### ISSUE TITLE
Migrate from Speccy to Spectral

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10001]
Hello,

We use [Speccy](https://github.com/wework/speccy) for linting API, but we should start using [Spectral](https://meta.stoplight.io/docs/spectral/README.md).

> What is the difference between Spectral and Speccy
> Speccy was a great inspiration for Spectral, but was designed to work only with OpenAPI v3. Spectral can apply rules to any JSON/YAML object (including OpenAPI v2/v3 and AsyncAPI).
> 
> Speccy has been abandoned, but Spectral is steaming ahead, adding loads of functionality like custom functions, exceptions, and AsyncAPI support.

Best regards,
Kamil
CC: @houqp

**Comment by houqp** [comment]
I agree, speccy seems like a dead project at this point.

**Comment by jpmarques66** [comment]
@mik-laj I can take this one.

**Comment by mik-laj** [comment]
I assigned you to this ticket.
