### ISSUE TITLE
Interval check operator should fail with null ratios

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#1000]
I ended up with a check that returned two 0's:

```
[2016-02-12 22:46:00,475] {check_operator.py:219} INFO - Ratio for COUNT(*): None 
 Ratio threshold : 1.6
[2016-02-12 22:46:00,476] {check_operator.py:231} INFO - All tests have passed
```

I think if the ratio comes back as None (0/0), it should fail the check, or at least make it configurable.

**Comment by r39132** [comment]
Hi @criccomini,
Can you provide some more context here? It seems to me that it is possible for counts to be 0 for a period of time. I agree that the ratios in general should reflect indeterminate status, but I am wondering if it makes sense here. Why doesn't None work for you here? 

```
for m in self.metrics_sorted:
            if current[m] == 0 or reference[m] == 0:
                ratio = None
            else:
                ratio = float(max(current[m], reference[m])) / \
                    min(current[m], reference[m])
            logging.info(rlog.format(m, ratio, self.metrics_thresholds[m]))
```

**Comment by criccomini** [comment]
Yea, I guess the problem that I had was that the table was empty, which wasn't expected. But I think that can be taken care of with a regular CheckOperator, so I'm going to close this.
