### ISSUE TITLE
Bugs with Airflow CLI backfill command for date in range

### ISSUE THREAD

**Issue by Chaho12** [apache/airflow#10028]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): CentOS Linux 7
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-1062.18.1.el7.x86_64 
- **Install tools**:
- **Others**:

**What happened**:

If I run backfill command on `airflow backfill example_bash_operator --reset_dagruns -s "2020-07-28 12:00:00+09:00" -e "2020-07-28 12:59:59+09:00"`, i get info message like below and cli command stops. But, the command is executed and dag is bagfilled if i check UI.
This happens if i set -s and -e value that does not match `execution_date` of the dag runs, but the execution_date is inside range of start and end date.

`[2020-07-28 17:09:46,181] {backfill_job.py:760} INFO - No run dates were found for the given dates and dag interval.`

This is applied same if I use `-y` or `--yes` option for backfill. Shows the message above and quits cli (but dag runs in background)

**What you expected to happen**:

If the dag run execution date is within the range of start and end date, it should run same as when I specify exact start and end time.

**How to reproduce it**:

1. Run dag several times, and find the execution time for each dags. (`airflow list_dag_runs`) (skip if you already have history of dags run)
2. Run `airflow backfill` with -s value as a time before the execution time, and -e value as time after the execution time.
ex) if execution time is `2020-07-28T05:00:00+00:00` then set -s as `2020-07-28T00:00:00+00:00` and -e as `2020-07-28T10:00:00+00:00`
3. Dag re-runs but, the cli message saids that it cannot find run dates.

![스크린샷 2020-07-28 오후 5 19 05](https://user-images.githubusercontent.com/25147023/88639136-68161a80-d0f7-11ea-85f6-b5023a05c8a4.png)

**Anything else we need to know**:

To simplify the situation, if there is a history of dag runs as following:

1: A-B (start-end)
2: D-E
3: F-G
4: I-J
5: L-M

If I run backfill with start=C, end=K; then dag run 2~4 runs but the info message shows and stops (but actually backfill is running in background)
So, I need to run backfill with option start=D, end=J in order to see the progress/logs of backfill cmd.

**Comment by eladkal** [comment]
This issue is reported against EOL version of Airflow.
Can you please let us know if the issue still happens in latest airflow version?

**Comment by potiuk** [comment]
> Can you please let us know if the issue still happens in latest airflow version?

Latest version is 2.5.2 (and 2.5.3 is being voted. 

Even if this could be somethign originated in open-source version, it's more than a year that your version is released and airflow open-source ONLY releases fixes in latest branch. We will not release any 2.2, 2.3, 2.4 any more. So I believe if you want to report it to us - you must check if the issue is stil in the latest version - it is very likely fixed already.
