### ISSUE TITLE
Remove try_number check to decide whether to monitor or create new POD for K8sPodOperator

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10021]
If the flag `reattach_on_restart` is True then a new pod gets created instead of monitoring the existing one ([line 285](https://github.com/apache/airflow/blob/2d25377a20cabac9ea1d26d015e6ac6e9606ac14/airflow/contrib/operators/kubernetes_pod_operator.py#L280-L285))

From @danccooper, the expected outcome is:
![image](https://user-images.githubusercontent.com/8811558/88578538-a00e5680-d040-11ea-9897-81501e04729d.png)

>the try number check I had in the original code (https://github.com/apache/airflow/pull/6377) was only there to add additional logging, not to drive any logic

The `same try_number` check is just redundant unless I am missing something i.e. if pod_exists and reattach_on_restart is true, it should just monitor whether the try_number is same or not.

@dancooper please feel free to expand on this, I just wanted to get at least what we talked about.

**Comment by danccooper** [comment]
You could argue that the second line (pod exists, same try number, reattach_on_restart=False) should monitor the existing pod as well, this would probably make sense.

However as discussed with @kaxil - `I've not seen a case where a pod already exists with the same try number, as every scenario that causes an untracked pod also causes the try number to increment.`  Except for the situation highlighted by @dakov in https://github.com/apache/airflow/pull/6377#discussion_r459648834 - completed pods are never removed from the k8s workloads.

This is the case to consider if we were to have the operator monitor an existing pod without a flag to disable (line 2).

**Comment by fabien-sarcel** [comment]
It seems to me that the try_number check can be useful, but v1.10.11 doesn't behave properly due to implementation errors.

In order to get the "expected behaviour", the first conditional step needs to run monitor_launched_pod (instead of create_new_pod_for_operator). And there is another error on the second conditional step, monitor_launched_pod need to be called with pod_list.items[0] instead of pod_list[0].

```
if len(pod_list.items) == 1 and \
        self._try_numbers_do_not_match(context, pod_list.items[0]) and \
        self.reattach_on_restart:
    self.log.info("found a running pod with labels %s but a different try_number"
                    "Will attach to this pod and monitor instead of starting new one", labels)
    final_state, result = self.monitor_launched_pod(launcher, pod_list.items[0])
elif len(pod_list.items) == 1:
    self.log.info("found a running pod with labels %s."
                    "Will monitor this pod instead of starting new one", labels)
    final_state, result = self.monitor_launched_pod(launcher, pod_list.items[0])
else:
    final_state, _, result = self.create_new_pod_for_operator(labels, launcher)

```

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/10056

**Comment by himabindu07** [comment]
This issue verified using 2.0.1 image, unable to reproduceble and can you please try with 2.0.0. 
Thanks
