### ISSUE TITLE
Re-Add try_number as identify label on a POD when using KubernetesPodOperator

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10020]
On our k8s cluster, we keep pods in the namespace for some time no matter the state they finished in (success, OOMKilled, evicted,....) -- I do not maintain the cluster and the decision is not up to me. Not having try_number as an identifying label of a pod makes airflow fail to launch another attempt.

_Originally posted by @dakov in https://github.com/apache/airflow/pull/6377#discussion_r459648834_

**Comment by OmairK** [comment]
Hi @kaxil is this issue up for taking? If so can you assign me this issue.

**Comment by dimberman** [comment]
Hi @kaxil @OmairK 

I don't think this is the right way to solve this issue.

In the case of pod failures, we WANT to reattach the first time so the failure can be reported.

Instead, we should add an annotation to that failed pod of "already_checked=True". This way the first time the task re-runs it would re-attach and fail, but the second time it would see the annotation and create a new pod instead.

**Comment by OmairK** [comment]
> Hi @kaxil @OmairK
> 
> I don't think this is the right way to solve this issue.
> 
> In the case of pod failures, we WANT to reattach the first time so the failure can be reported.
> 
> Instead, we should add an annotation to that failed pod of "already_checked=True". This way the first time the task re-runs it would re-attach and fail, but the second time it would see the annotation and create a new pod instead.

Hi @dimberman, should I open a new issue for this implementation? I would like to take this issue.

**Comment by dimberman** [comment]
@OmairK yes please

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/11368
