### ISSUE TITLE
DB Session leak in jobs.py?

### ISSUE THREAD

**Issue by yakneens** [apache/airflow#1002]
It appears that there may be a database session leak within the jobs module. I'm running a 100 node airflow cluster and am running out of database connections on my Postgresql server which has max_connections set at 1000. When I query the connections I see the following:

select count(*),state from pg_stat_activity group by state

count state
2   active
75  idle
495 idle in transaction

Looking into the "idle in transaction" connections it appears that they are all running this type of query:

"SELECT job.id AS job_id, job.dag_id AS job_dag_id, job.state AS job_state, job.job_type AS job_job_type, job.start_date AS job_start_date, job.end_date AS job_end_date, job.latest_heartbeat AS job_latest_heartbeat, job.executor_class AS job_executor_class, job.hostname AS job_hostname, job.unixname AS job_unixname 
FROM job 
WHERE job.id = 64157 
 LIMIT 1"

If I search through the jobs.py module there appear to be many spots that might result in this kind of query getting generated and not all of them close the session after querying. Could this be the source of the leak?

**Comment by yakneens** [comment]
Based upon further research it looks like there are two main sources of connection leaks. One is in the heartbeat method of the jobs module. That one is responsible for the huge number of idle in transaction connections. Calling settings.engine.dispose() in the heartbeat method seems to keep the number of these idle in transaction connections from growing unboundedly although 1000 active task instances still keeps about 300 DB connections busy at all times with the heartbeat. 

The other main source of leaks is in the TaskInstance class. Once I've dealt with the leak in jobs.py the number of "idle" connections begins to grown unboundedly until all connections run out and tasks start getting bounced. I've tried disposing the engine in a few key methods of that class but the session handling there is less straightforward and I haven't been able to figure it out yet.

**Comment by mistercrunch** [comment]
100 nodes! nice to hear that. Ok well I've done some research on this before. SqlAlchemy pools connection, so even when adequately closing the connections in the code, sqla does some magic that you may or may not want. 

Here's how it's configured in the Airflow code:
https://github.com/airbnb/airflow/blob/master/airflow/settings.py#L58

More about sqla session pooling:
http://docs.sqlalchemy.org/en/latest/core/pooling.html

It's probably safe to assume that it's nice for the web server and scheduler to have small connection pools, but that the individual `airflow run` commands should have none. Each heartbeat should pop a new connection and close it. I'm also ok with making those settings configurable.

**Comment by yakneens** [comment]
I agree about pooling on server vs. worker. Since workers scale out they should be extremely aggressive about letting go of DB connections. It looks like closing the session is not enough to close out the connections you actually need to dispose of the engine. I think I was able to pinpoint the culprit that was responsible for eating up connections ad infinitum. It was actually the TaskInstance class that was generating idle unclosed connections. Once I patched it, things got relatively under control. I will PR these changes some time this week. 

The heartbeat code still generates 1 idle_in_transaction connection per worker pretty much constantly. I was surprised to see this as I had switched the heartbeat to 60 seconds and dispose of the connections aggressively. I haven't had time to sort this out yet. It would be good to get this sorted as I want to be able to scale to about 6000 cores.

One thing that I noticed was that the session handling inside the airflow code isn't super consistent. Sometimes there is a centrally managed session and sometimes spurious sessions are created within methods. In general Sqlalchemy encourages session handling to be done centrally in a wrapper: http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#session-frequently-asked-questions
rather than in individual methods.

**Comment by r39132** [comment]
+1.

In general, db connections should be pooled for all usage. Some databases, e.g. Oracle, cannot handle constant db connection turnover - it results in fragmentation on the db side.  Not sure how viable that is here, but just wanted to share that thought.

**Comment by yakneens** [comment]
The more I think about this the more it seems that the necessity for workers to communicate with the database for heartbeats, is a scalability constraint. If you maintain a connection pool on each worker then you potentially need thousands of db connections just to maintain heartbeat. Why not have workers stick their updates into a queue that the server reads from? Why not have kill messages delivered via queue based events as well? None of these operations require transactionality that it would be worth to pay the scalability cost for.

**Comment by mistercrunch** [comment]
The airflow worker is a thin wrapper around the celery worker command and doesn't do much more than running the `airflow run` commands it receives from the queue. `airflow run` commands are executed as subprocesses and are the ones getting the connection count up.

From my perspective, the short term solution is to alter the sqlalchemy behavior when running `airflow run` to not maintain a pool. At every heartbeat (every minute, but configuraable), a connection would be created and destroyed.

Another longer term solution would be to go through a REST api call. I would prefer that over the message queue idea since only in the case of the CeleryExecutor we have the assumption that there is a message queue to be used.

**Comment by mistercrunch** [comment]
removed the bug tag as this is more of a scalability issue than a bug

**Comment by mistercrunch** [comment]
Alright, I gave it a shot as I know this issue will hit Airbnb soon (we had this issue in the past, but we extended our mileage with cranking up the number of sessions in MySql and reducing the pool sizes)
https://github.com/airbnb/airflow/pull/1021

@llevar please confirm that this reduces the number of sessions on your DB significantly

@r39132 @aoen

**Comment by yakneens** [comment]
Thanks for working on this Maxime. I'm currently running a massive job which will likely only finish by the end of the week. I should be able to test then.

**Comment by bolkedebruin** [comment]
@llevar any feedback? Closing the issue here in favor of a Jira issue if this issue persists.
