### ISSUE TITLE
Security context KubernetesPodOperator

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#10035]
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** 1.18

**What happened**:
During running KubernetesPodOperator with
 
`security_context={'runAsNonRoot':True,'runAsUser':1000,'runAsGroup':1000,'fsGroup':1000}`

I have following output:

`uid=1000(1000) gid=65533(nogroup) groups=65533(nogroup)`

During deployment execution via kubectl and set k8 security context as
`      securityContext: 
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
`
the output is 
`uid=1000(1000) gid=1000(1000) groups=1000(1000)`

**What you expected to happen**:
I think, there should be consistency between this two approaches based on the same image

**Comment by dimberman** [comment]
@gardnerdev can you try doing this using a pod_template_file or a pod object and see if that remedies the issue?

**Comment by kaxil** [comment]
@gardnerdev Please try this with >= **Airflow 2.0.1** and https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/1.0.2/ and let us know if you are able to reproduce it.
