### ISSUE TITLE
KubernetesExecutor/pod_template_file: PodGenerator should set restartPolicy: Never

### ISSUE THREAD

**Issue by arkady-emelyanov** [apache/airflow#10045]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  `minikube version: v1.12.1`

**What happened**:
When using `pod_template_file` without specifying `restartPolicy` in spec, `restartPolicy` receives value `Always` (which is default value for Kubernetes), which results `CrashLoopBackOff` for task pod (Kubernetes tries to restart pod upon completion). Explicitly setting up `restartPolicy: Never` in `pod_template_file` manifest solves the issue.

**What you expected to happen**:
PodGenerator should explicitly set `restartPolicy: Never` when processing `pod_template_file`.

**Comment by himabindu07** [comment]
I verified using 2.0.1 and not able to reproduceble, can you try it with Airflow 2.0.1
Thanks

**Comment by arkady-emelyanov** [comment]
@himabindu07 Don't have any running Airflow instance nearby, but I have checked to source code and it seems issue indeed has been resolved.

I think issue can be closed now.
