### ISSUE TITLE
Putting a task ON HOLD

### ISSUE THREAD

**Issue by afsalabdup** [apache/airflow#10044]
Feature to put a future instance task ON HOLD is missing in Airflow.  Is there any way to achieve this functionality in Airflow. Appreciate any help.

**Comment by eladkal** [comment]
How is that different than setting the DAG to off?

**Comment by afsalabdup** [comment]
I want to put a specific task on hold, not whole dag.

**Comment by eladkal** [comment]
Duplicate of https://github.com/apache/airflow/issues/9298
