### ISSUE TITLE
Standard way of submitting and cleaning up DAGs via APIs 

### ISSUE THREAD

**Issue by singhania** [apache/airflow#10057]
**Description**
Currently airflow doesn't provide a way to submit a DAG (an experimental api exists but not part of airflow deployment).
Similarly it provides a way to delete dag but doesn't cleanup the file.

**Use case / motivation**
We have a requirement where I want to generate a DAG programatically and then submit to airflow.Similarly based upon user request would like to cleanup the same.
But as there are no standard way, this can depend on how you airflow cluster is provisioned.If this can be standardised .

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/9937
