### ISSUE TITLE
Raise an exception when setting dependencies on task across DAG objects

### ISSUE THREAD

**Issue by davidsbatista** [apache/airflow#1005]
Can I import task between different DAG definition files, e.g:

`from dag_a import dag_b_task_one`
`from dag_a import dag_b_task_two`

`dag = DAG('dag_b', default_args=default_args, schedule_interval='0 1 * * *')`

`prepare_events = BashOperator(`
   `task_id='dag_a_task_one',`
   `bash_command='echo test',`
   `dag=dag)`

`# only start this DAG if dimensions are updated`
`dag_a_task_one.set_upstream(task_one)`
`dag_a_task_two.set_upstream(task_two)`

Running python over this definition file gives no errors, though, in the Airflow webserver console the graph/tree don't show the dependencies between tasks from different graphs. So, I'm not sure if this will DAG definition captures the dependencies.

**Comment by mistercrunch** [comment]
The current way to have dependencies on tasks from another DAG is to use the `ExternalTaskSensor` as documented here:
http://pythonhosted.org/airflow/code.html#airflow.operators.ExternalTaskSensor

We should raise an exception (or create an `ExternalTaskSensor` on your behalf!) when trying to reference a task from another DAG.
