### ISSUE TITLE
ldap configuration when rbca is true

### ISSUE THREAD

**Issue by sudarshan2906** [apache/airflow#10058]
I am configuring ldap when rbca is true
webconfiguration.py
```
import os
from airflow import configuration as conf
from flask_appbuilder.security.manager import AUTH_LDAP
basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = conf.get('core', 'SQL_ALCHEMY_CONN')

CSRF_ENABLED = True

AUTH_TYPE = AUTH_LDAP

AUTH_ROLE_ADMIN = 'Admin'
AUTH_USER_REGISTRATION = True

AUTH_USER_REGISTRATION_ROLE = "Admin"
# AUTH_USER_REGISTRATION_ROLE = "Viewer"

AUTH_LDAP_SERVER = 'ldaps://ldap:636/'
AUTH_LDAP_SEARCH = "DC=myorg,DC=net"
AUTH_LDAP_BIND_USER = 'CN=admin,DC=myorg,DC=net'
AUTH_LDAP_BIND_PASSWORD = 'password'
AUTH_LDAP_USE_TLS = False
```
airflow.cfg
```
authenticate = True
rbac = True
```

I also created a admin user using
```
airflow create_user
```

But in login page no matter what i type it is giving me same message that - Invalid login. Please try again.

**Comment by sudarshan2906** [comment]
I found this when seeing in logs 
```
[2020-07-30 13:15:20,214] {manager.py:838} DEBUG - LDAP bind with: admin XXXXXX
[2020-07-30 13:15:20,247] {manager.py:952} ERROR - {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []}
```

**Comment by sudarshan2906** [comment]
When trying to logging getting this error in the logs
```
[2020-07-30 14:50:07,305] {manager.py:815} DEBUG - LDAP indirect bind with: CN=admin,dc=example,dc=org
[2020-07-30 14:50:07,308] {manager.py:817} DEBUG - LDAP BIND indirect OK
[2020-07-30 14:50:07,309] {manager.py:836} DEBUG - LDAP bind failure: user not found
[2020-07-30 14:50:07,309] {manager.py:911} WARNING - Login Failed for user: admin
```
There is a user admin in AD. But i havn't created it in airflow. I tried using airflow cli to create user but that gives error as it requires password. How can create a user in airflow and bind it ldap user?

**Comment by sudarshan2906** [comment]
The error was because there was no and min user created in airflow. also i have to append the domain to the username.

**Comment by dprateek1991** [comment]
@sudarshan2906 - I'm facing similar issue at my end as well. I would like to understand, do we need to manually create the users in Airflow as well after configuring LDAP ?

Airflow does not automatically use users already present in LDAP to authenticate to Airflow UI
