### ISSUE TITLE
Use Cassandra as backend to store task results (from Celery)

### ISSUE THREAD

**Issue by Xrampino** [apache/airflow#1007]
Using Cassandra as `celery_result_backend` doesn't work, notably because those config keys are not passed to Celery in `celery_executor.py` :

```
CASSANDRA_SERVERS
CASSANDRA_KEYSPACE
CASSANDRA_TABLE
CASSANDRA_READ_CONSISTENCY
CASSANDRA_WRITE_CONSISTENCY
CASSANDRA_ENTRY_TTL
```

Additionally, `CASSANDRA_SERVERS` is a python list of hosts, and `configuration.py` doesn't have a `getList` method.

I hacked this a little to make it work, but I still finally got, when starting a worker,

`[2016-02-15 17:19:09,071: WARNING/Worker-14] Cassandra error: InvalidRequestException(why="(String didn't validate.) [celery][tasks][traceback] failed validation"). Retrying...`

Any clues ?

**Comment by mistercrunch** [comment]
That's probably more of a question to ask on the Celery/Cassandra side of things. We're open to enable the hooks and configurations you need to make this work though, send a PR with the hooks you need once you figure it out!
