### ISSUE TITLE
Make SparkSubmitHook capable of executing spark-submit through SSH Connection

### ISSUE THREAD

**Issue by flolas** [apache/airflow#10073]
**Description**
I want to add a functionality in SparkSubmitHook; connect to a remote server though SSH and execute spark-submit. This would be great when working with multiple spark clusters with an edge node for each cluster and installing an airflow's worker into edge node is not possibly.

I have a working solution but now i'm currently generating tests, when done, will submit a PR.

Felipe

**Comment by ashb** [comment]
Apache Livy hook/operator may be easier than this (which exists now) -- spark submit via SSH feels almost a bit too specialized...

**Comment by flolas** [comment]
@ashb You are right, I left the issue here just in case the community needed it, but if it not the case, maybe might be better not merging onto airflow official provider packages. Closing.
