### ISSUE TITLE
Migration guide for Airflow 2.0

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10089]
Hello,

We have a lot of entries in UPDATING.md, but there is no full procedure that will answer the most important question - how to update Airflow to the latest version. Users expect step-by-step instructions from us that will explain what they should do. The guide should contain information about `airflow upgrade-check`, `airflow db upgrade`, backport package, etc.

Best regards,
Kamil

**Comment by ryw** [comment]
guide exists @ https://github.com/apache/airflow/blob/master/UPGRADING_TO_2.0.md - ok to close this?

**Comment by gflores1023** [comment]
It's interesting that the guide actually doesn't tell you when or how to upgrade to v2.0. I assume it would be after Step 5. Related to #8158, it would be useful to know what the actual commands to execute and in what order. mik-laj mentions "airflow upgradedb" above but I don't see instructions for it in the guide. Just my 2 cents

**Comment by potiuk** [comment]
> It's interesting that the guide actually doesn't tell you when or how to upgrade to v2.0. I assume it would be after Step 5. Related to #8158, it would be useful to know what the actual commands to execute and in what order. mik-laj mentions "airflow upgradedb" above but I don't see instructions for it in the guide. Just my 2 cents

Yep. Thanks for pointing that out! 

That was exactly what we discussed yesterday at the Airflow 2.0 weekly call (see the notes from @vikramkoka ) https://lists.apache.org/thread.html/r2d4e08ffd5247b3df8c9a5e250b5b2625cadd642da1fcd007a3db46b%40%3Cdev.airflow.apache.org%3E

**Comment by vikramkoka** [comment]
@mik-laj @potiuk @kaxil @ashb 
Now that we published the "upgrading-to-2" and "upgrade-check" documents, I think this can be closed. Do you agree?

**Comment by potiuk** [comment]
Yep
