### ISSUE TITLE
GCPTransferOperator fails if Boto is not installed with "AWSHook TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by kundan1301** [apache/airflow#10087]
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: composer

- **Cloud provider or hardware configuration**: google
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: AWSHook throwing TypeError: 'NoneType' object is not callable

**What you expected to happen**:
It should throw actual error. 

**What do you think went wrong? **: 

Catching exception but not logging exception. 
https://github.com/apache/airflow/blob/1.10.9/airflow/contrib/operators/gcp_transfer_operator.py#L55
At this line AWSHook is set to None, before setting that we should log exception. Cloud composer don't install boto3 by default, because of this an exception is thrown  which causes AWSHook set to None.  Which in turn throwing error at line 
https://github.com/apache/airflow/blob/1.10.9/airflow/contrib/operators/gcp_transfer_operator.py#L71

stacktrace

```python traceback
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 972, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/contrib/operators/gcp_transfer_operator.py", line 638, in execut
    TransferJobPreprocessor(body=body, aws_conn_id=self.aws_conn_id, default_schedule=True).process_body(
  File "/usr/local/lib/airflow/airflow/contrib/operators/gcp_transfer_operator.py", line 108, in process_bod
    self._inject_aws_credentials(
  File "/usr/local/lib/airflow/airflow/contrib/operators/gcp_transfer_operator.py", line 71, in _inject_aws_credential
    aws_hook = AwsHook(self.aws_conn_id)
```

 

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Hey @kundan1301 - would you mind contributing a fix to that ? I will be happy to review!

**Comment by kundan1301** [comment]
@potiuk Sure I will fix and raise a PR.

**Comment by JeffryMAC** [comment]
this is not really AWS hook issue
It's a bug in GCP transfer operator

**Comment by shahar1** [comment]
@eladkal please assign me

**Comment by shahar1** [comment]
The file does not exist anymore (Airflow 1.x), I checked the equivalent operators in Airflow 2.x (`gcs_to_s3`, `s3_to_gcs`) and the imports seem ok.
I suggest closing this issue.
