### ISSUE TITLE
re-read airflow.cfg

### ISSUE THREAD

**Issue by davidsbatista** [apache/airflow#1009]
is there any way for airflow to re-read the airflow.cfg and update the parameters?

**Comment by davidsbatista** [comment]
just realized this is done automatically, upon checking the Configuration through the webserver interface. probably you can add a line explaining this to the documentation

**Comment by r39132** [comment]
I'm not sure it is reloaded everywhere. For runtime and dynamic config, it's better to use Variables. 

Can you describe your use case and why Variables won't be a good fit?

**Comment by davidsbatista** [comment]
Need to change the dags_folder variable.

**Comment by bolkedebruin** [comment]
If configuration is reloaded it is reflected everywhere. This was implemented a couple of months ago to allow testing for different authentication backends. Of course if a dag or somethings else has already been instantiated and a configuration item is localized (ie, self.my_item = configuration.get("item") ) then this will not get updated.

**Comment by r39132** [comment]
@bolkedebruin This is good to know. Then there is a case like this in the jobs.py script, which specified a default for heartrate in the `__init__` method. This would not be updated correct?

```
    def __init__(
            self,
            executor=executors.DEFAULT_EXECUTOR,
            heartrate=conf.getfloat('scheduler', 'JOB_HEARTBEAT_SEC'),
            *args, **kwargs):
```

**Comment by bolkedebruin** [comment]
Absolutely correct.
