### ISSUE TITLE
Double check UPDATING.md for "2.0" doesn't include breaking changes in import paths

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10104]
Hello, 

We should check if all operators and hooks available in Airflow 1.10 are also importable in Airflow 2.0. All these changes should also be included in
https://github.com/apache/airflow/blob/master/tests/deprecated_classes.py

Technically speaking, we should install Airflow 1.10, generate a list of operators/hooks, and then try to import each of it on Airflow 2.0.
In order to generate a list of operators, we can use this script:
https://github.com/apache/airflow/blob/master/scripts/list-integrations.py

If anyone is interested in this task, I am willing to provide all the necessary information.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst).

Best regards,
Kamil Breguła

**Comment by bhavaniravi** [comment]
I would like to take this up, would give me a head start with 2.0

**Comment by mik-laj** [comment]
@bhavaniravi I assigned you to this ticket.

**Comment by bhavaniravi** [comment]
@mik-laj I have a question 

How does `deprecated_classes` handle backward compatibility when importing modules instead of classes 

Example:

```
from airflow.contrib.hooks import gcp_kms_hook"
```
Instead of 
```
from airflow.contrib.hooks.gcp_kms_hook import GoogleCloudKMSHook
```

**Comment by mik-laj** [comment]
@bhavaniravi We have two deprecation messages. One for the module and one for the classes. 
<img width="723" alt="Screenshot 2020-08-20 at 03 02 03" src="https://user-images.githubusercontent.com/12058428/90704851-de8ae000-e291-11ea-8464-649794871195.png">
<img width="906" alt="Screenshot 2020-08-20 at 03 02 22" src="https://user-images.githubusercontent.com/12058428/90704856-e0ed3a00-e291-11ea-97ee-51fabfcdf11e.png">
When it comes to use it for Python it makes no difference if you import the entire module and use the class referencing, as attributes, or import each class in your modulle.

**Comment by ryw** [comment]
@bhavaniravi are you still working on this?

**Comment by kaxil** [comment]
Do we need to anything more here? Is this issue for core operators / AIP-21 ?

https://github.com/apache/airflow/blob/master/UPDATING.md#changes-to-import-paths

**Comment by mik-laj** [comment]
As I was checking, all imports worked.
