### ISSUE TITLE
TriggerDagRunOperator not finding DAG

### ISSUE THREAD

**Issue by Rulevoid** [apache/airflow#1010]
When attempting to execute a dag manually via an external script like the below, I receive the following error:

airflow.utils.AirflowException: Argument ['owner', 'task_id'] is required

The trigger_dag_id is the correct name of the dag and I have followed the tutorial with the same dag working fine.  It is as if the TriggerDagRunOperator is not "seeing" the dag.  If I enter a random value for trigger_dag_id, I receive the same result.  Is this an issue or is my example below not correct?  Thanks!

```

from airflow.operators import TriggerDagRunOperator

def set(context, dro):
    # Pass some data to the dag
    dro.payload={"something": "sofake"}
    return dro

tdro = TriggerDagRunOperator(trigger_dag_id="good_dag", python_callable=set)
```

**Comment by r39132** [comment]
Refer to the example I provide as the solution to the following issue : https://github.com/airbnb/airflow/issues/1001

You are missing the DAG definition, e.g. from my example on issue 1001.

```
dag = DAG(dag_id='test_trigger_dag_run_for_Sid',
          default_args={"owner" : "me",
                        "start_date":datetime.now()},
          schedule_interval='*/1 * * * *')
```

**Comment by r39132** [comment]
Closing issue. If you still have problems after reading my explanation on 1001, feel free to "@" ping me on gitter or here.

**Comment by pedrorjbr** [comment]
@Rulevoid how did you getting the payload on the triggered dag?

**Comment by r39132** [comment]
FYI, I have provided an example of passing state to the Python callable in https://github.com/airbnb/airflow/issues/1029
