### ISSUE TITLE
Double check UPDATING.md for "2.0"  include all changes in import paths

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10108]
Hello,

Some users may want to have easy access to the list of import path changes that were made in Airflow 2.0 Currently, this information is only available in `tests/` directory. 
https://github.com/apache/airflow/blob/master/tests/deprecated_classes.py
and README files for each backport packages.
https://pypi.org/project/apache-airflow-backport-providers-jdbc/

I think that it is worth creating a new UPDATING-IMPORT-CHANGES.md file that will contain similar tables so that everyone can check where the class is without having to look at the source code.

Best regards,
Kamil Breguła

**Comment by potiuk** [comment]
We should have either: 
* have simply a directory of all provider packages with links to README + core description

or

* combine the information in READMES automatically in one file (automatically)

**Comment by ashb** [comment]
Done a while ago now I think.
