### ISSUE TITLE
TypeError exception, comparing NoneType and int

### ISSUE THREAD

**Issue by kundan1301** [apache/airflow#10113]
**Apache Airflow version**: 1.10.9

**Environment**: composer

- **Cloud provider or hardware configuration**: google cloud

**What happened**:
TypeError: '>' not supported between instances of 'NoneType' and 'int
At line https://github.com/apache/airflow/blob/1.10.9/airflow/contrib/operators/gcp_transfer_operator.py#L643
None is passed as default timeout but at line 
https://github.com/apache/airflow/blob/1.10.9/airflow/contrib/hooks/gcp_transfer_hook.py#L338 
its comparing against int. 

**stacktrace**
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 972, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/contrib/operators/gcp_transfer_operator.py", line 643, in execut
    hook.wait_for_transfer_job(job, timeout=self.timeout
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_api_base_hook.py", line 284, in wrapper_decorato
    return func(self, *args, **kwargs
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_transfer_hook.py", line 338, in wait_for_transfer_jo
    while timeout > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int

looking at source code we may face same exception at line 
https://github.com/apache/airflow/blob/1.10.9/airflow/contrib/operators/gcp_transfer_operator.py#L781  as well. 

**What you expected to happen**:
Either pass significantly large value as default timeout for example (10**18) or handle None type as special case while checking for status in while loop. 

**Anything else we need to know**: 
I can fix this and raise a PR. Let me know.

**Comment by mik-laj** [comment]
Helllo. 
Does this problem also occur in Airflow from the master branch?  If not, then you can start using Airflow 2.0 operators thanks to [backport packages](https://github.com/apache/airflow#backport-packages).
Best regards,
Kamill

**Comment by kundan1301** [comment]
@mik-laj I don't think same problem will occur in Airflow 2.0. On this line 
https://github.com/apache/airflow/blob/1d68cd2929dbc55b73fed2417cb6ecbba162e4f8/airflow/providers/google/cloud/hooks/cloud_storage_transfer_service.py#L464
I can see that if timeout is None it is set to 60s. 

Let me know if we still want to fix for branch 1.10.* . Otherwise we can close this.

**Comment by mik-laj** [comment]
@kundan1301 We no longer update operators in Airflow 1.10. I recommend installing backport packages. https://github.com/apache/airflow#backport-packages
