### ISSUE TITLE
Use Hash / SHA to compare Serialized DAGs

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10116]
**Description**

Currently, we compare entire Serialized blobs to determine if the DAG changed or not before we write the Serialized DAGs to the Database which can be expensive.
Instead, we will store the HASH / SHA of the Serialized JSON and store that in a separate column in the serialized_dag table.
And before writing the Serialized Blob, we will compare the SHA to decide if DAG changed.

**Comment by potiuk** [comment]
Oh yeah!

**Comment by kaxil** [comment]
Planning to get to this by tomorrow so we can release it with Airflow 1.10.12

**Comment by potiuk** [comment]
What are the plans for 1.10.12?

**Comment by kaxil** [comment]
> What are the plans for 1.10.12?

Mostly to fix all the Kubernetes related issues that came of the Kubernetes Refactors in Airflow 1.10.11 -- https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Ak8s+milestone%3A%22Airflow+1.10.12%22
