### ISSUE TITLE
Better status monitoring in dag job runs api 

### ISSUE THREAD

**Issue by joshi95** [apache/airflow#10125]
Registering this as a feature that can help people keep track of job run via api better.

**Description**

Currently users can only get the status of a dag run via checking the state of the sepecific dag runs or get all the status of a dag which seems very costly on users front as he will have to filter them out on client level. Support for this feature will allow users to filter out dags in the dag get runs api and get specific response based on other filters like run_id, execution_date etc.

**Example**
The endpoint (/dags/<string:dag_id>/dag_runs)  currently support only status as an extra key argument in get api. What would have been better is support for not only status but other fields also for eg execution_date, run_id etc.

**Use case / motivation**
Will help users to monitor or get the status of the dag in deep down level and they can use some polling based mechanism to check the health of the runs of the dag.

**Comment by eladkal** [comment]
This request was raised against the experimental API which is no longer enhanced.
In the Rest API the dagrun endpoint require a run_id as you mentioned in your example.

If something is still missing please open a new issue about the rest api and explain the use case.
