### ISSUE TITLE
Allow AWS RedshiftToS3Transfer To Run a Custom Query

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#10124]
Registering this as it seems like a feature that people need.

**Description**

This has been requested by people on slack.
also https://issues.apache.org/jira/browse/AIRFLOW-6794

stale PR that wasn't finished https://github.com/apache/airflow/pull/7688

Nikhil Goyal reported a workaround on slack:
run custom sql using AWS UNLOAD command inside the postgres operator

**Comment by AratiNagmal** [comment]
I would like to work on this issue, can this be assigned to me?

**Comment by kaxil** [comment]
Assigned to you @AratiNagmal 🚀

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/14177
