### ISSUE TITLE
Job Schedule Interval on 2nd & 4th Tuesday

### ISSUE THREAD

**Issue by hlokired** [apache/airflow#10123]
Hi Team,

1.We have a requirement where we need to schedule the job Bi-Weekly. i.e. on 2nd and 4th Tuesday.
Could you please help us on how can we set the schedule interval in Airflow DAG Job.

2. Also in other requirement we tried to schedule individual jobs for 2nd Tuesday and 4th Tuesday. 
i.e. schedule_interval= "0 2 * * 2#2" for 2nd Tuesday
 schedule_interval= "0 2 * * 2#4" for 4th Tuesday
Could you please let us know is the schedule interval which I have shared is wrong.

Thanks,

**Comment by eladkal** [comment]
@uranusjr isn't that scheduling requirement covered fully by AIP-39?

**Comment by uranusjr** [comment]
Yes, this should be possible with custom timetables.
