### ISSUE TITLE
Pool not used in "airflow run" CLI command when using default executor

### ISSUE THREAD

**Issue by rdavison** [apache/airflow#1012]
Airflow Version: 1.6.2
Executor: CeleryExecutor

Symptoms:
1) Create a new pool in the UI
2) Use `airflow run dag_id task_id date -i --pool pool_id`
3) Observer that the pool never gets populated

Please let me know if there is any other info I can provide.

**Comment by r39132** [comment]
Which version of airflow are you using (can you just print `git log | head`)? Do you also see this behavior when running in the UI or via the CLI with LocalExecutor (i.e. specify `-l`)?

**Comment by r39132** [comment]
Also, can you confirm that you are not seeing anything under `http://<your_airlfow_webserver>:8080/admin/taskinstance/?flt1_pool_equals=<your_pool_name>` -- Note: replace the 2 placeholders above. Share a screen shot here.

**Comment by rdavison** [comment]
Airflow version is 1.6.2, I installed via `pip`, not via `git`.  

If I run with LocalExecutor it works and populates the pool page, otherwise it just looks like this:
http://imgur.com/5sjlpSr

**Comment by r39132** [comment]
Thanks for https://github.com/airbnb/airflow/pull/1013 

I happened to find and verify the same fix, so I know yours works. I'll await the requisite coverage tests to pass before merging. Thanks for the fix.
