### ISSUE TITLE
Airflow 1.10.x (ex. 1.10.9) allows to modify DAG description via web UI but does not modify file

### ISSUE THREAD

**Issue by anitakar** [apache/airflow#10133]
In airflow UI next to every DAG there is an edit button. You can click it, modify description and save it. But the file underneath does not actually change. Next time when DAG is reloaded all changes are lost.

**Comment by mik-laj** [comment]
@anitakar Do you want to take care of this ticket or do you need help?

**Comment by mik-laj** [comment]
Does this problem occur in RBAC or non RBAC UI or both?

**Comment by anitakar** [comment]
non RBAC UI, and change of view from tree to graph for example works. It persists.

**Comment by anitakar** [comment]
I can take care of that

**Comment by vikramkoka** [comment]
@mik-laj Can this be closed?
