### ISSUE TITLE
Deprecate BaseHook.get_connections method

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10135]
Hello,

Previously, Airflow allowed users to add more than one connection with the same `conn_id` and on access, it would choose one connection randomly Now, we marked field `conn_id` in table `Connection` as unique.
More information:
https://github.com/apache/airflow/pull/9067/files

For this reason, the `airflow.hooks.base_hook.BaseHook.get_connections` method is no longer applicable, because we have `airflow.hooks.base_hook.BaseHook.get_connection` method that returns only one connection. I think, we should mark it as deprecated to be able to delete it in the future. We should also update the use of this method.

Best regards,
Kamil

CC: @Hasan-J

**Comment by potiuk** [comment]
It will work fine without it (get_connections() returns [connection] but I agree it would be nice to remove the usage of it and replace it with get_connection - it might also simplify some of the code.

**Comment by Hasan-J** [comment]
Hey, I will open a PR soon.

**Comment by Hasan-J** [comment]
I opened a draft and need some confirmations. Please check the PR conversation when you have time :)
