### ISSUE TITLE
SSH operator error

### ISSUE THREAD

**Issue by xuhongtao0101** [apache/airflow#10149]
[2020-08-02 15:56:07,741] {{taskinstance.py:1047}} ERROR - SSH operator error: 'utf-8' codec can't decode bytes in position 16382-16383: unexpected end of data
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/ssh_operator.py", line 139, in execute
    self.log.info(line.decode('utf-8').strip('\n'))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 16382-16383: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/ssh_operator.py", line 173, in execute
    raise AirflowException("SSH operator error: {0}".format(str(e)))
airflow.exceptions.AirflowException: SSH operator error: 'utf-8' codec can't decode bytes in position 16382-16383: unexpected end of data

**Comment by xuhongtao0101** [comment]
I made an error using SSH operator to execute Python script remotely, which seems to be a log problem. However, my log level has been set to warning, so I still report an error. Please help me solve this problem

**Comment by kumarprabhu1988** [comment]
@xuhongtao0101 were you able to resolve the error? I see the same error when using SSHOperator.

**Comment by abhaypartap** [comment]
{
   "charset": "utf8",
   "cursorclass": "sscursor",
   "local_infile": true
}

Try passing those arguments in Extras of SSH connection

**Comment by xuhongtao0101** [comment]
> @xuhongtao0101 were you able to resolve the error? I see the same error when using SSHOperator.

I set the encoding in the remote server environment variable to UTF8, and the PY script encoding to UTF8, which seems to solve this problem. I haven't seen any similar errors since

**Comment by abhaypartap** [comment]
okay that's good

**Comment by eladkal** [comment]
@abhaypartap This sounds like a good information to include in the [documentation of SSH connection ](https://github.com/apache/airflow/blob/master/docs/apache-airflow-providers-ssh/connections/ssh.rst)
Would you mind creating a PR to add it ?

**Comment by Junnplus** [comment]
@eladkal I think the answer of @abhaypartap  is not helpful
