### ISSUE TITLE
SqliteHook hard codes connection attribute

### ISSUE THREAD

**Issue by coopergillan** [apache/airflow#10147]
**Apache Airflow version**: current `master`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: N/A

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**: Looking at `SqliteHook` it appears that the call to `get_connection` is hardcoding the `conn_name_attr` to `sqlite_conn_id`. However, the `DbApiHook` allows `conn_name_attr` to be overridden to support multiple named connections.

This is similar to an issue in `PostgresHook` fixed by f823a66001c9f3682153acbf27bca137d0f4a7ec around a year ago.

**What you expected to happen**: The call to `get_connection` should use whatever the `conn_name_attr` has been set to.

**How to reproduce it**: If a subclass of the hook is created with an overridden `conn_name_attr`, calls to `get_conn` will still hit the original connection specified by `sqlite_conn_id`.

**Comment by mik-laj** [comment]
FYI:

> If you create pull-request, you don't have to create an issue first, but if you want, you can do it. Creating an issue will allow you to collect feedback or share plans with other people.

https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow

**Comment by coopergillan** [comment]
@mik-laj - ah, that's right. Thanks for the reminder. I actually created the issue thinking I would come back to it after adding the type annotations. But then when I ran the type checking it helped point out the issue.
