### ISSUE TITLE
Ensure airflow database is created with timezone set to UTC

### ISSUE THREAD

**Issue by csubu** [apache/airflow#1015]
Airflow creates its metadata database using airflow initdb. Since its best practice to have everything in UTC to avoid issues with DST, airflow should create its metadata database with timezone set to UTC. 

In addition to this, the documentation should reflect that its best to set the TZ of the machines running airflow {scheduler, worker, webserver} to UTC

**Comment by BradHolmes** [comment]
Our host that is running the scheduler is a shared machine, and we cannot change the tz. This caused DagRuns to have an execution date in UTC, but it was checked against local time.  A simple fix in models.py `TaskInstance.is_queueable` is to change `datetime.now()` to `datetime.utcnow()`.  

Would this be possible?
