### ISSUE TITLE
Airflow documentation should have a section for Best Practices,

### ISSUE THREAD

**Issue by csubu** [apache/airflow#1016]
and for operations, deployment, configuration, monitoring, alerting, security, design, architecture.

**Comment by kretes** [comment]
Agreed. Starting with Airflow I feel the software itself isn't helping you go with the best practice and it is easy to configure something in a way that is not working correctly

**Comment by r39132** [comment]
I've started this. I need the rest of the community to add to it.
https://github.com/airbnb/airflow/wiki/Airflow-Common-Pitfalls

@mistercrunch @criccomini @bolkedebruin
