### ISSUE TITLE
Add capability to specify gunicorn access log format for airflow webserver

### ISSUE THREAD

**Issue by aranjanthakur** [apache/airflow#10166]
**Description**

Currently gunicorn access logs don't include response time. In gunicorn we can specify access-logformat to include response time. When running airflow webserver we should be able to specify this format by either defining it in airflow.cfg or passing as argument in airflow webserver command.

**Use case / motivation**

We want to monitor airlfow response time.

**Related Issues**

None

**Comment by mik-laj** [comment]
Hi. Would you like to prepare a PR to fix this problem? I will gladly support you if you have any questions.

**Comment by aranjanthakur** [comment]
Hi @mik-laj , I have made the required changes. Could you please guide how I can test it?
I have run integration tests in breeze env. I want to build it locally and test the webserver.

**Comment by mik-laj** [comment]
Can you create a PR?

**Comment by aranjanthakur** [comment]
https://github.com/apache/airflow/pull/10261 
Please take a look

**Comment by aranjanthakur** [comment]
@mik-laj I have added the test cases, could you please review the changes 
https://github.com/apache/airflow/pull/10261

**Comment by aranjanthakur** [comment]
@turbaszek @mik-laj let me know if any other changes are required for this feature add
