### ISSUE TITLE
BIgQuery operators from backport packages and DAG Serialization

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10171]
Dzień Dobry (Good morning),

I heard that the BigQuery operators from Backport packages do not work properly when DAG serialization is enabled on the latest version of Airflow.
```
KeyError: "Operator Link class 'airflow.providers.google.cloud.operators.bigquery.BigQueryConsoleLink' not registered"
```
We should confirm this information and make a change to ensure compatibility between the latest version of Airflow and backport packages.

In Airflow 2.0, this error does not occur. It may be related to this change, but I'm not sure.
https://github.com/apache/airflow/pull/7327/files

Dużo miłości (Lots of love),
Kamil Breguła

CC: @anitakar @kaxil

**Comment by mik-laj** [comment]
CC: @potiuk

**Comment by potiuk** [comment]
@kaxil @dimberman -> would be great to fif it before 1.10.12 gets released - so if we are very close to cutting 1.10.12 we might speed up testing and fixing this one. Are we very close to release 1.10.12 ?

**Comment by kaxil** [comment]
> @kaxil @dimberman -> would be great to fif it before 1.10.12 gets released - so if we are very close to cutting 1.10.12 we might speed up testing and fixing this one. Are we very close to release 1.10.12 ?

Still not that close, k8s fixes have been a pain. At this rate we can look at cutting RCs next week -- not happening this week. So yeah I would say we have some time :)

**Comment by potiuk** [comment]
> Still not that close, k8s fixes have been a pain. At this rate we can look at cutting RCs next week -- not happening this week. So yeah I would say we have some time :)

Purrfect :cat: !

**Comment by kaxil** [comment]
Any updates on this @potiuk? I am going through all 1.10.12 issues currently -- would love to create RCs by EOD tomorrow.

**Comment by potiuk** [comment]
@turbaszek :) ? any news /updates here ?

**Comment by turbaszek** [comment]
Confirmed that #7327 fix this issue. I was able to replicate the behavior and I've tested BigQuery operators from master with 1.10.10

**Comment by kaxil** [comment]
Fixed by https://github.com/apache/airflow/pull/10318
