### ISSUE TITLE
Move relevant information from Commiter's guide to CONTRIBUTING.rst

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10179]
**Description**

The old documentation for [Commiter's guide](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62696156) should be reviewed and incorporated in [CONTRIBUTING.rst](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by mik-laj** [comment]
I think, we should move it to the "dev" part of the Airflow Repo. The CONTRIBUTING.rst file is for new contributors and is already quite long. I don't think we should extend it, but try to make it more accessible to new people.

**Comment by potiuk** [comment]
I reviewed it and decided to move it to CONTRIBUTING.rst as is it is an important
documentation on what policies we have agreed to as community and
also it is a great resource for the contributor to learn what are
the committer's responsibilities.
