### ISSUE TITLE
task_log_prefix_template configuration is not documented and doesn't work

### ISSUE THREAD

**Issue by bellhea** [apache/airflow#10188]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.10.0

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): rhel 7.7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I am trying to use the configuration setting: [task_log_prefix_template](https://github.com/apache/airflow/blob/master/airflow/config_templates/default_airflow.cfg#L276)
Firstly, I don't see it in the documented list of [configurations](https://airflow.apache.org/docs/stable/configurations-ref.html), even though it's in the source code as you can see.
I am setting it as an environment variable like so: `AIRFLOW__CORE__TASK_LOG_PREFIX_TEMPLATE: {{ task_instance_key_str }} `
However, it's not being picked up and the task logs don't have the prefix I've specified.

**What you expected to happen**:
The logs to be outputted with the prefix specified in the environment variable, in this instance the `task_instance_key_str` macro.

**How to reproduce it**:
Simply attempt to set the environment variable described above and view the logs.

**Anything else we need to know**:

**Comment by mik-laj** [comment]
This configuration option is only available in the development version from the master branch. Here is the documentation for this option.
You pasted the link to the documentation for the stable version (currently: 1.10.11).
https://airflow.readthedocs.io/en/latest/configurations-ref.html#task-log-prefix-template

**Comment by bellhea** [comment]
Right ok, thanks for that. 
So instead I'm trying to use a custom logging config and implement something similar, would appreciate some guidance.. I have implemented the below custom "task_instance" formatter. I thought I should be able to see the actual dag and task ids in the log by using the relevant macros, but I'm just seeing the string "{{ti.dag_id}}-{{ti.task_id}}" itself. Any ideas?
```
LOGGING_CONFIG = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'airflow': {
            'format': LOG_FORMAT
        },
        'task_instance': {
            'format': "{{ti.dag_id}}-{{ti.task_id}} " + LOG_FORMAT
        },
        'airflow_coloured': {
            'format': COLORED_LOG_FORMAT if COLORED_LOG else LOG_FORMAT,
            FORMATTER_CLASS_KEY: COLORED_FORMATTER_CLASS if COLORED_LOG else 'logging.Formatter'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'airflow',
            'stream': 'ext://sys.stdout'
        },
        'task': {
            'class': 'airflow.utils.log.file_task_handler.FileTaskHandler',
            'formatter': 'task_instance',
            'base_log_folder': os.path.expanduser(BASE_LOG_FOLDER),
            'filename_template': FILENAME_TEMPLATE,
        },
...
```
