### ISSUE TITLE
Update and Move Scheduler Basics documentation to Airflow Docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10185]
**Description**

The old documentation for [Scheduler Basics](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=63407290) should be reviewed and incorporated into [Airflow Documentation](https://github.com/apache/airflow/tree/master/docs)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by yesemsanthoshkumar** [comment]
@potiuk I can pick this up over the weekend. Are we planning to add this to the [Scheduler](https://airflow.apache.org/docs/stable/scheduler.html) section of the docs?

**Comment by potiuk** [comment]
Great @yesemsanthoshkumar ! Yes. That's the right place  :)

**Comment by kaxil** [comment]
The current page is now pretty comprehensive - https://airflow.apache.org/docs/stable/scheduler.html
