### ISSUE TITLE
Move relevant information from Contributor's Guildelines to CONTRIBUTING.rst

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10187]
**Description**

The old documentation for [Contributor's guide](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62697734) should be reviewed and incorporated in [CONTRIBUTING.rst](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by morrme** [comment]
@potiuk 🙋🏾‍♀️

**Comment by potiuk** [comment]
Did I decifer it correctly that you want to work on it :)?

**Comment by morrme** [comment]
@potiuk  yes! 🙂  thank you!

**Comment by potiuk** [comment]
Any progress @morme ?

**Comment by morrme** [comment]
I'm so sorry @potiuk I have been slammed and totally dropped the ball on this 💔

**Comment by potiuk** [comment]
No no - I moved the commiter's guide :). Feel free to work on contributor's one :)

**Comment by potiuk** [comment]
No big hurry with that - I just updated docs relevant to committer's and that's why I moved those as it was relevant :)

**Comment by morrme** [comment]
@potiuk Looks lik  @Dr-Denzy Took care of it! Thanks @Dr-Denzy 
~ Dr. Morrme 😉
