### ISSUE TITLE
Move relevant information about Roles to CONTRIBUTING.rst

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10184]
**Description**

The old documentation for [Roles](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62694605) should be reviewed and incorporated in [CONTRIBUTING.rst](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by jpmarques66** [comment]
@potiuk Happy to take this.

**Comment by potiuk** [comment]
Feel free!. I assigned it to you :)
