### ISSUE TITLE
Changing timezone in webserwer UI

### ISSUE THREAD

**Issue by nie3e** [apache/airflow#10189]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- **Kernel** (e.g. `uname -a`): Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux
- **Install tools**: pip3
- **Others**:

**What happened**:

I can't change timezone in webserver UI. When i press on the time (top right corner) it just have me javascript alert with my host ip and host name. Changing timezone in config - airflow.cfg - also doesn't work. It still show time in UTC. I've seen some screens on the internet that there should be and arrow and dropdown list after clicking it (near time in UI) but clearly i don't have it.

**What you expected to happen**:
Successfully change timezone in webserver UI.

**How to reproduce it**:
In my case, just start webserver:
airflow webserver -p 8080

**Anything else we need to know**:

![image](https://user-images.githubusercontent.com/69011980/89447644-9aa6bf80-d756-11ea-997d-4bf25732b553.png)

**Comment by mik-laj** [comment]
Dp you have RBAC UI enabled? You should have the following values in airflow.cfg to use RBAC.
```
[webserver]
rbac = true
```
Here is the migration guide: https://github.com/apache/airflow/blob/master/UPDATING.md#drop-legacy-ui-in-favor-of-fab-rbac-ui

**Comment by nie3e** [comment]
> Dp you have RBAC UI enabled? You should have the following values in airflow.cfg to use RBAC.
> 
> ```
> [webserver]
> rbac = true
> ```
> 
> Here is the migration guide: https://github.com/apache/airflow/blob/master/UPDATING.md#drop-legacy-ui-in-favor-of-fab-rbac-ui

Thanks a lot! That solved my problem!
