### ISSUE TITLE
Review and move Common Pitfalls Documentation to Airflow Docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10180]
**Description**

The old documentation for [Common Pitfalls](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62694614) should be reviewed and incorporated in [Airflow Docs](https://github.com/apache/airflow/tree/master/docs)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by bsnithin44** [comment]
I would be happy to pick this up, 
But could someone give me a little context on documentation duplication?. Any guidance would be much appreciated.
Thanks

**Comment by potiuk** [comment]
Hello - just see the message now. Sorry I missed it :(

The context - we had a lot of documentation which was split into several different sources - Github docs, Cwiki, Airflow documentation in docs.  Airflow Site and sometimes the documentation was overlapping, sometimes outdated, sometimes it did not contain relevant information. 

We are now cleaning and restructuring the docs to be more consistent. It's mostly based on who the "Readers" of the documentation are:

* Airflow Docs - those are mostly the users of Airflow. People who either want to setup and manage Airlfow or those who want to write Dags or develop custom operators/Hooks etc. .

* Github Docs - Contributors and Committers. Basically, developers of Airflow

* Airlfow Site - mostly decision makers, those who would like to understand whether Airflow is a good choice for them. Also people who want to learn Airflow and decide whether they shoudl become users or contributors or both. Basically this should be index of "Everything Airflow" and a starting point for everything else.

* CWiki - we keep it mostly for AIPs (Airflow Improvement Proposals). But it's very likely (discussion https://lists.apache.org/thread.html/rf58348edc3ed4ad8dd167cdbeda0a2a5219a2ab1725d4e1b7e980d9a%40%3Cdev.airflow.apache.org%3E) we will get rid of it completely and move all the new AIPs to Github Issues. 

The common pitfalls doc clearly belongs to the "Airlfow Docs" (readership = users of Airflow). I think there should be a page in the Airflow Documentation with Common Pftfalls. And I believe it is enough to make a PR as  starting point with the content of the original document in CWiki and you will get plenty of comments from the community and suggestions what else to add ...

**Comment by potiuk** [comment]
I've assigned it to you

**Comment by wolfier** [comment]
I haven't seen any activity on this so I will be taking this issue.
