### ISSUE TITLE
Move relevant information about First time contributor workshop as Airflow Blog

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10182]
**Description**

The old documentation for [First time contributor's](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=139628154) should be reviewed and incorporated in [Apache Airflow Blog](https://airflow.apache.org/blog/)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by morrme** [comment]
@potiuk Should these be new articles?

**Comment by potiuk** [comment]
I think so - this one I think I will write with @turbaszek though - we had run a  few workshops so far and we will run a new edition in the coming weeks (online) so we will likely do that ourselves basing on our experience.

**Comment by potiuk** [comment]
But feel free to take the others :) @morrme ..

**Comment by turbaszek** [comment]
@potiuk should a description of the issue by updated? I think it corresponds to committers guide 🤔

**Comment by morrme** [comment]
@potiuk Sounds Good--and I'd like to attend one of these workshops someday! 🙏🏾

**Comment by potiuk** [comment]
There will be few in the coming weeks :)

**Comment by potiuk** [comment]
Or months

**Comment by nijanthanvijayakumar** [comment]
@potiuk - is another contributing to Airflow workshop coming soon? 🤔

**Comment by potiuk** [comment]
Not planned yet, but why not if there are people who would be interested.

**Comment by eladkal** [comment]
All the content already reviewed and existed in https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst

So the only step left is to create Airflow blog

**Comment by potiuk** [comment]
I think the documentation there is outdated and is actually never used. I don't think we need to add any blog for it.
