### ISSUE TITLE
Move "Releasing Airflow" docs to the "dev"

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10183]
**Description**

The documentation for [Releasing Airflow](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=69410380) should be reviewed and incorporated in [dev README.md](https://github.com/apache/airflow/blob/master/dev/README.md)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by sergioesca4** [comment]
Hello, @potiuk  I would like to work on this issue.

**Comment by potiuk** [comment]
Feel free :)

**Comment by potiuk** [comment]
Done !
