### ISSUE TITLE
Move Tips & Tricks for Oracle shops should be moved to Airflow Docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10186]
**Description**

The old documentation for [Tips and Tricks for Oracle Shops](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62694629) should be reviewed and incorporated in [Airflow Docs](https://github.com/apache/airflow/blob/master/docs)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by sergioesca4** [comment]
Hello, @potiuk I would like to work on this issue.

**Comment by mattluudo** [comment]
Hi @potiuk, can I add some tips and tricks on connecting to Oracle Database through Airflow GUI using the "extra" parameters. This specifies how a user can connect with (dsn and sid and not service_name), (dsn and service_name and not sid), and only dsn.

**Comment by potiuk** [comment]
Sure

**Comment by potiuk** [comment]
Hey @mattluudo @sergioesca4! Can I help somehow with those ?

**Comment by sergioesca4** [comment]
@mattluudo you can add them here and I will add them to the [PR I have open for this issue ](https://github.com/apache/airflow/pull/11197)

**Comment by mattluudo** [comment]
@sergioesca4 @potiuk I will move [my PR](https://github.com/apache/airflow/pull/11270) changes to the one you provided above

**Comment by mattluudo** [comment]
@sergioesca4 [PR ](https://github.com/apache/airflow/pull/11197) submitted to your branch

**Comment by potiuk** [comment]
CC: @matttiuudo - comment her and I will assign you :)

**Comment by mattluudo** [comment]
Jarek,

Thanks for the assignment!

-Matt

**Comment by mattluudo** [comment]
@potiuk Ready to go

**Comment by potiuk** [comment]
done!

**Comment by mattluudo** [comment]
@potiuk Pull request initiated!

**Comment by mattluudo** [comment]
@potiuk Issue resolved from merged pull request #13871

**Comment by morrme** [comment]
@potiuk @kaxil @mattluudo Should this issue be closed ?

**Comment by mattluudo** [comment]
Yes, it is done.
