### ISSUE TITLE
Move Announcement page to airflow.apache.org

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10196]
**Description**

The [Announcement page](https://cwiki.apache.org/confluence/display/AIRFLOW/Announcements) should be reviewed and moved tp in [Apache Airflow Website](https://airflow.apache.org/blog/)

**Use case / motivation**

To remove documentation duplication and clean it up.

**Related Issues**

#10178

**Comment by yesemsanthoshkumar** [comment]
@potiuk I can pick this up over this weekend.
One question though. Does this have to be a new section like blog and usecases?

**Comment by potiuk** [comment]
I think it would be best to have separate section. It could be blog but I think announcements should be more 'permanent' :)

**Comment by potiuk** [comment]
CC: @yesemsanthoshkumar  #10274 as a next one maybe ;) ?

**Comment by yesemsanthoshkumar** [comment]
Sold already. ;)

Planning to pick one for this weekend too. Will have to go over the issues once.

**Comment by potiuk** [comment]
:+1:
