### ISSUE TITLE
ModuleNotFoundError: No module named 'docker' in DockerOperator

### ISSUE THREAD

**Issue by tambulkar** [apache/airflow#10204]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Conda Python 3.6.11

**What happened**:

Trying to import the DockerOperator from `airflow.operators.docker_operator and I get this error
ModuleNotFoundError: No module named 'docker'

**What you expected to happen**:

Shouldn't airflow automatically install all the dependencies listed [here](https://github.com/apache/airflow/blob/1.10.11/requirements/requirements-python3.6.txt) when I run `pip install apache-airflow`? It is easily fixed by manually running `pip install docker`, but is this the expected behavior? 

**How to reproduce it**:
```
conda create -n test python 3.6.11 --yes
conda activate test
pip install apache-airflow
pip freeze
```
[docker](https://github.com/docker/docker-py) doesn't appear in the list of installed packages

**Comment by potiuk** [comment]
Not really. See https://airflow.apache.org/docs/stable/installation.html

Apache has a number of extras that you can choose when installing it . For example pip install airflow[kubernetes] will install all the stuff to run kubernetes. The file you mentioned is a constraint file only (and we are changing the mechanism of those  slightly soon). You can read the installation doc where you find some details: https://airflow.apache.org/docs/stable/installation.html
