### ISSUE TITLE
Make `webserver_config.py` location customizable

### ISSUE THREAD

**Issue by fengsi** [apache/airflow#10206]
**Description**
`webserver_config.py` location is [hard-coded](https://github.com/apache/airflow/blob/c2db0dfeb13ee679bf4d7b57874f0fcb39c0f0ed/airflow/configuration.py#L769) as follows:
```
WEBSERVER_CONFIG = AIRFLOW_HOME + '/webserver_config.py'
```
It would be great if this path is customizable.

**Use case / motivation**
Since `AIRFLOW_HOME/config` is already in `PYTHONPATH` (though that's also hard-coded), it's common for user to mount all config files under `AIRFLOW_HOME/config`.  However, this `webserver_config.py` needs extra handling, either by mounting using a `subPath` explicitly, or in my case, creating a symbolic link from `AIRFLOW_HOME/webserver_config.py` to `AIRFLOW_HOME/config/webserver_config.py` in the image.

**Comment by mik-laj** [comment]
@fengsi  I like this idea. This can be standardized to have a similar interface to `logging_config_class`.  Would you like to work on it?

**Comment by fengsi** [comment]
> @fengsi I like this idea. This can be standardized to have a similar interface to `logging_config_class`. Would you like to work on it?

Sure, I'd be willing to make that happen.  I may also take care of other config paths together. 👍

**Comment by kaxil** [comment]
I have assigned this issue to you @fengsi :) Looking forward to your PR

**Comment by mik-laj** [comment]
@fengsi I can see that you are not active on this ticket, so I unassigned you from this ticket so that the other contributor can start working on it. If you want to continue working, let me know and I will assign you again.

**Comment by AlexandrKhabarov** [comment]
I would like to work on it. It seems that issue on hold.

**Comment by kaxil** [comment]
@AlexandrKhabarov -- Assigned it to you -- However I think I saw a PR around it -- let me check

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/14353 -- this one -- that fixes it for the Helm Chart

**Comment by kurtqq** [comment]
would be nice to have this configurable

**Comment by amoghrajesh** [comment]
@eladkal @potiuk @kaxil saw that this issue was not fixed through config file but instead through a configmap: https://github.com/apache/airflow/pull/24227. Do we still want this issue to be open? We should either fix it through config file or use the configmap solution. However I think it would be a good idea to have the config file solution too for traditional users. In that case, I can take this issue up

**Comment by potiuk** [comment]
Feel Free @amoghrajesh . I think it would be good to read `webserver_config.py` from config if yoy have it there and no "webserver_config.py" in root. We should also - I think deprecate it and raise warning if it is still in "AIRFLOW_HOME" and change the default generation to be placed in "config". 

I don't think we should allow for any more "customization" - just changing the default location to "AIRFLOW_HOME/config" and deprecating old locatoin should be good enough IMHO.

**Comment by amoghrajesh** [comment]
I think deprecation will be a big change and that we should move eventually to it. For a start, we can start prioritising the webserver config present in config over what is present in the root directory. I will host a PR for that. We can create a follow up issue which perhaps I myself can take up for the deprecation part of it. WDYT @potiuk?

**Comment by amoghrajesh** [comment]
@potiuk added a PR: https://github.com/apache/airflow/pull/29926/. It is still in its first stage, figuring out a way to get a unit test up and running
