### ISSUE TITLE
Updating.md Note on Kubernetes Changes in 1.10.11 and 1.10.12

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10216]
Add a note in `Updating.md` about the Kubernetes related changed in 1.10.11 and 1.10.12 specifically telling users that they should update to 1.10.12 if they find any K8s related features that broke after they upgraded to 1.10.11.

And a note to tell that the older way of using Airflow POD class is deprecated. And all the paths from `airflow.contrib.kubernetes` have been deprecated in 1.10.12 and were accidentally removed in 1.10.11

This applies to the users of `pod_mutation_hook` too.

Related Issues:
- https://github.com/apache/airflow/issues/9860
- https://github.com/apache/airflow/issues/9827
- https://github.com/apache/airflow/issues/9966

Related PRs to fix those Issues:
- https://github.com/apache/airflow/pull/9935
- https://github.com/apache/airflow/pull/9903
- https://github.com/apache/airflow/pull/10067
- https://github.com/apache/airflow/pull/10084

**Comment by dimberman** [comment]
Updates added
