### ISSUE TITLE
SQSSensor Dag is not triggering whenever there is new message.

### ISSUE THREAD

**Issue by prakash260** [apache/airflow#10210]
I have created a DAG using SQSSensor to trigger whenever there is new message in SQS. 

It is not triggering automatically whenever there is new message. 

Below  is my code:

```python
from __future__ import print_function
from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.operators.python_operator import PythonOperator
from airflow.contrib.sensors.aws_sqs_sensor import SQSSensor

default_args = {
    'owner': 'Airflow',
    'start_date': days_ago(1),
    'provide_context': True,
}

def pull_from_xcom(**context):
    val = context['ti'].xcom_pull(task_ids='sqs_get', key='messages')
    print(val)

dag = DAG('sqs_test', default_args=default_args, schedule_interval='@daily')

t1 = SQSSensor(
    dag=dag,
    task_id='sqs_get',
    sqs_queue='https://sqs.ap-southeast-2.amazonaws.com/accountid/test',
    aws_conn_id='aws_default',
    max_message=1,
    wait_time_seconds = 1
    )

t2 = PythonOperator(
    task_id='xcom_pull',
    python_callable=pull_from_xcom,
    depends_on_past=False,
    dag=dag)

t1 >> t2
```

**Comment by eladkal** [comment]
>SQSSensor to trigger whenever there is new message in SQS.

sensors don't trigger anything. They are just blocking the workflow till condition met.
I think you are expecting that when a message is in the queue it will trigger a workflow - this is not the use case of Airflow sensors.
In any case please recheck with if the issue still exist with Airflow 2 + Amazon provider:
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html

if the issue still exist please clarify further.

**Comment by krishnareddy97** [comment]
> > SQSSensor to trigger whenever there is new message in SQS.
> 
> sensors don't trigger anything. They are just blocking the workflow till condition met. I think you are expecting that when a message is in the queue it will trigger a workflow - this is not the use case of Airflow sensors. In any case please recheck with if the issue still exist with Airflow 2 + Amazon provider: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
> 
> if the issue still exist please clarify further.

I am facing a similar issue where I can't read the contents of the sqs_queue message JSON strings and upload that to email_operator body... Can you help me with this issue???

**Comment by rverma-nsl** [comment]
@eladkal same here, we are not sure how to trigger dags with airflow. If we are only block at task and utilise a cron job for trigger, then we can't ever process a scenario where I want to run 2 dags concurrently since I got 2 messages in the queue.
