### ISSUE TITLE
Airflow configuration in web UI should recognize current settings rather than reading from `AIRFLOW_CONFIG` file

### ISSUE THREAD

**Issue by fengsi** [apache/airflow#10223]
**Apache Airflow version**:
1.10.11

**What happened**:
The `/configuration` URL is hard-coded to show config in `AIRFLOW_CONFIG`, which is usually the `AIRFLOW_HOME/airflow.cfg` file:
https://github.com/apache/airflow/blob/44d4ae809c1e3784ff95b6a5e95113c3412e56b3/airflow/www/views.py#L2133-L2134

**What you expected to happen**:
This `AIRFLOW_CONFIG` assumption is simply wrong.  It is very common for a user to define config as env vars, but those won't be reflected in this view at all.  All you get would be the default config, which is useless.

We should use the same interface like in `airflow config` command to retrieve the real config:
https://github.com/apache/airflow/blob/1d9a634d1dcb6f7d5816a38ccb5b967b074f918f/airflow/cli/commands/config_command.py#L32-L33

**How to reproduce it**:
Override config using env vars, and check the view.

**Comment by kaxil** [comment]
They are reflect. There are 2 configurations on the UI:

1) Configs from airflow.cfg
2) Running Configuration

**Comment by kaxil** [comment]
Check https://github.com/apache/airflow/blob/44d4ae809c1e3784ff95b6a5e95113c3412e56b3/airflow/www/templates/airflow/config.html#L44-L67

**Comment by fengsi** [comment]
Indeed!  Didn't scroll down.  Thanks!
Closing this ticket.
