### ISSUE TITLE
Cannot clear DAG with many past instances -- sqlite3.OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by zigeuner** [apache/airflow#1022]
I let a DAG with a start_date far in the past run for too long.  It accumulated a lot of past instances.  Unfortunately, I can't reset to a new start_date using a clear (through CLI or UI) because sqlite complains that it is getting too many variables in call.  See below for error message.  I think I can solve this short term by clearing 2 days at a time, but a fix would be useful for others.
related to issue: https://github.com/airbnb/airflow/issues/456
thanks

last airflow call using code from recent master was:
File "/home/user/anaconda3/envs/acda35/lib/python3.5/site-packages/airflow/models.py", line 89, in clear_task_instances

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/acda35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/user/anaconda3/envs/acda35/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: too many SQL variables

fuller error:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables [SQL: 'SELECT dag_run.id AS dag_run_id, dag_run.dag_id AS dag_run_dag_id, dag_run.execution_date AS dag_run_execution_date, dag_run.start_date AS dag_run_start_date, dag_run.end_date AS dag_run_end_date, dag_run.state AS dag_run_state, dag_run.run_id AS dag_run_run_id, dag_run.external_trigger AS dag_run_external_trigger, dag_run.conf AS dag_run_conf \nFROM dag_run \nWHERE dag_run.dag_id IN (?) AND dag_run.execution_date IN (?, ?, ?, ?, ?, ?,..... lots and lots....

**Comment by r39132** [comment]
@zigeuner 

To set a new start date, you should rename your DAG. I use the convention `my_dag_v1`, `my_dag_v2`, `my_dag_v3`. This is documented on https://github.com/airbnb/airflow/wiki/Airflow-Common-Pitfalls

It is not ideal and we are starting to discuss better way to set this dynamically. For now, that is your work-around. 

Additionally, as mentioned here, 999 is the limit for SQLite: 
http://stackoverflow.com/questions/7106016/too-many-sql-variables-error-in-django-witih-sqlite3/8433514#8433514

SQLite is okay for initially getting your system up, but we recommend using a DB that more closely mimics your production and qa deployments. DBs like mysql, postgresql do not impose limits in the IN-clause, though I am not sure about limits on host parameters. In either case, we leave to SQLAlchemy, our ORM and it's DB driver providers to solve the details of each DB.
