### ISSUE TITLE
BigQueryValueCheckOperator derived from deprecated ValueCheckOperator

### ISSUE THREAD

**Issue by dewaldabrie** [apache/airflow#10271]
`airflow.contrib.operators.bigquery_check_operator.BigQueryValueCheckOperator` [is derived from](https://github.com/apache/airflow/blob/69cc8370e486e00dd526e96c2b0aacd348ee255e/airflow/contrib/operators/bigquery_check_operator.py#L82) `airflow.operators.check_operator.ValueCheckOperator` but needs to be derived from `airflow.operators.sql.SQLValueCheckOperator` instead.

Until this is done, airflow generates a lot of warnings from [this](https://github.com/apache/airflow/blob/69cc8370e486e00dd526e96c2b0aacd348ee255e/airflow/operators/check_operator.py#L81) line of code.

**Comment by turbaszek** [comment]
Related #9844

**Comment by dewaldabrie** [comment]
@turbaszek This is related indeed, but #9844 is for a PR into master branch where the location of the BigQueryValueCheckOperator is also changed. My PR is to fix it for 1.10 specifically.

**Comment by eladkal** [comment]
This will be fixed in https://github.com/apache/airflow/pull/12677
