### ISSUE TITLE
Add Ecosystem page to Airflow Website

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10274]
**Description**

We should add **Ecosystem** page to the Apache Airflow Website. Here we should promote uses of Airflow.

Discussed in: https://lists.apache.org/thread.html/r8b61f45b8571bd7c5956aa6360be82afb90feeda4362b754c4663d32%40%3Cdev.airflow.apache.org%3E

**Use case / motivation**

We should promote those that are using Apache Airflow extensively and places where Airflow is the "shoulder of giant' which others are standing on and where you can learn more about Airlfow

Some of the chapters/ideas to put at that page:

1) Learning Airflow:

Here, useful sources to learn about Apache Airflow can be added:

* Apache Airflow YouTube Channel 
* Apache Airflow Summit page
* https://github.com/jghoman/awesome-apache-airflow is definitely something that should be on the list
* The Udemy Course by Marc  Lamberti:  https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow
* The Udemy Course by Alexa Abbas  https://www.udemy.com/course/apache-airflow-course/?couponCode=EARLYBIRD

2) Airflow-As-A-Service

* Astronomer
* Google Cloud Composer

TODO: Others?

3) Integrating with Airflow:

* "Ooozie-2-Airflow" library: https://github.com/GoogleCloudPlatform/oozie-to-airflow
* CWL-Airflow -> Airflow (https://github.com/Barski-lab/cwl-airflow) 
* Databand.ai -> observability platform built on top of Airflow and use Airflow as execution engine
* Chartis: https://github.com/trejas/chartis

TODO: Others? 

4)  Who's Using Airflow:

We should move all the users of Airflow from the README.md ? 

**Related Issues**

#10178

**Comment by alexandraabbas** [comment]
I'm happy to pick this up!
