### ISSUE TITLE
Update example DAG files to latest syntax

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10285]
Hello,

When we stop releasing backport packages, we will be able to update all example DAGs to use the new syntax for handling outputs introduced by AIP-31.

This is an example change.
```diff
 product_set_update = CloudVisionUpdateProductSetOperator(
     location=GCP_VISION_LOCATION,
-    product_set_id="{{ task_instance.xcom_pull('product_set_create') }}",
+    product_set_id=product_set_create.output,
     product_set=ProductSet(display_name='My Product Set 2'), 
    task_id='product_set_update',
)
```
Best regards,
Kamil Bregułła

**Comment by potiuk** [comment]
Or Maybe we can do automated refactoring for that one ? Sounds doable.

**Comment by potiuk** [comment]
CC: @turbaszek

**Comment by turbaszek** [comment]
This should be probably part of #9041

**Comment by hsnprsd** [comment]
Hey, I am new here :). Can I contribute on this issue as my first contribution? Has someone already addressed this issue?

**Comment by turbaszek** [comment]
@hsnprsd feel free to take this one 🚀 I'm happy to help with eventual questions. I think, as a good start we should refactor `airflow/example_dags/*` to use `.output` instead of jinja whenever it is possible.

**Comment by josh-fell** [comment]
@mik-laj @potiuk @turbaszek Is this enhancement still desired?  I could take a crack at it if it is.

**Comment by potiuk** [comment]
Sure. Take a look please :)

**Comment by josh-fell** [comment]
@mik-laj @potiuk @turbaszek Would you all also like to see `PythonOperator` use be converted to using the `@task` decorator or would that kind of update be considered out of scope for the enhancement?

**Comment by potiuk** [comment]
I think this could be done as extra task afterwards

**Comment by josh-fell** [comment]
Going through these example DAGs there are a number of `xcom_pull()` uses in which values from the `XCom` are directly accessed via an index and/or key as well as a `for loop` in Jinja.  Trying to rewrite these instances using the new syntax is  awfully cumbersome IMO.  For example:
```python
# Access by dict key
job_id="{{task_instance.xcom_pull('start_python_job_dataflow_runner_async')['dataflow_job_id']}}"

# Access by index
object_name="{{ task_instance.xcom_pull('upload_sheet_to_gcs')[0] }}"

# Using a for loop and accessing by dict key
echo_cmd = """
{% for m in task_instance.xcom_pull('pull_messages') %}
    echo "AckID: {{ m.get('ackId') }}, Base64-Encoded: {{ m.get('message') }}"
{% endfor %}
"""
```
The `output` property of operators doesn't seem to elegantly handle this type of access currently.  I can use a workaround with ugly hacks like these:
```python
# Dict key access workaround (index access would be written similarly)
start_python_job_dataflow_runner_async_output = str(start_python_job_dataflow_runner_async.output).strip("{ }")

wait_for_python_job_dataflow_runner_async_done = DataflowJobStatusSensor(
        task_id="wait-for-python-job-async-done",
        job_id="{{{{ {start_python_job_dataflow_runner_async_output}['dataflow_job_id'] }}}}",
        expected_statuses={DataflowJobStatus.JOB_STATE_DONE},
        project_id=GCP_PROJECT_ID,
        location='us-central1',
    )

# For loop workaround
echo_cmd = f"""
    {{% for m in {pull_messages_output} %}}
        echo "AckID: {{{{ m.get('ackId') }}}}, Base64-Encoded: {{{{ m.get('message') }}}}"
    {{% endfor %}}
    """
```
I logged #16618 as a feature request to enhance the use of `XComArgs` to handle such access.  I was wondering if you all thought it was worth implementing these workarounds or to leave them as-is for now.  What do you think?

**Comment by ashb** [comment]
@josh-fell Can't you do `xcom['dataflow_job_id']` or similar? Looking at the docs that looks like it should work.

**Comment by josh-fell** [comment]
@turbaszek @mik-laj @potiuk All of the PRs to update the example DAGs have now been merged. This issue can be closed if you feel they have satisfied the scope of this issue.

**Comment by mik-laj** [comment]
@josh-fell thanks. Closed!

**Comment by potiuk** [comment]
Fantastic! Thanks @josh-fell !
