### ISSUE TITLE
GCSToS3Operator (and S3Hook) does not allow passing in of custom metadata

### ISSUE THREAD

**Issue by dewaldabrie** [apache/airflow#10298]
This is related to #8304 which as closed due to becoming stale.

[GCSToS3Operator](https://github.com/apache/airflow/blob/f618cdd19a5cdf09262436978817934d27668997/airflow/providers/amazon/aws/transfers/gcs_to_s3.py#L30) uses the S3Hook to upload files.
The S3Hook uses boto3, which supports attaching metadata (headers) to files via the [`ExtraArgs` parameter](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html#the-extraargs-parameter). The `ExtraArgs` parameter is already being used in the `S3Hook`'s `upload_fileobj` method, but it does not allow the user to pass in custom metadata.

My proposition is to add the optional params to  `GCSToS3Operator` and `S3Hook` to allow the use to pass in custom metadata.

**Comment by rootcss** [comment]
@kaxil please assign this to me.
