### ISSUE TITLE
Help using TriggerDagRunOperator

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#1029]
Does anyone have an example how to use the payload with TriggerDagRunOperator?
How can I get the payload on triggered dag? 
Can someone provide and example?
I was looking at #1010, and prefer to open a new issue. 
I imagine it could better separate the issues.

**Comment by r39132** [comment]
Hi! 
Good question and the answer is that it is not exposed currently in any useful way to allow setting it : https://github.com/airbnb/airflow/blob/master/airflow/operators/dagrun_operator.py#L46

I don't think it is needed for most use-cases. What I think you are actually looking for is a way to pass state to your python callable. Here's how:

```
from airflow import DAG, utils
from airflow.operators import *
from datetime import date, datetime, time, timedelta


def foo(context, dag_run_obj):
    print "INSIDE FOO = {}".format(context['params']['passed_by_me'])
    if True:
        return dag_run_obj

dag = DAG(dag_id='test_trigger_dag_run_for_Sid_1',
          default_args={"owner" : "me",
                        "start_date":datetime.now()},
          schedule_interval='*/1 * * * *')

trigger = TriggerDagRunOperator(task_id='test_trigger_dagrun',
                                trigger_dag_id="simple_dummy_dag_v1",
                                python_callable=foo,
                                params={'passed_by_me':1},
                                dag=dag)

```

If you want to pass some state to the python callable via the TriggerDagRunOperator, just follow the example above.

**Comment by r39132** [comment]
Excuse me if I am being presumptuous about your needs. I will close this for now, but if you need something else, you can ping me gitter.

**Comment by pedrorjbr** [comment]
@r39132 Thanks for the response.

I dont think I made me clear. Imagine that I have a DAGS that trigger other DAG. So DAG1, DAG2 and DAG3 can trigger DAG4 using TriggerDagRunOperator. 
Every DAG that triggers DAG4 will pass some parameters and I would like to get these parameters on DAG4. 

Am I clear? Is that possible?

Thansk again!!!

**Comment by r39132** [comment]
Yes, this is possible:

Read https://www.linkedin.com/pulse/airflow-lesson-1-triggerdagrunoperator-siddharth-anand?trk=pulse_spock-articles

And look at the examples i checked in yesterday. 
https://github.com/airbnb/airflow/blob/master/airflow/example_dags/example_trigger_target_dag.py

I access data (i.e. message) in the Target DAG that was passed from the Controller DAG as shown below:
`kwargs['dag_run'].conf['message']`

If this does not make sense, then ping me https://gitter.im/airbnb/airflow

Also, it would probably be easier for you to start with a working example (the ones I checked in) and then modify those for your needs.

**Comment by r39132** [comment]
If this does not make sense, then ping me https://gitter.im/airbnb/airflow

**Comment by r39132** [comment]
Currently, you need to use a python operator to access this data, but then you can use xcom to push that data around within the dag.

**Comment by mistercrunch** [comment]
Since it's in the context, you can also reference it within a template `{{ dag_run.conf['foo'] }}`, I'm adding that to the example.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/commit/2a3e526a30146abc3bb3af36a04ab8b24b48eb76

**Comment by BradHolmes** [comment]
A related use-case is to trigger a dag-run from the command line, with a particular configuration.  We have achieved this by copying the creation of a DagRun object of the TriggerDagRunOpeartor, into a stand-alone python script.  

Would it make sense to expose the creation of DagRun's in some method?

The code I have had to copy is:

```
def CreateDagRun(args):

    dict_args = vars(args)
    session = settings.Session()
    dr = DagRun(
        dag_id=args.dag_id,
        run_id=args.run_id,
        conf=dict_args,
        external_trigger=True)
    logging.info("Created DagRun {} with parameters: {}".format(dr, dict_args))
    session.add(dr)
    session.commit()
    session.close()
```

where `args` is an `argpase` derived set of objects.  Some thought should be given to how the arguments are exposed.

**Comment by r39132** [comment]
Great question and a great use-case!

**Comment by r39132** [comment]
@BradHolmes This is now supported in the CLI itself thanks to @mistercrunch 

This is also documented on https://www.linkedin.com/pulse/airflow-lesson-1-triggerdagrunoperator-siddharth-anand

**Comment by BradHolmes** [comment]
Super!  Thanks for the fix, and for the excellent write-up.
