### ISSUE TITLE
Workers consuming from non-default celery queue receive tasks from default queue

### ISSUE THREAD

**Issue by caseybrown89** [apache/airflow#1030]
We've setup our Airflow environment so that certain DAGs get sent to celery workers on specific machines.  I understand this is a bit of a unique situation.  We're using CeleryExecutors, and Celery is using RabbitMQ for the broker and Redis for the result backend.  

To get tasks routed to specific workers, I did the following:
- Setup a celery worker on machine X.  Within airflow.cfg on worker X, set the default_queue variable to be the name of the special queue, 'foobar'. Then, I started the celery worker on machine X like,

```
 airflow worker -q foobar
```
- To get DAGs to run on a specific worker, I modified the default_args to specify the queue to be 'foobar',

```
    default_args = {
    'owner': '...',
    'depends_on_past': False,
    'start_date': datetime(2016, 1, 26, 19, 0, 0),
    'email': ['casey@cogolabs.com'],
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 0,
    'retry_delay': timedelta(minutes=5),
    'queue': 'foobar'}
```

At this point, my worker on machine X was consuming tasks from the foobar queue.  However, the worker was also consuming tasks from the default queue, but I hadn't specified the default queue when I started the celery worker on machine X.

It turns out that celery worker on machine X was listening to the Exchange used for the default queue (which I believe was named "celery") in addition to the foobar Exchange.  Even after manually removing that worker from the Exchange on the RabbitUI, the worker would be added back each time the worker was started.  To stop this, I modified celery_executor.py and added a line specifying the CELERY_DEFAULT_EXCHANGE,

```
class CeleryConfig(object):
    CELERY_ACCEPT_CONTENT = ['json', 'pickle']
    CELERYD_PREFETCH_MULTIPLIER = 1
    CELERY_ACKS_LATE = True
    BROKER_URL = configuration.get('celery', 'BROKER_URL')
    CELERY_RESULT_BACKEND = configuration.get('celery', 'CELERY_RESULT_BACKEND')
    CELERYD_CONCURRENCY = configuration.getint('celery', 'CELERYD_CONCURRENCY')
    CELERY_DEFAULT_QUEUE = DEFAULT_QUEUE
    CELERY_DEFAULT_EXCHANGE = DEFAULT_QUEUE # CHANGE 
```

After this change, the celery worker only connects to the Exchange associated with the queue it's listening to.  I also tested if the worker on X could still listen to both the default and foobar queues and that behavior seemed to be intact.

```
airflow worker -q foobar,default
```

So at this point, I'm curious what is the desired behavior?  To have workers that are listening to non-default queues only execute work for that specified queue?  Or have the worker execute work from both the specified non-default queue and the default queue?  I am by no means an expert on Celery or Rabbit so please share if I'm going about this the wrong way.

It's also worth noting that when I'd like to stop a worker from consuming from a queue I need to manually remove that worker from the Exchange (I've been doing that from the Rabbit UI http://rabbit_server:15672/#/exchanges) associated with that queue in addition to removing the name of the queue from the `airflow worker` call.

**Comment by mistercrunch** [comment]
Related notes and answers:
- The desired behavior is to listen only to the specified queue(s), if no queue is specified the default queue should be used 
- We use redis as the broker at Airbnb and use queues extensively, it works very well for us, but haven't tested on RabbitMQ
- Workaround idea, what about not using the `default` queue, ever?

If you think think that you can send a PR that will fix this behavior we'll be happy to review it.

**Comment by caseybrown89** [comment]
Here's the PR that fixed the issue for us, https://github.com/airbnb/airflow/pull/1041

I'm happy to refine the PR if the change causes problems for other brokers.

**Comment by garthcn** [comment]
Looks like this is the same issue as: https://github.com/airbnb/airflow/issues/778
