### ISSUE TITLE
Grayed out UI shown on all Pop-ups in the Webserver UI

### ISSUE THREAD

**Issue by r39132** [apache/airflow#1032]
<img width="1085" alt="screenshot 2016-02-18 16 54 41" src="https://cloud.githubusercontent.com/assets/581734/13153346/8750e636-d66b-11e5-9233-f41316a53fb9.png">

I'm curious if others are seeing this!

**Comment by mistercrunch** [comment]
Isn't this fixed in master and airbnb_prod?

**Comment by r39132** [comment]
Hmn..unclean install!
