### ISSUE TITLE
Skipped and Depends on Past

### ISSUE THREAD

**Issue by vansivallab** [apache/airflow#1033]
If the past task was skipped, the "current" task won't be scheduled.

It would be nice to have skipped be an allowable state in addition to success. Or have "acceptible_past_states" as a BaseOperator parameter.

**Comment by mistercrunch** [comment]
same as https://github.com/airbnb/airflow/issues/914, closing 914 as the title is more clear here. 

Wontfix as this is an unintuitive behavior. Using `depend_on_past` makes sense to me with branching.

Will review PR if any.

**Comment by r39132** [comment]
@vansivallab This is now supported and tracked in #1155!
