### ISSUE TITLE
bigquery_operator.py does not allow large results

### ISSUE THREAD

**Issue by 0xR** [apache/airflow#1034]
When you are query a large amount of data you have to turn on the flag [allowLargeResults](https://cloud.google.com/bigquery/docs/reference/v2/jobs) . This is not possible with the current bigquery_operator.

Depending on our available time we might submit a pull. For now have implemented a workaround by creating our own operator.

**Comment by mistercrunch** [comment]
Just curious, how big is largeResults?

**Comment by 0xR** [comment]
I found the answer [here](https://cloud.google.com/bigquery/quota-policy#queries). 128MB compressed. In our case we are retrieving 10+ million rows which accounts for around 2GB uncompressed csv.

**Comment by r39132** [comment]
@criccomini See above.. might be in your wheel house.

**Comment by criccomini** [comment]
I think that this has been fixed already. https://github.com/airbnb/airflow/blob/master/airflow/contrib/operators/bigquery_operator.py#L20
