### ISSUE TITLE
Markdown table is not rendered in doc_md attribute for DAG

### ISSUE THREAD

**Issue by jelther** [apache/airflow#10367]
**Apache Airflow version**: 1.10.11

**Environment**: Python 3.7

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): PRETTY_NAME="Debian GNU/Linux 10 (buster)"
 (from python3.7-slim-buster docker image)
- **Kernel** (e.g. `uname -a`): Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Using a markdown formatted table does not work.

**What you expected to happen**:

To be able to see a formated table within DAG view

**How to reproduce it**:

Add a tabular formatted code do dag.doc_md.

Example:

> mytable:
> 
> | a | b | c |
> | ------------- | ------------- | ------------- |
> | a | b | c |

[Table not formatted](https://i.imgur.com/l6JXuWe.png)

**Anything else we need to know**: N/A

**Comment by mik-laj** [comment]
It seems worth taking care of this. Do you want me to assign you this ticket? I will be happy to help if you need any support and reviews.

**Comment by mik-laj** [comment]
It seems that the original markdown specification does not provide support for tables
https://daringfireball.net/projects/markdown/syntax
We have to activate it with the extension.
https://python-markdown.github.io/extensions/

**Comment by mik-laj** [comment]
Hello,

I assigned you to this ticket. Now you can create a PR with your change. 

To work it is useful to set up the Breeze development environment. Here is a guide: https://github.com/apache/airflow/blob/master/BREEZE.rst

I think it's worth taking a look at the contribution workflow:
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow

If you have any questions, feel free to ask.

**Comment by mik-laj** [comment]
@avats-dev I unassigned you from this ticket so that the other contributor can start working on it. If you want to continue working, let me know and I will assign you again.

**Comment by jyotidhiman0610** [comment]
Can I take this up? @mik-laj

**Comment by potiuk** [comment]
Feel free @jyotidhiman0610

**Comment by yc0** [comment]
I have no idea if the bug is fixed. I saw it is merged but I don't see this commit in the latest branches.
However, I would like to offer the other concept: **add your own style for the markdown**.
```
dag.doc_md = """\
<style>
  th, td {
    border: 1px solid black;
  }
  thead th {
    width: 2%;
  }
</style>
"""
```
This way can also render tables in the form of Markdown correctly.

**Comment by dougbyrne** [comment]
Is there another issue opened already to provide better styles for markdown tables? I came up with this style but I'm not sure how to inject it into the airflow app.

```css
div.rich_doc td, th {
    padding: 5px;
    border: 1px solid black;
}
```

**Comment by potiuk** [comment]
> Is there another issue opened already to provide better styles for markdown tables? I came up with this style but I'm not sure how to inject it into the airflow app.
> 
> ```css
> div.rich_doc td, th {
>     padding: 5px;
>     border: 1px solid black;
> }
> ```

Commenting on a closed issue is not a good idea. I recommend you open a discussion isntead. But I believe we do not have it and adding that as a feature via PR would be even better than opening a discussion.
