### ISSUE TITLE
Clearer documentation about production image usage

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10363]
**Description**

We have quite comprehensive documentation about Docker Images used (https://github.com/apache/airflow/blob/master/IMAGES.rst) however it can be quite overwhelming for image users who just want to use it and possibly customize the image without having to know all the internals.

There is a small section about Production Images in https://github.com/apache/airflow/#official-docker-images but it likely need to be a bit updated and possibly some information from the IMAGES.rst can be copied or moved here (and some new information added). It should be mostly focused on users, not developers of the image.

I think the content of that section could consist  of:

1) Context - what the prod image is and where it can be used + explanation that in DockerHub there is just a  convenience binary and that image can (and often should) be built from the officially released sources.
2) Naming and links to the Production Images
3) Describe two options for the image - customization/extension
4) Short how-to on how to build image using Breeze (this is the easiest way for now).
5) link to https://youtu.be/wDr3Y7q2XoI - Airflow Summit 2020's "Production Docker Image" talk where context, architecture and customization/extension methods are explained. 

**Use case / motivation**

Make it easier for casual or first-time users to understand how they can use the image.

**Comment by sanjana1604** [comment]
@potiuk I would like to solve this issue.

**Comment by potiuk** [comment]
Feel free :). Assigned you to it and happy to review it!

**Comment by potiuk** [comment]
@sanjana1604 The context is described mostly in http://www.apache.org/legal/release-policy.html - Apache releases software as sources, so the binaries are released mostly as convenience packaging, not the official releases. I think this can be left as TODO and I am happy to add some content there.
