### ISSUE TITLE
Auth backends for new API

### ISSUE THREAD

**Issue by jhtimmins** [apache/airflow#10364]
**Description**

We need additional auth backends for the new API to allow access to users who aren't use an auth proxy service.

**Use case / motivation**

The new API does not have support for common authentication methods, such as JWT or basic authentication. It exclusively supports use of an authentication proxy service. Small teams using Airflow are unlikely to have auth proxies, meaning the API is difficult for them to use. By adding pre-built auth backends for common auth schemes, we increase the number of users who can easily build on top of the API

**Related Issues**

https://github.com/apache/airflow/issues/8111
https://github.com/apache/airflow/issues/8112

**Comment by mik-laj** [comment]
Currently @houqp  is already working on Basic Authorization
 https://github.com/apache/airflow/pull/10356
Does this fulfill your needs or would you like to implement something else?

**Comment by houqp** [comment]
Hi @jhtimmins sorry that I started working on the basic auth support because I didn't see anyone working on it and our team really need this feature for production workload. Perhaps we can repurpose this issue to JWT support?

**Comment by jhtimmins** [comment]
@houqp That's awesome! I don't care who does the work I'm just glad it's getting done :) 

@mik-laj I think this is good for now. If we need to add additional schemes in the future we can do that, but for now as long as there's a way for teams to authenticate beyond auth proxies or similar.
