### ISSUE TITLE
Default to OFF when adding a new DAG to dags directry

### ISSUE THREAD

**Issue by davidsbatista** [apache/airflow#1037]
Whenever I add a new dag file to the directory of the dags it seems airflow sets the status of the DAG to ON, according to the web interface. Would it be possible by default to start in the OFF state ?

**Comment by r39132** [comment]
https://github.com/airbnb/airflow/pull/956

Already exists as an entry in the airflow.cfg file on master. @mistercrunch time for a new release for this and other fixes?

**Comment by mistercrunch** [comment]
I'm hoping by end of week for next release. There's a lot of good stuff in trunk.
