### ISSUE TITLE
Chart README is incorrect

### ISSUE THREAD

**Issue by cccs-cat001** [apache/airflow#10379]
**Apache Airflow version**: docs issue

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The instructions to install the helm chart in the README file produce the helm/chart/stable/airflow helm chart, and not the one in this repo. 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Done: https://github.com/apache/airflow/pull/14643
