### ISSUE TITLE
Add mechanism to maintain UPDATING.md for each provider package separately

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10376]
**Description**

Add inventory of backwrds-incompatible changes in backport packages.

**Use case / motivation**

Currently, we do not have an inventory of the backwards-incompatible changes in backport packages. We want to keep the updated when there are a future changes and we want to include them in the release notes.

**Related Issues**

#10014

**Comment by ashb** [comment]
Not needed now that we aren't doing any more backport providers.
