### ISSUE TITLE
Add on_kill method to DataprocInstantiateWorkflowTemplateOperator

### ISSUE THREAD

**Issue by jaketf** [apache/airflow#10385]
**Description**

This operator should cancel running workflow template `on_kill`. This option probably should be configurable because of request_id prameter in a job definition: https://googleapis.dev/python/dataproc/latest/gapic/v1/api.html#google.cloud.dataproc_v1.WorkflowTemplateServiceClient.instantiate_inline_workflow_template
https://googleapis.dev/python/dataproc/latest/gapic/v1/api.html#google.cloud.dataproc_v1.WorkflowTemplateServiceClient.instantiate_workflow_template

Note this will have to cancle the Google Long Running Operation for the workflow template (which will in turn cancel all children jobs and clean up relevant cluster).

**Use case / motivation**

Remove dangling workflow templates

**Related Issues**
#10381
#6371

**Comment by nervoussidd** [comment]
.take-issue

**Comment by potiuk** [comment]
It does not work this way - you need to comment that you want to work on it, but I assigned you nevertheless @nervoussidd :)

**Comment by pankajastro** [comment]
do we still need this since the related issue has closed and DataprocWorkflowTemplateInstantiateInlineOperator has been deprecated?

**Comment by potiuk** [comment]
I think yes - the operator it's been deprecated with also misses the `on_kill` - we have been discussing that with @eladkal recently and I think all the operators that start some external job should have an `on_kill` implemented to be able to cancel running job when it is marked as failed/cleared and it is still running (unless it cleans up after itself automatically - for example cancelling a job that has an opened SQL query via dbapi will automatically close the connection and cancel such running query). 

I think in general, it would be nice to identify all such operators that miss proper cleaning, and implement on_kill methods for them. Maybe a good idea for some kind of spring cleanup :D  ?

**Comment by potiuk** [comment]
BTW. I renamed the operator in the subjects to point to the target one.

**Comment by pankajastro** [comment]
>  I think all the operators that start some external job should have an on_kill implemented to be able to cancel running job when it is marked as failed/cleared

yes, it would be great to have `ok_kill` for such operators. thank you!

**Comment by michalsosn** [comment]
Hi, I could take this issue on if it's ok with you

**Comment by eladkal** [comment]
@michalsosn assigned

**Comment by vksunilk** [comment]
Is this done or inprogress? Or shall I take it up? @eladkal @michalsosn

**Comment by michalsosn** [comment]
I have developed an implementation that I've tested in my custom extension of the Template Operator (you can see it [here](https://gist.github.com/michalsosn/606d045060d39ac0082a06ecf94ab346), the snippet covers more functionality than killing). So there's some progress, but I'm still working on integrating it into the Airflow codebase.

**Comment by michalsosn** [comment]
### operators in dataproc module

```
not killable, don't start a process:
    class DataprocCreateClusterOperator(GoogleCloudBaseOperator)
    class DataprocScaleClusterOperator(GoogleCloudBaseOperator)
    class DataprocDeleteClusterOperator(GoogleCloudBaseOperator)
    class DataprocUpdateClusterOperator(GoogleCloudBaseOperator)
    class DataprocDeleteBatchOperator(GoogleCloudBaseOperator)
    class DataprocGetBatchOperator(GoogleCloudBaseOperator)
    class DataprocListBatchesOperator(GoogleCloudBaseOperator)
    class DataprocCancelOperationOperator(GoogleCloudBaseOperator)
    class DataprocCreateWorkflowTemplateOperator(GoogleCloudBaseOperator)

killable, have on_kill, deprecated (by DataprocSubmitJobOperator):
    class DataprocJobBaseOperator(GoogleCloudBaseOperator)  // they have on_kill implemented
        def on_kill(self) -> None:
            """Callback called when the operator is killed; cancel any running job."""
            if self.dataproc_job_id:
                self.hook.cancel_job(project_id=self.project_id, job_id=self.dataproc_job_id, region=self.region)

    class DataprocSubmitPigJobOperator(DataprocJobBaseOperator)
    class DataprocSubmitHiveJobOperator(DataprocJobBaseOperator)
    class DataprocSubmitSparkSqlJobOperator(DataprocJobBaseOperator)
    class DataprocSubmitSparkJobOperator(DataprocJobBaseOperator)
    class DataprocSubmitHadoopJobOperator(DataprocJobBaseOperator)
    class DataprocSubmitPySparkJobOperator(DataprocJobBaseOperator)

killable, have on_kill:
    class DataprocSubmitJobOperator(GoogleCloudBaseOperator)  // on_kill added 18.08.2020 in https://github.com/apache/airflow/issues/10381
        def on_kill(self):
            if self.job_id and self.cancel_on_kill:
                self.hook.cancel_job(job_id=self.job_id, project_id=self.project_id, region=self.region)

    class DataprocCreateBatchOperator(GoogleCloudBaseOperator)
        def on_kill(self):
            if self.operation:
                self.operation.cancel()

killable, no on_kill:
    class DataprocInstantiateWorkflowTemplateOperator(GoogleCloudBaseOperator)
    class DataprocInstantiateInlineWorkflowTemplateOperator(GoogleCloudBaseOperator)
```

Since there was a discussion about implementing the `on_kill` method in all operators, I've prepared a summary. 
It seems that, among the operators in the dataproc module, only the `Workflow` operators, which are the target of this issue, do not have it implemented yet.

**Comment by michalsosn** [comment]
[this](https://github.com/apache/airflow/compare/main...michalsosn:airflow:10385-DataprocInstantiateWorkflowTemplateOperator-on_kill) change looks reasonable. Now I need to thoroughly read about how to test these changes in this project.
