### ISSUE TITLE
Documentation is missing instructions for preparing database for Airflow (during installation)

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [apache/airflow#10389]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):  N/A 

**Environment**:

- **Cloud provider or hardware configuration**:  AWS 
- **OS** (e.g. from /etc/os-release): Amazon Linux 2
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A 
- **Others**: N/A

**What happened**:
Airflow documentation is missing a step -- preparing the database for Airflow initdb.

This includes creating the "airflow" database, and the "airflow" user.

There are multiple different instructions for it outside the documentation, e.g.:

https://medium.com/@srivathsankr7/apache-airflow-a-practical-guide-5164ff19d18b says:

```
mysql -u root -p
mysql> CREATE DATABASE airflow CHARACTER SET utf8 COLLATE utf8_unicode_ci;
mysql> create user 'airflow'@'localhost' identified by 'airflow';
mysql> grant all privileges on * . * to 'airflow'@'localhost';
mysql> flush privileges;
```

http://site.clairvoyantsoft.com/installing-and-configuring-apache-airflow/ says:

```
CREATE DATABASE airflow CHARACTER SET utf8 COLLATE utf8_unicode_ci;
grant all on airflow.* TO ‘USERNAME'@'%' IDENTIFIED BY ‘{password}';
```

https://airflow-tutorial.readthedocs.io/en/latest/first-airflow.html says:

```
MySQL -u root -p
mysql> CREATE DATABASE airflow CHARACTER SET utf8 COLLATE utf8_unicode_ci;
mysql> GRANT ALL PRIVILEGES ON airflow.* To 'airflow'@'localhost';
mysql> FLUSH PRIVILEGES;
```

(This last one seems to be missing the step of creating the `airflow` user.)

**What you expected to happen**:

I would expect https://airflow.apache.org/docs/stable/howto/initialize-database.html to contain complete instructions for preparing the database backend for initialization.
 
**How to reproduce it**:

Try to install Airflow with a MySQL backend with no prior knowledge by following the Airflow documentation.

**Anything else we need to know**:

Airflow rocks!

**Comment by mik-laj** [comment]
Thanks for your feedback. Wouldn't you like to contribute this documentation change? You can do it even using Github UI.
https://docs.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository
I am very happy to help with the review of this change.

**Comment by potiuk** [comment]
Yeah. The best contributions in docs are from those who suffered from lack of it. You can write it in the way that will be usable for other newcomers so I encourage you to contribute it @atsalolikhin-spokeo :)

**Comment by atsalolikhin-spokeo** [comment]
Hello,

I was unable to commit my change.  The pre-commit hook test suite failed on:

```
Check if image build is needed....................................................................................................Failed
```

I had a look at your Contributing document, and the bar is a bit high -- Breeze, Docker, virtualenv -- I tried following the instructions but `breeze` did not start:

```
[~/git/airflow] fix/10389(+19/-0) ± ./breeze
[~/git/airflow] fix/10389(+19/-0) 1 ± echo $?
1
[~/git/airflow] fix/10389(+19/-0) ±
```

Here is the patch I was going to send in:

```
diff --git a/docs/howto/initialize-database.rst b/docs/howto/initialize-database.rst
index aabee9434..b3129286d 100644
--- a/docs/howto/initialize-database.rst
+++ b/docs/howto/initialize-database.rst
@@ -48,12 +48,31 @@ SqlAlchemy backend. We recommend using **MySQL** or **Postgres**.
    want to set a default schema for your role with a
    command similar to ``ALTER ROLE username SET search_path = airflow, foobar;``
 
+Setup your database to host Airflow
+-----------------------------------
+
+Create a database called ``airflow`` and a database user that Airflow
+will use to access this database.
+
+Example, for **MySQL**:
+
+.. code-block:: sql
+   CREATE DATABASE airflow CHARACTER SET utf8 COLLATE utf8_unicode_ci;
+   CREATE USER 'airflow' IDENTIFIED BY 'airflow';
+   GRANT ALL PRIVILEGES ON airflow.* TO 'airflow';
+
+Configure Airflow's database connection string
+----------------------------------------------
+
 Once you've setup your database to host Airflow, you'll need to alter the
 SqlAlchemy connection string located in your configuration file
 ``$AIRFLOW_HOME/airflow.cfg``. You should then also change the "executor"
 setting to use "LocalExecutor", an executor that can parallelize task
 instances locally.
 
+Initialize the database
+-----------------------
+
 .. code-block:: bash
 
     # initialize the database
```

**Comment by mik-laj** [comment]
pre-commit is optional. For small changes to the documentation, I very often post the changes without pre-commit to the CI. When an error occurs, I apply the correction locally and send the change again to CI. This is also the reason why I recommended editing the documentation via Github UI.

**Comment by potiuk** [comment]
@atsalolikhin-spokeo  Also you can always run `git commit --no-verify` which will skip pre-commit step.

**Comment by potiuk** [comment]
BTW. I almost never skip `pre-commits`  - they are super helpful and usually when they fail, there is a good reason to fix it .

**Comment by potiuk** [comment]
BTW. The recent changes to pre-commit script will hopefully fix one more reason for a problem, but @atsalolikhin-spokeo  - if  you rebase to latest version and run it again and it fails, please send me the output - maybe there is another case that I missed :)

I would love those pre-commits to be rock-solid so that people won't skip the pre-commits too often.

**Comment by atsalolikhin-spokeo** [comment]
@potiuk Thanks for letting me know about `git commit --no-verify`.  I've rebased to the tip of master and tried `git commit --verify` and it failed on the same step:

```
Check if image build is needed....................................................................................................Failed
```

**Comment by atsalolikhin-spokeo** [comment]
Great idea to get the pre-commit hook rock-solid so that it can run every time.

**Comment by potiuk** [comment]
I would love to hear more about the failure @atsalolikhin-spokeo . Would it be possible that you pass the output that you get wit it? It shoud print more information - usually. If not you can always run `pre-commit run build --verbose` and pass me the output.

**Comment by atsalolikhin-spokeo** [comment]
```
[~/git/airflow] fix/10389 ±
[~/git/airflow] fix/10389 ± command -v  getopt
/usr/bin/getopt
[~/git/airflow] fix/10389 ± getopt --version
 --
[~/git/airflow] fix/10389 ± getopt -T
 --
[~/git/airflow] fix/10389 ± echo $?
0
[~/git/airflow] fix/10389 ± brew --prefix getopt
Error: No available formula with the name "getopt"
[~/git/airflow] fix/10389 ± hash -r
[~/git/airflow] fix/10389 ± command -v  getopt
/usr/bin/getopt
[~/git/airflow] fix/10389 ±
```

I opened a new shell:

```
[~] $ command -v  getopt
/usr/bin/getopt
[~] $
```

Okay, that's the macOS getopt; so where is brew's getopt?

```
[~] $ find . -name getopt 2>/dev/null
./git/homebrew/Cellar/gnu-getopt/2.36/bin/getopt
./git/homebrew/Cellar/gnu-getopt/2.36/etc/bash_completion.d/getopt
./git/homebrew/Cellar/libusb/1.0.23/share/libusb/examples/getopt
[~] $ ./git/homebrew/Cellar/gnu-getopt/2.36/bin/getopt --version
getopt from util-linux 2.36
[~] $
```
So I've added it to my PATH.

```
[~/git/airflow] fix/10389 ± type getopt
getopt is /Users/atsalolikhin/git/homebrew/Cellar/gnu-getopt/2.36/bin/getopt
[~/git/airflow] fix/10389 ±
```
 

Now the pre-commit hook works:

```
[~/git/airflow] fix/10389 ± pre-commit run build --verbose
Check if image build is needed...........................................
Please confirm rebuild image CI-python3.6. Are you sure? [y/N/q]
y
The answer is 'yes'. rebuild image CI-python3.6. This can take some time!
Preparing apache/airflow:master-python3.6-ci.

Docker pulling python:3.6-slim-buster.

Build log: /var/folders/5m/1v1dg76s7zbdpwj39dh5skv80000gp/T/tmp.BExKt31d/out.log
/
Preparing apache/airflow:master-python3.6-ci.

Docker building apache/airflow:master-python3.6-ci.

Build log: /var/folders/5m/1v1dg76s7zbdpwj39dh5skv80000gp/T/tmp.BExKt31d/out.log
Step 96/100 :\
Passed
- hook id: build
- duration: 66.95s

Some of your images need to be rebuild because important files (like package list) has changed.

You have those options:
   * Rebuild the images now by answering 'y' (this might take some time!)
   * Skip rebuilding the images and hope changes are not big (you will be asked again)
   * Quit and manually rebuild the images using one of the following commands
        * ./breeze build-image
        * ./breeze build-image --force-pull-images

   The first command works incrementally from your last local build.
   The second command you use if you want to completely refresh your images from dockerhub.


Force pull base image python:3.6-slim-buster



Pulling the image apache/airflow:master-python3.6-ci

[~/git/airflow] fix/10389 ±
```

It's too bad the brew install didn't automagically make the gnu-getopt take precedence over the system getopt.  I understand the need for user awareness/choice in that.  I must have not read the prompt to take the manual step to adjust the path. Anyway it's done now.  Thanks!
