### ISSUE TITLE
Add on_kill method to KubernetesPodOperator

### ISSUE THREAD

**Issue by krisdock** [apache/airflow#10383]
**Description**

Kubernetes Pods that are created by KubernetesPodOperator aren't deleted when a running task is killed/cleared from the Airflow UI. There's a known function (on_kill) that can be implemented to properly handle this scenario.

**Use case / motivation**

If a running Airflow task is killed, the associated Kubernetes Pod should ideally be deleted. 

**Related Issues**

None

**Comment by krisdock** [comment]
@dimberman

**Comment by paolaperaza** [comment]
Thanks for submitting this, @krisdock! @dimberman Looks like you submitted a PR for this and it was merged a few days ago: https://github.com/apache/airflow/pull/10666

Want to close out this GH issue and add the 1.10.13 milestone to this?

Related followup PR:
- [Make grace_period_seconds option on K8sPodOperator #10727](https://github.com/apache/airflow/pull/10727)

**Comment by dimberman** [comment]
Issue has been addressed and merged
