### ISSUE TITLE
Add list of prerequisites that new provider package should fulfill

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10386]
**Description**

We need to have a folder template (ideally) and list of prerequisites that each provider should fulfill when it is created.

**Use case / motivation**

To make it easy to add new provider and to make new contributors aware what is needed in order to add provider. The following should be added:

- [x] directory structure (possibly automated templates or script to create them)
- [ ] usage scenarios for connections in hooks  (see discussion in #12128)
- [ ] Information about what is required:
    - [ ] hooks
    - [ ] operators/sensors/transfers
    - [ ] unit tests with mocks
    - [ ] integration tests if applicable
    - [ ] example dags for examples and their use (examples, howtos, system tests)
    - [ ] howto guides
- [ ] relation with backport providers.

**Comment by pcandoalmeida** [comment]
Hi @potiuk 🙂 I was thinking about taking a look at this; would you mind if I asked to help clarify the issue a bit further? Would this require a Gitub repository PR template update and documentation or something completely different? Apologies if I am missing the obvious here!

**Comment by potiuk** [comment]
It's rather about folder structure. We have monorepo - providers are in 'providers'  packages/folders  - both 'airflow' and 'tests' subfolders and they follow certain structure

**Comment by potiuk** [comment]
Ah sorry - did not understand. I think it is mostly a 'CONtRIBUTING.rat' update or rather creating new 'how to create a new provider.rst' file + folder structure explanation( or anyone script creating a new provider with some scaffolding)

**Comment by pcandoalmeida** [comment]
Thanks for the clarification @potiuk. I can certainly try working on the documentation to begin with if that suits.

**Comment by TobKed** [comment]
Any updates for this issue? @pcandoalmeida are you planning to come back working on this? I am happy to help with it.
I opened PR with new operator ([Apache Beam operators](https://github.com/apache/airflow/pull/12814)) and information about prerequisites for new providers will be very helpful.

**Comment by TobKed** [comment]
Is it not solved by https://github.com/apache/airflow/pull/12921 ?

**Comment by pcandoalmeida** [comment]
Hey @TobKed sorry for the delay on this! @potiuk shall we close this issue?

**Comment by TobKed** [comment]
Hi @pcandoalmeida , it is only partly solved. I created draft PR https://github.com/apache/airflow/pull/13193 to push it forward

**Comment by potiuk** [comment]
Yeah. The docs in #12921 only describe prerequisites for "custom" providers - which can be structured in whatever way the 3rd-party provider wants them to be. But there are much "higher" requirements for the providers that are part of the Airflow repo (i.e. community-managed ones) - documentation, examples, proper structure and naming, provider.yaml file etc. We cannot expect 3rd-party provider to fulfill all that (and we have no way of enforcing it). But we have very good checks already and review process to require them from all the Airflow providers :)

**Comment by eladkal** [comment]
@potiuk I think https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#developing-community-managed-provider-packages covers it quite nicely. Do you think we need something more?

**Comment by potiuk** [comment]
Absolutely. Closing it.
