### ISSUE TITLE
Invalid Syntax Error When Importing hdfs_hook

### ISSUE THREAD

**Issue by amirulmenjeni** [apache/airflow#10395]
**Apache Airflow Version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use kubectl version): N/A

**Environment:**
- **Cloud provider or hardware configuration**: N/A
- **OS**: CentOS Linux 7 (Core)
- **Kernel**: Linux myhost 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

Received syntax error when importing from `airflow.hooks.hdfs_hook` on Python 3.7.8. Here's the error message:

```
Traceback (most recent call last):
  File "subdags/copy_subset.py", line 9, in <module>
    from airflow.hooks.hdfs_hook import HDFSHook
  File "/home/amirul.menjeni/.pyenv/versions/dataops-flow-env/lib/python3.7/site-packages/airflow/hooks/hdfs_hook.py", line 24, in <module>
    from snakebite.client import Client, HAClient, Namenode, AutoConfigClient
  File "/home/amirul.menjeni/.pyenv/versions/dataops-flow-env/lib/python3.7/site-packages/snakebite/client.py", line 1473
    baseTime = min(time * (1L << retries), cap);
                            ^
SyntaxError: invalid syntax
```

**What you expect to happen**:

No syntax error when importing.

**How to reproduce it**:

- Create python version 3.7.8 environment
- Install airflow
- Import `airflow.hooks.hdfs_hook`

**Comment by amirulmenjeni** [comment]
Relevant: https://github.com/spotify/snakebite/issues/216

**Comment by ephraimbuddy** [comment]
You need to install snakebite-py3, snakebite does not work with python 3. I'll try and address this in master

**Comment by amirulmenjeni** [comment]
Thanks, `pip install snakebite-py3` fixed this issue.

**Comment by ephraimbuddy** [comment]
@mik-laj, `snakebite-py3` is a fork of `snakebite` and is not maintained by Spotify. Do you suggest we should use it in place of `snakebite`?

**Comment by turbaszek** [comment]
Closing as the issue seems to be solved and it seems that `snakebite-py3` is required for hdfs:
https://github.com/apache/airflow/blob/12a652f5344c7f03c3d780556ca1829b235fdb2d/setup.py#L296-L298
