### ISSUE TITLE
Vertica hook empty password problem

### ISSUE THREAD

**Issue by aadim** [apache/airflow#1040]
When a Vertica connection is created using the web admin and the password is not specified the password is set to NULL in Airflow database.
When trying to connect and execute some query using Vertica hook there's an exception thrown

```
from airflow.contrib.hooks import VerticaHook
h = VerticaHook('vertica_test')
h.get_first('select 1')
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/airflow/hooks/dbapi_hook.py", line 75, in get_first
>     conn = self.get_conn()
>   File "/usr/local/lib/python2.7/dist-packages/airflow/contrib/hooks/vertica_hook.py", line 31, in get_conn
>     conn = connect(**conn_config)
>   File "/usr/local/lib/python2.7/dist-packages/vertica_python/**init**.py", line 30, in connect
>     return Connection(kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 34, in **init**
>     self.startup_connection()
>   File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 247, in startup_connection
>     password = self.options['password'].encode('ascii')
> KeyError: 'password'

As a temporary solution I have to update Airflow DB and set the password to an empty string.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/commit/adab0cf9de1081ec19db102bcea4405c629d0baf

This should fix it, please confirm.

**Comment by aadim** [comment]
it's OK. thanks a lot!
