### ISSUE TITLE
DAGs remain in the UI after they are deleted

### ISSUE THREAD

**Issue by marcjimz** [apache/airflow#10427]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.14.8

**Environment**: PROD

- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16
- **Kernel** (e.g. `uname -a`): Linux
- **Install tools**: N/A
- **Others**: N/A

**What happened**: Today we use git-sync container to sync the commitment of DAGs into both our Airflow scheduler and Airflow web UI. When you delete a DAG from the Github repository, the reference of the DAG remains on the UI however when you click into it, we get HTTP404 DAG not found. 

We are running on Kubernetes and are running on Airflow 1.10.10

Below is the screen of the BashOperator, which we have deleted, and once we click into it we get Page Not Found. Upon returning to the main page we see the below error:

![Screen Shot 2020-08-20 at 8 20 47 AM](https://user-images.githubusercontent.com/4607826/90784192-3e977b80-e2be-11ea-87af-268eb9d01dca.png)

**What you expected to happen**:

When we delete the DAG, we expect it to not be available or displaying on the screen anymore

**How to reproduce it**:

Orchestrate AirFlow similarly with git-sync, run the DAG, then delete the DAG OR rename the DAG name within the file. It should rename.

**Anything else we need to know**:

This is a non-blocking issue but this will lead to issues with our users, any recommendations on a fix is appreciated

**Comment by kaxil** [comment]
Is this with or without DAG Serialization @marcjimz ?

**Comment by ryw** [comment]
@kaxil @ernest-kr are we able to reproduce this?

**Comment by kaxil** [comment]
> @kaxil @ernest-kr are we able to reproduce this?

This is my next task actually -- will come back with my findings

**Comment by kaxil** [comment]
I am not able to reproduce this on Airflow 2.0.0beta3, once I deleted the DAG file the DAG disappeared from the UI in sometime.

@marcjimz Can you please try with out with 2.0.0beta3 and let us know if the issue persist, we can reopen the issue if that happens

**Comment by hpareek1996** [comment]
Hi @marcjimz, so did you upgraded airflow or followed some other approach to fix this.
