### ISSUE TITLE
Multiple prefixes in GoogleCloudStorageListOperator and GoogleCloudStorageDeleteOperator

### ISSUE THREAD

**Issue by EmadMokhtar** [apache/airflow#10426]
**Description**

Support passing multiple prefixes to `GoogleCloudStorageListOperator` and `GoogleCloudStorageDeleteOperator` operators.

**Use case / motivation**

I have this folder structure in GCS bucket.

```
+-- year={year}
|   +-- month={month}
|       +--day={day}
|           +-- topic={topic1}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic2}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic3}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic4}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic5}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic6}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic7}
|       +--day={day}
|           +-- topic={topic1}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic2}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic3}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic4}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic5}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic6}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           +-- topic={topic7}
|                 +--file 1
|                 +--file 2
|                 +--file 3
|           ....
```

What I need to achieve is delete one day of objects. For example, I need to delete objects in `year=2020/month=08/day=19`. I can do that easily using `gsutils`. In `gsutil` you can delete them via wild card `gsutil ear=2020/month=08/day=19/*` but using the REST APIs you can't even if you use a prefix. The reason is there is no one prefix to get all the objects inside a folder. I achieved that by using multiple prefixes and for each prefix, I will get the list of objects. Unfortunately, I can't pass more than one prefix to the operators.

**Prefixes used**
- `year=2020/month=08/day=19/topic={topic1}`
- `year=2020/month=08/day=19/topic={topic2}`
- `year=2020/month=08/day=19/topic={topic3}`
- `year=2020/month=08/day=19/topic={topic4}`
- `year=2020/month=08/day=19/topic={topic5}`
- `year=2020/month=08/day=19/topic={topic6}`
- `year=2020/month=08/day=19/topic={topic7}`

**Comment by EmadMokhtar** [comment]
# Initial implementation

I implement it like this in my project


``` python
    def execute(self, context):
        hook = GoogleCloudStorageHook(
            google_cloud_storage_conn_id=self.google_cloud_storage_conn_id,
            delegate_to=self.delegate_to
        )

        if self.objects:
            objects = self.objects
        else:
            objects = []
            for prefix in self.prefixes:
                prefix_objects = hook.list(bucket=self.bucket_name,
                                           prefix=prefix)
                objects.extend(prefix_objects)
                self.log.info(prefix_objects)

        self.log.info("Deleting %s objects from %s",
                      len(objects), self.bucket_name)
        for object_name in objects:
            hook.delete(bucket=self.bucket_name,
                        object=object_name)
```

**Comment by mik-laj** [comment]
@EmadMokhtar Do you need help creating a PR? Your use case looks interesting and it looks like it's worth thinking about.

**Comment by EmadMokhtar** [comment]
@mik-laj I would like to make a PR for this. Please assign the ticket to me and I create a PR.

**Comment by mik-laj** [comment]
@EmadMokhtar  I assigned you to this ticket.

**Comment by EmadMokhtar** [comment]
# Decision

What I'm planning to do is to modify the `GCSHook.list()` method to accept `prefixes` instead of `prefix`. I need to know how we can do that with backward compatibility? Some old code will assume this hook is accepting one prefix and we need to raise a deprecation warning. Or maybe it is only used internally and I need to refactor the operators who use it?

**Comment by eladkal** [comment]
> What I'm planning to do is to modify the `GCSHook.list()` method to accept `prefixes` instead of `prefix`. I need to know how we can do that with backward compatibility? Some old code will assume this hook is accepting one prefix and we need to raise a deprecation warning. Or maybe it is only used internally and I need to refactor the operators who use it?

`prefix` is a parameter of `list_blobs` https://googleapis.dev/python/storage/latest/client.html
even if you modify the parameter on the hook at the end you will still be able to utalize only single prefix each time.
You can modify prefix to accept `Optional[str,List[str]]` that way the modification is also backward compatible. This has some similarities to approach suggested on https://github.com/apache/airflow/issues/15001

**Comment by potiuk** [comment]
@eladkal 's proposal sounds good.

**Comment by eladkal** [comment]
@EmadMokhtar are you still working on this issue?

**Comment by shahar1** [comment]
@eladkal Please assign me

**Comment by shahar1** [comment]
The original issue seems to be resolved natively, as I recreated the OP's file structure and deleted the entire `2020/month=08/day=19` object by simply passing it as the `prefix` parameter.
However, as it might be helpful to support multiple prefixes for other reasons (for example, I want to delete only `year=2020/month=08/day=19` and `year=2020/month=08/day=20` using one operator) - I created a PR for that.
