### ISSUE TITLE
Stale documentation for Kubernetes Executor

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#10455]
**What happened**:

In documentation about Kubenetes Executor (https://airflow.apache.org/docs/stable/executor/kubernetes.html or https://github.com/apache/airflow/blob/v1-10-test/docs/executor/kubernetes.rst), we see contents below 
![Kubernetes_Executor_—_Airflow_Documentation](https://user-images.githubusercontent.com/11539188/90930154-58d67400-e3fa-11ea-9180-390ccd4574b3.png)

However, we cannot find corresponding files in https://github.com/apache/airflow/tree/master/scripts/ci/kubernetes or https://github.com/apache/airflow/tree/v1-10-test/scripts/ci/kubernetes

**What you expected to happen**:

Documentation update

**Comment by dimberman** [comment]
Sorry for the delay on this! I've been pretty heads down on 2.0. Will take a look :)

**Comment by dimberman** [comment]
@XD-DENG I've backported some awesome fixes to the kubernetes architecture by @vikramkoka. Will go out with 1.10.13

**Comment by XD-DENG** [comment]
Cool, thanks @dimberman and @vikramkoka
