### ISSUE TITLE
helm pull stable/airflow pulls the [stable/airflow] chart from github.com/helm/charts repository and not this repository.

### ISSUE THREAD

**Issue by axk7812** [apache/airflow#10486]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.17.0

**Environment**:
AWS
Linux x86_64 x86_64 x86_64 GNU/Linux
Helm 3.2.0

**What happened**:
Following the directions to install the chart in this repository, and instead it pulls the chart from https://github.com/helm/charts/tree/master/stable/airflow

**What you expected to happen**:
The chart from https://github.com/apache/airflow/tree/master/chart should be pulled.

You can verify that the `values.yaml` pulled matches the one from helm/stable rather than the one in apache/airflow chart.

**How to reproduce it**:
```
kubectl create namespace airflow
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm dep update
helm install airflow . --namespace airflow
```

As minimally and precisely as possible. Keep in mind we do not have access to your cluster or dags.

If you are using kubernetes, please attempt to recreate the issue using minikube or kind.

If this is a UI bug, please provide a screenshot of the bug or a link to a youtube video of the bug in action

How often does this problem occur? Once? Every time etc?

**Comment by potiuk** [comment]
I'd leave it up to @dimberman

**Comment by mik-laj** [comment]
Now the documentation no longer references the wrong repository. We also have a warning at the beginning of the README.md file that this Chart has not been released.
<img width="1106" alt="Screenshot 2021-03-07 at 00 30 36" src="https://user-images.githubusercontent.com/12058428/110224488-5cd06c00-7edc-11eb-9dd8-8254291e80fb.png">
I don't think we can do anything else but release a Helm Chart, which is described in another ticket. See: https://github.com/apache/airflow/issues/10752

Related:  https://github.com/apache/airflow/pull/14643
