### ISSUE TITLE
Query errors after initdb

### ISSUE THREAD

**Issue by chris-hailstorm** [apache/airflow#1048]
Using a remote MySQL DB, I was able to run `airflow initdb` successfully using this connect string:

`sql_alchemy_conn = mysql+pymysql://username:password@some.thing.us-west-2.rds.amazonaws.com/schemaname` -- note use of `mysql+pymysql`.

When I try to do something basic in the web UI like click into a DAG, I get a SQL error:

`ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[(\\'dag_id\\', u\\'example_bash_operator\\')]'')' at line 1") [SQL: u'INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%(dttm)s, %(dag_id)s, %(task_id)s, %(event)s, %(execution_date)s, %(owner)s, %(extra)s)'] [parameters: {'task_id': None, 'extra': "[('dag_id', u'example_bash_operator')]", 'execution_date': None, 'dttm': datetime.datetime(2016, 2, 21, 11, 54, 18, 218042), 'owner': 'anonymous', 'event': 'graph', 'dag_id': u'example_bash_operator'}]`

The stack trace shows this exception being raised from the `pymysql` package. Seems like the SQL syntax is incompatible with the driver and/or the MySQL server version.

I found this problem can be resolved by switching to the `mysql+mysqldb` driver.  Depending on the client OS, this combination can be a little tricky to install, but nevertheless appears to be the solution.

Recommendation: do not allow `pymysql` during the initdb phase since it is not yet allowed in the webserver phase.  Provide advice in install doco to use the `mysql+mysqldb` driver only at this time.

**Comment by mistercrunch** [comment]
`pymysql` isn't supported at the moment, mostly because of issues in the sqlalchemy layer.

Can you try with `mysqlclient` (works with both py27 and py34) and see if the problem persists?
