### ISSUE TITLE
[OPTIMISATION] Selective builds for different types of tests

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10507]
**Description**

After we've implemented AIP-21 with backport packages and quite recently #10422 "Optimisation of Image building on CI" - we have now an interesting opportunity to speed up the tests even more. Previously each job had 4-10 minutes of overhead which is now down to just 1 minute of image pulling (so it cannot be optimized further). This is very little overhead and now we can have more jobs running in parallel for one job. This might speed up significantly most of our builds.

While the "merges" on master should build the full suite of tests, we can limit the tests run on PR:

1) If core python files change - run all the tests for all backends and versions.

2) If only files from certain provider are changed - run only tests for that provider and all providers that depend on it (we already have all the information to know which providers depend on each other). This can be done only for one backend (and all python versions) - for example, sqlite. Maybe some edge-cases in providers that require mysql/postgres.

With this change, if someone changes only one provider, the tests should run in few minutes rather than hours.

The best is to add another test type "Providers" with different matrix of runs and add custom filtering depending on the files modified by the PR (we already do similar filtering in kubernetes tests). This means we need more jobs (that's why reusing image built only once was so important). 

This can be implemented in two steps:

 - [ ]  extracting common composite test run step (which can be used to run all types of tests including the MySQL/Postgres ones) : https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
 - [ ]  implement the "Providers" type of test job with filtering only the tests for impacted providers (both direct and dependent providers)

**Use case / motivation**

Most contributors - only contributing code to providers - should wait less than 10 minutes for the result of their PR build (in terms of elapsed  time since the builds starts - there might be some queuing time that we might have no influence on).

**Related Issues**

#10422 #10959

**Comment by potiuk** [comment]
cc: @kaxil @dimberman @feluelle @turbaszek @mik-laj -> I think we want that :). Any comments are welcome. I am happy to collaborate with others rather than develop it myself so that you can also learn how our CI works.

**Comment by kaxil** [comment]
I will be happy to collaborate on this one :) -- let me know how should we proceed.

**Comment by potiuk** [comment]
> I will be happy to collaborate on this one :) -- let me know how should we proceed.

Cool! When we merge the #10959  (which introduces "programmability"), I will open a PR where I will propose a mechanism and some implementation for some of the "programmable" criteria and I will be happy to iterate on it and discuss all the different "variations" we might want and edge cases. We need to be rather careful with that - to not miss some important dependencies and cases. I have my proposal where I introduce not only several variations but I also add unit tests covering it, to make it robust and will be happy to collaborate on that :)
