### ISSUE TITLE
Adding 'body' as templated field to CloudSqlInstanceImportOperator

### ISSUE THREAD

**Issue by MohammedDiab** [apache/airflow#10508]
**Description**

it is really useful to have the body parameter as templated field, the parameter can have attributes related to file path, table name, database and many more  which usually comes from a previous operator that do the work and then send the information to the  CloudSqlInstanceImportOperator
 
**Use case / motivation**

I have the following case :

1.  GoogleDataFlowOperator that runs first to do some transformations and then stores the result as csv file on Google Bucket 
2. The CloudSqlInstanceImportOperator is supposed to load the csv into a a cloud sql instance but the import body isn't a templated field so it is challenging to pass the files dynamically to the operator, I had to override the operator just to add the body as templated field

**Comment by potiuk** [comment]
Would you be so kind to add a PR with this change? I am happy to review it once you ping me - this seems to be super -easy change.

**Comment by MohammedDiab** [comment]
@potiuk yes sure, i'm currently creating the PR

**Comment by mik-laj** [comment]
> If you create pull-request, you don't have to create an issue first, but if you want, you can do it. Creating an issue will allow you to collect feedback or share plans with other people.

https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow

**Comment by mik-laj** [comment]
Part-of: https://github.com/apache/airflow/issues/8893

**Comment by MohammedDiab** [comment]
@potiuk here is the PR, 
https://github.com/apache/airflow/pull/10510

**Comment by yashhd** [comment]
@MohammedDiab Hi I'm a little new to airflow and have been implementing a project of my own where I'm using cloudsqlinstanceimport operator. What exactly did you mean by having the body parameter as a templated field? 
 In this link - https://airflow.apache.org/docs/stable/howto/operator/gcp/sql.html#cloudsqlinstanceimportoperator , the body parameter is already present. So were you saying that it wouldn't have worked before your pull request got merged?

**Comment by MohammedDiab** [comment]
@yashhd the body field was already there, the issue was you couldn't render Airflow variables inside the `body` parameter. examples of Airflow variables here https://airflow.apache.org/docs/stable/macros-ref.html

**Comment by yashhd** [comment]
@MohammedDiab Oh yes, I understood. Thanks for clarifying!
