### ISSUE TITLE
task decorator for identifying functions as tasks

### ISSUE THREAD

**Issue by teaglebuilt** [apache/airflow#10511]
**Description**

A @task decorator to mark functions as tasks during dag run time. 

**Use case / motivation**
we have one task / function that has functions inside that are not marked as tasks. We want to expose metrics with the airflow - [exporter airflow plugin](https://github.com/robinhood/airflow-prometheus-exporter). If we can mark functions as tasks, this would allow for capturing metrics on these functions.

```
@task
def function():
    pass
```

**Comment by kaxil** [comment]
This is now possible with https://airflow.readthedocs.io/en/latest/tutorial_decorated_flows.html

**Comment by kaxil** [comment]
https://airflow.readthedocs.io/en/latest/concepts.html?highlight=Decorated%20Flows#decorated-flows
