### ISSUE TITLE
Trigger Dag requires a JSON conf but Dag Run view display a python dict

### ISSUE THREAD

**Issue by marcoaaguiar** [apache/airflow#10519]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Windows 10 WSL (Ubuntu18.04.4)

- **Kernel** (e.g. `uname -a`): Linux DESKTOP-8IVSCHM 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

In the __Trigger Dag__ view for a specific Dag, the view asks for JSON formatted object as inpunt. 
In the __Dag Runs__ view (list), it shows python formatted object in the __Conf__ column.

Despite JSON and Python formating being quite similar they differ in respect to string quotation marks: json uses double-quotes(") and python uses single quote(').
This makes annoying to copy a previously used config to a new trigger.

**What you expected to happen**:

I would expect a consistent read/write of Dag Run configuration. 
In particular require a Json in the Trigger Dag view, and display a Json in the DAG Runs view.

**How to reproduce it**:

1. Trigger a DAG manually passing a Json dict `{"test": "this is a test"}`.
2. Go to Dag Runs view, it shows as `{'test': 'this is a test'}`

**Anything else we need to know**:

This is not application breaking issue, more a quality of life/usability issue. 
I imagine it would be a minor change and could be tagged as an first issue

**Comment by mik-laj** [comment]
This is a great ticket for a first contribution. Would you like to help us with this?
Development environment guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Contributor guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

If you have problems, I will be happy to help.

**Comment by vkreddy** [comment]
@mik-laj  can I work on this issue?

**Comment by mik-laj** [comment]
Yes. You can work on it.

**Comment by marcoaaguiar** [comment]
I was planning to work on this issue this weekend, when I have some free time. 
Do you mind if I take this one, @vkreddy ?
If @mik-laj agrees, of coursee.

**Comment by vkreddy** [comment]
@marcoaaguiar please do I don't mind. I haven't started working on it and also you are the reporter so you have the complete context  :). I will try to find another issue.

**Comment by marcoaaguiar** [comment]
@vkreddy Thanks :)
