### ISSUE TITLE
Builiding image from source

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#10524]
During image builidiing following error appears:

`Step 96/108 : COPY scripts/prod/entrypoint_prod.sh /entrypoint
COPY failed: stat /var/lib/docker/tmp/docker-builder293147199/scripts/prod/entrypoint_prod.sh: no such file or directory`

**Comment by potiuk** [comment]
You seem to not update to latest repo. The script has been moved recently and I think there was a short moment it was not working. Please update/rebase to latest master.

This is the relevant line now in master:

```
COPY scripts/in_container/prod/entrypoint_prod.sh /entrypoint
```
