### ISSUE TITLE
Exception logging success function instead of failure

### ISSUE THREAD

**Issue by danjsouther** [apache/airflow#10553]
https://github.com/apache/airflow/blob/fdd9b6f65b608c516b8a062b058972d9a45ec9e3/airflow/sensors/sql_sensor.py#L97

**Comment by mik-laj** [comment]
Can you share an example of a DAG that causes problems?

**Comment by faihegberg** [comment]
@mik-laj @turbaszek If this issue is not taken yet, I'd be interested to take this on :)

**Comment by mik-laj** [comment]
I assigned you to this ticket. 🐈
