### ISSUE TITLE
New API takes over /airflow/api

### ISSUE THREAD

**Issue by ryw** [apache/airflow#10560]
for 2.0, should we should change the path of `/api_connexion` to `/api` and `/api` to `/api_deprecated`?

Any reason not to do that now in master branch?

**Comment by potiuk** [comment]
It's about our deprecation rules. If it's not absolutely necessary the rule is that we have at least one release when we deprecate something before we remove.

**Comment by potiuk** [comment]
I actually proposed to deprecate the old API in 1.10.12 but the majority  vote was that we should not deprecate something unless we provide a  replacement - which makes perfect sense as it does not allow you to do the sequence:

1) migrate first
2) change your way of doing things
3) migrate again

It requires you to migrate and change at the same time which is super-risky.

**Comment by ryw** [comment]
I'm not suggesting we remove the old api, just give it a different code path - and give /api directory to the new API -- took me a minute today to figure out which one was the new API

**Comment by mik-laj** [comment]
@ryw Moving the API to a different path is a change that breaks all existing integrations. Most of them have a fixed path, and it's not easy to change.  Some users won't even be able to change it easily as they have a heterogeneous environment with different Airflow versions.  

If you want to check if the API is deprecated, you can send a request via CURL and look at the headers.
See:  https://github.com/apache/airflow/pull/9888

**Comment by ryw** [comment]
Ok makes sense - didn't know how routes get rendered, but if it's reading from file structure then I'm ok to keep it as it is for now. Closing issue.

**Comment by mik-laj** [comment]
Have you been talking about package structure or URLs? This is not clear from your ticket.

**Comment by ryw** [comment]
i was referencing source code structure - sorry that wasn't clear

**Comment by mik-laj** [comment]
This here is a more complicated matter as some packages are deprecated and some will not.
**airflow.api.auth**
it's not deprecated. We use it in Stable API also.

**airflow.api.client**
This is still under discussion. We don't have a conclusion about it. For now, @ash has suggested that this package should stay until we have a detailed vision of CLI development.  So we should keep it backward compatible.
https://lists.apache.org/thread.html/rfada8ac2fce87c0516d62923e35e3bebfc44ee5a379103b890f8c61c%40%3Cdev.airflow.apache.org%3E
@houqp working on alternative python client: https://github.com/apache/airflow-client-python https://github.com/apache/airflow/issues/9080

**airflow.api.common.experimental**
This is a surprise, but these are not the endpoints for the experimental API. This package is also widely used in core and web UI. This is another utils package.

**airflow.api_connexion**
Everything related to a stable API.

**airflow.www.api.experimental.endpoints**
Endpoint for experimental API. This package will be deleted in Airflow 2.1 when we delete the experimental API only. The rest of the packages should be backward compatible according to ongoing discussions as we have no decision to delete them. The rest of the packages should be backwards compatible as we have no decision to delete or drop them

**Comment by ryw** [comment]
thanks for the detail @mik-laj - makes more sense.

if its possible, I think it'd be nice if all the code that we're keeping is moved into the `/airflow/api` directory and all the code that we're deprecating gets moved to `/airflow/api_deprecated` directory so it's easier to reason about the stable API - and read code related to it.

but if this would be painful in any way, we can just close this issue :)

**Comment by eladkal** [comment]
I think there are no further tasks on this issue
can be closed?
