### ISSUE TITLE
Dag in existing persistent volume claim not registering 

### ISSUE THREAD

**Issue by aimran-adroll** [apache/airflow#10574]
**Apache Airflow version**: v1.10.10 (server) / master for chart

**Kubernetes version (if you are using kubernetes)**: 1.18.6 (client) / v1.17.9-eks-4c6976

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Dag in existing `persistent` volume claim is not showing up

I am a complete beginner with airflow. I am using the chart from the repo and an official image (see reproduce below)

Trying to understand why the asymmetry between the two files:

1. chart/templates/scheduler/scheduler-deployment.yaml 
2. chart/templates/webserver/webserver-deployment.yaml

File (2) has a logic around `persistence.enabled` for the volumeMount while (1) does not (as of master). 

If I use the following patch, it seems to register my dags ✅  

```
diff --git a/chart/templates/scheduler/scheduler-deployment.yaml b/chart/templates/scheduler/scheduler-deployment.yaml
index 933155687..1c48ef722 100644
--- a/chart/templates/scheduler/scheduler-deployment.yaml
+++ b/chart/templates/scheduler/scheduler-deployment.yaml
@@ -145,7 +145,7 @@ spec:
               subPath: airflow_local_settings.py
               readOnly: true
 {{- end }}
-{{- if .Values.dags.gitSync.enabled }}
+{{- if or .Values.dags.gitSync.enabled .Values.dags.persistence.enabled }}
             - name: dags
               mountPath: {{ template "airflow_dags_mount_path" . }}
         {{- include "git_sync_container" . | indent 8 }}
```

**What you expected to happen**: 
I would expect the pvc to be mounted along with my dags.  At first I assumed there is some fancy back-n-forth happening between webserver and scheduler. But I waited and no Dags showed up in the UI.

**How to reproduce it**:

## install helm chart from apache/airflow
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm dep update 
```

## install release
```
helm install airflow . --namespace airflow-dev \
--set defaultAirflowTag=v1-10-test-python3.7 \
--set dags.persistence.enabled=true  \
--set dags.persistence.existingClaim=airflow-dag-pvc \   
--set dags.gitSync.enabled=false
```

**Anything else we need to know**:

**Comment by aimran-adroll** [comment]
#10630 may be the fix. Have to test it though

**Comment by eladkal** [comment]
@aimran-adroll is this still an issue?
