### ISSUE TITLE
Confusing parameter

### ISSUE THREAD

**Issue by amariucaitheodor** [apache/airflow#10575]
https://github.com/apache/airflow/blob/3a349624a20d3432dc75e337d6ffb1109a50e451/airflow/providers/amazon/aws/operators/athena.py#L49

What is the unit of measurement of time used here?

**Comment by coopergillan** [comment]
I'm almost certain that is seconds. That would be a good change for the docstring.

**Comment by theodor1289** [comment]
Just checked and it's [simply using](https://github.com/apache/airflow/blob/3a349624a20d3432dc75e337d6ffb1109a50e451/airflow/providers/amazon/aws/hooks/athena.py#L229) the Python method sleep() which, in turn, [uses seconds](https://docs.python.org/3/library/time.html#time.sleep). I'll make the change in the docstring then.
