### ISSUE TITLE
Cannot trigger_dag for specific date

### ISSUE THREAD

**Issue by rdavison** [apache/airflow#1058]
I noticed it's hard coded as `datetime.now()` in cli.py, I think we should be able to specify the execution date for this option.

**Comment by r39132** [comment]
AFAIK, that's not the intended use-case of trigger_dag. The date it runs is the datetime it was triggered. If you want to pass specific parameters to it, you can via the `--conf` flag, which accepts JSON payloads, as mentioned on https://www.linkedin.com/pulse/airflow-lesson-1-triggerdagrunoperator-siddharth-anand?trk=pulse_spock-articles

If you simply want to run specific dates in the past for a DAG but don't want to actually run the DAG, create a DAG with a non-None or non-once schedule, disable it (so the scheduler won't run it automatically), and trigger backfills for particular dates. Essentially, the `clear` & `backfill` (together) mechanism is the one you may want to use when executing date-specific fills.

**Comment by r39132** [comment]
@mistercrunch can also weigh in

**Comment by mistercrunch** [comment]
@r39132 is right, `trigger_dag` is intended for on-demand DAGs as opposed to on-schedule DAGs. 

I can see how this can be confusing as there's no way to alter the DagRuns' state or create new ones from the CLI, only in the UI at the moment.

**Comment by r39132** [comment]
Closing for now. Reach out to us on gitter if you need more context and there is some use-case not covered by other CLI commands.
