### ISSUE TITLE
Add support for impersonation in GKEStartPodOperator, DataflowCreateJavaJobOperator and DataflowCreatePythonJobOperator

### ISSUE THREAD

**Issue by olchas** [apache/airflow#10596]
**Description**

`GKEStartPodOperator`, `DataflowCreateJavaJobOperator` and `DataflowCreatePythonJobOperator` do not support [direct impersonation of a service account in Google services](https://cloud.google.com/iam/docs/understanding-service-accounts#directly_impersonating_a_service_account).

**Use case / motivation**

`GKEStartPodOperator`, `DataflowCreateJavaJobOperator` and `DataflowCreatePythonJobOperator`, in contrary to other Google operators, do not use `Credentials` class for authentication, so they require individual approach to support direct impersonation in them.

In case of `GKEStartPodOperator` it seems it should suffice to add [`--impersonate-service-account`](https://cloud.google.com/sdk/gcloud/reference#--impersonate-service-account) to the [`gcloud container clusters get-credentials` command](https://github.com/apache/airflow/blob/bb3e45c2509bba760f720d60b008f2f71e1024e2/airflow/providers/google/cloud/operators/kubernetes_engine.py#L324). However, this way we will not be able to use chain of service accounts, like in the rest of Google operators.

In case of `DataflowCreateJavaJobOperator` and `DataflowCreatePythonJobOperator`, some changes in [`provide_gcp_credential_file_as_context`](https://github.com/apache/airflow/blob/master/airflow/providers/google/common/hooks/base_google.py#L396) will probably be needed.

**Related Issues**

https://github.com/apache/airflow/issues/8803

**Comment by mik-laj** [comment]
@rajatsri28  Do you have experience with Google Cloud? This task is trivial from an Airflow perspective, but requires above-average knowledge of the Google Cloud platform. I don't want you to have a bad experience after contributing to this project.

**Comment by rajatsri28** [comment]
Hi @mik-laj , Yes I have some experience with Google Cloud. At Twitter, we migrated from on-premise offering to provide Airflow on GKE (GCP) so I can somewhat relate to this issue as well.

**Comment by mik-laj** [comment]
@rajatsri28 Awesome! I assigned you to this ticket.

**Comment by mik-laj** [comment]
@rajatsri28  I think support for a single service account is sufficient in most cases. `gcloud config set auth/impersonate_service_account`  The gcloud command should work for all operators that use gcloud, so all you have to do is add account name forwarding in `airflow.providers.google.common.hooks.base_google.GoogleBaseHook.provide_authorized_gcloud` method.

`gcloud config set auth/impersonate_service_account` command and `--impersonate-service-account` argument behave similarly, but I think the first method will be simpler to implement.  I am not sure about this and think it is worth checking for all the gcloud supported authentication methods.

**Comment by shahar1** [comment]
@eladkal Please assign me

**Comment by shahar1** [comment]
@eladkal Please reassign, I unassigned by accident

**Comment by shahar1** [comment]
I've been trying to resolve this issue, and it seems that:
- `GKEStartPodOperator` currently supports an impersonation chain. (#19518)
- `DataflowCreateJavaJobOperator` and `DataflowCreatePythonJobOperator` are both deprecated in favor of `BeamRunPythonPipelineOperator`. (#12814)
- `BeamRunPythonPipelineOperator` supports the impersonation chain by passing `DataflowConfiguration` that includes `impersonation_chain` parameter. (#14094)

Therefore, this issue could be closed as it is already resolved.
