### ISSUE TITLE
Let users add custom metadata to the dag runs

### ISSUE THREAD

**Issue by jpays** [apache/airflow#10603]
**Description**

Currently there is no way to add custom metadata to a dag run, this would be an interesting enhancement.

**Use case / motivation**

This could have multiple use cases, here are some examples :

* Let's say you have a dag that ends up loading data in a table, the number of lines loaded could be added as a custom metadata on the dag run
* You have a dag that run multiple times every day, and that can process serveral perimeters of data depending on external factors, the list of perimeters processed could be added as a custom metadata on the dag run
* ...

The main goal is to provide some easy-to-use feedback about what a dagrun has done. This could afterwards be displayed on the dagrun UI, but I think it is mainly relevant to use in charts, SQL queries or various dataviz products such has Tableau that could be plugged on the airflow DB.

Ultimately, this data could be made available in the new API.

I don't know if there is a way to achieve this differently.
I can help adding this feature if necessary.

**Related Issues**

Could not find.

Thanks &  Regards.

**Comment by sreenath-kamath** [comment]
Can't this be achieved using the configuration passed during the dag_runs

**Comment by jpays** [comment]
You mean using the "conf" attribute of the DagRun ?

That would indeed be an option I suppose, but :

* `conf` is stored as `PickleType`, which is good if you need to pass any kind of Python object to the DagRun, but not suitable at all for external use such as SQL Query
* from my understanding,  `conf` should be considered as the input values for the DagRun, and as such should not be tampered with during dag execution. Of course you can do it but input values should probably be immutable and that kind of metadata would be better off stored another place.

**Comment by bdsoha** [comment]
@jpays I think a variant of this was implemented #26457. Can this be closed?

**Comment by uranusjr** [comment]
Done in #26547.

**Comment by bdsoha** [comment]
> Done in #26547.

@uranusjr I think the PR was #26457...?
