### ISSUE TITLE
Upstream failed whereas Upstream is alright

### ISSUE THREAD

**Issue by nalepae** [apache/airflow#10604]
**Apache Airflow version**: 1.10.3 on Google Cloud Composer (so 1.10.3-composer)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): (Managed by Google Cloud Composer)

**Environment**:

- **Cloud provider or hardware configuration**: Google Cloud Composer
- **OS** (e.g. from /etc/os-release): (Managed by Google Cloud Composer)
- **Kernel** (e.g. `uname -a`): (Managed by Google Cloud Composer)
- **Install tools**: N/A
- **Others**: Managed by Google Cloud Composer

**What happened**:

Sometimes, some steps do not run because of "Failed Upstream" (orange color) whereas upstream is alright (green color).

_Examples:_
![image](https://user-images.githubusercontent.com/4943830/91458610-04ae1280-e886-11ea-8b16-d6bb82b46ce8.png)

or

![image](https://user-images.githubusercontent.com/4943830/91458622-08da3000-e886-11ea-9dfa-72dc35492b61.png)

_Additional informations:_
- All steps except `wait_for_dump`, `recort_start`, `join` and `record_end` are Kubernetes Pod Operator.
- Re running by hand "orange" steps always solve the issue.

**What you expected to happen**:

If all upstream tasks of a given task are green, the given task should run, and not be in state "Failed Uptream".

**How to reproduce it**:
Run some DAGs (no need to be a specific DAG) on Airflow (via Google Cloud Composer), and the issue will happen randomly.

**Anything else we need to know**:
I cannot reproduce this bug on my local version on Airflow, on MacOS (after about 10 trials) using the **Kubernetes single-node cluster** available in **Docker for mac**.

I'm not 100% sure this issue come from **Airflow** itself, but may also come from **Google Cloud Composer**.

**Comment by adambayrami** [comment]
Seeing the same issue on airflow 1.10.5. We recently increased from about 30 dags and 200-300 tasks to about 80 dags and over 1k task pretty quickly then started seeing this issue. 

Using reddis with a celery executor. Don't currently have access to scheduler logs but that's where I'd like to start investigating.

**Comment by pquentin** [comment]
I work with @nalepae, and we continue to see this a few times per week.

**Comment by adambayrami** [comment]
Did you all learn anything new or do you still have the issue? @pquentin @nalepae

**Comment by nalepae** [comment]
@adambayrami we still have the issue. What about you?

**Comment by nalepae** [comment]
Fixed when upgrading to **Airflow 1.10.10**

**Comment by shubhamg931** [comment]
facing this again with airflow 2.1.3

**Comment by LeandroDoldan** [comment]
Facing it as well on Airflow 2.1.4
