### ISSUE TITLE
Apache Airflow 1.10 Issue

### ISSUE THREAD

**Issue by blessedwithsins** [apache/airflow#10601]
Hi Team,

I'm reporting this issue on behalf of our customer. Customer is using AKS Cluster with version 1.15.7, where he is facing issue. 

He is spinning Airflow Worker Pods in AKS Cluster which spawn another set of Application Pods for log streaming. However, after doing it once, pod is going into completed state and Worker Pod is unable to retrieve this information. 

Can someone guide me in right direction here?

Regards,
Piyush Gaur

**Comment by blessedwithsins** [comment]
May I have an update on this issue?

**Comment by mik-laj** [comment]
Please ask on Slack channel. [![Slack Status](https://img.shields.io/badge/slack-join_chat-white.svg?logo=slack&style=social)](https://s.apache.org/airflow-slack)
We don't provide support via Github Issues. Github Issues should only have confirmed bugs, not help requests.
