### ISSUE TITLE
Use private docker repository with K8S operator and XCOM sidecar container

### ISSUE THREAD

**Issue by mickaelgervais** [apache/airflow#10605]
**Use private docker repository with K8S operator and XCOM sidecar container**

An extra parameter to KubernetesPodOperator: docker_repository, this allows to specify the repository where the sidecar container is located

**My company force docker proxy usage for K8S**

I need to use my company docker repository, images that are not proxifed by the company docker repository are not allowed

**Comment by potiuk** [comment]
would you like to add this feature @mickaelgervais ? I am happy to review it

**Comment by mickaelgervais** [comment]
Hi @potiuk ,

I've submitted a PR, do nopt hesitate to add comment or if I've implemented this badly. 
The sidecar container declaration is low level in K8S operator so I've tried to not add complexity.

Regards

**Comment by zoomzoomTnT** [comment]
Hi @mickaelgervais 

I have left a comment in your pr for adding a explicit image tag, we have something like private-registry/alpine:3.10, and would like to add a variable for image tags.

**Comment by Shivarp1** [comment]
A work around would be add this code block in the /home/airflow/airflow_local_settings.py
PodDefaults.SIDECAR_CONTAINER = k8s.V1Container(
    name=PodDefaults.SIDECAR_CONTAINER_NAME,
    command=['sh', '-c', PodDefaults.XCOM_CMD],
    image='<local private repository image>',
    volume_mounts=[PodDefaults.VOLUME_MOUNT],
    resources=k8s.V1ResourceRequirements(
        requests={
            "cpu": "10m",
            "memory":"32Mi"
        },
        limits={
            "cpu": "0.25",
            "memory":"32Mi"
        }
    ),
)

**Comment by fritzb** [comment]
Docker Inc started image pull rate limiting around October 30th 2020. As a result, all KubernetesPodPerator tasks with XCOM started to fail in large deployment. Can we backport this fix to Airflow 1.10 branch?

Based on the severity of the failure, the bug priority should be raised higher.

`  - image: alpine
    imageID: ""
    lastState: {}
    name: airflow-xcom-sidecar
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'rpc error: code = Unknown desc = Error response from daemon: toomanyrequests:
          You have reached your pull rate limit. You may increase the limit by authenticating
          and upgrading: https://www.docker.com/increase-rate-limit'
        reason: ErrImagePull`

**Comment by evanhlavaty** [comment]
Is there a reason why this has not been implemented yet?

**Comment by potiuk** [comment]
> Is there a reason why this has not been implemented yet?

It was waiting for someone like you to take that over and complete it possibly? Airflow has > 1700 contributors and you can become one if you want some features to be implemented faster :)

**Comment by potiuk** [comment]
Feel free to take it over and contribute! we even have Contributors workshops  (3 of them till the end of the year). On Airflow Slack there is a #contributors-workshop dedicated channel for it! Anyone is welcome!

**Comment by zoomzoomTnT** [comment]
sure, I think it's covered in a different feature request, let me find out
and update the comments.

Can you let me know when are the workshops and how do I attend them?

Thanks,
Zhicong

**Comment by fritzb** [comment]
Here is the workaround (tested with Airflow 2.1.4) if you are using airflow helm chart:


values.yaml:

```
airflowLocalSettings: |
  from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
  PodDefaults.SIDECAR_CONTAINER.image = private.registry.com/alpine
```

**Comment by potiuk** [comment]
> Can you let me know when are the workshops and how do I attend them?

Just join the #contributors-workshop channel - we announce the workshops there.

**Comment by ZackingIt** [comment]
> > airflowLocalSettings: |
> > from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
> > PodDefaults.SIDECAR_CONTAINER.image = private.registry.com/alpine
> 
> @fritzb
> 
> I tried something like this in the past and it didnt work. However this worked for me in 2.2.0, so thank you!

I was able to get my xcom to use a non-DockerHub repo also by creating a `airflow_local_settings.py` file in the root/config folder, due to this yaml:
https://github.com/apache/airflow/blob/73044af1c6908d1b075bd0127bc56c1db82b564b/chart/templates/_helpers.yaml#L416.

I then simply overwrote with the code:
```
from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
PodDefaults.SIDECAR_CONTAINER.image = "docker.very.private.repo.net/alpine:3.10"
```
You can verify the custom `airflow_local_settings.py` file is loaded because any code written in that file will be executed by teach task instance, i.e., those are the logs to check.  That's really the only annoying/hard part, is just knowing whether your instance is actually executing/including the local_settings file.

**Comment by dzungdev** [comment]
Hi @ZackingIt , could I know how do you overrote the code? Do you go to pod and change the  airflow_local_settings.py file in root/config folder or you add it in values.yaml file as below:
`airflow
    localSettings:
    ## the full content of the `airflow_local_settings.py` file (as a string)
    stringOverride: |
      # use a custom `xcom_sidecar` image for KubernetesPodOperator()
      from airflow.kubernetes.pod_generator import PodDefaults
      PodDefaults.SIDECAR_CONTAINER.image = "private_artifactory/alpine"`

`from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
PodDefaults.SIDECAR_CONTAINER.image = "docker.very.private.repo.net/alpine:3.10"`

**Comment by ZackingIt** [comment]
@dzungdev 
 I created an actual file, I did *not* overwrite a variable in the `values.yaml` i.e., part of my Docker build involves:
`cp /airflow-config/config/airflow_local_settings.py ${AIRFLOW_HOME}/config/airflow_local_settings.py`

When I say "due to this yaml" I mean that that yaml tells us that this is already a location,`${AIRFLOW_HOME}/config` is already one of the paths being read by default, as I did not need to explicitly set a PYTHONPATH environment variable to read that location.

**Comment by lshw42** [comment]
@ZackingIt 
Where exactly did you put the configuration? When I put the `PodDefaults.SIDECAR_CONTAINER.image` (as mentioned several times here and everywhere else) into the `values.yaml` it is just used by the helm chart. But I can't figure out where to put the `airflow_local_settings.py` to configure the worker pod image pulled by the `KubernetesExecutor`. I even can't build a Docker image with Airflow 2.1.4 which is configured as needed.

My current Dockerfile looks like the following:
```Dockerfile
FROM apache/airflow:2.1.4-python3.8@sha256:ae98e5e9eba596e24bce820e5f3a109274b82cd347bb9fdfca1e9d3f0dda4bb0

COPY --chown=airflow:root airflow_local_settings.py /opt/airflow/config/airflow_local_settings.py

USER airflow
```
But as soon as the `KubernetesExecutor` is pulling my image (because I configured it in the `values.yaml`) it runs into the Docker pull limit very easy, because I can't configure the image correctly.

**Comment by alexandrebunn** [comment]
We are facing the same issue, but in our case the error is related the absent of an option to define resources to the sidecar container. Our kubernetes cluster has this resource enforcement active and them even trying to set the resouces by airflow_local_settings.py, pod_template_file, it sounds like the code is ignoring these options.

**Comment by robkuehl** [comment]
> Hi @ZackingIt , could I know how do you overrote the code? Do you go to pod and change the airflow_local_settings.py file in root/config folder or you add it in values.yaml file as below:
> 
> Your code
> 
> ```
> from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
> PodDefaults.SIDECAR_CONTAINER.image = "docker.very.private.repo.net/alpine:3.10"
> ```
> 
> in values.yaml
> 
> ```
> airflow
>     localSettings:
>       ## the full content of the `airflow_local_settings.py` file (as a string)
>       stringOverride: |
>         # use a custom `xcom_sidecar` image for KubernetesPodOperator()
>         from airflow.kubernetes.pod_generator import PodDefaults
>         PodDefaults.SIDECAR_CONTAINER.image = "private_artifactory/alpine"
> ```

But where do I provide the Image Pull Secret for the private registry? So far I can't find anything and would really appreciate advice.

**Comment by robkuehl** [comment]
> Here is the workaround (tested with Airflow 2.1.4) if you are using airflow helm chart:
> 
> values.yaml:
> 
> ```
> airflowLocalSettings: |
>   from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
>   PodDefaults.SIDECAR_CONTAINER.image = private.registry.com/alpine
> ```

But where do I provide the Image Pull Secret for the private registry in the values.yaml? So far I can't find anything and would really appreciate advice @fritzb?

**Comment by raphaelauv** [comment]
you can setup the xcom container image in the kubernetes connection ( airflow connection )

![image](https://github.com/apache/airflow/assets/10202690/ba66a1b9-b0bc-46ef-a9d8-ef115d6f6ea5)

**Comment by marlena-hammond** [comment]
Incase anyone else is encountering this issue still, you can update the image value without have to recreate the whole V1Container. I put this in my custom EKSPodOperator.

```
if PodDefaults.SIDECAR_CONTAINER.image != "<your-custom-image>":
    PodDefaults.SIDECAR_CONTAINER.image = "<your-custom-image>"
```

**Comment by BjornvandeSandRWS** [comment]
> > Here is the workaround (tested with Airflow 2.1.4) if you are using airflow helm chart:
> > values.yaml:
> > ```
> > airflowLocalSettings: |
> >   from airflow.providers.cncf.kubernetes.utils.xcom_sidecar import PodDefaults
> >   PodDefaults.SIDECAR_CONTAINER.image = private.registry.com/alpine
> > ```
> 
> But where do I provide the Image Pull Secret for the private registry in the values.yaml? So far I can't find anything and would really appreciate advice [@fritzb](https://github.com/fritzb)?

Did you ever find an answer to this? Iḿ still struggling to use an image from our private repository for the sidecar.

**Comment by spartan-haiduong** [comment]
Hi, how exactly do we use this new feature?
I have added `sidecar_container_image` to the initialization of KubernetesPodOperator but got Error
```
TypeError: KubernetesPodOperator got an unexpected keyword argument 'sidecar_container_image'
```
