### ISSUE TITLE
Document subdags

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#1061]
I have no idea what subdags are. The documentation on the operator doesn't say much. The API reference has nothing. Searching Google shows nothing.

**Comment by nicktrav** [comment]
I can take this one on. I'm working pretty extensively with SubDags for some of our pipelines.

**Comment by mistercrunch** [comment]
I think it'd fit nicely in the "Concepts" section

**Comment by r39132** [comment]
It would be nice if an example were also added to the example DAGs..

**Comment by r39132** [comment]
@nicktrav :clap:

**Comment by mistercrunch** [comment]
It's out! http://pythonhosted.org/airflow/concepts.html#subdags
:clapper:
