### ISSUE TITLE
modules provided and imported by packaged DAGs can get mixed up

### ISSUE THREAD

**Issue by cchepelov** [apache/airflow#10616]
**Apache Airflow version**: 1.10.1, 1.10.10, code identical in 1.10.12 (reproduced with unit tests)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: on-prem
- **OS** (e.g. from /etc/os-release):  CentOS 7
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-957.1.3.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:

Our DAG require some proprietary support library, which evolves from time to time. 
The typical structure of our dag zips ("dagpacks") is the following:

dag-a.zip:
* dag-a.py
* support_lib/
   * __init__.py
   * constants.py
   * functions.py

dag-b.zip:
* dag-b.py
* support_lib/
   * __init__.py
   * constants.py
   * functions.py

While over time, all dagpacks will tend to use the same version of the support lib, the release cycles of various DAGs are decorrelated. 
What happens is that sometimes, and apparently randomly, dag-a will receive dag-b.zip's support_lib instead of its own.

After careful analysis of the logs and the UI, it may even happen that the situation visible in the UI can be different in the scheduler process (i.e. you can have dag-a receiving dag-b's support lib in the Web UI, while the scheduler might behave as if dag-b received dag-a's support library instead !)

**What you expected to happen**:
When a zipped DAG imports a module it provides within the same zip file, it receives that module and nothing else, _ever_. Distinct DAG zips can coexist with distinct versions.

**How to reproduce it**:
Unit test provided in the forthcoming PR

As it happens, the following structure *seems* fine:
dag-a.zip:
* dag-a.py
* support_lib.py

dag-b.zip:
* dag-b.py
* support_lib.py

but migrating back to this would require us to merge back all submodules of our support library into a single file.

**Anything else we need to know**:

This problem seems to happen 100% of the time on our systems. It got unnoticed at first, as the scope of changes within the support_lib was initially timid, but it no longer is.

**Comment by eladkal** [comment]
@cchepelov Now that Airflow 2.0 is out & following the correspondence in https://github.com/apache/airflow/pull/10617. Can you verify if it's still an issue in Airflow 2.0?
