### ISSUE TITLE
Use Dingding webhook with extra parameters, like proxy; 发送钉钉webhook添加其他参数 如:代理

### ISSUE THREAD

**Issue by pyxin** [apache/airflow#10624]
Hi 能否将配置中的Extra, 在钉钉 send 时使用?

@zhongjiajie 

具体文件如下
airflow/providers/dingding/hooks/dingding.py
第120 行

```python
# 添加 extra_options
conn = self.get_connection(self.http_conn_id)
extra_options = conn.extra_options

self.log.info('Sending Dingding type %s message %s', self.message_type, data)
resp = self.run(
            endpoint=self._get_endpoint(), data=data, headers={'Content-Type': 'application/json'},

extra_options=extra_options

        )

```

**Comment by XD-DENG** [comment]
Hi @pyxin please submit the issue with English so the folks from the community can better understand it? Thanks

Hi @pyxin 建议你把issue内容翻译为英文，不然社区大部分成员无法参与讨论或者帮助你解决问题。谢谢

**Comment by mik-laj** [comment]
Could I have more information about this issue in English, please?

**Comment by XD-DENG** [comment]
Hi @mik-laj , I have requested for an English description earlier, while no response from the issue author. I suggest to leave it, @zhongjiajie have assigned this issue to himself anyway.

For the time being, I will update the Issue subject with English (@pyxin , please check my comment above. Even if using a translator software, it will be better than sending an Issue that most folks here don't understand).

For future-wise, I suggest that we close issues if no response after we request for contents/description in English. Languages are equal definitely (like I'm proud of speaking Chinese), but as a community, participants should try to talk in the language more folks can understand.

**Comment by mik-laj** [comment]
I close due to inactivity of the original author after 72 hours.
