### ISSUE TITLE
Persistent dag option in helm chart - no dags in scheduler

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#10623]
I am using helm chart from this repo. I set up options like:
```
    --set dags.persistence.enabled=true \
    --set dags.persistence.size=10Gi \
    --set dags.persistence.existingClaim=dags-airflow \
```
After that, and prepared s3-sync process, dags landed only in worker and web server. Due to this fact, I cannot see them in UI.
I bet persistence dag option doesn't work properly

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/10630
