### ISSUE TITLE
DAG description/documentation that's viewable in the UI

### ISSUE THREAD

**Issue by battlesnake** [apache/airflow#10626]
**Description**

I would like a way to (optionally) provide DAG description text block when creating a DAG, and have this text shown in Airflow UI for tree/graph view, and in the Trigger Dag screen.

Also show the per-dag_run config in the UI.

**Use case / motivation**

A brief description of the DAG (and possibly, its owner / external dependencies) will be helpful for users, to understand what the DAG is for and who to DAG-specific report issues to.

Given that we can now specify a JSON config for `context.dag_run.conf` via the Trigger Dag prompt, showing documentation there would also help the user to know what they can configure via that field.

Being able to see that dag_run config for some run in the UI will make it easier for a user to understand why the DAG ran the way that it did (e.g. some parts skipped due to config), and also provides them with a template to copy+paste+edit if they want to do a run with config same as / similar to the previous one.

**Related Issues**

None that I know of

**Comment by battlesnake** [comment]
Anything I should take into consideration if I implement this myself and send a PR?

**Comment by coopergillan** [comment]
I thought this was already available either the `dag_description` attribute in the `DAG` object. Is this talking about something else?

**Comment by mik-laj** [comment]
Here is docs about DAG.doc: https://airflow.readthedocs.io/en/latest/concepts.html#documentation-notes

**Comment by battlesnake** [comment]
:facepalm: Thanks, some how I've not noticed that previously.

**Comment by battlesnake** [comment]
I've just tried this now and I notice that the description is displayed in one line to the right of the DAG title, and is truncated when it gets long.

Would it be ok to have a separate longer description/documentation string that appears in the "Trigger DAG" page, which can give more detailed information, especially regarding the dag_run config?
