### ISSUE TITLE
AWS SecretsManager as a hook

### ISSUE THREAD

**Issue by dyon78** [apache/airflow#10645]
**Description**

Hook for interaction with AWS SecretsManager

**Use case / motivation**

Simplify interaction with SecretsManager

**Comment by dhegberg** [comment]
@dyon78 

Is there any outstanding work to be picked up on this? 

 It looks like you've added the hook: https://github.com/apache/airflow/blob/master/airflow/providers/amazon/aws/hooks/secrets_manager.py

**Comment by dyon78** [comment]
@dhegberg yes, it's implemented, let me close this.
