### ISSUE TITLE
execution_timeout hangs in running state

### ISSUE THREAD

**Issue by aewald2** [apache/airflow#10661]
**Apache Airflow version**: 1.10.9

**What happened**: We set the execution_timeout set to 13 minutes, tasks will log that they are timing out at 13 minutes but are left hanging in run state.

**What you expected to happen**: if it goes beyond max time set it will raise and fail.

**How to reproduce it**: example code:

default_args = {
    'owner': 'owner',
    'description': 'description',
    'depend_on_past': False,
    'start_date': datetime(2020, 3, 11, tzinfo=execution_tz),
    'retries': 1,
    'retry_delay': timedelta(minutes=2),
    'execution_timeout': timedelta(minutes=13)
}

dag = DAG(
    'task_name',
    default_args=default_args,
    schedule_interval='8/15 * * * *',
    catchup=False,
    dagrun_timeout=timedelta(minutes=14)
)

**Comment by eladkal** [comment]
Can you please test if the issue happens on latest version (2.1.3)/ main branch?
