### ISSUE TITLE
remove airflow-pr tool 

### ISSUE THREAD

**Issue by ryw** [apache/airflow#10674]
`https://github.com/astronomer/airflow/blob/master/dev/README.md` mentions `airflow-pr` tool that works with Jira - I'd suggest we delete that code and tool. It also allows us to drop `PyGithub` and `chardet` requirement, which are category-x LGPL licensed. I'm happy to attempt the PR if you all agree.

@kaxil @ashb if other sections of the doc are outdated too (related to releases) then we should update that too.

**Comment by kaxil** [comment]
PyGithub is only sued for release management and not included in the source code (actually the entire "dev" folder for that matter isn't included) so licensing-wise it won't be a problem.

But yes the "dev" directory does need some cleanup, will do it in the coming days, thanks for creating the issue

**Comment by ryw** [comment]
FYI - I just downloaded https://github.com/apache/airflow/archive/1.10.12.zip from https://github.com/apache/airflow/releases/tag/1.10.12 and the `/dev` directory is present.

**Comment by potiuk** [comment]
Hey @Ry, goad that you arę looking at its but i'd really recommend readig the ASF dość before, to understand the 'legal' content we have as ASF project.


See the  http://www.apache.org/legal/release-policy.html#what-must-every-release-contain

There is only one 'official' release for ASF projects - and it has to be placed at downloads.apache.org. It has to be cryptographically signed by the release manager and placed in the Apache svn nexr to the file, its checksum and aarchived by ASF on case of aby Legal disputes. Each release has to have src  'tar.gz' file and this is the only concern (and most important one) of PMC members when voting - to make sure that whatever is in this package is good from the licencing point of view, and that whatever is there, allows to rebuild the resulting software by the uses with the use of appropriate platform and tools'

 Other ways of retrieving the sources is just 'convenience' method. Tag in GitHub is only a convenience way to mark that those are the git project sources that were used to generate the 'official' source package. So what is in the tag is not a concern when it comes to releasing the software, but what matters most is what goes into the official package. This is the only obligation that ASF puts on the PMC who's most important job is to make sure that those rules are followed.

I heartily recommend reading those policies if you are looking at the potential licencing issues. Those are  the most useful documents in that matter I ever saw. They are short, to the pointy, they stress that this od od uttermost importance that those rules arę followed by ASF projects, they have super useful FAQ that explain the nuances - Luke what od release and what is not.


Note that the ASF provides Legal idemnification for the PMCs  providing that we follow the rules. When becoming a PMC i very carefully read and understanding the ramifications  and I recommend anyone being PMC as binding  '+1' on the release means that we checked all those  (i did). 

I also recently added this guide for PMCs voting for release that explains the checks that PMCs should make:

https://github.com/apache/airflow/tree/master/dev

**Comment by ryw** [comment]
Thanks Jarek - learning more each day :) took an excerpt of your comment to add to project README (https://github.com/apache/airflow/pull/10678), as I wasn't aware of the downloads.apache.org source and I'm sure many other users aren't aware of it either.

**Comment by kaxil** [comment]
Yes, https://github.com/apache/airflow/releases/tag/1.10.12 & `.zip` just contains everything in the repo while we control what goes into the actual release (the .whl and tar.gz and the source uploaded at downloads.apache.org or dist.apache.org) using the [MANIFEST.in](https://github.com/apache/airflow/blob/master/MANIFEST.in) and [package_data](https://github.com/apache/airflow/blob/70f05ac6775152d856d212f845e9561282232844/setup.py#L752-L758) :

```
The official source release:
https://dist.apache.org/repos/dist/release/airflow/1.10.12
https://downloads.apache.org/airflow/1.10.12/

The PyPI package:
https://pypi.org/project/apache-airflow/1.10.12/

Docs: https://airflow.readthedocs.io/en/1.10.12/
```

**Comment by kaxil** [comment]
Btw users would still not have any dev dependencies installed even if they use the tag as we don't have it in setup.py

**Comment by ryw** [comment]
I understand that we're safe on dev requirements not being installed unless user does so explicitly and intentionally. 

I've put in [a PR](https://github.com/apache/airflow/pull/10675) to delete the `airflow-pr` tool which seems unnecessary since we've moved away from Jira, we can discuss the merits of that within that PR, so closing this issue.
