### ISSUE TITLE
dag/task pod is not getting created in kubernetes cluster

### ISSUE THREAD

**Issue by prasanthbangs2016** [apache/airflow#10688]
i have used airflow version 1.10.10.

airflow has got deployed successfully with kuberntes(like adding executor "kubernetesexecutor)... i see web and scheduler pods are running as expected.... the issue i have is, the moment i enable the dag from web UI it is not running(meaning, not getting into scheduled/queued state) and corresponding dag/task pod is also not getting created.

could you throw some light.

**Comment by prasanthbangs2016** [comment]
Apache Airflow version: 1.10.10


Environment:

Cloud provider or hardware configuration: AWS EKS

**Kubernetes version : v1.17 
**Kubectl version    : v1.16.6-beta.0


What happened:

airflow has got deployed successfully with kuberntes(like adding executor "kubernetesexecutor)... i see web and scheduler pods are running as expected.... the issue i have is, the moment i enable the dag from web UI it is not running(meaning, not getting into scheduled/queued state) and corresponding dag/task pod is also not getting created.

Order of Kubenetes yaml files

Service account
Cluster role
cluster role-binding
pvc
configmap
service
scheduler
webserver

**Comment by kaxil** [comment]
This looks like a setup issue with your Kubernetes Cluster. Please create a post in https://github.com/apache/airflow/discussions / StackOverflow or Airflow Slack where we can help out

**Comment by himabindu07** [comment]
Hi I verified this issues using 2.0.1, unable to reproduceble and can you please try with 2.0.1.
