### ISSUE TITLE
Not able to use gzip flag in S3Hook

### ISSUE THREAD

**Issue by yvadalia** [apache/airflow#10693]
**Apache Airflow version**:  v1.10.12

**What happened**:  when using gzip param, it is looking for _name_ in _filename_ string

Error : `AttributeError: 'str' object has no attribute 'name'`

**Anything else we need to know**:

Its should be an easy fix in S3Hook at - 
https://github.com/apache/airflow/blob/827a717fecc675b4d58fa202be003dee8e423632/airflow/hooks/S3_hook.py#L364

**Comment by XD-DENG** [comment]
Thanks for sharing the issue.

This feature was added in #7680, and the author had realised this bug later and had fixed it in #8571. But the fix was missed in the cherry-picking during the release. 

CC @kaxil @ashb  , let's include #8571 in the next release?

**Comment by eladkal** [comment]
Both PRs are included in the backport release of AWS
https://github.com/apache/airflow/blob/master/airflow/providers/amazon/PROVIDERS_CHANGES_2020.06.24.md

So no need to wait for 1.10.13

**Comment by XD-DENG** [comment]
Cool, thanks @eladkal for sharing this.

@yvadalia , please refer to the link @eladkal shared + https://github.com/apache/airflow#backport-packages for using the backport, before the fix is included in 1.10.13.

**Comment by eladkal** [comment]
Closed as no further action needed.
