### ISSUE TITLE
turning off dag causes mysql error

### ISSUE THREAD

**Issue by audubon** [apache/airflow#1071]
using mysql ,pymysql with latest airflow 
turning off job causes error

ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[(\'is_paused\', u\'false\'), (\'dag_id\', u\'example_bash_operator\')]'')' at line 1") [SQL: u'INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%(dttm)s, %(dag_id)s, %(task_id)s, %(event)s, %(execution_date)s, %(owner)s, %(extra)s)'] [parameters: {'task_id': None, 'extra': "[('is_paused', u'false'), ('dag_id', u'example_bash_operator')]", 'execution_date': None, 'event': 'paused', 'owner': 'anonymous', 'dttm': datetime.datetime(2016, 2, 24, 15, 57, 35, 175912), 'dag_id': u'example_bash_operator'}]

**Comment by mistercrunch** [comment]
pymysql isn't supported, please use `mysqlclient`

**Comment by r39132** [comment]
Added to https://github.com/airbnb/airflow/wiki/Airflow-Common-Pitfalls
