### ISSUE TITLE
Vague logs when worker crashes due to out of memory (OOME)

### ISSUE THREAD

**Issue by akuzni2** [apache/airflow#10717]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.17

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS using EC2 as worker nodes.
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.8
- **Kernel** (e.g. `uname -a`): Linux x84_64 GNU
- **Install tools**: helm 
- **Others**:

**What happened**:
Vague log output from airflow workers when an OOME error occurs due to data-intensive tasks.  

Log only says:
`{local_task_job.py:78} ERROR - Received SIGTERM. Terminating subprocesses`

**What you expected to happen**:
There should be some additional information to indicate it was an out of memory error. The above log does nothing to help.

**How to reproduce it**:
Install Airflow, create a dag to load some big data in a pandas dataframe (could be anywhere. SQL/S3/file) and DAG will fail with vague logs.

**Anything else we need to know**:
no

How often does this problem occur? Once? Every time etc?
every time

**Comment by eladkal** [comment]
This issue is reported against older version of Airflow.
Please check against latest version. If needed we will reopen this issue.
