### ISSUE TITLE
DAG Run ID referencing wrong DAG Run when trying to view

### ISSUE THREAD

**Issue by prakshalj0512** [apache/airflow#10721]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): MacOS & Linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

*I have set timezone=America/Phoenix in airflow.cfg.*

When clicking on the DAG Run ID in the DAG list, it references the DAG run based on my timezone as opposed to the UTC one. Since all DAG Run IDs are comprised of UTC only, it ends up setting the Base Date to the wrong value and referencing the wrong DAG run.

**What you expected to happen**:

it should reference the correct DAG run.

*What do you think went wrong?*

When moving from DAG list to the individual DAG run view, it changes the UTC time to your timezone set in airflow.cfg and causes the mismatch.

**How to reproduce it**:

Set timezone to something other than UTC in airflow.cfg.
Create a normal DAG; schedule it to execute every 1 min. 
Click on the Schedule button on the individual DAG view to get the DAG list. 
Click on one of the entries to view the DAG run. You should notice it refers to the wrong one. 

Screenshot Reference:

<img width="1792" alt="Screen Shot 2020-09-02 at 3 18 00 PM" src="https://user-images.githubusercontent.com/32403237/92182942-cbcfe980-ee01-11ea-900c-3e41e1d3299a.png">
<img width="1792" alt="Screen Shot 2020-09-02 at 3 18 54 PM" src="https://user-images.githubusercontent.com/32403237/92182946-cd99ad00-ee01-11ea-86e0-cc365abb8476.png">

**Comment by kaxil** [comment]
Base date is not run_id. Base date just allows you to view all the runs from that base date in the "Run" dropdown next to it

**Comment by prakshalj0512** [comment]
@kaxil Correct...but the base date that is shown there will populate the "Run" dropdown, right? In this case, the base date being populated isn't accurate so it's showing up the wrong Run in the UI.

**Comment by kaxil** [comment]
Yeah that is correct, looks like a bug then

**Comment by v1lev** [comment]
Hi. I would like to work on this task

**Comment by vikramkoka** [comment]
> Hi, @prakshalj0512 , @eladkal , @kaxil ! I would like to work on this task

Assigned to you @v1lev

**Comment by v1lev** [comment]
@vikramkoka , hi, i don't want to work on this task anymore
