### ISSUE TITLE
KubernetesPodOperator with XCom enabled errors: 403 forbidden

### ISSUE THREAD

**Issue by Shivarp1** [apache/airflow#10722]
Apache Airflow version: 1.10.12
kubernetes Version: 10.0.1
OpenAPI spec version: v1.14.5
OS: Linux Red Hat 7.x

--- 

Enabling the `do_xcom=True` with default configuration parameters for pod throws the 403 forbidden error as below

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"xyz..\" is forbidden: failed quota: default: must specify requests.memory","reason":"Forbidden","details":{"name":"xyz..","kind":"pods"},"code":403}
```
---

**What you expected to happen**: Create the default side car object with alpine image and launch the pod

**What do you think went wrong?**
In airflow.kubernetes.pod_generator the PodDefaults.SIDECAR_CONTAINER's resources does not include requests memory and limits memory.cpu.  These are checked by the Kubernetes client api later and throws this error

**How to reproduce it**:  A simple XCom test reproduces it

**How to resolve it**
Add requests memory, and limits to the resources to the PodDefaults.SIDECAR_CONTAINER as below..

--
```
resources=k8s.V1ResourceRequirements(
        requests={
            "cpu": "10m",
            "memory":"32Mi"
        },
        limits={
            "cpu": "0.25",
            "memory":"32Mi"
        }
    ),
```
----------------------------------

**Comment by kaxil** [comment]
@Shivarp1 Can you confirm if this worked before Airflow 1.10.12?

**Comment by dimon222** [comment]
@kaxil I can confirm that it didn't. It might old outstanding bug back from 1.10.9

**Comment by Shivarp1** [comment]
@kaxil I think PodDefaults in pod_generator was introduced in 1.10.12?  I have not checked the 1.10.11 version
In 1.10.10 we were using the kubernetes_request_factory.

**Comment by paolaperaza** [comment]
Hi @Shivarp1 ! @dimberman looked into this at Astronomer and found that if your cluster has resource quotas turned on without a default `limitRange` specified, this will happen.

This can be checked with `kubectl get resourcequota -n <namespace> -o yaml and kubectl get limitRange -n <namespace> -o yaml`

@dimon222 Let me know if that's in line with the behavior you're seeing as well. Given the above, we're not looking into this for 1.10.13 but happy to take a closer look if you're still running into trouble.

**Comment by Shivarp1** [comment]
I have had the resource quota turned on and a limit range also specified
for the namespace
If it's also working for others, with limits set, you can close this Jira.

Thanks,
-------------------
my settings..
kubectl get resourcequota -n  shivarp_namespace -o yaml -->
   ..
,kind: ResourceQuota
  spec:
    hard:
      limits.cpu: "100"
      limits.memory: 100Gi
      requests.cpu: "10"
      requests.memory: 10Gi
...
 staus:
   hard:
      limits.cpu: "100"
      limits.memory: 100Gi
      requests.cpu: "10"
      requests.memory: 10Gi
-----------------------------------
kubectl get limitRange -n shivarp_namespace  -o yaml
,, kind: LimitRange
spec:
  limits:
  - default:
       ephemeral-storage: 100Mi
    defaultRequest:
       ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 1Gi
    maxLimitRequestRaio:
      ephemeral-storage: "1"
   min:
      ephemeral-storage: 1Mi
   type: Container

**Comment by dimberman** [comment]
Hi Shivarp,

Unfortunately we haven't been able to reproduce this issue, and we haven't seen anyone else report this.

Can you please try to launch airflow on a KinD cluster, run your DAG, and let's see if it happens there too?

If it is still happening there, can you please either suggest a change or I'd be glad to help you with the PR process. We're pretty swamped on 2.0 so I'm glad to help but need to focus on getting a few features in before the beta is cut.

Thank you!

**Comment by Shivarp1** [comment]
@dimberman I can try on KinD cluster, but this is not an issue for us anymore, as the local airflow config updates is  working for us and we are not getting the 403 error anymore.
However mounting NAS volumes on KubernetesPodOperator spawned container is still an issue..appreciate any help on this 
https://github.com/apache/airflow/issues/10920

**Comment by dimberman** [comment]
Awesome glad to hear it!
