### ISSUE TITLE
databricks host name pulling out from extra json data when token is used

### ISSUE THREAD

**Issue by yangl7** [apache/airflow#10726]
When the token is used in the databricks connection, the host name is being pulled from extra json data

https://github.com/apache/airflow/blob/fdd9b6f65b608c516b8a062b058972d9a45ec9e3/airflow/providers/databricks/hooks/databricks.py#L160

I think the host name should be pulled from databricks_conn directly as the line 164, where basic auth is being used https://github.com/apache/airflow/blob/fdd9b6f65b608c516b8a062b058972d9a45ec9e3/airflow/providers/databricks/hooks/databricks.py#L164

Thanks!

Liusong

**Comment by joshi95** [comment]
Hi, I can pick this up if needed.

**Comment by potiuk** [comment]
Assigned it to you @joshi95 !

**Comment by joshi95** [comment]
Hi, I have added a new PR for this, please review it.
