### ISSUE TITLE
Parameter name collision in AutoMLBatchPredictOperator

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10723]
Hello,

AutoMLBatchPredictOperator accepts `params` parameter, but it is also used by BaseOperator.
https://github.com/apache/airflow/blob/828f7303b7ba058c3772787529f19162a63ca1a1/airflow/providers/google/cloud/operators/automl.py#L177
https://github.com/apache/airflow/blob/828f7303b7ba058c3772787529f19162a63ca1a1/airflow/models/baseoperator.py#L341
We should think about what we want to do with it.

Best regards,
Kamil

CC: @turbaszek

**Comment by turbaszek** [comment]
Let's renam this parameter and do this as a breaking change. We should add a note in `providers/google/ADDITIONAL_INFO.md ` about incompatibility with previous version of providers packages similar to this one:
https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/ADDITIONAL_INFO.md

**Comment by tszerszen** [comment]
My proposition is to change `params` to `prediction_params`, here's the [PR](https://github.com/apache/airflow/pull/10869)

**Comment by mik-laj** [comment]
AutoMLPredictOperator is also affected.
