### ISSUE TITLE
how to deploy updates to dags that depends on updated packages

### ISSUE THREAD

**Issue by KamilMroczek** [apache/airflow#1072]
Our DAGs rely on pip installed packages. Whenever we deploy updates to these packages we re-install the packages on the airflow machine but the webserver and scheduler do not see the updates to the packages. This requires us to kill and restart the webserver and scheduler to pick up the latest package updates. We've tried rebooting the gunicorn master (with kill -HUP) but that didn't work.

When we reboot everything any job that is running currently fails and we need to manually intervene.

Ideally there would be a way to reboot the processes and they pick up where they left off. 

We are running Airflow v1.6.2 with LocalExecutors

**Comment by mistercrunch** [comment]
Until we get more dynamic DagBags, `pkfill -f gunicorn`, you can also set the scheduler to reload the DAG definition every N runs.

**Comment by KamilMroczek** [comment]
Great thanks for the input I will give it a whirl on our next deploy
