### ISSUE TITLE
Dockerfile - Enable gpg to receive keys behind a proxy

### ISSUE THREAD

**Issue by enrique-ayala** [apache/airflow#10730]
**Description**

Allow build of airflow docker image behind a corporate firewall. 

**Use case / motivation**

I would like to manually build an image by specifying the http_proxy argument. Almost all of the Dockerfile instructions work fine with --build-arg http_proxy / https_proxy , however gpg command is not able to use it correctly . Gpg requires  --keyserver-options  "http-proxy=${http_proxy}" to be set explicitly

`gpg --keyserver "${KEYSERVER}" --keyserver-options "http-proxy=${http_proxy}" --recv-keys "${KEY}"`

**Related Issues**

**Comment by potiuk** [comment]
Nice thing to add indeed. There are a couple of similar requests so I will address them in one go soon.

**Comment by potiuk** [comment]
Or maybe ypu can simply add a PR with that @enriqueayala  -> happy to review it and merge :)

**Comment by enriqueayala** [comment]
@potiuk  Sounds good :) I will work on it

**Comment by potiuk** [comment]
Awesome! Let me know if I can help :)

**Comment by potiuk** [comment]
@enriqueayala I have just submitted #11176 that should handle the case by custom `--build-arg`

**Comment by jongillham** [comment]
> @enriqueayala I have just submitted #11176 that should handle the case by custom `--build-arg`

@potiuk I would be very grateful for an example showing how this commit will allow me to pass HTTP proxy details to the `gpg --keyserver` command during the Airflow `breeze` [build process for production images](https://github.com/apache/airflow/blob/master/BREEZE.rst#id22).
