### ISSUE TITLE
Running templatized Pig scripts (PigOperator/BashOperator)

### ISSUE THREAD

**Issue by garthcn** [apache/airflow#1074]
Hi,

We are trying to run some Pig scripts, but it seems the only way to do this is to use BashOperator. However BashOperator doesn't seem to support Jinja template. Am I missing something? If not, is there any plan to implement a PigOperator with better Jinja support? 

Thanks for the awesome work!

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/1075
