### ISSUE TITLE
Separate nodeSelector logic for scheduler+webserver vs ephemeral resources

### ISSUE THREAD

**Issue by aimran-adroll** [apache/airflow#10761]
**Description**
I would like to separate out the current `nodeSelector` logic for critical (imo) pods such as the scheduler+webserver vs worker pods.

**Use case / motivation**

If we look at the current implementation, https://github.com/apache/airflow/blob/ba36f876dc2334104fe75ec25c0c56be70e756ed/chart/values.yaml#L37-L40 

we have only **one** place to specify the logic above

Subsequently, the above template is applied _as is_ across all the resources (e.g scheduler, webserver, worker, ...)

Typically, I work with an autoscaling group that consists of few stable (ie on-demand) instances along with the more ephemeral spot (preemptible) instances. 

During deployment, I would like to assign the critical (TBD but at least scheduler and webserver) pods to the on-demand instances. 

**Related Issues**

grepping for `nodeSelector` did not turn up anything here or the astronomer chart repo.

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/13508
