### ISSUE TITLE
Some (not all) dags are not scheduled according to the configured interval (@daily). Why?

### ISSUE THREAD

**Issue by foresightyj** [apache/airflow#10775]
**Apache Airflow version: v1.10.6**:

**Environment**:

- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)
- **Kernel** (e.g. `uname -a`): Linux linux2 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: pip install
- **Others**:

**What happened**:

I have about 10 airflow dags that needs to be run daily to check nightly builds of my system. So I scheduled them all with `@daily` intervals. But only some of them are scheduled as expected while others don't. So for the past few weeks I always trigger them manually.

**What you expected to happen**:

scheduled as expected (`@daily`)

**How to reproduce it**:

Not possible as I do not use and I am also not so familiar with docker/kubernetes

**Anything else we need to know**:

The screenshot below shows the problem. Note that it is 7 Sept today. 

![image](https://user-images.githubusercontent.com/1296736/92340742-2745f400-f0ee-11ea-94dd-02c4577efe03.png)

![image](https://user-images.githubusercontent.com/1296736/92340897-8e63a880-f0ee-11ea-94fd-96afcdc5b6d1.png)

This is one of the dag definitions:

```
default_args = {
    'owner': 'foresightyj',
    'depends_on_past': False,
    'start_date': airflow.utils.dates.days_ago(0),
}

dag = DAG('check_vue_types_v1',
          catchup=False,
          schedule_interval='@daily',
          default_args=default_args)

warmup = BashOperator(
    task_id=f'vue-type-check',
    bash_command=f'npm run vtc --prefix /home/foresightyj/Working/fht-web-vue',
    dag=dag,
)
```

Occassionally, I saw this warning but I guess that is because some tasks took too long and I am running with a SequentialExecutor in only one machine?

![image](https://user-images.githubusercontent.com/1296736/92340824-56f4fc00-f0ee-11ea-94a5-b1753abc8a47.png)

How often does this problem occur? Once? Every time etc?

Dags not scheduled are never scheduled. And those which are scheduled are scheduled correctly (@daily)

I am guessing that it is unlikely this is a bug of airflow. I must have missed something. Thanks if anybody could enlighten me.

**Comment by eladkal** [comment]
We can't really investigate as there are no actual reproduce steps.
I created dags with `schedule_interval='@daily'`on both 1.10.14 and 2.0.0 and it's working fine.
If you still need help troubleshooting your case please use http://stackoverflow.com/
