### ISSUE TITLE
KubernetesPodOperator Secret doesn't use key property when attaching to pod as volume

### ISSUE THREAD

**Issue by a-poptsov** [apache/airflow#10777]
For the case when secret key is specified system should handle this key during attaching secret to pod as volume.

Expected result is:

> only specified key should be attached from full secret. it should be mounted as a file to the path == volume_mount  https://kubernetes.io/docs/concepts/configuration/secret/#projection-of-secret-keys-to-specific-paths

Current result:

> all keys are attached if key property is presented in secret https://github.com/apache/airflow/blob/v1-10-stable/airflow/kubernetes/secret.py#L107

**Comment by a-poptsov** [comment]
According my limited understanding we should specify items=[self.key] in the  https://github.com/apache/airflow/blob/v1-10-stable/airflow/kubernetes/secret.py#L99

**Comment by dimberman** [comment]
@a-poptsov would this fix this issue? https://github.com/apache/airflow/pull/11369

**Comment by a-poptsov** [comment]
@dimberman Sorry for late response. Thanks for a great job with adding items field. But I think it is partial fix. Secret contains all required information already  even without using items directly. For example I can specify `
`Secret("volume", "/etc/ca.pem", "secret_name", "secret_key")`` I am expecting that only selected key will be mounted

**Comment by a-poptsov** [comment]
I suggest to add items by default in the case  that was specified in prev. comment
