### ISSUE TITLE
TaskInstance tooltip in DAG tree view shows incorrect Operator

### ISSUE THREAD

**Issue by zbstof** [apache/airflow#10782]
**Apache Airflow version:** 2.0.0.dev0, built from HEAD master branch

**Environment:** kubernetes

**What happened:**

1. Create task **A** with operator **First**
2. Run the dag
2b. Single task instance of **A** is visible in the tree view
2c. On mouseover of this task instance, **Operator: First** is visible
2d. If task instance is opened (url `/task`), tab "Task Instance Details" then in column **operator** value is **First**
3. Change task **A** to use operator **Second** instead
4. Run the dag
4a. Two task instances of **A** is visible in the tree view
4b. On mouseover of the first task instance, **Operator: Second** is visible
4c. On mouseover of the second task instance, **Operator: Second** is visible
4d. If first task instance is opened (url `/task`), tab "Task Instance Details" then in column **operator** value is **First**
4e. If second task instance is opened (url `/task`), tab "Task Instance Details" then in column **operator** value is **Second**

**What you expected to happen:**

4b should be: On mouseover of the first task instance, **Operator: First** is visible

**Anything else we need to know:**

Reproduces every time

**Comment by JeffryMAC** [comment]
@alexbegg didn't you play with tooltips recently? maybe you have input

**Comment by ashb** [comment]
Fixing this properly _might_ without making _A lot_ of DB queries is hard, so this isn't a "good first issue"

This possibly falls under [AIP 36 - DAG Versioning](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning) too.

**Comment by eladkal** [comment]
We no longer have tree view so I'm closing this one
