### ISSUE TITLE
Task waits fror downstream (Skip)

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#1078]
![image](https://cloud.githubusercontent.com/assets/8076399/13318282/da637aa0-dbb1-11e5-8207-f9686ab2df51.png)

Is there any way to use "skip" a task and not all the downstream?

I would like to execute load task, if just one precedent task was succefull.

I can mark the task `false_01` as success, eg when a file doest exists, but I think skip show me visually that the task was skipped instead of just marked as success.

I imagine that I could be a option on the ShortCircuit operator.

**Comment by mistercrunch** [comment]
What's the trigger_rule on `join`? Seems like you could set it to `one_success`.

**Comment by r39132** [comment]
@pedrorjbr I do this in the DAG below. I have a BranchPythonOperator, similar to the ShortCircuitOperator you use above. In my case, my `check_for_time_to_build_model_branch_condition` BranchPythonOperator, branch left or right, and then skips the other side. My join happens in `wait_for_previous_hour`.

<img width="782" alt="screenshot 2016-02-29 13 14 49" src="https://cloud.githubusercontent.com/assets/581734/13409158/768a31f8-dee6-11e5-9e8d-e7bb43a2f8cb.png">

My Join Operator specifies a `trigger_rule='one_success',`

```
wait_for_previous_hour = ExternalTaskSensor(
    task_id='wait_for_previous_hour',
    trigger_rule='one_success',
    external_dag_id=DAG_NAME,
    external_task_id='send_email_notification_flow_successful',
    allowed_states=['success'],
    execution_delta=timedelta(hours=1),
    dag=dag)
```

As @mistercrunch mentions, just add a trigger rule to your `join` task.

All you need to do for your case is something like: 

```
join_op = DummyOperator(
    task_id='join',
    trigger_rule='one_success',
    dag=dag)
```

Hope this helps. I'm closing this. If you need to re-open, ping me on gitter.
