### ISSUE TITLE
Async pod launch 

### ISSUE THREAD

**Issue by agonen** [apache/airflow#10791]
we have a long-running task in airflow (5hr and more)

I would like the following abilities : 
1. when waiting for the pod starts or finishes, the log gets prints every 2 sec (this creates a lot of logging lines  ) can we expose this as a parameter ?
2. can we have a parameter to fire an forget (after the pod started running) and the monitor the status of the task using sensor 
this can free the worker and reduce resources 

https://github.com/apache/airflow/blob/10ce31127f1ff87176158935925afce46a989917/airflow/kubernetes/pod_launcher.py#L140

**Comment by agonen** [comment]
?

**Comment by agonen** [comment]
?

**Comment by dimberman** [comment]
Hi @agonen, would you like to write this feature in? Would be glad to help you through the development/PR process :)

**Comment by dimberman** [comment]
Also worth noting that this PR will ensure that all real pod logs will show up in the airflow UI if you set that flag https://github.com/apache/airflow/pull/11325

**Comment by jens-scheffler-bosch** [comment]
This feature request is a bit "aged". Is it still current?
Meanwhile the `KubernetesPodOperator` implements the deferred mode via `deferrable=True`, see https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html. This should resolve (2) of your request.

For (1) can you describe a bit your detailled desire? You just want to prevent the status printe every 2 seoncs or do you want to skip other parts of the task log as well? Are you willin gto contribute a feature PR?
