### ISSUE TITLE
Allow labels in KubernetesPodOperator to be templated

### ISSUE THREAD

**Issue by yamrzou** [apache/airflow#10792]
**Description**

It would be useful to have labels being a templated field in KubernetesPodOperator, in order for example, to be able to identify pods by run_id when there are multiple concurrent dag runs.

**Comment by dimberman** [comment]
@yamrzou can you create an example of what this would look like? Would this not already be handled by pod_template_file?

**Comment by yamrzou** [comment]
@dimberman We are using this to add variables from the dagrun conf to labels, in order to use them to filter pods and logs.

It looks like:
```
# ensure_valid_pod_label is a user-defined macro to make sure the value is a valid Kubernetes pod label

task = KubernetesPodOperator(
    ...,
    labels={
        "is_airflow_pod": "true",
        "run_id": "{{ ensure_valid_pod_label(run_id) }}",
        "element_id": "{{ ensure_valid_pod_label(dag_run.conf.element_id) }}",
        "start_date": "{{ ensure_valid_pod_label(dag_run.conf.start_date) }}",
        "end_date": "{{ ensure_valid_pod_label(dag_run.conf.end_date) }}",
        },
    )
```
I'm not familiar with `pod_template_file`, so I'm not sure if it would be possible.
