### ISSUE TITLE
Explore if "smart sensor" can be used with a new mode (similar to reschedule) instead.

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10817]
An enhancement to Smart Sensor feature introduced in https://github.com/apache/airflow/pull/5499 might be to have a separate “mode” like "reschedule mode".

This would also simplify making Sensors Smart Sensor compatible and unify methods with 'reschedule' mode.

**Comment by kaxil** [comment]
cc @KevinYang21

**Comment by eladkal** [comment]
Now that we have deferrable operators and we even say in the [docs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html):
`Deferrable Operators essentially supersede Smart Sensors, and should be preferred for almost all situations.`

Do we still want to enhance Smart Sensor?

**Comment by potiuk** [comment]
I believe we should not, possibly even we should deprecate smart sensors in 2.3 (to be removed in 3.0.

**Comment by kaxil** [comment]
Pretty much agree. Smart Sensors are marked experimental too so we can remove it sooner if needed but just incase someone is using it we can remove them in 3.0 too
