### ISSUE TITLE
auth backends User models do not init the User superclass

### ISSUE THREAD

**Issue by laura-moore** [apache/airflow#1081]
As an example, it looks like the PasswordUser only sets the 'user' attribute in the init method; it does not init the base User so attributes like username are not set unless set explicitly. The issue is that the load_user method does not explicitly set these attributes.  

One consequence of this is when the wwwutils.action_logging decorator is used to collect log information, it tries to extract the username attribute of current_user and use it to set the Log owner:

```
        if current_user and hasattr(current_user, 'username'):
            user = current_user.username
        else:
            user = 'anonymous'

       log = models.Log(
            event=f.__name__,
            task_instance=None,
            owner=user,
            extra=str(request.args.items()),
            task_id=request.args.get('task_id'),
            dag_id=request.args.get('dag_id'))


```

But because username attribute has not been set in the base User class, this returns nothing, which results in a blank Log model owner:

One solution is to explicitly set the username attribute in load_user:

```
@login_manager.user_loader
def load_user(userid):
    LOG.debug("Loading user %s", userid)
    if not userid or userid == 'None':
        return None

    session = settings.Session()
    user = session.query(models.User).filter(models.User.id == int(userid)).first()
    session.expunge_all()
    session.commit()
    session.close()

    passuser = PasswordUser(user)
    passuser.username = user.username
    passuser.email = user.email

    return passuser

```

Another solution is to init the PasswordUser class like:

```
class PasswordUser(models.User):
    _password = Column('password', String(255))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordUser, self).__init__(*args, **kwargs)


```

and to have the load_user method as:

```
@login_manager.user_loader
def load_user(userid):
    LOG.debug("Loading user %s", userid)
    if not userid or userid == 'None':
        return None

    session = settings.Session()
    user = session.query(models.User).filter(models.User.id == int(userid)).first()
    session.expunge_all()
    session.commit()
    session.close()

    user_dict = user.__dict__
    user_dict.pop('_sa_instance_state', None)

    return PasswordUser(user, **user_dict)

```

**Comment by mistercrunch** [comment]
We have our own auth backend that we maintain at Airbnb, please tag and get help from the folks who wrote the backend you are interested in using.

**Comment by laura-moore** [comment]
OK, thanks, I'll do that.
@neovintage maybe you have some thoughts on this? Thanks

**Comment by neovintage** [comment]
@laura-moore I don't have a strong preference on the solutions you've presented. Is there one you'd prefer over the others?

Coding up a PR should be quick.

**Comment by laura-moore** [comment]
@neovintage  Thanks for taking a look. I don't have a strong preference. I'm leaning towards the second because I think it's more consistent with other init methods in the airflow codebase. What do you think?

**Comment by bolkedebruin** [comment]
@laura-moore @neovintage any news on this? Would one of you want to do a PR for this for the backends? It is a nice bugfix

**Comment by neovintage** [comment]
Been kinda busy with work. I might be able to get to this next week.
