### ISSUE TITLE
Mark "Smart Sensor" as an early-access feature

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10815]
**Description**

Based on our discussion during Airflow 2.0 dev call, the consensus was that **Smart Sensors** ([PR](https://github.com/apache/airflow/pull/5499)) will be included in Airflow 2.0 as an **early-access** feature with a clear note that this feature might potentially change in future Airflow version with breaking changes.

Also, make it clear that Airbnb is running it in PROD since ~6-7 months to give confidence to our users

**Comment by kaxil** [comment]
@YingboWang Let me if you would love to do it

**Comment by YingboWang** [comment]
> @YingboWang @KevinYang21 Let me if you would like to do it. If not, we could mark this as a "good first issue" :)
Hi @kaxil I would be happy to do it. Is there any instruction/example PR on how to do that?

**Comment by kaxil** [comment]
Just a notice similar to https://airflow.readthedocs.io/en/latest/rest-api-ref.html (https://github.com/apache/airflow/blob/master/docs/rest-api-ref.rst) at https://airflow.readthedocs.io/en/latest/smart-sensor.html
