### ISSUE TITLE
Docs around different execution modes for Sensor

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#10816]
**Description**

It would be good to add docs to explain different modes for Sensors:

1. Poke mode
1. Reschedule mode
1. Smart Sensor

and to explain the advantages of one over the other

**Comment by kaxil** [comment]
cc @YingboWang @KevinYang21

**Comment by xinbinhuang** [comment]
I will work on this over the weekend. @mik-laj  where do you think this part should go into for the new doc structure?

**Comment by kaxil** [comment]
Can be a sub-section in https://airflow.readthedocs.io/en/latest/concepts.html#operators around Sensors

**Comment by ryw** [comment]
Reviewing 2.0rc1 issues, @xinbinhuang any progress on this? Will you be able to close out this week?

**Comment by xinbinhuang** [comment]
> Reviewing 2.0rc1 issues, @xinbinhuang any progress on this? Will you be able to close out this week?

Yeah, I am working on this, and I think a PR will be up tonight or tomorrow
