### ISSUE TITLE
WebHdfsSensor multiple connection for active and standby namenode

### ISSUE THREAD

**Issue by MR-GOYAL** [apache/airflow#10821]
I am using WebHdfsSensor. In our cluster we have standby and active node which interchange for maintenance and other purposes. I have to provide connection so that if one is standby than Sensor connect with other host.

I tried giving host as a list [servera,serverb] but it didn't work.

What is the way to handle this case?

Thanks in Advance

**Comment by eladkal** [comment]
You can't use two separate connections with sensors.
I'm closing as this is something that won't be addressed with a specific sensor - it's more in the area of https://github.com/apache/airflow/issues/9755
