### ISSUE TITLE
System Test Automation (AIP-4)

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10835]
This is an umbrella ticket for automation of our system tests. 

We already have a lot of semi-automated system tests in our code but we only trigger them manually.

We should aim to get them automatically executed in CI system,.

**Description**

We need to set up the CI build and a mechanism to authenticate/use credits from relevant services.

**Use case / motivation**

Confirm that the providers/operators are working with the real systems.

**Comment by mik-laj** [comment]
Link: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+Automation+of+System+Tests+for+external+systems

**Comment by TobKed** [comment]
I worked for some time on automating system tests.
It resulted in the repository with the configuration for system tests: https://github.com/PolideaInternal/airflow-system-tests.

**Comment by potiuk** [comment]
Cool

**Comment by eladkal** [comment]
Closing as we have AIP47
