### ISSUE TITLE
Description Field for Connections

### ISSUE THREAD

**Issue by yene** [apache/airflow#10840]
**Description**
A description field for connections. Allowing us to explain how the data source is used, where it is hosted, and if it is persisted/ under backup.

**Use case / motivation**
I just added a new connection to our Airflow configuration. When updating the internal docs that explain on how to use the connection, I asked myself: Are the devs even gonna read this, would it not be better to have an explanation next to the connection.

**Comment by mik-laj** [comment]
Sound good to me. Should I assign you to this ticket?

**Comment by abhilash1in** [comment]
@mik-laj  I can give this a shot. Please assign it to me.

**Comment by mik-laj** [comment]
@abhilash1in I assigned you to this ticket.
