### ISSUE TITLE
Airflow checks for wrong KubernetesExecutor import on task run

### ISSUE THREAD

**Issue by sglickman** [apache/airflow#10858]
https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/airflow/www/views.py#L1152

This code attempts to check whether the current executor is a KubernetesExecutor, but that executor has been moved out of contrib, it looks like, and into airflow.executors.kubernetes_executor. The ImportError is, for some reason, swallowed.

**Comment by sglickman** [comment]
looks like this is fixed in master: https://github.com/apache/airflow/blob/master/airflow/www/views.py#L992 but the KubernetesExecutor was moved in v.1.10 stable: https://github.com/apache/airflow/blob/v1-10-stable/airflow/executors/kubernetes_executor.py

**Comment by dimberman** [comment]
Hi @sglickman this has been fixed and will be released with 1.10.13.
