### ISSUE TITLE
Mask credentials in Rendered Template tab of task instance details page

### ISSUE THREAD

**Issue by abhilash1in** [apache/airflow#10855]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): `Ubuntu 18.04.4 LTS`
- **Kernel** (e.g. `uname -a`): `Linux upcairflow01 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
I have some credentials stored on Airflow which I'm passing to a PythonOperator via `op_kwargs` as follows:
```
from airflow.hooks.base_hook import BaseHook
from airflow.operators.python_operator import PythonOperator
from sample_module import sample_python_callable

CONN_ID = 'sample_conn_id'
conn = BaseHook.get_connection(CONN_ID)

# other DAG related code
# ...
sample_task = PythonOperator(
    task_id='sample_task',
    python_callable=sample_python_callable,
    op_kwargs={
        'credentials': {
            'host': conn.host,
            'username': conn.login,
            'password': conn.password
        }
    }
)
# ...
# other DAG related code
```
The actual plaintext credentials are exposed in the `Rendered Template` tab of the task instance details page.
![Screen Shot 2020-09-09 at 11 23 27 PM](https://user-images.githubusercontent.com/9111980/92689210-7b6df580-f2f3-11ea-9993-29d67df16b74.png)

**What you expected to happen**:

Expected all credentials/passwords stored as Airflow Connections to be **masked** in the UI.

There should be a way for Airflow to identify credentials/passwords and mask them everywhere (UI and logs) automatically. 

**How to reproduce it**:
Create a task using `PythonOperator` similar to the example above and pass some credentials stored as Airflow Connections. They are visible in plaintext on the UI.

**Anything else we need to know**:

**Comment by mik-laj** [comment]
You should pass conn_id to callable and this callable should use `conn = BaseHook.get_connection(CONN_ID)` to read credentials. 

Otherwise, your DAG will make a lot of database queries. In the community, we have automatic tests on CIs that detect and block such DAG file
https://github.com/apache/airflow/blob/ff7232761497985720387c4288439ac1dce2ee77/tests/test_example_dags.py#L47

**Comment by kaxil** [comment]
Similar issues:

- https://github.com/apache/airflow/issues/8421
- https://github.com/apache/airflow/issues/9638

**Comment by abhilash1in** [comment]
@mik-laj @kaxil thank you, the similar issues linked above covers this in more detail. Closing this issue.
