### ISSUE TITLE
Concurrency=1 not honored when depends_on_past=False

### ISSUE THREAD

**Issue by toryhaavik** [apache/airflow#1085]
I have a celery worker listening on a queue called "py2", which is the default queue in my airflow.cfg.  The scheduler is running, but my DAG is currently set to "off".  Steps to reproduce issue:
1. Enter these commands one after another:
   - `airflow run dag task 2015-01-01`
   - `airflow run dag task 2015-01-02`
   - `airflow run dag task 2015-01-03`
   - `airflow run dag task 2015-01-04`
2.  `2015-01-01` starts running while the others are queued properly because I have `concurrency=1` for this DAG
3. after `2015-01-01` successfully completes, all 3 queued tasks start executing, when I would have expected only 1 to start (and not necessarily `2015-01-02` because I have `depends_on_past=False`, so it might be arbitrary which starts next, which is fine)

Do I have something setup incorrectly to be sure that only 1 task instance is executing at a time?

**Comment by lucafuji** [comment]
I think right now how concurrency works is by checking how many running task instances in database, which means it's possible all tasks can start running at the same time because when they query the database, they all get a count of 0

**Comment by toryhaavik** [comment]
that seems to make sense based on what i see.  i've been using pools as a better way to control concurrency, but it gets annoying because the creation/management of a pool isn't easily expressed in the DAG itself, like the `concurrency` and `max_active_runs` parameters are.

**Comment by lucafuji** [comment]
Yes.. I think the airflow guys should query the number of running tasks from the executor .e.g. celery executor before queuing task_instance into the executor. Since it's in memory, they are guaranteed to get the most updated count. But this maybe a problem if you run some tasks over cli because that will be another executor

**Comment by r39132** [comment]
@mistercrunch How do you work around this at Airbnb? I don't use celery, so have not run into this. Also, I control my concurrency needs exclusively through the use of pools and have not run into an issue with it.

**Comment by r39132** [comment]
I think this should be reproduceable on the Local Executor as well. Can you provide a code snippet so that I can reproduce?

**Comment by r39132** [comment]
I reproduced this bug in the LocalExecutor with some test code. 

**1. My Example Code**

```
from airflow.operators import BashOperator, DummyOperator
from airflow.models import DAG
from datetime import datetime, timedelta

seven_days_ago = datetime.combine(datetime.today() - timedelta(7),
                                  datetime.min.time())
args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': seven_days_ago,
}

dag = DAG(
    dag_id='example_concur', default_args=args,
    concurrency= 1,
    schedule_interval='0 0 * * *',
    dagrun_timeout=timedelta(minutes=60))

task = BashOperator(
    task_id='task',
    bash_command='echo "starting - "; sleep 15; echo "done"',
    dag=dag)
```

**2. Steps to Reproduce
A. Once the DAG is loaded, it should run 7 daily DAG Runs**

<img width="1006" alt="screenshot 2016-03-03 06 19 21" src="https://cloud.githubusercontent.com/assets/581734/13486343/39d82bc4-e108-11e5-9d3e-0b552bcd7c87.png">

**B. Clear the DAG**

<img width="816" alt="screenshot 2016-03-03 06 22 41" src="https://cloud.githubusercontent.com/assets/581734/13486364/5fd1db86-e108-11e5-9ae6-6c77ed06b9b2.png">

**C. You will see the first run start running and the other 6 runs will be queued!**
<img width="1215" alt="screenshot 2016-03-03 06 18 35" src="https://cloud.githubusercontent.com/assets/581734/13486382/8cdc88ec-e108-11e5-9fda-a2ff40ca8ef3.png">

**D. Once the first one completes, the other 6 will all start running in parallel**
<img width="1357" alt="screenshot 2016-03-03 06 18 53" src="https://cloud.githubusercontent.com/assets/581734/13486396/a4c26c74-e108-11e5-8245-ec1427a556f9.png">

**E. Then they all complete**
<img width="1006" alt="screenshot 2016-03-03 06 19 21" src="https://cloud.githubusercontent.com/assets/581734/13486426/f256e9ba-e108-11e5-9438-5e20804e9a90.png">

**Comment by r39132** [comment]
I've confirmed this bug only occurs when `depends_on_past=False` -- essentially, `concurrency` is not honored for `depends_on_past=False` but is honored for `depends_on_past=True`

When I set `depends_on_past=True`, I observe the correct, expected behavior below:

<img width="1323" alt="screenshot 2016-03-03 06 28 54" src="https://cloud.githubusercontent.com/assets/581734/13486520/ae0c00f0-e109-11e5-9184-4e8609f0257d.png">

<img width="1329" alt="screenshot 2016-03-03 06 29 08" src="https://cloud.githubusercontent.com/assets/581734/13486524/b9597640-e109-11e5-8e7e-259eabdf0054.png">

**Comment by lucafuji** [comment]
Here is the code with depends_on_past = True but actually will have multiple task instance running at the same time.

```
num_of_tasks = 30

default_args = {
    'owner': 'lucafuji',
    'depends_on_past': True,
    'start_date': datetime(2016, 3, 1),
    'end_date': datetime(2016, 3, 3)
}


def sleep_30(**kwargs):
    logger.info("My task id is {}".format(kwargs['task'].task_id))
    time.sleep(30)

dag = DAG(dag_id="concurrency_test", default_args=default_args,concurrency=1)
for i in range(0, num_of_tasks):
    tid = "sleep_task_{}".format(i)
    task = PythonOperator(dag=dag, task_id=tid, python_callable=sleep_30, provide_context=True)
```

**Comment by r39132** [comment]
@lucafuji Thanks, though i already provided an example of one above. Also, please test with `depends_on_past:True`. Additionally, I'm testing on HEAD Master.

**Comment by lucafuji** [comment]
@r39132 Thanks for quickly reply 
Just test with depends_on_past=True,result is the same.

Actually my example is slightly different from yours because I've multiple tasks for the same day and they are independent.

**Comment by r39132** [comment]
If you have a fix in mind, please feel free to submit a PR. I'd be happy to review it.

**Comment by lucafuji** [comment]
Just created a pull request
https://github.com/airbnb/airflow/pull/1120
This is my first time to do a pull request, feel free to drop it but I will appreciate it very much if you can review the logic

**Comment by griffinqiu** [comment]
I also met the same issue. My way is,
1. Turn off the DAG.
2. Clear the tasks with future
3. Delete the DAG Runs which their status is running
4. Turn on the DAG

The reason of I cannot set depends_on_past=True is #914
