### ISSUE TITLE
Document Airflow with multiple webservers/schedulers

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#1087]
From the gitter channel @r39132:

> r39132 19:19
> Hi Folks! So, we are running dual webserver/schedulers in prod.. and they are running pretty well.
> So, we had a fire today.. we didn't know that someone setup airflow to run a webserver & scheduler combo on 2 boxes in prod
> We upgraded airflow on one machine and not the other and then deployed dags to both. The patch included a new API that the DAGs depended on.
> Well, one machine worked fine but the other didn't..
> 
> r39132 19:25
> due to the shared state in the DB, the webserver appeared to be flapping in states across multiple pages of the UI.
> We were told about the dual setup after 4 hours of scratching our heads and going crazy..
> we resolved the issue by shutting the other machine down
> then we deployed the patch to the second machine and restarted it.. and it worked fine
> lesson learned.. airflow does not work in a sane way if DAGs are missing from one machine (and present on the other) or if one DAG fails to import on one machine but not the other. In the second case, you will see flapping as one successfully imports and one fails at importing.
> Since the failed import is written to the Import error table, all webservers will report the error.. which will indicate that one of your systems has an issue

**Comment by krisskross** [comment]
Would be nice with a clarification on how to perform upgrades when running in a HA deployment.
