### ISSUE TITLE
Should we stay flexible to copy files from s3 to Redshift when using S3ToRedshiftTransfer?

### ISSUE THREAD

**Issue by Kobe-Wang** [apache/airflow#10895]
**Description**

Could we copy the different filename from s3 with the table name in Redshift using S3ToRedshiftTransfer? 

**Use case / motivation**

I want to use the S3ToRedshiftTransfer operator to copy S3 files to Redshift, but I found the table name in Redshift is the same as the S3 filename when I traced the S3ToRedshiftTransfer source code. To be more specific, if I want to use the name is the difference between the table name in Redshift and filename in S3,  I can not use the S3ToRedshiftTransfer operator. Could you consider this part to stay flexible for the S3ToRedshiftTransfer operator?

Add the copy_query source code from the S3ToRedshiftTransfer operator as the followings: (link: https://airflow.apache.org/docs/stable/_modules/airflow/operators/s3_to_redshift_operator.html )

```python
copy_query = """
            COPY {schema}.{table}
            FROM 's3://{s3_bucket}/{s3_key}/{table}'
            with credentials
            'aws_access_key_id={access_key};aws_secret_access_key={secret_key}'
            {copy_options};
        """.format(schema=self.schema,
                   table=self.table,
                   s3_bucket=self.s3_bucket,
                   s3_key=self.s3_key,
                   access_key=credentials.access_key,
                   secret_key=credentials.secret_key,
                   copy_options=copy_options)
``` 

**Related Issues**

No

**Comment by JeffryMAC** [comment]
It seems like https://github.com/apache/airflow/pull/9246 is going to solve this problem
@Kobe-Wang maybe you can test the code to make sure it solves it?

**Comment by Kobe-Wang** [comment]
Hi @JeffryMAC, 
Thank you for your reply. I found the issue is related to #10436. And the PR already be merged into the `apache:master` branch. I will close the feature request.

By the way, I will test the code to make sure the enhancement from #9246 later.

**Comment by Kobe-Wang** [comment]
related to #10436
