### ISSUE TITLE
Allow custom behavior on sensor timeout

### ISSUE THREAD

**Issue by shakedzy** [apache/airflow#10911]
**Description**

Allow custom behavior on sensor timeout: When sensors timeout, they throw an exception. A custom behavior on such cases can be useful, just like the `on_kill` method.

We found it to be necessary where I work, and I believe we're not the only ones who could benefit from this. 

Obviously, I suggest myself as the assignee for this.

**Comment by eladkal** [comment]
@shakedzy Can you please explain the missing functionality further?

`BaseSensorOperator` inherits from `BaseOperator` thus you can use `on_failure_callback`.

**Comment by shakedzy** [comment]
@eladkal - as far as I've seen from my use, there's a difference between failure (meaning, task failed) and timeout (meaning, it didnt fail, it just takes too long)

**Comment by eladkal** [comment]
@shakedzy  when timeout happens it raises exception.
Consider following example:
```

from datetime import datetime, timedelta
from airflow import DAG
from airflow.sensors.sql_sensor import SqlSensor


default_args = {
    'owner': 'Airflow',
    'start_date': datetime(2019, 6, 25),
    'execution_timeout': timedelta(minutes=1),
}


def fail_func(context):
    print("Called on failure method is confirmed!")


with DAG(
    dag_id="check_sensor",
    default_args=default_args,
    schedule_interval=None,
    max_active_runs=1
) as dag:

    sensor_op = SqlSensor(
        task_id='sensor',
        conn_id='presto_default',
        sql='select 1=2', # This SQL will be never be evaluated to True thus it will poke till timout
        on_failure_callback=fail_func
    )

```

![Screen Shot 2020-10-04 at 13 10 55](https://user-images.githubusercontent.com/45845474/95012676-2d72b600-0643-11eb-8af1-9bee1c3fa68a.png)
