### ISSUE TITLE
Api to fetch all dag ids filtered by tags

### ISSUE THREAD

**Issue by anshul17khanna** [apache/airflow#10914]
**Description**
A utility as well as a Restful Api to fetch all the dag ids by a given tag. The method can be implemented as `get_dags_by_tag` and experimental api as `GET /api/experimental/tags/<TAG>`.

**Use case**
My organisation uses tags to identify a Dag's responsibilities among teams, whereas the ownership is handled only by a single person. So authentication of other Rest apis for of our internal tool features can be easily done with corresponding team tags.

I also feel that use cases for this api will grow over time. If this sounds good, I would like to go ahead for the implementation.

**Comment by potiuk** [comment]
We have a fully-featured API coming in Airflow 2.0. #8107 the current, experimental API is not going to be extended any more. Airflow 2.0 is going to be released by the end of the year - please observe #10152 and https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+2.0+-+Planning
