### ISSUE TITLE
Add how to documentation for Qubole Operator

### ISSUE THREAD

**Issue by chattarajoy** [apache/airflow#10929]
We are trying to improve our documentation, and I see a guides that explains how to use these operators is missing. Here are guides for other operators: https://airflow.readthedocs.io/en/latest/howto/operator/index.html
Wouldn't you like to write a guide for this operator? In practice, the guide is an example DAG file + description.

_Originally posted by @mik-laj in https://github.com/apache/airflow/issues/9347#issuecomment-691988305_

**Comment by chattarajoy** [comment]
Please assign this to me

**Comment by mik-laj** [comment]
I would be past the point if this would also include documentation that describes the required steps to set up a connection.
https://airflow.readthedocs.io/en/latest/howto/connection/index.html#connection-types
https://airflow.readthedocs.io/en/latest/howto/operator/google/cloud/natural_language.html#prerequisite-tasks Section "Prerequisite Tasks"

**Comment by kaxil** [comment]
Thanks @chattarajoy

**Comment by mik-laj** [comment]
@chattarajoy Do you need help with this ticket?

**Comment by kaxil** [comment]
I have cleared the assignee for now so others who are interested can start working on it. Let me know if you want to continue though

**Comment by kazanzhy** [comment]
Hi all. 
I've prepared a draft PR #20058
I will be very glad to any suggestions, especially from @chattarajoy
