### ISSUE TITLE
Asynchronous run for DatabricksRunNowOperator

### ISSUE THREAD

**Issue by anshul17khanna** [apache/airflow#10921]
**Description**

Ability to let `DatabricksRunNowOperator` execute asynchronously based on an optional argument `async=False`.

**Use case / motivation**

Sometimes a databricks job would want to perform actions without letting the Dag operator wait for its completion. This would be very useful when the child tasks would periodically want to interact with that running job such as for message queue.

If this is valid, would like to be assigned the same.

**Comment by Red-0111** [comment]
Hi, I would like to work on this issue, please tell me how to proceed :)

**Comment by potiuk** [comment]
Feel free. Start with https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst and then read on for some details in https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst

**Comment by jtvmatos** [comment]
This ticket appears to be related with this -> https://github.com/apache/airflow/issues/18999

**Comment by eskarimov** [comment]
It seems related, though I think it's a different async functionality 🙂 The one requested in the current issue is about marking the task as completed once a job is submitted to Databricks, and then letting child tasks interacting with it, taking care of it, checking for status, etc.
While #18999 is about introducing new async or deferrable versions of Databricks operators, using the new deferrable tasks functionality released with 2.2.0

**Comment by uranusjr** [comment]
Note that `async=False` won’t work since `async` is now a keyword. Given the particular feature request here, `nowait=True` is probably a better argument name. The intention is not to actually make the operator itself work asynchronously (that’s #18999), but to _allow making asynchronous interaction with Databricks_ by not waiting for completion to end the task.

**Comment by eskarimov** [comment]
I would like to contribute or help to contribute on this functionality, not sure how it'd be better to proceed as I see @Red-0111 was assigned for this issue on 28th July. Could I help any how or take over?

**Comment by uranusjr** [comment]
Feel free to write and propose a PR anyway; in the worse case scenario, you get to write some code for fun and contributors can compare notes to come up with the best implementation possible 🙂

**Comment by eskarimov** [comment]
The issue can be closed, the PR #20536 has solved it
