### ISSUE TITLE
Improve test and typing coverage for Qubole Operator

### ISSUE THREAD

**Issue by chattarajoy** [apache/airflow#10928]
This provider also has poor typing coverage.
https://github.com/apache/airflow/issues/9708#issuecomment-687518888

_Originally posted by @mik-laj in https://github.com/apache/airflow/issues/9347#issuecomment-691988905_

**Comment by chattarajoy** [comment]
Pls assign this to me

**Comment by morrme** [comment]
Hello @eladkal and @vikramkoka ! 

It seems as though this operator now has ~94% coverage according to https://github.com/apache/airflow/issues/9708#issuecomment-714197157

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/11229
