### ISSUE TITLE
Missing system tests for Qubole provider

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#10931]
Hello,

We are trying to work on increasing [system test](https://github.com/apache/airflow/blob/master/TESTING.rst#airflow-system-tests) coverage of all providers that require credentials to communicate with external services/systems. Currently, system tests are not run on CI, but are still very helpful if you make changes to your code and want to make sure no regression has occurred. In the future, we want to run these tests also on CI - [AIP-4](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+Automation+of+System+Tests+for+external+systems). 

I noticed that we lack system tests for Qubole and I think it is worth adding these tests to make sure that the [example DAG](https://github.com/apache/airflow/blob/master/airflow/providers/qubole/example_dags/example_qubole.py) and [documentation](https://github.com/apache/airflow/issues/10929) do not have defects.

Best regards,
Kamil Bregułaa

**Comment by mik-laj** [comment]
@chattarajoy Can you look at it?

**Comment by chattarajoy** [comment]
Sure @mik-laj , we can definitely add a few system tests. Please assign it to me

**Comment by eladkal** [comment]
Closing in favor of https://github.com/apache/airflow/issues/22460
