### ISSUE TITLE
Warn about potential hash collisions in serialized_dag

### ISSUE THREAD

**Issue by anitakar** [apache/airflow#10946]
**Description**

Currently there is a small possibility of hash collision for serialized dags: https://github.com/apache/airflow/blob/master/airflow/models/serialized_dag.py#L112.

Maybe it is theoretical but dag code has logic to warn about those: https://github.com/apache/airflow/blob/master/airflow/models/dagcode.py#L103

Maybe we should implement logic for that?

**Use case / motivation**

Get warned that 2 dags give the same hash.

**Related Issues**

**Comment by potiuk** [comment]
That's a good question indeed

I think the probability of that accidentally happening is really low MD5 = 1.47*10^-29. This is is really, really low probability that changed DAG will have the same hash as the previous one is negligible.  

Of course, when you repeat it 10^x  times, it will happen eventually but let's do back of the back-of-the-envelope calculation on this:

Assume you have 10.000.000 installations of Airflow all over the world. Each of them has 1.000 DAGs, each DAG changes 1.000 times a day (that is really, really high end). Result: We have 10.000.000.000.000 changes in DAGs a day - 10^13 changes a day. We only care about collisions within a single DAG for each change (there is no problem if two DAGs have the same hash or if the same DAG changes back to a hash that it had in the past) so no B-day paradox or any such applies. We are really interested in what is the probability of one of those changes leading to a hash collision.

We would have to wait, 10^16 days so ~ 2.73790926 × 10^13 years for the collision to occur. And if it does occur, there is a super-easy way to recover (add space to DAG).

I'd love if someone checks my math but, if it is sound, I think we are pretty safe :)
