### ISSUE TITLE
Airflow  has snakebite as [hdfs] extra dependency in 1.10.12 for python 3 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10940]
**What happened**:

For python 3 we should use snakebite-py3 as [hdfs] extra dependency as snakebite does not work with python 2. We already do that in master bu we should also change it for 1.10.

**What you expected to happen**:

It has to use snakebite-py3 in python 3.

**Comment by kaxil** [comment]
PR: https://github.com/apache/airflow/pull/12340

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/12340
