### ISSUE TITLE
Pendulum 1.x drop warning 

### ISSUE THREAD

**Issue by heavelock** [apache/airflow#10952]
**Description**

Airflow 2.x switched major version of Pendulum to ~2.0. Pendulum 2.0 introduced quite a few breaking changes in their API in parts that users can face while creating DAGs. 

I search through the master branch and there seem to be no mention in the code, nor in the documentation about that change or any other dependency major version change. 
Also, UPDATING.md does not include any mention of that.

**Use case / motivation**

I am using a lot of execution_date instances in my DAGs. I have no idea how much is that used among the community but migrating to Airflow 2.x will break my dags just on usages of pendulum's API. 

I have no idea what kind of warning you would like to issue, but for sure UPDATING.md needs a mention about that issue. 

**Related Issues**

https://github.com/apache/airflow/pull/9184/files
https://github.com/apache/airflow/blob/master/UPDATING.md#airflow-master

**Comment by eladkal** [comment]
This will be listed in the [changelog](https://github.com/apache/airflow/blob/master/CHANGELOG.txt) for the relevant release

**Comment by eladkal** [comment]
closing as no further action is needed.
