### ISSUE TITLE
Refresh Airflow UI

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#10953]
**Description**

As the Airflow 2.0 is coming nearer it would be awesome to **refresh** the Airflow WebUI. By this it mostly means:
- using some "modern colors" (how about Airflow logo palette?)
- fixing some padding/spacing
- and other small HTML / CSS touches 

**Use case / motivation**

The main point is to **refresh** the look, not to rewrite the Web UI.

**Related Issues**

Apache Airflow brand book: https://cwiki.apache.org/confluence/display/AIRFLOW/Brandbook

I'm far away from being a frontend expert but removing the "Airflow green" gives a good impression I think:

<img width="2560" alt="Screenshot 2020-09-14 at 10 45 22" src="https://user-images.githubusercontent.com/9528307/93226956-2b1fe900-f774-11ea-9b6a-52579f4109c5.png">

**Comment by ashb** [comment]
@ryanahamilton will likely be up for tackling this.

**Comment by ryanahamilton** [comment]
Yes, I'm definitely interested in taking this on—I've got a few ideas brewing.
