### ISSUE TITLE
No response from gunicorn master within 120 seconds After Changing Worker Class

### ISSUE THREAD

**Issue by adamo57** [apache/airflow#10964]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**:
AWS using EKS with ELB
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

webserver stayed up for the 120ish seconds then crashed.

**What you expected to happen**:

I expected the webserver to not crash after the 120ish seconds

I think the issue might be with the gunicorn webserver code not handling the other worker classes properly.

**How to reproduce it**:

Use the stable/airflow helm chart to install airflow at version 7.6.0
In values.yaml, set `AIRFLOW__WEBSERVER__WORKER_CLASS: "eventlet"`

**Anything else we need to know**:

**Comment by rodrigoabdo** [comment]
We are facing the same problem...

**Comment by leodamasceno** [comment]
Same issue here.

**Comment by noniu** [comment]
Same issue here.

**Comment by kosinsky** [comment]
I'm seeing the same for `gevent` too

**Comment by paulsef** [comment]
I had the same issue and noticed in the webserver debug logs that after spinning up the workers they went immediately into refreshing which seems to cause a crash eg:

```
[3 / 4] some workers are starting up, waiting...
[4 / 4] sleeping for 120s starting doing a refresh...
[4 / 4] doing a refresh of 1 workers
[4 / 5] some workers are starting up, waiting...
...
[5 / 5] killing 1 workers
Handling signal: ttou
Worker exiting (pid: 164)
No response from gunicorn master within 120 seconds
```

I was able to work around this by setting `worker_refresh_batch_size` and `worker_refresh_interval` to 0.

**Comment by Marzocchi666** [comment]
> I had the same issue and noticed in the webserver debug logs that after spinning up the workers they went immediately into refreshing which seems to cause a crash eg:
> 
> ```
> [3 / 4] some workers are starting up, waiting...
> [4 / 4] sleeping for 120s starting doing a refresh...
> [4 / 4] doing a refresh of 1 workers
> [4 / 5] some workers are starting up, waiting...
> ...
> [5 / 5] killing 1 workers
> Handling signal: ttou
> Worker exiting (pid: 164)
> No response from gunicorn master within 120 seconds
> ```
> 
> I was able to work around this by setting `worker_refresh_batch_size` and `worker_refresh_interval` to 0.
> 
> This was using gevent as well on airflow 1.10.10

interesting, because if you switch worker_refresh_batch_size to 0 means disable the refresh.

**Comment by raj-manvar** [comment]
We are also facing similar issue and seeing that soon after all workers start, it goes into refresh state.
```
[2021-01-19 09:52:31,771] {cli.py:979} DEBUG - [5 / 5] Killing 1 workers
[2021-01-19 09:52:31 +0000] [66] [INFO] Handling signal: ttou
[2021-01-19 09:52:31 +0000] [124] [INFO] Worker exiting (pid: 124)
```
Though in out case we see the gunicorn master not responding error and consequently restart of webserver much later ( after an hour or so, also one hour duration isn't fixed )

**Comment by abdullahodibat** [comment]
also having same issue:
`docker_airflow_airflow-webserver_1 | [2021-02-01 15:58:31,286] {webserver_command.py:218} ERROR - Shutting down webserver
docker_airflow_airflow-scheduler_1 | [2021-02-01 16:00:57,573] {scheduler_job.py:1772} INFO - Resetting orphaned tasks for active dag runs`

i followed instructions here: http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/start/docker.html

**Comment by shinexia** [comment]
i got the same issue
`
$ tail -n 5 airflow-webserver.log
2021-01-27 21:16:06,457 INFO - Received signal: 15. Closing gunicorn.
2021-01-27 21:20:33,961 INFO - Received signal: 15. Closing gunicorn.
2021-01-28 10:40:02,935 INFO - Received signal: 15. Closing gunicorn.
2021-02-04 09:17:43,544 ERROR - No response from gunicorn master within 120 seconds
2021-02-04 09:17:43,545 ERROR - Shutting down webserver
`

`
$ airflow info   
Apache Airflow [1.10.14]

Platform: [Linux, x86_64] uname_result(system='Linux', node='xxx', release='5.4.0-65-generic', version='#73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021', machine='x86_64', processor='x86_64')
Locale: ('en_US', 'UTF-8')
Python Version: [3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]]
Python Location: [/opt/airflow/venv/bin/python]

git: [git version 2.25.1]
ssh: [OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020]
kubectl: [NOT AVAILABLE]
gcloud: [NOT AVAILABLE]
cloud_sql_proxy: [NOT AVAILABLE]
mysql: [mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))]
sqlite3: [3.31.1 2020-01-27 19:55:54 3bfa9cc97daxxxxxx117345eeb516eaa837balt1]
psql: [NOT AVAILABLE]


Executor: [LocalExecutor]
SQL Alchemy Conn: [mysql://xxx:xxx@xxx:3306/airflow]
DAGS Folder: [/opt/airflow/dags]
Plugins Folder: [/opt/airflow/plugins]
Base Log Folder: [/opt/airflow/logs]
`

**Comment by udaygreddy** [comment]
I have the same issue

**Comment by ns-mkusper** [comment]
Encountering this issue with 1.10.15 with slightly different behavior: I hit the error usually within 2--3m of launching a container running the airflow webserver with all default configuration options concerning the gunicorn worker configuration. In my case decreasing the number of workers from 4 (default) to 2 does not seem to impact this issue, but setting the values of both`worker_refresh_batch_size` and `worker_refresh_interval` to 0 does indeed seem to stop it from happening.

**Comment by jonathonbattista** [comment]
For us, Kubernetes was killing the pods (contrary to what the logs seem to indicate). I am betting **Received signal: 15. Closing gunicorn. means 15** is a shutdown/terminate signal. Increasing the **initialDelaySeconds** of the Liveness Probe fixed it.

**Comment by eladkal** [comment]
Is this issue happens in latest airflow version? If so please add updated reproduce steps

**Comment by LainerDonet** [comment]
I feel this issue has to be relate with python version and apache airflow version. I had the same issue.

**Comment by potiuk** [comment]
@LainerDonet - if you have this on latest version of Airlfow please report it with all details, logs etc.

**Comment by LainerDonet** [comment]
> @LainerDonet - if you have this on latest version of Airlfow please report it with all details, logs etc.
I had some problem without a concrete solution. They consolé show something related with gnircorn. I don't no remember well. Also I can't resolved the error. They solution for me was make environment with python 3.9 instead python 3.10 and the last versión of apache airflow.

**Comment by pankajastro** [comment]
I also had the same issue on the latest main, increasing the container resources fixed it.

**Comment by potiuk** [comment]
> I also had the same issue on the latest main, increasing the container resources fixed it.

Yep. that could be a reaosn - not enough resources might cause exactly this klind of problem.

**Comment by y3boy** [comment]
@potiuk Thx. I incresead resources and now airflow working correnctly.

**Comment by rfs-lucascandido** [comment]
I have the same problem, on a single machine running the container, even good settings for the 2vCPUs 8GB Ram application, but I can't succeed

`[2023-03-09 10:00:46,553] {webserver_command.py:222} ERROR - No response from gunicorn master within 120 seconds
[2023-03-09 10:00:46,554] {webserver_command.py:223} ERROR - Shutting down webserver`

**Comment by potiuk** [comment]
8GB might be not enough if you have many things running . We recommend for "no load" airflow in docker compose to have at least 4GB. If you have UI/other stuff running on the same machine, the running processes **might** take memory. And they might cause webserver to continue swapping on disk for example. 

Or you might have other resource problem

Or your database is run on the same machine and is taking cpu and memory

Or it is run on a really slow disk that other processes might use

Or .....

**Comment by potiuk** [comment]
Did you check any of the other resource issues I mentioned? are you sure your aiflow installed has all the resources it needs?Are you sure you are not running it in resource constrained environment? 

Did you read any of the previous suggestions for you to check that I gave?

**Comment by potiuk** [comment]
So - what is the result of your investigation on resources ? Did you check which one is causing problem ?

**Comment by Tsovinar1986** [comment]
https://github.com/apache/airflow/issues/10964?ysclid=lp85hj7dwb989131746#issuecomment-721729917

**Comment by Tsovinar1986** [comment]
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Tsovinar1986** [comment]
ERROR - No response from gunicorn master within 120 seconds
ERROR - Shutting down webserver

**Comment by tharhtetsan** [comment]
I am facing the same issue. when I set `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://`
`airflow db init` is work. But I cann't start webserver with ` airflow webserver --port 8080`
```
ERROR - No response from gunicorn master within 120 seconds
ERROR - Shutting down webserver
```

**Comment by potiuk** [comment]
I have the same request to both of you @Tsovinar1986 @tharhtetsan 

> Did you check any of the other resource issues I mentioned? are you sure your aiflow installed has all the resources it needs?Are you sure you are not running it in resource constrained environment?

> Did you read any of the previous suggestions for you to check that I gave?

**Comment by potiuk** [comment]
Nothing changed since last advice of mine and if the only thing you can post "I have the same error", the advice and questions apply to both of you in the same way @tharhtetsan @Tsovinar1986 - adding - "I have the same problem" without following the request to do more investigation and provide more information does not make anyone closer to solve the problem.

**Comment by Tsovinar1986** [comment]
No i have done airflow-hone=. For it to be on my folder which i eNt installs normal migrate db does users create goes well but webserver doesn’t work even tried making virtual environment than do steps stops at webserver partSent from my iPhoneOn 22 Nov 2023, at 13:16, Jarek Potiuk ***@***.***> wrote:﻿
I have the same request to both of you @Tsovinar1986 @tharhtetsan

Did you check any of the other resource issues I mentioned? are you sure your aiflow installed has all the resources it needs?Are you sure you are not running it in resource constrained environment?


Did you read any of the previous suggestions for you to check that I gave?

**Comment by potiuk** [comment]
I suggest you do then . Likely you lack resources to run airflow

**Comment by Tsovinar1986** [comment]
With a django it goes well while ebserver localhost entwrs but with airflow noSent from my iPhoneOn 22 Nov 2023, at 18:37, Jarek Potiuk ***@***.***> wrote:﻿
I suggest you do then . Likely you lack resources to run airflow

**Comment by tharhtetsan** [comment]
Hello @potiuk   I read the recommendations and I tested various ways.
I also checked with these commands for db connections. And all commands are success.
```
airflow db check
airflow db init
airflow db migrate
```
But when I run with `airflow webserver -p 8080`
```
ERROR - No response from gunicorn master within 120 seconds
ERROR - Shutting down webserver
```

**Comment by potiuk** [comment]
Still the same. What about your resources? I am afrain no-one can help if you won't provide more details.

**Comment by tharhtetsan** [comment]
When I run with  `AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://`, it show following user UserWarning. 
So I setup my database server with high compute resources, but it still not work.

Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.

**Comment by potiuk** [comment]
> /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.

Update your config then. You are using a deprecated one (see the docs they explain which one you should use)

> Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: [https://flask-limiter.readthedocs.io#configuring-a-storage-backend](https://flask-limiter.readthedocs.io/#configuring-a-storage-backend) for documentation about configuring the storage backend.

You can configure rate limiting following those docs, it does not change much 

None of this bring us any closer to finding out what happens in your case @tharhtetsan , And likely commenting on a close isssue is not a good idea. I recommend you to do one of two things:

1) open a separate discussion where you explain what your problem is, describe your environment, how you are running and installing airflow, what kind of resources you have  and results of your check if you do not lack any of those (memory, cpu, IO, networking etc.)

2) Do the same but in Slack #troubleshooting  channell (you wil find links to our slack in the `community` section of our documentation.

**Comment by tharhtetsan** [comment]
Thank for your support. Sure I opened as a new issue in [here](https://github.com/apache/airflow/issues/35938)

**Comment by ramkunwarmeghwal** [comment]
Installed latest airflow version(2.7.3) and python version is 3.10, airflow is working fine when sqlite database is using, when set mysql database(aws rds), airflow webserver stop working and error is  database successfully initialize the error is 
`No response from gunicorn master within 120 seconds` 
I run these commands
```
aiflow db migrate
airflow webserve
```r

**Comment by ramkunwarmeghwal** [comment]
> Any more details and logs ? without it it's not bringing us any closer @ramkunwarmeghwal
I attached sc of airflow webserver

**Comment by potiuk** [comment]
You likely have some misconfiguratio of your db. But no idea what it is - without details it's hard to say. What I'd do I would start tracking what is happening in your DB, whether the webserver actually connects there - use airflow CLI to see whether it works.

If everything works except your webserver and from the same machine you can sun all other `airflow` CLI then also look at webserver config and experiment with configuration of webserver - it could be that  drivers you use for mysql clash with some of the ways gunicorn stars (gevent and the like). Also maybe try using different mysql driver - look at sqlalchemy docs

**Comment by potiuk** [comment]
Generally experiment with different settings - without it's impossible to gues what's wrong with your setup

**Comment by ramkunwarmeghwal** [comment]
Thanks @potiuk , solved this problem, increased timeout in airflow.cfg file  `web_server_master_timeout = 300` and `web_server_worker_timeout = 300`

**Comment by cheeyeelim** [comment]
> ![Screenshot (905)](https://private-user-images.githubusercontent.com/60502249/290260010-b547f26f-6779-453a-97b7-9ac96f28882d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzY2OTYsIm5iZiI6MTcwNzQ3NjM5NiwicGF0aCI6Ii82MDUwMjI0OS8yOTAyNjAwMTAtYjU0N2YyNmYtNjc3OS00NTNhLTk3YjctOWFjOTZmMjg4ODJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDEwNTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTI0NGI3MjA5ZWE3MDQwNzg5ZjM0Y2QwOWNkN2ZhOGFlOWVhNjFlNWQ2ZTVmZDRlZjEzNDNiMTExM2E4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvl_tfrIhUtOEjF-4ejAk5A9abWSNoLWFAJZXIvznFc) I attached sc of airflow webserver

I faced the same issue with the same log, using the official Airflow docker following the official setup documentation [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html).

The webserver shutdown error only happened when Airflow was started up for the first time, while `override.py` is still running. The webserver works normally for me once `override.py` finished running after a few minutes.
