### ISSUE TITLE
Changes in scripts for worfklow_run might cause unexpected failures for not rebased PRs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10984]
We need to make sure that changes to "scripts" will not be a problem for non-rebased commits

**Apache Airflow version**: master /v1-10-test

**What happened**:

When we introduce changes to scripts building image, this is is not obvious how they will work for non-rebased commits. We are using the "workflow_run" type of workflow which builds the images and it uses scripts from master to build images from the PR (the main reason for that is security - so that PRs cannot "inject" any code into the build process without a review.

The problem is that when such change is merged to master, it start bein used for all PRs also those that are not rebased yet. In such case "master" scripts are used to build "pre-master" images. It already caused some problems: For example #10943 caused not rebased PRs to fail. 

**What you expected to happen**:

Merging a new version of scrips should not fail recent non-rebased PRs. 

It should be entirely possible to simulate such a situation in CI before merging such change. We should simply test if a new version of scripts is backwards compatible and if it can build the image from parent commit.

**Anything else we need to know**:

**Comment by OmairK** [comment]
@potiuk Any way I can help with this CI issue?

**Comment by potiuk** [comment]
This is not a programming problem it's more of lack of (at least some time ago) an information about merge commit that should be used to build the image. The thing to impleentt here is to make a merge of an incoming commit with the target one. I think it should be rather easy by running appropriate git merge  command before the build. We have both commits - the  source and target one so it should be possible.

**Comment by potiuk** [comment]
This has been fixed already.,
