### ISSUE TITLE
MSSQL via ODBC has string type mismatch for sqlalchemy queries vs alembic table creation

### ISSUE THREAD

**Issue by alexmc-ms** [apache/airflow#10982]
Apache Airflow version:
1.10.9, 1.10.11

Kubernetes version (if you are using kubernetes) (use kubectl version):
N/A

Environment:

Cloud provider or hardware configuration: Azure
OS (e.g. from /etc/os-release): Debian9
Kernel (e.g. uname -a): custom Linux
Database: MSSQL ODBC
Install tools:
Others:

What happened:

Running initdb produces tables that have string columns as type VARCHAR.  All Airflow queries produce string types as NVARCHAR.  As might be expected, this makes all queries very expensive since query indexes can't be used.

What you expected to happen:

Expectation is by default the alembic migrations called by initdb will use the same string datatype when setting up the initial tables that Airflow queries will use when querying the database.

Is there some flag to force this?

Is the best workaround to have alembic produce the SQL, change all the VARCHARs to NVARCHARs, and then apply the script manually?

How to reproduce it:

1. Start with a blank db
2. Run 'airflow initdb'
3. Run any Airflow query
4. View the query in MSSQL

Anything else we need to know:

sql_alchemy_conn=mssql+pyodbc://{username}:{password}@{server}:1433/{database name}?driver=ODBC+Driver+17+for+SQL+Server

**Comment by JeffryMAC** [comment]
@alexmc-ms there were some discussions around mssql it's not supported official as backend (see https://github.com/apache/airflow/issues/10713 )
You can patch a fix and PR it

**Comment by alexmc-ms** [comment]
I better understand this problem now.  I can patch it on my end, but it's not an easy fix to generalize for a PR.  Basically, for MSSQL all String types in the alembic migrations would need to become Unicode.  Similarly, the Celery tables would need to be patched with String changed to Unicode.

I am following up on #10713 to see where I can assist with better support for MSSQL.
