### ISSUE TITLE
User should be marked inactive if there are no Roles assigned to the user.

### ISSUE THREAD

**Issue by sumyan** [apache/airflow#11007]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**: Docker container

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 4.15.0-1065-aws
- **Kernel** (e.g. `uname -a`): Linux a9b9111a4c11 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 GNU/Linux
- **Install tools**: NA
- **Others**: NA

**What happened**:
web ui turns unavailable with blank page when user tries login, if user does not have any roles assigned.

**What you expected to happen**:
User should see some error message stated that the user is inactive and does not have access to web ui.

**How to reproduce it**:
In Security menu/List users. Click modify user and remove existing role.

**Anything else we need to know**: NA

**Comment by mik-laj** [comment]
This looks like a Flask AppBuilder problem. Can you also open a ticket for FAB?
https://github.com/dpgaspar/Flask-AppBuilder/issues
