### ISSUE TITLE
Airflow mixing up tasks from 2 different zipped DAGs

### ISSUE THREAD

**Issue by abhilash1in** [apache/airflow#11003]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: Local machine
- **OS** (e.g. from /etc/os-release): macOS Catalina
- **Kernel** (e.g. `uname -a`): `Darwin Abhilashs-MBP 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_6`
- **Install tools**:
- **Others**:

**What happened**:

Created two zipped DAGs as follows:

1. **sample-dag-test.zip**
Contents:
**sample-dag-test.zip/sample_dag/configs/config.py:**
```
env = 'test'

servers = [
    f'server1-{env}',
    f'server2-{env}'
]
```

**sample-dag-test.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from sample_dag.configs import config

with DAG('sample-dag-test',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    for server in config.servers:
        task = DummyOperator(task_id=f'task_{server}')
```

2. **sample-dag-prod.zip**
Contents:
**sample-dag-prod.zip/sample_dag/configs/config.py:**
```
env = 'prod'

servers = [
    f'server1-{env}',
    f'server2-{env}'
]
```

**sample-dag-prod.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from sample_dag.configs import config

with DAG('sample-dag-prod',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    for server in config.servers:
        task = DummyOperator(task_id=f'task_{server}')
```

Airflow parsed the two zipped DAGs as follows:

![Screen Shot 2020-09-17 at 4 37 48 PM](https://user-images.githubusercontent.com/9111980/93538925-330e9300-f904-11ea-8529-3c65952cc9ed.png)
![Screen Shot 2020-09-17 at 4 39 27 PM](https://user-images.githubusercontent.com/9111980/93538986-5fc2aa80-f904-11ea-9c7c-282db822fe90.png)

`sample-dag-test` has `-prod` tasks which is wrong! (`sample-dag-prod` has `-prod` tasks which is correct).

**What you expected to happen**:

Airflow should create `sample-dag-test` DAG with only `-test` tasks and `sample-dag-prod` DAG with only `-prod` tasks.

**How to reproduce it**:
As described above.

**Anything else we need to know**:
- In a different installation of Airflow with slightly different DAG structures (different operators instead of `DummyOperator`) , `-prod` DAG had `-test` tasks and `-test` DAG also had `-test` tasks. Inverse of what is described above.
- No errors in webserver and scheduler logs.

**Comment by mik-laj** [comment]
Is it related? 
https://github.com/apache/airflow/issues/10616

**Comment by cchepelov** [comment]
Good catch @mik-laj, it seems quite similar indeed

@abhilash1in , can you test whether #10617 solves the issue for you?

**Comment by eladkal** [comment]
Due to comments on https://github.com/apache/airflow/pull/10617 it might be that this issue is Airflow 1.10 specific

Please check against latest Airflow version. If the issue is reproducible we can revisit it.
