### ISSUE TITLE
Airflow unable to find zipped DAG with dynamic dag_id 

### ISSUE THREAD

**Issue by abhilash1in** [apache/airflow#11006]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: Local machine
- **OS** (e.g. from /etc/os-release): macOS Catalina
- **Kernel** (e.g. `uname -a`): `Darwin Abhilashs-MBP 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_6`
- **Install tools**:
- **Others**:

**What happened**:
Created two zipped DAGs as follows:

1. **sample-dag-test.zip**
Contents:
**sample-dag-test.zip/sample_dag/configs/config.py:**
```
env = 'test'
```

**sample-dag-test.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from sample_dag.configs import config

with DAG(f'sample-dag-{config.env}',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    task = DummyOperator(task_id=f'dummy_task')
```

2. **sample-dag-prod.zip**
Contents:
**sample-dag-prod.zip/sample_dag/configs/config.py:**
```
env = 'prod'
```

**sample-dag-prod.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from sample_dag.configs import config

with DAG(f'sample-dag-{config.env}',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    task = DummyOperator(task_id=f'dummy_task')
```
Both DAGs are listed on the home page (`/admin/`):

![Screen Shot 2020-09-17 at 5 48 13 PM](https://user-images.githubusercontent.com/9111980/93542487-052e4c00-f90e-11ea-9ad2-6ea8bd6ad41c.png)

When I click on `sample-dag-prod`, I'm able to view it (`/admin/airflow/tree?dag_id=sample-dag-prod`). 

![Screen Shot 2020-09-17 at 5 44 42 PM](https://user-images.githubusercontent.com/9111980/93542442-e334c980-f90d-11ea-941b-8798c7d54beb.png)

However, when I click on `sample-dag-test`, Airflow says `DAG "sample-dag-test" seems to be missing.`
![Screen Shot 2020-09-17 at 5 44 57 PM](https://user-images.githubusercontent.com/9111980/93542443-e465f680-f90d-11ea-9ef2-44007d458d0d.png)

**What you expected to happen**:
I should be able to view and run both DAGs.

**How to reproduce it**:
As described above.

**Anything else we need to know**:
- Happens every time.
- No errors in webserver and scheduler logs.
- This does not happen when the `env` variable is embedded within the DAG and not read from a separate package.

Example:
**sample-dag-test.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator

env = 'test'
with DAG(f'dag-{env}',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    task = DummyOperator(task_id=f'dummy_task')
```
**sample-dag-prod.zip/dag.py:**
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator

env = 'prod'
with DAG(f'dag-{env}',
         schedule_interval='0 12 * * *',
         start_date=datetime(2020, 9, 17), catchup=False) as dag:
    task = DummyOperator(task_id=f'dummy_task')
```

Both DAGs are visible in the UI and I'm able to click on both and view the tree view.

**Comment by eladkal** [comment]
This issue is reported against an end-of-life version of Airflow.
if the issue still happens on latest Airflow version please comment and we will revisit.
