### ISSUE TITLE
Deprecate DagModelView and replace with existing DAG Details page

### ISSUE THREAD

**Issue by abridgett** [apache/airflow#1100]
Both the "is paused" and "scheduler lock" buttons on DAG edit (i.e. the (i) button from the homepage) fail to work for me.  

I think this is due to airflow/www/views.py setting them as disabled.  For "is_paused" this was done in a27d11068dcd6d46703d27f2d4d25911f0b9693a  FYI.

For pausing the on/off button on the home screen works fine and seems to do exactly the same thing.

Doesn't fix scheduler lock, but perhaps removing is_paused (or hiding it until a better non-flickering solution is found would be a good idea.  Not that I see any flickering FWIW.

**Comment by r39132** [comment]
Adding an image of the disabled controls mentioned above : Image below of the screen launched by clicking the info button on the Home Screen.
<img width="1079" alt="screenshot 2016-03-01 16 00 18" src="https://cloud.githubusercontent.com/assets/581734/13446257/b86d892c-dfc6-11e5-81c6-323d8b722ac1.png">

**Comment by mistercrunch** [comment]
all of this is meant to be read-only. is_paused should be interacted with in the main DAGs page, and scheduler_lock will be used by the different schedulers  to not step on each other's toes.

**Comment by abridgett** [comment]
Aaaah!  That'd explain it :-D  Trying to figure out how to make that obvious.

Whilst you get here by clicking on "(i)" info button, the URL is /edit/ and the save/save&continue/cancel buttons could be replaced wth just "OK".

https://github.com/airbnb/airflow/issues/174 you actually mention this too if I've read it correctly :-)

**Comment by mistercrunch** [comment]
Yeah we should just deprecate this page and use the DAG details page for all this.
