### ISSUE TITLE
RBAC UI: Editing dag runs gives forbidden page when admin

### ISSUE THREAD

**Issue by stijndehaes** [apache/airflow#11014]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.17

**Environment**: Running. on kubernetes 

- **Cloud provider or hardware configuration**: Aws EKS on kubernetes
- **OS** (e.g. from /etc/os-release): NA
- **Kernel** (e.g. `uname -a`): NA
- **Install tools**: NA
- **Others**: NA

**What happened**:

When editing a dag run as admin in the RBAC ui I always get a forbidden page.

**What you expected to happen**:

To be able to edit the dag run.

**How to reproduce it**:
Just enabled the RBAC UI and edit a dag run. 

Example video:
https://youtu.be/nJPor3nUFrk

**Anything else we need to know**:
On the webserver the following log can be found:
```
[2020-09-18 14:42:15,160] {decorators.py:111} WARNING - Access is Denied for: can_edit on: DagModelView
```

**Comment by kaxil** [comment]
Yes that button will be removed as part of https://github.com/apache/airflow/pull/11026
