### ISSUE TITLE
Local unit tests don't work out of the box anymore with default LocalExecutor

### ISSUE THREAD

**Issue by thoralf-gutierrez** [apache/airflow#1102]
Hey guys,

I see you've changed the default Executor for unit tests from `SequentialExecutor` to `LocalExecutor` in the recent PR https://github.com/airbnb/airflow/pull/1051.

In the current state, if someone does a fresh install of airflow and tries to run the tests as explained in [CONTRIBUTING.md](https://github.com/airbnb/airflow/blob/master/CONTRIBUTING.md), he'll get the following error because `LocalExecutor`s aren't allowed with the default sqlite backend for unit tests.

```
======================================================================
ERROR: Failure: AirflowConfigException (error: cannot use sqlite with the LocalExecutor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/thoralf/RIA/airflow_test/airflow/__init__.py", line 14, in <module>
    from airflow import configuration as conf
  File "/Users/thoralf/RIA/airflow_test/airflow/configuration.py", line 503, in <module>
    conf.read(AIRFLOW_CONFIG)
  File "/Users/thoralf/RIA/airflow_test/airflow/configuration.py", line 436, in read
    self._validate()
  File "/Users/thoralf/RIA/airflow_test/airflow/configuration.py", line 380, in _validate
    format(self.get('core', 'executor')))
AirflowConfigException: error: cannot use sqlite with the LocalExecutor
-------------------- >> begin captured logging << --------------------
root: INFO: Reading the config from /Users/thoralf/RIA/airflow_test/unittests.cfg
--------------------- >> end captured logging << ---------------------
```

I see the problem was taken care of for the travis build with the following line in `tox.ini`
`airflow_backend_sqlite: AIRFLOW__CORE__EXECUTOR=SequentialExecutor`
But it looks like a similar mechanism was forgotten for local unit tests.

**Comment by nicktrav** [comment]
I tried running this locally with a fresh install / fresh virtualenv and it worked fine for me? The tests are using the sqlite db.

Do you have exact steps to repro?

**Comment by mistercrunch** [comment]
Good catch, I just pushed a quick commit to fix this. I meant to change this only for Travis but changed the default. @nicktrav you probably have a `~/airflow/unittests.cfg` from a previous version
https://github.com/airbnb/airflow/commit/7b66702758d029c36f3a69d426a22f12d43aebbf
