### ISSUE TITLE
Allow custom email backends

### ISSUE THREAD

**Issue by jmcarp** [apache/airflow#1103]
The current `send_email` helper uses SMTP, but sometimes it's useful to be able to send mail without SMTP--for example when using API-based services like Sendgrid, Mailgun, etc. It would be useful to include a hook for overriding `send_email`--maybe a Django-style override like `email_backend = path.to.plugin:send_email`. If folks would be interested, I'm happy to send in a patch for this.

**Comment by mistercrunch** [comment]
Seems reasonable. Good call on mimicking the Django approach.
