### ISSUE TITLE
Create NoAdditionalArgsInOperatorsRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11042]
This issue is part of #8765

## Rule
Create `NoAdditionalArgsInOperatorsRule` which corresponds to
> Additional arguments passed to BaseOperator cause an exception

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by coopergillan** [comment]
@turbaszek - I would like to give this a shot in the next week or two here.

**Comment by turbaszek** [comment]
Hey @coopergillan any update on this one?

**Comment by Dr-Denzy** [comment]
I will like to work on this task.

**Comment by ashb** [comment]
Done in #12660.
