### ISSUE TITLE
Create FernetEnabledRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11048]
This issue is part of #8765

## Rule
Create `FernetEnabledRule` which corresponds to
> Fernet is enabled by default

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by Sangarshanan** [comment]
Can pick this up : )

**Comment by turbaszek** [comment]
@Sangarshanan I assigned you 👌

**Comment by Sangarshanan** [comment]
Heya : ) just wanted to confirm what needs to be done

Check if cryptography is not importable or if fernetkey is empty

Return a message saying that fernet will be enabled by default when upgrading and 
an empty key has to be explicitly set in the ``fernet_key`` option of 
section ``[core]`` in the ``airflow.cfg`` file to retain the current behaviour 

Or am I going about this the wrong way?

**Comment by turbaszek** [comment]
> Return a message saying that fernet will be enabled by default when upgrading and
> an empty key has to be explicitly set in the `fernet_key` option of
> section `[core]` in the `airflow.cfg` file to retain the current behaviour

as per https://github.com/apache/airflow/blob/master/UPDATING.md#fernet-is-enabled-by-default

So we should check if `fernet_key` key in config is empty. If yes we should inform users than when migrating they will have to change it explicitly to empty

**Comment by turbaszek** [comment]
Closed via #11116
