### ISSUE TITLE
Create ChainBetwenDAGAndOperatorNotAllowedRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11040]
This issue is part of #8765

## Rule
Create `ChainBetwenDAGAndOperatorNotAllowedRule` which corresponds to
> Assigning task to a DAG using bitwise shift (bit-shift) operators are no longer supported

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-stable` branch.

**Comment by jmelot** [comment]
Hello, could I please take this one?

**Comment by mik-laj** [comment]
@jmelot I assigned you to this ticket.

**Comment by jmelot** [comment]
Thanks, and sorry for taking so long to follow up. I [implemented a rule](https://github.com/jmelot/airflow/commit/d9a109952d9bec5b7dc6e7db10001dd69a7e796d) for this that parses the text of the files in the dags folder and looks for bitshift operators being used on DAG instances. I keep wondering if I'm missing a better way to do this, though. Would you please take a quick look and see if this is on track, or if there is a different way of detecting this I should be looking at instead?

**Comment by turbaszek** [comment]
@jmelot would you mind opening a PR? This will simplify the review :) Please, target the `v1-10-stable` branch

**Comment by turbaszek** [comment]
Closed via #11839
