### ISSUE TITLE
Create MesosExecutorRemovedRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11043]
This issue is part of #8765

## Rule
Create `MesosExecutorRemovedRule` which corresponds to
> Removal of Mesos Executor

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by RaviTezu** [comment]
Hi @turbaszek I would like to take this up. Could you please assign this to me? Thanks.

**Comment by RaviTezu** [comment]
Thanks @turbaszek 
I see there's a open PR on adding a new mesos executer here https://github.com/apache/airflow/pull/10977 
Do you we will still need this rule ? I just want to check before starting on this. Thanks.

**Comment by mik-laj** [comment]
@RaviTezu Yes. Mesos may be added after the release Airflow 2.0, as we are now focusing on this release and prioritizing the tasks that are related to this release. Adding new features that are not in the roadmap is not essential now, so it may be a bit slower.  Additionally, few core contributors have experience with Mesos, so there is a chance that there will be a problem with the reviewer.  That being said, we should work as planned and add a migration alert.

**Comment by RaviTezu** [comment]
Thanks for the reply @mik-laj 👍

**Comment by RaviTezu** [comment]
@mik-laj @turbaszek Just want to confirm what needs to be done:

- Add a new rule under `airflow/upgrade/rules` with the name something like `mesos_executor_removed.py`
- Include a class which inherits from `BaseRule` and have `title` and `descripption` and override the `check` method. 
- Inside the `check` method look for `mesos` conf and if present then return a string saying - `Mesos has been deprecated` 

Thanks.

**Comment by dimberman** [comment]
@turbaszek @RaviTezu can we close this ticket?

**Comment by RaviTezu** [comment]
@dimberman Yes. I think, it can be closed.

**Comment by turbaszek** [comment]
Done in #11528, thanks!
