### ISSUE TITLE
Create StatNameHandlerNotSupportedRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11045]
This issue is part of #8765

## Rule
Create `StatNameHandlerNotSupportedRule` which corresponds to
> Drop plugin support for stat_name_handler

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by FHoffmannCode** [comment]
Hi, I would like to take this task can you assign me? @potiuk @mik-laj @turbaszek

**Comment by Dr-Denzy** [comment]
I will like take up this task.

**Comment by turbaszek** [comment]
There's already PR fort this #11223

**Comment by eladkal** [comment]
The PR is stale.
@Dr-Denzy would you like to take this one?

**Comment by Dr-Denzy** [comment]
> The PR is stale.
> @Dr-Denzy would you like to take this one?

I am currently neck-deep in some k8s issues but I will be happy to jump in on this once I have more wiggle room.

**Comment by eladkal** [comment]
Closing as there will be no more releases of upgrade check
