### ISSUE TITLE
Create CustomExecutorsRequireFullPathRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11053]
This issue is part of #8765

## Rule
Create `CustomExecutorsRequireFullPathRule` which corresponds to
> Custom executors is loaded using full import path

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by pcandoalmeida** [comment]
Hi @turbaszek could I try working on this?

**Comment by potiuk** [comment]
I assigned you :)

**Comment by turbaszek** [comment]
@pcandoalmeida in case of any questions feel free to ask 👌

**Comment by dimberman** [comment]
Hi @pcandoalmeida have you made any progress on this ticket? If you do not have time I can take it over.

**Comment by pcandoalmeida** [comment]
Hi @dimberman yes by all means!

**Comment by dimberman** [comment]
@turbaszek @kaxil I'm a bit confused by this

https://github.com/apache/airflow/blob/master/airflow/executors/executor_loader.py#L81-L110 Looking at these lines it looks like Airflow 2.0 still allows loading from plugins? Does this need to be an upgrade check or deprecation warning?

**Comment by kaxil** [comment]
@turbaszek Is there a rule to do the same (use normal Python package / modules) for operators and sensors?

I couldn't find one but we removed the support for adding operators and sensors via Plugins so we should have a check for it.

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/13678
