### ISSUE TITLE
Create TaskHandlersMovedRule to ease upgrade to Airflow 2.0

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11051]
This issue is part of #8765

## Rule
Create `TaskHandlersMovedRule` which corresponds to
> GCSTaskHandler has been moved, WasbTaskHandler has been moved, StackdriverTaskHandler has been moved , S3TaskHandler has been moved, ElasticsearchTaskHandler has been moved, CloudwatchTaskHandler has been  moved

entry in UPDATING.md. This rule should allow users to check if their current configuration needs any adjusting
before migration to Airflow 2.0.

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Remember** to open the PR against `v1-10-test` branch.

**Comment by ephraimbuddy** [comment]
I'm interested in this issue

**Comment by ephraimbuddy** [comment]
But it seems like this could be added to the import changes rule PR #11056?

**Comment by turbaszek** [comment]
@ephraimbuddy this is more like about checking that users configuration in airflow.cfg uses old task handlers in `task_log_reader`. Similar to #11067

**Comment by ephraimbuddy** [comment]
Got it

**Comment by ephraimbuddy** [comment]
The remote logging documentation for the stable release is the same as the master documentation.

2.0 doc: https://airflow.readthedocs.io/en/latest/logging-monitoring/logging-tasks.html
stable doc: https://airflow.readthedocs.io/en/stable/howto/write-logs.html

I'm finding it difficult looking for what to check in previous version that has changed in 2.0.
What I have found so far is the change in import path as can be seen here :
https://github.com/apache/airflow/blob/master/UPDATING.md#airflowcontributilslog-has-been-moved.

What do you think?

**Comment by turbaszek** [comment]
> What I have found so far is the change in import path as can be seen here :
> https://github.com/apache/airflow/blob/master/UPDATING.md#airflowcontributilslog-has-been-moved.

That's exactly the change. I see that the UPDATING.md has changed a bit since we created the list of rules... We should check if users configuration uses one of those handlers and warn them that this will change in 2.0

**Comment by ephraimbuddy** [comment]
I'm suggesting that we add it in import change PR #11056  just like we added it in the deprecated classes here:
https://github.com/apache/airflow/blob/51181e885ed82606f1dc2f9c3b52c4b55e29e9f0/tests/deprecated_classes.py#L1783,

This will help us not to duplicate code. What do you think?
https://github.com/apache/airflow/blob/51181e885ed82606f1dc2f9c3b52c4b55e29e9f0/tests/deprecated_classes.py#L1756-L1781

**Comment by turbaszek** [comment]
The difference is that the #11056 is for DAGs, task handlers are used in airflow.cfg that is not validated in #11056 So we need to look for problems in two different places

**Comment by ephraimbuddy** [comment]
Ok. It's clear now

**Comment by turbaszek** [comment]
Closed via #11265
