### ISSUE TITLE
Launch task through Java . Interacting with airflow server through airflow APIs 

### ISSUE THREAD

**Issue by iamon3** [apache/airflow#1105]
We may migrate to airflow if it fulfils our need. 
We use Oozie. We are exploring Airflow as an alternative. In our case, we are launch oozie jobs. In some of jobs launched through oozie i.e. Hadoop jar (java program), the code is written in such a way that, the code communicate to Oozie server though Oozie's APIs. Based on status / condition, we creates oozie tasks object within a program, and submit those to Oozie server at runtime (dynamically) using Oozie APIs. and launch another Oozie sub job.

If we want to achieve the similar scheme in Airflow, please let us the options.

**Comment by dgies** [comment]
What you're describing sounds a lot like Airflow's BranchPythonOperator, possibly combined with sensors such as ExternalTaskSensor or the SubDagOperator.  

Your current system sounds like typical imperative programming: "do X, then if true do Y" while Airflow is closer to a declarative programming environment "Y depends on result being true, result depends on X".  They can do the same things, but some rethinking is necessary to switch between them.

**Comment by bolkedebruin** [comment]
Please use the mailinglist for these kind of questions (apache malinglist). Thanks!
