### ISSUE TITLE
Resuming tasks through intermediate task

### ISSUE THREAD

**Issue by iamon3** [apache/airflow#1106]
In Oozie if an intermediate workflow action fails, we can resume the the failed and subsequent workflow actions and rerun the workflow.  Is similar thing possible in Airflow? I could find the way to execute a single task, but not the subsequent tasks.

e.g, workflow, consist of tasks . T1 - > T2 -> T3 - >T4 -> T5  
Tasks T1 and T2 completes successfully and if task T3 fails. Can I rerun dag by skipping tasks T1, T2, and running tasks T3, T4, T5

**Comment by mistercrunch** [comment]
Yes, this is the default behavior, the scheduler or backfill commands will only run the task instances that have not succeeded before.

**Comment by iamon3** [comment]
I tried backfill as well run, but both seems to be not working. I tried resume dag from the failed task i.e. T3 onwards. When a dag runs, run id is generated.
What I need is to run the failed dag having same run_id.
