### ISSUE TITLE
Stable API dag run query should count total results after filtering

### ISSUE THREAD

**Issue by jhtimmins** [apache/airflow#11074]
Context:
When querying dag runs in the stable API, it is possible to filter by date range and to receive paginated results. Pagination returns a subset of results, but a count of all available results is returned.

Expected behavior:
The total count should take place after filtering by date, and before paginating results.

Actual behavior:
The count is made prior to filtering by date. This means that the total number of accessible dags is returned, rather than the number of dags the user filtered for.

https://github.com/apache/airflow/pull/10594/files/1fe1da978763c9919cee0d2c7eccd96438631993#diff-3239f89a092764597348cabc5e74c2f5R125

I will make this change after #10594 is merged.

**Comment by mik-laj** [comment]
@ephraimbuddy @OmairK  Can you look at it also?

**Comment by ephraimbuddy** [comment]
Ok. Assign to me

**Comment by mik-laj** [comment]
@ephraimbuddy Done
