### ISSUE TITLE
Test that the xcom API endpoint handles joins properly

### ISSUE THREAD

**Issue by jhtimmins** [apache/airflow#11073]
The XCom endpoint joins the XCom and DagRun tables. Currently, the output of the join isn't getting stored as a new `query` variable, as seen in the link to the following PR. We should add a new test to check that these tables are getting joined correctly.

https://github.com/apache/airflow/pull/10594/files/1fe1da978763c9919cee0d2c7eccd96438631993#diff-aa0c2f68c6177fb1587a6de6b5cfb28cR59

I will make these changes after #10594

**Comment by mik-laj** [comment]
CC: @randr97 @ephraimbuddy

**Comment by mik-laj** [comment]
@ephraimbuddy @OmairK  Can you look at it also?

**Comment by OmairK** [comment]
@mik-laj Can you assign me this ticket.

**Comment by mik-laj** [comment]
@OmairK  Thank you for wanting to maintain this code still. I really appreciate it.

**Comment by OmairK** [comment]
@jhtimmins is this issue still relevant after this [change](https://github.com/apache/airflow/pull/10594/commits/bbd08a3c529f7af40842b80c42793b775071743e)?

**Comment by mik-laj** [comment]
I think we need to add unit tests to prevent regression.
