### ISSUE TITLE
BigQueryHook broken by dependency google-cloud-bigquery-datatransfer

### ISSUE THREAD

**Issue by darwinyip** [apache/airflow#11084]
**Apache Airflow version**: 1.10.10

**What happened**:

```
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook
../lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:30: in <module>
    from google.cloud.bigquery import (
E   ImportError: cannot import name ‘DEFAULT_RETRY’
```

A new release of `google-cloud-bigquery-datatransfer` broke `apache-airflow-backport-providers-google==2020.6.24`.

To fix, pin `google-cloud-bigquery-datatransfer==1.1.1`

**Comment by turbaszek** [comment]
@darwinyip would you like to open a PR? Related to #10014

**Comment by mik-laj** [comment]
Can you also provide an error message?  This can help Google search and also fix the problem.

**Comment by darwinyip** [comment]
@turbaszek Looks like its fixed in https://github.com/apache/airflow/blob/master/setup.py#L263
