### ISSUE TITLE
Helm lint for Chart + unexpected EOF

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11092]
Hello,

I heard we have a problem with the Helm Chart on master branch
```
parse error at (airflow/templates/configmap.yaml:69): 
````
This problem is easily detected with `helm lint`. It would be great if we could fix this problem and then add rules to pre-commit checks to prevent regression.
https://github.com/gruntwork-io/pre-commit

CC: @jaketf @dimberman @flvndh

**Comment by turbaszek** [comment]
Related to #11093

**Comment by jaketf** [comment]
@mik-laj I'd like to close this issue as to not cause alarm because it does not affect the apache airflow upstream.
This was an issue in the subrepo pulling process in our other project.
regardless it would be good to have helm linting in pre-commit which is covered under #11093
