### ISSUE TITLE
Add helm chart linting to precommit

### ISSUE THREAD

**Issue by jaketf** [apache/airflow#11093]
**Description**

I'd like to add `helm lint` to the pre-commit for apache airflow
This could run basic linting with some linter values using this existing pre-commit 
https://github.com/gruntwork-io/pre-commit#helm-lint-caveats

**Use case / motivation**
This can help developers catch errors sooner if they accidentally modify the helm chart that causes linter to fail.

cc: @potiuk 

**Related Issues**

**Comment by dimberman** [comment]
@jaketf That's great idea! Feel free to ping me when you have a PR

**Comment by potiuk** [comment]
Ahh. It's already added in #11108 . I missed that one in Airflow to close :)
