### ISSUE TITLE
Add Mac OS tests for Breeze/Pre-commit scripts

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11104]
**Description**

We are using Breeze by developers on Linux and MacOS and they behave slightly differently. 

This is both Bash and Some Posix tools (which are in different versions on Mac than on modern  Linux versions)

GitHub actions support Mac OS builds, so w could run a single, separate workflow on MacOS to only test Breeze's and development environment functionality on Mac. 

**Use case / motivation**

Get more robust MacOS script tests

**Related Issues**

**Comment by potiuk** [comment]
@francescomucio  - are you on MacOS? Maybe that might be an interesting task for you :)

**Comment by francescomucio** [comment]
Nope, I am on Windows 10 +WSL2 :(

**Comment by potiuk** [comment]
Ah. Right :( . Time to dust of my Mac then ;)

**Comment by pcandoalmeida** [comment]
If we listed out the types of tests needed or added specific tests required, I could try and contribute some along with some colleagues if within our reach (maybe as part of Hacktober). Might help us out as we're Mac based. Just an idea!

**Comment by potiuk** [comment]
Cool! I think it should be as easy as running the pre-commit checks (they run most of the scripts anyway under the hood)

**Comment by potiuk** [comment]
Those pre-commits also includes running `./breeze --help-all` so the basic stuff from breeze is also tested this way. 

Howver maybe some of the commands of breeze could be run as well (in two variants - one for Linux and one for Mac):
```
  shell --help
  cleanup-image
  initialize-local-virtualenv
  setup-autocomplete
  stop
  toggle-suppress-cheatsheet
  toggle-suppress-asciiart

  docker-compose help (that one might need more time to run)

  kind-cluster  status
  static-check --help
  static-check all
  test --help

  flags
  help
  help-all
```

**Comment by sunank200** [comment]
I had recently setup test for Mac OS for Breeze/Pre-commit scripts. Can I take this issue and raise the PR @mik-laj @kaxil @potiuk ?

**Comment by potiuk** [comment]
Sure!

**Comment by potiuk** [comment]
Closing as new Breeze is already on the way,
