### ISSUE TITLE
Priority Weight is not being honoured when using celery executor

### ISSUE THREAD

**Issue by brijeshgautam** [apache/airflow#11101]
I was using Airflow 1.10.10 with Celery executor. I defined two dag, each with three task. Same Pool id was used in both dag/task. Pool slot was configured as 3. First DAG (say High_prioirty)was having priroity_weight as 10 for each task. Second DAG (say Low_priority) was having default priority_weight ( that is 1). I submitted first 5 Low_priority Dag. I waited till 3 tasks of low priority were moved into running state. Then I submitted 4 high priority dag. I was expecting when pool slot becomes available in next scheduling round , high priority task should be moved into QUEUING state. But high priority task remain in Scheduling State. I repeated this for 10-15 times and observe same thing each and every time.

However this works fine when I moved to LocalExecutor.
Please suggest fix/workaround for resolving this priority_weight issue in CeleryExecutor.

**Comment by eladkal** [comment]
This issue is reported against 1.10 which reached end of life.
Please check against latest Airflow version and if the issue is still present please add reproduce DAG.
