### ISSUE TITLE
windows python3.8 can't install sasl

### ISSUE THREAD

**Issue by xu-xiang** [apache/airflow#11115]
**Apache Airflow version**:
Master

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
windows 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
python3.8

**What happened**:
```
pip-install-cr_nf0tt\sasl\sasl\saslwrapper.h(22): fatal error C1083: 无法打开包括文 件: “sasl/sasl.h”: No such file or directory

https://stackoverflow.com/questions/63562293/how-to-install-sasl-with-python-3-8

https://www.lfd.uci.edu/~gohlke/pythonlibs/#sasl      (no python3.8)
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Windows is not supported. We recommend using WSL2 to use Airflow on Windows. See: https://github.com/apache/airflow/issues/10388
