### ISSUE TITLE
SqlToS3Operator

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#11128]
Recently, all the Sql-related (mysql, postgres...) operators were merged into one. Applying the same, would be great to have a single SqlToS3Operator, so that you don't have to use MySqlToS3Operator, RedshiftToS3Operator, SnowflakeToS3Operator...

**Comment by manesioz** [comment]
>Recently, all the Sql-related (mysql, postgres...) operators were merged into one

Where is this? When looking for it I still ran into separate MySQL/PostgreSQL/etc db operations/hooks.

**Comment by akocukcu** [comment]
> > Recently, all the Sql-related (mysql, postgres...) operators were merged into one
> 
> Where is this? When looking for it I still ran into separate MySQL/PostgreSQL/etc db operations/hooks.

Hi @manesioz ,
I think for the sql to sql transfer there is => [GenericTransfer](https://github.com/apache/airflow/blob/master/airflow/operators/generic_transfer.py)

and for the hook there is => [DbApiHook](https://github.com/apache/airflow/blob/master/airflow/hooks/dbapi_hook.py)

Btw the name `GenericTransfer` is a little bit general 😊 Maybe `GenericSqlTransfer` would be more clear. 

Anyway, I would like to work on this issue if you think this is still needed @JavierLopezT .

**Comment by JavierLopezT** [comment]
> > > Recently, all the Sql-related (mysql, postgres...) operators were merged into one
> > 
> > 
> > Where is this? When looking for it I still ran into separate MySQL/PostgreSQL/etc db operations/hooks.
> 
> Hi @manesioz ,
> I think for the sql to sql transfer there is => [GenericTransfer](https://github.com/apache/airflow/blob/master/airflow/operators/generic_transfer.py)
> 
> and for the hook there is => [DbApiHook](https://github.com/apache/airflow/blob/master/airflow/hooks/dbapi_hook.py)
> 
> Btw the name `GenericTransfer` is a little bit general 😊 Maybe `GenericSqlTransfer` would be more clear.
> 
> Anyway, I would like to work on this issue if you think this is still needed @JavierLopezT .

Actually, I was referring to this operator:
https://github.com/apache/airflow/blob/master/airflow/operators/sql.py

And yeah, I think it is totally worth it to have this feature, so it would be great if you start working on it.

PS: sorry @manesioz for not answering you, I didn't realize

**Comment by akocukcu** [comment]
@JavierLopezT Great :) I can also give the option to select an [available file format](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) (such as parquet, json, excel ...)
As I see, right now there is only csv option for MySqlToS3Operator.
I would like to work on this. Sorry to disturb you @mik-laj .But could you assign it to me please 🐱

**Comment by eladkal** [comment]
@akocukcu assigned to you

**Comment by samuelkhtu** [comment]
@akocukcu just wondering how's going with the SqlToS3Operator?

**Comment by akocukcu** [comment]
Hi @samuelkhtu . There were some personal obstacles. But I am working on it again.

**Comment by samuelkhtu** [comment]
@akocukcu  of course. Let me know if anything I can help with. Thanks.
