### ISSUE TITLE
Request for feature: show running sensors and operators separately in DAGs list

### ISSUE THREAD

**Issue by hudbrog** [apache/airflow#1114]
I have a request for a small feature. Quite often when I get to work and see that there are some DAGs that have tasks in running state I have to check whether some underlying external ETL jobs have failed and DAGs are stuck at sensors or if we just got more data than usual and everything's ok and it just need time to finish. 
It would be awesome if in overview list running sensors and running everything else would be shown as different circles, that way I could see instantly if the DAG is stuck on sensors or is currently running.

**Comment by bolkedebruin** [comment]
@hudbrog Can you please create a Jira issue for this?

**Comment by hudbrog** [comment]
@bolkedebruin 
Sure, 
https://issues.apache.org/jira/browse/AIRFLOW-73
