### ISSUE TITLE
Cleanup CronJob fails

### ISSUE THREAD

**Issue by alikhtag** [apache/airflow#11146]
**Apache Airflow version**: 1.10.12

**Kubernetes version** : 1.17.9

**Environment**:

- **Cloud provider or hardware configuration**: Azure Kubernetes Service
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**: Helm chart (/chart in repo) 
- **Others**:

**What happened**:
Pod cannot run since `airflow-cleanup-pods` is not in $PATH
```
Error: failed to start container "airflow-cleanup-pods": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"airflow-cleanup-pods\": executable file not found in $PATH": unknown
```

**What you expected to happen**: 
Cleanup job pod runs

**How to reproduce it**:
* Deploy Helm Chart
* Manually trigger `airflow-cleanup ` CronJob 
* See it cannot run since `airflow-cleanup-pods` is not in $PATH

**Comment by alikhtag** [comment]
Found something in `github`, I assume these scripts were not migrated when `Helm` chart was donated by `Astronomer` ? 
https://github.com/astronomer/astronomer-airflow-scripts

**Comment by kaxil** [comment]
thanks for raising the issue, we will take a look into this one.

**Comment by mik-laj** [comment]
@kaxil I assigned you to this issue. Is it ok?

**Comment by mik-laj** [comment]
@kaxil Any progress on this ticket? I can see Helm Chart still using this script which is not available in the official image.
https://github.com/apache/airflow/blob/3970bfad4c878d99adce80a4bfd824a15132a161/chart/templates/cleanup/cleanup-cronjob.yaml#L64
I think it won't be a big problem to add this script as a command to the CLI.
https://github.com/apache/airflow/blob/3970bfad4c878d99adce80a4bfd824a15132a161/airflow/cli/cli_parser.py#L1276
What do you think about it?

**Comment by kaxil** [comment]
PR: https://github.com/apache/airflow/pull/11802
