### ISSUE TITLE
KubernetesPodOperator doesn't support workingDir parameter.

### ISSUE THREAD

**Issue by lgov** [apache/airflow#11168]
**Description**
We use a docker image for a project with multiple pre-built starting scripts included. As part of the dag setup, we need to define which script to start (with the `cmd` parameter), and what the working directory for that script needs to be.

In the Kubernetes Pod specification yaml file we use the `workingDir` key, but as far as I can see that can not be set in the `KubernetesPodOperator` initialization directly.

**Use case / motivation**

I like airflow to support our current Pod definition with all its features, without having to implement a work-around.

Airflow devs have proposed `pod_template_file` as an alternative way to provide the Pod definition, but unfortunately that has a couple of (blocking for us) issues on its own.

**Related Issues**

Not that I could find.

**Comment by mik-laj** [comment]
We do not plan to add new parameters to this operator. We are working on making migrations to `pod_template_file` easier.  If you have problems with pod_template_file please create a separate ticket.
See: https://lists.apache.org/thread.html/rb1bcafea1b8f86e6d155aea7169c05805f7021e90f1636afc8019074%40%3Cdev.airflow.apache.org%3E
