### ISSUE TITLE
Improved health checks

### ISSUE THREAD

**Issue by Alien2150** [apache/airflow#11161]
**Description**

Improve health checks for Airflow

**Use case / motivation**

According to https://airflow.apache.org/docs/stable/howto/check-health.html the health endpoint includes db and scheduler health-information. But the Http code is not usable as a health-basis which is not useful for orchestrating software like Kubernetes.

It think it would be better to add 2 more additional routes: 

* /health/scheduler
* /health/metadatabase 

On top it would be great to utilize Http code as health metric (e.g 200 for healthy and 4xx as unhealthy). In that case it would be possible to let Kubernetes health probes check the http status code in order to restart scheduler for example.

**Related Issues**

**Comment by rootcss** [comment]
@mik-laj Shall I pick this one up?

**Comment by rootcss** [comment]
@kaxil Shall I pick this one up or do we need to analyze this first?

**Comment by mik-laj** [comment]
It's not that easy to implement if we want multiple schedulers. Also, it means that if the webserver doesn't work, we won't be able to check the status of any component. I think we should try to find a better alternative.

**Comment by Alien2150** [comment]
@mik-laj Maybe having metrics - endpoints on each component? In that way each component can be checked and restarted individually on Kubernetes.

**Comment by rootcss** [comment]
What about sending statsd metrics as one of the ways? We can setup alerts on top of collected metrics. I think this one, we should add anyway, since we already have statsd integrated for several things. (in my company, we already use this method to monitor everything related to airflow)

**Comment by Alien2150** [comment]
@rootcss But it's metrics not health checks? Seeing at least 2 problematic things:

1. With your proposed way I would need to map back metrics to health (Just imagine what would happen if the metrics service is not available. Is it then metrics or airflow being down?
2. Also statsd sounds technology-bound solution while http is a very agnostic way?

**Comment by rootcss** [comment]
Totally agree @Alien2150, Statsd is not the best solution for health check but it's good to have since it's being used in other airflow modules. For a full proof health check, we'll need further discussion on it.

**Comment by Alien2150** [comment]
Meanwhile I think a temporary solution could be to run a simple sidecar that map's back the http results to a Kubernetes Probe. Are you folks managing the helm chart as well?

**Comment by mik-laj** [comment]
> Maybe having metrics - endpoints on each component? I

Running an HTTP server on every component to provide metrics sounds like a much better solution to me.  Do we want to continue using a custom JSON view? If we want other tools to be able to integrate with it, and it wasn't just used in the Web UI. I think it is worth thinking about using a common standard e.g. JMX, HTTP.

**Comment by kaxil** [comment]
We should look at integrating Prometheus natively in Airflow for metrics -- I remember creating an Issue (not sure if it was Jira or GH)

**Comment by mik-laj** [comment]
We should find out what Celery's plans are for deeper integration with Kubernetes. It may coincide with our needs.

**Comment by Alien2150** [comment]
@kaxil That would be awesome. Right now the only way doing that is to use the Exporter: https://pypi.org/project/airflow-prometheus-exporter/

**Comment by mik-laj** [comment]
It seems simpler to add a CLI command that will check if the process is healthy. We can be inspired by the Helm Chart, but it doesn't support multiple schedulers yet.
https://github.com/apache/airflow/blob/master/chart/templates/scheduler/scheduler-deployment.yaml#L115-L130

**Comment by Alien2150** [comment]
@mik-laj Looks good. Potentially these values should be adjustable. What do you think?

**Comment by mik-laj** [comment]
Hi.

I made some improvements and we have a health check for each component. This is described in the documentation:
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/logging-monitoring/check-health.html
You can also see it in our `docker-compose.yaml` file.
https://github.com/apache/airflow/blob/master/docs/apache-airflow/start/docker-compose.yaml
I believe that this ticket can now be closed.

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/issues/13838

**Comment by Alien2150** [comment]
Awesome. Thx @mik-laj
