### ISSUE TITLE
Update the GIF on the documentation main page

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11175]
Hello,

The GIF on the main page of the documentation is slightly outdated. I think it's worth updating.
https://airflow.readthedocs.io/en/latest/
![image](https://user-images.githubusercontent.com/12058428/94369128-3bc34e00-00e8-11eb-9256-e72f1b57b90e.png)
The interface has changed a lot so now this gif doesn't show the current state of the interface.

Best regards,
Kamil Breguła

**Comment by Yashs911** [comment]
Hi, @mik-laj I would like to work on this. What changes do I need to make and in which file?

**Comment by mik-laj** [comment]
The interface has changed, so you need to prepare new screenshots and then combine the screenshots into GIFs. It would be fantastic if it had a resolution similar to the original file. The file is available here:
https://github.com/apache/airflow/blob/master/docs/img/airflow.gif

**Comment by mik-laj** [comment]
You can gain an additional point if you prepare a script that will allow us to easily generate a similar GIF from image files and contribute to it.
https://stackoverflow.com/questions/3688870/create-animated-gif-from-a-set-of-jpeg-images

**Comment by mik-laj** [comment]
Blocked by: https://github.com/apache/airflow/pull/11195

**Comment by mik-laj** [comment]
#11195 has been merged, so this issue is unblocked now. 

CC: @ryanahamilton

**Comment by ryanahamilton** [comment]
@Yashs911 are you still looking to work on this? If not, I'll pick it up.
