### ISSUE TITLE
Core operators/hooks import paths according to AIP-21

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11178]
Hello,

Core operators have now moved to new [AIP-21](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths) compliant modules.
In most cases this means that the `_sensor` or `_operator` suffixes need to be deleted from the module name and in place of the old module a class deprecation warning should be added.

After making a change to the `master` branch, the same change should be made in release 1.10. This will allow us to implement an [upgrade vision for Airflow 2.0](https://github.com/apache/airflow/issues/10152) i.e. in the latest 1.10 release, users are updating to the new import paths supported by backport providers.

More discussion: 
https://github.com/apache/airflow/pull/10013

**Comment by kishvanchee** [comment]
Can I work on this? Please correct me if I'm wrong, so each PR should be for one operator right?

I see there are many files to be edited. I hope I'm searching for the right files.

```shell
[kishore@arch airflow]$ find providers/ -wholename "*/operators/*.py" | grep -v '__init__.py' | wc -l
121
[kishore@arch airflow]$ find providers/ -wholename "*/sensors/*.py" | grep -v '__init__.py' | wc -l
53
```

**Comment by mik-laj** [comment]
@kishvanchee  This should be done for all modules, so each PR can touch one or more modules. I think it's worth starting with preparing a list comparing the old path to the module and the new one.

**Comment by mik-laj** [comment]
Here is list: 
   1 airflow/operators/dagrun_operator.py
   1 airflow/operators/dummy_operator.py
   1 airflow/operators/generic_transfer.py
   1 airflow/operators/latest_only_operator.py
   1 airflow/operators/subdag_operator.py
   1 airflow/sensors/base_sensor_operator.py
   1 airflow/sensors/date_time_sensor.py
   1 airflow/sensors/external_task_sensor.py
   1 airflow/sensors/smart_sensor_operator.py
   1 airflow/sensors/sql_sensor.py
   1 airflow/sensors/time_delta_sensor.py
   1 airflow/sensors/time_sensor.py
   1 airflow/sensors/weekday_sensor.py

**Comment by kishvanchee** [comment]
So if I understand this correctly, these should go from `airflow/operators/<operator>_operator.py` to `airflow/operators/<operator>.py` and `airflow/operators/<operator>_operator.py` would raise the deprecation error. Right? Similarly for sensors.

**Comment by mik-laj** [comment]
Yes.Yes. Hooks also need to be updated but forgot to add them to the list.

You need to additionally update the tests, because we build documentation and guides based on this.
https://github.com/apache/airflow/blob/master/tests/deprecated_classes.py
https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py

**Comment by mik-laj** [comment]
This is not critical, but it would be great if we could close this ticket before the release of the first alpha version of Airflow 2.0. There is an active contributor to do this, but it would be helpful to support with quick review.

CC: @kaxil

**Comment by kishvanchee** [comment]
@mik-laj Any suggestions for renaming `airflow/operators/generic_transfer.py` ? Does `branch_operator.py` require a change too?

**Comment by kaxil** [comment]
@mik-laj Do we need this issue for 1.10.13? Since even in Airflow 2.0 we just raise deprecation warning, I think it should be ok to leave it out of 1.10.13, WDYT ?

**Comment by mik-laj** [comment]
@kaxil It is not required. We can do it in Airflow 2.0 only.

**Comment by ashb** [comment]
After 11178 is merged the last ones are

- [ ] airflow/operators/branch_operator.py
- [ ] airflow/operators/subdag_operator.py

**Comment by kaxil** [comment]
@ashb Updated https://github.com/apache/airflow/pull/11307 -- Rebased and replaced few more places

**Comment by kurtqq** [comment]
I think there are more for example :
hooks/base_hook.py
hooks/dbapi_hook.py

**Comment by kurtqq** [comment]
@ashb  Listing some more:

- [ ] sensors/external_task_sensor.py
- [ ] sensors/sql_sensor.py 
- [ ] sensors/weekday_sensor.py 
- [ ] sensors/smart_sensor_operator.py

**Comment by ashb** [comment]
> @ashb  Listing some more:
> 
> - [ ] sensors/external_task_sensor.py
> - [ ] sensors/sql_sensor.py 
> - [ ] sensors/weekday_sensor.py 
> - [ ] sensors/smart_sensor_operator.py
> 
> 
> 

Thanks. It appears when I checked last night I forgot sensors and hooks existed. Whoops 😄

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/12927 should take care of that list

**Comment by ashb** [comment]
Done!
