### ISSUE TITLE
Fast spell-check in pre-commits

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11180]
**Description**

We have the spell check implemented in sphinx-build, but I think we can do better. Currently, when you make a spelling mistake in any of the .rst docs you will find out only after you push it and wait for results (> 10 minutes). 

I think spell check is not as demanding when it comes to dependencies and when you modify an .rst or two you should be able to check the spelling really fast during the pre-commit without running the whole documentation build?

The key here is to synchronize the exception list and the "spelling: " directive between sphinx and potential pre-commit.

**Use case / motivation**

I think this can be really demotivating for people who write documentation that they find spelling mistakes a long time after they submitted it. I think fast feedback (preferably at the commit time) is much more encouraging.

Maybe we can find some fast pre-commit additional check that would work in >90% of cases at a pre-commit time? 

I believe the sphinx uses enchant library to do the spell-checking, maybe we can employ it to do a fast check?

It's not something super urgent or extremely important, but it becomes a bit annoying :) and may also discourage people who would like to improve some documentation.

**Comment by potiuk** [comment]
cc: @kaxil @mik-laj -> WDYT ?

**Comment by kaxil** [comment]
Sure yea good idea, I can definitely look at that one once I get some time 👍

**Comment by kaxil** [comment]
Assigning it to me for now, but let me know if someone wants to work on it

**Comment by ashb** [comment]
The current spell check also checks spelling of doc comments right? So we'd still want to keep the existing checks, but just add a quicker failure where we can check .rst files more directly

**Comment by kaxil** [comment]
> The current spell check also checks spelling of doc comments right? So we'd still want to keep the existing checks, but just add a quicker failure where we can check .rst files more directly

Yup

**Comment by potiuk** [comment]
> The current spell check also checks spelling of doc comments right? So we'd still want to keep the existing checks, but just add a quicker failure where we can check .rst files more directly

Absolutely no doubts sphinx spell check is needed. The word "alternative" was simply wrong but I do not know good English word for it :). Simply "additional check"  might be better wording. I will update it to be precise.

**Comment by ephraimbuddy** [comment]
Yes. Closing
