### ISSUE TITLE
Master 2.0.0-dev Docker, Editing Connections with SQLite crashes 

### ISSUE THREAD

**Issue by emiliocolo** [apache/airflow#11193]
**Apache Airflow version**: master repo

**Environment**:
Docker image used for local development, built with the Dockerfile provided in the repo, SequentialExecutor with SQLite3 ( as originally is ) 

added below steps in the entrypoint_prod.sh, to have a simple development local running version of airflow.

airflow db init
airflow scheduler &
exec airflow webserver

**What happened**:
From the webui, going to originally created connections, and edit some of the created one, then crashes as follows, it does not happen with the the one's i created manually.

Ooops. 

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: 0b1ee94811c4
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 602, in edit
    widgets = self._edit(pk)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 1228, in _edit
    self.prefill_form(form, pk)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/views.py", line 2554, in prefill_form
    extra_dictionary = json.loads(form.data.get('extra', '{}'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
****TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'****

**Comment by potiuk** [comment]
That one shoud be fixed for 2.0 for sure.

**Comment by kaxil** [comment]
@emiliocolo Can you give an example or reproduction steps please i.e. if we can reproduce it with the default connections or not

**Comment by emiliocolo** [comment]
sure
- Build docker from yesterday's master in github repo and Dockerfile ( plain vanilla or no extra vars, airflow env values etc )
- Run it, with the startup script modified adding as below: 
airflow db init  ( using SQLite , SequentialExecutor for local development ))
airflow scheduler &
exec airflow webserver

- Dockerized Airflow is running, i can access to the webUI and scheduler is also seems ok
- Go to connections and try to modify any of the pre-created connections, then it crashes with the above logs
- Manually created connections seems fine.

as a note i tried to recreate the DB with airflow init reset , upgrade etc from command line, but same crash.

**Comment by mik-laj** [comment]
> airflow scheduler &
> exec airflow webserver

You cannot run multiple processes if you are using SQLite. SQLite does not support multithreaded/multiprocess operations.

**Comment by emiliocolo** [comment]
ok, i ll check this

**Comment by potiuk** [comment]
Hey @emiliocolo - I am closing this one . I just tested that it works with Breeze + sqlite. Let us know if it still does not work for you
