### ISSUE TITLE
Contributor's Quick Guide

### ISSUE THREAD

**Issue by pcandoalmeida** [apache/airflow#11192]
**Description**

Create a Quick Guide to get new contributors engaging with the project as quickly as possible through a simplified, integrated page.

**Use case / motivation**

The Airflow contribution documentation is really comprehensive 🚀  This could seem a bit complex and perhaps overwhelming for new contributors as they go through all the documentation on Breeze, the contribution processes, testing, etc. The idea is to create a "Contributor's Quick Guide" or "Contributing: Up and Running" which will cover the basics of the PR process as well as some common debugging ideas in one integrated page. Moreover, the contribution process might be exemplified through an actual merged in PR. The motivation here being that we show new contributors what best practice looks like in terms of the PR process, as well as how to overcome common debugging issues that might be encountered, through said example. 

**Related Issues**

None at the moment.

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow Is this section is not enough?

**Comment by potiuk** [comment]
See the https://apache-airflow.slack.com/archives/CCR6P6JRL/p1601024096031400 @mik-laj . @pcandoalmeida proposes to restructure the documentation in the way that will be more "digestible" for new contributors. The current one is very comprehensive, but it might feel quite overwhelming for a newcomer. 

Patrick has some ideas on how to improve it from the perspective of "newbie" and I think this is fantastic idea.

**Comment by pcandoalmeida** [comment]
Hey @mik-laj 👋🏼 yes, the idea was to perhaps integrate bits from Breeze, Contributing and Testing in one page and work through a merged in example. Don't want to introduce documentation bloat potentially so all feedback/ideas very welcome!

**Comment by kaxil** [comment]
I love the idea, splitting would surely help and you can link them to CONTRIBUTING.rst

**Comment by VBhojawala** [comment]
Hello everyone, 

I am very new to this project and i exactly felt same as @pcandoalmeida has described in '**Use case / motivation**'.
I have prepared a document that might be useful for new contributors to quick setup.  
It is made keeping in mind that new contributor should be able to quick start from single document without going to any other pages and with continuous flow.
For preparing this document i have tested this flow on fresh install of Ubuntu 20.04.

Here is the link to document: 

https://github.com/VBhojawala/airflow/blob/dev-quick-start/docs/contributrs-quick-start.rst

**Comment by potiuk** [comment]
This is Really, Really cool @VBhojawala ! 

I love it. We'v been discussing this very thing at one of the latest meetings regarding triaging and I know we have an on-going documentation improvement process. Maybe you could open a PR with that and then we together with @ryw and @paolaperaza we could help to make it part of the Airlow documentation! . I really love that it has all the visual guidelines and examples!

**Comment by kaxil** [comment]
Love it @VBhojawala . Please feel free to open a PR and we all can help review that PR and get better with it

**Comment by pcandoalmeida** [comment]
Awesome @VBhojawala!
