### ISSUE TITLE
Need to convert end_date to epoch seconds in template in BashOperator

### ISSUE THREAD

**Issue by r39132** [apache/airflow#112]
Hi!
I am executing a remote spark job and need to pass the "start_date" as a parameter to the spark job. Unfortunately, the remote spark job is expecting the date as epoch seconds, so I need a template for `{{ end_date.strftime('%s') }` as shown in the example below. How do I accomplish this? Also, what is the macro for start-date? I feel that what I really want is start-date, not end-date.

```
# Convert the end_date to epoch seconds
aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    bash_command="ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; /root/run_aggregation.sh --start_ts {{ end_date.strftime('%s') }}'" ,
    dag=dag)
aggregate_data_spark_job.set_upstream(clean_up_db_tables_job)
```

**Comment by r39132** [comment]
Note: If I just datetime.now(), I could do this with python string interpolation. However, I need access to the end_date airflow job parameter passed to `./airflow/bin/airflow test ep_demo aggregate_data_spark_job 2015-07-07`

```
aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    bash_command="ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; /root/run_aggregation.sh --start_ts %s'" % (datetime.now().strftime('%s')) ,
    dag=dag)
aggregate_data_spark_job.set_upstream(clean_up_db_tables_job)

```

**Comment by mistercrunch** [comment]
Is this what you want: `{{ execution_date.strftime('%s') }}`?
I'm not sure whether this works `{{ task_instance.start_date.strftime('%s') }}`, but should be very close to  `{{ datetime.now().strftime('%s') }}`
More details here: http://pythonhosted.org/airflow/code.html#macros

**Comment by r39132** [comment]
Actually need the start and end dates for any run.

**Comment by r39132** [comment]
Will try.

**Comment by r39132** [comment]
I'm not interested in now -- was used for illustration

**Comment by artwr** [comment]
I have been using the following for one of my dags where the API requires the same. You could define the function in the DAG definition and then add it to the params for instance : 

```
def dt_to_epoch(dt):
    """
    Converts a date_stamp to epoch
    """
    epoch = datetime.datetime(1970,1,1)
    return int((dt - epoch).total_seconds())


params = {
    "dt_to_epoch": dt_to_epoch
}

aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    bash_command="ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; /root/run_aggregation.sh --start_ts {{ params.dt_to_epoch(end_date) }}'" ,
    dag=dag)
```

It is a little bit of a dirty way to define your own macros inline. I am also confused by your use of `start_date` and `end_date` for any run. Most runs, unless you are doing a backfill, the `date` parameter of interest is the `execution_date`, and `start_date == end_date ==  execution_date`, which corresponds for us to the day of data we want to process regardless of when it actually runs.

Let me know if that helps any.

**Comment by r39132** [comment]
Thanks @artwr and @mistercrunch 

In my use-case, I actually need to specify a window of 1 day worth of data, so I need both start_datetime and end_datetime. Start_datetime will essentially be the date at midnight, and end_datetime will be the time 24 hours later, both expressed in epoch seconds. My Spark job will take this start and end time and compute some aggregates.

**Comment by mistercrunch** [comment]
gotcha, so
`{{ execution_date.strftime('%s') }}` and
`{{ (execution_date + timedelta(1)).strftime('%s') }}`

**Comment by r39132** [comment]
Sounds good. Thanks folks!

**Comment by r39132** [comment]
@artwr I really like your approach above and am trying to use this pattern to solve another problem. I get an error that dict object has not attribute named dt_to_epoch.

**Comment by r39132** [comment]
Re-opening only to verify that @artwr approach works, though I have a work-around.

**Comment by r39132** [comment]
it should be 
`{{ params['dt_to_epoch'](end_date) }}`

**Comment by r39132** [comment]
I tried 
`{{ (execution_date + timedelta(1)).strftime('%s') }}`

as in 

```
# Operator : Read the parquet data and generate aggregate data
# Convert the end_date to epoch seconds
aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    bash_command="ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; /root/run_aggregation.sh {{ (execution_date - timedelta(5)).strftime('%s') }} {{ execution_date.strftime('%s') }}'" ,
    dag=dag)
aggregate_data_spark_job.set_upstream(clean_up_db_tables_job)
```

But, I get the following exception : 

```
2015-07-15 20:23:52,583 - root - ERROR - 'timedelta' is undefined
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/airflow/models.py", line 818, in run
    self.render_templates()
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/airflow/models.py", line 918, in render_templates
    result = rt(content, jinja_context)
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/airflow/models.py", line 1181, in render_template
    return template.render(**context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
UndefinedError: 'timedelta' is undefined
```

I'm passing 2 arguments to my aggregation.sh script, a `start date` and an `end date`. My `start date` is the `execution date - 5 days`, because data can take 5 days to reach us, so we have a look-back window of 5 days from any execution date. I need to do a time delta computation. I'm new to Jinja, so I am wondering how the render_template will know the timedelta is part of datetime.

**Comment by artwr** [comment]
In this particular case, it depends on how you import datetime. You might need to either do : 

```
import datetime

{{ (execution_date + datetime.timedelta(1)).strftime('%s') }}
```

or

```
from datetime import datetime, timedelta

{{ (execution_date + timedelta(1)).strftime('%s') }}
```

**Comment by r39132** [comment]
I am following the second example : 
`from datetime import date, datetime, time, timedelta`, when getting this exception.

I realized macros also solve my problem.

**Comment by r39132** [comment]
I solved my problem using 2 macros. So I can achieve what I need using ds_add and ds_format.

```
send_email_notification_flow_successful = EmailOperator(
    task_id='send_email_notification_flow_successful',
    to="sanand@agari.com",
    subject='custom email from airflow',
    html_content="{{ params.foo(macros.ds_add(ds, -5), macros.ds_format(macros.ds_add(ds, -5), '%Y-%m-%d', '%s'))  }}",
    params=params,
    dag=dag)
```

This code essentially subtracts 5 days from the execution date and converts the result into epoch seconds as a long.
