### ISSUE TITLE
another state for dagrun - skipped

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#11204]
right now dagrun returns state of success/failed. I would like a 3rd state - skipped. 

use case: dag polls a website looking for a change, if website has not changed I would like the dagrun (not the task instance) to be skipped. so I want to interpret the dagrun status in controlM. ie some error = failed, website changed and new data = success, website did not change = skipped

**Comment by eladkal** [comment]
Correct me if I'm wrong here but in your suggestion the DAG must run in order to check the website status.
So you expect the DAG to run but eventually mark itself as SKIPPED?

**Comment by tooptoop4** [comment]
yes, name could be RAN_WITH_SKIPPED_RESULT or whatever

**Comment by ashb** [comment]
I can see what you what you mean by this, but also the whole dag run _isnt_ skipped if the first task (I assume) actually ran.

So we'd have to be careful about the naming of this to make it clear.

As for the "API" to make a sensor trigger this: probably by throwing a (new) custom exception -- like we have `AirflowFailException` to make a task fail without retrying, a new `SkipRestOfDagRun` exception could be the way this mode is triggered.
