### ISSUE TITLE
Airflow flower: Connection reset

### ISSUE THREAD

**Issue by arsalan993** [apache/airflow#11202]
I am using airflow using celery executor and monitoring it using airflow dashboard and airflow flower. 

After couple of minutes later i get following error on terminal running flower
`[E 200930 14:45:01 broker:84] RabbitMQ management API call failed: [Errno 104] Connection reset by peer`

**Comment by turbaszek** [comment]
@arsalan993 is there any problem with your Airflow deployment or you only see log messages like this one (which I think comes from postgres?)?

**Comment by arsalan993** [comment]
During tasks are being executed on airflow using celery executors when i toggle different tabs in flower it suddenly stops working display above error i shared above.

Arsalan Ahmed
________________________________
