### ISSUE TITLE
LocalTaskJob does not check return code of the process

### ISSUE THREAD

**Issue by lucafuji** [apache/airflow#1121]
```
def _execute(self):
        command = self.task_instance.command(
            raw=True,
            ignore_dependencies=self.ignore_dependencies,
            force=self.force,
            pickle_id=self.pickle_id,
            mark_success=self.mark_success,
            task_start_date=self.task_start_date,
            job_id=self.id,
            pool=self.pool,
        )
        self.process = subprocess.Popen(['bash', '-c', command])
        return_code = None
        while return_code is None:
            self.heartbeat()
            return_code = self.process.poll()
```

Here we need to check the return_code of the process, otherwise it's possible that a process is killed externally but LocalTaskJob think it suceeds

**Comment by lucafuji** [comment]
Pull request here:https://github.com/airbnb/airflow/pull/1122

**Comment by mistercrunch** [comment]
Well it's also possible that this parent process gets killed as well. Luckily we send and monitor heartbeats and kill zombie tasks.

If we really wanted to capture this very rare case, we should refactor that logic instead of duplicating it.

Do you guys kill -9 a lot of tasks? I a normal kill should be clean (by SIGINT / SIGTERM handling), though I haven't run much tests since I first wrote the code...

**Comment by lucafuji** [comment]
There are several reasons we need take special care of the spawned process(TaskInstance.run):
1. As you said the LocalTaskJob process has already been taken care of by kill_zombies
2. We don't check the return code of the spawned process, it will keep in ''running" state forever, if it's in a pool, it's wasting a slot in the pool. I did see one pool is full with those running tasks so no other tasks can proceed
3. the LocalTaskJob process is usually very lightweight so there's little chance it will be killed, but the spawned process sometimes may do a heavy job like using lots of memory. In such case, they are easily being killed by some external daemon monitoring process because of out of memeory, too much FD,etc. Like in some cases, all the process is running in a docker, so a docker daemon will kill those spawned process.  

Thanks again for the quick reply
