### ISSUE TITLE
Connection Extra Field is not encrypted/masked on editing

### ISSUE THREAD

**Issue by FelixKJose** [apache/airflow#11218]
I see a discrepancy in the behavior of encryption:
When I created a variable with key containing ApiKey  suffix, the value get encrypted as shown in the attachment. Then I tried to edit that variable still it shows as ****** rather than plain text - thats perfect (expected).
Now coming to connection:
where I have extra field with value containing ApiKey  and it saves and shows as extra encrypted as True. But now when I click on edit, instead of showing the extra field as ********* it shows as plain text - which is inconsistent and not expected.

**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Local

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Mac OS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

But now when I click on edit, instead of showing the extra field as ********* it shows as plain text 

**What you expected to happen**:

expected to show ********* 

<img width="1664" alt="Screen Shot 2020-09-30 at 4 58 09 PM" src="https://user-images.githubusercontent.com/22526075/94757525-7b986880-0368-11eb-8ee5-2af511a31220.png">
<img width="1627" alt="Screen Shot 2020-09-30 at 4 55 57 PM" src="https://user-images.githubusercontent.com/22526075/94757526-7c30ff00-0368-11eb-86f8-3698cb6b957c.png">
<img width="1673" alt="Screen Shot 2020-09-30 at 4 46 35 PM" src="https://user-images.githubusercontent.com/22526075/94757528-7cc99580-0368-11eb-9bca-406e420414b2.png">
<img width="1641" alt="Screen Shot 2020-09-30 at 4 46 22 PM" src="https://user-images.githubusercontent.com/22526075/94757529-7cc99580-0368-11eb-90ac-8643a9a5ceae.png">

**Comment by ryw** [comment]
@ryanahamilton can you have a look at this maybe?

**Comment by ryanahamilton** [comment]
Took an initial look at this. The problem is that the connections does not have similar [`hidden_field_formatter()` logic](https://github.com/astronomer/airflow/blob/master/airflow/www/views.py#L2632) implemented that is used for variables.

**Comment by FelixKJose** [comment]
@ryanahamilton @ryanahamilton Is this something may get addressed on 2.0 version or is it too late?

**Comment by mik-laj** [comment]
@FelixKJose Feel free to submit a PR. It will be a long time before we release the final version 2.0.

**Comment by bhavaniravi** [comment]
I would like to raise a PR for this issue. You can assign it to me

**Comment by bhavaniravi** [comment]
There is a problem in implementing this. 
In variables, if the value is encrypted, then when updating the var, the value is overridden as  "*****" in DB. The same with extra connection args as well.

Now I'm wondering if this is something we should even handle at the backend

**Comment by potiuk** [comment]
I think it should be handled in the usual way as "write-only" change. If there is a secret value set in the database, it should be displayed as `*******` but we should also track if has been modified. If it has not, then we should not attempt to replace the password with the `*******`. In case it is replaced (someone sets a new secret), it should be modified in the db.

**Comment by eladkal** [comment]
@bhavaniravi  are you still working on this issue?

**Comment by leozitor** [comment]
This issue was not fixed yet?

**Comment by potiuk** [comment]
It's open, so likely not - but feel free to work on it @leozitor if you would like to. Shall I assign you ?

**Comment by leozitor** [comment]
> It's open, so likely not - but feel free to work on it @leozitor if you would like to. Shall I assign you ? 

Well, i've never contributed before, let me take a look at the issue first,if I see I can handle this, then sure thing!

**Comment by potiuk** [comment]
Starting from CONTRIBUTING.rst is a good first step when you get to the point tha you would like to ffix it :)

**Comment by Bowrna** [comment]
Could I check if I could fix this issue?

**Comment by Bowrna** [comment]
@potiuk Unfortunately I forgot to fix this issue and it has been pending for a long time. I remember seeing your fix around this and then it striked me that I have kept this open for long time. Is the fix you done on connections edit, closes this issue or is that a different one?

**Comment by potiuk** [comment]
I can't remember, really - but just checking/reproducing it might be good enough thing to do here.

**Comment by jscheffl** [comment]
This is a Airflow 1.10 issue reported a while ago. I assume in Airflow 2.x UI it is still the same. Assuming that the whole UI of connection sneed a re-write and nobody spent time or demanded a fix on this for a long time.... closing this.

My recommondation would be that secrets should be only added to password field, all other fields are not treated as secret in the connection.
