### ISSUE TITLE
Branch airflow in middle and test task with different parameters in parallel 

### ISSUE THREAD

**Issue by freephys** [apache/airflow#11224]
Hi,
 I am looking for a way to achieve this inside airflow, hopefully some easy demo code to study with.  Start with several jobs with say 50 parameters, then at some point (After finishing task A->B) , I wanna to run task C in parallel with different values of say 5 parameters(those 5 parameters will try different values) , after running task C in parallel, all results are passed onto task D and E with same parameters.  The dag id etc are needed to be generated dynamically.
  
Any idea about if this can be done with current airflow or a feature to be ask?
 
The advantage will be saving time on task A and B and try task C with several different parameters so we can pick best one based on the results of task D

thanks

**Comment by mik-laj** [comment]
I do not fully understand the question. [XCOM](https://airflow.readthedocs.io/en/latest/concepts.html#xcoms) is used to pass the results of one task to the next.

**Comment by eladkal** [comment]
I also don't understand the issue.
In any case this sounds more like ETL design question so if you need support please use Stackoverflow or troubleshooting channel in Airflow slack.
If this is a feature request please comment with more details and use case examples.
