### ISSUE TITLE
Enable CodeQL on Airflow repo

### ISSUE THREAD

**Issue by baolsen** [apache/airflow#11236]
**Description**

GitHub has recently released CodeQL for automatically scanning for security vulnerabilities.

https://securitylab.github.com/tools/codeql
https://www.techspot.com/news/86951-github-open-source-codeql-tool-looks-security-holes.html

**Use case / motivation**

Good to ensure Airflow is as secure as possible and that new features are security tested where possible

**Related Issues**

None

**Comment by potiuk** [comment]
There is already PR for that: #11211
