### ISSUE TITLE
Deprecate airflow.providers.email package

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11273]
Hello,

This package was released in one series of packages and was then removed from Airflow (PR: https://github.com/apache/airflow/pull/10013). We need to deprecate with a warning, but unfortunately, we cannot do it now as the new module location does not exist in Airflow 1.10 yet (PR: https://github.com/apache/airflow/issues/11178).

I propose that we create a backport package when Airflow with #11178 will be released. This will allow us to easily migrate to Airflow 2.0 and no user will be left without a deprecation warning

Best regards,
Kamil Breguła

**Comment by alexInhert** [comment]
I'm working on an upgrade now and I'm not so clear what is the deal with the email package.
What do we need to do to make sure our dags are not breaking when doing the upgrade?

**Comment by mik-laj** [comment]
This is for Airflow 1.10, so I'm closing
