### ISSUE TITLE
Cannot specify schema in HiveToMySqlTransfer

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#113]
it cannot specify a schema in HiveToMySqlTransfer init.
it also cannot apply the hive_cli_conn_id configured schema.

**Comment by mistercrunch** [comment]
What version are you running? I just ran some tests and the HiveServer2Hook takes the schema attribute and passes it along properly.

Alternatively you can specify the schema in your SQL, as in
`SELECT * FROM mydb.mytable`

While looking at the code I found a (unrelated) bug though, here's the fix: 
https://github.com/airbnb/airflow/pull/114

**Comment by mistercrunch** [comment]
reopen if this is still an issue
