### ISSUE TITLE
Possible false PendingDeprecationWarning due to identity test rather than equality test?

### ISSUE THREAD

**Issue by gwynevans** [apache/airflow#11303]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
Ubuntu fresh install

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Running commands such as "airflow list_dags" results in a PendingDeprecationWarning at models/dag.py:1337

Sorry, can't currently copy exact msgs from my test VM

**What you expected to happen**:
No warnings with a clean install.

Digging into the cause appears to be that the test "and self.task_dict[task.task_id] is not task" is returning False when comparing "Task(BashOperator)" with "Task(BashOperator)".  I suspect that the test should be "!=" instead, but I'm not 100% sure, hence this report.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment]
@gwynevans can you please check against latest version and let us know if you still encounter the issue?
