### ISSUE TITLE
Add dark mode to Airflow UI

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#11334]
**Description**

I think by now everyone knows the benefit of dark mode.
It would be great if Airflow will offer this open in the UI
I believe it should be setting per user that can be controlled from the user profile.

**Comment by alxdembo** [comment]
@mik-laj  Can I volunteer for this one?

**Comment by mik-laj** [comment]
This seems to me not to be a task that one person can do. @ryanahamilton  Can you help with this task? Do you have any expectations or suggestions?

**Comment by ryanahamilton** [comment]
This is definitely on my radar/wish list as well. With the current UI framework, there isn't a clean and clear path to implement this in a sustainable fashion. The aged Bootstrap (v3.3) dependency nested in our FAB dependency is one of the biggest limitations, whereas the latest Bootstrap versions (v5) employ CSS variables that would allow for systematic approach to theme switching. That said, I'm not ready to take this on at this time, but I'm exploring more significant UI framework changes that would definitely make this easier to accomplish.

**Comment by eladkal** [comment]
dark mode will be added as part of [AIP-38 Modern Web Application](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-38+Modern+Web+Application)

**Comment by MartinUQ** [comment]
So this is done but not in official release ? I can find it in the settings

**Comment by potiuk** [comment]
No. The AIP is not yet complete. It is in progress and currently airflow is a mixture of old and new UI. Until it is fully converted, dark mode will not happen consistently.

**Comment by NFeruch** [comment]
What is the status of this issue as of 10/1/2022?

**Comment by potiuk** [comment]
I think it waits for someone to implement it. Generally if there is no comment, about it and UI does not have it, there is no change. 

But maybe you want to help with that and provide some PRs @NFeruch if you are eager to have it ? That could speed it up. If not, then it simply has to wait for someone from the community to pick it up. We have > 2200 contributors and anyone could contribute it in forn of PR :). And you could become one of them. This is how OSS works basically.

**Comment by m-urminsky** [comment]
Please implement this, honestly a button on the main page changing the background to a darker color and the text color to a different one is enough. You can perfect it later.

**Comment by MartinUQ** [comment]
My eyes are hurtinggggg

**Comment by potiuk** [comment]
Well _ maybe one of you would like to take on the task ? I t waits  for someone who knows ui to pick it up. As everything in open sources will be implemented   whether someone implements it :). 

Or maybe find someone who could do it of you want it so badly? Anyone can volunteer and implement it actually so if you knowledge someone who knowledge ui frameworks and could implement it os the fastest way to get it done.

**Comment by luis-chaves-visa** [comment]
a good place for anyone that knows css: https://github.com/apache/airflow/tree/main/airflow/www/static/css

It's nearly 6k lines though

**Comment by djpirra** [comment]
It would even be better if we could define themes to be applied on the UI. Would be really awesome.

**Comment by potiuk** [comment]
> It would even be better if we could define themes to be applied on the UI. Would be really awesome.

Yes. This feature still waits for somene to implement it.

**Comment by bengabp** [comment]
No one has implemented it yet ???

**Comment by potiuk** [comment]
> No one has implemented it yet ???

Maybe you would like to volunteer and implement it @bengabp ? 

I think this task is waiting for someone who is interested in it an will implement it.  you can also find someone who would like to implement it and contribute it. This is how it works for open-source development when you have mostly volunteers contributing. Anyone could contribute it - and finding time or someone who could contribute it is the fastest way to get something you really want.

**Comment by Andrew-Wichmann** [comment]
I'm not sure if this goes against the philosophy / licensing of Airflow, but I would love to extend this dark mode theme idea into a broader feature set that would enable white labeling. I picked up the idea at a GrafanaLive conference where a presenter showed a dashboard where the color scheme matched the company's color scheme. I think that would be awesome in Airflow.

**Comment by potiuk** [comment]
Yes. It could be done. No licencing or philosophy problem. It just waits for somoene who will implement it. there are always a lot of ideas, but far less number people who will to spend their time and energy to contribute implementations of those :)

**Comment by Andrew-Wichmann** [comment]
I hear ya'. I'm not demanding anything. I really like the software. Thank you for your time and effort

**Comment by YounHS** [comment]
perhaps.... Is this what you're looking for?

![airflow_dark_mode](https://github.com/apache/airflow/assets/40846179/a536d3d4-e575-4e89-bbcd-05d1ac7aac1f)

**Comment by AndrewNLauder** [comment]
> @mik-laj Can I volunteer for this one?

Looks like nobody has taken a stab at this one. Are you still interested in it?

**Comment by dataract** [comment]
> > @mik-laj Can I volunteer for this one?
> 
> Looks like nobody has taken a stab at this one. Are you still interested in it?

I'm one of the interested in it.

**Comment by TruongNhanNguyen** [comment]
I have checked out Apache Airflow for the dark mode feature and see that @YounHS implemented the feature. The PR was merged 7hr ago, I love the new feature and will give it a try right now. Thank @YounHS for bringing the great feature to Apache Airflow.

**Comment by jscheffl** [comment]
Closing as fixed in #39355 (even though the current implementation is marked experimental)
