### ISSUE TITLE
Equivalent option to Oozie dataset 

### ISSUE THREAD

**Issue by iamon3** [apache/airflow#1133]
In Oozie, we can define the dataset in the coordinator, which can be passed to the action.
e.g.
Task -1 generates the output data in the directory structure as  /{Year}/{Month}/{Day}/{HOUR}

To an dependent task Ti 's definition we can pass the lookback parameters, say 3 days lookback, thus,  Ti will read data from the Start Date = Current date - 3 to End Date - Current Date, and accordingly will proceed the execution. i.e. Oozie will itself take care of scheduling the task, and accordingly reading the data from the passed parameter.

Is similar support provide by airflow as well?

**Comment by mistercrunch** [comment]
Check out the XCom feature in Airflow.
http://pythonhosted.org/airflow/concepts.html#xcoms
