### ISSUE TITLE
Fix Sync Logs from S3 in Airflow 1.10.12 with the Kubernetes Executor

### ISSUE THREAD

**Issue by Javier162380** [apache/airflow#11345]
**Apache Airflow version**:1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v.1.14.8

**Environment**:

- **Cloud provider or hardware configuration**:AWS/EKS
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I upgraded my airflow cluster from 1.10.10 to 1.10.12 and the python version from 3.7 to 3.8. The cluster is deployed on EKS using the K8s executor and syncing logs using s3. I found a repeatable bug on the UI. When I try to get the logs from a dag with just one attempt, it tries to get the logs from the pod, and as we erased the pods by default when they finished using the airflow.cfg options, so as the pod is erased, it cannot fetch logs from the pod, and it raised an error instead of searching the logs from S3. 
```*** Trying to get logs (last 100 lines) from worker pod hermesemaileventshermesemaileventstransationalloadredshift-7ffa ***

*** Unable to fetch logs from worker pod hermesemaileventshermesemaileventstransationalloadredshift-7ffa ***
(403)
Reason: Forbidden
```
When the task has two attempts, I can sync the logs from the UI easily

```
*** Reading remote log from s3://wt-prod-euwest1-zephyr/logs/adsales/adsales-shutterstock-image-report/2020-10-06T08:30:00+00:00/8.log.
```
I think this bug is related to this PR. https://github.com/apache/airflow/pull/8626

**What you expected to happen**:

Be able to sync the logs from s3 after the pod is deleted. If the pod do not exist it should be able to fetch logs from a remote storage

**How to reproduce it**:

**Anything else we need to know**:

**Comment by abhishekshenoy** [comment]
Hi Team ,
 
     
We are facing similar issue on. GCP.

Apache Airflow version: 2.0

Kubernetes version (kubectl version):v1.18.2

Environment:
Cloud provider or hardware configuration: GCP
OS (e.g. from /etc/os-release): Container Optimized OS.

We use GCS to store our logs. Recently we are seeing an issue wherein while executing DataprocOperators (CreateCluster , SubmitJob, DeleteCluster) , though the operator has successfully executed. Airflow is unable to read the logs from the pod and write it to GCS. Which intern results in task failure but in the background the actual DataProc operator has successfully completed.

This becomes a major issue wherein it runs the SparkSubmitJob twice resulting in duplicate data as well as in the below case it respawned another task to stop the cluster but the new task failed because the cluster was already stopped by the previous task which was marked as failed because it was unable to read logs.

Exception Stack Trace of such failed task is as below
```
*** Unable to read remote log from gs://hnw-airflow-prod-ba7642cd7876f2/logs/extraction_workflow/stop_cluster/2021-01-12T10:00:00+00:00/1.log
*** 404 GET https://storage.googleapis.com/download/storage/v1/b/hnw-airflow-prod-ba7642cd7876f2/o/logs%2Fextraction_workflow%2Fstop_cluster%2F2021-01-12T10%3A00%3A00%2B00%3A00%2F1.log?alt=media: No such object: hnw-airflow-prod-ba7642cd7876f2/logs/df_raw_file_extraction_workflow/stop_cluster/2021-01-12T10:00:00+00:00/1.log: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
*** Trying to get logs (last 100 lines) from worker pod dfrawfileextractionworkflowstopcluster-6f91dc0d7c26450c980c5464 ***
*** Unable to fetch logs from worker pod dfrawfileextractionworkflowstopcluster-6f91dc0d7c26450c980c5464 ***
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b677a80e-a9f8-4794-9085-ffb74aa2f443', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 13 Jan 2021 17:58:33 GMT', 'Content-Length': '294'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"dfrawfileextractionworkflowstopcluster-6f91dc0d7c26450c980c5464\\" not found","reason":"NotFound","details":{"name":"dfrawfileextractionworkflowstopcluster-6f91dc0d7c26450c980c5464","kind":"pods"},"code":404}\n'
```

**Comment by himabindu07** [comment]
Hi I verified this issues using 2.0.1, unable to reproduceble and can you please try with 2.0.1.
Thanks

**Comment by Reddy1990** [comment]
Hi @himabindu07  in Version: v2.0.2 I'm getting similar issues. The pod is getting deleted immediately once its has ran. As per the error message its correct but how can I retrieve the logs?  

*** Trying to get logs (last 100 lines) from worker pod filecopierfilecopier.b3d90ee2f9fc4ef7b5ee7edda63d55f4 ***

*** Unable to fetch logs from worker pod filecopierfilecopier.b3d90ee2f9fc4ef7b5ee7edda63d55f4 ***
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 05 Jul 2021 11:31:14 GMT', 'Content-Length': '274'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"filecopierfilecopier.b3d90ee2f9fc4ef7b5ee7edda63d55f4\\" not found","reason":"NotFound","details":{"name":"filecopierfilecopier.b3d90ee2f9fc4ef7b5ee7edda63d55f4","kind":"pods"},"code":404}\n'
