### ISSUE TITLE
Ooops error running any DAG

### ISSUE THREAD

**Issue by BigDataBrasil** [apache/airflow#11349]
Hey guys,

I´m trying to run a DAG but it´s showing the following error. It was working for months until yesterday. Does anyone know what might be happening? I´m sending the logs below.

I´m running Airflow in Docker with Kubernetes.

Kubectl version:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

![AirflowOoops](https://user-images.githubusercontent.com/5913383/95466242-821f7500-0952-11eb-8c18-556698f1d2d0.jpg)

[Airflow Logs.txt](https://github.com/apache/airflow/files/5348212/Airflow.Logs.txt)

Kind,

**Comment by eladkal** [comment]
The error log suggest:
`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: task_instance.pool`
what airflow version are you running? Can you please add reproduce steps?
