### ISSUE TITLE
Helm chart MySQL support

### ISSUE THREAD

**Issue by thesuperzapper** [apache/airflow#11367]
We should aim to support external MySQL databases in the [Offical Airflow Helm Chart](https://github.com/apache/airflow/tree/master/chart). 

The existing [stable/airflow](https://github.com/helm/charts/tree/master/stable/airflow) chart supports MySQL, so should try to aswell (if we want people to move).

The only significant issue I see is that we are using `pgbouncer`, which will need to either be disabled for MySQL or some MySQL alternative found.

**Comment by thesuperzapper** [comment]
Similar to: #9627

**Comment by mik-laj** [comment]
We have one ticket, so I'm closing this one for now.
