### ISSUE TITLE
missing logs from the included libraries

### ISSUE THREAD

**Issue by sreev** [apache/airflow#11366]
logs are missing printing to console/file from py packages using 'logging'.

airflow version 1.10.12 and latest from main branch. tried with these two versions separately.
os: local macos catalina & linux (containers from bitnami images). tried on these two separately.

```
svaddi@Srees-MacBook-Pro / % kubectl version  
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}

```

here is architecture:
airflow (LoggingMixin) -> NEW_DAG (airflow.models.DAG, LoggingMixin) -> a library (logging) -> another library (logging)

here are the details of my dag and attempts:
my_dag.py:
dag = NEW_DAG(...)
SomeOperator(..., dag=dag)

both of the library (logging):
this has log = logging.getLogger(__name__)

I made three attempts to rule out the combination of LoggingMixing and logging stepping over each other:
Attempt 1:
In NEW_DAG.__init__:
self.log.info(..) : these lines appear in the terminal where i started airflow.
and none from rest of the methods.

Attempt 2:
I added log = logging.getLogger(__name__) in NEW_DAG.
log.info(..) : these lines appear until __init__ is called, in the terminal where i started airflow.
and none from anywhere else, including methods.
In __init__:
self.log.info(..) : these lines appear in the terminal where i started airflow.
and none from rest of the methods.

Attempt 3:
I added log = logging.getLogger(__name__) in NEW_DAG.
And removed LoggingMixin form class NEW_DAG(airflow.models.DAG)
log.info(..) : these lines appear until __init__ is called, in the terminal where i started airflow.
and none from anywhere else, including methods.

**Comment by sreev** [comment]
Conversation before creating the git issue:
https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1602027042396900

**Comment by sreev** [comment]
the logs seems piped into themselves.
here is a sample logs lines from running `% airflow scheduler` in my local on mac.

```
[2020-10-20 18:47:29,294] {logging_mixin.logging_mixin.py:112} INFO - [2020-10-20 18:47:29,294] {dag.dag.py:496} INFO - job_run_ids: ["b0678e61-5174-4538-bf60-0960a10e94cf"]
[2020-10-20 18:47:29,294] {logging_mixin.logging_mixin.py:112} INFO - [2020-10-20 18:47:29,294] {dag.dag.py:155} INFO - marquez_run_id: b0678e61-5174-4538-bf60-0960a10e94cf

```

**Comment by mik-laj** [comment]
Can you update your first post to match the template? In particular, I am interested in the Airflow version.
https://raw.githubusercontent.com/apache/airflow/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by eladkal** [comment]
This issue is reported against older version of Airflow.
Please check against latest version. If needed we will reopen this issue.
