### ISSUE TITLE
Incorrect start_date Assignment for DagRun Instanciation within schedule_dag(self, dag)

### ISSUE THREAD

**Issue by RvN76** [apache/airflow#1136]
Hi,

Thank you for your great work on the system. It has provided so much convenience for our group.

Recently, after we upgraded to 1.6.2, we found an issue with the dagrun_timeout argument when we tested it:
The metadata db showed that the start_time of the DagRuns were always the same, which was the time when the scheduler started, instead of the actual start time of the DagRun. This would cause DagRuns fail immediately if their actual start times is later than the start time of the scheduler plus the given dagrun_timeout. This problem can be reproduced using CeleryExecutor and LocalExecutor.

I noticed that the issue #990 mentioned similar cases and could be resolved by setting the time zone of the metadata db to UTC. However, this didn't work for us (MySQL).

I've found that the code to judge whether a DagRun should be labeled FAILED due to time out was here in the method shcedule_dag(self, dag): https://github.com/airbnb/airflow/blob/1.6.2/airflow/jobs.py#L373, and that the code to initiate the next DagRun was here: https://github.com/airbnb/airflow/blob/1.6.2/airflow/jobs.py#L415. The problem is that the new start_date is not passed in when a new DagRun instance is created, thus the start_date of the new DagRun will be the default value in the DagRun class definition, which is this: https://github.com/airbnb/airflow/blob/1.6.2/airflow/models.py#L2873.

Since the start_date is set to datetime.now() and is never changed during the construction of the instances, it will always be the time when the class file gets loaded for the first time for all DagRun instances, which is the start time (or very close to it if not exactly) of the scheduler.

I solved the problem by adding start_date=datetime.now() to the the parameter used to create a DagRun. I also created a pull request for the change I did in my source code #1135. Could you please take a look of this issue? Thanks

**Comment by bolkedebruin** [comment]
@RvN76 thanks for your report and pull request. Did you have a look at the FAQ? 

Using a start_date of datetime.now() can lead to unpredictable behavior, and your DAG never starting. It's recommended to subtract a timespan to force the scheduler to recognize the start_date. See also http://stackoverflow.com/questions/33126159/airflow-not-scheduling-correctly-python .

And yes I agree with you that start_date is confusing...

**Comment by RvN76** [comment]
Hi @bolkedebruin thanks for your quick response. But I guess you meant the start_date in the workflow DAG definition? What I meant was that I added start_date=datetime.now() to the source code here https://github.com/airbnb/airflow/blob/1.6.2/airflow/jobs.py#L415, rather than in my workflow DAG args. Sorry for the confusion.

**Comment by bolkedebruin** [comment]
ok. this has been fixed in master, not in 1.7.1rc2 (@mistercrunch) @r39132 @criccomini
