### ISSUE TITLE
Using rest api, we are not able to get the dag state using run_id.

### ISSUE THREAD

**Issue by chinnusujitha** [apache/airflow#11376]
**Description**

**Use case / motivation**

**Related Issues**

**Comment by mik-laj** [comment]
We have two types of API:
- Experimental API - available in Airflow 1.10 and new
- Stable API - available in Airflow 2.0 release. https://airflow.readthedocs.io/en/latest/stable-rest-api-ref.html

Airflow 2.0 has not been released yet, so If you want to use new stable APi, you need to install airflow from sources.

We do not plan to develop API for Airflow 1.10 in any way and if you need to add new features, you have to use plugins and custom views.
See: https://airflow.readthedocs.io/en/latest/plugins.html#exclude-views-from-csrf-protection

**Comment by ashb** [comment]
New API in 2.0 should fix this.
