### ISSUE TITLE
Add ability to zoom into Graph view from selection in Tree View

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#11388]
**Description**
Currently to view DAG run in graph view you must first know it's execution date and then choose it from the drop list.
This is annoying in some cases because you might want to see the big picture in Tree view and then "zoom in" to graph view for a specific run. Currently there is no direct way to do this.

**I suggest the following:**
Go to tree view and click on a dag run. it will open the pop up to select what to do. my suggestion is to add to this a button "Go to Graph View" 
![Screen Shot 2020-10-09 at 23 42 49](https://user-images.githubusercontent.com/63792998/95629812-5521ae00-0a89-11eb-9494-520e00886dd0.png)

Clicking on it will switch to Graph View tab and preselect the specific DAG run that was chosen in Tree View screen:
![Screen Shot 2020-10-09 at 23 43 51](https://user-images.githubusercontent.com/63792998/95629819-594dcb80-0a89-11eb-8fb3-c632e5eaac4b.png)

**Comment by rynmccrmck** [comment]
Hi! I'd like to try this as a first issue if no one else has jumped on it.
