### ISSUE TITLE
Optimize subclasses of DummyOperator be set straight to success instead of being run

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11393]
**Apache Airflow version**:
v2.0.0

**What happened**:

Custom operators inheriting from DummyOperator are go in to a scheduled state, where as DummyOperator itself is set straight to success.

**What you expected to happen**:

All operators should be successfully executed.

**How to reproduce it**:

```py
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator

class MyJob(DummyOperator):
    template_fields_renderers = {
        "body": "json"
    }
    template_fields = ("body",)

    def __init__(self, body, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.body = body

with DAG(
    dag_id="test",
    schedule_interval=None,
    start_date=datetime(2020, 8, 13),
) as dag:
    MyJob(task_id="aaaa", body={"aaa": "bbb"})

```

**Anything else we need to know**:
This is a known problem that we will fix, see: https://github.com/apache/airflow/pull/10956#discussion_r502492775

**Comment by kaxil** [comment]
We subclass DummyOperator for ExternalTaskMarker

**Comment by malthe** [comment]
This optimization currently does not function correctly with the `pre_execute` and `post_execute` parameters introduced (on an experimental basis) in #17576.

**Comment by kaxil** [comment]
> This optimization currently does not function correctly with the `pre_execute` and `post_execute` parameters introduced (on an experimental basis) in #17576.

There is no point in wasting a worker slot for `DummyOperators`, there are exceptions too where a DummyOperator has callbacks or not. On a large scale this makes a huge difference and overhead of sending task to Workers if it is not needed.


The `pre/post_execute` are still "experimental" for a good reason. There still aren't that many use-cases for it. We might rip it of if that does not serves a purpose tbh.
