### ISSUE TITLE
[QUARANTINE] test failing TestImpersonationWithCustomPythonPath.test_impersonation_custom

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11439]
Seems that we have the test TestImpersonationWithCustomPythonPath.test_impersonation_custom failing often in quarantine 

Example here: https://github.com/apache/airflow/runs/1239113557?check_suite_focus=true

Would be great to solve it before we release 2.0

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment]
closed in favor of https://github.com/apache/airflow/issues/28658
