### ISSUE TITLE
[QUARANTINE] TestLocalTaskJob.test_localtaskjob_maintain_heart_rate failures

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11440]
Seems that the maintain_heart_rate test is failing often in quarantine. Should be fixed before 2.0

Example here: https://github.com/apache/airflow/runs/1239113557?check_suite_focus=true#step:9:379

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/17581
