### ISSUE TITLE
pip install airflow[hive]: UnicodeDecodeError

### ISSUE THREAD

**Issue by sdikby** [apache/airflow#1149]
I have this error when trying to install airflow[hive]

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

Any suggestion/help will be very appreciated

**Comment by artwr** [comment]
Hey, your version of pip is very old, could you try `pip install --upgrade pip` and report back afterwards if this fixes your issue?

**Comment by sdikby** [comment]
When i tried to execute  `sudo pip install --upgrade pip` i got this:
The directory '/home/sadok/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sadok/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages

And when i retried to install airflow[hive] i got this ne error

sadok@sadok-Inspiron-5547:~/.cache/pip/http$ sudo pip install airflow[hive]
The directory '/home/sadok/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sadok/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): airflow[hive] in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): alembic<0.9,>=0.8.3 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): chartkick<0.5,>=0.4.2 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): croniter<0.4,>=0.3.8 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): dill<0.3,>=0.2.2 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.10.1 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): flask-admin==1.2.0 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): flask-cache<0.14,>=0.13.1 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): flask-login==0.2.11 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): future<0.16,>=0.15.0 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): gunicorn<20.0,>=19.3.0 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): jinja2<3.0,>=2.7.3 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): markdown<3.0,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): pandas<1.0.0,>=0.15.2 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): pygments<3.0,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): python-dateutil<3,>=2.3 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): requests<3,>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): setproctitle<2,>=1.1.8 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy>=0.9.8 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): thrift<0.10,>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF==0.12 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): hive-thrift-py>=0.0.1 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): pyhive>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): pyhs2>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): Mako in /usr/local/lib/python2.7/dist-packages (from alembic<0.9,>=0.8.3->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): python-editor>=0.3 in /usr/local/lib/python2.7/dist-packages (from alembic<0.9,>=0.8.3->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from croniter<0.4,>=0.3.8->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask<0.11,>=0.10.1->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask<0.11,>=0.10.1->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): wtforms in /usr/local/lib/python2.7/dist-packages (from flask-admin==1.2.0->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2<3.0,>=2.7.3->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas<1.0.0,>=0.15.2->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from pandas<1.0.0,>=0.15.2->airflow[hive])
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/dist-packages (from python-dateutil<3,>=2.3->airflow[hive])
Collecting sasl (from pyhs2>=0.6.0->airflow[hive])
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading sasl-0.2.1.tar.gz
Installing collected packages: sasl
  Running setup.py install for sasl ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-A6BtZz/sasl/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-B4eQR8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/sasl
    copying sasl/**init**.py -> build/lib.linux-x86_64-2.7/sasl
    running egg_info
    writing requirements to sasl.egg-info/requires.txt
    writing sasl.egg-info/PKG-INFO
    writing top-level names to sasl.egg-info/top_level.txt
    writing dependency_links to sasl.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'sasl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sasl.egg-info/SOURCES.txt'
copying sasl/saslwrapper.cpp -> build/lib.linux-x86_64-2.7/sasl
copying sasl/saslwrapper.h -> build/lib.linux-x86_64-2.7/sasl
copying sasl/saslwrapper.pyx -> build/lib.linux-x86_64-2.7/sasl
running build_ext
building 'sasl.saslwrapper' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/sasl
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isasl -I/usr/include/python2.7 -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-2.7/sasl/saslwrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from sasl/saslwrapper.cpp:254:0:
sasl/saslwrapper.h:22:23: fatal error: sasl/sasl.h: No such file or directory
 #include <sasl/sasl.h>
                       ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-A6BtZz/sasl/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-B4eQR8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-A6BtZz/sasl/

**Comment by sdikby** [comment]
fixed after installaing libsasl2-dev

**Comment by artwr** [comment]
I was just about to say, this looks like a systems package issue. Thanks for documenting this!
