### ISSUE TITLE
[QUARANTINE] The test_backfill_job.py causes resource (probably memory) exhaustion

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11495]
**Apache Airflow version**:
master

We often have "Exit 137" which is likely memory exhaustion cause by the test_backfill_job.py. It's been investigated by GitHub support (we've enabled debugging and waiting to reoccur). See #11294 

Example here: 

https://github.com/apache/airflow/runs/1245441164?check_suite_focus=true#step:6:301

Most likely it is caused by backfill job trying to backfill too much ? 

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
This started happening a lot less afer we split the tests. Closing.

**Comment by ashb** [comment]
I'm still seeing this a noticeable amount of the time :(

**Comment by potiuk** [comment]
Fixed by #19809
