### ISSUE TITLE
Make sure Docker works with installing core + providers.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11490]
Currenlty when Docker is built, we are installing airflow using "pip install" from local sources. Since we split to separate providers, this process needs to be updated to also install relevant providers when certain extras are installed via PyPI and that it all work locally (there are the the separate, linked issues about it #11489 #11464 that should be implemented to cover this.

**Comment by ashb** [comment]
(If you're working on this then it's not important, but I'm not sure what this issue actually is from reading this)

**Comment by potiuk** [comment]
Description updated.
