### ISSUE TITLE
Perform "mini scheduling run" after task has finished

### ISSUE THREAD

**Issue by ashb** [apache/airflow#11498]
In order to further reduce intra-dag task scheduling lag we can add a further optimization: when a task has just finshed executing (success or failure) we can look at the downstream tasks of the task that just finished, and then make scheduling decisions for those tasks there -- we've already got the dag loaded, and we know they are _likely_ actionable as we just finished. We should set tasks to scheduled if we can (but no further, i.e. not to queued).

Upstream_failed may also not be safe as that would run callbacks. Think about this.

We'll need a config option to disable this, as it _could_ lead to task starvation of other dags

**Comment by potiuk** [comment]
Good idea!

**Comment by ashb** [comment]
We've already tested a hacky version of this, and it' makes a difference. (This was one of the two remaining items from https://github.com/apache/airflow/issues/9630)
