### ISSUE TITLE
Why are there two "DAGs" views in the UI?

### ISSUE THREAD

**Issue by davidaventimiglia-personal** [apache/airflow#115]
Why are there two "DAGs" views in the UI and what do they mean?  In the "main menu bar" there are choices "DAGs," "Data Profiling," "Browse," "Admin," and "Doc."  The "DAGs" choice shows a list of DAGs.  But then, within the "Admin" drop-down menu there also is a choice for "DAGs" and it also shows a list of DAGs, and the two screens are very similar though there also are differences.  Moreover, I have created two Python scripts in my "dags_folder" and each sets up an AirFlow DAG.  After restarting the web server, these two DAGs appear in the first screen described above.  However, they do not appear in the second one, which is under the Admin drop-down.  Why?  The only four that appear in the second screen are the four example ones that ship with AirFlow.  This is very confusing.  Thank you.

**Comment by mistercrunch** [comment]
The second DAGs view should not be there. I need to remove the link from the Menu. It's an artifact of registering the modelview in "flask admin"...

**Comment by davidaventimiglia-personal** [comment]
Thanks!
