### ISSUE TITLE
`celeryd_concurrency` mandatory configuration

### ISSUE THREAD

**Issue by itajaja** [apache/airflow#1151]
Even if I am not using the celery executor, I receive the following error:

```
section/key [celery/celeryd_concurrency] not found in config
```

I removed the celery section in the config file to keep it shorter and cleaner. this happens because of https://github.com/airbnb/airflow/blob/airbnb_prod.1.6.2.9/airflow/bin/cli.py#L751. The said key is the only one causing problems. Shouldn't be possible to run airflow without the celery config section, if we are not using celery?

Thanks!

**Comment by sheldonkwok** [comment]
Yeah I'm running into this issue as well. It seems like just importing the CeleryExecutor in the code requires the configuration to be there even if it is not used. 
https://github.com/airbnb/airflow/blob/master/airflow/executors/celery_executor.py#L29

**Comment by itajaja** [comment]
As a follow up, when enabling the logs, I also need to add `worker_log_server_port`. The celery call will fail and it will default to the s3 logs. If I don't set that variable though, an unhandled exception is generated when accessing the logs.

**Comment by bolkedebruin** [comment]
Can you please create a Jira issue for this?

**Comment by itajaja** [comment]
done, closing this
