### ISSUE TITLE
Allow to reset user password from Users panel.

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#11521]
**Description**

Currently any user can change his password when navigating to Profile -> Reset my password
However Admins have no option to reset password for users as this option doesn't exist in Security -> List users -> Edit users

The requested feature is:
Add new type of permission "Change other users password".
Grant this permission by default to Admins
Add option in the UI to reset other users password for whoever has the permission for this action.

The motivation for this request is that currently the only way to resolve this issue is to delete the user and recreate it.

**Comment by mik-laj** [comment]
We use [Flask AppBuilder](https://github.com/dpgaspar/Flask-AppBuilder) for user management and I think that is a missing feature in this framework.  Can you create a ticket in this project? FAB experts will solve this problem faster than if we try to handle it on our side. 

BTW. To get around the FAB limitations, I started using Keycloak: https://github.com/apache/airflow/issues/11305

**Comment by RosterIn** [comment]
closing as this is FAB issue

**Comment by ypelud** [comment]
You can use the FAB cli like this to reset password.

`FLASK_APP=airflow.www.app flask fab reset-password`

**Comment by contentfree** [comment]
And where does `flask` live in relation to airflow?
