### ISSUE TITLE
Multibyte Upload Behavior of S3Hook.load_file Causing Issues

### ISSUE THREAD

**Issue by adambom** [apache/airflow#1153]
When using the `S3Hook.load_file`, if `multipart_bytes` is set, uploads will fail if the file is smaller than `multipart_bytes`. The acute cause can be found [here](https://github.com/airbnb/airflow/blob/master/airflow/hooks/S3_hook.py#L316).

What happens is when the method calculates the number of chunks to use, it gets zero. The range iterator thus returns an empty set and no parts get uploaded. When the `complete_upload` method of the multipart uploader gets called, the whole thing crashes.

We've created a plugin to copy files from HDFS to S3 and it calls an `S3Hook`. We want to use multipart uploads if the file is larger than `multipart_bytes`. It would be nice if the hook could make that distinction and automatically choose whether to use multipart upload or not. At the very least, it should definitely not fail.

The easy way to fix this would be to stat the file to get its size, and then branch to either a multipart upload or a regular upload. Would be happy to submit a PR for the fix if that sounds reasonable.

**Comment by artwr** [comment]
Sounds very reasonable. I would be happy to review the PR.

**Comment by adambom** [comment]
I'm on it
