### ISSUE TITLE
airfow schedule load data & test load data Inconsistent

### ISSUE THREAD

**Issue by basebase** [apache/airflow#1154]
1. I use Hive select data to hive table 
2. use airflow schedule job  load hive data to oracle, oracle data and hive data Inconsistent
   I think see exist what bug, but Unfortunately test load hive data to oracle data It is consistent

Excuse me everyone I have not encountered a similar situation

thank you

**Comment by bolkedebruin** [comment]
Can you please either ask on the mailinglist or create a Jira issue for this?
