### ISSUE TITLE
Providers tar.gz for 2.0 alpha1 fails

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11544]
From Airflow Slack (https://apache-airflow.slack.com/archives/C0146STM600/p1602768865025700):

The 0.0.1a1 provide package I tried to install (`apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz`), 
has no `setup.py` or `pyproject.toml`, so automated tools like pip fail to install it. 

There is only a `setup_provider_packages.py` file in the tarball, which is of course not standard. Is this a known issue?

--

The `.whl` package has worked fine for this user

**Comment by potiuk** [comment]
Yep. That's a good point - we've only installed those packages using wheels. Good point to fix it. It just needs some setup.py template to generate good catch !

**Comment by kaxil** [comment]
Closing in favor of https://github.com/apache/airflow/issues/11546
