### ISSUE TITLE
BigQuery Hook get_records still using bql

### ISSUE THREAD

**Issue by TheSuperAgent** [apache/airflow#11545]
Version : 1.10.12

Im trying to get a SQL query results on BigQuery with BigQuery Hook. But in the logs, seems its showing the warning.
```py
WARNING - /root/.local/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py:800: DeprecationWarning: Deprecated parameter `bql` used in `BigQueryBaseCursor.run_query` Use `sql` parameter instead to pass the sql to be executed. `bql` parameter is deprecated and will be removed in a future version of Airflow.
  category=DeprecationWarning)
```
My code:

```py
from airflow.contrib.operators.gcs_to_bq import GoogleCloudStorageToBigQueryOperator
def get_dag_ids(tablename,**kwargs):
    bq_hook = BigQueryHook(bigquery_conn_id='bigquery_default',use_legacy_sql=False, location='US')
    records = bq_hook.get_records(sql="select max(time) from project.dataset.{};".format(tablename))
    return records[0][0]
```
Is this something  I need to fix from my code, or from it has to be updated on Airflow's hook itself?

**Comment by eladkal** [comment]
To get the latest version you should import the hook from [google provider](https://pypi.org/project/apache-airflow-backport-providers-google/) not from contrib.
`bql` param was removed in https://github.com/apache/airflow/pull/4060 thus you shouldn't see this deprecation warring when importing the hook via providers.

**Comment by BhuviTheDataGuy** [comment]
Oh great.
Thanks, I'll use providers for the hook
