### ISSUE TITLE
Can't pass --without-mingle and --without-gossip to celery worker

### ISSUE THREAD

**Issue by waleedsamy** [apache/airflow#11557]
**Apache Airflow version**: ANY

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I've an issue with airflow celery worker performance, and I think there are a place for optimization if airflow enables providing --without-gossip while creating celery worker https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/airflow/bin/cli.py#L1271 
https://docs.celeryproject.org/en/4.4.3/reference/celery.bin.worker.html?highlight=--without-gossip#cmdoption-celery-worker-without-gossip. In my case, I've a 200 vm and every vm running 2 queues, so 400 **workers exchanging useless message every second** which result in airflow worker is taking about 10% of cpu time (in 4 cores) and to compare, I've a standalone celery app that consume 0.1% of cpu time **after enabling --without-gossip --without-mingle --without-heartbeat**.

**What you expected to happen**:

celery worker should not take more than 2% of cpu time.

**How to reproduce it**:
Using 200 vm and every vm 2 celery workers running at same time, you will see that the celery worker process is taking ~10-15% of cpu time.

PLEASE NOTE:
Due to https://github.com/celery/celery/issues/2566, we can't provide --without-mingle and --without-gossip through configuration (config file).

**Anything else we need to know**:

**Comment by turbaszek** [comment]
According to this test:
https://github.com/celery/celery/blob/05da357502a109c05b35392391299d75d181ccab/celery/contrib/testing/worker.py#L110-L122

We should be able to pass those argument to celery worker without a problem because here:
https://github.com/apache/airflow/blob/f7e01ab29339080c77431a1fc5e4403ba2d80326/airflow/cli/commands/celery_command.py#L152

The `Worker` class is inheriting from `WorkController`

**Comment by mik-laj** [comment]
CC: @auvipy
