### ISSUE TITLE
Allow for specification of cipher in SftpHook

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#11560]
**Description**

I want to specify the cipher to use when creating a SftpHook. Currently this is not possible because there is not a way to propagate the value to CnOpts. 

https://github.com/apache/airflow/blob/master/airflow/providers/sftp/hooks/sftp.py
https://pysftp.readthedocs.io/en/release_0.2.9/pysftp.html?#pysftp.CnOpts
https://pysftp.readthedocs.io/en/release_0.2.9/cookbook.html

**Use case / motivation**

I want to be able to access SFTP servers that have disabled access from connection with weak ciphers.

**Comment by wolfier** [comment]
Here's some [unit tests](https://github.com/ryhsiao/pysftp/blob/master/tests/test_ciphers.py) in pysftp using copts and ciphers.

**Comment by mik-laj** [comment]
@wolfier Looks interesting. Can I assign you to this issue? We are open to pull requests from external contributors.
