### ISSUE TITLE
Can't view 2nd log

### ISSUE THREAD

**Issue by ryw** [apache/airflow#11561]
Running Airflow 2 using `astro` cli - I can only access log for first task attempt

![image](https://user-images.githubusercontent.com/4283/96177048-43ae2b00-0efb-11eb-87d5-ee01e4b4f5f9.png)

**Comment by eladkal** [comment]
This is something we are also experiencing in 1.10.11
I suspect this happens when the logs are saved on the worker locally, if the worker is down then the log isn't accessible when the worker comes up again the log is retrievable again.

**Comment by feluelle** [comment]
@ryw can you check the first log and see if the task log of the second run was appended there?

**Comment by ashb** [comment]
Closing in favour of #11717
