### ISSUE TITLE
Can't reset dag's start_date?

### ISSUE THREAD

**Issue by samson-wang** [apache/airflow#1156]
Hi all,
I create a dag for test, the `start_date` is set to today, and `schedule_interval` is 5 minutes.
Then the dag tasks keep running and the dag is scheduled every 5 min since 00:00. It's OK.
I want to stop scheduling like this. So I changed the start_time to `datetime.today()` in the dag source code hoping that the scheduler make execution time from now on. However it doesn't work.

What can I do to reset the `start_date`?
Thanks!

**Comment by mistercrunch** [comment]
http://pythonhosted.org/airflow/faq.html#faq
Please read the "What’s the deal with `start_date`?" section

**Comment by samson-wang** [comment]
Thanks for your tips. However I'm still confused with the faq. No clear clue to the reset of start_date.
So I did some search in the source code `airflow/jobs.py`. From this piece of code in 'SchedulerJob. schedule_dag'

```
                if latest_run:
                    # Migrating from previous version
                    # make the past 5 runs active
                    next_run_date = dag.date_range(latest_run, -5)[0]
                else:
                    next_run_date = min([t.start_date for t in dag.tasks])
```

It seems that only clearing the history of dag runs' and task instances' can force the scheduler to use the `start_date` updated. And it works!
