### ISSUE TITLE
Can't change state of a task instance via the task instance list view

### ISSUE THREAD

**Issue by ryw** [apache/airflow#11562]
clicking one or multiple task instances from /taskinstance/list/ view and choosing any new state, results in error screen

<img width="1177" alt="Screen Shot 2020-10-15 at 3 34 54 PM" src="https://user-images.githubusercontent.com/4283/96177660-3180bc80-0efc-11eb-8056-c9e3303b81a6.png">

**Comment by kaxil** [comment]
Duplicate of https://github.com/apache/airflow/issues/11513

**Comment by ryw** [comment]
Closing in favor of #11513
