### ISSUE TITLE
Strange behavior around the edge of the circles

### ISSUE THREAD

**Issue by ryw** [apache/airflow#11563]
Edge is flickery + sometimes I can't click the number

![Screen Recording 2020-10-15 at 4 07 46 PM](https://user-images.githubusercontent.com/4283/96180787-f6cd5300-0f00-11eb-8d0f-989e1ea424ae.gif)

**Comment by ryanahamilton** [comment]
I can take a look at this!

**Comment by ryw** [comment]
thanks @ryanahamilton

**Comment by ryanahamilton** [comment]
@ryw I'm struggling to reproduce this—anything in particular to get it in that state?

**Comment by ryw** [comment]
i just fired up a blank deployment w/ `astro` and `FROM astronomerio/ap-airflow:2.0.0-1.dev3-buster-onbuild` 

and i can get fluttery behavior on the border of the circles

![Screen Recording 2020-10-20 at 10 41 30 AM](https://user-images.githubusercontent.com/4283/96602649-3b6e3b00-12c1-11eb-8443-29f6b8bfe549.gif)
