### ISSUE TITLE
Manually triggering a dagrun when already at max_active_runs leads to nothing being scheduled.

### ISSUE THREAD

**Issue by ashb** [apache/airflow#11582]
If you have a DAG with `max_active_runs=1` and it is running some tasks, and then you manually trigger another run of this DAG, both runs end up not scheduling anything and you see this message over and over in the logs:

```
[2020-10-16 14:00:34,118]  2437572 {{airflow.jobs.scheduler_job.SchedulerJob scheduler_job.py:1657}} INFO - DAG scenario1_case2_01_1 already has 1 active runs, not queuing any more tasks
```

A longer term fix for this would be to introduce a "queued" state for DagRuns, and then when manually creating dag runs set it to queued, and only have the scheduler set DagRuns to running.

That may or may not be less work than fixing the current mechanism.

**Comment by gflores1023** [comment]
FYI - there's another bug related to max_active_runs that I filed a couple months ago (with potentially very bad effects). mik-laj also mentioned about adding a new dag state. 
https://github.com/apache/airflow/issues/9975
