### ISSUE TITLE
Release "cncf.kubernetes" and "google" backport packges

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11590]
**Description**

The "cncf.kubernetes" backport package has not been yet released as it contained some critical bugs when backported (the last fix implemented in #11478  and better debugging was added in #11502. 

We plan to release the "cncf.kubernetes" release candidate package on Monday 19th of October together with the "google" package with re-enabled GKEPodOperator that depends on it.

**Use case / motivation**

The "cncf.kubernetes"  package is important for many Airflow 1.10 users and they will make migration to 2.0 much easier. 

**Related Issues**
#11478  in #11502  #10014

**Comment by eladkal** [comment]
@potiuk can also be closed? :)
