### ISSUE TITLE
Default DagRun configuration

### ISSUE THREAD

**Issue by casassg** [apache/airflow#11599]
**Description**

It would nice to have the trigger UI pre-populated with default values for your dagrun configuration: https://airflow.apache.org/docs/stable/dag-run.html?highlight=params#using-ui

For that we need to add a new field to DAG that keeps the default conf for DAGRuns, serialize it and have it available on the Trigger UI.

This should allow user to more easily know what parameters/keys in config dictionary to expect.

**Use case / motivation**

Parameterize your DAG and change values easily on Trigger DAG UI.

**Related Issues**

#10587

**Comment by casassg** [comment]
I think we can activate `dag_run_conf_overrides_params` by default on master + https://github.com/apache/airflow/pull/10839#issuecomment-694079456 it may be enough. Proposing change of default in #10587

**Comment by turbaszek** [comment]
@casassg is this issue still valid?

**Comment by casassg** [comment]
We can close it, with the changes I merged it may be good enough already.
