### ISSUE TITLE
dynamic bash command

### ISSUE THREAD

**Issue by itajaja** [apache/airflow#1159]
I would like to pass `bash_command` to my BashOperator task. The reason I want to do that, it's because I want to pass the last time an task of that instance was successfully run. I am trying to understand if I can use templates, but I don't see how. Am I missing something basic?

**Comment by mistercrunch** [comment]
You can use templates. if your bash command strings endswith '.sh' or '.bash', the operator will try to resolve the file, relative to your python module.

**Comment by itajaja** [comment]
My bash_command is an inline command , not a file. Something like

``` py
def get_last_run_date(task_id):
    task_instance = settings.Session().query(TaskInstance) \
        .filter_by(task_id=task_id, state=State.SUCCESS) \
        .order_by('execution_date desc') \
        .first()
    if not task_instance:
        return datetime(2000, 1, 1)
    return task_instance.start_date

my_task = BashOperator(task_id='my_task_id' bash_command='do_stuff LAST_RUN_DATE_HERE')
```

How can I  pass something like `get_last_run_date('my_task_id')` to my bash operator so that? This, of course, will have to be computed during run time, ie doing

``` py
my_task = BashOperator(task_id='my_task_id' bash_command='do_stuff {}'.format(get_last_run_date('my_task_id')))
```

will not work, because it will not reflect the actual last run time. Hope it makes sense :)

**Comment by mistercrunch** [comment]
Time for you to go through the tutorial.

**Comment by itajaja** [comment]
I really did, I swear (should I move this conversation to the google group?). Are you suggesting to reference the db session from a macro to perform the query at runtime? I am not sure that's good practice.

**Comment by mistercrunch** [comment]
templating looks something like that:
`bash_command="bash foo.sh {{ ds }}"`
http://pythonhosted.org/airflow/code.html#macros

**Comment by itajaja** [comment]
sure. In this case though, I am trying to get something more complicated. specifically a query to retrieve the date of the previous run. For what is worth, this could be as well a call to some apis to retrieve some value I want to know for running the task. I don't know if creating a macro that does that is really something that makes sense. I'd rather use a callback approach where I am passing a function that gets executed at runtime, but using a template for this doesn't look like the best approach. But if that's the way to go, I'll build my fancy macro

**Comment by mistercrunch** [comment]
Is it a scheduled DAG? Are you interested in the execution_date for the schedule, or the time at which it started?

**Comment by itajaja** [comment]
I am interested in the time the last successful task of a certain ID was started. I need that, so that I can process only the entries in my database created after that date. To do so, I am running a query ([this one](https://github.com/airbnb/airflow/issues/1159#issuecomment-197557494)).

But my question was more general. Let's say this value I need at runtime is coming from an api call I make to my server. Is templating the way to go? My doubt is that it seems bad to create a macro that does this only to pass a value at runtime.

**Comment by mistercrunch** [comment]
If it's a scheduled DAG, I'd recommend filtering on your modification timestamp between execution_date and the next one as opposed to the start_date of the job.

If you need to get a parameter from an api call real the section in  the docs about Xcom

**Comment by itajaja** [comment]
Thanks, I think I will use with a python operator upstream to calculate the timestamp first and then pass it using xcom, and then use jinja templates to get the value :+1:
