### ISSUE TITLE
Support to turn off the sql echo at logging in dbapi_hook

### ISSUE THREAD

**Issue by robinhur** [apache/airflow#11618]
**Description**

through the parameter, like `mute=True`, 
can turn off not to echo the SQL query

**Use case / motivation**

I hope we can turn on or off the option to echo or not echo of SQL query
First, if the query is too long, the log becomes unnecessarily heavy
And also sometimes we don't want it to be recorded because of like privacy issues.

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/pull/9671
CC: @kaxil @davido912 @madison-ookla

**Comment by potiuk** [comment]
Is this somethign we should inclue in 2.0 @mik-laj ? WDYT? Shall we remove the milestone from it?

**Comment by mik-laj** [comment]
I removed the milestone because this looks like a change that we can do later, and now we don't have any person assigned to it.

**Comment by ChrisWeinrich** [comment]
Is therey any work going on here or someone knows a workarround ? We have ~10k * 500 Insert Lines and this spams the logging very badly :(

**Comment by robinhur** [comment]
@ChrisWeinrich 
it's been almost an yr for me to raise this issue
and i've resolved it by creating my own operator that overrides existing codes and added to skip the echo part

**Comment by potiuk** [comment]
@robinhur @ChrisWeinrich  - the easiest and most certain way to get this implement is to submit a PR with a fix. Airflow is developed by > 1800 contributors, and there is no magical "someone's approval" to provide a fix for such a simple PR. 

It's really as simple as it gets - the person most interested in a feature/fix usually implements it. Waiting a year makes very little sense if you can provide PR in an hour and get it merged in a few days after review.

Do you need any guidance on preparing a PR for that?

**Comment by robinhur** [comment]
@potiuk 
yes please
will take a look and create PR for this when i have a chance
Thanks

**Comment by potiuk** [comment]
Start here: https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst , detailed contributor's guide is at https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst and if you like video tutorials - here is a recording for first-time  contributor's workshop we held during OCSS Mexico: https://youtu.be/kvccZizzfTk

**Comment by robinhur** [comment]
@potiuk Great Information!!
@ChrisWeinrich wait for it!! will let you have this feature soon :)

**Comment by kaxil** [comment]
Yup, just add a feature to add `log_sql` kwarg to `DbApiHook` and then https://github.com/apache/airflow/pull/18718 should help in passing this kwargs to hook so that we don't need to add it to all Operators or just `BaseSQLOperator`

**Comment by holly-evans** [comment]
@eladkal could you assign this to me?

**Comment by robinhur** [comment]
ah I was personally busy with work, so I forgot.
please go ahead @holly-evans 
if you need help please let me know :pray:
