### ISSUE TITLE
Don't include upstream_failed in the 'active task instances' test in the scheduler

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#11633]
**Apache Airflow version**: 2.0.0a1

**What happened**:

On my dev environment I have a lot of DAG runs with failed tasks, where the *downstream* task instances then have been set to `upstream_failed`. The scheduler is now refusing to schedule more instances for such DAGs.

The scheduler looks for such task instances that are not in the `State.finished` set:

https://github.com/apache/airflow/blob/db3fe0926bb75008311eed804052c90bfa912424/airflow/jobs/scheduler_job.py#L1482-L1488

However, `State.finished` is currently not a proper inverse of *running* states, it only includes success, failed, and skipped:

https://github.com/apache/airflow/blob/db3fe0926bb75008311eed804052c90bfa912424/airflow/utils/state.py#L110-L114

What is missing is the task instance `upstream_failed` state, so currently my log is being filled (very rapidly) with:

```
[2020-10-18 13:22:18,503] {{scheduler_job.py:1658}} INFO - DAG test_dag already has 26 active runs, not queuing any more tasks
```

Those 26 'active runs' are simply dag runs that failed and have 'upstream_failed' task instances.

Either `upstream_failed` should be added to `State.finished`, or the Scheduler task instance test should explicitly take that state into account.

**Comment by kaxil** [comment]
Yup we will fix this for alpha2. Thanks for reporting

**Comment by mjpieters** [comment]
I've been running with the following patch for a few days now (added to `airflow_local_config.py` to ensure early loading):

```
def airflow_issue_11633_upstream_failed_state():
    """The 'upstream_failed' state should be included in the 'finished' set"""
    from airflow.utils.state import State

    # in Airflow =<2.0.0a1, State.finished is a method, in future versions it is a frozenset.
    finished, is_set = State.finished, isinstance(State.finished, frozenset)
    if not is_set:
        finished = finished()

    if State.UPSTREAM_FAILED in finished:
        return

    if is_set:
        State.finished = frozenset([State.UPSTREAM_FAILED]) | State.finished
    else:

        @classmethod
        def finished_with_failed(cls):
            return [*finished, State.UPSTREAM_FAILED]

        State.finished = finished_with_failed


airflow_issue_11633_upstream_failed_state()
```

and I have not seen any adverse side effects so far.

**Comment by ashb** [comment]
I'm re-working that query in question a bit as part of fixing #11582, I'll encorporate this fix in there and add a test case for it
