### ISSUE TITLE
SQLAlchemy string is passed to worker pod in plain text as env var

### ISSUE THREAD

**Issue by ashishraman** [apache/airflow#11649]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.17

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS

**What happened**:
When spawning a worker pod, the scheduler injects the sql alchemy string as plain text in environment variables

<code>
Environment:
      AIRFLOW__CORE__DAGS_FOLDER:       /usr/local/airflow/dags/
      AIRFLOW__CORE__EXECUTOR:          LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:  postgresql+psycopg2://<<Redacted>>:5432/airflow_db
</code>

Anyone with a read permission can describe the pod and get the credentials. 

**What you expected to happen**:
The variable is passed as secret. It can either be manually set by the user or by the scheduler.

**How to reproduce it**:
Use KubernetesExecutor with PythonOperator. The new pod spawned by scheduler has the env variables AIRFLOW__CORE__SQL_ALCHEMY_CONN in plain text. I tried AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD as well but when the scheduler spawns the worker pod it sends down AIRFLOW__CORE__SQL_ALCHEMY_CONN in plain text

**Comment by ashishraman** [comment]
Any update on this?

**Comment by mik-laj** [comment]
@ashishraman Can you check if this problem also occurs when you use option [`pod_template_file`](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/configurations-ref.html#config-kubernetes-pod-template-file) to configure KubernetesExecutor?  I guess this maybe should give you enough flexibility to configure a worker to use a secret.

When you use the pod_template_file option, the worker gets a configuration similar to the rest of the components.
https://github.com/apache/airflow/blob/308f1d06668ad427fd2483077d8e60f55ee617e6/chart/files/pod-template-file.kubernetes-helm-yaml#L35
https://github.com/apache/airflow/blob/3188b130b5f61332e24c340ac6c0569efa4e8056/chart/templates/_helpers.yaml#L26
