### ISSUE TITLE
unable to import the airflow.providers

### ISSUE THREAD

**Issue by TheSuperAgent** [apache/airflow#11651]
Im wants to import Airflow Google providers. So I installed it.
```sh
pip3 install apache-airflow-backport-providers-google
```
Im able to see all the hooks and everything under the packages directory.
```sh
/usr/local/lib/python3.7/dist-packages/airflow/providers/google/cloud/transfer
```
But when I run the import command its failing.
```py
from airflow.providers.google.cloud.transfers.sql_to_gcs import BaseSQLToGCSOperator


Error:
Traceback (most recent call last):
  File "test1.py", line 8, in <module>
    from custom.custom_PostgresToGCSOperator import custom_PostgresToGCSOperator
  File "/root/airflow/dags/custom/custom_PostgresToGCSOperator.py", line 8, in <module>
    from airflow.providers.google.cloud.transfers.sql_to_gcs import BaseSQLToGCSOperator
ModuleNotFoundError: No module named 'airflow.providers'
```

**Comment by potiuk** [comment]
You likely have airflow installed in a different namespace. Likely you installed airflow with -e switch or with --user flag. 

See here for troubleshooting and workaround: 

https://airflow.readthedocs.io/en/latest/backport-providers.html#troubleshooting-installing-backport-packages

**Comment by sakshi-bansal** [comment]
Facing the same issue. I can see that both apache and backport is in the same folder - 
/usr/local/lib/python3.6/site-packages/airflow
/usr/local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/
/usr/local/lib/python3.6/site-packages/apache_airflow_backport_providers_cncf_kubernetes-2020.11.23.dist-info/
/usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0b3.dist-info/
