### ISSUE TITLE
min_file_process_interval impacts task execution

### ISSUE THREAD

**Issue by jdobr** [apache/airflow#11658]
Apache Airflow version: 1.10.12

Environment:

Any

What happened:
min_file_process_interval is documented to control when a new/updated file gets picked up by Airflow, but it also seems to control when a queued job is executed as described in here:
https://github.com/puckel/docker-airflow/issues/233#issuecomment-510931051
and here:
https://stackoverflow.com/questions/50012952/airflow-1-9-0-long-delay-between-task-execution

That should not be linked to dag task execution. If it is by design it is not well design. Anybody able to explain?

What you expected to happen:
Separate parameter to control how often Scheduler schedules new job tasks from parameter min_file_process_interval that should be only responsible to control when a new/updated file gets picked up by Airflow.

**Comment by ashb** [comment]
This link has been removed for Airflow 2.0, and the parsing will no longer affect DAG scheduling.
