### ISSUE TITLE
GCSToBigQueryOperator - Not generating the Unique BQ Job Name

### ISSUE THREAD

**Issue by TheSuperAgent** [apache/airflow#11660]
I was using `GoogleCloudStorageToBigQueryOperator` then I wanted to use `GCSToBigQueryOperator`. When I run parallel data export from GCS to BQ, (via a for loop Im generating dynamic task) It is generating the BQ Job name as `test-composer:us-west2.airflow_1603109319` (I think its taking node name + current timestamp) as the job id for all the tasks. 

**Error**
```
ERROR - 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/centili-prod/jobs: Already Exists: Job test-composer:us-west2.airflow_1603109319
Traceback (most recent call last)
```
This is not allowing to import 2nd table, it has to wait for a min(retry in DAG) then its imported.

But the older one is giving proper Job ID like (Job_someUUID)

### 3 parallel table Import:

* _GCSToBigQueryOperator_ - BQ Job ID for all the load jobs: `Job test-composer:us-west2.airflow_1603109319`
* _GoogleCloudStorageToBigQueryOperator_ - BQ job id for table1(`job_NYEBXXXXXvoflDiEj2j`), table2(`job_9xGl7WlVXXXXXWBriaqbhLQY`), table3(`job_aqmVLXXXXXL2YqVCGAqb_5EtW`)

**Comment by muscovitebob** [comment]
I just started using this operator via the backports package a few days ago and I hit this at least one in ten times I invoke the operator, making it unusable without manual supervision. I do not use a dynamic dag but I do have a few `GCSToBigQueryOperator`s.

```
[2020-10-22 08:40:58,732] {base_task_runner.py:113} INFO - Job 59262: Subtask TASKNAME [2020-10-22 08:40:58,730] {taskinstance.py:1135} ERROR - 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/PROJECTNAME/jobs: Already Exists: Job PROJECTNAME:EU.airflow_1603356058@-@{"workflow": "DAGNAME", "task-id": "TASKNAME", "execution-date": "2020-10-22T08:29:42.258293+00:00"}
```

**Comment by BhuviTheDataGuy** [comment]
Yeah, maybe a bug, try the previous version(GoogleCloudStorageToBigQueryOperator). It works.

**Comment by muscovitebob** [comment]
[This](https://github.com/apache/airflow/blob/1da8379c913843834353b44861c62f332a461bdf/airflow/providers/google/cloud/hooks/bigquery.py#L1442) seems to be the method that incorrectly generates the job IDs but the format does not seem to match exactly what I get in the logs.
Meanwhile I will indeed switch to the older operator since you report it always generates job IDs correctly, thanks!

**Comment by QuinRiva** [comment]
Are you sure you're running the current backport versions?  I was getting this issue in 2020.6.24, but it looks like it is solved in 2020.10.5.  Unfortunately, 2020.10.5 **isn't** compatible with the new bigquery/pubsub libraries (2.0.0), so I can't test.

**Comment by jensenity** [comment]
I'm using `apache-airflow-backport-providers-google==2020.10.5` and seem to get similar error as well. 

```
[2020-11-08 23:31:58,200] {taskinstance.py:1150} ERROR - 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/banksalad/jobs: Already Exists: Job test:US.airflow_1604878317
```

**Comment by BhuviTheDataGuy** [comment]
Even the big query hook has the same issue, Im, not a coder :) so not able to find the exact cause. 

When we use `contrib.bigquery` then no issue, this new `providers.bigquery` having this problem on all distributions (like the hook, bigquery operator, gcs to bq, empty table creator, Bq to bq and etc)

**Comment by jensenity** [comment]
apparently they upgraded and fixed it at airflow backport 2020.10.29 version.

**Comment by jensenity** [comment]
https://github.com/apache/airflow/commit/47b05a87f004dc273a4757ba49f03808a86f77e7

**Comment by BhuviTheDataGuy** [comment]
Awesome!!! So im closing this now.

https://github.com/apache/airflow/issues/11282

**Comment by muscovitebob** [comment]
For Cloud Composer users like me, trying to use `2020.10.29` with the `composer-1.12.5-airflow-1.10.10` image will error out with a very cryptic:
```
The command '/bin/sh -c bash installer.sh $COMPOSER_PYTHON_VERSION  fail' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```
In the cloud build step. The warning from earlier in the log may provide some hints as to why this happens:

```
+ python3 -m pipdeptree --warn fail
Warning!!! Possibly conflicting dependencies found:
* google-cloud-memcache==0.2.0
 - google-api-core [required: >=1.17.0,<2.0.0dev, installed: 1.16.0]
```

So for now at least Cloud Composer users are stuck with using either the old non-buggy Operator or waiting for Google to patch this.

**Comment by mik-laj** [comment]
Can you  latest composer image `composer-1.13.0-airflow-1.10.12` image and latest backport provider -` apache-airflow-backport-providers-google==2020.10.29`?

**Comment by potiuk** [comment]
@muscovitebob -> I believe indeed it is a dependency problem that is very likely to be addressed in the last version of composer image. From what we know the Composer team keeps the images updated with the releases of Apache Airlfow and the providers and the next image will even include the latest google providers baked, in but you should try to install the latest provider there. Note that there is a new version of google provider as release candidate (voting on it finishes on Thursday) so you might even try to install this version instead 

https://pypi.org/project/apache-airflow-backport-providers-google/2020.11.13rc1/

**Comment by muscovitebob** [comment]
> Can you latest composer image `composer-1.13.0-airflow-1.10.12` image and latest backport provider -` apache-airflow-backport-providers-google==2020.10.29`?

Upgrade with these went well, thanks much! Did not realise there was a new release.
