### ISSUE TITLE
ECSOperator failed to display logs from Cloudwatch randomly

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#11663]
**Apache Airflow version**: v1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Deployed in ECS Fargate
- **Install tools**: poetry

**What happened**:

I'm having this issue **randomly** (I've calculated the error rate to be between 1~2% based on the # of ECS tasks running each day) where the `aws_logs_hook` is unable to obtain existing log entries from Cloudwatch:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 979, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/site-packages/airflow/contrib/operators/ecs_operator.py", line 152, in execute
    self._check_success_task()
  File "/usr/local/lib/python3.8/site-packages/airflow/contrib/operators/ecs_operator.py", line 175, in _check_success_task
    for event in self.get_logs_hook().get_log_events(self.awslogs_group, stream_name):
  File "/usr/local/lib/python3.8/site-packages/airflow/contrib/hooks/aws_logs_hook.py", line 81, in get_log_events
    response = self.get_conn().get_log_events(logGroupName=log_group,
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetLogEvents operation: The specified log stream does not exist.
```
The resource does exist when I check the cloudwatch UI.
Note: this is not the same issue as https://github.com/apache/airflow/issues/9486 where the log stream name setup is erroneous. 

**What you expected to happen**:

This could be a simple API glitch when using boto3 to get the log events. We could add a retry mechanism [here](https://github.com/apache/airflow/blob/6416d898060706787861ff8ecbc4363152a35f45/airflow/contrib/hooks/aws_logs_hook.py#L81).

**How to reproduce it**: 

Running enough # of ECS task with ECS Operator

**Anything else we need to know**:

**Comment by eladkal** [comment]
We have some hooks that have such functionality using tenacity
For example:
[TelegramHook](https://github.com/apache/airflow/blob/b40dffa08547b610162f8cacfa75847f3c4ca364/airflow/providers/telegram/hooks/telegram.py#L126)
[GoogleDataprepHook](https://github.com/apache/airflow/blob/b40dffa08547b610162f8cacfa75847f3c4ca364/airflow/providers/google/cloud/hooks/dataprep.py#L61)

@feluelle WDYT?

**Comment by feluelle** [comment]
@eladkal could work.

What I don't like about the error is that it tells us that the resource does not exist. I would like to narrow the issue down before retrying. But if we cannot get more information about this, we can use tenacity to start doing retries.

On the user end you can set task retries when this issue appears.

**Comment by sparrovv** [comment]
Hi, we only noticed that behaviour in our setup. For some tasks, cloudwatch logs are just not fetched/displayed.

**Comment by zachliu** [comment]
Most likely AWS's :hankey: 
See my comments here https://github.com/apache/airflow/issues/15000#issuecomment-824404502
