### ISSUE TITLE
LDAP and official docker image

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11667]
Hello,

Many users report a problem with ldap with the official Docker image. We should consider what we want to do with it:
a) add missing images to the image.
b) add documentation that will describe this case.

Related: 
https://github.com/apache/airflow/pull/8745#issuecomment-711080959
https://github.com/apache/airflow/issues/11436
https://apache-airflow.slack.com/archives/CCR6P6JRL/p1603139139494400?thread_ts=1603137393.490900&cid=CCR6P6JRL

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
CC: @potiuk

**Comment by FelixKJose** [comment]
stuck with this issue for two days:(

**Comment by mik-laj** [comment]
I heard that you managed to solve the problem, so I'm assigning you to this issue and I'm waiting for the guide.

**Comment by potiuk** [comment]
Fixed by https://github.com/apache/airflow/issues/13306
