### ISSUE TITLE
Support unicode output of BashOperator

### ISSUE THREAD

**Issue by samson-wang** [apache/airflow#1166]
Got exception when bash command output unicode to stdout.
In `airflow/operators/bash_operator.py`

```
                for line in iter(sp.stdout.readline, b''):
                    line = line.decode().strip()
                    logging.info(line)
```

**Comment by jlowin** [comment]
@samson-wang what versions  of Python or Airflow are you running? Can you please provide an example bash_command that raises the error? I thought both Python 2 and Python 3 return bytes here.

**Comment by samson-wang** [comment]
Sorry for late response.
Airflow is v1.6.2, and python is 2.7.
The command will output chinese utf-8 characters to stdout.
I use 
`
line = line.decode('utf-8').strip()
`
 to deal with the problem.

**Comment by bolkedebruin** [comment]
@samson-wang Can you provide a Pr for this and open a Jira?

**Comment by samson-wang** [comment]
@bolkedebruin Sounds interesting! However, I find that my airflow installed via pip is version 1.6.2 and the master branch has already added an option to set the output encoding. And the corresponding commit is c4714a602da23db459767f3bebdee5810ce2d091. Problem solved! Thanks.
