### ISSUE TITLE
airflow/example_dags/example_kubernetes_executor.py - use_zip_binary() - code quality issue

### ISSUE THREAD

**Issue by ilyash-b** [apache/airflow#11679]
The description of `use_zip_binary()` is incorrect.

https://github.com/apache/airflow/blob/318f18f5a835f457c6a68426a476af89ace0c7e7/airflow/example_dags/example_kubernetes_executor.py#L69-L70

Additionally, the name `use_zip_binary` is not very telling. Maybe `assert_zip_binary` (based on what the function actually does)?

**Comment by ilyash-b** [comment]
> issue template

Oops. Found bug in GitHub then. When you select the code first and then reference in new issue (which I did, as opposed to using the "New issue" button) there is no selection of templates.

**Comment by mik-laj** [comment]
Can you create PR with patch? I am happy to help with the review.

**Comment by ilyash-b** [comment]
I just started looking at the project and I don't understand enough to fix it quickly. The name `use_zip_binary` is debatable so I would probably leave it as is. What I don't know for example is how `use_zip_binary()` is even supposed to behave.

**Comment by ilyash-b** [comment]
Another thing. `The zip binary is missing` is semantically incorrect. Should be something like `Failed to run the zip binary`
