### ISSUE TITLE
Confusing pod template files

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11686]
Hello,

We currently have files with a similar purpose in the project, but their purpose is not described. Are these files required for Airflow to work?  I think ``airflow//kubernetes_executor_templates/basic_template.yaml`` file is only needed on CI, so we can safely move it to /scripts/ 
```
airflow//kubernetes/pod_template_file_examples/dags_in_image_template.yaml
airflow//kubernetes/pod_template_file_examples/git_sync_template.yaml
airflow//kubernetes/pod_template_file_examples/dags_in_volume_template.yaml
airflow//kubernetes_executor_templates/basic_template.yaml
````
@dimberman Can you help tell more about the purpose of these files?  I want to make sure the packages contain the necessary files to avoid problems similar to https://github.com/apache/airflow/issues/11666
Best regards,
Kamil Breguła

**Comment by potiuk** [comment]
Hey @dimberman - anything that can be clarified here? Maybe short one-two paragraph documentation can be added to explain the purpose of those? It would be great to have it as part of the 2.0.0rc1 docs. Can you please comment on it?

**Comment by kaxil** [comment]
Current docs exists at http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/executor/kubernetes.html

**Comment by kaxil** [comment]
ping @dimberman any updates here?
