### ISSUE TITLE
Master production docker image does not yet have providers installed.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11695]
For some reason despite #11490 the docker image built on DockerHub does not have providers folder.

**Comment by bbossy** [comment]
@potiuk I tracked this down to a typo in the [Dockerfile](https://github.com/apache/airflow/blob/172820db4d2009dd26fa8aef4a864fb8a3d7e78d/Dockerfile#L212):

**ROVIDERS** instead of **PROVIDERS**
```
ARG INSTALL_ROVIDERS_FROM_SOURCES="true"
ENV INSTALL_PROVIDERS_FROM_SOURCES=${INSTALL_PROVIDERS_FROM_SOURCES}
```

**Comment by potiuk** [comment]
AAAAAAAAAAAARGH. I thought I fixed it !!!! but apparently onle the ENV! 

THANKS A LOT ! This is a total bummer !

**Comment by shivanshs9** [comment]
@potiuk damn, I had been facing the same issue for 2 days now and just realized it's due to a typo :sob: 
By when do you think the fix will be live?

**Comment by potiuk** [comment]
> @potiuk damn, I had been facing the same issue for 2 days now and just realized it's due to a typo 
> By when do you think the fix will be live?

Once i get approval I will trigger the build immediately, It should take some ~30/60 minutes to complete for all versions.

**Comment by potiuk** [comment]
Merged. Builds are running in DockerHub. I will let you know when it completes!

**Comment by shivanshs9** [comment]
@potiuk thank you! :tada: :smile:

**Comment by potiuk** [comment]
@shivanshs9 @bbossy -> all shoudl be fixed now in Dockerhub. Tested with: `master-python3.7`

```
docker pull apache/airflow:master-python3.7
````
And the providers are there! 


Thanks @bbossy - I looked at it yesterday a bit and the typo was so mind-cheating that I totally could not see it :)
