### ISSUE TITLE
Celery worker hostname no longer supports %h, %n & %d patterns

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#11697]
The recent [refactoring of the celery Worker process](https://github.com/apache/airflow/commit/02ce45cafec22a0a80257b2144d99ec8bb41c961) dropped the use of `celery.bin.worker.Worker()`, and switched to using the `celery.app.worker.Worker()` class more directly.

Unfortunately, it was the task of the former to format the [Celery hostname patterns](https://docs.celeryproject.org/en/latest/reference/cli.html?highlight=hostname#cmdoption-celery-worker-n).

Unfortunately this refactoring dropped support for hostname patterns (`%h`, `%n`, etc.). Can we re-introduce these? All that is needed is a few `celery.utils.nodenames` calls:

```python
from celery.utils.nodenames import default_nodename, host_format

        # ...
        'hostname': host_format(default_nodename(args.celery_hostname)),
```

**Comment by mik-laj** [comment]
CC: @turbaszek @auvipy

**Comment by turbaszek** [comment]
To be honest, I think we will need to revert #11336 due to #1162, it's more feasible than upgrading to 5.0 as suggested in the latter issue

**Comment by thedrow** [comment]
If this is a problem in general, please file an issue on Celery's repository.

**Comment by turbaszek** [comment]
> If this is a problem in general, please file an issue on Celery's repository.

@mjpieters do you think it may be worth reporting it?

**Comment by mjpieters** [comment]
I _think_ it is a feature of the `celery worker` command, not necessarily of the `Worker` program?

The command-line for that command supports using `%h`, `%n` and `%i` placeholders, and by extension, so did `airflow worker`, and I was grateful for that support. Since Celery puts handling those placeholders in `celery.bin.worker` I'm presuming that they see this separate from `celery.apps.worker`. I haven't looked at how Celery 5 now handles this, since the whole `celery.apps` notion has been dropped.

**Comment by mjpieters** [comment]
I took a look at Celery 5, and there those parameters are very firmly placed in the 'command-line argument' camp, by defining a custom Click [argument type `Hostname`](https://docs.celeryproject.org/en/latest/_modules/celery/bin/worker.html#Hostname), that handles the placeholders when parsing command-line arguments.

**Comment by thedrow** [comment]
I presumed that functionality is related to the CLI itself.
I can fix it or you can come up with a PR, if that's not the case.
