### ISSUE TITLE
Authorization for Flower in the Helm Chart

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11706]
Hello,

The documentation for Helm Chart does not describe how to set up [Flower authorization](https://airflow.readthedocs.io/en/latest/security/flower.html?highlight=flower#flower-authentication) with a password. It would be useful if such documentation was added. It is possible that this will require changes to the Helm Chart to pass the required secrets.

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
@gigkokman can you post a comment here so i can assign you to this ticket?

**Comment by gigkokman** [comment]
May I help this issue?
