### ISSUE TITLE
Disable DAG sync when DAG serialization is enabled in the Helm Chart

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11704]
Hello,

In order to optimize costs and to improve system security, I think it is worth adding the option to disable DAG synchronization in the web container, if the user has enabled DAG synchronization. 

> With DAG Serialization we aim to decouple the webserver from DAG parsing which would make the Webserver very light-weight.

https://airflow.readthedocs.io/en/latest/dag-serialization.html

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
@kaxil @ashb  Is DAG Serialization mature enough to handle this case?

**Comment by ashb** [comment]
Yes, as of 1.10.12 (with the introduction of Rendered template Fields table) the webserver no longer reads dag files with serialisation and store dag code on.

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/11335 should take care of this issue too

**Comment by mik-laj** [comment]
@kaxil  As far as I know, Helm Chart is supposed to support Airflow 1.10 and 2.0, so disabling DAG synchronization for webserver pod should be optional.

**Comment by kaxil** [comment]
> @kaxil As far as I know, Helm Chart is supposed to support Airflow 1.10 and 2.0, so disabling DAG synchronization for webserver pod should be optional.

Yes Helm Chart should still support both, is this Github issue just related to Helm Chart ?

**Comment by mik-laj** [comment]
@kaxil   Yes. I want to disable DAG synchronization in Helm Chart, but only in one pod - webserver.
