### ISSUE TITLE
External Redis database in the Helm Chart

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11705]
Hello

Some users do not want to use Redis provided by Helm Chart, but want to use an external database (installed on the same cluster or in a remote service such as [Cloud Memorystore for Redis](https://cloud.google.com/memorystore/docs/redis)). It would be useful to be able to configure the deployment so that such a database would be used by Celery.

Best regards,
Kamil Breguła

**Comment by FloChehab** [comment]
Hello, just came across this issue.
Just wanted to let you know that we have started working on it a couple days ago: https://github.com/MeilleursAgents/airflow/commit/fb421f80264556e8c07be012ccb837bc82f5ae68 (it should work).

We plan on upstreaming this change at some point.

If the change roughly looks good to you, I can work on upstreaming this a bit earlier than I thought.

**Comment by FloChehab** [comment]
Ok, once this is tested in pré-production on our side, i'll come back to this.

**Comment by mik-laj** [comment]
@FloChehab  This is nothing urgent for me. I wanted to create a ticket to fill in the missing functions before this Helm Chart was released. I think you can wait to release this change as we are changing the unit test framework for Helm Chart. [The new framework](https://github.com/apache/airflow/issues/11657) will be much more convenient and easy, so you can fix your defects much faster.

**Comment by FloChehab** [comment]
Sounds good to me.

**Comment by mik-laj** [comment]
We have already finished the migration to the new framework. Nothing is blocking anymore to work on this change.

**Comment by FloChehab** [comment]
Sorry I miss clicked, I'll work on it very soon.

**Comment by XD-DENG** [comment]
As I mentioned in https://github.com/apache/airflow/pull/12010#issuecomment-757448775 , I'm not sure if this really needs any change in the Chart.

If I'm not wrong in my comment above, we only need a few additional lines in the doc.
