### ISSUE TITLE
Airflow : Windows Worker \ Agent

### ISSUE THREAD

**Issue by tannaalok** [apache/airflow#1171]
Can we install Airflow Worker \ Agent on windows box ? Does Airflow support Windows box as a worker.  I would like Airflow to communicate to windows Server ( SSIS ) box, is this possible ?

**Comment by bolkedebruin** [comment]
@tannaalok No unfortunately Windows is currently not supported. ssis also no directory however airflow has out of the box support for mssql. As ssis has some overlapping functionality with airflow what kind of integration are you looking for?

**Comment by tannaalok** [comment]
Thank you. I am looking to run\ schedule ssis packages using airflow .
