### ISSUE TITLE
Volume mounts not mounted to worker pod

### ISSUE THREAD

**Issue by jakepaw** [apache/airflow#11727]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.17.3

**Environment**: development environment

**What happened**:
My web and scheduler pods are given the volumemounts specified in my values.yaml but once I launch a dag, the pod that airflow creates for this dag does not get the volume mounts specified. How can I tell airflow to mount these to the worker pods that are created through the values file?

**What you expected to happen**:

I want the volume mounts specified to be mounted to the worker pods as well

Not sure. 

**How to reproduce it**:

**Anything else we need to know**:

Something else I would like to know: How are these worker pods configured? Where would I locate the yaml file that templates this pod out?

**Comment by jakepaw** [comment]
@mik-laj Any chance you could give me some pointers to work around this or where in the airflow code I can try create a custom mounting option?

**Comment by mik-laj** [comment]
You should use the [pod_mutation_hook](https://airflow.readthedocs.io/en/latest/kubernetes.html#pod-mutation-hook) or [pod_template_file](https://airflow.readthedocs.io/en/latest/configurations-ref.html#pod-template-file).  In case of problems, please ask on Slack. Github issues is not for asking questions.
