### ISSUE TITLE
Dataflow operators - add user possibility to define expected terminal state

### ISSUE THREAD

**Issue by TobKed** [apache/airflow#11721]
**Description**

Related to the discussion here: https://github.com/apache/airflow/pull/8553#discussion_r416136954

Allow user to define expected terminal state. e.g. `JOB_STATE_CANCELLED` could be not treated as failure but expected terminal state.

**Comment by eladkal** [comment]
@lwyszomi would you be interested in addressing this issue?

**Comment by lwyszomi** [comment]
@eladkal I can take care of this one, please assign it to me.

**Comment by eladkal** [comment]
@lwyszomi are you still working on this issue?

**Comment by lwyszomi** [comment]
@eladkal sorry I was very busy, I will try to find some time in this or next week to fix this issue

**Comment by dannikay** [comment]
Can you please assign this to me?

**Comment by potiuk** [comment]
Done.
