### ISSUE TITLE
"depends_on" functionality for DAGs

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#11739]
Right now, if you want to execute a DAG after another, you have to use a TriggerDagRunOperator, SubDags... What I propose is a little simpler way of making this happen. It consists of adding a new parameter to the dag called depend_on, so it would be as follow:
`with DAG(dag_name, default_args=default_args, depends_on=dag_name_previous_dag):`

The parameter `depends_on` would make `schedule_interval` optional, so that you can choose just executing the DAG after the previous one finishes its execution or including some scheduled executions.

**Comment by eladkal** [comment]
How would this work with case that `dag_name_previous_dag` has more than 1 active run?

**Comment by JavierLopezT** [comment]
> How would this work with case that `dag_name_previous_dag` has more than 1 active run?

With my original idea, every time an active run finishes, the dependant dag will be triggered, no matter how many times. Would be interesting to set some kind of optional limitation though, for some particular cases like the one you present

**Comment by ashb** [comment]
> With my original idea, every time an active run finishes, the dependant dag will be triggered, no matter how many times

You can do this right now by making the final task in the dag a TriggerDagRunOperator.

**Comment by eladkal** [comment]
I'm closing this for now as there is a way to get the requested functionality.
We can reopen if this needs to be revisited.
