### ISSUE TITLE
Docker "read-only" repo with changes from Airflow pushed to it.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11740]
Following a discussion in https://github.com/apache/airflow/issues/8872 I believe it's a good idea to have a separate 'read-only" repository, where only a Dockerfile and corresponding scripts and documentation would be pushed from Airflow automatically.

We still want to keep the Dockerfile in Airlfow's mono-repo, but having a separate Dockerfile that can be conveniently used by the developers woudl be a big plus for anyone who would like to - potentially contribute back to Airflow and use only the "Docker" part of it - Either via subrepo or submodule.

Depends on :

* Airflow 2.0 release
* Merging #12990

**Comment by potiuk** [comment]
cc: @landier

**Comment by mik-laj** [comment]
+1 This will allow us to create a separate README.md file for this image. Currently, In DockerHub README.md from our apache/airflow repository is available, which is not very useful for a Docker image user.

Dockerhub apache/airflow: https://hub.docker.com/r/apache/airflow

I would prefer we had a separate README.md file for the image. The Keycloaak approach is similar
Dockerhub: https://hub.docker.com/r/jboss/keycloak/
README.md for Docker image on Github: https://github.com/keycloak/keycloak-containers/blob/master/README.md
README.md for keycloak project on Github: https://github.com/keycloak/keycloak/blob/master/README.md

**Comment by potiuk** [comment]
Hey @landier - Please take a look at https://github.com/potiuk/airflow-docker where I implemented it. 

You just need to:

1) clone the repo
2) check out the "master" branch
3) run docker build pointing out to the version of Airflow you want to install (see the README)

I think that should do the job nicely :). Please let me know what you think.

I restarted relevant discussion in our monorepo vs. multiple repo thread - where I described how it works: https://lists.apache.org/thread.html/ra4eba1d28ece8b8276067dc2a947f8192a89a43cdb15c1699b8dba7d%40%3Cdev.airflow.apache.org%3E

**Comment by landier** [comment]
Thank, I'll look at it!

**Comment by landier** [comment]
OK so I did some test and it looks perfect: easy to customize the build, low footprint...
I really appreciate this and I'm sure others would/will.

Thanks again.

**Comment by potiuk** [comment]
I will move it to "airflow-docker" repo shortly :)

**Comment by ryw** [comment]
@potiuk this could be moved out of 2.0rc1 milestone I believe.

**Comment by potiuk** [comment]
This work depends on releasing Airflow 2.0 and #12990 merged.

**Comment by potiuk** [comment]
Just FYI - once we relase 2.0, this will be part of Airflow 2.0 "cleanup work"

**Comment by potiuk** [comment]
Not needed after #22492. With the new Biuildkit features we can have the Dockerfile standalone, which removes the need of having a separate repository for Dockerfile as it is just a standalone file
