### ISSUE TITLE
The dependent package version is incompatible

### ISSUE THREAD

**Issue by xqandpan** [apache/airflow#11756]
The **attrs** and **cattrs** packages version is incompatible.
Check command:
`pip check --use-feature=2020-resolver`

Code file: https://github.com/apache/airflow/blob/master/setup.py
Commit hash: 9150330
Line number:
694: 'attrs~=19.3'
696: 'cattrs~=1.0'

It will caused the final installed **attrs** version is higher than 20.1.0.

Why this happen?
From the dependency setting of **cattrs**:
https://github.com/Tinche/cattrs/blob/master/setup.py
Commit hash: 2f401b9
Line number:
12: "attrs >= 20.1.0"

**Comment by mik-laj** [comment]
Do you use constraint files? https://airflow.readthedocs.io/en/latest/installation.html#getting-airflow
