### ISSUE TITLE
RBAC and more customization in Helm Chart

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11755]
Hello,

The Helm community has prepared [best practices for RBAC](https://helm.sh/docs/chart_best_practices/rbac/). 

In particular, it would be useful to make the following changes:
- The path to enable `rbac` should be `rbac.create` instead of `rbacEnabled`.
- It should be possible to disable the creation of each SA individually, but the service account should still be associated with the same resources so that manually-created RBAC resources created later that reference it will function correctly. 
-  It should be possible to configure its own name for each SA individually

Best regards,
Kamil Breguła

**Comment by jaydesl** [comment]
I'll jump on this
