### ISSUE TITLE
Performance degradation in 1.10.12 (https://github.com/apache/airflow/pull/7276/)

### ISSUE THREAD

**Issue by Khrol** [apache/airflow#11780]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

We have a DAG with ~1300 tasks. After the 1.10.11 -> 1.10.12 upgrade Dag file processing time increased from 3-6sec to 150-250sec.

**What you expected to happen**:

It should be quick. 😄 
We extended `AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT` to 600 instead of default 50.

**How to reproduce it**:

One task processing in our Dag takes ~0.3sec. 
Make the call to `get_failed_dep_statuses` method on the task instance from similar DAG.
If the new `NotPreviouslySkippedDep` is removed from dependencies, it's quick again (0.001s and less).

**Anything else we need to know**:

**Comment by kaxil** [comment]
cc @yuqian90 -- Any ideas, thoughts?

**Comment by yuqian90** [comment]
The fix is in master but not in 1.10.*. I tried to cherry pick it in https://github.com/apache/airflow/pull/11010

Once it's merged in 1.10 this slowness will be addressed.

**Comment by Khrol** [comment]
I agree that the fix is not a new feature but a bug fix and should be merged into 1.10.*

**Comment by kaxil** [comment]
Has been merged, will be part of 1.10.13 -- thanks @yuqian90 .

Thanks @Khrol for reporting the issue
