### ISSUE TITLE
links wrapping on standard-width browser

### ISSUE THREAD

**Issue by ryw** [apache/airflow#11795]
on my macbook pro w/ chrome full width…

<img width="1423" alt="Screen Shot 2020-10-23 at 3 01 04 PM" src="https://user-images.githubusercontent.com/4283/97044480-2ce28680-1542-11eb-9a28-cea71e283678.png">

if i bump down to 90%...

<img width="1435" alt="Screen Shot 2020-10-23 at 3 02 08 PM" src="https://user-images.githubusercontent.com/4283/97044866-bf832580-1542-11eb-9e72-1660a52c49f2.png">

so i wonder if we should:

A) reduce font size, or 
B) roll the links up under a gear-icon-dropdown (which would allow us to put words next to the icons, which isn't all bad)

**Comment by ryanahamilton** [comment]
I've got some ideas on how to alleviate this.
