### ISSUE TITLE
provide_context backwards compatibility is broken

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#11798]
Backwards compatibility was broken for provide_context:

https://github.com/apache/airflow/blob/master/UPDATING.md#airflowoperatorspythonpythonoperator
^ states "The change is backwards compatible, setting provide_context will add the provide_context variable to the kwargs (but won't do anything)."

However, https://github.com/apache/airflow/commit/e9d65e3d21f2aa6eaeb557b2960730628540127f came by after the fact and leads to this:

```
Broken DAG: [/dags/dags/nested-mco.py] Traceback (most recent call last):
  File "/some/path/site-packages/airflow/utils/decorators.py", line 92, in wrapper
    result = func(*args, **kwargs)
  File "/some/path/site-packages/airflow/models/baseoperator.py", line 383, in __init__
    c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: parent). Invalid arguments were:
**kwargs: {'provide_context': True}
```

So we can either drop backwards compatibility by removing it from UPDATING.md, or add an exception for `provide_context` with `PythonOperator`. Thoughts?

**Comment by kaxil** [comment]
This has been fixed on Master: https://github.com/apache/airflow/pull/11597

**Comment by jedcunningham** [comment]
@kaxil, 🤦‍♂️, sorry about that.
