### ISSUE TITLE
API request issue with the example dags

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#11862]
Getting the list of dags in the example dags using the rest API is broken due to an example dag with no file location

**Apache Airflow version**:2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When you request for dags using the API dags endpoint, it returns an error as shown below:

```
{
    "detail": "None is not of type 'string'\n\nFailed validating 'type' in schema['allOf'][0]['properties']['dags']['items']['properties']['fileloc']:\n    {'description': 'The absolute path to the file.',\n     'readOnly': True,\n     'type': 'string'}\n\nOn instance['dags'][25]['fileloc']:\n    None",
    "status": 500,
    "title": "Response body does not conform to specification",
    "type": "https://airflow.apache.org/docs/2.0.0a1/stable-rest-api-ref.html#section/Errors/Unknown"
}
```
The reason is that a DAG is introduced in the list of example dags it's supposed to return and that DAG has no fileloc. Here is the DAG:

```
{
            "dag_id": "TEST_DAG_ID",
            "description": null,
            "fileloc": null,
            "is_paused": false,
            "is_subdag": false,
            "owners": [],
            "root_dag_id": null,
            "schedule_interval": null,
            "tags": []
        },
```
I don't know where this dag is coming from.

**What you expected to happen**:

I expected to receive a list of dags in response

**How to reproduce it**:

1. Start breeze and start both the scheduler and webserver
2. Using postman or any tool, request for this endpoint `http://localhost:28080/api/v1/dags`

**Comment by kaxil** [comment]
Can you try with the following command:

```
 ./breeze start-airflow --backend postgres --db-reset
```

and see

**Comment by ephraimbuddy** [comment]
Wow. This solved it!
I should have asked around before opening the issue. Thanks so much
