### ISSUE TITLE
Having Trouble Connecting to Hive Metastore with Kerberos Auth

### ISSUE THREAD

**Issue by adambom** [apache/airflow#1187]
I may be the only one having this problem, but I have had a hell of a time trying to get the `HiveMetastoreHook` to connect. I'm using the updated version that includes impyla, but I still can't connect. The problem seems to be with impyla, which is using [ImpalaHiveServer2Service.Client](https://github.com/cloudera/impyla/blob/master/impala/hiveserver2.py#L648) in its connection factory.

After a bit of debugging I discovered that what we really want to connect with is `ThriftHiveMetastore.Client`, and we can't get that using impyla's connection factory.

I ended up writing a plugin to replace `HiveMetastoreHook` and `HiveMetastoreSensor` (referenced below). It's kind of a one-off solution, and it would be nice if we could figure out a way to integrate this back into Airflow. I'm open to suggestions and ideas for how to approach it. I'm happy to put together a PR but I don't really know what the best way to work this in is. Maybe someone more familiar with the internals of Hive Metastore?

``` python
from airflow.hooks import HiveMetastoreHook
from airflow.operators import HivePartitionSensor
from airflow.plugins_manager import AirflowPlugin
from airflow.utils import apply_defaults

from impala._thrift_gen.hive_metastore import ThriftHiveMetastore

import sasl

from thrift.protocol import TBinaryProtocol
from thrift.transport.TSocket import TSocket

from thrift_sasl import TSaslClientTransport


class KerberosHivePartitionSensor(HivePartitionSensor):

    @apply_defaults
    def __init__(self, *args, **kwargs):
        super(KerberosHivePartitionSensor, self).__init__(*args, **kwargs)
        self.hook = KerberosHiveMetastoreHook(
            metastore_conn_id=self.metastore_conn_id,
            kerberos_service_name=kwargs.get('kerberos_service_name', 'hcat'))


class KerberosHiveMetastoreHook(HiveMetastoreHook):
    def __init__(
        self,
        metastore_conn_id='metastore_default',
        kerberos_service_name='hcat'
    ):
        self.kerberos_service_name = kerberos_service_name
        super(KerberosHiveMetastoreHook, self).__init__(
            metastore_conn_id='metastore_default')

    def get_metastore_client(self):
        '''
        Returns a Hive thrift client.
        '''
        ms = self.metastore_conn
        sock = TSocket(ms.host, ms.port)

        def sasl_factory():
            sasl_client = sasl.Client()
            sasl_client.setAttr('host', ms.host)
            sasl_client.setAttr('service', self.kerberos_service_name)
            sasl_client.init()
            return sasl_client
        transport = TSaslClientTransport(sasl_factory, 'GSSAPI', sock)
        protocol = TBinaryProtocol.TBinaryProtocol(transport)
        return ThriftHiveMetastore.Client(protocol)


class KerberosHivePartitionSensorPlugin(AirflowPlugin):
    name = 'KerberosHivePartitionSensor'
    operators = [KerberosHivePartitionSensor]
    hooks = [KerberosHiveMetastoreHook]
```

**Comment by bolkedebruin** [comment]
Ah that is Interesting. Impyla basically does not support hivemetastore connections as you have found out. But are you using Python 3? As the current version should still work with Python 2 so i am curious.

**Comment by bolkedebruin** [comment]
Ah for hivemetastore I did not implement the Kerberos part so that would not have worked indeed even for py3. I am tempted to wait for a release of thrift 1,0 that should support py3 which then allows better integration.

**Comment by adambom** [comment]
Using Python 2.7.

**Comment by bolkedebruin** [comment]
Can you check if PR-#1128 works for you?

**Comment by bolkedebruin** [comment]
Please report back on Jira if the issue still persists
