### ISSUE TITLE
Logout issues with Google Auth backend

### ISSUE THREAD

**Issue by VictorGeaGarcia** [apache/airflow#11889]
**Apache Airflow version**: 1.10.x

**What happened**:

With Google Auth configured and enabled, when I try to logout I cannot because it automatically logins back:

![image](https://user-images.githubusercontent.com/26174942/97306091-447d8000-185e-11eb-8531-1d6c7c896846.png)

This happens because [Google Auth request token params](https://github.com/apache/airflow/blob/v1-10-stable/airflow/contrib/auth/backends/google_auth.py#L97) is not using "prompt" as documented [here](https://developers.google.com/identity/protocols/oauth2/web-server#userconsentprompt). 

A new config param should be allowed, 'prompt'. With values: 'consent', 'select_account', 'none' or ''

**What you expected to happen**:

 The session should be terminated and you should be redirected back to the Login Page.

**How to reproduce it**:
Google Auth enabled using following config [(as documented here)](http://airflow.apache.org/docs/stable/security.html#setting-up-google-authentication)

```
[webserver]
authenticate = True
auth_backend = airflow.contrib.auth.backends.google_auth

[google]
client_id = *****
client_secret = ****
oauth_callback_route = /oauth2callback
domain = ****
```

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/11890
