### ISSUE TITLE
Rest api and kubernetes executor 

### ISSUE THREAD

**Issue by Hartorn** [apache/airflow#11881]
Apache airflow version:1.10.12
Env: GKE kubernetes cluster (Google) 

Hello,

Not sure if this is an issue, or a misunderstanding from my side, but I'm using airflow rest api to trigger dag run with input args (some ids).

Locally, in docker compose using celery executor, everything works fine, but when using kubernetes executor in gke, we are having troubles, we can see pod launching but :
- logs from the dags does not appear into the webserver
- the run does not received arguments given in rest api (we managed to get logs by mounting volume and getting logs from there)

The docker image we use is a built in image with airflow installed in it, and dags also in it.

What information do you need to help us? Or do you have any examples or idea of what we are doing wrong?

Cheers

Edit: sry about template, I am on my phone, I'll update the issue with proper format as soon as I got access to a computer

**Comment by mik-laj** [comment]
Github Issues is not for technical support, only for handling confirmed bugs. Please ask on #troubleshooting or #airflow-kubernetes channel. [![Slack Status](https://img.shields.io/badge/slack-join_chat-white.svg?logo=slack&style=social)](https://s.apache.org/airflow-slack)
