### ISSUE TITLE
SmartSensor poke interval handling

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#11894]
Currently, the smart sensor group DAG creates smart sensors for all shards with a fixed poke interval, 180 seconds.

This should really be configurable.

Moreover, the sensor should find some kind of compromise between running at a fixed rate and honouring the original `poke_interval` values of the sensor operators it replaces. Now _all_ sensors managed by the smart sensor dag will be poked every 180 seconds, regardless.

This could be handled like a cron scheduler instead: poke all the sensors that would have been poked since the last time the smart sensor ran, based on their `poke_interval` and `exponential_backoff` values.

E.g. record and cache the next poke execution time per managed sensor, and only poke those whose next execution time has passed.

**Comment by YingboWang** [comment]
@mjpieters Thanks for creating this issue. We do have the plan to support customized poke_interval in smart sensor and will implement it. As for now, the smart sensor operator class has a default of poke_interval as 180 and it could be changed by adding `poke_interval=xxx` in the `smart_sensor_group.py` when creating the `SmartSensorOperator` task. By doing it all smart sensor tasks in an airflow cluster will poke more aggressively with the input `poke_interval`. We could also make this field configurable by airflow.cfg if needed.

**Comment by mjpieters** [comment]
I suppose I could use the [`policy()` hook](https://airflow.apache.org/docs/stable/concepts.html#mutate-tasks-after-dag-loaded) to alter the sensor poke interval. I don't think asking people to alter the shipped Airflow code directly is a good idea, at any rate.

As for honouring managed sensors' poke intervals, I was thinking along the lines of the [standard library `sched` module implementation](https://github.com/python/cpython/blob/3.9/Lib/sched.py), so a heapqueue (but using a `time.monotonic()` rather than `time.time()` to avoid running into DST issues).

**Comment by anthonyp97** [comment]
@YingboWang can we also make the `poke_timeout` in the `SmartSensorOperator` configurable by `airflow.cfg` as well? It is currently set as 10 seconds by default in `smart_sensor_group.py` but often times our sensors require more time than this to run and as a result we are getting flooded with Airflow Process timed out errors.

**Comment by YingboWang** [comment]
I agree that this should be configurable as the poke time varies based on
environment and sensor differences. I will create a PR to fix it.

**Comment by eladkal** [comment]
I'm closing this as probably we won't add new features to Smart Sensors since Deferrable Operators essentially supersede Smart Sensors. See docs: https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html#smart-sensors
