### ISSUE TITLE
To show failure message when task is externally killed in queued state

### ISSUE THREAD

**Issue by mek97** [apache/airflow#11896]
**Apache Airflow version**: 1.10.12

**What happened**:
If a task is scheduled in `queued` state and the process associated to it with `airflow run` command is externally killed, the task goes in the failed state as expected but no meaningful failure messages or logs are shown. Following is a screenshot as an example.

<img width="472" alt="Screenshot 2020-10-24 at 9 18 45 PM" src="https://user-images.githubusercontent.com/29342858/97141690-3c9ddd00-1785-11eb-9933-e30f369b7798.png">

**What you expected to happen**:
Task to fail with a meaningful failure message

**Comment by eladkal** [comment]
The information should be available in the task log.
