### ISSUE TITLE
Cannot get example_branch_operator to perform any executions.

### ISSUE THREAD

**Issue by davidaventimiglia-personal** [apache/airflow#119]
Hi

I have AirFlow version 1.2 set up, with the four example DAGs.  When I try to run example_branch_operator like so

`airflow run example_branch_operator follow_branch_a 2015-01-01`

or with any other date, then when I refresh the DAGs view in the web-server UI, I see no change in its executions.  The successful executions does not increment, but neither do any of the others.  It's as if nothing happened.

When I run example_python_operator like so

`airflow run example_python_operator print_the_context 2015-01-01`

then I get a successful execution for that date.  As I re-run it with other dates, the successful executions increment.  Why does the example_branch_operator DAG not exhibit this same behavior?  Thanks

**Comment by mistercrunch** [comment]
If the dependencies aren't met, the task won't execute and record any state. It will print something about the reason it isn't running in the log file though. Is that the case?

**Comment by davidaventimiglia-personal** [comment]
Yes, it is.  I misunderstood. I thought in the checking of dependencies, `airflow run` ensure that upstream tasks also get run.  Evidently, that is not the case.  It seems that `airflow run` behaves more like `airflow test` and less like `airflow backfill`.  I think what I want to do in order to test a whole DAG, "from soup to nuts" is to use `airflow backfill`.  I'm curious what the use cases for `airflow test` and `airflow run` are.

**Comment by mistercrunch** [comment]
- `airflow test`: test a single task instance, get the logs printed out as stdout, no dependency checks, status of run doesn't get recorded. Typically you'd be working on a local branch and making sure you tasks work.
- `airflow run`: trigger a single task instance as it would run in production. I has flags to force a run or ignore the dependencies. Note that `airflow run` is used internally by the scheduler and backfill.
