### ISSUE TITLE
My Airflow Always stay scheduled state!

### ISSUE THREAD

**Issue by BestJiayi** [apache/airflow#11907]
My Airflow Always stay scheduled state! What should I do?

This is my code:
default_args = {
    'owner': 'taqu',
    'depends_on_past': False,
    'email': [],
    'email_on_failure': False,
    'email_on_retry': False,
    # 'on_success_callback': callback.task_success_dtalk_callback,
    "on_failure_callback": callback.task_failure_dtalk_callback,
    'retries': 1,
    'retry_delay': timedelta(minutes=3),
}

tz = pytz.timezone('Asia/Shanghai')
dt = datetime(2020, 6, 17, tzinfo=tz)
utc_dt = dt.astimezone(pytz.utc).replace(tzinfo=None)

dag = DAG('FeedsFM',
          default_args=default_args,
          description='A series of stat task.',
          start_date=utc_dt,
          schedule_interval="15 7 * * *",
          catchup=False  
          )

post_topic = BashOperator(
    task_id='post_topic',
    bash_command='/data/cron/feature-engineering/apps/PostTopic.sh ',
    dag=dag,
    pool="spark",
)

**Comment by turbaszek** [comment]
@BestJiayi please provide useful information about you issue. The bug report template by help you.

**Comment by BestJiayi** [comment]
> @BestJiayi please provide useful information about you issue. The bug report template by help you.

Hi, turbaszek,my airflow dosen't work. It's always stay in scheduled status, what should I do?
