### ISSUE TITLE
BigQuery support for create or replace table

### ISSUE THREAD

**Issue by shaneikennedy** [apache/airflow#11911]
**Description**

BigQuery supports multiple [create table statements](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement), one of which is create or replace. 

**Use case / motivation**

This would be really nice for batch processing because I can write a DAG that is: `create-table >> insert-data` and the operation is idempotent. Right now, the BiqQueryCreateEmptyTable operator fails if the table already exists, which means my dag needs some logic to see if I should actually run this operator.

**Related Issues**

Not that I could find

**Comment by manesioz** [comment]
I agree this functionality would be super useful! I would love to hear what you and the maintainers think about how to design this. 

It seems like we have to consider how we deal with the case when we wish to create a table when a table by the same name already exists in the dataset. We could: 

1) Fail. This is consistent with the `CREATE TABLE IF NOT EXISTS` DDL, and it seems like the current `BigQueryCreateEmptyTableOperator` works like this as well. 

2) Overwrite the existing table with the new table. This is consistent with the `CREATE OR REPLACE TABLE` DDL. This would be a new feature, and could possibly be added as a boolean option in the existing operator, or a completely new operator altogether. 

Example: 

```python
create_table = BigQueryCreateTableOperator(
    task_id="create_table",
    dataset_id=DATASET_NAME,
    table_id="test_table",
    replace=True, # this will create AND replace any existing tables with the same name in the same dataset 
    schema_fields=[
        {"name": "emp_name", "type": "STRING", "mode": "REQUIRED"},
        {"name": "salary", "type": "INTEGER", "mode": "NULLABLE"},
    ],
)
```
If `replace=False` then it should fail if a table exists by the same name in the same dataset. 

Am I missing something? What are everyones thoughts? I'd love to work on a PR for this if possible.

**Comment by mik-laj** [comment]
CC: @turbaszek

**Comment by turbaszek** [comment]
@shaneikennedy @manesioz this functionality is already available for Airflow users by using `BigQueryInsertJobOperator` and `query` job:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#api

Despite this fact I think it would be more user friendly to add `delete_if_exists` flag and delete existing table in `BigQueryCreateEmptyTableOperator` if there's a conflict (we already have logic that handles existing table).

**Comment by kumarvt** [comment]
I believe the "CREATE TABLE IF NOT EXISTS" is not implemented in this operator and I believe that will be very useful, whenever we need to create the target table only first time using JSON schema (that has several columns as required). I looked at the create table as select but that changes the mode  of all columns to NULLABLE in target table.

**Comment by eladkal** [comment]
I believe this already implemented.
See `exists_ok` parameter
https://github.com/apache/airflow/blob/acaa0635c8477c98ab78da9f6d86e6f1bad2737d/airflow/providers/google/cloud/operators/bigquery.py#L784

**Comment by jkukul** [comment]
@eladkal `exists_ok` parameter doesn't allow to replace a table if it exists. It will make the operator simply not create a table if it already exists. It corresponds to `CREATE TABLE IF NOT EXISTS` DDL statement.

This feature request is about adding a parameter to mimic the `CREATE OR REPLACE TABLE` DDL. It remains unresolved and I believe it should be re-opened.

**Comment by eladkal** [comment]
thanks for the clarification.
@jkukul would you like to raise a PR?

**Comment by vchiapaikeo** [comment]
It doesn't look like the [API supports a replace_if_exists / delete_if_exists parameter](https://github.com/googleapis/python-bigquery/blob/v2.34.4/google/cloud/bigquery/client.py#L702-L761). It will simply raise a `google.cloud.exceptions.Conflict` if the table exists, unless `exists_ok` is set to True. 

Is the desired behavior for a `delete_if_exists` or `replace_if_exists` flag to delete the table and recreate it if the table already exists? Also, is it okay if this type of operation is not atomic? We will need to delete the table first and then recreate it. I'm not sure how CREATE OR REPLACE TABLE is implemented under the hood.

It's also unusual how such a `replace_if_exists` parameter would work with the `exists_ok` parameter. Should the `replace_if_exists` parameter take precedence? Or should we only do the delete/recreate if `exists_ok` is set to False and `replace_if_exists` is set to True? I kinda prefer that approach so it's clear that the user is not okay with the table existing. (exists_ok currently defaults to False and a replace_if_exists param would obviously default to False as well).

**Comment by shahar1** [comment]
> It doesn't look like the [API supports a replace_if_exists / delete_if_exists parameter](https://github.com/googleapis/python-bigquery/blob/v2.34.4/google/cloud/bigquery/client.py#L702-L761). It will simply raise a `google.cloud.exceptions.Conflict` if the table exists, unless `exists_ok` is set to True.
> 
> Is the desired behavior for a `delete_if_exists` or `replace_if_exists` flag to delete the table and recreate it if the table already exists? Also, is it okay if this type of operation is not atomic? We will need to delete the table first and then recreate it. I'm not sure how CREATE OR REPLACE TABLE in standard BQ SQL is implemented under the hood.
> 
> It's also unclear how such a `replace_if_exists` parameter would work with the `exists_ok` parameter. Should the `replace_if_exists` parameter take precedence? Or should we only do the delete/recreate if `exists_ok` is set to False and `replace_if_exists` is set to True? I kinda prefer that approach so it's clear that the user is not okay with the table existing. (exists_ok currently defaults to False and a replace_if_exists param would obviously default to False as well).
> 
> An aside - for tables that get appended to, this operation could be quite dangerous - since a user will lose all their historical data as a result. Just worth mentioning that this should only be done for tables that are truncated / recreated and are okay with non-atomicity.

I agree with your statement - as long as BQ API doesn't support it as an atomic operation natively, I don't see a good reason to maintain a specific operator for that.

**Comment by eladkal** [comment]
So the preferred action is to do nothing until big query API supports this action natively?
If so I will close this ticket
