### ISSUE TITLE
Add how-to Guide for WinRM operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11914]
**Description**

A guide that describes how to use all the operators for WinRM (https://github.com/apache/airflow/tree/master/airflow/providers/microsoft/winrm) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil

**Related Issues**

Missing guides for operators in Microsoft provider:
- Azure: https://github.com/apache/airflow/issues/11912
- MSSQL: https://github.com/apache/airflow/issues/11913

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi,
The [link ](https://github.com/apache/airflow/tree/master/docs/howto/operator)specified for source code guides is not working for me.
Please can you advice if this has moved to another location?

**Comment by kaxil** [comment]
Yes, the link has moved to [https://github.com/apache/airflow/tree/master/docs/apache-airflow-providers-microsoft-winrm](https://github.com/apache/airflow/tree/master/docs/apache-airflow-providers-microsoft-winrm)

You can take a look at MySQL example: https://github.com/apache/airflow/tree/master/docs/apache-airflow-providers-mysql-

**Comment by Melodie97** [comment]
I would like to work on this issue

**Comment by eladkal** [comment]
added in https://github.com/apache/airflow/pull/21344
