### ISSUE TITLE
Add how-to Guide for Slack operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11919]
**Description**

A guide that describes how to use all the operators for Slack (https://github.com/apache/airflow/tree/master/airflow/providers/slack/operators) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil﻿

**Comment by msb217** [comment]
Hi Kaxil - do you mind if I take on this issue?

**Comment by kaxil** [comment]
Assigned it to you @msb217 :)

**Comment by eladkal** [comment]
@msb217 are you working on this issue?

**Comment by abrooks-nyt** [comment]
I'd like to work on this.

**Comment by ariesunique** [comment]
Hi @potiuk ,
I'd like to work on this.

**Comment by zkan** [comment]
@ariesunique Are you working on this?

**Comment by ariesunique** [comment]
Yes - still looking into this.

**Comment by kaxil** [comment]
@ariesunique Are you working on this?

**Comment by ariesunique** [comment]
No. Someone else can take it.

**Comment by kevin1kevin1k** [comment]
I would like to contribute to this!

**Comment by uranusjr** [comment]
🏃‍♂️

**Comment by eladkal** [comment]
solved in https://github.com/apache/airflow/pull/18525
