### ISSUE TITLE
Add how-to Guide for Databricks Operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11916]
**Description**

A guide that describes how to use all the operators for Azure (https://github.com/apache/airflow/tree/master/airflow/providers/databricks/operators) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil﻿

**Comment by sharad-vm** [comment]
@kaxil I'm a newbie here and would like to start contributing to Airflow with this.

**Comment by kaxil** [comment]
Awesome, assigned
