### ISSUE TITLE
Add how-to Guide for Postgres operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11917]
**Description**

A guide that describes how to use all the operators for Postgres (https://github.com/apache/airflow/tree/master/airflow/providers/postgres) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil﻿

**Comment by sunnygupta05** [comment]
Hey @kaxil Can you please assign this to me. May be a good start to become a open source committer. Thank you for opportunity.

**Comment by eladkal** [comment]
@sunnygupta05 assigned to you
