### ISSUE TITLE
Add how-to Guide for MySQL operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11918]
**Description**

A guide that describes how to use all the operators for MySQL (https://github.com/apache/airflow/tree/master/airflow/providers/mysql/operators) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil

**Comment by jfmolano** [comment]
Hi Kaxil, I am a newbie at open source contributions but I love AirFlow and I would like to contribute with this.

Can you assign this to me?

Regards

**Comment by kaxil** [comment]
Assigned it to you @jfmolano :)

**Comment by jfmolano** [comment]
Dear @kaxil I'm working on the MySql example DAG for the documentation and I have a question. I see that some example DAGS are in the airflow/example_dags folder but others are in the (i.e.) airflow/providers/snowflake/example_dags. Where should they be stored? Another question is whether example DAG should have unit tests.

**Comment by kaxil** [comment]
> Dear @kaxil I'm working on the MySql example DAG for the documentation and I have a question. I see that some example DAGS are in the airflow/example_dags folder but others are in the (i.e.) airflow/providers/snowflake/example_dags. Where should they be stored? Another question is whether example DAG should have unit tests.

Hi @jfmolano The examples under `airflow/example_dags` folder are for operators in https://github.com/apache/airflow/tree/master/airflow/operators i.e. the CORE operators. Whereas the example_dags for any specific provider (Company / Org / Tech) live under that specific provider directory. Example `airflow/providers/snowflake/example_dags` contains example dags for Snowflake `airflow/providers/snowflake`

**Comment by jfmolano** [comment]
Thank you, it is clear for me now :)
