### ISSUE TITLE
Add how-to Guide for Azure operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11912]
**Description**

A guide that describes how to use all the operators for Azure (https://github.com/apache/airflow/tree/master/airflow/providers/microsoft/azure) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil

**Related Issues**

Missing guides for operators in Microsoft provider:
- MSSQL Operators: https://github.com/apache/airflow/issues/11913
- WinRM: https://github.com/apache/airflow/issues/11914

**Comment by sunnygupta05** [comment]
Hey @kaxil Can you please assign this to me. May be a good start to become a open source committer. Thank you for opportunity.

**Comment by kaxil** [comment]
Assigned it to you, looking forward :)

**Comment by pyerbiz** [comment]
I volunteer -- I can do it in a similar way to the aws one I did (pending approval) https://github.com/apache/airflow/pull/16964

**Comment by potiuk** [comment]
Assigned you :)

**Comment by pyerbiz** [comment]
Curious why was this PR done? 
https://github.com/apache/airflow/pull/15651/files

**Comment by pyerbiz** [comment]
Missing Doc List

**Provider_file,Example,Doc,Doc-Action**

adls_delete.py,1,1,rename doc
adls_list.py,0,0
adx.py,0,0
azure_batch.py,0,0
azure_container_instances.py,1,0
azure_cosmos.py,1,0,
wasb_delete_blob.py,0,0,
transfers/azure_blob_to_gcs.py,0,1
transfers/file_to_wasb.py,1,0
transfers/local_to_adls.py,1,1
transfers/oracle_to_azure_data_lake.py,0,0

**Comment by pyerbiz** [comment]
I am still working on this, its just been a hectic few weeks!

**Comment by kaxil** [comment]
Sure, can you create a PR for it

**Comment by eladkal** [comment]
Both tasks listed on the description are resolved so i'm closing this issue
