### ISSUE TITLE
Add how-to Guide for Snowflake operators

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11921]
**Description**

A guide that describes how to use all the operators for Snowflake (https://github.com/apache/airflow/tree/master/airflow/providers/snowflake/operators) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kaxil﻿

**Comment by davido912** [comment]
@kaxil I can start with picking up this one, anything specific that is important for you guys to note or are all style wise should be similar to the ones on the website already?

**Comment by kaxil** [comment]
Something similar to https://airflow.readthedocs.io/en/latest/howto/operator/google/cloud/bigquery.html or https://airflow.readthedocs.io/en/latest/howto/operator/amazon/aws/datasync.html which just tells Users who they can use the Operator would be good enough :)

Thanks for picking this task up, appreciate it.
