### ISSUE TITLE
Web UI should fetch operator links in one request

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#11928]
Operators can define additional extra links to be displayed on the task instance. While most implementations limit to just a few links, the web UI code is loading each value with a separate request:

https://github.com/apache/airflow/blob/86ed7dcd687627412e93620ec5da7f05e2552ae7/airflow/www/templates/airflow/dag.html#L503-L532

That's not a very efficient way of loading these values. This should really be a single AJAX request that fetches all the task links; it could simply repeat the `link_name` parameter, and the server could send back a JSON object with link name -> URL entries.

**Comment by Google987** [comment]
Hi guys,
Can anyone please guide me with this one?
By the code snippet, I understood that the ajax call is done for every `link`. But we are supposed to do a single call and process the response object instead. 
I've forked the repo and cloned in my local system. I found this code in `dag.html`
But I'm not sure where these ajax calls are handled.
