### ISSUE TITLE
BaseBranchOperator isn't used anywhere

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#11931]
This is not a bug but more a question/observation about `BaseBranchOperator` that was added in  https://github.com/apache/airflow/pull/5231

Both [BranchPythonOperator](https://github.com/apache/airflow/blob/master/airflow/operators/python.py#L308) and [BranchSQLOperator](https://github.com/apache/airflow/blob/master/airflow/operators/sql.py#L476) inherit from `BaseOperator` and not from  [BaseBranchOperator](https://github.com/apache/airflow/blob/master/airflow/operators/branch_operator.py#L26)

So what `BaseBranchOperator` is used for? only for custom user branching operator? It's a bit odd that Airflow has 2 branching operators that don't use the Base.

The interesting part is that it used to be the parent class of `BranchSQLOperator` in the previous path of [sql_branch_operator.py](https://github.com/apache/airflow/blob/master/airflow/operators/sql_branch_operator.py#L28) but was changed for some reason.

**Comment by mik-laj** [comment]
@RosterIn This is used to express your own business logic.

**Comment by eladkal** [comment]
It is being used:
https://github.com/apache/airflow/blob/9070ba280253e918c2582f52c2b77a07c311198f/airflow/operators/weekday.py#L27
https://github.com/apache/airflow/blob/9070ba280253e918c2582f52c2b77a07c311198f/airflow/operators/datetime_branch.py#L27
