### ISSUE TITLE
Add new password users

### ISSUE THREAD

**Issue by adambom** [apache/airflow#1195]
From the docs (and a scan of the code) I don't see any easy way to create new users other than from a python shell.

The behavior I'd expect is for an admin to go to the users page and enter a username/email, and for the webserver to use the smtp settings to send an email to the new user with a link to set their password. As far as I can tell this isn't happening.

Have I messed something up, or is there another approach to creating new authenticated users?

**Comment by bolkedebruin** [comment]
Please ask this on the mailinglist. Thanks!
