### ISSUE TITLE
Documentation on Installation page has incorrect version

### ISSUE THREAD

**Issue by yyf6413** [apache/airflow#11977]
**Apache Airflow version**: 1.10.11

**What happened**:
On this page https://airflow.apache.org/docs/1.10.11/installation.html#getting-airflow, section 1 & 2, I think the 
airflow version in the pip install command is incorrect, it shows `apache-airflow==1.10.10`.
It should be `apache-airflow==1.10.11`

**Comment by mik-laj** [comment]
We only update the latest documentation and the latest documentation correctly says 1.10.12 so I'm closing this ticket because we can't take any action.
