### ISSUE TITLE
Argument image_pull_policy not applied inside KubernetesPodOperator

### ISSUE THREAD

**Issue by jrderuiter** [apache/airflow#11998]
**Apache Airflow version**:
2.0.0.a2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
v1.18.8

**Environment**:

- **Cloud provider or hardware configuration**: Docker image
- **OS** (e.g. from /etc/os-release): macOS Catalina (Docker for mac)
- **Kernel** (e.g. `uname -a`): -
- **Install tools**: - 
- **Others**: - 

**What happened**:

I'm trying to run a KubernetesPodOperator with a local docker image by specifying image_pull_policy="IfNotPresent" or image_pull_policy="Never":

```
KubernetesPodOperator(
        task_id="fetch_ratings",
        image="manning-airflow/movielens-fetch",
        cmds=["fetch-ratings"],
        arguments=[
            ...
        ],
        namespace="airflow",
        name="fetch-ratings",
        cluster_context="docker-desktop",
        in_cluster=False,
        volumes=[volume],
        volume_mounts=[volume_mount],
        image_pull_policy="Never",
    )
```

This worked before in 1.10.12 with the provider backport, but now it fails as the policy is not applied and Kubernetes tries to pull the image from a remote repo.

**What you expected to happen**:

I expect the operator to apply the policy and use the local docker image. 

**How to reproduce it**:

Build a local docker image and try to run it with the KubernetesPodOperator with the image_pull_policy set to Never. 

**Anything else we need to know**:

Looking through the implementation of the current operator, I don't see the argument actually being used anywhere. It should probably be passed to the container definition.

**Comment by Giuzzilla** [comment]
Hey, any hope of getting #12000 merged? I'm using that fix in production and it works perfectly. Thank you!

**Comment by Junnplus** [comment]
@Giuzzilla https://github.com/apache/airflow/pull/13289 already merged. It seems to have to wait until 2.0.1 for release.
