### ISSUE TITLE
S3ToSnowflakeTransfer enforces usage of schema parameter

### ISSUE THREAD

**Issue by davido912** [apache/airflow#12001]
Unlike all other Snowflake operators, S3ToSnowflakeTransfer requires the usage of schema instead of letting it be an optional variable that when passed would be used, and if not, then connection metadata is used. 

I can be assigned on this if needed. Keeping this up here so this doesn't go unnoticed.

**Comment by eladkal** [comment]
@davido912 assigned the issue to you :)
