### ISSUE TITLE
Add `files` to templated fields of `EmailOperator`

### ISSUE THREAD

**Issue by KIC** [apache/airflow#12028]
**Description**

Files are not part of the templated fields in the `EmailOperator` https://airflow.apache.org/docs/stable/_modules/airflow/operators/email_operator.html

Whle in fact file names should also be templated .

**Use case / motivation**
We want to store files accordingly to the DAGs execution date and further send them to email recipients like so:

```
send_report_email = EmailOperator(
        ....
        files=[
            "/tmp/Report-A-{{ execution_date.strftime('%Y-%m-%d') }}.csv",
            "/tmp/Reportt-B-{{ execution_date.strftime('%Y-%m-%d') }}.csv"
        ]
```

**Comment by contributor13** [comment]
I would like to fix this issue. Can anyone please explain that what exactly needs to be done.

**Comment by turbaszek** [comment]
@contributor13 would you like to work on this one?

**Comment by phraniiac** [comment]
Hi @turbaszek , I can try to take this up if there is no one else been involved yet.

**Comment by brighton1101** [comment]
I have a solution I believe to be working above :)
