### ISSUE TITLE
Airflow WebUI style broken

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12030]
**Apache Airflow version**:
2.0.0 - master branch

**Environment**:

- **OS** (e.g. from /etc/os-release): MacOS 10.15.7
- **Browser**: Safari Version 13.1.3 (15609.4.1)

**What happened**:

The row in tis table is wider than 100% width
<img width="1440" alt="Screenshot 2020-11-02 at 11 11 39" src="https://user-images.githubusercontent.com/9528307/97856398-85f9a980-1cfc-11eb-89ed-d739ecb0f51c.png">

**What you expected to happen**:

I expect the row to not overflow.

**How to reproduce it**:

Go to http://0.0.0.0:28080/taskinstance/list

**Anything else we need to know**:

N/A

**Comment by turbaszek** [comment]
CC @ryanahamilton

**Comment by msumit** [comment]
I too had observed it earlier, but as of now, I'm getting a scroll instead of the overflow.

**Comment by ryanahamilton** [comment]
I fixed a similar issue on the the DAGs (home) view just last week in #11958. This example is in the FAB generated views. I'll PR a similar type of fix for these as well.
