### ISSUE TITLE
Fix description of some extra packages

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12042]
**Description**

The PR #12023 added consistency check for documentation and setup.py. However few packages need additional description:

- [x] pagerduty
- [ ] plexus
- [ ] sentry
- [x] singularity
- [ ] tableau
- [ ] virtualenv

This is a great "good-first-issue" 

**Use case / motivation**

Descriptions should be complete.

**Comment by szn** [comment]
Can you guys help me updating `/docs/installation.rst` documentation file? All the packages mentioned below are listed there. But the description is missing (and not obvious for me) plus I am not sure if they are listed in a proper section:

1. @houqp you added `pagerduty` in d25ef2b2abc3da9f5725a3c433bc035b970eec23
2. @millertracy you added `Plexus` in b9dc3c51ba2cba1c61d327488cecf2623d6445b3
3. @tiopi you added `Sentry` in dc3bfe470c2d6ad9cda801635e3514088d38aed5
4. @vsoch you added `singularity` in 0bb687990b94da7445f4ba081592de8cea73119e
5. @feluelle you added `Tableau` in a9ad0a929851b6912e0bb8551f1ff80b50281944
6. @potiuk you added `virtualenv` in 7448d3c0cd85770021c230bbea33f758718e300b

**Comment by vsoch** [comment]
yes of course! Will open a PR soon.

**Comment by houqp** [comment]
@szn sent a PR to add description for pagerduty provider.

**Comment by szn** [comment]
@potiuk @feluelle @tiopi @millertracy we can save your time. Instead of creating four separate PR-s (each changing a single line of documentation), you can just write a valid description here and I'll handle the update.

I believe that's faster for you guys.

**Comment by potiuk** [comment]
Indeed. Good point @szn 

* plexus: Plexus service of CoreScientific.com AI platform
* sentry:  Sentry service for application logging and monitoring
* tableau: Tableau visualization integration
* virtualenv: Running python tasks in  local virtualenv

**Comment by szn** [comment]
@potiuk can you generate a description for `yandexcloud` as well? Is it _Yandexcloud hooks and operators_?

**Comment by szn** [comment]
> @potiuk can you generate a description for `yandexcloud` as well? Is it _Yandexcloud hooks and operators_?

I Googled that, and assumed **yes**.

Here is PR: https://github.com/apache/airflow/pull/12141
