### ISSUE TITLE
KubernetesExecutor: Add support for launching Jobs instead of Pods

### ISSUE THREAD

**Issue by ctso** [apache/airflow#12074]
**Description**

Kubernetes [suggests avoiding the use of bare Pods](https://kubernetes.io/docs/concepts/workloads/controllers/job/#bare-pods) for workloads and instead recommends using a `Job` or some other resource that has a `ReplicationController` associated with it.  While there are certainly some risks involved when the Kubernetes cluster is able to make a decision about restarting a Pod, in my opinion it would be nice to have the option to run Jobs instead of Pods.

**Use case / motivation**

In a situation where Airflow is simply a tenant of a larger Kubernetes cluster, having bare pods running can lead to confusion for the operators of the Kubernetes cluster.  Using Jobs would allow operations like `kubectl drain {node}` to happen without knowledge of Airflow and its workload.

**Comment by mik-laj** [comment]
It's a good idea, but can be difficult to implement. Airflow has protection against double task execution.  If we wanted to do it right, we needed to synchronize the number of execution attempts between Kubernetes.and Airflow.

**Comment by Reddy1990** [comment]
Hi, is there anyway that the pod created in the first execution of task can be reused for the next scheduled run. Instead of creating a new pod for every run. I have a batch job that runs for every minute in this scenario I want the pod to be running and make use of the existing pod. I'm aware its possible in direct K8s, but I want use Airflow for managing my tasks.

**Comment by jscheffl** [comment]
I close this now as I see the k8s provider package already provides a JobOperator as of today:
https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html#kubernetesjoboperator
