### ISSUE TITLE
PapermillOperator does not take user defined macros

### ISSUE THREAD

**Issue by humbledude** [apache/airflow#12081]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.15.11

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
- When initialize DAG, I defined `user_defined_macros` with my macros.
- If I use user defined macro on PapermillOperator, it does not find user defined macros.

```
[2020-11-04 16:35:10,822] {taskinstance.py:1150} ERROR - 'seoul_date' is undefined
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/airflow/operators/papermill_operator.py", line 57, in execute
    parameters=self.inlets[i].parameters,
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/airflow/lineage/datasets.py", line 69, in __getattr__
    ).render(**self.context)
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'seoul_date' is undefined

```

**What you expected to happen**:
PapermillOperator should find user defined macro.

**How to reproduce it**:

**Anything else we need to know**:
PapermillOperator uses `Notebook` class which derived from `DataSet`
https://github.com/apache/airflow/blob/65df1e802190d262b5e18fa9bc2e055768b96e28/airflow/operators/papermill_operator.py#L27
And `DataSet` seems not taking user defined macro from DAG.

**Comment by kaxil** [comment]
Would you like to take a look at this one @rootcss ?

**Comment by rootcss** [comment]
@kaxil Sure. please assign it to me.

**Comment by rootcss** [comment]
Hi @humbledude. This seems to be working fine for me. Could you please share a snippet of DAG object and your PapermillOperator.

**Comment by humbledude** [comment]
Hi, @rootcss.

I wrote DAG like this:
```
from airflow.utils import timezone
from airflow.operators.papermill_operator import PapermillOperator
from airflow import DAG

from common.macros import seoul_date

dag = DAG(
    dag_id='papermill-test2',
    start_date=timezone.datetime(2019, 9, 1),
    schedule_interval='0 15 * * *',
    catchup=False,
    user_defined_macros={
        'seoul_date': seoul_date
    }
)

with dag:
    t1 = PapermillOperator(
        task_id='papermill-task',
        input_nb='s3://test/papermill_test.ipynb',
        output_nb='s3://test/papermill_test_result.ipynb',
        parameters={
            'a': '{{ seoul_date(execution_date) }}',
            'b': 'test',
        }
    )
```

`seoul_date` is defined as:
```
KST = pendulum.timezone('Asia/Seoul')

def seoul_date(execution_date, years=0, months=0, days=0, hours=0, fmt="%Y%m%d"):
    return KST.convert(pendulum.instance(execution_date)).add(years=years, months=months, days=days, hours=hours).strftime(fmt)
```
This DAG does not work because of `seoul_date`.
Error log says, `'seoul_date' is undefined`

If I remove using `seoul_date` on parameters, then DAG works fine.

**Comment by rootcss** [comment]
Thanks @humbledude. Will check this and get back to you.

**Comment by eladkal** [comment]
hi @rootcss are you still working on it?
