### ISSUE TITLE
Default default_args

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#12086]
I use for every single dag the same s3_bucket, email and start_date. It would be nice that those default_args won't have to be written explicitly in each dag file, but taken from the airflow.cfg file or default_args.cfg file or something like that.

**Comment by msumit** [comment]
not tried, but I think you can create a default_args.py file along with your dags and write a DEFAULT_ARGS dict there and just import it in ur dags everytime?

**Comment by turbaszek** [comment]
Why not use cluster policy?

**Comment by JavierLopezT** [comment]
> Why not use cluster policy?

Ok, I didn't know that. Closing the issue then, thank you. Although I think having more documentation with examples of what can be achieved with cluster policy would be very nice

**Comment by turbaszek** [comment]
@JavierLopezT would you like to add them? It's best when the documentation comes from users who are using a feature 👍
