### ISSUE TITLE
dag_run is None when running TriggerDagRunOperator example

### ISSUE THREAD

**Issue by timovwb** [apache/airflow#1209]
I'm running Airflow airbnb_prod.1.6.2.9/1.7.0rc1 with the following examples for the TriggerDagRunOperator:
- Controller: https://github.com/airbnb/airflow/blob/master/airflow/example_dags/example_trigger_controller_dag.py
- Target: https://github.com/airbnb/airflow/blob/master/airflow/example_dags/example_trigger_target_dag.py

In the target example is shown how to get passed data from the controller by doing `kwargs['dag_run'].conf['message']` in Python or `dag_run.conf["message"]` in bash.

The problem is that `dag_run` is None instead of a `DagRun` object and the above code fails. Any help is appreciated.

**Comment by r39132** [comment]
Thanks for reporting. Can you quickly confirm for me that you are running in UTC everywhere?

-s

**Comment by r39132** [comment]
I reproduced what you are seeing when not running in UTC/GMT. Closing. Please refer to the common pitfalls wiki. Also, please use the ISSUE template.

**Comment by r39132** [comment]
Also, to understand how this example runs, refer to https://www.linkedin.com/pulse/airflow-lesson-1-triggerdagrunoperator-siddharth-anand 

The output of the target dag is written to the scheduler stdout. Once we set your DB and your servers to all run in UTC, this will work.
