### ISSUE TITLE
Liveness probe only observes one scheduler.

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#12098]
Hiello,

Recently, the Helm Chart has been updated to add the ability to run multiple schedulers.
https://github.com/apache/airflow/pull/11330

The liveness probe that does not support multiple schedulers has not been updated. I think we should also update the liveness probe to handle this case. Currently, it only watches the newest job, not the job assigned to the current scheduler.
https://github.com/apache/airflow/blob/91a64db505e50712cd53928b4f2b84aece3cc1c0/chart/templates/scheduler/scheduler-deployment.yaml#L115-L130

Best regards,
Kamil Breguła

**Comment by ryw** [comment]
Moved to Airflow 2.1 milestone since Helm chart is not part of 2.0 release.
