### ISSUE TITLE
Task with ALL_DONE trigger rule gets skipped

### ISSUE THREAD

**Issue by tanelk** [apache/airflow#12102]
**Apache Airflow version**:1.10.9

**Environment**:

- **OS** (e.g. from /etc/os-release):Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`):5.9.1-arch1-1
- **Install tools**:pip

**What happened**:

Task with `TriggerRule.ALL_DONE` will get skipped if any of its upstream tasks is skipped.

**What you expected to happen**:

The [docs](https://airflow.apache.org/docs/stable/concepts.html#trigger-rules) states that 

> Skipped tasks will cascade through trigger rules all_success and all_failed but not all_done, one_failed, one_success, none_failed, none_failed_or_skipped, none_skipped and dummy.

So I would assume that a task with `TriggerRule.ALL_DONE` will never get skipped.

**How to reproduce it**:

A minimal example:
```
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import ShortCircuitOperator
from airflow.utils.trigger_rule import TriggerRule
from datetime import datetime

dag_args = {
    'dag_id': 'test',
    'start_date': datetime(2020, 1, 1, 0, 0),
}

with DAG(**dag_args) as dag:
    task1 = ShortCircuitOperator(
        task_id='task1',
        python_callable=lambda: False
    )

    task2 = DummyOperator(task_id='task2')

    task3 = DummyOperator(
        task_id='task3',
        trigger_rule=TriggerRule.ALL_DONE
    )

    task1 >> task2 >> task3
```
And the resulting DAG:
![image](https://user-images.githubusercontent.com/3342974/98235306-4fc16180-1f6a-11eb-8863-42c62c093c01.png)

I would asume that task3 still gets executed or that the documentation gets updated and that there would be a trigger rule 'always', like it was asked in #10275.

Thank you.

**Comment by eladkal** [comment]
ShortCircuitOperator does not respect trigger rules.
Closing issue is better described in https://github.com/apache/airflow/issues/12102
