### ISSUE TITLE
On Windows, calling "airflow initdb" pops up "How do you want to open this file" dialog

### ISSUE THREAD

**Issue by TechArtistG** [apache/airflow#12146]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Windows 10

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

After following the install instruction, when calling "airflow initdb" from a powershell prompt the result is popping up the system "How do you want to open this file" dialog instead of executing the script.

**What you expected to happen**:
The airflow script would be executed

I'd say since the airflow python script doesn't have an extension and there's probably a call somewhere to execute that file using default application Windows can't resolve the correct app to use ie Python.

**How to reproduce it**:
Follow the install instructions on Windows 10

**Anything else we need to know**:
Reinstalled several times, same thing happens

**Comment by eladkal** [comment]
> How to reproduce it:
> Follow the install instructions on Windows 10

Can you please point to which instructions are you referring to?
See Jarek [answer](https://stackoverflow.com/questions/64931132/unable-to-start-airflow-locally-on-windows) for Windows support
