### ISSUE TITLE
Supporting JSON on Variables' editor UI

### ISSUE THREAD

**Issue by quandaica** [apache/airflow#12147]
**Description**

Variables on Airflow are required to be defined in JSON format but it's very hard to edit JSON on the current UI. Then it's much better if the editor variables UI on Airflow are updated to support JSON format instead of plain text.

**Use case / motivation**

The editor for variables is much better if it can highlight keywords and validate the content.

**Related Issues**

There are no related issues

**Comment by mik-laj** [comment]
A similar editor would be helpful on the DAG trigger screen.
![image](https://user-images.githubusercontent.com/12058428/98449344-14be5a00-2133-11eb-8465-445cc732191f.png)

**Comment by mik-laj** [comment]
We can use [CodeMirror](https://codemirror.net/). It supports JSON with linting.

**Comment by RosterIn** [comment]
How is that different than https://github.com/apache/airflow/pull/5573 ?

**Comment by mik-laj** [comment]
@RosterIn That change only formatted the code, that is, it added an indent and new lines. We want to have syntax highlight and lint in the browser.
See demo: 
https://codemirror.net/demo/lint.html

**Comment by pateash** [comment]
@quan-nguyen-sy, @mik-laj @kaxil 
this has been resolved in above PR, can we mark this issue close.

**Comment by mik-laj** [comment]
@pateash thanks. Done
