### ISSUE TITLE
Allow for setting dependencies in nested lists of tasks

### ISSUE THREAD

**Issue by darwinyip** [apache/airflow#12145]
**Description**

Allow for setting upstreams/downstreams of tasks contained in nested lists

**Use case / motivation**

Be able to do this:
```
t1 >> [[t2 >> t3 >> t4], [t5 >> t6 >> t7]] >> t8
```

Instead, currently it would be set up as:
```
t1 >> t2 >> t3 >> t4 >> t8
t1 >> t5 >> t6 >> t7 >> t8
```

**Comment by eladkal** [comment]
We already have [`chain`](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#task-dependencies):

```
from airflow.models.baseoperator import chain
# Replaces
# op1 >> op2 >> op4 >> op6
# op1 >> op3 >> op5 >> op6
chain(op1, [op2, op3], [op4, op5], op6)
```
