### ISSUE TITLE
Production image has only amazon and google providers installed

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12150]
When "production" image is prepared for, only amazon and google providers are installed from sources.

**Apache Airflow version**:

master

**What you expected to happen**:

All providers should be installed

**How to reproduce it**:

```
./breeze --production-image --python 3.6
```

Then:

```
./breeze --production-image --python 3.6 shell bash
```

then

```
ls -la ~/.local/lib/python3.6/site-packages/airflow/providers/

amazon
google

```

UPDATE:

They are not even installed: 

```
.
./amazon
./amazon/aws
./amazon/aws/hooks
./amazon/aws/hooks/batch_waiters.json
./google
./google/cloud
./google/cloud/example_dags
./google/cloud/example_dags/example_bigquery_query.sql
./google/cloud/example_dags/example_cloud_build.yaml
./google/cloud/example_dags/example_spanner.sql
```

**Comment by potiuk** [comment]
Confirmed that was an aftermath of #10806. adding a fix shortly and protection against missing installation.

**Comment by potiuk** [comment]
We need to merge it for Beta1 - otherwise the production images will not be usable.

**Comment by ashb** [comment]
The "production" image should be installing the providers packages anyway.

**Comment by potiuk** [comment]
Yep. It was until the implicit packages change

**Comment by ashb** [comment]
Sorry, I wasn't clear. Should be installing the providers packages _from split out providers_, not by having them be part of the apache-airflow dist.

Else it's not "production".

**Comment by ashb** [comment]
If we do #11464 do we even need to do anything?

**Comment by potiuk** [comment]
> Sorry, I wasn't clear. Should be installing the providers packages _from split out providers_, not by having them be part of the apache-airflow dist.
> 
> Else it's not "production".

If you install it from released PIP packages it will work. but if you want to build master version of the production image which uses the latest sources (and which many developers use to try out the latest and greatest), and which WE use for kubernetes and helm chart testing then yes. We definitely need to do it regardless of #11464. 

And we have to do it all the time if we do not want to be surprised at the release time that the image does not work. This is something we do for about 6 months already.

**Comment by ashb** [comment]
Then lets not call it production -- if it's not installing modules as close as possible to the same way we will for a release (i.e. with pip from wheels) then it's not production, it's a light(er)-weight CI image.

**Comment by potiuk** [comment]
As discussed - once we release providers via PYPI, I will change the build to use .whl backport packages to make the image from master even closer to the real  "production" one we are going to have. Let's do it incrementally :)
