### ISSUE TITLE
Not shown partial of text on Side-bar on Docs - REST API Reference 

### ISSUE THREAD

**Issue by roharon** [apache/airflow#12189]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: MS Edge
- **Others**:

**What happened**:

[REST API Reference](https://airflow.apache.org/docs/stable/rest-api-ref.html)
Not shown partial of text(Endpoint path)  located in the right side-bar 
```html
<a class="reference internal" href="#post--api-experimental-dags--DAG_ID--dag_runs">POST /api/experimental/dags/&lt;DAG_ID&gt;/dag_runs</a>
```

<img src="https://user-images.githubusercontent.com/4939738/98500046-b1493f00-228e-11eb-9628-fc3f5ad91b09.png" alt="image" style="zoom:20%;" />

**What you expected to happen**:
<img src="https://user-images.githubusercontent.com/4939738/98500530-0c2f6600-2290-11eb-91cb-c0069946dd4d.png" alt="image" style="zoom:25%;" />

Dose not changed to the next line 

**How to reproduce it**:
split text about endpoint or increase size of right-side-bar

**Anything else we need to know**:

**Comment by mik-laj** [comment]
This is documentation for an API that is no longer supported.  The documentation for the stable API looks better.
https://airflow.readthedocs.io/en/latest/stable-rest-api-ref.html

Can you create an issue also on [airflow-site ](https://github.com/apache/airflow-site/issues) repo?

**Comment by roharon** [comment]
Sure, I'll create it

**Comment by eladkal** [comment]
We have https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html for API documntation.
I'm closing as the issue doesn't seem relevant any more (we can reopen if needed)
