### ISSUE TITLE
SimpleHttpOperator tests are reaching out to google.com

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#1218]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet) : master
- Example code to reproduce the bug (as a code snippet in markdown) 
  https://travis-ci.org/airbnb/airflow/jobs/118566538
- Screen shots of your DAG's graph and tree views:
- Stack trace if applicable:
  root: INFO: Sending 'GET' to url: https://www.google.com//search
  root: ERROR: HTTP error: Service Unavailable
  root: ERROR: 503:Service Unavailable
  Traceback (most recent call last):
  File "/home/travis/build/airbnb/airflow/airflow/models.py", line 1077, in run
    result = task_copy.execute(context=context)
  File "/home/travis/build/airbnb/airflow/airflow/operators/http_operator.py", line 61, in execute
    self.extra_options)
  File "/home/travis/build/airbnb/airflow/airflow/hooks/http_hook.py", line 64, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/travis/build/airbnb/airflow/airflow/hooks/http_hook.py", line 95, in run_and_check
    raise AirflowException(str(response.status_code)+":"+response.reason)
  AirflowException: 503:Service Unavailable
- Operating System: (Windows Version or `$ uname -a`)
  Travis
- Python Version: `$ python --version`
  All
- (Optional) Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am having:
# Description of Issue
- What did you expect to happen?
  I expect tests not to reach out to Google.com
- What happened instead?
  Tests are reaching out to Google.com. This causes occasional failures (timeout, 500 error, etc). This is non-deterministic, and causes unit tests to fail sporadically.
- Here is how you can reproduce this issue on your machine:
## Reproduction Steps

1.
2.
3.

**Comment by bolkedebruin** [comment]
This was fixed.
