### ISSUE TITLE
Cant trigger task on demand under KubernetesExecutor

### ISSUE THREAD

**Issue by KulykDmytro** [apache/airflow#12185]
**Apache Airflow version**: 1.10.12
**Kubernetes version**: 1.18.6

**What happened**:
Airflow is running within a k8s with **KubernetesExecutor**
When trying to run task on demand within a DAG (f.e. "Ignore all deps") receiving following banner
> Only works with the Celery or Kubernetes executors, sorry

**What you expected to happen**:
Task should be executed

**How to reproduce it**:
see above

**Comment by bbovenzi** [comment]
Seems to be a duplicate of #12341 @kaxil do you agree?

**Comment by KulykDmytro** [comment]
Yes it is a duplicate, sorry folks
