### ISSUE TITLE
Final UI Style Refinement for "Blocked" Feature in Main Page

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#12186]
### Description

The home page (`DAGs`) actually provides the feature the mark/highlight the DAGs whose number of active DAG Runs >= max allowed number of DAG Runs. This feature was broken earlier, and I fixed it in PR https://github.com/apache/airflow/pull/12183. To align with the new UI design in 2.0.0, I made minor change in terms of the style. 

But it would be great if our UX/UI experts can take another look, and ensure the style matches well with the overall style. @ryanahamilton may you please take a look?

For more details and history, please refer to Issue https://github.com/apache/airflow/issues/12182 and https://github.com/apache/airflow/pull/12183

### Requirements / Use case / motivation

(1/2) Such DAGs' `schedule` is marked with special colour

![98482265-831d1e00-2200-11eb-87a5-5bf45bcbc615](https://user-images.githubusercontent.com/11539188/98482920-d1ccb700-2204-11eb-848c-b85fd357df79.png)

(2/2) Show Text when hover over

![98482288-b3fd5300-2200-11eb-9228-ad024b1e7a02](https://user-images.githubusercontent.com/11539188/98482925-d85b2e80-2204-11eb-9b06-9b54625e2c8e.png)

**Related Issues**

**Comment by XD-DENG** [comment]
CC @kaxil @potiuk @mik-laj

**Comment by kaxil** [comment]
aah nice, thanks for creating this.

**Comment by ryanahamilton** [comment]
This solution LGTM, closing the issue!

**Comment by potiuk** [comment]
> This solution LGTM, closing the issue!

WHOA! @XD-DENG -> maybe you have a new career as a frontend/UX ;)

**Comment by XD-DENG** [comment]
> > This solution LGTM, closing the issue!
> 
> WHOA! @XD-DENG -> maybe you have a new career as a frontend/UX ;)

Absolutely don't mind to pick up more ;-)
