### ISSUE TITLE
Add detailed documentation for scheduler "tuning" parameters

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12193]
https://github.com/apache/airflow/pull/12139 added some new params to the scheduler -- we have "cursory" docs for them in the comments in the config file, but we should have a more details docs in the scheduler.rst page.

**Comment by mik-laj** [comment]
If possible, I would change the option name from `clean_tis_without_dagrun ` to `clean_tis_without_dagrun_interval ` The other configuration options have this suffix.

**Comment by potiuk** [comment]
Hey @ashb @mik-laj - something for 2.0.0rc1? or will you change the milestone?
