### ISSUE TITLE
Inconsistent styles of different validation errors in Airflow UI

### ISSUE THREAD

**Issue by swalkowski** [apache/airflow#12202]
**Apache Airflow version**: 1.10.12

**Environment**:

- **Cloud provider or hardware configuration**: Google Cloud Composer (one tweaked environment running RBAC UI, one regular environment running non-RBAC UI)

**What happened**:

Inconsistent styles of different validation errors in Airflow UI. In particular, a validation error for missing field value is a white box with exclamation mark in a yellow square and text in black, while a validation error for incorrect value is in red text (and red box in RBAC UI), styled differently. Examples from the Add Connection form:

- Inconsistency in RBAC UI: 
![RBAC-UI-validations](https://user-images.githubusercontent.com/12511618/98559654-2aed2700-22a7-11eb-8dbd-184267a06bc0.png)

- Inconsistency in non-RBAC UI: 
![non-RBAC-UI-validations](https://user-images.githubusercontent.com/12511618/98559870-70115900-22a7-11eb-9754-5a96264c429b.png)

It's just a minor UX problem.

Looking at the page behavior, I guess the difference comes from client-side vs. server-side validation.

**What you expected to happen**:

Consistent style for all validation errors, in a single form but also across pages.

**How to reproduce it**:

For example: in Airflow UI go to Connections, click Add a new record, select Redis as connection type, write some characters in Conn Id field, put `{{{` in the Port field, click Save, clear the Conn Id field, click Save - you will now see both error styles in a single form.

+cc @ryanahamilton

**Comment by potiuk** [comment]
I guess @ryanahamilton that this is similar for 2.0? Or have we already unified it? I am happy to cherry-pick some changes to 1.10.13 if they might be simple and you can guide me - to make life of the 1.10.* folks a bit better on that :)

**Comment by ryanahamilton** [comment]
For some additional context, the "please fill out this field" messages are native browser rendered input validation based on the input having a `required` attribute, and the others are custom validation within the application. This is unchanged in 2.0. This form is rendered by FAB, so if we wanted to change it, it would have to be PR'ed to FAB.

**Comment by potiuk** [comment]
So i'd say it's something we might not even want to deal with, I am afraid. Looks like the effort is not worth it.

**Comment by ryanahamilton** [comment]
@potiuk yeah, I think I'd agree with that.

**Comment by potiuk** [comment]
@swalkowski  - I think we should close it then.
