### ISSUE TITLE
SlackWebhookHook should use password instead of extra to store the token

### ISSUE THREAD

**Issue by darwinyip** [apache/airflow#12214]
Currently `SlackWebhookHook` gets the token from `extra` but it would be more secure and intuitive to have it in password.

https://github.com/apache/airflow/blob/4fb5c017fe5ca41ed95547a857c9c39efc4f1476/airflow/providers/slack/hooks/slack_webhook.py

**Comment by mik-laj** [comment]
Sound good to me. Can I assign you to this ticket?

**Comment by darwinyip** [comment]
@mik-laj Sure! Do I need to make it backwards compatible and support extra along with password?

**Comment by mik-laj** [comment]
Yes. You should also add [DeprecationWarning](https://github.com/apache/airflow/search?q=DeprecationWarning). I assigned you to this ticket.
