### ISSUE TITLE
DingdingOperator return NoneType

### ISSUE THREAD

**Issue by betaincao** [apache/airflow#12223]
https://github.com/apache/airflow/blob/7463b6bcc7a823a9d02c7026d9b03b81c6421654/airflow/providers/dingding/hooks/dingding.py#L124

int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by caoyouming** [comment]
I Think errcode equal to 0 is OK, But the product returns this error.

**Comment by mik-laj** [comment]
@zhongjiajie Can you look at it?

**Comment by zhongjiajie** [comment]
> @zhongjiajie Can you look at it?

Will take a look

**Comment by zhongjiajie** [comment]
Hi @caoyouming did you miss some error here? I think it work fine here.

**Comment by caoyouming** [comment]
yes，I had miss some errors，it may be an occasional error, or a dingding error. please ignore.
