### ISSUE TITLE
Extras installation was lost in the last rebase

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12231]
The #11526 was badly rebased just before beta1 relase and few
lines installing the providers were lost.

**Comment by potiuk** [comment]
cc: @kaxil @ashb -  I think that ones calls for b2 release ASAP only containing this fix and #12217 restoring sendgrid provider. 

We can defer it to next week as the only difference is that you have to install providers manually, but from "user experience" point of view I think it would be great to have it from Day 1

**Comment by potiuk** [comment]
Happy to announce it and apologise if we agree to :).

**Comment by kaxil** [comment]
no, no -- definitely don't need to apologize. They are betas ;)
