### ISSUE TITLE
GCS to Presto transfer operator

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#12246]
**Description**
Transfer operator to allow loading data from GCS to Presto database

**Related Issues**

different direction the transfer operator added a while ago https://github.com/apache/airflow/pull/7718

**Comment by manesioz** [comment]
This looks fun, is anyone picking it up? I would like to take a stab at it if not. 

As a new(ish) contributor, should I be looking at https://github.com/apache/airflow/pull/7718 as an example to follow loosely?

**Comment by mik-laj** [comment]
@manesioz `*ToGCS` operators have a complex abstraction that you don't need, but you will surely find a similar operator in our repository.

I assigned you to this ticket.

**Comment by rsg17** [comment]
I would like to take a pass at this if no one else is working on it. Can you assign it to me?

**Comment by rsg17** [comment]
I have linked a v0/draft PR for this.

@eladkal Would you be able to help check if this is on the right track? 
Or do you know who I should check with? All other comments on this issue are from 2020.

**Comment by eladkal** [comment]
@rsg17 seems OK. you should add tests and docs then we can fully review.
