### ISSUE TITLE
'TaskInstance' object has no attribute 'get_previous_execution_date'

### ISSUE THREAD

**Issue by nadeesh-garg** [apache/airflow#12251]
I'm trying to use the following: `context['task_instance'].get_previous_execution_date()`
I get a response:
`
'TaskInstance' object has no attribute 'get_previous_execution_date'`

I'm using the docker Image: apache/airflow:1.10.11-python3.6

If I use the older `previous_execution_date_success`, I get None everytime!

**Comment by turbaszek** [comment]
@nadeesh-garg please provide required information like airflow version and environment. Without that we are unable to help you fully.

**Comment by nadeesh-garg** [comment]
Hi, edited original answer

**Comment by eladkal** [comment]
@nadeesh-garg can you please add a reproduce example?
