### ISSUE TITLE
"Log" button on graph view popup doesn't open the logs view

### ISSUE THREAD

**Issue by anirudhbagri** [apache/airflow#12254]
**Apache Airflow version**:2.0.0b2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): macOS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Clicking on the "Log" button in the popup for task instance in graph view doesn't link to the logs view.

**What you expected to happen**:
The log view should show up.

**How to reproduce it**:
1. Run any dag.
2. Open Graph VIew.
3. Click on any task.
4. Click on the "Log" button.

**Anything else we need to know**:
Check this in action [here](https://youtu.be/fXEQ-yOwMrM).

**Comment by ryanahamilton** [comment]
Planning on investigating this later today.
