### ISSUE TITLE
Main DAG list view is not pretty 

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12258]
**Apache Airflow version**:
master branch

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:

- **OS** (e.g. from /etc/os-release): MacOS
- **Browser**: Safari

**What happened**:

<img width="1680" alt="Screenshot 2020-11-10 at 17 38 01" src="https://user-images.githubusercontent.com/9528307/98703308-a6200d00-237b-11eb-9f98-ef1d7cb8de20.png">

**What you expected to happen**:

I expect that the UI is nice and clean ❤️ 

**How to reproduce it**:
I'm using breeze, so starting a webserver and heading to `http://0.0.0.0:28080/` should replicate the problem

**Anything else we need to know**:

**Comment by turbaszek** [comment]
CC @ryanahamilton

**Comment by ryanahamilton** [comment]
@turbaszek Might need to recompile your assets and restart webserver?
```bash
$ airflow/www/compile_assets.sh
```

**Comment by turbaszek** [comment]
> ```shell
> airflow/www/compile_assets.sh
> ```

Yes, that helped. I forgot about it 😞

**Comment by potiuk** [comment]
@ryanahamilton @turbaszek  : I already know how to automate it while entering breeze. Will add it shortly so that there are no such problems in the future.

**Comment by potiuk** [comment]
Issue #12262 created. Will add it shortly.
