### ISSUE TITLE
Log and all instances buttons not working

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12259]
**Apache Airflow version**:
Master branch

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:

- **OS** (e.g. from /etc/os-release): MacOS
- **Browser**: Safari
- **Others**: breeze environment

**What happened**:

Nothing happens when clicking "Log" or "All instances" in this view
<img width="1020" alt="Screenshot 2020-11-10 at 17 43 37" src="https://user-images.githubusercontent.com/9528307/98704517-0a8f9c00-237d-11eb-87d1-e0571c8b0914.png">

If I got to instance detail > log then I can see logs.

**What you expected to happen**:

I expect that I can access logs and task instances via mentioned buttons.

**How to reproduce it**:

Start webserver and scheduler, go to airflow webui, trigger `example_dag_decorator`, click on any task from DAG in graph view, click log.

**Anything else we need to know**:

🐈

**Comment by turbaszek** [comment]
CC @ryanahamilton  - I compiled the assets as mentioned in #12258

**Comment by kaxil** [comment]
Related: https://github.com/apache/airflow/issues/12254

**Comment by turbaszek** [comment]
Duplicate of #12254
