### ISSUE TITLE
Update TaskFlow API example to use `@dag` decorator

### ISSUE THREAD

**Issue by casassg** [apache/airflow#12269]
**Description**

Update https://github.com/apache/airflow/blob/master/airflow/example_dags/tutorial_taskflow_api_etl.py tp use `@dag` decorator instead of leveraging context manager to make it more TaskFlow-y.

**Comment by turbaszek** [comment]
Do we need other example than this one?
https://github.com/apache/airflow/blob/0cd1c846b2fb4d830b87e11b884094ee4765ab22/airflow/example_dags/example_dag_decorator.py#L43-L67

**Comment by casassg** [comment]
I was thinking more on having a more end to end example for the tutorial?

**Comment by kaxil** [comment]
We could update an example in https://github.com/apache/airflow/pull/12170 to use the `dag` decorator

**Comment by eflann** [comment]
Is this what you had in mind?

**Comment by casassg** [comment]
@eflann yes. Commenting in the PR

**Comment by casassg** [comment]
@kaxil I would encourage all TaskFlow tutorials to be using `@dag` better? We can leave some w context manager so people undertstand it's usable in both ways. But I was indeed refering to `tutorial_taskflow_api_etl` as @eflann mentions

**Comment by kaxil** [comment]
+1 to that change

**Comment by potiuk** [comment]
Hey @casassg  @turbaszek -> is it something we want for 2.0.0rc1 ? Or if not - can yo please move the milestone to 2.1.

**Comment by casassg** [comment]
This is documentation update. I would think it can be even done after release of 2.0 (aka 2.0.1?)
