### ISSUE TITLE
Astronomer's Helm Chart for Apache Airflow 

### ISSUE THREAD

**Issue by himabindu07** [apache/airflow#12275]
Step1--> https://github.com/astronomer/airflow-chart
Clone the repository
Step 2 --> kind create cluster --name airflow20 --config kind-cluster_bk.yaml
Creating cluster "airflow20" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✓ Preparing nodes 📦 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-airflow20"
You can now use your cluster with:

kubectl cluster-info --context kind-airflow20

Have a nice day! 👋

Step3--> kubectl create namespace air2k8s 
namespace/air2k8s created

Step4-->ktx
Switched to context "kind-airflow20".
kns
Set context namespace to "air2k8s"

Step5--> helm repo add astronomer https://helm.astronomer.io
"astronomer" has been added to your repositories

Step6-->helm install airflow --namespace air2k8s astronomer/airflow
NAME: airflow
LAST DEPLOYED: Mon Nov  9 16:51:01 2020
NAMESPACE: air2k8s
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Airflow!

Your release is named airflow.

You can now access your dashboard(s) by executing the following command(s) and visiting the corresponding port at localhost in your browser:

Airflow dashboard:        kubectl port-forward svc/airflow-webserver 8080:8080

Step7-->helm install  my-release .     
Error: found in Chart.yaml, but missing in charts/ directory: postgresql

Testing airflow-chart locally on kind with these as my custom values:
airflowVersion: 2.0.2
defaultAirflowTag: 2.0.2
defaultAirflowRepository: rohitke34/airflow20
images:
  airflow:
    # repository: quay.io/astronomer/ap-airflow-dev
    repository: rohitke34/airflow20
    tag: 2.0.2
Image that I built and loaded into kind locally starting, Default config of KubernetesExecutor not working out of the box for me. 
I tried with minikube, able to run the dags, when I ran the dags getting 403 error, So for some reason the executor pod is running under the webserver service account. Which is weird, because it should be running under the worker service account 
here is the values.txt file(Cannot upload .yaml file converting the file to .txt)
[values.txt](https://github.com/apache/airflow/files/5521546/values.txt)

**Comment by mik-laj** [comment]
This is the apache / airflow repository. We also have a Helm Chart that is based on an astronomer chart, but it has already changed a lot. 
Can you create a ticket in the correct repository? I don't think your problem is with Apache Airflow or our Helm Chart.
https://github.com/astronomer/airflow-chart/issues
