### ISSUE TITLE
Add DAG version info

### ISSUE THREAD

**Issue by tigicion** [apache/airflow#12278]
**Description**

Currently we can't tell which version the dag is as there is no corresponding param for it. I was wondering if it is possible to add version info for each dag, and show it on the UI

**Use case / motivation**

I can't tell if the dag is successfully updated after some modification has been done. It would be really convenient if I can view the version info for each dag on the UI.

**Related Issues**

There are no related issues

**Comment by eladkal** [comment]
[AIP-36 DAG Versioning](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning) 
As you can see in the [status page](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals) the AIP is currently under discussions. You are more than welcome to share your thoughts on the AIP page.
