### ISSUE TITLE
Add list of providers available in the docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12281]

**Comment by mik-laj** [comment]
I think it shouldn't be in the documentation, but on our website.  This way we will be able to update it independently of the rest of the documentation. For example: we will be able to issue providers every month, and Airflow with documentation every 3 months. This means that we will not have any documentation for 2 months for a new provider.

Similar issue: 
https://github.com/apache/airflow/issues/11423 (automatic generation of provider list)
https://github.com/apache/airflow/issues/11152 (publication of a list of packages on the site)

**Comment by potiuk** [comment]
> I think it shouldn't be in the documentation, but on our website. This way we will be able to update it independently of the rest of the documentation. For example: we will be able to issue providers every month, and Airflow with documentation every 3 months. This means that we will not have any documentation for 2 months for a new provider.

Absolutely - this is our strategic direction. But I belive we also need a "tactical" solution for now -  while people will be trying out Betas, I think it would be great to have a single page where they can simply see which providers are.

**Comment by mik-laj** [comment]
SGTM

**Comment by mik-laj** [comment]
Are you working on it? I will be happy to do it, because I will also need it to build the final documentation.

**Comment by potiuk** [comment]
Feel free!
