### ISSUE TITLE
Add docs around when to use TaskGroup vs SubDag and potentially listing PROs and CONS.

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#12298]
It would be great for users to know when they should use TaskGroup vs SubDag. A section somewhere in docs would be great or even better a Matrix / table to explain difference would be aweomse.

What are the PROs and CONs of each

**TaskGroup**: https://airflow.readthedocs.io/en/latest/concepts.html#taskgroup
**SubDags**: https://airflow.readthedocs.io/en/latest/concepts.html#subdags

**Comment by VeenaArv** [comment]
Hi, can I work on this as my first issue? Should this go under [concepts](https://github.com/apache/airflow/blob/master/docs/concepts.rst) or somewhere else?

**Comment by kaxil** [comment]
@VeenaArv Yes somewhere in Concepts, in or after https://github.com/apache/airflow/blob/master/docs/concepts.rst#taskgroup section

**Comment by turbaszek** [comment]
@kaxil @VeenaArv should we also add information about `TriggerDagRunOperator` as this is also a possibility to manage large DAGs?
