### ISSUE TITLE
Option to auto-replace deprecated configs with new options for 2.0

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#12294]
This issue is part of #8765

It would be good to have a rule or command in upgrade-check utility tool to replace the deprecated configs with new options.

Following are the deprecated options:
https://github.com/apache/airflow/blob/289c9b5a994a3e26951ca23b6edd30b2329b3089/airflow/configuration.py#L136-L174

**Comment by eladkal** [comment]
Closing as there will be no more releases of upgrade check
