### ISSUE TITLE
Permissions appear to reload repeatedly

### ISSUE THREAD

**Issue by jhtimmins** [apache/airflow#12300]
This results in slow UI load time and too many permissions records

Please assign to @jhtimmins

**Comment by paolaperaza** [comment]
(Copying a comment from @jhtimmins in a duplicate GH issue)

> From @ashb, this can be replicated by running the following:
> 
> GUNICORN_CMD_ARGS='--preload' AIRFLOW_WEBSERVER_UPDATE_FAB_PERMS=False AIRFLOW_WEBSERVER_WORKER_REFRESH_INTERVAL=0 airflow webserver -w 1

**Comment by kaxil** [comment]
Is this still an open issue @jhtimmins ?

**Comment by jhtimmins** [comment]
@kaxil Not sure. Need to validate.

**Comment by kaxil** [comment]
I am going to close this one, we can create a new one / open it if needed
