### ISSUE TITLE
The "Filter tags" multi-select container can't hold the selected tags while switching between views

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#12313]
**Apache Airflow version**: 1.10.12 & 2.0.0b2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): Linux mint 20
- **Kernel** (e.g. `uname -a`): 5.4.0-52-generic
- **Install tools**: 
- **Others**:

**What happened**: 
![ezgif-3-48bd0761e53d](https://user-images.githubusercontent.com/14293802/98970095-8e609a00-24dd-11eb-85bf-001504360480.gif)

**What you expected to happen**: The selected tags should stay the same while switching between `All`, `Active`, and `Paused`

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
cc @ryanahamilton
