### ISSUE TITLE
SSHOperator does support only RSA keys and should support other keys compatible with Paramiko

### ISSUE THREAD

**Issue by NBardelot** [apache/airflow#12318]
See the hook: `airflow/providers/ssh/hooks/ssh.py`

The Paramiko lib supports ECDSA keys. But the hook forces the use of RSA keys. 

This should be viewed as an issue as the release note of OpenSSH 8.4 states that `ssh-rsa` public key signatures are soon becoming obsolete. 

https://www.openssh.com/txt/release-8.4

```
Future deprecation notice
=========================

It is now possible[1] to perform chosen-prefix attacks against the
SHA-1 algorithm for less than USD$50K. For this reason, we will be
disabling the "ssh-rsa" public key signature algorithm by default in a
near-future release.

This algorithm is unfortunately still used widely despite the
existence of better alternatives, being the only remaining public key
signature algorithm specified by the original SSH RFCs.

The better alternatives include:

 * The RFC8332 RSA SHA-2 signature algorithms rsa-sha2-256/512. These
   algorithms have the advantage of using the same key type as
   "ssh-rsa" but use the safe SHA-2 hash algorithms. These have been
   supported since OpenSSH 7.2 and are already used by default if the
   client and server support them.

 * The ssh-ed25519 signature algorithm. It has been supported in
   OpenSSH since release 6.5.

 * The RFC5656 ECDSA algorithms: ecdsa-sha2-nistp256/384/521. These
   have been supported by OpenSSH since release 5.7.

To check whether a server is using the weak ssh-rsa public key
algorithm, for host authentication, try to connect to it after
removing the ssh-rsa algorithm from ssh(1)'s allowed list:

    ssh -oHostKeyAlgorithms=-ssh-rsa user@host

If the host key verification fails and no other supported host key
types are available, the server software on that host should be
upgraded.

We intend to enable UpdateHostKeys by default in the next OpenSSH
release. This will assist the client by automatically migrating to
better algorithms. Users may consider enabling this option manually.

[1] "SHA-1 is a Shambles: First Chosen-Prefix Collision on SHA-1 and
    Application to the PGP Web of Trust" Leurent, G and Peyrin, T
    (2020) https://eprint.iacr.org/2020/014.pdf
```

Thus, support of other public keys like EC keys should be added in order to improve the security and interoperability of Airflow, and so that users can start using more trustworthy algorithms. Especially since Paramiko already supports them.

**Comment by potiuk** [comment]
Would you maybe like to provide a PR/fix for that @NBardelot ? That sounds like rather easy and localized fix?

**Comment by potiuk** [comment]
Happy to help with reviewing it :)

**Comment by NBardelot** [comment]
@potiuk I currently have no available time to work on PRs (not even old PRs that I'd like to rework on the master branch…). I'm proposing the company I work for to let me spend some time in the future working on PRs when we'll prepare upgrading to Airflow 2.0.

**Comment by potiuk** [comment]
Oh That'd be cool if your company agrees to it :). This is super cool to be able to get paid for contributing to Open Source, I can tell you!

**Comment by brighton1101** [comment]
@potiuk I can work on this, very easy change. How do you want to differentiate between RSA and ECDSA keys... optional boolean flag as param in the constructor for `SSHHook`?

**Comment by ashb** [comment]
Why do we need to differentiate at all? We can't just pass any key type down, we have to know what type it is to tell Paramiko?

**Comment by ashb** [comment]
This is what Paramiko does when passed a `key_filename`
https://github.com/paramiko/paramiko/blob/dccc563c3a581a14ceaa261b5fe0d08539f84b87/paramiko/client.py#L673-L687

```python
            for key_filename in key_filenames:
                for pkey_class in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
                    try:
                        key = self._key_from_filepath(
                            key_filename, pkey_class, passphrase
                        )
                        allowed_types = set(
                            self._transport.auth_publickey(username, key)
                        )
                        two_factor = allowed_types & two_factor_types
                        if not two_factor:
                            return
                        break
                    except SSHException as e:
                        saved_exception = e
```

Perhaps we could do something similar.

**Comment by brighton1101** [comment]
@ashb i can look into doing something similar later. i wonder if they expose similar logic in their api for differentiating between key types when constructing different types of `PKey` instances such as what is baked into the code for rsa keys now. if not, i'd be happy to throw together a solution similar to the above with some tests

**Comment by brighton1101** [comment]
@ashb just threw a PR together :) let me know if you pictured it another way or have any other ideas
