### ISSUE TITLE
Response status 405 not handled in the stable REST API

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#12325]
Calling any endpoint in REST API with a method that's not allowed returns an HTML page instead of JSON

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```
**What you expected to happen**:
I expected a JSON response indicating that the method is not allowed

**How to reproduce it**:
1. Start airflow webserver in breeze
2. make a put request to  `http://localhost:28080/api/v1/variables` 
3. Notice that this is returned :

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by Zedmor** [comment]
Addressed in https://github.com/apache/airflow/pull/12305
