### ISSUE TITLE
The signature for the gcs hooks is different in apache 1.12 compare with the beta version 2.0

### ISSUE THREAD

**Issue by owlphi** [apache/airflow#12335]
### Google cloud storage hook is not backward compatible with the version 1.12.

In the version 1.12 the method download has the following parameters: (bucket, object, filename) in this order. See [here](
https://airflow.apache.org/docs/stable/_api/airflow/contrib/hooks/gcs_hook/index.html#airflow.contrib.hooks.gcs_hook.GoogleCloudStorageHook.download)
In the version 2.0.0b1 the method download has the following parameters (object_name, bucket_name, filename) in this order. See [here](https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/hooks/gcs.py#L259-L260)

You can see that the order of the parameters have changed from version 1.12 to 2.0.0b1. 

### The problem
If we use the method download with positional parameters like in this operator: https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py#L267. It will fail

**Comment by turbaszek** [comment]
Yes, it's a breaking change as described here:
https://github.com/apache/airflow/blob/master/UPDATING.md#airflowprovidersgooglecloudhooksgcsgcshook

**Comment by owlphi** [comment]
@turbaszek . Thank you for the quick reply. In that case this line of the code 
https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py#L267
is not working because the order of parameters is wrong. This is what I have tried to point it out.

Should I create a new issue? or could we have this open?

**Comment by Zedmor** [comment]
Addresses in https://github.com/apache/airflow/pull/12305
