### ISSUE TITLE
Add docs on Release process w.r.t test and stable branches

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#12338]
Add docs describing the process for Release Managers with respect to using and sync'ing v1-10-test and v1-10-stable (or any test and stable release branches) and the cherry-picking process.

**Comment by potiuk** [comment]
I tink we can close that one. We are really not in 1.10 any more and I think the cherry-picking process for v2* branches is much more strightforward now WDYT @kaxil .

**Comment by kaxil** [comment]
> I tink we can close that one. We are really not in 1.10 any more and I think the cherry-picking process for v2* branches is much more strightforward now WDYT @kaxil .

Agree
