### ISSUE TITLE
JSON schema validation for airflow/config_templates/config.yml

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#12357]
Hello my friends,

I hope you are all right and you are all healthy. Today I come with another small improvement proposal for our project. 

I think it is worth adding JSON schema validations for `[airflow/config_templates/config.yml`](https://github.com/apache/airflow/blob/master/airflow/config_templates/config.yml) file. This will allow us to detect the wrong structure of this file very quickly and also provide simple documentation for this file. This schema should be verified every time a file is loaded.

In order to generate a schema, you can use generators:
https://onlineyamltools.com/convert-yaml-to-json
https://www.liquid-technologies.com/online-json-to-schema-converter (Please note that you should set array rules to "List validation". In the result, it is also worth updating the JSON Schema specification versions to latest current spec)

In the generated specification, it is worth adding descriptions for each field: 
https://json-schema.org/understanding-json-schema/reference/generic.html#annotations

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
@SamWheating  Is it something interesting for you?

**Comment by SamWheating** [comment]
I can take this, but it may take me a week or two to get around to it. If that timeline is acceptable, then feel free to assign to me.

**Comment by mik-laj** [comment]
@SamWheating  This is not an urgent task, but I don't want to see bugs in this file, and we've been making some more changes lately. I assigned you to this ticket. 🐈‍⬛🐈

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/13025
