### ISSUE TITLE
CLI - "clear" command does not work

### ISSUE THREAD

**Issue by cognalog** [apache/airflow#1235]
# Environment
- **Version of Airflow:** 1.6.2, or master - 1db892b
- **Example code to reproduce the bug:** Using airflow cli: `airflow clear example_xcom`
- **Stack trace:**

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 4, in <module>
    __import__('pkg_resources').run_script('airflow==1.6.2', 'airflow')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1670, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.6.2-py2.7.egg/EGG-INFO/scripts/airflow", line 15, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.6.2-py2.7.egg/airflow/bin/cli.py", line 324, in clear
    only_failed=args.only_failed,
AttributeError: 'Namespace' object has no attribute 'only_failed'
```
- **Operating System:** Ubuntu 14.04
- **Python Version:** 2.7.6
# Description of Issue
- **What did you expect to happen?** No errors, just a dump of task history and a confirmation prompt.
- **What happened instead?** An error, see stack trace above.
## Reproduction Steps
1. Start web server
2. Start scheduler
3. `airflow clear example_xcom`

**Comment by r39132** [comment]
Per a conversation with @ty707 
He closed as it was not reproducible on a 1.7.0 pip install. This might have been a bug on a previous release or a result of an unclean install. Don't know which, but it is definitely not reproducible on 1.7.0.

**Comment by cognalog** [comment]
:+1:

**Comment by dennisobrien** [comment]
I am running into this same issue in `1.7.1rc1` as well as in `airbnb_1.7.1rc2`.  I'm installing via pip from requirements.txt:

```
-e git://github.com/airbnb/airflow.git@airbnb_1.7.1rc2#egg=airflow
```

In master, the section for `subparsers` includes a references to 'only_failed'
https://github.com/airbnb/airflow/blob/master/airflow/bin/cli.py#L830

But the same section in `airbnb_1.7.1rc2` (as well as `1.7.1rc1`) does not include a reference to 'only_failed'.
https://github.com/airbnb/airflow/blob/airbnb_1.7.1rc2/airflow/bin/cli.py#L644

But it looks like this was only recently introduced in master
https://github.com/airbnb/airflow/commit/6706babfd404173768b00f6add1b27d66d31a7e0
so I'll just sit tight until it is available in a tagged release.

**Comment by dennisobrien** [comment]
This is fixed in airbnb_1.7.1rc3 -- thanks!
