### ISSUE TITLE
Pre-commit for JSON schema validation

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#12358]
Hello,

We have several JSON schema specifications and files that we can check with them as pre-commit check, but this is not yet checked. I think it is worth adding such checking.

- [`dev/provider.yaml.schema.json`](https://raw.githubusercontent.com/apache/airflow/master/dev/provider.yaml.schema.json)
- [`chart/values.schema.json`](https://github.com/apache/airflow/blob/master/chart/values.schema.json)
- https://github.com/apache/airflow/issues/12357

This checks should take the path to the JSON Schema file and a list of JSON/YAML files to be validated as an arguments. 

Best regards,
Kamil Breguła

**Comment by AleksaC** [comment]
Hi, can I work on this?

**Comment by mik-laj** [comment]
We have pre-commit checks: https://github.com/apache/airflow/blob/71d874515a96369bce9a0c3d6e112929abd89f92/.pre-commit-config.yaml#L497-L543
