### ISSUE TITLE
In 2.0.0b2/master, CLI "airflow connections add" is not handling invalid URIs properly

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#12369]
**Apache Airflow version**: 2.0.0b2

**Environment**: Docker

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

In current 2.0.0b2, `airflow connections add` is not handling invalid URIs properly. 

For example, running CLI `airflow connections add --conn-uri xyz conn_dummy` will
- create the connection “conn_dummy” successfully (which should not be, IMO)
- in the connection created, it only has one attribute filled, which is “schema”, but the value added is “yz” (the value we provide is "xyz", i.e., the 1st element is removed. because of https://github.com/apache/airflow/blob/master/airflow/models/connection.py#L213)

<img width="552" alt="airflow_0284e070228e___" src="https://user-images.githubusercontent.com/11539188/99155673-519dca00-26ba-11eb-9517-31c1a238476f.png">

**What you expected to happen**:

In my opinion, a validation should be done first to ensure the `conn-uri` provided is valid (at least have “scheme” and “netloc” available in the `urlparse` result), and reject if it's an invalid URI.

**Comment by XD-DENG** [comment]
Hi @ashb @kaxil @mik-laj @turbaszek , let me know how you find this and whether agree with the idea I proposed above? Cheers.

**Comment by ashb** [comment]
Yeah that should be an error - the scheme at least should be required

**Comment by XD-DENG** [comment]
Let's enforce requiring at least `scheme` + `netloc`.

I will raise a PR either tonight or tomorrow

**Comment by kaxil** [comment]
Oh yes it should definitely raise an error

**Comment by jobegrabber** [comment]
@XD-DENG @kaxil I'm not sure if this should raise an error on missing `netloc` since at least for Google Cloud connections it is actually ignored: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#configuring-the-connection

This also caused a regression for us when upgrading to Airflow 2 and setting up connections through the CLI.
It took me a while to figure out what was causing the URI to become "invalid" - so this at least there should be a more precise warning about the actual part missing..

**Comment by jobegrabber** [comment]
> @XD-DENG @kaxil I'm not sure if an error should be raised on a missing `netloc` since at least for Google Cloud connections it's actually ignored: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#configuring-the-connection
> 
> This caused a regression for us when upgrading to Airflow 2 and setting up connections through the CLI. It took me a while to figure out what was causing the URI to become "invalid" - so this at least there should be a more precise warning about the actual part missing..

The workaround in our case was to simply add a stub `netloc`:
```diff
- google-cloud-platform://?extra__google_cloud_platform__project=...
+ google-cloud-platform://IGNORED_HOST?extra__google_cloud_platform__project=...
```
