### ISSUE TITLE
[ldap] section in configuration is not applicable anymore in 2.0

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#12385]
**Apache Airflow version**: 2.0.0b* / master

**What happened**:

`[ldap]` section in `airflow.cfg` is not applicable anymore in 2.0 and `master`, because the LDAP authentication (for webserver and API) is handled by FAB, and the configuration for this is handled by `webserver_config.py` file.

![airflow_–_default_airflow_cfg](https://user-images.githubusercontent.com/11539188/99289209-ef210700-283c-11eb-948e-16811ba09293.png)

**What you expected to happen**:

The `[ldap]` section should be removed from `airflow/config_templates/default_airflow.cfg` and `airflow/config_templates/config.yml` (and some other applicable files).

Otherwise leaving this section there will be a big confusion for users.

**Comment by XD-DENG** [comment]
@ashb @kaxil @turbaszek @mik-laj may you please help confirm if you agree or if I'm wrong?

If my understanding above is correct I will proceed to prepare the PR. Thanks.

**Comment by ashb** [comment]
Correct, this is for non-FAB UI

**Comment by XD-DENG** [comment]
> Correct, this is for non-FAB UI :boom:

Good. Will prepare a PR tonight
