### ISSUE TITLE
Best way to run an expensive task

### ISSUE THREAD

**Issue by adambom** [apache/airflow#124]
We have an expensive task (in terms of CPU and network). Basically, it will download data from S3 in CSV format, transform it into JSON then post it in batches to a third party API. We will need to do this for millions of records each hour.

We'd like to use airflow for its scheduler and dependency management, but we're not quite sure how best to structure the DAG so that this particularly expensive task, which is currently implemented as a PythonOperator, does not interfere with other tasks running on the same machine. We are using CeleryExecutor.

Is there a way to spin up one or more dedicated airflow workers on their own hardware and specify that this task and only this task should always run on the dedicated workers? I know there is a `queue` param available, but not sure if that's what we're looking for or how to use it.

**Comment by mistercrunch** [comment]
Yes! that's what queues are for:
http://pythonhosted.org/airflow/concepts.html#queues

Let me know if you have questions.

**Comment by adambom** [comment]
Thanks, will look into queues.
