### ISSUE TITLE
Duplicate connections UI

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#12401]
In the UI it would be nice to duplicate the selected connection, in the menu "With Selected". 

The copy would be set with the same name plus some suffix (_copy, _1, whatever) and it is useful for when you have a connection with all equal fields except something in a particular one.

**Comment by mik-laj** [comment]
Sound good to me. Can I assign you to this ticket?

**Comment by JavierLopezT** [comment]
> Sound good to me. Can I assign you to this ticket?

I have no clue how to approach this and right now I don't have time to investigate, sorry

**Comment by honarkhah** [comment]
I would like to work on this task, Should I add a new perm or use the can_create perm?
`airflow/www/templates/airflow/model_list.html:L71`
```python
      {% if can_show or can_edit or can_delete %}
        <td><center>
        {{ lib.btn_crud(can_show, can_edit, can_delete, pk, modelview_name, filters) }}
        </center></td>
      {% endif %}
```
I assume that we gonna have a button on the list and we gonna use the create form prefilled with the item that selected.

**Comment by mik-laj** [comment]
I think, you can use can_create perm.

**Comment by pateash** [comment]
I am working on this.
@mik-laj could you please assign this to me.

**Comment by pateash** [comment]
Implemented, multi-select and duplication.

![](https://user-images.githubusercontent.com/16856802/116422002-f5d88f00-a85c-11eb-99d5-e9648a6b8368.png)
