### ISSUE TITLE
Description Field for Variables

### ISSUE THREAD

**Issue by kurtqq** [apache/airflow#12413]
add text column to explain what the variable is used for

same as https://github.com/apache/airflow/issues/10840 just for Variables.

**Comment by kurtqq** [comment]
@abhilash1in  what do you think?

**Comment by abhilash1in** [comment]
That'll be useful, but I don't have the bandwidth for it right now, sorry.

**Comment by abhilash1in** [comment]
If you want to take a stab at it, I'll be happy to help.

**Comment by itroulli** [comment]
I'm willing to dive into this as my first attempt to contribute if there is still interest. I'll probably need some help to start though. I think it's a bit more tricky than the Connection description as the Variables are mostly handled as a key-value pair.

**Comment by kurtqq** [comment]
@itroulli why is it tricky? it's description per variable. it doesn't matter if the variable is text or key-value. the idea is to give general information to what the variable is used/who created it and stuff in that area.

**Comment by itroulli** [comment]
@kurtqq Sorry for the delay, I've been busy the past few days.

I had in mind some pieces of code like the import/export functions that treat variables as a key/value pair in which it would be required to change the struct to be able to import/export the description too. I might be wrong and have misunderstood something though. I'll try to give it a shot as soon as I find some time (first by skipping the description in functions like the import/export) and see what happens.

**Comment by kurtqq** [comment]
@itroulli I see the description field as a column in the DB that we are able to edit int he UI. This is a meta column that just give the ability to document why the variable was created and stuff like that.
I don't think it should involved the key,value properties of how you access to variables. So if you thinking about doing something like changing`Variable.get()` I don't think this is necessary.

**Comment by itroulli** [comment]
@kurtqq Tbh, that was indeed what I had in mind. So, I'll try to understand now, how the UI will be storing and retrieving the description content.

**Comment by itroulli** [comment]
According to my understanding, I'll have to create a file in `airflow/migrations/versions/` to add a column to the `variables` table but I'm not sure that I get how these files in the migrations folder work. Could you provide some resources? 
Thanks in advance!
