### ISSUE TITLE
The example DAG in the Tutorial does not work on Airflow 1.x

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [apache/airflow#12464]
Hello,

I tried installing the [tutorial DAG](https://airflow.apache.org/docs/stable/_modules/airflow/example_dags/tutorial.html)  and I got an import error:

```
No module named 'airflow.operators.bash'
```

The tutorial DAG had:

```
from airflow.operators.bash import BashOperator
```

I changed that to:

```
from airflow.operators.bash_operator import BashOperator
```
and was able to import the DAG.

This is on Airflow 1.10.11.

**Comment by jsrimr** [comment]
I experienced same issue when I executed the example on gcp VM.

you should install apache-airflow via sudo command.

```sudo pip3 install apache-airflow==1.10.14``` worked for me

**Comment by turbaszek** [comment]
> I tried installing the [tutorial DAG](https://airflow.apache.org/docs/stable/_modules/airflow/example_dags/tutorial.html) and I got an import error:

This link points to Airflow 2.0 which is not compatible with 1.10.X, please see tutorial for your version:
https://airflow.apache.org/docs/apache-airflow/1.10.11/_modules/airflow/example_dags/tutorial.html
