### ISSUE TITLE
Add API to query for providers

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12468]

**Comment by potiuk** [comment]
We can easly live without it for a while.

**Comment by nic314** [comment]
i'm new :) , If i got it correctly the task is to add a new rest api in https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html for retrive the list of installed providers similar to the cli "airflow providers list". I could work on that the next days.

**Comment by potiuk** [comment]
Cool ! correct assesment , I assigned the ticket to you :)
