### ISSUE TITLE
Display providers in Web UI

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12469]

**Comment by potiuk** [comment]
Not needed for now in 2.0. We can easily live without it.

**Comment by ShakaibKhan** [comment]
Hey, 
I wanted to try implementing this. Still getting familiar with Airflow and was wondering what information to display (provider package names and versions?) and where to put the page under (Browse?).

**Comment by potiuk** [comment]
Same as displayed in `airflow providers` CLI. And I think it is in the same menu where Plugins are :). Sounds very appropriate.

**Comment by ShakaibKhan** [comment]
PR to address this https://github.com/apache/airflow/pull/15385
