### ISSUE TITLE
Support deserialize_yaml in variable get

### ISSUE THREAD

**Issue by jtvmatos** [apache/airflow#12480]
**Description**
Airflow variables with the (de)serialize_json flag is an great feature.
Nevertheless, i believe that airflow should also have an option to have variables with YAML string.
YAML are better suited for configuration, and it is designed to be more readable/editable by humans than JSON.

**Use case / motivation**
Using a YAML string instead of a JSON string is more practical and less error prone. 
For example the difference between editing this:
> flow: 
>   - source:
>         - value: x1
>         - value: x2
>         - value: x3
>   - destination:
>         - value: x1
>         - value: x2
>         - value: x3

and this:
> { "flow": [ { "source": [ { "value": "x1" }, { "value": "x2" }, { "value": "x3" } ] }, { "destination": [ { "value": "x1" }, { "value": "x2" }, { "value": "x3" } ] } ] }

I believe that there are already many people to use YAML in their variables and then convert the string inside the dag.
However, this logic could be within the model of the variable, and have a `variable.get` flag to import yaml strings.

**Related Issues**

**Comment by SevakAvet** [comment]
I'll take this.

**Comment by ashb** [comment]
Can you explain why we need this, and why json isn't enough?

Mostly I'm not sure I like the the precedent of supporting multiple encoding types for variables.

Accepting YAML for input only _might_ be acceptable, but I think it should then be converted to JSON for storage (see the discussin in #13022) -- we could then also _maybe_ convert it back to YAML for display. But it should be stored as json so there is less code paths to deal with.

**Comment by ashb** [comment]
Closing as "Wont Support" -- it adds a reasonable amount of extra complexity for minimal benefit. (_Storing_ as yaml isn't needed, we could simply make this a UI concern but still store as JSON.)
