### ISSUE TITLE
Consider removing dependency on NumPy

### ISSUE THREAD

**Issue by adambom** [apache/airflow#125]
The longest two steps in installing airflow are setup for Pandas and Numpy. Pandas seems like it's pretty important, but numpy doesn't seem to be used too heavily:

https://github.com/airbnb/airflow/search?utf8=%E2%9C%93&q=numpy&type=Code

Seems like overkill to import all of numpy just to do type checking. Are there any alternatives? Am I missing anything important?

**Comment by artwr** [comment]
@adambom 
We are thinking of refactoring the mysql_hook slightly, but pandas requires Numpy (See https://github.com/pydata/pandas). I am not sure we can get around that.

One idea would be to install the OS binary package (yum or apt-get install python-numpy usually) and running the airflow install with `--ignore-installed`, but this is a little beyond my expertise. See for instance : 
http://stackoverflow.com/questions/12079607/make-virtualenv-inherit-specific-packages-from-your-global-site-packages
http://stackoverflow.com/questions/14571454/virtualenv-specifing-which-packages-to-use-system-wide-vs-local

**Comment by seibert** [comment]
Numpy is a direct dependency of pandas, so it would not help to remove it from airflow.

**Comment by mistercrunch** [comment]
I like to have Pandas around in application that have an analytics / charting component. I'm well aware of how compiling numpy/pandas is a pain though. 

I think the main place where it is used is in the "Data Profiling" web views, that probably could ship as an Airflow plugins. I can't justify to the time to perform this surgery though... Installing numpy isn't that bad, and many will ask for the pandas library to use in their PythonOperator, so you may have to install it anyhow. Closing for now.
