### ISSUE TITLE
Investigate removing pandas dependency from Core Airflow

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12500]
I want to take a look at removing numpy/pyarrow from _core_ airflow. We don't really need it, and it would make installing easier.

After 2.0

_Originally posted by @ashb in https://github.com/apache/airflow/issues/11950#issuecomment-731115568_

**Comment by turbaszek** [comment]
+1 for that, I faced some dependency issues with pyarrow too

**Comment by potiuk** [comment]
Oh yeah! That will help with #11950 as well!

**Comment by turbaszek** [comment]
Searching for `pandas` import it seems that only `DbApiHook` requires it explicitly for one method: `get_pandas_df`.
Apart from that:
```
root@1572924b0714:/opt/airflow# pipdeptree -r -p pandas
pandas==1.1.0
  - apache-airflow==2.0.0b3 [requires: pandas>=0.17.1,<2.0]
  - nteract-scrapbook==0.4.1 [requires: pandas]
  - pandas-gbq==0.13.2 [requires: pandas>=0.19.0]
```
Where `nteract-scrapbook` is required for `papermill` provider and `pandas-gbq` is for `google`. I removed pandas from setup.cfg and using clean venv installed airflow. No pandas was installed and running few airflow commands showed no errors.

**Comment by ashb** [comment]
It probably used to be used more - in the old chart view I think, but we've removed those uses now.

**Comment by ashb** [comment]
And no pandas means no numpy right?

**Comment by turbaszek** [comment]
> And no pandas means no numpy right?

Probably. I forgot check it but no idea where we would need it

**Comment by jchacks** [comment]
https://github.com/apache/airflow/blob/7d38645472b0502212504b09d85b0e1271d74274/airflow/utils/json.py#L21
That line in utils imports numpy, not sure if this is relevant.
It was causing my webserver to crash since my airflow version doesnt install numpy by default.
