### ISSUE TITLE
Manual change of dag_run state, leaves database in inconsistent state 

### ISSUE THREAD

**Issue by marino-19** [apache/airflow#1250]
# Environment
- Version of Airflow: 1.6.2
- Operating System: Linux 
- Python Version: Python 2.7.11
# Description of Issue

When you try to manually change the state of a dag_run via this view:
![screenshot_manual_state_change](https://cloud.githubusercontent.com/assets/5970618/14121232/ddc8551c-f5f6-11e5-9038-d46f004e0f41.png)

the dag_run is not correctly updated in the database. Indeed, in the Tree view the global state of the dag_run becomes white (=no satus). See below:

![screenshot_after_dag_run_state_change](https://cloud.githubusercontent.com/assets/5970618/14121303/2474993a-f5f7-11e5-9c91-af327e352cec.png)

And if you click on the white box, I get an error page with following error:

![screenshot_error](https://cloud.githubusercontent.com/assets/5970618/14121324/3497c15c-f5f7-11e5-8194-b5850eeafc1d.png)

**Comment by bolkedebruin** [comment]
Can you please create a Jira issue for this?
