### ISSUE TITLE
Global state of dag_run is not in sync with status of the subtasks after re-run of a subtask

### ISSUE THREAD

**Issue by marino-19** [apache/airflow#1251]
# Environment
- Version of Airflow:1.6.2
- Operating System: linux
- Python Version: 2.7.11
# Description of Issue

Suppose you have a dag_run with one failed task. It is possible to re-run this failed task via the UI. Suppose that after the re-run the state of the task becomes success, then the global state of the dag_run stays "failed" and is not updated to "success". You can see this clearly in the tree view (= for a certain dag-run, the global state is red , while all the substasks are green)

**Comment by bolkedebruin** [comment]
@tl-marino can you please create a Jira for this? Thanks!
