### ISSUE TITLE
Missing "parse_dates" parameter in .read_sql

### ISSUE THREAD

**Issue by timseries** [apache/airflow#1253]
Not much needs to be explained here, seems as though the DbApi hook's `get_pandas_df` is dropping the ability to pass a list of columns (or date parser functions) to the ever useful Pandas'  `read_sql`.

https://github.com/airbnb/airflow/blob/60e22ed50d485eb0bcc556b7826299c6b813efc3/airflow/hooks/dbapi_hook.py#L52

Seems like the workaround would be to introduce an additional, Pandas-specific "params" argument to this method.

**Comment by jlowin** [comment]
@timseries I think that would be a good enhancement. Would you like to make a PR for it? Adding a `pandas_params` dict should do the trick.

**Comment by timseries** [comment]
No problem!

**Comment by bolkedebruin** [comment]
@timseries any update?
