### ISSUE TITLE
Describe all extras that can be installed with Apache Airflow 

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12544]
**Description**

While installing `apache-airflow[google]` may suggest that we will install some google-related packages. It's less obvious what gets installed when users use `all`, `devel`, `devel_ci` or `all_dbs`.

**Use case / motivation**

Having a short note in documentation about the "non obvious" extras may reduce confusion and will help users understand what is installed when the extra is used without diving deep into `setup.py|cfg`

**Related Issues**

#12543 
https://apache-airflow.slack.com/archives/CCPRP7943/p1606044442396600?thread_ts=1605991398.394500&cid=CCPRP7943

**Comment by potiuk** [comment]
Actually - we do have a description already it seems : https://github.com/apache/airflow/blob/master/docs/extra-packages-ref.rst and it even contains correct description "All Airflow features known to man"

**Comment by turbaszek** [comment]
> it even contains correct (though ambiguous) description "All Airflow features known to man"

Not sure if this is correct as `all` contains also devel stuff. So yeah, there's too much ambiguity. I will try to take a look at that.
