### ISSUE TITLE
Python3.8 and botocore install issue for docutils

### ISSUE THREAD

**Issue by gfelot** [apache/airflow#12545]
**Apache Airflow version**: 1.10.12

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): ubuntu 20.04 LTS

**What happened**:

Trying to install Airflow as recommanded with 3.8 constraint.

`pip install "apache-airflow[crypto,password,postgres,aws]"==1.10.12 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.8.txt"``

I got the error : 
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

botocore 1.17.43 requires docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
```

In the constraint file botocore is set to 1.17.41, but reading this issue it should be 1.18.0 (1.19.23 in fact) : https://github.com/boto/botocore/issues/2120

I recomend to upgrade the file to botocore to 1.19.23 & boto3 to 1.16.23.

**What you expected to happen**:
Install should go flowless

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/pulls

**Comment by potiuk** [comment]
We solved it for 2.0. https://github.com/apache/airflow/pull/12664

I do not think we will be able to fix it for 1.10.12 as it is a fundamental problem with how PIP handles requirements. We found a solution that we applied to 2.0 https://github.com/apache/airflow/pull/12664 but it requires adding additional limitations for airflow itself which we won't be able to do in already released version. 

So we are not going to be able to do anything for 1.10.12. My recommendation is to update the packages manually.

I will see however, if I will be able to add it to the upcoming 1.10.14 version. I know now why Airflow had always problems with those conflicting requirements (PIP handling resolving of dependencies is a bit brittle) so I can apply the same solution.

**Comment by potiuk** [comment]
Hello @gfelot -> can you please try the latest constraints ( https://raw.githubusercontent.com/apache/airflow/constraints-1-10/constraints-3.8.txt ). I just updated all the constraints for 1.10.14 upcoming release and indeed docutils are 0.15.2 there. There is high chance it will work for 1.10.12 as well, so if you can give it a shot - please.

I just implemented the same approach as we hve in Airflow 2.0  -we run `pip check` before updating the constraints, so it should continue to be valid for the future.

**Comment by ranamit112** [comment]
Is there a plan to change the published constraints file for 1.10.12 so that it would be installable with the constraint file as recommended? (https://github.com/apache/airflow/blob/constraints-1.10.12/constraints-3.7.txt)
I tried installing with python3.7 and had the same error as OP and changing `docutils==0.16.0` to `docutils==0.15.2` or just dropping that specific constraint like fixes the pip install problem with the [aws] extra. 

I am aware it is recommended to move to 2.x, but to upgrade to it, it seems best to first upgrade to something like 1.10.12 - which doesn't deprecate things, then upgrade to 1.10.14 (changing deprecated features), and then to 2.x.

**Comment by potiuk** [comment]
No plans. But you can easily copy the file locally, modify and use it as you wish locally instead of taking it from the remote:

```
`pip install "apache-airflow[crypto,password,postgres,aws]"==1.10.12 --constraint your-modified-constraint-file.txt
```

**Comment by potiuk** [comment]
BTW. I would not recommend going to 1.10.12 as an intermediate step. There is no reason to do it I think. While there are a number of deprecated things in 1.10.14 (or rather 1.10.15 now), the deprecated functionality continue to work there. So I would strongly encourage you to upgrade straight to 1.10.15.
