### ISSUE TITLE
Introduce 'everything' extra in setup.py

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12543]
**Description**

Introduce a `everything` (or other name) extra so users can do `pip install apache-airflow[everything]` to install all additional user-related extras (no docs, no ci, no dev packages).

**Use case / motivation**

Simplify installing all user-related extras. Currently I need to put whole list of all extras to install everything.
I'm not sure if many users will install everything but in case they did, they will be able. And it can help us with testing.

**Related Issues**

#12508 
https://apache-airflow.slack.com/archives/CCPRP7943/p1606034789396100?thread_ts=1605991398.394500&cid=CCPRP7943

**Comment by ashb** [comment]
I went back and looked, and `all` extra has been devel back to at least 1.9, I think we should rename that to `devel_all` for clarity, and then make `all` be the extra you describe here.

My thinking is `all` and `everything` would need clarification on docs, but `all` and `devel_all` is hopefully clearer.

**Comment by potiuk** [comment]
Yeah I also looked it up today seeing that it was added in 2015 in fact (i even found the right commit where it was added in 2015 ! 

https://github.com/apache/airflow/commit/1d56f22f2e470ff5e9db0a24b3e4a4516cbf1811
