### ISSUE TITLE
Add ORC support to GCSToBigQueryOperator

### ISSUE THREAD

**Issue by juneoh** [apache/airflow#12556]
**Description**

[BigQuery API for loading data](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad) lists ORC file format as one of the supported formats, but it is currently not allowed in GCSToBigQueryOperator. Specifying ORC as the source format raises a [ValueError in BigQueryHook](https://github.com/apache/airflow/blob/a3dfd04ce4224e80c7b32351a744980e72bc10aa/airflow/providers/google/cloud/hooks/bigquery.py#L1667).

**Use case / motivation**

Include ORC file format in BigQueryHook so that GCSToBigQueryOperator will fully allow all file formats supported by the BigQuery API.

**Comment by turbaszek** [comment]
As mentioned in PR the `run_load` method is deprecated and users should use `insert_job` method which supports everything possible. That said, the change we should do is to update `GCSToBigQueryOperator` to use new method instead of the old one, see https://github.com/apache/airflow/issues/10288

**Comment by mik-laj** [comment]
@juneoh Are you willing to submit a PR?

**Comment by juneoh** [comment]
Sure, I'll take a look during the holidays.

**Comment by juneoh** [comment]
I've learned that holiday productivity is an illusion. I'll check in again next week as I'm ramping back up.

**Comment by juneoh** [comment]
Started working on this. Upon studying the history, looks like we need to fix the both paths in execute() for BigQuery and external tables to stop using the deprecated methods, which will likely to fix #10288 and #12329 along the way.

**Comment by juneoh** [comment]
Still working on this. The basic implementation is done but it's mostly a copy-paste from the BigQuery hook, so I'm trying to see what additional refactoring and testing is possible with the leverage of BigQuery Python SDK.

**Comment by eladkal** [comment]
@juneoh  are you still working on it?

**Comment by eladkal** [comment]
The fix needed (while small) is in a deprecated function of the hook.
The function is deprecated for almost 2 years I believe we are closer to remove the function rather than fixing a bug in it.
Also no one tried to address this issue for very long time so I guess most users already moved away from the deprecated function.

I'm closing this issue as won't fix
