### ISSUE TITLE
New Documentation link to the "directory" from generated documentation

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12553]
Version: Airflow 2.0.0b3

I think we shoudl have a link from "apache-airflow" and each "provider" documentation back to the "directory". I think eventually people will land on the main "airflow" page (via google search) and it will be very difficult for them to find the "providers" if they are not linked to prominently.

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by mik-laj** [comment]
Yes. I know this and it will be done with the Sphinx theme. I see it as there will be an Airflow theme (preview: https://airflow.apache.org/docs/stable/). On top navbar, we will have link to: http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/ Additionally, breadcrumbs will also have a link to http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/
I take care of it step by step to be able to respond to all problems.

**Comment by potiuk** [comment]
Cool!

**Comment by mik-laj** [comment]
Finally, I want it to look similar to these pages:
https://www.hashicorp.com/products/terraform
https://docs.microsoft.com/en-us/azure/?product=featured

**Comment by mik-laj** [comment]
Now we have "Documentation" link in the navbar.
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/index.html

**Comment by mik-laj** [comment]
Here is PR with index page for airflow-site: https://github.com/apache/airflow-site/pull/318/files
