### ISSUE TITLE
Remove or limit table of content at the main Airflow doc page

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12554]
Table of content here : http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/index.html at the main page of "apache-airflow" documentation is huge and useless (especially that we have it in directory on the left). 

We should remove it or limit heavily (to 1st level only)

![Screenshot from 2020-11-22 20-34-28](https://user-images.githubusercontent.com/595491/99915147-27738a00-2d02-11eb-8e6b-1e2717180f26.png)

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by mik-laj** [comment]
It seems to me that it cannot be removed completely, but it will probably be possible to limit the levels of the depth quite simply.

I don't have plans to do it any time soon. I will add the label "good-first-issues" label.Maybe another person will be willing to take care of it.

**Comment by potiuk** [comment]
Cool!

**Comment by ashb** [comment]
@mik-laj You reverted this change so it's a problem again.

**Comment by mik-laj** [comment]
> We should remove it or **limit heavily (to 1st level only)**

In my opinion, this ticket is already resolved.
