### ISSUE TITLE
Ability to provide sample conf JSON for a dag in trigger page

### ISSUE THREAD

**Issue by aniketbhatnagar** [apache/airflow#12550]
**Description**
In the trigger page, there is a text area to enter (optional) conf json. It would be great if a sample JSON can be provided programatically while defining DAG

**Use case / motivation**

This will improve usability of the UI that triggers a DAG

**Comment by mik-laj** [comment]
In Airflow 2.0, you can pass this as a `params` parameter. I don't know if this exists in Airflow 1.10. I also have serious concerns that this option is not documented. Would you like to add documentation?
https://github.com/apache/airflow/blob/8b95e513704b91110c47f424c4376a20560eccc4/airflow/www/views.py#L1426

**Comment by ashb** [comment]
I think (correct me if I'm wrong @aniketbhatnagar ) that he is asking for some in-page docs/example showing what to put in the textarea on the trigger page.

**Comment by aniketbhatnagar** [comment]
> page

Yes, that is correct and customizable per DAG. We right now have to document that outside airflow.

**Comment by mik-laj** [comment]
Will it be sufficient for you if DAG.doc_md was displayed on the trigger screen?

**Comment by aniketbhatnagar** [comment]
Yes, I think that should suffice.

**Comment by mik-laj** [comment]
Would you like to open a PR with a proposal for such a change? I am happy to help with the reviews.

**Comment by jyotidhiman0610** [comment]
@mik-laj Can I take up this issue?
