### ISSUE TITLE
Initialization of Dataproc hook in operator constructor

### ISSUE THREAD

**Issue by ibeauvais** [apache/airflow#12560]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.15.12-gke.20

**Environment**:

- **Cloud provider or hardware configuration**: Google Cloud Platform (Composer 1.12.4 )
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
On an environment with a lot of dataproc tasks (spark), we have a lot of performance issues. 
After investigation, It seems related to the problem below:
For all dataproc operators, hooks are initialized in the constructor instead of the execute method. The hook initialization results in a significant overhead because it accesses the airflow database (get_connection).
The operator's constructor is executed for each task by the scheduler and the workers which induces performance degradation for a large amount of dataproc tasks.

Similar problem already fixed in past : #5893 for other GCP operators

The code lead to the issue in dataproc_operator.py, all operator inherit from DataprocOperationBaseOperator :
```

class DataprocOperationBaseOperator(BaseOperator):
    """The base class for operators that poll on a Dataproc Operation."""
    @apply_defaults
    def __init__(self,
                 project_id,
                 region='global',
                 gcp_conn_id='google_cloud_default',
                 delegate_to=None,
                 *args,
                 **kwargs):
        super(DataprocOperationBaseOperator, self).__init__(*args, **kwargs)
        self.gcp_conn_id = gcp_conn_id
        self.delegate_to = delegate_to
        self.project_id = project_id
        self.region = region
        self.hook = DataProcHook(
            gcp_conn_id=self.gcp_conn_id,
            delegate_to=self.delegate_to,
            api_version='v1beta2'
        )
```

**What you expected to happen**:
Dataproc hook should be initialized in execute method

**Comment by turbaszek** [comment]
That's already done in new operators. We don't use `DataprocOperationBaseOperator` anymore. See:
https://github.com/apache/airflow/blob/c133df806247cfde87ba461ed22ee924d8d31fd3/airflow/providers/google/cloud/operators/dataproc.py#L389
https://github.com/apache/airflow/blob/c133df806247cfde87ba461ed22ee924d8d31fd3/airflow/providers/google/cloud/operators/dataproc.py#L1747

**Comment by turbaszek** [comment]
I would also suggest to migrate to 1.10.12 and use the providers packages with new operators - the ones that are supported and will be required for Airflow 2.0.
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/backport-providers.html?highlight=providers

**Comment by ibeauvais** [comment]
thanks for this very helpful information
