### ISSUE TITLE
DockerOperator causes log spam when pulling image

### ISSUE THREAD

**Issue by metov** [apache/airflow#12576]
**Apache Airflow version**: 1.10.4
**Environment**:
- **Cloud provider or hardware configuration**: AWS EC2
- **OS** (e.g. from /etc/os-release): ubuntu

**What happened**:
I am using `DockerOperator` in Airflow set to pull the image before executing. The pull step generates a lot of log spam:
![Screen Shot 2020-11-23 at 11 58 40 AM](https://user-images.githubusercontent.com/51468504/100010338-fab48680-2d84-11eb-8862-92e3540018b2.png)

For example the above log has 1104 lines, of which 1045 are Docker pull output.

**What you expected to happen**:
When nothing goes wrong, either of these three options:
* No output from Docker pull
* A single line saying the pull succeeded
* Several lines, one for each parent image, saying that the pull succeeded

When the pull fails, I expect a single line explaining that the pull failed and how/why.

The Docker pull output is clearly meant for an interactive shell as it is trying to display a live progress report. I see that [in my version](https://github.com/apache/airflow/blob/1.10.4/airflow/operators/docker_operator.py#L210-L212) the output is simply copied to the log. The [more recent version](https://github.com/apache/airflow/blob/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5/airflow/providers/docker/operators/docker.py#L287-L291) also has similar code so I'm assuming the latest Airflow has the same problem.

**How to reproduce it**:
I think simply creating a DAG with a `DockerOperator` that has `force_pull=True` should reproduce the issue.

**Comment by XD-DENG** [comment]
Thanks @metov for reporting the issue. I will take a look.
