### ISSUE TITLE
How to convert a JSON string into a DAG object?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [apache/airflow#12583]
Hi,
I have read the project codes of "airflow", and it is said that "Use Airflow to author workflows as directed acyclic graphs (DAGs) of tasks". Now, I have a task to read the following json string which will be used to construct a DAG. I have been told to use the "DAG engine", so could you pls tell me whether your codes can implement my function? Also, how to build a DAG object from Json using "your DAG engine"? Thanks!

"
{
"type": "Invocation",
"arguments": {
"DEFAULT_EXPRESSION_IMAGE": {
"type": "Invocation",
"arguments": {
"id": "LC08/01/T1/LC08_121031_20181019"
},
"functionName": "Image.load"
},
"B4": {
"type": "Invocation",
"arguments": {
"input": {
"type": "Invocation",
"arguments": {
"id": "LC08/01/T1/LC08_121031_20181019"
},
"functionName": "Image.load"
},
"bandSelectors": "B4"
},
"functionName": "Image.select"
},
"B5": {
"type": "Invocation",
"arguments": {
"input": {
"type": "Invocation",
"arguments": {
"id": "LC08/01/T1/LC08_121031_20181019"
},
"functionName": "Image.load"
},
"bandSelectors": "B5"
},
"functionName": "Image.select"
}
},
"function": {
"type": "Invocation",
"arguments": {
"expression": "(B5-B4)/(B5+B4)",
"argName": "DEFAULT_EXPRESSION_IMAGE",
"vars": [
"DEFAULT_EXPRESSION_IMAGE",
"B4",
"B5"
]
},
"functionName": "Image.parseExpression"
}
}
"

Best Regards,
Jennifer Wu

**Comment by turbaszek** [comment]
@JenniferYingyiWu2020 I'm afraid that Airflow natively does not support building DAGs in declarative way (either using json or yaml). But you can definitely write your own code generator that will convert your json to Airflow DAG file (.py file). You may want to take a look at this:
https://github.com/chriscardillo/gusty
https://github.com/Barski-lab/cwl-airflow
