### ISSUE TITLE
Run webserver without installing dag dependencies

### ISSUE THREAD

**Issue by honarkhah** [apache/airflow#12590]
**Description**

In order to have the webserver easy to maintain and scale it is nice if we can ignore dag dependencies (ex: python libraries) on the webserver and only install them on the worker.
currently webserver throwing an error `{dagbag.py:259} ERROR - Failed to import`

**Use case / motivation**

I want to have the webserver totally independent of what needs to be done! from my perspective only workers need to have all the dependencies installed, also the scheduler could ignore them!

**Comment by ashb** [comment]
2.0.0 does this already, as the Webserver now relies on Dag Serialization and reads things from the DB only.

Easiest issue fix ever -- cos it's already done :grin:

**Comment by ashb** [comment]
The scheduler will need them too -- as it "parses" the dag files. The way to avoid needing them on the scheduler is to not have imports at the top-level that are only needed inside execute functions

**Comment by honarkhah** [comment]
is the v2.0.0 stable now? I had a bad experience with serialized dag in < v1.10.13

**Comment by ashb** [comment]
From our testing, yes. It's not yet released "GA", but it's getting very close! If you have time to test the beta releases (latest is beta3) that would be helpful!
