### ISSUE TITLE
Kubernetes worker pod doesn't use docker container entrypoint, removing OpenShift support

### ISSUE THREAD

**Issue by matthieu-foucault** [apache/airflow#12602]
**Apache Airflow version**: 2.0.0-b3

**Kubernetes version**:  v1.18.3+47c0e71, OpenShift v4.5

**What happened**:

When starting a worker pod with the `KubernetesOperator`, the python script fails to import `airflow`

**What you expected to happen**:

Running a docker container in OpenShift is usually done with the "Restricted" Security Context Constraint, meaning that the container will be run with an arbitrary UID, and GID 0. The airflow docker image supports this (https://github.com/apache/airflow/pull/9545), which relies on the following lines from the container entrypoint: 

https://github.com/apache/airflow/blob/6caf2607e04f581abdcb38fdbc426e03d5307429/scripts/in_container/prod/entrypoint_prod.sh#L93-L99

However, the entrypoint is currently overridden:

https://github.com/apache/airflow/blob/dd2095f4a8b07c9b1a4c279a3578cd1e23b71a1b/airflow/kubernetes/pod_generator.py#L395-L399

https://github.com/apache/airflow/blob/dd2095f4a8b07c9b1a4c279a3578cd1e23b71a1b/airflow/executors/kubernetes_executor.py#L291-L303

`command` changes the container `ENTRYPOINT` (not the `CMD` as one might think :zany_face: ), which means that the production image entrypoint is not used by the worker pod, preventing the airflow command from executing properly. To execute a custom command while keeping the original entrypoint, one should use the `args` parameter instead of `command`
 
Looking at this with @pbastia. Sounds like a solution would be to:
 - add an `args` parameter to `PodGenerator.construct_pod`
 - in the kubernetes_executor, set `args` to `command[1:]`, since the container entrypoint expects an airflow command by default (see below)

https://github.com/apache/airflow/blob/6caf2607e04f581abdcb38fdbc426e03d5307429/scripts/in_container/prod/entrypoint_prod.sh#L135

Happy to open a PR for it if that sounds like an acceptable change.
cc @dimberman 

**How to reproduce it**:

Run any dag in OpenShift, using the restricted SCC

**Comment by ashb** [comment]
@matthieu-foucault Yes please, a PR would be ace!

**Comment by ashb** [comment]
Please also (somewhere) document what Airflow requires of the image being run.

Because there are at least  three "common" images that people might run (airflow, puckel, astronomer) and they might all handle this differently.

**Comment by matthieu-foucault** [comment]
Thanks for the info! The official production image also accepts commands that start with `bash`, so that option should be compatible with all four images

**Comment by ashb** [comment]
`bash -c "airflow ..."` would be an absolute last resort

**Comment by dimberman** [comment]
@ashb @matthieu-foucault This all sounds great! Definitely would rather avoid using bash within the entrypoint. I think we can start by just making this compliant with the official production image and then alert the maintainers of the other images when this is merged.

**Comment by potiuk** [comment]
> @ashb @matthieu-foucault This all sounds great! Definitely would rather avoid using bash within the entrypoint. I think we can start by just making this compliant with the official production image and then alert the maintainers of the other images when this is merged (hence why it is the official one :) )

Yep @dimberman . The official image is already Open-Shift compliant and I think it has all the required options in the entrypoint (you can specify bash 'command' as parameter and it will just 'exec' the command from the entrypoint. So I think it's just a matter of switching to the image.

**Comment by ashb** [comment]
@potiuk Check out Daniel's PR though please -- to make the "official" image support the common pattern that all the other common docker images support, we have changed it to accept `[airflow, task, run, ...]` as well as `[task, run, ...]` CMD (in docker speak. I'm unduly annoyed that Kube and Docker use the same term to mean **conflicting** things)

**Comment by potiuk** [comment]
Surely. I have not been marked as a reviewer on that. But this is a super-easy change to the official Dockerfile that I will open now.

**Comment by ashb** [comment]
@potiuk Already done as part of https://github.com/apache/airflow/pull/12766

**Comment by potiuk** [comment]
I will make a separate smaller change which will be backwards compatible with the old behaviour, also documentation in 'production-deployment.rst' needs to be updated. I think it's worth to separate it out.

**Comment by potiuk** [comment]
I extracted it: #12878 is much smaller, cleaner, backwards compatible and I also updated documentation  - adding the _CMD case and clarifying some details.
