### ISSUE TITLE
Integration list synchronization with airflow-site

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#12613]
Hello friends.

Today I am coming to you with another ticket. This time, while working on the website, I discovered that we have some information that is slightly outdated.

[`landing-pages/site/static/integrations.json`](https://github.com/apache/airflow-site/blob/master/landing-pages/site/static/integrations.json
) file have lists all the integrations that have been added to Airflow, but unfortunately it is updated manually.  Recently, new services were added there on Oct 2019

We can think of a tool that will update this list more automatically by reading the integration list from [provider.yaml](https://github.com/apache/airflow/find/master) files, and then creating an integration.json file that can be published to the airflow-site.

For now, we need a manual run script, but in the future, we can also run it on Github Action or during updates and documentation.

CC: @ryw

**Comment by ecerulm** [comment]
I can work on this
