### ISSUE TITLE
Send failure email just if all retries fail

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#12612]
Let's say that you have a DAG with 8 retries and email_on_failure=True. 

The first 6 times it fails due to a server conn error, and on the 7th it works. I really don't care why it failed the first six times, and I will care just if it fails the 8th time. 

It would be nice to have a parameter that allows us to only receive an email if all 8 retries fail.

**Comment by turbaszek** [comment]
Won't that be handled by `on_failure_callback`?

**Comment by JavierLopezT** [comment]
> Won't that be handled by `on_failure_callback`?

Since you say so, I guess it will be possible, but after a quick research on Google I can't figure it out. My idea is having a parameter like 'email_on_fail_retries' that you can set to False, which I think is way easier than doing it with on_failure_callback. 

Also, not sure if I understood correctly, but you would have to have the callback function on every dag that you want to use it, right? So it will be a lot of duplicated code (or more complexity added creating a module or something like that)

**Comment by turbaszek** [comment]
> you would have to have the callback function on every dag that you want to use it, right? So it will be a lot of duplicated cod

Use cluster policy. As per the emails, I wanted to point to `email_on_failure` not `on_faliure_callaback`.

**Comment by JavierLopezT** [comment]
Ok, I thought email_on_retry was False by default. Setting that to False, email_on_failure does exactly what I want. Sorry for the inconveniences and thanks for you help @turbaszek . I'll close the issue
