### ISSUE TITLE
Switch from Email to general/extensible Notifiers

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#12611]
**Description**

Replace the "email" API with a "notification" API that would let us integrate better with our workflow without adding extra code to the DAGs.

1. Change "[email]" to "[notification]"
2. Add "webhook", "gcp_error_reporting" and "aws_cloud_watch" notification methods

**Use case / motivation**

Though email es arguably the most used tool for communication Cloud infrastructures usually have a centralized tool to report problems in execution.

* GCP Error Reporting
* AWS CloudWatch Alarms
* Azure Application Insights
* DataDog
* New Relic
* ...

Also it would be nice to have an extensible way of triggering webhooks for notifying the common enterprise messaging tools like

* Slack
* MS Teams
* ...

We already have the "smtp", "sendgrid".

**Comment by turbaszek** [comment]
I think this is a good suggestion. Apart from that:
- instead of custom code in every DAG you can use cluster policy
- in case of slack - you can send emails to channels (slack provides this feature)

**Comment by mik-laj** [comment]
I would be most interested in integrating with PubSub. This would allow data synchronization with Airflow in the Push model, and not only fetch it via API (Pull model)

I saw that someone had already started working on it, but never finished.
https://github.com/apache/airflow/pull/2412

**Comment by eladkal** [comment]
It has some similarities with https://github.com/apache/airflow/issues/8686

**Comment by simon-k** [comment]
This would be really usefull.

**Comment by dinigo** [comment]
Thanks for the bump @eladkal 

We both,  OP from #8686 struggle with integrating Airflow in a SRE control plane

**Comment by ashb** [comment]
In response to someone asking this on the mailing list I proposed this API: https://lists.apache.org/thread.html/rcd7fbd99408f5cdc1cc09e8a1619b629743da158ecf4c9d0eeb411f1%40%3Cdev.airflow.apache.org%3E

```python
from airflow.providers.slack.notifiers import send_slack_message

task = MyOperator(
    task_id = "something",
    on_failure_callback= send_slack_message(
        slack_conn_id='slack-default', # Default, not actually required 
here, for example only
        channels=['#data-ops'],
        mentions=['@ash'],
    ),
)
```

Names can be changed/discussed, this is just a rough idea.

Using this approach means that a) We don't need to add a whole bunch of 
new config, and b) it can be easily extended/created by providers 
without needing changes to core -- after all the feature to run code 
after failure/success already exists, we just want to "package up" the 
common task of sending a slack message.

I think for consistency of interface too we should deprecate the 
email_on_failure task attribute too in favour of a similar function.

And finally, perhaps `on_*_callback` gets extended to allow a list of 
functions instead of just one.

**Comment by mik-laj** [comment]
I don't have time to look at the details, but I found a library that we can use to build notifications.
https://github.com/caronc/apprise
Is it compatible with your proposal?

**Comment by dinigo** [comment]
Looks amazing.
I was thinking on something to send errors to GCP error reporting. But this supports the custom JSON. In general having a notification API so people can plug their notification libraries. But yes, this certainly do :)

**Comment by subkanthi** [comment]
Just curious about the implementation details for this.
Is the plan to create a base notifier(BaseNotifier like BaseOperator) class and implement them for every provider, we already have opsgenie, pagerduty, slack and sengrid as providers. 
I can take this on if it's not being worked on.

**Comment by BasPH** [comment]
I think this is quite a big change and am leaning towards an AIP. Thoughts? @ashb others?

**Comment by ashb** [comment]
Given the current discussion around multi tenancy (aip 43 or 44) well need to work out how to do this securely.

/cc @potiuk another thing to factor in. (I think we can do it similar to how we do operator links).

I think this change is borderline on needing an AIP (that is I _don't_think it needs an AIP) - it's not necessarily a big architectural change and is easy to do fully backwards compatible.

**Comment by potiuk** [comment]
Yeah. I also think it's not really AIP-worthy.  

But this is very good point with the multi-tenancy interaction

I am performing an inventory of stuff that will be afected by multitenancy proposals and I will take a look on the notifications as well then and think about it (and for sure we will raise it in the API AIP). While the notification mechanism (emails) use now the "Connection" for authentication, it would be good indeed to "hide" that information from the caller - if it is a worker, or "DagProcessor" or "Triggerer" as this is really a shared service. As such this is definitely part of the 3rd AIP that follows (fine-grained access to resources) where this one falls in). And then whe we implement such fine-grained access we could potentially move it to the same place where other "Internal API calls" will be executed (which brings me more to the point of our recent discussions with @mhenc that we should not call it "DB-API" but "Internal API" sounds much more appropriate.

So we will keep an eye on that one.

However, ine thing that might be good to mention is to make it part of the Provider's interface. We already have a number of Providers (Slack, AWS, Azure, DataDog)  - and similarly as with other "core-extensions" those seem to be good candidated to land there as another "core extensions" that are provided by community providers https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/index.html (as @ashb mentioned similar to operator base links, also secret backends, auth etc. ).

Even if the notification "backends" would not require an explicit discovery/registration, it's good to have such a Provider's capability list - if anything for the documentation/discovery (with provider.yaml information the documentation can be easily automated for any new implementation of "notifier".  It's also nice for API/CLI/UI discovery of currently installed capabilllities with providers.

**Comment by BasPH** [comment]
I do think it would be good to have a plan for this one, for example:

- Will we leverage a 3rd party library e.g. [apprise](https://github.com/caronc/apprise)?
- What will the notification abstraction in code look like?
- How will the configuration of each notification system be supported?
- Will notifications be registered in the metastore?
- Will there be any UI changes to view sent notification configuration/sent notifications?
- How will it be part of providers packages

**Comment by ashb** [comment]
> * Will we leverage a 3rd party library e.g. apprise?
> * How will it be part of providers packages

Both of these have the same answer -- yes part of providers, so it doesn't need a "core" decision. So we could have an apache-airflow-providers-apprise that provides a load of notifications, and/or we could have a notification in apache-airflow-providers-slack too.

> What will the notification abstraction in code look like?

It could be as simple as this:

```python
class Notifier(Protocol):
    def __call__(self, **context): -> None
```

i.e. a function that gets called with the TI context.

> * Will notifications be registered in the metastore?

The notifications for a TI: they will exist in the serialized_dag table, but I don't think a "notifications" table or anything like that.
All the possible notification classes: no, not in the metastore.

> * Will there be any UI changes to view sent notification configuration/sent notifications?

Configuration should use existing Connections mechanism, so no on that front.
Sent notifications: possibly, but that isn't needed in the first version I don't think. At least not in a general case. (I can see that being useful if we have a HTTP Webhook notification to debug issues, much like how GitHub has for apps - you can see recent deliveries and the responses etc.)

**Comment by potiuk** [comment]
+1 on everything @ashb wrote with some update. I thought about using some existing APIs (a'la open-telemetry) but it add 0 value in our case and I agree with @ashb that simple interface where we simply notify with context is enough - with one caveat -we also need to pass "what" we are notifying about, so likely something like htat:
```
class Notifier(Protocol):
    def __call__(self, type: NotificationType, message: str, **context): -> None
```

**Comment by RosterIn** [comment]
I don't see a way to set email from providers there is only a way to configure it from airflow.cfg

**Comment by potiuk** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html?highlight=email -> email is configured both in config and in connection (and in email provider you can just use connection and send emails directly).

**Comment by RosterIn** [comment]
Thanks for this.
This is very confusing. Why can't email be a provider like all the others? is there a reason for this being such a unique case?

**Comment by potiuk** [comment]
Airlfow uses email to send notifications without involving operator  at all.

But if you have an idea how to change it, feel free it's easy to say that things are wrong, but proposing a better solution is much more difficult and I challenge you to do so.

**Comment by eladkal** [comment]
This is a request I hear quite often and I think it's an important one. This is a crucial part of on-call rounds in many companies.
Adding on top of what is already said. The current callbacks flow have 2 major flaws:
1. If they fail you have no way of knowing (no view/logs that shows callback execution)
2. There is no way to retry/manually control over them. There is no option to rerun a callback (since executing a callback require a worker slot)

**Comment by hterik** [comment]
Is this same as the recent Listener plugin api?
https://airflow.apache.org/docs/apache-airflow/2.5.0/listeners.html
https://github.com/apache/airflow/pull/27113

**Comment by potiuk** [comment]
Agree @hterik. I think this one is a perfect implementaiton of "general/extensible notifier". You can easily write your own plugins and handle it in the way that best integrate with your needs.

Closing is as done in 2.5.0 - unless someone thinks there are some things missing (but even then I would see that as some feature of the listeners to add).

**Comment by ashb** [comment]
The listener interface is very low level and not something DAG authors should use directly. Re-opening this as I think we should still add a general purpose DAG-author-friendly notification system ala https://github.com/apache/airflow/issues/12611#issuecomment-849625657

**Comment by potiuk** [comment]
> The listener interface is very low level and not something DAG authors should use directly. Re-opening this as I think we should still add a general purpose DAG-author-friendly notification system ala [#12611 (comment)](https://github.com/apache/airflow/issues/12611#issuecomment-849625657)

Should you update the description as well @ashb ? 

While (now after reading it) I understand your comment about adding a way for DAG authors to add separate notification, the original issue was only about extending the "system level notifications" on the whole Airlfow level. 

I understand adding more flexible notifications that are controllable in DAG are a good idea, but if you think that's the case - maybe updating the original description of this issue (because I think your comment changed the scope of the original issue quite dramatically). Or ... should it be another issue?

**Comment by potiuk** [comment]
This is why I actually closed the issue - because I read the description of it BTW. It's hard to expect that we will read all the comment changing the scope when we have such an issue :)

**Comment by ashb** [comment]
Where do you get the impression about "system level notifications" from btw? Because I too re-read the original description and didn't that that impression.

**Comment by ashb** [comment]
Ah, do you mean this:

> without adding extra code to the DAGs

I read that as "please don't make me add a whole `on_failure_callback` method that manually calls to SlackHook to send a message`, rather than having to make no changes to DAG file at all.

**Comment by potiuk** [comment]
This is how I read the original issue. Maybe it was more "rooted" in the current way Airlfow has notifications defined (and I lile the idea of changing it in the way you described, but it was really about this:

> Change "[email]" to "[notification]"
> Add "webhook", "gcp_error_reporting" and "aws_cloud_watch" notification methods

I believe this was about 

```
[[email]]
Configuration email backend and whether to send email alerts on retry or failure
```

Also this part:

```
> Also it would be nice to have an extensible way of triggering webhooks for notifying the common enterprise messaging tools like

> Slack
> MS Teams

> We already have the "smtp", "sendgrid".
```

Is about extending those capabilities: https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html

**Comment by potiuk** [comment]
So i read the original request we have as **just** a way to add more options to those (and I think you can do it very well using the listener mechanism and while this was not the original purpose of listeners, they are perfectly valid way of implementing this mechanism by the "operations" people of Airlfow.

**Comment by potiuk** [comment]
It just feels like this original issue had been side-tracked a lot during the discussion (now that I re-read all of it - there was multi-tenancy, DAG notifiers, using apprise and a number of others :) .

I tnink that's a a lot to handle for a single issue :)

**Comment by ashb** [comment]
Oh yeah, you are right, `[email]` def about config. I'll create a new issue! (which if nothing else will make it easier for me to find this issue!
