### ISSUE TITLE
Dynamic Workflows by spinning multiple task Instance during Dag Run

### ISSUE THREAD

**Issue by bhavaniravi** [apache/airflow#12647]
**Description**

Supporting Runtime-Dynamic workflows using multiple task instance during DAG run

**Use case / motivation**

One of the most common requirements that I constantly see repeating in multiple places and forums is to create dynamic task B based on the output of task A.

```
                   |---> Task B.1 -- |
                   |---> Task B.2 -- |
        Task A --- |---> Task B.3 -- |-----> Task C
                   |       ....     |
                   |---> Task B.N --|
```

A specific requirement in the above case is to parallelize data processing while the specification of the task remains the same. Let's the requirement is to 
1. Fetch the n records from the data lake
2. Process `n` records in task B `preprocess_records`
3. Spin up multiple B so that we can parallelize the processing of N records

*Inspiration from Argo* :: https://argoproj.github.io/argo/examples/#loops

**Idea**

With current airflow, there is only one task instance per task during a DAG run. 

How about we provide an API where `Task A` can inject the number of task instances it can spin up for the downstream task.

Should this be a separate operator?

**Related Issues**

https://stackoverflow.com/questions/41517798/proper-way-to-create-dynamic-workflows-in-airflow

**Comment by vidhithakrar** [comment]
I think this is a very important and powerful feature to have in Airflow.

**Comment by hedrickw** [comment]
I was able to do something kinda similar, where Task A creates a yaml file,  Task Group reads yaml file and generates N tasks, Task B takes all inputs from Task Group but having a Type of Operator to do this would be really nice, you also lose UI with my method since tasks are removed depending on N

**Comment by potiuk** [comment]
We already discussed this and yes it is planned - feel free to start discussion about it in the devlist

**Comment by eladkal** [comment]
Closing as already implemented by AIP 42
