### ISSUE TITLE
Constraints behaviour changes in new PIP

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12665]
We have this warning when running the latest PIP, so we have to take a close look what it means to us:

```
pip install 'https://github.com/apache/airflow/archive/master.tar.gz#egg=apache-airflow[devel_ci]' 
--constraint https://raw.githubusercontent.com/apache/airflow/constraints-master/constraints-3.6.txt
DEPRECATION: Constraints are only allowed to take the form of a package 
name and a version specifier. Other forms were originally permitted
as an accident of the implementation, but were undocumented. The new implementation
of the resolver no longer supports these forms. A possible replacement is replacing
the constraint with a requirement.. You can find discussion regarding 
this at https://github.com/pypa/pip/issues/8210.
```

**Description**

**Use case / motivation**

**Related Issues**

**Comment by potiuk** [comment]
cc: @ashb @kaxil @turbaszek . Not sure from the message if this is really the URL form that is not supported, or whether all the constraints should be in the form of name==version. But I will take a closer look soon.

**Comment by ashb** [comment]
Wonder if we can do

```
sphinx-airflow-theme==0.0.1 @ https://github.com/apache/airflow-site/releases/download/v0.0.1/sphinx_airflow_theme-0.0.1-py3-none-any.whl
```

**Comment by potiuk** [comment]
Yep.  I thought it's the new theme. But we can also exclude it from the constraints when we are  preparing the new constraints  by filtering it out.

**Comment by potiuk** [comment]
It's not this. In our case we simply need to use `--requirement` instead of `--constraint` - we have the same result and it is officially supported in PIP.

**Comment by potiuk** [comment]
Actually I think it was this. I have not seen this since I implemented the "@" (it was automatically overwritten before I merged it, so I think this was false-negative). I am provisionally closing it.
