### ISSUE TITLE
S3 Logging feature

### ISSUE THREAD

**Issue by debuggingfuture** [apache/airflow#1267]
# Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet) : 1.7
  Installed: airflow[s3]
# Description of Issue

I wonder is s3 logging tested in 1.7?

I found this commit try to abstract for GCS / S3, but there is no `S3Log` in `logging.py`
https://github.com/airbnb/airflow/commit/773f52feb9f0dcd29161dc7ec41d5ddc7f69f445#diff-948e87b4f8f644b3ad8c7950958df033L806

Also is this configuration (with `extra`) necessary? Seems the documentation will need some update. 
https://github.com/airbnb/airflow/issues/123

Let me know if I'm missing anything, it would be quickly fixed or I can help on PR, cheers
@artwr

**Comment by artwr** [comment]
Nice catch. Actually, this change is not in 1.7, which still uses the old remote s3 log mechanism.

Should be fixed by https://github.com/airbnb/airflow/pull/1268

**Comment by artwr** [comment]
I should add that a PR against the docs would be welcome :)
