### ISSUE TITLE
Create a upgrade check rule to update `[scheduler] max_threads` config

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#12672]
This config was renamed in https://github.com/apache/airflow/pull/12605#discussion_r530305557

The rule should suggest to change config from `[scheduler] max_threads`  to `[scheduler] parsing_processes` in 1.10.14

**Comment by mcepok** [comment]
This should be resolved by #14913 .

**Comment by kaxil** [comment]
closed by #14913
