### ISSUE TITLE
SparkSubmitHook -  allow log parsing

### ISSUE THREAD

**Issue by Athlestan** [apache/airflow#12680]
**Description**

Create a method that will allow developer to parse spark log as needed in SparkSubmitOperator to extract usefull information. Method should be designed to be overwritten.

**Use case / motivation**

I want to extract what business dates my spark application processed/inserted to hive table and pass it to next task in dag. My business logic is in my Spark application written in Scala that I run using Airflow SparkSubmitOperator. 

My idea was to parse spark log in `SparkSubmitOperator` using `SparkSubmitHook` in method `_process_spark_submit_log` looking for specific information that I will log in my spark application. Then I would be able to pass that information using xcom to another task.

**Related Issues**

No.

**Comment by eladkal** [comment]
This feels like a very custom use case for your needs.
You can do that with a custom operator.
