### ISSUE TITLE
Airflow commands should not show sensitive information by default

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#12696]
**Description**

Commands like `airflow info` or `airflow config` should by default show anonymised values.

**Use case / motivation**

Avoid displaying sensitive information by accident.

**Related Issues**

https://github.com/apache/airflow/pull/12689#discussion_r532107720
https://www.bbc.com/news/world-europe-55027641 (Dutch journalist gatecrashes EU defence video conference)

**Comment by turbaszek** [comment]
Opinions? @kaxil @XD-DENG @potiuk @ashb @mik-laj

**Comment by XD-DENG** [comment]
Yep, as mentioned in https://github.com/apache/airflow/pull/12689, I think we should make these information anonymised by default.

BTW I much like the 2nd link you shared above😄 and that was not the only such incident in 2020😄

**Comment by potiuk** [comment]
YES

**Comment by kaxil** [comment]
:D loved the 2nd link. 

I agree with @XD-DENG that we should anonymized sensitive information by default

**Comment by pateash** [comment]
this is already done using --anonymize so should be closed
@turbaszek 
<img width="1220" alt="image" src="https://github.com/apache/airflow/assets/16856802/02a2a8a7-130c-487e-bec7-226acdb7baa3">

vs

<img width="1102" alt="image" src="https://github.com/apache/airflow/assets/16856802/d950f326-ae6e-4c71-be79-e542bc3a8e08">

**Comment by potiuk** [comment]
Agree.
