### ISSUE TITLE
add dagrun_timeout to the DAG Details screen in the UI

### ISSUE THREAD

**Issue by kurtqq** [apache/airflow#12691]
In the Details page the is no indication of the DAG `dagrun_timeout`

**Comment by jyotidhiman0610** [comment]
Can I take this up?

**Comment by XD-DENG** [comment]
Thanks @jyotidhiman0610 . I have merged your PR and marked it for version 2.1

**Comment by jyotidhiman0610** [comment]
Thanks @XD-DENG :)
