### ISSUE TITLE
execution_date issue on version : 1.10.12

### ISSUE THREAD

**Issue by huangfei56** [apache/airflow#12713]
Dear Team,
I got a issue about airflow execution date on version 1.10.12.
I have a job scheduled daily. But the execution date is always **one day gap** between **Last Run in dag list** and **Startedin tree view**. I can not know if the job is run today or not in dag list page...
[dag list](https://github.com/huangfei56/debugpic/blob/main/dag-list.PNG)
[tree view](https://github.com/huangfei56/debugpic/blob/main/tree%20view.png)

**Comment by turbaszek** [comment]
It's not a day gap, it's a gap of ~30 seconds if I'm not mistaken. Airflow uses end of schedule interval. See:
https://lists.apache.org/thread.html/2b12ae265795ff2e655a5161c972f5c7bbe60722a12849a0e2c5c55f%40%3Cdev.airflow.apache.org%3E

> A DAG with a ``schedule_interval`` will execute once per interval. By
> default, the execution of a DAG will occur at the **end** of the
> schedule interval.

**Comment by mrd2242** [comment]
> This fits well the idea of processing "data intervals". If we process data for last hour we need to run DAG at the end of the hour.
@turbaszek This is not intuitive. Generally, if we give a execute date, we expect that job be executed just at that time. It's the programmer's responsibility to ensure any data need by this job being processed before this job start, for example, making the data process job upstream or any other approach.

**Comment by eladkal** [comment]
@mrd2242 Nothing prevents you from having full control over your code. You can process data between `{{ ds }}`  and `{{ next_ds }}` This may not be intuitive which is why there are discussions in the community how to address for example https://github.com/apache/airflow/pull/5787

For now I'm closing this issue as there is no action item here.
Currently this how Airflow works.

**Comment by potiuk** [comment]
Yeah @mrd2242 - if you really strongly feel about it - why don't you join the discussion that @turbaszek pointed out to ? Airflow is a  community-managed project so you can have impact on it. But down voting correct answer which explains reasons why Airflow works like that for the last 7 years is probably not a good way to have impact.

**Comment by mrd2242** [comment]
@potiuk I'm sorry about that down voting. And the link @turbaszek linked is not available, it's a blank page. The pr @eladkal linked is useful but I did not see that before he pointed out. Anyway, sorry for that.

**Comment by eladkal** [comment]
@mrd2242 the link opens for me. Give it a few moments it takes time to open it's a long thread.
