### ISSUE TITLE
Error with installing airflow - ERROR: No matching distribution found for cattrs==1.1.1 

### ISSUE THREAD

**Issue by rd16395p** [apache/airflow#12711]
**Apache Airflow version**: Can't Install 

**Environment**: 

- **Cloud provider or hardware configuration**: Desktop Computer
- **OS** (e.g. from /etc/os-release): Windows
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: Anaconda using the command line arg from the README.md file
- **Others**:

**What happened**:

ERROR: Could not find a version that satisfies the requirement cattrs==1.1.1 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-1.10.13/constraints-3.7.txt (line 81)) (from versions: 0.5.0, 0.6.0, 0.7.0, 0.8.0.dev0, 0.8.0, 0.8.1, 0.9.0, 0.9.2, 1.0.0rc0, 1.0.0, 1.1.0)
ERROR: No matching distribution found for cattrs==1.1.1 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-1.10.13/constraints-3.7.txt (line 81))

**What you expected to happen**:

Install airflow.

**How to reproduce it**:
Install the airflow package using the command in the README.md file. 

pip install apache-airflow==1.10.13 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.13/constraints-3.7.txt"

**Comment by dimon222** [comment]
I noticed this on python 3.6, but it makes sense, this library is compatible with python 3.7+ beginning with 1.1.1 release. Confirm your python version.

**Comment by potiuk** [comment]
@dimon222 is right - you need to use the right python version in the constraints URL.

**Comment by ashb** [comment]
Closing -- this appears to be a problem with using the 3.7 constraints file with python 3.6
