### ISSUE TITLE
No Support for special Characters in Passwords for get_uri() method in DbApiHook 

### ISSUE THREAD

**Issue by NadimYounes** [apache/airflow#12722]
Hello,

I have recently noticed that a lot of connections with certain special characters don't work with SqlAlchemy as it requires the passwords to be [urlencoded when they contain special characters](https://stackoverflow.com/questions/1423804/writing-a-connection-string-when-password-contains-special-characters). 

Would there be any impact to changing the code at line 81 to urlencode the password like `urllib.parse.quote_plus(conn.password)` to prevent login failures for special characters? 

https://github.com/apache/airflow/blob/dee304b222d355b03794aa063f39e3ee13997730/airflow/hooks/dbapi_hook.py#L72-L88

I initially caught this issue while using the OdbcHook method found here. https://github.com/apache/airflow/blob/dee304b222d355b03794aa063f39e3ee13997730/airflow/providers/odbc/hooks/odbc.py#L198-L204

Happy to create a feature request, I just want to confirm that this issue makes sense.

**Comment by mik-laj** [comment]
> Happy to create a feature request, I just want to confirm that this issue makes sense.

Go ahead. It makes a lot of sense.

**Comment by alokshenoy** [comment]
Experience this last night while testing something. If it's still unassigned, I'd like to take this up.

**Comment by mik-laj** [comment]
@alokshenoy I assigned you to this ticket 🐈‍⬛ 🐈

**Comment by NadimYounes** [comment]
@alokshenoy please go for it, I am super busy the next few weeks, thanks for taking this up. @alokshenoy can you please tag me on the PR or ticket so I can just follow it? 

Thanks
