### ISSUE TITLE
Add classic operator in TaskFlow API tutorial

### ISSUE THREAD

**Issue by casassg** [apache/airflow#12726]
**Description**

TaskFlow API tutorial should add an example to use a classic operator (example: EmailOperator) so that users know that it can be leveraged. 

Alternatively, it should add references to how to add dependencies (implicit or explicit) to classic operators.

**Use case / motivation**

It's not super clear how can TaskFlow API be used with existing operators (aka PostgresOperator, EmailOperator...). Adding an example, will facilitate users to get a picture of what can be done with this.

**Comment by anilkulkarni87** [comment]
@casassg 
Here is an example I have created and this dag implements taskgroup, taskflow with classic operators. Please take a look:
[Postgres DAG with Taskgroup and Taskflow](https://github.com/anilkulkarni87/airflow-docker/blob/master/dags/postgres_taskgroup.py)

Here is how the dependency looks like on UI:
![image](https://user-images.githubusercontent.com/10644132/107204541-a13a1c00-69b1-11eb-9139-7827e360ec67.png)

**Comment by casassg** [comment]
This is good. I think the example should include using `.outputs` though (aka implicit dependencies for traditional operators).

**Comment by josh-fell** [comment]
@vikramkoka @casassg Is this type of example still desired? I can help contribute if it is.

**Comment by josh-fell** [comment]
@eladkal #19214 was merged earlier. I believe if this issue can be closed if you agree.

**Comment by josh-fell** [comment]
Does anyone else agree that this can be closed now via existing docs + merging of #19124?

**Comment by potiuk** [comment]
Fine for me.
