### ISSUE TITLE
Encountered an error "mysql: [ERROR] mysql: Empty value for'port' specified." using airflow db shell in breeze

### ISSUE THREAD

**Issue by Nick-0723** [apache/airflow#12739]
**Apache Airflow version**:  2.0.0b3

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: 

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):  Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux ace72a077a8c 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
- **Install tools**: ./breeze --backend mysql --integration redis --db-reset
- **Others**:

**What happened**: Encountered an error "mysql: [ERROR] mysql: Empty value for'port' specified." using airflow db shell in breeze。 An error will be encountered when the port is not set in sql_alchemy_conn. Like the default value "mysql://root@mysql/airflow?charset=utf8mb4"

**What you expected to happen**: The default port should be used in db_command

**How to reproduce it**: use './breeze --backend mysql --integration redis --db-reset' ,and then run 'airflow db shell'

**Anything else we need to know**:

**Comment by vikramkoka** [comment]
@Nick-0723 Just check if this issue is resolved with your PR? 
Wanted to close this issue, but wanted to make sure first.
