### ISSUE TITLE
Log task errors into slack 

### ISSUE THREAD

**Issue by garaujodealmeida** [apache/airflow#1273]
# Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet) : 1.7
- Python Version: 2.7
# Description of Issue

I am trying to log airflow task errors into slack. What is the best way to do this? 
## Reproduction Steps
1. Task error/failed
2. Send a message to slack with this task infos

Thanks.

**Comment by dgies** [comment]
I create a method to serve as a callback for my tasks and in that method I use something like

```
def notify_failed(context)
    slack_api_params = { your params }
    slack_message = "your Jinja template message"
    slack_api_params['text'] = context['task'].render_template(slack_message, context)
    SlackClient.api_call('chat.postMessage', **slack_api_params)
```

Then make your tasks like this
`task = DummyOperator('d', provide_context=True, on_failure_callback = notify_failed)`

**Comment by bolkedebruin** [comment]
It is probably better to ask this question on the mailinglist if not resolved yet.
