### ISSUE TITLE
Task level documentation in other place than Task Details

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#12750]
Right now you can add documentation to a task and it will be seen on the task instance details page

![Captura de pantalla 2020-12-02 a las 3 00 19](https://user-images.githubusercontent.com/11339132/100818477-85167d80-344a-11eb-9b44-2a0dbef721e8.png)

It will we nice to have it here (maybe not mandatorily, but optionally):

![Captura de pantalla 2020-12-02 a las 3 01 17](https://user-images.githubusercontent.com/11339132/100818544-a7100000-344a-11eb-991b-e9bbb5e5febc.png)

**Comment by bbovenzi** [comment]
Great idea. We need to improve the UX of the task instance action modal. Including documentation would be a good thing to add. It should probably appear as a collapsed field by default to not make the modal too loud and distracting.
