### ISSUE TITLE
Helm Chart: Provide option to specify loadBalancerIP in webserver service

### ISSUE THREAD

**Issue by cheunhong** [apache/airflow#12751]
**Description**
The current service type for `webserver` is defaulted at `ClusterIP`.
I am able to change it to `LoadBalancer` type, but the I was not able to specify the static IP.
So every time we reinstall the chart, it will change the assigned IP of the loadbalancer being provisioned to us.

**Use case / motivation**

**Related Issues**

**Comment by jedcunningham** [comment]
Hi @cheunhong, to clarify you're looking to set `loadBalancerIP`, right?

**Comment by cheunhong** [comment]
hi @jedcunningham, yes.
