### ISSUE TITLE
Update source_code field of dag_code table to MEDIUMTEXT

### ISSUE THREAD

**Issue by rmanvar** [apache/airflow#12776]
**Description**

Update source_code field of dag_code table to MEDIUMTEXT

**Use case / motivation**

Lot of dags exceed the limit of 65K characters limit giving error `"Data too long for column 'source_code' at row 1"` when enabling webserver to fetch dag_code from db. 

**Related Issues**

**Comment by ashb** [comment]
What is the current column type?

This only applies to mysql, not other DBs I think

**Comment by rmanvar-indeed** [comment]
Currently it's TEXT which has limit of 65K characters. MEDIUMTEXT will have 16777K characters limit. 

yup was primarily aiming for sql, haven't use Airflow with other databases so need to explore them to be sure. 

I tried updating column type from TEXT to MEDIUMTEXT of a running db and airflow setup and sql updated it without re-creating table and no errors in Airflow logs as well. ( Tho not many dags were running in the setup, will do a re-test to be sure )

**Comment by rmanvar-indeed** [comment]
Do the migration files at https://github.com/apache/airflow/tree/master/airflow/migrations/versions include non-sql databases too? How can we apply only for sql if so

**Comment by ashb** [comment]
Again -- this is only a problem for MySQL -- PostgreSQL's TEXT type can store 4gb 

https://www.postgresql.org/docs/13/datatype-character.html

So your migration only needs to change it for MySQL.

**Comment by potiuk** [comment]
I think this shoudl be solved for 2.0 (marked is as such) @rmanvar-indeed  - do you plan to contribute fix for that back to Airlfow?

**Comment by rmanvar-indeed** [comment]
Yup, planning to create a MR for the fix. Might take few days tho as I don't have the airflow dev setup.

**Comment by rmanvar-indeed** [comment]
Awesome. Thanks :smile:  will take a look.

**Comment by rmanvar-indeed** [comment]
Is it possible to add this update for previous / upcoming versions of Airflow like 1.10.12 and 1.10.13 ?

**Comment by potiuk** [comment]
We are just about to release 1.10.14 (this morning) so not very likely - maybe 1.10.15 if we have one

**Comment by potiuk** [comment]
But we are releasing 2.0rc next week and hopefully final 2.0 version  after that, and if you are considering running Airflow in PROD we HIGHLY recommend migrating to 2.0. And for that one - it will happen not sooner than Tuesday!

**Comment by potiuk** [comment]
If you have any questions/etc. you can always ask me on airflow's slack (we have #breeze channel there)

**Comment by potiuk** [comment]
HEy @rmanvar-indeed - did you have a chance to work on it?

**Comment by rmanvar-indeed** [comment]
Thank for the MR!
I had written the alembic migrations, but couldn't figure a good way to add tests. 
Easiest way seemed to add a big dag exceeding 65Kb limit in example dags but that didn't seem ideal. 
Tried adding test case in test_dagcode on the lines of: 
```
    def test_storing_large_dag_file_in_db(self):
        """Test if large dag exceeding 65Kb size can be added to db"""
        with TemporaryDirectory(prefix='airflow_dagcode_dir') as tmp_dir:
            with NamedTemporaryFile(dir=tmp_dir, mode='w', suffix='.py') as f:
                f.write(get_large_test_dag())
                f.flush()
                f.close()

                import os
                os.listdir(tmp_dir)
                dag_bag = DagBag(tmp_dir)

                for dag in dag_bag.dags.values():
                    DagCode(dag.fileloc, get_large_test_dag()).sync_to_db()
                    dag.sync_to_db()

```
but this wasn't writing dag code to db as I had expected.
