### ISSUE TITLE
Error in wheel metadata (requirements)

### ISSUE THREAD

**Issue by DavHau** [apache/airflow#12789]
Hello, I think your wheels metadata is corrupt.
If you download the .whl file of a [current release](https://pypi.org/project/apache-airflow/#files), extract it via zip and check the file `*dist-info/METADATA`, you will see the following line:
```
Requires-Dist: azure-datalake-store (>=0.045azure-mgmt-datalake-store>=0.5.0); extra == 'all')
```

This seems invalid. Pip accepts this for some reason.
It installs `azure-datalake-store`, but not `azure-mgmt-datalake-store`.
This confirms my assumption, that this is a violation of the format and just for some lucky coincidence pip doesn't crash on it.

I'm maintaining [mach-nix](https://github.com/DavHau/mach-nix). An alternative package management solution for python focused on reproducibility. My implementation had trouble parsing this, which is what led me here.

In case I'm wrong about it being invalid, it would be nice if you could point me to the PEP which allows for such a requirement specification.

**Comment by potiuk** [comment]
Yeah. Confirmed. You managed to open the issue just it in time to put our 1.10.14 release on hold to fix it !

**Comment by potiuk** [comment]
That was fast ;) . Expect this fixed in 1.10.14

**Comment by kaxil** [comment]
Thanks for reporting @DavHau just in time for 1.10.14rc1 and @potiuk for the fix

**Comment by DavHau** [comment]
Thanks for this very quick fix. Are you guys planning on fixing the metadata for old releases by re-uploading them?

**Comment by potiuk** [comment]
There is no way. PIP releases are immutable.

**Comment by potiuk** [comment]
We can at most "yank" them if there are serious issues, but this is very far from being serious enough as this is only single extra that is wrong
