### ISSUE TITLE
Using the SSHExecuteOperator with a custom port fails

### ISSUE THREAD

**Issue by mtoma** [apache/airflow#1279]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet) : current git head
- Example code to reproduce the bug (as a code snippet in markdown)
  Change or set the port of a SSH connection

Now that you know a little about me, let me tell you about the issue I am having:
# Description of Issue

It is impossible to use a SSH connection with a custom ssh port with the SSHExecuteOperator
## Reproduction Steps
1. Set a ssh port for a connection
2. Run a task using that ssh connection in a SSHExecuteOperator
3. {models.py:1155} ERROR - execv() arg 2 must contain only strings

**Comment by bolkedebruin** [comment]
Fixed in master.
