### ISSUE TITLE
Can get execution_date reference when create the Operator?

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#128]
My SQLs statement depend on the execution_date. However, I do not how to get the execution_date reference when create the operators.

Thanks

**Comment by artwr** [comment]
Would this work for you?

```
select *
FROM table
where creation_date = '{{ ds }}'
```

You can check the rendering of templates by using `airlfow test` or in the rendered task view.

**Comment by griffinqiu** [comment]
I mean, I want to get the execution_date during operators.
Like I just want to update the data which is 2015-06-01 when I backfill 2015-06-01 data at 2015-07-14

**Comment by griffinqiu** [comment]
I have found the answer. I can use the Macros {{ ds }}.

Thank you
