### ISSUE TITLE
add default weight_rule to airflow.cfg

### ISSUE THREAD

**Issue by honarkhah** [apache/airflow#12807]
**Description**

It would be nice if the weight_rule default value could be managed by a global config

suggested config:
```
# Weighting method used for the effective total priority weight of the task. 
# Options are: { downstream | upstream | absolute } default is
default_weight_rule = downstream
```
**Use case / motivation**

In some pipeline, you really need to have absolute weight, and then you have to add a line in each task definition which is annoying

**Comment by eladkal** [comment]
>In some pipeline, you really need to have absolute weight, and then you have to add a line in each task definition which is annoying

Why not define it once in `default_args`?

**Comment by honarkhah** [comment]
Then it needs to be done in each dag, right?

**Comment by eladkal** [comment]
> Then it needs to be done in each dag, right?

Yes

**Comment by honarkhah** [comment]
Guess that is the point of issue!

**Comment by eladkal** [comment]
> Guess that is the point of issue!
You described that you want to avoid specifying the same value of `weight_rule` per task.
For that you can define it once in `default_args`.

Though it's not exactly what you are describing maybe [task policy](https://airflow.apache.org/docs/apache-airflow/stable/concepts.html#task-level-cluster-policy) can solve some of it.

**Comment by honarkhah** [comment]
I really think having that one configurable for entire cluster could be
helpful!

**Comment by honarkhah** [comment]
thanks for this feature ;)
