### ISSUE TITLE
Task exited with return code Negsignal.SIGABRT

### ISSUE THREAD

**Issue by MarlonAbeykoon** [apache/airflow#12808]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:

- **Cloud provider or hardware configuration**: hardware 2.5 GHz Quad-Core Intel Core i7 16 GB
- **OS** (e.g. from /etc/os-release): macOS Catelina 10.15.7 (19H15)
- **Kernel** (e.g. `uname -a`): 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**: Python 3.6.12

**What happened**:
When use [this](https://github.com/simple-salesforce/simple-salesforce) library via an operator, I get this error 
`{local_task_job.py:102} INFO - Task exited with return code Negsignal.SIGABRT`
which causes the DAG to fail.
The exact line that happens this is [here](https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/login.py#L200) when it tries to make an HTTP request.
BUT this works fine when I test the task using the command `airflow test salesforce_sync salesforceSync 2020-02-28`
issue only arises when it's executed in airflow via scheduler. The webserver also prints the following error.
```
objc[3861]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[3861]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**What you expected to happen**:

This should work as it works when I check the task using `test` command without the return code `Negsignal.SIGABRT` 

**How to reproduce it**:
pip install simple-salesforce==1.10.1

A dag task should call this

```
from simple_salesforce import Salesforce
sf = Salesforce(
            username='email@.example.com',
            password='password',
            security_token='token',
            domain='test'
        )
```

**Anything else we need to know**:
This always happens for the said scenario but not others. Having a try-catch won't work.

**Comment by kaxil** [comment]
This is because of the new update in MacOS.

Check https://airflow.apache.org/blog/airflow-1.10.10/#running-airflow-on-macos

Add the following to your `.bashrc` / `.zshrc`

```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

**Comment by kirillz1** [comment]
@kaxil Hi, the issue 'Task exited with return code Negsignal.SIGABRT' appears with Container-Optimized OS (on K8s cluster) as well. Do you have any solution for that?

**Comment by potiuk** [comment]
> @kaxil Hi, the issue 'Task exited with return code Negsignal.SIGABRT' appears with Airflow 1.10.15 running on Container-Optimized OS (on K8s cluster) as well. The case is for long-running sensor tasks. Do you have any solution for that?

It might be completely unrelated. The same message does not mean that this is the same circumstances or even the same root cause. I think if you have such problem @kirillz1, you need to gather all the evidences (logs, circumstances, docker file, describe when it happens, what your deployment is etc. and open a new issue -  definitely a more elaborated description of your problem is needed.
