### ISSUE TITLE
Add default conf to DAG definition to use in scheduled runs

### ISSUE THREAD

**Issue by vxtals** [apache/airflow#12817]
**Description**

When you trigger a DAG run through trigger operator, API or cli you can add parameters as "conf", so you can access them by template interpolation like {{ dag_run.conf['conf1'] }}

If you define a DAG relying on this it never will work when it is executed at schedule time.

**Use case / motivation**

Add a default conf parameter in Dag class so it will be used when create_dagrun is called without a conf defined, as it happens when called by scheduler.

**Related Issues**

I couldn't find any issue related.

**Comment by ashb** [comment]
cc @msumit -- perhaps we should think about deprecating/merging params and dagrun.conf in the template -- not sure there is real value in having both.

**Comment by eladkal** [comment]
You can use Params https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html
