### ISSUE TITLE
DAG callback handling not working properly on simultaneous executions

### ISSUE THREAD

**Issue by vxtals** [apache/airflow#12823]
**Apache Airflow version**:

apache-airflow 2.0.0b3

**Environment**:

Any environment

**What happened**:

I have dags triggered at same time for several other Dags through TriggerDagRunOperator (let's say this dags have a minute schedule). Then, on_success_callback is not triggered for some of this dags.

**What you expected to happen**:

Airflow is working pretty fast and sometimes executions_date for these dags is in the same second, so the execution_date stored in the DB is the same, when it calls _execute_dag_callbacks in scheduler_job.py and retrieve DagRun using this date the dag is not the right one.

**How to reproduce it**:

Create a dag with any task triggered by two other dags with the same schedule, every minute or every 5 minutes will be the faster way of testing.

I'm attaching a file with the 3 dags on it as txt

[multi_trigger.txt](https://github.com/apache/airflow/files/5645616/multi_trigger.txt)

, starting them and waiting to any two consecutive executions with the same execution_date and checking scheduler logs should be enough to reproduce it.

**Anything else we need to know**:

It doesn't happen in every execution but happens often, and I guess it's more likely with a better machine.

**Comment by vxtals** [comment]
I'm gonna ping this issue...

Could someone confirm if I'm right about this weird behavior? I'm experiencing other problems related to this, for example, macro {{ dag_run.id }} will have the same value for two runs at the same time. Going crazy with this...

Thank you.

**Comment by kaxil** [comment]
Does this happen on Airflow 2.0.1 too?

**Comment by cvsekhar** [comment]
This issue is happening in the version
Version: v2.0.0
Git Version:.release:2.0.0+ab5f770bfcd8c690cbe4d0825896325aca0beeca also.

**Comment by eladkal** [comment]
@cvsekhar can you check if it happens in 2.1.0?

**Comment by cvsekhar** [comment]
@eladkal sure, will post update after I upgrade to 2.1.0

**Comment by kaxil** [comment]
Any updates @cvsekhar ?

**Comment by cvsekhar** [comment]
Hi, that works perfect with azurefileshare thank you for the quick fix.
