### ISSUE TITLE
Missing docs about webserver_config.py

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#12827]
Hello,

We are missing documentation on the `webserver_config.py` file. I think it is worth answering the following questions in this guide:
* What is this file?
* What is this file for?
* When and how should you edit this file?

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
@zh0uquan  Can you help with it?

**Comment by AmarEL** [comment]
@mik-laj can you assign it to me, please?
I needed to figure out how to use this config file a few weeks ago, and I think that I can help with some documentation as my first issue =)

**Comment by mik-laj** [comment]
@AmarEL  Assigned 🎄🐈
