### ISSUE TITLE
Airflow server running, nothing appears to be working; what could I be doing wrong?

### ISSUE THREAD

**Issue by apapanico** [apache/airflow#1282]
Hi, Thanks for open sourcing this.  It looks like a really great tool.  I'm exploring it to put together a little prototype demo to show to my group how we can use it.  I've been trying to get a really rudimentary DAG running because none of the examples seemed to work.

Airflow version: 1.7.0
Airflow components and configuration: LocalExecutor, postgres
Running on EC2

What I mean by "nothing appears to be working"?
- `airflow trigger_dag` on any of the examples would create a running manual DAGrun but nothing would happen.  It would just hang and stay running.  I could run the tasks individually and they'd show up as successful but the DAGrun would still be going.
- I scheduled the simple DAG below and it never ran (I tried to schedule it every 15 seconds so I wouldn't have to wait long to see it do something).  `python dags/example.py` did not raise an exception
- backfilling does do something

Since everything appears so simple and I think I get the basic concepts for Airflow, I just don't get how nothing is happening.  I would expect to see the simple DAG below just run and run with Airflow not thinking much of it and I would see the successes show up.  But nothing is happening.

I would greatly appreciate any help to get over this hurdle.

```
# The DAG object; we'll need this to instantiate a DAG
from airflow import DAG

# Operators; we need this to operate!
from airflow.operators import BashOperator

from datetime import datetime, timedelta

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime.now(),
    'email': ['alex.papanicolaou@integral.com'],
    'email_on_failure': True,
    'email_on_retry': True,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    # 'queue': 'bash_queue',
    # 'pool': 'backfill',
    # 'priority_weight': 10,
    # 'end_date': datetime(2016, 1, 1),
}

dag = DAG(
    'hfbm', default_args=default_args, schedule_interval=timedelta(seconds=15))


t1 = BashOperator(
    task_id='hello',
    bash_command='echo "Hello"',
    dag=dag)

t2 = BashOperator(
    task_id='world',
    bash_command='echo "World"',
    retries=3,
    dag=dag)

t2.set_upstream(t1)
```

**Comment by jlowin** [comment]
@apapanico I think you're encountering a common problem having to do with the start date -- Airflow schedules DAGs for the period AFTER the start date, not ON the start date. (For example, the daily run for a DAG on 3/25 actually starts on 3/26). Since your start date is always read as "right now", the scheduler never gets to the "next" period. Try making your start_date `now() + timedelta(days=-1)` and I think it should work.

**Comment by apapanico** [comment]
Ah okay.  Thanks for that suggestion.  I updated that part to `datetime.now() + timedelta(days=-2)`, reset the db, and restarted the server.  Still nothing running though.  Does Airflow wait until the next day to start or should I expect it to kick off immediately?

**Comment by jlowin** [comment]
It should start right away -- I see it running under 1.6.2 and master. Only because you didn't mention it, did you restart your scheduler?

What I'm doing:

```
[put the code in the dags folder]
airflow resetdb -y
airflow webserver
airflow scheduler
```

And I see it start to run after a few seconds.

**Comment by apapanico** [comment]
Oh geez..... I am an idiot.  I was not going `airflow scheduler`.  It's working.  Sorry about this.  Read the docs more closely, Alex.  I thought the whole operation was done through `airflow webserver`.

**Comment by jlowin** [comment]
No worries! I've made the same mistake more times than I should admit. Airflow has a lot of components and it can be confusing to get going, but we want to make it as easy as possible. If there's anything that would have been more helpful to you (like a more concise/explicit explanation of the role of the scheduler vs the webserver), please let us know or consider adding it to the docs yourself!

**Comment by apapanico** [comment]
Well good thing I'm not the only one! Thanks for the help, especially that one little line `airflow scheduler`.

A few thoughts on adding to the docs: (1) I'll look at the tutorial again and see about adding some parts that create the full working example with the server and scheduler running.  (2) As I go and continue to try out Airflow, I will see if I can put together a kind of MWE that might be an example of how one would use it more in practice.
