### ISSUE TITLE
Overflow/scrollbars visible on Firefox on Linux

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12834]
On Firefox on linux the `<body>` tag seems to end up with "spurious" overflow, resulting in both horizontal and vertical scrollbars.

![image](https://user-images.githubusercontent.com/34150/101242585-cb8e0580-36f2-11eb-8ed1-7bf34d0fd1c5.png)

If I set `overflow-x: hidden` then they both disappear.

Something has gotten confused!

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/12923
