### ISSUE TITLE
Scheduler is slowly due to many local log files

### ISSUE THREAD

**Issue by ohadmata** [apache/airflow#12849]
Hi, I have a strange behavior in my production airflow:
The scheduler is VERY slowly, it's takes about five minutes to start a certain task after all of the previous tasks has completed.
After the deletion of the logs files (local logs) it's become super fast.

I searched in the web with no solution, 
All of the slowly-scheduler issues are related to many DAG files and not to many log files.
Why the scheduler is affected by the number of logs?

In addition, I saw about 5k logs directories (each one for a different DAG) while I have only 200 DAGS in my airflow instance.
The airflow shouldn't remove his old logs for deleted dags?

thanks

**Comment by ashb** [comment]
Please try out 2.0.0 -- the number of files should no longer have an impact on the scheduler performance

**Comment by ohadmata** [comment]
@ashb I will try, Thanks!
