### ISSUE TITLE
Find a way to inform our users about deprecated extras

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12851]
There are a number of extras being deprecated in 2.0. Those are marked with "remove in 2.1" comments in 2.0, however users might simply have no clue that this deprecation is happening. 

We should find a way to inform users. 

One of the ways might be a small apache-airflow-deprecated-extra package that will be added automatically as dependencies if someone uses that extra - such package could be a special provider that could register itself in Airflow and print a warning message when Airflow is started. Then we would have to figure out how to uninstall it when not needed and the user installs airflow next time. 

And in Airflow 2.1 we could - rather than removing the extras - increase the version of this package as required and make it fail hard with an appropriate message telling how to replace extras.

Not ideal but maybe it's the way to do it.

**Comment by potiuk** [comment]
@kaxil @ashb @turbaszek @mik-laj WDYT ?

**Comment by ashb** [comment]
Something like this sounds like a good idea. I wonder if we could make it show up in the UI - that's the only "sure fire" way to get it in front of users

**Comment by potiuk** [comment]
> Something like this sounds like a good idea. I wonder if we could make it show up in the UI - that's the only "sure fire" way to get it in front of users

Agree. Fortunately this is not something we desperately need to to do for 2.0. It can be easily added in 2.0.1 or beyond.

**Comment by vikramkoka** [comment]
This seems like a really good idea. I would be in favor of a slow deprecation on this too, something in the order of 2.1 or so.

**Comment by kaxil** [comment]
@uranusjr Any ideas here?

**Comment by potiuk** [comment]
I am afraid we only have a chance to check which extras are used at the moment of installation after `pip install` completes, the fact of using extras is not recorded anywhere I believe. The idea that I had initially about "deprecated-extra" provider, might be about the only way that makes sense (Actually I completely forgot about this idea, only recalled it now by reading it again).

**Comment by uranusjr** [comment]
If the deprecated extras are merged into the main dependency list, they can simply be removed since unrecognised extras are automatically ignored (with a warning). But there's not a good way to express that deprecation if the extra is renamed.

One hack to this would be to introduce various empty `apache-airflow-deprecated-extra-foo` packages, and organise dependencies like this:

```python
foo = ["dependency"]

deprecated_foo = ["dependency", "apache-airflow-deprecated-extra-foo"]
```

And detect the presence of `apache-airflow-deprecated-extra-foo` at runtime (with `importlib.metadata`) to show the deprecation.

**Comment by potiuk** [comment]
Is there a way to print a warning by PyPI at the moment such packge is installed (or even attempted to be installed) @uranusjr rather than by importlib introspection ? Or maybe we could simply start "failing" such installation (for example we could add `apache-airflow-deprecated-extra>1.0.0` but release only 1.0.0 in `PyPI` or something similar ?

**Comment by uranusjr** [comment]
> Is there a way to print a warning by PyPI at the moment such packge is installed

Unfortunately no. Well there's a way to show some warnings by publishing 1.0.0 and yanking it (IIRC pip emits a warning if you're installing a yanked version via `==`), but I'm not sure if the message would be clear or even understandable for users.

> Or maybe we could simply start "failing" such installation

That you can, but personally I'd rather just remove those extras (which would emit a warning on installation).

**Comment by potiuk** [comment]
Sounds like adding a new feature to PIP for that is the best route we can take :P

**Comment by potiuk** [comment]
Closing. Not really needed.
