### ISSUE TITLE
Unable to import Airflow plugins

### ISSUE THREAD

**Issue by bskim45** [apache/airflow#12855]
**Apache Airflow version**:
`1.10.14rc1`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
nop

**Environment**:

- **Cloud provider or hardware configuration**: docker (linux)
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster) (official docker image)
- **Kernel** (e.g. `uname -a`): Linux 5.4.39
- **Install tools**: official docker image with docker-compose
- **Others**:

**What happened**:

Unable to import Airflow plugins.

Here is a bit more context:
```
[2020-12-06 15:33:25,513] {plugins_manager.py:159} ERROR - Failed to import plugin AirflowPrometheus
worker_1     | Traceback (most recent call last):
worker_1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/plugins_manager.py", line 150, in load_entrypoint_plugins
worker_1     |     plugin_obj.__usable_import_name = entry_point.module
worker_1     | AttributeError: 'EntryPoint' object has no attribute 'module'
worker_1     | Traceback (most recent call last):
worker_1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/plugins_manager.py", line 150, in load_entrypoint_plugins
worker_1     |     plugin_obj.__usable_import_name = entry_point.module
worker_1     | AttributeError: 'EntryPoint' object has no attribute 'module'
```

**What you expected to happen**:
Airflow plugins should be loaded without any problem.

**How to reproduce it**:
From official latest docker image:
```
FROM apache/airflow:1.10.13-python3.8
RUN pip install --no-cache-dir --user -U apache-airflow==1.10.14rc1 airflow-exporter==1.3.0
```

**Anything else we need to know**:

I guess it's related to recent changes in apache/airflow#12694. I have little knowledge on `importlib`, but it seems like there's no `module` nor `module_name` in `importlib.metadata.EntryPoint`.

**Comment by kaxil** [comment]
cc @ashb -- Any ideas here?

**Comment by kaxil** [comment]
Oh looks like that might just be an issue with Python 3.8 where `importlib.metadata` does not have `.module` but if you use Python 3.7 which uses `importlib_metadata` that has `.module`

**Comment by ashb** [comment]
OH GAD.

Paging @mjpieters  -- turns out we _do_ need the backported module more often :(

**Comment by potiuk** [comment]
> OH GAD.
> 
> Paging @mjpieters -- turns out we _do_ need the backported module more often :(

I guess it is the same story as with importlib_resources Sounds like rc2 IMHO ?

**Comment by mjpieters** [comment]
The solution is to install the backport on 3.8 too.

**Comment by kaxil** [comment]
Indeed, we need to remove the following line from setup.py:

```
'importlib-metadata~=2.0; python_version<"3.8"',
```

i.e. remove `; python_version<"3.8"` bit 

Time for 1.10.14rc2 :(

**Comment by mjpieters** [comment]
Alternatively: don't use the module and attr attributes and fetch the  values yourself:

```python
match = entrypoint.pattern.match(entrypoint.value)
module, attr = match["module"], match["attr"]
```

This is what those attributes fetch (as property objects).  It's trivially poked in if needed.

**Comment by ashb** [comment]
> Indeed, we need to remove the following line from setup.py:
> 
> ```
> 'importlib-metadata~=2.0; python_version<"3.8"',
> ```
> 
> i.e. remove `; python_version<"3.8"` bit

Little bit more complicated than that -- we should keep it as `<3.9`. But also on 3.8 we need to ensure we import the backport, or add the `module` parameter to the EntryPoint class as Martijn suggests.

 
> Time for 1.10.14rc2 :(

Yes

**Comment by mjpieters** [comment]
> i.e. remove `; python_version<"3.8"` bit 

Not *remove*; update 3.8 to 3.9.

**Comment by kaxil** [comment]
Does 3.9 contain the `.module` parameter though? I know we officially don't support Py3.9 yet with 1.10.14 but do why do we not want to install it for 3.9 ?

**Comment by ashb** [comment]
Yes, 3.9 does contain it https://github.com/python/cpython/blob/3.9/Lib/importlib/metadata.py#L81-L84

**Comment by kaxil** [comment]
Aah ok, Cool 👍 Will create PRs / cherry-picks straigh-away too cut 1.10.14rc2 tonight

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/12859
