### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] "production-deployment.html"

### ISSUE THREAD

**Issue by MrCull** [apache/airflow#12852]
**Apache Airflow version**:
N/A

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:
N/A

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
The link under “Latest docs” gives
Status code [404:NotFound] - Link: https://github.com/apache/airflow/blob/master/docs/production-deployment.html

**What you expected to happen**:
The link should point to an actual file.

The closest name file I could find is “https://github.com/apache/airflow/blob/master/docs/apache-airflow/production-deployment.rst” 
But I was not sure if this is what the link should be pointing to or not(??)

**How to reproduce it**:
Click the link in the main page for this repo

## Install minikube/kind
N/A
**Anything else we need to know**:

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fapache%2fairflow
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=apache

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or long an “Issue”.

**Comment by potiuk** [comment]
Would you be so kind to fix the problem by opening a PR?

**Comment by potiuk** [comment]
ActuallIy I created the PR.

**Comment by MrCull** [comment]
Thanks for the quick action.
As mentioned, with not knowing this repo I was not 100% sure what the correct "fix" was so this is why I didn't submit a PR.
