### ISSUE TITLE
Don't figerprint compiled asset files when `yarn dev` is run

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12865]
When running in `yarn dev` it still fingerprints the output files, so the file name changes when the input does, meaning that the webserver needs to be restarted.

_Originally posted by @ashb in https://github.com/apache/airflow/pull/12837#discussion_r537130298_

Is it possible to configure webpack to not fingerprint files in dev so the names are predictable?

**Comment by ryanahamilton** [comment]
Yeah, we're essentially always running in Production mode and the required webserver restarts are a huge pain. I'm going to dig in see what is needed to get to an ideal dev environment.

**Comment by potiuk** [comment]
Happy to help to make it Breeze friendly

**Comment by ryanahamilton** [comment]
@potiuk thanks! I do imagine we might need a change to the commands within Breeze.

**Comment by potiuk** [comment]
This has been fixed by running the server in `dev` mde when `start-airflow` is used and adding instructions on how to run it in `dev` mode. https://github.com/apache/airflow/blob/5ebd63a31b5bc1974fc8974f137b9fdf0a5f58aa/scripts/in_container/run_tmux_welcome.sh#L24
