### ISSUE TITLE
add Neo4j provider

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#12873]
**Description**

Neo4j is very popular db there was attempt to get it in https://github.com/apache/airflow/pull/6604 hope this could be finished it seems like most of the work is already done (Neo4JHook, Neo4JOperator, docs even tests are written)

**Comment by subkanthi** [comment]
@RosterIn I could take a shot at this, is the plan to use code from #6604 or write everything from scratch?

**Comment by eladkal** [comment]
@subkanthi  assigned to you. You can reuse the work already done if you do so you can set co-author for the commit to save the credit for the original author (References [1](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) [2]( https://medium.com/blackode/creating-co-authored-commits-on-the-command-line-git-305ae2af9f73 ) )

**Comment by subkanthi** [comment]
Created PR https://github.com/apache/airflow/pull/13324
