### ISSUE TITLE
1.10.14rc4 - missing airflow.__main__

### ISSUE THREAD

**Issue by GuillaumeDesforges** [apache/airflow#12888]
https://github.com/apache/airflow/pull/7808 has been done for 2.*, but running

```
python -m airflow
```

on airflow 1.* will fail (e.g. current airflow 1.10.14rc4).

It is required to be launched this way for some environments, or else:

```
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
=================================================================            

Error: No module named 'airflow'
``` 

since gunicorn spawns processes without the proper Python env.

The same kind of issue happens for example for Flask using Nix: https://github.com/NixOS/nixpkgs/issues/33093, where the fix is to use `python -m flask ...`

**Comment by potiuk** [comment]
I do not think this would be a reason for failing the RC4 @kaxil @ashb @mik-laj -> it's been like that forever.

**Comment by GuillaumeDesforges** [comment]
#12889 : which I don't really expect it to be merged, even less to trigger a rc5, but I need it for my work and it would have been too bad not to share it.

**Comment by kaxil** [comment]
Yup we don't intend to support that for 1.10.x -- so that would only work for 2.0
