### ISSUE TITLE
Use DAG context in dag examples

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#12894]
The current code of dag examples is in the form of:
```
dag = DAG(whatever)

task_1 = Operator(task_id='dfsa', 
                               dag=dag)
```

As it is said in the docs (or in some article written by a commiter somewhere) it is better to have:
`with DAG(whatever):
`
I don't have time right now to make the changes

**Comment by jmelot** [comment]
I have some time now, I could work on this.

**Comment by eladkal** [comment]
@jmelot assigned to you
