### ISSUE TITLE
from airflow.operators.python import PythonOperator does not work

### ISSUE THREAD

**Issue by vikramkoka** [apache/airflow#12895]
This is not necessarily a bug in core Airflow, but the upgrade-check scripts recommend this as a solution when the old 1.10.x version of importing the python operator is used. 

So, there is a mismatch between the core Airflow code and the recommendations given in the upgrade check. 

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
This is the change that users need to make just before updating to 2.0 -- because this won't work with any 1.10.x versions

**Comment by ashb** [comment]
Perhaps this needs to be suggested as `try ... except ImportError` approach.

**Comment by ashb** [comment]
DummyOperator falls in to this same boat.

**Comment by dimberman** [comment]
@ashb @kaxil I'm not sure what the issue is since the tradition `from airflow.operators.python_operator` works in 2.0.

This can be fixed post-upgrade.

**Comment by ashb** [comment]
@dimberman Well to start with: the upgrade check command suggests making a change that will break in 1.10.14.

Secondly people will forget after upgrading ;)

**Comment by dimberman** [comment]
@ashb sure we can make it a soft warning but after 2.0 they should get deprecation warnings (@ryanahamilton would be great if we could add UI elements that warn people if a DAG uses deprecated features though don't know if it's too close to release at this point)

**Comment by ashb** [comment]
Kamil has already started working on collecting other classes of DAG warnings for display in the UI -- he's got a WIP PR somewhere.

**Comment by ashb** [comment]
But anyway -- the issue is the upgrade check is suggesting something that would break users dags on 1.10.14, so that check will need updating.

**Comment by ryw** [comment]
In my dags I used this form: `from airflow.operators.python_operator import PythonOperator` which worked in both 1.10 + 2.0, so maybe a decent % of airflow users wouldn't be affected by this

**Comment by kaxil** [comment]
> In my dags I used this form: `from airflow.operators.python_operator import PythonOperator` which worked in both 1.10 + 2.0, so maybe a decent % of airflow users wouldn't be affected by this

That will raise a deprecation warning in 2.0

**Comment by turbaszek** [comment]
Using old path will raise a warning. I think that current suggestion given by airflow upgrade check should be understood as "if you want to make your DAG fully compatible with Airflow 2.0 and limit number of warnings you get change the import path A to import path B". 

I can be wrong, be the check was to help migrate DAGs not to make them 1.10 and 2.0 compatible.

**Comment by mik-laj** [comment]
@turbaszek  It seems to me that we should try to ensure compatibility with Airflow 1.10 and Airflow 2.0 to be possible step by step. We've specially released backport packages to make this possible. Now users can test each integration one by one. Core operators are a different case, as they cannot be installed as a pip package. For this reason, it seems that some minor changes may still be needed.

Earlier thread that covered this topic.
https://github.com/apache/airflow/issues/11178#issuecomment-731043815

I've been working on displaying the warnings in the IU and it's almost done. I can do it tonight.
https://github.com/apache/airflow/pull/11960

**Comment by ashb** [comment]
Yeah -- with the exception of the core operators all the other changes suggested by upgrade-check will work on 1.10.14 and 2.0.0 -- for instance see https://github.com/apache/airflow/pull/12930 where we suggest (1.10.14 -> upgrade check -> fix warnings -> 2.0.0) so we'll need to make it very clear which ones can be done on 1.10.14 and which can't.

**Comment by potiuk** [comment]
> Yeah -- with the exception of the core operators all the other changes suggested by upgrade-check will work on 1.10.14 and 2.0.0 -- for instance see #12930 where we suggest (1.10.14 -> upgrade check -> fix warnings -> 2.0.0) so we'll need to make it very clear which ones can be done on 1.10.14 and which can't.

Or maybe RC5 with those operators added to 1.10.14 ?

**Comment by ashb** [comment]
I'd rather a 1.10.15 if we wanted to do that -- lets get 1.10.14 out already!

**Comment by potiuk** [comment]
Oh yeah!
