### ISSUE TITLE
Upgrade check: Check for spark-default connection

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12918]
Ther was an inconsistency between default connection names found in https://github.com/apache/airflow/pull/12558#discussion_r537895405 and added to UPDATING.md

Spark operator used different defaults: 'spark-default' and 'spark_default'.

In 2.0 this has been changed to be 'spark_default' (following all other connection names).

We likely need an upgrade check to cover that case.

**Comment by potiuk** [comment]
cc: @kaxil @dimberman

**Comment by Dr-Denzy** [comment]
I will like to take over this issue.

**Comment by mik-laj** [comment]
@Dr-Denzy  I assigned you to this ticket.

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/13798
