### ISSUE TITLE
Integration with Grafana Loki 

### ISSUE THREAD

**Issue by sshah90** [apache/airflow#12920]
**Description**

Grafana [Loki](https://grafana.com/oss/loki/) is an emerging Open Source project. Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus. It is designed to be very cost-effective and easy to operate. It does not index the contents of the logs, but rather a set of labels for each log stream.

Currently, Airflow has integration with different stacks (ex. S3, Azure blob) for logging solutions but none of them provide a cloud-agnostic real-time logging platform.

**Use case / motivation**

Create a log handler that pushes task logs to Loki with labels and using the same labels pull logs to Airflow Web UI. 

Loki Loghandler should add these features

- Get real-time log output in the UI
- Centralize all Airflow logging so that logs could be viewed at a "DAG level" (ie. multiple task logs in the same context) using Grafana

**Related Issues**
None

**Comment by sgrzemski** [comment]
That would be great!

**Comment by yoavo-datricks** [comment]
Hi. Any news on this? This integration is very useful these days.

**Comment by potiuk** [comment]
I think if someone wants to contribute, it would be great. Maybe even grafana provider could be developed by Grafana Labs? We have a number of providers developed and controlled by third parties (for example Great Expectations provider https://github.com/great-expectations/airflow-provider-great-expectations ). Happy to help someone from Grafana Labs to do so :).

**Comment by snjypl** [comment]
@potiuk  i have written a provider for grafana loki.  will be great if you can take a look and provide your suggestions when you get a chance. 

 https://github.com/snjypl/airflow-provider-grafana-loki 

@team, everyone's feedback would be greatly appreciated.

**Comment by potiuk** [comment]
NIce. Maybe you can add it as a PR to https://airflow.apache.org/ecosystem/ ? Just click "Suggest a change on this page" and it willl open a PR for you.

**Comment by potiuk** [comment]
Let me close that one then. Integrations do not have to be "Apache community" - this is perfectly ok if people do their own integration and publish them on our Ecosystem page.
