### ISSUE TITLE
Attempting to re-run githib action that failed leads to it being cancelled again.

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12945]
This may only be a problem with the "Build Images" workflow, but if a build of that fails (as it occasionally does due to network glitches) and a committer hits the "Re-run all jobs" button, the workflow will restart, but then almost immediately get cancelled.

This might be an unsolvable problem because of how Github re-runs the actions -- where it leaves the previous steps as "failed" whilst re-running the new ones from the start, so when a Cancel workflows step in a parallel build runs, it notices the "Build PROD images 3.6" is failed, so cancels the whole run, even though the (new) "Cancel workflow run" is still queued.

**Comment by potiuk** [comment]
I tested it and I think it works as expected. The 'immediate' cancel is only in case you try to re-rerun a failed build if there is a newer build for that branch already queued or running. For example if you have 5 merges one after another and you try to re-run the 'master' build 3 commits ago - it will get cancelled immediately if there are newer master commits (and resulting workflow runs). same if someone already pushed a fixup, or rebases to their PR  any older PRs when re-run will get immediately cancelled. 

I think it's a desired behaviour, but happy to discuss if there are cases which we would like to handle differently.

**Comment by ashb** [comment]
This is not the behaviour I've seen when I opened this issue -- re-running the latest "build images" job for a branch/PR it got cancelled. This was for the latest commit on a branch.

**Comment by ashb** [comment]
I'll close this until I notice it happening again.
