### ISSUE TITLE
The scheduler does not appear to be running  

### ISSUE THREAD

**Issue by xsu-git** [apache/airflow#12941]
**Apache Airflow version**:1.10.10

**Environment**:python3.6.5     mysql5.6.50

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):centos7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:  
  When I use the command    “airflow scheduler ”     to monitor the heartbeat is normal. 
  But when changing to the background “airflow scheduler -D”  I got the error .
  i donot know what happened （Using executor LocalExecutor）
  plese help. Thanks a lot.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:always

**Comment by vikramkoka** [comment]
@suxin1995 Can you please give any further information on this? 
It is fairly normal to run the airflow scheduler in the background as a daemon using the "airflow scheduler -D" command.
