### ISSUE TITLE
Document process for creating/setting up docker images for a new version/release stream

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12970]
We have documents about how to create a new release (https://github.com/apache/airflow/blob/master/dev/README_RELEASE_AIRFLOW.md) but that doesn't currently list the steps needed to ensure that docker images for that version is built and published.

We should extend our docs to include this process.

**Comment by potiuk** [comment]
Maybe because it won't be be needed as it should happen automatically. But yeah I will write the procedure to manually run it as well. It is literally running one script
