### ISSUE TITLE
Airflow cluster Policy is not working in 1.10.10

### ISSUE THREAD

**Issue by Gaurang033** [apache/airflow#12972]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Amazone EC2
- **OS** (e.g. from /etc/os-release):
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

- **Kernel** (e.g. `uname -a`): Linux ip-10-164-7-11 4.14.154-99.181.amzn1.x86_64
- **Install tools**:
- **Others**:

**What happened**:
I am trying to setup the cluster policy. However it's not working. This is a very simple code which should fail all the jobs. However, I job gets successful without any exception. 

File is located at **/root/airflow/config/airflow_local_settings.py**

```python
class PolicyError(Exception):
    pass


def cluster_policy(task):
    print("task_instance_mutation_hook")
    raise PolicyError


def task_instance_mutation_hook(ti):
    print("task_instance_mutation_hook")
    raise PolicyError
```

**What you expected to happen**:
If I run job it should fail with PolicyError exception 

Job is successful. 

**How to reproduce it**:
Try to place the above file at mentioned location and run the job. it should fail. 

**Anything else we need to know**:

**Comment by ashb** [comment]
That's because cluster policy wasn't introduced until 1.10.12:

http://airflow.apache.org/docs/apache-airflow/1.10.12/concepts.html#cluster-policies-for-custom-task-checks

**Comment by Gaurang033** [comment]
@ashb yes, I realize that, I upgraded to 1.10.12 and I can say those error messages.

**Comment by turbaszek** [comment]
As far as I'm aware we don't have something like `cluster_policy` we have `policy`:
http://airflow.apache.org/docs/apache-airflow/1.10.12/concepts.html#mutate-tasks-after-dag-loaded
https://github.com/apache/airflow/blob/6416d898060706787861ff8ecbc4363152a35f45/airflow/settings.py#L172-L188


The docs seems to be slightly misleading.
