### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ashb** [apache/airflow#12982]
Once 2.0.0 is out and fully released, we should switch over from `master` to `main` as our default branch, deleting/renaming master.

Rough steps:

- [ ] Check if the ASF GitBox sync needs to know about this
- [ ] Update all CI pipelines that check for `master` #14688
- [ ] Rebase all PRs with an INFRA ticket
- [ ] Update all docs

Thankfully GitHub as done a lot of work to make this transition easier https://github.com/github/renaming/ - we may want to wait for the "auto rename" feature GitHub promised here, or maybe we just do it anyway.

**Comment by potiuk** [comment]
Absolutely!

**Comment by turbaszek** [comment]
You need to fill issue to Apache Infra and that all PRs have to change the base branch. We did this in Apache Kibble:
https://github.com/apache/kibble/issues/45

**Comment by mik-laj** [comment]
Similar: https://github.com/apache/airflow/issues/9351

**Comment by nexterot** [comment]
Useless changes. Better concentrate on sth important

**Comment by ashb** [comment]
Done.
