### ISSUE TITLE
Can airflow synchronize with a CI like jenkins or replace it ?

### ISSUE THREAD

**Issue by afarbos** [apache/airflow#13]

**Comment by mistercrunch** [comment]
Airflow definitely isn't a drop in replacement for Jenkins. I don't know much about Jenkins but I'm sure the two systems can synchronize easily. I'm sure you could easily write a JenkinsTriggerOperator to trigger Jenkins jobs from Airflow, or have a JenkinsSensor operator that would wait for some sort of signal from Jenkins to move along.
