### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by dtheodor** [apache/airflow#130]
Hi,

Are there any plans for explicit support for data quality checks per task, such as result validation and profiling? Right now as far as I can tell a task can either succeed (no crash) or fail (crash), but there's no concept of validating the results.

**Comment by martingrayson** [comment]
Perhaps its not much help, but I've implemented a generic Python function for use within my dags. I use this function to execute check SQL within some of my pipelines and validate the result matches what I expect.

**Comment by mistercrunch** [comment]
You can always run your checks in or outside of your critical path.

We have a very common construct that we've abstracted in a function (in our pipeline repo, not the airflow repo) that returns a subdag containing:
- The task that loads data in to a staging table (HiveOperator)
- A set of data quality checks (PrestoCheckOperator)
- Exchanging the partition to make it live (HiveOperator)

Perhaps you could also use a subdag to run your DQ checks.

AIt'd be easy to create a ChainOperator that would receive a list of task and run them one after the other, and atomically (if one fails, the whole chain fails).
