### ISSUE TITLE
KubernetesExecutor - image from executor_config is ignored

### ISSUE THREAD

**Issue by cris-b** [apache/airflow#13003]
In 1.10.11+ the image used in executor_config is ignored.

in PodGenerator.construct_pod the kube_image is used  as the image when constructing the dynamic_pod.  Then because dynamic pod takes precedence here:

       pod_list = [base_worker_pod, pod_override_object, dynamic_pod]

I cant see how the image could ever be anything but the default worker image.

**Comment by cris-b** [comment]
this is only relevant to 1.10.x, in 2.0 there is this code in construct_pod which stops the problem:

        try:
            image = pod_override_object.spec.containers[0].image  # type: ignore
            if not image:
                image = kube_image
        except Exception:  # pylint: disable=W0703
            image = kube_image

**Comment by marcusianlevine** [comment]
Thanks for reporting this Cris, I'm seeing the same issue

AFAIK this only affects 1.10.13+

I'm currently running Airflow 1.10.12 and the `executor_config` image override works, but when I try to upgrade to 1.10.14 it always uses the image specified in the base config

**Comment by CatarinaSilva** [comment]
Hi, also suffering from this when trying to migrate from 1.10.12 to 1.10.14, I see the PR is already done, is there any idea when it's going to be released? @dimberman

**Comment by kaxil** [comment]
> Hi, also suffering from this when trying to migrate from 1.10.12 to 1.10.14, I see the PR is already done, is there any idea when it's going to be released? @dimberman

Most-likely in a month (or sooner)

**Comment by kaxil** [comment]
Fixed by https://github.com/apache/airflow/pull/13074

**Comment by CatarinaSilva** [comment]
hey @kaxil just wondering if there is already a tentative release date for 1.10.15?

**Comment by kaxil** [comment]
> hey @kaxil just wondering if there is already a tentative release date for 1.10.15?

Planning Early March

**Comment by CatarinaSilva** [comment]
> Planning last week of Feb or Early March

Thanks for the info 👍
