### ISSUE TITLE
unable to open SQLite database file whenever run_as_user set to a different user

### ISSUE THREAD

**Issue by jinyeluo** [apache/airflow#13004]
**Apache Airflow version**:
1.10.12

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Red Hat 7.9
- **Kernel** (e.g. `uname -a`):  Linux hqhddev84 3.10.0-1160.2.2.el7.x86_64
- **Install tools**: pip install
- **Others**:

**What happened**:
Whenever I use 'run_as_user',  the system switches the thread to be on a different user, then not able to update the table with status.
The error happens on a ShortCircuitOperator, which returns a false and have downstreams skipped. 

I also just modified the sample "example_xcom" by adding a " 'run_as_user': 'another_user'", and the error shows up.

```
[2020-12-10 21:25:45,344] {taskinstance.py:1150} ERROR - (sqlite3.OperationalError) unable to open database file
[SQL: UPDATE task_instance SET start_date=?, end_date=?, state=? WHERE task_instance.dag_id = ? AND task_instance.execution_date = ? AND task_instance.task_id IN (?, ?)]
[parameters: ('2020-12-11 02:25:45.342154', '2020-12-11 02:25:45.342154', 'skipped', 'frank_file_sensor_test_v2', '2020-12-11 02:25:18.725891', 'delete_file_op', 'do_something_useful')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/data/work01/venv/airflow_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/data/work01/venv/airflow_venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: unable to open database file
```

**What you expected to happen**:
The python_callable should be executed as the user I defined using "run_as_user". Once finished, the task status is updated successfully.

Whenever I use 'run_as_user',  the system switches the thread to be on a different user, then not able to update the table with status.
The error happens on a ShortCircuitOperator, which returns false and should have the downstreams skipped.

**How to reproduce it**:

The simplest way is to modify the sample "example_xcom" by adding a " 'run_as_user': 'another_user'" to the default args, and the error will show up.

**Comment by ashb** [comment]
This is a "WONTFIX" I'm afraid -- it's a problem with using SQLLite which is not recommended for anything other than simple tests https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html?highlight=sqlite#database-backend

We do have longer term plans that would fix this as a side-effect, but this is a limitation of SQLite and the linux permissions model.
