### ISSUE TITLE
Setting in_cluster to True is failing with invalid kube config 

### ISSUE THREAD

**Issue by sakshi-bansal** [apache/airflow#13006]
Airflow version: 1.10.12

Deploying the example https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/example_dags/example_spark_kubernetes.py and

Added parameter  **in_cluster=True** in the dag. 

Expected Result:
Dag gets executed and spark application is deployed in the local cluster where airflow is deployed

Actual Result:
Error: {taskinstance.py:1150} ERROR - Invalid kube-config file. No configuration found.

Work-around:
Works after manually adding a kube config in the worker pod.

**Comment by sakshi-bansal** [comment]
One possible solution that worked for me:
1. Add in_cluster in the kubernetes_default connection in the extras as **{"extra__kubernetes__in_cluster": "True"}**
2.  Create ClusterRole granting the serviceaccount airflow access to create spark applications

**Comment by jedcunningham** [comment]
`in_cluster` isn't a kwarg for `SparkKubernetesOperator` or `SparkKubernetesOperator`. Putting `extra__kubernetes__in_cluster` in the connection extras is the right way way currently.

That said, `KubernetesPodOperator` does support `in_cluster` making operators in this same provider inconsistent. Makes me wonder if KPO should also use the connection like the hook does? Or, at the very least have `extra__kubernetes__in_cluster` on the default connection? @dimberman, any input?

**Comment by kaxil** [comment]
> `in_cluster` isn't a kwarg for `SparkKubernetesOperator` or `SparkKubernetesSensor`. Putting `extra__kubernetes__in_cluster` in the connection extras is the right way currently.
> 
> That said, `KubernetesPodOperator` does support `in_cluster` making operators in this same provider inconsistent. Makes me wonder if KPO should also use the connection like the hook does? Or, at the very least have `extra__kubernetes__in_cluster` on the default connection? @dimberman, any input?

As long as it is consistent I am happy with either approach.

**Comment by jedcunningham** [comment]
#14954 provides a little more clarity, but we still should make it consistent.

**Comment by Vivekdjango** [comment]
> `in_cluster` isn't a kwarg for `SparkKubernetesOperator` or `SparkKubernetesSensor`. Putting `extra__kubernetes__in_cluster` in the connection extras is the right way currently.
> 
> That said, `KubernetesPodOperator` does support `in_cluster` making operators in this same provider inconsistent. Makes me wonder if KPO should also use the connection like the hook does? Or, at the very least have `extra__kubernetes__in_cluster` on the default connection? @dimberman, any input?

@jedcunningham : I am new to this skill so could you please help me out? Where did you pass 'extra__kubernetes__in_cluster' param? Inside 'SparkKubernetesOperator' or under some yaml file? please reply.

As far I tried to add under 'SparkKubernetesOperator' but didn't work.

**Comment by mik-laj** [comment]
> Where did you pass 'extra__kubernetes__in_cluster' param? 

In connection confiugraitton, see: http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-cncf-kubernetes/latest/connections/kubernetes.html
http://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html

**Comment by Vivekdjango** [comment]
> > Where did you pass 'extra__kubernetes__in_cluster' param?
> 
> In connection confiugraitton, see: http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-cncf-kubernetes/latest/connections/kubernetes.html
> http://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html

Thanks @mik-laj : I created the connection from UI , now how to pass it to 'SparkKubernetesOperator'?

**Comment by mik-laj** [comment]
You should use `*_conn_id` parameter.

**Comment by Vivekdjango** [comment]
@mik-laj : I tried but no luck, I created connection with two ways:

1)Conn_ID: <NAME>
   Type:Kubernetes Cluster Connection
   In Cluster Config: Checked
   Kube config (JSON format): {"extra__kubernetes__in_cluster": "True"}

Error:"Invalid connection configuration. Options extra__kubernetes__kube_config_path, "
                "extra__kubernetes__kube_config, extra__kubernetes__in_cluster are mutually exclusive. "
                "You can only use one option at a time."

2)Conn_ID: <NAME>
   Type:Kubernetes Cluster Connection
   Kube config (JSON format): {"extra__kubernetes__in_cluster": "True"}

Error: Invalid kube-config file. No configuration found.

Could you please guide where I am doing wrong?

**Comment by mik-laj** [comment]
Kube config field should be empty. In Cluster Config should be checked

**Comment by Vivekdjango** [comment]
Your help is really appreciable. Thanks for all your guidance it resolved the issue. @mik-laj
