### ISSUE TITLE
Hook BigQuery: update table not working. 

### ISSUE THREAD

**Issue by owlphi** [apache/airflow#13011]
# Problem

I am trying to update my table using the bigquery hook. 

bq_hook.update_table(...)

However I got this message: 
```
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

# Solution

In the update_table method

I have modified the line https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/hooks/bigquery.py#L717
from : 
`table_object = self.get_client().update_table(table=table, fields=fields)`
to:
 `table_object = self.get_client(project_id=project_id).update_table(table=table, fields=fields)`

It seems working.

**Comment by turbaszek** [comment]
@owlphi would you mind opening a PR?

**Comment by owlphi** [comment]
Hi @turbaszek, I have created the PR: https://github.com/apache/airflow/pull/13018.
