### ISSUE TITLE
On the page with dag runs, conf values should be double quoted, not single quoted

### ISSUE THREAD

**Issue by Hohol** [apache/airflow#13014]
![image](https://user-images.githubusercontent.com/2988117/101913462-76fbf600-3bdc-11eb-8634-3dd0aaca6c94.png)
I often want to rerun dag with the same or slightly tweaked conf parameters. So I copy the conf JSON from this page and trigger the dag with it. Except... it's not actually JSON, because it uses single quotes instead of double quotes. This results in "invalid JSON configuration" error.
Is there some reason for using single quotes here? Can it be changed to double quotes?
UPD: Airflow version I use is  `1.10.12`

**Comment by ashb** [comment]
Simply because that is showing the Python representation, not JSON.

Given the input is forced to be valid JSON we should show JSON in the output! Would you like to try a PR to fix this? We can help you through the process.

**Comment by Hohol** [comment]
No, I'm too busy :smile:. Let's hope for another volunteer.

**Comment by alxdembo** [comment]
@ashb I would like to volunteer

**Comment by ashb** [comment]
@alxdembo Great! Do you need any help or pointers with this?

**Comment by alxdembo** [comment]
Thanks! Will use documentation and Slack if any.

**Comment by alxdembo** [comment]
@Hohol which version is it? Don't see Conf column in 1.10 anymore

**Comment by Hohol** [comment]
@alxdembo it's `1.10.12`

**Comment by ashb** [comment]
@alxdembo please make all PRs target master (which is where 2.0 is about to be released from)

**Comment by alxdembo** [comment]
@ashb in master/2.0 it seem to be ok:

![image](https://user-images.githubusercontent.com/34896613/102028179-b07d5e80-3da0-11eb-9344-b278c8f0d6db.png)

for v1-10 I can add a formatter for conf column in www_rbac/views.py

**Comment by ashb** [comment]
Ah if it's already shown right on 2.0/main branch then there is nothing to do -- we are only making critical fixes to 1.10 now.
