### ISSUE TITLE
Airflow web page show delete dag

### ISSUE THREAD

**Issue by basebase** [apache/airflow#1302]
Dear Airflow Maintainers,

I Run Ariflow DAG, however I rm -r dag_dir and clear task data
airflow web page still show dag 
Whether there cache
I how clear cache
Thanks!

**Comment by basebase** [comment]
@jlowin My Delete this DAG stay Mysql  relevant data

**Comment by jlowin** [comment]
At the moment there is no way to delete a single DAG, I think. You can reset your entire database (all dags) with `airflow resetdb`

**Comment by jlowin** [comment]
See also #1314
