### ISSUE TITLE
add an  "import" `[-i FILEPATH]` to `airflow connections` cli command

### ISSUE THREAD

**Issue by andres-lowrie** [apache/airflow#13034]
**Description**

This would allow users to create a bunch of connections at once from a file.

**Use case / motivation**

I think having some parody between the _connections_ and _variables_ commands could be beneficial and provide a more pleasant UX for cli users.

For example when I did `airflow connections -h` and didn't see a `-i` it felt weird seeing as how this is possible for variables.

So I was left feeling a little confused; I was _expecting_ it to be there

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/9855
