### ISSUE TITLE
Task Group: Node order changes after collapse

### ISSUE THREAD

**Issue by JCoder01** [apache/airflow#13044]
**Apache Airflow version**: 2.0.0rc1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The order of the nodes changes when expanding and collapsing task groups:
Before:
![image](https://user-images.githubusercontent.com/651639/102012250-44a2e380-3d17-11eb-936a-c62dfa9c6e6b.png)

After expanding task group and collapsing:
![image](https://user-images.githubusercontent.com/651639/102012285-82077100-3d17-11eb-9da7-c94c98a9a0cb.png)

**What you expected to happen**:
node order to be consistent
**How to reproduce it**:

Create a DAG with multiple task groups.
expand the top group
collapse the top group
observe is is now at the end.

**Anything else we need to know**:

happens every time.

**Comment by turbaszek** [comment]
CC @yuqian90

**Comment by turbaszek** [comment]
Thanks @JCoder01, as I understand this is not a "real bug" but just an unpleasant UX, right?

**Comment by JCoder01** [comment]
@turbaszek Yeah, there is nothing wrong with the functionality. It's just a tad annoying when things move around.

**Comment by yuqian90** [comment]
> @turbaszek Yeah, there is nothing wrong with the functionality. It's just a tad annoying when things move around.

In fact, this isn't an issue for ``TaskGroup`` specifically. Even before ``TaskGroup`` was introduced, simply refreshing the page can sometimes render the Graph View differently causing the nodes to shuffle around. 

I can understand the pain. However, this issue needs to be addressed in the dependent package Dagre. I think this is the open issue upstream: https://github.com/dagrejs/dagre/issues/189

Unfortunately it doesn't look like they are addressing it any time soon. Hopefully someone can come up with a workaround.

**Comment by ashb** [comment]
Could some test this on Rc3 -- I don't see it there.

If you do see it, please give me a reproduction test case.

**Comment by JCoder01** [comment]
@ashb Just installed RC3 and see the same. The behavior is evident on that example_task_group dag.
Before
![image](https://user-images.githubusercontent.com/651639/102240811-42cb5280-3ec6-11eb-902b-01683ee22924.png)
After
![image](https://user-images.githubusercontent.com/651639/102240851-52e33200-3ec6-11eb-8866-d020c821251d.png)

**Comment by ashb** [comment]
I wonder if I don't see it cos I use Firefox

**Comment by JCoder01** [comment]
I don't know, I tried Firefox on both windows and linux and the same thing happens.

**Comment by eladkal** [comment]
I was able to reproduce using the `example_task_group` DAG :

![reproduce](https://user-images.githubusercontent.com/45845474/102336851-695abd80-3f9a-11eb-8ce9-cfd6c60ce624.gif)

**Comment by kaxil** [comment]
@bbovenzi Can you take a look at this one when you have time please

**Comment by bbovenzi** [comment]
dagre still has not been updated. If someone wants to fork that library or add logic to remember the order, feel free to open a PR. But I will not be focusing on this as we will use a different graphing library in AIP-38.

**Comment by yuqian90** [comment]
Hi @bbovenzi , just curious, what graphing library are we switching to in AIP-38? I think it makes sense to start thinking about how to implement Graph View and Tree View using that new library.

**Comment by bbovenzi** [comment]
@yuqian90 I'm still looking into it, so I'm open to suggestions. We can certainly bring those updates into the current UI when it's well tested.

**Comment by bbovenzi** [comment]
Just tested again in the new graph view. Group children appear to maintain their order.
