### ISSUE TITLE
CLI does not display TaskGroups

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13053]
Hello,

Airflow ability to [display DAG in CLI](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/usage-cli.html#display-dags-structure) with command `airflow dags show`, but unfortunately this command does not display Task Groups. It would be great if the Task Groups were correctly marked in the diagrams.

<img width="1268" alt="Screenshot 2020-12-14 at 02 28 58" src="https://user-images.githubusercontent.com/12058428/102030893-9f3e4d00-3db4-11eb-8c2d-f33e38d01997.png">
<img width="681" alt="Screenshot 2020-12-14 at 02 29 16" src="https://user-images.githubusercontent.com/12058428/102030898-a2d1d400-3db4-11eb-9b31-0cde70fea675.png">

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
@yuqian90 Can you help with it?

**Comment by yuqian90** [comment]
Thanks for reporting. @mik-laj I'll work on it.

**Comment by mik-laj** [comment]
@yuqian90  Do you need help?

**Comment by yuqian90** [comment]
> @yuqian90 Do you need help?

Sorry haven't got to this yet, but will get to it in the next few days.
