### ISSUE TITLE
Rewrite handwritten argument parser in prepare_provider_packages.py

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13069]
Hello @potiuk 

I believe you wrote this script - [`prepare_provider_packages.py`](https://github.com/apache/airflow/blob/master/dev/provider_packages/prepare_provider_packages.py).

I am wondering if there is any reason why you did not use the standard library - [`argument.ArgumentParser`](https://docs.python.org/3/library/argparse.html) in this script?
https://docs.python.org/3/library/argparse.html
https://github.com/apache/airflow/blob/550395192929f86376151b4385cea6b8dfb76e8e/dev/provider_packages/prepare_provider_packages.py#L1518-L1552

This makes the code overly complex and, by the way, more prone to errors e.g.  ``usage()`` method describes the `--version-suffix-for-pypi` parameter, but we changed its name to `--version-suffix`.

What do you think to rewrite this script to use the standard library? Do we have a requirement that prevents this? I think of something similar to [my gist](https://gist.github.com/mik-laj/ff008718fc6cec9fe929731b8c62d6f8).

**Comment by potiuk** [comment]
Feel free to rewrite it :). No problem with that.

**Comment by potiuk** [comment]
It simply grew from a simple script where there was more parameters. But my goal now is that more people take part in writing those scripts not only me. I marked it as good first issue, and if you feel like you would like to rewrite it - go ahead. I am happy to review it and guide you (or anyone else who would like to take on that task).

**Comment by debodirno** [comment]
Can I take this up @potiuk  and @mik-laj?

**Comment by mik-laj** [comment]
@debodirno I assigned you to this ticket 🐈‍⬛ 🎄
