### ISSUE TITLE
KubernetesPodOperator duplicate call to create_pod_request_obj()

### ISSUE THREAD

**Issue by lsowen** [apache/airflow#13070]
Does anyone know why there are two calls to `create_pod_request_obj()`  in https://github.com/apache/airflow/blob/c743b95a02ba1ec04013635a56ad042ce98823d2/airflow/contrib/operators/kubernetes_pod_operator.py#L278-L287

It looks like maybe a merge issue between two different PRs that got merged at approximately the same time?  (#11162 and #10963)

**Comment by eladkal** [comment]
You are viewing old version.
You should import the operator from providers:
https://github.com/apache/airflow/blob/bd90136aaf5035e3234fe545b79a3e4aad21efe2/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L311

**Comment by lsowen** [comment]
It looks like it has been fixed in `master`, but is still an issue in the `v1-10-stable` (https://github.com/apache/airflow/blob/v1-10-stable/airflow/contrib/operators/kubernetes_pod_operator.py#L278-L286)

Will there be any further 1.10.x releases?  Or is v2.0.0 the next release?

**Comment by eladkal** [comment]
You can install [backport provider package](https://pypi.org/project/apache-airflow-backport-providers-cncf-kubernetes/) which is compatible with 1.10.x
