### ISSUE TITLE
Apache Airflow Triggering DAG for Future Dates (Airflow Version 1.8.1)

### ISSUE THREAD

**Issue by shib-nmg** [apache/airflow#13077]
One of our DAG's "**Global Polling DAG**" which I am using for one of my Customers is getting triggered for Future dates, intermittently.

For example: **For 12/12 9.30 PM execution, the Global Polling DAG got triggered for 12/13 08:10 PM**

This is one of the unique occurrences that we are facing and the same Airflow domain was running without any issues, over the last 9+ Months.

Point to note is - The same "Global Polling DAG" is not behaving this way in other Airflow domains (we have a total of 4 Airflow Domains in Production).

Any quick help is really appreciated

**Environment: Airflow Version:** 1.8.1
**Cloud Platform :** AWS

Here's the Code Snippet on how the Global Polling DAG is triggered from the Airflow Python Script-
-----

_default_args = {  'owner': 'airflow', 'start_date': datetime(2018, 11, 25) } 
 
**dag = DAG('cdpGlobalPollingDag', default_args=default_args, schedule_interval='*/5 * * * *', catchup=False, max_active_runs=1)**
 
CDP_POLL_AUDIT_TABLE_task = PythonOperator( task_id='CDP_POLL_AUDIT_TABLE', provide_context=True, python_callable=poll.pollAuditTable, on_failure_callback=email.email_alert, op_kwargs={ 'dag_name':'cdpGlobalPollingDag' ,'thread_limit':thread_limit,'domain_list':domain_list} , dag=dag)_

**Comment by ashb** [comment]
Airflow 1.8.1 three and a half years old and does not receive any updates, nor support from the OSS project -- please test with later versions and re-open this issue if it is still a problem.
