### ISSUE TITLE
using relative directory as dags_folder no longer works in Airflow >= 1.7.0

### ISSUE THREAD

**Issue by amerkel2** [apache/airflow#1308]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow: 1.7.0
- Airflow components and configuration: running a scheduler with local executor
- Example code to reproduce the bug:
  `airflow.cfg`:
  
  ```
  [core]
  airflow_home = ~/airflow
  dags_folder = dags
  ```
- Operating System: Linux ubu91 3.13.0-83-generic #127~precise1-Ubuntu SMP Fri Mar 11 12:53:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Python Version: Python 2.7.3

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue
- What did you expect to happen?

When I configure a relative path as `dags_folder` in `airflow.cfg`, I expect dags in this folder to be found, scheduled, and executed, as it used to be the case in Airflow 1.6.2.
Or, at the very least, if relative paths are not supposed to be used, this should be documented and an error message given that the configuration is invalid.
- What happened instead?

The dags where found and scheduled, but the execution failed. The command the scheduler passes to the executor seems to be confused by the relative path and mixes things up, resulting in a wrong path to the dag passed to the executor. I find the following in the scheduler output:

```
[2016-04-06 14:44:31,680] {sequential_executor.py:27} INFO - Executing command: airflow run notify_wsgi notify_wsgi 2016-02-26T14:56:01.750588 --local -sd DAGS_FOLDER//home/PHI-TPS/amerkel/airflow/dag.py 
[2016-04-06 14:44:32,058] {__init__.py:36} INFO - Using executor SequentialExecutor
Traceback (most recent call last):
File "/home/PHI-TPS/amerkel/venv/airflow/bin/airflow", line 15, in <module>
    args.func(args)
  File "/home/PHI-TPS/amerkel/venv/airflow/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 167, in run
    raise AirflowException(msg)
  airflow.utils.AirflowException: DAG [notify_wsgi] could not be found in /home/PHI-TPS/amerkel/airflow/dags/home/PHI-TPS/amerkel/airflow/dag.py
```

(please note the duplication of the home directory in the path given in the last line of the traceback)
- Here is how you can reproduce this issue on your machine:
### Reproduction Steps
1. configure `dags_folder` using a relative path
2. put a DAG in the folder you configured
3. run `airflow scheduler`

**Comment by jlowin** [comment]
To be honest I'm not sure if we have ever "officially" supported relative directories. It's a messy proposition given that Airflow uses many subprocesses in its execution and while they will _probably_ share a working directory, I'm not sure that's guaranteed. In any case `git bisect` shows the commit that broke it was 8f06cf8 by @mistercrunch and I actually modified that code further in #1271.
