### ISSUE TITLE
max_retry_delay should be a timedelta for type hinting

### ISSUE THREAD

**Issue by wyndhblb** [apache/airflow#13086]
**Apache Airflow version**:

master

**What happened**:

https://github.com/apache/airflow/blob/master/airflow/models/baseoperator.py#L356 --> should be timedelta not datetime

**Comment by mik-laj** [comment]
Are you willing to submit a PR?

**Comment by wyndhblb** [comment]
there's another issue i'm working out as well (just found this while investigating that one).  even if the max_retry_delay is really a "timedelta" as defined in the task definition

it seems that https://github.com/apache/airflow/blob/master/airflow/models/taskinstance.py#L880 has it as a "float" (and thus the `min` fails).

**Comment by ashb** [comment]
Perhaps it should be a float (seconds) then, as this is the only thing that could have possible ever worked?

**Comment by iameugenejo** [comment]
I'm experiencing the same issue.

scheduler is failing to start up because of this.

**Comment by iameugenejo** [comment]
patch for `/airflow/models/taskinstance.py` I'm using to workaround is below:

```patch
880c880
<                 delay = min(self.task.max_retry_delay, delay)
---
>                 delay = timedelta(seconds=min(self.task.max_retry_delay, delay.total_seconds()))```
