### ISSUE TITLE
Log message about "variables" command being deprecated

### ISSUE THREAD

**Issue by tomyedwab** [apache/airflow#13091]
**Apache Airflow version**: 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): OSX 10.15.7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Saw this message in the logs:
`The 'variables' command is deprecated and removed in Airflow 2.0, please use 'variables' instead`

**What you expected to happen**:
If this is a legitimate error, it should be more helpful.

**How to reproduce it**:

```
pip install apache-airflow[postgres]==1.10.14
airflow db init
airflow variables
```

**Anything else we need to know**:

This happens in production on GKE as well.

**Comment by ashb** [comment]
Whoops, yes, that should have said something about use `variables list` instead.

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/14457
