### ISSUE TITLE
Too many workers being created on ARM platform (Nvidia Jetson Xavier)

### ISSUE THREAD

**Issue by RafayAK** [apache/airflow#13102]
**Apache Airflow version**:
1.10.13

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
 Running on Nvidia Jetson Xavier (ARMv8) 
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`):
 `4.9.140-tegra #1 SMP PREEMPT Thu Jun 25 21:22:12 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux`
- **Install tools**:
`- pip install apache-airflow --use-feature=2020-resolver`
- **Others**:
Running in a virtual pip environment 

**What happened**:
I am seeing very weird behavior when it comes to the number of worker threads created on my Jetson Xavier ARM platform. Airflow webserver should create a default of 4 workers but for some reason, **_it's creating 24 worker processes_**!

Following are the results from running `airflow webserver -p 8586`
![image](https://user-images.githubusercontent.com/17025191/102342173-afc01480-3fba-11eb-8544-85cee9722f47.png)

webserver logs show only 4 workers are created:
 
![image](https://user-images.githubusercontent.com/17025191/102342664-63290900-3fbb-11eb-841b-c8fbcc60c0e5.png)

Running `airflow webserver -p 8586 -w 1` still **_creates 8 worker processes_**:
![image](https://user-images.githubusercontent.com/17025191/102342458-10e7e800-3fbb-11eb-8bdb-f9f1f800b206.png)

even though, the webserver logs show only 1 worker is created
![image](https://user-images.githubusercontent.com/17025191/102342513-26f5a880-3fbb-11eb-8cae-5ccd90105f84.png) 

**What you expected to happen**:

Running Airflow on an x86 platform I don't  see this behavior:

Here's the result of running `airflow webserver -p 8586`:
![image](https://user-images.githubusercontent.com/17025191/102342908-bc913800-3fbb-11eb-94da-6bdae18a3f04.png)

Here's the result of running `airflow webserver -p 8586` on x86
![image](https://user-images.githubusercontent.com/17025191/102343021-ddf22400-3fbb-11eb-97da-b52aef8a8b49.png)

Some default value is being overridden on ARM
**How to reproduce it**:
Run on ARM platform

**Anything else we need to know**:

**Comment by RafayAK** [comment]
Any idea where I should look to resolve this issue?

**Comment by potiuk** [comment]
I believe it's just htop showing threads as processes on Arm. You can start investigating here - there are some options on disabling/enabling user threads: https://unix.stackexchange.com/questions/10362/why-does-htop-show-more-process-than-ps  - and you can compare it with what `ps` displays. I would love to hear when you investigate more @RafayAK. I close it for now as invalid but if you find that this is not the case and have some more findings, please comment here.
