### ISSUE TITLE
add Google leveldb hook

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#13109]
**Description**

add the ability to query and modify google leveldb https://github.com/google/leveldb from airflow.

Python wrapper that can be used to create the hook :
https://github.com/wbolster/plyvel
https://plyvel.readthedocs.io/en/latest/

**Are you willing to submit a PR?**

not at the moment due to time contains.

**Related Issues**

couldn't find any

**Comment by radim94** [comment]
Hello, @HaloKo4, @mik-laj, @eladkal! I am interested in making a PR for this.

**Comment by eladkal** [comment]
@radim94 assigned to you
