### ISSUE TITLE
Incorrectly rendered graph

### ISSUE THREAD

**Issue by MolochkoVitaly** [apache/airflow#13101]
**Apache Airflow version**: 1.10.10

**What happened**: 

```
from airflow.operators.dummy_operator import DummyOperator
from airflow import DAG
from datetime import datetime


default_args = {
    'start_date': datetime(2021, 1, 1),
    'owner': 'airflow'
}


dag = DAG('dummy_dag', default_args=default_args)

op1 = DummyOperator(task_id="op1", dag=dag)
op2 = DummyOperator(task_id="op2", dag=dag)
op3 = DummyOperator(task_id="op3", dag=dag)
op4 = DummyOperator(task_id="op4", dag=dag)
op5 = DummyOperator(task_id="op5", dag=dag)


op1 >> [op2, op3 >> op4] >> op5
```

![image](https://user-images.githubusercontent.com/11045746/102335030-6f539d00-3fa0-11eb-9b54-d5bfd79601e3.png)

**What you expected to happen**: 

![image](https://user-images.githubusercontent.com/11045746/102335407-ea1cb800-3fa0-11eb-866d-74be8b2731c6.png)

**How to reproduce it**:
Run code above

**Comment by ashb** [comment]
The issue is `op3 >> op4`. This expression returns the right hand side, so to expand out `op1 >> [op2, op3 >> op4] >> op5`, it is equivalent to:

```python
op1 >> op2
op3 >> op4
op1 >> op4
op2 >> op5
op4 >> op5
```

To get the structure you want you need to split it up a bit.


```python
op1 >> [op2, op3]
op3 >> op4
op5 << [op2, op4]
```

(I can't remember if you can do `[op2, op4] >> op5` or not.)

**Comment by MolochkoVitaly** [comment]
Thanks for clarifying
