### ISSUE TITLE
Improve DAG operator status accessibility for the color blind

### ISSUE THREAD

**Issue by atolopko-czi** [apache/airflow#13114]
The coloration of DAG operator statuses in the DAG "Tree" and "Graph" views are not easy to discern by color blind individuals. There is no textual representation of the status in the hover popup window.

**Use case / motivation**

**Are you willing to submit a PR?**

Yes

**Related Issues**

No

**Comment by eladkal** [comment]
What Airflow version are you running? There has been improve in that area in 1.10.11 
see issue https://github.com/apache/airflow/issues/7843, PR https://github.com/apache/airflow/pull/9520, [docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/customize-state-colors-ui.html) 
 
 
Also in Graph View when you over one of the statuses in the legend it makes all the tasks in that status highlighted:
![video](https://user-images.githubusercontent.com/45845474/102398072-7b168200-3fe7-11eb-95d5-b378ece02209.gif)


Can you give more information? (maybe a mock up of what you expect?)

**Comment by atolopko-czi** [comment]
Version : 1.10.10

The Tree view status-hover highlighting is indeed helpful, and I was unaware! The Graph view doesn't provide the same feature, which would be helpful.  So it would still be helpful if these popups contained the operator status: 
![image](https://user-images.githubusercontent.com/29237884/102410411-84d7bf80-3fbe-11eb-92c1-0d23cf320d82.png)

Use of custom colors may also be able to address this for particular degrees of color blindness, which I will try.

**Comment by kaxil** [comment]
You can customize those colors: https://airflow.readthedocs.io/en/stable/howto/customize-state-colors-ui.html

**Comment by ashb** [comment]
And if you can suggest new default colours we can look at changing them too.

**Comment by eladkal** [comment]
@atolopko-czi Do you think there are still issues needs to be addressed?  If you can please describe your suggestions

**Comment by atolopko-czi** [comment]
I still feel it is helpful if the Tree view status hover popups simply contained the operator status as text. Colors can be useful conveyors of information, but text is more accessible for the color-blind. I have not tried setting different default colors, since that would require consensus across our organization.

**Comment by kaxil** [comment]
![image](https://user-images.githubusercontent.com/8811558/106513750-42653600-64cb-11eb-99b2-7f1b96f2f659.png)

The tree view in 2.0.0 should already have that

**Comment by atolopko-czi** [comment]
Will upgrade! Thanks @kaxil!
