### ISSUE TITLE
Add missing logos for integrations

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13110]
Hello,

@ecerulm [added](https://github.com/apache/airflow/pull/13073) a logo `field` for `integration` object defined in `provider.yaml`
https://github.com/apache/airflow/blob/ccaca0af3933306c7ca0aa3d78fa2237ff3bfb19/airflow/provider.yaml.schema.json#L45-L48

We then use these logos to promote the integrations on our website.
<img width="1270" alt="Screenshot 2020-12-16 at 14 59 59" src="https://user-images.githubusercontent.com/12058428/102358718-21df2c00-3fb0-11eb-9310-18dd7ce42152.png">

It would be fantastic if we could add the missing logos to make each integration equally fantastic.

Here is an integration list that does not have a logo. If you are interested, you can integrate only to a few integrations and we will still be happy.
```
$ find . -name provider.yaml | xargs -n 1 yq r --tojson | jq '.integrations | map(select(.logo == null))[] | .["integration-name"]' -r | sort
jq: error (at <stdin>:11): Cannot iterate over null (null)
AWS DataSync
AWS Step Functions
Amazon CloudFormation
Amazon DataSync
Amazon ECS
Amazon ElastiCache
Amazon Glacier
Amazon SecretsManager
Amazon Simple Email Service (SES)
Amazon Web Services
Apache Kylin
Apache Livy
Atlassian Jira
Celery
Databricks
Datadog
Dingding
Discord
Docker
Docker Swarm
Elasticsearch
Exasol
Facebook Ads
File Transfer Protocol (FTP)
Google
Google API Python Client
Google Ads
Google Analytics360
Google BigQuery Data Transfer Service
Google Campaign Manager
Google Cloud
Google Cloud Data Loss Prevention (DLP)
Google Cloud Firestore
Google Cloud Life Sciences
Google Cloud OS Login
Google Cloud Secret Manager
Google Cloud Stackdriver
Google Data Catalog
Google Data Fusion
Google Data Proc
Google Dataprep
Google Deployment Manager
Google Discovery API
Google Display&Video 360
Google Drive
Google Search Ads 360
Google Spreadsheet
Hashicorp Vault
Hypertext Transfer Protocol (HTTP)
IBM Cloudant
Internet Message Access Protocol (IMAP)
Java Database Connectivity (JDBC)
Jenkins
Kubernetes
Microsoft Azure
Microsoft Azure Batch
Microsoft Azure Data Explorer
Microsoft Azure FileShare
Microsoft SQL Server (MSSQL)
MongoDB
MySQL
ODBC
OpenFaaS
Opsgenie
Oracle
Pagerduty
Papermill
Plexus
PostgreSQL
Presto
Qubole
Redis
SQLite
SSH File Transfer Protocol (SFTP)
Salesforce
Samba
Secure Shell (SSH)
Segment
Singularity
Slack
Snowflake
Spark on Kubernetes
Telegram
Vertica
Windows Remote Management (WinRM)
Yandex.Cloud
Yandex.Cloud Dataproc
Zendesk
gRPC
```

CC: @ecerulm

**Comment by griffincosgrove** [comment]
newbie here, looking to get my env set up and take this as my first issue.

**Comment by mik-laj** [comment]
@griffincosgrove I assigned you to this ticket. :-)

**Comment by griffincosgrove** [comment]
Beginner question: How do I view the home page of the docs with the integrations? I used breeze to build the docs and I can launch other pages, but I cannot find which HTML doc is the home page with the integrations, which file would be airflow.apache.org? Any guidance is appreciated

**Comment by potiuk** [comment]
http://airflow.apache.org/docs/

**Comment by griffincosgrove** [comment]
I am saying like the version i built through breeze, does that make sense?

**Comment by mik-laj** [comment]
@griffincosgrove  The website is developed in a separate repository. https://github.com/apache/airflow-site
If you want to see what these logos will look like on the site, you should take a few steps:
1.  First update provider.yaml files and add new logos in this repository.
2. Copy files to [airflow-site](https://github.com/apache/airflow-site) repository. [The`scripts/tools/generate-integrations-json.py` script](https://github.com/apache/airflow/blob/master/scripts/tools/generate-integrations-json.py) helps with this task.
3. Build a website using `site.sh` script - `site.sh build-site`. See: https://github.com/apache/airflow-site#getting-started
4. Launch preview - `site.sh preview-landing-pages`

**Comment by griffincosgrove** [comment]
@mik-laj ahh that's why I couldn't find it! thanks for pointing this out to me. I appreciate the knowledge. Want to make sure the logos look good!
