### ISSUE TITLE
[Question] [Feature] Ability to run python scripts as remote execution operator

### ISSUE THREAD

**Issue by sharmalalit** [apache/airflow#1312]
Dear Airflow Maintainers,

Is it possible to run a python script or a python method call when sensor is invoked. I was going through operators [0] documentation and noticed that this could be an HQL statement in Hive, a Pig script, a map reduce job, a stored procedure in Oracle or a Bash script to run.

[0]

**Comment by bolkedebruin** [comment]
Please ask this on the mailing list.
