### ISSUE TITLE
【no the feature？？？】Run multiple containers in `KubernetesPodOperator`?

### ISSUE THREAD

**Issue by zhangxiao696** [apache/airflow#13133]
Does the airflow.contrib.operators.kubernetes_pod_operator.KubernetesPodOperator have the possibility to start mutliple containers in the same pod?

If it has, where can I set related config?

please 🙏🙏
help me 🙏🙏

**Comment by hedrickw** [comment]
Have you tried using the KubernetesExecutor and using pod overrides like this example? https://github.com/apache/airflow/blob/master/airflow/example_dags/example_kubernetes_executor_config.py

**Comment by zhangxiao696** [comment]
> Have you tried using the KubernetesExecutor and using pod overrides like this example? https://github.com/apache/airflow/blob/master/airflow/example_dags/example_kubernetes_executor_config.py

I need use KubernetesPodOperator in the project, can you have some methods?

**Comment by eladkal** [comment]
Please use stackoverflow / slack for questions.
