### ISSUE TITLE
BigQuery hook: Insert_all (not working)

### ISSUE THREAD

**Issue by owlphi** [apache/airflow#13139]
# Problem 

When I am trying to use the method `insert_all` from bigquery hook I got:
 
```
ValueError: Could not determine schema for table 'Table(TableReference(DatasetReference(...))
```

The reason is that we are invoking the client insert_rows with a table without schema and the client is expecting a table with schema. 

Client expecting schema in the method insert_rows [here](https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/client.py#L2929), otherwise it will raise exception

However we are giving a table without schema [code](https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/hooks/bigquery.py#L879-L883 )

```
        table = self._resolve_table_reference(
            table_resource={}, project_id=project_id, dataset_id=dataset_id, table_id=table_id
        )
```

# Solution proposed: 

1. Get the table in bigquery 

```
table_ref = TableReference(dataset_ref=DatasetReference(project_id, dataset_id), table_id=table_id)
table = self.get_client(project_id=project_id).get_table(table_ref)
```

2. Pass the table in the method insert_rows (client)
```
self.get_client().insert_rows(
            table=table,
            rows=rows,
            ignore_unknown_values=ignore_unknown_values,
            skip_invalid_rows=skip_invalid_rows,
        )
```

**Comment by owlphi** [comment]
I have a PR: https://github.com/apache/airflow/pull/13138

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/13138
