### ISSUE TITLE
Purge DAG command?

### ISSUE THREAD

**Issue by apapanico** [apache/airflow#1314]
I believe my issue is related to this conversation.
https://groups.google.com/forum/#!topic/airbnb_airflow/GVsNsUxPRC0

The basic problem seems to be this:
I am testing out some parts of airflow so I create a test DAG and run it with the scheduler.  When I go to try to change the schedule, I update the dag code and restart the server and scheduler processes.  But the scheduler picks up where the previous schedule left off.  If I completely delete the dag and bring it back, same thing.  The only way to resolve it is to use `airflow resetdb`.  That seems like a blunt approach.  Based on the solution in that link above, what about something like `airflow purge dag_id` that will wipe out the DAG so that the new version can operate cleanly.

**Comment by jlowin** [comment]
I think this is a great idea that just needs to be codified as a PR... (hint, hint :smile:)

**Comment by bolkedebruin** [comment]
@apapanico please track AIRFLOW-20 that will allow more flexibility towards DAG updates. 

If needed please create a Jira to further track this please
