### ISSUE TITLE
Please update upper bound for `requests` dependency

### ISSUE THREAD

**Issue by yonromai** [apache/airflow#13141]
Hi, sorry if this is a duplicate. 

Would it be possible to update the upper bound for the `requests`, it's a bit outdated and conflicts with other packages' dependencies. e.g:
```
The conflict is caused by:
    apache-airflow[gcp] 2.0.0 depends on requests<2.24.0 and >=2.20.0
    apache-airflow 2.0.0 depends on requests<2.24.0 and >=2.20.0
    apache-beam[gcp] 2.25.0 depends on requests<3.0.0 and >=2.24.0
```

**Comment by turbaszek** [comment]
This is worked on. The limitation is due to snowflake as mentioned:
https://github.com/apache/airflow/blob/cddbf81b12650ee5905b0f762c1213caa1d3a7ed/setup.cfg#L128

Related: #13056 #12881 #13062

**Comment by yonromai** [comment]
Noted, thank you @turbaszek
