### ISSUE TITLE
Bug: s3 config file parsing

### ISSUE THREAD

**Issue by apapanico** [apache/airflow#1315]
There is a bug in s3 config file parsing.

Airflow version: 1.7

The bug is in:
https://github.com/airbnb/airflow/blob/3198756bceb9048829cfcd225e50336b6eee8f76/airflow/hooks/S3_hook.py#L55

Comment in `_parse_s3_config`, lines 43-44:

```
:param config_format: config type. One of "boto", "s3cmd" or "aws".
        Defaults to "boto"
```

However in `S3Hook` on lines 111-112:

```
# The format can be None and will default to boto in the parser
self.s3_config_format = self.extra_params.get('s3_config_format')
```

So what happens is, if `s3_config_format` is `None`, in line 55 it hasn't properly set it as the default value before applying the lower method.

**Comment by bolkedebruin** [comment]
@apapanico can you create a Jira for this (and/or PR)? Thanks!

**Comment by apapanico** [comment]
Will do.
