### ISSUE TITLE
Rewrite our Github Action workflows to Python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13182]
Yesterday (18th of December) GitHub announced a 3rd-party Python GHApi: https://github.blog/2020-12-18-learn-about-ghapi-a-new-third-party-python-client-for-the-github-api/

One of the features of the API is the ability to write GitHub Actions Workflows (including custom actions) entirely in Python:

https://github.blog/2020-12-18-learn-about-ghapi-a-new-third-party-python-client-for-the-github-api/#github-actions

This is super cool. Knowing the difficulties of combining YAML files, bash scripts and TypeScripts Actions) together, this is a so much better and easier way of writing the workflows,

We should rewrite all our workflows using this new API !

**Comment by potiuk** [comment]
cc: @kaxil @ashb @turbaszek @mik-laj and @TobKed  - let's do it!

**Comment by kaxil** [comment]
🎉 Yes let's do it

**Comment by emmanue** [comment]
@potiuk  I will like to help and contribute.

**Comment by TobKed** [comment]
@potiuk is it sill something considered to be done?

**Comment by eladkal** [comment]
> @potiuk is it sill something considered to be done?

This is in fact in progress. We have an intern from the Outreachy project that will take over this.

**Comment by potiuk** [comment]
Oh yeah. I will update the issue soon with an inventory of what is needed and we will work from here. Similarly https://github.com/apache/airflow/issues/12282 with rewriting breeze. Those will have some overlap so the two interns will be working together. More on that soon!

**Comment by potiuk** [comment]
Yeah. Finally the time had come to start work on the rewrite: 

First, founding PR is here: https://github.com/apache/airflow/pull/19867/ - those who are interested will find there some ADR (Architecture Decision Records) which we will keep throughout the whole project to capture all important decisions we've made and once we merge it, more stuff will come.

**Comment by eladkal** [comment]
I believe this is now completed :) ?

**Comment by potiuk** [comment]
Oh. Vrery much so :).
