### ISSUE TITLE
Generalize MLEngineStartTrainingJobOperator to custom images

### ISSUE THREAD

**Issue by IvanUkhov** [apache/airflow#13192]
**Description**

The operator is arguably unnecessarily limited to AI Platform’s standard images. The only change that is required to lift this constraint is making `package_uris` and `training_python_module` optional with default values `[]` and `None`, respectively. Then, using `master_config`, one can supply `imageUri` and run any image of choice.

**Use case / motivation**

This will open up for running arbitrary images on AI Platform.

**Are you willing to submit a PR?**

If the above sounds reasonable, I can open pull requests.

**Comment by turbaszek** [comment]
Please check the discussion:
https://github.com/apache/airflow/discussions/12610

I don't think the operator is limited as you can do:
```python
master_config={"imageUri" : "gcr.io/my-pytorch-image-uri"}
```

Please, reopen if I'm wrong 👌

**Comment by turbaszek** [comment]
Do I correctly understand that this:
```python
master_config={"imageUri" : "gcr.io/my-pytorch-image-uri"}
```

Won't work currently?

**Comment by IvanUkhov** [comment]
Those two are mutually exclusive ways of working with AI Platform. In other words, it does not make sense to specify `training_python_module` together with `imageUri`.

**Comment by turbaszek** [comment]
@IvanUkhov would you mind raising a PR?
