### ISSUE TITLE
Use of SQLAInterface in custom models in Plugins

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13226]
We might need to add to Airflow 2.0 upgrade documentation the need to use `CustomSQLAInterface` instead of `SQLAInterface`.

If you want to define your own appbuilder models  you need to change the interface to a Custom one:

Non-RBAC replace:
```
from flask_appbuilder.models.sqla.interface import SQLAInterface
datamodel = SQLAInterface(your_data_model)
```

with RBAC (in 1.10):
```
from airflow.www_rbac.utils import CustomSQLAInterface
datamodel = CustomSQLAInterface(your_data_model)
```

and in 2.0:

```
from airflow.www.utils import CustomSQLAInterface
datamodel = CustomSQLAInterface(your_data_model)
```

**Comment by Dr-Denzy** [comment]
I will like to work on this issue. Please assign it to me.

**Comment by Dr-Denzy** [comment]
@potiuk I am writing an upgrade check for this issue. Could you provide more perspective on this issue so that I can write a suitable unit test for this upgrade check. Thanks.

**Comment by potiuk** [comment]
Simply  import ogf the old SQLAInterface should tirgger a warning

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/14475
