### ISSUE TITLE
Clear Tasks via the stable REST API with task_id filter

### ISSUE THREAD

**Issue by avnerw74** [apache/airflow#13225]
**Description**

I have noticed that the stable REST API doesn't have the ability to run a task (which is possible from the airflow web interface.
I think it would be nice to have either:
- Run task 
- Run all failing tasks (rerun from point of failure)
this ability for integrations.

**Use case / motivation**

I would like the ability to identify the failing tasks on a specific DAG Run and rerun only them.
I would like to do it remotely (non-interactive) using the REST API.
I could write a script that run only the failing tasks, but I couldn't find a way to "Run" a task, when I have the task instance ID.

**Are you willing to submit a PR?**

Not at this stage

**Related Issues**

**Comment by vemikhaylov** [comment]
Would like to implement it

**Comment by eladkal** [comment]
@vemikhaylov assigned to you

**Comment by Kaash** [comment]
Am also looking at this feature as we want to "clear" tasks in DAGS based on task ids using the REST API. 

Hey @vemikhaylov are you close to a solution?

**Comment by kaxil** [comment]
Just to be clear we already have 

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_clear_task_instances

`https://airflow.apache.org/api/v1/dags/{dag_id}/clearTaskInstances` but the ask (at least from @Kaash ) is to have an optional task_id filter for this endpoint

**Comment by vemikhaylov** [comment]
> Am also looking at this feature as we want to "clear" tasks in DAGS based on task ids using the REST API.
> 
> Hey @vemikhaylov are you close to a solution?

Yes, I have implemented the most of the business logic and tests, but have gone on vacation. I'm going to create the PR in the next couple of days.

**Comment by vemikhaylov** [comment]
> Just to be clear we already have
> 
> https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_clear_task_instances
> 
> `https://airflow.apache.org/api/v1/dags/{dag_id}/clearTaskInstances` but the ask (at least from @Kaash ) is to have an optional task_id filter for this endpoint

Hey @kaxil 

I have locally implemented the following interface:

```yaml
  /dags/{dag_id}/runTaskInstance:
    parameters:
      - $ref: '#/components/parameters/DAGID'

    post:
      summary: Run a task instance
      x-openapi-router-controller: airflow.api_connexion.endpoints.task_instance_endpoint
      operationId: run_task_instance
      tags: [DAG]
      requestBody:
        description: Parameters of action
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunTaskInstance'

      responses:
        '202':
          description: Accepted.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NotFound'
    
   RunTaskInstance:
      type: object
      properties:
        task_id:
          description: The task ID.
          type: string

        execution_date:
          description: The execution date.
          type: string
          format: datetime

        ignore_all_dependencies:
          description: Whether to ignore all ignoreable dependencies
          type: boolean

        ignore_task_dependencies:
          description: Whether to ignore task-specific dependencies such as depends_on_past and
            trigger rule
          type: boolean

        ignore_task_instance_state:
          description: Whether to ignore the task instance's previous failure/success
          type: boolean
```

That's similar to what we have there:
https://github.com/apache/airflow/blob/master/airflow/www/views.py#L1311-L1331

That's is currently used to run a task instance from the UI, but works for the Celery and Kubernetes executors only.

Is it actually relevant or completely the same problems can be solved using the `/dags/{dag_id}/clearTaskInstances` endpoint and the separate endpoint isn't needed in the stable REST API?

**Comment by kaxil** [comment]
@vemikhaylov Yes, we should implement the `clearTaskInstances` as it works for all executors coz it let's Scheduler pick the TaskInstances instead of Webserver creating an executor and running it

**Comment by ngmiduc** [comment]
Is it also possible to clear a set of tasks with an associated dagRunId ? Like `/dags/{dag_id}/dagRuns/{dag_run_id}clearTaskInstances`

**Comment by potiuk** [comment]
You can get task instances via first: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances

**Comment by ngmiduc** [comment]
Okay but when I use a task_id, how does the API know from which DAG run it should clear? It doesn't seem to me that the task_id is a unique id. Or does it just clear out all tasks which that task_id?

**Comment by potiuk** [comment]
You wo't use task_id. Look what "get_task_instances" return.
