### ISSUE TITLE
One ClientInfo instance in Google provider

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13231]
Hello,

Client info initialization is duplicated in many places.
https://github.com/apache/airflow/blob/349b0811c3022605426ba57d30936240a7c2848a/airflow/providers/google/cloud/_internal_client/secret_manager_client.py#L65
https://github.com/apache/airflow/blob/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5/airflow/providers/google/cloud/log/gcs_task_handler.py#L100
https://github.com/apache/airflow/blob/b40dffa08547b610162f8cacfa75847f3c4ca364/airflow/providers/google/common/hooks/base_google.py#L343
https://github.com/apache/airflow/blob/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5/airflow/providers/google/cloud/log/stackdriver_task_handler.py#L112

It would be great if you could reduce these duplications and use one object created at the module level.
Of course, we must not forget that this change should be backward compatible and that old references displayed deprecation warnings. (GoogleBaseHook.client_info.

**Comment by anand-sivampeta** [comment]
Hi. This is my first contribution and I'd like to work on this.

**Comment by potiuk** [comment]
Feel Free! I assigned you :)

**Comment by eladkal** [comment]
@anand-sivampeta unassigning you due to passed time.
This issue is open for anyone who wants to pick it up.

**Comment by potiuk** [comment]
Assigned you @pierrejeambrun
