### ISSUE TITLE
[ui] Tree view provides inconsistent representation of dependent task views

### ISSUE THREAD

**Issue by akotlar** [apache/airflow#13242]
**Apache Airflow version**: 2.0.0
**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): NAME="Ubuntu 18.04.5 LTS"
- **Kernel** (e.g. `uname -a`): Linux 18.04.1-Ubuntu SMP
- **Install tools**:
- **Others**:

**What happened**:

Tree view does not appear to properly represent the relationship between dependent task group. Tasks within one task group should not be shown as dependent on another task group.

**What you expected to happen**:

Task groups to be descendants of one another, with no edges between the leaves of different task groups.

**How to reproduce it**:

Reproduction attached. TL;DR:

```python
with DAG(dag_id=DAG_NAME,
         default_args=default_args,
         schedule_interval='@daily',
         max_active_runs=1,
         catchup=False,
         tags=['test'],
         is_paused_upon_creation=True) as dag:
    folders = ['test1', 'test2', 'test3', 'test4']
    start = DummyOperator(task_id="start")
    with TaskGroup("step1") as task_group1:
        for path in folders:
            f1 = PythonOperator(
                task_id=path,
                python_callable=fn1
            )

    with TaskGroup("step2") as task_group2:
        for path in folders:
            f2 = PythonOperator(
                task_id=path,
                python_callable=fn2
            )

    with TaskGroup("step3") as task_group3:
        for path in folders:
            f3 = PythonOperator(
                task_id=path,
                python_callable=fn3
            )

    start >> task_group1 >> task_group2 >> task_group3
```

**How often does this problem occur? Once? Every time etc?**

Every time

[repo.py.gz](https://github.com/apache/airflow/files/5727820/repo.py.gz)
![Screenshot (312)](https://user-images.githubusercontent.com/5543229/102850057-8eaa5a00-43e6-11eb-8130-01788e8d5a58.png)
![Screenshot (314)](https://user-images.githubusercontent.com/5543229/102850169-c4e7d980-43e6-11eb-990f-552c14127def.png)

**Comment by bbovenzi** [comment]
It does seem like the Tree View is working as intended. It's just that a tree diagram isn't the best way to represent all types of DAGs.

I think we would need to add the ability for nodes in the tree to merge back together. Like so:
<img width="419" alt="Screen Shot 2021-02-10 at 1 39 55 PM" src="https://user-images.githubusercontent.com/4600967/107569427-e75bcf00-6bad-11eb-8fc6-3d39d5643a3c.png">

**Comment by akotlar** [comment]
Agreed, this should be a feature request.

**Comment by Miksu82** [comment]
What about showing only the task groups (and tasks that are not in any group) in the tree view and then when the task group is clicked (or hovered over) it shows the tasks belonging to that task group.

So the tree view would only show.

```
[DAG] 
     \
      Start
           \
            step1
                 \
                  step2
                       \
                        step3
```

would that simplify the implementation?
