### ISSUE TITLE
Authentication model is uselsss for multitenant use

### ISSUE THREAD

**Issue by dgies** [apache/airflow#1325]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
- Version of Airflow: 1.7.0
- LDAP authentication
- Example code to reproduce the bug

```
[webserver]
filter_by_owner = True
authenticate = True
auth_backend = airflow.contrib.auth.backends.ldap_auth

[ldap]
uri = ldaps://ldap.mycompany.com
#user_filter = uid={0}
user_filter = objectClass=CompanyUser
user_name_attr = uid
bind_user =   
bind_password =    
superuser_filter = memberOf=CN=admins,ou=groups,dc=mycompany,dc=com
basedn = ou=people,dc=mycompany,dc=com
```
- Operating System: (Windows Version or `$ uname -a`)
- Python Version: 2.7.5
- (Optional) Python packages: Babel==1.3
  Flask==0.10.1
  Flask-Admin==1.4.0
  Flask-Cache==0.13.1
  Flask-Login==0.2.11
  Flask-WTF==0.12
  SQLAlchemy==1.0.12
  WTForms==2.1
  airflow==1.7.0
  ldap3==1.2.2

Now that you know a little about me, let me tell you about the issue I am having:

The current web app security model of Airflow is unsuitable for supporting multiple unprivileged users.
With the above airflow.cfg settings any non-admin user can log in and get to the TaskInstances view for any other users' tasks.  From there they can view the DAGs, run/rerun/delete any other users' task instances.  This makes Airflow unusable in a multi-user environment because there is no way of protecting a user's jobs from everyone else.
- What did you expect to happen?
  I expected that filter_by_owner would act as true protection for user's DAGs against viewing/manipulation by other users.  Airflow should implement true owner-based permission checks for dags, dag_runs, task_instances and anything else with a dag_id
- What happened instead?
  Any non superuser has full control over every other user's DAGs and task instances.
- Here is how you can reproduce this issue on your machine:
  Enable filter_by_owner in airflow.cfg
  Create a DAG owned by some user 1
  Run any task in that dag
  Create a new user 2 who is not a superuser using your auth backend of choice
  Log in as the new user 2.
  Navigate to the Task Instances view
  See the TaskInstance of the DAG owned by user 1
  Click into the various dag details of user 1's DAG
  Run/delete task instances of user 1's DAG while logged in as user 2

**Comment by gumupaier** [comment]
I have the same problem. Has it been solved?
