### ISSUE TITLE
Move READMEs for providers to documentation.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13273]
The Readme's and changes generated should be created in the documentation folder and follow .rst format rather than in the provider's source code.

**Comment by debodirno** [comment]
Can you assign this to me, @potiuk?
FYI @mik-laj.

**Comment by mik-laj** [comment]
Assigned.

**Comment by potiuk** [comment]
I already have it in progress @debodirno  . I am making a change to revamp the provider structure and this is part of the change.

**Comment by potiuk** [comment]
This includes changing the auto-generated content of those and changing the approach of generation slightly so I prefer to do it as part of bigger change.

**Comment by potiuk** [comment]
That's why I assigned it to myself :)

**Comment by debodirno** [comment]
Makes sense.
