### ISSUE TITLE
Logging to S3 is failing

### ISSUE THREAD

**Issue by SivaPandeti** [apache/airflow#1327]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet):
- I used https://github.com/airbnb/airflow.git@6581858
- Set the config variables below
  remote_base_log_folder = s3://bucket-name/logs
  remote_log_conn_id = s3_default
- Created S3 connection with extra_params as 
  {"s3_config_file":"/path/to/credentials", "s3_config_format":"boto", "profile": "None", "calling_format":"boto.s3.connection.OrdinaryCallingFormat"}
- Airflow components and configuration, if applicable (e.g. "Running a Scheduler with CeleryExecutor")
  Used scheduler with CeleryExecutor

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue
- What did you expect to happen?
  To upload logs to S3 at the end of the job
- What happened instead?
  Did not upload logs to S3. 
  `ERROR - Could not write logs to s3://bucket-name/logs`

**Comment by SivaPandeti** [comment]
It ended up being a minor change. Looks like recent changes in organizing into utils may have broken this. utils/logging.py is referring to get_bool() function in configuration.py which does not exist. It should be using getboolean() function that exists already.

I submitted a pull request https://github.com/airbnb/airflow/pull/1326

**Comment by jlowin** [comment]
Closed via #1326
