### ISSUE TITLE
Documentation should match version of the provider.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13279]
Since we have diffferent version of the providers, we should be able to generate the documentation for each version of the provider based on it's past releases (tag: providers-<PROVIDER>/<VERSION>)

**Comment by potiuk** [comment]
CC: @mik-laj -> not sure how we want to do it. But I am sure you have some ideas

**Comment by mik-laj** [comment]
Currently, the version in provider.yaml is taken, so you only need to update this file before building the documentation.
https://github.com/apache/airflow/blob/1b96149f128925362482f93f7fb230ebacd60c9d/airflow/provider.yaml.schema.json#L17-L23
