### ISSUE TITLE
Slim down generated provider's READMEs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13274]
The generated READMES should contain only ADDITIONAL_INFO.md and Brief description of the package, link to the detailed documentation and list of changes since the last release.

**Comment by debodirno** [comment]
I can work on this @potiuk. Please assign it to me?

**Comment by potiuk** [comment]
Same here. This is part of the change on how provider packages are generated, that's why I had it assigned to myself and I am quite close to complete it.
