### ISSUE TITLE
Rename ADDITIONAL_INFO.md to CHANGELOG.rst

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13276]
ADDITIONAL_INFO will now become the main source of information on high-level changes in provider. So it is not additional and it should contain any information about new stuff added and changes.

**Comment by mik-laj** [comment]
I think we can just move this file to UPDATING.rst in the documentation for a specific provider. This will be most easily accessible to the end-user. I am happy to help with content migration.

**Comment by potiuk** [comment]
I prefer PROVIDERS_INFO.rst , it will contain more information than just updating. This contains also limitations, additional information etc. I already migrated content within the change that I am going to submit right after I merge #13409  #13488 and #13439 which have overlaping changes. I would love to only have to rebase and resolving conflicts once.
