### ISSUE TITLE
The LegacyUIDeprecatedRule and ChainBetwenDAGAndOperatorNotAllowedRule are not working as expected

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#13287]
Checking the upgrade check command and found out that LegacyUIDeprecatedRule and ChainBetwenDAGAndOperatorNotAllowedRule are not working as expected.

LegacyUIDeprecatedRule:
This is not working when `rbac` is set to `False` but works when it's set to `false`.

ChainBetwenDAGAndOperatorNotAllowedRule:
This is not working as I expected. I tested with the dag below and received no warning:
```
from airflow import models
from airflow.operators.dummy_operator import DummyOperator
from datetime import datetime
default_args = {
    'owner': 'airflow',
    'start_date': datetime(2018, 10, 31),
}

dag_name = 'on_failure_callback'


dag = models.DAG(dag_name,
                 default_args=default_args,
                 schedule_interval='@once',
                 catchup=False,
                 max_active_runs=5,
                 tags=['core']
                 )

test1 = DummyOperator(
    task_id="test1",
    start_date=datetime(2018, 10, 31)
)

dag >> test1
```

**Comment by eladkal** [comment]
the first issue was fixed in https://github.com/apache/airflow/pull/14967 and released in 1.4.0 the second issue was not as https://github.com/apache/airflow/pull/14982 was stale. Since there are no more releases of upgrade check I'm closing this issue.
