### ISSUE TITLE
multiporcessing in task throwd daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by mtaohuang** [apache/airflow#13298]
**Apache Airflow version**:
2.0

**Environment**:
Python3.6

**What happened**:
I used mutiprocessing Process in PythonOperator callable function, but it reports an error.

  File "/home/xxx/airflow/dags/Gen/SecData.py", line 88, in gen
    w.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children

**What you expected to happen**:
In airflow1.10, I could use multiprocessing in task function, it works well,
I'm not sure if is't a bug or there are other ways to use multiporcessing in PythonOperator task function.

**Comment by downeyh** [comment]
export PYTHONOPTIMIZE=1
solved the problem
