### ISSUE TITLE
Passing Task result from one to another?

### ISSUE THREAD

**Issue by anthonylau** [apache/airflow#133]
For example, I have a task A to get result from a REST API and task B requires task A result to do something.

**Comment by mistercrunch** [comment]
It's not directly supported. Though your pipeline script can read a configuration centrally and pass them to tasks, cross task communication isn't natively supported. Would it make sense in your case to make that call in the pipeline file itself (as opposed to within a task)

Specific operators could implement communication with other operators, but none of the native operators support this. The `Variables` model could be used for that purpose.

**Comment by anthonylau** [comment]
Thanks. Actually, I want something like Chain/Group in Celery.
