### ISSUE TITLE
Verify production image with all the components

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13315]
As discussed in https://github.com/apache/airflow/pull/13308#issuecomment-751251261 we would like to add more verification for ifeatures of airflow production image.

We run already 'verify image' step so we can run quite a more number of those veification in `ci_verify_prod_image.sh`  for example to test ldap we could run:

```
docker --rm ${AIRFLOW_PROD_IMAGE} 'python' 'import ldap'
```
The following features should be tested:

- [x] async
- [x] amazon
- [x] celery
- [x] cncf.kubernetes
- [x] docker
- [x] dask
- [x] elasticsearch
- [x] ftp
- [x] grpc
- [x] hashicorp
- [x] http
- [x] ldap
- [x] google
- [x] microsoft.azure
- [x] mysql,postgres
- [x] redis,sendgrid
- [x] sftp,slack
- [x] ssh,statsd
- [x] virtualenv

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by mik-laj** [comment]
I am not sure if we need to verify the installation of every possible library.  If they are written in Python, they should probably work fine in any case.  I am concerned about native libraries, especially libraries that need to be compiled during installation. When we use multi-stage build, it may turn out that we are missing system dependencies or the system dependency is incompatible.  For the most part, this is what pip does just fine, but only when we're actually using it, and not just copying the necessary files.
https://github.com/apache/airflow/blob/98896e4e327f256fd04087a49a13e16a246022c9/Dockerfile#L425

**Comment by potiuk** [comment]
It doe not cost us anything to add more libraries. Do you see any drawback of doing so ?

**Comment by mik-laj** [comment]
@potiuk I don't mind adding verifications of other libraries, but I wanted to show a wider context and reasons why we should add these tests.

**Comment by potiuk** [comment]
There are mamy other content which are similar. MySQL and Postgres have binary libraries with apt dependencies, similarly openssl and sqlite. Those are in exactly the same situation as ldap. 

That's why it is much better to chęci all dependencies rather than focus on single one because you might not realise thqt therr is a hidden dependency. 

There is nothing special with ldap in this regard.

**Comment by potiuk** [comment]
This is complteted. now.
