### ISSUE TITLE
Cleanup task_instance and dag_runs tables.

### ISSUE THREAD

**Issue by krisskross** [apache/airflow#1333]
Hi

We have a lot dags/tasks that run often and would like to delete them from the database after a while. How can we do this without triggering the scheduler to re-schedule them? 

Cheers,
-Kristoffer

**Comment by jlowin** [comment]
To delete tasks, the easiest thing is to use the Airflow UI TaskInstance view, filter for the ones you want to delete, select all, and delete them all at once.

Deleting dag_runs can be done the same way.

Keep an eye on #1344, it'll make it easier to totally delete a DAG.
