### ISSUE TITLE
CRSF Token missing

### ISSUE THREAD

**Issue by Karthik-PlantSense** [apache/airflow#13357]
i am trying to create a plugin which support rest-api whenever i try to call the api
on POST method it is saying csrf token and also i am using the `@csrf.exempt`
function also i got the same error

**Apache Airflow version**: 2.0.0, LocalExecutor

**Environment**: linux centos7

**Airflow Configuration**

`rbac=True`

please someone help me on this one...
@imbaczek

**Comment by Karthik-PlantSense** [comment]
@imbaczek

**Comment by mik-laj** [comment]
What version of Airflow are you using?

**Comment by Karthik-PlantSense** [comment]
i'm using
`airflow version 2.0` 
`rbac=True`
