### ISSUE TITLE
Add a flag to list all Upgrade Check Rules

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#13378]
It would be nice to have a list of all the available uprade-checks rules:

```
❯ airflow upgrade_check --help
usage: airflow upgrade_check [-h] [-s SAVE] [-i IGNORE] [-c CONFIG]

optional arguments:
  -h, --help            show this help message and exit
  -s SAVE, --save SAVE  Saves the result to the indicated file. The file
                        format is determined by the file extension.
  -i IGNORE, --ignore IGNORE
                        Ignore a rule. Can be used multiple times.
  -c CONFIG, --config CONFIG
                        Path to upgrade check config yaml file.
```

example (Ideally it should have 2 columns: Check_ID / Class Name and Summary):

```
❯ airflow upgrade_check --list

- Check for latest versions of apache-airflow and checker
- Remove airflowAirflowMacroPlugin class
- Chain between DAG and operator not allowed
- Connectionconn_id is not unique
- Connectionconn_type is not nullable
- Ensure users are not using custom metaclasses in custom operators
- Fernet is enabled by default
- GCP service account key deprecation
- Unify hostname_callable option in core section
- Changes in import paths of hooks, operators, sensors and others
- Users must delete deprecated configs for KubernetesExecutor
- Legacy UI is deprecated by default
- Logging configuration has been moved to new section
- Removal of Mesos Executor
- No additional argument allowed in BaseOperator
- Users must set a kubernetespod_template_file value
- SendGrid email uses old airflowcontrib module
- Changes in import path of remote task handlers
- Jinja Template Variables cannot be undefined
```

Related Slack conversation: https://apache-airflow.slack.com/archives/CCQB40SQJ/p1609259241092000

This allows users to know the progress of their checks and an easy way to ignore a check beforehand (if we list an id / class name too, example `PodTemplateFileRule`).

**Comment by madison-ookla** [comment]
If I might add, it would be also useful to list the rule class name so people know which rules correspond to which class if they want to ignore them!

**Comment by kaxil** [comment]
> If I might add, it would be also useful to list the rule class name so people know which rules correspond to which class if they want to ignore them!

Was just adding that too :) literally did it few seconds beack :)

**Comment by madison-ookla** [comment]
> Was just adding that too :) literally did it few seconds back :)

Ha, forgive my impatience 😁 ! I'm working on #13349 and #13350 right now, feel free to assign this to me if you wanted!

**Comment by kaxil** [comment]
> > Was just adding that too :) literally did it few seconds back :)
> 
> Ha, forgive my impatience 😁 ! I'm working on #13349 and #13350 right now, feel free to assign this to me if you wanted!

Awesome, assigned it to you :) Looking forward to reviewing your PR

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/13392
