### ISSUE TITLE
Dag scheduler doesn't create dag runs, clicking empty dag run box in UI results in server error

### ISSUE THREAD

**Issue by jbrownlucid** [apache/airflow#1338]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow - 1.6.2
- Scheduler and webserver on dedicated node, redis queue, two workers on separate nodes.
- Screen shots of your DAG's graph and tree views:
  <img width="686" alt="screen shot 2016-04-07 at 3 05 44 pm" src="https://cloud.githubusercontent.com/assets/14926421/14398499/3ef68574-fdaa-11e5-9249-3d09b599fdc3.png">
- Stack trace:

```
DataError: (psycopg2.DataError) invalid input syntax for integer: "undefined"
LINE 3: WHERE dag_run.id = 'undefined'
```
- Operating System: Ubuntu 14.04 on AWS
- Python Version: 2.7.6

Now that you know a little about me, let me tell you about the issue I am having:

After backfilling a DAG, the task instances show as complete, but the dag runs above each date are empty. When I click one of the white dag_run squares, I see the "mushroom cloud" page, with a message saying 

```
DataError: (psycopg2.DataError) invalid input syntax for integer: "undefined"
LINE 3: WHERE dag_run.id = 'undefined'
```
### Description of Issue
- What did you expect to happen? Expected to see information about the DAG run
- What happened instead? A 500 server error
### Reproduction Steps

After backfilling a DAG, the task instances show as complete, but the dag runs above each date are empty. When I click one of the white dag_run squares, I see the "mushroom cloud" page, with a message saying 

```
DataError: (psycopg2.DataError) invalid input syntax for integer: "undefined"
LINE 3: WHERE dag_run.id = 'undefined'
```

**Comment by bolkedebruin** [comment]
Is this still an issue on recent airflows? Then please create an issue on Jira.
