### ISSUE TITLE
No DAG parsing error while runing "airflow dags list" in airflow 2.0

### ISSUE THREAD

**Issue by forestlzj** [apache/airflow#13388]
**Apache Airflow version**:
2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:  hp gen380   32c, 192g ram
- **OS** (e.g. from /etc/os-release): centos 7.3
- **Kernel** (e.g. `uname -a`):
- **Install tools**:  
- **Others**:

**What happened**:
before 2.0, the command "airflow list_dags" will show the error of parsing a DAG, which help developer to find any syntax error. but for 2.0, the command “airflow dags list" only show the DAG parsed correctly. No any hints for the DAG parsed failed.

**What you expected to happen**:
somewhere to show the error of parsing a specify DAG

**How to reproduce it**:
create a DAG with syntax error, then run "airflow dags list"

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Done via: https://github.com/apache/airflow/pull/13180
