### ISSUE TITLE
airflow 2.0.0  sqlite3.OperationalError syntax error

### ISSUE THREAD

**Issue by ChiHangChen** [apache/airflow#13397]
Why I keep got this error when scheduler run my task?
```
[2020-12-31 03:05:22,716] {taskinstance.py:1396} ERROR - (sqlite3.OperationalError) near ",": syntax error
[SQL: DELETE FROM rendered_task_instance_fields WHERE rendered_task_instance_fields.dag_id = ? AND rendered_task_instance_fields.task_id = ? AND (rendered_task_instance_fields.dag_id, rendered_task_instance_fields.task_id, rendered_task_instance_fields.execution_date) NOT IN (SELECT rendered_task_instance_fields.dag_id, rendered_task_instance_fields.task_id, rendered_task_instance_fields.execution_date 
FROM rendered_task_instance_fields 
WHERE rendered_task_instance_fields.dag_id = ? AND rendered_task_instance_fields.task_id = ? ORDER BY rendered_task_instance_fields.execution_date DESC
 LIMIT ? OFFSET ?)]
[parameters: ('comic_app_v1', 'superman_task', 'comic_app_v1', 'superman_task', 30, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/home/user/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/user/py37/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ",": syntax error
```

**Comment by potiuk** [comment]
You have a very old sqlite3 version. Please upgrade to latest version.

**Comment by venezianluis** [comment]
@ChiHangChen do you have solved this error? i had the same issue and it's all documented at [stackoverflow](https://stackoverflow.com/questions/65521057/sqlite-syntax-error-with-simple-task-on-apache-airflow-2-0)

**Comment by ChiHangChen** [comment]
Already tried update sqlite3, still got the same error?
Is there any specific command to update sqlite3?

**Comment by potiuk** [comment]
If you are running some old system (RHE7 for sure has this problem) the sqlite3 vrersion there might be < 7 years old even if you update to standard latest version. You need to Follow https://www.tutorialspoint.com/sqlite/sqlite_installation.htm to install the latest version.

**Comment by potiuk** [comment]
just run `sqlite3 version` to check the version you have. Check https://sqlite.org/changes.html to see how old version you have. For sure 3.27.2 and newer is good.

**Comment by venezianluis** [comment]
I have updated sqlite3 to 3.34.0 2020-12-01 and still getting the error, do i need to do something else?

**Comment by potiuk** [comment]
Are you sure your sqlite version is correcty installed and used?

1) Can you follow this https://stackoverflow.com/questions/44621879/figuring-out-my-sqlite-version?rq=1  and report what you see?

2) Airflow has a neat `airflow db shell` command and it prints the version used

3) If all is fine can you wipe out the databases you find in ${AIRFLOW_HOME}/ or ${HOME}/airflow folder and retry? This is where sqlite database gets created and it is likely that if you the db got alrready created with old version, some backwards-compatibility mode kicks in, so deleting it might tigger recreation with the latest version.

**Comment by venezianluis** [comment]
1. There is sqlite_version and version:
```
>>> sqlite3.sqlite_version
'3.11.0'
>>> sqlite3.version
'2.6.0'
```

2. Using db shell:

```
~$ airflow db shell
SQLite version 3.34.0 2020-12-01 16:14:00
Enter ".help" for usage hints.
sqlite> SELECT sqlite_version();
3.34.0
```

3. I also tried to install the VM again([vm link](https://marclamberti.com/form-course-material-100/)) but i had no success, just putting here if someone want to know exactly how my enviroment is configured, password is vagrant

**Comment by potiuk** [comment]
Which python version do you use? I see that in my python version (3.6.12) the sqlite3.sqlite_version is 3.31.1 . So I guess you hava some old python version. Sqlite DB-API  is part of python and I believe you must have some old python version then.

**Comment by venezianluis** [comment]
```
~$ python --version
Python 3.7.9
```

**Comment by potiuk** [comment]
BTW. I confirmed that 3.11.0 results in this error. I followed the URL I gave you and downgraded sqlite with LD_LIBRARY_PATH and could reproduce it. I am trying to figure out which is the minimum version supported, but you should definitely upgrade sqlite3 and make it avaliable to python (via LD_LIBRARY_PATH for example)

**Comment by venezianluis** [comment]
Thanks for support, i'm trying to upgrade my sqlite_version and then when i get it i will post the results here and delete this comment.

**Comment by potiuk** [comment]
FYI. 3.15.0 is the minimum version that works. I am adding it to the docs and Airflow will fail hard if sqlite3 version is less than that (PR is coming for #13493)

**Comment by potiuk** [comment]
Don't delete comments. They might be useful for others having same problem.

**Comment by DuongPTIT** [comment]
I upgrade sqlite3 on Centos7 and python3 to newest version 3.34, but it still throw error: 
`WHERE rendered_task_instance_fields.dag_id = ? AND rendered_task_instance_fields.task_id = ? ORDER BY rendered_task_instance_fields.execution_date DESC
 LIMIT ? OFFSET ?)]
[parameters: ('tutorial', 'print_date', 'tutorial', 'print_date', 30, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ",": syntax error`

**Comment by potiuk** [comment]
@DuongPTIT  : As discussed in #13496 - this is for surre problem with your Airflow using still the old version. Please upgrade to later version of your VM or make sure that the upgraded sqlite libraries are your LD_LIBRARY_PATH when airflow runs. It might be tricky, depending on how your airflow is run (service? autostart? you name it) and this is totally outside of airflow itself. 

Upgrading to later version of VM, where sqlite3 is >= 3.15.0 is your best bet if you do not want to mess around with your airflow deployment and force it to use another version of sqlite3 than default.

**Comment by danmur** [comment]
I'll just add that a lot of corporate people are stuck on rhel7/centos7. If there were a fix that could be done in airflow it would be an advantage for adoption in that environment :)

**Comment by potiuk** [comment]
> I'll just add that a lot of corporate people are stuck on rhel7/centos7. If there were a fix that could be done in airflow it would be an advantage for adoption in that environment :)

I don't think so - for now we merged change that will simply fail Airflow starting from 2.0.1 if we see old sqlite version. Installing new sqlite is not really a problem once you know that it should be done. You will know now because Airflow will fail you and let you know why it did. I think this is better than supporting 6-old version of sqlite (which is development version only).

**Comment by kaxil** [comment]
To add to what Jarek said, sqlite should only be for local dev / unit tests (on your machine) but otherwise you should use Postgres / MySQL even for your company's dev environment

**Comment by danmur** [comment]
Yes, local dev on rhel7 machines is what I was referring to.

I've used a workaround, installing a new version of sqlite into /opt and injecting the so in the right place, so it's not a problem for me. I was just saying that it will be a roadblock for many.

**Comment by potiuk** [comment]
> Yes, local dev on rhel7 machines is what I was referring to.
> 
> I've used a workaround, installing a new version of sqlite into /opt and injecting the so in the right place, so it's not a problem for me. I was just saying that it will be a roadblock for many.

I understand your point, but i think in this case decision is good. We are in a "forward" looking project. There is little value in complicating our setup for "development" settings for RHEL7 case. RHEL8 was released in Novemeber 2019 and while RHEL7 EOL is 2025, it will be only going down, never up. The overhead of installing and using latest SQLite version is so small that it is no worth to complicate our code to serve that code. 

Besides, if that drives adoption of newer version of RHEL 8 for people who are stuck on RHEL7 - even by a fraction of a percent - I think this is a good karma that will return to us.
