### ISSUE TITLE
BashOperator "env" should extend os envvars and not entirely replacing them

### ISSUE THREAD

**Issue by ramsesrm** [apache/airflow#13445]
**Description**

Current (1.10.14) behavior of BashOperator's is entirely replacing the os env by the envvars present in the "env" dict, if exists.

Perhaps it should extend the os envvars with the ones in the env dict, instead.

**Use case / motivation**

I'm using a BashOperator + custom env dict on an Airflow stable helm installation, and i had to add an additional env dict entry like this to make it work:

``
        env={
            "PATH": "$PATH:/bin",
``

as using the "env" entry the original os PATH variable is ignored, and Airflow can't even find "bash" command.

**Comment by mik-laj** [comment]
Copying all the environmental ones doesn't sound good to me. There are cases when Airflow has certain environmental variables, and the script should not have these variables, especially since environment variables very often contain secrets.

You can easily add this behavior in your DAG code so I don't see any reason to make suggested change.
````bash
    task = BashOperator(
        task_id='runme',
        bash_command='./my-script.sh ',
        dag=dag,
        env={
            'CUSTOM_ENV': 'CUSTOM_VALUE',
            **os.environ
        }
    )
````

**Comment by ramsesrm** [comment]
Hi @mik-laj, thanks for the clarification, i didn't consider the value of isolating the script from the os envs. I'm closing this one :)

**Comment by leomarques90** [comment]
> Copying all the environmental ones doesn't sound good to me. There are cases when Airflow has certain environmental variables, and the script should not have these variables, especially since environment variables very often contain secrets.
> 
> You can easily add this behavior in your DAG code so I don't see any reason to make suggested change.
> 
> ```shell
>     task = BashOperator(
>         task_id='runme',
>         bash_command='./my-script.sh ',
>         dag=dag,
>         env={
>             'CUSTOM_ENV': 'CUSTOM_VALUE',
>             **os.environ
>         }
>     )
> ```

For those who are considering adding "**os.environ", and have sensitive data on environment variable, another way to not override the environment variables and avoid showing it on "Task Instance Details -> env" dag option, it to set the parameter `append_env` to `True`, like:
```shell
    task = BashOperator(
        task_id='runme',
        bash_command='./my-script.sh ',
        dag=dag,
        env={
            'CUSTOM_ENV': 'CUSTOM_VALUE',
        },
        append_env=true
    )
```
