### ISSUE TITLE
Source package distribution in PyPi repository

### ISSUE THREAD

**Issue by gshiva** [apache/airflow#13467]
Source package distribution in PyPi repository

To ensure that the correct libraries are linked, we rely on the source distribution package like https://files.pythonhosted.org/packages/db/f7/43fecb94d66959c1e23aa53d6161231dca0e93ec500224cf31b3c4073e37/lxml-4.6.2.tar.gz (lxml https://pypi.org/project/lxml/#files ). It would be great if the source distribution is also included in https://pypi.org/project/apache-airflow/#files

**Acceptance Criteria**
apache_airflow-2.0.0.tar.gz should be present in https://pypi.org/project/apache-airflow/#files

**Are you willing to submit a PR?**

Yes.

**Related Issues**

No

**Comment by mik-laj** [comment]
@gshiva  We don't use any native libraries, so it should make a difference whether you are installing from source code or prepackaged packages.

**Comment by potiuk** [comment]
Is there a reason you cannot use the .whl packages @gshiva ? Why it is important to you if the .whl package is equivalent?
Could you please elaborate on that?

**Comment by gshiva** [comment]
Our automated build system relies on the sdist packages and our security team has issues with blindly importing "binary" packages. Similar to reasons described in #13498 

Also thank you @potiuk and @mik-laj for such a quick response.

**Comment by kaxil** [comment]
Fixed in 2.0.1

**Comment by eldernewborn** [comment]
Thank you @kaxil  :) .
-Ali
