### ISSUE TITLE
Airflow 2.0.0 CLI "airflow dags trigger" doesn't support the --run_id parameter anymore

### ISSUE THREAD

**Issue by gbonazzoli** [apache/airflow#13476]
**Description**

Airflow 2.0.0 changed it's command line syntax in order to leverage it REST interface and it's well done. But I miss a very little switch that is the `--run_id` parameter in the `airflow dags trigger`

**Use case / motivation**

The use case is simple. An external bash script submit to airflow hundreds of dags every evening. A human operator the next morning checks the ones that failed, and the `--run_id` quickly identifies what had gone wrong.

**Are you willing to submit a PR?**

I'm not able to write contribute, but I think it is only to accept in the API the missed parameter and expose it also in the CLI interface.

**Comment by gbonazzoli** [comment]
I found the solution, the switch in Airflow 2.0.0 has been renamed in --run-id from --run_id.

You can close the issue.

`
root@new-airflow:~/airflow/dags# airflow dags trigger -h
usage: airflow dags trigger [-h] [-c CONF] [-e EXEC_DATE] [-r RUN_ID] [-S SUBDIR] dag_id

Trigger a DAG run

positional arguments:
  dag_id                The id of the dag

optional arguments:
  -h, --help            show this help message and exit
  -c CONF, --conf CONF  JSON string that gets pickled into the DagRun's conf attribute
  -e EXEC_DATE, --exec-date EXEC_DATE
                        The execution date of the DAG
  -r RUN_ID, --run-id RUN_ID
                        Helps to identify this run
  -S SUBDIR, --subdir SUBDIR
                        File location or directory from which to look for the dag. Defaults to '[AIRFLOW_HOME]/dags' where [AIRFLOW_HOME] is the value you set for 'AIRFLOW_HOME' config you set in 'airflow.cfg' 
`

**Comment by mik-laj** [comment]
I would like to add that all changes to the CLI are described in the documentation
https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#airflow-cli-changes-in-2-0
