### ISSUE TITLE
dag_stats are empty when runs complete via `airflow backfill` or `airflow run`, since dag_runs are not generated for those commands!

### ISSUE THREAD

**Issue by dgies** [apache/airflow#1348]
I was trying out 1.7.1rc1 and noticed that on the home page none of the dag stats were being populated.
Digging deeper I found out this was because this commit introduced filtering to show only stats for the most recent or current dag run:
https://github.com/airbnb/airflow/commit/7a0d4a1aedabd89b3162426427aa72f828680598#diff-948e87b4f8f644b3ad8c7950958df033

The problem with this is a Dag may have TaskInstances but no DagRuns if it gets executed either by backfills or individual task run commands.  

The dag_stats query should be changed to include all TaskInstances from Dags which do not have any DagRuns.

**Comment by r39132** [comment]
Please add screen shots of the overview page, dag runs page, and tree view for posterity.

**Comment by r39132** [comment]
This queries behavior changed in : https://github.com/airbnb/airflow/commit/7a0d4a1aedabd89b3162426427aa72f828680598#diff-948e87b4f8f644b3ad8c7950958df033

**Comment by r39132** [comment]
@bolkedebruin @jtschoonhoven @mistercrunch Please review. This modifies some changes made in https://github.com/airbnb/airflow/issues/974

**Comment by dgies** [comment]
**BEFORE FIX**

![before](https://cloud.githubusercontent.com/assets/4491601/14444453/78d166b8-fffa-11e5-840c-d0d4779fbe34.png)

**AFTER FIX**

![after](https://cloud.githubusercontent.com/assets/4491601/14444454/7c507ea0-fffa-11e5-8448-0cc7a23f3ac1.png)

**Comment by r39132** [comment]
@dgies To be clear, the status circles that appear after your fix reflect what exactly?

**Comment by dgies** [comment]
A related (and apparently untracked) issue is that backfills do not create any DagRuns.  Even if that were fixed, we should still include stats on TaskInstances without DagRuns because users may have created them via the run command.

**Comment by dgies** [comment]
@r39132 Those are the stats of the TaskInstances for those Dags which were created as a result of backfill commands (or occasionally standalone run commands).

**Comment by r39132** [comment]
Interesting, we mention the need to fix something we feel is broken in the `airflow backfill` and `airflow run` : we want them to create dag runs so we don't run into these weird issues: https://github.com/airbnb/airflow/wiki/Roadmap under `Backfill offers a parallel code path to scheduling - Champion : Jeremiah & Sid`

**Comment by dgies** [comment]
I think backfills creating dag runs will handle the empty dag_stats issue just fine.  

I see another problem with the fix for #974: The dag_stats are being filtered by most recent run, but the destination link of those stats filters on just the dag_id and state, including instances for all runs.  This means if I had a dag with 1 task and 10 successful runs, the stats circle would show 1, but link to a TaskInstance report showing 10 records.  If we're going to keep the logic of filtering stats based on DagRuns, we'll probably need to update those links to filter on execution_date too.

**Comment by bolkedebruin** [comment]
See AIRFLOW-20. Please create a Jira issue for this and link it to AIRFLOW-20. Thanks!
