### ISSUE TITLE
Airflow worker logs 404 Client Error

### ISSUE THREAD

**Issue by caoquyvu** [apache/airflow#13483]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`): Linux my-private-domain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
When the failed task and the success task in a DAG run in multiple worker, i just can see the latest logs of a task run
Cannot see logs of failed task

![ảnh](https://user-images.githubusercontent.com/19485589/103630512-55d8bc00-4f74-11eb-9686-c81b642096be.png)

![ảnh](https://user-images.githubusercontent.com/19485589/103630532-60935100-4f74-11eb-91fe-1f6b336d0f1e.png)

**What you expected to happen**:
Can see logs of previous failed task with diffferent worker host with the success task in a DAG run

I think airflow webserver get the host of latest success task. And when we try to see previous failed task log of this successed task, airflow try to give host of this success task to this failed task

**How to reproduce it**:
A task run with multiple retries, and a queue host this DAG run in multiple host

**Anything else we need to know**:

**Comment by eladkal** [comment]
You are using EOL version of Airflow.
Please let us know if the issue is reproducible in latest airflow version

**Comment by caoquyvu** [comment]
> You are using EOL version of Airflow. Please let us know if the issue is reproducible in latest airflow version

Using airflow 2.0.1 and still get the error
