### ISSUE TITLE
MSSQL to GCS Operator has no support for FLOAT field types when generating the schema

### ISSUE THREAD

**Issue by johnwesonga** [apache/airflow#13480]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: GCP Compute Engine
- **OS** (e.g. from /etc/os-release): Ubuntu Linux
- **Kernel** (e.g. `uname -a`):  SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Extract data containing float values in JSON format from MSSQL (Cloud SQL) to GCS using the MsSqlToGoogleCloudStorageOperator. The Schema generated sets the field type to integer and during import to BigQuery this fails with the error below

`'message': 'Error while reading data, error message: JSON parsing error in row starting at position 140815647: Could not convert value \'number_value: "0.0"\' to integer. Field: Credit; Value: 0.0'}]
`
**What you expected to happen**:

Schema should have set this field type to FLOAT

mssql_to_gcs only seems to have support for INTEGER, TIMESTAMP and NUMERIC. This https://github.com/apache/airflow/pull/11540 PR adds support for DATETIME conversion and field type but is yet to be merged into main.

**How to reproduce it**:

Connect to MSSQL (Cloud SQL or a local instance) and use MsSqlToGoogleCloudStorageOperator and run task to extract data with float values from table. Run another task using GoogleCloudStorageToBigQueryOperator to import the data to BigQuery.

**Anything else we need to know**:

**Comment by shahar1** [comment]
@eladkal Please assign me

**Comment by eladkal** [comment]
Closing as not reproduceable.
#28937 will improve docs around it
