### ISSUE TITLE
Unable to view StackDriver logs in Web UI

### ISSUE THREAD

**Issue by mcgin** [apache/airflow#13494]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.16.15-gke.4901

**Environment**:

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: Using the apache/airflow docker image
- **Others**: Running 1 pod encapsulating 2 containers (1 x webserver and 1x scheduler) running in localexecutor mode

**What happened**:

I have remote logging configured for tasks to send the logs to StackDriver as per the below configuration.  The logs get sent to Stackdriver okay and I can view them via the GCP console.  However I cannot view them when browsing the UI.

The UI shows a spinning wheel and I see requests in the network tab to 
`https://my_airflow_instance/get_logs_with_metadata?dag_id=XXX......`

These requests take about 15 seconds to run before returning with HTTP 200 and something like this in the response body:

```
{"message":"","metadata":{"end_of_log":false,"next_page_token":"xxxxxxxxx"}}
```

So no actual log data

**What you expected to happen**:

I should see the logs in the Web UI

**How to reproduce it**:

Configure remote logging for StackDriver with the below config:

```
  AIRFLOW__LOGGING__GOOGLE_KEY_PATH: "/var/run/secrets/airflow/secrets/google-cloud-platform/stackdriver/credentials.json"
  AIRFLOW__LOGGING__LOG_FORMAT: "[%(asctime)s] {{%(filename)s:%(lineno)d}} %(levelname)s - %(message)s"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "stackdriver://airflow-tasks"
```

**Anything else we need to know**:

**Comment by mik-laj** [comment]
It could be related: https://github.com/apache/airflow/issues/13343

**Comment by mcgin** [comment]
It's possible @mik-laj although the symptoms seem a little different, in the referenced issue the logs are retrieved (although garbled), here I'm not seeing any logs at all retrieved.

**Comment by mcgin** [comment]
I've just left the window open for a very long time with the UI polling the get_logs_with_metadata endpoint.  I do finally see a response containing some log information in the "message" after about 10 minutes in the network tab (I can see the logs in Stackdriver much earlier than this, so it's not that the job was running and only logged then).

Interestingly the UI doesn't update with the log message when it does finally arrive.  So I think there is actually 2 things happening here:

- The logs are taking 10 minutes to appear via the API resulting in a lot of polling requests of approx 15/16 seconds 
- The UI is not updating when the first logs are received are empty.

**Comment by eduartua** [comment]
@mcgin Could you tell me if you ever go this working?
I'm having the same issue.
Airflow config
```
Apache Airflow
version                | 2.2.2
executor               | KubernetesExecutor
task_logging_handler   | airflow.providers.google.cloud.log.stackdriver_task_handler.StackdriverTaskHandler
sql_alchemy_conn       | postgresql://airflow:PASSW@IP:5432/airflow?sslmode=disable
dags_folder            | /opt/airflow/dags/repo/dags
plugins_folder         | /opt/airflow/plugins
base_log_folder        | /opt/airflow/logs
remote_base_log_folder | stackdriver://airflow
```
error
```
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/zelus-basketball-dev.svc.id.goog/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\nb'Not Found\\n'", <google.auth.transport.requests._Response object at 0x7ff67be7fac0>)

ERROR - AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7ff67be628e0>" raised exception!"
```
When I inspect the network tab I get 
```
{"message":"","metadata":{"end_of_log":false,"next_page_token":"xxxxxxxxx"}}
```
Also, I'm using Workload Identity and the pods have the `logging.Viewer` role.
