### ISSUE TITLE
Update slackapiclient / slack_sdk to v3

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13515]
Hello,

Slack has released updates to its library and we can start using it for it. 

We especially like one change.

> slack_sdk has no required dependencies. This means aiohttp is no longer automatically resolved.

I've looked through the documentation and it doesn't look like a difficult task, but I think it's still worth testing.
More info: https://slack.dev/python-slack-sdk/v3-migration/index.html#from-slackclient-2-x

Best regards,
Kamil Breguła

**Comment by jyotidhiman0610** [comment]
Can I take this up?

**Comment by mik-laj** [comment]
@jyotidhiman0610 I assigned you to this ticket ;-)
