### ISSUE TITLE
Task Duration seems missing for task_duration < 1 sec

### ISSUE THREAD

**Issue by yogyang** [apache/airflow#13528]
**Apache Airflow version**: 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): no k8s

**Environment**:

- **Cloud provider or hardware configuration**: ec2
- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`): Linux airflow-dev-01 4.4.0-1118-aws #132-Ubuntu SMP Fri Nov 13 18:22:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Task Duration seems missing for task_duration < 1 sec

for task_duration < 1 sec
![image](https://user-images.githubusercontent.com/33287576/103853009-159a4a80-50e8-11eb-9d1a-6d409de1f65e.png)

db record:
![image](https://user-images.githubusercontent.com/33287576/103853152-5eea9a00-50e8-11eb-94b4-9edc601f3a06.png)

fro task_duration > 1 sec
![image](https://user-images.githubusercontent.com/33287576/103853079-3662a000-50e8-11eb-9d14-186a5f449d6f.png)

**What you expected to happen**:

Task duration should show up like it was in Airlfow 1.10.9
![image](https://user-images.githubusercontent.com/33287576/103853200-7a55a500-50e8-11eb-9d92-1c275303d34b.png)

**How to reproduce it**:

If this is a UI bug
build a dag with a dummy operator

**Anything else we need to know**:

**Comment by yogyang** [comment]
assign it to myself @yogyang

**Comment by bbovenzi** [comment]
I'm moving all our js from inline to their own files. I did see an issue with how we are getting the value for `duration`. I can put in a fix once the js migration is done.

**Comment by ryanahamilton** [comment]
Resolved by #13528
