### ISSUE TITLE
Airflow v1 REST List task instances api can not get `no_status` task instance

### ISSUE THREAD

**Issue by li1234yun** [apache/airflow#13531]
**Apache Airflow version**:
2.0

**Environment**:

- **OS** ubuntu 18.04
- **Kernel** 5.4.0-47-generic

**What happened**:
When I use list task instances REST api, I can not get the instances that status is `no_status`. 

```
### Get Task Instances
POST  {{baseUrl}}/dags/~/dagRuns/~/taskInstances/list
Authorization: Basic admin:xxx
Content-Type: application/json

{
  "dag_ids": ["stop_dags"]
}

or 

{
    "dag_ids": ["stop_dags"],
    "state": ["null"]
}
```

**What you expected to happen**:
include all state task instances when I don't have specific states.

**How to reproduce it**:
use REST test tools like postman to visit the api.

**Anything else we need to know**:
I can not find the REST api that I get all the dag runs instances with specific state, maybe should extend the REST api.

Thanks!

**Comment by ephraimbuddy** [comment]
I have not been able to reproduce this. @mik-laj can you take a look?

**Comment by mik-laj** [comment]
The field `state` is nullable
https://github.com/apache/airflow/blob/26ad55beb00f5a0915ba4bec541e3d67044834e9/airflow/models/taskinstance.py#L333
In API, we use `IN` statement to filter elemenets.
https://github.com/apache/airflow/blob/26ad55beb00f5a0915ba4bec541e3d67044834e9/airflow/api_connexion/endpoints/task_instance_endpoint.py#L144
https://github.com/apache/airflow/blob/26ad55beb00f5a0915ba4bec541e3d67044834e9/airflow/api_connexion/endpoints/task_instance_endpoint.py#L76-L79
Unfortunately, the IN expression never finds an element that is NULL. We need to handle this case and detect "NULL" / "NO_STATUS"/"NONE"(preferred) in the expression and build a more complex query that will contain the IS NULL expression.
When I looked at this field, I also noticed another problem with this field. We miss enum values validation.
https://github.com/apache/airflow/pull/19105/files#r744343850
