### ISSUE TITLE
503 Service Unavailable: No server is available to handle this request.

### ISSUE THREAD

**Issue by jazz215** [apache/airflow#13546]
Hi, my ml script running on airflow has stopped working from 29th December. When I click on the server access, i get the above error.

Does anybody else is getting this error recently?

**Comment by vikramkoka** [comment]
I am sorry, but can you please give me some more information, so that we can identify the problem?
This generally indicates a temporary problem.

**Comment by ashb** [comment]
Closing due to no response. We can reopen this if we get more details.
