### ISSUE TITLE
`ImportChangesRule` raises false positives

### ISSUE THREAD

**Issue by jecolvin** [apache/airflow#13570]
**Apache Airflow version**: 1.10.14, apache-airflow-upgrade-check==1.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: on-premise Linux server
- **OS** (e.g. from /etc/os-release): RHEL 7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: 

Running `airflow upgrade_check` gives a series of false positives for the import check rule. For example:

```
('Using `airflow.contrib.hooks.sftp_hook.SFTPHook` should be replaced by '
 '`airflow.providers.sftp.hooks.sftp.SFTPHook`. Affected file: '
 '/airflow/dags/std_wsljobs_dags/hccmodel_dag.py')
```

However, this import has actually already been updated in the indicated file, and when viewing the code using the "Code" button in the Airflow UI it shows the updated path.

**What you expected to happen**:

That this file would not be flagged by the ImportChangesRule.

**How to reproduce it**:

Run `airflow upgrade_check` with a DAG file containing one of the classes whose import path changed.

**Anything else we need to know**:

I believe the culprit is this section from the ImportChangesRule:

```
  @staticmethod
  def _check_file(file_path):
      problems = []
      providers = set()
      with open(file_path, "r") as file:
          content = file.read()
          for change in ImportChangesRule.ALL_CHANGES:
              if change.old_class in content:
                  problems.append(change.info(file_path))
                  if change.providers_package:
                      providers.add(change.providers_package)
      return problems, providers
```

It is only checking the the `old_class` is present, not the `old_path`. The if statement should read: `if change.old_path in content:`. If I make this change in the source file, I receive zero problems back instead of 39.

**Comment by mik-laj** [comment]
Are you willing to create PR? I am happy to help with the review.

**Comment by yergi** [comment]
Yes, I just created this PR. It's my first time ever contributing to an open-source project, so please be gentle. 😄

**Comment by zappallot** [comment]
I had the same problem with too many false positives and applied change proposed.
Problem is, it now does not find import statements like this:
`from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator`
because `change.old_path` would expect a string like `airflow.contrib.operators.kubernetes_pod_operator.KubernetesPodOperator`.

Changing `change.old_path` to `".".join(change.old_path.split(".")[0:-1])` worked for me, as it cuts away the classname from the path. But I cannot say if this is good enough for the checker, but just `changes.old_path` would find not enough deprecated imports.

**Comment by eladkal** [comment]
@yergi can you please check if https://github.com/apache/airflow/pull/14493 solves your issue?

**Comment by eladkal** [comment]
@yergi were you able to verify ?

**Comment by yergi** [comment]
Yes this did it. Thank you!!

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
