### ISSUE TITLE
S3FileTransformOperator has side effects on each instantiation, queries DB on each scheduler run

### ISSUE THREAD

**Issue by underyx** [apache/airflow#1357]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet): 1823f9d4531860e45bfcd88c6d3820edba4491a8
### Description of Issue

Defining a task should not have any side effects, but it looks like `S3FileTransformOperator` creates the S3 hooks upon instantiation here: https://github.com/airbnb/airflow/blob/1823f9d4531860e45bfcd88c6d3820edba4491a8/airflow/operators/s3_file_transform_operator.py#L60-61

Instantiation therefore fires the following:
- [DB queries to get the AWS credentials for both source and destination hooks.](https://github.com/airbnb/airflow/blob/1823f9d4531860e45bfcd88c6d3820edba4491a8/airflow/hooks/S3_hook.py#L97)
- [HTTP requests to authenticate to Amazon in some cases.](https://github.com/airbnb/airflow/blob/1823f9d4531860e45bfcd88c6d3820edba4491a8/airflow/hooks/S3_hook.py#L175)

If I'm not wrong, this means that each scheduler run will do the above stuff. And, well, that's not very nice.

I did not actually test this, just read through the code, so I could be totally mistaken.

**Comment by bolkedebruin** [comment]
This is a bug indeed. Can you submit a pr?

**Comment by underyx** [comment]
Sure, why not.
