### ISSUE TITLE
Rewrite Kubernetes tests to new Stable API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13588]
Hello friends!

Today I come with another small ticket.  Our tests for Kubernetes use old and deprecated "Experimental API". 
https://github.com/apache/airflow/blob/809ddcda73c1a7ee30f3273d7cab08f4e8642095/kubernetes_tests/test_kubernetes_executor.py#L106
It would be great if we could rewrite these tests to use the new "Stable API v1".

Migration Guide from Experimental API to Stable API v1
https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#migration-guide-from-experimental-api-to-stable-api-v1
It is worth paying attention to authorizations because a stable API requires a user in the database. See: https://github.com/apache/airflow/pull/13568
Fortunately, Helm Chart can create a user account.

Best regards,
Kamil Breguła

**Comment by potiuk** [comment]
Just one comment to that. I think this will only be possible if we make a decision that the helm chart should only support 2.0+. Which I think is a good idea, but I think we need to propose it and discuss at the devlist.

**Comment by mik-laj** [comment]
Do these tests run image for Airflow 1.10.14? I think they're using the newest production image.
https://github.com/apache/airflow/tree/master/kubernetes_tests

**Comment by potiuk** [comment]
So far all those tests are continuously cherry-picked to v1-10-test/stable and are also run there to test that it works.

**Comment by mik-laj** [comment]
So I'm closing this ticket. We can come back to this when we drop support for Airflow 1.10

> The Airflow 1.10.x release tree will be supported for a limited time after the GA release of Airflow 2.0 to give users time to upgrade from one of the Airflow 1.10.x releases. Specifically, only "critical fixes" defined as fixes to bugs that take down Production systems, will be backported to 1.10.x core for six months after Airflow 2.0.0 is released.

https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#support-for-airflow-1-10-x-releases

In six months' time, we will stop supporting Airflow 1.10 completely, so this is also a good time to rewrite it.
