### ISSUE TITLE
SendGrid - Support secrets backend 

### ISSUE THREAD

**Issue by eugenemiretsky** [apache/airflow#13618]
**Description**

Allow configuring SendGrid using secrets backend

**Use case / motivation**

Right now to configure SendGrid one has to set 
SENDGRID_MAIL_FROM={your-mail-from}
 SENDGRID_API_KEY={your-sendgrid-api-key}

However, one GCP that would mean that the variables need to be added in the UI. 

Instead of reading the configs from OS env vars (os.environ.get) the configs should be read as a Variable so that a secrets backend can be used to store them. 

**Are you willing to submit a PR?**

Yes

**Related Issues**

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/pull/13601 

Can you look at it?

**Comment by vikramkoka** [comment]
@eugenemiretsky Can you please confirm that the above referenced PR closes this?
