### ISSUE TITLE
SSHOperator returns last line for xcom_push, not full results

### ISSUE THREAD

**Issue by btallman** [apache/airflow#1361]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet):
- Airflow Version 1.7
- Scheduler with Local Executor against RDS Postgres

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue
- What did you expect to happen? SSHOperator returns only the last line of the results of the bash command for and xcom_push. I expected the full results.
### Reproduction Steps
1. Any SSHOperator with xcom_push=True.

**Comment by bolkedebruin** [comment]
Please create Jira if you still think this is an issue.
