### ISSUE TITLE
Airflow Operator "GoogleCloudStorageToBigQueryOperator" - BQ data load through External Source Partitioning [Hive Partitioning]

### ISSUE THREAD

**Issue by mbettan** [apache/airflow#13626]
**Description**

Composer Airflow Operator "GoogleCloudStorageToBigQueryOperator" needs the functionality to support BQ data load through External Source Partitioning [Hive Partitioning]

**Use case / motivation**

Ability to ingest data from data sources with years historical data into Google BigQuery for analytics purposes - we would like to support data load through External Source Partitioning [Hive Partitioning]

**Are you willing to submit a PR?**

N/A

**Related Issues**

BQ Load Bash Operator is the workaround but introduced other issues with the Airflow connection ID usage.

**Comment by mik-laj** [comment]
Have you tried to use BigQueryInsertJobOperator? for example, see: https://github.com/apache/airflow/pull/13598

**Comment by smowden** [comment]
check out the docs here:
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad
if you insert a load job (see #13598) you should be able to prive hivePartitioningOptions:
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#HivePartitioningOptions

**Comment by mik-laj** [comment]
This looks like an invalid ticket.

**Comment by mbettan** [comment]
Thank you @mik-laj - this solved my issue we used as alternative: BigQueryInsertJobOperator
