### ISSUE TITLE
Misleading dag pause info tooltip 

### ISSUE THREAD

**Issue by eldernewborn** [apache/airflow#13624]
**Apache Airflow version**:
2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:
N/A

**What happened**:
The UI tooltip is misleading and confuses the user.
Tooltip says " use this toggle to pause the dag" which implies that if the toggle is set to **ON** the flow is paused, but in fact it's the reverse of that.
Either the logic should be reversed so that if the toggle is on, the DAG is paused, or the wording should be changed to explicitly state the actual functionality of the "on state" of the toggle.
something like "When this toggle is ON, the DAG will be executed at scheduled times, turn this toggle off to pause executions of this dag ".

**What you expected to happen**:
UI tooltip should be honest and clear about its function. 

**How to reproduce it**:
open DAGs window of the airflow webserver in a supported browser, hold mouse over the (i) on the second cell from left on the top row.
<img width="534" alt="Screen Shot 2021-01-11 at 12 27 18 PM" src="https://user-images.githubusercontent.com/14813957/104258476-7bfad200-5434-11eb-8152-443f05071e4b.png">

**Comment by mik-laj** [comment]
Are you willing to submit a PR?

**Comment by kaxil** [comment]
That is not entirely mis-leading, as a DAG can be paused/unpaused at creation based on what is set in `[core] dags_are_paused_at_creation`. 

https://github.com/apache/airflow/pull/13642 just makes it clearer that the toggle is used for pausing and unpausing -- but I still think it was not required
