### ISSUE TITLE
HiveCliHook kill method error

### ISSUE THREAD

**Issue by c-hui** [apache/airflow#13629]
https://github.com/apache/airflow/blob/6c458f29c0eeadb1282e524e76fdd379d6436824/airflow/providers/apache/hive/hooks/hive.py#L464

It should be:
```
if hasattr(self, 'sub_process')
```

**Comment by mirelagrigoras** [comment]
Hi, @c-hui! If you did not start working on it yet, I could pick it up and create a PR for this.
