### ISSUE TITLE
Improve annotations customization in the chart

### ISSUE THREAD

**Issue by FloChehab** [apache/airflow#13643]
**Description**

As discussed in https://github.com/apache/airflow/pull/13616#issuecomment-758234146, we would need to improve the customization of annotations across all objects of the chart.

**Use case / motivation**

We often need to paremetrize the annotations and we would rather do it in one PR with all the objects rather than one small PR everytime.

**Are you willing to submit a PR?**

@mik-laj I am ready to be assigned.

**Related Issues**
Not to my knowledge.

-----

What need to be tackled before starting dev:

* [ ] On what objects do we want annotations?
* [ ] What terminology do we choose in the values.yaml? (`annotations` or `extraAnnotations` or both or something else?)
* [ ] Have a table with the mapping of each object and the value path for the annotation parametrization?
* [ ] Should we drop the value airflowPodAnnotations ?

**Comment by FloChehab** [comment]
**First:**

Objects that should have parametrizable annotations:
* Pod (inside deployment and StatefulSet),
* Service,
* ServiceAccount,
* Ingress.

Is this list too much ? Am I missing something?

**Comment by FloChehab** [comment]
(I have added more info in the issue description, feel free to it)

**Comment by mik-laj** [comment]
@dimberman @XD-DENG @potiuk Do you have any thoughts on this? I saw that these changes often come back in different forms, and I think we can do it once, but good.

**Comment by XD-DENG** [comment]
Absolutely a good idea 👍

**Comment by potiuk** [comment]
Absolutely !

**Comment by mik-laj** [comment]
We have a ticket that improves the annotation handling for SA a bit. Anyone willing to do a review and say if this change is sufficient for this ticket as well?
https://github.com/apache/airflow/pull/11769

**Comment by FloChehab** [comment]
Hello,

Regarding the terminology

> What terminology do we choose in the values.yaml? (annotations or extraAnnotations or both or something else?)

I checked the chart and `extraAnnotations` is only used when there are other annotations related to prometheus that are already present (for the pgbouncer-service & the statsd-service). My position on this would be to remove such annotations related to prometheus and use the `annotations` terminology everywhere.

**Comment by FloChehab** [comment]
Hello, just wanted to let you now that I should have time to work on this issue in couple of weeks.

**Comment by dimberman** [comment]
@FloChehab awesome! Please let us know when it's ready to review :)

**Comment by FloChehab** [comment]
Hello, time flies! 

I am going to have a quick lool at #15238 ; also, some related work seems to be going on in https://github.com/apache/airflow/pull/14152 .

**Comment by dimberman** [comment]
@FloChehab sounds good let me know where I can help!
