### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by tuusberg** [apache/airflow#1364]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow: 1.7.0
- Airflow components and configuration: CeleryExecutor, Redis for broker, MySQL for tasks
- Operating System: Ubuntu 14.4
- Python Version: 2.7.9
### The issue:

We are using airflow to verify the data that is coming from the api. The api has limits (16 requests per second), so we are using `concurrency` parameter to limit the number of running tasks.

However, worker often creates more than 1 subprocess (normally 2) for a certain task. This behaviour is unpredictable, so we are not able to run things in parallel.

```
ps aux | grep airflow
/bin/sh -c airflow run /usr/bin/python /usr/local/bin/airflow run <task name> <args> --local -sd <dag path>
/usr/bin/python /usr/local/bin/airflow run <task name> <args> --local -sd <dag path>
/usr/bin/python /usr/local/bin/airflow run <task name> <args> --job_id <id> --raw -sd <dag path>
```

Is there any key setting I'm missing? Please advice.

**Comment by jlowin** [comment]
Airflow will create multiple subprocesses for a task, but the task's `execute()` method should only be called one time (that includes the `python_callable` of a `PythonOperator` or the `bash_command` of a `BashOperator`. 

However, if you're still seeing this behavior, what you may want to do is use a [Pool](http://pythonhosted.org/airflow/concepts.html#pools). Pools limit the number of tasks no matter what your global concurrency parameters are.

**Comment by henryon** [comment]
you can use queue to control the concurrency issues. like rabbitmq

**Comment by bolkedebruin** [comment]
Closing for now. Please create Jira issue if needed. Please note that 1.7.1 will still be able to oversubscribe to Pools - this is a known issue and will be fixed in a later release.
