### ISSUE TITLE
Airflow 1.10.11 to 1.10.14 not starting with SQLAlchemy 1.3.15

### ISSUE THREAD

**Issue by bharath12345** [apache/airflow#13646]
**Apache Airflow version**: 1.10.11 to 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): None

**Environment**: MacOS with Python v3.8

- **Cloud provider or hardware configuration**: None
- **OS** (e.g. from /etc/os-release): Mac OSX
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:

I get the following runtime error - 

> scheduler_1  | Process DagFileProcessor0-Process:
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
scheduler_1  |     cursor, statement, parameters, context
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
scheduler_1  |     cursor.execute(statement, parameters)
scheduler_1  | pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
scheduler_1  |
scheduler_1  | The above exception was the direct cause of the following exception:
scheduler_1  |
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
scheduler_1  |     self.run()
scheduler_1  |   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
scheduler_1  |     self._target(*self._args, **self._kwargs)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 159, in _run_file_processor
scheduler_1  |     pickle_dags)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
scheduler_1  |     return func(*args, **kwargs)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 1593, in process_file
scheduler_1  |     paused_dag_ids = models.DagModel.get_paused_dag_ids(dag_ids=dagbag.dag_ids)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
scheduler_1  |     return func(*args, **kwargs)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/airflow/models/dag.py", line 1808, in get_paused_dag_ids
scheduler_1  |     .filter(DagModel.dag_id.in_(dag_ids))
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3244, in all
scheduler_1  |     return list(self)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
scheduler_1  |     return self._execute_and_instances(context)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
scheduler_1  |     result = conn.execute(querycontext.statement, self._params)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
scheduler_1  |     return meth(self, multiparams, params)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
scheduler_1  |     return connection._execute_clauseelement(self, multiparams, params)
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
scheduler_1  |     distilled_params,
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
scheduler_1  |     e, statement, parameters, cursor, context
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
scheduler_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
scheduler_1  |     cursor, statement, parameters, context
scheduler_1  |   File "/usr/src/python-app/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
scheduler_1  |     cursor.execute(statement, parameters)
scheduler_1  | sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
scheduler_1  | [SQL: SELECT dag.dag_id AS dag_dag_id
scheduler_1  | FROM dag
scheduler_1  | WHERE dag.is_paused IS 1 AND dag.dag_id IN (?)]
scheduler_1  | [parameters: ('SendResults',)]
scheduler_1  | (Background on this error at: http://sqlalche.me/e/f405)

**Anything else we need to know**:
Have tried with newer SQLAlchemy versions too but with no luck

**Comment by potiuk** [comment]
Airflow does now work with MsSQL server. If you see at the requirements: https://github.com/apache/airflow#requirements you need either Postgres or MysQL (sqlite is good for development). There is a discussion about adding support for #Mssql but there are no plans to implemeent it. See https://github.com/apache/airflow/issues?q=is%3Aissue+is%3Aopen+mssql+label%3Awish%3Amssql-support
