### ISSUE TITLE
Password is unintendedly changed when editing a connection

### ISSUE THREAD

**Issue by soltanianalytics** [apache/airflow#13656]
**Apache Airflow version**: 2.0.0

**What happened**:

When editing a connection - without changing the password - and saving the edited connection, a wrong password is saved.

**What you expected to happen**:

If I do not change the password in the UI, I expect that the password is not changed.

**How to reproduce it**:

- Create a new connection and save it (screenshots 1 + 2)
- Edit the connection without editing the password, and save it again (screenshots 3 + 4)

If you _do_ edit the password, the (new or old) password is saved correctly.

*Screenshot 1*
![image](https://user-images.githubusercontent.com/46958547/104480468-e5a9e600-55c4-11eb-8810-b3f033a750a4.png)

*Screenshot 2*
![image](https://user-images.githubusercontent.com/46958547/104480612-0e31e000-55c5-11eb-8aa7-6b9ecbb9a858.png)

*Screenshot 3*
![image](https://user-images.githubusercontent.com/46958547/104480726-29045480-55c5-11eb-8c93-43c05ba859fe.png)

*Screenshot 4*
![image](https://user-images.githubusercontent.com/46958547/104480770-39b4ca80-55c5-11eb-90d7-59be971ac53d.png)

(I blurred out the full string in the unlikely case that the full string might contain information on my fernet key or something)

**Comment by soltanianalytics** [comment]
Note: It seems that the unintended "new" password is always the _same_ string `RKk...jlx`

**Comment by potiuk** [comment]
@soltanianalytics  -> Do you have some software that auto-completes passwords or maybe chrome does it automatically? Your screenshots cut  the right side of the fields where you can have an indicator that the password have been auto-filled. 

 When I edit connections I got empty password and other sensitive fields when I edit them (even if password is actually set).

**Comment by soltanianalytics** [comment]
Yep, you're right, this is due to LastPass. It's actually my GUI admin password. This never was an issue before, I don't know if that's something you can have an influence over, but I'll close this issue

**Comment by potiuk** [comment]
No. It can be influenced. I believe we might fix it by setting autocomplete=off on all "*' fields

**Comment by potiuk** [comment]
Low priority, but worth fixing :)
