### ISSUE TITLE
Operator Extra Links not showing up on UI

### ISSUE THREAD

**Issue by hedrickw** [apache/airflow#13659]
**Apache Airflow version**: 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.18

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`): Linux
- **Install tools**:
- **Others**:

**What happened**: 
Followed the Example Here: https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html#define-an-operator-extra-link, and was expecting Link to show up on UI but it does not :( 
 
![image](https://user-images.githubusercontent.com/23406205/104509302-52f65080-559e-11eb-9459-2815f8bb5573.png)

```
class GoogleLink(BaseOperatorLink):
    name = "Google"

    def get_link(self, operator, dttm):
        return "https://www.google.com"


class MyFirstOperator(BaseOperator):
    operator_extra_links = (
        GoogleLink(),
    )
    @apply_defaults
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def execute(self, context):
        self.log.info("Hello World!")
        print(self.extra_links)

```

**What you expected to happen**: I expected a Button Link to show up in Task Instance Model

**How to reproduce it**: Follow Example here on Airflow 2.0 https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html#define-an-operator-extra-link

**Anything else we need to know**:

**Comment by ashb** [comment]
Operator links need to be registered via a plugin to appear in the UI -- sorry the docs are wrong on this point.

**Comment by hedrickw** [comment]
@ashb Ah that makes sense, thanks!

**Comment by potiuk** [comment]
Also you can do it via custom providers if you choose to bundle several custom operators into an installable python package: http://airflow.apache.org/docs/apache-airflow-providers/index.html#how-to-create-your-own-provider - that also adds a possibility to add custom connections.
