### ISSUE TITLE
Task is set "upstream_failed" while upstream tasks are success

### ISSUE THREAD

**Issue by doowhtron** [apache/airflow#13671]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: tencent cloud
- **OS** (e.g. from /etc/os-release): centos7
- **Kernel** (e.g. `uname -a`): 3.10
- **Install tools**:
- **Others**: Server version: 8.0.22 MySQL Community Server - GPL

**What happened**:

I have a dag of about a thousand tasks.  Task T has a few upstream tasks.  All the upstream tasks are success. But T is set "upstream_failed" and the whole dag is failed.

**What you expected to happen**:

Task T should be scheduled.

**How to reproduce it**:

I don't know how to reproduce it

**Anything else we need to know**:

It doesn't happen all the time and not always the same task.  Maybe the propability is about one third.

**Comment by vikramkoka** [comment]
Thank you for reporting this, but can you please add some more information and how to reproduce this. 
I can't think of how to proceed with this. We have run DAGs with more than a thousand tasks, so that is not by itself sufficient information.

**Comment by yuzeh** [comment]
For what it's worth, I'm seeing this on Airflow 2.1.3. Like the OP I can't precisely reproduce the situation but I can assure you it definitely happens.

**Comment by ctmikechen** [comment]
I have the same issue on Airflow 2.1.4 
any idea ?

**Comment by ephraimbuddy** [comment]
We fixed this in https://github.com/apache/airflow/pull/17819, upgrade to the latest airflow(2.2.2)
