### ISSUE TITLE
API Endpoints - /xcomEntries/{xcom_key} - doesn't return value

### ISSUE THREAD

**Issue by andrzejsydor** [apache/airflow#13676]
**Apache Airflow version**: 2.0.0

**What happened**:

Using endpoint `/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}` I got Response Body but without `value` entry. Like:
```
{
  "dag_id": "string",
  "execution_date": "string",
  "key": "string",
  "task_id": "string",
  "timestamp": "string"
}
```
Instead of:
```
{
  "dag_id": "string",
  "execution_date": "string",
  "key": "string",
  "task_id": "string",
  "timestamp": "string",
  "value": "string"
}
```
The exact value by defined `key` exists.

**Comment by kaxil** [comment]
Will be fixed in 2.0.1, thanks for reporting
