### ISSUE TITLE
Dags are not able to get connections via hashicorp_vault

### ISSUE THREAD

**Issue by lassanouer** [apache/airflow#13672]
Using Hashicorp_vault was a good idea to make things safe and easy for airflow users,

my airflow version: 1.10.14

**Use case:**
Create a secret X in vault, config airflow to get that connections
Create a 2 dags,
    

- in first one, u call the connection X that you create in vault
- the second one, call a connection Y that is not in vault

launch airflow,

==> In user interface, there is only error to get Y connection, and when i launch the dag :
get_connections raise AirflowException("The conn_id `{0}` isn't defined".format(conn_id))

i've debug that and i found out that if i call get_conn_uri from hashicorp_vault i got the connection... 
so the real probleme isn't in vault connection, but in airflow.secrets calling secretes

**Comment by kaxil** [comment]
The error is genuine though, have you added a connection Y in either Metadata DB or as Environment Variable.

If no-one of this, then it will error

**Comment by lassanouer** [comment]
my issue is when i use vault for connections, it doesn't work.
the connection Y case is to show that from the user interface, airflow is recognizing the connection X and doesn't show error for it.

**Comment by kaxil** [comment]
> my issue is when i use vault for connections, it doesn't work.
> the connection Y case is to show that from the user interface, airflow is recognizing the connection X and doesn't show error for it.

Can you post the steps to reproduce it?

**Comment by lassanouer** [comment]
Yeah,

1) create a secret X in vault in secrets/somewhere/in/vault for exemple

2) add this env var to airflow:
 - name: AIRFLOW__SECRETS__BACKEND
    value: "airflow.contrib.secrets.hashicorp_vault.VaultBackend"
  - name: AIRFLOW__SECRETS__BACKEND_KWARGS
    value: "{\"connections_path\": \"somewhere/in/vault\", \"mount_point\":\"secrets\", \"url\":\"https://vault.xxx.app\", \"role_id\":\"xxxxxxxxxx\", \"secret_id\":\"xxxxxxxxx\", \"auth_type\":\"approle\"}"

3) create a dag where you call this connection X in HttpSensor for example

**Comment by kaxil** [comment]
If possible, can you please also check with Airflow 2.0 ? and see if you can reproduce this

**Comment by kaxil** [comment]
I wasn't able to reproduce this, please try it with 2.0.1 -- We only backport critical fixes to 1.10.x now
