### ISSUE TITLE
BashOperator's on_success_callback process may be executed twice.

### ISSUE THREAD

**Issue by TajimaTheMemer** [apache/airflow#13687]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.16.15

**Environment**:

- **Cloud provider or hardware configuration**: GCP Cloud Composer (version: `composer-1.13.0-airflow-1.10.12`)
- **OS** (e.g. from /etc/os-release): linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
BashOperator's callback process `on_success_callback` is sometimes executed twice at the same time.

**What you expected to happen**:
BashOperator's callback process `on_success_callback` should be executed only once.

**How to reproduce it**:
Run an arbitrary process that executes BashOprator's `on_success_callback` in a similar environment.

**Anything else we need to know**:
It happens roughly once every five times.
It has been confirmed that the callback process of GKEOprator & DummyOperator is always executed only once.

**Comment by kaxil** [comment]
Can you test it with the current Master branch and see if you can reproduce it there
