### ISSUE TITLE
Email config section is incorrect

### ISSUE THREAD

**Issue by cccs-cat001** [apache/airflow#13697]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**: This pertains to the docs

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I see [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html#email-configuration) it says to set `subject_template` and `html_content_template` under the email header, but in the [configuration references](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#email) it doesn't show those two fields. Have they been removed for some reason?

**Comment by kaxil** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html#email-configuration is correct -- you can add it too the airflow.cfg file. I have added the missing config to the docs in https://github.com/apache/airflow/pull/13709
