### ISSUE TITLE
Unexpected "Access denied" redirects using OAuth with Keycloak

### ISSUE THREAD

**Issue by FlorianWagnerZEB** [apache/airflow#13693]
**Apache Airflow version**: 1.10.12

**Kubernetes version**: Client: v1.15.11, Server: v1.19.3

**Environment**: Kubernetes for Docker Desktop

- **OS**: Windows 10 Pro
- **Airflow Base Image**: apache/airflow:1.10.12-python3.8

**What happened**:
When I log in using keycloak as OAuth provider I frequently (every few seconds) get "Access denied" messages followed by a redirect to the `/login` page, even when I request endpoints, which are allowed for my user role.
Mostly those endpoints that were already working a few seconds ago suddenly result in an "Access denied" message.

**What you expected to happen**:
The login should result in a stable session allowing me to perform all actions on the webinterface according to my user role.

**How to reproduce it**:

I activated OAuth authentication with my keycloak as oauth backend the following way:
Passed the following environment variable to all airflow pods:
`AIRFLOW__WEBSERVER__RBAC: 'True'`

Added the following packages to my airflow docker image:
`pip --no-cache-dir install oauthlib flask_oauthlib==0.9.5`

Changed my webserver_config.py to the following:
```
from flask_appbuilder.security.manager import (
    AUTH_OAUTH
)
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Admin"
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
    {
        "name":'azure',
        "icon": 'fa-windows',
        "token_key": "access_token",
        "remote_app": {
            "consumer_key":"xxxxxxxxx",
            "consumer_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "base_url":"https://our-company-keycloak/auth/realms/our-realm",
            "access_token_url": "https://our-company-keycloak/auth/realms/our-realm/protocol/openid-connect/token",
            "authorize_url": "https://our-company-keycloak/auth/realms/our-realm/protocol/openid-connect/auth",
            "request_token_params": {
                "scope": "openid"
            }
        }
    },
]
```
Since there is no option to use "keycloak" as a name for an OAuth provider, I used "azure" and configured my keycloak client to map the user information according to Azure's OAuth behavior.
In particular, the following mappings had to be made:
`email -> upn`
`first_name -> given_name`
`last_name -> family_name`
`id -> oid`
`username -> oid`

**Comment by potiuk** [comment]
@FlorianWagnerZEB  - this is rather 'troubleshooting" kind of question rather than bug. I am closing this issue for now, but please copy it and open [discussions[(https://github.com/apache/airflow/discussions). If you click "new issue" and see the "Ask a question or Get Support" - discussion is the link that is suggested there.

**Comment by mik-laj** [comment]
This also doesn't look like an Airflow setup issue but a Flask App builder issue. Can you try to get help there?
https://github.com/dpgaspar/Flask-AppBuilder/issues
