### ISSUE TITLE
Are these jobs running?

### ISSUE THREAD

**Issue by kevinmandich** [apache/airflow#137]
Hi there,

I ran this query on the database: `select * from job where state = 'running';`. It seems that several jobs are marked as "running", but this is not reflected on the front end. I also don't see any relevant processes running on the Airflow server. From the screenshot, it seems that some of the `latest_heartbeat` values are weeks old.

How can I check if these jobs are actually running? If they're not actually running, can I just update their `state` entries in the database?

<img width="1202" alt="screen shot 2015-07-14 at 6 35 54 pm" src="https://cloud.githubusercontent.com/assets/8010735/8688982/31624d52-2a57-11e5-8488-a93a1caca71b.png">

**Comment by mistercrunch** [comment]
If the `latest_heartbeat` is old, it means they aren't running. I have an `airflow_maintenance` DAG that includes a task that clears those.

**Comment by kevinmandich** [comment]
Does your `airflow_maintenance` DAG just delete from this table?

**Comment by mistercrunch** [comment]
I believe I mark them pessimistically as failed. 

`airflow_maintenance` also archives rows from the `task_instance` table based on jobs that got started more than 90 days ago into `task_instance_archive`

But you don't need to worry about archiving until you get a very large table, and even then...

**Comment by kevinmandich** [comment]
Gotcha. Thanks for the info.
