### ISSUE TITLE
ImportError: No module named 'pysqlite2'

### ISSUE THREAD

**Issue by xu-xiaoqiang** [apache/airflow#1370]
Dear Airflow Maintainers,

After install from pypi using pip：
pip install airflow
I am trying to initialize the database：
airflow initdb 
but I get this error：
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 4, in <module>
    from airflow import configuration
  File "/usr/local/lib/python2.7/site-packages/airflow/**init**.py", line 16, in <module>
    from airflow.models import DAG
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 40, in <module>
    from airflow import settings, utils
  File "/usr/local/lib/python2.7/site-packages/airflow/settings.py", line 62, in <module>
    engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/**init**.py", line 386, in create_engine
    return strategy.create(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2

and my python version is 2.7.10
Operating System:Linux hadoop123 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Python packages：
Babel==1.3
Flask==0.10.1
Flask-Admin==1.4.0
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-WTF==0.12
Jinja2==2.8
Mako==1.0.4
Markdown==2.6.6
MarkupSafe==0.23
Pygments==2.1.3
SQLAlchemy==1.0.12
WTForms==2.1
Werkzeug==0.11.5
airflow==1.7.0
alembic==0.8.5
chartkick==0.4.2
croniter==0.3.12
dill==0.2.5
future==0.15.2
gunicorn==19.3.0
itsdangerous==0.24
numpy==1.11.0
pandas==0.18.0
python-dateutil==2.5.2
python-editor==1.0
pytz==2016.3
requests==2.9.1
setproctitle==1.1.9
six==1.10.0
thrift==0.9.3
wsgiref==0.1.2

**Comment by bolkedebruin** [comment]
Please copy paste your airflow.cfg

**Comment by bolkedebruin** [comment]
Psqlite2 has been long time renamed to sqlite3 when it became part of Python. You seem to have some very old versions lying around?

**Comment by xu-xiaoqiang** [comment]
following is my airflow.cfg:
 [core]
airflow_home = /root/airflow

dags_folder = /root/airflow/dags

base_log_folder = /root/airflow/logs

s3_log_folder = None

executor = SequentialExecutor

sql_alchemy_conn = sqlite:////root/airflow/airflow.db

sql_alchemy_pool_size = 5

sql_alchemy_pool_recycle = 3600

parallelism = 32

dag_concurrency = 16

dags_are_paused_at_creation = False

max_active_runs_per_dag = 16

load_examples = True

plugins_folder = /root/airflow/plugins

fernet_key = cryptography_not_found_storing_passwords_in_plain_text

donot_pickle = False

dagbag_import_timeout = 30

[webserver]
base_url = http://localhost:8080

web_server_host = 0.0.0.0

web_server_port = 8080

secret_key = temporary_key

workers = 4

worker_class = sync

expose_config = true

authenticate = False

filter_by_owner = False

[email]
email_backend = airflow.utils.send_email_smtp

[smtp]
smtp_host = localhost
smtp_starttls = True
smtp_ssl = False
smtp_user = airflow
smtp_port = 25
smtp_password = airflow
smtp_mail_from = airflow@airflow.com

[celery]
celery_app_name = airflow.executors.celery_executor

celeryd_concurrency = 16

worker_log_server_port = 8793

broker_url = sqla+mysql://airflow:airflow@localhost:3306/airflow

celery_result_backend = db+mysql://airflow:airflow@localhost:3306/airflow

flower_port = 5555

default_queue = default

[scheduler]

job_heartbeat_sec = 5

scheduler_heartbeat_sec = 5

[mesos]

master = localhost:5050

framework_name = Airflow

task_cpu = 1

task_memory = 256

checkpoint = False

authenticate = False

**Comment by xu-xiaoqiang** [comment]
My system is centos6.5 and the python originally come with is 2.6.6. And I noticed the airflow is tested under python2.7.\* ,so I install the python2.7.10

**Comment by henryon** [comment]
thought you should find "_sqlite3.so" right? @xu-xiaoqiang
