### ISSUE TITLE
Build only one CI image and run less jobs for docs-only PRs

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#13706]
Hello,

In my [last PR](https://github.com/apache/airflow/pull/13696/files), which made changes to documentation only, I saw that CI was running a few jobs that are unnecessary.
See: https://github.com/apache/airflow/actions/runs/488961399

The following files has been changed:
```
docs/apache-airflow/howto/index.rst
docs/apache-airflow/howto/initialize-database.rst
docs/apache-airflow/howto/set-up-database.rst
docs/apache-airflow/installation.rst
docs/apache-airflow/redirects.txt
```

The following jobs were launched:
```
Build info
Wait for CI images
Verify CI Image Py3.6
Static checks
Pylint
Build docs
Backport packages: wheel
Backport packages: sdist
Provider packages wheel
Provider packages sdist
Test Provider packages with 2.0.0 version wheel
Test Provider packages with 2.0.0 version sdist
Wait for PROD images
Verify Prod Image Py3.6
Selective build check
Status of image build CI: 3.6
Status of image build PROD: 3.6
```

I guess we don't need to build a PROD image for similar changes and all we have to do is run a much smaller set of jobs.
```
Build info
Wait for CI images
Verify CI Image Py3.6
Static checks: basic checks only (instead of Static checks)
Build docs
Selective build check
Status of image build CI: 3.6
```

Best regards,
Kamil Breguła

**Comment by potiuk** [comment]
I think it's the right time to rewrite the selecitive_checks.sh script to python for that. Would you like to do it @mik-laj  ?

**Comment by potiuk** [comment]
It's totally independent of Breeze - so can be rewritten any time.

**Comment by mik-laj** [comment]
@potiuk I would love to do it, but I don't have the capacity yet. When I finish my current tasks, I'll try to rewrite it.

**Comment by potiuk** [comment]
Let's see who gets first some time :)

**Comment by eladkal** [comment]
I think this one is completed?
i checked few PRs with doc-only label (for release notes) and It invoked only the relevant doc test

**Comment by potiuk** [comment]
Yes. Done a long time ago.
