### ISSUE TITLE
Allow dags to be scheduled by solar events

### ISSUE THREAD

**Issue by Lyalpha** [apache/airflow#13701]
**Description**

Alongside existing `@daily` etc. preset cron configurations, a new suite of `schedule_interval` options would exist to cause a dag to be scheduled each day to coincide with a solar based event, e.g. `@sunset`, `@dusk_nautical`. 

**Use case / motivation**

Some workflows are diurnal or nocturnal by nature, an example is processing astronomical data. Particularly when far from the equator a single time per day can be significantly off from these solar events. These event-based schedules would prevent a long wait inside a task as a workaround.

The scheduler would be able to calculate when the next event matching the `schedule_interval` will occur and update the time a dag will be scheduled that day as such. 

An example implementation is shown by vanilla Celery [solar schedule](https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#solar-schedules). Will require:

* External dependency (e.g. [skyfield](https://github.com/skyfielders/python-skyfield)) required to calculate the times of events
* Some means of setting a latitude/longitude in configuration to fix the solar events for a position on Earth

**Are you willing to submit a PR?**

In the future, hopefully. It is unlikely to warrant entry into core airflow.

**Related Issues**

**Comment by vikramkoka** [comment]
@Lyalpha Please take a look at AIP-39 which is intended to introduce support for varied Scheduling timetables including your use case described above. 
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-39+Richer+scheduler_interval

**Comment by Lyalpha** [comment]
Yes, great. The support offered by AIP-39 would allow for this feature. I will monitor it and hopefully be able to contribute something via the new support for custom scheduling.

**Comment by eladkal** [comment]
Now that AIP-39 is finished, You can achieve that by using custom Timetables
https://airflow.apache.org/docs/apache-airflow/stable/concepts/timetable.html
