### ISSUE TITLE
Google Marketing Platform Display and Video 360 SDF Operators Fail

### ISSUE THREAD

**Issue by sarahamilton** [apache/airflow#13702]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Google Cloud Composer 1.13.3

- **Cloud provider or hardware configuration**: Google Cloud Composer

**What happened**: All Google Marketing Platform Display and Video 360 SDF operations fail (other than creating the SDF). The "GoogleDisplayVideo360GetSDFDownloadOperationSensor" fails every time it runs in any DAG I have tested with the error 'Resource' object has no attribute 'operation'. 

**What you expected to happen**: Given a valid SDF operation object that has been created, the operator should check if that object is ready to download. Then, the GoogleDisplayVideo360SDFtoGCSOperator should download the operation. However, the underlying hook that is being used is trying to reference an "operation" instead of "operations," per the SDF API specifications (see [here](https://developers.google.com/display-video/api/reference/rest/v1/sdfdownloadtasks.operations/get)). Thus, the requests always fail (as there is no "operation" attribute of the API).

**How to reproduce it**:

**Anything else we need to know**: The patch is very simple -- I have already tested by patching my code locally and confirming that the patch fixes the problem. I will submit a pull request shortly.

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/13703
