### ISSUE TITLE
Selective documentation build 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13716]
Followinq #13706 . 

Building docs only is not as optimized as it can be. 
I think it needs to have some separate behaviour not only optimising the other builds 
In case of the doc build we should not only optimise non-needed jobs, but also optimise which part of the documentation should be built.

In case of the https://github.com/apache/airflow/pull/13696/files 

```
docs/apache-airflow/howto/index.rst
docs/apache-airflow/howto/initialize-database.rst
docs/apache-airflow/howto/set-up-database.rst
docs/apache-airflow/installation.rst
docs/apache-airflow/redirects.txt
```

Only 'apache-airflow' docs should be built. 

Similarly when there are limited changes to provider packages (both doc and code).
If we see that we have change in docs/code for only some of the providers, we can take a look at this dependencies:
https://github.com/apache/airflow/blob/master/airflow/providers/dependencies.json

And only build documentation for those Providers that changed and their dependencies.  And we should do airflow documentation build only when any of the airflow documentation or code changed. 

It should be rather easy to take a look at the list of files and produce such change list.

**Description**

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by kaxil** [comment]
I would say let's not try to optimize this because we use cross reference of apache-airflow in some providers and vice-versa to we should build all the docs.

https://github.com/apache/airflow/issues/13706 should be enough

**Comment by mik-laj** [comment]
Is it related? https://github.com/apache/airflow/issues/12983

**Comment by potiuk** [comment]
Closing as duplicate of #12983
