### ISSUE TITLE
Airflow web server UI bouncing horizontally at some viewport widths

### ISSUE THREAD

**Issue by mattwelke** [apache/airflow#13713]
**Apache Airflow version**: 2.0.0
**Environment**: Ubuntu 20.04 LTS, Python 3.8.6 via pyenv
- **OS** (e.g. from /etc/os-release): 20.04.1 LTS (Focal Fossa)
- **Kernel** (e.g. `uname -a`): Linux DESKTOP-QBFDUA0 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Following steps in https://airflow.apache.org/docs/apache-airflow/stable/start.html

**What happened**:

I followed the quickstart here (https://airflow.apache.org/docs/apache-airflow/stable/start.html) to start Airflow on my machine. Then, I followed the tutorial here (https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html) to create my own DAG after disabling the example DAGs via the config file. The bouncing problem I'm reporting I actually noticed as soon as I launched Airflow. I'm just explaining what steps I took to get to what you see in the GIF below.

When I opened the Airflow UI in my browser, it appeared to "bounce" left and right. This happened on multiple pages. It seemed to happen only at certain widths bigger than the mobile width. At a large width, it didn't happen. I captured a GIF to try to demonstrate it:

![airflow_bouncing_problem](https://user-images.githubusercontent.com/7719209/104796253-a45f3500-5782-11eb-8b8a-ffc5b24c90cc.gif)

I didn't see any JS errors in the console in dev tools as this was happening.

**What you expected to happen**: A bounce-free **Airflow experience**™️ 

**What do you think went wrong?**: CSS? I'm not qualified for this magical front end stuff tbh.

**How to reproduce it**: Run the steps I described above on Ubuntu 20.04 LTS or a similar Linux operating system, using Python 3.

**Anything else we need to know**: n/a

**How often does this problem occur? Once? Every time etc?**

Every time I launch the Airflow web server and scheduler and load it at `localhost:8080`.

**Comment by vikramkoka** [comment]
@ryanahamilton Just wondered if you had thoughts about this.

**Comment by INGCRENGIFO** [comment]
That happens to me too.
