### ISSUE TITLE
State.Removed not part of finished set

### ISSUE THREAD

**Issue by george-zubrienko** [apache/airflow#13738]
**Apache Airflow version**:

2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

1.15.x

**Environment**:

- **Cloud provider or hardware configuration**: AWS

**What happened**:

Apparently `removed` task state causes Airflow to consider `dag_run` as active, due to `removed` not being part of `finished` frozenset:

https://github.com/apache/airflow/blob/v2-0-stable/airflow/utils/state.py#L103

**What you expected to happen**:

Removed state is counted as finished

**How to reproduce it**:

Create a dag run, backfill with success (-m) and then deploy a change removing some tasks. Airflow will now count it as active

**Comment by potiuk** [comment]
Looks like regression

**Comment by kaxil** [comment]
Duplicate of https://github.com/apache/airflow/issues/13151 and already fixed in https://github.com/apache/airflow/pull/13165 which will be released in 2.0.1
