### ISSUE TITLE
Support The Log With Python3-Rich.

### ISSUE THREAD

**Issue by Guanyan1996** [apache/airflow#13737]
<features> 
need support the rich console for task

I have the task (dockerOperator) with Console.log(), that can have processbar and the table flush...

when I run the scripts in airflow with dockerOperator(tty) ,the log will can't read for human.

how can the airflow log be replaced with rich.console  not the basic log?

thx.

**Comment by potiuk** [comment]
Direct link here: https://github.com/apache/airflow/discussions
