### ISSUE TITLE
v2-0-stable does not have requirements folder for constraint files.

### ISSUE THREAD

**Issue by vibhavbol** [apache/airflow#13743]
v2-0-stable does not have a requirements folder for constraint files. The variable AIRFLOW_PRE_CACHED_PIP_PACKAGES is set to false. Because of this, it is not possible to pre-install master version of airflow dependencies for Production build image segment and we have to reinstall the requirements from scratch each time if we are using airflow 2.0. This folder was present in earlier branches including v1-10-stable (supporting version 1.10.14). Please include the constraint requirements in a branch that supports airflow 2.0.0.

**Comment by potiuk** [comment]
We have no "Stable" version of the requirements. You should use the version that you are installing. For example if you are using 2.0.0 version of Airflow, you should use `constraints-2.0.0` tag for constraints.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/tree/constraints-2.0.0
