### ISSUE TITLE
REST API Connection Endpoint doesn't return the extra field in response

### ISSUE THREAD

**Issue by ConfuzedCoder** [apache/airflow#13744]
**Apache Airflow version**:
Apache Airflow: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
- **Kernel** (e.g. `uname -a`):
Linux Personal 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

REST API doesn't return the **extra** field of the connection in the response.

**What you expected to happen**:

It should return all the fields as shown in the documentation.
![Screenshot from 2021-01-18 20-10-09](https://user-images.githubusercontent.com/15157792/104928902-38224280-59c9-11eb-814a-3f359c0796f2.png)

**How to reproduce it**:

Create one connection with id  **leads_ec2** and define values as shown in the screenshot. 

![Screenshot from 2021-01-18 19-49-48](https://user-images.githubusercontent.com/15157792/104927763-d44b4a00-59c7-11eb-9139-da83d7098b3c.png)

Now call the below API endpoint to get the connection details. And as shown in the screenshot it doesn't include the extra field in the response.
**API Endpoint** : `http://localhost:8000/api/v1/connections/leads_ec2`
 
![Screenshot from 2021-01-18 19-50-07](https://user-images.githubusercontent.com/15157792/104928126-491e8400-59c8-11eb-80d5-84b52e812d8e.png)

**How often does this problem occur? Once? Every time etc?**:

Same for other connection_id. It doesn't return the extra field in the response.

**Comment by potiuk** [comment]
The Extra field should be a dictionary.

**Comment by tandelDipak** [comment]
@potiuk Thank you for your support.
I tried setting the below values but none of them worked.
- '{ "test": "a"}'
- '{}'
- ' '
- "{ "test": "a"}"
- "{}"
- " "
- { "test": "a"}
- Kept this field empty

At least it should return empty value when filed is kept empty.

**Comment by mik-laj** [comment]
I confirm this bug. I am working on a fix now.

**Comment by tandelDipak** [comment]
@mik-laj  can I work on this? I can not fix it quickly as you but if it's not urgent I would like to contribute.

**Comment by mik-laj** [comment]
@tandelDipak Feel free. Here is a similar PR: https://github.com/apache/airflow/pull/13684
