### ISSUE TITLE
Broken link on CONTRIBUTING.rst

### ISSUE THREAD

**Issue by griffincosgrove** [apache/airflow#13746]
Version Airflow 2.0, or most current version

In CONTRIBUTING.rst under the section "How to rebase a PR", [link to the docs section](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#id14) for reference, the link to Resolve conflicts link has an erroneous period at the end of the URL: [current incorrect link](https://www.jetbrains.com/help/idea/resolving-conflicts.html.)

The link should be https://www.jetbrains.com/help/idea/resolving-conflicts.html - without the period. The link works without the period. 

Steps to reproduce:
Click on the Resolve conflicts link on the page CONTRIBUTING.rst in the documentation. 

I would like to submit a PR to fix this, if someone would like to assist me in the review 😄

**Comment by vikramkoka** [comment]
@griffincosgrove Please do submit a PR to fix this. Happy to review

**Comment by griffincosgrove** [comment]
thanks, please assign this ticket to me, @vikramkoka ill get this done today 😄

**Comment by vikramkoka** [comment]
> thanks, please assign this ticket to me, @vikramkoka ill get this done today 😄

Done, please tag me and I will review it
