### ISSUE TITLE
Trigger a DAG Run via the Stable REST API fails with Bad Request due to external_trigger is set

### ISSUE THREAD

**Issue by seybi87** [apache/airflow#13740]
**Apache Airflow version**:

2.0.0

**Environment**:

- **Cloud provider or hardware configuration**: OpenStack -> VM -> Docker container 
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux 77f8efd77516 4.4.0-193-generic #224-Ubuntu

**What happened**:

I am trying to trigger a DAG run via the new stable REST-API `1.0.0` by using a Java-based client. The Java client is generated from the Airflow OpenAPI specification with OpenAPI generator version `5.0.0` . 

In Airflow  I have one active DAG `demo`

I trigger the DAG execution via the java client with the following code snippet:

```
ApiClient defaultClient = Configuration.getDefaultApiClient();
defaultClient.setBasePath("http://1.2.3.4:8080/api/v1);
DagRunApi dagRunApi = new DagRunApi(defaultClient);
DAGRun dagRun = new DAGRun();
try {
      DAGRun result = dagRunApi.postDagRun("demo", dagRun);

      LOGGER.debug(result);

    } catch (ApiException e) {
      e.printStackTrace();
    }

```

However, I receive the following exception: 

`BAD REQUEST`

**What you expected to happen**:

By checking the airflow logs it turned out that the  `external_trigger` value of the `DAGRun` is set but this is actually a read-only value and not allowed to be set which results in the `BAD REQUEST` response.

Adding the `nullable: true`  setting to the  `external_trigger` and recreating the java client resolved the issue!

```
external_trigger:
          type: boolean
          nullable: true
          readOnly: true
```          

**How to reproduce it**:

Create the Java client (probably any client will produce this error) via OpenAPI generator: 

1. `java -jar codegen/openapi-generator-cli-5.0.0.jar generate -i openapi.yaml -g java  -o .`
2. create a simple java class and apply the code snippets from above

**Comment by kaxil** [comment]
Not sure why it is giving you error, the default value is `True`:

https://github.com/apache/airflow/blob/9d9ef1addc44bb1553cf392f598366fd241c05c4/airflow/api_connexion/schemas/dag_run_schema.py#L63

https://github.com/apache/airflow/blob/9d9ef1addc44bb1553cf392f598366fd241c05c4/airflow/api_connexion/openapi/v1.yaml#L1553-L1556

cc @ephraimbuddy @mik-laj

**Comment by seybi87** [comment]
The issues is caused because the external_trigger`  property is defined with  `default: true `.
This results in an object `DAGRun dagRun = new DAGRun();` that has set the `external_trigger` value yet the Airflow server apin only accepts null values (as specified for the other DAGRun properties).

**Comment by mik-laj** [comment]
@kaxil This looks like an error in the generator. This field is marked read-only and should never be sent for POST requests in the request body.  This should be fixed in the generator, not in the specification.

**Comment by kaxil** [comment]
@seybi87 Like @mik-laj said -- it looks like an error in generator as we already mark the field readOnly so we don't expect a value for it

**Comment by mik-laj** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/4190
It looks related.

**Comment by seybi87** [comment]
Yes, you are right, this should be handled by the generator.  So feel free to close this issue.

Just out of curiosity, did you test the `postDagRun` call with the Airflow go client?

This would show if the error only occurs for the `java client` parts of code generator or for different languages.

**Comment by mik-laj** [comment]
> Just out of curiosity, did you test the postDagRun call with the Airflow go client?

@houqp Can you check it?

**Comment by ephraimbuddy** [comment]
> Yes, you are right, this should be handled by the generator. So feel free to close this issue.
> 
> Just out of curiosity, did you test the `postDagRun` call with the Airflow go client?
> 
> This would show if the error only occurs for the `java client` parts of code generator or for different languages.

I have triggered dagrun through python client and it worked fine. The OpenAPI generator is not perfect, you need to do some work on the generated code to get it working fine.
Having said that, @mik-laj I think we need to remove the `default=True` argument, it's not necessary there, I think? though it's not affecting anything. What do you think?
