### ISSUE TITLE
New cli interface in Airflow 1.1014 is missing possibility to use task_params for a task run

### ISSUE THREAD

**Issue by jjmurre** [apache/airflow#13789]
**Apache Airflow version**: 1.10/14

**Environment**:
- **Cloud provider or hardware configuration**: -
- **OS** (e.g. from /etc/os-release): Ubuntu 20:04
- **Kernel** (e.g. `uname -a`): 5.8.0-36-generic
- **Install tools**: -
- **Others**: -

**What happened**:

The new cli uses `airflow task run ...` to run individual tasks. What is missing is the possibility to use task parameters as a cli flag: `-tp` or `--task_params`.

**What you expected to happen**:
The possibility to use task parmeters.

**How to reproduce it**:
Issue a `airflow task run` from cli. There is no mention of `--task_params`.

**Comment by mik-laj** [comment]
I guess you wanted to use the `airflow tasks test` command.  The `airflow run` command never had a `--task_params`` parameter

Airflow 1.10.12
```
airflow test [-h] [-sd SUBDIR] [-dr] [-tp TASK_PARAMS] [-pm]
             dag_id task_id execution_date

-tp, --task_params
    Sends a JSON params dict to the task
```
Airflow 1.10.14
```
airflow tasks test [-h] [-n] [-m] [-S SUBDIR] [-t TASK_PARAMS]
                   dag_id task_id execution_date

-t, --task-params
Sends a JSON params dict to the task
```
This change are described in the migration guide: https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#airflow-cli-changes-in-2-0

<img width="833" alt="Screenshot 2021-01-20 at 18 28 06" src="https://user-images.githubusercontent.com/12058428/105212068-44cfa380-5b4d-11eb-988c-5d0409a2849d.png">

**Comment by potiuk** [comment]
Closing it - please let us know @jjmurre if it is not solved by @mik-laj answer - we will reopen it then.

**Comment by jjmurre** [comment]
Tx. for the quick reply. That's good news, it was indeed the replacement for the `airflow test` command that I wanted to use. And tx. for the link to the migration guide!
