### ISSUE TITLE
Sentry celery dag task run error

### ISSUE THREAD

**Issue by vinny-santaiti** [apache/airflow#13797]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Centos7
- **Kernel** (e.g. `uname -a`): Linux  3.10.0-693.5.2.el7.x86_64 
- **Install tools**: celery==4.4.0, sentry-sdk==0.19.5
- **Others**: python 3.6.8

**What happened**:

We see this in the sentry error logs randomly for all dag tasks: 
`TypeError in airflow.executors.celery_executor.execute_command`

```
TypeError: _run_mini_scheduler_on_child_tasks() got multiple values for argument 'session'
  File "airflow/sentry.py", line 159, in wrapper
    return func(task_instance, *args, session=session, **kwargs)
```

**What you expected to happen**:

No error in sentry.

**How to reproduce it**:

Schedule or manually run a dag task such as PythonOperator. 
The error msg will appear when airflow runs dag task.
The error will not appear in the airflow web server logs but only on Sentry server.

**Anything else we need to know**:

N/A

**Comment by Junnplus** [comment]
related code: https://github.com/apache/airflow/blob/master/airflow/models/taskinstance.py#L1176
`_run_mini_scheduler_on_child_tasks` use positional arguments

**Comment by Junnplus** [comment]
full context
```
_run_mini_scheduler_on_child_tasks() got multiple values for argument 'session'
airflow/sentry.py in wrapper at line 159
            def wrapper(task_instance, *args, session=None, **kwargs):
                # Wrapping the _run_raw_task function with push_scope to contain
                # tags and breadcrumbs to a specific Task Instance
                with sentry_sdk.push_scope():
                    try:
                        return func(task_instance, *args, session=session, **kwargs)
                    except Exception as e:
                        self.add_tagging(task_instance)
                        self.add_breadcrumbs(task_instance, session=session)
                        sentry_sdk.capture_exception(e)
                        raise
```

**Comment by gedOHub** [comment]
Hey guys,

I'm seeing the same issue on my instance too

Instance info:
 - AirFlow version 2.0.0
 - Python version 3.8.7
 - Pip version 20.2.4
 - Sentry-sdk version 0.19.5

```
# airflow/sentry.py in wrapper at line 159
...
            def wrapper(task_instance, *args, session=None, **kwargs):
                # Wrapping the _run_raw_task function with push_scope to contain
                # tags and breadcrumbs to a specific Task Instance
                with sentry_sdk.push_scope():
                    try:
>>>>>             return func(task_instance, *args, session=session, **kwargs)
                    except Exception as e:
                        self.add_tagging(task_instance)
                        self.add_breadcrumbs(task_instance, session=session)
                        sentry_sdk.capture_exception(e)
                        raise
```

**Comment by jporter-dev** [comment]
Having the same issue using the LocalExecutor with Airflow 2.0 running on Ubuntu 20.04.

**Comment by maxcountryman** [comment]
Also seeing this issue.

It's particularly noisy and somewhat disruptive as it seems to also immediately trigger: `Failed to execute task Task received SIGTERM signal.` and then `AirflowException: Celery command failed on host: {redacted}` quite often as of Airflow 2.0.1.
