### ISSUE TITLE
Specify an Timeout on an Operator - On timeout, fail the task!

### ISSUE THREAD

**Issue by r39132** [apache/airflow#138]
I would like to specify a timeout on any operator. How do I do this? I would like different timeouts on different operators. For example, the following Bash Operator can get hung on a call to Spark for days. I would like to wait 3 hours, after which I would like the task to fail! 

```
# Operator : Pick up the latest collector uploads data and create intermediate Parquet files
generate_new_parquet_files_spark_job = BashOperator(
    task_id='generate_new_parquet_files_spark_job',
    bash_command="ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; ~/run_ingest.sh'",
    dag=dag)
```

**Comment by r39132** [comment]
Folks! Any ideas here would be much appreciated. My bash task can get stuck indefinitely.

**Comment by mistercrunch** [comment]
Adding a `timeout` (as a timedelta object) attribute to `BaseOperator` seems reasonable.  I already have an object that can be used in a `with` block to time things out. 

You'd have to wrap this call here if timeout the attribute is defined: https://github.com/airbnb/airflow/blob/master/airflow/utils.py#L437

https://github.com/airbnb/airflow/blob/master/airflow/utils.py#L437

**Comment by r39132** [comment]
Thanks. but can you suggest how I would use it with the example I have above? 

I have a bunch of operators. In the above case, I'm not using a Python operator, but I am using a BashOperator, so I don't have control of the execution of this operator - your DAG execution engine is executing each operator. I can convert this to a PythonOperator and then take control -- is that what you are suggesting?

**Comment by r39132** [comment]
It would be nice if this were part of the BaseOperator's execution for every operator to leverage. With the exception of the BashOperator, I'm using PythonOperator for all of my other needs. I could convert this to PythonOperator as well, but, I'd rather move towards the more type specific operators (Bash, PostGres, Email) at some point.

**Comment by mistercrunch** [comment]
What I was suggesting was how to bake the feature in the framework, which should be trivial.

In the meantime you wrap your bash operations in a PythonOperator, use Popen, and use my timeout decorator. It may look something like that

```
from airflow.utils import timeout
def the_callable():
    with timeout(30):  # in seconds
        sleep(35)
PythonOperator(...)
```

**Comment by mistercrunch** [comment]
I ended adding the feature:
https://github.com/airbnb/airflow/pull/141

**Comment by r39132** [comment]
Any idea when your next release will be?

**Comment by r39132** [comment]
Tested it with the following code and it works! 

```
def wait_here_for_sometime(ds, **kwargs):    
    print " GOING TO SLEEP"
    time.sleep( 15 )
    print " AWAKE"

test_me = PythonOperator(
    task_id='test_me',
    execution_timeout=timedelta(seconds=2),
    provide_context=True,
    python_callable=wait_here_for_sometime,
    dag=dag)
```

**Comment by mistercrunch** [comment]
I think I'll release this along with the new callbacks I'm validating now, probably over the weekend or early next week.

**Comment by r39132** [comment]
Cool. I've switched to just pulling the latest code from git in our QA env and will do the same in prod

**Comment by agrouaze** [comment]
Would it be possible to add to this timeout execution condition a way to kill the process that exceed the granted time ?

**Comment by r39132** [comment]
@grouny Open a [Jira](https://issues.apache.org/jira/browse/AIRFLOW/) and reference this issue - as part of our move to Apache, we are tracking all issues in Jira going forward.
