### ISSUE TITLE
Consider decreasing the default `dagbag_import_timeout`

### ISSUE THREAD

**Issue by underyx** [apache/airflow#1380]
The default setting as of 1.7.0 is:

```
dagbag_import_timeout = 30
```

I don't think there's any reason for DAG imports to take over 1 second. I didn't always know this though, and had a DAG earlier that made DB queries on each run making the scheduler a lot slower than it should've been. I feel like having a really low default setting would be a nice way to make sure users don't do silly things like I did, if coupled with helpful error reporting.

**Comment by jlowin** [comment]
cc @bolkedebruin and @criccomini who have been looking at import timing

**Comment by underyx** [comment]
Moved to https://issues.apache.org/jira/browse/AIRFLOW-29
