### ISSUE TITLE
max_active_runs doesn't seem to work anymore (in 1.10.14)

### ISSUE THREAD

**Issue by jsmodic** [apache/airflow#13802]
**Apache Airflow version**:

1.10.14

**Environment**:

Regular Airflow setup:
Python 3.6.2
Airflow 1.10.14
Celery 4.3.0

**What happened**:

max_active_runs isn't limiting DAG runs on DAGs when None schedule_interval (unsure about with a schedule, I don't use them). I set it to 20 but more than 20 are running.

It used to work on older versions of 1.10.

**What you expected to happen**:

DAG Runs to be limited to what I set in max_active_runs

**Anything else we need to know**:

I've had "max_active_runs" set as a DAG parameter for a long time and it always worked fine until this latest update I went from 1.10.12 -> 1.10.14. 

I didn't see anything relevant in the upgrade changelogs, so I didn't realize it wasn't working until I look into some problems.

More so, the 0/20 doesn't seem to display in the RBAC UI, but that could be a change in the new UI since I just switched to that as well.

**Comment by jsmodic** [comment]
As far as I can tell:

https://github.com/apache/airflow/blob/1.10.14/airflow/jobs/scheduler_job.py#L794

never actually populates "active_dag_runs" anymore like in 1.10.12

https://github.com/apache/airflow/blob/1.10.12/airflow/jobs/scheduler_job.py#L796

**Comment by jsmodic** [comment]
Looks like it broke here: https://github.com/apache/airflow/commit/cb8d53fbc64af8d6c175d0dda6ae51db65ccc19b

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/13803
