### ISSUE TITLE
Airflow 2.0 can not connect to RDS Postgres (helm chart from source)

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#13817]
**Apache Airflow version**: 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Migration container does not appears. 
```
│ wait-for-airflow-migrations DB_BACKEND=postgresql                                                                                                                                                     │
│ wait-for-airflow-migrations DB_HOST=airflow-db-eu-central-1.clqz5ot1o8tz.eu-central-1.rds.amazonaws.com                                                                                         │
│ wait-for-airflow-migrations DB_PORT=5432                                                                                                                                                              │
│ wait-for-airflow-migrations [2021-01-21 17:26:31,636] {migration.py:155} INFO - Context impl PostgresqlImpl.                                                                                          │
│ wait-for-airflow-migrations [2021-01-21 17:26:31,636] {migration.py:162} INFO - Will assume transactional DDL.                                                                                        │
│ wait-for-airflow-migrations [2021-01-21 17:26:37,912] {opentelemetry_tracing.py:29} INFO - This service is instrumented using OpenTelemetry. OpenTelemetry could not be imported; please add opentele │
```

**What you expected to happen**: Airflow is able to connect to RDS

**How to reproduce it**:  Run helm chart with specified RDS connection

**Anything else we need to know**:

**Comment by potiuk** [comment]
This looks like troubleshooting question not bug report.. This bug report contain very little information. Please provide more details - whether you are using the master chart, or some other , what are the error log you see and detailed reproduction path. If you are unsure if you configured it all properly, you can also ask at the #troubleshooting channel in slack or open a discussion about it.
