### ISSUE TITLE
Feature Request: Why is my task not scheduled?

### ISSUE THREAD

**Issue by wil5for** [apache/airflow#1383]
Dear Airflow Maintainers, cc: @mistercrunch @r39132,

Problem: I would like to know why tasks are not being scheduled when I expect them to be.

When debugging it would be nice to expose task dependency states, this can be especially crucial in production systems. 

I would like to quickly be able to see why a task (or dag run) is in its current state, specifically the queued -> running or blank -> queued states. This would be most useful to me in scheduler logs and/or in the UI.

Common examples might be task dependencies not completed, pool slots full, max active dag runs exceeded, execution date not yet reached.

**Comment by aoen** [comment]
Agreed. We have had plans to work on this for a while, and I'm going to be taking this soon.

**Comment by aoen** [comment]
JIRA here: https://issues.apache.org/jira/browse/AIRFLOW-149
