### ISSUE TITLE
Use Tabular Format for the List of Upgrade Check Rules

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#13858]
Would be awesome to have a tabular format (makes it more readable) like below :) (From https://github.com/apache/airflow/pull/13392#pullrequestreview-563164638)

```
| ClassName                                | Description                                                       |
|------------------------------------------|-------------------------------------------------------------------|
| VersionCheckRule                         | Check for latest versions of apache-airflow and checker           |
| AirflowMacroPluginRemovedRule            | Remove airflow.AirflowMacroPlugin class                           |
| BaseOperatorMetaclassRule                | Ensure users are not using custom metaclasses in custom operators |
| ChainBetweenDAGAndOperatorNotAllowedRule | Chain between DAG and operator not allowed.                       |
| ConnTypeIsNotNullableRule                | Connection.conn_type is not nullable                              |
| DbApiRule                                | Hooks that run DB functions must inherit from DBApiHook           |
| FernetEnabledRule                        | Fernet is enabled by default                                      |
| GCPServiceAccountKeyRule                 | GCP service account key deprecation                               |
| HostnameCallable                         | Unify hostname_callable option in core section                    |
| ImportChangesRule                        | Changes in import paths of hooks, operators, sensors and others   |
| LegacyUIDeprecated                       | Legacy UI is deprecated by default                                |
| LoggingConfigurationRule                 | Logging configuration has been moved to new section               |
| MesosExecutorRemovedRule                 | Removal of Mesos Executor                                         |
| NoAdditionalArgsInOperatorsRule          | No additional argument allowed in BaseOperator.                   |
| PodTemplateFileRule                      | Users must set a kubernetes.pod_template_file value               |
| SendGridEmailerMovedRule                 | SendGrid email uses old airflow.contrib module                    |
| TaskHandlersMovedRule                    | Changes in import path of remote task handlers                    |
| UndefinedJinjaVariablesRule              | Jinja Template Variables cannot be undefined                      |
| UniqueConnIdRule                         | Connection.conn_id is not unique                                  |
```

This should be just an enhancement to the changes in https://github.com/apache/airflow/pull/13392

**Comment by kaxil** [comment]
cc @madison-ookla

**Comment by madison-ookla** [comment]
I started down this road and ran into some issues with the airflow utils table function...will need to give it another shot!

**Comment by turbaszek** [comment]
Should we use rich? The upgrade check is already installed as separate package so we may add an additional dependency. We are using rich in 2.0 for many cli commands :)

**Comment by madison-ookla** [comment]
> Should we use rich? The upgrade check is already installed as separate package so we may add an additional dependency. We are using rich in 2.0 for many cli commands :)

I need to dig into the existing utils for 1.10.x a bit more to see what the issue is, but if I keep having trouble I'll see about rich!

**Comment by kaxil** [comment]
> Should we use rich? The upgrade check is already installed as separate package so we may add an additional dependency. We are using rich in 2.0 for many cli commands :)

`rich` is Python 3.6 only though

**Comment by potiuk** [comment]
> > Should we use rich? The upgrade check is already installed as separate package so we may add an additional dependency. We are using rich in 2.0 for many cli commands :)
> 
> `rich` is Python 3.6 only though

But Upgrade  check is also 3.6 + ?

**Comment by kaxil** [comment]
> > > Should we use rich? The upgrade check is already installed as separate package so we may add an additional dependency. We are using rich in 2.0 for many cli commands :)
> > 
> > 
> > `rich` is Python 3.6 only though
> 
> But Upgrade check is also 3.6 + ?

Nope, it is 2.7+ : https://github.com/apache/airflow/blob/v1-10-test/airflow/upgrade/setup.cfg#L52

**Comment by potiuk** [comment]
> Nope, it is 2.7+ : https://github.com/apache/airflow/blob/v1-10-test/airflow/upgrade/setup.cfg#L52

I think it's wrong then: http://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html -> migration to python 3 is the first step, long before you go to 1.10.14. I can't imagine anyone running "Upgrade check" in 2.7. I even argue that you should not be able to install Upgrade Check for 2.7 precisely for the reason to force people to upgrade python first.

**Comment by brendalf** [comment]
So we can use rich?
I would like to give a try on this, it's that ok?

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/14139
