### ISSUE TITLE
Add a Rule to Check version of Database (MySQL / Postgres / SQLite)

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#13850]
Many users are not sure about the requirements of the DB versions mentioned in https://github.com/apache/airflow#requirements and run into different errors.

We should have a "Check / Rule" in our Upgrade Check Plugin to warn users if they use a version that will be not compatible with 2.0.0

This issue is part of #8765

## How to guide
To implement a new rule, create a class that inherits from `airflow.upgrade.rules.base_rule.BaseRule`.
It will be auto-registered and used by `airflow upgrade-check` command. The custom rule class has to have `title`,
`description` properties and should implement `check` method which returns a list of error messages in case of
incompatibility.

For example:
https://github.com/apache/airflow/blob/ea36166961ca35fc51ddc262ec245590c3e236fb/airflow/upgrade/rules/conn_type_is_not_nullable.py#L25-L42

**Comment by kaxil** [comment]
cc @Dr-Denzy

**Comment by Dr-Denzy** [comment]
I will take this on right away.

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/13955
