### ISSUE TITLE
Baked pod_template_file.yaml appears only in webserver (not scheduler)

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#13866]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I am using helm chart for deployment of airflow 2.0. To add my own pod_template configuration I simply tried to  embeded it into built by me airflow docker image.It appeared that the new version is only stored and accessible via  webserver. Scheduler consist default one. When I am trying to launch pod, it uses old version and that's why my jobs fail.

**What you expected to happen**:
Embedded `pod_template_file.yaml` in docker image is used for launching pods (available in scheduler)

All components will be overidden.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Closing as this has not enough details to act on it. Please be specific about the problem you are reporting @gardnerdev

**Comment by gardnerdev** [comment]
@potiuk Can you please reopen issue? I added more specific description :)

**Comment by potiuk** [comment]
Sorry, this is certain,y not enough for a descrption nor reproducible cases. It lacks almost any detaul what you want to do and what is your problem. I suggest you open a discussion @ slack or Github Discussions and try to get some help there.

**Comment by gardnerdev** [comment]
I can not agree. Just for sure I added additional description. For those who will have the same issue: you need to change `pod_template_file.yaml` name and then airflow will be able to read new pod_template configuration. For me it seems like a bug cause it wasn't mentioned in documentation that previous name couldn't be updated
