### ISSUE TITLE
Pandas 1.2.1 does not support python 3.6

### ISSUE THREAD

**Issue by sokoloff** [apache/airflow#13863]
@potiuk  There is issue with constraints-3.6 in constraints-master

Pandas 1.2.1 does not support python 3.6

https://github.com/apache/airflow/blob/constraints-master/constraints-3.6.txt#L265

**Comment by potiuk** [comment]
Yep. temporary problem. Fixing it now.

**Comment by potiuk** [comment]
(badly set environment variable when generating constraints)

**Comment by potiuk** [comment]
Should be fixed now. Sorry for the trouble @sokoloff !
