### ISSUE TITLE
Need for a periodic DagBag cleansing on web servers.

### ISSUE THREAD

**Issue by storpipfugl** [apache/airflow#139]
Hi,

What is the preferred procedure for removing a dag? If it is removed from the dags dir (with the scheduler running) it still shows in the webUI just without the scheduling history. Refreshing the webUI (#116) makes no difference and "airflow clear <dag_id>"  returns an error because the dag_id does not exist. Restarting the webserver solves the problem. Should the webserver always run in debug mode or is there another way of picking up when dags are removed?

**Comment by r39132** [comment]
+1

**Comment by kevinmandich** [comment]
Would also like to know the answer to this!

**Comment by mistercrunch** [comment]
Oh, yeah, here the web servers get restarted every time I push new code in production, which is pretty much everyday. I'll keep this open until I get to it...

**Comment by pedrorjbr** [comment]
+1

I will develop a workaround using WatchDog. When a dag file is 'modified' | 'created' | 'moved' | 'deleted' i will restart the webserver.
