### ISSUE TITLE
Airflow 2.0.0: DagRunType not compatible with Airflow 1.x

### ISSUE THREAD

**Issue by widewing** [apache/airflow#13901]
I recently upgraded my Airflow version from 1.10.10 to 2.0.0, and noticed the scheduler are failing and exiting after upgrade. After checking the log, it's suggest the duplicated entry for records in `dag_run` table. It tries to insert dag runs already executed before the upgrade. 
After some digging, I found it related to how the scheduler calculate the next execution_date: it picks the last dag_run with `run_type` of scheduled, however the new `DagRunType.SCHEDULED` is not the same as "scheduled" as previously was. as `DagRunType` is an enum type, `DagRunType.SCHEDULED` is actually converted to "DagRunType.SCHEDULED" not "scheduled". 
It looks like not an intended design but a mistake. change of `DagRunType.SCHEDULED` to `DagRunType.SCHEDULED.value` will simply solve this issue.

https://github.com/apache/airflow/blob/ab5f770bfcd8c690cbe4d0825896325aca0beeca/airflow/jobs/scheduler_job.py#L1559-L1568

**Comment by mik-laj** [comment]
Is it related?

https://github.com/apache/airflow/pull/13278

**Comment by widewing** [comment]
> Is it related?
> 
> #13278

Thanks! yeah it's the same
