### ISSUE TITLE
TaskGroup need the default_args like dag

### ISSUE THREAD

**Issue by penggongkui** [apache/airflow#13911]
I wan't to use taskgroup to replace subdag, but i find it cannot add default_args, so i have to add a **default_args to my tasks.

how about add a feature, taskgroup has a default_args param, and it will pass to it's children task

**Comment by turbaszek** [comment]
You can pass `default_args` in DAG that will include TaskGroup. TaskGroup needs to live within a DAG, it does not substitute it as far as I understand.

**Comment by penggongkui** [comment]
I want in the same dag , different taskgroup has different default_args,
subdag can do it but task group can't

**Comment by xinbinhuang** [comment]
I will work on this @eladkal

**Comment by jhtimmins** [comment]
@xinbinhuang Were you able to work on this one? If we can get it merged this week it can be included in the 2.1 release, otherwise we'll target a later release.

**Comment by xinbinhuang** [comment]
@jhtimmins  hey sorry, this skips through my head. Let me work on this tonight! Will pin you for review

**Comment by penggongkui** [comment]
@xinbinhuang any update on this feature?

**Comment by penggongkui** [comment]
@xinbinhuang @jhtimmins I have fnished the feature, Could you please review the code

**Comment by penggongkui** [comment]
@eladkal Would you mind move this issue to milestone 2.1.1(it seams the version is going to release). I have waited for this feature for a really long time(about a half of year) 😄

**Comment by eladkal** [comment]
The milestone will be set by the release manager when the PR is merged.

**Comment by uranusjr** [comment]
This will likely be released in 2.2. 2.1 has already split out of main, and 2.1.1 will be released from that branch.

**Comment by uranusjr** [comment]
Also, since the PR has been merged, should this issue be closed/
