### ISSUE TITLE
The apache-airflow-backport-providers-ssh version 2020.10.29 is broken

### ISSUE THREAD

**Issue by bchazalet** [apache/airflow#13926]
**Apache Airflow version**:
 1.10.14 ( 1.10.14+composer)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.16.15-gke.6000

**Environment**:
- Cloud Composer 

**What happened**:

The [apache_airflow_backport_providers_ssh-2020.10.29-py3-none-any.whl](https://pypi.org/project/apache-airflow-backport-providers-ssh/#files) has got extra files in it which get installed and breaks the use of some hooks and operators. For example, it brings a version of `airflow/providers/google/cloud/hooks/compute.py` that is older than the one I have and need in my environment: I have the backported providers version 2020.11.23 and this package brings providers' files of version 2020.10.29.

**What you expected to happen**:

I expect the wheel files to basically contain two files (plus or minus the init files), just like the tar file. Namely: `airflow/providers/ssh/hooks/ssh.py` and `airflow/providers/ssh/operators/ssh.py` but it actually contains 786 files (I truncated the list to the top folders):

```
apache_airflow_backport_providers_ssh-2020.10.29-py3-none-any > ls -lR
total 0
drwxr-xr-x@ 4 bchazalet  staff  128 27 Jan 11:57 airflow
drwxr-xr-x@ 8 bchazalet  staff  256 27 Jan 11:57 apache_airflow_backport_providers_ssh-2020.10.29.dist-info

./airflow:
total 0
drwxr-xr-x@ 47 bchazalet  staff  1504 27 Jan 11:58 providers

./airflow/providers:
total 0
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 amazon
drwxr-xr-x@ 12 bchazalet  staff  384 27 Jan 11:57 apache
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 celery
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 cloudant
drwxr-xr-x@  3 bchazalet  staff   96 27 Jan 11:57 cncf
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 databricks
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 datadog
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 dingding
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 discord
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 docker
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 elasticsearch
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 exasol
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 facebook
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 ftp
drwxr-xr-x@ 11 bchazalet  staff  352 27 Jan 11:58 google
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 grpc
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 hashicorp
drwxr-xr-x@  8 bchazalet  staff  256 27 Jan 11:57 http
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 imap
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 jdbc
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 jenkins
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 jira
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 microsoft
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 mongo
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 mysql
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 odbc
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 openfaas
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 opsgenie
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 oracle
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 pagerduty
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 plexus
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 postgres
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 presto
drwxr-xr-x@  8 bchazalet  staff  256 27 Jan 11:57 qubole
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 redis
drwxr-xr-x@  8 bchazalet  staff  256 27 Jan 11:57 salesforce
drwxr-xr-x@  5 bchazalet  staff  160 27 Jan 11:57 samba
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 segment
drwxr-xr-x@  7 bchazalet  staff  224 27 Jan 11:57 sftp
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 singularity
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 slack
drwxr-xr-x@  8 bchazalet  staff  256 27 Jan 11:57 snowflake
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 sqlite
drwxr-xr-x@  6 bchazalet  staff  192 27 Jan 11:57 ssh
```

I think the build process of the wheel file went wrong and included lots of files that should not be there.

**How to reproduce it**:

You can either manually download the wheel file or simply install `apache-airflow-backport-providers-ssh` and look at all the files it installs.

**Comment by potiuk** [comment]
Confirmed. The .sdist package is correct. As a workaround you can download it From here: https://files.pythonhosted.org/packages/6d/e3/1cb2eb52cf842fa0a1fa1960cbc85ee35282c189f6900d51436aed51d226/apache-airflow-backport-providers-ssh-2020.10.29.tar.gz

and run `pip install apache-airflow-backport-providers-ssh-2020.10.29.tar.gz` 

I will review and find what was wrong at preparation time. 

I will release new providers this week hopefully and will yank 10.29 release.

**Comment by bchazalet** [comment]
thanks @potiuk, sound good! I don't have the luxury of installing from the tar directly because I am using Cloud Composer but I'll wait for the new provider.

**Comment by potiuk** [comment]
You can still install 2020.10.5 version still as well by adding `==2020.10.5` - there weren't any substantial changes then. And I see it was properly created.

**Comment by potiuk** [comment]
Actually I yanked it even now. So when you try to install it now without version, the 2020.10.5 should be installed,

**Comment by bchazalet** [comment]
ok, thanks I am going to try that.

**Comment by bchazalet** [comment]
FYI using `==2020.10.5` works just fine for me.
