### ISSUE TITLE
[Question] How to deploy DAGs in a production environment without human intervention

### ISSUE THREAD

**Issue by sdiazb** [apache/airflow#1393]
Hi all,

I wonder if any of you guys, that are more experienced using the platform, is working with a CD approach.

My idea is develop an automatic process that deploys new DAGs. The problems arise when you have to manually add variables and connections in the metadata DB. Have some of you tackled this problem?

Maybe a workaround could be implementing a feature so when you run the initdb command you can pass a file where your connection or variables used by your DAGs are explicited. For example like this: `airflow initdb --conections connections.yml`.

Another option could be scripting the DMLs outside airflow and incorporating into the automatic deployment process before deploying the DAGs, but I think using the defined models in the platform is a better solution.

I would love to know your thoughts about this topic.

Thanks in advance!

**Comment by syvineckruyk** [comment]
@sdiazb we are deploying variables and connections through ansible .... not a very elegant solution but gets the job done. We use simple python scripts and store variables and connections in ansible dictionary variables.

these scripts are not at all fancy ... and I believe i've seen a few PRs integrating this functionality into the CLI directly. But these scripts may help you in the short term.

https://gist.github.com/syvineckruyk/d2c96b418ed509a174e0e718cb62b20a

**Comment by sdiazb** [comment]
Thank you very much @syvineckruyk! These are great news. We use Ansible too and this is exactly what we have in mind if we didn't develop a functionality to integrate this feature into the CLI, so these scripts are very useful.

In the mid term, would it be nice to integrate it in the CLI and instead of using Ansible variables, using YAML files or something similar? If this is a better way to go in the mid term, I may look into it and provide a PR in the future.

Thanks again for your comment!

**Comment by bolkedebruin** [comment]
If any questions remaining please move it to the mailinglist
