### ISSUE TITLE
Bash Operator can't run custom bash commands

### ISSUE THREAD

**Issue by ConfuzedCoder** [apache/airflow#13942]
**Description**

I have defined one shell script function and in my .bashrc profile, I have added a line to source the bash script so that I can run the function defined inside the script. The same command doesn't work in Bash Operator.

**Use case / motivation**

I have to run multiples command (5-6 commands to run one script) using && operator to setup environment and other things. I have a custom command which takes 3 arguments and does all the work of 5-6 commands. This feature will help everyone to run custom commands to simplify the process. 

I have done something similar to the below post. Those custom commands are not working in BashOperator.

https://medium.com/devnetwork/how-to-create-your-own-custom-terminal-commands-c5008782a78e

**Are you willing to submit a PR?**

Yes, I am willing to submit PR.

**Related Issues**

**Comment by eladkal** [comment]
@tandelDipak you can always open PR directly, there is no need to open an issue first
feel free to submit your PR  :)

**Comment by ulisesojeda** [comment]
Hi @tandelDipak,

In order to define custom commands (functions) you can define it in a single line before calling. 
The BashOperator is not defined to execute a script before running the **bash_command**

**Example:**

```
run_this = BashOperator(
    dag=dag,
    task_id='run_bash',
    bash_command="print_my_input() { echo Your input: $1 ; } && print_my_input 222",
)
```
 **Result:**
{subprocess.py:78} INFO - Your input: 222

**Comment by potiuk** [comment]
This is not a problem with BashOperator, but misunderstanding how .bashrc works.  The `.bashrc` is only sourced for "interactive" login and remote non-interactive shell sessions (executed via ssh-daemon). Baasically .bashrc will only be sourced automatically if there is a human typing the command to execute.

For any kind of "unsupervised" bash command (for example when you run cron scripts) you need to manually source the .bashrc file if you want to process any custom code there:

```
source /opt/airflow/.bashrc && command
```

**Comment by uranusjr** [comment]
Actually `.bashrc` is only sourced for interactive _non-login_ shells; login shells read `.profile` and `.bash_profile`. But a lot of `.bash_profile` implementations automatically source `.bashrc` so, uh it’s complicated and off-topic anyway. I’ll just drop a link in case anyone is actually interested in the exact differences.

https://linuxize.com/post/bashrc-vs-bash-profile/

**Comment by potiuk** [comment]
Oh yeah. It is :exploding_head: especially that for example MacOS has their own rules on which ones are loaded when as well.

**Comment by taizilongxu** [comment]
By the way , you can run this to use the login user inital env:
bash -l  ***
