### ISSUE TITLE
Create a Google Drive Sensor and a Google Drive to Google Cloud Storage Operator

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#13966]
**Description**

- Google Drive Sensor `airflow/providers/google/suite/sensors/drive.py`
  - This sensor would check for the existence of a file in Google Drive.
- Google Drive to Google Cloud Storage Operator `airflow/providers/google/cloud/transfers/gdrive_to_gcs.py`
  - This transfer operator would copy files from a shared Google Drive folder to a location in a Google Cloud Storage bucket.
- Additional functionality to the Google Drive Hook `airflow/providers/google/suite/hooks/drive.py` to support the operator & sensor.

**Use case / motivation**
- ETL
  - The transfer operator can be used by non-technical users trigger ETL pipelines. For example, a user can upload a CSV file to a shared Google Drive folder to be ingested into BigQuery. The sensor would be used to first ensure the existence of a particular file in Google Drive before the operator attempts to copy it.
- Backup / archival
  - The transfer operator can create backups or archives of Drive files in Google Cloud Storage.

**Are you willing to submit a PR?**
Yes! The code has been developed and works as expected in Airflow/Breeze.

**Related Issues**
N/a

**Comment by mik-laj** [comment]
> If you create pull-request, you don't have to create an issue first, but if you want, you can do it. Creating an issue will allow you to collect feedback or share plans with other people.

https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow

I am looking forward for your PR.
