### ISSUE TITLE
KubernetesPodOperator with do_xcom_push makes 137 exit code error

### ISSUE THREAD

**Issue by getElementsByName** [apache/airflow#13967]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): Client v1.14.8 / Server v1.15.10

**Environment**:

- **Cloud provider or hardware configuration**: on-premise
- **OS** (e.g. from /etc/os-release):  Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`): Linux 5.4.0-62-generic

**What happened**:

- operator code (with xcom)
```
    write_xcom = KubernetesPodOperator(
        do_xcom_push=True,
        image='alpine',
        cmds=["sh", "-c", "mkdir -p /airflow/xcom/;echo '[1,2,3,4]' > /airflow/xcom/return.json"],
        ...
    )
```

- airflow log
   - pending
```
[2021-01-29 12:32:19,604] {pod_launcher.py:269} INFO - Running command... kill -s SIGINT 1
```

#### pod
- k8s state of `airflow-xcom-sidecar` container
```
    State:          Terminated
      Reason:       Error
      Exit Code:    137
```

- processes in `airflow-xcom-sidecar` container
```
/airflow/xcom # ps 
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
    6 root      0:00 sh -c sleep 9999;mkdir -p /airflow/xcom/;echo '[1,2,3,4]' > /airflow/xcom/return.json
   11 root      0:00 sleep 9999
   12 root      0:00 sh -c trap "exit 0" INT; while true; do sleep 30; done;
   23 root      0:00 sh
   31 root      0:00 sleep 30
   48 root      0:00 ps
```

**What you expected to happen**:

- send the INT signal to the sidecar's main process (It is PID 12 in the previous example)

**How to reproduce it**:

- It is probably related to setting up k8s about `shareProcessNamespace` pod.

**Comment by potiuk** [comment]
I honestly do not understand what is the problem and expectations here. Could you please elaborate on what you were trying to achive and what did not work? 

Please be as descriptive as possible.

**Comment by getElementsByName** [comment]
@potiuk
### Problem
- (airflow) The `airflow-xcom-sidecar` container waits a SIGINT signal by `trap "exit 0" INT;`. 
- (airflow) The pod launcher in the airflow package stops the sidecar's main processor by `kill -s SIGINT 1`
- (k8s) The PID1 process can be a init process made by a container runtime like the docker.
   - In the top example. The sidecar's main process is not PID 1. 
- In the top example, the command (`kill -s SIGINT 1`) makes the 137 exit code.

### Expectation
- The pod launcher can send the SIGINT signal to the sidecar's main process other than PID 1 .

**Comment by ashb** [comment]
This is indeed caused by `shareProcessNamespace`. Why/how are you setting that?
