### ISSUE TITLE
Schedule interval display error in UI

### ISSUE THREAD

**Issue by bfan4** [apache/airflow#13976]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): None

**Environment**: Local machine

**What happened**:
The schedule interval of a DAG on the home page is displayed incorrectly sometimes. If I defined the parameters like `start_date` or `schedule_interval` in the `default_args`, these parameters **can** work well but **can't** be displayed correctly in the UI. For example, if ```default_args = { 'scheduler_interval'='@daily or @weekly or None` }```, it will always display `1 day, 0:00:00` in UI. A similar error happened on start_date as well, for example, if I defined ```default_args = { 'start_date'='2021-01-29` }```, then open the detail of the DAG, I will find that the `start_date` is always `None`. 

**What you expected to happen**:
I hope the schedule interval and start_date(maybe other params also have the same error)can be displayed correctly no matter I defined them in constructor or default_args. And if I defined a `schedule_interval` with crontab (something like 0 9 * * 1) I hope the UI can translate it to a human-readable like at 9:00 of every Monday.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
`schedule_interval` and `start_date` should be defined on DAG. Anything you define in `default_args` applies to a Task.

**Comment by bfan4** [comment]
> `schedule_interval` and `start_date` should be defined on DAG. Anything you define in `default_args` applies to a Task.

Do you mean a Task also has a `start_date` and `schedule_interval`?

**Comment by kaxil** [comment]
> > `schedule_interval` and `start_date` should be defined on DAG. Anything you define in `default_args` applies to a Task.
> 
> Do you mean a Task also has a `start_date` and `schedule_interval`?

We used to have it: https://github.com/apache/airflow/pull/6103
