### ISSUE TITLE
No "ready" message after "docker-compose up"

### ISSUE THREAD

**Issue by brylie** [apache/airflow#13970]
When following the installation instructions, the `docker compose up` step seems to fail to complete. I.e. it looks like things are hung after the "webpack.Progress" section:

![image](https://user-images.githubusercontent.com/17307/106244169-34858b80-6213-11eb-85b0-cab4c87cb1a3.png)

However, the app is accessible via localhost:8088

Is tere some way to reduce the log volume from Webpack, and show a friendly message to the user that Airflow is ready?

**Comment by mik-laj** [comment]
> ``superset_node``

It seems this is not an issue with Airflow, but with the Apache Superset. Can you create a ticket in Apache Superset repository? https://superset.apache.org/docs/intro

Docker Airflow images compile resources during build, so it doesn't affect application launch speed.

**Comment by brylie** [comment]
Ah my bad. I'm in Airflow all day hehe. Thanks.
