### ISSUE TITLE
'schedule_interval' Doesn't work in 'default_args'

### ISSUE THREAD

**Issue by datasciencejazz** [apache/airflow#140]
When creating the dag:

Passing in 'schedule_interval' as an explicit constructor argument works as expected.
Passing in 'schedule_interval' as part of the 'default_args' json object results in an interval of one day (i.e. the default behavior)

I'm fine with either way working; the tutorial seems to indicate that this can be passed as part of the default_args object, though.

**Comment by mistercrunch** [comment]
Oh actually I think it's only supported at the DAG level for now to prevent confusion around heterogenous schedule_intervals in DAGs. Make sure you specify it as a param when instantiating the DAG object.

**Comment by jlerman44** [comment]
I also ran into this.

**Comment by mistercrunch** [comment]
Are you interested in having different schedule_interval within the same DAG, or you just got confused as to how to set it for your DAG?

I think we're in a situation where I could allow heterogenous schedule_interval within a DAG by changing a single line of code, but it may be confusing to people as schedule times need to be aligned properly.

**Comment by jlerman44** [comment]
I am trying to set it for the DAG overall.

For some reason when I set the schedule_interval to every five minutes
(instead of once a day) it appears only my first task is run repeatedly...

I'll try to make a smaller example to illustrate the problem.

Josh

**Comment by mistercrunch** [comment]
I haven't done any testing under an hour but it should work too. 5 minutes is borderline getting into streaming territory though. You may want to consider things like Storm or Spark Streaming if you need close to realtime.

**Comment by mistercrunch** [comment]
I clarified schedule_interval in the docs today.

**Comment by guang** [comment]
:+1:
