### ISSUE TITLE
Unable to change Timezone for Web Server UI. get alert box with empty message

### ISSUE THREAD

**Issue by surapuramakhil** [apache/airflow#14000]
**Apache Airflow version**: 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 

**Environment**: Docker Image

- **Cloud provider or hardware configuration**: local
- **OS** (e.g. from /etc/os-release): ubuntu 20.04
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:
From web UI i am unable to change Timezone as per described in Docs
https://airflow.apache.org/docs/apache-airflow/1.10.14/timezone.html

**What you expected to happen**:

**How to reproduce it**: Its reproducible with the latest stable airflow docker images

https://youtu.be/Y01dGZtghGY

**Anything else we need to know**:
It occurs every time

**Comment by eladkal** [comment]
Note to what the doc says "only in RBAC UI"
https://airflow.apache.org/docs/apache-airflow/1.10.14/timezone.html#web-ui

You need to set rbac=True
