### ISSUE TITLE
integration with Asana as provider

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#14009]
**Description**

Asana is a tool to manage tasks https://asana.com/ (similar to Jira and others)

**Use case / motivation**

Need to find or create tasks in my ETL.
For example: when issue is found open Asana task as followup.

**Are you willing to submit a PR?**

If time will allow but probably won't have time.
Asana has an official python package https://github.com/Asana/python-asana

**Related Issues**

None

**Comment by eladkal** [comment]
Marked as good first issue but for anyone picking this up note that adding a new provider require more work than adding operator to existed provider. You can view https://github.com/apache/airflow/pull/13324 (Adding Neo4j provider) to understand the scope.

**Comment by jmelot** [comment]
I'd like to take this on!

**Comment by potiuk** [comment]
Feel free!

**Comment by jdavidheiser** [comment]
Hi - James from the Data Team at Asana here.  We are big Airflow users, and while we use a different mechanism to interact with Asana tasks in our own pipelines, we've thought about releasing an operator for ages.  Thank you so much for getting to it first!

**Comment by potiuk** [comment]
Hey @jdavidheiser  - Glad to hear that Asana is a big Airfow user :). I think that makes it a perfect opportunity for you to become contributors and provide some support and updates to the provider.

**Comment by jdavidheiser** [comment]
Some folks from our team have contributed a few small things already, but I'll definitely keep an eye out for opportunities to help support the provider in the future.
