### ISSUE TITLE
Order of items not preserved in Task instance view

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#14010]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The order of items is not preserved in Task Instance information:
<img width="542" alt="Screenshot 2021-02-01 at 16 49 09" src="https://user-images.githubusercontent.com/9528307/106482104-6a45a100-64ad-11eb-8d2f-e478c267bce9.png">
<img width="542" alt="Screenshot 2021-02-01 at 16 49 43" src="https://user-images.githubusercontent.com/9528307/106482167-7df10780-64ad-11eb-9434-ba3e54d56dec.png">

**What you expected to happen**:

I expect that the order will be always the same. Otherwise the UX is bad.

**How to reproduce it**:

Seems to happen randomly. But once seen the order is then consistent for given TI.

**Anything else we need to know**:

**Comment by turbaszek** [comment]
CC @ryanahamilton

**Comment by Junnplus** [comment]
@ryanahamilton If you don’t mind, I’m willing make pr for this.

**Comment by ryanahamilton** [comment]
@Junnplus that would be great, please do!
