### ISSUE TITLE
Changing state of task_instance to None

### ISSUE THREAD

**Issue by cccs-cat001** [apache/airflow#14012]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The scheduler outputs logs saying it's changing the state of task_instances to None. As seen here
![image](https://user-images.githubusercontent.com/56204545/106598475-25ae1a00-652e-11eb-8a7b-7b3bc1eee559.png)

**What you expected to happen**: Should it not be saying something proper like succeeded/failed/queued/scheduled/etc? 

**How to reproduce it**:
From what I understand you can launch a new deployment of airflow with a dag being scheduled, and the scheduler will output this. 

**Anything else we need to know**:

**Comment by eladkal** [comment]
I can't see your image - please upload it to github.
I'm not sure I understand your question/issue? NONE is a valid state for a task https://github.com/apache/airflow/blob/d2efb33239d36e58fb69066fd23779724cb11a90/airflow/utils/state.py#L57

Can you please describe the actual issue you are experiencing? It looks more as a question rather than reporting an actual issue.

**Comment by cccs-cat001** [comment]
I Uploaded the image to github. The issue is that it's always None, and never anything more useful. Should it not be updating it to be all the different states?

**Comment by ephraimbuddy** [comment]
It's the state of the pod that's been set to None after execution and not the task instance.
