### ISSUE TITLE
1.10.14: Scheduler state is out of sync with DB

### ISSUE THREAD

**Issue by jonathonbattista** [apache/airflow#14040]
**Apache Airflow version**: 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.18.12-gke.1205

**Environment**: GKE using KubernetesExecutor with MySQL backend.

**What happened**:  Pods are not spawning because Scheduler is out of sync with the DB. 

The webserver is reporting queued tasks but the scheduler has no idea about them.

A restart of the Scheduler pod temporarily fixes the problem.

Our `default_pool` has `128` slots but we set`core-parallelism` to `120`.

Webserver:
![image](https://user-images.githubusercontent.com/42357520/106660653-21492780-6555-11eb-9b55-29eeaa9ef6ab.png)

Scheduler:
```
airflow-scheduler [2021-02-02 20:21:28,025] {base_executor.py:122} DEBUG - 3 running task instances                                                                                                                                                        
airflow-scheduler [2021-02-02 20:21:28,025] {base_executor.py:123} DEBUG - 0 in queue                                                                                                                                                                      
airflow-scheduler [2021-02-02 20:21:28,025] {base_executor.py:124} DEBUG - 117 open slots
```
**What you expected to happen**:
Webserver and Scheduler should be in sync.

**How to reproduce it**:
Deploy 1.10.14 on K8s with KubernetesExectuor and MySQL backend.

**Anything else we need to know**:

**Comment by eladkal** [comment]
This issue is reported against an old airflow version which has reached end of life.
We no longer deploy fixes for this version.
Please upgrade your airflow version.
