### ISSUE TITLE
Inexistant reference in docs/apache-airflow/stable-rest-api-ref.rst

### ISSUE THREAD

**Issue by pchtsp** [apache/airflow#14045]
**Apache Airflow version**: 2.1.0.dev0 (master branch)

**What happened**:

in file `docs/apache-airflow/stable-rest-api-ref.rst` there is a reference to a file that does not longer exist: `/docs/exts/sphinx_redoc.py`.

The whole text:
```
It's a stub file. It will be converted automatically during the build process
to the valid documentation by the Sphinx plugin. See: /docs/exts/sphinx_redoc.py
```
**What you expected to happen**:

A reference to `docs/conf.py`, where I think is where the contents are now replaced during the build process.

**How to reproduce it**:

Go to the file in question.

**Anything else we need to know**:

I would've made a PR but I'm not 100% sure this is wrong or I just do not find the file referenced.

**Comment by vikramkoka** [comment]
Not sure I see this. Here is the link I used to check the rendered document
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html

**Comment by pchtsp** [comment]
Yeah, sorry: it is way more subtle than that (and less harmful). Check this file:
https://github.com/apache/airflow/blob/master/docs/apache-airflow/stable-rest-api-ref.rst
That shows the following:
![image](https://user-images.githubusercontent.com/5459187/106779335-2d151680-6647-11eb-90f9-48199bb6d7b2.png)

The contents are never shown in the documentation because the reference is overwritten by the deployment of the open-api docs. I only found the file because I was curious how you built the open-api docs and found that.

I'm guessing the file is just there to point to the correct place where those docs are built. But the reference to the path to the file is no longer valid. I think.

Hope it helps!

**Comment by mik-laj** [comment]
@pchtsp  We use an ``sphinxcontrib.redoc`` extension to generate this page. https://github.com/apache/airflow/blob/10c026cb7a7189d9573f30f2f2242f0f76842a72/docs/conf.py#L131
https://github.com/apache/airflow/blob/10c026cb7a7189d9573f30f2f2242f0f76842a72/docs/conf.py#L517-L536
So we should update this file.

**Comment by pchtsp** [comment]
Yes, I managed to learn how you were doing it. In fact, we now do it in our own project like this, too.

It was easier to show it with a PR at the end: https://github.com/apache/airflow/pull/14079/files
