### ISSUE TITLE
Display description colume of dag in UI DAG list

### ISSUE THREAD

**Issue by junnplus** [apache/airflow#14044]
**Description**

Display description column of dag in UI DAG list.

**Use case / motivation**

display description of dag maybe more friendly for user.

**Are you willing to submit a PR?**

yes.

**Related Issues**

**Comment by eladkal** [comment]
You can set DAG description with [doc_md](https://github.com/apache/airflow/blob/0e8c77b93a5ca5ecfdcd1c4bd91f54846fc15d57/airflow/models/dag.py#L261) parameter.
Are you asking to expose the value as column in the DAG list? I don't think that is doable. The description can be really long.

**Comment by Junnplus** [comment]
> Are you asking to expose the value as column in the DAG list?

Right. 

> The description can be really long.

We can truncate part of the content like hover content of `DAG` column.

**Comment by eladkal** [comment]
I'm pretty sure that when you define `doc_md` the content appear when you hover over your DAG.

**Comment by eladkal** [comment]
yes, as I thought
![2021-02-03_12-59-03](https://user-images.githubusercontent.com/45845474/106737814-cf210880-661f-11eb-9531-886c6332518b.gif)

**Comment by Junnplus** [comment]
I think it would be better to display columns than hover.

![image](https://user-images.githubusercontent.com/8097526/106739087-b29ec380-6653-11eb-91d3-096a347d714a.png)

**Comment by D0zingcat** [comment]
> So if when have hover over why do we need another column?
> ![2021-02-03_12-59-03](https://user-images.githubusercontent.com/45845474/106739276-9eda6980-6621-11eb-898d-9dc64aa0ae26.gif)

If here's a column shows description, it would be easier to search for the dags you want to find(i.e. just Cmd+F to find the description), or if the description could be searched, that would be even better.

**Comment by ryanahamilton** [comment]
I'm not super keen on adding a column to this table. The layout is already tight/dense, and adding another column would exacerbate this. We made changes in 2.0 to specifically reduce density (hidden links). As an optional DAG attribute, it would also have potential to consume space even when not utilized.

I _do_ agree that making it a searchable property would be very valuable. That seems like it would address what is lacking of the existing hover implementation, no?

**Comment by Junnplus** [comment]
> I do agree that making it a searchable property would be very valuable. That seems like it would address what is lacking of the existing hover implementation, no?

In other scenarios, we may need to quickly browse the dag list to find what we want.
Although dag id can be used instead, but description column is more friendly to non-English speaking countries.

**Comment by Junnplus** [comment]
> The layout is already tight/dense, and adding another column would exacerbate this.

Or we can put the description in the DAG column like tags?

**Comment by Junnplus** [comment]
ping @ryanahamilton

**Comment by ashb** [comment]
> > I do agree that making it a searchable property would be very valuable. That seems like it would address what is lacking of the existing hover implementation, no?
> 
> In other scenarios, we may need to quickly browse the dag list to find what we want.
> Although dag id can be used instead, but description column is more friendly to non-English speaking countries.

A better fix for this would instead be if we allowed more (read any characters apart from whitespace!) in DAG and task_ids, no?

**Comment by jscheffl** [comment]
A lot of outdated debate in this ticket, nobody brought it forward. closing.
