### ISSUE TITLE
 SambaHook using old unmaintained library

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#14054]
**Description**
The  [SambaHook](https://github.com/apache/airflow/blob/master/airflow/providers/samba/hooks/samba.py#L26) currently using [pysmbclient](https://github.com/apache/airflow/blob/master/setup.py#L408) this library hasn't been updated since 2017 https://pypi.org/project/PySmbClient/

I think worth moving to https://pypi.org/project/smbprotocol/ which newer and maintained.

**Comment by Rishabhraghwendra18** [comment]
Hi...May I work on this ?

**Comment by potiuk** [comment]
Sure! I assigned you :)

**Comment by Rishabhraghwendra18** [comment]
@potiuk thanks man ;)

**Comment by HaloKo4** [comment]
thanks @Rishabhraghwendra18  looking forward to this!

**Comment by Rishabhraghwendra18** [comment]
I am really sorry guys. I am not able to setup the development on my machine . And I am also having university exams within this month .So I am not able to contribute 😞. I am unassingning myself.

**Comment by potiuk** [comment]
> I am really sorry guys. I am not able to setup the development on my machine . And I am also having university exams within this month .So I am not able to contribute . I am unassingning myself.

Too bad. Next time maybe,

**Comment by Rishabhraghwendra18** [comment]
ya..sure

**Comment by marcosmarxm** [comment]
@potiuk can I take this one instead? I'm finishing the Airbyte provider so right now is easier to do this modification :D

**Comment by ashb** [comment]
@marcosmarxm Sure, all yours!

**Comment by uranusjr** [comment]
It seems like [pysmb](https://github.com/miketeo/pysmb) is another choice. Not sure whether it or smbprotocol is better/more suitable.

**Comment by malthe** [comment]
@uranusjr one deficiency in `pysmb` that I came upon was lack of Samba 2.1+ support, see https://github.com/miketeo/pysmb/issues/95#issuecomment-360295622.
