### ISSUE TITLE
SLA mechanism does not work

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#14050]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I have the following DAG:

```py
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.bash_operator import BashOperator

with DAG(
    dag_id="sla_trigger",
    schedule_interval="* * * * *",
    start_date=datetime(2020, 2, 3),
) as dag:
    BashOperator(
        task_id="bash_task",
        bash_command="sleep 30",
        sla=timedelta(seconds=2),
    )

```

And in my understanding this dag should result in SLA miss every time it is triggered (every minute). However, after few minutes of running I don't see any SLA misses...

**What you expected to happen**:

I expect to see SLA if task takes longer than expected.

**How to reproduce it**:

Use the dag from above.

**Anything else we need to know**:

N/A

**Comment by turbaszek** [comment]
Moving discussion from slack, cc @ashb @BasPH 

I'm can to confirm that no callback are invoked in dag processor. In other words nothing after this line is executed:
https://github.com/apache/airflow/blob/9af452aee53dd300535dadd108ce3e60c5f11a2e/airflow/jobs/scheduler_job.py#L554

**Comment by kaxil** [comment]
@turbaszek Can you test it with Master too please?

**Comment by turbaszek** [comment]
> @turbaszek Can you test it with Master too please?

Tested, same issue

**Comment by vikramkoka** [comment]
I have seen this work when sla is specified at a DAG level, had not tried it before within a task

**Comment by turbaszek** [comment]
@vikramkoka how can one specify SLA on DAG level? The DAG class has no `sla` argument 🤔

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/14056 fixes it

Tested with following DAG:

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.bash_operator import BashOperator

with DAG(
    dag_id="sla_trigger5",
    schedule_interval="@daily",
    start_date=datetime(2021, 1, 1),
) as dag:
    BashOperator(
        task_id="bash_task",
        bash_command="sleep 30",
        sla=timedelta(seconds=2),
    )
```

![image](https://user-images.githubusercontent.com/8811558/106826363-b5fb7480-667e-11eb-846f-fd555cc31e3e.png)

**Comment by vikramkoka** [comment]
> @vikramkoka how can one specify SLA on DAG level? The DAG class has no `sla` argument 🤔

@turbaszek Sorry, I did not say that correctly. It was through the default DAG parameters as shown below, 
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    #    'retries': 1,
    "retry_delay": timedelta(minutes=5),
    "sla": timedelta(seconds=6),
    "email": ["vikram@astronomer.io"],
}

However, after re-testing, it turns out that it fails too.
Good catch in finding this!

**Comment by turbaszek** [comment]
> However, after re-testing, it turns out that it fails too.

@vikramkoka yes, using `default_args` just make it easier to apply the `sla` to every task in DAG, so in the end we are using the same mechanism 😄

**Comment by lavanya282** [comment]
Dag sla mechanism is not working for the dag schedule with ‘0 11 * * *’ but it is working for the dag with schedule of running every 5minutes

**Comment by potiuk** [comment]
The SLA mechanism is generally broken in many ways. I recommend not to use it until we rewrite it.
