### ISSUE TITLE
Add support for UNSTABLE Jenkins status

### ISSUE THREAD

**Issue by lisovskey** [apache/airflow#14071]
**Description**

Don't mark dag as `failed` when `UNSTABLE` status received from Jenkins.
It can be done by adding `allow_unstable: bool` or `success_status_values: list` parameter to `JenkinsJobTriggerOperator.__init__`. For now `SUCCESS` status is hardcoded, any other lead to fail.

**Use case / motivation**

I want to restart a job (`retries` parameter) only if I get `FAILED` status. `UNSTABLE` is okay for me and it's no need to restart.

**Are you willing to submit a PR?**

Yes

**Related Issues**

No

**Comment by mik-laj** [comment]
> Are you willing to submit a PR?
> Yes

I assigned you to this ticket 🐈

**Comment by lisovskey** [comment]
@mik-laj take a look #14131 🐈
