### ISSUE TITLE
AWS S3 Logs docker image puckel/docker-airflow:1.10.9

### ISSUE THREAD

**Issue by soumilshah1995** [apache/airflow#14081]
trying to store my airflow logs on aws s3 airflow is working fine with my celery workers 

[2021-02-04 17:51:08,227] {s3_task_handler.py:52} ERROR - Could not create an S3Hook with connection id "AWSS3LogStorage". Please make sure that airflow[s3] is installed and the S3 connection exists.

remote_logging = True

# Users must supply an Airflow connection id that provides access to the storage
# location.
remote_log_conn_id = AWSS3LogStorage
remote_base_log_folder = s3://XXXXXX/airflow
encrypt_s3_logs = False

# Logging level
logging_level = INFO

docker file 
```
FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install boto3
RUN  pip install 'apache-airflow[s3]'



```

**Comment by potiuk** [comment]
Issues are not for troubleshooting. This is likely misconfiguration issue. Please confiratle the connection properly and open discussion on slack or in the "Discussion".

**Comment by soumilshah1995** [comment]
no this is an issue its not a misconfiguration. any links for the slack channel

**Comment by soumilshah1995** [comment]
> Issues are not for troubleshooting. This is likely misconfiguration issue. Please confiratle the connection properly and open discussion on slack or in the "Discussion" link (as explained when you were creating new issue).
