### ISSUE TITLE
Typo in Sensor: GCSObjectsWtihPrefixExistenceSensor (should be GCSObjectsWithPrefixExistenceSensor)

### ISSUE THREAD

**Issue by rachael-ds** [apache/airflow#14097]
Typo in Google Cloud Storage sensor: airflow/providers/google/cloud/sensors/gcs/GCSObjectsWithPrefixExistenceSensor

The word _With_ is spelled incorrectly. It should be: GCSObjects**With**PrefixExistenceSensor

**Apache Airflow version**: 2.0.0
**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud
- **OS** (e.g. from /etc/os-release): Mac OS BigSur

**Comment by mik-laj** [comment]
You should change the name and then add the code below for backward compatibility.
```
class GCSObjectsWtihPrefixExistenceSensor(GCSObjectsWithPrefixExistenceSensor):
    """
    This class is deprecated.
    Please use `airflow.providers.google.cloud.sensors.gcs.GCSObjectsWithPrefixExistenceSensor`.
    """

    def __init__(self, *args, **kwargs):
        warnings.warn(
            """This class is deprecated.
            Please use `airflow.providers.google.cloud.sensors.gcs.GCSObjectsWithPrefixExistenceSensor`.""",
            DeprecationWarning,
            stacklevel=3,
        )
        super().__init__(*args, **kwargs)
```
It is also worth adding tests. To do it, update the [`deprecated_classes.py`](https://github.com/apache/airflow/blob/master/tests/deprecated_classes.py) file.

**Comment by morrme** [comment]
@rachael-ds Are you working to fix this? If not, I'd like to submit a fix. 

cc: @vikramkoka @mik-laj

**Comment by rachael-ds** [comment]
I haven't started on this - please go ahead thank you!
