### ISSUE TITLE
Airflow 2.0.0 Tasks not retried on failure when retries>=1 in case of OperationalError

### ISSUE THREAD

**Issue by nicor88** [apache/airflow#14101]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):  v1.18.15

**Environment**:

- **Cloud provider or hardware configuration**: AWS (running in k8s cluster provisioned by kops)
- **OS** (e.g. from /etc/os-release): using Docker image **apache/airflow:2.0.0-python3.8**
<pre>
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
</pre>

- **Kernel** (e.g. `uname -a`): Linux  5.4.92-flatcar #1 SMP Wed Jan 27 16:53:10 -00 2021 x86_64 GNU/Linux
- **Install tools**:
- **Others**:
   * installed snowflake-connector-python==2.3.9

**What happened**:
From time to time seems to be a network glitch between K8s pods and RDS database (postgres 11.6). worker-pod fails with error `Failed to log action with (psycopg2.OperationalError) SSL SYSCALL error: Connection timed out` but the task even if has retry=1 is marked as Failed, and no retry happens. Considering that we have a dag with serial tasks, all the dag is marked as FAILED. This seems to happen only in the case of Operational Error (network glitch).

**What you expected to happen**:

I expected that the task will be retried. We experience the same issue with airflow 1.10.14, and the with the 2nd retry the tasks was marked as successful.

**How to reproduce it**:
I didn't manage to reproduce.

**Anything else we need to know**:
value of `max_db_retries` in airflow.cfg is set to **3**
The issue happen time to time, depends on the day also 2/3 times per day.

**Comment by tooptoop4** [comment]
similar to https://issues.apache.org/jira/browse/AIRFLOW-6518

**Comment by nicor88** [comment]
@tooptoop4 Yes seems similar with AIRFLOW-6518. Point is, that with version 1.10.14 when the metastore connection was lost (and having a task retry >=1) with the 2nd or 3th retry the task was able to connect to the Metastore DB. Now, in such case the task is marked immediately as failed, without retrying at all. So for me this was fix on previous airflow versions.

**Comment by vikramkoka** [comment]
@nicor88 In the interest of clarity, what executor are you using? 
I am not sure it makes a difference, but trying to figure out how to reproduce this and it would definitely help there.

**Comment by nicor88** [comment]
@vikramkoka We are using Kubernetes Executor, totally forgot to mention that in the issue.

**Comment by vikramkoka** [comment]
> @vikramkoka We are using Kubernetes Executor, totally forgot to mention that in the issue.

Thank you @nicor88

**Comment by waleedsamy** [comment]
I'm kinda of experiencing similar issue. In airflow 1.10.12 when a task failed, killed or the executor running it killed (zombie task?) it will but to retry if retries > 1. But this seems to not be the case with v2.1.0. when a task killed it mark it as failed and does not retry at all.

**Comment by waleedsamy** [comment]
This issue maybe a side effect of [d24c1e8a84f72e88b0b9031e2862b866be83831b](https://github.com/apache/airflow/pull/15537/files/d24c1e8a84f72e88b0b9031e2862b866be83831b#diff-d80fa918cc75c4d6aa582d5e29eeb812ba21371d6977fde45a4749668b79a515R159).

**Comment by kaxil** [comment]
@ephraimbuddy Can you look at this one too -- it is similar as the process executor events where we should retry instead of fail

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy Can you look at this one too -- it is similar as the process executor events where we should retry instead of fail

Yes. I will take a look

**Comment by d3centr** [comment]
This can be reproduced on Airflow 2.1.2 with K8s executor when setting task retries >= 1. Call `kubectl delete pod` on a task pod while it is running. Task will fail but won’t be retried.

**Comment by ephraimbuddy** [comment]
At @d3centr your case seems different and is resolved by https://github.com/apache/airflow/pull/16301 released in 2.1.3.

Also, this ticket has been resolved by https://github.com/apache/airflow/pull/17819 which will be released in 2.2

To confirm, @nicor88 , when you get this operational error, do you also see in the scheduler log message like this: 
`<TaskInstance: somedag.taskid [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?`
You can share the scheduler log, thanks

**Comment by nicor88** [comment]
@ephraimbuddy I can't provide them anymore, as the I'm not working anymore in the setup where I experienced that error.

**Comment by ashb** [comment]
Yeah, from what you describe that PR would mean the task is retried correctly.

I'm going to close this issue then as the fix is included in 2.2.0 (in beta stages right now)
