### ISSUE TITLE
BACKEND: Unbound Variable issue in docker entrypoint

### ISSUE THREAD

**Issue by coolacid** [apache/airflow#14104]
This is NOT a bug in Airflow, I'm writing this issue for documentation should someone come across this same issue and need to identify how to solve it. Please tag as appropriate.

**Apache Airflow version**: Docker 2.0.1rc2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: Dockered

- **Cloud provider or hardware configuration**: VMWare VM
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`): 4.15.0-128-generic
- **Install tools**: Just docker/docker-compose
- **Others**:

**What happened**:
Worker, webserver and scheduler docker containers do not start, errors:

<details><summary>/entrypoint: line 71: BACKEND: unbound variable</summary>
af_worker    | /entrypoint: line 71: BACKEND: unbound variable
af_worker    | /entrypoint: line 71: BACKEND: unbound variable
af_worker exited with code 1
af_webserver | /entrypoint: line 71: BACKEND: unbound variable
af_webserver | /entrypoint: line 71: BACKEND: unbound variable
af_webserver | /entrypoint: line 71: BACKEND: unbound variable
af_webserver | /entrypoint: line 71: BACKEND: unbound variable
</details>

**What you expected to happen**:

Docker containers to start

**How to reproduce it**:
What ever docker-compose file I was copying, has a MySQL Connection String not compatible with: https://github.com/apache/airflow/blob/bc026cf6961626dd01edfaf064562bfb1f2baf42/scripts/in_container/prod/entrypoint_prod.sh#L58 -- Specifically, the connection string in the docker-compose did not have a password, and no : separator for a blank password.

Original Connection String: `mysql://root@mysql/airflow?charset=utf8mb4`

**Anything else we need to know**:

The solution is to use a password, or at the very least add the : to the user:password section

Fixed Connection String: `mysql://root:@mysql/airflow?charset=utf8mb4`

**Comment by potiuk** [comment]
Would you mind to make a PR to the http://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html?highlight=airflow__core__sql_alchemy_conn#sql-alchemy-conn describing it ? 

I think maybe a little description to https://github.com/apache/airflow/blob/fc67521f31a0c9a74dadda8d5f0ac32c07be218d/airflow/config_templates/config.yml#L63 and a word about it in https://github.com/apache/airflow/blob/master/docs/apache-airflow/production-deployment.rst#configuration might be a good idea? 

Sounds like nice first-time contribution :)

**Comment by potiuk** [comment]
I checked that according to specification password-less entry (with no ':') is also a valid URL so we should adapt. I fixed the regexp to handle all cases including that one. See #14221

**Comment by potiuk** [comment]
> For reference: I was able to fix it encoding `@` as `%40`

Yep. this is correct fix.

**Comment by arshadbarves** [comment]
1. Remove spaces around the equal sign (=) in your .env file.
    Environment variable assignments should not have spaces before or
    after the equal sign.

 2. Make sure there are no extra spaces or special characters in the
    variable names or values. Double-check for any typos or incorrect
    characters in the variable names and values.
