### ISSUE TITLE
Lineage Backend removed for no reason

### ISSUE THREAD

**Issue by JPonte** [apache/airflow#14106]
**Description**

The possibility to add a lineage backend was removed in https://github.com/apache/airflow/pull/6564 but was never reintroduced. Now that this code is in 2.0, the lineage information is only in the xcoms and the only way to get it is through an experimental API that isn't very practical either.

**Use case / motivation**

A custom callback at the time lineage gets pushed is enough to send the lineage information to whatever lineage backend the user has.

**Are you willing to submit a PR?**

I'd be willing to make a PR recovering the LineageBackend and add changes if needed, unless there is a different plan for lineage from the maintainers.

**Comment by potiuk** [comment]
I think only @bolkedebruin so far was really pursuing the lineage, but I am sure if you would like to re-add it we can jointly review it and get it in 2.1, I think it is important to add it back in a form that will be good. Maybe also others would like to chime in?

If it is simple and you can prepare a proposed PR, I think the fastest way will be to prepare it and send a message to the devlist inviting people to discuss on it?  I am not very into the lineage topic, but I know it is is important enough to deserve a bit of discussion and maybe others who already use Amundsen and other tools might chime in and iterate with you on the PR.

**Comment by kaxil** [comment]
Have you been using Lineage backend with 1.10.x ?

We want to make sure that it works as expected. Definitely an important topic but if we add/change something it should work :) @JPonte

**Comment by JPonte** [comment]
@kaxil Yes, I was pushing the lineage data to a custom lineage backend and it was surprising that it disappeared on 2.0. I can make a PR reintroducing it. I don't use Apache Atlas so I won't bring the AtlasBackend, only the base one.
