### ISSUE TITLE
"airflow" "DAG" strings in file necessary to import dag 

### ISSUE THREAD

**Issue by Etiene** [apache/airflow#1411]
Hello airflow team! Thanks for the awesome tool!

We made a small module to automate our DAG building process and we are using this module on our DAG definition. Our airflow version is 1.7.0.

However, airflow will not import this file because it doesn't have the words `DAG` and `airflow` on it. (The imports etc are done inside our little module). Apparently there's a `safe_mode` that skips files without these strings.
(https://github.com/airbnb/airflow/blob/master/airflow/models.py#L233)

This `safe_mode` is default to `True` but is not passed to the process_file function, so it is always `True` and there's no apparent way to disable it.
(https://github.com/airbnb/airflow/blob/master/airflow/models.py#L204)
(https://github.com/airbnb/airflow/blob/master/airflow/models.py#L382)

Putting this comment on the top of the file makes it work for the moment and brought me a good laugh today 👯 
`#DAG airflow —> DO NOT REMOVE. the world will explode`

**Comment by bolkedebruin** [comment]
👍 

![](http://tonsofcats.com/wp-content/uploads/2013/11/l-My-friends-awesome-cat-Oscar.-550x366.jpg)

**Comment by bolkedebruin** [comment]
@Etiene would you mind creating a Jira issue for this? Thanks!

**Comment by Etiene** [comment]
No worries! But where is that? Docs need updating: https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md#report-bugs

EDIT: oops. Nervermind! Just saw the top issue :)

**Comment by Etiene** [comment]
Added to Jira!
