### ISSUE TITLE
Migrate inline JavaScript scripting to external files

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#14115]
**Description**

Currently we have inline JavaScript scripting in templates like `airflow/www/templates/airflow/[dags/dag/gantt/tree/graph].html` etc. In these scripting, some practices are not optimal, like unused arguments, usage of undeclared variables, style issues, etc.

**Use case / motivation**

As briefly discussed in https://github.com/apache/airflow/pull/14019#discussion_r568761030, it's better to migrate these inline JavaScript scripting to external files.

**Comment by bbovenzi** [comment]
I can take this one, if that's cool.

**Comment by ryanahamilton** [comment]
@bbovenzi that would be great—assigning to you!

**Comment by XD-DENG** [comment]
Thanks @bbovenzi for your interest!

If you would like to proceed, it would be great to share how you would plan to make this change, and potential issues you can foresee. I believe @ryanahamilton , our UI guru, already has some brief ideas about these, so it would be great to discuss together.

**Comment by XD-DENG** [comment]
Ha, I just see you guys are from the same team. This issue is in good hands👍 Tip-top!
