### ISSUE TITLE
Visibility of the installed requirements.txt file in Airflow

### ISSUE THREAD

**Issue by naturalett** [apache/airflow#14127]
**Description**

Airflow allows to install a requirements.txt file when a container is staring.
[installRequirements](https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L901)
The requirements.txt file can be [cloned](https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L958) or it will be located in DAGs folder, for example by using [PVC](https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L905)

**Use case / motivation**

It would be great to show the installed packages from the requirements.txt in the UI of Airflow.

**Are you willing to submit a PR?**

Yes

**Related Issues**

No

**Comment by potiuk** [comment]
This helm chart is not managed by the community. We are working on our own helm chart https://github.com/apache/airflow/tree/master/chart and we plan to release it but if you want to raise the issue for the other helm charts, you need to raise it in the original project of the chart.
