### ISSUE TITLE
Helm Scheduler Does Not Have dags emptyDir when Persistence Disabled

### ISSUE THREAD

**Issue by alexanderursu99** [apache/airflow#14138]
**Apache Airflow version**:

2.0.0

**What happened**:

emptyDir named "dags" was not attached to the scheduler container when git-sync is enabled and persistence is disabled.

I see the line responsible for this [here](https://github.com/apache/airflow/blob/master/chart/templates/scheduler/scheduler-deployment.yaml#L163).

Not sure if this is intentional, or if there are some other things to consider before changing the condition to include checking the value of `.Values.dags.gitSync.enabled`.

**What you expected to happen**:

Expected the dags emptyDir to be attached.

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/14203 should have fixed it -- can you check and confirm, please?

We can re-open the issue if it has not fixed it

**Comment by Alxander64** [comment]
I believe that issue covered the same thing this one was, so it should be good.
