### ISSUE TITLE
DagRuns has an inconsistency between the execution_date and the Run Id

### ISSUE THREAD

**Issue by WesleyBatista** [apache/airflow#1413]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet): 1.7.0

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue
- What did you expect to happen?
  Expected to see the log outputs from tasks on the "running" DagRun.
  ![captura de tela 2016-04-20 as 11 53 57](https://cloud.githubusercontent.com/assets/755254/14679174/2622eee0-06ef-11e6-9c38-76e056831103.png)
- What happened instead? 
  The tasks do not started immediately. The execution_date is set using UTC, while the e Run Id is set using localtime.
  ![captura de tela 2016-04-20 as 11 44 00](https://cloud.githubusercontent.com/assets/755254/14679311/aafce68e-06ef-11e6-9012-1b41a4f589c8.png)
- Here is how you can reproduce this issue on your machine:
#### Reproduction Steps
1. Create 2 DAGs
2. On the first DAG, set a TriggerDagRun Operator to start the second DAG.

Changing the `execution_date` and `start_date` manually on the UI solved the problem.

**Comment by r39132** [comment]
Refer to https://github.com/airbnb/airflow/wiki/Common-Pitfalls

Run on UTC everywhere.

**Comment by WesleyBatista** [comment]
Thanks @r39132!

**Comment by WesleyBatista** [comment]
But WDYT about to standardize the UI? I think that the way it is nowdays it causes misunderstandings.
