### ISSUE TITLE
Quick start docker-compose.yaml file uses an invalid tag

### ISSUE THREAD

**Issue by rmtobin** [apache/airflow#14143]
**Apache Airflow version**: 2.0.1

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 11.1
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 20.2.0
- **Install tools**: docker-compose

**What happened**:
Following the steps in the Quick start > Running Airflow in Docker page, I pulled down the pre-made docker-compose.yaml file (https://airflow.apache.org/docs/apache-airflow/2.0.1/docker-compose.yaml) and ran `docker-compose up airflow-init` within the same directory as the docker-compose file. This command failed with: `Pulling airflow-init (apache/airflow:2.0.1)...
ERROR: manifest for apache/airflow:2.0.1 not found: manifest unknown: manifest unknown`. 

**What you expected to happen**:
The latest stable official airflow docker image to be pulled, and airflow-init to complete successfully.

**How to reproduce it**:
Follow the instructions per the quick start docs (https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html) to pull down the docker-compose.yaml file, then attempt to run `docker-compose up airflow-init`.

**Anything else we need to know**:
After seeing this I took a look on dockerhub and it does not appear there is a '2.0.1' tagged image. I then tried simply altering the docker-compose file to instead use the latest tag (with no other changes), which pulled successfully, but did not initialize successfully. I ended up using a different pre-made docker-compose file altogether which used a valid 2.0.1 tag.

**Comment by Riveryoon** [comment]
try with tag 

`apache/airflow:2.0.1rc2-python3.7`

it works for me

**Comment by rmtobin** [comment]
@Riveryoon yes, other tags do work. However the docs should still use a working tag, especially for the intro setup. Either the docs need updating or the ‘2.0.1’ tag needs to be pushed up so the given steps work.

**Comment by alcmontejo** [comment]
> try with tag
> 
> `apache/airflow:2.0.1rc2-python3.7`
> 
> it works for me

thanks for for me as well. tnx

**Comment by kaxil** [comment]
Yes 2.0.1 will be released soon.

**Comment by kaxil** [comment]
Images pushed:

https://hub.docker.com/r/apache/airflow/tags?page=1&ordering=last_updated&name=2.0.1-python

**Comment by whiterook6** [comment]
To be clear to anyone else finding this, I had to replace this line in the quickstart docker compose:
`  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.0.1}`
with this line:
`  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.0.1-python3.8}`
and run `docker-compose up airflow-init` again.

**Comment by potiuk** [comment]
FYI. Changing the image name should not be needed any more.

The airflow:2.0.1 tag now points to : `apache/airflow:2.0.1-python3.6`  so it should work. Python 3.6 is our 'default' python version so the "generic" tag should point to it now.

**Comment by kaxil** [comment]
and `apache/airflow:latest` should work too
