### ISSUE TITLE
Airflow crashes when DAG run triggered by POST request with oversized conf

### ISSUE THREAD

**Issue by THEdavehogue** [apache/airflow#14159]
**Apache Airflow version**: 1.10.4

**What happened**:

I recently discovered the upper limits of the Airflow experimental API when passing a conf that was too long (~100KB, very long text). I think there should be some error handling to detect when the conf in a POST request via the [API](https://airflow.apache.org/docs/apache-airflow/stable/rest-api-ref.html) is truncated.

I didn't save the error message but it was something from SqlAlchemy trying to write a truncated JSON so the parsing didn't work properly

**What you expected to happen**:

There should be some sort of failsafe to detect malformed requests and soft-fail somehow.

**How to reproduce it**:
Send a POST request as seen below where the JSON after --data is larger than 64KB.

`curl -X POST \
    'http://localhost:8080/api/experimental/dags/<DAG_ID>/dag_runs' \
    --header 'Cache-Control: no-cache' \
    --header 'Content-Type: application/json' \
    --data '{"conf":"{\"key\":\"value\"}"}'`
    
   
**Anything else we need to know**:
This bug will break the DAG listing (localhost:1188/admin) as well as the UI for the offending DAG (localhost:1188/admin/airflow/tree?dag_id=<my_broken_dag>)

**Comment by ashb** [comment]
Whoops!

The post request gave a 200 I assume?

**Comment by THEdavehogue** [comment]
> The post request gave a 200 I assume?
> 
> Are you on MySQL? I suspect what has happened is mysql, in its infinite wisdom, has silently trucated the JSON blob, so now the value in the DB is not valid JSON, but the post data was.

exactly this. 200 response, DAG run created but sql errors due to truncation.

**Comment by codersky** [comment]
as a workaround, we change the conf column from tiny blob to medium

**Comment by eladkal** [comment]
This issue is reported against old airflow version. The experimental API is deprecated in favor of a rest API.
Please upgrade your Airflow version and change to the rest API:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html
