### ISSUE TITLE
add InfluxdbHook

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#14168]
**Description**
https://www.influxdata.com/
Add the ability to query and modify Influxdb from airflow.

Python wrapper that can be used to create the hook :
https://github.com/influxdata/influxdb-python

There are some usage examples in https://github.com/influxdata/influxdb-python/tree/master/examples
would be nice if the hook would support the following:
create_database
query
drop_database
write_points 

**Are you willing to submit a PR?**

not at the moment due to time contains.

**Related Issues**

couldn't find any

**Comment by Dr-Denzy** [comment]
@HaloKo4 It will be really nice to have this feature.
What do you think? @kaxil @ashb

**Comment by ashb** [comment]
Sure yeah would be nice. Someone will need to open a PR though :)

**Comment by Dr-Denzy** [comment]
I can give it a go.

**Comment by subkanthi** [comment]
@kaxil , @Dr-Denzy , is this being worked on, please let me know I could take it on.

**Comment by kaxil** [comment]
@subkanthi go for it :)
