### ISSUE TITLE
Example tutorial_taskflow_api_etl crashes w/ AttributeError: Can't pickle local object

### ISSUE THREAD

**Issue by gschwim** [apache/airflow#14162]
**Apache Airflow version**: from the docker-compose file in the tutorial, image apache/airflow:master-python3.8 and apache/airflow:master-python3.7

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**:

- **Cloud provider or hardware configuration**: Bare metal server in lab, AMD threadripper, 64GB ram
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS BIONIC VM running atop KVM
- **Kernel** (e.g. `uname -a`): Linux zxdev01 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: docker-compose as provided in airflow tutorial w/ mods as above
- **Others**: set up per the tutorial [here](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html)

**What happened**:

Running a version of the included example tutorial dag _taskflow_api_etl_ that is set to be on a schedule causes a crash

`
docker exec -ti airflow_airflow-webserver_1 airflow dags backfill test_tutorial_taskflow_api_etl --start-date <any date> --end-date <any date>
`

The following error is received:

`
AttributeError: Can't pickle local object 'test_tutorial_taskflow_api_etl.<locals>.transform'
`

Modifications to this dag, including removing the return values from each function and the parameters in each, yield identical results. Running a single day backfill does *not* cause this crash. Deleting the dag and letting it re-import does not help.

**What you expected to happen**:
The dag should complete the backfill for all days.  I removed the return statement in all functions, and removed the parameters in each of the function definitions thinking this had to do with the passing along of return results but this did not help.

I tested with multiple workers and a single worker as well as with python 3.7. The same result was achieved in all cases. 

**How to reproduce it**:

1. Install an ubuntu VM, versions as specified, 8GB ram, 4 cores
2. Install Docker CE from the docker repositories per their installation directions
3. Download the Airflow docker-compose image, perform the tutorial set up tasks, modify only the airflow image as noted in the versions above (this is a different bug maybe, default causes a crash).
4. `docker-compose up -d`
5. Copy the code in tutorial_taskflow_api_etl, modify to set the schedule_interval to daily, save into ./dags/test.py and let airflow discover it.
6. execute `docker exec -ti airflow_airflow-webserver_1 airflow dags backfill test_tutorial_taskflow_api_etl --start-date <any date> --end-date <any date>`

**Anything else we need to know**:

At least two other dag examples appear to work just fine when executed this way. Neither are using the Taskflow API. Maybe that is a contributing factor.

This crash occurs consistently at every run as described.

**Comment by kaxil** [comment]
Can you take a look at this please @Dr-Denzy

**Comment by Dr-Denzy** [comment]
I am already on it.

**Comment by Dr-Denzy** [comment]
@gschwim I have been able to reproduce the issue. Classically implemented dags backfill work as expected. @kaxil and I are further investigating why the Taskflow API dags backfill are failing.

**Comment by kaxil** [comment]
Where are you running the backfill commands, try running it on Scheduler container instead of the webserver

**Comment by josh-fell** [comment]
FWIW, I'm not able to reproduce this on `main` with Breeze, 2.0.0 in Breeze, nor 2.3.0 with Astro CLI. I used the tutorial_taskflow_api_etl example DAG and changed `schedule_interval="@daily"`.

**Breeze (Airflow 2.0.0)**
Commands: `breeze exec`, `airflow dags backfill test_tutorial_taskflow_api_etl --start-date 2022-05-01 --end-date 2022-05-05`
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48934154/171493809-db374bd7-7098-43dc-9acc-1c84c66471b3.png">


**Breeze (main)**
Commands: `breeze exec`, `airflow dags backfill tutorial_taskflow_api_etl -s 2022-05-01 -e 2022-05-05`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48934154/171489681-a13b98b7-3a87-47c6-835e-448eabc3ac37.png">


**Astro CLI (Astro Runtime 5.0.0, Airflow 2.3.0)**
Command (directly on webserver container): `docker exec -it 2-3-0_d06ac9-webserver-1 airflow dags backfill tutorial_taskflow_api_etl -s 2022-05-01 -e 2022-05-05`
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48934154/171488115-d3494db2-79d6-4262-b29f-f504880c38f3.png">
Command (using built-in Astro CLI command): `astrocloud dev run dags backfill tutorial_taskflow_api_etl -s 2022-05-06 -e 2022-05-10`
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/48934154/171488616-0d19a26b-827d-4dcc-a6f0-fae5f7f650be.png">

@gschwim Does this pickling error still occur on Airflow 2.3.0 with your environment setup? Is the only modification made to the example DAG was the `schedule_interval` initially? Does setting the `--donot-pickle` flag alleviate the issue?
