### ISSUE TITLE
Support utf8mb4 character set better for mysql

### ISSUE THREAD

**Issue by Gabriel39** [apache/airflow#14172]
**Description**

Although the utf8mb4 character set is more and more popular for MySQL (actually, utf8mb4 becomes default character set already) and maybe [utf8mb3 will be removed in future](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html), there are still some problems in current Airflow. 
So if you use utf8mb4 as character set, you should set `sql_engine_collation_for_ids=utf8mb3_general_ci`.

**Use case / motivation**

In Airflow 2.0, when i use mysql database and utf8mb4, i must set `sql_engine_collation_for_ids=utf8mb3_general_ci`. Otherwise, the length of primary key of table xcom will exceed the maximum value 3072 bytes.
So I think we should address this problem to avoid more problems in future.

**Are you willing to submit a PR?**

I'd be willing to

**Comment by potiuk** [comment]
We are not going to do anything about it until MySQL releases a new version. Similarly as in 5.6->5.7 they are likely to increase maximum index size and if they do, the problem will be resolved without any action from our side. This is the plan.
