### ISSUE TITLE
Q: Understanding role of "default_args"

### ISSUE THREAD

**Issue by sabeerzaman** [apache/airflow#1418]
From the documentation that I've read so far, it appears that defining a dict of `default_args` allows setting a global set of arguments that could easily apply to all tasks part of that DAG, but allowing individual task definitions to override those values via their individual constructors.

I was wondering if this applies to `DAG` instances themselves? My team is in a situation where we're defining three DAGs, and for the most part, we expect them all to have the same defaults throughout. However, there may be the need to tweak an argument here and there per DAG. Could we leverage using a common set of `default_args` and override them via the `DAG` constructor?

The following code could help illustrate what I'm asking: 

Suppose we have `dag_a` and `dag_b`, and they both share the same values for `default_args`. But we decide that `dag_a` should run at a different `schedule_interval` than the default. So we set them up as follows:

``` python
# Contents of a `common_config.py`
default_args = {
  'adhoc': False,
  'depends_on_past': False,
  'start_date': datetime(2016, 4, 15),
  'retries': 1,
  'retry_delay': timedelta(minutes=5),
  'schedule_interval': '0 0 * * *"
}
```

``` python
# Contents of `dag_a.py`
from common_config.py import default_args
dag_a = DAG(
  dag_id='dag_a', 
  default_args=default_args,
  schedule_interval="0 5 * * *"  # Different from that in the common `default_args`
}
# ... rest of DAG definition ...
```

``` python
# Contents of `dag_b.py`
from common_config.py import default_args
dag_a = DAG(
  dag_id='dag_b', 
  default_args=default_args
}
# ... rest of DAG definition ...
```

**_In the above setup, will `dag_a` successfully run on the non-default schedule interval of `"0 5 * * *"` while `dag_b` runs on the default one of `"0 0 * * *"`?_**

**Comment by jlowin** [comment]
Hi @sabeerzaman, `default_args` only applies to Operators. It will not override DAG-level parameters.
