### ISSUE TITLE
Infinite redirects when logged in with user which doesn't have any roles

### ISSUE THREAD

**Issue by gaurav1008** [apache/airflow#14181]
Airflow version: 1.10.10, 1.10.14 and 2.0.0

From command line we create a user with Admin role. (lets called it "admin")
Logged in with same user ("admin" )from Airflow UI and created a new user without any role. (lets call it "test").
Airflow screens allows it. 

Now we logged out from current "admin" user and logged in with new user "test".

The screen gets into infinite redirections.

Please refer to following link for issue identified in AppBuilder corresponding to sending wrong Role from Airflow screen which also leads to infinite redirects. 

https://github.com/dpgaspar/Flask-AppBuilder/issues/1554

Please find the document with screen shots.
[Airflow-InfiniteRedirects.docx](https://github.com/apache/airflow/files/5961326/Airflow-InfiniteRedirects.docx)

Note:-The steps to recover from this problem is to give /logout from the browser.

**Comment by jhtimmins** [comment]
@gaurav1008 I believe this was fixed in 2.0.1. Can you verify whether you're still seeing this issue?

**Comment by gaurav1008** [comment]
Tested on below. Its showing same problem.

Version: v2.0.1
Git Version:.release:2.0.1+beb8af5ac6c438c29e2c186145115fb1334a3735

**Comment by blag** [comment]
How are you creating a user without a role?

Attempting to reproduce this on Airflow 2.2.2. The CLI requires you to specify a `--role`, but the web UI doesn't require a role to be specified when creating a user.

However, when attempting to login as that (`test`) user in the web UI, I get:

> Your user has no roles and/or permissions!
> 
> Unfortunately your user has no roles, and therefore you cannot use Airflow.
> 
> Please contact your Airflow administrator (authentication may be misconfigured) or log out to try again.
> 
> test

@gaurav1008 Can you help me reproduce this issue? Or can we close it?

**Comment by potiuk** [comment]
It has been fixed in 2.1.4. https://github.com/apache/airflow/issues/16587 . Closing as duplicate.
