### ISSUE TITLE
Host Airflow's helm chart on ArtifactHub or any Helm charts registry.

### ISSUE THREAD

**Issue by sherifabdlnaby** [apache/airflow#14194]
**Description**

Host the helm chart in `/chart` directory on artifacthub or any helm registry.

**Use case / motivation**

I want to be able to install this helm chart from a helm repository instead of having to maintain a private repo that I manually sync with the upstream.

**Are you willing to submit a PR?**

I can create a PR to generate a helm chart repo using Github Pages, but this is not ideal for something as mature as Airflow.

**Comment by potiuk** [comment]
Closing as duplicate of #10523
