### ISSUE TITLE
Rendered templates not properly formatted

### ISSUE THREAD

**Issue by dimonchik-suvorov** [apache/airflow#14192]
The case is when Airflow preparing a `Rendered Template` view it uses Jinja and Jinja uses a simple `pprint` which returns an ugly result surrounded by redundant single/double quotes in case it can't found and import `pretty` module.

<details>
<summary>Example of how it could be displayed</summary>
<p>

```
('USE test_db;\n'
'\n'
'INSERT OVERWRITE TABLE \n'
' test_table\n'
"PARTITION (part_column = 'some_part_value')\n"
'\n'
'SELECT  \n'
' field1           AS f_1,\n'
' count(*)         AS cnt\n'
'FROM\n'
' source_table\n'
'WHERE\n'
" part_column = 'some_part_value';")
```
</p>
</details>  

The line of Airflow code where it uses Jinja formatting - [views.py#L916](https://github.com/apache/airflow/blob/master/airflow/www/views.py#L916)

**Comment by ryanahamilton** [comment]
Closing this based on [@kaxil's response](https://github.com/apache/airflow/pull/14193#issuecomment-777615243) and the PR closure on #14193
> The library `pretty-py3` is not actively maintained and I am not sure if we should use it that globally.
> 
> Jinja uses built-in library not an external library -
https://github.com/pallets/jinja/blob/f009a004a2e70a3608d49aceb1814b90bb4370d6/src/jinja2/utils.py#L160
> 
> https://docs.python.org/3.8/library/pprint.html
> 
> That said -- I think the users who want it can use the library you mentioned or add their own custom filter.
> 
> You can just do `{{ yourvar| custom_pprint}}` where `custom_pprint` is your custom filter and Jinja will print it nicely I think: https://stackoverflow.com/a/25728848/5691525
