### ISSUE TITLE
Airflow image on Docker Hub is tagged 2.0.1 but appears to be 2.0.1rc2

### ISSUE THREAD

**Issue by johnjeffers** [apache/airflow#14195]
**Apache Airflow version**:
2.0.1

**Environment**:
Docker

**What happened**:
The image on Docker Hub that is tagged `2.0.1` appears to be `2.0.1rc2`:

```
$ airflow version
2.0.1rc2
```

**What you expected to happen**:

`airflow version` returns `2.0.1`

**How to reproduce it**:
```
docker pull apache/airflow:2.0.1

docker run -ti apache/airflow:2.0.1 bash

# inside the container
airflow version
```

**Comment by potiuk** [comment]
Will fix it shortly (weekend likely)

**Comment by potiuk** [comment]
The images for 2.0.1 are pushed. Note that 'apache-airflow' is the same but some dependencies might be updated comaring to 2.0.1rc1 (however they are tested and should work fine). 

They are based on latest python images so they contain latest security fixes (and some keys updated).

Also, by default google 1.0.0 provider is installed in the image. The  2.0.0 was released afterwards and it was backwards-incompatible for installation (dependency conflict) however you are free to extend/customize the image and upgrade to latest version of providers as you see fit (http://airflow.apache.org/docs/apache-airflow/stable/production-deployment.html#customizing-or-extending-the-production-image) 

Please pull the images again and see if they look good to you @johnjeffers . I am closing the ticket, but let us know if you have still some troubles with it.


![Screenshot from 2021-02-15 00-51-24](https://user-images.githubusercontent.com/595491/107892852-0ea4fa00-6f28-11eb-917e-7a562f9b2658.png)

**Comment by potiuk** [comment]
cc: @kaxil 2.0.1 images are pushed

**Comment by kaxil** [comment]
> cc: @kaxil 2.0.1 images are pushed

Thanks @potiuk
