### ISSUE TITLE
Scheduler in helm chart cannot access DAG with git sync 

### ISSUE THREAD

**Issue by alanwu4321** [apache/airflow#14202]
**Apache Airflow version**:
2.0.1

**What happened**:

When dags `git-sync` is `true` and `persistent` is `false`, `airflow dags list` returns nothing and the `DAGS Folder` is empty

**What you expected to happen**:

Scheduler container should still have a volumeMount to read the volume `dags` populated by the `git-sync` container

**How to reproduce it**:
```
  --set dags.persistence.enabled=false \
  --set dags.gitSync.enabled=true \
```
Scheduler cannot access git-sync DAG as Scheduler's configured `DAGS Folder` path isn't mounted on the  volume `dags`

**Comment by edikmkoyan** [comment]
I deployed the branch with the fix, and it indeed fixed the things.
