### ISSUE TITLE
AWS GlueHook does not pass Region name to superclass constructor

### ISSUE THREAD

**Issue by davidshay** [apache/airflow#14217]
https://github.com/apache/airflow/blob/e3bcaa3ba351234effe52ad380345c4e39003fcb/airflow/providers/amazon/aws/hooks/glue.py#L77

**Comment by jhtimmins** [comment]
@davidshay Thanks for bringing this up. Would you like to contribute the patch or would you like me to?

**Comment by davidshay** [comment]
Hello,

I'd have no problem with providing the fix itself, but I don't know how
much work would the whole patch process entails, since I never made any. Is
it long?

Regards,
David

**Comment by isunitha98selvan** [comment]
Hey, if no one is working on this issue, I can submit a patch :)

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/14251
