### ISSUE TITLE
Airflow installation suddenly stopped working few hours back 

### ISSUE THREAD

**Issue by debugger22** [apache/airflow#14229]
Python version: 3.6
pip version: 21.0.1 (Also tried with older version as written in doc)
os: Ubuntu 18.04

```
pip install apache-airflow==2.0.1 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt
ERROR: Could not find a version that satisfies the requirement apache-airflow==2.0.1
ERROR: No matching distribution found for apache-airflow==2.0.1
```

**Comment by debugger22** [comment]
Sorry, the template was very big for such a simple behaviour. I can provide more information if asked.

**Comment by mpolatcan** [comment]
Problem is that https://github.com/apache/airflow/blob/constraints-2-0/constraints-3.8.txt in line 104, apache-airflow==2.1.0.dev0, there is no version 2.1.0.dev0 on PYPI. It seems that @potiuk your update has broken constraint file for version 2.0.1 :)

**Comment by debugger22** [comment]
@mpolatcan I think your assessment is correct! Can this be fixed anytime soon? Tomorrow is Monday!

**Comment by mpolatcan** [comment]
I don't know anything about that. Also, I have been working on that so I will continue install Airflow without constraint :)

**Comment by debugger22** [comment]
Thanks!

**Comment by potiuk** [comment]
It should be fixed now. Please let me know if it works!

Sorry for this - I am automating it for future versions and I semi-automated it for 2.0.0 and 2.0.1 but those dev0 slipped throuh my radar.

**Comment by potiuk** [comment]
I tested it locally and it works for me :D

**Comment by debugger22** [comment]
Yep, worked for me as well. Thanks for the quick fix!

**Comment by mpolatcan** [comment]
Thanks for the quick fix @potiuk 👍 🤗

**Comment by potiuk** [comment]
Would be better if it did not happen :) . I will be more careful next time
