### ISSUE TITLE
How do I trigger an operator to run after a certain time?

### ISSUE THREAD

**Issue by sudowork** [apache/airflow#1423]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow: v1.7.0
- Airflow components and configuration: Using `LocalExecutor`
- Screen shots of your DAG's graph and tree views:
  ![image](https://cloud.githubusercontent.com/assets/1113327/14750350/34aeef5a-0879-11e6-8bd6-da947ab25619.png)
  ![image](https://cloud.githubusercontent.com/assets/1113327/14750408/88897960-0879-11e6-8de4-061fa97c457f.png)
- DAG code:

``` python
from datetime import datetime

from airflow.models import DAG
from airflow.operators import BashOperator, DummyOperator, SubDagOperator

DAG_NAME = 'test-dag'

def subdag(parent_dag_name, child_dag_name, args, schedule_interval):
    return DAG(
        dag_id='%s.%s' % (parent_dag_name, child_dag_name),
        default_args=args,
        schedule_interval=schedule_interval,
        max_active_runs=1,
    )

args = {
    'owner': 'airflow',
    'start_date': datetime(2016, 04, 20),
    'retries': 0,
}

# DAGs

dag = DAG(
    dag_id=DAG_NAME,
    default_args=args,
    schedule_interval='0 * * * *',
    max_active_runs=1,
)

dag_time_trigger = subdag(DAG_NAME, 'time-based-trigger', args, '30 * * * *')

# Operators

start = DummyOperator(
    task_id='start',
    default_args=args,
    dag=dag,
)

pre_calculation = BashOperator(
    task_id='pre-calculation',
    bash_command="""
        echo "pre-calculation $(date)"
    """,
    dag=dag,
)

time_trigger= SubDagOperator(
    task_id='time-based-trigger',
    subdag=dag_time_trigger,
    default_args=args,
    dag=dag
)

send_notifications = BashOperator(
    task_id='send-notifications',
    bash_command="""
        echo "send-notifications $(date)"
    """,
    default_args=args,
    dag=dag,
)

end = DummyOperator(
    task_id='end',
    default_args=args,
    dag=dag,
)

# subdag operators

dummy_trigger = BashOperator(
    task_id='trigger',
    bash_command="""
        echo "triggering time-based-trigger $(date)"
    """,
    default_args=args,
    dag=dag_time_trigger,
)

# Set up DAG paths

start.set_downstream(pre_calculation)
pre_calculation.set_downstream(send_notifications)
time_trigger.set_downstream(send_notifications) # from subdag
send_notifications.set_downstream(end)
```

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue

What I was trying to accomplish was to have an operator that both depended on the completion of its upstream tasks AND happening after a certain time.
- What did you expect to happen?
  Because I set the dag `schedule_interval` to `0 * * * *` and the subdag `schedule_interval` to `30 * * * *`, I expected the following to happen:
  - Roughly at every hour, the DAG `test-dag` would be started
  - The `start` and `pre-calculation` tasks should directly after
  - The `send-notifications` task should remain blocked by the `time-based-trigger` subdag
  - At about the 30 minute mark for that hour, the subdag should start
  - After the subdag completes, the `send-notifications` and then `end` tasks should follow.
- What happened instead?
  The SubDagOperator started immediately after `pre-calculation` finished. Zooming into that subdag, I also verified that as a result the `trigger` task completes almost immediately instead of happening after the 30 minute mark.
- Here is how you can reproduce this issue on your machine:
### Reproduction Steps
1. Run the DAG provided

**Comment by jlowin** [comment]
This is a nuance but SubDags don't get scheduled; therefore they ignore parameters like schedule_interval. Instead, what happens is your SubDagOperator forces the subdag to run when the SDO is run. That's why you're not seeing the behavior you expect.

You might want to use a `TimeSensor` instead -- that will block until a certain time of day. However it may require some modification for multiple runs per day. Have a look at the code in `operators/sensors.py`. 

We are moving all issues to Apache, so I'm going to close this issue, but if you have further questions please pick up over there!
