### ISSUE TITLE
upgrade checker missing rule

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#14232]
**What happened**:

The current upgrade-checker (1.2.0) doesn't have rule handle moving of classes / functions in the utils path.

Example:
from airflow.utils.db import create_session
changed to:
from airflow.utils.session import create_session

**What you expected to happen**:
provide notice on these changes.

**Comment by Dr-Denzy** [comment]
I will look into this.

**Comment by Dr-Denzy** [comment]
@HaloKo4 This should be a `kind:feature` and not necessarily a bug.

**Comment by eladkal** [comment]
@Dr-Denzy on 2nd thought, after reading carefully the issue again this task should not be done.
https://github.com/apache/airflow/blob/2fa3774608af9369135381c45529d3cf6f8c0e1a/airflow/utils/db.py#L38
isn't deprecated on 1.10.14
The function is deprecated only from >=2.0.0 so there is no action to take when upgrading from 1.10.14 to 2.0
We already decided not to suggest changes that will break dags on 1.10.x https://github.com/apache/airflow/pull/13012
