### ISSUE TITLE
checker update output as csv

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#14233]
**Description**

The checker update provide list of entries to handle.
Specifically in the path section (contrib -> providers) the list can be massive.
We have over 400 dags in our system handled by more than 30 different teams. Consider that each dag imports many hooks, sensor, operators and you get a list with thoulzends of enteries.
The list is impossible to handle in the current structure. It will take us weeks to go over this whole list and compile something that we can send to the teams (each team needs to see their dags and not hundreds of other entreries). More importantly even if we do this it won't be enough as we need to periodically compile updated report to see the progress.

This makes really hard to create an upgrade plans shared across many developers.

We are looking to get the information as csv with the following structure:
`dag_id , owner, old_path, new_path`

is this possible?

**Comment by eladkal** [comment]
Closing as there will be no more releases of upgrade check
