### ISSUE TITLE
DAG concurrency is not honored

### ISSUE THREAD

**Issue by shenghuy** [apache/airflow#1424]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow: 1.6.2
- Airflow configuration: Running a Scheduler with **LocalExecutor**
- Operating System: 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Python Version:  2.7.6
- Screen shots of your DAG's status:

![image](https://cloud.githubusercontent.com/assets/4205590/14751524/1f930c86-087f-11e6-824d-2f920f1299e5.png)

![image](https://cloud.githubusercontent.com/assets/4205590/14751546/3222373c-087f-11e6-996e-66ae1ad6ade9.png)

Now that you know a little about me, let me tell you about the issue I am having:
### Description of Issue

In our dag, we set the **dag_args['concurrency'] = 8,** however, when the scheduler starts to run, we can see this concurrency is not being honored, airflow scheduler will run up to num of the 'parallelism' (we set as 25) jobs.
- What did you expect to happen?
  dag_args['concurrency'] = 8 is honored, e.g. only run at most 8 jobs concurrently.
- What happened instead?
  when the dag starts to run, we can see the concurrency is not being honored, airflow scheduler will run up to the 'parallelism' (we set as 25) jobs.
- Here is how you can reproduce this issue on your machine:
- **create a dag which contains nothing but 25 parallelized jobs.**
- set the dag dag_args['concurrency'] = 8
- set the airflow parallelism to 25
- then run: airflow scheduler
- you will see all 25 jobs are scheduled to run, not 8.

**Comment by kretes** [comment]
Just to be sure - from your scree I can see concurrency 8 and you refer to 5 in the description are you sure you are setting it up correctly?

Do you observe the problem with 'concurrency' setting "concurrency (int) – the number of task instances allowed to run concurrently" or the "max_active_runs (int) – maximum number of active DAG runs, beyond this number of DAG runs in a running state, the scheduler won’t create new active DAG runs" ?

I'm asking because I see an issue with the 'max_active_runs' and wonder if it is related

**Comment by shenghuy** [comment]
@kretes the concurrency should be 8, it was typo & i have fixed it in the original question as well.

We set the max_active_runs_per_dag = 1, which is working fine. The problem is with this 1 active dag, we expect that only 8 jobs be running concurrently, but 25 jobs are running at the same time.

**Comment by bolkedebruin** [comment]
Please create a Jira issue and link it to AIRFLOW-72. Thanks!

**Comment by shenghuy** [comment]
@bolkedebruin  done. https://issues.apache.org/jira/browse/AIRFLOW-113.

**Comment by bolkedebruin** [comment]
@shenghuy Thanks, can you close this one (we cannot currently)?
