### ISSUE TITLE
Breeze: Specifiying "-install-airflow-version 2.0.1" produces error on Image build 

### ISSUE THREAD

**Issue by grantav** [apache/airflow#14255]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): "elementary OS 5.1.7 Hera"
- **Kernel** (e.g. `uname -a`): "Linux 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
- **Install tools**: Anaconda3
- **Others**: Python 3.7.6, Docker version 19.03.6, build 369ce74a3c, docker-compose version 1.28.2, build 67630359

**What happened**:

When running the following command:
`./breeze start-airflow --python 3.8 --install-airflow-version 2.0.1 --backend postgres --postgres-version 9.6`
If I choose to rebuild the CI image, I get the following error:
`Please confirm rebuild image CI-python3.8. Are you sure? [y/N/q]
y
....
airflow-providers-zendesk
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Requirement already up-to-date: pip==20.2.4 in /usr/local/lib/python3.8/site-packages (20.2.4)
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-ftp, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-http, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-imap, which is not installed.
apache-airflow 2.1.0.dev0 requires apache-airflow-providers-sqlite, which is not installed.
apache-beam 2.27.0 has requirement dill<0.3.2,>=0.3.1.1, but you have dill 0.3.3.
apache-beam 2.27.0 has requirement httplib2<0.18.0,>=0.8, but you have httplib2 0.18.1.
apache-beam 2.27.0 has requirement mock<3.0.0,>=1.0.1, but you have mock 4.0.2.
The command '/bin/bash -o pipefail -e -u -x -c if [[ ${INSTALL_FROM_PYPI} == "true" ]]; then         bash /scripts/docker/install_airflow.sh;     fi' returned a non-zero code: 1
ERROR: The previous step completed with error. Please take a look at output above`

**What you expected to happen**: The image would build accordingly

**How to reproduce it**: `./breeze start-airflow --python 3.8 --install-airflow-version 2.0.1 --backend postgres --postgres-version 9.6`

**Anything else we need to know**: Jarek asked me to log this issue on the slack channel. I'm a n00b at this, but I am looking forward to contributing.

**Comment by potiuk** [comment]
This is now woking fine. It was fixed by one of the earlier fixes with the constraints.
