### ISSUE TITLE
Airflow times out on Long Running Kubernetes Jobs with logging gaps

### ISSUE THREAD

**Issue by alittlesliceoftom** [apache/airflow#14259]
This is listed too in other locations:

https://issues.apache.org/jira/browse/AIRFLOW-3534
https://issues.apache.org/jira/browse/AIRFLOW-4526

Only known fix is to disable log stream: 
`When disabling the `get_logs` parameter everything works because the log stream is skipped.`

Suggested fix - up the retry count on the below line, or allow this to be configured. 
https://github.com/apache/airflow/blob/b23fc137812f5eabf7834e07e032915e2a504c17/airflow/kubernetes/pod_launcher.py#L198

**Comment by alittlesliceoftom** [comment]
Happy to raise this as a PR, I.e. changing 
` @tenacity.retry(stop=tenacity.stop_after_attempt(3), wait=tenacity.wait_exponential(), reraise=True) `
to
` @tenacity.retry(stop=tenacity.stop_after_attempt(5), wait=tenacity.wait_exponential(), reraise=True) `
Which I think would solve the issue for most people and make this much more usable, but I'm not used to this code base!

**Comment by alittlesliceoftom** [comment]
(note my version exp issue was 1.1.14

**Comment by alittlesliceoftom** [comment]
)

**Comment by alittlesliceoftom** [comment]
Note, I tried this fix and it **didn't work**. The best thread I have found is this one: 

https://github.com/apache/airflow/pull/7428#issuecomment-704994507

**Comment by eladkal** [comment]
Does this happens with latest Airflow version?
