### ISSUE TITLE
ERROR - Parameter validation failed when submitting a job using AwsBatchOperator

### ISSUE THREAD

**Issue by JoostKooijman** [apache/airflow#14275]
**Apache Airflow version**: 2.0.0

**Environment**:

- **Cloud provider or hardware configuration**: AWS ECS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When I'm submitting a job to AWS batch using `AwsBatchOperator` I get the following error message:
`[2021-02-16 00:05:51,776] {{batch.py:182}} ERROR - AWS Batch job (None) failed submission
[2021-02-16 00:05:51,780] {{taskinstance.py:1455}} ERROR - Parameter validation failed:
Unknown parameter in input: "tags", must be one of: jobName, jobQueue, arrayProperties, dependsOn, jobDefinition, parameters, containerOverrides, retryStrategy, timeout`

**What you expected to happen**:
I expect the batch to be submitted after running the operator. I've currently solved it by creating a custom class which inherits the `AwsBatchOperator` and removed line 175, `tags=self.tags,`  from the `submit_job` function from [airflow/airflow/providers/amazon/aws/operators/batch.py](https://github.com/apache/airflow/blob/b23fc137812f5eabf7834e07e032915e2a504c17/airflow/providers/amazon/aws/operators/batch.py#L37). After doing this the job gets submitted as expected.

Ps. For us this started happening from 2021-02-11 onwards.

**Comment by eladkal** [comment]
@JoostKooijman what version of boto3 are you running? Could it be that you running version older than 1.15.0?

**Comment by JoostKooijman** [comment]
@eladkal that's correct, I'm running 1.7.3

**Comment by eladkal** [comment]
> @eladkal that's correct, I'm running 1.7.3

Tag support was added in later version
https://boto3.amazonaws.com/v1/documentation/api/1.16.0/reference/services/batch.html#Batch.Client.submit_job

**Comment by eladkal** [comment]
closing as there seems to be no task here.
If you think otherwise please comment and explain
