### ISSUE TITLE
from 'apache-airflow-providers-google' package: No module named 'airflow.providers.postgres'

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [apache/airflow#14286]
**Apache Airflow version**: 2.0.1

**Environment**:

- **Cloud provider or hardware configuration**: MacBook Pro
- **OS** (e.g. from /etc/os-release): Catalina 10.15.7
- **Kernel** (e.g. `uname -a`): Darwin CSchillebeeckx-0589.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
- **Install tools**: pip

requirements.txt
```
apache-airflow[crypto,celery,amazon,mysql,jdbc,password,redis,slack,snowflake,ssh,google,databricks,mongo,zendesk,papermill,salesforce]==2.0.1
pyarrow==0.17.1
iniconfig==1.1.1
sqlparse==0.4.1
google-api-python-client===1.12.8
google-auth==1.27.0
google-api-core==1.26.0
avro-python3==1.10.0
databricks-connect==7.3.8
matplotlib==3.3.4
scikit-learn==0.24.1
ipykernel==5.4.3
flower==0.9.7

```

**What happened**:

I'm using MySQL as a backend and am using the `GoogleBaseHook`; when I run the webserver I see:
```
webserver_1  | [2021-02-16 23:39:13,008] {providers_manager.py:299} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.postgres'
webserver_1  | [2021-02-16 23:39:13,009] {providers_manager.py:299} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLDatabaseHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.postgres'
webserver_1  | [2021-02-16 23:39:13,066] {providers_manager.py:299} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.postgres'
webserver_1  | [2021-02-16 23:39:13,067] {providers_manager.py:299} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLDatabaseHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.postgres'
```

If I add the extra package `postgres` the warnings are not present anymore.

**What you expected to happen**:

No warnings

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Yep. We could remove the warnings indeed.

**Comment by OBITORASU** [comment]
Can I work on this particular issue? I am assuming addding ```postgres``` to ```apache-airflow[crypto,celery,amazon,mysql,jdbc,password,redis,slack,snowflake,ssh,google,databricks,mongo,zendesk,papermill,salesforce]==2.0.1``` this line should cover the warnings (correct me if I am wrong).

**Comment by potiuk** [comment]
Sure. Feel free. I think the gist is that we should log those warnings at info level not warning :)

**Comment by potiuk** [comment]
Those warnings here are not really warnings - they will happen if you do not have all providers installed, but they should not be treated as warnings, this is expected behaviour, so it should be INFO.

**Comment by OBITORASU** [comment]
Checking the error log and your suggestions above, should my approach be to introduce changes to ```providers_manager.py``` file and change the ```log.warning``` to ```log.info``` on line 295 to fix this issue? Hoping to hear back from you, thanks for your time and patience!

**Comment by ConstantinoSchillebeeckx** [comment]
Even at `INFO`, isn't this going to be really chatty? I think the webserver will just keep emitting those statements; I don't know this codebase well at all, but wouldn't a better fix be not to emit that message if it's not needed?

**Comment by potiuk** [comment]
This should be a one-time only message per webserver process only at the start of the process. Do you see it more often/repeated @ConstantinoSchillebeeckx  ?

**Comment by potiuk** [comment]
What we could do indeed, we could actually handle this a bit better - we could capture the warnings and print a nice summary indicating what is really going on. In this case we could aggregate all of the warning of this form:

```
WARNING: No module named 'airflow.providers.postgres'"
```
 into 
```
INFO: "Some of the features of `apache-airflow-providers-google` provider are not available . Please install 'apache-airflow-providers-postgres' to use "CloudSQLHook". "CloudSQLDatabaseHook" ... 
```

This could be much nicer and informative and I think they are worth seing in logs as "INFO".

WDYT @ConstantinoSchillebeeckx ?

**Comment by potiuk** [comment]
@OBITORASU -> Just hold on for a moment, @ConstantinoSchillebeeckx 's point made me think ^^  - this migth be a bit better approach to turn it into more informative message (see above comment)

**Comment by ConstantinoSchillebeeckx** [comment]
> This should be a one-time only message per webserver process only at the start of the process. Do you see it more often/repeated @ConstantinoSchillebeeckx ?

I'm seeing the warnings constantly being emitted

![Untitled](https://user-images.githubusercontent.com/8518288/108412151-7b094d00-71f7-11eb-9790-18216a718510.gif)

**Comment by OBITORASU** [comment]
Repeating the info can indeed be annoying for the user if the server keeps emitting ```INFO``` same as ```WARNINGS``` in the above example. Any ideas on how to handle this case?

**Comment by potiuk** [comment]
That's strange to see it repeated. This might happen once per process  if you have many processes but I am nto sure this is what happens here. Maybe it just repeats few times and stops? I think this might happen by gunicorn spawning few processes after webserver starts. Does it ever stop @ConstantinoSchillebeeckx or does it continue forever?

**Comment by ConstantinoSchillebeeckx** [comment]
> Does it ever stop @ConstantinoSchillebeeckx or does it continue forever?

@potiuk I don't know that I can comment about it continuing _forever_ 🤣 ; however I did observe these `WARNINGS` for over 20 minutes.

**Comment by potiuk** [comment]
:rofl: Indeed I do not want you to wait THAT long.

**Comment by potiuk** [comment]
I will check it during the weekend

**Comment by OBITORASU** [comment]
I guess I will wait until this is investigated further then.

**Comment by ashb** [comment]
@potiuk We've fixed this now with the latest batch of provider releases haven't we?

**Comment by potiuk** [comment]
Still needs investigation - it's not really a provider's issue but rather provider's manager (which is part of Airflow itself. So It still needs taking a look and likely releasing in 2.0.2

**Comment by potiuk** [comment]
I'll take a look shortly (tomorrow). This should be an easy fix.

**Comment by OBITORASU** [comment]
Dropping in because the thread is revived. I am kind of in a bad spot with my time management (stacked in middle of exams), so I don't think I would be able to put enough time and effort on this issue. Due to the above circumstances, I would like unassign myself from this issue. I do hope some other new contributor picks this one up. Sorry for the inconvenience :(

**Comment by ConstantinoSchillebeeckx** [comment]
I can pick this up if no one minds; if someone can nudge me in the right direction that would be great.

**Comment by potiuk** [comment]
@ConstantinoSchillebeeckx  - I think the main task is to diagnose it to see what is really the issue here. I expected that those warnings will only be printed once (which would be acceptable) but seems in the webserver they continue spamming the logs - I will have time to take a look tomorrow, but if you want, you can pick it before.

**Comment by ashb** [comment]
> @ConstantinoSchillebeeckx - I think the main task is to diagnose it to see what is really the issue here. I expected that those warnings will only be printed once (which would be acceptable) but seems in the webserver they continue spamming the logs - I will have time to take a look tomorrow, but if you want, you can pick it before.

On webserver boot up, the app is loaded once before starting gunicorn, then again for each of the (by default 4) workers, and then by default one webserver worker is replaced every 30s. Each time a web process starts up it will load the providers and produce these logs.

**Comment by potiuk** [comment]
Yep. Makes sense. Just started looking at it :)

**Comment by potiuk** [comment]
Yep. Just  reproduced it. The warnings come every 30 s

**Comment by potiuk** [comment]
@OBITORASU @ConstantinoSchillebeeckx -> #14903  to address it.
