### ISSUE TITLE
Migration of env_vars from dict to a List[V1EnvVar] for KubernetesPodOperator breaks Jinja template processing of env_vars with templates like {{ dags.conf['val1'] }} in KubernetesPodOperator

### ISSUE THREAD

**Issue by dkotsikau** [apache/airflow#14287]
**Environment:**
Airflow 2.0.1, Python 3.7.9. KubernetesExecutor is set in the configuration.

**Issue:**
KubernetsPodOperators does not process env_vars with Jinja templates like {{ dag.conf['key'] }} and leaves text as is, no substitution is done.

The method  [render_template](https://github.com/apache/airflow/blob/2.0.1/airflow/models/baseoperator.py#L875) of BaseOperator checks types of content using  

```Python
if isinstance(content, <some_type>):
```

As **env_vars** of type List[V1EnvVar]  is submitted to [render_template](https://github.com/apache/airflow/blob/2.0.1/airflow/models/baseoperator.py#L922) as a content parameter and has type 'list', it is passed to that part:

```Python
elif isinstance(content, list):
     return [self.render_template(element, context, jinja_env) for element in content]
```

 But elements now have type <class 'kubernetes.client.models.v1_env_var.V1EnvVar'>, not a 'dict'

 Old version would have processed the template in the following [part](https://github.com/apache/airflow/blob/2.0.1/airflow/models/baseoperator.py#L925):

```Python
elif isinstance(content, dict):
     return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
```

But now it goes to [the very end of the method](https://github.com/apache/airflow/blob/2.0.1/airflow/models/baseoperator.py#L931), into the final 'else'.  The type <class 'kubernetes.client.models.v1_env_var.V1EnvVar'> is not mentioned anywhere above and this part is the last resort for it.

 ```Python
else:
     if seen_oids is None:
           seen_oids = set()
     self._render_nested_template_fields(content, context, jinja_env, seen_oids)
```

This part does nothing as env_vars elements are not nested templates.

[KubernetesPodOperator](https://github.com/apache/airflow/blob/2.0.1/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L158) has the following list of fields that support substitution by Jinja

```Python
template_fields: Iterable[str] = (
        'image',
        'cmds',
        'arguments',
        'env_vars',
        'labels',
        'config_file',
        'pod_template_file', 
```

It happens when a dag triggers another dag and sets env_vars. 

**What is expected**
.Expansion of templates in env_vars should be supported.

**Comment by gm55** [comment]
As a temporary solution it can be something like that
```diff
--- airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py	(date 1612472719000)
+++ airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py	(date 1613645533626)
@@ -17,8 +17,9 @@
 """Executes task in a Kubernetes POD"""
 import re
 import warnings
-from typing import Any, Dict, Iterable, List, Optional, Tuple
+from typing import Any, Dict, Iterable, List, Optional, Tuple, Set
 
+import jinja2
 import yaml
 from kubernetes.client import CoreV1Api, models as k8s
 
@@ -532,3 +533,39 @@
             if self.termination_grace_period is not None:
                 kwargs = {"grace_period_seconds": self.termination_grace_period}
             self.client.delete_namespaced_pod(name=name, namespace=namespace, **kwargs)
+
+    def render_template(  # pylint: disable=too-many-return-statements
+        self,
+        content: Any,
+        context: Dict,
+        jinja_env: Optional[jinja2.Environment] = None,
+        seen_oids: Optional[Set] = None,
+    ) -> Any:
+        """
+        Render a templated string. The content can be a collection holding multiple templated strings and will
+        be templated recursively.
+
+        :param content: Content to template. Only strings can be templated (may be inside collection).
+        :type content: Any
+        :param context: Dict with values to apply on templated content
+        :type context: dict
+        :param jinja_env: Jinja environment. Can be provided to avoid re-creating Jinja environments during
+            recursion.
+        :type jinja_env: jinja2.Environment
+        :param seen_oids: template fields already rendered (to avoid RecursionError on circular dependencies)
+        :type seen_oids: set
+        :return: Templated content
+        """
+        if not jinja_env:
+            jinja_env = self.get_template_env()
+
+        if isinstance(content, k8s.V1EnvVar):
+            if isinstance(content.value, str):
+                return k8s.V1EnvVar(name=content.name, value=jinja_env.from_string(content.value).render(**context), value_from=content.value_from)
+            else:
+                return k8s.V1EnvVar(name=content.name, value=content.value, value_from=content.value_from)
+
+        elif isinstance(content, list):
+            return [self.render_template(element, context, jinja_env) for element in content]
+        else:
+            return super(KubernetesPodOperator, self).render_template(content, context, jinja_env, seen_oids))
```

**Comment by kaxil** [comment]
This should be fixed by https://github.com/apache/airflow/pull/14123 

@ashb / @dimberman / @potiuk Can one of you release new version of cncf.kubernetes providers please

**Comment by kaxil** [comment]
Created a separate ticket for it: https://github.com/apache/airflow/issues/14463
