### ISSUE TITLE
To capitalise or not to capitalise

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [apache/airflow#14283]
While reading Airflow materials in the repo, i've seen great disparity as to how names are written. pytest is written with a lowercase p and in some rare cases in with a P. SQLAlchemy turns sometimes into sqlalchemy. Gunicorn into gunicorn. Sometimes you configure Kubernetes sometimes kubernetes. Etc Etc Etc. 

While not a bug, it does seem Funny siwtching Case Randomly. It however occurs only in the case of library or tech stack or db names. 

Should all names be capitalised? should it be left in no caps? Some docs adhere to caps rigourously, some no. 

I am prepared to rectify the whole docs to whichever style choosen in two phases:

- Phase 1: Non docs file like contributing.rst, testing.rst, ci.rst etc
- Phase 2: The docs itself

**Comment by mik-laj** [comment]
I try to stick to the rules described in [the Google developer documentation style guide](https://developers.google.com/style/capitalization
) and [PEP-8 - Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/). The first describes the rules for writing documentation and the second describes the class names. 

>. Follow the official capitalization for the names of brands, companies, software, products, services, features, and terms defined by companies and open source communities.

~ Google developer documentation style guide

> CapitalizedWords (or CapWords, or CamelCase -- so named because of the bumpy look of its letters [4]). This is also sometimes known as StudlyCaps.
>. 
> Note: When using acronyms in CapWords, capitalize all the letters of the acronym. Thus HTTPServerError is better than HttpServerError.

~ PEP-8

> pytest is written with a lowercase p and in some rare cases in with a P

The official project documentation uses the name "pytest" and this is correct.
<img width="524" alt="Screenshot 2021-02-26 at 23 18 16" src="https://user-images.githubusercontent.com/12058428/109361256-ed79cd00-7888-11eb-97cd-971a0f297275.png">
Even at the beginning of a sentence, we should use a lowercase letter
<img width="228" alt="Screenshot 2021-02-26 at 23 18 59" src="https://user-images.githubusercontent.com/12058428/109361319-07b3ab00-7889-11eb-9c59-ccdbfe251dad.png">

> SQLAlchemy turns sometimes into sqlalchemy.

We should use "SQLAlchemy",  if we use the product name, but lowercase if we are referring to the package name.

<img width="593" alt="Screenshot 2021-02-26 at 23 22 43" src="https://user-images.githubusercontent.com/12058428/109361670-ae984700-7889-11eb-96fe-1b077528938a.png">

> Gunicorn into gunicorn. 

We should use "Gunicorn" when referring to the project name, but "gunicorn" when referring to the python package or command name.

> Sometimes you configure Kubernetes sometimes kubernetes.

We should use "Kubernetes" when referring to the project name, but "kubernetes" when referring to the python package.

**Comment by mik-laj** [comment]
Are you willing to submit a PR? I am happy to help with the review.

**Comment by potiuk** [comment]
Yep. I think there is often distinction between "Product Name" and "tool name" (deliberately written this way). So the naming is not often Random Case even if those are different (but sometimes indeed it is). So it can't be fixed automatically - you need to understand the context.

As @mik-laj - I am happy to review PRs that you might come up with on that.

**Comment by Abdur-rahmaanJ** [comment]
@mik-laj i am ready to PR, was just waiting for the direction to go

**Comment by potiuk** [comment]
> @mik-laj i am ready to PR, was just waiting for the direction to go

I think direction are clear @Abdur-rahmaanJ -> when  used as "Product" names should follow official product name. When used as "tool" usually the tools have lowercase names. So it depends on the context .

**Comment by Abdur-rahmaanJ** [comment]
Companion PR: #14534

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/14534
