### ISSUE TITLE
airflow-upgrade-check complains about spark imports i don't have

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#14295]
my dag has:
```
import datetime as dt
import glob
import json
import logging
import os
import subprocess
import traceback
from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.operators.python_operator import PythonOperator
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import BranchPythonOperator
from airflow.hooks.base_hook import BaseHook
```

i am on airflow 1.10.14, running airflow-upgrade-check 1.2.0 complains about:
```
airflow.contrib.operators.spark_jdbc_operator.SparkSubmitOperator
airflow.contrib.operators.spark_submit_operator.SparkSubmitOperator
```
ie
```Using `airflow.contrib.operators.spark_submit_operator.SparkSubmitOperator` should be replaced by `airflow.providers.apache.spark.operators.spark_submit.SparkSubmitOperator````

but my dag never imports them?

**Comment by eladkal** [comment]
same issue as https://github.com/apache/airflow/issues/13570 ?
Can you see if the https://github.com/apache/airflow/pull/13622 solves this?

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/14493
