### ISSUE TITLE
make dag link customizable from "main" list view

### ISSUE THREAD

**Issue by andres-lowrie** [apache/airflow#14298]
**Description**

Would be nice if the Dag link from the main list view could be customized. For example, instead of linking to the tree view have it link to the graph view by default.

**Use case / motivation**

I find myself always going to the graph view more often than the tree view, in particular when having to clear tasks and all that

**Are you willing to submit a PR?**

If someone could point me in the right direction, I'll be more than happy to send up a PR

**Comment by tooptoop4** [comment]
https://github.com/apache/airflow/blob/master/airflow/config_templates/default_airflow.cfg#L531 it is customisable, you can change that value @andres-lowrie

**Comment by andres-lowrie** [comment]
sweet... my apologies for not rtfm 😂
