### ISSUE TITLE
activate serialization should be noted on airflow upgrade check

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#14291]
**Description**
The doc says 
>From Airflow 2.0 DAG Serialization is a strictly required and can not be turned off.

but when we run the upgrade check we were not informed that we need to set this up.

**Use case / motivation**
I think it's better to make sure serialization works on 1.10.14 and only then migrate to Airflow 2
a notice about this on the checker can help to others i believe

**Comment by ashb** [comment]
Enabling serialization before upgrading isn't strictly required, and I don't think there's anything that can really break in this area by just upgrading.

Have you experienced something that doesn't work with DAG serialization turned on?

**Comment by alexInhert** [comment]
@ashb we encounter several issues which we don't know what exactly they are due to that we thought we should handle each change as "stand alone" as much as we can but I see your point. I'll close this.

**Comment by ashb** [comment]
If there's something that you suspect is caused by serialization we can reopen this.

We want to make upgrading as easy as possible, so let us know how we can help.
