### ISSUE TITLE
EmailOperator CC parameter does not support DagParam type like To parameter does 

### ISSUE THREAD

**Issue by hedrickw** [apache/airflow#14300]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Linux

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Following the example here (https://github.com/apache/airflow/blob/master/airflow/example_dags/example_dag_decorator.py) I tried to add cc param for the email operator like below
```
@dag(default_args=DEFAULT_ARGS, schedule_interval=None, start_date=days_ago(2), tags=['example'])
def example_dag_decorator(email: str = 'example@example.com', email_cc: str = 'example2@example.com'):
    """
    DAG to send server IP to email.
    :param email: Email to send IP to. Defaults to example@example.com.
    :type email: str
    """
    get_ip = GetRequestOperator(task_id='get_ip', url="http://httpbin.org/get")

    @task(multiple_outputs=True)
    def prepare_email(raw_json: Dict[str, Any]) -> Dict[str, str]:
        external_ip = raw_json['origin']
        return {
            'subject': f'Server connected from {external_ip}',
            'body': f'Seems like today your server executing Airflow is connected from IP {external_ip}<br>',
        }

    email_info = prepare_email(get_ip.output)

    EmailOperator(
        task_id='send_email', to=email, cc=email_cc, subject=email_info['subject'], html_content=email_info['body']
    )


dag = example_dag_decorator()
# [END dag_decorator_usage]
```
I get the following error:

 cc = get_email_address_list(cc)
  File "/opt/app-root/lib64/python3.8/site-packages/airflow/utils/email.py", line 213, in get_email_address_list
    raise TypeError(f"Unexpected argument type: Received '{received_type}'.")
TypeError: Unexpected argument type: Received 'DagParam'.

**What you expected to happen**:
CC parameter to work like the To parameter

**How to reproduce it**:

See Example above

**Anything else we need to know**:
I dont know if this is a bug or not if its not a bug can we mark this a feature request?

**Comment by VBhojawala** [comment]
I think you are passing string to  "cc=email_cc" instead of list of string that is why you are getting
 TypeError(f"Unexpected argument type: Received '{received_type}'.")

Kindly check the official document describing arguments type of EmailOperator in below link :

https://airflow.apache.org/docs/apache-airflow/1.10.9/_modules/airflow/operators/email_operator.html
