### ISSUE TITLE
Remote log on azure blob storage display issue on microsoft provider airflow/providers/microsoft/azure/log/wasb_task_handler.py

### ISSUE THREAD

**Issue by heeroyuy925** [apache/airflow#14312]
**Apache Airflow version**: 2.1.0.dev0

**Environment**: docker-compose

**pip package I installed**: 
azure-storage-blob                 12.7.1

**What happened**: 
In my spike environment, we are testing to store remote log to Azure blob storage. 

When we triggered the example dags, we find the log is displayed in one line which is hard to read. 

For example:
  *** Reading remote log from platform-boundary-airflowlogs/example_bash_operator/also_run_this/2021-02-07T03:42:07.725535+00:00/1.log.
b'[2021-02-07 03:42:14,900] {taskinstance.py:1739} DEBUG - Updating task params ({\'example_key\': \'example_value\'}) with DagRun.conf ({\'example_key\': \'example_value\'})\n[2021-02-07 03:42:14,901] {executor_loader.py:82} DEBUG - Loading core executor: LocalExecutor\n[2021-02-07 03:42:14,936] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner\n[2021-02-07 03:42:14,957] {taskinstance.py:1739} DEBUG -----------------------'

**What you expected to happen**:
The log on UI can be displayed as follow:

Reading remote log from platform-boundary-airflowlogs/example_bash_operator/runme_0/2021-02-18T09:07:31.667381+00:00/1.log.
[2021-02-18 09:07:33,878] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-18T09:07:31.667381+00:00 [queued]>
[2021-02-18 09:07:33,950] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-18T09:07:31.667381+00:00 [queued]>
[2021-02-18 09:07:33,954] {taskinstance.py:1042} INFO - 

[2021-02-18 09:07:33,956] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-18 09:07:33,958] {taskinstance.py:1044} INFO - 

[2021-02-18 09:07:33,994] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-02-
--- other logs ---

In the wasb_task_handler.py, the remote log is tried to be read as string. But the log is too long so python read it as bytes which will be showed started with " b' " on UI.

**How to reproduce it**:
1.Set your log to the remote log store to Azure blob storage
2.Trigger the example dags
3.Check the log of example dags job on Web UI

**Anything else we need to know**:
I am trying to fix airflow/providers/microsoft/azure/log/wasb_task_handler.py by decode the remote string.

**Comment by flolas** [comment]
We are facing same issue... after upgrading airflow 2.0.0 to 2.0.1 and providers 1.0.0 to 1.0.1.

**Comment by ldacey** [comment]
Ah, good there is any issue already. Yep, my airflow logs are displayed as a single line which makes them unreadable on the webserver. If I download the log from the UI, or if I open the log directly in the blob container then the formatting is fine.

`b"[2021-02-21 16:16:03,590]`

**Comment by ephraimbuddy** [comment]
Closed via https://github.com/apache/airflow/pull/14313

**Comment by ldacey** [comment]
Nice, thanks. For future reference with changes that happen in provider packages, would I wait for pypi to have this change reflected here? https://pypi.org/project/apache-airflow-providers-microsoft-azure/

**Comment by ephraimbuddy** [comment]
Yes. You'll have to wait for new provider release
