### ISSUE TITLE
Airflow Login Failed After Creating User

### ISSUE THREAD

**Issue by stbones** [apache/airflow#14322]
**Apache Airflow version**:
1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
No Kubernetes 
**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
Linux 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I have created an admin user using below command for first time, and it was successfully created as I have received a message saying - Admin user test_admin created. I can also see a record in ab_user table (postgreSQL). However, when I try to log in with the credential (I ensured I did not type wrong credential) on Airflow WebUI, I get ERROR Invalid Login.

**What you expected to happen**:
I should be able to log in with the credential I have created. 

I am not sure, what went wrong. And, this my first time setting up authentication. 
I have set rbac = true in airflow.cfg file.

**How to reproduce it**:

**Anything else we need to know**:
I have recently changed the backend db to PostgreSQL. 
I have followed below steps

Updated airflow.cfg file with 
```
[webserver]
authenticate = True
auth_backend = airflow.contrib.auth.backends.password_auth
```

Activate virtual env.
`source airflow_env/bin/activate`

Set Airflow Home
`export AIRFLOW_HOME=/tools/airflow_lib`

Install postgreSQL
`sudo apt-get install postgresql postgresql-contrib`

Create user and database

` sudo -u postgres psql`
 `CREATE USER **** PASSWORD '****';`
` CREATE DATABASE airflow_db;`
 `GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user;`

Update postgresql.conf with:
`listen_addresses= 'localhost'`

Update/add pg_hba.conf with
Update
`#host all all 127.0.0.1/32 md`
`host all all 0.0.0.0/0 reject`
Add below IP address 
`host airflow_db user ***.***.***.**/32 md5`

Update airflow.cfg file with
`sql_alchemy_conn = postgresql+psycopg2://user-name:password@localhost:5432/db-name`

Restart PostgreSQL database.
`sudo service postgresql restart`

Restart airflow database
`airflow resetdb`

**Comment by VBhojawala** [comment]
In my humble opinion 

airflow resetdb : removes all entries (Records) from  database.

airflow init : initalize the database. 
https://airflow.apache.org/docs/apache-airflow/1.10.8/howto/initialize-database.html

After initializing database you can create new user using 

"airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname foo --lastname bar"

**Comment by stbones** [comment]
@VBhojawala  Thank you it worked out.. 

I noticed another issue, password does not take few special characters like $, &, etc. Example I had password TestAirflow123&, I could not log in with it, but when I change it to TestAirflow123, it worked out. Are there any special rules for setting up password?

**Comment by potiuk** [comment]
You need to quote parameters in bash when you have special characters. In Bash/Zsh when you put & without quote it is "go to background" indicator. This is probably the problem you had.

I am closing the issue for now unless there are other findings.

**Comment by alonrolnik** [comment]
> @VBhojawala Thank you it worked out..
> 
> I noticed another issue, password does not take few special characters like $, &, etc. Example I had password TestAirflow123&, I could not log in with it, but when I change it to TestAirflow123, it worked out. Are there any special rules for setting up password?

This `$` save our prod deployment now :)

**Comment by kashiftriffort** [comment]
> In my humble opinion
> 
> airflow resetdb : removes all entries (Records) from database.
> 
> airflow init : initalize the database. https://airflow.apache.org/docs/apache-airflow/1.10.8/howto/initialize-database.html
> 
> After initializing database you can create new user using
> 
> "airflow users create --role Admin --username admin --password admin --email [admin@example.com](mailto:admin@example.com) --firstname foo --lastname bar"

This works great
