### ISSUE TITLE
Task Instances stuck in "scheduled" state

### ISSUE THREAD

**Issue by ajbosco** [apache/airflow#14326]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.17.12

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Several Task Instances get `scheduled` but never move to `queued` or `running`. They then become orphan tasks.

**What you expected to happen**:
Tasks to get scheduled and run :) 

**How to reproduce it**:

**Anything else we need to know**:
I believe the issue is caused by this [limit](https://github.com/apache/airflow/blob/2.0.1/airflow/jobs/scheduler_job.py#L923). If we have more Task Instances than Pool Slots Free then some Task Instances may never show up in this query.

**Comment by ajbosco** [comment]
@kaxil - This is the issue we discussed on Slack.

**Comment by ajbosco** [comment]
Actually, I think the issue is right here. If you have 100 slots in a pool and 1 task running with 99 queued, this will return that there are no tasks to run.

https://github.com/apache/airflow/blob/2.0.1/airflow/jobs/scheduler_job.py#L904

**Comment by ajbosco** [comment]
Update: I think the issue is that we have tasks that are more than 63 characters. The annotation for task_id then gets truncated. This causes these tasks to never leave the `self.running` list in the Executor and once enough build up the Scheduler is blocked even though it is not doing anything.

**Comment by kaxil** [comment]
Thanks for the info @ajbosco -- Are you using KubernetesExecutor? Just want to make sure I get enough details to  reproduce this on my end.

**Comment by ajbosco** [comment]
Yep, we're using the KubernetesExecutor

**Comment by jedcunningham** [comment]
I've been able to replicate and will pick this up.

**Comment by kaxil** [comment]
Thanks @jedcunningham -- assigned to you
