### ISSUE TITLE
init scripts for dockerfile 

### ISSUE THREAD

**Issue by binygreenberg** [apache/airflow#14346]
**Description**

Add ability to process init scripts when starting airflow container (part of entrypoint script)

**Use case / motivation**

Similar to the [mysql entrypoint.sh](https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh#L369) allowing to run any number of init scripts before the scheduler/webserver is started. 
This can be usefull when using or extending the official docker image allowing to COPY scripts that can add connections, variables or any other airflow functionality automatically when starting the container

**Are you willing to submit a PR?**

yes. the PR should be relatively simple. As seen in the mysql example above

**Related Issues**

not the i found

**Comment by potiuk** [comment]
Cool! I assigned you to that :)

**Comment by potiuk** [comment]
Just make sure that the init scripts are scanned from `docker-context-files` - this folder is one of the few that are included in the docker context. We have the rule (that makes it really fast) to exclude everythin from docker context and inclulde only some files /directories (see .dockerignore)

**Comment by mik-laj** [comment]
@binygreenberg  Any progress? Users on Slack are looking forward to this change. See: https://apache-airflow.slack.com/archives/CCV3FV9KL/p1620289725321500?thread_ts=1620279612.318500&cid=CCV3FV9KL

**Comment by yiga2** [comment]
@binygreenberg just pinging too on the progress here as you wrote PR should be easy. 
Another use case is being able to set dynamically airflow config env variables like connections, variables or directory locations (e.g `dags`) based on info only available at runtime.
For us, see https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1634045335174500?thread_ts=1632400706.492300&cid=CCQ7EGB1P where we define all these based on the GKE `project_id` in which the container is running. Saves us from maintaining one yaml per project/deployment.
