### ISSUE TITLE
No space left on device for self-hosted runners

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14349]
I think there are some left-overs from previous builds that make self-hosted runners vulnerable to exhausting/disk memory space.

There was a failure in https://github.com/apache/airflow/pull/14347/checks?check_run_id=1947465987 where the errors was "no-space-left on device"   that suggest some left-overs. I believe the only way to fight with those is to make complete cleanup of the self-hosted runners.

The problem with those errors is that you have no control of it as a user, so the only way to provide a good service for the users is a complete cleanup (logs/docker images/sources/ everything) when the job starts. True Clean State (TM). 

Otherwise problems like that might re-occur any time.

**Comment by ashb** [comment]
That link doesn't take me to anything showing out of disk space (anymore?) -- did it get rerun?

I _really_ wish GitHub had a way of linking to logs for previous runs.

**Comment by potiuk** [comment]
Can't find it as well. I think I will close it for now - I have not seen it for a while. Le't see if it reappears.
