### ISSUE TITLE
Not able to access dag ui after json decode error in payload

### ISSUE THREAD

**Issue by aroraprince** [apache/airflow#14355]
**Apache Airflow version**:  2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): Not using

**Environment**:

- **Cloud provider or hardware configuration**:  DigitalOcean
- **OS** (e.g. from /etc/os-release):Ubuntu 20
- **Kernel** (e.g. `uname -a`): Linux airflow 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
I think there was a JSON error in my conf payload.
I have a dag, that triggers another dag in a loop.
While triggering the second dag using TriggerDagRunOperator I send some data in conf param.
There was a code bug and I sent a Decimal() object and the second dag broke with the error shown below in the image, 
TypeError: Object of type Decimal is not JSON serializable.
This is only happening with one of the dags, the others are working fine.

I updated the code now and the error should not persist, still, this is happening when I rerun the dag.
I don't see any errors while running `airflow db init` or `airflow scheduler`.
How can I fix this error and get the UI back working?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4674029/108690686-a4d8b180-7520-11eb-83aa-7ec6d209e00d.png">

**What you expected to happen**:
After the code change, the error should get fixed.

**How to reproduce it**: Send a Decimal Object in conf data while triggering another dag using TriggerDagRunOperator.
The second dag breaks.

**Anything else we need to know**:

**Comment by ernest-kr** [comment]
Can you check the airflow.cfg file ? I assume that is corrupted

**Comment by aroraprince** [comment]
@ernest-kr that should not be the case.
The other dags are working fine.

**Comment by Junnplus** [comment]
Conf parameter should be JSON Serializable. see https://github.com/apache/airflow/issues/13414
