### ISSUE TITLE
Argument order change in airflow.providers.google.cloud.hooks.gcs.GCSHook:download appears to be a mistake.

### ISSUE THREAD

**Issue by wpromatt** [apache/airflow#14363]
### Description
https://github.com/apache/airflow/blob/6019c78cb475800f58714a9dabb747b9415599c8/airflow/providers/google/cloud/hooks/gcs.py#L262-L265

Was this order swap of the `object_name` and `bucket_name` arguments in the `GCSHook.download` a mistake? The `upload` and `delete` methods still use `bucket_name` first and the commit where this change was made `1845cd11b77f302777ab854e84bef9c212c604a0` was supposed to just add strict type checking. The docstring also appears to reference the old order.

**Comment by jhtimmins** [comment]
I suspect this was done on purpose, since the change also made `bucket_name` optional, and `object_name` is still required. But you're right about the doc-block, that should be updated to match the current order.

@mlgruby does this sound correct?

**Comment by mlgruby** [comment]
Yes, the swap was done on purpose as there is no default value for object_name and to make mypy pass this check I have to put the no default argument at first and then the default value arguments ones. 

Agree that the doc block is not updated, My Bad.

**Comment by jhtimmins** [comment]
Thanks for the info @mlgruby! Makes sense.

@wpromatt if you'd like to get a PR with Airflow you can update the doc block, otherwise I'm happy to make the change.
