### ISSUE TITLE
delete_dag in json_client, the end_point is wrong

### ISSUE THREAD

**Issue by huaerheima** [apache/airflow#14373]
**Apache Airflow version**: 1.10.12

the code of the function delete_dag in /airflow/api/client/json_client.py
```python
def delete_dag(self, dag_id):
    endpoint = '/api/experimental/dags/{}/delete_dag'.format(dag_id)
    url = urljoin(self._api_base_url, endpoint)
    data = self._request(url, method='DELETE')
    return data['message']
```
the code of the function delete_dag in /airflow/www/api/experimental/endpoints.py
```python
@csrf.exempt
@api_experimental.route('/dags/<string:dag_id>', methods=['DELETE'])
@requires_authentication
def delete_dag(dag_id):
    """
    Delete all DB records related to the specified Dag.
    """
    try:
        count = delete.delete_dag(dag_id)
    ...
```

I found the endpoint is diffent with the route of delete_dag, this should be a bug

**Comment by jhtimmins** [comment]
Looks like this is a valid error (and still exists on master). @kaxil how far back are we backporting bug fixes like this?

**Comment by kaxil** [comment]
Experimental API is deprecated for 2.0 so unlikely we will fix any non-critical errors for 1.10.x

Btw what's the error ? It looks like it works fine -- https://github.com/apache/airflow/blob/v1-10-stable/tests/www/api/experimental/test_endpoints.py#L152-L170

did you try running it?

**Comment by huaerheima** [comment]
The test works fine because the url_template is same with the route. but the code in json_client.py is wrong.
https://github.com/apache/airflow/blob/v1-10-stable/airflow/api/client/json_client.py#L62 @kaxil

**Comment by kaxil** [comment]
aah right yes, would you like to create a PR against v1-10-stable? We can include it in 1.10.15 but bear in mind that experimental API is deprecated in 2.0.0+

**Comment by vs4vijay** [comment]
If you guys take a look at the documentation, there is no DELETE Dag API mentioned on API Specs. - 
https://airflow.apache.org/docs/apache-airflow/stable/rest-api-ref.html

**Comment by kaxil** [comment]
@vs4vijay Experimental API was not maintained properly -- so docs lack few endpoints: https://github.com/apache/airflow/blob/59c459fa2a6aafc133db4a89980fb3d3d0d25589/airflow/api/client/json_client.py#L59-L63

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/14441

**Comment by vs4vijay** [comment]
@kaxil thanks for quick reply, is there any Stable API to delete a DAG? Because of this DELETE functionality, we're using Experimental APIs.

**Comment by kaxil** [comment]
You should just need to delete the DAG file -- currently we don't have an endpoint that removes the dag entry from all the DB tables -- can you create a separate Github issue for it if it does not already exist
