### ISSUE TITLE
Add link to not deprecated modules docs

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#14394]
There are a lot of documentation that is the first link when you google something that actually doesn't contain anything because of the update of the paths. 

For instance, if you google `trigger dagrun operator` the first link is https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/dagrun_operator/index.html
Which has the following content:
![Captura de pantalla 2021-02-23 a las 16 25 38](https://user-images.githubusercontent.com/11339132/108865688-c5257080-75f3-11eb-9676-323efbe29f42.png)

The ideal situation would be that the google search brings you to the correct link, but otherwise, it would be nice to have at least a link to the new module in the same page

**Comment by jhtimmins** [comment]
This is a good idea and can be assigned to me
