### ISSUE TITLE
STORE_DAG_CODE not displaying correct code for zipped dag files

### ISSUE THREAD

**Issue by prithvisathiya** [apache/airflow#14412]
**Apache Airflow version**:
1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.19.4

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: production docker image
- **Others**: python3.7

**What happened**:
I recently upgraded from 1.10.9 -> 1.10.14, and enabled both `STORE_SERIALIZED_DAGS` and `STORE_DAG_CODE` to True. Everything seems to work as expected, and the scheduler is able to execute the DAG and the tasks within. However, the "Code View" in the UI displays a very long hex string instead of the actual code. 

```
\x66726f6d206461746574696...
```

I have narrowed it down to be an issue, only when dag file is stored within zip files. For example, `my_dag.py` and `my_other_dag.py` would show in the UI incorrectly in the following case:
```bash
├── my_dag.zip
│   ├── my_dag.py
│   └── utils.py
├── my_other_dag.zip
│   ├── my_other_dag.py
```
but this is fine:
```bash
├── my_dag.py
├── my_other_dag.py
├── utils.py
```

A quick look at the database also reflects the incorrectly parsed DAG code within the `source_code` column of the `public.dag_code` table. But the fact that the scheduler can execute the dag, and that the `data` column of the `public.serialized_dag` table contains the correct code, suggests that this issue is isolated only when storing within the `dag_code` table. 

**What you expected to happen**:
I should expect the actual python code to show in UI
```python
import os
...
```

**How to reproduce it**:
Create 2 similar dags (1 within zip and 1 unzipped) and place into root dags folder. The UI will display the `dag2.py` incorrectly, but work fine for `dag1.py`
```bash
├── opt/airflow/dags
│   ├── dag1.py
│   ├── dag2.zip
│   │   └── dag2.py
```

**Comment by ashb** [comment]
Could you please test this on Airflow 2.0 and let us know if the problem persists there?

**Comment by kaxil** [comment]
Any luck with testing @prithvisathiya with Airflow >= 2?

**Comment by prithvisathiya** [comment]
hey, sorry for late reply. Recent changes have made de-prioritize this issue for the last couple months. If I remember correctly, it was affecting Airflow >= 2 as well, but I will double check and update here shortly

**Comment by kaxil** [comment]
This was fixed by https://github.com/apache/airflow/pull/13984
