### ISSUE TITLE
Airflow improperly shows task status as 'up for retry' for a task that failed on re-run

### ISSUE THREAD

**Issue by kretes** [apache/airflow#1441]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:
- Airflow version: _1.7.0_
- Airflow components: _webserver, mysql, scheduler with celery executor_
- Python Version: _2.7.6_
- Operating System: _Linux Ubuntu 3.19.0-26-generic_
### Description of Issue

Now that you know a little about me, let me tell you about the issue I am having:

What I expect:
If I do a re-run and it fails - The task should be either re-tried again (resetting retry count) and marked accordingly in GUI OR not retried - and marked in GUI as 'failed'
- What happened instead?
  The task in the GUI was presented as 'up_for_retry' however it was not retried, even after retry_delay has passed
### Reproducing the Issue

DAG does not have some strange settings:
          concurrency= 3,
          max_active_runs = 2,
          start_date = datetime(2016,04,03,01),
         default_args={
         'depends_on_past': False,
          'retries': 2,
          'retry_delay': timedelta(minutes=3) }

**Comment by bolkedebruin** [comment]
@kretes Can you create a Jira issue for this and provide a reproducible case with it plus screenshots? Thanks

**Comment by kretes** [comment]
migrated to https://issues.apache.org/jira/browse/AIRFLOW-138
