### ISSUE TITLE
Airflow does not respect 'max_active_runs' when task from multiple dag runs cleared

### ISSUE THREAD

**Issue by kretes** [apache/airflow#1442]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:

_Please fill out any appropriate fields:_
- Airflow version: _1.7.0_
- Airflow components: _webserver, mysql, scheduler with celery executor_
- Python Version: _2.7.6_
- Operating System: _Linux Ubuntu 3.19.0-26-generic_
  Scheduler runs with --num-runs and get restarted around every minute or so
### Description of Issue

Now that you know a little about me, let me tell you about the issue I am having:
- What did you expect to happen?
  After running 'airflow clear -t spark_final_observations2csv -s 2016-04-07T01:00:00 -e 2016-04-11T01:00:00 MODELLING_V6' I expected that this task gets executed in all dag-runs in specified by given time-range - respecting 'max_active_runs'
  Dag configuration:
  concurrency= 3,
  max_active_runs = 2,
- What happened instead?
  Airflow at first started executing 3 of those tasks, which already violates 'max_active_runs', but it looks like 'concurrency' was the applied limit here.
  ![3_running_2_pending](https://cloud.githubusercontent.com/assets/1224887/14855926/46c50622-0c96-11e6-857f-7c5aa506ff34.png)
  ![dag_view5outof2](https://cloud.githubusercontent.com/assets/1224887/14855986/7ab297a6-0c96-11e6-87b1-87ac080a5c1b.png)

After first task was done - airflow scheduled all other tasks, making it 5 running dags at the same time that violates all specified limit.
In the GUI we saw red warning (5/2 Dags running ;-) )
![4outof4](https://cloud.githubusercontent.com/assets/1224887/14856051/cb4fde8a-0c96-11e6-82b4-6bb5f8c18520.png)
### Reproducing the Issue

max_active_runs is respected in a day-to-day basis - when of the tasks was stuck - airflow didn't start more than 2 dags concurrently.

**Comment by bolkedebruin** [comment]
@kretes can you create a Jira issue for this and link it to AIRFLOW-72? Thanks!

**Comment by kretes** [comment]
I've created an issue https://issues.apache.org/jira/browse/AIRFLOW-137  .

BTW - I guess this is not the first project that gets transitioned from github to apache incubator jira - why isn't there some migration tool used for issues?

**Comment by bolkedebruin** [comment]
@kretes the reason is that not everyone has an Apache Jira id or has one that can not be linked, so there is no way to link it to the owner.

Thanks.
