### ISSUE TITLE
Quick Start for Docker - REST API returns Unauthorized

### ISSUE THREAD

**Issue by lnryan** [apache/airflow#14423]
**Apache Airflow version**: 2.0.1

**Environment**:

- **Cloud provider or hardware configuration**: NA
- **OS** (e.g. from /etc/os-release): Mac
- **Kernel** (e.g. `uname -a`): NA
- **Install tools**: docker-compose
- **Others**:

**What happened**:

When following [this Quickstart for Docker](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html), the section under "Sending requests to the web api" do not work. They return Unauthorized. It looks like it's because in the docker config access defaults to `deny_all`.

**What you expected to happen**:

The request in the guide should return a 200 response.
`ENDPOINT_URL="http://localhost:8080/" curl -X GET -u "airflow:airflow"  "${ENDPOINT_URL}/api/v1/pools"  `

**How to reproduce it**:

Walk through the Quick Start for Docker, follow each command. Do not change any of the configuration. Then try the curl example.

```
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.0.1/docker-compose.yaml'
mkdir -p ./dags ./logs ./plugins
echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
docker-compose up airflow-init

docker-compose up
```

in a separate terminal window
```
ENDPOINT_URL="http://localhost:8080/" \
curl -X GET \
 --user "airflow:airflow" \
  "${ENDPOINT_URL}/api/v1/pools"  
```

returns 
```
{
  "detail": null,
  "status": 401,
  "title": "Unauthorized",
  "type": "https://airflow.apache.org/docs/2.0.1/stable-rest-api-ref.html#section/Errors/Unauthenticated"
}

```

Trying the same via the swaqqer endpoint also fails, even when entering the credential into the "Authorize" dialog.

**Anything else we need to know**:

checking the permissions via `./airflow.sh airflow config get-value api auth_backend` returns `airflow.api.auth.backend.deny_all`

Creating a new `airflow.cfg` file and adding the below does not change the configuration upon restart, with either `default` or `basic_auth`

```
[api]
auth_backend = airflow.api.auth.backend.default

```

**Comment by ephraimbuddy** [comment]
You need to manually edit the docker-compose file and set auth_backend to basic_auth before you can be able to use basic auth. This is not an issue, by default requests to the REST API are denied.

`AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth`

Add the above then let me know if it worked for you so we can close it. Cheers

**Comment by mik-laj** [comment]
It seems to me that we should fix docker-compose.yaml so that it does not require manual setting of this envariable variable. This file is intended for the beginner who does not need to know all the configuration options.

However, if we do not want to change it, we should update the guide to describe it.
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/start/docker.html#sending-requests-to-the-rest-api
