### ISSUE TITLE
Unpin moto from <2

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#14434]
We had to pin moto to <2 in https://github.com/apache/airflow/pull/14433 since it was breaking CI.

We should support moto >2 by fixing the failing errors (https://github.com/apache/airflow/pull/14406/checks?check_run_id=1973102416#step:6:3130)

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by danarwix** [comment]
Hey,
tried to reproduce the issue and saw that no tests are failing.

what i did was the following:
1. ran the breeze env
2. ran `pytest tests/providers/amazon/aws/` and saw that the tests are not failing
3. stoped the breeze env
4. changed `moto<2` to `moto` at the `setup.py` at the root folder
5. ran the environment again
6. ran `pytest tests/providers/amazon/aws/` and saw that the tests are not failing

expected result: 
see that some tests are failing 

actual result: 
none of the tests are failing

Can anybody point to which tests are supposed to fail and how to reproduce?

**Comment by kaxil** [comment]
@danarwix 

Run `pip install -U moto` in your breeze env and run tests again

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/15051
