### ISSUE TITLE
Airflow + CockroachDB throws DDL issues.

### ISSUE THREAD

**Issue by HusseinSamao** [apache/airflow#14438]
**Apache Airflow version**:
- apache-airflow==1.10.14
- alembic==1.4.3
- SQLAlchemy==1.3.20
- sqlalchemy-cockroachdb==1.3.2
- SQLAlchemy-JSONField==0.9.0
- SQLAlchemy-Utils==0.36.8

**Environment**:
- Airflow runs on:
      Operating System: Red Hat Enterprise Linux Server 7.9
      Kernel: Linux 3.10.0-1160.11.1.el7.x86_64
- CockroachDB runs on:
      Operating System: Amazon Linux 2
      Kernel: Linux 4.14.214-160.339.amzn2.x86_64
- CRDB version:
    Build Tag:        v21.1.0-alpha.2
    Build Time:       2021/02/01 14:48:09
    Distribution:     CCL
    Platform:         linux amd64 (x86_64-unknown-linux-gnu)
    Go Version:       go1.15.6
    C Compiler:       gcc 6.3.0
    Build Commit ID:  21432ccf9a6e2c7f8da29fbedf5a7e9cc1ded5a7
    Build Type:       release

**What happened**:

Airflow connects to CockroachDB throws DDL issues, it fails to create sequences without showing sequence creation error in the log!

**What you expected to happen**:

Apache Airflow works seamlessly with CockroachDB.

**How to reproduce it**:
 1. Installed CockroachDB v21.1.0 (below link is CRDB installation instructions)
      https://www.cockroachlabs.com/docs/releases/v21.1.0-alpha.1.html
  2. Installed Airflow 1.10.14 (below link is Airflow installation instructions)
      https://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-tools
  3. Changed Airflow config file to point CockroachDB cluster
  4. DDL error message shows up in the log
      psycopg2.errors.FeatureNotSupported: ALTER COLUMN TYPE from int to float is only supported experimentally
      HINT:  See: https://go.crdb.dev/issue-v/49329/v21.1
      you can enable alter column type general support by running `SET enable_experimental_alter_column_type_general = true`
  5. Then, enabled experimental alter toggle as suggested in the above error log
      `SET enable_experimental_alter_column_type_general = true`
  6. Reran Airflow application again, then I got the following error messages:
      [SQL: INSERT INTO ab_role (name) VALUES (%(name)s) RETURNING ab_role.id]
      [parameters: {'name': 'Admin'}]
      (Background on this error at: http://sqlalche.me/e/13/f405)
      [2021-02-03 20:51:41,829] {manager.py:256} ERROR - Add Role: (psycopg2.errors.InvalidForeignKey) missing "id" primary key column

What is happening here is that Airflow failed to create sequences and assign them to the Primary Keys (PK) in multiple tables at the bootstrap time, unfortunately Airflow does not throw errors when it failed to create those sequences. When Airflow tries to insert records in the tables, it expects the sequences to generate values for the PKs. Therefore, we see errors on insertion operation `(psycopg2.errors.InvalidForeignKey) missing "id" primary key column`. Once I manually created sequences and assigned them to PKs, it started working normally.

**Anything else we need to know**:
I wish Airflow out-of-the-box works seamlessly with CockroachDB as it does with Postgres. Manually changes is not an optimal way to cope with Airflow future changes in the schema.

**Comment by xinbinhuang** [comment]
Hi @HusseinSamao, CockroachDB is not currently supported as a backend for Airflow, and [neither is CRDB fully compatible with Postgres](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html#:~:text=CockroachDB%20supports%20the%20PostgreSQL%20wire%20protocol%20and%20the%20majority%20of%20its%20syntax.&text=However%2C%20CockroachDB%20does%20not%20support,implemented%20in%20a%20distributed%20system.). So I am not surprised that it will throw errors. So this is more like a feature request than a bug.

That being said, I am curious to know your use case for using CRDB for Airflow?

**Comment by kaxil** [comment]
I have closed it since we don't officially support CockroachDB -- but feel free to add your use-case and answers to @xinbinhuang 's questionsn

**Comment by ashb** [comment]
And while Cockroach is not officially supported, we will accept PRs to improve support for it.

**Comment by HusseinSamao** [comment]
Hi @xinbinhuang ,
I would like to deploy Airflow to multiple regions backed up with a database that supports that topology. CockroachDB provides capability to deploy my database in multiple regions, all regions serve read and write operations.

**Comment by saolof** [comment]
On cockroachdb as an airflow backend, it may be worth mentioning that CRDB is a lot easier to host and comes with a lot more observability out of the box, which is a valid reason to pick it even at the expense of single-node speed.
