### ISSUE TITLE
GITHUB ISSUES BEYOND THIS POINT NOW CLOSED PLEASE USE APACHE JIRA

### ISSUE THREAD

**Issue by bolkedebruin** [apache/airflow#1445]
Airflow is moving to Apache. Due to this move we are required to have all our issues in Apache's Jira. Therefore, we will stop responding to issues created on github beyond this point.

Please use https://issues.apache.org/jira/browse/AIRFLOW/ for new issues.

We will review the current outstanding issues and either migrate or close them whatever seems appropriate.

Also please bear with us while we get used to the new setup ourselves ;-).

**Comment by r39132** [comment]
👍
