### ISSUE TITLE
Release Kubernetes Providers 1.0.2

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#14463]
A new version of cncf Kubernetes Providers 1.0.2 should be released.

It should contain https://github.com/apache/airflow/pull/14123 that fixes issues with Jinja templating with env_vars. This issue was raised multiple times by our users: https://github.com/apache/airflow/issues/13348, https://github.com/apache/airflow/issues/13522 & https://github.com/apache/airflow/issues/14287

@ashb / @dimberman / @potiuk Can one of you release new version of cncf.kubernetes provider please

_Originally posted by @kaxil in https://github.com/apache/airflow/issues/14287#issuecomment-781675876_

**Comment by ashb** [comment]
On it

**Comment by potiuk** [comment]
Ah. I totally missed it @kaxil! sorry.

**Comment by potiuk** [comment]
BTW  Should not we release the next wave of the providers ? It is about the time we would plan to do it and then we could vote on all of them at once ?

**Comment by potiuk** [comment]
If you run the 'prepare readme' without specifying the providers you should see which of the providers require release @ashb  and gives you a chance to decide which version should each released provider be released at - with the possibility of looking at the commits to make sure.
