### ISSUE TITLE
breeze: build-image output docker build parameters to be used in scripts

### ISSUE THREAD

**Issue by ecerulm** [apache/airflow#14460]
**Description**

I would like to see a `--print-docker-args` option for `breeze build-image`

**Use case / motivation**

`breeze build-image --production-image --additional-extras microsoft.mssql --print-docker-args` should print something like

```--build-arg XXXX=YYYY --build-arg WWW=ZZZZ```

I would like to use that output in a script so that I can use `kaniko-executor` to build the image instead of `docker build` .  

**Are you willing to submit a PR?**

**Related Issues**

**Comment by potiuk** [comment]
It's already implemented. Just use --verbose flag.

**Comment by ecerulm** [comment]
but that actually builds the image, I just want to get the `--build-arg` parameters . I think maybe it's a matter of adding a `--dry-run` parameter then.

**Comment by potiuk** [comment]
Ah ok. Yeah. Dry run sounds good.

Maybe you would like to contribute it :)
