### ISSUE TITLE
DagRun duration not visible in tree view tooltip if not currently running

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#14473]
On airflow 2.0.1

On tree view if dag run is running, duration shows as expected:
![image](https://user-images.githubusercontent.com/15932138/109248646-086e1380-779b-11eb-9d00-8cb785d88299.png)

But if dag run is complete, duration is null:
![image](https://user-images.githubusercontent.com/15932138/109248752-3ce1cf80-779b-11eb-8784-9a4aaed2209b.png)

**Comment by bbovenzi** [comment]
I believe this was fixed by #13537 but was merged after 2.0.1 was released.

**Comment by dstandish** [comment]
@bbovenzi my task took 20 seconds (you can see in the image) 

seems like different issue wdyt?

**Comment by bbovenzi** [comment]
@dstandish you're right. I just replicated it. I've been playing with the tooltip js so let me take a look.

**Comment by dstandish** [comment]
nice! thanks
