### ISSUE TITLE
Add a retry with wait interval for SSH operator

### ISSUE THREAD

**Issue by Gaurang033** [apache/airflow#14489]
**Description**
currently SSH operator fails if authentication fails without retying.  We can add two more parameters as mentioned below which will retry in case of Authentication failure after waiting for configured time. 

- max_retry - maximum time SSH operator should retry in case of exception 
-  wait - how many seconds it should wait before next retry 

**Use case / motivation**
We are using SSH operator heavily in our production jobs, And what I have noticed is sometimes SSH operator fails to authenticate, however open re-running jobs it run successfully. And  this happens ofthen. We have ended up writing our own custom operator for this. However, if we can implement this, this could help others as well. 

Implement the suggested feature for ssh operator. 

**Are you willing to submit a PR?**
I will submit the PR if feature gets approval. 

**Related Issues**
N/A

No

**Comment by mik-laj** [comment]
SGTM. GoogleCompute retry authorizations, so generic 
hook can also do it.

**Comment by Gaurang033** [comment]
@Gaurang033  can you elaborate on the generic hook thing? I was thinking to modify the existing hook and add an option for this.

**Comment by mik-laj** [comment]
We have 2 hooks that allows us to connect to SSH server. Second hook have retry mechanism. See: https://github.com/apache/airflow/blob/3f7ebfdfe2a1fa90b0854028a5db057adacd46c1/airflow/providers/google/cloud/hooks/compute_ssh.py#L251

**Comment by Gaurang033** [comment]
@mik-laj  perfect. we can similar implementation for this as well, then 
https://github.com/apache/airflow/blob/3f7ebfdfe2a1fa90b0854028a5db057adacd46c1/airflow/providers/ssh/hooks/ssh.py

**Comment by nshetty15** [comment]
@eladkal Can I take this up?

**Comment by potiuk** [comment]
assigned it to you @nshetty15

**Comment by eladkal** [comment]
@nshetty15 are you still working on it?

**Comment by nshetty15** [comment]
@eladkal  I had some issues setting up airflow. Its good now. I will submit a PR soon for this one.

**Comment by nshetty15** [comment]
@eladkal  could you please review the change?
