### ISSUE TITLE
webserver redirects to dags page after clearing task or dagrun in tree view

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#14482]
**Apache Airflow version**: 2.0.1

**What happened**:

Redirect to dags page

**What you expected to happen**:

go back to tree view

**How to reproduce it**:

go to tree view and clear failed task

**Anything else we need to know**:

I think it did not always do this, possibly prior to 1.10.14 it would return you to tree view.

If I'm wrong about that I guess this is "feature request"

**Comment by yogyang** [comment]
maybe https://github.com/apache/airflow/discussions/14450 can give you a workaround.
BTW, a possible fix in codes maybe 
add `conf.get('webserver', 'backend_url')` in this line https://github.com/apache/airflow/blob/5bfa0f123b39babe1ef66c139e59e452240a6bd7/airflow/www/views.py#L125

**Comment by bbovenzi** [comment]
@dstandish is this still happening for you? I'm on the latest of `main` and not experiencing this issue.

**Comment by dstandish** [comment]
Same, I think this is fixed
