### ISSUE TITLE
Docker image hide LOAD_EXAMPLES config in helm chart

### ISSUE THREAD

**Issue by xinbinhuang** [apache/airflow#14491]
The env `AIRFLOW__CORE__LOAD_EXAMPLES` is set to `false` directly inside the Docker image. This makes the usage of official Docker image with helm chart a bit confusing because it hides the helm chart parameter `config.core.load_examples` (the mounted `airflow.cfg`). Instead, users need to specify `AIRFLOW__CORE__LOAD_EXAMPLES=True` in the `extraEnv/extraEnvFrom` if they want to load example dags. 

For consistency, I think we should either remove the env config in the Docker file or the helm parameter `config.core.load_examples` and use envFrom to configure it

**Apache Airflow version**: master branch

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Good point.I'd vote for changing it in the helm chart documentation. It makes perfect sense for the prod image to not load examples  by defaul (I hardly imagine anyone wanting example dags in production). But having a way to set it properly described in the charat should be a better solution.

This is an example of config parameter which you want to have set as "true" for basic development install and "false" when you actually use it in production.

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/14646
