### ISSUE TITLE
Self hosted runner build sometimes fail without providing logs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14502]
I have seen a number of cases recently when self-hosted runner build failed/was cancelled without providing any logs. Sometimes it is after 1-2 hours of running. It looks like VM running the builds is stuck and hangs and then gets killed without sending any logs.

An example of that is here: https://github.com/apache/airflow/runs/1990835677?check_suite_focus=true 

I know the job works because it succeeded in one of the previous builds. There are no logs to investigate,

It would be great if we have some way of reaching out to the logs of the machine it is running on. Currently only @ashb  can investigate those problems and it puts enormous responsibility and makes @ashb Single Point of Failure in those cases. They happened 3-4 times for me over last few days so they are frequent.

It would be great if several other people have access to the logs to be able to investigate it, also it would be great to get some links printed in the output of the job where we can get directly to the logs of the machine /run that was executed there.

**Comment by ashb** [comment]
I'll take a look, see if anything shows up on the system logs.

I _think_ I have also seen this on GitHub runners too, so it might not be anything on our side. Might

**Comment by ashb** [comment]
Logs are viewable in CloudWatch for the actions.runner systemd service.

I think there's some way of managing SSH access via a System Manager tool, I'll look at integrating that

**Comment by potiuk** [comment]
Another similar error here: https://github.com/apache/airflow/runs/1990836050?check_suite_focus=true

**Comment by potiuk** [comment]
I think it would be great to get instructions on how to get to the right log (at minimum). For now I do not even know what to look for in the cloud watch if i want to find a log from this particular runner (probably it is easy but it is a bit 'secret knowledge' now. 

This is very similar situation as `Build Image` job - which was easy to find, but no-one knew how, so the automated links from the build Image and comments in PRs helped a lot with that. Ideally (maybe that will be even easier than documenting) a URL to the right CloudWatch log entry (with filtering for the right machine name etc.) could be passed as an env variable, then we would see it in the output (I dump all the env variables in Build Info) and we could even click-through to get to the cloud watch if you are already logged to the Amazon project of ours. 

I guess the URL could be easily generated.

**Comment by ashb** [comment]
> I guess the URL could be easily generated.

Less easily than we might hope it turns out. The AWS console url is... hideous. It uses a url fragment that is encoded in a really weird format - not using `?key=value%20space` but.... odd. LIke `$` instead of `%`, and `~` as the separator?

**Comment by ashb** [comment]
```ipython
In [25]: fragment
Out[25]: 'logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272021-02-27T09*3a59*3a59.000Z$257Estart$257E$25272021-02-27T09*3a00*3a00.000Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527fields*20*40timestamp*2c*20message*0a*7c*20filter*20*40logStream*20*3d*20*27ip-172-31-16-53*27*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2010000$257EisLiveTail$257Efalse$257EqueryId$257E$2527582c4f04-c056-4614-97cc-16916474edde$257Esource$257E$2528$257E$2527GitHubRunners$2529$2529'

In [26]: re.sub(r'\$([0-9A-F]{2})', lambda x: chr(int(x.group(1), 16)), re.sub(r'\$25([0-9A-F]{2})', lambda x: chr(int(x.group(1), 16)), fragment))
Out[26]: "logsV2:logs-insights?queryDetail=~(end~'2021-02-27T09*3a59*3a59.000Z~start~'2021-02-27T09*3a00*3a00.000Z~timeType~'ABSOLUTE~tz~'Local~editorString~'fields*20*40timestamp*2c*20message*0a*7c*20filter*20*40logStream*20*3d*20*27ip-172-31-16-53*27*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2010000~isLiveTail~false~queryId~'582c4f04-c056-4614-97cc-16916474edde~source~(~'GitHubRunners))"
```

**Comment by ashb** [comment]
Example of failure without logs that didn't run on self-hosted logs https://github.com/apache/airflow/pull/13929/checks?check_run_id=2037296302

Closing as it's not a self-hosted issue.
