### ISSUE TITLE
Sometimes build process (likely on self-hosted runners) exits with 1 when exit code was 0 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14503]
I guess this yet another manifestation of self-hosted runner problem. Sometimes it happens that even if the script exits with '0' exit code, the actual CI job is marked as a failure and has exit code != 0.

Example here: https://github.com/apache/airflow/runs/1990897172?check_suite_focus=true

```
Finished the script ci_run_kubernetes_tests.sh
Elapsed time spent in the script: 635 seconds
Exit code 0

Error: Process completed with exit code 1.
```

**Comment by ashb** [comment]
>   kubernetes_tests/test_kubernetes_pod_operator.py::TestKubernetesPodOperatorSystem::test_full_pod_spec FAILED [ 21%]

THis was a commo garden variety test failure. Nothing to do with self-hosted runners.
