### ISSUE TITLE
Airflow cron expression is not scheduling dag properly

### ISSUE THREAD

**Issue by 7eng** [apache/airflow#1451]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:

*Please fill out any appropriate fields:
- Airflow version: 1.7.0
- Airflow components: webserver, mysql, Using executor SequentialExecutor
- Relevant `airflow.cfg` settings:
- Python Version: Python 2.7.5
- Operating System: Linux version 3.10.0-123.9.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) 
### Description of Issue

I was testing its functionality by setting cron like "2,3,5,8, \* \* \* *". I was expecting particular dag to be scheduled on minute 2,3,5 and 8 of every hour. However in reality the dag for 2nd minute is executed on 3rd, for 3rd on 5th and for 5th on 8th. And it is not executed for 8th at all. I guess it would be executed for 8th on 2nd minute of the next hour.

Looks like some kind of a bug or not handled case for cron expression in airflow.

**Comment by bolkedebruin** [comment]
Please read the docs on this one and use Apache Jira in the future.
