### ISSUE TITLE
Test status of provider RCs released 27.02.2021 (RCs)

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14511]
People who were involved, please tick the boxes when you test the RCs and they work as expected:

* [amazon](https://pypi.org/project/apache-airflow-providers-amazon/1.2.0rc1/)
  * [x] @piffall 
  * [x] @ecerulm 
  * [ ] @AratiNagmal 
  * [ ] @ivica-k 
  * [ ] @JavierLopezT 
* [apache.druid](https://pypi.org/project/apache-airflow-providers-apache-druid/1.1.0rc1/)
  * [x] @xinbinhuang 
* [apache.spark](https://pypi.org/project/apache-airflow-providers-apache-spark/1.0.2rc1/)
  * [x] @Khrol 
* [cncf.kubernetes](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/1.0.2rc1/)
  * [ ] @jpyen 
  * [X] @ashb 
  * [ ] @dimberman 
* [google](https://pypi.org/project/apache-airflow-providers-google/2.1.0rc1/)
  * [ ] @VBhojawala 
  * [x] @xinbinhuang 
  * [ ] @Scuall1992 
  * [ ] @uma66 
  * [ ] @ryanyuan 
  * [ ] @morrme 
  * [x] @SamWheating 
  * [ ] @YingyingPeng22 
  * [ ] @RNHTTR 
  * [ ] @TobKed 
* [jenkins](https://pypi.org/project/apache-airflow-providers-jenkins/1.1.0rc1/)
  * [ ] @lisovskey 
* [microsoft.azure](https://pypi.org/project/apache-airflow-providers-microsoft-azure/1.2.0rc1/) 
   * [ ] @flvndh
   * [ ] @heeroyuy925 
* [mysql](https://pypi.org/project/apache-airflow-providers-mysql/1.0.2rc1/):
   * [x] @ConstantinoSchillebeeckx 
* [qubole](https://pypi.org/project/apache-airflow-providers-qubole/1.0.2rc1/)
   * [x] @xinbinhuang 
* [salesforce](https://pypi.org/project/apache-airflow-providers-salesforce/2.0.0rc1/)
   * [ ] @jyotidhiman0610 
* [slack](https://pypi.org/project/apache-airflow-providers-slack/3.0.0rc1/)
   * [x] @Khrol 
* [tableau](https://pypi.org/project/apache-airflow-providers-tableau/1.0.0rc1/):
   * [x] @jyotidhiman0610 
* [telegram](https://pypi.org/project/apache-airflow-providers-telegram/1.0.2rc1/):
  * [ ] @rootcss 
  * [x] @adilkhash

**Comment by potiuk** [comment]
Related issue #14512 - where you can also test Backport provider RCs.

**Comment by adilkhash** [comment]
how to tick the checkbox? if I click on a checkbox nothing is happening

**Comment by potiuk** [comment]
Ah.. Experiment :). Possibly only committers can click it :). Comment here will be enough :). I clicked it for you.

**Comment by piffall** [comment]
Checked!

**Comment by ecerulm** [comment]
checked

**Comment by ivica-k** [comment]
Hey @potiuk I would gladly do it but I have no idea how. Any hints/guides appreciated.

**Comment by jyotidhiman0610** [comment]
> Hey @potiuk I would gladly do it but I have no idea how. Any hints/guides appreciated.

I will also require some guidance @potiuk

**Comment by Khrol** [comment]
My change was very cosmetic. I'm not sure that we should test something there.

**Comment by Khrol** [comment]
`apache.spark` - tested.
`slack` - the change is too cosmetic to test it somehow. Not even sure how exactly do that.

**Comment by AratiNagmal** [comment]
> > Hey @potiuk I would gladly do it but I have no idea how. Any hints/guides appreciated.
> 
> I will also require some guidance @potiuk

Me too @potiuk .

**Comment by ConstantinoSchillebeeckx** [comment]
> I will also require some guidance @potiuk

ditto

**Comment by potiuk** [comment]
@ConstantinoSchillebeeckx @AratiNagmal  @jyotidhiman0610 @ivica-k -> this should be as easy as installing the new provider release `pip install <provider>==X.Y.Zrc1`  version in an airflow installation of yours and check if the feature/fix implemented by you works. This is pretty safe - you can always go back by installing the previous version of provider you test.

You can see the exact version of the provider to install in the link just above your name in the issue description.

For example [telegram](https://pypi.org/project/apache-airflow-providers-telegram/1.0.2rc1/) leads to 1.0.2rc1 version

I hope that is helpful - if not - happy to provide more guidance.

BTW. Many, many thanks for help there - I am super happy with the response I got to the experiment!

I think this is the easiest way we can get people from the community more involved 🗡️

**Comment by ephraimbuddy** [comment]
@heeroyuy925 Can you test your fix?

**Comment by xinbinhuang** [comment]
@potiuk Is't possible to also get this https://github.com/apache/airflow/pull/14418 in for druid as well?

**Comment by SamWheating** [comment]
I have verified that the changes from https://github.com/apache/airflow/pull/14086 are working as expected.

**Comment by flvndh** [comment]
There is an error in AzureDataFactoryHook (microsoft.azure). The Azure SDK clients for the major part use this constructor signature `[Service]Client(credentials, subscription_id, **kwargs)` but the Data Factory client has `credential` as its first parameter instead. I'll see if I can fix this rapidly.

**Comment by ConstantinoSchillebeeckx** [comment]
@potiuk I can't find the RC for apache-airflow-providers-mysql, can you point me in the right direction please?

**Comment by SamWheating** [comment]
@ConstantinoSchillebeeckx I think that you want to install `apache-airflow-providers-mysql==1.0.2rc1`

https://pypi.org/project/apache-airflow-providers-mysql/#history

**Comment by ConstantinoSchillebeeckx** [comment]
@potiuk checked!

**Comment by potiuk** [comment]
> There is an error in AzureDataFactoryHook (microsoft.azure). I created #14557 to solve it.

Cool. Thanks for looking at it @flvndh -> Since this is a new thing, I am tempted to still release it (as the BugFix: Fix remote log in azure storage blob displays in one line (#14313)) seems to be more important to handle and the hook is new. Let's see if if we have more providers to release and we can relase a new version of it.

WDYT?

**Comment by potiuk** [comment]
> @potiuk I can't find the RC for apache-airflow-providers-mysql, can you point me in the right direction please?

Indeed - it was under the `mysql` link above your name :) - sorry it was not too obvious :). Next time I will rather put the whole link there (if we decide to automate it) :)

**Comment by potiuk** [comment]
Anyone else - if you think you could take a look - I'd love to get some feedback on those :)

**Comment by ivica-k** [comment]
Hey, absolutely but over the weekend if it's not too late. Working full
time plus doing something on the side just eats up all my time.

**Comment by potiuk** [comment]
Perfectly understand (have the same now). And thanks for the willingness @ivica-k !). We are voting and planning to release the providers tomorrow. It is not a blocker if it is not tested (and this is more of an experiment to see whether we could get help from the community). The providers are also good that you can always downgrade easily if you discover a problem so it would be nice to get confifrmation that it works, but it is not a must.

**Comment by xinbinhuang** [comment]
@potiuk can we get #14418 in for druid before the release? It fixes a bug for Druid.

**Comment by potiuk** [comment]
> @potiuk can we get #14418 in for druid before the release? It fixes a bug for Druid.

I believe so. For me - seeing the feedback - this calls for removing the three:  druid, azure, beam from this release and re-releasing it after the fixes are merged.

We already anticipated this - in our process we have foreseen the option of removing some of the providers even when voting is overall +1 (at the discretion of release manager). I think having those three fixes merged, justifies an out-of band release without waiting 3 weeks for the next wave.

**Comment by ryanyuan** [comment]
@potiuk Checked.

**Comment by xinbinhuang** [comment]
Just checked google

**Comment by xinbinhuang** [comment]
#14418 is merged, so I think Druid is good to go now (after including the fix)

**Comment by jyotidhiman0610** [comment]
Verified tableau, @potiuk

**Comment by potiuk** [comment]
Thanks everyone for help ! All but the 4 remaining packages have been released (and I am following up with releasing the remaining 4) It was a valuable learning for us - we are discussing a more "established" process for releasing providers in the future and we will for sure take the learnings from this experiment into account.

**Comment by potiuk** [comment]
Release announcement here: https://lists.apache.org/list.html?dev@airflow.apache.org

**Comment by potiuk** [comment]
@xinbinhuang @flvndh  -> I prepared this one: https://github.com/apache/airflow/pull/14655 to release the 4 providers that were excluded. Once it is merged, I will prepare release candidates and release those 4 providers (+ backports).

**Comment by xinbinhuang** [comment]
@potiuk Got it! Thank you so much! Will test the new RC once it's out.

**Comment by ashb** [comment]
This batch is released now
