### ISSUE TITLE
docker-compose install error

### ISSUE THREAD

**Issue by gitzhuyongfu** [apache/airflow#14520]
use Official documents install airflow 2.0.1 
docker-compose version is 1.28.5
docker-compose file : curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.0.1/docker-compose.yaml'
error:

Status: Downloaded newer image for apache/airflow:2.0.1
Creating airflow_redis_1    ... done
Creating airflow_postgres_1 ... done
Creating airflow_airflow-init_1 ... done
Attaching to airflow_airflow-init_1
airflow-init_1       | BACKEND=postgresql+psycopg2
airflow-init_1       | DB_HOST=postgres
airflow-init_1       | DB_PORT=5432
airflow-init_1       | 
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       | ModuleNotFoundError: No module named 'airflow'
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       | ModuleNotFoundError: No module named 'airflow'
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       | ModuleNotFoundError: No module named 'airflow'
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       | ModuleNotFoundError: No module named 'airflow'
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       | ModuleNotFoundError: No module named 'airflow'
airflow_airflow-init_1 exited with code 1

**Comment by mik-laj** [comment]
What is your operating system?

**Comment by gitzhuyongfu** [comment]
os：CentOS Linux release 7.8.2003 (Core)
docker: 20.10.3
docker-compose: 1.28.5

**Comment by mik-laj** [comment]
Can you show content of .env file and $UID and $GID?  for now this docker compose is not working from root, but today I merged the patch. See. https://github.com/apache/airflow/pull/14226

**Comment by gelinger777** [comment]
@mik-laj  so we should not use root user and root id?  i also used 0,0 ..

**Comment by mik-laj** [comment]
@gelinger777 Yes. You should use a non-root user.  As a temporary workaround, you can also add a directory with user modules to PYTHONPATH.
```yaml
  environment:
    &airflow-common-env
    PYTHONPATH: "/home/airflow/.local/lib/python3.6/site-packages"
```

**Comment by gelinger777** [comment]
Thank you @mik-laj

**Comment by jagusztinl** [comment]
> ```yaml
> PYTHONPATH: "/home/airflow/.local/lib/python3.6/site-packages"
> ```

Please explain in detail how the yaml file should look like please
