### ISSUE TITLE
Task can not exit normally when I use map in billiard

### ISSUE THREAD

**Issue by 2011211242** [apache/airflow#14538]
```
with mp.Pool(processes=mp.cpu_count()) as pool:
      pool.map(process_thread,                                                                                                                                                              
                 ((idx, file_path) for idx, file_path in enumerate(files)))
```

When error occured in my subprocess, sometime task cannot terminnal normally. The task status on the web was running.

CentOS Linux release 8.3.2011
Python 3.6.8
airflow '2.0.1'
billiard 3.6.3.0

**Comment by vikramkoka** [comment]
@2011211242 Can you please elaborate on this? 
An example DAG with the steps to reproduce this would be ideal, so that we can understand and reproduce the problem.
