### ISSUE TITLE
string templated fields are not rendered literally

### ISSUE THREAD

**Issue by YangMuye** [apache/airflow#14543]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**:

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): redhat 7.9
- **Kernel** (e.g. `uname -a`): 3.10.0-1160.11.1.el7.x86_64
- **Install tools**: pip
- **Others**:

**What happened**:

Given the following code

```
SSHOperator(task_id='dummy', command='''\
for i in 1..100
do
echo $i
echo $i $i
echo $i $i $i
done
''')
```

The `command` field is rendered as:

```
'\n\nfor i in 1..100\ndo\necho $i\necho $i $i\necho $i $i $i\ndone\n'
```

**What you expected to happen**:

I expect to see

```
for i in 1..100
do
echo $i
echo $i $i
echo $i $i $i
done
```

**How to reproduce it**:

**Anything else we need to know**:

This is because the following line renders templated fields using the `pformat` function.

https://github.com/apache/airflow/blob/35c9a902929b79cf7cf53ac5b90c3565dddb97dc/airflow/www/views.py#L926-L928

I suggest we should render strings as is.

```diff
            if renderer in renderers:
                html_dict[template_field] = renderers[renderer](content)
            else:
                html_dict[template_field] = Markup("<pre><code>{}</pre></code>").format(
                     pformat(content)
+                   content if isinstance(content, str) else pformat(content)
                )  # noqa
```

**Comment by eladkal** [comment]
@YangMuye can you submit a PR with your suggest fix?

**Comment by jyotidhiman0610** [comment]
Let me know if you are working on this @YangMuye, if not I can take this up.

**Comment by YangMuye** [comment]
@jyotidhiman0610 Sorry, I am not . Pleasworking on ite feel free to take this up.

**Comment by uranusjr** [comment]
#15130 will fix this (by assigning the `bash` renderer to `command`).
