### ISSUE TITLE
Issues with Celery Executor in Airflow

### ISSUE THREAD

**Issue by divyabairavi** [apache/airflow#1455]
Dear Airflow Maintainers,
### The Celery Executor did start successfully,jobs are running successfully but the same is not reflected in the UI recent status section

Before I tell you about my issue, let me describe my Airflow environment:

_Please fill out any appropriate fields:_
- Airflow version: _latest one..not sure about version,used pip to install it_
- Airflow components: _Webserver with MySQL database on aws and CeleryExecutor_
- Relevant `airflow.cfg` settings:Attached the settings used
- Python Version: _Pyhton 2.7_
- Operating System: _CentOS_
- Python packages: _pip 2.7_
### The Celery Executor did start successfully,jobs are running successfully but the same is not reflected in the UI recent status section

Now that you know a little about me, let me tell you about the issue I am having:
- Recent Status to show respective status of the Airflow jobs
- No Status shown in the Recent Status.
- Screen shots of your DAG's graph and tree views, if appropriate:
- Stack trace, if appropriate:
### Reproducing the Issue

Here is how you can reproduce this issue on your machine.
- Example code that reproduces the issue, including a minimally illustrative DAG if necessary:
- Reproduction steps:
1. Attaching airflow.cfg used
2. Installed Celery
3. Installed Flower
   [airflowcfg.txt](https://github.com/airbnb/airflow/files/245854/airflowcfg.txt)

**Comment by bolkedebruin** [comment]
Please use Apache Jira. Thanks!
