### ISSUE TITLE
Externally triggered DAG is marked as 'success'  when 'start_date' is set to timezone.utcnow() and passed in a DAG level params.

### ISSUE THREAD

**Issue by PrarthiJain** [apache/airflow#14584]
Bug-

When 'start_date': timezone.utcnow() is passed in default_args dictionary, the DAG is not being executed since “The execution_date>=start_date from DAG default_args,” but when the corresponding start date is passed at task level(DAG level parameters), the airflow UI reports it as ’success’ when externally triggered. (Screenshot attached.)

 

Expected-

Manual triggering should not be executed and should behave the same as passed in default_args

 

<details><summary>DAG example code- </summary> 

from datetime import timedelta
from airflow import DAG
from airflow.utils import timezone
from datetime import datetime
from airflow.operators.bash_operator import BashOperator
from airflow.utils.dates import days_ago
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}
dag = DAG(
    'DAG-start_date',
    default_args=default_args,
    description='A simple tutorial DAG',
    schedule_interval=timedelta(days=1),
    start_date = timezone.utcnow(),
    tags=['example'],
    is_paused_upon_creation = False
)
t1 = BashOperator(
    task_id='print_date',
    bash_command='date',
    dag=dag,
)
 
t2 = BashOperator(
    task_id='sleep',
    depends_on_past=False,
    bash_command='sleep 5',
    retries=3,
    dag=dag,
)
dag.doc_md = __doc__
 
t1.doc_md = ""
templated_command = """
{% for i in range(5) %}
    echo "{{ ds }}"
    echo "{{ macros.ds_add(ds, 7)}}"
    echo "{{ params.my_param }}"
{% endfor %}
"""
 
t3 = BashOperator(
    task_id='templated',
    depends_on_past=False,
    bash_command=templated_command,
    params={'my_param': 'Parameter I passed in'},
    dag=dag,
)
 
t1 >> [t2, t3]
 
</details>

<details><summary>Log- </summary>

AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T14:55:35.896567+00:00
[2021-03-03 20:25:37,111] {bash.py:135} INFO - Tmp dir root location:
/var/folders/nl/v9xl69s13k57smt_g1l9zrx40000gn/T
[2021-03-03 20:25:37,112] {bash.py:158} INFO - Running command: date
[2021-03-03 20:25:37,117] {bash.py:169} INFO - Output:
[2021-03-03 20:25:37,123] {bash.py:173} INFO - Wed Mar  3 20:25:37 IST 2021
[2021-03-03 20:25:37,123] {bash.py:177} INFO - Command exited with return code 0
[2021-03-03 20:25:37,135] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=tutorial-2, task_id=print_date, execution_date=20210303T145535, start_date=20210303T145537, end_date=20210303T145537
[2021-03-03 20:25:37,147] {taskinstance.py:1220} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-03-03 20:25:37,162] {local_task_job.py:146} INFO - Task exited with return code 0
 </details>
<img width="1763" alt="Screenshot 2021-03-03 at 8 26 37 PM" src="https://user-images.githubusercontent.com/46317159/109838968-aa46a200-7c6c-11eb-8808-ae970eb80723.png">

**Comment by eladkal** [comment]
`start_date` should not be` timezone.utcnow()` As [docs](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date) mention:
We recommend against using dynamic values as start_date, especially datetime.now() as it can be quite confusing
