### ISSUE TITLE
trigger specific task in an existing DAG run

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [apache/airflow#14591]
**Description**

I may be missing it, but I couldn't find a way of triggering an individual task to run within an existing DAG run through the REST API.

This [endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_set_task_instances_state) nearly gets me there, however the only allowed states are either `success` or `fail` - if I could set the state to `clear`.

**Use case / motivation**

For our testing purposes, we'd like to trigger an individual task and confirm that it behaves as expected.

**Are you willing to submit a PR?**

Oh yeah!

**Comment by mik-laj** [comment]
For development, you can consider to use docker-compose and airflow tasks tests command.

**Comment by ConstantinoSchillebeeckx** [comment]
We would be triggering tasks on a deployed QA environment; is it possible to use the Airflow CLI to interact with a remote deployment? I see the [Docs hints at this](https://airflow.apache.org/docs/apache-airflow/stable/usage-cli.html#set-up-connection-to-a-remote-airflow-instance).

**Comment by mik-laj** [comment]
no.  This feature is not working.  you must use kubectl exec to invoke a remote command.

**Comment by vemikhaylov** [comment]
@ConstantinoSchillebeeckx 
Will this solve your problem? https://github.com/apache/airflow/pull/14500 https://github.com/apache/airflow/issues/13225

**Comment by ConstantinoSchillebeeckx** [comment]
@vemikhaylov it sure does solve the problem!

**Comment by ngmiduc** [comment]
@ConstantinoSchillebeeckx , how did you do it in the end?
Did you use: `https://airflow.apache.org/api/v1/dags/{dag_id}/clearTaskInstances` ?

I was also wondering now how to clear a task of a dagRun.
