### ISSUE TITLE
Max Active Run Feature is not Running

### ISSUE THREAD

**Issue by hinduja1234toko** [apache/airflow#14596]
We have made make **max_active_run =3** in our dag and in config file we have made **max_active_run_per_dag=10**
But our code is running only on one run.
Here is the configuration for the dag.
`
default_args = {
    'owner': 'DE',
    #'start_date': datetime(2021, 2, 24, 8, 6, 0),
    #'start_date': datetime.utcnow() + timdelta(seconds=) - timedelta(=),
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=1),
}

dag = DAG(dag_id='Test', default_args=default_args,
          description='',
          schedule_interval='*/1 * * * *',
          catchup=True,
          start_date=datetime(2021, 2, 24, 8, 6, 0),
          max_active_runs=3,
          is_paused_upon_creation=False)`

**Comment by FredericoCoelhoNunes** [comment]
What executor are you using? If you're using SequentialExecutor, I think you won't be able to run more than one DAG at once
