### ISSUE TITLE
DagRun scheduled after end_date

### ISSUE THREAD

**Issue by dud225** [apache/airflow#1459]
Hello
### Environment

_Please fill out any appropriate fields:_
- Airflow version: v1.7.0
- Airflow components: webserver and scheduler with a postgres database and LocalExecutor
- Python Version: 2.7.9
### Description of Issue

When I write a new DAG, it is automatically picked by the scheduler as intended. However the _end_date_ parameter is not accounted when creating a DagRun, so that DagRuns scheduled after _end_date_ are being displayed  in the web interface  and are staying in the running state forever as the scheduler doesn't launch them.

From [my reading of the sources](https://github.com/airbnb/airflow/blob/master/airflow/jobs.py#L451), the _end_date_ paremeter is never used.

Is there any reason for this behaviour ?

Regards
dud

**Comment by bolkedebruin** [comment]
@dud225 Please use Apache Jira for this as requested. In addition the the line just above what you highlighted considers end_date so your analysis does not seem entirely correct.

Closing.
