### ISSUE TITLE
airflow2.0 - Run the task with the specified user will report an error

### ISSUE THREAD

**Issue by zqd759592942** [apache/airflow#14593]
Use the specified user to run the task, and an error will be reported when the scheduler log path('/bigdata/airflow/logs/scheduler/2021-03-01') is not created the next day.

------------------------------------------------log------------------------------------------------
airflow_install_user = airflow
run_as_user = zqd
_get_log_direc = /bigdata/airflow/logs/scheduler/2021-03-01
Traceback (most recent call last):
  File "/bigdata/python38/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/bigdata/python38/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/bigdata/python38/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 53, in __init__
    Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
  File "/bigdata/python38/lib/python3.8/pathlib.py", line 1266, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/bigdata/airflow/logs/scheduler/2021-03-01'
------------------------------------------------log------------------------------------------------

After a while, this directory is created elsewhere, and it can run normally.

**Comment by vikramkoka** [comment]
@zqd759592942 Can you please share more information here so that we can understand the problem? 

Also, here is a section of the Airflow documentation http://airflow.apache.org/docs/apache-airflow/stable/security/workload.html which may be useful in understanding the requirements for the use of the run_as_user configuration parameter.

**Comment by vikramkoka** [comment]
@zqd759592942 Based on the conversation above, there is nothing to indicate this is a bug. Please do reopen or report a new issue if you continue to encounter a problem.
