### ISSUE TITLE
cx_Oracle insert is not performant

### ISSUE THREAD

**Issue by geeknam** [apache/airflow#1463]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:

_Please fill out any appropriate fields:_
- Airflow version: _1.7.0_
- Airflow components: _OracleHook_
- Python Version: _2.7.10/3.4_
- Operating System: _Linux Centos7 / Mac_
### Description of Issue

Now that you know a little about me, let me tell you about the issue I am having:
- What did you expect to happen?
  OracleHook should allow me to insert 1 million rows quickly (2-4min)
- What happened instead?
  It's very slow.
### Reproducing the Issue

Here is how you can reproduce this issue on your machine.
- Example code that reproduces the issue, including a minimally illustrative DAG if necessary:
- Reproduction steps:
1. Pass in 1 million records to OracleHook.insert_rows()

**Comment by geeknam** [comment]
Pull request attached.

**Comment by r39132** [comment]
Hi @geeknam 
Please refer to https://github.com/airbnb/airflow/issues/1445

We are only accepting Jiras now as per our more to Apache, not Github Issues. 

Please close this and create a new one in [Jira](https://issues.apache.org/jira/browse/AIRFLOW) 

Refer to your PR in the new Jira that you create.

Afterwards, you will need to create a few accounts : refer to [Migrating to Apache](https://groups.google.com/forum/#!msg/airbnb_airflow/961jUu-yxR8/5c_WzmgEBAAJ)

Closing this issue now.

**Comment by geeknam** [comment]
@r39132 https://issues.apache.org/jira/browse/AIRFLOW-50
