### ISSUE TITLE
UpdateMask is useless for POST/PATCH if readOnly=true in the openapi specs

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#14635]
**Apache Airflow version**: 2.0.1

**Environment**: Docker on Linux Mint 20.1, image based on apache/airflow:2.0.1-python3.8

**What happened**:
when i made this PATCH request to the API:
```python
>>> import json
>>> import requests
>>> from requests.auth import HTTPBasicAuth
>>> payload = {"dag_id": "example_bash_operator", "is_paused": False}
>>> r = requests.patch("https://localhost:8080/api/v1/dags/example_bash_operator?update_mask=is_paused", auth=HTTPBasicAuth('username', 'password'), data=json.dumps(payload), headers={'Content-Type': 'application/json'})
```
the following error occurred
```
HTTP response body: {
    "detail": "Property is read-only - 'dag_id'",
    "status": 400,
    "title": "Bad Request",
    "type": "https://airflow.apache.org/docs/2.0.1/stable-rest-api-ref.html#section/Errors/BadRequest"
}
```

**What do you think went wrong?**:
The `requestBody` of the `patch` request is defined to use the `DAG` schema:
https://github.com/apache/airflow/blob/33910d6c699b5528db4be40d31199626dafed912/airflow/api_connexion/openapi/v1.yaml#L423-L428
But the `dag_id` property in the `DAG` schema has been defined as `readOnly`: https://github.com/apache/airflow/blob/33910d6c699b5528db4be40d31199626dafed912/airflow/api_connexion/openapi/v1.yaml#L1452-L1455

And according to https://github.com/zalando/connexion/issues/942, we'll get a 400 error

**Anything else we need to know**:

This is not exactly an issue on Airflow's side. Unless someone thinks we should remove `UpdateMask` from the specs.

**Comment by mik-laj** [comment]
From what I can see, you are not correctly defining the update mask. See: 
https://github.com/apache/airflow/blob/779ecc41847c4e476a12fbc1c607c08a00e90205/tests/api_connexion/endpoints/test_dag_endpoint.py#L587-L594

**Comment by zachliu** [comment]
sorry, that's a typo
i followed the example

**Comment by zachliu** [comment]
btw, this would be more of an issue once we start using the generated client
for example, in Python client, this example in the doc won't work:
```python
    dag = DAG(
        dag_id="dag_id_example",
        root_dag_id="root_dag_id_example",
        is_paused=True,
        is_subdag=True,
        fileloc="fileloc_example",
        file_token="file_token_example",
        owners=[
            "owners_example",
        ],
        description="description_example",
        schedule_interval=ScheduleInterval(
            type="CronExpression",
            value="value_example",
        ),
        tags=[
            Tag(
                name="name_example",
            ),
        ],
    )
    update_mask = [
        "is_paused",
    ] 
    api_response = api_instance.patch_dag(dag_id, dag, update_mask=update_mask)
```
we need to do
```python
    dag = DAG(is_paused=True)
    api_response = api_instance.patch_dag(dag_id, dag)
```
which looks funny

**Comment by ephraimbuddy** [comment]
@zachliu, did you try using `update_mask=is_paused` instead of `update_mask=['is_paused']`?

**Comment by vemikhaylov** [comment]
If I understand it correctly, the problem is that specification states passing a DAG object as the body of the PATCH request is allowed. However, there's the `dag_id` field there, which is `readOnly` and when we pass a full `DAG` object to the `PATCH`, it fails with the `400` because of the `dag_id`.

Maybe all the fields except `dag_id` should be moved to the separate entity (e.g. `DAGData` or something), while `DAG` should include it and extend with `dag_id` (using `allOf`). Then the `PATCH` method will use the `DAGData` schema, not the `DAG` one.

**Comment by ephraimbuddy** [comment]
I recall we had some discussions around it during development(@mik-laj ) to still have the update mask for this endpoint even though only the `is_paused` field is the updatable field for DAG. Same thing is also in Variables PATCH. 

One thing we can do is to make the body of the PATCH method for DAG to accept only `is_paused` and also update that of Variables PATCH method to accept only `value`. I do not support removing update_mask.
I will make a PR shortly to correct this
