### ISSUE TITLE
KeyError template_fields does not exists when get_template_context 

### ISSUE THREAD

**Issue by marcosmarxm** [apache/airflow#14660]
The problem occurs when using a PythonOperator with the TaskInstance and attempt to get the context information.
The code to reproduce the error can be run as a pytest. I raised the question because in Airflow 1.* the same code returned values for template_fields and in Airflow 2. * no. Perhaps it is some structural change that I'm not aware of, especially the change in the behavior of the `.get` method of the **Variable** class

```python
import unittest
import pytest

from airflow.models import TaskInstance, Variable
from airflow.version import version

from airflow.operators.python import PythonOperator
from airflow import DAG
from airflow.utils.dates import days_ago

def someFunc(arg, **kwargs):
    print("hello word")

class TestOperator(unittest.TestCase):

    def test_operator(self):

        dag_object = DAG(dag_id='dag_example',
         default_args={'owner': 'airflow'},
         schedule_interval='@daily',
         start_date=days_ago(1))

        test_operator = PythonOperator(
            dag=dag_object,
            task_id='test-task',
            retries=0,
            python_callable=someFunc,
            op_args=[0],
            templates_dict={
                'database': 'some_database',
                'query': 'some_query',
                'output_location': 'output_location'}
        )

        ti = TaskInstance(task=test_operator, execution_date=dag_object.start_date)
        test_operator.execute(ti.get_template_context())
```
This will raise the `KeyError: 'Variable template_fields does not exist'`
Tracing the error:
```
/airflow/operators/python.py
    self.op_kwargs = determine_kwargs(self.python_callable, self.op_args, context)
/airflow/models/baseoperator.py:602: in __setattr__
    self.set_xcomargs_dependencies()
/airflow/models/baseoperator.py:724: in set_xcomargs_dependencies
    apply_set_upstream(arg)
/airflow/models/baseoperator.py:716: in apply_set_upstream
    apply_set_upstream(elem)
/airflow/models/baseoperator.py:716: in apply_set_upstream
    apply_set_upstream(elem)
/airflow/models/baseoperator.py:717: in apply_set_upstream
    elif hasattr(arg, "template_fields"):
/airflow/models/taskinstance.py:1585: in __getattr__
    self.var = Variable.get(item, deserialize_json=True)
```

In Airflow 1.0 the model Variable uses the method `get_variable` to return values.
https://github.com/apache/airflow/blob/e6475938727941f24926c0d85f4d03a2b7064f2a/airflow/models/variable.py#L104-L122

In Airflow 2.0 was changed to `get_variable_from_secrets`. This function only map variables in the `EnvironmentVariablesBackend` and the `MetastoreBackend` context.
https://github.com/apache/airflow/blob/b718495e4caecb753742c3eb22919411a715f24a/airflow/models/variable.py#L113-L137

**Comment by ashb** [comment]
This is def a bug.

It can be worked around by changing the python callable to not take `**kwargs`:

```
def someFunc(arg):
    print("hello word")
```

But this definately is a bug that we'll fix.

**Comment by ashb** [comment]
Oh actually, this may just be a "bug"/change needed in your tests for 2.0:

```
        test_operator.prepare_for_execution().execute(ti.get_template_context())
```

This works.

**Comment by marcosmarxm** [comment]
Thanks @ashb I'm going to say this to the user
