### ISSUE TITLE
Some backport provider packages are broken

### ISSUE THREAD

**Issue by odracci** [apache/airflow#14673]
**Apache Airflow version**:
v1.10.14

**Kubernetes version**:
v1.18.9

**Environment**:
- EKS

**What happened**:

The following wheel packages are broken. All of them contains the source code of all providers:
```
apache-airflow-backport-providers-postgres==2020.10.29
apache-airflow-backport-providers-salesforce==2020.10.29
apache-airflow-backport-providers-jira==2020.10.29
apache-airflow-backport-providers-opsgenie==2020.10.29
```

**What you expected to happen**:

The wheel files contain only the code of one provider

**How to reproduce it**:

- Build a docker image using the following `Dockerfile`
```
FROM apache/airflow:1.10.14-python3.7

RUN pip install apache-airflow-backport-providers-postgres==2020.10.29 \
  apache-airflow-backport-providers-salesforce==2020.10.29 \
  apache-airflow-backport-providers-jira==2020.10.29 \
  apache-airflow-backport-providers-opsgenie==2020.10.29 \
```

- Run the container
- run `ls -lah /home/airflow/.local/lib/python3.7/site-packages/airflow/providers`
The `providers` directory contains all the providers an

**Anything else we need to know**:

Similar to https://github.com/apache/airflow/issues/13926

**Comment by potiuk** [comment]
Indeed. Seems that we have quite a few providers (only .whl packages) broken in similar way. It looks like the ssh one was not the only broken one for the 2020.10.29 release.  

I will double check that and re-release the providers that are still affected/yank the others.

**Comment by potiuk** [comment]
New packages released. All packages with 2020.10.29 should be yanked now (i.e. skipped by pip, only installed if specifically requested by `==2020.10.20`.

**Comment by potiuk** [comment]
Thanks @odracci for the report - I would love if you verify if all works on your side with the latest versions of the pckages.
