### ISSUE TITLE
Test status of provider rc2s released 2021-03-08

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14670]
* https://pypi.org/project/apache-airflow-providers-apache-beam/1.0.1rc2/
  * [x] @xinbinhuang 
* https://pypi.org/project/apache-airflow-providers-apache-druid/1.1.0rc2/
  * [x] @xinbinhuang 
* https://pypi.org/project/apache-airflow-providers-microsoft-azure/1.2.0rc2/
   * [x] @flvndh
   * [ ] @heeroyuy925 
* https://pypi.org/project/apache-airflow-providers-snowflake/1.1.1rc2/
   * [x] @potiuk

**Comment by potiuk** [comment]
Hey @xinbinhuang @flvndh @heeroyuy925  -> kind request if you could test the providers with fixes :).

**Comment by potiuk** [comment]
Please comment here if/when you test it please.

**Comment by xinbinhuang** [comment]
@potiuk LGTM! for both Druid and beam

**Comment by flvndh** [comment]
@potiuk Azure Data Factory tested successfully. I just need to adapt some argument types in method signatures (#14677) but it doesn't hinder usability.

**Comment by potiuk** [comment]
Providers and backport providers have been released.

**Comment by potiuk** [comment]
Thanks @xinbinhuang and @flvndh for help with testing ! Much appreciated!
