### ISSUE TITLE
PostgreSQL connection does not use option target_session_attrs

### ISSUE THREAD

**Issue by bochkarevnv** [apache/airflow#14683]
**Apache Airflow version**: 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): -

**Environment**:

- **Cloud provider or hardware configuration**: Intel i5-8250U 16GB RAM
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **Kernel** (e.g. `uname -a`): Linux 635b29b988b2 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux
- **Install tools**: Run Airflow in Docker containers
- **Others**: I have two Postgresql servers in cluster: master and read-only replica

**What happened**:
I create new connection:
```
Conn Id: two_postgresql
Conn Type:Postgres
Host: replica,master
Schema: test
Login: test
Port: 5432
Extra: {"target_session_attrs": "read-write"}
```

Then go to Ad Hoc Query choose two_postgresql connection and run query: `SHOW transaction_read_only;`
And I see that transaction_read_only is **on**. It means that airflow connect to replica, because target_session_attrs parameter ignored.

**What you expected to happen**:

I expect that transaction_read_only is **off** and airflow connect to master.

**How to reproduce it**:

**Anything else we need to know**:
Parameter target_session_attrs correctly works with psycopg2.
I think this problem caused by this filter of extra parameters: https://github.com/apache/airflow/blob/1.10.14/airflow/hooks/postgres_hook.py#L88

**Comment by mik-laj** [comment]
Are you willing to submit a PR?

**Comment by kaxil** [comment]
The Airflow 1.10.x series will be supported for six months (June 17, 2021) from Airflow 2.0.0 release date (Dec 17, 2020). Specifically, only 'critical fixes' defined as fixes to bugs that takedown Production systems, will be backported to 1.10.x until June 17, 2021.

Let us know if you can reproduce it on Airflow >= 2.0.1

**Comment by mik-laj** [comment]
Done via: https://github.com/apache/airflow/commit/a4dc11fae63d56bc6cbb029525113948862fd45d
