### ISSUE TITLE
Synchronization of DAG files from object storages (GCS/S3) for Helm Chart

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#14728]
Hello, 

A lot of production Apache Airflow environments deployed on a cloud platform - AWS, Google uses object storage for storing DAG files. This is due to the popularity of Cloud Composer or Amazon Managed Workflows for Apache Airflow (MWAA)  services that have adopted this deployment model. For some users, these services didn't their expectations  (e.g. due to a version shift) and are planning to migrate to Helm Chart.

I think we should help with these migrations and prepare a solution that will allow the use of Helm Chart together with object storages. I think adding two examples to the documentation describing how to use a side-car would be enough, but I am open to discussing another idea to support these syncrhonziations.

The current documentation describes only the following [DAG file management methods](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/helm-chart/latest/manage-dags-files.html):

- Bake DAGs in Docker image
- Mounting DAGs using Git-Sync sidecar with Persistence enabled
- Mounting DAGs using Git-Sync sidecar without Persistence
- Mounting DAGs from an externally populated PVC

Best regards.

**Comment by Swalloow** [comment]
if no one assigned, I will try it.
We need a sidecar container image to use for our example. (s3-sync, gcs-sync)
Should images be included in chart/dockerfiles?

**Comment by mik-laj** [comment]
It's a good idea to add them there, but it's not necessary.

**Comment by kaxil** [comment]
I would like to keep this a bit simpler and allow extra sideCar containers and add example of how someone can use GCS or S3 to sync instead of adding all cloud-specific containers here

**Comment by eladkal** [comment]
This will be addressed in [AIP-71 Generalizing DAG Loader and Processor for Ephemeral Storage](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-71+Generalizing+DAG+Loader+and+Processor+for+Ephemeral+Storage)

If someone has comment on this please do it in the AIP page
