### ISSUE TITLE
Task Instances in the "shutdown" state prevent the scheduler from scheduling new tasks

### ISSUE THREAD

**Issue by larsjeh** [apache/airflow#14744]
**Apache Airflow version**: 2.0.1
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
**Environment**:

- **Cloud provider or hardware configuration**: AWS ECS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **Kernel** (e.g. `uname -a`):  Linux 4d41276694bd 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 GNU/Linux
- **Install tools**:
- **Others**: Python 3.7

**What happened**:
This bug is comparable to #13151, but only for the `shutdown` state instead of the `failed` state.

`DAG <dag_name> already has 1 active runs, not queuing any tasks for run 2020-12-17 08:05:00+00:00`

A bit of digging revealed that this DAG had task instances associated with it that are in the shutdown state. As soon as I forced the task instances that are in the shutdown state into the failed state, the tasks would be scheduled.

**What you expected to happen**:
I expected the task instances in the DAG to be scheduled, because the DAG did not actually exceed the number of `max_active_runs`.

**How to reproduce it**:
I think the best approach to reproduce it is as follows:

- Create a DAG and set max_active_runs to 1.
- Ensure the DAG has ran successfully a number of times, such that it has some history associated with it.
- Set one historical task instance to the shutdown state by directly updating it in the DB

**Anything else we need to know**:
A workaround is to set the tasks to failed, which will allow the scheduler to proceed.

**Comment by ashb** [comment]
How long were these tasks in the shutdown state? They should have automatically progressed to failed reasonable quickly.

**Comment by larsjeh** [comment]
Thanks for your response @ashb! For some reason, the tasks remain in the shutdown state and are not failing automatically. 

We have a setup with AWS ECS containers where we redeploy the containers after dependency changes etc. Smaller changes are synced over EFS. 

I have a feeling that the tasks end up in the shutdown state after/during a new deployment. It appears that the worker, that is currently processing a task, is taken down by the orchestrator causing the task to go into the shutdown state. Unfortunately, the tasks are not failed automatically afterward and they remain in the shutdown state. This results in new dagruns that are not scheduled if `max_active_runs=1`.

**Comment by ashb** [comment]
Ah, I wonder if the "correct" fix is then instead to look for zombie task in RUNNING or SHUTDOWN state, where as currently it only looks at them in the RUNNING state

https://github.com/apache/airflow/blob/2a2adb3f94cc165014d746102e12f9620f271391/airflow/utils/dag_processing.py#L1077-L1089

**Comment by jedcunningham** [comment]
@Birne94, if you could grab the state from both the `task_instance` and `job` rows (based on `TI.job_id == job.id`), that would help me determine what went wrong. Also, what version are you on?

**Comment by eladkal** [comment]
This issue is reported against older version of Airflow.
Please check latest Airflow version to verify if the problem still happens
