### ISSUE TITLE
Problem with from SSHExecuteOperator

### ISSUE THREAD

**Issue by chqli** [apache/airflow#1475]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:
- Airflow version: _1.7.0_
- Airflow components: _CeleryExecutor_
- Python Version: _2.7.6_
- Operating System: _Centos_
### Description of Issue

Now that you know a little about me, let me tell you about the issue I am having:
I am not able to see the dag on UI once I add `from airflow.contrib.operators import SSHExecuteOperator
` to my dag file. I get the 

> dag zzz is missing

 when I click on the dag link

Below is the screenshot for the same. 
<img width="1259" alt="sc_201657_211751_241" src="https://cloud.githubusercontent.com/assets/6815499/15093129/767435f2-149b-11e6-8870-aac41517f359.png">

**Comment by bolkedebruin** [comment]
Please use Jira as per request. Thank you!
