### ISSUE TITLE
Fail when running the example_dag

### ISSUE THREAD

**Issue by zippoobbiz** [apache/airflow#14768]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by vikramkoka** [comment]
I am closing this issue, assuming this was created accidentally. If this was deliberate, please open it with more information around which example DAG, what environment, and steps to reproduce.
