### ISSUE TITLE
The scale-in settings are sligthly too aggressive I think 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14782]
Hey @ashb -  following your request of observing the self-hosted behavior.

I believe the current scale-in settings are slightly too aggressive - especially when the traffic is low (weekends).

I pushed a number of builds here (and @turbaszek as well):

https://github.com/apache/airflow/actions/workflows/build-images-workflow-run.yml

And quite a number a lot of them failed without logs indicating the scale-in event happened. some of them with 'git' failed, some of them with explicitly `lost communication`

Some examples here: 

* https://github.com/apache/airflow/actions/runs/651685483
* https://github.com/apache/airflow/actions/runs/651569791
* https://github.com/apache/airflow/actions/runs/651571502
* https://github.com/apache/airflow/actions/runs/651550722
* https://github.com/apache/airflow/actions/runs/651642721
* https://github.com/apache/airflow/actions/runs/651688017

(maybe some of those were cancelled as duplicates - but at most 1 or 2)

At the same time a number of those jobs succeeded, so I think the scale-in events are the ones to blame.

The previous setting was much more stable (but more costly as well) - however I think I will merge the #14531 which should sigificantly decrease the time needed from the runners so hopefully we will be able to tune up the scale-in settings so that they are more stable.

**Comment by ashb** [comment]
Failed without logs isn't scale-in triggered, but the "lost communication" is.

I'll dig in to logs on Monday and see if I can see what went on

**Comment by ashb** [comment]
Just noticed this happening a lot today, and (thanks to the extra logs) I am testing a change to when we mark a node as OkayToTerminate.

**Comment by ashb** [comment]
Let me know if you notice any more instances now.

**Comment by potiuk** [comment]
closing as it's been already updated several times since and is better I belive
