### ISSUE TITLE
UI of the dash board does not change when jobs are executed 

### ISSUE THREAD

**Issue by abhinav59** [apache/airflow#1480]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:

_Please fill out any appropriate fields:_
- Airflow version: 1.7.0
- Airflow components:"webserver and scheduler with a postgres+psycopg2 database and CeleryExecutor"
- Relevant `airflow.cfg` 
  settings:
- Python Version: 2.7.3
- Operating System: Ubuntu 15.10
- Python packages: 
# 
### Description of Issue

Now that you know a little about me, let me tell you about the issue I am having:
- I was running 3 hadoop map reduce job and it would take a significant amount of time which is around 15 min. I was expecting to see the change in status in "**recent status**" column on the dashboard.
- Instead when ever i run a job the "**recent status**" column does not change and remains static". The color changes are there in graph view, tree view, task duration etc. logs are proper but the ui on the dash board does not change

please someone suggest some solution to it !!!!
### Reproducing the Issue

Here is how you can reproduce this issue on your machine.
- Example code that reproduces the issue, including a minimally illustrative DAG if necessary:
- Reproduction steps:
1. 
2. 
3.

**Comment by bolkedebruin** [comment]
Please ask this on the mailinglist dev@airflow.incubator.apache.org. Github issues are closed per notice. Another option is to create a Jira issue if you think you found a bug. Thanks!
