### ISSUE TITLE
Current user permission validation

### ISSUE THREAD

**Issue by ryanahamilton** [apache/airflow#14805]

**Comment by bbovenzi** [comment]
On login the API should return the currently logged in user with its details and permissions.
The user should be stored in the auth context provider.
Then, any component in the app can pre-validate views and actions for a user before sending requests to the API and receiving an unauthorized error.

**Comment by jscheffl** [comment]
I don't see the details of the issue, either it is fixed or should not be disclosed. Anyway, nothing possible to be fixed w/o text. Therefore: Closing.
