### ISSUE TITLE
Incorrect Sentry Option Indicated in Docs

### ISSUE THREAD

**Issue by zschumacher** [apache/airflow#14841]
**Apache Airflow version**:
2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:
N/A

**What happened**:  
The docs here https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/errors.html indicate that `sentry_on=True` is the config, however the correct config option is `sentry_on=true`

**What you expected to happen**:

**How to reproduce it**:

![image](https://user-images.githubusercontent.com/42360273/111386177-3cde3c80-8682-11eb-8418-1f259ced1354.png)

**Comment by mik-laj** [comment]
The configuration option value is case insensitive.
https://github.com/apache/airflow/blob/72ea841b4bb439495b0f58e043774d38f701100e/airflow/sentry.py#L51
https://github.com/apache/airflow/blob/72ea841b4bb439495b0f58e043774d38f701100e/airflow/configuration.py#L406
