### ISSUE TITLE
Add area:providers for general providers to boring-cyborg

### ISSUE THREAD

**Issue by marcosmarxm** [apache/airflow#14879]
**Description**

Add label **area-providers** to general providers.
For example the **provider:Google**
 https://github.com/apache/airflow/blob/16f43605f3370f20611ba9e08b568ff8a7cd433d/.github/boring-cyborg.yml#L21-L25

**Use case / motivation**

Help better issue/pull request monitoring.

**Are you willing to submit a PR?**

Yes

**Related Issues**

**Comment by mik-laj** [comment]
> Are you willing to submit a PR?
> 
> Yes

LGTM. Can you submit a PR?
