### ISSUE TITLE
Airflow Web Server - Performance Issues with Password Based Authentication 

### ISSUE THREAD

**Issue by harshit283** [apache/airflow#14874]
Airflow Setup Used
Airflow Version: 1.10.12
PostgreSQL version: 10

Airflow Configuration:
AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE: 0 
AIRFLOW__WEBSERVER__WORKERS:10
AIRFLOW__CORE__STORE_SERIALIZED_DAGS: True 
AIRFLOW__CORE__STORE_DAG_CODE: True 
AIRFLOW__WEBSERVER__WORKER_CLASS: gevent

Kubernetes version (if you are using kubernetes) (use kubectl version): 1.18.14

Environment:

Cloud provider or hardware configuration: Azure
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:

**What happened:**

So we are doing some performance tests on airflow webserver to benchmark how many requests per second can a single container (kubernetes) of airflow webserver can handle, we are testing the airflow [experimental APIs](https://airflow.apache.org/docs/apache-airflow/stable/rest-api-ref.html#post--api-experimental-dags--DAG_ID--dag_runs). We are able to handle upto 8 RPS and on investigation it appears that the bottleneck is at the authentication layer. We are using the password based authentication where `check_password_hash` [method ](https://github.com/apache/airflow/blob/1.10.12/airflow/contrib/auth/backends/password_auth.py#L84) appears to be extremely slow in execution, due to which the authentication flow is contributing to 80-85% of total time taken for the Airflow API's.
After bypassing this method airflow webserver is easily able to serve 50 RPS

**How to reproduce it:**

Use the above airflow setup to launch web server, scheduler, workers
Create a simple DAG with python operator which prints "hello world"
Trigger the airflow experimental Trigger Dag API with a load testing tool

**What you expected to happen**
- Airflow webserver handling more requests per second

**Anything else we need to know:**
Kubernetes Container Configuration - 4vCPU, 4Gi memory

**Queries**
- Is there any way to fix this issue or if this is expected should we opt for any other authentication protocol?
- Is this issue fixed in later versions of airflow?
- Are other authentication protocols more performant than password_auth?

**Comment by kaxil** [comment]
Hi @harshit283 , the old UI is deprecated and removed in Airflow 2 and we won't be porting any fixing to that UI.

Please consider using RBAC UI (https://airflow.apache.org/blog/airflow-1.10.12/#use-airflow-rbac-ui)

**Comment by harshit283** [comment]
Hi @kaxil We are testing out the **experimental APIs** [[Link](https://airflow.apache.org/docs/apache-airflow/stable/rest-api-ref.html#post--api-experimental-dags--DAG_ID--dag_runs)] in Airflow and not the Admin UI
Does this RBAC settings have any effect on our use case?

**Comment by kaxil** [comment]
@harshit283 The experimental API too has been deprecated from 2.0.0 -- since there were already experimental. They have been replaced by the Stable API: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html
