### ISSUE TITLE
Scheduler doesn't make command generic

### ISSUE THREAD

**Issue by JCoder01** [apache/airflow#14892]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: EKS, On Prem

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Scheduler includes full dag `fileloc` rather than generic `DAGS_FOLDER/path/to/dag.py`

**What you expected to happen**:

`--subdir` in task instance is genericized to allow running tasks on workers where `core.dags_folder` is different than scheduler.

**How to reproduce it**:
Run scheduler with Celery executor and observe log output.

**Anything else we need to know**:

In TaskInstance there is some logic to handle this,
https://github.com/apache/airflow/blob/master/airflow/models/taskinstance.py#L405:411
 
However, it seems in the latest scheduler, it just passes `dag.fileloc` from the metadata db. 
https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L1103

Should the write to the db genericize the command like in TaskInstance?

**Comment by mik-laj** [comment]
Duplicate:  https://github.com/apache/airflow/issues/8061
