### ISSUE TITLE
Unable to provide Kubernetes proxy information in the Kubernetes pod operator.

### ISSUE THREAD

**Issue by doughepi** [apache/airflow#14904]
**Description**

The current `GKEStartPodOperator` and the `KubernetesPodOperator` don't have a way to configure the proxy URL feature provided by the underlying Python Kubernetes client. A useful feature would include a way to pass this value down to the underlying Kubernetes Python client.

**Use case / motivation**

For Kubernetes clusters in GCP that are subject to VPC transitive peering limitations, it's common to place a proxy in a VPC that you can peer to another VPC. This is required because private GKE clusters present their API servers to you in a Google managed, peered project. Because you cannot route spoke-to-spoke in a peered hub-and-spoke architecture, you must peer the spokes together. The problem is, you cannot peer the GKE API VPC with anything other than your cluster VPC because it is managed by Google.

The solution is to set up an intermediate proxy like [described here](https://cloud.google.com/solutions/creating-kubernetes-engine-private-clusters-with-net-proxies). 

With a proxy setup like above, you must provide a proxy URL to your Kubernetes client. In this case, the Python client used in the `GKEStartPodOperator` and the `KubernetesPodOperator`.

There's no way to specify the [Kubernetes python client `proxy` configuration value](https://github.com/kubernetes-client/python/blob/bf63f59e726562295e9c67dc48b9dcf76e7d8aec/kubernetes/client/configuration.py#L156) in the [`GKEStartPodOperator`](https://github.com/apache/airflow/blob/0e8698d3edb3712eba0514a39d1d30fbfeeaec09/airflow/providers/google/cloud/operators/kubernetes_engine.py#L239) or in the `KubernetesPodOperator`.

**Are you willing to submit a PR?**

Yep! Just let me know.

**Related Issues**

Not that I could find.

**Comment by mik-laj** [comment]
> Yep! Just let me know.

LGTTM. I'm happy to help with review.

**Comment by doughepi** [comment]
Sounds good. Starting on this now.

**Comment by doughepi** [comment]
Going back to the drawing board. The single configuration option in the airflow.cfg file wouldn't support having a proxy URL per cluster (if you were deploying to multiple clusters).

**Comment by eladkal** [comment]
@doughepi are you still working on this issue?

**Comment by doughepi** [comment]
Apologies. I am not. It's fair to say that the architecture of our internal resources has changed to avoid this problem altogether.

**Comment by amoghrajesh** [comment]
@eladkal I would volunteer to take this up, seems like an interesting one. Self assigning.

**Comment by amoghrajesh** [comment]
Looks like @doughepi was able to get a workaround working here. I would not be fixing this at the moment. We can reopen if any other users come to ask for it.

cc @eladkal

**Comment by mikouaj** [comment]
Hi, can we please re-open this? There is a Google Cloud customer that leverages `GKEStartPodOperator` in their Cloud Composer to schedule PODs on another GKE cluster. The API server of this GKE cluster is reachable via the public IP address and the internet egress traffic has to go via the http proxy due to their security policies.

**Comment by eladkal** [comment]
> Hi, can we please re-open this? There is a Google Cloud customer that leverages `GKEStartPodOperator` in their Cloud Composer to schedule PODs on another GKE cluster. The API server of this GKE cluster is reachable via the public IP address and the internet egress traffic has to go via the http proxy due to their security policies.

It's very unlikely that someone from the community will take this take. It has been open for 2 years without any traffic/interests while we can reopen it I don't think it serves any value. It seems that most of the value from this feature is for GCP then probably someone from Google needs to take this task.
I am happy to assist with review if someone decides to implement.
