### ISSUE TITLE
HiveHook doesn't scale up to tables with more than 32,767 partitions

### ISSUE THREAD

**Issue by kurtqq** [apache/airflow#14919]
I don't know why previous issue was closed https://github.com/apache/airflow/issues/7963
it wasn't fixed yet:

The Hive metastore API has a rather confusing method signature for listPartitions. The last method parameter specifies the maximum number of partitions to return, and its type is a Java short. So Airflow passes the maximum Java short value (32,767) and notes the limitation in its API docs:
https://github.com/apache/airflow/blob/master/airflow/providers/apache/hive/hooks/hive.py#L628:L630

However, if you pass the magic number -1 as the "limit", then the metastore API will return all partitions:

https://issues.cloudera.org/browse/IMPALA-749

**Comment by jedcunningham** [comment]
@kurtqq, would you be interested in opening a PR for this? If not, would you be willing to test it (assuming you have an easy way to reproduce it)?

**Comment by kurtqq** [comment]
> @kurtqq, would you be interested in opening a PR for this? If not, would you be willing to test it (assuming you have an easy way to reproduce it)?

I no longer work with hive but this limitation should be removed.
In general fixing it shouldn't cause any trouble for anyone because this is just about allowing to pass `-1`. So in the worst case the -1 won't work. I think it's safe to just fix it.

I would have done it myself but can't due to working on some other stuff.

**Comment by eladkal** [comment]
@pingzh maybe you can help with that issue as you are familiar with partitions in hive
