### ISSUE TITLE
Make the xcom sidecar container resource configurable

### ISSUE THREAD

**Issue by kevincong** [apache/airflow#14926]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):1.11

**Environment**:

- **Cloud provider or hardware configuration**: OpenShift 3.11
- **OS** (e.g. from /etc/os-release): RHEL Server
- **Kernel** (e.g. `uname -a`): Linux
- **Install tools**: Airflow
- **Others**:

**What happened**:

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"sales-trend-predict.181186911d0344eda3f3ff7d446f7d62\" is forbidden: [maximum memory usage per Pod is 8Gi, but limit is 9663676416., minimum cpu usage per Container is 400m, but request is 1m., cpu max limit to request ratio per Container is 5, but provided ratio is 1000.000000.]","reason":"Forbidden","details":{"name":"sales-trend-predict.181186911d0344eda3f3ff7d446f7d62","kind":"pods"},"code":403}

**What you expected to happen**:

For some enterprise kubernetes/openshift cluster, the admin will set a cpu/memory limit on container's resource, eg. minimum 400m cpu core, maximum 8Gi memory etc. However, for airflow's auto generated sidecar container for xcom 'airflow-xcom-sidecar' will fail this requirement as the error shown above, since the cpu core request is set to '1m' currently, (https://github.com/apache/airflow/blob/master/airflow/kubernetes/pod_generator.py#L60), as a result, the sidecar container won't be able to start up. Therefore, we need to have the capability to specify the xcom sidecar resource on kubernetesPodOperator as a parameter.

**How to reproduce it**:

This error only exist in certain kubernetes cluster that have a restriction on container's resource. Therefore, the error can be reproduced by manually setting a resource restriction on admin's level (eg. cpu core request 400m minimum, etc.). Then use KubernetesPodOperator with xcom enabled, you will be able to reproduce the error above. 

**Anything else we need to know**:
N/A

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10605
