### ISSUE TITLE
docker airflow-init is stuck

### ISSUE THREAD

**Issue by ogierpaul** [apache/airflow#14938]
**Apache Airflow version**:
apache/airflow:2.0.1-python3.8

**Environment**:

- **Cloud provider or hardware configuration**: Mac Os X 3 Ghz
- **OS** (e.g. from /etc/os-release): Mac Os 10.15.7
- **Kernel** (e.g. `uname -a`): docker
- **Install tools**:
- **Others**:

**What happened**:
download the `docker.yml` file from apache airflow docker:
https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html

run

`docker-compose up airflow-init`

The console gets stuck after this steps:

`
 paulogier@MBP-de-Paul:~/81-GithubPackages/UdacityDendCapstone$ docker-compose up airflow-init
Creating network "udacitydendcapstone_default" with the default driver
Creating udacitydendcapstone_postgres_1 ... done
Creating udacitydendcapstone_redis_1    ... done
Creating udacitydendcapstone_airflow-init_1 ... done
Attaching to udacitydendcapstone_airflow-init_1
airflow-init_1       | BACKEND=postgresql+psycopg2
airflow-init_1       | DB_HOST=postgres
airflow-init_1       | DB_PORT=5432
airflow-init_1       | 
`
Waiting 10 minutes + and I have to kill the process

**What you expected to happen**:

Initialization of the db

**How to reproduce it**:
This is hard to reproduce.
It happens usually after I have run `docker-compose down` and I try to re-build the project.

**Anything else we need to know**:

It can also happen sometime with airflow-webserver

**Comment by marcosmarxm** [comment]
@ogierpaul maybe using this command to create containers could help. 
`docker-compose up -d --force-recreate --remove-orphans`

**Comment by mik-laj** [comment]
Hi. 
We added an improvement to `docker-compose.yaml` that should improve reliability and stability.  Can you check it now?
https://github.com/apache/airflow/pull/16180
Best regards,
Kamil Breguła
