### ISSUE TITLE
[QUARANTINED] tests/cli/commands/test_task_command.py::TestLogsfromTaskRunCommand

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#14937]
TestLogsFromTaskRunCommand increases a lot of memory usage when we run it in parallel tests. This leads to Exit 137 and soe random failures without logs.

For now we put it in quarantine as it is not  crucial. The likely culprit is that tasks that create a new process are started but not completely killed immediately during the tests, thus in high-pressure environment, the tests might increase the pressure on memory and eventually fail on small Public Github Runners.

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment]
closed in favor of https://github.com/apache/airflow/issues/28658
