### ISSUE TITLE
airflow installation issue:

### ISSUE THREAD

**Issue by hussainaphroj** [apache/airflow#1494]
Dear Airflow Maintainers,
### Environment

Before I tell you about my issue, let me describe my Airflow environment:
- Python Version: Python 2.6.6(tried on 2.7)
- Operating System: RedHat 6.5(tried on RedHat 7.5)
- Python packages: 
  argparse==1.2.1
  aws-cfn-bootstrap==1.3
  backports.ssl-match-hostname==3.4.0.2
  boto==2.34.0
  cas==0.15
  chardet==2.0.1
  Cheetah==2.4.1
  cloud-init==0.7.2
  configobj==4.6.0
  ethtool==0.6
  freeipa==2.0.0a0
  iniparse==0.3.1
  iotop==0.3.2
  ipapython==3.0.0
  iwlib==1.0
  kerberos==1.1
  lockfile==0.9.1
  lxml==2.2.3
  M2Crypto==0.20.2
  Markdown==2.0.1
  matplotlib==0.99.1.1
  netaddr==0.7.5
  nose==0.10.4
  numpy==1.4.1
  ordereddict==1.2
  paramiko==1.7.5
  policycoreutils-default-encoding==0.1
  prettytable==0.6.1
  pycparser==2.14
  pycrypto==2.0.1
  pycurl==7.19.0
  Pygments==1.1.1
  pygpgme==0.1
  pyOpenSSL==0.10
  pystache==0.5.4
  python-daemon==1.5.5
  python-dateutil==1.4.1
  python-default-encoding==0.1
  python-dmidecode==3.10.13
  python-ldap==2.3.10
  python-nss==0.16.0
  pytz===2010h
  PyYAML==3.10
  requests==1.1.0
  rhnlib==2.5.22
  rhsm==1.12.5
  setools==1.0
  simplejson==2.0.9
  six==1.9.0
  SSSDConfig==1.12.4
  urlgrabber==3.9.1
  urllib3==1.5
  yum-metadata-parser==1.1.2

I am unable to install airflow using "pip install airflow", getting errors as:
## RHEL 6

 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bI9hiv/pandas/setup.py", line 631, in <module>
        **setuptools_kwargs)
      File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 550, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (numpy 1.4.1 (/usr/lib64/python2.6/site-packages), Requirement.parse('numpy>=1.7.0'))

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bI9hiv/pandas

RHEL 7:

Complete output from command python setup.py egg_info:
    Running from numpy source directory.
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/setup.py:327: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command, proceeding with "
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1640: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1649: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.**doc**)
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1652: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.**doc**)
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1542: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1553: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.**doc**)
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/numpy/distutils/system_info.py:1556: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.**doc**)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);
         ^
    _configtest.o: In function `main':
    /tmp/easy_install-9Yjxgb/numpy-1.11.0/_configtest.c:6: undefined reference to`exp'
    collect2: error: ld returned 1 exit status
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
     int exp (void);

Any help would be appreciated.

Thanks,
Afroz Hussain

**Comment by bolkedebruin** [comment]
Please close this issue and use Jira instead. This is requiered Since our move to Apache. Thanks

**Comment by hussainaphroj** [comment]
Could you please provide me the link for Jira.

I have tried creating an issue in Jira: https://issues.apache.org/jira/browse/INCUBATOR-131.

**Comment by mistercrunch** [comment]
http://lmgtfy.com/?q=jira+airflow
