### ISSUE TITLE
Tooltip does not display on task instance on any state other than not started

### ISSUE THREAD

**Issue by gopalakrishnanu** [apache/airflow#14956]
**Apache Airflow version**: 2.0.0, 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

When hovering over the task instances on the Graph view or the tree view of a DAG, no tool tip is displayed on any task instances that are in not-starterd state. Tooltip are getting displayed on tasks that are on the not-started state.

![2021-03-23 at 9 21 AM](https://user-images.githubusercontent.com/6332524/112161759-700c5880-8bb9-11eb-8326-251f09bd1b27.gif)

**What you expected to happen**:
Tool tip should be displayed on all instance of the tasks irrespective of its state. This used to work on Airflow 1.10.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
What browser are you using, I couldn't reproduce it.

**Comment by gopalakrishnanu** [comment]
I was able to reproduce on Chrome(Version 89.0.4389.90)  and Safari (Version 14.0.3) on MacOS Catalina

**Comment by gopalakrishnanu** [comment]
And this error is generated on the console when hovering over the task instance 
![image](https://user-images.githubusercontent.com/6332524/112519369-4e050880-8d68-11eb-86f8-4e9662204e0a.png)

**Comment by gopalakrishnanu** [comment]
This is happening only when the selected timezone is the 'server' timezone which doen't have the timezone name set. When I select UTC or CST it works fine. I will see if I can get the server time zone config updated 
![image](https://user-images.githubusercontent.com/6332524/112520191-2a8e8d80-8d69-11eb-8d6a-3a69bd1bb331.png)
