### ISSUE TITLE
Support all terminus task states for Docker Swarm Operator

### ISSUE THREAD

**Issue by akki** [apache/airflow#14959]
**Apache Airflow version**: latest

**What happened**:

There are more terminus task states than the ones we currently check in Docker Swarm Operator. This makes the operator run infinitely when the service goes into these states.
 
**What you expected to happen**:

The operator should terminate.

**How to reproduce it**:

Run a Airflow task via the Docker Swarm operator and return failed status code from it.

**Anything else we need to know**:

So as a fix I have added the complete list of tasks from the Docker reference (https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/)
We would like to send this patch back upstream to Apache Airflow.

**Comment by akki** [comment]
Hi @eladkal 

Can you please advise how I can get [the fix for this issue](https://github.com/apache/airflow/pull/14960) merged?

**Comment by eladkal** [comment]
commented on the PR
