### ISSUE TITLE
Create EMR Notebook execution operators

### ISSUE THREAD

**Issue by rliuamzn** [apache/airflow#14962]
**Description**

Similar to [EMR Jobflow operator](https://github.com/apache/airflow/blob/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68/airflow/providers/amazon/aws/operators/emr_create_job_flow.py) and [EMR Jobflow sensor](https://github.com/apache/airflow/blob/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68/airflow/providers/amazon/aws/sensors/emr_job_flow.py), we should add operator and sensor that interact with [EMR Notebook execution](https://docs.amazonaws.cn/en_us/emr/latest/ManagementGuide/emr-managed-notebooks-headless-cli.html) and abstracts all amazon logic from the airflow user.

**Use case / motivation**
This will allow airflow users use operator and sensor built for EMR Notebook execution.

**Are you willing to submit a PR?**
Yes. We already have some [code](https://github.com/aws-samples/emr-studio-samples/blob/main/airflow_dag_for_execution/simple_dag.py#L32-L75) to start with.

**Related Issues**
Not tightly related, but we would like to follow the same standard/pattern with the [feature request for EKS operator](https://github.com/apache/airflow/issues/8544)

**Comment by mik-laj** [comment]
> Yes. We already have some code to start with.

LGTM. Feel free to submit a PR.

**Comment by shubham22** [comment]
FYI @syedahsn is working on this and will submit a PR in the next few days.

**Comment by syedahsn** [comment]
Can this issue be assigned to me? Thanks!

**Comment by Taragolis** [comment]
Better late than never 🥳
