### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by hitmau** [apache/airflow#14980]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by XD-DENG** [comment]
Hi @hitmau , please provide more details in your issue description. By "Login", we do not know what issue you are facing or how the community can help.

**Comment by hitmau** [comment]
Hello,
I'm using centos8.
I start the normal server, the login screen is displayed, when I enter a
username and password and enter this error!

[image: image.png]
*Mauricio Rodrigues.*
*98031.7641*


Em qua., 24 de mar. de 2021 às 10:58, Xiaodong DENG <
***@***.***> escreveu:

**Comment by XD-DENG** [comment]
Hi @hitmau , please update the details in the Issue title and the main issue description. you can find the edit buttons as shown in the screenshot below.
![Login_·_Issue__14980_·_apache_airflow](https://user-images.githubusercontent.com/11539188/112379308-4a31a180-8ce8-11eb-8e73-ca92ed26e736.png)

And the way you attached picture seems not working
