### ISSUE TITLE
`GCSToLocalFilesystemOperator` unnecessarily downloads objects when it checks object size

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#15005]
`GCSToLocalFilesystemOperator` in `airflow/providers/google/cloud/transfers/gcs_to_local.py` checks the file size if `store_to_xcom_key` is `True`.

https://github.com/apache/airflow/blob/b40dffa08547b610162f8cacfa75847f3c4ca364/airflow/providers/google/cloud/transfers/gcs_to_local.py#L137-L142

How it checks size is to download the object as `bytes` then check the size. This unnecessarily downloads the objects. `google.cloud.storage.blob.Blob` itself already has a `size` property ([documentation reference](https://googleapis.dev/python/storage/1.30.0/blobs.html#google.cloud.storage.blob.Blob.size)), and it should be used instead.

In extreme cases, if the object is big size, it adds unnecessary burden on the instance resources.

A new method, `object_size()`, can be added to `GCSHook`, then this can be addressed in `GCSToLocalFilesystemOperator`.

**Comment by XD-DENG** [comment]
CC @potiuk as you were the original author if I'm wrong :)

Please correct me if anything in my analysis above is incorrect, or maybe there was some reasons for what you implemented in this way? 

Cheers!

**Comment by XD-DENG** [comment]
Sorry @potiuk I think I was wrong. You were not the original author of this chunk, and this code has been implemented 4+ years ago.

But it would still be appreciated if you have time to help share your inputs.

**Comment by eladkal** [comment]
> A new method, object_size(), can be added to GCSHook, then this can be addressed in GCSToLocalFilesystemOperator.

We already have that method in the hook:

https://github.com/apache/airflow/blob/1a85ba9e93d44601a322546e31814bd9ef11c125/airflow/providers/google/cloud/hooks/gcs.py#L776-L793
