### ISSUE TITLE
Installed Airflow 2.0.1 and try login with created user credentials getting below error 

### ISSUE THREAD

**Issue by Avinashreddy29** [apache/airflow#15008]
Python version: 3.6.9
Airflow version: 2.0.1
Node: ip-172-31-45-1.ec2.internal
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/views.py", line 483, in index
    filter_dag_ids = current_app.appbuilder.sm.get_accessible_dag_ids(g.user)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/security.py", line 252, in get_accessible_dag_ids
    [permissions.ACTION_CAN_EDIT, permissions.ACTION_CAN_READ], user
  File "/usr/local/lib/python3.6/dist-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/security.py", line 266, in get_accessible_dags
    .subqueryload(Role.permissions)
AttributeError: '_UnboundLoad' object has no attribute 'options'

airflow@ip-172-31-45-1:~/airflow$ airflow users create \
>     --username admin \
>     --firstname Avinash \
>     --lastname Reddy \
>     --role Admin \
>     --email avinash.reddy@XXXX.com
[2021-03-25 14:11:46,518] {manager.py:727} WARNING - No user yet created, use flask fab command to do it.
Password:
Repeat for confirmation:
Admin user admin created

**Comment by vikramkoka** [comment]
@Avinashreddy29 Can you please elaborate with respect to where you are running this and what database? 

Are you able to do the command: 'airflow users list' 

The installation instructions here may be helpful https://airflow.apache.org/docs/apache-airflow/stable/installation.html

**Comment by Avinashreddy29** [comment]
hi ,

followed the same steps provided by apache airflow.

please find the attached screenshot.

after i login to airflow with user credentials getting a shared error .

let me know anything to check .


regards,
avinash

**Comment by mik-laj** [comment]
@Avinashreddy29 Do you use constraints files? http://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files

**Comment by Avinashreddy29** [comment]
Hi kamil ,
No I think while using constraint file I got some error,so I skip that step.


Regards,
Avinash

**Comment by Avinashreddy29** [comment]
Hi Team , 


Please let us know how to proceed with the next steps ..or we need to re-install the apache airflow 2.0 once gain .

We are struck in using the Airflow 2.0 features .

Regards,
Avinash.L

**Comment by potiuk** [comment]
What error did you have when using constraints ? 

You should not skip it basically.

It looks like you might have some dependency problem.. If you have some dependencies that are not compatible, you will have errors but if you will not tell us the details of error you got when installing airflow, we will not be able to help.

**Comment by Avinashreddy29** [comment]
Hi Team , 

Please find the below error message installed Ubuntu 18.04.

airflow@ip-172-31-45-1:~$ AIRFLOW_VERSION=2.0.1
airflow@ip-172-31-45-1:~$ PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
Python 2.7.17
airflow@ip-172-31-45-1:~$ PYTHON_VERSION="$(python3 --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
airflow@ip-172-31-45-1:~$ echo $PYTHON_VERSION
3.6
airflow@ip-172-31-45-1:~$ CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
airflow@ip-172-31-45-1:~$ sudo python3 -m pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
The directory '/home/airflow/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/airflow/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting apache-airflow==2.0.1
  Downloading https://files.pythonhosted.org/packages/4d/be/7228d4505133bdfedaab0afedb272463190c214baea43fc15be5e3accaae/apache_airflow-2.0.1-py3-none-any.whl (4.5MB)
    100% |████████████████████████████████| 4.5MB 215kB/s
Requirement already satisfied: Flask==1.1.2 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 14))
Requirement already satisfied: SQLAlchemy-JSONField==1.0.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 29))
Collecting tabulate==0.8.7 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 455))
  Downloading https://files.pythonhosted.org/packages/c4/f4/770ae9385990f5a19a91431163d262182d3203662ea2b5739d0fcfc080f1/tabulate-0.8.7-py3-none-any.whl
Requirement already satisfied: pandas==1.1.5 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 328))
Requirement already satisfied: attrs==20.3.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 114))
Requirement already satisfied: croniter==0.3.37 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 169))
Requirement already satisfied: argcomplete==1.12.2 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 107))
Requirement already satisfied: cattrs==1.0.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 151))
Collecting alembic==1.5.4 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 39))
  Downloading https://files.pythonhosted.org/packages/1d/c2/cc544acb821740b4f53d262ecc77774b8fabb3993e91a32842c6d5e9faef/alembic-1.5.4-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 6.6MB/s
Requirement already satisfied: psutil==5.8.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 352))
Requirement already satisfied: python3-openid==3.2.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 396))
Collecting python-daemon==2.2.4 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 386))
  Downloading https://files.pythonhosted.org/packages/5a/0c/57f15b1572661877ff1acbe66c2f5be9d999ae5fb128e22933d374f62aa1/python_daemon-2.2.4-py2.py3-none-any.whl
Requirement already satisfied: lockfile==0.12.2 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 292))
Requirement already satisfied: python-nvd3==0.15.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 393))
Requirement already satisfied: connexion==2.7.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 166))
Requirement already satisfied: MarkupSafe==1.1.1 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 22))
Requirement already satisfied: importlib-resources==1.5.0 in /usr/local/lib/python3.6/dist-packages (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 262))
Collecting cryptography==3.4.5 (from -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.6.txt (line 170))
  Downloading https://files.pythonhosted.org/packages/60/6d/b32368327f600a12e59fb51a904fc6200dd7e65e953fd6fc6ae6468e3423/cryptography-3.4.5.tar.gz (546kB)
    100% |████████████████████████████████| 552kB 1.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ryowr9bv/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ryowr9bv/cryptography/

**Comment by Avinashreddy29** [comment]
Hi Team , 

Thanks issue got resolved sudo python3 -m pip install --upgrade pip

**Comment by Avinashreddy29** [comment]
Hi Team , 

Need sample program how to use REST API to check the list of dags using python programmatically .

When i below getting 401 error .

import requests

response = requests.get("http://3.81.45.85:8080//api/v1/dags")
print(response)

**Comment by mik-laj** [comment]
> Thanks issue got resolved sudo python3 -m pip install --upgrade pip

I'm closing this ticket.

For support on using Airflow, I recommend you post on Slack or Github Discussion.
