### ISSUE TITLE
Running upgrade_check command doesn't process DAGs located in zip files

### ISSUE THREAD

**Issue by kosteev** [apache/airflow#15004]
**Description**
"airflow upgrade_check" command should consider that DAGs can be located in zip archives, as well as scheduler does.

**Use case / motivation**
User stores DAGs in zip archive file and willing to upgrade their Airflow instance from 1.10.15 version to 2.0. They want to run "airflow upgrade_check" command and see the correct report in this case.

Right now, for 1.3.0 version of "apache-airflow-upgrade-check" command doesn't fail in this scenario, it just skips all files except python modules.

**Comment by eladkal** [comment]
Closing as there will be no more releases of upgrade check
