### ISSUE TITLE
OdbcHook string values in connect_kwargs dict converts to None

### ISSUE THREAD

**Issue by krnhotwings** [apache/airflow#15016]
**Apache Airflow version**: 2.0.1

**What happened**:

`OdbcHook` returns `None` for non-boolean-like string values in `connect_kwargs` dict arg

**What you expected to happen**:

`connect_kwarg` values should remain as is.

**How to reproduce it**:

```python
>>> from airflow.providers.odbc.hooks.odbc import OdbcHook
>>> OdbcHook('my_conn', connect_kwargs={'CurrentSchema': 'SCHEMA'}).connect_kwargs
{'CurrentSchema': None}
```

**Anything else we need to know**:

The issue lies in: https://github.com/apache/airflow/blob/db9febdb3be97832679d2ced8028fd7f1c21cd4e/airflow/providers/odbc/hooks/odbc.py#L170-L173

There's no `else` block that returns `val`. As it is, any string value will instead return `None`.

Pardon my ignorance on the subject, but this raises a question: Why is `clean_bool` being called in the first place for a user-provided dictionary? I'm not sure how this is necessary because the user can provide a literal boolean value in the dictionary if needed, no? If in the event that a driver needs to take a case-sensitive boolean string for some parameter, then `clean_bool` would make it impossible to provide such a value.

**Comment by Goodkat** [comment]
I can take it, if you don't mind

**Comment by marcosmarxm** [comment]
@krnhotwings this function is useful because the `connect_kwargs` also is able to receive a JSON object and `clean_bool` maps the JSON bool type to Python boolean type. The function will convert `"true"` to `True` and doesn't change other strings.

The `connect_kwargs` you use can be also configured in the UI when adding the ODBC connection.
You can see more here:
https://airflow.apache.org/docs/apache-airflow-providers-odbc/stable/connections/odbc.html

**Comment by krnhotwings** [comment]
@marcosmarxm Sorry, but I'm still not entirely sure why `clean_bool` is necessary. In Python's eyes, JSON objects would just be raw strings that need to be parsed by the `json` lib and converted into a dictionary with Python data types, correct? 

It looks like `clean_bool` is being applied to the merged dicts of `connection_extra_lower` and `_connect_kwargs`. `connection_extra_lower` is just applying `.lower()` to the keys of `connection.extra_dejson`. `extra_dejson` is using Python's `json` lib to parse the `extras` string into a dictionary, which _should_ handle unquoted JSON boolean values, if I'm not mistaken:

https://github.com/apache/airflow/blob/db9febdb3be97832679d2ced8028fd7f1c21cd4e/airflow/models/connection.py#L335

Looking at the documentation you linked, I noticed the quoted JSON boolean values in the very last example code block, but I would think that it should all work correctly with unquoted raw JSON booleans, which should make `clean_bool` unnecessary.

For example, if you created a connection `testconn` in the UI with Extra:
```json
{
  "connect_kwargs": {
    "DummySetting": true
  }
}
```
it should yield:
```python
>>> airflow.providers.odbc.hooks.odbc.OdbcHook('myconn').connect_kwargs
{'DummySetting': True}
```

Am I missing something else?

(Again, pardon any ignorance on my part.)

**Comment by marcosmarxm** [comment]
@krnhotwings you are correct and nice work diving into this. Maybe this is just legacy structure that keep until nowadays.
Just for sanity: do you really add the `connect_kwargs` without double-quotes in the UI and works? OR can you just give a try?

**Comment by krnhotwings** [comment]
@marcosmarxm Yes, I have tested in 2.0.2 and have my extras as follows:

```json
{
  "connect_kwargs": {
    "CurrentSchema": "TEST",
    "Blah": true,
    "Blah2": false
  }
}
```
```python
>>> from airflow.providers.odbc.hooks.odbc import OdbcHook                                         
>>> OdbcHook('myconn').connect_kwargs
{'CurrentSchema': None, 'Blah': True, 'Blah2': False}  
```

(Had to double-check today. It was getting late last night.)

**Comment by Goodkat** [comment]
@marcosmarxm I have removed `clean_bool ` on my local copy and can confirm that it returns the schema_name instead of None now. I used the folowing extras for my test:

`{
  "connect_kwargs": {
    "CurrentSchema": "SCHEMA",
    "Blah": true,
    "Blah2": false
  }
}`

`>>> from airflow.providers.odbc.hooks.odbc import OdbcHook                                         
>>> OdbcHook('myconn').connect_kwargs
{'CurrentSchema': 'SCHEMA', 'Blah': True, 'Blah2': False}`

As the next step, I will make and commit the changes within the PR #15510
