### ISSUE TITLE
enable generate_pod_template in airflow 2.0.1

### ISSUE THREAD

**Issue by hlin14** [apache/airflow#15014]
**Description**

enable generate_pod_template in airflow 2.0.1 in cli

**Use case / motivation**

the pod_template_file is needed in airflow 2.0.1 while using Kubenetes Executor, however the command "generate_pod_template" is only existed in 1.10.14 but not in 2.0.1. It would be helpful if it can also exist in 2.0.1.

**Comment by Dr-Denzy** [comment]
Assign to me @ashb

**Comment by eladkal** [comment]
This command was created just for the [migration guide](https://airflow.apache.org/docs/apache-airflow/2.0.0/upgrading-to-2.html#step-2-upgrade-to-airflow-1-10-14-a-k-a-our-bridge-release) for 1.10 branch:
https://github.com/apache/airflow/pull/10732/files

@jedcunningham do you see value in adding it to Airflow 2 ?

**Comment by jedcunningham** [comment]
Short version: no

Airflow 1 had a bunch of config options that made building one realistic and useful. Airflow 2, however, has always relied on an existing pod_template_file. There really isn't a way to generate one - it'd basically be the already configured pod_template_file. A bit of a chicken/egg problem here.
