### ISSUE TITLE
Don't remove "full tests required" label when PR  is created with it

### ISSUE THREAD

**Issue by ashb** [apache/airflow#15028]
Right now we have some process/part of the CI pipeline that is removing the "full tests required" label from newly created PRs. https://github.com/apache/airflow/pull/15022#event-4510424213

This only applies to committers/PMC who can choose to apply this label to a PR (non committers can't control labels) but in this case we shouldn't remove the label.

**Comment by potiuk** [comment]
It gets removed when the Image is not in "removed" state

The current process is that label is not really supposed to be "manually" set - it is set automatically when we determine that the PR "likely" needs full tests and after it gets approved by a committer. If it gets "deapproved" it looses the label. We might want to change it that once the label is set (whether automated or manual) it can only get removed manually. That might be actually a nice improvement of the current workflow.

**Comment by ashb** [comment]
I've been setting it manually as an optimization (for instance when I know a change will need full tests.) to avoid a second test run. I _thought_ this used to work, but I'm not 100% sure.

In this case it didn't get unapproved, it was just never approved :).

**Comment by potiuk** [comment]
Yeah. to be precise the label is automatically removed now when the PR has no "Approved" status (non-approved also falls in this category :) ). It think @TobKed that would require slight change in the action of yours ?

**Comment by potiuk** [comment]
PR created in @TobKed 's action: https://github.com/TobKed/label-when-approved-action/pull/6

**Comment by eladkal** [comment]
@potiuk this is solved, right?
