### ISSUE TITLE
Probléme d'accés user et pass

### ISSUE THREAD

**Issue by yacine-del** [apache/airflow#15032]
<!--
I need for your help 

sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <PermissionView at 0x7f368c6e6d30> is not bound to a Session; lazy load operation of attribute 'view_menu' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)

Tank you all

**Comment by yacine-del** [comment]
Ci-dessous le message d'ERR

sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <PermissionView at 0x7f368c6e6d30> is not bound to a Session; lazy load operation of attribute 'view_menu' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)

**Comment by mik-laj** [comment]
Sorry, but this project prefers English for communication. Can you create a new ticket written in English?
