### ISSUE TITLE
Remove 'user_id', 'role_id' from User and Role in OpenAPI schema 

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#15059]
Would be good to remove the 'id' of both User and Role schemas from what is dumped in REST API endpoints. ID of User and Role table are sensitive data that would be fine to hide from the endpoints

**Comment by rijusougata13** [comment]
can you help me out from where i can start with? @ephraimbuddy

**Comment by ephraimbuddy** [comment]
Hi @rijusougata13, you can start by setting up the development environment. Here are instructions on how to contribute https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst. 
The codes for the REST API are located at `airflow/api_connexion.`
Let me know if I should assign this to you.

**Comment by amoghrajesh** [comment]
@vikramkoka I would like to work on this issue if it is still open. Can you help in ramping up?

**Comment by ephraimbuddy** [comment]
@amoghrajesh I have assigned you to this ticket. Here's how to get started https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst

**Comment by amoghrajesh** [comment]
@ephraimbuddy I see that this issue has been fixed as a part of https://github.com/apache/airflow/pull/15117. 
Why is this issue open yet and what are the exact expectations of the fix?

**Comment by ephraimbuddy** [comment]
#15117 removed `user_id`, we also need to remove `role_id`

**Comment by aa3pankaj** [comment]
@ephraimbuddy @potiuk If nobody is working on this issue, I can pick it up

**Comment by potiuk** [comment]
I think it's been quite a time so - go ahead (@amoghrajesh can chime-in in case).

**Comment by aa3pankaj** [comment]
@ephraimbuddy 
I verified **"/roles"** and **"/roles/{role_name}"** APIs, both are not exposing role_id, 
could you please share API that is exposing role_id?

**Comment by amoghrajesh** [comment]
@aa3pankaj @potiuk @ephraimbuddy cannot see role_id being exposed on any API. We should close this issue

**Comment by potiuk** [comment]
@ephraimbuddy - are you ok with that assesment ?

**Comment by uranusjr** [comment]
I also mentioned in the original PR that, from what I could tell, the role ID is not exposed anywhere. So I _think_ this indeed can be closed.

**Comment by potiuk** [comment]
closing then. We can re-open if needed.
