### ISSUE TITLE
PostgresHook do not use the specified cursor

### ISSUE THREAD

**Issue by Davide95** [apache/airflow#15108]
**Apache Airflow version**: 2.0.1

**What happened**:

From the docs it is reported that "you can choose cursor as {"cursor": "dictcursor"}." (https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/_api/airflow/providers/postgres/hooks/postgres/index.html).

I was not able to use this feature, it may be a bug.

Exception: `ERROR - tuple indices must be integers or slices, not str`

**What you expected to happen**:

I should be able to use the correct cursor while executing the queries

**How to reproduce it**:

```
hook = PostgresHook(
      postgres_conn_id='conn-id',
      extra=json.dump({'cursor': 'dictcursor'})
)

row = hook.get_first(
        sql="""select * from filestatus """
)

logging.info(row['parquetfile'])
```

**Comment by uranusjr** [comment]
That said, it is definitely a bit confusing the hook just throws away unused arguments like this. Maybe it should throw an error instead?

**Comment by Davide95** [comment]
Hi @uranusjr 
> I believe the documentation is saying you need to set extra on your Connection, not the hook.

Does this mean that if you want to use different cursor types you have to create different connections? Isn't this behavior particularly tricky?

**Comment by uranusjr** [comment]
> Does this mean that if you want to use different cursor types you have to create different connections?

Yes, as the implementation currently stands.

> Isn't this behavior particularly tricky?

It is definitely a bit inconvinient, but why would you need to mix both kinds of cursors in the first place? It’s a nice feature to have, but *particluarly tricky* wouldn’t be my description to the situation.

But nontheless, it would still be a good feature request and contribution if the interface can be designed reasonably.

**Comment by Davide95** [comment]
> Yes, as the implementation currently stands.

Ok, thanks for the clarification

> It is definitely a bit inconvinient, but why would you need to mix both kinds of cursors in the first place? It’s a nice feature to have, but _particluarly tricky_ wouldn’t be my description to the situation.

I'm inheriting a large and old codebase and migrating everything could be an issue. Integrating different DAGs with different settings would be a nice feature to have

**Comment by vikramkoka** [comment]
@uranusjr and @Davide95, Can this issue be closed now?

**Comment by uranusjr** [comment]
I think this depends on whether @Davide95 wants to turn this into a feature request (instead of a bug report) on setting the cursor class (and persuambly other extras) on a per-hook (per-operator?) basis.

**Comment by Davide95** [comment]
I have some issues regarding breeze. I've already posted a message on Slack to get some help
If I will be able to have a working env, it would be great to contribute

**Comment by scouvreur** [comment]
Hey @Davide95 - are you still looking into addressing this issue ? I have a working dev environment with Airflow and Postgres is that's helpful I would be happy to open a pull request

**Comment by Davide95** [comment]
Hi @scouvreur
Nope, I had some issues configuring the dev env in my machine, it seems that there were issues with btrfs:)

**Comment by scouvreur** [comment]
@Davide95 @uranusjr do you think it's worth turning this issue into a feature request ?

**Comment by uranusjr** [comment]
Feel free to raise one yourself if you think it’s useful!

**Comment by anauwal** [comment]
hello, please fix this bug
