### ISSUE TITLE
Airflow web server redirects to a non-existing log folder - v2.1.0.dev0

### ISSUE THREAD

**Issue by mllamazares** [apache/airflow#15103]
**Apache Airflow version**: v2.1.0.dev0

**Environment**:

- **Others**: Docker + docker compose
```
docker pull apache/airflow:master-python3.8
```

**What happened**:

Once the tasks finish successfully, I click on the Logs button in the web server, then I got redirected to this URL:
`http://localhost:8080/task?dag_id=testing&task_id=testing2&execution_date=2021-03-30T22%3A50%3A17.075509%2B00%3A00`

Everything looks fine just for 0.5-ish seconds (the screenshots below were taken by disabling the page refreshing):
![image](https://user-images.githubusercontent.com/5461023/113067907-84ee7a80-91bd-11eb-85ba-cda86eda9125.png)
![image](https://user-images.githubusercontent.com/5461023/113067993-aea7a180-91bd-11eb-9f5f-682d111f9fa8.png)

Then, it instantly gets redirected to the following URL:
`http://localhost:8080/task?dag_id=testing&task_id=testing2&execution_date=2021-03-30+22%3A50%3A17%2B00%3A00#
`

In which I cannot see any info:
![image](https://user-images.githubusercontent.com/5461023/113068254-3d1c2300-91be-11eb-98c8-fa578bfdfbd1.png)
![image](https://user-images.githubusercontent.com/5461023/113068278-4c02d580-91be-11eb-9785-b661d4c36463.png)

The problems lies in the log format specified in the URL:
```
2021-03-30T22%3A50%3A17.075509%2B00%3A00
2021-03-30+22%3A50%3A17%2B00%3A00#
```

This is my python code to run the DAG:
```python
args = {
    'owner': 'airflow',
}

dag = DAG(
    dag_id='testing',
    default_args=args,
    schedule_interval=None,
    start_date=datetime(2019,1,1),
    catchup=False,
    tags=['example'],
)

task = PythonOperator(
    task_id="testing2",
    python_callable=test_python,
    depends_on_past=False,
    op_kwargs={'test': 'hello'},
    dag=dag,
)
```

**Configuration details**

Environment variables from docker-compose.yml file:
```
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Madrid
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Europe/Madrid
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
```

**Comment by grepthat** [comment]
Seeing this as well. Is there a quick fix for this?

**Comment by darkaero-xx** [comment]
I see this behaviour as well, thought it was my configuration :D :D how can I fix it?
