### ISSUE TITLE
apache-airflow-backport-providers-google only installs only `dist-info` without files

### ISSUE THREAD

**Issue by oripwk** [apache/airflow#15115]
Running

```
pip3 install apache-airflow-backport-providers-google
```

Installs only `dist-info` without any Python files. It happens on all machines I'm trying, including my laptop, other laptops, and a docker container.

Please help.

**Comment by uranusjr** [comment]
The package installs files into `airflow/providers/google/`. You can look into the contents of the `RECORD` file in the `.dist-info`, it should list the installed files.
