### ISSUE TITLE
Bump google-api-core package version to make apache-airflow-providers-google compatible with python3.6

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#15129]
**Apache Airflow version**:
1.10.14 and 1.10.15

**Environment**
Official Docker image python 3.6

**What happened**:

The backport package `apache-airflow-backport-providers-google` has a dependency on `google-api-core`:

* [apache-airflow-backport-providers-google](https://github.com/apache/airflow/blob/a7a558eade11ff43a7b96544dcfb84be2441fdc0/setup.py#L285) — `>=1.25.1,<2.0.0`
* [airflow 1.10.14 constraints for python 3.6](https://raw.githubusercontent.com/apache/airflow/constraints-1.10.14/constraints-3.6.txt) — `google-api-core==1.23.0`

Those two do not overlap in any version. Setting  `google-api-core==1.26.3` will make it solve the dependencies again

**What you expected to happen**:

Should be posible to install airflow with the current constraints.
```
pip install apache-airflow-backport-providers-google -c https://raw.githubusercontent.com/apache/airflow/constraints-1.10.14/constraints-3.6.txt 
```

**Comment by dinigo** [comment]
I haven't found where the constraint files are created, because they seem to be dynamically created. Where can I find it?

**Comment by dinigo** [comment]
Same issue with `snowflake-connector-python==2.3.6` in the constraints but `snowflake-connector-python>=2.4.1` in the `apache-airflow-backport-providers-snowflake` package. If the providers are going to be decoupled, then each one should have it's own constraints, so it's easier to keep them up to date

**Comment by uranusjr** [comment]
The constraint files are automatically generated from CI, and you shouldn’t be modifying them directly.

I believe the way to do it is to change the minimal version in `setup.py`; CI will pick them up automatically and update the constraints files accordingly.

**Comment by dinigo** [comment]
I've placed a link to the `setup.py` with a range of versions, and then the constrain generated lays outside of this range. I thought they where generated from the `setup.py` until I saw this:

* [setup.py](https://github.com/apache/airflow/blob/a7a558eade11ff43a7b96544dcfb84be2441fdc0/setup.py#L285) — `>=1.25.1,<2.0.0`
* [airflow 1.10.14 constraints for python 3.6](https://raw.githubusercontent.com/apache/airflow/constraints-1.10.14/constraints-3.6.txt) — `==1.23.0`

**Comment by RosterIn** [comment]
The `>=1.25.1,<2.0.0` is in master branch not in 1.10 branch.
I would imagine that the constrains for 1.10.14 are not created from master but i might be wrong here.

**Comment by ashb** [comment]
> The `>=1.25.1,<2.0.0` is in master branch not in 1.10 branch.
> I would imagine that the constrains for 1.10.14 are not created from master but i might be wrong here.

You are correct.

**Comment by dinigo** [comment]
> The >=1.25.1,<2.0.0 is in master branch not in 1.10 branch.

You are right, in the 1.10.14 branch is [not in the setup.py](https://github.com/apache/airflow/blob/1.10.14/setup.py#L267). How do we get to this version? I think I'm missing something.

I see a couple of reasons to close this issue:

1. Backport providers [not maintained anymore](https://github.com/apache/airflow/blame/master/dev/README.md#L104), 
  > _Note that Backport Providers for Airflow 1.10.* series are not released any more. The last release
of Backport Providers was done  on March 17, 2021._
2. Python [3.6 about to die](https://endoflife.date/python) — only 8 months left

According to the /dev/README each package has its dependencies. But in the master they seem to be managed from the `setup.py`. I see how different providers (overall transfer operators) might over time use incompatible versions if they where completely decoupled.

(I hope Google updates their Composer image to python3.6 soon)

**Comment by potiuk** [comment]
@dinigo. Everything is as expected.

Constraints are frozen at the time of  creating the `apache-airflow` package. And they are there to be able to install the given version of `apache-airflow` in a consistent way. No more, no less. They have nothing to do with the version of provider that you can install afterwards. Constraints finish their role when you have apache-airflow installed, and then you should manage your additional packages (including backport providers) on your own.

There is (and cannot be) absolutely no relation of the constraints with version 1.10.14 to the providers (which are released on a completely dfferent schedule).

You should not use constraints to install providers, this is neither endorsed not supported. You should install providers (or backport providers) separately

**Comment by dinigo** [comment]
@potiuk much clearer. Thanks
