### ISSUE TITLE
Add documentation on how to easily add new python packages to the docker-compose development setup

### ISSUE THREAD

**Issue by CharlesWinter** [apache/airflow#15139]
**Description**

It is currently not clear how one should use 3rd party python packages when running apache airflow locally using docker-compose as shown here. https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html

Clearly a volume mount of some description would help, but it is not clear where to mount the volume to. 

Notice that the 3rd party attempt at this here _does_ specify, and allows one to mount a requirements.txt file which is respected by the entrypoints script.

https://github.com/puckel/docker-airflow#install-custom-python-package

**Use case / motivation**

Provide clarity to users who are using docker-compose for a local instance of airflow using docker. 

**Are you willing to submit a PR?**

Absolutely! However I can't solve this issue myself so I'm not sure I would be of much use. 

**Related Issues**

None that I can see.

**Comment by potiuk** [comment]
You need to create your own image. Extending/customizing image, including adding your own python packages are described in http://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html . Soon (as of 2.0.2 the documention will be updated to put all docker stuff together )
