### ISSUE TITLE
curl REST authentication fails if variable value hidden from the UI

### ISSUE THREAD

**Issue by saveriogzz** [apache/airflow#15136]
**Apache Airflow version**: 2.0.1 - release:2.0.1+beb8af5ac6c438c29e2c186145115fb1334a3735

**Environment**:

- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS

**What happened**:
After I have hidden some sensitive variable values from the UI by writing 'secret' into their names, the task supposed to run using this variable value fails for an authentication issue.  
The task is a **BashOperator** with which I am doing **curl PUT** requests.

More in details, the bash operator is the following:

```python
put_task = BashOperator(
    task_id='put_task',
    bash_command=rest_operations.templated_put,
    env={
        'basepath': basepath,
        'filename': filename,
        'checksum': "{{ ti.xcom_pull(task_ids='create_metadata', key='checksum') }}",
        'user': user,
        'password': Variable.get(f"{user}_apikey_secret")
        }
)
```
where the templated bash command is:
```bash
curl --header "Content-Type: application/json" --request PUT --data-binary @$basepath/$filename https://cloudnet.fmi.fi/upload/data/$checksum --user $user:$password
```
and the variable is correctly rendered as secret:
```json
{
    "basepath": "/path/to/my/binary/data",
    "checksum": "mychecksum",
    "filename": "myfile",
    "password": "********",
    "user": "myUser"
}
```

I get this *Authorization required* message.
```
[2021-04-01 08:51:17,677] {bash.py:158} INFO - Running command: curl --header "Content-Type: application/json"         --request PUT         --data-binary @$basepath/$filename         https://cloudnet.fmi.fi/upload/data/$checksum         --user $user:$password
[2021-04-01 08:51:17,849] {bash.py:169} INFO - Output:
[2021-04-01 08:51:18,069] {bash.py:173} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-04-01 08:51:18,072] {bash.py:173} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-04-01 08:51:18,190] {bash.py:173} INFO - 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 1367k  100    22    0     0    154      0 --:--:-- --:--:-- --:--:--   154
[2021-04-01 08:51:18,196] {bash.py:173} INFO - Authorization required
```

However, If I remove 'secret' from the variable name, then its value is shown in clear, but everything works as expected.

**What you expected to happen**: I would expect the bash command to be working also with the hidden variable value.

**Comment by wolfier** [comment]
Based on #8421, the render template view is not be capable of hiding sensitive information. 

Quoting @kaxil,

> Yes the Rendered UI Field currently exposes everything. We should have a way of hiding this.

I was unable to replicate what you had by following your instructions. The hidden sensitive value when the name of the Variable contains special keywords still renders as its original value.

I think you may have saved the Airflow Variable while the value was shown as the replaced value in the Airflow Variables view thereby saving the the actual value as "********". That was the only way I am able to replicate what you had.

1. Create Airflow Variable in UI, my_value_secret.
![Screen Shot 2021-04-01 at 3 35 42 PM](https://user-images.githubusercontent.com/5952735/113361210-49a89480-9300-11eb-9d5c-37c3bee0ca26.png)
2. Save my_value_secret with no changes made.
![Screen Shot 2021-04-01 at 3 43 48 PM](https://user-images.githubusercontent.com/5952735/113361532-1adeee00-9301-11eb-8502-700cc0af2ab9.png)
3. Create Airflow Variable in UI, my_value
![Screen Shot 2021-04-01 at 3 46 46 PM](https://user-images.githubusercontent.com/5952735/113361748-7c06c180-9301-11eb-8a2b-ddc57893c739.png)
4. my_value_secret Variable is rendered as "********" while my_value Variable is rendered as "wow"
![Screen Shot 2021-04-01 at 3 46 17 PM](https://user-images.githubusercontent.com/5952735/113361780-8f199180-9301-11eb-8946-2a0d4bd48e26.png)

```python
from airflow.models import DAG
from datetime import datetime
from airflow.models import Variable
from airflow.operators.bash import BashOperator

dag = DAG(
    dag_id="trigger_dag",
    start_date=datetime(2021, 3, 10),
    catchup=False,
    schedule_interval='@once',
)

with dag:
    put_task = BashOperator(
        task_id='put_task',
        bash_command=
        '{{ var.value.my_value }} | '
        '{{ var.value.my_value_secret }} | '
        ,
        env={
            'password': Variable.get(f"my_value"),
            'password2': Variable.get(f"my_value_secret"),
        }
    )
```

Can you verify that your scenario is reproducible on your end? Also if you are able to reproduce the issue, can you print out the secret value in a PythonOperator to see its true value?

**Comment by saveriogzz** [comment]
Hey @wolfier thanks for your help!  
You are iright indeed, the password was not "correctly rendered as secret" but simply saved as the actual value "********" after an edit..
I will close this and follow #8421 

Thanks a lot again!! ❤️
