### ISSUE TITLE
Allow labelling of task dependencies

### ISSUE THREAD

**Issue by andrewgodwin** [apache/airflow#15140]
It would be beneficial to larger/more complex DAGs to be able to label the dependency edges between tasks so that, in the graph view (and potentially other places), we can show this information to the user:

![image](https://user-images.githubusercontent.com/36182/113329516-e9ebc280-92da-11eb-92a1-2a0f5428780c.png)

The proposed syntax for this would allow for use with both the `>>` style and `set_upstream` style of declaring dependencies:

```
mean_height >> Label("Output") >> print_result
mean_height .set_downstream(print_result, Label("Output"))
```

There would be no runtime effect initially; it would just be for displaying and understanding the DAGs.

I have a PR cooking for this, and will push a WIP of it and link it here shortly.

**Comment by ashb** [comment]
Cc @eladkal

**Comment by eladkal** [comment]
This is really cool. I'm glad to see that you thought of it.
This is something that i'm thinking about for a while and I believe to be one of the features that will make a big impact!

**Comment by uranusjr** [comment]
How about hiding the `Label` class from the user entirely? Something like `task1 << "Label" << task2` and create the label automatically in `_set_relatives()`.

**Comment by devhmars** [comment]
the commit closing this issue doesnt seem to implement the asked for functionality

**Comment by potiuk** [comment]
> the commit closing this issue doesnt seem to implement the asked for functionality

Feel free to implement it then. I am not sure what you wantted to achieve by commenting it ? Which functionality? What is missing? If you think something is missing - either implement it or clearly describe it in a new issue where you will explain what and why you are missing.
