### ISSUE TITLE
Separate K8sPodOperator code from airflow core code

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#15164]
**Description**

Currently, the KubernetesPodOperator uses the pod_launcher class in airflow core. This means that if we need to fix a bug in the KubernetesPodOperator such as https://github.com/apache/airflow/pull/15137 then the new cncf.kubernetes package will require an Airflow upgrade. Since we hope to release providers in a much faster cadence than Airflow core releases, we should separate this dependency.

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

**Comment by SamWheating** [comment]
I can take this one, since I'm already dealing with the linked k8spodoperator issue 👍

**Comment by dimberman** [comment]
Hey @SamWheating I'm sorry to do this but I actually just put up a PR for this (I started hacking it out of curiosity and got a little carried away) https://github.com/apache/airflow/pull/15165

If you'd like you're welcome to take it from here, or we can just mine merged in quickly and then immediately merge yours once you rebase (we can then start the process of releasing a new provider ASAP to unblock you)

**Comment by SamWheating** [comment]
> Hey @SamWheating I'm sorry to do this but I actually just put up a PR for this (I started hacking it out of curiosity and got a little carried away)

No worries at all! Thanks for the quick turnaround on this 👍

**Comment by SamWheating** [comment]
This was resolved in https://github.com/apache/airflow/pull/15165 and can be closed now :)
