### ISSUE TITLE
Airflow Init:CrashLoopBackOff after K8S restart

### ISSUE THREAD

**Issue by jagusztinl** [apache/airflow#15160]
**Apache Airflow version**:
v2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.19

**What happened**:
Deployed AIrflow to K8S:
helm install -f bitnami_values.yaml airflow-k8s bitnami/airflow \
--set executor=KubernetesExecutor \
--set redis.enabled=false \
--set rbac.create=true \
--set serviceaccount.create=true \
--set auth.username=my-user \
--set auth.password=my-passsword \
--set git.dags.enabled=true \
--set git.dags.repositories[0].repository=https://github.com/apache/airflow \
--set git.dags.repositories[0].branch=master \
--set git.dags.repositories[0].path=airflow/example_dags \
--set git.dags.repositories[0].name=Examples \

Worked perfectly. Then stopped the K8S cluster, and started again. 
Airflow containers did not start, the clone-repositories init container failed:

fatal: destination path '/dags-examples' already exists and is not an empty directory.

**What you expected to happen**:

 clone-repositories init container not handling well the restarts

**How to reproduce it**:

Install Airflow (described above) start some workflow then and restart K8S

**Anything else we need to know**:
Reproducable every time

**Comment by xinbinhuang** [comment]
This issue is related to the bitnami helm chart in use, and you should open an issue there.
