### ISSUE TITLE
Task doc is not shown on Airflow 2.0 Task Instance Detail view

### ISSUE THREAD

**Issue by Matts966** [apache/airflow#15178]
**Apache Airflow version**: 932f8c2e9360de6371031d4d71df00867a2776e6

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: locally run `airflow server`

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): mac
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Task doc is shown on Airflow v1 Task Instance Detail view but not shown on v2.

**What you expected to happen**:

Task doc is shown.

**How to reproduce it**:

- install airflow latest master
- `airflow server`
- open `tutorial_etl_dag` in `example_dags`
- run dag(I don't know why but task instance detail can't open with error if no dag runs) and open task instance detail

**Comment by kaxil** [comment]
I was able to reproduce it and will fix it for 2.0.2

**Comment by KulykDmytro** [comment]
just figured out:
enabling of `STORE_SERIALIZED_DAGS` leads to this issue
