### ISSUE TITLE
CLI 'kubernetes cleanup-pods' should only clean up Airflow-created Pods

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#15193]
**Update**

We discussed and decide this CLI should always only clean up pods created by Airflow.

<hr>

### Description

Currently command `kubernetes cleanup-pods` cleans up Pods that meet specific conditions in a given namespace.

Underlying code: https://github.com/apache/airflow/blob/2.0.1/airflow/cli/commands/kubernetes_command.py#L70

### Use case / motivation

The problem to me is: users may have other non-Airflow stuff running in this specific namespace, and they may want to have different strategy/logic for Pod cleaning-up for these non-Airflow pods.

We may want to have an additional boolean flag for this command, like `--only-airflow-pods`, so that users can decide if they only want to clean up Airflow-created Pods.

It should not be hard to identify Airflow-created pods, given the specific labels Airflow adds to the Pods it creates (https://github.com/apache/airflow/blob/2.0.1/airflow/kubernetes/pod_generator.py#L385)

**Comment by XD-DENG** [comment]
@dimberman @mik-laj  may you please share your inputs on if this makes sense to you or not? Let me know if I overlooked anything. Thanks

**Comment by XD-DENG** [comment]
CC @kaxil @ashb

**Comment by mik-laj** [comment]
in my opinion this is a bug and by default we should only manage pods created by Airflow i.e. we don't need extra option.

**Comment by XD-DENG** [comment]
That's my first thought as well, but I would like to hear the original author's opinion, like if there is any specific reason or not 

This feature was added in https://github.com/apache/airflow/pull/11802 . @kaxil may you please share your inputs? Cheers!

**Comment by potiuk** [comment]
> in my opinion this is a bug and by default we should only manage pods created by Airflow i.e. we don't need extra option.

My thoughts exactly!

**Comment by kaxil** [comment]
Hey, thanks for this issue @XD-DENG . I added this feature and we use it in Astronomer too -- to cleanup any hanging PODs and their sidecars. So yeah we can just restrict it to pod launched via Airflow.

**Comment by XD-DENG** [comment]
Thanks everyone.

I think we have come to a consensus. So I will change `kind: feature` to `kind: bug` and work on this later.
