### ISSUE TITLE
SCHEDULED TASKS ARE STUCK IN THE STATE OF "RUNNING"

### ISSUE THREAD

**Issue by iremonur** [apache/airflow#15192]
Hi,

I am trying to schedule 4 tasks to be 10 minutes between each other, I want the first task to start at 19:20.
In the dag code (located in ~/airflow/dags/example_v6.py), I set:
-> start_date=datetime.datetime(2021, 4, 4, 19, 20)
-> schedule_interval= '*/10 * * * *'
The first task is succeeded but the other three of them are stuck in the state of "running".
Some of the parameters I set in the dag code :
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'wait_for_downstream' : False,
    'email': ['airflow@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

I run these commands to schedule the dag:
$ python ~/airflow/dags/example_v6.py
$ airflow db init
$ airflow dags backfill dag_v6 -s 2021-04-04-19:20 -e 2021-04-04-19:50

I got these messages from the terminal:
![Screenshot from 2021-04-04 22-44-39](https://user-images.githubusercontent.com/47700082/113519924-239d2180-9598-11eb-9df6-b6dfb698feb6.png)

Apache Airflow version: v2.0.1
Kubernetes is not used.
I use the SequentialExecutor.

Environment:

- GPU : NVIDIA Quadro K3100M
- OS:   Ubuntu 18.04
- Python 3.7.3

At the UI, the tasks are listed as:
![Screenshot from 2021-04-04 22-49-25](https://user-images.githubusercontent.com/47700082/113519910-0bc59d80-9598-11eb-9351-7ede519aad97.png)

I would be very glad if you help me with this.

**Comment by parkyo** [comment]
I found this issue on ovio.org and would love to contribute!

**Comment by iremonur** [comment]
Thank you, it would be great ! Could you share the link related to the issue ?

**Comment by iremonur** [comment]
Actually, I tried schedule to another tasks to be 10 minutes between each other, I want the first task to start at 19:50.
In the dag code (located in ~/airflow/dags/tutorial_v2.py), I set:
-> start_date=datetime.datetime(2021, 4, 4, 19, 50)
-> schedule_interval= '*/10 * * * *'
The first task is succeeded but the other three of them are stuck in the state of "running".
Some of the parameters I set in the dag code :
default_args = {
'owner': 'airflow',
'depends_on_past': False,
'wait_for_downstream' : False,
'email': ['airflow@example.com'],
'email_on_failure': False,
'email_on_retry': False,
'retries': 1,
'retry_delay': timedelta(minutes=5),
}

I run these commands to schedule the dag:
$ python ~/airflow/dags/tutorial_v2.py
$ airflow db init
$ airflow dags backfill dag_v6 -s 2021-04-04-19:50 -e 2021-04-06
The tasks which have the execution time at future are succeeded but some of the tasks at the beginning are stuck in the state of "running" :+1: 
![Screenshot from 2021-04-05 10-07-44](https://user-images.githubusercontent.com/47700082/113547538-c97f7900-95f6-11eb-9cf7-34eba7ce6df4.png)

I don't understand why the scheduler skip some of the tasks, I would be very glad if you help me with this.

**Comment by hafid-d** [comment]
Any update on this ? Facing the same issue!

**Comment by eladkal** [comment]
If someone is experiencing similar issue with latest airflow version please comment and share reproduce steps
