### ISSUE TITLE
ExternalTaskSensor not working python3.6 & airflow2.0.1

### ISSUE THREAD

**Issue by EunSeop** [apache/airflow#15196]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): not used

**Environment**: Mac os(Catalina)

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Mac os(Catalina)
- **Kernel** (e.g. `uname -a`): `Darwin AL01590440.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
- **Install tools**: pyenv, pip 
- **Others**: python 3.6.13

**What happened**: 
Example task of externaltasksensor doesn't work. 
`example_external_task_marker_child` is never success even I tried `example_external_task_marker_parent` at the same time. 
And finally, `example_external_task_marker_child` become failed due to timeout. 

**How to reproduce it**:
- install python 3.6.13 using pyenv
- install latest airflow(2.0.1)
- setup db(default, maybe sqlite?), and add user, start scheduler, and run webserver
- trigger `example_external_task_marker_child` and `example_external_task_marker_parent` at the same time,
- Also tried `example_external_task_marker_parent` and `example_external_task_marker_child` but it shows same situation.

![image](https://user-images.githubusercontent.com/6908807/113526783-48c07d00-95f6-11eb-9889-df1a85f159d3.png)

**Anything else we need to know**:
Also had same situation in `CentOS Linux release 7.4.1708`.

**Comment by EunSeop** [comment]
Got same situation on `apache-airflow==1.10.14`.

**Comment by EunSeop** [comment]
Did I missing any setup of airflow? same situation on `python==3.7.10` & `apache-airflow==2.0.1`

**Comment by EunSeop** [comment]
It's working after set schedule.

**Comment by DenisOgr** [comment]
@EunSeop how did you set DAG schedule so that it worked? 
I set up `schedule_interval='@weekly',`  cleaned database, and turned on the  DAGs: `example_external_task_marker_parent` and `example_external_task_marker_child`. After that my scheduler failed with the error: `AttributeError: 'TaskInstance' object has no attribute 'task'`

**Comment by EunSeop** [comment]
@DenisOgr I never saw that message. Airflow 2.0 is not perfectly support python 3.6, so I decided upgrade python version using pyenv. Please check airflow and python versions. 
And to make run ExternalTaskSensor, if we decided use `schedule_interval='@weekly'`, then `start_date` should be over 7 days ago to make run immediately. Or can use airflow dags cli to run 2 dags at the same time.
