### ISSUE TITLE
SCHEDULER SKIPS SOME OF THE SCHEDULED TASKS 

### ISSUE THREAD

**Issue by iremonur** [apache/airflow#15202]
I am trying to schedule tasks to be 10 minutes between each other, I want the first task to start at 20.00.
In the dag code (located in ~/airflow/dags/tutorial_v2.py), I set:
-> start_date=datetime.datetime(2021, 4, 4, 19, 50)
-> schedule_interval= '*/10 * * * *'
Some of the parameters I set in the dag code :
default_args = {
'owner': 'airflow',
'depends_on_past': False,
'wait_for_downstream' : False,
'email': ['airflow@example.com'],
'email_on_failure': False,
'email_on_retry': False,
'retries': 1,
'retry_delay': timedelta(minutes=5),
}

I run these commands to schedule the dag:
$ python ~/airflow/dags/tutorial_v2.py
$ airflow db init
$ airflow dags backfill tutorial_v2 -s 2021-04-04-19:50 -e 2021-04-06
Some of the tasks at the beginning are stuck in the state of "running" :
NOTE: When I run these commands, the date of the database was: 4 April 2021 / 19:57.
![Screenshot from 2021-04-05 10-07-44](https://user-images.githubusercontent.com/47700082/113557544-d906be00-9606-11eb-98df-09292ff33c03.png)

Apache Airflow version: v2.0.1
Kubernetes is not used.
I use the SequentialExecutor.

Environment:

GPU : NVIDIA Quadro K3100M
OS: Ubuntu 18.04
Python 3.7.3

I don't understand why the scheduler skip some of the tasks, I would be very glad if you help me with this.

**Comment by eladkal** [comment]
I'm not able to reproduce this.
Did it happened one time ?

**Comment by iremonur** [comment]
The problem is solved, thank you
