### ISSUE TITLE
Add setting up using VS Code to CONTRIBUTORS_QUICK_START.rst

### ISSUE THREAD

**Issue by ByPort** [apache/airflow#15205]
**Description**

In the CONTRIBUTORS_QUICK_START.rst (and not only there) I can see some parts that are tied to PyCharm. There is nothing complicated and specific to PyCharm, but I can understand that - explicit is better than implicit. But in this case, I think it would be nice to cover other IDEs and code editors as well.

**Use case / motivation**

As a new contributor I want to set up the project using my favorite IDE or code editor. As a VS Code user I want to set up the project using VS Code. To achieve this - I want CONTRIBUTORS_QUICK_START.rst to have instructions for VS Code.

**Are you willing to submit a PR?**

I can submit a PR, but first decided to ask if it is worth doing this at all. Because as I said earlier, the instructions for PyCharm are quite trivial and non-specific. So there won't be anything special for VS Code either.

**Related Issues**

No

**Comment by potiuk** [comment]
@ByPort  absolutely - feel free to submit a PR.
