### ISSUE TITLE
Operators in cncf.kubernetes provider are configured differently

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#15219]
The operators in the cncf.kubernetes provider use different methods of configuring where the k8s cluster you want run against is. `KubernetesPodOperator` uses `in_cluster`, `cluster_context`, and/or `config_file`, while `SparkKubernetesOperator` uses a Kubernetes Cluster connection with the specifics in extras.

**Use case / motivation**

The operators in this provider should be configured in the same manner to keep things consistent and avoid confusion.

**Related Issues**

#13006

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/22086
