### ISSUE TITLE
Scheduler livenessprobe and k8s v1.20+

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#15259]
Pre Kubernetes v1.20, exec livenessprobes `timeoutSeconds` wasn't functional, and defaults to 1 second. The livenessprobe for the scheduler, however, takes longer than 1 second to finish so the scheduler will have consistent livenessprobe failures when running on v1.20.

> Before Kubernetes 1.20, the field timeoutSeconds was not respected for exec probes: probes continued running indefinitely, even past their configured deadline, until a result was returned.

```
...
  Warning  Unhealthy  23s    kubelet            Liveness probe failed:
```

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes

**Kubernetes version**: v1.20.2

**What happened**:

Livenessprobe failures keeps restarting the scheduler due to timing out.

**What you expected to happen**:

Livenessprobe succeeds.

**How to reproduce it**:

Deploy the helm chart on v1.20+ with the default livenessprobe `timeoutSeconds` of 1 and watch the scheduler livenessprobe fail.

**Comment by thesuperzapper** [comment]
I had to fix this for `stable/airflow` as well, all you need to do is increase `timeoutSeconds`, for example:
https://github.com/airflow-helm/charts/blob/airflow-8.0.6/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L110

**Comment by kimyen** [comment]
@thesuperzapper upgrading helm from 7.x to 8.x to get this value is a major change with consequences: https://github.com/airflow-helm/charts/blob/main/charts/airflow/UPGRADE.md#v715x--v800

We are not ready to commit to Python version upgrade and Airflow version upgrade. Major Airflow upgrade takes months for us. Can we have this patch in 7.x to expose this value?

**Comment by thesuperzapper** [comment]
@kimyen while not explicitly stated in the docs of the `stable/airflow` chart, you can use `8.X.X` chart versions with an older airflow/python version.

For example, the values to use `airflow 2.0.1` with `python 3.6`:
```yaml
airflow:
  image:
    repository: apache/airflow
    tag: 2.0.1-python3.6
```

For example, the values to use `airflow 1.15.0` with `python 3.6`:
```yaml
airflow:
  # needed for airflow 1.10 to work
  legacyCommands: true

  image:
    repository: apache/airflow
    tag: 1.10.15-python3.6
```
