### ISSUE TITLE
Update GoogleAdsHook to authenticate via OAuth2

### ISSUE THREAD

**Issue by jacobhjkim** [apache/airflow#15269]
**Description**
Currently, GoogleAdsHook only supports the `service account authentication flow`. It would be nice to have a way to authenticate with `OAuth2 installed application flow`.

**Use case / motivation**
[AdWords API Doc](https://developers.google.com/adwords/api/docs/guides/authentication#an_alternative_to_service_accounts) 
> Because of the complexity of setting up service account access for the AdWords API, we recommend a simpler alternative that achieves the same goal, which is to use the OAuth2 installed application flow

To quote Google, service account flow is a hassle, and they recommend `OAuth2 installed application flow`. With this feature, GoogleAds operator users will be able to choose which authentication flow to use.

**Are you willing to submit a PR?**
Yes!

**Related Issues**
AIRFLOW-6732

**Comment by eladkal** [comment]
@jacobhjkim assigned to you

**Comment by eladkal** [comment]
@jacobhjkim are you still working on this issue?

**Comment by jacobhjkim** [comment]
I'm not working on this issue. I think we can close it for now.
