### ISSUE TITLE
Changing datetime will never show task instance logs

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#15261]
This is an extension of #15103

**Apache Airflow version**: 2.x.x

**What happened**:

Once you get to the task instance logs page, the date will successfully load at first. But if you change the time of the `execution_date` from the datetimepicker in any way the logs will be blank. 
The logs seem to require exact datetime match, which can be down 6 decimal points beyond a second.

**What you expected to happen**:

Logs should interpret a date and allow for at least only to the nearest whole second, which the UI can then handle. Although a better UX should allow flexibility beyond that too.
or
Remove the datetimepicker because logs would only happen at the exact point a task instance occurs.

**How to reproduce it**:

![Apr-07-2021 16-56-10](https://user-images.githubusercontent.com/4600967/113933125-d00a1e00-97b9-11eb-939c-9907d8ff34ac.gif)

**Anything else we need to know**:

Occurs every time

**Comment by uranusjr** [comment]
Another semi-related issue is the datetime picker currently shows the local time, but the logs are in UTC, resulting in quite unintuitive behaviour. Personally I feel removing the datepicker is a good solution.
