### ISSUE TITLE
Feature "The scheduler won’t trigger your tasks until the period it covers has ended" be Optional

### ISSUE THREAD

**Issue by ravog** [apache/airflow#15294]
**Description**

It would be great to have the option to disable the feature "The scheduler won't trigger your tasks until the period it covers has ended"

**Use case / motivation**

It is very difficult and confusing to add new DAGs and execute the tasks that are needed at the same time and not wait for the period to complete

**Comment by XD-DENG** [comment]
I don't very well get your use case here. May you please clarify a bit more? Thx.

**Comment by jedcunningham** [comment]
[AIP-39](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-39+Richer+scheduler_interval) will do this when it is finished with the (currently named) `CronTimetable` class.

**Comment by PrideIsLife** [comment]
Hi,
When is the `CronTimetable` class supposed to be implemented @jedcunningham ?
I saw that the API-39 was completed and added to airflow 2.0 but I can't see to find the class.

**Comment by eladkal** [comment]
covered by AIP-39. You can use Timetable for this
https://airflow.apache.org/docs/apache-airflow/stable/concepts/timetable.html
