### ISSUE TITLE
Add CLI to delete roles

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#15318]
Currently there is no option to delete a role from CLI which is very limiting.
I think it would be good if CLI will allow to delete a role (assuming no users are assigned to the role)

**Comment by jhtimmins** [comment]
@alexInhert can you share some info about why it's inconvenient to do this through the UI?

**Comment by alexInhert** [comment]
@jhtimmins because it's part of the environment setup that we do and we want to run commands in script.
we modify roles and permissions constantly and doing it from scripts is much easier.
Also it's very odd that you can do something from UI but not from CLI

**Comment by divyeshransariya** [comment]
@jhtimmins @alexInhert  Do you guys know how to modify permission for a given role using CLI?

**Comment by alexInhert** [comment]
@jhtimmins is that a reasonable use case or shall I close this request?

**Comment by divyeshransariya** [comment]
Also i want to know, is there any cli command that can modify existing permissions for given role?

**Comment by uranusjr** [comment]
I don’t think there are.

**Comment by divyeshransariya** [comment]
> Are they gonna add any `cli` command to modify existing perms ?

**Comment by uranusjr** [comment]
I think the CLI *should* be able to modify permissions on an existing role, so feel free to submit a pull request implementing such an endpoint if you need it.

**Comment by divyeshransariya** [comment]
> I think the CLI _should_ be able to modify permissions on an existing role, so feel free to submit a pull request implementing such an endpoint if you need it.

Found another way, used DAG level access control. In my use case it helps me a lot.
