### ISSUE TITLE
Support WebHook Alerting

### ISSUE THREAD

**Issue by blcksrx** [apache/airflow#15322]
**Description**
It's a good idea to have such a feature like we already have it `email_on_failure` also for webhooks that lets the users configured it once to alert in Slack, Mattermost, etc. I know it's possible to write a callback function and set the `on_failure_callback` but it needs to each user develop it for his/her goods. In addition, supporting this provides a better user experience 

**Are you willing to submit a PR?**
Yes

**Comment by mik-laj** [comment]
This looks like a feature that requires a discussion of the body format that we will be sending in request. Could you please prepare a document and then start discussions on the mailing list?

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/issues/14622

**Comment by eladkal** [comment]
somehow related to https://github.com/apache/airflow/issues/8686

**Comment by blcksrx** [comment]
@mik-laj Thanks for your comment. I will do it

**Comment by blcksrx** [comment]
I would like to present a new feature in airflow. It's a good idea to support webhooks triggers for notifying users about their tasks.
we can do it by providing it in a way that I could supports software like Slack, MatterMost, Discord, MS Teams. this software currently uses by a wide range of international users.
This feature provides a better UX for our users and also reduces efforts for every company/user who uses airflow to write their own callbacks.

Here is my initials idea:
- Changes in the `default_args`:
  - add new entry: `webhook_on_failure: bool`
  - add new entry: `webhook_on_retry: bool`
  - add new entry: `webhook_on_success: bool`
  - add new entry: `channels: List[str]` (List of channels)
  - add new entry: `mentions: List[str]` (List of users to mention)
- Changes in the `airflow.cfg`:
  - add new seciont like `[webhook]` for Slack, etc. configuration.
- Message templates:
    I would like to do it like the Prometheus alerting template.
  
  
About message templates, I mean something like this. 
![Screenshot from 2021-04-12 19-14-41](https://user-images.githubusercontent.com/35199552/114437811-4dbd9780-9bc7-11eb-81aa-da504b520037.jpg)

**Comment by blcksrx** [comment]
@mik-laj is this good?

**Comment by eladkal** [comment]
Two related issues: https://github.com/apache/airflow/issues/8686 https://github.com/apache/airflow/issues/12611

**Comment by ashb** [comment]
Closing in favour of the more general purpose https://github.com/apache/airflow/issues/12611
