### ISSUE TITLE
`PythonVirtualenvOperator` does not push to XCom from return in 2.0.1

### ISSUE THREAD

**Issue by dsynkov** [apache/airflow#15335]
**Apache Airflow version**: 2.0.1

**What happened**:

I've edited the `pusher` / `puller` example DAG from https://github.com/apache/airflow/issues/12985 and am using the below example to test. I expect the value returned from the `pusher` tasked to be consumable by `puller` through XCom.

I've tested this DAG and the XCom works as expected in the `master` branch and `1.10.14` but not in `2.0.1`.

```
import airflow
from airflow import DAG
from airflow.operators.python_operator import PythonVirtualenvOperator

args = {
    'owner': 'Airflow',
    'start_date': airflow.utils.dates.days_ago(2),

}

dag = DAG('python_virtualenv_dag', schedule_interval="@once", default_args=args)


def push_by_returning():
    import json
    values = ['a', 'b', 'c']
    return json.dumps(values)


def pull_from_return(values):
    import json
    values_list = json.loads(values)
    assert values_list == ['a', 'b', 'c']
    print(values_list)


pusher = PythonVirtualenvOperator(
    task_id='pusher',
    dag=dag,
    python_callable=push_by_returning,
    requirements=[],
    python_version='3.7'
)

puller = PythonVirtualenvOperator(
    task_id='puller',
    dag=dag,
    op_kwargs={'values': '{{ ti.xcom_pull(task_ids="pusher") }}'},
    python_callable=pull_from_return,
    requirements=[]
)

pusher >> puller
```

**What you expected to happen**:

I expect the return values `['a', 'b', 'c']` to be available in XCom.

**How to reproduce it**:

Run the above DAG in `2.0.1`.

**Anything else we need to know**:

Only started noticing after migrating from `1.10.14` to `2.0.1`.

**Comment by dsynkov** [comment]
This seems to be resolved by https://github.com/apache/airflow/pull/14061 with the `2.1.0` release; closing this issue.

**Comment by XiaoXin101** [comment]
Is it necessary to upgrade?

**Comment by potiuk** [comment]
Yes. And it's generally advised to upgrade to latest 2.* version. We are following SemVer versioning and 2.* releases are backwards compatible to install. Also the security fixes in the future will be applied to latest minor release, so it is generally advised to upgrade to latest minor release as soon as possible.

We have the whole discussion panel about it at Airflow Summit next month: Highly recommended https://airflowsummit.org/sessions/2021/panel-airflow-security/
