### ISSUE TITLE
Error: no repository definition for @stable when helm dependency update for tag 2.0.1

### ISSUE THREAD

**Issue by patsevanton** [apache/airflow#15342]
Hello! Thanks for airflow!

```
git clone https://github.com/apache/airflow.git
cd airflow/chart
git checkout 2.0.1
helm dependency update
```

**Error:**
`Error: no repository definition for @stable. Please add them via 'helm repo add'`

**git branch**
```
* (HEAD detached at 2.0.1)
  master
```

**Comment by patsevanton** [comment]
If use master - no error
**git checkout master**
```
Previous HEAD position was 5786dcdc3 Add Changelog & Updating.md for 1.10.15
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

**helm dependency update**
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
```

**Comment by patsevanton** [comment]
May be create new release/tag?

**Comment by jedcunningham** [comment]
Hi @patsevanton, you should use the chart from master at the moment. The helm chart will follow a separate release cycle and the first "official" release is currently targeting the first week of May. You can track it at: https://github.com/apache/airflow/projects/7

**Comment by jedcunningham** [comment]
#10752 will cover the first official release.
