### ISSUE TITLE
Some more information regarding custom view plugins would be really nice!

### ISSUE THREAD

**Issue by StartedFromTheButton** [apache/airflow#15353]
**Description**
Some more information regarding custom view plugins would be really nice

**Use case / motivation**
I have created a custom view for airflow which was a little tricky since the Airflow docs are quite short and most of the information in the www is out of date.
Additionally the only example cannot simply be copied and pasted. 
Maybe one example view would be nice or at least some more information (especially how to implement the standard Airflow layout or where to find it)

Maybe some additional documentation would be nice or even a quick start guide?

**Are you willing to submit a PR?**

Would be a pleasure after some discussion! 

**Related Issues**
I haven't found any related issues

Some feedback would be nice since this is my first issue:)

**Comment by StartedFromTheButton** [comment]
I would really like to contribute! This sounds like a good starting point. Even if it's only a section about implementing the airflow layout

**Comment by mik-laj** [comment]
Yea! We should expand this documentation.  I see a lot of questions about how to write plugins.

We have an example plugin in the repo but it is not described in the documentation.
https://github.com/apache/airflow/tree/master/metastore_browser

**Comment by StartedFromTheButton** [comment]
What do you think of replacing the old example with the one you mentioned and adding some additional documentation?

**Comment by Bowrna** [comment]
> Yea! We should expand this documentation. I see a lot of questions about how to write plugins.
> 
> We have an example plugin in the repo but it is not described in the documentation. https://github.com/apache/airflow/tree/master/metastore_browser

Could I start adding documentation for this example plugin @mik-laj ?

**Comment by mik-laj** [comment]
@Bowrna Assigned.

**Comment by Bowrna** [comment]
I am currently working on this issue (and another one too) and hope to make some progress by this weekend.

**Comment by Bowrna** [comment]
I can add one more example for the plugin using Listener. Could I add that code and docs for it as separate PR?

**Comment by potiuk** [comment]
Yep.
