### ISSUE TITLE
Link to provider package documentation/source code for providers maintained outside of Airflow GitHub

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#15356]
**Description**

I think it'd be helpful to have a block in the [documentation](https://airflow.apache.org/docs/) that links to airflow providers that exist outside of the airflow repository (e.g. [Great Expectations](https://github.com/great-expectations/great_expectations) or [airflow-dbt](https://pypi.org/project/airflow-dbt/) if that is ever converted into an Airflow provider package)

**Use case / motivation**
It would help make the community more aware of the Airflow providers that are available in the wild outside of the Airflow repo

**Are you willing to submit a PR?**

Yep! I think as of now it would only be Great Expectations, but given Cloudera's interest in developing a provider and talk of a dbt provider package, I think it could be useful.

Let me know what you think :)

**Comment by xinbinhuang** [comment]
I think it will be a good feature! Probably a new section along the line with `Community Providers Packages`. Thoughts? @mik-laj

**Comment by potiuk** [comment]
How about adding a section in https://airflow.apache.org/ecosystem/ ?

Astronomer has this searchable and navigable registry now: https://www.astronomer.io/blog/astronomer-registry and I think it's really cool and great that they are maintaining it. from the community point of view, just section with links in the Ecosystem page should be more than enough. 

There is a good reason why it should not be more "prominently" displayed or endorese. ASF has very strict rules when it comes to trademarks, logo and what is the "ASF owned" part: https://www.apache.org/foundation/marks/#guidelines. 

Any 3rd-party link have to be clearly separated out and labeled as non-ASF. This is why our Ecosystem page contains this disclaimer:

```
Those resources and services are not maintained, nor endorsed by the Apache Airflow Community and Apache Airflow project (maintained by the Committers and the Airflow PMC). Use them at your sole discretion. The community does not verify the licences nor validity of those tools, so it’s your responsibility to verify them.
```

So simply adding a section with providers seems like a good idea @RNHTTR  - WDYT Maybe a PR with those?

**Comment by mik-laj** [comment]
I agree with @potiuk . Rather, we should not add documentation for other packages unless absolutely necessary. We can only create a new page - Community Providers Packages in the documentation and add a link to the ecosystem website. 

After that, there is also the problem of updating the documentation. We update the documentation relatively rarely compared to the website. If you want to make a change to the website, just create a PR for the airflow-site repository and after merging, this change is visible.  Documentation is generated manually, so we only do it when releasing new releases.

**Comment by RNHTTR** [comment]
That makes sense. I probably should've raised the issue on the airflow-site repo -- that was the intention. That said, would it make sense to also include a link at https://airflow.apache.org/docs/ that links to the ecosystem page?

**Comment by potiuk** [comment]
The link is there in the menu I believe ?

**Comment by RNHTTR** [comment]
I created a [PR to the airflow-site repo](https://github.com/apache/airflow-site/pull/411).
