### ISSUE TITLE
Airflow 2.0 Scheduler suddenly stopped queuing tasks

### ISSUE THREAD

**Issue by gvazharov** [apache/airflow#15369]
Hello folks,

I am using Airflow 2.0 with the KubernetesExecutor and Postgres DB as config database, after more than a month in production one of my dags has stopped working out of no where.

The problem is that the scheduler is creating new dag runs, but the tasks inside the dag are not queued, in the scheduler logs could be found the following:
_[2021-04-14 14:51:02,666] {{scheduler_job.py:1667}} INFO - DAG tool_statistic_dag already has 16 active runs, not queuing any tasks for run 2021-04-14 12:20:00+00:00_

In the UI all previous dag runs are successfully finished and no running tasks are displayed, I've checked also the status of all my previous dag runs in Postgres, but didn't found anything that is running and could cause any vulnerability. 

I am not quite sure how to reproduce this behavior, but I had the same problem in my test environment and the only solution to fix the dag was to delete it and import it again, after that everything start to run smoothly again. Because now the problem is in the production environment I don't want to do that again, therefore I will be glad to get your support.

Just for info, this is my first Dag, that is using Task Groups.

Here you can see my tree view:

![Scheduler_Problem](https://user-images.githubusercontent.com/32455036/114716303-38b24700-9d34-11eb-9de6-9db29334b370.png)

**Comment by ashb** [comment]
Did you by any chance clear the state of any of the old dag runs?

I ask since the log says "has 16 active runs" but the screenshot only shows 2.

**Comment by gvazharov** [comment]
Hi @ashb,

Yes, I have tried to clear couple old dag runs, by them everything is working properly, they are cleared, then started again and their task are successfully queued and executed, but tasks in the new dag runs are still not queued and executed.

**Comment by kaxil** [comment]
>:[2021-04-14 14:51:02,666] {{scheduler_job.py:1667}} INFO - DAG tool_statistic_dag already has 16 active runs, not queuing any tasks for run 2021-04-14 12:20:00+00:00


This is the underlying issue though, 


Can you check the Airflow Webserver -> Admin -> Pools  and then in the row with your pool (`default`) check the Used slots. And click on the number in Used slots, it should take you to the TaskInstance page that should show the currently "running" taskinstances in that Pool.

It is possible that they are not actually running but somehow got in that state in DB. If you see 3 entries over here, please mark those tasks as success or failed, that should clear your pool.

![image](https://user-images.githubusercontent.com/8811558/113708634-64508400-96d9-11eb-8505-2c293f0d2f44.png)

![image](https://user-images.githubusercontent.com/8811558/113708679-72060980-96d9-11eb-8c11-6c84a9c64801.png)

**Comment by gvazharov** [comment]
Hi, 

I've checked, they were no task instances in running state.

I think the problem can be reproduced, when you delete a failed task instance from the UI. 
At this point the task instance is deleted from the UI and from the Postgres task_instance table, but the data sets which are related to this deleted task_instance are not removed from the other postgres tables, such as dag_run, job, log and rendered_task_instance_fields. 
For me exactly because of this reason, somehow airflow is thinking that this deleted task_instance is running, because it cannot be found in the task_instance table, but the execution_time and dag_id of this instance could be found in all other tables. 

I am not quite sure if exactly this is the problem, but should be definitely directed in this way.

As a solution of this problem I delete manually all data sets related to my dag from all postgres tables for the previous couple days(from the day, that the problem started to occur, till now) , started again the dag and the problem was solved.

**Comment by ashb** [comment]
> somehow airflow is thinking that this deleted task_instance is running, because it cannot be found in the task_instance table

I can confirm that this is categorically not the case. The task_instance (and dag_run) table is the only place the only place the Scheduler looks at.

**Comment by gvazharov** [comment]
Hi @kaxil, neither in the UI, nor in the database something was in running state, I've checked all database tables for something that on first look could cause the problem, but found nothing disturbing..

I have deleted the failed task instance from the UI, because there was some timeout error, which was caused from another services, all previous executions of this dag were successful and I had only 1 failed instance that was irrelevant for me, that's why I removed it in order the UI to be clear and if any relevant new error dag runs occur to see them straight.

That's right, I guessed also that their shouldn't be any connection between the tast_instance table, with the other once, but somehow because the execution_time + dag_id exist in the following tables task_instace, dag_run, log and rendered_task_instance_fields and thought that probably in the background Airflow make some relation between them.

For me was also interesting to find how are the [currently_active_runs](https://github.com/apache/airflow/blob/beb8af5ac6c438c29e2c186145115fb1334a3735/airflow/jobs/scheduler_job.py#L1696) set, but didn't manage to do that, wanted to know if some kind of query is made to the database in order to calculate their sum and if yes, how this query looks like.

**Comment by kaxil** [comment]
@gvazharov Yeah that is counted using the following code:

https://github.com/apache/airflow/blob/beb8af5ac6c438c29e2c186145115fb1334a3735/airflow/jobs/scheduler_job.py#L1498-L1521

**Comment by hafid-d** [comment]
Any update on this ? Facing the same issue

**Comment by gvazharov** [comment]
Hi the solution for me was to update the Airflow to 2.0.2

**Comment by ashb** [comment]
Can anyone else confirm if this is fixed? I'm going to mark it as "pending-response" so that it gets auto-closed after a while
