### ISSUE TITLE
Hadoop Dockerfile missing `mkdir`

### ISSUE THREAD

**Issue by prakshalj0512** [apache/airflow#15365]
[hadoop.Dockerfile](https://github.com/apache/airflow/blob/master/docs/docker-stack/docker-images-recipes/hadoop.Dockerfile) missing `mkdir -p "${HADOOP_HOME}"` after [Line 50](https://github.com/apache/airflow/blob/master/docs/docker-stack/docker-images-recipes/hadoop.Dockerfile#L50-L51).

**Comment by mik-laj** [comment]
Are you willing to submit a PR?
