### ISSUE TITLE
The link IMAGES.rst on docker hub is broken

### ISSUE THREAD

**Issue by paulo3011** [apache/airflow#15370]
**Apache Airflow version**: 2.0.1

**What happened**:

The link IMAGES.rst on docker hub is broken
(https://hub.docker.com/r/apache/IMAGES.rst)
https://hub.docker.com/r/apache/airflow

**What you expected to happen**:

Fix the link

**How to reproduce it**:
Go to https://hub.docker.com/r/apache/airflow and seach for "Official Docker (container) images for Apache Airflow are described in IMAGES.rst."

**Comment by kaxil** [comment]
Yeah docker hub uses README.md in the repo where we have relative links.

You can take a look at https://github.com/apache/airflow/blob/master/IMAGES.rst or http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/docker-stack/index.html
