### ISSUE TITLE
Airflow 2.0.1: Dag - Subdag - Scheduler issues

### ISSUE THREAD

**Issue by qu0cster** [apache/airflow#15396]
**Apache Airflow version: 2.0.1
**Python: 3.7
**Install tools**: docker

In attempt to see if the SQLtoGCSOperator is bugged on airflow 1.10.x when exporting out columns with emoji with format JSON, I am trying to upgrade to Airflow 2.  I installed Airflow 1.10.15 and run the "airflow update_check".  Made all the import updates and all. I have it running.

There are two issues I am running into:

1.  I have a Dag that checks to see if any events came in -- ShortCircuit if none.  Otherwise, run the subdag.  Seems like the  subdag is receiving invalid prev_execution_date macros ?

Dag:
![image](https://user-images.githubusercontent.com/5314630/114949712-8a83cb80-9e1f-11eb-8601-97d7a987e4c6.png)

SubDag:
![image](https://user-images.githubusercontent.com/5314630/114949953-1d246a80-9e20-11eb-8540-5d31f0c69240.png)

they both are received_date_utc >= prev_execution_date.to_datetime_string() and received_date_utc < next_execution_date.to_datetime_string() but you can see the difference there.  It did not behave like that in the older version.

2.  The other issue is, the SubDag step won't run unless I cleared it from the Dag side.  I don't know why there.  Locally, I am running SequentialExecutor / sqlite -- ran fine with my previous version. After clearing out the subdag, it ran the first step of it.  scheduled the next and just stop

Here is the sub dag instance details:
![image](https://user-images.githubusercontent.com/5314630/114955729-4e566800-9e2b-11eb-9a30-be194f51bf0d.png)

**What you expected to happen**:
SubDag runs;
SubDag have access to correct prev_execution_date

**Comment by quoc-t-le** [comment]
Just read about TaskGroups and was able to convert subdags over....and i can confirm that the encoding for sql to gcs is fixed for exporting format json that contains emojis also
