### ISSUE TITLE
Not scheduling since there are (negative number) open slots in pool

### ISSUE THREAD

**Issue by wongelz** [apache/airflow#15399]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.16

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Airflow fails to schedule any tasks after some time. The "Task Instance Details" tab of some of the failed tasks show the following: 

```
('Not scheduling since there are %s open slots in pool %s and require %s pool slots', -3, 'transformation', 3)
```

Admin > Pools tab shows 0 Running Slots but 9 Queued Slots. Gets stuck in this state until airflow is restarted.

**What you expected to happen**:

Number of "open slots in pool" should never be negative! 

**How to reproduce it**:
- Create/configure a pool with a small size (eg. 6)
- DAG with multiple tasks occupying multiple pool_slots (eg. pool_slots=3)

**Anything else we need to know**:

**Comment by wongelz** [comment]
I see that `occupied_slots` includes QUEUED as well (`EXECUTION_STATES` includes RUNNING & QUEUED). 

QUEUED tasks shouldn't be occupying slots in the pool should they?

```
    @provide_session
    def occupied_slots(self, session: Session):
        """
        Get the number of slots used by running/queued tasks at the moment.
...
        return (
            session.query(func.sum(TaskInstance.pool_slots))
            .filter(TaskInstance.pool == self.pool)
            .filter(TaskInstance.state.in_(list(EXECUTION_STATES)))
            .scalar()
        ) or 0
```

**Comment by jedcunningham** [comment]
Yes, `QUEUED` should be included, this might help:

https://airflow.apache.org/docs/apache-airflow/stable/concepts.html#task-lifecycle

Basically, `QUEUED` means the executor has passed it along and is waiting for the worker to start/pick it up (depending on your executor).

That said, negative open slots sure does seem like an issue.

**Comment by wongelz** [comment]
@jedcunningham Looks like the `slots_stats` method in `pool.py` may be under-reporting the number of running/queued slots here:

```
        state_count_by_pool = (
            session.query(TaskInstance.pool, TaskInstance.state, func.count())
            .filter(TaskInstance.state.in_(list(EXECUTION_STATES)))
            .group_by(TaskInstance.pool, TaskInstance.state)
        ).all()
```

I think the query should be:

```
session.query(TaskInstance.pool, TaskInstance.state, func.sum(TaskInstance.pool_slots))
```
