### ISSUE TITLE
Improve KubernetesPodOperator error message for env_vars

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#15404]
passing str to `env_vars` gives the following error:
![Screen Shot 2021-04-16 at 12 21 22](https://user-images.githubusercontent.com/62940116/115003269-51466c80-9eae-11eb-95c4-b54ab66f28d1.png)

The error is right but the issue is that the error doesn't specify that the problem is with `env_vars`.
That is really frustrating when working with large dag. It doesn't say the task_id nor the argument that has the problem when makes debugging really hard.

**Comment by Dr-Denzy** [comment]
I will work on this @kaxil

**Comment by Dr-Denzy** [comment]
@alexInhert please could you give more details on how to reproduce this issue.

**Comment by alexInhert** [comment]
sorry this was wrong and local issue on my code
