### ISSUE TITLE
Airflow and Kubernetes and python versions

### ISSUE THREAD

**Issue by coolsubbu** [apache/airflow#15424]
airflow functionalities | Python Version | Airflow version | running?
                                   |                            |                            |   
                 scheduler | 3.7.5 | 1.10.7 | yes
                webserver | 3.7.5 | 1.10.7 | yes
airflow test run on kubernetes pod | 3.7.5 | 1.10.7 | unsupported pickle protocol 5
                 scheduler | 3.7.5 | 1.10.11 | yes
                webserver | 3.7.5 | 1.10.11 | yes
airflow test run on kubernetes pod | 3.7.5 | 1.10.11 | unsupported pickle protocol 5
                scheduler | 3.8.2 | 1.10.11 | yes
                webserver | 3.8.2 | 1.10.11 | yes
airflow test run on kubernetes pod | 3.8.2 | 1.10.11 | yes
               Scheduler | 3.8.2 | 1.10.7 | Can't pickle local object 'SchedulerJob._execute.<locals>.processor_factory
               webserver | 3.8.2 | 1.10.7 | yes
airflow test run on kubernetes pod | 3.8.2 | 1.10.7 | yes
               Scheduler | 3.7.10 | 1.10.7 | yes
              webserver | 3.7.10 | 1.10.7 | yes
airflow test run on kubernetes pod | 3.7.10 | 1.10.7 | unsupported pickle protocol 5

IS there a way to run airflow functionalities on apache-airflow version=1.10.7
using python and have all the above functionalities such as airflow scheduler/webserver and test run on kubernetes pod operator?

**Comment by mik-laj** [comment]
Unfortunately, we no longer provide support for older versions. Please check if this problem occurs in a newer version and create a new ticket if the problem persists.
