### ISSUE TITLE
Getting approx. 25 emails when dag fails

### ISSUE THREAD

**Issue by vedimuthan** [apache/airflow#15435]
I have setup a simple dag to run ECS task via ECSOperator and I would like to be notified when it fails. However, i am receiving approx. 25 emails per run for the failures. Can you please tell me why this is happening?

from airflow import DAG
from airflow.contrib.operators.ecs_operator import ECSOperator
from datetime import datetime, timedelta
import json
from botocore.vendored import requests

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2019, 8, 16, 10, 0),
    'email': ['xxxxxxxxxx.com'],
    'email_on_failure': True,
}

dag = DAG('update_confluence', default_args=default_args,
          schedule_interval="0 13 * * *")

t1 = ECSOperator(
    task_id='xxxxxxx',
    cluster='xxxxxxx',
    launch_type='FARGATE',
    task_definition='xxxxxx:1',
    network_configuration={'awsvpcConfiguration':
                           {
                               'subnets': ['subnet-xxxxxxxx'],
                               'assignPublicIp': 'DISABLED'
                           }
                           },
    overrides={},
    region_name='us-east-1',
    aws_conn_id="aws_default",
    dag=dag)

**Comment by eladkal** [comment]
Is the issue happens in a specific workflow or in all your DAGs?
Can you please share a reproduce code that we can actually run?

**Comment by vedimuthan** [comment]
Yeah, it is happening in all the dags. I am not sure if it is only due to ECS operator. I have pasted the whole dag code above in the issue description.

**Comment by vedimuthan** [comment]
I didn't know what caused the issue. it seems it worked today and i got only one email. I am closing this issue. thanks for checking.
