### ISSUE TITLE
DAG run state not updated while DAG is paused

### ISSUE THREAD

**Issue by arbass22** [apache/airflow#15439]
**Apache Airflow version**:
2.0.0

**What happened**:

The state of a DAG run does not update while the DAG is paused.   The _tasks_ continue to run if the DAG run was kicked off before the DAG was paused and eventually finish and are marked correctly.  The DAG run state does not get updated and stays in Running state until the DAG is unpaused.

Screenshot:
![Screen Shot 2021-04-19 at 2 18 56 PM](https://user-images.githubusercontent.com/10891729/115284288-7b9c6200-a11a-11eb-98ab-5ce86c457a17.png)

**What you expected to happen**:
I feel like the more intuitive behavior would be to let the DAG run continue if it is paused, and to mark the DAG run state as completed the same way the tasks currently behave.

**How to reproduce it**:
It can be repoduced using the example DAG in the docs: https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html
You would kick off a DAG run, and then paused the DAG and see that even though the tasks finish, the DAG run is never marked as completed while the DAG is paused.

I have been able to reproduce this issue 100% of time.  It seems like logic to update the DAG run state simply does not execute while the DAG is paused.

**Anything else we need to know**:
Some background on my use case:
As part of our deployment, we use the Airflow rest API to pause a DAG and then use the api to check the DAG run state and wait until all dag runs are finished.  Because of this bug, any DAG run in progress when we paused the DAG will never be marked as completed.

**Comment by ashb** [comment]
>  I feel like the more intuitive behavior would be to let the DAG run continue if it is paused, and to mark the DAG run state as completed the same way the tasks currently behave.

I disagree, at least partially.

If the _currently_ running tasks finish the DAG, then the state should update, but new tasks should not be kicked off for a paused DAG.

**Comment by arbass22** [comment]
Yeah that makes sense to me.  The situation I really care about is updating the DAG state when tasks' state change, even if the DAG is paused.

**Comment by jhtimmins** [comment]
@arbass22 do you want to take this on? If so we'll target the next release with the fix.
