### ISSUE TITLE
Remote Logging: WasbTaskHandler wasb_read returns bytes instead of string

### ISSUE THREAD

**Issue by bobpace** [apache/airflow#15489]
**Apache Airflow version**:
2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): macOS Big Sur 11.2.1
- **Kernel** (e.g. `uname -a`): Darwin ftlmacwmd6t.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:
After configuring remote logging using wasb it works but the remote log output is returned as bytes instead of string and makes it difficult to read in the airflow UI. For example, the log output will look like b"line1\nline2\nline3\netc" and it will not split the lines on the \n.

I was able to work around this issue by including a custom task handler that inherits from WasbTaskHandler and overrides the `wasb_read` function and its usage of the underlying WasbHook `read_file` function to set encoding to "utf-8":
```
    def wasb_read(self, remote_log_location: str, return_error: bool = False):
        """
        Default WasbTaskHandler returns contents as bytes which doesn't look good in log display
        ie, b"text\nsome more text\n" and doesn't split the newlines
        This overrides the encoding to utf-8 so we get a string back
        """
        try:
            return self.hook.read_file(self.wasb_container, remote_log_location, encoding="utf-8")
        except AzureHttpError:
            msg = f'Could not read logs from {remote_log_location}'
            self.log.exception(msg)
            # return error if needed
            if return_error:
                return msg
```

**What you expected to happen**:
It would be convenient if the encoding was set to "utf-8" or otherwise allow for it to be passed in so that the remote logs don't display as one giant line that wraps.

**How to reproduce it**:
Use remote logging with WasbTaskHandler

**Anything else we need to know**:

**Comment by uranusjr** [comment]
It might not be a good idea to change `wasb_read()` to return a str, but changing the log line (in `WasbTaskHandler._read()`) to do `remote_log.decode("utf-8", errors="backslashreplace")` IMO.

Would you be interested in submitting a pull request for that?

**Comment by bobpace** [comment]
Ah ok I see what you mean, sure I'll take a shot at a PR this weekend.

**Comment by ephraimbuddy** [comment]
There's an issue on this that have been fixed, can you share the version of apache-airflow-providers-microsoft-azure you're using? If you're on a lower version please upgrade and try if you can reproduce it again

**Comment by bobpace** [comment]
was using:
apache-airflow-providers-microsoft-azure==1.1.0

now using:
apache-airflow-providers-microsoft-azure==1.3.0

confirmed that it works without issue after upgrading to latest version, thank you for your help!
