### ISSUE TITLE
webserver is not logging

### ISSUE THREAD

**Issue by wirshad00** [apache/airflow#15491]
Hi,

I am unable to capture the airflow webserver logs. The file (airflow-webserver.log and airflow-webserver.out) are empty under path ~/airflow. I tried to start the webserver and the scheduler using the commend below. I am able to login to UI and run DAG's.

airflow webserver -D
airflow scheduler -D

I really appreciate the help.

Regards,

Walid

**Comment by uranusjr** [comment]
`-D` puts the process in daemon mode so of course you’re not going to see logs in the terminal. Either remove `-D` or use the various log options to log to files. You can learn about those with `--help` or by reading the documentation.

**Comment by wirshad00** [comment]
Thank you @uranusjr for pointing the issue. I was able to figure it using --help
