### ISSUE TITLE
airflow dag sucess , but task is no status and not working

### ISSUE THREAD

**Issue by trollhe** [apache/airflow#15503]
hello,

   in airflow , dag statu is running ,but task is not running and no status,see after:

![image](https://user-images.githubusercontent.com/41068725/115868579-42902480-a46f-11eb-86f1-38371bb180b1.png)

   detail logs after:
dag logs:
![image](https://user-images.githubusercontent.com/41068725/115869053-e974c080-a46f-11eb-8442-e5994af5b74f.png)

one task logs:
![image](https://user-images.githubusercontent.com/41068725/115869120-03ae9e80-a470-11eb-8489-75c5e060c2b3.png)

![image](https://user-images.githubusercontent.com/41068725/115869444-7a4b9c00-a470-11eb-9a74-751f9ca94415.png)

  but are some dag and task is sucess:
![image](https://user-images.githubusercontent.com/41068725/115869514-918a8980-a470-11eb-9c87-d2bab6e0b434.png)

  pool settings:
![image](https://user-images.githubusercontent.com/41068725/115869550-9e0ee200-a470-11eb-9b03-2ab2d6ce26fb.png)

 airflow configs:
![image](https://user-images.githubusercontent.com/41068725/115869666-cac2f980-a470-11eb-8f3f-07ff004ffbe5.png)

![image](https://user-images.githubusercontent.com/41068725/115869725-e1695080-a470-11eb-8230-6a0831c53f5b.png)

no statu tasks see :
![image](https://user-images.githubusercontent.com/41068725/115877084-a15a9b80-a479-11eb-8602-79050158ef81.png)

click in ,see:
![image](https://user-images.githubusercontent.com/41068725/115877138-b0414e00-a479-11eb-9ea5-5e610270d99a.png)

but schedule server progress not is about progress:
![image](https://user-images.githubusercontent.com/41068725/115877357-eda5db80-a479-11eb-8b77-3fca8a210f21.png)

   please , how can to Troubleshooting?

**Comment by eladkal** [comment]
Please check against Airflow 2 if the issue still happens we need reproduce steps to recreate it.

**Comment by hancyhancy123** [comment]
Hi, I have run up with the same issue.And I wonder that if you have solve the problem.

**Comment by potiuk** [comment]
If there is anyone with similar issue, please create a new issue and describe version, logs and all the circumstances - enough reproducible case that somene can look at this and diagnose. Posting "I also have this problem" on closed issue, when it might be a completely different issue is cheap, but as most cheap solutions it gives you as much as much it costs.

Please take your time to report your issue properly and provide all the necessary information that could help anyone to diagnose it..

**Comment by ravindraittamalla** [comment]
if previous run of a task is failed, by default the next runs won't be queued. clear the failed task and rest of tasks will be triggered.
