### ISSUE TITLE
rich pinned to 9.2.0 in setup.cfg

### ISSUE THREAD

**Issue by yuqian90** [apache/airflow#15529]
This line is found in in `setup.cfg` which pins `rich` to 9.2.0. Is there a reason this is needed? The latest `rich` is already at 10.1.0. I briefly tested this version and see no issues.

What are the things we need to test before unpinning `rich` ?

**Comment by potiuk** [comment]
Just push a PR and tests will run automatically. If they pass, we can merge it.
