### ISSUE TITLE
Improve test coverage of task_command

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15524]
Task command has a few missing commands not tested: https://codecov.io/gh/apache/airflow/src/master/airflow/cli/commands/task_command.py (77%)

**Comment by vikramcse** [comment]
Hello @potiuk 
I would like to work on this issue

**Comment by potiuk** [comment]
Feel free :)

**Comment by vikramcse** [comment]
Raised a PR for improving test coverage of task_command.py file
https://github.com/apache/airflow/pull/15760
