### ISSUE TITLE
Improve test coverage of Kubernetes Executor

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15523]
The Kubernetes executor has surprisingly low test coverage: 64% 

https://codecov.io/gh/apache/airflow/src/master/airflow/executors/kubernetes_executor.py - looks like some of the "flush/end" code is not tested.

We might want to improve it.

**Comment by Dr-Denzy** [comment]
I will like to add tests for this as well @kaxil

**Comment by eladkal** [comment]
We are at 81%
https://app.codecov.io/gh/apache/airflow/blob/main/airflow/executors/kubernetes_executor.py
