### ISSUE TITLE
Improve test coverage of Kubernetes config_refresh 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15526]
Kuberentes refresh_config has untested method https://codecov.io/gh/apache/airflow/src/master/airflow/kubernetes/refresh_config.py 75%

We might want to improve that.

**Comment by gm7y8** [comment]
@potiuk  can i work on this?

**Comment by potiuk** [comment]
Feel free!

**Comment by Dr-Denzy** [comment]
Hey @gm7y8 how is the progress on putting up a PR for this issue?

**Comment by subkanthi** [comment]
can I have this assigned please
