### ISSUE TITLE
S3KeySensor wildcard fails to match valid unix wildcards

### ISSUE THREAD

**Issue by jackstrang** [apache/airflow#15538]
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: AWS MWAA
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: In a DAG, we implemented an S3KeySensor with a wildcard.  This was meant to match an S3 object whose name could include a variable digit.  Using an asterisk in our name, we could detect the object, but when instead we used [0-9] we could not.

**What you expected to happen**: S3KeySensor bucket_key should be interpretable as any valid Unix wildcard pattern, probably as defined here: https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm or something similar.

I looked into the source code and have tracked this to the `get_wildcard_key` function in `S3_hook`: https://airflow.apache.org/docs/apache-airflow/1.10.14/_modules/airflow/hooks/S3_hook.html.
This function works by iterating over many objects in the S3 bucket and checking if any matches the wildcard.  This checking is done with `fnmatch` that does support ranges.

The problem seems to be in a performance optimization.  Instead of looping over all objects, which could be expensive in many cases, the code tries to select a Prefix for which all files that could meet the wildcard would have this prefix.  This prefix is generated by splitting on the first character usage of `*` in the `wildcard_key`.  That is the issue.

It only splits on `*`, which means if `foo_[0-9].txt` is passed in as the `wildcard_key`, the prefix will still be evaluated as `foo_[0-9].txt` and only objects that begin with that string will be listed.  This would not catch an object named `foo_0`.

I believe the right fix to this would either be:
1. Drop the performance optimization of Prefix and list all objects in the bucket
2. Make sure to split on any special character when generating the prefix so that the prefix is accurate

**How to reproduce it**:  This should be reproduceable with any DAG in S3, by placing a file that should meet set off a wildcard sensor where the wild-card includes a range.  For example, the file `foo_1.txt` in bucket `my_bucket`, with an S3KeySensor where bucket_name='my_bucket', bucket_key='foo_[0-9].txt`, and wildcard_match=True

**Anything else we need to know**: This problem will occur every time

**Comment by john-jac** [comment]
I'm happy to take this one if it's still free

**Comment by potiuk** [comment]
feel free!
