### ISSUE TITLE
Airflow 1.10.15 : The CSRF session token is missing when i try to trigger a new dag

### ISSUE THREAD

**Issue by chakir-alaoui** [apache/airflow#15532]
**Apache Airflow version**: 1.10.15
https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.6.txt

**Kubernetes version**: 
  Client Version: v1.16.2
  Server Version: v1.14.8-docker-1

**Environment**: python 3.6.8 + celeryExecutor  + rbac set to false

- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64 

**What happened**:  I have upgraded from 1.10.12 to 1.10.15, when i trigger a dag i have the exception below 
![image](https://user-images.githubusercontent.com/31507537/116103616-0b5c8600-a6b0-11eb-9255-c193a705c772.png)

**What you expected to happen**: trigger a dag without exceptions
  

**How to reproduce it**: use airflow 1.10.15 and try to trigger an example dag example_bash_operator

**Anything else we need to know**: 

How often does this problem occur:  Every time i trigger a dag

Any relevant logs to include? Put them here in side a detail tag:
<details><summary>webserver.log</summary> [2021-04-26 15:03:06,611] {__init__.py:50} INFO - Using executor CeleryExecutor
[2021-04-26 15:03:06,612] {dagbag.py:417} INFO - Filling up the DagBag from /home/airflow/dags
175.62.58.93 - - [26/Apr/2021:15:03:10 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
175.62.58.93 - - [26/Apr/2021:15:03:11 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
175.62.58.93 - - [26/Apr/2021:15:03:15 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
175.62.58.93 - - [26/Apr/2021:15:03:16 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
[2021-04-26 15:03:17,401] {csrf.py:258} INFO - The CSRF session token is missing.
10.30.180.137 - - [26/Apr/2021:15:03:17 +0000] "POST /admin/airflow/trigger?dag_id=example_bash_operator&origin=https://xxxxxx/admin/ HTTP/1.1" 400 150 "https://xxxxxxxxxxxx/admin/airflow/trigger?dag_id=example_bash_operator&origin=https://xxxxxxxxxxxx/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
175.62.58.93 - - [26/Apr/2021:15:03:20 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
175.62.58.93 - - [26/Apr/2021:15:03:21 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+" </details>

**Comment by kaxil** [comment]
Are you running more than one Webserver? Try logging out and logging back in. And please use RBAC UI, we have deprecated the old Flask-Admin UI.

**Comment by chakir-alaoui** [comment]
Thank you Kaxil for your reply , i just tested these 2 scenarios :  
  -  rbac enabled + 2 instances of webserver :   KO ( CSRF SESSION TOKEN missing just after the authentification UI)
  - rbac enabled + 1 instance of webserver : OK

should we use just one instance of webserver for this version ?

**Comment by kaxil** [comment]
@chakir-alaoui When you use more than 1 Webservers, make sure `[webserver] secret_key` is set same across both of them.

If you don't set it by it will generate a random ones and since both webserver will have different keys, one of them will error.

**Comment by eladkal** [comment]
@kaxil is it the same issue as https://github.com/apache/airflow/issues/13357 ?

**Comment by chakir-alaoui** [comment]
thank you for your help, it's working now 👍

**Comment by xsqian** [comment]
Hi there, I installed airflow (airflow-1.3.0) with helm install on a Kubernetes cluster with ONLY ONE airflow-webserver, but got the same error message: `The CSRF session token is missing.` What could be the issue?
