### ISSUE TITLE
Airflow Dag Stuck in Running Status for Kubernetes Executor

### ISSUE THREAD

**Issue by BShraman** [apache/airflow#15542]
Hi Team,
   We are running into an issue after upgrading to airflow 2.0.2. When running simple jobs dags are stuck in Running status but the Scheduler Pod logs shows that task are succeeded . 

Environment: 
Airflow : 2.0.2
Python : 3.6.8
kubernetes : 11.0.0
Docker Image Build : RUN pip3 install apache-airflow[async,google,statsd,cncf.kubernetes]=="${AIRFLOW_VERSION}"

Issue Reproduce Steps : 
-- Update airflow.cfg 
[kubernetes]
pod_template_file = /home/airflow/airflow/dags_in_image_template.yaml
worker_container_repository = XXXXX
worker_container_tag = XXXXX
namespace = XXXXX
delete_worker_pods = True
delete_worker_pods_on_failure = False
worker_pods_creation_batch_size = 1

So far i have tried couple of different option. 
Option I:
            1. Place dags_in_image_template file into pod_template_file path. 
            2. Run hello_world Dags.
            3. Test results are attached in 15542.docx
            LogFile: SchedulerPod.log
            
Option II:  Using Option I, POD were not deleted from K8 cluster and was in running status (15542.docx) with current configuration . I have to modify pod_generator and kubernetes_executor modules to delete the pod from K8 cluster. 
          1. Place dags_in_image_template file into pod_template_file path. 
          2. Place pod_generator.py and kubernetes_executor.py module in respective place. 
          3. Run hello_world Dags. 
           LogFile : SchedulerPodLogWithDeletePod.log
           
[SchedulerPod.log](https://github.com/apache/airflow/files/6381286/SchedulerPod.log)
[SchedulerPodLogWithDeletePod.log](https://github.com/apache/airflow/files/6381287/SchedulerPodLogWithDeletePod.log)

[dags_in_image_template.txt](https://github.com/apache/airflow/files/6381464/dags_in_image_template.txt)

[15542.docx](https://github.com/apache/airflow/files/6381296/15542.docx)

[hello_world.txt](https://github.com/apache/airflow/files/6381301/hello_world.txt)

[pod_generator.txt](https://github.com/apache/airflow/files/6381304/pod_generator.txt)
[kubernetes_executor.txt](https://github.com/apache/airflow/files/6381312/kubernetes_executor.txt)

**Comment by donotpush** [comment]
@kaxil I wonder if #15542 is already present in release 2.1.3, I tried to find a commit or PR but I did not succeed. Can you help me to find the commit/PR?
