### ISSUE TITLE
Bump hadolint to v2.3.0

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#15544]
We are currently using some old version of Hadolint. 
https://github.com/apache/airflow/blob/4b031d39e12110f337151cda6693e2541bf71c2c/scripts/ci/static_checks/lint_dockerfile.sh#L22
I think it's worth updating to better validate our Docker files. It shouldn't be very time-consuming, but we'll have to fix some warnings. I am most interested in this rule that will optimize our images better.
> DL3059: Multiple consecutive RUN instructions (https://github.com/hadolint/hadolint/pull/591)

**Comment by potiuk** [comment]
Agree. Would be nice. And it should not be hard. A lot of the work for optimising RUN (and ENV) has been just implemented in #15438 - so there should be just few optimizations left I think.
