### ISSUE TITLE
airflow dag can't be deleted cleanly

### ISSUE THREAD

**Issue by atm1992** [apache/airflow#15563]
**Apache Airflow version**: 1.10.4

**What happened**: Firstly, I delete the dag file in disk, then click the delete button in airflow web ui. I can see the relevant  record has been deleted from airflow metadata database(MySQL) , but a  few seconds later, a  new record was written in the dag/dag_run/task_instance table.  

**What you expected to happen**: After click the delete button in airflow web ui, no new records should be generated.

**Anything else we need to know**: I guess before i click the delete button, the scheduler_job.DagFileProcessor._run_file_processor had read the dag file from disk. After the delete_dag function has delete database records, the DagFileProcessor regenerated database records.

**Comment by kaxil** [comment]
Are you sure you deleted the DAG File, as your statements contradict. In **What Happened** you say that you removed the dag file, but in **Anything else we need to know** you say the schedule read the dag file from disk.
