### ISSUE TITLE
sqlalchemy connection string with @ in username does not work anymore

### ISSUE THREAD

**Issue by ericdevries** [apache/airflow#15575]
**Apache Airflow version**: 2.0.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.17.9

**Environment**:

- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

When starting a pod, the error message says 

```
/entrypoint: line 109: BACKEND: unbound variable
```

We use an azure-hosted postgres database for the backend, which MUST contain a @ in the username for it to work. The previous versions of airflow handled this just fine. But since the changes in this ticket: https://github.com/apache/airflow/issues/14104 it no longer works because the regex has been changed and now does not accept a @ character in the username.

**What you expected to happen**:

I expect it to accept a @ in the username

**How to reproduce it**:
Start airflow with a connection string like this:

```
postgresql://airflow@env:password@env.postgres.database.azure.com:5432/airflow
```

**Anything else we need to know**:

**Comment by potiuk** [comment]
Using @ in user name is not allowed by specification see for example here: https://stackoverflow.com/questions/10050877/url-username-with . If the user contains @ you MUST URL-encode it (replace with %40)

**Comment by potiuk** [comment]
For details /specification see here: https://tools.ietf.org/html/rfc3986 
* '@' is part of gen-delims (type of reserved characters)
* Userinfo is defined like this: `userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )`  - which means that gen-delims cannot be used, they must b pct-encoded

**Comment by ericdevries** [comment]
Ok, encoding it works, thanks for the advice. I will close this now
