### ISSUE TITLE
Qubole Hook Does Not Support 'include_headers'

### ISSUE THREAD

**Issue by levyitay** [apache/airflow#15598]
**Description**

Qubole Hook and Operator do not support `include_header` param for getting results with headers
Add Support for `include_header` get_results(... arguments=[True])
**Use case / motivation**

It's very hard to work with CSV results from db without headers. 
This is super important when using Qubole's databases.

**Are you willing to submit a PR?**

Not sure yet, I can give it a try

**Related Issues**

**Comment by eladkal** [comment]
@levyitay assigned to you

**Comment by levyitay** [comment]
@eladkal Can you take a look and push it if possible?
