### ISSUE TITLE
BigQueryCreateExternalTableOperator table_resource parameter is impossible to use

### ISSUE THREAD

**Issue by dougpm** [apache/airflow#15604]
**Apache Airflow version**: 1.10.14

**What happened**: 

I specified the table_resource parameter in BigQueryCreateExternalTableOperator.

**What you expected to happen**:

Expected operator to ignore all other table related parameters and execute normally.

The 'table_resource' parameter can't be specified alongside 'destination_project_dataset_table', which is needed. 
destination_project_dataset_table shouldn't be in the 'kwargs_passed' list. Also other atributes in said list have default values, which is also a bug.

**Comment by bmbejcek** [comment]
Any updates on this? Currently facing this issue.

**Comment by potiuk** [comment]
This is already fixed in 5.1.0 version of Airflow provider. You can upgrade the provider to that version and use it. Also in case you use an earlier version of the provider, you can set those conflicting parameters to None as a workaround.

**Comment by potiuk** [comment]
Fixed in here: https://github.com/apache/airflow/pull/17900
