### ISSUE TITLE
airflow dag support multiple versions

### ISSUE THREAD

**Issue by luoyuliuyin** [apache/airflow#15608]
**Description**

Suppose I created a dag yesterday, and Its structure is: task_a >> task_b
Today I updated the structure of dag to: task_c >> task_d >> task_e

I need to know what the dag looked like yesterday, and I need to find yesterday's log from ui.

**Use case / motivation**

**Are you willing to submit a PR?**
yes

**Related Issues**

**Comment by eladkal** [comment]
We have [AIP-36 DAG Versioning](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning) currently in draft

**Comment by luoyuliuyin** [comment]
I want to know how this AIP is progressing and in which version we will be able to use this new feature

**Comment by luoyuliuyin** [comment]
> We have [AIP-36 DAG Versioning](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning) currently in draft

I want to know how this AIP is progressing and in which version we will be able to use this new feature

**Comment by eladkal** [comment]
> I want to know how this AIP is progressing and in which version we will be able to use this new feature

This is currently a draft proposal. You are welcome to comment to the suggested approch on the AIP page.

**Comment by eladkal** [comment]
closing as there is AIP for this
