### ISSUE TITLE
Add documentation on what each parameter to a `sla_miss_callback` callable is

### ISSUE THREAD

**Issue by CrossNox** [apache/airflow#15641]
I couldn't find any official documentation specifying what each parameter to a `sla_miss_callback` callable are. This would be a great addition to know how to properly format the messages sent.

**Comment by vikramkoka** [comment]
Thank you for reporting this. 
Here is the high level description for the SLA callback in the docs http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/concepts/tasks.html#slas

Would you like to create a PR to add this?

**Comment by alex-astronomer** [comment]
I'd love to create a PR for this.  This will be my first contribution to Airflow.  I searched for "good first issue" and "documentation" labels for my first try at this.  Would this Issue be a good place to start making contributions?

**Comment by potiuk** [comment]
Sure. Feel free!
