### ISSUE TITLE
Can't refresh DAGs when more than one Airflow UI is open

### ISSUE THREAD

**Issue by jcpalmer108** [apache/airflow#15658]
**Apache Airflow version**:
Apache Airflow Version 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: v1.20.4
Server Version: v1.15.12-eks-31566f

**Environment**:
We see the issue in both our dev and prod environments. 

- **Cloud provider or hardware configuration**:  AWS EKS
- **OS** (e.g. from /etc/os-release):  Python36
- **Kernel** (e.g. `uname -a`): ubuntu
- **Install tools**:  None
- **Others**: 1.10.10 version of airflow

**What happened**:
When I am navigating from one cluster to another to refresh the DAGs, we see the 'Bad Requst: The CSRF Token is Missing' error. We saw there were issues with the Flask Builder for a similar issue, so we deprecated our Flask-AppBuilder to v2.3.2 but it doesn't solve the issue. 

Error image: 
<img width="297" alt="Screen Shot 2021-05-04 at 12 27 28 PM" src="https://user-images.githubusercontent.com/61334397/117058972-25abea80-acd4-11eb-9d24-35d920b8c6fb.png">

**What you expected to happen**:
I expect to be able to refresh the DAGs of the cluster I'm in, despite however many Clusters I have open in my browser. 

**How to reproduce it**:
1. Open cluster A's Airflow UI in one tab
2. Open cluster B's UI in another (unrelated) tab
3. Open dag in cluster A
4. Open dag in cluster B
5. In cluster A's dag click refresh - it should refresh
6. In cluster B's dag click refresh - `Bad Request: CSRF Token Missing` Error appears

Video of Bug Reproduced:
https://user-images.githubusercontent.com/61334397/117060761-26458080-acd6-11eb-93ef-b0bbc1997889.mov

**Anything else we need to know**:
Happens every time in both of our prod and dev environments.

**Comment by jedcunningham** [comment]
Related to #15539, which also has a way to resolve it with the RBAC UI: https://github.com/apache/airflow/issues/15539#issuecomment-827489265

**Comment by vshabarish** [comment]
hey, @jedcunningham  we want it fixed in FAB UI, not on RBAC UI. Due to some internal concerns, we are not opting for the rbac ui within our team. we are preparing the 2.0.1 in coming sprints. we want this issue to be fixed in our current environments

**Comment by jcpalmer108** [comment]
@jedcunningham ditto what shabarish said! He's on my team and we're working on the same product.

**Comment by jedcunningham** [comment]
1.10.x reaches EOL in a couple weeks.

You can try patching your [`www/app.py`](https://github.com/apache/airflow/blob/1.10.10/airflow/www/app.py#L61-L63) to set [SESSION_COOKIE_PATH](https://flask.palletsprojects.com/en/1.1.x/config/#SESSION_COOKIE_PATH).

**Comment by jedcunningham** [comment]
@jcpalmer108 , @vshabarish did setting `SESSION_COOKIE_PATH` work out?
