### ISSUE TITLE
Docs: check_migrations more verbose documentation

### ISSUE THREAD

**Issue by andormarkus** [apache/airflow#15650]
**Description**
The documentation and the error message of the [check-migrations](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#check-migrations) / `def check_migrations` could be more verbose.  This check can fail if the underlying database was never initialised.

**Use case / motivation**

We are deploying our airflow helm chart with terraform helm provider. This provider has a [bug](https://github.com/hashicorp/terraform-provider-helm/issues/683) with helm hook. If airflow would give us a bit more verbose error message why could the `check-migrations` fail, we would find the underlying error/bug much sooner.

**Are you willing to submit a PR?**
Yes

**Comment by vikramkoka** [comment]
@kaxil Just tagging you since you have been working on the Airflow helm chart
