### ISSUE TITLE
Airflow 1.10.12 - Scheduler performance issues due to database connections

### ISSUE THREAD

**Issue by milletstephane** [apache/airflow#15654]
**Apache Airflow version**: 1.10.12
** Postgres version**: 9.6
** Python version**: 3.6.3
** SQLAlchemy version**:  1.3.20

**Environment**:

- **OS** (e.g. from /etc/os-release): Redhat 7
- **Kernel** (e.g. `uname -a`): 3.10.0-327.el7.x86_64

**What happened**:

Our team is running Airflow with Celery Executor inside a local cluster

We implemented a Dag with around 800 tasks, and each task has an average of 4 dependencies.
The dag is also configured with a max_active_runs of 4.

In airflow configuration we set the following parameters:
 - [core]
    parallelism = 32
    dag_concurrency = 16
 - [celery] 
    worker_concurency = 16

When executing this dag, its associated scheduler runtime is around 100s. 
So in other words it takes 100 seconds to launch 16 tasks. 

**What you expected to happen**:

I would have expected the scheduler to be faster. 

**How to reproduce it**:

Create a dag with a large amount of task with many task dependencies

**Anything else we need to know**:

By setting a few traces inside airflow code I identified that most of the time consumption was linked to the function get_failed_dep_statuses() inside the file airflow/models/taskinstance.py

```
    @provide_session
    def get_failed_dep_statuses(self, dep_context=None, session=None):
        """Get failed Dependencies"""
        dep_context = dep_context or DepContext()
        for dep in dep_context.deps | self.task.deps:
            for dep_status in dep.get_dep_statuses(self, session, dep_context):

                self.log.debug(
                    "%s dependency '%s' PASSED: %s, %s",
                    self,
                    dep_status.dep_name,
                    dep_status.passed,
                    dep_status.reason,
                )

                if not dep_status.passed:
                    yield dep_status
```

During a single call of this function, several connections were made to the database instead of the expected single one. 

By using a yield in this function we create an iterator, and the problem is that in python3 iterator element are computed on call, thus generating a large number of connections when a database is involved.

By replacing the yield with a list comprehension, we were able to divide by two the duration of the runtime:

```
    @provide_session
    def get_failed_dep_statuses(self, dep_context=None, session=None):
        """Get failed Dependencies"""
        
        dep_context = dep_context or DepContext()
        
        dep_status_array = [ dep_status for dep in dep_context.deps | self.task.deps 
                                        for dep_status in dep.get_dep_statuses(self, session, dep_context)
                                        if not dep_status.passed ]

        return dep_status_array
```

By removing the yield in the get_dep_statuses function, I think that we could further decrease the runtime duration.

Except if there is a reason that I'm unaware of, "yield" should be avoided in function used to interact with databases.
If my analysis is incorrect or if I missed some useful configuration please let me know.

**Comment by ashb** [comment]
Upgrade/try out Airflow 2.0 (.2) and I think you will be pleasantly surprised at how it performs -- we did _a lot_ of work on the scheduler for the 2.0 release

**Comment by milletstephane** [comment]
Before anyone try it. It seems that I messed up somewhere when getting runtime duration with the modified get_failed_dep_statuses function. 
In the end it looks like it has no effect

**Comment by milletstephane** [comment]
If like me you are stuck with an old version of airflow, here is an update on the problem.

My assumption that the problem was linked to the time taken to establish a connection with the database was not correct. 

And it seems that rather than a bug, this behaviour is a choice. The scheduler is optimized for a high reactivity with DAG containing few tasks. The drawback is that if you build a single DAG with hundreds or thousands of  task then performnaces will be quite awful ...

This behaviour is induced in the code of the file "jobs/scheduler_job.py", specifically in the function _process_task_instances and there is even a comment indicating the slow loop: 

```
        for run in active_dag_runs:
            self.log.debug("Examining active DAG run: %s", run)
            tis = run.get_task_instances(state=SCHEDULEABLE_STATES)

            # this loop is quite slow as it uses are_dependencies_met for
            # every task (in ti.is_runnable). This is also called in
            # update_state above which has already checked these tasks
            for ti in tis:
                task = dag.get_task(ti.task_id)

                # fixme: ti.task is transient but needs to be set
                ti.task = task

                if ti.are_dependencies_met(
                        dep_context=DepContext(flag_upstream_failed=True),
                        session=session):
                    self.log.debug('Queuing task: %s', ti)
                    task_instances_list.append(ti.key)
```

By running it and setting a few traces, we identified that the most time consumming function was "ensure_finished_tasks" from  the class DepContext. 
This function runtime isaround 20ms on our platform (may vary depending on the number of tasks or database). And it is called 800 times, 4 times as we decided to launch 4 dag runs sequentially.

20 ms * 800 * 4 = 64 seconds

And looking at the function we see that if the list of finished tasks is already set, the database won't be queried. So the solution was quite simple, retrieve the list of finished tasks at the beginning at each dagrun loop then use this result inside each loop on tasks element.
I ended with the following code:

```
        for run in active_dag_runs:
            self.log.debug("Examining active DAG run: %s", run)
            tis = run.get_task_instances(state=SCHEDULEABLE_STATES)

            # here we get the finished tasks for each execution date in the taskinstances
            dep_con = DepContext(flag_upstream_failed=True)
            ti_exec_date_array = list(set([ ti.execution_date for ti in tis ]))
            res = {}
            for exec_date in ti_exec_date_array:

                finished_tasks = list(dep_con.ensure_finished_tasks(
                    dag, exec_date, session
                    ))

                res[exec_date] = finished_tasks

            # this loop is quite slow as it uses are_dependencies_met for
            # every task (in ti.is_runnable). This is also called in
            # update_state above which has already checked these tasks
            for ti in tis:
                task = dag.get_task(ti.task_id)

                # fixme: ti.task is transient but needs to be set
                ti.task = task

                dep_con = DepContext(flag_upstream_failed=True)

                # the finished tasks are set with the result of the upper loop call
                dep_con.finished_tasks = res[ ti.execution_date ]

                if ti.are_dependencies_met(
                        dep_context=dep_con,
                        session=session):
                    self.log.debug('Queuing task: %s', ti)
                    task_instances_list.append(ti.key)
```

As we don't know if the  dep_context is modified during the execution of the function "are_dependencies_met", it was decided to get the list of finished tasks and apply it on dep_context object newly created.  

When setting the finished task in the dep_con object, we could also use a deepcopy to ensure that the finished_tasks won't be modified. (but why would they ?)

Conclusion:

With this dirty trick the DAG runtime is now below 10sec which is not perfect but quite correct. 
I hope this helps
