### ISSUE TITLE
Some Entries in the Job view do not have Dag Ids

### ISSUE THREAD

**Issue by r39132** [apache/airflow#157]
Here are the Dags that I have!
<img width="1081" alt="screenshot 2015-07-20 11 36 11" src="https://cloud.githubusercontent.com/assets/581734/8783906/b384a354-2ed3-11e5-83ef-d50a85829437.png">

However, I see some running in the job view that do not have dag ids!
<img width="1074" alt="screenshot 2015-07-20 11 36 00" src="https://cloud.githubusercontent.com/assets/581734/8783909/b5e5cc4a-2ed3-11e5-94b4-97b95ec03aed.png">

I am running code synced via Git from master -- last sycned on Friday, July 17th, 5pm PST.

**Comment by mistercrunch** [comment]
The jobs are used for anything that derives BaseJob (SchedulerJob, BackfillJob, LocalTaskJob, ...).

I think when you CTRL-C kill the scheduler, it may leave a "RUNNING" entry in the DB.

I'm not sure what job id 14 is about...

**Comment by r39132** [comment]
I have been 'CTRL-C'ing the scheduler very liberally -- I should SIGTERM it, assuming that the processes catch that signal and terminate cleanly, including cleaning up the DB of any running jobs on those processes? Asked another way, what is the correct way to terminate the scheduler and or backfill jobs so that they do not leave tasks in the running state forever?

In my "monit" automation, I am SIGTERM'ing both the webserver and scheduler processes, so assume that is the clean way to shutdown.

**Comment by r39132** [comment]
We are using the LocalScheduler, so I am guessing those tasks are running as LocalTaskJobs. This turned out to be one of our model building jobs.

**Comment by r39132** [comment]
But, to my original question, isn't dag_id required? Why would it be empty? I guess I'm asking whether this is a bug. In my case, I have not subclassed BaseJob, so the fact that the job view is not displaying dag_ids seems like a bug.

**Comment by mistercrunch** [comment]
It's expected that SchedulerJob instances would have an empty `dag_id` column.
