### ISSUE TITLE
Python dictionary contains duplicate keys

### ISSUE THREAD

**Issue by jbampton** [apache/airflow#15732]
`airflow/providers/apache/hive/hooks/hive.py`

"It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary)"

https://docs.python.org/3/tutorial/datastructures.html#dictionaries

<img width="482" alt="Screen Shot 2021-05-08 at 6 03 31 pm" src="https://user-images.githubusercontent.com/418747/117531959-726f2880-b028-11eb-91b1-a394e0cb65a3.png">

<img width="691" alt="Screen Shot 2021-05-08 at 6 03 48 pm" src="https://user-images.githubusercontent.com/418747/117531966-7a2ecd00-b028-11eb-8bf7-33837c86eec9.png">

**Comment by potiuk** [comment]
There is no need to open issue for that. Can you please just open PR fixing it?

**Comment by potiuk** [comment]
And just one more comment - so that you are aware of the "ettqute" and usual  approach.

Tthis is a comment which has no impact on the code and can be fixed very easily. There is no reason to pollute the issue space with an issue for that. 

Please try not to create such issues as it drags our attention from more important problems. 

I close the issue now.,

**Comment by potiuk** [comment]
Happy to guide you. Just remove one of the duplicated keys with it's value. It's a comment so you will not destroy anything.

**Comment by potiuk** [comment]
BTW. Maybe it's time to start learning Python. I think your comments will be much more valuable if you learn Python and will be able to assess how important/easy to fix the issues are.

**Comment by jbampton** [comment]
What about the two values in the dictionary ?  They are different. 
If we delete one key we also lose a value

**Comment by potiuk** [comment]
Does'nt matter. It's a comment. Doctest (but we are not using doctests). https://docs.python.org/3/library/doctest.html
