### ISSUE TITLE
Install Airflow cloud providers as extra [AWS] [Azure] [Google]

### ISSUE THREAD

**Issue by n3onUser** [apache/airflow#15747]
**Description**

It will be better to install airflow with pip base pip requirements and cloud platform as extra dependencies.

**Use case / motivation**

I would like to install Airflow without other Cloud Service Provider if i choose Azure or Google or AWS.
It will help to have less security flaws surface, less dependencies, less dependencies problems,...

**Are you willing to submit a PR?**

As it seems that you install Airflow through pip with all cloud providers dependencies, i wonder if you might change your mind. I don't think you change mind with PR but i can be wrong here.
It will normally conduct to less dependencies, less security vulnerabilities for specific cloud provider usages, ...

**Related Issues**

It's not an issue but a feature request.

**Comment by potiuk** [comment]
It's already possible. Airflow 2.0 has this built-in.

**Comment by potiuk** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html#providers-extras

**Comment by n3onUser** [comment]
sorry for the inconvenience, feature already exists !
