### ISSUE TITLE
flask error:  ValueError: instance() only accepts datetime objects.

### ISSUE THREAD

**Issue by xsu-git** [apache/airflow#15759]
**Apache Airflow version**: 

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: 2.0.1

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: Python 3.7.3

**What happened**: When I click task instance  from the home page and jump to the page, I get an error prompt.
Traceback (most recent call last):
    File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 801, in get_previous_start_date
    return prev_ti and pendulum.instance(prev_ti.start_date)
  File "/usr/local/lib/python3.7/dist-packages/pendulum/__init__.py", line 174, in instance
    raise ValueError("instance() only accepts datetime objects.")
ValueError: instance() only accepts datetime objects.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by SamWheating** [comment]
Fixed in https://github.com/apache/airflow/pull/14416
