### ISSUE TITLE
clear tasks is failing

### ISSUE THREAD

**Issue by maryampashmi** [apache/airflow#15775]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by jedcunningham** [comment]
Hi @maryampashmi, can you provide some more details on the issue you are facing?

**Comment by maryampashmi** [comment]
Hi, this is happening when I am trying to clear tasks from UI. I select all the tasks and I push the clear button, and I am getting an error. So doesn't clear the tasks, when you select all.

**Comment by ephraimbuddy** [comment]
Please @maryampashmi can you provide steps to reproduce and information such as the airflow version and executor you are using plus the log if any. Thanks

**Comment by maryampashmi** [comment]
airflow: 2.0.0

errro:

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.8
Airflow version: 2.0.2
Node: airflow-web-68c7bc54cc-jj8gp
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.

steps:
Brows/taskinstance/select all/ action:clear

**Comment by uranusjr** [comment]
There should be a reb box in the web UI that says something like

> Failed to clear task instances: [blah blah blah]

What does that message say? (The *blah blah blah* part.)

**Comment by ephraimbuddy** [comment]
@maryampashmi can you try in 2.0.2. Though you said 2.0.0, the error says 2.0.2, and I couldn't reproduce in 2.0.2

**Comment by maryampashmi** [comment]
@ephraimbuddy sorry , misspelling. it is V2.0.2.

**Comment by maryampashmi** [comment]
@ephraimbuddy 
I have the same issue.

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.8
Airflow version: 2.0.2
Node: airflow-web-5b784dff49-lw4q5
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.

<img width="1370" alt="Screenshot 2021-05-26 at 09 07 12" src="https://user-images.githubusercontent.com/6945288/119617136-c7b98100-be01-11eb-9148-5d22cd0ca67a.png">
