### ISSUE TITLE
[SambaHook] Can not extract domain from the username

### ISSUE THREAD

**Issue by edwinkong** [apache/airflow#15773]
**Apache Airflow version**:
2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: docker-compose + custom built docker image

**What happened**:

The `airflow.providers.samba.hooks.samba.SambaHook` does not accept the `domain` argument and is automatically defaults to the server ip address by upstream `pysmbclient`.
If the DOMAIN/USERNAME format was supplied, it would fail with `NT_STATUS_BAD_NETWORK_NAME` error. If only the USERNAME was supplied, then the login would fail with `NT_STATUS_LOGON_FAILURE` error.

**What you expected to happen**:
The domain should be extracted from the username if the user supplied the `SambaHook.conn.login` in the DOMAIN/USERNAME format.

**How to reproduce it**:
Just connect to a samba drive with domain authentication with `SambaHook`

**Comment by edwinkong** [comment]
I am sorry for not checking the upstream before opening an issue here. The upstream project `pysmbclient` was last updated at 9 years ago so the project is very likely to be obsolete. The `NT_STATUS_BAD_NETWORK_NAME` error was raised due to the faulty `subprocess` call
```
smbclient [SHARE] -I [IP] -A [AUTH_FILE] -c ls "[PATH]"
```
the double quote doesn't include the `ls` so it fails.

I would create my samba hook myself. Moreover, the `SambaHook` can not even list the directory, so probably some deprecation warning should be displayed when installing the package.

**Comment by eladkal** [comment]
We have open task to move to a maintained library https://github.com/apache/airflow/issues/14054 handled by @marcosmarxm
