### ISSUE TITLE
google provider requires leveldb installed in system

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#15770]
google provider now requires plyvel, which is used by leveldb hook.

to install plyvel, the user needs leveldb headers installed in the system, otherwise it will fail:

```
  plyvel/_plyvel.cpp:632:10: fatal error: 'leveldb/db.h' file not found
  #include "leveldb/db.h"
           ^~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for plyvel
```

the average GCP user may not use leveldb and it seems a little burdernsome to require its installation just to use GCP hooks, when most of them don't need this library.

perhaps there is a way to make this dependency optional?

or perhaps is there a way to install only certain components of a provider?

**update**

after looking more closely, i see that levelDB isn't a GCP service

it seems to me levelDB might belong as a distinct provider, e.g. `google-gcp` vs `google-level` like there is currently with apache and microsoft?  @potiuk any thoughts?

cc: @mik-laj 
related: https://github.com/apache/airflow/pull/14105

**Comment by uranusjr** [comment]
Doesn’t `plyvel` publish manylinux wheels and does not require compilation on most system?

**Comment by uranusjr** [comment]
But is macOS a supported production system? I’ve thought it’s only supported as a development platform…

Either way, it’s a good idea to split plyvel out anyway. Not every Linux is manylinux and there might be some people having problems with this e.g. on Alpine.

**Comment by potiuk** [comment]
It's mostly for development convenience. Plyvel is really such a `niche` thing that it's worth making it optional if only for the convenience of developers.

**Comment by potiuk** [comment]
I hit the same problem on linux today. When installing python 3.6 version of airflow for whatever reason plyvel failed to compile :(

**Comment by potiuk** [comment]
We SHOULD do it.

**Comment by dstandish** [comment]
I may not be able to get to it this weekend ... Traveling... but will let you know

**Comment by javatarz** [comment]
I'd be happy to. Incoming PR!

**Comment by rodrigo-fss** [comment]
Hello guys
any updates? I'm still struggling with the leveldb requirement to install the google provider and I can see that it wasn't split apart yet. Do you have any recommendations?

```
plyvel/_plyvel.cpp:703:10: fatal error: leveldb/db.h: No such file or directory
#14 3.011         703 | #include "leveldb/db.h"
```

Thanks!

**Comment by uranusjr** [comment]
You would probably have better luck reaching out to the plyvel maintainers. https://github.com/wbolster/plyvel

**Comment by dstandish** [comment]
@rodrigo-fss pretty sure that leveldb was made optional in google provider.  You might try installing a more recent version of the provider.  Which one did you try to install?

**Comment by potiuk** [comment]
Yeah. As mentioned in #15933 the right solution to your problem is to upgrade to Airflow 2.1+.
