### ISSUE TITLE
Auto-refresh of logs.

### ISSUE THREAD

**Issue by fob-cesar** [apache/airflow#15783]
**Description**

Auto-refresh of logs.

**Use case / motivation**

Similar process that is already implemented in the Graph View, have the logs to auto-refresh so it's easier to keep track of the different processes in the UI.

Thank you in advance!

**Comment by bbovenzi** [comment]
Good idea. Let me look into it.

**Comment by ashb** [comment]
I think this already exists, at least for _some_ logging backends -- ElasticSearch for instance.

**Comment by rsg17** [comment]
Hi - I would like to contribute to this. I am new to airflow.. are there any pointers you could share to help me get started?
