### ISSUE TITLE
High volume of API requests with AWS Secrets Manager backend

### ISSUE THREAD

**Issue by john-jac** [apache/airflow#15780]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

n/a

**Environment**:

- **Cloud provider or hardware configuration**: MWAA
- **OS** (e.g. from /etc/os-release): Amazon Linux
- **Kernel** (e.g. `uname -a`): x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

When using AWS Secrets Manager backend there is a high volume of API request from Airflow to the secrets backend, regardless of whether DAGs are running or not

**What you expected to happen**:

Traffic to secrets backend should be limited to what's needed

**How to reproduce it**:
https://airflow.apache.org/docs/apache-airflow/1.10.12/howto/use-alternative-secrets-backend.html?highlight=backend#aws-secrets-manager-backend

**Anything else we need to know**:

n/a

**Comment by kaxil** [comment]
Also please test it with 2.x -- Only critical fixes would be done on 1.10.x and that too will end next month.

https://github.com/apache/airflow/blob/master/dev/PROJECT_GUIDELINES.md#support-for-airflow-110x-releases
https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#support-for-airflow-1-10-x-releases
