### ISSUE TITLE
2.1 Airflow UI ( Tree view/Calender View )

### ISSUE THREAD

**Issue by himabindu07** [apache/airflow#15830]
On Airflow UI, not able to see tree view/calender view, continuously refreshing the page. Facing the problem in platform and local. 
**Airflow version:** 2.1.0
**What happened:**
When I click on the Tree view/calender view, I should see the task in the tree view, but the page is refreshing all the time. 
**What you expected to happen:**
When I click on the Tree view should be able to see the tasks in the tree view

<img width="1098" alt="Screen Shot 2021-05-13 at 1 31 55 PM" src="https://user-images.githubusercontent.com/47584863/118193832-360f4400-b3fd-11eb-88db-412c0b4b891b.png">

**Comment by bbovenzi** [comment]
I can replicate on the docker image, but not on breeze.  In docker, it is unable to  `tree.js` and `calendar.js`. @ashb I wonder if something like `./airflow/www/compile_assets.sh` didn't run correctly?

**Comment by potiuk** [comment]
Which image are using/building ? Is it the master one ?

**Comment by potiuk** [comment]
FYI: Just tried it with latest master docker image and it works:

* `docker pull apache/airflow:master-python3.6`
* `docker run -it -e _AIRFLOW_WWW_USER_CREATE="true" -e _AIRFLOW_WWW_USER_PASSWORD="admin" -e _AIRFLOW_DB_UPGRADE="true" -e AIRFLOW__CORE__LOAD_EXAMPLES=True -it -p 8080:8080 apache/airflow:master-python3.6 bash`
* `aiflow scheduler` (wait a moment to populate example dags)
* `airflow webserver`

![Screenshot from 2021-05-14 06-55-06](https://user-images.githubusercontent.com/595491/118223356-65679480-b481-11eb-86bd-6017283391bc.png)

**Comment by himabindu07** [comment]
> Which image are using/building ? Is it the master one ?

Image:2.1.0-buster-onbuild-37485
Yes, On master.

**Comment by potiuk** [comment]
Ah. That's the astronomer image :). The official airflow one does not seem to have the problem

**Comment by ashb** [comment]
Not an issue on apache/airflow
