### ISSUE TITLE
load module cost too much time when parse dagbag in DagBag#process_file

### ISSUE THREAD

**Issue by ZhendongBai** [apache/airflow#15833]
the airflow scheduler load module cost too much time in method `airflow.models.dagbag.DagBag#process_file` 
Airflow version: 1.10.4
# What happened:
1. as we known , `imp.load_source(mod_name, filepath)` in airflow.models.dagbag.DagBag#process_file is a time cost operation,sometimes it may cost more than 1 minute, is where any better way to load module?
2. and  I use the version 1.10.4, use`imp.load_source(mod_name, filepath)` to load module, and the version 2.x , use `importlib` to load module, so I want to ask a quastion - `importlib is more efficent than imp` ?

**Comment by ashb** [comment]
No, `importlib` and `imp` use roughly the same code under the hood.

The "expensive" part is not the method used to load the module, but what ever your module is doing.

If it is taking 1 minute to load your DAG file, then I suggest moving imports or code execution out of the top level of the module.

**Comment by johnnyprimary** [comment]
@ashb  thank you more than I can see, according my log , I make sure the dag py file import cost a lot of time, thx very much.
