### ISSUE TITLE
Add ability to edit dag_run conf when re-running tasks

### ISSUE THREAD

**Issue by veerendranathT** [apache/airflow#15887]
not able to edit conf section while re-run. Please find the below snap for the same.
![image](https://user-images.githubusercontent.com/46118531/118464772-d4ade480-b71e-11eb-8871-d831013d4da0.png)

**Comment by jakobkolb** [comment]
I have the same problem when triggering DAGs via CLI (which I use for integration testing during development). I would like to pass the dag a clean database via the `conf` to operate on but can't since the `conf` object is persisted between runs and cannot be reset afaik.
