### ISSUE TITLE
Adding support for --index-url (or) --extra-index-url for PythonVirtualenvOperator

### ISSUE THREAD

**Issue by veerendranathT** [apache/airflow#15886]
**Description**

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

**Comment by ashb** [comment]
I think you can put `--index_url http://internal` in the requirements already.

**Comment by ashb** [comment]
Yes, that works https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format

So this just needs a doc PR -- could you open a PR against the docs to call out this fact?
