### ISSUE TITLE
Set a state of task instances can not be applied to a specific task instance

### ISSUE THREAD

**Issue by fbertos** [apache/airflow#15897]
**Description**

The current API:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_set_task_instances_state

with this parameters:
```
{
"dry_run": true,
"task_id": "string",
"execution_date": "string",
"include_upstream": true,
"include_downstream": true,
"include_future": true,
"include_past": true,
"new_state": "success"
}

```

does not allow to change the status of specific task instance (a task instance is really identified by the pid).

**Use case / motivation**

It would be great if could pass the pid of the task instance in order to change the status of one specific task instance. 
Currently with just the execution_date as parameter there is no way of selecting one specific task instance when we have several task instances started at the same time.
 
Something like:

```
{
"dry_run": true,
"task_id": "string",
"execution_date": "string",
**"pid": int,**
"include_upstream": true,
"include_downstream": true,
"include_future": true,
"include_past": true,
"new_state": "success"
}

```
**Are you willing to submit a PR?**

**Related Issues**

**Comment by ashb** [comment]
A task instances is currently identified by (dag_id, execution_id, task_id).

**Comment by fbertos** [comment]
@ashb, then can you ensure there can not be more than one task instance with the same dag_id, task_id and execution_date? Thanks

**Comment by ashb** [comment]
> @ashb, then can you ensure that's a kind of PK and there can not be more than one task instance with the same dag_id, task_id and execution_date even when they start at the same time? Thanks

Correct. That is a unique constraint in the database.

**Comment by fbertos** [comment]
Hi @ashb, absolutely understood now. Many thanks for your help!
