### ISSUE TITLE
KubernetesPodOperator pod_template_file content doesn't support jinja airflow template variables

### ISSUE THREAD

**Issue by rahulgoyal2987** [apache/airflow#15892]
KubernetesPodOperator  pod_template_file content doesn't support jinja airflow template variables. pod_template_file  is part of templated_fields list. 
https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L165

template_fields: Iterable[str] = (        'image',        'cmds',        'arguments',        'env_vars',        'labels',        'config_file',        'pod_template_file',    )

But pod_template_file content is not supporting template variables. pod_template_file can be implemented the way SparkKubernetesOperator implemented using template_ext

https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py#L46
 template_ext = ('yaml', 'yml', 'json')

**Comment by Dr-Denzy** [comment]
I will put up a PR for this @kaxil

**Comment by rahulgoyal2987** [comment]
@Dr-Denzy  can you share PR?
