### ISSUE TITLE
Airflow Docker - Webserver not starting

### ISSUE THREAD

**Issue by pdavis156879** [apache/airflow#15927]
**Apache Airflow version**: 2.0.2

**Environment**:

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS

Hi there,

I'm running Airflow via Docker using the official docker-compose image, and whilst everything seems to work fine, the webserver gets stuck in an endless loop of:

![image](https://user-images.githubusercontent.com/73368400/118303061-eacc6280-b4dc-11eb-9975-04db58ba8f07.png)

Whilst the image suggests port 8080 is taken, it is not. Nonetheless, I have tried forcing a different external port:

```
airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 5050:8080
```

And the problem persists. 

After a bit more investigation, I found out that apparently, both the scheduler and webserver are using the same port (see image below), unless I'm misinterpreting the log. Is this supposed to happen?

![image](https://user-images.githubusercontent.com/73368400/118717459-00fc5a80-b81e-11eb-80d2-257218f670d3.png)

**Comment by mik-laj** [comment]
> After a bit more investigation, I found out that apparently, both the scheduler and webserver are using the same port (see image below), unless I'm misinterpreting the log. Is this supposed to happen?

This does not cause problems as these ports are not exposed, so they do not conflict. Each container has its own network stack provided by [kernel namespae](https://docs.docker.com/engine/security/#kernel-namespaces).

**Comment by pdavis156879** [comment]
> > After a bit more investigation, I found out that apparently, both the scheduler and webserver are using the same port (see image below), unless I'm misinterpreting the log. Is this supposed to happen?
> 
> This does not cause problems as these ports are not exposed, so they do not conflict. Each container has its own network stack provided by [kernel namespae](https://docs.docker.com/engine/security/#kernel-namespaces). Besides, these ports are not really in use, just an entry in the image metadata. This port may or may not be used.

Hi @mik-laj , thank you so much for the explanation! Makes perfect sense, I am a newcomer when it comes to both Airflow and Docker, so all teachings are more than welcome :)

Any suggestions on how to fix my problem?

**Comment by mik-laj** [comment]
Can you make the logs more verbose? You can do this with the `logging_level` option in the `[logging]` section. The easiest way to do this is with the `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG` environment variable. See: http://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#logging

**Comment by timotk** [comment]
Hi @mik-laj, not the issue creator but ran into this issue too, on macOS  11.3.1.

Here's a debug log:
https://gist.github.com/timotk/4172fbf3bf4687b2b44509830b0ee4e0

Hope it helps.

**Comment by mik-laj** [comment]
Do you have enough memory resources available for the Docker virtual machine? Can you only try to run one container - webserver?

**Comment by potiuk** [comment]
Exit 137 is almost always Out-of-memory. Here you can find the documentation about the right Docker settings for development: https://github.com/apache/airflow/blob/master/BREEZE.rst#docker-community-edition

**Comment by potiuk** [comment]
I think it misses the Memory setting thoughj, but I would recommend at least 4GB RAM /8GB comfortable allocated for Docker if you want to run containerised Airflow.

**Comment by potiuk** [comment]
Good :)

**Comment by pdavis156879** [comment]
> Can you make the logs more verbose? You can do this with the `logging_level` option in the `[logging]` section. The easiest way to do this is with the `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG` environment variable. See: http://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#logging

Hi @mik-laj , I apologize for the late reply.

I set the logging mode to DEBUG and here is the output: https://gist.github.com/pdavis156879/699872f49ee85e7684c75bfd23039b7f

**Comment by pdavis156879** [comment]
@mik-laj I belive I figured out the problem: 
for some reason, even though I ran airflow-init successfully, the Webserver claims the 'dag' table does not exist:
```
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2021-05-19T22:32:51.673116491Z"}
{"log":"  File \"/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1277, in _execute_context\n","stream":"stderr","time":"2021-05-19T22:32:51.673193803Z"}
{"log":"    cursor, statement, parameters, context\n","stream":"stderr","time":"2021-05-19T22:32:51.673212995Z"}
{"log":"  File \"/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 608, in do_execute\n","stream":"stderr","time":"2021-05-19T22:32:51.673420732Z"}
{"log":"    cursor.execute(statement, parameters)\n","stream":"stderr","time":"2021-05-19T22:32:51.673437988Z"}
{"log":"sqlite3.OperationalError: no such table: dag\n","stream":"stderr","time":"2021-05-19T22:32:51.673446786Z"}
{"log":"\n","stream":"stderr","time":"2021-05-19T22:32:51.673454973Z"}
{"log":"The above exception was the direct cause of the following exception:\n","stream":"stderr","time":"2021-05-19T22:32:51.673462998Z"}
```

Any idea what may be causing this?
