### ISSUE TITLE
Configure GCP Secrets Backend For Cloud Customers

### ISSUE THREAD

**Issue by stevenjs1** [apache/airflow#15928]
**Apache Airflow version**: 2.0.2-2

**Environment**: Production

**Cloud provider**: GCP, Astronomer Cloud

**What happened**:
This is a Cloud customer and needs some type of configuration / direction / documentation to correctly config GCP Secrets Manager in Airflow. There is currently no documentation  for Cloud customers, only Enterprise.  

Additional Notes:
Zendesk Ticket: https://astronomer.zendesk.com/agent/tickets/4687

**Comment by mik-laj** [comment]
The Apache Airflow community is independent of service providers. We do not want to promote any partner that offers Airflow as a service., as it may affect the independence/vendor neutrality of the project. If you have problems with a service, you should report to that service provider's technical support, not the Apache community.

You may also be interested in the articles below.
[Configuring Cloud Composer environments with Secret Manager](https://cloud.google.com/composer/docs/secret-manager)
[Configure an External Secrets Backend on Astronomer](https://www.astronomer.io/docs/cloud/stable/customize-airflow/secrets-backend)

**Comment by stevenjs1** [comment]
This was opened here in error. Closing.
