### ISSUE TITLE
MacOS docker-compose 2.0.2 webserver restart all the time，but centos is normal！

### ISSUE THREAD

**Issue by andotorg** [apache/airflow#15961]
ERROR INFO： 
Log  Print： 
airflow-webserver_1  | Traceback (most recent call last):
airflow-webserver_1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
airflow-webserver_1  |     sys.exit(main())
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
airflow-webserver_1  |     args.func(args)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
airflow-webserver_1  |     return func(*args, **kwargs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
airflow-webserver_1  |     return f(*args, **kwargs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/webserver_command.py", line 368, in webserver
airflow-webserver_1  |     check_if_pidfile_process_is_running(pid_file=pid_file, process_name="webserver")
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/process_utils.py", line 266, in check_if_pidfile_process_is_running
airflow-webserver_1  |     raise AirflowException(f"The {process_name} is already running under PID {pid}.")
airflow-webserver_1  | airflow.exceptions.AirflowException: The webserver is already running under PID 24.
airflow_airflow-webserver_1 exited with code 1

CentOS7 docker-compose running is normal!

CentOS docker-compose website document executer command, is restart all the time .

**Comment by potiuk** [comment]
You should increase the memory allocated for Docker engine in Docker Desktop. It should be 4GB at least (I think default is 2 GB)
