### ISSUE TITLE
Constraints support in DockerOperator

### ISSUE THREAD

**Issue by nisarg1499** [apache/airflow#15974]
**Description**
In the current DockerSwarmOperator, there is no parameter of network and constraint. It will create a container in a new network and without constraints of worker node or manager node. Now, there is support of network in DockerOperator, but constraints is not supported. 

Use case : 

**Use case / motivation**
If some user has an existing swarm network and want to create a service with network and constraints specified, then this support will be useful.

Final output should be that a user can start a service with network and constraints(worker or manager) specified in existing swarm network.

**Are you willing to submit a PR?**
Yes

**Comment by nisarg1499** [comment]
I am working on this issue.

**Comment by eladkal** [comment]
@nisarg1499 are you still working on this issue?

**Comment by nisarg1499** [comment]
> @nisarg1499 are you still working on this issue?

Hey @eladkal Currently I am not working on this due to hectic schedule. But I know the solution as I have worked on this and I was planning to complete that in December. But if in between someone wants to work on this, then feel free to take it.

**Comment by Bowrna** [comment]
I am willing to try fixing this issue :)

**Comment by eladkal** [comment]
@Bowrna assgined

**Comment by Bowrna** [comment]
https://github.com/apache/airflow/blob/e63f6e36d14a8cd2462e80f26fb4809ab8698380/airflow/providers/docker/operators/docker_swarm.py#L93-L113

In docker swarm, we have the option to pass network and placement. The type `placement` is a type of dict and accepts constraint as a parameter.  The current code of DockerSwarmOperator looks like having support for network and constraint. Maybe we can improve the documentation for better understanding. 

```
placement= Placement(constraints=['node.role == "manager"'])
```
I didn't try the above code, but something in this way is supported to pass constraint

If I am missing to understand any part, please explain

In DockerOperator, when you mean by constraint, do you mean the resource constraint? If yes, there is support for cpu_shares, mem_limit. If it's something different, could you explain?

**Comment by Bowrna** [comment]
Could we close this issue as suggested in PR https://github.com/apache/airflow/pull/22217 @eladkal?

We already have documentation for this part and you can refer to the below part to check about network and constraints.

![image](https://user-images.githubusercontent.com/10162465/158301569-861414f1-c86b-466a-9dba-a3cd8f6fdd31.png)

**Comment by eladkal** [comment]
Closing as no action needed
see https://github.com/apache/airflow/pull/22217#discussion_r826089680
