### ISSUE TITLE
SalesforceToGcsOperator requires additional packages

### ISSUE THREAD

**Issue by hprzegendza** [apache/airflow#15977]
**Apache Airflow version**: 1.10.15
**Environment**: GCP composer - image: `composer-1.16.0-airflow-1.10.15` 

**What happened**:
When trying to import the `SalesforceToGcsOperator` in a DAG:
```
from airflow.providers.google.cloud.transfers.salesforce_to_gcs import SalesforceToGcsOperator
```

A Broken DAG error is reported by the composer:`No module names 'airflow.providers.salesforce'`

**What you expected to happen**:
`SalesforceToGcsOperator` being available.

**What do you think went wrong?**:
`apache-airflow-backport-providers-salesforce` package not being listed as required by `apache-airflow-backport-providers-google`

**How to reproduce it**:
- Import `SalesforceToGcsOperator`:
```
from airflow.providers.google.cloud.transfers.salesforce_to_gcs import SalesforceToGcsOperator
```
- Try using it.
- Get an error.
- Install apache-airflow-backport-providers-salesforce(2021.3.3).
- Try again.

**Anything else we need to know**:
The line importing the missing package:
https://github.com/apache/airflow/blob/85b2ccb0c5e03495c58e7c4fb0513ceb4419a103/airflow/providers/google/cloud/transfers/salesforce_to_gcs.py#L24

EDIT: corrected the composer image's version

**Comment by mik-laj** [comment]
This dependency is listed in "Cross provider package dependencies" section. See: https://pypi.org/project/apache-airflow-backport-providers-google/

Additionally, we do not support backport providers. See. https://lists.apache.org/thread.html/rb34212bd13c44aa61e793d0fef14f4ab9d9408939b1b98dc814cf274%40%3Cdev.airflow.apache.org%3E
