### ISSUE TITLE
Deleting a DagRun from UI does not delete its associated tasks

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#15986]
**Apache Airflow version**: master

When DagRuns are selected in the UI for deletion, a request is sent to the `DagRunModelView.action_muldelete`, a Flask-Appbuilder action:

https://github.com/apache/airflow/blob/aa4713e43f92d3e4c68c3ad00e2d44caaf29aafe/airflow/www/views.py#L3490-L3496

The function deletes all the DagRun rows matching the selection from db. However, this does not delete the TaskInstance rows (also TaskFail, maybe more?) associated to the DagRun.

This is also peripherally related to AIP-39; one of the issues here is there is not a concrete relatation between DagRun and its associates; they are all fetched by an implicit relation via their `dag_id` and `execution_date` values.

So I guess the question here is two-way: Should we consider the current behaviour a bug and remove rows associated to a DagRun as well? And if not, how should be keep the behaviour after implementing AIP-39, which likely will link them together with concrete foreign keys?

**Comment by eladkal** [comment]
Is there a value in keep saving the tasks when the DagRun is deleted?

**Comment by uranusjr** [comment]
Not to my knowledge.

**Comment by potiuk** [comment]
> Is there a value in keep saving the tasks when the DagRun is deleted?

Should not be.

> So I guess the question here is two-way: Should we consider the current behaviour a bug and remove rows associated to a DagRun as well? And if not, how should be keep the behaviour after implementing AIP-39, which likely will link them together with concrete foreign keys?

Cascade-delete should be expected behaviour IMHO.

**Comment by uranusjr** [comment]
In that case, we should implement cascading deletion as a part of #16320, which would (I think) make `TaskInstance.run_id` a foreign key constraint on `DagRun.run_id`.
