### ISSUE TITLE
Move `UPDATING.md` to Doc site

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#15996]
Currently, there are 2 places users need to look into when updating an Airflow Version:

* Changelog: https://airflow.apache.org/docs/apache-airflow/2.1.0/changelog.html
* Updating.md: https://github.com/apache/airflow/blob/master/UPDATING.md#airflow-210

We should create a new section on "Updating" in docs where we have 2 pages: 

1. Changelog -- same as what we have now just moved under that section
2. Move the https://github.com/apache/airflow/blob/master/UPDATING.md guide to https://github.com/apache/airflow/tree/master/docs/apache-airflow

**Comment by Dr-Denzy** [comment]
I will create a PR for this @kaxil
