### ISSUE TITLE
Service for scheduler

### ISSUE THREAD

**Issue by codewithcheese** [apache/airflow#16]
Hi

I'm just trying to figure how the tasks are run in production. Am I right in thinking that the scheduler must be running, and if i am using celery than a worker must be running as well?

I just plan on using mysql at the moment. Do you recommend creating a init script to start the scheduler?

Cheers

**Comment by mistercrunch** [comment]
You are absolutely right. A more modest single worker setup could run the scheduler with the LocalExecutor (as subprocesses). No Celery or message queue setup is needed in that case, but you are limited to a single worker.

**Comment by codewithcheese** [comment]
Ok great thanks. I see the LocalExecutor can run tasks in parallel using multiprocessing. Will the scheduler be able to run tasks from different DAGs in parallel?

**Comment by mistercrunch** [comment]
Yes.

**Comment by codewithcheese** [comment]
:+1:
