### ISSUE TITLE
DagRun triggered via API stuck in running state

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#16009]
**Apache Airflow version**: v2.2.0.dev0 

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
Breeze + postgres

**What happened**:

Originally reported on [StackOverflow](https://stackoverflow.com/questions/67657260/using-airflow-restapi-to-trigger-dag-doesnt-work-but-clicking-in-ui-does).

It seems that triggering a dag run via API with execution date results in dag run that is stuck in running state.

**What you expected to happen**:

Triggering dag via API should always result in DAG being executed.

**How to reproduce it**:
```py
import requests
import json
from datetime import datetime
from pprint import pprint

if __name__ == '__main__':
    headers = {
        'accept':'application/json',
        'content-type':'application/json',
    }
    auth = ('admin','admin')
    body = {
        "conf": {},
        "dag_run_id": "testrun01",
        "execution_date":datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    print(body)
    result = requests.post(
      "http://localhost:28080/api/v1/dags/example_bash_operator/dagRuns",
        headers=headers,
        auth=auth,
      data=json.dumps(body)
    )
    pprint(result.json())
```

Then go to Airflow UI and you should see that there's a run stuck in running state:
<img width="1133" alt="Screenshot 2021-05-23 at 11 48 09" src="https://user-images.githubusercontent.com/9528307/119255560-c3e8ed00-bbbc-11eb-8a23-75296f54225e.png">

**Comment by turbaszek** [comment]
Ok, it seems that the problem is in fact that I'm triggering a DAG with date other than in UTC timezone, so the execution data is in future:
<img width="1666" alt="Screenshot 2021-05-23 at 11 58 27" src="https://user-images.githubusercontent.com/9528307/119255859-34443e00-bbbe-11eb-88ec-b13ae55082ed.png">

I'm not sure if this is expected behaviour. WDYT @kaxil @jhtimmins ?

**Comment by ashb** [comment]
Expected behaviour I think.

**Comment by turbaszek** [comment]
Closing as this seems to be an expected behaviour

**Comment by kaxil** [comment]
Oh yea expected behaviour
