### ISSUE TITLE
If external postgres password contains '@' then it appends it to host.

### ISSUE THREAD

**Issue by Anirudhaagrawal** [apache/airflow#16000]
**What happened:**

My password for external Postgres RDS contained '@123' at the end which got appended to the host of the DB due to some bug. One can notice in the logs, the DB_HOST has an unwanted 123@ in the front of it  DB_HOST=**123@**{{postgres_host}}. I removed '@' character from the password and it worked fine. 

I am using the latest image of apache/airflow and using the official helm chart.

```
kc logs airflow-run-airflow-migrations-xxx
BACKEND=postgresql
DB_HOST=123@{{postgres_host}}
DB_PORT=5432
....................
ERROR! Maximum number of retries (20) reached.

Last check result:
$ run_nc '123@{{postgres_host}}' '5432'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
Can't parse  as an IP address
```

**Steps to reproduce:**
One can easily reproduce this by using a password that contains the '@' character in it.
```
data:
  metadataConnection:
    user: {{postgres_airflow_username}}
    pass: {{postgres_airflow_password}}
    protocol: postgresql  
    host: {{postgres_host}}
    port: 5432
    db: {{postgres_airflow_dbname}}
```

**Expected behavior:**
Migrations should run irrespective if the Postgres password contains an @ character or not.

**Comment by mik-laj** [comment]
Password should be percent encoded. See: https://github.com/apache/airflow/pull/15089

**Comment by mik-laj** [comment]
But yes. This is a bug, not in Docker Image, but in Helm Chart. It uses string concatenation to build URI.

**Comment by mik-laj** [comment]
In Apache Airflow, we need to build the URL from the values from the `values.yaml` file, but unfortunately this cannot be done because to build the URL with userinfo we need a function that percent-encode the usernaame/password.  
More context: https://github.com/apache/airflow/pull/16004

**Comment by mik-laj** [comment]
@Anirudhaagrawal I working on this bug. Can you check my PR? https://github.com/apache/airflow/pull/16004
