### ISSUE TITLE
GoogleCloudStorageToBigQueryOperator reads string as a list in parameter source_objects

### ISSUE THREAD

**Issue by stavhaco** [apache/airflow#16008]
**Apache Airflow version**:1.10.12
**Environment**: google cloud composer

**What happened**:
When using GoogleCloudStorageToBigQueryOperator and providing string as parameter source_objects, the process is iterating on a the string as a valid list.
For example - 
`cloud_storage_to_bigquery = GoogleCloudStorageToBigQueryOperator(
        bucket = 'bucket',
        source_objects = 'abc',
    )`
Will result in looking into the sources: bucket/a, bucket/b, bucket/c.

**What you expected to happen**:
Throw an error on type (string instead of list).

**Comment by eladkal** [comment]
`GoogleCloudStorageToBigQueryOperator` is deprecated. Please use `GCSToBigQueryOperator` from providers.
Note that `source_objects` expect `list` not `str`. You should set `source_objects = ['abc']`

**Comment by stavhaco** [comment]
@eladkal seems like the behaviour is the same in GCSToBigQueryOperator.
I get that the parameter should be set as `source_objects = ['abc']` but shouldn't I expect type error when setting it to `source_objects = 'abc'`? instead of iterating on the chars of the string and looking for different paths based on it?

**Comment by eladkal** [comment]
PRs are welcome :)

**Comment by stavhaco** [comment]
@eladkal Alright. Can this be assigned to me?

**Comment by eladkal** [comment]
You can just open a PR
BTW probably a better solution would be to allow `str or List[str]` rather than raise error.
