### ISSUE TITLE
[Helm] Resources for the git-sync sidecar

### ISSUE THREAD

**Issue by CyberHippo** [apache/airflow#16056]
**Description**

It would be nice to be able to specify resources for the `git-sync` sidecar in the helm chart values.

**Use case / motivation**

I don't want to use keda for autoscaling and would like to setup a HPA myself. However this is currently not possible since it is not possible to specify resources for the `git-sync` sidecar.

**Are you willing to submit a PR?**

Yes, I am willing to submit a PR.

**Related Issues**

Not that I know of.

**Comment by potiuk** [comment]
Go for it @CyberHippo
