### ISSUE TITLE
Snowflake hook doesn't parameterize SQL passed as a string type, causing SnowflakeOperator to fail

### ISSUE THREAD

**Issue by grassten** [apache/airflow#16068]
**Apache Airflow version**: 2.1.0

**What happened**: The new Snowflake hook run method is not taking parameters into account when the SQL is passed as a string; it's using Snowflake connector's execute_string method, which does not support parameterization. So the only way to parameterize your query from a SnowflakeOperator is to put the SQL into a list. 

https://github.com/apache/airflow/blob/304e174674ff6921cb7ed79c0158949b50eff8fe/airflow/providers/snowflake/hooks/snowflake.py#L272-L279

https://docs.snowflake.com/en/user-guide/python-connector-api.html#execute_string

**How to reproduce it**: Pass a sql string and parameters to SnowflakeOperator; the query will not be parameterized, and will fail as a SQL syntax error on the parameterization characters, e.g. %(param)s.

**Anything else we need to know**: Quick workaround is to put your sql string into a list, these are still being parameterized correctly.

**Comment by potiuk** [comment]
Would you be willing to submit a fix @grassten ? Happy to review and merge it,

**Comment by grassten** [comment]
@potiuk I'm wondering if we should split the passed sql param and then parameterize the resulting queries, or stop splitting the string altogether (splitting was implemented recently in #15533). To split the string I think we could use `from snowflake.connector.util_text import split_statements`; that's what's used by execute_string in the Snowflake connector. (I have that in a PR in my fork [here](https://github.com/grassten/airflow/pull/1))

That being said, I don't think parameterizing a list of queries (after splitting) with a single set of params makes sense. cc @mobuchowski @eladkal I see you guys on that PR, what do you think?

**Comment by potiuk** [comment]
@mobuchowski  - WDYT?
