### ISSUE TITLE
Queued tasks become running after dagrun is marked failed

### ISSUE THREAD

**Issue by doowhtron** [apache/airflow#16078]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): centos7
- **Kernel** (e.g. `uname -a`): 3.10.0
- **Install tools**:
- **Others**:

**What happened**:

A dagrun has some tasks which are in running and queued status because the concurrency limit. After I mark dagrun as **failed**, the running tasks turn **failed** while the queued tasks turn **running**.

**What you expected to happen**:

The queued tasks should turn **failed** instead of **running**

**How to reproduce it**:

- in airflow.cfg set worker_concurrency=8, dag_concurrency=64
- create a dag with 100 BashOperator tasks which are all independent, with a bash command "sleep 1d"
- run the dag, and will see 8 tasks running, 56 queued and 36 scheduled
- mark the dagrun as failed, and will see 8 running tasks are set failed, but another 8 are set running and the rest 84 are set no_status. If the dagrun is marked failed again, this process will be repeated again.

**Anything else we need to know**:

**Comment by ephraimbuddy** [comment]
I think the behaviour is Ok. @ash should we change this to fail all task instances and never run any other instances when the dagrun fail?

**Comment by potiuk** [comment]
Thanks @SamWheating for notifying. It missed "closes: " :)
