### ISSUE TITLE
Can't see connection type OpsGenie

### ISSUE THREAD

**Issue by cleveritcz** [apache/airflow#16094]
Hello,
I tried to get work Apache Airflow with OpsGenie in docker container.

I installed apache-airflow-providers-opsgenie but still I can't see in Connections option for OpsGenie. Or what should be happened when is installed. Documentation is missing. I also don't know if it is python 2 or python 3. I installed it for both versions. 
 
Could you help me, please?

**Comment by potiuk** [comment]
The current OpsGenie provider uses HTTPConnection. There is nothing special for OpsGenie there. However there is a change  coming and in the next version of OpsGenie provider, you will see OpsGenie as separate connection:

See https://github.com/apache/airflow/pull/16048

**Comment by cleveritcz** [comment]
ok, thanks
