### ISSUE TITLE
Contradictory default in store_dag configuration reference

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#16090]
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#store-dag-code

![Captura de pantalla 2021-05-26 a las 17 47 56](https://user-images.githubusercontent.com/11339132/119691160-a2049a00-be4a-11eb-8f55-0ad2c6117620.png)

The Default is True or None?

**Comment by potiuk** [comment]
The default value is sort of `Trueish` . Thanks :). PR to fix it on its way
