### ISSUE TITLE
List only a single level of TaskGroup in tree view

### ISSUE THREAD

**Issue by tothandor** [apache/airflow#16112]
**Description**

TaskGroups are somewhat replacements for SubDAGs, but with lower latency and better integration. But its major drawback to SubDAGs becomes apparent in tree view, where many "subtasks" makes a tree incomprehensible. A nested folder view we got used to with SubDAGs would solve that anew. Similar to directory trees, only a single level of task group (or path) should be listed.
The root level would list the tasks which have no task group specified. One could dive into a task group by clicking on its node, and that would list only those tasks which has the selected task group set.
The UI elements from SubDAGs could be reused.

**Use case / motivation**

Make tree views with many subtasks comprehensible again.

**Are you willing to submit a PR?**

I would love to, but I'm not familiar with frontend frameworks.

**Related Issues**

Issue #13242 is somewhat related, but has a different focus.

**Comment by ashb** [comment]
Could you show a screenshot of what you mean? TaskGroups can be nested inside each other (did you already know this?) so I'm not quite sure what you are asking.

**Comment by tothandor** [comment]
Sure. 

Here's a graph view collapsed and grouped with TaskGroup:
![image](https://user-images.githubusercontent.com/4449214/119849789-36cfcc00-bf0d-11eb-976b-dbcb22dcb496.png)

And here it is expanded:
![image](https://user-images.githubusercontent.com/4449214/119849911-55ce5e00-bf0d-11eb-88ea-09ee4b2a2fa8.png)

And the tree view (query names masked out):
![image](https://user-images.githubusercontent.com/4449214/119850291-b362aa80-bf0d-11eb-8495-5791def11d12.png)
You may say it's not incomprehensible, but usually there are more task groups along the pipeline, where each contains 10 to 100 subtasks generated dynamically. Each leaf node gets repeated.

Compare this to a classic grouping with SubDAGs.
![image](https://user-images.githubusercontent.com/4449214/119850770-20764000-bf0e-11eb-86eb-8593bca4dcff.png)

And zooming to the `sql` subdag:
![image](https://user-images.githubusercontent.com/4449214/119850931-4865a380-bf0e-11eb-9fa4-3540b95ab4dd.png)

Nice and flat. 

I am aware of TaskGroup nesting, that's what I have mentioned "path" in parentheses, but that does not help.

**Comment by bbovenzi** [comment]
Tell me if I got this right.

The other issue mentioned is to show only the TaskGroup and orphan tasks in the Tree View. Then this issue focuses on what happens when you click on a TaskGroup leaf: it renders a new tree of just the tasks of that TaskGroup like we do with SubDags.

If so, we should probably merge these two issues into a singular complete feature.

One thing I do not like with our SubDag approach is how you lose context of the rest of the DAG when drilling down. So maybe we do a bounded box around it like we do with the Graph View.

**Comment by tothandor** [comment]
@bbovenzi you're right. A click on a TaskGroup would render a new tree, with just those tasks in the TaskGroup, just as it happens with SubDags.

As for the context, there are numerous solutions around where one could browse a hierarchy, without losing context. In webshops, breadcrumbs help to navigate. In folder/directory trees you'll have the path somewhere.   

Though, I don't know if it is possible to, but what would happen if someone adds every second task to a group along a pipeline. 
Like: ```T1:nogroup => T2:group1 => T3:nogroup => T4:group1 => T5:nogroup```
Is that valid? I'll give it a try.

**Comment by tothandor** [comment]
Now, that's interesting.

Graph view folded:
![image](https://user-images.githubusercontent.com/4449214/120061655-8540b000-c05e-11eb-8fd1-7a672269f9aa.png)

Graph view unfolded:
![image](https://user-images.githubusercontent.com/4449214/120061619-5d514c80-c05e-11eb-947d-23dcc652e79a.png)

Tree view:
![image](https://user-images.githubusercontent.com/4449214/120061636-6e01c280-c05e-11eb-8b19-ae5200c8c472.png)

How can this be folded in tree view?

**Comment by bbovenzi** [comment]
Sorry, I've been working on a few other things.

Yes, I think that makes sense. It's not a perfect representation, but neither is a tree in general.
