### ISSUE TITLE
Not able to access airflow-variables at worker

### ISSUE THREAD

**Issue by Prajakta-Palve** [apache/airflow#16113]
I have deployed airflow on kubernetes where as webserver, scheduler, postgres and redis are on kubernetes but airflow-worker is on different server. Other tasks executes properly but if I am trying to access airflow-variables then it throws an error showing 
**Variable Variable_Name does not exist**

But if I list airflow-variables via CLI  then it lists them
![Screenshot from 2021-05-27 17-25-39](https://user-images.githubusercontent.com/52483395/119821874-aeebc100-bf10-11eb-9c0f-f93c2c15b06d.png)

A line of code that I am using to access variable is
`variable_name = Variable.get("Variable_Name",deserialize_json=True)`

How do I access airflow variables in worker?

**Comment by potiuk** [comment]
you need to put a real variable name in there and not "Variable_Name"
