### ISSUE TITLE
KubernetesPodOperator env_vars Jinja Templates Not Used

### ISSUE THREAD

**Issue by alexanderursu99** [apache/airflow#16125]
**Apache Airflow version**: v2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.16

**Environment**: Kubernetes (EKS)

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Helm
- **Others**:

**What happened**:

Using task instance of KubernetesPodOperator as shown below, when the DAG runs the Jinja templating is applied for the `arguments` parameter, but not for the `env_vars` parameter, as we see in the logs from the task no all lines have the expected values substituted.

```
from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator

ds = "{{ ds }}"
ts = "{{ ts }}"

passing = KubernetesPodOperator(
    namespace='airflow',
    image="python:3.6",
    cmds=["python", "-c"],
    arguments=[f"import os; print('{my_secret}'); print('{ds}'); print('{ts}'); print(os.environ['TEST_DS']); print(os.environ['TEST_TS']); exit(0)"],
    env_vars={
        "TEST_DS": ds,
        "TEST_TS": "{{ ts }}"
    },
    labels={"foo": "bar"},
    name="passing-task",
    task_id="passing-task",
    is_delete_operator_pod=True,
    get_logs=True,
    dag=dag,
)
```

```
[2021-05-27 19:17:33,424] {pod_launcher.py:136} INFO - this is the value for this variable
[2021-05-27 19:17:33,424] {pod_launcher.py:136} INFO - 2021-05-27
[2021-05-27 19:17:33,425] {pod_launcher.py:136} INFO - 2021-05-27T19:17:25.205147+00:00
[2021-05-27 19:17:33,425] {pod_launcher.py:136} INFO - {{ ds }}
[2021-05-27 19:17:33,425] {pod_launcher.py:136} INFO - {{ ts }}
```

**What you expected to happen**:

It is documented [here](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/_api/airflow/providers/cncf/kubernetes/operators/kubernetes_pod/index.html#airflow.providers.cncf.kubernetes.operators.kubernetes_pod.KubernetesPodOperator.template_fields) that both `arguments` and `env_vars` are templated fields.

I expect that Jinja templating is applied as expected to values in both paramters, being the items in the `arguments` list, and the values of the `env_vars` dictionary.

**How to reproduce it**:

Create a sample DAG with a task defined as above, and run the DAG.

**Comment by Alxander64** [comment]
Just wanted to add that I've also tried this example blow:

```
from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
from kubernetes.client import models as k8s

ds = "{{ ds }}"
ts = "{{ ts }}"

env_vars = [
    k8s.V1EnvVar("TEST_DS", ds),
    k8s.V1EnvVar("TEST_TS", "{{ ts }}"),
]

passing = KubernetesPodOperator(
    namespace='airflow',
    image="python:3.6",
    cmds=["python", "-c"],
    arguments=[f"import os; print('{my_secret}'); print('{ds}'); print('{ts}'); print(os.environ['TEST_DS']); print(os.environ['TEST_TS']); exit(0)"],
    env_vars=env_vars,
    labels={"foo": "bar"},
    name="passing-task",
    task_id="passing-task",
    is_delete_operator_pod=True,
    get_logs=True,
    dag=dag,
)
```

I still get the same result as I originally described. I just realized that this is what the type specification for initializing KubernetesPodOperator expects, but it made no difference.

**Comment by jedcunningham** [comment]
@Alxander64, can you try with the latest (or maybe second latest if you can't update to `2.1.0`) cncf.kubernetes provider? I believe this was already fixed: #14123

**Comment by Alxander64** [comment]
@jedcunningham Thanks, I will be sure to try this and report back!

**Comment by Alxander64** [comment]
@jedcunningham I updated to 2.1.0 and this issue is in fact fixed, thanks!
