### ISSUE TITLE
Gantt chart for DAGs in UI

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#16132]
The idea is to have a Gantt graph for the DAGs in the UI, so that you can see at what hours there are more overlaps, when you have a gap without any dag running, which ones are the most time consuming etc.

I think it could be done by taking the average execution time of the dag in the last X days from the metadata database or something like that. Also, for further precision, an outlier processing could be done as well. 

From my point of view, is a very nice feature to be added to the new UI

**Comment by eladkal** [comment]
Seems like a duplication of https://github.com/apache/airflow/issues/8931
