### ISSUE TITLE
Delete local logs when choosing remote logging

### ISSUE THREAD

**Issue by JPonte** [apache/airflow#16142]
**Description**

When remote logging is enable, logs are sent to S3/Google Cloud Storage/etc but never deleted from the local disk. This can be an issue when the disk space in the workers is limited.

**Use case / motivation**

Local logs should be deleted when upload to the remote services is successful. 

**Are you willing to submit a PR?**

Yes.

**Related Issues**

Not that I'm aware of.

**Comment by potiuk** [comment]
Hey @JPonte - thanks! Would you like to submit PR for that?

**Comment by JPonte** [comment]
@potiuk Yes, I'll see what I can do.

**Comment by Jorricks** [comment]
Is it an option to put this behind a flag? We also use remote logging but are in favor of keeping our logs locally as well. In the case our remote logging solution becomes unavailable, we still have the local logs for debugging purposes.
Furthermore, we do periodic removal of logs older than two weeks, so we don't face the issue of growing log sizes.

**Comment by potiuk** [comment]
> Is it an option to put this behind a flag? We also use remote logging but are in favor of keeping our logs locally as well. In the case our remote logging solution becomes unavailable, we still have the local logs for debugging purposes. Furthermore, we do periodic removal of logs older than two weeks, so we don't face the issue of growing log sizes.

Yes. It should be optional.
