### ISSUE TITLE
Combined Executor - KubernetesExecutor + LocalExecutor

### ISSUE THREAD

**Issue by hendoxc** [apache/airflow#16185]
**Description**
In short: There exists already combined executor support for Celery + Kubernetes, I think that also adding Local + Kubernetes
would be warmly welcomed.

**Use case / motivation**

Many tasks are low-resource intensive tasks on the airflow pod, It makes sense to keep things running on LocalExecutor, 0 overhead. However I also have a large number of dags, that have some long running tasks which are somewhat resource hungry, for these I currently use KubernetesPodOperator, this makes the Dags more scalable and overall workload elastic. Being able to easily switch between easily between KubernetesExecutor and LocalExecutor, just feels natural in this sense.

**Related Issues**

N/A
@potiuk

**Comment by potiuk** [comment]
Worth looking at creating !

**Comment by acmh** [comment]
@potiuk  Can I grab this issue? If yes, where I can start looking?

**Comment by potiuk** [comment]
Take a look at ``CeleryKubernetesExecutor``. Although this one would require a little more intrinsic knowledge of Airflow - so please take a little more knowledge of Airflow  - like integration with Helm Chart etc. Maybe marking it as ``first-good-issue`` was not the best idea :) . Just take a look at the C-K executor and see if this is something you would like to take on.
