### ISSUE TITLE
Building Prod image Python 3.6 on CI

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#16193]
Seems that we started having a problem with building PROD image for Python 3.6 - it consistently fails. 

Needs investigation and fix.

**Comment by karakanb** [comment]
We started getting failures in our pipelines as well due to the `-build` images being missing from Docker Hub, we used to use `airflow:2.0.1-python3.8-build` images, and they are missing now. Seems like they might be related, are they?

**Comment by potiuk** [comment]
Not really. The build images are gone because they were moved to `apache/airflow-ci`. The `build` images in registry are also not needed to build the actual production images (they will be automatically build when you run 'docker buid'. The ones in 'airflow-ci' are only for optimization of the speed of the build
