### ISSUE TITLE
Airflow scheduler - Can't start correctly because it has error message about DagFileProcessor0-Process failed

### ISSUE THREAD

**Issue by jhonatanrt** [apache/airflow#16207]
Hi guys,
I have a bug problem with the last version of airflow (2.1.0). Because, I can't start the app correctly. If you could help me with another configuration or fix.
When I like to make a schedule in airflow Dag or sync new Dags, Airflow didn't work. 
My configuration:
CPU: 1GB
Memory: 2GB

Environment:
"AIRFLOW_DATABASE_NAME": *****,
"AIRFLOW_DATABASE_PORT_NUMBER": "5432",
"AIRFLOW_DATABASE_HOST": ******,
"AIRFLOW_EXECUTOR": "CeleryExecutor",
"AIRFLOW_WEBSERVER_HOST": "webserver.airflow",
"AIRFLOW_LOAD_EXAMPLES": "no",
"AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL": "30",
"REDIS_HOST": *****,
"BUCKET_NAME": *****

_Error screenshot_

![image](https://user-images.githubusercontent.com/22306384/120385181-b2a28d80-c2ec-11eb-9826-3cdcf46a9966.png)

Thanks for your help.

**Comment by jedcunningham** [comment]
@jhonatanrt, can you post the complete traceback?

**Comment by jedcunningham** [comment]
```
PermissionError: [Errno 13] Permission denied: '/opt/bitnami/airflow/logs/scheduler/2021-06-01/demo.py.log'
```

It looks like the scheduler can't write log files. You'll need to debug why as that would be something with the bitnami chart, image, or your cluster. If you can reproduce it, it might be worth an issue over at bitnami.

(If you weren't aware, the community also recently released the official community chart: https://airflow.apache.org/docs/helm-chart/stable/index.html)

**Comment by jhonatanrt** [comment]
Thanks @jedcunningham. I had a problem with the user root. when I changed to user 1001 that work well.  🙂

**Comment by raefezzeldin** [comment]
@jhonatanrt  I am facing the same issue when I tries to presist logs from where did you change the user?
