### ISSUE TITLE
add ability to add java_opts for jdbcoperator

### ISSUE THREAD

**Issue by cocampbe** [apache/airflow#16208]
**Description**

I need to add java_opts to the jdbcoperator.

**Use case / motivation**

Adding the java_opts will allow me to run drill queries against HPE MAPR.

Rather than telling us how you might implement this solution, try to take a
step back and describe what you are trying to achieve.

-->

**Are you willing to submit a PR?**

Sure, but I think it may actually need a change to jaydebeapi as well

**Comment by uranusjr** [comment]
If this requires a change in jaydebeapi, you’ll need to request a change there first: https://github.com/baztian/jaydebeapi

Airflow can’t implement it until its dependencies provide that functionality.
