### ISSUE TITLE
Can't increase the limit of return DAGs for listDAGs REST API

### ISSUE THREAD

**Issue by iitzhak** [apache/airflow#16217]
Hi guys,
when I send the following REST API I receive only the first 100 DAGs:
GET https://<hostname>:8080/api/v1/dags?**limit=200**
Is it possible to get more than 100 records in a single request? 

Thanks,
Itay

**Comment by uranusjr** [comment]
You need to set the configuration `[api] maximum_page_limit` to a higher number.
