### ISSUE TITLE
Can not find master-python3.8 image in DockerHub

### ISSUE THREAD

**Issue by akihiro-inui** [apache/airflow#16215]
Hi, I'm trying to use the Docker image with `airflow:master-python3.8`
but I'm getting this error.
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/apache/airflow:master-python3.8: not found

```
It seems the image called master-python3.8 dissapeared. Can anyone help me which image I should use or is this image coming back?

**Comment by potiuk** [comment]
The image has just been moved (it's been announced at the devlist) to `apache/airflow-ci`  repo and `master` has been renamed to `main` (because we renamed the HEAD branch of our repository to `main`.

The right command to get it now is:

```
docker pull apache/airflow-ci:main-python3.8
```
