### ISSUE TITLE
trigger a dag，dag_run is success but instance is not run

### ISSUE THREAD

**Issue by zqd759592942** [apache/airflow#16235]
![Image of Yaktocat](https://github.com/zqd759592942/Test/blob/master/Snipaste_2021-06-03_16-01-43.png?raw=true)
when I trigger a dag,this dag_run is success but instance is not run

**Comment by zqd759592942** [comment]
airflow2.0.2 
the instances state is NONE

**Comment by ephraimbuddy** [comment]
Please share the steps to reproduce

**Comment by zqd759592942** [comment]
1.  I execute cmd "airflow dags trigger xxx"
2.  I'll go see this dag
Then the above problem occurs,Hard to reproduce,It seems that there is a small chance of a problem

**Comment by zqd759592942** [comment]
the scheduler.log:
{{dagrun.py:445}} INFO - Marking run <DagRun TEST_ABC_SUB_1 @ 2021-06-03 06:25:18+00:00: manual__2021-06-03T06:25:18+00:00, externally triggered: True> successful
![Image of Yaktocat](https://github.com/zqd759592942/Test/blob/master/Snipaste_2021-06-03_17-58-09.png?raw=true)
Did these  unfinished_tasks   disappear?

**Comment by eladkal** [comment]
Does this happens on a specific DAG ?

**Comment by ephraimbuddy** [comment]
> Does this happens on a specific DAG ?

In addition to this, can you try this on airflow 2.1.0?
