### ISSUE TITLE
Add support for types of Secrets in Kubernetes

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#16237]
It's impossible at the moment to pass Opaque secret in Airflow.
The Airflow secret object doesn't have type https://github.com/apache/airflow/blob/8505d2f0a4524313e3eff7a4f16b9a9439c7a79f/airflow/kubernetes/secret.py#L28
https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Comment by alexInhert** [comment]
hi @jedcunningham do you think it's possible to support it?

**Comment by jedcunningham** [comment]
Hey @alexInhert!

Airflow Secret != K8s Secret. Basically the Airflow Secret is a helper to simplify using an existing K8s Secret into a pod, not a way to define a secret. For instance, instead of having to build both a Volume and VolumeMount you can represent both with an Airflow Secret and let Airflow deal with the specifics.

Can you expand on what you are trying to do?

**Comment by alexInhert** [comment]
@jedcunningham the use case is to export Airflow variables or connections (which stored securely in airflow say via secret backend) to the pod.

**Comment by mik-laj** [comment]
As a workaround, to use the same values, we can support VaultSecretBackend and Vault Injector. All secrets should be stored in the Vault. Airflow will have access to them using [VaultBackend](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/secrets-backends/hashicorp-vault.html). Kubernetes will be able to access them with [Vault Injector](https://www.vaultproject.io/docs/platform/k8s/injector/examples). It's not a perfect solution, but I think it can be useful in many cases.

**Comment by alexInhert** [comment]
@mik-laj yes it's a good solution but not for Opaque secrets because these secrets are to exist only while pod is running. they are created before the pod starts and removed after. I don't think it make sense to write these to Vault only to remove them after the task finish.

**Comment by potiuk** [comment]
@alexInhert - I read it few time, and I still  do not understand what you want to achieve. can you make a  more comprehensive description or maybe a draft PR to explain?
