### ISSUE TITLE
Fully functional DAG Dependencies Graph view

### ISSUE THREAD

**Issue by jjlyr** [apache/airflow#16249]
**Description**

Fully functional DAG Dependencies Graph view to be able to monitor all the Dags with similar features and functions to the existing Dag Graph view 

**Use case / motivation**

The new feature in the UI, DAG Dependencies (https://github.com/apache/airflow/pull/13199), is very good but it does not add any value to monitor the Dags or to see the status of them

![image](https://user-images.githubusercontent.com/47416271/120685068-5af45580-c497-11eb-81ba-6d085de533aa.png)

**Are you willing to submit a PR?**

No

**Related Issues**

No

**Comment by jjlyr** [comment]
@ashb FYI

**Comment by bbovenzi** [comment]
I totally agree we can make Dag Dependencies more useful. But could you list out what "fully functional" would be in your opinion? I don't think we want this to be a super graph view of all dags and tasks. That's a lot of nodes to render and to navigate around.

**Comment by jjlyr** [comment]
@bbovenzi I had though in something like this, if we want to keep DAG Dependencies as it is, create a new view where we need to select the Dags we want to monitor(up to a limit) via drop down list, name-regex or even select the ones we want from DAG dependencies view, and then only those we have selected will be displayed there. Also we will need to add a date selector for this view, and I think this is the tricky bit as the selected Dags may have different schedule runs or the same. We could display the most recent status for the Dags selected for that date(if any).
Later or at the same time, more functionality can be added, for example if we double click in the Dag we could jump into DAG Graph view for that date for that particular Dag.
Please see below an example:

![image](https://user-images.githubusercontent.com/47416271/120887292-e251de00-c5e9-11eb-9a00-36b4ff1a1ff8.png)

Please let me know how you see it and many thanks for your comment

**Comment by bbovenzi** [comment]
Got it.

I think this makes most sense as adding dependency info to the Graph view to get all that detailed info per run. Dag Dependencies remains as an overview of all the dags with dependencies.

**Comment by ManiBharataraju** [comment]
@bbovenzi - I created something exactly similar that the user is requesting in our org prior to an inbuilt version of dag_dependencies was available. You might want to take a look at 
https://github.com/ManiBharataraju/DAG-dependencies
Just as an FYI, before working on this project I never worked on javascript or UI coding. So obviously there might be a lot of redundancy or better ways to do things. I would love to contribute if you could guide me along. It's always fun to learn :)

**Comment by bbovenzi** [comment]
@ManiBharataraju That looks great! I am more than happy to help you out with javascript. Feel free to message me on the airflow slack channel to figure out how to get this moving.

**Comment by ManiBharataraju** [comment]
@eladkal - Sure. I will try to work on it.

**Comment by jscheffl** [comment]
I believe this request is quite outdated since all thius functionality today is being made traceable via Dataset views.
