### ISSUE TITLE
Helm chart: Keda add minReplicaCount

### ISSUE THREAD

**Issue by andormarkus** [apache/airflow#16256]
**Description**
Keda supports [minReplicaCount](https://keda.sh/docs/1.4/concepts/scaling-deployments/) (default value is 0).  It would be great if the users would have the option in the helm chart to overwrite the default value.

**Use case / motivation**
Keda scales the workers to zero if there is no running DAG. The scaling is possible between 0-`maxReplicaCount` however we want the scaling between `minReplicaCount`-`maxReplicaCount `

**Are you willing to submit a PR?**

Yes

**Comment by mik-laj** [comment]
> Are you willing to submit a PR?
> 
> Yes

Feel free to submit PR. I'm happy to help with the review.
