### ISSUE TITLE
Nessus Plugin ID 136929 : Jquery Update to 3.5.0 or greater

### ISSUE THREAD

**Issue by HardikVijayPatel** [apache/airflow#16251]
**What happened**:

There is a security vulnerability identified with Jquery version being used by airflow and needs to be updated. Looks like earlier report issues has no updated, hence filing another one to bring attention to this.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10429

**Comment by mik-laj** [comment]
In the past, someone has tried to update this library. Could you help in this task? Here is PR: https://github.com/apache/airflow/pull/10684#issuecomment-686629969
Without your involvement, it may take us a while to get this done.
