### ISSUE TITLE
Unable to use nested lists in DAG markdown documentation

### ISSUE THREAD

**Issue by Richiecakes** [apache/airflow#16263]
**Apache Airflow version**: 2.0.2

**What happened**:

Tried to use the following markdown as a `doc_md` string passed to a DAG

```markdown
- Example
    -  Nested List
```

It was rendered in the web UI as a single list with no nesting or indentation.

**What you expected to happen**:

I expected the list to display as a nested list with visible indentation.

**How to reproduce it**:

Try and pass a DAG a `doc_md` string of the above nested list.
I think the bug will affect any markdown that relies on meaningful indentation (tabs or spaces)

**Comment by Richiecakes** [comment]
#14564 I suspect this pull request may be the reason since it appears to strip spaces and tabs from every line of the markdown. A minor issue, but as a lover of nested lists, would be great to get them working again 😄

**Comment by Richiecakes** [comment]
![airflow_issue2](https://user-images.githubusercontent.com/6248193/120771475-d31f5180-c551-11eb-97ea-feb73325e029.png)
![airflow_issue1](https://user-images.githubusercontent.com/6248193/120771481-d581ab80-c551-11eb-879e-c4c7c2c168be.png)

This also affects code blocks, which is probably more important than nested lists, but it shows that markdown docstrings are quite limited.

[textwrap.dedent](https://docs.python.org/3/library/textwrap.html#textwrap.dedent) could well be part of the solution here.

**Comment by Dr-Denzy** [comment]
I will try and reproduce this.

**Comment by uranusjr** [comment]
The cause is the same as https://github.com/apache/airflow/issues/16138#issuecomment-851688673. Instead of `str.lstrip()` each line, the parser need to dedent the lines more smartly to preserve internal indentation.

**Comment by ashb** [comment]
`textwrap.dedent` would do the job here wouldn't it?

**Comment by uranusjr** [comment]
I think so (mentioned in the linked comment), but someone needs to actually try.

**Comment by uranusjr** [comment]
I tried, it works well. The linked PR fixed nested lists, but does *not* fix triple-tick code blocks because it’s a non-universal extension syntax. See my comments in the PR for details.
