### ISSUE TITLE
Allow deleting existing spark application before creating new one via SparkKubernetesOperator in Kubernetes 

### ISSUE THREAD

**Issue by yevsh** [apache/airflow#16290]
airflow version: v2.0.2
 
**Description**
calling SparkKubernetesOperator within DAG should delete spark application if such already exists before submitting a new one.

**Use case / motivation**

```
t1 = SparkKubernetesOperator(
    task_id='spark_pi_submit',
    namespace="dummy",
    application_file="spark.yaml",
    kubernetes_conn_id="kubernetes",
    do_xcom_push=True,
    dag=dag,
)
```

After first successful run, next runs fail to submit spark application 

> airflow.exceptions.AirflowException: Exception when calling -> create_custom_object: (409)
> Reason: Conflict
> 
> {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"sparkapplications.sparkoperator.k8s.io "xxx" already exists","reason":"AlreadyExists","details":{"name":"xxx","group":"sparkoperator.k8s.io","kind":"sparkapplications"},"code":409}
> 

**Expected Result**

Delete existing spark application if such exists before submitting new one.

**Comment by grcanosa** [comment]
I also have this problem. 
I think I may be able to contribute to tackle this issue (since I have to do it anyway for my job). 
I will try to set up the contributing environment and then I will come back here.
With new features would it be better to propose a solution or ask design inputs before proposing it. 

Thanks.

**Comment by mingchuno** [comment]
What is the update? I am hitting the same issue. Is there a way to work around?

**Comment by grcanosa** [comment]
Sorry. I couldn't get the development environment working in time. I had to install kubectl in my work pod image and then add a BashOperator with kubectl delete sparkapp as a workaround.

**Comment by mingchuno** [comment]
What work for me is suffix your `SparkApplication` name with `-{{ ds_nodash }}-{{ task_instance.job_id }}` so that it is unique every run.

**Comment by jherrmannNetfonds** [comment]
Hi, I modified the `SparkKubernetesSensor` so it deletes the spark application if it finished successfully. For retry I have `{{ task_instance.try_number }}` for the SparkApplication name so that I still can have a look at the logs.

My proposal is to add an option to the Sensor to delete the spark application via a flag `ALWAYS`, `ON_FAILURE`,`ON_SUCCESS`.
What do you guys think?

**Comment by MightyTedKim** [comment]
@jedcunningham thanks for the tip. could u share a little more for the sensor deleting configs?

**Comment by MightyTedKim** [comment]
I made my yaml like this 

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplicationmetadata:  
#name: sparkapp-test   
name: "sparkapp-test-{{ ts_nodash\|lower }}-{{ task_instance.try_number }}"

spec:
  type: Python
  pythonVersion: "3"

  timeToLiveSeconds: 3600 # delete sparkapplication after an hour
```
still on a dev phase, but works as I expected

**Comment by theesen** [comment]
I would like to contribute to this issue. 
I'd suggest though that the airflow task attaches to the task no matter what the spark state is. The airflow task should also attach to the spark application in k8 if a previous airflow worker had launched the spark app and it is still running.

**Comment by theesen** [comment]
@eladkal Does it make sense if this issue is assigned to me? I have just opened the PR to address this.

**Comment by eladkal** [comment]
@theesen assigned

**Comment by avinovarov** [comment]
Bumping into same issue, would be happy to have it fixed, thanks!
