### ISSUE TITLE
Getting connection aborted error in SimpleHttpOperator Airflow for exactly 5 minutes while making HttpCall.

### ISSUE THREAD

**Issue by pushpaksol** [apache/airflow#16292]
When Airflow SimpleHttpOperator is executed with number of jobs the connection gets aborted at exact 5 minutes.
with exception from pyopenssl:
**OSError: (104,'ECONNRESET')**
and connection error from http_hook.py > sessions.py > adapters.py 
**requests.exceptions.connectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))**

According to [Source Code](https://airflow.readthedocs.io/en/1.9.0/_modules/http_hook.html#HttpHook ) extra_options take dict values where
**_timeout (float or tuple)_ – (optional) How long to wait for the server to send data before giving up, as a float, or a (connect timeout, read timeout) tuple.**

Even I have used **extra_options = {'timeout':600.0}** 
as in [SimpleHttpOperator](https://airflow.readthedocs.io/en/1.9.0/code.html?highlight=requests#airflow.operators.SimpleHttpOperator)

even tried passing **execution_timeout = timedelta(minutes=10)** 
(execution timeout parameter is available for all operators)
which I think any of above options must extend timeout setting to 10 mins, but it doesn't work.

Investigated timeout **_urllib3.util.Timeout_**, and default timeout is set as Global default timeout mentioned as default system timeout.What does that mean and how can we make the connection success with the fix.

**timeout=socket._GLOBAL_DEFAULT_TIMEOUT**

what is **DEFAULT TIMEOUT / GLOBAL_DEFAULT_TIMEOUT** for http requests ???

I don't know what's going wrong there or how could I change this default timeout of 5 mins to 10 mins when running Airflow SimpleHttpOperator

_Originally posted by @pushpaksol in https://github.com/apache/airflow/discussions/16281_

**Comment by potiuk** [comment]
ECONNRESET is issued when the "Other" party broke the connection. So the problem is on your server side not in the client.

**Comment by potiuk** [comment]
See for example here: https://www.quora.com/What-does-%E2%80%9CError-read-ECONNRESET%E2%80%9D-mean

**Comment by pushpaksol** [comment]
Hi @potiuk, It doesn't seem to be an server side issue, because we are able to get the response from server when we ran the job from SOAP UI adding wait time of about 6 mins in backend service and seems that the **connection aborted** error was **NOT** raised and we were getting proper http response.

The issue is seen only when we invoke the job from airflow.

Is there any server configuration which is breaking the connection and that we can change for timeout if it is not from airflow end.

**Comment by potiuk** [comment]
The default setting for timeout is infinite in python/requests/urrlib3 library. I think it's something about your network/connectivity setup. This is not a client timeout. When you have timeout you get different error ("Read timed out."  or "Network unreachable") - depending if it is a read or connect timeout. CONNRESET can be caused by a number of things - firewall, proxy, server timing out the connection.  This is usually a deployment issue

I have no idea what deployment you have, but if you are running your Airflow in GKE then the most likely reason is the stream idle time:

> A Stream idle timeout, whose value is fixed at 5 minutes (300 seconds). This value is non-configurable. HTTP streams become idle after 5 minutes without activity.

https://cloud.google.com/load-balancing/docs/l7-internal

And the solution is to set keep-alive < 5 minutes on your server. So not much Airflow/client can do about it.

**Comment by pushpaksol** [comment]
Hi @potiuk found your reply useful and we guess same is the issue.

- As you mentioned and just to confirm keep-alive time is to be set less than **5 mins** as we made below changes and seen that issue is not fixed. Just want to make sure if the server reboot is required after making changes in the sysctl.conf file?

- Also below configuration has these keep alive total timeout less than 5 minutes. Just want to make sure these settings are fine or let us know what could be the ideal settings parameters to resolve the 5 minutes Connection aborted error
When added to /etc/sysctl.conf as mentioned [here](https://webhostinggeeks.com/howto/configure-linux-tcp-keepalive-setting/
)
**net.ipv4.tcp_keepalive_time = 120
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6**

- Also, we tried figure out that another file httpd.conf has these keep alive changes but we couldn't find that file in the server path. Any idea where this file could be located ? 

Please confirm

**Comment by potiuk** [comment]
I think it's the matter of your server or worker machines/network/not really Airflow. It's not really possible for me to help with your deployment configuration.
