### ISSUE TITLE
Add data_interval_start and data_interval_end columns to DagRun table, and set them when creating DagRuns.

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#16304]
Create a single DB Migration for the following:

- [ ] Use `DagModel.schedule_interval` to calculate `DagRun.data_interval_start` and `DagRun.data_interval_end`.
- [ ] Once`DagRun.data_interval_end` is calculated, use it's value as `DagRun.schedule_date` which will be a "replacement" for `DagRun.execution_date` as mentioned in [AIP-39](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-39+Richer+scheduler_interval#AIP39Richerscheduler_interval-RenameDagRun.execution_datetoschedule_date) (Keep `execution_date` - don't remove it for backwards compatibility.)

**Comment by uranusjr** [comment]
What should we set the values to for DAGs with `schedule_interval` either `None` or `"@once"`? They don’t really have a data interval so both `(execution_date, execution_date)` and `(execution_date, None)` feels sensible to me.
