### ISSUE TITLE
Scheduler fails with Airflow initdb not finishing

### ISSUE THREAD

**Issue by ashmgln** [apache/airflow#16319]
### Environment:
Airflow v1.10.10
Helm Deployment

### Description:

I'm trying to enable git-sync and serialization on my exiting airflow setup. I added the config for git, in the values.yaml, also, enabled the flag "serializedDAGs" & "storeDAGs" as true. But when I deploy it on my Kubernetes setup using a helm upgrade, the scheduler gets stuck after a log involving airflow initdb. The postgres setup that I'm using seems to be working fine. Unable to understand, what to do next. The same setup is running fine in another cluster.
<img width="1411" alt="Screenshot 2021-06-07 at 6 02 49 PM" src="https://user-images.githubusercontent.com/20070386/121144650-d2413500-c85b-11eb-9a60-374631f00df3.png">

**Comment by potiuk** [comment]
Airflow 1.10 is about to reach end-of-life (June 17). I strongly suggest to migrate to 2.1 and see if your problem will be fixed there.
