### ISSUE TITLE
SSH and SFTP connection param alignment

### ISSUE THREAD

**Issue by hx-markterry** [apache/airflow#16323]
**Apache Airflow version**:

2.1.0

**Environment**:

**What happened**:

With the SSH hook you can specify a private key as a string using the `private_key` param:

https://github.com/apache/airflow/blob/main/airflow/providers/ssh/hooks/ssh.py#L138

With the SFTP hook you can only specify a private key path using the `private_key` param:

https://github.com/apache/airflow/blob/main/airflow/providers/sftp/hooks/sftp.py#L108

This means that you can not provide a private key string to a SFTP connection, only a path to a file.

**What you expected to happen**:

As the SFTP hook already has the SSH hook as a base class, then changing the `private_key` param to mean a string rather than a file, and using the `key_file` like the SSH hook does, would allow the SFTP hook to support private key strings and files, and would reduce some code in the SFTP hook.

**How to reproduce it**:

Private key strings are not supported in the SFTP connection.

**Anything else we need to know**:

Example of SSH connection params:
https://airflow.apache.org/docs/apache-airflow-providers-ssh/stable/connections/ssh.html

Example of SFTP connection params:

https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/connections/sftp.html

**Comment by eladkal** [comment]
fixed by https://github.com/apache/airflow/pull/18988
