### ISSUE TITLE
Pause, unpause airflow DAGs with a justification, and enable back datetime.

### ISSUE THREAD

**Issue by AFGhazy** [apache/airflow#16349]
**Description**

Add justification reason before pausing a DAG, and the UI should ask for unpause deadline datetime.

**Use case / motivation**

Sometimes we go to the Airflow UI to find out that a DAG is disabled but we can't link back to why it's paused, and who paused it.

If we implemented this change, it will be much easier to know who disabled the DAG, why, and when the DAG will be unpaused again.

**Are you willing to submit a PR?**

**Related Issues**

**Comment by kaxil** [comment]
cc @bbovenzi :)

**Comment by eladkal** [comment]
Duplicated of https://github.com/apache/airflow/issues/15675

you can know who paused/unpaused it. It appears in the log:
![Screen Shot 2021-06-09 at 14 05 50](https://user-images.githubusercontent.com/45845474/121343885-d046a700-c92b-11eb-9b75-bbe1ad65e717.png)

**Comment by AFGhazy** [comment]
It's not just a duplicate, we want to put a time for unpausing too.

**Comment by eladkal** [comment]
The time of unpausing/pausing the the event timestamp (Dttm column)

**Comment by AFGhazy** [comment]
In here, I meant setting a time for unpausing the DAG automatically, it's not about retrieving these times.

**Comment by eladkal** [comment]
> In here, I meant setting a time for unpausing the DAG automatically, it's not about retrieving these times.

Do you mean you want to schedule when a DAG will enter a Pause/Active mode?
