### ISSUE TITLE
What Can I Do If Error AttributeError: module 'airflow' has no attribute 'startswith' Is Reported After the command 'airflow db init' is executed

### ISSUE THREAD

**Issue by keep-forward** [apache/airflow#16346]
The procedure is as follows:
1. export AIRFLOW_HOME=~/airflow
2. pip install apache-airflow
3. airflow db init
the error is as follows:
Traceback (most recent call last):
  File "~/python3.6/site-packages/pep562/__init__.py", line 238, in __getattr__
    return getattr(self._module, name)
AttributeError: module 'airflow' has no attribute 'startswith'

Ask for help. Thank you.

**Comment by kaxil** [comment]
What version of `pep562` are you using?

```
pip show pep562
```

Using the following command to install `apache-airflow`:

```shell
AIRFLOW_VERSION=2.1.0
PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
pip install "apache-airflow[async,postgres,google]==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
```

**Comment by keep-forward** [comment]
version of pep562 is 1.0

**Comment by keep-forward** [comment]
I switched a new environment and installed airflow, now it works. Thank you for your answer.
