### ISSUE TITLE
Dag graph aligned at bottom when expanding a TaskGroup

### ISSUE THREAD

**Issue by enrique-ayala** [apache/airflow#16359]
**Apache Airflow version**:  2.1.0

**Kubernetes version (if you are using kubernetes)** : v1.17.5

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux airflow-scheduler-5c6fcfbf9d-mh57k 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 GNU/Linux 
- **Install tools**:
- **Others**:

**What happened**:
When expanding a TaskGroup, graph is placed at bottom ( it disappears from current display) . 

Graph collapsed placed at top: 
![2021-06-07 11_36_52-collapsed](https://user-images.githubusercontent.com/10963531/121449654-db1b2f00-c95f-11eb-89df-a458aadad422.png)

Graph at bottom when clicking on a TaskGroup: 
![2021-06-07 11_36_52-expanded](https://user-images.githubusercontent.com/10963531/121449698-eec69580-c95f-11eb-8750-2e96b04f7628.png)

**What you expected to happen**:
Maintain graph at top , to avoid a scroll down.

**Comment by bbovenzi** [comment]
This is most likely an issue with how the automatic zoom is handled. I'll check it out soon.

**Comment by bbovenzi** [comment]
Related to #13044
