### ISSUE TITLE
Operator and Hook for Amazon Redshift Statement Execution and Federated User Authentication

### ISSUE THREAD

**Issue by Brooke-white** [apache/airflow#16355]
**Description**

We should provide support for users to authenticate with Amazon Redshift via IAM or Identity Provider (e.g. Ping, Okta) and execute statements.

[redshift_connector](https://github.com/aws/amazon-redshift-python-driver), the official DB-API Python driver for Amazon Redshift, supports authenticating via IAM or Identity Provider as well as statement execution.

To satisfy this proposal, the following tasks must be completed

- Development of a Hook, proposed name `RedshiftStatementHook`, which depends on redshift_connector  and a sqlalchemy dialect
- Development of an Operator, proposed name `RedshiftOperator`, which allows users to execute SQL code against Amazon Redshift

**Use case / motivation**

Many users need to access Amazon Redshift using temporary credentials or through an Identity Provider. These is an opportunity to improve the workflow experience for these users, by streamlining the authentication process.

Currently users need to use the `PostgresOperator` to execute queries against their Amazon Redshift cluster. This is not ideal as the `PostgresHook` uses `psycopg2` which afaik does not support using IAM authentication or 3rd party Identity Providers.

There is an existing Hook, `RedshiftHook`, built using boto3, but it does not support statement execution.

**Are you willing to submit a PR?**

Yes

**Related Issues**

No

**Comment by potiuk** [comment]
Would you be working on it @Brooke-white ?

**Comment by Brooke-white** [comment]
@potiuk Yes
