### ISSUE TITLE
Airflow 2.0.2 export and import variables from CLI has an issue

### ISSUE THREAD

**Issue by HashSalmon** [apache/airflow#16354]
**Apache Airflow version**: Airflow 2.0.2

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`): 3.10.0-1062.12.1.el7.x86_64
- **Install tools**: rh-python36
- **Others**:

**What happened**:

After exporting the variables into a json file by running `airflow variables export /some_path/var.json`, when I import the variables from CLI by running `airflow variables import  /some_path/var.json`. All of the variables will be messed up when you check them on the UI page. However, if you import the variables from airflow webUI, it works fine.

**What you expected to happen**:

The airflow variables export CLI should work properly.

**How to reproduce it**:
- Create some variables in your airflow env.
- Run `airflow variables export /some_path/var.json` to export the vars.
- Delete all of the variables or run `airflow db reset`
- Run `airflow variables import  /some_path/var.json`
- Check the new imported variables, the values of the variables are wrong.
- Go do the web UI -> click Admin -> click Variables -> choose files -> choose the var.json -> click import variables.
- All of the vars shows correctly with correct values.

**Anything else we need to know**:

N/A

**Comment by potiuk** [comment]
Could you please provide examples of "wrong" ? just few examples of variables that you got messed up and how.
