### ISSUE TITLE
After upgrade from 2.0.1 to 2.1.0 the MsSQLToS3Operator has stopped working when uploading a multipart to S3

### ISSUE THREAD

**Issue by hhagblom** [apache/airflow#16351]
I think that the issue is primarily in the smart_open library that is used, however this worked fine in the 2.0.1 version.

https://github.com/RaRe-Technologies/smart_open/issues/623

If one looks at the stacktrace in the referenced issue the `io.UnsupportedOperation: read` occurs when processing a logstatement with `airflow/utils/log/secrets_masker.py`. I'm not quite sure if it is the secrets_masker that is doing something it shouldn't or if the problem is within `smart_open` entirely.

**Comment by uranusjr** [comment]
I think #16118 should cover this.
