### ISSUE TITLE
Tree view shown incorrect dag runs 

### ISSUE THREAD

**Issue by dkhome** [apache/airflow#16367]
Apache Airflow version: 2.1.0

On Tree view, switch to 50 Runs, and the view is broken:
![screenshot](https://user-images.githubusercontent.com/16779368/121520434-93e27c00-c9fb-11eb-8625-65c07a1ac770.png)

**Comment by eladkal** [comment]
possibly same/related to https://github.com/apache/airflow/issues/16238

**Comment by bbovenzi** [comment]
Just replicated this one. It is an issue with the auto-refresh. Working on a fix now.
