### ISSUE TITLE
_PIP_ADDITIONAL_REQUIREMENTS environment variable of the container image cannot install more than one package

### ISSUE THREAD

**Issue by MWargelin** [apache/airflow#16363]
**Apache Airflow version**: 2.1.0

**Environment**: Docker

**What happened**: I tried to install more than one pip packages using the _PIP_ADDITIONAL_REQUIREMENTS enviroment variable when running Airflow image built using the latest Dockerfile. My _PIP_ADDITIONAL_REQUIREMENTS was set to "pandas scipy". The result was `ERROR: Invalid requirement: 'pandas scipy'`

**What you expected to happen**: I expected both pandas and scipy to install without errors. I believe that the image is now trying to install one package called "pandas scipy", which doesn't exist. I believe by removing the double quotation marks surrounding the ${_PIP_ADDITIONAL_REQUIREMENTS=} from this line of code would solve the issue: https://github.com/apache/airflow/blob/main/scripts/in_container/prod/entrypoint_prod.sh#L327

**How to reproduce it**: Using image built using the latest Dockerfile, try to run the image with `docker run --rm -it --env _PIP_ADDITIONAL_REQUIREMENTS="pandas scipy" image:tag`

**Comment by uranusjr** [comment]
I think we shouldn’t quote this (or should split the string into an array first)

https://github.com/apache/airflow/blob/7744f05997c1622678a8a7c65a2959c9aef07141/scripts/in_container/prod/entrypoint_prod.sh#L327
