### ISSUE TITLE
Pass triggering user information to DAG

### ISSUE THREAD

**Issue by yupbank** [apache/airflow#16373]
**Description**

It would be very useful if we can pass triggering user information to DAG. So that we can bring over the info to the downstream system for security auditing purpose 
**Use case / motivation**

Expose some macro in the DAG, so user can use the trigger user info at will

**Are you willing to submit a PR?**

If someone can point me in the right direction 
**Related Issues**

No

**Comment by eladkal** [comment]
In manual jobs there is a specific user who triggered it - that doesn't exist for scheduled jobs.
What value are you expecting to have for scheduled jobs?

**Comment by yupbank** [comment]
I'm looking for the manual jobs actually, currently, we can pass the info through the `dag_run.conf` in `cli` use case. 
but the web UI `dag_run.conf` is a bit complicated. I'm wondering if it makes sense to add some `current_user` field in the default conf https://github.com/apache/airflow/blob/main/airflow/www/views.py#L1490 here
something like `default_conf=json.dumps(dict(current_user=current_user.user.username))` 

it would be amazing if a default default_conf can be configured for all CLI and web UI submissions. Since airflow would perform checks on the triggering user anyway. why not pass it in to the DAG so default_conf actually have some default info

**Comment by yupbank** [comment]
e.g., i could define a BashOperator that login to a web server, in which all the credentials are managed by connections for sure. but it would also be nice to tell the web server that who triggered the job manually if that happened

**Comment by uranusjr** [comment]
Not commenting on whether this is a good idea or not, IMO a scheduled job could be categorised under either the DAG owner (since they scheduled the DAG) or `None`.

**Comment by yupbank** [comment]
maybe let me re-state the feature: allow the user to customize the `DAG.default_conf` in the web console?

**Comment by santosh-d3vpl3x** [comment]
`airflow.models.log.Log` should already contain the information about trigger. Here the owner field indicates user performing actions.

You can listen on `after_insert` in sql alchemy to route this info via a simple airflow plugin.

**Comment by yupbank** [comment]
i'm not sure i follow, how would the plugin pass on the `after_insert` info to a DAG execution?

**Comment by MinusYuan** [comment]
> In manual jobs there is a specific user who triggered it - that doesn't exist for scheduled jobs. What value are you expecting to have for scheduled jobs?

Hi, I want to ask which variable/what kind of method can I use to get this specific user when manual trigger happens?
Now, I also need this to know which user trigger.
