### ISSUE TITLE
CLI Connection import command not work

### ISSUE THREAD

**Issue by ravog** [apache/airflow#16374]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/connection_command.py", line 272, in _import_helper
key: value for key, value in conn_values.items() if key in allowed_fields
AttributeError: 'Connection' object has no attribute 'items'

I just use the file generated from connections export command

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by DDullahan** [comment]
I met the same problem and checked the source code.

In airflow/cli/commands/connection_command.py it loads connections file as a dict, conn_id for key, Connection type for value.
After that, it calls items() on Connection type which doesn't have.
   
```python
def _import_helper(file_path):
    """Helps import connections from a file"""
    connections_dict = load_connections_dict(file_path)
    with create_session() as session:
        for conn_id, conn_values in connections_dict.items():
            # type(conn_id) is str
            # type(conn_values) is airflow.models.connection.Connection

            if session.query(Connection).filter(Connection.conn_id == conn_id).first():
                print(f'Could not import connection {conn_id}: connection already exists.')
                continue

            allowed_fields = [
                'extra',                                                                                                              
                'description',
                'conn_id',
                'login',                                                                                                                
                'conn_type',
                'host',                                                                                                                
                'password',
                'schema',
                'port',
                'uri',                                                                                                                 
                'extra_dejson',                                                                                                     
            ]
            filtered_connection_values = {
                key: value for key, value in conn_values.items() if key in allowed_fields
            }
            connection = _create_connection(conn_id, filtered_connection_values)
            session.add(connection)
            session.commit()
            print(f'Imported connection {conn_id}')      
```

I guess in the previous version, method load_connections_dict just loads connections file as a json object. In this situation, this code can run correctly.

Maybe you should use `airflow connections create` for now.

**Comment by uranusjr** [comment]
Weirdly enough, from what I can tell with `git blame`, `load_connections_dict` has always returned a Connection object during the entire lifetime of this command (only two months old; `load_connections_dict` was last changed 8 months ago). Maybe @natanweinberger could provide some background why the implementation was made this way; there was actually a unit test, but the `load_connections_dict` mock is configured to not do the right thing from what I can tell. (See #15177)

**Comment by natanweinberger** [comment]
Yes, that's right. I made a mistake in the unit test. This was just fixed in #15425 this morning!

**Comment by uranusjr** [comment]
You borrowed [Guido’s time machine](http://www.catb.org/jargon/html/G/Guido.html) for this one, didn’t you 😉 So I think this can be closed?

**Comment by natanweinberger** [comment]
😁

Yes, it can be closed!
