### ISSUE TITLE
Update template context to deprecate `execution_date` and add new "interval" properties

### ISSUE THREAD

**Issue by ashb** [apache/airflow#16372]
As per the AIP, we want to deprecate some of the current variables in the template context, as well as add some new ones

When one of these deprecated variables is accessed we want to issue a DeprecationWarning., Getting this to show up the location of the dag file may be hard, so we make to include the dag_id and task_id in the warning.

**Comment by uranusjr** [comment]
> When one of these deprecated variables is accessed we want to issue a DeprecationWarning

Is there an example of this?

**Comment by Dr-Denzy** [comment]
This is a test comment to test my code. To be deleted soon after.

**Comment by uranusjr** [comment]
Figured it out in #16352.
