### ISSUE TITLE
DB migration: XCom table from `execution_date` to `run_id`

### ISSUE THREAD

**Issue by ashb** [apache/airflow#16370]
Migrate the `execution_date` column to `run_id`, and add a check to ensure no "dangling" in the same place as #16302.

This can be done by editing the same migration that #16302 added, or as a separate migration.

**Comment by Dr-Denzy** [comment]
Test comment - To be deleted

**Comment by uranusjr** [comment]
Adding some backrefs

https://github.com/apache/airflow/pull/17719#discussion_r692723888
https://github.com/apache/airflow/pull/17719#discussion_r692726838

**Comment by ashb** [comment]
Fixed by https://github.com/apache/airflow/pull/20975
