### ISSUE TITLE
SageMaker operators return non-serializable value

### ISSUE THREAD

**Issue by olivermeyer** [apache/airflow#16386]
**Apache Airflow version**: 1.10.15, 2.1.0

**What happened**:
The `execute` methods of all SageMaker operators return a dictionary which contains `datetime` objects (e.g. [here](https://github.com/apache/airflow/blob/69a1a732a034406967e82a59be6d3c019e94a07b/airflow/providers/amazon/aws/operators/sagemaker_training.py#L120) but affects all operators). Execution fails consistently, throwing `TypeError: Object of type 'datetime' is not JSON serializable`.

There is already a ticket for this issue [here](https://issues.apache.org/jira/browse/AIRFLOW-3772), I am opening this to add visibility in GitHub and reference it in an eventual PR.

**What you expected to happen**:
The operator's `execute` should return only serializable values. I suggest that these operators should return only the name of the job, instead of the full description, which can then be used elsewhere to pull further information about the job if needed.

**Comment by uranusjr** [comment]
Since we already implements custom (de-)serialisation in `airflow.utils.json`, we should use it in `XCom.serialize_value()` (and add a `AirflowJsonDecoder` for `XCom.deserialize_value()`).

**Comment by olivermeyer** [comment]
That makes sense and seems simple enough. I'm happy to take a shot at it in the next few days.

**Comment by c-thiel** [comment]
@olivermeyer do you know what the state on this is? Looking at #8703 I don't think there is going to be a solution outside of this operator.

**Comment by olivermeyer** [comment]
> @olivermeyer do you know what the state on this is? Looking at #8703 I don't think there is going to be a solution outside of this operator.

I ended up forking the operators and using my own version. I don't know if there's a plan to address this, perhaps @eladkal or @kaxil can shed some light?

**Comment by potiuk** [comment]
> I ended up forking the operators and using my own version. I don't know if there's a plan to address this, perhaps @eladkal or @kaxil can shed some light?

@olivermeyer - I think the easiest way to get it released is to contribute your fork version back. Do you need some guidance on how to do it? I will be happy to review and merge it. Airflow is created by more than 1700 contributors, and you can easily become one of them - and it 's also great if you can clear the path to others!

**Comment by olivermeyer** [comment]
> @olivermeyer - I think the easiest/fastest way to get it released is to contribute your fork version back. Do you need some guidance on how to do it? I will be happy to review and merge it. Airflow is created by more than 1700 contributors, and you can easily become one of them - and it 's also great if you can clear the path to others!

I'm not sure my fork will work for others, since I bypassed the problem by having the operator return just the model name. I think my initial PR https://github.com/apache/airflow/pull/16395 is worth considering as it's a bit more generic, although it's a bit old now and might need to be updated.

**Comment by uniquejtx** [comment]
what's the solution here? I am running  a SageMakerProcessingOperator Airflow task the processing job executed successfully but I got the error "ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config., TypeError: Object of type datetime is not JSON serializable" .   How should I get away from this ? I have downstream task depend on success of SageMakerProcessingOperator

**Comment by potiuk** [comment]
> what's the solution here? I am running a SageMakerProcessingOperator Airflow task the processing job executed successfully but I got the error "ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config., TypeError: Object of type datetime is not JSON serializable" . How should I get away from this ? I have downstream task depend on success of SageMakerProcessingOperator

a) set `do_xcom_push` to False:  https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/baseoperator/index.html

b) derive your own custom operator from the SageMarkerOperator and return nothing (or converte return value to serializable. Smth like: 

```
class MyOperator(SageMakerProcessingOperator):
    def execute():
       ret = super().execute()
      serializable_return = .....  # convert it to serializable
      return (serializable_return)
```

c) enable pickle in Airflow configuration https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html?highlight=pickle#enable-xcom-pickling

d) correct it in the operator and contribute it back (this is by far the best idea).

**Comment by olivermeyer** [comment]
@potiuk I opened a PR some time ago (https://github.com/apache/airflow/pull/16395) but was told to wait for some other PRs which were, by the looks of it, never merged. Are you able to tell me if my PR is relevant? It seems to me that it would fix the issue. If that's the case, I can spend some time updating my solution and opening another PR. I just don't want to waste time if it's clear from the start that another solution is preferred.

**Comment by potiuk** [comment]
@kaxil  - do you think the reasons from https://github.com/apache/airflow/pull/16395 stil hold, or is @olivermeyer free to continue with the PR (I think it should be no problem to continue, but I would like to verfiy with you).

**Comment by Taragolis** [comment]
Fixed by: https://github.com/apache/airflow/pull/23628
