### ISSUE TITLE
API for marking the running DAG state to success or failure

### ISSUE THREAD

**Issue by MAHESH-HASBI** [apache/airflow#16412]
**Description**

Like how we are able to turn OFF the DAG or turn ON the DAG using airflow API, we need a feature where we can mark the running DAG as FAILED or SUCCESS. This feature is needed for us.

I see two methods `set_dag_run_state_to_failed` and `set_dag_run_state_to_success` already present in code like how we want. It would be good if we have an API for it.

API's something like below
GET /api/experimental/dags/<DAG_ID>/dag_runs/<string:execution_date>/SUCCESS
GET /api/experimental/dags/<DAG_ID>/dag_runs/<string:execution_date>/FAILED

**Use case / motivation**
In my application, airflow DAGs are getting stuck in a running state for some reason, we want to mark them as FAILED or SUCCESS and trigger a fresh DAG run, and sometimes while the DAG is in running state we want to abort it based on some predefined conditions. Currently, we are doing this by using airflow UI but we want to use API instead.

**Are you willing to submit a PR?**

No, I'm not willing to contribute.

**Related Issues**

**Comment by uranusjr** [comment]
I wouldn’t use GET for this. We shouldn’t add more stuff to `experimental` either.

A `PATCH /api/v1/dags/{dag_id}/dagRuns/{dag_run_id}` with `{"state": STATE_NAME}` is probably appropriate.

**Comment by potiuk** [comment]
Yep. Experimental API is deprecated, but the REST API could be extended.

@MAHESH-HASBI It would be great if you could actually contribute - this way you could make sure it happens faster. Airflow is a community managed project and it would be great if more people who use Airflow contribute to it. The committers here are willing to help with reviews, directions, etc. so maybe a good idea for you to add such feature.

**Comment by sollozzo2** [comment]
Hi, I am willing to work on this as my first issue.

**Comment by sollozzo2** [comment]
I've made a few commits on my branch - [https://github.com/sollozzo2/airflow/](link to my branch)
I changed three files in order to add this function:
airflow/api_connexion/openapi/v1.yaml - OpenAPI definition to link endpoint to the backend function
airflow/api_connexion/endpoints/dag_run_endpoint.py - file for implementing backend functions
airflow/api_connexion/schemas/dag_run_schema.py - definition of parameters to submit to the API? I could be wrong
I've written some preliminary code but it will need testing and definitely modifying.

**Comment by uranusjr** [comment]
It would be easier to discuss eh implementation  if you could post your branch as a draft pull request.

**Comment by alex-astronomer** [comment]
Since the existing PRs have been marked as Closed and no code has been merged, also there is no Assignee, I'm going to take this on unless someone objects.

**Comment by alex-astronomer** [comment]
@potiuk Can you add me as the Assignee for this Issue?

**Comment by uranusjr** [comment]
Go ahead.

**Comment by alex-astronomer** [comment]
Code has already been submitted to solve this issue.  Here is the PR that can close this request: https://github.com/apache/airflow/pull/17839

**Comment by ephraimbuddy** [comment]
Closed by #17839
