### ISSUE TITLE
API for making the success state backfill instance to rerun in airflow-1.10.11

### ISSUE THREAD

**Issue by yyhecust** [apache/airflow#16427]
**Description**
Like how we are able to rerun the backfill instance of failed status using airflow API, we need a feature where we can rerun the backfill instance of success status. This feature is needed for us.

**Use case / motivation**
In my application, we use airflow-1.10.11. Sometimes, we need to make some changes to the DAG files so that require to rerun the backfill instances to get new data. But airflow-1.10.11 only offers rerun of failed tasks for the backfill function, and we want it will also support rerun of successful tasks.

**Are you willing to submit a PR?**
Yes, I'm willing to.

**Related Issues**

**Comment by potiuk** [comment]
Aiflow 1.10 reaches end-of-life June 17 (in 3 days). Currently we are in the mode of implementing only critical fixes to 1.10. I heartly recommend to migrate to Airflow 2 at earliest convenience.

Closing this one.
