### ISSUE TITLE
API to set the state of the task instance to the specified state (airflow-1.10.11)

### ISSUE THREAD

**Issue by yyhecust** [apache/airflow#16429]
**Description**
we need a feature where we can set the state of the task instance to the specified state. 

**Use case / motivation**
In my application, some task instances have been scheduled for a long time, we want to put it in the failed state. Currently, we are doing this by using airflow Web UI but we want to use API instead.

**Are you willing to submit a PR?**
Yes, I'm willing to.

**Related Issues**
#16412

**Comment by potiuk** [comment]
Aiflow 1.10 reaches end-of-life June 17 (in 3 days). Currently we are in the mode of implementing only critical fixes to 1.10. I heartly recommend to migrate to Airflow 2 at earliest convenience.

I believe the new REST API in 2.0 is the best to have it. There is no such API yet there but there is already an isssue #16412 created for that.

Closing as duplicate.
