### ISSUE TITLE
Restart Airflow scheduler and retain historical data

### ISSUE THREAD

**Issue by bencaine-integral** [apache/airflow#16439]
Some administrative actions, like changing a value in my `airflow.cfg` file, require a restart of the scheduler for changes to take effect. However, if I were to do that, all the historical data from my past runs would be deleted. Is there any way to restart the scheduler while still preserving this historical data?

**Comment by kaxil** [comment]
Restarting Airflow scheduler does not remove the old Metadata. That metadata about historical DagRuns and Task instances is stored in Airflow Metadata DB (Postgres, MySQL etc) as shown in https://airflow.apache.org/docs/apache-airflow/stable/concepts/overview.html

You should use a managed DB service like Cloud SQL or AWS RDS and not use ephemeral storage like Postgres in Kubernetes Pod etc.

**Comment by bencaine-integral** [comment]
This was a mistake on my end. I can stop the webserver and restart it without any loss of data. Thank you and sorry for the inconvenience!
