### ISSUE TITLE
Documentation landing page links in the section headers are hard to find

### ISSUE THREAD

**Issue by peter-gergely-horvath** [apache/airflow#16431]
**Apache Airflow version**:  N/A - current documentation

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: N/A

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**: 
I had spent quite some time looking for the documentation pages on https://airflow.apache.org/docs/ till I realized that actually the section headers are the links to the documentation pages. This is highly counter-intuitive (a link on a section header is normally a _permalink to the section header_ and not another page.) and is generally a **terribly bad UI user experience**. 
For the first glance it seems Airflow does not have any documentation apart from the landing page!  

**What you expected to happen**:
Documentation pages should be intuitive to navigate. One would normally expect proper links to other sections of documentation. For example: "Read the Documentation >>" as link text at the end of each section or something similar.     

![airflow_documentation_page](https://user-images.githubusercontent.com/15800802/121871981-0bb6ec00-cd05-11eb-96b0-d3ad12d4426b.png)

**How to reproduce it**:
Get someone new to the project look at the documentation landing page with a fresh pair of eyes and ask them to locate the links to the main documentation. 

**Anything else we need to know**:

**Comment by potiuk** [comment]
Could you please propose a better solution @peter-gergely-horvath ? Maybe find a few examples of other sites where things are more intutitive? I think we are so used to it, that we do not see it as a problem, but you are probably (as a person who had problems with it) the best person to tell us what would be better?

**Comment by uranusjr** [comment]
I’ve always found the current layout unintuitive. Maybe we can add a single list item under *Apache Airflow* that says `apache-airflow` like the provider packages? That would be a more obvious target to click on.

**Comment by uranusjr** [comment]
Something like this

![image](https://user-images.githubusercontent.com/605277/121879359-55242d00-cd3f-11eb-84c0-4626529f356f.png)

**Comment by peter-gergely-horvath** [comment]
I could imagine something like this, with "Read the documentation" being a link to the corresponding sub-page:

![airflow_documentation_page2](https://user-images.githubusercontent.com/15800802/121880003-c9de7380-cd0d-11eb-829f-fb0b2cda0cfa.png)

**Comment by potiuk** [comment]
Better indeed. Would you like to make PR with that change ? That might be a nice first contribution and it is very simple to do - just follow this link https://github.com/apache/airflow-site/edit/main/landing-pages/site/content/en/docs/_index.md

**Comment by peter-gergely-horvath** [comment]
OK, I've created my first AirFlow pull request :)

https://github.com/apache/airflow-site/pull/434
