### ISSUE TITLE
Key errors on importing DAGs

### ISSUE THREAD

**Issue by saul-data** [apache/airflow#16457]
We are receiving import errors on environment variables that we use inside our DAGs - used to switch between local docker compose and our staging environment. Not sure why?

```
Broken DAG: [/opt/airflow/dags/xyz.py] Traceback (most recent call last):
  File "/opt/airflow/dags/xyz.py", line 16, in <module>
    if os.environ["ENVIRONMENT"] == 'staging':
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'ENVIRONMENT'
```

**Comment by uranusjr** [comment]
It means you did not set the `ENVIRONMENT` variable in the environment that the scheduler process is running in.

**Comment by saul-gush** [comment]
I see - OK I got it to work thanks @uranusjr 

![image](https://user-images.githubusercontent.com/63714857/122053004-3e80e300-cdde-11eb-87b3-7d6326c2cef0.png)
