### ISSUE TITLE
Failed to fetch log file from worker. Unsupported URL protocol ''

### ISSUE THREAD

**Issue by raajpackt** [apache/airflow#16478]
```
*** Log file does not exist: /opt/airflow/logs/my-task/my-task/2021-06-15T14:11:33.254428+00:00/1.log
*** Fetching from: http://:8793/log/my-task/my-task/2021-06-15T14:11:33.254428+00:00/1.log
*** Failed to fetch log file from worker. Unsupported URL protocol ''
```
Getting this error when i run newer dags. My earlier dags are working fine. This error is very recent. Earlier I had a different error fixed by [this one]( https://issues.apache.org/jira/browse/AIRFLOW-4922) which resulted in the above error.
I am using `apache/airflow:2.1.0` docker image.

**Apache Airflow version**: 2.1.0

**Environment**:

- **Cloud provider or hardware configuration**: AWS ec2 instance

**Comment by niklasbeierlarc** [comment]
I think this might be addressed in https://github.com/apache/airflow/pull/16768.

**Comment by uranusjr** [comment]
Yup. Thanks for identifying this! I’ll close this so discussions can happen in one thread.
