### ISSUE TITLE
dag.py#handle_callback relays on an ordered list of TaskInstances returned by #get_task_instances

### ISSUE THREAD

**Issue by lehmann** [apache/airflow#16481]
**Apache Airflow version**: 2.1.0 (

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.15.10

**Environment**: MacOS

- **Cloud provider or hardware configuration**: not-relevant-here
- **OS** (e.g. from /etc/os-release): MacOS BigSur
- **Kernel** (e.g. `uname -a`): 20.5.0 Darwin Kernel
- **Install tools**:
- **Others**:

**What happened**:
When running some failing task, from time to time, Airflow call `on_failure_callback` with wrong task's infos like task_id, state and so on.

**What you expected to happen**:
The callback must be called with the right context for finished task.

**How to reproduce it**:

`
def send_failure_message(self, context: [Any]):
    task_instance: TaskInstance = context['task_instance']
    partition: str = context['ds']
    message = f'"{task_instance.dag_id}.{task_instance.task_id}" has failed for partition: {partition}'
    print(message)

with DAG('test_dag',
         start_date=datetime(2021, 6, 14),
         schedule_interval='0 0 * * *',
         on_failure_callback=send_failure_message,
         default_args={
             'retries': 1,
             'retry_delay': timedelta(minutes=1)
         }) as dag:

    run_this_last = DummyOperator(task_id='run_this_last', dag=dag)

    run_exit = BashOperator(task_id='run_exit', bash_command='exit 1', dag=dag)
    [run_exit] >> run_this_last

    run_this_first = DummyOperator(task_id='run_this_first', dag=dag)
    run_this_first >> [run_exit]
`

**Anything else we need to know**:
The script [dag.py#865](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L865) is getting the full list of TaskInstances from [dagrun.py#306](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L306) and dag.py assumes the list is ordered by `execution_date`. It is true for [dag.py](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L1059) and [baseoperator.py](https://github.com/apache/airflow/blob/main/airflow/models/baseoperator.py#L1204) implementations, but not for `dagrun.py`.

**Comment by msumit** [comment]
@lehmann the `on_failure_callback` you are applying at the DAG level, so it'll be called when the dag run fails & it'll randomly pick one TI for the context. You need to define the `on_failure_callback` at the task level & probably you can set that into `default_args` as well.
