### ISSUE TITLE
Potential security leak in logging connection 

### ISSUE THREAD

**Issue by MM-Lehmann** [apache/airflow#16483]
**Apache Airflow version**: 2.1.0

**Environment**:

- **Cloud provider or hardware configuration**: any
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Kernel** (e.g. `uname -a`): 5.4.0
- **Install tools**: airflow official docker container, python 3.8.10
- **Others**:

**What happened**:
When details about a connection are printed to log, username and password might be exposed indirectly.
e.g. in `INFO - Using connection to: id: NEXTCLOUD. Host: http://***-nextcloud/remote.php/dav/files/***, Port: None, Schema: None, Login: ***, Password: ***, extra: {}` the connection is referring to the host `http://test-nextcloud`, the user `airflow` and the password `test`.

However, not only the `Login` and `Password` fields seem to be hidden, but everything with their content. In this case, coincidentally, they match some strings in the URI of the corresponding service.  In rare but possible cases (with potentially insecure credentials), this could expose the credentials indirectly. It seems like there is a regex rule in place which tries to mask credentials in the host string as well.

**What you expected to happen**:

Host string should not be modified. If `user:password@...` information is passed in the host string, there should be a warning instead when creating the connection.

**How to reproduce it**:

- create a connection with the following parameters:
  host: http://test-nextcloud/remote.php/dav/files/airflow
  login: airflow
  password: test

- create and run a dag/task which uses the connection
- observe the log output (log level: INFO)

**Comment by ashb** [comment]
FYI; This behaviour is what Jenkins, GitHub Actions and other CI tools do.

Do you have a proposal for what we should do differentl
