### ISSUE TITLE
Inconsistency between package requirements and constraints: flask-appbuilder (python 3.9)

### ISSUE THREAD

**Issue by cesaralba** [apache/airflow#16499]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N//A

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Fedora/34
- **Kernel** (e.g. `uname -a`): 5.12.10-300.fc34.x86_64
- **Install tools**: Python 3.9.5
- **Others**: Trying to run locally as in https://airflow.apache.org/docs/apache-airflow/stable/start/local.html

**What happened**:
When trying to install airflow following the URL mentioned above I got the following message:

~~~
...
ERROR: Cannot install apache-airflow==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow 2.1.0 depends on flask-appbuilder~=3.3
    The user requested (constraint) flask-appbuilder==3.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
...
~~~

**What you expected to happen**:
To install flawlessly :)

** What do you think went wrong?**:

The requirements package for apache-airflow (https://github.com/apache/airflow/blob/6236e7e205f3dcff3b1f003b7897ba3f549454be/setup.cfg#L102 ) were updated on May 12th (PR https://github.com/apache/airflow/pull/15792) but it seems that for some reason the constraints for python-3.9 were not updated accordingly (rest of versions are ok).

**How to reproduce it**:

On a Linux Box able to run airflow

* Create a virtual environment on a server with python==3.9, pip==21.1.2 (previous versions of pip show a different error message)
* Activate it
* Set environment variables per  https://airflow.apache.org/docs/apache-airflow/stable/start/local.html
* Install apache-airflow

~~~
mkdir wrk
cd wrk/
python3 -m venv sandbox
source sandbox/bin/activate
export AIRFLOW_HOME=$PWD/airflow
AIRFLOW_VERSION=2.1.0
PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
~~~

**Anything else we need to know**:

I tried to change it in a fork but I wasn't able.

To get the fix done (on bash)

~~~
git checkout constraints-2.1.0
sed -i -e 's/Flask-AppBuilder==3.1.1/Flask-AppBuilder==3.3.0/' *-3.9.txt
~~~

After the change, an installation with a local constraints file worked ok.

**Comment by potiuk** [comment]
Python 3.9 is not supported yet (see #15515 ) - it will be added soon (working on it as we speak)
