### ISSUE TITLE
UI: Port is not an integer error on Connection Test

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#16493]
When adding the port in the Webserver it error as it considers the port as a string instead of int

![image](https://user-images.githubusercontent.com/8811558/122307294-f65ae100-cf01-11eb-80fd-1623692c8ff3.png)

Error in Webserver:
```
[2021-06-16 22:56:33,430] {validation.py:204} ERROR - http://localhost:28080/api/v1/connections/test validation error: '25433' is not of type 'integer' - 'port'
```

cc @msumit

**Comment by msumit** [comment]
Found out that when we add a connection, HTML form submits the data in the correct format, but in the test connection, we are hitting an API via JS, which is taking the input as a string. To fix this, we can modify the Openapi definition for port & change it to a string, which would just work fine for add or test connection both. Or we can modify JS and convert the port value to a number before sending it to UI.

**Comment by kaxil** [comment]
closed by https://github.com/apache/airflow/pull/16497
