### ISSUE TITLE
`context` referenced before assignment

### ISSUE THREAD

**Issue by seibert** [apache/airflow#165]
The except block here:

https://github.com/airbnb/airflow/blob/master/airflow/models.py#L840

will fail if an exception is thrown in the preceding try block before line 826:

https://github.com/airbnb/airflow/blob/master/airflow/models.py#L840

The fix is to ensure that `context` has been assigned regardless of where the exception is thrown, but I'm not familiar enough with this code to know how best to do that.

**Comment by mistercrunch** [comment]
This should fix it:
https://github.com/airbnb/airflow/pull/166
