### ISSUE TITLE
Pause/Unpause DAG tooltip doesn't disappear after click

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#16500]
**Apache Airflow version**:
2.2.0dev

**What happened**:
The on/off toggle shows a tooltip "Pause/Unpause DAG" when hovering over it.
This works as expected. However if clicking on the toggle the tooltip will stick until clicking elsewhere in the screen.

**What you expected to happen**:
The tooltip should disappear when user isn't hovering the button.

**How to reproduce it**:
![2021-06-17_11-48-15](https://user-images.githubusercontent.com/45845474/122364575-8c265880-cf62-11eb-834f-4fa3404b3f4b.gif)

**Comment by bbovenzi** [comment]
This is because the switch is in focus once you click on it. Clicking anywhere else on the page will remove the focus and tooltip.

I can still look at the css to fix that.
