### ISSUE TITLE
Adding SubDag to an already unpaused dag created in paused state

### ISSUE THREAD

**Issue by ManiBharataraju** [apache/airflow#16507]
**Apache Airflow version**: Checked in 2.0.2 as well as 2.2

**What happened**:

Adding a new subdag to an already unpaused dag creates the subdag task in paused state. This causes the subdag tasks to not start.
<img> 
![image](https://user-images.githubusercontent.com/9946408/122441191-f2d76080-cfba-11eb-8ed0-1ce52b6b38cf.png)
</img>

**What you expected to happen**:

I expect the subdag to follow the same state of the parent dag. 
PS: Turning the parent dag off and turning it back on fixes the state subdag.

**How to reproduce it**:
```
def simple_subdag(parent_dag_name, subdag_id):

    with DAG(
    dag_id=f'{parent_dag_name}.{subdag_id}',
    default_args=args,
    start_date=datetime(2021, 6, 9),
    schedule_interval="@once",
    ) as subdag:
        start_subdag = DummyOperator(
            task_id='start_subdag',
        )

        start_subdag

    return subdag
```

```
with DAG(
    dag_id='test_subdag',
    default_args=args,
    start_date=datetime(2021, 6, 9),
    schedule_interval="@once",
) as dag:

    run_this_first = DummyOperator(
        task_id='run_this_first',
    )

    do_something = SubDagOperator(
        task_id='do_something',
        subdag=simple_subdag('test_subdag','do_something')
    )
    run_this_first >> do_something

```
1. Create a dag
2. turn the dag on
3. add a new subdag task and retrigger the dag.

**Willing to submit PR**:
Yes

**Comment by segfault16** [comment]
I was also confused about this behavior when adding new subdags and the execution stalled when reaching the new subdag.

Also I want to point out that while individual subdags can be paused/unpaused it's pretty hard to get to the page where the on/off for the subdag is actually shown. I only found them when navigating to the logs of the individual run.
Shouldn't this switch be visible when you "zoom into subdag"?

**Comment by uranusjr** [comment]
This whole concept of subdags is confusing by design, that's why we've been suggesting people to avoid them and use task groups instead 🙂

**Comment by segfault16** [comment]
One thing I like about the subdags is that you are able to use it for high-level structuring of the pipeline into blocks and being able to reschedule individual blocks by clearing with option `downstream` only.
