### ISSUE TITLE
Feature: Method in AWSAthenaHook to get output URI from S3

### ISSUE THREAD

**Issue by Vineet-Sharma29** [apache/airflow#16502]
**Description**

Athena is commonly used service amongst data engineers where one might need to get location of CSV result file in S3. This method will return S3 URI of CSV result on athena aquery. 

**Use case / motivation**
Current implementation of [AWSAthenaHook](https://airflow.apache.org/docs/apache-airflow/1.10.12/_modules/airflow/contrib/hooks/aws_athena_hook.html) has methods to get result data as list of dictionaries, which is not always desired. Instead S3 URI of CSV file is more apt when one have many rows in the CSV file. One can use the S3 URI to process the data further(at some other service like Batch)

This method shall let the used get S3 URI of result CSV file of athena query.(If there some way to add some method to get S3 file URI in `AWSAthenaOperator` then it can be helpful as well)
**Are you willing to submit a PR?**
Yes

**Related Issues**

**Comment by eladkal** [comment]
@Vineet-Sharma29 assigned to you

**Comment by vineetsharma883** [comment]
@eladkal  Would start working on it
