### ISSUE TITLE
Replication of Subdag behaviour with Task Groups

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#16506]
**Description**

Subdag DAGs does not propagate the skip cascading effect when triggered by a ShortCircuitOperator because the inner DAG is contained as it's own DAG. The SubDagOperator is resolved as success and continues through it's downstream dependency in the main DAG.

**Use case / motivation**

I want to replace SubDagOperators with TaskGroup because they are easier to navigate in the UI and much less code to maintain. 

However, after replacing them, the ShortCircuitOperator skips the rest of my DAG since the task group (before was a subsdag) is on the top level of the DAG. 

~~For now, I've added DummyOperators with its trigger rule adjusted to simulate the SubDag behaviour.~~

**Are you willing to submit a PR?**

I would like to contribute but definitely need guidance on what to change.

**Comment by eladkal** [comment]
How did `DummyOperators` solved it? `ShortCircuitOperator` ignores trigger rules (see https://github.com/apache/airflow/issues/7858 )

**Comment by wolfier** [comment]
Hmm, you're right. I must be misremembering. 

Updated the description.

**Comment by uranusjr** [comment]
Since TaskGroup does not have any effect in the scheduler now (I believe), I feel the best solution is to put an operator at the end of the task group that succeeds when any of its upstreams is not skipped, something like

```
   ______________________ TaskGroup _____________________
  |                                                      |
 --> Success --> ShortCurcuit --> Skipped --> AnySuccess --> ThisWillRunNormally
         `--------------------------------------^
```

This can be done with a PythonOperator subclass with trigger rule `DUMMY` and overriding `execute()`. You could also just write that logic in `ThisWillRunNormally`, but having an extra operator probably makes things easier to reason with. What do you think?

**Comment by josh-fell** [comment]
Does the new [`ignore_downstream_trigger_rules`](https://github.com/apache/airflow/blob/6b772f68db4f80b01ede836ddd47437d4aa1b43d/airflow/operators/python.py#L248) param of the `ShortCircuitOperator` help at all?

**Comment by potiuk** [comment]
I'd say this **might** be a good candidate to make scheduler TaskGroup aware. We had few discussions about it in separate threads, and I think it is inevitable that Task Group will be more than just UI concept in the future (but we need to be careful to avoid SubDag pitfalls).
