### ISSUE TITLE
[Feature] Google groups - RBAC role mapping

### ISSUE THREAD

**Issue by rng-spokeo** [apache/airflow#16519]
**Description**
With Google OAuth authentication enabled, users able to login without pre-creating user account in Airflow. However, AUTH_ROLES_MAPPING won't work with Google provider because Google OAuth v2 API do not return user's group information. 

So, can we add a new feature for Google groups - RBAC role mapping. Maybe with Google Service Account setting and Admin SDK API call?

**Use case / motivation**
Fully automate the authentication and authorization processes.

**Are you willing to submit a PR?**
No

**Comment by mik-laj** [comment]
Could you please create this ticket in the Flask App Builder project? It is responsible for the OAuth2 integration in this project.

**Comment by rng-spokeo** [comment]
Sure, I've created this ticket in the FAB project. Here's the link:
https://github.com/dpgaspar/Flask-AppBuilder/issues/1657

**Comment by mik-laj** [comment]
I don't think we can do anything more with this ticket, so I'm closing it
