### ISSUE TITLE
Redshift postgres hook usage

### ISSUE THREAD

**Issue by sanchitburkule** [apache/airflow#16544]
**Description:** While using the Postgres hook for redshift connection, I couldn't find anything on docs if we can do this. 
**To do:** Add instructions for using Postgres hook with a redshift connection.
**Are you willing to submit a PR?** Yes

**Comment by turbaszek** [comment]
@Sanchit112 let us know if you would like some help with opening the PR 👌

**Comment by Sanchit112** [comment]
Hey, I was thinking of adding a line over [here](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/_api/airflow/providers/postgres/hooks/postgres/index.html) that suggests we can use this for redshift connections too, in the class description.
If you have any other idea let me know @turbaszek

**Comment by uranusjr** [comment]
I feel most Redshift users should end up on `airflow.providers.amazon.aws.hooks.redshift` first, so we should probably also add a note there telling them the SQL commands should use `PostgresHook`?

**Comment by Sanchit112** [comment]
Yes, @uranusjr, we can add the SQL note on the **airflow.providers.amazon.aws.hooks.redshift** page and another note in the **Postgres hook**  page

**Comment by eladkal** [comment]
> I feel most Redshift users should end up on `airflow.providers.amazon.aws.hooks.redshift` first, so we should probably also add a note there telling them the SQL commands should use `PostgresHook`?

I agree but would like also to raise a thought. Is it a documentation issue or a functionality issue?
Should we have a`RedshiftSqlHook` that just expose all `PostgreSQLHook` methods?

**Comment by uranusjr** [comment]
> specifically should we have a `RedshiftSqlHook`

That’s a good idea as well

**Comment by JavierLopezT** [comment]
> > I feel most Redshift users should end up on `airflow.providers.amazon.aws.hooks.redshift` first, so we should probably also add a note there telling them the SQL commands should use `PostgresHook`?
> 
> specifically should we have a`RedshiftSqlHook` that just expose all `PostgreSQLHook` methods?

I agree with that

**Comment by eladkal** [comment]
@Sanchit112 are you willing to submit PR?

**Comment by Sanchit112** [comment]
Hey, I'm willing to submit the PR, but I will need some help from you guys.

**Comment by potiuk** [comment]
What help do you need @Sanchit112 ?

**Comment by potiuk** [comment]
Happy to help if you need some :)

**Comment by frankcash** [comment]
I'd be more than happy to grab this.  Is it just to create a hook in the AWS provider along the lines of `RedshiftSqlHook` that essentially utilizes the PostgresHook

**Comment by josh-fell** [comment]
To close the loop and make this group aware (for those who aren't already), #18447 has been created to add a `RedshiftSQLHook` and `RedshiftSQLOperator` which captures the functionality described in this issue.
