### ISSUE TITLE
Document secret masker behaviour/configuration

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#16559]
The new secrets masker feature of 2.1 has no user-facing documentation. Users of airflow who had their own pre-2.1 configuration might be surprised to find out that their logs contain passwords and there are no instruction available on how they should hide them. The best we can do is to direct them to the "default" configuration and tell them "do similar". See #16558 for example.

I think we need better Secrets Masker documentation and possibly some warning in the logs directing them to instructions in case the users start airflow without secrets masker filtering enabled.

I think we should have appropriate documentation here: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/index.html

**Comment by potiuk** [comment]
cc: @ashb

**Comment by ashb** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/index.html

**Comment by potiuk** [comment]
Ah. Hmm strange. I was searching for secrets and masking in the search but there was no results. Maybe the search is broken again

**Comment by potiuk** [comment]
Nope. It works now. 

Sorry for that - must have been some problem in my browser when I tried (I have a spotty connection so it is likely).

**Comment by ashb** [comment]
NP -- our docs are a bit of an IA disaster so it's hard to find  things 😞
