### ISSUE TITLE
Connection Base Hook printing out password in Airflow logs,

### ISSUE THREAD

**Issue by raajpackt** [apache/airflow#16558]
I have recently upgraded to `airflow:2.1.0`.

I am finding the issue of password being printed from within the connection objects in Airflow logs. Earlier they used to be covered with several `X`s in the logs. 

[This ](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/hooks/base.html) should be the source code which causes it to print the password.

**Comment by potiuk** [comment]
Airflow has a new feature in 2.1 - secrets masker. You should configure your logs in the way to enable secrets masker if you want your connection logs to be hidden. See the default configuration for logging, if you have custom configuration you should do a similar filtering in your logs: https://github.com/apache/airflow/blob/6b0dfec01fd9fca7ab3be741d25528a303424edc/airflow/config_templates/airflow_local_settings.py#L67

**Comment by potiuk** [comment]
Here is the docs (I missed it when searching) about it  https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/index.html?highlight=secrets%20masking#masking-sensitive-data

**Comment by raajpackt** [comment]
Does it not by default mask the password field for the connection?
The documentation mentions "Airflow will by default mask Connection passwords and sensitive Variables and keys from a Connection's extra (JSON) field when they appear in Task logs, in the Variable and in the Rendered fields views of the UI."

So is it not a default feature to hide the password?

**Comment by ashb** [comment]
It does mask the password by default, anything else would be useless :)

Questions:

Which log file do you see the password in?
Have you customized the logging in any way?
Can you show the log line (after masking the password manually, of course)

**Comment by raajpackt** [comment]
```
[2021-07-13 05:00:02,423] {subprocess.py:79} INFO - [[34m2021-07-13 05:00:02,423[0m] {[34mbase.py:[0m78} INFO[0m - Using connection to: id: X. Host: X , Port: X, Schema: X, Login: X, Password: X, extra: {}[0m
```
This is the example output in airflow logs. I have replaced the values with X.

**Comment by ashb** [comment]
@raajpackt Masking happens when tasks are run -- where do you have the code that is triggering that behaviour?
