### ISSUE TITLE
Users with Guest role stuck in redirect loop upon login

### ISSUE THREAD

**Issue by dolevf** [apache/airflow#16587]
Airflow 2.1.0, Docker

**What happened**:

Users with the Guest role assigned are stuck in a redirect loop once they attempt to login successfully to the web interface.

**What you expected to happen**:

Get minimal access to the dashboard with the appropriate views for a guest role

**How to reproduce it**:
1. Assign a guest role to any user and remove any other roles with the administrator user.
2. Logout from the admin account 
3. Login as the guest user
4. You will notice constant HTTP redirects, and the dashboard will not show up.

**Comment by potiuk** [comment]
Might be worth fixing for the next release :)

**Comment by mdcsaenz** [comment]
This also happens with oauth for Google. It gets rid of the role for the user and goes into a redirect loop. Will open a ticket. This is happening in 2.1.0

**Comment by uranusjr** [comment]
I wonder how we should fix this. The loop happens because the user is redirected to the login page without appropriate permissions to view the page, and the login page wants to redirect away because the user *is* logged in. So do we log the user out automatically when redirecting due to lack of permission?

**Comment by timothyclarke** [comment]
Isn't a user with the "Guest" role still a validated user and not be pushed back to the login page? (Assuming that the guest role still has default permissions)
Shouldn't https://github.com/apache/airflow/pull/17613 fix this one as well ?

**Comment by uranusjr** [comment]
If the issue description is accurate, the linked PR would not fix this since it only applies when a user has no roles at all.

cc @jedcunningham

**Comment by jedcunningham** [comment]
What "Guest" role? There isn't one by default. Do you mean Public?

This is on my list to look at eventually. #17613 won't fix it, and was targeted specifically at broken FAB role mapping (I didn't consider misconfigured roles).

The easy answer is probably to see if the user has no roles OR permissions are empty OR doesn't have "can read on website". Granted, I haven't fully thought it through.
