### ISSUE TITLE
Support for Jinja2 3.x

### ISSUE THREAD

**Issue by ashwin153** [apache/airflow#16591]
**Description**

Currently, Jinja2 is required to be < 2.12.0.

https://github.com/apache/airflow/blob/7af18ac856b470f91e75d419f27e78bc2a0b215b/setup.cfg#L116

However, the latest version of Jinja2 is 3.0.1.

**Use case / motivation**

This causes some build issues in my monorepo, because other libraries depend on Jinja2 3.x but Airflow does not yet support it. I stepped through the git blame, and it doesn't seem like there's a specific reason why Jinja2 3.x is not supported; the upper-bound appears to be there for stability and not incompatibility reasons.

**Are you willing to submit a PR?**

I would be happy to submit a PR, but I would need some guidance on how to test this change.

**Comment by potiuk** [comment]
Maybe you can just try it. We run a lot of tests which are using Jinja internally so I think it will be enough to have "Green" PR :).

The only thing you need is to make a PR with limitation for Jinja removed in setup.py/cfg. It will automatically bump Jinja to latest non-conflicting version and run all the tests. If it gets green and other committers will be OK with that we can then merge it.
