### ISSUE TITLE
Please consider renaming function airflow.utils.dag_cycle_tester.test_cycle to check_cycle

### ISSUE THREAD

**Issue by zhangyi-hu** [apache/airflow#16608]
**Description**

function test_cycle will be collected by pytest if this function is imported in a user-defined test.
Such an error will be emitted as pytest will treat it as a test.
```
test setup failed
file /opt/conda/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py, line 27
  def test_cycle(dag):
E       fixture 'dag' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

```

**Use case / motivation**
This can be simply "fixed" by renaming this function to check_cycle although the user can do it upon importing this function.
This change by airflow will reduce the amount of surprise received by the end-user, and save a large number of debugging hours. 

**Are you willing to submit a PR?**
The changeset is too small to worth the trouble for a PR.

**Comment by uranusjr** [comment]
> The changeset is too small to worth the trouble for a PR.

All changes are done via PR (even the core maintainers), so one will be needed either way, small or not. Also this may not be as small as you imagine since Airflow has pretty strict backwards compatibility rules, so we can’t just make the old name unavailable, but need to do some tricks to keep the old name available (e.g. using PEP 562 `__getattr__`).

**Comment by potiuk** [comment]
Yeah @zhangyi-hu, it would be great you make PR. PR is a must as @uranusjr mentioned. This change is probably not worth creating issue though, but PR is most welcome. Shall I assign it to you @zhangyi-hu ?

**Comment by zhangyi-hu** [comment]
Sure, give it to me : )

**Comment by zhangyi-hu** [comment]
> > The changeset is too small to worth the trouble for a PR.
> 
> All changes are done via PR (even the core maintainers), so one will be needed either way, small or not. Also this may not be as small as you imagine since Airflow has pretty strict backwards compatibility rules, so we can’t just make the old name unavailable, but need to do some tricks to keep the old name available (e.g. using PEP 562 `__getattr__`).

Is it a good idea to make test_cycle a wrapper of check_cycle and at the same time emit a Deprecation Warning?

**Comment by potiuk** [comment]
> Is it a good idea to make test_cycle a wrapper of check_cycle and at the same time emit a Deprecation Warning?

Yep

**Comment by zhangyi-hu** [comment]
> > Is it a good idea to make test_cycle a wrapper of check_cycle and at the same time emit a Deprecation Warning?
> 
> Yep
Any suggestion on which Release version number I should put here? 
warn("Will be deprecated after Release ###, please use check_cycle from the same module instead.", DeprecationWarning)

**Comment by potiuk** [comment]
Don't. Just deprecate. We are very strictly following SemVer as of 2.0 and it will get dropped at 3.0 (but this is a given): https://github.com/apache/airflow/blob/main/README.md#semantic-versioning
