### ISSUE TITLE
Pod naming ignores dashes and underscores

### ISSUE THREAD

**Issue by SimonOsipov** [apache/airflow#16600]
**Apache Airflow version**: 
2.0.2

**Kubernetes version (if you are using Kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:27:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1600", GitCommit:"7b8e568a7fb4c9d199c2ba29a5f7d76f6b4341c2", GitTreeState:"clean", BuildDate:"2021-05-07T09:18:53Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
I am running Airflow within GKE, one pod, a git-sync container for dags, two containers (same image) for the webserver and scheduler. I utilize Kubernetes Executor and Kubernetes Pod Operators. When I run task I see pod with the name matching the pattern `dag_idtask_id.hash`. But this naming ignores dashes and underscores. Example, `dag_id='inititializer_prefix'`, and `task_id='job_prefix'`. In `kubectl get pods` I see `initializerprefixjobprefix.6d5191b91782409082d46dd3b0ea97f9`

**What you expected to happen**:

I expect executor pod to have name like `initializer_prefixjob_prefix.6d5191b91782409082d46dd3b0ea97f9` at least, or `initializer_prefix_job_prefix.6d5191b91782409082d46dd3b0ea97f9` (autoseparation of `dag_id` and `task_id` by underscore)

**Comment by jedcunningham** [comment]
I understand it wasn't what you were expecting, but is this causing an issue for you?

**Comment by ashb** [comment]
Pod names need to be valid DNS labels, and so _can't_ have underscores in them anyway https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names.

We could make it more legabile by having `_` -> `-`, and then also separating as OP suggestes

**Comment by SimonOsipov** [comment]
Our organization has a certain set of rules for object naming in GKE. And when someone from the admin team looks over our namespace, it is a bit hard to read without any spaces or space replacer. Having `_` -> `-` would be sufficient, imho.

**Comment by SimonOsipov** [comment]
https://github.com/apache/airflow/blob/129fc61a06932175387175b4c2d7e57f00163556/airflow/kubernetes/kubernetes_helper_functions.py#L28-L40

I can't understand from the code and link, why strip from dashes `-`?

**Comment by ashb** [comment]
I _suspect_ dashes are stripped cos of a mistake/misunderstanding

(Or it was cludge to stop things _ending_ in a dash maybe?)

**Comment by uranusjr** [comment]
The docstring seems to suggest the original author knew, but didn’t want to deal with edge cases in the rules, and just took the simplest route by removing everything.

**Comment by SimonOsipov** [comment]
I added PR, adding back dashes in the naming.
