### ISSUE TITLE
Can't use sftp connection defined in environment variables

### ISSUE THREAD

**Issue by chriskessel** [apache/airflow#16616]
I'm using the S3Hook, passing it a connection id and for some reason it's not able to find it if that connection is defined as an environment variable. 

```
        sftp_hook = SFTPHook(ftp_conn_id=self.sftp_conn_id)
```
```
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `sftp_local` isn't defined
```

The connection is definitely there, I can see it if I use the CLI to `get connections sftp_local`
```
$ airflow connections get sftp_local
id   | conn_id    | conn_type | blah blah
None | sftp_local | sftp      | blah blah 
```

I'm using other environment variables for connections (AWS Athena/S3 connections) and they work, so I'm not sure if I'm doing something wrong or it's a bug.

**Comment by potiuk** [comment]
Are you sure you have the env variable it defined in the worker where you run the tasks?

**Comment by chriskessel** [comment]
I'm fairly sure, I kill the docker process, rm the container, and restart it (via docker-compose.yml) before each usage as I've been testing. I even bashed into the worker and looked at the env vars and it was there. Which was no surprise, that's why the airflow CLI found it.

I blew away the complete airflow docker setup, blew away the containers and images. Restarted everything...and now it works.

I really don't get it, I defined 3 different _CONN_ variables all at the same time, all 3 showed up on the worker's env vars, all 3 showed up in the CLI, only 2 worked....but it's working after that complete nuke, so yay?

Magic...closing.

**Comment by potiuk** [comment]
Well. I stopped counting the times I was sure about something I did  - about 20 years ago ;). It helps.
