### ISSUE TITLE
GitSync SubPath configuration is not workibg

### ISSUE THREAD

**Issue by raefezzeldin** [apache/airflow#16622]
When I try to enable GitSync to sync dags from private repo on Github using HTTPS , Username and PAT. it keeps synscing the whole repo , ignoring my subPath configuration and always create this folders in dags folder:

![image](https://user-images.githubusercontent.com/1645929/123010719-74fec500-d3bf-11eb-84c3-d972ec8ec3d7.png)

  dags: 
    gitSync: 
      repo: "https://XXXXXXXXs"
      subPath: "dags"
      enabled: true
      branch: "main"
      credentialsSecret: git-credentials

**Comment by jjyxi** [comment]
https://www.maconnerie-landes-pays-basque.fr/ /nike tribute veste
https://www.max-sidney.fr/ /masque d horreur a imprimer
https://www.cpe-beton-dellatti.fr/ /batterie ducati monster 900 ie
https://www.domoconfig.fr/ /chaussures de sécurité facom
https://www.senteursparc.fr/ /casquette nike de golf
https://www.monvela.com/ /tumbona terraza ikea
https://www.umrohpersada.com/ /nike sb stefan janoski beige
https://www.alwaselshelves.com/ /cesto para ropa sucia de madera
https://www.festivosdecolombia.com/ /adidas duramo 7 precio
https://www.spiritofvalencia.es/ /venta de tenis nike en tijuana
https://www.cocinasmayfran.com/ /nike huarache kobe bryant
https://www.fjlopezbus.com/ /camara digital olympus fe 340
https://www.tarifakitesurf.es/ /Supeme Hoodie
https://www.procashwallet.com/ /welke scooter moet ik kopen
https://www.casaruralbardenas.es/ /nike huarache og colorways
https://www.infad.es/ /bimba y lola zapatos
https://www.payasosdalmatas.es/ /adidas adizero ace boost 7
https://www.aireproyectosyservicios.com/ /juguete avalancha apache
https://www.elvientodelnorte.es/ /botas de pelo mujer
https://www.enoneuroliderazgo.com/ /zapatillas de agua niña
https://www.pensionesjerez.com/ /tapie adidas credit lyonnais
https://www.clubemprendedorescadiz.es/ /sandalias rosa palo tacon ancho giro
https://www.hostallosarcos.com/ /sims 4 nike shoes kids
https://www.mardepepa.com/ /adidas real valladolid portero niño
https://www.mitsubishiteruel.com/ /nike metal swoosh cap white

**Comment by ururu-fy** [comment]
@raefezzeldin hello. could you please tell me how you resolved this problem?

**Comment by ulan-yisaev** [comment]
I have the same issue, is there any known solution?

**Comment by funes79** [comment]
Same here
