### ISSUE TITLE
Open up breeze container ssh access to support IDE remote development

### ISSUE THREAD

**Issue by zhangyi-hu** [apache/airflow#16621]
**Description**

The breeze container is the preferred way of development setup since it provides a full-fledged and isolated environment. However, breeze container is not very suitable for development with IDE. 

**Use case / motivation**

My IDEs actually support remote development and the only additional requirement is for a host to support ssh connection. 
We can make breeze container support ssh connection by adding two changes:

1. Add a password to user airflow for the CI Docker image. 
2. Add a portforward to 22 from host. 

**Are you willing to submit a PR?**

Yes a PR is on the way

**Setup with Pycharm pro**

1. Add a ssh configuration, with user airflow and password airflow and the default ssh port 12322, (12322 will be forward to 22)
2. Add a remote ssh interpreter, (airflow@localhost:12322/usr/local/bin/python)
3. Add two source mappings from local source to container: \<source root\>/airflow -> /opt/airflow/airflow; \<source root\>/tests -> /opt/airflow/tests.
4. Set the unnit test framework for this project as pytest.  

After those steps, one will be able to set breakpoints and debug through the python codes with Pycharm Pro.

**Comment by zhangyi-hu** [comment]
Will create a PR from branch: https://github.com/zhangyi-hu/airflow/tree/breeze_container_ssh_remote_debugging after https://github.com/apache/airflow/pull/16617 is merged.

**Comment by potiuk** [comment]
Nice :)

**Comment by potiuk** [comment]
The #16617 merged. Looking forward to the SSH/Breeze one

**Comment by huymq1710** [comment]
Do we have any document for setting breeze with Pycharm ?

**Comment by potiuk** [comment]
https://www.jetbrains.com/help/pycharm/configuring-remote-interpreters-via-ssh.html#ssh - > but you need to have PRO version of Pycharm

**Comment by huymq1710** [comment]
@potiuk 
Thank you

I already run 
```
cd /GitHub/airflow
breeze start-airflow
```

> Add two source mappings from local source to container: <source root>/airflow -> /opt/airflow/airflow; <source root>/tests -> /opt/airflow/tests.

In step 3. Is it sync folder path in https://www.jetbrains.com/help/pycharm/configuring-remote-interpreters-via-ssh.html#ssh ?

**Comment by huymq1710** [comment]
Background: I would like to debug and try to fix the issue I just found in `backfill_job_runner.py` in Pycharm Pro via breeze
I already watched [your video](https://www.youtube.com/watch?v=4MCTXq-oF68&ab_channel=ApacheAirflow), but do not know how to debug it ...

**Comment by potiuk** [comment]
Like any other running interpreter : you can stop existing running component and run it with ssh debugging. https://www.jetbrains.com/help/pycharm/configuring-remote-interpreters-via-ssh.html#ssh. Youu can do the same with Remote debug server (same link) - stop the process you want to debug, modify code to connect back to your remote debugging server and run it.

Also our documentation has whole chapter with screenshots about remote debugging using pyChar, - have you seen it? https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#local-and-remote-debugging-in-ide
