### ISSUE TITLE
KubernetesPodOperator gets automatically shifted ended time

### ISSUE THREAD

**Issue by jvaca92Code** [apache/airflow#16637]
**Apache Airflow 1.10.12**:

**Kubernetes version 1.17.9**:

**Environment**:

- **Cloud provider or hardware configuration**:  Azure AKS

**What happened**:
On our environment we try to run dag multiple KubernetesPodOperator tasks which are not deployed in cluster where the Airflow instances have run but in the other Openshift cluster with different kube config. Every manual run some of the task finished successfully but some of them are randomly killed by SIGTERM but on Openshift the containers are normally finished successfully.

>[2021-06-24 16:46:11,323] {local_task_job.py:159} WARNING - State of this instance has been externally set to failed. Taking the >poison pill.
>[2021-06-24 16:46:11,324] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 447
>[2021-06-24 16:46:11,324] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
>[2021-06-24 16:46:11,325] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site->packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'prod1->ocp.prg-dc.dhl.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced->usage.html#ssl-warnings InsecureRequestWarning,

The other strange behavior is that the task run something around 1- 2 minutes but ended duration show up with shifted value which does not make sense:

![image](https://user-images.githubusercontent.com/72670462/123307614-fe7ad800-d522-11eb-8bf9-d97775d20621.png)

**What you expected to happen**:

I would expect show up right ended time and without SIGTERM signal.

**Comment by eladkal** [comment]
This issue is reported against EOL version of Airflow.
Can you please let us know if the issue happens in latest airflow version?
