### ISSUE TITLE
Airflow 2.0.0 Docker Image Not working with MySQL RDS 5.7.34 or higher

### ISSUE THREAD

**Issue by yashbaldawa-okta** [apache/airflow#16643]
**Apache Airflow version**: Airflow Docker Image 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): None. Using docker. 

**Environment**: Trying to instantiate the servers locally on Mac (16 GB RAM, i9) MacOS Mojave

- **Cloud provider or hardware configuration**: Mac
- **OS** (e.g. from /etc/os-release): Mojave
- **Kernel** (e.g. `uname -a`): - 
- **Install tools**: Docker 
- **Others**:

**What happened**: Airflow 2.0.0 docker image does not allow the webserver and scheduler to start with metadata RDS MySQL 5.7.34 or higher. 

 No known error message generated except "ERROR - Failed to add operation for GET /api/v1/connections" 
Error similar to stackoverflow issue: https://stackoverflow.com/questions/67437595/airflow-db-init-error-failed-to-add-operation-for-get-api-v1-connections but solutions given does not solve the problem for MySQL backend. 

**What you expected to happen**: Webserver and Scheduler to start as normal as they did for 1.10.14 with changes in config necessary for 2.0.0
 Unknown bug in 2.0.0's docker image for MySQL Integration. 

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Unless you provide .ore information and logs, there is no way we can help here. You need to describe the exact deployment you have and analyse the log files that should state error that you are receiving.

**Comment by potiuk** [comment]
Closing untill more details are provided.
