### ISSUE TITLE
Edit on Github button is brocken.

### ISSUE THREAD

**Issue by NiklasBeierl** [apache/airflow#16649]
**Apache Airflow version**: Guess the most recent

**Environment**: The documentation website

**What happened**:

Clicking the "Suggest a change on this page" button in the doc pages leads to a 404".
Tested on:
https://airflow.apache.org/docs/apache-airflow/stable/license.html
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html

**What you expected to happen**:

Getting a github page to edit the corresponding rst file.

**How to reproduce it**:

Go on the doc pages and click the "Suggest an edit on github" button in the outtom right corner. If you are a developer, it might actually work for you if you have access to a branch called "develop", in that case I suggest you use an incognito tab.

**Anything else we need to know**:
I compared the url generated for the button with the one i got when manually navigating through the repo:

In the repo: https://github.com/apache/airflow/edit/**main**/docs/apache-airflow/configurations-ref.rst
In the site: https://github.com/apache/airflow/edit/**devel**/docs/apache-airflow/configurations-ref.rst

I do not see a `devel` branch in github. Seems like the branch was either unintentionally hidden from the public, or it was intentionally hidden, but the sphinx configuration that generates the doc website was not adjusted accordingly.

Funny enough, the checked in conf.py on `main` seems to be correctly configured to point to the `main` branch.
https://github.com/apache/airflow/blob/88ee2aa7ddf91799f25add9c57e1ea128de2b7aa/docs/conf.py#L333

**Comment by potiuk** [comment]
Thanks. Already reperted and fixed but needs documentation release. It already works for providers, now it needs airflow 2.1.1 to get fixed

**Comment by potiuk** [comment]
But this is a good point that you raised it. I also made a new change to independently fix it for all the already released docs: https://github.com/apache/airflow-site/pull/440
