### ISSUE TITLE
Load Entrypoint Plugins Before Directory Plugins

### ISSUE THREAD

**Issue by aplett98** [apache/airflow#16641]
**Description**

Load entrypoint plugins before plugins directory plugins

**Use case / motivation**

https://github.com/apache/airflow/blob/ffb1fcacff21c31d7cacfbd843a84208fca38d1e/airflow/plugins_manager.py#L291-L292
Currently, entrypoint plugins are loaded after plugins directory plugins. If there's not a specific reason for this ordering, I think these should be reversed.

For example, if I have a custom operator `MyOperator` that I want to derive from another developer's custom operator `TheirOperator`, and that operator is part of a package that uses the Airflow plugins entrypoint, I would probably have a `my_operator.py` file that looks like this:
```python3
from airflow.operators.their_plugin import TheirOperator

class MyOperator(TheirOperator):
    ...
    ...
```
As it stands, since `MyOperator` is loaded first, this will fail with `ModuleNotFoundError` on `their_package.plugins`, making it difficult to derive operators from other packages.

**Are you willing to submit a PR?**

Yes!

**Related Issues**

Sorry, didn't use template in original issue:
apache/airflow#16640

**Comment by uranusjr** [comment]
> For example, if I have a custom operator `MyOperator` that I want to derive from another developer's custom operator `TheirOperator`, and that operator is part of a package that uses the Airflow plugins entrypoint, I would probably have a `my_operator.py` file that looks like this:
> 
> ```python
> from airflow.operators.their_plugin import TheirOperator
> ```

It is more idiomatic Python to import from the actual plugin instead. An operator is just a class and unrelated to the plugin interface, and [the `airflow.operators` is not even available anymore](https://airflow.apache.org/docs/apache-airflow/stable/plugins.html) since Airflow 2.0.

**Comment by mik-laj** [comment]
Adding Operators and Sensors via plugins is no longer supported. See: https://github.com/apache/airflow/blob/main/UPDATING.md#adding-operators-and-sensors-via-plugins-is-no-longer-supported
