### ISSUE TITLE
Display operator details on the Instance Details page

### ISSUE THREAD

**Issue by mtrovo** [apache/airflow#16657]
**Description**

Provide a way to display operator details on the Instance Details page

**Use case / motivation**

I have some custom operators that produces output (a report, an S3 file, etc.) and I would like to have a way to just click on a task instance and see what this output is (possibly for URLs it just generates a link to its content).

Right now I have to rely on opening the task instance logs and looking up for the relevant information over there. 

For the implementation I think Airflow UI could show all operator class properties on the Instance Details page as a new block, similar to what current happens to the TaskInstance properties itself.

**Are you willing to submit a PR?**

Sure

**Related Issues**

N/A

**Comment by potiuk** [comment]
I think this is already there in the form of operator extra links. https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html

You need to add your operator via plugin or custom provider but I think it does exactly what you want

**Comment by potiuk** [comment]
I am closing this for now - do let me know @mtrovo in case it did not solve your feature request (and why) - we can consider reopening it then.
