### ISSUE TITLE
WebHDFS : why force http ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [apache/airflow#16651]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Cloud provider or hardware configuration**: /
- **OS** (e.g. from /etc/os-release):  /
- **Kernel** (e.g. `uname -a`): /
- **Install tools**: / 
- **Others**: /

**What happened**:

I'm trying to make the provider WebHDFS work...

I don't understand why "http" is not overridable by https : https://github.com/apache/airflow/blob/main/airflow/providers/apache/hdfs/hooks/webhdfs.py#L95

Is there aynone using WebHDFS with https ?

**Comment by potiuk** [comment]
Feel free to make a PR to fix it @Jeoffreybauvin ! Shall I assign you the issue ?

**Comment by Aakcht** [comment]
Looks like I have the same issue, I'll try submitting a PR if nobody minds

**Comment by potiuk** [comment]
> Looks like I have the same issue, I'll try submitting a PR if nobody minds

Please!
