### ISSUE TITLE
Can't select version of the hook in hooks docs

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#16655]
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/hooks/s3/index.html
https://airflow.apache.org/docs/apache-airflow/1.10.14/_modules/airflow/hooks/S3_hook.html
http://airflow.apache.org/docs/apache-airflow-providers-mongo/stable/_api/airflow/providers/mongo/hooks/mongo/index.html

<img width="868" alt="Captura de pantalla 2021-06-25 a las 14 43 06" src="https://user-images.githubusercontent.com/11339132/123426399-a942d300-d5c3-11eb-9cf3-0a20363ee599.png">
<img width="868" alt="Captura de pantalla 2021-06-25 a las 14 43 18" src="https://user-images.githubusercontent.com/11339132/123426417-b069e100-d5c3-11eb-8104-cfab3053a675.png">
<img width="975" alt="Captura de pantalla 2021-06-25 a las 14 43 46" src="https://user-images.githubusercontent.com/11339132/123426475-c081c080-d5c3-11eb-9640-e5aae1981614.png">

In the index hook you can choose the version
<img width="952" alt="Captura de pantalla 2021-06-25 a las 14 45 09" src="https://user-images.githubusercontent.com/11339132/123426648-f32bb900-d5c3-11eb-86ba-42dd02f3d043.png">

Maybe not a bug but a feature, dunno

**Comment by potiuk** [comment]
Similar to #16654 PRs to fix it are most welcome :)

**Comment by potiuk** [comment]
Thanks for reporting @JavierLopezT !

**Comment by brandao-andre** [comment]
Hi @potiuk, im looking for some good first issue trying to make my first contribution to the airflow project. Any hints where to start this one? Or someone that i could talk to? Thanks!

**Comment by potiuk** [comment]
Hell yeah : https://github.com/apache/airflow/contribute

**Comment by josh-fell** [comment]
After spot checking several providers and assorted Python API docs pages within those providers, I can no longer replicate this issue. Of course this can be reopened if needed.
