### ISSUE TITLE
DAG.add_task doesn't pick up start_date default arg

### ISSUE THREAD

**Issue by ZaxR** [apache/airflow#16697]
**Apache Airflow version**: 2.1.0

**What happened**:
When attempting to set the dag for a task (Operator) without the dag previously set, where the dag's start_date is set via default_args , an error is raised: `AirflowException: Task is missing the start_date parameter`.

**What you expected to happen**:
The start_date from default_args to be honored and no error to occur.

**Related notes**:
This relates to an issue in 1.x where using the bitshift operator with Operators that don't specify a dag (or are not within a DAG's context), and a dag where start_date is set via `default_args`, the bitshift operation will error with: `AirflowException: Task is missing the start_date parameter`. That issue was raised several times in the past (most recently in #7996), and @ashb had a solution in #5598 , but it was put on hold since support for bitshift operators was being debated for Airflow 2.x.

**How to reproduce it:**
```
from datetime import datetime

from airflow import DAG
from airflow.operators.dummy import DummyOperator

default_args = {
    'owner': 'airflow',
    'start_date': datetime(2017, 2, 1)
}

dag = DAG('my_dag', default_args=default_args)
dummy = DummyOperator(task_id='dummy')
dag.add_task(dummy)
# # Rest of the flow
# dummy2 = DummyOperator(task_id='dummy2')
# dag.add_task(dummy2)

# dummy >> dummy2
```
Setting start_date directly instead of from default_args works as expected:
```
...
dag = DAG('my_dag', start_date=datetime(2017, 2, 1), default_args=default_args)
...
```

While the example is contrived, I think it's important functionality for reusable, pre-configured Operators, such as are used in factory and composition patterns.

**Comment by ashb** [comment]
Are both tasks missing the start date?

**Comment by ZaxR** [comment]
Updated by issue. The error happens on `dag.add_task(dummy)`, where the `dummy` task to add doesn't have its own start_date (or other config for that matter), but rather it would expect it to take on the dag's.

**Comment by ashb** [comment]
I'm of two minds wether or not we fix this -- as 99% of use cases od `default_args` should just be set directly as attributes on DAG -- it's just that our examples show using default args so many people copy that.

**Comment by ZaxR** [comment]
From what I've seen in the wild, people heavily use default_args for everything. At companies I've worked at, there's even been utility functions to get "global" default_args as a fallback, which include start_date. So based on the heavy usage and support for using default_args for start_date, I'd argue the fix is justified.

**Comment by uranusjr** [comment]
Personally I wish Airflow never had `default_args`, it’s too magical with a logical native Python approach (`**kwargs`). But I guess that ship sailed way back and we should make it work mroe closely to what users expect in this case.

**Comment by potiuk** [comment]
> Personally I wish Airflow never had `default_args`, it’s too magical with a logical native Python approach (`**kwargs`). But I guess that ship sailed way back and we should make it work mroe closely to what users expect in this case.

Side comment - It does save you a bit of hassle when you define dags, but I agree it is a bit too implicit. And yeah. the ship has sailed :).

**Comment by ashb** [comment]
> From what I've seen in the wild, people heavily use default_args for everything. At companies I've worked at, there's even been utility functions to get "global" default_args as a fallback, which include start_date. So based on the heavy usage and support for using default_args for start_date, I'd argue the fix is justified.

Setting start date via default_args is the one that bugs me most. Set it on the dag directly instead :)

**Comment by eladkal** [comment]
Using the DAG code as shared by the author will show broken dag message
![Screen Shot 2022-11-02 at 12 58 02](https://user-images.githubusercontent.com/45845474/199472808-05e598bb-cc04-4621-83a7-2e84c3445556.png)

However if using the code as:
```
default_args = {
    'owner': 'airflow',
    'start_date': datetime(2017, 2, 1)
}
with DAG('my_dag', default_args=default_args):
    DummyOperator(task_id='dummy')
```
It will work
![Screen Shot 2022-11-02 at 13 01 16](https://user-images.githubusercontent.com/45845474/199473353-02a5f0dd-5f98-460e-bb56-e8d1bde02528.png)

In our examples we never show usage of `dag.add_task()` and I'm not sure why this is needed here?
Since the recommended way to use context manager and this is working fine I'm closing this issue.
