### ISSUE TITLE
ssh provider limits to an old version of sshtunnel 

### ISSUE THREAD

**Issue by kurtqq** [apache/airflow#16699]
ssh provider has limit to sshtunnel  < 0.2
https://github.com/apache/airflow/blob/9d6ae609b60449bd274c2f96e72486d73ad2b8f9/setup.py#L451

I don't know why? sshtunnel  already released 0.4
I didn't open PR because I don't know this provider i just tried to install it and couldn't due to conflicts with other requirements in my system so eventually i used vitrual env to solve my problem but logging this issue so that someone who knows this code can handle it.

**Comment by potiuk** [comment]
Please simply just make a PR with it. We have automated suite of tests, if they pass, this means we should approve it.

**Comment by potiuk** [comment]
Same as #16698
