### ISSUE TITLE
Show  schedule_interval/timetable description for schedule cron expression in Airflow UI

### ISSUE THREAD

**Issue by pateash** [apache/airflow#16692]
**Description**

Users should be able to see a short description of the cron expression when hovering over the expression in a tooltip.

![image](https://user-images.githubusercontent.com/16856802/123651190-e7045d80-d848-11eb-9ed5-529d806992d1.png)

In the above case, the user should see description like  **At 09:30 PM, only on Friday**

**Use case / motivation**
It will be really easy to get schedule information for the users who are not really great at reading CRON,
even for the experience users CRON can be really complicated at times.

We will create a tooltip component which will evaluate underlying cron and show the description.

**Are you willing to submit a PR?**
YES

**Related Issues**
NONE

**Comment by uranusjr** [comment]
Sounds like a nice feature to me. How do you plan to geenrate the description? I know there are some online services but am not aware of a Python package for this. And it seems a bit weird to implement it directly in Airflow’s code base.

**Comment by ashb** [comment]
https://github.com/azza-bazoo/prettycron might do the job? We should check it supports at least everything croniter does.

**Comment by uranusjr** [comment]
croniter actually “supports” some weird (invalid?) cron formats, for example `10 * * * * *` (six sgements!) can be parsed by it. I saw a report on it just yesteday but can’t find the thread now. So we either need to do some additional validation (to reject those currently-allowed formats) or be bug-to-bug compatible with croniter.

**Comment by pateash** [comment]
I have used  **[cronstrue](https://www.npmjs.com/package/cronstrue)** previously in my projects.
may be I will prefer to use that;

**Comment by uranusjr** [comment]
Let’s try it out then! We can carry on with the details in the PR thread.

**Comment by uranusjr** [comment]
Found the issue on croniter formats: #16107.

**Comment by lucas-garcia-rubio** [comment]
Cronstrue in Python: https://github.com/Salamek/cron-descriptor
