### ISSUE TITLE
dag_hash generation is unstable

### ISSUE THREAD

**Issue by luoyuliuyin** [apache/airflow#16690]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

dag_hash is used to judge whether the current dag has changed, but I found that the generation of dag_hash is unstable.
the json just takes the keys in order here, but the value is not sorted inside
![image](https://user-images.githubusercontent.com/28948186/123630380-0949ab80-d848-11eb-837c-eb2b44c2b709.png)

**What you expected to happen**:
Need to return a stable object when calling here `SerializedDAG.to_dict(dag)` 
![image](https://user-images.githubusercontent.com/28948186/123632670-c76e3480-d84a-11eb-8733-b39ea89d895b.png)

If you want to fix this bug, you need to order the list, (Of course I can also pick up and fix this bug 😊)
![image](https://user-images.githubusercontent.com/28948186/123633174-74e14800-d84b-11eb-94ae-53b448e13278.png)

![image](https://user-images.githubusercontent.com/28948186/123632807-eff62e80-d84a-11eb-936e-9bb5c8a1faac.png)

**How to reproduce it**:

**Anything else we need to know**:

**Comment by uranusjr** [comment]
So looks like we should use `sorted` on the code you highlighted. Could you draft a PR for that?

**Comment by luoyuliuyin** [comment]
> So looks like we should use `sorted` on the code you highlighted. Could you draft a PR for that?

ok
