### ISSUE TITLE
Support a JoinPythonOperator to Work with the BranchPythonOperator Already Supported

### ISSUE THREAD

**Issue by r39132** [apache/airflow#167]
I need a branch operator to do the following

Currently, in our QA environment, our Spark job has been split into 2 steps, let's call them **A** and **C**. In our PROD environment however, it is still one step, **A**. I don't want to maintain 2 different DAGs, one for PROD and one for QA. Instead, I would like to leverage both Variables and the new BranchPythonOperator. 

Specifically, I have a new Variable called ENV with values of QA or PROD. I would like the PythonBranchOperator to execute `A-->B-->C-->D-->E` in QA and `A-->B-->D-->E` in PROD. I would like to make step **C** optional based on ENV.

My DAG is below: 
<img width="914" alt="screenshot 2015-07-22 19 16 26" src="https://cloud.githubusercontent.com/assets/581734/8841719/49bbe7b4-30a6-11e5-8aeb-1382cbbe04d7.png">

I tried to leverage the new BranchPythonOperator for this, but it doesn't work. The reason is that the DAG is not allowed to rejoin after a branch. Once one leg of the branch is taken, all downstream descendants are marked as skipped. However, if the DAG rejoins, then this is not the case.

In my example, **C** is a BashOperator.

**Comment by mistercrunch** [comment]
For the templated operators like `BashOperator` it's pretty easy to skip and succeed:

```
{% if params.is_dev %}
echo "success"
{% else %}
bash spark_command.sh
{% endif %}
```

We've been doing this for skipping tasks before a certain date for instance as in `{% if ds >= '2015-01-01' %}`

A more generic way could be (not a feature yet) to pass a `skip_and_succeed` param that expects a callable that receives the context object and skips and succeeds if the callable returns `True`. It may look something like this:

```
FooOperator(
    task_id='bar',
    skip_and_succeed=lambda context: return context['ds']<'2015-01-01',
    dag=dag,
)
```

**Comment by r39132** [comment]
Cool. This works. 

```
# Operator : Read the parquet data and generate aggregate data
optional_aggregation_templated_command = """
    {% if params.ENV == "EP_PROD" %}
        echo "Skipping Aggregation in Prod Env"
    {% else %}
        ssh -i ~/.ssh/id_rsa_spark root@10.10.2.157 '. /root/.bash_profile; /root/run_aggregation.sh {{ macros.ds_format(macros.ds_add(ds, -3), '%Y-%m-%d', '%s') }} {{ execution_date.strftime('%s') }}'
    {% endif %}
"""
aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    execution_timeout=timedelta(hours=3),
    bash_command=optional_aggregation_templated_command,
    params={'ENV': ENV},
    dag=dag)
aggregate_data_spark_job.set_upstream(generate_new_parquet_files_spark_job)
```

It's a handy solution, but I guess I was thinking of the more general problem of handling branched flows that need to be joined later. Branching is a great feature, but with branching often comes joining. The legs of the branch could be different lengths. Currently, you set all descendants to "Skipped", but perhaps the code can be changed to set only those descendants to Skipped that do not join with a Non-skipped branch. In other words, we would need to set descendants to skipped until we come across a node that has multiple parents and one of those parents is not skipped.

**Comment by r39132** [comment]
BTW, I was not able to follow your FooOperator example. I'd like to keep this open in hopes there is a more generic join approach!

**Comment by r39132** [comment]
Hi Folks!
I've changed the title of this issue to `Support a JoinPythonOperator to Work with the BranchPythonOperator Already Supported`. Prior to the creation of the BranchPythonOperator, we had ability to execute DAGs containing "diamond" topologies. With the advent and use of the BranchPythonOperator, we lost that ability, since every downstream node is labeled as `skipped`. I think the support of branching sets Airflow apart from other workflow engines, but it does require support for joining, as shown above. If this were available I would use it instead of the 'if-else' templating method, which I feel is less elegant.

**Comment by mistercrunch** [comment]
Sounds right. We'd need the `skipped` state to propagate downstream until it hits a JoinOperator of some sort.

**Comment by azaroth42** [comment]
:+1:

**Comment by mistercrunch** [comment]
Joining will be possible using any operator once this PR is merged!
https://github.com/airbnb/airflow/pull/261

**Comment by r39132** [comment]
:+1:

**Comment by smnaveen** [comment]
Btw, when attempting to use the branch operator, I am getting a "import error" on the line trying to import the branch python operator. (from airflow.operators import BranchPythonOperator)

i am using v1.1.1. is the branch operator only available in a specific version or release of airflow ?

**Comment by artwr** [comment]
@smnaveen the operator showed up in 1.2.0 if I am correct, but I would recommend using the latest release (There have been a decent amount of bug fixes since)

**Comment by mistercrunch** [comment]
Joining can now be achieve with "trigger rules":
http://pythonhosted.org/airflow/concepts.html#trigger-rules

**Comment by r39132** [comment]
I finally got to a point where I needed to use this.. excellent!

Thanks!

<img width="729" alt="screenshot 2015-11-20 23 41 20" src="https://cloud.githubusercontent.com/assets/581734/11317330/3d9ccbda-8fe0-11e5-9c87-7042d768b655.png">
