### ISSUE TITLE
Airflow 2.1.0: Snowflake connection not enabling snowflake "role"

### ISSUE THREAD

**Issue by saurasingh** [apache/airflow#16717]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 

**Environment**: 

- **Cloud provider or hardware configuration**: AWS EKS, AWS ECS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When creating a snowflake connector using a snowflake hook(using UI), not able to add snowflake roles in the extras. 
here is the screenshot of the connection which I am creating 
![Screen Shot 2021-06-29 at 1 31 33 PM](https://user-images.githubusercontent.com/19628707/123842261-92abbd00-d8de-11eb-93ae-baf29999ba9d.png)

but once I am done saving it I lose the role and if I edit my connection this is what I see in the UI

![Screen Shot 2021-06-29 at 1 32 18 PM](https://user-images.githubusercontent.com/19628707/123842357-b111b880-d8de-11eb-9a73-146b0b069851.png)

so Extra gets populated with all the other placeholders.  I can see that https://github.com/apache/airflow/blob/4b14d93f25f237b8cca17f57352c253f292a111b/airflow/providers/snowflake/hooks/snowflake.py#L89 you guys are returning some value to the widget but it is not having a snowflake "role" definition.

https://github.com/apache/airflow/blob/4b14d93f25f237b8cca17f57352c253f292a111b/airflow/providers/snowflake/hooks/snowflake.py#L105 

I also updated the JSON object and created it as a nested JSON `{{"role": "test"}}`  following the `placeholder` from the above function but still, the behaviour remains the same. 

**What you expected to happen**:
```
"placeholders": {
                'extra': json.dumps(
                    {
                        "role": "snowflake role",
                        "authenticator": "snowflake oauth",
                        "private_key_file": "private key",
                        "session_parameters": "session parameters",
                    },
                    indent=1,
                ),
                'host': 'snowflake hostname',
                'schema': 'snowflake schema',
                'login': 'snowflake username',
                'password': 'snowflake password',
                'extra__snowflake__account': 'snowflake account name',
                'extra__snowflake__warehouse': 'snowflake warehouse name',
                'extra__snowflake__database': 'snowflake db name',
                'extra__snowflake__region': 'snowflake hosted region',
                'extra__snowflake__aws_access_key_id': 'aws access key id (S3ToSnowflakeOperator)',
                'extra__snowflake__aws_secret_access_key': 'aws secret access key (S3ToSnowflakeOperator)',
            }
```
If I follow above code I should be able to pass the snowflake role into the Extras. But this behaiour is missing

**How to reproduce it**:

Create a connection with connection type snowflake in airflow UI.

**Anything else we need to know**:

**Comment by potiuk** [comment]
@saurasingh - would you be willing to add a PR to add this feature?

**Comment by saurasingh** [comment]
@potiuk I have committed my changes to a local branch but not able to push to create a PR for you guys to review. 
`unable to access 'https://github.com/apache/airflow.git/': The requested URL returned error: 403` I am getting this error

**Comment by potiuk** [comment]
You need to make Pull request from your branch.

**Comment by uranusjr** [comment]
See: https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#contribution-workflow

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/16735

**Comment by spniemansburg** [comment]
Issue is closed, but wanted to note that the same issue is happening when trying to add a private key file (using "private_key_file" parameter) in the Extra field. I am using Apache Airflow 2.1.0. Should I file a new bug report?
