### ISSUE TITLE
[Bug] Task log can't be shown on Web-Server when the task runs failed

### ISSUE THREAD

**Issue by huozhanfeng** [apache/airflow#16729]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Aliyun
- **OS** (e.g. from /etc/os-release): CentOS Linux" VERSION="7 (Core)
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-514.21.1.el7.x86_64
- **Install tools**: celery  4.4.7    rabbitmq 3.8.17
- **Others**:

**What happened**:
Task log can't be shown on Web-Server when the task runs failed, while log can be shown normally when the task success

<pre>
*** Log file does not exist: /home/airflow/airflow/logs/dag_id/task_id/2021-06-28T00:00:00+08:00/28.log
*** Fetching from: http://:8793/log/dag_id/task_id/2021-06-28T00:00:00+08:00/28.log
*** Failed to fetch log file from worker. Unsupported URL protocol 
</pre>

**What you expected to happen**: 
The task log should be shown normally when the task runs failed.

The Hostname info doesn't be written into the task instance table, so the webserver can't get the corresponding hostname.

**How to reproduce it**:
Just run a dag and make its task fail to reproduce the bug.

**Anything else we need to know**:
I have fixed it in my env and will commit a PR to fix it.

**Comment by uranusjr** [comment]
Looks like another duplicate to #13692.

**Comment by huozhanfeng** [comment]
> Looks like another duplicate to #13692.

Sure, I will track it on the other issue.
