### ISSUE TITLE
filesensor wildcard matching does not recognize directories

### ISSUE THREAD

**Issue by MrSandoman** [apache/airflow#16725]
**Apache Airflow version**: 2.1.0

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:  FileSensor does not recognize directories with wildcard glob matching.

**What you expected to happen**: FileSensor would sense a directory that contains files if it matches with the wild card option.

**How to reproduce it**: Create a directory with a pattern that matches a wild card using glob

**Anything else we need to know**: Code from FileSensor source that I believe to cause the issue:

```
for path in glob(full_path):
            if os.path.isfile(path):
                mod_time = os.path.getmtime(path)
                mod_time = datetime.datetime.fromtimestamp(mod_time).strftime('%Y%m%d%H%M%S')
                self.log.info('Found File %s last modified: %s', str(path), str(mod_time))
                return True

            for _, _, files in os.walk(full_path):
                if len(files) > 0:
                    return True
        return False

```
I believe to resolve the issue `full_path` in os.walk should be `path` instead.

**Comment by potiuk** [comment]
Would you be willing to open PR for that ?

**Comment by uranusjr** [comment]
We should change the logic to use `pathlib.Path.glob()` instead, which automatically handles recursive globbing. (Or `glob.rglob()` but pathlib is easier to use IMO.)

**Comment by MrSandoman** [comment]
I can open a PR for the quick fix to substitute path for full_path in the walk, but I'm not very familiar with `pathlib.Path.glob()` to be able to make that change in the logic. Also never submitted a PR to a big project like Airflow before (pretty new to coding in general) so gotta go figure out that process.

**Comment by uranusjr** [comment]
Hmm, after reading the relevant code, `pathlib.Path.glob()` might not be the best choice. It’s easier to do `glob(full_path, recursive=True)` instead. So you’ll need to do that. After that, please follow the instructions in https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst to submit a pull request for your change.

**Comment by ShraddheyaS** [comment]
@uranusjr I have opened a PR https://github.com/apache/airflow/pull/16894 for resolving this using the `recursive=True` fix you mention above. Also verified with the new test added that the fix works (as expected, the test fails without the flag).

As a first time contributor, a workflow in the CICD pipeline is blocked on the PR. Can you please approve the workflow? Thanks!

**Comment by potiuk** [comment]
Running now

**Comment by 0sunny** [comment]
Can you please assign this to me ?
