### ISSUE TITLE
Custom headers not passible to send_email

### ISSUE THREAD

**Issue by dvd9604** [apache/airflow#16740]
Issue:
`custom_headers` is available as an optional keyword argument in `build_mime_message` but it is not exposed in `send_email` or `send_email_smtp`. This prevents using custom headers with the email operator when using the default smtp backend. 

https://github.com/apache/airflow/blob/8e2a0bc2e39aeaf15b409bbfa8ac0c85aa873815/airflow/utils/email.py#L105-L116

Expected:
`send_email` should take optional key word argument `custom_headers` and pass it to `send_email_smtp` if that is the selected backend.

**Comment by uranusjr** [comment]
Hi! Would you be interested in submitting a fix for this?

**Comment by dvd9604** [comment]
> Hi! Would you be interested in submitting a fix for this?

Yes, I would like to contribute to open source.

**Comment by eladkal** [comment]
@dvd9604 are you still working on this issue?
