### ISSUE TITLE
'httpx' dependency must be version constrained

### ISSUE THREAD

**Issue by besar22** [apache/airflow#16758]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Ubuntu Linux 4.15.0-126-generic

**What happened**:

running `airflow webserver` , produces
```
 File "~/.local/share/virtualenvs/airflow-venv/lib/python3.8/site-packages/airflow/_vendor/connexion/decorators/security.py", line 17, in <module>
    limits = httpx.Limits(max_keepalive_connections=100, max_connections=100)
AttributeError: module 'httpx' has no attribute 'Limits'
```
**What you expected to happen**:

Webserver should start

**How to reproduce it**:
```
pip install httpx==0.13.3 --force-reinstall
airflow webserver
```

**Anything else we need to know**:
from [httpx documentation](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0140-august-7th-2020) they updated httpx.Limits(). 

Therefore the apache-airflow should be restricted to run on more recent version of httpx. Currently it has no constrain and pip does not report a dependency error.

 I have not tested all versions that work. For me the latest one httpx==18.2 works.

Thank you

**Comment by potiuk** [comment]
You can always `--force-reinstall` any package to any version. Airflow should be installed using constraints. See the official installation documentation https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files - if you follow the guide, you get all the dependencies in the right version. If you force-reinstall a dependency after that - then, well  - you are on your own.

Each version of Airflow has corresponding set of constraints. For example the current `main` version's httpx is here https://github.com/apache/airflow/blob/constraints-main/constraints-3.6.txt#L273
