### ISSUE TITLE
Realtime ECS logging

### ISSUE THREAD

**Issue by pavelhlushchanka** [apache/airflow#16753]
**Description**

Currently when `ECSOperator` is run, the logs of the ECS task are fetched only when the task is done. That's not so convenient, especially when the task takes some good amount of time. In order to understand what's happening with the task, I need to go to Cloudwatch and search for the tasks logs. It would be good to have some parallel process that could fetch ECS task logs from Cloudwatch and make them visible in a realtime. 

**Are you willing to submit a PR?**

I can try, but I need to be guided.

**Comment by potiuk** [comment]
That would be cool. There is a great example you can use - we have such streaming stackdriver task handler implemented already for GCS/stackdriver. It should be very similar.

 https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/log/stackdriver_task_handler.py

**Comment by codenamestif** [comment]
@potiuk okay, you can assign to me, I will check what i can do

**Comment by codenamestif** [comment]
@potiuk i have checked the example and it looks like it's a bit different. From my understanding that task handler is used for logging for the operator. In the example writing of the logs can be sync/async depends on provided transport type. Reading is always synchronous. But anyway, in using ECSOperator we run a separated ECS task with a separated log stream. And what we need is to read logs from ECS task log stream and write them to ECSOperator logs.

That's the code from ECSOperator:
```
        self._wait_for_task_ended()

        self._check_success_task()
```

`self._wait_for_task_ended()` is blocking. And we read logs of the ECS task in `self._check_success_task()`. So my question is how to take the part that reads the logs from `self._check_success_task()` and have it running in parallel with ` self._wait_for_task_ended()`

The only idea I have is not to use standard boto3 waiter, but have some custom wait implementation that pulls the status of the task and also pulls the logs in the same iteration. But that doesn't sound good.

**Comment by potiuk** [comment]
Ah I see now.  I think you do not have to skip the waiter, it's quite likely you could be able to run separate thread reading the logs while the waiter waits.
