### ISSUE TITLE
Upgrade Check UseCustomSQLAInterfaceClassRule assumes view has datamodel

### ISSUE THREAD

**Issue by ofir-ov** [apache/airflow#16751]
**Apache Airflow version**: 1.10.15

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

Python Version: [3.8.8 (default, Mar 12 2021, 19:44:18)  [GCC 8.3.0]]
- **Cloud provider or hardware configuration**: Local, N/A
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)"
- **Kernel** (e.g. `uname -a`): Linux 1fa25678085e 5.10.25-linuxkit # 1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 GNU/Linux
- **Install tools**: N/A
- **Others**: `apache-airflow-upgrade-check==1.4.0`

**What happened**:

Running the script `airflow upgrade_check` fails with the following exception: 

```
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/upgrade/checker.py", line 118, in run
    all_rule_statuses = check_upgrade(formatter, rules)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/upgrade/checker.py", line 38, in check_upgrade
    rule_status = RuleStatus.from_rule(rule)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/upgrade/problem.py", line 48, in from_rule
    result = rule.check()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/upgrade/rules/use_customsqlainterface_class_rule.py", line 53, in check
    if not isinstance(view_obj.get("view").datamodel, CustomSQLAInterface):
AttributeError: 'MyPlugin' object has no attribute 'datamodel'
```

**What you expected to happen**: Expected the script to finish running and not exit half-way with an exception.

I assume the reason is that my plugin doesn't have a `datamodel` defined and the chcek `use_customsqlainterface_class_rule` expects one: https://github.com/apache/airflow/blob/86ce67fac14b3175d056adfca86881540834bacb/airflow/upgrade/rules/use_customsqlainterface_class_rule.py#L53

Note that in Airflow's own documentation a `datamodel` is not defined in `AppBuilderBaseView`: https://airflow.apache.org/docs/apache-airflow/stable/plugins.html

**How to reproduce it**:

The following plugin code, taken from Airflow's own documentation produces the same exception:

```python
from airflow.plugins_manager import AirflowPlugin
from flask import Blueprint
from flask_appbuilder import BaseView as AppBuilderBaseView, expose

class TestAppBuilderBaseView(AppBuilderBaseView):
    default_view = "test"

    @expose("/")
    def test(self):
        return self.render_template("test_plugin/test.html", content="Hello galaxy!")

v_appbuilder_package = {"name": "Test View",
                        "category": "Test Plugin",
                        "view": TestAppBuilderBaseView()}

bp = Blueprint(
    "test_plugin", __name__,
    template_folder='templates', # registers airflow/plugins/templates as a Jinja template folder
    static_folder='static',
    static_url_path='/static/test_plugin')


class AirflowTestPlugin(AirflowPlugin):
    name = "test_plugin"
    hooks = []
    macros = []
    flask_blueprints = [bp]
    appbuilder_views = [v_appbuilder_package]
    appbuilder_menu_items = []
    global_operator_extra_links = []
    operator_extra_links = []
```

**Anything else we need to know**: Don't think so, but if you do, lmk :)

**Comment by mik-laj** [comment]
Closing as there will be no more releases of upgrade check

If you run into problems with specific rules, you can turn them off. For details, see: http://airflow.apache.org/docs/apache-airflow/2.1.0/upgrade-check.html#turning-off-checks
