### ISSUE TITLE
DAG with KubernetesPodOperator induces weird CLI behaviour.

### ISSUE THREAD

**Issue by ypicard** [apache/airflow#16757]
**Apache Airflow version**: 2.0.2 (AWS MWAA)

**Environment**:

- **Cloud provider or hardware configuration**: AWS MWAA

**What happened**:

I have created 2 DAG files:
- one using only the `BashOperator`
- one using the `KubernetesPodOperator`

When executing the Airflow CLI command `dags list`, only the first DAG is listed. As soon as I remove the usage of the `KubernetesPodOperator` (and more specifically, its import: `from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator`), it is listed by the CLI. The DAG is always listed by the UI though.

Triggering the DAG with `dags trigger dag_id --run-id run_id` works.
Trying to show the state of one of its DAG runs with `dags state dag_id execution_date` does not work, and returns:
```
Error: Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/dag_command.py", line 229, in dag_state
    dag = get_dag(args.subdir, args.dag_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 191, in get_dag
    'parse.'.format(dag_id)
airflow.exceptions.AirflowException: dag_id could not be found: my_dag_id. Either the dag did not exist or it failed to parse.
```

**What you expected to happen**:
I expected all my DAGs to be listed by default, and I do not understand why the usage of the `KubernetesPodOperator` breaks this feature.

**How to reproduce it**:

First DAG:
```
from datetime import timedelta

from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.utils.dates import days_ago


default_args = {
    'owner': 'me',
    'depends_on_past': False,
    'start_date': days_ago(2),
    'email': ['airflow@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'tutorial',
    default_args=default_args,
    description='A simple tutorial DAG',
    schedule_interval=timedelta(days=1),
)

t1 = BashOperator(
    task_id='print_date',
    bash_command='date',
    dag=dag,
)

t2 = BashOperator(
    task_id='sleep',
    depends_on_past=False,
    bash_command='sleep 5',
    retries=3,
    dag=dag,
)

templated_command = """
{% for i in range(5) %}
    echo "{{ ds }}"
    echo "{{ macros.ds_add(ds, 7)}}"
    echo "{{ params.my_param }}"
{% endfor %}
"""

t3 = BashOperator(
    task_id='templated',
    depends_on_past=False,
    bash_command=templated_command,
    params={'my_param': 'Parameter I passed in'},
    dag=dag,
)

t1 >> [t2, t3]
```

Second DAG:
```
from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.python import PythonOperator
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator # breaks because of this line. Removing it fixes the issue.


default_args = {
   'owner': 'me',
   'depends_on_past': False,
   'start_date': datetime(2019, 2, 20),
   'provide_context': True
}

dag = DAG(
   'k8s', default_args=default_args, schedule_interval=timedelta(days=1))


def run_this_func(ds, **kwargs):
    print("Remotely received value of: {}".format(kwargs['dag_run'].conf))


run_this = PythonOperator(
    task_id='run_this',
    provide_context=True,
    python_callable=run_this_func,
    dag=dag,
)
```

**Comment by potiuk** [comment]
It looks like a bug in the MWAA package configuration. My wild guess is that `cncf.kubernetes` provider is missing in the container that is running the CLI of Airflow. @subashcanapathy  - that sounds vaguely familiar with the webserver not having all packages installed @ypicard - I am closing this one as invalid but what I can suggest is to open an issue in MWAA  issue tracking system for that.

**Comment by potiuk** [comment]
It looks like a bug in the MWAA package configuration. My wild guess is that `cncf.kubernetes` provider is missing in the container that is running the CLI of Airflow. @subashcanapathy  - that sounds vaguely familiar with the webserver not having all packages installed @ypicard - I am closing this one as invalid but what I can suggest is to open an issue in MWAA  issue tracking system for that.

**Comment by ypicard** [comment]
The thing is the DAG actually runs fine, so this implies the `cncf.kubernetes` package is present right?

**Comment by potiuk** [comment]
Not as long as the "container" used to run CLI  is different than that which runs workers/scheduler. From What I understand MWAA does not have the "raw" airflow CLI exposed, you can only use a subset of commands (https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-cli-command-reference.html#access-airflow-ui-prereqs-cli) and it is executed via some kind of web proxy (which might or might not have the same packages installed as worker and scheduler).

We know for a fact (discussion on slack and reason why connections for providers are not in the UI) that the container that runs webserver does not contain any of the providers installed by the user, My guess (wild yes) is this might be the same with the CLI proxy. I imagine it has just the airflow package and possibly some pre-installed providers but not more. But this is just hypothesis - I do not know much about MWAA internals. @subashcanapathy might comment if my guess is right or not :).

**Comment by ypicard** [comment]
Thank you, I think you are right.

AWS's support just answered me with some fresh new documentation, leaving it here: https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-cli-command-reference.html#parsing-support.
