### ISSUE TITLE
SagemakerProcessingOperator ThrottlingException

### ISSUE THREAD

**Issue by jimmycfa** [apache/airflow#16763]
**Apache Airflow version**: 2.0.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**: MWAA and Locally

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): NA
- **Kernel** (e.g. `uname -a`): NA
- **Install tools**: NA
- **Others**: NA

**What happened**:

When calling the SagemakerProcessingOperator sometimes get: "botocore.exceptions.ClientError: An error occurred (ThrottlingException)" due to excessive ListProcessingJobs operations.

**What you expected to happen**:

The job should have started without timing out. I believe one fix would be to use the `NameContains` functionality of boto3 [list_processing_jobs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.list_processing_jobs) so you don't have to paginate as is occurring [here](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/hooks/sagemaker.py#L916). 

**How to reproduce it**:

If you incrementally create Sagemaker Processing jobs you will eventually see the Throttling as the pagination increases.

**Anything else we need to know**:

This looks like it is happening when the account already has a lot of former Sagemaker Processing jobs.

**Comment by jimmycfa** [comment]
Realized this is already happening. Sorry! We are still seeing this issue but going to close until I do some more investigating.

**Comment by jimmycfa** [comment]
For posterity sake we are using boto3==1.17.99. This actually appears to be an issue with the way that NameContains filter gets applied:

The NameContains is getting passed into list_processing_jobs but it doesn't actually filter on the entire set of ProcessingJobs. It appears to filter per batch of 100 so you still end up calling the list_processing_jobs in that SagemakerOperator 30+ times back to back. Another way of saying this is if I specify NameContains in the list_processing_jobs with a job name that doesn't exist and I have over 3500 processing jobs it will return an empty set of ProcessingJobSummaries BUT still includes a NextToken. It will do this 35 more times as the max results = 100 for that call and you likely run into Throttling issues.

I believe the expected behavior of that boto3 call should be the NameContains filter should be being applied to the entire set of jobs and then returning results vs per batch so that the first call through returns an empty set for ProcessingJobSummaries and NO NextToken.

I'm going to reopen but this does appear to be a boto3 issue.

**Comment by potiuk** [comment]
Since we have a solution here - which appears to be applicable by everyone, I think it should be closed. Alternatively mayb you could add the solution above as a comment to the documentation of the SageMaker Operator @jimmycfa ?
