### ISSUE TITLE
Deprecation warning on Sqlite operator

### ISSUE THREAD

**Issue by BertCatsburg** [apache/airflow#16791]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): No Kubernetes

**Environment**: Docker on OSX

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): OSX
- **Kernel** (e.g. `uname -a`): (In the Docker Container) : Linux e06c1b70e310 5.10.25-linuxkit 1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 GNU/Linux
- **Install tools**: Docker-compose, following the Airflow docs
- **Others**:

**What happened**:
When running a DAG using the SQLite Operator, I get a DeprecationWarning on the SQLite Operator. 
This is the line in Python: 
```python
from airflow.providers.sqlite.operators.sqlite import SqliteOperator
```

And this is the message in the logfile:
```bash
[2021-07-03 08:52:31,107] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/sqlite/operators/sqlite.py:25 DeprecationWarning: This decorator is deprecated.
```

But according to the Airflow Docs the SQLiteOperator is imported from airflow.providers.sqlite.operators.sqlite

Why the DeprecationWarning?

**What you expected to happen**:

No Deprecation Warning, since I'm using the latest import for Sqlite

**How to reproduce it**:

- Install Airflow for Docker, following the Docs. 
- Create an empty DAG with the import statement in it 
- Run the DAG
- Check the logfile

**Comment by potiuk** [comment]
Please upgrade to latest version of sqlite provider or (even better) to latest 2.1.1 version of Airflow which already has consraints set to include latest provider versions (released last night). 

The warning is about deprecated "apply_defaults" decorator not import and with 2.1.0 'apply_defaults' is not needed any more - so we recently released all providers without "apply_default" decorator - for example for sqlite: https://airflow.apache.org/docs/apache-airflow-providers-sqlite/stable/index.html#breaking-changes.
