### ISSUE TITLE
How Do I Access Configuration Values from the airflow.cfg File?

### ISSUE THREAD

**Issue by r39132** [apache/airflow#168]
I would like to use include the base_url in emails that I send via from flow. The base_url is defined under the `webserver` section of the config in airflow.cfg

What's the easiest way to these variables in any operator? Currently, I send email using my own PythonOperator (so that I can send both text and html multipart email). Hence, I access the config using the code below.

```
    parser = SafeConfigParser()
    parser.read('airflow.cfg')
    base_url = parser.get('webserver', 'base_url')
```

This works, but I was wondering if there is a more elegant way? Also, this only works for PythonOperators, but what if I need to access a configuration parameter in any operator in a Jinja template?

**Comment by mistercrunch** [comment]
It's easy for me to throw it in the context. Here's the PR:
https://github.com/airbnb/airflow/pull/169

**Comment by r39132** [comment]
Hi! I see the change in documentation, but didn't see a material change to the code. It's late, so I might have missed something. 
-s

**Comment by mistercrunch** [comment]
I added a line comment to point out which line makes the difference

**Comment by r39132** [comment]
Great... replaced 4 lines of code (including an import) with one. 
`base_url = kwargs['conf'].get('webserver', 'base_url')`

Thx
