### ISSUE TITLE
Change failed DAG log level

### ISSUE THREAD

**Issue by Prasnal** [apache/airflow#16807]
**Apache Airflow version**: 2.0.2

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- **Kernel**: Linux 4.15.0-54-generic 
- **Install tools**: Docker
- **Others**:

**What happened**:

```
Marking run <DagRun <name> @ 2021-07-04 20:00:59+00:00: scheduled__2021-07-04T20:00:59+00:00, externally triggered: False> failed
```
Every time when task is failing I'm getting this error message. That generates a lot of noise on sentry.

**What you expected to happen**: 

I expect failing DAG as a warning. Failing DAG is a normal behavior from Airflow perspective so it shouldn't be considered as error. I think this line should be changed: [](https://github.com/apache/airflow/blob/5034414208f85a8be61fe51d6a3091936fe402ba/airflow/models/dagrun.py#L430)

**How to reproduce it**:
Run any failing DAG.

**Comment by uranusjr** [comment]
Do you mean a failing DAG *run*? Because a DAG that fails is pretty critical.

IMO a failed DAG run is also very notification-worthy, because Airflow does not know why a run failed, and it might be something critical the user does not expect. If you expect something to happen, you should handle it in the DAG so it does not fail (and write a warning-level log message in the handler).

**Comment by Prasnal** [comment]
Ok, I understand.
In my case, sometimes business logic fails because of external dependencies. In this situation we need to fix the issue somewhere else before we retry the DAG. It means that I'm raising Exception and want to get this DAG run failed (as the job was not done) but in sentry I'm getting doubled errors - one with my Exception and the other one with Airflow error message. Do you have any suggestion what I can do in this case?

**Comment by uranusjr** [comment]
We could potentially reduce logging so you only get one entry for the exception. But you’ll need to provide a bit more context, including what is the operator configuration you are using, what logs are emitted for the entire task run when it fails, and what you want and what you don’t want to see, so we can get a better picture of things.

**Comment by Prasnal** [comment]
Sorry for my late reply.
More details:
Operator type: PythonOperator
It's not log when I fail the DAG run, it's just Python Exception that I throw in method that I pass as callable argument in PythonOperator constructor.
I would like to see only my exception, without additional generic error log "Marking Dag failed".

**Comment by eladkal** [comment]
Can you show an example of your log today in compare to how you want it to be?
