### ISSUE TITLE
Initiating `mark success/failed` operation causes UI border to disappear for task instances with no status

### ISSUE THREAD

**Issue by edwardwang888** [apache/airflow#16824]
**Apache Airflow version**: 2.1.1

**Environment**: Docker setup from Installation page

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Mac OS 11.4, but similar behavior occurs in Airflow 1.10.4 on Ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Docker
- **Others**:

**What happened**:
After adding new tasks to an existing DAG, the newly added tasks appear as task instances in existing DAG runs with `no_status`. These usually appear as a white box with a black border. However, after initiating the `mark success/failed` operation, the black border disappears from all task instances with `no_status` in that particular DAG run.

**What you expected to happen**: The black border should remain.

**How to reproduce it**:
1. Create DAG with at least one DAG run.
![image](https://user-images.githubusercontent.com/40527812/124538043-d9fae780-ddcf-11eb-8064-ec5038815a19.png)

2. Add new tasks to the DAG.
![image](https://user-images.githubusercontent.com/40527812/124538088-e67f4000-ddcf-11eb-9b61-92a65d75e1e5.png)
 
3. Initiate the `mark success/failed` operation on any task instance.
  - Here, I initiated the `marked failed` operation on `dummy1a` and `dummy1b` for the latest DAG run.
![image](https://user-images.githubusercontent.com/40527812/124538183-0a428600-ddd0-11eb-83d3-243ef85918b7.png)

4. At this point, you can click `OK!`/`Cancel`, or simply exit the page. As long as the `mark success/failed` operation has been initiated, the issue occurs.
I chose to click `Cancel`, so no statuses were changed. However, ALL task instances with `no_status` in that particular DAG run lose their black borders.
  - This occurs regardless of the number of tasks instances being marked as success/failed.
  - The `mark success/failed` operation does not need to be initiated on a task instance with `no_status`. Initiating it on any task instance (including `dummy0a` or `dummy0b`) affects all `no_status` task instances in that DAG run.
![image](https://user-images.githubusercontent.com/40527812/124538244-2514fa80-ddd0-11eb-9730-077652bf9a02.png)

**Anything else we need to know**: If after the above steps, I add additional tasks, the additional `no_status` task instances would have borders while the task instances without borders still do not have borders. Then, if I initiate another `mark success/failed` operation, the remaining `no_status` task instances would lose their borders.
![image](https://user-images.githubusercontent.com/40527812/124558077-125dee00-ddef-11eb-86b1-fc1022c5c0f2.png)

**Comment by edwardwang888** [comment]
Upon further investigation, this appears not to be primarily a UI bug, but rather an issue with the existence of task instances in the `task_instances` table.

It seems that if a task instance does not exist in the `task_instance` table, the UI will display it as `no_status` (with the black border). However, upon initiating a `mark success/failed` operation, the non-existent task instances for that DAG run are created in the `task_instance` table with `state` = `NULL`. This does not get identified as a `no_status` task instance, and thus is not drawn properly.

**Comment by bbovenzi** [comment]
That makes sense to me. If anything, it should render the other way around: non-existent tasks are just blank with no outline. We can still handle this in `tree.js` of the UI.

**Comment by edwardwang888** [comment]
I actually prefer having non-existent tasks still render with the outline, the reason being that after adding a task, there is sometimes a need to mark the non-existent tasks as success/failed - so being able to still see the outline is still useful.

It also seems that non-existent tasks and tasks with `null` state are essentially treated the same (by the scheduler), so it may be misleading to display them differently in the UI.

**Comment by edwardwang888** [comment]
A few more observations:
- I think the missing borders are due to the run being a manual run - the borderless white box is meant to display when the task instance previously existed but has been cleared. (In this case, the non-existent task instances are incorrectly added to the DB to make them appear as if they previously existed.)
- Non-existent tasks and tasks with `null` state actually are actually not equivalent - the way the scheduler treats them seems to depend on whether the DAG run is manual/scheduled.
- The bug above disappears once there is at least one schedule DAG run.

I think it may be better to separate the backend DB bugs to another issue.

In terms of the UI, I guess the main consideration is whether to add a border when the run is manual but the box color is white?

**Comment by bbovenzi** [comment]
Let's separate the backend and frontend bugs into their own issues.
I think we should at least stay consistent with however we do borders.

**Comment by edwardwang888** [comment]
I created a new issue for the border behavior. I will investigate the backend bugs further and open a separate issue.

**Comment by bbovenzi** [comment]
I believe this is now fixed by #18675
