### ISSUE TITLE
Airflow dashboard cannot load logs containing emoji

### ISSUE THREAD

**Issue by internetcoffeephone** [apache/airflow#16834]
**Apache Airflow version**:
2.1.0

**What happened**:
When printing emoji to a DAG log, the Airflow dashboard fails to display the entire log.
When checking the output log in the Airflow dashboard, the following error message appears:

> *** Failed to load local log file: /tmp/dag_name/task_name/2021-07-06T10:49:18.136953+00:00/1.log
> *** 'ascii' codec can't decode byte 0xf0 in position 3424: ordinal not in range(128)

**What you expected to happen**:
The log should be displayed.

**How to reproduce it**:
Insert the following into any Python DAG, then run it.
`print("💼")`

**How often does this problem occur?**
Every log with an emoji in it prints an error.

**Why would anyone even want to print emoji in their logs?**
When they're part of the dataset you're processing.

**Comment by potiuk** [comment]
It would be great to standardise encoding to "utf-8" (default) when writing and reading logs. Seems like this should be a good first issue for someone. @internetcoffeephone - maybe you would like to contribute a fix for that?

**Comment by alokshenoy** [comment]
I can take this one up.

**Comment by potiuk** [comment]
Feel free :). Assigned you to it!

**Comment by alokshenoy** [comment]
Yep. I'll have a pr out in the next few days.

**Comment by Narendra-Neerukonda** [comment]
I see this issue is already assigned to @alokshenoy. Hence, please feel free to cancel this PR #17965  if needed.

I've had the same issue a few days ago. There is no problem while writing the logs. Hence, only read part needs to be fixed.
