### ISSUE TITLE
/dag/{dag_id} returns stale dags without its serialized version unlike /dags/{dag_id}/details

### ISSUE THREAD

**Issue by psg2** [apache/airflow#16839]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

After removing a dag from the filesystem, Airflow cleans up the SerializedDags table and updates the DAG table to mark the DAG with is_active as False. If you call the /dag/{dag_id} endpoint with the removed dag_id, it will return the stale information about the dag, but if you call the /dag/{dag_id}/details you will receive and 404 error Dag Not Found.

Slack thread: https://apache-airflow.slack.com/archives/CCPRP7943/p1625504228302500

**What you expected to happen**:

Receive a 404 Dag Not Found on /dag/{dag_id} as well.

**How to reproduce it**:

1. Write a DAG file
2. Wait for Airflow to parse it
3. Remove the file
4. Call the API

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Endpoint `/dag/{dag_id} ` returns the active DAGs by default. If you want access to all DAGs, you must use the is_active parameter. To access all DAGS - both active and inactive, you should pass `in_active` parameter.  Thanks to this, you can access archived data, but by default, you have consistent UI with CLI (`airflow dags list`) and Web UI (`/home/`).

**Comment by potiuk** [comment]
Closed as per conversation in #16842
