### ISSUE TITLE
Chart: Add docs on using custom pod-template

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#16833]
Currently, we allow users to use their own `podTemplate` yaml using the `podTemplate` key in `values.yaml`. Some users have passed the name of the file in `podTemplate` instead of YAML string.

We should have a dedicated page on how a user could do that and add an example in `values.yaml` file itself.

https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html

https://github.com/apache/airflow/blob/81fde5844de37e90917deaaff9576914cb2637ee/chart/values.yaml#L1123-L1125
https://github.com/apache/airflow/blob/81fde5844de37e90917deaaff9576914cb2637ee/chart/templates/configmaps/configmap.yaml#L59-L65

**Comment by gmsantos** [comment]
Does make sense to support helm templates in `podTemplate`? As of today, there is no easy way to customize the`files/pod-template-file.kubernetes-helm-yaml` content.

**Comment by jedcunningham** [comment]
Yeah, passing `podTemplate` through `tpl` makes sense to me.

What is your use case for modifying the template though? Most of the "normal" scenarios I can think of off the top of my head are pretty much already covered. I'd love to hear it so we can consider how best to support whatever it is.

**Comment by gmsantos** [comment]
Something I'm missing is to define a sidecar container or specific resources requests and limits for Airflow tasks on top of the generated pod template file.

Giving an extra context, internally we allow teams to deploy data platform instances in a K8s cluster and the Airflow chart is the main component of it. One goal is to abstract Airflow base configuration and other components in a custom chart with recommended default values.

**Comment by jedcunningham** [comment]
Cool, thanks. For resources you can use `workers.resources`. `workers.extraContainers` isn't automatically added to k8s workers, but it probably should be (with a warning that you are on your own for stopping the sidecar so Airflow can continue its shutdown process).

**Comment by jedcunningham** [comment]
@gmsantos, in the next release `podTemplate` can be templated and `workers.extraContainers` will be added to k8s workers automatically. Thanks!

**Comment by kaxil** [comment]
Is this still pending, if yes can you take this over @dstandish

**Comment by dstandish** [comment]
sure think
