### ISSUE TITLE
Rest API: allow filtering DagRuns by state.

### ISSUE THREAD

**Issue by gyscos** [apache/airflow#16844]
**Add state filter to the dag runs list API endpoint**

One feature available in the "Browse / Dag Runs" page but not in the current rest API is the ability to filter runs of a specific state(s).

Example use-case: this would let a client efficiently fetch the number of "queued" and "running" runs, or look at recent failed runs.

Ideally, the current `/dags/{dag_id}/dagRuns` and `/dags/~/dagRuns/list` endpoints would each get updated to support an additional parameter called `state`. This parameter could be given multiple times and act as a logical "OR" (just like `dag_ids` in the POST endpoint, or like `state` in the task instances endpoint).

The web UI page offers more fancy filters like "includes", but for something with a finite number of values like `state`, it doesn't feel necessary for the API.

**Comment by uranusjr** [comment]
Hi! Would you be interested in submmitting a pull request for this?

**Comment by gyscos** [comment]
I can try? Tentatively sent #16845 for that.

**Comment by fbertos** [comment]
Hi @uranusjr, I think we can now close this one as it is linked to PR: https://github.com/apache/airflow/pull/20485
Thanks!

**Comment by uranusjr** [comment]
I’ve linked #20697 to automatically close this once it’s merged, that change should be the lst missing piece to completion of this feature.
