### ISSUE TITLE
Configurable KubernetesPodOperator XCom sidecar container

### ISSUE THREAD

**Issue by mgorsk1** [apache/airflow#16850]
**Description**

Since Airflow 2 we get a lot of customization options for pods spawned using `KubernetesPodOperator`. There is, however, one area in which nothing has changed and it's `xcom_sidecar_container`. Currently, all of the specs for it are hardcoded in `PodDefaults` class.

This issue is meant to start discussion and to possibly shape the end solution enabling configuration of xcom side container (unless there is a feeling it's not needed).

**Use case / motivation**

We are running on self-hosted k8s with own docker repository (JFrog artifactory) and in our current setup we are required to spawn pods using full path to the repo - we cannot do `docker pull alpine` but need to do `docker pull arficatory.domain/registry/alpine`.

**Are you willing to submit a PR?**

Yes, but could use some points, discussion on what would be the acceptable target solution.

**Related Issues**

n/a

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10605
