### ISSUE TITLE
Cleared task instances in manual runs should have borders

### ISSUE THREAD

**Issue by edwardwang888** [apache/airflow#16877]
**Description**

Task instances in manual runs do not display with a border, except when the task instance is non-existent (after adding tasks to an existing DAG). Hence, when an _existing_ task instance is cleared, it is displayed without a border, causing it to disappear into the background. To be consistent, existing task instances that are cleared should also be drawn with borders.

Here, `task2a` and `task2b` are newly-added tasks and have `no_status`. They are displayed with borders:
![image](https://user-images.githubusercontent.com/40527812/124863865-ba4cf600-df6c-11eb-932f-f2515ecb3914.png)

Afterwards, `task1a` and `task1b` are cleared and lose their borders:
![image](https://user-images.githubusercontent.com/40527812/124863991-fb450a80-df6c-11eb-8a5c-f9a0ca6b478e.png)

**Use case / motivation**

To prevent the task instances from disappearing into the background.

**Are you willing to submit a PR?**

Yes, but would need ramp-up time as I am new to front-end.

**Related Issues**

Split from #16824.

**Comment by bbovenzi** [comment]
@edwardwang888 Are you on the airflow slack? I'd be happy to help you get up and running with the frontend :)

**Comment by edwardwang888** [comment]
@bbovenzi Sounds good, I will join the Airflow slack! I will be busier for the next week but I will get started on this in a bit.

**Comment by edwardwang888** [comment]
@bbovenzi Sorry for the delay. I have my local development environment setup now, and am playing around with `tree.js`. I will reach out on Slack if I have any questions!

**Comment by edwardwang888** [comment]
@bbovenzi Do we usually add tests for cosmetic changes like this one? From a quick skim of the UI tests, it looks like they are mostly focused on the functional aspects of the UI. My changes also did not break any tests, so I am guessing this part of the code is not currently tested?

**Comment by bbovenzi** [comment]
Yeah, you shouldn't have to worry about tests for this.

**Comment by edwardwang888** [comment]
@bbovenzi The PR should be ready now. Let me know if you have any comments. Thanks!
