### ISSUE TITLE
Show duration of a task group

### ISSUE THREAD

**Issue by armandduijn** [apache/airflow#16887]
**Description**

Show the duration of the task group in the Airflow UI.

![image](https://user-images.githubusercontent.com/706385/124945371-5e3aae00-e00e-11eb-8050-6fa988e09191.png)

**Use case / motivation**

The task groups are a nice way to encapsulate multiple tasks. However, in the Graph view, the duration of the grouped tasks isn't visible. You need to expand the group to view them.

It's possible to view the task durations in the Task Duration view, but that isn't as convenient if you want to zoom in on a particular section of the pipeline.

**Are you willing to submit a PR?**

Yes, but I'm not familiar with the codebase. If it a relatively easy fix, I would appreciate some guidance on which files to touch.

**Related Issues**

None

**Comment by bbovenzi** [comment]
@armandduijn great idea! I'm happy to point you to the right place on where to fix it.
