### ISSUE TITLE
List User UI in security is broken

### ISSUE THREAD

**Issue by saurasingh** [apache/airflow#16898]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): AWS EKS, AWS ECS

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I have enabled RBAC and using FAB OAUTH to authenticate users using AZURE AD. Users are able to sign-in using Azure SSO. I have referenced my webserver config file from https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/oauth/config.py with OAUTH_PROVIDER as Azure.

Now all our users are acquiring role ADMIN and I am not able to edit their role to other available roles as there is no edit option coming in the List USER page. My user to have an ADMIN role.  

![Screen Shot 2021-07-08 at 10 07 05 AM](https://user-images.githubusercontent.com/19628707/125004469-926e9880-e027-11eb-8c9c-2d370f61b2be.png)

**What you expected to happen**:

As ADMIN is having  `can edit on UserOAuthModelView`  permission I should be able to edit the roles for different users. 

**How to reproduce it**:

**Anything else we need to know**:

**Comment by misurin** [comment]
In my case, I am able to list users, but there is no edit, delete buttons shown.

**Comment by saurasingh** [comment]
@potiuk @kaxil Something has changed in 2.1.0 and migrated to 2.1.1 as well. A lot of people are facing the same issue. https://github.com/dpgaspar/Flask-AppBuilder/issues/1667  Can you guys look into this?

**Comment by jedcunningham** [comment]
Thanks for the report @saurasingh and @misurin!

Duplicate of #16202

(I'm going to add the FAB link into that issue to, but feel free to add anything else I overlooked)
