### ISSUE TITLE
Problem with starting airflow

### ISSUE THREAD

**Issue by ivanmiloj** [apache/airflow#16897]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by jedcunningham** [comment]
@ivanmiloj, please open another issue with details if you have something to report. Thanks.
