### ISSUE TITLE
Add a SalesforceToS3Operator to push Salesforce data to an S3 bucket

### ISSUE THREAD

**Issue by josh-fell** [apache/airflow#16891]
**Description**
Currently an operator exists to copy Salesforce data to Google Cloud Storage (`SalesforceToGcsOperator`) but a similar operator for an S3 destination is absent.  Since S3 is widely used as part of general storage/data lakes within data pipelines as well as Salesforce to manage a slew of marketing, customer, and sales data, this operator seems beneficial.

**Use case / motivation**
Undoubtedly there are use cases to extract Salesforce into an S3 bucket, perhaps augmenting a data warehouse with said data downstream, or ensuring the data is sync'd to a data lake as part of a modern data architecture.  I imagine users are currently building custom operators to do so in Airflow (if not taking advantage of an external service to handle the copy/sync). Ideally this functionality would be included within the AWS provider as well as help provide some feature parity with Google Cloud in Airflow.

**Are you willing to submit a PR?**
Yes 🚀 

**Related Issues**
None that I can find.

**Comment by potiuk** [comment]
Assigning you then :)
