### ISSUE TITLE
Add tests suite for MariaDB 10.6+ and fix incompatibilities

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#16907]
It seems that MariaDB 10.6 has added support for SKIP...LOCKED, so we could theoretically easily officially support MariaDB database (possibly with fixing some small issues resulting for test suite execution).

It would require to add `mariadb` backend similarly as we added `mssql` backend in those three PRs: #9973, #16103, #16134

**Comment by subkanthi** [comment]
I would like to take a shot at this

**Comment by potiuk** [comment]
Feel Free!

**Comment by eladkal** [comment]
@potiuk i belive we can close this one now?
