### ISSUE TITLE
Unable to connect to Kubernetes cluster from Airflow

### ISSUE THREAD

**Issue by jpatel-fpmx** [apache/airflow#16909]
**Apache Airflow version**: v2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):-
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: Development

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I am unable to connect to my Kubernetes cluster from Airflow while using SparkKubernetesOperator. I have hosted Airflow and Spark-operator on EKS. I have created a connection on Airflow to connect to kubernetes cluster by using "in cluster configuration".
I am just running the sample application just to check the execution of spark on Kubernetes through Airflow. Please find below the sample application link:-
https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/example_dags/example_spark_kubernetes.py

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"sparkapplications.sparkoperator.k8s.io is forbidden: User \"system:serviceaccount:***:***-cluster\" cannot create resource \"sparkapplications\" in API group \"sparkoperator.k8s.io\" in the namespace \"spark-operator\"","reason":"Forbidden","details":{"group":"sparkoperator.k8s.io","kind":"sparkapplications"},"code":403}

**What you expected to happen**:
Kubernetes Airflow should schedule and run spark job using spark operator.

The Airflow Kubernetes connection is not working.

**How to reproduce it**:
1. Deploy Spark operator using helm on Kubernetes cluster.
2. Deploy Airflow using helm on Kubernetes cluster.
3. Deploy below application by writing Airflow DAG:-
https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/example_dags/example_spark_kubernetes.py

**Anything else we need to know**:

**Comment by potiuk** [comment]
Apparently you have problem with permissions in your deployment. You need to configure your service account to have access to create resources.

**Comment by potiuk** [comment]
If you want to discuss and get some help it's  better to open a 'GitHub Discussion' or discuss it on slack, rather than opening an issue

**Comment by jpatel-fpmx** [comment]
Thanks @potiuk for your suggestion.

I have tried by creating a service account with cluster edit permission but still, the SparkApplications pod is not getting spin up.

As per your suggestion, I have open a 'GitHub Discussion' (https://github.com/apache/airflow/discussions/16940) with complete details. So requesting you to have a look and suggest me to get rid of this issue. I am stuck due to this.

**Comment by potiuk** [comment]
I am not sure I can help (not my area). But possibly someone who looks at it will.
