### ISSUE TITLE
SQL query in Airflow job differs from that in yaml

### ISSUE THREAD

**Issue by aaron-ang** [apache/airflow#16906]
-->

**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: 

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`): 5.4.0-1041-aws
- **Install tools**:
- **Others**:

**What happened**: After a SQL CTE, the next select statement is not captured by the Airflow job, causing the SQL to produce an error as the structure is altered

**What you expected to happen**: Expected the job to capture the whole SQL query in the yaml file entirely

**How to reproduce it**: Use a Qualify statement(using Snowflake ANSI SQL) right before the end of the CTE in a yaml file

**Anything else we need to know**: Issue occurs and is causing failure in every run
Screenshots:
<a href="https://ibb.co/ssmKmtj"><img src="https://i.ibb.co/HGFtFX7/Screenshot-2021-07-08-at-11-19-07-PM.png" alt="Screenshot-2021-07-08-at-11-19-07-PM" border="0"></a>

<a href="https://ibb.co/b5W6jKN"><img src="https://i.ibb.co/VYjL0qM/Screenshot-2021-07-08-at-11-19-35-PM.png" alt="Screenshot-2021-07-08-at-11-19-35-PM" border="0"></a>

**Comment by potiuk** [comment]
Like in all sql dialects, you need to separate statements with `;`. I believe snowflake hook supports it already. Make sure to use the latest snowflake provider, as there were some improvements in this part. https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html

**Comment by aaron-ang** [comment]
@potiuk do you mean inserting a `;` right after the CTE? My entire query consists of a CTE, along with a select statement. It does not make sense to break them apart using `;`

**Comment by aaron-ang** [comment]
perhaps I should share the structure of my query to make myself clearer. My query works perfectly in Snowflake, but when it is picked up by Airflow, it gets cut off.

`
WITH SCFS_COMPANIES AS (
  select...
  from...
  where...
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ... DESC) = 1
)
select ...
from...
`
Unless there is something regarding semicolon rules that I am unaware of? Thanks.
