### ISSUE TITLE
Tried to install the Airflow on the ubuntu machine but I am getting the following error

### ISSUE THREAD

**Issue by SHIVAPRASAD96** [apache/airflow#16910]

**Comment by potiuk** [comment]
Can you please - for the future avoid opening issue for this kind of problem? "Discussions" or slack are much better to discuss problems with your setup. 

You have not run 'airflow db init`

**Comment by potiuk** [comment]
Also. If you create issues, you have template to follow and you did not follow it - next time when you report bug or feature request please follow the right template. This is not really good for everyone involved to not follow the template/purpose of issues..
