### ISSUE TITLE
Upgrade to latest requests when it is released without chardet dependency

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#16929]
As discussed at length in https://issues.apache.org/jira/browse/LEGAL-572  we found out that the chardet library used by requests library was a mandatory dependency to requests and since it has LGPL licence, we should not release any Apache Software with it. 

Since then (and since in Airflow we rely on requests heavily) we have been working with the requests maintainers and "charset-normalizer" maintainer to make it possible to replace chardet with MIT-licensed charset-normalizer instead so that requests library can be used in Python releases by Apache projects.

This was a bumpy road but finally the PR by @ashb has been merged: https://github.com/psf/requests/pull/5797 and we hope soon a new version of requests library will be released. 

Once the new release is ready we should bump to the new version and we should help with testing when RC is available.

**Comment by uranusjr** [comment]
Did #16974 resolve this?

**Comment by potiuk** [comment]
oh yeah

**Comment by potiuk** [comment]
New requests 2.26.0 released and we switched to it ! Yay.
