### ISSUE TITLE
omething bad has happened. Please consider letting us know by creating a bug report using GitHub.  Python version: 3.8.10 Airflow version: 2.1.0 Node: DESKTOP-N1S0KHS.localdomain ------------------------------------------------------------------------------- Traceback (most recent call last):   File "/home/codebind/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context     self.dialect.do_execute(   File "/home/codebind/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute     cursor.execute(statement, parameters) sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by Prabhuddha** [apache/airflow#16920]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
You have corrupted image for sqlite.delete it.
