### ISSUE TITLE
Include `Authlib` in Airflow Docker images

### ISSUE THREAD

**Issue by vkostyuk** [apache/airflow#16944]
**Description**

`Authlib` is required for FAB authentication. Currently, it's not included in the Airflow images and must be pip installed separately. It's a small package supporting core functionality (Webserver UI authentication), hence would make sense to include.

**Comment by potiuk** [comment]
Would you like to make a PR with it @vkostyuk ? Should not be too difficult to find the right place in ethe Dockerfile (same thing should be done in Dockerfile.ci)

**Comment by potiuk** [comment]
I have some clarification/real fix coming - the original fix was not really good, it still had the old dependencies linked which are not needed any more in FAB 3.
