### ISSUE TITLE
backfill API can not backfill at time 00:00  if set default_timezone=Asia/Shanghai

### ISSUE THREAD

**Issue by yyhecust** [apache/airflow#16961]
**Description**

We want use backfill api to create a backfill task_instance when execution_date = "2021-07-13 00:00:00"(for example) if set default_time=Asia/Shanghai

**Use case / motivation**

In my application, we set default_time=Asia/Shanghai in airflow.cfg. when we use backfill API and set start_date=2021-07-13 00:00:00 and end_date=2021-07-13 00:00:00, also the dag's start time at 00:00, we want it can create a success state backfill task_instance, but it only create a None state task_instance record in DB, until we execute the same backfill command again, the backfill task_instance will running and success. we want it can be succeeded at first time we execute backfill command.

**Are you willing to submit a PR?**

Yes, I am willing to.

**Related Issues**

**Comment by eladkal** [comment]
Feel free to open PR @yyhecust

**Comment by eladkal** [comment]
Should be solved by https://github.com/apache/airflow/pull/16809
