### ISSUE TITLE
GCStoGCS operator not working when replace=False and source_object != destination_object

### ISSUE THREAD

**Issue by aslantar** [apache/airflow#16967]
The GCStoGCS operator using the _replace=False_ flag and specifying _source_object != destination_object_, will not work properly, because it is comparing [apples](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/transfers/gcs_to_gcs.py#L351) with [pears](https://github.com/apache/airflow/blob/0dd70de9492444d52e0afaadd7a510fc8a95369c/airflow/providers/google/cloud/transfers/gcs_to_gcs.py#L357).

Cause: the _prefix_ in the _pears_ case needs to be calculated from the _destination_object_, however, it is coming from the _source_object_.

**Comment by aslantar** [comment]
Possible solution:
```
existing_objects = hook.list(self.destination_bucket, prefix=prefix_, delimiter=delimiter)

# add an additional case
if self.destination_object is not None:
    existing_objects = existing_objects.replace(prefix_, self.destination_object, 1)

objects = set(objects) - set(existing_objects)
```

**Comment by potiuk** [comment]
Would you like to provide a PR with a fix @aslantar - happy to review it.

**Comment by aslantar** [comment]
Yes. I never contributed, but I'll find out and let you know.

**Comment by aslantar** [comment]
@potiuk From my side it is ready for review #16991. I'd especially be interested how I can improve wrt. your coding guidelines.
