### ISSUE TITLE
Support run multiple sql statements from file in DBApiHook

### ISSUE THREAD

**Issue by flolas** [apache/airflow#16979]
**Description**

Support run multiple sql statements from file in ~JdbcOperator~ DBApiHook, when the provided file has multiple statements (we can check it with https://github.com/andialbrecht/sqlparse)

**Use case / motivation**

Running single sql file with multiple sentences with JdbcOperator or any other DBApi operator (uses run method from DbApiHook, maybe we can implement here or in JdbcOperator):

**Are you willing to submit a PR?**
yes

**Comment by potiuk** [comment]
One comment - this should be done on DBAPI hook, not in JdbcOperator. This way all DB operators will be able to use it. Assigning you to it :)

**Comment by grahovam** [comment]
I am already using the PostgresOperator and MySqlHook to execute SQL queries that contain multiple queries seperated by semicolons. And both the operator and the hook use DbApiHook for doing so. Am I missing something here? Thank you for any clarification.

**Comment by eladkal** [comment]
> I am already using the PostgresOperator and MySqlHook to execute SQL queries that contain multiple queries seperated by semicolons. And both the operator and the hook use DbApiHook for doing so. Am I missing something here? Thank you for any clarification.

Assuming you have a SQL script:
`Select 1; Select 2;` Both Postgres and MySQL are able to execute this script. However you will not be able to execute this script in Snowflake, Presto nor Trino. This is why for these databases we first parse the script and break the statements one by one:

https://github.com/apache/airflow/blob/6ab00bfcfdfe1213928281527f32ca31b77cce1b/airflow/providers/trino/hooks/trino.py#L111-L112

https://github.com/apache/airflow/blob/6ab00bfcfdfe1213928281527f32ca31b77cce1b/airflow/providers/snowflake/hooks/snowflake.py#L276-L277

After that we can execute the statements one by one.


I think though there is a catch here. Executing `Update table a ... ; Update table b...;` may not the same as executing `Update table a ... ;`  and then executing `Update table b...;` when we break the statements there is a question of when the `commit(s)` gets executed.

**Comment by grahovam** [comment]
So the idea here is to not break the statements (and execute one by one) inside `TrinoHook` nor `SnowflakeHook` anymore and therefore break the statements (and execute one by one) inside `DBApiHook`?

**Comment by potiuk** [comment]
Yeah. Sounds like the third time is the charm

**Comment by potiuk** [comment]
Hey @flolas - how is it going ? I saw a few people interested in it :)

**Comment by flolas** [comment]
@potiuk Hi! I will work this week on the PR.

**Comment by eladkal** [comment]
Should be covered fully by https://github.com/apache/airflow/pull/23971
