### ISSUE TITLE
Rendered Templates - py renderer doesn't work for list or dict

### ISSUE THREAD

**Issue by jordanjeremy** [apache/airflow#16976]
**Apache Airflow version**: 2.1.1

**What happened**:

The rendered templates screen doesn't show the operator arguments for TaskFlow API operators.
![image](https://user-images.githubusercontent.com/72943478/125486179-f6dde0be-9f60-4aca-831a-5cfd16e7f006.png)

**What you expected to happen**:

Should show the arguments after any templates have been rendered.

**How to reproduce it**:

Will happen for any `@task` decorated operator.

**Anything else we need to know**:

This issue appears on a number of operators.  Possible solution is to modify the "get_python_source" in utils/code_utils.py to handle list and dict. This would cause any operator that using py as the renderer to handle lists and dicts.  Possibly something like:
```
    if isinstance(x, list):
        return [str(v) for v in x]

    if isinstance(x, dict):
        return {k: str(v) for k, v in x.items()}
```
The converting values to strings seems necessary in order to avoid errors when this is passed to the pygments lexer.
![image](https://user-images.githubusercontent.com/72943478/125494716-01cf0c11-9e5f-45fa-afe2-4f99409edefc.png)

**Comment by brain-buster** [comment]
I can confirm this bug - the same situation after updating from Apache Airflow 2.0.2 to 2.1.2. I made small research and found the reason - in previous version was check "if isinstance(content, (dict, list))" and used json.dumps() method.

**Comment by brain-buster** [comment]
Reference: /airflow/www/views.py -> rendered_templates() method

In version 2.0.2:
    if renderer in renderers:
        if isinstance(content, (dict, list)):
            content = json.dumps(content, sort_keys=True, indent=4)
        html_dict[template_field] = renderers[renderer](content)

In version 2.1.2:
    if renderer in renderers:
        html_dict[template_field] = renderers[renderer](content)

**Comment by brain-buster** [comment]
So, this bug is applicable to any PythonOperator which is using op_args or op_kwargs.

**Comment by potiuk** [comment]
@brain-buster - would you like to make a PR to fix the issue maybe ?

**Comment by brain-buster** [comment]
> @brain-buster - would you like to make a PR to fix the issue maybe ?

Yes, of course. I will make PR tomorrow ASAP since this bug is completely affects my project.
