### ISSUE TITLE
Private Image for KubernetesPodOperator XCOM Sidecar Container

### ISSUE THREAD

**Issue by alexanderursu99** [apache/airflow#16996]
**Description**

When using `KubernetesPodOperator` with the option `do_xcom_push=True`, I would also like to be able to change the image being used by the sidecar container that extracts the JSON file from the main container.

**Use case / motivation**

I would like to have all images pulled from a private repository. Main reason being that I've seen rate limiting issues with Docker Hub, since the image being pulled for the sidecar container is `alpine:latest`. It would be helpful if I can set Airflow's behaviour to pull a mirror of this image from ECR.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10605
