### ISSUE TITLE
Pod fails to run when task or dag name contains non ASCII characters (k8s executor)

### ISSUE THREAD

**Issue by flolas** [apache/airflow#16992]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.20.5

**Environment**:

- **Cloud provider or hardware configuration**: Azure AKS

**What happened**:

When task or dag name is defined with a non ascii character, pod creations fails with a kubernetes.client.rest.ApiException: (422)
(task maintains scheduled status)
this is because the hostname defined for the pod is based on dag and task name...

**What you expected to happen**:

Create the pod and run the task

**How to reproduce it**:
Run a task with name "campaña" on K8s executor,

Error log
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"dagnamecampaña.0fb696e661e347968216df454b41b56f\" is invalid: metadata.name: Invalid value: \"dagnamecampaña.0fb696e661e347968216df454b41b56f\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0
-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid"
```

**Comment by samgans** [comment]
If this message is from Kubernetes API, I guess that this is not the Airflow problem.

**Comment by flolas** [comment]
@samgans i dont think so... the sanitization of the pod_id is implemented on the airflow side, look at https://github.com/apache/airflow/blob/177dfbd12a42a5c229640c6c830f43f280ea5caa/airflow/kubernetes/kubernetes_helper_functions.py#L28

I think that we can make sure that non-ascii characters are translated there and the problem will be fixed....

**Comment by potiuk** [comment]
@flolas  -> I think sanitization of the name and converting it to ASCII -only is a great idea. Would you maybe want to submit a PR for that ? That would be great contribution to the project :)

**Comment by flolas** [comment]
@potiuk yeah!  will do it on the weekend glad to help and contribute to Airflow :) !

**Comment by potiuk** [comment]
cool!
