### ISSUE TITLE
Missing documentation about MSSQL setting up

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#17018]
Hi.

In the user documentation, we only have a description of the configuration and requirements for SQLite, MySQL, PostgresSQL, but we [recently added Microsoft SQL support](https://github.com/apache/airflow/pull/9973) as well. I think it is worth updating these parts of the documentation and describing it in a similar way to other databases.

For details, see: [Set up a Database Backend](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/howto/set-up-database.html#setting-up-a-postgresql-database), [docs/apache-airflow/howto/set-up-database.rst](https://github.com/apache/airflow/blob/main/docs/apache-airflow/howto/set-up-database.rst).

Love,

CC: @aneesh-joseph

**Comment by potiuk** [comment]
Hey @aneesh-joseph - any chance for that :) ?

**Comment by potiuk** [comment]
I think it would be great to have it before we release 2.2.0 :)
