### ISSUE TITLE
NONE_FAILED_OR_SKIPPED is unclear

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#17012]
**Apache Airflow version**:
2.1.2

**What happened**:

https://github.com/apache/airflow/blob/16c55f100374df8cb17a85d06396aa42785fed0e/airflow/ti_deps/deps/trigger_rule_dep.py#L206

and 

https://github.com/apache/airflow/blob/16c55f100374df8cb17a85d06396aa42785fed0e/airflow/ti_deps/deps/trigger_rule_dep.py#L216

is the same code, so both look like doing the same
**What you expected to happen**:

NONE_FAILED_OR_SKIPPED should do the same than ALL_SUCCESS

maybe NONE_FAILED_OR_SKIPPED could be removed.

**Comment by potiuk** [comment]
Looks about right. For the sake of backwards compatibility I'd merge it in one IF and deprecate one of those. Anyone?

**Comment by uranusjr** [comment]
I `git blame`-ed this and `NONE_FAILED_OR_SKIPPED` was added in #7464. `NONE_FAILED_OR_SKIPPED` is intentionally implemented to be almost exactly the same as `NONE_FAILED`, but sets the state of the *current* task differently.

https://github.com/apache/airflow/blob/16c55f100374df8cb17a85d06396aa42785fed0e/airflow/ti_deps/deps/trigger_rule_dep.py#L128-L156

Assuming no upstream fails…

* `ALL_SUCCESS` skips the current task if at least one upstream is skipped.
* `NONE_FAILED` does nothing (continues the current task).
* `NONE_FAILED_OR_SKIPPED` skips the current task only if *all* upstream tasks are skipped, otherwise continues.

So I don’t think we can afford to change anything.

cc @yuqian90 maybe you could recall some of the context here?

**Comment by yuqian90** [comment]
@uranusjr already explained the differences between these states. I just want to re-iterate that `none_failed_or_skipped` and `none_failed` are different. The difference is explained in [Trigger Rules](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#trigger-rules).

In the documented example, if `join` is set to `none_failed_or_skipped`, it is skipped when both `branch_false` and `follow_branch_a` are skipped. However, if `join` is set to `none_failed`, it will be `success` even if both `branch_false` and `follow_branch_a` are skipped.
![image](https://user-images.githubusercontent.com/6637585/126268585-a4ac658e-95f9-4b55-a5ed-097a8cb5c66b.png)

In practices, I do find the `none_failed_or_skipped` behaviour more useful, especially when used to join branching logic. However, I don't know if any users out there prefer the behaviour of `none_failed`.

The code that causes such difference can be found here:
https://github.com/apache/airflow/blob/866a601b76e219b3c043e1dbbc8fb22300866351/airflow/ti_deps/deps/trigger_rule_dep.py#L146

**Comment by raphaelauv** [comment]
@uranusjr thanks for the explanation.

So we could maybe rename NONE_FAILED_OR_SKIPPED by NONE_FAILED_OR_ALL_SKIPPED ?

That would be more explicit.

**Comment by uranusjr** [comment]
“Trigger this task if none (of the upstreams) failed or [were] skipped” reads reasonable to me, so IMO a rename is not necessary. But English is hard and also not my first langauge, so don’t take my word for this 🙂

**Comment by eladkal** [comment]
Is the issue here only the name of the trigger rule?

**Comment by raphaelauv** [comment]
At first I through it was a redondant trigger_rule, but now I'm just proposing a more explicit name , but nothing really important. I will close the issue in the next days if it's not relevant.

**Comment by eladkal** [comment]
> At first I through it was a redondant trigger_rule, but now I'm just proposing a more explicit name , but nothing really important. I will close the issue in the next days if it's not relevant.

Do you have suggestion for a better name?

**Comment by raphaelauv** [comment]
You missed my previous messages, take a look

**Comment by eladkal** [comment]
@raphaelauv if you want to take it and run your suggestion in the mailing list and if accepted to open a PR you are more than welcome.
