### ISSUE TITLE
Autoselect oauth provider if there is only one / with flag

### ISSUE THREAD

**Issue by MM-Lehmann** [apache/airflow#17029]
I am using oauth2 (keycloak) as my sole auth provider and it causes some confusion/nuisance with my users having to click the icon without label before they can click on "sign in". It would be much more comfortable if either
1. the provider were preselected and users can directly click "sign in"
2. the provider icon were labeled so they would know why to click that icon
3. they would be redirected directly to the keycloak login page without any clicking
4. (the default airflow login mask could be used and the creds somehow forwarded to keycloak)

I couldn't find any of those approaches anywhere here on in forums so would be happy for some pointers if this is implemented already.

**Comment by mik-laj** [comment]
We use [Flask-AppBuilderfor](https://github.com/dpgaspar/Flask-AppBuilder) Web UI authentication. Can you create a ticket for this project also? I am afraid that your change goes beyond the scope of Airflow and it is the FAB that should make the necessary changes.

**Comment by MM-Lehmann** [comment]
yeah, silently it slipped my attention. But it has been integrated in FAB 3.3.1 recently https://github.com/dpgaspar/Flask-AppBuilder/pull/1655
