### ISSUE TITLE
IMAP provider is always installed even if not selected

### ISSUE THREAD

**Issue by baryluk** [apache/airflow#17024]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**:

- **Install tools**: `virtualenv`, `pip`

- Python 3.9.5 (.final.0) in venv.
- virtualenv 20.4.0
- pip 21.0.1

**What happened**:

```
(venv) ~/airflow-testing/airflow$ pip install 'apache-airflow[postgres]'
(venv) ~/airflow-testing/airflow$ pip install 'apache-airflow[postgres]'
Requirement already satisfied: apache-airflow[postgres] in /home/witek/airflow-testing/venv/lib/python3.9/site-packages (2.1.1)
...
Collecting apache-airflow-providers-imap
  Using cached apache_airflow_providers_imap-2.0.0-py3-none-any.whl (15 kB)
...

Installing collected packages: apache-airflow-providers-imap
Successfully installed apache-airflow-providers-imap-2.0.0
```

```
(venv) ~/airflow-testing/airflow$ pip freeze | grep airflow
apache-airflow==2.1.1
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-sqlite==2.0.0
apache-airflow-upgrade-check==1.4.0
```

Removing manually `apache-airflow-providers-imap` works, but then executing `pip install 'apache-airflow[postgres]'` again reinstall is.

**What you expected to happen**:

Not explicitly specified (or hard dependency) providers should be installed.

**Comment by potiuk** [comment]
This is intended behaviour: https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html#other-extras . See "pre-installed" column.

**Comment by baryluk** [comment]
@potiuk  I do not see "pre-installed" column.

Also why? Why is it preinstalled?

**Comment by potiuk** [comment]
It's been agreed in the community at the time we split providers that some,  most often used providers are preinstalled.

![Screenshot 2021-07-15 18 13 02](https://user-images.githubusercontent.com/595491/125822099-5859bb2f-3d63-4376-bff4-94be4987af88.png)

**Comment by baryluk** [comment]
Ok. I do not quite agree with that, but ok. Thanks.

PS. The preinstalled column was hidden, because my web browser windows was not wide enough apparently.

**Comment by potiuk** [comment]
> Ok. I do not quite agree with that, but ok. Thanks.

That's OK. It's OK to have different opinion. We argue about many things in airflow community often and often have different opinions. This is perfectly fine not to agree with someone else. However if you would like to change it feel free to start discussion about it at the devlist. https://airflow.apache.org/community/. Airflow is a community-managed project and if you have good arguments and convince the community and get to a consensus, the community might make decision to get rid of it. 

Simply stating that you don't agree with something does not move a needle.
