### ISSUE TITLE
Unable to trigger a DAG run via stable rest api

### ISSUE THREAD

**Issue by AvniM** [apache/airflow#17054]
**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): Client = v1.21.1, Server = v1.19.11

**Environment**:

- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Others**: Docker, Kubernetes, Terraform

**What happened**:
When I try to trigger a DAG run via rest api, I getting the following error message: 

**Command**: `curl -X POST -d '{"execution_date": "2021-01-01T15:00:00Z", "conf": {}}' 'https://<env>.centralus.cloudapp.azure.com/api/v1/dags/<dag_id>/dagRuns' -H 'content-type: application/json' --user <user_name>`

Error:

<pre>
Something bad has happened.
Please consider letting us know by creating a <b><a href="https://github.com/apache/airflow/issues/new/choose">bug report using GitHub</a></b>.

Python version: 3.7.10
Airflow version: 2.1.0
Node: airflow-webserver-6bfdb5f887-dgnbb
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/app.py&#34;, line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/app.py&#34;, line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/app.py&#34;, line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/_compat.py&#34;, line 39, in reraise
    raise value
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/app.py&#34;, line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File &#34;/usr/local/lib/python3.7/dist-packages/flask/app.py&#34;, line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/decorator.py&#34;, line 48, in wrapper
    response = function(request)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/uri_parsing.py&#34;, line 144, in wrapper
    response = function(request)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/validation.py&#34;, line 184, in wrapper
    response = function(request)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/validation.py&#34;, line 384, in wrapper
    return function(request)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/response.py&#34;, line 103, in wrapper
    response = function(request)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/_vendor/connexion/decorators/parameter.py&#34;, line 121, in wrapper
    return function(**kwargs)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/api_connexion/security.py&#34;, line 47, in decorated
    return func(*args, **kwargs)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/utils/session.py&#34;, line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File &#34;/usr/local/lib/python3.7/dist-packages/airflow/api_connexion/endpoints/dag_run_endpoint.py&#34;, line 249, in post_dag_run
    or_(DagRun.run_id == post_body[&#34;run_id&#34;], DagRun.execution_date == post_body[&#34;execution_date&#34;]),
TypeError: tuple indices must be integers or slices, not str
</pre>

**What you expected to happen**:

As per [documentation](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_dag_run), a new instance of the specified DAG should get triggered. 

**How to reproduce it**:

Try triggering a DAG run for Airflow 2.1.0 using python 3.7. 

**Anything else we need to know**:

**Comment by pkuca** [comment]
Does it work like this?
```
curl -X POST -d "{\"execution_date\": \"$(date -u -Iseconds)\"}" https://<env>.centralus.cloudapp.azure.com/api/v1/dags/<dag_id>/dagRuns -H 'content-type: application/json' --user airflow
```

**Comment by kaxil** [comment]
I can't reproduce this on Airflow 2.1.2:

```
❯ curl -X POST -d '{"execution_date": "2021-01-01T15:00:00Z", "conf": {}}' 'http://localhost:8080/api/v1/dags/example_dag/dagRuns' -H 'content-type: application/json' --user admin
Enter host password for user 'admin':
{
  "conf": {},
  "dag_id": "example_dag",
  "dag_run_id": "manual__2021-01-01T15:00:00+00:00",
  "end_date": null,
  "execution_date": "2021-01-01T15:00:00+00:00",
  "external_trigger": true,
  "start_date": "2021-07-19T21:12:05.601989+00:00",
  "state": "running"
}
```

**Comment by AvniM** [comment]
@pkuca No luck.

**Comment by AvniM** [comment]
@kaxil We are on Airflow 2.1.0. We haven't upgraded to 2.1.2 yet. 

Can you try reproducing it in v2.1.0 ?

**Comment by kaxil** [comment]
hmm, I tried with 2.1.0 too couldn't reproduce.

cc @ephraimbuddy can you reproduce with 2.1.0?

**Comment by uranusjr** [comment]
Would you be able to get what `post_body` is when this happens?

**Comment by ephraimbuddy** [comment]
> hmm, I tried with 2.1.0 too couldn't reproduce.
> 
> cc @ephraimbuddy can you reproduce with 2.1.0?


I was not able to reproduce in 2.1.0 as well.
@AvniM , Check that you're in the project you're running this by checking the output of: `echo $AIRFLOW_HOME`

**Comment by AvniM** [comment]
@ephraimbuddy: The output is 
`airflow@airflow-webserver-78dd8ff445-zdm62:/$ echo $AIRFLOW_HOME`
`/opt/airflow`

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy: The output is
> `airflow@airflow-webserver-78dd8ff445-zdm62:/$ echo $AIRFLOW_HOME`
> `/opt/airflow`

How are you running airflow? I was assuming that you're running locally and not in a cluster. Please provide steps you use to start up airflow

**Comment by AvniM** [comment]
@kaxil @ephraimbuddy 
Could this be due to some misconfiguration while upgrading from Airflow v1.10.12 to v2.1.0?

We were able to trigger a DAG using the experimental api when on v1.10. 

On v2.1.0, I tried several commands via the stable API. Some of them worked and most of them threw an error. 

**Successful:** 
Get current configuration
List connections
List DAG runs

**Errored:**
Trigger a new DAG run
List DAG runs (batch)
List DAGs
Get basic information about a DAG

**Comment by AvniM** [comment]
> > @ephraimbuddy: The output is
> > `airflow@airflow-webserver-78dd8ff445-zdm62:/$ echo $AIRFLOW_HOME`
> > `/opt/airflow`
> 
> How are you running airflow? I was assuming that you're running locally and not in a cluster. Please provide steps you use to start up airflow

We are not running it locally. Using Azure cloud with Kubernetes, Terraform and Docker.

**Comment by ephraimbuddy** [comment]
> @kaxil @ephraimbuddy
> Could this be due to some misconfiguration while upgrading from Airflow v1.10.12 to v2.1.0?
> 
> We were able to trigger a DAG using the experimental api when on v1.10.
> 
> On v2.1.0, I tried several commands via the stable API. Some of them worked and most of them threw an error.
> 
> **Successful:**
> Get current configuration
> List connections
> List DAG runs
> 
> **Errored:**
> Trigger a new DAG run
> List DAG runs (batch)
> List DAGs
> Get basic information about a DAG

In 2.0+, you need to set the auth_backend. This is how you should set it to use basic authentication:
`auth_backend = airflow.api.auth.backend.basic_auth`
Did you set this?

**Comment by AvniM** [comment]
> > @kaxil @ephraimbuddy
> > Could this be due to some misconfiguration while upgrading from Airflow v1.10.12 to v2.1.0?
> > We were able to trigger a DAG using the experimental api when on v1.10.
> > On v2.1.0, I tried several commands via the stable API. Some of them worked and most of them threw an error.
> > **Successful:**
> > Get current configuration
> > List connections
> > List DAG runs
> > **Errored:**
> > Trigger a new DAG run
> > List DAG runs (batch)
> > List DAGs
> > Get basic information about a DAG
> 
> In 2.0+, you need to set the auth_backend. This is how you should set it to use basic authentication:
> `auth_backend = airflow.api.auth.backend.basic_auth`
> Did you set this?

Yes, this is set in our airflow.cfg file. 
Again, some of the API calls are working (eg. List DAG runs), but most are not (eg. Trigger a new DAG run, List DAGs).

**Comment by AvniM** [comment]
Closing this issue as this could be a misconfiguration on our end.

**Comment by yagodorea** [comment]
@AvniM did you solve this? I'm having the same problem here, is it a configuration issue?
