### ISSUE TITLE
`conn.set_extra` isn't working as expected.

### ISSUE THREAD

**Issue by jmaldon1** [apache/airflow#17055]
**Apache Airflow version**: v2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Macos
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Basically, I want the ability to override the `extras` in a connection object.
Using the `set_extra` method in the `conn` object will set the extra, but it will doesn't seem to use it when running `hook.run()`

**What you expected to happen**:

`hook.run()` should be using the new `extra` value.

**How to reproduce it**:
```python
# Export this connection elsewhere
# Comment out the extra because I want to set it programmatically somewhere else.
Connection(
    conn_id="demo_mssql_odbc",
    conn_type="odbc",
    login=user,
    schema=database,
    password=password,
    host=f"{host},{port}",
    # extra=json.dump({
    #    "Driver": "ODBC Driver 17 for SQL Server"
    # })
)

conn = MsSqlHook.get_connection(conn_id="demo_mssql_odbc")
conn.set_extra(json.dump({"Driver": "ODBC Driver 17 for SQL Server"}))
print(conn.get_extra())
# {"Driver": "ODBC Driver 17 for SQL Server"}
hook = conn.get_hook()
hook.run(sql=sql)

# ERROR
# pyodbc.InterfaceError: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)')
# ^ this error occurs when pyodbc cannot find the Driver which gets set in the `extras`
```

**Anything else we need to know**:

If I uncomment the `extra` field in the original `Connection` object, everything works fine. Which leads me to believe that either `conn.set_extra` or `conn.get_hook` isn't working correctly. Or I am misunderstanding the way these methods work.

**Comment by potiuk** [comment]
It does not work this way. get_hook() method is implemented by instantiating new hook class and passes connection id as parameter - which in turn will create a new connection class using standard mechanisms (from db or from variable).

Connections should be immutable in your tasks. You should not attempt to dynamically modify them. You can always create a new connection with different id and different extra and use this other id. In some methods/objects connections are cached and in some they are recreated and trying to modify them on the flight is a bad idea.
