### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by laxmikanth-d** [apache/airflow#17063]
**Apache Airflow version**: 2.1.0 Running from Apache/airflow Container

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Airflow Container
- **OS** (e.g. from /etc/os-release): Windows
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Using S3Hook to upload file to AWS S3. I have created user in aws with full S3 permissions. 
I have created s3_connection in connections like this

```
{
"aws_access_key_id":"********", 
"aws_secret_access_key":"********",
"region_name":"us-west-2"
}
```

But When I run my DAG task I am getting error "role_arn" is NONE. 

**What you expected to happen**: Expected to connect successfully to S3 and upload the local test.txt file to S3.

**How to reproduce it**:
Here is the code snippet.

```python
from airflow import DAG
import airflow
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.operators.python import PythonOperator

from datetime import timedelta, datetime

default_args = {
    'owner':'Lax',
    'retries':0,
    'email_on_retry': False,
    'email':'email@gmail.com',
    'email_on_failure': False,
    'retry_delay': timedelta(minutes=1)
}    

def file_upload(filename,key,bucket_name):
    hook = S3Hook('s3_connection')
    hook.load_file(filename, key, bucket_name)
    

with DAG(dag_id='s3_hook_demo', start_date = datetime(2021,7,14), schedule_interval = "@daily", default_args = default_args,
         catchup=False) as dag:

    file_upload_task = PythonOperator(
        task_id='file_upload',        
        op_kwargs= {
            'filename': 'test.txt',
            'key':'text.txt',
            'bucket_name':'angfdighubfjhdknmmf'
        },
        python_callable=file_upload
    )
```

**Anything else we need to know**:

![Airflow](https://user-images.githubusercontent.com/32249729/126051488-9c27a819-a305-46a4-903e-8a838b3e8e67.PNG)

**Comment by mik-laj** [comment]
`role_arn is None` is an info entry. It is not an error. You can ignore this line. Can you provide a full error stack?

**Comment by baryluk** [comment]
Please provide rest of the stack trace. The `INFO - role_arn is None` is expected, and not a problem. In fact it is normal operation.

**Comment by soumitra9** [comment]
Could anybody help please, I am facing similar issues

**Comment by rainyjonne** [comment]
Me too...

**Comment by m0zart89** [comment]
I have the same problem. Also when I add region as postfix to my bucket name (_bucketname.us-east-1_) I see another behaviour:
An error occurred (**404**) when calling the HeadObject operation: Not Found

**Comment by NirbanPal** [comment]
I am facing the same issue when my django app is running on the vercel server. In local env it is running successfully. Can anyone help me out?  Error is: botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
