### ISSUE TITLE
Changed DAG being executed, but Views not Updated to Reflect the new DAG

### ISSUE THREAD

**Issue by r39132** [apache/airflow#171]
I've changed my DAG by removing some operators. In the DAG below, I removed 3 operators : 
- check_for_parquet_file_branch_condition
- clean_up_db_tables_job
- send_sns_notification_no_parquet_data
  <img width="993" alt="screenshot 2015-07-22 23 29 40" src="https://cloud.githubusercontent.com/assets/581734/8844412/9ce7cb2e-30c9-11e5-9dd0-b24974233745.png">

<img width="875" alt="screenshot 2015-07-22 23 36 29" src="https://cloud.githubusercontent.com/assets/581734/8844493/8775d0c8-30ca-11e5-9961-85aeb37dc1f4.png">

The new DAG is being executed as is expected, but why are the other nodes hanging around in the views?

They still appear on my DAG. Why? I am running `airflow webserver -d` and `airflow scheduler` and did not restart these. I just put an updated dag file in the dags directory.

**Comment by r39132** [comment]
Ok. Restarting the scheduler and webserver solved the problem. Is that by design?

<img width="902" alt="screenshot 2015-07-22 23 49 38" src="https://cloud.githubusercontent.com/assets/581734/8844647/60e88c8c-30cc-11e5-8c0f-843a39103a88.png">
<img width="902" alt="screenshot 2015-07-22 23 49 20" src="https://cloud.githubusercontent.com/assets/581734/8844649/65581fda-30cc-11e5-9368-1e3433c633b5.png">

**Comment by artwr** [comment]
Hey Sid,

I believe it is linked to the way python imports files (and here dags). A full reload is sometimes difficult, and the only to purge the old is to restart everything...

**Comment by r39132** [comment]
Restarting is a reasonable work-around. I'm closing this. Thanks.

**Comment by mistercrunch** [comment]
You may have to hit the refresh button to force the DAG to refresh, it's the rightmost button on the screenshot and can be found on the DAGs page.
<img width="158" alt="screen shot 2015-07-23 at 11 43 51 pm" src="https://cloud.githubusercontent.com/assets/487433/8869088/c87c7552-3194-11e5-96a3-a3f575d57ed9.png">

**Comment by mistercrunch** [comment]
This button actually "expires" the DAG, forcing the different "DagBags" in the ecosystem to refresh from file. The scheduler has its own dagbag, as well as each web server thread, so refreshing it in one place doesn't solve the problem of freshness. The expiration is actually a timestamp in the database for that DAG that the DagBag looks up against periodically to see if it should reload the DAG.

There may be some bad behaviors to watch for around:
- files that get renamed/deleted
- conflicting dag_ids in multiple files
