### ISSUE TITLE
Incorrect python version used for 2.1.2-python3.9 docker image

### ISSUE THREAD

**Issue by andormarkus** [apache/airflow#17102]
**Apache Airflow version**: 2.1.2

Hi All,

Based on my testing, python 3.8 is used for the python 3.9 image.

```bash
▶ docker run --rm -it  apache/airflow:2.1.2-python3.6 python --version
Python 3.6.13

▶ docker run --rm -it  apache/airflow:2.1.2-python3.7 python --version
Python 3.7.10

▶ docker run --rm -it  apache/airflow:2.1.2-python3.8 python --version
Python 3.8.10

▶ docker run --rm -it  apache/airflow:2.1.2-python3.9 python --version
Python 3.8.10
```

Thanks,
Andor

**Comment by uranusjr** [comment]
Confirmed, see step 7 here:

https://hub.docker.com/layers/apache/airflow/2.1.2-python3.9/images/sha256-a2df4ea3cd5aad765f6169dcc94d53a6c90eed85e539b17b44c0168610f6307e

```
ENV PYTHON_VERSION=3.8.10
```

**Comment by kaxil** [comment]
We will fix it, thanks for reporting

**Comment by potiuk** [comment]
aaaaaaH!

**Comment by potiuk** [comment]
Yep. I know exactly what happened. Our base python image I manually pushed to v2-1-test `apache/airflow-ci:python3.9-v2-1-test` is actualy 3.8.10 :(. Fixing it.

**Comment by potiuk** [comment]
This was the only manual step I had to do to prepare v2-1 tests for release back then :( . There's a reason why I like automation..

```
docker run -it apache/airflow-ci:2.1.2-python3.9 python --version
Python 3.9.6
```

Anyway - it's fixed. Thanks @andormarkus for reporting it!
