### ISSUE TITLE
apache-airflow-providers-google locks google-ads to an unsupported version

### ISSUE THREAD

**Issue by Overbryd** [apache/airflow#17113]
The `apache-airflow-providers-google` package locks the `google-ads` package to an unsupported version.

The maximum supported Google Ads API with the Apache Airflow google provider package is now stuck at `v5`.
The current supported version (until Jun 2022) is `v8`.

Hence the Apache Airflow package breaks all Google Ads functionality (API calls with the package Google Ads client are all rejected).

As a user of Airflow, I would expect to be able to upgrade google-ads individually.

**Comment by potiuk** [comment]
Duplicate of #17111. @Overbryd closing this one as duplicate - if you would like you can provide a PR to fix that one or you can agree with @rv-irosario to join the forces and submit/test the PR. Happy to guide you to with the process.
