### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open file

### ISSUE THREAD

**Issue by deswandhi** [apache/airflow#17123]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by uranusjr** [comment]
Hi, you did not provide any information about your error!
