### ISSUE TITLE
Python VirtualEnvDecorator - Rendered variable not visible in UI

### ISSUE THREAD

**Issue by mehmax** [apache/airflow#17139]
**Apache Airflow version**:
2.1.0

**Environment**:

- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-1062.1.1.el7.x86_64 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- 
**What happened**:

I created the following DAG + a single Task 
```
from re import template
from airflow.decorators import dag, task
from airflow.utils.dates import days_ago
from airflow.operators.python import PythonVirtualenvOperator

default_args = {
    'owner': 'airflow',
}
@dag(default_args=default_args, schedule_interval=None, start_date=days_ago(2), tags=['example'], template_searchpath='/airflow/home/airflow/sql')
def tutorial_taskflow_api_etl():
    @task.virtualenv(templates_exts=['.sql'], system_site_packages=True, python_version=3.8)
    def extract(sql):
        print(sql)

    taskflow = extract('file_to_be_rendered.sql') 

tutorial_etl_dag = tutorial_taskflow_api_etl()
```

 I call this task with a filename that needs to be rendered at runtime. In the Task Decorator I defined 
`templates_exts=['.sql']`
and in the DAG I defined
`template_searchpath='/airflow/home/airflow/sql'`

The content of file /airflow/home/airflow/sql/file_to_be_rendered.sql is
```
THE FOLLOWING LINE SHOULD SHOW THE DAG RUN ID:
{{ run_id }}
```

When I run the DAG, the file is correctly rendered (see the following Log)
![image](https://user-images.githubusercontent.com/84371809/126514140-7046882a-13e0-4e4d-9502-6f01bb58a579.png)

But I cannot see it in the UI

![image](https://user-images.githubusercontent.com/84371809/126514000-4e36c3dd-773d-4f34-9006-50af47e7e4f8.png)

**What you expected to happen**:

`'file_to_be_rendered.sql'` should be shown in the UI under Rendered Template of TaskInstance with content:

```
THE FOLLOWING LINE SHOULD SHOW THE DAG RUN ID:
manual__2021-07-21T14:56:14.898433+00:00
```

**How to reproduce it**:

Use the DAG code from above and run it - check UI.

**Comment by potiuk** [comment]
It's already been fixed in #16976 and will likely be released in 2.1.3
