### ISSUE TITLE
airflow 更改 dag_id 导致任务在队列中不执行

### ISSUE THREAD

**Issue by xujiang1** [apache/airflow#17154]
当我们改变dag_id ，在airflow线上任务不关闭的情况下通过git pull更新代码 会导致任务在queued中不执行

**Comment by potiuk** [comment]
I am sorry but we are using English here for communication. Could you please reopen the issue and explain it in English. 
I understand that it might be seen as hurdle, but this is the language of the project, and vast majority of the people who see that would not understand this neither the following conversation if it is in Chinese and we also have to make sure both - issues and resolutions are visible and transparent to the whole community.
