### ISSUE TITLE
Typo in GoogleCloudStorageToBigQueryOperator deprecation message

### ISSUE THREAD

**Issue by Jesus89** [apache/airflow#17155]
**Apache Airflow version**: latest (main branch)

**What happened**:

There is a little typo in this line of code: https://github.com/apache/airflow/blob/6172b0e6c796d1d757ac1806b671ee168c031b1e/airflow/contrib/operators/gcs_to_bq.py#L40

**What you expected to happen**:

It should be *gcs_to_bigquery* instead of *gcs_to_bq*:

```
Please use `airflow.providers.google.cloud.transfers.gcs_to_bigquery.GCSToBigQueryOperator`.""",
```

**Comment by mik-laj** [comment]
Are you willing to submit a PR? I'm happy to help with review.

**Comment by Jesus89** [comment]
Yes! Here it is https://github.com/apache/airflow/pull/17159

Thanks
