### ISSUE TITLE
Add LocalFilesystemtoS3Operator

### ISSUE THREAD

**Issue by denimalpaca** [apache/airflow#17168]
**Description**

Currently, an S3Hook exists that allows transfer of files to S3 via `load_file()`, however there is no operator associated with it. The S3Load Operator would wrap the S3 Hook, so it is not used directly.

**Use case / motivation**

Seeing as to upload a local file to S3 using the S3 Hook, a Python task with the same functionality has to be written anyway, this could reduce a lot of redundant boiler-plate code and standardize the local file to S3 load process.

**Are you willing to submit a PR?**

Yes

**Related Issues**

Not that I could find.

**Comment by eladkal** [comment]
Yeah we can have an operator to load from local to S3 (like the equivalent from GCP ) https://github.com/apache/airflow/blob/45a49e0f81cc592a4e6a95aa230560530d88a5c8/airflow/providers/google/cloud/transfers/local_to_gcs.py#L28

assigned the issue to you :)
