### ISSUE TITLE
TriggerDagRunOperator triggering subdags out of order

### ISSUE THREAD

**Issue by ManiBharataraju** [apache/airflow#17176]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
We have dags that get triggered by another dag using the TriggerDagRunOperator. These dags include subdags as well. What we are seeing is that it triggers the subdags as well(without checking the dependencies) which should not be the case.

**What you expected to happen**:
I would expect the dag run to be created for the parent dag only. The subdags should be run only when the upstream task dependencies are met.

**How to reproduce it**:

Create a dag that includes subdags with upstream task dependencies. Trigger it from another dag and see dag runs created for both subdags and main dag.

**Anything else we need to know**:
Its because of this piece of code  I believe
https://github.com/apache/airflow/blob/main/airflow/api/common/experimental/trigger_dag.py#L81

which adds the subdags as well to the dags to be triggered. Any reason why this was done?

**Comment by ManiBharataraju** [comment]
Another thing that we are seeing is that subdags are no more created with a backfill run id. They are either scheduled or manual based on their parent dag. Could that be the cause of this issue to popup? Because it worked as expected in 1.10.x version.

**Comment by enriqueayala** [comment]
We're having same issue on 2.1.0 with same use case: TriggerDagRunOperator -> DAG with a subdag . This is affecting subdag tasks relying on xcom values from a parent dag task (which produces incorrect/failed process cause xcom value doesn't exist yet) .  Is there any workaround?

**Comment by ManiBharataraju** [comment]
@enriqueayala - We created a custom TriggerDagRunOperator along with the changes in trigger_dag.py. I just copied the trigger dag run operator code and trigger_dag.py code and made the one change that I have mentioned. That worked. 
But I am unsure of why that was done or if that is the real reason behind this issue. As a temporary fix, u can do that.

**Comment by enriqueayala** [comment]
Thanks @ManiBharataraju

**Comment by uranusjr** [comment]
@ManiBharataraju WOuld you mind submitting that change you alluded to? (You said you made a change and where you changed, but didn’t mention *what* you changed it into.) We can maybe discuss the issue better when there’s concrete code.

**Comment by ManiBharataraju** [comment]
@uranusjr - Hey, the line highlighted here, 
https://github.com/apache/airflow/blob/main/airflow/api/common/experimental/trigger_dag.py#L81
I removed `dag.subdags`. But, I am not sure whether that is the right fix for this because it seems to be not a recent change and not sure why it was put in the first place(maybe to support some other use case).

**Comment by ManiBharataraju** [comment]
@uranusjr - 

> Would this not make subdags not triggered at all?

The subdags are getting triggered after upstream dependencies are met. But, without the change, the subdags get triggered as soon as the parent dag is triggered and not respecting the upstream task dependencies. 

One thing that I observed is, the triggered dags no more have run id as `trig__<date>` they now have run id as `manual__<date>` and subdags are inheriting run id from the parent. Previously, the subdag run id used to be `backfill__<date>`. I strongly suspect this change could be the root cause.

**Comment by ManiBharataraju** [comment]
Hey @uranusjr - I see AIP-39 where changes are made as to how dags are scheduled now. Do u think that could have caused this? Still trying to understand what has been done in that. I'll let you know if I find anything.

**Comment by dVladon** [comment]
Hi
Does anyone know, is there any updates on this problem? Is it going to be fixed?

**Comment by potiuk** [comment]
I think not. The long term solution is to switch to Task Group. Subdags are deprecated and are going to be removed in Airflow 3 anyway, so the best we can advice is to switch to TaskGroups as suggested by https://github.com/apache/airflow/issues/17176#issuecomment-890295058

See https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#taskgroups-vs-subdags

Closing it due to that.
