### ISSUE TITLE
Chart: Uses deprecated v1beta1 Ingress Resource. Incompatible with Kubernetes 1.22

### ISSUE THREAD

**Issue by cablespaghetti** [apache/airflow#17188]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.20

**Environment**: Amazon EKS deployed via Helm Chart v1.0.0

**What happened**: The ingress resource created via the Helm chart uses the now deprecated v1beta Ingress which will be removed in Kubernetes 1.22. The stable version has been available since 1.19 which is two versions behind, and at least one version behind on most major cloud providers.

**What you expected to happen**: The stable v1 resource with option for ingressClassName is used instead. If you wish to support Kubernetes versions older than 1.19 then Helm is capable of doing different things depending on detected Kubernetes versions, which I've seen other charts do.

**Comment by mik-laj** [comment]
Are you willing to submit a bug fix? I'm happy to help with review. :-D

**Comment by cablespaghetti** [comment]
Sure yes. I'll have a go.

**Comment by mik-laj** [comment]
Assigned.

**Comment by thesuperzapper** [comment]
If you want some reference, here is the PR that made this change in the "user-community" (not "official") helm chart: 
 https://github.com/airflow-helm/charts/pull/381
