### ISSUE TITLE
sqlite3.OperationalError: no such column: variable.description

### ISSUE THREAD

**Issue by pindge** [apache/airflow#17219]
**Apache Airflow version**: 2.1.2

**Environment**:
- github workflow
- 
**What happened**:

in our code base, we provide VARS from terraform, and allows dags owner to get via Variable
```
INDEXING_USER_SECRET = Variable.get(
    "processing_user_secret", default_var="indexing-aws-creds-sandbox"
)
```
since upgrading to v2.1.2, we are noticing following issues, in v1.10.15 it didnt have variable.description columns, its doesnt appear to be breaking anything just eye sore to see
```
[SQL: SELECT variable.val AS variable_val, variable.id AS variable_id, variable."key" AS variable_key, variable.description AS variable_description, variable.is_encrypted AS variable_is_encrypted 
FROM variable 
WHERE variable."key" = ?
 LIMIT ? OFFSET ?]
[parameters: ('processing_user_secret', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
ERROR [airflow.models.dagbag.DagBag] Failed to import: /home/runner/work/dea-airflow/dea-airflow/dags/utility/utility_explorer_summary.py
Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/share/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: variable.description
```
**What you expected to happen**:
when `default_var` is passed to `Variable.get` no error message displays.

**How to reproduce it**:
1. have code contain `Variable.get` in an environment and database that doesnt have this VAR defined.
2.  `airflow db init`
3. `airflow dag list`

**Anything else we need to know**:
https://github.com/GeoscienceAustralia/dea-airflow/runs/3158865646?check_suite_focus=true expland `setup airflow and check dags list` section

**Comment by potiuk** [comment]
You have not run `airflow db upgrade` when you upgraded from an earlier version of airfflow. If you are running unit tests you also need to run `ariflow db upgrade` or `airflow db reset` with Unit test mode enabled https://airflow.apache.org/docs/apache-airflow/stable/howto/use-test-config.html

**Comment by barun-mazumdar** [comment]
It happening also on docker container from image: airflow 2.1.2, which I try to run with default sqlite db of airflow.  I just run the airflow db init, airflow scheduler and airflow webserver  commands in entrypoint script.

**Comment by barun-mazumdar** [comment]
It is happening also on docker container from image: airflow 2.1.2, which I try to run with default sqlite db of airflow. I just run the airflow db init, airflow scheduler and airflow webserver commands in entrypoint script as i use sequential executor. It happens only the first time. The issue does not occur for subsequent docker start commands.

**Comment by potiuk** [comment]
> It is happening also on docker container from image: airflow 2.1.2, which I try to run with default sqlite db of airflow. I just run the airflow db init, airflow scheduler and airflow webserver commands in entrypoint script as i use sequential executor. It happens only the first time. The issue does not occur for subsequent docker start commands. If I run airflow db upgrade before airflow db update, it then fails with same message in airflow db upgrade command.

Yeah. It can happen if you do not use the tool according to it's intended use. I am afraid the way you use it quite wrong.

The docker image of airflow has never been designed to override its entrypoint, to run several different airflow components inside and to run sqlite as a database for anything else than quick tests. SQlite + Sequential executor are never intended to be used for production and they are 100s times slower when it comes to scheduling than any "proper" database. 2.1.3 version of airflow will have a big, uremovable warning that you should only use it for testing/development purpose.
