### ISSUE TITLE
MSSQL in CI takes far too much memory

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#17232]
When MSSQL is run for CI, it takes far to much memory and it makes our CI fails. Likely the image uses default configuration - which is kind-of-needed when MSSQL is run in any reasonable production like environment, but we only need it for very low amount of data and very limited performance. We've already limited MySQL and Postgres to take < 250 MB each, MSSQL takes ~ 1.2GB at least, which is far too much for GitHub public runners.

We should investigate setings of MSSQL and bring it's memory footprint down on CI - similarly as we did for MySQL and Postgres.

**Comment by potiuk** [comment]
cc: @aneesh-joseph

**Comment by potiuk** [comment]
Results of `docker stats` for comparision:

```
CONTAINER ID   NAME                        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
60facbbb64e1   docker-compose_postgres_1   0.03%     77.87MiB / 29.61GiB   0.26%     1.03MB / 666kB    47.5MB / 385MB    6
3499b2b1615a   docker-compose_mysql_1      0.11%     250.6MiB / 29.61GiB   0.83%     1.13MB / 933kB    68.8MB / 1.83GB   31
52e0c49d66a1   docker-compose_mssql_1      103.85%   1.191GiB / 29.61GiB   4.02%     4.53MB / 1.93MB   1.31GB / 304MB    183
```

**Comment by potiuk** [comment]
Does not seem there is a good chance for that https://github.com/microsoft/mssql-docker/issues/517

**Comment by eladkal** [comment]
@potiuk is this issue still relvant?

**Comment by potiuk** [comment]
We workarounded it since. Closing.
