### ISSUE TITLE
Python Operator on Apple M1, python 3.9.6, airflow 2.1.2

### ISSUE THREAD

**Issue by warrenstephens** [apache/airflow#17241]
**Apache Airflow version**: 
Airflow version: 2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): macOs Big Sur 11.4
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.9.6
Airflow version: 2.1.2
Node: helx-web-78985b668c-bwgtp
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/views.py", line 1373, in run
    task = dag.get_task(task_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dag.py", line 1547, in get_task
    raise TaskNotFound(f"Task {task_id} not found")
airflow.exceptions.TaskNotFound: Task print_it not found
```

**What you expected to happen**:

I have been experimenting (for the first time) with trying to get the PythonOperator to work -- and to see where I can get the log output to go.  

I have 2 functions listed below.

The first function, print_context, causes my laptop to run out-of-memory -- and I have to reboot it.  Shown farther below is how I tried to call it, but that was commented out in order to try the 2nd function after the reboot.

The second function, my_function, caused the Airflow UI to pop-up the "Something bad has happened." message.

I have not been able to get the PythonOperator to work.

**How to reproduce it**:

```
def print_context(ds, **kwargs):
    import logging
    import pprint
    pprint(kwargs)
    print(ds)

    tlogger = logging.getLogger("airflow.task")
    tlogger.info(f"kwargs: {kwargs}")

    return 'done!'

def my_function(arg1):
    import logging
    print(f"arg1: {arg1}")

    tlogger = logging.getLogger("airflow.task")
    tlogger.info(f"arg1: {arg1}")

    return 'done!'
```

With this in the dag:
```
    LoggingMixin().log.info("hello from mixin logger")

    # run_printlog = PythonOperator(
    #     task_id='print_it',
    #     provide_context=True,
    #     python_callable=print_context,
    #     dag=dag)

    run_printlog = PythonOperator(
        task_id='log_it',
        python_callable=my_function,
        op_kwargs={
            'duglog': theloglevel
        },
        dag=dag)

    log.info(f"after python operator")

```

**Anything else we need to know**:

**Comment by warrenstephens** [comment]
Hitting the "back" button on the UI, then shows the "log_it" task (rather than "print_it"), and then running "log_it" will crash the pod, like this:
```
$ kubectl get pods
NAME                                                READY   STATUS             RESTARTS   AGE
annotateduglogit.e7d5501e50d644d8894934b6880613b7   0/1     CrashLoopBackOff   2          62s
```

**Comment by warrenstephens** [comment]
May be interesting and related:
```
$ kubectl logs annotateduglogit.e7d5501e50d644d8894934b6880613b7 
[2021-07-26 21:24:26,515] {cli_action_loggers.py:105} WARNING - Failed to log action with (sqlite3.OperationalError) no such table: log
[SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2021-07-26 21:24:26.512164', 'annotate_dug', 'log_it', 'cli_task_run', '2021-07-23 12:04:21.596591', 'airflow', '{"host_name": "annotateduglogit.e7d5501e50d644d8894934b6880613b7", "full_command": "[\'/home/airflow/.local/bin/airflow\', \'tasks\', \'run\', \'annotate_dug\', \'log_it\', \'2021-07-23T12:04:21.596591+00:00\', \'--local\', \'--pool\', \'default_pool\', \'--subdir\', \'DAGS_FOLDER/annotate.py\']"}')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-07-26 21:24:26,516] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/annotate.py
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 220, in task_run
    dag = get_dag(args.subdir, args.dag_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 191, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: dag_id could not be found: annotate_dug. Either the dag did not exist or it failed to parse.
~ $
```

**Comment by BasPH** [comment]
Hi @warrenstephens, I'm not able to reproduce an error with Apple M1, Python 3.9.6, and Airflow 2.1.2. I tested locally running a SequentialExecutor but it appears you're running on K8S. Could you provide more info about your setup?

Also, this line:
```
Failed to log action with (sqlite3.OperationalError) no such table: log
```
Indicates your Airflow metastore isn't properly initialized.

**Comment by warrenstephens** [comment]
Yes, my Mac M1 is running the Airflow UI, but K8S is used to run the Airflow tasks and such on a remote cluster -- part of a new RENCI HeLx platform deployment for an NIH project.  I am the only M1 ~victim~ user here.

I am curious about the sqlite3 issue.  I have been developing and running DAGs for a couple of weeks -- this sqlite3 issue would be intermittent then?  Or is something fundamentally missing from our K8S config?

**Comment by BasPH** [comment]
Before starting anything you must initialize the metastore (i.e. create all tables). This can be done by running either:

- `airflow db init` (initialize everything on empty metastore)
- or `airflow db upgrade` (check current metastore state if there are any upgrades to make)
- or `airflow db reset` (remove & recreate everything)

Could you initialize your metastore and see if issues persist after that?
