### ISSUE TITLE
bash operator overrides environment variables instead of updating them

### ISSUE THREAD

**Issue by omriAl** [apache/airflow#17240]
**Apache Airflow version**: 1.10.15

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
**Environment**:

- **Cloud provider or hardware configuration**: EKS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux airflow-web-84bf9f8865-s5xxg 4.14.209-160.335.amzn2.x86_64 #1 SMP Wed Dec 2 23:31:46 UTC 2020 x86_64 
- **Install tools**: helm (fork of the official chart)
- **Others**:
**What happened**:
We started using `env` variable in the built-in bash_operator. the goal was to add a single variable to be used as part of the command. but once using the variable, it caused all of the other environment variables to be ignored.

**What you expected to happen**:
we expected that any environment variable we are adding to this operator will be added or updated.
the expectation are wrong from this variable.
**How to reproduce it**:

`import os
os.environ["foo"] = "bar"
from datetime import datetime
from airflow import DAG
from airflow.models import TaskInstance
from airflow.operators.bash_operator import BashOperator

dag = DAG(dag_id='anydag', start_date=datetime.now())

#unsuccessfull example:
task = BashOperator(bash_command='if [ -z "$foo" ]; then exit 1; fi',env= {"foo1" : "bar1"},dag=dag, task_id='test')
ti = TaskInstance(task=task, execution_date=datetime.now())
result = task.execute(ti.get_template_context())

#successfull example:
task = BashOperator(bash_command='if [ -z "$foo" ]; then exit 1; fi',dag=dag, task_id='test1')
ti = TaskInstance(task=task, execution_date=datetime.now())
result = task.execute(ti.get_template_context())`

**Anything else we need to know**:
this happens every time it runs.

**Comment by uranusjr** [comment]
I think this is working as expected (that how `env` in the stdlib subprocess works). Does the documentation says otherwise? We should fix the documentation if that's the case.

**Comment by potiuk** [comment]
Yep. It is explicitly mentioned in the documentation of BashOperator:

```
    :param env: If env is not None, it must be a dict that defines the
        environment variables for the new process; these are used instead
        of inheriting the current process environment, which is the default
        behavior. (templated)
    :type env: dict
```

However @omriAl, if you feel you need the case where env have to be additive, I would encourage you to make a PR and this feature. I imagine, this could be an extra flag with default = True (`replace_os_env=True`) and if it is set to`False` the os env will be retained and the env values specified would just override those specified ones. It's an easy fix and I encourage you to contribute it.

Would you like to add it ?

**Comment by omriAl** [comment]
Hi @potiuk @uranusjr!
Yes - I would gladly take this.
I think you've described a better behaviour - that it would be an option to append/update rather than to override.
I didn't contribute to this project yet - what is the best way to start?
Thanks!

**Comment by potiuk** [comment]
Feel free. We have plenty of good docs to start. You can start wit: https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst and work your way through https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst

**Comment by mik-laj** [comment]
Related issues: https://github.com/apache/airflow/issues/13445 https://github.com/apache/airflow/issues/14620

**Comment by omriAl** [comment]
@potiuk @uranusjr Hi, I'm pretty much finished with the change. but I'm having trouble testing it with my local environment. I followed all of the steps, but once I'm starting airflow (`breeze start-airflow`) I'm getting some kind of a static view of the webserver, so it's hard for me to verify my changes.
Any thoughts? (I've branched off the main branch).
thanks!

**Comment by potiuk** [comment]
rebase on top of the latest main branch and rebuild breeze when asked (ot force it with `./breeze build-images --force-pull-images` )

**Comment by omriAl** [comment]
@potiuk Thanks, I did that and got the same result.
btw - I see that one section of the tmux is failing with: 
`$ NODE_ENV=dev webpack --watch --colors --progress --debug --output-pathinfo --devtool eval-cheap-
source-map --mode development                   
/bin/sh: 1: webpack: not found error Command failed with exit code 127.        
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.             
root@61674abb901d:/opt/airflow/airflow/www# `
do you think this is related?

**Comment by potiuk** [comment]
It is related - did you build the image ? It will take a while ...

**Comment by potiuk** [comment]
I think you should somehow clean up - I think this is strange you do not get webpack in docker ... just start from scratch :

``docker system prune --all` 
``rm -rf .build`` 

And start again.

**Comment by omriAl** [comment]
Hey, yes I found the error.
The build didn't finish because im running behind a proxy and this causes issues with the ssl certificate.
Thanks!
