### ISSUE TITLE
Helm v1.0.0 missing, no entry in index.yaml for 1.1.0

### ISSUE THREAD

**Issue by naomiaro** [apache/airflow#17243]
https://downloads.apache.org/airflow/helm-chart/

There is no more https://downloads.apache.org/airflow/helm-chart/1.0.0/airflow-1.0.0.tgz, only 1.1.0.

However, there's no entry here for 1.1.0:

https://airflow.apache.org/index.yaml

**Comment by naomiaro** [comment]
https://airflow.apache.org/index.yaml Index now includes 1.1.0 at least

**Comment by kaxil** [comment]
Yup, the `index.yaml` at https://airflow.apache.org/index.yaml contains 1.0.0 and 1.1.0

so you could do (and documented at https://airflow.apache.org/docs/helm-chart/stable/quick-start.html#add-airflow-helm-stable-repo):

```
helm repo add apache-airflow https://airflow.apache.org
helm repo update
```

and then install with:

```
export RELEASE_NAME=example-release
helm install $RELEASE_NAME apache-airflow/airflow 
```

**Comment by potiuk** [comment]
Yep. The "downloads" source should be mostly used if you want to download the chart and install it from there (it is signed and checksummed and only latest version of released software is there as per "Release Policy of ASF": https://www.apache.org/legal/release-policy.html

Also all releases (including the archived ones) are automatically available via archive.apache.org -  http://archive.apache.org/dist/airflow/helm-chart/ has both 1.0.0 and 1.1.0 for example. So if you do not want to use the "airflow.apache.org" you can directly use the "archive" link.

**Comment by matthieu-foucault** [comment]
Was there an update to the index.yaml yesterday just before @naomiaro  reported the issue? Looks like there was a blip and our [chart-releaser action](https://github.com/bcgov/cas-airflow/runs/3166669235) was momentarily attempting to download from `downloads.apache.org`, but the chart was not there anymore.

Should the URL for v1.1.0 point to `archive.apache.org` too, so that it does not need to be updated when a new version of the chart is released?

**Comment by kaxil** [comment]
@matthieu-foucault Check https://infra.apache.org/mirrors#location :) 

Current public releases appear on downloads.apache.org/. Place current, official releases that the PMC has approved for end-users here, on the main public release site that is mirrored world-wide. Make all changes at https://dist.apache.org/repos/dist/release/.

Older releases that you no longer recommend to the general public should appear on archive.apache.org/dist/. This site automatically contains all the content of downloads.apache.org/, but nothing is ever deleted. Therefore it should rarely be necessary to touch this site, except during a reorganization. Once your project no longer recommends public use of a particualr release, simply delete it from downloads.apache.org/dist/ by removing it from https://dist.apache.org/repos/dist/release/. It will remain on the archive site.


**There will be some short duration where the dists are not available on archive.apache.org -- hence we can't use that for current stable release**

**Comment by naomiaro** [comment]
There was about a 60-90min delay with the 1.1.0 release process that made the chart unusable yesterday which was more of the issue.

1.0.0 had been removed from downloads.apache.org before 1.1.0 was added to https://airflow.apache.org/index.yaml, so neither 1.0.0 nor 1.1.0 could be installed at one point in time for about 60min when using helm charts. Only 1.1.0 was at downloads.apache.org, and only 1.0.0 was available in https://airflow.apache.org/index.yaml pointing to 1.0.0 at downloads.apache.org which didn't exist anymore at that time.

**Comment by potiuk** [comment]
Yep. The documentation (and thus index.yaml) is merged after release is done. One thing we can do is we can point to archive for all versions (including the latest one).

**Comment by kaxil** [comment]
We can't and shouldn't point to archive for the latest version.

The thing to do would be that I won't delete the old artifact for a day or too from downloads.apache.org.
