### ISSUE TITLE
Webserver doesn't show `params` in tast details

### ISSUE THREAD

**Issue by fjmacagno** [apache/airflow#17295]
**Apache Airflow version**: 2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: pip3
- **Others**:

**What happened**:

The `params` entry on the task details page is empty.

**What you expected to happen**:

The `params` entry shows the params i know were passed in dag trigger (since the task worked as intended)

**How to reproduce it**:
For any dag which has params passed to it when triggered, check the params field in the task instance details view.

![image](https://user-images.githubusercontent.com/42754983/127380267-6df6d1ca-c7e1-4ba4-a55b-e21eb5b4c6b2.png)

**Comment by jedcunningham** [comment]
@fjmacagno, I think you may be confusing `params` with the DagRun `conf`.

```
DummyOperator(task_id="task1", params={"hello": "world"})
```
![Screen Shot 2021-07-28 at 1 10 23 PM](https://user-images.githubusercontent.com/66968678/127381963-35cfe068-8a99-431e-b9d6-34c9483101c5.png)

You can see an example of it in the tutorial:
https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html

The DagRun `conf` is displayed on the DagRun list:

![Screen Shot 2021-07-28 at 1 14 26 PM](https://user-images.githubusercontent.com/66968678/127382409-24f1f933-f9d0-4a10-afc8-49221fe38086.png)

**Comment by fjmacagno** [comment]
Ahaaaaa that makes sense. Definitely a little confusing, I would expect to see that in the task instance data. Thanks!
