### ISSUE TITLE
pgbouncer-exporter wrong health check command

### ISSUE THREAD

**Issue by alexakra** [apache/airflow#17306]
**Apache Airflow version**: 2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.19.7

**Cloud provider or hardware configuration**: Azure

**What happened**:
metrics-exporter container fails during startup.

**Error message**: could not check store: pq: unrecognized configuration parameter "version"

**What do you think went wrong?**:
The check health command is:
`rows, err := s.db.QueryContext(ctx, "SHOW VERSION")`
[https://github.com/apache/airflow-pgbouncer-exporter/blob/af9089e9f69be7cc9b6eff928eac54c716defbbd/internal/store/sql.go#L163](https://github.com/apache/airflow-pgbouncer-exporter/blob/af9089e9f69be7cc9b6eff928eac54c716defbbd/internal/store/sql.go#L163)

which causes the error: unrecognized configuration parameter "version"

The correct command is: "SHOW server_version"

**Comment by mik-laj** [comment]
@potiuk  Could you give some tips on what the `airflow-pgbouncer-exporter` contribution process looks like? I suspect that we are not accepting new changes to this repository.

**Comment by potiuk** [comment]
Why not ? I think it's exactly the same as for airflow-site or any other repository. Pull Request will do. When we think we should make an image with it we will just push it as an image - as we did before. We do not officially release it (same as with airflow-site), we do not provide sources for it. 

Do you have other proposals how to proceed?

**Comment by potiuk** [comment]
For me this is exactly the same as when we use "postgres image" - with the difference that we push the image ourselves. but it is not the "software" released by ASF. But maybe we should rethink that approach. Any ideas are welcome here :)

**Comment by eladkal** [comment]
https://github.com/apache/airflow-pgbouncer-exporter/pull/2

**Comment by cjj1120** [comment]
Double check the following: 
- connection string and ensure you are connecting to pgbouncer.
- pgbouncer.ini -> ensure `admin_users` is added & the same user is used in connection string. 

ref: https://www.pgbouncer.org/usage.html#quick-start
