### ISSUE TITLE
no variables injected via AIRFLOW_VAR_NAME

### ISSUE THREAD

**Issue by jdomag** [apache/airflow#17338]
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.18.11

**Environment**: helm chart used to install airflow https://airflow.apache.org/docs/helm-chart/stable/adding-connections-and-variables.html#variables

**What happened**:
When I inject variables to airflow webserver pods via AIRFLOW_VAR_{NAME}  ( accordingly to: https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables ) 

I can't see them in Airflow webserver (Admin->Vabiables).
Vars in the pod:
```
kubectl exec airflow-webserver-76d474c884-t76s8 -- printenv | grep AIRFLOW_VAR
AIRFLOW_VAR_ANOTHER_KEY=value_2
AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW_VAR_ANOTHER_KEY=value_2

```

**What you expected to happen**: Variavle avaliable in UI in admin->Variables

**Comment by potiuk** [comment]
Variables added via env vars or secrets are not visibile in the UI. This is by design, also because you cannot modify them. The Variables UI is not "all variables of Airflow" but "Those variables that are defined in the DB and editable".
