### ISSUE TITLE
different parallelism for different types of task

### ISSUE THREAD

**Issue by surapuramakhil** [apache/airflow#17332]
**Description**

There could be certain task which requires huge amount of resources which can't be run with default parallelism and many other smaller tasks which are can run at parallelism of 32.

At present there is a parallelism config

The amount of parallelism as a setting to the executor. This defines the max number of task instances that should run simultaneously on this airflow installation 
parallelism = 32

A way where we can tag tasks and different level of parallelism for different tasks at entire airflow level.

Like having smaller task to run at default parallelism [32] but heavy task at much lower parallelism [1-4]

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

**Comment by potiuk** [comment]
This is currently possible with "pools" feature. https://airflow.apache.org/docs/apache-airflow/stable/concepts/pools.html
