### ISSUE TITLE
Add support for hyperparameter tuning on GCP Cloud AI

### ISSUE THREAD

**Issue by leahecole** [apache/airflow#17348]
@darshan-majithiya had opened #15429 to add the hyperparameter tuning PR but it's gone stale. I'm adding this issue to see if they want to pick it back up, or if not, if someone wants to pick up where they left off in the spirit of open source 😄

**Comment by subkanthi** [comment]
@potiuk can I have this assigned to me please

**Comment by potiuk** [comment]
Sure :)
