### ISSUE TITLE
The new weberser does not seem to care about AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA

### ISSUE THREAD

**Issue by cansjt** [apache/airflow#17374]
The new UI does not seem to care about the AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA configuration directive.

**Apache Airflow version**: 2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): not relevant

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The permissions table were create by the webserver user in the public schema:
```
airflow=> \dt+ public.*
                                       Liste des relations
 Schéma |           Nom           | Type  | Propriétaire | Persistence |   Taille   | Description 
--------+-------------------------+-------+--------------+-------------+------------+-------------
 public | ab_permission           | table | webserver    | permanent   | 8192 bytes | 
 public | ab_permission_view      | table | webserver    | permanent   | 40 kB      | 
 public | ab_permission_view_role | table | webserver    | permanent   | 56 kB      | 
 public | ab_register_user        | table | webserver    | permanent   | 8192 bytes | 
 public | ab_role                 | table | webserver    | permanent   | 8192 bytes | 
 public | ab_user                 | table | webserver    | permanent   | 16 kB      | 
 public | ab_user_role            | table | webserver    | permanent   | 8192 bytes | 
 public | ab_view_menu            | table | webserver    | permanent   | 8192 bytes | 
(8 lines)
```

**What you expected to happen**:

The webserver should not create table (not require such high privileges on the database), look for and use the table create by the migrations in the schema specified by the `AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA`. The tables were, indeed, properly created by the migrations. But then remain used (empty).

```
airflow=> \dt+ airflow.ab_*
                                           Liste des relations
 Schéma  |              Nom              | Type  | Propriétaire | Persistence |   Taille   | Description 
---------+-------------------------------+-------+--------------+-------------+------------+-------------
 airflow | ab_permission                 | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_permission_view            | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_permission_view_role       | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_register_user              | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_role                       | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_user                       | table | schema-admin | permanent   | 8192 bytes | 
 airflow | ab_user_role                  | table | schema-admin | permanent   | 0 bytes    | 
 airflow | ab_view_menu                  | table | schema-admin | permanent   | 8192 bytes | 
(8 lines)
```

This also causes permission issue as the tables, not being created by the migrations and in the wrong schema, do not inherit the permissions they should.

The generated SQL statements leave no doubts, on the fact that table names are not properly qualified with a schema name:
```
Broken DAG: [/opt/airflow/share/dags/test/test_dag.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for table ab_permission_view


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table ab_permission_view

[SQL: SELECT ab_permission_view.id AS ab_permission_view_id, ab_permission_view.permission_id AS ab_permission_view_permission_id, ab_permission_view.view_menu_id AS ab_permission_view_view_menu_id 
FROM ab_permission_view JOIN ab_permission ON ab_permission.id = ab_permission_view.permission_id JOIN ab_view_menu ON ab_view_menu.id = ab_permission_view.view_menu_id 
WHERE ab_permission.name = %(name_1)s AND ab_view_menu.name = %(name_2)s]
[parameters: {'name_1': 'can_read', 'name_2': 'DAG:TEST_DAG'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
``` 

**How to reproduce it**:

Airflow test suite should generate a random schema name and use it. Any access to a table not qualified with a schema name would be immediately detected.

**Anything else we need to know**:

Remediations (with postgresql):
- change tables permissions (not really secure)
- change user search path (not recommended though

**Comment by uranusjr** [comment]
I’m not entirely sure, but I think `sql_alchemy_schema` does not apply for `ab_*` prefixed tables; those are created by Flask-Appbuilder and out of Airflow’s control.

**Comment by cansjt** [comment]
I think if you use a framework to build an application, that application should control the behavior of the framework, not let it do as it pleases.

I am no specialist of Flask AppBuilder but my understanding is that you use it with regular SQLAlchemy declarative ORM models. So I am guessing you should be able to create those models with the appropriate `MetaData` object (w. custom base model class ?), specifying the same schema as other Airflow models or override the schema name on a per model basis. Though both method mean you need the configuration available while loading (importing) the models or make sure no model is ever imported before the configuration has been parsed...

You might also want ot have a look at this FAB issue: https://github.com/dpgaspar/Flask-AppBuilder/issues/1585 (fairly recent March of this year)
The last solution seems "cleaner" to me:
```python
db = SQLAlchemy(app)
db_eng = db.engine.execution_options(schema_translate_map= {None: configuration.get('core', 'SQL_ALCHEMY_SCHEMA')})
Session = sessionmaker(bind=db_eng)
db_sess = scoped_session(Session)
appbuilder = AppBuilder(app, db_sess)
```
Not sure it fits the current implementation though.

**Comment by uranusjr** [comment]
I think it’d work. AppBuilder is initialised here:

https://github.com/apache/airflow/blob/71088986f12be3806d48e7abc722c3f338f01301/airflow/www/extensions/init_appbuilder.py#L46-L52

and `settings.Session` is initialised here:

https://github.com/apache/airflow/blob/71088986f12be3806d48e7abc722c3f338f01301/airflow/settings.py#L204-L235

So I think we just need to consider `sql_alchemy_schema` in `prepare_engine_args`.

Backward compatibility would be the biggest issue though; we need to prevent breaking people using the current setup (not putting F.A.B. models inside a schema). But I think it can be done.

Would you be interested in taking a shot at this and submit a PR?

**Comment by potiuk** [comment]
Yeah. I think if we are creating the tables in "public" this should be fixed, the FAB tables should be created in the same schema as the airflow tables (or in dedicated schema if we would add this possibility). 

Submitting a PR fixing it would indeed be nice @cansjt

**Comment by potiuk** [comment]
We'd probably implement some migration path as @uranusjr mentioned - likely detecting if the tables are defined in public schema and offering the user migration to the new one. Those tables are rather small so simply copying the content over for those tables should be rather painless and fast.

**Comment by cansjt** [comment]
Well it is not the only issue I am facing with upgrading to Airflow 2.x. So I would like to sort those out first. But I'll see what I can do.

With respect to the migration, it might be quite tricky as, as I mentioned, the migrations created the table in the right schema (`airflow` in our case), but the application created others in the `public` schema.

To make matter worse both contain data. As we did not yet define any role etc. they seem to only contain the base permissions, but even those are not create in a very deterministic matters: _e.g._ a given permission (row in the `ab_permission` table) may not have the same ID in  both tables.

Would this migration strategy makes sense:
if the schema in airflow configuration is `None` or `public`:
- do nothing;
else:
- assume the tables in the public are the correct ones
- truncate those in the `<other>` schema;
- fill them back with the table in the `<other>` content of the tables in the `public` schema;
- drop the tables in the public schema;

Or is there a more clever way to do it ? (again, I never used Flask AppBuilder before)

**Comment by potiuk** [comment]
I think we need some of @jhtimmins expert knowledge on that part :)

**Comment by jedcunningham** [comment]
In the meantime, a workaround to this would be to not use `sql_alchemcy_schema` on the Airflow side and set it via `search_path` on the db or user on the psql side.

**Comment by cansjt** [comment]
FYI here is the SQL script I used to move things around:
```sql
TRUNCATE TABLE
    airflow.ab_permission,
    airflow.ab_view_menu,
    airflow.ab_user_role,
    airflow.ab_role,
    airflow.ab_user,
    airflow.ab_register_user,
    airflow.ab_permission_view_role,
    airflow.ab_permission_view ;
INSERT INTO airflow.ab_permission (name) SELECT name FROM public.ab_permission ;
INSERT INTO airflow.ab_view_menu (name) SELECT name FROM public.ab_view_menu ;
INSERT INTO airflow.ab_role (name) SELECT name FROM public.ab_role ;
INSERT INTO airflow.ab_user (first_name,
                             last_name,
                             username,
                             password,
                             active,
                             email,
                             last_login,
                             login_count,
                             fail_login_count,
                             created_on,
                             changed_on,
                             created_by_fk,
                             changed_by_fk)
    SELECT
        first_name,
        last_name,
        username,
        password,
        active,
        email,
        last_login,
        login_count,
        fail_login_count,
        created_on,
        changed_on,
        created_by_fk,
        changed_by_fk
    FROM public.ab_user ;
INSERT INTO airflow.ab_register_user (first_name,
                                      last_name,
                                      username,
                                      password,
                                      email,
                                      registration_date,
                                      registration_hash)
    SELECT
        first_name,
        last_name,
        username,
        password,
        email,
        registration_date,
        registration_hash
    FROM public.ab_register_user ;
INSERT INTO airflow.ab_user_role (user_id, role_id)
    SELECT
        au.id AS user_id,
        ar.id AS role_id
    FROM
        public.ab_user_role  AS pur
        JOIN public.ab_user  AS pu  ON pur.user_id = pu.id
        JOIN public.ab_role  AS pr  ON pur.role_id = pr.id
        JOIN airflow.ab_user AS au  ON pu.username = au.username
        JOIN airflow.ab_role AS ar  ON pr.name     = ar.name
    ;
INSERT INTO airflow.ab_permission_view (permission_id, view_menu_id)
    SELECT
        ap.id  AS permission_id,
        avm.id AS view_menu_id
    FROM
        public.ab_permission_view  AS ppv
        JOIN public.ab_permission  AS pp  ON ppv.permission_id = pp.id
        JOIN public.ab_view_menu   AS pvm ON ppv.view_menu_id  = pvm.id
        JOIN airflow.ab_view_menu  AS avm ON pvm.name          = avm.name
        JOIN airflow.ab_permission AS ap  ON ap.name           = pp.name
    ;
INSERT INTO airflow.ab_permission_view_role (permission_view_id, role_id)
    SELECT
        pv_map.schema_permission_view_id AS permission_view_id,
        ar.id  AS role_id
    FROM
        public.ab_permission_view_role AS ppvr
        JOIN (SELECT
                  ppv.id AS public_permission_view_id,
                  apv.id AS schema_permission_view_id
              FROM
                  public.ab_permission_view  AS ppv
                  JOIN public.ab_permission  AS pp  ON ppv.permission_id = pp.id
                  JOIN public.ab_view_menu   AS pvm ON ppv.view_menu_id  = pvm.id
                  JOIN airflow.ab_view_menu  AS avm ON pvm.name          = avm.name
                  JOIN airflow.ab_permission AS ap  ON ap.name           = pp.name
                  JOIN airflow.ab_permission_view AS apv
                      ON apv.view_menu_id = avm.id AND apv.permission_id = ap.id
         ) AS pv_map ON ppvr.permission_view_id = pv_map.public_permission_view_id
        JOIN public.ab_role                 AS pr   ON ppvr.role_id            = pr.id
        JOIN airflow.ab_role                AS ar   ON pr.name                 = ar.name
    ;
```
Ensures, in the most portable way I could think of, that there will be no issues with ID (or sequences or whatever).
Controlled things went okay with these ones. They should not return any row, if everything went fine:
```
SELECT
    ar.name,
    avm.name,
    ap.name
FROM
    airflow.ab_permission_view_role AS apvr
    JOIN airflow.ab_permission_view AS apv ON apv.id = apvr.permission_view_id
    JOIN airflow.ab_view_menu AS avm ON avm.id = apv.view_menu_id
    JOIN airflow.ab_role AS ar ON ar.id = apvr.role_id
    JOIN airflow.ab_permission AS ap ON ap.id = apv.permission_id
EXCEPT
    SELECT
        pr.name,
        pvm.name,
        pp.name
    FROM
        public.ab_permission_view_role AS ppvr
        JOIN public.ab_permission_view AS ppv ON ppv.id = ppvr.permission_view_id
        JOIN public.ab_view_menu AS pvm ON pvm.id = ppv.view_menu_id
        JOIN public.ab_role AS pr ON pr.id = ppvr.role_id
        JOIN public.ab_permission AS pp ON pp.id = ppv.permission_id
;
SELECT
    au.username,
    ar.name
FROM
    airflow.ab_user_role AS aur
    JOIN airflow.ab_user AS au ON aur.user_id = au.id
    JOIN airflow.ab_role AS ar ON ar.id = aur.role_id
EXCEPT
    SELECT
        pu.username,
        pr.name
    FROM
        public.ab_user_role AS pur
        JOIN public.ab_user AS pu ON pur.user_id = pu.id
        JOIN public.ab_role AS pr ON pr.id = pur.role_id
;
```

**Comment by shicholas** [comment]
I think this works if you set two environment variables, and pass the schema in the connection url like @jedcunningham mentioned.

```bash
export AIRFLOW__CORE__SQL_ALCHEMY_CONN="postgresql://postgres@localhost:5432/my_db?options=-csearch_path%3Dairflow"
export AIRFLOW__CORE__SQL_ALCHEMY_SCHEMA="airflow"
```

now you should see airflow tables in the `airflow` schema of `my_db`.

Hope this helps.

**Comment by potiuk** [comment]
@cansjt  - seems that the solution proposed by @shicholas should solve the problem. Could you please confirm that it does?  Ideally maybe (instead of changing anything in Airflow) - adding a bit of documentation to Airlfow for the users who would like to follow it might be good @cansjt @shicholas - maybe you would like to add it?

**Comment by potiuk** [comment]
Closing it for now then until more information is available.,

**Comment by fungss** [comment]
The solution provided by @shicholas does not work if MSSQL is used. MSSQL does not have schema search path implemented. Please find below the returned error message for your reference.


> \> airflow db reset
/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/models/base.py:27 DeprecationWarning: The sql_alchemy_schema option in [core] has been moved to the sql_alchemy_schema option in [database] - the old setting has been used, but please update your config.
DB: <my_mssql_connection_string>
This will drop existing tables if they exist. Proceed? (y/n)y
[2022-12-28 03:33:35,789] {db.py:1598} INFO - Dropping tables that exist
[2022-12-28 03:33:38,615] {migration.py:204} INFO - Context impl MSSQLImpl.
[2022-12-28 03:33:38,615] {migration.py:207} INFO - Will assume transactional DDL.
[2022-12-28 03:33:38,649] {migration.py:204} INFO - Context impl MSSQLImpl.
[2022-12-28 03:33:38,649] {migration.py:207} INFO - Will assume transactional DDL.
Traceback (most recent call last):
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "dbo" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/ronaldfung/Projects/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/__main__.py", line 39, in main
    args.func(args)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/db_command.py", line 46, in resetdb
    db.resetdb(skip_init=args.skip_init)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/db.py", line 1611, in resetdb
    initdb(session=session)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/db.py", line 697, in initdb
    _create_db_from_orm(session=session)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/db.py", line 682, in _create_db_from_orm
    _create_flask_session_tbl()
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/airflow/utils/db.py", line 677, in _create_flask_session_tbl
    db.create_all()
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 851, in visit_metadata
    self.traverse_single(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    self.connection.execute(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ronaldfung/Projects/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The specified schema name "dbo" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)')
[SQL: 
CREATE TABLE session (
        id INTEGER NOT NULL IDENTITY, 
        session_id VARCHAR(255) NULL, 
        data VARBINARY(max) NULL, 
        expiry DATETIME NULL, 
        PRIMARY KEY (id), 
        UNIQUE (session_id)
)
]
(Background on this error at: https://sqlalche.me/e/14/f405)
