### ISSUE TITLE
Allow using default celery commands for custom Celery executors subclassed from existing

### ISSUE THREAD

**Issue by georborodin** [apache/airflow#17373]
**Description**

Allow custom executors subclassed from existing (CeleryExecutor, CeleryKubernetesExecutor, etc.) to use default CLI commands to start workers or flower monitoring.

**Use case / motivation**

Currently, users who decide to roll their own custom Celery-based executor cannot use default commands (i.e. `airflow celery worker`) even though it's built on top of existing CeleryExecutor. If they try to, they'll receive the following error: `airflow command error: argument GROUP_OR_COMMAND: celery subcommand works only with CeleryExecutor, your current executor: custom_package.CustomCeleryExecutor, see help above.`

One workaround for this is to create custom entrypoint script for worker/flower containers/processes that are still going to use the same Celery app as CeleryExecutor. This leads to unnecessary maintaining of this entrypoint script.

I'd suggest two ways of fixing that:

- Check if custom executor is subclassed from Celery executor (which might lead to errors, if custom executor is used to access other celery app, which might be a proper reason for rolling custom executor)
- Store `app` as attribute of Celery-based executors and match the one provided by custom executor with the default one

**Related Issues**

N/A

**Comment by potiuk** [comment]
Would you like to provide a PR fixing it? Seems like the approach where executor could define what "type" of the executor it is a good approach. Sounds like an easy fix.

**Comment by georborodin** [comment]
@potiuk would be my pleasure! Suppose I'd be able to provide a PR in a couple of days

**Comment by potiuk** [comment]
Assigned you then :)

**Comment by georborodin** [comment]
@potiuk would you mind taking a look at my PR to see if I got it right? I feel that code might be a bit 'hacky' 😄

**Comment by potiuk** [comment]
> @potiuk would you mind taking a look at my PR to see if I got it right? I feel that code might be a bit 'hacky'

Not really. It's good. Small Nit :)

**Comment by santosh-d3vpl3x** [comment]
We ran into this limitation while trying to extend celery executor to fix one of the issues found during airflow upgrade. It would be a good addition definitely :)

**Comment by dongwangdw** [comment]
Why I still got this issue in 2.4.1?

**Comment by potiuk** [comment]
It's pretty uselsss to ask question 'why". By definition it's impossible to answer. Until you provide more details it may or may not be similar or different issue. 

If you have similar issue - please open a new one an describe all details and logs @dongwangdw. It might be different issue, or you could have made a mistake, or misunderstood it.
