### ISSUE TITLE
With Helm Chart, get CSRF error if setting webserver.replicas > 1

### ISSUE THREAD

**Issue by smythie86** [apache/airflow#17398]
**Apache Airflow version**: 2.1.2
**Airflow Helm Chart version: 1.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What happened**: I set webserver.replicas to 2 in my helm chart, and then when I attempt to login, I get an error : 
Bad Request
The CSRF session token is missing.

**What you expected to happen**: I expect to be able to login successfully.

**How to reproduce it**: Install the helm chart, and set webserver.replicas to 2. Then attempt to login to the UI.

**Anything else we need to know**:
I was able to get this working by also setting the webserverSecretKey in the values.yaml file of the helm chart as well. But I think the helm chart should set the key to the same value for each replica of the webserver, or alternatively, the documentation should make it clear that the key needs to be set when setting webserver.replicas to more than 1.

**Comment by jedcunningham** [comment]
#17142 should have fixed this. Silly question, but are you sure you are on 1.1.0, not 1.0.0? Do you see the `valueFrom` `AIRFLOW__WEBSERVER__SECRET_KEY` env var in your webserver pods?

**Comment by smythie86** [comment]
Yes, I confirmed that I am running 1.1.0, and that the AIRFLOW__WEBSERVER__SECRET_KEY env variable is set.

After more digging, I discovered that this bug doesn't happen on a helm install, only on a helm-upgrade.

To reproduce: Run helm install for the airflow chart. Once the chart is deployed, increase the replicas count for webserver, and run helm upgrade. You will then receive this error.

It seems to me that the webserver-secret-key secret is also updated, and an additional webserver pod will be started. However, since the older webserver pod was not restarted, it will have the old value of the secret, and will be out of sync with the value of the secret and the new webserver pods.

**Comment by jedcunningham** [comment]
Thanks @smythie86. Unfortunately the naive approach of just adding annotations where necessary isn't enough to fix this (it would cause worker restarts on any `helm upgrade`, which we don't want). In the meantime setting the secret-key is a good solution.

**Comment by jedcunningham** [comment]
Just to follow up here, restarts are now forced whenever the secret key changes (#18079) and a notice is shown when a dynamic secret key is used (#18306) so unnecessary restarts can be avoided.
