### ISSUE TITLE
Path to dags folder in incorrect while using DagBag

### ISSUE THREAD

**Issue by shlomi-viz** [apache/airflow#17404]
**Apache Airflow version**:
`apache-airflow==2.1.2`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
Local on Mac
**What happened**:
While running tests, with `pytest` I'm getting import errors (in my case). 
```python 
ModuleNotFoundError: No module named 'encryption'
````

**What you expected to happen**:
Dag should be imported without errors.

**How to reproduce it**:

**Anything else we need to know**:
When I'm running the UI I use `AIRFLOW_HOME` to indicate where is the `airflow` folder, in the tests I have: 
```python
import sys
from airflow.models import DagBag

from decouple import config
AIRFLOW_HOME = config('AIRFLOW_HOME')

class Test(object):
    @classmethod
    def setup_class(cls):
        cls.dagbag = DagBag(f'{AIRFLOW_HOME}/dags/', include_examples=False)
        print(cls.dagbag.dags)

    def test_dag_loaded(self):
        dag = self.dagbag.get_dag(dag_id='test_dag')
        assert self.dagbag.import_errors == {}
        assert dag is not None
        assert len(dag.tasks) == 1

```

note that I had to add

```python 
        sys.path.append(f'{AIRFLOW_HOME}/dags/')
````
to fix the above error

**Comment by potiuk** [comment]
This is expected behaviour. DAGs folder is expected to be in the system path  if you need to import something from there in your DAG.

**Comment by potiuk** [comment]
See also here: https://airflow.apache.org/docs/apache-airflow/stable/modules_management.html#additional-modules-in-airflow - DAGS folder is explicitly added by the path and if  your tests are going to simulate airfow\s behaviour, they have to do the same.

**Comment by shlomi-viz** [comment]
Looking at the above link I see 

> Config folder: It is configured by setting AIRFLOW_HOME variable ({AIRFLOW_HOME}/config) by default. 
but if I ran my tests without 
```python
sys.path.append(f'{AIRFLOW_HOME}/dags/')
```
those are the paths I see in `sys.path`
```bash
'/Users/USERNAME/airflow/dags', '/Users/USERNAME/airflow/config', '/Users/USERNAME/airflow/plugins'
```
instead of:
```bash
'/Users/USERNAME/workspace/PROJECT_NAME/airflow/dags', '/Users/USERNAME/workspace/PROJECT_NAME/airflow/config', '/Users/USERNAME/workspace/PROJECT_NAME/airflow/plugins'
````

What I'm doing wrong?

**Comment by potiuk** [comment]
Check your AIRFLOW_HOME settings. Just debug what are your settings when you run Test and fix it. Not sure how you are running yout tests and what settings you have but this is something that is definitely on your environment side, not Airflow.

**Comment by shlomi-viz** [comment]
Thanks, the problem was in my code, I used https://pypi.org/project/python-decouple/ to load the env var but it doesn't add them into `os.environ`
