### ISSUE TITLE
New view "Operator arguments" between "Task Instance Details" and "Rendered"

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#17473]
Hello. A lot of times, when I click on a task, I just want to see the operator arguments that can be manually passed, so Rendered view lacks information, because there are not non-renderable arguments, and Task Instance Details has way too much information, because I don't care about most of the things that are there.

I think it would be useful to add a feature to accomplish this. It could be a new button/view called Task Operator arguments or something like that

**Comment by potiuk** [comment]
Feel free to propose PR. I think seeing some screenshots here would be useful here before to asses how big of a problem it is

**Comment by JavierLopezT** [comment]
Let's say you have the following default_args:

```
default_args = {
    'email': globals_variables['email_data'],
    'file_format': globals_variables['file_format_csv']['es'],
    'schema': 'schema',
    'database': 'dwh'
    }
```
And the following custom SnowflakeOperator:
```
dw_ext_ba_campaign_costs = SnowflakeOperator(
        task_id='dw_ext_ba_campaign_costs',
        warehouse='warehouse',
        incr_table='ba_campaign_costs'
)
```
Basically I would like to have a button somewhere like this:
<img width="703" alt="Captura de pantalla 2021-09-27 a las 15 08 12" src="https://user-images.githubusercontent.com/11339132/134914580-bdb0fd74-c27d-4251-bca0-ac9f4471da55.png">

It would show me the following information:

<img width="714" alt="Captura de pantalla 2021-09-27 a las 15 09 57" src="https://user-images.githubusercontent.com/11339132/134915205-2bf4426c-843a-44b2-9c29-2148653b8f2e.png">

**Comment by uranusjr** [comment]
Do you want `file_format` to show `globals_variables['file_format_csv']['es']` literally? I don't think it's possible.
