### ISSUE TITLE
Execution date is in future

### ISSUE THREAD

**Issue by thaysa** [apache/airflow#17481]
**Apache Airflow version**: 
2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.19.6

**Environment**:
On-premise Cluster
Official Docker Image with Python 3.8

**What happened**:
The scheduler is triggering future run
_Execution date is in future: 2021-08-07 00:00:00+00:00_

![image](https://user-images.githubusercontent.com/6821208/128580442-44f79960-80c4-44b4-8e33-16c04982b5f1.png)

**What you expected to happen**:
Scheduler should not trigger future execution date

**How to reproduce it**:
Not sure if there is a deterministic steps to reproduce it. There was an  env issue in the cluster that was preventing the communication to the Airflow Metadata database (Postgresql) database- 
"could not translate host name"

After this behavior, when the pods were restarted,  the dag started future execution.

pods and database are in UTC timezone

https://github.com/apache/airflow/blob/main/airflow/jobs/scheduler_job.py

```
        if dag_run.execution_date > timezone.utcnow() and not dag.allow_future_exec_dates:
            self.log.error("Execution date is in future: %s", dag_run.execution_date)
            return 0
```

**Comment by lewismc** [comment]
We also encountered this issue. We discovered it through our integration with Sentry. Have no idea how to further diagnose.

**Comment by thaysa** [comment]
@lewismc  in my case, the dates were out of sync between the Airflow metadatabase server and the Airflow scheduler pod. They were both in UTC but they were out of sync.

**Comment by potiuk** [comment]
This is very likely casee for you @lewismc. Make sure that your time is synced (for example with ntp) on all the machines you have airflow components.

**Comment by potiuk** [comment]
If you are on AWS then you likely need to apply https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

**Comment by lewismc** [comment]
Excellent thank you @potiuk ... i think this might just be it. We can probably close https://issues.apache.org/jira/browse/AIRFLOW-6500

**Comment by potiuk** [comment]
We don't use JIRA any more. It's been put in READ-ONLY mode some 2.5 years ago :)
