### ISSUE TITLE
Connection health check

### ISSUE THREAD

**Issue by malthe** [apache/airflow#17498]
**Description**

Add an option to enable a "Connection health check" on a connection.

This would have the effect that a background connection test would be scheduled to run with a configurable interval (globally configured). The test would be executed by a worker.

If one or more connection health checks currently fail, a message on the main page will be shown. In addition, the connection list will show a health status for each entry.

**Use case / motivation**

It's previously been proposed to run a connection check as part of saving a new connection through the Airflow UI (see related issues below).

But such a health check is really an on-going concern – similar to how DAG input files are scanned for syntax errors and reported on the main page.

**Are you willing to submit a PR?**

Yes

**Related Issues**

- https://issues.apache.org/jira/browse/AIRFLOW-2998

**Comment by BasPH** [comment]
I realize your issue suggests different behaviour, but linking this here for reference https://github.com/apache/airflow/pull/15795

**Comment by malthe** [comment]
@BasPH oh awesome – when is this coming to an Airflow release? I don't see it in the latest 2.1.2 release.

**Comment by BasPH** [comment]
It's currently set for Airflow 2.2 (you can see a "Milestone" section in the PR).
