### ISSUE TITLE
Lint Dockerfile - pre_commit_lint_dockerfile.sh  takes too long or gets stuck

### ISSUE THREAD

**Issue by subkanthi** [apache/airflow#17494]
On Mac M1, the "Lint Dockerfile" pre-commit step takes forever to complete. Need to troubleshoot and add a fix for this problem.

Environment:
Docker version 20.10.6, build 370c289
Mac M1 Big Sur

**Comment by potiuk** [comment]
You can always disable it by setting SKIP variable in the meantime https://pre-commit.com/#temporarily-disabling-hooks

**Comment by subkanthi** [comment]
> You can always disable it by setting SKIP variable in the meantime https://pre-commit.com/#temporarily-disabling-hooks (as a workaround)

Thanks that helps for now
