### ISSUE TITLE
BigQueryInsertJobOperator may start the same job twice

### ISSUE THREAD

**Issue by hsej** [apache/airflow#17493]
**Apache Airflow version**: 1.10.15

**Apache Airflow Provider versions** (please include all providers that are relevant to your bug):
apache-airflow-backport-providers-google==2021.3.3

**What happened**:
Looking at the _submit_job method the job is started by using job.result() - in bold below. However, the job IS already started by just callnig the hook.insert_job() method. Thus I suggest removing the extra job.result() call in the _submit_job() method below.
```
    def _submit_job(
        self,
        hook: BigQueryHook,
        job_id: str,
    ) -> BigQueryJob:
        # Submit a new job
        job = hook.insert_job(
            configuration=self.configuration,
            project_id=self.project_id,
            location=self.location,
            job_id=job_id,
        )
        # Start the job and wait for it to complete and get the result.
        **job.result()**
        return job
```

**Comment by hsej** [comment]
Sorry!

Thank you very much for that.

**Comment by uranusjr** [comment]
We have ceased maintenance of Airflow 1.10. Please consider upgrading to Airflow 2.
