### ISSUE TITLE
Changing role name in access_control doesn't remove permission from previous role

### ISSUE THREAD

**Issue by sudarshan2906** [apache/airflow#17508]
**Apache Airflow version**: 2.1.2

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Debian 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When access_control is configured in a dag, and we remove a role from access_control. The permission doesn't get removed from that role
When `access_control={"test_role":{"can_edit"}}`
![image](https://user-images.githubusercontent.com/25225354/128717114-1e7a2c0a-53a3-4e56-b3cc-48ae7bd35129.png)
After access_control is changed to {}
![image](https://user-images.githubusercontent.com/25225354/128717114-1e7a2c0a-53a3-4e56-b3cc-48ae7bd35129.png)

**What you expected to happen**:
The role should have also updated and the permission should be removed

**How to reproduce it**:
Create a dag with access control property set and after it gets created, edit the dag's access_control property by just removing a role or just replace it with another role.

How often does this problem occur? Once? Every time etc?
Every Time

**Comment by alete89** [comment]
is there at least a CLI command that we could run to refresh permissions from DAGs `access_control` field? both remove and add new ones.

**Comment by jedcunningham** [comment]
What version of Airflow are you running? I see it in help:

```
$ airflow sync-perm --help
usage: airflow sync-perm [-h] [--include-dags]

Update permissions for existing roles and optionally DAGs

optional arguments:
  -h, --help      show this help message and exit
  --include-dags  If passed, DAG specific permissions will also be synced.
```

**Comment by alete89** [comment]
Woops! You're right, Jed, I suppose I missed something when I ran it last time.

Now getting back to the bug, I'm experiencing this on 2.1.4 but I tested it on 2.2.2 locally and it happens as well.
What I'm experiencing is Airflow not updating permissions at all (neither adding or removing role permissions) based on DAG `access_control` field. 

Only by running `airflow sync-perm --inlcude-dags` will add new permissions if existing, but not removing any (as the issue states).

**Comment by jedcunningham** [comment]
I wonder if you are running into this? #18575

Make a trivial change and watch your UI for an import_error (it'll only last a single dag parsing cycle), or look in your parsing log (e.g. AIRFLOW_HOME/logs/scheduler/...).

Removal of the role isn't an easy fix, unfortunately, but adding new roles should work.

**Comment by zachliu** [comment]
i'm on 2.9.2 and experiencing this too

whenever the creation of a dag with `dag.access_control = {"Role_A": {"can_edit", "can_read"}}` precedes the creation of `Role_A`, the role permissions won't be updated unless the airflow server is restart or `airflow sync-perm --include-dags` is executed on the server.

I thought the reoccurring dag parsing mechanism should take care of the permission-sync

```
min_serialized_dag_update_interval = 30
min_serialized_dag_fetch_interval = 10
```

**Comment by potiuk** [comment]
> i'm on 2.9.2 and experiencing this too
> 
> whenever the creation of a dag with `dag.access_control = {"Role_A": {"can_edit", "can_read"}}` precedes the creation of `Role_A`, the role permissions won't be updated unless the airflow server is restart or `airflow sync-perm --include-dags` is executed on the server.
> 
> I thought the reoccurring dag parsing mechanism should take care of the permission-sync
> 
> ```
> min_serialized_dag_update_interval = 30
> min_serialized_dag_fetch_interval = 10
> ```

I think this one might simply not work this way, so I marked it as good first issue for someone to take a look and investigate. @zachliu -> maybe you would like to dig-in?

**Comment by zachliu** [comment]
> > i'm on 2.9.2 and experiencing this too
> > whenever the creation of a dag with `dag.access_control = {"Role_A": {"can_edit", "can_read"}}` precedes the creation of `Role_A`, the role permissions won't be updated unless the airflow server is restart or `airflow sync-perm --include-dags` is executed on the server.
> > I thought the reoccurring dag parsing mechanism should take care of the permission-sync
> > ```
> > min_serialized_dag_update_interval = 30
> > min_serialized_dag_fetch_interval = 10
> > ```
> 
> I think this one might simply not work this way, so I marked it as good first issue for someone to take a look and investigate. @zachliu -> maybe you would like to dig-in?

yes, i'm doing some initial investigation and just realized a simple fact: the dag parsing mechanism indeed doesn't do anything unless the dag code is changed:

https://github.com/apache/airflow/blob/f56f13442613912725d307aafc537cc76277c2d1/airflow/models/dagbag.py#L648-L649

my current bandaid solution is to have a designated dag do this every 2 mins

```python
run_this = BashOperator(
    task_id="sync_perm",
    bash_command="/entrypoint.sh airflow sync-perm --include-dags -v",
    env={"PYTHONPATH": "/usr/local/airflow/"},
    append_env=True,
)
```

**Comment by eladkal** [comment]
@joaopamaral you recently raised PRs around access control. Maybe you'd be willing to look into this issue?

**Comment by joaopamaral** [comment]
Hey @sudarshan2906 and @eladkal , I've tested with the master branch and seems to be working correct:

- added the following access control:
```python
    access_control={
        "Public": {"DAGs": {"can_edit"}, "DAG Runs": {"can_create"}}
    }
```
<img width="539" alt="image" src="https://github.com/user-attachments/assets/a8ca703e-bed1-4b85-9c4b-a3eb158b9112">

- changed to `access_control={}`
<img width="167" alt="image" src="https://github.com/user-attachments/assets/747db888-b4e3-49ed-8815-6f7e71f26d52">

- Back to the permissions to Public and then changed to Viewer
```python
    access_control={
        "Public": {"DAGs": {"can_edit"}, "DAG Runs": {"can_create"}}
    }
```
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/4027ba5d-0022-466e-8eae-f53aa5c6ec44">

It takes a few seconds to sync (~30s) but all these tests show the dags permissions are synced automatically.
 
@sudarshan2906 are you still facing this issue in the latest airflow version?
