### ISSUE TITLE
ImportError: /usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

### ISSUE THREAD

**Issue by github-sunildhiddi** [apache/airflow#17511]
**Apache Airflow version**:

**Apache Airflow Provider versions** (please include all providers that are relevant to your bug):

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Without providing aby details and explaining how you got the problem into we are nor able to help
 Just filmów the template and fill-in all data there.
