### ISSUE TITLE
the filter condition of taskinstance does not work

### ISSUE THREAD

**Issue by luoyuliuyin** [apache/airflow#17535]
**Apache Airflow version**: 2.1.0

**Apache Airflow Provider versions** (please include all providers that are relevant to your bug):

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: pip
- **Others**:

**What happened**:
I click the sample dag and my link is: http://127.0.0.1:8080/graph?dag_id=example_bash_operator
![image](https://user-images.githubusercontent.com/28948186/128862854-5a1a105b-15fd-4b1e-b1b2-f86f651e7bbd.png)
![image](https://user-images.githubusercontent.com/28948186/128862931-a9d3c3d7-f8ae-44c3-9249-e2d05a8c3b79.png)
The dag I visited is `example_bash_operator`, but the dag_id filter condition does not work. After the link jumps, all tasks related to `also_run_this` are displayed.
![image](https://user-images.githubusercontent.com/28948186/129029224-80fbc4c3-dcf9-4bb5-8086-4c071ea5bb2d.png)

**What you expected to happen**:
Only display tasks related to `example_bash_operator`, such as
![image](https://user-images.githubusercontent.com/28948186/128864202-505b54c1-8e39-48c9-8df0-3f2c51ce7a49.png)

**How to reproduce it**: 
Run airflow by command `airflow webserver`, visit this link: http://127.0.0.1:8080/graph?dag_id=example_bash_operator, and finally click the `All Instances` button

**Anything else we need to know**:

If this is a bug, I can draft a PR to fix it

**Comment by bbovenzi** [comment]
That does seem to be a bug. Feel free to draft up a PR and I'll review it.

**Comment by luoyuliuyin** [comment]
> That does seem to be a bug. Feel free to draft up a PR and I'll review it.
Okay, I have drafted a PR.

**Comment by bbovenzi** [comment]
> > Okay, I have drafted a PR.

Your changes are looking good. Care to open a full PR to review?

**Comment by luoyuliuyin** [comment]
> > > Okay, I have drafted a PR.
> 
> Your changes are looking good. Care to open a full PR to review?

Okay, the PR address is:
https://github.com/apache/airflow/pull/17548
