### ISSUE TITLE
Dags are not triggered at right time when start date is set

### ISSUE THREAD

**Issue by rabsr** [apache/airflow#17534]
**Apache Airflow version**: 2.1.2

**What happened**:

Dags created with start date are not triggered on expected time. 
For eg. start date = `2021-07-29T06:00Z` and schedule interval `00 06 */1 * *`, 
The dag is triggered at  `2021-07-30, 06:00:01` but using execution date as `2021-07-29, 06:00:00`

**What you expected to happen**:

 The dag should be triggered at  `2021-07-29, 06:00:01`

**How to reproduce it**:

1. Use following dag
```
args = {
    'owner': ‘test’-user
}

dag = DAG(
    dag_id=‘dag’_id_test,
    default_args=args,
    schedule_interval='20 15 */1 * *',
    access_control={‘test-user: {'can_read', 'can_edit'}},
    start_date = datetime.datetime.strptime('2021-07-29T06:00Z', "%Y-%m-%dT%H:%MZ"),
    end_date = datetime.datetime.strptime('2021-07-30T06:30Z', "%Y-%m-%dT%H:%MZ")
}


notebook_task = PapermillOperator(
    task_id=‘task’_id_test,
    dag=dag,
    run_as_user='test-user',
    input_nb=‘nb_inp_test.ipynb',
    output_nb=nb_out_test.ipynb,
    parameters={}
)

notebook_task
```

**Comment by uranusjr** [comment]
This is correct. Aifrlow has an implicit notion of *intervals*. For a DAG started at 2021-07-29 and runs every day, it needs one initial day before executing, so the initial run have that one day of data to extract. The second run would happen on 2021-07-31 so it can process data for that previous day, and so on. The terminology around this is a bit confusing (and we plan to improve this in 2.2), but the *idea* itself won’t change, and your DAG won’t be scheduled immediately.
