### ISSUE TITLE
Cannot enter in localhost:8080

### ISSUE THREAD

**Issue by rubenjv7** [apache/airflow#17555]
**Apache Airflow version**:

**Apache Airflow Provider versions** (please include all providers that are relevant to your bug):

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment]
Please use Stackoverflow / Slack for support.
