### ISSUE TITLE
Airflow with latest slim-buster(3.9) along with latest stable debian release.

### ISSUE THREAD

**Issue by pukaleashish** [apache/airflow#17566]
The current 3.6 slim-buster version has vulnerabilities issues.
Could you please update to 3.9 slim-buster with stable debian release.
ETA for doing this activity.

**Comment by uranusjr** [comment]
Could you describe what vulnerability issues you are referring to?

**Comment by pukaleashish** [comment]
PFA XLS sheet for detailed vulnerability issues
[Airflow_vulneribility.xlsx](https://github.com/apache/airflow/files/6973091/Airflow_vulneribility.xlsx)

**Comment by uranusjr** [comment]
So since those are vulnarabilities in the Linux distribution, is the goal to move off *Buster*? Note that Airflow images are not built against Debian’s system Python, but a separate CPython installation under `/usr/local` (it’s based on `python:3.6`.

**Comment by pukaleashish** [comment]
How to fix those vulnerabilities?
I thought if we move to latest Buster those vulnerabilities would be addressed.

**Comment by pukaleashish** [comment]
Thanks for sharing info.
I didnt mean to be rude here.
I was just asking the details when the slim buster would be updated to latest version.
Anyways i will go through the documentation shared by you.
Thanks once again.

**Comment by uranusjr** [comment]
Airflow’s images are based on CPython’s builds (https://hub.docker.com/_/python); `apache/airflow:2.1.2-python3.6`, for example, is built against `python:3.6-slim-buster`. So if anything non-Python contains vulnarabilities, you should report it to the Python image’s maintainers (information available on the DockerHub page).
