### ISSUE TITLE
importing Operators directly from DAGS folder in airflow

### ISSUE THREAD

**Issue by madhusudhan0542** [apache/airflow#17573]
### Discussed in https://github.com/apache/airflow/discussions/17569

<div type='discussions-op-text'>

<sup>Originally posted by **madhusudhan0542** August 12, 2021</sup>
My intent is to create a Operator folder in dags folder (airflow/dags/operator/) and place my operators in use there. so that I can create a repository at git for dags folder and when I make changes to operator which can reflect to the repository and then the team members can also clone accordingly

```
airflow
 |--dags
 |      |--operators
 |      |       |--MsSqlOperator.py
 |      |--dag_file.py
 |      |--dag_file1.py
 |      |--dag_file2.py
 |
```

here while I was trying to import Class from the MsSqlOperator.py I was unable to import, were it states MsSqlOperator is undefined because airflow can't point to dags folder while importing , How can I import my operator file which is in dags/operators/  folder

thank you in advance!

</div>

**Comment by jedcunningham** [comment]
@madhusudhan0542, I'm going to close this in favor of the discussion linked in the description.

**Comment by madhusudhan0542** [comment]
Yes, we can import a file to the dag files by just importing them as if we do in python, ex:  "from operators.MsSqlOperator import ms_sql" . I can make this happen in my local, by giving all the permissions to the file which we are importing(reason why I can't make it earlier). Thank you
