### ISSUE TITLE
DAG trigger with config params visualisation with proper deserialisation

### ISSUE THREAD

**Issue by sbrundu** [apache/airflow#17582]
**Description**

Add a proper `params` configuration in the trigger page of a DAG showing the dict without the serialisation format `__var` and `__type` but with a flat, normal dict.

**Use case / motivation**

Now we are using the `params` dictionary that can be configured in the DAG. In our case this configuration is a dictionary with nested fields. When this is showed in the trigger page is we see the serialised format of the dictionary with the content of the dict in `__var` and `__type = dict`. In that form instead we should have the dictionary in a flat format with only the different contents nested. In the images you can see some examples.

To improve this we can deserialise the dict before being visualised in the UI.

Example:
Now I'm configuring the dag with this definition...
```
dag_params = {
    'dag_name': f'{DAG_NAME}',
    'env': 'qa',
    'config': {'categories': [], 'end': '2020-01-01', 'start': '2021-01-01'},
}

dag = DAG(
    DAG_NAME,
    default_args=default_args,
    [...]
    params=dag_params,
)
```
And this is what I see in the DAG trigger page...
```
{
    "dag_name": "anomalies_manual_job",
    "env": "qa",
    "config": {
        "__var": {
            "categories": [],
            "end": "2020-01-01",
            "start": "2021-01-01"
        },
        "__type": "dict"
    }
}
```
What I expect instead is this...
```
{
    "dag_name": "anomalies_manual_job",
    "env": "qa",
    "config": {
        "categories": [],
        "end": "2020-01-01",
        "start": "2021-01-01"
    }
}
```

**Related Issues**

I've tried to search for it but nobody said anything about it.

**Comment by VLADPOLUNIN** [comment]
Спасибо

**Comment by VLADPOLUNIN** [comment]
> Thanks for opening your first issue here! Be sure to follow the issue template!
> 
Hi

**Comment by potiuk** [comment]
Which version of Airlfow? Sounds like quite improbable that others have not seen it.

**Comment by potiuk** [comment]
Ah. yeah. I confirmed it's the case in main as well. Would you be willing to provide a PR fixing it?

**Comment by saimon46** [comment]
The version we are using is the latest 2.1.2. Unfortunately I don't have a lot of knowledge of the Airflow UI, about standards and best practise and I don't even know where is the best place where we can apply the fix. On the UI or backend? If you guide me on it I can put an effort and create a PR.

**Comment by VLADPOLUNIN** [comment]
👋😊

**Comment by uranusjr** [comment]
Those `__type` and `__val` keys are added by Airflow’s DAG serialisation logic, and the UI shouldn’t see them in the first place. I’m suspecting this is a bug in (de)serialisation, and if that’s correct this would be very deep down in the stack.

**Comment by potiuk** [comment]
> Those `__type` and `__val` keys are added by Airflow’s DAG serialisation logic, and the UI shouldn’t see them in the first place. I’m suspecting this is a bug in (de)serialisation, and if that’s correct this would be very deep down in the stack (in other words may not be as easy to fix as it appears to).

Yep. we neee some black-woodo magic of one of our serialization wizards ;)

**Comment by uranusjr** [comment]
I believe #17100 actually fixed this, although not sure if it’s intentional or accidental. That PR should be a part of 2.2 (including the currently available beta), so I’ll close this for now; feel free to reopen if this is still an issue in 2.2.

This is how the Trigger DAG view renders for me in `main`:

![image](https://user-images.githubusercontent.com/605277/133598810-f766edf5-e87a-48c3-a328-7647a029c4f3.png)
