### ISSUE TITLE
Helm Chart Doc Links Broken

### ISSUE THREAD

**Issue by GrayAlex49** [apache/airflow#17583]
In the helm chart documentation any links that refer to the main airflow documentation are broken. They are pointing to /docs/apache-airflow/latest/... which doesn't exist and looks like it should be pointing to /docs/apache-airflow/stable/...

I couldn't find where the root was defined in the docs to submit a PR. 

This occurs at least with the 'See Managing Variables for more.' link on the [variables page](https://airflow.apache.org/docs/helm-chart/stable/adding-connections-and-variables.html#variables) and the 'DAG Serialization' link on the [Manage Dag Files](https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#mounting-dags-using-git-sync-sidecar-without-persistence) page.

**Comment by kaxil** [comment]
https://github.com/apache/airflow/commit/3650448301d3b2a31a4996e035f1b325148c8639 should fix it too I think
