### ISSUE TITLE
New Tasks to an existing DAG do not get scheduled if they have depends_on_past = True

### ISSUE THREAD

**Issue by joshk-kang** [apache/airflow#17585]
**Apache Airflow version**: 2.1.2

**Apache Airflow Provider versions** (please include all providers that are relevant to your bug): None are relevant

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: 

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

When adding new tasks to an existing dag with `depends_on_past = True`, it will never get scheduled. 

**What you expected to happen**:
The newly added tasks should be able to run even with `depends_on_past=True`

The reason is that the logic to determine if it is the first task depends on the dag not the task itself https://github.com/apache/airflow/blob/main/airflow/ti_deps/deps/prev_dagrun_dep.py#L58-L65. The code here should be updated so that the first TaskInstance should be allowed to run even if there are previous DagRuns related to that task.

**How to reproduce it**:
Create a DAG with some tasks and let it have a run. Add another task with `depends_on_past=True` to the existing DAG, and it will never be scheduled because of the following reason `depends_on_past is true for this task's DAG, but the previous task instance has not run yet.`

**Anything else we need to know**: NA

**Comment by eladkal** [comment]
> Add another task with depends_on_past=True to the existing DAG

I think the issue here is that you assume that when you add a new task Airflow knows that it starts from the date you added it thus you expect depends_on_past=True to work but this is not the case. You must provide a `start_date` to this new task then it will work as expected.

```
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from datetime import datetime

default_args = {
    'owner': 'Elad',
    'start_date': datetime(2021, 8, 19),
}

with DAG('my_dag2', default_args=default_args, schedule_interval='*/5 * * * *') as dag:
    a = DummyOperator(task_id="1st")
    b = DummyOperator(task_id="2nd", wait_for_downstream=True)
    a >> b

with DAG('my_dag3', default_args=default_args, schedule_interval='*/5 * * * *') as dag:
    a = DummyOperator(task_id="1st")
    b = DummyOperator(task_id="2nd", wait_for_downstream=True, start_date=datetime(2021, 8, 19, 15, 15))
    a >> b
```

as you can see `my_dag3` works fine yet `my_dag2` is stuck:

![Screen Shot 2021-08-19 at 18 29 18](https://user-images.githubusercontent.com/45845474/130097259-52b79d35-0186-446e-a668-aa12f145c642.png)

![Screen Shot 2021-08-19 at 18 29 11](https://user-images.githubusercontent.com/45845474/130097294-7996b42f-2b24-4db3-abcc-486f15e86f51.png)

**Comment by joshk-kang** [comment]
Thanks @eladkal, I am currently using `start_date=days_ago(1)`, for a DAG that runs every 30 minutes, would you suggest using `start_date=days_ago(0)` instead?

**Comment by eladkal** [comment]
> Thanks @eladkal, I am currently using `start_date=days_ago(1)`, for a DAG that runs every 30 minutes, would you suggest using `start_date=days_ago(0)` instead?

No, I'm suggesting not to use dynamic values in `start_date`.

**Comment by skarangi-personal** [comment]
https://github.com/apache/airflow/issues/8989
