### ISSUE TITLE
Airflow Summit 2021 banner is still present on docs site

### ISSUE THREAD

**Issue by thmzlt** [apache/airflow#17607]
**Apache Airflow version**: 2.1.2

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Banner for Airflow Summit 2021 (which has passed) still shows up on docs site using some of the view space.

**What you expected to happen**: 

Banner does not show up.

**How to reproduce it**: 

Go to https://airflow.apache.org/docs/apache-airflow/stable/index.html and look at the top section of the page

**Comment by thmzlt** [comment]
@bbovenzi

**Comment by kaxil** [comment]
https://github.com/apache/airflow-site/pull/466 should fix it
