### ISSUE TITLE
JSON client does not provide an API for getting a list of Dag Runs

### ISSUE THREAD

**Issue by sw1010** [apache/airflow#17606]
**Description**

The JSON client provides API for many endpoints, but some of them are still missing, e.g. `GET /api/experimental/dags/<DAG_ID>/dag_runs`.

**Use case / motivation**

I would like to obtain all the run ids for a given DAG id. It looks like the missing API is the way to do so.

**Are you willing to submit a PR?**

Sure!

**Comment by uranusjr** [comment]
I don’t think we are going to accept contributions to `/api/experimental` (Deprecated API). Would it be possible for you to switch to `/api/v1` (Stable API)? If not, why?

**Comment by sw1010** [comment]
> I don’t think we are going to accept contributions to `/api/experimental` (Deprecated API). Would it be possible for you to switch to `/api/v1` (Stable API)? If not, why?

Many thanks for your reply. I see your point of view. I am working on a project that already uses the deprecated API and it would take us some time to switch to the new one. I could have made the corresponding changes inside my project and left them unpublished, but many other users may be in a similar situation and would like to reuse that functionality. Thus in my opinion it would be good to accept this pull request.

**Comment by potiuk** [comment]
> Many thanks for your reply. I see your point of view. I am working on a project that already uses the deprecated API and it would take us some time to switch to the new one. I could have made the corresponding changes inside my project and left them unpublished, but many other users may be in a similar situation and would like to reuse that functionality. Thus in my opinion it would be good to accept this pull request.

Not a good idea. We want to move people away from the experimental API as soon as possible (now). It will be removed in Airflow 3 completely (and irreversibly). Effectlively  - adding new functionality has the effect that people staying longer with the deprecated API, which is precisely what we want to avoid.

No more changes will be accepted to the experimental API.
