### ISSUE TITLE
Switch Alibaba tests to use Mocks

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#17617]
We should also take a look if there is a way to mock the calls rather than having to communicate with the reaal "Alibaba Cloud". This way our unit tests would be even more  stable. For AWS we are using `moto` library. Seems that Alibaba has built-in way to use Mock server as backend (?) https://www.alibabacloud.com/help/doc-detail/48978.htm

CC: @Gabriel39 -> would you like to pick on that task? We had a number of transient failures of the unit tests over the last week - cause the unit tests were actually reaching out to cn-hengzou Alibaba region's servers, which has a lot of stability issues. I am switching to us-east-1 in https://github.com/apache/airflow/pull/17616 but ideally we should not reach out to "real" services in unit tests (we are working on standardizing system tests that will do that and reach-out to real services but it should not be happening for unit tests).

**Comment by potiuk** [comment]
Can I assign you to that one @Gabriel39  ?

**Comment by Gabriel39** [comment]
OK, I'll take this task and will submit next PR in next few days. :)

**Comment by EricGao888** [comment]
> We should also take a look if there is a way to mock the calls rather than having to communicate with the reaal "Alibaba Cloud". This way our unit tests would be even more stable. For AWS we are using `moto` library. Seems that Alibaba has built-in way to use Mock server as backend (?) https://www.alibabacloud.com/help/doc-detail/48978.htm
> 
> CC: @Gabriel39 -> would you like to pick on that task? We had a number of transient failures of the unit tests over the last week - cause the unit tests were actually reaching out to cn-hengzou Alibaba region's servers, which has a lot of stability issues. I am switching to us-east-1 in #17616 but ideally we should not reach out to "real" services in unit tests (we are working on standardizing system tests that will do that and reach-out to real services but it should not be happening for unit tests).

Maybe we could just simply @mock.patch this get_connection() function in unit tests and there will be no need to connect to a real oss. I'd like to work on this issue if currently there's no one working on this. Please assign it to me, thx : )
![image](https://user-images.githubusercontent.com/34905992/155687847-9a506f7d-fa55-485d-a92a-683647c204ee.png)

**Comment by potiuk** [comment]
Feel Free!

**Comment by EricGao888** [comment]
> Feel Free!

@potiuk Hello, I've switched test cases in oss hook to use Mocks in [this PR](https://github.com/apache/airflow/pull/21992). If this works, I will fix unit tests in [oss_task_handler](https://github.com/apache/airflow/pull/21785), oss operator and oss sensor in  future PRs and commits. THX : )

**Comment by potiuk** [comment]
Merged it . This looks cool. Thanks! Please proceed with other tests :)

**Comment by EricGao888** [comment]
> Merged it . This looks cool. Thanks! Please proceed with other tests :)

All unit tests in alibaba provider have been fixed now : )  @potiuk
