### ISSUE TITLE
Expose celery config option 'result_expires' to airflow.cfg

### ISSUE THREAD

**Issue by zhangyi-hu** [apache/airflow#17623]
**Description**

Currently, Airflow celery executor has this config in its default value, one day. As a user, I hope I can set this value by myself through Airflow easily.

**Use case / motivation**

When you spot a silent mistake, where the task is successful but the results are wrong, you find the bug in your ETL workflow and fixed the bug. However, you cannot easily rerun because the celery result backend has the results cached for one day by default. You can ask airflow to rerun that task for sure, however, your celery worker will immediately return the cached results without actually doing anything. 

Instead of waiting for a day, you end up manually truncate the celery_metatask table. However, this hack can be avoided if we set that celery config as one hour instead of one day. 

**Are you willing to submit a PR?**

Unfortunately, I don't have time for this recently. 

**Related Issues**

I also believe when forcing rerun a dag, with celery executor, we should remove the celery task run history through the celery api.

**Comment by potiuk** [comment]
You can set it by `CELERY_RESULT_EXPIRES` environment variable. There is no point in adding it to the configuration of airflow.

**Comment by zhangyi-hu** [comment]
I verified that, by setting the environmental variable `CELERY_RESULT_EXPIRES `, this problem can be solved. 
However, the root of this problem is, that whether a task should be rerun is not fully controlled by airflow, unless the user sets this env var as a small number.

To my understanding, the status of a task should be solely managed by airflow. It seems to me that, airflow should always set this celery config as a small value to make celery memoryless, instead of letting the user worry about it.  Does this worth a separate ticket?

**Comment by potiuk** [comment]
I believe you probably try to re-run the tasks in some ways that are not the way airflow is supposed to rerun the task.  Airflow has a `backfill` command to be able to re-run the tasks that you want to run "again" (which is exactly the case you descibed).

This is pretty basic feature of Airflow, and I would be extremely surprised if in this case you get the result from cache of celery. I believe when you backfill the tasks via Airflow mechanisms, you will NOT get it from the cache of celery as this will be a different task run. 

I have a suspicion that you are somehow trying to manually rerun the tasks rather than via backfill. Could you explain how you re-run the tasks in order to get into the the problem?

**Comment by zhangyi-hu** [comment]
I backfilled for a certain day, and check the result. I found there was a mistake and updated the code the dag run will call. I backfilled again with --reset-dagruns option.  I guess backfill task with identical input arguments will produce identical celery job UUID?

**Comment by potiuk** [comment]
why `--reset-dagruns` ?

**Comment by zhangyi-hu** [comment]
Because the mistake was silent, the task finished successfully (from airflow's perspective) with the wrong logic and unintended result. I spotted the mistake by looking at the final result. After updating the code with the correct logic, I need to force Airflow to backfill again with the corrected code. With this option, Airflow will ignore the backfill request. 

I believe the root of the issue is that the option `--reset-dagruns` is not resting dagruns forceful enough, giving away the right to decide on whether a task should rerun to the down-stream broker: celery.

**Comment by potiuk** [comment]
So this is a "development" setup, something you need to set on  your "development" instance to try things out. This is clearly not something that would be happening in production, and clearly not something that you would like to enable for "all" runs.

I do not see this as a usual scenario for production, setting environment variable if you want to speed up re-backfilling and iterating while developing and testing, seems like pretty good solution.

**Comment by potiuk** [comment]
I am just wondering why backfill again (without --reset-dagrun) would be rejected? What was the error when you tried it? I believe what should happen is that backfill should be possible to repeat again.

**Comment by zhangyi-hu** [comment]
When I backfill again without --rest-dagrun, the jobs are not scheduled, as that dag run is already marked as success. So you believe if the dags are reloaded, the jobs should still be scheduled without --rest-dagrun? 

My code change is like "1+1" updated to "1+2".

**Comment by potiuk** [comment]
Can you give the exact command you run to run the backfill? Are you sure you are not running it with `--dry-run` or `--mark-success` flags? 

I am not sure why this might be happening - I think it should not. There is even this new feature to rerun all succeeded tasks automatically when you backfill a dag https://github.com/apache/airflow/pull/16475/files so I am pretty sure Airflow should be ablee to rerun sucdeeded tasks without `--reset-dagrun`. 

But maybe there is a scenario that I am not aware of ?

Just to summarize:

a) You run a backfill and the task succeeds (without `--reset-dagruns`).
b) You change the code and re-run backfill again for that task and It does not run but is marked as success immediately (?)

Did I get it correctly?

**Comment by zhangyi-hu** [comment]
Yes, a) and b) is what I believe happened. 
`--rerun-succeeded-tasks` is what I actually wanted to use. 

Are you saying that, Airflow 2.1.2 will keep a record of the checksums of all the imported python files, and decide if a dag in success state need to rerun in a backfill?
