### ISSUE TITLE
Invalid step_id argument in EmrStepSensor

### ISSUE THREAD

**Issue by rsotogar** [apache/airflow#17636]
Hi!

I am getting this error in the EmrStepSensor:

`botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the DescribeStep operation: Step id '{ task_instance.xcom_pull(task_ids='users_pipeline', key='return_value')[0] }' is not valid`.

Here's the code:

       `pipelines = ["events", "users", "eventsstaged", "activities", "feeds", "attendances", "friendships", "media", "downtoclown", "agents"]

        for pipeline in pipelines:

        watcher_operator = EmrStepSensor(task_id=f"{pipeline}_sensor",
                                         job_flow_id="{{ task_instance.xcom_pull(task_ids='start_emr_cluster', key='return_value')}}",
                                         step_id= f"{{ task_instance.xcom_pull(task_ids='{pipeline}_pipeline', key='return_value')[0] }}",
                                         target_states=["COMPLETED"])

        watcher_operators.append(watcher_operator)`

I am using Spark 3.1.1 running on EMR 6.3.0 and Airflow is deployed on EC2 using Docker. When I use the XCOM method to extract the job flow id seems fine, it only gives me problems when extracting the step id. Any help would be appreciated.

Thanks!

**Comment by eladkal** [comment]
I think it may be just a wrong usage of Jinja with f string format.

**Comment by uranusjr** [comment]
In an f-string, `{{` becomes `{`, and `}}` becomes `}`. So to get a valid Jinja template you need four open and four closing braces.

**Comment by eladkal** [comment]
I'm closing as this isn't a bug but more of a support question.
If further assistance is needed please use StackOverflow or troubleshooting channel in slack.
