### ISSUE TITLE
Airflow API (Stable) (1.0.0) Update a DAG endpoint documentation shows you can update is_active, but the api does not accept it

### ISSUE THREAD

**Issue by jmorgannht** [apache/airflow#17639]
**Apache Airflow version**:

v2.1.1+astro.2

**OS**:

Ubuntu v18.04

**Apache Airflow Provider versions**:

**Deployment**:

VM

Ansible

**What happened**:

PATCH call to api/v1/dags/{dagID} gives the following response when is_active is included in the update mask and/or body: 
{
    "detail": "Only `is_paused` field can be updated through the REST API",
    "status": 400,
    "title": "Bad Request",
    "type": "http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html#section/Errors/BadRequest"
}

The API spec clearly indicates is_active is a modifiable field: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/patch_dag

**What you expected to happen**:

Expected the is_active field to be updated in the DAG.  Either fix the endpoint or fix the documentation.

**How to reproduce it**:

Send PATCH call to api/v1/dags/{dagID} with "is_active": true/false in the body

**Anything else we need to know**:

Occurs every time.  

**Are you willing to submit a PR?**

No

**Comment by mik-laj** [comment]
You're right. We should add readOnly=True property to `is_active` field. It should look similar to `is_subdag` field. 
https://github.com/apache/airflow/blob/2935be19901467c645bce9d134e28335f2aee7d8/airflow/api_connexion/openapi/v1.yaml#L1871-L1882
