### ISSUE TITLE
Import Errors Flapping

### ISSUE THREAD

**Issue by frenchwr** [apache/airflow#17641]
**Apache Airflow version**: 2.1.2

**OS**: Amazon Linux release 2 (Karoo)

**Apache Airflow Provider versions**:

```
apache-airflow-providers-amazon==2.0.0
apache-airflow-providers-apache-hdfs==2.0.0
apache-airflow-providers-apache-hive==2.0.0
apache-airflow-providers-celery==2.0.0
apache-airflow-providers-docker==2.0.0
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-google==4.0.0
apache-airflow-providers-hashicorp==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-microsoft-mssql==2.0.0
apache-airflow-providers-odbc==2.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-sftp==2.0.0
apache-airflow-providers-slack==4.0.0
apache-airflow-providers-sqlite==2.0.0
apache-airflow-providers-ssh==2.0.0
```

**Deployment**:

Running on single AWS EC2 instance (connected to an AWS EMR cluster) with [Supervisor](http://supervisord.org/running.html) used to manage airflow processes. We use CeleryWorker and postgresql for our backend db.

**What happened**: 

A handful of parsing errors are going in and out of the `import_error` table. I uncovered this while specifically trying to address a parsing error from botocore: `botocore.exceptions.ProfileNotFound: The config profile (nonprod) could not be found`. The stacktrace from this error was originally in both the `import_error` table and also appeared in the scheduler logs for the DAG producing this error. 

After addressing this error (Supervisor needed additional environment vars to be set so it knew where to find the AWS creds file), the error disappeared from the scheduler logs (both for the individual DAG logs and in the report generated by the DAG File Processor). However, the error flaps in and out of the `import_error` table. I notice that immediately after the DAG processing loop completes (we have it set to run every two minutes) the error disappears from the `import_error` table for about 5-15 seconds before returning again, and remaining there until the next DAG processing loop.  

**What you expected to happen**:

I expect the parsing error to disappear permanently from the `import_error` table. 

**How to reproduce it**:

I have not attempted to create a minimal reproducer. 

**Anything else we need to know**:

It's unclear to me whether this is a bug or there is something in our Supervisor config that needs to be further tweaked, so I'm reaching out to see if anyone has a hunch of what might be occurring (e.g. are the previous import errors perhaps getting cached some place and then re-read? or maybe the old errors are stored some place in the serialized version of the DAG?). I appreciate any help or tips!   

**Are you willing to submit a PR?**

Sure!

**Comment by potiuk** [comment]
It almost looks like you have two schedulers running at the same time - one with the properly set environment variable and the other without. Are you sure you do not have two schedulers running?

**Comment by frenchwr** [comment]
> It almost looks like you have two schedulers running at the same time - one with the properly set environment variable and the other without. Are you sure you do not have two schedulers running?

I had checked this before _on the same instance_ and was getting ready to post a reply when I realized we had left an old dev EC2 instance running. That instance was using the same backend postgres db and was generating the errors. Stopping the instance resolved the issue. 

Thanks for weighing in pointing me in the right direction!

**Comment by potiuk** [comment]
Glad it helped :).

> “How often have I said to you that when you have eliminated the impossible, whatever remains, however improbable, must be the truth?”

Sherlock Holmes Quote
