### ISSUE TITLE
Preset manual triggers or trigger documentation

### ISSUE THREAD

**Issue by Limess** [apache/airflow#17657]
**Description**

It'd be useful for some ad-hoc/manual workloads to be able to define structure for the JSON used in manual triggered. 

This could be either a JSON schema, example/presets trigger payloads, or both.

**Use case / motivation**

For some use cases we allow triggering jobs with different parameters manually, e.g. disabling some notifications, or triggering more debug logs, or a a different behaviour.

As the manual trigger UI is fairly basic, there's no way of hinting this to users (aside from documentation in the code/UI, however the DAG level documentation is not shown on the manual trigger page so this is of little help at the time of triggering).

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/pull/17100 Is it related?

**Comment by Limess** [comment]
Yes, thanks for pointing this out. I'll sub to that issue and close this.
