### ISSUE TITLE
Dags volume not getting mounted in webserver pod?

### ISSUE THREAD

**Issue by kn6405** [apache/airflow#17662]
When I deploy via the helm chart the dags volume gets mounted in worker pods, schedular, etc... but does not get mounted in the webserver pod. Noticed the yaml is coded differently than for workers or the schedular (vs. others) and references version numbers older than 2.0.0. So running 2.1.2 the dag never gets mounted. 

gitSync.enabled is false for my deployment
dags.persistence.enabled is true for my deployment.

I download a local copy of the chart and changed from < to > and the dag folder gets mounted. I noticed there are also version checks 4 other places in the webserver deployment yaml file.

https://github.com/apache/airflow/blob/c22ed08ec4d8a9def1f09e74d51eafee83f87e8c/chart/templates/webserver/webserver-deployment.yaml#L147

**Comment by potiuk** [comment]
This is correct behaviour. Dags no longer need to be mounted in Webserver in Airflow 2. Webserver reads everything it needs from Serialized DAGs table and will never read DAGs from the files. This is absolutely expected and correct.

**Comment by kn6405** [comment]
> This is correct behaviour. Dags no longer need to be mounted in Webserver in Airflow 2. Webserver reads everything it needs from Serialized DAGs table and will never read DAGs from the files. This is absolutely expected and correct.

With older versions python errors within dags would be displayed on the UI and I believe where checked against python modules installed within the webserver container. How are these dependencies now checked? What container(s) does it look to have all the proper dependencies? 

On my old install 1.x the dags had requirement.txt that was mounted and it installed them at startup in most of the containers. 

Just want to make sure I understand the new logic in the 2.x version of airflow. Thanks!

**Comment by potiuk** [comment]
This is also done through DB - there is a DB "import errors"  that is populated by scheduler (and I believe it's always been like that)

**Comment by potiuk** [comment]
This has been also possible to not mount dags in few last versions of airflow if you had serialization turned on  BTW. Simply in Airlfow 2 Dag Serialization is the only way.

**Comment by potiuk** [comment]
See this page - it explains everything https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html
