### ISSUE TITLE
Documentation "how to sync your fork" is wrong, should be updated.

### ISSUE THREAD

**Issue by artik00** [apache/airflow#17665]
**Description**
From documentation , "CONTRIBUTING.rst" : 
 _There is also an easy way using ``Force sync main from apache/airflow`` workflow. You can go to "Actions" in your repository and choose the workflow and manually trigger the workflow using "Run workflow" command._
This doesn't work in the current GitHub UI, there is no such option.

**Use case / motivation**
Should be changed to reflect current github options, selecting ""Fetch upstream" -> "Fetch and merge X upstream commits from apache:main" 

**Are you willing to submit a PR?**
I will need help with wording

**Related Issues**
No.

**Comment by potiuk** [comment]
Happy if you submit PR. I think when you submit PR there will be some people who will help you with wording! Shall I assign you the PR?

**Comment by potiuk** [comment]
BTW. The reason is because the "fetch upstream" was added couple of months ago and we removed the old worklow (but not the docs).
