### ISSUE TITLE
Airflow not running as root when deployed to k8s via helm

### ISSUE THREAD

**Issue by yevsh** [apache/airflow#17679]
**Apache Airflow version**:  v2.1.2

**Deployment**: Helm Chart + k8s

**What happened**:

helm install with values:
uid=0
gid=0

Airflow pods must run as root.

error:

from container's bash: 

root@airflow-xxx-scheduler-7f49549459-w9s67:/opt/airflow# airflow

```
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
ModuleNotFoundError: No module named 'airflow'
```

**What you expected to happen**:
should run as root

using airflow's helm only

in pod's describe I see:

      securityContext:
        fsGroup: 0
        runAsUser: 0

**Comment by potiuk** [comment]
You have not written which Helm Chart you used. The official Helm Chart of Apache Airflow Community https://airflow.apache.org/docs/helm-chart/stable/index.html should work with root  user without a problem (though it's not recommended  in general). So I assume you use User-community chart though https://github.com/airflow-helm/charts (which I believe has that problem) and if you need help you should open your issue there.

**Comment by yevsh** [comment]
from readme

Full documentation for Helm Chart (latest **stable** release) lives [on the website](https://airflow.apache.org/docs/helm-chart/).

**Comment by potiuk** [comment]
Before I reopen it, I need to know what error do you have when you configure user as root and what kind of modifications you've made. 

I think you could have jumped to conclusion that it does not work. If you enter the container via "/bin/bash"  you will indeed get this error. But you should only enter the bash image via Airflow's image /entrypoint not via `/bin/bash`. This is the only way that can make it openshift-compatible and allow to run airflow as arbitrary user. You can see more what the entrypoint is doing in https://airflow.apache.org/docs/docker-stack/entrypoint.html

`docker run -it <airflow_image> bash` as parameter will allow you to enter bash and utilising the entrypoint in the way that root user works (and all containers in the Helm Chart should use it).

**Comment by potiuk** [comment]
This is an example I just tried:

```
[jarek@penguini:~] $ docker run --user "0:0" -it apache/airflow:2.1.2-python3.6 bash -c "airflow version" 
The container is run as root user. For security, consider using a regular user account.
2.1.2
```

**Comment by yevsh** [comment]
Fair enough,  
First, when running with airflow user, I am able to run airflow command within hte contaner's bash.

Now, when I use root user

I am not able to do so and :

airflow-xxx-scheduler pod is in a restart loop

 kubectl describe pod  airflow-xxx-scheduler-6fc986d95c-44246   

under events:

```
Warning  Unhealthy  4m3s (x110 over 58m)  kubelet            Liveness probe failed: Traceback (most recent call last):
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'airflow'
```

**Comment by potiuk** [comment]
Can you please install airflow from the scratch (delete the previous deployment you have), with the the configuration you want and provide the exact steps you do and exact modifications you've made in the values.yaml  to get there? I am afraid that if you just change the user after initially running it, it might not work (but also it might be that there is an error in the helm chart, so I want to make sure that we can reproduce what you exactly did to see if it is a real issue or not).

**Comment by potiuk** [comment]
I think I know what it is - looked at the liveness probe and it indeed seems to run exec directly - this looks like a bug in the chart.

**Comment by yevsh** [comment]
oh..  do you want to see values yaml?

**Comment by potiuk** [comment]
Yes I think only that.

**Comment by potiuk** [comment]
Hmm. Actually not really. It should work fine IMHO. Yes. Please provide the command and try to install from the scratch with it. I think the liveness probe should work IMHO if correctly configured (unless you do some funny things with extra mounting volumes as HOME directory of the user - in which case it might be the problem you describe.

**Comment by yevsh** [comment]
```
helm install airflow-xxx airflow \
   --set webserver.service.type=NodePort \
   --set executor="LocalExecutor" \
   --set workers.persistence.size=1Gi \
   --set logs.persistence.size=1Gi \
   --set workers.persistence.enabled=false \
   --set postgresql.persistence.enabled=false \
   --set dags.persistence.enabled=true \
   --set logs.persistence.enabled=true \
   --set dags.persistence.accessMode=ReadWriteMany \
   --set dags.persistence.storageClassName=airflow-dags-xxx \
   --set logs.persistence.storageClassName=airflow-logs-xxx \
   --set images.airflow.repository=${EXTERNAL_IMAGES}/airflow \
   --set postgresql.image.registry=${EXTERNAL_IMAGES} \
   --set redis.enabled=false \
   --set uid=0 \
   --set gid=0 \
   --namespace xxx
```

from values.yaml, 

#User and group of airflow user
uid: 0
gid: 0


if you need anything specific from values please tell.

**Comment by yevsh** [comment]
the only pvc are for dags and logs.

**Comment by jedcunningham** [comment]
This reproduces it:

```
helm upgrade --install --set uid=0 test airflow/airflow
```

**Comment by yevsh** [comment]
thanks, so I can take the latest helms?

**Comment by potiuk** [comment]
You could try Fri. The main branch of airflow. We are following a release process where we vote and put version etc. But you can install the 'main' version too (with some potential instabilities but i think it is pretty safe) just checkout main repo and  install it from 'chart'

**Comment by yevsh** [comment]
now pod is not restarting.

from within the container (bash), running command 'airflow' as root user still yields 
No module named 'airflow'

is that normal?

**Comment by potiuk** [comment]
> If you enter the container via "/bin/bash" you will indeed get this error. But you should only enter the bash image via Airflow's image /entrypoint not via /bin/bash. This is the only way that can make it openshift-compatible and allow to run airflow as arbitrary user (including root). You can see more what the entrypoint is doing in https://airflow.apache.org/docs/docker-stack/entrypoint.html

**Comment by potiuk** [comment]
Are you sure you get the latest merged `main` code?

**Comment by potiuk** [comment]
BTW. You can test if the root user works by running `/entrypoint bash` when you `exec` into the container.

**Comment by yevsh** [comment]
I just added 
- /entrypoint
to scheduler-deployment.yaml
and pod is not restarting .

/entrypoint bash when you exec into the container. also works

**Comment by potiuk** [comment]
What error do you see? "Pod not restarting" is really vague description that is difficult to reason about :)

**Comment by potiuk** [comment]
Side comment. I really, really love the non-empathetic "it does not work" description of the bug when you want to get some help. It's  never helpful and a bit frustrating.

**Comment by yevsh** [comment]
no erros

**Comment by potiuk** [comment]
aaaa :)

**Comment by potiuk** [comment]
Cool ! Sorry, misunderstood it ❤️

**Comment by potiuk** [comment]
Glad it helped !

**Comment by potiuk** [comment]
Thanks @jedcunningham !
