### ISSUE TITLE
Duplicated general notifications in Airflow UI above DAGs list

### ISSUE THREAD

**Issue by mnojek** [apache/airflow#17727]
**Apache Airflow version**:
2.2.0.dev0 (possible older versions too)

**OS**:
Linux Debian 11

(BTW Here we have a typo in comment inside bug report template in `.github/ISSUE_TEMPLATE/bug_report.md`: `cat /etc/oss-release` <- double 's'.)

**Apache Airflow Provider versions**: -

**Deployment**:
Docker-compose 1.25.0

**What happened**:
The issue is related to Airflow UI and it shows duplicated notifications when removing all the tags from the input after filtering DAGs.

**What you expected to happen**:
The notifications should not be duplicated.

**How to reproduce it**:
In the main view, above the list of the DAGs (just below the top bar menu), there is a place where notifications appear. Suppose that there are 2 notifications (no matter which). Now try to search DAGs by tag using 'Filter DAGs by tag' input and use a valid tag. After the filtering is done, clear the input either by clicking on 'x' next to the tag or on the 'x' near the right side of the input. Notice that the notifications are duplicated and now you have 4 instead of 2 (each one is displayed twice). The input id is `s2id_autogen1`.
This bug happens only if all the tags are removed from the filtering input. If you remove the tag while there is still another one in the input, the bug will not appear. Also, it is not present while searching DAGs by name using the input 'Search DAGs'.

After search, before removing tags from input:
![notif](https://user-images.githubusercontent.com/7412964/130072185-ca2b3bd4-023d-4574-9d28-71061bf55db6.png)
Duplicated notifications after removing tag from input:
![notif_dup](https://user-images.githubusercontent.com/7412964/130072195-1d1e0eec-c10a-42d8-b75c-1904e05d44fc.png)

**Are you willing to submit a PR?**
I can try.

**Comment by potiuk** [comment]
Funny bug :) 

> (BTW Here we have a typo in comment inside bug report template in .github/ISSUE_TEMPLATE/bug_report.md: cat /etc/oss-release <- double 's'.)

Maybe PR fixing it @mnojek ?

**Comment by mnojek** [comment]
@potiuk You mean this small issue in bug report template? I can do it tomorrow with other small typos across the documentation that I found while reading it.

**Comment by mnojek** [comment]
@potiuk I submitted a PR for the typos #17809. Nothing very important there, just some grammar/typo fixes and also the `os-release` command in the bug_report template.

**Comment by bbovenzi** [comment]
This is happening when we redirect the home page to itself on this [line](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L581).

Is there a better way we can clean up the filter tags cookie?

**Comment by bbovenzi** [comment]
This also happens when the flask cookie tries to add tags that exist in the cookie but not in the url. I think we should just get rid of that cookie entirely.

**Comment by bbovenzi** [comment]
Instead of moving the cookies around, we probably need to use a regular alert instead of flash and render those after the redirects.
