### ISSUE TITLE
airflow.dates.days_ago doesn't respect configured timezone

### ISSUE THREAD

**Issue by Xilorole** [apache/airflow#17720]
**Apache Airflow version**: 2.1.1

**OS**:Chromium OS 11.0 ( on google cloud composer)

**Apache Airflow Provider versions**: 

**Deployment**: None

**What happened**:

The parameter `schedule_interval` does not respect the `default_timezone` set by airflow.cfg when using `airflow.utils.dates.days_ago` as `start_date`.

I am setting the default timezone to Asia/Tokyo. When I use the start_date, the schedule_interval respects the default timezone, but by using the days_ago, the schedule are set on UTC. 

**What you expected to happen**:

The scheduled runtime is to be set with respect to the default timezone.

**How to reproduce it**:

add the below to airflow.cfg
```
default_timezone = Asia/Tokyo
```
run
```python
from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.operators import dummy_operator

with DAG(
  "test",
  schedule_interval = "0 10 * * *",
  start_date = days_ago(1)
) as dag:
  t_start = dummy_operator.DummyOperator(task_id="start")
  t_end = dummy_operator.DummyOperator(task_id="end")
  t_start >> t_end
```

**Anything else we need to know**:

After a couple of inspections, I found that using `utcnow()` in the `days_ago` function, which drop timezone info was the reason why it didn't respect the timezone. 

https://github.com/apache/airflow/blob/4da4c186ecdcdae308fe8b4a7994c21faf42bc96/airflow/utils/dates.py#L255-L261

Defining a function that respect the timezone fixed this issue.

```python
def days_ago(n, hour=0, minute=0, second=0, microsecond=0):
  import pendulum
  import os
  import datetime as dt
  from datetime import timedelta
  tz = pendulum.tz.timezone(os.environ.get("AIRFLOW__AIRFLOW__CORE__DEFAULT_TIMEZONE"))
  today = dt.datetime.now(tz=tz).replace(hour=hour, minute=minute, second=second, microsecond=microsecond)
  return today - timedelta(days=n)
```

The dag using airflow-defined `days_ago` is the upper and the user-defined `days_ago` is the below which is timezone-aware.
<img width="799" alt="スクリーンショット 2021-08-20 12 17 12" src="https://user-images.githubusercontent.com/29719311/130173758-e0e9f560-7a0f-41e9-a110-a2143b7b1e6f.png">

**Are you willing to submit a PR?**

If this is not what it was intended to happen, of course!

**Comment by eladkal** [comment]
If you have a fix you can always open PR :)

**Comment by Sonins** [comment]
I have also same issue. If you would like to open PR, I would like to suggest a little fix in your code.
The variable that includes user's local time zone already exists as `TIMEZONE` in [settings.py](https://github.com/apache/airflow/blob/main/airflow/settings.py).

```python
...
# settings.py line 46
TIMEZONE = pendulum.tz.timezone('UTC')
try:
    tz = conf.get("core", "default_timezone")
    if tz == "system":
        TIMEZONE = pendulum.tz.local_timezone()
    else:
        TIMEZONE = pendulum.tz.timezone(tz)
except Exception:
    pass
```

And in [timezone.py](https://github.com/apache/airflow/blob/main/airflow/utils/timezone.py), you can get `datetime` object that is set to local timezone.

```python
from airflow.settings import TIMEZONE
...

# timezone.py line 170
def datetime(*args, **kwargs):
    """
    Wrapper around datetime.datetime that adds settings.TIMEZONE if tzinfo not specified
    :return: datetime.datetime
    """
    if 'tzinfo' not in kwargs:
        kwargs['tzinfo'] = TIMEZONE

    return dt.datetime(*args, **kwargs)
```

So you can simply go like this.

```python
# dates.py
from airflow.utils import timezone
...

def days_ago(n, hour=0, minute=0, second=0, microsecond=0):
  today = timezone.datetime().now().replace(hour=hour, minute=minute, second=second, microsecond=microsecond)
  return today - timedelta(days=n)
```

**Comment by eladkal** [comment]
@Sonins would you like to PR a fix?

**Comment by Sonins** [comment]
> @Sonins would you like to PR a fix?

@eladkal I opened PR #20508.
