### ISSUE TITLE
Skip Scheduled Runs

### ISSUE THREAD

**Issue by sou-joshi** [apache/airflow#17752]
**Description**
Ability to skip scheduled Dag Runs. 

**Use case / motivation**
Let's say we have a Dag scheduled to run from 5th through 10th of every month. When it runs on 5th and is successful,  would like to skip all the following scheduled runs for the month and only trigger it next month.

**Comment by potiuk** [comment]
Sounds like a very, very specific request.. Since Airflow is developed by community, I think the only way to get it, is that you implement it. Would you be willing to make a  PR for it?

**Comment by sou-joshi** [comment]
@potiuk Approach to solve one off case right now is this - 
**Assuming**
- DAG scheduled to run from 5th - 10th of every month
- DAG run successful for 6th dated run

**Solution**
- If DAG successful, get the next scheduled Dag Runs for the month
- delete the next dag run scheduled for the month from the metadata db

**Questions**
- How safe is it to touch the meta db for deletion?
- Any other impacts?

**Comment by ManiBharataraju** [comment]
@sou-joshi - Can't you add a BranchPythonOperator as the first task and in the function, query the DagRun table and check if the dag has already run and based on the result skip the subsequent tasks? 
Just thinking what parameter would you pass to skip the next runs to achieve this.

**Comment by uranusjr** [comment]
Allowing a DAG to control when the next run should happen feels like the wrong abstraction to me. A BranchPythonOperator seems like a good way to go. With AIP-39 implemented, you may also use a custom timetable to query previous DAG run results to determine when the next DAG run should happen. The difference is to not put controlling logic on the *previous* run (which is wrong), but make the *next* run—either when the run happens as in BranchPythonOperator, or when the scheduler decides when the run should happen as in AIP-39 timetable—decide what to do.

**Comment by uranusjr** [comment]
Another thing—it is very unlikely for Airflow core to implement this behaviour, since backfilling is a thing and those runs may happen concurrently or even out of order, so it’s conceptually difficult not clear how the scheduler can schedule runs based on the previous run’s result in a general way. We can skip a run from happening after it’s created, but can’t stop it from being created, nor dynamically decide when the run should happen. So whatever you choose to do, it would probably need to happen in your own customisation.

**Comment by potiuk** [comment]
Very much agree with @uranusjr . Skipping processing based on success of previous runs is not compatible with airflow paradigm and I cannot see how.it can be part of scheduler. Some kind of 'data based' behaviour is possible - for example you might skip a run If the data is already prepared - but as @uranusjr  mentioned this should be done as Dag logic not as scheduler decision
