### ISSUE TITLE
Investigating expensive query when a dag has a large amount of tasks.

### ISSUE THREAD

**Issue by StewartThomson** [apache/airflow#17771]
**Apache Airflow version**:

v2.1.2

**OS**:

Docker on Amazon Linux 2

**Apache Airflow Provider versions**:

**Deployment**:

docker-compose 1.29.2

**What happened**:

We're noticing high cpu usage stemming from one query. The db backend we are using is Mysql 8.0. The DAG has 407 tasks in it.

The query is as follows:

```sql
SELECT 
task_instance.try_number AS task_instance_try_number,
 task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, 
 task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date,
 task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, 
 task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, 
 task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, 
 task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool,
 task_instance.pool_slots AS task_instance_pool_slots, task_instance.queue AS task_instance_queue,
 task_instance.priority_weight AS task_instance_priority_weight,
 task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, 
 task_instance.queued_by_job_id AS task_instance_queued_by_job_id, task_instance.pid AS task_instance_pid,
 task_instance.executor_config AS task_instance_executor_config,
 task_instance.external_executor_id AS task_instance_external_executor_id 
FROM task_instance, 
	(
    SELECT task_instance.task_id AS task_id,
    max(task_instance.execution_date) AS max_ti 
	FROM task_instance USE INDEX (PRIMARY) 
	WHERE task_instance.dag_id = 'sql_dump_partition_ten_minutes' 
    AND (task_instance.state = 'success' OR task_instance.state = 'skipped') 
    AND task_instance.task_id IN ({tasks.....})
    GROUP BY task_instance.task_id
    ) AS sq 
	WHERE task_instance.dag_id = 'sql_dump_partition_ten_minutes'
	 AND task_instance.task_id = sq.task_id 
     AND task_instance.execution_date = sq.max_ti;
```

The task ids have been removed. This takes about 2 seconds to run, with a dag that runs every 10 minutes. What is this query for? (I notice that removing the state check improves performance). 

Curious of any possible solutions. Would removing old task instances to reduce the size of the table help? Maybe I could add the task_instance's state to the primary key.

**What you expected to happen**:

This query shouldn't be bogging down the backend so much

**How to reproduce it**:

Create a dag with 407 tasks, run every 10 minutes

**Anything else we need to know**:

This happens consistently

**Are you willing to submit a PR?**

Not at the moment

**Comment by potiuk** [comment]
2 seconds, every 10 minutes. Do I get it right? Are we talking about optimising something tha takes 2/(10*60) = 0.3% of CPU potentially. 

My whole engineering background tells me that optimising things makes them complex and it really makes sense to optimise something when the result of the optimisation brings some real improvements.

So let me add additional question - WHY do you want to optimise this? What are the benefits you want to achieve? Does it actually change  anything for your setup? What are the problems you see with it and what are the measurable benefits you want to get ?

**Comment by StewartThomson** [comment]
Thanks for your quick response. It's mainly an issue in that it causes our database instance to spike to 100% every time the dag runs. Throw in any other dags and we end up in a situation where the CPU gets pinned at 100% and performance degrades. 

https://imgur.com/gnhQTXJ

Attached is a link of the RDS performance insight that shows this query as the main culprit. The motivation behind wanting to investigate this is that if it is resolved, we can reduce the hardware requirements. The expense of this query also gives me concerns about scalability in the future.

Thanks again for your response.

**Comment by uranusjr** [comment]
This is probably one of the issues I call "yeah it's nice but I'm not going to do it". I agree with @potiuk this is not very worthwhile from an engineering standpoint since there are too many more valuable things to do, but otoh this query taking 2 whole seconds also doesn't feel right to me at a quick glance, and it can likely be optimised. So I'd very much welcome a pull request rewriting the query, but don't expect anyone else putting effort on it.

**Comment by potiuk** [comment]
> The motivation behind wanting to investigate this is that if it is resolved, we can reduce the hardware requirements. The expense of this query also gives me concerns about scalability in the future.

As I see it this is wrong diagnosis. You can't optimise your hardware this way. Please correct me if I am wrong,  But If you reduce the hardware requirements now by 50%, the query will (at most) take 4 seconds. Which will cause longer, smaller spike, but that's about it. Jumping to conclusion that it might cause scalability issues is extremely premature, I'd love if you explain how this might be impacting scalability. It's very easy to say "this query takes most time" but you should analyse it and judge if it makes sense to optimise it and what impact it will have.

There is a very good quote `premature optimisation is the root of all evil` which I very much sympathise with and for any optimisation I do, I try at least to find out what am I optimising actually and how much can I gain.

I am not saying that it's not worth, but I am saying from the data/analysis/graphs you provided I see no reason why anyone should invest it optimising something that brings at most 0.03% improvement. This is very basic engineering rule - optimise something that you know makes sense to be optimised.

If you  you have some strongly founded, data-based justification that optimising this query is needed I am happy to take a look at it but as @uranusjr - if you feel that you might improve that query - feel free, we will judge is potential complexity (which is inherent with optimisation) is worth it. 

Shall I assign you the issue ?

**Comment by StewartThomson** [comment]
Maybe I wasn't clear in my intentions of this issue. I was moreso wondering if there was a newbie gotcha that I was encountering / curious about the source of this query.

I dug around the source code and found that this query is running for the SLA check, which is something that I don't really need at the moment, so I have removed my SLA's.

Thank you both for your time, I'll close this issue. If I find myself wanting to make use of this feature in my large dags, I'll re-open and make a PR about it with an optimization, if I can find one.

Thanks again!

**Comment by potiuk** [comment]
Well. This is the BEST optimisation if you can disable/remove something :D
