### ISSUE TITLE
Add Arango hook

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#17778]
**Description**

https://www.arangodb.com/ is a graph db much like Neo4j.
It has official python connector: https://github.com/ArangoDB-Community/python-arango

**Use case / motivation**

Using ArangoHook to interact with Arango.
Using ArangoOperator to run [simple queries](https://docs.python-arango.com/en/main/simple.html).
Possibly also ArangoAQLHook / ArangoAQLOperator to run [AQL queries](https://docs.python-arango.com/en/main/aql.html) - not sure if it require separate hook/operator.

**Comment by potiuk** [comment]
Would you be willing to add it ? I think if you have the need and use Rango, you might be the best person to add it .

**Comment by ashmeet13** [comment]
Hi, can I pick this up?

**Comment by mrbazzan** [comment]
@vijaya-lakshmi-venkatraman 
No, not at the moment. If I'm still unable to do something in the coming week, I'll drop it.

**Comment by pateash** [comment]
@eladkal as discussed over slack, I will pick this up.

**Comment by Megha-Sai-Sree-PINNAKA** [comment]
@pateash can I know if you are working on documentation of Arango Hook, else I am interested to take it up.

**Comment by pateash** [comment]
> @pateash can I know if you are working on documentation of Arango Hook, else I am interested to take it up.

I have added some as part of PR,
@eladkal Do we need any more?

**Comment by pateash** [comment]
> Hello @pateash I see you have documented the development work of Arango Hook. I would like to document the use cases of Arango Hook if it is ok.

Sure, go ahead

**Comment by Megha-Sai-Sree-PINNAKA** [comment]
Hello. I tried comparing the structure of MongoDB's docs folder with ArangoDB's, it looked almost similar. But then we are able to see MongoDB in the official documentation of apache airflow whereas ArangoDB is not coming up. Is there anything exclusively to be done inorder to see Arango in the documentation https://airflow.apache.org/docs/?

**Comment by pateash** [comment]
the docs are available here,
https://airflow.apache.org/docs/apache-airflow-providers-arangodb/1.0.0/

I am looking into, why they are not available on main page.

**Comment by pateash** [comment]
I am able to see **arangodb**, when i build docs locally

![image](https://user-images.githubusercontent.com/16856802/169348871-b67c97e3-45d7-41f5-9bc3-6b803a127464.png)

@potiuk @eladkal , Do we build all the docs or just the provider which is released?

**Comment by potiuk** [comment]
Because it has to be added manually - this is one of the few steps in process which is still manual and sometimes can be missed:

**Comment by potiuk** [comment]
Any improvement in the automation there are welcome: 

The step is here:

https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#prepare-documentation

> If you publish a new package, you must add it to [the docs index](https://github.com/apache/airflow-site/blob/master/landing-pages/site/content/en/docs/_index.md):

**Comment by potiuk** [comment]
Link is up on our website: https://airflow.apache.org/docs/

**Comment by pateash** [comment]
> Link is up on our website: https://airflow.apache.org/docs/

Thanks @potiuk
