### ISSUE TITLE
Webserver fail to start with virtualenv: No such file or directory: 'gunicorn': 'gunicorn'

### ISSUE THREAD

**Issue by UnightSun** [apache/airflow#17804]
**Apache Airflow version**: 2.1.2

**OS**: CentOS Linux release 8.2.2004 (Core)

**Apache Airflow Provider versions**: 
apache-airflow-providers-celery==2.0.0
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-mysql==2.1.0
apache-airflow-providers-redis==2.0.0
apache-airflow-providers-sftp==2.1.0
apache-airflow-providers-sqlite==2.0.0
apache-airflow-providers-ssh==2.1.0

**Deployment**: Virtualenv  3.7.5

**What happened**:
Got error when I try to start a webserver:
```bash
$ $VENV_PATH/bin/airflow webserver
...
=================================================================
Traceback (most recent call last):
  File "/VENV_PATH/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/VENV_PATH/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/VENV_PATH/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/VENV_PATH/lib/python3.7/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/VENV_PATH/lib/python3.7/site-packages/airflow/cli/commands/webserver_command.py", line 483, in webserver
    with subprocess.Popen(run_args, close_fds=True) as gunicorn_master_proc:
  File "/home/user/.pyenv/versions/3.7.5/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/user/.pyenv/versions/3.7.5/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gunicorn': 'gunicorn'
[user@xxxxx xxxxxxxxxx]$ /VENV_PATH/bin/python
Python 3.7.5 (default, Aug 20 2021, 17:16:24)
```

**What you expected to happen**:
Airflow start webserver success

**How to reproduce it**:
assume we already have `AIRFLOW_HOME`
1. create a venv: `virtualenv xxx`
2. `xxx/bin/pip install apache-airflow`
3. `xxx/bin/airflow webserver`

**Anything else we need to know**:
`cli/commands/webserver_command.py:394` use `gunicorn` as subprocess command, assume it's in PATH.
`airflow webserver` runs well after `export PATH=$PATH:$VENV_PATH/bin`.

**Are you willing to submit a PR?**
I'm not good at python so maybe it's not a good idea for me to submit a PR.

**Comment by potiuk** [comment]
I think this is a reasonable assumption to have  `virtualenv/bin` on the path when you installed airflow (or anything there). 

This happens when you source `activate` script as part of "activation" of the virtualenv and it is described in https://docs.python.org/3/library/venv.html :

> Once a virtual environment has been created, it can be “activated” using a script in the virtual environment’s binary directory. The invocation of the script is platform-specific (<venv> must be replaced by the path of the directory containing the virtual environment):

also there is an alternative method of "activation" of the virtualenv - which is precilsely about prepending the `bin` directory of the venv to your PATH::

> You don’t specifically need to activate an environment; activation just prepends the virtual environment’s binary directory to your path, so that “python” invokes the virtual environment’s Python interpreter and you can run installed scripts without having to use their full path. However, all scripts installed in a virtual environment should be runnable without activating it, and run with the virtual environment’s Python automatically.

I think what **might**  not work if you run airlfow command after installing it in venv but without `activating` it. But I think expecting venv to be activated and gunicorn to be on the path is reasonable. Unless some people will express different opnion (and propose a solution) I consider that as `won't fix`

**Comment by mik-laj** [comment]
I already working on fix.

**Comment by potiuk** [comment]
Cool!
