### ISSUE TITLE
Missing example for Salesforce DAG

### ISSUE THREAD

**Issue by jayantsande25** [apache/airflow#17815]
**Description**
airflow/providers/salesforce/example_dags/__init__.py
Missing example of Salesforce DAG ( rest api, bulk api)

**Use case / motivation**

An example DAG on how to query(select), Update, Delete salesforce object using Rest API and Bulk APIs
**Are you willing to submit a PR?**
May be later , after one basic example

**Related Issues**
None

None

**Comment by jayantsande25** [comment]
@xinbinhuang issue created for salesforce DAG.

**Comment by SCrocky** [comment]
I'm starting contributing.

Can I take this?

**Comment by uranusjr** [comment]
Go ahead.

**Comment by SCrocky** [comment]
Can someone explain why the salesforce provider operator and sensor both contain tableau provider empty files?

Also the salesforce hook folder also has an empty tableau hook file in there.

I think they should've been deleted in commit [Add Tableau Provider Separate from Salesforce Provider](https://github.com/apache/airflow/commit/45e72ca83049a7db526b1f0fbd94c75f5f92cc75#diff-013f494aaae3dee1fbddedd59a9e7cac444b425f8432426e2f0467dc8c42f22b).

Should I delete them in my commit ?
Do I only use Salesforce hooks in my DAG example? No Sensors or Operators?

**Comment by eladkal** [comment]
> Can someone explain why the `providers/salesforce` folders: operator and sensor, both contain `providers/tableau` empty files?

Tableau used to be in Salesforce provider. It was extracted to a seperated provider. To avoid breaking change we left the option to import tableau from Salesforce provider which will be removed eventually.

You can ignore the tableau folder in the salesforce provider. If you wish to add examples for tableau add them to the Tableau provider.

**Comment by SCrocky** [comment]
> Tableau used to be in Salesforce provider. It was extracted to a seperated provider. To avoid breaking change we left the option to import tableau from Salesforce provider which will be removed eventually.

Backwards compatibility. Got it.

**Comment by jayantsande25** [comment]
I guess no one is working on example DAGs for salesforce APIs yet.

**Comment by SCrocky** [comment]
Yes, my bad,  I'll upload a proposal this weekend.

Thanks for the reminder. :)

**Comment by mrbazzan** [comment]
@SCrocky Are you still working on this issue?

**Comment by eladkal** [comment]
@rsg17 The goal of examples is to show simple usage of the capabilities. It is not for suggesting workaround or how to complete missing functionality (Bulk is not yet supported https://github.com/apache/airflow/issues/16921 )

The easiest way to do it is simple go over the provider abilities and add example where missing. If you find the examples we have satisfactory we can close this issue

**Comment by jayantsande25** [comment]
Yes Rachana
You're understanding is correct.
In case you need more information please let me know, we can discuss

**Comment by rsg17** [comment]
Sounds good. Will look at examples for existing code. (Will exclude bulk API related examples)

**Comment by jayantsande25** [comment]
@rsg17 @eladkal @SCrocky 
Is anyone willing to working on this Incomplete piece ? It has to be a sample/demo code to integrate with Salesforce Rest and BULK APIs 2.0.
Much appreciated if anyone is willing to help here

**Comment by eladkal** [comment]
You are welcome to work on Salesforce docs but bulk is something that we currently don't support in Airflow so what kind of docs do you think we should have?
see https://github.com/apache/airflow/issues/16921

**Comment by alexbegg** [comment]
I just wanted to share my code example for initiating `SalesforceBulk` (Bulk API) from an existing `SalesfoceHook` (commented in the issue @eladkal referenced) in case someone is willing to include it in an Example DAG:
https://github.com/apache/airflow/issues/16921#issuecomment-964831154

**Comment by eladkal** [comment]
If we don't have SalesforceBulk hook and operators I don't think Airflow needs example for usage of Bulk API.

I'm closing this issue as to my understanding it focuses on bulk.
lets keep it in https://github.com/apache/airflow/issues/16921
