### ISSUE TITLE
Unable to install Airflow 2.1.3 with pipenv due to conflicting constraints on markupsafe dependency version

### ISSUE THREAD

**Issue by agrounds** [apache/airflow#17812]
**Apache Airflow version**:

2.1.3 (python version 3.8.11)

**OS**:

MacOS Big Sur 11.4

**Apache Airflow Provider versions**:

None

**Deployment**:

Local virtualenv created with pipenv

**What happened**:

Unable to install apache-airflow 2.1.3 using pipenv. Full error message:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches markupsafe<2.0,>=1.1.1,>=2.0 (from apache-airflow==2.1.3->-r /var/folders/1f/vgxps40576s4y3yp5g45l3qh0000gn/T/pipenvb6k6gz5rrequirements/pipenv-052vuxby-constraints.txt (line 2))
Tried: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0, 2.0.1
Skipped pre-versions: 2.0.0a1, 2.0.0rc1, 2.0.0rc2
There are incompatible versions in the resolved dependencies:
  markupsafe<2.0,>=1.1.1 (from apache-airflow==2.1.3->-r /var/folders/1f/vgxps40576s4y3yp5g45l3qh0000gn/T/pipenvb6k6gz5rrequirements/pipenv-052vuxby-constraints.txt (line 2))
  markupsafe>=2.0 (from jinja2==3.0.1->apache-airflow==2.1.3->-r /var/folders/1f/vgxps40576s4y3yp5g45l3qh0000gn/T/pipenvb6k6gz5rrequirements/pipenv-052vuxby-constraints.txt (line 2))
```

**What you expected to happen**:

Airflow to be installed in a virtualenvironment.

**How to reproduce it**:

1. Make sure [pipenv](https://pipenv.pypa.io/en/latest/) is installed
2. Save the following to a file called `Pipfile` somewhere you don't already have a `pipenv` project:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"apache-airflow" = "==2.1.3"

[dev-packages]

[requires]
python_version = "3.8"
```

3. Run `pipenv lock` or `pipenv install`

**Are you willing to submit a PR?**

Yes, if someone can show me how subdependencies of Airflow are managed.

**Comment by potiuk** [comment]
PIPenv should be used to install Airflow. It misses crucial features and until it supports constraints, you should use 'pip'' and constraints to install airflow. 

See https://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-tools where it is explicitly stated that pip-tools.shoild not be used (unless you make use of pip constraints).

**Comment by agrounds** [comment]
Thanks @potiuk. I had previously read through the installation tools section, but I wasn't familiar with poetry or pip-tools and didn't realize that the same advice applied to pipenv. Since it's such a popular tool, it would be nice to mention that it's not supported on that page.

**Comment by potiuk** [comment]
> Thanks @potiuk. I had previously read through the installation tools section, but I wasn't familiar with poetry or pip-tools and didn't realize that the same advice applied to pipenv. Since it's such a popular tool, it would be nice to mention that it's not supported on that page.

Absolutely? Could you please make a PR and add it? Airflow is community-driven and anyone can add their PRs - happy to review and approve it. It's supper easy - at the bottom of the page you will find "Suggest a change on this page" button - it will open PR for you. No dev environment needed or any preparation to make a doc-only change, it can be done straight from the GitHub UI, same as commenting here :).
