### ISSUE TITLE
"Runs" column being cut off by "Schedule" column in web UI

### ISSUE THREAD

**Issue by ghost** [apache/airflow#17810]
**Apache Airflow version**:

2.1.3

**OS**:

CentOS Linux 7

**Apache Airflow Provider versions**:

Standard provider package that comes with Airflow 2.1.3 via Docker container

**Deployment**:

docker-compose version 1.29.2, build 5becea4c

**What happened**:

Updated container from Airflow 2.1.2 --> 2.1.3 without an specific error message

**What you expected to happen**:

I did not expect an overlap of these two columns.

**How to reproduce it**:

Update Airflow image from 2.1.2 to 2.1.3 using Google Chrome Version 92.0.4515.159 (Official Build) (x86_64).

**Anything else we need to know**:

Tested in Safari Version 14.1.2 (16611.3.10.1.6) and the icons do not even load. The loading "dots" animate and do not load "Runs" and "Schedule" icons. No special plugins used and adblockers shut off. Refresh does not help; rebuild does not help. Widened window. Does not fix issue as other column adjust with change in window width.

**Are you willing to submit a PR?**

I am rather new to Airflow and do not have enough experience in fixing Airflow bugs.
![Screen Shot 2021-08-24 at 9 08 29 AM](https://user-images.githubusercontent.com/18553670/130621925-50d8f09d-6863-4e55-8392-7931b8963a0e.png)

**Comment by eladkal** [comment]
@zachliu we will have 2.1.4 the PR already marked to be released
