### ISSUE TITLE
Task stuck in running status

### ISSUE THREAD

**Issue by NanyinK** [apache/airflow#17827]
### Discussed in https://github.com/apache/airflow/discussions/17823

<div type='discussions-op-text'>

<sup>Originally posted by **NanyinK** August 25, 2021</sup>
Hi,

I tried to run a dag on the web UI but failed.
It's always showing "running" status.

and when I click on the logs, I get this : 
////////////////////////////////////////////////////////
*** Log file does not exist: /data/app/airflow/logs/dag_test/variable_step1/2021-08-14T16:00:00+00:00/1.log
*** Fetching from: http://:8793/log/dag_test/variable_step1/2021-08-14T16:00:00+00:00/1.log
*** Failed to fetch log file from worker. The request to ':///' is missing either an 'http://'                         or 'https://' protocol.
/////////////////////////////////////////////////////////

but when I run both of the steps locally on the server, it will succeed.

//////////////////////////////////////////////////////
[2021-08-25 15:09:06,214] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=variable_step1, execution_date=20210825T000000, start_date=20210825T070906, end_date=20210825T070906
///////////////////////////////////////////////////////

Could someone give some clues on troubleshooting this?
Thanks 
</div>

**Comment by potiuk** [comment]
Siince the discussion is quite extensive there and there seem to be no conclusion whether it is a configuration issue or a bug in Airflow..let's keep it as discussion. There is no clear reproduction path and a lot of details are missing here 

Closing this one.
