### ISSUE TITLE
Add another tab in Dags table that shows running now

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#17826]
The DAGs main page has All/Active/Paused.

It would be nice if we can have also Running Now which will show all the DAGs that have at least 1 in Running of DAG runs:
![Screen Shot 2021-08-25 at 11 30 55](https://user-images.githubusercontent.com/62940116/130756490-647dc664-7528-4eb7-b4d8-515577f7e6bb.png)

For the above example the new DAGs tab of Running Now should show only 2 rows.
The use case is to see easily what DAGs are currently in progress.

**Comment by bbovenzi** [comment]
After #11652 I think it makes sense to look into other sorting/filtering to do for the dags table.

**Comment by alexInhert** [comment]
@bbovenzi https://github.com/apache/airflow/pull/11652 seems to be closed
