### ISSUE TITLE
AwsBaseHook isn't using connection.host, using connection.extra.host instead

### ISSUE THREAD

**Issue by alwaysmpe** [apache/airflow#17833]
**Apache Airflow version**:

Version: v2.1.2
Git Version: .release:2.1.2+d25854dd413aa68ea70fb1ade7fe01425f456192

**OS**:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Apache Airflow Provider versions**:

**Deployment**:

Docker compose using reference docker compose from here: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html

**What happened**:

Connection specifications have a host field. This is declared as a member variable of the connection class here:
https://github.com/apache/airflow/blob/96f7e3fec76a78f49032fbc9a4ee9a5551f38042/airflow/models/connection.py#L101
It's correctly used in the BaseHook class, eg here:
https://github.com/apache/airflow/blob/96f7e3fec76a78f49032fbc9a4ee9a5551f38042/airflow/hooks/base.py#L69
However in AwsBaseHook, it's expected to be in extra, here:
https://github.com/apache/airflow/blob/96f7e3fec76a78f49032fbc9a4ee9a5551f38042/airflow/providers/amazon/aws/hooks/base_aws.py#L404-L406
This should be changed to
`endpoint_url = connection_object.host`

**What you expected to happen**:

AwsBaseHook should use the connection.host value, not connection.extra.host

**How to reproduce it**:

See above code

**Anything else we need to know**:

**Are you willing to submit a PR?**

Probably. It'd also be good for someone inexperienced. This would represent a backwards-incompatible change, any problem with that?

**Comment by alwaysmpe** [comment]
FYI: I'm currently moving house. Should have a look at this over the weekend. My thought was leave the current functionality working as is, if the host value in extra isn't present, use the connection defined version. Probably needs to combine host/port number, so I'll add a function to the connection to do that.

**Comment by ashb** [comment]
> FYI: I'm currently moving house. Should have a look at this over the weekend. My thought was leave the current functionality working as is with a deprecated warning. Then if the host value in extra isn't present, use the connection defined version. Probably needs to combine host/port number, so I'll add a function to the connection to do that.

That sounds about right, yes

**Comment by prajvan** [comment]
hi @ashb i can take this up, if it isnt being worked upon

**Comment by eshabhide** [comment]
Hi, looks like this issue is not getting any traction. I am happy to take a look at it.

**Comment by eladkal** [comment]
@eshabhide assigned to you
