### ISSUE TITLE
Connections created via AIRFLOW_CONN_ enviroment variables do not show up in the Admin > Connections or airflow connections list

### ISSUE THREAD

**Issue by ecerulm** [apache/airflow#17852]
The connections created using [environment variables like AIRFLOW_CONN_MYCONNID](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#storing-a-connection-in-environment-variables) do not show up in the UI. 

They don't show up in `airflow connections list` either, although if you know the conn_id you can `airflow connections get conn_id` and it will find it.

**Comment by ecerulm** [comment]
If it is expected behaviour should it be documented somehow in https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#storing-a-connection-in-environment-variables? 

Should I create a different issue for that?

**Comment by potiuk** [comment]
> Should I create a different issue for that?

Maybe just make a PR directly fixing it @ecerulm  It should be as easy as clicking "Suggest Change on this Page" button. No Need to create issue!
