### ISSUE TITLE
Macros reference point to outdated pendulum information

### ISSUE THREAD

**Issue by dmateusp** [apache/airflow#17853]
**Apache Airflow version**:

2.x

**Description**:

The documentation on Macros Reference is outdated when it comes to `pendulum`.

This commit: https://github.com/apache/airflow/commit/c41192fa1fc5c2b3e7b8414c59f656ab67bbef28 updated Pendulum to `~=2.0` but the [documentation](https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html) still refers to `pendulum.Pendulum` (which doesn't exist in 2.x). 

The link to the docs refers to 2.x, but it gives me a 404 when I try to open it? https://github.com/apache/airflow/blame/98d45cbe503241798653d47192364b1ffb633f35/docs/apache-airflow/templates-ref.rst#L178

I think these macros are all of type `pendulum.DateTime` now

**Are you willing to submit a PR?**

Yes, I'll add a PR asap

**Comment by 1nF0rmed** [comment]
@dmateusp Hey - just wanted to know if you are still working on this issue :)
