### ISSUE TITLE
More than one url in cors header

### ISSUE THREAD

**Issue by SegondsGauthier** [apache/airflow#17869]
**Description**

Enabled list of cors headers origin allowed

**Use case / motivation**

I'm currently developping Django application working with apache airflow for some external work through api. From Django, user run dag and a js request wait for dag end. By this way, I enabled cors headers in airflow.cfg with correct url. But now, I've  environment (dev & prod). It could be useful to be able to set more than one url in airflow.cfg cors header origin allowed

Thank's in advance :)

**Comment by SegondsGauthier** [comment]
Yes sure, I could work on it within next week

**Comment by GauthierSgds** [comment]
Hi, I switched to my pro account. I've just create a PR: https://github.com/apache/airflow/pull/17941. Feel free if you have some comments
