### ISSUE TITLE
Is it possible to extend the window with parameters in the UI? 

### ISSUE THREAD

**Issue by paantya** [apache/airflow#17874]
### Description

Is it possible to extend the window with parameters in the UI? - I have simple parameters and they do not fit (

### Use case/motivation

I have simple parameters and they do not fit (

### Related issues

yt

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Yes, we can make the textarea be more responsive to window size. I think there are other changes for configuration variables coming soon and it may be addressed then.

**Comment by paantya** [comment]
@bbovenzi 
cool!  tnx

Can you please tell me, can I change something somewhere so that this window becomes larger?

**Comment by bbovenzi** [comment]
Go to [trigger.js](https://github.com/apache/airflow/blob/main/airflow/www/static/js/trigger.js) and add something like `.setSize('null, 'auto');` or play around with other values and see what works.

**Comment by PApostol** [comment]
Hi, I'm also interested in the above. Should we make the config window dynamically change size based on the input JSON? Or maybe preset the height with a constant like `window.innerHeight * 0.5`?
