### ISSUE TITLE
Airflow 2.1.3 Variable.set(name, value) statement clears out Variable Description inserted in Airflow UI

### ISSUE THREAD

**Issue by gbonazzoli** [apache/airflow#17889]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Other

### Deployment details

LXD Container

### What happened

If you write in a DAG:

```
                Variable.set("BACKUP_ORACLE_PSDB_LAST_APPLIED_ARCH", p_event)
                Variable.set("BACKUP_ORACLE_PSDB_LAST_APPLIED_DATETIME", p_timestamp)
```

the Airflow Variables are successfuly set, but the descriptions are cleared away

### What you expected to happen

I expect that the description is left untouched, and it is only updatable by the Airflow UI

### How to reproduce

Create a Variable, give it a description, write 2 python lines of cod to update them.

```
from airflow.models           import Variable
Variable.set("BACKUP_ORACLE_PSDB_LAST_APPLIED_ARCH", "pippo")
Variable.set("BACKUP_ORACLE_PSDB_LAST_APPLIED_DATETIME", "puluto")
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
I don't think this is a bug. There's a `setdefault` method you can use for the behaviour you want above and not `set`.
@ash

**Comment by uranusjr** [comment]
The weird thing is there is no API to set the value _with_ description. Maybe we should have

```python
Variable.set(key, val, description=desc)  # description is optional.
Variable.update(key, value)  # Only works if there is a variable matching key?
```

**Comment by ephraimbuddy** [comment]
I like the first one: 
```python
Variable.set(key, val, description=desc)  # description is optional.
```
if we want it, I can work on it. Looks like there's a reason for the current design, will find out.

**Comment by ashb** [comment]
Variables didn't use to have descriptions, and when someone added it via the UI they forgot about the python API.

The interface uranusjr  proposes looks like a good one.

**Comment by SamWheating** [comment]
I can put together a PR for this if you want to assign this one to me.

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/18159
