### ISSUE TITLE
Change Azure operators to comply with AIP-21

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#17898]
### Body

Some of Azure operators/sensors paths needs to be changed:

|           Operator name           	|                              current path                             	|                             new path                            	|
|:---------------------------------:	|:---------------------------------------------------------------------:	|:---------------------------------------------------------------:	|
|  AzureContainerInstancesOperator  	| airflow.providers.microsoft.azure.operators.azure_container_instances 	| airflow.providers.microsoft.azure.operators.container_instances 	|
| AzureCosmosInsertDocumentOperator 	|        airflow.providers.microsoft.azure.operators.azure_cosmos       	|        airflow.providers.microsoft.azure.operators.cosmos       	|
|         AzureBatchOperator        	|        airflow.providers.microsoft.azure.operators.azure_batch        	|        airflow.providers.microsoft.azure.operators.batch        	|
|     AzureCosmosDocumentSensor     	|         airflow.providers.microsoft.azure.sensors.azure_cosmos        	|         airflow.providers.microsoft.azure.sensors.cosmos        	|

same should go for hooks:
https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/azure/hooks

fix should be similar to:
https://github.com/apache/airflow/pull/11209

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by josh-fell** [comment]
Should this also apply to the secrets backend?
https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/azure/secrets

**Comment by eladkal** [comment]
@josh-fell yep

**Comment by josh-fell** [comment]
@eladkal You can assign this to me if no one else has claimed it.

**Comment by potiuk** [comment]
Assigned!
