### ISSUE TITLE
upgrade_check should check python_callable is not used in TriggerDagRunOperator

### ISSUE THREAD

**Issue by aran3** [apache/airflow#17899]
### Apache Airflow version

2.1.2

### Operating System

Red Hat Enterprise Linux Server 7.6 (Maipo)

### Deployment

Virtualenv installation

### What happened

`airflow upgrade_check` should check `python_callable` is not used in `TriggerDagRunOperator`.
As of https://github.com/apache/airflow/pull/6317, `python_callable` is no longer supported (in any 2.x version) and dag tasks using it will fail to parse. 
This is not currently verified by upgrade_check and I caught it only after upgrading to 2.x. 

### What you expected to happen

upgrade_check to verify parameters of `TriggerDagRunOperator` and warn that `upgrade_check` should be removed and replaced with passing `conf` dictionary directly. 

### How to reproduce

run `airflow upgrade_check` on a dag with the following task (from PR):

```python
def _trigger_task(context, object):
    object.payload = {"message": "Hello world"}
    return object

trigger_task = TriggerDagRunOperator(
    task_id='test_trigger_dagrun',
    trigger_dag_id="example_trigger_target_dag",
    python_callable=_trigger_task,
    dag=dag,
)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Closing for two reasons:
1. There are no further releases of upgrade check tool as 1.10 is EOL.
2. In any case this is not something that can be added to the upgrade check as the `conf` param doesn't exist in `TriggerDagRunOperator` of 1.10 - It wasn't backported so this specific change is a breaking change. The upgrade checker doesn't handle breaking changes.
