### ISSUE TITLE
add yaml/omegaconf vizualization in UI in "run w/ config".

### ISSUE THREAD

**Issue by paantya** [apache/airflow#17912]
### Description

Can you please tell me, is it possible in params to draw the output in the form of yaml/omegaconf, not json? in UI

1. yaml is much more compact and easier to render.
2. omegaconf - has convenient interpolation functions that would be great to use when working with configs - I use it, I really like it.

omegaconf:

- git : https://github.com/omry/omegaconf
- docs: https://omegaconf.readthedocs.io/en/2.1_branch/

![image](https://user-images.githubusercontent.com/2975813/131343045-9df90bc3-133c-4acf-8779-4ac869ebe72d.png)

### Use case/motivation

- use of interpolations, in large configs
- use of yaml configs and no problems with quotes
- Using self-written macros to increase the power of the config
- Ability to write circuits yourself and further use in Hydra -core.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
That would be a nice feature to allow yaml input - it should be entirely possible (and seems super easy). 

What we need is just a Dict form, and this is both yaml and json compatible. We could even actually even parse the entry with yaml parser rather with json and this would work pretty much out-of-the-box @msumit - maybe you can include it - every "valid json" is automatically also "valid yaml" by definition, so it should be rather easy (and maybe there should be an option to choose the "default" values generated in the field as either json or yaml -it could be a toggle and could be stored in cookies. The json-schema defintion  can easily validate yaml input as well (we are doing it all the time in Airflow).

When it comes to omegaconf, I think it's an overkill. We do not need to merge configurations  - each DAG's configuration is separate from another, so I am not sure how omegaconf could be useful (though I do not know omegaconf  - i got that impression after looking at the page, so maybe I do not get how it could be helpful. Maybe you can explain it @paantya ?

**Comment by msumit** [comment]
@potiuk yeah we can include the yaml support as well, but maybe in the next diff, cause the current diff is already become pretty big and hanging for a long time.

**Comment by potiuk** [comment]
absolutely

**Comment by jens-scheffler-bosch** [comment]
Hi @paantya This feature request is stale for a long time and I got notice from some housekeeping. We on our side also thought a lot about YAML but never made it to propose an extension. YAML and JSON both are very easy to be supported in Python and standard libs are available.

Nevertheless the UI for triggering has changed a lot since the issue was reported first, meanwhile AIP-50 (see https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-50+Trigger+DAG+UI+Extension+with+Flexible+User+Form+Concept) was implemented to generate a user friendly trigger UI. JSON dict is still possible via API and also in the UI. UI is controlled via Params (see https://airflow.apache.org/docs/apache-airflow/stable/concepts/params.html)

Do you still see the need/demand for such feature? Or shall we close the ticket as long as we don't find a contributor?

**Comment by paantya** [comment]
wow, I haven't had time to get acquainted with the options page yet, thanks.
I don’t understand yet, is this the default now or can I change the display to JSON?

In my many years of experience, editing a yaml config is much easier than editing json. especially when it comes to lists...

I still see the point of displaying it in the UI as json, as, for example, is done in CLearML, and already inside you can immediately translate it into json and do all the necessary checks for values. Although, of course, I am more attracted to working with OmegaConf , but since you have implemented a lot using json, then, as they say. up to the community :)

**Comment by jscheffl** [comment]
I still had this a long time in my personal backlog, but as nobody opted for this and other priorities catched by focus, going to close this. Please re-open if there is still demand after the trigger DAG run UI.

**Comment by paantya** [comment]
yes, its actual
