### ISSUE TITLE
Support for Rerun of dagrun that is aborted

### ISSUE THREAD

**Issue by akashg116414** [apache/airflow#17928]
### Description

In a Dag, if there are multiple dagrun, so we can able to stop and rerun that dagrun using any runid or unique id

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I’m curious why you want to abort the run in the first place, if you want to un-abort it later? Airflow already allows you to trottle concurrent runs, and runs will stay in queue until there’s an empty slot for it. Also, how is this un-aborted run different from triggering a manual run?

**Comment by akashg116414** [comment]
Like if I have 5 python operator in a single dag which is running sequentially, if I abort that dagrun at 3rd python operator then it will resume or rerun from that 3rd python operator but in your case, if we triggered a manual run then it will start from 1st python operator.

**Comment by potiuk** [comment]
How about backfill?

**Comment by eladkal** [comment]
> Like if I have 5 python operator in a single dag which is running sequentially, if I abort that dagrun at 3rd python operator then it will resume or rerun from that 3rd python operator but in your case, if we triggered a manual run then it will start from 1st python operator.

Lets take your example - you have 5 operators  as ` a >> b >> c >> d >> e`  now `a` & `b` are success and `c` is running, you aborted the run (I would assume that by abort you mean set the dag to failure). To continue from where you left off all you need is to change the dagrun status to `Running`.


I'm closing this issue as it seems you can do what you wish with existed functionality. If this comment nor previous one solved you problem please provide some more information about what you had in mind.

**Comment by akashg116414** [comment]
It is known fact that it is works on UI but how about using it from API or cli commands, can you share me any reference if there is any API or Cli commands to change dagrun status from failed stage to running stage.

if we used Backfill then it will rerun last dagrun but what about re-run using dag runid.
