### ISSUE TITLE
template_ext in task attributes shows incorrect value

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#17932]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Debian Buster

### Deployment

Managed Services (Astronomer, Composer, MWAA etc.)

### Deployment details

Running `quay.io/astronomer/ap-airflow:2.1.3-buster` Docker image

### What happened

In the task attributes view of a BashOperator, the `template_ext` row doesn't show any value, while I would expect to see `('.sh', '.bash')`.

![image](https://user-images.githubusercontent.com/6249654/131467817-8620f68d-0f3d-491d-ad38-cbf5b91cdcb3.png)

### What you expected to happen

Expect to see correct `template_ext` value

### How to reproduce

Run a BashOperator and browse to Instance Details --> scroll down to `template_ext` row

### Anything else

Spent a little time trying to figure out what could be the reason, but haven't found the problem yet. Therefore created issue to track.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Not sure why this happens, but feel free to work on this!

**Comment by BasPH** [comment]
If only I knew the reason😅  Will dig a little deeper today

**Comment by BasPH** [comment]
Turns out `template_ext` is never serialized into the DB. Preparing PR.
