### ISSUE TITLE
Support  on conflict statement in DBApiHook

### ISSUE THREAD

**Issue by blcksrx** [apache/airflow#17938]
### Description

It's a good idea to support conflicts statements such as `ON CONFLICT DO NOTHING` or `ON CONFLICT UPDATE`
in `DBApi Hook`, that user can do it easily by providing additional  `kwargs` in `insert_rows` method.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free . Should I assign it to you :) ?

**Comment by eladkal** [comment]
@blcksrx I see that the PR you raised became stale. Do you wish to finish it?

**Comment by blcksrx** [comment]
Definitely, but Im still watching for review

**Comment by eladkal** [comment]
> Definitely, but Im still watching for review
The PR is closed so if you were waiting for some comment it's better to ping on the PR itself
