### ISSUE TITLE
Warn if robots.txt is accessed

### ISSUE THREAD

**Issue by thejens** [apache/airflow#17962]
### Description

https://github.com/apache/airflow/pull/17946 implements a `/robots.txt` endpoint to block search engines crawling Airflow - in the cases where it is (accidentally) exposed to the public Internet.

If we record any GET requests to that end-point we'd have a strong warning flag that the deployment is exposed, and could issue a warning in the UI, or even enable some kill-switch on the deployment. 

Some deployments are likely intentionally available and rely on auth mechanisms on the `login` endpoint, so there should be a config option to suppress the warnings.

An alternative approach would be to monitor for requests from specific user-agents used by crawlers for the same reasons

### Use case/motivation

People who accidentally expose airflow have a slightly higher chance of realising they've done so and tighten their security.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by thejens** [comment]
( now that I think of it, there may be - or perhaps should be - a plugin to Flask that does this)

**Comment by potiuk** [comment]
good idea.

**Comment by potiuk** [comment]
BTW. I think logging it in logs should possibly be enough ?

**Comment by thejens** [comment]
Logging would be a start. 

However I think the kind of user who accidentally expose their Airflow deployment are quite likely not the kind of user who monitors logs. I know quite a lot of data scientists who set up tooling like airflow without really understanding what they're doing - but simply following tutorials.

**Comment by potiuk** [comment]
> However I think the kind of user who accidentally expose their Airflow deployment are quite likely not the kind of user who monitors logs. I know quite a lot of data scientists who set up tooling like airflow without really understanding what they're doing - but simply following tutorials.

True.

**Comment by thejens** [comment]
Here's a list of google's crawlers user-agents btw; **https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers**

**Comment by ShakaibKhan** [comment]
This feature sounds interesting and I would like to try implementing it if no one minds :)

**Comment by potiuk** [comment]
Feel free!

**Comment by ShakaibKhan** [comment]
started pr to address this: https://github.com/apache/airflow/pull/18557
