### ISSUE TITLE
Center tree and graph view queries on current running dag run date instead of on now.

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#17979]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Ubuntu 20.04.2 LTS (Focal Fossa)

### Deployment

Other

### Deployment details

Local dev environment with breeze

### What happened

Running dagruns are not visible in the UI when there are many queued dagruns.

# Running not visible in tree view
![norunning](https://user-images.githubusercontent.com/4122866/131803071-dbb807d8-eefb-4011-a051-631b4c98b73f.PNG)

# Running not visible in graph view
![norunninggraph](https://user-images.githubusercontent.com/4122866/131803525-a4db61f1-5c3e-4168-91bb-2c509016c551.PNG)

# Running visible in details page
![2running](https://user-images.githubusercontent.com/4122866/131803173-25dc88ec-f04e-4516-9c85-cf8a1fb4567b.PNG)

### What you expected to happen

I expected to see the running dagruns in the tree view and graph view

### How to reproduce

Run this dag and check the tree/graph view when queued dagruns is more than 20:

```
from airflow import models
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta

with models.DAG('my-test-dag-for-active-runs',
                schedule_interval= '@daily',
                start_date = datetime(2021, 4, 4, 19, 20)
                catchup=True,
                max_active_runs=2
                ) as dag:

    start = BashOperator(
        task_id='start',
        bash_command='echo "Starting"; echo "Sleeping for 10 seconds"; sleep 10; echo "Finished"'
    )
    task2 = BashOperator(
        task_id='next_task',
        bash_command='echo "Starting"; echo "Sleeping for 10 seconds"; sleep 10'
    )
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
@bbovenzi

**Comment by bbovenzi** [comment]
It is working correctly since its showing the 25 most recent runs going back from the current date. Expanding the number of runs to 100 or 365 or manipulating the date will let you see the running tasks.

I'm not sure if this is something we want to fix.

Although I do notice a separate issue of how the tree refresh will render many newly created dag runs.

**Comment by ephraimbuddy** [comment]
> It is working correctly since its showing the 25 most recent runs going back from the current date. Expanding the number of runs to 100 or 365 or manipulating the date will let you see the running tasks.
> 
> I'm not sure if this is something we want to fix.
> 
> Although I do notice a separate issue with how the tree refresh isn't always rendering new dag runs correctly.

I'm thinking that we should make the running dags visible. Is there a way we could prioritize running dagruns to show first?
