### ISSUE TITLE
Can't delete user "admin"

### ISSUE THREAD

**Issue by malthe** [apache/airflow#17978]
### Apache Airflow version

2.1.2

### Operating System

Debian

### Deployment

Official Apache Airflow Helm Chart

### What happened

I tried to delete the "admin" user using the command-line interface:
```bash
$ airflow users delete -u admin
```
I get the message "User admin deleted".

But it's in fact not deleted!

### What you expected to happen

I get warnings such as:
```
WARNING - Refused to delete permission view, assoc with role exists My Profile.userinfoedit Admin
...
WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin
```

### Anything else

The problem persists between attempts. I also tried:
```bash
$ airflow sync-perm
```
Same warnings ...

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@malthe would you like to submit a PR to fix it?

**Comment by chenglongyan** [comment]
Resolved on main branch.
