### ISSUE TITLE
Backfill blocks all tasks from being queued when a single pool is full.

### ISSUE THREAD

**Issue by smamessier** [apache/airflow#17975]
### Apache Airflow version

2.0.1

### Operating System

Linux

### Deployment

Docker-Compose

### Deployment details

We are using pools with limited slots for various tasks.

### What happened

- Scheduled tasks on the default pool are blocked from being queued because of unrelated pools being maxed out.

### What you expected to happen

- Tasks scheduled on pools with free slots should keep getting queued and run. 

### How to reproduce

This (wrong) behavior is logical given the implementation of the backfiller https://github.com/apache/airflow/blob/2aa443f8d5f0fe9b4b37b9029e9bac5176c563ce/airflow/jobs/backfill_job.py#L575

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you please check if the issue still happens in latest airflow version?

**Comment by rmekdma** [comment]
This also happened in v2.2.0

**Comment by ninsbl** [comment]
This happend to me with Airflow 2.10.4...
