### ISSUE TITLE
Task groups are not stable in the UI

### ISSUE THREAD

**Issue by Limess** [apache/airflow#18009]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Amazon Linux 2

### Deployment

Other Docker-based deployment

### Deployment details

ECS, not relevant to issue

### What happened

The tree UI changes the order of tasks on auto refresh occasionally. This is fairly jarring when tracking a DAG run.

### How to reproduce

Create a large dag, e.g. dummy operators. Then browse the tree view with auto refresh false, the tasks will jump around on refresh.

e.g. we can reproduce the issue on this structure:

![image](https://user-images.githubusercontent.com/3199181/131997640-8578cf1a-1a73-4d19-bb98-7689e06656ff.png)

### Anything else

Occasionally on refresh

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Could you include a gif of your specific issue? We have a few issues with Task Groups in tree view and I want to makre sure we distinguish them all as I work on a full solution.


Related: #13242 #16112

**Comment by dnz-siliang** [comment]
Meeting the same issue from airflow 2.1.3. Tasks are keep changing location on tree view.
However we didn't meet this issue on 2.1.2.
Any ideas?

**Comment by Limess** [comment]
![Kapture 2021-09-20 at 10 36 58](https://user-images.githubusercontent.com/3199181/133982235-ed3cd1f6-3b14-468b-9314-c2415895379a.gif)
