### ISSUE TITLE
`context` parameter is unused on method `execute` on class `TriggerDagRunOperator`

### ISSUE THREAD

**Issue by ryanlow-tw** [apache/airflow#18049]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

macOS Catalina 10.15.7

### Deployment

Virtualenv installation

### What happened

https://github.com/apache/airflow/blob/8505d2f0a4524313e3eff7a4f16b9a9439c7a79f/airflow/operators/trigger_dagrun.py#L116

`context` parameter is unused and I need to pass in an empty dictionary to use the `execute` method.

### What you expected to happen

I shouldn't need to pass in an empty dictionary to the `context` parameter in order to use the `execute` method as the dictionary that is passed in is unused.

### How to reproduce

```
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.utils.trigger_rule import TriggerRule

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2021, 8, 30),
    'email': ['airflow@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG('test_wordcount_dag', default_args=default_args)

t1 = TriggerDagRunOperator(task_id='trigger_word_count_dag',
                                    trigger_dag_id='test_wordcount_dag',
                                    wait_for_completion=True,
                                    trigger_rule=TriggerRule.ONE_SUCCESS,
                                    dag=dag,
                                    poke_interval=5)

t1.execute(context={})
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
This parameter is required by BaseOperator, so we cannot change the signature of the method in a subclass.

Why do you want to invoke this method?

**Comment by ashb** [comment]
By having the code you show at the top level of your file  _every_ time Airflow parses the file (which is about once every 30s by default on new installs) it will call your TriggerDagRun task.
