### ISSUE TITLE
Move auto-refresh interval to config variable

### ISSUE THREAD

**Issue by rachelwigell** [apache/airflow#18069]
### Description

Auto-refresh is an awesome new feature! Right now it occurs every [3 seconds](https://github.com/apache/airflow/blob/79d85573591f641db4b5f89a12213e799ec6dea1/airflow/www/static/js/tree.js#L463), and this interval is not configurable. Making this interval configurable would be useful.

### Use case/motivation

On a DAG with many tasks and many active DAG runs, auto-refresh can be a significant strain on the webserver. We observed our production webserver reach 100% CPU today when we had about 30 running DAG runs of a DAG containing about 50 tasks. Being able to increase the interval to guard against this would be helpful.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
The config option is fine, but the number of Tasks in a DAG _shouldn't_ have any bearing on the number of requests made (it should be a single request per use on a Graph or Tree View page).

**Comment by rachelwigell** [comment]
Hmm okay. We were able to observe pretty clearly that when we had tree view open, with auto-refresh on, looking back over 365 DAG runs, of which about 30 were in the running state, our webserver ground to a halt and CPU was at 100%. When we closed that tab it recovered. I can do some experimentation in my dev environment tonight to see if I can nail down what exactly strains the CPU so much. It could be that even with just one request there was too much data to parse out of the request results for the webserver CPU to handle doing every 3 seconds.

**Comment by rachelwigell** [comment]
Yeah I haven't quite been able to locally replicate the same severe effects on CPU we saw a few days ago. I do see that we are indeed making just one request to populate the tree view regardless of whether I have many active tasks or DAG runs. Of course, that request has to do more work if there are lots of tasks to iterate over, but the n's here don't seem like enough to tank a server. Regardless, I'll move forward with my PR as I think folks still might like being able to customize this setting.

**Comment by ashb** [comment]
Yeah, absolutely no problem with your PR, I was just a bit surprised by the effects!
