### ISSUE TITLE
TriggerDagRunOperator start_date is not set

### ISSUE THREAD

**Issue by abezruchenkov** [apache/airflow#18082]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

ubuntu, macos

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==1.4.0
apache-airflow-providers-ftp==1.1.0
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-postgres==1.0.2
apache-airflow-providers-slack==4.0.0
apache-airflow-providers-sqlite==1.0.2

### Deployment

Virtualenv installation

### What happened

We are using TriggerDagRunOperator in the end of DAG to retrigger current DAG:

`TriggerDagRunOperator(task_id=‘trigger_task’, trigger_dag_id=‘current_dag’)`

Everything works fine, except we have missing duration in UI and ​warnings in scheduler :

`[2021-09-07 15:33:12,890] {dagrun.py:604} WARNING - Failed to record duration of <DagRun current_dag @ 2021-09-07 12:32:17.035471+00:00: manual__2021-09-07T12:32:16.956461+00:00, externally triggered: True>: start_date is not set.`

And in web UI we can't see duration in TreeView and DAG has no started and duration values. 

### What you expected to happen

Correct behaviour with start date and duration metrics in web UI.

### How to reproduce

```
import pendulum
import pytz
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from airflow.operators.trigger_dagrun import TriggerDagRunOperator


with DAG(
        start_date=pendulum.datetime(year=2021, month=7, day=1).astimezone(pytz.utc),
        schedule_interval='@daily',
        default_args={},
        max_active_runs=1,
        dag_id='current_dag'
) as dag:

    step1 = DummyOperator(task_id='dummy_task')

    trigger_self = TriggerDagRunOperator(task_id='trigger_self', trigger_dag_id='current_dag')

    step1 >> trigger_self
```

`[2021-09-08 12:53:35,094] {dagrun.py:604} WARNING - Failed to record duration of <DagRun current_dag @ 2021-01-04 03:00:11+00:00: backfill__2021-01-04T03:00:11+00:00, externally triggered: False>: start_date is not set.`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhavaniravi** [comment]
I was able to reproduce is locally, working towards creating a PR for the same

**Comment by sweco** [comment]
I'm observing exactly the same issue (missing `DagRun.start_date`) with Airflow 2.1.3 for `DagRun`s created via CLI:

```
airflow dags trigger <DAG_NAME>
```

![image](https://user-images.githubusercontent.com/11132999/133619884-6eaf60db-06be-4ce6-bf77-0d54db6d5072.png)

@bhavaniravi, will your PR fix the CLI as well?

**Comment by bhavaniravi** [comment]
Yes, @sweco Internally it's all using the same`trigger_dag`function , so this PR should fix it
