### ISSUE TITLE
Mark all tasks in task group failed/success from UI

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#18097]
### Description

I would like to be able to click on a task group in the Graph view (and tree view if task groups start being represented there as well) and bring up the dialog box for Clear/Mark Success/Failed including the downstream and failed options. Whatever is selected should then be applied to all tasks in the task group.

### Use case/motivation

As discussed on #17992, sometimes you have a series of parallel tasks that you want to operate on together. The best way to do that currently is to go one task upstream of the parallel tasks and use the "Downstream" option, but that can have unintended consequences for tasks further downstream if there are task with `all_done`. The only other option is to one-by-one mark all the parallel tasks.

With task groups, I think of this series of tasks as one entity, and I'd like to be able to operate one it as if that were true.

### Related issues

related #17992 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Good idea. I am working on improving how we show task groups in the tree view. After that is done, this would be a good next step.

**Comment by nathadfield** [comment]
In Airflow 2.7, Task Groups can now be marked as success or failed via Grid View.
