### ISSUE TITLE
Warning when Fernet/Webserver keys are randomly generated

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#18098]
### Description

While I think the random generation is rather useful for quick start, maybe it should be accompanied by a big fat warning (possibly including a warning generated in the UI) - directing user to generate both Fernet Key and Webserver key manually. We already'we done a few of those - for example Sequential executor + Sqlite recently.

I think showing a UI warning is the only one that is going to work, but it will be very effective and make people generate those keys eventually.

### Use case/motivation

When users install airllow for a "quick" start with Helm Chart, they might not realise, that they should generate the keys. While this is useful to generate the keys, the behaviour is not nice when the Helm Chart is upgraded and the keys regenerated - for example when you use argocd.

We should make it very clear for the users trying out airflow, that the setting they use for "quick start" is not good for "production" and rather than relying on generating the keys randomly they should generate and configure their keys manually.

### Related issues

https://github.com/apache/airflow/pull/18079#issuecomment-915393804

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
The secret key warning will be in place for chart 1.2.0 and Airflow 2.2.0.

I've opened a new issue (#18509) to cover the fernet key portion of this as it requires more than just a warning message.
