### ISSUE TITLE
Snowflake provider not accepting private_key_file in extras

### ISSUE THREAD

**Issue by weiminmei** [apache/airflow#18102]
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

2.1.1

### Apache Airflow version

2.1.3 (latest released)

### Operating System

centos7

### Deployment

Virtualenv installation

### Deployment details

Created a virtualenv, did a pip install.

### What happened

I am adding the dictionary below to the extras in snowflake connections. After I click save and try to access this connection, I get a response that the password field is empty. This leads me to believe that the dictionary key is not being picked up.

`{ "private_key_file": "/etc/key/key.pk8" }`

According to https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py, there is a KEY_PAIR_AUTHENTICATOR authenticator as well, but I am not sure if this is required to be passed as using the standard sqlalchemy I do not need to pass the authenticator.

### What you expected to happen

With the private_key_file provided, the session should connect without any errors.

### How to reproduce

Install apache-airflow-providers-snowflake 2.1.1

Go to connections
Add Snowflake
In extras field, enter the dictionary, click save.

### Anything else

Looks like it might be the same issue as https://github.com/apache/airflow/pull/16735.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
This is a symptom of connections using both custom fields and the classic `Extras` field in the connection form.  [This PR](https://github.com/apache/airflow/pull/17269) will fix the collision issue between the custom fields (which use `Extras` under the hood) and classic `Extra` values but it's definitely a good idea if there were explicit fields in the connection form for the parameters that are needed to connect to Snowflake.

**Comment by eladkal** [comment]
@weiminmei Can you please check if the issue still happens in `2.2.0b1` ?
The release includes https://github.com/apache/airflow/pull/17269 which should solve your issue.

**Comment by weiminmei** [comment]
> @weiminmei Can you please check if the issue still happens in `2.2.0b1` ?
> This is a beta release that includes #17269 which should solve your issue.

Sure, let me see about getting this version spun up to check. Does this mean that 2.1.4 did not include any fix for this?

**Comment by weiminmei** [comment]
Hi,

On version 2.2.0b1, looks like this is addressed.

![Screen Shot 2021-09-21 at 4 02 55 PM](https://user-images.githubusercontent.com/59876267/134247290-f416a0a1-4966-48c8-8d4d-3ccbef4f93a5.png)
