### ISSUE TITLE
HeadObject error when trying to upload file to S3

### ISSUE THREAD

**Issue by shlomi-viz** [apache/airflow#18111]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

```apache-airflow-providers-amazon==1.4.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-postgres==1.0.1
apache-airflow-providers-sftp==1.1.1
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==1.3.0
```

### Apache Airflow version

2.0.2

### Operating System

Mac and Linux

### Deployment

MWAA

### What happened

When trying to upload a file to another AWS account using the `load_file` function, I got the following 
```
An error occurred (403) when calling the HeadObject operation: Forbidden
```
looking at source code the error is from 
```
    @provide_bucket_name
    @unify_bucket_name_and_key
    def check_for_key(self, key: str, bucket_name: Optional[str] = None) -> bool:
        """
        Checks if a key exists in a bucket

        :param key: S3 key that will point to the file
        :type key: str
        :param bucket_name: Name of the bucket in which the file is stored
        :type bucket_name: str
        :return: True if the key exists and False if not.
        :rtype: bool
        """
        try:
            self.get_conn().head_object(Bucket=bucket_name, Key=key)
            return True
        except ClientError as e:
            if e.response["ResponseMetadata"]["HTTPStatusCode"] == 404:
                return False
            else:
                raise e
```

As I understand it I'm getting this error since I don't a `List` permissions on the bucket in the other account

### What you expected to happen

AirFlow should try and upload the file, even if it already exists. In this section of the code we can add another check for the response code we get when no `List` permissions

```python
        except ClientError as e:
            if e.response["ResponseMetadata"]["HTTPStatusCode"] == 404:
                return False
            else:
                raise e
````

### How to reproduce

Use the following command to upload the file to an S3 bucket that you only have `Get` and `Put` permissions.
```python 
s3_hook.load_file(local_file_path, bucket_name=bucket_name, key=s3_key, acl_policy='bucket-owner-full-control')
````

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
> AirFlow should try and upload the file, even if it already exists

`load_file` has `replace` parameter (default False)
https://github.com/apache/airflow/blob/43f595fe1b8cd6f325d8535c03ee219edbf4a559/airflow/providers/amazon/aws/hooks/s3.py#L499-L500 
You don't set it in your example so it will not try to overwrite existed key.

Is your suggestion only catch the error from the API and change it to an Airflow error?
You are always welcome to open PR directly with your suggested code.

**Comment by shlomi-viz** [comment]
I want it to be able to upload a file in any case (file already exists or not), I know about the `replace` flag, but I also want to cover the case when the file doesn't exists. 

My suggestion is to catch the error and allow the upload, without adding another error. It will be something like, updating:
```python
        except ClientError as e:
            if e.response["ResponseMetadata"]["HTTPStatusCode"] == 404:
                return False
            else:
                raise e
```

to:

```python 
        except ClientError as e:
            if e.response["ResponseMetadata"]["HTTPStatusCode"] IN (404, 403):
                return False
            else:
                raise e
```

shortest PR ever 😆  I will try to submit one next week.

**Comment by shlomi-viz** [comment]
I created a PR https://github.com/apache/airflow/pull/18201, what is the process to get it reviewed? Thanks

**Comment by xinbinhuang** [comment]
> I want it to be able to upload a file in any case (file already exists or not), I know about the `replace` flag, but I also want to cover the case when the file doesn't exists.
> 
> My suggestion is to catch the error and allow the upload, without adding another error. It will be something like, updating:
> 
> ```python
>         except ClientError as e:
>             if e.response["ResponseMetadata"]["HTTPStatusCode"] == 404:
>                 return False
>             else:
>                 raise e
> ```
> 
> to:
> 
> ```python
>         except ClientError as e:
>             if e.response["ResponseMetadata"]["HTTPStatusCode"] IN (404, 403):
>                 return False
>             else:
>                 raise e
> ```
> 
> shortest PR ever 😆 I will try to submit one next week.

I believe the `replace` flag will just upload the file regardless if the key exists or not. Have you tried it? We don't call the `check_for_key` function when `replace=True`.

IMO, It's not reasonable for us to swallow the permission error.
