### ISSUE TITLE
Methods `TaskInstance.get_previous_execution_date()` & `TaskInstance.get_previous_ti()` are lying !

### ISSUE THREAD

**Issue by cansjt** [apache/airflow#18116]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Linux

### Versions of Apache Airflow Providers

Irrelevant

### Deployment

Other

### Deployment details

Irrelevant

### What happened

The method `TaskInstance.get_previous_execution_date()` asks a state, which logically means you should get as a return value the execution date of the same tasks, with the given state.

But in truth it is not the tasks state that is looked, but the [previous DagRun state](https://github.com/apache/airflow/blob/ebbe2b4cafebe2b523ca08abd40145c3c7eec046/airflow/models/taskinstance.py#L916). Which means that, for example, using the method to determine when was the last time when the task was not skipped, you get the wrong date in return as the actual tasks states are disregarded.

The behaviour is not only unexpected, but undocumented as the method documentation refers the reader to a now deprecated and undocumented method, which refers you to the documentation of yet another method [`get_previous_ti()`](https://github.com/apache/airflow/blob/ebbe2b4cafebe2b523ca08abd40145c3c7eec046/airflow/models/taskinstance.py#L913) which states:

> The task instance for the task that ran before this task instance.
> :param state: If passed, it only take into account instances of a specific state.

Given that this is a method of the TaskInstance class, that returns yet another TaskInstance instance, I don't see why the users of this method should not assume it is the state of tasks instance that is being considered in the method implementation. Yet it is not, it is the DagRun state that is.

### What you expected to happen

I'd expect the method to return me the  task instance (or its execution date, depending on the method) that is in the state I gave, not any instance possibly not in the state I specified.

### How to reproduce

Create a DAG with one task
Create two DagRun for the dag the first shoud complete, the second should be skipped.
Create a third dag run that looks for the last task in the SUCCESS state. You will not get the (execution date of the) task from the first dag run, but from the second dag run.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
There was another issue on this recently but I couldn’t find it right now. The bottom line is this method is like this since, like, forever, and we can’t just change it now.

From what I can tell, `get_previous_ti(state)` is _never_ intended to be used as a public API (only `get_previous_ti()` with, which gives you the previous TaskInstance as the name suggests), so perhaps we should separate the two signatures (and rename the with-state version to something better).

**Comment by cansjt** [comment]
Sorry if this is a duplicate. I searched the methods names, but could not find anything.

I am not sure I understand what you mean about these method not being public. In the context of an operator comes the `TaskInstance` instance. It has been so since forever too. So I would consider all public methods of the `TaskInstance` class to be public API. By extension any object reachable from the context or through calls to public methods on those objects to be public API.

I do understand that fixing this could break lots of different behaviors, though. So if it is less risky to simply had another method with the proper behavior, that would be okay to me, though naming it will probably be a bit difficult.

**Comment by uranusjr** [comment]
> It has been so since forever too. So I would consider all public methods of the TaskInstance class to be public API.

The method is only made public in 2.0, so definitely not since forever. Yes it’s currently public (technically not all public methods are public API, only documented ones, but that distinction is not relevant here), but I was saying it was never _intended_ to be public (at least the `state` argument is not), so we should fix that.

**Comment by potiuk** [comment]
Agree with @uranusjr - we should likely deprecate the parameter (and replace it with an internal/non-public method) and remove the parameter  in Airflow 3.

**Comment by cansjt** [comment]
Too bad, I find it useful.

**Comment by ybressler** [comment]
I'm experiencing this issue too.

Could we not design this method to query the relational DB via the ORM directly?

Ex:
```
get_previous_ti(state):
    return TaskInstance.filter(state=state, task_id=self.task_id).order_by(date).first()
```

**Comment by uranusjr** [comment]
The problem is not _how_ we can change the method, but that we _can’t_ change the method without affecting other things.

**Comment by TamGB** [comment]
Is there any way to get the tasks's previous succesful execution date? Would @ybressler 's method work?
This is particularly useful when using branching strategies based on time.

**Comment by Guilherme-B** [comment]
Should anyone require, I was experiencing the same problem and this is how I approached it:

```
@provide_session
def get_previous_ti_by_state(task_instance: TaskInstance, task_state: TaskInstanceState, session: Session = NEW_SESSION) -> TaskInstance:
    # retrieve the latest Task Instance model whose TaskInstanceState corresponds to the specified task instance state
    return session.query(TaskInstance).filter_by(state=task_state, task_id=task_instance.task_id).order_by(TaskInstance.start_date.desc()).first()

@provide_session
def get_previous_ti_success(task_instance: TaskInstance, session: Session = NEW_SESSION) -> TaskInstance:
    return get_previous_ti_by_state(task_instance=task_instance, task_state=TaskInstanceState.SUCCESS, session=session)
```

**Comment by potiuk** [comment]
I think we will add deprecation with "broken by design" while adding AIP-44 ( and in case of AIP-44 those will raise exception when used). We will have to take a close look at all such methods during AIP-44 completion so this is a good opportunity to do something about it.
