### ISSUE TITLE
Allow airflow standard images to run in openshift utilising the official helm chart

### ISSUE THREAD

**Issue by nwalens** [apache/airflow#18136]
### Description

Airflow helm chart is very powerful and configurable, however in order to run it in a on-premises openshift 4 environment, one must manually create security context constraints or extra RBAC rules in order to permit the pods to start with arbitrary user ids.

### Use case/motivation

I would like to be able to run Airflow using the provided helmchart in a on-premises Openshift 4 installation.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Good Idea. While the Airflow Official Image supports Open-Shift  arbitrary user, the Charts might indeed need some modifications to be able to support it out-of-the-box cc: @jedcunningham ?

**Comment by potiuk** [comment]
Happy to help with review @nwalens !

**Comment by jedcunningham** [comment]
@nwalens, I'm also happy to help! Ping us on slack in #helm-chart-official if you get stuck or want/need to chat about this 👍.

**Comment by nwalens** [comment]
Hi @jedcunningham  and @potiuk, thanks for the support!

I have just create a pull request (#18147) addressing this issue.

Thanks a lot!
