### ISSUE TITLE
Upgrade `importlib-resources` version

### ISSUE THREAD

**Issue by bmckallagat-os** [apache/airflow#18155]
### Description

The version for `importlib-resources` constraint sets it to be [v1.5.0](https://github.com/python/importlib_resources/tree/v1.5.0) which is over a year old. For compatibility sake (for instance with something like Datapane) I would suggest upgrading it. 

### Use case/motivation

Upgrade a an old dependency to keep code up to date.

### Related issues

Not that I am aware of, maybe somewhat #12120, or #15991.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free. It is configured in setup.cfg - you need to change it and see what happens when all tests run. If all tests pass, we will merged. Remember that importlib_resources are backport of the 3.9 native library and we need to make sure we are compatible with 3.6 - 3.9.

**Comment by bmckallagat-os** [comment]
> Feel free. It is configured in setup.cfg - you need to change it and see what happens when all tests run. If all tests pass, we will merged. Remember that importlib_resources are backport of the 3.9 native library and we need to make sure we are compatible with 3.6 - 3.9.

Got it! Will do.
