### ISSUE TITLE
install of airflow fails in argoCD because post-install hook in migrate-database-job.yaml

### ISSUE THREAD

**Issue by angel9484** [apache/airflow#18172]
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.1.2

### Kubernetes Version

1.18

### Helm Chart configuration

no configuration

### Docker Image customisations

no customization

### What happened

if we install airflow against argoCD, argoCD synchronizes all, then webserver and scheduler tries to run, inits with the wait-for-migrations but the job from migrate-database-job.yaml will never run because is not yet "installed" from the point of view of argoCD synchronization.

### What you expected to happen

To run the job from migrate-database-job.yaml without need of post-install in first "installation"

### How to reproduce

Install chart using argoCD (per example version v1.8.7+eb3d1fb) 

### Anything else

We can fix it setting replicas to 0 to scheduler and webserver (minimum), then we let to continue to post-install and then change again the replicas to scheduler and webserver

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/17447
