### ISSUE TITLE
Helm chart ingress support multiple hostnames

### ISSUE THREAD

**Issue by fredthomsen** [apache/airflow#18216]
### Description

When the official airflow helm chart is used to install airflow in k8s, I want to be able to access the airflow UI from multiple hostnames.  Currently given how the ingress resource is structured it doesn't seem possible, and modifying it needs to take into account backwards compatibility concerns.

### Use case/motivation

Given my company's DNS structure, I need to be able to access the airflow UI running in kubernetes from multiple hostnames.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
@fredthomsen Assigned. I know some corporations have complex DNS configurations.
