### ISSUE TITLE
Audit Logging for Variables, Connections, Pools

### ISSUE THREAD

**Issue by alex-astronomer** [apache/airflow#18217]
### Description

Audit Logs or some other type of logging that shows details about the [who, what, where, when, why] [changed, added, delted] Airflow Variables, Connections, Pools etc.

### Use case/motivation

Anything configurable from the UI should have Audit Logging or some other type of tracking which will allow admins and other adequately permission'd users to see details about when these configurables were added, changed, deleted, etc.

Whether or not these changes happen from API, UI, environment variables on Astronomer, no matter how these change it would be useful to know the details and owners of those changes.

Very generic issue right now on purpose.  Partially because I don't know the best implementation for this off the top of my head, and partially because I think this would be very useful to start a discussion about with stakeholders and contributors to discover the most elegant solution.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by alex-astronomer** [comment]
Love that idea.  I was starting to look in the Variables (`variables.py`) and found a `set(...)` function that looks like the root for where variables are set.  That was my first glance, and seemed like a good place to start or add a logging decorator or something.  I like the idea of SQLAlchemy events though.  Makes sure that every time that changes it gets captured.  I'll definitely look into this more before getting assigned.  I think this might be a tough one for an early contributor like me but definitely something I'm willing to take a crack at.

**Comment by alex-astronomer** [comment]
Upon further consideration, I'd like to not use a SQLAlchemy event to make this happen.  The way that we handle audit logging right now happens (from what I've seen) mostly through decorators and I'd like to take a similar approach to this problem just for clarity.  I feel like a sqlalchemy event could have the potential to be lost in the code in some obscure spot and I'd like to have the audit logging occur at the source of the change, right next to the code that makes that change.  Right now after the research that I've done both the API and CLI call the `Variable.set(...)` `classmethod` when making their changes to variables.  I'm starting with Audit Logging for setting Variables through CLI, API, and UI.  What do you think about that @potiuk?

**Comment by potiuk** [comment]
WHy not - go ahead!

**Comment by repl-mike-roest** [comment]
@alex-astronomer have you made any progress on this?  This is a feature we would really like as well.  

Would be willing to work on a PR as well
