### ISSUE TITLE
Cannot import name 'FlowerCommand' from 'flower.command'

### ISSUE THREAD

**Issue by sbwilli3** [apache/airflow#18223]
### Apache Airflow Provider(s)

celery

### Versions of Apache Airflow Providers

apache-airflow==2.1.3
apache-airflow-providers-celery==2.1.0
celery==5.1.2
flower==1.0.0

### Apache Airflow version

2.1.3 (latest released)

### Operating System

Ubuntu 20.04.1 LTS (Focal Fossa)

### Deployment

Virtualenv installation

### Deployment details

executor = CeleryExecutor

### What happened

When issuing **apache celery worker** or **apache celery flower** I receive the following error: 

Traceback (most recent call last):
  File "/home/airflow/sandbox/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 47, in command
    func = import_string(import_path)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/cli/commands/celery_command.py", line 29, in <module>
    from flower.command import FlowerCommand
ImportError: cannot import name 'FlowerCommand' from 'flower.command' (/home/airflow/sandbox/lib/python3.8/site-packages/flower/command.py)

### What you expected to happen

I would expect the Flower UI to be loaded or a celery worker to be started.

### How to reproduce

Configure apache-airflow with the CeleryExecutor
Issue the following commands: **apache celery worker** or **apache celery flower**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Celery 5.0 and Flower 1.0 are not supported by Airflow 2.1. Please use the constraint files to install Apache Airflow. to avoid dependency problems.
https://github.com/apache/airflow/blob/constraints-2.1.3/constraints-3.6.txt
http://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files

Duplicate: https://github.com/apache/airflow/issues/11301

**Comment by pacharaphet** [comment]
Why would it be done this way? I installed airflow using a constraint file with version 0.9.7 of flower but I am getting the same error. Just seems strange to provide the syntax airflow celery flower when later versions of flower aren't supported. Still very new to this, if someone could just give me the correct term for this, I would happy to go research it further on my own and then report back.

**Comment by potiuk** [comment]
Commenting on issue closed 6 months ago makes no sense and brings `0` value if you provide no new details.  You likely have diferent issue.  Please create a new discussion or open issue if you have reproducible case and describe the exact case you have.

**Comment by pacharaphet** [comment]
Sorry. I do not have a different issue, tho.

ในวันที่ พฤ. 31 มี.ค. 2022 19:27 Jarek Potiuk ***@***.***>
เขียนว่า:

**Comment by potiuk** [comment]
> Sorry. I do not have a different issue, tho.

Message might be the same, Issue might be different. And this isssue has been closed so likely your issue is different. But no-one has idea because you have not shown the details, you just wrote you have the same issue (and honestly you don't even know if it is the same issue because the user has not confirmed neither issue nor solution - so your certainty you have THE SAME issue, when we don't even know what really the orginal issue was is pretty stunning.
