### ISSUE TITLE
Airflow Celery Worker logs inaccessible 

### ISSUE THREAD

**Issue by datsabk** [apache/airflow#18239]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Python 3.6 Apache Airflow Docker

### Versions of Apache Airflow Providers

2.1.3

### Deployment

Other Docker-based deployment

### Deployment details

Kubernetes based deployment - Workers and Master in Kubernetes as pods. Logs accessed via NodePort Service

### What happened

*** Log file does not exist: /xxx/airflow/home/logs/xxxx/2021-09-14T12:13:32.383510+00:00/1.log
*** Fetching from: http://tsc-aflow-orca:8793/log/xxxx/2021-09-14T12:13:32.383510+00:00/1.log
*** Failed to fetch log file from worker. 503 Server Error: Service Unavailable for url: http://tsc-aflow-orca:8793/log/xxxx/2021-09-14T12:13:32.383510+00:00/1.log
For more information check: https://httpstatuses.com/503

Checked the Worker pod - Logs exist. However, it seems like the Worker web service is unable to access the logs. 

### What you expected to happen

Worker logs worked fine with the same setup but older version v1.10.12

### How to reproduce

Run a sample Dag with Webserver, Scheduler and one Worker running in Kubernetes - No custom setup. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dimon222** [comment]
In airflow.cfg set this
```
hostname_callable = airflow.utils.get_host_ip_address
```

**Comment by datsabk** [comment]
Hello @dimon222 - The workers are sitting behind a Kubernetes service. Hence, the logs need to be accessible via the service name. To support this, I have used a different hostname callable and gave it the DNS name of service. 

I do not see how it could be a problem though. You can imagine the situation like: 

master.abc.com -> Airflow master
worker.abc.com -> Airflow workers (multiple behind a load balancer sharing logs storage) 

I need logs to be accessible behind worker.abc.com instead of via IP address

**Comment by pvanliefland** [comment]
I'm using the helm chart and experiencing something similar. When using `KubernetesExecutor` and `logs.persistence.existingClaim`, it works fine. As soon as I switch to `CeleryExecutor` (without touching `logs.persistence.existingClaim`), I also get `Log file does not exist`.

**Comment by SamWheating** [comment]
> worker.abc.com -> Airflow workers (multiple behind a load balancer sharing logs storage)

I don't think this is going to work, since each airflow worker runs a background flask application which serves logs from tasks run on that worker at the specified logging port (in this case 8793). 

https://github.com/apache/airflow/blob/9b3ed1f652fcdf6eaf672e5d15646a0512b852f4/airflow/utils/serve_logs.py#L70-L72

By running the workers behind a load balancer, you're removing the webserver's ability to specify which server the logs are stored on. I suspect that if you reload the page enough times it may work eventually when your request happens to be routed to the correct worker via the load balancer.

**Comment by dimon222** [comment]
> By running the workers behind a load balancer, you're removing the webserver's ability to specify which server the logs are stored on..
I would assume "shared logs" implies that storage is shared (mounted volume, PVC in kubernetes, etc). Unless there's something on worker itself restricts to go above what was allocated to this specific worker to do?

**Comment by dimon222** [comment]
@changxiaoju 
containerPort on container of airflow worker in property `ports`
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by changxiaoju** [comment]
> @changxiaoju containerPort on container of airflow worker in property `ports` https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

Thankyou, but i am not using CeleryExecutor , instead i use LocalExcutor,  what may cause the error then?

**Comment by dimon222** [comment]
> > @changxiaoju containerPort on container of airflow worker in property `ports` https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
> 
> Thankyou, but i am not using CeleryExecutor , instead i use LocalExcutor, what may cause the error then?

If error does include the port still in a same way as you see in first message, you could attempt expose that port on your scheduler. If not, I suspect you have some unrelated exception and should probably make separate ticket for that.

**Comment by eladkal** [comment]
Please check if the issue happens on latest Airflow version (there has been some work related to this)
