### ISSUE TITLE
Deferred status color not distinct enough

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#18245]
### Apache Airflow version

2.2.0b1 (beta snapshot)

### Operating System

Mac OSX 11.5.2

### Deployment

Docker-Compose

### What happened

In the tree view, the status color for deferred is very difficult to distinguish from up_for_reschedule and is generally not very distinct. I can’t imagine it’s good for people with colorblindness either.

### What you expected to happen

I expect the status colors to form a distinct palette. While there is already some crowding in the greens, I don't want to see it get worse with the new status.

### How to reproduce

Make a deferred task and view in tree view.

### Anything else

I might suggest something in the purple range like [BlueViolet #8A2BE2](https://www.color-hex.com/color/8a2be2)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@collinmcnulty Would you mind including a screenshot of the mismatched colors?

**Comment by collinmcnulty** [comment]
![image](https://user-images.githubusercontent.com/13177948/133287298-c17682ed-89b4-4b1b-bf43-6e56c733c212.png)
![image](https://user-images.githubusercontent.com/13177948/133287365-0f2b7e13-c8d5-423e-985b-fec65d1f288e.png)

I think it's pretty tough to tell if the task above is deferred or up_for_reschedule.

**Comment by collinmcnulty** [comment]
Also, the fact that the black border is used to distinguish manual vs scheduled makes it more of an issue, since the border affects perceived color.
