### ISSUE TITLE
Spurious message complaining of no heartbeat from Triggerer

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#18246]
### Apache Airflow version

2.2.0b1 (beta snapshot)

### Operating System

Mac OSX 11.5.2

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==1.1.0
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-sqlite==1.0.2

### Deployment

Docker-Compose

### Deployment details

Docker compose (from astro cli). Then I ran an `airflow triggerer` process in the same container as the airflow scheduler. I did not daemonize the triggerer so I'm watching it with docker exec

### What happened

I am running a TimeDeltaTrigger like this:
```
class WaitAMinuteSensor(BaseSensorOperator):
    def execute(self, context):
        self.defer(trigger=TimeDeltaTrigger(timedelta(minutes=1)), method_name="execute_complete")

    def execute_complete(self, context, event=None):
        # We have no more work to do here. Mark as complete.
        print(event)
        return
```

The trigger works as expected, but I still get a banner message complaining about lack of a triggerer process.
![image](https://user-images.githubusercontent.com/13177948/133281609-23490ecc-46ca-4399-81a7-cd10fde50e53.png)

### What you expected to happen

No banner message when I have a running, working triggerer.

### How to reproduce

1. Spin up docker compose with scheduler, webserver, and postgres12.2 pods. Running local executor.
2. Docker exec onto scheduler pod and run `airflow triggerer`.
3. Run a dag with a TimeDeltaTrigger with one minute delay.
4. Go to tree view and watch for banner.

### Anything else

I turned the dag on before running triggerer, so at that point the banner was helpful. Then I ran the triggerer, the banner disappeared for a bit. Then it returned. At first I though it would only show up after 30 seconds with no trigger, but as you can see it got up to many minutes.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
This should be fixed by #18129 already (it didn't make it in before b1).
