### ISSUE TITLE
Airflow 2.1.4rc2 has snowflake-connector-python 2.6.0 which has a known bug

### ISSUE THREAD

**Issue by aa-matthias** [apache/airflow#18288]
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

I tested Airflow 2.1.4rc2 (Python 3.9) resulting in issues with putting files to snowflake stage.

the [constraints file](https://github.com/apache/airflow/blob/constraints-2.1.4rc2/constraints-3.9.txt) is pointing to 2.6.0 for snowflake-connector-python which has an [issue with PUT / GET](https://github.com/snowflakedb/snowflake-connector-python/issues/850)

it seems to be updated already in `https://github.com/apache/airflow/blob/constraints-2-1/constraints-3.9.txt` so maybe it will be solved in 2.1.4.

just wanted to point it out.

### Apache Airflow version

main (development)

### Operating System

Ubuntu 20.04

### Deployment

Virtualenv installation

### Deployment details

Installed via pip pointing to the constraints file for 2.1.4rc2

### What happened

snowflake-connector-python 2.6.0 got installed which has an issue with PUT / GET

### What you expected to happen

the final release should point to snowflake-connector-python 2.6.1

### How to reproduce

install 2.1.4rc2 in venv pointing to constraints file

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I see snowflake connector python has a bug - We can bump constraints separately from releasing the software. I will take a look and if it works we can even push a new image (cc: @kaxil )

**Comment by potiuk** [comment]
Yeah. The constraints were even automatically bumped to include 2.6.1 (our automated constraints upgrade works miracles sometimes). 

I just moved the tag and I am rebuilding the images to include those. They should be refreshed in ~30 minutes or so

**Comment by potiuk** [comment]
Should be fine:

![Screenshot 2021-09-16 13 13 24](https://user-images.githubusercontent.com/595491/133602375-194d7836-4e03-4a7a-9b88-29046825f4c5.png)

**Comment by kaxil** [comment]
Thanks @aa-matthias for reporting and @potiuk for quick fix

**Comment by swiffer** [comment]
@kaxil / @potiuk - 2.1.4 is out and constraints are tagged with 2.6.0 again

**Comment by kaxil** [comment]
@swiffer Let me update that now, not sure what happened there

**Comment by potiuk** [comment]
Yeah. The final tag is set for rc1 not rc2. I just pushed the right tag.

**Comment by potiuk** [comment]
Refreshing the images now too. Should be there in 20 minutes or so.

**Comment by kaxil** [comment]
Cool, thanks @potiuk - was about to push.
