### ISSUE TITLE
db+ string in result backend but not metadata secret

### ISSUE THREAD

**Issue by EliMor** [apache/airflow#18283]
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.1.3 (latest released)

### Kubernetes Version

1.21

### Helm Chart configuration

  data:
    metadataSecretName: "airflow-metadata"
    resultBackendSecretName: "airflow-result-backend"

### What happened

If we only supply 1 secret with 
```
connection: postgresql://airflow:password@postgres.rds:5432/airflow?sslmode=disable
```
To use for both metadata and resultBackendConnection then we end up with a connection error because
resultBackendConnection expects the string to be formatted like 
```
connection: db+postgresql://airflow:password@postgres.rds:5432/airflow?sslmode=disable
```
from what i can tell

### What you expected to happen

I'd expect to be able to use the same secret for both using the same format if they are using the same connection. 

### How to reproduce

Make a secret structured like above to look like the metadataConnection auto-generated secret.
use that same secret for the result backend.
deploy.

### Anything else

Occurs always. 
To get around currently we make 2 secrets one with just the db+ prepended. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I am not sure this is a helm-chart issue. It could probably be handled by the airflow itself - there are just few prefixes of the URL that could be shared with Airflow Metadata DB (postgres/sqlite/mysql variants) and it could be as easy of adding `db+` in front.

@EliMor  - maybe you would like to make a PR in Airflow to implement it? Sounds like an easy thing for a small, nice contribution.

**Comment by bigyan-kc** [comment]
@potiuk  Can I take this? I will submit PR.

**Comment by EliMor** [comment]
I'd be happy to try to take this, but if @bigyan-kc  would like to I don't want to stand in the way. 

Thank you.

**Comment by potiuk** [comment]
Feel free1 @EliMor  - you can review the change :)

**Comment by EliMor** [comment]
Thank you @potiuk 
I was wondering if we could also add a small comment to the values file to hint what the secret created should look like.
Somewhere around here; https://github.com/apache/airflow/blob/main/chart/values.yaml#L242
Could you add that as well @bigyan-kc  please if @potiuk  thinks its worth it? 

Thank you again.

**Comment by bigyan-kc** [comment]
@EliMor sure I will also add comment to the values file.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hello,
Is this still available?

**Comment by Aakcht** [comment]
Hello, I could use a fix for this issue, but the issue hasn't been updated in a while 😟 If no one minds, can I try submitting a PR for it?

**Comment by potiuk** [comment]
Feel free
