### ISSUE TITLE
None button under recent tasks creates an invalid search response

### ISSUE THREAD

**Issue by ITJamie** [apache/airflow#18294]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

ubuntu 20.04, bitnami docker image

### Versions of Apache Airflow Providers

bitnami docker image 2.1.3 latest

### Deployment

Docker-Compose

### Deployment details

bitnami docker images 2.1.3, using docker compose. fairly minimal install

### What happened

when attempting to view "None" scheduled tasks via the quick links on dashboard you get a search query that returns no tasks at all

### What you expected to happen

to return the current tasks scheduled with None state

### How to reproduce

Use 2.1.3 airflow and press None on a task with tasks in that state

### Anything else

screenshots here: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1631631911171900

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Changing to `webserver` since this is an issue with Flask AppBuilder search params. I looked through the docs and I'm not sure how to search by a null state. I've tried `="` `" =''` `=none` `=null` and `=`
