### ISSUE TITLE
Offline Usage of the User's Statistics

### ISSUE THREAD

**Issue by JNGruse** [apache/airflow#18297]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==1.4.0
apache-airflow-providers-celery==1.0.1
apache-airflow-providers-cncf-kubernetes==1.2.0
apache-airflow-providers-docker==1.2.0
apache-airflow-providers-elasticsearch==1.0.4
apache-airflow-providers-ftp==1.1.0
apache-airflow-providers-google==3.0.0
apache-airflow-providers-grpc==1.1.0
apache-airflow-providers-hashicorp==1.0.2
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-microsoft-azure==2.0.0
apache-airflow-providers-mysql==1.1.0
apache-airflow-providers-postgres==1.0.2
apache-airflow-providers-redis==1.0.1
apache-airflow-providers-sendgrid==1.0.2
apache-airflow-providers-sftp==1.2.0
apache-airflow-providers-slack==3.0.0
apache-airflow-providers-sqlite==1.0.2
apache-airflow-providers-ssh==1.3.0

### Deployment

Docker-Compose

### What happened

We want to use the security/user's statistics in an offline environment. Unfortunately nothing is shown.

Further investigations revealed that the google_chart.js is using loader.js, which on the other hand is trying to reach https://www.gstatic.com/charts/48.1/loader.js . This makes the feature not usable in an offline environment.

### What you expected to happen

That the chart in security/user's statistics can be displayed in an offline environment.

### How to reproduce

Revoke the computer's internet access and reload the chart in security/user's statistics. As you will see, nothing will be displayed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
This looks like a problem with the Flask App Builder. Can you create a ticket for this project as well? https://github.com/dpgaspar/Flask-AppBuilder
