### ISSUE TITLE
Add task name, DAG name, try_number, and run_id to all Kubernetes executor logs

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#18329]
### Description

Every line in the scheduler log pertaining to a particular task instance should be stamped with that task instance's identifying information. In the Kubernetes executor, some lines are stamped only with the pod name instead.

### Use case/motivation

When trying to trace the lifecycle of a task in the kubernetes executor, you currently must search first for the name of the pod created by the task, then search for the pod name in the logs. This means you need to be pretty familiar with the structure of the scheduler logs in order to search effectively for the lifecycle of a task that had a problem.

Some log statements like `Attempting to finish pod` do have the annotations for the pod, which include dag name, task name, and run_id, but others do not. For instance, `Event: podname-a2f2c1ac706 had an event of type DELETED` has no such annotations.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it - maybe even there might be a way to add it automatically for all such cases ?

**Comment by amoghrajesh** [comment]
@potiuk seems like the solution was not completed here. I would like to try my hand at it if it is available.

**Comment by potiuk** [comment]
Feel free
