### ISSUE TITLE
Detect and fail any command when db is not migrated

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#18323]
### Description

We had recently a number of questions from users who did not run `airflow db upgrade` and run airflow and it was failing because of missing columns etc. 

It was not entirely clear for new users that they should do it and I am fixing it in #18282 , however I think we should do better 

### Use case/motivation

I think we should check what migration is currently applied and fail any Airflow command that requires the DB hard with clear information that the DB is not migrated and what to do.

This should be rather easy, I think. Alembic keeps track of the migration and I believe it has already all the tools to determine "current migration" vs. "expected migration". 

### Related issues

#18282 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc:@kaxil  - WDYT? I do not know Alembic that well, but from what I understand, I believe this would be entirely possible to perform such a check and clearly raise error "Please migrate the db with `airflow db upgrade`  in case the migration revisiion is different than expected?

**Comment by bhavaniravi** [comment]
Yes, it's possible in the alembic. [Check this SO answer](https://stackoverflow.com/a/56085521/6340775)

A similar airflow snippet would look like, used `check_migrations` as a template

```
def compare_migrations():
    from alembic.runtime.migration import MigrationContext
    from alembic.script import ScriptDirectory

    config = _get_alembic_config()
    script_ = ScriptDirectory.from_config(config)
    with settings.engine.connect() as connection:
        context = MigrationContext.configure(connection)
        if context.get_current_revision() != script_.get_current_head():
            raise exceptions.DatabaseIsNotUpToDate('Upgrade the database.')
```

Do we do this check every time we start the webserver or scheduler?

**Comment by kaxil** [comment]
Yea we have something similar that we already use in the Helm Chart:  https://github.com/apache/airflow/blob/11621ce06616777f6709ffb7f029d733be78f297/airflow/utils/db.py#L622-L649

I will add that to the components

**Comment by uranusjr** [comment]
One minor thought (aside from we obviously can’t show this error for `airflow db upgrade) is maybe we need to provide an override mechanism for local development, it’s occasionally useful knowingly run things without full migration (to fix an existing migration for example).

**Comment by potiuk** [comment]
> One minor thought (aside from we obviously can’t show this error for `airflow db upgrade`) is maybe we need to provide an override mechanism for local development, it’s occasionally useful knowingly run things without full migration (to fix an existing migration for example).

Yep. Good call. And yeah. I was toying with the thought of enabling the check for `airflow db upgrade` just for the fun of it.

**Comment by uranusjr** [comment]
Another one https://github.com/apache/airflow/discussions/18368

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/18439
