### ISSUE TITLE
Docker Image with CentOS Base 

### ISSUE THREAD

**Issue by imamdigmi** [apache/airflow#18374]
### Description

as far as i know, currently Airflow only supports Debian as a base docker image, maybe it will be more flexible if airflow can use other linux distributions like CentOS, because some features in Cloud Provider (e.g Alibaba Cloud) requires CentOS base container image to enable some features

### Use case/motivation

we want to implement OSS (cloud object storage) as a Persistent Volume on Alibaba's cloud service provider, to use this feature we are required to use CentOS as the base container image used in Kubernetes.
what I'm thinking right now is to create a custom Airflow docker image using CentOS, is that the recommended solution? any other suggestions would be very valuable, thanks

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
> we are required to use CentOS as the base container image used in Kubernetes.

Can you provide a link to the documentation describing this requirement?  I find it strange that the Kubernetes infrastructure depends on the specific distribution in the container.

**Comment by imamdigmi** [comment]
In the instructions section and at the very last point, it says "Only the **CentOS** and Alibaba Cloud Linux 2 operating systems are supported." Like in the image below
![image](https://user-images.githubusercontent.com/10998240/134085768-e85ed14e-837f-49e6-9c6d-18f158911ca7.png)
https://www.alibabacloud.com/help/doc-detail/86543.htm?spm=a2c63.p38356.b99.356.6d7b4c7aCXkF7J

**Comment by potiuk** [comment]
I find it highly strange as well that only two OS-es are supported for any image I do not know Alibaba and OSS but I believe the limitation you mention is for the OSS "provided" volume. So basically you need to run CentOS or Alibaba to provide the volumes, not to use them. You can likely use those provided volumes in any docker-container, based on any  OS I believe (but I just briefly looked at it so I might be wronb)

But even if for whatever reason (though I repeat - I find it extremely unlikely), that you need to use CentOS, then you should build such an image yourself - it's rather easy to build a one-use Airflow image with your speciific requirements, it's much more complex to build a general, reusable solution, You can take Airflow Image as an inspiration, but do not count we will build multiple versions of those images based on different OSes. 

Airflow images are build as "reference" images, support many cases and ways of building the image and we do not plan or publish or support any other base images.
