### ISSUE TITLE
Upgrade google-api-python-client to 2.x.x

### ISSUE THREAD

**Issue by ValBerthe** [apache/airflow#18371]
### Description

As described [here](https://github.com/apache/airflow/blob/main/setup.py#L287), `google-api-python-client` has the `<2.0.0` requirement, which prevents the usage of nice QoL upgrades concerning the discovery cache of the client. This request is concerning the provider `apache-airflow-providers-google`.

More information on the upgrade [here ](https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md).

This migration to 2.x.x **does not induce breaking changes** (should be transparent).

### Use case/motivation

Newer version of `google-api-python-client` brings useful features regarding the discovery cache. 

https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md

### Related issues

None.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@ValBerthe assigned to you

**Comment by eladkal** [comment]
@ValBerthe are you still working on this issue?

**Comment by eladkal** [comment]
Will be tracked in https://github.com/apache/airflow/issues/27292
