### ISSUE TITLE
UI indication for parallelism, concurrency, or pool limit reached

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#18378]
### Description

On a dag's page in the web UI, show an indicator when the scheduling of tasks is being affected by limits on parallelism, concurrency, or a pool limit. The indicator should be relatively unobtrusive, as being affected by these things is not an error. I think it should also link to the appropriate section of the documentation describing the configuration element.

### Use case/motivation

A frequent question I hear is "why isn't my task running?" The first check is parallelism, concurrency, and pools. This is tedious and unintuitive for many people, especially because there is a whole matrix of these controls. 

Having a UI indication come up, clearly indicate which configuration element is impacting the dag scheduling and having a link to the description in the documentation would be very helpful in directing less experienced folks to be able to answer this question on their own.

### Related issues

Might be better fit with AIP-38

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
ice idea. I am not sure though if it's easy to implement due to how scheduler works. But maybe ?

**Comment by fritz-astronomer** [comment]
This is a feature that I regularly need to assist others with - there are many tuning options for both Global and DAG based parallelism, and it's _very_ obtuse why a task or DAG might not be being scheduled. The scheduler logs are very overwhelming for most people - and that's currently the only place to find this information.

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/38449
