### ISSUE TITLE
Multi Arch Airflow docker image

### ISSUE THREAD

**Issue by pixie79** [apache/airflow#18372]
### Description

Docker hub supports multi arch images. It would be good if the Airflow image could be updated to support arm64 as well to let it run in the latest Mac M1's

### Use case/motivation

M1 Mac's are becoming more popular for development, the current amd based image run slowly due to emulation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/15635
