### ISSUE TITLE
Color Blindness -  Color Schemas

### ISSUE THREAD

**Issue by neilor-mendes** [apache/airflow#18391]
### Description

Folks,

Can you please add an option to change the color schema for users who has a disfunction called color blindness? Specially the ones with red/green disorder (Deuteranomaly, Protanomaly, Protanopia  & deuteranopia). It is very difficult for us to decode if a task ran successfully or not.  

Below I'm sending a link explaining what is it and how to use an color palette to help us

https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/color-blindness/types-color-blindness

https://www.tableau.com/about/blog/examining-data-viz-rules-dont-use-red-green-together#:~:text=Use%20a%20colorblind%2Dfriendly%20palette%20when%20appropriate&text=For%20example%2C%20blue%2Forange%20is,blue%20to%20someone%20with%20CVD.

### Use case/motivation

Would be great to identify the task status only looking at the graph/tree view instead of checking the tooltip. Currently due to my color blindness is hard for me to decode if a task ran successfully or not!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
You can change the tasks colors. See perivious issue https://github.com/apache/airflow/issues/7843

**Comment by neilor-mendes** [comment]
Thanks @eladkal I'm gonna try it and let you know!

**Comment by bbovenzi** [comment]
Additional note: we will include more native support for color blind friendly palettes in AIP-38

**Comment by neilor-mendes** [comment]
Considering you guys are going to improve it and I was able to change colors I'm closing the issue.
Thanks for all your support folks.

**Comment by vmatt** [comment]
hey @neilor-mendes, you might be interested with an alternative approach where you can replace colors with symbols! 
It's created as a [userscript](https://greasyfork.org/en/scripts/518865-airflow-task-instance-status-enhancer). Let me know your thoughts! 
![image](https://github.com/user-attachments/assets/a68df1f1-80c5-4ba8-b059-5ef3ce85209b)

**Comment by neilor-mendes** [comment]
@vmatt it is a very interesting option!
