### ISSUE TITLE
AttributeError running airflow webserver

### ISSUE THREAD

**Issue by ahmad-musleh** [apache/airflow#184]
Hello

I am currently facing an issue running the following command:

```
      airflow webserver -p 8080
```

and I get the following Error:

airflow webserver -p 8080 

```
 ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 238, in webserver
    from airflow.www.app import app
  File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 17, in <module>
    from flask.ext.admin.contrib.sqla import ModelView
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 62, in load_module
    __import__(realname)
  File "/usr/local/lib/python2.7/dist-packages/flask_admin/contrib/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 90, in <module>
    packaging = pkg_resources._vendor.packaging
AttributeError: 'module' object has no attribute '_vendor'
```

Please note that I have changed the database settings and I had it running on a mysql server.

Thanks.

**Comment by mistercrunch** [comment]
What python version are you using?
`python --version`

**Comment by mistercrunch** [comment]
can you share the output of `pip freeze`?

**Comment by ahmad-musleh** [comment]
```
          pip freeze
```

adium-theme-ubuntu==0.3.4
aiohttp==0.16.5
airflow==1.2.0
alabaster==0.7.6
amqp==1.4.6
anyjson==0.3.3
apt-xapian-index==0.45
asyncio==3.4.3
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.0
billiard==3.3.0.20
boto==2.38.0
celery==3.1.18
certifi==2015.4.28
chardet==2.0.1
chartkick==0.4.2
colorama==0.2.5
command-not-found==0.3
cssselect==0.9.1
debtagshw==0.1
defer==1.0.6
dill==0.2.3
dirspec==13.10
Django==1.5.4
docutils==0.12
duplicity==0.6.23
Flask==0.10.1
Flask-Admin==1.2.0
Flask-Cache==0.13.1
Flask-Login==0.2.11
flower==0.8.2
futures==3.0.3
google-api-python-client==1.4.1
GoogleScraper==0.1.37
guppy==0.1.10
hive-thrift-py==0.0.1
html5lib==0.999
httplib2==0.8
itsdangerous==0.24
Jinja2==2.7.3
kombu==3.0.26
librabbitmq==1.6.1
lockfile==0.8
lxml==3.3.3
Markdown==2.6.2
MarkupSafe==0.23
mock==0.8.0
mps-youtube==0.2.5
MySQL-python==1.2.5
nose==1.3.7
numpy==1.9.2
oauth2client==1.4.12
oauthlib==0.6.1
oneconf==0.3.7
pafy==0.3.74
PAM==0.4.2
pandas==0.16.2
pexpect==3.1
Pillow==2.3.0
pinball==0.1.1
piston-mini-client==0.7.5
pluggy==0.3.0
protobuf==2.6.1
psycopg2==2.6.1
py==1.4.30
pyasn1==0.1.8
pyasn1-modules==0.0.6
pycrypto==2.6
pycups==1.9.66
pydot==1.0.28
Pygments==2.0.2
pygobject==3.12.0
pygoogle==0.6
PyHive==0.1.5
pyhs2==0.6.0
PyMySQL==0.6.6
pyOpenSSL==0.13
pyparsing==2.0.3
pyserial==2.6
pysmbc==1.0.14.1
PySmbClient==0.1.3
python-apt===0.9.3.5ubuntu1
python-dateutil==2.4.2
python-debian===0.1.21-nmu2ubuntu2
PyTrie==0.1
pytz==2013b0
pyxdg==0.25
PyYAML==3.11
qds-sdk==1.3.0
reportlab==3.0
requests==2.7.0
rsa==3.1.4
sasl==0.1.3
selenium==2.46.0
sessioninstaller==0.0.0
setproctitle==1.1.8
simplejson==3.7.3
six==1.9.0
snakebite==2.5.5
snowballstemmer==1.2.0
software-center-aptd-plugins==0.0.0
Sphinx==1.3.1
sphinx-argparse==0.1.15
Sphinx-PyPI-upload==0.2.1
sphinx-rtd-theme==0.1.8
SQLAlchemy==1.0.6
statsd==3.1
system-service==0.1.6
thrift==0.9.2
tornado==4.2
tox==2.1.1
Twisted-Core==13.2.0
Twisted-Web==13.2.0
unity-lens-photos==1.0
uritemplate==0.6
urllib3==1.7.1
virtualenv==13.1.0
Werkzeug==0.10.4
wheel==0.24.0
WTForms==2.0.2
xdiagnose===3.6.3build2
zope.interface==4.0.5

**Comment by mistercrunch** [comment]
related:
http://stackoverflow.com/questions/28967785/attribute-error-installing-with-pip

**Comment by ahmad-musleh** [comment]
I did that only to find the same problem.
I also uninstalled airflow and reinstalled it to find the same problem again. Turns out the error was in my DAGs folder. 

Thanks for the help.
