### ISSUE TITLE
helm chart: allow each component to have different custom pod annotations

### ISSUE THREAD

**Issue by wc-s** [apache/airflow#18400]
### Description

Currently, to inject custom annotations into airflow pods, we can use such a snippet in the `values.yaml`:
```
airflowPodAnnotations:
  my-annotation: "foo"
```

However, this will inject the annotation to the pods of all airflow components (scheduler.. worker.. etc.). There is no way to inject different annotations to different components.

It would be nice to be able to inject different annotations to different components with such a `values.yaml`:
```
workers:
  podAnnotations:
    my-annotation: "foo"

scheduler:
  podAnnotations:
    my-annotation: "bar"
```

### Use case/motivation

Generally, it's not a bad idea to make things more customizable to the chart users.

Specifically for my use case, the motivation is because we are using vault sidecar to inject secrets into our airflow pods: https://www.vaultproject.io/docs/platform/k8s/injector#secrets-via-annotations

And we wish to have different vault connection settings for the different pods.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
assigned you. Seems a good feature to have.

**Comment by wc-s** [comment]
Hey, @potiuk , I've opened a PR here: https://github.com/apache/airflow/pull/18481, with unit tests passing locally.

Could you advise on how I should proceed from here? Thanks. From what I can see, I need an approval to even get the pipeline started.
