### ISSUE TITLE
Add a 'View' button for Airflow Variables in the UI

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#18436]
### Description

A 'view' (eye) button is added to the Airflow Variables in the UI. This button shall open the selected Variable for viewing (but not for editing), with the actual json formatting, in either a new page or a modal view.

### Use case/motivation

I store variables in the json format, most of them have > 15 attributes. To view the content of the variables, I either have to open the Variable in editing mode, which I find dangerous since there is a chance I (or another user) accidentally delete information; or I have to copy the variable as displayed in the Airflow Variables page list and then pass it through a json formatter to get the correct indentation. I would like to have a way to (safely) view the variable in it's original format.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Yes, a way to see variables without editing them sounds like a good idea.

**Comment by aa3pankaj** [comment]
I would like to work on this issue.

**Comment by potiuk** [comment]
Assigned you!
