### ISSUE TITLE
Can't Run Tasks from UI when using CeleryKubernetesExecutor

### ISSUE THREAD

**Issue by mrbungie** [apache/airflow#18440]
### Apache Airflow version

2.1.3

### Operating System

ContainerOS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.1.0
apache-airflow-providers-celery==2.0.0
apache-airflow-providers-cncf-kubernetes==2.0.2
apache-airflow-providers-databricks==2.0.1
apache-airflow-providers-docker==2.1.0
apache-airflow-providers-elasticsearch==2.0.2
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-google==5.0.0
apache-airflow-providers-grpc==2.0.0
apache-airflow-providers-hashicorp==2.0.0
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-microsoft-azure==3.1.0
apache-airflow-providers-mysql==2.1.0
apache-airflow-providers-papermill==2.0.1
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-redis==2.0.0
apache-airflow-providers-sendgrid==2.0.0
apache-airflow-providers-sftp==2.1.0
apache-airflow-providers-slack==4.0.0
apache-airflow-providers-sqlite==2.0.0
apache-airflow-providers-ssh==2.1.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Official Helm Chart on GKE using CeleryKubernetesExecutor.

### What happened

I'm unable to Run Tasks from the UI when using CeleryKubernetesExecutor. It just shows the error "Only works with the Celery or Kubernetes executors, sorry". 
<img width="1792" alt="Captura de Pantalla 2021-09-22 a la(s) 17 00 30" src="https://user-images.githubusercontent.com/2586758/134413668-5b638941-bb50-44ff-9349-d53326d1f489.png">

### What you expected to happen

It should be able to run Tasks from the UI when using CeleryKubernetesExecutor, as it only is a "selective superset" (based on queue) of both the Celery and Kubernetes executors.

### How to reproduce

1. Run an Airflow instance with the CeleryKubernetes executor.
2. Go to any DAG
3. Select a Task
4. Press the "Run" button.
5. Check the error.

### Anything else

I will append an example PR as a comment.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
For anyone looking to fix this: It looks like we'd need to update `valid_celery_config` or `valid_kubernetes_config` here: https://github.com/apache/airflow/blob/main/airflow/www/views.py#L1556

**Comment by potiuk** [comment]
Nice catch!

**Comment by potiuk** [comment]
Just in case - added a fix :)
