### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by Raydrrrr1234** [apache/airflow#18474]
### Description

Airflow is a great software. I use it intensively in my current work. But I wonder why the webserver is running without other language support? Isn't it nice to switch between different language for different country?

### Use case/motivation

I want to add Chinese to airflow. I am professional in Chinese and Japanese. I would like to add a switch to change webserver to Chinese and Japanese.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
We have an open issue for localization of the UI : https://github.com/apache/airflow/issues/9864
I'm closing as duplicate.
Feel free to comment in https://github.com/apache/airflow/issues/9864
