### ISSUE TITLE
Helm chart schema error for images.useDefaultImageForMigration property

### ISSUE THREAD

**Issue by AdrianLsk** [apache/airflow#18477]
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.1.2

### Kubernetes Version

1.21.4

### Helm Chart configuration

Using `images.useDefaultImageForMigration=true` altogether with my own image set in `images.airflow.{repository,tag,pullPolicy}`

### What happened

Tried to use my own airflow image ONLY for scheduler,webserver and worker hence I used  `images.useDefaultImageForMigration=true` in values.yaml. This yielded a schema validation error

```images: Additional property useDefaultImageForMigration is not allowedimages: Additional property useDefaultImageForMigration is not allowed```

### What you expected to happen

No error. Image correctly assigned to only webserver,scheduler and worker resources 

### How to reproduce

Set values.yaml to `images.useDefaultImageForMigration=true` altogether with your own image for airflow 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kaxil** [comment]
`useDefaultImageForMigration` is only available in the `main` branch not `1.1.0` of the chart. This will be available in Helm Chart 1.2.0 that should be released in next 4-5 days.

Use https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html to check what's available in latest stable version of the chart

**Comment by AdrianLsk** [comment]
Thanks for the info about the release date and sorry for the false alarm. I must have looked at the wrong branch.
