### ISSUE TITLE
No SQL error shown when using the JDBC operator

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#18482]
### Apache Airflow version

2.2.0b1 (beta snapshot)

### Operating System

Debian buster

### Deployment

Astronomer

### Deployment details

astro dev start
Dockerfile - https://gist.github.com/jyotsa09/267940333ffae4d9f3a51ac19762c094#file-dockerfile

### What happened

Both connection pointed to the same database where table "Person" doesn't exist.

When there is a SQL failure in PostgressOperator then logs are saying - 
```
psycopg2.errors.UndefinedTable: relation "person" does not exist
LINE 1: Select * from Person
```

When there is a SQL failure in JDBCOperator then logs are just saying -
```
[2021-09-23, 19:06:22 UTC] {local_task_job.py:154} INFO - Task exited with return code
```

### What you expected to happen

JDBCOperator should show "Task failed with exception" or something similar to Postgress.

### How to reproduce

Use this dag - https://gist.github.com/jyotsa09/267940333ffae4d9f3a51ac19762c094 
(Connection extras is in the gist.)

### Anything else

Related: https://github.com/apache/airflow/issues/16564

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by subkanthi** [comment]
@potiuk I can try this out.

**Comment by kaxil** [comment]
@subkanthi assigned it to you, go for it

**Comment by uranusjr** [comment]
I remember chatting with another developer on this. Note that this seems to be problem specific to JDBC; after #16805 (the PR fixing #16564), most task errors can correctly be logged—but not JDBC. In fact, the JDBC error does not even go through the code path implemented in the PR; when using JDBCOperator, you get *no errors at all*, not the *Task failed with exception* message an exception would normally trigger (for example, the Postgres example above would emit this log). My current hypothesis is JDBC (or the operator/hook) is swallowing the exception somehow and the scheduler never actually received it, let alone logging.

**Comment by subkanthi** [comment]
Im having trouble getting the jar working for the JDBC connection, unassigning.
