### ISSUE TITLE
airflow

### ISSUE THREAD

**Issue by Cyan-Zheng** [apache/airflow#18515]
### Apache Airflow version

2.0.1

### Operating System

linux

### Versions of Apache Airflow Providers

airflow=2.0.1

### Deployment

Other

### What happened

I installed airflow=2.0.1 and started the web server and then see below errors:

-----------------------------------------------------------------------------------------------------------------------

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.10
Airflow version: 2.0.1
Node: ip-10-15-61-128.ap-southeast-1.compute.internal
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/lib/python3.7/site-packages/flask/sessions.py", line 387, in save_session
    samesite=samesite,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 479, in set_cookie
    samesite=samesite,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/http.py", line 1217, in dump_cookie
    raise ValueError("SameSite must be 'Strict', 'Lax', or 'None'.")
ValueError: SameSite must be 'Strict', 'Lax', or 'None'.

-----------------------------------------------------------------------------------------------------------------------

I did the trick to comment out line 1216 and line 1217 in /usr/local/lib/python3.7/site-packages/werkzeug/http.py, this makes my web server accessible for now. But the UI looks wierd:

![image](https://user-images.githubusercontent.com/28339089/134766467-e6730b00-06d7-43ef-9ad4-f28a1a18645e.png)

### What you expected to happen

To fix the error more properly, and be able to visit the normal UI.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Duplicale of #17620

You likely did not follow the installation instructions and did not use constraints: https://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-script
