### ISSUE TITLE
Allow to set execution_timeout default value in airflow.cfg

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#18578]
### Discussed in https://github.com/apache/airflow/discussions/18411

<div type='discussions-op-text'>

<sup>Originally posted by **alexInhert** September 21, 2021</sup>
### Description

Currently the default value of execution_timeout in base operator is None
https://github.com/apache/airflow/blob/c686241f4ceb62d52e9bfa607822e4b7a3c76222/airflow/models/baseoperator.py#L502

This means that a task will run without limit till finished.

### Use case/motivation

The problem is that there is no way to overwrite this default for all dags. This causes problems where we find that tasks run sometimes for 1 week!!! for no reason. They are just stuck. This mostly happens with tasks that submit work to some 3rd party resource. The 3rd party had some error and terminated but the Airflow task for some reason did not.

This can be handled in cluster policy however it feels that cluster policy is more to enforce something but less about setting defaults values.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by potiuk** [comment]
cc: @alexinhert

**Comment by potiuk** [comment]
Details in #18411

**Comment by Ayushsunny** [comment]
Hello, @potiuk I would like to work on this.
Could you guide me more on this?

**Comment by potiuk** [comment]
> Hello, @potiuk I would like to work on this. Could you guide me more on this?

Just read the discusion in #18411 i think @alexInhert explained it in the last comment -and maybe he can provide more guidance if needed?

**Comment by eladkal** [comment]
@zevaverbach are you still working on this issue?

**Comment by zevaverbach** [comment]
Oh darn, to be honest I think I over-committed. Can you please unassign me?

**Comment by dillonjohnson** [comment]
I'd be glad to take this one over.
@eladkal

**Comment by eladkal** [comment]
> I'd be glad to take this one over. @eladkal

Assigned

**Comment by eladkal** [comment]
@dillonjohnson are you still working on this issue?

**Comment by dillonjohnson** [comment]
Yes. Sorry.
I just need to test a little bit more.
Will try to wrap it up soon. @eladkal

**Comment by dillonjohnson** [comment]
On second thought, have had some stuff come up and I'm having tons of issues with the various tests failing (not sure why).
I think I'll have to pass it off. Sorry about that. @eladkal
