### ISSUE TITLE
Current task instances state remains unchanged after updating the state to success/failed through API

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#18579]
### Apache Airflow version

2.2.0b2 (beta snapshot)

### Operating System

Debian buster

### Deployment

Astronomer

### Deployment details

Astro dev start

### What happened

Current task instance state remains unchanged after updating the state to success/failed through API. Also if the "include_past" in payload is true then Its updating the states of past task instances not the current task instances.

### What you expected to happen

Task Instances state should update as per the state mentioned in the payload and also downstream tasks in upstream_failed state should automatically clear.

### How to reproduce

API end point- 
```
dags/{{dag_id}}/updateTaskInstancesState
```
Payload- 
```
{
"dry_run": false,
"task_id": "{{task_id}}",
"execution_date": "{{dag_execution_date}}",
"include_upstream": false,
"include_downstream": true,
"include_future": false,
"include_past": false,
"new_state": "success"
}
```

### Anything else

It's giving me 200 as well for the case where I am passing non existing execution date in payload.
Related - https://github.com/apache/airflow/pull/16539

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kaxil** [comment]
cc @ephraimbuddy

**Comment by ephraimbuddy** [comment]
This endpoint works as expected except that it runs even if the execution date does not hold.

**Comment by ephraimbuddy** [comment]
> This endpoint works as expected except that it runs even if the execution date does not hold.

@jyotsa09 can you verify? If you set `include_past:true`, the current task instance is not included and that's how the UI works too. Is this the correct behaviour? @ashb @kaxil

**Comment by ephraimbuddy** [comment]
Closing this as the API works the same way as the UI and #18642 is now merged
