### ISSUE TITLE
vertical spacing between tasks has increased significantly in Graph View

### ISSUE THREAD

**Issue by stephenonethree** [apache/airflow#18587]
### Apache Airflow version

2.1.2

### Operating System

Multiple (Mac and Cloud Composer)

### Versions of Apache Airflow Providers

apache-airflow-providers-postgres = "==2.0.0"

### Deployment

Composer

### Deployment details

composer-1.17.1-airflow-2.1.2
 

### What happened

This is related to Graph View in the Airflow UI. Parallel tasks used to be relatively tightly-spaced (vertically speaking), but now there is a pretty large amount of whitespace between them. I'm not sure if this is an intended feature, but it makes browsing more difficult when you have a lot of parallel tasks. (The spacing seems to always be the same, it's just much more annoying when you have a lot of parallel tasks, think 30-50)

I'm not sure if this started when I turned RBAC on or when I upgraded to the 2.x release, but it wasn't a problem in 1.10.15 with RBAC off.

It would be nice to reduce the spacing a bit, or give us the ability to tweak the vertical separation ourselves in the Airflow config. 

See following image for an example of the amount of whitespace. Note that these stacked tasks extend quite a ways upward/downward, so to see everything I have to zoom out much more than before.

<img width="264" alt="Screen Shot 2021-09-28 at 3 45 40 PM" src="https://user-images.githubusercontent.com/66647680/135157162-32c08fa6-3c2c-4fc7-a0ff-6072c3097dbd.png">

### What you expected to happen

When tasks are stacked vertically because they are parallel, I want less whitespace between them so I don't have to zoom way out to see all of them.

### How to reproduce

Create a DAG with a large number of parallel tasks and look at it in Graph View.

### Anything else

Note that this occurs in Airflow 2.1.2 in both my local (Mac) installation and in my Composer installation. I think it started happening either with RBAC or with Airflow 2.x.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@ryanahamilton You updated the styling for the graph view a little while back. Was the extra spacing for labels? I'm curious to hear your opinion.

**Comment by ryanahamilton** [comment]
> @ryanahamilton You updated the styling for the graph view a little while back. Was the extra spacing for labels? I'm curious to hear your opinion.
> 
> From the commit message where vertical spacing was changed: (#15257) `` - Slightly increases the vertical node separation (`nodeSep`) to make the graphs feel a little less crowded. This also reduces the amount that the task nodes overlap with the edges. ``

Yeah [the `nodeSep` value](https://github.com/astronomer/airflow/blob/3bfb2312043e51cca4c75ce03fdce25b6a647d35/airflow/www/templates/airflow/graph.html#L162) was doubled from `15` to `30` to prevent overlapping of nodes and edges. I suppose we could test a smaller number in between?

**Comment by bbovenzi** [comment]
Closing since we have a new graph view.
