### ISSUE TITLE
SerializedDagNotFound - when create 1000 dags 

### ISSUE THREAD

**Issue by denysivanov** [apache/airflow#18598]
### Apache Airflow version

2.1.3

### Operating System

Linux

### Deployment

Other

### Deployment details

Community Helm chart 8.0.8

### What happened

I have created 1000 dags like that 

**test_AIR10001.py** 
...
**test_AIR11001.py** 

After wait period of 5 minutes try to open any dag and can't.
Here is an exception details: https://sentry.io/share/issue/b97fca62ccec47709e814e70deb3e4ba/

If I try do do 5 dags like that I do not have this issue.

### What you expected to happen

I expect dags would be loaded to Ariflow without any issue

### How to reproduce

**dag code**

```
import numpy as np
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime
from src.helpers import dag_helper

with DAG(
    dag_id=dag_helper.get_dag_id_from_path(__file__),
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    catchup=False,
    tags=["example"]
) as dag:
    def print_array():
        """Print Numpy array."""
        a = np.arange(15).reshape(3, 5)
        print(a)
        time_wait_cuy = dag_helper.get_time_wait_cuy()
        print(time_wait_cuy)
        return time_wait_cuy


    run_this = PythonOperator(
        task_id="print_the_context",
        python_callable=print_array,
    )
```

**Here is dag_helper**

```
import os
from pathlib import Path


def get_time_wait_cuy():
    return os.environ['environment']


def get_dag_id_from_path(dag_file_path):
    path = Path(dag_file_path)
    stem = path.stem
    trimmed_path = Path(*path.parts[5:len(path.parts) - 1])
    prefix = str(trimmed_path).replace(os.path.sep, '_')
    return '__'.join([prefix, stem])

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by khalidmammadov** [comment]
I have modified your Dag a bit and produced 1000 copy of it.  And scheduler processed it without any issues:

=====================================================
```
import numpy as np
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime
import os
from pathlib import Path
import uuid

with DAG(
    dag_id=Path(__file__).stem,
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    catchup=False,
    tags=["example"]
) as dag:
    def print_array():
        """Print Numpy array."""
        a = np.arange(15).reshape(3, 5)
        print(a)
        time_wait_cuy = get_time_wait_cuy()
        print(time_wait_cuy)
        return time_wait_cuy


    run_this = PythonOperator(
        task_id="print_the_context",
        python_callable=print_array,
    )
```
=====================================================

And bash command to make it 1000

`for i in {1..1000} ; do echo $('cp' my_dag.py "my_dag$i.py") ; done`

Is it possible the issue is related to your setup i.e. files, folder etc.? 
If not can you please help to reproduce the issue so we can investigate?

**Comment by denysivanov** [comment]
@khalidmammadov I do not have an issue when I am not referencing a helper class.
Issue is exists only when you reference helper.

Here is my helper - when you use helper you would see an issue.

```
import os
from pathlib import Path


def get_time_wait_cuy():
    return os.environ['environment']


def get_dag_id_from_path(dag_file_path):
    path = Path(dag_file_path)
    stem = path.stem
    trimmed_path = Path(*path.parts[5:len(path.parts) - 1])
    prefix = str(trimmed_path).replace(os.path.sep, '_')
    return '__'.join([prefix, stem])


```

**Comment by khalidmammadov** [comment]
sure things, let me take a look and will revert

**Comment by khalidmammadov** [comment]
Did just that. Freshly installed 2.3.1, created dag from your code with one import with helper module and functions that reference in the dag and duplicated Dag by 1000. The scheduler consumed all 1000 of them and I checked from UI. But couldn't reproduce issue the issue:
```
my_dag197.py.log   my_dag298.py.log  my_dag399.py.log  my_dag49.py.log   my_dag5.py.log    my_dag700.py.log  my_dag801.py.log  my_dag902.py.log
my_dag198.py.log   my_dag299.py.log  my_dag39.py.log   my_dag4.py.log    my_dag600.py.log  my_dag701.py.log  my_dag802.py.log  my_dag903.py.log
my_dag199.py.log   my_dag29.py.log   my_dag3.py.log    my_dag500.py.log  my_dag601.py.log  my_dag702.py.log  my_dag803.py.log  my_dag904.py.log
my_dag19.py.log    my_dag2.py.log    my_dag400.py.log  my_dag501.py.log  my_dag602.py.log  my_dag703.py.log  my_dag804.py.log  my_dag905.py.log
my_dag1.py.log     my_dag300.py.log  my_dag401.py.log  my_dag502.py.log  my_dag603.py.log  my_dag704.py.log  my_dag805.py.log  my_dag906.py.log
(venv_airflow) air213@linux:~/airflow/logs/scheduler/latest$ ls | wc
   1002    1002   16919
(venv_airflow) air213@linux:~/airflow/logs/scheduler/latest$ cat my_dag* | grep SerializedDagNotFound
(venv_airflow) air213@linux:~/airflow/logs/scheduler/latest$ airflow version
2.1.3
(venv_airflow) air213@linux:~/airflow/logs/scheduler/latest$ 
```

Need some more info for further investigation.

**Comment by denysivanov** [comment]
@khalidmammadov I did some tests on my side and it is environmental issue on my end. 

Thanks for support.

**Comment by potiuk** [comment]
What kind of issue? We would love to learn from that :)

**Comment by denysivanov** [comment]
@potiuk 

Currently I have in PROD 186 dags.
I would have around 500 by new year + 500 - 1000 dags during 2022.

We set up Grafana in prod and I see that DAG processing total parse time is 4.8 minutes.
I looked up this article https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html and tried  to play with it in QA. 

I created a copy of 1000 dags from that sample and did some tests in my QA

You can see details here 
[DAG load process.docx](https://github.com/apache/airflow/files/7289250/DAG.load.process.docx)
 
Surprisingly those details are very different from the case when I am running it locally.
And moreover they are not what article describes ... 

Here is how my environment look like in QA & PROD
![image](https://user-images.githubusercontent.com/7118801/136101338-154ae2f1-68e3-4052-a4ed-b20be419fb33.png)

In case of QA & PROD I am getting my variables from HashiCorp Vault.

For DEV it is local. 
I do not expect that it should be matter but it is... 


So currently I am not traveling to HashiCorp vault and take parameters from local environment 
+ 
I did 

min_file_process_interval = 300
dag_dir_list_interval = 300 
scheduler_parsing_processes = 4 

and this addressed my issue 

(I do not produce dynamic dags so after deploy I am not touching them at all)

This change brought DAG processing total parse time from 4.8 minutes to 3.3 seconds. 

Let me know if you have to add anything here from your perspective :) 

Thanks a lot for your help. 
I do really appreciate it.

**Comment by potiuk** [comment]
This is fantastic! Maybe you'd like to write a blog post on it  - we could publish it at https://medium.com/apache-airflow?

**Comment by denysivanov** [comment]
@potiuk I can if you are talking about my set up :) 

But I am still do not have real answer why it behaves differently in my environment.

**Comment by denysivanov** [comment]
@potiuk I do realize this but in my example https://github.com/apache/airflow/files/7289250/DAG.load.process.docx
I tried this in different way and it doesn't work as I would expect. Just see code and results.
