### ISSUE TITLE
datadog parsing error for dagrun.schedule_delay since it is not passed in float type

### ISSUE THREAD

**Issue by coinzerge** [apache/airflow#18599]
### Apache Airflow version

2.1.2

### Operating System

Gentoo/Linux

### Deployment

Docker-Compose

### What happened

In datadog-agent logs, got parsing error

[ AGENT ] 2021-09-29 03:20:01 UTC | CORE | ERROR | (pkg/dogstatsd/server.go:411 in errLog) | Dogstatsd: error parsing metric message '"airflow.dagrun.schedule_delay.skew:<Period [2021-09-29T03:20:00+00:00 -> 2021-09-29T03:20:00.968404+00:00]>|ms"': could not parse dogstatsd metric value: strconv.ParseFloat: parsing "<Period [2021-09-29T03:20:00+00:00 -> 2021-09-29T03:20:00.968404+00:00]>": invalid syntax

### What you expected to happen

since datadog agent expects a float, see https://github.com/DataDog/datadog-agent/blob/6830beaeb182faadac40368d9d781b796b4b2c6f/pkg/dogstatsd/parse.go#L119, the schedule_delay should be a float instead of timedelta.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Maybe you would like to take a stab and fix it @coinzerge ? Seems like really simple fix and good first issue?

**Comment by lostkamp** [comment]
Hello,
I'm willing to work on this. Would be my first contribution though, so I might need some guidance.

**Comment by potiuk** [comment]
Feel free!

**Comment by lostkamp** [comment]
thanks @potiuk 
Sorry, I didn't realize that there is already a PR open for this issue. Should I fork the repo from @coinzerge and try to fix the tests?

**Comment by potiuk** [comment]
why not - but try talk to @coinzerge first maybe :)

**Comment by lostkamp** [comment]
Sorry, I'm a Github noob, but it seems like you cannot send DMs on Github. So I'm not sure how I am supposed to contact @coinzerge . I have submitted a PR now that includes the changes from the previos PR and fixes the test (hopefully).

**Comment by potiuk** [comment]
That's enough if you make a comment, if @coinzerge does not respond  in a day or two - just take it over.

**Comment by lostkamp** [comment]
Alright. I have opened a PR and am just waiting for a code review now. Should I ask anyone in particular for this?

**Comment by potiuk** [comment]
Which PR?

**Comment by lostkamp** [comment]
https://github.com/apache/airflow/pull/19973
