### ISSUE TITLE
Selecting DAG in search dropdown should lead directly to DAG

### ISSUE THREAD

**Issue by edwardwang888** [apache/airflow#18600]
### Description

When searching for a DAG in the search box, the dropdown menu suggests matching DAG names. Currently, selecting a DAG from the dropdown menu initiates a search with that DAG name as the search query. However, I think it would be more intuitive to go directly to the DAG.

If the user prefers to execute the search query, they can still have the option to search without selecting from the dropdown.

---

Select `example_bash_operator` from dropdown menu:

![image](https://user-images.githubusercontent.com/40527812/135201722-3d64f46a-36d8-4a6c-bc29-9ed90416a17f.png)

---
We are taken to the search result instead of that specific DAG:

![image](https://user-images.githubusercontent.com/40527812/135201941-5a498d75-cff4-43a0-8bcc-f62532c92b5f.png)

### Use case/motivation

When you select a specific DAG from the dropdown, you probably intend to go to that DAG. Even if there were another DAG that began with the name of the selected DAG, both DAGs would appear in the dropdown, so you would still be able to select the one that you want.

For example:
![image](https://user-images.githubusercontent.com/40527812/135202518-f603e1c5-6806-4338-a3d6-7803c7af3572.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Makes sense. Hopefully FAB doesn't make this too annoying to change.

**Comment by edwardwang888** [comment]
@bbovenzi Is this something that would make more sense to implement after AIP-37 - would it need to be refactored later anyways?

**Comment by uranusjr** [comment]
AIP-37 is still quite far away though; if you have any intention to use this feature yourself in close future, it's better to try implement it in F.A.B. first.

**Comment by bbovenzi** [comment]
I agree. Minor improvements should not wait on AIP-38.

**Comment by edwardwang888** [comment]
Sounds good. I will give it a try.

**Comment by edwardwang888** [comment]
@bbovenzi The PR above is ready for review when you get a chance!
