### ISSUE TITLE
The cleared dagrun and tasks are set failed by scheduler

### ISSUE THREAD

**Issue by doowhtron** [apache/airflow#18628]
### Apache Airflow version

2.1.2

### Operating System

centos7.5.1804

### Versions of Apache Airflow Providers

apache-airflow-providers-mysql==1.0.0

### Deployment

Virtualenv installation

### Deployment details

I have four VMs, each deployed with a webserver, a scheduler and a celery worker.

To gain real-time scheduling ability, I just such configs in airflow.cfg:

scheduler_heartbeat_sec=1
processor_poll_interval = 0
dag_dir_list_interval=0
parsing_processes=20
...

### What happened?

I have a dag which has 6 tasks and runs every 10 mins. One of the task might fail so I have a monitor script to mark success and clear the downstream task.  But eventually the successor downstream tasks will finish upstream_failed and the dag_run failed. 

![企业微信截图_16329873154661](https://user-images.githubusercontent.com/4937178/135409166-184d7ab1-e8f0-46a4-9183-e4ba3ad8ed28.png)

As shown in the above screenshot, the 'failed' possibility is about 50%

I checked the source codes and logs and found the upstream_failed tasks were set_state by the scheduler running on an other VM using pysnooper.

`task_instance_scheduling_decisions -> _get_ready_tis -> are_dependencies_met -> get_failed_dep_statuses -> get_dep_statuses -> _get_dep_statuses -> _evaluate_trigger_rule: ti.set_state(State.UPSTREAM_FAILED, session) `

### How I fix it

I think the state changing stage of ti and dagrun in the clear operation might be conflict with the decision-making stage in the scheduler. So it should be a critical-section problem and be solved by using row locks.

**airflow/models/dags**
![dag](https://user-images.githubusercontent.com/4937178/135415180-6efb2178-8aeb-4344-b95f-d2eacfbb94f4.png)

**airflow/models/taskinstance.py**
![taskintance](https://user-images.githubusercontent.com/4937178/135415179-f4a13c01-e618-486d-a611-b0c195b43fa6.png)

Now my problem is fixed.

### What you expected to happen

The clear operator should not be conflict with the schedulers.

### How to reproduce

As I described above...

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by doowhtron** [comment]
Is there an instruction to submit a PR?

**Comment by potiuk** [comment]
> Is there an instruction to submit a PR?

https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#id3
