### ISSUE TITLE
Auto-refresh doesn't take into account the selected date

### ISSUE THREAD

**Issue by peloyeje** [apache/airflow#18632]
### Apache Airflow version

2.1.3

### Operating System

Debian GNU/Linux 9 (stretch)

### Deployment

Other Docker-based deployment

### What happened

In the DAG tree view, if I select a custom date in the date filter (top left corner) and press "update", DAG runs are correctly filtered to the selected date and number of runs.
 
However, if the "auto-refresh" toggle is on, when the next tick refresh happens, the date filter is no longer taken into account and the UI displays the actual **latest** x DAG runs status. However, neither the header dates (45° angle) nor the date filter reflect this new time window 

I investigated in the network inspector and it seems that the xhr request that fetches dag runs status doesn't contain a date parameter and thus always fetch the latest DAG run data

### What you expected to happen

I expect that the auto-refresh feature preserves the selected time window

### How to reproduce

Open a DAG with at least 20 dag runs
Make sure autorefresh is disabled
Select a filter date earlier than the 10th dag run start date and a "number of runs" value of 10, press "update"
The DAG tree view should now be focused on the 10 first dag runs
Now toggle autorefresh and wait for next tick
The DAG tree view will now display status of the latest 10 runs but the header dates will still reflect the old start dates

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Makes sense to me. It should be relatively easily to just pass the dat in `tree.js` [here](https://github.com/apache/airflow/blob/main/airflow/www/static/js/tree.js#L433). I believe the webserver code is already built to handle the `base_date`

**Comment by peloyeje** [comment]
Yep exactly, I looked around and I was planning on adding the base date as a meta tag in the html template in order to match the current implementation. If that's fine by you I'll submit a PR in the next couple of days :)

**Comment by sbialkowski-pixel** [comment]
I will add my observation :)
Refresh button also cause this problem.
Raw view (without day/time filter in he left corner:
![Zrzut ekranu 2021-10-30 111252](https://user-images.githubusercontent.com/60385441/139527335-9b482ed4-5f0f-4761-9b49-42c058e48db5.png)
After filter apply (button update)
![Zrzut ekranu 2021-10-30 111309](https://user-images.githubusercontent.com/60385441/139527337-dea3411f-1b17-44f9-9fad-f808aae46f25.png)
After refresh button click
![Zrzut ekranu 2021-10-30 111329](https://user-images.githubusercontent.com/60385441/139527334-887429ef-5310-4bf8-af1f-0cb6c0b18594.png)

Legend respects day/time filter but taskInstances not :)

**Comment by bbovenzi** [comment]
@peloyeje do you still want to take this on or should I finish this out? Quite a bit changed with #18675
