### ISSUE TITLE
Pendulum 1.x -> 2.x with Airflow 1.x -> 2.x Documentation Updates

### ISSUE THREAD

**Issue by agrubb86** [apache/airflow#18634]
### Describe the issue with documentation

With the upgrade from Pendulum 1.x to 2.x that coincides with upgrading from Airflow 1.x to 2.x, there are some breaking changes that aren't mentioned here:
[Upgrading from 1.x to 2.x](https://airflow.apache.org/docs/apache-airflow/stable/upgrading-from-1-10/index.html)

The specific breaking change I experienced is the .copy() method is completely removed in Pendulum 2.x. It turns out this isn't needed in my case as each macro that provides a pendulum.Pendulum provides a brand new instance, but it still caught me by surprise.

I also noticed that the stable documentation (2.1.4 at time of writing) for macros still links to Pendulum 1.x:
[Macros reference](https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html)

Specifically the macros: execution_date, prev_execution_date, prev_execution_date_success, prev_start_date_success, next_execution_date

**EDIT**
Another breaking change: .format() now defaults to the alternative formatter in 2.x, meaning 
`execution_date.format('YYYY-MM-DD HH:mm:ss', formatter='alternative')`
now throws errors.

### How to solve the problem

The macros reference links definitely need to be changed to Pendulum 2.x, maybe it would be a nice-to-have in the 1.x -> 2.x documentation but I was effectively using .copy() in a misguided way so I wouldn't say it's totally necessary.

**EDIT**
I think it's worth including that 
`execution_date.format('YYYY-MM-DD HH:mm:ss', formatter='alternative')`
will throw errors in the 1.x -> 2.x upgrade documentation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
The `format` function in Pendulum 2.x does not accept the `formatter` argument at all.

**Comment by 1nF0rmed** [comment]
@uranusjr In that case, should we avoid adding it in the upgrade documentation? and just focus on updating the pendulum references?

Also, could you point me to where I would have to make changes for the same? 
Thanks
