### ISSUE TITLE
Refactor OpsgenieAlertHook to official python sdk

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#18641]
### Body

Currently [OpsgenieAlertHook](https://github.com/apache/airflow/blob/d79f506213297dc0dc034d6df3226361b6f95d7a/airflow/providers/opsgenie/hooks/opsgenie_alert.py#L29) works with HTTP.
We should change the hook to work with the [official python sdk](https://github.com/opsgenie/opsgenie-python-sdk)

This will allow also to easily integrate to airflow the various methods and options the SDK has to offer
https://github.com/opsgenie/opsgenie-python-sdk#documentation-for-api-endpoints

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Arun-kc** [comment]
Can I help in any way? @eladkal

**Comment by eladkal** [comment]
> Can I help in any way? @eladkal

If you want to work on it... Its all yours

**Comment by fernandobugni** [comment]
Sorry. if there is no one working on it, I am free to take it or to help :) @eladkal @Arun-kc

**Comment by Arun-kc** [comment]
> Sorry. if there is no one working on it, I am free to take it or to help :) @eladkal @Arun-kc

Sure thing, I didn't get much time to check up on this, so was not able to follow up on this till now.

**Comment by eladkal** [comment]
@fernandobugni assigned to you

**Comment by pierrejeambrun** [comment]
Hello @eladkal and @Arun-kc,

There hasn't been much activity on this one lately and I wanted to give this one a try, I hope you don't mind guys.

You can find a first draft of the PR [here](https://github.com/apache/airflow/pull/20263)
