### ISSUE TITLE
DagFileProcessor running continuously for DAG file (non-UTC system time)

### ISSUE THREAD

**Issue by brki** [apache/airflow#18674]
### Apache Airflow version

2.1.3

### Operating System

Redhat 6.10

### Deployment

Virtualenv installation

### What happened

When deploying an updated version of a DAG, I noticed that there was higher CPU usage, and a new process was starting every few seconds:
```
airflow  31449 76.0  0.1 935636 79236 ?        Rl   17:04   0:00  airflow scheduler - DagFileProcessor /path/to/the/dag_file.py
```

Note: there are many DAGs in this directory, only this file was being continually scanned by the DagFileProcessor.
The other files would be scanned every 5 minutes or so, which agrees with the airflow configuration.

Eventually I guessed that it might be related to a difference between the UTC time and the local system time (Central Europe, e.g. Berlin).

Running 
```
touch -d "1 day ago" /path/to/the/dag_file.py 
```
stopped the continuous scanning of the file.

But after running
```
touch /path/to/the/dag_file.py 
```
the continuous scanning started again.

### What you expected to happen

When a new or updated file appears, I'd expect Airflow to notice, "hey, there's a new or updated file, I'll scan it".   But not scan it again and again.

### How to reproduce

Run Airflow on a system with non-UTC time, specifically 'Europe/Berlin'.

Deploy a new or updated DAG.

Notice that there's a DagFileProcessor process running very often (every second or so there's a new process).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nikochiko** [comment]
This issue exists when the last updated timestamp of a file is greater than current time (when I tried `touch -d 'tomorrow' example-dag.py`).

But, I wasn't able to get this issue by setting the system time to another timezone. I am running a docker deployment with airflow 2.1.3

```bash
sudo timedatectl set-timezone Europe/Berlin

touch dags/example-dag.py
docker container top <container-name> | grep DagFileProcessor

# to grab container name, $(docker ps | awk '/scheduler/  { print $NF }')
```

is there something I might have missed?

**Comment by potiuk** [comment]
the problem is that you have likely differnet machines and their time is not synchronized. Timezone setting should have no impact on checking modification time but wroing clock setting likely has. Make sure that all your machines have time synchronized (for example using `ntp`). I am converting that into a discussion as this is not very likely to be an airflow issue.
