### ISSUE TITLE
Unclear when scheduled runtime actually executes DAGs

### ISSUE THREAD

**Issue by raehirsch** [apache/airflow#18678]
### Describe the issue with documentation

There is no obvious documentation about when DAGs actually run compared to their scheduled cron string. Please indicate where this is documented in the official Airflow documentation.

All I was able to find was a blog post (https://eugeneyan.com/writing/why-airflow-jobs-one-day-late/).

### How to solve the problem

At the top of the Variables page, there should be a note saying something like "if you schedule a job for '0 2 * * *' and you want it to execute on 6/19/21 at 2am, it will be actually run at 2am on 6/20/21 with the { ds } of 6/19/21 at 02:00:00 (i.e. there is always a 24 hour delay after the scheduled time)".

### Anything else

We have experience using Glue, Control-M, Kubernetes, etc and have never encountered this type of inherent delay.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by msropp** [comment]
This really needs to be fixed.   👍

**Comment by GoranGoranovic** [comment]
definitely an issue that needs to be addressed

**Comment by eladkal** [comment]
> There is no obvious documentation about when DAGs actually run compared to their scheduled cron string. Please indicate where this is documented in the official Airflow documentation.

There is:
https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html#scheduler

It's even highlighted :
```
If you run a DAG on a schedule_interval of one day, the run with execution_date 2019-11-21 triggers soon after 2019-11-21T23:59.

Let’s Repeat That, the scheduler runs your job one schedule_interval AFTER the start date, at the END of the period.
```

In any case AIP 39 soon to be released will change things in this area dramatically
