### ISSUE TITLE
Tooltips don't appear in Graph or Tree view on UI after hovering over a task

### ISSUE THREAD

**Issue by PApostol** [apache/airflow#18673]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Amazon Linux 2

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.2.0
apache-airflow-providers-apache-spark==2.0.1
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Virtualenv installation

### What happened

When hovering over a task in Graph or Tree view in the UI, no tooltip with status info appears at all. The problem only appeared after upgrading from Airflow 2.0.2 to 2.1.4 (same browser used in both versions: Chrome 93.0.4577.82 (32-bit))

Examples:

Airflow 2.0.2:
![2 0 2](https://user-images.githubusercontent.com/50751110/135641129-de59e4b6-a38c-4940-9ddd-eab4f7f30b79.PNG)

Airflow 2.1.4:
![2 1 4](https://user-images.githubusercontent.com/50751110/135641159-519f3479-94fa-4466-af2d-1e17856e8ec0.PNG)

### What you expected to happen

Tooltips with task info & status to appear (see screenshots above).

### Anything else

The tooltips seem to appear for tasks with no status or queued tasks, but they stop appearing for running or successful tasks.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you please check with [2.2.0b2](https://pypi.org/project/apache-airflow/#history) ?

In main branch it seems to work fine:
![Screen Shot 2021-10-03 at 10 39 15](https://user-images.githubusercontent.com/45845474/135744802-776b3e39-6728-48d0-b31f-ed125d0913d0.png)

**Comment by PApostol** [comment]
Hi, thanks for your reply. I managed to fix this by clearing all browsing data on Chrome.
