### ISSUE TITLE
Log which user triggered a dag

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#18681]
### Description

For audit purposes the username who triggered a dagrun should be logged (or stored in the metadb, shown in UI). Whether they logged into the UI and clicked trigger or used API to trigger a dagrun this should be captured.
ie userX triggered dagrunY with execDateZ
userA triggered dagrunB with execDateC

### Use case/motivation

Want to know who interacted with adhoc dagruns

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by doowhtron** [comment]
In the menu Browse -> logs, you may find what you need

**Comment by potiuk** [comment]
Related to #18217 - maybe you want to cooperate with @alex-astronomer and also add this one @tooptoop4 ?
