### ISSUE TITLE
Airflow Uptake Falsk-AppBuilder 3.3.3 In order to Mitigate Jquery Vulnerability on version coming from Flask-AppBuilder

### ISSUE THREAD

**Issue by HardikVijayPatel** [apache/airflow#18680]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to upgrade to the new Flask. We are automatically upgrading new releases when they come in constratints, so with new releases you will get new FAB (and other dependencies) in constraints but if you want to upgrade to newer version of FAB - on the old version, feel free to do it, there is nothing blocking you. You can even copy the original constraints and modify FAB version there and install Airflow using your own, modified constraints. See https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html
