### ISSUE TITLE
Inter-DAG dependencies and the scheduler

### ISSUE THREAD

**Issue by blake-nicholson** [apache/airflow#187]
How should one set up inter-DAG dependencies so that the priorities of the associated Tasks get set properly?

Consider the situation with three DAGs with the following IDs: (1) staging, (2) prod, and (3) derived.  The derived DAG has dependencies on prod, and prod has dependencies on staging.  I represent the dependencies via ExternalTaskSensors.  For example, the prod DAG has an ExternalTaskSensor for each output of staging on which the prod DAG depends.  The ExternalTaskSensors are then set as upstream of Tasks in prod based upon their dependencies.  Same idea for derived and its dependencies on prod.

What I find is happening is that the priority weights that are computed to determine what Tasks to run next only reflect the dependencies within the given DAG.  The priority weight computation simply looks at what is downstream within the DAG and does not account for inter-DAG dependencies.

Is there something in the setup of the DAGs that I should be doing differently?  I believe manually setting the default priority_weight of each DAG would solve the problem, but seems like it would lead to an inefficient schedule.  I'm going to adjust the priority_weights for my batch run tonight to see how the completion time compares, but I was hoping to avoid this.  Let me know if you have any feedback on adjustments I should make to my setup.  Thanks!

**Comment by mistercrunch** [comment]
As of now, `priority_weight` don't compute across DAGs. Many other features don't go across DAGs, upstream and downstream dependencies (clearing, backfilling, ...) don't go across DAGs either.

How big are your DAGs? It may be that you want all these tasks in a single DAG since they seem to be tightly coupled. We have many DAGs with hundreds of tasks and they behave well.

Another option is to crank up the priority_weight artificially.

**Comment by mistercrunch** [comment]
As a side note, at Airbnb we tend to segment our DAGs based on large-ish subject areas, and we keep the full lineage from staging to warehouse in the same DAG.

**Comment by blake-nicholson** [comment]
Thanks, @mistercrunch.  My DAGs aren't particularly big.  None of them have more than 100 tasks.  I'll probably manually override the priority_weight for now, but look to consolidate the DAGs at some point.
