### ISSUE TITLE
Default Value for AIRFLOW_GID. 0 vs. 50000

### ISSUE THREAD

**Issue by brettpalmberg** [apache/airflow#18709]
### Describe the issue with documentation

Is the default value for environment variable $AIRFLOW_GID `0` or `50000`?
- 50000 (shown in the [docs](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#environment-variables-supported-by-docker-compose))

![image](https://user-images.githubusercontent.com/29417036/135888684-cb395a13-47e2-4b43-9ee5-742f0148b05a.png)

- 0 (shown in the [docker-compose.yml](https://airflow.apache.org/docs/apache-airflow/2.1.4/docker-compose.yaml) file)
  
![image](https://user-images.githubusercontent.com/29417036/135888631-c1696ede-c7fe-49f1-9b50-4b443f1656e7.png)

### How to solve the problem

Verify correct values are referenced in the documentation. Change incorrect value if necessary.

### Anything else

Thank you

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
For docker-compose, the default value for `AIIRFLPW_GID` is `0`. 
https://github.com/apache/airflow/blob/86bf2a29ba784b25c335408eb4647ad2eb48b525/docs/apache-airflow/start/docker-compose.yaml#L67
For docker image, the default value for `AIRFLOW_GID` is `50000`

**Comment by mik-laj** [comment]
CC: @potiuk

**Comment by potiuk** [comment]
The AIRFLOW_GID is the source of confusion and it brings no value whatsoever. I will remove it and hard-code it to 0. This should work everywhere and it should have no side-effects.
