### ISSUE TITLE
/entrypoint Environment Variable Typo "_AIRFLOW_WWW_USER_LASTNME"

### ISSUE THREAD

**Issue by brettpalmberg** [apache/airflow#18716]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

All

### Deployment

Other Docker-based deployment

### Deployment details

Docker

### What happened

Environment Variable `_AIRFLOW_WWW_USER_LASTNAME` will not be recognized by script /entrypoint.  I think there is a typo in the environment variable here: https://github.com/apache/airflow/blob/main/scripts/in_container/prod/entrypoint_prod.sh#L144 .  i.e. `LASTNME` should be `LASTNAME` as shown in the [docs](https://github.com/apache/airflow/blob/main/scripts/in_container/prod/entrypoint_prod.sh#L144)

### What you expected to happen

Environment Variable `_AIRFLOW_WWW_USER_LASTNAME` should populate the `--lastname` field of the command `airflow users create ...`

### Anything else

Thank you

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
> Are you willing to submit PR?
> ☑️ Yes I am willing to submit a PR!

Assigned!

**Comment by brettpalmberg** [comment]
Thank you @mik-laj .  PR Submitted.  I'm new around here, let me know if I missed any contributing steps.

**Comment by mik-laj** [comment]
If you want to make a change to the project, you don't have to create a ticket beforehand and wait for it to be assigned to it.  Submitting a PR is enough in most cases.  Creating an issue will allow us to collect feedback or share plans with other people.
