### ISSUE TITLE
Add possibility to refresh list of DAGs

### ISSUE THREAD

**Issue by mnojek** [apache/airflow#18717]
### Description

Add new button to DAGs list view for refreshing DAGs, e.g. when new DAG is uploaded to Airflow, using button will refresh the list without a need to refresh the whole page.

This can look like this (or it can be separated from the group of buttons):
![image](https://user-images.githubusercontent.com/7412964/135902311-4f3aa480-1384-4d67-b319-ec95d2161544.png)

### Use case/motivation

I want to be able to refresh the DAGs list without a need to refresh the whole page. Especially, when I upload a new DAG and it's not displayed automatically on the DAGs list.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Agree with @BasPH . It's pretty "normal" for the page to get refreshed with refresh button when pretty much all content is refreshed. There is a very (unless it's autor-refresh which is good to avoid flickering) there is very little saving by just refreshing the list - all the other components are already in cache.

**Comment by mnojek** [comment]
So what actually we can do about it? Somehow implement autorefresh when new DAG is added or just refresh the list with some time interval? I don't fully get your message @potiuk (please review it)

**Comment by nathadfield** [comment]
Auto-refresh of the DAGs page is now a feature of Airflow.
