### ISSUE TITLE
/roles stable API endpoint PATCH verb needs better documentation in the openapi spec

### ISSUE THREAD

**Issue by alex-astronomer** [apache/airflow#18713]
### Describe the issue with documentation

When using the `PATCH` verb for the `/roles/{role_name}` endpoint, I found myself, as a beginner with the stable API, having to look through source code and the meta database to try to find the correct terms to use for `action.name`, `permissions.name` and other pieces that get merged into the role with this command.

### How to solve the problem

I'd like to add some better documentation to the API `yml` that better explains how to use this command.  More details about the options for action and permission and resource.

Thoughts? Maybe I'm missing something?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by alex-astronomer** [comment]
`update_mask` is also confusing to me.  I'd be happy to submit a PR for this, would allow me to get more familiar with the REST API.

**Comment by eladkal** [comment]
@alex-astronomer are you still working on this?
