### ISSUE TITLE
Tooltip element is not removed and overlays another clickable elements

### ISSUE THREAD

**Issue by mnojek** [apache/airflow#18732]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Debian GNU/Linux 11 rodete

### Deployment

Docker-Compose

### What happened

On a clean Airflow install, sometimes there is a problem with accessing clickable elements like 'Airflow Home' button (logo with name), or 'DAGs' menu button. This is a problem that can be replicated also in older versions on Airflow. 
The issue is caused by tooltip elements that are created each time another element is hovered and they appear as transparent elements in the 0,0 point which is the top left corner of the interface. That's why they cover Airflow Home button and sometimes even DAGs menu button (depending on the size of the tooltip). 
This is causing some of the elements that are located near top left corner not clickable (e.g. Airflow Home button is clickable but only the bottom side of it).

This is a screenshot of the interface with highlighted place where the redundant tooltips appear. I also showed here the tooltip elements in the HTML code.
![image](https://user-images.githubusercontent.com/7412964/135996630-01640dac-6433-405c-8e7c-398091dbfe34.png)

### What you expected to happen

I expect that the tooltips disappear when the element triggering them is not hovered anymore. The Airflow Home button and DAGs button should be clickable. 

### How to reproduce

1. Hover over Airflow Home button and see that all of the element can be clicked (note the different pointer).
2. Now hover over any other element that shows a tooltip, e.g. filters for All/Active/Paused DAGs just a bit below.
3. Hover again over Airflow Home button and see that part of it is not clickable.
4. Open devtools and inspect the element that covers the top left corner of the interface.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
This is a weird issue. I can confirm it happens with "All, Paused, None". But at least most of our tooltips do not experience this behavior. 
I'm going to need to look into this more.
