### ISSUE TITLE
Chart in Task Duration is too narrow

### ISSUE THREAD

**Issue by mnojek** [apache/airflow#18731]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Debian GNU/Linux 11 rodete

### Deployment

Docker-Compose

### What happened

Task Duration chart is too narrow which leads to not displaying properly maximum and minimum points because they are printed in the corner of the chart, but they also have some area which is partly hidden outside of the SVG element which is exactly the same height that the chart is. 

This is an example (it's hard to take a screenshot because the points disappear then so I drew them with red color and added arrows to show where to look):
![image](https://user-images.githubusercontent.com/7412964/135986997-d5ea2f13-b98a-47a9-a21a-d749cff659a4.png)

### What you expected to happen

I expect that the points drawn in the chart end about 10% lower than the height of the chart and also that they start maybe a bit above the bottom of the chart. It then would be easier to hover over them and the point would be displayed properly.

### How to reproduce

Click on any DAG with several runs from the DAGs list. Go to 'Task Duration' tab and see the chart.

### Anything else

I believe that the change needs to be done inside `airflow/www/views.py` file (I guess, it is around line 2700 inside `landing_times` function). The code uses NVD3 line chart (https://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart). Possible solution can be achieved by doing something like this: https://stackoverflow.com/questions/47146031/add-more-space-padding-into-nvd3-line-chart-max-and-min

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
This also happens on the far right and far left. 

<img width="431" alt="Screen Shot 2021-10-08 at 12 48 08 PM" src="https://user-images.githubusercontent.com/4600967/136600716-f94342d6-0fbd-451b-a336-0fc00a65791b.png">

**Comment by mnojek** [comment]
Can someone check if this is still an issue? @bbovenzi ?
I haven't used Airflow since the time end of 2021.

**Comment by bbovenzi** [comment]
Probably. I haven't touched this view. My preference is to replace it with a better visualization in the near future.

**Comment by eladkal** [comment]
> My preference is to replace it with a better visualization in the near future.

If that is the case I'd say we should close this issue as won't fix. It's not worth investing time on it
