### ISSUE TITLE
Kubernete executor: fetch log failed, no retries on task when task pod is DELETED while running

### ISSUE THREAD

**Issue by enniomorricone123** [apache/airflow#18756]
### Apache Airflow version

2.1.3

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

use helmchart and deployed on amazon eks with Kubernetes Executor

### What happened

When Task was submitted and new pod launched, and was running. If the task pod was somehow deleted right after it turned to running state, airflow webUI log will show errors:

```
*** Unable to fetch logs from worker pod xxxxxxx.dec54b913bdf4d2fb10c2b136800d ***
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '06b56d47-8cdc-4efd-99f6-5dc3cb3fd318', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 05 Oct 2021 19:57:51 GMT', 'Content-Length': '294'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"xxxxxxx.dec54b913bdf4d2fb10c2b136800d\\" not found","reason":"NotFound","details":{"name":"xxxxxxx.dec54b913bdf4d2fb10c2b136800d","kind":"pods"},"code":404}\n'
```

or 

```
*** Trying to get logs (last 100 lines) from worker pod  ***

*** Unable to fetch logs from worker pod  ***
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e93f7e78-f226-411d-91e0-2f1bb0f1744a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 05 Oct 2021 20:03:03 GMT', 'Content-Length': '136'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"name must be provided","reason":"BadRequest","code":400}\n'
```

And no retries will be triggered even retried are configured to this task.

### How to reproduce

How to reproduce?

Using kuberneteExecutor and launch a dummy task. You can manually delete a running task pod right after it turned to RUNNING state.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by easontm** [comment]
I believe I'm experiencing a similar issue. Occasionally in my deployment, task pods fail to create due to k8s environmental reasons. To a degree this can't be helped by me, and I would prefer if the scheduler could automatically retry/reschedule on this event (because it can at least tell that the task failed).
