### ISSUE TITLE
[Quarantine] test_no_orphan_process_will_be_left 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#18777]
### Body

The `test_no_orphan_process_will_be_left` in `TestSchedulerJob` is really flaky.

Before we know how to fix it, I will quarantine it:

https://github.com/apache/airflow/pull/18691/checks?check_run_id=3811660138

```
  =================================== FAILURES ===================================
  _____________ TestSchedulerJob.test_no_orphan_process_will_be_left _____________
  
  self = <tests.jobs.test_scheduler_job.TestSchedulerJob object at 0x7fc2f91d2ac8>
  
      def test_no_orphan_process_will_be_left(self):
          empty_dir = mkdtemp()
          current_process = psutil.Process()
          old_children = current_process.children(recursive=True)
          self.scheduler_job = SchedulerJob(
              subdir=empty_dir, num_runs=1, executor=MockExecutor(do_update=False)
          )
          self.scheduler_job.run()
          shutil.rmtree(empty_dir)
      
          # Remove potential noise created by previous tests.
          current_children = set(current_process.children(recursive=True)) - set(old_children)
  >       assert not current_children
  E       AssertionError: assert not {psutil.Process(pid=2895, name='pytest', status='running', started='06:53:45')}
  
```

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by uranusjr** [comment]
Should this be closed since the PR is merged?

**Comment by potiuk** [comment]
No no. We keep those `Quarantine` open to keep track on the quarantined issues (+ track where it happened and keep stack-trace in case we cannot easily find a case when we try to attempt to fix it). 

See other issues like that: https://github.com/apache/airflow/labels/Quarantine
