### ISSUE TITLE
Retry interval much longer than what is set

### ISSUE THREAD

**Issue by pharoson** [apache/airflow#188]
I have a dag with retry_interval set in the default_args to timedelta(seconds=10). However, when a task failed, it did not retry until 5 minutes and 6 seconds later (according to the logs). Another retried after 5 minutes and 3 seconds. 

Is there a workaround for this? Has anyone encountered this before?

**Comment by mistercrunch** [comment]
At which interval is your scheduler running?
Look for `SCHEDULER_HEARTBEAT_SEC` in your airflow.cfg

Also, what's your `JOB_HEARTBEAT_SEC` set to?

**Comment by pharoson** [comment]
Both are set to 5 seconds.

**Comment by mistercrunch** [comment]
The docs/tutorial wasn't using the right param name:
https://github.com/airbnb/airflow/pull/189

Thank you for reporting this!

**Comment by pharoson** [comment]
Thanks a bunch!
