### ISSUE TITLE
Error in setting up the development environment following the docs for VS code

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#18849]
### Describe the issue with documentation

https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#setup-and-develop-using-visual-studio-code

I am following the steps on the above page to set up the development environment. however, running the 
```pyenv install 3.8.5``` in Apple M1 chip MacOS Big Sur runs into an error similar to the issue mentioned in the below StackOverflow link

https://stackoverflow.com/questions/65457674/unexpected-output-of-arch-on-osx-using-mac-m1-installing-elastic-beans

### How to solve the problem

I am not sure how to solve this issue, but i used higher version of python 3.8.10 that is supported in M1 chip Apple MacOS Big Sur to solve the issue for time being.

### Anything else

Further following the steps in this documentation, i got docker container up and running. however, if i try to reset the db, i get error saying 

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1130, "Host 'docker-compose_airflow_run_718f404eac1d.docker-compose_defau' is not allowed to connect to this MySQL server")(Background on this error at: http://sqlalche.me/e/13/e3q8)

I am not sure why if i am running into this issue.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
M1 has some issues indeed. I believe the problem might be that MySQL still does not have ARM image.
