### ISSUE TITLE
command not found: complete when using bash completion for breeze setup-autocomplete

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#18851]
### Describe the issue with documentation

OS: MacOS Big Sur (M1 chip)
Shell used: zsh

I am trying to set up the airflow local development setup using Breeze as described in the video in the link https://github.com/apache/airflow/blob/main/BREEZE.rst

I forked and cloned the repo, checked the docker and docker-compose version, and have given the below command

```./breeze setup-autocomplete```

At the end of the above command, I got the result like below,

```Breeze completion is installed to ~/.bash_completion.d/breeze-complete

     Please exit and re-enter your shell or run:

     source ~/.bash_completion.d/breeze-complete```
    
I entered the below command in prompt to finish the process:
```$source ~/.bash_completion.d/breeze-complete```
 
and got the below response:
```/Users/sk/.bash_completion.d/breeze-complete:466: command not found: complete
 /Users/sk/.bash_completion.d/breeze-complete:467: command not found: complete
```

### How to solve the problem

i have to execute:

```source ~/.zshrc``` command  first and then execute the command 

```  source ~/.bash_completion.d/breeze-complete ``` 

we can either put instruction to execute both of the above command or add them as part of breeze.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to update it :)

**Comment by Bowrna** [comment]
Could I update the instructions or make changes in breeze to make this change @potiuk
