### ISSUE TITLE
Fix DockerSwarmOperator timeout 

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#18867]
### Body

See discussion in https://github.com/apache/airflow/discussions/18270

`docker-py` released version 5.0.3 https://github.com/docker/docker-py/releases/tag/5.0.3 which fixed https://github.com/docker/docker-py/issues/931

**Task:**
Update `DockerSwarmOperator`
https://github.com/apache/airflow/blob/4da4c186ecdcdae308fe8b4a7994c21faf42bc96/airflow/providers/docker/operators/docker_swarm.py#L205-L215
as we don't need the workaround any longer.

Note: this also require set minimum version of the package to 5.0.3 in [steup.py](https://github.com/apache/airflow/blob/fd45f5f3e38b80993d5624480a793be381194f04/setup.py#L263)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by RyanSiu1995** [comment]
I will pick this up. Will open the PR shortly.

**Comment by potiuk** [comment]
Assigned it to you @RyanSiu1995!
