### ISSUE TITLE
Change the Sensors default timeout using airflow configs

### ISSUE THREAD

**Issue by mariotaddeucci** [apache/airflow#18878]
### Description

Add the configuration parameters to set the default `timeout` on `BaseSensorOperator`.
```
[sensors]  
default_timeout=
```

### Use case/motivation

By default the sensor timeout is 7 days, this is to much time for some environments and could be reduced to release workers slot faster if a sensor never matches the result and have no custom timeout.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Feel free! 🐈
