### ISSUE TITLE
DockerOperator xcom is broken

### ISSUE THREAD

**Issue by asaf400** [apache/airflow#18874]
### Apache Airflow version

2.0.2

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==1.3.0
apache-airflow-providers-celery==1.0.1
apache-airflow-providers-databricks==1.0.1
apache-airflow-providers-docker==1.2.0
apache-airflow-providers-ftp==1.0.1
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-oracle==1.1.0
apache-airflow-providers-postgres==1.0.2
apache-airflow-providers-presto==1.0.2
apache-airflow-providers-sftp==1.2.0
apache-airflow-providers-sqlite==1.0.2
apache-airflow-providers-ssh==1.3.0
apache-airflow-providers-tableau==1.0.0

### Deployment

Virtualenv installation

### What happened

When using DockerOperator with 'do_xcom_push' set as True,
Airflow documentation states that without xcom_all also True, the default False behavior is that airflow would push only the last line from docker into xcom return_value, but this statement is False

do_xcom_push just returns the entire \ chunked part of the entire docker output as a single 'merged' string,
all the lines, as far as I can tell..

See code lines:
https://github.com/apache/airflow/blob/10023fdd65fa78033e7125d3d8103b63c127056e/airflow/providers/docker/operators/docker.py#L258

lines is the generator that cli.attach returns earlier in the code, the generator comes from docker py, see here:
https://github.com/docker/docker-py/blob/7172269b067271911a9e643ebdcdca8318f2ded3/docker/api/client.py#L418

Following the api code for docker-py, and into the generator logic (socket read and stuff..) 
we can conclude that the assumption that 'cli.attach' returns 'lines' is wrong, therefore do_xcom_push is braking the 'contract' set by the documentation of the parameter, it never actually returns the last line.

So it is probably better just to also use 'xcom_all' because that at least uses cli.logs which is a safer interface to use, until this issue is fixed, probably we need to create a matching issue in the docker-py repo, but maybe airflow should just handle the stream itself and split it into lines, returning the last line, see this example, modified from another issue on xcoms:

```python
from docker import APIClient                                                                                                                                                               
d = APIClient()                                                                                                                                                                            
c = d.create_container(image='ubuntu:20.04', name='TEST', command="""bash -c "echo 'test' && echo 'test2'" """, host_config=d.create_host_config(auto_remove=False, network_mode='bridge'))
gen=d.attach(c['Id'], stderr=True, stdout=True, stream=True)                                                                                                                               
d.start(c['Id'])                                                                                                                                                                           
print( [i for i in gen] )                                                                                                                                                                  
print([i for i in d.logs(c['Id'], stream=True, stdout=True, stderr=True)])                                                                                                                 
d.remove_container(c['Id'])
```

Thank you @nullhack
Related issues: 
https://github.com/apache/airflow/issues/15952
https://github.com/apache/airflow/issues/9164
https://github.com/apache/airflow/issues/14809 - This is a real nasty issue, I'm also having

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

Edits:
- airflow version correction
- Code chunk formatting

**Comment by potiuk** [comment]
This part of docker provider had gone through a number of changes and improvements and a number of bug have been fixed. What you are observing is very likley already fixed in latest `docker provider` - you  will need to upgrade Airflow to 2.1 in order to use that provider however.

**Comment by asaf400** [comment]
All the GitHub perm links I have published here are LATEST main/master branches of each repository,
therefore I actually think that I have done my due diligence enough to say the code doesn't seem to have changed from airflow 2.0.2 to airflow 2.1+, and that the issue would be just the same in new versions of airflow..

I myself am using 2.0.2 because that's what the MWAA over at AWS have enabled so far..
I have full respect for everyone officially involved in airflow development,

But even taking the most recent chunk of code from docker.py file in airflow's docker provider, you can see that this isn't fixed yet, and airflow component tests for this provider? I have no idea how they pass this feature test, it looks like the correct behavior is asserted, but in the 'real' world, it just doesn't compile:

https://github.com/apache/airflow/commit/cd3307ff2147b170dc3feb5999edf5c8eebed4ba#diff-942f75ae382d164822ff30e8138471be26102283dfcbf25e6f1c8e5795de0cb0R463

**Comment by asaf400** [comment]
@potiuk Yes, I can try and fix it, but it wouldn't be pretty, 
Partly because the issue is also actually docker-py's fault..

I'll have to go through some of the old commits, but I think the resolution might be not using attach() at all, and just using logs() after container exits, and before container removal

**Comment by ferruzzi** [comment]
Looks like this is maybe abandoned?   I can pick it up if @asaf400 isn't able to finish it.

**Comment by eladkal** [comment]
@ferruzzi assigned to you

**Comment by ferruzzi** [comment]
It looks like https://github.com/apache/airflow/pull/19030 is unrelated and, IMHO, undesirable since it is changing the default behavior of an existing Operator.  

@eladkal @uranusjr - Do either of you feel that one needs to be finished and included here?

**Comment by uranusjr** [comment]
No, let’s just fix the Docker log streaming issue here.
