### ISSUE TITLE
Manual execution of future dated dag succeeds, but none of the tasks actually run

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#18918]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Debian Buster (in docker)

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

Dockerfile:

```
FROM quay.io/astronomer/ap-airflow-dev:2.2.0-buster-onbuild-44762
```

**DAG**
```
with DAG(
    dag_id='future_dag',
    start_date=datetime.now() + timedelta(days=1),
    schedule_interval=timedelta(weeks=1),
) as dag:

    DummyOperator(
        task_id='dummy'
    )
```

### What happened

The DAG succeeded, but the task didn't run:

![image](https://user-images.githubusercontent.com/5834582/137015726-f37c7ac6-f19a-4742-b685-c504e5b57e13.png)

### What you expected to happen

Whatever the tasks do, the dag should do also.  Since this is a manual execution, I expect that any scheduling constraints will be ignored and the tasks will run.

### How to reproduce

Run the DAG indicated above, notice that its task didn't run.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Your code indeed not working but this code do work:

```
with DAG(
    dag_id='future_dag2',
    start_date=datetime(2021, 1, 1),
    schedule_interval=timedelta(weeks=1),
) as dag:

    DummyOperator(
        task_id='dummy'
    )
```

Using dynamic start date isn't recommended it can caused weird issues. We explain this is the [docs](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date).
