### ISSUE TITLE
Add template_ext = ('.json')  to databricks operators

### ISSUE THREAD

**Issue by celoibarros** [apache/airflow#18925]
### Description

Add template_ext = ('.json') in databricks operators. I will improve the debug and the way to organize parameters.

### Use case/motivation

Bigger parameters on file. Easier to debug and maintain.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
> If you create pull-request, you don't have to create an issue first, but if you want, you can do it. Creating an issue will allow you to collect feedback or share plans with other people.

https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#contribution-workflow
