### ISSUE TITLE
[ui] Use name of variable or connection in delete confirmation box

### ISSUE THREAD

**Issue by jameslamb** [apache/airflow#18959]
### Description

As of Airflow 2.1.0, when you click the trash can in the UI to delete a Variable or Connection, the following confirmation box appears.

![image](https://user-images.githubusercontent.com/7608904/137201420-48a4dc49-7a49-4074-9f9f-2b98c4756275.png)

With the message.

> You sure you want to delete this item?

In this feature request, I'd like to propose that this message include the name of the Variable or Connection being deleted. For example, for a variable `TARGET_S3_BUCKET`, this confirmation message would say

> Sure you want to delete variable "TARGET_S3_BUCKET"?

### Use case/motivation

As an administrator of an Airflow instance, I regularly delete Connections or Variables when the DAG(s) using them are removed or refactored.

Because the delete action is non-reversible, sometimes I reach this very generic confirmation box and thing "wait...am I sure I clicked on the right thing?". When that happens, I usually hit "cancel" and then very carefully re-select the 🗑️ next to the item I want to delete.

If the confirmation message contained the name of the thing being deleted, it would save me this extra set of "let me double-check clicks".

I think including the name in the message might also help Airflow users catch mistakes.

### Related issues

Searching through open and closed issues, I did not find a similar feature request.

I did see the following issues related to management of variables and connection through the UI, which might have some relevant information.

* https://github.com/apache/airflow/issues/8421
* https://github.com/apache/airflow/issues/18217
* https://github.com/apache/airflow/issues/18436

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jameslamb** [comment]
I didn't see a place in the GitHub Form to add this....I checked "willing to submit a PR" because I am willing to do the work if maintainers are open to the feature, but I'm very inexperienced with JavaScript, so I expect that other contributors would be able to implement this much more quickly than I could.

**Comment by eladkal** [comment]
After consulting with @pierrejeambrun closing this one as won't fix.
This is not a trivial change and doesn't worth the investment

**Comment by jameslamb** [comment]
No problem, thanks anyway for considering it!
