### ISSUE TITLE
Trino JWT Authentication Support

### ISSUE THREAD

**Issue by harlequin** [apache/airflow#18969]
### Description

Would be great to support JWT Authentication in Trino Hook (which also can be used for presto hook).

For example like this

```
        elif extra.get('auth') == 'jwt':
            auth = trino.auth.JWTAuthentication(
                token=extra.get('jwt__token')
            )
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pragyak412** [comment]
Hello @eladkal 
It seems the https://github.com/apache/airflow/pull/19008 is not merged, also test cases and documentation is left. Can you please assign this to me? I would like to contribute and make all the necessary changes required.

Thanks!

**Comment by potiuk** [comment]
Assigned
