### ISSUE TITLE
suffix of dag run id is always +00:00

### ISSUE THREAD

**Issue by yifeng-chen** [apache/airflow#19004]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Ubuntu 20.04.2 LTS

### Versions of Apache Airflow Providers

docker tag: apache/airflow:2.2.0-python3.7

### Deployment

Other

### What happened

No matter what time zone do I specify in config file [core/default_timezone] or dag's start date, the suffix of dag_run_id is always "+00:00".

### What you expected to happen

The time zone suffix of dag_run_id should be some kind related to the time zone that I specify in the config file or the dag object. Is there any way to customize the format of dag_run_id?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Duplicate to #17502
