### ISSUE TITLE
Migrate execution_date database columns to logical_date

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#19049]
To conform with other AIP-39 changes. `execution_date` should still be kept on the class and emit a deprecation warning when accessed (either as a property or a filter). I think there's mechanism in SQLAlchemy for this out of the box.

**Comment by kaxil** [comment]
Is this still pending @uranusjr ?

**Comment by uranusjr** [comment]
Let's not do this in 2.3

**Comment by eladkal** [comment]
@uranusjr should we add this task also under AIP-83 project effort?

**Comment by phanikumv** [comment]
This is covered in https://github.com/apache/airflow/pull/43902

**Comment by sunank200** [comment]
Now that this PR: [https://github.com/apache/airflow/pull/43902](https://github.com/apache/airflow/pull/43902) is merged following is covered:

> The database level migration is already done, but we still need to rename the attribute on the model (and all references to it, obviously). We also don’t need to emit a deprecation warning since this is only for 3.0
