### ISSUE TITLE
V2.2 Pythonoperator  task status could not be changed to success, write large log file and OOM

### ISSUE THREAD

**Issue by mmlzhang** [apache/airflow#19069]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

centos

### Deployment

Other Docker-based deployment

### What happened

I use two case run pythonoperator
A memory leak occurs when pythonOperator is used. The machine runs out of memory and the task is forced to end,
task is running, cannot turn to success status, but code python_callable is execute end

here is a example
test1 cannot change status to success, state is always running, write large log file, about 4GB, caused OOM
        send execute success 
test2 auto change to success normaly

![image](https://user-images.githubusercontent.com/38830811/137891829-f7402aae-b386-47d9-9cd3-1a37fd22bd40.png)

### What you expected to happen

The task is complete and mark success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
Hi @lanms, I'm not able to reproduce this and I suspect it's something related to `EnterpriseWeiChat`. Can you try to reproduce with this DAG:

```python
from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator, ShortCircuitOperator


def say_hello():
    print("hello")


def keep_going():
    return True


with DAG("pythonop", start_date=datetime(2021, 10, 14), schedule_interval=None) as dag:
    short = ShortCircuitOperator(task_id="short", python_callable=keep_going)
    hello = PythonOperator(task_id="hello", python_callable=say_hello)
    short >> hello
```

**Comment by lanms** [comment]
Thanks for your attention, The DAG you give is OK, 
I can give you some run logs, please analyze the problem, I add some Print in code, and log it


here is my DAG
EnterpriseWeiChat is func to send msg for me
![image](https://user-images.githubusercontent.com/38830811/138019443-cc5443e6-72d6-4393-82cc-6f1ab5f64182.png)


here is log
log file is mor than 300M

![image](https://user-images.githubusercontent.com/38830811/138019655-29038435-0496-44e5-88a9-afa3446b7122.png)

head of log
![image](https://user-images.githubusercontent.com/38830811/138019741-19ddfdc5-4159-474e-908a-f52a62f8651c.png)

tail of log
![image](https://user-images.githubusercontent.com/38830811/138019791-616a3e8a-3025-427f-95b5-912883a5cbd0.png)

:

**Comment by lanms** [comment]
[ppe-aiflow-worker-f6f66fd7c-pvxf2-ppe-aiflow-worker.log](https://github.com/apache/airflow/files/7377822/ppe-aiflow-worker-f6f66fd7c-pvxf2-ppe-aiflow-worker.log)

**Comment by lanms** [comment]
> Hi @lanms, I'm not able to reproduce this and I suspect it's something related to `EnterpriseWeiChat`. Can you try to reproduce with this DAG:
> 
> ```python
> from datetime import datetime
> from airflow import DAG
> from airflow.operators.python import PythonOperator, ShortCircuitOperator
> 
> 
> def say_hello():
>     print("hello")
> 
> 
> def keep_going():
>     return True
> 
> 
> with DAG("pythonop", start_date=datetime(2021, 10, 14), schedule_interval=None) as dag:
>     short = ShortCircuitOperator(task_id="short", python_callable=keep_going)
>     hello = PythonOperator(task_id="hello", python_callable=say_hello)
>     short >> hello
> ```

**Comment by lanms** [comment]
I run this DAG in airfow v2.1.4 It's OK, only raise problem in v2.2
