### ISSUE TITLE
Display DAGs dependencies  in CLI

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#19080]
### Description

Recently, we added [a new DAG dependencies view](https://github.com/apache/airflow/pull/13199) to the webserver. It would be helpful if a similar diagram could also be displayed/generated using the CLI. For now, only [one DAG can be displayed](http://airflow.apache.org/docs/apache-airflow/stable/usage-cli.html#exporting-dag-structure-as-an-image) using CLI.
![image](https://user-images.githubusercontent.com/12058428/137945580-6a33f919-2648-4980-bd2c-b40cfcacc9fe.png)

If anyone is interested, I will be happy to help with the review.

### Use case/motivation

* Keep parity between CLI and web serwer.
* Enable the writing of scripts that use these diagrams, e.g. for attaching in the documentation.

### Related issues

https://github.com/apache/airflow/pull/13199/files

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by subkanthi** [comment]
can I take this on please.

**Comment by mik-laj** [comment]
@subkanthi  Assgined.

**Comment by subkanthi** [comment]
Observation: the UI retrieves the dag dependencies of all the DAG's
`SELECT serialized_dag.dag_id AS serialized_dag_dag_id, json_extract(serialized_dag.data, %s) AS json_extract_1 
FROM serialized_dag`

But for the CLI, dag dependencies need to be filtered for the specific DAG passed by the user.

**Comment by mik-laj** [comment]
@subkanthi  Why do you want to filter dependencies based on DAG ID? I think it makes sense to see all the dependencies in one diagram.

**Comment by subkanthi** [comment]
> @subkanthi Why do you want to filter dependencies based on DAG ID? I think it makes sense to see all the dependencies in one diagram.

Hi @mik-laj , its good you actually looked at this comment, the current dag show takes the DAG id, so I assumed for the dag dependencies we need to show that specific DAG. Maybe its nice to have one for specific DAG id , and it no arguments are passed, show the dag dependencies for all DAGs.

`airflow dags show example_external_task_marker_parent --save output.jpg`
