### ISSUE TITLE
airflow worker not picking up tasks

### ISSUE THREAD

**Issue by nocrosstalk** [apache/airflow#191]
I'm new to airflow, installed all components on an empty Ubuntu server, airflow seems to run (webinterface works), RabbitMQ is receiving mesages, but if I run airflow worker nothing happens. When I run "airflow run tutorial print_date 2015-01-01" I see a message added to rabbitMq, but no message seems to be processed. Any hint to get me started with this? I don't believe Celery has to be started seperately?

**Comment by jomario** [comment]
Check what queue you're sending the task to. If u want the worker to process a certain queue run it with "-q queuename". If you send your tasks to the default queue it should work out of the box. No celery extra setup needed in any case.

**Comment by jomar83** [comment]
Check what queue you're sending the task to. If u want the worker to process a certain queue run it with "-q queuename". If you send your tasks to the default queue it should work out of the box. No celery extra setup needed in any case.

**Comment by nocrosstalk** [comment]
Working now, I was running at root and had to set a flag, blame on me. It's running now... Txs, next question in separate topic.

**Comment by mistercrunch** [comment]
Glad to hear it's working now. I really want Airflow to be easy to setup and use. Let us know if there's something we can clarify in the docs or use before defaults somewhere.
