### ISSUE TITLE
API: DagRunState

### ISSUE THREAD

**Issue by Nidesh-Arumugam** [apache/airflow#19101]
### Describe the issue with documentation

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/update_dag_run_state

based on the above  documentation whenever i tried to raise an req with PATCH method, it results in method not allowed
<img width="1440" alt="Screenshot 2021-10-20 at 2 48 41 PM" src="https://user-images.githubusercontent.com/80671776/138065613-042ff4b7-f9c6-4e6a-b87b-c13dc91071a1.png">
.

### How to solve the problem

Need to update the dag_run_state as per our requirements, when we trigger the API

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
The patch endpoint was added in 2.2
