### ISSUE TITLE
After updating the the airflow provider , unable to access Airflow UI (MWAA)

### ISSUE THREAD

**Issue by priyadarshan1995** [apache/airflow#19129]
### Apache Airflow version

2.0.2

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-snowflake==2.2.0

### Deployment

MWAA

### Deployment details

We updated the version of airflow-snowflake-providers to a stable version. WE got the below error:

```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.
```

### What happened

We updated the version of airflow-snowflake-providers to a stable version (2.2.0) and redeployed the MWAA instance. After that we arent able to access the airflow UI.

### What you expected to happen

We are not sure.

### How to reproduce

WE added apache-airflow-providers-snowflake in the requirements.txt file 
version:2.2.0 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Do you get anything in server logs?

**Comment by uranusjr** [comment]
Yeah I fully support that only AWS should be responsible for looking into this, not the community. I'm just responding to the six-month-old part since MWAA customers have no choices (and it's also not the community's fault, it's their choice to use old software).
