### ISSUE TITLE
Unable to access Airflow UI (MWAA)

### ISSUE THREAD

**Issue by priyadarshan1995** [apache/airflow#19133]
### Apache Airflow version

2.0.2

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-snowflake==1.3.0

### Deployment

MWAA

### Deployment details

WE got the below error:

```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.
```

### What happened

We updated the version of airflow-snowflake-providers to a stable version (1.3.0) and redeployed the MWAA instance. After that we aren't able to access the airflow UI.

### What you expected to happen

For the UI to be accessible

### Anything else

Opened a previous issue that got closed. The resolution suggested also wasn't working
Link: https://github.com/apache/airflow/issues/19129

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
I am afraid that this is a problem that affects MWAA and you should contact AWS support.
https://github.com/apache/airflow/issues/19129#issuecomment-948678464
