### ISSUE TITLE
Add timeout_fallback to DAG

### ISSUE THREAD

**Issue by Mavtti** [apache/airflow#19131]
### Description

Currently when a DAG times out, there is not way to call a fallback. The on_failure_callback is not called in this case.
The idea would be to give the possibility to call a fallback when a DAG times out.

### Use case/motivation

Log times outs

### Related issues

https://github.com/apache/airflow/issues/18746

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Isn't that just [sla_miss_callback](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#sla-miss-callback) ?

**Comment by Mavtti** [comment]
Sorry I didn't see your answer. Anyway thanks for taking the time to look into it.
SLA seems to be at the task level, I wondered if there was the same thing at the DAG level else it requires to define an sla_miss_callback for every task instead of defining only one time.
