### ISSUE TITLE
Allow to turn dag run state to skipped

### ISSUE THREAD

**Issue by parisni** [apache/airflow#19196]
### Description

Behing able to track failed task in the past run is great. Sometimes the task has failed but we don't care. To remove the entry from the failed task (because this is polluting), we only have the option to turn it to `success` witch is not the real semantic.

I would prefer to be able to turn it to `skipped`. This would help in the future if we change our mind about this particular failure. Also having it to `skipped` will help to remove this false positive read flags in the UI and improve productivity of the team.

![Screenshot-nparis_2021-10-25_10:26:38](https://user-images.githubusercontent.com/9535350/138661786-cb6581fb-b043-4983-afbc-b60ff6e0a7b1.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Since no further comments on this I'm closing this request as wont fix.
We can revisit in the future if needed
