### ISSUE TITLE
WebUI: Action on multiple selection in dag run list yields an error

### ISSUE THREAD

**Issue by parisni** [apache/airflow#19199]
### Apache Airflow version

2.1.3

### Operating System

linux

### Deployment

Virtualenv installation

### What happened

When trying to apply batch set state to success, this does not work. I have to set the state on each element one by one. This happens in the "list dag run" panel.

When:

![Screenshot-nparis_2021-10-25_10:57:19](https://user-images.githubusercontent.com/9535350/138666579-02ea9298-7d5c-4454-82b2-e984a3c4f3a4.png)

then:

![Screenshot-nparis_2021-10-25_10:56:50](https://user-images.githubusercontent.com/9535350/138666588-a1901df8-8341-4aa7-b9a4-c47f195b599a.png)

### What you expected to happen

Each task selected shall be turned to `success`. No error message `failed to set state` shall appear

### Anything else

related to  #11513 ?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
@parisni, can you try with 2.2.2? I'm unable to reproduce this with 2.2.2 or main.

**Comment by jedcunningham** [comment]
Hmm, I couldn't even reproduce this in 2.1.3 🤷‍♂️

**Comment by parisni** [comment]
Thanks for your support. This was also fixed in our environment.
Probably some magical dwarfs under the hood
