### ISSUE TITLE
Airflow Config connection URI generation from backend/vault similar to Connection done in amazon provider 2.3.0

### ISSUE THREAD

**Issue by SohailChamadia-everestek** [apache/airflow#19217]
### Description

Currently the Connection can be created by storing the parameters or arguments in AWS Secrets Manager and then creating the Connection URI in runtime. Unfortunately the same functionality does not exist in the Config connection URI such as the database backend (sql_alchemy_conn) and the redis backend (result_backend)

The idea is if the functionality is implemented for Connections, then the same can be used for Config.

### Use case/motivation

The Config values such as sql_alchemy_conn for database backend can be generated during runtime by using json/parameters from AWS Secrets Manager. This will help also if needed to enable rotations on the same connection.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is already possibly via _CMD and _SECRET env variable. See  https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html

**Comment by SohailChamadia-everestek** [comment]
The _CMD and _SECRET is only valid for the entire connection string stored in secrets backend and not configuration based secret using which connection URI can be created.

**Comment by potiuk** [comment]
> The _CMD and _SECRET is only valid for the entire connection string stored in secrets backend and not configuration based secret using which connection URI can be created.

I do not follow. Can you provide specific example of what you cannot do via _CMD or _SECRET ?

**Comment by SohailChamadia-everestek** [comment]
The _SECRET specifically looks for airflow/config/sql_alchemy_conn in AWS secrets manager where the value needs to be postgresql+psycopg2://<user>@<database> like connection string instead of separate parameters like username, password, dbinstance, etc.
Having a plain connection string causes issue in maintenance as well as rotation after specific interval of time

**Comment by potiuk** [comment]
> The _SECRET specifically looks for airflow/config/sql_alchemy_conn in AWS secrets manager where the value needs to be postgresql+psycopg2://<>@<> like connection string instead of separate parameters like username, password, dbinstance, etc.
> Having a plain connection string causes issue in maintenance as well as rotation after specific interval of time


```
#!/bin/bash
password=$(command to RETRIEVE_CONNECTION_FROM_SECRET)
echo "postgresql+psycopg2://your_user:${password}/.....@<>"
```

**Comment by potiuk** [comment]
It can also be a python script, or whatever script you want BTW.

**Comment by SohailChamadia-everestek** [comment]
Oh okay, got it thanks, but if the password changes during runtime by means of scheduled password rotation, how the update of connection string needs to be handled?

**Comment by potiuk** [comment]
This is handled automatically. If you have connection opened, it's kept open (and password change will not influence it). If there is a new conection opened by SQLAlchemy, then  the `_CMD` is re-executed, so you will get a new password.

**Comment by SohailChamadia-everestek** [comment]
Thanks, will test it and revert back, for `_CMD` if there is any reference documentation, if you point me in the right direction that would be appreciated.

**Comment by potiuk** [comment]
As pointed out above: 

> This is already possibly via _CMD and _SECRET env variable. See https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html
