### ISSUE TITLE
Add subprocess.DEVNULL to LoggingCommandExecutor stdout

### ISSUE THREAD

**Issue by deedmitrij** [apache/airflow#19224]
### Body

According to the @uranusjr request in the following PR https://github.com/apache/airflow/pull/17651#discussion_r735348180, this issue was created to refactor the **LoggingCommandExecutor** class and it's inheritors to substitute the next legacy logic
```
            with open(os.devnull, 'w') as dev_null:
                return subprocess.call(args=cmd, stdout=dev_null, stderr=subprocess.STDOUT, env=env, cwd=cwd)
```
to provide `subprocess.DEVNULL` to `sdtout` instead.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by ShakaibKhan** [comment]
PR for this: https://github.com/apache/airflow/pull/19354

**Comment by eladkal** [comment]
Fixed by https://github.com/apache/airflow/pull/19354
