### ISSUE TITLE
OpenAPI Generator generated python wrapper with a bug. It returns ApiValueError when calling get_variables().

### ISSUE THREAD

**Issue by rolldeep** [apache/airflow#19221]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Ubuntu: 20.04.1 LTS (Focal Fossa)

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==2.0.1
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-sqlite==2.0.

### Deployment

Docker-Compose

### What happened

I've used Airflow's [python wrapper](https://github.com/apache/airflow-client-python) and found out that get_variables() method is not working. I've created [PR](https://github.com/apache/airflow-client-python) in the repo to fix it and @mik-laj [said](https://github.com/apache/airflow-client-python/pull/34#issuecomment-949895751) that I need to fix it in the Airflow core repo. 

### What you expected to happen

I expect that get_variables function returns all variables.

### How to reproduce

```Python
import getpass
import json
import socket

import airflow_client.client
import etl.utils.templates.variable as variable
from airflow_client import client
from airflow_client.client.api import variable_api
from airflow_client.client.model.variable import Variable

local_user = input("Enter Local Airflow Admin username: ")
local_pass = getpass.getpass("Enter Local Airflow Admin password: ")
local_host = socket.gethostbyname(socket.gethostname())
configuration = airflow_client.client.Configuration(
            host=f"{local_host}:8080/api/v1",
            username=local_user,
            password=local_pass)


with client.ApiClient(configuration) as api_client:
    variable_key = "NewVar"
    var_api_instance = variable_api.VariableApi(api_client)
    vars = var_api_instance.get_variables() # raise ApiValueError
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@rolldeep assigned the issue to you. Feel free to open PR.
