### ISSUE TITLE
none_failed_min_one_success trigger rule not working with BranchPythonOperator in certain cases.

### ISSUE THREAD

**Issue by shubhamprasad0** [apache/airflow#19222]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

CentOS Linux 7 (Core)

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp 2.0.1
apache-airflow-providers-http 2.0.1
apache-airflow-providers-imap 2.0.1
apache-airflow-providers-sqlite 2.0.1

### Deployment

Other

### Deployment details

centos 7.3
postgres - 12.2

### DAG 1

In this DAG, I am expecting task_6 to run even when one of task_4 or task_5 get skipped. But, as soon as task_5 skips, task_6 also gets skipped. Ideally, task_6 should have waited for task_4 to finish, then only it should have taken the decision whether to run or skip.
```
import datetime as dt
import time

from airflow import DAG
from airflow.operators.python_operator import BranchPythonOperator
from airflow.operators.dummy_operator import DummyOperator


dag = DAG(
    dag_id="test_non_failed_min_one_success",
    schedule_interval="@once",
    start_date=dt.datetime(2019, 2, 28),
)


def sleep(seconds, return_val=None):
    time.sleep(seconds)
    return return_val


op1 = DummyOperator(task_id="task_1", dag=dag)
op2 = BranchPythonOperator(
    task_id="task_2", python_callable=sleep, op_args=[30, ["task_4"]], dag=dag
)
op3 = BranchPythonOperator(task_id="task_3", python_callable=sleep, op_args=[10, []], dag=dag)
op4 = DummyOperator(task_id="task_4", dag=dag)
op5 = DummyOperator(task_id="task_5", dag=dag)
op6 = DummyOperator(task_id="task_6", dag=dag, trigger_rule="none_failed_min_one_success")

op1 >> [op2, op3]
op2 >> op4
op3 >> op5
[op4, op5] >> op6
```

![image](https://user-images.githubusercontent.com/20776426/138857168-b4cd7fb3-80a4-4989-bc32-981db0938587.png)
![image](https://user-images.githubusercontent.com/20776426/138857227-2fcb8aad-9933-49ef-9e4c-3f9d67d6e644.png)

### DAG 2

This is just a modification of DAG 1 where I have created two more dummy tasks between task_5 and task_6. Now, I get the desired behaviour, i.e. task_6 waits for both task_4 and dummy_2 to finish before taking the decision of whether to run or skip.

```
import datetime as dt
import time

from airflow import DAG
from airflow.operators.python_operator import BranchPythonOperator
from airflow.operators.dummy_operator import DummyOperator


dag = DAG(
    dag_id="test_non_failed_min_one_success",
    schedule_interval="@once",
    start_date=dt.datetime(2019, 2, 28),
)


def sleep(seconds, return_val=None):
    time.sleep(seconds)
    return return_val


op1 = DummyOperator(task_id="task_1", dag=dag)
op2 = BranchPythonOperator(
    task_id="task_2", python_callable=sleep, op_args=[30, ["task_4"]], dag=dag
)
op3 = BranchPythonOperator(task_id="task_3", python_callable=sleep, op_args=[10, []], dag=dag)
op4 = DummyOperator(task_id="task_4", dag=dag)
op5 = DummyOperator(task_id="task_5", dag=dag)
dummy1 = DummyOperator(task_id="dummy1", dag=dag)
dummy2 = DummyOperator(task_id="dummy2", dag=dag)
op6 = DummyOperator(task_id="task_6", dag=dag, trigger_rule="none_failed_min_one_success")

op1 >> [op2, op3]
op2 >> op4
op3 >> op5
op5 >> dummy1 >> dummy2
[op4, dummy2] >> op6
```

![image](https://user-images.githubusercontent.com/20776426/138857664-5d3d03c3-3fd7-4831-9cf5-b8a19ffb8b42.png)

![image](https://user-images.githubusercontent.com/20776426/138856704-17654f90-f867-4289-80cf-dc5756a619b2.png)

### What you expected to happen

I expected task_6 in DAG 1 to wait for both the parent tasks to finish their runs and then run. This is because I have set trigger rule = "none_failed_min_one_success" in task_6. But, this trigger rule is not being respected in DAG 1.

### How to reproduce

The above code can be used to reproduce the issue.

### Anything else

This works fine in version 2.0.2 with trigger rule = "none_failed_or_skipped".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sergxm2** [comment]
Seeing the same issue with BranchPythonOperator / branching and the final task (i.e. task6) being incorrectly skipped instead of being called. This is observed in 2.2.x but not in 2.1.x and not in 2.0.x

**Comment by joetsx** [comment]
> Seeing the same issue with BranchPythonOperator / branching and the final task (i.e. task6) being incorrectly skipped instead of being called. This is observed in 2.2.x but not in 2.1.x and not in 2.0.x To be specific, this is unrelated to returning an "empty" task ID, as we're seeing this happen even when the task ID is returned.

![example_broken_dag](https://user-images.githubusercontent.com/97644927/152047612-ae99b1c5-2038-4365-8c18-397eaf1b2408.png)

In the attached DAG example, tasks{1,2,3} are long running, and fast_task{1,2} get completed fast. The problem happens with fast_task2_x - which trigger rule is set to "none_failed_or_skipped" - but it is getting incorrectly skipped in version 2.2.3 but not in 2.0.1 and not in 2.1.2. This incorrect skipping behavior seem to happen with more complex dependencies, and appears to be broken starting 2.2.x

**Comment by yuqian90** [comment]
The issue reported here started after this change by @kaxil : Fix mini scheduler not respecting wait_for_downstream dep (#18338)[https://github.com/apache/airflow/pull/18338]. `BranchPythonOperator` returning empty or non-existent branches is irrelevant to this issue.

How to reproduce:

```
import pendulum

from airflow.operators.python_operator import BranchPythonOperator
from airflow.sensors.python import PythonSensor
from airflow.operators.python import PythonOperator
from airflow.models import DAG
from airflow.utils.trigger_rule import TriggerRule

with DAG(
    dag_id="example_wrong_skip",
    schedule_interval="@daily",
    catchup=False,
    start_date=pendulum.DateTime(2022, 1, 1),
) as dag:
    branch = BranchPythonOperator(task_id="branch", python_callable=lambda: "task_b")
    task_a = PythonOperator(task_id="task_a", python_callable=lambda: True)
    task_b = PythonOperator(task_id="task_b", python_callable=lambda: True)
    task_c = PythonSensor(task_id="task_c", python_callable=lambda: False)
    task_d = PythonOperator(task_id="task_d", python_callable=lambda: True, trigger_rule=TriggerRule.NONE_FAILED_MIN_ONE_SUCCESS)

    branch >> [task_a, task_b]
    [task_a, task_c] >> task_d
```
![Screen Shot 2022-02-06 at 9 20 51 PM](https://user-images.githubusercontent.com/6637585/152707755-771f3ccd-87ea-4efa-b7e6-5cf9d5b2c268.png)

Observe that `task_d` which has `none_failed_min_one_success` trigger_rule is skipped before `task_c` even finishes. This violates the `trigger_rule` logic of `none_failed_min_one_success`.

This happens because #18338 changed the following line to `include_downstream=True`:

```
            partial_dag = task.dag.partial_subset(
                task.downstream_task_ids,
                include_downstream=True,
                include_upstream=False,
                include_direct_upstream=True,
            )
```

This change caused the `partial_dag` in the "mini scheduler" to include all downstream tasks (even the indirect downstream tasks).

In the reproducing example, once `branch` finishes, it creates a `partial_dag` which includes `task_a`, `task_b` and `task_d` (but does not include `task_c` because it's not downstream of `branch`). Looking at only this `partial_dag`, the "mini scheduler" determines that `task_d` can be skipped because its only upstream task in `partial_dag` `task_a` is in skipped state. This happens in `DagRun._get_ready_tis()` when calling `st.are_dependencies_met()`.


A temporary workaround is to set `schedule_after_task_execution` to `False`. This will stop the bad behaviour (by stopping using "mini scheduler" after each task finishes).

```
schedule_after_task_execution = False
```

A proper fix should be to make the "mini scheduler" evaluate the `trigger_rule` properly like how the scheduler does.

**Comment by kaxil** [comment]
@yuqian90 Would you like to PR a fix?
