### ISSUE TITLE
Add task actions to task view

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#19235]
### Description

A section in the task view that exposes the task actions that are available in the task modal in the dag view. 

### Use case/motivation

We always check the logs to see why a task failed. We then oftentimes want to restart the task by clearing its state. However to do that we need to back out of the task specific view and clear it from task modal in the graph or tree view. It would be a lot more convenient if those actions were surfaced in the task view for easier access.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
I assume this feature request is totally outdated as all (almost all) functionality has been migrated in AIP-38 to Grid view.
