### ISSUE TITLE
Add support for multiple AdAccount when getting Bulk Facebook Report from Facebook Ads Hook

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#19269]
### Description

Currently, the Facebook Ads Hook only supports one `account_id` for every hook(`facebook_conn_id`).  It would be great if we could pass multiple `account_id` from the Facebook connection(`facebook_conn_id`). When multiple `account_id` is provided in the connection, we could support getting insights from one `facebook_conn_id` for all of them rather than creating a Facebook connection for every `account_id`. 

### Use case/motivation

We are using FacebookAdsReportToGcsOperator to export our Facebook Ad data since our infrastructure is on the Google Cloud Platform products and services. This feature will prevent us to create and maintain a connection per account id which will lead us to provide a feature to export multiple CSV files from one connection(one task in a DAG|one operator in a DAG) with one operator. In addition, this feature should not prevent adding multiple Facebook connections per account id to use as it is.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bugraoz93** [comment]
Hey @randr97 and @mik-laj, I think the default API version update reverted in [#18996](https://github.com/apache/airflow/pull/18996). When I pull from the main branch, I am getting `api_version` as an Optional constructor parameter assigned as None. So, I will not change that part. I wanted to inform you all.

**Comment by eladkal** [comment]
The change was to take defaults from the upstream package - whatever that may be. As soon as they update Airflow allign with it. If user needs a specific version he/she can use the api_version param.

**Comment by bugraoz93** [comment]
Hey @eladkal, thank you, yes I saw your changes. I liked the idea behind it. Since Facebook can update its API regularly, we need to continuously update our default version to the latest acceptable one. I think this change has eliminated that maintenance cost in the future. So that, I wanted to state that I will leave that logic as it is with your changes.
