### ISSUE TITLE
Create get_partition, create_partition methods in AWS Glue Catalog Hook

### ISSUE THREAD

**Issue by harsh2911** [apache/airflow#19272]
### Description

Current AWS Glue Catalog Hook does not have all the methods. 
If possible, we can add get_partition and create_partition methods in existing Glue Catalog Hook. 

### Use case/motivation

I do work in Amazon.com. Our team is using Airflow to orchestrate Data Builds for our services. 
In process of data builds, we need to create new Glue partitions for generated data and also retrieve particular Glue partition. Existing Glue Catalog Hook does not contain all the available methods. 

### Related issues

I was not able to find any related existing issues or feature request. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@harsh2911 are you still working on this?

**Comment by harsh2911** [comment]
@eladkal Yes, I will be working on this in next 2 weeks.

**Comment by victorphoenix3** [comment]
Hi @eladkal, I am new to the community and would like to work on this feature request. I looked at the codebase and get_partition method already exists. Should I put up a PR for create_partition and are there any other methods that should be added ?

**Comment by vincbeck** [comment]
Welcome to the community :) Unless I am mistaken `get_partition` does not exist, only `get_partitions` does. Sure! Feel free to create a for these 2 methods and I'll be more than happy to review it.

If you think other methods are needed, feel free to implement them too but implementing these 2 methods is already great :)
