### ISSUE TITLE
Tutorial example backfill function not working

### ISSUE THREAD

**Issue by nocrosstalk** [apache/airflow#193]
I'm following the tutorial and tried to run:

airflow backfill tutorial -s 2015-01-01 -e 2015-01-07

```
sqlalchemy.exc.DataError: (psycopg2.DataError) integer out of range
 [SQL: 'INSERT INTO dag_pickle (pickle, created_dttm, pickle_hash) VALUES (%(pickle)s, now(), %(pickle_hash)s) RETURNING dag_pickle.id'] [parameters: {'pickle_hash': 8784895684905, 'pickle': <psycopg2._psycopg.Binary object at 0x7fd6495c0d88>}]
```

**Comment by mistercrunch** [comment]
Thanks for reporting this bug. I'm not sure why it only affects postgres, but this should do it: https://github.com/airbnb/airflow/commit/97c98b12f517b06c21f834841cb5cf4c0b59255d

You may have to recreate your table with the new code or just alter it straight in the db cli.

**Comment by nocrosstalk** [comment]
Done, worked for me, thank's
