### ISSUE TITLE
Airflow Helm chart fails on Apple Silicon + kind

### ISSUE THREAD

**Issue by ralleman-quasarsat** [apache/airflow#19360]
### Apache Airflow version

2.2.1 (latest released)

### Operating System

Mac OS Big Sur (2021 Mac Air M1)

### Versions of Apache Airflow Providers

-

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Following these instructions https://marclamberti.com/blog/airflow-on-kubernetes-get-started-in-10-mins/ and also the official instructions https://airflow.apache.org/docs/helm-chart/stable/index.html (which are essentially the same), the build fails with `INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:88: [debug] failed post-install: timed out waiting for the condition`.

This was also reported here but was closed: https://github.com/apache/airflow/issues/16176. The fix in this post doesn't help to resolve the issue.

### What happened

Build fails with:

```
% helm install airflow apache-airflow/airflow --namespace airflow --debug
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: .../Library/Caches/helm/repository/airflow-1.2.0.tgz

client.go:299: [debug] Starting delete for "airflow-broker-url" Secret
client.go:328: [debug] secrets "airflow-broker-url" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airflow-fernet-key" Secret
client.go:328: [debug] secrets "airflow-fernet-key" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airflow-redis-password" Secret
client.go:328: [debug] secrets "airflow-redis-password" not found
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 31 resource(s)
client.go:299: [debug] Starting delete for "airflow-run-airflow-migrations" Job
client.go:328: [debug] jobs.batch "airflow-run-airflow-migrations" not found
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job airflow-run-airflow-migrations with timeout of 5m0s
client.go:556: [debug] Add/Modify event for airflow-run-airflow-migrations: ADDED
client.go:595: [debug] airflow-run-airflow-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for airflow-run-airflow-migrations: MODIFIED
client.go:595: [debug] airflow-run-airflow-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:88: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_arm64.s:1130
```

### What you expected to happen

It should deploy Airflow successfully.

### How to reproduce

It happens 100% of the time for me despite many repeat attempts, so simply follow the instructions in the links above and it should happen.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yep. There is no support for ARM images yet. See https://github.com/apache/airflow/issues/15635
