### ISSUE TITLE
Misleading "Update a DAG" REST API example 

### ISSUE THREAD

**Issue by jakubczaplicki** [apache/airflow#19402]
### Describe the issue with documentation

On https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/patch_dag
the payload in the example for PATCH  /dags/{dag_id} suggest that it's possible to update `schedule_interval` which is not true : 
 
```
{
"is_paused": true,
"schedule_interval": {
"__type": "string",
"days": 0,
"seconds": 0,
"microseconds": 0
}
}
```

### How to solve the problem

Update documentation removing the `schedule_interval` part from payload

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
This is a problem with Redoc. It is possible that updating the library will fix the problem.
https://github.com/apache/airflow/blob/f18e4ba612f8ce19bcce7fce612e2409c4afd7ab/airflow/www/yarn.lock#L5779
https://github.com/apache/airflow/blob/f18e4ba612f8ce19bcce7fce612e2409c4afd7ab/docs/conf.py#L652
If that doesn't help, we should report the problem to this project.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/15917

**Comment by jakubczaplicki** [comment]
Thanks @mik-laj  I've created a PR for adding an explicite example : https://github.com/apache/airflow/pull/19465
