### ISSUE TITLE
A parameter name `deploy_mode` is incorrect in spark.rst

### ISSUE THREAD

**Issue by masayuki038** [apache/airflow#19403]
### Describe the issue with documentation

A parameter name `deploy_mode` is incorrect in spark.rst. `deploy-mode` is correct.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Feel free to open a PR
