### ISSUE TITLE
Patch Airflow to use okta email address instead of okta_id as the username

### ISSUE THREAD

**Issue by piyush-daga** [apache/airflow#19422]
### Apache Airflow version

2.1.3

### Operating System

Linux

### Versions of Apache Airflow Providers

flask-appbuilder~=3.3.0
authlib~=0.15.3

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Self-hosted on AWS EKS with the official helm chart.

### What happened

When enabling OAUTH using Okta, the username is replaced by the okta_id, which is a unique identifier to differentiate users but it makes it super difficult to understand which `exact user` is being referenced in a human friendly manner.

Examples:

<img width="1400" alt="Screenshot 2021-10-31 at 7 36 55 PM" src="https://user-images.githubusercontent.com/9255130/139587586-eb36bea8-1a55-41c4-99bd-356501b2d691.png">^ The user-statistics page

<BR>
<img width="1389" alt="Screenshot 2021-10-31 at 7 38 15 PM" src="https://user-images.githubusercontent.com/9255130/139587640-0455e95d-229d-45fb-8971-fab232233bcc.png">^ Or the Audit Logs

### What you expected to happen

Airflow to patch the username to be the `email address` or the `username` of the email address, instead of the okta id.

### How to reproduce

Deploy the Airflow helm chart with okta as the OAUTH provider, steps detailed here: [how-to-authenticate-airflow-users-with-ldapoauth](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-authenticate-airflow-users-with-ldapoauth), login and you'll find that the username is auto-populated with the okta-id.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
In Airflow 2+, we use Flask App Builder for web authentication, so you should report this issue to this project. Here are docs about authentication in Flask App Builder https://flask-appbuilder.readthedocs.io/en/latest/security.html

I am closing because we cannot take any additional actions.
