### ISSUE TITLE
why not use `ON DUPLICATE KEY UPDATE` in XCom.set

### ISSUE THREAD

**Issue by ghostbody** [apache/airflow#19423]
### Description

At present, a `set` method in XCom using two steps:

1. delete all XCom with key `(dag_id, execution_date, task_id)`
2. insert new XCom

However, when the xcom is set frequently, some error will occur, like this:

```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')
``` 

related code lines: https://github.com/apache/airflow/blob/main/airflow/models/xcom.py#L84

### Use case/motivation

using `ON DUPLICATE KEY UPDATE` maybe better?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
This is not supported by all databases so you need to write specific code for each backend, and still keep the current implementation when nothing better is available (e.g. for SQLite IIRC). Feel free to try it.

**Comment by ghostbody** [comment]
> This is not supported by all databases so you need to write specific code for each backend, and still keep the current implementation when nothing better is available (e.g. for SQLite IIRC). Feel free to try it.

reasonable~
