### ISSUE TITLE
Trigger Reserialization on Demand

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#19432]
### Description

Dag serialization is currently out of the hands of the user. Whenever dag reserialization is required, I run this python script. 

```
from airflow.models.serialized_dag import SerializedDagModel
from airflow.settings import Session
session = Session()
session.query(SerializedDagModel).delete()
session.commit()
```

It would be great to have this available from the CLI and/or UI. Or even be able to do it for individual dags without having to delete the whole dag with the trash can button. Also would be worth considering triggering reserialization for any version upgrades that affect dag serialization as part of `airflow db upgrade`.

### Use case/motivation

If your serialized dags get broken for any reason, like the incompatibilities with the changes made in 2.2 recently, reserializing will fix the issue, but it's fairly difficult to trigger reserializing.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Maybe you would like to add such CLI command @collinmcnulty ? This is not dificult

**Comment by collinmcnulty** [comment]
Sure, I'll do that.
