### ISSUE TITLE
Use Job API 2.1 version for databricks provider hooks and 

### ISSUE THREAD

**Issue by jtvmatos** [apache/airflow#19447]
### Description

According with Airflow Databricks hook documentation, this hook use the `latest` endpoint version of the databricks job API. 

```
Databricks hook.
This hook enable the submitting and running of jobs to the Databricks platform. Internally the
operators talk to the ``api/2.0/jobs/runs/submit``
`endpoint <https://docs.databricks.com/api/latest/jobs.html#runs-submit>`_.
```

However, the provided link, point to new 2.1 API version instead of the 2.0 version endpoints used in the job api.

### Use case/motivation

Since there are a new versions of the Jobs API (2.1) the Job API endpoints should be updated to version 2.1:
namely:
```
RUN_NOW_ENDPOINT = ('POST', 'api/2.1/jobs/run-now')
SUBMIT_RUN_ENDPOINT = ('POST', 'api/2.1/jobs/runs/submit')
GET_RUN_ENDPOINT = ('GET', 'api/2.1/jobs/runs/get')
CANCEL_RUN_ENDPOINT = ('POST', 'api/2.1/jobs/runs/cancel')
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@jtvmatos Does #19412 cover this feature request?

**Comment by jtvmatos** [comment]
Hi @josh-fell,
I believe your PR  https://github.com/apache/airflow/pull/19412 resolves this issue.
Can you need any help?

Tks.

**Comment by josh-fell** [comment]
> Hi @josh-fell, I believe your PR #19412 resolves this issue. Can you need any help?
> 
> Tks.

Not my PR but wanted to make you aware of it since you were willing to submit a PR here. Didn't want you to do waste your time with a PR if you didn't need to 😄
