### ISSUE TITLE
DAG Run Views showing information of DAG duration

### ISSUE THREAD

**Issue by surapuramakhil** [apache/airflow#19458]
### Description

In Airflow UI. If we go to Browse --> DAG Runs, then DAG Runs view will be displayed.

Table contains a lot of insightful values likes DAG execution date, Start date, end date, Dag config etc

Request to add DAG duration column in the same table.
DAG Duration i.e. DAG end_date timestamp  - DAG start_date timestamp

### Use case/motivation

Analytics purpose of knowing DAG duration at all DAGs level. So that I can easily find out which DAG  have least and max duration.

### Related issues

Checked open issues. There aren't any

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Should be relatively straightforward to add another column [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L3934).

We already have duration on `/taskinstance` as you can see [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L4314)

**Comment by subkanthi** [comment]
can I take this on please.

**Comment by subkanthi** [comment]
![Screen Shot 2021-11-08 at 3 53 12 PM](https://user-images.githubusercontent.com/17434846/140816457-bb11c716-8e3d-4445-b0a3-36d3edbae7bd.png)
Is it OK to have the duration displayed in seconds? Since duration is not a column in the table, it was removed from order_columns and it wont be sortable.

**Comment by alexInhert** [comment]
Should it have tooltip that explains that the metric is in seconds?
