### ISSUE TITLE
Templated volumes for KubernetesExecutor.

### ISSUE THREAD

**Issue by stefanondisponibile** [apache/airflow#19460]
### Description

When using `PersistenVoume`s or `PVC`s with the Kubernetes Executor it should be possible to build their configuration (at least their names) dynamically.

### Use case/motivation

I want to attach some volume to running worker's containers, but I need to build its name dynamically (e.g. using the `dag_id`, `task_id`, or other values available at "runtime"). I'm using quotes because this wouldn't be actually "runtime", but just before it, since we're still building the pod template.

Any way to do that?
If there's a way, I'm willing to submit a PR.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
Operator by operator, this should be possible with `template_fields` and something similar to [this](https://github.com/apache/airflow/blob/81f92d6c321992905d239bb9e8556720218fe745/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L295-L298), but globally it's tougher.

I'd try and use either [pod_mutation_hook](https://airflow.apache.org/docs/apache-airflow/stable/kubernetes.html#pod-mutation-hook) or [task_instance_mutation_hook](https://airflow.apache.org/docs/apache-airflow/stable/concepts/cluster-policies.html#task-instance-mutation).
