### ISSUE TITLE
'NoneType' object has no attribute 'refresh_from_task'  Error when manually running task instance

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19477]
### Discussed in https://github.com/apache/airflow/discussions/19366

<div type='discussions-op-text'>

<sup>Originally posted by **a-pertsev** November  2, 2021</sup>
### Apache Airflow version

2.2.1 (latest released)

### Operating System

Ubuntu 20.04 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.3.0
apache-airflow-providers-apache-cassandra==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.0.0
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-jdbc==2.0.1
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-presto==2.0.1
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-sqlite==2.0.1

### Deployment

Virtualenv installation

### What happened

Got error when manually run newly created task in already finished dag run (in UI).

### What you expected to happen

"Run" button should work without exceptions.

### How to reproduce

1. Define a dag with some tasks.
2. Create dag run (manually or by schedule)
3. Add new task into dag, deploy code
4. Select new task in UI and press "Run" button

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by potiuk** [comment]
cc: @a-pertsev

**Comment by a-pertsev** [comment]
@potiuk as i can see, attempt of running newly created task will cause redirect with error message.
In previous versions airflow was creating and running new task instance - imho it is more preferable behaviour, beacause it is what user expects airflow to do

**Comment by potiuk** [comment]
I am afraid it is not possible now because of how DAG serializatiion works (and I think this is correct behaviour to be honest). But you can raise a feature request for that.

**Comment by jayceslesar** [comment]
This was fixed in the UI but not the cli
