### ISSUE TITLE
provider Databricks : add cluster API 

### ISSUE THREAD

**Issue by ThAccart** [apache/airflow#19490]
### Description

Add Databricks Cluster API in Databricks Hook

### Use case/motivation

Databricks provider lacks [Cluster API](https://docs.databricks.com/dev-tools/api/latest/clusters.html) access to allow
to CRUD cluster as well as manage clusters (start/restart/delete/...)
Those API are very convenient to control clusters (get status, force shutdown...) and to optimize some specific flows (scale cluster in advance when a coming need is detected )

### Related issues

none

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you the issue!

**Comment by alexott** [comment]
It's interesting use case. But really we have two things here:
* cluster creation/deletion - these tasks are nicely done with [Terraform](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster), for example
* managing the cluster state - stop/start - that's not possible (or very limited) with Terraform

**Comment by alexott** [comment]
@potiuk it looks like it's stale, can you assign it to me?

**Comment by eladkal** [comment]
@alexott are you still working on this issue?

**Comment by alexott** [comment]
Yes, I do

**Comment by Seokyun-Ha** [comment]
Hello, guys!! I opened new PR of Databricks ClusterState utility :)

Any feedback would be appreciated!

https://github.com/apache/airflow/pull/34071

**Comment by Lee-W** [comment]
It seems this issue has not been updated for more than one year and @Seokyun-Ha is not working on it. I assigned this one to @Seokyun-Ha
