### ISSUE TITLE
Multiple SLA miss emails if multiple schedulers are used

### ISSUE THREAD

**Issue by alexbegg** [apache/airflow#19500]
### Apache Airflow version

2.1.4

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Astronomer

### Deployment details

2 schedulers and CeleryExecutor with 2 workers

### What happened

I am receiving 2 identical SLA miss emails for each SLA miss due to having 2 schedulers running.

I know the scheduler is what checks the SLA so I can understand why both schedules sent out a SLA miss, but if the 2 schedulers can know to not run the same task twice, it should also be robust enough to not send the SLA miss email twice.

### What you expected to happen

I should only receive 1 SLA miss email

### How to reproduce

Have 2 schedulers running and set up an SLA (as well as an email configuration or maybe an sla_miss_callback) and set up a task to run past the SLA

### Anything else

If I can get a better understanding of how multiple scheduler work side-by-side I can make a PR to fix this, but I come from the Airflow 1.10.x world and I am new to using 2 schedulers in Airflow.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by EricGao888** [comment]
I'm wondering why you use two schedulers. Are you using multiple headers for high availability?

**Comment by alexbegg** [comment]
> I'm wondering why you use two schedulers. Are you using multiple headers for high availability?

I did that because Astronomer actually recommends it for production: "To increase the speed at which tasks are scheduled and ensure high-availability, we recommend provisioning 2 or more Airflow Schedulers for production environments" As stated under the "Airflow Scheduler" section of his documentation: https://www.astronomer.io/docs/enterprise/v0.25/deploy/configure-deployment#scale-core-resources

However, I don't have another reason to use 2 schedulers, I might switch back to 1. Nethertheless, it still is a sort of bug.

**Comment by uranusjr** [comment]
What should happen if a task misses SLA in one scheduler but was picked up by another? Or is this scenario impossible?
