### ISSUE TITLE
Airflow does not load default connections

### ISSUE THREAD

**Issue by BrunoRizziBTG** [apache/airflow#19529]
### Official Helm Chart version

main (development)

### Apache Airflow version

2.2.1 (latest released)

### Kubernetes Version

1.20

### Helm Chart configuration

```

---

  dags: 

    persistence: 

      storageClassName: "gp2"

  logs: 

    persistence: 

      storageClassName: "gp2"

  redis: 

    persistence: 

      storageClassName: "gp2"

  webserver: 

    service: 

      annotations: 

        service.beta.kubernetes.io/aws-load-balancer-internal: "true"

      type: "LoadBalancer"

  workers: 

    persistence: 

      storageClassName: "gp2"

  extraEnv: |-

    - name: AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS

      value: "True"

    - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG

      value: "True" 


```

### What happened

When I try to deploy my airflow with helm chart the default connections does not appears in UI and in the database, I checked both.
Connections like aws_default and emr_default does not appears.

### What you expected to happen

I expect the connections to appear in the database, because with the variable  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS set to true the connections have to be created in the database, but it is not happening.

### How to reproduce

Use the custom values that I pass, change the "gp2" storage class to yours and the annotation of the load balancer too. 
With this you can run the helm chart and check the connections in ui and in postgres and you will see that no default connection was created.

### Anything else

I run this in EKS environment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The 'load_default_connections" parameter is only valid at "db init" time and they are only there for ease of development setup - they are not recommended for production setup. We are running "db upgrade" only. If you need to create some connections upfront, you need to do it outside of the helm chart
