### ISSUE TITLE
Add proxy argument for PythonVirtualEnvOperator during pip install

### ISSUE THREAD

**Issue by theelderbeever** [apache/airflow#19522]
### Description

The `PythonVirtualEnvOperator` can't `pip install` the virtualenv behind a corporate proxy. The addition of a `proxy` arg to the`PythonVirtualEnvOperator` and consequently to the underlying `pip install --proxy` command would be valuable.

### Use case/motivation

Sometimes I have Airflow deployments running on clusters that are behind a corporate proxy. In these instances it is nice to not set environment variable proxies so that the workers, webserver, and scheduler can easily see other services internal to the proxy/cluster. This however causes `pip` to not be able to connect to pypi and fails to install libraries.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can do proxy and much more using pip config file or environment variables: https://pip.pypa.io/en/stable/topics/configuration/#pip-config-file

Is not that enough ?

**Comment by theelderbeever** [comment]
@potiuk So it is. You taught me something today. Thank you for the fast response time!
