### ISSUE TITLE
Always re-serialise DAGs after an upgrade

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#19533]
### Description

https://github.com/apache/airflow/issues/19519#issuecomment-965621090

> Also I think we have a new "dags reserialize" coming - #19471 - which is really good idea because the "serialized" form of DAGs is pretty safe to delete and recreate.

> I just wonder if this is not something that we should always do after/during upgrade "just in case". It might slow-down initial dag refresh, but at least we can be sure that everything in serialized dags is "correct".

Recording this in a new issue so it doesn’t get forgotten.

### Related issues

A way to manually trigger DAG reserialisation:
#19471

If a previous-serialised DAG is not being compatible with new semantics, a bug can be raised at a confusing location:
#19519

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dstandish** [comment]
closed following discussion on https://github.com/apache/airflow/pull/19637
