### ISSUE TITLE
Miscellaneous documentation typos

### ISSUE THREAD

**Issue by jplauri** [apache/airflow#19581]
### Describe the issue with documentation

Recently starting our with Airflow I've been reading parts of the documentations quite carefully. There's at least two typos that could be fixed. First, looking at [Module management](https://airflow.apache.org/docs/apache-airflow/stable/modules_management.html) I see:  "You can see the `.ariflowignore` file at the root of your folder." I'm rather confused by this, since when looking at [module_management.rst](https://github.com/apache/airflow/blob/main/docs/apache-airflow/modules_management.rst) it seems to say "You can see the `.airflowignore` file at the root of your folder" (no typo). Why's that?

Second, looking at the docs for [GenericTransfer](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/generic_transfer/index.html), the explanation for `destination_conn_id (str)` I believe should be e.g., `destination connection` and not `source connection` (compare with `source_conn_id (str)`). However, I'm unable to find the corresponding doc from the repo. When clicking on "Suggest a change on this page" I end up with 404. 

### How to solve the problem

See above for the suggested fixes as well. I'd be happy to submit a PR too (but see some questions above as well).

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Feel free to submit the PR!

The GenericTransfer documentation is automatically generated from Python docstrings with [Sphinx Autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). The actual line is in `airflow/operators/generic_transfer.py`.

**Comment by easontm** [comment]
Hi @jplauri, could you include this doc change into your PR as well?

In `airflow/airflow/www/templates/airflow/dags.html`, line 61:
```
      in <a href={{ get_docs_url("installing/upgrading.html") }}><b>Upgrading</b></a>.
```
to
```
      in <a href={{ get_docs_url("installation/upgrading.html") }}><b>Upgrading</b></a>.
```

**Comment by potiuk** [comment]
@easontm - it's equally easy to submit your onw change. Just use "Suggest a change on this page" button at bottom-right of the page and it will open a PR for you that you will be able to submit using GitHub UI - as easy as commenting on the issue.

**Comment by easontm** [comment]
Ah, the issue is not _in_ the docs themselves, rather the DAG list page which I don't think has that button. I'll make my own PR if I have the time
