### ISSUE TITLE
Clearing a defered task instance in deferred state does not clear its next_method

### ISSUE THREAD

**Issue by Greetlist** [apache/airflow#19612]
### Apache Airflow version

2.2.1

### Operating System

Ubuntu 16.04

### Deployment

Other

### What happened

When I mark a defferd task to Failed-State then clear it or clear a defferd task which in Defferd-State, this task is marked success immediately.
I check the task instance table, this task's next_method is not null when I clear this task.This cause task's execute function is replaced by next_method function.

### What you expected to happen

When I clear a defferd task, I want to re-judge it's trigger condition, re-execute the execute function.

### How to reproduce

Sensor
``` python
class ExternalTaskFromOtherAirflowSensor(BaseSensorOperator):
    def execute(self, context):
        trigger = ExternalTaskFromOtherAirflowTrigger(args)
        self.defer(trigger=trigger, method_name="execute_complete")

    def execute_complete(self, context, event=None):
        return
```
Trigger
``` python
class ExternalTaskFromOtherAirflowTrigger(BaseTrigger):
    def _get_task_instance_state(self):
        sql_query = "SELECT state FROM {}.task_instance WHERE dag_id = '{}' and run_id like '%{}%';".format(
            self.old_airflow_db_name,
            self.old_external_dag_id,
            self.old_external_task_id,
            self.old_external_execution_date_str
        )
    async def run(self):
        while self._get_task_instance_state() == False:
            await asyncio.sleep(5)
        yield TriggerEvent('success')
```

1. Clear this task when it is in **defferd** State.
2. Mark this task as **failed** and clear this task. 

Both operations above will cause this task is marked as **success** instead of re-execute the execute function.

### Anything else

Similar issue:
#18146
#19120

I try to add this code in **models/taskinstance.py clear_task_instances function**
![image](https://user-images.githubusercontent.com/18439743/141941165-a7a8c738-23db-45e9-be1d-cf901c209ee2.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Your added code makes sense. Feel free to start a pull request for this.

**Comment by malthe** [comment]
We can close this now then right?

**Comment by jochenott** [comment]
I believe this can be closed, as the according code change was made via #23929

**Comment by uranusjr** [comment]
Thanks for catching this

**Comment by park-peter** [comment]
Can we reopen this? I just tested the fix in astronomer image 2.3.3-2 and clearing a deferred task will still mark the task as success immediately without executing. The other case of marking the task as failed first then clearing the task does re-execute the task.

**Comment by Greetlist** [comment]
After adding this code, In my env, this problem is disappear. of course, I do not use ```astronomer image 2.3.3-2```, I just deploy airflow on host machine. Try to attach into container and check source code ```sudo docker exec -ti $container_id /bin/bash ``` @park-peter

**Comment by uranusjr** [comment]
Should probably do it in a new issue instead with fresh reproduction steps.
