### ISSUE TITLE
Deprecate template variables ts etc. and change the default log_filename_template

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#19625]
### Body

Context: https://github.com/apache/airflow/issues/19058#issuecomment-947023469

Note that changing the default `log_filename_template` have a lot of backward compatibility implications, and the solution needs to be cheap enough. Not a trivial job.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by ashb** [comment]
For AIP-42 we'll need to add some form of "task_mapping_id" in here too

**Comment by uranusjr** [comment]
Copying from Slack to record the thoughts:

> My current best idea is to create a table tracking log template changes and create a fk on TaskInstance pointing to it. A row is inserted to the table when Airflow launches whenever the template does not match the last row in the table.

The plan is to piggyback this operation on #18439, right after migrations are done.

When a TaskInstance is created, a foreign key to this tracking table is populated to signify what log filename template this TI will use. `render_log_filename` will use this fk to render the filename, instead of accessing the config.

Existing TaskInstance rows will not be backfilled for performance reasons. If this fk is NULL on TaskInstance, it will simply use the first row in the tracking table for rendering.

**Comment by uranusjr** [comment]
Yes I think so.

**Comment by uranusjr** [comment]
PR that actually flipped the switch: #21495
