### ISSUE TITLE
Airflow connection forms show fields that should be hidden

### ISSUE THREAD

**Issue by bensta** [apache/airflow#19648]
### Apache Airflow version

2.2.1

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-airbyte==2.1.1
apache-airflow-providers-alibaba==1.0.0
apache-airflow-providers-amazon==2.3.0
apache-airflow-providers-apache-beam==3.0.1
apache-airflow-providers-apache-cassandra==2.1.0
apache-airflow-providers-apache-drill==1.0.1
apache-airflow-providers-apache-druid==2.0.2
apache-airflow-providers-apache-hdfs==2.1.1
apache-airflow-providers-apache-hive==2.0.2
apache-airflow-providers-apache-kylin==2.0.1
apache-airflow-providers-apache-livy==2.1.0
apache-airflow-providers-apache-pig==2.0.1
apache-airflow-providers-apache-pinot==2.0.1
apache-airflow-providers-apache-spark==2.0.1
apache-airflow-providers-apache-sqoop==2.0.2
apache-airflow-providers-asana==1.1.0
apache-airflow-providers-cloudant==2.0.1
apache-airflow-providers-databricks==2.0.2
apache-airflow-providers-datadog==2.0.1
apache-airflow-providers-dingding==2.0.1
apache-airflow-providers-discord==2.0.1
apache-airflow-providers-facebook==2.0.1
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.0.0
apache-airflow-providers-hashicorp==2.1.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-jira==2.0.1
apache-airflow-providers-microsoft-azure==3.2.0
apache-airflow-providers-opsgenie==2.0.1
apache-airflow-providers-pagerduty==2.0.1
apache-airflow-providers-plexus==2.0.1
apache-airflow-providers-qubole==2.0.1
apache-airflow-providers-salesforce==3.2.0
apache-airflow-providers-segment==2.0.1
apache-airflow-providers-sendgrid==2.0.1
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-snowflake==2.2.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-tableau==2.1.1
apache-airflow-providers-telegram==2.0.1
apache-airflow-providers-vertica==2.0.1
apache-airflow-providers-yandex==2.1.0
apache-airflow-providers-zendesk==2.0.1

### Deployment

Virtualenv installation

### Deployment details

pip 21.2.4
Python 3.8.10
virtualenv 20.2.2

### What happened

Connection type specific fields in the airflow connection form remain visible when a different connection type is selected. 
Note in the screenshot: 
Connection type Email is selected, but Blob Storage Login and Blob Storage Key are still visible. 
These fields stem from the connection type that was selected previously (azure blob storage connection)

![image](https://user-images.githubusercontent.com/9579702/142216932-5ef4c634-bd60-45ff-bed5-920a18069f98.png)

### What you expected to happen

I expected that all non relevant connection fields are hidden when I select different connection types. 

### How to reproduce

1. Install a new airflow instance with many extras installed (unsure if it is relevant, but it is our case)
2. Go to connection -> add , select connection type Azure 
3. Observe, that azure specific fields are shown (e.g.  Azure Client ID )
4. Select connection type Email
5. Observe that Azure specific fields are still show (e.g.  Azure Client ID )

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
This is a bug and should be fixed with #19411.

**Comment by bensta** [comment]
Thanks for the info!

**Comment by bbovenzi** [comment]
@josh-fell should we close the issue then if fix is already merged?

**Comment by josh-fell** [comment]
> @josh-fell should we close the issue then if fix is already merged?

Yes please.
