### ISSUE TITLE
facing issue to integrate airflow 2.2.2 with mssql as meta store

### ISSUE THREAD

**Issue by zubairshahzadarain** [apache/airflow#19651]
### Body

facing issue to integrate airflow 2.2.2 with mssql as meta store

sqlalchemy.exc.IntegrityError: (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert explicit value for identity column in table 'ab_permission' when IDENTITY_INSERT is set to OFF. (544) (SQLExecDirectW)") [SQL: INSERT INTO ab_permission (id, name) OUTPUT inserted.id VALUES (NEXT VALUE FOR ab_permission_id_seq, ?)] [parameters: ('can_read',)] (Background on this error at: https://sqlalche.me/e/14/gkpj)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Correct. Mssql is not supported in 2.2. We have experimental support that is coming in 2.3 https://github.com/apache/airflow/blob/main/README.md#requirements
