### ISSUE TITLE
apache-airflow-providers-ssh 2.2.0 has wrong sshtunnel dependency requirements <0.2,>=0.1.4

### ISSUE THREAD

**Issue by vitalibertas** [apache/airflow#19656]
### Apache Airflow Provider(s)

sftp

### Versions of Apache Airflow Providers

apache-airflow-providers-ssh 2.1.1

### Apache Airflow version

2.1.4

### Operating System

Google Cloud Composer

### Deployment

Composer

### What happened

When trying to upgrade to apache-airflow-providers-ssh 2.2.0, there is a bad dependency requirement for an old version of sshtunnel. "apache-airflow-providers-ssh 2.2.0 has requirement sshtunnel<0.2,>=0.1.4, but you have sshtunnel 0.4.0."

### What you expected to happen

Allow for the actual sshtunnel dependency requirements of >=0.3.2,<0.5

### How to reproduce

Install apache-airflow-providers-ssh 2.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
This is already fixed in 2.3.0.
