### ISSUE TITLE
Pgbouncer auth type cannot be configured

### ISSUE THREAD

**Issue by freget** [apache/airflow#19654]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.1

### Kubernetes Version

1.20.9

### What happened

The default pgbouncer config generated by the helm chart looks something like

```
[databases]
...

[pgbouncer]
pool_mode = transaction
listen_port = 6543
listen_addr = *
auth_type = md5
auth_file = /etc/pgbouncer/users.txt
stats_users = <user>
ignore_startup_parameters = extra_float_digits
max_client_conn = 200
verbose = 0
log_disconnections = 0
log_connections = 0

server_tls_sslmode = require
server_tls_ciphers = normal
```

If the database to connect against is Azure Postgresl, the auth type `md5` [does not seem](https://github.com/pgbouncer/pgbouncer/issues/325) to be supported. Hence, we need to add a configuration flag to change the auth type to something else in the helm chart. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by freget** [comment]
kind:feature would probably be the better tag, but I'm not able to change this (or I do not find how).

**Comment by potiuk** [comment]
(BTW. In the future - you can choose "new feature" from the issue types when creating new issue @freget )
