### ISSUE TITLE
UI broken in current main branch code

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#19675]
### Apache Airflow version

main (development)

### Operating System

macOS

### Deployment

Other Docker-based deployment

### What happened

I am running the airflow in development mode and drop downs and icons in the UI is broken. It prevents me to add new connections to test.

### What you expected to happen

Proper rendering of UI buttons and icons. 

### How to reproduce

Pull the recent code from main branch and start the development env using breeze.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
Attaching the image for reference. 
<img width="1359" alt="Screenshot 2021-11-17 at 2 59 42 PM" src="https://user-images.githubusercontent.com/10162465/142406600-80f78844-1632-4789-b6a7-23b99b9fea5e.png">
 


<img width="1359" alt="Screenshot 2021-11-17 at 2 58 50 PM" src="https://user-images.githubusercontent.com/10162465/142406585-1be5f0b8-4554-4dd6-aeb5-45512b4fe464.png">

**Comment by eladkal** [comment]
Wasn't this solved by https://github.com/apache/airflow/pull/19661 ?
are you on latest main ?

**Comment by Bowrna** [comment]
Yes, it's working now. i didn't pull the recent changes and started with old changes in my local. Sorry for this. This issue is invalid now.
