### ISSUE TITLE
Display task documentation when hovering on the task

### ISSUE THREAD

**Issue by yarong-lifemap** [apache/airflow#19674]
### Description

It would be great if task documentation wouldn't be hidden within the task instance page, but rather displayed when hovering over the task.

### Use case/motivation

In complex DAGs, having access to this allows access to documentation with a few less clicks per task

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I agree we should make the documentation more visible. But I don't think the tooltip is the right place. It already has a lot in it. I do want to make the task instance page more visible. 
The next UI task is displaying the tree view side-by-side with others so it is easier to see how everything is related. The Task Instance page will certainly be part of that.
