### ISSUE TITLE
Can't launch Redis container on a cluster enforcing MustRunAsNonRoot policy

### ISSUE THREAD

**Issue by tomasgatial** [apache/airflow#19681]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.2 (latest released)

### Kubernetes Version

1.20

### Helm Chart configuration

default

### Docker Image customisations

None

### What happened

Unable create Redis containers when using cluster wide`PodSecurityPolicy` `MustRunAsNonRoot`.

### What you expected to happen

Default Redis runtime should be non-root to run out-of-box on clusters that enforce these security policies.

References: 
https://github.com/helm/charts/blob/master/stable/redis/values.yaml#L183
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L74

### How to reproduce

enable cluster wide`PodSecurityPolicy` `MustRunAsNonRoot` and install the chart with default values. 

### Anything else

It is possible to work around using externalRedis. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you like to provide a fix for it @tomasgatial ? That does not seem complex - just setting runAsUser on the redis container in the helm chart and testing it. Nice way to join the > 1800 contributors to Airfllow and pay back for the free software you use.

**Comment by tomasgatial** [comment]
Sure, here comes. @potiuk thanks for encouragement!

**Comment by sumeshpremraj** [comment]
Looks like this is resolved by #22182 🤔

**Comment by potiuk** [comment]
closing then. @tomasgatial please check if it fixes it, and let us know- we can always re-open.
