### ISSUE TITLE
Feature Request - Sqoop hook and operators

### ISSUE THREAD

**Issue by syvineckruyk** [apache/airflow#197]
to be defined.

**Comment by cgelman** [comment]
I want to +1 this.

**Comment by chenghaibo** [comment]
I want to +1 this

**Comment by rakeshsingh** [comment]
I want to +1 this

**Comment by notifytovishal** [comment]
+1 Can this be done using https://pypi.python.org/pypi/sqoopy/ ? Can this be defined !!

**Comment by syvineckruyk** [comment]
We currently have a functioning SqoopOperator that we use internally. Currently the feature set is based on our need and may be considered rather limited. I would be interested to hear what the community is looking in terms of features from a SqoopOperator.

Currently our Sqoop Operator has the benefit of using the connections from Airflow ... so no need to to have your connection strings and credentials in your code or command parameter. It takes tool (import,export etc...), args, kwargs and templated option file as parameters.

**Comment by hyperborea** [comment]
@syvineckruyk any chance to get a sneak peak at your current implementation?

**Comment by syvineckruyk** [comment]
@hyperborea sure thing ... ill get a pr going and update here.

**Comment by mafc** [comment]
Any updates on this?

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-airflow/pull/1489
