### ISSUE TITLE
glue job error for render the script_args parameter

### ISSUE THREAD

**Issue by Arwiim** [apache/airflow#19717]
### Apache Airflow version

2.0.1

### Operating System

LInux

### Versions of Apache Airflow Providers

2.0.1

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Is running in a EKS cluster

### What happened

im trying to render a macro in the arguments of the glue operator
![image](https://user-images.githubusercontent.com/53288078/142686116-7703313b-8055-4834-b6ae-06fb01402cd4.png)
but in glue, shows the literrly string
![image](https://user-images.githubusercontent.com/53288078/142686639-b965228c-8066-44b7-a8e4-5b94e278f8eb.png)

### What you expected to happen

I want it to render the parameter well, in the case of the python operator it does it without problems

### How to reproduce

import airflow.providers.amazon.aws.operators.glue AwsGlueJobOperator
create a task with that operator, and pass the argument script_args
in the scripts_args pass a macro for render

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
You are probably using outdated version of the amazon provider.
`script_args` is templated field.
If the issue is reproducible with the latest amazon provider version please comment and add reproduce example.
