### ISSUE TITLE
Add UI collapse property to TaskGroups

### ISSUE THREAD

**Issue by tothandor** [apache/airflow#19773]
### Description

Multiple chained groups of tasks yield a visual clutter in the UI Tree View, with many repetitions of the same leaf tasks. In some situations this may be desirable, but in others a simple "group level" tree view would be more comprehensible, where on could descend into a group. 

Subdags helped to contain the scope of view to a subdag level, similarly to browsing folders/directories on a filesystem. Such feature would help to leave subdags behind.

### Use case/motivation

Please consider the DAG layout below in graph view:

![image](https://user-images.githubusercontent.com/4449214/143026392-ee3026dd-c038-4c8f-8b9d-975fffe468b9.png)

And in tree view:
![image](https://user-images.githubusercontent.com/4449214/143027303-73024d67-7a96-4d2f-b0db-c32c050a89d5.png)

The same tasks appear over and over again, filling up the page, and therefore hindering to identify a possible failure.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
The tree view on main has already been reworked for 2.3 -- see https://github.com/apache/airflow/pull/18675

I think this new Tree view addresses your complaints -- see 
<img width="677" alt="Screen Shot 2021-10-07 at 10 23 11 AM" src="https://user-images.githubusercontent.com/4600967/136414969-3f69fdd6-2d6c-4ad1-b05d-c72f323ed3c4.png">

If I've misunderstood please let us know and we can re-open this issue

**Comment by tothandor** [comment]
This is pretty close to what I would need. Thanks a lot for your reply and checking this out, I am closing the issue.

**Comment by potiuk** [comment]
> Just a final remark, I would not reopen the issue for sake of that, but still it would be great if the initial collapsed state of a group could be specified in advance.

You can always open a separate PR request - taking as the base what you see in main
