### ISSUE TITLE
DAGRun API endpoint returns status 500 for some run states

### ISSUE THREAD

**Issue by frapa-az** [apache/airflow#19836]
### Apache Airflow version

2.0.2

### Operating System

Unknown

### Deployment

Other Docker-based deployment

### What happened

I am using the REST API. 

When I make a request to the [DAGRun endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_runs) and one DAGRun is in state skipped, the request fails with 500 internal server error:

```text
{
    "detail": "'skipped' is not one of ['success', 'running', 'failed']\n\nFailed validating 'enum' in schema['allOf'][0]['properties']['dag_runs']['items']['properties']['state']:\n    {'description': 'DAG State.',\n     'enum': ['success', 'running', 'failed'],\n     'readOnly': True,\n     'type': 'string',\n     'x-scope': ['',\n                 '#/components/schemas/DAGRunCollection',\n                 '#/components/schemas/DAGRun']}\n\nOn instance['dag_runs'][1]['state']:\n    'skipped'",
    "status": 500,
    "title": "Response body does not conform to specification",
    "type": "https://airflow.apache.org/docs/2.0.2/stable-rest-api-ref.html#section/Errors/Unknown"
}
```

This seemingly happens because the state of the run is skipped, and not one of those three.

### What you expected to happen

I would expect `state=skipped` to be returned by the API.

### Anything else

I have no access and do not know how AirFlow was set-up in our current system.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
WTH, a DAG run is not supposed to be skipped. There’s a serious bug somewhere.

**Comment by ephraimbuddy** [comment]
@frapa-az How can we reproduce DagRun to be in `skipped` state?

**Comment by frapa-az** [comment]
@ephraimbuddy Thanks for answering. I manage to reproduce it by simply pausing the DAG (not the DAG run). I do not know exactly if this is timing dependent, but for me it seems rather easy to reproduce 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/68114433/143895776-e93240ab-b9a0-4b9d-a2a4-152827820f03.png">

I have a few in the last few days, so it's not impossible:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/68114433/143896114-e05c8749-a7f4-49a6-8c98-29cac2974f58.png">

**Comment by uranusjr** [comment]
Just curious, are any of your DAGs happen to be subDAGs?

**Comment by frapa-az** [comment]
@uranusjr what do you mean by subDags? I do not unfortunately know the details because we have an abstraction layer on top, but I think there's actually a single DAG that runs all pipelines, creating tasks dinamically based on a json bspec. Does that help?

**Comment by frapa-az** [comment]
@uranusjr Wow, thanks for finding out. I can ask the team responsible for this if they give me more details to ensure that this is really the case. Most probably I'll come back tomorrow with an answer.

**Comment by uranusjr** [comment]
When you do, it’d be most awesome if you could also tell them we appreciate them pushing how Airflow works to the limit that this obscure bug can surface 😛

**Comment by frapa-az** [comment]
I digged the code. We're not using Sub-DAGs, but we do something really weird with callbacks. So after all, this is our misuse of AirFlow and not a bug in AirFlow itself. Here the relevant snippet (I believe):

```python
def on_failure_callback(context):
    if isinstance(context['exception'], TaskCanceledException):
        session = settings.Session()
        context['task_instance'].set_state(State.SKIPPED, session=session)
        context['dag_run'].state = State.SKIPPED
        session.merge(context['dag_run'])
        session.commit()
    
task.on_failure_callback = on_failure_callback
```

However, maybe it would be good to add some validation to the states before saving them to avoid that they go to such inconsistent states? I find it a little strange that AirFlow accepts this to be saved into the database, but then validates it when returning it from the API.

**Comment by potiuk** [comment]
> However, maybe it would be good to add some validation to the states before saving them to avoid that they go to such inconsistent states? I find it a little strange that AirFlow accepts this to be saved into the database, but then validates it when returning it from the API.

Currently you are fully in power of what you do with Airflow code, but power also means responsibility. This is the basic premise of Airlfow "open DB access" mode that Airflow currently supports. There is nothig to prevent any DB operations from the code point of view. You'd have to implement complex Databse triggers or tap into SQLAlchemy logic to prevent this (but the latter could be bypassed).  Airflow supports "raw" DB operation. Use those powers wisely.

And this one is not very disruptive opration. Currently in Airlfow you can literally delete whole database from callback if you want. So preventing this case is like trying to plug a small hole with your finger where half of the bottom of your boat is missing. 

However, we are already working on Multitenancy implementation and specifically it includes DB-Isolation mode, where you won't be able to directly execute DB operations, but you will have some API methods to call (including set_task state on your task). 

Until there it makes litle sense to do anything with it.

See the notes here: (https://docs.google.com/document/d/19d0jQeARnWm8VTVc_qSIEDldQ81acRk0KuhVwAd96wo/edit).

**Comment by potiuk** [comment]
Closing this one for now then

**Comment by uranusjr** [comment]
FWIW, we can pretty trivially validate state values on assignment (both on `DagRun` and `TaskInstance`, even though the latter one isn’t the problem here). Feel free to create a pull request for this. I created #19898 for this.

**Comment by potiuk** [comment]
> FWIW, we can pretty trivially validate state values on assignment (both on `DagRun` and `TaskInstance`, even though the latter one isn’t the problem here). Feel free to create a pull request for this. I created #19898 for this.

Ah right!
