### ISSUE TITLE
Xcom: the parameters of  key named value is too long

### ISSUE THREAD

**Issue by byr18** [apache/airflow#19834]
### Apache Airflow version

2.0.2

### Operating System

Ubuntu:18.04.1 

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==1.0.0
apache-airflow-providers-http==1.0.0
apache-airflow-providers-imap==1.0.0
apache-airflow-providers-sqlite==1.0.0
apache-airflow-providers-ssh==1.0.0

### Deployment

Other

### What happened

I use the SSHOperator,then  i get the error: 
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'value' at row 1")
[SQL: INSERT INTO xcom (`key`, value, timestamp, execution_date, task_id, dag_id) VALUES (%(key)s, %(value)s, %(timestamp)s, %(execution_date)s, %(task_id)s, %(dag_id)s)]
[parameters: {'key': 'return_value', 'value': b'"cnVuIHJlZ2lzdGVyIC4uLgpweXRob24zIC9kYXRhL3Rlc3RfZGF0YS9haXJmbG93L21vZGVsLXZpYS1mYWNlLXgtZGVidWctM2QvUmVnVXNlcnNNcC5weSAtLXBhcmFtcyB7Imhvc3QiOiIxNzI ... (155033 characters truncated) ... 5q+U6L+H5bCPIiwicmVxdWVzdF9pZCI6IjI5OTkwMDkyLThjNDAtNDIzYi04OGJiLWMyN2EzZTBmZDc2ZSJ9CidUb3RhbCB0aW1lOiAxNjM3ODMzNTAzLjc3NzM2NTQnCidGaW5pc2hlZCEnCg=="', 'timestamp': datetime.datetime(2021, 11, 25, 9, 45, 4, 7199), 'execution_date': datetime.datetime(2021, 11, 25, 9, 44, 51, 99638), 'task_id': '*', 'dag_id': '*'}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)

I guess the xcom saved some unnecessary information somewhere I don't know，example：the error code ,which task print 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by byr18** [comment]
I try to delete all python print, then the error is disappeared ，but this is not that  I want,I should the print the information. 
I want to know Whether saving information is a default mechanism?

**Comment by ephraimbuddy** [comment]
Consider using a custom xcom backend. Xcom is not made to store large values. See https://github.com/apache/airflow/blob/cab6d96a463e227961b8e487dd000199f4864978/airflow/models/xcom.py#L39

**Comment by ashb** [comment]
The other option is to set `do_xcom_push=False` on your SSHOperator.
