### ISSUE TITLE
Refactor poll_query_status in EMRContainerHook

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#19877]
### Body

The goal is to refactor the code so that we can remove this TODO
https://github.com/apache/airflow/blob/7640ba4e8ee239d6e2bbf950d53d624b9df93059/airflow/providers/amazon/aws/hooks/emr_containers.py#L174-L176

More information about the concerns can be found on https://github.com/apache/airflow/pull/16766#discussion_r668089559

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by patrikhv** [comment]
Hi. I would like to work on this issue. Can you assign it to me?

**Comment by uranusjr** [comment]
Go ahead!

**Comment by dacort** [comment]
Thanks @patrikhv - let me know if I can help in any way! (original PR contributor and EMR team member)

**Comment by patrikhv** [comment]
Hi, I am working on that, but I do not have any idea how to refactor it. I already just did a more explicit call, if the query is in a completed stage. Can you give me any tips?

**Comment by ferruzzi** [comment]
Had a chat with dacort.  They mentioned that the change they had in mind was that we don't actually confirm that the state is at a terminal state, only that it is not at an intermediate state.  I can't think of any other changes I'd make to it.

**Comment by ferruzzi** [comment]
@patrikhv - It looks to me like adding in the explicit "is it a terminal state?" check is all that is needed here.  You want to put in the PR?

**Comment by eladkal** [comment]
@ferruzzi since patrikhv is not working on it. Do you want to put a PR to solve this?

**Comment by ferruzzi** [comment]
@eladkal I have a few other things I'm working on.  I can have a look when I get time, but it'll likely be a couple weeks unless somebody gets to it before then.

**Comment by victorphoenix3** [comment]
Hello! I am new to the community and would like to take this on as my first issue. May I submit a PR for this? @eladkal

**Comment by potiuk** [comment]
Feel fre to attempt it :). Maybe @ferruzzi will be able to help with reviewing it :)
