### ISSUE TITLE
Incorrect doc reference

### ISSUE THREAD

**Issue by kazanzhy** [apache/airflow#19906]
### Apache Airflow Provider(s)

google
Incorrect doc reference

### Apache Airflow version

2.2.2 (latest released)

### Operating System

ubuntu

### Deployment

Docker-Compose

### What happened

It seems to be a wrong ref here:
https://github.com/apache/airflow/blob/33a4502f68be6b25fbccb96ed1832c5b527bb02a/airflow/providers/google/provider.yaml#L207

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you be willing to correct it please with PR ? BTW. There is no need to open issue - opening a PR to fix without issue is much faster and simpler.

**Comment by kazanzhy** [comment]
@potiuk I'm sorry.
I assumed that it might be okay to have reference to Yandex DataProc instead of Google one. 
Let me close this issue and open PR

**Comment by kazanzhy** [comment]
Just found there almost the same
https://github.com/apache/airflow/blob/15a9d7910cc0d2ca0ed97e3535a6b85edcf16af8/airflow/providers/google/provider.yaml#L240
