### ISSUE TITLE
DuplicateTaskIdFound when reusing tasks with task_group decorator

### ISSUE THREAD

**Issue by jceresini** [apache/airflow#19902]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

MacOS 11.6.1

### Versions of Apache Airflow Providers

$ pip freeze | grep airflow
apache-airflow==2.2.2
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other

### Deployment details

`airflow standalone`

### What happened

Exception raised :     

```
raise DuplicateTaskIdFound(f"Task id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'do_all_things.do_thing__1' has already been added to the DAG
```

### How to reproduce

* Add the following python file to the `dags` folder:

```python
from datetime import datetime

from airflow.decorators import dag, task, task_group


@dag(start_date=datetime(2023, 1, 1), schedule_interval="@once")
def test_dag_1():
    @task
    def start():
        pass

    @task
    def do_thing(x):
        print(x)

    @task_group
    def do_all_things():
        for i in range(5):
            do_thing(i)

    @task
    def end():
        pass

    start() >> do_all_things() >> end()


test_dag_1()
```

* Start airflow by running `airflow standalone`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jceresini** [comment]
I just noticed that the above works if I ditch the for loop in the _task_group_, and run each _task_ separately.

**Comment by uranusjr** [comment]
Yeah, this is a known problem (well, I know it, at least) with `@task`, you need to instead do something like

```python
@task_group
def do_all_things():
    for i in range(5):
        @task(task_id=f"do_thing_{i}")
        def do_thing(i):
            print(i)
 
        do_thing(i)
```

instead. But it’s unfortunately not very easy to fix.

**Comment by uranusjr** [comment]
(Self-assigning so maybe I can come back to it at some point. But feel free to raise your hand if you want to tak a stab instead!)

**Comment by uranusjr** [comment]
Oh the cause is simpler than I though; fixing.
