### ISSUE TITLE
Task-level end_date stops entire DAG

### ISSUE THREAD

**Issue by easontm** [apache/airflow#19917]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

Ubuntu 19.10

### Deployment

Other Docker-based deployment

### What happened

If a task has an `end_date`, the whole DAG stops at that time instead of only that task.

### What you expected to happen

The task with the `end_date` should stop at that time and the rest should continue.

### How to reproduce

```
from datetime import datetime, timedelta

from airflow.models import DAG
from airflow.operators.dummy import DummyOperator

default_args = {
    "owner": "me",
    "email": [""],
    "start_date": datetime(2021, 11, 20),
}


dag = DAG(
    "end_date_test",
    default_args=default_args,
    schedule_interval="@daily",
)

task1 = DummyOperator(
    task_id="no_end_date",
    dag=dag
)

task2 = DummyOperator(
    task_id="special_start_end",
    start_date=datetime(2021, 11, 22),
    end_date=datetime(2021, 11, 24),
    dag=dag,
)
```
![image](https://user-images.githubusercontent.com/7014837/144162498-a2bce24f-64da-4949-a9ac-c3a9a1edc735.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Confirmed that it works this way, however I am not sure if this is wrong. The behaviour of what happens with the DAG when one of the tasks in the DAG has "end-date" is not really clear from the documentation:

https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/index.html#airflow.models.BaseOperator

> end_date (datetime.datetime) – if specified, the scheduler won’t go beyond this date

This is what happens now - scheduler won't go beyond the date if end_date is specified for any of it's tasks. That **might** be intended behaviour.

@BasPH @kaxil @ashb @dstandish as you know more about the origins of it - is it expected behaviour ?

**Comment by ashb** [comment]
Having an end date on one task but not the others was I think the second "bug" I ran in to in Airflow 1.8.2 (that I just worked around at the time)

I think and this is a bug we should fix

**Comment by potiuk** [comment]
> Having an end date on one task but not the others was I think the second "bug" I ran in to in Airflow 1.8.2 (that I just worked around at the time)

Déjà vu  :D

**Comment by kaxil** [comment]
For some time now -- I don't think having a "task-level" `start_date` and `end_date` makes sense ! 

Some arguments around having a separate task-level `start_date` was to have a "waiting" `timedelta` or an offset from DAG start_date which I think can be achieved in a more "transparent way" by using Async Time sensor now.

**Comment by potiuk** [comment]
> For some time now -- I don't think having a "task-level" `start_date` and `end_date` makes sense !

It does seem weird - that's why I doubted if that is a "real" error.

**Comment by eladkal** [comment]
> For some time now -- I don't think having a "task-level" `start_date` and `end_date` makes sense !

It does and it does not. It's a matter of perspective.
I can list several use cases but for most of them there are other options to get the same functionality.

One thing that we should consider is also the case of backfilling.
For example I had a process that query a sources and does some work (task per source. after a while a new source introduced and DAG was updated with a new task with the relevant `start_date`. If for any reason i want to backfill then it didn't make any sense to schedule the task of the new source for dates prior to the creation of the source. It's a waste. This is where the `start_date` is useful on task level. Same argument could also be raised for `end_date`.

**Comment by ashb** [comment]
I've wanted separate task level start/end dates when processing data sets from suppliers - when they've told us in advance that "as of date X we are changing the format of data we send you", or internally "from X we alsoc need to process country Y"

**Comment by ashb** [comment]
I think the logic should be:

For start date.

- Treat null task start date as dag start date
- dag start date is min of all start dates

For end date
- treat null task end date as no end date
- when calculating dag end date (when it isn't given explicitly at the dag level), if any tasks have null end date then the dag has no end date.

**Comment by kaxil** [comment]
>One thing that we should consider is also the case of backfilling.

Oof yeah, backfill is a use-case, true.



> I think the logic should be:
> 
> For start date.
> 
> * Treat null task start date as dag start date
> * dag start date is min of all start dates
> 
> For end date
> 
> * treat null task end date as no end date
> * when calculating dag end date (when it isn't given explicitly at the dag level), if any tasks have null end date then the dag has no end date.

Generally, agree, I think we also add logs with warnings for those case -- so "unintentional" cases can be mitigated

**Comment by potiuk** [comment]
Fine for me :)
