### ISSUE TITLE
ShortCircuitOperator does not save to xcom

### ISSUE THREAD

**Issue by yan-hic** [apache/airflow#19922]
### Description

`ShortCircuitOperator` does not return any value regardless of the result. 

Still, if `condition` evaluates to `falsey`, it can be useful to store/save the result of the condition to XCom so that downstream tasks. can use. 
Many objects evaluates to True/False, not just booleans - see  https://docs.python.org/3/library/stdtypes.html

### Use case/motivation

The change is trivial and would allow to combine a Python task and ShortCircuit into one.:

1. if callable returns None (or False) -> skip
2. if callable returns non-empty object (or True) -> continue. The proposed change is to pass on the condition to XCom.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you describe a usecase where this is usefull?
I'm curious because currently the operator skip all downstream tasks so if you have a usecase where something like that is needed it might not work as you expect?

**Comment by yiga2** [comment]
We currently check if file(s) exist in a folder (e.g. GCS) and if not empty, parse the latest file and extract 3 data elements that will trigger a whole branch. 
If nothing, we skip all tasks in that branch up until it merges back to the "main stream".

**Comment by eladkal** [comment]
> We currently check if file(s) exist in a folder (e.g. GCS) and if not empty, parse the latest file and extract 3 data elements that will trigger a whole branch. If nothing, we skip all tasks in that branch up until it merges back to the "main stream".

So why do you need the True/False value of ShortCircuitOperator?

**Comment by yiga2** [comment]
There is no True/False to save. The `callable` returns `None` or a `dict`, and I want to have the `dict` saved.
The code evaluates the condition like so:
`if condition:` and it doesn't force for it to be a boolean - which is great.

**Comment by eladkal** [comment]
The feature request is to push to xcom - your explnation doesnt say anything about what pulls from xcom. If you can show a simple dag that uses the feature it will be easier to understand.

Regardless - that is just me being curious. You can ofcourse submit a PR and we will review it.

**Comment by josh-fell** [comment]
+1 on seeing a simple or analogous example. 

No reason why the `callable` used in the `ShortCircuitOperator` couldn't push an `XCom` and then a downstream `BranchPythonOperator` uses that `XCom` to determine which branch(es) to follow. Of course, you're still up against #7858 being implemented first like you mentioned.

**Comment by yiga2** [comment]
@josh-fell just to clarify that a use case - not mine - may not involve the use of a `BranchPythonOperator` right (or any time) after, so no real dependency or downside. Any downstream task could just use the result of the `ShortCircuitOperator` evaluation with the change, whereas today it can't.
