### ISSUE TITLE
Tree view status filters

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#19943]
It would be really useful to be able to filter the tree view.

- By dag run/task instance status
- By dag run length (maybe?)
- By run type (scheduled, backfill, manual) (maybe?)

As part of this, it may also make sense to bring the number of runs and the base date into react to improve UX and avoid extra rerenders.

**Comment by pierrejeambrun** [comment]
Hi @bbovenzi,

Is this issue open for contribution ? It looks interesting and I would like to work on it :smile: 

Best,

**Comment by pierrejeambrun** [comment]
Hello guys,

This issue looks really interesting and I would love to work on it.

I was thinking of something like this for the UI:

![image (1)](https://user-images.githubusercontent.com/14861206/164985570-c1e71308-20ee-4894-93ff-191e4a9fd81d.png)
![image (2)](https://user-images.githubusercontent.com/14861206/164985569-c5d93f37-96c8-4d5b-b8b9-ede289025000.png)
![image (3)](https://user-images.githubusercontent.com/14861206/164985568-02db6d9d-b801-4abc-a959-9cf6cbc8d2a2.png)
![image (4)](https://user-images.githubusercontent.com/14861206/164985567-23e01a6e-d075-4795-a4b6-ff66bd01c270.png)
![image (5)](https://user-images.githubusercontent.com/14861206/164985566-1fefbd59-4a14-4552-8bb8-c1bb1cb2a64d.png)

**Comment by bbovenzi** [comment]
It's all yours Pierre! Feel free to reach out if you have any questions whatsoever.

Quick feedback on the mocks:
- Let's not completely hide non-matching task instances, but instead apply an opacity to them
- "Dag State" -> "Run State"
- Let's not have the options in all caps, and let's include the status color next to the name of each option
