### ISSUE TITLE
Update url routes and naming

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#19944]
If we integrate tree/graph/gantt/details views into a single page, then we will need to change how the url routes in airflow work.

The default url would change from `/tree?dag_id=example_dag` to `/dags/example_dag` and `/dags/example_dag/gantt` would then show the tree/gantt combined view.

We should also drop all `tree` nomenclature, because it is no longer a tree diagram. It is simply the default dag page.

Redirects should be used to keep backwards compatibility.

**Comment by potiuk** [comment]
+1

**Comment by bbovenzi** [comment]
Added in #20730
