### ISSUE TITLE
Breeze: Setup Autocomplete for Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19967]
We should leverage the 'click' functionality to get autocomplete working (https://click.palletsprojects.com/en/8.0.x/shell-completion/#) for `./Breeze2` command. The commands should come from the `./dev/breeze/src/breeze.py`.

This might require some hackery approach and might prove to be impossible or difficult, because it is based on entrypotnts and the fact that we want to use `Breeze2` command to run Airflow might not be well recognized by shell autocomplete. 

But I believe with proper naming of the commands/entrypoints we should be able to achieve it.

The result of this should be short instruction on how to make autocomplete for Breeze2 works (possibly with links to the documentation from click).

**Comment by Bowrna** [comment]
I will pick this issue to work on first @potiuk

**Comment by uranusjr** [comment]
A better approach would be to pre-generate completion scripts, and use pre-commit to keep everything in sync. This would eliminate most of the hacks (at runtime at least; all of those would only need to be able to generate a completion script).

[click-completion](https://github.com/click-contrib/click-completion) is another thing to look into that can help this.

**Comment by Bowrna** [comment]
@uranusjr could you explain to me why we have to keep everything in sync using pre-commit?

**Comment by uranusjr** [comment]
So when someone adds a new command, they can be automatically reminded to regenerate the autocompletion script.

**Comment by Bowrna** [comment]
@potiuk I am planning to start this with one actual command and adding autocomplete for that one command and create help docs with that. Am i going in right direction?

**Comment by potiuk** [comment]
@uranusjr is right - Click completion is the right approach. And I aggre that the scripts should be automatically generated by .pre-commit.

> So when someone adds a new command, they can be automatically reminded to regenerate the autocompletion script.

Not even reminded - the scripts should be automatically regenerated. We have quite a few of those already - for example look here: https://github.com/apache/airflow/blob/cc3f038aede71d54e66cce37fe5ce1d4ec5a86e4/.pre-commit-config.yaml#L355 where we take a version and update it in a few places. 

In this case as pre-commit we should simply run generation of the scrits whenever the dev/breeze/src/airflow_breeze.py changes.

See how to generate the scripts here: https://click.palletsprojects.com/en/7.x/bashcomplete/#activation-script 

Then I think we coud make (or find) the right way to update .zshrc/.bashrc etc with those activation commands (I guess someone had done that).

**Comment by Bowrna** [comment]
@potiuk I have tried the above https://click.palletsprojects.com/en/7.x/bashcomplete/#activation-script script generation part and it works for me. Do I have to add that as part of python script in pre_commit like what is there for update-version?  the script that generates <Breeze2-complete>.bash/.zsh/.fsh and update in .zshrc/.bashrc/`~/.config/fish/completions/` file? 

https://github.com/apache/airflow/blob/cc3f038aede71d54e66cce37fe5ce1d4ec5a86e4/.pre-commit-config.yaml#L357

Also, you have mentioned that in pre-commit we should simply run generation of the scripts whenever the dev/breeze/src/airflow_breeze.py changes. How could I find out there are changes in this script file?

**Comment by potiuk** [comment]
Yeah. Just add a pre-commiit to generate the files and save them somewhere in `./dev/breeze/autocomplete/` for example.

There is no need to check it. Assuming that precommit generates the same script when you run it twice, pre-commit checks on it's own if the re-generated file changed or not. So it's ok to regenerate the file again and again only to find out that nothing changed (but in pre-commit definition you should specify that pre-commit should run only when the `./airflow_breeze.py` changes (because that's where the defintions of click commands are). 

This can be done by adding `pass_filenames` to false: https://pre-commit.com/#hooks-pass_filenames and adding dev/breeze/airflow_breeze.py proper regexp to `files` parameter of pre-commit https://pre-commit.com/#hooks-files.
