### ISSUE TITLE
Tree view tooltips not showing when timezone is set to local

### ISSUE THREAD

**Issue by hterik** [apache/airflow#19960]
### Apache Airflow version

2.2.1

### Operating System

Ubuntu 21.04

### Deployment

Other Docker-based deployment

### What happened

Go to airflow UI
In top right corner, select time zone CET (+01:00) local.
Go to tree view
Hover any item. The tooltip does not show up and javascript console is printing following:
```
Uncaught TypeError: moment.defaultZone is null
    generateTooltipDateTimes static/dist/tree.33a23cc92d6f78b075bf.js:1189
    tiTooltip static/dist/tree.33a23cc92d6f78b075bf.js:1263
    update static/dist/tree.33a23cc92d6f78b075bf.js:1018
```

With UTC selected instead, the tooltips work as expected.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@hterik Is this happening in the old or new UI?

**Comment by hterik** [comment]
When you say new, do you mean 2.3 or AIP-38?

This happens on the official Docker image version: v2.2.1
Git Version: .release:2.2.1+360474fff3738f70e95580a91e778250afa7ce82

**Comment by bbovenzi** [comment]
Oh my bad, I missed the version number. Closing as all of this will be changed in 2.3
