### ISSUE TITLE
CI: Rewrite `free_space` script in Python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19969]
In our build/ci.yml (maybe other?) files we are using a "free_space" script that performs cleanup of the machine before running the tasks. This allows us to reclaim memory and disk space for our tasks.

Example: https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/.github/workflows/ci.yml#L334

This should be written in Python and our ci.yml and build.yml should be updated. We shoudl also be able to remove free_space script from the repo.

**Comment by edithturn** [comment]
I see airflow/scripts/ci/tools is where we have all the sh files.
This script free_space.sh contains another script: `$( dirname "${BASH_SOURCE[0]}" )/../libraries/_script_init.sh` and this another one.

Should I focus just on free_space.sh, right?

I would like to work on this issue :)

**Comment by potiuk** [comment]
The "init" script contains some common setup which are needed for Bash and defines common functions used by both Breeze and CI, but they are largely unnecessary for Python and if we find that we need some common code we will extract it to some common packages that will be used by both CI and Breeze.

**Comment by potiuk** [comment]
So yeah. Just port what the `free_spaces" do - the common parts we will extract later if /when needed.

**Comment by edithturn** [comment]
Why we are using `docker_v system prune` instead of `docker system prune`? 

For this, I can understand that is for making VERBOSE more readable?
`# In case "VERBOSE" is set to "true" (--verbose flag in Breeze) all docker commands run will be
# printed before execution. In case of DRY_RUN_DOCKER flag set to "true"
# show the command to execute instead of executing them`

**Comment by potiuk** [comment]
Precisely. In our case we can do it differently - we can make a function that will do that for us. But this might be done later when we start extracting common parts.

As the good old saying is "let's make things usable before they are made reusable".

**Comment by edithturn** [comment]
In which part of the ci process do we call this function "free_space.sh"? 
is testing it independently (free-space.py) but now I want to test the whole flow :)

**Comment by potiuk** [comment]
It will be launched automaticallyt when you submit the PR in GitHub Actions: https://docs.github.com/en/actions - Generally the build you see in PR is precisely the "ci.yml" execution. There is also this project: https://github.com/nektos/act which apparently allows you to run it locally but when we tried it some time ago it did not work well - but I hear it improved since.
