### ISSUE TITLE
breeze start-airflow tmux session

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#19964]
### Describe the issue with documentation

You can also have breeze launch Airflow automatically breeze start-airflow, this will drop you in a tmux session with four panes:

one to monitor the scheduler,
one for the webserver,
one monitors and compiles JavaScript files,
one with a shell for additional commands.

Current documentation says it has four panes. But code in main branch, will drop you in tmux session with three panes and we wont see the one pane that monitors and compiles Javascript files

### How to solve the problem

We can update the documentation with the correct information

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Ah yea. Please fix it :). There used to be 4 sessions but we removed the session that reloaded webserver automatically in favour of instructions printed: https://github.com/apache/airflow/blob/9d5647b91246d9cdc0819de4dd306dc6d5102a2d/scripts/in_container/run_tmux_welcome.sh#L24
