### ISSUE TITLE
Breeze: Make Breeze works for Windows seemleasly

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19966]
The goal to achieve:

We would like to have `./Breeze2.exe` in the main directory of Airlfow which should do the same as `python Breeze2` now - firing the Breeze command line and managing the virtualenv for it.

We need to have: 
* colors in terminal
* possibility to use commands and flags
* [stretch goal] autocomplete in Windows (we might separate it out to a separate task later)

**Comment by edithturn** [comment]
Requirements over windows 10:
- Python 3.7+
- Docker
- Docker-compose

I used: `pip install pyinstaller ` to generate the executable. With` pyinstaller Breeze2` I got Breeze2.exe, and it is detecting a  virtus false positive. Now I will try to convert exe without any virus errors.

**Comment by edithturn** [comment]
I created a PR to update the documentation to install  Breeze2 on Windows. 
https://github.com/apache/airflow/pull/20148.

> We need to have:

colors in terminal
possibility to use commands and flags
[stretch goal] autocomplete in Windows (we might separate it out to a separate task later)

@potiuk I think the task is still incomplete, as we need to verify this registered as the scope of the task. Let me know your thoughs

**Comment by edithturn** [comment]
Color in the terminal is working, I tested with: "Breeze version" with showing green letters for "breeze2 version: 0.01"
Flags and command are working:
```

Breeze2 --help
Breeze2 shell
```

The implementation of each option is pending,
