### ISSUE TITLE
CI: Rewrite selective check script in Python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19971]
Breeze's CI uses selective check script, to determine which parts of the tests and build should be executed. This helps to save a LOT of build time for simpler PRs - for example when there is a PR with just a documentation change, it wil not run unit tests.

It's used in two places: ci.yml and build.yml:

* https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/.github/workflows/ci.yml#L209
* https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/.github/workflows/build-images.yml#L124

The logic for that is described in https://github.com/apache/airflow/blob/main/PULL_REQUEST_WORKFLOW.rst#id1

This boils down to simply generating the right set of outputs, based on what files were modified in the PR and what labels the PR has.

This should be rewritten in python and we should be able to remove and replace the selective check script in the CI of airflwo when this is complete.

**Comment by edithturn** [comment]
> It's used in two places: ci.yml and build.yml:

The right file should be build-images.yml :)

**Comment by edithturn** [comment]
Two of my task is almost ready, I would like to take this one (I will have two tasks on my hand) 😄 
@eladkal could you assign it to me?

**Comment by edithturn** [comment]
> I have a feeling It can be somewhat simplified :) 
@potiuk I think we could separate this task into parts that have their own deliverables, just the task as it is very big.
I will re-take this one now.

**Comment by potiuk** [comment]
> > I have a feeling It can be somewhat simplified :)
> 
> @potiuk I think we could separate this task into parts that have their own deliverables, just the task as it is very big. I will re-take this one now.

Cool. Yep

**Comment by edithturn** [comment]
@potiuk do you have 10 minutes to discuss this a little bit? Maybe Tuesday? I will bring some ideas and we can split to start to work on it. 🙏🏼

**Comment by potiuk** [comment]
Tuesday is fine. I will be mostly out since Wed though.

**Comment by edithturn** [comment]
Thank you Jarek, I will ping you Tuesday, Poland Time. 🇵🇱 ⏲️

**Comment by potiuk** [comment]
Reserve time with calendly - will be easier :)
