### ISSUE TITLE
Postgres 9.6 end of support

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#19986]
### Describe the issue with documentation

since November 11, 2021 the support of Postgres 9.6 is finish

https://www.postgresql.org/support/versioning/

### How to solve the problem

remove 9.6 from airflow

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
Btw @raphaelauv, you don't need to open an issue before opening a PR, especially if you have the change ready to go 👍
