### ISSUE TITLE
TaskInstance.log_url is uncallable due to execution_date being deprecated

### ISSUE THREAD

**Issue by PrincipalsOffice** [apache/airflow#19995]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

Debian GNU/Linux

### Versions of Apache Airflow Providers

N/A

### Deployment

Other Docker-based deployment

### Deployment details

N/A

### What happened

When I created a TaskInstance object and tried to access its `log_url` property, an `AttributeError: 'NoneType' object has no attribute 'isoformat'` exception was raised.

### What you expected to happen

`task_instance.log_url` returns the correct url.

### How to reproduce

```
>>> import pendulum
>>> from airflow.models import DAG, TaskInstance
>>> from airflow.operators.dummy import DummyOperator
>>> dag = DAG("dummy_dag", start_date=pendulum.parse("20210101"))
>>> task = DummyOperator(task_id="dummy_task", dag=dag, task_group=dag.task_group)
>>> task_instance = TaskInstance(task, execution_date=execution_date, run_id="test")
>>> task_instance.log_url
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path_to_my_venv/python3.8/site-packages/airflow/models/taskinstance.py", line 651, in log_url
    iso = quote(self.execution_date.isoformat())
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

### Anything else

Not sure if the log_url in 2.2.2 even support the execution_date param anymore. What's the official expected behavior?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
TaskInstance is just a reflection of datamodel, so it is bound to change. See the latest definition in Airflow code (I gues you initially looked at internals too to find out how to create it) . The latest definitiion (reflecting the data model is here) https://github.com/apache/airflow/blob/8ca3eda02c58ab7ff224e463bd8b7ae389ce4370/airflow/models/taskinstance.py#L308

**Comment by uranusjr** [comment]
Also note that the problem is not `TaskInstance.log_url` is broken per-se, it’s that you’re creating a TaskInstance without a DagRun, which is no longer supported. [^1] This would not fail if you properly create a DagRun and establish its relationship with the TaskInstance.

[^1]: https://github.com/apache/airflow/blob/6d42b0e611c6b68c611dc25f3de2661e268cf3fe/UPDATING.md#taskinstances-now-require-a-dagrun
