### ISSUE TITLE
Trigger event payload mutually incompatible with deferral kwargs

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#20003]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

official docker image

### Deployment

Virtualenv installation

### Deployment details

When we defer we can supply kwargs

```
        self.defer(
            trigger=DateTimeTrigger(moment=target_dttm),
            method_name="execute_complete",
            kwargs={"other_thing": "hello"},
        )
```

If we do, these are passed to `method_name` when we come back out of deferral.

We can also return a payload from the trigger, and this is also supposed to be forwarded to `method_name`.

However, when you supply `kwargrs` in deferral, the event payload is ignored.

### What you expected to happen

I expecte both event payload _and_ deferral kwargs to be passed to the next method when resuming.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by stephenonethree** [comment]
+1, I ran into this as well. In our use case we want to get some information back from the trigger, but there are also some variables that we want to pass along to our resume method from the original `execute` method. 

I'm able to work around this by just adding the data to a new property of my trigger and then adding that property into my payload instead of using `kwargs`, but it seems like a sensible thing to allow both `kwargs` and `payload` to be used.

**Comment by uranusjr** [comment]
What is the behaviour you’d expect when both deferring kwargs and even payload are provided? If they should be merged, how should duplicated keys be handled?

**Comment by stephenonethree** [comment]
I'd say they should be merged. If there are duplicates it might make sense for the values from triggers to win, since they're determined later.

**Comment by eladkal** [comment]
@dstandish is this still an issue?

**Comment by dstandish** [comment]
i assume so

**Comment by dstandish** [comment]
it shouldn't be that hard to fix.  @stephenonethree would you be interested in taking a crack at it?

**Comment by tomrutter** [comment]
It might be useful to allow explicit turning off of the custom parameters as well. In some cases the desired method won’t accept an additional kwarg. For example, this would make it easier to use task deferral with vanilla taskflow @task operators (calling the execute method to run the task again after the trigger fires). This is the current behaviour when the trigger method is set to None but this isn’t documented. I’d be happy to submit a PR with a documentation update if that would help. On 8 Nov 2022, at 20:57, Daniel Standish ***@***.***> wrote:﻿
it shouldn't be that hard to fix.  @stephenonethree would you be interested in taking a crack at it?
