### ISSUE TITLE
DB schema: varying(64) is not enough for email fields

### ISSUE THREAD

**Issue by aKumpan** [apache/airflow#20020]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

composer-1.17.3-airflow-2.1.2

### Deployment

Composer

### What happened
Originally reported here: 
https://stackoverflow.com/questions/69718827/receiving-http-401-when-accessing-cloud-composers-airflow-rest-api

Getting "401 Unauthorized" error when accessing Airflow Stable REST api with service accounts having email longer than 64 symbols.
Successfully Accessing API with service accounts email <64 symbols. 
Details:
https://stackoverflow.com/a/70217282/9583820

### What you expected to happen

Google Cloud Platform service accounts emails are usually quite long due to big domain part.
I would expect longer emails to work with Airflow

### How to reproduce

I think the same will reproduce for every environment, but my issue happened on this:
composer-1.17.3-airflow-2.1.2 (Google Cloud Platform)

Set "api-auth_backend" to "airflow.composer.api.backend.composer_auth"
Make sure your service account has required permissions (Composer User role should be sufficient)
Make sure your service account email length is >64 symbols
Provide Bearer token for the request

Result:
Requests to Stable API will fail with "401 Unauthorized" 

Change service account to have email <64 symbols
Result:
Requests sucessed

### Anything else

I think updating tables:
public.ab_register_user
public.ab_user

to have email field to be VARCHAR(320) as per 
RFC 5321 (the current SMTP spec, obsoletes RFC2821) states:
The maximum total length of a user name or other local-part is 64 octets. The maximum total length of a domain name or number is 255 octets

Should fix the issue.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Already addressed by the in-progress #19932

**Comment by aKumpan** [comment]
Thanks @potiuk 
Closing the ticket
