### ISSUE TITLE
Airflow plugin doesn't respect SQLALCHEMY_BINDS 

### ISSUE THREAD

**Issue by wills-feng** [apache/airflow#20078]
### Apache Airflow version

2.2.1

### What happened

I'm writing a plugin that needs to connect to a database and add a Modelview.
I have configured the SQLALCHEMY_BINDS in webserver_config.py and set `__bind_key__` in the model, but this model keeps connecting to `core SQLALCHEMY_DATABASE_URI ` instead of the external database.

### What you expected to happen

Models defined in plugins should respect `SQLALCHEMY_BINDS`

### Operating System

Ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I saw you already created a discussion for that. Since we do not know if this is an airflow problem or configuration on your side, I am closing this in favour of discussion. #20080
