### ISSUE TITLE
DAG tree view autorefresh does not keep schedule timeline labels in sync.

### ISSUE THREAD

**Issue by curlup** [apache/airflow#20076]
### Apache Airflow version

2.2.0

### What happened

Tree view of a DAG with a busy schedule updates statuses of recent N (25) runs and autoupdates the view when new runs are scheduled and more old runs are finished. But it does not update corresponding labels on the schedule time line. 

<img width="211" alt="Screen Shot 2021-12-06 at 11 05 30 AM" src="https://user-images.githubusercontent.com/338607/144880824-4eb69909-7512-4189-854f-fb089aa120f7.png">
As you can see here in a tooltip of the leftmost task - the run it represents is for `2021-12-04 2:26:00 EST`,
but corresponding timeline header (in background of that tooltip, which I made to be semitransparent) shows `Dec 03, 23:22` - because it was not updated when the task history line was. 

### What you expected to happen

I expect the timeline header with date labels to be autoupdated (and shifted to the left if necessary) along with DAG run columns. 

### How to reproduce

* Create some simple DAG (with say a `sleep 1` task) and put it on a tight schedule, say once every minute or two minutes (as in the example above). 
* Enable this dag and open its tree view. 
* Select 5 to be the number of runs shown. 
* Make sure autoupdate is enabled in the view.
* Wait for couple of cycles of runs finished (>5), so they are "shifted out" of the current view (of 5 most recent).
* Hover over the left most run to see its scheduled date.
* Compare it to the label on the timeline in the view and find that they are not in sync. 

### Operating System

Ubuntu Bionic

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Closing as labels were rebuilt when switching to Grid.
