### ISSUE TITLE
CORS access_control_allow_origin header never returned

### ISSUE THREAD

**Issue by Csaki95** [apache/airflow#20110]
### Apache Airflow version

2.2.2 (latest released)

### What happened

To fix CORS problem added the [access_control_allow_headers](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#access-control-allow-headers), [access_control_allow_methods](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#access-control-allow-methods), [access_control_allow_origins](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#access-control-allow-origins) variables to the 2.2.2 docker-compose file provided in documentation. Both header, and methods returns with the correct value, but origins never does.

### What you expected to happen

The CORS response returning with provided origin header value.

### How to reproduce

Download the latest docker-compose from documentation add the following lines:
`AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS: 'content-type, origin, authorization, accept'`
`AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS: 'GET, POST, OPTIONS, DELETE'`
`AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS: '*'`

run and call with a CORS preflight

### Operating System

Windows 11

### Deployment

Docker-Compose

### Anything else

It's repeatable regardless of ORIGINS value. There was a name change on this variable that's possibly not handled.
On 2.1.4 the same works without problems.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
@ryanahamilton I know you were using and depending on CORS -- any ideas here?

**Comment by uranusjr** [comment]
Looks like the logic does not handle wildcard expansion:

https://github.com/apache/airflow/blob/b0eecc3d997ebbdb1fe6b6dfe7134238543f3dfa/airflow/www/extensions/init_views.py#L167-L171

**Comment by Madaditya** [comment]
Was anybody able to fix a fix to the CORS issue for airflow API? 
We are facing a similar issue and wondered if its was a v2.2..2 specific.

**Comment by uranusjr** [comment]
Feel free to fix it, pull requests are open to anyone 🙂

**Comment by copypasteearth** [comment]
Has this been fixed I'm having this problem on 2.3.3 and 2.3.4 docker compose
