### ISSUE TITLE
Airflow Gantt View is improper

### ISSUE THREAD

**Issue by yrj** [apache/airflow#20125]
### Apache Airflow version

2.2.2 (latest released)

### What happened

Airflow Task and Gantt view doesnt display the task names properly in Airflow UI. Anything more than 30 characters are hidden or display is overridden with the charts.

Tree View
![Screenshot 2021-12-08 at 10 42 20 AM](https://user-images.githubusercontent.com/19816434/145152089-01ff5492-c7e4-4616-a8ec-36de59201173.png)

Gantt View
![Screenshot 2021-12-08 at 10 42 34 AM](https://user-images.githubusercontent.com/19816434/145152052-740b8de8-a845-4e76-ac68-5a3f9567f879.png)
:

### What you expected to happen

Task and Gantt view should display the task names with proper indentation and without being hidden or cut. This impacts users on monitoring front to identify right tasks and mitigate.

Tree View:
![Screenshot 2021-12-08 at 12 19 58 PM](https://user-images.githubusercontent.com/19816434/145162106-a3df834e-7018-44a9-a372-9f2c4c69ae3a.png)

Gantt View:
![Screenshot 2021-12-08 at 12 20 06 PM](https://user-images.githubusercontent.com/19816434/145162139-1d2033c1-994c-4363-8be1-eb81f2882b21.png)

### How to reproduce

This issue is all about the visualisation gap in UI. Can be compared between 1.x and 2.x versions

### Operating System

NAME="Oracle Linux Server" VERSION="7.9"

### Deployment

Virtualenv installation

### Deployment details

Python 3.9
Mysql DB backend
Redis MB

### Anything else

This issue is observed starting versions 2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by BasPH** [comment]
The tree view was rewritten recently: https://github.com/apache/airflow/pull/18675.

If this suits your expectations, could you change this issue to just the Gantt view?

**Comment by yrj** [comment]
@BasPH Thanks for the update. I have updated the issue to Gantt view.
