### ISSUE TITLE
WARNING - Access is Denied for: can_read on: CustomUserOAuthModelView

### ISSUE THREAD

**Issue by huxuan** [apache/airflow#20127]
### Apache Airflow version

2.2.2 (latest released)

### What happened

After configuring `AUTH_OAUTH`, everything looks good except that Role `User` and `Viewer` can not access "Your Profile" page or `/users/userinfo/` API. The logout functionality also does not work well, It may be the same problem or related to https://github.com/apache/airflow/issues/15601. 

### What you expected to happen

`Viewer` and `User` can access their profile page.

### How to reproduce

Install airflow with `AUTH_OAUTH` configured.

### Operating System

Debian 10

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

 Slightly configured with custom `webserver_config.py` and custom security manager based on official docker image with tag 2.2.1/2.2.2-python3.8.

### Anything else

Guidance are needed for potential bug fix.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@huxuan is the issue still present in latest Airflow version?
