### ISSUE TITLE
DAG_run_id not include Task Instance object for REST API

### ISSUE THREAD

**Issue by frankbreetz** [apache/airflow#20142]
### Apache Airflow version

2.2.2 (latest released)

### What happened

I would expect the DAG_run_id to be included when I do a REST Call to get task Instances.
When doing a task instance batch call, you don't provide the DAG_run_id as input
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch

it would be easier to identify task Instance if the Dag_run_id was included. It is difficult to get the DAG_run_id, from execution_date, dag_id, task_instance especially if you are trying to not query the metadata base as is recommended. 

### What you expected to happen

you would get the dag_run_id returned as parameter of the TaskInstance Object
ex:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/TaskInstance

### How to reproduce

perform the following rest call:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch

examine any of the task_instances fields

there is no dag_run_id

### Operating System

ubuntu

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Done: https://github.com/apache/airflow/pull/19105
