### ISSUE TITLE
View Average Execution time of a DAG in Tree View

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#20140]
### Description

When viewing the DAG history in Tree View, individual DAG run times are available by hovering over the DAG run. As an Airflow user, I would like the average execution time to be readily available in the UI -> DAG -> Tree View.
It can be an average over the last _n_ runs, _n_ being the number of runs selected in the Tree View.

### Use case/motivation

The average DAG run execution information can help our team make decisions such as the optimal schedule interval for a DAG. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
<img width="676" alt="Screen Shot 2021-12-03 at 11 16 47 AM" src="https://user-images.githubusercontent.com/4600967/145856132-bca89a2b-3b66-4d73-942d-18ef9418d3cd.png">

We will be giving a visual indication of the dag run duration vs other recent ones. We can certainly include a running average. How far back should the average go? UI-wise ti would be simplest to do it just for the count shown on screen.

**Comment by SangwanP** [comment]
@bbovenzi -- It'd be preferred if it's configurable in the UI (like Tree View does).
On a different note, is the screenshot attached part of Tree View or is it a new view that is being developed. I really like this visual representation of dag run duration!

**Comment by bbovenzi** [comment]
That is the new tree view to come out in 2.3.0. So yeah, anything average will be across the _n_ count of dag runs shown in the UI. Where do you see this duration average info appearing? Anywhere in the tree view or only in a model when you hover over a dagrun?

**Comment by SangwanP** [comment]
I'd say any place in the tree view where it's readily visible. Tough to comment without exactly seeing the new view, but perhaps it can be right aligned on the menu where the user selects the start date, and number of runs in tree view.
