### ISSUE TITLE
SFTPHook requires param 'ftp_conn_id' to be passed even for ssh connections

### ISSUE THREAD

**Issue by saveriogzz** [apache/airflow#20144]
### Apache Airflow Provider(s)

sftp

### Versions of Apache Airflow Providers

apache-airflow-providers-sftp==2.2.0

### Apache Airflow version

2.2.2 (latest released)

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Docker-Compose

### What happened

When instantiating an SFTPHook in order to create a connection to an sftp server, I noticed that if I was passing the parameter `ssh_conn_id`, the hook was trying to connect to `localhost`, whereas if I am passing `ftp_conn_id`, I obtain the desired connection.

https://github.com/apache/airflow/blob/35be8bdee0cdd3e5c73270b0b65e0552fb9d9946/airflow/providers/sftp/hooks/sftp.py#L67-L69

### What you expected to happen

I would expect to be able to instantiate an sftp conection using the parameter `ssh_conn_id` instead of `ftp_conn_id`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
> I would expect to be able to instantiate an sftp conection using the parameter `ssh_conn_id` instead of `ftp_conn_id`.

Why?

**Comment by saveriogzz** [comment]
To be consistent with the SFTPOperator and not to mislead the type of connection to be used since there are both FTP and SFTP connections!

**Comment by potiuk** [comment]
OK. Works for me. Sftp is really ssh under-the-hood indeed. But you should make sure to keep deprecated previous option working too. Assigning you :D

**Comment by kaxil** [comment]
I would say rather than deprecating, allow both as it is quite common to use SSH for get and send files

**Comment by potiuk** [comment]
It's really about the "__iniit__" parameter name of Hook, so I am not sure if we should have two variants :). One should be blesssed.

**Comment by potiuk** [comment]
And there is disconnect which one is used between the  Operator and Hook.

**Comment by kaxil** [comment]
Oh yes this is regarding the Hook, I am fine with that. 

The SftpOperator uses the SSHHook anyway so all food 😅

**Comment by potiuk** [comment]
Food is good 🥫

**Comment by potiuk** [comment]
:D

**Comment by kaxil** [comment]
![d](https://media.giphy.com/media/kCAKbvUp4FTWUu3u1s/giphy.gif)

**Comment by eladkal** [comment]
fixed by https://github.com/apache/airflow/pull/20164
