### ISSUE TITLE
Add missing docs on using more than one `pool_slot`

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#20175]
### Describe the issue with documentation

We added a feature that allow more than one pool slots to be used by a single task in https://github.com/apache/airflow/pull/7160

However, we currently have no docs on it.

We should add some docs in https://airflow.apache.org/docs/apache-airflow/stable/concepts/pools.html that covers:

- Example of an operator using it
- Use-cases when it might be helpful

**Comment by BasPH** [comment]
Subscribing to the thread because I wonder what the use case is for pool slots.

**Comment by eladkal** [comment]
> Subscribing to the thread because I wonder what the use case is for pool slots.

Pools are used to limit concurrency with external services.
Not all tasks "weight" the same. Some tasks might require more resources from the external service - so for those heavy tasks you might want to occupy more slots of the pool to avoid scheduling more tasks.

**Comment by BasPH** [comment]
I get that, but what do pool slots give over creating a second pool with fewer slots?

**Comment by eladkal** [comment]
> I get that, but what do pool slots give over creating a second pool with fewer slots?

Say we have:
`Pool(pool='db', slots=2)`
This pool protect a resource that can handle up to 2 units of computing power.

and we have:
```
with DAG(...) as dag:
    BashOperator(
        task_id='task1',
        bash_command='echo Big Task',
        pool_slots=2,
        pool='db'
    )
    
    BashOperator(
        task_id='task2',
        bash_command='echo Small Task',
        pool_slots=1,
        pool='db'
    )
 
 
 with DAG(...) as dag2:   
    BashOperator(
        task_id='task3',
        bash_command='echo Small Task',
        pool_slots=1,
        pool='db'
    )
```

With this code the resource is protected according to requirements.
How would suggest to get the same functionality with 2 pools (without `pool_slots`)?

**Comment by potiuk** [comment]
Ah. How cool I did not know Airflow can do that :)

**Comment by BasPH** [comment]
Oh I see, you'd only be able to approximate a limit of 2 "units" without pool slots.

**Comment by PApostol** [comment]
I can take this one!

**Comment by potiuk** [comment]
Feel free!

**Comment by eladkal** [comment]
Fixed by https://github.com/apache/airflow/pull/20257
