### ISSUE TITLE
dags folder mount readonly with git-sync true option

### ISSUE THREAD

**Issue by ghost** [apache/airflow#20196]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.1

### Kubernetes Version

1.20

### Helm Chart configuration

# Git sync
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: false
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim:
  gitSync:
    enabled: true
    repo: git@bitbucket.org:/data-airflow.git
    branch: test_dags
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 1
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: ""
    # if your repo needs a user name password
    # you can load them to a k8s secret like the one below
    #   ---
    #   apiVersion: v1
    #   kind: Secret
    #   metadata:
    #     name: git-credentials-data-airflow
    #   data:
    #     GIT_SYNC_USERNAME: 
    #     GIT_SYNC_PASSWORD: 
    # and specify the name of the secret below
    #
    #credentialsSecret: git-credentials-data-airflow
    #
    #
    # If you are using an ssh clone url, you can load
    # the ssh private key to a k8s secret like the one below
    #   ---
    #   apiVersion: v1
    #   kind: Secret
    #   metadata:
    #     name: airflow-ssh-secret
    #   data:
    #     # key needs to be gitSshKey
    #     gitSshKey: <base64_encoded_data>
    # and specify the name of the secret below
    sshKeySecret: airflow-ssh-secret
    #
    # If you are using an ssh private key, you can additionally
    # specify the content of your known_hosts file, example:
    #
    # knownHosts: |
    #    <host1>,<ip1> <key1>
    #    <host2>,<ip2> <key2>
    # interval between git sync attempts in seconds
    wait: 60
    containerName: git-sync
    uid: 65533
    extraVolumeMounts: []
    env: []
    resources: {}
    #  limits:
    #   cpu: 100m
    #   memory: 128Mi
    #  requests:
    #   cpu: 100m
    #   memory: 128Mi

### What happened

When I turn on git sync, the dags folder is mounted read-only. If you turn off synchronization, the folder is mounted for reading and writing.

### What you expected to happen

Mount /opt/airflow/dags in readwrite mode

### How to reproduce

enable gitSync: true

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ururu-fy** [comment]
I would like to store master dag file generator in git and sync it to dags folder. Master dag auto generates new dags into the same folder.

**Comment by jedcunningham** [comment]
Even then, your pattern won't work without also having persistence enabled, as each component gets its own emptyDir dags volume. There are also race conditions with your plan - think of the delay between syncing a new change from git (which throws away local changes) and your generator DAG running.

You'd be better off having something else do the DAG generation (e.g. ci/cd), then using git-sync on that output. Or use a PVC instead of gitsync.

I think it's "safer" to only allow read so the wiping behavior isn't surprising. Thoughts @kaxil / @dstandish?

**Comment by potiuk** [comment]
yep. This is a very wrong approach (And @jedcunningham had nicely explained why).

Here are our best practices on dynamic dag generation: https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#dynamic-dag-generation - you have couple of options there.

Having the DAG generate python files dynamically sounds like recipe for disaster.  Please follow best practices @ururu-fy .

**Comment by kaxil** [comment]
>I think it's "safer" to only allow read so the wiping behavior isn't surprising. Thoughts @kaxil / @dstandish?


Agreed

**Comment by ururu-fy** [comment]
The thing is that my dags are very dynamic and can change very often. I'm not worried about their safety, since the dag master takes metadata from the database. Therefore, I see no reason to store them in git. It would be great to be able to the user to change the parameters of these settings depending on his needs.

**Comment by potiuk** [comment]
> The thing is that my dags are very dynamic and can change very often. I'm not worried about their safety, since the dag master takes metadata from the database. Therefore, I see no reason to store them in git. It would be great to be able to the user to change the parameters of these settings depending on his needs.

Then probably you are doing it wrong (and it will not work as you expect them). From the main Airflow page:
https://airflow.apache.org/docs/apache-airflow/stable/index.html


> Workflows are expected to be mostly static or slowly changing. You can think of the structure of the tasks in your workflow as slightly more dynamic than a database structure would be. Airflow workflows are expected to look similar from a run to the next, this allows for clarity around unit of work and continuity.

You should rethink if Airflow is a good choice for you if you want the DAGs to change frequently. The fact that you generate file in DAG folder does not mean that it will be reflected immediately or even very quickly in the DAG structure (it needs to be parsed by DagParser, stored in serialized dag table and scheduled by scheduler). Also it means that  your hist

**Comment by devgonvarun** [comment]
@potiuk I will be really grateful for your guidance on a similar but different case. I have airflow with kubernetes executor syncing dags via gitsync and just like mentioned in this post, with gitsync enabled the opt/airflow/dags path does not allow write mode. I dont want to mount a persisted volume for dags. I want to keep the pods file system non persistent for dags. dbt requires write access and i was hoping that the worker pod simply writes its to non persistent file system and as the pod gets deleted after the execution everything goes away and my dbt run works too. How can i do this considering the read only file system created by git sync? Thank you and sorry if this is rather a basic question.


UPDATE: in the case of dbt, I could use the log path and target path flags to route the dbt outputs to the tmp dir which is writtable and backed by an empty dir volume and non persisted as i wanted. 

Found a useful discussion on the same topic so linking here for others: https://github.com/apache/airflow/pull/27305

**Comment by potiuk** [comment]
Or you could mount an empty filessystem to your pod and use it instead - there is no need to use logs folder. You can do it in your pod template.
