### ISSUE TITLE
Triggering a DAG in Graph view switches to Tree view

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#20197]
### Apache Airflow version

2.2.2 (latest released)

### What happened

After I trigger a DAG from the Graph view, the view switches to the Tree view (happens on both 2.2.2 and main).

### What you expected to happen

I expect to stay in the Graph view, ideally switch to the newly created DAG run

### How to reproduce

Trigger a DAG from the Graph view

### Operating System

N/A

### Versions of Apache Airflow Providers

N/A

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kaxil** [comment]
@blag Can you take a look at this one?
