### ISSUE TITLE
Airflow UI "Next Run" displays wrong value

### ISSUE THREAD

**Issue by alangularte** [apache/airflow#20198]
### Apache Airflow version

2.2.2 (latest released)

### What happened

"Next run" time, displayed in Airflow UI, is not exactly the same as defined in the DAG script.
![Capture](https://user-images.githubusercontent.com/3098082/145580711-c234b5a2-fed0-41ff-81ad-a476e3d7e3be.PNG)

### What you expected to happen

Airflow UI should have the "Next Run" date time exactly the same as defined in the DAG script.

### How to reproduce

Define in the DAG script:
`start_time:datetime(2021, 12, 1, 11, 51),
schedule_interval="*/2 * * * *"`

In the Airflow UI the "Next run" value will be "2021-12-01, 11:52:00"

![Capture](https://user-images.githubusercontent.com/3098082/145580762-c33f5ae0-5a43-4428-892e-e1e74873bd9e.PNG)

But if I define:
`start_time:datetime(2021, 12, 1, 11, 50),
schedule_interval="*/2 * * * *"`

the "Next run" value will be **correctly**  "2021-12-01, 11:50:00"
![Capture](https://user-images.githubusercontent.com/3098082/145580888-e82eeb83-7f04-4ef2-91a5-f2cfe4443222.PNG)

### Operating System

Linux Ubuntu

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
This is by design -- the date of the first run is "normalized" to match the schedule interval. `*/2` doesn't say "every two minutes", but at every even minute (48,50,52,54 etc).

If you want every two minutes after the start time, use `schedule_interval=timedelta(minutes=2)`

**Comment by alangularte** [comment]
Thank you @ashb for the clarification! It worked now as expected.
