### ISSUE TITLE
Feature Request : Support Pools at the DAG level

### ISSUE THREAD

**Issue by r39132** [apache/airflow#202]
You already support pools at the Operator level. I would like to have flow level pooling as well. In other words, let's say that I have flow_1 and flow_2, I would like the tasks of flow_1 to have a pool and the tasks of flow_2 to have a separate pool -- these are flows, not flow instances. Flow_1 could be some aggregation DAG and flow_2 could be some model building flow. I would like to specify the pool_id as an argument to the DAG for each flow,  and not need to remember to pass it to each operator in each flow.

**Comment by mistercrunch** [comment]
default_args is how you set default arguments for the tasks in your DAG.

Check out the "Default Arguments" section in the tutorial
https://github.com/airbnb/airflow/blob/master/docs/tutorial.rst

Default arguments can be overridden at the task level.

**Comment by r39132** [comment]
Oh Cool!
