### ISSUE TITLE
"TaskInstance.dag_run" is joined twice in Dag.get_task_instances()

### ISSUE THREAD

**Issue by PrincipalsOffice** [apache/airflow#20248]
### Apache Airflow version

2.2.2 (latest released)

### What happened

Calling the `Dag.get_task_instances()` method would result in a sqlalchemy warning `sqlalchemy.exc.SAWarning: Pathed join target TaskInstance.dag_run has already been joined to; skipping`. This is because the query is trying to `.join(TaskInstance.dag_run)` twice. Once here https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L1373 then again here https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L1452

### What you expected to happen

No warning.

### How to reproduce

Simply creating a dag object then call  `get_task_instances()` should reproduce this warning.

### Operating System

Debian GNU/Linux

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Maybe you would like to attempt to fix it @PrincipalsOffice  ?

**Comment by hubert-pietron** [comment]
Hi. I would like to work on that. Can you assign it to me?

**Comment by potiuk** [comment]
Assigned

**Comment by tirkarthi** [comment]
I guess this can be closed given that https://github.com/apache/airflow/pull/20591 is merged.

**Comment by potiuk** [comment]
Thanks @tirkarthi
