### ISSUE TITLE
CI: Rewrite testing examples of images in python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20254]
We are runing automated tests for example images building as Bash scripts - those should be converted to Python.

https://github.com/apache/airflow/blob/98514cc1599751d7611b3180c60887da0a25ff5e/.github/workflows/ci.yml#L322

**Comment by edithturn** [comment]
@potiuk I would like to take this task 🙏🏼 😃

**Comment by edithturn** [comment]
This task is running one bash script, which is called three scripts.

`. "$(dirname "${BASH_SOURCE[0]}")/../libraries/_script_init.sh"

python3 "${SCRIPTS_CI_DIR}/images/ci_run_docker_tests.py" "${AIRFLOW_SOURCES}/docker_tests/test_examples_of_prod_image_building.py"
`

Should I write this file in python, right? :)

Thanks in advance.

**Comment by potiuk** [comment]
Yeah. I think this is as simple as this -  just getting rid of any "bash" executed.

Currently the tests to execute is really executing "pytest docker_tests" (more or less)

* script_init is not needed (as in most of our python code we can reuse common code)
* then what really want to do is to initialize the virtualenv and move the docker_tests.py script to "dev/breeze" so that it becomes a standalone command - similar to "freespace" (say "dockertest") 

Eventually I think what should happen is that the docker tests "CI job" for it should be: 
1) initialize the venv by `pip install ../dev/breeze" (actually this will likely be done by a previous freespace step already)
2) switch to the "airflow" source directory
3) running pytest (it can be easily run from python code) https://docs.pytest.org/en/latest/how-to/usage.html#calling-pytest-from-python-code

**Comment by edithturn** [comment]
@potiuk I am analyzing this one. When you said:  "docker_tests.py" do you mean: "ci_run_docker_tests.py" .
If it is, this script is in this directory: airflow/scripts/ci/images, and this another one
![Screenshot from 2022-01-13 11-23-12](https://user-images.githubusercontent.com/58795858/149368638-47a472c7-998d-4757-9028-6e52e11af5af.png)
Do we want to move them into dev/breeze, ci_breeze?

In this case, this ./scripts/ci/images/ci_test_examples_of_prod_image_building.sh script was not more needed, and we can call ci_run_docker_tests.py and test_examples_of_prod_image_building.py , like the same was as "freespace".

Let me know if that affirmation is correct.

**Comment by potiuk** [comment]
I think there are two main resasons why we have the few scripts:

The bash script is needed because  _script_init.sh is called to set the "AIRFLOW_CI_IMAGE` variable - this variable is then used internally by some tests to determine which image should be tested. 

But in our case we can get the image from the BuildParams instead:
https://github.com/apache/airflow/blob/bad070f7f484a9b4065a0d86195a1e8002d9bfef/dev/breeze/src/airflow_breeze/ci/build_params.py#L68
So what we really need to do is to create BuildParams class, set the python version from PYTHON_MAJOR_MINOR_VERSION environment variable and retrieve `airlfow_ci_image` from there (And set it as AIRFLOW_CI_IMAGE env variable using `os.environ`. @mik-laj - do I get it right? Maybe we can figure a good way of retrieveing the image easier ?

Originally the `ci_run_docker_tests.py` does a bit more - it actually bootstraps a virtualenv and runs "pytest" command in it with appropriate parameter.  And I think we do not really need it. We already have `breeze` virtualenv - we might want to add there missing dependencies in setup.cfg (in the script we have "pytest", "pytest-xdist", "requests" - I think we only miss `requests`). So instead we can immediately call `python -m pytest ./docker-tests/tests_examples_of_prod_image_building.py`. 

Do I get it right @mik-laj ?

Then we will not need any "bash script" to run it or even any "intermediate script" - not even the "freespace" equivalent

**Comment by mik-laj** [comment]
> The bash script is needed because _script_init.sh is called to set the "AIRFLOW_CI_IMAGE` variable - this variable is then used internally by some tests to determine which image should be tested.

This is needed for some tests, but for the `test_examples_of_prod_image_building.py` test we don't need any environment variable. 

If I remember correctly some tests rely on a variable called `AIRFLOW_IMAGE` and we will have to set it, but this is a different kind of test. They are in one directory but in a different file.
https://github.com/apache/airflow/blob/44df1420582b358594c8d7344865811cff02956c/scripts/ci/images/ci_run_docker_compose_quick_start_test.sh#L22-L23

> We already have breeze virtualenv 

If breeze has a virtual environment, we should use it.

From what I can see, file `scripts/ci/images/ci_run_prod_image_test.sh` should be removed as it is no longer used, because now we have all the tests in Python. Here is related PR: https://github.com/apache/airflow/pull/19819/files
