### ISSUE TITLE
Breeze: Asciiart disabling

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20252]
This is a small thing, but might be useful. Currently Breeze prints the Asciiart when started. You should be able to persistently disable the asciiart.

This is done with storing the rigth "flag" file in the ".build" directory. If the file is there, the ASCIIART should not be printed. If not, it shoudl be printed.

**Comment by Bowrna** [comment]
@potiuk I will pick up this task. Could you tell me the right flag name in the .build directory which indicates ASCIIART enable/disable state? Right now I don't see any relevant flag name in my .build directory that will indicate ASCIIART enable/disable state. Do I have to create a new flag name or could you point me to the correct flag name?

**Comment by potiuk** [comment]
`./breeze toggle-suppress-cheatsheet` `./breeze toggle-suppress-asciiart` - those are separate commands, but maybe simply better add `./breeze config --toggle-cheatsheet --toggle-asciiart`  instead ?

**Comment by potiuk** [comment]
This will add capabilities of more configuration changes. for example we could also add `--python` `--backend` flags to be availabl in this command, so that you could change python/backend without running anything.

**Comment by Bowrna** [comment]
> This will add capabilities of more configuration changes. for example we could also add `--python` `--backend` flags to be availabl in this command, so that you could change python/backend without running anything.

@potiuk Do you mean to change the python , backend version stored in .build directory, so that it could be made default and used when running breeze commands?

**Comment by potiuk** [comment]
> @potiuk Do you mean to change the python version or backend version stored in .build directory, so that it could be made default and used when running breeze commands?

The one stored in .build

**Comment by potiuk** [comment]
> Edit: ` --toggle-cheatsheet --toggle-asciiart` these configs are on/off switch, while python, backend flags can have multiple values. Am I right in understanding this?

Correct: toggle just disables/enables it. Actually maybe better to make them `cheeatsheet/no-cheatsheet` instead. Click has nice mechanism for that:  https://click.palletsprojects.com/en/8.0.x/options/#boolean-flags

**Comment by Bowrna** [comment]
Is this issue closed by mistake?

**Comment by potiuk** [comment]
yep
