### ISSUE TITLE
CI: Rewrite client codegen in Python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20253]
There is a step where Python client for Airflow API is generated automatically. This should be rewrittent in Pythone. It is just running the open-api client generation and checking that it succeded.

https://github.com/apache/airflow/blob/98514cc1599751d7611b3180c60887da0a25ff5e/.github/workflows/ci.yml#L307

**Comment by joppevos** [comment]
@potiuk I would like to tackle this issue.

**Comment by potiuk** [comment]
This is completed already.
