### ISSUE TITLE
Breeze: Verify if there are enough resources avaiilable in Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20251]
At entry of the Breeze command we verify if there iss enouggh CPU/memory/disk space and print (coloured) information if the resources are not enough.

We should replicate that in Python

**Comment by edithturn** [comment]
@potiuk I would like to work on this. In Breeze installation, I will take as consideration: https://github.com/apache/airflow/blob/main/BREEZE.rst#resources-required

**Comment by edithturn** [comment]
Ideal resources available to check:
* Memory available 16G.
* CPUs available 12.
* Disk available 41G.

Breeze has a line where call `_all_libs.sh` and `run_resource_check.sh` is part of one of these scripts. 

How could we structure run_resource_check.py? this script is inside: scripts/in_container, we will change it?

I could say it is not part of CI, so we can consider keeping it in the same directory as an in_container of Breeze. @potiuk do you have a better idea for a good place for this script?

**Comment by potiuk** [comment]
I think we should rewrite this check in python entirely:

* make a python script equivalent to run_resource_check.sh (run_resource_check.py ) - but it should be run inside breeze
* replace calling of the run_resource_check.sh -> run_resource_py
* remove the .sh script

This way the run_resouce_check.py will be used also in the old "breeze".

**Comment by edithturn** [comment]
We already have "tools" directory and some files. We have this structure:
| - scripts
    | -  init_container
         | - run_resource_check
    | -  tools
         | - list-integrations.py

"tools" is something more general, I think it can be left out, as is. Unless we have another "tools" folder just for init_container.

**Comment by potiuk** [comment]
Yeah - we want separate "tools" for the "in_container" - those should be only scripts that are available inside the container.

**Comment by edithturn** [comment]
Closes with #20763

**Comment by ashb** [comment]
Had to revert merged PR as it was failing all jobs, so re-opening this.
