### ISSUE TITLE
New operator for Go SDK in Apache Beam

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#20283]
### Description

[Go SDK Exits Experimental in Apache Beam 2.33.0](https://beam.apache.org/blog/go-sdk-release/), so we can add a new operator for this SDK

### Use case/motivation

Feature parity between Beam SDKs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Hello @mik-laj,

This one looks pretty interesting and I would like to give it a try :).

Do you mind if I work on it ?

(Any specific instruction ?)

**Comment by mik-laj** [comment]
@pierrejeambrun  I haven't used this SDK yet, but I think it should look similar to the Java SDK, but you have to run a different command. If you have any problems, we can ask friends from Apache Beam for support, as they have already reviewed other integrations before.
