### ISSUE TITLE
 Consistently name Amazon provider operators files

### ISSUE THREAD

**Issue by ferruzzi** [apache/airflow#20296]
### Description

Follow-up to 
Restructure Amazon provider operators files [#20139](https://github.com/apache/airflow/issues/20139) as discussed with @eladkal 

Amazon Operators, Hooks, and Sensors are inconsistently named regarding acronym capitalization and whether to prefix with AWS or not.

An incomplete list for example: we have `SnsPublishOperator` but we capitalize the acronyms in `SQSPublishOperator` and `ECSOperator`. We prefix `AwsGlueCrawlerOperator` and `AwsBatchOperator` in lowercase, `AWSAthenaOperator` is prefixed in uppercase, and no prefix at all on `GlacierCreateJobOperator`or `CloudFormationCreateStackOperator`

Correct naming conventions are listed in AIP 21 cases [3-4](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths#AIP21:Changesinimportpaths-Case#3{aws/azure/gcp}_*) and case [6](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths#AIP21:Changesinimportpaths-Case#6Otherisolatedcases).

The sensors/operators class names should not have Aws/AWS as part of the class name and only the first letter of the acronyms should be capitalized.

So:
SnsPublishOperator -> No change
SQSPublishOperator -> SqsPublishOperator
AwsBatchOperator -> BatchOperator
AWSAthenaOperator -> AthenaOperator
etc...

### Use case/motivation

For each task: 
 -Rename the operator
 -Deprecate the old name
 --Add to tests/deprecated_classes.py
 --Add to the KNOWN_DEPRECATED_MESSAGES section of dev/provider_packages/prepare_provider_packages.py
 -Correct any references to the old name in docstrings and docs files
 -Correct all references in tests
 -Correct references in example dags

### Changes Required:

| Current                      | New Name                 |
|------------------------------|--------------------------|
| AWSAthenaOperator            | AthenaOperator           |
| AwsBatchOperator             | BatchOperator            |
| AWSDataSyncOperator          | DataSyncOperator         |
| ECSProtocol                  | EcsProtocol              |
| ECSTaskLogFetcher            | EcsTaskLogFetcher        |
| ECSOperator                  | EcsOperator              |
| EKS***Operator (all of them) | Eks***Operator           |
| SQSPublishOperator           | SqsPublishOperator       |
|||
| EKS***Sensor (all of them) | Eks***Sensor           |
| AwsRedshiftClusterSensor   | RedshiftClusterSensor  |
| SQSSensor                  | SqsSensor              |
|||
| AWSAthenaHook     | AthenaHook     |
| AWSCloudFormationHook     | CloudFormationHook     |
| AWSDataSyncHook     | DataSyncHook     |
| AwsDynamoDBHook     | DynamoDBHook     |
| EKSHook     | EksHook     |
| AwsFirehoseHook  (in kinesis.py)   | FirehoseHook     |
| AwsLambdaHook     | LambdaHook     |
| SESHook     | SesHook     |
| AwsSnsHook     | SnsHook     |
| SQSHook     | SqsHook     |

### Action Items:

- [x] operators/athena.py - @ferruzzi https://github.com/apache/airflow/pull/20305
- [x] operators/batch.py - @ferruzzi https://github.com/apache/airflow/pull/20369
- [x] operators/datasync.py - @ferruzzi https://github.com/apache/airflow/pull/20328
- [x] operators/ecs.py - @ferruzzi https://github.com/apache/airflow/pull/20332
- [x] operators/eks.py - @ferruzzi https://github.com/apache/airflow/pull/20354
- [x] operators/glue_crawler.py - @ferruzzi https://github.com/apache/airflow/pull/20372
- [x] operators/sqs.py - @eladkal https://github.com/apache/airflow/pull/20732
- [x] sensors/eks.py - @ferruzzi https://github.com/apache/airflow/pull/20354
- [x] sensors/redshift.py - @ferruzzi https://github.com/apache/airflow/pull/20374
- [x] sensors/sqs.py - @eladkal https://github.com/apache/airflow/pull/20732
- [x] hooks/athena.py - @ferruzzi https://github.com/apache/airflow/pull/20305
- [x] hooks/cloud_formation.py @ferruzzi https://github.com/apache/airflow/pull/20357
- [x] hooks/datasync.py - @ferruzzi https://github.com/apache/airflow/pull/20328
- [x] hooks/dynamodb.py - @ferruzzi  https://github.com/apache/airflow/pull/20360
- [x] hooks/emr.py - @bhavaniravi https://github.com/apache/airflow/pull/20375
- [x] hooks/eks.py - @ferruzzi https://github.com/apache/airflow/pull/20354
- [x] hooks/kinesis.py - @ferruzzi https://github.com/apache/airflow/pull/20362
- [x] hooks/lambda.py - @ferruzzi https://github.com/apache/airflow/pull/20365
- [x] hooks/ses.py - @ferruzzi https://github.com/apache/airflow/pull/20367
- [x] hooks/sns.py  - @ferruzzi https://github.com/apache/airflow/pull/20368
- [x] hooks/sqs.py - @eladkal https://github.com/apache/airflow/pull/20732

### To be verified (recently changed in the linked campaign):

~~DMS - good~~
~~EC2 - good~~
~~EMR - good~~
~~Glue - Added above~~
~~S3 - good~~
~~SageMaker - good~~

---

### No changes required:
**Operators:**
CloudFormationCreateStackOperator
CloudFormationDeleteStackOperator
GlacierCreateJobOperator
SnsPublishOperator
StepFunctionGetExecutionOutputOperator
StepFunctionStartExecutionOperator
AthenaSensor
CloudFormationCreateStackSensor
CloudFormationDeleteStackSensor
DmsTaskBaseSensor
DmsTaskCompletedSensor

**Sensors:**
GlacierJobOperationSensor
StepFunctionExecutionSensor

**Hooks:**
ElastiCacheReplicationGroupHook
GlacierHook
RedshiftHook
S3Hook
SageMakerHook
SecretsManagerHook
StepFunctionHook

### Related issues

https://github.com/apache/airflow/issues/20139

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ferruzzi** [comment]
@eladkal Should the Hooks be part of this campaign as well, or is that scope-creep getting out of hand?

**Comment by eladkal** [comment]
We should do both 
https://github.com/apache/airflow/pull/20160 already handle Emr 

This task shouldn't take long. Lets try to finish all in the next few days so all new paths/classes will be avaliable in the next peovider release.

**Comment by ferruzzi** [comment]
hooks/logs.py calls the hook AwsLogsHook and... I think we should keep that one.  "LogsHook" is just too generic IMHO.

**Comment by KennyRich** [comment]
> @KennyRich would you like to pick some?

Yes sure!!!

**Comment by dstandish** [comment]
@eladkal i thought that `RedshiftSqlOperator` was not correct and that `RedshiftSQLOperator` ....  i remember discussion about this at some point in the past

**Comment by eladkal** [comment]
> @eladkal i thought that `RedshiftSqlOperator` was not correct and that `RedshiftSQLOperator` .... i remember discussion about this at some point in the past

I think so too. I didnt review the whole list yet.
We always must look for consistency (other operatoa, other providers etc...) In case of sql its easy as we have planty.

**Comment by ferruzzi** [comment]
My mistake!  I'll update OP

**Comment by eladkal** [comment]
> > @KennyRich would you like to pick some?
> 
> Yes sure!!!

Please let us know which so we can assign.

**Comment by KennyRich** [comment]
> > > @KennyRich would you like to pick some?
> > 
> > 
> > Yes sure!!!
> 
> Please let us know which so we can assign.

I'll handle Sqs

**Comment by eladkal** [comment]
@bhavaniravi would you like to take the emr hook?

**Comment by bhavaniravi** [comment]
Yup will do.

**Comment by ferruzzi** [comment]
EKS is a big one, I'll get started on that

**Comment by eladkal** [comment]
@KennyRich do you need help?

**Comment by KennyRich** [comment]
> @KennyRich do you need help?

Please you can help go through my PR
