### ISSUE TITLE
Fail jobs entities on SIGINT

### ISSUE THREAD

**Issue by r39132** [apache/airflow#203]
At Agari, we use the LocalExecutor scheduler on a single EC2 instance with concurrency set to 128 - so we have 128 scheduler processes. We currently only have 2 DAGs -- one for building our email forwarder models, another for our main aggregation and scoring data pipeline flow.  

The jobs page does not make sense and it does not agree with the Task Instance Page. Similarly, the Logs page also shows a lot of running tasks, which are not running in-fact. Examples of all three are provided below. 

**Jobs Page**
How do I interpret what I am seeing here?
- There are 273 "jobs" running? Ok, I buy a handful of backfill jobs against host `etl-00.tad.agari.com` that were CTRL-C'd and hence not cleaned up, but what are the rest? 
- What the heck are all of these hostnames like  `ip-10-10-2-X` doing here? Where are these coming from?

<img width="776" alt="screenshot 2015-07-29 21 47 31" src="https://cloud.githubusercontent.com/assets/581734/8976004/743aa0f8-363b-11e5-9bd9-9cee6f8a6f11.png">

**Task Instances Page**
The Jobs page and the Task Instances page don't agree.

<img width="834" alt="screenshot 2015-07-29 22 13 51" src="https://cloud.githubusercontent.com/assets/581734/8976264/437679c0-363f-11e5-8c7a-cf353a72d806.png">

**Logs Page**
<img width="858" alt="screenshot 2015-07-29 22 20 33" src="https://cloud.githubusercontent.com/assets/581734/8976338/43e6aed8-3640-11e5-9269-3d3864d137c0.png">

**Comment by r39132** [comment]
I'd like the Jobs, Logs, and other views to support a state called "Expired", instead of having them in "Running" but have a heartbeat which is like 2 days old.

**Comment by mistercrunch** [comment]
Agreed. I see how this is confusing. We need a watchdog that keeps an eye on jobs without heartbeat (maybe part of the scheduler daemon) and expires or fails tasks. I think I also need to manage the SIGINT on a task to update the corresponding job. Currently it only flags the task instance as failed on SIGINT/SIGTERM.

In the meantime, the task instance table is the authority on state and jobs / logs aren't used in the logic and are informational indicators around it.

**Comment by r39132** [comment]
Not seeing this issue anymore. Closing
