### ISSUE TITLE
Add Github provider

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#20300]
### Body

Add Github provider based on offical Python SDK https://github.com/PyGithub/PyGithub
The SDK has many objects which can be viewed at https://pygithub.readthedocs.io/en/latest/github_objects.html

It would be nice if we can create a hook that can leverage the package and allow the user to interact with it.

For example: being able to to find when file was last commited.

PR example for creating new provider can be seen on https://github.com/apache/airflow/pull/17068

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by uranusjr** [comment]
Not sure is async support is useful, but [gidgethub](https://github.com/brettcannon/gidgethub) is another solution.

**Comment by pateash** [comment]
@eladkal as far as I know **LGPL-3.0 License** is not compatible with **Apache2** license ( we can use ApacheV2 into LGPL3 but not the otherway around)
So we can't use **PyGithub**.

**Comment by pateash** [comment]
I would like to take this up.

**Comment by eladkal** [comment]
> @eladkal as far as I know **LGPL-3.0 License** is not compatible with **Apache2** license ( we can use ApacheV2 into LGPL3 but not the otherway around), So we can't use **PyGithub** https://www.apache.org/licenses/GPL-compatibility.html Also I would like to take this up.

This is about Airflow provider. https://github.com/apache/airflow/issues/9898 talks about it at length.
There shouldn't be a problem with providers packages.
@kaxil @potiuk can you confirm?

**Comment by potiuk** [comment]
It's OK. LGPL Is ok as an optional dependency.

https://www.apache.org/legal/resolved.html#optional

**Comment by potiuk** [comment]
Alll providers - by definition - are optional dependencies of Airflow.
