### ISSUE TITLE
Airflow API throwing 500 when user does not have last name

### ISSUE THREAD

**Issue by williamfmr** [apache/airflow#20320]
### Apache Airflow version

2.2.2 (latest released)

### What happened

When listing users via GET api/v1/users, a 500 error is thrown if a user in the database does not have a last name. 

```
{
  "detail": "'' is too short\n\nFailed validating 'minLength' in schema['allOf'][0]['properties']['users']['items']['properties']['last_name']:\n    {'description': 'The user lastname', 'minLength': 1, 'type': 'string'}\n\nOn instance['users'][25]['last_name']:\n    ''",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "https://airflow.apache.org/docs/apache-airflow/2.2.2/stable-rest-api-ref.html#section/Errors/Unknown"
}
```

### What you expected to happen

Result set should still be returned with a null or empty value for the last name instead of a 500 error.

### How to reproduce

Create a user in the database without a last name and then hit GET api/v1/users

### Operating System

linux

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
:D . Asigned you Willam (?). What's your last name again :D ?

**Comment by williamfmr** [comment]
haha .. I'd be happy to submit a PR, but I'm not sure how to get started.

**Comment by potiuk** [comment]
CONTIRBUTING.rst :) ?

**Comment by hubert-pietron** [comment]
Hi, it's not like "last_name" field in database for user has "not null" constraint?

**Comment by williamfmr** [comment]
@potiuk, unfortunately my employer does not allow for contributing code to external projects. I have removed myself from this ticket. Very sorry :(

**Comment by arsalanfardi** [comment]
Can I take this up as my first  issue?

**Comment by uranusjr** [comment]
Go ahead.

**Comment by frankcash** [comment]
It looks like the exact reason this occurs is because 

>Hi, it's not like "last_name" field in database for user has "not null" constraint?

last_name has a not null constraint in the DB https://github.com/apache/airflow/blob/8505d2f0a4524313e3eff7a4f16b9a9439c7a79f/airflow/migrations/versions/92c57b58940d_add_fab_tables.py#L99

**Comment by eladkal** [comment]
So the fix is probably just make sure it returns meaningful error rather than 500

**Comment by frankcash** [comment]
Yeah, that's a good idea.  Weird that someone was able to make a user without a last_name if there is a not null constraint, wonder if this was introduced in a migration or something

**Comment by ashb** [comment]
An empty string is distinct from a null value. This is a bug in our OpenAPI/marshmallow schemas.

See also https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
