### ISSUE TITLE
Add a `@task.sensor` TaskFlow decorator

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#20323]
### Description

Implement a taskflow decorator that uses the decorated function as the poke method.

### Use case/motivation

Here is a sketch of the solution that might work:

[sensor_decorator.txt](https://github.com/apache/airflow/files/7721589/sensor_decorator.txt)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mingshi-wang** [comment]
Hi @dstandish I am interested in working on this issue.

**Comment by dstandish** [comment]
Nice @mingshi-wang it's all yours

**Comment by mingshi-wang** [comment]
Hi @dstandish - It would be great if you can please help me look at my first PR to Airflow https://github.com/apache/airflow/pull/20530. Thanks!

**Comment by dstandish** [comment]
nice @mingshi-wang will give it a  look

**Comment by dstandish** [comment]
hi @mingshi-wang where do we stand with this?

**Comment by potiuk** [comment]
I just merged it last night @dstandish

**Comment by dstandish** [comment]
oh, cool 👍
