### ISSUE TITLE
Search List Task Instance

### ISSUE THREAD

**Issue by olegsalei** [apache/airflow#20342]
### Apache Airflow version

2.0.2

### What happened

Search List Task Instance by 4 filters failed (works fine with 3)
---
Dag Id |  Equal to | Dag_id
Task Id |  Equal to | Task_id
Start Date | Grater than | 2021-12-09 02:00:00+00:00 
-- works
Start Date | Smaller than | 2021-13-09 02:00:00+00:00 
-- fails  
![2021_12_16_15_40_49_Airflow](https://user-images.githubusercontent.com/15084610/146376503-b75ef295-045d-4ff2-a50b-bbcc9b2803db.png)
![Airflow_bug](https://user-images.githubusercontent.com/15084610/146376702-754f7c15-66a2-45cb-8dc4-2beb709b5089.png)

### What you expected to happen

Search result with applied filters 

### How to reproduce

Create DAG (or check on existing one) with schedule 0 2,10,14,18,22 * * *.
Browse -> Task Instances -> Search(Dropdown) -> Add 3 filters as described above -> Search(Button) (should work fine) 
After previous step ->  Search(Dropdown) -> Add 4th filter -> Search(Button) (should fail)

### Operating System

amazon-linux

### Versions of Apache Airflow Providers

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact

### Deployment

MWAA

### Anything else

Multiple times

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by humit0** [comment]
@olegsalei
I think it raises error because of last filter is not valid datetime.

**Comment by olegsalei** [comment]
Should it be in a different format? If so, which is the correct one?

**Comment by olegsalei** [comment]
Thank you, I see, should it be wrapped in try-except or I'd rather close the ticket?

**Comment by humit0** [comment]
I think wrapping try-except block is unnecessary.

Maybe your airflow webserver [expose_stacktrace](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#expose-stacktrace) configuration is `False`, so it does not print stacktrace.

**Comment by potiuk** [comment]
Closing. Seems there is nothing to do here
