### ISSUE TITLE
Fail to run breeze on Apple Silicon

### ISSUE THREAD

**Issue by pingzh** [apache/airflow#20351]
### Describe the issue with documentation

When running `./breeze` after installing `brew install gnu-getopt coreutils`, it still complains 

```
ERROR: You are running breeze in OSX environment and you need to install gnu commands

Run 'brew install gnu-getopt coreutils'
```

The root cause is with Apple Silicon, the Homebrew prefix is changed to `/opt/homebrew`

I can find `getopt` under `/opt/homebrew`
```
❯ l /opt/homebrew/opt/gnu-getopt/bin
total 112
drwxr-xr-x   3 ping_zhang  admin    96B Aug 16 06:27 .
drwxr-xr-x  12 ping_zhang  admin   384B Dec 16 10:46 ..
-r-xr-xr-x   1 ping_zhang  admin    54K Aug 16 06:27 getopt
```

### How to solve the problem

I think we need to use `$(brew --prefix)` to get the homebrew prefix

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think not. When you run `brew install gnu-getopt coreutils' it will tell you that you should also set the path.

**Comment by potiuk** [comment]
You can try to run it again and you will see that it's 'cask-only'.  

See https://github.com/apache/airflow/blob/main/BREEZE.rst#getopt-and-gstat

> Run brew install gnu-getopt coreutils and then follow instructions to link the gnu-getopt version to become the first on the PATH. Make sure to re-login after you make the suggested changes.

**Comment by potiuk** [comment]
Ah I see. Yeah. The examples might indeed be improved.
