### ISSUE TITLE
Paused event is logging twice in some pages.

### ISSUE THREAD

**Issue by humit0** [apache/airflow#20373]
### Apache Airflow version

2.2.2 (latest released)

### What happened

If I pause/unpause dag in `Tree`, `Graph`, or `Gantt` page, `/paused` url is calling twice.

![image](https://user-images.githubusercontent.com/8676247/146517082-b359a81c-a53f-4aa7-a2e8-11bdbdd1e4d8.png)

So paused events are logging twice.
![image](https://user-images.githubusercontent.com/8676247/146517366-d25efa3c-a029-4aa4-a655-60a8d84a1e1c.png)

### What you expected to happen

It should be logging only once.

### How to reproduce

Go to `Tree`, `Graph`, or `Gantt` page. And pause/unpause it.

### Operating System

centos

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
Just to ask the obvious question first: you're not double clicking the control are you?

**Comment by humit0** [comment]
@ashb yes I clicked once.

There are duplicated code in `tree.[hash].js` and `dag.[hash].js`, so it call twice.
![image](https://user-images.githubusercontent.com/8676247/146528222-4cd8a672-eb2b-4005-870d-6702c19ac6c7.png)

![image](https://user-images.githubusercontent.com/8676247/146528284-b7790cee-b24f-4997-a82e-f4ef28af2e3c.png)

So I think it needs to split [dag.js](https://github.com/apache/airflow/blob/main/airflow/www/static/js/dag.js) file.

**Comment by ashb** [comment]
Good digging @humit0 !

**Comment by bbovenzi** [comment]
Good catch. Looks like our webpack isn't handling es6 style `import` statements efficiently. Webpack is always annoying to deal with but we already needed to improve it.

**Comment by potiuk** [comment]
Javascript never ceases to surprise me :)

**Comment by humit0** [comment]
Maybe #15896 was similar issue.
