### ISSUE TITLE
Streamline task action UX

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#20382]
Problem:

Clearing a task is a relatively simple process conceptually yet a user is run through multiple different redirects and views. This results in a clunky experience that is slower, causes one to lose context and even end up on a page where they didn't even start on.

Solution:

Handle the API calls within the client and have everything happen within a modal/drawer on the user's current page. The modal can handle confirmation events too.

In Grid view, this is being handled by a new details panel and confirmation modal: https://github.com/apache/airflow/pull/22123
For Graph and Gantt, we should change the `/confirm` endpoints in `views.py` to return a json object instead of rendering a new page and then handling everything in javascript.

**Comment by potiuk** [comment]
Should be great to improve that. User eXperience matters!
