### ISSUE TITLE
Airflow's PythonVirtualenvOperator isn't installing different python versions unless its the version airflow is ran with.

### ISSUE THREAD

**Issue by rustikk** [apache/airflow#20392]
### Apache Airflow version

2.2.2 (latest released)

### What happened

When specifying the version in the PythonVirtualenvOperator it fails to find the version 2.7 and as a result causes the task to fail. As I was writing this issue I decided to test python version 3 and versions 3.6, 3.7, and 3.8 also face this same issue. Python version 3.9.9 is the version of the python running airflow and when specifying the version to 3.9 for the operator it finds the version and installs it correctly.

### What you expected to happen

I expected the PythonVirtualenvOperator to be able to find the version specified and install it successfully. 

### How to reproduce

```
from airflow.models import DAG
from airflow.operators.python import PythonVirtualenvOperator
from airflow.utils.dates import days_ago

import sys

def py2_venv():
    import sys
    inner_version = sys.version[0:3] #'2.7'
    print("inner", inner_version)
    print("inner passed in", "".join(virtualenv_string_args[0][0:3]))
    print("outer", virtualenv_string_args[1][0:3])

with DAG(
    dag_id="python_version_2",
    schedule_interval=None,
    start_date=days_ago(2)
) as dag:

    pv0 = PythonVirtualenvOperator(
        task_id="check_version",
        python_callable=py2_venv,
        string_args=["2.7", f"{sys.version}"],
        python_version=2.7)
```

### Operating System

Docker (debian:buster)

### Deployment

Docker-Compose

### Deployment details

Utilizing astronomer's astro CLI

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You need to have the right version preinstalled if you want to run different Python version (either available in your machine or Docker image if you use Docker). 

Airflow will not install them for you.
