### ISSUE TITLE
Add separate name attribut for dag so that dag can be easily renamed

### ISSUE THREAD

**Issue by char101** [apache/airflow#20396]
### Description

**Problem**

It is not easy to rename dags.

**Suggestion**

It would be better if dag can have both id and name. Id could be some guid/uuid. If not given then id can be generated. At least when required the id can be queried from the database. This way we can change the dag name without changing the id.

```python
DAG_ID = '76c9eb30-4f9c-4806-aad8-931c03679726'
DAG_NAME = 'test'

with DAG(dag_id=DAG_ID, dag_name=DAG_NAME, ...):
  # some tasks
```

If I want to rename the dag then I can simply change the name and I can still get the dag history and not running into the risk of backfilling the dag again.

```python
DAG_ID = '76c9eb30-4f9c-4806-aad8-931c03679726'
DAG_NAME = 'test_edited'

with DAG(dag_id=DAG_ID, dag_name=DAG_NAME, ...):
  # some tasks
```

### Use case/motivation

So that dag can be easily renamed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think it shoudl be part of the bigger discussion on DAG versioning AIP:  https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning. Separating name from id and being able to version a file are - in my view - inseparable.

**Comment by char101** [comment]
DAG already have id. so we just need a name field. Adding name field is basically cosmetic and can be implemented with less risk:

* add name field to the table
* add name parameter to the constructor
* incrementally fix the templates to use dag name instead of id

**Comment by potiuk** [comment]
It's more than that. You also need to update APIs for example to retrieve it and define what kind of relation it will have in the future when we have dag versioning and ID will (likely) change it's meaning of being name. And you need to define how it behaves when  you have duplicate names (can you?) and define what to do if some of your dags have name and some of them not, and probably a  number of changes. Should you be able to query tasks by name? Should you be able to search by it? What should it look like in the UI when different name was used in the past and changed? Should we keep the history of those names? 

Those are just first 12 questions that pop in my head when you say "this is a cosmetic change".  

IMHO - It is not. And we need to introduce such changes only when we know how it fits in the bigger vision of dag versioning. But that's my opinion only so I wonder what others think abou it too.

**Comment by char101** [comment]
> You also need to update APIs for example to retrieve it

At least adding a name field won't break the APIs. So changes can be implemented incrementally.

> ID will (likely) change it's meaning of being name

Why should id be changed into name? Just keep it that way but add an optional name parameter. This way backward compatibility can be maintained.

> you have duplicate names

Should not be a problem  just like two person can have the same name.

> Should you be able to search by it

Of course.

> Should you be able to query by both id and name when hafl of your dags have names and the other does not?

Name should be coalesced to id to maintain backward compatibility.

> What should it look like in the UI when different name was used in the past and changed?

This is versioning problem. What I am suggesting is the problem with the current airflow which does not have versioning. Past names should only appear in a history menu.

> Should we keep the history of those names?

This is the problem of versioning.

All in all I think this is a separate problem and should not be viewed from the versioning point of view.

**Comment by potiuk** [comment]
> All in all I think this is a separate problem and should not be viewed from the versioning point of view.

Yep. That's your opinion looking from short term gain point of view. Mine is simply different when i look at it from product point of view. We just have different opinions :).

**Comment by potiuk** [comment]
I am just a little surprised you have such clarity and know all the answers. I am developing the product for ~3 years and I would not even dear to answer those without trying to understand what you consider deeper consequences and future vision of the product and listening to other's opinion.

**Comment by char101** [comment]
I have the right to have my own opinion whether it is right or wrong. I am not pushing my opinion to you. Expressing my opinion does not prevent others from expressing their opinions.

Also it is clear that you are viewing this from the point of view of a product manager. I am viewing this from the point of view of a user that just want to get things done. You probably should not expect for users to think like a product manager.

**Comment by potiuk** [comment]
I don't deny your right to have an opinion. Nowhere in this discussion actually. I just try to hear (from three posts what others think).Your "defensive" approach make it very difficult for others to express their opinion here. You are risking that others won't chime in here because they will think we are arguing with each other. Just my 2 cents and suggestion to wait what other think before others chime in.

**Comment by eladkal** [comment]
Since this is AIP-36 related. i suggest to take it to the AIP comment page / relevant thread in the mailing list... We usualy dont discuss AIPs in github issues
