### ISSUE TITLE
Add a "previous_schedule" boolean param to "ExternalTaskSensor"

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#204]
My dag scenario is check one folder and import data to hive per 15 minutes.

**Comment by griffinqiu** [comment]
depends_on_past only depends the task. I want to depends the past dag.
I also tried the ExternalTaskSensor, however the ExternalTaskSensor cannot specified time

**Comment by mistercrunch** [comment]
I'll rename this task to add a `previous_schedule` boolean param to `ExternalTaskSensor`, in the meantime you can emit a signal of some sort (DB flag, trigger file, empty partition in a hive signal table) on one side and put a sensor on the other DAG.

**Comment by griffinqiu** [comment]
I have observed the change(aa6fccc31f7679494dd7fb73e36c3f2b0e0a061c) added execution_delta .

I can set the execution_delta same with dag schedule_interval. However, if the depend is the dag self. It cannot been pass at the first dag run turn

**Comment by mistercrunch** [comment]
Click "mark success" in the UI?

**Comment by griffinqiu** [comment]
Yes, It should work, but it does not like a formal solution

**Comment by mistercrunch** [comment]
PRs are welcomed for a more formal solution
