### ISSUE TITLE
Need clearer documentation on setting up Sendgrid to send emails

### ISSUE THREAD

**Issue by raajpackt** [apache/airflow#20419]
### Describe the issue with documentation

https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html

needs to have more documentation on how to use sendgrid to send emails. Like would installing the provider package guarantee the appearance of the "Email" connection type in the frontend? I do not think we can find a Email connection. Secondly do we need to import the providers packages in our dags to make it work or options like email_on_success etc should be automatically working once this is set up.

### How to solve the problem

Better documentation

### Anything else

Better documentation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you like to work on it @raajpackt ? I think the best way to get this documentation improved is to have someone to go through the installation, find all the missing pieces and write it from the user perspective.

This is how most of the documentation of Airlfow is being written. Airflow is created by > 1800 (mostly) voluntaries and actually user documentation is best if written by the users. This is also a great way to "give back" to the community for the free software you get.

**Comment by raajpackt** [comment]
That is of course a great way but unfortunately I am bounded by enough knowledge of the code base to contribute in this. Would be really glad for other people who can address this thereby "giving back" to the community.

**Comment by potiuk** [comment]
I marked it as good-first-issue and maybe someone who uses Sendgrid will contribute it indeed. But the fastest way is when someone who has vested interest, contributes.

**Comment by bhavaniravi** [comment]
I will take this up. I'm working on an Email guide for Airflow, would be a good extension from that

**Comment by kaxil** [comment]
Assigned it to you @bhavaniravi

**Comment by bhavaniravi** [comment]
I was creating an example for this, a few questions popped up.

1. `from_email` in airflow config is not introduced until 2.2.4, but I can still use it. Should I include it in the guide?
2. Is there a reason for `from_email` config alone to be in [lower case](https://github.com/apache/airflow/blob/064efbeae7c2560741c5a8928799482ef795e100/airflow/utils/email.py#L53)? It created confusion in the env variable `AIRFLOW__EMAIL__from_email`
3. When will a user use SMTP config over EmailConnection?
4. Should we create a separate documentation page for the commonly used `utils` method. E.g., `send_email`

**Comment by uranusjr** [comment]
Since new documentation for this would be targeting 2.3+ anyway, using `from_email` is fine IMO.

Casing does not matter in config keys, `from_email` is entirely equivalent to `FROM_EMAIL` here (and the environment variable is always upper case).

**Comment by eladkal** [comment]
@bhavaniravi are you still working on this issue?

**Comment by bhavaniravi** [comment]
Yes, I will raise a PR this week or early next week. I have the content ready
