### ISSUE TITLE
Inconsistencies in Pod labels after AIP-39

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#20421]
### Apache Airflow version

2.2.2 (latest released)

### What happened

The labels on POD created by `KubernetesPodOperator` and `KubernetesExecutor` are inconsistent. The latter was updated during AIP-39 to have `execution_date` or `run_id`.

https://github.com/apache/airflow/blob/aa27d9f92ef261ce2bf2b0e1b3699c1ffd23307f/airflow/kubernetes/pod_generator.py#L361-L374

While KPO still has the same 

https://github.com/apache/airflow/blob/ee68a25facb5541000d5d6524a4009d7e3895ae1/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L308-L320

**Comment by hussein-awala** [comment]
Do we need to make them consistent? the Kubernetes executor pod should have some extra annotations used by the Kubernetes executor job to watch the updates events. Still, these labels are not necessary for the pods created by KPO.

However, adding more labels to KPO pods could be beneficial for users who want to monitor created pods.

**Comment by jedcunningham** [comment]
They don't have to be, but I'd say the "core" labels that associate it with a task would make a lot of sense to keep consistent (basically, the TI pk labels).

[KPO side](https://github.com/apache/airflow/blob/3ae6b4e86fe807c00bd736c59df58733df2b9bf9/airflow/providers/cncf/kubernetes/operators/pod.py#L483-L488) vs [KE side](https://github.com/apache/airflow/blob/3ae6b4e86fe807c00bd736c59df58733df2b9bf9/airflow/providers/cncf/kubernetes/pod_generator.py#L415-L416) - The latter today has both execution_date and run_id.

Not sure when KE got the run_id, but I see these "core" labels on both sides now, so I think we are good to close this.
