### ISSUE TITLE
the API of delete_dag does not delete the record in dag_code

### ISSUE THREAD

**Issue by luoyuliuyin** [apache/airflow#20458]
### Apache Airflow version

2.2.2

### What happened

**the API of delete_dag does not delete the record in dag_code.**

![image](https://user-images.githubusercontent.com/28948186/147068771-0560119d-8d3d-4472-be09-a72f61dfb77f.png)

This function will delete all the records containing the dag_id field, and will delete the related records of TaskFail, TaskInstance, ImportError. But the dag_code table does not have a dag_id field, the records in it will not be deleted.
`function location: airflow.api_connexion.endpoints.dag_endpoint.delete_dag()`
![image](https://user-images.githubusercontent.com/28948186/147068839-850e7442-f565-4ba2-bc55-223686388504.png)

show create table of dag_code
![image](https://user-images.githubusercontent.com/28948186/147068905-0f257348-a56d-4440-9435-6ace5d980865.png)

**For example: delete example_bash_operator**
![image](https://user-images.githubusercontent.com/28948186/147089130-ba0c64b0-22e4-41b9-ad03-18b58086a6ae.png)
![image](https://user-images.githubusercontent.com/28948186/147089558-2895e9f7-b8b2-4044-b7b2-c166ca9c5dce.png)
![image](https://user-images.githubusercontent.com/28948186/147089625-64a3414a-a0ef-4b83-b939-09c0e417b1fc.png)

### What you expected to happen

All related records in the database are deleted, including the dag_code table.

### Operating System

MacOS 12.1

### Versions of Apache Airflow Providers

2.2.2

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is correct. DAG code is related to dag file not dag id. 
DAG file can contain more than one dag_id , so there is no way to delete dag_code when you delete dag id. 
Maybe what you need is to have separate API to delete and manage DAG code separately via PI - this is a good idea and I invite you to create a feature request for it (or even maybe implement it).

**Comment by uranusjr** [comment]
Also note that DAG code entries are automatically cleaned up by the DAG file process when it scans the DAG directory. Everything should end up consistent eventually.
