### ISSUE TITLE
Release 2.5.1 of Amazon Provider

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#20457]
### Apache Airflow version

2.2.3 (latest released)

### What happened

The 2.5.0 version of Amazon Provider contains breaking changes - https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/commits.html specifically https://github.com/apache/airflow/commit/83b51e53062dc596a630edd4bd01407a556f1aa6 or the combination of the following:

- https://github.com/apache/airflow/commit/83b51e53062dc596a630edd4bd01407a556f1aa6
- https://github.com/apache/airflow/commit/d58df468c8d77c5d45e80f2333eb074bb7771a95
- https://github.com/apache/airflow/commit/4be04143a5f7e246127e942bf1d73abcd22ce189

and confirmed by @uranusjr 

I have yanked 2.5.0 and we will need to release ~3.0.0~ 2.5.1 with backwards compatibility fixes 

I have updated the constraints for 2.2.3 for now - https://github.com/apache/airflow/commit/62d490d4da17e35d4ddcd4ee38902a8a4e9bbfff

UPDATED: (@potiuk) to reflect that we are going to release 2.5.1 instead of 3.0.0

**Comment by kaxil** [comment]
cc @potiuk

**Comment by potiuk** [comment]
What kind of breaking changes they are @uranusjr  - they are not immediately visible. Can we make it baclwards-scompatible instead? I would not introduce backwards incompatibility unless we really have a good reason.

**Comment by uranusjr** [comment]
On the surface level, the `AwsBaseHook.expand_role()` now calls `_get_credentials()` with no arguments, which is not supported on older versions, and thus if someone subclasses the hook to reimplement `_get_credentials()`, the code would break after upgrade.

More deeply though, `expand_role()` used to depend on boto’s `get_client_type()` with a dynamic client type, which is deprecated in newer Boto versions. Tt now uses `_get_credentials()` instead to avoid the deprecation. But `expand_role()` does not tak a region argument and therefore cannot pass one to `_get_credentials()`. If we keep compatibility on `_get_credentials()`, we’d break compatibility on `expand_role()` instead.

**Comment by potiuk** [comment]
> More deeply though, `expand_role()` used to depend on boto’s `get_client_type()` with a dynamic client type, which is deprecated in newer Boto versions. Tt now uses `_get_credentials()` instead to avoid the deprecation. But `expand_role()` does not tak a region argument and therefore cannot pass one to `_get_credentials()`. If we keep compatibility on `_get_credentials()`, we’d break compatibility on `expand_role()` instead.

Can't we pass `None` explicitly as region from the `expand_role()`  and leave the argument Optional but without default ?

**Comment by uranusjr** [comment]
Hmm, I think so. And maybe `expand_role()` should gain an optional `region_name` argument as well (defaulting to None and never explicitly used in the provider until 3.0).

**Comment by potiuk** [comment]
Yeah. Seems to small af a thing to make whole provider backwards incompatible.
