### ISSUE TITLE
Need to set `tags=[]` to remove all tags from a DAG.

### ISSUE THREAD

**Issue by ReadytoRocc** [apache/airflow#20468]
### Apache Airflow version

2.2.3 (latest released)

### What happened

When removing the `tags` argument from a DAG, the tags are not removed. You need to set `tags=[]` to remove them.

### What you expected to happen

I would expect that if you remove the `tags` argument from the `DAG` definition, all tags would be removed from the DAG.

### How to reproduce

Add `tags=["foo"]` to your `DAG` definition, and then remove the argument entirely. The `DAG` should still have tag `foo` in the UI. You should see the tag removed once you set `tags=[]`.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other Docker-based deployment

### Deployment details

Astronomer CLI Docker based deployment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PApostol** [comment]
I think this has already been fixed on `main` by changing `self.tags = tags` to `self.tags = tags or []` in [airflow/models/dag.py](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L492) (the change is not in Airflow 2.2.3 though). Can you check the issue against `main`?

**Comment by potiuk** [comment]
Oh yeah. Some nice side-effect of Our #19891  quest with MyPY.

It's been fixed here: 

https://github.com/apache/airflow/pull/20272 

@ReadytoRocc - I am closing the issue now - but if you could double-check if it is really fixed, it would be great.

**Comment by ReadytoRocc** [comment]
@PApostol @potiuk confirmed that this is working as expected on `main`. Thanks!

**Comment by potiuk** [comment]
> @PApostol @potiuk confirmed that this is working as expected on `main`. Thanks!

Glad to hear!

**Comment by EugeneChung** [comment]
You can remove tags from the `dag_tag` table.
