### ISSUE TITLE
no logs returned when an end_date specified at the task level is after dag's end date

### ISSUE THREAD

**Issue by rustikk** [apache/airflow#20471]
### Apache Airflow version

2.2.2

### What happened

When you set an 'end_date' that is after the date for the dag parameter 'end_date' the task fails and no logs are given to the user.

### What you expected to happen

I expected the task to succeed with an 'end_date' of the date specified at the task level.

### How to reproduce

```
from airflow.models import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime

def this_passes():
    pass

with DAG(
    dag_id="end_date",
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    end_date=datetime(2021, 1, 2),
    tags=["dagparams"],
) as dag:

    t1 = PythonOperator(
        task_id="passer",
        python_callable=this_passes,
        end_date=datetime(2021, 2, 1),
    )


```
### Operating System

Docker (debian:buster)

### Deployment

Other Docker-based deployment

### Deployment details

Using the astro cli with docker image:
quay.io/astronomer/ap-airflow:2.2.2-buster-onbuild

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Probably related to #19917 and could be fixed together.
