### ISSUE TITLE
DAG runs overlaps task names in Tree View

### ISSUE THREAD

**Issue by cccs-cat001** [apache/airflow#20483]
### Apache Airflow version

2.2.2

### What happened

In the Tree view page, when the name of the task is ridiculously long, the dag runs grid will overlap the task name. See this picture: 
![image](https://user-images.githubusercontent.com/56204545/147242762-5b5bcad8-edd9-4200-8da9-bbd1d6c6bdd6.png)

The real name of this task is `dummy_task_with_a_really_long_name_that_should_be_covered_by_the_runs`, so you can see that a lot of it is being overlapped. 

### What you expected to happen

I would expect the dag runs grid to move to the right as the length of names gets longer, instead of sticking at what looks to be a hardcoded place on the screen. 

### How to reproduce

Should just be able to create a task with a really long name and let it run a few times for this to show up. 

### Operating System

Debian GNU/Linux 10 (buster)"

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Tree view is rewritten in upcoming 2.3 version of airflow. It fixes many things (on top of removing all the insanity of the previous tree view) https://github.com/apache/airflow/pull/18675
