### ISSUE TITLE
Add "Anchor Date" and "Number of schedules" form elements to tree view

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#205]
The tree view display empty. We my dag settings is 

two_hours_ago = datetime.now() - timedelta(0.084)
default_args = {
    'owner': 'airflow',
    'start_date': two_hours_ago,
}
dag = DAG('import_dna_data', 
        default_args=default_args,
        schedule_interval=timedelta(minutes=15))

![1](https://cloud.githubusercontent.com/assets/179343/8978058/30531744-36d1-11e5-87a5-2b0999fd4dad.jpg)

![2](https://cloud.githubusercontent.com/assets/179343/8978061/34ad0aca-36d1-11e5-9cdd-04ccadfdb71a.jpg)

**Comment by mistercrunch** [comment]
The quick solution is to modify the url parameter `num_runs=25` to something higher. Eventually the UI should have 2 form elements for anchor_date (default = now) and num_runs (default=25). I'll rename this issue and keep it open until we get to it.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/344
