### ISSUE TITLE
Improve the connections list view

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#20515]
### Description

I find the connections view often leads to confusion because connections defined as environment variables and in a secrets backend are not displayed. This is not stated clearly.

I suggest to:

1. Display connections set via environment variables (and hide the edit controls for those connections). This could also help debugging a URI string if you could see the URI components broken down in the connection view.
2. Display an info message in the connections view in case a secrets backend is configured stating that those connections are not visible in the webserver.

### Use case/motivation

Motivation: having to explain over and over that _only_ connections defined in the Airflow metastore are visible in the webserver.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Very, very much agree with it. This is yet another example that we should add helpful description of what's going on where and when users most expect it - at the very moment and place where they experience some pain.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10867 ?

**Comment by potiuk** [comment]
Pretty much so @mik-laj . @BasPH  - should we close that ane?
