### ISSUE TITLE
Several dagruns scheduled at roughly the same time: SLA misses don't show up for the first few.

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#20554]
### Apache Airflow version

2.2.3 (latest released)

### What happened

Here's a dag, I expect it to create 5 dagruns when unpaused, and it does.

```python3
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from datetime import datetime, timedelta
from textwrap import dedent
from time import sleep

decade = 31556952 * 10

with DAG(
    "count_sla_misses",
    start_date=datetime(1970, 1, 1),
    schedule_interval=timedelta(seconds=decade),
    catchup=True,
    doc_md=dedent(
        """
        # Purpose

        Generate an expected number of SLA misses

        ## To Test

        1. Unpause the dag
        2. Wait for dagruns to complete
        3. [browse] -> [SLA Misses]

        ## Expect

        five dagruns, and five SLA misses:

        - 1970 - 1980
        - 1980 - 1990
        - 1990 - 2000
        - 2000 - 2010
        - 2010 - 2020
        """
    ),
) as miss:
    PythonOperator(
        task_id="miss",
        python_callable=lambda x: sleep(x),
        op_args=[20],
        sla=timedelta(seconds=15),
    )
```

### What you expected to happen

I also expect it to create five SLA misses, but only four show up:

![slamiss](https://user-images.githubusercontent.com/5834582/147678208-432bf953-1c1f-460f-80f7-023df8a43e03.png)

### How to reproduce

unpause the dag
let catchup run it five times
notice only four misses

### Operating System

docker / debian

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

`astro dev start` with dockerfile:

```
FROM quay.io/astronomer/ap-airflow:2.2.3-onbuild
```

### Anything else

If this is somehow desired behavior, I can submit a docs change PR if somebody explains to me why it's desired.  But it smells like an actual bug to me.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sweta-dsouza** [comment]
Same dag created 3 records for me instead of 5.

![image](https://user-images.githubusercontent.com/34476770/147691727-dd38c021-538c-4865-8830-fd6d3d2bac73.png)

**Comment by jyotsa09** [comment]
The same dag has created 3 records for me instead of 5.

![image](https://user-images.githubusercontent.com/88504849/147691849-63128368-8b56-4a53-8570-8ba440302838.png)

**Comment by jyotsa09** [comment]
I have tried same dag with 2.4.1 but now it's not creating any records for me.

![2022-10-18 20 39 46](https://user-images.githubusercontent.com/88504849/196470406-269f147d-c19b-420b-b336-67fd5eb6fe87.gif)

cc: @ephraimbuddy

**Comment by potiuk** [comment]
Personal opinion: our SLAs are broken in a number of ways and unless we can do something resonably localized and quic, I do no think we should invest a lot of time in investigation, rather than that we should design a "Good" SLA approach and implement it  basically from scratch (leaving the old SLA as deprecated and legacy).

**Comment by eladkal** [comment]
I'm going to close this one as the SLA feature is currently in development and should solve the pains around the old SLA mechanism.
