### ISSUE TITLE
Whenever we see current DAG run and toggle over different views like Tree view and Task Duration, the targeted view gets changed to different time along with a change in DAG run status..

### ISSUE THREAD

**Issue by MamunManisha** [apache/airflow#20582]
### Apache Airflow version

2.1.2

### What happened

Whenever we see current DAG run and toggle over different views like tree and map, the targeted view gets changed to different time.

For graph view in first toggle, the datetime is: 2021-05-29T08:43:22Z and RunId is manual_2021-05-29T08:43:21+00:00.

But after switching to other views like 'Tree View', 'Task Duration', 'Task Tries', and switching back to graph view, the datetime is changing to 2021-12-27T06:40:04Z and the RunId is changing to manual_2021-12-27T06:40:03.385845+00:00 in airflow window.

The result is routed to different DAG run and is not able to finish the completely.

### How to reproduce

**_Steps to Reproduce:_**

1. Login to Airflow window
2. Try to view DAG.
3. Switch to other views like 'Tree View', 'Task Duration', 'Task Tries'
4. Switch back to Graph View.
5.Check that earlier result that was Success is now displayed as Failed status.

For details, please refer attached screenshot with detailed pipeline view of error.

 
![image001 (1)](https://user-images.githubusercontent.com/96865640/147740070-cf137067-6307-4007-8b8f-0278a4272bde.png)
![image002](https://user-images.githubusercontent.com/96865640/147740080-9c2037be-9a9f-4590-b590-a28c6ae83b05.png)
![image003](https://user-images.githubusercontent.com/96865640/147740089-b0493779-1325-483c-9a88-36c5cdcdcc2f.png)

### Operating System

Linux

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
This should be fixed by: https://github.com/apache/airflow/pull/23462
