### ISSUE TITLE
Add docstrings to DAG class methods

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#206]
Is there an environment variable/some property of a dag to know the actual dags location on the file system?

**Comment by mistercrunch** [comment]
Here:
https://github.com/airbnb/airflow/blob/master/airflow/models.py#L1576

I need to add docstrings to some of these methods so that they surface in the API docs...

Since it's a property you can just use `mydag.filepath`

**Comment by martingrayson** [comment]
Thanks :+1:
