### ISSUE TITLE
Running Airflow in Docker Error - Triggerer's async thread was blocked

### ISSUE THREAD

**Issue by uplsh580** [apache/airflow#20607]
### Apache Airflow version

2.2.3 (latest released)

### What happened

It does not run normally in the process of proceeding with this document([Running Airflow in Docker](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html)).

When Running Airflow step, I executed `docker-compose up`.
And the following errors constantly occur and the execution has not been completed.

```
airflow-triggerer_1  | [2021-12-31 09:38:07,978] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.45 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:08,803] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.21 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:10,222] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 1.14 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:12,214] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 1.13 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:12,615] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.38 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:13,594] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.23 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:14,971] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 1.14 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:16,309] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.22 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-triggerer_1  | [2021-12-31 09:38:17,572] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 0.25 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
airflow-webserver_1  | [2021-12-31 09:38:28 +0000] [30] [INFO] Handling signal: term
airflow-triggerer_1  | [2021-12-31 09:38:23,706] {triggerer_job.py:345} ERROR - Triggerer's async thread was blocked for 4.68 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
```
<img width="2560" alt="ScreenShot 2021-12-31 오후 6 47 22" src="https://user-images.githubusercontent.com/50520567/147816239-241a711b-3938-4d5c-a7ef-cd27efc4a98f.png">

### How to reproduce

I followed this guide document as it is.
https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html

### Operating System

macOS 12.1 (Build Version: 21C52)

### Versions of Apache Airflow Providers

I just use this docker-compose.yaml file
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.2.3/docker-compose.yaml'

### Deployment

Docker-Compose

### Anything else

Docker Version : 20.10.11, build dea9396
Docker-Compose Version : 1.29.2, build 5becea4c

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Likely you are very limitied in resources. Increase memory and CPU available to your docker.

**Comment by uplsh580** [comment]
Oh, I missed this warning.
https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin

**Comment by smktpd** [comment]
@uplsh580  What exactly was the solution?
