### ISSUE TITLE
Add priorityClassName support

### ISSUE THREAD

**Issue by YossiTamari** [apache/airflow#20632]
### Official Helm Chart version

1.2.0

### Apache Airflow version

2.1.4

### Kubernetes Version

1.21.2

### Anything else

It's currently impossible to assign a `priorityClassName` to the Airflow containers.
Seems like a very useful feature to ensure that the Airflow infrastructure has higher priority than "regular" pods.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by subkanthi** [comment]
I can take on this, thoughts on the priorityClasses would be useful.
Simple proposal would be to define 3 priority classes(high, medium, low) and then assign it to different deployments. Maybe airflow-migration takes high priority.


```apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreempting
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class will not cause other pods to be preempted."```

**Comment by YossiTamari** [comment]
Hi @subkanthi, thanks for taking this. My request was only to add support for assigning priorities in values.yaml, not necessarily for creating priorities or assigning them by default (Same thing as [affinity](https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html#kubernetes), which has a default empty value).

**Comment by potiuk** [comment]
assigned it @subkanthi
