### ISSUE TITLE
Edit Task Instance Page does not save updates.

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#20655]
### Apache Airflow version

main (development)

### What happened

On the Task Instances table, one can click on `Edit Record` and be directed to a `Edit Task Instance` page. There, if you try to change the state, it will simply not update nor are there any errors in the browser console.

<img width="608" alt="Screen Shot 2022-01-04 at 10 10 52 AM" src="https://user-images.githubusercontent.com/4600967/148101472-fb6076fc-3fc3-44c4-a022-6625d5112551.png">

### What you expected to happen

Changes to state should actually update the task instance.

### How to reproduce

Try to use the `Edit Task Instance` page

### Operating System

Mac OSx

### Deployment

Virtualenv installation

### Anything else

This page is redundant, as a user can successfully edit task instance states from the table. Instead of wiring up the correct actions, I say we should just remove the `Edit Task Instance` page entirely.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by subkanthi** [comment]
I can take a look at this to disable the edit option.
