### ISSUE TITLE
Airflow Elastic MapReduce connection

### ISSUE THREAD

**Issue by HaloKo4** [apache/airflow#20746]
### Description

Airflow has connections:
```
Amazon Web Services
Amazon Redshift
Elastic MapReduce
```

It wasn't easy to find the `Elastic MapReduce` because it wasn't listed as Amazon.
I think it would be better to rename it to `Amazon Elastic MapReduce` for easier find in the Connections droplist

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Why don't you create PR with it https://github.com/apache/airflow/blob/b597ceaec9078b0ce28fe0081a196f065f600f43/airflow/providers/amazon/aws/hooks/emr.py#L42 ? 

You can become one of the ~1900 contributors. shall I assign you to it?

**Comment by vinitpayal** [comment]
Hey @potiuk I would want to take it up, quite simple and good to start for my open source journey :)

**Comment by vinitpayal** [comment]
@potiuk PR is up for this at https://github.com/apache/airflow/pull/20767
