### ISSUE TITLE
Create documentation on @task_group

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#20762]
https://github.com/apache/airflow/pull/20671#issuecomment-1007619143

> Actually looks like this would be all new documentation on the `@task_group` decorator. I can't find any docs in 2.2.3 that outline the feature (at least not easily) and no docs seem to reference the `[START/END howto_task_group_decorator]` markers in the `example_task_group_decorator` DAG too.

**Comment by eladkal** [comment]
@uranusjr was this completed?

**Comment by uranusjr** [comment]
This was finished in #28001. I totally forgot this issue exists, thanks for the reminder!
