### ISSUE TITLE
Make Airlfow integration with Open-Telemetry "pluggable"

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20778]
We should be able to "plug-in" the open-telemetry integration in Airflow. This should be possible to be done on several layers:

1) we should be able to integrate different exporters by just enabling them (Jaeger, Console, ....). Currently we know that we have to some Gunicorn/Fork workarounds (and write some small code snippets specific per exporter) but ideally we should be able to just configure the exporter

2) Some basic exporters should be runnable via breeze env ("--integration" flag) - this way we should be able to test and enable open-telemetry integration as an optional component during airflow development

**Comment by Melodie97** [comment]
Ok, I’ll work on this
