### ISSUE TITLE
[Provider] Huawei Cloud: Object Storage Service

### ISSUE THREAD

**Issue by CelastrinaLadon** [apache/airflow#20780]
### Description

in airflow, we have a provider for AWS, Google Cloud but I have to use Huawei and did not have a provider yet

so I request a provider for Huawei Cloud and the first service is Object Storage Service.

feature would be

1. list file in the bucket
2. get the file from the bucket
3. upload file to the bucket

### Use case/motivation

I'll make it happen by follow python SDK from Huawei  

https://support.huaweicloud.com/intl/en-us/api-obs_python_sdk_api_en/obs_32_0104.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@CelastrinaLadon assigned to you. Feel free to open PR

**Comment by eladkal** [comment]
Due to the time passed and the fact that no one else expressed interest I suggest to first roll your own provider as a 3rd party https://airflow.apache.org/ecosystem/#third-party-airflow-plugins-and-providers
