### ISSUE TITLE
AIrflow Scheduler does not schedule any tasks when >max running tasks queued with non-existant pool

### ISSUE THREAD

**Issue by fjmacagno** [apache/airflow#20788]
### Apache Airflow version

2.2.3 (latest released)

### What happened

Our airflow instance was not scheduling any tasks, even simple ones using the default pools. The log showed that it was attempting to run 64 tasks, and that every one was trying to use a pool that didn't exist. When i created the missing pool the scheduler started the tasks and started clearing the queue.

### What you expected to happen

The scheduler to continue running correctly-configured tasks, ignoring the incorrectly configured ones, rather than blocking.

### How to reproduce

Create a dag with 64 concurrent tasks, and set a pool that doesnt exist. Create a second dag using the default pool for a single task. Trigger the first, then the second.

### Operating System

ubuntu

### Deployment

Other Docker-based deployment

### Deployment details

Using KubernetesExecutor connected to EKS.

### Anything else

Unfortunately i don't have access to the logs anymore.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by fjmacagno** [comment]
I mean, I just dont think the whole scheduler should stop scheduling tasks because one dag is misconfigured. This caused an entire cross-team airflow installation to stop working because one team made a mistake on one dag, and gods help us if that had been prod.

It seems like if a task is misconfigured in some way that prevents it from running, it shouldn't be considered to be in the queue. Maybe it could at least be shoved to the back of the queue so that other tasks can try to run?

**Comment by SamWheating** [comment]
>  I just dont think the whole scheduler should stop scheduling tasks because one dag is misconfigured. 

Agreed - although in this case though I think that setting `dagrun_timeout`, `max_active_runs` or `max_active_tasks` on your DAG can reduce the ability of a single DAG to use too many resources and thus limit the blast radius of such an incident. 

> Maybe it could at least be shoved to the back of the queue so that other tasks can try to run?

Agreed, I'll have a look through the scheduler logic to see how viable this is.

**Comment by fjmacagno** [comment]
Thats an interesting point though, because we do have most of those set. We cant do dagrun_timeout because it is a 15 day long dag, but max_active_runs is 1 and dag_concurrency is 16, while scheduler parallelism is 64, so it sounds like something is amiss there too.

**Comment by ephraimbuddy** [comment]
@SamWheating @fjmacagno let me know what you think about my PR

**Comment by SamWheating** [comment]
Your PR looks good! 

I think that https://github.com/apache/airflow/pull/19747 also fixes this issue, but I like your approach more as it will prevent this un-runnable DAG from ever making it to the scheduler.
