### ISSUE TITLE
Airflow can not schedule task in new subDAG 

### ISSUE THREAD

**Issue by sunnyxcao79** [apache/airflow#20821]
### Apache Airflow version

2.2.3 (latest released)

### What happened

We are using the input parameter from one configuration file to control the number of SubDAG will be triggered in one DAG.  It works in original configuration,e.g. we set 5 SubDAG, all can run complete normally.   After we try to add one more SubDAG in configuration file,  the subDAG can be listed in UI, but all tasks in the new subDAG can not be scheduled.  (All tasks of other old SubDAG can still run complete normally)

### What you expected to happen

The tasks in new SubDAG can be scheduled as well.  This design works in Airflow 1.10.9

### How to reproduce

Add new subDAG in any DAG with some subDAG,  the case can reproduce.

### Operating System

red hat linux 7

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
SubDAG is a deprecated feature so fixing bugs related to it isn't a priority.
You should switch to TaskGroups.
If this issue is blocking you then maybe you can raise a PR to fix it?

**Comment by sunnyxcao79** [comment]
May I know how to raise a PR?

**Comment by eladkal** [comment]
> May I know how to raise a PR?

We have guide for contributors:
https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst

**Comment by ManiBharataraju** [comment]
@sunnyxcao79 - There is a PR that I created to fix this. Please refer https://github.com/apache/airflow/pull/16508.
To get your subdag scheduled there is a small hack that could unblock you meanwhile, 
1. click on zoom into subdag
2. click on code and turn on the subdag. It will be scheduled.

FWIW, it is better to move to TaskGroups. They offer similar functionality of a subdag.
