### ISSUE TITLE
Static check docs mistakes in example

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#20823]
### Describe the issue with documentation

<img width="1048" alt="Screenshot 2022-01-12 at 4 22 44 PM" src="https://user-images.githubusercontent.com/10162465/149127114-5810f86e-83eb-40f6-b438-5b18b7026e86.png">
Run the flake8 check for the tests.core package with verbose output:

./breeze static-check mypy -- --files tests/hooks/test_druid_hook.py

The doc says flake8 check for tests.core package but it runs mypy check for files

### How to solve the problem

It can be solved by adding the right instruction.
./breeze static-check flake8 -- --files tests/core/* --verbose

Didn't check if the above command is working. But we have to use similar command like above.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to update it :)
