### ISSUE TITLE
Update google-cloud-container package to v2.10.1

### ISSUE THREAD

**Issue by askmeegs** [apache/airflow#20829]
### Description

The google-cloud-container [version constraint in setup.py](https://github.com/apache/airflow/blob/main/setup.py#L305) restricts the version to < 2.0.0, but the latest version of google-cloud-container [is v2.10.1](https://github.com/googleapis/python-container/releases/tag/v2.10.1). 

### Use case/motivation

I help maintain the [google-cloud-container client library](https://github.com/googleapis/python-container), and we believe [this bug](https://github.com/googleapis/python-container/issues/118) (Google Cloud Composer) is caused by an outdated google-cloud-dependency version in Airflow. 

### Related issues

https://github.com/googleapis/python-container/issues/118

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
It was introduced in https://github.com/apache/airflow/pull/10317 due to breaking changes.
Feel free to submit a PR to address it.

**Comment by jyotidhiman0610** [comment]
Hi, @askmeegs are you working on this or can I take this up?

**Comment by potiuk** [comment]
I will add you as assignee already @jyotidhiman0610 :)

**Comment by eladkal** [comment]
Closing as completed
https://github.com/apache/airflow/blob/5246c009c557b4f6bdf1cd62bf9b89a2da63f630/airflow/providers/google/provider.yaml#L86
