### ISSUE TITLE
Provide 'vanilla' Airflow Docker image

### ISSUE THREAD

**Issue by mgorsk1** [apache/airflow#20849]
### Description

Currently the 'minimal' version of Airflow Docker image ships with 20+ extra dependencies, which according to my understanding, are the most common used libraries. The idea of this PR to prepare another, pure Airflow image, which wouldn't have those dependencies and would only ship with core Airflow package. 

[https://github.com/apache/airflow/blob/main/Dockerfile#L37](https://github.com/apache/airflow/blob/main/Dockerfile#L37)

Alternative solutions would be:
- ship separate Airflow images per each executor type (kubernetes, dask, celery, etc.). I like this one equally to having vanilla Airflow image
- fix the issue with dask. I don't like this idea as it's less scalable as any of packages mentioned below could yield similar issues

### Use case/motivation

We are using official Airflow image for Airflow on our k8s cluster, which is constantly scanned for security vulnerabilities. The fact that dask is pinned to very low version is problematic for us cause there are a lot of red flags coming from this package. We do not need dask at all as we rely on KubernetesExecutor. Some of the security scanners work on docker layer level so removing/upgrading dask doesn't solve the problem.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yeah. :slim image is probably a good idea.

**Comment by potiuk** [comment]
I will add it next week after I merge #20664  - this will improve vastly the way how we build our images and it will be easy to add then (ARM support and Python 3.10 are following that closely).

**Comment by mgorsk1** [comment]
Thanks @potiuk! Let me know if I can be of any help with this.

**Comment by potiuk** [comment]
Just want to let to know i have not forgotten about it. It is on my list but we are transitioning to python and debian bullseye support and once done i will add slim version

**Comment by potiuk** [comment]
And one more comment - few more things have happened since (ARM support and some optimisations). This one is "still" on my list after those are complete and we migrate to new python based build-image scripts.

**Comment by potiuk** [comment]
Finally - we are close :). Merged some docker build simplifications in CI and  finally it can be implemented without adding complexity/duplication using the new Python based breeze. :)

**Comment by potiuk** [comment]
Discussion about support for adding those images here: https://lists.apache.org/thread/g2jp5s9cqgwhltz7wd3gkxb7vnnkrp5n - please chime-in @mgorsk1 @eladkal  :) - we are perfectly ready to release such slim images and #23391 is all that we need :). I hope the discussion/consensus will be quick.

**Comment by eladkal** [comment]
@potiuk just to clarify about the policy. What will happen to the 3.7 image when we drop Python 3.7 support?
the image still be available right? The thread mention matrix of 3*4 = 12 images but this number is not static.. it will always grow isn't it?

**Comment by potiuk** [comment]
Nope. It won't. Once we drop 3.7 we will stop releasing them. Same as we did with 3.6 - there is no more `2.3.0-python3.6` image.

**Comment by potiuk** [comment]
The slim images for 2.3.0 are now available:  see lazy consensus reached here: 

 https://lists.apache.org/thread/cfn2ckj5d8xnk0v0og28n4jxhd5pq08v
