### ISSUE TITLE
NoValueSentinel is returned as default-value instead of empty field

### ISSUE THREAD

**Issue by awildturtok** [apache/airflow#20851]
### Apache Airflow version

2.2.3 (latest released)

### What happened

When trying to run a Dag with Config, setup with params, I get `"value" : "NoValueSentinel"` as default value.

### What you expected to happen

An empty field in the default config, or at least prettier defaults (number = 0, str = "").

### How to reproduce

```
params = {
    "value": Param(type="string", minLength=1),
}
```

### Operating System

Dockerfile based on  `apache/airflow:2.2.3-python3.8`

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
#20442.
