### ISSUE TITLE
Ingress for Statsd

### ISSUE THREAD

**Issue by PushRom** [apache/airflow#20867]
### Description

Hello everyone!
Can you add publication of statsd port 9102 via ingress?
Needed to collect metrics in a centralized Prometheus. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
We already have defined annotations on service, so preometheus should detect stated service:
https://github.com/apache/airflow/blob/bbe1efff71496b76e1dda2f19bc3ef13229a3320/chart/templates/statsd/statsd-service.yaml#L36-L37

**Comment by mik-laj** [comment]
Here is  section in Prometheus docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#service

**Comment by PushRom** [comment]
Yes. My mistake. Didn't see the annotations section.
