### ISSUE TITLE
Distinguish links in DAG documentation from code

### ISSUE THREAD

**Issue by Limess** [apache/airflow#20873]
### Description

Currently code blocks (i.e using backticks in markdown) look the same as links when using `dag.doc_md`.

This makes it very difficult to distinguish what is clickable in links.

For example in the image below, 

![image](https://user-images.githubusercontent.com/3199181/149515893-a84d0ef8-a829-4171-9da9-8a438ec6d810.png)

`document-chunker` is a code block, whereas `offline-processing-storage-chunking-manual-trigger-v5` is a link - but they appear identical.

If this was rendered on github it'd look like:

> The restored files must subsequently be restored using a manual trigger of `document-chunker`: [offline-processing-storage-chunking-manual-trigger-v5](https://invalid-link.com), set `s3_input_base_path` as copied and provide the same start and end dates.

notice that the link is clearly different to the code block.

We're using Airflow version 2.1.4.

### Use case/motivation

We're trying to link between manual steps which are possible with Airflow runs for recovery, reducing the need to write long pieces of documentation.

The links are currently difficult to distinguish which causes issues when following instructions.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
What is your `doc_md`?

I can only reproduce this with:

```
doc_md="Test `code block` and a [`link`](https://airflow.apache.org).",
````

But if I don't use a code block in the link text (and you don't in your example), it rendered fine:
![Screen Shot 2022-01-14 at 2 55 30 PM](https://user-images.githubusercontent.com/66968678/149590433-c29b61f0-7ea3-4a24-a8ab-bbf93c172615.png)

**Comment by Limess** [comment]
You're correct - sorry my example was slightly wrong, it's code blocks within links which are unclear:

The screenshot above still applies, this is the Github example:


> The restored files must subsequently be restored using a manual trigger of `document-chunker`: [`offline-processing-storage-chunking-manual-trigger-v5`](https://invalid-link.com), set `s3_input_base_path` as copied and provide the same start and end dates.

Note the code block in a link is still blue: [`offline-processing-storage-chunking-manual-trigger-v5`](https://invalid-link.com)
