### ISSUE TITLE
Airflow database upgrade fails with "psycopg2.errors.NotNullViolation: column "map_index" of relation "task_instance" contains null value"s

### ISSUE THREAD

**Issue by dcardinha** [apache/airflow#20876]
### Apache Airflow version

main (development)

### What happened

I currently have Airflow 2.2.3 and due to this [issue](https://github.com/apache/airflow/issues/19699) I have tried to upgrade Airflow to this [commit](https://github.com/apache/airflow/commit/14ee831c7ad767e31a3aeccf3edbc519b3b8c923).

When I run `airflow db upgrade` I get the following error:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 587bdf053233 -> e655c0453f75, Add TaskMap and map_index on TaskInstance.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "map_index" of relation "task_instance" contains null values
```

The map_index column was introduced with this [PR](https://github.com/apache/airflow/pull/20286).

Could you please advise? 

### Operating System

Ubuntu 18.04.6 LTS

### Deployment

Other

### Deployment details

Kubernetes

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kaxil** [comment]
Map Index hasn't been introduced in Airflow 2.2.3 and nor intended to, it is currently available in the main branch and will be released in Airflow 2.3. So it is very likely you somehow used some code from the main branch.

**Comment by dcardinha** [comment]
Thank you for your answer.

Yes, I was using the code from the main branch.

Is there an estimate as to when Airflow 2.3 will be released?

**Comment by ashb** [comment]
@dcardinha Nothing firm, but our aim is "in about a month"
