### ISSUE TITLE
Bump `jsonschema` version for Airflow 2.3

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#20880]
### Body

We are using jsonschema 3.2.0 which is a 2 years old version.

Based on https://github.com/Julian/jsonschema/blob/main/CHANGELOG.rst there might be the following change that might affect us.:

```
jsonschema.__version__, jsonschema.validators.validators, jsonschema.validators.meta_schemas and jsonschema.RefResolver.in_scope have been deprecated, as has passing a second-argument schema to Validator.iter_errors and Validator.is_valid.
```

Also jsonschema>4.0 supports Python >=3.7 -- so should be good for main and Python 2.3 but not Python 2.2.x

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I think after 2.2.4 we should really drop 3.7 finally. This is unlikely to release 2.2.5 but even if we do, it will be very unlikely we need more cherry-picking that just few PRs. @jedcunningham WDYT?

**Comment by uranusjr** [comment]
Do you mean 3.6? 3.7 is not EOF until June 2023.

**Comment by potiuk** [comment]
::D right :)

**Comment by potiuk** [comment]
I think we should be god to go with that one - all that should be cherry-picked is cherry-picked already :)

**Comment by ephraimbuddy** [comment]
Closed in https://github.com/apache/airflow/pull/21712
