### ISSUE TITLE
Only string, no bools in values.yaml env allowed 

### ISSUE THREAD

**Issue by chla0089** [apache/airflow#20899]
### Apache Airflow version

2.2.3 (latest released)

### What happened

Hi,

with the new release the values.yaml has a strict schema (see #19181).
The new schema allows only for strings for variables in `env`.

Until the new release, I also used booleans. That does not work anymore. The following error occurs during the deployment (I set the environment variable in the `values.yaml` using a `gitlab-ci.yml`):

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- env.0.value: Invalid type. Expected: string, given: boolean
helm.go:88: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- env.0.value: Invalid type. Expected: string, given: boolean
UPGRADE FAILED
```

It is also not possible to use `"true"` or `1` as replacement as they are apparently parsed as boolean and integer and the same error is returned.

Is it possible to change this behaviour, e.g. by allowing also booleans and integers as environment variables? Or is there another solution?

### What you expected to happen

Booleans allowed as environment variables in `values.yaml`.

### How to reproduce

Change the following in the `values.yaml`:

```
env:
  - name: "test-bool"
    value: true
```

### Operating System

Linux Mint 20

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Environment variables are always strings. This validation is correct. Even if you want to set variable to "true", it should be string of value "true" not a boolean..
