### ISSUE TITLE
BQ link console not working - new syntax

### ISSUE THREAD

**Issue by yan-hic** [apache/airflow#20897]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

6.3

### Apache Airflow version

2.2.2

Seems G has changed the format of the URL to get to a query job. 
The `j` parameter = `jobID` is not sufficient anymore. If you try, website states it needs `location` from now on too.
Error is `Invalid value for location: undefined is not a valid value`
Weird as unannounced but at the same time, there is no official documentation for the console shortcuts neither.

I found out that prefixing the jobId with `bq:US:` works for me so it seems the link code must be changed to pass the region as part of `j` param

**Comment by yiga2** [comment]
Actually, that new syntax is out there for quite some time but the `BigQueryConsoleLink` class is not used anymore except in deprecated operators. It would be helpful to fix it and include in the `BigQueryInsertJobOperator`

**Comment by eladkal** [comment]
@yiga2 would you like to work on it?

**Comment by yiga2** [comment]
Honestly no because the shortcut (direct hyperlink) is not documented i.e. endpoint + params that are available. They may change at any point in time w/o notice - like here. If Google makes the feature public, I sure would. For now, it looks more like a hack.
