### ISSUE TITLE
Bytes cast to String in `airflow.providers.google.cloud.transfers.gcs_to_local.GCSToLocalFilesystemOperator` ~142

### ISSUE THREAD

**Issue by danneaves-ee** [apache/airflow#20901]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

```
$ pip freeze | grep apache-airflow-providers
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.3.0
apache-airflow-providers-http==2.0.2
apache-airflow-providers-imap==2.1.0
apache-airflow-providers-pagerduty==2.1.0
apache-airflow-providers-sftp==2.4.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0
```

### Apache Airflow version

2.2.3 (latest released)

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Composer

### What happened

Using `airflow.providers.google.cloud.transfers.gcs_to_local.GCSToLocalFilesystemOperator` to load the contents of a file into `xcom` unexpectedly casts the file bytes to string.

### What you expected to happen

`GCSToLocalFilesystemOperator` should not cast to string

### How to reproduce

Store a file on gcs;
```
Hello World!
```

Read file to xcom
```
my_task = GCSToLocalFilesystemOperator(
    task_id='my_task',
    bucket=bucket,
    object_name=object_path,
    store_to_xcom_key='my_xcom_key',
)
```

Access via jinja;
```
{{ ti.xcom_pull(task_ids="my_task", key="my_xcom_key") }}
```

XCom result is;
```
b'Hello World!'
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is expected. We cannot treat object stored in GCS as "string". It's always retrieved as Bytes. If you know what encoding is used you can easily decode it `ti.xcom_pull(task_ids="my_task", key="my_xcom_key").decode('utf-8') for example.

**Comment by danneaves-ee** [comment]
@potiuk please look at the code here; https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/transfers/gcs_to_local.py#L142

This is a bug.

You cannot cast `byte` to `str` in this way and successfully decode it after. The `str()` method must be supplied with an `encoding` param like this;

```
str(file_bytes, encoding='utf-8')
```

**Comment by potiuk** [comment]
Ah. I see - this actually converts the value of the bytes to nice "string" representation: https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not

> Passing a bytes object to str() without the encoding or errors arguments falls under the first case of returning the informal string representation (see also the -b command-line option to Python). For example:

```
str(b'Zoot!')
"b'Zoot!'"
```

So those are not "bytes" but string containing `b'` :scream: 

Yeah. Agree it's a bug then. Would you like to fix it maybe? What do you think should be the fix @danneaves-ee  ?

**Comment by danneaves-ee** [comment]
Thanks for reopening @potiuk :smile: 

GCS provides a "Content-Encoding" meta key, however, it's optional so I guess not many people would use it. 

Since XComs must be serializable, we have replaced the lines as follows in our work-around;
```
# airflow.providers.google.cloud.transfers.gcs_to_local.GCSToLocalFilesystemOperator ~142
- context['ti'].xcom_push(key=self.store_to_xcom_key, value=str(file_bytes))
+ context['ti'].xcom_push(key=self.store_to_xcom_key, value=str(file_bytes, encoding='utf-8'))
```

But it could be safer to use `sys.getdefaultencoding()` instead of `utf-8`. Or even expose the encoding as a parameter to the class?

What do you think @potiuk?

**Comment by potiuk** [comment]
I think the problem is that we really want to store binary data as string. What I thing should be really good solution is to convert the bytes into string assuming that the bytes follow the encoding specified. And if the data is encoded using different encoding, it will fail.

I think adding optional "encoding" parameter which falls-back to`'utf-8` is a better idea. getdefaultencoding is something I do not really trust in Python. In many places (including str() built-in function, encoding=utf-8 is default rather than getdefaultencoding.

**Comment by potiuk** [comment]
I assigned you to it :)
