### ISSUE TITLE
Xmatters integration on DAG failure

### ISSUE THREAD

**Issue by aranjanthakur** [apache/airflow#20903]
### Description

We want to get alerted via xmatters on a DAG failure.

### Use case/motivation

As far as I know, we get DAG failure notification over email and slack only. We want the integration with xmatters so that we can leverage the notification channels in xmatters. We will be alerted over phone if we are not able to check the email.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
related https://github.com/apache/airflow/issues/12611

**Comment by eladkal** [comment]
Closing infavor of #12611
