### ISSUE TITLE
Unable to access Airflow MWAA UI

### ISSUE THREAD

**Issue by amansehgal-ccx** [apache/airflow#20914]
### Apache Airflow version

2.0.2

### What happened

On updating the requirements.txt with jdbc(apache-airflow-providers-jdbc) driver, I restarted the airflow service. The service took around 20 minutes to update and showed status as `Available`. On clicking `Open Airflow UI`, I received a message `Something bad has happened. Please consider letting us know by creating a bug report using GitHub.` As per my understanding the scheduler isn't starting in the background, as this error appears on DAGs page.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/93635963/149872437-81712e2c-8210-4172-814c-824e601b60bb.png">

### What you expected to happen

Ideally the DAGs screen should have appeared with list of DAGs from dags folder. But, I'm unable to access the Airflow UI and see any DAGs. Even on restarting the Airflow service, by adding a blank `requirements.txt`, skipping `requirements.txt`, the error still persists.

### How to reproduce

Add `apache-airflow-providers-jdbc` to `requirements.txt` and restart Apache Airflow via AWS Management Console.

### Operating System

Amazon MWAA

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
It looks like problem related to MWAA. Please contact Amazon support.
