### ISSUE TITLE
Update web ui to allow for using strict content security policies

### ISSUE THREAD

**Issue by ttaubermarshall-stripe** [apache/airflow#20934]
### Description

CSP (Content Security Policy) is a layer of security that can be applied to web applications to mitigate certain types of attacks, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Currently, it is difficult to apply a strict CSP to the Airflow web ui due to the use of certain html constructs that are considered unsafe, such as inline scripts and styles and style attributes. Rewriting the Airflow html templates to remove these constructs would allow for stricter policies to be applied.

### Use case/motivation

Applying strict CSPs creates confidence that the web application is not vulnerable to certain types of attacks such as XSS, which is useful for security conscious users and for passing security audits.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The web UI of airlfow is being overwritten as we speak with some of the goals of removal the inline scripts etc. https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-38+Modern+Web+Application

**Comment by ttaubermarshall-stripe** [comment]
Thanks for the quick response! Sorry I wasn't aware of the ongoing work

**Comment by vandanthaker-ey** [comment]
@potiuk there are still some references to inline scripts and styles and style attributes in latest version of airflow. due to which it's difficult to set strict CSP. which commit fixed this? if you can please share

**Comment by potiuk** [comment]
Wher did you make an assumption the commit is merged from? 

This AIP is still in progress If you have not noticed. We are discussing it as part of Airlfow 2 workstream to complete it https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+3+Workstreams 

And if you would like to help with hasing out your concerns, or make proposal other than already discussed there or even (which will be best - commit to it and contribute in the process of progressing with it - that would be fantastic). There are regular calls we have on Airflow 3 plans https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+3.0 and we welcome anyone who would like to contribute there. Commenting and raising your hand in the AIP is the best thing you can do to speed it up.
