### ISSUE TITLE
Airflow doesn't start in container

### ISSUE THREAD

**Issue by shidenko97** [apache/airflow#20947]
### Apache Airflow version

2.0.2

### What happened

Yesterday (18.01.2022) got an error regarding MySQL key repo while building Airflow image, as I can see [it](https://github.com/apache/airflow/issues/20911) was fixed and we got [updated docker image](https://hub.docker.com/r/apache/airflow/tags?page=1&name=2.0.2-python3.6). After it we got new one error - can't build docker image because of following line `chgrp airflow ..`. This group was unexpectedly removed from from original image. We also removed this line and successfully built it. 
Now we have issue with starting pod in k8s - 
```
BACKEND=sqs
DB_HOST=None
DB_PORT=
....................
ERROR! Maximum number of retries (20) reached.
Last check result:
$ run_nc 'None' ''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
Can't parse  as an IP address
```
Before it worked well at least till the end of previous week.

### Operating System

apache/airflow:2.0.2-python3.6

### Deployment

Other Docker-based deployment

### Anything else

ENV vars:
```
  REGION: "eu-west-1"
  AWS_DEFAULT_REGION: "eu-west-1"
  NODE_ENV: "integration"
  ENVIRONMENT_TYPE: "integration"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://***:***@***.eu-west-1.rds.amazonaws.com/airflow"
  AIRFLOW__CORE__PARALLELISM: 4096
  AIRFLOW__CORE__DAG_CONCURRENCY: 2048
  AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 2048
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://***:***@***.eu-west-1.rds.amazonaws.com/airflow"
  AIRFLOW__CELERY__BROKER_URL: sqs://
  AIRFLOW__CELERY__DEFAULT_QUEUE: airflow-default
  AIRFLOW__CELERY__WORKER_CONCURRENCY: 8
  AIRFLOW__CELERY__WORKER_AUTOSCALE: '8,4'
  AIRFLOW__CELERY__WORKER_PREFETCH_MULTIPLIER: 4
  AIRFLOW__CELERY__CELERY_CONFIG_OPTIONS: celery_config.integration.CELERY_CONFIG
  AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__REGION: "eu-west-1"
  AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE: 512
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 4
  AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY: 512
```

External CELERY_CONFIG:
```
from airflow.config_templates.default_celery import DEFAULT_CELERY_CONFIG

EXTRA_CELERY_CONFIG = {
    'broker_transport_options': {
        'visibility_timeout': 21600,
        'region_name': "eu-west-1",
        'region': "eu-west-1",
        'predefined_queues': {
            'airflow-default': {
                'url': 'https://sqs.eu-west-1.amazonaws.com/***/airflow-default',
            },
        },
    },
}

CELERY_CONFIG = dict(DEFAULT_CELERY_CONFIG, **EXTRA_CELERY_CONFIG)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yeah. The 2.0.2 image has been refreshed including the latest scripts, and I think that was a bit too much invasive update for 2.0 images. Give me some time and I will refresh it again with the originl version.

**Comment by potiuk** [comment]
~ 30 minutes ?

**Comment by eldarnegrinperion** [comment]
awesome

**Comment by shidenko97** [comment]
great, we are waiting, thanks

**Comment by potiuk** [comment]
3.6 image should be there: please let me know it it works. I am updating other 2.0 images too.

![image](https://user-images.githubusercontent.com/595491/150134208-3786b78a-cdfd-4fb5-af95-fbd8cdc5300b.png)

**Comment by shidenko97** [comment]
ok, we will let u know

**Comment by shidenko97** [comment]
Yes, it works. thanks!

**Comment by potiuk** [comment]
Yep. I recreated and pushed all 2.0* images with as close configuration as possible for those! Thanks for raising the issue!

**Comment by potiuk** [comment]
> Yes, it works. thanks!

Glad I could help !
