### ISSUE TITLE
DagFileProcessor 'NoneType' is not iterable

### ISSUE THREAD

**Issue by momoadc** [apache/airflow#20993]
### Apache Airflow version

2.2.2

### What happened

I'm seeing the same log repeating in the Scheduler.
I'm working in a restricted network so I cannot bring the entire log:
```
in bulk_write_to_db
    if orm_tag.name not in set(dag.tags)
TypeError: 'NoneType' object is not iterable
```
I saw that a single DAG didn't have any labels and i tried to add a label but the log is still showing

### Operating System

Debian 10 (Scheduler image)

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

I'm deploying on OpenShift 4.8 using the official Helm Chart v1.3.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Could you provide a simple DAG to reproduce this behaviour? I have tried setting tags=None but I couldn't get the error
