### ISSUE TITLE
Triggerer Process Do Not create new trigger instance to run

### ISSUE THREAD

**Issue by Greetlist** [apache/airflow#21005]
### Apache Airflow version

2.2.1

### What happened

When a Deferrable Task which is cleared or generated. This Trigger's TriggererId is NULL,and never change, which cause this trigger is never init and run by triggerer process.

### What you expected to happen

When a Deferrable Task is generated, It will init and run correctly.

### How to reproduce

Clear a Deferrable Task.
I add some log to source code and find out the reason of this problem:
![image](https://user-images.githubusercontent.com/18439743/150479992-a6223697-760f-4e8c-b8b7-a3b20a9641e1.png)

First Query:
``` is None ``` has a strange behavior, It does not work.
Second Query:
when the trigerer_id has a NULL value in database, it can not query correctly.

I fix both problems by:
![image](https://user-images.githubusercontent.com/18439743/150480781-c110e240-a1f6-4a3a-9b26-7b15ce274844.png)

### Operating System

Ubuntu 16.04

### Deployment

Other

### Deployment details

1.One Triggerer Process
2. Three Scheduler
3. Pecona Mysql 8.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you to it @Greetlist  - can you please make a PR for that one with "Fixes: #21005" in the message (and cc: @andrewgodwin best to review it ), I thin you wil have to add a test case for that one but we can guide you.

**Comment by Greetlist** [comment]
I'm willing to make a PR for it, but I don't know how to add a test case. By the way, there is a ```test_trigger.py``` file in tests, Can I just use the file to test this case?

**Comment by potiuk** [comment]
I believe so - but do not know too much about it - I think you can start with PR even without tests and the right people will comment there on how to add tests!

**Comment by Greetlist** [comment]
I have another PR [#19640](https://github.com/apache/airflow/pull/19640) which has not been Merged yet.I should wait until it is finished so I can start a new PR for this.

**Comment by eladkal** [comment]
@Greetlist are you working on this issue?

**Comment by Greetlist** [comment]
@eladkal I found this problem is solved by #21770. I close this issue.
