### ISSUE TITLE
AWS Systems Manager Parameter store support for Airflow AWS Provider package

### ISSUE THREAD

**Issue by hrishik** [apache/airflow#21008]
### Description

Airflow DAGs when used in AWS context, the parameter sharing across different subsystems becomes tedious job. There is a need to create a central parameter handling repository that can be accessed by any service provider (Such as AWS Service) outside of Airflow DAG. 

### Use case/motivation

One important part of DAG based orchestration is sharing of metadata and configuration across different service providers.
Existing alternative of using XCom feature of Airflow has its own limitations in terms of security, encryption, extensibility etc., 

AWS Systems Manager parameter store provides the parameter sharing mechanism, and it is directly supported by all AWS services including lambda, glue, cloud-formation etc. It is an important addition to Airflow to develop the operator for AWS Systems Manager parameter store to standardize information sharing across different services and Airflow DAG seamlessly. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The SystemsManagerParameterStoreBackend is already available in Airflow as custom Secrets manager: 

https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html#airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend

**Comment by hrishik** [comment]
> The SystemsManagerParameterStoreBackend is already available in Airflow as custom Secrets manager:
> 
> https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html#airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend

The existing operator only provides a read for specific actions i.e. connection URI, Config, and custom variable pertaining to airflow information. I am talking about using SSM parameter store as metadata storage to share configuration/metadata across different subsystems, as well as airflow

**Comment by potiuk** [comment]
I don't thik Airlflow will never have "AWS" or "Google" or any other "specific" configuration built in in other way that current "customization options".  Airflow is "Cloud Agnostic". 

It provides features to "talk" to external systems (via Providers: Hoops, Operators, Sensors) and airflow configuration capabilities can be extended precisely via Custom Secrets Backend. 

If you also want to use SystemsManagerParameter for sharing Inter-tasks metadata - feel free to add and contribute custom XCom Backend using  https://airflow.apache.org/docs/apache-airflow/stable/concepts/xcoms.html#custom-backends in the Amazon Provider. But that does not require a separate issue or agreement, just contribute it to the AWS provider.
