### ISSUE TITLE
Building AWS Lambda operator support for Airflow AWS Provider package

### ISSUE THREAD

**Issue by hrishik** [apache/airflow#21009]
### Description

AWS Lambda offers serverless event driven mechanism across different AWS and other services in enterprise landscape. This feature is to bring in the event handling capabilities support in Airflow by building AWS Lambda operator, that will enable invocation of Lambda functions seamlessly.

### Use case/motivation

AWS Lambda is the key drivent for event based architecture for customers who use AWS services extensively. However, today Airflow does not provide a direct support to trigger lambda functions from DAGs. This feature will enable the Airflow designers to directly call lambda function through AWS Lambda operator.

### Related issues

https://github.com/apache/airflow/pull/5914

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@hrishik feel free to open PR. assigned the issue to you

**Comment by eladkal** [comment]
Closed in https://github.com/apache/airflow/pull/21686
