### ISSUE TITLE
Supports SQL in DatabricksHook

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#21037]
### Description

Currently, we support submitting spark jobs for the Databricks service. On December 15, 2021, they announced [General Availability of Databricks SQL](https://databricks.com/blog/2021/12/15/announcing-general-availability-of-databricks-sql.html) and we should provide support for it also.

To do this, we can use one of the existing libraries that provide integration with SQLAlchemy/DBApi:
- [https://pypi.org/project/databricks-sql-connector/](`databricks-sql-connector`) - Apache 2 Licensed (?), officially maintained by Databricks, code source is not available publicly (yet?)
- [https://github.com/crflynn/databricks-dbapi](`databricks-dbapi`) - MIT Licensed, unmaintained, open-source public available

In particular, we should consider using DbApiHook class. 

CC: @eskarimov  @alexott @christophergrant @Mokubyow  

### Use case/motivation

Support a new kind of task.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by alexott** [comment]
It’s basically #21030 that I’ve filed today

**Comment by mik-laj** [comment]
Ahh yes. So I close this PR.  I opened this PR because I saw that Apache Superset had some changes related to Databricks.
https://github.com/apache/superset/issues/18139
