### ISSUE TITLE
Databricks: Add support for execution of SQL commands against clusters/SQL endpoints

### ISSUE THREAD

**Issue by alexott** [apache/airflow#21030]
### Description

Airflow supports communication with different databases using native interfaces or JDBC. But it's harder to use JDBC operator with Databricks as it requires additional downloads, etc. It would be really useful to allow to extract data from Databricks SQL endpoints/clusters without need to install additional objects, like, JDBC/ODBC drivers.

I'm opening issue just to visibility, as I'm starting to work on this functionality and wants to avoid doing double work

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
ASsigned you to it @alexott

**Comment by mik-laj** [comment]
Do you know where the source code for the `databricks-sql-connector` package is available? The metadata for this package specifies that it is released under the `Apache Software License (http://www.apache.org/licenses/LICENSE-2.0)` license, so the source code should be public.
![Screenshot 2022-01-22 at 22 45 42](https://user-images.githubusercontent.com/12058428/150656474-92e1bc16-a1fc-41af-b508-7afd6f904836.png)

**Comment by alexott** [comment]
Not sure, need to check

**Comment by mik-laj** [comment]
It would be great if this information were added to the package metadata.
https://github.com/apache/airflow/blob/d5cafc901158ec4d10f86f6d0c5a4faba23bc41e/setup.cfg#L60-L66

**Comment by mik-laj** [comment]
@juliuszsompolski @NiallEgan Do you know where the source code for the databricks-sql-connector package is available?

**Comment by NiallEgan** [comment]
Hi @mik-laj, we're still working on hosting the source code in a public repo. We hope to make it more publicly available over the coming months.
