### ISSUE TITLE
More ArtifactsHub specific labels in docker image

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#21046]
### Description

We added two labels that allow us to publish docker images in [ArtifactHub](https://artifacthub.io/). We should consider adding other labels as well, if it helps to exposing our image on ArtifactHub. https://artifacthub.io/docs/topics/repositories/#container-images-repositories

Probably, we should consider adding these labels with `docker build --label` i.e. as a docker command argument instead of Dockerfile instruction. For now, we should hold off on this change, as the image building process is undergoing a major overhaul - rewriting from Bash to Python.

### Use case/motivation

Better exposition of our images on ArtifactHub

### Related issues

https://github.com/apache/airflow/pull/21040#issuecomment-1019423007

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
We will do it when we finish converting of build image to python.

I prefer to only change the Bash scripts if absolutely necessary as we will have to move all those changes to Python version (and we are not very far from that to be honest)

**Comment by mik-laj** [comment]
@potiuk Is this a good time to start doing this?

**Comment by potiuk** [comment]
Very close to. Just merged a few breeze changes over the weekend that finalized using `breeze` in CI and removing the old build-image code so yeah. I will take a look soon. :)
