### ISSUE TITLE
Dag dependency view is not rendering for Postgres backed Airflow

### ISSUE THREAD

**Issue by zambadruzaman** [apache/airflow#21059]
### Apache Airflow version

2.2.2

### What happened

Dag dependency view is not rendering for Postgres backed Airflow.

### What you expected to happen

In this [if statements](https://github.com/apache/airflow/blob/cecd4c8059e04c5be0cfec67ebb576d08d83f7b9/airflow/models/serialized_dag.py#L312), the iterator for the `else` part (which is including Postgres) is assigned as session.query object which is shouldn't be.
Current :
```
if session.bind.dialect.name in ["sqlite", "mysql"]:
    query = session.query(cls.dag_id, func.json_extract(cls.data, "$.dag.dag_dependencies"))
    iterator = ((dag_id, json.loads(deps_data) if deps_data else []) for dag_id, deps_data in query)
elif session.bind.dialect.name == "mssql":
    query = session.query(cls.dag_id, func.json_query(cls.data, "$.dag.dag_dependencies"))
    iterator = ((dag_id, json.loads(deps_data) if deps_data else []) for dag_id, deps_data in query)
else:
    iterator = session.query(cls.dag_id, func.json_extract_path(cls.data, "dag", "dag_dependencies"))
return {dag_id: [DagDependency(**d) for d in (deps_data or [])] for dag_id, deps_data in iterator}
```

It should be like this : 
```
if session.bind.dialect.name in ["sqlite", "mysql"]:
    query = session.query(cls.dag_id, func.json_extract(cls.data, "$.dag.dag_dependencies"))
elif session.bind.dialect.name == "mssql":
    query = session.query(cls.dag_id, func.json_query(cls.data, "$.dag.dag_dependencies"))
else:
    query = session.query(cls.dag_id, func.json_extract_path(cls.data, "dag", "dag_dependencies"))

iterator = ((dag_id, json.loads(deps_data) if deps_data else []) for dag_id, deps_data in query)
return {dag_id: [DagDependency(**d) for d in (deps_data or [])] for dag_id, deps_data in iterator}
```

### How to reproduce

1. Deploy an Airflow instance with Postgres as the meatadata DB
2. Create two dags (one dag depends to the other), it can use `TriggerDagRunOperator` or  `ExternalTaskSensor`
3. Check the Dag dependencies view from the UI : Browse ->. Dag dependencies

### Operating System

Debian GNU/Linux 10  VERSION_ID="10" 

### Versions of Apache Airflow Providers

apache-airflow                           2.2.2
apache-airflow-providers-amazon          2.4.0
apache-airflow-providers-celery          2.1.0
apache-airflow-providers-cncf-kubernetes 2.1.0
apache-airflow-providers-databricks      2.0.2
apache-airflow-providers-docker          2.3.0
apache-airflow-providers-elasticsearch   2.1.0
apache-airflow-providers-ftp             2.0.1
apache-airflow-providers-google          6.1.0
apache-airflow-providers-grpc            2.0.1
apache-airflow-providers-hashicorp       2.1.1
apache-airflow-providers-http            2.0.1
apache-airflow-providers-imap            2.0.1
apache-airflow-providers-jira            2.0.1
apache-airflow-providers-microsoft-azure 3.3.0
apache-airflow-providers-microsoft-mssql 2.0.1
apache-airflow-providers-mongo           2.2.0
apache-airflow-providers-mysql           2.1.1
apache-airflow-providers-odbc            2.0.1
apache-airflow-providers-opsgenie        2.0.1
apache-airflow-providers-postgres        2.3.0
apache-airflow-providers-redis           2.0.1
apache-airflow-providers-salesforce      3.3.0
apache-airflow-providers-sendgrid        2.0.1
apache-airflow-providers-sftp            2.2.0
apache-airflow-providers-slack           4.1.0
apache-airflow-providers-sqlite          2.0.1
apache-airflow-providers-ssh             2.3.0
apache-airflow-providers-tableau         2.1.2

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zambadruzaman** [comment]
Closed this issue, the problem is not due to any bug, it's configuration issue on my side.

**Comment by lidalei** [comment]
> 



> Closed this issue, the problem is not due to any bug, it's configuration issue on my side.

Hi @zambadruzaman, could u share which configuration issue? We had the same problem after deleting some dags.
The browser shows error
```
Uncaught TypeError: Cannot set properties of undefined (setting 'label')
    at dagre-d3.min.js:103:1930
    at Array.forEach (<anonymous>)
    at preProcessGraph (dagre-d3.min.js:103:1833)
    at Array.fn (dagre-d3.min.js:103:453)
    at Array.Co.call (d3.min.js:3:15178)
    at renderGraph (dagDependencies.bd18a52029a9cc9bbe0d.js:265:12)
    at Object.9 (dagDependencies.bd18a52029a9cc9bbe0d.js:288:1)
    at __webpack_require__ (dagDependencies.bd18a52029a9cc9bbe0d.js:30:30)
    at dagDependencies.bd18a52029a9cc9bbe0d.js:94:18
    at dagDependencies.bd18a52029a9cc9bbe0d.js:97:10
DevTools failed to load source map: Could not load content for http://airflow.datadott.int/static/appbuilder/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by zambadruzaman** [comment]
Hi @lidalei, yes it was the exact same issue, when you delete any dags, make sure there is no other dag depends on the deleted dag. If you have a dag which has external trigger or sensor pointing to the deleted dag, the dependency graph will be broken and the [dagre-d3](https://github.com/dagrejs/dagre-d3) js won't able to render the graph.

**Comment by potiuk** [comment]
Hmmm maybe it woudl be a good idea to add it as PR to https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/external_task_sensor.html?highlight=dag%20dependency (I guess this is the right page) 

I think the two f you @lidalei  @zambadruzaman are one of the two best people out there to write such a description tha will be helpful and useful for people like you who will struggle with it :). This is really a good way to give back in return for the free software you get ! You can become one of the more thab 1900 (and approaching 2000 fast) number of contributors to Airflow?

This is very simple. Just click "Suggest chnage on this page" at the bottom right and you will get a PR where you will be able to add the change. What say you ?

**Comment by lidalei** [comment]
@potiuk Thanks! I created a PR to explain the case. https://github.com/apache/airflow/pull/21170
