### ISSUE TITLE
Templated fields for DynamoDBToS3Operator similar to MySQLToS3Operator

### ISSUE THREAD

**Issue by rpauli** [apache/airflow#21057]
### Description

I am using Airflow to move data periodically to our datalake and noticed that the MySQLToS3Operator has tempalted fields and the DynamoDBToS3Operator doesn't. I found a semi awkward workaround but thought templated fields would be nice.
I supposed an implementation could be as simple as adding 

  template_fields = (
      's3_bucket',
      's3_key',
  )

to the Operator similar to the MySQLToS3Operator.
Potentially one could also add a log call in execute() 
as well as using with in the NamedTemporaryFile

### Use case/motivation

At the moment MySQLToS3Operator and DynamoDBToS3Operator behave differently in terms of templating and some of the code in MySQLtoS3Operator seems more refined.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
assigned you !

**Comment by gmcrocetti** [comment]
I'm interest on it. I'll give it a try @potiuk . o/
