### ISSUE TITLE
Update the architecture overview to include Triggerer

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21071]
### Body

Following up after the [discussion](https://github.com/apache/airflow/discussions/21068) : we need to update our Concept/Architecture overview to include Triggerer: https://airflow.apache.org/docs/apache-airflow/stable/concepts/overview.html

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
I wonder if it would be better to generate the diagram with code, for example: https://github.com/mingrammer/diagrams
that way we can update the diagram by modifying code and pre commit can generate the image when the code is changed. This will make future modification very simple.

**Comment by potiuk** [comment]
Absolutely. I woudl even said we can continue using Mermaid: https://github.com/mermaid-js/mermaid it's popular, open-source, we already use it in CI and it even supported by Github by default - so if we add the diagram as file in Github it will be rendered there when someone opens it and you will be able to compare rendered images when there is a change in PR.

**Comment by potiuk** [comment]
See https://github.com/apache/airflow/blob/main/CI_DIAGRAMS.md - those diagrams are rendeded on-the flight by GitHub

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/36035
