### ISSUE TITLE
Wrong time in task's log interface

### ISSUE THREAD

**Issue by yuanke7** [apache/airflow#21081]
### Apache Airflow version

2.2.2

### What happened

I've set right timezone in docker-compose like this:
    AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Shanghai'
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE :  'Asia/Shanghai'
And I've set the right timezone in UI like this:
![image](https://user-images.githubusercontent.com/48709060/150906800-65cee25b-7e25-4266-a0ad-03477575a007.png)

In other interface, timezone is perfect right, but in log interface it shows UTC timezone which is not as my settings:
![image](https://user-images.githubusercontent.com/48709060/150907049-04f5261c-3169-4144-8675-115658b79d5d.png)
![image](https://user-images.githubusercontent.com/48709060/150907170-6f2935be-8e67-4a00-8442-edf5185331c9.png)

### What you expected to happen

I expected time shows correctly as my settings in log interface.

### How to reproduce

As my settings.

### Operating System

CentOS Linux 7

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-cncf-kubernetes==2.1.0
apache-airflow-providers-docker==2.3.0
apache-airflow-providers-elasticsearch==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.1.0
apache-airflow-providers-grpc==2.0.1
apache-airflow-providers-hashicorp==2.1.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-microsoft-azure==3.3.0
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-odbc==2.0.1
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-redis==2.0.1
apache-airflow-providers-sendgrid==2.0.1
apache-airflow-providers-sftp==2.2.0
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0

### Deployment

Docker-Compose

### Deployment details

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Which timestamps are you expected to be formatted in CST? The dates at the beginning of each line surrounded by`[]` in your screenshot appear to be correct. We currently do not format the dates inside a log message.
