### ISSUE TITLE
Oops! Something wrong happened

### ISSUE THREAD

**Issue by shadishomali** [apache/airflow#21094]
### Apache Airflow version

2.0.2

### What happened

I am using MWAA (Managed Apache Airflow) AWS version of 2.0.2. I recently uploaded a new DAG file. However, I am unable to access it from UI, I'm getting an error with the following: 

```
Ooops!

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.
```

### What you expected to happen

I'm expecting to be able to access the DAG.

### Operating System

Linux/ MWAA

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
From your description I would suggest to report it to the support of Amazon MWAA.
This doesn't seem to be Airflow issue.
