### ISSUE TITLE
Breeze: Detecting if image needs to be rebuild by Breeze and trigger rebuilds

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21103]
In many breeze commands, we want to check if the image is "fresh" - i.e. whether the changes in the current sources are much different from the ones we had when the last time we run "breeze-build-image` (CI image only). In case we find that there were changes to important files (using hashes stored in .build) we should:

1) ask the user if it is ok to rebuild the image (timing out after 4 seconds) 
2) if the user answered "yes" make sure that the code of the user is rebased and if not - warn the user that it might take a lot of time and only proceed if the user agrees to it
3) after successful rebuild we should store "hashes" of all the important files in .build - this way we will know, next time when those file change, that the last build was done when those files were different.

**Comment by Bowrna** [comment]
@potiuk Could i pick up this issue?

**Comment by potiuk** [comment]
Actually.... that's already done.:)
