### ISSUE TITLE
Breeze: Setting up local virtualenv

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21105]
There shoudl be a comand that allows to set-up local virtualenv easly.

This involves:

* checking is airlfow is installed in "${HOME}/airflow" and warning and suggesting to move elsewhere if so (this is very bad because ${HOME}/airflow is by default where airflow stores all files (logs/config etc).

* cleaning the "${HOME}/airflow" and regenerating all necessary folders and files

* checking if vitualenv is activated - if not writing helpful message

* checking if additional dependencies are installed, and based on the OS, suggest what shoudl be installed (note we  do not have Windows support here).

* installing aiflow with the right extra ([devel-all] I think )

* initializing the sqlite databases of airflow - both "normal" and "unit test" database

**Comment by joppevos** [comment]
you can assign me :)

**Comment by Bowrna** [comment]
@joppevos 

**Setting up environment for developing breeze:**

we set the environment for developing breeze by setting venv as `pip install -e dev/breeze/`  from airflow_home.
After that, you can simply add commands in breeze.py and verify it by running it

**Comment by joppevos** [comment]
> checking if Airflow is installed in "${HOME}/airflow" and warning and suggesting to move elsewhere if so (this is very bad because ${HOME}/airflow is by default where airflow stores all files (logs/config etc).
@potiuk What do you mean with installed here. As in, where the repository of Airflow is located? or the executable path to airflow? 

The venv with the airflow executable should not be placed in "${HOME}/airflow"
The repository in "${HOME}/airflow" is not good either, since it will self destruct itself when wiping out that location :)

**Comment by potiuk** [comment]
Good point. By  "Installed" I mean "checked out" really :)

The - unfortunate - problem with new contributors of irflow is that they often don't have often "separate folder for code" and check out the code in "$HOME" directly. And since default name of the repo is "airflow" this ends up with airflow source code in "${HOME}/airflow" more often than not,

That's unfortunate and something we can't change without breaking compatibility - airflow's default "HOME_DIR" when no AIRFLOW_HOME is not set is .... "${HOME}/airflow" :scream: . And when you run airlfow it will do all kinds of "writes" in this directory - logs, dags, sqlite database, airlfow config/settings files are all create there (and which files get created depend on some variables like UNIT_TEST_MODE :scream:  :scream: :scream_cat: . 

So really "${HOME}/airflow" might be both at the same time more often that not - the source code checked out from git as well as "writable storage" for running airflow. 

This is not a HUGE problem for casual users (we already protect agains accidential commits of files created in sources this way - via .gitignore - we ignore a number of files tha airflow might write there when running. But if you want to wipe that directory (which you might want to do to make sure there are no databases, configuration , you better make sure you are not wiping out checked out sources :).

**Comment by potiuk** [comment]
(BTW. Such wiping out of the source code actually happened for people in the past :D )

**Comment by joppevos** [comment]
> Good point. By "Installed" I mean "checked out" really :)
Thanks for clearing that up 👍

**Comment by joppevos** [comment]
@potiuk There is a bash function called `function breeze::setup_default_breeze_constants()`, which sets up all the variables and globals. Many of those globals are used when creating the virtualenv. `function breeze::initialize_virtualenv()`. That is the bash function that we are re-writing in this issue.

Should we also create a similar function in python? One who sets all these globals. Or should we approach this different in Python?

**Comment by potiuk** [comment]
> Should we also create a similar function in python? One who sets all these globals. Or should we approach this different in Python?

Most of those (if not all) are already set in Global Constants and/or read from parameters and passed via BuildParams, or ShellParams 

I think however, there is one thing here that we might correct though (now when I think of it).

`initialize-local-virtualenv` should not be "breeze" command :). This caused quite a confusion before - because this is really setting up "alternative" to breeze. It does not need most of those parameters that entering Breeze require (because it does not actually build or run docker image/container or docker compose)

Also there is a bit of a problem here, because "breeze" has in fact its own virtualenv now, so running it using the same venv as "breeze" willl be quite problematic, because you will need to ... setup another venv from within Breeze venv. This is a bit mind-boggling when you think of it.

I think the BEST approach is to simply have a separate python script to initialize local virtualenv that 

a) is executable python script in ./script/tools/initialize_virtualenv.py 
b) is completely independent from ./breeze and does not even use anythong from `./dev/breeze`
c) does not need any dependencies (neither click nor rich - they are not needed essentially)
d) checks if it is already run within a virtualenv (and if not - fails and asks the user to create and activate one)
d) figures out python version (3.7, 3.8 etc. ) automatically by checking which python version is used (this is a problem in the current version - it requires --python version to match the actual python version the local venv uses and cryptically fails sometimes if they are not matching).

I think really you need two things to run the "initialize-local-virtualenv" command:

* location of airflow sources
* python version

So you don't even need to pass anything as parameter as you can get those automatically. Simply the user should:

1) create a venv
2) activate it
3) run `./scripts/tools/initialize-local-virtualenv.py` 

That should be the "user story" here.

**Comment by Bowrna** [comment]
> (BTW. Such wiping out of the source code actually happened for people in the past :D )

I am one of the person who checked out the code in home directory, lost the code and reported it as issue :(

**Comment by potiuk** [comment]
> I am one of the person who checked out the code in home directory, lost the code and reported it as issue :(

Not the only one, I can assure you :)
