### ISSUE TITLE
Breeze: Exec'ing into running Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21104]
`./Breeze2 exec` should exec into the currently running Breeze (or fail with helpful message if Breeze is not running).

**Comment by Bowrna** [comment]
@potiuk Shall I pick up this task? :)

**Comment by potiuk** [comment]
Please :)

**Comment by Bowrna** [comment]
@potiuk `DOCKER_COMPOSE_RUN_SCRIPT_FOR_PROD` i see this variable is not set anywhere. Can you tell me about this?

https://github.com/apache/airflow/blob/95a1b71d762f0ee26284624cbe17c539e78265bd/breeze#L3480-L3485

**Comment by potiuk** [comment]
> @potiuk `DOCKER_COMPOSE_RUN_SCRIPT_FOR_PROD` i see this variable is not set anywhere. Can you tell me about this?
> 
> https://github.com/apache/airflow/blob/95a1b71d762f0ee26284624cbe17c539e78265bd/breeze#L3480-L3485

It's just an artifact of very old way when we could exec and run into prod image as well. This should be gone :)
