### ISSUE TITLE
Breeze: Add 'prepare-image-cache'  in Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21102]
We have a separate command that prepares image caches. It is very similar to "building image" but:
* it should prepare both prod and CI images
* the `docker build` command should be slighly modified (--cache-to and some other commands)
* validation on whether the `buildx plugin` needs to be performed (and command should fail if not with helpful message)

Those "differences" between standard build-image can be found with `PREPARE_BUILDX_CACHE` variable == "true" usage in old breeze

**Comment by Bowrna** [comment]
Can I pick up this task @potiuk?

Also, build-prod-image have `PREPARE_BUILDX_CACHE ` as part of its function. Does it come under `build-prod-image` or `prepare-image-cache`?

**Comment by Bowrna** [comment]
@potiuk is `prepare-build-cache` and `prepare-image-cache` means the same?  Also when we send `prepare-build-cache` we also set few other flags. Do we need to follow this and set those flags too?

https://github.com/apache/airflow/blob/4a1503b39b0aaf50940c29ac886c6eeda35a79ff/breeze#L1313-L1325

**Comment by Bowrna** [comment]
@potiuk I will resume working on this issue once PR #21956 got merged as it will be easier to add code to ci-image and refactor the reusable parts too.

**Comment by potiuk** [comment]
> 



> @potiuk is `prepare-build-cache` and `prepare-image-cache` means the same? 
Yes.
> Also when we send `prepare-build-cache` we also set few other flags. Do we need to follow this and set those flags too?
Some:
* "FORCE_BUILD_IMAGES" we already dropped it
* "FORCE_ANSWER_TO_QUESTIONS" is not needed (there will be no questions asked).
* "CLEANUP_DOCKER_CONTEXT_FILES" -> yes it should be overwritten to "yes" in this case
* "DOCKER_CACHE" -> yes.

**Comment by Bowrna** [comment]
> > 
> 
> > @potiuk is `prepare-build-cache` and `prepare-image-cache` means the same?
> > Yes.
> > Also when we send `prepare-build-cache` we also set few other flags. Do we need to follow this and set those flags too?
> > Some:
> 
> * "FORCE_BUILD_IMAGES" we already dropped it
> * "FORCE_ANSWER_TO_QUESTIONS" is not needed (there will be no questions asked).
> * "CLEANUP_DOCKER_CONTEXT_FILES" -> yes it should be overwritten to "yes" in this case
> * "DOCKER_CACHE" -> yes.

@potiuk It should apply for the build-prod-image case too. Am I right?

**Comment by potiuk** [comment]
Yes
