### ISSUE TITLE
Breeze: Build PROD image with Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21100]
Similarly to building CI image, we should build PROD image

**Comment by edithturn** [comment]
@potiuk could please point me to where we are building the CI image? To have an  idea how it was build :)
![Screenshot from 2022-01-31 10-47-25](https://user-images.githubusercontent.com/58795858/151825894-094b5263-a8af-4e2d-be0a-9f83eedfa451.png)

I also find that "build CI image" references this another ci_build_ci_image_on_ci.sh which is for the CI and exists for PROD too. ci_prepare_prod_image_on_ci.sh

https://github.com/apache/airflow/blob/906d710060ebfe893ef3d7cddf00d2c49c7998fa/.github/workflows/build-images.yml#L229-L230
```
      - name: "Build CI image ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG }}"
        run: ./scripts/ci/images/ci_build_ci_image_on_ci.sh
```

**Comment by edithturn** [comment]
name: "Build PROD image ${{matrix.python-version}}"

**Comment by potiuk** [comment]
You need to rebase to latest `main` @edithturn. I JUST merged today the change where those names were actually simplified and the scripts were separate. We used to have `prepare` that either did  `pull` or `build` depending on circumstances (and the logic there was complex because historically we had two ways of building.

I literally yesterday simplified all that and it should be much more straightforward: https://github.com/apache/airflow/pull/21219 

So:

* build is build
* pull is pull
* there is no "prepare" any more.

Also names of the CI jobs are synchronized ("Build" or "Pull" instead of ambiguous "Prepare").

**Comment by Bowrna** [comment]
@potiuk Could i pick this task next?

**Comment by potiuk** [comment]
Please :)
