### ISSUE TITLE
apache-airflow-providers-google

### ISSUE THREAD

**Issue by Arti3DPlayer** [apache/airflow#21109]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==6.3.0

### Apache Airflow version

2.2.3 (latest released)

### Operating System

Macos m1

### Deployment

Virtualenv installation

### What happened

```
get_dataset = BigQueryGetDatasetOperator(task_id="get-dataset", dataset_id="my_table")
```

Google libraries cause:

```
'/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)
```

Similar issue fixed: https://github.com/grpc/grpc/issues/25082
Need to update libraries

```
 from grpc._cython import cygrpc
ImportError: dlopen(/.venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/.venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-310-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)

```

### How to reproduce

Install `apache-airflow-providers-google==6.3.0` on Apple Silicon mac

### Anything else

Similar issue been fixed here:

https://github.com/grpc/grpc/issues/25082

Need to update google packages

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Apple sillicon M1 is not supported yet. But likely it will be soon (a month or so). this issue tracks it:  https://github.com/apache/airflow/issues/15635 

Closing as duplicate
