### ISSUE TITLE
can not delete dag

### ISSUE THREAD

**Issue by cjhnbls** [apache/airflow#21118]
### Apache Airflow version

2.2.3 (latest released)

### What happened

I  delete a dag via both airflow UI and REST api, but the dag is just temporarily deleted and appears again in next dag_dir_list_interval.
The database backend is postgresql-13, during the deletion, record corresponding  the dag in the table [tag] is deleted but then resumes.

### What you expected to happen

the dag python file removed
info about the dag disappears from airflow UI

### Operating System

NAME="Aliyun Linux" VERSION="2.1903 LTS (Hunting Beagle)" ID="alinux" ID_LIKE="rhel fedora centos" VERSION_ID="2.1903" PRETTY_NAME="Aliyun Linux 2.1903 LTS (Hunting Beagle)" ANSI_COLOR="0;31" HOME_URL="https://www.aliyun.com/"

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-spark==2.0.3
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Virtualenv installation

### Deployment details

run locally
airflow webserver
airflow scheduler

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
In Airflow DAGs are controlled by the DAGs folder not UI/API/CLI.

You should delete DAG from dags folder first in order to delete it from the UI. Deleting "DAG" from UI/CLI/API removes all DB records for a dag that has been deleted from DAG folder.

**Comment by achuriraghavendra** [comment]
I have deleted from DAGs folder and it is not showing in DAGs folder. Even it is showing successful when i deleted the dag from UI. But after some time it is appearing again. Not quite sure whether I am doing anything wrong.

**Comment by kwanyu-pf** [comment]
suffering from the same issue.

I've also deleted the dag from my folder, tried deleting by command, checked by airflow database (Postgresql), and nothing seems to be there, yet it appears again

**Comment by kwanyu-pf** [comment]
just got it deleted by removing the roles & Permissions for the specific dag
