### ISSUE TITLE
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag_run' expected to update 5 row(s); 0 were matched.

### ISSUE THREAD

**Issue by LIKEL123** [apache/airflow#21142]
### Apache Airflow version

2.2.2

### What happened

I have the same problem, and I don't know how to solve it. but my airflow-scheduler.err the errors reported in this log are:
"sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag_run' expected to update 5 row(s); 0 were matched.
", How should this problem be solved

### What you expected to happen

I have the same problem, and I don't know how to solve it. but my airflow-scheduler.err the errors reported in this log are:
"sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag_run' expected to update 5 row(s); 0 were matched.
", How should this problem be solved

### Operating System

I have the same problem, and I don't know how to solve it. but my airflow-scheduler.err the errors reported in this log are: "sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag_run' expected to update 5 row(s); 0 were matched. ", How should this problem be solved

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

I have the same problem, and I don't know how to solve it. but my airflow-scheduler.err the errors reported in this log are:
"sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag_run' expected to update 5 row(s); 0 were matched.
", How should this problem be solved

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is not an issue. Please describe your full configuraiton and open a separate discussion on it.
