### ISSUE TITLE
Add Trigger Rule Display to Graph View

### ISSUE THREAD

**Issue by ReadytoRocc** [apache/airflow#21201]
### Description

This feature would introduce some visual addition(s) (e.g. tooltip) to the Graph View to display the trigger rule between tasks. 

### Use case/motivation

This would add more detail to Graph View, providing more information visually about the relationships between upstream and downstream tasks.

### Related issues

https://github.com/apache/airflow/issues/19939

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I agree we can do it in a new graph view, but I don't think this would be too complicated to do for the current one either.
