### ISSUE TITLE
Issues reaching the Airflow UI. (Something bad has happened.)

### ISSUE THREAD

**Issue by soyedokun** [apache/airflow#21271]
### Apache Airflow version

2.0.2

### What happened

When I try to click on the Airflow UI link I get "Ooops! Something bad has happened"

### What you expected to happen

I expect to see the Airflow UI.

### How to reproduce

Just click on the Airflow UI link in AWS MWAA

### Operating System

AWS

### Versions of Apache Airflow Providers

Airflow version: 2.0.2

### Deployment

MWAA

### Anything else

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please contact MWAA for support. This is not an airflow issue.
