### ISSUE TITLE
Databricks Maintenance occasional wrong 403s causing retry failures - Please Discuss

### ISSUE THREAD

**Issue by andreaslang** [apache/airflow#21286]
### Apache Airflow Provider(s)

databricks

### Versions of Apache Airflow Providers

current master, but has been there since pre-2.0

### Apache Airflow version

2.2.3 (latest released)

### Operating System

ubuntu 18.04 LTS

### Deployment

MWAA

### What happened

I have databricks retry limit/delay configured to deal with the usual issues during a maintenance window, but was in for a surprise recently.

During a databricks maintenance a 403 was returned instead of the usual connection errors. Credentials/token was correct - databricks support explanation to follow below. This is not considered a recoverable error by the airflow provider - for good reason usually in my opinion, but it did cause the job to 'fail' from airflow perspective while still running. Retries did not work either because the job was already running so those where skipped. 

Databricks support says:
```
During our maintenance window, our central ACL database was being upgraded and hence it was down for 0-15 minutes.

When the central database is down, the existing connections to the database on the Auth service will hang and cannot be returned to the connection pool. Since new requests keep coming in, we have new connections in the pending state while all the connections of the connection pool are in the hung state, which causes Auth failures.

We are working towards handling this gracefully and achieving minimal downtime.
```

I am asking for a time frame of this work and will update once I receive it.

### What you expected to happen

Here is where I am not 100% sure, personally I think databricks should fix that urgently, but I have not been given a time frame and this can affect other databricks customers/users of the airflow provider, too.

Databricks support says: `Our team has advised that it would be best to include != 200 to deal with such scenarios.`. So they think provider behaviour should change.

Question is should this make its way into the provider code changing the following:

```python
def _retryable_error(exception) -> bool:
    return (
        isinstance(exception, (requests_exceptions.ConnectionError, requests_exceptions.Timeout))
        or exception.response is not None
        and exception.response.status_code >= 500
    )
```

Maybe with an operator parameter to enable. It all seems terrible to be honest. I am still considering if monkey-patching this on my side for the time being is actually the best solution.

### How to reproduce

Run a databricks run now operator with the following retry settings during the maintenance window when there is an ACL update
```
databricks_retry_limit=30
databricks_retry_delay=30
```

This should get you across the usual connection issues which are usually done after 10 min - this covers 15 min. Now if there is an ACL update and a 403 the retry fails (due to 403 not being retryable). It's all a bit bad from databricks side in the first place, but here we are.

### Anything else

So as said, this occurs rarely, but for us the impact can be quite big as it affects our delivery. Question is should there be a way to address this in the provider or should this be monkey patched until databricks sorts out their maintenance? If it should be in the provider I am happy to provide a PR. If not I will post my monkey patch solution (once implemented) here.

Also for context: 
1. We cannot move the time of these jobs
2. Databricks says they cannot let us configure/change the time of the maintenance window

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
assigned you @andreaslang

**Comment by andreaslang** [comment]
I did put a proposal PR up which ignores all errors when polling during maintenance windows. It does still require databricks_retry_limit/delay to be appropriately configured to get over the maintenance window as the existing retry mechanism is used.

**Comment by andreaslang** [comment]
I am actually closing this issue, since putting it up databricks has come back to me and given a much better timeline than expected to fix it (hopefully close to March 2nd).

Hence it should not be necessary anymore to work around the wrong return codes during maintenance.
