### ISSUE TITLE
Scheduled dag never runs

### ISSUE THREAD

**Issue by spiremak** [apache/airflow#21291]
### Apache Airflow version

2.2.3 (latest released)

### What happened

I have tried to schedule a dag to run every 5 mins. However at time 10:57am the dag looks like the below and I would have assumed the dag should have been triggered.
![image](https://user-images.githubusercontent.com/96873357/152330551-3b9dfa96-ecea-4f30-acc3-3854adebc884.png)

And then at 11:02 am I can see the the next run information has changed but the dag still hasn't run
![image](https://user-images.githubusercontent.com/96873357/152330780-ced4692b-dd6c-48e3-a9b8-d778a6240c12.png)

This is the code used to create the dag
```
with DAG("my_dag",start_date=datetime(2021, 1 ,1),schedule_interval= '*/5 * * * *',
         catchup = False) as dag:
    task1 = BashOperator(task_id = 'test', bash_command = 'echo "hello"')
 ```

### What you expected to happen

I expect the dag to run or at least log errors in the scheduler logs

### How to reproduce

Create a new dag with a scheduling interval which isn't none

### Operating System

Amazon Linux 2

### Deployment

Virtualenv installation

### Anything else

Using MySQL 8.0.23.
Local executor

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
@spiremak, it sounds silly, but it isn't in your screenshots... is the DAG paused?

**Comment by spiremak** [comment]
No the dag isn't paused. I wish it was that simple haha

**Comment by jedcunningham** [comment]
You should get a run immediately after unpausing, plus one every 5 minutes. I wasnt able to reproduce on main/postgres.

Can you try enabling [debug logging](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#logging-level) in your scheduler?

**Comment by spiremak** [comment]
I have created new dags today and this is what I see in the logs near time of creation 

```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'my_dag2' for key 'serialized_dag.PRIMARY'")
[parameters: ('my_dag2', '/home/ec2-user/airflow/dags/spiremak_test.py', 70986863378950560, '{"__version": 1, "dag": {"edge_info": {}, "timezone": "UTC", "_task_group": {"_group_id": null, "prefix_group_id": true, "tooltip": "", "ui_color": " ... (800 characters truncated) ... Operator", "_task_module": "airflow.operators.bash", "_is_dummy": false, "bash_command": "echo \\"hello\\""}], "dag_dependencies": [], "params": {}}}', datetime.datetime(2022, 2, 4, 9, 42, 40, 154149), '13e704f28bd83ca69cd2969c9aa6c173')]
```
and 
```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'my_dag3' for key 'dag.PRIMARY'")
[parameters: ('my_dag3', None, 0, 0, 1, datetime.datetime(2022, 2, 4, 9, 47, 41, 672474), None, None, None, None, '/home/ec2-user/airflow/dags/another_test.py', 'airflow', None, 'graph', '"*/5 * * * *"', 9, 350, 0, 0, datetime.datetime(2022, 2, 4, 9, 40), datetime.datetime(2022, 2, 4, 9, 40), datetime.datetime(2022, 2, 4, 9, 45), datetime.datetime(2022, 2, 4, 9, 45))]
```
However I don't see anything in the logs after every 5 mins which is when I expect the dag to run

**Comment by ephraimbuddy** [comment]
The log seems to suggest you have duplicate dag IDs. Check if you have duplicate DAG IDs and also do you have any environment variable set?

**Comment by spiremak** [comment]
I checked before creating the dags and after and don't think I could see any duplicate DAG IDs in the mysql db. And there arent any Airflow environment variables set

**Comment by spiremak** [comment]
okay it seems l had use_job_schedule = False.
Changing that to True has fixed it. 
Had anything changed between 2.1.4 to 2.2.3?
