### ISSUE TITLE
on_kill method for SparkKubernetesOperator

### ISSUE THREAD

**Issue by blcksrx** [apache/airflow#21325]
### Description

In some cases the Airflow sends `SIGTERM` to the task, here to the `SparkKubernetesOperator`, it needs to send `SIGTERM` also to the corresponding pods/jobs

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you !

**Comment by sam-som** [comment]
Hi @blcksrx 
Are you still planning to work on the fix for this?
I see that you have a closed PR - https://github.com/apache/airflow/pull/21327/files

**Comment by blcksrx** [comment]
Hey @sam-som, I mentioned that in the PR that I can not test it and I get 404 error from this Operator. could you please verify that also this operator does not work?
