### ISSUE TITLE
kubernetesPodOperatorAsync

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#21350]
### Description

The KPO is probably the most famous operator triggering compute out of airflow, I would like to know if someone is already working on the implementation of a kubernetesPodOperatorAsync

### Use case/motivation

Having a kubernetesPodOperatorAsync would be amazing and we could reduce the size and number of our airflow workers because each kubernetesPodOperator take a full worker slot.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I believe not - feel free to start one :)

**Comment by potiuk** [comment]
(unless I misuderstood that you would like to do so)

**Comment by subkanthi** [comment]
This will be good, happy to help.

**Comment by raphaelauv** [comment]
The astronomer provider release 1.0

Have  a kubernetesPodOperatorAsync

https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py#L16

**Comment by raphaelauv** [comment]
last missing feature for a  "production ready" KPOA

https://github.com/astronomer/astronomer-providers/issues/140
