### ISSUE TITLE
Rendered template fields in the REST API

### ISSUE THREAD

**Issue by gmcatsf** [apache/airflow#21447]
### Description

Make task instance rendered template fields available in the REST API.

### Use case/motivation

A task instance stores its rendered template fields in rendered_task_instance_fields table. We'd like to be able to retrieve the  information as json after a task instance is executed. This could be a new endpoint or a new field in the existing TaskInstanceSchema.

### Related issues

Did not find any existing issue.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to work on it

**Comment by ephraimbuddy** [comment]
I prefer adding it to the schema
