### ISSUE TITLE
HTML of Pipeline example in tutorial incomplete

### ISSUE THREAD

**Issue by KevinYanesG** [apache/airflow#21457]
### Describe the issue with documentation

**Apache Version**: 2.2.3

**OS**:macOS Catalina Version 10.15.7

**Apache Airflow Provider versions**:

**Deployment**:

**Web browser**: Google Chrome Version 98.0.4758.80 (Official Build) (x86_64)
Also happened with Safari Version 13.1.3 (15609.4.1)

**What happened**:

The [Pipeline example of the tutorial](https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html#pipeline-example) (in the website) looked like the following:
![image](https://user-images.githubusercontent.com/75472729/153197308-4a5e9cb8-2a56-49c2-8f06-32c97f861ca3.png)

I was wondering why there was so little information about the connection to  Postgres and why there were no `import` statements in the code. 

### How to solve the problem

Then, I realized that in the GitHub repo the [tutorial file](https://github.com/apache/airflow/blob/main/docs/apache-airflow/tutorial.rst) was way more extensive:
![image](https://user-images.githubusercontent.com/75472729/153198129-542888c8-c142-4fd0-905d-19ac98822aac.png)

I marked in red the parts of the tutorial that can't be seen on the website. There are probably more missing details.

Thanks in advance!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by KevinYanesG** [comment]
Also: 
I think that in the full version of the code the import should remain as `from airflow.providers.postgres.hooks.postgres import PostgresHook`.
 `from airflow.hooks.postgres import PostgresHook` gives me an `ImportError`

**Comment by ashb** [comment]
>  `from airflow.hooks.postgres import PostgresHook gives me an ImportError.`

You need to install the postgres provider -- that is also missing from that tutorial https://airflow.apache.org/docs/apache-airflow-providers-postgres/2.4.0/#installation

**Comment by KevinYanesG** [comment]
>You need to install the postgres provider -- that is also missing from that tutorial https://airflow.apache.org/docs/apache-airflow-providers-postgres/2.4.0/#installation
Thanks! But I actually already have the provider installed, since `from airflow.providers.postgres.hooks.postgres import PostgresHook` works for me without problems. 

I think `from airflow.hooks.postgres` is wrong because it doesn't exist, or at least I didn't found it.

The closest module is: `airflow.hooks.postgres_hook` (https://airflow.apache.org/docs/apache-airflow/1.10.6/_api/airflow/hooks/postgres_hook/index.html), from which you can import `PostgresHook`

**Comment by ashb** [comment]
Oh sorry, `airflow.providers.postgres.hooks.postgres`  is the new module path https://airflow.apache.org/docs/apache-airflow-providers-postgres/2.4.0/_api/airflow/providers/postgres/hooks/postgres/index.html

**Comment by potiuk** [comment]
Thanks for posting those. But I will cloe the ticket because the main reason why you see the difference is because you are looking at "stable" version of the docs released together with Airflow when the stable versio is released (which is 2.2.3 currently) 

So what is published in 2.2.3 version of the docs (which you can see at the top-left selection of the page) is this: https://github.com/apache/airflow/blob/2.2.3/docs/apache-airflow/tutorial.rst

The 'main` version of the docs is "development' version which might (or might not) be released with the new version. The changes you pointed at from `main` are actually cherry-picked to v2-2-test (which will become 2.2.4 soon - about a week - when we release it): https://github.com/apache/airflow/blob/v2-2-test/docs/apache-airflow/tutorial.rst

I actually looked through all documentation-only changes we had in `main` (development versions) and when they were just "improving" the documentation rather than adding new feature docs, i cherry-picked all such changes (and Jed - our release manager cherry-picked some before as well).   

> I just thought that from airflow.hooks.postgres is wrong because it doesn't exist, or at least I didn't found it.

This is indeed wrong. The easiest way to fix it is just go to the tutorial page and click "Suggest a change on this page" - it will open you the PR with the "main" version of the page and you will be able to easily create a PR (even more easily than creating this issue was. You can this way become one of the > 1900 contributors to Airlfow (because Airflow is created by the contributors like you. This would be a fantastic first contribution to correct it! 

> I don't know if this is the intended/optimal way to create the DB, but the DAG's run didn't fail. Maybe it would be easier for bloody beginners like me to include the part of creating the DB explicitly in the tutorial's code.

You should follow [Quick start](https://airflow.apache.org/docs/apache-airflow/stable/start/index.html) if you are bloody beginner. This is who it is intended for. And It explains what happens and what is going on includng the steps to initialize DB (`airflow db init` is the right command),

**Comment by ashb** [comment]
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/tutorial.html#pipeline-example for the rendering of the latest doc.

The import is still wrong in that example, so if you fancy a PR @KevinYanesG (no need for an issue, can just go to PR fixing it) we can guide you through it.

**Comment by potiuk** [comment]
> The import is still wrong in that example, so if you fancy a PR @KevinYanesG (no need for an issue, can just go to PR fixing it) we can guide you through it.

Absolutely.

**Comment by KevinYanesG** [comment]
>  But I will close the ticket because the main reason why you see the difference is because you are looking at "stable" version of the docs released together with Airflow when the stable version of Airflow is released (which is 2.2.3 currently)

Thanks for the extensive responses! I wasn't aware of that. In any case, it's good that you are going to include these details into the next version.

> This is indeed wrong. The easiest way for you to fix it is just go to the tutorial page and click "Suggest a change on this page" (bottomn-right of the page)

I will be happy to do that :)  I hope I can manage to do it before the end of the week.

> You should follow [Quick start](https://airflow.apache.org/docs/apache-airflow/stable/start/index.html) if you are bloody beginner. This is who it is intended for. And It explains what happens and what is going on includng the steps to initialize DB (airflow db init is the right command),

I actually followed the [Docker Quickstart](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html) and not the standalone one. Thus, I didn't saw the `db init` command. Although, I just had a look at it and it rather seems to be for initializing the postgres Backend, right? I was talking about how to explicitly create the `Employee` tables from the tutorial, which I did with the `cur.execute('''CREATE TABLE "Employees ...")`method. Is there another way to do it in a Docker environment?

**Comment by potiuk** [comment]
> I actually followed the [Docker Quickstart](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html) and not the standalone one. Thus, I didn't saw the `db init` command. Although, I just had a look at it and it rather seems to be for initializing the postgres Backend, right? I was talking about how to explicitly create the `Employee` tables from the tutorial, which I did with the `cur.execute('''CREATE TABLE "Employees ...")` method. Is there another way to do it in a Docker environment?

Actually there IS a better way! 

We have the command:

```
airflow db shell
```

That drops you into the DB command line environment that is configured. So you could - I think - even redirect a cration script to the command - that would be much nicer, because it could be done as a single command:

```
airflow db shell <<EOF

CREATE ....

EOF

**Comment by potiuk** [comment]
And in docker-compoe Quickstart you could likely combineit with https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#running-the-cli-commands

**Comment by KevinYanesG** [comment]
Thanks to you! 

I tried 
> airflow db shell <<EOF ...

But unfortunately, after trying many different things, I didn't bring it to work, probably because of little experience in Airflow / Postgres. 

A very brief summary of what I tried after deleting the `cur.execute()`code:
- `./airflow.sh airflow db reset`
- `./airflow.sh airflow db init`(just in case)
- `airflow db shell <<EOF ...`
- run the DAG
- Got the error
 ```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "Employees_temp_pkey"
 ERROR:  relation "Employees_temp" already exists
```
(I wonder why this error didn't appear when using the `cur.execute()`)
- Tried to solve it with https://stackoverflow.com/a/21639138, but when `pg_get_serial_sequence("Employees", "Serial Number")` there was no output, the [solution](https://stackoverflow.com/a/54766000) to this seems to go to deep into PostgresSQL for me to understand it in a reduced amount of time

(I also tried to run the sql commands directly in the shell but also didn't work)

**Comment by potiuk** [comment]
> ERROR:  relation "Employees_temp" already exists

Isn't that because you already created it before :)?

**Comment by potiuk** [comment]
just run (in reverse order from creation) at the beginning of the script


```
DROP TABLE EMPLOYEES_TEMP IF EXISTS CASCADE;
DROP TABLE EMPLOYEES IF EXISTS CASCADE;
```

https://www.geeksforgeeks.org/postgresql-drop-table/#:~:text=PostgreSQL%20has%20a%20DROP%20TABLE,table%20permanently%20from%20the%20database.

**Comment by KevinYanesG** [comment]
I actually already tried with `DROP TABLE <name>`, it didn't work either.

With
```bash
./airflow.sh airflow db shell <<EOF

DROP TABLE EMPLOYEES_TEMP IF EXISTS CASCADE;
DROP TABLE EMPLOYEES IF EXISTS CASCADE;
CREATE TABLE "Employees" 
(
    "Serial Number" NUMERIC PRIMARY KEY,
    "Company Name" TEXT,
    "Employee Markme" TEXT,
    "Description" TEXT,
    "Leave" INTEGER
);


CREATE TABLE "Employees_temp"
(
    "Serial Number" NUMERIC PRIMARY KEY,
    "Company Name" TEXT,
    "Employee Markme" TEXT,
    "Description" TEXT,
    "Leave" INTEGER
);

EOF
```

After running the DAG I still get 
```python
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "Employees_temp_pkey"
DETAIL:  Key ("Serial Number")=(2) already exists.
CONTEXT:  COPY Employees_temp, line 2

```

**Comment by potiuk** [comment]
(BTW. Of course I had no idea about it before I googled it).

**Comment by KevinYanesG** [comment]
Thanks that's a good hint, thanks! I will probably get to it in the beginning/middle of next week.
