### ISSUE TITLE
Allow to set statement behavior for PostgresOperator

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#21486]
### Body

Add the ability to pass parameters like `statement_timeout` from PostgresOperator.
https://www.postgresql.org/docs/14/runtime-config-client.html#GUC-STATEMENT-TIMEOUT

The goal is to allow to control over specific query rather than setting the parameters on the connection level.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Cool. I assume this is about the possibility of overriding it for individual statements? Because we already can add "extra options" in the `connection" and they will be passed to the "client.connect" ?

**Comment by potiuk** [comment]
Ah yeah. You wrote about :)

**Comment by victorphoenix3** [comment]
Hi, May I work on this issue?

**Comment by eladkal** [comment]
@victorphoenix3 sure! assigned to you
