### ISSUE TITLE
ExternalTaskSensor does not work after upgrade to airflow 1.3.0

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#215]
I have set an ExternalTaskSensor to depend on other dag.

However, it did not work after I upgrade airflow 1.3.0. The ExternalTaskSensor task status display queued after the other dag task executed.

Other question is do airflow have a release note for version update?

**Comment by mistercrunch** [comment]
My guess is the `queued` state is unrelated to the `ExternalTaskSensor` changes. You must be using pools, is there room in your pool?

I'll start including release notes, for the past you have to diff out tags. Each pypi release has had a clear tag and you can easily diff them. (https://github.com/airbnb/airflow/releases) This is more noisy than a typical maintainer curated release notes. I'll start including those in future releases.

**Comment by griffinqiu** [comment]
That is true, add pool, it work.

Thank you very much, close it
