### ISSUE TITLE
Add Go to docker images

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#21545]
### Description

Following https://github.com/apache/airflow/pull/20386 we are now supporting execution of Beam Pipeline written in Go.

We might want to add Go to the images.

Beam Go SDK first stable release is `v2.33.0` and requires `Go v1.16` minimum:

### Use case/motivation

This way people running airflow from docker can build/run their go pipelines.

### Related issues

Issue:
https://github.com/apache/airflow/issues/20283

PR:
https://github.com/apache/airflow/pull/20386

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
@potiuk as requested, here is the issue :)

**Comment by potiuk** [comment]
I will see how much go will add to the size of the image and decide :)

**Comment by potiuk** [comment]
The worst case we can add instructions in our "extending image" chapter.

**Comment by mik-laj** [comment]
I think we should add the guide to the "Recipes" section in `docker-stack` documentation package. https://airflow.apache.org/docs/docker-stack/recipes.html

We already have a guide on how to install additional tools:
* Google Cloud SDK, which is needed for GKEPodOperator, DataflowStartSqlJobOperator, and others.
* JRE, which is needed for DataflowCreateJavaJobOperator, and many others.

**Comment by pierrejeambrun** [comment]
Hello @potiuk,

I would be glad to give a hand on this one for the go recipe.

Let me know if you want me to work on it :)

Best,

**Comment by potiuk** [comment]
Feel free.
