### ISSUE TITLE
Breeze: Allow to switch between Debian Bullseye and Buster when building images.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21547]
Following the #21546 - we should also add a switch in the new Breeze to be able to switch between `buster` and `bullseye` base Python images.

We will likely have to support both in the coming 6 months so being able to switch between them will be necessary.

**Comment by Bowrna** [comment]
@potiuk I made some relevant changes in [this](https://github.com/apache/airflow/pull/21145) PR wrt debian version. What would be the default value for the Debian version? 

https://github.com/Bowrna/airflow/blob/7c631962df9cea24f3d0dff3aa636e0f2db2212f/dev/breeze/src/airflow_breeze/ci/build_params.py#L60

**Comment by potiuk** [comment]
> @potiuk I made some relevant changes in [this](https://github.com/apache/airflow/pull/21145) PR wrt debian version. What would be the default value for the Debian version?

Bullseye. I am just about to merge #21378

**Comment by Bowrna** [comment]
i will test by making it default to Bullseye and update here

**Comment by potiuk** [comment]
merged bullseye :)

**Comment by potiuk** [comment]
This one shoud be fine :)

**Comment by potiuk** [comment]
BTW. There are some small changes coming soon as well (pretty cool in terms of optimizations) - you will have to do some modifications there too, but this should be easy.

**Comment by Bowrna** [comment]
> BTW. There are some small changes coming soon as well (pretty cool in terms of optimizations) - you will have to do some modifications there too, but this should be easy.

Sure looking forward to it
