### ISSUE TITLE
typing_extensions package isn't installed with apache-airflow-providers-amazon causing an issue for SqlToS3Operator

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#21566]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

3.0.0rc2

### Apache Airflow version

2.2.3 (latest released)

### Python version

Python 3.9.7 (default, Oct 12 2021, 02:43:43)

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### What happened

I was working on adding this operator to a DAG and it failed to import due to a lack of a required file

### How to reproduce

Add 

```

from airflow.providers.amazon.aws.transfers.sql_to_s3 import SqlToS3Operator
```

to a dag

### Anything else

This can be resolved by adding `typing-extensions==4.1.1` to `requirements.txt` when building the project (locally)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by frankcash** [comment]
It looks like as of Python 3.8 this functionality can be achieved by  changing the import to 

```
from typing import Literal
```

instead of 

```
from typing_extensions import Literal
```

but utilizing `typing_extensions` wouldn't break backwards compatibility it would just require  a change here https://github.com/apache/airflow/blob/0a6ea572fb5340a904e9cefaa656ac0127b15216/setup.cfg#L140

**Comment by frankcash** [comment]
Also looks like the SQS Sensor suffers from a similar issue https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/sensors/sqs.py#L24

**Comment by josh-fell** [comment]
FYI - There is [typing_compat](https://github.com/apache/airflow/blob/main/airflow/typing_compat.py) that could be used for the `Literal` type import.

**Comment by josh-fell** [comment]
Might be worth putting in some sort of CI check for these compat-related imports too. @potiuk WDYT?

**Comment by potiuk** [comment]
Ah yeah. Absolutely :)
