### ISSUE TITLE
replace `hql` references to `sql` in `TrinoHook` and `PrestoHook`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#21597]
### Body

Both:
https://github.com/apache/airflow/blob/main/airflow/providers/presto/hooks/presto.py
https://github.com/apache/airflow/blob/main/airflow/providers/trino/hooks/trino.py

uses terminology of `hql` we should change it to `sql`.
The change needs to be backwards compatible. e.g deprecating hql with warning 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by kazanzhy** [comment]
I'm working on a few other PRs but could take this issue if nobody else will take it.

**Comment by utkarsharma2** [comment]
Hey @eladkal,  simply replacing `hql` with `sql` won't break backward compatibility. Can you explain bit more about the backward compatibility?
