### ISSUE TITLE
ArgoCD deployment: Cannot synchronize after updating values

### ISSUE THREAD

**Issue by druizz90** [apache/airflow#21615]
### Official Helm Chart version

1.4.0 (latest released)

### Apache Airflow version

2.2.3 (latest released)

### Kubernetes Version

v1.20.12-gke.1500

### Helm Chart configuration

defaultAirflowTag: "2.2.3-python3.9"
airflowVersion: "2.2.3"

createUserJob:
  useHelmHooks: false
migrateDatabaseJob:
  useHelmHooks: false

images:
  migrationsWaitTimeout: 300

executor: "KubernetesExecutor"

### What happened

I was able to configure the synchronization properly when I added the application to _ArgoCD_ the first time, but after updating an environment value, it is set properly (the scheduler is restarted and works fine), but _ArgoCD_ cannot synchronize the jobs (_airflow-run-airflow-migrations_ and _airflow-create-user_), so it shows that the application is not synchronized.

Since I deploy _Airflow_ with _ArgoCD_ and I disable the _Helm's_ hooks, these jobs are not deleted when finished and remain as completed.

The workaround I am doing is to delete these jobs manually, but I have to repeat this after an update.

Should the attribute `ttlSecondsAfterFinished: 0` be included below this line when the _Helm's_ hooks are disabled in the jobs templates?

https://github.com/apache/airflow/blob/af2c047320c5f0742f466943c171ec761d275bab/chart/templates/jobs/migrate-database-job.yaml#L48

https://github.com/apache/airflow/blob/af2c047320c5f0742f466943c171ec761d275bab/chart/templates/jobs/migrate-database-job.yaml#L48

PD: I created a custom chart in order to synchronize my value's files with _ArgoCD_, and this chart only includes a dependency with the _Airflow's_ chart and my values files (I use one by environment), and  the _Helm_ configuration I put in the section _Helm Chart configuration_ is under a _airflow_ block in my value's files.

This is my _Chart.yaml_:

```yaml
apiVersion: v2
name: my-airflow
version: 1.0.0
description: Airflow Chart with my values
appVersion: "2.2.3"
dependencies:
  - name: airflow
    version: 1.4.0
    repository: https://airflow.apache.org
```

### What you expected to happen

I expect that _ArgoCD_ synchronizes after changing an environment variable in my values file.

### How to reproduce

- Deploy the chart as an _ArgoCD_ application.
- Change an environment variable in the values file.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to take a stab on it.

**Comment by druizz90** [comment]
I found a solution, I am testing in my environment. I'll do the pull request in the next days.

**Comment by druizz90** [comment]
It is possible to add annotations for solving this issue (https://github.com/apache/airflow/pull/21776#issuecomment-1049935021).
