### ISSUE TITLE
Jenkins Connection Example

### ISSUE THREAD

**Issue by nicolamarangoni** [apache/airflow#21647]
### Describe the issue with documentation

I need to configure a connection to our jenkins and I dont find anywhere an example.
I suppose that I need to define a http connection with the format:
`http://usename:password@jenkins_url`
However don't have any idea about adding `/api` so that the url would be:
`http://usename:password@jenkins_url/api`

### How to solve the problem

Is it possible to include at least a jenkins connection example in the documentation?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
You are welcome to submit a PR for this

**Comment by eladkal** [comment]
@SasanAhmadi maybe you can help with creating example in the docs?

**Comment by SasanAhmadi** [comment]
> @SasanAhmadi maybe you can help with creating example in the docs?

sure, I can help with this.
just to confirm, is [this](https://github.com/apache/airflow/tree/main/docs/apache-airflow-providers-jenkins) the place to update doc for jenkins?

**Comment by eladkal** [comment]
> sure, I can help with this. just to confirm, is [this](https://github.com/apache/airflow/tree/main/docs/apache-airflow-providers-jenkins) the place to update doc for jenkins?

I require to create a doc like:
https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-dbt-cloud/connections.rst
https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-ftp/connections/ftp.rst

and reference it from the relevant hook:
https://github.com/apache/airflow/blob/c58b5e583bcad83048fdee72bc9ddf6c3a7b4229/airflow/providers/dbt/cloud/hooks/dbt.py#L135
