### ISSUE TITLE
SFTP Sensor - Allow Use of Modified Time

### ISSUE THREAD

**Issue by AdamPaslawski** [apache/airflow#21655]
### Description

The SFTP sensor uses the existence of a modified time to determine if a file exists in an SFTP location.

I would like to propose extending the sensor to allow for a `newer_than`  option, since we already get the modified time in the current implementation of `poke()` this would be a relatively simple but useful extension.

### Use case/motivation

I want to be able to use this sensor and ensure it succeeds if a file exists and is "fresh" enough.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/22377
