### ISSUE TITLE
Using AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD inserts \n at end of connection string

### ISSUE THREAD

**Issue by SystemOfaDrow** [apache/airflow#21657]
### Apache Airflow version

2.2.3 (latest released)

### What happened

We use credstash to set/retrieve passwords. While trying to upgrade from Airflow v2.2.1 to v2.2.3, we started getting failures connection to the meta-database and ended up tracking the issue down to an additional new line character being inserted at the end of the connection string.

### What you expected to happen

There shouldn't be a new line inserted at the end of the connection string when using a command.

### How to reproduce

```
airflow@airflow-webserver:~$ credstash put example_airflow_conn_string postgresql+psycopg2://airflow:password@airflow-db:5432/airflow
example_airflow_conn_string has been stored
airflow@airflow-webserver:~$ credstash get example_airflow_conn_string
postgresql+psycopg2://airflow:password@airflow-db:5432/airflow
airflow@airflow-webserver:~$ export AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD='credstash get example_airflow_conn_string'
airflow@airflow-webserver:~$ python
Python 3.9.10 (main, Jan 29 2022, 05:27:31)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from airflow.configuration import conf
>>> conf.get('core', 'sql_alchemy_conn')
'postgresql+psycopg2://airflow:password@airflow-db:5432/airflow\n'
```

### Operating System

Debian Bullseye 11.2

### Deployment

Docker-Compose

### Anything else

The version of credstash we're using is v1.17.1 and hasn't changed since it was working, so the issue isn't with its return value.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
A new line is added by credstash. Please look at:
https://github.com/fugue/credstash/blob/df24f9189e843e0cdc700c015ee4f37fbd35dc40/credstash.py#L542-L543
