### ISSUE TITLE
[AWS] Configurable AWS SessionFactory for AwsBaseHook 

### ISSUE THREAD

**Issue by alexchen8** [apache/airflow#21672]
### Description

Add custom federated AWS access support through configurable [SessionFactory](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/hooks/base_aws.py#L424),

User will have the option to use their own `SessionFactory` implementation that can provide AWS credentials through external process.

### Use case/motivation

Some company uses custom [federated AWS access](https://aws.amazon.com/identity/federation/) to AWS services. It corresponds to [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) in AWS configuration option.

While the hook currently support AWS profile option, I think it would be great if we can add this support on the hook directly, without involving any AWS configuration files on worker nodes.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
feel free to submit PR
