### ISSUE TITLE
Remove all usages of days_ago from test suite

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#21683]
### Body

`days_ago` is deprecated https://github.com/apache/airflow/pull/21653

We have several references to the function in test suite / example dags.

Task:
there should be no imports of `airflow.utils.dates import days_ago` in the code.
In most cases we can simple replace with `datetime(2022, 1, 1)`

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by hubert-pietron** [comment]
Hi, can i take it?

**Comment by eladkal** [comment]
@hubert-pietron sure, assigned to you.

**Comment by Dev232001** [comment]
Hi, can you assign this to me?

**Comment by potiuk** [comment]
Just check with @hubert-pietron - if it's not something already started.

**Comment by hubert-pietron** [comment]
Let me know @Dev232001 how you want to split, or you can take whole and i will look for another issue to work on :)

**Comment by Dev232001** [comment]
Hi @hubert-pietron , thanks for letting me join this issue here. I am relatively new to open source contributions and was looking for a beginner level task. This looked like an easy problem so I asked for this. If you can just give me an update on what you have done till now that will be the best. I think I will be able to work on the rest of the issue from thereon :)

**Comment by eladkal** [comment]
it can be in example dags or in tests.
You can find all references by searching `airflow.utils.dates import days_ago` in the code base.

**Comment by Dev232001** [comment]
Okay. Appreciate the help. Thanks

**Comment by hubert-pietron** [comment]
I just looked how many occurrences there is in code, so You can take it all :)

**Comment by Dev232001** [comment]
I have completed the given task and created a pull request for the same. Kindly review it. 
Besides this, there are quite a few syntax related errors in tests folder like in 
from fake_datetime import FakeDatetime - test_impersonation_custom.py - dags_corrupted - tests

tests - decorators - test_python_virtualenv.py - errors found

tests - operators - test_python.py - import funcsigs - error

**Comment by Dev232001** [comment]
This is my first contribution and its asking for a approval review 
https://github.com/apache/airflow/pull/21796

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/23237
and duplicated of https://github.com/apache/airflow/issues/23233
I don't know why I opened two issues for this :/
