### ISSUE TITLE
Airflow tasks marked as failed without retry with KubernetesExecutor

### ISSUE THREAD

**Issue by nicor88** [apache/airflow#21701]
### Apache Airflow version

2.2.3 (latest released)

### What happened

We use Kubernetes Executor in combinations with AWS spot instances. Time to time spot instances are evicted, therefore the tasks/pods running on it fail. All our tasks are having a retry >=1, which generally works fine, but in this case, the tasks running in the evicted K8s node, are marked immediately as failed.

### What you expected to happen

I expected that the scheduler considers the retry, and trigger another instance of the task without marking it immediately as failed. 

### How to reproduce

Kill a running pod when is running, to obtain the same error described in this issue.

### Operating System

Official Docker Airflow image 2.2.3

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-slack==4.1.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Can you upload the scheduler logs when this happens
