### ISSUE TITLE
Unable to pass parameters which aren’t strings while triggering external data in airflow 2.1.4

### ISSUE THREAD

**Issue by Syar123** [apache/airflow#21714]
### Description

in airflow 1: we used to pass parameters like below to external dag trigger
def trigger_gcs_to_bq_dag(context, dag_run_obj) :
dag_run_obj.payload = {
'gcs_bucket" : context['ti' ].xcom_pull (key='gcs_bucket'
, task_ids='parse_params' ), "gcs_objects_list"
context['ti'].xcom_pull(key='gcs_objects_list'
task_ids='parse_params')
, task_ids='filter_gcs_files'),"bq_schema"
:context['ti'].xcom_pull(key='bq_schema
}
return dag_run_obi
trigger_gcs_to _ba_dag = TriggerDagRunoperator(
task_id='trigger_gcs_to_bq_dag'
trigger_dag_id="gcs_to_bg"
python_callable=trigger_gcs_to_bq_dag
)
in airflow 2.1.4 as python_callable is deprecated we need to pass parameters through conf

trigger_gcs_to_bq_dag = TriggerDagRunOperator (
task_id='trigger_gcs_to_bq_dag'
trigger_dag_id="gcs_to_bq"
conf= {"gcs_bucket":
"{{ti.xcom_pull(key='gcs_bucket', task_ids='parse_params') }}", "gcs_objects_list":
“{{ti.xcom_pull(key='gcs_objects_list', task_ids='parse_params') }}",
"bq_schema":
"{{ xcom_pull (key=' bq_schema',
task_ids='parse_params') }}" },
)
when passing through conf the parameter values are going as strings instead of their own values (None is passing as 'None')
in the external dag we are using logic like
if params['bq-schema' ] is not None:
schema_fields=[
{
"name' : f[0],
'type': f[11
} for f in params['bq_schema']]

and other values which arent strings.

how can we eradicate this issue in airflow 2.1.4 when the previous modules are deprecated?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by allebacco** [comment]
Thanks for opening the issue. The code in the description is not well formatted and it is hard to understand. Could you please improve its formatting using the [Markdown code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)?

**Comment by Syar123** [comment]
def trigger_gcs_to_bq_dag(context, dag_run_obj):        
        dag_run_obj.payload = {
            "gcs_bucket" : context['ti'].xcom_pull(key='gcs_bucket', task_ids='parse_params'),"gcs_objects_list" : context['ti'].xcom_pull(key='gcs_objects_list', task_ids='filter_gcs_files'),"bq_auto_detect_schema" : context['ti'].xcom_pull(key='bq_auto_detect_schema', task_ids='parse_params'),"bq_schema" : context['ti'].xcom_pull(key='bq_schema', task_ids='parse_params')
        }
        return dag_run_obj


    trigger_gcs_to_bq_dag = TriggerDagRunOperator(
        task_id='trigger_gcs_to_bq_dag',
        trigger_dag_id="gcs_to_bq",  
        python_callable=trigger_gcs_to_bq_dag, 
        retries=1
        )        


in airflow 2.1.4 as python_callable is deprecated we needed  to pass parameters through 'conf' under TriggerDagRunOperator instead of  dag_run_obj.payload

trigger_gcs_to_bq_dag = TriggerDagRunOperator(
        task_id='trigger_gcs_to_bq_dag',
        trigger_dag_id="gcs_to_bq",  
        conf={"gcs_bucket" : "{{ ti.xcom_pull(key='gcs_bucket', task_ids='parse_params') }}","gcs_objects_list" : "{{ ti.xcom_pull(key='gcs_objects_list', task_ids='filter_gcs_files') }}","bq_auto_detect_schema" : "{{ ti.xcom_pull(key='bq_auto_detect_schema', task_ids='parse_params') }}","bq_schema" : "{{ xcom_pull(key='bq_schema', task_ids='parse_params') }}" },
        retries=1
    )

when passing through conf the parameter values are going as strings instead of their own values (None is passing as 'None')

in the external dag ( gcs_to_bq) we are using logic like

 def parse_params(ti, **context):
            if context['dag_run'].conf:
                params['gcs_bucket'] = context['dag_run'].conf.get('gcs_bucket', None)
                params['gcs_objects_list'] = context['dag_run'].conf.get('gcs_objects_list', None)
                params['bq_auto_detect_schema'] = context['dag_run'].conf.get('bq_auto_detect_schema', None)
                params['bq_schema'] = context['dag_run'].conf.get('bq_schema', None)
            else: # fail without retry
                raise AirflowFailException("config missing. please trigger the dag with proper config")

            
            # set defaults:
            if (params['bq_auto_detect_schema'] is None and params['bq_schema'] is None):
                params['bq_auto_detect_schema'] = True 
            
            if params['bq_schema'] is not None:
                schema_fields=[
                    {
                        'name':f[0],
                        'type':f[1]
                    } for f in params['bq_schema']]



in our external dag (gcs_to_bq) [ as parsing parameters are strings we are having issues while reading values like None, integers (0,1) and boolean values (true)]
