### ISSUE TITLE
Add ability to pin Airflow Variable(s)/Connection(s) in the UI

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#21720]
### Description

I'd like to see functionality in the UI to allow pinning some Airflow Variables/Connections at the top of the list.

### Use case/motivation

In our deployment we have a couple of Airflow Variables, and Connections that are central to our operations. We typically have to use filter search in order to reach these Connection/Variable, since we maintain a long list.
It would be nice to have the ability to pin these few important artifacts to the top of the Variable/Connection list in the UI, such that they are readily accessible.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pateash** [comment]
This looks interesting, let me look into this.

**Comment by bbovenzi** [comment]
assigning you, @pateash

**Comment by msumit** [comment]
IMO having a Recent of DAGs/Connections/Variables etc is another good way to solve this. In general, I find it common that we don't un-favorite things & they just keep on adding up, like the number of bookmarks in our browsers.

**Comment by bbovenzi** [comment]
Maybe just added a updatedAt column and default the sort to the most recently changed?

**Comment by eladkal** [comment]
Most recently changed doesn't necessarily mean most important one but sorting capabilities in general is a good thing to have.
