### ISSUE TITLE
Unable to pass parameters which aren’t strings while triggering external data in airflow 2.1.4

### ISSUE THREAD

**Issue by Syar123** [apache/airflow#21765]
### Apache Airflow version

2.1.4

### What happened

in airflow 1: we used to pass parameters like below to external dag trigger through dag_run_obj.payload
```
def trigger_gcs_to_bq_dag(context, dag_run_obj):        
        dag_run_obj.payload = {
            "gcs_bucket" : context['ti'].xcom_pull(key='gcs_bucket', task_ids='parse_params'),"gcs_objects_list" : context['ti'].xcom_pull(key='gcs_objects_list', task_ids='filter_gcs_files'),"bq_auto_detect_schema" : context['ti'].xcom_pull(key='bq_auto_detect_schema', task_ids='parse_params'),"bq_schema" : context['ti'].xcom_pull(key='bq_schema', task_ids='parse_params')
        }
        return dag_run_obj


    trigger_gcs_to_bq_dag = TriggerDagRunOperator(
        task_id='trigger_gcs_to_bq_dag',
        trigger_dag_id="gcs_to_bq",  
        python_callable=trigger_gcs_to_bq_dag, 
        retries=1
        )        
```

in airflow 2.1.4 as python_callable is deprecated in TriggerDagRunOperator we needed  to pass parameters through 'conf' under TriggerDagRunOperator instead of  dag_run_obj.payload
```
trigger_gcs_to_bq_dag = TriggerDagRunOperator(
        task_id='trigger_gcs_to_bq_dag',
        trigger_dag_id="gcs_to_bq",  
        conf={"gcs_bucket" : "{{ ti.xcom_pull(key='gcs_bucket', task_ids='parse_params') }}","gcs_objects_list" : "{{ ti.xcom_pull(key='gcs_objects_list', task_ids='filter_gcs_files') }}","bq_auto_detect_schema" : "{{ ti.xcom_pull(key='bq_auto_detect_schema', task_ids='parse_params') }}","bq_schema" : "{{ xcom_pull(key='bq_schema', task_ids='parse_params') }}" },
        retries=1
    )
```
when passing through conf the parameter values are going as strings instead of their own values (None is passing as 'None')

in the external dag ( gcs_to_bq) we are using logic like
```
 def parse_params(ti, **context):
            if context['dag_run'].conf:
                params['gcs_bucket'] = context['dag_run'].conf.get('gcs_bucket', None)
                params['gcs_objects_list'] = context['dag_run'].conf.get('gcs_objects_list', None)
                params['bq_auto_detect_schema'] = context['dag_run'].conf.get('bq_auto_detect_schema', None)
                params['bq_schema'] = context['dag_run'].conf.get('bq_schema', None)
            else: # fail without retry
                raise AirflowFailException("config missing. please trigger the dag with proper config")

            
            # set defaults:
            if (params['bq_auto_detect_schema'] is None and params['bq_schema'] is None):
                params['bq_auto_detect_schema'] = True 
            
            if params['bq_schema'] is not None:
                schema_fields=[
                    {
                        'name':f[0],
                        'type':f[1]
                    } for f in params['bq_schema']]
```

in our external dag (gcs_to_bq) [ as parsing parameters are strings we are having issues while reading values like None, integers (0,1) and boolean values (true)]

### What you expected to happen

I would like to pass parameters which aren't strings from source Dag to target Dag and read them as is

### Operating System

macOS Big Sur

### Versions of Apache Airflow Providers

v2

### Deployment

Composer

### Deployment details

I am using Google Composer 2.0.1 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
Starting with Airflow 2.1, there was a new parameter introduced called `render_template_as_native_obj` which will render templated values as native Python types rather than strings or stringified versions of native types. You can check out more info in the [Operator concepts documentation](https://airflow.apache.org/docs/apache-airflow/stable/concepts/operators.html#rendering-fields-as-native-python-objects).

Let's take the below DAGs as an example.
```python
from pendulum import datetime
from typing import Dict

from airflow.decorators import dag, task
from airflow.models import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator

# DAG performing the triggering of another.
@dag(
    dag_id="parent_dag",
    start_date=datetime(2021, 1, 1),
    schedule_interval=None,
    render_template_as_native_obj=True
)
def parent_dag():
    @task
    def xcom_push() -> Dict:
        return {
            "gcs_bucket": "my_bucket",
            "gcs_objects_list": [1, 2, 3],
            "bq_auto_detect_schema": True,
            "bq_schema": None,
        }

    t = xcom_push()

    trigger_child_dag = TriggerDagRunOperator(
        task_id="trigger_child_dag",
        trigger_dag_id="child_dag",
        conf={
            "gcs_bucket": "{{ ti.xcom_pull(key='gcs_bucket', task_ids='xcom_push') }}",
            "gcs_objects_list": "{{ ti.xcom_pull(key='gcs_objects_list', task_ids='xcom_push') }}",
            "bq_auto_detect_schema": "{{ ti.xcom_pull(key='bq_auto_detect_schema', task_ids='xcom_push') }}",
            "bq_schema": "{{ ti.xcom_pull(key='bq_schema', task_ids='xcom_push') }}",
        },
        retries=1,
    )

    t >> trigger_child_dag


_parent_dag = parent_dag()

# DAG to be triggered.
@dag(
    start_date=datetime(2021, 1, 1),
    schedule_interval=None,
)
def child_dag():
    @task
    def get_trigger_conf(dag_run=None):
        from pprint import pprint

        pprint(dag_run.conf)

    t = get_trigger_conf()


_child_dag = child_dag()
```

When the `child_dag` is triggered, the output printed from the "get_trigger_conf" task is:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/48934154/155456720-5a4bb9f0-c672-4529-82dd-2a9393318d17.png">

Notice that the values for `gcs_bucket`, `gcs_objects_list`, `bq_auto_detect_schema`, and `bq_schema` are native Python types rather than the stringified versions that you are running into now.

Can you try setting `render_template_as_native_obj=True` on the triggering DAG and see if this helps? I ran the above example on 2.1.4 and using the `main` branch with the same result so hopefully this works for you as well.

**Comment by Syar123** [comment]
@josh-fell  thanks a lot, it worked.
