### ISSUE TITLE
Add default 'aws_conn_id' to SageMaker Operators

### ISSUE THREAD

**Issue by ferruzzi** [apache/airflow#21808]
The SageMaker Operators not having a default value for `aws_conn_id` is a pain, we should fix that.  See EKS operators for an example: https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/eks.py

_Originally posted by @ferruzzi in https://github.com/apache/airflow/pull/21673#discussion_r813414043_

**Comment by eladkal** [comment]
@hsrocks would you like to work on the followup task?

**Comment by hsrocks** [comment]
> @hsrocks would you like to work on the followup task?

Thanks @eladkal  please assign it to me. Will do

**Comment by potiuk** [comment]
Assigned!

**Comment by ferruzzi** [comment]
Hey, cool.  Thanks for taking it on.

**Comment by hsrocks** [comment]
Hello @ferruzzi :)

 I reviewed the code for changes and as per me these changes will not be needed.

As part of Sagemaker Base : https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/sagemaker.py#L51

the connection id is assigned a default value . Let me know if anything needs to be improvise. Thanks!!

**Comment by ferruzzi** [comment]
The problem is that the individual operators also declare the aws_conn without a default value so it isn't optional, and it won't fall back to that value:

```
In [1]: class Foo():
   ...:     def __init__(self, myvar=5):
   ...:         self.myvar = myvar
   ...: 
   ...:     def op(self):
   ...:         return self.myvar
   ...: 
   ...: class Bar(Foo):
   ...:     def __init__(self, myvar):
   ...:         super().__init__(myvar=myvar)
   ...: 

In [2]: Foo().op()
Out[2]: 5

In [3]: Foo(3).op()
Out[3]: 3

In [4]: Bar(2).op()
Out[4]: 2

In [5]: Bar().op()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-06b11a1ebf4e> in <module>
----> 1 Bar().op()

TypeError: __init__() missing 1 required positional argument: 'myvar'
```

So if we move the defaulting into the child Operators, we don't have to declare `aws_conn_id='default_aws'` in every operator use:

```
In [1]: class Foo:
   ...:     def __init__(self):
   ...:         pass
   ...: 
   ...:     def op(self):
   ...:         return self.myvar
   ...: 
   ...: 
   ...: class Bar(Foo):
   ...:     def __init__(self, myvar=5):
   ...:         self.myvar = myvar
   ...:         super().__init__()
   ...: 

In [2]: Bar(2).op()
Out[2]: 2

In [3]: Bar().op()
Out[3]: 5
```

**Comment by hsrocks** [comment]
Got the intent . Yes can see this problem with few of them individually . Appreciate the details :) Will work this out.!!
