### ISSUE TITLE
Display TaskGroup types in Graph view legends

### ISSUE THREAD

**Issue by ghost** [apache/airflow#21870]
### Description

In addition to the Operator types that are displayed in Airflow's graph's legend, show TaskGroup types, as well.

### Use case/motivation

I create and utilize reusable TaskGroups. For instance, I have a multi-task TaskGroup that creates external stages, migrates a table, and copies data from the external stage into the table. It's completely reusable, and we use this task group across different DAGs with simple configuration changes.

When I open up the graph view in Airflow, though, only the underlying operators of the task group are displayed in the Operator legend in the upper left-hand corner of the graph view. This can be confusing, because sometimes the fully-collapsed view of the DAG only shows task groups and no operators - so you end up looking at a graph that has no relationship to the legend until you expand one of the task groups (and the Operators become visible).

It might be nice to support either (or both of):

1. Displaying the custom TaskGroup's name alongside the rest of the legend.
2. Only displaying a legend for what is currently visible in the graph view. e.g. If the fully-collapsed version of the DAG is only task groups, then only the TaskGroup names are in the legend, but when you expand a task group, the Operator names for the newly-visible operators are also displayed in the legend.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We've changed the graph view quite a lot since this was opened. TaskGroups now have a lot more visual separation from regular tasks
