### ISSUE TITLE
hive provider support for python 3.9

### ISSUE THREAD

**Issue by Aakcht** [apache/airflow#21891]
### Apache Airflow Provider(s)

apache-hive

### Apache Airflow version

2.2.4 (latest released)

### Operating System

Debian “buster”

### Deployment

Official Apache Airflow Helm Chart

### What happened

Hive provider can not be used in python 3.9 airflow image without also manually installing `PyHive`, `sasl`, `thrift-sasl` python libraries.

### What you expected to happen

Hive provider can be used in python 3.9 airflow image after installing only hive provider.

### Anything else

Looks like for python 3.9 hive provider support was removed in https://github.com/apache/airflow/pull/15515#issuecomment-860264240 , because `sasl` library did not support python 3.9. However now python 3.9 is supported in `sasl`: https://github.com/cloudera/python-sasl/issues/21#issuecomment-865914647 . 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
ah cool. Thanks for the info @Aakcht - I am about to prepare new providers. So let me try this one out

**Comment by potiuk** [comment]
I think this is not as easy, unfortunately @Aakcht . 

In order to add Python 3.9, this one should be implemented:  https://github.com/dropbox/PyHive/issues/380 
PyHive uses `thrift-sasl` library which is different than the python-sasl library.

**Comment by potiuk** [comment]
Ah I am wrong! 

Originally it was about switching to thrift-sasl, but indeed now sasl 0.3.1 is released and this versio nis already downloaded in other python versions, so we shoudl be perfectly fine.

**Comment by sergei3000** [comment]
Hi does all this mean Hive provider will work for Python 3.10 as well?

**Comment by Aakcht** [comment]
I didn't personally test it, but I don't see any issues related to hive provider and python 3.10 so I suspect it should work fine (since the latest airflow versions support python 3.10).
