### ISSUE TITLE
Metrics documentation incorrectly lists dag_processing.processor_timeouts as a gauge

### ISSUE THREAD

**Issue by yeachan153** [apache/airflow#21897]
### Describe the issue with documentation

According to the [documentation](https://airflow.apache.org/docs/apache-airflow/2.2.4/logging-monitoring/metrics.html), `dag_processing.processor_timeouts` is a gauge.

However, checking the code, it appears to be a counter: https://github.com/apache/airflow/blob/3035d3ab1629d56f3c1084283bed5a9c43258e90/airflow/dag_processing/manager.py#L1004

### How to solve the problem

Move the metric to the counter section.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you @yeachan153

**Comment by ashutoshcipher** [comment]
Hi @potiuk - If you @yeachan153 is not working on it, Can I pick this up?

**Comment by potiuk** [comment]
Take it :)

**Comment by yeachan153** [comment]
Sorry for the delay, @ashutoshcipher I checked whether you had already made a PR but I couldn't so I just made a PR.

**Comment by ashutoshcipher** [comment]
Thanks  @yeachan153
