### ISSUE TITLE
Best approach for periodic, but not uniform schedule interval?

### ISSUE THREAD

**Issue by seibert** [apache/airflow#219]
I have a DAG I want to run at 10:30am and 3:30pm every day, but I'm not sure what the best way to specify this is in Airflow.  I can't just set the schedule interval on a single DAG, because the interval between jobs is not uniform (alternates between 5 and 19 hours).

Is there an easy way to make a DAG for the 10:30 case, and then duplicate it with a different name and change the start time to 3:30pm?

**Comment by mistercrunch** [comment]
I'd use a 12 hours `schedule_interval` anchored on a 00:00 start_date and derive the `TimeSensor` with your specific logic. Something like: 

```
class CustomTimeSensor(TimeSensor):
    def poke(self, context):
        # pseudocode
        # if the time of context['exectution_date'] is 00:00 and current_time >= 10:30am
        #     return True
        # elif the time of context['exectution_date'] is 12:00 and current_time >= 3:30pm
        #     return True
        # else 
        #     return False
```

Then your processes downstream can just depend on this and should trigger at 10:30 for the morning run and 3:30 for the afternoon one.
