### ISSUE TITLE
Elasticsearch hook support DSL

### ISSUE THREAD

**Issue by alexxi0213** [apache/airflow#21929]
### Description

Current elasticsearch provider hook does not support query with DSL. Can we implement some methods that support user input json to get query results? 
BTW, why current `ElasticsearchHook's` father class is `DbApiHook`? I thought DbApiHook is for relational database that supports `sqlalchemy`?

### Use case/motivation

I think the elasticsearch provider hook should be like `MongoHook` that inherit from `BaseHook` and provide more useful methods works out of the box.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
> BTW, why current ElasticsearchHook's father class is DbApiHook? I thought DbApiHook is for relational database that supports sqlalchemy?

https://github.com/apache/airflow/blob/602abe8394fafe7de54df7e73af56de848cdf617/airflow/providers/elasticsearch/hooks/elasticsearch.py#L29

[elasticsearch-dbapi](https://github.com/preset-io/elasticsearch-dbapi) is a SQLAlchemy driver for Elasticsearch.

**Comment by alexxi0213** [comment]
> > BTW, why current ElasticsearchHook's father class is DbApiHook? I thought DbApiHook is for relational database that supports sqlalchemy?
> 
> https://github.com/apache/airflow/blob/602abe8394fafe7de54df7e73af56de848cdf617/airflow/providers/elasticsearch/hooks/elasticsearch.py#L29
> 
> [elasticsearch-dbapi](https://github.com/preset-io/elasticsearch-dbapi) is a SQLAlchemy driver for Elasticsearch.

Oh, I see, but I think most use cases for `elasticsearch` is using the DSL (json format) for filter or keyword search. I would have to implement a custom hook to do that in my use case, also some useful method to manipulate indexes. I would like to contribute that, do you think it's needed?

**Comment by potiuk** [comment]
Feel free to add support for that.
