### ISSUE TITLE
Programmatic customization of run_id for scheduled DagRuns

### ISSUE THREAD

**Issue by KevinJiao** [apache/airflow#21923]
### Description

Allow DAG authors to control how `run_id`'s are generated for created DagRuns. Currently the only way to specify a DagRun's `run_id` is through the manual trigger workflow either through the CLI or API and passing in `run_id`. It would be great if DAG authors are able to write a custom logic to generate `run_id`'s from scheduled `DagRunInterval`'s.

### Use case/motivation

In Airflow 1.x, the semantics of `execution_date` were burdensome enough for users that DAG authors would subclass DAG to override `create_dagrun` so that when new DagRuns were created, they were created with `run_id`'s that provided context into semantics about the DagRun. For example, 
```
def create_dagrun(self, **kwargs):
  kwargs['run_id'] = kwargs['execution_date'] + self.following_schedule(kwargs['execution_date']).date()
  return super().create_dagrun(kwargs)
```
would result in the UI DagRun dropdown to display the weekday of when the Dag actually ran.
<img width="528" alt="image001" src="https://user-images.githubusercontent.com/9851473/156280393-e261d7fa-dfe0-41db-9887-941510f4070f.png">

After upgrading to Airflow 2.0 and with Dag serialization in the scheduler overridden methods are no longer there in the SerializedDAG, so we are back to having `scheduled__<execution_date>` values in the UI dropdown. It would be great if some functionality could be exposed either through the DAG or just in the UI to display meaningful values in the DagRun dropdown.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hterik** [comment]
Agree that navigating the UI based on dagrun-id is very confusing today. But i don't think generating custom `run_id` is necessarily the solution. 

It would be better if the UI could format the id and even augment more data from the dagrun into a more meaningful description, for example reading parameters from the `conf` or reading output produced by selected `xcom` parameters. For most of our use cases the execution date itself means nothing, it is mostly the input provided via parameters that are used to identify a run.

**Comment by uranusjr** [comment]
One possible solution would be to allow a DAG argument `run_id_format` for Airflow to use instead, and the user can set this to whatever they want (within some limitations of course). Maybe a Python `.format()` syntax or Jinja2.

**Comment by potiuk** [comment]
I like this one. Likely we would like to also be able to add it on "cluster policy" level. I imagine a company would lilke to make a global change to format all the dagruns in the same way.

**Comment by dukarc** [comment]
+1 on this.  Has anyone found a temporary solution for Airflow 2.0?

**Comment by valayDave** [comment]
+1 on this. Are there any plans of supporting this in the near future ?

**Comment by potiuk** [comment]
> +1 on this. Are there any plans of supporting this in the near future ?

As usual with such 'small-ish" features, if someone will do it, it will be done. This is an open-source. Anyone (including yourself) can make a PR and add it. Seems like there is a general consensus on that one and no objections, so anyone contributing the PR can be pretty sure the reception will be good. 

So if you feel like it - feel free to make PR.

**Comment by ashb** [comment]
I'm looking at making this a thing that the timetable controls.

(That does mean running timetable code in the scheduler "hot loop" so needs some careful thought)
