### ISSUE TITLE
Sagemaker Transform Job fails if there are job with Same name

### ISSUE THREAD

**Issue by hsrocks** [apache/airflow#21941]
### Description

Sagemaker Transform Job fails if there are job with Same name exist. Let say I create a job name as 'transform-2021-01-01T00-30-00'  . So if I clear the airflow task run id for this so that the operator re-triggers then the Sagemaker Job creation fails because job with same name exists. So can we add  'action_if_job_exists flag where Behaviour if the job name already exists. Possible options are "increment" (default) and "fail".'

### Use case/motivation

Now in production environment failures are inevitable and with Sagemaker Jobs we have to ensure there is unique name for each run of the Job. So like the Sagemaker Processing Job operator or training operator we have an option to increment a job name by appending the count like if I run same job twice the job name will be 'transform-2021-01-01T00-30-00-1' where 1 is appended at end with the help of 'action_if_job_exists ([str](https://docs.python.org/3/library/stdtypes.html#str)) -- Behaviour if the job name already exists. Possible options are "increment" (default) and "fail".'

I have faced this issue personally on one of the task I am working on and think will save time and cost instead of running entire workflow again to get unique job names if there are other dependent task in the job by just clearing failed task id post fixing the failure in Sagemaker code , docker image input etc and that will just continue from where it failed

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned uou @hsrocks

**Comment by schirag1993** [comment]
Hey @potiuk and @hsrocks,

Would it make sense to add a random suffix to the end of the Transform job name vs. incrementing a number to it as a suffix? 

Since the suffix would be irrelevant to the actual run of the job and serves only to avoid name collisions, a random suffix would make the code a lot simpler and serve the same purpose.

Thoughts?

**Comment by potiuk** [comment]
Random is fine.

**Comment by schirag1993** [comment]
Awesome. Had a word with @hsrocks, I'll be working on this one!

**Comment by celeriev** [comment]
Hello ! I think this feature could indeed be very useful ! We are facing the issue currently with my team. I can help if needed @hsrocks

**Comment by potiuk** [comment]
I added you - not sure if @schirag1993 had done much on it - but if you still want @schirag1993  - chime in.

**Comment by schirag1993** [comment]
Hey y'all, I hadn't started work. Please feel free to get on it!
