### ISSUE TITLE
Azure data factory hook doesn't support pipelines which are saved in a directory

### ISSUE THREAD

**Issue by tsaaii** [apache/airflow#21949]
### Apache Airflow version

2.2.4 (latest released)

### What happened

I am trying to implement the functionality specified in this [PR ](https://github.com/apache/airflow/pull/17885) here 

From the code, to run a pipeline on ADF, you do this

```
    run_pipeline1 = AzureDataFactoryRunPipelineOperator(
        task_id="run_pipeline1",
        pipeline_name="pipeline1",
        parameters={"myParam": "value"},
    )
```

This doesn't work if your pipeline is in a folder, something like
```
    run_pipeline1 = AzureDataFactoryRunPipelineOperator(
        task_id="run_pipeline1",
        pipeline_name="folder_name/pipeline1",
        parameters={"myParam": "value"},
    )
```

DAG fails with following error

```
msrest.exceptions.ValidationError: Parameter 'pipeline_name' must conform to the following pattern: '^[A-Za-z0-9_][^<>*#.%&:\\\\+?/]*$'.
```

### What you expected to happen

There should be a way to specify directory and sub directory names when using AzureDataFactoryRunPipelineOperator.

### Operating System

windows

### Versions of Apache Airflow Providers

3.6.0

### Deployment

Other Docker-based deployment

### Deployment details

Docker+Helm chart with custom values.yaml

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
You should be able to trigger with just the name of the pipeline alone regardless if the pipeline is in a folder structure. This is an API limitation from what the error message says and in the [documentation](https://docs.microsoft.com/en-us/rest/api/datafactory/pipelines/create-run). The operator and hook do not perform any transformations of the name but simply passes the args through to the API call.

IIRC the pipeline name is also unique within a resource group/factory and the folders are purely for visual organization. I don't believe you can create different pipelines in the same factory even when one is contained a folder.

Have you tried triggering the pipeline with just the name?

**Comment by tsaaii** [comment]
you are right about the second part. You can create only one pipeline with a certain name in a data factory irrespective of folders they are in. I will trigger pipeline with just the name to see what happens.

**Comment by tsaaii** [comment]
This works as expected. Thank you. I will close this now.
