### ISSUE TITLE
"deadlock detected" error in dag table updates

### ISSUE THREAD

**Issue by imbaczek** [apache/airflow#21947]
### Apache Airflow version

2.0.2

### What happened

```
2022-02-26 15:42:51 UTC [104192]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 STATEMENT: UPDATE dag SET next_dagrun='2022-02-26T15:32:50.428672+00:00'::timestamptz, next_dagrun_create_after='2022-02-26T15:42:50.428672+00:00'::timestamptz WHERE dag.dag_id = 'redacted_1'
2022-02-26 15:43:07 UTC [130186]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 ERROR: deadlock detected
2022-02-26 15:43:07 UTC [130186]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 DETAIL: Process 130186 waits for ShareLock on transaction 1728784371; blocked by process 130573.
Process 130573 waits for ShareLock on transaction 1728784356; blocked by process 130186.
Process 130186: UPDATE dag SET next_dagrun='2022-02-26T15:42:47.604016+00:00'::timestamptz, next_dagrun_create_after='2022-02-26T15:52:47.604016+00:00'::timestamptz WHERE dag.dag_id = 'redacted_1'
Process 130573: UPDATE dag SET last_parsed_time='2022-02-26T15:43:03.633626+00:00'::timestamptz, next_dagrun='2022-02-26T15:40:03.633649+00:00'::timestamptz WHERE dag.dag_id = 'redacted_2'
2022-02-26 15:43:07 UTC [130186]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 HINT: See server log for query details.
2022-02-26 15:43:07 UTC [130186]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 CONTEXT: while updating tuple (4,2) in relation "dag"
2022-02-26 15:43:07 UTC [130186]: user=prod_airflow,db=prod_airflow,app=[unknown],client=10.80.166.208 STATEMENT: UPDATE dag SET next_dagrun='2022-02-26T15:42:47.604016+00:00'::timestamptz, next_dagrun_create_after='2022-02-26T15:52:47.604016+00:00'::timestamptz WHERE dag.dag_id = 'redacted_1'
```

Likely places which conflict in the code:
https://github.com/apache/airflow/blob/d7265791187fb2117dfd090cdb7cce3f8c20866c/airflow/models/dag.py#L2436
https://github.com/apache/airflow/blob/d7265791187fb2117dfd090cdb7cce3f8c20866c/airflow/models/dag.py#L2919

### How to reproduce

We have 830 dags and this number keeps growing due to business requirements. No special steps to reproduce are required, it just happens every now and then, as would be expected. Increase fillfactor, perhaps?

### Operating System

VERSION="20.04.3 LTS (Focal Fossa)"

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==1.0.1
apache-airflow-providers-ftp==1.0.1
apache-airflow-providers-http==1.1.0
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-sqlite==1.0.1

### Deployment

Other Docker-based deployment

### Deployment details

```
$ docker --version
Docker version 19.03.5, build 633a0ea838
```

Postgres: psql (11.5 (Ubuntu 11.5-1.pgdg16.04+1))

### Anything else

Multiple times a day.

Took remediation steps to reduce amount of rows on page:

```
prod_airflow=# alter table dag set (fillfactor = 10);
ALTER TABLE
prod_airflow=# vacuum full dag;
VACUUM
```

which reduced frequency to ~1/day.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
I have seen this error with multi-scheduler setup. How many schedulers are you using?

**Comment by imbaczek** [comment]
Just one active scheduler at a time.

**Comment by ephraimbuddy** [comment]
Deadlocks are fine except if they caused the scheduler to stop. From the log above, this happens in your database and does not stop your scheduler. Looks similar to this fix https://github.com/apache/airflow/pull/19842

**Comment by potiuk** [comment]
Yep. duplicagte of #19842

**Comment by farvour** [comment]
Also seeing this in the same table with a massive number of DAGs (3k+). We are running multi-scheduler. Will #19842 resolve this? We're on `2.3.3` at this time.

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
DETAIL:  Process 25726 waits for ShareLock on transaction 374820848; blocked by process 26495.
Process 26495 waits for ShareLock on transaction 374820791; blocked by process 25726.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (7,13) in relation "dag"

[SQL: UPDATE dag SET next_dagrun=%(next_dagrun)s, next_dagrun_data_interval_start=%(next_dagrun_data_interval_start)s, next_dagrun_data_interval_end=%(next_dagrun_data_interval_end)s, next_dagrun_create_after=%(next_dagrun_create_after)s WHERE dag.dag_id = %(dag_dag_id)s]
[parameters: {'next_dagrun': DateTime(2022, 11, 16, 1, 48, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_start': DateTime(2022, 11, 16, 1, 48, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_end': DateTime(2022, 11, 16, 1, 50, 0, tzinfo=Timezone('UTC')), 'next_dagrun_create_after': DateTime(2022, 11, 16, 1, 50, 0, tzinfo=Timezone('UTC')), 'dag_dag_id': '<redacted>'}]
```
