### ISSUE TITLE
Add support for Apache Zeppelin

### ISSUE THREAD

**Issue by EricGao888** [apache/airflow#21953]
### Description

Add support for [Apache Zeppelin](https://zeppelin.apache.org/) in airflow.providers.apache package.

### Use case/motivation

- [Apache Zeppelin](https://zeppelin.apache.org/) is a 
web-based notebook that enables data-driven,
interactive data analytics and collaborative documents with SQL, Scala, Python, R and more.
- Our team are using customized zeppelin operator, enabling data engineers to use airflow to schedule zeppelin notes directly after they finish developing big data jobs like spark, hive, flink, etc. in zeppelin notes. This feature will greatly boost big-data development efficiency.
- We'd like to contribute this zeppelin-provider package to community.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by EricGao888** [comment]
Currently I'm working on this feature and will submit an initial pr later this day. I'll appreciate it if this issue could be assigned to me. THX : )

**Comment by h7kanna** [comment]
Hi, Is this being worked upon actively?

**Comment by EricGao888** [comment]
> Hi, Is this being worked upon actively?



> Hi, Is this being worked upon actively?

@h7kanna Hello, I've been quite busy recently. I will handle this as soon as I have time. Currently, the problem is we haven't completed the unit tests but the feature is ok to use as you can access the code in this pr: #21954

**Comment by h7kanna** [comment]
Hi Thanks, I will try this branch then.

**Comment by EricGao888** [comment]
> Hi Thanks, I will try this branch then.

Sure. If you have any questions about zeppelin operator, you are welcome to reach out to me. : )

**Comment by eladkal** [comment]
Hi @EricGao888 do you intend to complete the PR?

**Comment by EricGao888** [comment]
> Hi @EricGao888 do you intend to complete the PR?

Sorry to reply late. Currently Apache Zeppelin hasn't released pyzeppelin yet. In my previous PR for airflow zeppelin operator , I put pyzeppelin code inside and this might not be a good practice. Once Apache Zeppelin releases pyzeppelin, I will reopen #21954, remove the pyzeppelin related code and complete it. 

![image](https://user-images.githubusercontent.com/34905992/212232521-c68749ea-83dc-41d0-a09d-886b607d85bc.png)

**Comment by potiuk** [comment]
Closing it for now then.
