### ISSUE TITLE
helm chart - mounting-dags-from-a-private-github-repo-using-git-sync-sidecar

### ISSUE THREAD

**Issue by schudoku** [apache/airflow#21970]
### Describe the issue with documentation

doc link: https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#mounting-dags-from-a-private-github-repo-using-git-sync-sidecar
doc location:
"""
  [...]
    repo: ssh://git@github.com/<username>/<private-repo-name>.git
  [...]
"""
I literally spent one working day making the helm deployment work with the git sync feature.
I prefixed my ssh git repo url with "ssh://" as written in the doc. This resulted in the git-sync container being stuck in a CrashLoopBackOff.

### How to solve the problem

Only when I removed the prefix it worked correctly.

### Anything else

chart version: 1.4.0
git-sync image tag: v3.1.6 (default v3.3.0)

Maybe the reason for the issue is the change of the image tag. However I want to share my experience. Maybe the doc is misleading. For me it was.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Could you please submit a fix for that?

**Comment by potiuk** [comment]
It's as easy as clicking a "suggest a change on this page" and creating a PR. Airlfow is created by almost 2000 contributors and you can become one of them this way.
