### ISSUE TITLE
Add Metadata Upload Support to GCSHook Upload Method

### ISSUE THREAD

**Issue by patricker** [apache/airflow#21978]
### Description

When uploading a file using the GCSHook Upload method, allow for optional metadata to be uploaded with the file. This metadata would then be visible on the blob properties in GCS.

### Use case/motivation

Being able to associate metadata with a GCS blob is very useful for tracking information about the data stored in the GCS blob.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it.
