### ISSUE TITLE
Airflow S3 connection name

### ISSUE THREAD

**Issue by treyyi** [apache/airflow#21987]
### Description

Hi,

I took a look some issues and PRs and noticed that `Elastic MapReduce` connection name has been changed to `Amazon Elastic MapReduce` lately. [#20746](https://github.com/apache/airflow/issues/20746)

I think it would be much intuitive if the connection name `S3` is changed to `Amazon S3`, and would look better on connection list in web UI. (also, it is the official name of s3)

Finally, AWS connections would be the followings:
```
Amazon Web Services
Amazon Redshift
Amazon Elastic MapReduce
Amazon S3
```

Would you mind to assign me for PR and change it to `Amazon S3`?
It would be a great start for my Airflow contribution journey.

Thank you!

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Sure. Feel free.

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/21988
