### ISSUE TITLE
Does not appear dags in mwaa

### ISSUE THREAD

**Issue by dgamorimm** [apache/airflow#21995]
### Apache Airflow version

2.0.2

### What happened

Simply the Dags stopped being executed and soon after disappeared in MWAA. The aws is very devoid of logs and there they do not point out any kind of error.

### What you expected to happen

May the dags continue to run perfectly

### How to reproduce

Put your dags in the s3 bucket, configure the MWAA environment and wait for the Dag to appear on the web server to run it

### Operating System

Linux

### Versions of Apache Airflow Providers

2.0.2

### Deployment

MWAA

### Deployment details

Virginia
Public Network
Nothing Additional Setting
S3 in Virginia

### Anything else

No

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please report your issue to MWAA
