### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by brettatoms** [apache/airflow#22]
What are the supported Python versions? Are there plans to support Python 3?

**Comment by mistercrunch** [comment]
`2.7.*` for now, we'll support 3 when our dependencies do, there are many important ones that don't at the moment

**Comment by mistercrunch** [comment]
Added a note in the docs:
https://github.com/airbnb/airflow/commit/62ad66ebb17c6be946635cc459542130be545ce8

**Comment by brettatoms** [comment]
For reference it looks like the main blockers are `thrift` and `snakebite`.

**Comment by mistercrunch** [comment]
https://caniusepython3.com/project/airflow
```
dill (which is blocking airflow)
flask-admin (which is blocking airflow)
flask-bootstrap (which is blocking airflow)
flask-login (which is blocking airflow)
hive-thrift-py (which is blocking airflow)
librabbitmq (which is blocking airflow)
mysql-python (which is blocking airflow)
protobuf (which is blocking snakebite, which is blocking airflow)
pyhive (which is blocking airflow)
pysmbclient (which is blocking airflow)
sphinx-argparse (which is blocking airflow)
sphinx-pypi-upload (which is blocking airflow)
thrift (which is blocking airflow)
```

**Comment by brettatoms** [comment]
Yeah, that is painful but FWIW I think this list might be a little misleading since some of those packages support Python 3 but they just don't have their supported versions defined in their setup.py.
