### ISSUE TITLE
Global variable not being accessed in pipline

### ISSUE THREAD

**Issue by ahmad-musleh** [apache/airflow#220]
I have code where the output of one task is required in order to be used in another task. Direct access from one task and another doesn't seem possible. Hence I have defined a global variable in the pipeline in order to store the output the task. However the global variable doesn't seem to change. Is there another way to provide one task with the output of another? Could you provide me with an simple example pipeline that does so?  Or with a way that a global variable could be edited by more than one task at different times ?

**Comment by mistercrunch** [comment]
There's currently no easy way to do this in Airflow. If you are using two PythonOperator you may want to use the Variable model as a key value store.
http://pythonhosted.org/airflow/concepts.html#variables

**Comment by ahmad-musleh** [comment]
Is there a way to define the key-value in a Python Operator? (Other than creating one from the webserver interface). Could you provide an example of doing such a task?

Thanks in advance

**Comment by jlowin** [comment]
Try this:

``` python
import airflow

# create the local variable
var = airflow.models.Variable(key='key', val='val')

# get the database session
session = airflow.settings.Session()

# add the variable
session.add(var)
session.commit()

# [you should see it in the web interface now]

# retrieve it
airflow.models.Variable.get('key')

# delete it
session.delete(var)
session.commit()
```

**Comment by ahmad-musleh** [comment]
Interesting. I have tested it and it works. But is it the case where I can only pass strings? ie I can't pass any structures (lists, dicts, etc.)?

**Comment by jlowin** [comment]
I think you'll want to store it as json (`json.dumps(your_obj)`) and retrieve (I believe) with `Variable.get('key', deser_json=True)` or calling `json.loads(...)` after retrieval

**Comment by ahmad-musleh** [comment]
Alright it worked by doing json.loads(...) (including deser_json=True raised an error) 

Thank you

**Comment by mistercrunch** [comment]
We're building something more flexible and integrated, follow it here:
https://github.com/airbnb/airflow/pull/232

**Comment by AnweshaSen** [comment]
Hi all, I want to have a dynamic list with value from a previously executed step on every time run, upon that list I will be iterating and generating dynamic steps. 
I have tried with setting an airflow variable but it does not seem to work, since it's taking the initial value as [] and generating a broken structure. 
Any suggestion, how to do that ?
