### ISSUE TITLE
Add Variable, Connection "description" fields available in the API

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#22007]
### Description

I'd like to get the "description" field from the variable, and connection table available through the REST API for the calls:

1. /variables/{key}
2. /connections/{conn_id}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nitinmahawadiwar** [comment]
Hello @SangwanP,
I checked the description field for variables API, seems like missing, but for connections api, its working properly (for both scenarios, all connections & a specific connection)

Can I request you to confirm the version you are using ? I tried with 2.4

**Comment by nitinmahawadiwar** [comment]
Please assign this ticket to me.

**Comment by potiuk** [comment]
> Please assign this ticket to me.

Done!

**Comment by potiuk** [comment]
It follows releases. API is connected with Airlfow releases. Tje main is development and any changes there are coming in 2.3.0. Should we close that one?

**Comment by nitinmahawadiwar** [comment]
Hello @potiuk @eladkal , I am able to return the description field from get api, also found the places to update documentation (verifying locally) but somehow not able to understand the Test cases & its structure.
Do you have any reference material to go through on test cases 
I am referring https://github.com/apache/airflow/blob/main/TESTING.rst &
updated  test cases in a) tests/models/test_variable.py & b) tests/api_connexion/endpoints/test_variable_endpoint.py 

Thanks

**Comment by potiuk** [comment]
I am afraid not, but if you have some specific questions/ comments - @ephraimbuddy and @mik-laj  might be able to help.

**Comment by ephraimbuddy** [comment]
> Hello @potiuk @eladkal , I am able to return the description field from get variable api, also found the places to update documentation (/api_connexion/openapi/v1.yaml - verifying locally) but somehow not able to understand the Test cases & its structure. Do you have any document to go through for test case implementation. I am referring https://github.com/apache/airflow/blob/main/TESTING.rst & updated test cases in a) tests/models/test_variable.py & b) tests/api_connexion/endpoints/test_variable_endpoint.py
> 
> Thanks

You can make the PR, we will guide you on the tests

**Comment by nitinmahawadiwar** [comment]
> > Hello @potiuk @eladkal , I am able to return the description field from get variable api, also found the places to update documentation (/api_connexion/openapi/v1.yaml - verifying locally) but somehow not able to understand the Test cases & its structure. Do you have any document to go through for test case implementation. I am referring https://github.com/apache/airflow/blob/main/TESTING.rst & updated test cases in a) tests/models/test_variable.py & b) tests/api_connexion/endpoints/test_variable_endpoint.py
> > Thanks
> 
> You can make the PR, we will guide you on the tests

Sure @ephraimbuddy Thanks
