### ISSUE TITLE
Google cloud dataproc: Add an operator to run a serverless spark in dataproc

### ISSUE THREAD

**Issue by ajayganti3** [apache/airflow#22019]
### Description

Recently GCP has launched serverless spark on dataproc. It will be really great if Airflow has an operator to submit a serverless spark job. Please refer to the [dataproc serverless documentation](https://cloud.google.com/dataproc-serverless/docs/overview) and its [gloud sdk documentation](https://cloud.google.com/sdk/gcloud/reference/dataproc/batches)

### Use case/motivation

Using this serverless dataproc we can run spark jobs easily without managing any infrastructure, autoscaling and work loads.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aoelvp94** [comment]
DId you see this PR https://github.com/apache/airflow/pull/19248?
