### ISSUE TITLE
Bottom scrollbar not working in the DAGs page.

### ISSUE THREAD

**Issue by NirmalSharmaRaj** [apache/airflow#22036]
### Apache Airflow version

2.2.2

### What happened

On the home page, when the window size is reduced, a bottom scrollbar appears. But this scrollbar is unclickable, so I am not able to side-scroll using it. The page navigation buttons seems to be overlapping it.
![image](https://user-images.githubusercontent.com/95294875/156979836-52fa6c30-474b-43ff-ac0e-d9fe1b8d9e0f.png)

### What you expected to happen

I expected bottom scrollbar to be moved using click and hold with mouse, to scroll the page.

### How to reproduce

Reduce the size of the browser window for the bottom scrollbar to appear. Then try to click and hold on the scrollbar.

### Operating System

Ubuntu 20 LTS

### Deployment

Virtualenv installation

### Anything else

Browsers used: Chrome, Edge, Firefox

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@NirmalSharmaRaj I'm not able to reproduce this behavior on 2.2.2 with both side-scrolling via trackpad nor click and drag of the scrollbar. https://www.loom.com/share/63bda5a341d54238b7995a9c61943063

@bbovenzi Are you able to reproduce and/or is there other information that would be helpful to know if this is a bug? We can always convert to a Discussion too.

**Comment by bbovenzi** [comment]
I've checked a few browsers and OSes. This issie no longer exists.

<img width="485" alt="Screen Shot 2022-07-05 at 1 09 09 PM" src="https://user-images.githubusercontent.com/4600967/177380588-bbe55a18-e0dd-40b1-b4e6-1bb5db9ad2b1.png">
