### ISSUE TITLE
Add "aborted" as a state option for DAG Runs

### ISSUE THREAD

**Issue by itay-raveh** [apache/airflow#22040]
### Description

Currently, `DAG Runs` have two "done" states: "succeeded" or "failed". I propose a third, **"aborted"**.

### Use case/motivation

Currently if I wish to stop a `DAG Run`, I must mark it one of the states listed above, and usually choose "failed" for lack of a better option. This means that later I have no easy way to differentiate between runs that actually failed, due to some exception, and runs that I manually stopped. Adding an **"aborted"** state will solve that. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kmehkeri** [comment]
Same could be for individual tasks.

**Comment by tirkarthi** [comment]
This seems to be similar to https://github.com/apache/airflow/issues/21252

**Comment by potiuk** [comment]
Just FYI - @itay-raveh - the surest way to get it is to implement it yourself if you are interested to get it.

**Comment by josedaniel-escribano-clarity** [comment]
Hi all, we started to work on this. Here is the branch containing the first changes at api level, we will try to continue in the future but in case anyone wants go for it here is [the code](https://github.com/clarityai-eng/airflow/tree/include-aborted-state). :)

**Comment by vedantlodha** [comment]
Hi @potiuk I would love to work on this! Last discussion on this and the related issue seems to be over 6 months old. If its okay, can i work on this issue? Also, could you assign this issue to me?

**Comment by utkarsharma2** [comment]
@potiuk I would like to contribute to this. Please assign this to me. :)

**Comment by potiuk** [comment]
I can. But be warned - this likely is going to span some discussions and will take time to complete, because of a "deep" change in the core it introduces.

**Comment by utkarsharma2** [comment]
Ya, I think this will require some core-level changes, but do you think there is an easier way to achieve this?

**Comment by potiuk** [comment]
No. But It will cause some discussions and people having opinions and maybe even rejecting the whole idea (just saying, it involves a lot of communication not only code).

**Comment by utkarsharma2** [comment]
Fair enough, I'll give it a shot. :)

**Comment by utkarsharma2** [comment]
@potiuk What if we can track user activity and show it in the UI? 

1. If a user updates a task we can show the `user name` in the UI
2. If airflow does we can show `airflow`.

That way we won't have to update the internal states as well.

**Comment by eladkal** [comment]
> What if we can track user activity and show it in the UI?

There is audit log https://github.com/apache/airflow/pull/25856

**Comment by eladkal** [comment]
> It will cause some discussions and people having opinions and maybe even rejecting the whole idea

Agree. I for example am -1 for this idea mainly because use cases for this are not strong (at least I didn't see compiling arguments that in this thread)
I think this require a mailing list thread that will be very details about the motivation for this request.

**Comment by utkarsharma2** [comment]
@eladkal That Makes sense. Since I don't have the entire context about the motivation/use case for this. @itay-raveh can you please share more details?

**Comment by itay-raveh** [comment]
> @eladkal That Makes sense. Since I don't have the entire context about the motivation/use case for this. @itay-raveh can you please share more details? 
> 
> Also, an audit log should be sufficient for your use case, right?

For my use case, the need for the 'aborted' state is similar to the need for the 'skipped' state. If someone triggered a dag, and decided based on the logs that the rest of the tasks should not run, I would like to know that.

In that situation, there is a difference between "Something failed but did not raise an error, so I stopped it manually" and "I realised that, although everything is working, I actually don't need the dag to continue"

While 'skipped' indicates a programmatic decision to skip some task, 'aborted' indicates a human decision to skip the rest of the dag. 

However, I concede that this may not be a widespread use case, and as such might not warrant a core change. I have no knowledge on the scope of the required changes or on the popularity of my suggestion.




Currently I use the success and failure callbacks for tasks and dags to send updates to an external service. I would need a third callback, which I assume requires a core change as discussed above. 

The goal is to track the failure rate of dags and tasks, which is why counting manual abortions as failures is problematic. 

If I could, as you suggested, query the user (or `airflow`) which marked the failure, I should be able to make do with that. It would be much less convenient, but beggars can't be choosers :)

**Comment by eladkal** [comment]
> For my use case, the need for the 'aborted' state is similar to the need for the 'skipped' state. If someone triggered a dag, and decided based on the logs that the rest of the tasks should not run, I would like to know that.

One can leave a note on the tasks:
![Screenshot 2023-04-08 at 0 13 27](https://user-images.githubusercontent.com/45845474/230679799-94c564f4-1750-4baa-8f96-13c8e29a03ab.png)


I would like to hear the full use case of this scenario.
What does the new status is for?
is it for human to know what happens with this run or do you expect further actions to be taken automatically?
is it for metric collection?
Do you see it on dag level or task level and why?

**Comment by utkarsharma2** [comment]
@eladkal @potiuk I think there is a delicate issue, if so can we please close it? 
ref - https://github.com/apache/airflow/issues/21252

**Comment by potiuk** [comment]
> @eladkal @potiuk I think there is a delicate issue, if so can we please close it?

Why ? discussing and having options is normal. why closing an issue opened by somoene else quoting as "delicate"?

**Comment by utkarsharma2** [comment]
I'm sorry @potiuk, I meant there is a duplicate issue, a typo. Also, I agree, we should have multiple options :)

**Comment by potiuk** [comment]
Typos is somethign I do all the time . I know the drill :)
