### ISSUE TITLE
DB To GCS Operations Should Return/Save Row Count

### ISSUE THREAD

**Issue by patricker** [apache/airflow#22065]
### Description

All DB to GCS Operators should track the per file and total row count written for metadata and validation purposes.

- Optionally, based on param, include the row count metadata as GCS file upload metadata.
- Always return row count data through XCom. Currently this operator has no return value.

### Use case/motivation

Currently, there is no way to check the uploaded files row count without opening the file. Downstream operations should have access to this information, and allowing it to be saved as GCS metadata and returning it through XCom makes it readily available for other uses.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This would be easier after https://github.com/apache/airflow/issues/21599

**Comment by patricker** [comment]
@eladkal I actually wrote this up last night. I didn't have to touch any of the implementation specific classes. I only had to change `BaseSQLToGCSOperator`. Still testing the code.
