### ISSUE TITLE
Separate dag/task UI display name from dag / task id

### ISSUE THREAD

**Issue by EricGao888** [apache/airflow#22073]
### Description

* Enable users to use their national characters, which are usually non-ASCIIs as the display name of their dags / tasks.

### Use case/motivation

* At present, only ASCIIs are allowed for dag_id and task_id as shown in [this comment](https://github.com/apache/airflow/issues/21127#issuecomment-1045329791). 
* However, in many cases, users would like to use their national characters for their dag_ids and task_ids, which apparently leads to some existing issues, related: #21127, #18010
* Enabling non-ASCII dag_id / task_id would be a great idea to solve these issues as [commented here](https://github.com/apache/airflow/issues/18010#issuecomment-912820115)
* For a quick fix, maybe we could add a new optional field `display_name` for both dag and task.
* Considering backward compatibility, dag_id or task_id will be used as UI display name if the field `display_name` is None.

UPDATE (by @potiuk):

* any solution to this one should also include possibility of specifying names for dynamically mapped tasks (individually - per mapped index id)

### Related issues

related: #21127 
related: #18010
related: #23020 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by EricGao888** [comment]
> I think it's a good feature to have. I hope someone would like to pick it up.

I'd like to take a look into this : )

**Comment by HugoCornu** [comment]
Separating task_id and task display name would allow to haev several similar tasks showing the same name.

**Comment by potiuk** [comment]
Sure.Anyone is free to submit PR s imeplementing it @HugoCornu - yourself including.

**Comment by koroder** [comment]
I am looking to make my first contribution to Airflow. Would it be okay if I work on this issue?

**Comment by EricGao888** [comment]
> @potiuk I am looking to make my first contribution to Airflow. Would it be okay if I work on this issue?

@koroder It's totally fine from my perspective. As currently I'm busy with another project. Thx.

**Comment by EricGao888** [comment]
> @potiuk I am looking to make my first contribution to Airflow. Would it be okay if I work on this issue?

@koroder BTW, you may directly start from this PR if you'd like to. #22118

**Comment by koroder** [comment]
Awesome! This is really helpful - I will take it from here.

**Comment by potiuk** [comment]
Following up from the discussion in #23020  - this feature should also include naming of mapped tasks.

**Comment by aleksandr-shel** [comment]
Hi guys, I would like to try to solve this issue

**Comment by potiuk** [comment]
Feel free.

**Comment by eladkal** [comment]
There is a pending PR https://github.com/apache/airflow/pull/27145
I think we are waiting for a dev list discussion on that

**Comment by aleksandr-shel** [comment]
> There is a pending PR #27145 I think we are waiting for a dev list discussion on that

Are there any other issues you can recommend?

**Comment by aleksandr-shel** [comment]
I put up a pr, would someone be able to take a look, please? #28183

**Comment by potiuk** [comment]
I did. A LOT more needs to be done for that (and I would really like others to chime in there). The #28183 is just  the beginning of what should happen in te PR if we are to go in this direction (details in comments in the PR - and I think this is also just beginning of the comments, there are probably more things that will have to be thought about in this PR that I have not yet thought about.

**Comment by matthewblock** [comment]
Any more news on this? On top of the use cases listed, it could address the lack of support for changing a DAG name without wiping out its logs and `dag_runs`.

**Comment by potiuk** [comment]
Well. As all other issues here - likely if there is no changes, nobody works on it. But if you feel like it, you can. I can assign you - the whole history of the issue is there - one of the solutions were vetoed by one of the maintainers - you can read all in the history. Better solution that would solve the problems mentioned there would probably be accepted if someone works on it. Would you like to @matthewblock ?

**Comment by alex-astronomer** [comment]
+1 on this!  Would love to see a feature like this for DAGs that delegate a bunch of work to mapped tasks and have a clear identifier for the work that is being done in that particular dynamic mapped task.

To make this more general I think is also brilliant.  I'd love to work on this but we'll see if I get the time...

**Comment by matthewblock** [comment]
> Well. As all other issues here - likely if there is no changes, nobody works on it. But if you feel like it, you can. I can assign you - the whole history of the issue is there - one of the solutions were vetoed by one of the maintainers - you can read all in the history. Better solution that would solve the problems mentioned there would probably be accepted if someone works on it. Would you like to @matthewblock ?

I'm not a contributor at the moment and unfortunately I won't have the bandwidth to do so in the short term.

**Comment by xgao1023** [comment]
I created a new PR, it's based on the work from **aleksandr-shel** but removed slugifiying
https://github.com/apache/airflow/pull/32520

**Comment by pnsvk** [comment]
do we have a timeline on this ? please update.

**Comment by cmarteepants** [comment]
@pnsvk the [PR](https://github.com/apache/airflow/pull/38446) will be included as part of 2.9, which should be released within the next 1.5 weeks
