### ISSUE TITLE
@task decorator does not handle "templates_exts" argument correctly (files are not rendered)

### ISSUE THREAD

**Issue by ghost** [apache/airflow#22072]
### Apache Airflow version

2.2.2

### What happened

When I use Taskflow, and especially the `@task` decorator to create a task, the template files are not correctly rendered : I still have the filename inside `templates_dict` instead of the templated file content, even though I supplied a valid `templates_exts` argument (at least one which works with `PythonOperator`).

I do not encounter the same issue using the old  `PythonOperator` syntax.

### What you expected to happen

I expect that the behavior of the `@task` decorator would be the same as the `PythonOperator` class, or at least have a workaround explained in the documentation such as other arguments I would need to provide.

### How to reproduce

Sample code below :

```python
from airflow.decorators import task

@task(templates_dict={"query": "sql/sample.sql"}, templates_exts=[".sql"])
def aggregate_logs(**kwargs):
    logging.info("query: %s", str(kwargs["templates_dict"]["query"]))
```

Which returns `INFO - query: sql/sample.sql`.

However, if I use a `PythonOperator` with the old syntax it works :

```python
from airflow.operators.python import PythonOperator

def aggregate_logs(**kwargs):
    logging.info("query: %s", str(kwargs["templates_dict"]["query"]))

aggregate_task = PythonOperator(
    python_callable=aggregate_logs,
    templates_dict={"query": "sql/sample.sql"},
    templates_exts=[".sql"],
)
```

I get the entire templated file inside `kwargs["templates_dict"]["query"]`, not just its name.

### Operating System

AWS MWAA

### Versions of Apache Airflow Providers

Not sure if relevant here since I only use Airflow packages in the example.

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xingularity** [comment]
I am interested in this issue and I would like to work on it.

**Comment by potiuk** [comment]
If there is no response from @xingularity, maybe you want to take over @esthomw ?

**Comment by Bowrna** [comment]
I could try fixing this issue if @xingularity and @esthomw do not want to take over.

**Comment by potiuk** [comment]
Feel free @bowrna :) - unless @xingularity raises a hand (and @esthomw - you could also help with reviewing and testing the change if you don't feel like implementing it).

**Comment by esthomw** [comment]
@potiuk I would love to address that issue, however, I am not sure if I currently have enough time. In that case please go ahead @Bowrna :) I will try to help with reviewing and testing
