### ISSUE TITLE
add timeout to DockerOperator

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#22115]
### Body

`APIClient` has [timeout](https://github.com/docker/docker-py/blob/b27faa62e792c141a5d20c4acdd240fdac7d282f/docker/api/client.py#L84) param which sets default timeout for API calls. The package [default](https://github.com/docker/docker-py/blob/7779b84e87bea3bac3a32b3ec1511bc1bfaa44f1/docker/constants.py#L6) is 60 seconds which may not be enough for some process.

The needed fix is to allow to set `timeout` to the APIClient constructor in DockerHook and DockerOperator:

for example in:
https://github.com/apache/airflow/blob/05f3a309668288e03988fc4774f9c801974b63d0/airflow/providers/docker/hooks/docker.py#L89

Note that in some cases DockerOperator uses APIClient directly for example in:
https://github.com/apache/airflow/blob/05f3a309668288e03988fc4774f9c801974b63d0/airflow/providers/docker/operators/docker.py#L390

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by prashantpaidi** [comment]
I am new to open source. Can I work on this?

**Comment by josh-fell** [comment]
@prashantpaidi Feel free, it's all yours!

**Comment by prashantpaidi** [comment]
@josh-fell Currently value of `DEFAULT_TIMEOUT_SECONDS` is `60`.
What would be the right `DEFAULT_TIMEOUT_SECONDS` value?

**Comment by eladkal** [comment]
> @josh-fell Currently value of `DEFAULT_TIMEOUT_SECONDS` is `60`. What would be the right `DEFAULT_TIMEOUT_SECONDS` value?

It's optional param so you don't have to set it.
If you must set then I would say import `DEFAULT_TIMEOUT_SECONDS` from the lib and use it directly.

**Comment by prashantpaidi** [comment]
So after importing, I should create the new variable and assign an increased value or while passing the parameter add the value?

what should be the timeout seconds value?

**Comment by eladkal** [comment]
@prashantpaidi i think it would be good if you can open a draft PR with what you had in mind then we can review the code. You can make descion of how you think it should be done and just explain it in the description.
On the PR we can discuss alternative options if needed

**Comment by Bowrna** [comment]
Could I pick up this issue to work on?
