### ISSUE TITLE
apache-airflow-providers-google uses deprecated Google Ads API V8

### ISSUE THREAD

**Issue by anthonyjgraff** [apache/airflow#22111]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google = 6.4.0

### Apache Airflow version

2.1.3

### Operating System

Debian Buster

### Deployment

Other Docker-based deployment

### What happened

`apache-airflow-providers-google 6.4.0` has the requirement `google-ads >=12.0.0,<14.0.1`

The latest version of the Google Ads API supported by this is V8 - this was deprecated in November 2021, and is due to be disabled in April / May (see https://developers.google.com/google-ads/api/docs/sunset-dates)

### What you expected to happen

Update the requirements to so that the provider uses a version of the Google Ads API which hasn't been deprecated

At the moment, the only non-deprecated version is V10 - support for this was added in `google-ads=15.0.0`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add PR upgrading  it @anthonyjgraff !

**Comment by potiuk** [comment]
Assigned you

**Comment by anthonyjgraff** [comment]
I tried to upgrade the dependencies, and noticed this comment in `setup.py` https://github.com/apache/airflow/issues/18705#issuecomment-933746150

It looks like all recent releases of `google-ads` still require `google-api-core >= 2.0.1` (see https://github.com/googleads/google-ads-python/issues/569)

Will this still cause conflicts with other libraries?

**Comment by potiuk** [comment]
> Will this still cause conflicts with other libraries?

Likely

**Comment by anthonyjgraff** [comment]
Had a look through to work out where the conflicts would be (seeing as there's already a TODO to upgrade libraries which required < 2.0.0)

🟢  = Airflow minimum requirement already supports > 2.0.0
🟠  = Minimum requirement needs to be bumped, but latest requirement supports > 2.0.0
🔴  = Doesn't currently support > 2.0.0

| Library                            | Current Version  | Required Version | Supported        | Link                                                                                                                                                                                                 |
| ---------------------------------- | ---------------- | ---------------- | ---------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| google-cloud-aiplatform            | \>=1.7.1,<2.0.0  | \>=1.3.0         | :green\_circle:  | [https://github.com/googleapis/python-aiplatform/blob/main/CHANGELOG.md#130-2021-07-30](https://github.com/googleapis/python-aiplatform/blob/main/CHANGELOG.md#130-2021-07-30)                       |
| google-cloud-automl                | \>=2.1.0         | \>=2.4.1         | :orange\_circle: | [https://github.com/googleapis/python-automl/blob/main/CHANGELOG.md#241-2021-07-21](https://github.com/googleapis/python-automl/blob/main/CHANGELOG.md#241-2021-07-21)                               |
| google-cloud-bigquery-datatransfer | \>=3.0.0         | \>=3.3.1         | :orange\_circle: | [https://github.com/googleapis/python-bigquery-datatransfer/blob/main/CHANGELOG.md#331-2021-07-26](https://github.com/googleapis/python-bigquery-datatransfer/blob/main/CHANGELOG.md#331-2021-07-26) |
| google-cloud-bigtable              | \>=1.0.0,<2.0.0  | \>=2.3.2         | :red\_circle:    | [https://github.com/googleapis/python-bigtable/blob/main/CHANGELOG.md#232-2021-07-20](https://github.com/googleapis/python-bigtable/blob/main/CHANGELOG.md#232-2021-07-20)                           |
| google-cloud-build                 | \>=3.0.0         | \>=3.3.1         | :orange\_circle: | [https://github.com/googleapis/python-cloudbuild/blob/main/CHANGELOG.md#331-2021-07-24](https://github.com/googleapis/python-cloudbuild/blob/main/CHANGELOG.md#331-2021-07-24)                       |
| google-cloud-container             | \>=0.1.1,<2.0.0  | \>=2.6.1         | :red\_circle:    | [https://github.com/googleapis/python-container/blob/main/CHANGELOG.md#261-2021-07-20](https://github.com/googleapis/python-container/blob/main/CHANGELOG.md#261-2021-07-20)                         |
| google-cloud-datacatalog           | \>=3.0.0         | \>=3.3.1         | :orange\_circle: | [https://github.com/googleapis/python-datacatalog/blob/main/CHANGELOG.md#331-2021-07-20](https://github.com/googleapis/python-datacatalog/blob/main/CHANGELOG.md#331-2021-07-20)                     |
| google-cloud-dataproc              | \>=3.1.0         | \>=2.5.0         | :green\_circle:  | [https://github.com/googleapis/python-dataproc/blob/main/CHANGELOG.md#250-2021-07-24](https://github.com/googleapis/python-dataproc/blob/main/CHANGELOG.md#250-2021-07-24)                           |
| google-cloud-dataproc-metastore    | \>=1.2.0,<2.0.0  | \>=0.3.1         | :green\_circle:  | [https://github.com/googleapis/python-dataproc-metastore/blob/main/CHANGELOG.md#031-2021-07-26](https://github.com/googleapis/python-dataproc-metastore/blob/main/CHANGELOG.md#031-2021-07-26)       |
| google-cloud-dlp                   | \>=0.11.0,<2.0.0 | \>=3.2.1         | :red\_circle:    | [https://github.com/googleapis/python-dlp/blob/main/CHANGELOG.md#321-2021-07-21](https://github.com/googleapis/python-dlp/blob/main/CHANGELOG.md#321-2021-07-21)                                     |
| google-cloud-kms                   | \>=2.0.0         | \>=2.4.1         | :orange\_circle: | [https://github.com/googleapis/python-kms/blob/main/CHANGELOG.md#241-2021-07-20](https://github.com/googleapis/python-kms/blob/main/CHANGELOG.md#241-2021-07-20)                                     |
| google-cloud-language              | \>=1.1.1,<2.0.0  | \>=2.2.1         | :red\_circle:    | [https://github.com/googleapis/python-language/blob/main/CHANGELOG.md#221-2021-07-20](https://github.com/googleapis/python-language/blob/main/CHANGELOG.md#221-2021-07-20)                           |
| google-cloud-logging               | \>=2.1.1         | \>=2.6.0         | :orange\_circle: | [https://github.com/googleapis/python-logging/blob/main/CHANGELOG.md#260-2021-07-28](https://github.com/googleapis/python-logging/blob/main/CHANGELOG.md#260-2021-07-28)                             |
| google-cloud-memcache              | \>=0.2.0         | \>=1.1.1         | :orange\_circle: | [https://github.com/googleapis/python-memcache/blob/main/CHANGELOG.md#111-2021-07-26](https://github.com/googleapis/python-memcache/blob/main/CHANGELOG.md#111-2021-07-26)                           |
| google-cloud-monitoring            | \>=2.0.0         | \>=2.4.1         | :orange\_circle: | [https://github.com/googleapis/python-monitoring/blob/main/CHANGELOG.md#241-2021-07-20](https://github.com/googleapis/python-monitoring/blob/main/CHANGELOG.md#241-2021-07-20)                       |
| google-cloud-os-login              | \>=2.0.0         | \>=2.3.1         | :orange\_circle: | [https://github.com/googleapis/python-oslogin/blob/main/CHANGELOG.md#231-2021-07-26](https://github.com/googleapis/python-oslogin/blob/main/CHANGELOG.md#231-2021-07-26)                             |
| google-cloud-orchestration-airflow | \>=1.0.0,<2.0.0  | \>=0.1.1         | :green\_circle:  | [https://github.com/googleapis/python-orchestration-airflow/blob/main/CHANGELOG.md#011-2021-07-28](https://github.com/googleapis/python-orchestration-airflow/blob/main/CHANGELOG.md#011-2021-07-28) |
| google-cloud-pubsub                | \>=2.0.0         | \>=2.7.0         | :orange\_circle: | [https://github.com/googleapis/python-pubsub/blob/main/CHANGELOG.md#270-2021-07-24](https://github.com/googleapis/python-pubsub/blob/main/CHANGELOG.md#270-2021-07-24)                               |
| google-cloud-redis                 | \>=2.0.0         | \>=2.2.1         | :orange\_circle: | [https://github.com/googleapis/python-redis/blob/main/CHANGELOG.md#221-2021-07-20](https://github.com/googleapis/python-redis/blob/main/CHANGELOG.md#221-2021-07-20)                                 |
| google-cloud-secret-manager        | \>=0.2.0,<2.0.0  | \>=2.7.0         | :red\_circle:    | [https://github.com/googleapis/python-secret-manager/blob/main/CHANGELOG.md#270-2021-08-03](https://github.com/googleapis/python-secret-manager/blob/main/CHANGELOG.md#270-2021-08-03)               |
| google-cloud-spanner               | \>=1.10.0,<2.0.0 | \>=3.7.0         | :red\_circle:    | [https://github.com/googleapis/python-spanner/blob/main/CHANGELOG.md#370-2021-07-29](https://github.com/googleapis/python-spanner/blob/main/CHANGELOG.md#370-2021-07-29)                             |
| google-cloud-speech                | \>=0.36.3,<2.0.0 | \>=2.5.1         | :red\_circle:    | [https://github.com/googleapis/python-speech/blob/main/CHANGELOG.md#251-2021-07-21](https://github.com/googleapis/python-speech/blob/main/CHANGELOG.md#251-2021-07-21)                               |
| google-cloud-storage               | \>=1.30,<2.0.0   | \>=1.41.1        | :orange\_circle: | [https://github.com/googleapis/python-storage/blob/main/CHANGELOG.md#1411-2021-07-20](https://github.com/googleapis/python-storage/blob/main/CHANGELOG.md#1411-2021-07-20)                           |
| google-cloud-tasks                 | \>=2.0.0         | \>=2.5.0         | :orange\_circle: | [https://github.com/googleapis/python-tasks/blob/main/CHANGELOG.md#250-2021-07-21](https://github.com/googleapis/python-tasks/blob/main/CHANGELOG.md#250-2021-07-21)                                 |
| google-cloud-texttospeech          | \>=0.4.0,<2.0.0  | \>=2.5.1         | :red\_circle:    | [https://github.com/googleapis/python-texttospeech/blob/main/CHANGELOG.md#251-2021-07-20](https://github.com/googleapis/python-texttospeech/blob/main/CHANGELOG.md#251-2021-07-20)                   |
| google-cloud-translate             | \>=1.5.0,<2.0.0  | \>=3.3.1         | :red\_circle:    | [https://github.com/googleapis/python-translate/blob/main/CHANGELOG.md#331-2021-07-21](https://github.com/googleapis/python-translate/blob/main/CHANGELOG.md#331-2021-07-21)                         |
| google-cloud-videointelligence     | \>=1.7.0,<2.0.0  | \>=2.3.1         | :red\_circle:    | [https://github.com/googleapis/python-videointelligence/blob/main/CHANGELOG.md#231-2021-07-20](https://github.com/googleapis/python-videointelligence/blob/main/CHANGELOG.md#231-2021-07-20)         |
| google-cloud-vision                | \>=0.35.2,<2.0.0 | \>=2.4.1         | :red\_circle:    | [https://github.com/googleapis/python-vision/blob/main/CHANGELOG.md#241-2021-07-21](https://github.com/googleapis/python-vision/blob/main/CHANGELOG.md#241-2021-07-21)                               |
| google-cloud-workflows             | \>=0.1.0,<2.0.0  | \>=1.2.1         | :orange\_circle: | [https://github.com/googleapis/python-workflows/blob/main/CHANGELOG.md#121-2021-07-26](https://github.com/googleapis/python-workflows/blob/main/CHANGELOG.md#121-2021-07-26)                         |

That's a lot of conflicts - will definitely need to hold off until the requirement in `google-ads` is relaxed

**Comment by eladkal** [comment]
I think the real blocker is not really google-ads but more :
https://github.com/googleapis/google-cloud-python/issues/10566
which blocks also bumping google-ads

**Comment by potiuk** [comment]
Yeah. I think this is about the right time to take a concerted action maybe to upgrade all the remaining libraries to > 2.0.0 :) @lwyszomi @mnojek . It's very likely that pretty much all the packages are already possible to upgrade. It's I think ~1.5 year since the breaking 2.0.0 Google APIs were released.

**Comment by lwyszomi** [comment]
I think this will be a good step to start upgrading all google packages to the latest version. I will try to prioritize this upgrades as soon as possible but hard to say any dates for now.

**Comment by potiuk** [comment]
> I think this will be a good step to start upgrading all google packages to the latest version. I will try to prioritize this upgrades as soon as possible but hard to say any dates for now.

Happy to help with reviewing etc.:)

**Comment by anthonyjgraff** [comment]
Google Ads Python has relaxed it's dependencies as of v15.1.1 (which was released earlier today) - will take another look at upgrading the dependencies!
