### ISSUE TITLE
Add autodetect arg in BQCreateExternalTable Operator

### ISSUE THREAD

**Issue by shahkshitij15** [apache/airflow#22129]
### Apache Airflow Provider(s)

google

### Apache Airflow version

2.2.4 (latest released)

### Operating System

macOS Monterey

### Deployment

Virtualenv installation

### What happened

Autodetect parameter is missing in the create_external_table function in BQCreateExternalTableOperator because of which one cannot create external tables if schema files are missing
See function on line 1140 in this [file](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py)

### What you expected to happen

If autodetect argument is passed to the create_external_table function then one can create external tables without mentioning the schema for a CSV file leveraging the automatic detection functionality provided by the big query 

### How to reproduce

Simply call BigQueryCreateExternalTableOperator in the dag without mentioning schema_fields or schema_object

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@shahkshitij15 Feel free to submit a PR. Assigned to you.

**Comment by hankehly** [comment]
@shahkshitij15 @josh-fell I will take this if you don't mind
