### ISSUE TITLE
Show average dag run duration

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#22132]
It would be useful to show a running average dag run duration in the grid view. This could be a plotted line on top of the duration bar chart.

The average duration should be calculated on the webserver and included  with a dag run's info.

Bonus: We could possibly use the average duration to calculate a very rough "Expected time to completion" for active dag runs.

**Comment by eladkal** [comment]
If possible I would say that we should let users decide on the metrics to be displayed. Can we provide options and let the users choose? For example some might prefer median (p50) over avg, some might want p80 etc..

**Comment by raj-wadhwa** [comment]
Is there any progress in this area? I was looking for this info to be returned in the API for DAG Run info: 
`ETA` or `Estimated_Time_To_Completion`

Something like this.
Is anyone aware that it's being developed? or is likely to be picked up for development?

**Comment by potiuk** [comment]
> Is anyone aware that it's being developed? or is likely to be picked up for development?

Marked it as good first issue. That's what I can do as maintainer.  

Just to set expectations right:

If you want to take a shot at it and try it yourself. Also if you have an interest in this feature (if you do not have skills) what works well is finding someone who would contribute it (for example at your company, customer who has the right skills and can contribute it). That's the best way to give back by the companies using the freely available software - by contributing back.

This is usually how things work in Open-Source projects. Things get implemented, when someone implements it and the best way to get something implemented is to either implement it or find someone who will implement it for you.

**Comment by raj-wadhwa** [comment]
@potiuk 
Sure. Let me try my hands on it. Will provide an update If I'm successful at it.

**Comment by moreaupascal56** [comment]
Hey ! I'd love to have this feature for a long time as well, if you want some help I can give it a shot as well

**Comment by raj-wadhwa** [comment]
Hi @moreaupascal56 ,

I did work on this feature. But for now, using it locally.
Can we connect to review the solution and then submit it?

**Comment by jscheffl** [comment]
Implemented via #38214
