### ISSUE TITLE
Minimal Constraints files not define

### ISSUE THREAD

**Issue by sandeepmohan** [apache/airflow#22164]
### Describe the issue with documentation

So for a base install of Airflow [no providers or extras] where use case requires only BashOperator, was looking to install Airflow from pip.

The standard `pip3 install apache-airflow==2.2.3` works but results in web server issues not rendering GUI as the flask version we have in our artifactory is higher. Web Server launches but GUI not accessible. 

If we try the constraints file `https://raw.githubusercontent.com/apache/airflow/constraints-2.2.3/constraints-3.7.txt` with the pip install, it tries to locate various libraries associated with provider packages many of which we have no use for no is on our Artifactory.

We are trying to install with no access to the internet. 

Can a constraints file be defined (or can I be pointed to one) that has the minimum libraries defined for a working installation sans any operator other than Bash, Dummy and Python? This seems to be the mission of `https://raw.githubusercontent.com/apache/airflow/constraints-2.2.3/constraints-3.7.txt` but the file has a large number of provider libraries that is "more than bare minimum or core"...

Thanks in advance. 

Sandeep

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I think you are confusing constraints with requirements.
constraints doesn't install anything.
