### ISSUE TITLE
Support log download in task log view

### ISSUE THREAD

**Issue by euccas** [apache/airflow#22174]
### Description

Support log downloading from the task log view by adding a download button in the UI.

### Use case/motivation

In the current version of Airflow, when we want to download a task try's log, we can click on the task node in Tree View or Graph view, and use the "Download" button in the task action modal, as in this screenshot:
<img width="752" alt="Screen Shot 2022-03-10 at 5 59 23 PM" src="https://user-images.githubusercontent.com/815701/157787811-feb7bdd4-4e32-4b85-b822-2d68662482e9.png">

It would make log downloading more convenient if we add a Download button in the task log view. This is the screenshot of the task log view, we can add a button on the right side of the "Toggle Wrap" button.

<img width="1214" alt="Screen Shot 2022-03-10 at 5 55 53 PM" src="https://user-images.githubusercontent.com/815701/157788262-a4cb8ff7-b813-4140-b8a1-41a5d0630e1f.png">

I work on Airflow at Pinterest, internally we get such a feature request from our users. I'd like to get your thoughts about adding this feature before I create a PR for it. Thanks.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
SGTM. We should add it because it is actually more intuitive. I'm just wondering if we shouldn't delete the download buttons from the modal window. What do you think?

**Comment by euccas** [comment]
I think we should keep the download buttons in the modal window, those buttons are useful!

**Comment by hankehly** [comment]
@euccas @mik-laj I can take this if you don't mind.

**Comment by euccas** [comment]
@hankehly hey if you have a PR, I'll help review it! Otherwise I'll submit my PR in a few days.

**Comment by hankehly** [comment]
@euccas Thank you! Please see #22804
