### ISSUE TITLE
max_active_runs = 1 can still create multiple active execution runs (again)

### ISSUE THREAD

**Issue by stas-snow** [apache/airflow#22193]
### Apache Airflow version

2.2.3

### What happened

Same issue as reported in: #9975 - max_active_runs** = 1 can still create multiple active execution runs.

I'm seeing this issue in airflow 2.2.3.
catchup=True and max_active_runs=1.
DAG is triggered multiple times and multiple instances are running in parallel.

![image](https://user-images.githubusercontent.com/93541868/157966793-794beb86-6e91-4589-9e51-76a3b58b51fc.png)

### What you expected to happen

Expect that only one instance of the DAG is running at any given time if max_active_runs=1.

### Operating System

GCP: composer-2.0.4-airflow-2.2.3

### Versions of Apache Airflow Providers

https://cloud.google.com/composer/docs/concepts/versioning/composer-versions
composer-2.0.4-airflow-2.2.3

### Deployment

Composer

### Deployment details

composer-2.0.4-airflow-2.2.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Describe how to reproduce it including a sample dag to reproduce it

**Comment by stas-snow** [comment]
Code:

```
import logging
import time

# Airflow packages
from random import uniform
from airflow.decorators import dag, task

logger = logging.getLogger(__name__)

default_dag_args = {
    'owner': 'airflow',
    'start_date': '2022-03-01',
    'schedule_interval': '@daily',
    'retries': 0,
    'catchup': True,
    'max_active_runs': 1,
    'depends_on_past': False,
}


@dag(default_args=default_dag_args)
def test2_dag():

    @task()
    def start():
        logging.info("Starting DAG. Going to sleep")
        time.sleep(uniform(1, 5) * 60)
        logging.info("First task, exiting")
        return None

    @task()
    def do():
        time.sleep(uniform(1, 5) * 60)
        return None

    @task()
    def end():
        logging.info(f"Finishing...")
        time.sleep(3)
        return None

    # Define dependency between tasks
    start() >> do() >> end()


# start the DAG
test_pipeline = test2_dag()

```

Screenshot of multiple DAG instances all in "Running" state.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/93541868/158224423-fae9b635-abd2-4be5-a292-fa2c6d3c5398.png">

Documentation says that there should not be more than max_active_runs in Running state:
```
max_active_runs – maximum number of active DAG runs, beyond this number of DAG runs in a running state, the scheduler won’t create new active DAG runs
```

I would expect only 1 DAG in Running state if I have "max_active_runs = 1".
