### ISSUE TITLE
Broken link for dbt-Cloud download

### ISSUE THREAD

**Issue by sebbASF** [apache/airflow#22197]
### Describe the issue with documentation

https://airflow.apache.org/docs/apache-airflow-providers/installing-from-sources

https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/installing-providers-from-sources.html => 404

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Fixed. Thanks again @sebbASF  - helped us to improve our processes :) 

I Would love to hear how did you check it.

**Comment by sebbASF** [comment]
I extracted the links semi-manually from the main page, and then checked them all using a Whimsy tool.

However of course this failed at the first hurdle.

**Comment by potiuk** [comment]
Cool. Thanks again!
