### ISSUE TITLE
Add Kerberos support

### ISSUE THREAD

**Issue by garthcn** [apache/airflow#222]
It'd be great if Airflow could add Kerberos support to hooks (e.g. HDFS, etc). The `snakebite` lib Airflow depends on just added Kerberos support in this PR: https://github.com/spotify/snakebite/pull/153

**Comment by mistercrunch** [comment]
I think that an `impersonate` flag in BaseOperator could be a decent generic way to help around security and attribution of "who is running what", even if Airflow is triggering the job.

The way `impersonate` would work is that the job on the worker would `sudo su {task.owner}` prior to running it. This assumes unix based roles and security to be deployed on workers. Of course many systems (take mysql for instance) don't support unix-type authentication.

Impersonate could be forced to `True` for given operators using the undocumented `policy` feature described in `settings.py`

**Comment by txominpelu** [comment]
Hello @garthcn and @mistercrunch , I would be really interested in having this feature in airflow. Right now the lack of support for kerberos is the main thing that is blocking the adoption of airflow in my project. 

I am willing to help in the implementation. Has anybody already started working on it?

**Comment by mistercrunch** [comment]
Can you describe which part(s) of Airflow you are thinking about integrating with Kerberos? Specific operators? The whole platform!?

**Comment by txominpelu** [comment]
I'd like to modify some operators (e.g Hive) so that they can be scheduled and run with the right user in a hadoop cluster in secure mode .

**Comment by pharoson** [comment]
#229 is a similar issue. It includes the current workaround I'm using to run workflows as a different user.

**Comment by mistercrunch** [comment]
@txominpelu , I'm not sure if you read the impersonation section in here:
http://www.cloudera.com/content/cloudera/en/documentation/cdh4/v4-3-0/CDH4-Security-Guide/cdh4sg_topic_9_1.html

You could have a model where the user on their dev box need to provide their kerberos creds, and in production the server has superuser creds and impersonates the owner of the task.

**Comment by bolkedebruin** [comment]
I did the work in snakebite. I am also interested in having Kerberos in. And although I need to wrap my mind around how airflow works and how it could be integrated I am
Willing to spend some time on it. I would think of something like:

Airflow has its own principal and keytab. This allows it to renew tickets on behalf of users, so it allows users to use their own credentials for "submitting". I'm not sure yet though how the submitting part would work. Or in other words how to make sure scripts executed under the users credentials are secured
And someone else cannot impersonate the user. Any ideas?

**Comment by bolkedebruin** [comment]
Btw having only one super user is not enough in a multi tenant environment. Segregation of duties is required then. Therefore separate users are required

**Comment by txominpelu** [comment]
I was thinking on doing something similar to what hue does in the default setup for cloudera. The hue user is a proxy user that can impersonate others when launching oozie workflows, hive queries, spark jobs, etc. That means that the hue user can do anything (not ideal), but hue users can only schedule and run things by asking hue to impersonate them.

**Comment by mistercrunch** [comment]
@txominpelu , this should work. The key is users develop using their own credentials locally, and when the code runs on the worker it runs as user `airflow` that can impersonate the owner of the task.

There needs to be safeguards around source control, and the policy can be inforced with the "policy function" on the worker.

**Comment by bolkedebruin** [comment]
@txominpelu actually the hue user is not capable of doing everything except that it is allowed to impersonate other users when the right credential is supplied for that user. Ideally airflow, in a Kerberos context, should never execute under its own principal.

**Comment by bolkedebruin** [comment]
The question for me is where to start? Basically airflow should not allow unauthenticated users to 1) connect to the webservice (ie present authentication screen) 2) start/schedule jobs of other users. Also how are users going to submit jobs? In the end they cannot copy their code to the server I presume or maybe they can? And what to do with the user administration? Does it need synchronization or externalization?

We can start small of course. First Kerberize the webservice only allow authenticated users, leaving user admin for what it is. Then move on to the command line and jobs and maybe force the user to the one submitting the job?

**Comment by mistercrunch** [comment]
One of the first step is for the hook to allow other types of authentication and make the impersonation work.
https://github.com/airbnb/airflow/blob/master/airflow/hooks/hive_hooks.py#L329

**Comment by bolkedebruin** [comment]
Impersonation is the one of the most complex steps. Ie it requires a service principal, a ticket renewer and verification of the user's credentials.

**Comment by mistercrunch** [comment]
Here are a few ideas on things that might work: 
- you could have an `extra` parameter that would look up credentials from a local file with a specific format, the user would put their creds in a local `600` file
- add an `impersonate` flag to the hooks that when it is set to true it changes the behavior of the operator. For BashOperator that might mean adding a `sudo su {owner}` or `chpst` somewhere in the bash command
- use a policy function as defined in settings.py to force the environment on the workers to force `impersonate=True` when running on the worker and alter the connection to get/use the `airflow` user and credentials.

**Comment by bolkedebruin** [comment]
I'm doing some work in bolkedebruin/airflow kerberos branch. I'm taking the hue approach - ie a key tab file and tickets that are renewed by a separate process (airflow kerberos). This process will be required wherever airflow is running. I haven't thought about it how to implement in with Celery. Sudo I won't touch as this is something else than Kerberos support. To make use of the Kerberos support the different hooks need to updated.

**Comment by txominpelu** [comment]
Hello @bolkedebruin , I've seen you're doing a good job with the ticket generation. If you manage to create a session ticket for the airflow application I think I can have quite easily a hive operator that uses impersonation by leveraging your tickets.

**Comment by bolkedebruin** [comment]
@txominpelu the session tickets is actually already generated. Ie: you should be able to access hive by the credentials that are now available for the "airflow" user (ie the uid under which "airflow kerberos" is running). 

Impersonation is something else yet (ie. by delegation tickets (preferred) or proxy)

**Comment by txominpelu** [comment]
I was thinking about using the impersonation mechanism described in the following gist:

https://gist.github.com/txominpelu/65a85524429e9f4e2c25

**Comment by bolkedebruin** [comment]
That is a proxy user and could work. I would say try it

Just to be sure: because airflow currently uses its own user administration you are basically circumventing the whole kerberos authentication. Preferably airflow integrates with LDAP/AD for its users then you get a little bit of security back. In the end delegation tokens are preferred eventually I would say.

**Comment by txominpelu** [comment]
I'm not sure why delegation tokens are safer. Could you explain how delegation tokens would be safer for a example for a job that is scheduled to be run every month?

**Comment by bolkedebruin** [comment]
Because they need the kerberos credentials of the user executing the job? Ie this makes end to end and auditable. Otherwise you are assuming airflow is safe enough to impersonate anyone and airflows documentation states "everything is wide open by default".

**Comment by harakiro** [comment]
It would be beneficial to have a look at the work done for the hue project: https://github.com/cloudera/hue
1) it has solved this
2) its written in python

**Comment by bolkedebruin** [comment]
@harakiro: my implementation for the ticket renewer is a straight up port from hue. Airflow needs an ldap authenticator to get the basics right and then for every part "doAs" functionality needs to be implemented.  Obvious targets are snakebite, hive as for those the groundwork has already been done in other projects.

**Comment by bolkedebruin** [comment]
@mistercrunch @harakiro @txominpelu come to think of it my airflow version should 'just' work with snakebite and kerberos activated if snakebite is running from the same host where "airflow kerberos" is started. I did not try it myself yet though.

**Comment by bolkedebruin** [comment]
I have done some further work on the kerberos support (https://github.com/bolkedebruin/airflow - kerberos branch). The HiveCliHook with beeline now works with kerberos (tested). To get it to work make sure you generate a key tab for airflow and put something like this in your airflow.cfg

`[security]
keytab = /etc/airflow/airflow.keytab
reinit_frequency = 3600
enabled = True`

then for the hive_cli connections add something like this:

`{ "use_beeline": true, "principal": "hive/_HOST@EXAMPLE.COM"}`. 

_HOST gets replaced by the fqdn of the server airflow is running on. Replace EXAMPLE.COM with your realm.

Furthermore you will need an "airflow kerberos" instance running for every worker. Celery stuff is working yet (ie. I havent looked at it yet).

Let me know what you think.

**Comment by bolkedebruin** [comment]
@txominpelu @garthcn @pharoson @mistercrunch 

Im am working on adding doAs functionality for the HiveCliHook. And I am wondering what I should take for a user that is being proxied. Is should this be the user mentioned as the login in the connection settings or should this be the owner that is set within a DAG?

From my perspective both have their downsides: access to connections is unauthenticated (every user has access to a connection) and thus this creates a risk of abuse and the same goes for owners of DAGs.

What would be the best approach?

edit: I just checked, but a hook doesn't know about a DAG owner so for now I will just use the login when configured to do so.

**Comment by mistercrunch** [comment]
You could add a flag "run_as_owner" in the operator and leave the choice to the user, fall back on the connection's information.

I think clearly the goal here is to make Airflow work with a Kerberosed Hive service, not to secure Airflow itself, that's bigger challenge that would start with securing the `Connection` access in some sort of vault that would require authentication. 

Airflow is still an "all or nothing" type of service for the time being.

**Comment by bolkedebruin** [comment]
Ok, I agree with the additional setting in the connections settings that sets whether login or owner should be used. This leaves some influence to an administrator.

BTW this is not just Hive but also (potentially) spark etc, so a bit of a generic pattern would be nice :)

**Comment by bolkedebruin** [comment]
@txominpelu @garthcn @pharoson I need some help in testing the patches I have created. Would you mind taking a look and either comment on the PR-#438 or here what your experiences are?

**Comment by txominpelu** [comment]
Hello @bolkedebruin, sure I'll have a look at your patches.
