### ISSUE TITLE
Contributing guide still refers to the branch 'master'

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#22215]
### Describe the issue with documentation

In `CONTRIBUTING.rst`, the image still says to fork `airflow/master`:

https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#contribution-workflow

### How to solve the problem

We need to make a new image and replace the current one 🙂 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by wutienyang** [comment]
Hi, thanks for the easy issue to experience how to contribute to Airflow. I am from PyCon APAC 2022 Sprint
It's my first time to give pr (https://github.com/apache/airflow/pull/22216). 

Please let me know if I missed anything or something is incorrect.

**Comment by potiuk** [comment]
Fixed by #22216
