### ISSUE TITLE
Allow entering dag_run_id when triggering DAG with config

### ISSUE THREAD

**Issue by yarong-lifemap** [apache/airflow#22299]
### Description

This will allow better tracking of runs without requiring commandline/REST API

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Covered by #21336.
