### ISSUE TITLE
ReST API : get_dag should return more than a simplified view of the dag

### ISSUE THREAD

**Issue by dylanbstorey** [apache/airflow#22325]
### Description

The current response payload from  https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag is a useful but simple view of the state of a given DAG. However it is missing some additional attributes that I feel would be useful for indiduals/groups who are choosing to interact with Airflow primarily through the ReST interface. 

### Use case/motivation

As part of a testing workflow we upload DAGs to a running airflow instance and want to trigger an execution of the DAG after we know that the scheduler has updated it. We're currently automating this process through the ReST API, but the `last_updated` is not exposed. 

This should be implemented from the dag_source endpoint. 

 https://github.com/apache/airflow/blob/main/airflow/api_connexion/endpoints/dag_source_endpoint.py

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Good idea! I wonder if it should be on get dag or get dag details.

**Comment by bbovenzi** [comment]
Good idea! I wonder if it should be on get dag or get dag details.
