### ISSUE TITLE
bigquery provider's - BigQueryCursor missing implementation for description property.

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#22328]
### Apache Airflow version

2.2.4 (latest released)

### What happened

When trying to run following code:

```
import pandas as pd
from airflow.providers.google.cloud.hooks.bigquery import BigqueryHook 

#using default connection
hook = BigqueryHook()

df = pd.read_sql(
        "SELECT * FROM table_name", con=hook.get_conn()
)
```

Running into following issue:

```Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/pandas/io/sql.py", line 602, in read_sql
    return pandas_sql.read_query(
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/pandas/io/sql.py", line 2117, in read_query
    columns = [col_desc[0] for col_desc in cursor.description]
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2599, in description
    raise NotImplementedError
NotImplementedError
```

### What you think should happen instead

The property should be implemented in a similar manner as [postgres_to_gcs.py](https://github.com/apache/airflow/blob/7bd165fbe2cbbfa8208803ec352c5d16ca2bd3ec/airflow/providers/google/cloud/transfers/postgres_to_gcs.py#L58)  

### Operating System

macOS

### Versions of Apache Airflow Providers

apache-airflow-providers-google==6.5.0

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to implement it @utkarsharma2

**Comment by eladkal** [comment]
@utkarsharma2 are you still working on this issue?

**Comment by utkarsharma2** [comment]
@eladkal, I didn't get a chance to work on it, planning to look into it next week.

**Comment by jayarjo** [comment]
Any update on this?

**Comment by sophiely** [comment]
Hi ! I don't know if you have some updates on this issue but I started a PR for this bug :) 

It's on draft for now because it's still a wip but do not hesitate to comment if you feel the need to.

[https://github.com/apache/airflow/pull/25366](url)
