### ISSUE TITLE
Copying DAG ID from UI and pasting in Slack includes schedule

### ISSUE THREAD

**Issue by alexbegg** [apache/airflow#22320]
### Apache Airflow version

2.2.3

### What happened

(Yes, I know the title says Slack and it might not seem like an Airflow issue, but so far this is the only application I noticed this on. There might be others.)

PR https://github.com/apache/airflow/pull/11503 was a fix to issue https://github.com/apache/airflow/issues/11500 to prevent text-selection of scheduler interval when selecting DAG ID. However it does not fix pasting the text into certain applications (such as Slack), at least on a Mac.

@ryanahamilton thanks for the fix, but this is fixed in the visible sense (double clicking the DAG ID to select it will now not show the schedule interval and next run as selected in the UI), however if you copy what is selected for some reason it still includes schedule interval and next run when pasted into certain applications.

I can't be sure why this is happening, but certain places such as pasting into Google Chrome, TextEdit, or Visual Studio Code it will only include the DAG ID and a new line. But other applications such as Slack (so far only one I can tell) it includes the schedule interval and next run, as you can see below:

- Schedule interval and next run **not shown as selected** on the DAG page:
    ![Screen Shot 2022-03-16 at 11 04 21 AM](https://user-images.githubusercontent.com/45696489/158659392-2df1f428-61e9-4785-be21-cdb1eda9ff6e.png)
- Schedule interval and next run **not pasted** in Google Chrome and TextEdit:
    ![Screen Shot 2022-03-16 at 11 05 10 AM](https://user-images.githubusercontent.com/45696489/158659521-adc2be64-1b31-403f-8630-b36b40900b42.png)
    ![Screen Shot 2022-03-16 at 11 15 14 AM](https://user-images.githubusercontent.com/45696489/158659539-0c76c079-3b44-4846-b41e-9038689bb33d.png)
- Schedule interval and next run **_pasted and visible_** in Slack:
   ![Screen Shot 2022-03-16 at 11 05 40 AM](https://user-images.githubusercontent.com/45696489/158659837-a57b0a57-306e-4ea2-9648-a4922d41c403.png)

### What you think should happen instead

When you select the DAG ID on the DAG page, copy what is selected, and then paste into a Slack message, only the DAG ID should be pasted.

### How to reproduce

Select the DAG ID on the DAG page (such as double-clicking the DAG ID), copy what is selected, and then paste into a Slack message.

### Operating System

macOS 1.15.7 (Catalina)

### Deployment

Astronomer

### Anything else

This is something that possibly could be a Slack bug (one could say that Slack should strip out anything that is `user-select: none`), however it should be possible to fix the HTML layout so `user-select: none` is not even needed to prevent selection. It is sort of a band-aid fix.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I can confirm this indeed happens with paste ( CMD + V)
However if you will paste with  CMD + SHIFT + V  - it will behave as you expect

**Comment by alexbegg** [comment]
> I can confirm this indeed happens with paste ( CMD + V)
> 
> However if you will paste with  CMD + SHIFT + V  - it will behave as you expect
> 
> 

Good catch on the CMD + SHIFT + V, I do that sometimes when I didn't want to paste HTML. I'll keep that in mind.

It will be nice though if selecting the text just selects that DAG ID and not the other stuff.

**Comment by potiuk** [comment]
Change it into feature. And yeah feel free to work on it @alexbegg  :)

**Comment by vchiapaikeo** [comment]
Is anyone still working on this? Happy to take this on if no one is.

**Comment by potiuk** [comment]
Feel free - if @alexbegg won't object :)
