### ISSUE TITLE
`airflow dags backfill` command doesn't propagate DagRun conf attribute if the DagRun already exists

### ISSUE THREAD

**Issue by nominee1997** [apache/airflow#22336]
### Apache Airflow version

2.1.4

### What happened

`airflow dags backfill` command has an option to provide config for the DagRun's it will trigger (https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#Named%20Arguments_repeat10).

This works correctly if there are no existing DagRun's for the execution dates in question. However, if they exist, then the existing config will not get overwritten. I think this is because in the backfill job code we check if there's an existing DagRun and use that if so. Thus we'll end up using the existing config! See https://github.com/apache/airflow/blob/81d633cc02813e44e1dfcd23dc29a06ddb0abb72/airflow/jobs/backfill_job.py#L291-L345

Potential fix could be to add setting `run.conf = self.conf` before we verify and return the run?

### Operating System

RHEL8

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hankehly** [comment]
@nominee1997 I haven't looked through the code, but the cli docs show a `--reset-dagruns` flag that may be useful for this purpose. Have you experimented with this?

> If reset_dag_run option is used, backfill will first prompt users whether airflow should clear all the previous dag_run and task_instances within the backfill date range.

https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#Named%20Arguments_repeat10

**Comment by babyyoda26** [comment]
@hankehly This issue needs to be fixed. Setting --reset-dagruns does not work for all use cases. It fails if tasks are having trigger rule as None_failed.

**Comment by snjypl** [comment]
this issue has been  fixed by https://github.com/apache/airflow/pull/22837
@ephraimbuddy  maybe we could close it?
