### ISSUE TITLE
ScheduleInterval schema in OpenAPI specs should have "nullable: true" otherwise generated OpenAPI client will throw an error in case of nullable "schedule_interval"

### ISSUE THREAD

**Issue by omarsmak** [apache/airflow#22358]
### Apache Airflow version

2.2.4 (latest released)

### What happened

Currently we have this schema definition in the OpenAPI specs:
```
    ScheduleInterval:
      description: |
        Schedule interval. Defines how often DAG runs, this object gets added to your latest task instance's
        execution_date to figure out the next schedule.
      readOnly: true
      oneOf:
        - $ref: '#/components/schemas/TimeDelta'
        - $ref: '#/components/schemas/RelativeDelta'
        - $ref: '#/components/schemas/CronExpression'
      discriminator:
        propertyName: __type
```

The issue with above is, when using an OpenAPI generator for Java for example (I think is same for other languages as well), it will treat `ScheduleInterval` as **non-nullable** property, although what is returned under `/dags/{dag_id}` or `/dags/{dag_id}/details` in case of a `None` `schedule_interval` is `null` for `schedule_interval`.

### What you think should happen instead

We should have `nullable: true` in `ScheduleInterval` schema which will allow `schedule_interval` to be parsed as `null`.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Anything else

If the maintainers think is a valid bug, I will be more than happy to submit a PR :)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kianelbo** [comment]
Does adding `allow_none=True` argument to [schedule_interval field](https://github.com/apache/airflow/blob/main/airflow/api_connexion/schemas/dag_schema.py#L64) suffice?
If so, may I open the PR?

**Comment by omarsmak** [comment]
I think it doesn't really help, the issue will be on the generated client side.
Feel free to open a PR as I haven't get the time yet

**Comment by Bowrna** [comment]
Currently when I hit the below API 
`http://127.0.0.1:28080/api/v1/dags/example_trigger_target_dag/details`,

I get the response:
```
{
  "catchup": false,
  "concurrency": 16,
  "dag_id": "example_trigger_target_dag",
  "dag_run_timeout": null,
  "default_view": "grid",
  "description": null,
  "doc_md": null,
  "end_date": null,
  "file_token": ".eJxT0s8vKNFPzCxKy8kvh9OpFYm5BTmp8SmJ6cVwTklRZnp6alF8SWJRemoJSE6voFIJADOyGRw.vE-k8zZfRBEacXoSycU5gDkSXDk",
  "fileloc": "/opt/airflow/airflow/example_dags/example_trigger_target_dag.py",
  "is_active": true,
  "is_paused": false,
  "is_paused_upon_creation": null,
  "is_subdag": false,
  "last_parsed": "2022-06-03T11:07:15.950865+00:00",
  "max_active_runs": 16,
  "max_active_tasks": 16,
  "orientation": "LR",
  "owners": [
    "airflow"
  ],
  "params": {

  },
  "pickle_id": null,
  "render_template_as_native_obj": false,
  "schedule_interval": null,
  "start_date": "2021-01-01T00:00:00+00:00",
  "tags": [
    {
      "name": "example"
    }
  ],
  "timezone": "Timezone('UTC')"
}
```
How does setting the `ScheduleInterval` param to `nullable:true` will be useful?

**Comment by uranusjr** [comment]
From what I understand, the problem is not in the API response, but the generated API _clients_. The response you have above is currently not consumable by an API client. Adding `nullable: true` would allow the clients to handle `"schedule_interval": null` correctly.
