### ISSUE TITLE
Audit rest api update requests

### ISSUE THREAD

**Issue by gmcatsf** [apache/airflow#22352]
### Description

Need a way to monitor updates from rest api, like persisting requests into existing log table.

### Use case/motivation

Airflow UI audit user actions by logging into log table, but this feature is missing in the rest api endpoints. For production this feature is needed to track mis usages or bugs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
`airflow.www.decorators` has `action_logging` method used in different parts of the views for logging. An example of using the decorator in the `patch_connection` endpoint where I modified the description of the connection using rest api.


Id | Dttm | Dag Id | Task Id | Event | Logical Date | Owner | Extra
-- | -- | -- | -- | -- | -- | -- | --
2581 | 2022-04-23, 11:56:53 | None |   | patch_connection |   | test | [('connection_id', 'aws_default')]
