### ISSUE TITLE
'external_trigger' in OpenAPI specs has a default value which as a result, will be always included in the request body by the generated OpenAPI specs

### ISSUE THREAD

**Issue by omarsmak** [apache/airflow#22365]
### Apache Airflow version

2.2.4 (latest released)

### What happened

We have this in the `DAGRun` model:
```
      external_trigger:
          type: boolean
          default: true
          readOnly: true
```
We use the same model for both getting the dagrun details and trigging dagrun. However, since we include a default value, the generated OpenAPI client will include the default value nevertheless during `POST /dags/{dag_id}/dagRuns` which as a result the request will be failed in the validation process on Airflow side since this is a read only property and was set nevertheless by the default value.
For honesty, I am not sure if this shall be an Airflow bug or an OpenAPI generator bug (I think `readOnly` should be respected during  and it should ignore the default value) but in the other hand, I don't really understand why has to be a default value for read only `external_trigger` 🤔 . 
Removing the default value shall fix this issue.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Anything else

If you guys think this can be fixed on Airflow side, I will be happy to provide a PR .

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to fix it.

**Comment by eladkal** [comment]
@omarsmak are you still working on this issue?
