### ISSUE TITLE
AthenaOperator retries max_tries mix-up

### ISSUE THREAD

**Issue by vladyslavnsa** [apache/airflow#22381]
### Apache Airflow version

2.2.4 (latest released)

### What happened

After a recent upgrade from 1.10.9 to 2.2.4, an odd behavior where the aforementioned Attributes, are wrongfully Coupled, is observed.
An example to showcase the issue:
```
AthenaOperator(
    ...
    retries=3,
    max_tries=30,
    ...)
```
Related Documentation states:
* retries: Number of retries that should be performed before failing the task
* max_tries: Number of times to poll for query state before function exits

Regardless of the above specification `max_tries=30`, inspection of related _Task Instance Details_ shows that the Value of both Attributes is **3**

### Operating System

Ubuntu 20.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==3.0.0

### Deployment

Official Apache Airflow Helm Chart

### Anything else

Imagine a Query, executed on an hourly basis, with a varying scope, causing it to 'organically' execute for anywhere between 5 - 10 minutes. This Query Task should Fail after 3 execution attempts.
In such cases, we would like to poll the state of the Query frequently (every 15 seconds), in order to avoid redundant idle time for downstream Tasks.
A configuration matching the above description:
```
AthenaOperator(
    ...
    retry_delay=15,
    retries=3,
    max_tries=40,  # 40 polls * 15 seconds delay between polls = 10 minutes
    ...)
```
When deployed, `retries == max_tries == 3`, thus causing the Task to terminate after 45 seconds
In order to quickly avert this situation where our ETL breaks, we are using the following configuration:
```
AthenaOperator(
    ...
    retry_delay=15,
    retries=40,
    max_tries=40,
    ...)
```
With the last configuration, our Task does not terminate preemptively but will retry **40 times** before failing - which causes an issue with downstream Tasks SLA, at the very least (that is before weighing in the waste of time and operational costs)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you like to fix the problem maybe  by creating a PR @vladyslavnsa ?

**Comment by SamWheating** [comment]
I think that this was introduced in https://github.com/apache/airflow/pull/21018, so its only included in 2.2.4:

Specifically this addition of this line to the TaskInstance constructor:
https://github.com/apache/airflow/blob/d6031f97ab9fd2666cfbcf5a851b26e2ceb010c6/airflow/models/taskinstance.py#L484

It looks like the only operators which use an argument called `max_tries` are the AthenaOperator.

**Comment by eladkal** [comment]
This happens because `AthenaOperator` has [`max_tries`](https://github.com/apache/airflow/blob/fa655fe53dcf34a7b581fe3e881d770921dfc7a0/airflow/providers/amazon/aws/operators/athena.py#L72) parameter which conflicts with the one added in https://github.com/apache/airflow/pull/21018 by @yuqian90 


To fix this we probably need to make a breaking change to `AthenaOperator` and rename the parameter @potiuk WDYT?

**Comment by yuqian90** [comment]
@eladkal `max_tries` is an attribute of `TaskInstance`. #21018 is basically fixing a bug of the web UI to not reset its value by mistake when someone opens the Task instance web page. It's not clear to me how it conflicts with `AthenaOperator` which is a `BaseOperator` instead of `TaskInstance`.

**Comment by gmcrocetti** [comment]
I'm willing to work on it o/. If the way to go is a breaking change, I would like to suggest a more "explicit" naming for such parameter:
`max_polling_attempts` for example - but would love to hear suggestions.
It looks like there are two places with `max_tries`:  [EmrContainerOperator](https://github.com/apache/airflow/blob/46c61ed3e94de1484f5f8f3f2fa74e522d67ba9d/airflow/providers/amazon/aws/operators/emr.py#L162) and [AthenaOperator](https://github.com/apache/airflow/blob/602abe8394fafe7de54df7e73af56de848cdf617/airflow/providers/amazon/aws/operators/athena.py#L72) as previously stated.

**Comment by gmcrocetti** [comment]
@potiuk, WDYT ?

**Comment by potiuk** [comment]
Abslolutely. I think in this case it's technicallly not a breaking change - it's just a bugfix :)  - we apparently  already (unknowingly) introduced a breaking change already (and in Airflow). 

But yeah - I think it's one of the cases where we need to bump the MAJOR version and introduce new parameter.

**Comment by Taragolis** [comment]
Is this argument actually required in this use case? I think BaseOperator have parameter `execution_timeout` for this purpose.

If user want to terminate task after 10 minutes IMHO better set it explicitly, rather than calculate 40 * 15 = 10 min, for example

```
AthenaOperator(
    ...
    sleep_time=15,
    execution_timeout=timedelta(minutes=10)
    ...)
```

Probably better mark deprecate `max_tries` for AthenaOperator and EmrContainerOperator and remove entirely in further releases
