### ISSUE TITLE
Upgrade to FlaskAppBuilder 4.0.*

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22397]
### Body

Flask App Builder 4.0 has been released - including allowing us to bump multiple depending packages that have been held back by it. Apart of bumping version of dependent packages, there does not seem to be breaking changes that impact us directly.

We should migrate to FAB 4.0.*  in Airlfow 2.3 I think at earliest convenience, but it also requires some extensive testing (which 2.3.0 will probably be all about.

https://flask-appbuilder.readthedocs.io/en/latest/breaking.html#version-4-0-0

## Drops python 3.6 support

* Removed config key AUTH_STRICT_RESPONSE_CODES, it’s always strict now.
* Removes Flask-OpenID dependency (you can install it has an extra dependency pip install flask-appbuilder[openid])

Major version bumps on following packages

## Flask from 1.X to 2.X

Breaking changes: https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0

## flask-jwt-extended 3.X to 4.X:

Breaking changes: https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/

## Jinja2 2.X to 3.X

Breaking changes: https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-0

## Werkzeug 1.X to 2.X

https://werkzeug.palletsprojects.com/en/2.0.x/changes/#version-2-0-0

The following packages are probably not impactful to you:

## pyJWT 1.X to 2.X:

Breaking changes: https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-0-0

## Click 7.X to 8.X:

Breaking changes: https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0

## itsdangerous 1.X to 2.X

Breaking changes: https://github.com/pallets/itsdangerous/blob/main/CHANGES.rst#version-200

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by johannesjung** [comment]
Hi @potiuk, thank you for pushing towards upgrading Flask-AppBuilder. I see that you had started to work on this issue in https://github.com/apache/airflow/pull/22587, but then suddenly closed it again. What was the reason for closing the PR and what does it mean for this issue?

**Comment by potiuk** [comment]
This was just a draft to try it and see if it works, It had a number of problems in just "dependencies".
It means that it's not "straightforward" and someone will need to make a substantial effort to migrate (and tests).  

But if you want - you can pick it up and try to make a PR yourself. Woudl you want to take a stab on it ?

**Comment by johannesjung** [comment]
Thanks for the quick reply. It is not my field of expertise, so I would be happy if someone else gives it a try. It would be great to get rid of the older version of dependencies related to this.

**Comment by gmsantos** [comment]
@potiuk I can help by testing it. I have some scenarios that integrate Airflow with Azure AD for authentication and implement custom roles as well.

**Comment by potiuk** [comment]
> @potiuk I can help by testing it. I have some scenarios that integrate Airflow with Azure AD for authentication and implement custom roles as well.

Cool :) Thansl!

Status for everyone:

* I already have a separate PR #24519  that is important prerequisite for the migration (basically changing the library that is used for encryption/verification of log retrieval to more standard one as one of the upgraded dependencies deprecated and removed the class we were used). The good news is that I did it in a much more "standard" way (following JWT standard and pyjwt library using) 

* there is another PR #24516 that should fix incompatibility of authlib library wiht Flask App Builder (I had to refresh docker images as well to fix it for our past Airflow releases #24524 

*  the #24399 is draft PR that I keep on rebasing that I am using to see what's left and extract PRs like above after fixing them there. I already did the following:

   * merged in all the FAB 4.1.1 security manager changes that we need to synchronize every time 
   * I got rid of most of the static MyPy erors (Flask 2 added static check typing that revealed some potential typing issues and MyPy flagged them
 
What is left:

* currently new version of Werkzeug fails with `ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.7/site-packages/werkzeug/security.py)` which I am looking at removing next
* tests are failing (but for now due to Werkzeug, so we do not know yet the real scope)
* provider verification is failing due to conflicts in dependencies - I will look to it at the very end
* docker-compose quick-start tests are failing - those are likely due to some flask failures 
* helm chart tests are failing (same - lilkely flask upgrade problem)

It will take a few days/ week to iterate on all those and slowly fix it one-by-one (but PRs to my PR #24399 are most welcome if anyone would like to take a stab on solving any of the issues there :)

**Comment by potiuk** [comment]
Good news. Static checka are all fixed and now I got to **real** tests to fix.

**Comment by potiuk** [comment]
Hey @dpgaspar - FYI:  we are close to switch to FAB 4.1.1+ (the #24399  is green and we are starting testing it with the help of our users).

**Comment by sainman** [comment]
Hi

We are using Apache-airflow v2.5.1 which is using with Flask-AppBuilder version 4.1.4

A few days back Flask-AppBuilder version 4.1.4 is marked as vulnerable with high severity by dependabot.

Now the problem is Airflow v2.5.1 is not supporting Flask-AppBuilder version 4.3.0 ( any >4.1.4 )

Could any one please suggest what could be the possible solution or timeline Airflow will support Flask-AppBuilder version 4.3.0?

Thanks

**Comment by potiuk** [comment]
> Hi
> 
> We are using Apache-airflow v2.5.1 which is using with Flask-AppBuilder version 4.1.4
> 
> A few days back Flask-AppBuilder version 4.1.4 is marked as vulnerable with high severity by dependabot.
> 
> Now the problem is Airflow v2.5.1 is not supporting Flask-AppBuilder version 4.3.0 ( any >4.1.4 )
> 
> Could any one please suggest what could be the possible solution or timeline Airflow will support Flask-AppBuilder version 4.3.0?
> 
> Thanks

yes. 2.6.0 beta 1 with FAB 4.3.0 has been already published last week, RC1 is expected this week. Please watch the issues/devlist and help us testing the RC1 as soon as it is released, the more people will test it, the faster we will release 2.6.0 final version.

**Comment by sainman** [comment]
thanks, Jarek,

Could you please share the satisfactory link to download beta?

**Comment by potiuk** [comment]
You will find it in devlist. Subscribing to devlist is a good idea https://lists.apache.org/thread/yj1xgz2gfjl0ff329nmdyll9d0ctk7x9
