### ISSUE TITLE
See individual mapped tasks in grid and graph views

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#22409]
Right now, in the grid and graph view, we show mapped tasks like a task group that can't be expanded. One can get a summary of all the mapped tasks: earliest start date, latest end date, overall state, counts of all mapped instance states.

In the task instance details (panel for Grid, modal for Graph): Show a table of all of the mapped instances. The table should have basic sorting and pagination.

API: https://github.com/apache/airflow/pull/22341
Grid UI blocked by: https://github.com/apache/airflow/pull/22123

**Comment by uranusjr** [comment]
Blockers are cleared!
