### ISSUE TITLE
auto refresh Dags home page

### ISSUE THREAD

**Issue by talnagar** [apache/airflow#22418]
### Description

Similar to auto refresh in the DAG page, it would be nice to have this option in the home page as well. 
![image](https://user-images.githubusercontent.com/7373236/159442263-60bbcd58-50e5-4a3d-8d6f-d31a65a6ff81.png)

### Use case/motivation

having an auto refresh at the home page will let users have a live view of running dags and tasks.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by talnagar** [comment]
I'll be happy to implement it myself if you think it's a viable feature.

**Comment by bbovenzi** [comment]
I was saving any rewrite I would do for the future full react ui in `airflow/ui` vs the current `airflow/www`.

But that doesn't mean we couldn't do something for the current UI. I think a start could be to follow the logic in `graph.js` and add autorefresh to `lastDagRunsHandler()` and `taskStatsHandler()` for unpaused dags that have an active dag run.

**Comment by talnagar** [comment]
I'll look at the code and will give it a try

**Comment by potiuk** [comment]
Good luck :)
