### ISSUE TITLE
Migrate Elasticsearch example DAGs to new design

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22445]
There is a new design of system tests that was introduced by the [AIP-47](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests).

All current example dags need to be migrated and converted into system tests, so they can be run in the CI process automatically before releases.

This is an aggregated issue for all example DAGs related to `Elasticsearch` provider. It is created to track progress of their migration.

List of paths to example DAGs:
- [x] airflow/providers/elasticsearch/example_dags/example_elasticsearch_query.py

**Comment by Bowrna** [comment]
@potiuk I will pick this up and try if i could fix it

**Comment by Bowrna** [comment]
@potiuk Could this be updated in the project too? https://github.com/apache/airflow/projects/15

**Comment by potiuk** [comment]
I did

**Comment by potiuk** [comment]
It was automated checks - indeed it seems that the original test is not removed yet :)
