### ISSUE TITLE
Connections import and export should also support ".yml" file extensions

### ISSUE THREAD

**Issue by jackemuk** [apache/airflow#22473]
### Apache Airflow version

2.2.4 (latest released)

### What happened

Trying to export or import a yaml formatted connections file with ".yml" extension fails. 

### What you think should happen instead

While the "official recommended extension" for YAML files is .yaml, many pipeline are built around using the .yml file extension. Importing and exporting of .yml files should also be supported. 

### How to reproduce

Running airflow connections import or export with a file having a .yml file extension errors with:
`Unsupported file format. The file must have the extension .env or .json or .yaml`

### Operating System

debian 10 buster

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
assigned you

**Comment by hankehly** [comment]
@jackemuk @potiuk I will take this if no one minds

**Comment by potiuk** [comment]
Feel free.
