### ISSUE TITLE
CLI command "airflow dags next-execution"  give unexpected results with paused DAG and catchup=False

### ISSUE THREAD

**Issue by frankbreetz** [apache/airflow#22474]
### Apache Airflow version

2.2.2

### What happened

Current time 16:54 UTC
Execution Schedule: * * * * *
Last Run: 16:19 UTC
DAG Paused
Catchup=False

`airflow dags next-execution sample_dag`
returns
```
[INFO] Please be reminded this DAG is PAUSED now.
2022-03-22T16:20:00+00:00
```

### What you think should happen instead

I would expect
```
[INFO] Please be reminded this DAG is PAUSED now.
2022-03-22T16:53:00+00:00
```
To be returned since when you unpause the DAG that is the next executed DAG

### How to reproduce

Create a simple sample dag with a schedule of * * * * * and pause with catchup=False and wait a few minutes, then run 
`airflow dags next-execution sample_dag`

### Operating System

Debian

### Versions of Apache Airflow Providers

Airflow 2.2.2

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by frankbreetz** [comment]
I believe this same issue is showing through the UI, the"next run" on any of the dag views has the same datetime as the 'next-execution' cli command.

**Comment by uranusjr** [comment]
I guess the viable solution would be to add a flag to optionally respect catchup (and perhaps emit a warning when the command is run without the option but with `catchup=False`, to tell the user to explicitly specify the behaviour).

**Comment by potiuk** [comment]
@frankbreetz  - marked it as "good first issue" - so maybe someone can implement it. But maybe you would like to fix it and become contributor?

**Comment by frankbreetz** [comment]
I may need some help, but go ahead and sign me up

**Comment by frankbreetz** [comment]
@uranusjr any preference for the cli flag? I was thinking -r for "respect catchup", but that doesn't seem great

**Comment by frankbreetz** [comment]
Here is a PR (is this the correct way to do this?)

https://github.com/apache/airflow/pull/22666

**Comment by uranusjr** [comment]
I'd not add a short option for now. Short options are overrated and don't need to exist anyway.

**Comment by potiuk** [comment]
> I'd not add a short option for now. Short options are overrated and don't need to exist anyway.

Very much agree. Short options are only for really often used flags that are supposed to be hand-typed and remembered by the users by heart. Can't imagine anyone remembering shorthand for "respect catchup".

**Comment by eladkal** [comment]
@frankbreetz are you still working on the PR?

**Comment by mrmammadov** [comment]
@eladkal @potiuk seems like the issue and PR are both still open. Can I take it over?

**Comment by frankbreetz** [comment]
I won't have time for this anytime soon, feel free to take it over

**Comment by potiuk** [comment]
Assigne you @mrmammadov

**Comment by eladkal** [comment]
@mrmammadov are you still working on this?

**Comment by boushphong** [comment]
Mind if I take-over?

**Comment by mrmammadov** [comment]
@boushphong please go ahead

**Comment by boushphong** [comment]
I created a PR for this issue at: https://github.com/apache/airflow/pull/30117
Do you guys mind taking a look? @eladkal @potiuk . Cheers
