### ISSUE TITLE
DAG is not loading

### ISSUE THREAD

**Issue by camitava** [apache/airflow#22484]
### Apache Airflow version

2.1.3 (Updated by @potiuk  from wrongly specified 2.2.4)

### What happened

I created a DAG file using a python program. Earlier, it was loading in the airflow DAG page and I can trigger the DAG programmatically or manually. Today when I clicked on the DAG, some exception was thrown on the page and nothing further proceeds. 
But this is not happening for all other DAGs listed there. It is happening for only local_job_md DAG. 
The DAG listing -
![image](https://user-images.githubusercontent.com/92978137/159667194-d544f7c4-d6d4-44a4-9761-c546b513dc55.png)
The Error message:
![image](https://user-images.githubusercontent.com/92978137/159667062-265d0856-0d91-4c5c-b3e6-d7bb9bc1efb0.png)

### What you think should happen instead

The DAG should be triggered.

### Operating System

Windows 10

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please upgrade to latest version. Similar issues have been fixed in 2.2* (but there is not a single concrete bug to point at).
