### ISSUE TITLE
Expose `DummyOperator` under the `EmptyOperator` name

### ISSUE THREAD

**Issue by jbylund** [apache/airflow#22490]
### Description

Expose the DummyOperator class under a different name (or move it), to allow consumers to avoid the use of the word `Dummy` in source.

### Use case/motivation

Some projects have language guidelines for avoiding certain words, dummy occasionally shows up on these lists.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jbylund** [comment]
Ahh, thanks for the reference, I did a quick issue search and didn't find anything.  

Looks like people prefer the term `EmptyOperator`, I'll update the title of this issue and see how easy it would be to make a pr (tempted to say it should be reasonably straightforward).

**Comment by eladkal** [comment]
Closing as duplicate of https://github.com/apache/airflow/issues/15994
(I will probably submit a PR for this sometime if no one will do it sooner)
