### ISSUE TITLE
ECS Operator: Realtime container execution logs in Airflow task execution log

### ISSUE THREAD

**Issue by virendhar-aws** [apache/airflow#22512]
### Description

# Objective:
Add functionality to Airflow ECSOperator to capture the task execution logs as they happen from AWS CloudWatch to the ECSOperator's task execution logs.

### Use case/motivation

Present Challenge:
When executing Fargate tasks via ECSOperator the logs are not readily available in Airflow task during execution. The logs are shown after execution and final status of the container execution is reflected in Airflow ECS Operator task logs. As a result one should navigate the task logs in Airflow to get a handle of the container log path in AWS Cloudwatch and then access the log from AWS Cloudwatch in realtime.

The current behavior introduces the following challenges,

The ongoing execution logs are not captured in Airflow task ( ECS Operator ) log. This typically involves couple of additional steps - which can be avoided.
Also for long execution tasks, one has to wait till the task is executed to debug issues if any

# Solution
Mechanism to relay the logs from AWS CloudWatch during execution to Airflow logs as and when they are happening in realtime (or near realtime < 2 mins ).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Hopefully someone will take it - but if you want to make it happen, the fastest and most certain way is to become a contributor and submit it as a PR (which I heartily encourage you to do). That should involve streaming the logs from Fargate (in a similar way we do it for K8S Pod Operator.

**Comment by hankehly** [comment]
It looks like the `EcsTaskLogFetcher` tries to handle this already. I'll test it out myself to see if it works.

https://github.com/apache/airflow/blob/e63f6e36d14a8cd2462e80f26fb4809ab8698380/airflow/providers/amazon/aws/operators/ecs.py#L125-L132

**Comment by hankehly** [comment]
@virendhar-aws Could you check that you're using version 2.3.0 or above?

**Comment by hankehly** [comment]
@virendhar-aws Could you check that you're using `apache-airflow-providers-amazon` 2.3.0 or above?

**Comment by virendhar-aws** [comment]
@hankehly - I noticed this on an earlier version Airflow 2.0.0. Let me verify the same on a recent version later this week.

**Comment by shubham22** [comment]
@virendhar-aws - could you confirm if you were able to verify this? If yes, we should close this ticket.

**Comment by potiuk** [comment]
Closing. We can always reopen if we find it's not fixed
