### ISSUE TITLE
sla_miss.execution_date is incorrect for daily dagruns

### ISSUE THREAD

**Issue by KulykDmytro** [apache/airflow#22532]
### Apache Airflow version

2.2.4 (latest released)

### What happened

When inspecting metadata in airflow tables about sla stuff found that
* in case of daily DAG's schedule `execution_date` attribute for `sla_miss` is filled with unexpected value. Seems like `data_interval_end`
![image](https://user-images.githubusercontent.com/34435869/160171043-13db4ae4-4166-4638-a2bc-504e48013ffe.png)
* in case of hourly schedule `sla_miss.execution_date` are as expected (equals to DAGRun's `data_interval_start`/`logical_date`/`execution_date`)
![image](https://user-images.githubusercontent.com/34435869/160171322-ddd327fd-c82e-4149-a9bd-1a9e6b2dfc97.png)
<img width="939" alt="image" src="https://user-images.githubusercontent.com/34435869/160172266-357cab52-0718-4d92-a59c-2f3793e3d9b2.png">

this prevents to create any custom SLA analisys dashboards/metrics because unable to join `sla_miss` and `dag_run`/`task_instance` in direct and clear way

clicking on daily task's link on SLA Miss dashboard forwarding to task instance which was never executed (because it is in "future") and have no runtime metrics in `Task instance details`

All screenshots are taken @ 2022-03-25 17:xx:xx Z
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/34435869/160170309-ba527b6f-dd4d-4244-b3aa-53a907d62a37.png">

### What you think should happen instead

`sla_miss.execution_date` should be same as `dag_run.execution_date` in all cases

### How to reproduce

setup a dag with any  daily schedule
setup an SLA on task
wait `sla miss` to trigger
observe in `SLA Miss` dashboard - incorrect incorrect execution date

### Operating System

amazon linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
SLA feature is genreally broken in many ways and need to be completely rewritten. I think there is no point to fix it

**Comment by uranusjr** [comment]
We should advertise 2.4 as “SLA now actually works!”

**Comment by potiuk** [comment]
> We should advertise 2.4 as “SLA now actually works!”

Providing that we will fix it :)

**Comment by sarinarw** [comment]
Bumping this as we're also experiencing this and it seems to align with data interval end here as well.

**Comment by argibbs** [comment]
@uranusjr @potiuk Can I check if the above is tongue in cheek, or if there is a rewrite of SLAs planned for 2.4(.x)?

I'm hitting an issue in 2.3.3 with SLAs preventing processing of the dags (similar to #15596 which I raised a while back - the way in which it fails has changed, but the behaviour is the same; dags don't get recreated, etc. etc.)

I ask because I'm trying to judge whether I should write SLAs off in 2.3.3 and try again in 2.4, or if it's worth putting effort in to work out what's going wrong...

**Comment by argibbs** [comment]
Ok, I got nerd sniped, and dug into it anyway, and now have a reasonable idea of how I might fix it.

So, the question still stands: is it worth me attempting to patch this locally for myself (and then raising the change as an MR if successful) or is this pointless since it's already being worked on?

**Comment by potiuk** [comment]
> @uranusjr @potiuk Can I check if the above is tongue in cheek, or if there is a rewrite of SLAs planned for 2.4(.x)?
> 
> I'm hitting an issue in 2.3.3 with SLAs preventing processing of the dags (similar to #15596 which I raised a while back - the way in which it fails has changed, but the behaviour is the same; dags don't get recreated, etc. etc.)
> 
> I ask because I'm trying to judge whether I should write SLAs off in 2.3.3 and try again in 2.4, or if it's worth putting effort in to work out what's going wrong...

If you have smple fix that is easy to review you can make a PR fixing it. Happy to review. For now no-one works on rewritinug SLA as far as I know and it is unlikely to happen in 2.4. You can also see discussion I started on it - https://lists.apache.org/thread/h10l2d8l4mkrfm68ns58m0rgq5x63m8g - seems like everyone agrees SLA is broken, but there is not enough will (or courage maybe ?) to deprecate it nor incentive to rewrite it, So we are a bit in a limbo - and anything you might want to improve there with very little cost is welcome. 

Feel free also to chime in the discussion if you have strong feelings about it @argibbs - I think more stronger voices are needed if we want to improve the situation a bit more than just patch here or there (or maybe by patching it here and there we might get it to a usable state - who knows :) ?

**Comment by potiuk** [comment]
Actully - If you are much into it and REALLY want to dig into it and see if you can incrementally improve it - I think that might be a super-valuable contribution to the community :). So if you have the will, I am happy to help with reviews and comments :). Just ping me in the PRs.
