### ISSUE TITLE
@task and chain() don't play well together

### ISSUE THREAD

**Issue by ferruzzi** [apache/airflow#22594]
### Apache Airflow version

main (development)

### What happened

I've been told that the current community preference is to use an @task decorated method instead of the Python Operator when possible, but the chain() method does not support that yet. `ci_install_and_test_provider_packages.sh` will fail with the following message:

```
File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1578, in chain 
up_type=type(up_task), down_type=type(down_task)

TypeError: Chain not supported between instances of <class 'airflow.models.xcom_arg.XComArg'> 
and <class 'airflow.models.xcom_arg.XComArg'>
```

### What you think should happen instead

Might be as simple as adding the Typing to the chain() signature?

### How to reproduce

see [this example DAG](https://github.com/apache/airflow/blob/012beeb04271e58f5c2750f3ff9332fdaecb50e9/airflow/providers/amazon/aws/example_dags/example_hive_to_dynamodb.py)

In case that isn't persistent, this should do it as well:

```
from datetime import datetime

from airflow import DAG
from airflow.decorators import task
from airflow.models.baseoperator import chain


@task
def echo1():
    print('hello')


@task
def echo2():
    print('world')


with DAG(
    dag_id='example_dag',
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    tags=['example'],
    catchup=False,
) as dag:
    
    chain(echo1(), echo2())

```

### Operating System

linux

### Deployment

Docker-Compose

### Deployment details

I am running it in an updated Breeze environment and it passes all test there; this does not fail until the CI tests on github run `/opt/airflow/scripts/in_container/run_install_and_test_provider_packages.sh`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ferruzzi** [comment]
Willing to do the PR on this, but I have my next couple of issues lined up.  This seems like it should be an easy first commit for someone; if someone else gets to it before I do, then great.

**Comment by potiuk** [comment]
Assigned you :)

**Comment by josh-fell** [comment]
FWIW this only seems to be an issue on `main`. I confirmed you can use `chain()` with TaskFlow functions in 2.2.4 and 2.2.5rc2. This functionality was introduced with #16732. I also wonder why the unit tests aren't failing though.

**Comment by ferruzzi** [comment]
In case the unit tests passing locally are a Layer 8 issue, my testing procedure before pushing is to run `pre-commit run --all-files` then `./scripts/ci/testing/ci_run_airflow_testing.sh`.  Currently also running `./breeze build-docs -- --package-filter apache-airflow-providers-amazon` since I'm working on AWS docs and sample dags, but the first two always run and they pass just fine.

**Comment by josh-fell** [comment]
Actually, I can get the example in this issue and `example_hive_to_dynamodb` DAG to parse just fine locally with `main` as well using Breeze.

@ferruzzi Is this what you are seeing as well?

**Comment by ferruzzi** [comment]
Yeah, locally in Breeze no issue at all.  It's when I put in [the PR](https://github.com/apache/airflow/pull/22517) that it fails:   https://github.com/apache/airflow/runs/5726300574?check_suite_focus=true

**Comment by ferruzzi** [comment]
I'm about to rebase that PR because there is a static check failing that I don't think is my chanrge, so in case those tests results go away, the stack trace in the message is:

```
Good version of docker 20.10.11.
Running 'ci_install_and_test_provider_packages.sh'

Using pulled cache strategy for the build.

Check if CI image build is needed
docker run -v /home/runner/work/airflow/airflow/files:/files -v /home/runner/work/airflow/airflow/dist:/dist --rm --env-file /home/runner/work/airflow/airflow/scripts/ci/docker-compose/_docker.env -t -v /home/runner/work/airflow/airflow/setup.py:/airflow_sources/setup.py:cached -v /home/runner/work/airflow/airflow/setup.cfg:/airflow_sources/setup.cfg:cached -v /home/runner/work/airflow/airflow/airflow/__init__.py:/airflow_sources/airflow/__init__.py:cached -v /home/runner/work/airflow/airflow/empty:/opt/airflow/airflow:cached -v /home/runner/work/airflow/airflow/scripts/in_container:/opt/airflow/scripts/in_container:cached -v /home/runner/work/airflow/airflow/dev/import_all_classes.py:/opt/airflow/dev/import_all_classes.py:cached -e SKIP_ENVIRONMENT_INITIALIZATION=true ghcr.io/apache/airflow/main/ci/python3.7:012beeb04271e58f5c2750f3ff9332fdaecb50e9 /opt/airflow/scripts/in_container/run_install_and_test_provider_packages.sh 
Verify parameters passed
Install Airflow as specified
Install provider packages
Import all Airflow classes
There were errors when importing Providers!
This test is run to check Provider's compatibility with Airflow 2.1.0
So this error might mean that your providers are not Airflow 2.1.0 compatible

Detailed errors:

----------------------------------------
Exception when importing: airflow.providers.amazon.aws.example_dags.example_hive_to_dynamodb


Traceback (most recent call last):
  File "/opt/airflow/dev/import_all_classes.py", line 90, in import_all_classes
    _module = importlib.import_module(modinfo.name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name, package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/example_dags/example_hive_to_dynamodb.py", line 137, in <module>
    delete_dynamodb_table,
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1578, in chain
    up_type=type(up_task), down_type=type(down_task)
TypeError: Chain not supported between instances of <class 'airflow.models.xcom_arg.XComArg'> and <class 'airflow.models.xcom_arg.XComArg'>

----------------------------------------

########################################################################################################################
 [IN CONTAINER]   EXITING /opt/airflow/scripts/in_container/run_install_and_test_provider_packages.sh WITH EXIT CODE 1  
########################################################################################################################



ERROR: The previous step completed with error. Please take a look at output above 

###########################################################################################
                   EXITING WITH STATUS CODE 1
###########################################################################################

Finished the script ci_install_and_test_provider_packages.sh
Elapsed time spent in the script: 59 seconds
Exit code 1
```

**Comment by potiuk** [comment]
AAAAAAAH! It fails because we check all providers for Airflow 2.1 compatibility !!! And Apparently chain support for taskflow was aded in 2.2 ! 

So yeah >> is good for now. We do not want 2.1 users to give examples that they will use for 2.1 installation in the provider that is 2.1 compliant! 

Actually our 2.1 importability check worked like a charm!

**Comment by ferruzzi** [comment]
Alright, after a chat with Jarek, this is a non-issue.   The part I was missing was that chain() currently supports @task but did not in 2.1;  providers require 2.1 compatibility so the CI testing failed on the backward compatibility checks.
