### ISSUE TITLE
Helm values nameOverride and fullnameOverride are not p

### ISSUE THREAD

**Issue by evanrosebrook** [apache/airflow#22622]
### Official Helm Chart version

1.5.0 (latest released)

### Apache Airflow version

2.2.4 (latest released)

### Kubernetes Version

1.21

### Helm Chart configuration

In your values.yaml you can specify fullnameOverride or nameOverride. Neither is added to the names of the Deployment objects created.

# Provide a name to substitute for the full names of resources
fullnameOverride: "whatever"

# Provide a name to substitute for the name of the chart
nameOverride: "whatever"

Generated names will look like:

airflow-scheduler-c48f6d677-zc72b
airflow-webserver-7b6fc468fb-xq86l

In this example "airflow" is the release name. 

If fullnameOverride is set it should take precedence and the name should look like:

whatever-scheduler-c48f6d677-zc72b
whatever-webserver-7b6fc468fb-xq86l

If nameOverride is set and fullnameOverride is set then the name should be included with the release name. For example:

airflow-whatever-scheduler-c48f6d677-zc72b
airflow-whatever-webserver-7b6fc468fb-xq86l

### What happened

When setting name overrides, the deployment objects do not include the overrides in deployment objects

### What you think should happen instead

Deployment objects should include the name overrides.

### How to reproduce

Set nameOverride or fullnameOverride and deploy to a cluster. Inspect your Deployments and find that the name is based on .Release.Name without including overrides.

### Anything else

The template function that should be used has already been added to _helpers.yaml: https://github.com/apache/airflow/blob/9e66d14dc1212e54c0eb22cc43a1eee764a8fed8/chart/templates/_helpers.yaml#L23

Someone just needs to go through the various *-deployment.yaml files and update the name to use the template function.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gerardo-garcia** [comment]
This issue is still valid. The helper template in `airflow/chart/templates/_helpers.yaml` already defines "airflow.fullname". It's just a matter of changing all references to `.Release.name` to use the template function `{{ include "grafana.fullname" . }}`.
Would it be possible to reopen it?
