### ISSUE TITLE
GCSToGCSOperator cannot copy a single file/folder without copying other files/folders with that prefix   

### ISSUE THREAD

**Issue by Yao-ATG** [apache/airflow#22675]
### Apache Airflow Provider(s)

google

### Apache Airflow version

2.2.4 (latest released)

### Operating System

MacOS 12.2.1

### Deployment

Composer

### What happened

I have file "hourse.jpeg" and "hourse.jpeg.copy" and a folder "hourse.jpeg.folder" in source bucket.
I use the following code to try to copy only "hourse.jpeg" to another bucket.
 gcs_to_gcs_op = GCSToGCSOperator(
        task_id="gcs_to_gcs",
        source_bucket=my_source_bucket,
        source_object="hourse.jpeg",
        destination_bucket=my_destination_bucket
    )

The result is the two files and one folder mentioned above are copied.
From the source code it seems there is no way to do what i want.

### What you think should happen instead

Only the file specified should be copied, that means we should treat source_object as exact match instead of prefix.
To accomplish the current behavior as prefix, the user can/should use wild char
    source_object="hourse.jpeg*"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
See the documentation (docstring) where you can have examples.

As unitutitive as it is, source_object is a wildcard specification by default. If you want to copy single object you need specify it like that: 

```
source_objects = [ 'your_object' ] 
```

See examples here: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/transfers/gcs_to_gcs/index.html

**Comment by potiuk** [comment]
I see I looked at the code and ideed. I marked it as good first issue and maybe someone woudl like to work on it.

Note that the fastest and surest way to get it implemented is if you make a PR yourself and lead it to completion. Would you like to contribute such a change ? Happy to review the code. If not then ti will have to wait for someone to pick it up.

**Comment by Yao-ATG** [comment]
Before anybody try to fix it, can we clarify the expected behavior?

Let's limit the discussion only on objects without wild char.
The current behavior is to treat the object as a prefix, no matter specified in source_object or source_objects.
My expected behavior is to treat object as exact match, also no matter specified in source_object or source_objects, and let users to add wildchar if they want the current result.
Maybe the intended behavior is to treat source_object as prefix and source_objects as exact match?

**Comment by potiuk** [comment]
I think that can be discussed when PR is opened. I have no opinion. Maybe you can pick something as a proposal, and the reviewer reviewing the PR migh decide which one is ok.

**Comment by potiuk** [comment]
For sure it shoudl be backwards compatible ideally though.

**Comment by potiuk** [comment]
I think flag with "exact_match_when_no_wildcard" might be a solution.

**Comment by spatocode** [comment]
@potiuk I'll be picking this up

**Comment by potiuk** [comment]
Assigned you!
