### ISSUE TITLE
HDFS provider causes TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22689]
### Discussed in https://github.com/apache/airflow/discussions/22301

<div type='discussions-op-text'>

<sup>Originally posted by **frankie1211** March 16, 2022</sup>
I build the custom container image, below is my Dockerfile.

```dockerfile
FROM apache/airflow:2.2.4-python3.9
USER root
RUN apt-get update \
        && apt-get install -y gcc g++ vim libkrb5-dev build-essential libsasl2-dev \
        && apt-get autoremove -yqq --purge \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --upgrade pip
RUN pip install apache-airflow-providers-apache-spark --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.9.txt
RUN pip install apache-airflow-providers-apache-hdfs --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.9.txt"
```

But i got the error when i run the container

```
airflow-init_1       | The container is run as root user. For security, consider using a regular user account.
airflow-init_1       | ....................
airflow-init_1       | ERROR! Maximum number of retries (20) reached.
airflow-init_1       |
airflow-init_1       | Last check result:
airflow-init_1       | $ airflow db check
airflow-init_1       | Traceback (most recent call last):
airflow-init_1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-init_1       |     from airflow.__main__ import main
airflow-init_1       |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 28, in <module>
airflow-init_1       |     from airflow.cli import cli_parser
airflow-init_1       |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 621, in <module>
airflow-init_1       |     type=argparse.FileType('w', encoding='UTF-8'),
airflow-init_1       | TypeError: __init__() got an unexpected keyword argument 'encoding'
airflow-init_1       |
airflow_airflow-init_1 exited with code 1
```
</div>

**Comment by uranusjr** [comment]
The `encoding` argument is there since Python 3.4, so this seems to indicate there’s something very wrong with the Python installation (either CPython as a whole, or the `argparse` module specifically).

https://docs.python.org/3/library/argparse.html#argparse.FileType

**Comment by potiuk** [comment]
I think we know the problem already. https://pypi.org/project/snakebite-py3/  which is the dependency of hdfs has this as dependencies:

```
install_requires = [
    'protobuf>2.4.1',
    'argparse'
]
```

Which means that it pulls the "argparse" project from PyPI.

It is so old, that even the simple json interface does not show the dependency - we had to look it up in setup.py. 

I think the only possibility is to vendor-in the snakebite-py3 code.

**Comment by uranusjr** [comment]
Judging from activity in the snakebite-py3 repository I guess it’s best to fork it (or vendoring).

**Comment by Taragolis** [comment]
I tried to build Docker image with HDFS provider on 2.5.1, it is installed and Airflow started without any problem.
I believe that in some circumstances it is possible that `argparse` from pypi might use instead of builtin and as result it broke something (or everything).

Also I think this Hook not supported and maintained well even before Airflow 2.

https://github.com/apache/airflow/blob/264ace5f86e560d09444b833556074363b055f81/airflow/providers/apache/hdfs/hooks/hdfs.py#L57-L62

Maybe we should discontinue and remove this hook (and related operators) due to lack of modern packages and contributors? We still have WebHDFSHook as alternative

WDYT?

**Comment by potiuk** [comment]
It also worked for me in venv. 

I would say - let's leave it it, and close the issue and add documentation on how to get rid of the problem when it appears (remove argparse). This seems like very isolated issue and even if argparse is installed it can be circumvented by `pip uninstall argparse`.

**Comment by potiuk** [comment]
This is what #29614 does.

**Comment by potiuk** [comment]
@Taragolis  Some discussions on our slack led me to conclusion that we should indeed remove HDFS hook.

**Comment by potiuk** [comment]
https://apache-airflow.slack.com/archives/CCPRP7943/p1677834257579739
