### ISSUE TITLE
dbt Cloud Provider only works for Multi-tenant instances

### ISSUE THREAD

**Issue by ernestoongaro** [apache/airflow#22730]
### Apache Airflow Provider(s)

dbt-cloud

### Apache Airflow version

2.2.5 (latest released)

### Operating System

any

### Deployment

Official Apache Airflow Helm Chart

### What happened

   Some dbt Cloud deployments require the setting of a different base URL (could be X.getdbt.com) or cloud.X.getdbt.com) 

Relevant line: https://github.com/apache/airflow/blame/436c17c655494eff5724df98d1a231ffa2142253/airflow/providers/dbt/cloud/hooks/dbt.py#L154
   
       self.base_url = "https://cloud.getdbt.com/api/v2/accounts/"

### What you think should happen instead

A runtime paramater that defaults to cloud.getdbt 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@ernestoongaro All yours!

**Comment by sungchun12** [comment]
@epapineau FYI

**Comment by epapineau** [comment]
I'd like to tackle this issue 🧑‍💻

**Comment by ernestoongaro** [comment]
@epapineau great! all yours

**Comment by ernestoongaro** [comment]
@josh-fell could you assign @epapineau to this issue?

**Comment by potiuk** [comment]
Assigned you @epapineau

**Comment by spetrescu** [comment]
Hello. 

Would replacing 
```
 self.base_url = "https://cloud.getdbt.com/api/v2/accounts/"
 ```
 with 
 ```
  self.base_url = "https://cloud.getdbt.com"
  ```
  fix the issue? 
  
  If not, from where can we fetch the setting of `cloud.getdbt`? Any hints?
