### ISSUE TITLE
Fix the order that tasks are displayed in Grid view

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#22731]
The order that tasks are displayed in Grid view do not correlate with the order that the tasks would be expected to execute in the DAG. See `example_bash_operator` below:

<img width="335" alt="Screen Shot 2022-04-04 at 11 47 31 AM" src="https://user-images.githubusercontent.com/4600967/161582603-dffea697-68d9-4145-909d-3240f3a65ad2.png">
<img width="426" alt="Screen Shot 2022-04-04 at 11 47 36 AM" src="https://user-images.githubusercontent.com/4600967/161582604-d59885cc-2c71-4a7d-b332-e439115d8c4c.png">

We should update the [task_group_to_tree](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L232) function in views.py to better approximate the order that tasks would be run.

**Comment by eladkal** [comment]
i wonder if https://github.com/apache/airflow/issues/13044 share same root cause?

**Comment by ashb** [comment]
@eladkal Nope, that's purely an artefact of the chart/graphing libary we are using on the front end as expanding the collapsed TG doesn't request any new data -- it's already there in the `nodes` JS var
