### ISSUE TITLE
Grid view details shows `_PythonDecoratedOperator` instead of `@task.python`

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#22762]
### Apache Airflow version

main (development)

### What happened

I ran a dag and navigated to the details drawer in the grid view.  Saw this:

<img width="358" alt="Screen Shot 2022-04-05 at 12 49 03 PM" src="https://user-images.githubusercontent.com/5834582/161830203-60b79ff7-3984-4c8b-b010-efd0bd6470d3.png">

### What you think should happen instead

The class name was descriptive enough, but it's not a class I had ever directly referenced.  It would be easier for me to correlate this detail with my code if `@task` showed up somewhere in whatever is displayed.

### How to reproduce

Run any dag with task decorators, view details about those task instances

### Operating System

Mac OS 12.3.1

### Deployment

Virtualenv installation

### Deployment details

installed via `pip install ~/src/airflow` cloned at 34154803a
ran via `airflow webserver`

### Anything else

I'm under the impression that a new endpoint might be needed to expose friendlier operator descriptions.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatrixManAtYrService** [comment]
@bbovenzi FYI

**Comment by eladkal** [comment]
This is issue I raised in Slack a while ago:
https://apache-airflow.slack.com/archives/CCPRP7943/p1644846308701199

**Comment by uranusjr** [comment]
Maybe we could override `task_type` for this. I did a quick search and it seems this is only used for UI presentation now (need to double check).

**Comment by norm** [comment]
Would it not be easier to *add* the operator name to the API results?

**Comment by bbovenzi** [comment]
Yeah, there's a few UI only things we could probably also get rid of at the same time. But I think `task.operator` would be easiest to understand for anyone using the API

**Comment by norm** [comment]
Looking into this, and I'm not sure what we are looking for to replace `_PythonDecoratedOperator` if it is not the task's ID? If it is that, it is already in the API results.

**Comment by eladkal** [comment]
It should not be the task_id. it should be the Operator class name..
`_PythonDecoratedOperator` should become `PythonOperator`

**Comment by eladkal** [comment]
True but we probably can distinguish.
Decorators also inherit from `DecoratedOperator`.

> It’d be easier if we let the class implement what they want the API/UI to display for it.

yeah maybe it's prefered. We can set in `BaseOperator` something like:

    def get_operator_ui_name_(self):
        return self.__class__.__name__
       
 and specific operators that need to change the name can override this method.

**Comment by ashb** [comment]
> Maybe we could override `task_type` for this. I did a quick search and it seems this is only used for UI presentation now (need to double check).

Task type is also used for metrics form DagRun creation:

```python
                Stats.incr(f"task_instance_created-{task_type}", count)
```

But I'd probably argue that the current value is as "wrong" there as it is in the UI.

**Comment by bbovenzi** [comment]
Just heads up, this isn't just the API endpoint used by Grid view. Here is the same issue in Graph view:

<img width="1115" alt="Screen Shot 2022-04-07 at 4 43 59 PM" src="https://user-images.githubusercontent.com/4600967/162295951-488b3984-28c6-4714-b2c4-02dc2ff7f268.png">
