### ISSUE TITLE
Paused DAG manual running task has no external_ executor_ id

### ISSUE THREAD

**Issue by wangzhijunwang** [apache/airflow#22779]
### Apache Airflow version

2.1.4

### What happened

When we have a simple DAG and execute the  `sleep command` to keep running, if we pause the DAG first and manually clear a task, it will not run at this time. Now let's run the task directly manually. The status of the task is running and the status of the whole DAG is queued. Now, the operation that causes the bug comes. Unpause the dag and the scheduler log will report

```
2022-04-06 11:39:34,250] {scheduler_job.py:1283} INFO - Reset the following 1 orphaned TaskInstances:

<TaskInstance: dag. test 2022-04-04 16:00:00+00:00 [running]>
```

Found field  `external_executor_id`  in  table `task_instance`  is empty, resulting in adopt_ or_ reset_ orphaned_ Tasks cannot be used correctly

The above case is just a simple reproduction of the problem. This problem occasionally occurs during the operation of our complex formal tasks. Usually, the error is reported as follows

```
[2022-04-02 19:22:19,365] {local_task_job.py:209} WARNING - 
State of this instance has been externally set to None. Terminating instance.
```

### What you think should happen instead

Running tasks are not reset

### Operating System

celery executor  |  k8s

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tanelk** [comment]
I tried, but could not reporduce this.

For me the `external_executor_id` was filled and the adoption worked as intended.

Just to be sure - by "run the task directly manually" did you mean through web UI? or with CLI?

I was running 2.2.4 instead of 2.1.4, perhaps you could try newer release - the issue might be fixed.

**Comment by wangzhijunwang** [comment]
@tanelk 
Sorry to bother you again!
First, I use the Web UI to operate，And the example of my operation this time comes from https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html

![res](https://user-images.githubusercontent.com/65493688/162871426-c0e0ef38-908c-47f4-8f83-8646b98828bb.png)

By upgrading to version 2.2.4, I did find that running task external external_executor_id was filled, but version 2.1.4 external_executor_id is empty

**Comment by tanelk** [comment]
Did I understand correctly - in 2.2.t the external_executor_id is filled, but the issue still there?

**Comment by wangzhijunwang** [comment]
There is no problem with the issue in version 2.2.4
