### ISSUE TITLE
UI bug in recent chromium when search for a variable

### ISSUE THREAD

**Issue by parisni** [apache/airflow#22774]
### Apache Airflow version

2.2.4

### What happened

in the "variable" menu, when I search for a pattern, then it does not work

In debug mode I get : 
```
Form submission failed, as the <SELECT> element named '' was implicitly closed by reaching the end of the file. Please add an explicit end tag ('</SELECT>')
```

### How to reproduce

- install chromium `Version 102.0.4976.0 (Official Build) unstable (64-bit)`
- search for a variable

### Operating System

ubuntu 20

### Versions of Apache Airflow Providers

2.2.4

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Is this in `/variable/list` and when searching for a key/val? I'm trying to replicate.

<img width="607" alt="Screen Shot 2022-04-06 at 8 29 02 AM" src="https://user-images.githubusercontent.com/4600967/161974625-116b1a32-5ccb-4170-9916-8019b7a33134.png">

**Comment by parisni** [comment]
Indeed, thanks

**Comment by bbovenzi** [comment]
@parisni Could you add a screenshot of the filter you are trying to apply?
