### ISSUE TITLE
Helm deployment fails when postgresql.nameOverride is used

### ISSUE THREAD

**Issue by evanrosebrook** [apache/airflow#22790]
### Apache Airflow version

2.2.5 (latest released)

### What happened

Helm installation fails with the following config:

``` 
postgresql:
  enabled: true
  nameOverride: overridename
```

The problem is manifested in the `-airflow-metadata` secret where the connection string will be generated without respect to the `nameOverride`

With the example config the generated string should be:

`postgresql://postgres:postgres@myrelease-overridename:5432/postgres?sslmode=disable`

but the actual string generated is:
`postgresql://postgres:postgres@myrelease-overridename.namespace:5432/postgres?sslmode=disable`

### What you think should happen instead

Installation should succeed with correctly generated metadata connection string

### How to reproduce

To reproduce just set the following in values.yaml and attempt `helm install`

``` 
postgresql:
  enabled: true
  nameOverride: overridename
```

### Operating System

Ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

using helm with kind cluster

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think this is already known and handle in the upcoming version of the chart https://github.com/apache/airflow/pull/22676

**Comment by evanrosebrook** [comment]
Actually this is a different issue. [22676](https://github.com/apache/airflow/pull/22676) deals with nameOverride for the airflow chart. 

This issue deals with using nameOverride in the postgres sub-chart. For the postgresql chart nameOverride works fine, however the connection string that gets created in the airflow parent does not use the overriden postgres host when generating the connection string and so the deployment fails.

**Comment by evanrosebrook** [comment]
This issue can be worked around by setting a value for the metadataConnection.host that matches the postgresql.nameOverride. However, I wouldn't think the chart should remain deployable while specifying only the postgresql nameOverride.

```
postgresql:
  enabled: true
  nameOverride: {{ .Release.Name }}-someName
data:
  metadataConnection:
    host: someName
```

**Comment by potiuk** [comment]
would you like to provide a fix?

**Comment by amoghrajesh** [comment]
@potiuk @evanrosebrook saw that this issue has been idle for sometime. Can I pick it up?

**Comment by potiuk** [comment]
sure.

**Comment by amoghrajesh** [comment]
Thanks @potiuk. I have attached a pull request for this: https://github.com/apache/airflow/pull/29214
cc @evanrosebrook

**Comment by eladkal** [comment]
resolved in https://github.com/apache/airflow/pull/29214
