### ISSUE TITLE
JiraTicketSensor duplicates TaskId

### ISSUE THREAD

**Issue by kostiantyn-lab** [apache/airflow#22810]
### Apache Airflow Provider(s)

jira

### Versions of Apache Airflow Providers

apache-airflow-providers-jira==2.0.1

### Apache Airflow version

2.2.2

### Operating System

Amazon Linux 2

### Deployment

MWAA

### What happened

I've been trying to use the Jira Operator to create a Ticket from Airflow and use the JiraTicketSensor to check if the ticket was resolved. Creating the task works fine, but I can't get the Sensor to work.

If I don't provide the method_name I get an error that it is required, if I provide it as None, I get an error saying the Task id has already been added to the DAG.

```text
Broken DAG: [/usr/local/airflow/dags/jira_ticket_sensor.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 553, in __init__
    task_group.add(self)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 175, in add
    raise DuplicateTaskIdFound(f"Task id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'jira_sensor' has already been added to the DAG
```

### How to reproduce

use this dag

```python
from datetime import datetime

from airflow import DAG
from airflow.providers.jira.sensors.jira import JiraTicketSensor

with DAG(
    dag_id='jira_ticket_sensor',
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    catchup=False
) as dag:
    jira_sensor = JiraTicketSensor(
        task_id='jira_sensor',
        jira_conn_id='jira_default',
        ticket_id='TEST-1',
        field='status',
        expected_value='Completed',
        method_name='issue',
        poke_interval=600
    )
```

### Anything else

This error occurs every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kianelbo** [comment]
I opened a PR according to what @potiuk explained. This is my first ever contribution and I would really appreciate it if you take a look at it and give your feedbacks.

**Comment by kostiantyn-lab** [comment]
> I opened a PR according to what @potiuk explained. This is my first ever contribution and I would really appreciate it if you take a look at it and give your feedbacks.

@kianelbo I've found error in your patch
```
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base.py", line 234, in execute
    while not self.poke(context):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow_contrib/sensors/jira.py", line 110, in poke
    return JiraSensor.poke(self, context=context)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/jira/sensors/jira.py", line 64, in poke
    return self.result_processor(context, jira_result)
TypeError: issue_field_checker() takes 2 positional arguments but 3 were given
```

I see two ways to fix it
1. Add `context: Dict` as parameter to `def issue_field_checker(self, issue: Issue) -> Optional[bool]`
2. Remove `context` parameter from the `return self.result_processor(context, jira_result)`

**Comment by kianelbo** [comment]
I'm embarrassed... I hope https://github.com/apache/airflow/pull/23352 does the trick.

> I see two ways to fix it

I decided to go with the second solution since github sensor and arangodb operator are written in a similar way.
