### ISSUE TITLE
Breeze: Provider package documentation integration with Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22825]
We have "Prepare provider documentation" action in Breeze that builds the documentation via running appropriate Python script and passing appropriate parameters. 

It shoudl be added to the new Breeze.

**Comment by Bowrna** [comment]
@potiuk Could i pick up this issue?

**Comment by potiuk** [comment]
IMa just aboput to submit a big change covering those all issues that I assigned to myself :)

**Comment by Bowrna** [comment]
oh ok, @potiuk Let me know if you need anything. I can join in finishing this part too :)
Could you move other Breeze tasks in project to `Ready to pick` section so that I can pick any other task?
