### ISSUE TITLE
UUID encoded in CassandraToGCSOperator but not other operators

### ISSUE THREAD

**Issue by fuxiao224** [apache/airflow#22846]
### Apache Airflow version

2.2.5 (latest released)

### What happened

I noticed that UUID is encoded in CassandraToGCSOperator by:

`elif isinstance(value, UUID):
            return b64encode(value.bytes).decode('ascii')`

Therefore, for example, UUID 000e0000-5719-12a3-0000-000028327d4a is represented as "AA4AAFcZEqMAAAAAKDJ9Sg==". However, this seems inconsistent with other *TOGCSOperators. For example, UUID in MySQL/oracle is represented as  a UTF8 string of five hexadecimal numbers in format "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", so in the previous example, UUID 000e0000-5719-12a3-0000-000028327d4a would still be represented as "UUID 000e0000-5719-12a3-0000-000028327d4a". Therefore, when using MySQLToGCSOperator/OracleToGCSOperator, UUID will preserve as "UUID 000e0000-5719-12a3-0000-000028327d4a" format, which is not encoded.

Thus, I wonder what is the main concern of encoding UUID in CassandraToGCSOperator, and if possible, can we change it to not encoding UUID when loading Cassandra table to GCS using Airflow? Please let me know your thoughts about this issue. Thanks!

### Operating System

macOS

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
According to #3483, this was done because 

> issue with UUID type conversion: currently UUID is converted to hex string, but should be converted to base64-encoded as that is the required format in BigQuery for uploading.

If this description is taken at face value, the format you proposed would not work? I am not familiar with Google services to provide more information, unfortunately.

**Comment by fuxiao224** [comment]
Thanks! @uranusjr 
This PR was opened 4 years ago, I'm not sure if this was a BigQuery rule at that time, but I don't think base64-encoded UUID format is a requirement for BigQuery at this point.

**Comment by fuxiao224** [comment]
I wonder if there's any other concerns if I revert #3483 CassandraToGCSOperator part to convert UUID to hex string, instead of base64-encoded format? Thanks!

**Comment by uranusjr** [comment]
cc @jgao54 in case you know some more details on this.

**Comment by potiuk** [comment]
Yeah. Adding parameter willl be a good solution.

**Comment by fuxiao224** [comment]
Thanks for your suggestions! I agree that adding a parameter to let user choose from whether to encode UUID sounds a good plan. I'll create the PR asap.

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/23766
