### ISSUE TITLE
Add .sql template extension rendering for BigQueryInsertJobOperator

### ISSUE THREAD

**Issue by LennyKLB** [apache/airflow#22859]
### Description

Add `.sql` as value to `template_ext` in `airflow.providers.google.cloud.operators.bigquery.BigQueryInsertJobOperator`

### Use case/motivation

It would be helpful if Jinja would also read `.sql` templates in `airflow.providers.google.cloud.operators.bigquery.BigQueryInsertJobOperator`, especially for its `configuration.query.query` parameter. It will render that parameter as `sql` correctly, but only the outer `configuration` body -- which is based on [Bigquery/rest/v2/Job#jobconfiguration](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfiguration) -- is considered for extension-based rendering and only `json` is considered.

I think there is a clear use-case to support templating SQL-only files. I know that `BigQueryExecuteQueryOperator` has this but it's deprecated in favour of `BigQueryInsertJobOperator`.

I currently work around this using a really basic override:
```
class BigQueryTemplateFileOperator(BigQueryInsertJobOperator):
    template_ext = (".json", ".sql")
```
However, I'd like to avoid having to replicate this operator everywhere in our codebase if this might actually already be implemented soon.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@LennyKLB Assigned to you!

**Comment by LennyKLB** [comment]
The change itself is so small that I refrained from adding/editing tests. I found that the BigQuery-related tests didn't feature any file-based templating. 
If this is nonetheless still necessary, could someone point me in the right direction in terms of inspiration?

**Comment by josh-fell** [comment]
Closing via #22920.
