### ISSUE TITLE
clearTaskInstances API sets state for all dagruns when given task_ids that don't exist / existed in the DAG

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#22869]
### Apache Airflow version

2.1.1

### What happened

I have two identical DAGs with the same three tasks. You can see that they have already completed since there are three tasks in either success or failed.

I accidentally called the [clearTaskInstances endpoint](https://airflow.apache.org/docs/apache-airflow/2.1.1/stable-rest-api-ref.html#operation/post_clear_task_instances) without any valid task instance id. The next thing I know, all dagruns went into the running states and none of the task instance states changed.

![Screen Shot 2022-04-08 at 2 14 44 PM](https://user-images.githubusercontent.com/5952735/162532989-72f68e93-4f6b-426c-8171-b89510c59a3c.png)

### What you think should happen instead

Nothing should have changed because the task id I provided to the clearTaskInstances endpoint is invalid.

Airflow should not have cleared any task instances and, by that logic, it should not have set any dagruns to running.

### How to reproduce

1. Add two DAGs
2. Generate one dagrun and mark dagrun as success for both DAGs.
3. Call `clearTaskInstances` endpoint with `task_ids` as a list containing one empty string for one of the DAG.
4. Check dagrun is marked as running and no task instances were cleared for both DAGs.

You can also trigger this effect with this snippet. (derived from the [source code](https://github.com/apache/airflow/blob/2.1.1/airflow/api_connexion/endpoints/task_instance_endpoint.py#L237-L261))

```python
from airflow.utils.db import create_session
from airflow.models.taskinstance import clear_task_instances
from airflow.models.dagbag import DagBag
from datetime import datetime, timezone

with create_session() as session:
    dag = DagBag().get_dag(dag_id='example_dag')
    data = {
        "task_ids": [""],
        "start_date": datetime.now(timezone.utc),
        "end_date": datetime.now(timezone.utc),
        "only_failed": False,
        "only_running": False
    }
    tis = dag.clear(get_tis=True, **data)
    clear_task_instances(tis, session, dag=dag, dag_run_state="running")
```

### Operating System

N/A

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by wolfier** [comment]
The call to [clearTaskInstances](https://github.com/apache/airflow/blob/2.1.1/airflow/api_connexion/endpoints/task_instance_endpoint.py#L237-L261) will first construct [a query](https://github.com/apache/airflow/blob/2.1.1/airflow/api_connexion/endpoints/task_instance_endpoint.py#L251) that will fetch all task instances that matches the given criteria. With the task instances query, Airflow then [builds a dictionary](https://github.com/apache/airflow/blob/2.1.1/airflow/models/taskinstance.py#L221-L240) where dag id are the keys and a set of execution dates of the task instances are the values.

Knowing all of this, when you pass a list with only invalid task ids, it will return query that returns no task instances. No task instances means an empty dictionary. An empty dictionary means no filters will be applied to the dagruns query. No filters means all dagruns will be selected to be set to running.

A possible fix would be to check the task instances query result length. An empty result means no dagruns needs to be set to running.

**Comment by tirkarthi** [comment]
This PR seems to be related : https://github.com/apache/airflow/pull/17961

**Comment by tirkarthi** [comment]
Probably something like below could be added as a test case : 

```python
def test_clear_taskinstance_is_called_with_invalid_task_ids(self, session):
    """Test that dagrun is running when invalid task_ids are passed to clearTaskInstances API."""
    dag_id = "example_python_operator"
    tis = self.create_task_instances(session)
    dagrun = tis[0].get_dagrun()
    assert dagrun.state == 'running'

    payload = {"dry_run": False, "reset_dag_runs": True, "task_ids": [""]}
    self.app.dag_bag.sync_to_db()
    response = self.client.post(
        f"/api/v1/dags/{dag_id}/clearTaskInstances",
        environ_overrides={"REMOTE_USER": "test"},
        json=payload,
    )
    assert response.status_code == 200

    dagrun.refresh_from_db()
    assert dagrun.state == 'running'
    assert all(ti.state == 'running' for ti in tis
```

**Comment by ephraimbuddy** [comment]
@tirkarthi do you want to add that? And also test that this issue does not occur in the latest airflow

**Comment by tirkarthi** [comment]
Thanks @ephraimbuddy, created https://github.com/apache/airflow/pull/22894

**Comment by ephraimbuddy** [comment]
@wolfier this issue was fixed in https://github.com/apache/airflow/pull/17961, can you verify that it doesn't exist from airflow 2.1.4

**Comment by wolfier** [comment]
I have verified that this is no longer a bug in 2.1.4 and 2.2.5!
