### ISSUE TITLE
Keyboard shortcut in Airflow web UI

### ISSUE THREAD

**Issue by chlee1016** [apache/airflow#22870]
### Description

Thanks to you guys contribution, we are using Airflow in production.
We have a number of DAGs we should manage, so it is frequent to clear a task or mark it as success, etc.

### Use case/motivation

Everytime we clear a task or mark it as success, clicking the button 'Clear' or 'Mark Success' is timespent.

Therefore, it would be great if there is a keyboard shortcut for that buttons.

![image](https://user-images.githubusercontent.com/36870121/162550841-3e06e499-1ed5-4d3b-a6e6-8d429555f55b.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Good idea. Why don''t you add a PR for that @chlee1016 ? Sounds like an easy first-time contribution

**Comment by HoangTuan110** [comment]
I am interested in this issue. Where is the place that stores the Web UI code?

**Comment by Megha-Sai-Sree-PINNAKA** [comment]
Hello, is this issue still available? If yes, I would like to try it.

**Comment by potiuk** [comment]
Feel free. Assigned.

**Comment by Adaverse** [comment]
Hello everyone, 

we come across a lot of instances (especially in dev) where 
1. we need to clear the existing tasks at the (1.1) dag level i.e. from the first task or (1.2) at a particular task and all its downstream. 
2. Also, we come across situations where we need to manually set the dags (or tasks) to either success or failed.

Just wanted to get your suggestions (was working on the PR) @potiuk @chlee1016 on the shortcuts to make it more intuitive. 

So, for the first case mentioned above, we can have a shortcut of ```alt+c``` and the action selected will depend on whether the user has selected a particular dag (1.1) or a particular task (1.2). 

In the below case, the user is at dag level, and upon hitting ```alt+c```, it will trigger the method of ```Clear existing tasks```

![image](https://user-images.githubusercontent.com/35839624/234691855-8d5f9333-bab3-4dbe-b903-3edbf76ff608.png)

And in the below case, the user is at a task level, and upon hitting ```alt+c```, it will clear the tasks and all it downstream.

![image](https://user-images.githubusercontent.com/35839624/234692132-5ec2e266-c75d-4dca-bd73-fa0fb752720f.png)

Similarly, ```alt+f``` for failing a particular dag or task and ```alt+s``` for succeeding dag or task.

Do let me know your thoughts.

_Sorry for making it long but wanted to be clear and descriptive._

**Comment by potiuk** [comment]
I think best is to just make a PR. You do not need to agree upfront what you are implementting in a PR -> just make a  PR referring to this one, and then the reviewers will comment there.
