### ISSUE TITLE
constraints folder does not exists on repository

### ISSUE THREAD

**Issue by Noobzik** [apache/airflow#22875]
### What do you see as an issue?

Following the quickstart install https://airflow.apache.org/docs/apache-airflow/stable/start/local.html

This block of code is not working as it returns an 404 not found.

```bash
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
# For example: https://raw.githubusercontent.com/apache/airflow/constraints-2.2.5/constraints-3.6.txt
```

Full console log
```log
bash ./airflow_script.sh 
Defaulting to user installation because normal site-packages is not writeable
ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints-2.2.5/constraints-3.10.txt
./airflow_script.sh: line 15: airflow: command not found
```

### Solving the problem

I think the documentation needs to be update to reflect the current way to deploy locally airflow.

```
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-${PYTHON_VERSION}.txt"
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
IIUC Python 3.10 is not supported for the 2.2 series. You need to use Python 3.9 for now, or wait for Airflow 2.4.

**Comment by potiuk** [comment]
Precisely Python 3.10 is not supported for 2.2. https://github.com/apache/airflow/blob/main/README.md#requirements
