### ISSUE TITLE
Airflow health API is returning always 200

### ISSUE THREAD

**Issue by gitruhul** [apache/airflow#22895]
### Apache Airflow version

2.2.4

### What happened

The health endpoint of airflow (base_url/health) is always returning 200 in all the scenarios (healthy+unhealthy).

Same information is mentioned [here](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/check-health.html?msclkid=33d4cc33b96611ec8aea45c673e864e7) that

`Please keep in mind that the HTTP response code of /health endpoint should not be used to determine the health status of the application. The return code is only indicative of the state of the rest call (200 for success).`

Scenario-1: (Scheduler and Metadatabase are healthy) - Status Code = 200

```
{
  "metadatabase": {
   "status": "healthy"
  },
  "scheduler": {
   "latest_scheduler_heartbeat": "2022-04-07T13:13:41.102804+00:00",
   "status": "healthy"
  }
}
```
Scenario-2: (Scheduler is unhealthy) - Status Code = 200

```
{
  "metadatabase": {
   "status": "healthy"
  },
  "scheduler": {
   "latest_scheduler_heartbeat": "2022-04-07T13:13:41.102804+00:00",
   "status": "unhealthy"
  }
}
```

The only way to get unhealthy information is by parsing the JSON response.

### What you think should happen instead

The status code of scenario-2 (Something is unhealthy) should return a status code other than 200.

### How to reproduce

Install airflow and hit the URL base_url/health

### Operating System

Linux

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I don’t think we can change this, if we return anything other than 200 it risks breaking existing usages. Also, what would you propose using instead? Honestly 200 feels like the most appropriate code to me.

**Comment by gitruhul** [comment]
Creating a template for the health response will help with different standards. 

For example, some organizations prefer health responses as 

```
{
"status": "unhealth",
"results": {
	"metadatabase": {
		"status": "healthy"
	},
	"scheduler": {
		"latest_scheduler_heartbeat": "2022-04-07T13:13:41.102804+00:00",
		"status": "unhealthy"
	}
}
}
```

**Comment by gitruhul** [comment]
Hi @uranusjr , Thanks for your response.
Current health API is just like API ping. whereas health checks should be superior to that.
When I see some standards (Including my organization's) the expectation was a non 200 code for an unhealthy signal.

**Comment by potiuk** [comment]
We should create a NEW health endpoint for that not change the existing one.

**Comment by potiuk** [comment]
@uranusjr is right - this is a breaking change and changing it to fit someone's standard (even if it's a reasonable and desired state) does not justify breaking existing endpoint's behaviour.

**Comment by mik-laj** [comment]
We shouldn't change the code when the scheduler isn't working. This endpoint should only checks health of webserver and required components - metabase. Otherwise the web server will be restarted much more often than necessary.

We have a related note in doc.

> For this check to work, at least one working web server is required. Suppose you use this check for scheduler monitoring, then in case of failure of the web server, you will lose the ability to monitor scheduler, which means that it can be restarted even if it is in good condition. For greater confidence, consider using [CLI Check for Scheduler](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/check-health.html#check-health-cli-checks-for-scheduler).

**Comment by mik-laj** [comment]
I agree. We can add separate health checks for other components that will be independent of the webserver.

**Comment by rbiegacz** [comment]
Indeed, it would be great to have other API-based methods for checking the health of other components (e.g. Scheduler).

**Comment by michaelmicheal** [comment]
Feel free to assign this to me, I can start by adding a healthcheck endpoint to the scheduler
