### ISSUE TITLE
Multiple workers on the same machine? 

### ISSUE THREAD

**Issue by pharoson** [apache/airflow#229]
As the title suggests, I want to know if this is possible. 

Currently, I'm running workers on different machines as different users. I have these workers listening to different queues in order to run bash scripts as different users. 

However, I need one machine to run scripts as two different users. The issue arises when Airflow attempts to create a new worker and runs into an existing mini-web server on port 8793 (used to serve local logs to the main webserver). 

Is there a workaround or a planned feature for this?

**Comment by mistercrunch** [comment]
This is an interesting hack. I think the real solution here is to add a boolean flag to BaseOperator  `run_as_owner`. If set to true, the worker would impersonate the owner `chpst`(?) prior to executing the task.

Are those BashOperators? PythonOperators?

**Comment by pharoson** [comment]
I'm running BashOperators.

**Comment by mistercrunch** [comment]
Celery does not support multiple workers on the same box. You'd have to use containers or virtualization of some sort. 

But this is more about impersonation and authentication and there are other issues open for this topic.
