### ISSUE TITLE
Text wrap for task group tooltips

### ISSUE THREAD

**Issue by ghost** [apache/airflow#22912]
### Description

Improve the readability of task group tooltips by wrapping the text after a certain number of characters.

### Use case/motivation

When tooltips have a lot of words in them, and your computer monitor is fairly large, Airflow will display the task group tooltip on one very long line. This can be difficult to read. It would be nice if after, say, 60 characters, additional tooltip text would be displayed on a new line.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@astronaut-chris could you please include an example screenshot?
