### ISSUE TITLE
after migrating from version 2.1.4 to 2.3.0 airflow is unable to view the scheduler logs

### ISSUE THREAD

**Issue by tronlightracer** [apache/airflow#22987]
### Apache Airflow version

main (development)

### What happened

After migrating from version 2.1.4 to 2.3.0 and running `airflow db upgrade` I try to view the logs of tasks run in 2.1.4 in the UI and I'm given this error:

```
*** Log file does not exist: /usr/local/airflow/logs/dag_id=builtin_macros_most_recent/run_id=manual__2022-04-13T15:11:11.269706+00:00/task_id=test_time/attempt=1.log
*** Fetching from: http://1e317b63d5f4:8793/log/dag_id=builtin_macros_most_recent/run_id=manual__2022-04-13T15:11:11.269706+00:00/task_id=test_time/attempt=1.log
*** Failed to fetch log file from worker. [Errno 111] Connection refused
```

It gives this error whether you update the database with `airflow db upgrade` or don't update the database at all.

### What you think should happen instead

I should be able to view the logs from tasks ran in a different version than what the current version is.

### How to reproduce

start airflow with version 2.1.4
run dags in 2.1.4
change dockerfile to that of version 2.3.0
check logs of tasks run in version 2.1.4 and you'll receive that error

### Operating System

Docker (debian:buster)

### Deployment

Astronomer

### Deployment details

quay.io/astronomer/ap-airflow-dev:2.1.4-7-buster-nightly-20220411
quay.io/astronomer/ap-airflow-dev:2.3.0.dev20220411

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This looks lie deployment issue - I think you should open support request to Astronomer.
