### ISSUE TITLE
"container_timeout" argument for providers.microsoft.azure.hooks.container_instance missing(?)

### ISSUE THREAD

**Issue by tobianton** [apache/airflow#22986]
### Apache Airflow Provider(s)

microsoft-azure

### Versions of Apache Airflow Providers

apache-airflow-providers-microsoft-azure==3.7.2

apache-airflow-providers-amazon==3.2.0
apache-airflow-providers-celery==2.1.3
apache-airflow-providers-cncf-kubernetes==3.0.0
apache-airflow-providers-docker==2.5.2
apache-airflow-providers-elasticsearch==2.2.0
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-google==6.7.0
apache-airflow-providers-grpc==2.0.4
apache-airflow-providers-hashicorp==2.1.4
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-mysql==2.2.3
apache-airflow-providers-odbc==2.0.4
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-redis==2.0.4
apache-airflow-providers-sendgrid==2.0.4
apache-airflow-providers-sftp==2.5.2
apache-airflow-providers-slack==4.2.3
apache-airflow-providers-sqlite==2.1.3
apache-airflow-providers-ssh==2.4.3

### Apache Airflow version

2.2.5 (latest released)

### Operating System

Server: Docker Desktop 4.7.0 (77141) & apache/airflow:2.2.5-python3.9

### Deployment

Docker-Compose

### What happened

I see from the [docs](https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/operators/container_instances.py) that the **AzureContainerInstancesOperator** accepts a "container_timeout" parameter (of type timedelta?).

When I supply the argument to the AzureContainerInstancesOperator my DAG serialization fails.

### What you think should happen instead

Either the argument should be removed from the docs:
- [Source1](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/_api/airflow/providers/microsoft/azure/operators/container_instances/index.html)
- [Source2](https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/operators/container_instances.py)

Or the argument should be re-introduced.

I'm hoping for the latter outcome as it would make the "cost control" kickback from my employer go over a lot smoother in our cloudification of an old Airflow instance.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it . Seems it's never been there.
