### ISSUE TITLE
Grid view: "duration" shows 00:00:00

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#23068]
### Apache Airflow version

2.3.0b1 (pre-release)

### What happened

Run [a dag with an expanded TimedeltaSensor and a normal TimedeltaSensor](https://gist.github.com/MatrixManAtYrService/051fdc7164d187ab215ff8087e4db043), and navigate to the corresponding entries in the grid view.

While the dag runs:
- The unmapped task shows its "duration" to be increasing 
- The mapped task shows a blank entry for the duration

Once the dag has finished:
- both show `00:00:00` for the duration

### What you think should happen instead

I'm not sure what it should show, probably time spent running?  Or maybe queued + running?  Whatever it should be, 00:00:00 doesn't seem right if it spent 90 seconds waiting around (e.g. in the "running" state)

Also, if we're going to update duration continuously while the normal task is running, we should do the same for the expanded task.

### How to reproduce

run a dag with expanded sensors, notice 00:00:00 duration

### Operating System

debian (docker)

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

`astrocloud dev start`

Dockerfile:
```
FROM quay.io/astronomer/ap-airflow-dev:main
```

image at airflow version 6d6ac2b2bcbb0547a488a1a13fea3cb1a69d24e8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatrixManAtYrService** [comment]
@bbovenzi mentioned that we could solve this in the UI by:

> always basing the duration on the displayed end/start because sometimes the value we get from the webserver isn't consistent.

But I filed an issue instead of recommending that he do that because maybe we should investigate why the webserver is providing 00:00:00 in the first place.

**Comment by uranusjr** [comment]
FOr clarification, does this only happen to sensors (or even only `TimedeltaSensor`), while a normal task show a correct duration when mapped?

**Comment by MatrixManAtYrService** [comment]
I created one with a PythonOperator that just slept for 90 seconds, and I still get 00 for it, whether or not it's mapped.  So I guess the failure is more general than I thought.
