### ISSUE TITLE
Breeze: Add running Helm Install/Upgrade tests to Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23084]
There are pytests tests for helm chart that can be triggered from the new Breeze (the biggest complexity is to enable runinng them in Paralllel running Pools).

**Comment by Bowrna** [comment]
@potiuk I am new to k8s / helm chart. Do you think I can pick up this task or Do I need to understand more about Helm to pick this task?

**Comment by potiuk** [comment]
I assigned it to you just in case :)

**Comment by Bowrna** [comment]
yes i will pick this up :) thanks @potiuk

**Comment by potiuk** [comment]
This is done now with #25678
