### ISSUE TITLE
Breeze: Running integration tests in Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23083]
We should be able to run integration tests with Breeze - this is extension of `test` unit tests command that should allow to enable --integrations (same as in Shell) and run the tests with only the integration tests selected.

**Comment by joppevos** [comment]
@potiuk I can take this one :)
so we want a flag like `breeze test --integrations`?

**Comment by potiuk** [comment]
I think we need to do "breeze test" in general first - just to allow regular unit testing to be executed with single command.

We already have CI executing the different test types - and we need to automate CI running of those tests in parallel but it should start with a `breeze test` command:

The different test types are described here:

https://github.com/apache/airflow/blob/main/TESTING.rst#airflow-test-types


And we gnerally have to implement equivalent of this:


Detailed usage for command: tests


```
breeze-legacy tests [FLAGS] [TEST_TARGET ..] [-- <EXTRA_ARGS>]

      Run the specified unit test target. There might be multiple
      targets specified separated with comas. The <EXTRA_ARGS> passed after -- are treated
      as additional options passed to pytest. You can pass 'tests' as target to
      run all tests. For example:

      'breeze-legacy tests tests/core/test_core.py -- --logging-level=DEBUG'
      'breeze-legacy tests tests

Flags:

--test-type TEST_TYPE
        Type of the test to run. One of:

               All,Always,Core,Providers,API,CLI,Integration,Other,WWW,Postgres,MySQL,Helm,
               Quarantined

        Default: All
```

**Comment by joppevos** [comment]
@potiuk Great. I think the general test command wil be covered by [this](https://github.com/apache/airflow/issues/23082) issue not? This will then depend on the implementation of that issue. I can make a start on the `breeze test` command and see later how we bring it together @Bowrna

**Comment by joppevos** [comment]
@potiuk I tried to make a start this morning, but some things are not clear to me yet. 

We want to run pytest in our container. Too run `docker exec ...pytest`, the container needs to be running. 
Do we want `breeze tests` to spin up the container? 
A logic like the following:
```
check if container is running
...
if not, spin up container detached
exec pytest in container
...
forward pytest results to stdout
stop de container
```

In `breeze-legacy`, we ask the user to first spin up the container himself, detached. 
I cannot find a command in the new breeze where we can spin the container up easily detached. Then we need to provide a command for that too i guess. something like `docker-compose up -d` wrapped with `breeze up`?

Thanks for the help and rubber ducking 🦆

**Comment by Bowrna** [comment]
@joppevos 
https://github.com/apache/airflow/pull/23052 - This is in the new breeze where you can join the shell of interactive airflow container to execute commands. It's not yet merged.
