### ISSUE TITLE
Breeze: Running K8S tests with Kind with Breeze

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23085]
There is the whole "kind" set of commands that should be implemented in the new Breeze. 

There are few sub-commands there that can be implemented gradually.

**Comment by edithturn** [comment]
@potiuk I would like to take this issue gradually.

**Comment by potiuk** [comment]
Feel free

**Comment by edithturn** [comment]
Just adding some context:

`They cover the whole liffecycle of "kubernetes" development:
deploying and installing kind -> which is  greate "Kubernetes-in-docker"  solution that allows you to set-up development-grade K8S instances if you have Docker running (very good to master kind if you want to do anythoing K8S)
Building and deploying Airflow on the kind cluster using Production Image and Helm Chart of Airflow
Running tools that allow you to debug running Airflow instance (In particular fantastic k9s tool)
Running tests using Airflow deployed in the  Kind cluster` --Jarek

**Comment by edithturn** [comment]
@potiuk I understand, could I start with this one ./breeze kind-cluster start

![Screenshot from 2022-05-04 18-13-20](https://user-images.githubusercontent.com/58795858/166840099-a01fd54b-cbfa-4491-8c92-c408d0fabc50.png)

I will check how kind is working with Breeze legacy and then try to make it with the breeze.

**Comment by potiuk** [comment]
Cool

**Comment by edithturn** [comment]
@potiuk I am so sorry :(, I was thinking to take it today. If I don't make any progress today please feel free to retake it 🙏🏼

**Comment by potiuk** [comment]
No problem at all :). You are doing that in your free time so no pressure.

**Comment by edithturn** [comment]
@potiuk let me know if I am going for the right path:

1. In the Developer tools section, I am adding kind-cluster as a command (./breeze --help)

![Screenshot from 2022-05-09 22-22-48](https://user-images.githubusercontent.com/58795858/167537308-2c695e72-d67a-45f1-bf7f-24977e237ed3.png)

* As options of kind-cluster, I am adding just for now "start", "stop" and "restart". 

![Screenshot from 2022-05-09 22-22-59](https://user-images.githubusercontent.com/58795858/167537334-491e4f73-ed52-428e-a2b2-ed4fd7f64333.png)

2.  I added a new class in `dev/breeze/src/airflow_breeze/utils/kind_command_utils.py`, it will contain validations to start/stop...etc kind with airflow version for this: `./breeze-legacy kind-cluster start`

![Screenshot from 2022-05-09 22-28-06](https://user-images.githubusercontent.com/58795858/167537193-28c8437a-47cf-41d6-adaa-e8a788c727c3.png)

Now, --start, --stop, --restart, should they be commands and not options, right? In `./breeze kind-cluster start`  <-- kind-cluster is a command and **start** should be a command too

**Comment by potiuk** [comment]
Yeah "start", "stop", "restart" should be sub-commands rather than flags. They shoudl be multi-level structure (using click.group) as described in https://mauricebrg.com/article/2020/08/advanced_cli_structures_with_python_and_click.html for example

So the user should run:

* `breeze kind-cluster start` 
* `breeze kind-cluster stop`

etc.

**Comment by edithturn** [comment]
Thanks, Jarek! :)

**Comment by potiuk** [comment]
Ey Edith. I wen ahead and implemented it almost from the scratch - with much renewed command line and I am just about to submit PR. This is a mammoth of a change BTW :)

**Comment by edithturn** [comment]
@potiuk thank you for letting me know, should I close this issue?
Paste the link of you PR, it will be nice to learn how you approach it
