### ISSUE TITLE
Cloudant Provider: Replace `cloudant` with `ibmcloudant`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#23117]
### Body

cloudant is deprecated:
```
  /usr/local/lib/python3.7/site-packages/cloudant/__init__.py:28: DeprecationWarning: The module cloudant is now deprecated. The replacement is ibmcloudant.
    DeprecationWarning)
```

https://pypi.org/project/cloudant/ :
```
DEPRECATED
This library is now deprecated and will be end-of-life on Dec 31 2021.
```
    
Replacement is:
https://pypi.org/project/ibmcloudant/
https://github.com/IBM/cloudant-python-sdk

Migration guide: https://github.com/cloudant/python-cloudant/blob/master/MIGRATION.md

The task:
Make [CloudantHook](https://github.com/apache/airflow/blob/501a3c3fbefbcc0d6071a00eb101110fc4733e08/airflow/providers/cloudant/hooks/cloudant.py#L27) compatible with the new lib.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by uranusjr** [comment]
To resolve the PyJWT incompatibility, we (at least) need to upgrade to FAB 4.x, which requires upgrading to Flask 2.x. We need to make progress in #22397 first.

(Closing since #21004 already tracks this, and the situation has not changed.)

**Comment by eladkal** [comment]
Ah i missed that issue
