### ISSUE TITLE
Task Duration shows as "empty" when it was really less than 1 second

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#23169]
### Apache Airflow version

2.2.5 (latest released)

### What happened

![Screen Shot 2022-04-22 at 8 48 18 AM](https://user-images.githubusercontent.com/6012231/164717343-249c5953-e458-4d3f-b649-e63bd52c5090.png)
When in reality it just ran less than a second
![Screen Shot 2022-04-22 at 8 48 42 AM](https://user-images.githubusercontent.com/6012231/164717401-bd0b1f29-84f0-48ed-a282-46c36863fd29.png)

### What you think should happen instead

Duration should denote the task took less than 1 second

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

N/A

### Deployment

Astronomer

### Deployment details

`based on Airflow 2.2.5` 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aschoe21** [comment]
I think I found an easy solution to this. The problem seems to be that, by default, moment's diff method truncates decimal places resulting in a rounded-down integer, so if execution time is less than a full second it will appear as 0. Luckily the diff method accepts an optional argument to disable this functionality. I'll get on making a PR ASAP.

**Comment by frankcash** [comment]
Awesome!

**Comment by amoghrajesh** [comment]
@eladkal @bbovenzi I can take this issue if nobody is working on it. Seems like an interesting one.

**Comment by bbovenzi** [comment]
<img width="252" alt="Screenshot 2023-03-02 at 1 47 19 PM" src="https://user-images.githubusercontent.com/4600967/222523140-4728de05-80fa-40ca-b61b-aa2e9f54e459.png">

We got rid of the tree view a long time ago and we know calculate duration better.

Even the legacy tooltip in the graph seems to be working:
<img width="332" alt="Screenshot 2023-03-02 at 1 48 19 PM" src="https://user-images.githubusercontent.com/4600967/222523296-2696fbd4-94c5-4f36-a7a3-a43544be94f5.png">
