### ISSUE TITLE
Airflow Production image not working but dev Image is working

### ISSUE THREAD

**Issue by algoexpert12** [apache/airflow#23163]
### Apache Airflow version

2.2.3

### What happened

The production image when built then a container stopped a second after starting from docker desktop.

### What you think should happen instead

Production image should work.

### How to reproduce

./breeze build-image --python 3.8 --production-image --install-airflow-version 2.2.3

### Operating System

windows 11

### Versions of Apache Airflow Providers

2.2.3

### Deployment

Other

### Deployment details

I am deploying using BREEZE.

### Anything else

I am making my custom airflow image and the development image is built successfully and running.

 but the **production image successfully built but not running.**

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You are using it wrong.

Production image by default runs airflow command (for example you can do `docker run apache/airflow webserver`) and it . So if you do not specify a command it will just ask you to provide one. This is what expected. There are special commands `bash` and `python` that you can use to run python code or drop into bash if you want. 

All details are described here: https://airflow.apache.org/docs/docker-stack/entrypoint.html#executing-commands
