### ISSUE TITLE
GCSToGCSOperator ignores replace parameter when there is no wildcard

### ISSUE THREAD

**Issue by Yao-ATG** [apache/airflow#23162]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

Latest

### Apache Airflow version

2.2.5 (latest released)

### Operating System

MacOS 12.2.1

### Deployment

Composer

### What happened

Ran the same DAG twice with 'replace = False', in the second run files are overwritten anyway.
source_object does not include wildcard.

Not sure whether this incorrect behavior happens to "with wildcard" scenario, but from source code
https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/transfers/gcs_to_gcs.py 
in line 346 (inside _copy_source_with_wildcard) we have
      if not self.replace:
but in _copy_source_without_wildcard we don't check self.replace at all.

### What you think should happen instead

When 'replace = False', the second run should skip copying files since they are already there.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Can you add a PR to fix it please? That's the best way to make it happen quickly otherwise it will have to wait for somene to pick it up @Yao-ATG

**Comment by sahutd** [comment]
@potiuk i am interested in filing a fix for this[i might be facing a similar issue described here]

as i have not developed airflow in the past, it might take me some time. in the meantime, if someone wants to file a fix, go for it :)

**Comment by spatocode** [comment]
> @potiuk i am interested in filing a fix for this[i might be facing a similar issue described here]
> 
> as i have not developed airflow in the past, it might take me some time. in the meantime, if someone wants to file a fix, go for it :)

I'll be picking this up, then.

**Comment by spatocode** [comment]
@potiuk I raised a [PR](https://github.com/apache/airflow/pull/23340) to fix this.
