### ISSUE TITLE
Mark Success on a mapped task, reruns other failing mapped tasks

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23171]
### Apache Airflow version

2.3.0b1 (pre-release)

### What happened

Have a DAG with mapped tasks. Mark at least two mapped tasks as failed. Mark one of the failures as success. See the other task(s) switch to `no_status` and rerun.

![Apr-22-2022 10-21-41](https://user-images.githubusercontent.com/4600967/164734320-bafe267d-6ef0-46fb-b13f-6d85f9ef86ba.gif)

### What you think should happen instead

Marking a single mapped task as a success probably shouldn't affect other failed mapped tasks.

### Operating System

OSX

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
This looks like a similar issue to https://github.com/apache/airflow/issues/22995 where changing status might clear downstream failed tasks causing re-run.
