### ISSUE TITLE
Some links in contributor's quickstart table of contents are broken

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#23174]
### What do you see as an issue?

In `CONTRIBUTORS_QUICK_START.rst`, the links in the table of contents that direct users to parts of the guide that are hidden by the drop down don't work if the drop down isn't expanded. For example, clicking "[Setup Airflow with Breeze](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#setup-airflow-with-breeze)" does nothing until you open the appropriate drop down `Setup and develop using <PyCharm, Visual Studio Code, Gitpod>`

### Solving the problem

Instead of having the entire documentation blocks under `Setup and develop using {method}` dropdowns, there could be drop downs under each section so that the guide remains concise without sacrificing the functionality of the table of contents.

### Anything else

I'm happy to submit a PR eventually, but I might not be able to get around to it for a bit if anyone else wants to handle it real quick.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Also, isn't breeze agnostic to a contributor's code editor? Maybe breeze should have its own header section without being embedded in the drop down so it doesn't get repeated a few times.

**Comment by potiuk** [comment]
Some good ideas. We might to redo some of the Breeze docs once we finish #12282 . Breeze will get simpler to use and more powerful after the rewrite so some of the content here might be reshuffled at least or rewrritten

**Comment by potiuk** [comment]
I split it into separate pages to make it nicer. I think the duplication is useful - as mostly people focus on the IDE they know best. If you have power-users who do not need IDEs. they don't need QUICK conributor's guides.

**Comment by ashb** [comment]
@RNHTTR Do Jarek's changes (now on main) fix this do you think? Can we close this now?

**Comment by potiuk** [comment]
Not yet on main :) need an approval for #23762 and they will close this one when merged :)

**Comment by ashb** [comment]
> Not yet on main :) need an approval for #23762 and they will close this one when merged :)

🤦🏻

**Comment by potiuk** [comment]
Yeah @RNHTTR , any improvments proposals/input there are most welcome :).

**Comment by RNHTTR** [comment]
> Yeah @RNHTTR , any improvments proposals/input there are most welcome :).

Sure, I'll have a look today. Would it make sense to migrate all the docs from .rst to markdown?

**Comment by potiuk** [comment]
In this case - absolutely. But I guess we can do it as next step.
