### ISSUE TITLE
Ability to clear a specific DAG Run's task instances via REST APIs

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23227]
### Discussed in https://github.com/apache/airflow/discussions/23220

<div type='discussions-op-text'>

<sup>Originally posted by **yashk97** April 25, 2022</sup>
Hi,

My use case is in case multiple DAG Runs fail on some task (not the same one in all of them), I want to individually re-trigger each of these DAG Runs. Currently, I have to rely on the Airflow UI (attached screenshots) where I select the failed task and clear its state (along with the downstream tasks) to re-run from that point. While this works, it becomes tedious if the number of failed DAG runs is huge.

I checked the REST API Documentation and came across the clear Task Instances API with the following URL: /api/v1/dags/{dag_id}/clearTaskInstances

However, it filters task instances of the specified DAG in a given date range. 

I was wondering if, for a specified DAG Run, we can clear a task along with its downstream tasks irrespective of the states of the tasks or the DAG run through REST API.

This will give us more granular control over re-running DAGs from the point of failure.
![image](https://user-images.githubusercontent.com/25115516/165099593-46ce449a-d303-49ee-9edb-fc5d524f4517.png)
![image](https://user-images.githubusercontent.com/25115516/165099683-4ba7f438-3660-4a16-a66c-2017aee5042f.png)
</div>

**Comment by uranusjr** [comment]
I wonder whether we should overload `clearTaskInstances`, or have a separate endpoint under the DAG run ID prefix instead.

**Comment by yashk97** [comment]
Having a separate endpoint will allow maintaining consistency with the flow to clear the task through the Airflow UI.

The parameters can include the following:

- Task ID to be cleared (A single task ID)
- Whether to clear upstream/downstream tasks too.
- Reset DAG run to set its state to running.

**Comment by erdos2n** [comment]
This sounds like a similar issue I'm currently working on to update a taskInstanceState via the API, the current endpoint is a `POST:   /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}:`

the body of the work I'm doing contains the following, which should suffice for this, if I'm not mistaken

```
include_upstream
include_downstream
include_future
include_past
```

Though currently this endpoint does not support a date-range

**Comment by Bowrna** [comment]
Could I take this issue and try fixing it? This is the first time I am working on the REST APIs part.

**Comment by ephraimbuddy** [comment]
I have assigned it to you @Bowrna

**Comment by yashk97** [comment]
I'm sorry, but I received an email about a comment by Rafael Carrasco (have attached the screenshot). I wasn't able to locate the same on the issue page. I think it would be better to clear things up so that two people don't end up working on the same thing. 

![image](https://user-images.githubusercontent.com/25115516/166219740-33e4d595-3f1b-4c61-a1da-bd2213baca34.png)

**Comment by erdos2n** [comment]
@yashk97 Please disregard that message, as I deleted it.

**Comment by yashk97** [comment]
@erdos2n Thanks for the clarification.

**Comment by Bowrna** [comment]
@erdos2n As mentioned in this issue https://github.com/apache/airflow/issues/23246 the above task is also very similar. 
Here the already existing api `/api/v1/dags/{dag_id}/clearTaskInstances` filters the dag run instances based on the date. 

The above issue asks for API endpoint with dag_run_id rather than date filter passed as param in `/api/v1/dags/{dag_id}/clearTaskInstances`

If I am right the endpoint expected for this issue is :
`/api/v1/dags/{dag_id}/dagRuns/{dag_run_id}/clearTaskInstances` with param supported : 
`task_id`
`include_upstream`
`include_downstream`
`include_future`
`include_past`
`reset_dag_runs`

cc: @yashk97 

I think the code for the other issue that you are working on will work for this case too. @erdos2n except that you pass the task_id as part of the endpoint. 

Can anybody tell me if my understanding is correct?  Is it still relevant to work on this issue or is it the same as https://github.com/apache/airflow/issues/23246 ?

**Comment by Bowrna** [comment]
> This issue is to replace `/clear` in the [webserver](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2035)

@bbovenzi This API has `map_index` and `execution_date` as param. Do I have to include those in params too?

**Comment by bbovenzi** [comment]
> @bbovenzi This API has `map_index` and `execution_date` as param. Do I have to include those in params too?

Yes, we will need to string together even multiple `map_index`s. But we can use `dag_run_id` instead of `execution_date`

**Comment by ephraimbuddy** [comment]
@bbovenzi @Bowrna I'm leaning towards updating the existing clearTaskInstances endpoint to optionally accept dag_run_id. This is a duplication of the existing endpoint (`/api/v1/dags/{dag_id}/clearTaskInstances`). There's nothing new that we want to introduce with the new endpoint. We could update the existing one to either accept `execution_date` or `dagrun_id`. I believe that's what the UI is doing. The current clear task instance endpoint can clear a specific dagrun given the execution date

**Comment by ephraimbuddy** [comment]
Another PR addressing the issue: https://github.com/apache/airflow/pull/23451
cc: @Bowrna

**Comment by Bowrna** [comment]
@bbovenzi @ephraimbuddy Could i just make change in the `/api/v1/dags/{dag_id}/clearTaskInstances` endpoint to accept `dagrun_id` then?

**Comment by ephraimbuddy** [comment]
> @bbovenzi @ephraimbuddy Could i just make change in the `/api/v1/dags/{dag_id}/clearTaskInstances` endpoint to accept `dagrun_id` then?

Yes. It should either accept a `dag_run_id` or `(start_date and end_date)`. If both `dag_run_id` and `start_date, enddate` is used, should error.

**Comment by Bowrna** [comment]
> > @bbovenzi @ephraimbuddy Could i just make change in the `/api/v1/dags/{dag_id}/clearTaskInstances` endpoint to accept `dagrun_id` then?
> 
> Yes. It should either accept a `dag_run_id` or `(start_date and end_date)`. If both `dag_run_id` and `start_date, enddate` is used, should error.

Sure i will update the PR

**Comment by Bowrna** [comment]
@ephraimbuddy @bbovenzi  How to pass `map_index` in this case of using `/api/v1/dags/{dag_id}/clearTaskInstances` endpoint? 
Because in `/api/v1/dags/{dag_id}/clearTaskInstances` we can get array of task_id. If we get an array of task_id with map_index, how to ensure to which task_id that map_index belong?

**Comment by Bowrna** [comment]
Any update about this?

**Comment by ephraimbuddy** [comment]
We can use the method we used here: https://github.com/apache/airflow/blob/325444e3813bc2439566f6f29c07ff3cfc038368/airflow/models/dag.py#L1381

Get a tuple of task_ids with the corresponding map_index instead of repeating ourselves on a new endpoint?

**Comment by ephraimbuddy** [comment]
> We can use the method we used here:
> 
> https://github.com/apache/airflow/blob/325444e3813bc2439566f6f29c07ff3cfc038368/airflow/models/dag.py#L1381
> 
> Get a tuple of task_ids with the corresponding map_index instead of repeating ourselves on a new endpoint?

I will think about this more

**Comment by Bowrna** [comment]
@ephraimbuddy @bbovenzi  Could i proceed with getting a tuple of task_ids with corresponding map_index?

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy @bbovenzi Could I proceed with getting a tuple of task_ids with the corresponding map_index?

The other PR has been merged: https://github.com/apache/airflow/pull/23451

**Comment by Bowrna** [comment]
@ephraimbuddy the PR merged https://github.com/apache/airflow/pull/23451 doesn't have task_ids as part of the API. Am I missing to understand any point? I thought this particular issue is about clearing DAG with task_ids and corresponding map_index as one of the params.  Can you please clarify?

**Comment by bbovenzi** [comment]
@ephraimbuddy that PR was to clear an entire DAG run. This issue is to clear specific task instances. Maybe we need a more complex request body:

```
{
  instances: [
    { task_id: 'task', map_index: 3 },
   { task_id: 'other_task' } // default to map_index = -1
  ]
}

**Comment by Bowrna** [comment]
@bbovenzi Does this API can accept more than one `task instance` for a specific dag run to clear?

**Comment by bbovenzi** [comment]
> @bbovenzi Does this API can accept more than one `task instance` for a specific dag run to clear?

Yes, because we are modifying the existing `/clearTaskInstances` endpoint. Since that is already plural, we need to stay consistent.
