### ISSUE TITLE
Remove usage of `days_ago()` from test suite 

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#23233]
### Body

`days_ago()` is deprecated https://github.com/apache/airflow/pull/21653

There are many test using this function thus raising warnings.
This task is to replace all usages of `days_ago()` in the tests with alternatives.
A stale PR that started to work on it https://github.com/apache/airflow/pull/21830 but didn't finish

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by maryampashmi** [comment]
What we should use instead of days_ago()?

**Comment by potiuk** [comment]
> What we should use instead of days_ago()?

Fixed date when your DAG's beginning of life is. Pick a date that you either created it or one that you might ever want to backfill from). Using `days_ago` used to be present in our examples erroneously but never had any sense.

**Comment by potiuk** [comment]
Just look at our examples NOW.
