### ISSUE TITLE
Default location of airflow_yaml_output with k8s provider

### ISSUE THREAD

**Issue by ronaldpetty** [apache/airflow#23268]
### Apache Airflow version

2.2.5 (latest released)

### What happened

Generating YAML for a DAG for K8s usage.

```
~$ airflow kubernetes generate-dag-yaml myfirstdag_bash_operator 2022-04-26
[2022-04-26 17:16:57,325] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags
YAML output can be found at /home/ubuntu/airflow_yaml_output/
```

### What you think should happen instead

I would have expected the default location to be `$AIRFLOW_HOME/airflow_yaml_output` instead of $HOME.

### How to reproduce

* Install latest airflow
* pip install apache-airflow[cncf.kubernetes]
* launch airflow
* airflow kubernetes generate-dag-yaml myfirstdag_bash_operator 2022-04-26
* YAML output can be found at /home/ubuntu/airflow_yaml_output/

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==4.0.0

### Deployment

Other

### Deployment details

I am doing this via pip, nothing else (on AWS VM).

### Anything else

Love airflow, if this is an issue (or desired feature) I am happy to work on it.

If its user error, then I am sorry!

Go Airflow!!!

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
By default, we save files in the current working directory, so you need to change the current directory.
https://github.com/apache/airflow/blob/1d875a45994540adef23ad6f638d78c9945ef873/airflow/cli/cli_parser.py#L204

**Comment by ronaldpetty** [comment]
Thanks @mik-laj wasn't seeing that option.
