### ISSUE TITLE
Test Connection button in connections

### ISSUE THREAD

**Issue by starinfinity** [apache/airflow#23273]
### Description

Add a button to test connections in connections.

![Untitled](https://user-images.githubusercontent.com/36023973/165387619-1c283d92-f769-40ce-9843-9bc8fc671ceb.jpg)
connections

### Use case/motivation

Having a test connection button in connection will be helpful while adding new connections. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @bbovenzi

**Comment by bbovenzi** [comment]
Makes sense to me. Just a heads up, the connections list is generated via a FAB template. So it may be a lot of work to just add that button.

**Comment by eladkal** [comment]
There is test connection button just not from the connection table.
Testing a connection is not a common action in the day to day work unless it's a new connection and then you need to edit the connection in any case. So I think the extra step of entering the edit connection menu to be able to test the connection is not that bad/annoying.

Given what @bbovenzi mention about effort I think we should consider closing this one.
