### ISSUE TITLE
Breeze-legacy missing flag_build_docker_images

### ISSUE THREAD

**Issue by blag** [apache/airflow#23272]
### Apache Airflow version

main (development)

### What happened

Running `./breeze-legacy` warns about a potential issue:

```shell
❯ ./breeze-legacy --help
Good version of docker 20.10.13.
./breeze-legacy: line 1434: breeze::flag_build_docker_images: command not found

...
```

And sure enough, `flag_build_docker_images` is referenced but not defined anywhere:

```shell
❯ ag flag_build_docker_images
breeze-legacy
1433:$(breeze::flag_build_docker_images)
```

And I believe that completely breaks `breeze-legacy`:

```shell
❯ ./breeze-legacy
Good version of docker 20.10.13.

ERROR: Allowed platform: [  ]. Passed: 'linux/amd64'

Switch to supported value with --platform flag.


ERROR: The previous step completed with error. Please take a look at output above
```

### What you think should happen instead

Breeze-legacy should still work. Bash functions should be defined if they are still in use.

### How to reproduce

Pull `main` branch.
Run `./breeze-legacy`.

### Operating System

macOS 11.6.4 Big Sur (Intel)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Fixed. Next time just fix it @blag :)
