### ISSUE TITLE
the api.auth_backend setting not working.

### ISSUE THREAD

**Issue by ramwin** [apache/airflow#23321]
### Apache Airflow version

2.2.5 (latest released)

### What happened

If I just set the `airflow.cfg` file
```
[api]
auth_backend = airflow.api.auth.backend.basic_auth
```
the rest api didn't work, it returns
```
{
  "detail": null,
  "status": 401,
  "title": "Unauthorized",
  "type": "https://airflow.apache.org/docs/apache-airflow/2.2.5/stable-rest-api-ref.html#section/Errors/Unauthenticated"
}
```

I found the solution on [stackoverflow](https://stackoverflow.com/a/65593173/3601654). After setting the `AIRFLOW__API__AUTH_BACKEND` environment variable, the rest api works.

### What you think should happen instead

The rest api show be enabled if I only set the `airflow.cfg`

### How to reproduce

1. install airflow
2. change the airflow.cfg
3. use `airflow standalone` to start
4. call the rest api.

### Operating System

Ubuntu 20.04.4 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.2
apache-airflow-providers-imap==2.1.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0

### Deployment

Other

### Deployment details

[program:airflow]
directory = /home/airflow/
user = airflow
command = airflow standalone
autostart=true
autorestart=true
stdout_logfile=/var/log/airflow/stdout.log
stderr_logfile=/var/log/airflow/stderr.log

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
It worked for me.
After installing airflow. Once you run `airflow standalone` it'll start with default `airflow.cfg`. Stop and set the `auth_backend = airflow.api.auth.backend.basic_auth`. Start `airflow standalone` and it should work.

Steps:
```
mkdir airflow
python3 -m venv env
. env/bin/activate
pip install apache-airflow==2.2.5 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.5/constraints-3.8.txt"
airflow standalone
```
Stop and update `auth_backend = airflow.api.auth.backend.basic_auth` in `airflow.cfg`.
Works. 

You should make sure that your `airflow.cfg` is in the same directory of the `AIRFLOW_HOME` you are using.

**Comment by ephraimbuddy** [comment]
Let me know if the above steps worked for you

**Comment by ramwin** [comment]
It works, thank you, @ephraimbuddy . It's because I start the airflow in the wrong directory.
