### ISSUE TITLE
Python 3.6 is still present in the main README

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#23403]
### What do you see as an issue?

![Screenshot from 2022-05-02 14-11-06](https://user-images.githubusercontent.com/10202690/166231487-511108df-42a5-47b5-92db-667b7b623c82.png)

### Solving the problem

remove 3.6 from 2.3 release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
PR to fix it maybe ?

**Comment by potiuk** [comment]
@raphaelauv ?
