### ISSUE TITLE
Airflow 2.3.0 does not keep promised backward compatibility regarding database configuration using _CMD Env

### ISSUE THREAD

**Issue by c-thiel** [apache/airflow#23408]
### Apache Airflow version

2.3.0 (latest released)

### What happened

We used to configure the Database using the AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD Environment variable.
Now the config option moved from CORE to DATABASE. However, we intended to keep backward compatibility as stated in the [Release Notes](AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD). 

Upon 2.3.0 update however, the _CMD suffixed variables are no longer recognized for database configuration in Core - I think due to a missing entry here:
https://github.com/apache/airflow/blob/8622808aa79531bcaa5099d26fbaf54b4afe931a/airflow/configuration.py#L135

### What you think should happen instead

We should only get a deprecation warning but the Database should be configured correctly.

### How to reproduce

Configure Airflow using an external Database using the AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD  environment variable. Notice that Airflow falls back to SQLight.

### Operating System

kubernetes

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Indeed seems like a bug. Would you like to submit a PR fixing it? Seems like an easy fix - and you could become one of the ? 2000 contributors.
