### ISSUE TITLE
Add more fields to DAG Run API endpoints

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23415]
### Description

There are a few fields that would be useful to include in the REST API for getting a DAG run or list of DAG runs:

`data_interval_start`
`data_interval_end`
`last_scheduling_decision`
`run_type` as (backfill, manual and scheduled)

### Use case/motivation

We use this information in the Grid view as part of `tree_data`. If we added these extra fields to the REST APi we could remove all dag run info from tree_data.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
I have created https://github.com/apache/airflow/pull/23440 adding the fields to response.
