### ISSUE TITLE
Add Run Task Instance endpoint to REST API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23421]
### Description

Replicate the run task instance endpoint [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L1748) in the REST API.

POST `/api/v1/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/run`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I would say we should return an array of any task instances that are changed, similar to [this](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_clear_task_instances)

**Comment by tirkarthi** [comment]
@bbovenzi  I have created https://github.com/apache/airflow/pull/23530 as a fix. Please assign this ticket to me.

**Comment by bbovenzi** [comment]
Closing since we got rid of the Run action from the UI in https://github.com/apache/airflow/pull/29706
