### ISSUE TITLE
Add a queue DAG run endpoint to REST API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23420]
### Description

Add a POST endpoint to queue a dag run like we currently do [here](https://github.com/apache/airflow/issues/23419).

Url format: `api/v1/dags/{dag_id}/dagRuns/{dag_run_id}/queue`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
@bbovenzi I can take this too since I worked clearing dag run endpoint and logic to be ported is below : 

https://github.com/apache/airflow/blob/af5463098ae30206c053dc96481dab48368cd4aa/airflow/www/views.py#L2246-L2259

**Comment by tirkarthi** [comment]
@bbovenzi There is already `/dags/{dag_id}/dagRuns/{dag_run_id}` patch endpoint that supports updating state to success, failure. Do I need to add support for queued state to the endpoint to mark dagrun as queued or do we need a separate endpoint for this?

**Comment by bbovenzi** [comment]
Yeah, I guess it does make sense to add it to patch.

**Comment by tirkarthi** [comment]
Thanks @bbovenzi , created https://github.com/apache/airflow/pull/23481 for this issue.
