### ISSUE TITLE
DataprocJobBaseOperator not compatible with TaskGroups

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#23439]
### Body

Following Stackoverflow question: https://stackoverflow.com/questions/72091119/airflow-issues-with-calling-taskgroup

The issue is that when defining task in TaskGroup the identifier of the task becomes `group_id.task_id`
[DataprocJobBaseOperator](https://github.com/apache/airflow/blob/05ccfd42f28db7d0a8fe3ed023b0e7a8ec188609/airflow/providers/google/cloud/operators/dataproc.py#L836-L838) have default of using `task_id` for job name but Google doesn't allow the `.` char :

`google.api_core.exceptions.InvalidArgument: 400 Job id 'weekday_analytics.avg_speed_20220502_22c11bdf' must conform to '[a-zA-Z0-9]([a-zA-Z0-9\-\_]{0,98}[a-zA-Z0-9])?' pattern`

We probably should fix `DataprocJobBaseOperator` to handle cases where the task defined in task group by replacing the `.` to another char.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
@pierrejeambrun you might be interested in this

**Comment by gmcrocetti** [comment]
I can take it o/
