### ISSUE TITLE
Add Postgres 14 support

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#23460]
### Use case/motivation

Using Postgres 14 as backend

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you like to make a PR to change it ? It should be rather easy.

**Comment by subkanthi** [comment]
Can I take this please

**Comment by potiuk** [comment]
Feel free!
