### ISSUE TITLE
Grid View - Multilevel taskgroup shows white text on the UI 

### ISSUE THREAD

**Issue by thaysa** [apache/airflow#23476]
### Apache Airflow version

2.3.0 (latest released)

### What happened

Blank text if there are nested Task Groups .

Nested TaskGroup - Graph view:

![image](https://user-images.githubusercontent.com/6821208/166685216-8a13e691-4e33-400e-9ee2-f489b7113853.png)

Nested TaskGroup - Grid view:

![image](https://user-images.githubusercontent.com/6821208/166685452-a3b59ee5-95da-43b2-a352-97d52a0acbbd.png)

### What you think should happen instead

We should see the text as up task group level.

### deploy below DAG:
```
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from airflow.utils.dates import datetime
from airflow.utils.task_group import TaskGroup

with DAG(dag_id="grid_view_dag", start_date=datetime(2022, 5, 3, 0, 00), schedule_interval=None, concurrency=2,
         max_active_runs=2) as dag:
    parent_task_group = None
    for i in range(0, 10):
        with TaskGroup(group_id=f"tg_level_{i}", parent_group=parent_task_group) as tg:
            t = DummyOperator(task_id=f"task_level_{i}")
            parent_task_group = tg
```
### got to grid view and expand the nodes:

![image](https://user-images.githubusercontent.com/6821208/166683975-0ed583a4-fa24-43e7-8caa-1cd610c07187.png)

#### you can see the text after text selection:
![image](https://user-images.githubusercontent.com/6821208/166684102-03482eb3-1207-4f79-abc3-8c1a0116d135.png)

### Operating System

N/A

### Versions of Apache Airflow Providers

N/A

### Deployment

Docker-Compose

### Deployment details

reproducible using the following docker-compose file:  https://airflow.apache.org/docs/apache-airflow/2.3.0/docker-compose.yaml

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @bbovenzi

**Comment by bbovenzi** [comment]
Good catch! Looks like I forgot to remove a line of code from when group children had a background color.
