### ISSUE TITLE
AWS rate limiting causes tasks to fail

### ISSUE THREAD

**Issue by SamLynnEvans** [apache/airflow#23475]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

All versions

### Apache Airflow version

2.3.0 (latest released)

### Operating System

linux

### Deployment

Astronomer

### What happened

When using the [AWS glue crawler operator](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/glue_crawler.py), if the sensing stage gets a 400 error with "Rate exceeded" message then the glue crawler operator fails.

The problem is that this can occur with as little as 10 crawler sensors working concurrently with a poll_interval of 60s.

You can set retries and exponential_backoff on the operators, however if you retry the glue crawler operator it will then fail because the crawler has already been started. In essence this means that if you use this operator and you get rate limited, then you cannot retry and you end up with brittle pipelines.

This rate limting issue happens with all other AWS operators I have worked with too.

### What you think should happen instead

This is the kind of error that the operator receives when it pings AWS for a status update:
"An error occurred (ThrottlingException) when calling the GetCrawler operation (reached max retries: 4): Rate exceeded"

I think this error should be handled instead of it causing the task to fail.

I have implemented a custom operator which catches this particular exception. I would be happy to try and submit a PR myself for the issue.

### How to reproduce

As this is a problem of being rate limited by AWS you will need to have an AWS account setup with some crawlers.

Create a DAG that uses the glue crawler operator linked to above. Have somewhere between 10 and 20 of these setup to run glue crawlers in an AWS environment. 

### Anything else

This problem occurs without fail every time we try to run 12 crawler operators at once (each with a poll_interval of 60s). 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel Free! Assigned you

**Comment by Taragolis** [comment]
As workaround - set Environment Variables for airflow service to use more "pessimistic" retry strategy, rather than [default one](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#legacy-retry-mode)
```
AWS_RETRY_MODE=standard
AWS_MAX_ATTEMPTS=10
```

Most benefit to use this approach - it effect to all AWS operators, secrets backends, hooks, and other stuff which uses boto3

Unless it explicitly set to specific [AWS connection](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#configuring-the-connection) in `extra [config_kwargs]`

**Comment by potiuk** [comment]
I think that's a good general solution that solves the problem (and it does not need any other fix except maybtle updating the docs). Thanks @Taragolis. Closin

**Comment by potiuk** [comment]
@SamLynnEvans would you like to make a PR to the Aws docs to mention that as a solution

**Comment by SamLynnEvans** [comment]
Yes that seems simpler, thank you!
