### ISSUE TITLE
Broken link  example_external_task_marker_dag.html

### ISSUE THREAD

**Issue by obearn** [apache/airflow#23480]
### What do you see as an issue?

The documentation page [https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/external_task_sensor.html](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/external_task_sensor.html) as a broken link [https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_external_task_marker_dag.html](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_external_task_marker_dag.html)

### Solving the problem

The problem seems to be the version in the link (stable)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhirsz** [comment]
Related : https://github.com/apache/airflow-site/issues/536

This issue is ongoing for quite a while but it's good that you have noticed one thing - that's the problem is propably with the version of the link (stable vs 2.2.3 for example). I will update linked issue

**Comment by potiuk** [comment]
The links are fixed. For older missing source links we now have link to the direct version in Github. For new pages that we will generate (2.3.3+) they will lead to embedded sources.)
