### ISSUE TITLE
Add Task Logs to Grid details panel

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23503]
Many users use the tree/grid view to find a failing task instance and then look at its logs to figure out what went wrong. Right now that requires one to redirect out to a separate page.

We already have access to a task instance logs with the REST API: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_log

Therefore, we can add the task logs into the details panel itself to reduce the amount of steps it takes to drill down to find out what's actually happening for an instance.

**Comment by pierrejeambrun** [comment]
Hello @bbovenzi,

I was playing around and started drafting something for this.

I was thinking about a simple read-only text area positioned with the "internal link" section and with a moderate fixed height.

Only present for `not mapped` and `not group` instances.

- Clicking on the attempt index would load the relevant logs (and not download the logs)
- We keep a download button for downloading the logs of the currently selected attempt.
- We add a button 'See more' or 'Details' that would redirect to the log page. (Same as the Nav button)

![image](https://user-images.githubusercontent.com/14861206/170892257-9a39681e-e2b4-4a29-9f6a-c8df8a857288.png)

**Comment by bbovenzi** [comment]
Yes! that looks great.

I feel like it should be below the data metadata now. We can also turn the task metadata into 2 columns to reduce the vertical spacing.

It would be nice to color coordinate or even filter the logs but we'll need changes to the API to support that.
