### ISSUE TITLE
CloudSQL proxy download doesn't work for `x86_64` systems

### ISSUE THREAD

**Issue by denver-at-takeoff** [apache/airflow#23501]
### Apache Airflow version

2.3.0 (latest released)

### What happened

The automatic `cloud_sql_proxy` download via the `CloudSqlProxyRunner` is not working because the environment is using the `uname -a` info and it is pull `x86_64`.  The url for the `cloud_sql_proxy` binaries are no longer  using `x86_64`.  Instead, the binaries are now using `amd64` indicator.

### What you think should happen instead

The hardcoded process should be opened up to include a user defined option via an extra parameter for the CloudSQLDatabaseHook and other hooks.  This would hedge for future URL updates without the need for a full blown release. 

### How to reproduce

Run in an environment that has no local copy of the `cloud_sql_proxy` and the `uname -a` gives `x86_64`.  

### Operating System

Linux

### Deployment

Composer

### Anything else

This will happen every time the `_download_sql_proxy_if_needed` is ran in an `x86_64` environment.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Closing as duplicate.

**Comment by denver-at-takeoff** [comment]
Thanks didn't catch that previous ticket when I initially search for this issue.

**Comment by potiuk** [comment]
No worries. Not always easy indeed. I KNEW there was a change but I had trouble finding it too :)
