### ISSUE TITLE
Grid View: Details Panel does not reopen (once hidden) when a task is clicked. Have to manually unhide the details panel.

### ISSUE THREAD

**Issue by AmirZahre** [apache/airflow#23505]
### Apache Airflow version

2.3.0 (latest released)

### What happened

When the Details Panel is hidden, clicking on a task does not reopen the panel. 

### What you think should happen instead

Clicking on a task should reopen the panel.

### How to reproduce

1. Dag with a single task, Airflow 2.3
2. Hide the details panel
3. Click on the task
4. **nothing happens**

### Operating System

Mac, OS Monterey 12.3.1 

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
This should be a relatively straightforward fix for anyone interested in picking it up.

We just need to listen to changes to `useSelection` in [Grid.jsx](https://github.com/apache/airflow/blob/main/airflow/www/static/js/grid/Grid.jsx) and open the details panel when needed.

**Comment by bbovenzi** [comment]
Actually, I think this is acceptable behavior. If a user wants to close the details panel, then it is on them to expand it again. Generally, we don't want to move page elements that are below the cursor. (How do you undo an action?)
