### ISSUE TITLE
Calendar view is taking too long to load in airflow 2.3.0

### ISSUE THREAD

**Issue by sambhatt25** [apache/airflow#23519]
### Apache Airflow version

2.3.0 (latest released)

### What happened

Calendar view in DAG is taking too long to load. It was fine in 2.2.5.

### Operating System

MacOS 12.3

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please add more information
