### ISSUE TITLE
Airflow 2.3.0 webserver fails to start

### ISSUE THREAD

**Issue by alexvkaam** [apache/airflow#23525]
### Apache Airflow version

2.3.0 (latest released)

### What happened

upgraded from 2.2.5

airflow db upgrade showed a list of messages inline with what is in the changelog:  

Database configuration moved to new section (#22284)

The following configurations have been moved from [core] to the new [database] section. However when reading the new option, the old option will be checked to see if it exists. If it does a DeprecationWarning will be issued and the old option will be used instead.

    sql_alchemy_conn
    sql_engine_encoding
    sql_engine_collation_for_ids
    sql_alchemy_pool_enabled
    sql_alchemy_pool_size
    sql_alchemy_max_overflow
    sql_alchemy_pool_recycle
    sql_alchemy_pool_pre_ping
    sql_alchemy_schema
    sql_alchemy_connect_args
    load_default_connections
    max_db_retries

so nice as I am I moved those lines from [core] to a new [database] section and airflow db upgrade did not mention them again so all was well.

After that I started the services

sudo systemctl start airflow-webserver.service
sudo systemctl start airflow-scheduler.service

but the webservice failed with this error:

May 04 08:46:21 postest airflow[108983]: [2022-05-04 08:46:21 +0200] [108983] [ERROR] Exception in worker process
May 04 08:46:21 postest airflow[108983]: [2022-05-04 08:46:21,254] {configuration.py:494} WARNING - section/key [core/sql_alchemy_conn] not found in config
May 04 08:46:21 postest airflow[108982]: [2022-05-04 08:46:21 +0200] [108982] [INFO] Worker exiting (pid: 108982)
May 04 08:46:21 postest airflow[108982]: airflow.exceptions.AirflowConfigException: section/key [core/sql_alchemy_conn] not found in config

for now I duplicated the lines, so they are both in [core] and [database], so no big issue.

### What you think should happen instead

service should start and find the settings in the [database] section

### How to reproduce

upgrade from 2.2.5, move the lines in question to a new [database] section and start the webservice.

### Operating System

Ubuntu 20.04.4 LTS (Focal Fossa)

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-sqlite==2.1.3

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Likeluy your worker processes are not upgraded yet. Check which airflow versions they have.
