### ISSUE TITLE
Provide resources attribute in KubernetesPodOperator to be templated

### ISSUE THREAD

**Issue by nitinmuteja** [apache/airflow#23529]
### Description

Make resources in KubernetesPodOperator as templated. We need to modify this during several runs and it needs code change for each run.

### Use case/motivation

For running CPU and memory intensive workloads, we want to continuously optimise the "limt_cpu" and "limit_memory" parameters. Hence, we want to provide these parameters as a part of the pipeline definition.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by talnagar** [comment]
we would love to get this feature!

**Comment by potiuk** [comment]
@nitinmuteja -> I assigned you - also maybe @talnagar you could take a stab at it - it seems like an easy first contribution

**Comment by nitinmuteja** [comment]
Created PR https://github.com/apache/airflow/pull/23531 .

**Comment by alanatlemba** [comment]
Would be great to get this feature.  @potiuk / @nitinmuteja seems it got stuck a few months back.  I'm relatively new to Airflow (only a couple of years of Python experience, million years of experience in C# prior), and wouldn't mind sinking some time into it (not a ton).

**Comment by potiuk** [comment]
Feel free to add it @alanatlemba - you do not need much experience for that and we can point out any improvement areas while reviewing

**Comment by alanatlemba** [comment]
@potiuk @jedcunningham finally got around to this.  Sorry about the long wait - life got in the way.  

This is my first PR for a mainstream large scale open source project, let alone Airflow.
Sorry in advance if I've done anything improper, and thanks for your patience.
