### ISSUE TITLE
Gantt Chart Broken After Deleting a Task

### ISSUE THREAD

**Issue by joelossher** [apache/airflow#23546]
### Apache Airflow version

2.2.5

### What happened

After a task was deleted from a DAG we received the following message when visiting the gantt view for the DAG in the webserver.

```
{
  "detail": null,
  "status": 404,
  "title": "Task delete-me not found",
  "type": "https://airflow.apache.org/docs/apache-airflow/2.2.5/stable-rest-api-ref.html#section/Errors/NotFound"
}
```

This was only corrected by manually deleting the offending task instances from the `task_instance` and `task_fail` tables.

### What you think should happen instead

I would expect the gantt chart to load either excluding the non-existent task or flagging that the task associated with task instance no longer exists.

### How to reproduce

* Create a DAG with multiple tasks.
* Run the DAG.
* Delete one of the tasks.
* Attempt to open the gantt view for the DAG.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other Docker-based deployment

### Deployment details

Custom docker container hosted on Amazon ECS.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
If you want to submit a PR, the error seems to come from [trying to get extra links of a deleted task](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L3313)

**Comment by joelossher** [comment]
> If you want to submit a PR, the error seems to come from [trying to get extra links of a deleted task](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L3313)

Thanks for the pointer! I'll put together a PR.
