### ISSUE TITLE
apache-airflow-providers-google not compatible with google-ads

### ISSUE THREAD

**Issue by SarbjitGahra** [apache/airflow#23543]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google    6.8.0
apache-airflow-providers-amazon    3.2.0       
apache-airflow-providers-ftp       2.1.2       
apache-airflow-providers-http      2.1.2      
apache-airflow-providers-imap      2.2.3      
apache-airflow-providers-postgres  4.1.0       
apache-airflow-providers-sqlite    2.1.3     

### Apache Airflow version

2.2.4

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### What happened

Context: 
apache-airflow-providers-google=6.8.0 has package version requirement range of >=12.0.0,<14.0.1 for google-ads. 
![image](https://user-images.githubusercontent.com/9274393/167197478-4f2de56a-d5fc-4832-9805-c1868ec65ea3.png)

The lowest google-ads version to contain v9 is 14.1.0 
![image](https://user-images.githubusercontent.com/9274393/167197421-36ff3572-05d3-451f-84d2-d23d3fd93a8e.png)

Google-ads is deprecating v8, v7 on may 11th. 
![image](https://user-images.githubusercontent.com/9274393/167197640-ea77988f-6bae-4971-90cb-88834cb279b4.png)

Issue: 
The said google-airflow provider is blocking us from updating google-ads. 
Is it possible to relax the restriction on google-ads package versions to include upto 14.1.0 ?

Thanks 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Duplicated https://github.com/apache/airflow/issues/22111

**Comment by SarbjitGahra** [comment]
Hi @eladkal 
The original issue never resolved the main problem. 
Comments by the author of the original issue- 
>Sounds great. Just as a heads up, V8 of the API will stop working on Wednesday 11th - definitely makes sense to group the Google Provider changes together, but we'll be a bit stuck if a new version of the provider hasn't been released by then!

Google provider is still preventing update to any google-ads api version older than 14.0.0.
While google-ads=14.1.0 is the lowest version to contain v9. 

Thanks

**Comment by eladkal** [comment]
The issue is resolved in main we just didn't release the new version yet.

**Comment by SarbjitGahra** [comment]
Thank you for the information. 
When do you expect to release this version ?

**Comment by potiuk** [comment]
When it's ready @SarbjitGahra . This is the only answer we can giv as we do not know if we won't find any regressions that will prevent us from releasing.

**Comment by potiuk** [comment]
And to repeat what I've already stated - you **Cannot** base your business continuity on the fact if we release or not.
