### ISSUE TITLE
Grid View: Task order rearranges constantly with auto-refresh on

### ISSUE THREAD

**Issue by tagoad** [apache/airflow#23542]
### Apache Airflow version

2.3.0 (latest released)

### What happened

While navigating the Grid view with auto refresh on the list of tasks is constantly rearranging. You can have the task instance centered in the view and then it refreshes and that task is now at the bottom of the list of tasks, next second its at the top.

### What you think should happen instead

The list of tasks should atleast be somewhat stable. Finding specific run and task just to have it essentially run away from you is very annoying.

### How to reproduce

Just have grid view open with tasks running and auto refresh on.

### Operating System

Hosted on Astronomer

### Deployment

Astronomer

### Deployment details

Using astronomer's 2.3.0-3 build

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@tagoad could you include a screen recording and maybe even a sample dag? I'm having difficulty replicating this issue.

**Comment by tagoad** [comment]
Sorry this was a little delayed but here is a recording of the tasks jumping around. I can get a sample dag if needed, but it will take some time to generate. I am scrolled to the top and don't move the scroll bar at all during this video. I don't know if graph view is even set up to update this way but i also watched graph view as the grid view was jumping around and didn't see any changes happening there.

https://user-images.githubusercontent.com/43684949/169556960-f6ce7b75-d643-41d0-a86c-2ce77d68764c.mp4

**Comment by ashb** [comment]
@tagoad Is your DAG definition static or is it perchance dynamic as the result of a DB query?

**Comment by rajrao** [comment]
We have the same issue. The DAG definition is the result of a DB query. At first, too thought it might be related to the ordering of items from the db, but, even when I placed a deterministic ordering on the data, it still keeps changing the order of the items.

**Comment by tagoad** [comment]
It looks like this issue has been addressed, @rajrao you should update to the latest Airflow version
#27523
