### ISSUE TITLE
templates_dict, op_args, op_kwargs no longer rendered in PythonVirtualenvOperator

### ISSUE THREAD

**Issue by lssatvik** [apache/airflow#23557]
### Apache Airflow version

2.3.0 (latest released)

### What happened

Templated strings in templates_dict, op_args, op_kwargs of PythonVirtualenvOperator are no longer rendered. 

### What you think should happen instead

All templated strings in templates_dict, op_args and op_kwargs must be rendered, i.e. these 3 arguments must be template_fields of PythonVirtualenvOperator, as it was in Airflow 2.2.3

### Operating System

Ubuntu 20.04

### Deployment

Virtualenv installation

### Anything else

This is due to template_fields class variable being set in PythonVirtualenvOperator
`template_fields: Sequence[str] = ('requirements',)`
that overrode class variable of PythonOperator 
`template_fields = ('templates_dict', 'op_args', 'op_kwargs')`.
I read in some discussion that wanted to make requirements a template field for PythonVirtualenvOperator, but we must specify all template fields of parent class as well.
`template_fields: Sequence[str] = ('templates_dict', 'op_args', 'op_kwargs', 'requirements',)`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lssatvik** [comment]
Nice. Was wondering how to "inherit" class variables.

**Comment by lssatvik** [comment]
@eladkal Doesn't the length of template_ext need to match template_fields?

**Comment by lssatvik** [comment]
Nvm, as requirements is first, doesn't matter.

**Comment by eladkal** [comment]
Lets leave issue open till the fix is merged
