### ISSUE TITLE
Tag persists even if we open a new window of home page after searching with tag

### ISSUE THREAD

**Issue by nandlalyadav57** [apache/airflow#23565]
### Apache Airflow version

2.2.5

### What happened

we can see that tag persists even if we open the new home page on airflow UI.

### What you think should happen instead

probably due to cache. the bug could be fixed from backend code probably

### How to reproduce

As in Ticket [9309](https://astronomer.zendesk.com/agent/tickets/9309) a customer reported this behavior & i tried to replicate it as well

1.) Searched dags with the tag on a link https://deployments.gcp0001.us-east4.astronomer.io/modem-wave-4385/airflow/home?tags=BBRO

![image](https://user-images.githubusercontent.com/33649510/167291185-ea2774b6-a672-4408-9849-696817a4c575.png)

2.) I closed the tab and went to open a new tab with the home page 
https://deployments.gcp0001.us-east4.astronomer.io/modem-wave-4385/airflow/home

![image](https://user-images.githubusercontent.com/33649510/167291201-61fa5560-0e7b-47bc-a3d4-6ba43842ad4f.png)

3) we can see that tag persisted & we have been redirected to the link in step1 again probably due to the caching issue.

### Operating System

windows11

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dnlfm** [comment]
Something that can be useful for whoever faces this problem:
Remove the filter(s) in the filter box, then you'll be able to go back to the home page.
