### ISSUE TITLE
Description of defaultAirflowRepository in values.yaml is misleading

### ISSUE THREAD

**Issue by Dris101** [apache/airflow#23566]
### Official Helm Chart version

1.5.0 (latest released)

### Apache Airflow version

2.3.0 (latest released)

### Kubernetes Version

minikube v1.25.2

### What happened

defaultAirflowRepository is described in ```values.yaml``` as

```yaml
# Default airflow repository -- overrides all the specific images below
defaultAirflowRepository: apache/airflow
```

### What you think should happen instead

```defaultAirflowRepository``` doesn't override the specific images, it is _overridden by them_. For example, in ```_helpers.yaml```
```
{{ define "pod_template_image" -}}
{{ printf "%s:%s" (.Values.images.pod_template.repository | default .Values.defaultAirflowRepository) (.Values.images.pod_template.tag | default .Values.defaultAirflowTag) }}
{{- end }}
```

Suggest updating the comment line to:-
```yaml
# Default airflow repository -- overridden by all the specific images below
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Would you like to contribute a fix @Dris101 - sounds like an easy clarification with the docs.

**Comment by potiuk** [comment]
PR are most welcome!

**Comment by ihorlukianov** [comment]
Hello @potiuk, @Dris101
May I take this?

**Comment by Dris101** [comment]
Please do! I did submit a pull request but I think it slipped through the review net. Thank you!
