### ISSUE TITLE
Synchronizing Airlfow releases, API versions and clients

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23585]
### Body

The current version of API https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html shows version 1.0.0. I think this is terribly wrong and we shoudl synchronize the API version with Airflow Version. We had a long discussion about the client versioning (and we agreed that the client versioning should be done in a specific way)

https://lists.apache.org/thread/8yd7o9wsj7jgcwvpzz9pcc74gt1l7r65

But the API itself should be versioned together with Airflow IMHO.

I have a feeling that we lack a bit of coordination here when we release Airflow - while there is some follow-up work done to get the Helm Chart catch-up with the latest Airflow Version, the API ad Clients are pretty detached from the whole process and we do not - even closely - follow up with the client work.

I do not know for sure yet how to  approach it, but I believe our relase process of Airflow should be updated with:

1) Upgrading the API version together with Airflow version upgrade
2) Similarly to Helm Chart, synchronize release of all the clients we have with Airflow Releases - this should become part of our release process, otherwise it will not be followed.

@jedcunningham @ephraimbuddy @msumit @ashb  @kaxil - I think something that we should decide what to do and execute it/make part of our regular process - happy to do some parts of it, but I think we need to agree what we want to do first. 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
I think we no longer have a task here?
We now have the policy of releasing clients https://github.com/apache/airflow/blob/main/dev/README_RELEASE_AIRFLOW.md#api-clients right after releasing Airflow
