### ISSUE TITLE
Calendar view is taking too long to load in airflow 2.3.0

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23602]
### Discussed in https://github.com/apache/airflow/discussions/23545

<div type='discussions-op-text'>

<sup>Originally posted by **sambhatt25** May  6, 2022</sup>
### Apache Airflow version

2.3.0 (latest released)

### What happened

Calendar view in DAG is taking too long to load. It was fine in 2.2.5.

### Operating System

MacOS 12.3

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by bbovenzi** [comment]
We'd have to look out how the "planned" part of calendar view is calculated.

**Comment by bbovenzi** [comment]
Yes, so [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2754) we're just iterating through every single `next_dagrun_info` for a whole year. We should be able to interpret the schedule better than that.

UI-wise we could split the requests to show at least something to the user, but really, we need to improve the webserver code.

**Comment by jedcunningham** [comment]
https://github.com/apache/airflow/pull/24262 is an attempted optimization for cron scheduled DAGs.
