### ISSUE TITLE
DatabricksSubmitRunOperator and DatabricksRunNowOperator cannot define .json as template_ext

### ISSUE THREAD

**Issue by jonathansp** [apache/airflow#23622]
### Apache Airflow version

2.2.2

### What happened

Introduced here https://github.com/apache/airflow/commit/0a2d0d1ecbb7a72677f96bc17117799ab40853e0 databricks operators now define template_ext property as `('.json',)`. This change broke a few dags we have currently as they basically define a config json file that needs to be posted to databricks. Example:

```python
DatabricksRunNowOperator(
    task_id=...,
    job_name=...,
    python_params=["app.py", "--config", "/path/to/config/inside-docker-image.json"],
    databricks_conn_id=...,
    email_on_failure=...,
)
```

This snippet will make airflow to load /path/to/config/inside-docker-image.json and it is not desired.

@utkarsharma2 @potiuk can this change be reverted, please? It's causing headaches when a json file is provided as part of the dag parameters.

### What you think should happen instead

Use a more specific extension for databricks operators, like ```.json-tpl```

### Operating System

Any

### Versions of Apache Airflow Providers

apache-airflow-providers-databricks==2.6.0

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I think this is the same problem we had with K8s https://github.com/apache/airflow/issues/17186 ?
