### ISSUE TITLE
OracleHook get_uri does not return the right connection information

### ISSUE THREAD

**Issue by jsertel** [apache/airflow#23626]
### Apache Airflow version

2.1.2

### What happened

There are multiple ways an Oracle connection can be specified. the get_conn() method contains logic to check for these various options. However, get_uri just returns the user and password without the other paramaters. 

### What you think should happen instead

get_uri should make use of the logic in get_conn() to get the proper connection info. 

### How to reproduce

Create an oracle connection with extra parmaters set as {"dsn": "hostname", "service_name": "service_name"}

### Operating System

CENTOS 7

### Versions of Apache Airflow Providers

2.1.2

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I assigned the issue to you. Feel free to raise PR

**Comment by jsertel** [comment]
Thank you. I will have to get up to speed on contributing, but I am interested.

**Comment by eladkal** [comment]
@jsertel are you planing to complete this task?

**Comment by phanikumv** [comment]
I can work on this, please assign to me @potiuk @eladkal

**Comment by phanikumv** [comment]
@jsertel I have tried making a connection with the dsn field set in the extras. I am getting the below URI from `get_uri()` method. I dont see any missing info here, can you please clarify

[2023-07-05, 06:28:38 UTC] {logging_mixin.py:152} INFO - oracle://xxxxxx:xxxxxxxxx@:1521/?dsn=providersoracledb.crzoh6zpuh9f.us-east-1.rds.amazonaws.com%2FDATABASE

**Comment by eladkal** [comment]
I'm closing as no task.
we can always reopen if further information is provided and it will become clear what is missing.
