### ISSUE TITLE
Broken Source Code Links in Operator Guides

### ISSUE THREAD

**Issue by SamWheating** [apache/airflow#23632]
### What do you see as an issue?

The `[source]` links in the operator HowTo guides seem to be 404'ing:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/16950874/167749019-aee534e1-cb5b-46c2-ab1f-92f9fe0e87c9.png">

([source](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/bash.html))

I tried to fix this but got kinda lost in the docs build system. 

### Solving the problem

I think that sphinx isn't loading the `example_dags` folder, as these modules aren't found here:

https://airflow.apache.org/docs/apache-airflow/2.3.0/_modules/

While they were present in 2.2.3:

https://airflow.apache.org/docs/apache-airflow/2.2.3/_modules/

### Anything else

I can keep looking into this, but would appreciate any pointers or guidance. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
see https://github.com/apache/airflow/issues/23480

**Comment by potiuk** [comment]
Yep. Known issue. Maybe time to fix it.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi
I would like to give a try on this if this is not already taken.

**Comment by potiuk** [comment]
Feel Free! :) Sphinx is a bit mysterious creature and asks many riddles, so any help is more than welcome.

**Comment by potiuk** [comment]
Some pointers here: https://github.com/apache/airflow-site/issues/536

**Comment by potiuk** [comment]
And possibly @mik-laj can help

**Comment by vijaya-lakshmi-venkatraman** [comment]
Thank you.
My understanding from the comment is that between 2.2.3 and the stable (2.3.0) version, the links have stopped working due to some change, possibly in the sphinx.ext.code module.
For the next step, should I be checking how to add a new module to Sphinx?

**Comment by potiuk** [comment]
I personally do not know :). I have very little knowledge about sphinx. Big part of the task is to find out what to do really because possiblychange in sphinx triggered it but we do not know exactly what was the root cause.

**Comment by rbiegacz** [comment]
BTW - the links stopped working also for providers. For example, [source] link doesn't work in the page devoted to this operator: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/automl.html

**Comment by potiuk** [comment]
Fixes are there:

* #24386  - fixes it for future documenation (I will cherry-pick it to regeenerate new provider's docs)
* https://github.com/apache/airflow-site/pull/613 - replaces the missing links in old documentation with lnks to github as we would have to regenerate all teh autapi-generated html pages otherwise as they were missing in the generated docs.
