### ISSUE TITLE
Add transfers operator S3 to SQL / SQL to SQL 

### ISSUE THREAD

**Issue by thinhnd2104** [apache/airflow#23666]
### Description

Should we add S3 to SQL to aws transfers?

### Use case/motivation

1. After process data from spark/glue(more), we need to publish data to sql
2. Synchronize data between 2 sql databases.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
SQL to SQL is GenericTransfer:
https://github.com/apache/airflow/blob/7277122ae62305de19ceef33607f09cf030a3cd4/airflow/operators/generic_transfer.py#L25

----------------
You are more than welcome to work on S3ToSql...
We have dedicated operators like: S3ToMySqlOperator, S3ToSnowflakeOperator
should you be able to create a generic transfer that can be great.

**Comment by thinhnd2104** [comment]
In my case genneric transfers is enough because it does not have update or upsert rows.

**Comment by maggesssss** [comment]
@thinhnd2104 are you working on this topic?

**Comment by o-nikolas** [comment]
@maggesssss  Are you interested in opening a PR for this issue? We can re-assign it to you since we have not heard from @thinhnd2104 in some time.

**Comment by maggesssss** [comment]
@o-nikolas yes, I'd like to pick it up.

**Comment by o-nikolas** [comment]
> @o-nikolas yes, I'd like to pick it up.

Perfect, assigned to you :)
