### ISSUE TITLE
Fix ./breeze build-docs command options in docs/README.rst

### ISSUE THREAD

**Issue by ishiis** [apache/airflow#23669]
### What do you see as an issue?

I got an error when executing `./breeze build-docs -- --help` command in docs/README.rst.

```bash
% ./breeze build-docs -- --help
Usage: breeze build-docs [OPTIONS]

Try running the '--help' flag for more information.

╭─ Error ─────────────────────────────────────────────────╮
│ Got unexpected extra argument (--help)                  │
╰─────────────────────────────────────────────────────────╯

To find out more, visit
https://github.com/apache/airflow/blob/main/BREEZE.rst
```

### Solving the problem

"--" in option should be removed.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Just remove `--` . I will remove those "old" entries in docs.

**Comment by potiuk** [comment]
I have one more fix to do there - so I will do it together :)
