### ISSUE TITLE
Max dagrun limitation should not stop failed dagrun from retry

### ISSUE THREAD

**Issue by NickYadance** [apache/airflow#23664]
### Description

The configuration option `max_active_runs_per_dag` defines the max dagrun for a DAG. By default Airflow will spawn 16 dagruns if should. But when all 16 dagruns have been spawned, they are stoping previous dagruns from retry cuz there is not enough room.
A simple example is that say i define DAG with `catchUp` and `depends_on_past`.
```python
with DAG(
        'test',
        default_args={
            'depends_on_past': True,
            'retries': 0,

        },
        description='Max dagrun limitation should not stop failed dagrun from retry',
        schedule_interval=timedelta(hours=1),
        start_date=pendulum.datetime(2022, 5, 11, tz='Asia/Singapore'),
        catchup=True,
        tags=['example'],
) as dag:
    task_error = BashOperator(task_id='error',
                              bash_command='error')
    task_error 
```
So Airflow will spawn all 16 dagrun for me:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/10060849/168016417-c2cd6185-cc29-43fe-922d-8fcb8e05077d.png">
After the first task fails the other 16 dagruns are just sitting there waiting for the first dagrun to succeed.
But first dagrun retry will not work as it stays being queued without room to run: 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/10060849/168016932-a32a9e5e-9f9f-416d-95cd-365dfa21feb9.png">

A real life example is that when dagrun queue is full:  
1. mark the latest dagrun to success to make up room.
2. clear the failed dagrun to retry.
3. clear the latest dagrun to rerun.

After step 2 but before step 3, it happens that another dagrun is kicked and the room is full again. Then i have to mark the newest dagrun to success and rerun the dagrun in step 1.  In worst condition, the rerun loop just continues going and cannot be stopped. 

### Use case/motivation

Maybe the dagrun retried, which is triggered by clearing state, should not count into  `max_active_runs_per_dag`. And the retried dagrun has its own max number limitation.

Or add a second level option `total_active_runs_per_dag` to make up room for special dagrun including retried ones.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by spatocode** [comment]
@potiuk Please assign me this issue

**Comment by spatocode** [comment]
@NickYadance From your description and example code, the previous dag runs didn't retry because you set retries to 0. If you set retries to 3 for example, the failed dag would retry 3 times. If the dag failed after the 3rd retry, it stucks and stops other dagruns from running. So, i believe the issue here is to make sure other dagruns proceed when a previous dag retry fails.

**Comment by NickYadance** [comment]
@spatocode Oh i didn't notice that default retry is set to 0. It's been a while so i re-test this in Airflow 2.3.2 with retry set to 3 and `max_active_runs_per_dag` to 4.

The DAG:
```python
from datetime import datetime, timedelta
from textwrap import dedent
import pendulum
# The DAG object; we'll need this to instantiate a DAG
from airflow import DAG

# Operators; we need this to operate!
from airflow.operators.bash import BashOperator
with DAG(
        'test',
        default_args={
            'depends_on_past': True,
            'retries': 3,
        },
        description='Max dagrun limitation should not stop failed dagrun from retry',
        schedule_interval=timedelta(hours=1),
        start_date=pendulum.datetime(2022, 5, 11, tz='Asia/Singapore'),
        catchup=True,
        tags=['test'],
) as dag:
    task_error = BashOperator(task_id='error',
                              bash_command='error')
    task_error
```

Airflow spawns 4 dagruns and the first dagrun fails with retry. However i can manually clear the first dagrun and it will rerun as normal. This is actually the behavior that i expected. In real life case we can fix the problem and kick off the first dagrun so the rest won't stuck so there is no deadlock in the situation.
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/10060849/177131844-a5ed28f5-6c77-4860-a6b7-af9011be855d.png">

Will close the issue since i can't reproduce it and i haven't experiencing similiar issues in real life.
