### ISSUE TITLE
Update integrations.json

### ISSUE THREAD

**Issue by rozza** [apache/airflow#23748]
### What do you see as an issue?

Some providers with logos are missing their logos on the main page.  #13717 added missing logs but it looks like they haven't been included in integrations.json  - For example: https://github.com/apache/airflow-site/blob/main/landing-pages/site/static/integrations.json#L503-L505 is missing a logo but it was added in #13717.

### Solving the problem

Rerun `./scripts/tools/generate-integrations-json.py` to generate the integrations.json file with the logos.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rozza** [comment]
I'm not sure how to submit a pr to fix this one. I found this issue investigating #23746.

**Comment by potiuk** [comment]
> I'm not sure how to submit a pr to fix this one. I found this issue investigating #23746.

Clone airflow-site repo and re-run generate-integrations I guess :)

**Comment by potiuk** [comment]
'Before using this script, set the environment variable AIRFLOW_SITE_DIRECTORY. This variable '
        'should contain the path to the airflow-site repository directory. '
        '${AIRFLOW_SITE_DIRECTORY}/docs-archive must exists.'
