### ISSUE TITLE
Apache Airflow 2.3.0 has non release version

### ISSUE THREAD

**Issue by Nyantechnolog** [apache/airflow#23752]
### Apache Airflow version

2.3.0 (latest released)

### What happened

I tried apache/airflow:2.3.0 and apache/airflow:2.3.0-python3.9 docker images
both of them has 
Version: 2.3.0
Git Version: .**dev0**+6b772f68db4f80b01ede836ddd47437d4aa1b43d.dirty
at the bottom in ui.

My previous version was
Version: 2.2.5
Git Version: .**release**:2.2.5+7c3513903462511212df742263a49ec1f729ec0e

### Operating System

docker 

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is not a problem with docker image - this is the problem with released Airlfow Version in PyPI. We are aware of that and we cannot change it in 2.3.0 but it will be fixed in the upcoming 2.3.1.

**Comment by potiuk** [comment]
cc: @jedcunningham @ephraimbuddy - seems that one is important for a few people :)
