### ISSUE TITLE
Received SIGTERM. Terminating subprocesses

### ISSUE THREAD

**Issue by SolinTao** [apache/airflow#23770]
### Apache Airflow version

2.2.4

### What happened

My program flow is as follows:
Step1： parent process ——> Step2：start three child processes ( use multiprocessing.Process ) ——> Step3：wait for the child process to finish.
The following error message appears in step 3：
![image](https://user-images.githubusercontent.com/26808654/168945788-29e9939c-4058-4631-acce-8c5746496dab.png)

Why does the process receive an exception signal when subprocess terminates, and how can I resolve it? 

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp=2.0.1
apache-airflow-providers-http=2.0.3
apache-airflow-providers-imap==2.2.0
apache-airflow-providers-mysql==2.2.0 (I use pymysql)
apache-airflow-providers-redis==2.0.1
apache-airflow-providers-sqlite==2.1.0

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pingzh** [comment]
hi @SolinTao what's this `parent process`? is this your airflow task?

also it will be great if you can include more log message before my selected area

![image](https://user-images.githubusercontent.com/8662365/168951941-d0317f4d-a18f-48f7-852e-a6a836c3b66b.png)

**Comment by SolinTao** [comment]
hi @pingzh ，parent process is my airflow task. There is no additional useful log information except the task log. I'm sorry I didn't make it clear,  I used [pandarallel ](https://pypi.org/project/pandarallel/)package in my program. I delete ‘multiprocessing.Process‘ and just keep pandarallel, but there was still an error message. 
`{taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses`

By the way, is Airflow allowed to use multiple cpus by default in multiple processes? (I didn't change the default configuration)
`[operators]
default_owner = airflow
default_cpus = 1
default_ram = 512
default_disk = 512
default_gpus = 0`
