### ISSUE TITLE
Add an AWS operator for Create RDS Database

### ISSUE THREAD

**Issue by ferruzzi** [apache/airflow#23822]
### Description

@eladkal suggested we add the operator and then incorporate it into https://github.com/apache/airflow/pull/23681.  I have a little bit of a backlog right now trying to get the System Tests up and running for AWS, but if someone wants to get to it before me, it should be a pretty easy first contribution.

The required API call is documented [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.create_db_instance) and I'm happy to help with any questions and./or help review it if someone wants to take a stab at it before I get the time.

### Related issues

Could be used to simplify https://github.com/apache/airflow/pull/23681

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eskarimov** [comment]
Hello everyone, I'd be happy to work on this issue.

**Comment by ferruzzi** [comment]
Sweet, thanks.   Let me know if you need any help.

**Comment by josh-fell** [comment]
@eskarimov All yours!
