### ISSUE TITLE
Airflow2.3 constraints file conflict

### ISSUE THREAD

**Issue by alexopoulos7** [apache/airflow#23831]
### Apache Airflow version

2.3.0 (latest released)

### What happened

I had tried to install airflow 2.3.0 with constraints:
"https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.8.txt" but could not because of the following **conflict**: 

```
The conflict is caused by:
           The user requested docutils==0.18.1
           sphinx 4.5.0 depends on docutils<0.18 and >=0.14
```

### What you think should happen instead

I think that we should replace Sphinx with version 5.0

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Don't use "all" when you install airflow. It's only for development and test purpose. There is no reason you should install airflow with "all" dependencies - pick those that you actually need.

We just updated desription for it to be clear - will be released in 2.3.1:
https://github.com/potiuk/airflow/blob/main/docs/apache-airflow/extra-packages-ref.rst#bundle-extras
