### ISSUE TITLE
Breeze is unable to install pipx on ubuntu 20.04

### ISSUE THREAD

**Issue by sploink36** [apache/airflow#23843]
### Apache Airflow version

2.3.0 (latest released)

### What happened

when trying to run airflow breeze with the `./breeze start-airflow` command breeze tries to install pipx but fails and doesn't start up as a result

### What you think should happen instead

breeze should be able to run airflow with a breeze

### How to reproduce

type `./breeze start-airflow` at the command line.

this is what's returned:
```
sudo ./breeze start-airflow

The 'pipx' is not on path. It should be installed and 'pipx' should be available on your PATH.

Please confirm Installing pipx?. Are you sure? [y/N/q]
y
The answer is 'yes'. Installing pipx?. This can take some time!
./breeze: line 55: python: command not found
```

### Operating System

debian(buster)

### Versions of Apache Airflow Providers

N/A

### Deployment

Docker-Compose

### Deployment details

airflow breeze with this git commit sha: 5802e4e6dd0ef6508215e12b4e2924b9ce1a71c9

### Anything else

this problem occurs everytime.

### Are you willing to submit PR?

- [ ] No I am willing to submit a PR.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sploink36** [comment]
@potiuk Is this [PR](https://github.com/apache/airflow/pull/23827) related to this issue?

**Comment by potiuk** [comment]
No. The problem is that you have no `python` installed. There are a few prerequisites to run Breeze and having "python" on the path is one of them. Also `./breeze` is just a wrapper around automating some installation steps, but in order to install Breeze, you need to follow pre-requisites described in the docs - including `pipx` - https://github.com/apache/airflow/blob/main/BREEZE.rst#prerequisites 

Make sure to follow the prerequisites. 

BTW. If you have no python on your path. If you want to make python development, you should make sure that well ... you have python around.

**Comment by potiuk** [comment]
BTW. you are running 'sudo ./breeze start-airflow` - which is almost for sure terribly wrong and this is the root of your problems. WHY ON EARTH are you using sudo to run breeze?

**Comment by sploink36** [comment]
@potiuk I'm using sudo to run breeze as this is a relatively new install of this OS and I haven't added docker to user group yet in ubuntu so I need to run docker and apps that use docker with sudo.

**Comment by potiuk** [comment]
> @potiuk I'm using sudo to run breeze as this is a relatively new install of this OS and I haven't added docker to user group yet in ubuntu so I need to run docker and apps that use docker with sudo.

Then don't. Breeze is intended to be used by user. And if you want to use it with sudo, you still can of course. Just make sure you have python on your path when you sudo, and realise consequences (that all your files will be created as root user).

But If you look closely at breeze's prerequistes it is very clearly stated that you should not do it:

> Permissions: Configure to run the docker commands directly and not only via root user. Your user should be in the docker group. See [Docker installation guide](https://docs.docker.com/install/) for details.
