### ISSUE TITLE
Main constraints for Airflow downgrade cncf.kubernetes provider to 3.1.2 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23858]
### Apache Airflow version

main (development)

### What happened

The cncf.kubernetes in constraints should be bumped to 4.0.2 (automatically), but for some reason it is downgraded to 3.1.2 - we need to investigate why.

### What you think should happen instead

the cncf.kubernetes should be updated to 4.0.2.

### How to reproduce

Just run generate constraints - all the providers are correctly set to latest version but only cncf.kubernetes is 3.1.2

### Operating System

Any

### Versions of Apache Airflow Providers

cncf.kubernetes == 3.1.2

### Deployment

Other

### Deployment details

CI

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@potiuk was this task completed?

**Comment by potiuk** [comment]
Yeah. It was some strange issue with dependencies. Solved long time ago.
