### ISSUE TITLE
Does airflow have task configuration based on worker machine cpu or memory load balancing

### ISSUE THREAD

**Issue by zqd759592942** [apache/airflow#23863]
### What do you see as an issue?

Does airflow have task configuration based on worker machine cpu or memory load balancing

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
No. And please next time follow what you are edlladvised to when you open an issue. You should open Discussion when you have question. NOT issue
