### ISSUE TITLE
Don’t show traceback on 'breeze tests' subprocess returning non-zero

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#23868]
### Body

Currently, if any tests fail when `breeze tests` is run, Breeze 2 would emit a traceback pointing to the `docker-compose` subprocess call. This is due to Docker propagating the exit call of the underlying `pytest` subprocess. While it is technically correct to emit an exception, the traceback is useless in this context, and only clutters output. It may be a good idea to add a special case for this and suppress the exception.

A similar situation can be observed with `breeze shell` if you run `exit 1` in the shell.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Yep. Most of the commands had it already. Also I tihnk `shell` has it already (but maybe there is another case):

<img width="738" alt="Screenshot 2022-05-24 at 17 44 35" src="https://user-images.githubusercontent.com/595491/170077436-a801a830-d85a-46a1-ab37-b798c897273b.png">

**Comment by potiuk** [comment]
Fix in #23897
