### ISSUE TITLE
Add Templated SQL Check Operators for Columns and Tables

### ISSUE THREAD

**Issue by denimalpaca** [apache/airflow#23874]
### Description

The new SQL Check Operators would provide templated quality checks so users could quickly and easily add common data quality checks on columns and tables. The resulting output of the tests would be saved in the dictionary passed in containing the check names and parameters.

### Use case/motivation

Current SQL Check Operators are extremely broad, but limited to aggregate checks, making them confusing and sometimes redundant with respect for each other. The new checks would allow a more streamlined experience, and would save enough information that the results can be parsed in OpenLineage, which old checks cannot be.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
All yours @denimalpaca!
