### ISSUE TITLE
Kubernetes pods are not staying alive when delete_worker_pods set to False

### ISSUE THREAD

**Issue by adityasharmaKH** [apache/airflow#23893]
### Apache Airflow version

2.1.4

### What happened

I am setting `delete_worker_pods = False` and expecting  pod to remain after the job is complete. However, once the job is complete the pod is deleting.

apache-airflow-providers-cncf-kubernetes==2.1.0
kubernetes==11.0.0

### What you think should happen instead

Pod should not delete after the job completion.

### How to reproduce

Run any job with airflow version 2.1.4, apache-airflow-providers-cncf-kubernetes==2.1.0 and kubernetes==11.0.0 and in the Kubernetes pods setting set `delete_worker_pods` to False. 

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.3.0
apache-airflow-providers-cncf-kubernetes==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
We have revamped kubernetes with new version of kubernetes library in 2.3.* - @dstandish - do you think that one is likely to be solved by it ?

**Comment by eladkal** [comment]
This report is against old versions. I can say that I worked with newer versions and I did not experienced that.
If you are still experiencing the issue with latest Airflow with supported K8s version please let us know.
