### ISSUE TITLE
Wrong dependecy version of requests for Databricks provider

### ISSUE THREAD

**Issue by yershovkiril** [apache/airflow#23917]
### Apache Airflow Provider(s)

databricks

### Versions of Apache Airflow Providers

apache-airflow-providers-databricks==2.7.0

### Apache Airflow version

2.2.2

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other

### What happened

There was added import statement from the `requests` library to `airflow/providers/databricks/hooks/databricks_base.py` by [this MR](https://github.com/apache/airflow/pull/22422/files#diff-bfbc446378c91e1c398eb07d02dc333703bb1dda4cbe078193b16199f11db8a5R34).

But minimal version of requests wasn't bumped up to `>=2.27.0`, as we can see[ it's still >=2.26.0](https://github.com/apache/airflow/blob/main/setup.py#L269), but that JSONDecodeError class added to `requests` library starting from [2.27.0 (see release notes)](https://github.com/psf/requests/releases/tag/v2.27.0).

It brings inconsistency between libraries and leads to following error: 
```
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/databricks/hooks/databricks.py", line 33, in <module>
    from airflow.providers.databricks.hooks.databricks_base import BaseDatabricksHook
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/databricks/hooks/databricks_base.py", line 34, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' 
```

### What you think should happen instead

it breaks DAGs

### How to reproduce

Use any Databricks operator with `requests==2.26.0`, which is defined is minimal compatible version

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by collinmcnulty** [comment]
I have also reproduced this error and confirmed that adding `requests>=2.27,<3` fixes the problem.

**Comment by koconder** [comment]
Started a PR for this based on the comment/test from @collinmcnulty as https://github.com/apache/airflow/pull/23927
