### ISSUE TITLE
Airflow 2.3.1 : "CryptographyDeprecationWarning: Blowfish has been deprecated" message on gunicorn 20.1.0 startup

### ISSUE THREAD

**Issue by gbonazzoli** [apache/airflow#23925]
### Apache Airflow version

2.3.1 (latest released)

### What happened

I get the following warning on the startup of gunicorn:

```
root@airflow:~/airflow# airflow webserver -p 8080
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 1 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat: 
=================================================================
[2022-05-26 05:32:46 +0200] [396086] [INFO] Starting gunicorn 20.1.0
/usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236 CryptographyDeprecationWarning: Blowfish has been deprecated
[2022-05-26 05:32:46 +0200] [396086] [INFO] Listening at: http://0.0.0.0:8080 (396086)
```

### What you think should happen instead

The message is self explaining. 

The configuration file (webserver_config.py) has the following:

`AUTH_TYPE = AUTH_LDAP
`
I think this settings is responsible of the message, infact with AUTH_DB gunicorn doesn't cry.

### How to reproduce

Just start airflow webserver

### Operating System

Ubuntu 20.04.4 LTS

### Versions of Apache Airflow Providers

```
apache-airflow-providers-celery==2.1.4
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-microsoft-mssql==2.1.3
apache-airflow-providers-microsoft-winrm==2.0.5
apache-airflow-providers-mysql==2.2.3
apache-airflow-providers-openfaas==2.0.3
apache-airflow-providers-oracle==2.2.3
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-samba==3.0.4
apache-airflow-providers-sftp==2.6.0
apache-airflow-providers-sqlite==2.1.3
apache-airflow-providers-ssh==2.4.4
```

### Deployment

Virtualenv installation

### Deployment details

Airflow all in one on a LXD container

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Related issue https://github.com/paramiko/paramiko/issues/2038

**Comment by potiuk** [comment]
I wil take a look at that one shortly (i.e. next week  due to Summit). It's not clear for me what blocks paramiko from upgrading to the latest version - even in main).  Stay tuned.

**Comment by eladkal** [comment]
> It's not clear to me what blocks paramiko from upgrading to the latest version - even in main

In both main and 2.3.1 `paramiko` is in latest version

**Comment by eladkal** [comment]
The 2.3.1 constraints were refreshed in https://github.com/apache/airflow/commit/edf8c465b95479bac53119e465c5bf9613b8b33c
10 days ago..
@gbonazzoli Did you use updated constraints?

**Comment by potiuk** [comment]
Ahhh Right - I think I checked it in my own fork :facepalm: . Yep. Paramiko was updated in the latest versions. So all is good. Closing.

**Comment by gbonazzoli** [comment]
@eladkal @potiuk 

If it can be of help, I manually upgraded paramiko without having any complain from pip:

```
root@airflow:~# pip3 install --upgrade paramiko
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.10.4)
Collecting paramiko
  Downloading paramiko-2.11.0-py2.py3-none-any.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.9/212.9 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko) (37.0.2)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko) (1.3.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from paramiko) (1.14.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.21)
Installing collected packages: paramiko
  Attempting uninstall: paramiko
    Found existing installation: paramiko 2.10.4
    Uninstalling paramiko-2.10.4:
      Successfully uninstalled paramiko-2.10.4
Successfully installed paramiko-2.11.0
```

**Comment by potiuk** [comment]
That's expected. Just FYI - you should use constraints to install Airflow https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

**Comment by gbonazzoli** [comment]
@potiuk 

Many thanks, I wasn't aware of the constraints file existance. I will do it next time.

Donwloaded it, and it contains `paramiko==2.11.0`.
