### ISSUE TITLE
No option to set blocksize when retrieving a file in ftphook 

### ISSUE THREAD

**Issue by yfyg** [apache/airflow#23935]
### Apache Airflow version

2.0.0

### What happened

using ftphook, im trying to download a file in chunks but the deafult blocksize is 8192 and cannot be changed.
retrieve_file code is calling conn.retrbinary(f'RETR {remote_file_name}', callback) but no blocksize is passed while this function is declared:
 def retrbinary(self, cmd, callback, blocksize=8192, rest=None):

### What you think should happen instead

allow passing a blocksize

### Operating System

gcp

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@yfyg It seems like you know what the feature implementation should be and can easily test it too. Do you want to submit a PR for this? Airflow has over 2K contributors and we love when new people come onboard!

**Comment by potiuk** [comment]
Feel free
