### ISSUE TITLE
Only autorefresh active dags on home page

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23949]
### Description

In https://github.com/apache/airflow/pull/22900, we added auto-refresh for the home page. Right now, we pass all dag_ids to the `last_dagruns`, `dag_stats` and `task_stats` endpoints. During auto-refresh, we should only request info for dags that are not paused. 

On page load, we still want to check all three endpoints for all dags in view. But for subsequent auto-refresh requests we should only check active dags.

See [here](https://github.com/apache/airflow/blob/main/airflow/www/static/js/dags.js#L429) for where the homepage auto-refresh lives.

### Use case/motivation

Smaller requests should make a faster home page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hankehly** [comment]
Please assign this to me

**Comment by potiuk** [comment]
Assigned

**Comment by hankehly** [comment]
@bbovenzi @potiuk Please see #24770 at your earliest convenience.
