### ISSUE TITLE
Add backfill icon to grid view dag runs

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23945]
### Description

In the grid view, we use a play icon to indicate manually triggered dag runs. We should do the same for a backfilled dag run.

Possible icons can be found [here](https://react-icons.github.io/react-icons).

Note: We use the manual run icon in both the [dag run bar component](https://github.com/apache/airflow/blob/main/airflow/www/static/js/grid/dagRuns/Bar.jsx) and in the [details panel header](https://github.com/apache/airflow/blob/main/airflow/www/static/js/grid/details/Header.jsx)

### Use case/motivation

Help users quickly differentiate between manual, scheduled and backfill runs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dskoda1** [comment]
I'd like to work on this as part of the workshop.

**Comment by eladkal** [comment]
assigned!
