### ISSUE TITLE
Add missing parameter documentation in `DatabricksSubmitRunOperator` and `DatabricksSqlOperator`

### ISSUE THREAD

**Issue by josh-fell** [apache/airflow#23954]
### Body

Currently the following modules are missing certain parameters in their docstrings. Because of this, these parameters are not captured in the [Python API docs for the Databricks provider](https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/_api/airflow/providers/databricks/index.html).

- [ ] DatabricksSubmitRunOperator: `tasks`
- [ ] DatabricksSqlOperator: `do_xcom_push`
   - Granted this is really part of the `BaseOperator`, but this operator specifically sets the default value to False so it would be good if this was explicitly listed for users.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by yuyafukuchi** [comment]
Hello! Can I pick this one?

**Comment by eladkal** [comment]
assigned

**Comment by Bowrna** [comment]
I will try fixing this issue @eladkal @josh-fell

**Comment by potiuk** [comment]
Feel free.
