### ISSUE TITLE
Add `TrinoToSlackOperator`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#23963]
### Body

Runs a single query against Trino and send output to Slack channel
functionality should be similar to existed `SnowflakeToSlackOperator`

https://github.com/apache/airflow/blob/e2401329345dcc5effa933b92ca969b8779755e4/airflow/providers/snowflake/transfers/snowflake_to_slack.py#L32

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by SaumyaBhushan** [comment]
@eladkal How can I do this?

**Comment by eladkal** [comment]
@SaumyaBhushan Follow https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst

**Comment by eladkal** [comment]
Closed in favor of https://github.com/apache/airflow/issues/24243
