### ISSUE TITLE
Set color of Operators in cloud_sql.py

### ISSUE THREAD

**Issue by ishiis** [apache/airflow#23999]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==5.0.0

### Apache Airflow version

2.1.2

### Operating System

GCP Container

### Deployment

Composer

### Deployment details

composer-1.17.1-airflow-2.1.2

### What happened

No color is set for the GraphView legends. All CloudSQLOperator legends are white.

<img width="970" alt="legends" src="https://user-images.githubusercontent.com/12693596/170856092-0f9af91a-fbe9-47d9-9a9e-6e572b45fdfc.png">

### What you think should happen instead

A color should be set to the Operators in cloud_sql.py.

### How to reproduce

Add example_cloud_sql.py to Dags and look at GraphView.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
feel free to raise PR
