### ISSUE TITLE
Make port as optional argument

### ISSUE THREAD

**Issue by ankurbajaj9** [apache/airflow#24022]
### Apache Airflow version

2.3.1 (latest released)

### What happened

my webhdfs is running behind a proxy. 
I need to give a complicated URL and do not want to add port in front of the URL

So there are two options 
1) use Schema to add stuff before webhdfs/v1
2) make adding of port optional so that complete url before webhdfs can be provided in the hostname

### What you think should happen instead

error while connecting to webhdfs
[2022-05-27, 15:24:43 UTC] {webhdfs.py:89} INFO - Read operation on namenode abc.xyz.com failed with error: b''

### How to reproduce

run webhdfs behind a proxy without exposing the actual servers

### Operating System

Debian

### Versions of Apache Airflow Providers

2.2.3 apache-airflow-providers-apache-hdfs

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to propose a PR.
