### ISSUE TITLE
CRSF bad request error when redirected from another website

### ISSUE THREAD

**Issue by furkan-pensa** [apache/airflow#24051]
### Apache Airflow version

2.2.5

### What happened

We are giving a link to the Airflow webserver running in a docker container from our UI and when the Airflow UI is opened via that link it errors out saying "Bad Request. The CSRF session token is missing.". When this happens there is no reliable way to make the webserver work again. When I type the URL and and access the webserver, it works until I click on the link on our UI. Then it breaks and doesn't work even if I type the URL.

### What you think should happen instead

There should be a more clear documentation on how to configure and use the CSRF token (aka `secret_key` in webserver section of airflow.cfg).

### How to reproduce

From another website access the Airflow webserver using a hyperlink like below.
```html
<a
  :href="`http://localhost:8080`"
  target="_blank"
>
  Airflow
</a>
```

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

apache/airflow:2.2.5-python3.9 docker image

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Tejalgnrml** [comment]
Similar issue, upon redirecting the webserver ip through a domain i am facing this issue
Any solutions?
Thanks in advance

**Comment by potiuk** [comment]
Possibly the guide might help you. https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html
