### ISSUE TITLE
ExternalTaskSensor manually trigger

### ISSUE THREAD

**Issue by Lee2532** [apache/airflow#24100]
### Description

when the External Task Sensor is manually executed, not work

### Use case/motivation

We can add options to perform functions such as scheduling when executing manually.

Since we FAIL the DAG with External Task Sensor when executing manually, we add logic to pass when executing manually

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee2532** [comment]
When using an external task sensor, running DAG manually does not work normally.
Therefore, I would like to add a parameter that allows the corresponding external task sander to pass when triggering the corresponding TASK manually.

for example
`
wait_airflow_test = ExternalTaskSensor(
        task_id="wait_airflow_test",
        external_dag_id="airflow_sample",
        external_task_id="start",
        allowed_states=["success"],
        failed_states=None,
        execution_delta=None,
        execution_date_fn=None,
        check_existence=True,
        dag=dag,
        default_args=dag_args,
        mode='reschedule',
        timeout=5,
        wait_task=False
    )


`

**Comment by potiuk** [comment]
How about [params](https://airflow.apache.org/docs/apache-airflow/stable/concepts/params.html?highlight=params)  - I still do not understand what you are asking for - but that would be my guess tha it's likely what you want. In either case I am converting that to a discussion until this is clarified.
