### ISSUE TITLE
Add support for KEDA HPA Config to Helm Chart

### ISSUE THREAD

**Issue by Swalloow** [apache/airflow#24103]
### Description

> When managing the scale of a group of replicas using the HorizontalPodAutoscaler, it is possible that the number of replicas keeps fluctuating frequently due to the dynamic nature of the metrics evaluated. This is sometimes referred to as thrashing, or flapping.
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#flapping

Sometimes clusters need to restrict the flapping of Airflow worker replicas.
KEDA supports [`advanced.horizontalPodAutoscalerConfig`](https://keda.sh/docs/1.4/concepts/scaling-deployments/).
It would be great if the users would have the option in the helm chart to configure scale down behavior.

### Use case/motivation

KEDA currently cannot set advanced options.
We want to set advanced options like `scaleDown.stabilizationWindowSeconds`, `scaleDown.policies`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to make PR . Assigned you!
