### ISSUE TITLE
Grid JavaScript error on new task added

### ISSUE THREAD

**Issue by tothandor** [apache/airflow#24162]
### Apache Airflow version

2.3.1 (latest released)

### What happened

I have added a new task to an existsting workflow (DAG), where the other tasks already had previous runs.
When I added the new task, the grid became inaccessible, because it wanted to get `runId`s for the new task, which did not exist.
An error occured in the grid.<hash>.js, but since the file is minified/obfuscated, it's unclear for me where exactly.

### What you think should happen instead

The grid should handle missing `runId` without causing an exception.

### How to reproduce

1) Create a simple dag, with a few dummy tasks, and let it run a few times. Check out the grid (it should be okay).
2) After that, add a new dummy task, and check out the grid again. The grid's area will be empty, and the JS console will have the following error: `TypeError: Cannot read properties of null (reading 'runId')`

Probably any other scenarios where the tasks run history is uneven, could also cause this error.

### Operating System

Linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Seems to be same as 

https://github.com/apache/airflow/discussions/23908
https://github.com/apache/airflow/issues/23933

cc @bbovenzi

**Comment by bbovenzi** [comment]
Yes, this seems to be a duplicate. I just tried the exact steps in main and it is working as expected. 

Fixed in https://github.com/apache/airflow/pull/23947 for 2.3.2
