### ISSUE TITLE
`BigQueryCreateExternalTableOperator` uses deprecated function

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#24160]
### Body

The `BigQueryCreateExternalTableOperator` uses `create_external_table`:

https://github.com/apache/airflow/blob/cd49a8b9f64c57b5622025baee9247712c692e72/airflow/providers/google/cloud/operators/bigquery.py#L1131-L1147

this function is deprecated:
https://github.com/apache/airflow/blob/511d0ee256b819690ccf0f6b30d12340b1dd7f0a/airflow/providers/google/cloud/hooks/bigquery.py#L598-L602

**The task:**
Refactor/change the operator to replace `create_external_table` with  `create_empty_table`.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by cswpy** [comment]
Hello @eladkal, I can take this issue.

**Comment by eladkal** [comment]
@cswpy assigned

**Comment by cswpy** [comment]
Thanks for assigning me the task.
I took a look at the code and I want to make sure that my approach is correct before proceeding. I should create a `table_resouce` (where I would define info relating to the external table) object to pass into the `create_empty_table`?

**Comment by potiuk** [comment]
I think it's better to discuss with the code and in PR - make a draft PR with your proposal and it can be discussed there - it's far easier this way because the discussion can be focused around the actual code without looking it up and guessing what you really want to do @cswpy.

**Comment by cswpy** [comment]
Thanks for the tip @potiuk. I will come up with something and submit a PR.
