### ISSUE TITLE
Status of AIP-47

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#24168]
Summary of ALL issues: for 46 issues
   Completed and closed issues: 44/46: 95.65%
   Completed files 245/277 = 88.45%

 Issues that are not completed and are still opened:

 * [Migrate Google example DAGs to new design](https://github.com/apache/airflow/issues/22447): 71/89 : 79.78%
 * [Migrate Google system tests to new design](https://github.com/apache/airflow/issues/22430): 57/71 : 80.28%

 Issues that are completed and are already closed:

 * [Amazon AppFlow System Test](https://github.com/apache/airflow/issues/27566)
 * [Migrate dbt example DAGs to new design](https://github.com/apache/airflow/issues/22472)
 * [Migrate Zendesk example DAGs to new design](https://github.com/apache/airflow/issues/22471)
 * [Migrate Yandex example DAGs to new design](https://github.com/apache/airflow/issues/22470)
 * [Migrate Trino example DAGs to new design](https://github.com/apache/airflow/issues/22469)
 * [Migrate Telegram example DAGs to new design](https://github.com/apache/airflow/issues/22468)
 * [Migrate Tableau example DAGs to new design](https://github.com/apache/airflow/issues/22467)
 * [Migrate Snowflake example DAGs to new design](https://github.com/apache/airflow/issues/22466)
 * [Migrate Slack example DAGs to new design](https://github.com/apache/airflow/issues/22465)
 * [Migrate Singularity example DAGs to new design](https://github.com/apache/airflow/issues/22464)
 * [Migrate Salesforce example DAGs to new design](https://github.com/apache/airflow/issues/22463)
 * [Migrate SQLite example DAGs to new design](https://github.com/apache/airflow/issues/22461)
 * [Migrate Qubole example DAGs to new design](https://github.com/apache/airflow/issues/22460)
 * [Migrate Presto example DAGs to new design](https://github.com/apache/airflow/issues/22459)
 * [Migrate Postgres example DAGs to new design](https://github.com/apache/airflow/issues/22458)
 * [Migrate Plexus example DAGs to new design](https://github.com/apache/airflow/issues/22457)
 * [Migrate Papermill example DAGs to new design](https://github.com/apache/airflow/issues/22456)
 * [Migrate Opsgenie example DAGs to new design](https://github.com/apache/airflow/issues/22455)
 * [Migrate Neo4j example DAGs to new design](https://github.com/apache/airflow/issues/22454)
 * [Migrate MySQL example DAGs to new design](https://github.com/apache/airflow/issues/22453)
 * [Migrate Microsoft example DAGs to new design](https://github.com/apache/airflow/issues/22452)
 * [Migrate Jenkins example DAGs to new design](https://github.com/apache/airflow/issues/22451)
 * [Migrate JDBC example DAGs to new design](https://github.com/apache/airflow/issues/22450)
 * [Migrate Influx example DAGs to new design](https://github.com/apache/airflow/issues/22449)
 * [Migrate HTTP example DAGs to new design](https://github.com/apache/airflow/issues/22448)
 * [Migrate GitHub example DAGs to new design](https://github.com/apache/airflow/issues/22446)
 * [Migrate Elasticsearch example DAGs to new design](https://github.com/apache/airflow/issues/22445)
 * [Migrate Docker example DAGs to new design](https://github.com/apache/airflow/issues/22444)
 * [Migrate DingTalk example DAGs to new design](https://github.com/apache/airflow/issues/22443)
 * [Migrate Databricks example DAGs to new design](https://github.com/apache/airflow/issues/22442)
 * [Migrate Cncf.Kubernetes example DAGs to new design](https://github.com/apache/airflow/issues/22441)
 * [Migrate Asana example DAGs to new design](https://github.com/apache/airflow/issues/22440)
 * [Migrate Apache example DAGs to new design](https://github.com/apache/airflow/issues/22439)
 * [Migrate Amazon example DAGs to new design](https://github.com/apache/airflow/issues/22438)
 * [Migrate Alibaba example DAGs to new design](https://github.com/apache/airflow/issues/22437)
 * [Migrate Airbyte example DAGs to new design](https://github.com/apache/airflow/issues/22436)
 * [Migrate Snowflake system tests to new design](https://github.com/apache/airflow/issues/22434)
 * [Migrate Postgres system tests to new design](https://github.com/apache/airflow/issues/22433)
 * [Migrate Microsoft system tests to new design](https://github.com/apache/airflow/issues/22432)
 * [Migrate HTTP system tests to new design](https://github.com/apache/airflow/issues/22431)
 * [Migrate CNCF system tests to new design](https://github.com/apache/airflow/issues/22429)
 * [Migrate Asana system tests to new design](https://github.com/apache/airflow/issues/22428)
 * [Migrate Apache Beam system tests to new design](https://github.com/apache/airflow/issues/22427)
 * [Migrate Amazon system tests to new design](https://github.com/apache/airflow/issues/22426)

**Comment by potiuk** [comment]
cc: @bhirsz @chethanuk-plutoflume @ferruzzi @Bowrna

**Comment by Bowrna** [comment]
@potiuk This is the fix for https://github.com/apache/airflow/issues/22445
PR: https://github.com/apache/airflow/pull/22811

**Comment by potiuk** [comment]
@Bowrna  - the #22811  missed deletion of the original example. That's why I reopened it :).

**Comment by potiuk** [comment]
@Bowrna  - the #22811  missed deletion of the original example. That's why I reopened it :).

**Comment by Bowrna** [comment]
> @Bowrna - the #22811 missed deletion of the original example. That's why I reopened it :).

I have raised PR https://github.com/apache/airflow/pull/24172 to fix this @potiuk 
Thanks for pointing it to me :)

**Comment by potiuk** [comment]
> > @Bowrna - the #22811 missed deletion of the original example. That's why I reopened it :).
> 
> I have raised PR #24172 to fix this @potiuk Thanks for pointing it to me :)

Merged already and reflected in status :).

**Comment by potiuk** [comment]
Updated statis.

**Comment by potiuk** [comment]
Updated stats:

Summary of ALL issues: for 45 issues
Completed and closed issues: 38/45: 84.44%
Completed files 147/275 = 53.45%

Issues that are not completed and should be opened:

Issues that are not completed and are still opened:

https://github.com/apache/airflow/issues/22465: 0/1 : 0.00%
https://github.com/apache/airflow/issues/22447: 38/89 : 42.70%
https://github.com/apache/airflow/issues/22438: 13/36 : 36.11%
https://github.com/apache/airflow/issues/22436: 0/1 : 0.00%
https://github.com/apache/airflow/issues/22430: 29/71 : 40.85%
https://github.com/apache/airflow/issues/22426: 0/9 : 0.00%

**Comment by potiuk** [comment]
Slowly but surely we are getting there :)

Summary of ALL issues: for 45 issues
Completed and closed issues: 39/45: 86.67%
Completed files 156/275 = 56.73%

Issues that are not completed and are still opened:

https://github.com/apache/airflow/issues/22465: 0/1 : 0.00%
https://github.com/apache/airflow/issues/22447: 41/89 : 46.07%
https://github.com/apache/airflow/issues/22438: 15/36 : 41.67%
https://github.com/apache/airflow/issues/22436: 0/1 : 0.00%
https://github.com/apache/airflow/issues/22430: 32/71 : 45.07%
https://github.com/apache/airflow/issues/22426: 0/9 : 0.00%

**Comment by Bowrna** [comment]
@potiuk Could you check if Slack example DAGs are already merged? I found this PR merged #25137

**Comment by potiuk** [comment]
Yep. Just re-run the script and closed it.

Summary of ALL issues: for 45 issues
   Completed and closed issues: 40/45: 88.89%
   Completed files 171/275 = 62.18%

 Issues that are not completed and are still opened:

 * [Migrate Google example DAGs to new design](https://github.com/apache/airflow/issues/22447): 47/89 : 52.81%
 * [Migrate Amazon example DAGs to new design](https://github.com/apache/airflow/issues/22438): 20/36 : 55.56%
 * [Migrate Airbyte example DAGs to new design](https://github.com/apache/airflow/issues/22436): 0/1 : 0.00%
 * [Migrate Google system tests to new design](https://github.com/apache/airflow/issues/22430): 35/71 : 49.30%
 * [Migrate Amazon system tests to new design](https://github.com/apache/airflow/issues/22426): 0/9 : 0.00%

**Comment by eladkal** [comment]
we seem to miss some? for example:
https://github.com/apache/airflow/blob/main/airflow/providers/arangodb/example_dags/example_arangodb.py

**Comment by potiuk** [comment]
If It was added later then it is likely. Maybe someone can add a review after that as a cleanup.

**Comment by ferruzzi** [comment]
Yeah, I've noticed the same in the AWS package, some new ones have been added since so we'll have to do a "final pass" after the checklist is cleared.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/issues/22447: 52/89 : 58.43%
https://github.com/apache/airflow/issues/22438: 22/36 : 61.11%
https://github.com/apache/airflow/issues/22430: 39/71 : 54.93%
https://github.com/apache/airflow/issues/22426: 0/9 : 0.00%

**Comment by potiuk** [comment]
Summary of ALL issues: for 45 issues
   Completed and closed issues: 42/45: 93.33%
   Completed files 209/275 = 76.00%

 Issues that are not completed and are still opened:

 * [Migrate Google example DAGs to new design](https://github.com/apache/airflow/issues/22447): 58/89 : 65.17%
 * [Migrate Amazon example DAGs to new design](https://github.com/apache/airflow/issues/22438): 27/36 : 75.00%
 * [Migrate Google system tests to new design](https://github.com/apache/airflow/issues/22430): 45/71 : 63.38%

**Comment by potiuk** [comment]
Summary of ALL issues: for 45 issues
   Completed and closed issues: 42/45: 93.33%
   Completed files 213/275 = 77.45%

 Issues that are not completed and are still opened:

 * [Migrate Google example DAGs to new design](https://github.com/apache/airflow/issues/22447): 59/89 : 66.29%
 * [Migrate Amazon example DAGs to new design](https://github.com/apache/airflow/issues/22438): 29/36 : 80.56%
 * [Migrate Google system tests to new design](https://github.com/apache/airflow/issues/22430): 46/71 : 64.79%

**Comment by eladkal** [comment]
@potiuk i think we can close this one?
