### ISSUE TITLE
KubernetesPodOperator rendered template tab does not pretty print `env_vars`

### ISSUE THREAD

**Issue by ShahNewazKhan** [apache/airflow#24197]
### Apache Airflow version

2.2.5

### What happened

I am using the `KubernetesPodOperator` for airflow tasks in `Airflow 2.2.5` and it doesnot render the `env_vars` in the `rendered template` in a easily human consumable format as it did in `Airflow 1.10.x`

![image](https://user-images.githubusercontent.com/3241700/172024886-81fafb11-62c9-4daf-baff-7b47f3baf7d7.png)

### What you think should happen instead

The `env_vars` should be pretty printed in human legible form. 

### How to reproduce

Create a task with the `KubernetesPodOperator` and check the `Rendered template` tab of the task instance. 

### Operating System

Docker

### Versions of Apache Airflow Providers

2.2.5

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@ShahNewazKhan WDYT about submitting a PR for this? Airflow has over 2K contributors and it seems like you are in a great position to test an enhancement here.

I suspect it's a matter of adding `template_fields_renderers` attribute to `KubernetesPodOperator`; maybe even something similar to what's done in [this operator](https://github.com/apache/airflow/blob/b4a5783a2a90d9a0dc8abe5f2a47e639bfb61646/airflow/providers/microsoft/azure/operators/data_factory.py#L120) (and others).

There are [several rendering lexers](https://github.com/apache/airflow/blob/06856337a51139d66b1a39544e276e477c6b5ea1/airflow/www/utils.py#L530) that are available and this seems like it could be a matter of finding the correct one so `env_vars` is more human-readable in the UI.

**Comment by DMilmont** [comment]
I took a crack at this but I don't think it is easily possible to make the env_vars formatting nicer. I tried adding this line to the k8s pod operator ```    template_fields_renderers = {"env_vars": "json"}```

The env_vars look like this in the UI afterwards: 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3598125/173108728-db7dbcd6-0abd-4385-a4ff-39979e48f1c9.png">

In the past it looks like env_vars was just a dict so it was easy to format it with the json lexer however now env_vars are converted to a list of env_vars with [this function](https://github.com/apache/airflow/blob/2b2d97068fa45881672dab6f2134becae246f3f3/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py#L90-L105).

Perhaps there is a way to still make this work, but it isn't as straight forward as I was hoping.

**Comment by ShahNewazKhan** [comment]
Thanks for looking into this @DMilmont!

@josh-fell unfortunately I do not have the bandwidth to take this on, just reporting here, for the time being I will use the human readable `env_vars` `dict` passed in from the task definition.

**Comment by bdsoha** [comment]
Changing the render to use python solves the issue:

`template_fields_renderers = {"env_vars": "py"}`

**Comment by potiuk** [comment]
> Changing the render to use python solves the issue:
> 
> `template_fields_renderers = {"env_vars": "py"}`

Feel free to submit PR.

**Comment by DMilmont** [comment]
I will make a PR for this! Feel free to assign.
