### ISSUE TITLE
Create `SqlToSlackOperator`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#24243]
### Body

Currently we have `SnowflakeToSlackOperator` & `PrestoToSlackOperator`.
This task is to create a generic `SqlToSlackOperator` to be compatible with all hooks that has `get_pandas_df` function.
The new operator should be in `providers/slack/transfers/sql_to_slack.py`, once completed we can also deprecate `SnowflakeToSlackOperator` & `PrestoToSlackOperator`.

A good resource for reference can be `SqlToS3Operator` which the first part of the operator (running query and creating dataframe should be identical), the 2nd part of creating the slack message should be very similar to what the current operators do.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by alexkruc** [comment]
I'm willing to take this one :) 
Hopefully, I could manage my way around this issue :)

**Comment by potiuk** [comment]
assigned you
