### ISSUE TITLE
Blank page on grid panel when changing tasks of a dag

### ISSUE THREAD

**Issue by geoffreyaldebert** [apache/airflow#24280]
### Apache Airflow version

2.3.1

### What happened

After I added tasks on a specific dag, Airflow grid panel was a blank page.
I manage to resolve it by removing all previous dag runs. The grid panel then displayed normally.
For info, this problem was managed automatically in past versions.

### What you think should happen instead

Automatically manage architecture change in a specific dag and display latest architecture on grid panel instead of a blank page.

### How to reproduce

Import a dag, change its structure (rename task, add new task) and go to grid panel.

### Operating System

debian 11

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This has been fixed in Airlfow 2.3.2 https://github.com/apache/airflow/issues/23960 - please upgrade.
