### ISSUE TITLE
Previous DAG run task group instances are showing same status as current DAG run

### ISSUE THREAD

**Issue by tagoad** [apache/airflow#24293]
### Apache Airflow version

2.3.2 (latest released)

### What happened

I updated to 2.3.2 today and while i love the new additions to the task groups ui i am getting weird behavior with their statuses. The previous run task groups status is changing to whatever the current run status is:

![image](https://user-images.githubusercontent.com/43684949/172405342-690dce8f-f3ca-4e5f-b4ed-67356e35e87a.png)

As you can see the top task group finished completely in the previous run but is now showing deferred because the most recent has that status. Same with the one below, it is showing running even though it is actually complete. I can post a video of all this happening real time if needed.

### What you think should happen instead

They should show their own status, not the most recent one.

### How to reproduce

All of my DAGs are doing it, so seems like you just need to have multiple runs on a DAG with task groups to reproduce.

### Operating System

Windows 10

### Deployment

Astronomer

### Deployment details

Currently developing locally, will not be pushing this version to deployment until this is resolved.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Fixed in [#24327](https://github.com/astronomer/airflow/issues/24327)
