### ISSUE TITLE
Specify an image pull secret

### ISSUE THREAD

**Issue by onemec** [apache/airflow#24303]
### Description

Add a parameter `images.airflow.imagePullSecrets` to support [this](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) secret for fetching airflow images.

### Use case/motivation

When deploying custom images (e.g. the extended images with [DAGs embedded](https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#bake-dags-in-docker-image) or dependencies installed) they are often pushed somewhere like a private Gitlab repository. To successfully pull them after, secrets would need to be specified similar to [this](https://docs.bitnami.com/kubernetes/infrastructure/apache-airflow/configuration/change-image-version/).

### Related issues

Don't believe any other issue pertains, but may have missed something.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
@onemec  - why don't you make a PR with improved documentation? Since you already understand how it works and know (as a user) where you would like to see the documentation - you are absolutely best person to add such an improved documentation. You can easily become one of the > 2K contributors - many of them were (like you) users who saw the opportunity to improve the code or documentation. 

Shall I assign you the issue @onemec ?

**Comment by DSamuylov** [comment]
@onemec could you elaborate on how did you fix it? I am actually looking for a solution for the exactly the same use case that you describe in this issue.

**Comment by potiuk** [comment]
> @onemec could you elaborate on how did you fix it? I am actually looking for a solution for the exactly the same use case that you describe in this issue.

Ideally in the form of doc PR :)

**Comment by DSamuylov** [comment]
@potiuk I found a solution, and I could update the documentation. I think it makes sense to add it to this page: https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html under "Bake DAGs in Docker image"

But I am not familiar with the code base and I do not know what file should I modify. Could you guide me through the process?

**Comment by potiuk** [comment]
No guidance needed. Just click "suggest a change on this page" - bottom-right and you will get a PR opened where you will be able to add the doc modification using GitHub UI. 

Its even easier than wriitng an issue about it .

**Comment by DSamuylov** [comment]
Thank you, @potiuk, I thought it would be less straightforward. I made my suggestion.

**Comment by zhishangsun** [comment]
I met the problem as well, after reading the helm chart. I figured out a solution.

**Comment by adinamarca** [comment]
> I met the problem as well, after reading the helm chart. I figured out a solution. First, create a secret in you kubernetes cluster, detailed info can be found here [how to create a secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) Then, set the secretName in values.yaml.
> 
> ```
> registry:
>   secretName: yourSecretName
> ```

After 5 hours, I found your answer and now my cluster works with my container registry. Thank you.
