### ISSUE TITLE
Templating Git Sync directory

### ISSUE THREAD

**Issue by RaghavBatra** [apache/airflow#24302]
### Official Helm Chart version

1.6.0 (latest released)

### Apache Airflow version

2.3.0

### Kubernetes Version

1.22.6

### What happened

We use the official Airflow Helm Chart for deploying our production Airflow instances. 
However, whenever going from local to our dev instance, we run into a path issue since the GIT_SYNC_DEST field is hard-coded in the `_helpers.yaml` file (line 211). Because of the hard-coded value of "repo", all our local instance paths have to be changed to account for this. 

For example, `dags/example_dag.py` becomes `dags/repo/example_dag.py`. This becomes very tedious very quickly.
Reproducing the field below:
```
    - name: GIT_SYNC_DEST
      value: "repo"
```

### What you think should happen instead

 Is it possible to template this value so we can set to whatever works for each team?
Something like:

```
    - name: GIT_SYNC_DEST
      value: {{ .Values.dags.gitSync.dest | quote }}
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you if you want to make PR.

**Comment by RaghavBatra** [comment]
@jedcunningham the issue is that because `repo` is hard-coded, it will always be an additional folder, regardless of `dags_folder`.
