### ISSUE TITLE
'__type' is a required property exception when loading DAG Grid

### ISSUE THREAD

**Issue by pawellrus** [apache/airflow#24329]
### Apache Airflow version

2.3.0-2.3.1

### What happened

Grid for any DAG stop loading for some unknow issue. Instead I get exception in console and webserver's logs.

### What you think should happen instead

`{
  "detail": "'__type' is a required property\n\nFailed validating 'required' in schema['properties']['tasks']['items']['properties']['retry_delay']:\n    {'description': 'Time delta',\n     'nullable': True,\n     'properties': {'__type': {'type': 'string'},\n                    'days': {'type': 'integer'},\n                    'microseconds': {'type': 'integer'},\n                    'seconds': {'type': 'integer'}},\n     'required': ['__type', 'days', 'seconds', 'microseconds'],\n     'type': 'object'}\n\nOn instance['tasks'][0]['retry_delay']:\n    {'days': 0,\n     'microseconds': 0,\n     'objectType': 'TimeDelta',\n     'seconds': 300}",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "https://airflow.apache.org/docs/apache-airflow/2.3.1/stable-rest-api-ref.html#section/Errors/Unknown"
}`

### Operating System

Oracle Linux Server 7.6

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==3.4.0
apache-airflow-providers-celery==2.1.4
apache-airflow-providers-cncf-kubernetes==4.0.2
apache-airflow-providers-docker==2.7.0
apache-airflow-providers-elasticsearch==3.0.3
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-google==7.0.0
apache-airflow-providers-grpc==2.0.4
apache-airflow-providers-hashicorp==2.2.0
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-microsoft-azure==3.9.0
apache-airflow-providers-mysql==2.2.3
apache-airflow-providers-odbc==2.0.4
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-redis==2.0.4
apache-airflow-providers-sendgrid==2.0.4
apache-airflow-providers-sftp==2.6.0
apache-airflow-providers-slack==4.2.3
apache-airflow-providers-sqlite==2.1.3
apache-airflow-providers-ssh==2.4.4

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
1. If you changed from the browser console tab to the network tab, is there a specific endpoint that is failing?

2. Could you share an example DAG where this is occuring?

**Comment by pawellrus** [comment]
1) Endpoint /tasks is failing.

2) 
[dag.txt](https://github.com/apache/airflow/files/8881021/dag.txt)

**Comment by bbovenzi** [comment]
the get tasks endpoint was giving us some other trouble so we removed it in https://github.com/apache/airflow/pull/25359
