### ISSUE TITLE
"Example DAGs" link under kubernetes-provider documentation is broken. Getting 404

### ISSUE THREAD

**Issue by deeptansh** [apache/airflow#24331]
### What do you see as an issue?

_Example DAGs_ folder is not available for _apache-airflow-providers-cncf-kubernetes_ , which results in broken link on documentation page ( https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html ).

Getting 404 error when clicked on _Example DAGs_ link (https://github.com/apache/airflow/tree/main/airflow/providers/cncf/kubernetes/example_dags )

<img width="1464" alt="Screenshot 2022-06-08 at 9 01 56 PM" src="https://user-images.githubusercontent.com/11991059/172657376-8a556e9e-72e5-4aab-9c71-b1da239dbf5c.png">

<img width="1475" alt="Screenshot 2022-06-08 at 9 01 39 PM" src="https://user-images.githubusercontent.com/11991059/172657413-c72d14f2-071f-4452-baf7-0f41504a5a3a.png">

### Solving the problem

Folder named _example_dags_ should be created under link (https://github.com/apache/airflow/tree/main/airflow/providers/cncf/kubernetes/) which should include kubernetes specific DAG examples.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
This is a deeper issue than just the Kubernetes provider. With [AIP-47](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests), example DAGs are being migrated out of the `example_dags` folders and used as system tests. The docs point `tree/main/airflow/providers/.../example_dags` for all providers even past versions.

The question is, how should this link be handled for provider versions prior to the one which migrated the example DAGs for the AIP.

@potiuk WDYT? I shiver a little to update manually, but I assume there is a smarter way.

**Comment by potiuk** [comment]
The links should point to provider's branch version  of examples  I think

**Comment by potiuk** [comment]
Then in new docs we should get new links and in old ones, old links. But that's a bit "transition period" for now which makes it a bit difficult I think we should possibly Have two links for the time being to make it simpler and fix it afterwards.

**Comment by potiuk** [comment]
Working on a good fix.
