### ISSUE TITLE
BigQueryCreateEmptyTableOperator do not deprecated bigquery_conn_id yet

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#24343]
### Apache Airflow version

2.3.2 (latest released)

### What happened

`bigquery_conn_id` is deprecated for other operators like `BigQueryDeleteTableOperator`

and replaced by `gcp_conn_id` but it's not the case for `BigQueryCreateEmptyTableOperator`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kianelbo** [comment]
I also took the liberty of using `gcp_conn_id` in [BigQueryCreateExternalTableOperator](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py#L898) in my PR if that's okay.
