### ISSUE TITLE
Pattern parameter in S3ToSnowflakeOperator

### ISSUE THREAD

**Issue by grzegorzb1990** [apache/airflow#24360]
### Description

I would like to propose to add a pattern parameter to allow loading only those files that satisfy the given regex pattern.

This function is supported on the Snowflake side, it just requires passing a parameter to the COPY INTO command.
[Snowflake documentation/](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#loading-using-pattern-matching)

### Use case/motivation

I have multiple files with different schema in one folder. I would like to move to Snowflake only files which meet the given name filter, and I am not able to do it with the prefix parameter.

### Related issues

I am not aware

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it in PR. BTW there is no need to open an issue for it. Just Pull Request is enough.
