### ISSUE TITLE
Is there a dev emailing list?

### ISSUE THREAD

**Issue by josephykwang** [apache/airflow#244]
Hi,

I'm trying to check if airflow can be easily adapted for Hadoop ETL. Is there a developer emailing list?
More specifically, I run

export AIRFLOW_HOME=~/airflow

but I don't see ~/airflow/dags directory. Want to understand where and how to create a new workflow.
Also, is there a mechanism to set variables hierarchically so that different groups can have different
default priorities and policies.

Thanks in advance.

**Comment by mistercrunch** [comment]
`mkdir $AIRFLOW_HOME/dags`

By variables, do you mean `params` or `default_args`. To clarify the difference, `default_args` are used to define default arguments for operator constructors and `params` are used as a set of variables that can be used in the template and the "context" which is passed around to operators execute and various callbacks.

**Comment by mistercrunch** [comment]
Oh about the dev mailing list, do you mean a forum for contributors or for the community in general?

I recently created a Google group as a place holder and just now added a reference to in on the README.md, but it hasn't been used yet. I will post there when pushing new pypi release, when we have meet ups, ...

https://groups.google.com/forum/#!forum/airbnb_airflow

**Comment by maraca** [comment]
Oh neat - thoughts about an IRC channel too?

**Comment by mistercrunch** [comment]
No IRC just yet.
