### ISSUE TITLE
Airflow Grid view UI issues

### ISSUE THREAD

**Issue by lssatvik** [apache/airflow#24410]
### Apache Airflow version

2.3.2 (latest released)

### What happened

1) Task status is applied to task groups of all dag runs.
<img width="885" alt="image" src="https://user-images.githubusercontent.com/3456652/173344189-0dd97cc6-4ec6-4e2a-b73f-11174f04bece.png">

2) Task Name overlaps with "Hide details panel" UI element
<img width="844" alt="image" src="https://user-images.githubusercontent.com/3456652/173344332-783a1bc2-c95a-4b6c-9ed7-0532518cbba9.png">

### What you think should happen instead

1) Task group status of only corresponding dag run should be updated when a task status changes.
2) No overlap of html elements

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by argibbs** [comment]
Seconded. I literally just came here to raise the same issue. 😆  S/shot below of a (redacted, sorry) example dag. You can see that despite a single failed node, all dates for the containing task groups are red, I'd expect only the groups on the affected day to be red...

![image](https://user-images.githubusercontent.com/4406514/173350811-87ce208f-a86a-46ee-ac85-1022f81e3e8a.png)

**Comment by lssatvik** [comment]
The issue came about in 2.3.1, but was not fixed in 2.3.2. I don't understand why no one raised the issue earlier. And so I am here.
