### ISSUE TITLE
Asset compilation not running when building Airflow Docker image from Github url.

### ISSUE THREAD

**Issue by lmeerwood** [apache/airflow#24428]
### Apache Airflow version

2.3.2 (latest released)

### What happened

I followed the instructions on [building a docker image from Github](https://airflow.apache.org/docs/docker-stack/build.html#building-from-github). The resulting image resulted in the webpage missing key CSS and JS.

![image](https://user-images.githubusercontent.com/6085575/173447312-848b9e5e-1b0b-47ce-a265-6b5ca4f26b34.png)

Here's a snippet of the HTML code missing the links to the assets:
![image](https://user-images.githubusercontent.com/6085575/173447415-c70fa19f-a3ac-486c-9791-10d02f34ede9.png)

### What you think should happen instead

I think the CSS and JS should be applied.

### How to reproduce

Follow the steps [here](https://airflow.apache.org/docs/docker-stack/build.html#building-from-github), and then use the resulting image with the [docker-compose](https://airflow.apache.org/docs/apache-airflow/stable/docker-compose.yaml) provided. 

I have had the issue with all of the following version:
- My fork (https://github.com/lmeerwood/airflow/archive/main.tar.gz)
- Airflow main (https://github.com/apache/airflow/archive/main.tar.gz)
- Airflow 2.3.2 (https://github.com/apache/airflow/releases/download/2.3.2/apache-airflow-2.3.2-source.tar.gz)
- Airflow 2.3.0 (https://github.com/apache/airflow/releases/download/2.3.0/apache-airflow-2.3.0-source.tar.gz)

### Operating System

Ubuntu 20.04.4 LTS (WSL2)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lmeerwood** [comment]
I honestly completely forgot about this issue. I am unsure if this is still an issue or not. I am happy to have this ticket closed.

**Comment by potiuk** [comment]
Yeah. It's a rather small issue even if still there.
