### ISSUE TITLE
Allow for BaseOperator properties such as priority_weight to be determined via params

### ISSUE THREAD

**Issue by f0cus10** [apache/airflow#24426]
### Description

Request to make properties of tasks such as `priority_weight` and `pool_slots` be specified through variables passed into the `params`. 

Decorated tasks should also have the ability to specify these values based on external triggers or schedules. 

### Use case/motivation

**Motivation for `pool_slots`**
We execute the same DAG for running workflows that consume different amount of resources based on the client. The number of resources used for the client would be specified when the DAG is triggered. 

**Motivation for `priority_weight`**
Different tenants in our system also use the same DAG but have different priorities. Therefore, we need a way to prioritize DAG runs of one client over the other via `params` passed into the DAG

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This can't be done.
Templating happens as part of task being executed - this is after the task was scheduled and sent to worker.
The pool values are needed for the scheduler, so since templating happens only after you can not get this value during run time.
