### ISSUE TITLE
Add SQL Provider

### ISSUE THREAD

**Issue by denimalpaca** [apache/airflow#24422]
### Description

Adds a new SQL Provider for new SQL Check Operators.

### Use case/motivation

This will allow for faster development and maintenance of non-core SQL operators.

### Related issues

#23874 Add Templated SQL Check Operators for Columns and Tables

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Why do we need provider?

**Comment by potiuk** [comment]
I think in the future this might become an interesting pattern.

**Comment by eladkal** [comment]
Do you plan to move `DbApiHook` there?

Do you see it as sql provider or core provider with sql as standalone option?

**Comment by denimalpaca** [comment]
I can't really speak to `DbApiHook`, as I'm not sure what all the consequences may be. Not sure what a core provider is relative to other providers, but I see this as a SQL provider that would be installed with Airflow (is that what you mean by core provider?).

**Comment by potiuk** [comment]
I think it would make sense to move DBAPI there too and all related functions. There is no particular reasons why DBApi should be part of the "core". We could deprecate it and move it all to provider, I think.

**Comment by potiuk** [comment]
> As for the provider name i just wondered if it should be provider sql or provider core with sql as extra. Just for the case where we might want to extract other core operators/hooks/sensors into provider(?)

Interesting idea, however extras are "evil". I'd say `apache-airflow-providers-core-sql` is better approach.

This will allow independent release of similar features -  we avoid the fate of "google" provider this way, where things that are "loosely" related (i.e. by google) will be actually coupled when it comes to releasing them. I can easily imagine if we have (for example) `core-storage' and `core-sql` that we would like to release only "core-sql` with a new feature, without touching 'core-storage`..

**Comment by eladkal** [comment]
yes exactly like we have now for example with Microsoft.
The provider is Microsoft but azure and mssql are totally separated.
