### ISSUE TITLE
Airflow pinning old version of attrs: apache-airflow (>=2.3.2,<3.0.0) requires attrs (>=20.0,<21.0)

### ISSUE THREAD

**Issue by arminnajafi** [apache/airflow#24421]
### Apache Airflow version

2.3.2 (latest released)

### What happened

Hello Airflow is pinning old version of attrs and this is leading to version conflict on our side to use Airflow.

```
And because every version of aws-cdk-lib requires attrs (>=21.2,<22.0) or jsii (>=1.58.0,<2.0.0) (4), every version of aws-cdk-lib requires attrs (>=21.2,<22.0)
      Because no versions of apache-airflow match >2.3.2,<3.0.0
   and apache-airflow (2.3.2) depends on attrs (>=20.0,<21.0), apache-airflow (>=2.3.2,<3.0.0) requires attrs (>=20.0,<21.0).
      Thus, apache-airflow (>=2.3.2,<3.0.0) is incompatible with aws-cdk-lib.
```

### What you think should happen instead

Please upgrade attrs to >=21

### Operating System

macOS Monterey - 12.3.1

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to PR it.  - just remove the lmit frmo setup.cfg and solve any problems it might generate..

**Comment by potiuk** [comment]
Assigned it to you

**Comment by arminnajafi** [comment]
@potiuk 
Thanks.

Any guidelines/pointers on how to get my environment set up and make sure tests pass after my changes?

I assume I just need to follow https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst ?

**Comment by potiuk** [comment]
Yes/ Follow those.. CI will run all the tests as well when you push a change to setup.cfg.  Updating requirements is a little more involved (You need to build image with `--upgrade-to-newer-dependencies` flag if you change dependencies and want to re-run test locally using `breeze`. This is the only difference vs. standard contribution guildelines.

**Comment by potiuk** [comment]
There might be also other dependencies holding it back, so you need to check which versions you get when you build the image

**Comment by uranusjr** [comment]
Also note that the `setup.cfg` contains some reasoning:

```
    # We limit the version of attrs to work with the old version of cattrs
    attrs>=20.0,<21.0
    # Cattrs upgrades were known to break lineage https://github.com/apache/airflow/issues/16172
    # TODO: Cattrs is now at 3.8 version so we should attempt to upgrade cattrs soon.
    cattrs~=1.1, !=1.7.*
```

You can use `git blame` to find the corresponding issues that added these comments. They provide context for you to evaluate whether upgrades are viable, and how they can be done.

**Comment by potiuk** [comment]
Any news @arminnajafi ?

**Comment by tomsej** [comment]
Think this can be closed. See https://github.com/apache/airflow/pull/25689
