### ISSUE TITLE
Improved Airflow Dag homepage

### ISSUE THREAD

**Issue by lihan** [apache/airflow#24439]
### Description

Display more useful information about the Airflow on the airflow home page, instead of the dag listing view.

![image](https://user-images.githubusercontent.com/655051/173561113-0639def3-d666-4a91-a24a-20dbc8de082c.png)

### Use case/motivation

Refer to above screenshot.

It's pretty useful to highlight the
* recent dag failures
* Recently succeeded runs
* Currently running dags
* Upcoming dag runs

Optionally to display other metadata like total number of task runs in the last 24 hours etc..

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
would be nice to have something similar, I agree.

**Comment by NilsJPWerner** [comment]
Relevant #19942

**Comment by uranusjr** [comment]
I’m going to just merge this into #19942.
