### ISSUE TITLE
Airflow Docker Compose YAML File Version Inccorect

### ISSUE THREAD

**Issue by vincentkoc** [apache/airflow#24442]
### What do you see as an issue?

Currently the docker-compose.yaml is giving the following error from the following command:

```
❯ docker-compose up airflow-init

ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.airflow-cli.image contains an invalid type, it should be a string
services.airflow-init.image contains an invalid type, it should be a string
services.airflow-scheduler.image contains an invalid type, it should be a string
services.airflow-triggerer.image contains an invalid type, it should be a string
services.airflow-webserver.image contains an invalid type, it should be a string
services.airflow-worker.image contains an invalid type, it should be a string
services.flower.image contains an invalid type, it should be a string
(base) 
```

### Solving the problem

We should update the version of the docker compose from 3 to 3.2 to allow for the expressive notations.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by koconder** [comment]
Resolved, was not commenting out properly.
