### ISSUE TITLE
Override dag run generate_run_id

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#24453]
### Description

 #21851 Added the ability to override run_ids in the manual dag conf. It would be useful to specify a default function for a specific dag to override the dag [generate_run_id](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L407) method for scheduled runs, and allow custom run id formats.

### Use case/motivation

An example use case: You are using the dag run id to determine where files should be saved for a certain run on s3 and you want to add more information to the run_id or use integer timestamps and have that map to the dropdown run ids in the airflow ui.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Why not simply specify the run_id when you trigger the dag via API? you can specify run_id there as you wish.
