### ISSUE TITLE
Dag backfill is running infinitely when I renamed task

### ISSUE THREAD

**Issue by yjs03057** [apache/airflow#24515]
### Apache Airflow version

2.0.1

### What happened

When I renamed my task and backfill the dag which contains that task, I got a warning message like below.
"WARNING - Failed to get task <task instance info> for dag <dag info>. Marking it as removed."

But that removed tasks still exist in my backfill schedule, and that status is waiting not removed.
When I check the airflow code, task's state update to removed after target task instance for backfill already made. 

Is this version issue? Is this issue solved at latest version?

### What you think should happen instead

- airflow/jobs/backfill_job.py
- airflow/jobs/dagrun.py

(backfill_job.py call update_state() function after task_instance_for_dag_run() but I think it should call once more before task_instance_for_dag_run() )

### Operating System

Ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is expected. 

From: https://airflow.apache.org/docs/apache-airflow/stable/index.html

> Workflows are expected to be mostly static or slowly changing. You can think of the structure of the tasks in your workflow as slightly more dynamic than a database structure would be. Airflow workflows are expected to look similar from a run to the next, this allows for clarity around unit of work and continuity.

Until DAG versioning is implemented https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning there is no guarantees thad things will work when the tasks change their structure. The recommended approach when you change structure of your DAG is to copy your DAG and change the dag_id for the newly structured dag.
