### ISSUE TITLE
Airfflow "Code View" not displaying the actual DAG code

### ISSUE THREAD

**Issue by sarthakhaikerwalsaxena** [apache/airflow#24517]
### Apache Airflow version

2.3.2 (latest released)

### What happened

We use DAG bags to parse DAGs across different custom directories. The Code View in the DAG rather than showing the actual DAG code, is displaying the code which is used to parse DAGs. 

![image](https://user-images.githubusercontent.com/11522831/174260493-48b9832f-7e5e-4503-b820-94822b1b8d9e.png)

### What you think should happen instead

It should display the actual DAG code. Note that its working fine in 2.1.2. Once we upgraded to 2.3.2 we are seeing this issue. 

### How to reproduce

You can replicate this issue by using DAG bags. 

### Operating System

RHEL 7.9

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I don't think using DagBag like this has been ever supported. Maybe it worked by accident in the past (though I am not sure how)  but I do not thik it's even been "supported". IMHO DagBag is really an internal mechanism of Airflow, It can change it's behaviour at any time and the pattern you present is nowhere to be found in our documentation (just checked). 

I suggest you change to the "standard" method of dag storage - i.e. make sure that your DAGs are all available in the dags folder.

I will convert it into a discussion, and would love to hear what others think (@ashb @kaxil @dstandish ?) but I believe we are not going to do anything to change the behaviour ans support the way you invented.
