### ISSUE TITLE
`AirbyteHook` add cancel job option

### ISSUE THREAD

**Issue by sivankumar86** [apache/airflow#24574]
### Apache Airflow Provider(s)

airbyte

### Versions of Apache Airflow Providers

I want to cancel the job if it running more than specific time . Task is getting timeout however, airbyte job was not cancelled. it seems, on kill feature has not implemented 

Workaround:
  Create a custom operator and implement cancel hook and call it in on kill function. 

   def on_kill(self):
        if (self.job_id):
            self.log.error('on_kill: stopping airbyte Job %s',self.job_id)
            self.hook.cancel_job(self.job_id)

### Apache Airflow version

2.0.2

### Operating System

Linux

### Deployment

MWAA

### Deployment details

Airflow 2.0.2

### What happened

airbyte job was not cancelled upon timeout 

### What you think should happen instead

it should cancel the job

### How to reproduce

Make sure job runs more than timeout

sync_source_destination = AirbyteTriggerSyncOperator(
                    task_id=f'airbyte_{key}',
                    airbyte_conn_id='airbyte_con',
                    connection_id=key,
                    asynchronous=False,
                    execution_timeout=timedelta(minutes=2)
            )

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it! assigned you!

**Comment by sivankumar86** [comment]
Could you please review the change ? 

https://github.com/apache/airflow/pull/24593
