### ISSUE TITLE
AWS Apache Airflow - Error! Please contact server admin.

### ISSUE THREAD

**Issue by SumitJaiswal997** [apache/airflow#24598]
### Apache Airflow version

2.0.2

### What happened

We get the below message once we click on AWS MWAA - Apache Airflow. Instance gets build successfully. 

Oops
Something bad has happened.
Please consider letting us know by creating a [bug report using GitHub](https://github.com/apache/airflow/issues/new/choose).

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.

### Operating System

AWS

### Versions of Apache Airflow Providers

2.0.2

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please do not use Airflow issues for MWAA problems. Please contact MWAA - They are your server admin. Issues in Airflow are not for help-desk of MWAA problems and there is 0 information here that we could act on.
