### ISSUE TITLE
Using .sh for BashOperator

### ISSUE THREAD

**Issue by debuggingfuture** [apache/airflow#246]
Background: I have a simple script in the worker to be run, something like `/usr/src/app/script.sh`

In [here](https://github.com/airbnb/airflow/blob/073e5d8ca146c45140878ada80bc4e8377332046/airflow/operators/bash_operator.py#L12) It's stated that BashOperator can be used for running script. 

while as in tutorial / the actual logic, it is always treated as template file path, being lookup & `TemplateNotFound` error from jinja will be resulted.  

so - is it supposed to run bash script in the target container or it's always required to use a template as wrapper?    

Not sure if it is consistent to turn on the template feature for files only if a separated argument `bash_template_file`  is used?

e.g. 

```
t1 = BashOperator(
    task_id='script1',
    bash_template_file='/usr/src/app/script.sh',
    dag=dag)
```

**Comment by mistercrunch** [comment]
I agree, though I can't break compatibility at this point. I agree that we should clarify the BashOperator parameters, other people have been confused using it.

One path of solution is to add that folder to your template_searchpath as you construct your DAG.
https://github.com/airbnb/airflow/blob/master/airflow/models.py#L1530

```
dag = DAG(dag_id='mydag', template_searchpath="/usr/src/app/")

t1 = BashOperator(
    task_id='script1',
    bash_template_file='script.sh',
    dag=dag)
```

**Comment by seibert** [comment]
The workaround I currently use is to add a trailing space at the end of the `bash_command` argument.

**Comment by mistercrunch** [comment]
@seibert , yeah we do that here too, semicolon also works, it throws the "file detection" off.

```
t1 = BashOperator(
    task_id='script1',
    bash_template_file='bash /usr/src/app/script.sh;',
    dag=dag)
```

**Comment by mistercrunch** [comment]
I'd change that in a heartbeat if it wasn't for breaking backwards compatibility...

**Comment by mistercrunch** [comment]
Closing, feel free to reopen if you have follow up questions
