### ISSUE TITLE
LocalExecutor run Async operators without a triggerer process

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#24602]
### Description

Currently the LocalExecutor can't run Async operators, it need a triggerer process 

### Use case/motivation

LocalExecutor "should" be a fully airflow working process without needing another process to run tasks

It would keep airflow simple for entry users and small deployments ( and even big deployments if using only async operators).

----

The simplest prod deployment with async support is currently this -> 

![localexectur (1)](https://user-images.githubusercontent.com/10202690/175033423-cf060f66-c459-4b1a-8c75-6950c28a65e3.jpg)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
What do you think about `airflow standalone`command? Is it meer your requirements?

**Comment by raphaelauv** [comment]
`airflow standalone` is more for starting a local airflow , nothing close to a production setup.

`LocalExecutor` is perfectly prod ready and enough for anyone only running operators triggering operations in external solutions and not having needs for elastic scaling ( because not big amount of tasks )

**Comment by potiuk** [comment]
I think it's wrong. We should instead make standalone a fully-production ready solution. Merging Triggerer into Scheduler is a bad idea.
