### ISSUE TITLE
Macro prev_execution_date is always empty

### ISSUE THREAD

**Issue by TamGB** [apache/airflow#24678]
### Apache Airflow version

2.3.2 (latest released)

### What happened

The variable `prev_execution_date` is empty on the first run meaning, all usage will automatically trigger a None error.

### What you think should happen instead

A default date should be provided instead, either the DAG's `start_date` or a default `datetime.min` as during the first run, it will always trigger an error effectively preventing the DAG from running and hence, always returning an error.

### How to reproduce

Pass the variables/macros to any Task:
```
{
    "execution_datetime": '{{ ts_nodash }}',
    "prev_execution_datetime": '{{ prev_start_date_success | ts_nodash }}'  #.strftime("%Y%m%dT%H%M%S")
}
```

Whilst the logical execution date (`execution_datetime`) works, the previous succesful logical execution date `prev_execution_datetime` automatically blows up when applying the `ts_nodash` filter. This effectively makes it impossible to use said macro ever, as it will always fail.

### Operating System

Ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by TamGB** [comment]
Overcame the problem using Jinja:
`{{ prev_start_date_success | ts_nodash if prev_start_date_success is not none else '19800101T000000' }}`

**Comment by potiuk** [comment]
You can also use the `default` built-in Ninja filter. This is much better than imposing some behaviour of the macro.

**Comment by uranusjr** [comment]
Perhaps we should let `ts_nodash` et. al accept None (and just return None). It’ll make the template a bit easier to write.

**Comment by potiuk** [comment]
Good idea @uranusjr :)

**Comment by NaveenGokavarapu19** [comment]
Hii all,

I am interested in this issue. Can i contribute to this issue.

**Comment by uranusjr** [comment]
Go ahead! The filters are in `airflow/templates.py`. I think we should add support for None in all of them.

**Comment by NaveenGokavarapu19** [comment]
is there way to assign it to me.
