### ISSUE TITLE
Error  for   Hive Server2 Connection Document

### ISSUE THREAD

**Issue by tianrobin** [apache/airflow#24692]
### What do you see as an issue?

In  this Document https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/connections/hiveserver2.html  Describe , In Extra  must use the "auth_mechanism " but in the sources Code used "authMechanism".

### Solving the problem

use same words.

### Anything else

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
@tianrobin - why don't you fix it in a PR ?
