### ISSUE TITLE
Clear one single mapped task instance

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#24699]
### Body

We can handle this programmatically, but currently there’s no user interface available for this. The “Clear” button in the task modal applies to all the mapped tasks no matter which map index is chosen (which also is a UX issue), while the `clearTaskInstances` API only takes a list of task IDs.

Currently `DAG.clear()` supports passing in a 2-tuple instead of string to clear one single mapped task (e.g. `task_ids=[("my_task", 1)]`). But I’m not sure how to expose this in the REST API—something like `{"task_ids": [["my_task", 1], "another_task"]}` is difficult to spec in Open API.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by bbovenzi** [comment]
I think that was the source of some confusion over at https://github.com/apache/airflow/pull/23516

**Comment by pierrejeambrun** [comment]
Hello @bbovenzi and @uranusjr,

I feel like this is addressed as of today, both via the grid view and task modal actions.

Closing for now, feel free to reopen if needed

**Comment by manugarri** [comment]
@pierrejeambrun maybe im not understanding your answer. On my current dag, we map (with `expand`) 5 tasks to run in parallel, and for what I see there is no place where we can clear the task. 
![image](https://github.com/apache/airflow/assets/3670355/c042e9ec-57bb-4a65-a477-0001d15d3ddc)

You can see there are no tasks to select.
![image](https://github.com/apache/airflow/assets/3670355/d04e4817-e137-4cea-b709-7ffcdedb751d)

**Comment by bbovenzi** [comment]
This isn't the normal behavior so you'll need to help us debug.

Do you see any errors in your browser's network tab or is the response just an empty array?
Can you clear any non mapped tasks in this dag normally?
Once the dag finished running is everything performing as expected?

**Comment by jayceslesar** [comment]
@manugarri I noticed that the map index data is empty when there are certain special characters in the run id of the DAG -- for instance with forward slashes in the run id, nothing appears in the mapped task instances, but if I replace all forward slashes with underscores for example, this data shows up in the UI fine
