### ISSUE TITLE
Password autocompletion set off on login page

### ISSUE THREAD

**Issue by abhishekbhakat** [apache/airflow#24700]
### Description

The form on the login page for Airflow has not set `autocomplete="off"` either for the form or the password input field.
Modern browsers ignore that and offer autocompletion anyway, which some will when it detects it is a login form.

### Use case/motivation

Even though browsers are free to ignore this option. There are a few Airflow users reporting this as a vulnerability caught in their scanner. Therefore it should be a "good to have".

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhishekbhakat** [comment]
Can we try adding a parameter to [Login.tsx](https://github.com/apache/airflow/blob/main/airflow/ui/src/views/Login.tsx) as:

```
          <FormControl mt={4}>
            <FormLabel htmlFor="password">Password</FormLabel>
            <InputGroup>
              <InputLeftElement>
                <Icon as={FiLock} color="gray.300" />
              </InputLeftElement>
              <Input
                type="password"
                name="password"
                placeholder="Password"
                data-testid="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                isRequired
              />
            </InputGroup>
          </FormControl>
```

Guess the parameter should be `autoComplete = 'off'`?

**Comment by bbovenzi** [comment]
I wouldn't worry about `Login.tsx` for now. The UI in `airflow/ui` is an experimental full UI for AIP-38. The main frontend is in `airflow/www`.

**Comment by Tingweiftw** [comment]
Is there any further action on this? We used airflow and similar issue was caught in our vulnerabilility assessement.

**Comment by uranusjr** [comment]
Submitting a pull request is always the fastest way to get this fixed!

**Comment by potiuk** [comment]
> Is there any further action on this? We used airflow and similar issue was caught in our vulnerabilility assessement.
> Submitting a pull request is always the fastest way to get this fixed!

Also it is the good thing to do to pay back for the free software you use @Tingweiftw. I think if your company is bothered by something in Free, Open Source Software I think it is only reasonable to expect they sponsor a little time of their engineer to contribute such a fix back. This would be awesome if your commpany fulfills the moral obligations there (rather than expect things to happen).

**Comment by potiuk** [comment]
This is not valid according to Brent's comment, so we can close this one.
