### ISSUE TITLE
Trigger DAG from templated view tab producing bad request

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#24725]
### Body

Reproduced on main branch.

The bug:
When clicking Trigger DAG from templated view tab it resulted in a BAD REQUEST page however DAG run is created (it also produce the UI alert "it should start any moment now")
To compare trying to trigger DAG from log tab works as expected so the issue seems to be relevant only to to the specific tab.

![trigger dag](https://user-images.githubusercontent.com/45845474/176372793-02ca6760-57f7-4a89-b85e-68411561009f.gif)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
cc @bbovenzi

**Comment by bbovenzi** [comment]
Ok, I see. The trigger request goes through but the redirect back to the page loses its query params and is then a bad request. The same issue happens in grid view, all url params are cleared after triggering a new run. Working on a fix...
