### ISSUE TITLE
`default_wrap` setting for webserver is not working

### ISSUE THREAD

**Issue by ming-zhang-SN** [apache/airflow#24721]
### Apache Airflow version

2.3.2 (latest released)

### What happened

The DAG logs are not wrapped even I set `default_wrap` in `airflow.cfg` to `True`.
That may cause by this line I think:
https://github.com/apache/airflow/blob/main/airflow/www/static/js/dag_code.js#L25

I tried with the following code and worked:
```
$('pre > code').toggleClass('wrap');
```

### Operating System

Ubuntu 19.10

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@pierrejeambrun We may want to make sure this config is passed to the new grid view logs too.

**Comment by pierrejeambrun** [comment]
Yes good idea. I'll open a PR for that :)

**Comment by bbovenzi** [comment]
@ming-zhang-SN do you still want to open a PR to fix this?

**Comment by pierrejeambrun** [comment]
@ming-zhang-SN We made the update for the grid view, do you want to open a PR for the log page ?

**Comment by bbovenzi** [comment]
If anyone else wants to pick up this issue. You will want to add a meta tag for `wrapped` to the [ti_log html file](https://github.com/apache/airflow/blob/main/airflow/www/templates/airflow/ti_log.html). Then to use `getMetaValue()` to get that value in the js file and add the `wrap` class to the code block [here](https://github.com/apache/airflow/blob/main/airflow/www/static/js/ti_log.js#L123).
