### ISSUE TITLE
API endpoint for uploading files to DAG_FOLDER

### ISSUE THREAD

**Issue by CarlosDomingues** [apache/airflow#24740]
### Description

Since Airflow now has stable a [REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html), it would be great if we had an endpoint to upload files to DAG_FOLDER.

### Use case/motivation

DAGs are loaded from files and directories stored in `DAG_FOLDER`, which is a filesystem path that must be shared among several Airflow components.

I've explored a few options to populate and update `DAG_FOLDER`over the years:

1. Use `git sync` + Cron to pool DAGs from Git repos. That does not scale operationally and requires Airflow servers to access repos where source lives, which is bad for security.

2. Use a middleman like AWS S3 and upload DAGs to it during a CD pipeline. Then, Airflow can periodically pull from that. IMO that's better than (1), but still not ideal.

3. Use a shared mount (like AWS EFS or K8s volumes) between Airflow and CD servers, so DAGs can be copied to `DAG_FOLDER`. That's cool, but it means tigher coupling between Airflow and CD infrastructure.

I think it would be operationally  great if I could upload DAGs using a simple `curl` command. That would make interaction between Airflow and CI/CD pipelines much more flexible, as well as enabling finer graned security.

### Related issues

After searching for older issues, I found #24537. Note, however, that I'm proposing something way simpler - just uploading files.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
> Use git sync + Cron to pool DAGs from Git repos. That does not scale operationally and requires Airflow servers to access repos where source lives, which is bad for security. That does not scale operationally and requires Airflow servers to access repos where source lives, which is bad for security

Why is it bad for security?
And if so, how using API to deploy code directly into Airflow DAG folder improve the security?

**Comment by CarlosDomingues** [comment]
Hi! Thank you so much for your quick response. Here are my thoughts:

> Why is it bad for security?

1. It's yet another point of failure, another credential at risk. I'd rather restrict source access to my CI servers, which need such privilege anyway.

2. There's no easy way of giving fine-grained access to the contents of a Git repo. Hence, using `git sync` means giving Airflow acess to entire repos. That's specially worrisome for folks using monorepos.

> And if so, how using API to deploy code directly into Airflow DAG folder improve the security?

1. It would prevent another component of my infrastructure needing access to source.

2. It would make DAG deployment friendler to CI/CD scenarios, which in many organizations are at greater security scrutiny.

**Comment by phenriquerangel** [comment]
Following

**Comment by uranusjr** [comment]
If you think GitSync is insecure, I’d say allowing uploading file via the REST API is even more so. A DAG file is run as plain Python code in the interpreter, and it’s against code injection prevention 101 to expose it via any web API.
