### ISSUE TITLE
FacebookAdsReportToGcsOperator CSV conversion option available

### ISSUE THREAD

**Issue by mz-heesun** [apache/airflow#24758]
### Apache Airflow Provider(s)

facebook

### Versions of Apache Airflow Providers

3.0.0

### Apache Airflow version

2.2.5

### Operating System

mac os

### Deployment

Docker-Compose

### Deployment details

In airflow 2.2.5, docker-compose up environment was established using facebook provider in docker.

### What happened

A problem arose under certain circumstances. There was no cpc field.

An error occurred when converting to csv in that situation. It was an error that the field could not be found.

Below is the error message.

`[2022-06-30, 10:38:39 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/facebook_ads_to_gcs.py", line 165, in execute
    total_row_count = self._decide_and_flush(converted_rows_with_action=converted_rows_with_action)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/facebook_ads_to_gcs.py", line 197, in _decide_and_flush
    self._flush_rows(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/facebook_ads_to_gcs.py", line 227, in _flush_rows
    writer.writerows(converted_rows)
  File "/opt/python3.8/lib/python3.8/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/opt/python3.8/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'cpc'`

### What you think should happen instead

I think you should specify an option so that missing fields can be ignored.

Depending on the user, you may want to proceed without the field.

### How to reproduce

If airflow is installed, you can try running the dag.

Instead, it seems that only people who have set up Facebook ads can do this.

### Anything else

Actually, in terms of code, it seems like it would be enough to provide only a way to control the option to ignore in the csv file conversion part.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
feel free to submit PR

**Comment by eladkal** [comment]
The list of fields is controlled by:
https://github.com/apache/airflow/blob/fd116cc1964c49e21aaac6062fff596764833c59/airflow/providers/google/cloud/transfers/facebook_ads_to_gcs.py#L68

Isn't excluding `cpc` from this list a solution to your issue?
