### ISSUE TITLE
Make task_instance priority_weight dag_run/execution_date dependent

### ISSUE THREAD

**Issue by aaronmielke** [apache/airflow#24788]
### Description

We want to weight a task's priority based on execution date. In general it would be nice to have the option to make the priority weight of a task instance dynamic based on the dag_run (from which execution_date and possibly other parameters can be derived)

### Use case/motivation

We have a pool to run a set of tasks. Sometime we rerun a lot of old dag instances. This queues a LOT of task instances. Those dag rerun task instances end up delaying "today's" dag_instance tasks. If we weight today's dag_instance tasks with a higher priority weight this wouldn't happen.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This would be a major change in the architectuer of scheduler and executor. I think it is not enough to make it a feature. If someone would like to implement such prioritisation that would require major re-architecting of how schedulers and executors work. That requires AIP https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals and extended discussion on devlist. converting this into discussion.
