### ISSUE TITLE
Dag disappears when DAG tag is longer than 100 char limit

### ISSUE THREAD

**Issue by LarsAlmgren** [apache/airflow#24820]
### Apache Airflow version

2.2.5

### What happened

We added new DAG tags to a couple of our DAGs. In the case when the tag was longer than the 100 character limit the DAG was not showing in the UI and wasn't scheduled. It was however possible to reach it by typing in the URL to the DAG.
Usually when DAGs are broken there will be an error message in the UI, but this problem did not render any error message.

This problem occurred to one of our templated DAGs. Only one DAG broke and it was the one with a DAG tag which was too long. When we fixed the length, the DAG was scheduled and was visible in the UI again.

### What you think should happen instead

Exclude the dag if it is over the 100 character limit or show an error message in the UI.

### How to reproduce

Add a DAG tag which is longer than 100 characters.

### Operating System

Ubuntu

### Deployment

Other 3rd-party Helm chart

### Deployment details

Running Airflow in Kubernetes.
Syncing DAGs from S3 with https://tech.scribd.com/blog/2020/breaking-up-the-dag-repo.html

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Interesting :)

**Comment by TommyDew42** [comment]
Hi! I'll pick up this good-first-issue!

**Comment by TommyDew42** [comment]
@potiuk
I think we'll just add a length check to [tags](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L345).
If we have a tag with length >= 100, we raise an exception.

But I'm not sure how we pip install the dependencies. I [read](https://github.com/apache/airflow/blob/main/LOCAL_VIRTUALENV.rst#creating-a-local-virtualenv) that only `pip` installation is officially supported.

I wonder if [dev/requirements.txt](https://github.com/apache/airflow/blob/main/dev/requirements.txt) & [docker_test/requirements.txt](https://github.com/apache/airflow/blob/main/docker_tests/requirements.txt) are all the requirements.txt that can get us to run unit tests? Thanks a lot!

**Comment by potiuk** [comment]
@TommyDew42 -> https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst has all the instruction on starting contribution and links to how to setup development environments
