### ISSUE TITLE
Default start_date and schedule_interval to None

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#24842]
### Description

I suggest changing the bare-minimum code required for instantiating a DAG:

```python
# Proposed

from airflow import DAG
from airflow.operators.bash import BashOperator

with DAG(dag_id="no_schedule_dag") as dag:
    BashOperator(task_id="foobar", bash_command="echo hello")
```

This is currently not possible because `start_date` is a required argument:
![image](https://user-images.githubusercontent.com/6249654/177302561-6b7a363d-df95-4363-9725-32898a50c326.png)

I regularly see people using externally triggered DAGs and you're currently forced to set a placeholder `start_date` because Airflow requires it:

```python
# Current situation

import datetime

from airflow import DAG
from airflow.operators.bash import BashOperator

with DAG(dag_id="no_schedule_dag", start_date=datetime.datetime(2022, 1, 1), schedule_interval=None) as dag:
    BashOperator(task_id="foobar", bash_command="echo hello")
```

When people want to set a `schedule_interval`, they intentionally think of it, so defaulting to `None` feels like a better UX to me.

### Use case/motivation

To improve the Airflow user experience, I suggest removing the `start_date` requirement on `DAG`:

```python
DAG(dag_id="my_dag")
```

This DAG could be triggered externally.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
The "default" schedule_interval is currently daily. I'm all for this so long as we can do it without breaking back-compat.

**Comment by BasPH** [comment]
Yea that won't be possible. The default daily schedule interval has been there [since the very first commit](https://github.com/apache/airflow/blob/1047940ca4363b04044c4963b9c88f7632746407/core/models.py#L710), and always felt like undocumented magic to me, and goes against Python's "explicit is better than implicit".

**Comment by ashb** [comment]
Then it's unlikely we can do it before 3.0

**Comment by ashb** [comment]
I think we might be able to do this by changing the function default to `NOT_SET` (a special singleton object) and then changing the value at runtime after checking other parameters.

**Comment by malthe** [comment]
See also discussion here https://lists.apache.org/thread/hyctljm0o1odn1bntp4fcgok0d0433ov.

**Comment by eladkal** [comment]
> See also discussion here https://lists.apache.org/thread/hyctljm0o1odn1bntp4fcgok0d0433ov.

As of Airflow 2.8 `start_date` is not required when `schedule=None`
https://github.com/apache/airflow/issues/35199

I think this solves this issue to the best we can do without causing breaking changes.

**Comment by uranusjr** [comment]
With #41321 we should be set to do this.
