### ISSUE TITLE
grid_data api keep refreshing  when backfill DAG runs

### ISSUE THREAD

**Issue by yingxuanwangxuan** [apache/airflow#24844]
### Apache Airflow version

2.3.2 (latest released)

### What happened

![image](https://user-images.githubusercontent.com/95274553/177323814-fa75af14-6018-4f9d-9468-4e681b572dcc.png)

### Operating System

186-Ubuntu 

### Versions of Apache Airflow Providers

2.3.2

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
You can manually click the auto-refresh toggle off to prevent this. Otherwise, those backfilled runs are "pending" and will refresh.

**Comment by yingxuanwangxuan** [comment]
> You can manually click the auto-refresh toggle off to prevent this. Otherwise, those backfilled runs are "pending" and will refresh.
I think this is a problem, can I fix it.

**Comment by yingxuanwangxuan** [comment]
> 



> @yingxuanwangxuan can you add more info
> 
> 1. When do you see this error?
> 2. What should happen instead?
> 3. How can we reproduce this?
> 
> Currently, it looks like the grid view is updating because Auto-refresh is enabled

step1 I schedule DAG（airflow_log_cleanup).
step2 I backfill it.
dags  backfill airflow_log_cleanup  -s 2022-06-11 -e 2022-06-20  --donot-pickle
step3  
![image](https://user-images.githubusercontent.com/95274553/177456957-5754d16d-d43a-48c1-b52c-5661dd9212b7.png)

I wish it didn't refresh automatically all the time.

**Comment by bbovenzi** [comment]
What solution do you want other than the already existing ability to manually turn off auto-refresh?

**Comment by yingxuanwangxuan** [comment]
> What solution do you want other than the already existing ability to manually turn off auto-refresh?

in [airflow/www/static/js/grid/api/useGridData.ts] by filter manual and  scheduled 
![image](https://user-images.githubusercontent.com/95274553/177463065-adf62be1-c9c1-41f5-873e-940599cad402.png)

**Comment by yingxuanwangxuan** [comment]
> What solution do you want other than the already existing ability to manually turn off auto-refresh?

I'm not sure this is a good solution, can I submit a pr to fix it?

**Comment by cloventt** [comment]
I'm not sure I understand the reason for this change. Why would you not want the page to auto-refresh? Auto-refresh is useful for seeing the state of running tasks, regardless of whether that task was triggered via a backfill, schedule or manually.

**Comment by yingxuanwangxuan** [comment]
> I'm not sure I understand the reason for this change. Why would you not want the page to auto-refresh? Auto-refresh is useful for seeing the state of running tasks, regardless of whether that task was triggered via a backfill, schedule or manually.

I am using AirFlow1.10. When I tried to upgrade to a higher version. I found this feature auto-refresh is useful for seeing the state of running tasks. When I backfill my task, the state of these tasks is pending which keeps refreshing. 

The airflow Grid page maintains backfilled task state by automatically refreshing whether this is the most appropriate way？ Because the backfill command does not re-run completed DAGs within the given period unless we explicitly instruct it to do.

**Comment by Gollum999** [comment]
I'm a bit confused by this thread.  I have been doing a lot of backfilling recently and I personally find the auto-refresh behavior to be quite useful for monitoring progress.  It's still not entirely clear to me what the bug is, but disabling auto-refresh for *all* backfills seems a bit heavy-handed to me.

**Comment by potiuk** [comment]
I would kindly suggest any of the people who are commenting here, on a closed task to submit a PR fixing it. I think there are a number of ways this can be handled - so if any of you has an idea, constructive PR proposing a fix (especially that there is a linked PR that disabled it that can be used as starting point) is much better approach than commenting on a closed issue.

I heartily invite any of you @cloventt @Gollum999  @yingxuanwangxuan to attempt to do it.

**Comment by Gollum999** [comment]
@potiuk Well, if it were up to me I would just revert the original PR, but that doesn't seem especially productive. :smile: 

I was hoping to get some more details from @yingxuanwangxuan (or perhaps @bbovenzi) to better understand the reason behind this change.

Would it help to re-open this thread?  Or start a new one?

**Comment by bbovenzi** [comment]
Looking at this again, maybe we should revert this change. It is possible to turn off auto-refresh when a user doesn't want it. Therefore, the previously functionality is the most flexible for all users. @Gollum999 I'd welcome a PR to change it.

**Comment by yingxuanwangxuan** [comment]
I am using AirFlow1.10. When I tried to upgrade to a higher version. I found this feature auto-refresh is useful for seeing the state of running tasks. When I backfill my task, the state of these tasks is pending which keeps refreshing.

The airflow Grid page maintains backfilled task state by automatically refreshing whether this is the most appropriate way？ Because the backfill command does not re-run completed DAGs within the given period unless we explicitly instruct it to do.



| |
hefeixuanzi
|
|
***@***.***
|
On 8/25/2022 11:50，David ***@***.***> wrote：

I'm not sure I understand the reason for this change. Why would you not want the page to auto-refresh? Auto-refresh is useful for seeing the state of running tasks, regardless of whether that task was triggered via a backfill, schedule or manually.
