### ISSUE TITLE
Example for callbacks on DAG and task level

### ISSUE THREAD

**Issue by p13rr0m** [apache/airflow#24868]
### What do you see as an issue?

Hi everyone,

is this callback [example](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/callbacks.html#example
) from the documentation correct or just confusing? 

It mentions: "In the following example, failures in any task call the task_failure_alert function, and success in the last task calls the dag_success_alert function:"

The task_failure_alert is set on a DAG level, while the dag_success_alert on an task level. Based on the name of the functions, shouldn't it be the other way round?

 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Nope. The example is correct. Read it carefully please. Callbacks are always set on "tasks" - even if you set them at DAG level, they always propagate to the tasks. The reason "success" is "on dag success" is only becase it is called on success of the last task in DAG, but this is still a task callback not dag callback. The example is good.
