### ISSUE TITLE
Wrong syntax in mssql setup documentation

### ISSUE THREAD

**Issue by Frank-T-Johansen** [apache/airflow#24893]
### What do you see as an issue?

https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html#setting-up-a-mssql-database

Documentation says:
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow_user;

For MSSQL 2019 patchlevel 15.0.4236.7 the correct syntax is:
GRANT ALL PRIVILEGES ON DATABASE::airflow TO airflow_user;

Only the latter works, although I still get a warning that it is deprecated.

### Solving the problem

Updating documentation with new alternative, maybe depending on mssql version.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nigel-millward** [comment]
Hi! I'm a newbie, I'll pick up this good-first-issue!

**Comment by uranusjr** [comment]
Go ahead!

**Comment by nigel-millward** [comment]
All links below point to using new syntax
SQL patch: https://support.microsoft.com/en-us/topic/kb4518398-sql-server-2019-build-versions-782ed548-1cd8-b5c3-a566-8b4f9e20293a
2022 preview: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-database-permissions-transact-sql?view=sql-server-ver16
2019: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-database-permissions-transact-sql?view=sql-server-ver15
2017: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-database-permissions-transact-sql?view=sql-server-2017
 
 
 
Airflow supports the following database engine versions
PostgreSQL: 10, 11, 12, 13
MySQL: 5.7, 8
MsSQL: 2017, 2019
SQLite: 3.15.0+
 
Tested on mssql 2017 and 2019, both worked fine with the new syntax
Updated docs to the later version

Created a PR: https://github.com/apache/airflow/pull/24939

**Comment by jedcunningham** [comment]
Fixed in #24939.
