### ISSUE TITLE
Pulled the Latest Code and Webserver Displays SQL-Alchemy Error

### ISSUE THREAD

**Issue by r39132** [apache/airflow#249]
I pulled the latest code, which includes the following fix :  https://github.com/airbnb/airflow/commit/1264bde6d6b8f12f1ff0223d3166c4b296d4a1a3

The previous update was about 2 weeks ago.

I then ran `python setup.py install` and restarted the webserver 

I get the following error : 

``` sqlalchemy.exc.ProgrammingError
ProgrammingError: (psycopg2.ProgrammingError) relation "import_error" does not exist
LINE 2: FROM import_error
             ^
 [SQL: 'SELECT import_error.id AS import_error_id, import_error.timestamp AS import_error_timestamp, import_error.filename AS import_error_filename, import_error.stacktrace AS import_error_stacktrace \nFROM import_error']
```

**Comment by jlowin** [comment]
I'm not sure this will work but while building the `XCom` stuff I learned that running `airflow resetdb` will create new tables (of which `import_error` is one) -- but it might also erase anything you've stored in the db. @mistercrunch is there a non-destructive way to load the new table?

**Comment by r39132** [comment]
Hmn... I'm not familiar with sqlalchemy or flask, but I did `airflow initdb` and it resolved the issue in a non-destructive way or so it appears to me.

**Comment by mistercrunch** [comment]
Careful with `resetdb`, it will drop all airflow tables and recreate them, it's useful on a dev environment while iterating on the models, but beyond that it's just plain dangerous, it does prompt for confirmation though.

`initdb` will create new models in a non destructive way, but it won't migrate anything, it's not a model migration mechanism. @r39132 , this should work for you, but taking a backup is always a safe bet.

I'll provide migration scripts moving forward for releases, in trunk(master) you may have surprises as you did today.

**Comment by mistercrunch** [comment]
The good news is the new feature shows error messages on the main page when some DAGs go offline (anything python file that can't be parse in your DAGS_FOLDER)

**Comment by r39132** [comment]
Got it. BTW, I've been in Colombia on vacation for more than a week, so I'm out of the loop on recent changes. It would be nice to have a migration process for trunk(master) as well. I tend to pull the latest code when I can.
