### ISSUE TITLE
Show a browser notification when a DAG run completes

### ISSUE THREAD

**Issue by Caerbannog** [apache/airflow#24928]
### Description

When the DAG grid view is open and a DAG is running, the auto-refresh already detects when all tasks end.
We could show a web notification when this happens.

Metabase does something similar when a long running process finishes. It also notifies through the favicon and the page title.
https://github.com/metabase/metabase/issues/21247

### Use case/motivation

When you are waiting for a DAG end (debugging the DAG or needing the output), you have to keep the Airflow tab in view to know when the process finishes.
Adding a way to notifiy the user from a background tab would be more convenient.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I don't think we will support this in the near-term. Right now, the auto-refresh will pause when the page is in the background, because we simply GET the same endpoint every 5 seconds or so. We don't yet have a real streaming API that we could subscribe to.

**Comment by Caerbannog** [comment]
Just to be clear : I think that a 5s precision is quite sufficient.

If this notification feature was enabled, it would purely be javascript code.
When the feature is enabled, the auto-refresh wouldn't be paused when the page goes in background. The 5s requests would still fire, and when they indicate that the task finished the notification would be shown (and the requests stopped).

Also, a real streaming API might not be preferrable to the current polling system. For instance we currently deploy Airflow behind a load balancer with a 60s HTTP timeout, and I suspect that few organisations in our situation would bother setting up a websocket-style channel just for below-5s-latency.
