### ISSUE TITLE
Add options to Docker Operator

### ISSUE THREAD

**Issue by cardosofede** [apache/airflow#24921]
### Description

I'm trying to add options like log-opt max-size 5 and I can't. 

### Use case/motivation

I'm working in Hummingbot and I would like to offer the community a system to manage multiple bots, rebalance portfolio, etc. Our system needs a terminal to execute commands so currently I'm not able to use airflow to accomplish this task.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I marked it as good first issue and if someone would like to pick it they might. Hower just so you be aware how open-source work - if no-one will pick it up, it won't be implemented, so the most sure way of getting this feature if you need it, is that you or your company will invest time and effort in implementing it and make contribution - PR implementing what you think should be added.

**Comment by cardosofede** [comment]
Thank you!

**Comment by yingw787** [comment]
I'm brand new to the Airflow contributors community and wanted to submit a pull request, can I take this issue?

**Comment by potiuk** [comment]
Feel free @yingw787 . Assigned you :)

**Comment by yingw787** [comment]
wanted to give an update, no progress yet due to work having a tight deadline, but will see how much I can get done in the next week; I did have trouble getting started when I tried to run `breeze`, not sure whether I should create an issue or if it's something simpler: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1657592430809019

**Comment by yingw787** [comment]
yo...honestly not sure if I have the bandwidth to take this on, pls feel free to reassign

**Comment by nshetty15** [comment]
@potiuk  I can take this up.
