### ISSUE TITLE
Type hints for taskflow @dag decorator

### ISSUE THREAD

**Issue by AndrewTsao** [apache/airflow#24936]
### Description

I find no type hints when write a DAG use TaskFlowApi.  `dag` and `task` decorator is a simple wrapper without detail arguments provide in docstring.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
What environment do you use? Both of them already provide autocomplete for me in VSCode.

**Comment by AndrewTsao** [comment]
Thank you for your reply.

I use VSCode with Python extensions too. python==3.7 apache-airflow==2.3.2.  
I can't get any hint when I'm input `@dag(`. no argument hints.

**Comment by AndrewTsao** [comment]
I find   `__init__.pyi` in `airflow.decorators` module in the main branch, but no `dag` and `task` typing definition in it.

**Comment by potiuk** [comment]
In my Intellij Dag does not work:
![image](https://user-images.githubusercontent.com/595491/178454191-a1b92eae-b932-491e-8e80-5936b64ddcd8.png)


While task works:
![image](https://user-images.githubusercontent.com/595491/178454313-7a6fce65-baca-49b7-9ae7-caa49afbb656.png)

**Comment by uranusjr** [comment]
I edited the title to better reflect the issue.
