### ISSUE TITLE
Error while doing Airflow Integration with Datahub

### ISSUE THREAD

**Issue by Kuladeep1996** [apache/airflow#24956]
### Apache Airflow version

2.3.3 (latest released)

### What happened

We are following this "https://datahubproject.io/docs/lineage/airflow" for airflow integration with datahub but when running step3 command causing error
![image](https://user-images.githubusercontent.com/74226018/178199168-2d0d05a7-73e7-48a0-8686-21cec7f7f28b.png)

### What you think should happen instead

execute(airflow connections add  --conn-type 'datahub_rest' 'datahub_rest_default' --conn-host 'http://localhost:8080') command without any error

### How to reproduce

Follow this https://datahubproject.io/docs/lineage/airflow/
At step 3 you will get this error
![image](https://user-images.githubusercontent.com/74226018/178199344-8364474e-0c10-48a5-8b17-9cf768bb6586.png)

### Operating System

Windows 10

### Versions of Apache Airflow Providers

apache-airflow==2.3.2
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-sqlite==3.0.0

### Deployment

Docker-Compose

### Deployment details

Followed this doc for airflow deployment
https://medium.com/@garc1a0scar/how-to-start-with-apache-airflow-in-docker-windows-902674ad1bbe

and also modified port8080 to 8089 due to conflict with Datahub

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Windows is not supported yet. Please follow #10388
