### ISSUE TITLE
DebugExecutor runs task callbacks twice

### ISSUE THREAD

**Issue by jochenott** [apache/airflow#24957]
### Apache Airflow version

2.3.3 (latest released)

### What happened

The DebugExecutor runs the on_failure_callback twice.

This is due to `TaskInstance._run_finished_callback()` being called twice: once implicitly via the (new) call to `ti.run()`, once explicitly again:

https://github.com/apache/airflow/blob/62778bb8648515e9823ace2f48d9a89ec91a6803/airflow/executors/debug_executor.py#L79,L81

This came in to the airflow 2-3 branch via this commit: https://github.com/apache/airflow/commit/13e4a752a5b8d71609c90016b9abfd1f14a99ece

This is not an issue on the main branch, where the explicit call to `TaskInstance._run_finished_callback()` has been removed from the `DebugExecutor`.

### Operating System

Debian 11

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @o-nikolas related to https://github.com/apache/airflow/pull/24357 ?

**Comment by o-nikolas** [comment]
> related to #24357 ?

@eladkal, related yeah. My change depended on a previous change in main, but the previous change didn't make it into the 2.3 release branch it seems? From what I can tell everything has always been good in main and still seems to be. I'd say we can close this one?

**Comment by SwanseN21** [comment]
> ### Apache Airflow version
> 
> 2.3.3 (latest released)
> 
> ### What happened
> 
> The DebugExecutor runs the on_failure_callback twice.
> 
> 
> 
> This is due to `TaskInstance._run_finished_callback()` being called twice: once implicitly via the (new) call to `ti.run()`, once explicitly again:
> 
> 
> 
> https://github.com/apache/airflow/blob/62778bb8648515e9823ace2f48d9a89ec91a6803/airflow/executors/debug_executor.py#L79,L81
> 
> 
> 
> This came in to the airflow 2-3 branch via this commit: https://github.com/apache/airflow/commit/13e4a752a5b8d71609c90016b9abfd1f14a99ece
> 
> 
> 
> This is not an issue on the main branch, where the explicit call to `TaskInstance._run_finished_callback()` has been removed from the `DebugExecutor`.
> 
> 
> 
> ### What you think should happen instead
> 
> _No response_
> 
> ### How to reproduce
> 
> _No response_
> 
> ### Operating System
> 
> Debian 11
> 
> ### Versions of Apache Airflow Providers
> 
> _No response_
> 
> ### Deployment
> 
> Other
> 
> ### Deployment details
> 
> _No response_
> 
> ### Anything else
> 
> _No response_
> 
> ### Are you willing to submit PR?
> 
> - [ ] Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
>
