### ISSUE TITLE
2nd menu is missing whitespace when there are more than 2 menu items

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#24962]
### What do you see as an issue?

When there are more than 2 menu items, the docs don't show a whitespace between the `/` and the 2nd menu name:

![image](https://user-images.githubusercontent.com/6249654/178264144-d7f9e258-ebaf-4fed-a71c-024da302b8ed.png)
[link](https://airflow.apache.org/docs/apache-airflow/stable/howto/add-dag-tags.html)

However, when opening just the 2nd menu, it displays correct:
![image](https://user-images.githubusercontent.com/6249654/178264484-fae8abb8-3c71-4286-8dbf-86048f2c6e48.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Akshay-samsung** [comment]
Hello 
I have submitted a [Pull Request](https://github.com/apache/airflow-site/pull/708) for this issue in airflow-site repo.

**Comment by uranusjr** [comment]
Closing since the linked PR has been merged.
