### ISSUE TITLE
Doc menu items are not collapsible

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#24963]
### What do you see as an issue?

Some menus contain many sub-menus and it would be convenient to close the menu to avoid having to scroll down:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/6249654/178265155-4db34a46-c37a-461e-8d5a-de32f29d16e6.png">

However, nothing happens when clicking on "Installation".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by anselboero** [comment]
a [PR](https://github.com/apache/airflow-site/pull/641) on [airflow-site](https://github.com/apache/airflow-site) was submitted and approved, but I don't know when the site will be rebuilded. :)

**Comment by potiuk** [comment]
> a [PR](https://github.com/apache/airflow-site/pull/641) on [airflow-site](https://github.com/apache/airflow-site) was submitted and approved, but I don't know when the site will be rebuilded. :)

It was rebuil, I even published the new theme, but something is not working apparently @mik-laj  - do we need to do anything else ?

**Comment by anselboero** [comment]
Ah Ok. Then I probably forgot something. I'm sorry. I will try to learn more about sphinx API.

**Comment by BasPH** [comment]
Again a new release was made 2 days ago: https://github.com/apache/airflow-site/releases/tag/0.0.10 but I don't see the collapsible menu items. Any ideas if somehow it isn't deployed @potiuk @mik-laj?

**Comment by anselboero** [comment]
Hi, 
I've noticed that on the official [website](https://airflow.apache.org/docs/apache-airflow/stable/index.html) there is no reference to the Js **globaltoc.js** script that I've committed from the airflow-site Github repo. 
BUT
I've noticed that the [Documentation from the development version webpage](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/index.html) is updated and it contains the reference to the **globaltoc.js** script

![Screenshot from 2022-08-18 19-44-25](https://user-images.githubusercontent.com/51990800/185461274-397c4468-2d5d-4ef4-be34-cc841a44b537.png)


(The menu is not collapsible anyway as I noticed that a comma is missing in the [setup.py](https://github.com/apache/airflow-site/blob/7ad3b3ff6ccb71f3ab993dd10fc936a42efe1223/sphinx_airflow_theme/setup.py#L56) file, but it will be easy to fix).

**I wonder why the two pages are out of sync**. Is it normal?

Thank you
