### ISSUE TITLE
artifacthub official chart does not have latest airflow app version 

### ISSUE THREAD

**Issue by imkaka** [apache/airflow#24964]
### Official Helm Chart version

1.6.0 (latest released)

### Apache Airflow version

2.3.3 (latest released)

### Kubernetes Version

v1.20.9

### What happened

https://artifacthub.io/packages/helm/apache-airflow/airflow does not have latest App version?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is correct. The airflow default version will be updated with the next release of chart (as usual). We release those independently.
