### ISSUE TITLE
Taskgroups show incorrect status in grid view

### ISSUE THREAD

**Issue by pascal-knapen** [apache/airflow#24998]
### Apache Airflow version

2.3.2

### What happened

Once a task belonging to a TaskGroup is in the status `failed` or `upstream failed`, that status is shown for the TaskGroup over all the runs in grid view. 

### What you think should happen instead

I expect in the grid view to see TaskGroups in the status corresponding to the status of the tasks in that group for the given dag run. 

### How to reproduce

1. Create a DAG using taskgroups
```
from airflow import DAG
from airflow.utils.task_group import TaskGroup
from airflow.operators.empty import EmptyOperator
from datetime import datetime, timedelta


default_args = {
    "depends_on_past": False,
    "start_date": datetime(year=2022, month=7, day=9),
    "email": [],
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    "sample-taskgroup", default_args=default_args, schedule_interval="@daily", max_active_runs=1
) as dag: 

    t0 = EmptyOperator(task_id='start')

    # Start Task Group definition
    with TaskGroup(group_id='group1') as tg1:
        t1 = EmptyOperator(task_id='task1')
        t2 = EmptyOperator(task_id='task2')

        t1 >> t2
    # End Task Group definition
        
    t3 = EmptyOperator(task_id='end')

    # Set Task Group's (tg1) dependencies
    t0 >> tg1 >> t3
```
1. Change the status of one of the tasks in the taskgroup

https://user-images.githubusercontent.com/33350052/178497737-60195a29-4bc9-4027-b5de-9d3daf00435e.mov

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

N/A

### Deployment

Other Docker-based deployment

### Deployment details

N/A

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I love the video-report :)

**Comment by josh-fell** [comment]
@pascal-knapen Thanks for submitting this issue. Definitely not the desired behavior. Can you check out Airflow 2.3.3 and see if the issue is fixed when you get a chance please? I did a quick test with the example you provided on 2.3.3 as well as the `main` branch and this seems to be fixed.

**Comment by pascal-knapen** [comment]
Thanks @bbovenzi for checking, that saved me some time this evening.
