### ISSUE TITLE
Invalid `package.json` file in `airflow/www`

### ISSUE THREAD

**Issue by tm-drtina** [apache/airflow#25007]
### Apache Airflow version

2.3.3 (latest released)

### What happened

According to npm docs fields `name` and `version` are required in `package.json`, but are not present in `airflow/www/package.json`
See: https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields

This can confuse some build tools, but also is just in incorrect format.

### What you think should happen instead

The fields `name` and `version` should be defined even if they contain just dummy values - we don't need real values since the package is not published in npm registry.

### Operating System

N/A

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@tm-drtina Good call. Feel free to open a PR!
