### ISSUE TITLE
Airflow Not able to delete a DAG both from UI as well as from Backend

### ISSUE THREAD

**Issue by AnudeepKonaboina** [apache/airflow#25015]
### Apache Airflow version

2.1.1

### Problem 

- A DAG has a DAG run for which the underlying tasks got completed but the DAG RUN is still not completed as shown below:

![image](https://user-images.githubusercontent.com/59328701/178645263-eb8fc8f6-5392-4301-ab7e-9ed5534009b7.png)

- I tried clearing/marking the DAG as success  but it keeps on loading forever and doesn't get completed. Screenshot attached below:

![image](https://user-images.githubusercontent.com/59328701/178645686-a49a66aa-e959-4835-8be3-c586e34ec4ab.png)

- Also tried to delete the dag from CLI ,but still no luck. It  gets stuck and doesn't come out as shown below
![image](https://user-images.githubusercontent.com/59328701/178646032-493e7660-ceba-4235-b321-5dc868fea9c6.png)

### What you think should happen instead

- The DAG must have been marked as success or got cleared  without any issues
- There needs to be a concept of force deleting a DAG, which must have the capability of forcibly deleting DAG in any state.
- The DAG deleting must not have got stuck forever .Instead it must have got deleted immediately

### Operating System

Debian Linux  within Docker

### Versions of Apache Airflow Providers

```
root@1ac67a4cd60c:/usr/local/airflow# pip freeze |grep apache-airflow-providers
apache-airflow-providers-celery==2.0.0
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-jdbc==2.0.0
apache-airflow-providers-microsoft-winrm==2.0.0
apache-airflow-providers-oracle==2.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-redis==2.0.0
apache-airflow-providers-samba==2.0.0
apache-airflow-providers-sftp==2.1.1
apache-airflow-providers-sqlite==2.0.0
apache-airflow-providers-ssh==2.1.1
root@1ac67a4cd60c:/usr/local/airflow#

```

### Deployment

Docker-Compose

### Anything else

This has occurred for few DAG's which are critical. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please check with latest Airflow version. Indexes were added to later versions to improve cascade deletes.
