### ISSUE TITLE
Add revisionHistoryLimit to Helm deployments

### ISSUE THREAD

**Issue by csp33** [apache/airflow#25058]
### Description

We can use this parameter to control how many old ReplicaSets we want to retain for each deployment 

### Use case/motivation

We wouldn't end up with a lot of unused replicasets in our deployment

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to create a PR
