### ISSUE TITLE
Task Group States defined for the UI aren't in the same order as the back-end python code

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#25062]
### Apache Airflow version

2.3.0

### What happened

The priority arrays defined in the following blocks of code do not set the same precedent:
- https://github.com/apache/airflow/blob/main/airflow/www/static/js/graph.js#L601-L605
- https://github.com/apache/airflow/blob/main/airflow/www/utils.py#L79-L95 

Causing a potential mismatch when defining the state of the group

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Hello,

For me this has been fixed in:
https://github.com/apache/airflow/pull/26789

Closing for now. Feel free to reopen if needed :)
