### ISSUE TITLE
AWS 

### ISSUE THREAD

**Issue by data-djinn** [apache/airflow#25084]
### What do you see as an issue?

the link to example dags in `docs/apache-airflow-providers-amazon/example-dags.rst` instead points to `tests/system/providers/amazon/aws/`

### Solving the problem

point the link instead to https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/example-dags.html

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is correct. We are in a process to migrate example dags to new hierarchy (following https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests)  where example dags are migrated to "tests/system". You see two links in the AWS providers. The new ("system tests") and legacy ("example dags"). 

![image](https://user-images.githubusercontent.com/595491/179175426-f0c99708-82b8-4ada-b503-d843b44880d0.png)
