### ISSUE TITLE
Add provider for OpenMLDB

### ISSUE THREAD

**Issue by vagetablechicken** [apache/airflow#25118]
### Description

Adds a new Provider for OpenMLDB in https://github.com/apache/airflow/tree/main/airflow/providers.

### Use case/motivation

[OpenMLDB](https://openmldb.ai/) is an open-source machine learning database. We can do feature extraction by using it.
If we have the OpenMLDB provider, users can orchestrate the model training pipeline which extracts features from OpenMLDB.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Closed due to https://github.com/apache/airflow/pull/25119#issuecomment-1189733980
