### ISSUE TITLE
Airflow Long Dag Runs overlaps runs on Tree view

### ISSUE THREAD

**Issue by ngreen-ny** [apache/airflow#25126]
### Apache Airflow version

2.2.3

### What happened

We have a bunch of dags nested inside a dag and when looking at the tree view. The dag names which are quite long seem to overlap the dag run blocks. 

Please see screenshot attached.

![airflow](https://user-images.githubusercontent.com/64902557/179531902-9468bdbe-e318-495f-802d-511701448f85.png)
.

Any idea on how we can fix this going forward?

### What you think should happen instead

Dag name in tree view should have a space and then show the dag run blocks an accomodate for longer dag names and not overlap.

### How to reproduce

Make your dag or task name like 60 characters or more and see if the dagrun blocks overlap or if they scale correctly.

### Operating System

Debian GNU/Linux 10 \n \l

### Deployment

Other 3rd-party Helm chart

### Deployment details

Helm deployment inside of AWS EKS.

Airflow Deployment:

apiVersion: v2
description: Airflow Helm Chart (User Community) - used to deploy Apache Airflow on Kubernetes
name: airflow
version: 8.5.2
appVersion: 2.2.3
icon: https://airflow.apache.org/_images/pin_large.png
home: https://github.com/airflow-helm/charts

### Anything else

This occurs constantly in version 2.2.3 of apache airflow.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Airflow has no loner Tree view. It was replaced by Grid view.
Updating Airflow to newer version will solve your issue.
