### ISSUE TITLE
Add auth_type to LivyHook

### ISSUE THREAD

**Issue by bdsoha** [apache/airflow#25179]
### Apache Airflow Provider(s)

apache-livy

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-livy==3.0.0

### Apache Airflow version

2.3.3 (latest released)

### Operating System

Ubuntu 18.04

### Deployment

Other 3rd-party Helm chart

### What happened

This is a feature request as apposed to an issue.

I want to use the `LivyHook` to communicate with a Kerberized cluster.
As such, I am using `requests_kerberos.HTTPKerberosAuth` as the authentication type.
Currently, I am implementing this as follows:

```python
from airflow.providers.apache.livy.hooks.livy import LivyHook as NativeHook
from requests_kerberos import HTTPKerberosAuth as NativeAuth

class HTTPKerberosAuth(NativeAuth):
    def __init__(self, *ignore_args, **kwargs):
        super().__init__(**kwargs)

class LivyHook(NativeHook):
    def __init__(self, auth_type=HTTPKerberosAuth, **kwargs):
        super().__init__(**kwargs)
        self.auth_type = auth_type
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
feel free to submit PR
