### ISSUE TITLE
Add `SqlExecuteQueryOperator`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#25259]
### Body

There has been previous attempt to add this operator in https://github.com/apache/airflow/pull/10011
But now after https://github.com/apache/airflow/pull/23971 is completed this should be much easier as `DbApiHook` has unified run method that works for all providers (with some configuration of parameters like `split_statements` etc..)

We can now explore again the option of `SqlExecuteQueryOperator`
There are two approaches that I can think of:
1. Creating a `BaseSqlExecuteQueryOperator` that all Sql related operators (`PostgresOperator`, `MySqlOperator`, `SnowflakeOperator`) will inherit from.
2. Deprecate the current individual operators in favor of `SqlExecuteQueryOperator` (just like https://github.com/apache/airflow/pull/10011 attempted to do)

Personally I prefer to try the 2nd approach first (It should be similar to what we do in `SqlSensor` or `SqlBranchOperator` the issue to resolve is how to handle the batch queries in some of the DBs and that is now should be possible thanks to https://github.com/apache/airflow/pull/23971  in `SqlSensor` / `SqlBranchOperator` executing batch queries was never an issue as they are expected to execute only 1 SQL statement )

FYI @potiuk @kazanzhy 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by kazanzhy** [comment]
Great idea, I like SqlSensor and use it in my pipelines.
If @mik-laj doesn't have time I could pick it up

**Comment by eladkal** [comment]
Feel free to pick it @kazanzhy
