### ISSUE TITLE
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/werkzeug/routing/__init__.py)

### ISSUE THREAD

**Issue by kennyth01** [apache/airflow#25269]
### Apache Airflow version

2.0.2

### What happened

Hi all,
Can anyone guide me, I woke up in the morning and suddenly I have this issue with the ImportError, can anyone guide me, please?

` File "/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 21, in <module>
    from flask_login import current_user
  File "/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/flask_login/login_manager.py", line 35, in <module>
    from .utils import _create_identifier
  File "/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/root/airflow-venv/airflow_virtualenv/lib/python3.7/site-packages/werkzeug/routing/__init__.py)
`

### How to reproduce

I am using virtualenv

### Operating System

using image: python:3.7.3 in bitbucket pipelines

### Versions of Apache Airflow Providers

apache-airflow==2.0.2
apache-airflow-providers-ftp==1.1.0
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-slack==4.0.0
apache-airflow-providers-sqlite==1.0.2
apache-airflow-providers-ssh==1.3.0
setproctitle==1.2.2
pytest==6.2.4
markdown==3.3.4
awscli==1.19.5
apache-airflow[databricks]

### Deployment

Virtualenv installation

### Deployment details

bitbucket pipelines deploying dags to s3, using mwaa

### Anything else

Suddenly I have this issue with the ImportError, can anyone guide me, please?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rino0601** [comment]
I also met this error, then I found my instance's werkzeug version is `2.2.0`
which is doesn't match with [constraints-3.9.txt](https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-3.9.txt) list. (werkzeug==2.1.2)

so I downgrade werkzeug to 2.1.2, problem solved in my case.

**Comment by rino0601** [comment]
- werkzeug 2.2.0 released 2 days ago (7/23) https://werkzeug.palletsprojects.com/en/2.2.x/changes/#version-2-2-0
- Change log doesn't mention any breaking change... but.. https://github.com/pallets/werkzeug/pull/2433 breaks import path. (routing.py -> `routing/__init__.py` & miss  parse_rule)

I think we need werkzeug limitation (e.g `werkzeug<2.2`) until flask_login are handle it

**Comment by potiuk** [comment]
Closed by #25270

**Comment by davidism** [comment]
Flask-Login 0.6.2 was released.

**Comment by potiuk** [comment]
> Flask-Login 0.6.2 was released.

Tahnks @davidism !. I will test it out :)

**Comment by potiuk** [comment]
https://github.com/apache/airflow/pull/25291 is running now

**Comment by kennyth01** [comment]
thanks!
