### ISSUE TITLE
Apache Airflow SqlSensor DbApiHook Error

### ISSUE THREAD

**Issue by vlcheong** [apache/airflow#25274]
### Apache Airflow version

2.3.3 (latest released)

### What happened

I trying to make SqlSensor to work with Oracle database, I've installed all the required provider and successfully tested the connection. When I run SqlSensor I got this error message
`ERROR - Failed to execute job 32 for task check_exec_date (The connection type is not supported by SqlSensor. The associated hook should be a subclass of `DbApiHook`. Got OracleHook; 419)`

### Operating System

Ubuntu 20.04.4 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.0.0
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-oracle==3.2.0
apache-airflow-providers-postgres==5.1.0
apache-airflow-providers-sqlite==3.0.0

### Deployment

Other

### Deployment details

Run on Windows Subsystem for Linux

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please use the "Common-sql" sensor for that. Instead of `from airflow.sensors import SqlSensor` use `from airflow.providers.common.sql.sensors import SqlSensors` - that should fix the problem.

Unfortunately, other than documenting it, we cannot do much about it.

Please let me know @vlcheong if it fixed your problem. if it does, I will make sure to add appropriate documentation about it.

**Comment by potiuk** [comment]
Mybe I will find another solution for that in the future as well - I will think and dig a bit deeper.

**Comment by potiuk** [comment]
Yeah. I found a solution that will make it works also if you use legacy SqlSensor (will be released in the next common.sql provider)

**Comment by potiuk** [comment]
See #25293
