### ISSUE TITLE
The AWS Secrets Backends (SM and SSM) do not allow configuration of Assume Role Methods via Backend Kwargs

### ISSUE THREAD

**Issue by ReadytoRocc** [apache/airflow#25326]
### Description

My current understanding, is that the methods documented [here](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials) outline the ways we can authorize AWS Secrets Manager or AWS Systems Manager as a [Secrets Backend](https://airflow.apache.org/docs/apache-airflow/2.3.3/security/secrets/secrets-backend/index.html). This requires managing authorization via Environment Variables or Profiles defined in an `.aws/config` file.

This does not include the Assume Role methods and configuration framework offered by the **[AWSBaseHook](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/hooks/base_aws.py#L609)**. I am proposing we extend the Secrets Backend integrations, so that they can be configured in a similar manner.

### Use case/motivation

This would enable users to have a consistent authorization and configuration framework (with the Hooks/Operators) when connecting to AWS Secrets Backends. This could also reduce the number of cases where users need to deploy Access & Secret Keys to their Airflow environment.

For example, users could pass a Role in the `BACKEND_KWARGS` for the Worker or Scheduler (once authorized) to assume to connect to the service powering their Secrets Backend.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free . Also @o-nikolas and @ferruzzi and @vincbeck might want to chime-in

**Comment by ferruzzi** [comment]
@potiuk - I appreciate the ping.   I'm not familiar enough with the Secrets Backend yet to have any useful opinion on this one.  At face value, it sounds like a useful addition, but I can't predict any unintended side-effects at this time. :+1:

**Comment by o-nikolas** [comment]
I reviewed the linked PR #25628 and left some feedback :+1:
