### ISSUE TITLE
Unable to specify in memory db for SQL Alchemy connection

### ISSUE THREAD

**Issue by atrbgithub** [apache/airflow#25376]
### Apache Airflow version

2.3.3 (latest released)

### What happened

Prior to attempting to upgrade to Airflow 2.3.3 from Airflow 1.10.14, we had the following configuration for our tests:

```
ENV AIRFLOW__CELERY__RESULT_BACKEND="sqlite:///:memory:" \
    AIRFLOW__CORE__SQL_ALCHEMY_CONN="sqlite:///:memory:" \
    AIRFLOW__CORE__LOAD_EXAMPLES="False" \
    PYTHONPATH=${PYTHONPATH}:${APP_DIR}/dags:${APP_DIR}/plugins
```

However this now breaks with:
```
#15 25.54         url = make_url(flask_app.config['SQLALCHEMY_DATABASE_URI'])
#15 25.54         if url.drivername == 'sqlite' and url.database and not url.database.startswith('/'):
#15 25.54 >           raise AirflowConfigException(
#15 25.54                 f'Cannot use relative path: `{conf.get("database", "SQL_ALCHEMY_CONN")}` to connect to sqlite. '
#15 25.54                 'Please use absolute path such as `sqlite:////tmp/airflow.db`.'
#15 25.54             )
#15 25.54 E           airflow.exceptions.AirflowConfigException: Cannot use relative path: `sqlite:///:memory:` to connect to sqlite. Please use absolute path such as `sqlite:////tmp/airflow.db`.
```

### What you think should happen instead

Should work as before. 

### How to reproduce

Specify connection string as `sqlite:///:memory:`

### Operating System

Linux

### Versions of Apache Airflow Providers

n/a

### Deployment

Other 3rd-party Helm chart

### Deployment details

n/a

### Anything else

n/a

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Correct. We only support file-based sqlite. Sqlite is anyhow only used for development convenience and should never be used in production so we do not keep compatibility. If you wish you can make PR to fix it (if you find a way) but this is certainly not someting we support or document so it might break at any time anyway.

**Comment by atrbgithub** [comment]
Just in case anyone else runs into this, the fix is to use this for the connection string for in memory db:

```
ENV AIRFLOW__CELERY__RESULT_BACKEND="sqlite://" \
    AIRFLOW__CORE__SQL_ALCHEMY_CONN="sqlite://" \
    AIRFLOW__CORE__LOAD_EXAMPLES="False" \
    PYTHONPATH=${PYTHONPATH}:${APP_DIR}/dags:${APP_DIR}/plugins
```
