### ISSUE TITLE
CPU utilization 100 % loads in one worker nodes

### ISSUE THREAD

**Issue by karkyra** [apache/airflow#25372]
### Apache Airflow version

2.1.1

### What happened

There are 7 workers. 1 worker node loads 100% CPU utilization, 5 worker nodes CPU Utilization 70-80 % and 1 worker nodes CPU utilization within 20 %. it doesn't distributing loads equally between the nodes. 
Airflow running in Kubernetes and using airflow Kubernetes executor. 

### What you think should happen instead

Loads should be distributed equally between worker nodes

### How to reproduce

N/A

### Operating System

redhat 8.2

### Versions of Apache Airflow Providers

N/A

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Airflow is not a solution to distribute the load evenly. I am not sure where you took the notion that this "should" happen.

You can control your Kubernetes resources on your own if you want and fine-tune it, but Airflow does not do it (and will likely never do) on it's own.

**Comment by plutoid** [comment]
hi,

I'm using airflow 2.3.2 in docker not Kubernetes , the worker nodes are consuming almost CPUs too,  as per attachment, not sure what's doing!

VMs: 4core 16GB  
nodes: 2

any ideas for this? Many thanks!
<img width="555" alt="810" src="https://user-images.githubusercontent.com/1091981/183844947-557cd362-4976-4940-af73-2bc655996e5d.png">

**Comment by potiuk** [comment]
> hi,
> 
> I'm using airflow 2.3.2 in docker not Kubernetes , the worker nodes are consuming almost CPUs too, as per attachment, not sure what's doing!
> 
> VMs: 4core 16GB nodes: 2
> 
> any ideas for this? Many thanks! <img alt="810" width="555" src="https://user-images.githubusercontent.com/1091981/183844947-557cd362-4976-4940-af73-2bc655996e5d.png">

I thin the question is what kind of tasks your worker are running - but only you can tell it. Possibly you spin up some processes that simply consume a lot of CPU - you need to investigate further to see what your python processes are doing. This is not a widespread problem so likely this is the code you run as part of your taskt that are doing it. 

You can likely use 'trace' built in module or I actually recommend pyflame https://pyflame.readthedocs.io/en/latest/usage.html to produce interactive flamechart. See the instructions on how to run it - but it can give answer what actually takes the time.

I woudl be very curious to see results of the investigation you do and flamechart.

**Comment by plutoid** [comment]
I'm still struggling with issue that pyflame not support py3.7, since airflow now running on py3.7.
https://github.com/uber-archive/pyflame/issues/120

**Comment by plutoid** [comment]
hi,

@potiuk  , at last I use py-spy instead to capture the processes for flame  graph , kindly have a look, thanks a lot!

![816](https://user-images.githubusercontent.com/1091981/185001854-62a0788e-a3ab-4ba4-b914-a341fe36b010.svg)

**Comment by potiuk** [comment]
Sorry for delay - but it Looks like vast majority of time is exec ssh command - You seem to have an SSH hook that likely simply gets a lot of output to process and it it does so.

**Comment by plutoid** [comment]
thanks for your reply, I will check with my colleagues and see what will happen if we direct output to /dev/null.
