### ISSUE TITLE
Adding execution time monitoring feature to Airflow for monitoring long running of tasks

### ISSUE THREAD

**Issue by deepaklearner** [apache/airflow#25433]
### Description

Adding execution time monitoring feature to Airflow for monitoring long-running tasks. Also, an alerting feature will be added, which will compare the runtime with the average of the last 15 runs (excluding the boundary ones after sorting the run time values to exclude any erroneous data).

### Use case/motivation

The execution time monitoring and alerting feature is currently available with most of the paid schedulers in the market. This key feature is missing in Airflow due to which the support team spends a lot of time in manual monitoring for execution time.

### Related issues

No

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
It's under progress in [AIP-49 OpenTelemetry Support for Apache Airflow](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-49+OpenTelemetry+Support+for+Apache+Airflow)
