### ISSUE TITLE
Helm Chart: Allow adding annotations to statsd deployment

### ISSUE THREAD

**Issue by sbrandtb** [apache/airflow#25446]
### Description

Helm Chart [does not allow adding annotations](https://github.com/apache/airflow/blob/40eefd84797f5085e6c3fef6cbd6f713ceb3c3d8/chart/templates/statsd/statsd-deployment.yaml#L60-L63) to StatsD deployment. We should add it.

### Use case/motivation

In our Kubernetes cluster we need to set annotations on deployments that should be scraped by Prometheus. Having an exporter that does not get scraped defeats the purpose :slightly_smiling_face:

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
@sbrandtb, would you be interested in opening a PR to add it?

**Comment by sbrandtb** [comment]
@jedcunningham Yes, that should be no problem. I just need to find some time for doing it. Probably not this week, but next.

**Comment by potiuk** [comment]
I assigned you now @sbrandtb but I am happy to co-assign you as well @joshuaghezzi (but you need to comment here)

**Comment by joshuaghezzi** [comment]
@potiuk sounds good 🙂

**Comment by sbrandtb** [comment]
As I said: No offense. Just not a good job sticking to the process :slightly_smiling_face: I unassigned myself again because I am not part of the solution anymore. Waiting for this to be released, thanks
