### ISSUE TITLE
URL contains tag query parameter but Airflow UI does not correctly visualize the tags

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#25493]
### Apache Airflow version

2.3.3 (latest released)

### What happened

An URL I saved in the past, `https://astronomer.astronomer.run/dx4o2568/home?tags=test`,  has the tag field in the query parameter though I was not aware of this. When I clicked on the URL, I was confused because I did not see any DAGs when I should have a bunch.

After closer inspection, I realized that the URL has the tag field in the query parameter but then noticed that the tag box in the Airflow UI wasn't properly populated.

![screen_shot_2022-07-12_at_8 11 07_am](https://user-images.githubusercontent.com/5952735/182496710-601b4a98-aacb-4482-bb9f-bb3fdf9e265f.png)

### What you think should happen instead

When I clicked on the URL, the tag box should have been populated with the strings in the URL.

### How to reproduce

Start an Airflow deployment with some DAGs and add the tag query parameter. More specifically, it has to be a tag that is not used by any DAG.

### Operating System

N/A

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
So in the UI you're not able to put in an invalid tag, but a url could be wrong. The webserver should catch an invalid tag and remove it, listing all dags.

Around [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L824) we should check if the DagTags exists and remove any invalid ones.

[Here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L781) is an example of how to redirect the page.
