### ISSUE TITLE
Add documentation for Facebook Ads connection type

### ISSUE THREAD

**Issue by josh-fell** [apache/airflow#25495]
Related: [#25453 (comment)](https://github.com/apache/airflow/pull/25453/files#r936183279)

Currently [no documentation exists for setting up a Facebook Ads connection](https://airflow.apache.org/docs/apache-airflow-providers-facebook/stable/index.html) used by the [`FacebookAdsReportingHook`](https://github.com/apache/airflow/blob/d0048414a6d3bdc282cc738af0185a9a1cd63ef8/airflow/providers/facebook/ads/hooks/ads.py#L43). Should users want to integrate Airflow with Facebook Ads, they would need to look through the source code to determine how they _might_ be able to setup an Airflow Connection properly.

Clear documentation on how to setup a Facebook Ads connection would improve the developer experience here.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by divyanshugit** [comment]
@josh-fell If this issue is still available, I would love to work on it.

**Comment by josh-fell** [comment]
@divyanshugit All yours!

**Comment by josh-fell** [comment]
Closing this in favor of #28790.

@divyanshugit If you would still like to contribute the documentation, please reference #28790 instead.
