### ISSUE TITLE
Dag is not created  when python is runned 

### ISSUE THREAD

**Issue by vigneshkalai** [apache/airflow#255]
After creating a project using the [tutorial site](http://pythonhosted.org/airflow/tutorial.html) I was able to create a dag and was able to run the dag and a .pyc folder was created in the same folder that is `~/airflow/dag/` 

When I create a another dag using  the same .py file with different name no dag is created but a .pyc is created in the same folder and no error is also thrown both the .py files are in the same folder 

from airflow import DAG
from airflow.operators import BashOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 1),
    'email': ['airflow@airflow.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5)

}

dag = DAG('dad', default_args=default_args) #name is changed

t1 = BashOperator(
    task_id='printdate',
    bash_command='date',
    dag=dag)

t2 = BashOperator(
    task_id='slep',
    bash_command='sleep 5',
    dag=dag)

templated_command = """
    {% for i in range(5) %}
        echo "{{ ds }}"
        echo "{{ macros.ds_add(ds, 7)}}"
        echo "{{ params.my_param }}"
    {% endfor %}
"""

t3 = BashOperator(
    task_id='temp',
    bash_command=templated_command,
    params={'my_param': 'Parameter I passed in'},
    dag=dag)

t2.set_upstream(t1)
t3.set_upstream(t1)

Is there something I am doing wrong and sorry if this a silly mistake

**Comment by vigneshkalai** [comment]
The dags are available when I type `airflow list_dags` but it is not available in the "webserver "

**Comment by morgandu** [comment]
You need to restart the airflow webserver before it shows up in UI
