### ISSUE TITLE
Add MSTeams hook and operator

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#25504]
### Description

Would be nice to have the ability to post a message to MSTeams

### Use case/motivation

Posting messages to Ms teams like slack, telagram and other integrations that Airflow has

### Related issues

There is a code in https://code.mendhak.com/Airflow-MS-Teams-Operator/
source code
https://github.com/mendhak/Airflow-MS-Teams-Operator
that can be used as ground work

I will try to find time to work on this but if someone has time to work on it before it's OK

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked it as good first issue.

**Comment by spatocode** [comment]
@potiuk Could you assign to me. I'll pick it up

**Comment by eladkal** [comment]
Policy for adding new provider is explained at https://github.com/apache/airflow/blob/main/PROVIDERS.rst

I'm going to close this issue as the process of adding a provider require investment and commitments from the requester thus it's unlikely that someone will just pick up this request and implement it so no reason to keep this issue open.
