### ISSUE TITLE
Vertical overlay scrollbar on Grid view blocks last DAG run column

### ISSUE THREAD

**Issue by Lyalpha** [apache/airflow#25512]
### Apache Airflow version

2.3.3 (latest released)

### What happened

The vertical overlay scrollbar in Grid view on the Web UI (#22134) covers up the final DAG run column and makes it impossible to click on the tasks for that DAG run:

![image](https://user-images.githubusercontent.com/12103194/182652473-e935fb33-0808-43ad-84d8-acabbf4e9b88.png)

![image](https://user-images.githubusercontent.com/12103194/182652203-0494efb5-8335-4005-920a-98bff42e1b21.png)

### What you think should happen instead

Either pad the Grid view so the scrollbar does not appear on top of the content or force the scroll bar to take up its own space

### How to reproduce

Have a DAG run with enough tasks to cause vertical overflow. Found on Linux + FF 102

### Operating System

Fedora 36

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
A small fix is proposed here https://github.com/apache/airflow/pull/25554
