### ISSUE TITLE
dockerhub readme not up to date

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#25552]
### What do you see as an issue?

README is not up to date on this page https://hub.docker.com/r/apache/airflow

### Solving the problem

re-sync with current github README

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Thanks Rafael. Updated. Unfortunately this cannot be easily automated :(
