### ISSUE TITLE
SQL error when pulling a list of Task Instances sorted by Logical Date (execution_date)

### ISSUE THREAD

**Issue by fredym** [apache/airflow#25557]
### Apache Airflow version

2.3.3

### What happened

When I pull a list of Task Instances sorted by Logical Date (execution_date) using this URL:

```
https://<host>/<path>/airflow/taskinstance/list/?_oc_TaskInstanceModelView=dag_run.execution_date&_od_TaskInstanceModelView=desc&_flt_3_state=failed&_flt_1_execution_date=2022-08-04+00%3A00%3A00%2B00%3A00
```

...I get this SQL error message:

```
psycopg2.errors.UndefinedTable: invalid reference to FROM-clause entry for table "dag_run"
LINE 5: ...022-08-04T00:00:00+00:00'::timestamptz)) ORDER BY dag_run.ex...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "dag_run_1".
```

### What you think should happen instead

I'm expecting a list of Task Instances filtered by the specified parameters but I'm getting a SQL error message instead.

Based on the error message, I presume the OMR layer is generating a malformed SQL statement. I would try updating that library as it seems like an underlying bug.

### How to reproduce

Open this URL in the browser you usually use to access Airflow UI: (replace host and path with yours)

```
https://<host>/<path>/airflow/taskinstance/list/?_oc_TaskInstanceModelView=dag_run.execution_date&_od_TaskInstanceModelView=desc&_flt_3_state=failed&_flt_1_execution_date=2022-08-04+00%3A00%3A00%2B00%3A00
```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### Anything else

This happens every time I try to open the URL mentioned above.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you - would be great to fix it.

**Comment by uranusjr** [comment]
What is this `https://<host>/<path>/airflow/taskinstance/list/` URL in the first place?

**Comment by fredym** [comment]
> What is this `https://<host>/<path>/airflow/taskinstance/list/` URL in the first place?

That's the URL to the Task Instance report that's broken. You'll have to replace `<host>` with your Airflow instance hostname and `<path>` with whatever path you have it on. In a local dev environment could be something like this:

```
https://localhost:8080/instance_one/airflow/taskinstance/list/?_oc_TaskInstanceModelView=dag_run.execution_date&_od_TaskInstanceModelView=desc&_flt_3_state=failed&_flt_1_execution_date=2022-08-04+00%3A00%3A00%2B00%3A00
```

**Comment by uranusjr** [comment]
But Airflow doesn’t serve anything under `/airflow`.

**Comment by potiuk** [comment]
Ah. Right. This is indeed not an airflow API . this mist be something you have in own installation

**Comment by fredym** [comment]
🤔 yeah this is Astronomer based. I'm gonna test this in a vanilla Airflow installation and report my findings back. Thanks for looking into this.

**Comment by uranusjr** [comment]
Feel free to drop a word to Astronomer as well, people managing that environment might be able to identify the problem more easily (I work for Astronomer but not on the platform).
