### ISSUE TITLE
Google cloud tasks sensor addition

### ISSUE THREAD

**Issue by vinitpayal** [apache/airflow#25575]
### Description

Needed a sensor for cloud tasks which can check if the cloud task queue is empty or not

### Use case/motivation

We quite often find need of us waiting for cloud task queue to get empty before we trigger rest of the tasks in airflow DAG.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vinitpayal** [comment]
@potiuk as per slack discussion sometime back, am taking it up.

**Comment by potiuk** [comment]
Assigned you :)
