### ISSUE TITLE
Mapped KubernetesPodOperater not rendering nested templates

### ISSUE THREAD

**Issue by bdsoha** [apache/airflow#25588]
### Apache Airflow version

2.3.3

### What happened

Nested values, such as `env_vars` for the `KubernetesPodOperater` are not being rendered when used as a dynamically mapped operator.

Assuming the following:

```python
op = KubernetesPodOperater.partial(
    env_vars=[k8s.V1EnvVar(name='AWS_ACCESS_KEY_ID', value='{{ var.value.aws_access_key_id }}')],
    # Other arguments
).expand(arguments=[[1], [2]])
```

The *Rendered Template* results for `env_vars` should be:
```
("[{'name': 'AWS_ACCESS_KEY_ID', 'value': 'some-super-secret-value', 'value_from': None}]")
```

Instead the actual *Rendered Template* results for `env_vars` are un-rendered:
```
("[{'name': 'AWS_ACCESS_KEY_ID', 'value': '{{ var.value.aws_access_key_id }}', 'value_from': None}]")
```

This is probably caused by the fact that `MappedOperator` is not calling [`KubernetesPodOperater._render_nested_template_fields`](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L286).

### Operating System

Ubuntu 18.04

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
MappedOperator inherits AbstractOperator, which calls `_render_nested_template_fields` via `render_template`. So the analysis seems off.

**Comment by uranusjr** [comment]
Does this work?

```python
KubernetesPodOperater(
    task_id=...,
    ...,
    env_vars=[k8s.V1EnvVar(name='AWS_ACCESS_KEY_ID', value='{{ var.value.aws_access_key_id }}')],
)
```

**Comment by bdsoha** [comment]
> Does this work?
> 
> ```python
> KubernetesPodOperater(
>     task_id=...,
>     ...,
>     env_vars=[k8s.V1EnvVar(name='AWS_ACCESS_KEY_ID', value='{{ var.value.aws_access_key_id }}')],
> )
> ```

Yes, as mentioned above the issue is only when using the operator as a mapped-operator.
