### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlparse'

### ISSUE THREAD

**Issue by sushi30** [apache/airflow#25595]
### Apache Airflow version

Other Airflow 2 version

### What happened

```python
Broken DAG: [/opt/airflow/dags/my_dag.py] Traceback (most recent call last):
  File "/opt/airflow/lib/operators/trino.py", line 5, in <module>
    from airflow.providers.trino.hooks.trino import TrinoHook as BaseTrinoHook
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/trino/hooks/trino.py", line 25, in <module>
    import sqlparse
ModuleNotFoundError: No module named 'sqlparse'
```

### What you think should happen instead

Import should succeed

### How to reproduce

Install trino hook provider 3.1.0

```shell
pip install apache-airflow-providers-trino==3.1.0
```

### Operating System

linux

### Versions of Apache Airflow Providers

2.2.2

### Deployment

Official Apache Airflow Helm Chart

### Anything else

Clearly a missing dependency. Don't know if its supposed to be in `common-sql` or in trino...?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Thanks. This is already fixed in new version of the common-sql provider that is coming out shortly https://github.com/apache/airflow/pull/23971
