### ISSUE TITLE
How to elegant add myself library to DAG

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#256]
How to add myself library to dag ?
The library is not for Airlfow expand. So I do not want to put them to Airflow plugins folder. 
It work if I append to my library path in every dags. But I need change my every dags. 
import sys
sys.path.append('/mylibrarypath/')

Is it have other elegant solution? Thank you. ; ))

**Comment by maraca** [comment]
@griffinqiu fwiw I went through the same thing yesterday.
The "cleanest" solution I came with was appending my project path to my `$PYTHONPATH` to avoid having to do `sys.path.append` on every single DAG.

Curious what others are doing?

**Comment by artwr** [comment]
One of the things we use internally, especially for more specialized libraries is to drop them in a contrib folder in the DAG folder. This gets added to the path for free. This allows for things like
`from contrib.pythonlibraryfilename import useful_function`.

IHTH

**Comment by mistercrunch** [comment]
just don't forget to add a `__init__.py` file to make that folder a package.

**Comment by mistercrunch** [comment]
Another way is to deploy you code on your machines. Python setuptools works nicely and is very easy to setup. All you need is a simple `setup.py` file with a few rules and you can `python setup.py install` the package on different machines, or through a python egg.
