### ISSUE TITLE
change Jira sdk to official atlassian sdk

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#25669]
### Description

Jira is a product of atlassian https://www.atlassian.com/
There are 
https://github.com/pycontribs/jira/issues
and
https://github.com/atlassian-api/atlassian-python-api

### Use case/motivation

Motivation is that now Airflow use unoffical SDK which is limited only to jira and can't also add operators for the other productions.

https://github.com/atlassian-api/atlassian-python-api is the official one and also contains more integrations to other atlassian products

https://github.com/atlassian-api/atlassian-python-api/issues/1027

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Sure - if someone wants to do it - there is nothing against it. That someone needs to volunteer and do it. marked it as "good first issue".

**Comment by HassanShafiq123** [comment]
I would like to do this. Please assign this issue to me.

**Comment by eladkal** [comment]
assigned

**Comment by Adityamalik123** [comment]
@potiuk @eladkal Can this issue be assigned to me? I'd be interested to work on it.

**Comment by o-nikolas** [comment]
@Adityamalik123 I've assigned the task to you :)
