### ISSUE TITLE
Tasks get stuck at random, never execute, get skipped after dag timeout

### ISSUE THREAD

**Issue by lssatvik** [apache/airflow#25672]
### Apache Airflow version

2.3.3

### What happened

I have multiple dags running regularly. Dags fail randomly for no reason. When I look at the grid view, one task is in skipped state due to dag timeout. But that task did not get executed during the entire period until timeout.

This happens randomly to any dag, to any task, at any time.

![Screenshot 2022-07-27 at 12 04 00 PM](https://user-images.githubusercontent.com/3456652/184148510-fad37728-1a6a-4d07-9c8c-55038df6372a.png)
<img width="1792" alt="Screenshot 2022-07-27 at 12 04 06 PM" src="https://user-images.githubusercontent.com/3456652/184148550-2e7bf4fe-28a1-4199-8929-14a4531d5e10.png">
<img width="1792" alt="Screenshot 2022-07-27 at 12 04 10 PM" src="https://user-images.githubusercontent.com/3456652/184148557-3cd26862-593c-417c-bcc4-0805c44d9cf1.png">
<img width="1792" alt="Screenshot 2022-07-27 at 12 04 13 PM" src="https://user-images.githubusercontent.com/3456652/184148562-7b81dfcf-ac18-4517-8f70-165969429ea5.png">

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by malthe** [comment]
Can you check the logs to see if you see something similar to this:

![image](https://user-images.githubusercontent.com/26405/185083104-bc8d8e4d-e678-41ab-8d8f-0d5fb353e207.png)

Here we lose contact to redis, but after reconnecting, the worker is in a stuck state – this would explain how your "tasks get stuck at random".

What's your setup?

**Comment by lssatvik** [comment]
@malthe What are those logs? 

I use celery and redis.

**Comment by potiuk** [comment]
Any logs. Withhout trying to see if there are some logs around the problem you are mentioning, we are not able to help. just try to correlate the logs (there are few of them - including celery, redis, schedulers, worker) and try to see if you can find any anomalies there.

**Comment by lssatvik** [comment]
I shall endeavour to obtain the logs from a feasible case. Will update once I obtain them.

**Comment by malthe** [comment]
@lssatvik it might also be that this is a duplicate of #24731. There we have some logs that hint at this being some sort of bad internal state after a redis disconnect.
