### ISSUE TITLE
`airflow dags test` command with run confs

### ISSUE THREAD

**Issue by seongwon77** [apache/airflow#25671]
### Description

Currently, the command [`airflow dags test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test) doesn't accept any configs to set run confs.  We can do that in [`airflow dags trigger`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#trigger) command through `--conf` argument.

The command `airflow dags test` is really useful when testing DAGs in local machines or CI/CD environment.  Can we have that feature for the `airflow dags test` command?

### Use case/motivation

We may put run confs same as `airflow dags trigger` command does.

Example:
```
$ airflow dags test <DAG_ID> <EXECUTION_DATE> --conf '{"path": "some_path"}'
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked it as a good first issue. Hopefully someone will implement it. But - just to let you know - the fastest and most sure way of getting such change is to do it yourself. Airlfow is an open-source project and it has more than 2100 contributors - most of them are users like you who miss some feature and decided to add it back  - this is the simplest and best contribution you can make back as a "giving back" for the free software yo use -so if you do not want to wait for someone who will pick it up, contributing it back is the fastest way to get it in :)

**Comment by pankajastro** [comment]
Hey @potiuk can I assign this to myself?

**Comment by potiuk** [comment]
assigned
