### ISSUE TITLE
Get back TI list page bulk actions that were removed in 2.3

### ISSUE THREAD

**Issue by dmishh** [apache/airflow#25724]
### Apache Airflow version

2.3.3

### What happened

TI list page bulk actions that were mistakenly removed in 2.3 by this [PR](https://github.com/apache/airflow/pull/20659).
That's why the only action you can access on TI is Delete

<img width="1485" alt="issue" src="https://user-images.githubusercontent.com/822562/184654686-4a81dbc7-3839-4efb-813c-1a1f4940d35d.png">

### What you think should happen instead

Bulk actions on TI list page should be available like in 2.2.x

![image](https://user-images.githubusercontent.com/822562/184654858-95081e7d-ff3f-4590-adf5-43bd38ebc1f8.png)

### How to reproduce

1. Visit Airflow Task Instance list page (/taskinstance/list/)
2. Select several tasks
3. Click **Actions**

### Operating System

K8s installation (AWS EKS)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Hello @dmishh,

Thank you for reporting the issue. Sorry for the late response. As of today I believe this has been fixed:
![image](https://user-images.githubusercontent.com/14861206/202544109-4e061003-7f69-4fa7-99d6-5414accd7b82.png)

Closing for now. Feel free to reopen if needed :)
