### ISSUE TITLE
Airflow returns a http URL when "Last Run" in DAGs Page is clicked though the webserver is configured to run on HTTPS

### ISSUE THREAD

**Issue by PadmajaPeri** [apache/airflow#25776]
### Apache Airflow version

Other Airflow 2 version

### What happened

We are running airflow version 2.3.1 behind an apache proxy. The base_url in the webserver in airflow.cfg is as below - 

```
[webserver]
# The base url of your website as airflow cannot guess what domain or
# cname you are using. This is used in automated emails that
# airflow sends to point links to the right web server. `airflow` is appended at
# the end so that authz regex can be defined off of this path
base_url = https://<host_name>/airflow
```

On the airflow DAGs page, when I click on "Last Run" (for a DAG) and copy the link address, I see that a https link is generated - 
`https://<host_name>/airflow/graph?dag_id=<dag_id>&execution_date=<some_date>`

However, when I load the link, the response is empty. The reason is, the link has been transformed into http as below

`http://<host_name>/airflow/dags/<dag_id>/graph?execution_date=<some_date>`

### What you think should happen instead

The returned link should be a https link since the server is running on https

### How to reproduce

1. Run airflow on https behind a proxy
2. Click on Last Run

### Operating System

Ubuntu Bionic (18.04LTS)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PadmajaPeri** [comment]
Hi, Has anyone run into this issue before? Are there any workarounds to get around this issue?

**Comment by uranusjr** [comment]
This is likely related to how your pxory is set up. Generally you need to add the `X-FORWARDED-PROTO` header (and a few others for other purposes) when the proxy forwards the request to the service for things to function properly.
