### ISSUE TITLE
Support overriding `replace_microseconds` parameter for `airflow dags trigger` CLI command

### ISSUE THREAD

**Issue by jessmchung** [apache/airflow#25836]
### Description

`airflow dags trigger` CLI command always defaults with `replace_microseconds=True` because of the default value in the API. It would be very nice to be able to control this flag from the CLI.

### Use case/motivation

We use AWS MWAA. The exposed interface is Airflow CLI (yes, we could also ask to get a different interface from AWS MWAA, but I think this is something that was just overlooked for the CLI?), which does not support overriding `replace_microseconds` parameter when calling `airflow dags trigger` CLI command.

For the most part, our dag runs for a given dag do not happen remotely at the same time. However, based on user behavior, they are sometimes triggered within the same second (albeit not microsecond). The first dag run is successfully triggered, but the second dag run fails the `replace_microseconds` parameter is wiping out the microseconds that we pass. Thus, DagRun.find_duplicates returns True for the second dag run that we're trying to trigger, and this raises the `DagRunAlreadyExists` exception.

### Related issues

Not quite - they all seem to be around the experimental api and not directly related to the CLI.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it @jessmchung

**Comment by potiuk** [comment]
Assigned you.

**Comment by MrParosk** [comment]
@uranusjr created a PR for it (https://github.com/apache/airflow/pull/27640)
