### ISSUE TITLE
Each scheduler may process same zombie tasks in HA mode

### ISSUE THREAD

**Issue by pingzh** [apache/airflow#25843]
### Apache Airflow version

main (development)

### What happened

https://github.com/apache/airflow/blob/f40ec8d6f80badbdc5dfc131ce677c7e93d6824a/airflow/jobs/scheduler_job.py#L1447-L1483

`_find_zombies` should also support HA. Each scheduler tries to find all zombie tasks. When there are more than one schedulers, it might cause issues.

### Operating System

Apple M1 Max, version: 12.2

### Deployment

Other

### Deployment details

NA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you try 2.3.4RC1?
https://github.com/apache/airflow/pull/24906 probably fixed it?

**Comment by potiuk** [comment]
Yep. This is fixed in #24906

**Comment by pingzh** [comment]
nice, thanks @eladkal and @potiuk
