### ISSUE TITLE
Task stuck as deferred

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#25859]
### Discussed in https://github.com/apache/airflow/discussions/25630

<div type='discussions-op-text'>

<sup>Originally posted by **Limess** August 10, 2022</sup>
On Airflow version 2.3.3:

A task has become stuck in the deferred state. 

Upon clearing the task, nothing happens.
Upon marking the task as a success/failure, the task is marked correctly, but after clearing it immediately goes back to deferred with the same retry number.

I'd expect the task to restart it's execution entirely when cleared.

I haven't raised a bug as I don't have any idea what to do to reproduce this - this hasn't happened to previous deferred tasks I've tried to clear

![Screenshot 2022-08-10 at 09-02-52 offline-processing-articles-update-chunked-store-full-reprocessing-range-v1 - Signal Analytics Airflow](https://user-images.githubusercontent.com/3199181/183848440-bb100b89-2786-4129-81f6-ec42d88f6e42.png)
.</div>

**Comment by potiuk** [comment]
Logs from around clearing the tasks and why it failed are necessary to solve that issue I believe @notatallshaw-gts

**Comment by notatallshaw-gts** [comment]
> Logs from around clearing the tasks and why it failed are necessary to solve that issue I believe @notatallshaw-gts

I will try to produce logs, issue however was transient and I'm not sure why 😟

**Comment by potiuk** [comment]
> I will try to produce logs, issue however was transient and I'm not sure why worried

That calls even more for more logs and details. If it was transient for you, there is no sane way no-one will be able to reproduce it (and the only way to fix the problem is to reproduce it first)

**Comment by eladkal** [comment]
I'm closing this issue as we don't have enough information to take action / reproduce it and significant time has passed without new reports for problem
