### ISSUE TITLE
Backfill CLI Behaviour 

### ISSUE THREAD

**Issue by MHAbido** [apache/airflow#25872]
### Apache Airflow version

Other Airflow 2 version

### What happened

When using the backfill cli command to rerun tasks using the following command
`airflow dags backfill dag_id -y -c extra_config -s start_date -e end_date --reset-dagruns`

we noticed indeterministic behaviour, such that if we trigger less than aprox. 35 dagruns everything is fine and the dagruns are retriggered with the expected extra_config dict. 

But if we try to backfill a bigger range of dagruns then weird things start to happen - some dagruns are trigger with the expected extra_config dict some are trigger without the expected extra_config dict. and it's random.

`Airflow Version: 2.3.0`

### Operating System

Debian GNU/Linux

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RavijitRamana** [comment]
@potiuk

**Comment by potiuk** [comment]
Not until more details are provided. This issue does not have log, analysis, trying to understand what's going on and trying to provide a reproducible case so there is no-one that could help you to diagnose your problem. 

As explained when you create an issue, when there is no clear reproduction, opening an issue is not a good idea - you should open discussion instead.

Converting it into discussion until more imformation is provided.
