### ISSUE TITLE
digest auth for http hooks?

### ISSUE THREAD

**Issue by areyoubiks** [apache/airflow#259]
Any advice for authenticating to an endpoint via digest auth? Supplying username/pass in the http config forces basic auth on the session object. Even if I hardcode the creds in the dag I don't see a way of being able to pass a requests.auth.HTTPDigestAuth object to the session in SimpleHttpOperator.

Any advice?

**Comment by mistercrunch** [comment]
Sorry about the delay answering this.

You'd have to extend the http hook functionality, many of the hooks use the `extra` column to avoid having to hardcode extra params in the code. The `requests` library seem to offer everything that is needed to hook into.
