### ISSUE TITLE
DeprecationWarning due to json_encoder in Flask 2.2

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#25909]
### Apache Airflow version

main (development)

### What happened

On Flask 2.2 starting webserver emits the following deprecation warnings : 

```
/home/karthikeyan/stuff/python/airflow/airflow/www/app.py:111 DeprecationWarning: 'app.json_encoder' is deprecated 
and will be removed in Flask 2.3. Customize 'app.json_provider_class' or 'app.json' instead.
```

The warning was added in https://github.com/pallets/flask/pull/4735

### Operating System

Ubuntu 20.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
I believe #25753 fixes this?

**Comment by tirkarthi** [comment]
Thanks @josh-fell , I searched for "json_encoder" in GitHub before opening the issue but for some reason https://github.com/apache/airflow/pull/25753 was not in the result.
