### ISSUE TITLE
How to guide for @task.docker decorator

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#25926]
### Body

Hi.

[The documentation for apache-airflow-providers-docker](https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/index.html) does not provide information on how to use the `@task.dockker `decorator. We have this decorator described only in the API reference for this provider and documentation for the apache airflow package.

Best regards,
Kamil

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Actually it is descrbed a little in https://airflow.apache.org/docs/apache-airflow/stable/tutorial_taskflow_api.html#using-the-taskflow-api-with-docker-or-virtual-environments - I think we need to move it to docker provider and add decorators to https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/index.html (and make this page - and related more compact).

**Comment by potiuk** [comment]
But I am happy to take a stab on it.

**Comment by Bowrna** [comment]
I would like to check this as I have been working on a similar issue #25711 
@potiuk Can I pick it up in case you are not working on it?

**Comment by potiuk** [comment]
Feel free.

**Comment by Bowrna** [comment]
I am currently working on this issue (and another one too) and hope to make some progress by this weekend.
