### ISSUE TITLE
Develop Mypy plugin to type-check XComArg passed to a template_field

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#25922]
### Body

Task extracted from https://github.com/apache/airflow/pull/25604#pullrequestreview-1082835392

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Comment. Would be great. Unfortunately developing MyPy plugin is not an easy task. The docs are very sparse :(

**Comment by josh-fell** [comment]
Addressed via #26023.
