### ISSUE TITLE
Gluejob creation using gluejoboperator

### ISSUE THREAD

**Issue by kumbarsg** [apache/airflow#25996]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

I tried with all the versions of airflow providers

### Apache Airflow version

2.2.2

### Operating System

on AWS

### Deployment

MWAA

### What happened

I am using Airflow Amazon provider packages on my MWAA with airflow version 2.2.2 and Aws providers version 3.2.0(also tried with further versions)
I am trying to create a glue job with GlueJobOperator with this configuration 'NumberOfWorkers': 2, 'WorkerType': 'G.1X'. Here's my code for job creation.
```
job_name = "glue_job"
    submit_glue_job = AwsGlueJobOperator(
        task_id="glue_job",
        job_name=job_name,
        wait_for_completion=True,
        # num_of_dpus=10,
        retry_limit=0,
        script_location=f"s3://bucket/etl.py",
        s3_bucket=GLUE_EXAMPLE_S3_BUCKET,
        iam_role_name=GLUE_CRAWLER_ROLE.split("/")[-1],
        create_job_kwargs={
            'GlueVersion': '3.0', 'NumberOfWorkers': 2, 'WorkerType': 'G.1X',
            "DefaultArguments": {"--enable-glue-datacatalog": ''}
        }
```
and here's the error:

```
when calling the CreateJob operation: 
Please do not set Allocated Capacity if using Worker Type and Number of Workers
```
I checked the official documentation to see if the Allocated capacity is assigned to any default value, but it's not.

- Also, it is not updating an existing job's parameters

### What you think should happen instead

It should create a glue job with provided parameters but an error is showing up saying I cannot assign values to number of workers and worker type along with Allocated capacity, which I am not assigning in my code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
I can pick this next. @eladkal @kaxil can you please assign this to me.

**Comment by kumbarsg** [comment]
The params are : 
        task_id="glue_job",
        job_name=job_name,
        wait_for_completion=True,
        # num_of_dpus=10,
        retry_limit=0,
        script_location=f"s3://bucket/etl.py",
        s3_bucket=GLUE_EXAMPLE_S3_BUCKET,
        iam_role_name=GLUE_CRAWLER_ROLE.split("/")[-1],
        create_job_kwargs={
            'GlueVersion': '3.0', 'NumberOfWorkers': 2, 'WorkerType': 'G.1X',
            "DefaultArguments": {"--enable-glue-datacatalog": ''}
            
Also, I am not able to use the Gluejoboperator on my MWAA. I then used Awsgluejoboperator for this purpose

**Comment by kumbarsg** [comment]
This is the error that I am facing while I try to use Gluejoboperator on MWAA instance: 

Broken DAG: [/usr/local/airflow/dags/Glue_sample.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/Glue_sample.py", line 8, in <module>
    from airflow.providers.amazon.aws.operators.glue import GlueJobOperator
ImportError: cannot import name 'GlueJobOperator' from 'airflow.providers.amazon.aws.operators.glue' (/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py)

**Comment by Taragolis** [comment]
@kumbarsg I saw somewhere in the airflow slack that MWAA do not support update `apache-airflow-providers-amazon` right now and it uses fixed version, I thought it use [2.4.0](https://github.com/apache/airflow/blob/providers-amazon/2.4.0/airflow/providers/amazon/aws/operators/glue.py). 

@vincbeck @ferruzzi @o-nikolas could you confirm or deny that information? (Sorry I do not actually know does you guys directly affiliated with MWAA)

**Comment by kumbarsg** [comment]
@vincbeck @Taragolis I see an issue, cannot import GlueJobOperator, but when I use AwsGlueJobOperator, it works fine. this is with apache-airflow-providers-amazon>=3.2.0 on my MWAA. 
Is there a bug that doesn't allow us to import operators from the providers package but allows us to use custom operators?

**Comment by vincbeck** [comment]
Nice timing! Just to let everyone knows, this issue has been fixed yesterday. It might not be deployed yet (depending on the region your are using). Worst case scenario, the bug should be deployed by end of next week.

@kumbarsg the bug **was** you could not upgrade the amazon provider package in MWAA. Regardless of the version you specify in `requirements.txt`, the amazon provider package used was 2.4.0

**Comment by eladkal** [comment]
from the description it doesn't sound like MWAA bug not Airflow so I'm closing this issue.
If I'm wrong please clarify
