### ISSUE TITLE
schedule_interval is not respecting the value assigned to that either it's one day or none 

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#26013]
### Apache Airflow version

main (development)

### What happened

Schedule_interval is `none` even if `timedelta(days=365, hours=6)` also its 1 day for `schedule_interval=None` and `schedule_interval=timedelta(days=3)`

### What you think should happen instead

It should respect the value assigned to it.

### How to reproduce

Create a dag with `schedule_interval=None` or `schedule_interval=timedelta(days=5)` and observe the behaviour.
![2022-08-27 17 42 07](https://user-images.githubusercontent.com/88504849/187039335-90de6855-b674-47ba-9c03-3c437722bae5.gif)

**DAG-**
```
with DAG(
    dag_id="branch_python_operator",
    start_date=days_ago(1),
    schedule_interval="* * * * *",
    doc_md=docs,
    tags=['core']
) as dag:
```

**DB Results-** 
```
postgres=# select schedule_interval from dag  where dag_id='branch_python_operator';
                              schedule_interval
------------------------------------------------------------------------------
 {"type": "timedelta", "attrs": {"days": 1, "seconds": 0, "microseconds": 0}}
(1 row)
```

### Operating System

Ubuntu

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jyotsa09** [comment]
FYI.. @ephraimbuddy

**Comment by uranusjr** [comment]
I think #25999 fixes this

**Comment by ephraimbuddy** [comment]
> I think #25999 fixes this

Looks like the issue is still there
