### ISSUE TITLE
Rewrite the in-container scripts in Python

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#26019]
We have a number of "in_container" scripts written in Bash, They are doing a number of houseekeeping stuff but since we already have Python 3.7+ inside the CI image, we could modularise them more and make them run from external and simplify entrypoint_ci (for example separate script for tests).

**Comment by Bowrna** [comment]
Could I help in this task @potiuk ?

**Comment by potiuk** [comment]
sure - pick any of those scripts, I think there are a few "standalone" scripts there that could be easily rewritten, the "entrypoint_ci.sh" is generally more complex to handle and I think about changing the idea there so might be a bit more complex, but there are quite a few scripts there ate are simple to rewrite and simply replacing .sh with corresponding .py (and replacing all the places it is used) should be quite easy and possible.

**Comment by potiuk** [comment]
Note - that this is a bit "lower" priority than getting rid of Bash in Breeze "host" - mainly because those "in-container" scripts do not have to be rewritten to make "Windows" support work, and we can rely in them on the version of Bash that is installed in our images, so this is "nice to have " kind of things (but also it might be good to go to "almost 0" bash scripts in Airlfow.

**Comment by eladkal** [comment]
@Bowrna are you still working on this issue?

**Comment by Bowrna** [comment]
no @eladkal currently i am not working on this issue.

**Comment by KesharwaniArpita** [comment]
Is this issue still open to work on?

**Comment by potiuk** [comment]
Sure

**Comment by KesharwaniArpita** [comment]
Are the install files in the `/scripts/in_container/bin` standalone to rewrite?

**Comment by KesharwaniArpita** [comment]
That means, we are trying to break the dependency between the files and the `_in_container_utils.sh` file?

**Comment by potiuk** [comment]
> That means, we are trying to break the dependency between the files and the `_in_container_utils.sh` file?

Eventually - we want to remove it entirely.

**Comment by potiuk** [comment]
Finally all the "logic" scripts will be rewritten when #36158 is merged.
