### ISSUE TITLE
Include external_executor_id in zombie detection method

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#26067]
### Description

Adjust the SimpleTaskInstance to include the external_executor_id so that it shows up when the zombie detection method prints the SimpleTaskInstance to logs.

### Use case/motivation

Since the zombie detection message originates in the dag file processor, further troubleshooting of the zombie task requires figuring out which worker was actually responsible for the task. Printing the external_executor_id makes it easier to find the task in a log aggregator like Kibana or Splunk than it is when using the combination of dag_id, task_id, logical_date, and map_index, at least for executors like Celery.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by collinmcnulty** [comment]
I don't know if there are any secondary consequences to change SimpleTaskInstance, so I want to check with the community before I just add a new parameter.

**Comment by wolfier** [comment]
The zombies query is a list of TaskInstances which has the attribute `external_executor_id`.

Without too much thought, you can probably add a new log line that prints the `external_executor_id` value.

```
            self.log.error("Killing zombie job with external_executor_id: %s", ti.external_executor_id)
```
