### ISSUE TITLE
Missing Queue values breaks API

### ISSUE THREAD

**Issue by Jorricks** [apache/airflow#26068]
### Apache Airflow version

2.3.4

### What happened

Some tasks do not have a `queue` value defined and equal `None`.
When you load the GRID view for these DAGs you get a 502 error with the following error appearing in the logs:
```
https://airflow-webserver-hdp-beta-b.is.adyen.com/api/v1/dags/my_dag_id/tasks validation error: None is not of type 'string'

Failed validating 'type' in schema['properties']['tasks']['items']['properties']['queue']:
    {'readOnly': True, 'type': 'string'}

On instance['tasks'][4]['queue']:
    None
```

For most people this is not an immediate issue but for people using [passive health checks inside NGINX](https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check/#passive-health-checks), it is a huge issue.
What is happening is that a single user visits a DAG that has some invalid data (according to the old schema), the API returns a 502. Then the browser retries, we have another 502. Each 502 will temporarily take the host out of the active host lists inside NGINX. Even though we have 5 webserver instances, often they are all taken out of the active host lists in NGINX as they all returned a 502 in the passed seconds. Especially if you have 100+ users, the changes of multiple users loading the GRID view for a DAG at the same time, are quite high meaning we are seeing BAD GATEWAY erros very often now.

### What you think should happen instead

The API should return a successful 200 response with the data.
The schema should allow for the `queue` to be nullable. Currently it's not as you can see here:
```
        retries:
          type: number
          readOnly: true
        queue:
          type: string
          readOnly: true
        ...
        execution_timeout:
          $ref: '#/components/schemas/TimeDelta'
          nullable: true
```
We should add `nullable: true` to this field. Currently this crashes the webserver with this error.

### How to reproduce

Create some TaskInstances.
Then make the queue field empty in a Database.
You can check this in the TaskInstance view:
![image](https://user-images.githubusercontent.com/20257392/187467130-dc75f0f4-0ac7-4059-aa3b-d757f91c57b1.png)
Then open the GRID view.

### Operating System

CentOS Linux 7 (Core)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-apache-druid==2.0.2
    # via apache-airflow
apache-airflow-providers-apache-hdfs==2.1.1
    # via apache-airflow
apache-airflow-providers-apache-hive==2.0.2
    # via apache-airflow
apache-airflow-providers-apache-spark==2.0.1
    # via apache-airflow
apache-airflow-providers-celery==2.1.0
    # via
    #   -r adyen_airflow/requirements/requirements.txt
    #   apache-airflow
apache-airflow-providers-ftp==2.0.1
    # via apache-airflow
apache-airflow-providers-http==2.0.1
    # via apache-airflow
apache-airflow-providers-imap==2.0.1
    # via apache-airflow
apache-airflow-providers-pagerduty==2.0.1
    # via apache-airflow
apache-airflow-providers-postgres==2.3.0
    # via apache-airflow
apache-airflow-providers-sqlite==2.0.1
    # via apache-airflow
```

### Deployment

Other

### Deployment details

Deployed on centos boxes without virtualisation

### Anything else

This problem occurs only on specific DAGs. It remains unknown to me why we have tasks that do not have a Queue specified.
My expectation is that new tasks were added, then these tasks are set to success by setting the DAGRun to a success.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jorricks** [comment]
From what I can see, this is only present for TaskInstance created by older Airflow versions as long as you don't use the `ti_mutation_hook`.
```
    def _get_task_creator(
        self, created_counts: Dict[str, int], ti_mutation_hook: Callable, hook_is_noop: bool
    ) -> Callable:
        """
        Get the task creator function.

        This function also updates the created_counts dictionary with the number of tasks created.

        :param created_counts: Dictionary of task_type -> count of created TIs
        :param ti_mutation_hook: task_instance_mutation_hook function
        :param hook_is_noop: Whether the task_instance_mutation_hook is a noop

        """
        if hook_is_noop:

            def create_ti_mapping(task: "Operator", indexes: Tuple[int, ...]) -> Generator:
                created_counts[task.task_type] += 1
                for map_index in indexes:
                    yield TI.insert_mapping(self.run_id, task, map_index=map_index)

            creator = create_ti_mapping

        else:

            def create_ti(task: "Operator", indexes: Tuple[int, ...]) -> Generator:
                for map_index in indexes:
                    ti = TI(task, run_id=self.run_id, map_index=map_index)
                    ti_mutation_hook(ti)
                    created_counts[ti.operator] += 1
                    yield ti

            creator = create_ti
        return creator
```

The `TI.insert_mapping` will set the `queue` for you. The other one however, will not set the `queue` for you, so I can imagine if you just spawned a couple TaskInstances, you will get the same error.

**Comment by Jorricks** [comment]
I think it might fail on more than just this field.
It seems when new TaskInstances are spawned, there are a lot of fields that don't adhere to this schema:
![image](https://user-images.githubusercontent.com/20257392/187478922-5f426a75-94c0-4ba2-9ff1-d41175b2bb7a.png)

**Comment by eladkal** [comment]
completed  https://github.com/apache/airflow/pull/26076 https://github.com/apache/airflow/pull/26077

**Comment by Jorricks** [comment]
> completed  https://github.com/apache/airflow/pull/26076 https://github.com/apache/airflow/pull/26077

Given its removed from the 2.3.5. Milestone, cab u assume we are not planning on doing a 2.3.5 release?

**Comment by eladkal** [comment]
> Given its removed from the 2.3.5. Milestone, cab u assume we are not planning on doing a 2.3.5 release?

milestones are set on the PRs so no need for one on the issue.
i don't think there will be 2.3.5

**Comment by Jorricks** [comment]
> > Given its removed from the 2.3.5. Milestone, cab u assume we are not planning on doing a 2.3.5 release?
> 
> milestones are set on the PRs so no need for one on the issue.
> i don't think there will be 2.3.5

Thang for the swift reply!
