### ISSUE TITLE
Unable to remove default value from auth_backends

### ISSUE THREAD

**Issue by Shubham3009** [apache/airflow#26085]
### Apache Airflow version

Other Airflow 2 version

### What happened

Hi ,
I am using Airflow 2.3.2 and getting below Warning while calling Airflow APIs ,

airflow jobs check
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:356: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0. warnings.warn(
Found one alive job.

airflow version
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:356: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.  warnings.warn(
2.3.2

I tried to override AUTH_BACKENDS as below , but default values is still in use and not getting overridden by my value.

name: AIRFLOW__API__AUTH_BACKENDS
value: "airflow.api.auth.backend.basic_auth"
In airflow.cfg , Currently I see two values for auth_backends as below ,
auth_backends : airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
-- | --

Because of this behavior , am unable to apply livness probe on SCHEDULER to autorestart if heartbeat not received.

Please help to resolve this warning or override auth_backend default value.

### Operating System

Ubuntu 18.04.5 LTS

### Deployment

Other 3rd-party Helm chart

### Deployment details

https://github.com/bitnami/charts/tree/master/bitnami/airflow

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is a bitnami chart. Not ours. In official community chart the values can get overwritten as you expected.  I recommend you to switch to the official chart of the Airflow Community: https://airflow.apache.org/docs/helm-chart/stable/index.html or raise your issue to bitnami.
