### ISSUE TITLE
Add one_done trigger rule

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#26099]
### Body

Action: trigger as soon as 1 upstream task is in success or failuire
This has been requested in https://stackoverflow.com/questions/73501232/how-to-implement-the-one-done-trigger-rule-for-airflow
I think this can be useful for the community.

**The Task:**
Add support for new trigger rule `one_done`
You can use as reference previous PRs that added other trigger rules for example: https://github.com/apache/airflow/pull/21662

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajastro** [comment]
Hey @eladkal Have you started working on this if not is it ok if I can work on this?

**Comment by eladkal** [comment]
sure
