### ISSUE TITLE
UI: Task duration view always shows local time

### ISSUE THREAD

**Issue by cccs-seb** [apache/airflow#26110]
### Apache Airflow version

Other Airflow 2 version

### What happened

Task duration view always shows local time and doesn't represent the selected timezone (e.g. Graph still shows EDT if I choose UTC in the timezone picker)

### What you think should happen instead

The times displayed in the graph should match the timezone selected.

### How to reproduce

Steps:
- Go to the Task duration screen for any DAG;
- Select UTC timezone
- Look at the graph, it will be local (EDT in my case)

### Operating System

Debian GNU/Linux 11 (bullseye)  (we use the official docker image as base)

### Deployment

Official Apache Airflow Helm Chart

### Anything else

Airflow version 2.3.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hungtsetse** [comment]
can I work on this since it still occurs in version 2.5

**Comment by potiuk** [comment]
Sure. Assigned you.

**Comment by hungtsetse** [comment]
I just had an overview of this issue, and would like to get some suggestions for addressing properly.

The chart of Task Duration is generating at server side as html and pass to Falsk for further rendering, so it can't get the selected timezone on browser.

Epoch time was literally converted by `time.mktime` which is based off server local time.
https://github.com/apache/airflow/blob/1cf1fc46e95c889c8c81bb2ed2c3f08a681bf7e3/airflow/www/views.py#L3083

Additionally, it's also happending on "Task Tries" and "Landing Times" tabs which generate charts with the similar approach.

**Comment by potiuk** [comment]
Part of the issue is really to figure out what to do - it's best to discuss your doubts when you have a PR and would like to get feedback. If you do not have an idea how to fix it, enough to raise a PR and start discussing it, I think it's best to find a taks where you will be able to get to the point on your own.

**Comment by tirkarthi** [comment]
Task duration page is now implemented in react in #35863. It shows the timestamp with selected timezone on hovering the bar in chart. Same for dagrun duration chart as well. I guess this can be closed.

cc: @bbovenzi
