### ISSUE TITLE
Add CLI to add/remove permissions from existed role

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#26155]
### Body

Followup on https://github.com/apache/airflow/pull/25854
[Roles CLI](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#roles) currently support create, delete, export, import, list

It can be useful to have the ability to add/remove permissions from existed role.
This has also been asked in https://github.com/apache/airflow/issues/15318#issuecomment-872496184

cc @chenglongyan

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by chenglongyan** [comment]
@eladkal  I'm working on...

**Comment by thuy-bui-ts** [comment]
I thought remove/add role from an existing users is already provided in user command ( airflow users remove-role ...) you can find it here [https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#remove-role](url)
