### ISSUE TITLE
Extra entry for logs generated with 0 try number when clearing any task instances 

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#26194]
### Apache Airflow version

main (development)

### What happened

When clearing any task instances an extra logs entry generated with Zero try number.

<img width="1344" alt="Screenshot 2022-09-07 at 1 06 54 PM" src="https://user-images.githubusercontent.com/88504849/188819289-13dd4936-cd03-48b6-8406-02ee5fbf293f.png">

### What you think should happen instead

It should not create a entry with zero try number

### How to reproduce

Clear a task instance by hitting clear button on UI and then observe the entry for logs in logs tab

### Operating System

mac os

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jyotsa09** [comment]
@ephraimbuddy @jedcunningham

**Comment by ephraimbuddy** [comment]
cc: @bbovenzi
