### ISSUE TITLE
`depends_on_past` is ignored when upstream is skipped

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#26200]
### Apache Airflow version

2.3.4

### What happened

If we have an hourly dag of 2 tasks `T1` and `T2` (`T1 >> T2`), and `T2` has `depends_on_past=True`, if at the run of 10:00 `T1` is skipped, `T2` is directly marked as skipped too without waiting the task of the previous run 09:00, then in the next run 11:00, `T2` can be executed where `T2` of its previous run is skipped.

### What you think should happen instead

If the task has `depends_on_past=True`, we should not change its state before that the same task of the previous run is marked as `succeeded` or `skipped`.

### How to reproduce

Here is a simple dag which can help to reproduce the problem:
```python
from datetime import datetime

from airflow import DAG
from airflow.exceptions import AirflowSkipException
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator

with DAG(
        dag_id='dag',
        start_date=datetime(2022, 1, 1),
        schedule_interval=None,
) as dag:
    def t1_callable(**context):
        dag_run_conf = context["dag_run"].conf
        if dag_run_conf.get("skip_t1"):
            raise AirflowSkipException()

    t1 = PythonOperator(
        task_id="T1",
        python_callable=t1_callable
    )
    t2 = BashOperator(
        task_id="T2",
        bash_command="sleep {{dag_run.conf.get('sleep_seconds', 1)}}",
        depends_on_past=True,
    )
    t1 >> t2

```
Then using Airflow CLI:
```bash
airflow dags trigger dag --conf '{"sleep_seconds":1000}'
airflow dags trigger dag --conf '{"skip_t1":true}'
airflow dags trigger dag --conf '{"sleep_seconds":10}'
```

### Operating System

Debian GNU/Linux

### Deployment

Official Apache Airflow Helm Chart

### Anything else

In some cases `max_active_runs` can help to avoid this problem, but we have dags with tasks not dependent on past, which we prefer to run ASAP and keep the dag running waiting the tasks which depend on past runs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Hmmm I think everything is as expected. 

1) when you manually set task on 10.00  to "skipped" - it will be skipped without taking "depends_on_past" into account. "Depends_on_past" only prevents the tasks from RUNNING when the same task in previous instance is not "succeeded" or "skipped". But when you manually force it to "skip" this is not done. If you would like it to "wait" for previous task to run, you would have to have a new state "waiting for skipping" or smth. I.e. you would like to have a state when we know that the task should be skipped immediately when it is eligible to run. Airfow has no such state and it's quite doubtful if it will ever have one

2) Then the task at 11.00 will only look at the "last previous", not "all previous" tasks and it will see tha the previous task is skipped, so it will run immediately.

All is fine, as expected and perfectly reflects the current state of Airflow implementation, so this is not a bug.

What you likely would like to get instead is a new feature for example "depend_on_all_past_not_runnning" or similar, where you should check if there is ANY past task that is currently not "completed" and "queued" or "running". But I think this one is not needed. It is quite a bit more complex to implemented, I think and  it might be a bit more "predictable" in terms of execution sequence, but probably much better, simpler and something that you can implement even now, is to assign a separate pool for your task with size = 1. This will make sure that only one task instance can run at a time. This is PROBABLY what you really want to achieve. There is no guarantee on sequence of execution - so if you run 5 of those instances one after the other then, they will execute in a "random" sequence, but In most cases of scheduled run, they should run in a proper sequence as past task will be already running while the future task is scheduled.

Converting to a discussion.
