### ISSUE TITLE
Broken Link for 'trigger rule' on DAG Runs page

### ISSUE THREAD

**Issue by mr-t1000** [apache/airflow#26214]
### What do you see as an issue?

On the [DAG Runs page](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#dag-runs), in the [DAG Run Status](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#dag-run-status) section, there is a link for [trigger rule](https://airflow.apache.org/docs/apache-airflow/stable/dags.html#trigger-rules) which results in a 404 Not Found error

### Solving the problem

I'd be happy to help fix this but I don't know where the link should point to.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PApostol** [comment]
I think that has already been fixed in #25840.
