### ISSUE TITLE
should we limit max queued dag runs for dataset-triggered dags

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#26259]
if a dataset-triggered dag is running, and upstreams are updated multiple times, many dag runs will be queued up because the scheduler checks frequently for new dag runs needed.

you can easily limit max active dag runs but cannot easily limit max queued dag runs.  in the dataset case this represents a meaningful difference in behavior and seems undesirable.

i think it may make sense to limit max queued dag runs (for datasets) to 1.   cc @ash @jedcunningham @uranusjr @blag @norm

the graph below illustrates what happens in this scenario.  you can reproduce with the example datasets dag file. change consumes 1 to be `sleep 60` , produces 1 to be `sleep 1`, then trigger producer repeatedly.

![image](https://user-images.githubusercontent.com/15932138/189264897-bbb6abba-9cea-4307-b17b-554599a03821.png)

**Comment by ashb** [comment]
> if a dataset-triggered dag is running, and upstreams are updated multiple times, many dag runs will be queued up because the scheduler checks frequently for new dag runs needed.

This is but design to my mind. Each time a dataset updates the a down stream dag run should be created to process that.

In future we can add some mechanism to give more control over this -- either using `catchup` flag, or some other mechanism that we've talked/hinted/thought about that works also let your control the all/any for multiple datasets.

**Comment by ashb** [comment]
Oh! We already have `max_active_runs` on DAG but we aren't respecting that for dataset triggering! Ooos
