### ISSUE TITLE
helm chart doc Manage DAGs files recommended Bake DAGs in Docker image need improvement.

### ISSUE THREAD

**Issue by BobDu** [apache/airflow#26262]
### What do you see as an issue?

https://airflow.apache.org/docs/helm-chart/1.6.0/manage-dags-files.html#bake-dags-in-docker-image

> The recommended way to update your DAGs with this chart is to build a new Docker image with the latest DAG code:

In this doc , recommended user manage dags way is build in image.

But , ref this issue: 
https://github.com/airflow-helm/charts/issues/211#issuecomment-859678503

> but having the scheduler being restarted and not scheduling any task each time you do a change that is not even scheduler related (just to deploy a new DAG!!) 

> Helm Chart should be used to deploy "application" not to deploy another version of DAGs. 

So, I think bake dags in docker image should not be the most recommended way.

At least. We should say this way weaknesses (restart all components when jsut deploy a new DAG!) in docs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to propose a PR. It's as easy as clicking "Suggest a change on this page" when you look at the doc,
