### ISSUE TITLE
Feature Request: Initiate multiple instances of same dag in parallel?

### ISSUE THREAD

**Issue by azaroth42** [apache/airflow#263]
Request:  We'd love to be able to run the same dag in parallel with different input, preferably from an operator.  This would enable batch processing of content to be parallelized via the messaging/executor framework, while each manipulation of the data is its own operator and hence individually testable and recomposable (plus all other great features).

Something along the lines of:

``` python
class DagExecutingOperator():
  def execute(self, context):
    for item in somelist:
      dag.execute(params={'input':item})
```

Here's our use case, and what I think we would like to support it, but as a novice airflower (:dash::tulip:), any pointers in better directions would be greatly appreciated.

We have a reasonable chunk of data in a system that we want to migrate away from, but there are so many business processes associated with it, that will be a multi-year project. In order to convince our stakeholders of the correctness of any new solution, we're going to have to iterate over and over this dataset making incremental improvements (you all know how it is, I'm sure!).  

We've been experimenting with two approaches, breadth-first and depth-first:
- Breadth-first: The DAG does (say) 10 steps, where each step does one process on every record.  We can parallelize by partitioning the data and setting the first step of the DAG to check if there's a partition not being processed, but the resource contention is huge, as all of the same compute/IO resources are needed at the same time... for example, the last step of writing the merged record to a database means that we're blocked on IO while the rest of the system stands idle. 
- Depth-first: So we went back to depth-first where a single record flows all the way through the DAG before returning to the next one.  We tried various nasty tricks (have you tried setting the heartbeat configs to 0 with a schedule_interval of 1 second? :smile_cat: ) but at the end of the day, it seems like an iterator that kicks off DAGs would solve our issue in a way that we could use the scheduling code as it's intended. 

Any advice or thoughts would be appreciated.

**Comment by mistercrunch** [comment]
Are you trying to do stream processing with Airflow? Airflow is a **batch workflow engine**, not a stream processing engine. If the duration of most of your batch jobs is less than a few minutes, Airflow probably isn't the right system.

The schedule interval we use is usually 1 day, but have many hourly DAGs that work very well. As you get closer to 5 minutes scheduler intervals, you need to start thinking in terms of realtime / stream processing and use the systems designed to do that (storm, spark streaming, ...)

What is your unit of work? What's you pivot point, as in one dag per **blank** ? file?

btw you can generate dags dynamically, the same way that you can generate tasks dynamically, you just have to stamp it in the global namespace of your module. But I get a sense that you are bending Airflow in doing things it wasn't designed for, which is fine if it works for you.

```
business_units = ['CA01', 'US01', 'US02']
for bu in in business_units:
    globals()[bu] = DAG(dag_id=bu)
    ...
```

All of these would show up in the UI

**Comment by mistercrunch** [comment]
Re-open if needed.
