### ISSUE TITLE
Whitespaces disappear when referencing file content

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#26364]
### What do you see as an issue?

Looking at the [TaskFlow API tutorial](https://airflow.apache.org/docs/apache-airflow/stable/tutorial_taskflow_api.html), it appears whitespaces are missing in the code:

![image](https://user-images.githubusercontent.com/6249654/189884877-3ad87452-a697-49e2-b843-fc7c249fb0eb.png)

While they are present in the code: https://github.com/apache/airflow/blob/88b274c95b212b541ba19918880ae425856212be/airflow/example_dags/tutorial_taskflow_api_etl.py#L27-L30.

Whitespaces should be correctly shown in the docs if present in the code.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yeah. Small but annoying issue :)

**Comment by rbb17** [comment]
@eladkal Would like to work on this issue, can you assign it to me?

**Comment by anuj-walia** [comment]
I would like to work on this . Please assign to me
