### ISSUE TITLE
SparkKubernetesSensor credential expires in 20 min

### ISSUE THREAD

**Issue by lyso** [apache/airflow#26379]
### Apache Airflow Provider(s)

amazon

### Apache Airflow version

2.2.2

### Operating System

centos rhel fedora

### Deployment

MWAA

### Deployment details

v2.2.2

### What happened

When using SparkKubernetesSensor, the task failed if the pod running for more than 20 minutes.

Error message raised on the 21st minute:

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```
The assumed root cause was the credential expires at 20 minutes, which caused the 401 error.

### What you think should happen instead

The Sensor should keep renew the credential every time call poke, or capture credential expire exception and renew credential.

### How to reproduce

Reproduce is very easy. It always fail at 21st minute.

1. prepare EKS that spark can run more than 20 minutes.
2. use the following DAG to trigger the spark.

```python

from airflow.models.dag import DAG
from airflow.providers.cncf.kubernetes.operators.spark_kubernetes import SparkKubernetesOperator
from airflow.providers.cncf.kubernetes.sensors.spark_kubernetes import SparkKubernetesSensor

with DAG(...):
    task1 = SparkKubernetesOperator(...)
    task2 = MySparkKubernetesSensor(...)
    task1 >> task2

```

### Anything else

I find a workaround for this issue: override the poke function with my own class which inherit from SparkKubernetesSensor.

```python

from airflow.models.dag import DAG
from airflow.providers.cncf.kubernetes.operators.spark_kubernetes import SparkKubernetesOperator
from airflow.providers.cncf.kubernetes.sensors.spark_kubernetes import SparkKubernetesSensor, KubernetesHook, AirflowException


class MySparkKubernetesSensor(SparkKubernetesSensor) :
    def poke(self, context: dict) -> bool:
        self.log.info("Poking: %s", self.application_name)
        # Only change here: create a new hook evertime poke instead of reuse the same hook
        response = KubernetesHook(conn_id=self.kubernetes_conn_id).get_custom_object(
            group=self.api_group,
            version=self.api_version,
            plural="sparkapplications",
            name=self.application_name,
            namespace=self.namespace,
        )
        try:
            application_state = response["status"]["applicationState"]["state"]
        except KeyError:
            return False
        if self.attach_log and application_state in self.FAILURE_STATES + self.SUCCESS_STATES:
            self._log_driver(application_state, response)
        if application_state in self.FAILURE_STATES:
            raise AirflowException(f"Spark application failed with state: {application_state}")
        elif application_state in self.SUCCESS_STATES:
            self.log.info("Spark application ended successfully")
            return True
        else:
            self.log.info("Spark application is still in state: %s", application_state)
            return False



## put the above in the DAG file
## in the dag file, use MySparkKubernetesSensor replacing SparkKubernetesSensor like below


with DAG(...):
    task1 = SparkKubernetesOperator(...)
    task2 = MySparkKubernetesSensor(...)
    task1 >> task2
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think something to take a look by @ferruzzi @o-nikolas @vincbeck to take a look at.

**Comment by o-nikolas** [comment]
I'm not a spark/kubernetes expert, but does this really have anything to do with AWS? The response body you're getting is from the kubernetes api which is using it's own connection/client from the cncf hook modules to hit the `CustomObjectsApi` (I have no idea what this is). This request is timing out. I'd have to do a deep dive to see how the cncf client does authentication and how that may be timing out, but I hope there are others who know more who can jump in.

**Comment by potiuk** [comment]
Yeah I think you are right.  this is likely Spark Kubernetes Issue only.

**Comment by eladkal** [comment]
We had similar issue with EKS creds expiring after 15 minutes https://github.com/apache/airflow/pull/17951

**Comment by o-nikolas** [comment]
> We had similar issue with EKS creds expiring after 15 minutes #17951

Indeed, but in that case, the code in question was AWS hooks/operators and was interacting with EKS directly. This issue seems to be at the Spark/Kube level in cncf modules only. Though, again, I'm no expert.

**Comment by o-nikolas** [comment]
> Yep.. this is why I marked this on as Kubernetes label rather than aws :)

I was just confused because you linked an AWS related issue, my bad! :)
