### ISSUE TITLE
Deadlock dag_runs when max_active_runs=1 and dag_duration greater then schedule interval

### ISSUE THREAD

**Issue by was-av** [apache/airflow#26397]
### Apache Airflow version

Other Airflow 2 version

### What happened

When max_active_runs set 1, new dag runs stopped when slow dag run duration greater then schedule interval

### What you think should happen instead

New dag runs don't stop execution after slow dag run finished.

### How to reproduce

DAG for reproduce
```python
from airflow import DAG
from airflow.operators.bash import BashOperator
from pendulum import datetime

default_args = {"owner": "airflow"}

with DAG(
    dag_id="deadlock",
    start_date=datetime(2020, 2, 2),
    schedule_interval="* * * * *",
    catchup=False,
    default_args=default_args,
    max_active_runs=1,
    tags=["test"],
) as dag:
    op1 = BashOperator(task_id="op1", bash_command="echo START ; sleep 70; echo END")
```

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Versions of Apache Airflow Providers

Apache Airflow
version                | 2.3.2 

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by was-av** [comment]
I don't find this fix in the changelog, but this bug is not reproducible in version 2.3.4.
Thanks for the quick response.

**Comment by potiuk** [comment]
Yeah. Sometimes we get such fixes as "by-product" of other fixes, so upgrading to latest version from the "major" line is always good thing to try first. Saves a ton of time!
