### ISSUE TITLE
helm chart fails during `post-install`

### ISSUE THREAD

**Issue by eeluve** [apache/airflow#26405]
### Official Helm Chart version

1.6.0 (latest released)

### Apache Airflow version

2.3.0

### Kubernetes Version

v1.20.6

### Helm Chart configuration

```
- helm repo add apache-airflow https://airflow.apache.org
- helm repo update
- helm upgrade -i airflow apache-airflow/airflow -n airflow
                      --set images.airflow.repository=$pathToOurGLABprojContReg
                      --set images.airflow.tag=stg
                      --set images.airflow.pullPolicy=Always
                      --set registry.secretName=airflowreg
                      --set nodeSelector."kubernetes\\.io/hostname"=$nodeName
                      --set fernetKey="$sens"
                      --set workers.persistence.size=30Gi
                      --create-namespace
                      --wait=false
                      --kubeconfig some-config.yaml
```

also had ::
--set webserverSecretKey=""
temporarily removed, testing one of hypotheses based on k8s events for a namespace

### Docker Image customisations

```
FROM apache/airflow

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
            default-libmysqlclient-dev \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow \
    airflow-clickhouse-plugin \
    apache-airflow-providers-mysql

COPY ./dags ${AIRFLOW_HOME}/dags
COPY ./plugins ${AIRFLOW_HOME}/plugins
COPY ./files ${AIRFLOW_HOME}/files
```

### What happened

recently deploy attempts end up in a state like this ::

```
NAME                                       READY   STATUS    RESTARTS   AGE
pod/airflow-postgresql-0                   1/1     Running   0          15m
pod/airflow-redis-0                        0/1     Pending   0          15m
pod/airflow-run-airflow-migrations-5j9qc   0/1     Pending   0          15m
pod/airflow-scheduler-588cbbf87f-j7z52     0/2     Pending   0          15m
pod/airflow-statsd-58d7f8d864-brpb5        0/1     Pending   0          15m
pod/airflow-triggerer-6cc749dbb4-q6549     0/1     Pending   0          15m
pod/airflow-webserver-747bffcccd-lr5bl     0/1     Pending   0          15m
pod/airflow-worker-0                       0/2     Pending   0          15m

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/airflow-postgresql            ClusterIP   10.233.26.13    <none>        5432/TCP            15m
service/airflow-postgresql-headless   ClusterIP   None            <none>        5432/TCP            15m
service/airflow-redis                 ClusterIP   10.233.51.154   <none>        6379/TCP            15m
service/airflow-statsd                ClusterIP   10.233.11.53    <none>        9125/UDP,9102/TCP   15m
service/airflow-webserver             ClusterIP   10.233.39.52    <none>        8080/TCP            15m
service/airflow-worker                ClusterIP   None            <none>        8793/TCP            15m

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/airflow-scheduler   0/1     1            0           15m
deployment.apps/airflow-statsd      0/1     1            0           15m
deployment.apps/airflow-triggerer   0/1     1            0           15m
deployment.apps/airflow-webserver   0/1     1            0           15m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/airflow-scheduler-588cbbf87f   1         1         0       15m
replicaset.apps/airflow-statsd-58d7f8d864      1         1         0       15m
replicaset.apps/airflow-triggerer-6cc749dbb4   1         1         0       15m
replicaset.apps/airflow-webserver-747bffcccd   1         1         0       15m

NAME                                  READY   AGE
statefulset.apps/airflow-postgresql   1/1     15m
statefulset.apps/airflow-redis        0/1     15m
statefulset.apps/airflow-worker       0/1     15m

NAME                                       COMPLETIONS   DURATION   AGE
job.batch/airflow-run-airflow-migrations   0/1           15m        15m
```

I am not able to check logs for the JOB pod, it returns (example) ::
`Error from server (NotFound): the server could not find the requested resource ( pods/log airflow-run-airflow-migrations-5j9qc)`

the only thing I was able to collect is from namespace events, smthg like that :: 
`5m18s       Warning   FailedMount              pod/airflow-statsd-58d7f8d864-qs2rt               MountVolume.SetUp failed for volume "airflow-statsd-token-8tsdg" : secret "airflow-statsd-token-8tsdg" not found`

sometimes its a token for statsd, more often I met similar one for the `webserver` component etc
and, indeed, the `airflow-statsd-token` ends up having different name. as in the recent deploy attempt that would be
`airflow-statsd-token-smthb` not `-8tsdg`
is there a way to control this behavior via Values [`--set in our current case/setup`]? what "suddenly" began causing it. since the recent successful deploys we only changed couple DAGs

we made some backups and, at some point, fully removed every cluster object for airflow helm Release and the namespace itself. pv included. no crd's here as far as I know(some OPS wouldve been mentioned and required during install etc, right). still the same

btw: when it hangs in a state like that, several resources, beginning with a JOB require manual `delete --force` for a cleanup
regular `helm un airflow -n airflow` couldnt handle it

EDIT1 ::
just tried to use base IMG from hub.docker during install(fully cleaned NS again). still the same. so we may, apparently, exclude that from the "debug protocol"

someThoughts ::
since we're not pulling these secrets from like EXT source(say Vault or whatnot), their naming has to and may only be described in your templates, right? nor do we append anything during `--upgrade` phase. would that mean, that those suffixes come from some random go template in like your _helpers?(right, I'll go `helm pull` & `ack` them for some key strings, check in general. its just.. how much time would it take me to figure on my own). has to be smthg else.. I simply couldnt think of yet

EDIT2 ::
uh. what if this has been a wrong route. so, looking closer. I do have those `MountVolume.SetUp failed for volume .. secret $name not found` at the end of events like `k get events -n airflow --sort-by='.metadata.creationTimestamp'` . but: it may have been previous attempt, in the observing case, of creating the webserver POD. because current one, that is 0/1 and `Pending` has `-zq4c4` suffix [final MSGs in events report a different]. describing it returns:
`serviceAccount: airflow-webserver`
`serviceAccountName: airflow-webserver`
volumes.name: `airflow-webserver-token-dwftg`
& secretName: `airflow-webserver-token-dwftg`
describe of the SA tells me:
secrets.name: `airflow-webserver-token-dwftg` as well
and that one actually exists now with:
metadata.annotations.kubernetes.io/service-account.name: `airflow-webserver`
it sorta kinda checks out. so, mb the `job.batch/airflow-run-airflow-migrations` somehow simply fails every time now? and theres still no way I can check its POD logs
I saw someone "from a similar Issue" has been running install with `--debug --timeout 10m0s`. chances are that is gonna provide some more info then. checking soon

exec ::
```
helm upgrade -i airflow apache-airflow/airflow -n airflow --set images.airflow.pullPolicy=Always --set nodeSelector."kubernetes\\.io/hostname"=$node --set fernetKey="$sens" --set workers.persistence.size=30Gi --create-namespace --wait=false --debug --timeout 10m0s
```

returns to console ::
```
history.go:56: [debug] getting history for release airflow
Release "airflow" does not exist. Installing it now.
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: $home/Library/Caches/helm/repository/airflow-1.6.0.tgz

client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airflow-broker-url" Secret
client.go:339: [debug] secrets "airflow-broker-url" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airflow-fernet-key" Secret
client.go:339: [debug] secrets "airflow-fernet-key" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airflow-redis-password" Secret
client.go:339: [debug] secrets "airflow-redis-password" not found
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 30 resource(s)
client.go:310: [debug] Starting delete for "airflow-run-airflow-migrations" Job
client.go:339: [debug] jobs.batch "airflow-run-airflow-migrations" not found
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Job airflow-run-airflow-migrations with timeout of 10m0s
client.go:568: [debug] Add/Modify event for airflow-run-airflow-migrations: ADDED
client.go:607: [debug] airflow-run-airflow-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for airflow-run-airflow-migrations: MODIFIED
client.go:607: [debug] airflow-run-airflow-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
```

same cluster state, nothing else happened during these 10m ;(

at some point reduced `-upgrade` to simply:
`helm upgrade -i airflow apache-airflow/airflow -n airflow --create-namespace`
thus: base IMG:latest & the most basic install. result: the same 🤷 

finally been able to retrieve `airflow-run-airflow-migrations` POD logs. possibly have a clue as to why, but to not mislead anyone, keep for now. yet, there are only dots. still require some assistance 🙏 
node cont runtime :: `cri-o://1.20.7`
STORAGECLASS :: `longhorn`
not sure what other info could be of use

### What you think should happen instead

everything gets deployed w/o any errors thrown

### How to reproduce

based on the Dockerfile & helm upgrade string I provided, probably

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
Does this work?

```
helm upgrade --install airflow apache-airflow/airflow
```

If so, slowly add stuff in until it doesn't. That might help us narrow down what's going wrong and/or let me reproduce it.

**Comment by eeluve** [comment]
it still doesn't work

**Comment by jedcunningham** [comment]
Something cluster related seems likely. When you describe any of the pending pods, normally you'll see why in the events. In the OP I had a bit of trouble determining if it was because of a volume or the statsd secret?

For postgres, we use the bitnami postgres chart as a subchat. `postgres.primary.nodeSelector` should work, though I haven't actually tried it.
https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values&path=primary.nodeSelector

You could also try to reproduce with [kind](https://kind.sigs.k8s.io/). (It should definitely work there)

**Comment by eeluve** [comment]
thanks, checking `postgres.primary.nodeSelector`. I'll update this

**Comment by jedcunningham** [comment]
Sorry, I went from memory and got it wrong, it'd be `postgresql.primary.nodeSelector`!

**Comment by eeluve** [comment]
❤️ thanks man solved
also, a note: I'll quite likely kill my colleague, that I pinged 5 hours ago about whether this cluster is fine
lets just think of this as some nice experience
