### ISSUE TITLE
`POST /taskInstances/list` with wildcards returns unhelpful error

### ISSUE THREAD

**Issue by fritz-astronomer** [apache/airflow#26424]
### Apache Airflow version

2.3.4

### What happened

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch
fails with an error with wildcards while
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances 
succeeds with wildcards

Error:
```
400
"None is not of type 'object'"
```

### How to reproduce

1) `astro dev init`
2) `astro dev start`
3) `test1.py` and `python test1.py`
```
import requests
host = "http://localhost:8080/api/v1"
kwargs = {
    'auth': ('admin', 'admin'),
    'headers': {'content-type': 'application/json'}
}
r = requests.post(f'{host}/dags/~/dagRuns/~/taskInstances/list', **kwargs, timeout=10)
print(r.url, r.text)
```

output
```
http://localhost:8080/api/v1/dags/~/dagRuns/~/taskInstances/list 
{
  "detail": "None is not of type 'object'",
  "status": 400,
  "title": "Bad Request",
  "type": "http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html#section/Errors/BadRequest"
}
```

3) `test2.py` and `python test2.py`
```
import requests
host = "http://localhost:8080/api/v1"
kwargs = {
    'auth': ('admin', 'admin'),
    'headers': {'content-type': 'application/json'}
}
r = requests.get(f'{host}/dags/~/dagRuns/~/taskInstances', **kwargs, timeout=10)  # change here
print(r.url, r.text)
```
```
<correct output>
```

### Operating System

Debian

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dstandish** [comment]
it probably does not make sense to support wildcards on the batch (i.e. POST) endpoint, because wildcards can be handled by the normal, non-batch version.  batch's stated pupose is for when you have too many dag_ids for the GET request.  so, since it doesn't work now anyway, probably best solution here is to raise 404 / some helpful message suggesting to use the get endpoint.   or... could just fix it and support it 🤷

**Comment by chenglongyan** [comment]
@fritz-astronomer,  The POST parameter data cannot be None

```python
import requests
host = "http://localhost:8080/api/v1"
kwargs = {
    'auth': ('admin', 'admin'),
    'data':'{}',  
    'headers': {'content-type': 'application/json'}
}
r = requests.post(f'{host}/dags/~/dagRuns/~/taskInstances/list', **kwargs, timeout=10)
print(r.url, r.text)
```

**Comment by fritz-astronomer** [comment]
Oh, @chenglongyan - thanks. That makes a lot of sense 😞 
Maybe this can just be a more helpful error message on that route saying that a data payload is required
current message
```
  "detail": "None is not of type 'object'",
```
vs 
```
  "detail": "POST Body must not be None",
```

**Comment by potiuk** [comment]
> Oh, @chenglongyan - thanks. That makes a lot of sense 😞 Maybe this can just be a more helpful error message on that route saying that a data payload is required current message
> 
> ```
>   "detail": "None is not of type 'object'",
> ```
> 
> vs
> 
> ```
>   "detail": "POST Body must not be None",
> ```

Good idea :). Maybe you would like to contribute a fix for that :) ?

**Comment by dstandish** [comment]
or maybe the API can be made to handle None?

**Comment by maheshsv** [comment]
i will work on this issue , can you please assign it to me

**Comment by maahir22** [comment]
@eladkal I'd like to work on this issue, please /assign.

**Comment by maahir22** [comment]
@eladkal @potiuk I've allowed the Request Payload to be nullable and then checked it later before JSON is parsed to allow custom error. Let me know if it seems fine.
