### ISSUE TITLE
can't have different DAGS_FOLDER between scheduler and worker

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#26440]
### Apache Airflow version

2.4.0b1

### What happened

tried to run something with virtualenv scheduler and kube exec and task failed to run as a result of this

### Operating System

official docker image

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hterik** [comment]
I think this got fixed in 2.4.2 by https://github.com/apache/airflow/pull/26509

**Comment by potiuk** [comment]
Oh yeah.
