### ISSUE TITLE
Do not mount DAG folder to scheduler in "standalone dag processor" mode in Chart

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#26474]
### Description

I believe with "standalone dag processor" completed in 2.4, Scheduler should not need a DAG folder to be mounted? 

Should we disable the mount it in the helm chart in "standalone dag processor" mode similarly as we do for webserver in all cases?

### Use case/motivation

Additional layer of security of the Scheduler - which would not have to have access to DAG code .

### Related issues

Dicussed in https://github.com/apache/airflow/issues/26008#issuecomment-1248947543

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc: @jedcunningham @ashb @mhenc @ephraimbuddy -> do you think of any reason why Scheduler in standalone dag processor mode would need DAG code? I can't think of any, but maybe I forgot about somethig so I raised the issue (and happy to implement it before we release the new chart) - but I wanted to get your feedback on it.

**Comment by mhenc** [comment]
No, I hope not - that was the whole idea of DagProcessor separation - to make Scheduler "trusted component" that runs without any iteracation with user code.
If there is still any dependency required, then we should fix it.

**Comment by jedcunningham** [comment]
This was already done in #23711, or am I overlooking something?

**Comment by potiuk** [comment]
Nope. you did not. It's I who overlooked it.  :facepalm:
