### ISSUE TITLE
Cannot fetch log from Celery worker

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#26492]
### Discussed in https://github.com/apache/airflow/discussions/26490

<div type='discussions-op-text'>

<sup>Originally posted by **emredjan** September 19, 2022</sup>
### Apache Airflow version

2.4.0

### What happened

When running tasks on a remote celery worker, webserver fails to fetch logs from the machine, giving a '403 - Forbidden' error on version 2.4.0. This behavior does not happen on 2.3.3, where the remote logs are retrieved and displayed successfully.
The `webserver / secret_key` configuration is the same in all nodes (the config files are synced), and their time is synchronized using a central NTP server, making the solution in the warning message not applicable.

My limited analysis pointed to the `serve_logs.py` file, and the flask request object that's passed to it, but couldn't find the root cause.

### What you think should happen instead

It should fetch and show remote celery worker logs on the webserver UI correctly, as it did in previous versions.

### How to reproduce

Use airflow version 2.4.0
Use CeleryExecutor with RabbitMQ
Use a separate Celery worker machine
Run a dag/task on the remote worker
Try to display task log on the web UI

### Operating System

Red Hat Enterprise Linux 8.6 (Ootpa)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-common-sql==1.1.0
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-hashicorp==3.0.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-microsoft-mssql==3.0.0
apache-airflow-providers-mysql==3.0.0
apache-airflow-providers-odbc==3.0.0
apache-airflow-providers-sftp==3.0.0
apache-airflow-providers-sqlite==3.0.0
apache-airflow-providers-ssh==3.0.0
```

### Deployment

Virtualenv installation

### Deployment details

Using CeleryExecutor / rabbitmq with 2 servers

### Anything else

All remote task executions has the same problem.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by potiuk** [comment]
From the discussion:

Sorry if not clear, but this already happened in 2.4.0, which I installed today (It was fine on 2.3.3 and before).
Running on Python 3.10.5.

This is the message from the web UI:

![image](https://user-images.githubusercontent.com/389091/191034865-84bfef74-7639-45ce-9338-d51b9f80deac.png)

This is the relevant log from the remote celery worker when the web UI requests the task log:

```
Sep 19 15:55:05 airflow[3734318]: [2022-09-19 15:55:05,027: INFO/ForkPoolWorker-15] Task airflow.executors.celery_executor.execute_command[af1dec61-b437-4605-980c-de2d65f60bd7] succeeded in 0.9207695280201733s: None
Sep 19 15:55:11 airflow[3734281]: [2022-09-19 15:55:11,177] {serve_logs.py:104} WARNING - Unknown error
Sep 19 15:55:11 airflow[3734281]: Traceback (most recent call last):
Sep 19 15:55:11 airflow[3734281]:   File "/data/apps/.pyenv/versions/3.10.5/envs/airflow-py310/lib/python3.10/site-packages/airflow/utils/serve_logs.py", line 64, in validate_pre_signed_url
Sep 19 15:55:11 airflow[3734281]:     request_filename = request.view_args['filename']
Sep 19 15:55:11 airflow[3734281]: TypeError: 'NoneType' object is not subscriptable
```

Looks like the `request.view_args` is `None` in the validation function. Don't know whether it's the root cause though.

Do you need any additional logs?

**Comment by potiuk** [comment]
Ah sorry - my mistake @emredjan . Looking into it.

**Comment by potiuk** [comment]
Are you sure you also restarted webserver

**Comment by sakutepov** [comment]
I have the same problem
The container works on the same machine, but not on different hosts

**Comment by potiuk** [comment]
I reproduced it and I think I have a fix - unfortunately it's not easily workaroundable I am afraid (If I got the right root cause)

**Comment by potiuk** [comment]
So we will need 2.4.1 sooon

**Comment by potiuk** [comment]
(And I think its me who caused it :( )

**Comment by emredjan** [comment]
I'm happy to modify installed files (`serve_logs.py`, `file_task_handler.py`, etc.) for testing, if it's that's simple of course.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/pull/26493 contains the fix - one `/` needs to be added.

**Comment by potiuk** [comment]
@emredjan - it should be changed on the webserver (so it's not serve_logs.py that is guilty but file_task_handler.py on the webserver side.

**Comment by emredjan** [comment]
Perfect, I confirm this indeed fixes the issue. Thanks for the swift help @potiuk !

**Comment by potiuk** [comment]
Would be great if it wasn't there in the first place :( .Thanks for confirming!

**Comment by Financeit-kli** [comment]
Hi @potiuk , I ran into this error on 2.4.3. The env I'm using is directly from the official docker compose file from [here](https://airflow.apache.org/docs/apache-airflow/2.4.3/docker-compose.yaml). 
The way to reproduce it is to create and run a simple dag and check the log from UI.
Thanks for looking into it.

**Comment by potiuk** [comment]
> Hi @potiuk , I ran into this error on 2.4.3. The env I'm using is directly from the official docker compose file from [here](https://airflow.apache.org/docs/apache-airflow/2.4.3/docker-compose.yaml).
The way to reproduce it is to create and run a simple dag and check the log from UI.
Thanks for looking into it.

Just to clarify ut - the docker compose is NOT official compose. It's a quick-start docker compose that can get you up an running but if you have anu problems with it (in your environment) you should apply your docker compose expertise to be able to analyse it, I am afraid (and this is very clearly written [here](https://airflow.apache.org/docs/apache-airflow/2.4.3/howto/docker-compose/index.html) as "Caution".

> This procedure can be useful for learning and exploration. However, adapting it for use in real-world situations can be complicated. Making changes to this procedure will require specialized expertise in Docker & Docker Compose, and the Airflow community may not be able to help you.

> For that reason, we recommend using Kubernetes with the [Official Airflow Community Helm Chart](https://airflow.apache.org/docs/helm-chart/stable/index.html) when you are ready to run Airflow in production.

I just followed (again as a million times before) all the steps one-by-one from our quick-start and unfortunately I cannot reproduce your problem. This is what I get. 

<img width="2021" alt="Screenshot 2022-11-28 at 22 23 02" src="https://user-images.githubusercontent.com/595491/204383801-b210587c-a073-4a99-9032-7be2c8354f5d.png">

So NO. It's not easily reproducible. You have to do better.

Docker compose functionality depends on many local factors. This is one of the reasons why we do not recommend people who are not already experts in docker compose to use it - there is a learning curve involved and unfortunately when someone has expectations that things will "just work", they are gravely mistaken. You need to dive deep and understand a lot that happens under the hood in order to actually run anything (not only airflow) in docker compose. And we just warned you that you need to do a lot of investigations on your own - and provide useful information if you want help. Writing "it does not work for me" is not a useful information that will help those who want to help in their free time (because this is what is happening here - I am responding to you in my free time). But you give me little chance to help me without spending your own time first.
 
If you want any help for your case where likely you have some misconfiguration of some sort. We are not ablet to magically guess with your docker, docker-compose configuration unfortunately - and if you really need some help with solving your problem
