### ISSUE TITLE
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

### ISSUE THREAD

**Issue by jakemraz** [apache/airflow#26514]
### Apache Airflow version

Other Airflow 2 version

### What happened

when I installed the airflow 2.1.4 with the constraints-3.8 using below command

pip install "apache-airflow[celery]==2.1.4" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.1.4/constraints-3.8.txt"

it returns the error
"ERROR: launchpadlib 1.10.13 requires testresources, which is not installed."

so, I installed testresources with the command of "pip install testresources"
after that the installation was finished.

I think [constrains-3.8.txt](https://raw.githubusercontent.com/apache/airflow/constraints-2.1.4/constraints-3.8.txt) should contains testresources package information.

please consider.

### What you think should happen instead

successfully installed

### How to reproduce

pip install "apache-airflow[celery]==2.1.4" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.1.4/constraints-3.8.txt"

### Operating System

Ubuntu 20.04.5 LTS

### Versions of Apache Airflow Providers

2.1.4

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is quite a misunderstanding how constraints and airflow installation works.

You are mixing constraints with requirements. Contrary to constraints work in the way that IF you install some requirement already, it will be installed in the version you specified. 

Also meither launchpadlib, nor testresources are Ailrflow requirements and you always have to install them separately from airlfow. Airlfow nor airlfow constraints nor airlfow requirements have anything to do with it. 

It's completely on your side to install both.

**Comment by lukalafaye** [comment]
Try `sudo apt install python3-testresources`  (python3) or `sudo apt install python-testresources` (python2).
