### ISSUE TITLE
Airflow 2.4 Inline Task Logs Should Default to Most Recent Task Try

### ISSUE THREAD

**Issue by fritz-astronomer** [apache/airflow#26545]
### Description

I noticed with the new inline task logs view in Airflow 2.4 - the default is to go to the 1st task attempt log, rather than the most recent, which is not the behavior of the prior task logs view. 

I think it's a good default to go to the most recent

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
> I think it's a good default to go to the most recent

oh yeah.
I change this to a bug report because this is not really a feature. This is how logs used to work before

**Comment by tirkarthi** [comment]
There were some changes done in below commit where `useState` which always used zero now has a different logic. I have a question where if there are two task instances with 2 and 3 attempts respectively. User selects task-instance-1 and attempt 1 in log UI. Now user navigates to task-instance-2. Should the user have attempt 3 (latest) or attempt 1 (selected in task-instance-1) displayed?

https://github.com/apache/airflow/pull/26556/files#diff-69e2a778c59cc3ec6dbaeb666f063da6a144596d15034db3291bc6066586074eL102

cc: @bbovenzi

**Comment by bbovenzi** [comment]
We fixed this issue in: https://github.com/apache/airflow/pull/26556

@tirkarthi We try to maintain the selection manually done by the user. But if a task doesnt have that try number, we will reset to the latest.

**Comment by tirkarthi** [comment]
Got it. Thanks @bbovenzi .
