### ISSUE TITLE
Enabling and Disabling the Task Before the DAG Run From UI and API 

### ISSUE THREAD

**Issue by Amar1404** [apache/airflow#26590]
### Description

Enabling and Disabling the task for the particular DAG from the UI and API. or using the parameter that disable it. This was it is easy to disable a particular task easily while running manually or schedule. The UI gives us the feature to select the task to disable it before triggering it manually

### Use case/motivation

So  for the backfill or running manually in a DAG if we don't want to run a particular task we can disable it, from UI and in the next schedule the particular task will not run. That way we don't have to remove the code for the task.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think this one will be hard to implement and it is not something we really want to do. Tasks have dependencies to other tasks, and it might get tricky to decide what to do when one or more tasks are disabled. 

But I wonder what others think,
