### ISSUE TITLE
Google Cloud Batch Jobs Hooks, Operators & Sensors

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#26600]
### Description

[Batch Jobs](https://cloud.google.com/batch) were just introduced. They're still in "preview" and only avail in certain regions. But it will be great to support this from GA day 1.

### Use case/motivation

Batch jobs are a very very good alternative to `KubernetesPodOperator` functionality. Fewer configuration, fewer overhead both in the Data Engineers and for the DevOps maintaining the solution.

Also a good solution to decouple orchestration from execution, rather than using —for example— Cloud Build (GCP).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhirsz** [comment]
Thank you, I will pass it to the team that is working on increasing the coverage of the Google Cloud services in the Airflow. Just a note that the service needs a python SDK (ideally) or API, and lack of those can postpone support in the Airflow. And of course since it's open source it can be added by anyone, any contribution is welcome :)

**Comment by dinigo** [comment]
There's both, a REST and gRPC API, and also a [python library](https://github.com/googleapis/python-batch)

**Comment by Yaro1** [comment]
please assign to me

**Comment by msaad7777** [comment]
Hello! I was wondering if this issue is currently assigned to anyone? If not, I would be interested in taking it on and submitting a PR to address it. Please let me know if it is available to be assigned or if there are any other steps I need to take to get started on this. Thank you!

**Comment by potiuk** [comment]
> Hello! I was wondering if this issue is currently assigned to anyone? If not, I would be interested in taking it on and submitting a PR to address it. Please let me know if it is available to be assigned or if there are any other steps I need to take to get started on this. Thank you!

You need to talk to @Yaro1 and find out if the work started there is going to be continued (as you can clearly see in the issue - there is a PR in progress) .

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/32606
