### ISSUE TITLE
The "Filter DAGs by tag" UI component doesn't wrap correctly

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#26610]
### Apache Airflow version

2.4.0

### What happened

* case 1: the half-hidden tag is "test"
![2022-09-22_15-24_1](https://user-images.githubusercontent.com/14293802/191855005-d1a11547-7dbb-491f-a8f4-aaaa138907fe.png)

* case 2: the half-hidden tag is "conversion"
![2022-09-22_17-35](https://user-images.githubusercontent.com/14293802/191855822-74b680be-01b5-47f6-89d7-b291282ee66a.png)

* case 3: a successful case probably because the 3rd tag is long
![2022-09-22_17-36](https://user-images.githubusercontent.com/14293802/191855837-42362a81-cb78-4c7b-8b41-b96975951663.png)

### How to reproduce

Depending on the tags you have, just go to the main UI and start selecting tags in the "Filter DAGs by tag" field.

### Operating System

Linux Mint 20.3 Una

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by alvaroqueiroz** [comment]
this does not seem to be a problem on the newer versions anymore
