### ISSUE TITLE
Airflow webserver: make success button should show a scrollable pop-up of tasks

### ISSUE THREAD

**Issue by vqcuong** [apache/airflow#26622]
### Apache Airflow version

2.3.4 and 2.4.0

### What happened

I have a dag with more task in it. When I click on "make success" button for a dag run on DAG ui and the pop-up shows, but I can't scroll down to see "confirm" or "cancel" buttons at the end of it. The below images will illustrate this issue clearer
<img width="1440" alt="Screen Shot 2022-09-23 at 15 15 25" src="https://user-images.githubusercontent.com/35632030/191919321-282fca5d-3632-4a7f-82a7-93e608a0708a.png">
<img width="1440" alt="Screen Shot 2022-09-23 at 15 17 24" src="https://user-images.githubusercontent.com/35632030/191919336-02f8ea13-d2b7-497e-8a25-4e56a1ca8685.png">

### What you think should happen instead

I think this pop-up should enable scroll to prevent this issue

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Docker-Compose

### Deployment details

I using an official docker-compose on airflow github to deploy

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Thank you for reporting this issue.

Indeed it looks like the overflow is not properly handled for the dialog component. (On chrome I can scroll the modal content by playing around but it definitely feels buggy).

Maybe we could have a maxHeight ~90% of the vertical space, and add a scrollbar to the task instances list :thinking: ?  (cf screenshot)

Would be glad to review a PR for this. @vqcuong, do you want to take this one ?
![image](https://user-images.githubusercontent.com/14861206/192110550-293a8c39-1023-43f1-a419-d635dbe451c7.png)

**Comment by vqcuong** [comment]
Hi @pierrejeambrun, sorry for my bad. I have found an issue from my deployment solution. Thank for help me.

**Comment by pierrejeambrun** [comment]
@vqcuong how did you solve this ? Wondering if we should still make this change
