### ISSUE TITLE
Importing DummyOperator is not detected as an error

### ISSUE THREAD

**Issue by esoyer** [apache/airflow#26630]
### Apache Airflow version

2.4.0

### What happened

After having upgraded our Airflow from 2.3.4 to 2.4.0, we observed that the DummyOperator was deleted (by the way, the release note does not talk about this at all). 

We ran our tests which check that the import_errors from our dag bag is an empty map, and the tests were passing even though the imports of DummyOperator were still there in the DAG python files. 

The test looks like something like this:

```
dagbag = DagBag(include_examples=False)
assert dagbag.import_errors == {}
```

### What you think should happen instead

We were expecting the test to fail since we are importing an Operator which does not exist anymore.

### How to reproduce

Upgrade to Airflow 2.4.0 and import the `DummyOperator` in one of your DAG python file. Run a test which checks that the `import_errors` from your Dag Bag containing your DAG with the wrong import is empty. It should pass even though the import is invalid.

### Operating System

MacOS Monterey Version 12.5

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
The `DummyOperator` was deprecated.
You can still use it.
see :
https://github.com/apache/airflow/blob/55d11464c047d2e74f34cdde75d90b633a231df2/airflow/operators/__init__.py#L51

We just replaced it  with PEP-562 dynamic attribute loading.
