### ISSUE TITLE
apache-airflow-providers-atlassian-jira Not in PyPi Repository

### ISSUE THREAD

**Issue by BusinessGoose001** [apache/airflow#26638]
### Apache Airflow Provider(s)

atlassian-jira

### Versions of Apache Airflow Providers

attempting to use any version (latest)(1.0.0)

### Apache Airflow version

2.3.0

### Operating System

Linux Mint

### Deployment

Docker-Compose

### Deployment details

package install section 
`RUN python3 -m pip install --upgrade pip`
`RUN pip install JIRA`
`RUN pip install 'apache-airflow-providers-atlassian-jira'`

### What happened

Was trying to install the package `apache-airflow-providers-atlassian-jira` into the docker container and was getting the following error
`ERROR: Could not find a version that satisfies the requirement apache-airflow-providers-atlassian-jira (from versions: none)
ERROR: No matching distribution found for apache-airflow-providers-atlassian-jira`

upon looking into this we found the docs page here https://airflow.apache.org/docs/apache-airflow-providers/packages-ref.html#apache-airflow-providers-atlassian-jira
but when you click the link to go to the PyPi package there is no such package found
https://pypi.org/project/apache-airflow-providers-atlassian-jira/

### What you think should happen instead

the package should exist in PyPi

### How to reproduce

`RUN python3 -m pip install --upgrade pip`
`RUN pip install 'apache-airflow-providers-atlassian-jira'`

### Anything else

This problem occurs every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sardelorme** [comment]
I am also having this issue. I have not been able to find anyone else posting about this - thanks for making the issue. Hopefully, a solution can be reached promptly.

**Comment by eladkal** [comment]
the provider wasn't released yet
