### ISSUE TITLE
Cleanup Job Pods host remove history after completing the job

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#26709]
We currently do not have possibility of confioguring:

* spec.successfulJobsHistoryLimit
* spec.failedJobsHistoryLimit

For cleanup jobs. Creaeted it to add a feature for that.

### Discussed in https://github.com/apache/airflow/discussions/26547

<div type='discussions-op-text'>

<sup>Originally posted by **alionar** September 21, 2022</sup>
<img width="919" alt="Screen Shot 2022-09-21 at 10 36 29" src="https://user-images.githubusercontent.com/18596757/191408780-fa3e0aba-2faf-45d2-b0ca-6c8c8db458d2.png">

Airflow Version: 2.2.2
Kubernetes Version: 1.22.12-gke.500
Helm Chart version: 1.6.0

Hi, i found that completed cleanup job pods just stayed in nodes after finished and make GKE auto scaller triggered to add new nodes everytime cleanup job pods executed.

It made us to delete all completed job pods and drain the unused nodes manually everyday.

I found in k8s docs that:
```
The .spec.successfulJobsHistoryLimit and .spec.failedJobsHistoryLimit fields are optional. 
These fields specify how many completed and failed jobs should be kept. 
By default, they are set to 3 and 1 respectively
```

But when i tried to add this history limit as 0 into cleanup helm chart value, chart didn't recognize it
![Screen Shot 2022-09-21 at 10 40 19](https://user-images.githubusercontent.com/18596757/191409229-ff2336df-c417-4e70-b9cd-f837b053f3b5.png)

is that possible to add some job history limit number in cleanup value chart?

Current values.yaml for cleanup:
```
cleanup:
  enabled: true
  schedule: "*/15 * * * *"
```

</div>

**Comment by MatthieuBlais** [comment]
I can work on that
