### ISSUE TITLE
Refactor `S3KeysUnchangedSensor` system test

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#26725]
S3KeysUnchangedSensor doesn't work well with DebugExecutor which causes issues for system tests.

Spawn of _Originally posted by @eladkal in https://github.com/apache/airflow/pull/26606#discussion_r978103055_

**Comment by suselunarwolf** [comment]
HI can i work on this ..is issue is still open

**Comment by o-nikolas** [comment]
Hey @suselunarwolf
Sorry we hadn't gotten back sooner! I've assigned this task to you :)

**Comment by eladkal** [comment]
@vandonr-amz Now that https://github.com/apache/airflow/pull/28528 is this issue still valid?

https://github.com/apache/airflow/blob/9ab1a6a3e70b32a3cddddf0adede5d2f3f7e29ea/tests/system/providers/amazon/aws/example_s3.py#L205-L209

**Comment by o-nikolas** [comment]
I looked more deeply into this issue. There actually isn’t a small bug fix here. It’s a fundamental conflict between how the sensor in question works (which is stateful, it needs to keep track of the current keys to compare against future keys in each poke, and in reschedule mode there is no way to do this (cleanly)) and how the debug executor works (which is single threaded and must use reschedule mode for sensors). I think the best course of action is to invest in teaching the Airflow system test mechanism to use other executors than the DebugExecutor. This will solve this problem and allow us to get test coverage for other new executors (ECS executor for an example). But that will be a much bigger task.

CC: @shubham22
