### ISSUE TITLE
OFFICAL Documentation page gives ERROR and not loads in -  Not Found  The requested URL was not found on this server.

### ISSUE THREAD

**Issue by stromal** [apache/airflow#26777]
### What do you see as an issue?

https://airflow.apache.org/docs/apache-airflow/2.3.3/howto/docker-compose/index.html

ERROR:
- Not Found
- The requested URL was not found on this server.

### Solving the problem

Get aback the page it was fine yesterday

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This is not a bug. This doc exist only for >=2.4.0
It was updated in https://github.com/apache/airflow/pull/25888
You are probably looking for:
https://airflow.apache.org/docs/apache-airflow/2.3.3/start/docker.html#customizing-the-quick-start-docker-compose

Please do not use deep links between versions. Docs are constantly changing.
Use the search option in the docs main page to find what you are looking for in a specific version.
