### ISSUE TITLE
Incorrect await_container_completion in KubernetesPodOperator

### ISSUE THREAD

**Issue by windmark** [apache/airflow#26796]
### Apache Airflow version

2.3.4

### What happened

The [await_container_completion](
https://github.com/apache/airflow/blob/2.4.0/airflow/providers/cncf/kubernetes/utils/pod_manager.py#L259) function has a negated condition

```
while not self.container_is_running(pod=pod, container_name=container_name):
```
that causes our Airflow tasks running <1 s to never be completed, causing an infinite loop. 

I see this was addressed and released in https://github.com/apache/airflow/pull/23883, but later reverted in https://github.com/apache/airflow/pull/24474. How come it was reverted? The thread on that revert PR with comments from @jedcunningham and @potiuk didn't really address why the fix was reverted.

### What you think should happen instead

Pods finishing within 1s should be properly handled.

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==4.3.0

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
It caused failure of tests and we were unable to point the source so we had to revert
https://github.com/apache/airflow/pull/24479

https://apache-airflow.slack.com/archives/CCPRP7943/p1655306336391429
https://apache-airflow.slack.com/archives/CCPRP7943/p1655300699968739

Quoting Ash from slack:
> That'll learn us for merging a bug fix without any new tests  

Feel free to raise PR with tests :)

**Comment by windmark** [comment]
> It caused failure of tests and we were unable to point the source so we had to revert #24479
> 
> https://apache-airflow.slack.com/archives/CCPRP7943/p1655306336391429 https://apache-airflow.slack.com/archives/CCPRP7943/p1655300699968739
> 
> Quoting Ash from slack:
> 
> > That'll learn us for merging a bug fix without any new tests
> 
> Feel free to raise PR with tests :)

I see, thanks for the links. Though it's quite a severe bug if the condition incorrectly is negated when waiting for completed pods. Let me read up on the threads.
