### ISSUE TITLE
ExternalTaskSensor with execution_delta not correctly running

### ISSUE THREAD

**Issue by pharoson** [apache/airflow#268]
I'm using an ExternalTaskSensor with the execution_delta parameter to coordinate between a daily DAG and an hourly DAG (daily depends on hourly). The daily runs at 1:00 and the hourly runs at x:10. 

It hasn't run a scheduled instance (it will run later tonight), so I ran it manually via the run command. 

I have the daily workflow set to depend on the hourly run 110 minutes earlier (23:10 in this case). Although Airflow reports it was successful, the log files report the wrong time when poking for the task instance. It reports that the `2015-08-17 01:00:00` was successful, not the `2015-08-16 23:10:00`.

Relevant code and log files are below. If the normal scheduled run has correct logs, I'll close the issue. Thanks! 

Daily DAG definition: 

```
default_args = {
    ...
    'start_date': datetime(2015, 8, 11, 1),
    ...
    'schedule_interval': timedelta(days=1),
}

dag = DAG('check_for_missing_logs', default_args=default_args, schedule_interval=timedelta(days=1))
...
ext_dep = ExternalTaskSensor(
    external_dag_id='hourly_logs',
    external_task_id='end_of_logs', # end_of_logs is a DummyOperator that depends on all other tasks
    execution_delta=timedelta(minutes=110),
    task_id='hourly_logs_sensor',
    dag=dag)
```

Hourly DAG definition: 

```
default_args = {
    ...
    'start_date': datetime(2015, 8, 10, 0, 10),
    ...
    'schedule_interval': timedelta(hours=1),
}

dag = DAG('hourly_logs', default_args=default_args, schedule_interval=timedelta(hours=1))
```

Logs files from ExternalTaskSensor in Daily DAG: 

```
--------------------------------------------------------------------------------
New run starting @2015-08-18T17:05:33.597081
--------------------------------------------------------------------------------
[2015-08-18 17:05:33,619] {models.py:826} INFO - Executing <Task(ExternalTaskSensor): hourly_logs_sensor> on 2015-08-17 01:00:00
[2015-08-18 17:05:33,621] {sensors.py:139} INFO - Poking for hourly_logs.end_of_logs on 2015-08-17 01:00:00 ... 
[2015-08-18 17:05:33,648] {sensors.py:57} INFO - Success criteria met. Exiting.
```

**Comment by pharoson** [comment]
The ExternalTaskSensor did not actually work last night. 

Is there anything I am defining incorrectly?

**Comment by mistercrunch** [comment]
The log should be clear about what it is poking for, seem like it's a simple issue around how time and delta are aligned isn't it?

**Comment by mistercrunch** [comment]
Reopen if the log says it's poking for something that does exist and is stuck, or if it's not poking where you set it up to poke.

**Comment by hilaviz** [comment]
Hi pharoson,
Did you manage to use ExternalTaskSensor?
I am new to airflow and trying to implement daily dag that depends on hourly dag,
didn't find any other documentation for implement the dag's dependency that actually works with airflow scheduler.
Thanks!

**Comment by r39132** [comment]
@hilaviz Please open a [Jira issue](https://issues.apache.org/jira/browse/AIRFLOW/) as we are migrating off Github Issues and place a pointer here (assign to me as well).  

I'd be happy to provide a working example for you there.

**Comment by hilaviz** [comment]
Hi,
Thank you for your quick reply.
I am not sure that there is an issue with the operator, 
I assume that I am missing something in strat_date/schedule_interval/execution_delta parameters

**Comment by hilaviz** [comment]
https://issues.apache.org/jira/browse/AIRFLOW-47

thanks!
