### ISSUE TITLE
Backfill option to respect start_date/end_date

### ISSUE THREAD

**Issue by Gollum999** [apache/airflow#26851]
### Description

Add some option to `airflow dags backfill` to allow the DAG + Task `start_date`/`end_date` args to constrain which tasks are run by the backfill.

Alternatively, I think this is conceptually the same request: Add some way to allow scheduler "catchup" behavior to go back in time.

### Use case/motivation

I have a DAG that builds many datasets, and the list of datasets that are built changes over time.  Each dataset (and each corresponding task) has a `start_date` and possibly an `end_date` depending on when that dataset should logically exist.

I want to backfill a large range of dates, but in backfill mode Airflow will try to run tasks for dates that don't make sense (i.e. outside of that task's `start_date`/`end_date` range).  I want to be able to fill in only the tasks that were valid for each date in my date range.

As a workaround I have been doing something like the following in each of my tasks:
```
if not task.start_date <= data_interval_start <= task.end_date:
    raise AirflowSkipException
```
Which is obviously a bit silly since this should never happen under normal (non-backfill) circumstances.

### Related issues

* #14854

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think this is the question for DAG versioning . What you are trying to do is trying to have different versions of DAGs in different times. We are yet to implement DAG versioning https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning but it is neither decided how to do it, nor approved, nor implemented. 

I think once DAG versioning will be implemented, airlfow backfill will run as you describe, but essentially what you propose is subset of what dag versioning should have implemented and it won't be implemented in isolation. Closing this one as this is not a feature that will be implemented on its own.
