### ISSUE TITLE
logical_date<start_date causes Null DAGRun

### ISSUE THREAD

**Issue by frankbreetz** [apache/airflow#26865]
### Apache Airflow version

2.4.1

### What happened

When you trigger a DAG that has a logical date earlier then the DAGs start date. You get a successful DAG Runs, but none of the tasks run:
![image](https://user-images.githubusercontent.com/24467723/193884284-377e5694-64eb-4bce-af7c-c1bb3b9f3b0c.png)

### What you think should happen instead

All of the tasks in the DAGRun should execute with a logical date of the one supplied

### How to reproduce

- Have DAG with start_date of A
- Trigger DAG w/ Config, set logical_date before A 
- look at DAG Run state and notice none of the Tasks have run

### Operating System

Debian

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I think we should simply disallow triggering a DAG with logical date earlier than its start date instead.

**Comment by Poxxy** [comment]
Why is this not getting caught by `trigger_dag.py`? Lines 62-68:

`if dag.default_args and 'start_date' in dag.default_args:
        min_dag_start_date = dag.default_args["start_date"]
        if min_dag_start_date and execution_date < min_dag_start_date:
            raise ValueError(
                f"The execution_date [{execution_date.isoformat()}] should be >= start_date "
                f"[{min_dag_start_date.isoformat()}] from DAG's default_args"
            )`

**Comment by Soonmok** [comment]
Can I take this task?

**Comment by o-nikolas** [comment]
@eladkal @kaxil 
Can either of you assign this one to @Soonmok

**Comment by eladkal** [comment]
@Soonmok are you still working on this issue?

**Comment by Jax-dreamus** [comment]
Yes.  If it need to be in hurry, you can open this issue to everyone. 
It takes time to understand the code base for me because this is my first contribution on this project.

**Comment by Soonmok** [comment]
@eladkal  Yes.  
If it needs to be in hurry, you can open this issue to everyone. 
It takes time to understand the code base for me.

**Comment by eladkal** [comment]
No rush :) just checking.
if you have questions feel free to join [Slack Chat](https://github.com/apache/airflow#links) there are several support channels for contributors.

**Comment by Soonmok** [comment]
I made PR of this issue
https://github.com/apache/airflow/pull/28398

**Comment by Soonmok** [comment]
@frankbreetz Could you provide the sample dag code to reproduce this issue?
