### ISSUE TITLE
Auto-Refresh is broken in graph view 2.4.1

### ISSUE THREAD

**Issue by nicolamarangoni** [apache/airflow#26901]
### Apache Airflow version

2.4.1

### What happened

After starting a DAG, the auto-refresh works in the grid view but not in the graph view.

The top-right auto-refresh icon shows indefinitely that the page is refreshing but nothing happens.

It is necessary to refresh the whole page to show the current status.

### What you think should happen instead

The auto-refresh should work and show the current status of the tasks.

### How to reproduce

Start a DAG in version 2.4.1.

### Operating System

Alpine on Kubernetes

### Versions of Apache Airflow Providers

```
apache-airflow-providers-apache-hdfs==3.1.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-datadog==3.0.0
apache-airflow-providers-exasol==2.1.3
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-jenkins==3.0.0
apache-airflow-providers-microsoft-mssql==3.2.1
apache-airflow-providers-odbc==3.1.2
apache-airflow-providers-oracle==3.1.0
apache-airflow-providers-postgres==5.0.0
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-slack==5.1.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.2.0
```

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @pierrejeambrun

**Comment by joeknize-bc** [comment]
I'm also seeing this issue using "Astronomer Runtime 6.0.2 based on Airflow 2.4.1+astro.1"

**Comment by gasci** [comment]
Yes, I confirm that this bug exists for me, too.

**Comment by pierrejeambrun** [comment]
Just opened https://github.com/apache/airflow/pull/26926, thanks for reporting the issue.

**Comment by pierrejeambrun** [comment]
Should be solved now. Closing
