### ISSUE TITLE
Align TriggerDagRunOperator with logical date terminology

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#26916]
Spawn of https://github.com/apache/airflow/issues/19264

By the way, since [`execution_date` has been renamed to `logical_date`](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#faq-what-does-execution-date-mean), but `TriggerDagRunOperator` [still uses this nomenclature](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator), shouldn't this be changed? Like so:
* rename the `execution_date` parameter to `logical_date`
* using the `execution_date` parameter in this class would call `logical_date` for backward compatibility, after raising a deprecation warning

If this makes sense, I can create a new issue about it.

_Originally posted by @augusto-herrmann in https://github.com/apache/airflow/issues/19264#issuecomment-1233400217_

**Comment by frankcash** [comment]
@eladkal I wonder if `execution_date` is still valid due to the fact that the API call https://github.com/apache/airflow/blob/main/airflow/operators/trigger_dagrun.py#L136-L142 takes `execution_date` as a parameter.  https://github.com/apache/airflow/blob/main/airflow/api/common/trigger_dag.py#L31-L38

**Comment by eladkal** [comment]
We may need to allign other parts of the code

**Comment by augusto-herrmann** [comment]
I have just checked the documentation for Airflow 2.7.2 and the `TriggerDagRunOperator` [still has a parameter named `execution_date`](https://airflow.apache.org/docs/apache-airflow/2.7.2/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator) and does not have a parameter named `logical_date`.

So the issue still persists in current Airflow.
