### ISSUE TITLE
cannot import name 'JSONEncoder' from 'json' (/opt/airflow/plugins/xcom_backend/type_serializers/json.py)

### ISSUE THREAD

**Issue by WorksWellWithOthers** [apache/airflow#27014]
### Apache Airflow version

2.4.1

### What happened

```
File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/proto_json_utils.py", line 5, in <module>
    from json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'json' (/opt/airflow/plugins/xcom_backend/type_serializers/json.py)
```

### Operating System

Linux

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sethmenghi** [comment]
I am getting the same issue in 2.4.0

**Comment by o-nikolas** [comment]
Thanks for helping out @sethmenghi. Since this is not an airflow issue, rather an issue with the architecture of the user's xcom backend plugin I'm closing this issue. @WorksWellWithOthers  please re-open if you think there is some issue with Airflow.
