### ISSUE TITLE
UI runs never ends loading after fresh install

### ISSUE THREAD

**Issue by micaelarg** [apache/airflow#27042]
### Apache Airflow version

2.4.1

### What happened

We did a fresh reinstall of airflow on ubuntu 22.04, running on UpCloud premises. It all went smoothly until we went on the web UI. The little grey dots in "Runs", "Last Run" and "Recent Tasks" keep loading (i.e. going from dark to light grey) for ever. We tried different versions of airflow and had the same issue. Any hints on how to fix that? 

### What you think should happen instead

It should load almost inmediatly, thus should be able to see green/red dots once I open the web browser.

### How to reproduce

fresh install ubuntu 22.04 and airflow 2.4.1

### Operating System

Ubuntu 22.04.1 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-sqlite==3.2.1

### Deployment

Other

### Deployment details

pip install and running straight from the server

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
I noticed this broken in main for me too (when testing with my breeze env). The browser console showed that there were issues with the `dags.js` file so I looked at the last commit which touched those and it turned out to be #26878
After reverting that commit on my local machine the UI is back alive again.

CCing @blag @bbovenzi and @jedcunningham

**Comment by o-nikolas** [comment]
I'd like to submit a PR which reverts those changes, but I'll try wrangle one of the above who were involved in that change to weigh in.

**Comment by micaelarg** [comment]
Awesome! When will the solution be updated on the pip last version?

**Comment by micaelarg** [comment]
@pierrejeambrun @o-nikolas -- just tried a fresh install and it is still not working. Anything I can do to help solving the issue? Any hint to something that would allow me to have the airflow up and running?

**Comment by bbovenzi** [comment]
> I noticed this broken in main for me too (when testing with my breeze env). The browser console showed that there were issues with the `dags.js` file so I looked at the last commit which touched those and it turned out to be #26878 After reverting that commit on my local machine the UI is back alive again.

What were the console logs you were seeing?

**Comment by pierrejeambrun** [comment]
@micaelarg

I wasn't able to reproduce this, on a fresh virtualenv installing airflow 2.4.3 and running it in standalone works fine.
Do you have any more details on how to reproduce this ? How did you install airflow, what metadata database are you using ?
