### ISSUE TITLE
Race condition in multiple triggerer process can lead to both picking up same trigger.

### ISSUE THREAD

**Issue by iw-pavan** [apache/airflow#27057]
### Apache Airflow version

main (development)

### What happened

Currently airflow triggerer loop picks triggers to process by below steps

query_unassinged_Triggers
update_triggers from above id
query which triggers are assigned to current process

If two triggerer process executes above queries in below order

query unassigned trigger both will get all triggers then if one triggerer completes 2nd and 3rd operation before 2nd triggerer does 2nd operation that will lead to both triggerer running same triggers
there is sync happening after that but unnecessary cleanup operations are done in that case.

### What you think should happen instead

There should be locking on rows which are updated.

### Operating System

All

### Deployment

Virtualenv installation

### Deployment details

HA setup with multiple triggerers can have this issue

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
Hey @iw-pavan! Thanks for submitting this issue :smile: I see that you've checked that you're willing to submit a PR, would you like me to assign this issue to you?

**Comment by pavansharma36** [comment]
@o-nikolas  I've raised PR with fix, you can assign this to me
