### ISSUE TITLE
Log files are still being cached causing ever-growing memory usage when scheduler is running

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#27065]
### Apache Airflow version

2.4.1

### What happened

My Airflow scheduler memory usage started to grow after I turned on the `dag_processor_manager` log by doing
```bash
export CONFIG_PROCESSOR_MANAGER_LOGGER=True
```

see the red arrow below

![2022-10-11_12-06 (1)](https://user-images.githubusercontent.com/14293802/195940156-3248f68a-656c-448a-9140-e50cfa3a8311.png)

By looking closely at the memory usage as mentioned in https://github.com/apache/airflow/issues/16737#issuecomment-917677177, I discovered that it was the cache memory that's keep growing:

![2022-10-12_14-42 (1)](https://user-images.githubusercontent.com/14293802/195940416-1da0ab08-a3b4-4f72-b35b-fba86918cdbc.png)

Then I turned off the `dag_processor_manager` log, memory usage returned to normal (not growing anymore, steady at ~400 MB)

This issue is similar to #14924 and #16737. This time the culprit is the rotating logs under `~/logs/dag_processor_manager/dag_processor_manager.log*`. 

### What you think should happen instead

Cache memory shouldn't keep growing like this

### How to reproduce

Turn on the `dag_processor_manager` log by doing
```bash
export CONFIG_PROCESSOR_MANAGER_LOGGER=True
```
in the `entrypoint.sh` and monitor the scheduler memory usage

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Other Docker-based deployment

### Deployment details

k8s

### Anything else

I'm not sure why the previous fix https://github.com/apache/airflow/pull/18054 has stopped working :thinking: 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I've addded a PR that should address it in #27223 @zachliu  - would it be possible that you test it in your installation?

**Comment by zachliu** [comment]
> I've addded a PR that should address it in #27223 @zachliu - would it be possible that you test it in your installation?

sure thing :+1:

**Comment by zachliu** [comment]
@potiuk the cache memory is still growing :crying_cat_face: 

![2022-10-27_10-32](https://user-images.githubusercontent.com/14293802/198315723-c48d12b0-314d-4459-b485-dce1e169940a.png)

**Comment by potiuk** [comment]
Maybe The rotating file handler has another place where it copies files and leaves them behind. Not the end of the world (as you know this is no-harm-at-all and perfecrly normal to happen.

Maybe i will take a look soon (or maybe you can @zahchliu - you could see how I've done that and you could potentially iterate on it and verify it in your test system and make a PR after you test it ? How about that?

Also there are ways you can check if this might be the cause. Just delete the rotated files and see if that causes drrop in cache memory used.

**Comment by potiuk** [comment]
Would be great contribution back :) ?

**Comment by zachliu** [comment]
yeah, the root cause of this might be somewhere else. here are the facts:
* setting `CONFIG_PROCESSOR_MANAGER_LOGGER=True` does make the cache increase
* deleting files under `~/logs/dag_processor_manager` has no effect on cache memory usage, also there are cache files i cannot delete
![2022-10-27_11-02](https://user-images.githubusercontent.com/14293802/198326228-bb59c72d-fb38-4fdd-bcd7-8ec49582db86.png)

**Comment by potiuk** [comment]
You can always drop the whole cache to verify what causes it:

https://linuxhint.com/clear_cache_linux/

Also you can do some trial/error to see which files are in the cache as explained in this answer:
https://serverfault.com/questions/278454/is-it-possible-to-list-the-files-that-are-cached

Seems this is not easy to get list of files which contribute to cache, but if you have some guesses you might try to find out by using fntools.

**Comment by zachliu** [comment]
the 2 `.nfs*` files at `~/logs/dag_processor_manager` do add up to my current cache memory usage :thinking: 

![2022-10-27_11-36](https://user-images.githubusercontent.com/14293802/198334683-656930fa-553b-4145-8874-f9fe4fe45d6a.png)

**Comment by Taragolis** [comment]
`.nfs*` files should be related to NFS not to Airflow.

**Comment by potiuk** [comment]
Very much so. This is the choice of using NFS to store logs :)

**Comment by zachliu** [comment]
wait i'm confused, so it is NFS design choice not to remove the cache file after it's written to an actual file?

**Comment by Taragolis** [comment]
> wait i'm confused, so it is NFS design choice not to remove the cache file after it's written to an actual file?
> 
> ![2022-10-27_12-07](https://user-images.githubusercontent.com/14293802/198342056-2a836c9b-4d02-40da-9ab2-231087e6fac6.png)

https://nfs.sourceforge.net/#faq_d2

**Comment by potiuk** [comment]
silly rename :rofl:

**Comment by potiuk** [comment]
Nothing we can do about it :). But I am not sure if those are the culprits - accoding to the descriptions those should be removed when airflow stops keeping the file unless client crashes

**Comment by Taragolis** [comment]
I also mount default `logs` directory to NFS (AWS EFS) so I could only suggest my personal configuration which use for a long time
1. Change default dag processor manager log location outside of NFS, e.g. `AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION = "/tmp/airflow/logs/dag_processor_manager/dag_processor_manager.log"`
2. Increase print stats interval `AIRFLOW__SCHEDULER__PRINT_STATS_INTERVAL = 300` which could reduce final size of file

**Comment by potiuk** [comment]
3. Write a custom handler to rotate the logs outside.
4. Use externa service for logging (CloudWatch etc.) for storing them remotely.

**Comment by potiuk** [comment]
5. Stop worrying about it. The fact that Unix cache grows has only one drawback - it will show up when you choose to in your monitoring service. You should monitor other parameters - it's perfectly OK that cache grows up until all available memory - it has no negative consequences

**Comment by zachliu** [comment]
i'm also using AWS EFS :handshake: 

i think i'll try 1 & 2, they seem to be the easiest except 5, which involves educating all current/future maintainers to understand memory nuances :sweat_smile:

**Comment by potiuk** [comment]
BTW. I've heard VERY bad things about EFS when EFS is used to share DAGs. It has profound impact on stability and performance of Airlfow if you have big number of DAGs unless you pay big bucks for IOPS. I've heard that from many people.

This is the moment when I STRONGLY recommend GitSync instead: https://medium.com/apache-airflow/shared-volumes-in-airflow-the-good-the-bad-and-the-ugly-22e9f681afca

**Comment by potiuk** [comment]
> 5, which involves educating all current/future maintainers to understand memory nuances sweat_smile

As counterintuitive as it is, I know what you are talking about :)

**Comment by Taragolis** [comment]
> BTW. I've heard VERY bad things about EFS when EFS is used to share DAGs. It has profound impact on stability and performance of Airlfow if you have big number of DAGs unless you pay big bucks for IOPS. I've heard that from many people.
> This is the moment when I usually STRONGLY recommend GitSync instead: https://medium.com/apache-airflow/shared-volumes-in-airflow-the-good-the-bad-and-the-ugly-22e9f681afca

It's always it depends on configuration and monitoring. I personally have this issue might be in Airflow 2.1.x and I do not know is it actually related to Airflow itself or some other stuff. Work with EFS definitely take more effort rather than GitSync.

Just for someone who might found this thread in the future with EFS performance degradation might help:

**Disable save python bytecodes inside of NFS (AWS EFS) mount**
   + Mount as Read-Only
   + Disable Python bytecode by set `PYTHONDONTWRITEBYTECODE=x`
   + Or set location for bytecodes by set `PYTHONPYCACHEPREFIX` for example to `/tmp/pycaches`

Throughput in mode Bursting in first looks like miracle but when all Bursting Capacity go to zero it could turn into your life into the hell. Each newly created EFS share has about 2.1 TB Bursting capacity.

What could be done here:
- Switch to Provisional Throughput mode permanently which might cost a lot, something like 6 USD per 1 MiB/sec without VAT
- Switch to Provisional Throughput mode only when Bursting Capacity less than some amount, like 0.5 TB, and switch back when Bursting Capacity exceed limit 2.1 TB. Unfortunately there is no autoscaling so it would be manual or combination of CloudWatch Alerting + AWS Lambda.

![image](https://user-images.githubusercontent.com/3998685/198383225-2b101e42-726f-4f60-90e2-44ab3e4a1098.png)

**Comment by potiuk** [comment]
This is very close to what I've heard! Good one @Taragolis! And yeah  PYTHONDONTWRITEBYTECODE is also my typical recommendation.

**Comment by zachliu** [comment]
i moved the dag_processor_manager logs from ```/user/local/airflow/logs/``` (NFS) to ```/tmp/airflow/logs/``` (local), but the cache memory still keeps growing :crying_cat_face: 

![2022-10-28_11-31](https://user-images.githubusercontent.com/14293802/198675995-7cf26d00-ed99-43d6-8a45-115cc44c9fa0.png)

so it is still using cache somewhere but not the `.nfs***` silly-rename cache files :thinking:

**Comment by potiuk** [comment]
So I guess the quest shoudl continue :)/ But let me repeat again - if you have anything that creates files continuously and those files are not deleted and there is no advice from the kernel to not use cache - they will increase the cache memory used.  You will likely never get it to 0 growth over time. Likely just ssh to your system and saving your history when you type in a command will increase cache used. And this is normal. So you are likely chasing a red herring.

**Comment by zachliu** [comment]
worse than a red herring, this is a mirage :laughing:
can't change the [kernel's behavior](https://serverfault.com/a/1090418/946571), i'll just change meself:
```python
LOGGING_CONFIG["handlers"]["processor_manager"].update(
    {
        'maxBytes': 10485760,  # 10M
        "backupCount": 3,
    }
)
```
this makes the cache memory usage cap at 40~50Mb
