### ISSUE TITLE
Connection time out when doing sts_assume_role with AwsBaseHook

### ISSUE THREAD

**Issue by btoh** [apache/airflow#27078]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I get connection time out when doing an assume_role with `AwsBaseHook`. I have provided an endpoint URL in the connection, but it keeps trying to connect to the default endpoint sts.amazonaws.com

### What you think should happen instead

It should pick up my endpoint url and connect to it instead. I have this working when I use boto3 directly, but I would like to get it working directly within the hook

### How to reproduce

1. Create connection within Airflow UI. Connection type is 'AWS', and in extras, provide an ARN, a region name and assume_role_method. In my case,  `assume_role_method`: `assume_role`
2. Use `AwsBaseHook`  to assume role: `hook = AwsBaseHook(aws_conn_id=connection_id, region_name=region)`

### Operating System

MacOs

### Versions of Apache Airflow Providers

apache-airflow-providers==3.2.0

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
Hey @btoh!
Thanks for submitting this issue. Can you update theHow to Reproduce section with how you're providing the endpoint url? Providing all the exact inputs to the connection (redacting or changing any sensitive names account numbers of course) will help folks triage this further.

**Comment by Taragolis** [comment]
Right now during creation sts client for assume role we only set botocore.config.Config and do not use all other parameters [from Connections Extra](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#configuring-the-connection).

https://github.com/apache/airflow/blob/ea55626d79fdbd96b6d5f371883ac1df2a6313ec/airflow/providers/amazon/aws/hooks/base_aws.py#L162-L164

In the other hand I do not know what side effect may happen when we start propagate it from Connections Extra

**Comment by btoh** [comment]
Hi @o-nikolas, here is some sample code I'm using:
`conn = Connection(conn_id='aws_test', conn_type='aws', extra = {'region_name':'eu-west-2', 'role_arn': 'arn:aws:xxxxxxx', 'assume_role_method': 'assume_role', 'host': 'elasticmapreduce.eu-west-2.amazonaws.com'})`

I then commit this connection using `settings.Session().add(conn)` and then `settings.Session().commit()` to persist the connection in the Airflow connections database.

When I try to use the connection in an operator, say the `EmrAddStepsOperator`, I get a timeout, because Airflow is trying to connect to `sts.amazonaws.com` instead

**Comment by btoh** [comment]
@Taragolis  - thanks for the comment. I'm still quite unsure about using botocore.config.Config, because I tried to use that as follows: `config = botocore.config.Config(endpoint_url = 'elasticmapreduce.eu-west-2.amazonaws.com')`, and I get a `TypeError: Got unexpected keyword argument: 'endpoint_url'`, so I'm not exactly sure that the endpoint url can be passed in through Config. Can you please point me to any examples where this has been done successfully?

**Comment by Taragolis** [comment]
I do not know your case and why you need to specify `endpoint_url` because it is not general use case.

However if you have timeout issues with access to any of the AWS endpoints (like `https://sts.amazonaws.com`) usual it refers to some miss configuration in VPC, like something wrong configure in route tables within VPC (no route to Internet Gateway, NAT Gateway or VPC Endpoints)

**Comment by Taragolis** [comment]
> STS service use global endpoint `https://sts.amazonaws.com` which not depend on actual `region_name`,

I've double checked and found this is not correct in all cases. 

Actually AWS has regional endpoints for STS (like `sts.eu-west-2.amazonaws.com`) but boto3 use STS global endpoint by default, see: https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html, and [there is no public API in boto3/botocore](https://github.com/boto/botocore/issues/2202) for change this parameter except set environment variable `AWS_STS_REGIONAL_ENDPOINTS=regional` or specify settings in profile config.

It also might cause some issue in some circumstances with specific network configurations.

**Comment by Taragolis** [comment]
@btoh just a wondering is information above help your?

**Comment by btoh** [comment]
@Taragolis yes - but it doesn't still solve the problem, as my Airflow instance still tries to connect to sts.amazonaws.com. My  (inelegant) solution so far has been to use temporary credentials generated by assuming the role directly with boto3.

**Comment by Taragolis** [comment]
> as my Airflow instance still tries to connect to sts.amazonaws.com.

One main question which endpoint_url do you expect to use for STS client in your case?

**Comment by btoh** [comment]
@Taragolis Like I mentioned above, I want to use the regional endpoint: `elasticmapreduce.eu-west-1.amazonaws.com`

**Comment by Taragolis** [comment]
If you use `botocore>=1.29` than this endpoint should generated by default.
The current limitations of AWS connection in provider that it use same `endpoint_url` for all AWS clients which might have some issues especially if call assume role.

**Comment by btoh** [comment]
@Taragolis I have botocore==1.29.20, and I still have the issue. I have attached the airflow DAG I'm running, as well as logs that show the error I'm facing, and my development environment. Maybe I'm missing something obvious that you can identify. Thank you very much for your help so far! Please let me know if there's any other information you need about this issue
[assume_role_logs.txt](https://github.com/apache/airflow/files/10168091/assume_role_logs.txt)
[environment.txt](https://github.com/apache/airflow/files/10168093/environment.txt)
[test_assume_role.txt](https://github.com/apache/airflow/files/10168095/test_assume_role.txt)

**Comment by Taragolis** [comment]
Oh... right. Forget that STS didn't use regional endpoint by default in `boto3`. And it should be enabled by set environment variable `AWS_STS_REGIONAL_ENDPOINTS` to `regional` all other clients use regional endpoints by default (except some S3 regions)


```python
import os
import boto3

os.environ["AWS_DEFAULT_REGION"] = "eu-west-1"

session = boto3.session.Session()
emr_client = session.client("emr")
print(f"Client info: {emr_client.meta.config.user_agent}")
print(f"STS Endpoint URL: {emr_client.meta.endpoint_url}")

sts_client = session.client("sts")
print(f"STS Endpoint URL: {sts_client.meta.endpoint_url}")

os.environ["AWS_STS_REGIONAL_ENDPOINTS"] = "regional"
sts_client_regional = session.client("sts")
print(f"STS Endpoint URL: {sts_client_regional.meta.endpoint_url}")
```

I have an idea to enable set endpoint url by dictionary (on service level) in connection rather than define it for all services.

**Comment by shubham22** [comment]
@btoh - could you please confirm if the suggestion from @Taragolis resolves your issue?

**Comment by shubham22** [comment]
@Taragolis @o-nikolas - IMO we should close this as there has been no response for 3+ months. It is filed as bug and I am not sure what we can fix here.

**Comment by btoh** [comment]
Hi @shubham22, sorry I thought I replied to your original mail. Yes, the suggestion by @Taragolis fixed my issue. I'll close this now.

**Comment by dillmac** [comment]
@btoh @Taragolis can AWS_STS_REGIONAL_ENDPOINTS be set within the connection extras?
