### ISSUE TITLE
Wrong missing args error when initialising operator with multiple inheritance

### ISSUE THREAD

**Issue by alexandermalyga** [apache/airflow#27081]
### Apache Airflow version

2.4.1

### What happened

When initialising an operator with multiple inheritance, an exception is raised: 
`airflow.exceptions.AirflowException: missing keyword argument ...`

This only happens when multiple parent classes share an attribute name in their `__init__` method.

### What you think should happen instead

Multiple inheritance with shared attribute names in the parent classes should work as expected in Python.

### How to reproduce

Run this python script:

```python
from airflow.models import BaseOperator

class A(BaseOperator):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(**kwargs)

class B(BaseOperator):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(**kwargs)

class C(A, B):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(value=value, **kwargs)

C(task_id="test", value="value")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "airflow/models/baseoperator.py", line 411, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "<stdin>", line 1, in __init__
  File "airflow/models/baseoperator.py", line 411, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "<stdin>", line 1, in __init__
  File "airflow/models/baseoperator.py", line 394, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'value'
```

### Operating System

macOS 12.6

### Deployment

Docker-Compose

### Anything else

The issue seems to be somehow caused by the `@apply_defaults` decorator and signature caching, but I'm not very familiar with it.

Related: 

- https://stackoverflow.com/questions/54529660/airflow-apply-defaults-decorator-reports-argument-is-required
- https://lists.apache.org/thread/kwfdk17t8gfrv6fbwoc041sr8thgt4p3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
> work as expected in Python.

How? I removed `BaseOperator` from the given example:

```python
class R:
    def __init__(**kwargs):
        pass

class A(R):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(**kwargs)

class B(R):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(**kwargs)

class C(A, B):
    def __init__(self, *, value: str, **kwargs):
        super().__init__(value=value, **kwargs)

C(task_id="test", value="value")
```

And it still fails.

```
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
    C(task_id="test", value="value")
  File "<stdin>", line 21, in __init__
    super().__init__(value=value, **kwargs)
  File "<stdin>", line 11, in __init__
    super().__init__(**kwargs)
TypeError: __init__() missing 1 required keyword-only argument: 'value'
```

Python’s `super` chain follows MRO (C→B→A→BaseOperator in this example), so the `super().__init__` calls in `C.__init__` calls `B.__init__`, **and the `super().__init__` in `B.__init__` calls `A.__init__`**, which is missing the required `value` argument.

From what I can tell, `apply_defaults` is doing its job properly. It obscures the traceback, which we could improve, but the error is legistimate.
