### ISSUE TITLE
Autorefresh on Graphview is not working on UI 2.4.1

### ISSUE THREAD

**Issue by erdos2n** [apache/airflow#27118]
### Apache Airflow version

2.4.1

### What happened

When clicking on GraphView and running a DAG the autorefresh is no longer working, when checking the logs of the browser the following message is showing

```
Failed to load response data: No resource with given identifier found
```

### What you think should happen instead

Tasks should be changing statuses live on the Graph page as the DAG runs

### How to reproduce

Create a DAG using dynamic task mapping in 2.4.1 and run the DAG

### Operating System

Debian

### Deployment

Astronomer

### Anything else

Every time for every DAG

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Fixed in https://github.com/apache/airflow/pull/26926
