### ISSUE TITLE
Assume Role with role_arn is failing in apache-airflow-providers-amazon==6.0.0. Works with apache-airflow-providers-amazon==5.0.0

### ISSUE THREAD

**Issue by sandeeppure** [apache/airflow#27130]
### Apache Airflow version

2.4.1

### What happened

I am attempting to submit AWS Batch Job with AWS BatchOperator.
I configured AWS Connection with role_arn for assuming a role. My assumed role is in a different account.
The assume role functionality is not working with apache-airflow-providers-amazon==6.0.0

When I downgraded to apache-airflow-providers-amazon==5.0.0 I could submit the job successfully with the assumed role.

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==6.0.0

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
@sandeeppure Do you use initial credentials (access key / secret key) for assume role?

If so it most possible will fix by https://github.com/apache/airflow/pull/26946

**Comment by eladkal** [comment]
Should be resolved in https://github.com/apache/airflow/pull/26946
