### ISSUE TITLE
dbt Cloud Provider Not Compatible with emea.dbt.com

### ISSUE THREAD

**Issue by ernestoongaro** [apache/airflow#27146]
### Apache Airflow Provider(s)

dbt-cloud

### Apache Airflow version

2.3.3

### Operating System

Linux

### Deployment

Composer

### What happened

Trying to use the provider with dbt Cloud's new EMEA region (https://docs.getdbt.com/docs/deploy/regions) but not able to use the emea.dbt.com as a tenant, as it automatically adds `.getdbt.com` to the tenant

### What you think should happen instead

We should be able to change the entire URL - and it could still default to cloud.getdbt.com

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
Hey @ernestoongaro

Thanks for submitting this issue! It looks like you've checked that you're willing to submit a PR, that would be much appreciated! Would you like me to assign this task to you?

**Comment by josh-fell** [comment]
@o-nikolas I can take this.

**Comment by o-nikolas** [comment]
> @o-nikolas I can take this.

Thanks Josh!

**Comment by erdinculuturk-nw** [comment]
hey all @josh-fell @ernestoongaro,

Looks like this fix hasn't been released yet.
Is there any workaround that I can use until the release?

Thanks,
Erdinc

**Comment by josh-fell** [comment]
@erdinculuturk-nw The fix was released as part of version 2.3.1 of the dbt Cloud provider package. What version of the provider package do you have installed?

**Comment by josh-fell** [comment]
Right on, if you still can't connect to the EMEA region with 2.3.1+, let us know.

**Comment by erdinculuturk-nw** [comment]
hey @josh-fell, just wanted to let you know that it works fine now after upgrading to proper versions for both Airflow and dbt Cloud provider.
Thanks for the help.
