### ISSUE TITLE
Graph view reload does not work anymore

### ISSUE THREAD

**Issue by pspeter** [apache/airflow#27159]
### Apache Airflow version

2.4.1

### What happened

Clicking Refresh on the graph view of any DAG does not refresh the view, it just gets stuck refreshing forever.
In the JS console, it displays the following error message on each refresh:

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    N http://internal-airflow/static/dist/graph.c3f9b20b23ed9651c62a.js:2
    jQuery 7
    N http://internal-airflow/static/dist/graph.c3f9b20b23ed9651c62a.js:2
    R http://internal-airflow/static/dist/graph.c3f9b20b23ed9651c62a.js:2
    $/< http://internal-airflow/static/dist/d3.min.js:1
```

This happens even on a fresh DAG with no runs, even if the JSON returned by the request to `/object/task_instances?dag_id=test_dag&execution_date=2022-10-20T11:17:22.870600+00:00` is empty, but also on normal DAGs.

The container logs also show no problems, just that the GET-request was made.

### What you think should happen instead

Refresh the graph.

### How to reproduce

Create a DAG with one EmptyOperator, go to graph view, click refresh.

### Operating System

CentOS 8

### Versions of Apache Airflow Providers

apache-airflow-providers-databricks
apache-airflow-providers-microsoft-azure

### Deployment

Docker-Compose

### Deployment details

Docker version 20.10.14, build a224086

We use official image apache/airflow:2.4.1-python3.9 slightly extended with the above providers and a custom fix for the python package `thrift` used by the DatabricksOperator. It's a small fix just to make it work with our proxy.

### Anything else

We upgraded from 2.3.3 to 2.4.1, had no problems in 2.3.3.

Tested with Firefox and Edge, both are the same. In Edge, the error message is `VM90:1 Uncaught SyntaxError: "[object Object]" is not valid JSON`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by set92** [comment]
In my case, with Chrome shows 
```
VM221:1 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (graph.c3f9b20b23ed9651c62a.js:2:21394)
    at c (jquery-latest.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-latest.js:2:29072)
    at l (jquery-latest.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-latest.js:2:82355)
```

And we also upgraded from 1.4 to 2.4.1, and the error is in graph view.
