### ISSUE TITLE
Carets in Grid view are the wrong way around

### ISSUE THREAD

**Issue by stuart23** [apache/airflow#27166]
### Apache Airflow version

main (development)

### What happened

When expanding tasks to see sub-tasks in the Grid UI, the carets to expand the task are pointing the wrong way.

### What you think should happen instead

Can you PLEASE use the accepted Material UI standard for expansion & contraction - https://mui.com/material-ui/react-list/#nested-list

### Operating System

All

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @bbovenzi

**Comment by bbovenzi** [comment]
You're right. Our warning messages are also inconsistent.
<img width="1039" alt="Screen Shot 2022-10-20 at 12 06 59 PM" src="https://user-images.githubusercontent.com/4600967/197001087-04492b2b-1d6d-4ae8-8425-75dc9f15302c.png">

**Comment by tirkarthi** [comment]
The change for caret in grid page is to be done at this conditional to swap them : https://github.com/apache/airflow/blob/b9e133e40c2848b0d555051a99bf8d2816fd28a7/airflow/www/static/js/dag/grid/TaskName.tsx#L60

**Comment by stuart23** [comment]
Thanks @tirkarthi - do you want to make the PR?

**Comment by shashwata27** [comment]
@stuart23 is it solved or I can?

**Comment by tirkarthi** [comment]
@shashwata27 I am not working on this issue. Please feel free to proceed.

**Comment by shashwata27** [comment]
@tirkarthi ok I will make a PR soon

**Comment by vchiapaikeo** [comment]
Wanted to get started with some light UI work here so gave this simple issue a shot. Hope that's okay @shashwata27 - I see your PR was a bit stale.

PR: https://github.com/apache/airflow/pull/28624

cc @eladkal
