### ISSUE TITLE
2.2.3 deps conclicts between celery and flask.

### ISSUE THREAD

**Issue by nobody4t** [apache/airflow#27175]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I try to install airflow 2.2.3. But  I got errors like: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
celery 5.2.3 requires click<9.0,>=8.0.3, but you have click 7.1.2 which is incompatible.
```

airflow here requires celery at least 5.2.3 which requires click <9.0,>=8.0.3. But flask 1.1.4 requres 7.1.2.

### What you think should happen instead

No deps conflicts.

### How to reproduce

Just install airflow 2.2.3.

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

2.2.3

### Deployment

Other

### Deployment details

pip install airflow==2.2.3
python 3.10.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Do you install with constraints?
