### ISSUE TITLE
Exception when I set the hive2 authMechanism  to PLAIN 

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#272]
I set extra to {"authMechanism": "PLAIN"} in the hive2 connection. However I got this exception when I do some query. Someone could help me?

Wrong number of arguments for overloaded function 'Client_setAttr'. Possible C/C++ prototypes are: setAttr(saslwrapper::Client *,std::string const &,std::string const &) setAttr(saslwrapper::Client *,std::string const &,uint32_t)

**Comment by mistercrunch** [comment]
You may want to drop down to troubleshooting pyhs2 directly, looks like the bug may be in that library (or is it in the way to hook is using it?). If you can make pyhs2 work outside of Airflow in your environment then you can easily retrofit the hook to make it work. Unfortunately pyhs2 has gone without a maintainer recently...
https://github.com/BradRuderman/pyhs2

Anybody else using pyhs2 in PLAIN mode? We use NOSASL so i can't really help troubleshooting PLAIN...

**Comment by griffinqiu** [comment]
I worked the PLAIN mode. it work as well in my another server.

**Comment by griffinqiu** [comment]
I found the reason after debug. It bcs the user is a utf8 string.

saslc.setAttr("username", user)
