### ISSUE TITLE
Handle TODO: .first() is not None can be changed to .scalar()

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#27200]
### Body

The TODO part of:
https://github.com/apache/airflow/blob/d67ac5932dabbf06ae733fc57b48491a8029b8c2/airflow/models/serialized_dag.py#L156-L158

can now be addressed since we are on sqlalchemy 1.4+ and https://github.com/sqlalchemy/sqlalchemy/issues/5481 is resolved

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by ayushthe1** [comment]
hey @eladkal ,i would like to work on this issue. Please assign it to me.

**Comment by ayushthe1** [comment]
#self-assign

**Comment by ayushthe1** [comment]
hey @potiuk ,i made a pr for this issue .Could you please review it.
