### ISSUE TITLE
Nested Parameters Break for DAG Run Configurations

### ISSUE THREAD

**Issue by technopahadi** [apache/airflow#27228]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version Used: 2.3.3

This bug report is being created out of the following discussion - https://github.com/apache/airflow/discussions/25064

With the following DAG definition (with nested params):

```
DAG(
    dag_id="some_id",
    start_date=datetime(2021, 1, 1),
    catchup=False,
    doc_md=__doc__,
    schedule_interval=None,
    params={
        "accounts": Param(
            [{'name': 'account_name_1', 'country': 'usa'}],
            schema =  {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "default": {"name": "account_name_1", "country": "usa"},
                    "properties": {
                        "name": {"type": "string"},
                        "country": {"type": "string"},
                    },
                    "required": ["name", "country"]
                },
            }
        ),
    }
)
```

**Note:** It does not matter whether `Param` and JSONSchema is used or not, I mean you can try to put a simple nested object too.

Then the UI displays the following:

```
{
    "accounts": null
}
```

### What you think should happen instead

Following is what the UI should display instead:

```
{
    "accounts": [
        {
                "name": "account_name_1",
                "country": "usa"
       }
    ]
}
```

### Operating System

Debian Linux

### Deployment

Composer

### Deployment details

Although I am personally using Composer, it is most likely related to Airflow only given there are more non-Composer folks facing this (from the discussion's original author and the Slack community).

### Anything else

I have put some more explanation and a quick way to reproduce this [as a comment in the discussion](https://github.com/apache/airflow/discussions/25064#discussioncomment-3907974) linked.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked as good-first-issue - maybe someone would llike to take a look.

**Comment by tirkarthi** [comment]
During AirflowApp instantiation `read_dags_from_db` is set to True. This causes serialized dags to be loaded from database. Meanwhile collecting it from `DagBag` without flask app context makes it read from files. My first guess is the below approach to deserialize the param value before passing them to resolve. I can make a PR with tests for this.

https://github.com/apache/airflow/blob/b29ca4e77d4d80fb1f4d6d4b497a3a14979dd244/airflow/www/extensions/init_dagbag.py#L33

https://github.com/apache/airflow/blob/b29ca4e77d4d80fb1f4d6d4b497a3a14979dd244/airflow/models/dagbag.py#L184-L191

```patch
diff --git a/airflow/www/views.py b/airflow/www/views.py
index bc03f42f04..541dc49a6f 100644
--- a/airflow/www/views.py
+++ b/airflow/www/views.py
@@ -104,6 +104,7 @@ from airflow.models.serialized_dag import SerializedDagModel
 from airflow.models.taskinstance import TaskInstance
 from airflow.providers_manager import ProvidersManager
 from airflow.security import permissions
+from airflow.serialization.serialized_objects import BaseSerialization
 from airflow.ti_deps.dep_context import DepContext
 from airflow.ti_deps.dependencies_deps import RUNNING_DEPS, SCHEDULER_QUEUED_DEPS
 from airflow.timetables.base import DataInterval, TimeRestriction
@@ -1864,7 +1865,8 @@ class Airflow(AirflowBaseView):
             else:
                 try:
                     default_conf = json.dumps(
-                        {str(k): v.resolve(suppress_exception=True) for k, v in dag.params.items()}, indent=4
+                        {str(k): v.resolve(value=BaseSerialization.deserialize(v.value), suppress_exception=True)
+                         for k, v in dag.params.items()}, indent=4
                     )
                 except TypeError:
                     flash("Could not pre-populate conf field due to non-JSON-serializable data-types")
```
