### ISSUE TITLE
Pgbouncer doesn't support extraAnnotations for deployment/pod

### ISSUE THREAD

**Issue by rahulgoyal2987** [apache/airflow#27246]
### Official Helm Chart version

1.6.0

### Apache Airflow version

2

### Kubernetes Version

1.24

### Helm Chart configuration

Pgbouncer doesn't support extraAnnotations for deployment/pod

### What happened

Pgbouncer doesn't support extraAnnotations for deployment/pod

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rahulgoyal2987** [comment]
Please find pull request for issue:
https://github.com/apache/airflow/pull/27247/files

**Comment by amoghrajesh** [comment]
@potiuk @jedcunningham @hussein-awala  I see that the issue has gone stale here. Can i pick this up and lead it to completion?

**Comment by potiuk** [comment]
Sure. You should not ping us BTW  but rather the person who got assigned, and if no response - continue. @rahulgoyal2987

**Comment by jedcunningham** [comment]
This functionality was added in #30168.
