### ISSUE TITLE
Add ability to specify SQLAlchemy logging level

### ISSUE THREAD

**Issue by ejstembler** [apache/airflow#27265]
### Description

Currently we are not seeing SQLAlchemy related logs.  It would be great to see the generated SQL SQLAlchemy generates.

Please consider adding the ability to enable SQLAlchemy logging. Perhaps add a new ENV variable, `SQLALCHEMY_ENGINE_LOGGING_LEVEL`.

```python
# wherever Airflow initializes SQLAlchemy

import os
import logging


sqlalchemy_engine_logging_level = os.environ['SQLALCHEMY_ENGINE_LOGGING_LEVEL'].upper()
logging_level = logging.getLevelName(sqlalchemy_engine_logging_level)

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging_level)
```

### Use case/motivation

We want to be able to see the SQLAlchemy log entries.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can already today do it via "advanced logging configuration" as described in configuration: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html#advanced-configuration. You just need to create local settings. deepcopy standard configuration and you can add any logging configuration there.
