### ISSUE TITLE
KubernetesPodOperator: Option to show logs from all containers in a pod

### ISSUE THREAD

**Issue by pulquero** [apache/airflow#27282]
### Description

Currently, KubernetesPodOperator fetches logs using
```
             self.pod_manager.fetch_container_logs(
                    pod=self.pod,
                    container_name=self.BASE_CONTAINER_NAME,
                    follow=True,
                )
```
and so only shows log from the main container in a pod. It would be very useful/helpful to have the possibility to fetch logs for all the containers in a pod.

### Use case/motivation

Making the cause of failed KubernetesPodOperator tasks a lot more visible.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yep. nice feaure. Maybe you would like to add it @pulquero and become one of the > 2200 contributors to Airflow? 

Otherwise it will need to wait for someone to pick it up (marked it as good first issue).

**Comment by bdsoha** [comment]
@pulquero How would you suggest displaying or storing the logs? In sequence?

**Comment by pulquero** [comment]
I imagine verbatim with whatever the kubernetes api call returns.

**Comment by mlnsharma** [comment]
Hi @potiuk I would like to work on this. If nobody is working on it, can you please assign it to me?

**Comment by potiuk** [comment]
Done

**Comment by mlnsharma** [comment]
Hi, I created a pull request https://github.com/apache/airflow/pull/27802. Tested changes locally, logs will be printed for each container one after another, except for the airflow-xcom-sidecar container. Please review it @potiuk @pulquero 

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1742344/202896341-9fdf7ca8-07df-4122-af7d-026166282fdf.png">

**Comment by pulquero** [comment]
PR looks good to me, I would suggest adding an option to KubernetesPodOperator so it's possible to specify the names of the containers to fetch the logs for, default it to "base", and maybe empty list means all containers, something like that.

**Comment by bdsoha** [comment]
@pulquero A similar comment was left on the pull request itself.

https://github.com/apache/airflow/pull/27802#pullrequestreview-1187282883

**Comment by mlnsharma** [comment]
Hi @pulquero @bdsoha @potiuk 
I have my code changes ready, could you please review it and merge it?

**Comment by amoghrajesh** [comment]
@potiuk @pulquero @potiuk I would like to lead this to completion if no one else is actively working on it. Would like to make some optimisations from my end too on what the PR has currently
