### ISSUE TITLE
scripts/tools/initialize_virtualenv.py calling .exists() on str

### ISSUE THREAD

**Issue by rkarish** [apache/airflow#27338]
### Apache Airflow version

main (development)

### What happened

While setting up a local development environment I went to use the `scripts/tools/initialize_virtualenv.py` script and received an exception. I believe this should be `os.path.exists(airflow_home)` instead.

```
Traceback (most recent call last):
  File "/Users/rkarish/Projects/airflow/scripts/tools/initialize_virtualenv.py", line 187, in <module>
    main()
  File "/Users/rkarish/Projects/airflow/scripts/tools/initialize_virtualenv.py", line 142, in main
    clean_up_airflow_home(airflow_home_dir)
  File "/Users/rkarish/Projects/airflow/scripts/tools/initialize_virtualenv.py", line 36, in clean_up_airflow_home
    if airflow_home.exists():
AttributeError: 'str' object has no attribute 'exists'
```

Also, `LOCAL_VIRTUALENV.rst` has an incorrect path to this file.

### How to reproduce

```shell
mkdir $HOME/airflow
./scripts/tools/initialize_virtualenv.py
```

### Operating System

macOS 13.0

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
Thanks for the bug report @rkarish!

I've assigned you the task since you checked that you're willing to submit a PR :smiley: 

>  I believe this should be os.path.exists(airflow_home) instead

Looking at the function stub for `clean_up_airflow_home` it looks like that code is expecting a `Path` object, but it's getting a string. So I think the better fix is to update the calling code to pass in a Path object instead of a string as it is now.

**Comment by rkarish** [comment]
Hi @o-nikolas, seems like it was intended to be a `Path` object like you said. I had a PR open with an approval but needed to move it to a branch in my fork so I opened another PR.

**Comment by o-nikolas** [comment]
> Hi @o-nikolas, seems like it was intended to be a `Path` object like you said, thank you for pointing that out and assigning me the ticket. I had a PR open with an approval but needed to move it to a branch in my fork so I opened another PR for this.

Thanks for putting up a PR! I've reviewed it and left a comment :)
