### ISSUE TITLE
镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### ISSUE THREAD

**Issue by 601579263** [apache/airflow#27343]
### Apache Airflow version

2.4.2

### What happened

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### What you think should happen instead

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### How to reproduce

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### Operating System

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### Versions of Apache Airflow Providers

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### Anything else

镜像缺少authlib依赖这是咋回事啊？镜像版本是2.2.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Not an Airflow issue.
