### ISSUE TITLE
Upgrade to the latest version of bitnami/postgresql

### ISSUE THREAD

**Issue by calebwoofenden** [apache/airflow#27353]
### Official Helm Chart version

1.7.0 (latest released)

This is a feature request for the helm chart. It's currently using bitnami/postgresql as a dependency chart when Postgres is enabled. It's pointing at version 10.5.3, which is over a year old. That chart has been updated significantly since then. It offers a lot of new features, and also has a lot of changes in variable names. This can make it difficult to customize values of that chart since you have to find the documentation for it at that version.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Why don't you raise a PR for that ? IT should be as easy as changing version and seeing if all tests pass?

**Comment by potiuk** [comment]
Update: It\s even easier - updating the Postgres Chart .tgz file to the right version in the PR - we changed it some time ago. @calebwoofenden - would you want to do it ?

**Comment by calebwoofenden** [comment]
Can do, though I'm quite sure it will cause at least some problems. The documentation for the apache/airflow chart tells users to set `postgresql.postgresqlUsername` and `postgresql.postgresqlPassword`, which are variable names that are no longer used in the latest version of the postgresql chart. It looks like they've been renamed to `postgresql.auth.username` and `postgresql.auth.password`. I can make a branch and just replace these values and see if it works though.

**Comment by potiuk** [comment]
> Can do, though I'm quite sure it will cause at least some problems. The documentation for the apache/airflow chart tells users to set `postgresql.postgresqlUsername` and `postgresql.postgresqlPassword`, which are variable names that are no longer used in the latest version of the postgresql chart. It looks like they've been renamed to `postgresql.auth.username` and `postgresql.auth.password`. I can make a branch and just replace these values and see if it works though.

So ..... opportunitu for an improvement then! You seem to know what to do - happy to help with reviewing it, and if they pass the  the Helm tests, you are sure it works (we are using the source Helm Chart to run Helm Kubernetes tests, so it is automatically tested. 

Shall I assign you ?

**Comment by calebwoofenden** [comment]
Here ya go 😄 https://github.com/apache/airflow/pull/27357
