### ISSUE TITLE
Improve error message when branched task_id does not exist

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#27409]
### Body

This issue is to handle the TODO left in the code:
https://github.com/apache/airflow/blob/64174ce25ae800a38e712aa0bd62a5893ea2ff99/airflow/operators/python.py#L211

Related: https://github.com/apache/airflow/pull/18471/files#r716030104

Currently only BranchPythonOperator will show informed error message when the requested branched task_id does not exist other branch operators will show :
```
  File "/usr/local/lib/python3.9/site-packages/airflow/models/skipmixin.py", line 147, in skip_all_except
    branch_task_ids = set(branch_task_ids)
TypeError: 'NoneType' object is not iterable
```

This task is to generalize the solution of https://github.com/apache/airflow/pull/18471/ to all branch operators.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Oh. yeah. 

I read recently an advice - never leave TODOs in the code except while you are iterating on thoe code - always convert TODO to issues !

Maybe we should strive to remove all TODOs and have pre-commit for that :). ?

**Comment by o-nikolas** [comment]
> > Maybe we should strive to remove all TODOs and have pre-commit for that :). ?
> 
> I think TODO are OK.. we just need to go over them once in a while We have some from 2017
> 

I land somewhere in the middle, I think they're okay sometimes, but if you do commit a TODO it should _always_ have an associated Issue created and mentioned/linked in the TODO (IMHO)
