### ISSUE TITLE
SFTP Sensor fails to locate file

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#27418]
### Body

issue is described in PR https://github.com/apache/airflow/pull/25705
the author of the PR abandon it so anyone can try to submit a fix to the issue.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Bowrna** [comment]
could I try fixing this issue @eladkal ?

**Comment by potiuk** [comment]
Feel Free.

**Comment by potiuk** [comment]
Closing as duplicate of #28121 (and the other being more complete)
