### ISSUE TITLE
CeleryExecutor when zero worker and 1 triggerer -> async task are queued 

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#27427]
### Apache Airflow version

2.4.2

### What happened

With the Celeryexecutor with 1 scheduler and 1 triggerer 

Async tasks ( deferable ) stay in queued state when there is zero airflow worker

### What you think should happen instead

Deferable task should not stay in queued STATE when there is at least 1 triggerer with enought slots to run the async task

### How to reproduce
```shell
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.4.2/docker-compose.yaml'

mkdir -p ./dags ./logs ./plugins

docker compose up -d

# wait 1 minute

docker stop airlfow-worker

# open  http://localhost:8080/dags/example_time_delta_sensor_async/grid
# activate dag 
# trigger run

# the task stay in queued


docker start airlfow-worker

# the task run when worker is back online


```

### Operating System

Ubuntu 22.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is completely invalid and comes from misunderstanding how Async/Triggerer works.. Triggerer DOES NOT execute derrerd tasks. It executes Triggers and when the trigger determines that deferrable task should run, it will let the regular "worker" execute it. So the observed behaviour is 100% correct.
