### ISSUE TITLE
Incorrect command displayed in warning when breeze dependencies are changed

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#27429]
### Apache Airflow version

main (development)

### What happened

During switching between some old branches I noticed the below warning. The `--force` option seems to have been removed in 3dfa44566c948cb2db016e89f84d6fe37bd6d824 and is default now. This message could be updated in below places

https://github.com/apache/airflow/blob/b29ca4e77d4d80fb1f4d6d4b497a3a14979dd244/dev/breeze/src/airflow_breeze/utils/reinstall.py#L50

https://github.com/apache/airflow/blob/b29ca4e77d4d80fb1f4d6d4b497a3a14979dd244/dev/breeze/src/airflow_breeze/utils/reinstall.py#L59

 Also here I guess

https://github.com/apache/airflow/blob/b29ca4e77d4d80fb1f4d6d4b497a3a14979dd244/dev/breeze/src/airflow_breeze/utils/path_utils.py#L232

```
$ breeze shell                                                    

Breeze dependencies changed since the installation!

This might cause various problems!!

If you experience problems - reinstall Breeze with:

    breeze setup self-upgrade --force

This should usually take couple of seconds.
```

```
breeze setup self-upgrade --force      
Usage: breeze setup self-upgrade [OPTIONS]

Try running the '--help' flag for more information.

╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such option: --force                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

To find out more, visit https://github.com/apache/airflow/blob/main/BREEZE.rst
```

### What you think should happen instead

The warning message could be updated with correct option.

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @potiuk

**Comment by bdsoha** [comment]
@tirkarthi @potiuk Just opened a PR

**Comment by potiuk** [comment]
Me too :) exactly in tnis moment @bdsoha

**Comment by potiuk** [comment]
Sorry @bdsoha - > I have not seen your change while I pushed mine :)

**Comment by bdsoha** [comment]
> Sorry @bdsoha - > I have not seen your change while I pushed mine :)

No worries, always glad to help.

**Comment by potiuk** [comment]
> No worries, always glad to help.

I will remember :)
