### ISSUE TITLE
Unexpected Last Run same as Next Run timestamp in DAGs view

### ISSUE THREAD

**Issue by vitaly-krugl** [apache/airflow#27477]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Recently upgraded to apache-airflow 2.3.1 (from 1.10.15)

Observed that several of the dags sometimes have Last Run timestamp same as Next Run timestamp in DAGs view. This changes from time to time. This was not observed prior to upgrading to Airflow 2.x.

See Screenshot for examples:
![Screen Shot 2022-11-02 at 18 09 56](https://user-images.githubusercontent.com/1441066/199612041-05e8cb2e-dd88-486f-b7fc-bd2ff4152fae.jpg)
In the above screenshot, the following have the same timestamp:
* 2022-11-02, 21:52:27	2022-11-02, 21:52:27
* 2022-11-02, 21:56:20	2022-11-02, 21:56:20

### What you think should happen instead

Expect Last Run and Next Run to differ by Schedule Interval

### Operating System

Ubuntu

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Can you explain what is your timezone configuration (@bbovenzi @pierrejeambrun - I guess it might be related to timezone problem - wild guess)

@vitaly-krugl - is it possible that you further upgrade to latest version of Airlfow and check if it is still there? Airflow 2 follows semver and the expectation is that upgrade/migration should be painless.

**Comment by uranusjr** [comment]
Tentitively adding UI since I’m not sure whether this is a problem in webserver representation or something in the scheduling logic.

**Comment by bbovenzi** [comment]
I'm not sure. Let's see if it is a migration issue: What if you create a new dag with a daily schedule, does that have the correct Next Run?
