### ISSUE TITLE
airfow can not import   RemovedInAirflow3Warning ???

### ISSUE THREAD

**Issue by timecommunication** [apache/airflow#27494]
### Apache Airflow version

2.4.2

### What happened

After upgrading my airflow from 2.3.3 to 2.4.2, I found this error on web UI. 

![屏幕截图 2022-11-04 102658](https://user-images.githubusercontent.com/19165258/199872330-f01d5cb1-c508-4c51-bcb9-91b2a39628d4.png)

### What you think should happen instead

how to fix this error ?

### How to reproduce

upgrade command is :

pip3 install "apache-airflow==2.4.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.4.2/constraints-no-providers-3.10.txt"

### Operating System

Ubuntu 22.04.1 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.0.0
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-sqlite==3.0.0

### Deployment

Virtualenv installation

### Deployment details

upgrade command is :

pip3 install "apache-airflow==2.4.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.4.2/constraints-no-providers-3.10.txt"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by timecommunication** [comment]
it seems the error occurs in airflow source code.

**Comment by Taragolis** [comment]
@timecommunication did you restart all airflow services after upgrade airflow version in virtual environment?

**Comment by timecommunication** [comment]
> @timecommunication did you restart all airflow services after upgrade airflow version in virtual environment?

Yes, I did.
