### ISSUE TITLE
Bug : Backfill job gets "replicated" to consume all of the task slots 

### ISSUE THREAD

**Issue by r39132** [apache/airflow#275]
I am trying to run a backfill using the following command `airflow backfill ep_demo -s 2015-08-19 -e 2015-08-19 -i`

The code base is about 2 weeks old -- last pulled from master 2 weeks ago.

I allow `130` tasks, and all 130 were taken by this backfill command! 

`deploy@etl-00:/root$ ps ax|grep 'airflow backfill'|wc -l`
`130`

**Comment by mistercrunch** [comment]
Are you using LocalExecutor or CeleryExecutor?

**Comment by r39132** [comment]
Local

**Comment by mistercrunch** [comment]
LocalExecutor spins off a multiprocess pool inside the command. Each `airflow` cli command has its own multiprocess pool. Meaning if your concurrency is set to 10 and you have 10 backfill commands running at once, you'll get 100 tasks running simultaneously.

Also your `ps|grep|wc`combo will always look maxed out as you're looking at the number of processes and I believe they all get created regardless of how they are used.

The proper way to get a shared pool of slots is through the CeleryExecutor.
