### ISSUE TITLE
[REDACTED]

### ISSUE THREAD

**Issue by kadu-vido** [apache/airflow#27504]
[REDACTED]

* This should be reported in confidence via  https://github.com/apache/airflow/security/policy

**Comment by potiuk** [comment]
This is a very bad idea to create a public issue @kadu-vido. 

This is not following our security policy  - https://github.com/apache/airflow/security/policy  PLEASE DON'T DO IT next time, just follow the policy. This not responsible behaviour and while you've been informed about that when you opened the issue. 

I am deleting this issue now. Please reaport it following the polcy.

**Comment by potiuk** [comment]
Can't delete it, unfortunately. This is was not a good idea to post it this way.

**Comment by potiuk** [comment]
Which logs do you find this information in @kadu-vido ?

**Comment by eladkal** [comment]
I removed the content and hidden it from history.
@kadu-vido please report this privately as @potiuk suggested. thank you
