### ISSUE TITLE
Making logging for HttpHook optional

### ISSUE THREAD

**Issue by alon-parag** [apache/airflow#27507]
### Description

In tasks that perform multiple requests, the log file is getting cluttered by the logging in `run`, line 129
I propose that we add a kwarg `log_request` with default value True to control this behavior

### Use case/motivation

reduce unnecessary entries in log files

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to make PR. I assigned youl

**Comment by amoghrajesh** [comment]
Is this issue being actively worked on? If not, I can take this up given some background and where to look at.
@potiuk @alon-parag

**Comment by potiuk** [comment]
Feel free.

**Comment by amoghrajesh** [comment]
@alon-parag @potiuk can you attach some references on how to reproduce this issue/where to look to make code changes?

**Comment by potiuk** [comment]
I think it's quite straigthforward from the description? (at least for me). Run HTTP operator (you will find examples likely in the code of airflow or google) and you will reproduce it likely.

**Comment by amoghrajesh** [comment]
Thank you @potiuk! I was able to reproduce this locally and have tried providing a fix for this here https://github.com/apache/airflow/pull/28911

**Comment by amoghrajesh** [comment]
@potiuk we should be closing this issue. The PR has been merged

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/28911
