### ISSUE TITLE
Resizable grid view components

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#27512]
### Description

~1. Ability to change change the split ratio of the grid section and the task details section.~  - already done in #27273 
![resizable_horizontal](https://user-images.githubusercontent.com/10968348/200072881-0f0cd1f0-0b91-46fa-8d6d-6c72d9ff6a97.jpg)

2. Ability for the log window to be resized.
![resizable_vertical](https://user-images.githubusercontent.com/10968348/200073200-412c9637-d537-4749-8ad0-0fe50a8df6a3.jpg)

3. Would love if the choices stuck between reloads as well.

### Use case/motivation

I love the new grid view and use it day to day to check logs quickly. It would be easier to do so without having to scroll within the text box if you could resize the grid view to accommodate a larger view of the logs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Already done in https://github.com/apache/airflow/pull/27273 but I think they are not sticky between reloads @bbovenzi WDYT?

**Comment by NilsJPWerner** [comment]
Ah I missed that pr. I think that covers 1, but not request 2 or 3.

**Comment by potiuk** [comment]
Marked it as good first issue

**Comment by uranusjr** [comment]
cc @bbovenzi in case you are already working on this

**Comment by NilsJPWerner** [comment]
🙏
