### ISSUE TITLE
(mapped) Task Labels

### ISSUE THREAD

**Issue by fritz-astronomer** [apache/airflow#27511]
### Description

Adding a user defined, small text `label` field to (mapped) task instances, which would appear in the UI

### Use case/motivation

Currently it is difficult to differentiate between mapped tasks in both the `Grid view` and the `Browse > Task Instances` view. It requires a lot of hunting and pecking into either the parent XCOM to find what you need, or individually clicking through the Rendered task view.

It would be helpful to be able to mark tasks with metadata at runtime in some fashion, to distinguish in the UI

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@uranusjr Aren't we planning to add args or some better way to differentiate mapped tasks than just map_index?

**Comment by uranusjr** [comment]
Yes I think there’s already an open issue for this.

**Comment by tirkarthi** [comment]
Possibly a duplicate of https://github.com/apache/airflow/issues/23020 which in turn got closed in favor of https://github.com/apache/airflow/issues/22073

**Comment by fritz-astronomer** [comment]
Closing for https://github.com/apache/airflow/issues/22073 👍
