### ISSUE TITLE
missing volumes for git-sync-ssh-key

### ISSUE THREAD

**Issue by chuxiangfeng** [apache/airflow#27545]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.2

### Kubernetes Version

1.20

### Helm Chart configuration

dags:
  gitSync:
    enabled: true
 persistence:
    enabled: true

### Docker Image customisations

all is office helm-chart images

### What happened

when set gitSync enabled: true and persistence enabled: true for dags, volumes has no name with git-sync-ssh-key, it cause install schedule failed.

### What you think should happen instead

in office document for helm-chart, set both true is enabled, so i think set both true should work good, but it failed.
helm upgrade --install airflow apache-airflow/airflow \
  --set dags.persistence.enabled=true \
  --set dags.gitSync.enabled=true

### How to reproduce

just follow the above question

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Related: https://github.com/apache/airflow/issues/27476

**Comment by ftaib** [comment]
When will the new Helm Chart be available with this changes?
