### ISSUE TITLE
Remove unused attribute (self.using_mysql) from scheduler_job.py

### ISSUE THREAD

**Issue by treyyi** [apache/airflow#27569]
### Apache Airflow version

2.4.2

### What happened

Hi all,

I would like to update the scheduler_job.py script by removing the unused attribute -> `self.using_mysql`.

I understand that `self.using_sqlite` attribute is used to define the variable `async_mode` in scheduler_job.py code, but noticed that `self.using_mysql` is not used.

You can check the code from [scheduler_job.py](https://github.com/apache/airflow/blob/main/airflow/jobs/scheduler_job.py),
```python
def __init__(...):
    # Check what SQL backend we use
    sql_conn: str = conf.get_mandatory_value('database', 'sql_alchemy_conn').lower()
    self.using_sqlite = sql_conn.startswith('sqlite')   # <- only self.using_sqlite is used for async_mode
    self.using_mysql = sql_conn.startswith('mysql')

...

def _execute(self) -> None:
    ...
    async_mode = not self.using_sqlite
```

not sure it was used before, but no longer used for the current scheduler.

If it's not the major change, would you mind me to remove it from the script?

Thanks in advance!

### Operating System

-

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
@TreyYi Thanks, for future there is no need to create an issue for this sort of change, just go straight to creating the PR!
