### ISSUE TITLE
Helm chart tries to patch immutable Job resources on helm upgrade

### ISSUE THREAD

**Issue by calebwoofenden** [apache/airflow#27561]
### Apache Airflow version

2.4.2

### What happened

Running `helm upgrade` with helm hooks disabled in a namespace that already has the chart installed will fail because it's trying to patch a `Job` resource, which is immutable:

```
cannot patch "<release_name>-run-airflow-migrations" with kind Job: Job.batch "<release_name>-run-airflow-migrations" is invalid: spec.template: Invalid value: core.PodTemplateSpec {<...entire json spec of Job resource...>}: field is immutable
```

This happens when helm hooks are disabled on the db migrations job:
```
  migrateDatabaseJob:
    useHelmHooks: false
```

For more detail on why a user would want to do this, see https://github.com/apache/airflow/issues/11979

Copying this from my comment on that issue:

> Kube does offer a parameter called .spec.ttlSecondsAfterFinished that, when specified, will delete the Job after the specified number of seconds after completion (see https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/). This is a pretty good solution, though installs done in a period of time shorter than this value might still run into the same problem.
> 
> The solution I propose here is to set a helm pre-install hook on the database deployment as well as the db migrations, and set the hook weight on the database lower than that of the migrations, so the database will be created first, then the migrations will run, then the webserver and etc. pods will come up. Then I think we could safely remove the wait-for-db-migrations initContainer on the deployments.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunghospark-calm** [comment]
Running into the same problem here.
Had to disable the hooks because migration was not running properly during upgrade, without hooks the followup deployment fails because of the job spec conflict.

**Comment by potiuk** [comment]
Marking as fixed then.

**Comment by alexandermalyga** [comment]
Just tried `applyCustomEnv: false` with `1.8.0rc1` and I'm still getting `cannot patch "run-airflow-migrations" with kind Job ... field is immutable`, so https://github.com/apache/airflow/pull/27148 does not fix this issue.

**Comment by alexandermalyga** [comment]
Just to clarify, #27148 can indeed fix this issue, but it comes with the effect of removing env vars secrets from the migration job, which the job may use to connect to the database. #29314 should be a better fix for this issue.

**Comment by eladkal** [comment]
@alexandermalyga with PR merged this issue is now resolved right?

**Comment by alexandermalyga** [comment]
Yes, it is fixed, but we discussed a follow-up improvement: https://github.com/apache/airflow/pull/29314#pullrequestreview-1295134749
We agreed with @potiuk that it would be done in a separate PR, but I don't have much time to do it right now.

**Comment by alexandermalyga** [comment]
> @alexandermalyga with PR merged this issue is now resolved right?

Yes, it is fixed, but we discussed a follow-up improvement: https://github.com/apache/airflow/pull/29314#pullrequestreview-1295134749
We agreed with @potiuk that it would be done in a separate PR, but I don't have much time to do it right now.

**Comment by eladkal** [comment]
OK so I'm closing this issue as resolved. Please open new issue dedicated to the followup task

**Comment by Throne3d** [comment]
Now ttlSecondsAfterFinished has been added, is the recommended approach still as documented? Reading the thread, it sounds like instead of (as in [the documentation](https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform)):

```yaml
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
```
the recommendation is instead again:
```yaml
createUserJob:
  useHelmHooks: false
migrateDatabaseJob:
  useHelmHooks: false
```
making use of the implicit `ttlSecondsAfterFinished` to drop the jobs between deploys before the next patch comes along and tries to mutate immutable fields.

Should I create a follow-up to update the documentation with this recommendation, and a caveat that deploys < ttlSecondsAfterFinished apart may still trigger the underlying Job mutation issue?
