### ISSUE TITLE
Amazon AppFlow System Test

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27566]
### Description

A Hook and several Operators were added for AppFlow in #24057 but at the time the AIP-47 spec system test infrastructure was just being developed for AWS, so it was decided to just produce an example DAG. Now that AWS system tests are stable in their design, we should circle back and create a system test for AppFlow  

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by igorborgest** [comment]
@o-nikolas I would be happy to contribute here, but I don't have the required time in the next six weeks, so I prefer to not block the task development by now. If it is still open after that, I will be happy to jump in! :)

**Comment by o-nikolas** [comment]
@igorborgest Sounds good, no pressure!

**Comment by potiuk** [comment]
Look like this one is done
