### ISSUE TITLE
Allow for templating of pod-template.yaml at service start time or pod creation

### ISSUE THREAD

**Issue by andscoop** [apache/airflow#27577]
### Description

I've been researching how one can template out the pod-template.yaml.

Airflow provides a few control points for this but none of them seem quite right for our use case
- Helm charts: our k8s environment does not support helm
- pod overrides: called for every pod creation, requires existing defaults and extends some fields instead of overwriting

We're currently "templating" via `sed` find and replace at service start time. This works fine, but it is not as elegant as I think it could be.

### Use case/motivation

Not all kubernetes environments support helm. Additionally, since the K8sExecutor is responsible for pod creation, it should have the ability to render templates closer to pod creation. 

This would allow for a single jinja templated `pod-template.yaml` file to be reused across multiple pipeline clusters or in multi-cluster deployments environments. 

If I am missing something, please point me in the right direction.

Thanks!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You have not explained "WHEN" the pod_template would change. From what I understand, you want to do it at service deployment time. And seems this is what you want to do - either on service deployment time or based on some manually triggered  event (which would be some kind of event reconfiguring the whole cluster). What you really need is a solution for your deployment not "airflow feature".

What I think you shuld do is to simply use whatever k8s already provides - you are really talking about config map that will be mounted as your pod_template_file:  https://kubernetes.io/docs/concepts/storage/volumes/#configmap

You can mount this config map as a volume/folder available for all pods that need them and then you can use absolutely standard k8s mechanism to apply any changes to it (kubectl apply) including pre-processing it via jinja as you wish (you do not need sed, you can simply use jinja2 CLI for that https://pypi.org/project/jinja2-cli/

Converting it into discussion, but I suggest you try this first and see if you can make it works.
