### ISSUE TITLE
To make airflow UI interactive

### ISSUE THREAD

**Issue by saicharita** [apache/airflow#27575]
### Description

Hi, 

Is it possible to make the DAG UI interactive where you can change the order of task flow as we wanted instead of going back to the code every time and making changes to it?

### Use case/motivation

So we have around 75 odd jobs running on server which we are trying to migrate to airflow. Because that is a lot of jobs on a single DAG, we would like to keep changing the order in which each task is being executed depending on our resource and data availability at that particular time. Hence, it would be great if the UI is interactive and we can make changes in the front rather than updating the code every time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Everything is possible, but this is not something we aim to do in near future. The DAG code and the web server are isolated from each other, and if you are able to modify DAGs in the web UI, it opens the possibility for anyone with access to the UI to be able to run arbitrary code on your server, which is an atack vector Airflow tries to avoid.

**Comment by tirkarthi** [comment]
> Is it possible to make the DAG UI interactive where you can change the order of task flow as we wanted instead of going back to the code every time and making changes to it?

I guess modifying workflow from UI needs to update DAG code, serialized dags, etc. and goes against the https://airflow.apache.org/docs/apache-airflow/stable/#workflows-as-code . This looks similar to https://github.com/apache/airflow/issues/27164

**Comment by potiuk** [comment]
> I guess modifying workflow from UI needs to update DAG code, serialized dags, etc. and goes against the https://airflow.apache.org/docs/apache-airflow/stable/#workflows-as-code . This looks similar to #27164

Yeah. I re-read itl @tirkarthi. I thought the change is about changing the order of tasks DISPLAYED in the UI in the grid view - as It can be easily done as UI-only change. 

Indeed, changing "execution" sequence via UI is something that currently falls outside of the scope of Airflow and it is "won't do" case.
