### ISSUE TITLE
Mapped tasks get stuck in restarting state and cause http 500 errors

### ISSUE THREAD

**Issue by nickroci** [apache/airflow#27617]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version 2.4.1 Mapped tasks got stuck in restarting state after retrying. This also caused the ui to break with http server returning 500 errors - "restarting is not one of [success...." there is also no way I could find to mark those restarting tasks as failed/clear them. Didn't look like celery workers were trying to do anything with the tasks either.

I wonder if it's related to mapped tasks + retry, task config didn't work as I expected and I had to set retry with default_args into pythonoperator.partial 

### What you think should happen instead

Should try running the tasks

### How to reproduce

Not sure what exactly caused this as it retries OK 99 percent of the time

### Operating System

Python 3.9 slim buster

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Please provide steps to reliably reproduce this.

**Comment by tirkarthi** [comment]
restarting was added to TaskState Enum in af368243f87dfb5a4bc98a571d7b4775186d214c (Airflow version 2.4.2)

**Comment by nickpholden** [comment]
OK thanks I'll upgrade and report back

**Comment by potiuk** [comment]
Closing provisionally until the user reports otherwise.

**Comment by nickpholden** [comment]
After testing on the most recent version I see tasks getting stuck in queued state. Possibly related to retries/unstable network conditions
