### ISSUE TITLE
[Chart] Container security context is not defined

### ISSUE THREAD

**Issue by NipunaPrashan** [apache/airflow#27612]
### Apache Airflow version

main (development)

### What happened

Container security context is not defined to change through values yaml. This is a **security** issue for containers. 

https://github.com/apache/airflow/blob/main/chart/templates/triggerer/triggerer-deployment.yaml

### What you think should happen instead

Include securitContext block under containers section and allow to change from values yaml.

### How to reproduce

Run azure security compliance checks to identify the issues with the containers.
`Kubernetes clusters should not allow container privilege escalation `

### Operating System

N/A

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
This is coming (soon!) in #24588.

**Comment by mikaeld** [comment]
Hey! Any news on getting https://github.com/apache/airflow/pull/24588 in `1.9.0`? I was about to start implementing this exact feature when I found this PR

**Comment by potiuk** [comment]
@mikaeld - if you want #24588 to be merged, make sure it passes the tests first - author can do it if pinged, or you can take over. Passing tests is the prerequisite we look at it.
