### ISSUE TITLE
KubernetesPodOperator - Applying core Airflow settings from section [kubernetes] with the following keys

### ISSUE THREAD

**Issue by skvsree** [apache/airflow#27619]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are receiving below warning in version 2.4.0 of airflow while using celery executor + KubernetesPodOperator .  We are using in_cluster as True as we are running in AKS.  We tried fixing it by adding cluster_context and config_file to DAG file.  Now we got error as config_file and in_cluster as mutually exclusive.

Does this mean in_cluster=True is being deprecated. It is challenging to get a kubeconfig file within a pod and maintain its validity.

It also means that we need to give context name which might change in each environment and dags need to be versioned for each environment.
```
DeprecationWarning:
Applying core Airflow settings from section [kubernetes] with the following keys:
cluster_context='<context>'
config_file='/root/.kube/config'
In a future release, KubernetesPodOperator will no longer consider core
Airflow settings; define an Airflow connection instead.
```

### What you think should happen instead

When in_cluster is true make cluster_context and config_file as optional.

### How to reproduce

In a airflow hosted inside k8s try using KubernetesPodOperator with in_cluster as true.  This should raise the warning.

### Operating System

ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
This means that you should configure the Kubernetes credentials information using [Connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html), not the Airflow configuration. Here is docs about Kubernetes connection: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/connections/kubernetes.html

**Comment by skvsree** [comment]
The first line of the article says,  They are not used by KubernetesPodOperator tasks.
