### ISSUE TITLE
Bug in REST API

### ISSUE THREAD

**Issue by ikucan** [apache/airflow#27620]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

In version v2.3.3.... (apologies if this has been fixed since)

The clear tasks on a DAG endpoint rejects the _include_subdags_ param. Odd as it works on the UI and the CLI also...

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_clear_task_instances

this is my post data:

cmd = {
    "dry_run": True,
    "task_ids": [
        "First--Split-instrument-data-by-dealer",
        "Second--Split-instrument-data-by-clearing-house",
        "Filter-quotes",
        "Build-CME-books",
        "Build-LCH-books",
        "Compute-stream-metrics-for-CME-instruments",
        "Compute-stream-metrics-for-LCH-instruments",
    ],
    "only_failed": False,
    "start_date": "2022-11-02T00:00:00.000Z",
    "end_date": "2022-11-03T00:00:00.000Z",
    "reset_dag_runs": True,
    "include_downstream": True,
    }

running this, i get the error :

{
'detail': "{'include_downstream': ['Unknown field.']}",
 'status': 400,
 'title': 'Bad Request',
 'type': 'https://airflow.apache.org/docs/apache-airflow/2.3.3/stable-rest-api-ref.html#section/Errors/BadRequest'
}

if i only remove thet "include_downstream":True entry, it works fine. (200, clears task etc...)

### What you think should happen instead

I expect behaviour eqivalent to the behaviour when a task is cleared in the UI with the _downstream_ option enabled

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

running on k8s

### Anything else

every time. this seems to be a straightforward issue?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
It seems this field was only added to API in https://github.com/apache/airflow/commit/eceb4cc5888a7cf86a9250fff001fede2d6aba0f discussed in issue https://github.com/apache/airflow/issues/23227 (Merged in version 2.4.0 and above) though it was present in cli and webserver. Can you please try the payload with 2.4.0 and above?

**Comment by potiuk** [comment]
Closing provisionally - we can always re-open it after the user comes back after checking that this is still an issue.
