### ISSUE TITLE
Allow global volume & volumeMounts in Helm chart

### ISSUE THREAD

**Issue by csp33** [apache/airflow#27687]
### Description

I think we should add this option to avoid repeating the declaration in all the component's subsections.
It would be something similar to `env`

### Use case/motivation

Avoid repeating volume & volumeMounts along all components

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
If you have a feature you want to work on you can raise PR directly. no need to open issue first :)
