### ISSUE TITLE
More Information on Working with Airflow Scheduler

### ISSUE THREAD

**Issue by alybel** [apache/airflow#277]
Several questions came up when we were exploring Airflow and I believe this could also be of interest to others and might be part of a later version of the documentation. 

1) what is the proper way to terminate the scheduler
a) for all running dags
b) for specific running dags
2) what is the proper way to restart the scheduler 
a) for all running dags
b) for specific running dags

**Comment by mistercrunch** [comment]
There's a new toggle on the latest version of the UI that looks like this:
![screen shot 2015-08-17 at 10 28 19 am](https://cloud.githubusercontent.com/assets/487433/9388803/a660e096-471c-11e5-8932-dc077e955417.png)

In older version there was a pause checkbox when clicking the magnifying glass by your DAG in the my page.

You can also kill the scheduler process SIGTERM / SIGINT , the state is stored in the metadata database so it's ok.

It could be nice to have some master toggle switch, but it's typically something that never happens here expect when we do major infrastructure migrations and then I'll just kill the scheduler manually.
