### ISSUE TITLE
Add pre-commit rule to validate using `urlsplit` rather than `urlparse`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#27715]
### Body

Originally suggested in https://github.com/apache/airflow/pull/27389#issuecomment-1297252026

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Arvind2222** [comment]
I am checking this @eladkal

**Comment by KUNDAN1334** [comment]
plz assigned this to me

**Comment by KUNDAN1334** [comment]
plz guide me in which file i have to make changes
