### ISSUE TITLE
Different output data formats for macros {{ ts }} depending on time

### ISSUE THREAD

**Issue by andreitsukanov** [apache/airflow#27777]
### Apache Airflow version

2.4.3

### What happened

In the case when the DAG starts at the moment when the number of milliseconds is 0, 
then {{ ts }} macros the time format is %Y-%m-%dT%H:%M:%S%z
in the case when the number of milliseconds is not equal to 0, 
the time format is %Y-%m-%dT%H:%M:%S.%f%z

Therefore it breaks work with macro `macros.ds_format`

### What you think should happen instead

The case when the number of milliseconds is equal to 0, should be in the time format %Y-%m-%dT%H:%M:%S.%f%z

### How to reproduce

1. Create DAG with only one BashOperator
```
bash_task = BashOperator(
    task_id="bash_task",
    bash_command='echo "Here is the message: {{ macros.ds_format(ts, '"%Y-%m-%dT%H:%M:%S.%f%z'", '"%Y/%m/%d/%H'") }}"',
)
```
2. Create DAG with schedule each ten(for example) minutes 
3. Run DAG manual at an arbitrary point in time

### Operating System

macOs 12.6

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
This is unlikely a bug of Airflow it is how builtin [datetime.isoformat()](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) works.

I would recommend [format](https://pendulum.eustace.io/docs/#formatter) `logical_date` instead of use `macros.ds_format`

```python
    bash_task = BashOperator(
        task_id="bash_task",
        bash_command="""echo "Here is the message: {{ logical_date.format('YYYY/MM/DD/HH') }}" """,
    )
```
