### ISSUE TITLE
Apache not found in providers folder 

### ISSUE THREAD

**Issue by erosons** [apache/airflow#27788]
### Apache Airflow version

2.4.3

### What happened

After installing the providers package , I restarted my instance of airflow, I  was able to setup the spark connections  but  my dag sparksubmit operator cannot find the apache . spark folder path in the airflow provider path

Broken DAG: [/opt/airflow/dags/sparkSubmitPerMeter.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/sparkSubmitPerMeter.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'

Here is my code based

```
from airflow.models.dag import DAG
from datetime import datetime, timedelta
#from airflow.providers.apache.spark.operators.spark_sql import SparkSqlOperator
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
#from airflow.contrib.operators.spark_submit_operator import SparkSubmitOperator

default_args = {
    'owner': 'samson',
    'start_date': datetime(2022, 8, 20),
    'retries':2,
    'retry_delay': timedelta(hours=1),
}
with DAG('ETL_sparkSubmitOperatorV1',
                  default_args=default_args,
                  schedule_interval='@daily',
                  tags=["SparkSubmitTest"],
                  catchup=False

                ) as dag:

    # spark = SparkSession(SparkContext(conf=SparkConf()).getOrCreate())

    SparkSubmitOps= SparkSubmitOperator(
        task_id='sparkSubmitOps',
        conn_id='Spark-Conn',
        application="/opt/airflow/dags/amperon/sparkPerMeterLTF.py",
        total_executor_cores=3,
        executor_memory="2G",
        executor_cores=1,
        driver_memory="2G",
        num_executors=6,
        env_vars=None,
        dag=dag
    )

    SparkSubmitOps
~
```
~
~

### Operating System

Debian

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-spark 4.0.0

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
Can you describe how you installed the spark provider? And if you still have it paste the output you got.

**Comment by erosons** [comment]
I did docker exec it <containerID> bash  into the airflow webserver
container and run the pip install apache-airflow-providers-apache-spark

Thank you
Samson

**Comment by Taragolis** [comment]
Due to information that you provided you only install additional packages into webserver container after started it however you need to install into all of containers/services (at least scheduler/worker).

This is not a bug of Airflow. I would suggest install packages during build image based on airflow image or customise airflow image.

Links below might help you:
- https://airflow.apache.org/docs/docker-stack/build.html#building-the-image
- https://airflow.apache.org/docs/docker-stack/build.html#customizing-the-image
