### ISSUE TITLE
werkzeug.routing.BuildError: Could not build url for endpoint 'Airflow.legacy_graph'. Did you mean 'Airflow.graph' instead?

### ISSUE THREAD

**Issue by amit151993** [apache/airflow#27815]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    Use a ``with`` block to push the context, which will make
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    generate. If this starts with a ``.``, the current blueprint
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    except Exception as e:
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    the scheme and domain, like ``https://example.com/hello``. When
  File "/usr/local/lib/python3.8/site-packages/airflow/www/auth.py", line 51, in decorated
    'airflow/no_roles_permissions.html',
  File "/usr/local/lib/python3.8/site-packages/airflow/www/views.py", line 695, in index
    ) in user_permissions
  File "/usr/local/lib/python3.8/site-packages/airflow/www/views.py", line 477, in render_template
    return (
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 287, in render_template
    for attr_name in dir(self):
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    **context: t.Any
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    if loader is not None:
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    template_class: t.Optional[t.Type["Template"]] = None,
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    zipfile.
TypeError: reraise() argument after * must be an iterable, not BuildError
```

### How to reproduce
Installed airflow SSH operator using the below command and scheduled sample DAGs.
**pip install apache-airflow-providers-ssh**

And after restart of the Airflow Instance, getting mentioned error.

### Operating System

Linux

### Versions of Apache Airflow Providers

airflow 2.2.0 version

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Please provide information as requested by the issue template, otherwise there is no way to identify the issue.

**Comment by amit151993** [comment]
@underyx , I'm not using any custom flask template in the DAGs.

Below are the default flask templates at the location /usr/local/lib/python3.8/site-packages/flask/templating.py

import typing as t

from jinja2 import BaseLoader
from jinja2 import Environment as BaseEnvironment
from jinja2 import Template
from jinja2 import TemplateNotFound

from .globals import _cv_app
from .globals import _cv_request
from .globals import current_app
from .globals import request
from .helpers import stream_with_context
from .signals import before_render_template
from .signals import template_rendered

if t.TYPE_CHECKING:  # pragma: no cover
    from .app import Flask
    from .scaffold import Scaffold


def _default_template_ctx_processor() -> t.Dict[str, t.Any]:
    """Default template context processor.  Injects `request`,
    `session` and `g`.
    """
    appctx = _cv_app.get(None)
    reqctx = _cv_request.get(None)
    rv: t.Dict[str, t.Any] = {}
    if appctx is not None:
        rv["g"] = appctx.g
    if reqctx is not None:
        rv["request"] = reqctx.request
        rv["session"] = reqctx.session
    return rv


class Environment(BaseEnvironment):
    """Works like a regular Jinja2 environment but has some additional
    knowledge of how Flask's blueprint works so that it can prepend the
    name of the blueprint to referenced templates if necessary.
    """

    def __init__(self, app: "Flask", **options: t.Any) -> None:
        if "loader" not in options:
            options["loader"] = app.create_global_jinja_loader()
        BaseEnvironment.__init__(self, **options)
        self.app = app


class DispatchingJinjaLoader(BaseLoader):
    """A loader that looks for templates in the application and all
    the blueprint folders.
    """

    def __init__(self, app: "Flask") -> None:
        self.app = app

    def get_source(  # type: ignore
        self, environment: Environment, template: str
    ) -> t.Tuple[str, t.Optional[str], t.Optional[t.Callable]]:
        if self.app.config["EXPLAIN_TEMPLATE_LOADING"]:
            return self._get_source_explained(environment, template)
        return self._get_source_fast(environment, template)

    def _get_source_explained(
        self, environment: Environment, template: str
    ) -> t.Tuple[str, t.Optional[str], t.Optional[t.Callable]]:
        attempts = []
        rv: t.Optional[t.Tuple[str, t.Optional[str], t.Optional[t.Callable[[], bool]]]]
        trv: t.Optional[
            t.Tuple[str, t.Optional[str], t.Optional[t.Callable[[], bool]]]
        ] = None

        for srcobj, loader in self._iter_loaders(template):
            try:
                rv = loader.get_source(environment, template)
                if trv is None:
                    trv = rv
            except TemplateNotFound:
                rv = None
            attempts.append((loader, srcobj, rv))

        from .debughelpers import explain_template_loading_attempts

        explain_template_loading_attempts(self.app, template, attempts)

        if trv is not None:
            return trv
        raise TemplateNotFound(template)

    def _get_source_fast(
        self, environment: Environment, template: str
    ) -> t.Tuple[str, t.Optional[str], t.Optional[t.Callable]]:
        for _srcobj, loader in self._iter_loaders(template):
            try:
                return loader.get_source(environment, template)
            except TemplateNotFound:
                continue
        raise TemplateNotFound(template)

    def _iter_loaders(
        self, template: str
    ) -> t.Generator[t.Tuple["Scaffold", BaseLoader], None, None]:
        loader = self.app.jinja_loader
        if loader is not None:
            yield self.app, loader

        for blueprint in self.app.iter_blueprints():
            loader = blueprint.jinja_loader
            if loader is not None:
                yield blueprint, loader

    def list_templates(self) -> t.List[str]:
        result = set()
        loader = self.app.jinja_loader
        if loader is not None:
            result.update(loader.list_templates())

        for blueprint in self.app.iter_blueprints():
            loader = blueprint.jinja_loader
            if loader is not None:
                for template in loader.list_templates():
                    result.add(template)

        return list(result)


def _render(app: "Flask", template: Template, context: t.Dict[str, t.Any]) -> str:
    app.update_template_context(context)
    before_render_template.send(app, template=template, context=context)
    rv = template.render(context)
    template_rendered.send(app, template=template, context=context)
    return rv


def render_template(
    template_name_or_list: t.Union[str, Template, t.List[t.Union[str, Template]]],
    **context: t.Any
) -> str:
    """Render a template by name with the given context.

    :param template_name_or_list: The name of the template to render. If
        a list is given, the first name to exist will be rendered.
    :param context: The variables to make available in the template.
    """
    app = current_app._get_current_object()  # type: ignore[attr-defined]
    template = app.jinja_env.get_or_select_template(template_name_or_list)
    return _render(app, template, context)


def render_template_string(source: str, **context: t.Any) -> str:
    """Render a template from the given source string with the given
    context.

    :param source: The source code of the template to render.
    :param context: The variables to make available in the template.
    """
    app = current_app._get_current_object()  # type: ignore[attr-defined]
    template = app.jinja_env.from_string(source)
    return _render(app, template, context)


def _stream(
    app: "Flask", template: Template, context: t.Dict[str, t.Any]
) -> t.Iterator[str]:
    app.update_template_context(context)
    before_render_template.send(app, template=template, context=context)

    def generate() -> t.Iterator[str]:
        yield from template.generate(context)
        template_rendered.send(app, template=template, context=context)

    rv = generate()

    # If a request context is active, keep it while generating.
    if request:
        rv = stream_with_context(rv)

    return rv


def stream_template(
    template_name_or_list: t.Union[str, Template, t.List[t.Union[str, Template]]],
    **context: t.Any
) -> t.Iterator[str]:
    """Render a template by name with the given context as a stream.
    This returns an iterator of strings, which can be used as a
    streaming response from a view.

    :param template_name_or_list: The name of the template to render. If
        a list is given, the first name to exist will be rendered.
    :param context: The variables to make available in the template.

    .. versionadded:: 2.2
    """
    app = current_app._get_current_object()  # type: ignore[attr-defined]
    template = app.jinja_env.get_or_select_template(template_name_or_list)
    return _stream(app, template, context)


def stream_template_string(source: str, **context: t.Any) -> t.Iterator[str]:
    """Render a template from the given source string with the given
    context as a stream. This returns an iterator of strings, which can
    be used as a streaming response from a view.

    :param source: The source code of the template to render.
    :param context: The variables to make available in the template.

    .. versionadded:: 2.2
    """
    app = current_app._get_current_object()  # type: ignore[attr-defined]
    template = app.jinja_env.from_string(source)
    return _stream(app, template, context)

**Comment by amit151993** [comment]
As of now, there are no DAGs scheduled in Airflow, I removed all of the DAGs and restarted the Airflow Instance, still seeing the same issue.

**Comment by ephraimbuddy** [comment]
@amit151993 @uranusjr is asking you to follow the issue template here. You omitted 'how to reproduce' in the issue template. Can you answer that? How can we reproduce your issue

**Comment by amit151993** [comment]
@ephraimbuddy I have included a temple for how to reproduce errors. Let me know, if it will require more information.

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy I have included a temple for how to reproduce errors. Let me know, if it will require more information.

What version of airflow?

**Comment by amit151993** [comment]
> > @ephraimbuddy I have included a temple for how to reproduce errors. Let me know, if it will require more information.
> 
> What version of airflow?

airflow 2.2.0  version

**Comment by potiuk** [comment]
Upgrade to latest.

**Comment by potiuk** [comment]
Converting to discussion until @amit151993 rechecks this in latest version of airflow. I believe the problem was caused by conflict of depdendencies. @amit151993 - make sure when you upgrade to follow https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html and use constraints to install airlfow (this is the only official/supported version to install airflow);
