### ISSUE TITLE
Add  s3 object get

### ISSUE THREAD

**Issue by Lee2532** [apache/airflow#27811]
### Description

The s3 operator has a create object and a List keys operator, but it does not have the ability to import a single object (key).
We added the ability to import a single object.

### Use case/motivation

I want to add a function to read a single file stored in s3 on memory without saving it locally.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
As per the discussion in #27812, should we close this one?
