### ISSUE TITLE
GCSToBigQueryOperator no longer uses field_delimiter or time_partitioning

### ISSUE THREAD

**Issue by mdering** [apache/airflow#27842]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

google=8.5.0

### Apache Airflow version

2.4.3

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other Docker-based deployment

### What happened

The newest version of the google providers no longer provides the `field_delimiter` or `time_partitioning` fields to the bq job configuration for the GCStoBQ transfers. Looking at the code it seems like this behavior was removed during the change to use deferrable operations

### What you think should happen instead

These fields should continue to be provided

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Wolff-Lucas** [comment]
I have the same issues with the 8.0.5.
