### ISSUE TITLE
Getting 404 when clicking on download logs button 

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#27883]
### Apache Airflow version

main (development)

### What happened

Getting 404 when clicking on download logs button for empty operator or mapped task group.

![2022-11-24 14 08 23](https://user-images.githubusercontent.com/88504849/203733537-747b9771-53e9-4438-8e76-09fc6b927ec2.gif)

Logs url- 
```
http://localhost:8080/get_logs_with_metadata?dag_id=taskmap_taskgroup&task_id=done&execution_date=2022-11-24T06%3A33%3A47.847619%2B00%3A00&map_index=-1&format=file&try_number=1
```

### What you think should happen instead

It should download the logs 

### How to reproduce

Run any dag with mapped taskgroup or empty operator 
DAG-
```
from datetime import datetime

from airflow import DAG
from airflow.decorators import task, task_group
from airflow.operators.empty import EmptyOperator

with DAG(
    dag_id="taskmap_taskgroup",
    tags=["AIP_42"],
    start_date=datetime(1970, 1, 1),
    schedule=None,
) as dag:

    @task
    def hi():
        print("hi")
    @task
    def hello_there(arg):
        print(arg)

    @task_group
    def tg(x):
        hello_there(x)

    hi()>> tg.expand(x=["a", "b", "c"]) >> EmptyOperator(task_id="done")
```

### Operating System

mac os

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jyotsa09** [comment]
cc @bbovenzi

**Comment by bbovenzi** [comment]
Looks like the logs are not loading either. We should catch that error, display it and disable the download button.
