### ISSUE TITLE
Unable to see mapped task group information on UI 

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#27880]
### Apache Airflow version

main (development)

### What happened

UI is looking like a normal task group one even if the dag has mapped task group in it.

<img width="1352" alt="Screenshot 2022-11-24 at 12 01 12 PM" src="https://user-images.githubusercontent.com/88504849/203717544-572fd615-d03f-43ab-9592-e695952edbfd.png">

### What you think should happen instead

UI should show the mapped task group details and all the mapped task group attached in it.

### How to reproduce

Run a dag with mapped task group and observe the UI -
```
from datetime import datetime

from airflow import DAG
from airflow.decorators import task, task_group
from airflow.operators.empty import EmptyOperator

with DAG(
    dag_id="taskmap_taskgroup",
    tags=["AIP_42"],
    start_date=datetime(1970, 1, 1),
    schedule=None,
) as dag:

    @task
    def hello_there(arg):
        print(arg)

    @task_group
    def tg(x):
        hello_there(x)

    tg.expand(x=[1]) >> EmptyOperator(task_id="done")
```

### Operating System

mac os

### Deployment

Virtualenv installation

### Anything else

Also logs are missing for the task which is inside the task group.
Log url looks like- 
http://localhost:8080/get_logs_with_metadata?dag_id=taskmap_taskgroup&task_id=tg.hello_there&execution_date=2022-11-24T06%3A33%3A47.847619%2B00%3A00&map_index=-1&format=file&try_number=1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Fixed by: https://github.com/apache/airflow/pull/28208
