### ISSUE TITLE
Password is not masked in audit logs for connections/variables

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#27907]
### Apache Airflow version

main (development)

### What happened

Password for connections and variables with secret in the name are not masked in audit logs.
<img width="1337" alt="Screenshot 2022-11-25 at 12 58 59 PM" src="https://user-images.githubusercontent.com/88504849/203932123-c47fd66f-8e63-4bc6-9bf1-b9395cb26675.png">
<img width="1352" alt="Screenshot 2022-11-25 at 12 56 32 PM" src="https://user-images.githubusercontent.com/88504849/203932220-3f02984c-94b5-4773-8767-6f19cb0ceff0.png">
<img width="1328" alt="Screenshot 2022-11-25 at 1 43 40 PM" src="https://user-images.githubusercontent.com/88504849/203933183-e97b2358-9414-45c8-ab8f-d2f913117301.png">

### What you think should happen instead

Password/value should be masked

### How to reproduce

1. Create a connection or variable(with secret in the name i.e. test_secret)
2. Open audit logs 
3. Observe the password

### Operating System

mac os

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
This looks like the fix:
```diff

diff --git a/airflow/www/decorators.py b/airflow/www/decorators.py
index 079c91fdfa..16a886098b 100644
--- a/airflow/www/decorators.py
+++ b/airflow/www/decorators.py
@@ -30,6 +30,7 @@ from pendulum.parsing.exceptions import ParserError
 
 from airflow.models import Log
 from airflow.utils.session import create_session
+from airflow.utils.log import secrets_masker
 
 T = TypeVar("T", bound=Callable)
 
@@ -56,6 +57,7 @@ def action_logging(func: Callable | None = None, event: str | None = None) -> Ca
                     for k, v in chain(request.values.items(multi=True), request.view_args.items())
                     if k not in fields_skip_logging
                 ]
+                extra_fields = [(k, '****') if secrets_masker.should_hide_value_for_key(k) else (k, v) for k, v in extra_fields]
 
                 params = {k: v for k, v in chain(request.values.items(), request.view_args.items())}
```
