### ISSUE TITLE
HdfsSensor has no clear failure mode

### ISSUE THREAD

**Issue by pulquero** [apache/airflow#27902]
### Description

Currently, HdfsSensor pings forever if some failure causes the file not to be written. Some sort of timeout parameter would be nice.

### Use case/motivation

If there is a failure earlier in the pipeline that prevents the file of interest being written, HdfsSensor just pings forever, and everything looks fine. I would like some sort of way to have HdfsSensor fail, so that my team can detect issues promptly and address them.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
all sensor has a `timeout` parameter, did you try to use that?

**Comment by pulquero** [comment]
No, I didn't, I just looked at the parameters doc-ed here https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/_api/airflow/providers/apache/hdfs/sensors/hdfs/index.html#airflow.providers.apache.hdfs.sensors.hdfs.HdfsSensor and completely overlooked **kwargs. Thanks, that'll probably do it.
