### ISSUE TITLE
AIP-51 - Local Executor Compatibility

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27928]
### Overview
Executors that run locally have certain limitations and requirements, many of which are currently hardcoded in core Airflow code. To add a new Executor, that would run locally, one would be required to change this core Airflow code.
### Examples
- **1a**) Whether or not to start the serve_logs sub-process, currently hardcoded to LocalExecutor and SequentialExecutor: https://github.com/apache/airflow/blob/27e2101f6ee5567b2843cbccf1dca0b0e7c96186/airflow/cli/commands/scheduler_command.py#L93
- **1b**) When running in standalone mode, asserts a local Executor is being used, currently hardcoded to LocalExecutor and SequentialExecutor: https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/cli/commands/standalone_command.py#L156-L158
- **1c**) Local Executors need a copy of Airflow configuration created in tmp, currently hardcoded to LocalExecutor and SequentialExecutor: https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/jobs/backfill_job.py#L505-L509
### Proposal
A static method or attribute on the Executor class which can be checked by core code.

There is a precedent already set with the `supports_ad_hoc_ti_run` attribute, see:
https://github.com/apache/airflow/blob/fb741fd87254e235f99d7d67e558dafad601f253/airflow/executors/kubernetes_executor.py#L435 https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/www/views.py#L1735-L1737

**Comment by pierrejeambrun** [comment]
Would like to help on this one, assigning myself :)

**Comment by snjypl** [comment]
@pierrejeambrun , i faced an issue with the `LocalKubernetesExecutor`  https://github.com/apache/airflow/pull/28638
the scheduler command is not starting the serve_logs process for `LocalKubernetesExecutor`. 

i think, `is_local` should be set to `True` for `LocalKubernetesExecutor`.  

if you get a chance, you please review the PR.
