### ISSUE TITLE
AIP-51 - Add More Details to Docs re Writing Custom Executors

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27934]
There is some documentation [here](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html) for Executors with a very small explanation on how to provide a path to a custom executor class.
However, it would be nice to add more pointers, tips and tricks around building custom Executors. Specifically around the importance of inheriting the Airflow BaseExecutor interface as well as what knobs are available from the BaseExecutor interface.

**Comment by Bowrna** [comment]
@o-nikolas Could i check this issue if its still open?

**Comment by o-nikolas** [comment]
Hey @Bowrna, I just finished one of the last AIP-51 development tasks and was planning on doing this one next. Let's definitely collaborate though! I'll be sure to tag you on the PR 😀

**Comment by o-nikolas** [comment]
Requested in #33146
