### ISSUE TITLE
AIP-51 - Misc. Compatibility Checks

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27930]
### Overview

Coupling around other compatibility checks, similar to coupling 1 and 2, but which don't fall into either category.

### Examples
- **3a**) Some Executors support pickling, some don’t, there is logic in both backfill and scheduler jobs that checks before submitting tasks to the Executor queue. Applies to DaskExecutor, LocalExecutor and SequentialExecutor as of now: https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/jobs/backfill_job.py#L825-L829 https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/jobs/scheduler_job.py#L703-L704
- **3b**) Sentry has a celery integration, if the Executor is Celery, the Sentry integration is imported and configured: https://github.com/apache/airflow/blob/27e2101f6ee5567b2843cbccf1dca0b0e7c96186/airflow/sentry.py#L87
  - Sentry at the moment only supports Celery, so this particular coupling is low priority, but should still be fixed.

### Proposal
A static method or attribute on the Executor class which can be checked by core code.

There is a precedent already set with the `supports_ad_hoc_ti_run` attribute, see:
https://github.com/apache/airflow/blob/fb741fd87254e235f99d7d67e558dafad601f253/airflow/executors/kubernetes_executor.py#L435 https://github.com/apache/airflow/blob/26f94c5370587f73ebd935cecf208c6a36bdf9b6/airflow/www/views.py#L1735-L1737

**Comment by rkarish** [comment]
Hey Niko, I'll take this ticket if it's still available.

**Comment by potiuk** [comment]
Assigned you

**Comment by o-nikolas** [comment]
Thanks for taking this one @rkarish! Ping me if you need any guidance :smile:

**Comment by rkarish** [comment]
Excited to get started on this tonight. The ticket is scoped out really well and I was planning on using pierrejeambrun's PR as inspiration for this one since it seems very similar. I will reach out if I need any guidance. Thanks Niko!

**Comment by o-nikolas** [comment]
> The ticket is scoped out really well and I was planning on using pierrejeambrun's PR as inspiration for this one since it seems very similar.

Glad to hear that! I tried to put a good amount of context in the issues to make them easy to start :smile:

**Comment by rkarish** [comment]
Hey Niko! I've opened a PR for this task that covers 3a and 3b. Looking forward to getting some feedback on this.
