### ISSUE TITLE
AIP-51 - Executor Coupling in Logging

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27931]
### Overview
The FileTaskHandler logging class has a special branch for Kubernetes, to fetch logs from the pod (Note: this is currently hardcoded to KubernetesExecutor so this would fail to run for the CeleryKubernetesExecutor or LocalKubernetesExecutor).
### Examples
- **4a**) See code: https://github.com/apache/airflow/blob/27e2101f6ee5567b2843cbccf1dca0b0e7c96186/airflow/utils/log/file_task_handler.py#L157-L192
### Proposal
Adding a `get_task_logs(ti: TaskInstance | None)` method on the `BaseExecutor` class, which Executor subclasses could implement is one viable approach, since other Executors could certainly make use of such a paradigm, particularly containerized or cloud based executors.

**Comment by snjypl** [comment]
@o-nikolas  if you don't mind, i would like to contribute to this task.

**Comment by o-nikolas** [comment]
> @o-nikolas if you don't mind, i would like to contribute to this task.

Absolutely, I have assigned it to you! Let me know if you need any more help or details

**Comment by snjypl** [comment]
@o-nikolas  i have opened a PR https://github.com/apache/airflow/pull/28161 with some quick changes to check if i understand the requirement correctly.
