### ISSUE TITLE
Latest log not shown in grid view for deferred task

### ISSUE THREAD

**Issue by tanelk** [apache/airflow#27955]
### Apache Airflow version

2.4.3

### What happened

In the grid view I do not see the logs for the latest try number if the task is in deferred state. I do see it in the "old" log view.

Grid view:
![image](https://user-images.githubusercontent.com/3342974/204215464-989e70e3-9dfc-490b-908c-f47f491316d5.png)

"Old" view:
![image](https://user-images.githubusercontent.com/3342974/204215513-05a6b0ac-f3da-44fa-b8c2-e31013e2467c.png)

It could have something to do with the deferred task getting its try_number reduced by 1 - in my example try_number=1 and next_try_number=2.

https://github.com/apache/airflow/blob/3e288abd0bc3e5788dcd7f6d9f6bef26ec4c7281/airflow/models/taskinstance.py#L1617-L1618

### Operating System

Red Hat

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tanelk** [comment]
@bbovenzi, you probably know the best how to handle this.

**Comment by bbovenzi** [comment]
Yeah, there's an issue with the try number. I tried to fix it in https://github.com/apache/airflow/pull/26993 but I should go back and find a better solution.
