### ISSUE TITLE
Cancel a step created from EmrAddStepsOperator

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27979]
### Description

Support an EMR operator for cancelling jobs/steps.
Created from the following Github Discussion: https://github.com/apache/airflow/discussions/27959

### Related issues

#27959

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked as good first issue.

**Comment by swapz-z** [comment]
@o-nikolas 
I Would love to take this up and come back with a possible implementation.
Could you assign this issue to me ?
Thanks

**Comment by o-nikolas** [comment]
> @o-nikolas I Would love to take this up and come back with a possible implementation. Could you assign this issue to me ? Thanks

Fantastic! I've assigned to you. Let me know if you need any help/guidance on it :smiley:

**Comment by swapz-z** [comment]
I will definitely come back soon 
And thanks for the opportunity :)

**Comment by o-nikolas** [comment]
> @o-nikolas
> 
> Few questions regarding the approach Being an operator, this would involve coupling it with each of possibly hundreds of steps and thus hardly find any use case, when actually we just wanted to stop the existing running/pending step and do a new addstep of the same step name ( However, we can still implement this Operator )
> 
> I was thinking, we could emulate the Clear functionality on this Operator :
> 
>     1. Call clear on this operator -> With an extra parameter in the `EmrAddStepsOperator` as `cancel_step_when_cleared` boolean which clears the existing step and adds a new step ( works as  a retrigger ) whenever  clear is called on this operator and acts as a normal `EmrAddStepsOperator` ( Just add a new step - no cancel ) whenever this parameter is false
> 
>     2. Call clear on this operator -> By default, If there is an existing named step in the current cluster with status 'PENDING/RUNNING' , it will send a cancel-step before calling a addstep -> add a new step of the same name for execution
> 
> 
> I would require your thoughts on this , if I am going too overboard with these approaches sweat_smile

Very interesting idea! I think it sounds like a handy feature. Though I don't know EMR itself as a service, and the common workflows associated with it, well enough to say which of the two approaches is the right call.

Perhaps @dacort and @syedahsn can weigh in on the topic

**Comment by dacort** [comment]
I'm curious what the use-case is for cancelling a step? 

Regarding the two options:

> Just add a new step - no cancel

I'd be hesitant to do this as who knows how long that step may run for and consume cluster resources. 

>  If there is an existing named step

Would we be able to keep track of the Step ID and use that to cancel it?

**Comment by swapz-z** [comment]
@dacort

Use-case : 
Its same as what we have in the AWS UI, 
In an airflow Pipeline DAG, if we have a an EMR Operator  step which is basically stuck in Pending/Running for an unexpected amount of time and we want to stop the current execution and mark it for retry.

In current behaviour, if a step is running on EMR and we maybe want to send cancel to it, there is no provision for that ( Clear button in UI doesn't send anything to emr, instead it adds another same step and will be in PENDING until the previous step has either COMPLETED/FAILED (Step concurrency - 1) 


> > Just add a new step - no cancel
> 
> I'd be hesitant to do this as who knows how long that step may run for and consume cluster resources.

Exactly, eating up unwanted resources. This is actually the current behaviour when a clear is called on `EmrAddStepsOperator` - it just adds another same step

> > If there is an existing named step
> 
> Would we be able to keep track of the Step ID and use that to cancel it?

yes, based on the Name of the step, we can get the StepId to be cancelled 

After clear this command will be triggered
-   AddNewStep 
` [{`'Name'`: 'import_jars', 'ActionOnFailure': 'CONTINUE', 'HadoopJarStep': {'Jar': 'command-runner.jar', 'Args': ['bash', '-c', 'sudo cp /usr/share/aws/redshift/jdbc/*.jar /usr/lib/spark/jars/']}}]`

We'll make a` list_steps() `call to emr on that cluster (via boto3) and check if same `Name` step is in PENDING/RUNNING state, then corresponding stepId will be marked for cancellation
-  steps list to be cancelled  `[('import_jars', 's-XV0CPI8KO65T')]`
- And new step will be added 

After changes done in operator => demo behaviour

![image](https://user-images.githubusercontent.com/40524373/206373967-39f9f9c4-9bcd-4626-bfec-4063a16ea7be.png)

![image](https://user-images.githubusercontent.com/40524373/206373881-0fc9b0ac-5149-482e-aa90-56c3b1c3644c.png)

**Comment by swapz-z** [comment]
Created my first PR. Perhaps the PR helps to understand the issue it solves more clearly.
Could you please have a look and provide your feedback on this PR and the issue it address.
Would love to understand your thoughts on the same 
 @dacort and @syedahsn
