### ISSUE TITLE
Airflow AMI

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#280]
I'm in the process of setting up a EC2 instance for our airflow environment and it occurred to me how useful it would be if an AMI already existed.

Do you guys run airflow on a dedicated box in-house and is it an EC2? Would you ever consider making a standard AMI?

This could definitely alleviate some of hassle of setting up the backend components (Mysql/Celery executor components..)

**Comment by mistercrunch** [comment]
We have specific requirements at Airbnb to glue all these systems together. 

I have no experience setting up AMIs but I'm sure the community would appreciate if someone was to set this up...

**Comment by neovintage** [comment]
I'm doing something a little parallel to this. I'm in the process of Dockerizing airflow so that you'll be able to deploy to Heroku with a couple of commands.

**Comment by jasminetsai** [comment]
@neovintage did you end up making progress on this? Would be curious to see it. I am attempting something similar atm.

**Comment by neovintage** [comment]
Yes I did and it works. :-)

https://Github.com/heroku/heroku-airflow

There's zero documentation on how to release it to heroku and is all in my head unfortunately. I'll try to write that up soon

**Comment by jasminetsai** [comment]
Nice, are you running the scheduler + webserver in the same instance or
separately ?

On Fri, Oct 2, 2015 at 2:17 PM, Rimas Silkaitis notifications@github.com
wrote:

> Yes I did and it works. :-)
> 
> https://Github.com/heroku/heroku-airflow
> 
> There's zero documentation on how to release it to heroku and is all in my
> head unfortunately. I'll try to write that up soon
> 
> Sent from my iPhone
> 
> > On Oct 2, 2015, at 1:27 PM, Jasmine Tsai notifications@github.com
> > wrote:
> > 
> > @neovintage did you end up making progress on this? Would be curious to
> > see it. I am attempting something similar atm.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airbnb/airflow/issues/280#issuecomment-145157140.

## 

Jasmine Y. Tsai
+1 415 812 2219

**Comment by neovintage** [comment]
Scheduler runs in a separate process. Although, it's not documented in the current Procfile on the project.

**Comment by bolkedebruin** [comment]
Closing. If this is still a question please contact the apache mailing list.
