### ISSUE TITLE
Add a provider to interact with Microsoft Graph API/SDK 

### ISSUE THREAD

**Issue by odaneau-astro** [apache/airflow#28013]
### Description

Add a new provider for Microsoft Graph API & SDK.

https://learn.microsoft.com/en-us/graph/overview
The Microsoft Graph API offers a single endpoint, https://graph.microsoft.com, to provide access to rich, people-centric data and insights in the Microsoft cloud, including Microsoft 365, Windows, and Enterprise Mobility + Security. You can use REST APIs or SDKs to access the endpoint and build apps that support Microsoft 365 scenarios, spanning across productivity, collaboration, education, people and workplace intelligence, and more. Microsoft Graph also includes a powerful set of services that manage user and device identity, access, compliance, and security and help protect organizations from data leakage or loss.

### Use case/motivation

This would allow interactions with all of these Microsoft Products:

- **Microsoft 365 core services**: Bookings, Calendar, Delve, Excel, Microsoft 365 compliance eDiscovery, Microsoft Search, OneDrive, OneNote, Outlook/Exchange, People (Outlook contacts), Planner, SharePoint, Teams, To Do, Viva Insights
- **Enterprise Mobility + Security services**: Advanced Threat Analytics, Advanced Threat Protection, Azure Active Directory, Identity Manager, and Intune
**Windows services:** activities, devices, notifications, Universal Print
Dynamics 365 Business Central services

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Surely it would be great if Microsoft is inteerested in contributing this (similarly liokee Google, Amazon, Databricsks and others have dedicated teams that spend their time on contributing, maintaining in fixing those.

**Comment by eladkal** [comment]
Policy for adding new provider is explained at https://github.com/apache/airflow/blob/main/PROVIDERS.rst

I'm going to close this issue as the process of adding a provider require investment and commitments from the requester thus it's unlikely that someone will just pick up this request and implement it so no reason to keep this issue open.

**Comment by dabla** [comment]
As discussed [here](https://github.com/apache/airflow/discussions/36315), I've implemented such a provider, now it's just a matter how we will proceed.
