### ISSUE TITLE
Dataproc operators ClusterGenerator can't find parameter of ShieldedInstanceConfig

### ISSUE THREAD

**Issue by italovinicius18** [apache/airflow#28023]
### What do you see as an issue?

Here is the command i'm using to create the VM:

```py
CLUSTER_CONFIG = {
    "master_config": {
        "num_instances": 1,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 1024},
    },
    "worker_config": {
        "num_instances": 2,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 1024},
    },
}

create_cluster = DataprocCreateClusterOperator(
    task_id="create_cluster",
    project_id=PROJECT_ID,
    cluster_config=CLUSTER_CONFIG,
    region=REGION,
    cluster_name=CLUSTER_NAME,
)
```

And I'm following the document below:

https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/dataproc.html
https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.ClusterGenerator
https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/cloud/operators/dataproc.html#ClusterGenerator

But I want to add the options of shielded VM, like the options below:

```py
{
  "enableSecureBoot": True,
  "enableVtpm": True,
  "enableIntegrityMonitoring": True
}
```
But i don't know which parameter I specify these options, and I need a help to solve this.

I've tried to put this on 'properties' parameter of ClusterGenerator, but this doesn't work.

Can someone help me?

### Solving the problem

I believe that if the documentation was more detailed, I could identify if my problem is the missing feature, seeing that I could help create this feature, but I cannot identify if this shielded vm parameter can be applied to the ClusterGenerator function

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mdering** [comment]
it looks like this can be specified in the `gce_cluster_config` field. referring to here https://cloud.google.com/python/docs/reference/dataproc/latest/google.cloud.dataproc_v1.types.ClusterConfig
so maybe something like (I did not test this)

```python
CLUSTER_CONFIG = {
    "gce_cluster_config":{
        "shielded_instance_config":{
            "enableSecureBoot": True,
            "enableVtpm": True,
            "enableIntegrityMonitoring": True
        }
    },
    "master_config": {
        "num_instances": 1,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 1024},
    },
    "worker_config": {
        "num_instances": 2,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 1024},
    },
}
```

**Comment by italovinicius18** [comment]
@mdering And how I put this using CLUSTER_CONFIG using ClusterGenerator?

Like this:

```py
CLUSTER_CONFIG = ClusterGenerator(
    project_id=PROJECT_ID,
    region="us-central1-f",
    cluster_name=CLUSTER_NAME,
    tags=["dataproc"],
    network_uri="",
    internal_ip_only = True,
    # Add shielded VM config
    shielded_instance_config={
        "enable_secure_boot": False,
        "enable_vtpm": True,
        "enable_integrity_monitoring": True,
    },
    subnetwork_uri= "datalab-network",
    config_bucket= "sandbox-processing",
    num_workers=2,
    storage_bucket="sandbox-processing",
    num_masters=1,
    master_machine_type="n1-standard-4",
    master_disk_type="pd-standard",
    master_disk_size=1024,
    worker_machine_type="n1-standard-4",
    worker_disk_type="pd-standard",
    worker_disk_size=1024,
    image_version="2.0-debian10",
    autoscaling_policy=None,
    idle_delete_ttl=7200
     #optional_components=['JUPYTER', 'ANACONDA']
    #metadata={"gcs-connector-version" : '2.1.1' , 
    #              "bigquery-connector-version": '1.1.1',
    #              "spark-bigquery-connector-version": '0.17.2',
    #              "PIP_PACKAGES" : 'datalab shap oyaml click apache-airflow apache-airflow-providers-google'
    #             },
    #init_actions_uris =['gs://goog-dataproc-initialization-actions-us-central1/connectors/connectors.sh','gs://goog-dataproc-initialization-actions-us-central1/python/pip-install.sh']
).make()
```

**Comment by mdering** [comment]
I would just add it after the call to `make()`

```python
CLUSTER_CONFIG['gce_cluster_config']['shielded_instance_config']={...}
```

**Comment by italovinicius18** [comment]
I've tried this option but I got a error

ValueError: Protocol message GceClusterConfig has no "shieldedInstanceConfig" field.

**Comment by italovinicius18** [comment]
I know now, that the syntax needs to be the same of protobuf protocol, but I found the same error:

ValueError: Protocol message GceClusterConfig has no "shielded_instance_config" field.

**Comment by shivannakarthik** [comment]
@italovinicius18
I was able to create a dataproc cluster using the cluster create operator using the following configs.
From the [GCP doc](https://cloud.google.com/python/docs/reference/dataproc/latest/google.cloud.dataproc_v1.types.ShieldedInstanceConfig), it is not very clear if the value should be a string (True or False) or numeric bool (0 or 1). I tried providing True and it gave me a  TypeError - "TypeError('an integer is required (got type str)')"}. I then gave an int and the cluster came up with VMs having the Shield configs enabled.

`    'cluster_config': {
        'software_config': {
            'image_version': '1.5'
        },
        'gce_cluster_config': {
            "shielded_instance_config": {
                "enable_secure_boot": 1,
                "enable_vtpm": 1,
                "enable_integrity_monitoring": 1
            }
        } `


The same should work for ClusterGenerator.

**Comment by italovinicius18** [comment]
Hi, @shivannakarthik !

Can you send me all the dict? I think i'm putting the key in the wrong place

**Comment by shivannakarthik** [comment]
@italovinicius18  Here you go
>  {
>   "cluster_config": {
>       "software_config": {
>         "properties": {
>           "spark:spark.sql.catalogImplementation": "hive"
>         },
>         "optional_components": [
>           "ANACONDA"
>         ]
>       },
>       "gce_cluster_config": {
>           "metadata": {
>             "key": "value"
>           },
> 	  "shielded_instance_config": {
>             "enable_secure_boot": 1,
>             "enable_vtpm": 1,
>             "enable_integrity_monitoring": 1
> 	}
>       },
>       "master_config": {
>           "disk_config": {
>               "boot_disk_size_gb":500
>           }
>       },
>       "worker_config": {
>           "num_instances": 2,
>           "disk_config": {
>               "boot_disk_size_gb":500
>           }
>       },
>       "secondary_worker_config": {
>           "num_instances": 1,
>           "disk_config": {
>               "boot_disk_size_gb":500
>           }
>       }
>   }
> }

**Comment by italovinicius18** [comment]
Thank you! But I had the same problem.

I managed to solve the problem using the dataproc api and added a function to this cluster creation, below is the function created.

```py
def create_cluster_custom(project_id, region, cluster_name):
    # Create a client
    client = dataproc_v1.ClusterControllerClient(
        client_options={"api_endpoint": "{}-dataproc.googleapis.com:443".format(region)}
    )

    # Initialize request argument(s)
    cluster = dataproc_v1.Cluster()
    cluster.project_id = project_id
    cluster.cluster_name = cluster_name

    cluster_config = dataproc_v1.ClusterConfig()
    cluster_config.master_config.num_instances = 1
    cluster_config.master_config.machine_type_uri = "n1-standard-4"
    cluster_config.worker_config.num_instances = 2
    cluster_config.worker_config.machine_type_uri = "n1-standard-4"

    # Subnetwork URI

    cluster_config.gce_cluster_config.subnetwork_uri = "datalab-network" 

    # Specify the zone

    cluster_config.gce_cluster_config.zone_uri = "us-central1-f"

    # Specify the image version
    cluster_config.software_config.image_version = "2.0-debian10"

    # Set shieled instance

    cluster_config.gce_cluster_config.shielded_instance_config.enable_secure_boot = True
    cluster_config.gce_cluster_config.shielded_instance_config.enable_vtpm = True
    cluster_config.gce_cluster_config.shielded_instance_config.enable_integrity_monitoring = True

    # Set internal IP only

    cluster_config.gce_cluster_config.internal_ip_only = True

    cluster.config = cluster_config

    request = dataproc_v1.CreateClusterRequest(
        project_id=project_id,
        region=region,
        cluster=cluster,
    )

    # Make the request
    operation = client.create_cluster(request=request)

    print("Waiting for operation to complete...")

    response = operation.result()

    # Handle the response
    print(response)
```
