### ISSUE TITLE
Long step names are truncated in the Grid view

### ISSUE THREAD

**Issue by WojciechO** [apache/airflow#28055]
### Apache Airflow version

2.4.3

### What happened

In the grid view, when big number of runs are displayed, the names of the steps are truncated at the flow name even though there is space to display longer string. It makes it hard to navigate the DAG.

Tested on Chrome 103.0.5060.114, 100% zoom and Safari Version 16.1 

Grid view with 100 runs:
![image](https://user-images.githubusercontent.com/10329851/205265010-b1841e95-da2b-4e88-a302-05410eedb6cc.png)

The same Grid View displays full step names when 25 runs are selected.

### What you think should happen instead

The step names should fill the space that's available for them fully.

### How to reproduce

* Create a flow that has step names with names longer than 50 characters (estimated length, I do not get this behaviour for flow names with 50 chars)
* The flow needs to have more than 100 runs available
* Toggle the Gird View with 100 runs

### Operating System

Mac OS 11.7.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mb-m** [comment]
To explain a bit further, these task names (and the dags they fall in) are auto-generated from a system scanning multiple teams' configurations, which means that just using shorter names isn't actually particularly plausible here :-(

**Comment by tirkarthi** [comment]
cc: @bbovenzi

**Comment by bbovenzi** [comment]
Actually, I think this was fixed by https://github.com/apache/airflow/pull/27560 in 2.5
