### ISSUE TITLE
task duration in grid view is different when viewed at different times.

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#28070]
### Apache Airflow version

2.4.3

### What happened

I wrote this dag to test the celery executor's ability to tolerate OOMkills:

```python3
import numpy as np
from airflow import DAG
from airflow.decorators import task
from datetime import datetime, timedelta
from airflow.models.variable import Variable
import subprocess
import random


def boom():
    np.ones((1_000_000_000_000))


def maybe_boom(boom_hostname, boom_count, boom_modulus):
    """
    call boom(), but only under certain conditions
    """

    try:
        proc = subprocess.Popen("hostname", shell=True, stdout=subprocess.PIPE)
        hostname = proc.stdout.readline().decode().strip()

        # keep track of which hosts parsed the dag
        parsed = Variable.get("parsed", {}, deserialize_json=True)
        parsed.setdefault(hostname, 0)
        parsed[hostname] = parsed[hostname] + 1
        Variable.set("parsed", parsed, serialize_json=True)

        # only blow up when the caller's condition is met
        print(parsed)
        try:
            count = parsed[boom_hostname]
            if hostname == boom_hostname and count % boom_modulus == boom_count:
                print("boom")
                boom()
        except (KeyError, TypeError):
            pass
        print("no boom")
    except:
        # key errors show up because of so much traffic on the variable
        # don't hold up parsing in those cases
        pass


@task
def do_stuff():
    # tasks randomly OOMkill also
    if random.randint(1, 256) == 13:
        boom()


run_size = 100

with DAG(
    dag_id="oom_on_parse",
    schedule=timedelta(seconds=30),
    start_date=datetime(1970, 1, 1),
    catchup=False,
):

    # OOM part-way through the second run
    # and every 3th run after that
    maybe_boom(
        boom_hostname="airflow-worker-0",
        boom_count=run_size + 50,
        boom_modulus=run_size * 3,
    )
    [do_stuff() for _ in range(run_size)]

```

I'm not surprised that tasks are failing.  The dag occasionally tries to allocate 1Tb of memory.  That's a good reason to fail.  What surprises me is that occasionally, the run durations are reported as 23:59:30 when I've only been running the test for 5 minutes.  Also, this number changes if I view it later, behold:
![2022-12-02 09 44 32](https://user-images.githubusercontent.com/5834582/205346230-1173a79e-b6f1-43bd-b232-5cbda29e1d13.gif)

23:55:09 -> 23:55:03 -> 23:55:09, they're decreasing.

### What you think should happen instead

The duration should never be longer than I've had the deployment up, and whatever is reported, it should not change when viewed later on.

### How to reproduce

Using the celery executor, unpause the dag above.  Wait for failures to show up.  View their duration in the grid view.

This gist includes a script which shows all of the parameters I'm using (e.g. to helm and such): https://gist.github.com/MatrixManAtYrService/6e90a3b8c7c65b8d8b1deaccc8b6f042

### Operating System

k8s / helm / docker / macos

### Versions of Apache Airflow Providers

n/a

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

See script in this gist? https://gist.github.com/MatrixManAtYrService/6e90a3b8c7c65b8d8b1deaccc8b6f042

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatrixManAtYrService** [comment]
I wonder if @bbovenzi can tell us if this is a UI bug or something deeper.

**Comment by bbovenzi** [comment]
Is that all of the task instances or just this one which is also missing a start date?

**Comment by MatrixManAtYrService** [comment]
Some of them don't have that problem.  Some do.  And yes, it doesn't have a start date because it went straight from queued to failed.
