### ISSUE TITLE
close

### ISSUE THREAD

**Issue by azraelxuemo** [apache/airflow#28091]
### Apache Airflow version

2.5.0

### What happened

Hi there,i use this guide to install airflow
https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
But when i run docker compose up airflow-init 
![image](https://user-images.githubusercontent.com/60163868/205479814-95a8d064-ee47-4627-8985-6e78ee360ab5.png)

### What you think should happen instead

In the tutorial, you said that if it succeeds, it will return the following content
![image](https://user-images.githubusercontent.com/60163868/205479841-c0ce5f85-452c-4e99-90c5-8d8bf75bdea1.png)

### Operating System

NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.4 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal

### Versions of Apache Airflow Providers

curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.5.0/docker-compose.yaml'

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is just a warning. But yeah. Likely default configuration should be updated to reflect it.

**Comment by potiuk** [comment]
Fix in #28094 - @azraelxuemo  - can you please apply it and see if that fixes the problem?
