### ISSUE TITLE
Celery Flower Port

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#281]
I'm trying to start the Celery Flower by running `airflow celery`

I assumed this would pickup the `flower_port` variable from the config, however it seems to run on 5555 by default. From what I can see the port from the config is never passed into [this function](https://github.com/airbnb/airflow/blob/33b459379aabfa9c5273be4ba329228528a906f6/airflow/bin/cli.py#L337) when no cmd line args are supplied.

Should the `flower_port` value get picked up?

**Comment by mistercrunch** [comment]
Yes it should... I think on our side it's hard coded somewhere in our chef recipe

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/284
