### ISSUE TITLE
Type Error while using dynamodb_to_s3 operator

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#28103]
### Discussed in https://github.com/apache/airflow/discussions/28102

<div type='discussions-op-text'>

<sup>Originally posted by **p-madduri** December  1, 2022</sup>
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

https://github.com/apache/airflow/blob/430e930902792fc37cdd2c517783f7dd544fbebf/airflow/providers/amazon/aws/transfers/dynamodb_to_s3.py#L39

if we use the below class at line 39:
def _convert_item_to_json_bytes(item: dict[str, Any]) -> bytes:
return (json.dumps(item) + "\n").encode("utf-8")

its throwing below error
TypeError: Object of type Decimal is not JSON serializable.

can we use

class DecimalEncoder(json.JSONEncoder):
def encode(self, obj):
if isinstance(obj, Mapping):
return '{' + ', '.join(f'{self.encode(k)}: {self.encode(v)}' for (k, v) in obj.items()) + '}'
elif isinstance(obj, Iterable) and (not isinstance(obj, str)):
return '[' + ', '.join(map(self.encode, obj)) + ']'
elif isinstance(obj, Decimal):
return f'{obj.normalize():f}' # using normalize() gets rid of trailing 0s, using ':f' prevents scientific notation
else:
print(obj)
return super().encode(obj)

and need to update the code at line 
https://github.com/apache/airflow/blob/430e930902792fc37cdd2c517783f7dd544fbebf/airflow/providers/amazon/aws/transfers/dynamodb_to_s3.py#L99

This solution is suggested in this article:
https://randomwits.com/blog/export-dynamodb-s3

Airflow version of MWAA : 2.0.2

### What you think should happen instead

mentioned in what happened section

### How to reproduce

mentioned in what happened section

### Operating System

MAC

### Versions of Apache Airflow Providers

from airflow.providers.amazon.aws.transfers.dynamodb_to_s3 import DynamoDBToS3Operator

### Deployment

MWAA

### Deployment details

n/a

### Anything else

n/a

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by snjypl** [comment]
@potiuk  i was wondering if this could be a solution: https://github.com/open-contracting/spoonbill-web/commit/6987a7e0b820c35cd8a9e9d62befdf7200de7348

`json.dumps(item,default=str)`
```
>>> from decimal import Decimal
>>> import json
>>> item = {'a':1, 'b':Decimal(1038)}
>>> json.dumps(item)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
>>> json.dumps(item,default=str)
'{"a": 1, "b": "1038"}'
```

**Comment by snjypl** [comment]
@potiuk  i was wondering if this could be a solution.

```python
import json
from decimal import Decimal


class JSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
              return float(obj)
        return json.JSONEncoder.default(self, obj)


for i in ["102938.3043847474",1.010001,10,"100","1E-128",1E-128]:
    org = Decimal(i)
    encoded = json.dumps(org,cls=JSONEncoder)
    decoded = json.loads(encoded,parse_float=Decimal)
    
    
    print(f"{org=}")
    print(f"{encoded=}")
    print(f"{decoded=}")
    print(" "*5)
```
output:
```python
org=Decimal('102938.3043847474')
encoded='102938.3043847474'
decoded=Decimal('102938.3043847474')

org=Decimal('1.01000099999999992661514625069685280323028564453125')
encoded='1.010001'
decoded=Decimal('1.010001')

org=Decimal('10')
encoded='10.0'
decoded=Decimal('10.0')

org=Decimal('100')
encoded='100.0'
decoded=Decimal('100.0')

org=Decimal('1E-128')
encoded='1e-128'
decoded=Decimal('1E-128')

org=Decimal('1.00000000000000005401408859568103309052834145426594802430862986593345890744772751462514653740544965836726232958009946209108101694078484369205457039971496303344480117025912844198468177541980552987602212529712035107713678381275316882208085186144350914663534730232928215257050045129264726062873538499086450376880826074188490792948869056999683380126953125E-128')
encoded='1e-128'
decoded=Decimal('1E-128')
```

 there is something similar in airflow uitls 
https://github.com/apache/airflow/blob/64deada0babf3ad0ebf8dc4465a14dab6358c659/airflow/utils/json.py#L77-L83

**Comment by potiuk** [comment]
Make a PR - It's far easier to reason about it when you just make a PR and run tests.
