### ISSUE TITLE
docker-compose.yaml issue

### ISSUE THREAD

**Issue by DebabrataTah** [apache/airflow#28144]
### Apache Airflow version

2.5.0

### What happened

I tried to install airflow localhost. I downloaded the docker-compose.yaml file from the link "https://airflow.apache.org/docs/apache-airflow/stable/docker-compose.yaml". When I ran the command "docker-compose up airflow-init" or the command "docker-compose up", it is giving error like " **Invalid interpolation format for "environment" option in service "flower": "${_PIP_ADDITIONAL_REQUIREMENTS:-}"** ".

### Operating System

Microsoft Windows 10 Enterprise

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xlanor** [comment]
What version of docker-compose are you using?
