### ISSUE TITLE
Logs tab is automatically scrolling to the bottom while user is reading logs

### ISSUE THREAD

**Issue by hterik** [apache/airflow#28143]
### Apache Airflow version

2.5.0

### What happened

Open the logs tab for a task that is currently running.
Scroll up to read things further up the log.
Every 30 seconds or so the log automatically scrolls down to the bottom again.

### What you think should happen instead

If the user has scrolled away from the bottom in the logs-panel, the live tailing of new logs should not scroll the view back to the bottom automatically.

### Operating System

Ubuntu 22.04

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zachliu** [comment]
i thought it was by design :joy:

**Comment by zachliu** [comment]
is it fixed or am i looking at another (but very similar) problem?

https://user-images.githubusercontent.com/14293802/214154892-43154669-2020-4bab-a901-67fb704e2b87.mp4

the auto-refresh is seemingly refreshing, scrolling, and appending logs continuously until the end of this task, making me think this task will have accumulated a ton of repeating logs but that's not the case if i check back after it's done :thinking:

**Comment by bbovenzi** [comment]
@zachliu What about if you view the logs from the grid view?

**Comment by zachliu** [comment]
grid view logs seems to be fine. this only occurs if i click "See More".
after i click "See More" there are actually 2 scenarios:
1. if i scroll down to the bottom i'll start seeing what the video shows
2. if i don't scroll down, i'll see the scrollbar keeps getting smaller and smaller
