### ISSUE TITLE
Links to dag graph some times display incorrect dagrun

### ISSUE THREAD

**Issue by hterik** [apache/airflow#28155]
### Apache Airflow version

2.5.0

### What happened

Open url `dags/gate/graph?dag_run_id=8256-8-1670328803&execution_date=2022-12-06T12%3A13%3A23.174592+00%3A00`
The graph is displaying a completely different dagrun. 
![image](https://user-images.githubusercontent.com/89977373/205916845-8acdf310-6073-46f9-aea3-8e144f6e4fba.png)
If you are not careful to review all the content, you might continue looking at the wrong results, or worse cancel a run with Mark failed.

I got the link from one of our users, so not 100% sure if it was the original url. I believe there could be something wrong with the url-encoding of the last `+` character. In any case, if there are any inconsistencies in the URL parameters vs the found dagruns, it should not display another dagrun, rather redirect to grid-view or error message.

### What you think should happen instead

* dag_run_id should be only required parameter, or have precedence over execution_date
* Provided dag_run_id should always be the same run-id that is displayed in graph
* Inconsistencies in any parameters should display error or redirect to grid view.

### Operating System

Ubuntu 22.04

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Where are you clicking the link to the graph view?

**Comment by hterik** [comment]
I got the link in a chat message from one of our users, he claims it was from airflow, but can not be sure if it was fat-fingered during the paste into the chat. 

Regardless if the url is from a correct source or not, i still think there should be some validation to not present any arbitrary dagrun, if there is an attempt to select a `dag_run_id` via querystrg.
