### ISSUE TITLE
Log links in grid view

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#28163]
### Description

In the log view urls are automatically converted to links. This doesn't happen in the logs in grid view. It would be great if that behavior was matched. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsha-samsung** [comment]
@potiuk,  can I take up this task ?

**Comment by potiuk** [comment]
Feel free

**Comment by MohammadWasi** [comment]
Hi Can you please provide more details/screenshots.
I can’t find the log view in UIw

**Comment by tirkarthi** [comment]
This looks like a duplicate of https://github.com/apache/airflow/issues/35280

**Comment by bbovenzi** [comment]
Closed by https://github.com/apache/airflow/pull/36816
