### ISSUE TITLE
how to loop a task group in DAG

### ISSUE THREAD

**Issue by mis98zb** [apache/airflow#28164]
### Description

I have a requirement that I need a loop to do several tasks according to the previous task's output.

### Use case/motivation

I have a requirement that I need a loop to do several tasks according to the previous task's output.

For example, a SearchTask found 5 new folders, then I need to loop for each folder to do preprocess/aggreate/update_flag/email.
I image to use like this:
```
searchTask >> LoopOperator(XCom.newFolders, [preprocess, aggreate, update_flag, email])
```

However, I did not find any LoopOperator in the document.
I only find BranchOperator, but seems it cannot help on this case.

Can anyone help to finger out how to deal with this kind of case?
Thanks in advance!   

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Use DynamicTaskMapping added in Airflow 2.4 and improved upon in 2.5.0. This solves your problem.
