### ISSUE TITLE
Allow Markdown in Task comments

### ISSUE THREAD

**Issue by odaneau-astro** [apache/airflow#28167]
### Description

Implement the support for Markdown in Task notes inside Airflow.

### Use case/motivation

It would be helpful to use markdown syntax in Task notes/comments for the following usecases:
- Formatting headers, lists, and tables to allow more complex note-taking.
- Parsing a URL to reference a ticket in an Issue ticketing system (Jira, Pagerduty, etc.)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @Jorricks

**Comment by pierrejeambrun** [comment]
+1 for this, would be great !

**Comment by pierrejeambrun** [comment]
This looks fun to do. Assigning myself :p
