### ISSUE TITLE
Allow changing the Task comments via a task

### ISSUE THREAD

**Issue by xeor** [apache/airflow#28232]
### Description

A way to set the new task-comment that arrived in 2.5 using a task.

### Use case/motivation

I want to summarize a dag-run with some additional information from the context available inside the dag-run. Example with links and data that should be easy to look up.

This will work great with https://github.com/apache/airflow/issues/28167 to add markdown support for adding links from inside a task.

Something like

```py
    @task(task_id="summarizer")
    def preflight(ti=None):
        ti.notes = 'some notes with context'
```

### Related issues

https://github.com/apache/airflow/discussions/28035

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
IMHO - This should be done via API not via decorator/task. There is no "internal" mechanism to change some tasks from other tasks and stable REST API is the best way of doing it. Let me convert it to a discussion - maybe others will see it differently but I have a feeling that the way it is specified (what should be decorateD? when? when it should be processed? etc. is far from "defined". This is more a wish than defined feature, and discussion is more appropriate place for it.
