### ISSUE TITLE
Airflow CLI to list roles is slow

### ISSUE THREAD

**Issue by malthe** [apache/airflow#28242]
### Apache Airflow version

2.5.0

### What happened

We're currently running a suboptimal setup where database connectivity is laggy, 125ms roundtrip.

This has interesting consequences. For example, `airflow roles list` is really slow. Turns out that it's doing a lot of individual queries.

### What you think should happen instead

Ideally, listing roles should be a single (perhaps complex) query.

### How to reproduce

We're using py-spy to sample program execution:

```bash
$ py-spy record -o spy.svg -i --rate 250 --nonblocking airflow roles list
```
Now, to see the bad behavior, the database should incur significant latency.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by malthe** [comment]
Flamegraph generated using [py-spy](https://github.com/benfred/py-spy).

![spy](https://user-images.githubusercontent.com/26405/206579152-ddc49063-7450-48e5-b6b3-501a9f02ffb9.svg)

**Comment by potiuk** [comment]
I believe there is not much we can do - when you look at the flamegraph it initializes flask and flask-app-builder. Until we replace the user model with somethiing else thanf Flass App Builder, there is not much we can do I am afraid.

**Comment by potiuk** [comment]
Correction: We could likely decrease it a bit by removing connexion (REST API) intialization- it seems it contributes to > 50% of the time

**Comment by potiuk** [comment]
Or maybe we could actually not initialize views ...
