### ISSUE TITLE
AIP-44 Migrate DagFileProcessor.execute_callbacks to Internal API.

### ISSUE THREAD

**Issue by mhenc** [apache/airflow#28269]
Note that Callback execution must be still done in DagProcessor

**Comment by vincbeck** [comment]
I'd like to work on this one

**Comment by vincbeck** [comment]
I dont think the method `execute_callbacks` needs to be converted itself but rather the submethods `_execute_task_callbacks` and `_execute_dag_callbacks`. What do you think? The submethod `manage_slas` has already its own issue

**Comment by mhenc** [comment]
Right, I should have been more descriptive:
The problem about this task is that executing the callback itself must be still done in the DagProcessor (not Internal API) component.
One the other hand all requests to DB must be done through Internal API. E.g. `_execute_task_callbacks`  first read data from DB then call `ti.handle_failure`(which unfortunatelly also tasks session in the arguments and ameks some additional DB calls.).
This all must be untangled - even with refactoring of some methods/introducing new
