### ISSUE TITLE
AIP-44 Migrate Variable to Internal API

### ISSUE THREAD

**Issue by mhenc** [apache/airflow#28271]
Link: https://github.com/apache/airflow/blob/main/airflow/models/variable.py

Methods to migrate:

- val
- set 
- delete
- update

Note that get_variable_from_secrets shouls still be executed locally.

It may be better to first close https://github.com/apache/airflow/issues/28267

**Comment by bugraoz93** [comment]
Hey! 
I would like to work on this issue. Of course, after closing #28267 as you suggested. 
Meanwhile, I would also like to work on #28612 if there is no dependency.

**Comment by mhenc** [comment]
Thanks!
Just a note - you can work on a PR even now. 
Just remember to start InternalAPI (as part of Web Server) with `[core]database_access_isolation=False` (while running e.g. Worker/Dag processor with` [core]database_access_isolation=True`.

Can you also comment on https://github.com/apache/airflow/issues/28612 so I can assign you there?

**Comment by bugraoz93** [comment]
Great information, thanks! 
Sure, I am writing a comment now.

**Comment by bugraoz93** [comment]
This story is in progress. I cannot change the Issue Status. FYI

**Comment by potiuk** [comment]
Changed.

**Comment by bugraoz93** [comment]
Thanks a lot!
