### ISSUE TITLE
expand_kwargs does not handle update of dataset correctly when "outlets" parameter is used as kwargs

### ISSUE THREAD

**Issue by julwin** [apache/airflow#28304]
### Apache Airflow version

2.5.0

### What happened

When using dynamic task mapping, I tried to update an airflow dataset for every file in a S3 location. 
The URI for the dataset should be generated inside of a Taskflow task, containing the basename of the processed file.

The
```python
@task()
def extract_s3_destination():
  dataset = Dataset("s3://dataset-bucket/example.csv")
  return {"filename": path, "dest_key": dest_key, "outlets": [dataset]}
```

When handing this over to `expand_kwargs` (even with strict=False), this error occurs:

```python
filenames = extract_s3_destination.expand(path=XComArg(list_modified_files))

copy_to_s3 = LocalFilesystemToS3Operator.partial(
        task_id="copy_file_to_s3",
        aws_conn_id="s3",
        gzip=True,
        replace=True,
        dest_bucket="{{ conn.s3.login }}",
    ).expand_kwargs(filenames, strict=False)
```

```
{manager.py:56} WARNING - DatasetModel Dataset(uri='unprocessed/customfilename20221212.zip', extra=None) not found
```

The same happens when 

### What you think should happen instead

The Dataset should be updated if not exists or created, the way you would expect it after reading these examples from the Documentation:

```
from airflow import Dataset

with DAG(...):
    MyOperator(
        # this task updates example.csv
        outlets=[Dataset("s3://dataset-bucket/example.csv")],
        ...,
    )


with DAG(
    # this DAG should be run when example.csv is updated (by dag1)
    schedule=[Dataset("s3://dataset-bucket/example.csv")],
    ...,
):
    ...
```

### Operating System

kubernetes / airflow executor / default image

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Is this specific to `expand_kwargs`? I am under the impression passing outlet as XComArg would not work in general since the value needs to be accessed in the scheduler.

Say

```python
@task()
def get_outlet():
    return Dataset("s3://dataset-bucket/example.csv")

MyOperator(outlets=[get_outlet()])  # Does this work?
```

**Comment by DaanRademaker** [comment]
Why is this issue closed? This does not seem possible currently.

**Comment by potiuk** [comment]
Looking at the history - because the author did not respond to the question - it has been closed automatically after than. If you want, you can respond in a new issue @DaanRademaker - there is nothing stopping you from creating similar issue (and becoming and author who will provide more insights when asked). Feel absolutely free.

**Comment by uranusjr** [comment]
If you do reactivate the issue, please make sure to first investigate the topic asked above first.
