### ISSUE TITLE
DB init and upgrade for mysql does not work on Airflow 2.2.5

### ISSUE THREAD

**Issue by agarwalakash06** [apache/airflow#28330]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow db init and upgrade fails with airlfow version 2.2.5
airflow 2.2.5 interanlly installs mysql 5.6.51
python version: 3.6.8

(MySQLdb.OperationalError) (1709, \'Index column size too large. The maximum column size is 767 bytes.\')\n[SQL: ALTER TABLE slot_pool MODIFY pool VARCHAR(256) COLLATE utf8mb3_general_ci NULL

when trying manually, it works when the size of varchar is 255 instead of 256

Steps followed:
manually executed this command
ALTER TABLE slot_pool MODIFY `pool` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin;

still db upgrade fails

### What you think should happen instead

Airflow db should have been started without any issue

### Operating System

NAME="Oracle Linux Server" VERSION="7.9" ID="ol" ID_LIKE="fedora" VARIANT="Server" VARIANT_ID="server" VERSION_ID="7.9" PRETTY_NAME="Oracle Linux Server 7.9" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:oracle:linux:7:9:server" HOME_URL="https://linux.oracle.com/" BUG_REPORT_URL="https://bugzilla.oracle.com/"  ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7" ORACLE_BUGZILLA_PRODUCT_VERSION=7.9 ORACLE_SUPPORT_PRODUCT="Oracle Linux" ORACLE_SUPPORT_PRODUCT_VERSION=7.9

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==2.1.0
apache-airflow-providers-http==2.1.0
apache-airflow-providers-imap==2.2.1
apache-airflow-providers-mysql==2.2.1
apache-airflow-providers-sqlite==2.1.1

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Actually It's not even 2.2.5. It's Mysql 5.6 that has never been supported in Airflow 2. See the prerequisites. So even if you try the latest version it won't work.

**Comment by agarwalakash06** [comment]
never mind
I got it. we are installing it from the dockerfile
Thank you @potiuk for your input
