### ISSUE TITLE
Showing Task State in Gantt Chart?

### ISSUE THREAD

**Issue by yxiao1996** [apache/airflow#28341]
### Description

Hi team,

Recently I've been working on using Airflow to orchestrate some of my teams ETL jobs. Lately I run into some performance issue and noticed that the Gantt chart feature is a pretty handy tool for understanding long running DAG runs. I observed large gaps between tasks in the Gantt chart, showing there's a resource bottleneck. However, it seems like the Gantt chart only tracks "running" state of the tasks, so I was not able to fully pin-point whether the bottleneck is the worker(tasks being "queued" for a long time) or the scheduler(tasks being in "no_status" for a long time). So I'm thinking about if airflow could track different task state in the Gantt chart, it would be easier for users to troubleshoot similar issues. 

Please educate me if my understanding is wrong. 

Thanks,
Yu

### Use case/motivation

By having task state tracking in Gantt chart, it would be easier for airflow users to troubleshoot performance issue in DAG's.

### Related issues

n/a

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We do have `queued_dttm` for task instances, so that shouldn't be too hard to add. Otherwise, I think we'll need a new table to record task events like state changes?

**Comment by pierrejeambrun** [comment]
Hello @yxiao1996,

Good idea!

I see you are willing to contribute, assigning you :)

**Comment by yxiao1996** [comment]
thanks for the comments. wip....

**Comment by yxiao1996** [comment]
Hi team, I looked into the code a little bit, want to check with you about the general approach before making the change.

Seems like I should be able to retrieved the `queued_dttm` field from the `ti` objects [here](https://github.com/apache/airflow/blob/753b9eced5938a4216ddaf0c4afcf89bd7a39a4e/airflow/www/views.py#L3441)? If that is the case, looks like I can add queued_dttm field into `task_dict`, which would be passed to the front-end. Then I can make drop new boxes in gantt.js around [here](https://github.com/apache/airflow/blob/753b9eced5938a4216ddaf0c4afcf89bd7a39a4e/airflow/www/static/js/gantt.js#L186) with box width defined by queued_dttm and task start_date.

Am I making sense?

**Comment by bbovenzi** [comment]
Yes, that sounds about right. And the class will just be `queued` instead of the task state. You can see how the current boxes are created [here](https://github.com/apache/airflow/blob/753b9eced5938a4216ddaf0c4afcf89bd7a39a4e/airflow/www/static/js/gantt.js#L243). Reach out if you have any other questions!

**Comment by yxiao1996** [comment]
Hi, 

I think I'm getting close to put up a PR. I noticed that the queued_dttm is already passed to the UI through [this line](https://github.com/apache/airflow/blob/753b9eced5938a4216ddaf0c4afcf89bd7a39a4e/airflow/www/views.py#L3448) so I'm only changing the javascript. I'm curious are there any tests I need to created for this new feature? I don't see on the surface there's any tests for these javascripts. Also, is there a template I need to follow for PR?

Thanks,
Yu

**Comment by yxiao1996** [comment]
![Screenshot_20221230_110010](https://user-images.githubusercontent.com/27112484/210104028-1dcba80e-5c35-4eee-a46c-0987f98e388d.png)

Here's a snapshot of this feature in my dev environment. Basically I'm drawing these gray boxes for tasks instances with non-null queued_dttm, also add a tooltip on the queued state box to provide related info. Curious do you guys have any comments on how this should look?

**Comment by bbovenzi** [comment]
Looks great! I'd say open a PR so we can can a closer look. If it's not fully ready, open it up as a draft.

**Comment by eladkal** [comment]
Looks nice!
BTW would be intresting as a followup to see what we can do about https://github.com/apache/airflow/issues/17487

**Comment by bbovenzi** [comment]
Closed by https://github.com/apache/airflow/pull/28686

But a future improvement could be to use Task Reschedules in Gantt as explained in https://github.com/apache/airflow/issues/17487
