### ISSUE TITLE
S3 Remote Logging not working on Airflow 2.4.3 with apache-airflow-providers-amazon==6.0.0

### ISSUE THREAD

**Issue by sid-habu** [apache/airflow#28365]
### Apache Airflow version

Airflow 2.4.3

### What happened

Upgrade from Airflow 2.3.4 to 2.4.3 has stopped S3 remote logging. We have a working `aws` connection type in 2.3.4 with the below attributes.  

Sensitive Values are masked as `xxxxxxxxxx`

```
AWS Access Key ID
AWS Secret Access Key
Extra: {"region_name": "us-east-2", "role_arn": "arn:aws:iam::xxxxxxxxx:role/service/xxxxxxxxx"}
```

Airflow logging environment variables from the scheduler pod

```
AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION=/airflow-logs/logs/dag_processor_manager/dag_processor_manager.log
AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=xxxxxxx
AIRFLOW__LOGGING__BASE_LOG_FOLDER=/airflow-logs/logs
AIRFLOW__LOGGING__REMOTE_LOGGING=True
AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://xxxxxxx
AIRFLOW__LOGGING__ENCRYPT_S3_LOGS=False
```

With upgrade to 2.4.3, remote logging no longer with below error

```
canarydagprintdate-938a1a1f10ab4c3c9db5650fdec731b7
*** Failed to verify remote log exists s3://xxxxxx/dag_id=canary_dag/run_id=scheduled__2022-12-14T21:21:40.610340+00:00/task_id=print_date/attempt=1.log.
An error occurred (403) when calling the HeadObject operation: Forbidden
*** Falling back to local log
*** Trying to get logs (last 100 lines) from worker pod canarydagprintdate-938a1a1f10ab4c3c9db5650fdec731b7 ***
```

I manually verified using AWS CLI that the IAM user is able to assume role and access the S3 bucket and list keys within it.

Below are S3 bucket permissions

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::xxxx:role/service/xxxxx"
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::xxxxxx"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::xxxxx:role/service/xxxxxxx"
            },
            "Action": [
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:GetObjectVersion",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:DeleteObjectVersion",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::xxxxxxx/*"
        }
    ]
}
```

### What you think should happen instead

Remote logging to S3 used to work on Airflow 2.3.4

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==6.1.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.3.1
apache-airflow-providers-docker==3.2.0
apache-airflow-providers-elasticsearch==4.2.1
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==8.4.0
apache-airflow-providers-grpc==3.0.0
apache-airflow-providers-hashicorp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-microsoft-azure==4.3.0
apache-airflow-providers-mysql==3.2.1
apache-airflow-providers-odbc==3.1.2
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==4.1.0
apache-airflow-providers-slack==6.0.0
apache-airflow-providers-snowflake==3.3.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.2.0
```

Note: Upgraded `apache-airflow-providers-amazon==6.1.0` from `6.0.0` as I saw a related issue in https://github.com/apache/airflow/pull/26946/files

### Deployment

Other

### Deployment details

Cloud provider or hardware configuration: AWS
Custom Helm Chart
Kubernetes version (if you are using kubernetes) (use kubectl version): 1.21.14

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Just for confirm.

1. You provide AWS Access Key ID, AWS Secret Access Key and role_arn in extra? Because You not masked as `xxxxx` for access key and secret key, so I assume that might be option that you retrieve initial credentials as IAM Profile or somewhere else.

2. Are log files created in S3?

3. Does this issue persist for newly created logs? After you upgrade to 6.1.0

4. Did you also upgrade amazon-provider on webserver? Just ask because logs retrieved from webserver, not scheduler.

5. Could you try to check your credentials by this snippet: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#snippet-to-create-connection-and-convert-to-uri and check is it printed correct role.

**Comment by sid-habu** [comment]
> Just for confirm.
> 
> 1. You provide AWS Access Key ID, AWS Secret Access Key and role_arn in extra? Because You not masked as `xxxxx` for access key and secret key, so I assume that might be option that you retrieve initial credentials as IAM Profile or somewhere else.
> 2. Are log files created in S3?
> 3. Does this issue persist for newly created logs? After you upgrade to 6.1.0
> 4. Did you also upgrade amazon-provider on webserver? Just ask because logs retrieved from webserver, not scheduler.
> 5. Could you try to check your credentials by this snippet: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#snippet-to-create-connection-and-convert-to-uri and check is it printed correct role.

1. The Access Key and Secret are provided in the Connection UI
2. Yes, I see the log files getting generated in the S3
3. Yes
4. This might be the issue! You are right as `pip freeze` in webserver is still pointing to `6.0.0`

```
apache-airflow-providers-amazon==6.0.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-docker==3.2.0
apache-airflow-providers-elasticsearch==4.2.1
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==8.4.0
apache-airflow-providers-grpc==3.0.0
apache-airflow-providers-hashicorp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-microsoft-azure==4.3.0
apache-airflow-providers-mysql==3.2.1
apache-airflow-providers-odbc==3.1.2
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==4.1.0
apache-airflow-providers-slack==6.0.0
apache-airflow-providers-snowflake==3.3.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.2.0
```

5. Yes, it's correct

Let me work on 4 above. Thank you so much for the insights

**Comment by sid-habu** [comment]
> > Just for confirm.
> > 
> > 1. You provide AWS Access Key ID, AWS Secret Access Key and role_arn in extra? Because You not masked as `xxxxx` for access key and secret key, so I assume that might be option that you retrieve initial credentials as IAM Profile or somewhere else.
> > 2. Are log files created in S3?
> > 3. Does this issue persist for newly created logs? After you upgrade to 6.1.0
> > 4. Did you also upgrade amazon-provider on webserver? Just ask because logs retrieved from webserver, not scheduler.
> > 5. Could you try to check your credentials by this snippet: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#snippet-to-create-connection-and-convert-to-uri and check is it printed correct role.
> 
> 1. The Access Key and Secret are provided in the Connection UI
> 2. Yes, I see the log files getting generated in the S3
> 3. Yes
> 4. This might be the issue! You are right as `pip freeze` in webserver is still pointing to `6.0.0`
> 
> ```
> apache-airflow-providers-amazon==6.0.0
> apache-airflow-providers-celery==3.0.0
> apache-airflow-providers-cncf-kubernetes==4.4.0
> apache-airflow-providers-common-sql==1.2.0
> apache-airflow-providers-docker==3.2.0
> apache-airflow-providers-elasticsearch==4.2.1
> apache-airflow-providers-ftp==3.1.0
> apache-airflow-providers-google==8.4.0
> apache-airflow-providers-grpc==3.0.0
> apache-airflow-providers-hashicorp==3.1.0
> apache-airflow-providers-http==4.0.0
> apache-airflow-providers-imap==3.0.0
> apache-airflow-providers-microsoft-azure==4.3.0
> apache-airflow-providers-mysql==3.2.1
> apache-airflow-providers-odbc==3.1.2
> apache-airflow-providers-postgres==5.2.2
> apache-airflow-providers-redis==3.0.0
> apache-airflow-providers-sendgrid==3.0.0
> apache-airflow-providers-sftp==4.1.0
> apache-airflow-providers-slack==6.0.0
> apache-airflow-providers-snowflake==3.3.0
> apache-airflow-providers-sqlite==3.2.1
> apache-airflow-providers-ssh==3.2.0
> ```
> 
> 5. Yes, it's correct
> 
> Let me work on 4 above. Thank you so much for the insights

Confirmed, it works after upgrading to `apache-airflow-providers-amazon==6.1.0` on both web server and scheduler. It might be a good idea to update `https://raw.githubusercontent.com/apache/airflow/constraints-2.3.4/constraints-3.7.txt` with `apache-airflow-providers-amazon==6.1.0` as `6.0.0` is broken for S3/Assume role 

```
Reading remote log from s3://habu-stage-kedge-logs/dag_id=airflow-log-cleanup/run_id=scheduled__2022-12-14T00:00:00+00:00/task_id=log_cleanup_worker_num_1_dir_0/attempt=1.log.
[2022-12-15, 00:01:24 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow-log-cleanup.log_cleanup_worker_num_1_dir_0 scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2022-12-15, 00:01:24 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow-log-cleanup.log_cleanup_worker_num_1_dir_0 scheduled__2022-12-14T00:00:00+00:00 [queued]>
```

Thanks once again @Taragolis
