### ISSUE TITLE
Dataproc Generator should allow creating spot instances

### ISSUE THREAD

**Issue by sudohainguyen** [apache/airflow#28399]
### Description

GCP has released their new generation of Preemptible instance called Spot

background: https://cloud.google.com/dataproc/docs/reference/rest/v1/ClusterConfig#preemptibility

`DataprocCreateClusterOperator` should allow passing options for secondary workers to be created as spot instances

### Use case/motivation

as the background: https://cloud.google.com/compute/docs/instances/spot

Spot instances have a some advantages comparing to preemptible ones. And most important is, it can save cost charged by GCP.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Hey @sudohainguyen, did you tried to provide required config into `cluster_config` of [DataprocCreateClusterOperator](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.DataprocCreateClusterOperator)?
See also usage of [Dataproc Operators in Airflow](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/dataproc.html)

**Comment by sudohainguyen** [comment]
hey @Taragolis, yes I tried, but behind of the picture, apparently python dataproc client have not supported SPOT yet, you can check it out here 
https://github.com/googleapis/python-dataproc/issues/506

**Comment by sudohainguyen** [comment]
let me follow closely with the issue from google, will be back when they have any progress regarding this feature

**Comment by sudohainguyen** [comment]
due to the latest change from google (https://github.com/googleapis/python-dataproc/pull/512)
I'm resuming the work from now on

**Comment by sudohainguyen** [comment]
to fulfill the need to create secondary workers as SPOT type, `google-cloud-dataproc` version must be `5.3.0`
