### ISSUE TITLE
Make pandas an optional dependency for amazon provider

### ISSUE THREAD

**Issue by manugarri** [apache/airflow#28468]
### Apache Airflow Provider(s)

amazon

### Apache Airflow version

latest

### Operating System

any

### Deployment

Other

### What happened

First of all, apologies if this is not the right section to post a GH issue. I looked for provider specific feature requests but couldnt find such section.

We use the aws provider at my company to interact from airflow with AWS services. We are using poetry for building the testing environment to test our dags.

However the build times are quite long, and the reason is building pandas, which is a [dependency ](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/provider.yaml#L62) of the amazon provider.

By checking the provider's code, it seems pandas is used in a small minority of functions inside the provider:
```
./aws/transfers/hive_to_dynamodb.py:93:        data = hive.get_pandas_df(self.sql, schema=self.schema)
```
and
```
./aws/transfers/sql_to_s3.py:159:        data_df = sql_hook.get_pandas_df(sql=self.query, parameters=self.parameters)
```

Forcing every AWS Airflow user that do not use hive or want to turn sql into an s3 file to install pandas is a bit cumbersome.

### What you think should happen instead

given how heavy the package is and how little is used in the amazon provider, pandas should be an optional dependency.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
@manugarri Do you use Python 3.7 or Alpine Linux? 

According to https://pypi.org/project/pandas/#files
- No pre-build wheels for Python 3.7 (EOL is 27 Jun 2023)
- No pre-build wheels for [musllinux](https://peps.python.org/pep-0656/)

**Comment by manugarri** [comment]
@Taragolis we use AWS MWAA, so we are stuck with python 3.7 unfortunately :/

**Comment by Taragolis** [comment]
MWAA right now support Airflow 2.2.2 however even if someone add this changes, which to be honest not a straightforward and required introduce breaking chages, it wouldn't be applicable to Airflow<2.3: https://github.com/apache/airflow/blob/main/README.md#release-process-for-providers

However I see at Slack that AWS might add support of new version Airflow into MWAA soon

**Comment by eladkal** [comment]
This is probably leftovers from where pandas was a core dependency.

@o-nikolas @ferruzzi @vincbeck probbaly something worth looking into.

**Comment by potiuk** [comment]
Yeah. Pandas is quite a "drag" as a dependency- regardles if it is a binary wheel or not so making it optional for Amazon provider would be a good idea.

**Comment by potiuk** [comment]
I can even make a draft PR for that - we have a few prior-art cases (plyvel in google provider was pretty similar and we made it optional, we even have the `AirflowOptionalProviderFeatureException` foreseen for the case where people would use an exssting code in the provider and the needed dependency is not installed. It's actually pretty easy to do.

**Comment by vincbeck** [comment]
I dont have much context on this one so if creating a PR for it is easy for you @potiuk, be my guest :) Happy to review it if needed!

**Comment by Taragolis** [comment]
Is it might be better make in optional for all providers where it listed as core dependency?

- amazon
- apache.hive
- exasol
- google
- presto
- salesforce
- trino

**Comment by Taragolis** [comment]
Or where it applicable

**Comment by potiuk** [comment]
> Is it might be better make in optional for all providers where it listed as core dependency?

I can do an example PR for amazon as an example and we can split the job for others :)

**Comment by potiuk** [comment]
BTW. this is one of the 2.3+ features so we are again benefiting from bumping min airflow version

**Comment by potiuk** [comment]
PR in #28505

**Comment by potiuk** [comment]
I told you it should be simple :)

**Comment by manugarri** [comment]
![image](https://user-images.githubusercontent.com/3670355/208924631-2bb78a86-25d6-40b3-930c-60ed6404e573.png)
