### ISSUE TITLE
Airflow 2.2.4 Jenkins Connection - unable to set as the hook expects to be

### ISSUE THREAD

**Issue by petrosbaltzis** [apache/airflow#28465]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello team,

I am trying to use the `JenkinsJobTriggerOperator` version v3.1.0 on an Airflow instance version 2.2.4

Checking the documentation regards how to set up the connection and the hook in order to use `https` instead of the default `http`, I see https://airflow.apache.org/docs/apache-airflow-providers-jenkins/3.1.0/connections.html

```
Extras (optional)

Specify whether you want to use http or https scheme by entering true to use https or false for http in extras. Default is http.

```

Unfortunately from the Airflow UI when trying to specify the connection and especially the `Extras` options it accepts a JSON-like object, so whatever you put differently to a dictionary the code fails to update the extra options for that connection.

Checking in more details what the [Jenkins hook](https://airflow.apache.org/docs/apache-airflow-providers-jenkins/3.1.0/_modules/airflow/providers/jenkins/hooks/jenkins.html#JenkinsHook.conn_name_attr) does:

```
self.connection = connection
connection_prefix = "http"
# connection.extra contains info about using https (true) or http (false)
if to_boolean(connection.extra):
            connection_prefix = "https"
url = f"{connection_prefix}://{connection.host}:{connection.port}"
```

where the `connection.extra` cannot be a simple true/false string!

### What you think should happen instead

Either we should get the `http` or `https` from the `Schema`
Or we should update the [JenkinsHook](https://airflow.apache.org/docs/apache-airflow-providers-jenkins/stable/_modules/airflow/providers/jenkins/hooks/jenkins.html#JenkinsHook.default_conn_name) to read the provided dictionary for http value:

`if to_boolean(connection.extra.https)`

### Operating System

macos Monterey 12.6.2

### Versions of Apache Airflow Providers

```
pip freeze | grep apache-airflow-providers
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-common-sql==1.3.1
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.3
apache-airflow-providers-imap==2.2.0
apache-airflow-providers-jenkins==3.1.0
apache-airflow-providers-sqlite==2.1.0
```

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
This definitely should be changed 🤦 https://github.com/apache/airflow/blob/fefcb1d567d8d605f7ec9b7d408831d656736541/airflow/providers/jenkins/hooks/jenkins.py#L40-L42

@petrosbaltzis If you would like to work on this issue I could assign it to you.

But I want to warn you than any new changes in community providers would not be applicable to Airflow<2.3: https://github.com/apache/airflow/blob/main/README.md#release-process-for-providers

**Comment by petrosbaltzis** [comment]
Hi @Taragolis , Yes please assign it to me I could work on it. 

There is no problem with the release version as well 👍

**Comment by eladkal** [comment]
**The needed fix(s):**
1. `connection.extra` accepts only json while Jenkins conn attempts to set boolean value. This needs to be changed. Probably to:  `{"use_https": true}`
2. in the UI change the fields into something more user friendly. You can use the example of Snowflake provider where it has bool field:

<img width="647" alt="Screenshot 2023-02-20 at 9 29 37" src="https://user-images.githubusercontent.com/45845474/220040183-cf7cf758-af05-4276-8e90-afc839cc4dee.png">


https://github.com/apache/airflow/blob/eff677c418f09690f7e89302368dbff54e7fce75/airflow/providers/snowflake/hooks/snowflake.py#L134-L136

**Comment by pateash** [comment]
@eladkal , I would like to pick this up.
