### ISSUE TITLE
Microsoft Operators has Azure Blob Storage Transfer Operator listed twice

### ISSUE THREAD

**Issue by dnarain** [apache/airflow#28470]
### What do you see as an issue?

URL: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/operators/index.html
Remove second occurrence of Azure Blob Storage Transfer Operator (last item on the list as of right now )

### Solving the problem

Remove second occurrence of Azure Blob Storage Transfer Operator (last item on the list as of right now )

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by snjypl** [comment]
@dnarain  they are both links to  different operators.  one is AzureBlobStorageToGCSOperator and  other is SFTPToWasbOperator . the link needs to be fixed.

**Comment by eladkal** [comment]
resolved in https://github.com/apache/airflow/pull/28559
