### ISSUE TITLE
varimport payloads are not logged in audit logs

### ISSUE THREAD

**Issue by maxdml** [apache/airflow#28474]
### Description

The content of the payload of the /variable/varimport  is not reported to audit logs. 

### Use case/motivation

We should audit this payload in the same way we audit creating/updating/deleting individual variables through the UI

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
@maxdml @potiuk this looks like an interesting issue for me to take up if no one is working on it actively.
New to audit side of things, do we have any docs on how to configure audit logs for an API?

**Comment by potiuk** [comment]
no docs. just code.

**Comment by amoghrajesh** [comment]
Where would be the best place to look for some examples? I am pretty new to this side, but want to explore more

**Comment by amoghrajesh** [comment]
@potiuk how are events added for audit logging in airflow. I am trying to find some docs or code for this but seeming to be lost. Any pointer to look for would be nice here

**Comment by potiuk** [comment]
There is a "log" table. (Log class).

**Comment by amoghrajesh** [comment]
@potiuk @maxdml this issue has been fixed already. Verified that it is not an active issue anymore.
Observe the screenshot below:

![image](https://github.com/apache/airflow/assets/35884252/8b9b4b7f-763f-40a0-a287-fd8cd4409855)

Seems that is was fixed by #24079

**Comment by amoghrajesh** [comment]
IMO, we should close this issue as completed.

**Comment by potiuk** [comment]
Thanks @amoghrajesh . Closing. We can always re-open if the author will find still not fixed.
