### ISSUE TITLE
Kubernetes Executor Config does not support templating

### ISSUE THREAD

**Issue by ginwakeup** [apache/airflow#28489]
### Apache Airflow version

2.5.0

### What happened

I am trying to use an Operator output, or the DAG config params to parametrize the executor_config, but it does not work.

### What you think should happen instead

It should be possible to send Operators outputs and DAG params to executor_config.

### How to reproduce

Create a DAG with two tasks in a Airflow Cluster setup with Kubernetes Executor.
Generate a string from the first task and use it in the executor_config of the second task.

```python
@dag(
...
    params={
        "venv-name": Param("")
    }
)
def createVenv():
...

    volumeOperator = volume.K8sCreateVolumeOperator(
        task_id="create_volume",
        name="{{ params['venv-name'] }}", 
        executor_config={
            "KubernetesExecutor": {
                "volume_mounts": [
                    {"name": "kubeconf", "mountPath": "/secrets"}
                ],
                "volumes": [
                    {
                        "name": "kubeconf",
                        "secret": {"secretName": "airflow-kubeconfig-secret"},
                    }
                ],
            }
        },
    )

    createVenv = BashOperator(
        task_id="create_venv",
        bash_command=f"python -m venv /venvs",
        executor_config={
            "KubernetesExecutor": {
                "volume_mounts": [
                    {"name": "venv", "mountPath": "/venvs"}
                ],
                "volumes": [
                    {
                        "name": "venv",
                        "persistentVolumeClaim": {"claimName": "airflow-pvc-{{ params['venv-name'] }}"},
                    }
                ],
            }
        },
    )
    volumeOperator >> createVenv >> endTask


...
```

### Operating System

Ubuntu20

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Kubernetes Deployment using HELM chart.
Airflow set to use Kubernetes Executor.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Since templating is essentially arbitrary code execution, the operation is strictly confined in the operator worker process. But for the Kubernetes executor, the executor config must be fully resolved before the worker can be run (because the worker runs inside the pod that is created using the executor config). So what you want is unfortunately impossible.

**Comment by uranusjr** [comment]
An approximation to this would be to use the KubernetesPodOperator, which would launch a pod from the worker, and thus can do templating on configuration of the inner pod.
