### ISSUE TITLE
TypeError: Object of type DataflowTemplatedJobStartOperator is not JSON serializable

### ISSUE THREAD

**Issue by dnshah1991** [apache/airflow#28492]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I am trying to trigger dataflow template dynamically using expand() , I am getting this error.

Scenario : 

 ```
   @task
   def load_data():
       return [{a:1}, {b:2}]


  @task
   def trigger_job(param, **kwargs)
        return DataflowTemplatedJobStartOperator(
    // omitting the config
    parameters: param
)


trigger_job.expand(param=load_data())
```

### Operating System

macos

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
In general you can not use in return of task flow operators non-json serialisable object especially return another operator.

But there is nice section exists in documentation how to use [Mapping with non-TaskFlow operators](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dynamic-task-mapping.html#mapping-with-non-taskflow-operators)
