### ISSUE TITLE
"Dependency already registered for DAG" warnings with tasks with multiple outputs

### ISSUE THREAD

**Issue by sdebruyn** [apache/airflow#28499]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow 2.4.3

Just like in issue #26599 I get a lot of warnings saying I'm registering dependencies multiple times. With a little bit of debugging, I found the culprit:.

Some of my tasks have multiple outputs, which are then used by other tasks. These are TaskFlow-based tasks. The task dependency is added when it detects the first XComArg and then it's added again with every following XComArg, generating these warnings.

Call stack:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/963413/208720058-bf66a57c-8849-4fda-9bd4-b570eac4ce93.png">

### What you think should happen instead

You should not see the warnings if the cause is that you're using multiple outputs from the same upstream task.

### How to reproduce

Create a function that returns a `dict[str, str]` and make it a task with `@task(multiple_outputs=True)`. Then create another task that takes multiple of these outputs as input.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

not relevant

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

You can get this with unit tests just by creating a `DagBag` instance with your DAGs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
I think we should do away with this warning

**Comment by vedantlodha** [comment]
@pierrejeambrun @potiuk I dont see any progreess on this issue for a while. Can i take this up if no one else is working? Thanks

**Comment by andrew-stein-sp** [comment]
Just discovered this morning that we're ingesting 2.3 BILLION of these types of logs from airflow into elasticsearch every month... please do away with this warning.

**Comment by arturbrandysonwelo** [comment]
We have this same problem on version 2.5.3 every of our DAGs is disabled right now (because we are moving from an old production environment to a new one) but airflow logs are growing very fast in the log partition.  They are full of Warnings - Dependecy task already registered for DAG.

**Comment by arturbrandysonwelo** [comment]
As a quick workaround, you can set the logging level from INFO to WARNING in _airflow.cfg_ file:
```
[logging]

logging_level = WARNING
```

**Comment by ketozhang** [comment]
Although turning off the warning is pretty easy, there seems to be an underlying inefficiency of re-registering tasks when using Taskflow with multiple output, dynamic generation of tasks, and dynamic task mapping.

@vedantlodha Any thoughts from what you've worked on.

**Comment by ephraimbuddy** [comment]
Fixed in https://github.com/apache/airflow/pull/31502
