### ISSUE TITLE
Question: Can I set airflow configuration parameters from the environment?

### ISSUE THREAD

**Issue by RasterBurn** [apache/airflow#285]
I am running airflow under a heroku-like PaaS.  Can I somehow use environment variables to specify configuration like the `sql_alchemy_conn` and `broker_url` variables?

**Comment by jlowin** [comment]
Funny, I was just looking at this today. As far as I know `ConfigParser` doesn't support env var interpolation; it has to be coded explicitly.

In the past we've used code like this to do a one-time override with env vars during import:

``` python
config = configparser.ConfigParser()

# load config file
config.read_file(airflow_config)

# Check for env vars that overwrite config vars.
# Env vars have the format "airflow_{section}_{key}"
# For example core:sql_alchemy_conn would be overwritten by
# $AIRFLOW_CORE_SQL_ALCHEMY_CONN
for section in config.sections():
    for key, value in config[section].items():
        env = 'AIRFLOW_{s}_{k}'.format(s=section.upper(), k=key.upper())
        if env in os.environ:
            config.set(section, key, os.getenv(env))
```

However, Airflow already uses a custom ConfigParser that checks for default values, so it might be simpler to add the env var check to its `get()` method.

**Comment by mistercrunch** [comment]
I'd approve a PR that does that well. I'm fine env vars having precedence as long as they namespaced in a way that would prevent any collision. There should be an obvious direct mapping with the configuration section and key.

Maybe `AIRFLOW__SECTION__VALUE` (note the double underscores)
