### ISSUE TITLE
rendering public google common hooks base_hook get_credentials public breaks ComputeEngineHook because that class still refers to the private method

### ISSUE THREAD

**Issue by zazaho** [apache/airflow#28573]
### Apache Airflow version

2.5.0

### What happened

I was trying to use the example fo creating a google compute VM instance and the code crashes with a AttributeError: ComputeEngineHook has no attribute _get_credentials

### How to reproduce

modify the ComputeEngineHook to call get_credentials

### Operating System

linux

### Versions of Apache Airflow Providers

latest I believe, not sure 

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zazaho** [comment]
related PR: https://github.com/apache/airflow/pull/28588

**Comment by briva** [comment]
Same pb
