### ISSUE TITLE
Airflow helm chart MEMORY LEAK!!!

### ISSUE THREAD

**Issue by tamis-laan** [apache/airflow#28595]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

latest

### Kubernetes Version

Major:"1", Minor:"25", GitVersion:"v1.25.2

### What happened

After installing the airflow chart the machines memory is filled up. 

### How to reproduce

Run the following script for a basic airflow setup:

``` bash
#! /bin/bash

# Add helm charts
helm repo add apache-airflow https://airflow.apache.org

# Create a cluster
kind create cluster --name experiment

# Set the context
kubectl config set-context experiment

# Install airflow operator
helm upgrade --install airflow apache-airflow/airflow --namespace airflow --create-namespace
```

After this runs the memory will fill up.
![screenshot](https://user-images.githubusercontent.com/3178666/209540140-0373a24d-4bdb-473c-b3b7-4ce6fee835df.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Clearly SOMETHING fills SOME memory. But what it is, whether this memory, whether this is actually a memory that cannot be reclaimed and whether it is at all airflow is not known from what you posted. 

Please provide more details as I could not reproduce it the way you explained it. 

More details needed and more discussion likely if you want us to help you with diagnosing your memory issues.
