### ISSUE TITLE
Exception method for using Airflow with error handling in Slack

### ISSUE THREAD

**Issue by emincanoguz11** [apache/airflow#28665]
### Apache Airflow version

2.5.0

### What happened

Hi everyone,

I have a problem with getting error logs in Slack.
I followed this steps in the order.
I take cURL in logs (I get curl scripts in network at Google Chrome) and I see that logs. After than I take jquery and grep for see only errors locally.
I take in dag for this curl but also I see only numbers. I use os.system().  I don’t know that this situation because of I try locally it is works but I don’t know why it is not worked. (I take os.system() also log in Python script at localhost)
So that I researched another way and I found Exception parameter in Airflow but it is not worked because I see only None.
I excepted that the second step is success for getting error logs in Airflow. But it is not worked in Airflow

![Screen Shot 2023-01-01 at 16 18 11](https://user-images.githubusercontent.com/47830986/210176451-9e086fb1-ca2a-40f1-ba97-434d9c051010.png)
![Screen Shot 2023-01-01 at 16 18 18](https://user-images.githubusercontent.com/47830986/210176452-95841b21-6735-46da-82db-6a704dbe39c2.png)

### How to reproduce

- I searched Airflow source code and I see that exception is used. 
- But I don't understand that is this bug or not because of I don't know that how exception is running?

### Operating System

MacOs

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Could you provide a sample DAG code.

**Comment by potiuk** [comment]
Seems like a discussion/troubleshooting rather than issue - and the description is very difficult to understand. I do not even understand what your problem is @emincanoguz11.

Converting to a discussion - and if you need help add the DAG in question and please explain clearly what the problem is.
