### ISSUE TITLE
Support telegram-bot v20+

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#28670]
### Body

Currently our telegram integration uses Telegram v13 telegram-bot library. On 1st of Jan 2023 a new, backwards incompatible version of Telegram-bot has been released : https://pypi.org/project/python-telegram-bot/20.0/#history and at least as reported by MyPy and our test suite test failures, Telegram 20 needs some changes to work:

Here is a transition guide that might be helpful. 

Transition guide is here: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0

In the meantime we limit telegram to < 20.0.0

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by maxnathaniel** [comment]
@potiuk happy to take a look and work on this

**Comment by potiuk** [comment]
Assigned you !
