### ISSUE TITLE
Improve AWS Batch hook and operator

### ISSUE THREAD

**Issue by gmnmedeiros** [apache/airflow#28680]
### Description

AWS Batch hook and operator do not support the boto3 parameter shareIdentifier, which is required to submit jobs to specific types of queues.

### Use case/motivation

I wish that AWS Batch hook and operator support the submit of jobs to queues that require shareIdentifier parameter.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I see you are willing to add it - assigned you @gmnmedeiros

**Comment by shubham22** [comment]
@gmnmedeiros - just checking in, if you're working on this? Please let us know if you need any help. cc: @o-nikolas

**Comment by gmnmedeiros** [comment]
actually I started looking into this subject but some other things came up and I'll not be able to finish it.. I'm sorry!

**Comment by o-nikolas** [comment]
No worries @gmnmedeiros, thanks for letting us know!

**Comment by phanikumv** [comment]
I will take this up- please assign to me

cc @kaxil @eladkal

**Comment by potiuk** [comment]
assigned you @phanikumv
