### ISSUE TITLE
helmChart values.yaml with log persistence enabled follow the documentation cause errors

### ISSUE THREAD

**Issue by minnieshi** [apache/airflow#28734]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.1

### Kubernetes Version

v1.22.6

### Helm Chart configuration

see below

### What happened

Airflow  official chart 1.7 (default airflow app version 2.4.1) onto Kubernetes cluster (created by KinD, also tried in AKS Azure Kubernetes, same results), attempt to enable log persistence like the documentation here: https://airflow.apache.org/docs/helm-chart/stable/manage-logs.html#celery-worker-log-persistence
says one can enable the log persistence.

details are below:

I had installed airflow see above info, successfully and trying now to upgrade it to use PVC (the SC, PV, PVC have been created successfully, as the state shows Bound) for DAGs and LOGs.
but the helm upgrade fails with failure message (
Error: UPGRADE FAILED: cannot patch "airflow-worker" with kind StatefulSet: StatefulSet.apps "airflow-worker" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
)
the section which are ‘new’ in the values2.yaml is below
which essentially came from above link enable log persistence
```
logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-pvc
```    
I do not really understand why the airflow-worker was a StatefulSet before, and i do not understand why asking for persistence dags, logs would cause this error;

versions
```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.6
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
This is not a problem in the chart but a restriction in kubernetes, as there are some immutable fields in the statefulset (the kubernetes object used to run ariflow worker when the persistence is enabled).
To solve the problem, you can delete `airflow-worker` statefulset and reinstall the helm release in order to recreate the statefulset and attach your existing PVC.

**Comment by minnieshi** [comment]
yes, i have solved the issue with my experienced colleague; and i will update the airflow doc to help others in the future.

**Comment by minnieshi** [comment]
close this issue now.
