### ISSUE TITLE
annotations in logs pvc

### ISSUE THREAD

**Issue by do-it-tim** [apache/airflow#28745]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.5.0

### Kubernetes Version

v1.22.8+d48376b

### What happened

When creating the dags pvc, it is possible to inject annotations to the object.

### What you think should happen instead

There should be the possibility to inject annotations to the logs pvc as well.

### Anything else

We are using annotations on pvc to disable the creation of backup snapshots provided by our company platform. (OpenShift)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add PR adding it @do-it-tim

**Comment by amoghrajesh** [comment]
@potiuk @do-it-tim if nobody is actively developing this, i would be more than happy to take it up. I would require some more context and concrete idea before starting though.

**Comment by do-it-tim** [comment]
Glad to here that. 
There are differences between the creation of dags pvc versus logs pvc.
You can compare these two files:
https://github.com/apache/airflow/blob/main/chart/templates/dags-persistent-volume-claim.yaml#L32-L35
vs
https://github.com/apache/airflow/blob/main/chart/templates/logs-persistent-volume-claim.yaml
There is no possibility to add annotations in the logs pvc.
Hope this helps!
Thanks

**Comment by amoghrajesh** [comment]
Oh, thanks @do-it-tim. It would be nice to accept it from: `.Values.logs.persistence.annotations`?

**Comment by amoghrajesh** [comment]
I can take it up then. @potiuk can I?

**Comment by amoghrajesh** [comment]
@do-it-tim added support for this in https://github.com/apache/airflow/pull/29270.

**Comment by amoghrajesh** [comment]
@potiuk we can close this. It has been merged
