### ISSUE TITLE
Add pre-commit to prevent using xfail tests

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#28768]
### Body

Related https://github.com/apache/airflow/issues/23539

xfail means that you expect a test to fail for some reason.
If we expect a test to fail it should simply be a regular test that make sure the relevant logic fails and in that case we finish the test with success.|
There should be no cases where we see tests ends in failure yet we consider it good - this is very confusing.

This task is about writing pre-commit that will make sure we don't add any xfail test to the project.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by uranusjr** [comment]
But what would be used instead if I do want to mark a test as xfail, i.e. it should pass but currently does not (due to certain reasons, perhaps bugs in dependencies)?

**Comment by eladkal** [comment]
> But what would be used instead if I do want to mark a test as xfail, i.e. it should pass but currently does not (due to certain reasons, perhaps bugs in dependencies)?

If test is flaky it should be mark as quarantined
https://github.com/apache/airflow/issues/28658

**Comment by eladkal** [comment]
By the way if for some reason we must use xfail then its OK to have a list of exclusions but this needs to be intentional by the PR author and verified by reviewer so we can avoid cases like we have now where xfail was used when not really needed.
