### ISSUE TITLE
Add colors in help outputs of Airfow CLI commands

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#28789]
### Body

Folowing up after https://github.com/apache/airflow/pull/22613#issuecomment-1374530689 - seems that there is a new [rich-argparse](https://github.com/hamdanal/rich-argparse) project that might give us the option without rewriting Airflow's argument parsing to click (click has a number of possible performance issues that might impact airlfow's speed of CLI command parsing) 

Seems this might be rather easy thing to do (just adding the formatter class for argparse).

Would be nice if someone implements it and tests (also for performance of CLI).

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Bowrna** [comment]
@potiuk Could I try my hands on a few CLI commands to use rich-argparse?

**Comment by potiuk** [comment]
Sure. But I guess it will be "all-or-nothing"

**Comment by Bowrna** [comment]
@potiuk Do you mean that it should be done either for all the CLI commands or for nothing? Am i right?

**Comment by potiuk** [comment]
I believe so. This is what rich-argparse promises at least. Change formatter and all your commands will get colour.

**Comment by potiuk** [comment]
Just here and see if you can apply it to all argparse https://github.com/hamdanal/rich-argparse
