### ISSUE TITLE
AIP-44 Migrate DagFileProcessorManager._fetch_callbacks to Internal API

### ISSUE THREAD

**Issue by mhenc** [apache/airflow#28784]
https://github.com/apache/airflow/blob/main/airflow/dag_processing/manager.py#L663

**Comment by vincbeck** [comment]
Working on this one as well

**Comment by bugraoz93** [comment]
Hey,
I would like to work on this issue, please.

**Comment by mhenc** [comment]
Can you sync with @vincbeck as he may have covered that part as well:
https://github.com/apache/airflow/pull/28900

**Comment by vincbeck** [comment]
Yeah I think I will include it in #28900

**Comment by bugraoz93** [comment]
Thanks a lot for the update! You are fast :) Let's assign the issue to @vincbeck
