### ISSUE TITLE
AIP-44 Migrate dagbag.sync_to_db to Internal API

### ISSUE THREAD

**Issue by mhenc** [apache/airflow#28786]
This method is used in DagFileProcessor.process_file:
https://github.com/apache/airflow/blob/main/airflow/dag_processing/processor.py#L787

it needs to be changed to static

**Comment by mhenc** [comment]
Also take a look at #28787 while working on this item

**Comment by snjypl** [comment]
@mhenc  is this different from https://github.com/apache/airflow/issues/28615?
