### ISSUE TITLE
Display what checks are available to SQLColumnCheckOperator and all classes that inherit from SQLColumnCheckOperator

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#28807]
### What do you see as an issue?

It's currently impossible to know what checks are available for `SQLColumnCheckOperator` and all classes that inherit from `SQLColumnCheckOperator` (e.g. `BigQueryColumnCheckOperator`) without reviewing the source code.

### Solving the problem

Users should be able to see the checks in the documentation without needing to review source code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
It's  very nicely described in https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/operators.html

If you think you need anything more or somewhat discover it better - i encourage you to make PRs.

**Comment by RNHTTR** [comment]
Sorry -- not sure how I missed that!
