### ISSUE TITLE
statsd metric for dataset count

### ISSUE THREAD

**Issue by ghost** [apache/airflow#28803]
### Description

A count of datasets that are currently registered/declared in an Airflow deployment.

### Use case/motivation

Would be nice to see how deployments are adopting datasets.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Nice one to add. Marked as good first issue.

**Comment by hussein-awala** [comment]
@potiuk can you please assign it to me?

**Comment by potiuk** [comment]
Assigned you
