### ISSUE TITLE
Make Kubernetes Scheduler Logs Uniform with Celery Executor when reporting TaskInstance Finished

### ISSUE THREAD

**Issue by frank-ye** [apache/airflow#28814]
### Description

To properly export logs into third party vendor logging software, it'd be useful to report uniform logs for task instances that have successfully completed. Currently, the scheduler logging is quite different for KubeExecutor vs CeleryExecutor.

### Use case/motivation

Given a query checking for scheduler logs, we'd be able to count and aggregate the number of logs with `TaskInstance Finished` and a corresponding task instance state.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
This was done in #28871.
