### ISSUE TITLE
Broken macro support in `DataProcJobBuilder` `task_id` parameter

### ISSUE THREAD

**Issue by rafalh** [apache/airflow#28810]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

8.5.0

### Apache Airflow version

2.3.4

### Operating System

Linux

### Deployment

Composer

### What happened

I am passing string containing macros to `DataProcJobBuilder` `task_id` parameter:

```
{{ (dag.dag_id + '-' + task.task_id.replace('_', '-'))[:90] }}
```

I use created job with `DataprocSubmitJobOperator`.
It worked fine in composer-2.0.27-airflow-2.2.5 (apache-airflow-providers-google==2022.9.6+composer). Now I tried upgrading to composer-2.1.2-airflow-2.3.4 (apache-airflow-providers-google==8.5.0) and it no longer works because after #23791 all "." are replaced by "_" before macro evaluation. It causes error: 
```
'dag_dag_id' is undefined
```

### What you think should happen instead

Optimally `DataProcJobBuilder` should allow using macros as before.
PR that broke this usage was supposed to fix task groups (#23439). Perhaps that fix (string replacement) could be moved to a different place e.g. `DataprocJobBaseOperator` default value. This way API of DataProcJobBuilder would still allow macros. 

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The replacement should be done AFTER running JINJA. Anyone wants to provide a fix? (@eladkal :) ? )
