### ISSUE TITLE
Graph UI: Add Filter Downstream & Filter DownStream & Upstream

### ISSUE THREAD

**Issue by r-richmond** [apache/airflow#28847]
### Description

Currently Airflow has a `Filter Upstream` View/option inside the graph view. (As documented [here](https://docs.astronomer.io/learn/airflow-ui#graph-view) under `Filter Upstream`)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/9246654/211711759-670a1180-7f90-4ecd-84b0-2f3b290ff477.png">

It would be great if there were also the options
1. `Filter Downstream` &
2. `Filter Downstream & Upstream`

### Use case/motivation

Sometimes it is useful to view downstream tasks & down & upstream tasks when reviewing dags. This feature would make it as easy to view those as it is to view upstream today.

### Related issues

I found nothing with a quick search

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yxiao1996** [comment]
looks like an interesting idea, may I take a shot at this?

**Comment by potiuk** [comment]
Feel free.

**Comment by yxiao1996** [comment]
Took a look at the code, seems to me this should be a rather small change as we have the capacity to query downstreams of a task in a dag already defined in the dag data model class([code](https://github.com/apache/airflow/blob/264ace5f86e560d09444b833556074363b055f81/airflow/models/dag.py#L2153)). 

Think that we need to make changes in the following places:
* Update UI to include new filtering method in template([code](https://github.com/apache/airflow/blob/main/airflow/www/templates/airflow/graph.html))
* Update [callModal.js](https://github.com/apache/airflow/blob/main/airflow/www/static/js/callModal.js#L140) to attach handlers for new filtering options.
* Need to extend query string of the [graph view function](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2910) to support new filtering options. Currently its assuming we are only filtering upstream.
* Need to extend this [updateQueryStringParameter](https://github.com/apache/airflow/blob/264ace5f86e560d09444b833556074363b055f81/airflow/www/static/js/callModal.js#L25) function to support new filtering options.

**Comment by yxiao1996** [comment]
probably unrelated, `breeze start-airflow --dev-mode` looks broken for me with error message saying asset compilation fail. Without the `--dev-mode` flag it runs alright.

```
admin already exist in the db

The asset compilation failed. Exiting.
```

**Comment by yxiao1996** [comment]
coded the filter downstream functionality, looks like this:

original graph
![Screenshot_20230129_102657](https://user-images.githubusercontent.com/27112484/215348002-605ed49d-90dd-4e42-8ea3-c1c77927acdb.png)

update the filter upstream button to filter tasks downdrop with 2 options:

![Screenshot_20230129_102718](https://user-images.githubusercontent.com/27112484/215348032-28990e42-753a-4f0c-98d3-d8275511cacd.png)

After filtering downstream for one of the tasks
![Screenshot_20230129_102737](https://user-images.githubusercontent.com/27112484/215348117-659df100-63fa-4afb-9b5f-9d7a9c34c108.png)

**Comment by potiuk** [comment]
> probably unrelated, `breeze start-airflow --dev-mode` looks broken for me with error message saying asset compilation fail. Without the `--dev-mode` flag it runs alright.

Fix to this problem in #29225 (thanks for commenting that it does not work - I broke --dev-mode accidentally when fixing regular asset compilation few days ago)

**Comment by yxiao1996** [comment]
thanks for fixing.

**Comment by yxiao1996** [comment]
put up a PR: https://github.com/apache/airflow/pull/29226

**Comment by r-richmond** [comment]
Hey @yxiao1996 this looks great. 2 questions for you

1) For your example `After filtering downstream for one of the tasks`  which task_id did you click on & which option did you select?
2) If you select either option and navigate to the grid view dues the filter on tasks remain? (It does this currently).

Then lastly as a weak suggestion that can be disregarded due to my tardiness in getting back to you. Would it be worth keeping the same style of interface as the Task Actions? See my rough mockup below (note: the additional functionality provided with the recursive option)


<img width="589" alt="Screenshot 2023-01-31 at 10 07 44" src="https://user-images.githubusercontent.com/9246654/215846382-68b33ed7-b14f-400c-a00d-43f8a741d466.png">
