### ISSUE TITLE
Wrong GitHub Link provided in Documentation

### ISSUE THREAD

**Issue by Lokeshrathi** [apache/airflow#28866]
### What do you see as an issue?

The Gitbhub link provided in the Documentation page "https://airflow.apache.org/docs/apache-airflow/2.2.1/concepts/dags.html" under "Suggest a change on this page" is wrong.

Present: https://github.com/apache/airflow/edit/main/docs/apache-airflow/concepts/dags.rst

Correct : https://github.com/Lokeshrathi/airflow/blob/main/docs/apache-airflow/core-concepts/dags.rst

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
It should regenerated for new version of Airflow when it released, this change https://github.com/apache/airflow/pull/27235 not applied yet

**Comment by potiuk** [comment]
Yep. We had structure change that will be reflected when we relese 2.6.0
