### ISSUE TITLE
ComputeEngineHook object has no attribute '_get_credentials'

### ISSUE THREAD

**Issue by djpalm801** [apache/airflow#28864]
### Apache Airflow version

2.5.0

### What happened

When trying to use the ComputeEngineInsertInstanceFromTemplateOperator I get an error stating that the ComputeEngineHook doesn't have a _get_credentials() attribute.  The stack trace is:

> Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/compute.py", line 379, in execute
    existing_instance = hook.get_instance(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/compute.py", line 343, in get_instance
    client = self.get_compute_instance_client()
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/compute.py", line 87, in get_compute_instance_client
    return InstancesClient(credentials=self._get_credentials(), client_info=self.client_info)
AttributeError: 'ComputeEngineHook' object has no attribute '_get_credentials'

### What you think should happen instead

The GoogleBaseHook, which is the super class of the ComputeEngineHook has a get_credentials() method that I believe should be called.  Either that, or the ComputeEngineHook needs to implement a _get_credentials() method.

### How to reproduce

Create a DAG that uses any of the ComputeEngine operators and run it.

### Operating System

Cloud Composer

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.5.0

### Deployment

Composer

### Anything else

I'd be interested to see if there is a work around since I will have to wait for google to support a newer version of airflow that contains a fix.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by djpalm801** [comment]
Forgot to include the line of code in question: https://github.com/apache/airflow/blob/352d492c66e69e816fb1547e46fc1e3b7ba32066/airflow/providers/google/cloud/hooks/compute.py#L83

**Comment by Taragolis** [comment]
@djpalm801 it it possible that you issue also related to this PR: https://github.com/apache/airflow/pull/28588 ?

**Comment by djpalm801** [comment]
Looks like it, thanks.
