### ISSUE TITLE
`webserver.instance_name` shows markup text in `<title>` tag

### ISSUE THREAD

**Issue by IAL32** [apache/airflow#28888]
### Apache Airflow version

2.5.0

### What happened

https://github.com/apache/airflow/pull/20888 enables the use of markup to style the `webserver.instance_name`.
However, if the instance name has HTML code, this will also be reflected in the `<title>` tag, as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/562969/212091882-d33bb0f7-75c2-4c92-bd4f-4bc7ba6be8db.png)

This is not a pretty behaviour.

### What you think should happen instead

Ideally, if `webserver. instance_name_has_markup = True`, then the text inside the `<title>` should be stripped of HTML code.

For example:
- Set `webserver.instance_name` to some text with markup, like `<b style="color: red">title</b>`
- Set `webserver.Instance_name_has_markup` to `true`

This is how the `<title>` tag should look like:

```html
<title>DAGs - title</title>
```

Instead of:

```
<title>DAGs - &lt;b style=&#34;color: red&#34;&gt;title&lt;b&gt;</title>
```

### How to reproduce

- Airflow version 2.3+, which is [when this change has been introduced](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#instance-name-has-markup)
- Set `webserver.instance_name` to some text with markup, like `<b style="color: red">title</b>`
- Set `webserver.Instance_name_has_markup` to `true`

### Operating System

Doesn't matter

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
@IAL32 are you actively working on this? I see the PR was not merged. I can take it forward.

**Comment by potiuk** [comment]
Assigned you @amoghrajesh

**Comment by IAL32** [comment]
@amoghrajesh hello there! I mean, the PR https://github.com/apache/airflow/pull/28894 is ready, so there is not much to bring forward unfortunately 😅 feel free to pitch in, though!
