### ISSUE TITLE
Azure Blob storage exposes crendentials in UI

### ISSUE THREAD

**Issue by blcksrx** [apache/airflow#28884]
### Apache Airflow version

Other Airflow 2 version (please specify below)
2.3.3

### What happened

Azure Blob Storage exposes credentials in the UI

<img width="1249" alt="Screenshot 2023-01-12 at 14 00 05" src="https://user-images.githubusercontent.com/35199552/212072943-adca75c4-2226-4251-9446-e8f18fb22081.png">

### How to reproduce

Create an Azure Blob storage connection. then click on the edit button on the connection.

### Operating System

debain

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The fix for that would be to hide extra field, if someone would like to do it, that would be cool.

**Comment by potiuk** [comment]
Examples can be found how other hooks do it.
