### ISSUE TITLE
A way to set an environment variable as a sensible config

### ISSUE THREAD

**Issue by portoedu** [apache/airflow#28898]
### Description

A way to set an environment variable as a sensible config so that airflow hides it in the configuration page.

### Use case/motivation

For security measures, we set the AIRFLOW__WEBSERVER__EXPOSE_CONFIG to non-sensitive-only so that Airflow hides a lot of information in the Configuration web page.

![image](https://user-images.githubusercontent.com/19151446/212171377-aaaa774f-9008-4e75-9e0b-1df1d0d1ffa2.png)

There are a lot of non sensible information that is also being hidden, why?
A few examples:
![image](https://user-images.githubusercontent.com/19151446/212175610-9e2d08ce-1b05-4e91-bcdf-97bd8306dc2d.png)
![image](https://user-images.githubusercontent.com/19151446/212175330-ada136a9-99a4-461a-a400-34ce50269f0c.png)
![image](https://user-images.githubusercontent.com/19151446/212175359-403c795e-de01-4508-8488-1d74677e5e5b.png)
![image](https://user-images.githubusercontent.com/19151446/212175487-266f8838-48b9-45c4-a338-ed8d252f6e98.png)

We use an authentication provider for the login and there are some parameters that we need to set for this to work, a few examples of these parameters are "client_id" and "client_secret". Since we set this using env vars, the straightforward and simple way is to set the section as auth (or something similar) and the name to the required parameter.
An example is AIRFLOW__GENERIC_OAUTH__CLIENT_ID that we use to set the client_id parameter of auth.

But here's the problem, airflow hides all of these auth env vars parameters except "AIRFLOW__GENERIC_OAUTH__CLIENT_SECRET". After a lot of research we couldn't find a way to set this information as sensible to the airflow configuration, we only could set the [AIRFLOW__CORE__SENSITIVE_VAR_CONN_NAMES](https://airflow.apache.org/docs/apache-airflow/2.4.2/configurations-ref.html#sensitive-var-conn-names) that doesn't work for the configuration page. 

![image](https://user-images.githubusercontent.com/19151446/212175040-c39ca780-0ae3-4147-be67-cdc427404274.png)

Then, we found this [documentation](https://airflow.apache.org/docs/apache-airflow/2.4.2/howto/set-config.html) which says that if we append _secret to a env var airflow will considers it as a connection string to be used at runtime.  

We are using the airflow version 2.4.2.

Work Around: Don't use environment variables that ends with _secret (or _cmd), instead use _sekret or _token.

![image](https://user-images.githubusercontent.com/19151446/212171545-9f916ba1-fde3-4a81-9e58-0f7e48c84d61.png)
![image](https://user-images.githubusercontent.com/19151446/212175146-681258ce-53c1-4826-bed9-b33bbddfda04.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Looks like this is affected by #28756 and the proposed solution wouldn’t be needed since that is fixed?

**Comment by eladkal** [comment]
closing as solved in https://github.com/apache/airflow/pull/28802
