### ISSUE TITLE
Pgbouncer metrics exporter restarts

### ISSUE THREAD

**Issue by JeremieDoctrine** [apache/airflow#28891]
### Official Helm Chart version

1.6.0

### Apache Airflow version

2.4.2

### Kubernetes Version

1.21

### Helm Chart configuration

Nothing really specific

### What happened

From time to time we have pg_bouncer metrics exporter that fails its healthcheck.

When it fails its healtchecks three times in a row, pgbouncer stop being reachable and drops all the ongoing connection.

Is it possible to make the pgbouncer healtcheck configurable at least the timeout parameter of one second that seems really short?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
feel free to make it configurable.
