### ISSUE TITLE
Misnamed param in EcsRunTaskOperator

### ISSUE THREAD

**Issue by deanmorin** [apache/airflow#28910]
### What do you see as an issue?

In the `EcsRunTaskOperator`, one of the params in the docstring is `region_name`, but it should be `region`:

https://github.com/apache/airflow/blob/2.5.0/airflow/providers/amazon/aws/operators/ecs.py#L281

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
Good catch! It is definitely a very easy code change to make :) Would you want to do it 
@deanmorin?

**Comment by deanmorin** [comment]
Yes sorry for the slow reply @vincbeck I can do this. I found an actual bug so I'll need to figure out the PR process anyway
