### ISSUE TITLE
Empty Graph view if DAG contains Dynamic Task Mapping

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#28988]
### Apache Airflow version

main (development)

### What happened

In current `main` if DAG contain Dynamic Task Mapping it doesn't show in Graph View, it is not affected Grid View
This problem not exists in 2.5.0

**Grid View** (work as expected)
![image](https://user-images.githubusercontent.com/3998685/212898620-c10c7f1c-a341-45d7-a0e2-670e2eb571be.png)

**Graph View** (empty)
![image](https://user-images.githubusercontent.com/3998685/212898671-df29fad7-8755-4fc6-9e71-d8ad0dfb9b5a.png)

**Development Console (F12) Console Logs**

```console
DevTools failed to load source map: Could not load content for http://127.0.0.1:28080/static/appbuilder/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

graph.78011973b3d1b76efe64.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at e (graph.78011973b3d1b76efe64.js:2:19908)
    at graph.78011973b3d1b76efe64.js:2:20208
    at Array.map (<anonymous>)
    at e (graph.78011973b3d1b76efe64.js:2:20184)
    at graph.78011973b3d1b76efe64.js:2:29704
    at graph.78011973b3d1b76efe64.js:2:29758
    at graph.78011973b3d1b76efe64.js:2:29764
    at graph.78011973b3d1b76efe64.js:2:222
    at graph.78011973b3d1b76efe64.js:2:227
e @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2
e @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2
(anonymous) @ graph.78011973b3d1b76efe64.js:2

moment.197a6f3cab42e240f8bd.js:2 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2023-01-17T12:26:22T+00:0017, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:10753)
    at vo (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:35093)
    at Ko (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:38425)
    at Fo (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:38292)
    at jo (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:38011)
    at Vo (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:38783)
    at Qo (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:38817)
    at e (http://127.0.0.1:28080/static/dist/moment.197a6f3cab42e240f8bd.js:2:7629)
    at HTMLTimeElement.<anonymous> (http://127.0.0.1:28080/static/dist/graph.78011973b3d1b76efe64.js:2:4108)
    at Function.each (http://127.0.0.1:28080/static/appbuilder/js/jquery-latest.js:2:3003)

```

### What you think should happen instead

Graph view should show DAG if it contain Dynamic Task Mapping. 

### How to reproduce

Use example `example_dynamic_task_mapping` DAG and go to Graph View 

https://github.com/apache/airflow/blob/65010fda091242870a410c65478eae362899763b/airflow/example_dags/example_dynamic_task_mapping.py#L19-L38

### Operating System

Linux/macOS

### Versions of Apache Airflow Providers

n/a

### Deployment

Other Docker-based deployment

### Deployment details

breeze

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
It is also affects [2.5.1rc1](https://pypi.python.org/pypi/apache-airflow/2.5.1rc1), I'm not familiar with JS but according info from DevTools the error happen here:

https://github.com/apache/airflow/blob/78b72f4fa07cac009ddd6d43d54627381e3e9c21/airflow/www/static/js/graph.js#L93-L94

**Comment by potiuk** [comment]
might be a reason to do rc2 @pierrejeambrun @ephraimbuddy

**Comment by ephraimbuddy** [comment]
Cc @bbovenzi

**Comment by pierrejeambrun** [comment]
I can't reproduce the issue.

The screenshot is from main using breeze. (postgres, python 3.8).

@potiuk @ephraimbuddy do you manage to reproduce locally ? 

![image](https://user-images.githubusercontent.com/14861206/212969097-030cb951-a866-4be9-9be0-99c3977e0d30.png)

**Comment by pierrejeambrun** [comment]
What db/python version/executor are you using ? Maybe it is tied to a specific configuration ?

**Comment by Taragolis** [comment]
`main`: Postgres, Python 3.7, LocalExecutor
`2.5.1rc1`: Postgres, Python 3.9, LocalExecutor

**Comment by Taragolis** [comment]
@pierrejeambrun problem in Graph not in Grid.

**Comment by pierrejeambrun** [comment]
:man_facepalming:

**Comment by pierrejeambrun** [comment]
Yep, guess we need rc2
