### ISSUE TITLE
Multiple dag_folder locations

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#290]
I am thinking about having multiple `DAG_FOLDER` locations.

I have multiple projects that are creating DAGs for the same Airflow server, and I want each project's DAGs to be tracked in git along with the project itself. This means that they can't share a common `DAG_FOLDER`, as would be required currently.

Instead, I'd like to provide a new config option `OTHER_DAG_FOLDERS` (or something) to Airflow where it will look for additional DAGs. This way, users can save DAGs in each project's individual `DAG_FOLDER` and the project repos can be cloned to the Airflow server, where all the DAGs are loaded. No user has to have access to a common folder (or even to the server). Bonus points: the UI could show the project folder that each DAG comes from, for clarity and sorting.

I think this is fairly easy to do (essentially just change `DagBag` to accept a list of folders) but wanted to see if anyone has a better idea first.

**Comment by mistercrunch** [comment]
Could you just use symlinks to do this? I think you can tell `os.walk` (in the DagBag method) to follow symlinks and that by default it's set to `False`.

**Comment by jlowin** [comment]
Ah, I had tried that -- but I never knew about that option for `os.walk`! This should work perfectly -- thanks. The lesson once again: never bet against "batteries included".
