### ISSUE TITLE
TaskFlow DAGs don't register implicitly

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#29009]
### Apache Airflow version

2.5.0

### What happened

TaskFlow `@dag`s don't register without explicitly calling the function that defines it. 

### What you think should happen instead

My understanding is that since Airflow 2.4 DAGs don't require explicit registration as a global object anymore (this is also mentioned in https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html#instantiate-a-dag). However, this seems to only be true for the classic style and not for taskflow style DAGs.

### How to reproduce

```python
import datetime

from airflow import DAG
from airflow.decorators import dag, task
from airflow.operators.empty import EmptyOperator

with DAG(dag_id="no_global_dag_registration", start_date=datetime.datetime(2023, 1, 1), schedule=None):
    EmptyOperator(task_id="test")


@dag(start_date=datetime.datetime(2023, 1, 1), schedule=None)
def no_global_dag_registration_taskflow():
    @task
    def test():
        pass
```

My understanding both styles should register the DAG, however only DAG "no_global_dag_registration" does. For the taskflow-style DAG I have to call `no_global_dag_registration_taskflow()` for it to register.

### Operating System

varying

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Maybe doc has not clear description, but it actually mentioned how it work.

```
Changed in version 2.4: It’s no longer required to “register” the DAG
into a global variable for Airflow to be able to detect the dag if that DAG 
is used inside a with block, or if it is the result of a @dag decorated function.
```

My understanding of differences 

```python
# Before Airflow 2.4
dag = decorated_function()
# or
_ = decorated_function()

with DAG(...) as daaaag:
    ...


# SInce Airflow 2.4
decorated_function()

with DAG(...):
    ...
```

**Comment by BasPH** [comment]
Could you provide a working example? I'm not following your code example.

My point is that:
```python
with DAG(...):
```
Indeed works, so without having to write `as dag`.

However, this does not:
```python
@dag(...)
def mydag():
    ...
```

You have to call `mydag()` for Airflow to register the decorated DAG function. According to the docs this should not be necessary?

**Comment by BasPH** [comment]
Doh! I'll make a PR for the docs to clarify this.
