### ISSUE TITLE
Prevent templated field logic checks in `__init__` of operators automatically

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#29069]
### Body

It happens all-too-often that in our operators we have some initialization logic that checks the content of templated fields or generally parameters passed to the operators. This however has an adverse effect that if those checks assume some content or type of those fields, there are a number of cases that those checks are wrong.

Example here: https://github.com/apache/airflow/issues/27328

We should have a way to automatically check if someone is performing such logical checks in all our operators.

This has been initially discussed here: https://github.com/apache/airflow/issues/27328#issuecomment-1386626513 and there are some ideas how this might be done.

However we are open for any way of doing it

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
@eladkal Please assign me

**Comment by potiuk** [comment]
Done

**Comment by ephraimbuddy** [comment]
@shahar1, are you still working on this?

**Comment by shahar1** [comment]
> @shahar1, are you still working on this?

I started working on it a while ago, I paused due to some personal circumstances.
I'll try to get back to it in the next few days.
