### ISSUE TITLE
FTP operator has logic in __init__

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#29070]
### Body

Similarly to SFTP (fixed in https://github.com/apache/airflow/pull/29068) the logic from __init__ should be moved to execute.

The #29068 provides a blueprint for that.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by snjypl** [comment]
@potiuk  can you please assign this to me?

**Comment by potiuk** [comment]
did :)
