### ISSUE TITLE
Add `max_active_tis_per_dagrun` for Dynamic Task Mapping

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#29084]
### Description

Currently we cannot restrict how many ti can be running at the same time in the same Dag Run, we can set `max_active_tis_per_dag` or use a dedicated pool to restrict how many ti can be running at the same time in all the Dag Runs of the dags.

This option was not useful before the Dynamic Task Mapping  because we had one ti in each dag, but now I think it's necessary to control the parallelism in each Dag Run.

### Use case/motivation

Control the Dynamic Task Mapping  parallelism in each Dag Run.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Is it only related to Dynamic Task Mapping?
I think it should be set on DAG level and work with `DAG.max_active_tasks` and `DAG.max_active_runs` as well as other concurrency limitation:

`DAG.max_active_tasks_per_tun` x  `DAG.max_active_runs` <= `DAG.max_active_tasks`

**Comment by hussein-awala** [comment]
It will be available as parameter for `BaseOperator` for Dynamic Task Mapping and normal tasks, but it will be useful only in the Dynamic Task Mapping case, where in the normal tasks, the number of the active tis per run is always <=1.

> I think it should be set on DAG level and work with DAG.max_active_tasks and DAG.max_active_runs as well as other concurrency limitation:
DAG.max_active_tasks_per_tun x DAG.max_active_runs <= DAG.max_active_tasks

It's more a task configuration than dag configuration similar to `max_active_tis_per_dag`.
There is a big difference between `max_active_tasks` which control the number of task instances allowed to run concurrently in all the dag runs, and `max_active_tis_per_dag` which control the number of task instances for **a specific task** allowed to run concurrently in all the dag runs.

The configuration I propose is similar to `max_active_tis_per_dag` but in each run.

**Comment by uranusjr** [comment]
I can see how this is different from DAG-level configuration, but am still unsure why DAG-level configurations can’t satisfy the need. Is there a practical use case this would be required?

**Comment by hussein-awala** [comment]
I have two different use cases for this feature:
- I have an API used by the users to submit ML processing requests for some data by a list of models (they choose a subset from ~30 models), this requests are sent to Kafka and processed by a stream app which create a `DagRun` for each request via the REST API, then the dag process the data in parallel by each chosen model. Currently the requests are processed in FIFO method, and I cannot set a quota for each DagRun, so if a client requested a big set of models, the other requests will stay in `queued` state until the end of its run. With the new conf, I can set a quota for each request (5 max parallel processing/request) which lead to a FAIR scheduling method.
- Another use case is any parallel workload on a database sharded/partitioned by date, where we cannot create a pool for each partition, and reducing the `max_active_tis_per_dag` is not the best solution, where the other partitions can be on a different shard, and processing them is not a problem, so we just need to reduce parallelism for each partition.

**Comment by potiuk** [comment]
I see the need, but I think having a parameter for that in in DAG is not the best way of doing it. 
For me it should be strictly dynamic task mapping parameter and more than that - you should be able to configure it separately for each dynamic task mapping. Why not something like that:

```
task.expand(x=[2, 4, 8], y=[5, 10]).max_active_tasks(30) 
```

Sounds much more in-line with task flow/functional approach.

**Comment by hussein-awala** [comment]
I agree, I added it as a task parameter in #29094 :
```python
import time
import pendulum

from airflow.decorators import dag, task

@dag(
    dag_id='dag',
    default_args={},
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    schedule=None
)
def processing_dag():

    @task
    def get_numbers():
        return list(range(20))

    @task(max_active_tis_per_dagrun=2)
    def process(number):
        time.sleep(5)
        return number

    numbers = get_numbers()

    process.expand(number=numbers)


my_dag = processing_dag()
```
I'll check how can I add it as dynamic task mapping parameter and use it in the schedule job.
