### ISSUE TITLE
graph disappears during run time when using branch_task and a dynamic classic operator

### ISSUE THREAD

**Issue by talnagar** [apache/airflow#29105]
### Apache Airflow version

2.5.1

### What happened

when using a dynamically generated task that gets the expand data from xcom after a branch_task the graph doesn't render. 
It reappears once the dag run is finished. 
tried with BashOperator and a KubernetesPodOperator. 

the developer console in the browser shows the error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at z (graph.1c0596dfced26c638bfe.js:2:17499)
    at graph.1c0596dfced26c638bfe.js:2:17654
    at Array.map (<anonymous>)
    at z (graph.1c0596dfced26c638bfe.js:2:17646)
    at graph.1c0596dfced26c638bfe.js:2:26602
    at graph.1c0596dfced26c638bfe.js:2:26655
    at graph.1c0596dfced26c638bfe.js:2:26661
    at graph.1c0596dfced26c638bfe.js:2:222
    at graph.1c0596dfced26c638bfe.js:2:227
z @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
z @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
(anonymous) @ graph.1c0596dfced26c638bfe.js:2
`

grid view renders fine. 

### What you think should happen instead

graph should be rendered. 

### How to reproduce

```@dag('branch_dynamic', schedule_interval=None, default_args=default_args, catchup=False)
def branch_dynamic_flow():
    @branch_task
    def choose_path():
        return 'b'


    @task
    def a():
        print('a')

    @task
    def get_args():
        return ['echo 1', 'echo 2']

    b = BashOperator.partial(task_id="b").expand(bash_command=get_args())
    path = choose_path()
    path >> a()
    path >> b

```

### Operating System

red hat

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes | 5.1.1 | Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I can assign you @talnagar if you would like to take a stab on it?

**Comment by josh-fell** [comment]
Can reproduce with Breeze `breeze start-airflow --use-airflow-version 2.5.1`:

https://user-images.githubusercontent.com/48934154/214113365-655f40d3-49a2-44fe-bc18-cc69293938b0.mov

Console also shows an additional related error message when I tested:
```bash
Uncaught TypeError: t[a].mapped_states is undefined
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
graph.1c0596dfced26c638bfe.js:2:17406
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    map self-hosted:221
    z http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
    <anonymous> http://localhost:28080/static/dist/graph.1c0596dfced26c638bfe.js:2
```

**Comment by bbovenzi** [comment]
PR to fix is already open. https://github.com/apache/airflow/pull/29042

**Comment by talnagar** [comment]
so looks like a duplicate and will be resolved with the next release. thanks!
