### ISSUE TITLE
[Doc] Link to examples how to use FTP provider is incorrect

### ISSUE THREAD

**Issue by Draqun** [apache/airflow#29128]
### What do you see as an issue?

HI.
I tried to use FTP provider (https://airflow.apache.org/docs/apache-airflow-providers-ftp/stable/connections/ftp.html#howto-connection-ftp) but link to the "Example DAGs" is incorrect and Github response is 404.

### Solving the problem

Please update links to Example DAGs - here and check it in other providers.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/29134 should fix it. meanwhile, you can get the example from https://github.com/apache/airflow/blob/providers-ftp/3.3.0/tests/system/providers/ftp/example_ftp.py
