### ISSUE TITLE
Use latest azure-mgmt-containerinstance (10.0.0) which depricates network_profile and adds subnet_ids

### ISSUE THREAD

**Issue by binnisb** [apache/airflow#29127]
### Description

network_profile has been depricated in container instances. azure-mgmt-containerinstance has added subnet_ids. The operator should move to later version of azure-mgmt-containerinstace and replace network_profile with subnet_ids.

### Use case/motivation

There are no network profiles in the resource group to point to so I am unable to add a container group to a subnet.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This is something waiting for one of Azure users to do it
https://github.com/apache/airflow/blob/911b708ffddd4e7cb6aaeac84048291891eb0f1f/airflow/providers/microsoft/azure/provider.yaml#L59-L61

Will you open a PR?

**Comment by binnisb** [comment]
I can do that if I get it working for our use case. I have 2 week so if I haven't opened a PR by then I will not have time to do it.

**Comment by eladkal** [comment]
I'm closing this issue as we normally don't keep issues open for updating libraries.
feel free to raise PR
