### ISSUE TITLE
Fix access to context in functions decorated by task.sensor

### ISSUE THREAD

**Issue by Thomas-McKanna** [apache/airflow#29137]
### Description

Hello, I am a new Airflow user. I am requesting a feature in which the airflow context (containing task instance, etc.) be available inside of functions decorated by `airflow.decorators.task.sensor`.

### Use case/motivation

I have noticed that when using the `airflow.decorators.task` decorator, one can access items from the context (such as the task instance) by using `**kwargs` or keyword arguments in the decorated function. But I have discovered that the same is not true for the `airflow.decorators.task.sensor` decorator. I'm not sure if this is a bug or intentional, but it would be very useful to be able to access the context normally from functions decorated by `task.sensor`.

I believe this may have been an oversight. The `DecoratedSensorOperator` class is a child class of `PythonSensor`:

https://github.com/apache/airflow/blob/1fbfd312d9d7e28e66f6ba5274421a96560fb7ba/airflow/decorators/sensor.py#L28

This `DecoratedSensorOperator` class overrides `poke`, but does not incorporate the passed in `Context` object before calling the decorated function:

https://github.com/apache/airflow/blob/1fbfd312d9d7e28e66f6ba5274421a96560fb7ba/airflow/decorators/sensor.py#L60-L61

This is in contrast to the `PythonSensor`, whose `poke` method merges the context with the existing `op_kwargs`:

https://github.com/apache/airflow/blob/1fbfd312d9d7e28e66f6ba5274421a96560fb7ba/airflow/sensors/python.py#L68-L77

This seems like an easy fix, and I'd be happy to submit a pull request. But I figured I'd start with a feature request since I'm new to the open source community.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Feel free to make a PR

**Comment by BrunoGrandePhD** [comment]
I see that a PR to address this is already open and already approved by at least one reviewer, but if anyone else stumbles upon this issue, you can use `airflow.operators.python.get_current_context()` as a temporary solution to access context variables ([docs](https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html#:~:text=Also%2C%20sometimes%20you%20might%20want%20to%20access%20the%20context%20somewhere%20deep%20in%20the%20stack%2C%20but%20you%20do%20not%20want%20to%20pass%20the%20context%20variables%20from%20the%20task%20callable.%20You%20can%20still%20access%20execution%20context%20via%20the%20get_current_context%20method.)).
