### ISSUE TITLE
Auto refreshing (or auto tail) of logs in Web UI is erroneous 

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#29138]
### Apache Airflow version

2.5.X

### What happened

the entire log section keeps being appended to the existing logs, making this page grow like crazy

https://user-images.githubusercontent.com/14293802/214397834-6f368ab2-23ac-45d0-b699-65e19deeb752.mp4

### What you think should happen instead

only new entries are appended to the tail

### How to reproduce

1. turn on the [example_sensors](https://github.com/apache/airflow/blob/2.5.1/airflow/example_dags/example_sensors.py) DAG
2. click on the `timeout_after_second_date_in_the_future_async` task
3. click on the `logs` button (it's a running task so the spinning dots will appear)
4. scroll down to the bottom and watch the page growing

### Operating System

Debian 10.13

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zachliu** [comment]
might be related to https://github.com/apache/airflow/pull/26169

**Comment by Taragolis** [comment]
It also might potentially fixed by https://github.com/apache/airflow/pull/28818

Could you provide some simple DAG which might reproduce this behaviour?
And do you use Remote Logging?

**Comment by zachliu** [comment]
i guess throttling would just make it refresh less frequent?

the `example_sensors` dag has some long-running tasks (> 1min) that can clearly show this behavior 

no i'm not using remote logging, all logs are read from local

**Comment by Taragolis** [comment]
Just wondering are you use `EcsRunTaskOperator` with enable fetching CloudWatch logs to Airflow tasks?

**Comment by zachliu** [comment]
oops, didn't reconcile my own derived class with that [PR](https://github.com/apache/airflow/pull/26169) :sweat_smile: 

i have a `PatchedS3TaskHandler` to always read from local for speed and use s3 just as a backup
