### ISSUE TITLE
Parameter for disabling scheduling

### ISSUE THREAD

**Issue by rishabh643** [apache/airflow#29149]
### Description

Can we have a parameter in airflow that can disable scheduling for all dags that are present?
I know one can disable dags individually or can turn off the scheduler altogether.
But I am specifically looking for a parameter through which we can disable the scheduling of all dags without bringing down the scheduler.

### Use case/motivation

We are creating a Disaster Recovery setup. In which primary site will be up and running.
While the secondary site should be up with minimum replicas and no one should be able to trigger the dags on the secondary.
In order to do so I want to set up airflow on secondary with this parameter enabled. So that no one even by mistake can run enable the dag from the UI and run it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Is the issue that you don't want the tasks to be scheduled or you don't want them to actually run?
If you won't have any workers up then nothing will be executed (except EmptyOperator)
