### ISSUE TITLE
trigger process missing from Airflow docker docs

### ISSUE THREAD

**Issue by amarlearning** [apache/airflow#29150]
### What do you see as an issue?

The section [`Fetching docker-compose.yaml`](https://github.com/apache/airflow/blob/main/docs/apache-airflow/howto/docker-compose/index.rst#fetching-docker-composeyaml) claims to talk about all the process definitions that the Dockerfile compose contain but missed to talk the `airflow-trigger` process.

### Solving the problem

We need to include the `airflow-trigger` in the process list that the docker-compose file contains.

### Anything else

None

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
feel free to add it.
