### ISSUE TITLE
FTP(S)FileTransmitOperator class should allow to use file-like buffer.

### ISSUE THREAD

**Issue by Draqun** [apache/airflow#29153]
### Description

Hi.

It would be great to have possibility to use file-like buffer as local_filepath parameter. An example:
```python3
class FTPFileTransmitOperator(BaseOperator):
    def __init__(
        self,
        *,
        ftp_conn_id: str = "ftp_default",
        local_filepath: str | list[str] | io.TextIOWrapper | list[io.TextIOWrapper],
        remote_filepath: str | list[str],
        operation: str = FTPOperation.PUT,
        create_intermediate_dirs: bool = False,
        **kwargs,
    ) -> None:
        ...
```
My proposition can be found in the following PR: https://github.com/apache/airflow/pull/29156
Please let me know it requires more coding/fixing. I really need this functionality.

### Use case/motivation

Files to be sent to the FTP server can be read by open/smart_open from e.g. S3 or AzureStorage. The current solution forces such a file to be downloaded, which makes the provider very limited. Here, passing the handle returned by smart_open would solve the problem. It should not be hard, because hook (FTPHook) in method store_file can use file_handlers.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Could you provide any samples how you intend to use this?
Because you can't easily send file-like objects between tasks.

**Comment by eladkal** [comment]
The project doesn't not require summiting Github issue for PRs so if you open a PR you can have all the information there. there is no need to also open issue.

**Comment by potiuk** [comment]
As described in #29156 - this is not going to work - this is not how airflow works, and there are already other solution (building custom transfer operators or using TaskFlow and Hooks).
