### ISSUE TITLE
Support for Redis Time series in Airflow common packages

### ISSUE THREAD

**Issue by m2b** [apache/airflow#29175]
### Description

The current Redis API version is quite old.  I need to implement a DAG for Timeseries data feature.   Please upgrade to version that supports this.  BTW, I was able to manually update my redis worker and it now works. Can this be added to next release please.

### Use case/motivation

Timeseries in Redis is a growing area needing support in Airflow

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> Can this be added to next release please.

Why not? If **someone** found that we could safety migrate to new version of [`redis`](https://pypi.org/project/redis/), [create a PR](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst) and it is reviewed and  merged so potentially all signs that it might include to next release.

The problem how long it takes for **someone** who could work on this issue.

The limitation in Redis Provider Package, but it also could conflict/affect other with different components, e.g. Celery:

https://github.com/apache/airflow/blob/d80b583db07197c8c3d0549a805e83ceaaf10d52/airflow/providers/redis/provider.yaml#L37-L41

**Comment by Owen-CH-Leung** [comment]
@Taragolis @eladkal I made a PR to resolve this issue by upgrading redis to the latest one (i.e. 4.5.5). Can I ask for your review for my PR ?
