### ISSUE TITLE
Trigger DAG w/config raising error from task detail views

### ISSUE THREAD

**Issue by enrique-ayala** [apache/airflow#29197]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version: 2.4.3 (migrated from 2.2.4)

Manual UI option "Trigger DAG w/config" raises an error  _400 Bad Request - Invalid datetime: None_ from views "Task Instance Details", "Rendered Template", "Log" and "XCom" .  Note that DAG is actually triggered , but still error response 400 is raised. 

### What you think should happen instead

No 400 error 

### How to reproduce

1. Go to any DAG graph view  
2. Select a Task > go to "Instance Details"
3. Select "Trigger DAG w/config"
4. Select Trigger
5. See error

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Thank you for opening this issue, I can reproduce the problem with 2.5.1 and master.
Can someone assign it to me?
