### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by lixiaoyong12** [apache/airflow#29232]
### Apache Airflow version

2.5.1

### What happened

使用2.5.0版本运行200个DAG，运行50分钟时间，内存从100M增加到500M；（由于服务设置了内存上限，所以到500M就会重启），而在2.0.1版本在70M左右

![image](https://user-images.githubusercontent.com/34184204/215424653-a02a0643-da5e-47c7-a79f-77cbeb0f8c83.png)

### What you think should happen instead

经过分析，我任务airflow下面的代码会导致内存泄露，

 if hook_is_noop:
                session.bulk_insert_mappings(TI, tasks)
            else:
                session.bulk_save_objects(tasks)

![image](https://user-images.githubusercontent.com/34184204/215422647-ac7994fd-60bc-4649-9b3b-e000f6c977f3.png)

### How to reproduce

下发200个dag，每个dag不要做任何事情，也就是空跑调度

### Operating System

欧拉

### Versions of Apache Airflow Providers

2.5.0

### Deployment

Official Apache Airflow Helm Chart

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
PLease report your issue in English.

**Comment by lixiaoyong12** [comment]
Linear memory growth，The system（20 DAG） runs for 50 minutes and the memory is increased from 100 MB to 500 MB.

![image](https://user-images.githubusercontent.com/34184204/215722888-2bacc85a-0c3d-4206-81e6-22b4de503f76.png)

Comment out the following code. The memory does not increase.
![image](https://user-images.githubusercontent.com/34184204/215722944-da4b8e82-63b4-4c81-8595-a4fa1072bc93.png)
