### ISSUE TITLE
Repair functionality in DatabricksRunNowOperator

### ISSUE THREAD

**Issue by kyle-hamlin** [apache/airflow#29250]
### Description

The Databricks jobs 2.1 API has the ability to repair failed or skipped tasks in a Databricks workflow without having to rerun successful tasks for a given workflow run. It would be nice to be able to leverage this functionality via airflow operators.

### Use case/motivation

The primary motivation is the ability to be more efficient and only have to rerun failed or skipped tasks rather than the entire workflow if only 1 out of 10 tasks fail.

**Repair run API:**
https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsRunsRepairfail

@alexott for visability

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
@Mokubyow Sounds cool! Feel free to submit a PR.

**Comment by josh-fell** [comment]
Closing as completed via #30786. We can reopen if that PR doesn't sufficiently handle the feaure.
