### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by lixiaoyong12** [apache/airflow#29263]
### Apache Airflow version

2.5.1

### What happened

Linear memory growth，The system（200 DAG） runs for 50 minutes and the memory is increased from 100 MB to 500 MB.

![image](https://user-images.githubusercontent.com/34184204/215723671-774b1ed3-f92a-4d73-a296-66934e98a5e4.png)

Comment out the following code. The memory does not increase.

![image](https://user-images.githubusercontent.com/34184204/215723776-97db7de4-1bd5-480d-900b-21cb291a209c.png)

### How to reproduce

Run 200 2-minute dag files and run the ps command to check the memory usage.

### Operating System

euleros

### Versions of Apache Airflow Providers

2.5.0

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Let me convert it to discussion. There are far too little details in this request to be able to act on it.

This is absolutely normal that (for example cache) memory grows in linux when the system is running and which process leaks memory. This could be - for example your database allocating more memory as it is caching things in the DB. 

You have not explained what kind of memory is growing nor which process leaks . 

This is really not actionable report until more details is given and showing which process leaks "real" memory.  You can see similar issues here: https://github.com/apache/airflow/discussions/28597
