### ISSUE TITLE
Google Bigquery connection type is not working

### ISSUE THREAD

**Issue by bonamim** [apache/airflow#29286]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Using this type of connection it is not possible to pass all the necessary parameters such as Keyfile JSON, Project Id, Scopes.

- Google Bigquery
![image](https://user-images.githubusercontent.com/36086878/216052103-fb731446-a63c-45f5-91c2-b6545d9b8000.png)

### What you think should happen instead

The fields should be the same as those of the **Google Cloud** connection type in order to be able to specify data such as Keyfile JSON, Project Id, Scopes.

- Google Cloud
![image](https://user-images.githubusercontent.com/36086878/216052254-80e0d9fe-3762-4a5e-8bf0-7e7a494b0ee8.png)

### How to reproduce

1. Admin -> Connections
2. Add a new record
3. Connection Type -> Google Bigquery

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==3.0.0
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-cncf-kubernetes==3.0.2
apache-airflow-providers-docker==2.4.1
apache-airflow-providers-elasticsearch==2.2.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.4.0
apache-airflow-providers-grpc==2.0.1
apache-airflow-providers-hashicorp==2.1.1
apache-airflow-providers-http==2.0.3
apache-airflow-providers-imap==2.2.0
apache-airflow-providers-microsoft-azure==3.6.0
apache-airflow-providers-mongo==3.0.0
apache-airflow-providers-mysql==2.2.0
apache-airflow-providers-odbc==2.0.1
apache-airflow-providers-postgres==3.0.0
apache-airflow-providers-redis==2.0.1
apache-airflow-providers-sendgrid==2.0.1
apache-airflow-providers-sftp==2.4.1
apache-airflow-providers-slack==4.2.0
apache-airflow-providers-sqlite==2.1.0
apache-airflow-providers-ssh==2.4.0

### Deployment

Docker-Compose

### Anything else

I'm trying to use the operator below:

`from airflow.providers.google.suite.transfers.sql_to_sheets import SQLToGoogleSheetsOperator`

When I use the **Google Bigquery** connection type and put in the `Password` field the content that should be placed in the `Keyfile JSON` field, an error message is returned:

![image](https://user-images.githubusercontent.com/36086878/216055849-b60a6ac9-5ef7-4680-862f-4ec15e634d5b.png)

When I use the **Google Cloud** connection type, an error message is returned:

![image](https://user-images.githubusercontent.com/36086878/216056206-ed0044c6-5784-4f7f-b629-36b6b96f5c76.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
currently, you can pass this in the extra field `{"key_path": "key.json"}` but yes look like we need to fix the UI behaviour

**Comment by eladkal** [comment]
Closing as task is listed in https://github.com/apache/airflow/issues/28790
