### ISSUE TITLE
AIP-44 Migrate TaskInstance.refresh_from_db to Internal API

### ISSUE THREAD

**Issue by mhenc** [apache/airflow#29311]
https://github.com/apache/airflow/blob/main/airflow/models/taskinstance.py#L770

Note it is used in multiple places. The places needed by AIP-44
https://github.com/apache/airflow/blob/main/airflow/jobs/local_task_job.py#L234
...

**Comment by dstandish** [comment]
Hi @mhenc I see you've marked this done. Is it done? Is work on it in progress?  Are there any particular challenges in this one?

**Comment by mhenc** [comment]
Yes, it is done. 
If you take a look at 
https://github.com/apache/airflow/blob/main/airflow/models/taskinstance.py#L464C28-L464C40 
then  you can see that method
`TaskInstance.get_task_instance`
is already migrated
https://github.com/apache/airflow/blob/main/airflow/api_internal/endpoints/rpc_api_endpoint.py#L82
