### ISSUE TITLE
Ensure only one setup/teardown is allowed per scope

### ISSUE THREAD

**Issue by norm** [apache/airflow#29324]
Two parts to this:
- [x] nested
- [ ] peer

**Comment by dstandish** [comment]
this one appears covered by test `test_setup_block_nested` @jedcunningham

**Comment by jedcunningham** [comment]
I blocked nested setups, but I didn't block 2 peer setups yet :)

**Comment by dstandish** [comment]
ok nice, i updated description

**Comment by jedcunningham** [comment]
You can now have more than 1 per scope, nothing remaining to do here.
