### ISSUE TITLE
DAG dependencies graph not updating when deleting a DAG

### ISSUE THREAD

**Issue by alejandrofm** [apache/airflow#29323]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

ON Airflow 2.4.2 Dag dependencies graph show deleted DAGs that use to have dependencies to currently existing DAGs

### What you think should happen instead

Deleted DAGs should not appear on DAG Dependencies

### How to reproduce

Create a DAG with dependencies on other DAG, like a wait sensor.
Remove new DAG

### Operating System

apache/airflow:2.4.2-python3.10

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We generate that graph based on `SerializedDagModel.get_dag_dependencies()`. I'm not too sure as to when that is updated after deleting a dag. Maybe someone with more knowledge on that side of things could chime in?

**Comment by michaelmicheal** [comment]
I think this related to not excluding disabled DAGs. Can you assign this to me? I'd like to tackle it this week

**Comment by michaelmicheal** [comment]
I actually wasn't able to reproduce this behaviour. I didn't realize, but we started deleting serialized dags when removing stale DAGs here: https://github.com/apache/airflow/commit/f878854fff0f5bc577eab70c61e69e353aed43c3#diff-bde85feb359b12bdd358aed4106ef4fccbd8fa9915e16b9abb7502912a1c1ab3.

@alejandrofm How are you deleting the DAG? Removing it from the DAG bucket?

**Comment by michaelmicheal** [comment]
Actually I was able to reproduce. I think that there is a bug in the deletion of serialized DAGs. Should be able to figure it out and come up with a fix.

**Comment by alejandrofm** [comment]
Great, just to add the info:
We make the DAG changes on Gitlab and then retrieve the DAG folder via git-sync.
