### ISSUE TITLE
Update the DAG graph to show setup/teardown

### ISSUE THREAD

**Issue by norm** [apache/airflow#29328]

**Comment by dstandish** [comment]
probably want to also indicate that it's special with diff color or icon overlay

**Comment by bbovenzi** [comment]
@jedcunningham and I discussed this earlier this week

The dependencies between setup/teardown tasks to everything else can be noisy but are also important. So we will show those edges in the graph as a fainter dashed line that users can toggle on/off.

If we need more, we can add some text or icon on our more information-rich graph nodes

**Comment by jedcunningham** [comment]
Close with #32578.
