### ISSUE TITLE
Ensure setup/teardown dependencies raise an error

### ISSUE THREAD

**Issue by norm** [apache/airflow#29336]

**Comment by dstandish** [comment]
i think you may mean, if you define an upstream / downstream relationship between normal and setup, raise?

**Comment by norm** [comment]
This was taken from the AIP:

> It is an error for setup and teardown tasks to have dependencies (This is to allow us to work out the semantics of what multiple setup/teardown should be at a future point, and to reserve deps for this if we want it)
