### ISSUE TITLE
Check Absence of files or objects via GCSObjectExistenceSensor

### ISSUE THREAD

**Issue by vksunilk** [apache/airflow#29344]
### Description

Currently GCSObjectExistenceSensor fails if the object is not present. We can add a parameter `check_for_absence`, which when true, should check for absence and should fail if the file is present

### Use case/motivation

To fail if a file is present, currently we are writing a Python Operator. If this is included the same operator can be used

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Closing due to issues raised in code review https://github.com/apache/airflow/pull/29346#issuecomment-1437448536
