### ISSUE TITLE
Cannot use TypedDict object when defining params

### ISSUE THREAD

**Issue by jcobb-healx** [apache/airflow#29358]
### Apache Airflow version

2.5.1

### What happened

Context: I am attempting to use [TypedDict](https://docs.python.org/3/library/typing.html#typing.TypedDict) objects to maintain the keys used in DAG params in a single place, and check for key names across multiple DAGs that use the params.
This raises an error with `mypy` as `params` expects an `Optional[Dict]`. Due to the invariance of `Dict`, this does not accept `TypedDict` objects.

What happened: I passed a `TypedDict` to the `params` arg of `DAG` and got a TypeError.

### What you think should happen instead

`TypedDict` objects should be accepted by `DAG`, which should accept `Optional[Mapping[str, Any]]`. 

Unless I'm mistaken, `params` are converted to a `ParamsDict` class and therefore the appropriate type hint is a generic `Mapping` type.

### How to reproduce

Steps to reproduce

```Python
from typing import TypedDict

from airflow import DAG
from airflow.models import Param

class ParamsTypedDict(TypedDict):
    str_param: Param

params: ParamsTypedDict = {
    "str_param": Param("", type="str")
}

with DAG(
    dag_id="mypy-error-dag",
    # The line below raises a mypy error
    # Argument "params" to "DAG" has incompatible type "ParamsTypedDict"; expected "Optional[Dict[Any, Any]]"  [arg-type]
    params=params,  
) as dag:
    pass
```

### Operating System

Amazon Linux

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jcobb-healx** [comment]
Relevant mypy discussion on passing `TypedDict` as args annotated with `Dict`: https://github.com/python/mypy/issues/4976

**Comment by potiuk** [comment]
Feel free to work on it.

**Comment by pierrejeambrun** [comment]
@jcobb-healx Are you still working on this ?

**Comment by jcobb-healx** [comment]
@pierrejeambrun Sorry, I hadn't gotten around to looking at this. Spent a bit of time on this today, and it looks like converting the type hint to `Mapping` isn't right, as the `params` are merged with the default params in an [`update` call](https://github.com/apache/airflow/blob/a5adb87ab4ee537eb37ef31aba755b40f6f29a1e/airflow/models/dag.py#L430), which isn't consistent with `TypedDict` behaviour.
Given the earlier `mypy` discussion, it probably makes sense to use `MutableMapping` to allow generic inputs, and let users perform casts, i.e. _not_ accept `TypedDict` objects.
