### ISSUE TITLE
Add pagination to get_log in the rest API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#29405]
### Description

Right now, the `get_log` endpoint at `/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/logs/{task_try_number}` does not have any pagination and therefore we can be forced to load extremely large text blocks, which makes everything slow. (see the workaround fix we needed to do in the UI: https://github.com/apache/airflow/pull/29390)

In `task_log_reader`, we do have `log_pos` and `offset` (see [here](https://github.com/apache/airflow/blob/main/airflow/utils/log/log_reader.py#L80-L83)). It would be great to expose those parameters in the REST API in order to break apart task instance logs into more manageable pieces.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
shall i try this one?

**Comment by Bowrna** [comment]
i will start working on this today.

**Comment by Bowrna** [comment]
@ephraimbuddy just now your comment made sense to me. Please validate this comment and correct me if I am wrong @bbovenzi you can make API calls like the one below. In case this didn't work out, share it here. 
```
        from itsdangerous.exc import BadSignature
        from itsdangerous.url_safe import URLSafeSerializer

        request_url = f"api/v1/dags/{DAG_ID}/dagRuns/{RUN_ID}/taskInstances/{TASK_ID}/logs/1"
        key = self.app.config["SECRET_KEY"]
        serializer = URLSafeSerializer(key)
        token = serializer.dumps({"log_pos": 10000})

        response = self.client.get(
            request_url,
            query_string={"token": token},
            headers={"Accept": "text/plain"},
            environ_overrides={"REMOTE_USER": "test"},
        )
       continuation_token = response.json["continuation_token"]
       try:
            metadata = URLSafeSerializer(key).loads(continuation_token)
            log_pos = metadata["log_pos"] # Absolute char position to which log is retrieved
            end_of_log = metadata["end_of_log"] # Boolean, True if end of log is reached or False
        except BadSignature:
            raise BadRequest("Bad Signature. Please use only the tokens provided by the API.")

```
Here `log_pos` is the char position to which the log was retrieved in previous calls.

Say example you make an API call and the log file is too large, you can render only part of the log chars in the page. To render the next one, you can send the API call like above with log_pos as say 10000, then the log starting from char 10000 to last (not the end as the logs may be tailing behind in running state) will be returned. that way you can do pagination with metadata as part of the token.

@ephraimbuddy please let me know if what I mentioned above is right. Also, what's your opinion on the documentation of this part? If yes, can you suggest where this documentation should belong too?

**Comment by ephraimbuddy** [comment]
@Bowrna , you are right. Sorry for not communicating it well.

We can document it on the openapi spec description of the log endpoint https://github.com/apache/airflow/blob/dff425bc3d92697bb447010aa9f3b56519a59f1e/airflow/api_connexion/openapi/v1.yaml#L1671

**Comment by Bowrna** [comment]
@ephraimbuddy could we include documentation by quoting code examples like the above comment in v1.yaml ?
or is it ok to explain in words alone without quoting code to explain the endpoint ?

**Comment by Bowrna** [comment]
@ephraimbuddy Like how full_content (boolean) that is passed as param to api is loaded into metadata, could we consider a similar one for log_pos too? like rather than loading into token and retrieving it, how about following the same way as the below code for `log_pos` too. just an opinion. please let me know if it doesn't work out. because `full_content` key could be passed into token rather than passing as param. but still, we support the param for `full_content` option. keeping that in mind this question raised for me.

(https://github.com/apache/airflow/blob/9de71187ed53dd4e9f91d2b148c8db6bf69221a8/airflow/api_connexion/endpoints/log_endpoint.py#L68-L77)

**Comment by Bowrna** [comment]
@ephraimbuddy gentle reminder, do you have any update for me about this one?

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy gentle reminder, do you have any update for me about this one?

The full_content is not part of the log's metadata, it's just a boolean to check if we should download logs while log_pos is part of the metadata. I don't think it's a good idea to have it as an option in the API

**Comment by Bowrna** [comment]
@ephraimbuddy when I looked into the code in log_endpoint.py, the full_content is a boolean that decides how to populate the metadata. with that value set in metadata only, the download_logs is set/unset in the metadata. can you tell me why a similar solution won't work log_pos?
https://github.com/apache/airflow/blob/9de71187ed53dd4e9f91d2b148c8db6bf69221a8/airflow/api_connexion/endpoints/log_endpoint.py#L60-L77

**Comment by bbovenzi** [comment]
I'd like to add, I think it is important to add the ability to start reading from the most recent logs and go backwards in time. But maybe that's a slightly separate issue.

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy when I looked into the code in log_endpoint.py, the full_content is a boolean that decides how to populate the metadata. with that value set in metadata only, the download_logs is set/unset in the metadata. can you tell me why a similar solution won't work log_pos?

I don't think we need the log_pos, it's not a boolean like the download_logs. It's something that should come from the logger.
At the first request, we can just get the log with its position. It seems to me that giving it position would mean truncating some logs

**Comment by ephraimbuddy** [comment]
> I'd like to add, I think it is important to add the ability to start reading from the most recent logs and go backwards in time. But maybe that's a slightly separate issue.

Makes sense to me. @Bowrna maybe you can look into this if we have a way to do it or you can work on adding it

**Comment by Bowrna** [comment]
> > @ephraimbuddy when I looked into the code in log_endpoint.py, the full_content is a boolean that decides how to populate the metadata. with that value set in metadata only, the download_logs is set/unset in the metadata. can you tell me why a similar solution won't work log_pos?
> 
> I don't think we need the log_pos, it's not a boolean like the download_logs. It's something that should come from the logger. At the first request, we can just get the log with its position. It seems to me that giving it position would mean truncating some logs

Ok that makes sense to me @ephraimbuddy

**Comment by Bowrna** [comment]
i will add the description part by this weekend and close this issue by this weekend.
