### ISSUE TITLE
Hide non-used docs attributes from Task Instance Detail

### ISSUE THREAD

**Issue by lorenzomagni** [apache/airflow#29515]
### Description

Inside a BashOperator, I added a markdown snippet of documentation for the "Task Instance Details" of my Airflow nodes.
Now I can see my markdown, defined by the attribute "doc_md", but also

Attribute: bash_command
Attribute: doc
Attribute: doc_json
Attribute: doc_rst
Attribute: doc_yaml

I think it would look better if only the chosen type of docs would be shown in the Task Instance detail, instead of leaving the names of other attributes without anything added to them.

![screenshot](https://user-images.githubusercontent.com/23013638/218585618-f75d180c-6319-4cc5-a569-835af82b3e52.png)

### Use case/motivation

I would like to see only the type of doc attribute that I chose to add to my task instance detail and hide all the others docs type.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
You're right it's a little cluttered with all of those docs attributes.
