### ISSUE TITLE
'docker compose' instead of 'docker-compose'

### ISSUE THREAD

**Issue by Jianxuan-Li** [apache/airflow#29542]
### What do you see as an issue?

Hi all,

link to the document: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
<img width="687" alt="Screenshot 2023-02-14 at 14 00 00" src="https://user-images.githubusercontent.com/49817817/218832135-80cb7e87-1654-45d1-977e-54ce8b2c7a92.png">

In the script it still uses 'docker-compose' as compose command, this command come from docker-compose V1, which will be removed.
<img width="502" alt="Screenshot 2023-02-14 at 14 02 06" src="https://user-images.githubusercontent.com/49817817/218832607-fbc2347a-0ff5-47aa-b931-e0113ad5717e.png">
<img width="750" alt="Screenshot 2023-02-14 at 14 02 57" src="https://user-images.githubusercontent.com/49817817/218832619-3f1a5ba6-29a3-4cbf-bf1e-a1b4088b3bc5.png">

### Solving the problem

I think we should check which command does a user is using.

```bash
if [ -x "$(command -v docker-compose)" ]; then
    dc=docker-compose
else
    dc="docker compose"
fi
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free.
