### ISSUE TITLE
Grid view for a single DAG run

### ISSUE THREAD

**Issue by jayesh-shaw-glean** [apache/airflow#29551]
### Description

A filter on run_id in the grid view

### Use case/motivation

Having used Airflow for sometime, I and my teammates get the most value out of the grid view. I might be missing something, but it seems that there is no way to view a single dag run in the grid view, if it isn't the latest run (latest success/running/failed runs also work). I would like to know if there is some way to get to view a single dag run or if there isn't then it would be a great feature to add. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Could you a bit clarify, what do you mean "it seems that there is no way to view a single dag run in the grid view"

Is that what are you looking for? Or something else?
https://user-images.githubusercontent.com/3998685/219343273-faeb27e6-e648-404f-971e-b64ace6622ed.mp4
