### ISSUE TITLE
Support execution_date parameter in dags list-runs CLI

### ISSUE THREAD

**Issue by ellisms** [apache/airflow#29588]
### Description

Enable parameter in dags list-runs command to support supplying an execution_date, or range of execution_dates.

### Use case/motivation

Listing runs based on execution date (logical) date rather than start/end dates.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
> @shahar1 would you like to take this one?

Yes, I would!

**Comment by shahar1** [comment]
I started working on this issue, and it seems that `start_date`/`end_date` terms already refer to `execution_date` (logical date), as of the latest Airflow version. See the following snippet from `airflow.cli.commands.dag_command.py`:

```python
    dag_runs = DagRun.find(
        dag_id=args.dag_id,
        state=state,
        no_backfills=args.no_backfill,
        execution_start_date=args.start_date, # <-
        execution_end_date=args.end_date, # <-
        session=session,
    )
```

In the `find()` method of `airflow.models.dagrun.py`: - you could see the following logic:
```python
        if execution_start_date and execution_end_date:
            qry = qry.filter(cls.execution_date.between(execution_start_date, execution_end_date))
        elif execution_start_date:
            qry = qry.filter(cls.execution_date >= execution_start_date)
        elif execution_end_date:
            qry = qry.filter(cls.execution_date <= execution_end_date)
```

Thus - the existing functionality resolves the issue.

@ellisms Which Airflow version do you use? Does the above provide what you need, or do you need something else?

**Comment by potiuk** [comment]
Closing it provisionally as fixed then. In case @ellisms has some more to add we can always reopen it.
