### ISSUE TITLE
Example return 404 for some JS, leaving the UI unusable

### ISSUE THREAD

**Issue by bmentges** [apache/airflow#296]
Hi,

There are 3 404s right now in airflow==1.4.0:
- form-1.0.0.js
- jquery-2.1.1.js 
- moment-2.8.4.min.js

Basically most things in vendor/

2015-08-24 09:55:22,136 - tornado.access - WARNING - 404 GET /admin/static/vendor/jquery-2.1.1.min.js (127.0.0.1) 12.58ms
2015-08-24 09:55:22,145 - tornado.access - WARNING - 404 GET /admin/static/vendor/moment-2.8.4.min.js (127.0.0.1) 3.39ms

Best regards,
Bruno

**Comment by eoin-o** [comment]
I'm also seeing this issue, I've solved it temporarily with symbolic links. Also want to add the below to the list:

/admin/static/admin/js/form-1.0.0.js

Also even once I've worked-around the 404's, the main DAG page is still not rendering in the UI.

Thanks,
E

**Comment by mistercrunch** [comment]
Ok, I'm going to fix this asap and push 1.4.1

**Comment by mistercrunch** [comment]
Looks like an issue with flask-admin `1.3.0` that was pushed on `2015-08-23`. I'm going to pin my dependency to `flask-admin` on `1.2.0` until this gets resolved.

In the meantime, easiest fix for people experiencing this is:
`pip install flask_admin==1.2.0`

**Comment by bmentges** [comment]
Fixed in 1.4.1. Thanks mistercrunch!

**Comment by eoin-o** [comment]
Thank you!
