### ISSUE TITLE
Importing CreateCustomContainerTrainingJobOperator takes too much time

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#29613]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When importing CreateCustomContainerTrainingJobOperator it seems to take 3-4 seconds just to import the module.
I ran `time python` for two DAG files - one with the import line and one without it. The import line is simple as follows:
``from airflow.providers.google.cloud.operators.vertex_ai.custom_job import CreateCustomContainerTrainingJobOperator``

The results of the comparison:

```
airflow@airflow-scheduler-##########-#####:~/gcs/dags$ time python dag_w_import.py
real    0m4.884s
user    0m4.668s
sys     0m1.425s
airflow@airflow-scheduler-##########-#####:~/gcs/dags$ time python same_dag_wo_import.py
real    0m1.484s
user    0m1.310s
sys     0m0.163s

```

### What you think should happen instead

The import of the module should be instant

### How to reproduce

Described above

### Operating System

Ubuntu 18.04.6 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.6.0

### Deployment

Google Cloud Composer

### Deployment details

composer-2.1.6-airflow-2.4.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Check it locally, most of the time spend during this import:

`from google.cloud.aiplatform.models import Model`

![image](https://user-images.githubusercontent.com/3998685/219967078-195efa4c-e9d3-4ba9-a601-a032dea4accc.png)
