### ISSUE TITLE
Fix adding annotations for dag persistence PVC

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#29621]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.0

### Kubernetes Version

v1.25.4

### Helm Chart configuration

The dags persistence section doesn't have a default value for annotations and the usage looks like: 
```
  annotations:
    {{- if .Values.dags.persistence.annotations}}
    {{- toYaml .Values.dags.persistence.annotations | nindent 4 }}
    {{- end }}
```

### What happened

As per the review comments here: https://github.com/apache/airflow/pull/29270#pullrequestreview-1304890651, due to this design, the upgrades might suffer. Fix them to be helm upgrade friendly

### What you think should happen instead

The design should be written in an helm upgrade friendly way, refer to this suggestion https://github.com/apache/airflow/pull/29270#pullrequestreview-1304890651

### How to reproduce

-

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to fix them @amoghrajesh . Assigned you

**Comment by hussein-awala** [comment]
@potiuk we can close it since #29622 is megred.

**Comment by amoghrajesh** [comment]
@potiuk we can close this issue. The PR is merged

**Comment by potiuk** [comment]
For the future @amoghrajesh -> please remember to add description and ("Fixes: #PR) outside  of the comment section so that the issues get closed automatically when PR is merged :)
