### ISSUE TITLE
EcsRegisterTaskDefinitionOperator params are incorrectly invalidated

### ISSUE THREAD

**Issue by janrito** [apache/airflow#29637]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

https://raw.githubusercontent.com/apache/airflow/constraints-2.4.3/constraints-3.10.txt

### Apache Airflow version

2.4.3

### Operating System

https://github.com/aws/aws-mwaa-local-runner / on macos 12.6

### Deployment

Docker-Compose

### Deployment details

[local ](https://github.com/aws/aws-mwaa-local-runner)

### What happened

ECS task definition cpu and memory params are incorrectly invalidated

### What you think should happen instead

parameters are correct, it should register a task. I can run the same bit of code using boto3.client.ecs.register_task_definition`

### How to reproduce

Try and define a task using:

```python 
EcsRegisterTaskDefinitionOperator(
        task_id="register_task",
        family=TASK_FAMILY_NAME,
        container_definitions=[
            {
                "name": CONTAINER_NAME,
                "image": "ubuntu",
                "workingDirectory": "/usr/bin",
                "entryPoint": ["sh", "-c"],
                "command": ["ls"],
            }
        ],
        register_task_kwargs={
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "networkMode": "awsvpc",
        },
    )
```

```logs
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter cpu, value: 256, type: <class 'int'>, valid types: <class 'str'>
Invalid type for parameter memory, value: 512, type: <class 'int'>, valid types: <class 'str'>
```

Could this error have something to do with JSON serialising/deserialising where the parameters are autodetected as `int`s, rather than deserialised into strings

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Not a bug Airflow provider, the validation happen inside [`botocore`](https://github.com/boto/botocore) / [`boto3`](https://github.com/boto/boto3), see available options and types in [ECS.Client.register_task_definition](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.register_task_definition)

**Comment by Taragolis** [comment]
Nevermind, I have a look on wrong parameters initially.
Did you use specific values such as `render_template_as_native_obj=True` in DAG?

**Comment by janrito** [comment]
Ah! yes. I did. Why is that clashing?
