### ISSUE TITLE
Implement native OpenLineage integration for chosen other Provider

### ISSUE THREAD

**Issue by mobuchowski** [apache/airflow#29675]
### Body

In a first phase, we want to choose one specific provider, implement OpenLineage integration with it and make sure it plays well with prepared framework. It seems to me that Snowflake is a nice candidate - it matches well with a lot of things we want to provide in the first phase of OL-Airflow provider. 

This should also include unit tests that will confirm implementation works. 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by JDarDagran** [comment]
@thcidale0808 I just saw your comment. Snowflake already got OL integration but you're very welcome to contribute!

**Comment by mobuchowski** [comment]
This is done.
