### ISSUE TITLE
Fix Quarantined `test_cli_internal_api_background`

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#29679]
### Body

Recently, [this test](https://github.com/apache/airflow/blob/9de301da2a44385f57be5407e80e16ee376f3d39/tests/cli/commands/test_internal_api_command.py#L134-L137) began to failed with timeout error and it has affected all tests in single CI run. As temporary solution this test was marked as `quarantined`.

We should figure out why it happen and try to resolve it.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @mhenc
