### ISSUE TITLE
Improve code in `KubernetesPodOperator._render_nested_template_fields`

### ISSUE THREAD

**Issue by jose-lpa** [apache/airflow#29759]
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==5.2.1

### Apache Airflow version

2.5.1

### Operating System

Arch Linux

### Deployment

Other

### What happened

Not really showing a failure in operation, but the code in the [`KubernetesPodOperator._render_nested_template_fields`](https://github.com/apache/airflow/blob/d26dc223915c50ff58252a709bb7b33f5417dfce/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L373-L403) function could be improved.

The current code is formed by 6 conditionals checking the type of the `content` variable. Even when the 1st of the succeed, the other 5 conditionals are still checked, which is inefficient because the function could end right there, saving time and resources.

### What you think should happen instead

The conditionals flow could be fixed with a simple map, using a dictionary to immediately get the value or fallback to the default one.

### How to reproduce

There is no bug _per se_ to reproduce. It's just making the code cleaner and more efficient, avoiding to keep computing conditionals even when the condition has been resolved.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
FYI. There is no need to create issue for such things. Just a PR is more than enough.
