### ISSUE TITLE
Can I click the node in the DAG diagram?

### ISSUE THREAD

**Issue by liujie316316** [apache/airflow#29830]
### What do you see as an issue?

I want to put the DAG diagram generated by airflow into QT, and the nodes in the DAG diagram can be clicked. What should I do? I can't click the DAG graph node in the airwindow ui!!!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You opened a discussion about that and you got some hints there. Please in the future avoid opening issues for things that are questions
