### ISSUE TITLE
Migrate DAG Code page to Grid Details

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#29858]
- [ ] Use REST API to render DAG Code in the grid view as a tab when a user has no runs/tasks selected
- [ ]  Redirect all urls to new code 
- [ ] delete the old code view

**Comment by tquazi** [comment]
Hello @bbovenzi, Can I take a stab at this one?

**Comment by potiuk** [comment]
Feel free.

**Comment by tquazi** [comment]
@bbovenzi @potiuk Can you please help me point to any additional details around this request to get me started? Thanks for your time!

**Comment by potiuk** [comment]
What do you miss? Generally we expect anyone who takes on the tasks to be pretty self-sufficient using our code and documentation, contributing guides (see CONTRIBUTE.rst) and only reach out when they have specific questions about problems they had by following them.

Do you have some problems/questions?

**Comment by tquazi** [comment]
I understand that this request is part of bigger UI initiative which @bbovenzi is also working on. 
Wanted to make sure if he has any more details to add to this. and also how this will fit in along with the other PRs for this UI.

I will read through the existing PRs that are being worked on as part of this UI upgrade and will get back if I have any further questions.

Thanks!

**Comment by bbovenzi** [comment]
We have a GET `dagSources/{file_token}` endpoint in the REST API. (file token comes from the get dag endpoint)

My thought was adding it as a tab in the grid view kind of like how details, graph and logs works right now. What do you think?

**Comment by tquazi** [comment]
@bbovenzi Thanks for the rest api reference.  
I will work on this and have something for your review in the next few days.
