### ISSUE TITLE
Improve js build file sizes

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#29854]
The build files for the new react pages are quite large and can be slow to load. We should find ways to fix this to improve page loading times.

<img width="1127" alt="Screenshot 2023-03-01 at 7 25 19 PM" src="https://user-images.githubusercontent.com/4600967/222298187-7a03165c-0bf3-4ea9-b92a-49f9e7be05e8.png">

**Comment by vincbeck** [comment]
Just for reference and having used it in the past, [Webpack Bundle Analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) can be really useful for this kind of issue
