### ISSUE TITLE
ZohoCRM Hook

### ISSUE THREAD

**Issue by foodporty** [apache/airflow#29868]
### Description

 **Zoho CRM hook** 
Allow developers to interact with the Zoho database 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
see `Can I contribute my own provider to Apache Airflow?`
https://airflow.apache.org/docs/apache-airflow-providers/#how-to-create-your-own-provider

If you are not willing to start the process, own it and maintain it... it's unlikely that such provider will be accepted.
I suggest to raise this with Zoho and ask them to develop 3rd party provider
