### ISSUE TITLE
Import error for dagfactory module

### ISSUE THREAD

**Issue by Narsimha1997** [apache/airflow#29890]
### Apache Airflow version

2.5.1

### What happened

Iam running airflow version 2.3.0 through docker and python version is 3.10.6, i installed dag-factory python module using pip and but getting error in the airflow web interface showing that 'No module named dagfactory'. I also entered into container and again installed the module using pip but same same issue, any suggestions please let me know.

### How to reproduce

you can mail to me.

### Operating System

Ubutnu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
dag-factory is not part of Airflow. it's 3rd party project.
Please report your issue to them https://github.com/ajbosco/dag-factory

**Comment by potiuk** [comment]
Also (regardless of whether you use dag-factory or another module) - you are not supposed to install module into running containers. This is not how containers work. You need to build your own image extend the images if you want to add extra dependencies. https://airflow.apache.org/docs/docker-stack/build.html

Using containers has a learning curve and I recommend to watch some tutorials if you want to start using them as you need to treat them differently thatn local environments, so if you are not ready for tha @Narsimha1997 t, I'd say you should got the regular local virtualenv installation.
