### ISSUE TITLE
Tree view is slow for recombining DAGs

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#299]
The Tree View has a very cool approach to representing graphs that aren't actually trees by letting users collapse and uncollapse leaves that appear in multiple places. Unfortunately, this approach comes with an extreme computational burden since before it can display the tree, it must build a data object containing _every possible path from the root to every single leaf_. When DAGs recombine (meaning if it the edges weren't directed, it would be a cyclic graph), the number of possible paths explodes. For example, my machine totally freezes when trying to load Tree View for this relatively simple graph:

``` python
import airflow
from airflow.operators import DummyOperator
import datetime

dag = airflow.DAG(
    dag_id='break_the_tree',
    default_args=dict(owner='airflow' , start_date=datetime.datetime.now()))

group, prev_group = None, None

for i in range(5):
    ops = [DummyOperator(task_id='dummy{}{}'.format(i, j), dag=dag) for j in range(10)]
    if prev_group:
        prev_group.set_downstream(ops)
    group = DummyOperator(task_id='group{}'.format(i), dag=dag)
    group.set_upstream(ops)
    prev_group = group
```

![screen shot 2015-08-24 at 6 33 37 pm](https://cloud.githubusercontent.com/assets/153965/9454271/ad310714-4a8e-11e5-92b9-aff6ebc62539.png)

However, if we are willing to abandon the collapse/uncollapse functionality, then we could implement a much more efficient traversal algorithm. I did, and now I can generate this Tree View for the above graph almost instantly:
![screen shot 2015-08-25 at 7 50 53 am](https://cloud.githubusercontent.com/assets/153965/9465845/26e90402-4afe-11e5-8dd0-3b14080c936d.png)

I really like the collapse/expand functionality, but I think it's much more important to be able to see the tree than worrying that I'm going to freeze my server by clicking the wrong button. Maybe there's a way to have a checkbox on the Tree View page to turn on the fancy collapse functionality, if the user wants it? I could submit a PR that checks an argument `expand_collapse` and runs the efficient search when it's `False` and the old way if it's `True`, but I don't know how to build the UI piece.

**Comment by mistercrunch** [comment]
What about adding a url parameter `nocollapse=true` to force your alternate view? Maybe compute the size of the tree and fallback on this view if the tree goes over a limit?

**Comment by jlowin** [comment]
Closing, see PR #320
