### ISSUE TITLE
Task-level retries overrides from the DAG-level default args are not respected when using `partial`

### ISSUE THREAD

**Issue by elchao96** [apache/airflow#29903]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When running a DAG that is structured like:
```
@dag{dag_id="my_dag", default_args={"retries":0"}}
def dag():
    op = MyOperator.partial(task_id="my_task", retries=3).expand(...)
```

The following test fails:
```
    def test_retries(self) -> None:
        dag_bag = DagBag(dag_folder=DAG_FOLDER, include_examples=False)
        dag = dag_bag.dags["my_dag"]
        for task in dag.tasks:
            if "my_task" in task.task_id:
                self.assertEqual(3, task.retries) # fails - this is 0
```

When printing out `task.partial_kwargs`, and looking at how the default args and partial args are merged, it seems like the default args are always taking precedence, even though in the `partial` global function, the `retries` do get set later on with the task-level parameter value. This doesn't seem to be respected though.

### How to reproduce

If you run my above unit test for a test DAG, on version 2.4.3, it should show up as a test failure.

### Operating System

OS Ventura

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I can reproduce on master:
```python
import pendulum
from airflow.decorators import dag
from airflow.operators.bash import BashOperator


@dag(
    dag_id="test_default_args_with_partial",
    start_date=pendulum.datetime(2023, 1, 1),
    catchup=False,
    default_args={"retries": 0},
)
def dag():
    op = BashOperator.partial(task_id="my_task", retries=3).expand(bash_command=["exit 1", "ps"])


dag()
```
The retries of the mapped tasks is 0.
