### ISSUE TITLE
Unable to get the value of a Variable that has a `/` in it in the API

### ISSUE THREAD

**Issue by dfdeshom** [apache/airflow#29982]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When using the API, I'm unable to get the value of a Variable with a `/` in it in curl. Instead, I get a `404 - Not Found error`

### What you think should happen instead

I should be able to get the value of the variable I'm looking for

### How to reproduce

Create a variable with a `/` in it, ie `project/version`. 

Try to get the Variable via curl:
```bash
$ curl "https://localhost:8080/api/v1/variables/project/version" --user "user:password"

{
  "detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}

```

### Operating System

Ubuntu 22.04.2 LTS

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
As in all REST requests you ned to URL-encode name of the variable. Use `%2F` instead of "/". This is how URL and REST API works.
