### ISSUE TITLE
Bug : `pip install -r requirements.txt` missing dependency on jquery

### ISSUE THREAD

**Issue by r39132** [apache/airflow#300]
Currently, it seems that `pip install airflow` is more complete than `pip install -r requirements.txt`.

When doing the latter, we noticed the following error when loading airflow's home page vi the airflow webserver : `/admin/static/vendor/jquery-2.1.1.min.js HTTP/1.1" 404 -`

This js file seems to be served from `/usr/local/lib/python2.7/dist-packages/flask_admin/static/vendor/jquery-2.1.1.min.js` and was not installed (as of the `1.4 release` tag) by simply running `pip install -r requirements.txt`

Running `pip install airflow` installed this file. It is likely that most people don't notice this since they follow your quick-start guide, which sets airflow up using `pip install`.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/issues/296

**Comment by mistercrunch** [comment]
Fixed in Pypi 1.4.1, should be good in master branch also
https://github.com/airbnb/airflow/issues/296

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/commit/f4223935c6a4ea0cc5232d70890a6d72f26377be

**Comment by r39132** [comment]
Thanks -- makes sense.
