### ISSUE TITLE
Calendar view gives 504 when running with timetable schedule

### ISSUE THREAD

**Issue by Tristan-Zaleski** [apache/airflow#30004]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Switched a DAG to use custom timetable for complex scheduling logic, and ran the DAG, before going to check the Calendar view of that DAG. Page appears to load for a time before giving a 504 error screen.

### What you think should happen instead

Prior to this, CRON scheduling worked, and view would load and give correct info. I am just expecting to see the year's run's displayed as they would be under normal scheduling. Switching back to CRON scheduling also appears to fix the issue.

### How to reproduce

Host a helm deployment on a RH cluster with airflow version 2.3.2. Copy DAG code to a PVC from git repo. Ensure that a timetable is used when declaring the DAG. ( At this point, Calendar view is still accessible, just empty). Now run the DAG, and attempt to view the Calendar. Will load for several seconds before giving white screen with 504 server error message.

### Operating System

Red Hat Linux v3.7

### Deployment

Other 3rd-party Helm chart

### Deployment details

Airflow Version deployed in container is v2.3.2

### Anything else

Same timetable logic is used in a standalone version of Airflow v2.2, and Calendar view loads without issues. Have not tested on other, newer versions of Airflow up to this point. Logging conventions remain the same, names of directories and log files are created in the same format as CRON scheduling.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I believe this was fixed by https://github.com/apache/airflow/pull/29454 which will come out in 2.5.2

**Comment by eladkal** [comment]
@Tristan-Zaleski please test it with 2.5.2rc1
https://github.com/apache/airflow/issues/30028

**Comment by eladkal** [comment]
Due to no response closing as fixed. We can reopen if there are new findings
