### ISSUE TITLE
DataDog Connection type not available 

### ISSUE THREAD

**Issue by shannonchoang** [apache/airflow#30005]
### Apache Airflow Provider(s)

datadog

### Versions of Apache Airflow Providers

apache-airflow-providers-datadog==3.0.0

### Apache Airflow version

2.2.2

### Operating System

Mac OS

### Deployment

Amazon (AWS) MWAA

### What happened

I installed the provider package for DataDog. After installation I'm not getting any import errors when using the hook/operator in a DAG file, but I'm unable to create a DataDog connection through the Airflow UI. 

I noticed in this file where other providers have a Connections section, Datadog does not.
https://github.com/apache/airflow/blob/main/airflow/providers/datadog/provider.yaml

### What you think should happen instead

See above -- I believe some code is missing to actually allow the creation of a DataDog connection.

### How to reproduce

Install the noted version of the Datadog provider package, through the airflow UI attempt to create a DataDog connection. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
DataDog provider not implemented own connection, my assuming that this hook expected to use Generic connection.
And Hook not implements mandatory class attributes for appear in the UI, see: https://github.com/apache/airflow/issues/28790

**Comment by Taragolis** [comment]
close as DataDog is listed in https://github.com/apache/airflow/issues/28790, but even if this issue is duplicate you still could contribute to improve situation with connections
