### ISSUE TITLE
Add PURGE flag to S3ToSnowflakeOperator

### ISSUE THREAD

**Issue by pabrrs** [apache/airflow#30000]
### Description

Snowflake `COPY` operator supports `PURGE=[TRUE|FALSE]` to delete files in S3 after they're copied into the tables. It would be nice to replicate this behavior in `S3ToSnowflakeOperator` with a flag.

[See snowflake COPY options docs](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#copy-options-copyoptions)

### Use case/motivation

In my use case, the files doesn't need to keep In the bucket after being inserted into tables.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
Nice! @pabrrs All yours!

**Comment by Taragolis** [comment]
Nice! Just one thing `S3ToSnowflakeOperator` is deprecated and changes should be addressed to [`CopyFromExternalStageToSnowflakeOperator`](https://github.com/apache/airflow/blob/0fd4fc7f35f0e12bef2c9615acf9651e9f2cec72/airflow/providers/snowflake/transfers/copy_into_snowflake.py#L30)

**Comment by Taragolis** [comment]
And as I could see [CopyFromExternalStageToSnowflakeOperator](https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/_api/airflow/providers/snowflake/transfers/copy_into_snowflake/index.html#airflow.providers.snowflake.transfers.copy_into_snowflake.CopyFromExternalStageToSnowflakeOperator) supports `copy_options` argument

**Comment by pabrrs** [comment]
@Taragolis thanks for referencing `CopyFromExternalStageToSnowflakeOperator`, this works fine for me. 
Since `S3ToSnowflakeOperator` is deprecated, I believe not worth to implement it. 

Thanks!
