### ISSUE TITLE
Nested Taskgroup and Dynamic task mapping fails on second group

### ISSUE THREAD

**Issue by badrisrinivas9** [apache/airflow#30021]
### Apache Airflow version

2.5.1

### What happened

If we create two nested groups and expand the groups the second group tasks fail. I assume the second expand doesn't know which value of mapped index to take. 
![image](https://user-images.githubusercontent.com/114723574/224307242-f1eda991-7fa0-4afd-83df-0103ed52eb44.png)

It throws error 
[2023-03-10 17:01:02,521] {abstractoperator.py:457} ERROR - Cannot expand <Task(_PythonDecoratedOperator): group2.group3.task6> for run manual__2023-03-10T11:30:56.862283+00:00; missing upstream values: ['x']
[2023-03-10 17:01:02,521] {abstractoperator.py:457} ERROR - Cannot expand <Task(_PythonDecoratedOperator): group2.group3.task6> for run manual__2023-03-10T11:30:56.862283+00:00; missing upstream values: ['x']

### What you think should happen instead

The second group should have got the value from the upstream from the first group(most probably by mapping index)

### How to reproduce
    import pendulum
    
    from airflow.decorators import dag, task, task_group
    from airflow.operators.empty import EmptyOperator
    
    
    @dag(dag_id="test", start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
         schedule=None, catchup=False,
         render_template_as_native_obj=True
         )
    def generic_wrapper():
        task1 = EmptyOperator(task_id="task1")
        task2 = EmptyOperator(task_id="task2")
    
        @task
        def task3():
            return [1, 2, 3]
    
        @task_group(
            group_id="group2"
        )
        def group2(i):
            @task
            def task4(i):
                print(i)
    
            @task
            def task5():
                return [1, 2, 3]
    
            task4(i) >> group3.expand(x=task5())
    
        @task_group(
            group_id="group3"
        )
        def group3(x):
            @task
            def task6(x):
                print(x)
    
            task6(x)
    
        task1 >> task2 >> group2.expand(i=task3())
    
    
    dag = generic_wrapper()
    
    if __name__ == "__main__":
        dag.test()

### Operating System

linux

### Versions of Apache Airflow Providers

airflow 2.5.1

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
This issue duplicates #29339.

As I mentioned in my comment there, tasks and task groups expansion in an expanded task group is not supported yet.

If you want to discuss it more, or propose a new design to support nested expansion, you can join this discussion #29618
