### ISSUE TITLE
Import Error can not remove

### ISSUE THREAD

**Issue by SJshenjian** [apache/airflow#30038]
### Apache Airflow version

2.5.1

### What happened

I run the dag with helm on k8s, first I have no module xxx, when the pod started, i install the module in all of the workers and webserver, but still there is 
DAG Import Errors (12)
I'm tring remove it on table import_error, but after seconds it rehappend, what can i do to remove it, please, thanks

### How to reproduce

import modules without in pip list, and webserver you can see the error

### Operating System

CentOS Linux 7

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
> when the pod started, i install the module in all of the workers and webserver, but still there is

how do you install the module and when? can you provide the dockerfile which you use to build the pods docker image?

> I'm tring remove it on table import_error, but after seconds it rehappend, what can i do to remove it,

did you try to import the module manually after installing it? (by creating a Python  shell session and then typing `import module`)
