### ISSUE TITLE
Search/filter by note in List Dag Run

### ISSUE THREAD

**Issue by mayeulk** [apache/airflow#30042]
### Description

Going to Airflow web UI, Browse>DAG Run displays the list of runs, but there is no way to search or filter based on the text in the "Note" column.

### Use case/motivation

It is possible to do a free text search for the "Run Id" field. The Note field may contain pieces of information that may be relevant to find, or to filter on the basis of these notes.

### Related issues

Sorting by Note in List Dag Run fails: 
https://github.com/apache/airflow/issues/30041

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
@dstandish Can you please take a look on this request since the note filter was disabled in #27849 when we moved the notes to as new separate table?

**Comment by dstandish** [comment]
Hi, I do not have time to take this one on right now I am focusing on AIP-52
