### ISSUE TITLE
Helm Chart: allow setting annotations for resource controllers (CronJob, Deployment)

### ISSUE THREAD

**Issue by bnguyennhon** [apache/airflow#30071]
### Description

The Helm Chart allows setting annotations for the pods created by the `CronJob` [but not the CronJob controller itself](https://github.com/apache/airflow/blob/helm-chart/1.8.0/chart/templates/cleanup/cleanup-cronjob.yaml).

The values file should offer an option to provide custom annotations for the `CronJob` controller, similarly to how the DB migrations job exposes `.Values.migrateDatabaseJob.jobAnnotations` 

In the same fashion, other `Deployment` templates expose custom annotations, but [statsd deployment doesn't](https://github.com/apache/airflow/blob/helm-chart/1.8.0/chart/templates/statsd/statsd-deployment.yaml).

### Use case/motivation

Other tools e.g. ArgoCD may require the use of annotations, for example:
* [ArgoCD Sync Options](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options)
* [ArgoCD Sync Phases and Waves](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/)

Example use case:
_Set the cleanup CronJob to be synced after the webserver and scheduler deployments have been synced with ArgoCD_

### Related issues

https://github.com/apache/airflow/issues/25446 originally mentioned the issue regarding the StatsD deployment, but the accepted fix was https://github.com/apache/airflow/pull/25732 which allows setting annotations for the pod template, not the `Deployment` itself

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
@bnguyennhon Assigned it to you, feel free to open a PR.
