### ISSUE TITLE
Connection password values appearing unmasked in the "Task Instance Details" -> "Environment" field

### ISSUE THREAD

**Issue by chriscmorgan** [apache/airflow#30089]
### Apache Airflow version

Airflow  2.5.1

### What happened

Connection password values appearing in the "Task Instance Details" -> "Task Attributes" -> environment field.

We are setting environment variables for the docker_operator with values from the password field in a connection. 

The values from the password field are masked in the "Rendered Template" section and in the logs but it's showing the values in the "environment" field under Task Instance Details.

### What you think should happen instead

These password values should be masked like they are in the "Rendered Template" and logs.

### How to reproduce

Via this DAG, can run off any image.

Create a connection called "DATABASE_CONFIG" with a password in the password field.

Run this DAg and then check its Task Instance Details.

DAG Code:

```

from airflow import DAG
from docker.types import Mount
from airflow.providers.docker.operators.docker import DockerOperator
from datetime import timedelta
from airflow.models import Variable
from airflow.hooks.base_hook import BaseHook
import pendulum
import json

# Amount of times to retry job on failure
retries = 0

environment_config = {
    "DB_WRITE_PASSWORD": BaseHook.get_connection("DATABASE_CONFIG").password,
}

# Setup default args for the job
default_args = {
    "owner": "airflow",
    "start_date": pendulum.datetime(2023, 1, 1, tz="Australia/Sydney"),
    "retries": retries,
}

# Create the DAG
dag = DAG(
    "test_dag",  # DAG ID
    default_args=default_args,
    schedule_interval="* * * * *",  
    catchup=False,
)

# # Create the DAG object
with dag as dag:
    docker_task = DockerOperator(
        task_id="task",
        image="<image>",
        execution_timeout=timedelta(minutes=2),
        environment=environment_config,
        command="<command>",
        api_version="auto",
        docker_url="tcp://docker.for.mac.localhost:2375",
    )
    
```
Rendered Template is good:
![image](https://user-images.githubusercontent.com/41356007/224928676-4c1de3d9-90dc-40dc-bb27-aa10661537ba.png)

In "Task Instance Details"
![image](https://user-images.githubusercontent.com/41356007/224928510-0dc4fc40-f675-49fd-a299-2c2f42feef5b.png)

### Operating System

centOS Linux and MAC

### Deployment

Docker-Compose

### Deployment details

Running on a docker via the airflow docker-compose

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by chriscmorgan** [comment]
This article seems to have a fix for it:
https://medium.com/@poatek/airflow-might-be-leaking-your-passwords-f4ff94647de7

**Comment by chriscmorgan** [comment]
Adding this code to line 1593 of views.py does resolve it:

```
 from airflow.utils.log.secrets_masker import get_sensitive_variables_fields

        for sensitive_key in get_sensitive_variables_fields():
            pattern = rf"((\"|\')[a-z0-9_\.]*{sensitive_key}[a-z0-9_\.]*(\"|\'|\=|:|\s)+(\"|\')?.*?(\"|\'))"
            for attr_name in dir(task):
                if not attr_name.startswith("_"):
                    attr = getattr(task, attr_name)
                    regex_matches = re.findall(pattern, str(attr), re.IGNORECASE)
                    if regex_matches:
                        for match in regex_matches:
                            case_1 = re.findall(r":", match[0], re.IGNORECASE)
                            if case_1:
                                attr = re.sub(re.escape(match[0]), f"{match[0].split(':')[0]}:*******", str(attr))
                            else:
                                attr = re.sub(re.escape(match[0]), f"{match[0].split('=')[0]}=*******'", str(attr))
                            try:
                                setattr(task, attr_name, attr)
                            except Exception as e:
                                logging.error(f"Failed to mask password. Error:{e}")
```

![image](https://user-images.githubusercontent.com/41356007/225161540-711c1c59-414e-433c-96ad-a5080196c92b.png)

**Comment by chriscmorgan** [comment]
@potiuk, is there a guide on how I can get a local build environment up and running. I am keen to a MR for this but struggled to get it building locally.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst (look at "New Contributor" section).

**Comment by niegowic** [comment]
I can see same problem on bash_attribute BashOperator on Task Instance Details - this issue was there in 2.4.0 I was hoping 2.5.2 will fix that but this bug is still there Secrets are properly masked in logs but not in Task Instance Details page:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/60968600/225884913-456cf82c-be1f-45f0-a725-057f113dd1fc.png">

**Comment by herlambang** [comment]
This issue is a potential hit to the security compliance on my workplace, moreover since the blog about this is posted

@chriscmorgan any news on this? 
I'm happy to carry-on on this one. cc: @potiuk

**Comment by potiuk** [comment]
Feel free @herlambang

**Comment by niegowic** [comment]
Problem still not fully fixed - bash_command attribute in bash operator is not masked secrets as expected already put comment in another issue 
<img width="415" alt="image" src="https://github.com/apache/airflow/assets/60968600/eda9326b-9b39-4926-aeb5-46017627e125">

**Comment by potiuk** [comment]
> Problem still not fully fixed - bash_command attribute in bash operator is not masked secrets as expected already put comment in another issue <img alt="image" width="415" src="https://user-images.githubusercontent.com/60968600/238767723-eda9326b-9b39-4926-aeb5-46017627e125.png">

Feel free to open a new issue and put a reference to this one . Making a comment in a closed issue is one of the worst things to make sure that new - similar but not the same - issue is fixed by someone. Or even better make a PR to fix it. Then you won't even have to open an issue.

**Comment by herlambang** [comment]
> Problem still not fully fixed - bash_command attribute in bash operator is not masked secrets as expected already put comment in another issue <img alt="image" width="415" src="https://user-images.githubusercontent.com/60968600/238767723-eda9326b-9b39-4926-aeb5-46017627e125.png">

Are you using something like this?

```python
bash_command=f'export MY_VAR={ Variable.get("THE_SECRET_VALUE") }'
```

I confirm this is still exposing unmasked sensitive value on that way, however it's better to use template variable

```python
bash_command='export MY_VAR={{ var.value.THE_SECRET_VALUE }}'
```

or even better
```python
BashOperator(
    bash_command='echo $MY_VAR',
    env={'MY_VAR': '{{ var.value.THE_SECRET_VALUE }}'
)
```
