### ISSUE TITLE
Bump azure dependencies to newer versions

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#30199]
### Body

This task is about bumping new versions for Azure:
https://github.com/apache/airflow/blob/013490edc1046808c651c600db8f0436b40f7423/airflow/providers/microsoft/azure/provider.yaml#L69-L72

- [x] azure-mgmt-containerinstance https://github.com/apache/airflow/pull/33696
- [x] azure-mgmt-containerinstance to >= 9.0.0 https://github.com/apache/airflow/pull/34738
- [x] azure-mgmt-datafactory https://github.com/apache/airflow/pull/34040
- [x] azure-kusto-data https://github.com/apache/airflow/pull/33598

Note: these will probably require refactoring to hooks

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
assigned
can you please clarify what package are you working on? (there are 3 and each one is to be handled seperatly)

**Comment by shayyxi** [comment]
I am starting with the first one. But isn't it okay if I continue the other two as well?

**Comment by eladkal** [comment]
Its very Ok!

**Comment by shayyxi** [comment]
Any thread/guide to read before proceeding with this task? So that I may know something(which is complicated) about this task?

**Comment by eladkal** [comment]
See https://github.com/apache/airflow/pull/29764#issuecomment-1462356933
