### ISSUE TITLE
delete dag run times out

### ISSUE THREAD

**Issue by talnagar** [apache/airflow#30196]
### Apache Airflow version

2.5.2

### What happened

when trying to delete a dag run with many tasks (>1000) the operation times out and the dag run is not deleted. 

### How to reproduce

attempt to delete a dag run that contains >1000 tasks (in my case 10k) using the dagrun/list/ page results in a timeout:
![image](https://user-images.githubusercontent.com/7373236/226325567-5a87efa1-4744-417e-9995-b97dd1791401.png)

code for dag (however it fails on any dag with > 1000 tasks):
```
import json

from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
from datetime import datetime, timedelta
from airflow.decorators import dag, task

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'retries': 0,
    'retry_delay': timedelta(minutes=1),
    'start_date': datetime(2023, 2, 26),
    'is_delete_operator_pod': True,
    'get_logs': True
}


@dag('system_test', schedule=None, default_args=default_args, catchup=False, tags=['maintenance'])
def run_test_airflow():
    stress_image = 'dockerhub.prod.evogene.host/progrium/stress'  

    @task
    def create_cmds():
        commands = []
        for i in range(10000):
            commands.append(["stress --cpu 4 --io 1 --vm 2 --vm-bytes 6000M --timeout 60s"])
        return commands

    KubernetesPodOperator.partial(
        image=stress_image ,
        task_id=f'test_airflow',
        name=f'test_airflow',
        cmds=["/bin/sh", "-c"],
        log_events_on_failure=True,
        pod_template_file=f'/opt/airflow/dags/repo/templates/cpb_cpu_4_mem_16'
    ).expand(arguments=create_cmds())


run_test_airflow()

```

### Operating System

kubernetes deployment

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Sounds like inefficient query.

**Comment by dzhigimont** [comment]
@potiuk Can I try to solve the issue?

**Comment by potiuk** [comment]
Sure - feel free if you feel like you can dig in.

**Comment by rohan472000** [comment]
@talnagar , you can try increasing the timeout value for deleting dag runs, by setting the dag_parsing_timeout configuration option in your airflow.cfg file. You can try increasing this value to a higher number, such as 3600 (1 hour), to see if it helps.

**Comment by talnagar** [comment]
thanks @rohan472000 but we also have nginx limits on our kubernetes cluster and 1 hours is too long security-wise.
