### ISSUE TITLE
Ensure setup/teardown tasks can be reused/works with task.override

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#30225]
Ensure that this works:

```python
@setup
def mytask():
    print("I am a setup task")

with dag_maker() as dag:
    mytask.override(task_id='newtask')

assert len(dag.task_group.children) == 1
setup_task = dag.task_group.children["newtask"]
assert setup_task._is_setup
```
and teardown also works

**Comment by dzhigimont** [comment]
Can I take it?

**Comment by jedcunningham** [comment]
Hey @dzhigimont, thanks for the engagement here. Unfortunately, I have a feeling this one will be a bit tricky to get working, so you'd probably be better off picking something marked as a [good first issue](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead.

I'll also mention, once you find something, feel free to reach out to [#development-first-pr-support on slack](https://apache-airflow.slack.com/archives/CCZRF2U5A) if you need any help!
