### ISSUE TITLE
apache-airflow-providers-samba module 'smbclient' has no attribute 'link'

### ISSUE THREAD

**Issue by Alexandrmrn** [apache/airflow#30221]
### Apache Airflow Provider(s)

samba

### Versions of Apache Airflow Providers

apache-airflow                           2.5.2
apache-airflow-providers-amazon          3.4.0
apache-airflow-providers-celery          2.1.4
apache-airflow-providers-cncf-kubernetes 4.0.2
apache-airflow-providers-common-sql      1.3.4
apache-airflow-providers-docker          2.7.0
apache-airflow-providers-elasticsearch   3.0.3
apache-airflow-providers-ftp             2.1.2
apache-airflow-providers-google          7.0.0
apache-airflow-providers-grpc            2.0.4
apache-airflow-providers-hashicorp       2.2.0
apache-airflow-providers-http            2.1.2
apache-airflow-providers-imap            2.2.3
apache-airflow-providers-microsoft-azure 3.9.0
apache-airflow-providers-microsoft-mssql 3.0.0
apache-airflow-providers-microsoft-winrm 3.0.0
apache-airflow-providers-mysql           2.2.3
apache-airflow-providers-odbc            2.0.4
apache-airflow-providers-postgres        4.1.0
apache-airflow-providers-redis           2.0.4
apache-airflow-providers-samba           4.1.0
apache-airflow-providers-sendgrid        2.0.4
apache-airflow-providers-sftp            2.6.0
apache-airflow-providers-slack           4.2.3
apache-airflow-providers-sqlite          2.1.3
apache-airflow-providers-ssh             2.4.4
apache-airflow-providers-telegram        3.0.0

### Apache Airflow version

2.5.2

### Operating System

linux suse

### Deployment

Docker-Compose

### Deployment details

just use docker-compose

### What happened

Broken DAG: [/opt/airflow/dags/sambatest.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/samba/hooks/samba.py", line 30, in <module>
    class SambaHook(BaseHook):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/samba/hooks/samba.py", line 86, in SambaHook
    @wraps(smbclient.link)
AttributeError: module 'smbclient' has no attribute 'link'

### What you think should happen instead

perhaps issue like this https://stackoverflow.com/questions/72177073/attributeerror-module-mymodule-has-no-attribute-module1 
 
for at first is seems should importing like <import smbclient.link>  instead of <import smbclient and use @wraps(smbclient.link)>

### How to reproduce

Just create dag and import SambaHook

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Alexandrmrn** [comment]
update wheel file apache_airflow_providers_samba-4.1.0-py3-none-any
set this code 
<...from smbclient import link
    @wraps(link)
    def link(self, src, dst, follow_symlinks=True):
        return link( ...>
Then find this problem and install

  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/samba/hooks/samba.py", line 26, in <module>
    from smbclient import link
ImportError: cannot import name 'link' from 'smbclient' (/home/airflow/.local/bin/smbclient.py)


samba.py checking wrong smbclient library:
this path (/home/airflow/.local/bin/smbclient.py) really havent link attrubute 
but this path /home/airflow/.local/lib/python3.7/site-packages/smbclient/ __init__.py have it

**Comment by potiuk** [comment]
OK. Then it not an airlfow issue. You (or some of the packages you added) added smbclient.py to your ".local/bin" shadowing the smbclient package that gets installed . It does not seem to come from a package - becayse packages installing anything to "bin" folder wil not generally use .py extension. You must remove/rename the file. 

Closing
