### ISSUE TITLE
set tasks as successful/failed at their task-group level.

### ISSUE THREAD

**Issue by masonhopkins** [apache/airflow#30220]
### Description

Ability to clear or mark task groups as success/failure and have that propagate to the tasks within that task group. Sometimes there is a need to adjust the status of tasks within a task group, which can get unwieldy depending on the number of tasks in that task group. A great quality of life upgrade, and something that seems like an intuitive feature, would be the ability to clear or change the status of all tasks at their taskgroup level through the UI.

### Use case/motivation

In the event a large number of tasks, or a whole task group in this case, need to be cleared or their status set to success/failure this would be a great improvement. For example, a manual DAG run triggered through the UI or the API that has a number of task sensors or tasks that otherwise don't matter for that DAG run - instead of setting each one as success by hand, doing so for each task group would be great.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This feature was added in 2.5.0
Please update your Airflow environment and if you experiance issues let us know

**Comment by masonhopkins** [comment]
@eladkal We're on 2.5.1 and, while clear is definitely there (that's my mistake), the ability to mark success/failure does not seem to be available. Can this request be reopened for that distinction?

**Comment by eladkal** [comment]
I guess it ahould be simple after https://github.com/apache/airflow/pull/26658
cc @pierrejeambrun

**Comment by pierrejeambrun** [comment]
Yes I think we can follow a similar approach.

We just need to extract some logic from the `clear` view to avoid code duplication. (row fetch + locking).

**Comment by tquazi** [comment]
@eladkal Can I work on this one? Thanks!

**Comment by eladkal** [comment]
Assigned

**Comment by tquazi** [comment]
Hey @eladkal @pierrejeambrun, Need quick feedback on the UI.

Adding Success/Fail buttons to the existing layout looks something like this:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/1306697/229378690-c19d0034-c3a4-4ddd-bb6a-26cc191623db.png">

When Clearing/Marking Success/Marking Failure at Group level, the buttons Upstream/Downstream/Recursive/Failed makes no sense and have no real value.

Does the below UI layout make sense? 

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1306697/229378810-402799e6-99a8-44bd-9ae1-661332ffc7ae.png">

Any suggestions/feedback?

Thanks!

**Comment by pierrejeambrun** [comment]
Hello @tquazi,

>When Clearing/Marking Success/Marking Failure at Group level, the buttons Upstream/Downstream/Recursive/Failed makes no sense and have no real value.

Why are you saying that Upstream/Downstream/Failed/Recursive don't have value for a task group ?

Yes we can update the layout if this is the actions we are going to end up with, but as you will notice, Upstream/Downstream/ are very useful (unless I am missing something) and you will most likely want to keep a similar layout to what we have for normal tasks.

**Comment by tquazi** [comment]
At taskgroup level if we select Upstream/Downstream, we will be clearing the tasks (upstream/downstream) outside the current taskgroup. My thinking was that, as this action is at TaskGroup level, its impact should be limited to the TaskGroup that the user is working with.

What do you suggest?

**Comment by pierrejeambrun** [comment]
Upstream/Downstream tasks is a really generic concept that is used everywhere (not only in this part of the UI), see: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html

It is indented to work like this and operate 'outsite'/'on related' tasks of the DAG. We have the same behavior when clearing a simple tasks for instance. (We are able to clear upstream/downstream etc...)

Only allowing to perform actions on the task group itself, without being able to specify how to handle dependencies (upstream, downstream, nested groups, etc...) would be too limiting I believe. We already have what is needed on the backend to implement full support for task groups, I think we should do it.

**Comment by tquazi** [comment]
Thanks for the explanation. I will continue to work with the existing layout structure.
