### ISSUE TITLE
Update Python operator how-to with @task.sensor example

### ISSUE THREAD

**Issue by josh-fell** [apache/airflow#30229]
### Body

The current [how-to documentation for the `PythonSensor`](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html#pythonsensor) does not include any references to the existing `@task.sensor` TaskFlow decorator. It would be nice to see how uses together in this doc.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by erdos2n** [comment]
@josh-fell I can take this one

**Comment by erdos2n** [comment]
@josh-fell can you take a look at this and let me know if this is what you envisioned? If not, drop more info and I can continue working on this. Thanks! 

https://github.com/erdos2n/airflow/blob/main/docs/apache-airflow/howto/operator/python.rst#pythonsensor

**Comment by amoghrajesh** [comment]
Was looking for python sensor examples and stumbled upon this issue.
Where did we arrive with this? If the author cannot complete it, I'd like to lead it to completion.
cc @josh-fell @erdos2n

**Comment by vijayasarathib** [comment]
I could help with this issue to complete this issue @josh-fell @erdos2n

**Comment by scr-oath** [comment]
FWIW, I tried this simple sensor code - this use case is similar to how oozie workflows/coordinators can wait for data to exist for their schdeule… 

I was surprised to see that context is not injected into `@task.sensor` is this by design or a separate issue that should be filed?

```python
@dag(
    schedule='@daily',
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    tags=['triggering', 'datasets']
)
def ds_consumer():
    @task.sensor(poke_interval=60, timeout=86400, mode='reschedule')
    def wait_for_upstream(ds=None) -> PokeReturnValue:
        assert ds is not None
        # ... Hits the assertion ^
```

**Comment by josh-fell** [comment]
@scr-oath We can take this over to a Discussion, but what version of Airflow are you using?

**Comment by scr-oath** [comment]
#33121

**Comment by scr-oath** [comment]
> @scr-oath We can take this over to a Discussion, but what version of Airflow are you using?

Latest MWAA (2.5.1)

![image](https://github.com/apache/airflow/assets/41922797/1e3eed2b-d574-4b82-8798-4bc088df18f3)

**Comment by scr-oath** [comment]
Looks like MWAA is behind by ~8 mo - issue is resolved - sorry for the chatter.

**Comment by eladkal** [comment]
Issue is resolved. Documentation shows both classic and `@task.sensor`
