### ISSUE TITLE
Support for per-connection permissions

### ISSUE THREAD

**Issue by kimminw00** [apache/airflow#30232]
### Description

It would be great to be able to grant permission for each connection with the Airflow permission value.

Currently, there are ​​"an create on Connections, can read on Connections, can edit on Connections, can delete on Connections and menu access on Connections".

I think we need "can access on Connection:CONNECTION_NAME, can read on Connection:CONNECTION_NAME, can edit on Connection:CONNECTION_NAME, can delete on Connection:CONNECTION_NAME" as well.

### Use case/motivation

When multiple people use airflow, there needs to limit the connections each user can access.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is impossible today, and will be a part of the multi-tenancy effort that we are incrementally adding. Currently workin on AIP-44 in https://github.com/orgs/apache/projects/169  and long term vision presented in https://airflowsummit.org/sessions/2022/multitenancy-is-coming/

**Comment by potiuk** [comment]
Closing as essentially duplicate.
