### ISSUE TITLE
Feature request - filter for dags with running status in the main page

### ISSUE THREAD

**Issue by match-gabeflores** [apache/airflow#30280]
### Description

Feature request to filter by running dags (or by other statuses too). We have over 100 dags and we were having some performance problems. we wanted to see all the running Dags from the main page and found that we couldn't. We can see the light green circle in the runs (and that involves a lot of scrolling) but no way to filter for it. 

We use SQL Server and it's job scheduling tool (SQL Agent) has this feature. The implementation for airflow shouldn't necessarily be like this but just presenting this as an example that it's a helpful feature implemented in other tools. 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/286903/227529646-97ac2e8e-52de-421a-8328-072f35ccdff2.png">

I'll leave implementation details for someone else. 

on v2.2.5

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I thikn good idea, Marked is a good first issue - hopefully someone will pick it up.

**Comment by eladkal** [comment]
I think its best to implement it as part of https://github.com/apache/airflow/issues/16081
