### ISSUE TITLE
RedshiftToS3 Operator Wrapping Query in Quotes Instead of $$

### ISSUE THREAD

**Issue by paden-stewart** [apache/airflow#30287]
### Apache Airflow version

2.5.2

### What happened

When passing a select_query into the RedshiftToS3 Operator, the query will error out if it contains any single quotes because the body of the UNLOAD statement is being wrapped in single quotes. 

### What you think should happen instead

Instead, it's better practice to use the double dollar sign or dollar quoting to signify the start and end of the statement to run. This removes the need to escape any special characters and avoids the statement throwing an error in the common case of using single quotes to wrap string literals. 

### How to reproduce

Running the RedshiftToS3 Operator with the sql_query: `SELECT 'Single Quotes Break this Operator'` will throw the error

### Operating System

NAME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2" PRETTY_NAME="Amazon Linux 2" ANSI_COLOR="0;33" CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2" HOME_URL="https://amazonlinux.com//"

### Versions of Apache Airflow Providers

apache-airflow[package-extra]==2.4.3
apache-airflow-providers-amazon

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashwaq06** [comment]
Hi, I'd like to work on this issue. I believe the solution is to use double dollar sign or dollar quoting to wrap the query statement in the RedshiftToS3 operator, which will remove the need to escape any special characters. Could you please assign this issue to me so that I can start working on it? Thanks!

**Comment by eladkal** [comment]
@ashwaq06 feel free to raise PR

**Comment by ashwaq06** [comment]
@eladkal I've made some changes to the code to fix handling of single quotes in the RedshiftToS3Operator.

Before submitting the changes, I wanted to perform thorough testing to ensure everything works as expected. However, I'm facing some challenges in running the tests locally. I would greatly appreciate your assistance and guidance in testing these changes to ensure they are of high quality and won't introduce any issues.

**Comment by eladkal** [comment]
> @eladkal I've made some changes to the code to fix handling of single quotes in the RedshiftToS3Operator.
> 
> Before submitting the changes, I wanted to perform thorough testing to ensure everything works as expected. However, I'm facing some challenges in running the tests locally. I would greatly appreciate your assistance and guidance in testing these changes to ensure they are of high quality and won't introduce any issues.

Join Slack Chat https://github.com/apache/airflow#links
There is a channel for `airflow-breeze` and `development-first-pr` where you can get assistance.

**Comment by ashwaq06** [comment]
@eladkal I've raised my first PR . Can you please look into it and let me know if there are still any changes required
[https://github.com/apache/airflow/pull/32915](url)
