### ISSUE TITLE
import error while using BranchPythonOperator in airflow 1.1.1

### ISSUE THREAD

**Issue by smnaveen** [apache/airflow#303]
Im using 1.1.1 version of airflow on centos and the import stmt for the branchpythonoperator seems to be failing. I can import the PythonOperator. What am i missing ? Do i need to upgrade to a newer version to start seeing the BranchPythonOperator in the airflow.operators package ?

**Comment by artwr** [comment]
Hi @smnaveen, yes you would need to upgrade to at least 1.2.0, but would recommend you update to latest.
`pip install --upgrade airflow` with the appropriate extras should be fine. Let me know if you need more info.

**Comment by smnaveen** [comment]
Thank you @artwr. I will upgrade as advised and try it out.

**Comment by mistercrunch** [comment]
Please reopen if it's still a problem in the latest version
