### ISSUE TITLE
in DockerOperator, adding an attribute `tls_verify` to choose whether to validate the provided certificate.

### ISSUE THREAD

**Issue by oboki** [apache/airflow#30309]
### Description

The current version of docker operator always performs TLS certificate validation. I think it would be nice to add an option to choose whether or not to validate the provided certificate.

### Use case/motivation

My work environment has several docker hosts with expired self-signed certificates. Since it is difficult to renew all certificates immediately, we are using a custom docker operator to disable certificate validation.

It would be nice if it was provided as an official feature, so I registered an issue.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/30310
