### ISSUE TITLE
KPO deferrable needs kubernetes_conn_id while non deferrable does not

### ISSUE THREAD

**Issue by iJanki-gr** [apache/airflow#30324]
### Apache Airflow version

2.5.2

### What happened

Not sure if this is a feature not a bug, but I can use KubernetesPodOperator fine without setting a kubernetes_conn_id.
For example:
```
start = KubernetesPodOperator(
        namespace="mynamespace",
        cluster_context="mycontext",
        security_context={ 'runAsUser': 1000 },
        name="hello",
        image="busybox",
        image_pull_secrets=[k8s.V1LocalObjectReference('prodregistry')],
        cmds=["sh", "-cx"],
        arguments=["echo Start"],
        task_id="Start",
        in_cluster=False,
        is_delete_operator_pod=True,
        config_file="/home/airflow/.kube/config",
    )
```

But if I add deferrable=True to this it won't work. It seems to require an explicit kubernetes_conn_id (which we don't configure).

Is not possible to the deferrable version to work as the non deferrable one?

### What you think should happen instead

I hoped that kpo deferrable would work the same as non deferrable.

### How to reproduce

Use KPO with deferrable=True but no kubernetes_conn_id setting

### Operating System

Debian 11

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
This will be changed soon
https://github.com/apache/airflow/pull/28848

**Comment by iJanki-gr** [comment]
KPO deferrable still behaves differently from non deferrable.


[2023-05-31, 08:17:01 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 623, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: Invalid kube-config file. Expected object with name  in kube-config/contexts list


I use kubernetes_conn_id=None in KPO and it works fine. I want to workers to just use the kubeconfig in config_file="/home/airflow/.kube/config".

Using kubernetes_conn_id=None with deferrable=true, causes the error above.
