### ISSUE TITLE
Unexpected behaviour when manually triggering DAG with config using a custom timetable

### ISSUE THREAD

**Issue by Jamie3213** [apache/airflow#30327]
### Apache Airflow version

2.5.2

### What happened

When using a custom timetable, triggering a DAG manually via the Airflow UI using the "Trigger DAG w/ config" option and specifying a logical date in the past causes Airflow to schedule all subsequent DAG runs up to the current time (which have not yet been run) in addition to the manual run.

For context, I'm writing a timetable to support uneven intervals, so the behaviour should be similar to the behaviour when providing a cron schedule. All behaviour is as expected, other than when triggering a DAG run with a logical date in the past. I'd assumed this was an issue with my implementation, but I can see that the `AfterWorkdayTimetable` example [in the docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/timetable.html) also exhibits the same behaviour. I know that cron strings are scheduled using the `CronDataIntervalTimetable`, but it's not clear to me from the source code why this behaves differently to my own timetable or the example timetable in this respect, and I can't see anything in the docs which mentions this behaviour.

### What you think should happen instead

Airflow should create a manual DAG run for the specified logical date, but should not schedule any subsequent DAG runs as a result of this manual DAG run. The behaviour should be equivalent to the behaviour observed when running a DAG whose schedule is given using a cron string.

### How to reproduce

* Create a DAG using the `AfterWorkdayTimetable` example [in the docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/timetable.html) and set `catchup` to `False`.
* From the Airflow UI, use the "Trigger DAG w/ config" feature and specify a logical date in the past which falls on a weekday - Airflow will create a manual run for the specified weekday, but will then schedule all DAG runs subsequent to this up to today.

### Operating System

macOS Ventural Version 13.2.1

### Deployment

Docker-Compose

### Deployment details

Standard Airflow Docker deployment exactly as outlined in the docs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
I tested this bug report with the provided example on Airflow 2.7.0 and latest main and can confirm this "strange" behavior. Made some regression and can confirm that even when `catchup=False` is set, an execution of a manual run from a DAG with a custom TimeTable adds scheduled jobs filling the gap. In total with my tests the scheduling behavior looks inconsistent like below:

Scheduling Expression | Initial Run of Last Time Period | Filling Gaps | Notes
--- | --- | --- | ---
Custom TImetable as example `AfterWorkdayTimetable` | No. Current time period is not started automatically | Yes. When a manual with a logical date in the past is executed, occurrences after this are started and fill the gaps. | This is actually unexpected and inconsistent to other default timetables.
Classic cron expression `"0 0 * * *"` | Yes. An initial run for the current period is made | No. | This is how I expected it as well for a custom timetable.
Usage of `CronTriggerTimetable` | Yes. An initial run for the current period is made | No. | This is how I expected it as well for a custom timetable.
Usage of `EventsTimetable` | Ups, all events defined in the past were executed. | n/a | This was a surprise. Whereas I would see this also as a feature but all defined events in the past were run even when `catchup=False` was set. Might be another bug? Or explicity feature? Could not find any mentioning in the docs, so rather documentation flaw of bug.
Usage of `datetime.timedelta()` | Yes. An initial run for the current period is made | ? Another ups. A second run was scheduled after the manual trigger. | This was also rather unexpected. Can be repeated. Whenever a run with a logical date in the past is triggered, one additional scheduled run based on current time is started as well.

I tried to walk through the code in `airflow/jobs/scheduler_job_runner.py` which I assume is the core part of logic where this is implemented. But after drilling into the code I was lost :-( and not able to pin down the root error. I fear an scheduler expert is needed here for investigation. (@ashb ?)
I assume it is an artifact related to the AIP-39 integration.
