### ISSUE TITLE
trigger_rule=TriggerRule.ALWAYS doesn't work properly with task_groups

### ISSUE THREAD

**Issue by antonio-antuan** [apache/airflow#30334]
### Apache Airflow version

2.5.2 (checked on 2.5.3 also)

### What happened

I'd like to setup "watcher" pattern inside of task_group, but the task always marked as "upstream_failed".
reference to a similar issue: #30333 

### How to reproduce

```
from datetime import datetime

from airflow import DAG
from airflow.decorators import task_group
from airflow.operators.python import task
from airflow.utils.trigger_rule import TriggerRule


@task(retries=0, trigger_rule=TriggerRule.ALWAYS)
def trigger_always():
    pass


@task
def foo(x):
    pass


@task_group()
def process_attestation(x):
    foo(x) >> trigger_always()


with DAG(
        dag_id='test',
        start_date=datetime.now(),
) as dag:
    # Receives sboms from database, one row per each DAG run.
    # Will be changed in the future with HTTP-endpoint or something like that.
    @task
    def provider():
        return [1, 2, 3]


    process_attestation.expand(x=provider())
```

### Operating System

Arch Linux (kernel 6.2.6)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==7.3.0
apache-airflow-providers-common-sql==1.3.4
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==8.11.0
apache-airflow-providers-http==4.2.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-sqlite==3.3.1

### Deployment

Official Apache Airflow Helm Chart

### Anything else

the result graph screenshot:
![image](https://user-images.githubusercontent.com/6426720/227980345-99c991ed-7f99-4a2b-b5f2-46ef29f077fe.png)
task instance details screenshot::
![image](https://user-images.githubusercontent.com/6426720/227980443-bf580dee-7233-4a8e-80af-e4c43237620f.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by antonio-antuan** [comment]
checked on 2.5.3, still reproduced

**Comment by hussein-awala** [comment]
I think that the two issues (this and #30333) are related, I will try to fix them

**Comment by antonio-antuan** [comment]
up
