### ISSUE TITLE
Google Ads API Sunset for Version 11

### ISSUE THREAD

**Issue by cgadam** [apache/airflow#30353]
### Apache Airflow version

2.5.2

### What happened

Current version of Airflow (2.5.2) has as constraint google ads version `18.0.0`, see [here](https://raw.githubusercontent.com/apache/airflow/constraints-2.5.2/constraints-3.7.txt).

Now, version `18.0.0` has support only for `version 11` of the API. See [here](https://github.com/googleads/google-ads-python/pull/672/files#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfbR1) for release notes of version `18.0.0`. Actually the last support for API version was added [here](https://github.com/googleads/google-ads-python/pull/672/files#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfbR9) for `version 11` (`v17.0.0`)

`Version 11` sunset is **today**  (March 29, 2023) which means, starting today API calls done to the API should start failing. See deprecation and sunset days here: https://developers.google.com/google-ads/api/docs/sunset-dates

Long story short, current latest version of Airflow doesn't supports (as part of its constraints file) any actual working version of `google-ads`. 

Not sure how you come up with which versions are meant to be listed  in the constraints file, but, `v12` which is the next version of `google-ads` that is still active was added as supported by `google-ads` in version `18.2.0`. See [here](https://github.com/googleads/google-ads-python/pull/716/files#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfbR1)

Not sure how you test which versions are safe to put in the constraints file, but it seems that it would be worth updating at least to `google-ads 18.2.0` to support a pypi package that can actually interact with Google Ads API. 

### How to reproduce

Just all calls to Google Ads API should start failing when using google-ads version 18 as sunset for v11 which is the max API version supported by that version of the package is sunsetting 

### Operating System

Any

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
google team is working on it in https://github.com/apache/airflow/pull/30067
