### ISSUE TITLE
Need an REST API or/and Airflow CLI to fetch last parsed time of a given DAG

### ISSUE THREAD

**Issue by skpune** [apache/airflow#30365]
### Description

We need to access the time at which a given DAG was parsed last.

Airflow Version : 2.2.2 and above.

### Use case/motivation

End users want to run a given DAG post applying the changes they have done on them. This would mean that the DAG should be parsed post the edits done to it. Right now the last parsed time is available by accessing the airflow database only. Querying the database directly is not the best solution to the problem. Ideally airflow should be exposing APIs that end users can consume that can help provide the last parsed time for a given DAG.

### Related issues

Not Aware.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by maahir22** [comment]
If this is a legit requirement, I'd be willing to submit a PR. Please /assign.

**Comment by shubham22** [comment]
@maahir22 - this definitely is a legit requirement, especially in 2 cases - 1/ users who update and trigger DAGs programmatically, and are looking to confirm that triggering DAG now will include the latest changes. 2/ users who run multiple Airflow environments to accommodate their DAGs and build a simple UI for tracking across all environments.

**Comment by maahir22** [comment]
Correct me if I am wrong, since I am new to this repo - doesn't the end-point GET https://airflow.apache.org/api/v1/dags/{dag_id} provides last_parsed_time for a DAG in the response field? Or is this referring to something else.

**Comment by shubham22** [comment]
You're right! Thanks for pointing it out, I missed that. REST API does provide it, but I think CLI doesn't. However, I can't really find where in CLI it can fit. May be `dags list` can have option to include last_parsed_time?

**Comment by hussein-awala** [comment]
The REST API part already exists, but I think adding it to the CLI through a new command `airflow dags details <dag id>` which returns all the dag details (as https://airflow.apache.org/api/v1/dags/{dag_id}) could be a nice new feature.
@maahir22 assigned you
