### ISSUE TITLE
SnowflakeCheckOperator does not use the database parameter

### ISSUE THREAD

**Issue by fourierlion** [apache/airflow#30408]
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

apache-airflow-providers-snowflake==4.0.4

### Apache Airflow version

2.3.4

### Operating System

Linux

### Deployment

Other 3rd-party Helm chart

### What happened

When running this operator 
```python
SnowflakeCheckOperator(
    task_id="task_name",
    snowflake_conn_id=SNOWFLAKE_CONN_ID,
    database="database_a",
    sql="SELECT COUNT(*) > 0 FROM my_schema.users",
    dag=dag,
)
```
Get the error that 
```
snowflake.connector.errors.ProgrammingError: 090105 (22000): 01ab5318-0001-0771-0001-3f2201bdf396: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
```

### What you think should happen instead

The operator should use the database passed as the operator argument and do not throw the error.

### How to reproduce

Use the operator example above and run a query. The connection id should not have default database.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to take a stab on it.

**Comment by ronald-fenner** [comment]
I ran into this issue as well, however, with the SnowflakeOperator. We tracked it down to a role issue. The message was a red herring in that it wasn't that it was not seeking the db just the role didn't have access to it.
It became a bit more apparent when I switched to using fully qualified names and got an access error to the db.

**Comment by yzliao-zip** [comment]
I feel it is not the role issue for me. I tried to downgrade to 3.x and everything works fine. My suspicion is the `get_hook` function.
