### ISSUE TITLE
Cannot clear tasking instances on "List Task Instance" page with User role

### ISSUE THREAD

**Issue by eejbyfeldt** [apache/airflow#30414]
### Apache Airflow version

main (development)

### What happened

Only users with the role `Admin` are allowed to use the action clear on the TaskInstance list view.

### What you think should happen instead

Users with role `User` should be able to clear task instance in the Task Instance page.

### How to reproduce

Try to clear Task instance while using a user with a `User` role.

### Operating System

Fedora 37

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
@eejbyfeldt assigned you
