### ISSUE TITLE
Conflicting dependency on `python-daemon`

### ISSUE THREAD

**Issue by jgmarcel** [apache/airflow#30416]
### Apache Airflow version

2.5.3

### What happened

When I try to install `apache-airflow[postgres]==2.5.3`, using as constraints the URL `https://raw.githubusercontent.com/apache/airflow/constraints-2.5.3/constraints-3.11.txt`, installation fails with the following error:

```
ERROR: Cannot install apache-airflow[postgres]==2.5.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow[postgres] 2.5.3 depends on python-daemon>=3.0.0
    The user requested (constraint) python-daemon==2.3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### What you think should happen instead

The installation should succeed.

### How to reproduce

Follow the installation instructions given at https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html, with `AIRFLOW_VERSION` equal to `2.5.3` and `PYTHON_VERSION` equal to `3.11`.

### Operating System

Ubuntu 22.04.2 LTS

### Versions of Apache Airflow Providers

```
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-sqlite==3.2.1
```

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Airflow isnt officially support Python 3.11 so constraints are not ready yet.
https://github.com/apache/airflow#requirements

**Comment by potiuk** [comment]
Yep.

**Comment by jgmarcel** [comment]
Sorry I missed that.

**Comment by potiuk** [comment]
I also removed the constraints from there (they were temporary artifact of attempting to bring 3.11 support). This way others will not get confused.

BTW. I hope 3.11 support is coming - maybe in April, for sure in May after some of our dependencies will get bumped to new versions.
