### ISSUE TITLE
Airflow admin user does not get updated

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [apache/airflow#30461]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I have a `docker-compose` stack running with `airflow` `2.3.3`

I am setting the following env vars

```
_AIRFLOW_WWW_USER_EMAIL=someone@somewhere.com
_AIRFLOW_WWW_USER_LASTNAME=Doe
_AIRFLOW_WWW_USER_PASSWORD=mypassword
_AIRFLOW_WWW_USER_USERNAME=myadminusername
_AIRFLOW_WWW_USER_FIRSTNAME=John
```

I recreated the `docker-compose` stack and changed just the password to

```
_AIRFLOW_WWW_USER_PASSWORD=myNEWpassword
```

I `exec` into the web server container and I see that indeed `_AIRFLOW_WWW_USER_PASSWORD` is set to `myNEWpassword`.

However I cannot login with this, but rather still with `mypassword`

### What you think should happen instead

The `admin` user password should change to `myNEWpassword`

### How to reproduce

Create a `docker-compose` stack and set the following env vars

```
_AIRFLOW_WWW_USER_EMAIL=someone@somewhere.com
_AIRFLOW_WWW_USER_LASTNAME=Doe
_AIRFLOW_WWW_USER_PASSWORD=mypassword
_AIRFLOW_WWW_USER_USERNAME=myadminusername
_AIRFLOW_WWW_USER_FIRSTNAME=John
```

Verify that you can login.

Change the `_AIRFLOW_WWW_USER_PASSWORD` env var from `mypassword` to `myNEWpassword`.

Restart the stack by also recreating the containers.

You should still be able to login with `mypassword` instead of `myNEWpassword` as expected.

### Operating System

Ubuntu 20.04.2 LTS

### Deployment

Docker-Compose

### Deployment details

The deployment is in `docker-compose` using an RDS PG as database.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pantelis-karamolegkos** [comment]
Are there any specific instructions on how to do this?

**Comment by potiuk** [comment]
Just read the docs of airlfow and see the CLI/API to manage users. Those are your instructions. How you use them it is up to you.
