### ISSUE TITLE
Task stalled on "no status" keeps the DAG run status as "running"

### ISSUE THREAD

**Issue by alejandrofm** [apache/airflow#30491]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi, I'm in Airflow 2.4.2, couldn't find a similar issue, when a DAG is configured with "depends_on_past = True", and the task is blocked on status "no status" the DAG run stays in status=Running, using a running slot.
<img width="108" alt="image" src="https://user-images.githubusercontent.com/19591174/230212619-6645d8af-4bd5-44c2-9038-82d1d72e5280.png">

### What you think should happen instead

The task+DAG run should be on a status like "stalled" not using a run slot and the dag shouldn't be on status running.

### How to reproduce

Set a DAG with depends_on_past =  True
Make a task fail so he next cant start (status=no status)
the DAG run will be "running" infinitelly

### Operating System

apache/airflow:2.4.2-python3.10

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
First of all, this is not a bug, rather it is a new feature request.

As long as the dag run has at least one unfinished task(state not in [success, failed, skipped, upstream_failed, removed]), and the dag run is not timed out and not manually cleared , its state should remain running.

For the new proposed state `stalled`, I think this can add a lot of complexity to the scheduler job, which should process the dag runs with the state `stalled` in the critical section like the state `running` to check if the tasks are unblocked or they still somehow blocked, and should not run any task in the stalled dag runs before passing them to running, respecting that the count of running tasks is less than or equal to the max active dag runs.

IMHO this can be a good feature in some use cases, especially in large dags that have a small number of tasks with depend_on_past or with a small pool size. I convert it to discussion.
