### ISSUE TITLE
Stuck docker compose

### ISSUE THREAD

**Issue by Alexandrmrn** [apache/airflow#30508]
### Apache Airflow version

2.5.3

### What happened

Server working correctly but once without any errors webserver container stopped
I cant do anything with it, every command (without docker compose start) executing infinity like this docker up
 ⠹ Container airdata-airflow-webserver-1  Recreate                                                               300.2s

docker ps showing status (unhealthy)  of airdata-airflow-webserver-1 container

### How to reproduce

-

### Operating System

linux suse

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Can you provide the container log and the output of `docker inspect <container id>`?

**Comment by Alexandrmrn** [comment]
> 
I cant do any docker command with this container
docker inspect showing infinite executing command, but else container showing logs

![image](https://user-images.githubusercontent.com/48490798/230561428-a4e1d42c-b864-4f2f-aede-dafc48ddee7f.png)

**Comment by Alexandrmrn** [comment]
Ok I made this steps and container again available
We can close ticket 

[qqdokr0@ltdkswarm02vm](mailto:qqdokr0@ltdkswarm02vm):~> exit
logout
[q160884@ltdkswarm02vm](mailto:q160884@ltdkswarm02vm):~> whoami
q160884

[q160884@ltdkswarm02vm](mailto:q160884@ltdkswarm02vm):~> sudo /usr/bin/systemctl daemon-reload
SSO Password:
[q160884@ltdkswarm02vm](mailto:q160884@ltdkswarm02vm):~> sudo /usr/bin/systemctl restart docker

**Comment by potiuk** [comment]
Next time @Alexandrmrn PLEASE do not upe an issue for your troubleshooting - you SHOULD open Github discussion instead (as you are explained clearly while opening an issue). Issues here are not a helpdesk to solve your problems, or troubleshoot, they are to raise issues with Airflow itself. If unsure if it is airflow or your problem. open discussion. This will save some time of volunteers who maintain the project. 

And BTW. You can close issue you opened yourself, this is self-service, you do not have to ask anyone to do it.
