### ISSUE TITLE
CI Docker Image not found for Airflow 1.10.15 (Bridge Release)

### ISSUE THREAD

**Issue by shivam-oj** [apache/airflow#30534]
### What do you see as an issue?

I have cloned this repository and switched to the branch `v1-10-stable` like suggested here:
https://airflowsummit.org/sessions/production-docker-image/

And, following the steps here: https://github.com/apache/airflow/blob/v1-10-stable/BREEZE.rst
Breeze gets installed without any issues.

However, when I try to build the CI image from the root directory of the github repo, the `./breeze` command fails with this error:
`Error response from daemon: manifest for apache/airflow:python3.8-v1-10-test not found: manifest unknown: manifest unknown`

Furthermore, I am not able to find any CI images except for `1.10.12-python2.7-ci` on Dockerhub.
Are the other CI images no longer present on Dockerhub?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Closing. 1-10 is not maintained for 3 years.  You are 3 years behind. Surely with your extensive research you found that 1.10 end of life was almost 3 years ago and that the latest version of airflow is 2.5.3 - which is about 30 versions ahead of 1.10.12 ? 

The links you are pointing at are from 2020 - in cased you missed this crucial information

**Comment by shivam-oj** [comment]
Thanks! I understand that version 1.10.15 is the last one in the 1.x series and my intention too is to upgrade to 2.x.

We are using an even older version of Airflow (1.10.9) in my organisation and this document seems to suggest that we upgrade to the Bridge Release (1.10.15) first to minimise friction and then upgrade to Airflow 2:
https://airflow.apache.org/docs/apache-airflow/stable/howto/upgrading-from-1-10/index.html

**Comment by potiuk** [comment]
Then why do you use Breeze? Breeze is for airflow development only and you should never use it to migrate. CI images are used for developing Airflow. For using airflow you should use images published in dockerhub https://hub.docker.com/r/apache/airflow/tags?page=1&name=1.10


Why do you think you should use Breeze and CI image? Where the idea came from?

**Comment by shivam-oj** [comment]
Ah, understood - a misunderstanding on my part.
Thank you!
