### ISSUE TITLE
alembic Logging

### ISSUE THREAD

**Issue by geekykayaker** [apache/airflow#30562]
### Apache Airflow version

2.5.3

### What happened

When I call the airflow initdb function, it outputs these lines to the log

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

### What you think should happen instead

There should be a mechanism to disable these logs, or they should just be set to WARN by default

### How to reproduce

Set up a new postgres connection and call:

from airflow.utils.db import initdb
initdb()

### Operating System

MacOS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by geekykayaker** [comment]
https://github.com/apache/airflow/pull/30563

**Comment by hussein-awala** [comment]
@amoghrajesh assigned you. [Here](https://github.com/apache/airflow/pull/30563#pullrequestreview-1380243607) is the solution we discussed to solve this issue
