### ISSUE TITLE
Missing mapped task logs when using Dynamic task groups

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#30578]
### Apache Airflow version

2.5.2

### What happened

When using dynamic task groups mapping I cannot access logs of the mapped task instances

![obrazek](https://user-images.githubusercontent.com/31843161/231144317-5d29e07d-9e50-4540-b482-d080e80793f2.png)

### What you think should happen instead

I want to be able to click through logs of mapped task instances in the Grid View in Airflow UI

### How to reproduce

Follow tutorial https://docs.astronomer.io/learn/dynamic-tasks#mapping-over-task-groups

### Operating System

debian

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
duplicates: #30276
