### ISSUE TITLE
Pendulum America/Mexico_City Timezone no Longer Correct

### ISSUE THREAD

**Issue by alex-astronomer** [apache/airflow#30605]
### Apache Airflow version

2.5.3

### What happened

Mexico senate voted to change their rules on DST last year in October.  Mexico's timezones (for the most, including Mexico City) are now running at UTC-6.  As of last year at this time, Mar 21st was the date that Mexico would bring their clock forward for DST.

`pendulum` depends on `pytzdata`.  The latest version of `pytzdata` is from 2020, so it doesn't have this information in it.

Therefore, theoretically and as tested, Airflow has the wrong time for Mexico now.

### What you think should happen instead

All timezones should be up to date.

### How to reproduce

On a virtualenv with just Airflow installed, and everything else default, run this script:

```
import pendulum

local_tz = pendulum.timezone("America/Mexico_City")
print(pendulum.now(local_tz))
```

This will display the old time before the change was in place.

### Operating System

Docker Linux

### Versions of Apache Airflow Providers

n/a

### Deployment

Virtualenv installation

### Deployment details

Everything default.

### Anything else

[Here](https://github.com/sdispater/pendulum/issues/700) is the related issue on `pendulum`'s Github.

Pendulum pre-release 3.0.0 might address this, but it has some breaking changes from what I've read.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
There is no action item we can take here. It's upstream library problem not a bug in Airflow.
I already submitted doc clarification about such issues https://github.com/apache/airflow/pull/30467
