### ISSUE TITLE
Airflow fetching too many tokens from Vault

### ISSUE THREAD

**Issue by llamageddon83** [apache/airflow#30611]
### Apache Airflow Provider(s)

hashicorp

### Versions of Apache Airflow Providers

3.3.0

### Apache Airflow version

2.5.3

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### What happened

We use Vault as the secrets backend for Airflow. And we have noticed quite an abnormal pattern where Airflow asks for 400 tokens every 10 minutes. This is when all the DAGs are disabled/paused. When the DAGs, totaling 300ish, are enabled and running, the number of tokens spikes to 40K. The TTL on the tokens is 15 minutes. Most of our DAGs finish within 10 minutes. 

We initially thought it was due to a typical pattern in the code related to how DAGs access secrets. But upon further troubleshooting, this happens during the auth, which is probably when the pod comes up. (We use Kubernetes Executor).

### What you think should happen instead

The token should be cached and Airflow should not be requesting a new token for every DAG execution. Even without any DAG executing, Airflow is asking for tokens.

### How to reproduce

Start Airflow with Kubernetes Executor and Vault as the secrets backend. Observe the number of tokens/leases in Vault. 

### Anything else

The following is after disabling all the DAGs in one of our lower environments. We can identify number of leases based on the read policy associated with Airflow.

![vault-leases](https://user-images.githubusercontent.com/108699169/231593538-2a96daad-8ced-47ab-9a55-c52882511c77.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by throwawayaccount11111** [comment]
![vault-leases](https://user-images.githubusercontent.com/108699169/231593288-725956bd-5c91-4b4f-9544-02452f1adf23.png)
