### ISSUE TITLE
default_args not propagated to tasks that don't have dag referenced inside a chain method

### ISSUE THREAD

**Issue by el-aasi** [apache/airflow#30620]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow 2.4.3 

When defining the task dependency using chain method - it is only required to pass the dag object only to one of the tasks, and for the downstream tasks it will be inferred. But the default_args are only passed to the task that has the dag object. 

### What you think should happen instead

Since chain method allows to only pass the dag to the first task - the default_args should follow the same principle and be propagated to all tasks inside the chain method. 

### How to reproduce

Create a dag that has the default_args specified. Create a few tasks and chain then using the chain method from airflow.models.baseoperator. Only add the dag argument to the first task in the chain, observe that the default args are not passed to the rest of the tasks. 

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.3.4
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.2.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-sqlite==3.3.1

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dzhigimont** [comment]
@el-aasi Hi, could you please provide the code with your DAG?

**Comment by el-aasi** [comment]
Hey @dzhigimont here's a simple example that demonstrates it: 

```
from airflow import DAG
from airflow.models.baseoperator import chain
from airflow.utils.dates import days_ago
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import (
    KubernetesPodOperator,
)


my_dag = DAG(
    dag_id="some_dag_id",
    description="some_dag_descrption",
    default_args={"namespace": "my_namespace"},
    schedule_interval="@once",
    start_date=days_ago(1),
)

operators_list = [
    KubernetesPodOperator(task_id="1", name="1", dag=my_dag),
    KubernetesPodOperator(task_id="2", name="2"),
    KubernetesPodOperator(task_id="3", name="3", dag=my_dag),
    KubernetesPodOperator(task_id="4", name="4"),
]

chain(*operators_list)

for operator in operators_list:
    print(operator.namespace)
```

my expectation would be that the namespace for all operators would be `my_namespace`, but in reality it is only set for operator 1, 3 the ones that have dag as argument when constructing. Now my assumption is only based on the fact that when using `chain` method we are not required to pass dag to all operators but rather on the first ones. 

results: 
![image](https://user-images.githubusercontent.com/27493937/231743598-b44aecd5-4eeb-4a3a-b47e-3c3dca2e6ea4.png)

**Comment by dzhigimont** [comment]
It's better to use the context manager when you create a DAG and everything will work fine:
```
with DAG(
    dag_id="some_dag_id",
    description="some_dag_descrption",
    default_args={"namespace": "my_namespace"},
    schedule_interval="@once",
    start_date=days_ago(1),
):

    operators_list = [
        KubernetesPodOperator(task_id="1", name="1"),
        KubernetesPodOperator(task_id="2", name="2"),
        KubernetesPodOperator(task_id="3", name="3"),
        KubernetesPodOperator(task_id="4", name="4"),
    ]

    chain(*operators_list)

for operator in operators_list:
    print(operator.namespace)
```
result: 
```
my_namespace
my_namespace
my_namespace
my_namespace

Process finished with exit code 0
```

**Comment by ephraimbuddy** [comment]
> It's better to use the context manager when you create a DAG

Or add the dag argument to all the tasks in the list.

**Comment by el-aasi** [comment]
@ephraimbuddy I think that closing the issue was a bit pre-mature? While yes, there are workarounds and alternatives - the specific described bug is still present, so unsure if maybe it would be a good idea to keep it open?

**Comment by mziwisky** [comment]
we encountered this same issue when using the taskflow interface and wanting to attach a "heartbeat" task at the end of the dag:

```py
@task
def do work():
    # ...

@task
def more_work():
    # ...

@dag
def my_dag():
    do_work()
    more_work()

the_dag = my_dag()
the_dag.leaves >> heartbeat_task()
```

the options i'm aware of are either change that last line to `the_dag.leaves >> heartbeat_task.override(dag=the_dag)()`, or refactor it to use the context manager so that the heartbeat task could be instantiated in a place that the dag instance was available:

```py
with DAG('my_dag') as dag:
    do_work()
    more_work()

    dag.leaves >> heartbeat_task()
```

the taskflow interface sure feels like the "recommended" way to write dags, even if that's not explicitly stated anywhere, so i'm a little irked by the fact that we can't use it here without the `.override`, but it's not a huge deal.  the context manager option feels cleaner than the `.override` one, but one potential pitfall is if you de-indent that last line, it doesn't break (because python "leaks" the scope of that `dag` var), rather you'll just lose your default args.

i guess my question is, why _not_ propagate the `dag` property to all tasks in a dag's graph?  i see airflow already guards against setting that property to the _wrong_ dag, e.g.:

```py
with DAG('test_1') as dag1:
    do_work()

with DAG('test_2') as dag2:
    more_work()

dag2.leaves >> heartbeat_task.override(dag=dag1)()
```

that blows up with:

```
Broken DAG: [/usr/local/airflow/dags/test.py] Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 237, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 195, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: test_2>, <DAG: test_1>}
```

so apparently the `dag` property can either be the correct DAG, or `None`.  what's the use case of letting it be `None`, besides perhaps slightly less boilerplate needed to unit test?
