### ISSUE TITLE
Tasks forked by the Local Executor are loading stale modules when the modules are also referenced by plugins

### ISSUE THREAD

**Issue by ghost** [apache/airflow#30796]
### Apache Airflow version

2.5.3

### What happened

After upgrading from Airflow 2.4.3 to 2.5.3, tasks forked by the `Local Executor` can run with outdated module imports if those modules are also imported by plugins. It seems as though tasks will reuse imports that were first loaded when the scheduler boots, and any subsequent updates to those shared modules do not get reflected in new tasks. 

I verified this issue occurs for all patch versions of 2.5.

### What you think should happen instead

Given that the plugin documentation states:
> if you make any changes to plugins and you want the webserver or scheduler to use that new code you will need to restart those processes.

this behavior may be attended. But it's not clear that this affects the code for forked tasks as well. So if this is not actually a bug then perhaps the documentation can be updated.

### How to reproduce

Given a plugin file like:
```python
from airflow.models.baseoperator import BaseOperatorLink
from src.custom_operator import CustomOperator


class CustomerOperatorLink(BaseOperatorLink):
    operators = [CustomOperator]
```

And a dag file like
```
from src.custom_operator import CustomOperator
...
```

Any updates to the `CustomOperator` will not be reflected in new running tasks after the scheduler boots.

### Operating System

Debian bullseye

### Deployment

Docker-Compose

### Anything else

Workarounds
- Set `execute_tasks_new_python_interpreter` to `False`
- In my case of using Operator Links, I can alternatively set the Operator Link in my custom operator using `operator_extra_links`, which wouldn't require importing the operator from the plugin file.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think it might be a side-effect of some of our import optimisatios and I am not even sure whether the original intention was to reload plugins on tasks or not cc: @uranusjr WDYT?

Also I tihnk this one will become even more true for DAG parsing after https://github.com/apache/airflow/issues/30796 also for DAG parsing cc: @vandonr-amz . 

I wonder if we should agree on the expected behaviour for all components and stick to it (and possibly even add tests for those). 

WDYT?

**Comment by vandonr-amz** [comment]
so we should go with

> If this is not actually a bug then perhaps the documentation can be updated.

**Comment by potiuk** [comment]
> so we should go with

>> If this is not actually a bug then perhaps the documentation can be updated.

If we agree this is the "expected" behaviour, then yes

**Comment by uranusjr** [comment]
Honestly I think this is expected and essentially how Python works. The modules are not “stale”, they are just normal modules and naturally are always there. I’d say a note in documentation is sufficient.

**Comment by vijayasarathib** [comment]
I can work on the documentation to get this issue closed @potiuk
