### ISSUE TITLE
Invalid default for xcom.timestamp column

### ISSUE THREAD

**Issue by NeilHanlon** [apache/airflow#308]
The migration for the new xcom table has an invalid value for the default for the timestamp column, which is causing the migration to fail.

https://github.com/airbnb/airflow/blob/master/airflow/migrations/versions/13eb55f81627_add_xcom_and_import_error.py

```
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1067, "Invalid default value for 'timestamp'") [SQL: u'\nCREATE TABLE xcom (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\t`key` VARCHAR(512), \n\tvalue BLOB, \n\ttimestamp DATETIME DEFAULT CURRENT_TIMESTAMP, \n\texecution_date DATETIME NOT NULL, \n\ttask_id VARCHAR(250) NOT NULL, \n\tdag_id VARCHAR(250) NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n']
```

**Comment by jlowin** [comment]
@NeilHanlon just pushed some changes to the migrations -- mind trying again?

**Comment by mistercrunch** [comment]
Should be fixed. Reopen if it's still an issue.
