### ISSUE TITLE
TriggerDagRunOperator was not creating an task instance for external Dag which have schedule interval as None 

### ISSUE THREAD

**Issue by krishnakanth1666** [apache/airflow#30828]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I have four trigger dag run operators in the single Dag and trying to execute one after the other on the successful completion of the previous,but some of the task instances were not triggering and show as None State.

### How to reproduce

create two or more dags using trigger dagrunoperators and schedule them at sometime and making external dags schedule to none and see if you can find the same issue of not triggering the tasks with None status

### Operating System

Linux

### Deployment

Other

### Deployment details

deployed on gcp server 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
are you facing this on airflow 2.0.0? otherwise can you please tell us the specific airflow version for example 2.5.3?
