### ISSUE TITLE
Sort Dag List by Last Run Date

### ISSUE THREAD

**Issue by TryHarder01** [apache/airflow#30838]
### Description

It would be helpful to me if I could see the most recently ran DAGs and their health in the Airflow UI. Right now many fields are sortable but not last run.

The solution here would likely build off the previous work from this issue: https://github.com/apache/airflow/issues/8459

### Use case/motivation

When my team updates a docker image we want to confirm our DAGs are still running healthy. One way to do that would be to pop open the Airflow UI and look at our teams DAGs (using the label tag) and confirm the most recently ran jobs are still healthy. 

### Related issues

I think it would build off of https://github.com/apache/airflow/issues/8459

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tquazi** [comment]
@eladkal Can I take this one?

**Comment by eladkal** [comment]
opening as PR was reverted.
New PR https://github.com/apache/airflow/pull/31234
