### ISSUE TITLE
Task Group Mapped Instances doesn't show in "Grid" view

### ISSUE THREAD

**Issue by pargass31** [apache/airflow#30834]
### Apache Airflow version

2.5.3

### What happened

When using expand for a task_group, the mapped instances doesn't show in the "Grid" view (but it is ok in the graph view)

### What you think should happen instead

The "Grid" view should show the "[]" close to the task group name, and propose to choose one instance to see logs, in the same way that works for Task with expand.

### How to reproduce

```
from airflow import DAG
from airflow.decorators import task_group, task
from pendulum import datetime

@task_group(group_id="group1")
def tg1(my_num):
    @task
    def print_num(num):
        return num

    @task
    def add_42(num):
        return num + 42

    print_num(my_num) >> add_42(my_num)


with DAG(
        "test_group_expand",
        start_date=datetime(2023, 3, 3),
) as dag:
    tg1.expand(my_num=[19, 23, 42, 8])
```

### Operating System

Ubuntu 22.04.2 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-sqlite==3.3.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
aaah Cool :)

**Comment by pargass31** [comment]
Oh great! Thanks a lot!
