### ISSUE TITLE
RunID has changes

### ISSUE THREAD

**Issue by fokmess** [apache/airflow#30840]
### Apache Airflow version

2.5.3

### What happened

When TI has cleared RunID + replace to spacebar
<img width="779" alt="Снимок экрана 2023-04-24 в 17 34 35" src="https://user-images.githubusercontent.com/61796911/234028990-58a56692-d3dc-4ef2-8c4d-ff5235357581.png">

<img width="688" alt="Снимок экрана 2023-04-24 в 17 35 18" src="https://user-images.githubusercontent.com/61796911/234029184-a284524c-8409-4d27-820c-63407794e023.png">

### How to reproduce

1. Filter by RunID
2. Clear Task Instance
3. Look at RunID value

### Operating System

Ubuntu 22.04.1 LTS

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by parth166** [comment]
Hi, can I work on this? I am new to Apache Airflow and since it has been marked as a good first issue. 
I would like to give it a shot.

**Comment by potiuk** [comment]
Another error that seems to be a duplicate in #30898 - @parth166 if you are still working on it, that might give you more clues on reproducibility

**Comment by parth166** [comment]
> Another error that seems to be a duplicate in #30898 - @parth166 if you are still working on it, that might give you more clues on reproducibility

Hey @potiuk - Yess, I was able to reproduce the error. Thanks for this - I'll use this as a hint too!

**Comment by potiuk** [comment]
deassigned you. Hopefully someone else will look at it

**Comment by herlambang** [comment]
Hi @potiuk , I'm able to reproduce it on main branch, I can take this one?
However I'm unable to reproduce #30898 from steps its provided

**Comment by herlambang** [comment]
I can confirm this issue is fixed on werkzeug 2.3.x, but there's dependency conflict on upgrading 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
connexion 2.14.2 requires werkzeug<2.3,>=1.0, but you have werkzeug 2.3.0 which is incompatible.
```

**Comment by potiuk** [comment]
Then we will have to wait for 3.0.0 of connexion https://pypi.org/project/connexion/3.0.0a6/ released 24 April with werkzeug <3. This will almost certainly mean that if there will be no errors during API tests, it will get fixed automatically by our constraints upgrades.

**Comment by tirkarthi** [comment]
This seems like a related werkzeug issue : https://github.com/pallets/werkzeug/issues/2657 . @fokmess Can you please confirm the version of werkzeug used and the URL before and after you hit search button?

**Comment by potiuk** [comment]
> This seems like a related werkzeug issue : [pallets/werkzeug#2657](https://github.com/pallets/werkzeug/issues/2657) . @fokmess Can you please confirm the version of werkzeug used and the URL before and after you hit search button?

Yes It is - see the comments just above yours @tirkarthi

**Comment by tirkarthi** [comment]
@potiuk My question was since the bug is present only on 2.3.0 (fixed in 2.3.1) and there is "connexion 2.14.2 requires werkzeug<2.3,>=1.0, but you have werkzeug 2.3.0 which is incompatible." pip resolution error. So I was just curious about the version and how they ended up in this state. Maybe that an older version of pip didn't catch this since resolver is in newer version of pip. 2.2.3 doesn't have this change and using that should also fix this issue along with being compatible.

**Comment by potiuk** [comment]
> @potiuk My question was since the bug is present only on 2.3.0 (fixed in 2.3.1) and there is "connexion 2.14.2 requires werkzeug<2.3,>=1.0, but you have werkzeug 2.3.0 which is incompatible." pip resolution error. So I was just curious about the version and how they ended up in this state. Maybe that an older version of pip didn't catch this since resolver is in newer version of pip. 2.2.3 doesn't have this change and using that should also fix this issue along with being compatible.

Ah. I see that this is 2.3.0 ONLY bug. I have not see it before - then we can simpy add !=2.3.0 in airflow to fix it.

**Comment by potiuk** [comment]
(and indeed the user might be able to just downgrade it manually if they wish to)

**Comment by herlambang** [comment]
Airflow 2.5.3

```
❯ pip freeze | grep Werkzeug
Werkzeug==2.2.3
```

Also there's dependency from FAB that requires `werkzeug==2.2.3` at the moment, which also becoming constrain in upgrading. 
Going to pull my self off from this issue as it seems would be a long waiting.
