### ISSUE TITLE
Add docker options when running an image

### ISSUE THREAD

**Issue by srendon** [apache/airflow#30851]
### Description

Interested on adding docker run options such as `--dns`, `--cap-add`, `--device`, etc. I'm using `KubernetesPodOperator`

### Use case/motivation

I'm trying to use openvpn and to be able to use it on the docker container I need use docker run options. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dzhigimont** [comment]
@srendon Speaking in terms of Kubernetes pod configuration is not the same as speaking in terms of the docker run command, so firstly, you should understand which configuration for pod you require, and then we can help implement it. For example, in the Kuberneted pod, there is no equivalent configuration as  `--device` Read the following discussion https://stackoverflow.com/questions/59290752/how-to-use-device-dev-video0-with-kubernetes. What about --cap-add It will be equivalent to something like this: `container_security_context={"capabilities": {"add": "NET_ADMIN"}}`.  Only what I see that  `dns_config` is missed. @eladkal @potiuk What do you think should we add possibility to set dns_config to the KubernetesPodOperator ?

**Comment by potiuk** [comment]
If there is anything that can't be done via current capabilities, then we can add it if somone will make a PR.

**Comment by potiuk** [comment]
Marked it as good first issue.

**Comment by RachitSharma2001** [comment]
I would like to work on this if that is ok. In terms of the implementation, I was thinking of add a field `docker_run_options` to the KubernetesPodOperator, where the user could then specify particular options like so:
```
KubernetesPodOperator(
      namespace="default",
      image="....",
     docker_run_options=["dns", "cap-add"],
  )
```

Let me know if this design makes sense or if there may be a better way. 

Also, because there are some run options that are not possible on Kubernetes, such as --device, I was thinking that the documentation could specify which run options are possible.

**Comment by potiuk** [comment]
Usually it's best to make a PR and discuss it there rather than discuss it upfront. It's small enough change to be able to iterate on it easily and discussing it on the changed code is far more productive than abstract discussion with copying parts of code.  Feel free to create one. Assigning you.

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/30992
