### ISSUE TITLE
Wrong DAG duration time

### ISSUE THREAD

**Issue by wycmiko** [apache/airflow#30877]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version: Airflow 2.2

There is an erroneous duration shown in the figure, the overall DAG duration is 1min8s, but the following sub-task has run for many hours, and the overall time consumption is not accurate:
![image](https://user-images.githubusercontent.com/34699047/234481097-0c1d1e5b-03a6-4795-a97c-b557da74970e.png)
and we can see another task's duration under this dag is more than 9h:
![image](https://user-images.githubusercontent.com/34699047/234481336-5726e30a-f30a-4b8f-aff4-455ab876c7fb.png)

### What you think should happen instead

Does this mismatched duration metric relates to the clear retry operation?

### How to reproduce

Registering a dag then clear specific task may cause the mismatched overall duration metric

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

Airflow 2.2

### Deployment

Other Docker-based deployment

### Deployment details

we are using the Google Kubernetes cluster and deploy Airflow image.

### Anything else

Some times this issue will happen, not frequently.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
The screenshots attached are from Tree View which was removed in favor of Grid view starting Airflow 2.3.0
Closing as there is no action items on code that we no longer have.

**Comment by arley-wilches** [comment]
Hi there.

I found a similar issue, the duration time does not take into account mapped tasks and I have two tasks
one of them took about 3 hours and the other one took a similar time but I rerun a couple of times one of their tasks, but the bar is
<img width="400" alt="Screenshot 2024-03-24 at 3 42 00 PM" src="https://github.com/apache/airflow/assets/67939534/669eb5ae-84d6-4f4e-bcdd-90e6b6ebc39c">
<img width="479" alt="Screenshot 2024-03-24 at 3 42 06 PM" src="https://github.com/apache/airflow/assets/67939534/2a75ef6f-83e1-4e30-a40f-16ea1c60bbe3">
<img width="734" alt="Screenshot 2024-03-24 at 3 42 44 PM" src="https://github.com/apache/airflow/assets/67939534/ce07ed00-e8a4-443e-b80b-ec428153ffe2">

 incorrect.

the other issue is, the total time was about 3 hours, the duration say 23 hours, 
when I rerun the task, that total time was about 3 hours but it showed 12 min.

I am using:
Version: [v2.8.1](https://pypi.python.org/pypi/apache-airflow/2.8.1)
Git Version: .release:c0ffa9c5d96625c68ded9562632674ed366b5eb3

**Comment by HuanjieGuo** [comment]
We also met this issue. 

The dagrun duration shows that it ran for 3 mins and 10 sconds.
 
![image](https://github.com/user-attachments/assets/c0ee2865-63b2-4199-9330-4689d6d6bbe5)

However, one task in this dagrun already ran for 3 hours and 23 mins.
![image](https://github.com/user-attachments/assets/9ca2f5cc-3827-4e4d-a3c3-349a4e6f511a)

Version: 2.7.2
