### ISSUE TITLE
Different timezone with pendulum on start_date doesn't work with @task.flow

### ISSUE THREAD

**Issue by fuechter** [apache/airflow#30893]
### Apache Airflow version

2.5.3

### What happened

When I set a start_date with different timezone (ex: `America/Mexico_City`) in @task.flow, airflow doesn't respect the parameter, but when I see in WEB UI, show only timezone of core settings (in the example, the timezone's core settings is `America/Sao_Paulo`)

```python

from airflow.decorators import dag, task
import pendulum

start_date = pendulum.now('America/Mexico_City') - pendulum.duration(
    days=7,
    hours=0
)

@dag(
    dag_id='teste_dag',
    schedule_interval='* 5 * * *',
    start_date=start_date,
    catchup=False,
    max_active_runs=1
)
def teste_dag():

    @task
    def test():
        print('teste')
        
    test()

dagT = teste_dag()
```
WEB UI Airflow:
<img width="572" alt="Screen Shot 2023-04-26 at 17 25 04" src="https://user-images.githubusercontent.com/890738/234694093-bb335a45-b331-43c2-8685-7cce78893fd2.png">

### What you think should happen instead

Should change the timezone of DAG, has an example about this on airflow's official document: https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timezone.html#time-zone-aware-dags

### How to reproduce

It's a simple dag

```python

from airflow.decorators import dag, task
import pendulum

start_date = pendulum.now('America/Mexico_City') - pendulum.duration(
    days=7,
    hours=0
)

@dag(
    dag_id='teste_dag',
    schedule_interval='* 5 * * *',
    start_date=start_date,
    catchup=False,
    max_active_runs=1
)
def teste_dag():

    @task
    def test():
        print('teste')
        
    test()

dagT = teste_dag()
```

### Operating System

Debian GNU/Linux 11 (bullseye) - Docker

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
look closely at the docs. You have not set DAG to the timezone, you set it's start_date and the documentation you linked to, clearly describes that setting the start_date\s tz will merely trigger conversion of the date using the timezone but will not change the whole dag's timezone. 

Please be more careful when reading the docs.
