### ISSUE TITLE
Split job_heartbeat_sec parameter into different parameter per job type

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#30908]
### Body

Currently the https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#job-heartbeat-sec parameter is set in `scheduler` section but it controls expecated heartbeat time for all job types - including local_task_job, triggerer and standalone dag file processor.

We should split it per job type and allow to configure it separately by our users.

This should allow to easier way to manage heartbeat expecations in cases like https://github.com/apache/airflow/issues/30884 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
solved by https://github.com/apache/airflow/pull/32313 ?

**Comment by potiuk** [comment]
Yes.
