### ISSUE TITLE
Tableau - Authentication deprecated

### ISSUE THREAD

**Issue by Michae94** [apache/airflow#30940]
### What do you see as an issue?

Currently, in the Airflow documentation of Tableau connector, it is marked as deprecated to use a token to authenticate to Tableau.      
https://airflow.apache.org/docs/apache-airflow-providers-tableau/stable/connections/tableau.html#authenticating-to-tableau

However, since MFA enforcement release (27th April 2023), it is now impossible to use a user/password to authenticate as a service account.

### Solving the problem

Put the deprecated (even remove?) flag on the user/password authentication, and mark the access token authentication as strongly recommended.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Thanks. If you would like to do it - feel free to open PR, otherwise I marked it as good first issue for someone who would like to pick it up.

**Comment by Michae94** [comment]
Hey @potiuk , thanks for the answer. I don't think I will have the time in the following days to open the PR so thanks for the flag `good_first_issue` 👍

**Comment by eladkal** [comment]
This is duplicate of https://github.com/apache/airflow/issues/25904

**Comment by Michae94** [comment]
Oops, my bad. Closing it then
