### ISSUE TITLE
XCOMs not working with PythonVirtualenvOperator

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#30967]
### Apache Airflow version

2.5.3

### What happened

XCOMs not working with PythonVirtualenvOperator

### How to reproduce

Create a DAG with PythonVirtualenvOperator tasks, and attempt to use XCOMS bettween the tasks.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Xcoms and passing context will only work if you have the same airflow version and the same Python version as in the original Airflow environment. See the docstring of the operator.

**Comment by pedro-cf** [comment]
> Xcoms and passing context will only work if you have the same airflow version installed and the same Python version used in the venv as in the original Airflow environment. See the docstring of the operator.

would it be possible to make this a feature request?

In my case I was using a ShortCircuitOperator followed by a PythonVirtualenvOperator...

**Comment by potiuk** [comment]
No. There is no way to make it works without fulfilling those prerequisites in general way. You need to serialize the data to send (hence same Python) and use Airflow code to pull or Push Xcom (hence Xcom requirement) - but you have other ways how you can pass data between tasks - you can write them to external storage and read them from there for example. You can also pass the data via string args and return string values from Python Virtualenv Operator (see the docstring)
