### ISSUE TITLE
Incorrect logic when reading from local log files

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#30997]
### Apache Airflow version

2.6.0

### What happened

The logic of this line https://github.com/apache/airflow/blob/ab54c63940a99646df974d4bcf2e37415e277e69/airflow/utils/log/file_task_handler.py#L323
is incorrect.

We are trying to achieve:
* `when finished, if we don't have remote logs, then read from local`

But the this line does the opposite:
* `when not not unfinished (not finished), if we don't have remote logs, then read from local`

Also, the "triple negation logic" is really hard to read :joy: It should be

```python
if ti.state in State.finished and not remote_logs:
```

### How to reproduce

Run 2.6.0 with local logs

### Operating System

Irrelevant 

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc: @dstandish -> if that's correct assesment, then likely we need 2.6.1 quickly (the triple not logic makes it hard to confirm it 🤣

**Comment by zachliu** [comment]
my bad, the logic is correct :sweat_smile: 

| remote_logs     | task state | triple not logic final output |
|-----------------|------------|-------------------------------|
| no remote logs  | unfinished | True (read local)             |
| has remote logs | finished   | False (don't read local)      |
| no remote logs  | finished   | True (read local)             |
| has remote logs | unfinished | True (read local)             |

but i'll keep my PR open since the triple not logic is hard to understand

**Comment by potiuk** [comment]
> @potiuk I thought the comment was self-explanatory. Here is more context:

Not without explaining your configuration - commenting on a closed PR without providing your context and configuration does not help. Airflow logging is super configurable and we have no idea to read inside your head and find out which configuration you use when you make such comment.

Can yo please comment inthe #31059 and explain the logging configuration you have (pretty please). That will help to investigate the root cause.
