### ISSUE TITLE
Using a period for the DAG name (dag_id) prevents scheduling

### ISSUE THREAD

**Issue by fdion** [apache/airflow#310]
The dag gets registered, but the namespace is mismatched and the DAG never gets scheduled and shows no status.

As an example:

dag = DAG(dag_id='second_dag.py', default_args=args)

Will not get scheduled, while dag = DAG(dag_id='second_dag', default_args=args) will.

**Comment by toryhaavik** [comment]
I think this is also the reason why we see the status bubbles disappearing from some of our DAGs on the frontpage.  Chrome's console tells me d3 says `'svg#dag.with.period' is not a valid selector`

![image](https://cloud.githubusercontent.com/assets/4268290/10678917/49861744-78e3-11e5-8a7a-dc91e08edec2.png)

**Comment by artwr** [comment]
I think this was fixed in https://github.com/airbnb/airflow/pull/468

**Comment by toryhaavik** [comment]
ah, i think you're right! i'll look for it in the next release. thanks!
