### ISSUE TITLE
Documentation building is missing some docs in output

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#31017]
### Apache Airflow version

main (development)

### What happened

Docs are not building correctly both in main and the recently released 2.6.0. Some API references are missing. For example this link http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/_api/airflow/models/baseoperator/index.html no longer works. Same in 2.6.0 https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/baseoperator/index.html but works in 2.5.3: https://airflow.apache.org/docs/apache-airflow/2.5.3/_api/airflow/models/baseoperator/index.html

### What you think should happen instead

All API references should work

### How to reproduce

Run docs build command and check the folders in `docs/_build/apache-airflow/stable/_api/airflow` and notice that a lot of folders are missing.

### Operating System

MacOs M1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is resolved now via #31021
