### ISSUE TITLE
Airflow DockerOperator Passing Multiple command 

### ISSUE THREAD

**Issue by fafa92** [apache/airflow#31046]
### Apache Airflow version

2.6.0

### What happened

I'm trying to pass multiple commands via the Dockeroperator command argument like the below:

```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.providers.docker.operators.docker import DockerOperator
from docker.types import Mount

dag = DAG('demo_dag', description='Hello World DAG',
          
          start_date=datetime(2017, 3, 20), catchup=False)
task_1 = DockerOperator(
    dag=dag,
    task_id='docker_task',
    image='python',
    auto_remove=False,
    docker_url='unix://var/run/docker.sock',
     command=['pip install numpy' ,'pip install pandas','python3 code.py'],
   cpus=2.0,
    network_mode="bridge"
)
task_1
```

But I realized based on the https://github.com/apache/airflow/issues/9518 issue it doesn't let me do that. I changed part of the source code that was parsing command input on this file:
https://github.com/apache/airflow/blob/main/airflow/providers/docker/operators/docker.py

From:
```
 def format_command(command: list[str] | str | None) -> list[str] | str | None:
        """
        Retrieve command(s). if command string starts with [, it returns the command list)

        :param command: Docker command or entrypoint

        :return: the command (or commands)
        """
        if isinstance(command, str) and command.strip().find("[") == 0:
            command = ast.literal_eval(command)
        return command
```

to this:

```
def format_command(command: list[str] | str | None) -> list[str] | str | None:
        """
        Retrieve command(s). if command string starts with [, it returns the command list)

        :param command: Docker command or entrypoint

        :return: the command (or commands)
        """
        if isinstance(command, str) and command.strip().find("[") == 0:
            command = ' && '.join(ast.literal_eval(command))
            print(' new command', command)
        return command
```

Unfortunately, I cannot see any change in airflow output, I already restarted both the webserver and scheduler, but neither cannot find the printed output command anywhere or a change in the parsing command when it's submitted scheduler. 

Can this issue be fixed? I already appreciate any help in advance. 

### How to reproduce

this is my env version:

Python 3.9
airflow 2.5.1

### Operating System

Ubuntu 18.04

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
I don't think is an Airflow issue. I believe it would be similar to how commands are accepted by Docker.

Can you try specifying the command parameter as below:
```
command=["sh", "-c", "pip install numpy && pip install pandas && python3 code.py"],
```

Additional reference: https://www.baeldung.com/ops/docker-run-multiple-commands#using-cmdentrypoint-in-the-dockerfile

Also, in general, if you have multiple commands to run, I would suggest converting it to a shell script and specifying to execute that shell script in the command for the DockerOperator.

**Comment by potiuk** [comment]
> I don't think is an Airflow issue. I believe it would be similar to how commands are accepted by Docker.
> 
> Can you try specifying the command parameter as below:
> 
> ```
> command=["sh", "-c", "pip install numpy && pip install pandas && python3 code.py"],
> ```
> 
> Additional reference: https://www.baeldung.com/ops/docker-run-multiple-commands#using-cmdentrypoint-in-the-dockerfile
> 
> Also, in general, if you have multiple commands to run, I would suggest converting it to a shell script and specifying to execute that shell script in the command for the DockerOperator.

Correct. None of the standard Python nor docker API implement such a behaviour especially that there are multiple ways you could interpret such commands - should they be run all when some of them fail? should they stop when the first is run ? Should they be run in parallel? 

This is not something we wa are going to change. Wrapping your commands in a script (might be bash or python, or whatever) is the right approach.

**Comment by fafa92** [comment]
Thank you @pankajkoti and @potiuk for your response. That worked for me. The reason that I wanted to do it this way and not with the shell script approach was to have those commands to be executed at the running time for each docker and not have shell script commands attached/copied to the docker image at its build time.

**Comment by fafa92** [comment]
Thank you @pankajkoti and @potiuk for your response. That worked for me. The reason that I wanted to do it this way and not with the shell script approach was to have those commands to be executed at the running time for each docker and not have shell script commands attached/copied to the docker image at its build time.
