### ISSUE TITLE
ShieldedInstanceConfig not being accepted by Dataproc operators ClusterGenerator 

### ISSUE THREAD

**Issue by shivannakarthik** [apache/airflow#31058]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

While creating dataproc cluster using Dataproc Cluster Create Operator, I am unable to to toggle ShieldedInstanceConfig related properties. It works when I create using gcloud command or direct Dataproc APIs though. 

This has been discussed here -> https://github.com/apache/airflow/issues/28023

I believe the operator must support this property. Could this be a potential PR?

### How to reproduce

While passing the cluster configs, pass the gce_cluster_config as follows to create the cluster using Dataproc Cluster Create Operator.
      "gce_cluster_config": {
          "metadata": {
              "enable-pepperdata": "false",
              "ha_flag": "no"
          },
	  "shielded_instance_config": {
            "enable_secure_boot": 1,
            "enable_vtpm": 1,
            "enable_integrity_monitoring": 1
	}
      }

### Operating System

debian11

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
You could use the `gcloud` command or direct `Dataproc` APIs to create the cluster with the `ShieldedInstanceConfig` properties until this feature is added to the Airflow operator.

Here is how you can create a cluster with `ShieldedInstanceConfig` using the `gcloud` command:

    gcloud dataproc clusters create my-cluster \
        --region=us-central1 \
        --subnet=default \
        --zone=us-central1-a \
        --master-machine-type=n1-standard-2 \
        --worker-machine-type=n1-standard-2 \
        --num-workers=2 \
        --image-version=1.5-debian10 \
        --project=my-project \
        --shielded-instance-config enable-secure-boot enable-vtpm enable-integrity-monitoring


And here is how you can create a cluster with `ShieldedInstanceConfig` using the `Dataproc` APIs:

    from google.cloud import dataproc_v1 as dataproc
    from google.protobuf import json_format
    
    project_id = 'my-project'
    region = 'us-central1'
    cluster_name = 'my-cluster'
    
    client = dataproc.ClusterControllerClient()
    
    cluster = {
        'project_id': project_id,
        'cluster_name': cluster_name,
        'config': {
            'gce_cluster_config': {
                'metadata': {
                    'enable-pepperdata': 'false',
                    'ha_flag': 'no'
                },
                'shielded_instance_config': {
                    'enable_secure_boot': True,
                    'enable_vtpm': True,
                    'enable_integrity_monitoring': True
                }
            }
        }
    }
    
    op = client.create_cluster(
        request={'project_id': project_id, 'region': region, 'cluster': cluster}
    )
    
    print(json_format.MessageToDict(op))

**Comment by shivannakarthik** [comment]
Thanks Rohan. Yes, I am able to create it using gcloud and Dataproc API. Will raise a PR.

**Comment by rohan472000** [comment]
If my suggestion worked for you then kindly close this issue.

**Comment by shivannakarthik** [comment]
It does not address the issue, but provides a workaround. Ideally I should be able to create the cluster using the airlfow datapro cluster create operator passing the shielded_instance_config properties

**Comment by shivannakarthik** [comment]
Working on it

**Comment by sai3563** [comment]
@eladkal Please assign this to me.

**Comment by sai3563** [comment]
@eladkal @shivannakarthik It seems no modifications in the `DataprocCreateClusterOperator` are needed. While testing with the latest dev branch i.e. `2.10.0.dev0`, I was able to get `shielded_instance_config` working using the operator. I tried it with both True and False values for the parameters and confirmed it to be working from GCP Console.

Here is the full code I used

```
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.google.cloud.operators.dataproc import DataprocCreateClusterOperator

# Constants
PROJECT_ID = 'my-project'
REGION = 'asia-south1'
CLUSTER_NAME = 'testing-cluster'
ZONE = 'asia-south1-a'

# Default DAG arguments
default_args = {
    'start_date': datetime.now() - timedelta(days=1)
}

# Define the DAG
dag = DAG(
    'dataproc_create_cluster_dag',
    default_args=default_args,
    description='A DAG to create a Dataproc cluster',
    schedule=None,
    catchup=False
)

# Dataproc cluster configuration
cluster_config = {
    "gce_cluster_config": {
        "zone_uri": f"https://www.googleapis.com/compute/v1/projects/{PROJECT_ID}/zones/{ZONE}",
        "metadata": {
            "enable-pepperdata": "false",
            "ha_flag": "no"
        },
        "shielded_instance_config": {
            "enable_secure_boot": True,
            "enable_vtpm": True,
            "enable_integrity_monitoring": True
        }
    }
}

# Create Dataproc cluster task
create_cluster = DataprocCreateClusterOperator(
    task_id='create_dataproc_cluster',
    project_id=PROJECT_ID,
    cluster_name=CLUSTER_NAME,
    cluster_config=cluster_config,
    region=REGION,
    dag=dag
)

# Define task sequence
create_cluster
```

@eladkal I believe this issue can be closed for the moment.
