### ISSUE TITLE
[BUG] apache.hive extra is referencing incorrect provider name

### ISSUE THREAD

**Issue by davidshur** [apache/airflow#31067]
### Apache Airflow version

2.6.0

### What happened

When creating docker image with airflow 2.6.0 I receive the error: `ERROR: No matching distribution found for apache-airflow-providers-hive>=5.1.0; extra == "apache.hive"`

After which, I see that the package name should be `apache-airflow-providers-apache-hive` and not `apache-airflow-providers-hive`.

### What you think should happen instead

We should change this line to say `apache-airflow-providers-apache-hive` and not `apache-airflow-providers-hive`, this will reference a provider which exists.

### How to reproduce

Build image for airflow 2.6.0 with the dependency `apache.hive`. Such as `pip3 install apache-airflow[apache.hive]==2.6.0 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.6.0/constraints-3.8.txt`.

### Operating System

ubuntu:22.04

### Versions of Apache Airflow Providers

Image does not build.

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by davidshur** [comment]
https://github.com/apache/airflow/blob/4e545c6e54712eedb6ca9cbb8333393ae3f6cba2/setup.py#L815

**Comment by davidshur** [comment]
https://github.com/apache/airflow/pull/31068 linked PR.

**Comment by eladkal** [comment]
Thanks for noticing.
BTW @davidshur since you are using this provider.
The Hive provider uses [Pyhive](https://github.com/dropbox/PyHive) which is discontinued. There seems to be no other Python SDK for Hive that I can find. Do you know of alternatives?
