### ISSUE TITLE
Changing configuration as part of the custom airflow docker image

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#31084]
### What do you see as an issue?

https://airflow.apache.org/docs/docker-stack/build.html
This docs doesn't share information on how we can edit the airflow.cfg file for the airflow installed via docker. Adding this to docs, would give better idea about editing the configuration file

### Solving the problem

Add more details in build your docker image for editing the airflow.cfg file

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
I have added it as bug before taking up solving the issue as i want to make sure that if this issue is a valid one.

**Comment by potiuk** [comment]
I don't think we need/should do it. Maybe better is to explain that if you want to add your configuration you should extend the image with configuration variables instead:

```
FROM apache/airflow:.....
ENV AIRFLOW__CORE__LOAD_EXAMPLES=True
```

This is far simpler and better way of changing default configuration in custom image than trying to modify the .cfg file on the flight

**Comment by Bowrna** [comment]
yes thanks for sharing this part @potiuk i will make changes to the documentation with the suggested env configuration.

**Comment by Bowrna** [comment]
can expect delay at my side ( for a week) as i am relocating home. I will resume to work on this afterwards

**Comment by Bowrna** [comment]
i am taking up this work today and it can be assigned to me. i will close it in two days
