### ISSUE TITLE
Can't cancel EMR Serverless task

### ISSUE THREAD

**Issue by dacort** [apache/airflow#31099]
### Apache Airflow version

2.6.0

### What happened

When marking an EMR Serverless job as failed, the job continues to run.

### What you think should happen instead

The job should be cancelled. Looking at the [EMR Serverless Operator](https://github.com/apache/airflow/blob/a6be96d92828a86e982b53646a9e2eeca00a5463/airflow/providers/amazon/aws/operators/emr.py#L939), I don't see an `on_kill` method, so assuming we just need to add that. 

I'm not sure how to handle the `EmrServerlessCreateApplicationOperator` operator, though - if the workflow has a corresponding `EmrServerlessDeleteApplicationOperator`, we'd probably want to delete the application if the job is cancelled.

### How to reproduce

- Start an EMR Serverless DAG
- Mark the job as failed in the Airflow UI
- See that the EMR Serverless job continues to run

### Operating System

n/a

### Versions of Apache Airflow Providers

`apache-airflow-providers-amazon==8.0.0`

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
Thank you for creating the issue  @dacort , would you like to create a PR for the `on_kill` method implementation?

**Comment by dacort** [comment]
@phanikumv Yep, happy to! Just getting reacquainted with it airflow dev environment. 😁

**Comment by phanikumv** [comment]
Assigned it to you

**Comment by eladkal** [comment]
> When marking an EMR Serverless job as failed, the job continues to run.

This is expected. Marking a task as failed in the UI just change the status of the task in the DB. It does not invoke on_kill function.

**Comment by dacort** [comment]
> It does not invoke on_kill function.

I was wondering if that was the case. When does it get invoked?

**Comment by potiuk** [comment]
>> This is expected. Marking a task as failed in the UI just change the status of the task in the DB. It does not invoke on_kill function.

> I was wondering if that was the case. When does it get invoked?

I think @eladkal you mistook it with something else (some callbacks or maybe race conditions ?). When task is running and you clear it from the UI, it will be marked as kiled in the DB and when the task runs a heartbeat, as far as I know it checks if the state is set to "FAILED" and generally it will run the "on_kill" method when exiting. So I think indeed it is a bug.

**Comment by phanikumv** [comment]
yes we need to add on_kill method on the operator class to kill stale processes on target system. For example we did the same in Trino Operator when the task is cleared from UI and the query wasnt getting killed in Trino DB
