### ISSUE TITLE
Add support for standard SQL in `BigQueryGetDataOperator`

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#31109]
### Description

Currently, the BigQueryGetDataOperator always utilizes legacy SQL when submitting jobs (set as the default by the BQ API). This approach may cause problems when using standard SQL features, such as names for projects, datasets, or tables that include hyphens (which is very common nowadays). We would like to make it configurable, so users can set a flag in the operator to enable the use of standard SQL instead.

### Use case/motivation

When implementing #30887 to address #24460, I encountered some unusual errors, which were later determined to be related to the usage of hyphens in the GCP project ID name.

### Related issues

- #24460
- #28522 (PR) adds this parameter to `BigQueryCheckOperator`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Thanks for reporting, just assigned you :)

**Comment by shahar1** [comment]
> Thanks for reporting, just assigned you :)

No problem :)
I've already solved it in #30887, but I was asked to move the related changes to a separate PR (for clarity).
I am waiting for the former to be merged, and then I'll create a new PR.
