### ISSUE TITLE
Errors in callback functions are hidden

### ISSUE THREAD

**Issue by ying-w** [apache/airflow#31112]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

The function I call for `on_success_callback` has an error (parameterized incorrectly). This error does not show up in airflow logs.

### What you think should happen instead

Errors in callbacks should propagate to airflow logs or there should be an alternative path for debugging [in documentation](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html)

### How to reproduce

A dag that looks something like this

```py

def send_email(context, job_status):
    # send email here parameterized by context  

def dag_success(context):
    send_email(context, success=True)  # this should fail

def dag_fail(context):
    send_email(context, success=False)  # this should fail

@dag(
    schedule=None,
    start_date=pendulum.datetime(2023, 1, 1),
    on_success_callback=dag_success,
    on_failure_callback=dag_fail,
    tags=["example"],
)
def foo():
    BigQueryCheckOperator(
      ...
    )

foo_run = foo()
```

I expect the following function to throw an error because of mismatch of arguments: `send_email()` expects `job_status=` while i'm passing in `success=`.

### Operating System

OS X 13.2.1

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.11.0

### Deployment

Astronomer

### Deployment details

Airflow 2.5.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Due to the nature of the callbacks they are executed after the tasks are completed, so errors in the callbacks are showing up in the scheduler logs. not task logs.

> Errors in callbacks should propagate to airflow logs or there should be an alternative path for debugging [in documentation](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html)

100% agree. I assigned you. It's easy to update the docs, just click "Suggest a change on this page" button at the bottom of the page and PR should be opened for you. Easy way to become a contributor.

**Comment by ying-w** [comment]
Is there a way to see scheduler logs in UI?

**Comment by potiuk** [comment]
> Is there a way to see scheduler logs in UI?

NO. But you can configure logging via https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/logging-tasks.html#advanced-configuration and configure your logging as you want.

**Comment by potiuk** [comment]
Note that airflow log is **not** to monitor airflow components - the logs there are to show task logs only, and callbacks are considered part of the "application" not part of the task.

**Comment by ephraimbuddy** [comment]
Hi @ying-w , are you aware of this log file for dag level callbacks: https://github.com/apache/airflow/blob/75f5f53ed0aa8df516c9d861153cab4f73318317/airflow/models/dag.py#L1328-L1329

**Comment by ying-w** [comment]
resolved by https://github.com/apache/airflow/pull/31116
