### ISSUE TITLE
Pass custom schedulingPriorityOverride in aws BatchOperator

### ISSUE THREAD

**Issue by 0x26res** [apache/airflow#31148]
### Description

The aws [BatchOperator](https://github.com/apache/airflow/blob/521dae534dd0b906e4dd9a7446c6bec3f9022ac3/airflow/providers/amazon/aws/operators/batch.py#L47) uses boto3 batch [submit_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch/client/submit_job.html).

At the moment the constructor of BatchOperator allows you to customise some aspect of the batch job (eg: job_definition, job_queue etc). But this doesn't cover all the options that can be passed to boto3 batch submit_job. 

In particular I'd like to be able to pass the parameter `schedulingPriorityOverride`

### Use case/motivation

I submit a lot of array jobs to aws batch using airflow. As there can only be a limited number of job running at the same time, aws schedule jobs on a mix of FIFO logic and using the `schedulingPriorityOverride`. 

As I have jobs with higher priority than other, I'd like to be able to customise that argument for my high priority jobs. So they don't get blocked until the other lower priority jobs are done.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
I can see `scheduling_priority_override` did you try to use it? https://github.com/apache/airflow/blob/521dae534dd0b906e4dd9a7446c6bec3f9022ac3/airflow/providers/amazon/aws/operators/batch.py#L135
