### ISSUE TITLE
Old, unused tags cannot be removed easily

### ISSUE THREAD

**Issue by arjunanan6** [apache/airflow#31184]
### What do you see as an issue?

We recently removed a bunch of our old dags. However, this left behind the tags that used within those DAGs behind. Unfortunately, I cannot find a simple way to clean up the tags besides directly going into the metadatabase and deleting it from there. 

The ```airflow db clean``` CLI command also does not help in my case, as it would also remove the DAG itself if run with, for example:
```airflow db clean -t dag --clean-beforetimestamp '2023-05-10'``` 

Also, dag_tag is not a valid table selection for this command. 

Another strange issue is that the tags are also displayed in a non-alphabetical order. Example:
![image](https://github.com/apache/airflow/assets/102953522/a43194a6-90f3-40dd-887e-fdfad043f200)

I could not reproduce this issue with the non-alphabetical list order in a local dev environment at least. Is there a smarter way to clean up the tags and get it to show in a right order? 

I am willing to submit a PR if I can get some guidance :)

### Solving the problem

Probably with the introduction of a new table for the clean command such as  ```airflow db clean --tables dag_tag```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
If want to remove the tag then I think you will have to remove it from your DAG file

**Comment by arjunanan6** [comment]
@pankajastro The thing is that the DAGs using these old tags are no longer there. The tags have not gone away for some strange reason. Another odd thing is the listing in non-alphabetical order which I cannot reproduce locally.

**Comment by pankajastro** [comment]
what airflow version you are uing?

**Comment by arjunanan6** [comment]
We're on 2.6.0 at the moment.

**Comment by pankajastro** [comment]
that's weird.

**Comment by arjunanan6** [comment]
Yep. I was thinking of trying out purging the entire dag_tag table, and seeing if it will get properly listed once the dag bag is refreshed. Would that be a good idea?

**Comment by ephraimbuddy** [comment]
Solving this may require an extra table, an association table...I will take a look

**Comment by ephraimbuddy** [comment]
So the issue is that when you remove a DAG file, it's not deleted from DB, only removed from SerializedDagModel and deactivated in DagModel. The Tag will continue to show since the dag is not really deleted. The DAG 

One thing you can do is use `airflow db clean` command with time in the past that includes the time you removed the files. 
OR
Use `airflow dags delete dag_id`

**Comment by arjunanan6** [comment]
I see. That makes sense. However, would `airflow db clean` not wipe a bit more than required? It wiped out all DAGs the last time I tried it out - cannot remember the exact parameters unfortunately.

Would it make sense to purge the `dag_tag `table manually? My assumption is that when the DAGs are serialized again, it should pick up only stuff that exists.

**Comment by ephraimbuddy** [comment]
Let me know if that doesn't solve it

**Comment by ephraimbuddy** [comment]
> I see. That makes sense. However, would `airflow db clean` not wipe a bit more than required? It wiped out all DAGs the last time I tried it out - cannot remember the exact parameters unfortunately.

Yes. It will wipe everything 

> Would it make sense to purge the `dag_tag `table manually? My assumption is that when the DAGs are serialized again, it should pick up only stuff that exists.

I don’t think so since it’s a child to DagModel. 

If you know the DAG ID, you can use `airflow dags delete DAG_ID`

**Comment by arjunanan6** [comment]
@ephraimbuddy I have some updates on this. I think I might have misled you here to begin with because the DAG(s) aren't deleted. Just some tags are deleted.

On one of our dev environments, we have just about 10 DAGs, and the dag_tag table had 18 rows. I took a backup of it and truncated the dag_tag table, which was almost instantly refilled (I guess logs are DEBUG level on that, so I saw nothing). This did not initially fix the sorting problem, but after a couple of truncates, things got weird, and all the tags were sorted as expected, and the row count in the dag_tag table was now just 15, so 3 rows were removed in all. We also added a new DAG in there with a tag "arjun", which also got listed first - so all sorted on that environment.

Unfortunately, on our other environment with about 160 DAGs, there is no difference after attempting the above process barring the fact that the row count is reduced. We started off with 431 tags in the dag_tag table, now reduced to 307 after a truncate and automatic "refill". I've attempted to truncate the table a couple of times, and after a few minutes, it has the 307 rows - which look correct. The only problem remaining is that the tags are still not sorted in the Filter DAGs by tag.

**Comment by ephraimbuddy** [comment]
I didn't investigate the sorting. Can you create a different issue if the sorting is the issue. As for removing the tags, I don't think it'll be easy to remove them since they are attached to some dags. If I understand correctly, you can't create a Tag without creating a Dag.

**Comment by arjunanan6** [comment]
Yep, will do. I was hoping the cleanup of non-existent tags would take care of sorting, but no. If someone comes in here with a similar issue: truncating the dag_tag table is okay, the tags get resynced.

**Comment by sbrugman** [comment]
This behaviour is quite annoying in a flow where DAGs are tagged with git branch names. Any chances that refreshing tags can be put on the backlog for future versions?

**Comment by potiuk** [comment]
there is no backlog. You can create PR and add it yourself and become one of the contrbutors (this is fastest way and most certain). The second best is you create an issue and describe it nicely as feature request, we mark it as "good first issue" and hopefully someone will pick it and implement.  You could also sponsor someone to implement it if you want.

This is how OSS project contributions work.

**Comment by ITJamie** [comment]
an idea for this would be to have an additional column on the dag_tag table. 
a last_seen date field.

when the scheduler / importer runs it could update the dag_tag table with new dates.
then delete tags not seen in x days?
