### ISSUE TITLE
Problems after redesign grid view

### ISSUE THREAD

**Issue by JoepvandenHoven-Bluemine** [apache/airflow#31186]
### Apache Airflow version

2.6.0

### What happened

The changes in #30373 have had some unintended consequences. 

- The clear task button can now go of screen if the dag / task name is long enough. This is rather unfortunate since it is by far the most important button to fix issues (hence the reason it is taking up a lot of real estate)
- Above issue is exacerbated by the fact that the task name can also push the grid off screen as well. I now have dags where I can see grid or the clear state button, but not both.
- Downstream and Recursive don't seem to be selected default anymore for the clear task button. For some reason recursive is only selected for the latest task (maybe this was already the case?).

The first two are an annoyance, the last one is preventing us from updating to 2.6.0

### What you think should happen instead

- Downstream should be selected by default again. (and possibly Recursive)
- The clear task button should *always* be visible, no matter how implausibly small the viewport is.
- Ideally long taks names should no longer hide the grid.

### How to reproduce

To reproduce just make a dag with a long name with some tasks with long names and open the grid view on a small screen.

### Operating System

unix

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
Can I take this up @bbovenzi?

**Comment by bbovenzi** [comment]
> Can I take this up @bbovenzi?

Go for it! Sounds like we should make sure the actions wrap and are always visible.
