### ISSUE TITLE
Double execution of taskinstance, spark-submit twice.

### ISSUE THREAD

**Issue by ORuteMa** [apache/airflow#31205]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version: 2.4.2
In my organization, I need to run an SSHOperator to execute a script that triggers a spark-submit task. I encountered a situation where I had to rerun a specific execution, so I cleared the state of the task. However, I noticed that there were two distinct applications running on YARN when there should have been only one. This occurred three times in total.

![image](https://github.com/apache/airflow/assets/30034544/8bc68881-1ffe-4785-ad59-c9c9e6875f09)

From the log, I observed that each line is being logged twice. I'm curious to know if there is any connection or reason behind this duplication. I have `remote_logging` to be true.

![image](https://github.com/apache/airflow/assets/30034544/e1e62b64-e69c-472e-8d7f-e2b1a57d01e8)

### How to reproduce

Clear the state of Task.
But I can't produce it several hours later.

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ORuteMa** [comment]
I run Airflow on ECS with celery exectuor, use redis sentinel as the broker.

**Comment by xlanor** [comment]
@ORuteMa hey, out of curiosity, how did you resolve this issue?

**Comment by ORuteMa** [comment]
> @ORuteMa hey, out of curiosity, how did you resolve this issue?

This is because we were using MySQL version 5.7, and the issue was resolved after switching to version 8.0. As for the reason for duplicate logging, it was due to our usage of the remote_logging feature. This problem seems to exist in version 2.4.2, but in subsequent testing with version 2.5.3, the logs were normal without duplication.

**Comment by xlanor** [comment]
@ORuteMa That's very helpful - I will send this over to another team, we've been seeing this issue in 2.4.2 pop up as well and were curious as to what was causing it.

Just curious, were you seeing duplicate task execution? We're seeing tasks get picked up twice by different airflow workers.

**Comment by ORuteMa** [comment]
> @ORuteMa That's very helpful - I will send this over to another team, we've been seeing this issue in 2.4.2 pop up as well and were curious as to what was causing it.
> 
> Just curious, were you seeing duplicate task execution? We're seeing tasks get picked up twice by different airflow workers.

Yes, I am certain that the task was executed repeatedly. Please take a look at the image below.
<img width="1061" alt="image" src="https://github.com/apache/airflow/assets/30034544/dd17c940-2feb-4402-b859-6db0ed00ab02">

It can be observed that attempt 44 started before attempt 43 had finished. This clearly indicates that the Scheduler, while picking up runnable task instances, had at least two schedulers selecting the same task instance and distributing it concurrently, leading to a concurrency issue.

**Comment by xlanor** [comment]
> > @ORuteMa That's very helpful - I will send this over to another team, we've been seeing this issue in 2.4.2 pop up as well and were curious as to what was causing it.
> 
> > 
> 
> > Just curious, were you seeing duplicate task execution? We're seeing tasks get picked up twice by different airflow workers.
> 
> 
> 
> Yes, I am certain that the task was executed repeatedly. Please take a look at the image below.
> 
> <img width="1061" alt="image" src="https://github.com/apache/airflow/assets/30034544/dd17c940-2feb-4402-b859-6db0ed00ab02">
> 
> 
> 
> It can be observed that attempt 44 started before attempt 43 had finished. This clearly indicates that the Scheduler, while picking up runnable task instances, had at least two schedulers selecting the same task instance and distributing it concurrently, leading to a concurrency issue.

Thanks a lot! This helped us with our issue - we're seeing this as well in 2.4.2 and we couldnt replicate it reliably either.
