### ISSUE TITLE
The @task.branch inside the dags.html seems to be incorrect

### ISSUE THREAD

**Issue by yenchenLiu** [apache/airflow#31236]
### What do you see as an issue?

In the documentation page [https://airflow.apache.org/docs/apache-airflow/2.6.0/core-concepts/dags.html#branching)](https://airflow.apache.org/docs/apache-airflow/2.6.0/core-concepts/dags.html#branching), there is an incorrect usage of the @task.branch decorator.

``` python
@task.branch(task_id="branch_task")
def branch_func(ti):
    xcom_value = int(ti.xcom_pull(task_ids="start_task"))
    if xcom_value >= 5:
        return "continue_task"
    elif xcom_value >= 3:
        return "stop_task"
    else:
        return None


branch_op = branch_func()
```

This code snippet is incorrect as it attempts to initialize branch_func without providing the required parameter.

### Solving the problem

The correct version maybe is like that

```python
 def branch_func(**kwargs):
    ti: TaskInstance = kwargs["ti"]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Both notations are equivalent and supposed to work out of the box. (Accessing a specific keyword arg from the context, or collect the entire  context in **kwargs).

Do you see an error when running the first version ?

**Comment by pierrejeambrun** [comment]
True, here is the relevant part of the doc here: 
https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html#accessing-context-variables-in-decorated-tasks
