### ISSUE TITLE
 error initializing database 

### ISSUE THREAD

**Issue by zhiflow** [apache/airflow#31248]
### Apache Airflow version

2.6.0

### What happened

When initializing the database, an error was reported with no default value for the datetime column
![图片](https://github.com/apache/airflow/assets/46391660/6d1f3b96-3ba7-4bee-b81e-65b1ddf316a1)

![图片](https://github.com/apache/airflow/assets/46391660/d963ece9-ae0f-4fe4-93b6-cf09ded45c6d)

 Suspected that the default value is not valid 
```
updated_at = Column(UtcDateTime, default=timezone.utcnow, onupdate=timezone.utcnow, nullable=False)
```
 I think it would be better to use the following methods 
updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

### How to reproduce

airflow db init

### Operating System

linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Since this is for mysql this might be related : https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at

**Comment by phanikumv** [comment]
@zhiflow Does this issue occur only for `mysql` backend  or any other database as well?
