### ISSUE TITLE
Migrate elasticsearch client to 8.* (or latest 7.*)

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#31256]
### Body

The eleasticsearch version we use is old (from 2021). It is eleasticsearch 7.* and since we are using elasticsearch-dsl, we cannot used elasticsearch 8 currently (first version of that was also released in 2021). 

We are currently limited to < 7.15.0 additionally to being limited to 7, because 7.15.0 breaks our tests as we found out when we released some of the dependencies as part of https://github.com/apache/airflow/pull/30067

We should migrate to a newer version of elasticsearch. There are two options:

1) Fix the tests and migrate to lates 7.* version - and bump to latest released 7* by fixing our tests (possible for short term).
2) Migreate to 8 version (better long term)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Owen-CH-Leung** [comment]
Since `elasticsearch-dsl` doesn't support elasticsearch 8, if we are to migrate to the official elasticsearch 8, does it mean we need to deprecate `elasticsearch-dsl` also ?

**Comment by potiuk** [comment]
If we do yes. But that also might be reason why we don't do it.

**Comment by Owen-CH-Leung** [comment]
Ok. Please assign this issue to me. I'll take some time to study the current usage of this package and propose whether to upgrade to 8.* or latest 7.*

**Comment by potiuk** [comment]
Done.

**Comment by Owen-CH-Leung** [comment]
I saw `elasticsearch_dsl` was only used in 3 files as follows (one usage in taskhandler & 2 in testing) : 

https://github.com/apache/airflow/blob/fc36d002fccaad65718f42994747600c14f10263/airflow/providers/elasticsearch/log/es_task_handler.py#L291
https://github.com/apache/airflow/blob/fc36d002fccaad65718f42994747600c14f10263/docker_tests/test_prod_image.py#L130
https://github.com/apache/airflow/blob/fc36d002fccaad65718f42994747600c14f10263/tests/providers/elasticsearch/log/test_es_task_handler.py#L344

Given the utilization of `elasticsearch_dsl` is fairly limited, I'll try to upgrade to `elasticsearch` 8.* and deprecate `elasticsearch_dsl`

**Comment by Owen-CH-Leung** [comment]
hmmmm - I just realize that we also use `elasticsearch-dbapi`, which requires `elasticsearch==7.13.4`

https://github.com/apache/airflow/blob/main/airflow/providers/elasticsearch/provider.yaml#L60
https://github.com/preset-io/elasticsearch-dbapi/blob/master/requirements.txt#L9

**Comment by Owen-CH-Leung** [comment]
Ok luckily this library wasn't widely adopted also...looks like we can deprecate it when upgrading to 8 

https://github.com/apache/airflow/blob/main/airflow/providers/elasticsearch/hooks/elasticsearch.py#L25

**Comment by Owen-CH-Leung** [comment]
I feel like if we are to upgrade to elasticsearch 8, we need to divide it into chunk of works (coz we will be deprecating 2 packages). Since `elasticsearch-dbapi` is used to construct the `ElasticsearchSQLHook`, we might first need to refactor it using the existing official `elasticsearch` library. Then we can go further to refactor the taskhandler that uses `elasticsearch_dsl` to use the existing `elasticsearch` library. Finally we can attempt to upgrade to 8, remove those 2 libraries, and fix the failing tests. What do you think ? @potiuk
