### ISSUE TITLE
Migrate Pagerduty provider to official SDK

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31251]
### Body

Pagerduty has official Python SDK :
https://github.com/PagerDuty/pdpyras

developer section of Pagerduty recommends using the official library
https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTg2-api-client-libraries

![Screenshot 2023-05-12 at 17 21 01](https://github.com/apache/airflow/assets/45845474/ca29b0d8-bac6-4123-9b11-cdcd2b8cdde5)

This task is about migrating `PagerdutyEventsHook` and `PagerdutyHook` to official SDK rather than using HTTP endpoints directly.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajkoti** [comment]
@utkarsharma2 ☝🏽

**Comment by utkarsharma2** [comment]
@eladkal Can you please assign this ticket to me?

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/31290
