### ISSUE TITLE
unable to specify location in arguments to CloudBuildRunBuildTriggerOperator

### ISSUE THREAD

**Issue by siddhsql** [apache/airflow#31272]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

airflow version 2.4.3

when we try to specify location in argument to CloudBuildRunBuildTriggerOperator 

code:

```
from airflow.providers.google.cloud.operators.cloud_build import (
    CloudBuildRunBuildTriggerOperator,
)

CloudBuildRunBuildTriggerOperator(
        task_id=task_id,
        project_id=PROJECT_ID,
        trigger_id=trigger_id,        
location=LOCATION,
        source={"project_id": PROJECT_ID, "repo_name": repo_url, "branch_name": "master"},
)
```

we get error:

```
Broken DAG: [/home/airflow/gcs/dags/xxx.py] Traceback (most recent call last):

  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults

    result = func(self, **kwargs, default_args=default_args)

  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 756, in __init__

    raise AirflowException(

airflow.exceptions.AirflowException: Invalid arguments were passed to CloudBuildRunBuildTriggerOperator (task_id: iacv-common). Invalid arguments were:

**kwargs: {'location': 'us-central1'}
```

### What you think should happen instead

the location should be honored

### How to reproduce

run the code above

### Operating System

Linux Debian

### Versions of Apache Airflow Providers

2.4.3

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Fixed in https://github.com/apache/airflow/pull/29937 - check in release notes of provider when it has been released and upgrade provider (or upgrade to latest simply).

**Comment by siddhsql** [comment]
on https://github.com/apache/airflow/releases a search for 29937 does not return anything. is this pending release?
