### ISSUE TITLE
airflow dags list-jobs missing state metavar and choices keyword arguments

### ISSUE THREAD

**Issue by jgarte** [apache/airflow#31303]
### What do you see as an issue?

The `--state` CLI flag on `airflow dags list-jobs` does not tell the user what arguments it can take.

https://github.com/apache/airflow/blob/1bd538be8c5b134643a6c5eddd06f70e6f0db2e7/airflow/cli/cli_config.py#L280

It probably needs some keyword args similar to the following:

```python
 metavar="(table, json, yaml, plain)",
 choices=("table", "json", "yaml", "plain"),
```

### Solving the problem

The problem can be solved by adding those keyword arguments so that the user gets a suggestion for what state arguments can be passed in.

### Anything else

Any suggestions on what can be a valid state would be much appreciated. Otherwise, I'll find some time to read through the code and/or docs and figure it out.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
@jgarte look #31308

**Comment by rohan472000** [comment]
@pankajastro as #31308 is merged so, you can close this issue.

**Comment by pankajastro** [comment]
> @pankajastro as https://github.com/apache/airflow/pull/31308 is merged so, you can close this issue. 

closed. But you can link your PR with an issue like `closes: #ISSUE_NUM` that would automatically close the issue when PR will get merged.
