### ISSUE TITLE
The `Next Run` column name and tooltip is misleading

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#31365]
### Description

> Expected date/time of the next DAG Run, or for dataset triggered DAGs, how many datasets have been updated since the last DAG Run

"Expected date/time of the next DAG Run" to me sounds like Run After.

Should the tooltip indicate something along the lines of "start interval of the next dagrun" or maybe the header Next Run is outdated? Something like "Next Data Interval"?

On the same vein, "Last Run" is equally as confusing. The header can be "Last Data Interval" in additional to a tool tip that describe it is the data interval start of the last dagrun.

### Use case/motivation

Users confused "Next Run" as when the next dagrun will be queued and ran and does not interpret it as the next dagrun's data interval start.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
+1 to this. This was raised by our internal users after Airflow upgrade. The Next Run was assumed by many as the date the execution should happen though it is only data interval start and many missed the hover over part thinking it's a plain button. We modified it to show `next_dagrun_create_after` as more users wanted to know the next time the dag will be executed than the data interval start.

**Comment by tirkarthi** [comment]
Prior discussion : 

https://github.com/apache/airflow/pull/17732
https://github.com/apache/airflow/issues/21493

**Comment by amoghrajesh** [comment]
@wolfier @hussein-awala @bbovenzi I would like to take this up if nobody is working actively towards it.
The consensus here is to re word the tooltip text, right?

**Comment by potiuk** [comment]
Looks like. Propose in PR and then it might be fine-tuned :)

**Comment by amoghrajesh** [comment]
@potiuk it got assigned to @wolfier. I dont think @wolfier is taking this issue up.

**Comment by Rafnel** [comment]
As of Airflow 2.6.3 the "Next Run" listed on the DAG page is still in the past. For example, I have a DAG that runs on the first of the month at 8PM. The next run is 2023-09-01, 20:00:00, but the DAG UI for "Next Run" show 2023-08-01, 20:00:00, which is the data_interval_start, and is in the past. Wouldn't it be more accurate for this UI component to display the data_interval_end, which is the actual datetime of the next run?

**Comment by calebAtIspot** [comment]
Agreed, UI is still confusing to a newcomer (speaking as a newcomer).
