### ISSUE TITLE
White screen when attempting to view task details in Grid view

### ISSUE THREAD

**Issue by charlie-firth-cko** [apache/airflow#31364]
### Apache Airflow version

2.6.1

### What happened

When attempting to view a task instance in the Grid view, the task details fan out displays for a moment before the page whites out completely. 
This error appears in the console log:
![image](https://github.com/apache/airflow/assets/90192887/0bc59ec1-b8d6-496a-8ba3-e4e1419fbbc4)

White page:
![image](https://github.com/apache/airflow/assets/90192887/dda4119e-902b-4ab0-a3d5-7928eec0568f)

This issue doesn't occur for Admin users, only for users with lower levels of privilege. However, we've tried granting "read" on all resources but the problem remains.

If the user goes via the "Graph" tab instead of "Grid", then full functionality is possible.

### How to reproduce

Our workflow that produces this is:
- RBAC with Okta Integration
- View DAG which user should have access to based on their Role
- View Grid
- Click on a task instance square
- Task details appears for a moment
- Error then appears in console which drops all UI elements inside grid view

### Operating System

ECS Linux Fargate

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-sqlite==3.3.2

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bmoon4** [comment]
Adding `can edit on DAGs, can edit on DAG Runs, can edit on Task Instances, can delete on Task Instances` to viewer role manually helped my case.
