### ISSUE TITLE
Facing issue with database migrations while installing the chart using ArgoCD

### ISSUE THREAD

**Issue by RohithkumarRavi** [apache/airflow#31394]
### Official Helm Chart version

1.9.0 (latest released)

### Apache Airflow version

2.5.0

### Kubernetes Version

1.25.9

### Helm Chart configuration

`
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: airflow
    namespace: dev
spec:
  project: default
  source:
    repoURL: https://github.com/apache/airflow.git
    targetRevision: main
    path: chart

    helm:
      values: |
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

`

### What happened

The above one is the ArgoCD Template which I am using to install airflow chart using ArgoCD. I have followed the same steps mentioned in the below docs to avoid data migration errors: 
[installing-the-chart-with-argo-cd-flux-rancher-or-terraform](https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform)

Even after adding the values, I'm still getting data migration errors.

### How to reproduce

Run ArgoCD on your cluster. Save the template in a .yaml file and run **kubectl apply -f file.yaml**

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
> Even after adding the values, I'm still getting data migration errors.

What are the data migration errors you are getting?

**Comment by RohithkumarRavi** [comment]
The above issue was resolved automatically after a sync in ArgoCD
