### ISSUE TITLE
Trigger UI Form Dropdowns with enums do not set default correct

### ISSUE THREAD

**Issue by jscheffl** [apache/airflow#31399]
### Apache Airflow version

2.6.1

### What happened

When playing around with the form features as interoduced in AIP-50 and using the select list option via `enum` I realized that the default value will not be correctly picked when the form is loaded. Instead the first value always will be pre-selected.

### What you think should happen instead

Default value should be respected

### How to reproduce

Modify the `airflow/example_dags/example_params_ui_tutorial.py:68` and change the default to some other value. Load the form and see that `value 1` is still displayed on form load.

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

not relevant

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

not relevant

### Anything else

Workaround: Make your default currently top of the list.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
@jens-scheffler-bosch FYI,you can open a PR without creating an issue if you know already how to fix it and you want to work on it ([doc](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#issue-reporting-and-resolution-process)):
> An unusual element of the Apache Airflow project is that you can open a PR to fix an issue or make an enhancement, without needing to open an issue first. This is intended to make it as easy as possible to contribute to the project.
