### ISSUE TITLE
Add GluePartitionSensor

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31438]
### Body

Sensor that waits for a specific partition(s) in a table.
Can be constructed on top of boto3 [Glue.Client.get_partitions(**kwargs)](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_partitions.html)

Need to support the following use cases:
1. Waiting for specific partition
2. Given range of partitions wait for at least one partition present in range.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by RachitSharma2001** [comment]
I would love to work on this if that is ok.

**Comment by RachitSharma2001** [comment]
Looking at the codebase, I see that there exists a `GlueCatalogPartitionSensor` already. This waits for a specific partition to show up in a Glue table. Would the `GluePartitionSensor` just be a more powerful version of this, as it would be able to handle a range of partitions as opposed to just one partition?

**Comment by eladkal** [comment]
> Looking at the codebase, I see that there exists a GlueCatalogPartitionSensor already. This waits for a specific partition to show up in a Glue table. Would the GluePartitionSensor just be a more powerful version of this, as it would be able to handle a range of partitions as opposed to just one partition?

ah yeah!
I looked under `glue.py` rather than under `glue_catalog.py`
