### ISSUE TITLE
S3ToAzureBlob Transfer Operator

### ISSUE THREAD

**Issue by RachitSharma2001** [apache/airflow#31449]
### Description

A useful operation would be to move data from an S3 Bucket to an Azure Blob Storage. Azure is able to support this kind of transfer, as seen [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json). As seen from this post [here](https://stackoverflow.com/questions/69893676/apache-airflow-operator-to-transfer-data-files-from-s3-to-azure-blob), there are people who would find this functionality useful. 

### Use case/motivation

Currently, Airflow support Azure transfers such blob to gcs, local to data lake, etc. However, there is no support for moving data from an S3 Bucket to Azure Blob storage. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
No need to open issue if you are going to submit PR. Just open PR directly

**Comment by jroachgolf84** [comment]
Is this operator yet to implemented? If so, I'd like to have it assigned to myself and begin development.

**Comment by jroachgolf84** [comment]
Would this operator be more suited in the `airflow/providers/amazon/aws/transfers/` directory? I wasn't able to pick up rules describing where a cross-cloud operator should go. That being said, there are two reasons I believe that this operator should be in the `airflow/providers/amazon/aws/transfers` directory:

1. There are very few operators in the `airflow/providers/microsoft/azure/transfers/` directory.
2. There is a corresponding `AzureBlobStorageToS3Operator` in the `airflow/providers/amazon/aws/transfers/` directory.

Thanks!

**Comment by jroachgolf84** [comment]
Issue good to close (addressed via https://github.com/apache/airflow/pull/40511).
