### ISSUE TITLE
Add capability in Airflow connections to validate host

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#31460]
### Apache Airflow version

2.6.1

### What happened

While creating connections in airflow, the form doesn't check for the correctness of the format of the host provided. For instance, we can proceed providing something like this which is not a valid url: `spark://k8s://100.68.0.1:443?deploy-mode=cluster`. It wont instantly fail but will return faulty hosts and other details if called later.

Motivation:
https://github.com/apache/airflow/pull/31376#discussion_r1200112106

### What you think should happen instead

The Connection form can have a validator which should check for these scenarios and report if there is an issue to save developers and users time later.

### How to reproduce

1. Go to airflow connections form
2. Fill in connection host as: `spark://k8s://100.68.0.1:443?deploy-mode=cluster`, other details can be anything
3. Create the connection
4. Run `airflow connections get <name>` 
5. The host and schema will be wrong

### Operating System

Macos

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
note that this one is a bit tricky. It literally needs to be "per-connection type". The host part might vary wildly between different types of connections and it does not have to conform to a standard URL or anything. There are likely connection types that are using host as host name (and there it could theoretically contain even multiple :// ://, some other treat is a URL, some other have likely different expectations. 

So I don't think there is "one rule to apply to all of them".

**Comment by hussein-awala** [comment]
this validation will be added by #31465
