### ISSUE TITLE
ERROR!!!: Too old Airflow version !

### ISSUE THREAD

**Issue by AbrahanTorres** [apache/airflow#31506]
### Apache Airflow version

2.6.1

### What happened

Hi team.

Please help me with an issue.

I have got an issue recently, it is new, weeks ago It did not happened. 

I use in the dockerfile FROM apache/airflow:latest
![image](https://github.com/apache/airflow/assets/102258512/07f0cbd3-3b9e-4ea7-b86f-a86ef79812e9)

And in the docker-compose.yml also the latest version

![image](https://github.com/apache/airflow/assets/102258512/9df57625-29ad-4d84-913e-c3702d14658e)

I executed the docker command docker build and everthing is OK, The problem happend when I run the docker-compose up command.

![image](https://github.com/apache/airflow/assets/102258512/4e11f2b7-c70b-45f5-aef5-600072f34275)

How can I fixed this?

### What you think should happen instead

It sholud works as before.

### How to reproduce

    1. DOCKERFILE
    docker build . --tag extending_airflow:latest

    2. DOCKER-COMPOSE 
    docker-compose up

### Operating System

windows

### Versions of Apache Airflow Providers

latest

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Likely some of your requirements is bringing airflow down - See this chapter and note how you can detect this and find out which requirement does it:  https://airflow.apache.org/docs/docker-stack/build.html#example-of-adding-packages-from-requirements-txt
