### ISSUE TITLE
`/health` endpoint missed when adding triggerer health status reporting

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#31522]
### Apache Airflow version

main (development)

### What happened

https://github.com/apache/airflow/pull/27755 added the triggerer to the rest api health endpoint, but not the main one served on `/health`.

### What you think should happen instead

As documented [here](https://airflow.apache.org/docs/apache-airflow/2.6.1/administration-and-deployment/logging-monitoring/check-health.html#webserver-health-check-endpoint), the `/health` endpoint should include triggerer info like shown on `/api/v1/health`.

### How to reproduce

Compare `/api/v1/health` and `/health` responses.

### Operating System

mac os

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
I would like to work on this. I have started my efforts on this in PR https://github.com/apache/airflow/pull/31529
