### ISSUE TITLE
Airflow exmaple DAG using `schedule` property instead of `schedule_interval`

### ISSUE THREAD

**Issue by amarlearning** [apache/airflow#31525]
### What do you see as an issue?

Tutorial DAG in the examples folder still uses the `schedule` property for DAG. I don't see a property like `schedule` in the DAG class. I think it should be `schedule_interval`. I have seen similar issues in multiple places in the documentation.

### Solving the problem

We need to update the code.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is wrong. Schedule is now the default one and the others are deprecated. You should only use schedule.

**Comment by eladkal** [comment]
`schedule_interval` is deprecated. `schedule` is the relevant parameter.
If this is confusing to you then you are probably running older Airflow version and if so you should view the docs for the version you have. The `schedule` parameter appears only for version where it's avaiable.

**Comment by amarlearning** [comment]
@eladkal @potiuk you are right, my bad. I got confused between `2.3.4` and `2.4.3` 😅

**Comment by potiuk** [comment]
Easy miss :)
