### ISSUE TITLE
Missing values from API response - `dags/{dag_id}/details`

### ISSUE THREAD

**Issue by Adaverse** [apache/airflow#31605]
### Apache Airflow version

2.6.1

### What happened

When calling the API GET `dags/{dag_id}/details`, we get the following response - 
```
{
  "catchup": false,
  "concurrency": 16,
  "dag_id": "tutorial",
  "dag_run_timeout": null,
  "default_view": "grid",
  "description": "A simple tutorial DAG",
  "doc_md": "\n    This is a documentation placed anywhere\n    ",
  "end_date": null,
  "file_token": "Ii9maWxlcy9kYWdzL3R1dG9yaWFsLnB5Ig.OOp1l6v5V9rSh-D0cJjLCb8XlHI",
  "fileloc": "/files/dags/tutorial.py",
  "is_active": true,
  "is_paused": false,
  "is_paused_upon_creation": null,
  "is_subdag": false,
  "last_parsed": "2023-05-30T04:47:57.735743+00:00",
  "max_active_runs": 16,
  "max_active_tasks": 16,
  "orientation": "LR",
  "owners": [
    "airflow"
  ],
  "params": {},
  "pickle_id": null,
  "render_template_as_native_obj": false,
  "schedule_interval": {
    "__type": "TimeDelta",
    "days": 1,
    "microseconds": 0,
    "seconds": 0
  },
  "start_date": "2021-01-01T00:00:00+00:00",
  "tags": [
    {
      "name": "example"
    }
  ],
  "timezone": "Timezone('UTC')"
}
```

### What you think should happen instead

Instead, it should have returned all the fields mentioned in the schema - 
```
{
  "dag_id": "string",
  "default_view": "string",
  "description": "string",
  "file_token": "string",
  "fileloc": "string",
  "has_import_errors": true,
  "has_task_concurrency_limits": true,
  "is_active": true,
  "is_paused": true,
  "is_subdag": true,
  "last_expired": "2023-05-30T04:48:34.555Z",
  "last_parsed_time": "2023-05-30T04:48:34.555Z",
  "last_pickled": "2023-05-30T04:48:34.555Z",
  "max_active_runs": 0,
  "max_active_tasks": 0,
  "next_dagrun": "2023-05-30T04:48:34.555Z",
  "next_dagrun_create_after": "2023-05-30T04:48:34.555Z",
  "next_dagrun_data_interval_end": "2023-05-30T04:48:34.555Z",
  "next_dagrun_data_interval_start": "2023-05-30T04:48:34.555Z",
  "owners": [
    "string"
  ],
  "pickle_id": "string",
  "root_dag_id": "string",
  "schedule_interval": {
    "__type": "string",
    "days": 0,
    "microseconds": 0,
    "seconds": 0
  },
  "scheduler_lock": true,
  "tags": [
    {
      "name": "string"
    }
  ],
  "timetable_description": "string",
  "catchup": true,
  "concurrency": 0,
  "dag_run_timeout": {
    "__type": "string",
    "days": 0,
    "microseconds": 0,
    "seconds": 0
  },
  "doc_md": "string",
  "end_date": "2023-05-30T04:48:34.555Z",
  "is_paused_upon_creation": true,
  "last_parsed": "2023-05-30T04:48:34.555Z",
  "orientation": "string",
  "params": {},
  "render_template_as_native_obj": true,
  "start_date": "2023-05-30T04:48:34.555Z",
  "template_search_path": [
    "string"
  ],
  "timezone": "string"
}
```

I can see a lot of these missing fields being returned from `dags/{dag_id}`. Also, the model on which the response of the details endpoint is based on, contains all these fields. Hence, ideally, it should return all these fields either null or some value.

### How to reproduce

Just call the above endpoint from the Swagger UI or any other means.

### Operating System

Ubuntu (20.04.5 LTS (Focal Fossa))

### Versions of Apache Airflow Providers

None

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
hi @Adaverse . It is not necessary to return all fields from a database model in an API response. In fact, it is often considered a good practice to only include the necessary fields in the response to minimize data transfer and improve performance.

IMO, if you feel some fields are necessary that can be consumed by the interface/client, we can include those, but not all :)

Also, please feel to create a PR directly without creating issues if you know you're going to work on it and also going to create a PR for it. I have seen a convention across the project to create issues either for reporting bugs or feature requests that users would like to have but they themselves are not going to create a PR for it.

**Comment by Adaverse** [comment]
Thanks for quick response @pankajkoti 
Yes majority of the fields are necessary since they are available to users today in the UI at /details page.

According to my understanding since we are dumping the serialized DAG model from DagBag into a schema that contains all the fields, hence the api should have returned all the fields.  Hence I wanted to know where are controlling the fact that which field should be part of API response and which should not.

**Comment by pankajkoti** [comment]
yes, okay. calling the expert. @pierrejeambrun could you please help us here when you have time?

**Comment by Adaverse** [comment]
To add some more info - 
[Here](https://github.com/apache/airflow/blob/956aac2b2d719e76c9c8cf6a77e9373021900307/airflow/api_connexion/openapi/v1.yaml#L1738) we can see that it is clearly mentioned that `dags/{dag_id}/details` would contain much more info than `/dags/{dag_id}`, but on hitting the API, the opposite is seen. On little more investigation, the dag that is being returned [here](https://github.com/apache/airflow/blob/956aac2b2d719e76c9c8cf6a77e9373021900307/airflow/api_connexion/endpoints/dag_endpoint.py#L61) doesn't contain all the fields that are there in `DAGDetailSchema` + `DAGSchema`. Just wondering why it is so.

Background -  We are working on replacing the current `dags/{dag_id}/details` UI screen with all the info in the grid view.

**Comment by pierrejeambrun** [comment]
`DAG` and `DagModel` are distinct entities with distinct attributes and purpose (even if some overlaps). Schemas suggest full inheritance for all attributes of `DAGModel` into `DAG` but it is not completely true, and some of them do not exist on a `DAG` instance. Therefore I think this is why they are missing from serialization on the `/details`.

I think the idea was that a `SerializedDAG` has a lot more info than the DagModel (which just represents the DAG metadata), for instance children, task_group, tasks, UI colors, dag_dependencies to name a few and appeared as a natural base class for a ' detailed' dag view.

I think schemas should be fixed to at least reflect what is actually returned by the API. (So the doc is not misleading anymore).

Then if you need some additional information not yet available on the `/details` view, we can update it. (But that would mean adding attributes to the `SerializedDAG` class, which is not trivial and has some inplications on other components (scheduler, DagFileProcessor, serialization module etc...)

**Comment by Adaverse** [comment]
> `DAG` and `DagModel` are distinct entities with distinct attributes and purpose (even if some overlaps). Schemas suggest full inheritance for all attributes of `DAGModel` into `DAGDetail` but it is not completely true, and some of them do not exist on a `DAG` instance. Therefore I think this is why they are missing from serialization on the `/details`.
> 
> I think the idea was that a `SerializedDAG` has a lot more info than the `DagModel` (which just holds the DAG metadata), for instance children, task_group, tasks, UI colors, dag_dependencies to name a few and appeared as a natural base class for a ' detailed' dag view.
> 
> I think schemas should be fixed to at least reflect what is actually returned by the API. (So the doc is not misleading anymore).
> 
> Then if you need some additional information not yet available on the `/details` view, we can update it, but that would mean adding attributes to the `SerializedDAG` class, which is not trivial and has some implications on other components (scheduler, DagFileProcessor, serialization module etc...)

Thanks @pierrejeambrun for the information. For now we can combining the APIs to get all the info. I think we can take this up later if absolutely required but for now I think its fine.
