### ISSUE TITLE
Airflow Scheduler not working as expected with SQL Server as backend whereas the same configuration working fine with Postgres as backend

### ISSUE THREAD

**Issue by sidnalla** [apache/airflow#31618]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Scheduler not working as expected with SQL Server as backend whereas the same configuration working fine with Postgres as backend. The DAGs are not getting triggered as per the schedule. And also the manual trigger is not working as expected. In case of manual trigger, the DAGs are getting started after 4 hours of the manual trigger time.

If the DAGs are manually triggered at 9 AM UTC, they are running at 1 PM UTC(4 hours after the trigger time). Looks like it is considering the EST time(server time where Airflow is running). We have changed the below parameters to match the timezones for the Server on which Airflow is running and the UI timezone. We set the below two parameters to America/NewYork since the server is in EST zone. But, we are still seeing the same issue. The same configuration works fine when we use Postgres as the backend.

AIRFLOW__CORE__DEFAULT_TIMEZONE
AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE

Could you please clarify if something needs to be changed when we use Sql Server as the backend?

### How to reproduce

If the DAGs are manually triggered at 9 AM UTC, they are running at 1 PM UTC(4 hours after the trigger time). Looks like it is considering the EST time(server time where Airflow is running). We have changed the below parameters to match the timezones for the Server on which Airflow is running and the UI timezone. We set the below two parameters to America/NewYork since the server is in EST zone. But, we are still seeing the same issue. The same configuration works fine when we use Postgres as the backend.

AIRFLOW__CORE__DEFAULT_TIMEZONE
AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE

### Operating System

linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Sound similar to
https://github.com/apache/airflow/issues/31487#issuecomment-1561972242

**Comment by jscheffl** [comment]
MSSQL support is dropped finally in Airflow 2.9.0, I'd not expect a fix for this issue. Therefore closing.
