### ISSUE TITLE
Dataset producers are not being connected to consumers

### ISSUE THREAD

**Issue by barrysteyn** [apache/airflow#31626]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Datasets producers are not being connected to dataset consumers. A picture paints a thousand words:
![Screenshot 2023-05-30 at 7 44 36 PM](https://github.com/apache/airflow/assets/1537348/996a88fe-1ae1-40f8-ba01-014ec76ab335)

### What you think should happen instead

The scheduled consumer dataset should be connected to the producer.

### How to reproduce

I have a function that deterministically produces strings based on a config.

### Operating System

MacOD

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Can you share a dag to reproduce the behaviour

**Comment by hussein-awala** [comment]
If you compare the two dataset names in the screenshot, you'll notice that they are different: one is labeled as `dynamodb`, while the other is labeled as `dynamobd`.
I tried to reproduce the issue in 2.6.1, but everything appears to be working correctly.

I close the issue and we can reopen it if needed.
