### ISSUE TITLE
waitForMigrations.enabled is missing for "workers" helm

### ISSUE THREAD

**Issue by grjones** [apache/airflow#31624]
### Official Helm Chart version

1.9.0 (latest released)

### Apache Airflow version

2.6.1

### Kubernetes Version

1.26

### Helm Chart configuration

`waitForMigrations` does not have an `enabled` property for the `workers` section. For consistency with the other components and to fully support ignoring migrations, the `enabled` boolean should be added.

### What happened

I tried to set `waitForMigration.enabled` on `workers` but it is not supported.

### What you think should happen instead

For consistency with the other components and to fully support ignoring migrations, the `enabled` boolean should be added.

### How to reproduce

Add this to your `values.yaml`:

```
workers:
  waitForMigrations:
    enabled: false
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
I know you didn't hit the "Yes, I'll do a PR" box, but just keep in mind in the future that we don't require an issue for PRs. You can just open a PR directly 👍
