### ISSUE TITLE
Add extra links for EMR Serverless

### ISSUE THREAD

**Issue by dacort** [apache/airflow#31620]
### Description

Add extra links to the EMR Serverless operator for S3 logs as well as the [`GetDashboardForJobRun`](https://docs.aws.amazon.com/emr-serverless/latest/APIReference/API_GetDashboardForJobRun.html) API that returns a one-time link to the UI.

### Use case/motivation

Allow for easier debugging of EMR Serverless jobs. Today, folks have to navigate through the AWS console to find the corresponding application and job run ID in order to gain access to the Spark UI or stdout/stderr logs. It'd be great to have direct links for both of those things.

One potential challenge is that the URL returned by the [`GetDashboardForJobRun`](https://docs.aws.amazon.com/emr-serverless/latest/APIReference/API_GetDashboardForJobRun.html) API is both short-lived (expires after 1 hour) and one-time (expires on first use). I'm concerned about both poor user experience of clicking an expired or already used URL and the API impact of generating a URL every time the DAG popup is triggered even if it's not used. This may require some additional functionality in Airflow to implement.

### Related issues

#29939

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
@dacort assigning it to you as you mentioned that you are willing to submit a PR for this

**Comment by eladkal** [comment]
Hi @dacort are you still working on this issue?

**Comment by dacort** [comment]
I am yes, hope to push something up early next week. 

- Don't think I will try to figure out a new approach for ephemeral links. Some changes were made on EMR side to make the user experience better
- Also considering add more links (like to S3 and/or [CloudWatch](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-emr-serverless-storing-logs-amazon-cloudwatch/), but then the links started going off the pop up dialog. :/
