### ISSUE TITLE
dags in error

### ISSUE THREAD

**Issue by onacht** [apache/airflow#31632]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

airflow version- 2.3.0
hello we are using the helm chart to install airflow in out eks cluster
we run the cluster on od nodes and spot instances and it looks like when ever a spot instance is replacing the pods that run the dags on the node get evicted and when they move to the new node they become stuck on an error state
after checking the logs of the pod this is the error:
airflow.exceptions.AirflowException: Dag 'spot_sfdc_update_dag' could not be found; either it does not exist or it failed to parse.
this dag exist and if i try to run it, it runs just fine
thanks in advanmce for any kind of help!

### What you think should happen instead

the dag should continue working in the new node or reset but should not stay in an error state

### How to reproduce

a node should be replaced when dag is in the middle

### Operating System

Debian GNU/Linux 11

### Versions of Apache Airflow Providers

airflow version- 2.3.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
@YuvalDr Are there any other log messages from the git-sync container? I believe there might be a problem with the git-sync, and the dag file does not exist indeed.

**Comment by onacht** [comment]
@hussein-awala hello
this is the log from git-sync container of a pod that is stuck in error
INFO: detected pid 1, running init handler
I0531 09:31:28.682385      11 main.go:454] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync"]
I0531 09:31:28.682795      11 main.go:871] "level"=0 "msg"="cloning repo" "origin"="https://github.com/spotinst/spot-bi-dag.git" "path"="/git"
I0531 09:31:30.596710      11 main.go:714] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="7356dec50e52882ceb7a119dbd8c3c7be7626a05"
I0531 09:31:32.658085      11 main.go:749] "level"=0 "msg"="adding worktree" "path"="/git/7356dec50e52882ceb7a119dbd8c3c7be7626a05" "branch"="origin/main"
I0531 09:31:33.275215      11 main.go:815] "level"=0 "msg"="reset worktree to hash" "path"="/git/7356dec50e52882ceb7a119dbd8c3c7be7626a05" "hash"="7356dec50e52882ceb7a119dbd8c3c7be7626a05"
I0531 09:31:33.275258      11 main.go:820] "level"=0 "msg"="updating submodules"

**Comment by ephraimbuddy** [comment]
This might have been fixed. Can you try version 2.6.1

**Comment by YuvalDr** [comment]
@hussein-awala we did not find any other logs on the git-sync container other those I listed above.
@ephraimbuddy we are running on k8s and no helm chart is available for 2.6.1, latest one is 2.5.3, should it be fixed in 2.5.3 as well or should we wait for a release of 2.6.1 helm chart?

**Comment by ephraimbuddy** [comment]
@YuvalDr , I think you can upgrade the default airflow version in the helm chart

**Comment by YuvalDr** [comment]
Hey @ephraimbuddy, we upgraded last month and let it up until now, so far it looks good, I think we can close this issue.
Thanks for the help!
