### ISSUE TITLE
Quiet mode for dags list-import-errors

### ISSUE THREAD

**Issue by fjmacagno** [apache/airflow#31655]
### Description

Add an option for `airflow dags list-import-errors` command like `-q` which suppresses all logging, in order to print just the intended output.

### Use case/motivation

I want to make a CI test which confirms that there are no dag import errors, and the easiest way that it seems to do that is to parse the output of `airflow dags list-import-errors`, something like
```
airflow dags list-import-errors -o json | jq -e 'select(type=="array" and length == 0)'
```

However, if there is any logging that occurs in `list-import-errors` it breaks the test, and it isn't always possible to remove the logging statement (currently [this](https://github.com/datahub-project/datahub/blob/4ade1311f179d16dc95b6ebf412dc88c846f02c2/metadata-ingestion/src/datahub_provider/_plugin.py#L354) is messing me up).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vedantlodha** [comment]
Hey Folks! I would like to work on this issue. Is it okay if i take this up?

**Comment by hussein-awala** [comment]
@vedantlodha Sure, I assigned you

**Comment by phanikumv** [comment]
@hussein-awala is it fine to remove the `needs-triage` label on this? Looks like it is a bug

**Comment by hussein-awala** [comment]
I'm not sure if this is a bug or a new feature, I prefer that someone else take a look on this issue and do the triag

**Comment by potiuk** [comment]
This is not a bug @fjmacagno  - this is a bit of sloppines on your side.

1) you should fix the deprecation warning - simply fix your configuratoin
2) remove INFO log in your plugin at the top-levle code  it gets imported

The problem is tha those logs and warnings are printed when imports are happening and we have no chance to disable it before. There is not much we can do here. Fix your configuration and remove info log.

**Comment by fjmacagno** [comment]
Thank you for the explanation! I understand what you are saying now, yeah it wouldn't make any sense to add any sort of hacky fix for something that is clearly not idiomatic. It didn't occur to me originally that these messages would be printed during imports.

I could see one non-hacky workaround could be to add a `-o <filepath>` argument to any command like this one to change the command output stream, but that seems like far more effort than it is worth for an issue like this.

**Comment by potiuk** [comment]
> I could see one non-hacky workaround could be to add a -o <filepath> argument to any command like this one to change the command output stream, but that seems like far more effort than it is worth for an issue like this.

Indeed, I think what **could** be a solution is to mention in the documentation that if you want to use the -o option you might want to disable or lazy load plugins and make sure you get rid of deprecations . I wonder if the `lazy load` solution worked for you - if it did, maybe a PR to improve the docs around it (for example a general note in the "CLI" page could be somethin you could consider contributing :)

**Comment by fjmacagno** [comment]
It did work, though i was also able to finally get the logging statement removed from Datahub. I have finally had time to write up an addition to the docs, thanks for the suggestion!
