### ISSUE TITLE
Issue with "@continuous" schedule. 

### ISSUE THREAD

**Issue by arjunanan6** [apache/airflow#31679]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

v: 2.6.0

Not sure if this is a bug or a really odd issue. But, I'm seeing an extremely weird issue ever since we switched out one of our DAGs to use the `@continuous` schedule. Ever since, any change to the DAG will not persist, and we cannot even refresh our DAGs. I've tried using `airflow db clean` against the dag and dag_run table in an attempt to purge anything, but somehow the DAGbag gets refreshed with the old DAGs despite /opt/airflow/dags containing only 1 dag now (it's a test environment so I tried this out). 

Before we noticed this problem, the first issue that we saw was that the schedule would no longer change on the specific dag we switched the schedule_interval on. Previously, it was `@continuous` and now it is None. However, the UI still shows:

![image](https://github.com/apache/airflow/assets/102953522/d58361d4-657f-411d-87f6-7da74c5c697b)

If I look at the code view, I can see that it is indeed None. Is there anything else I can do here other than a db reset?

### What you think should happen instead

The DAG bag should remove the old dags and show only the 1 new DAG.

### How to reproduce

N/A - but it has only become a problem ever since we tried the @contninuos schedule.

### Operating System

Debian GNU/Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.0.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-microsoft-psrp==2.2.0
apache-airflow-providers-microsoft-winrm==3.0.0
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-oracle==3.0.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Deployed on AKS.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Before accepting the issue, I have a few questions:
1. How many schedulers do you have?
2. Have you checked if the DAG file is up to date on all schedulers volumes?
3. Are you certain that the DAG file processor is running? Have you verified if the `last_parsed_time` in the DAG view is greater than the timestamp of your change?
4. Additionally, why did you mention `@continuous` in the issue? Have you attempted to add other DAGs with different schedules and update their parameters to see if they were updated properly?

**Comment by arjunanan6** [comment]
Hi @hussein-awala, sure here are the answers:
1. We have only one scheduler.
2. Actually, it is not. For some reason, the scheduler still has files from yesterday. I've tried deleting the scheduler pod, but it somehow has those retained. On the webserver pod for instance, I can see that the dag list is up to date.
3. Seems to be, from the DB I can see that the last parsed time is from a few minutes ago. My change was first done about 3h back - when I first noticed this problem. 
4. To be honest, it could be a total coincidence, but we only noticed this problem first after this switch to "@continuous" schedule in one DAG. At this moment, no new DAGs register at all, and I cannot remove anything either. This has to be related to pt. 2.

**Comment by hussein-awala** [comment]
> Actually, it is not. For some reason, the scheduler still has files from yesterday. I've tried deleting the scheduler pod, but it somehow has those retained. On the webserver pod for instance, I can see that the dag list is up to date.

So that is the problem (which is not related to Airflow). Are you using `git-sync` to pull the dags files?

**Comment by arjunanan6** [comment]
Indeed, I just correlated it (maybe incorrectly) to the continuous schedule. We are not using git-sync, however, a new build is triggered each time there is an update to our dags repository(ies). In this case, it is a dev environment, so it is just on a change to the dags directory. I find it weird that all other pods show the right status with the right DAGs, but scheduler didn't. Even an `airflow db reset` did not help - which makes sense considering that the scheduler had all the old DAGs in the dags dir. 

But anyway, I nuked the deployment for the scheduler and now things are behaving well. Thanks for the input, it helped me isolate the problem!

**Comment by arjunanan6** [comment]
I will continue to play around with the continuos schedule locally to see if I can replicate this issue (at least the UI bug).

**Comment by hussein-awala** [comment]
If you add the DAGs file to the Docker image, you can compare the hash of the scheduler pod with the hashes of the other services pods.

**Comment by hussein-awala** [comment]
I close the issue, and we can re-open it if needed.

**Comment by arjunanan6** [comment]
Thought I'd add a comment here in case someone else comes looking for something similar, but I did not manage to reproduce the issue after all. It looks like this issue was indeed related to image integrity as you said @hussein-awala. It's just strange that it happened on only the scheduler, but I leave it at that since I cannot reproduce it.
