### ISSUE TITLE
Unable to specify dns_config for kubernetes pod executor

### ISSUE THREAD

**Issue by rokos-angus** [apache/airflow#31689]
### Apache Airflow version

2.6.1

### What happened

Seem to be unable to specify dns_config in KubernetesPodOperator, despite it being an argument.

`Broken DAG: [/opt/airflow/dags/repo/bug-report-dag.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to KubernetesPodOperator (task_id: task). Invalid arguments were:
**kwargs: {'dns_config': {'nameservers': None, 'options': None, 'searches': ['mydomain.com']}}`

### What you think should happen instead

dnsConfig should be correctly added to the pod manifest

### How to reproduce

```
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
from airflow.utils.dates import days_ago
from kubernetes.client import models as k8s

default_args = {
    'owner': 'airflow'
}

env = [
    k8s.V1EnvVar(name="TEST_ARG", value="test")
]
dns = k8s.V1PodDNSConfig(searches=["mydomain.com"])

with DAG(
    dag_id='my-dag',
    default_args=default_args,
    schedule_interval="*/5 * * * *",
    start_date=days_ago(2),
    catchup=False,
    tags=['k8s-pod-operator','example', 'python'],
) as dag:
    k = KubernetesPodOperator(
        namespace='airflow',
        image="python",
        cmds=["python", "-c"],
        arguments=["print('hello ...')"],
        name="k8s-pod",
        task_id="task",
        env_vars=env,
        dns_config=dns,
        is_delete_operator_pod=True,
        hostnetwork=False,
        startup_timeout_seconds=1000,
        kubernetes_conn_id=None
    )

```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Official helm chart via flux with 
defaultAirflowTag: "2.6.1"
    airflowVersion: "2.6.1"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
`dns_config` was added in https://github.com/apache/airflow/pull/30992
Please update to `apache-airflow-providers-cncf-kubernetes==7.0.0`

**Comment by rokos-angus** [comment]
Thanks @eladkal 
Docs are a bit vague, but I was able to create a custom image which pip installed that package over the base airflow image and this works.
Is this the recommended approach?
