### ISSUE TITLE
Multi tenant Web UI

### ISSUE THREAD

**Issue by kapil-malik** [apache/airflow#317]
We want to use Airflow in a multi-tenant environment.

The dags (python scripts), will be created by different people (reflected in owner field), but eventually dumped to <airflow-home>/dags folder via a central API.

Given that Airflow does not expose any REST APIs to get state (dags / tasks et al),and the UI is too good to be reinvented, we want to use the same UI for different tenants.

However, the default UI shows everything to the user, we can call it the 'admin view'. I want to enable 'tenant view' of UI where a tenant can login (Basic auth for example), will be able to see only the dags (and corresponding tasks/status/logs etc.) with tenant as owner.
It will also be nice to hide all admin-type tabs (like connections/variables/pools) etc. for the tenants. It can be assumed that admin will create and define these for all tenants at system level.

**Comment by kapil-malik** [comment]
I went through [Web-Authentication](http://pythonhosted.org/airflow/installation.html#web-authentication) and [default-login.py](https://github.com/airbnb/airflow/blob/master/airflow/default_login.py).
Can some one kindly confirm if modifying default-login.py should be sufficient for this requirement? (Basic auth + restricted views) or would I need to write some plugins as mentioned [here](http://pythonhosted.org/airflow/plugins.html).

**Comment by mistercrunch** [comment]
There are 3 levels of access to the UI, the basic, the data profiling (+data profiling menu) and the superuser (admin menu items). 

The flask-login hook should allow you to define your user model and authenticate in a way that makes sense in your environment (ldap, openid, password, authentication reverse proxy, ...).

As to different people seeing different DAGs, are you doing it to avoid confusion, or do you really want to restrict someone from seeing someone else's DAGs? If you want to restrict you'll probably need to add it as a new security access level.

**Comment by kapil-malik** [comment]
Hi @mistercrunch 
Thanks for the reply. So as I understand, flask-login hook gives me 
1. Authentication and 
2. Access level as you mention.
We also need 
3. DAGs filtering based on owner
So can be taken up as a potential contribution.

However, right now, I am struggling with flask-login. I am a python noob and trying to understand how it works. I copied default_login as airflow_login to pythonpath, and is picked up correctly (also set authenticate=true). However, it results in an infinite loop between 
GET /admin and
GET /admin/airflow/login?next=/admin

So is there some minimal modification I can / need to do to the airflow_login.py to make it work?

I was hoping something like a basic authentication popup to show with DEFAULT_USER (i.e. airflow) as valid username, and something (say secret_key?) as password.

I guess going through flask login tutorials available online will probably help, but some immediate suggestions to make it work will allow me to get on board quickly.

Thanks.

**Comment by mistercrunch** [comment]
Here's an example of how this can be done. We use an internal authentication reverse proxy that authenticates and adds information in http headers

```
import flask_login

from flask_login import login_required, current_user, logout_user
from flask import url_for, redirect

from airflow import settings
from airflow import models

from sqlalchemy.types import PickleType
from sqlalchemy import Column

import urllib2
import re


ACCEPTED_ROLES= [
    'Some secret roles'
]

login_manager = flask_login.LoginManager()
login_manager.login_view = 'airflow.login'  # Calls login() bellow
login_manager.login_message = None

class User (models.BaseUser):
    roles = Column(PickleType())

    def is_active(self):
        '''Required by flask_login'''
        return True

    def is_authenticated(self):
        '''Required by flask_login'''
        return True

    def is_anonymous(self):
        '''Required by flask_login'''
        return False

    def data_profiling(self):
        '''Provides access to data profiling tools'''
        roles = self.roles or []
        return any([g in ACCEPTED_ROLES for g in roles])

    def is_superuser(self):
        '''Access all the things'''
        roles = self.roles or []
        return any([g in ACCEPTED_ROLES for g in roles])
models.User = User
del User


@login_manager.user_loader
def load_user(userid):
    session = settings.Session()
    user = session.query(models.User).filter(models.User.id == userid).first()
    session.expunge_all()
    session.commit()
    session.close()
    return user


def login(self, request):
    session = settings.Session()

    has_access = some_secret_internal_stuff()

    if has_access:
        user = session.query(models.User).filter(
            models.User.username == username).first()
        if not user:
            user = models.User(username=username)
        user.email = email
        user.roles = groups
        session.merge(user)
        session.commit()
        # this is important
        flask_login.login_user(user)
        session.commit()
        session.close()
        return redirect(request.args.get("next") or url_for("index"))
    else:
        return redirect(url_for('airflow.noaccess'))

```

**Comment by kapil-malik** [comment]
Thanks @mistercrunch 
Although the code above gives me an error on compilation -

```
sqlalchemy.exc.ArgumentError: Column 'roles' on class <class '__main__.User'> conflicts with existing column 'user.roles'
```

But I got the crux of why the default_login.py was not working.

default_login.py has -

```
def login(self, request):
# ----- some stuff ---
    session.merge(user)
    session.expunge_all()
    session.commit()
    session.close()
    flask_login.login_user(user)
    return redirect(request.args.get("next") or url_for("index"))
```

It results in an infinite loop.

While the snippet you gave has -

```
def login(self, request):
# ----- some stuff ---
        session.merge(user)
        session.commit()
        flask_login.login_user(user)
        session.commit()
        session.close()
        return redirect(request.args.get("next") or url_for("index"))
```

Which works perfectly :) 
I think we should fix it in default_login.py as well.

**Comment by kapil-malik** [comment]
Again, thanks for getting me started on this. Will continue on this and update.

**Comment by kapil-malik** [comment]
Hi @mistercrunch 
I was able to enable a multi-user basic authentication login by extending default_login.py and adding a login page via plugins. It also sets data profiling / super_user appropriately.
However, to restrict other users from being able to see others' dags, tasks and logs, I needed to modify app.py. Please look at https://github.com/airbnb/airflow/pull/352 for the same.
Thanks

**Comment by kapil-malik** [comment]
Thanks for all the support.
