### ISSUE TITLE
Would it be possible to add 'config' to the list of template fields for EmrServerlessStartJobOperator?

### ISSUE THREAD

**Issue by sumitdas66** [apache/airflow#31711]
### Description

We have a use case where we would like to start job runs in EMR Serverless where the job name is derived from the output from a previous task.
Since the job name is passed via the 'config' argument to the EmrServerlessStartJobOperator, this request is to add 'config' to the list of 'template_fields' in that operator (https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/emr.py#L966), if at all possible.

Thanks in advance,
Sumit Das

### Related issues

Something similar is already implemented on the aws-samples project. 
Link to the related issue: https://github.com/aws-samples/emr-serverless-samples/issues/36
Link to the code: https://github.com/aws-samples/emr-serverless-samples/blob/main/airflow/emr_serverless/operators/emr.py#L171

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
This should definitely be feasible! Let me know if you would like to open a PR on it ?

**Comment by mahammi** [comment]
Hello! I would like to pick up this issue.

**Comment by sumitdas66** [comment]
Which versions of the provider and airflow can we expect these changes to reflect?

**Comment by phanikumv** [comment]
Hi @potiuk , I believe a PR needs to be created for the issue, hence lets keep the issue open.

**Comment by o-nikolas** [comment]
> Hi @potiuk , I believe a PR needs to be created for the issue, hence lets keep the issue open.

@phanikumv you can see the PR from Maham above has been merged (it is #31746), so I think this is safe to close
