### ISSUE TITLE
UI view of timetable based on CronDataIntervalTimetable shows incorrect planned dates

### ISSUE THREAD

**Issue by mattymo** [apache/airflow#31721]
### Apache Airflow version

2.6.1

### What happened

I have a custom class HolidayCronTimeTable which inherits CronDataIntervalTimetable as a plugin. It correctly shows the future execution dates in `airflow dags next-execution -n 30 test_timetable`, skipping holidays such as June 19 or July 4.

If I browse to http://myhost:8080/dags/test_timetable/calendar, I can see that all weekdays are ticked as planned according to the original cron expression. 

### What you think should happen instead

www/views.py should be updated to use the _get_next method from the timetable class used instead of blindly using croniter.

### How to reproduce

Create a custom class that wraps CronDataIntervalTimetable that overrides _gen_next() method and skips 1 or more dates. Store it in plugins directory. Create a DAG that uses it as a timetable.

### Operating System

CentOS 7

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by boushphong** [comment]
@mattymo Do you mind sharing your custom class? 
I can work on this

**Comment by hussein-awala** [comment]
@mattymo we can you provide an example to reproduce the issue? it's better to provide simple one similar to the one you have in prod, after checking if it has the same problem.
