### ISSUE TITLE
redirect to same url after set base_url

### ISSUE THREAD

**Issue by PaleNeutron** [apache/airflow#31726]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

```
$ curl localhost:8080/airflow/
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="http://localhost:8080/airflow/">http://localhost:8080/airflow/</a>. If not, click the link.
```

### What you think should happen instead

At least not circular redirect.

### How to reproduce

generate yaml:

```
helm template --name-template=airflow  ~/downloads/airflow > airflow.yaml
```

add base_url in webserver section and remove health and ready check in webserver(to keep pod alive):
```
    [webserver]
    enable_proxy_fix = True
    rbac = True
    base_url = http://my.domain.com/airflow/
```

### Operating System

Ubuntu 22.04.2 LTS

### Versions of Apache Airflow Providers

apache-airflow==2.5.3
apache-airflow-providers-amazon==7.3.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==5.2.2
apache-airflow-providers-common-sql==1.3.4
apache-airflow-providers-docker==3.5.1
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==8.11.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.0
apache-airflow-providers-http==4.2.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==5.2.1
apache-airflow-providers-mysql==4.0.2
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.4
apache-airflow-providers-sqlite==3.3.1
apache-airflow-providers-ssh==3.5.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
The circular redirect error suggests that there might be a misconfiguration in the URL redirection settings.

**Comment by PaleNeutron** [comment]
@rohan472000 I found the problem, it could be reproduced by using standalone mode and just set `base_url = http://localhost:8080/airflow/`  in `airflow.cfg`.

It should be  `base_url = http://localhost:8080/airflow`, without the last slash.

I think it should be treated as bug or at least emphasis it in document.
