### ISSUE TITLE
after upgrade 2.6.0 from 2.3.4, task can't show log in webui

### ISSUE THREAD

**Issue by itsallsame** [apache/airflow#31733]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I have a three node airflow cluster, after upgrade 2.6.0 from 2.3.4, task can't show log in webui. and when task in running state, i can see log in webui, however, after task is failed or sucess, task log is gone, only left hostname. 
![image](https://github.com/apache/airflow/assets/115528312/5657a7ec-8b4d-4191-92a5-16dc63665eb7)

by the way, airflow webserver、woker、scheduler process don't have error log.
master node get logs requese is fine:
![image](https://github.com/apache/airflow/assets/115528312/5ef8e421-95b5-4c83-a6aa-5898a9c7c20e)

and, use api get logs, have same issue:
![image](https://github.com/apache/airflow/assets/115528312/340ef41a-e365-4b90-8e14-2a544ee81c72)

upgrade steps:
1. step-1
AIRFLOW_VERSION=2.6.0
PYTHON_VERSION="$(python3 --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
pip3 install "apache-airflow==${AIRFLOW_VERSION}" --upgrade --constraint /home/airflow/deploy/upgrade/up_to_2_6_0/constraints-3.9.txt

2. step-2
kill worker process

3. upgrade db
airflow db upgrade

### How to reproduce

upgrade 2.6.0 from 2.3.4

### Operating System

centos7.6

### Versions of Apache Airflow Providers

2.6.0

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Scope0910** [comment]
Hey, 
i have exactly the same issue. I came from v2.3.3 - but without an upgrade. - we installed v2.6.0 on a new system with new metadb etc. Im not sure if it helps  - If i run the following code within webserver the logs are requested correctly - were using airflow on kubernetes 

`from airflow.providers.cncf.kubernetes.hooks.kubernetes import KubernetesHook    `
`hook = KubernetesHook(conn_id="kubernetes_default")
log = ""
for line in hook.get_pod_logs("<insert podname here>", namespace="<your namespace>"):
	log += line.decode()
	print(log) 
`

**Comment by potiuk** [comment]
Can you please update to 2.6.2 ? I believe this is manifestation of a known issue -> see release notes and look for 'logs'  https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-6-1-2023-05-16  - you will find the issue.

Generally speaking it makes very little sense to install .0 version when bugfix-only versions are out there. I am not sure why one would do it> @Scope0910 - could you please explain why you are installing 2.6.0 when 2.6.2 (bugfix only) is released already and 2.6.1 has been released few weeks ago? 

Closing this one as duplicate. We can reopen after user upgrades and still showing the issue.
