### ISSUE TITLE
Add a process_line callback to KubernetesPodOperator 

### ISSUE THREAD

**Issue by yupbank** [apache/airflow#31745]
### Description

Add a process_line callback to KubernetesPodOperator 
Like https://github.com/apache/airflow/blob/main/airflow/providers/apache/beam/operators/beam.py#LL304C36-L304C57 the `BeamRunPythonPipelineOperator`, which allows the user to add stateful plugins based on the logging from docker job 

### Use case/motivation

I can add a plugin based on the logging and also allow cleanup on_kill based on the job creation log. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
If you truly need this feature and you want to become an Airflow contributor, I encourage you to take the initiative and implement it yourself. Otherwise, you'll have to wait for someone else to pick up the issue and implement it.

**Comment by zeotuan** [comment]
I would like to pick up this feature.

**Comment by potiuk** [comment]
Feel free
