### ISSUE TITLE
User AWS postgresql with IAM auth as backend

### ISSUE THREAD

**Issue by stroeovidiu** [apache/airflow#31759]
### Apache Airflow version

2.6.1

### What happened

I am trying to deploy airflow in aws eks ( kubernetes ) using the helm chart. 
I am trying to set as external database an aws rds postgresql with IAM auth enabled.
I have created the IAM role and the corresponding service account but it doesn't connect.
I get "port 6432 failed: FATAL:  PAM authentication failed "
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

Does airflow support aws rds postgres as backend using iam auth ?

### How to reproduce

use an rds postgresql with iam auth as backend

### Operating System

kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Could you update the issue by providing more information about your Airflow configurations, the error/problem you have and a full example to reproduce the issue?

**Comment by stroeovidiu** [comment]
It is a vanilla airflow deployed in eks using as backend a postgresql database in RDS.
As for the custom configs:
 - an IAM user for the postgresql DB
 - an IAM role with permissions to connect to that db with that iam role
 - and kubernetes service account ( created using the helm provided values ) with annotations to map to the above IAM role.

What i am expecting is that the airflow pods/containers start but they get a PAM auth error .
Thank you !

**Comment by vincbeck** [comment]
Did you follow the recommandations as mentioned in the [documentation](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html#setting-up-a-postgresql-database). Specifically:

> For managed Postgres such as Redshift, Azure Postgresql, CloudSQL, Amazon RDS, you should use keepalives_idle in the connection parameters and set it to less than the idle time because those services will close idle connections after some time of inactivity (typically 300 seconds), which results with error The error: psycopg2.operationalerror: SSL SYSCALL error: EOF detected. The keepalive settings can be changed via sql_alchemy_connect_args configuration parameter [Configuration Reference](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html) in [database] section. You can configure the args for example in your local_settings.py and the sql_alchemy_connect_args should be a full import path to the dictionary that stores the configuration parameters. You can read about [Postgres Keepalives](https://www.postgresql.org/docs/current/libpq-connect.html). An example setup for keepalives that has been observed to fix the problem might be:

**Comment by stroeovidiu** [comment]
my issue is connecting to postgres using IAM Auth not password auth. The link you provided has no info on the matter i am trying to fix.
