### ISSUE TITLE
BaseSQLToGCSOperator creates row group for each rows during parquet generation

### ISSUE THREAD

**Issue by eric-ke-long** [apache/airflow#31750]
### Apache Airflow version

Other Airflow 2 version (please specify below)
Airflow 2.4.2

### What happened

BaseSQLToGCSOperator creates row group for each rows during parquet generation, which cause compression not work and increase file size.
![image](https://github.com/apache/airflow/assets/51909776/bf256065-c130-4354-81c7-8ca2ed4e8d93)

### How to reproduce

OracleToGCSOperator(
        task_id='oracle_to_gcs_parquet_test',
        gcp_conn_id=GCP_CONNECTION,
        oracle_conn_id=ORACLE_CONNECTION,
        sql='',
        bucket=GCS_BUCKET_NAME,
        filename='',
        export_format='parquet',
)

### Operating System

CentOS Linux 7

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-hive  2.1.0
apache-airflow-providers-apache-sqoop 2.0.2
apache-airflow-providers-celery       3.0.0
apache-airflow-providers-common-sql   1.2.0
apache-airflow-providers-ftp          3.1.0
apache-airflow-providers-google       8.4.0
apache-airflow-providers-http         4.0.0
apache-airflow-providers-imap         3.0.0
apache-airflow-providers-mysql        3.0.0
apache-airflow-providers-oracle       2.1.0
apache-airflow-providers-salesforce   5.3.0
apache-airflow-providers-sqlite       3.2.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
Are you getting any error while doing this operation? If not, I think this a new feature for the `OracleToGCSOperator`

**Comment by eric-ke-long** [comment]
@phanikumv I don't receive any error however it turn a 300KB parquet into 156MB, a kind of defect

**Comment by phanikumv** [comment]
Thanks for your response. I will try to reproduce the issue and analyze it

**Comment by phanikumv** [comment]
@eric-ke-long how did you check the file size(how did you get the info shown in the screenshot)

**Comment by hussein-awala** [comment]
This is normal, since we read the rows and we write them to the parquet one by one.
I have a solution for this problem, I will implement it and let you test it before merging the PR, but I see the issue more like a feature request (specify the row group size) rather than a bug.

**Comment by hussein-awala** [comment]
@eric-ke-long can you test #31831 and try to change the `parquet_row_group_size` paramter?

**Comment by eric-ke-long** [comment]
@hussein-awala Thanks for your update, sorry for late response. I just got chance to check chat box. I made a fix for this in my local and looks like our ideas are totally same. I believe your solution can solve above issue very well.

**Comment by hussein-awala** [comment]
Great! This new feature will be released soon.
