### ISSUE TITLE
Tree view is not showing correctly when the dag has s3keysensor

### ISSUE THREAD

**Issue by cwong99** [apache/airflow#318]
The tree view is not showing any run history when the dag includes a S3keysensor. 
Please refer to screen shot: the test dag is showing successful run on 8/24 on Graph View, but nothing is showing up on Tree View.

<img width="858" alt="screen shot 2015-08-26 at 8 11 17 am" src="https://cloud.githubusercontent.com/assets/1521793/9497496/1adfefbe-4bca-11e5-8f83-30d7fec12b08.png">
<img width="951" alt="screen shot 2015-08-26 at 8 11 26 am" src="https://cloud.githubusercontent.com/assets/1521793/9497498/1fb34720-4bca-11e5-9a47-d239e3521a8a.png">

**Comment by mistercrunch** [comment]
Which version are you using?  Also for clarity we tend to put an even `start_date` as in `2015-01-01T00:00:00` and use a `TimeSensor` to delay task execution to say `17:35:00`.

Anyhow the tree view should look ok either way, I think a fix was pushed for this recently.

`airflow version` will print the version
`pip install airflow --upgrade` to move up to the latest version

**Comment by cwong99** [comment]
It works after I change the start time.  Thanks!
