### ISSUE TITLE
Add retry + timeout to Airflow db check

### ISSUE THREAD

**Issue by xuganyu96** [apache/airflow#31818]
### Description

In my company usage of Airflow, developmental instances of Airflow run on containerized PostgreSQL that are spawned at the same time the Airflow container is spawned. Before the Airflow container runs its initialization scripts, it needs to make sure that the PostgreSQL instance can be reached, for which `airflow db check` is a great option.

However, there is a non-deterministic race condition between the PSQL container and Airflow containers (not sure which will each readiness first and by how much), calling the `airflow db check` command once is not sufficient, and implementing a retry-timeout in shell script is feasible but unpleasant.

It would be great if the `airflow db check` command can take two additional optional arguments: `--retry` and `--retry-delay` (just like with `curl`) so that the database connection can be checked repeatedly for up to a specified number of times. This command should exit with `0` exit code if any of the retries succeeds, and `1` if all of the retries failed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
feel free. sounds useful

**Comment by xuganyu96** [comment]
Some notes to myself about the specification of the new feature.

`--retry` is a optional argument that accepts a non-negative integer that indicates the number of times the database check will be performed AFTER the initial failure (meaning that with `--retry 0` database check will be performed once). The default value is to retry 0 times.

`--retry-delay` is an optional argument that accepts a positive integer as the number of seconds between each retry. The minimum value is 1 second.

At each database check failure, the command should print a message to STDOUT (borrowed from `curl`):

> Will retry in X seconds. Y retries left.

At the final database check failure, no additional message will be printed, and the program should exit with a non-zero exit code.

_some addition notes for implementation_:

- Use `type=positive_int(allow_zero=False)` for specifying integer argument

**Comment by xuganyu96** [comment]
# How database check is performed
The `airflow.cli.commands.db_command.check` function calls the function `airflow.utils.db.check`, which in turns uses the provided session to execute a trivial SQL command:

```python
@provide_session
def check(session: Session = NEW_SESSION):
    """
    Checks if the database works.

    :param session: session of the sqlalchemy
    """
    session.execute(text("select 1 as is_alive;"))
    log.info("Connection successful.")
```

The DB check command will let the `execute` function call raise unhandled exception as a "fail".

For implementing retry, one approach would be to catch the exception raised by `execute` each time and update the retry status in the "except" clause.

Note that `airflow.utils.db.check` is not used anywhere else, so it is also possible to refactor `db.check` in a major way, such as letting it return a boolean indicating whether the check is successful, which avoids using (what I think to be rather unsavory) try-catch blocks and makes the logic more straight forward, but oh well.

**Comment by xuganyu96** [comment]
# (WIP) Testing
There is obviously validating the behavior of `airflow db check --retry ... --retry-delay ...`

I don't see any existing unit tests for either the `db_commands.check` function or the `db.check` function in the test suite. I assume that since this code change is introducing non-trivial logic into the procedure of `airflow db check`, some unit tests would be needed? I am not sure about how to approach this though.

# (WIP) Documentation change
The help text in the CLI is automated updated alongside the code change.

- [ ] What about documentation on the CLI reference [webpage](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html)?
- [ ] Probably also need to update the change log

**Comment by potiuk** [comment]
> I don't see any existing unit tests for either the db_commands.check function or the db.check function in the test suite. I assume that since this code change is introducing non-trivial logic into the procedure of airflow db check, some unit tests would be needed? I am not sure about how to approach this though.

Just look at `tests/cli/commands/test_db_command.py` -> it has some ways other db commands have been tested, This should be similar. Mocking what's necessary (for example mocking out the call to the DB and pretending it failed) and testing just the retry logic.
