### ISSUE TITLE
Add a command line option to start a triggerer process with breeze

### ISSUE THREAD

**Issue by vandonr-amz** [apache/airflow#31826]
### Description

As discussed in https://lists.apache.org/thread/ss0605b561bcrrlogydgww1pzo97691j
It would be helpful to be able to start a triggerer process from the same command line that starts breeze, using an option like `--run-triggerer=True` or `--with-triggerer`.

### Use case/motivation

This option would be used when running system tests that contain deferrable operators, and thus need a triggerer to run to completion.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
@potiuk @eladkal @vandonr-amz , To resolve this issue I need to make changes in `main()`, so should I do changes in `breeze.py` by making a `main()` there or edit the existing `main()` in `breeze.src.airflow_breeze.commands.main_command` ??

**Comment by rohan472000** [comment]
> No. You should not need modify main. Why would you ?

Yes, don't need that, I tried without modifying `main()` in #31880

**Comment by kelechi2020** [comment]
@rohan472000 are you still working on this?

**Comment by shubham22** [comment]
@rohan472000 - can you please explain what problem are you facing so that folks can help? If you think it is better to be assigned to someone else, feel free to let us know. No pressure!

**Comment by rohan472000** [comment]
> @rohan472000 - can you please explain what problem are you facing so that folks can help? If you think it is better to be assigned to someone else, feel free to let us know. No pressure! 

Yes plz assign it to others as I'm not getting time.

**Comment by kelechi2020** [comment]
Okay. I can pick this up. Can you assign me?

**Comment by potiuk** [comment]
Done.

**Comment by vandonr-amz** [comment]
@kelechi2020 how are you making progress on this one ?
Did you check #31880 ? utkarsharma2 and potiuk left some pretty useful comments on how to approach the task. Please let us know if you need more help on it.

**Comment by o-nikolas** [comment]
Cleared out @kelechi2020 as the assignee since we haven't heard back in weeks. This way any other interested individuals can pick up the task. If you get back to it @kelechi2020 let me know and I can re-assign it to you!

**Comment by Bowrna** [comment]
I will pick this up today as part of dev sprint for PyCon India 2023 :)

**Comment by o-nikolas** [comment]
Fantastic! Thanks @Bowrna, I've assigned the issue to you :)

**Comment by Bowrna** [comment]
I am currently working on this issue and hope to raise a PR ( at least in draft mode) by end of this week.

**Comment by potiuk** [comment]
Reopened as @o-nikolas mentioned the idea here was for SYSTEM TESTS to support triggerer - see https://github.com/apache/airflow/pull/36063#issuecomment-1852622579
