### ISSUE TITLE
Allow variables to be printed to STDOUT

### ISSUE THREAD

**Issue by vedantlodha** [apache/airflow#31851]
### Description

Currently, the `airflow variables export` command requires an explicit file path and does not support output to stdout. However connections can be printed to stdout using `airflow connections export -`. This inconsistency between the two export commands can lead to confusion and limits the flexibility of the variables export command.

### Use case/motivation

To bring some consistency, similar to connections, variables should also be printed to STDOUT, using `-` instead of filename. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vedantlodha** [comment]
If the folks think this is a valid request, i would like to work on this. 
Thanks!

**Comment by potiuk** [comment]
Feel free. Sounds like a good first contribution

**Comment by phanikumv** [comment]
Assigned it to you @vedantlodha
