### ISSUE TITLE
pause/unpause dag logs wrong event status

### ISSUE THREAD

**Issue by achharKalia** [apache/airflow#31871]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

IN version 2.5.1 release, airflow pause/unpause dag button on dags page doesn't work properly.
When we pause a dag in the  audit logs its show dag as unpaused.
 and when we unpause any dag audit log shows a dag is paused. Also sometimes dag runs properly as per schedule and sometime doesn't because of this problem. 

IN recent dag behaviour, we enabled the dag on friday and dag was scheduled to run on Monday but it didn't. It was a active dag not paused in blue color. However in the dag audit logs, it was showing below :

2023-06-12, 17:42:57 | None | paused | None | achhar.kalia | [('is_paused', 'false'), ('dag_id', 'resdex-usage-mis-w')]
-- | -- | -- | -- | -- | --
2023-06-08, 17:53:02 | None | paused | None | pawan.shaw@naukri.com | [('is_paused', 'true'), ('dag_id', 'resdex-usage-mis-w')]

![image](https://github.com/apache/airflow/assets/49907838/5696c234-900e-4c45-adab-093db58aeb53)

### What you think should happen instead

when we pause, it should say its paused, when we unpause or resume, it should give message that dag is in unpause or resume state.

### How to reproduce

try, for me this is still live problem in 2.5.1

### Operating System

centos 7

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by achharKalia** [comment]
hi, ANy update on the issue,

**Comment by achharKalia** [comment]
yes, I want to open PR.

**Comment by potiuk** [comment]
Assigned you then :)

**Comment by achharKalia** [comment]
any luck you are able to find.

**Comment by gustavohwulee** [comment]
not sure if this is related but in this version 2.5.1 when we try to pause a dag programatically the value is not logged to the audit logs if it runs by the scheduler.

**Comment by eladkal** [comment]
Able to reproduce this on main branch

**Comment by alephmelo** [comment]
@eladkal Would you be able to review the PR I opened a few days ago? 🙏

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/36182
