### ISSUE TITLE
Auto-refresh turn off before updating status of MAPPED tasks

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#31870]
### Apache Airflow version

2.6.1

### What happened

when I trigger a new dag_run , the auto-refresh work , but turn off before all the mapped task get the final status

### What you think should happen instead

auto-refresh should refresh one last time the mapped task status before turn off

### How to reproduce

[Screencast from 13-06-2023 11:28:31.webm](https://github.com/apache/airflow/assets/10202690/39f88286-376d-402f-8ad3-c70b95b45965)

### Operating System

ubuntu 22.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I have been meaning redo [this PR](https://github.com/apache/airflow/pull/23805/files). With that we can fix this too.
