### ISSUE TITLE
DatabricksSubmitRunOperator libraries parameter has incorrect type

### ISSUE THREAD

**Issue by jlaneve** [apache/airflow#31877]
### Apache Airflow version

2.6.1

### What happened

The type of the libraries field in the DatabricksSubmitRunOperator is incorrect. According to the Databricks docs, the values should look more like:

```python
[
    {"pypi": {"package": "simplejson"}},
    {"pypi": {"package": "Faker"}},
]
```

as opposed to what the type hint implies:

```python
[
    {"pypi": "simplejson"},
    {"pypi":  "Faker"},
]
```

https://github.com/apache/airflow/blob/providers-databricks/4.2.0/airflow/providers/databricks/operators/databricks.py#L306

### How to reproduce

n/a

### Operating System

macOS

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc: @alexott

**Comment by phanikumv** [comment]
I will check this
