### ISSUE TITLE
Incorrect audience argument in Google OpenID authentication doc

### ISSUE THREAD

**Issue by sumeshpremraj** [apache/airflow#31891]
### What do you see as an issue?

I followed the [Google OpenID authentication doc](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/api-auth-backend/google-openid.html) and got this error:

```
$ ID_TOKEN="$(gcloud auth print-identity-token "--audience=${AUDIENCE}")"
ERROR: (gcloud.auth.print-identity-token) unrecognized arguments: --audience=759115288429-c1v16874eprg4455kt1di902b3vkjho2.apps.googleusercontent.com (did you mean '--audiences'?)

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
```

Perhaps the gcloud CLI parameter changed since this doc was written.

### Solving the problem

Update the CLI argument in the doc.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
@sumeshpremraj added you as assignee as you already submitted a PR for this :)

**Comment by laurajsdias** [comment]
hey @sumeshpremraj, were you able to connect to Airflow API using a Google account?

**Comment by sumeshpremraj** [comment]
> hey [@sumeshpremraj](https://github.com/sumeshpremraj), were you able to connect to Airflow API using a Google account?

See my linked PR for updating documentation, it's to fix the command line argument

**Comment by laurajsdias** [comment]
> > hey [@sumeshpremraj](https://github.com/sumeshpremraj), were you able to connect to Airflow API using a Google account?
> 
> See my linked PR for updating documentation, it's to fix the command line argument

hey, thanks for replying. Yeah, I'm using the correct `audiences` flag, but getting 401 unauthorized. I wanna know what you did to authenticate to the Airflow API using Google OpenID. 

I have a support request open here if you can take a look when you have some time, I would really appreciate the help: https://github.com/apache/airflow/discussions/48055
