### ISSUE TITLE
Add `--use-airflow-version` option to `breeze testing tests` command

### ISSUE THREAD

**Issue by vincbeck** [apache/airflow#31907]
### Description

The option `--use-airflow-version` is available under the command `start-airflow` in `Breeze`. As an example, this is used when testing a release candidate as specified in [documentation](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_AIRFLOW.md#verify-release-candidates-by-contributors): `breeze start-airflow --use-airflow-version <VERSION>rc<X> --python 3.8 --backend postgres`.

The idea I have is to add that option as well under the command `testing tests` in `Breeze`.

### Use case/motivation

Having the option `--use-airflow-version` available under the command `testing tests` in `Breeze` would make it possible to  run system tests against a specific version of Airflow and provider. This could be helpful when releasing new version of Airflow and Airflow providers. As such, providers could run all system tests of their provider package on demand and share these results (somehow, a dashboard?, another way?) to the community/release manager. This would not replace the manual testing already in place that is needed when releasing such new version but would give more information/pointers to the release manager.

Before submitting a PR, I wanted to have first some feedbacks about this idea. This might not be possible? This might not be a good idea? This might not be useful at all?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
That might be possible and rather useful.

One difficulty is tha the "--use-airflow-version" automatically removes all the airflow sources when entering breeze (by implying --mount-sources none)  and installs airflow using Pypi. 

So nn order to be able to run system tests, you would have to add another flag `--mount-sources system-tests" ?) and mount the sources to inside breeze. That **should** work in principle I think. Also what would be useful in this case could be

```
breeze shell --use-airflow-version .... --mount-sources system-tests
```

And then you could manually run the tests as needed

**Comment by vincbeck** [comment]
Cool! Thanks for the infos. However, here are my findings:

When I run `breeze shell --mount-sources remove`, `/opt/airflow/tests` is actually mounted and contains the whole `tests` directory. Is that a bug? Because of that, when I run `breeze shell --use-airflow-version 2.6.1`, I can successfully trigger a system test using the `pytest` command. Should I count on that or we should fix the bug (if this is confirmed it is a bug) at the first place and thus, introduce a new value for the option `--mount-sources` as you mentioned

**Comment by potiuk** [comment]
Ah... Cool., It's an unintended bug which turned into feature then.

Indeed when you look at https://github.com/apache/airflow/blob/main/scripts/ci/docker-compose/remove-sources.yml - only "airflow" folder is removed in case of `--mount-sources remove`

more context:

Generally when you pass flags to shell/testing/start-airflow breeze decides which docker-compose files to ... well compose when it runs breeze. Docker compose has been designed in the way that it allows to specify multiple compose files and docker-compose merges those files together. In thos case the "remove-sources.yml` adds mounting of the "empty" directory which is (you guessed .... empty) to "/opt/airflow/airflow" (which is where `airflow` folder in sources is mapped by default. 

So yes. Seems even easier than I thought.

**Comment by potiuk** [comment]
No. It's ok. `tests` have no impact on what's installed, so it's ok to keep them
