### ISSUE TITLE
execution_date backward compatibility between Airflow1 and Airflow2

### ISSUE THREAD

**Issue by ksundeepsatya** [apache/airflow#31908]
### Apache Airflow version

2.6.1

### What happened

We are trying to upgrade from Airflow 1.10.15 to 2.5.1 and noticed an issue with execution_date. `execution_date` in Airflow 1.10.15 execution_date in Airflow1 at the end of time interval the DAG schedule. In Airflow 2.5.1 it is start time of time interval the DAG schedule.
Example: 
Schedule: "*/15 * * * *"

**Airflow 1.10.15:**

execution_date | 2023-06-14T17:45:00+00:00
-- | --
queued_dttm | 2023-06-14 17:45:09.065412+00:00
start_date | 2023-06-14 17:45:26.611351+00:00

**Airflow 2.5.1:**

execution_date | 2023-06-14 17:30:00+00:00
-- | --
start_date | 2023-06-14, 17:45:04
queued_dttm | 2023-06-14, 17:45:01
Data interval start | 2023-06-14, 17:30:00 UTC
Data interval end | 2023-06-14, 17:45:00 UTC

Notice the 15 min difference in execution_Date. There is no Data Interval end in Airflow1 but, for sake of comparison, in Airflow1 execution_date is equal to `Data interval end`  and in Airflow2 it is `Data interval start`

execution_date is deprecated in Airflow2 and logical_date is supposed to be used. But, have taken dependency on execution_date in our code. It would be good to maintain backward compatibility. This change in behavior was introduced in Airflow 2.2 at part of [AIP-39](https://github.com/apache/airflow/projects/10)

This particular [line](https://github.com/apache/airflow/blob/5dd690b57a20ca944deb8d96e89ec6ae6161afeb/airflow/timetables/base.py#LL94C1-L100C40) of code could be issue (call chain: [create_dag_run](https://github.com/apache/airflow/blob/5dd690b57a20ca944deb8d96e89ec6ae6161afeb/airflow/jobs/scheduler_job.py#LL873C21-L873C58) -> [next_dagrun_info](https://github.com/apache/airflow/blob/5dd690b57a20ca944deb8d96e89ec6ae6161afeb/airflow/models/dag.py#L717) -> [next_dagrun_info](https://github.com/apache/airflow/blob/5dd690b57a20ca944deb8d96e89ec6ae6161afeb/airflow/timetables/interval.py#L90) ).  With the change from just CRON based schedule to timetable based schedule, just a single date for execution was not sufficient to understand start and end date of a schedule. Primary logic with in scheduling shifted to Data interval start and Data interval end and execution date is set to the newly introduced start date.
Compare that with code in Airflow 2.1.1 when there was only CRON schedule, execution date is set to next schedule run happen, which is nothing but end time of cron schedule prior to 2.2.0: this line of [code](https://github.com/apache/airflow/blob/614858fb7d443880451e6111b27fdaf942f563a4/airflow/models/dag.py#L484). (call chain: [create_dag_run](https://github.com/apache/airflow/blob/614858fb7d443880451e6111b27fdaf942f563a4/airflow/jobs/scheduler_job.py#L1026) -> [next_dagrun_info](https://github.com/apache/airflow/blob/614858fb7d443880451e6111b27fdaf942f563a4/airflow/models/dag.py#L539) -> [next_dagrun_after_date](https://github.com/apache/airflow/blob/614858fb7d443880451e6111b27fdaf942f563a4/airflow/models/dag.py#LL595C30-L595C30) ). Though execution_date is not explicitly set to end date, next schedule run is current run+delta.

**Proposed fix**
Changing this line of [code](https://github.com/apache/airflow/blob/5dd690b57a20ca944deb8d96e89ec6ae6161afeb/airflow/timetables/base.py#LL100C3-L100C40) to
`return self.data_interval.end`

### How to reproduce

Run sam DAG in Airflow 1 and Airflow 2 and notice the execution_date difference for the DAGs that are queued at same time

Eg DAG
```from datetime import timedelta

from airflow import DAG
from airflow.utils.dates import days_ago

try:
    from airflow.operators.bash import BashOperator
except ModuleNotFoundError:
    from airflow.operators.bash_operator import BashOperator


default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "email": ["test@test.com"],
    "email_on_failure": True,
    "execution_timeout": timedelta(minutes=5),
}


with DAG(
    "rollout_simple_dag",
    default_args=default_args,
    description="An example DAG",
    schedule_interval="*/15 * * * *",
    start_date=days_ago(2),
    catchup=False,
) as dag:
    task1 = BashOperator(
        task_id="run_data_task",
        dag=dag,
        bash_command="echo Hello"
    )
```

### Operating System

Ubuntu 18.04.6 LTS (Bionic Beaver)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by utkarsharma2** [comment]
AFAIK, Upgrading to a major version will such issues since all the breaking changes are deferred to a major release. I'm not sure if we can maintain such backward compatibility. Maybe @uranusjr can chime in?

**Comment by ksundeepsatya** [comment]
In fact this is not even Airflow1 to Airflow2 compatibility. `execution_date` from Airflow2.1.4 to Airflow2.2.0 is broken as well

**Comment by utkarsharma2** [comment]
@ksundeepsatya Can you please share an example for Airflow2.1.4 to Airflow2.2.0 issue?

**Comment by ksundeepsatya** [comment]
Same as mentioned in the issue. breaking change was introduced in 2.2.0 version. This is as part of [AIP-39](https://github.com/apache/airflow/projects/10). [This](https://github.com/apache/airflow/commit/4556828dccba2df0ab26b0aeeb26d0a30944da6f) and subsequent changes that went in as part of 2.2.0 release

**Comment by utkarsharma2** [comment]
Ya, I think Airflow2.1.4 to Airflow2.2.0 issue should not be there. I'll let other folks tagged earlier comment on it, they have more context about the changes done.

**Comment by uranusjr** [comment]
> `execution_date` in Airflow 1.10.15 execution_date in Airflow1 at the end of time interval the DAG schedule.

I believe this has _never_ been the case, the only execution date has always been the start of an interval. A real example is most definitely needed.

**Comment by ksundeepsatya** [comment]
I would like to apologize the community here. Looks like internally we have forked Airflow1 to modify the behavior of execution date in Airflow1 to set execution to end time of time interval. In community version of Airflow1 it is set to start time. This bug is incorrect. So closing it

**Comment by uranusjr** [comment]
For completeness, note that Airflow 2.2 introduces timetable to better costomise scheduling logic, so you might not need to fork anymore to achieve the behaviour you need (depends on what you need exactly, of course).
