### ISSUE TITLE
Tasks stuck in queued state

### ISSUE THREAD

**Issue by NXDnixiaodong** [apache/airflow#31929]
### Apache Airflow version

2.6.1

### What happened

Why are most tasks queued？And even if some running tasks are displayed in the queued state in the k8s cluster

### What you think should happen instead

I think there should be about a hundred tasks running at the same time, but according to my observation, there are only a maximum of forty tasks, and in most cases, only 20 to 30 tasks are running

### How to reproduce

Here are some of my configurations：
```bash
airflow 2.5.1
k8s 1.18.0
executor: KubernetesExecutor 
```
The k8s cluster has one master node and three node nodes

### Operating System

master:Centos7.9/node:Ubuntu20.04

### Deployment

Official Apache Airflow Helm Chart

### Anything else

Simply building a K8S cluster and deploying Airflow should be able to replicate without requiring special operations

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by acmh** [comment]
Since it seems the issue can be consistently replicated, have you tried to reduce an localize the source of the issue? Or could you please provide more input (e.g logs, airflow conf)?
