### ISSUE TITLE
Add support for Feishu notification  

### ISSUE THREAD

**Issue by john8628** [apache/airflow#31994]
### Description

Add support for Feishu notification to improve Airflow's ability to notify failures of DAGs.

### Use case/motivation

Recently we upgraded Airflow 1.10.7 to 2.5.3 in production. During the upgrade, we encountered issues with DAG failure notifications. We noticed that recent versions of Airflow introduced a notifier to support richer notification methods. However, our team commonly uses Feishu for communication, and Airflow's notifier currently does not support Feishu notification.
Therefore, we propose this feature request and hope that Airflow can support Feishu notification. This can allow Airflow to notify relevant personnel through Feishu when a DAG fails, improving fault detection and handling efficiency.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by utkarsharma2** [comment]
Assigned it to you :)

**Comment by utkarsharma2** [comment]
I think you would need to add a provider for this feature. It's very similar to a PR I recently raised, referring to it might be helpful - https://github.com/apache/airflow/pull/31533

**Comment by eladkal** [comment]
We have policy for what needs to be done to add official provider.
Please follow procedure listed on https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers
before raising PR. If discussion and vote passes then feel free to open PR (no need for GitHub issue)
I'm closing this issue as we don't have a community task here.
