### ISSUE TITLE
WARNING - Model file does not exist

### ISSUE THREAD

**Issue by arjunanan6** [apache/airflow#32026]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow v2.6.0 w/KubernetesExecutor

At this point, it is just a cosmetic issue since everything works as expected. I'm seeing this warning on all of my tasks:

`[2023-06-20, 11:40:18 UTC] {pod_generator.py:529} WARNING - Model file /opt/airflow/pod_templates/pod_template_file.yaml does not exist`

But the file does exist, as shown in the warning message as it managed to get the path from `kube_config` and I can use yaml.safe_load on it if I were to shell into the pod, or import `deserialize_model_file` from pod_generator.py. What could be going on here? 

### What you think should happen instead

The warning should not be printed as the file does exist.

### How to reproduce

Just execute any task.

### Operating System

Debian GNU/Linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Deployed on AKS with official helm chart.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
> since everything works as expected

What do you mean by works as expected? does it load the configurations from the `pod_template_file`?

**Comment by arjunanan6** [comment]
I mean that the pods do get spun up anyway, and tasks are executed as expected. It's just that this warning appears first and doesn't make sense. 

I think despite the warning it works because of:
https://github.com/apache/airflow/blob/8f65aee8f3c4dfdd6c4195d97f57f4267d37c209/airflow/kubernetes/pod_generator.py#LL131C1-L134C30
