### ISSUE TITLE
Failure to run all DAGs for Airflow in Kubernetes

### ISSUE THREAD

**Issue by xiankgx** [apache/airflow#32039]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi, we are running Airflow on Kubernetes on AWS EKS.
It has been running for several years issues. 

All of a sudden it seems none of the DAG runs work and trying to get the logs results in this.

Please help, there are much DAG runs scheduled daily and this error is catastrophic.

*** Falling back to local log
*** Trying to get logs (last 100 lines) from worker pod  ***

*** Unable to fetch logs from worker pod  ***
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '3bda0e6f-0ea8-4c2b-a950-20a21ed162f0', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 21 Jun 2023 01:35:12 GMT', 'Content-Length': '136'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"name must be provided","reason":"BadRequest","code":400}\n'

### What you think should happen instead

Not sure what happened.

### How to reproduce

Unsure

### Operating System

Kubernetes

### Versions of Apache Airflow Providers

Unsure

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Kubernetes

### Anything else

No right now

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xiankgx** [comment]
![image](https://github.com/apache/airflow/assets/4113258/013e6535-7793-41d5-b617-d0121579310f)

Trying to restart the scheduler and it just seems to keep restarting. What can I do?

**Comment by arjunanan6** [comment]
It looks like your ClusterRole might be broken. I'll take a look at our config and get back to you.

**Comment by hussein-awala** [comment]
Are you using the official helm chart or bitnami chart?
Which executor are you using? is it KubernetesExecutor?
Are you using remote logging? If not, do you have a shared persistent volume between the different services?

I convert it to discussion, and we can reopen it if needed.
