### ISSUE TITLE
All DAGs file are parsing while executing some "airflow tasks" cli command

### ISSUE THREAD

**Issue by vidyapanchalZS** [apache/airflow#32071]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello ,

We were trying to execute airflow CLI commands for "airflow tasks" in MWAA. While testing these commands , we observed that below "airflow tasks" cli command are parsing parsing all DAGs file then execute provided airflow tasks command.

**Commands** : 
airflow tasks clear
airflow tasks failed-deps
airflow tasks run
airflow tasks test  

### What you think should happen instead

We are expecting that when to execute "airflow tasks" cli command, it should only parse DAG name and task name provided in the command and not parse DAG lists followed by task list.

### How to reproduce

1. We created web logic token to access web server 
2. After that, we used python script to run "airflow tasks" cli commands.

### Operating System

Amazon Linux

### Versions of Apache Airflow Providers

Airflow version 2.2.2

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
In the current implementation of the `tasks run` command, we load the DagBag from the dags folder (or the directory specified using the `--subdir` flag). I'm currently working on a new feature that adds an option to load the DagBag from the Metadata DB instead of parsing the DAG files. You can find more details about this feature in #32038.

I close the issue because it duplicates the other one you have created #32020

**Comment by vidyapanchalZS** [comment]
Hello Hussein,

thank you for looking into this request. In this request , i also mentioned some other "airflow tasks" cli command which giving similar output as "airflow tasks run" command. 

Requesting you to also add below commands into your feature request.

airflow tasks clear
airflow tasks failed-deps
airflow tasks test
