### ISSUE TITLE
Missing placeholder in add connection screen in `extra` field option

### ISSUE THREAD

**Issue by Adaverse** [apache/airflow#32081]
### Apache Airflow version

2.6.2

### What happened

On version 2.5.3

![extra-2 5 3](https://github.com/apache/airflow/assets/35839624/bd0823a4-6f42-47f2-94bf-a399e16243fc)

On version >= 2.6.0

![extra-2 6 2](https://github.com/apache/airflow/assets/35839624/684c028f-bb09-47ad-9624-b0528b8267f8)

It's important to have these placeholders to give ideas to the users on optional fields. We are also missing the resizer.

### How to reproduce

Try viewing add connection screen containing extra option in the field

### Operating System

.

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
cc: @pierrejeambrun

It could be related to #29946

**Comment by pierrejeambrun** [comment]
I just took a look on main and things seem to work as expected must have been fixed by the time.

Closing. Feel free to re-open if needed.

![Screenshot 2024-09-05 at 10 49 12](https://github.com/user-attachments/assets/9ec18c94-f7aa-4c62-b80a-639d02b53588)
