### ISSUE TITLE
Add URI to dbt Cloud Job in Airflow logs after DbtCloudRunJobOperator is triggered

### ISSUE THREAD

**Issue by boxysean** [apache/airflow#32094]
### Description

I would kindly request to add the URI to dbt Cloud Job in Airflow logs after DbtCloudRunJobOperator is triggered, to make it easy for Airflow operators to see the dbt Cloud job status and logs within the dbt Cloud platform.

### Use case/motivation

I'm trying to achieve easier operations and understanding for Airflow engineers who have dbt Cloud operators in their DAGs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I see that there is an operator link for this operator (`DbtCloudRunJobOperatorLink`), why do you think this is not sufficient for your needs?
