### ISSUE TITLE
SLA miss alert are triggered incorrectly 

### ISSUE THREAD

**Issue by sawant-ankeeta** [apache/airflow#32138]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are using airflow 2.4.3 version of Airflow. 

Incorrect SLA miss alerts are being triggered for production Jobs. Despite the job being in a running state and not exceeding any SLA thresholds, we receive notifications on the Slack channel and observe entries in the "SLA misses" tab in the browser.

The SLA miss alert that was triggered for the 10.05 PM run should not have occurred, as the job was in a running state and did not exceed any SLA thresholds. The threshold was set to 5 hours, but the job typically takes around 2 hours to complete.

<img width="1664" alt="Screenshot 2023-06-26 at 2 37 53 PM" src="https://github.com/apache/airflow/assets/97666785/800d8bdc-edb8-44f2-a28c-34586fa60083">
<img width="1696" alt="Screenshot 2023-06-26 at 2 45 04 PM" src="https://github.com/apache/airflow/assets/97666785/97ad17fc-f88a-4c28-b1d4-12067de40b76">
<img width="1574" alt="Screenshot 2023-06-26 at 2 45 17 PM" src="https://github.com/apache/airflow/assets/97666785/90c64ddd-cc4a-43ac-bf08-a8fb2740c908">
<img width="779" alt="Screenshot 2023-06-26 at 2 45 31 PM" src="https://github.com/apache/airflow/assets/97666785/cbf551c8-84ff-4fd3-bbb5-13d4201826ae">
<img width="775" alt="Screenshot 2023-06-26 at 2 47 19 PM" src="https://github.com/apache/airflow/assets/97666785/07e525d3-c3c2-4f68-add8-1bb5194a1827">

This is mostly seen when previous run of the job was manually triggered from the airflow UI. 

### What you think should happen instead

SLA miss alert should not have triggered for 10.05pm run since job was in running state and not exceeded any SLA threshold.

### How to reproduce

This is mostly seen when previous run of the job was manually triggered from the airflow UI. 

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yep. The SLA feature is generally quite broken and until it is fixed, I think there will be cases like that popping up. There is work in progress to replace the SLA with a better design/implementation - discussed in https://cwiki.apache.org/confluence/display/AIRFLOW/%5BWIP%5D+AIP-57+SLA+as+a+DAG-Level+Feature

**Comment by potiuk** [comment]
You can see discussion in the doc for some scenarios that are problematic in the current solution,  I think your scenario is among them

**Comment by eladkal** [comment]
I'm going to close this one as the SLA feature is currently in development and should solve the pains around the old SLA mechanism.
