### ISSUE TITLE
Show dataset extra field in UI

### ISSUE THREAD

**Issue by easontm** [apache/airflow#32145]
### Description

When you're on the UI page for a specific dataset `datasets?uri=MY_DATASET`, I think it would be nice to show the `extra` dictionary.

### Use case/motivation

I sometimes attach meta information to a dataset, but it can only by consuming tasks or by going directly to the meta DB. I would like to be able to view it from the UI.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We already return `extra` in the API request so its just a matter of rendering it inside of a `<code>` view.

**Comment by phanikumv** [comment]
I will work on this

**Comment by darshilparmar** [comment]
Hi, @phanikumv can I work with you on this?

**Comment by phanikumv** [comment]
sure Darshil

**Comment by jscheffl** [comment]
This is already implemented, Dataset extra is displayed on UI.
