### ISSUE TITLE
Metrics - Encrypted OTel Endpoint?

### ISSUE THREAD

**Issue by ferruzzi** [apache/airflow#32164]
### Apache Airflow version

2.6.2

### What happened

I left this as a TODO and will get t it eventually, but if someone wants to look into it before I get time, this may be an easy one:

We are creating an OTLPMetricExporter endpoint with `http` [here](https://github.com/apache/airflow/blob/main/airflow/metrics/otel_logger.py#L400) and should look into whether we can make this work with `https`.

### Definition of Done:
Either implement HTTPS or replace the TODO with a reference citing why we can not.

I am submitting this as an Issue since I will be a little distracted for the next bit and figured someone may be able to have a look in the meantime. Please do not assign it to me, I'll get it when I can is nobody else does.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by deepchand** [comment]
Hi, can I work on this? I am new to Open source contribution but have good knowledge of Apache airflow and since it has been marked as a good first issue.
I would like to give it a shot.

**Comment by ferruzzi** [comment]
All yours!   Thanks for having a look!

**Comment by deepchand** [comment]
JFYI, I am currently working on implementing the suggested changes, but it might take a little longer as I am relatively new to this particular aspect.

**Comment by ferruzzi** [comment]
No rush at all, thanks for taking it on.

**Comment by ferruzzi** [comment]
Thanks @deepchand !
