### ISSUE TITLE
Async S3 support needed

### ISSUE THREAD

**Issue by yjdlau** [apache/airflow#32174]
### Description

We need async support for S3 facilities for use in our Triggers.
We see AwsBaseAsyncHook was introduced  in [this commit](https://github.com/apache/airflow/commit/cf77c3b96609aa8c260566274d54b06eb38c8100)  ([PR 28850](https://github.com/apache/airflow/pull/28850)) merged on [2023-03-14](https://github.com/apache/airflow/pull/28850). 

However in https://github.com/apache/airflow/pull/31610 , AwsBaseAsyncHook was marked Deprecated by @pankajastro and subsequently approved by @vincbeck .

I would like to know:
- on what basis do you determine this class is not used? There has been no discussions in the PR.
- from a user stance, providing a new functionality then removing it a few months later is not very good practice. 
- is async S3 operations going to be supported ? We have code based on this and deprecating this will break our code.

Many thanks, particularly to the two gentlemen I named above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment]
We decided to use boto waiter for aws deferrable operator and not create a separate async hook. 
You can check some examples here https://github.com/apache/airflow/tree/main/airflow/providers/amazon/aws/triggers how we are creating triggers. particular line https://github.com/apache/airflow/blob/688f91b330addbc88a5bbda2f0e29cbed2313678/airflow/providers/amazon/aws/triggers/batch.py#L76

**Comment by yjdlau** [comment]
@pankajastro Could you please add context to your PR and discussion, particularly the link to the discussion. From your PR it looks like you're killing a feature without any discussion.

**Comment by pankajastro** [comment]
> @pankajastro Could you please add context to your PR and discussion, particularly the link to the discussion. From your PR it looks like you're killing a feature without any discussion.

we have a discussion and PR https://github.com/apache/airflow/pull/30032 where we decided to use the waiter and not create a separate hook async operator.

**Comment by pankajastro** [comment]
>  From your PR it looks like you're killing a feature without any discussion.

FYI: I added AwsBaseAsyncHook hook

**Comment by yjdlau** [comment]
Got it. That clears things up. Closing issue.
