### ISSUE TITLE
Another scheduler question

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#322]
Sorry - I've tried searching but cant find the answer.

I understand that the scheduler takes a timedelta, but is it possible to some how schedule dags based on day of week rather than frequency?

I'd like to have a DAG executed every friday. I could calculate a time delta to do this, but am I right in thinking that unless the scheduler is restarted this wont get re-evaluated.

For example if i do the following:

```
today = date.today()
friday = today + timedelta( (4-today.weekday()) % 7 )
schedule_interval = friday-today
```

I _think_ the first run will work, but future runs will not as they'll used a timedelta based on when the scheduler started.

**Comment by mistercrunch** [comment]
As long as you start_date, or latest run is a `Friday`, the schedule_interval will get applied to it and it should be all good. One thing to keep in mind is that much like in the daily schedule_interval context, `2015-01-01` run is for the `2015-01-01` to `2015-01-02` and gets triggered at 00:00 on `2015-01-02`, on a weekly run labeled `2015-01-01` will get kicked off on `2015-01-08`, and that run should represent that period.

**Comment by mistercrunch** [comment]
Please reopen if you have more questions, I'm trying to cleanup the issue log
