### ISSUE TITLE
AIP-56 - Documentation

### ISSUE THREAD

**Issue by vincbeck** [apache/airflow#32211]
Some documentation needs to be written to explain what is an auth manager and some guidance on how to create concrete auth managers

**Comment by SridharCR** [comment]
I'm interested in this item, will look into the code and do a PR. Kindly assign this one to me

**Comment by vincbeck** [comment]
Happy to. Though, I was thinking we should work on this task later in the project once most of the code will be written, it might be easier. What do you think?

**Comment by SridharCR** [comment]
Yeah sure, makes sense! will work on this, once the base code is merged.

**Comment by vincbeck** [comment]
Amazing!
