### ISSUE TITLE
airflow dag missing from yesterday 28th of June 2023

### ISSUE THREAD

**Issue by ThiyagarajanRajalingam** [apache/airflow#32237]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

airflow dag missing from yesterday 28th of June 2023
airflow version 2.0.2

### How to reproduce

airflow dag missing from yesterday 28th of June 2023
airflow version 2.0.2

### Operating System

windows

### Versions of Apache Airflow Providers

airflow dag missing from yesterday 28th of June 2023
airflow version 2.0.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

airflow dag missing from yesterday 28th of June 2023
airflow version 2.0.2

### Anything else

airflow dag missing from yesterday 28th of June 2023
airflow version 2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
To create an issue, you need to provide all the information and the context of your issue, and an example to reproduce it.

I close the issue and we can reopen it when you update the description.
