### ISSUE TITLE
execution_date column not found in airflow db 

### ISSUE THREAD

**Issue by iagochoa** [apache/airflow#32266]
### Body

**Apache Airflow version**
2.5.1

**Operating System**
AWS EKS

**Deployment**
HELM Chart 1.9.0

**Deployment details**
Deployed using ArgoCD.

**What happened**
When I try to get data via grafana query it is listed that some columns do not exist.

**Example error:**
`db query error: pq: column task_fail.execution_date does not exist`

**Used query**
```
WITH task_fails_to_remove AS (
  SELECT 
    task_fail.dag_id,
    task_fail.task_id,
    task_fail.execution_date
  FROM
    task_fail
  LEFT JOIN 
    dag_run ON 
    dag_run.dag_id = task_fail.dag_id 
    AND dag_run.execution_date = task_fail.execution_date
  WHERE
    dag_run.run_id IS NULL
)
DELETE FROM
    task_fail
USING 
    task_fails_to_remove
WHERE (
    task_fail.dag_id = task_fails_to_remove.dag_id
    AND task_fail.task_id = task_fails_to_remove.task_id
    AND task_fail.execution_date = task_fails_to_remove.execution_date
);

```
**What I've tried so far**
1) Run ` airflow db upgrade`
2) Run `airflow db clean`
3) Run `airflow db check-migrations`
4) Tried to apply this [GitHub issue](https://github.com/apache/airflow/issues/18894) solution

**Additional details:** 
- I didn't change anytime the airflow version on my deployment.
- I used the [official helm ](https://airflow.apache.org/docs/helm-chart/stable/index.html)deployment guide (mentions some changes to run migrations on argo deployment)
- In my first time deploying I lost the fernetKey and deployed again, so I used `airflow db reset` to rebuild the database.

Any tips on how to solve this?

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
This is some kind of customization of yours. which done outside of Airflow.  Possibly those are some 3rd-party extensions or maintenance scripts you are using - they are definitely not part of airlfow and they are not guaranteed to work if they are accessign airflow DB database. As explained in https://airflow.apache.org/docs/apache-airflow/stable/public-airflow-interface.html#what-is-not-part-of-the-public-interface-of-apache-airflow  DB structure is not public interface of airflow, so you cannot expect  3rd-party components accessing the DB to work.

```
WITH  task_fails_to_remove
```

You need to replace whatever you were doing it with something that is included in Airflow (for example when people used 3rd party maintenance dags  in the past, there is built-in `airflow db clean` command) or use REST API if you want to interact with Ariflow.

**Comment by iagochoa** [comment]
Thanks @potiuk , I'll keep that in mind.
