### ISSUE TITLE
Add DagProcessor status to health endpoint.

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#32279]
### Description

Add DagProcessor status including latest heartbeat to health endpoint similar to Triggerer status added recently. Related PRs.

https://github.com/apache/airflow/pull/31529
https://github.com/apache/airflow/pull/27755

### Use case/motivation

It helps in dag processor monitoring 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by utkarsharma2** [comment]
@tirkarthi I don't see any downside to adding this information in Healthcheck. However, DagProcessor is not a separate component as opposed to the trigger. If DagProcessor is having some issues it won't affect airflow as a whole. It's probably an issue with a dag and if an instance of airflow is shared with multiple teams, they won't be interested to know if some dag that they don't own has some issues. WDYT?

**Comment by tirkarthi** [comment]
It's an issue from the perspective that updates to dag or new dags won't be picked up by UI and scheduler till the dag processor is healthy.

**Comment by utkarsharma2** [comment]
On further looking into this I think you can run DagProcessor as a separate process, having this feature would certainly help. 
Ref - https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dagfile-processing.html

**Comment by eladkal** [comment]
We also have a task for health endpoints for workers https://github.com/apache/airflow/issues/17191
