### ISSUE TITLE
RedshiftDataOperator: Add support for Redshift serverless clusters

### ISSUE THREAD

**Issue by somil98** [apache/airflow#32280]
### Description

This feature adds support for Redshift Serverless clusters for the given operator.

### Use case/motivation

RedshiftDataOperator currently only supports provisioned clusters since it has the capability of adding `ClusterIdentifier` as a parameter but not `WorkgroupName`. The addition of this feature would help users to use this operator for their serverless cluster as well.

### Related issues

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
@shubham22

**Comment by shubham22** [comment]
Thanks for bringing this up @cw-somil. Valid concern and requires a minor update to the existing operator. We'll update here once the AWS team starts working on it. Meanwhile, others are welcome to work on it as well.

**Comment by ivica-k** [comment]
I'd like to take a stab at this one - Redshift Serverless offers $300 credits for the free trial so why not.

@shubham22 I may reach out to you via Slack just to get your team's opinion on the approach I took.
