### ISSUE TITLE
Move `AzureBlobStorageToGCSOperator` to the Google provider

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#32285]
### Body

https://github.com/apache/airflow/blob/94128303e17412315aacd529d75a2ef549cce1f5/airflow/providers/microsoft/azure/transfers/azure_blob_to_gcs.py#L31

is stored in the Azure provider but our [policy](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#naming-conventions-for-provider-packages) is that transfer operators of major clouds should be in the target provider (Google)

**The Task:**
Deprecate `AzureBlobStorageToGCSOperator` in Azure provider
Move `AzureBlobStorageToGCSOperator` to Google provider

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Adaverse** [comment]
Sure! I will take this up.
