### ISSUE TITLE
datetime.utcnow and datetime.utcfromtimestamp are deprecated in Python 3.12

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#32344]
### Apache Airflow version

2.6.2

### What happened

The usage of `datetime.utcnow` is deprecated in Python 3.12 and it can be replaced with `airflow.utils.timezone.utcnow` and a similar method can be introduced for utcfromtimestamp too in timezone module

> [datetime.datetime](https://docs.python.org/3.12/library/datetime.html#datetime.datetime)’s [utcnow()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow) and [utcfromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp) are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call [now()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.now) and [fromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.fromtimestamp) with the tz parameter set to [datetime.UTC](https://docs.python.org/3.12/library/datetime.html#datetime.UTC). (Contributed by Paul Ganssle in [gh-103857](https://github.com/python/cpython/issues/103857).)

### How to reproduce

```
./python                     
Python 3.13.0a0 (heads/main:58906213cc, Jul  3 2023, 21:54:53) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.utcnow()
<stdin>:1: DeprecationWarning: datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
datetime.datetime(2023, 7, 4, 12, 41, 45, 658447)
>>> datetime.datetime.utcfromtimestamp(10000)
<stdin>:1: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC).
datetime.datetime(1970, 1, 1, 2, 46, 40)
```

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I talked to Paul Ganssle a while ago and these two specifically have few caveats, you basically need to use the version without `utc` and make sure to always attach an appropriate timezone. Or since we already use Pendulum we can just use its `now(UTC)`. I’ll take a look at the PR once submitted though.

**Comment by tirkarthi** [comment]
`timezone.utcnow` that constructs current time without timezone and then uses `replace` to update the timezone. It is used in many places. There are also places where `datetime.utcnow()` is used that has no timezone and as per the linked cpython bug this leads to issues where this gets passed to timezone aware functions. My attempt would be to replace them with `timezone.utcnow` version. See also https://github.com/python/cpython/issues/81669#issuecomment-1093828742 for an example

**Comment by jens-scheffler-bosch** [comment]
I would not call it a bug though. It is rather an improvement as Python 3.12 is not officially supported yet. So a PR is appreciated but will be something like a feature to prepare for support Python 3.12++ in future releases.

**Comment by potiuk** [comment]
> I would not call it a bug though. It is rather an improvement as Python 3.12 is not officially supported yet. So a PR is appreciated but will be something like a feature to prepare for support Python 3.12++ in future releases.

yes

**Comment by Gui-FernandesBR** [comment]
Any updates on this one? 

Python 3.12 was released a few weeks ago.

The warning persists: 
```txt
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH = datetime.datetime.utcfromtimestamp(0)
```

This happens in this file of my environment (hope this helps): .venv\Lib\site-packages\dateutil\tz\tz.py

**Comment by tirkarthi** [comment]
Unfortunately, I don't have the bandwidth to proceed with the fix. If someone wants to use my work as base please feel free to check the changes at https://github.com/tirkarthi/airflow/tree/fix-datetime
