### ISSUE TITLE
Variable AIRFLOW__CORE__EXECUTOR value is hardcoded in pod template file

### ISSUE THREAD

**Issue by alex-sentsiurou** [apache/airflow#32364]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.3.2

### Kubernetes Version

1.21

### What happened

Hi Team,
In `chart/files/pod-template-file.kubernetes-helm-yaml` file env variable `AIRFLOW__CORE__EXECUTOR` is hardcoded to `LocalExecutor.` Other env variables are not hardcoded and can be dynamically added via values.yaml file.

### What you think should happen instead

Variable `AIRFLOW__CORE__EXECUTOR` in the pod template file should not be hardcoded (there is a possibility to add it via .`Values.<variable_name>`).

### How to reproduce

Install the helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yes. This is as expected and designed to be like that. 
Kubernetes executor uses Local Executor inside the task to run the task.

**Comment by alex-sentsiurou** [comment]
Thanks for quick feedback. So, it means that we must NOT change this variable value to anything else? We need to leverage `KubernetesExecutor.`

**Comment by potiuk** [comment]
Yes.
