### ISSUE TITLE
Unable to get mapped task xcom value via REST API. Getting MultipleResultsFound error

### ISSUE THREAD

**Issue by pvaling** [apache/airflow#32367]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow 2.3.4 (but actual code seems to have same behaviour).

I have mapped task with xcom value.

I want to get xcom value of particular instance or xcom values of all task instances.

I am using standard REST API method /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}

And it throws an error
`
  File &#34;/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py&#34;, line 2850, in one_or_none
    return self._iter().one_or_none()
  File &#34;/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py&#34;, line 1510, in one_or_none
    return self._only_one_row(
  File &#34;/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py&#34;, line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
`

Is it any way of getting xcom of mapped tasks via API?

### How to reproduce

Make dag with mapped task. Return xcom value in every task. Try to get xcom value via API.

### Operating System

ubuntu 20.04

### Deployment

Other

### Deployment details

Standard

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
The endpoint doesn't accept map_index. Would the fix be to allow map_index as query parameter defaulting to -1 for backwards compatibility through which users can get the relevant xcom? Another approach would be a new endpoint that has map_index in the url path but that wouldn't fix this issue though.

https://github.com/apache/airflow/blob/d3f0900bbb68bda36f81475bf64d83d51ee32b22/airflow/api_connexion/endpoints/xcom_endpoint.py#L85-L107

**Comment by pvaling** [comment]
I think that first approach is better (map_index in existing endpoint with fallback to -1).
