### ISSUE TITLE
SFTP Sensor as a decorator

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#32410]
### Description

I would like to write the sftp sensor as a task decorator

### Use case/motivation

Keep code style cohesive

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
You can just raise PR :)
No need to submit GitHub issue first

**Comment by frankcash** [comment]
Not sure I will be able to work on it unfortunately, but I might try to!  More than happy to close if this is an unwanted raised request

**Comment by Adaverse** [comment]
I can work on it!

**Comment by potiuk** [comment]
Assigned you
