### ISSUE TITLE
ERROR: Invalid requirement: "'apache-airflow==2.6.2'" with Python 3.10

### ISSUE THREAD

**Issue by SaqlainHussainShah** [apache/airflow#32418]
### Apache Airflow version

2.6.2

### What happened

I am installing airflow 2.6.2 with python 3.10 using `pip install 'apache-airflow==2.6.2' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.6.2/constraints-3.10.txt"` command and getting error ERROR: Invalid requirement: "'apache-airflow==2.6.2'"

### How to reproduce

Run `pip install 'apache-airflow==2.6.2' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.6.2/constraints-3.10.txt"` in visual studio code installed on windows 10 OS

### Operating System

Windows 10

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
1) Airflow does not work on Windows so what you are trying to do is not supported. We only support POSIX installation.
2) Your Windows shell is not stripping apostrophe and you are trying to install package that has apostrophes in name. You should understand the difference for Windows shell expansion.
