### ISSUE TITLE
Variable AIRFLOW__CORE__EXECUTOR value is hardcoded in pod template file causing few Jobs goes in LocalExecutor

### ISSUE THREAD

**Issue by jigs031** [apache/airflow#32416]
### Official Helm Chart version

1.6.0

### Apache Airflow version

2.3.1

### Kubernetes Version

1.21

### What happened

We have spined up the Airflow from Helm chart 1.6.0. We have defined AirflowExcecutor as "KubernetesExecutor" in our config map.

System works fine when number of parallel runs less, but when parallel runs increase - few of the PODS randomly runs on "LocalExecutor" and these task are not visible on Airflow DAG Run UI screen. After the long debugging we identified that it was dues to the environment variable "AIRFLOW__CORE__EXECUTOR " hard-coded to "LocalExecutor" in chart/files/pod-template-file.kubernetes-helm-yaml.

We tried to hard-coded as "KubernetesExecutor", then all the Jobs are working as expected. 

### What you think should happen instead

Like other configuration, Variable AIRFLOW__CORE__EXECUTOR in the pod template file should not be hardcoded (there is a possibility to add it via .Values.<variable_name>).

### How to reproduce

Install the helm chart and define - "AIRFLOW__CORE__EXECUTOR == "KubernetesExecutor" in ConfigMap.

Run single job multiple times (atleast 20+ runs) within 10 seconds. You may observe that - not all job instances are visible on the screen. If we go on Task level details -  you may find task are available but the Job are not register on Airflow UI/Database.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Kunernetes Executor ALWAYS uses LocalExecutor to execute tasks. This is why it is Hard-coded. The way how task in Kubernetes Executor's POD works is that it executes single task inside the POD using the LocalExecutor. This is designed and expected.

**Comment by jigs031** [comment]
Thanks Potiuk for response.
That might be true but, When we checked on Airflow Job Config it shows - "KubernetesExecutors" for most of the job but jobs which are not visible on UI are running with  LocalExecutor, LocalExecutor might not able to connect to Airflow DB.

Any reason why 1-2% are showing Executor as "LocalExecutor" while other are with "KubernetesExecutors"

**Comment by potiuk** [comment]
This is likely a different issue and not related to hard-coding of CORE__EXECUTOR. 

No idea why you had it, if you investigate it and produce a reproducible case, feel free to open a new issue.
