### ISSUE TITLE
Pydantic 2.0.2 warnings/errors causing issues (Airflow 2.6.2)

### ISSUE THREAD

**Issue by kulasbart** [apache/airflow#32431]
### Apache Airflow version

2.6.2

### What happened

When launching webserver, pydantic raised errors. Not sure if this is expected behavior or not. 

However, I was able to resolve the error/warning message by downgrading pydantic to 1.10.10

### How to reproduce

airflow webserver -p 8080

raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `dag_id = <class 'str'>`. All model fields require a type annotation; if `dag_id` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.0.2/u/model-field-missing-annotation

### Operating System

macos

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You should install airflow using constraints: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html (and before opening an issue it's worth checking if there are no similar issues). Just look for Pydantic.
