### ISSUE TITLE
Dag run timeout with timedelta value is rendered as [object object] in UI

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#32442]
### Apache Airflow version

main (development)

### What happened

Dag run timeout with timedelta value is rendered as [object object] in UI. It seems the data is fetched and string is used to render the value. timedelta is handled for schedule_interval which should also be done here.

![image](https://github.com/apache/airflow/assets/3972343/0a1e2257-4e7c-49a2-bde8-e9a796146cc5)

### What you think should happen instead

timedelta should be handled similar to how it's done in scheduleInterval value here.

https://github.com/apache/airflow/blob/e70bee00cd12ecf1462485a747c0e3296ef7d48c/airflow/www/static/js/dag/details/Dag.tsx#L278C2-L293

### How to reproduce

1. Create a dag with dag_run_timeout as timedelta value.
2. Visit the dag details tab in grid view to check dag_run_timeout

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sanjurm16** [comment]
Hello, can I pick this up?

**Comment by potiuk** [comment]
feel free

**Comment by sanjurm16** [comment]
cheers!

**Comment by sanjurm16** [comment]
@potiuk I have raised a PR. Please review and share your feedback if any. Let me know if you need any evidences or screenshot post fix
