### ISSUE TITLE
Possible issue with 2.6.3rc1 - '{run_id}' is invalid

### ISSUE THREAD

**Issue by lewijw** [apache/airflow#32459]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Our integration test passes with 2.6.2, but fails with 2.6.3rc1 with this message.  This might be our issue, but I thought I would let you know.   Our integration test uses the following id in the URL:

integration_test.sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad

In the same POST, this Name is passed into the body:

An instance of integration_test.sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad at 2023-07-07 20:06:57.64
2492 -0400 EDT

The new version seems to taking this Name over the dag id that is passed into the URL.  Here is the message:

    f"The provided run ID '{run_id}' is invalid. It does not match either "
airflow.exceptions.AirflowException: The provided run ID 'An instance of integration_test.
sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad at 2023-07-07 20:06:57.64
2492 -0400 EDT' is invalid. It does not match either the configured pattern: '^[A-Za-z0-9_
.~:+-]+$' or the built-in pattern: '^(?:manual|scheduled|dataset_triggered)__(?:\d{4}-\d{2
}-\d{2}T\d{2}:\d{2}:\d{2}\+00:00)$'
10.254.247.184 - Admin [08/Jul/2023:00:19:03 +0000] "POST /api/v1/dags/integration_test.sa
s_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad/dagRuns HTTP/1.1" 500 4535

### What you think should happen instead

It seems the Name in the body should not preempt the id in the URL. 

### How to reproduce

Do a POST /api/v1/dags/{id}/dagRuns with a space in the Name in the body.

### Operating System

RHEL8

### Versions of Apache Airflow Providers

None.

### Deployment

Other

### Deployment details

k8s with kustomize

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @ephraimbuddy

**Comment by ephraimbuddy** [comment]
Updating the config `[scheduler]allowed_run_id_pattern` will allow you to use any kind of `run_id`. It's not a breaking change

**Comment by lewijw** [comment]
That is interesting.  I did not know that was possible.  However, I think the bigger issue is that the Name in the body is being validated with the same validation intended for the id.  Is that intentional?

**Comment by potiuk** [comment]
> That is interesting. I did not know that was possible. However, I think the bigger issue is that the Name in the body is being validated with the same validation intended for the id. Is that intentional?

What do you mean by "Name in the body"?  As far as I can see the validation is only failing for `run_id` and there is no "Name" in the body? Or am I missing something?

**Comment by lewijw** [comment]
I am sorry I am not being clear.  The error message indicates that this string is the problem:

"An instance of integration_test.sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad at 2023-07-07 20:06:57.642492 -0400 EDT"

That string is being passed in as the Name in the body of the POST (that may be an error on our part).  The dag_id that is passed in the URL is a smaller string:

integration_test.sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad

Since the error message is mentioning the larger string that starts with "An instance", it looks like the Name is being subjected to the dag_id validation.

**Comment by potiuk** [comment]
> "An instance of integration_test.sas_po_hello_world_poc_flow-5cf6ded1-3949-44da-9f6b-9e59839d99ad at 2023-07-07 20:06:57.642492 -0400 EDT"
> That string is being passed in as the Name in the body of the POST (that may be an error on our part). The dag_id that is passed in the URL is a smaller string:

There is no "name" in the body. this string is passed as run_id

**Comment by potiuk** [comment]
Simply speaking - your `run_id` generated via integration test of yours "looks like" name, but this is an ID of the run. 

A bit more explanation why it has changed:

It used to be "free form", but it causes a lot of problem (including security issues) that's why we are limiting it to be follow a "real" id format (and you can define how your "id" should look like by providing your own regular exception in configuration).

**Comment by potiuk** [comment]
Converting this one to discussion in case more discussion is needed.
