### ISSUE TITLE
Login Failed when user password contain '$'

### ISSUE THREAD

**Issue by Rattnik** [apache/airflow#32504]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When user creating through cli or LDAP Auth with password contain '**$**' (dollar symbol), unable to log in with error "**Login Failed for user**"

### How to reproduce

`airflow users create -e "test@test.com" -f "Firstname" -l "Lastname" -p "aaa$aaa" -u "test-user" -r Viewer`

### Operating System

"Debian GNU/Linux 11 (bullseye)"

### Versions of Apache Airflow Providers

apache-airflow==2.5.3

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
It looks like a case of $a being interpolated by shell within double quotes and not an Airflow issue. Can you please try using single quotes '' from the shell for -p?
