### ISSUE TITLE
when manual trigger dagrun, airflow will  skip scheduled runs

### ISSUE THREAD

**Issue by itsallsame** [apache/airflow#32544]
### Apache Airflow version

2.6.3

### What happened

I'm using Airflow version 2.6.1 and facing this issue. My DAG is scheduled to run "@daily". I manually triggered the Dag run_id(manual__2023-07-03T16:30:00+00:00) and I expect it to be scheduled at 2023-07-03, but the DAG was not scheduled. 

my dag already runnig very long time at lower version airflow(2.3.4), it's work fine;

my dag config:
```python
dag_id = 'hive_dw_daily'

default_args = {
    'owner': 'someone',
    'depends_on_past': True,
    'start_date': datetime(2020, 12, 4),
    'retries': 10,
    'retry_delay': timedelta(minutes=15),
    'concurrency': 2,
    'pool': 'data_pool',
    'priority_weight': 100
}

with DAG(
    dag_id,
    schedule_interval = '30 16 * * *',
    catchup = False,
    default_args = default_args) as dag:
    
    ....
```

### How to reproduce

upgrade airflow to 2.6.1, then manul trigger a dag

### Operating System

centos7.6

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

python3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Could you please provide more details, logs, screenshots and evidences of what happens - showing historical dag-runs? This is not really actionable without those details.
