### ISSUE TITLE
Documentation Update to stop breeze environment  

### ISSUE THREAD

**Issue by darshilparmar** [apache/airflow#32588]
### What do you see as an issue?

Hello,
This is the first time I am contributing to open source I was trying to set up Airflow Dev Environment on my local computer (MacOS M1) and I found the issue in the documentation 

To stop the breeze environment the command mentioned in the [documentation](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst) is 

> breeze down

When I run the command I get the following error, looks like it has been changed to 

> breeze stop

![image](https://github.com/apache/airflow/assets/22773771/13a8672c-be9a-4ea3-b623-6c4043df5579)

### Solving the problem

There are three places found in the [doc](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst) where we can update
> breeze down 

to 

> breeze stop

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You have to checkout latest main - the "stop" command has been replaced with down command few months ago and you are likely checking out some old version/tag. Development for airlfow is always done in main and BREEZE docs are always describing "main" state.
