### ISSUE TITLE
Add Templating for logs PVC storageClassName

### ISSUE THREAD

**Issue by Natalique** [apache/airflow#32581]
### Description

I'm using EFS For different envs in EKS and I have a few different storage class
I need to pass airflow a templated storageClassName

Implementation
Already tested locally and all seems fine
Change in `logs-persistent-volume-claim.yaml`
From
`storageClassName: "{{ .Values.logs.persistence.storageClassName }}"`
To
`storageClassName: "{{ tpl .Values.logs.persistence.storageClassName . }}"`

Desired content
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "airflow_logs_volume_claim" . }}
  labels:
    tier: airflow
    component: logs-pvc
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.logs.persistence.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.logs.persistence.size | quote }}
  {{- if .Values.logs.persistence.storageClassName }}
  {{- if (eq "-" .Values.logs.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ tpl .Values.logs.persistence.storageClassName . }}"
  {{- end }}
  {{- end }}
{{- end }}
```

### Use case/motivation

Templating the value of storageClassName instead of taking it as is from values file

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@Natalique Are you planning to submit a PR for this yourself?

**Comment by Natalique** [comment]
@nathadfield Yes, I just submitted this one - https://github.com/apache/airflow/pull/32582

**Comment by oneturkmen** [comment]
I'd like to work on this task! Going to continue pushing to [PR#32582](https://github.com/apache/airflow/pull/32582/files)

**Comment by amoghrajesh** [comment]
Removing assignment due to inactivity
