### ISSUE TITLE
Airflow tasks went disappear after airflow db clean

### ISSUE THREAD

**Issue by lihan** [apache/airflow#32596]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version: 2.6.2

* Did a Airflow meatabase clean up using `airflow db clean  --clean-before-timestamp ...`
* Tasks instances went missing (see below)
* Deleting the dag run, airflow would re-trigger the missing dag run
  * After the first task was completed, all tasks instances are gone again.
<img width="184" alt="image" src="https://github.com/apache/airflow/assets/655051/1aee4c4e-d09b-4332-ae7f-b6029beadc97">

### How to reproduce

Not sure if this can be reproduced reliably 

### Operating System

Ubuntu 22.04

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Can you provide a few more details on your case?

- Were the tasks belonging to an execution before the cleaning time stamp?
- Are you able to find the task instances via "Browse" -> "Task Instances" in the UI? Or are they gone in there like in the Grid view?
- Can you try to re-produce and attach logs of the `airflow db clean` command?

**Comment by lihan** [comment]
@jens-scheffler-bosch 

Were the tasks belonging to an execution before the cleaning time stamp?
> Both. Though the intended clean up was for db records a year ago. But found out more recent dag runs were also affected.

Are you able to find the task instances via "Browse" -> "Task Instances" in the UI? Or are they gone in there like in the Grid view?
> They were gone in Task Instances view as well. As I checked in task_instances DB table as well. I can see there were tasks (7 as expected) initially after the dag was triggered. After the first task was completed, all 7 rows were gone.

Can you try to re-produce and attach logs of the airflow db clean command?
> Nothing unusual here, I used verbose mode and it printed all the usual clean up SQL there.

**Comment by RNHTTR** [comment]
This might have been resolved by #32684

Going to close this as not reproducible.
