### ISSUE TITLE
Helm operator/sensor for Airflow

### ISSUE THREAD

**Issue by wolvery** [apache/airflow#32614]
### Description

A collection of Operators/Sensor to Helm seems something interesting to create in-house Helm Charts and use the Airflow to deploy these in Kubernetes. Some actions like Upgrade/Install/Uninstall would be helpful and Sensors to monitor the status of some releases to guarantee that it was successful.

### Use case/motivation

An in-house Trino helm chart can be deployed to execute multiple SQL Queries and uninstalled after its use.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I am not sure if understand what it is. But just a reminder - you do not need to create an issue in Airflow. PR with the code is almost infinitely more valuable, showing the code you want to contribute, and we do not need an issue at all if it is a new operator. It's a red-tape that we prefer to avoid. 

But since you expressed willingnes to create a PR - by all means propose one and we will see.

**Comment by hussein-awala** [comment]
If you propose adding a new provider for helm, you can check this [doc](https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers) which explain the policy to accept new community providers.

**Comment by wolvery** [comment]
Ok. I'll work on this PR!
Thank you for sharing this doc, @hussein-awala

**Comment by eladkal** [comment]
> But, I believe that Helm is part of CNCF, so, we won't need a new provider in this case

We do.
The provider we have is `cncf.kubernetes`.
Having `cncf.helm` is accepting a new provider.

**Comment by potiuk** [comment]
> Having cncf.helm is accepting a new provider.

Yes. It's new provider.

But as a general comment - I believe it has a higher chance being accepted (providing it fulfills all the criteria - full test coverage, INCLUDING integration testing in this case. We have everything in place to perform end-to-end testing with such a provider automatically in our CI. We already have all the infrastructure to setup kubernetes, with kind we even run our own helm chart testing in CI automatically. The main reason we hesitate with accepting new providers, especially from external services that have their own teams that could manage, release and test the providers - is that we have no-one who could do all that.

We are all volunteer based organisation, some of us are paid to do some of the stuff relaterd to alirflow, some of us are lucky enough to be paid to be contributors.  But - this is nothing that we can promise anyone will be doing continuously. This is why for example the basic requirement for external services to be approved as community provider is that the 3rd-party that is interested in contributing and managing the provider will take the burden of developing, maintaining and running "system tests" and even provide infrastructure to do so  - this is already happening with AWS and is about to be completed for Google. 

But helm chart is different - it's not a service, its's a software that can be run independently. All it needs is running K8S. And we can have it in our CI. And we have already similar services - `mongo`, `kerberos` , `celery`, `kafka` - so Helm is really falling into this camp -  there is no "other" paid-for team that could manage the provider and run and maintain such tests. If the provider will have all the integration tests that will show "green" wherever the "smoke tests" with it pass (installing, upgrading, status, uninstalling - all that should be automatically tested) - then I think it's no brainer to accept it.

But without those, I'd be strongly against.

**Comment by eladkal** [comment]
> then I think it's no brainer to accept it.

I agree
