### ISSUE TITLE
Enhance UI for Datasets View

### ISSUE THREAD

**Issue by charliehahn** [apache/airflow#32639]
### Description

**Enhancing the interface of the "Datasets View" to optimize user experience**

1. Make the side menu collapsible
2. Add search bar that guides users to their desired DAGs

![image](https://github.com/apache/airflow/assets/29587716/e9bb8858-6816-4184-ab75-8c3878127362)

### Use case/motivation

1. The side menu obstructs the DAG/datasets lineage view. A collapsible menu would save space 🪐 
2. The process of finding DAGs is painful, even if `cmd/ctrl+f` is used for highlighting. A search bar for quick access to your DAGs would save loads of time 🕚

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by simond** [comment]
@bbovenzi I was hoping to work on this but it looks like you may have already done this?

**Comment by bbovenzi** [comment]
Oh yeah, I forgot we had an issue open for this.

Closed by: https://github.com/apache/airflow/pull/37425 and https://github.com/apache/airflow/pull/37464
