### ISSUE TITLE
Tableau provider - AttributeError

### ISSUE THREAD

**Issue by otamxfcz** [apache/airflow#32648]
### Apache Airflow version

2.6.3

### What happened

After updating to Airflow 2.6.3-python3.8 I have started to get this error message from Tableau provider/hook.
I am not passing variable "tableau_conn_id" but I am hoping that it will default to a value 'tableau_default'

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/tableau/operators/tableau.py", line 105, in execute
    with TableauHook(self.site_id, self.tableau_conn_id) as tableau_hook:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/tableau/hooks/tableau.py", line 82, in __init__
    self.site_id = site_id or self.conn.extra_dejson.get('site_id', '')
AttributeError: 'str' object has no attribute 'get'
```

### What you think should happen instead

It should load the default site_id (tableau_default) without throwing exception.

### How to reproduce

1. Install Airflow 2.6.3-python3.8
2. Create dag which is using ```from airflow.providers.tableau.operators.tableau import TableauOperator```
3. Call operator:
```
    update_tableau = TableauOperator(
        task_id='refresh_tableau_datasource',
        resource='datasources',
        method='refresh',
        blocking_refresh=False,
        find='NameOfTheDatasource',
        match_with='name',
    )
```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==7.2.1
apache-airflow-providers-celery==3.2.1
apache-airflow-providers-cncf-kubernetes==7.1.0
apache-airflow-providers-common-sql==1.5.2
apache-airflow-providers-docker==3.7.1
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.4.2
apache-airflow-providers-github==2.2.0
apache-airflow-providers-google==10.2.0
apache-airflow-providers-grpc==3.2.1
apache-airflow-providers-hashicorp==3.4.1
apache-airflow-providers-http==4.4.2
apache-airflow-providers-imap==3.2.2
apache-airflow-providers-microsoft-azure==6.1.2
apache-airflow-providers-mysql==5.1.1
apache-airflow-providers-odbc==4.0.0
apache-airflow-providers-papermill==3.2.1
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-redis==3.2.1
apache-airflow-providers-sendgrid==3.2.1
apache-airflow-providers-sftp==4.3.1
apache-airflow-providers-slack==7.3.1
apache-airflow-providers-snowflake==4.2.0
apache-airflow-providers-sqlite==3.4.2
apache-airflow-providers-ssh==3.7.1
**apache-airflow-providers-tableau==4.2.1**

### Deployment

Docker-Compose

### Deployment details

Deployment is done trough docker-compose.yml file.

### Anything else

It happens every time when TableauOperator is called.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@otamxfcz I am not able to replicate this.  What does the default Tableau connection look like?.  According to the [source code](https://github.com/apache/airflow/blob/main/airflow/utils/db.py#L625-L634), it should contain `{"site_id": "my_site"}` in the extras section.

**Comment by otamxfcz** [comment]
@nathadfield Thank you. I was using {... , extra:""} When I removed the extra field completely it started to work :)
