### ISSUE TITLE
AWS hook test_connection also needs endpoint_url

### ISSUE THREAD

**Issue by ieunea1128** [apache/airflow#32652]
### Apache Airflow version

2.6.3

### What happened

The initial code for testing an aws connection in my project had a bug. The bug caused the connection to be established with an incorrect URL because the necessary endpoint_url parameter was missing. As a result, the client connection consistently sent requests to the wrong URL, leading to unexpected behavior. 

### What you think should happen instead

'endpoint_url' parameter is needed to be added to the test_connection function's client connection(line 791) in 'airflow/providers/amazon/aws/hooks/base_aws.py' . By including the correct URL, the subsequent client requests were directed to the intended endpoint, resolving the URL discrepancy problem.

### How to reproduce

To reproduce the issue, attempt to establish a connection with an AWS-like service (such as Naver Cloud Platform) using the Python SDK, specifically boto3. During the connection process, make sure to provide the endpoint_url parameter along with the region_code. When trying to make test connection, failure to include the endpoint_url may result in incorrect URLs being sent and subsequent undesired behavior.

### Operating System

ubuntu 18.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@ieunea1128 I see you have indicated you are willing to submit a PR so I will assign this to you.
