### ISSUE TITLE
airflow 2.6.2 works from curl but not work when generate javaclient with same user password got 401, used to work on 2.3.0

### ISSUE THREAD

**Issue by zachik250** [apache/airflow#32661]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

airflow 2.6.2 works from curl but not work when generate javaclient with same user password got 401, used to work on 2.3.0

Inside application pod, I success to get data via curl:

curl --user ":" --location --request GET 'http://airflow-webserver.airflow:8080/api/v1/dags/~/dagRuns'
--header 'Accept: application/json'
--header 'Content-type: application/json'
--header 'Connection: keep-alive'
--data-raw ''

but from the application, when I build the client and try to call, get 401:

    ApiClient apiClient = org.openapitools.client.Configuration.getDefaultApiClient();
    apiClient.setBasePath("http://airflow-webserver.airflow:8080/api/v1/");
    apiClient.setUsername("<user>");
    apiClient.setPassword("<pass>");
Its work with same code on 2.3.0

The ApiClient generated via open api from 2.6.2 (and generate from 2.3.0 in the past)
This is the same code. but 401 from the application good from the curl

### What you think should happen instead

Should success to call the API

### How to reproduce

Let me understand what is the problem

### Operating System

k8s on gcp

### Versions of Apache Airflow Providers

works on 2.3.0
dont work on 2.6.2

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Did you test the clients built from 2.4 and 2.5? (just to detect where does the problem come from)

**Comment by pankajkoti** [comment]
hi @zachik250 what is the auth_backends https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#auth-backends value set in your Airflow configuration. It depends on which type of authentication your client is trying to use, if it's basic auth, you would need to set the value as `airflow.api.auth.backend.basic_auth`
