### ISSUE TITLE
Gird view - There should be an option to adjust the panel sizes

### ISSUE THREAD

**Issue by prithvi-git** [apache/airflow#32668]
### Description

Issue  - Can't see multiple run details when task name is long. There should be an option to adjust the panel sizes as we need.
For example: 
DAG - etl_phase3-1_bq_transform
Tasks like - scorecard_mart_main_bin_mrkt_cat_key_1-100
![image](https://github.com/apache/airflow/assets/80380870/7a3ca361-cfac-4e78-b304-ba12883a4d30)

### Use case/motivation

There should be an option to adjust the panel sizes as we need.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
hi @prithvi-git perhaps you're on an older version of Airflow. The issue does not mention the Airflow version and as @nathadfield pointed out the panels are adjustable on recent versions. Would suggest you upgrading your Airflow version as that is only way you would get the fix.

**Comment by prithvi-git** [comment]
Hi @pankajkoti , Thanks for the inputs. 
We are using Airflow Version: 2.3.4+composer, May I know in which version the width adjustment is added?

**Comment by pankajkoti** [comment]
hi @prithvi-git 
 you're welcome

A lot of features and bug fixes go on in each release. So to find out in which version it got fixed would need to put some time to read the release notes here: https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html

I tested on Airflow 2.5.3 locally which seems to be an available(latest) version on Composer and the panel seems to be resizable in that version of Airflow.
