### ISSUE TITLE
Total DAG execution time displayed in Grid view is not correct

### ISSUE THREAD

**Issue by prithvi-git** [apache/airflow#32667]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Issue - Total DAG execution time displayed in Grid view is not correct
Project - byzzer_production
Version: 2.3.4+composer
Environment Name: byzzer-prod-etl-load-3
For example: Below DAG run showing Duration: 02:20:36, which is just part of total DAG execution time.
DAG - etl_phase3-1_bq_transform
Run ID - manual__2023-07-09T12:00:18.636307+00:00
My observation - This normally happens when there is a failure in DAG and we recover the DAG run after fixing the issue. Somehow the total execution time for DAG starts showing less (may be only the execution time after recovery) 
![image](https://github.com/apache/airflow/assets/80380870/c95fcc09-99b5-4f6b-90bd-fb6c780bad41)

### What you think should happen instead

The DAG execution time should be cumulative time taken by all tasks in the DAG run. 

### How to reproduce

Run a big DAG, fail some task(s) in between. Fix the issue(s) and resume DAG from failed task. Check DAG execution bar in GRID view if it is showing correct time.

### Operating System

Windows

### Versions of Apache Airflow Providers

Version: 2.3.4+composer

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
When you clear the state of a finished DagRun (with `failed` or `success` state), we reset its start_date, and this is an expected behavior.

If you have a failed DagRun, and you want to clear its state after one week, based on your suggestion the duration should be the the duration before the clear + one week + the duration needed to finish, which is wrong. In current duration visible in the UI is the duration of the last try of the DagRun.

I close the issue, and we can re-open it if needed.

**Comment by prithvi-git** [comment]
Hi @hussein-awala - Why not to show the DAG level execution time as just sum of execution time of all child tasks? 
Even if you are resetting the start_date when a state is cleared after a week, instead of calculating DAG run time as described above (i.e. duration before the clear + one week + the duration needed to finish) can we show it as duration before the clear + the duration needed to finish.
