### ISSUE TITLE
Helm chart 1.10.0 introduces a bug with dagProcess and log groomer sidecar, webserver config invalid

### ISSUE THREAD

**Issue by brokenjacobs** [apache/airflow#32703]
### Apache Airflow version

2.6.3

### What happened

Trying to deploy helm chart 1.10.0 with a standalone dagprocessor fails with:
```
is invalid: spec.template.spec.containers[2].volumeMounts[1].name: Not found: "webserver-config"
```
I believe due to this being included in the log groomer sidecar by mistake:
https://github.com/apache/airflow/blob/bbd290266c0aba07a9e4c4fc24e1eb9b6b4c61d8/chart/templates/dag-processor/dag-processor-deployment.yaml#L212

### What you think should happen instead

Webserver config shouldn't be mounted in the logGroomer sidecar

### How to reproduce

set values:
dagProcessor.enabled: true

### Operating System

kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by csp33** [comment]
This behavior would be fixed by https://github.com/apache/airflow/pull/32644

**Comment by brokenjacobs** [comment]
Beat me to it, Thanks!
