### ISSUE TITLE
Support for DolphinDB database operator

### ISSUE THREAD

**Issue by peeyee** [apache/airflow#32711]
### Description

[DolphinDB ](https://www.dolphindb.com/) database is a timeseries database , which is good at timeseries storage and analysis.
This provider package will support using dolphindb database for batch data processing and complex data workflow.

### Use case/motivation

Time series data analysis using airflow, especially in the financial field.

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please follow procedure as explained in: https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers

It will guide you though the needed steps.

Closing as there is no need to have this issue open.
