### ISSUE TITLE
create-custom-decorator.rst does not describe how/where to setup get_provider_info

### ISSUE THREAD

**Issue by henrique** [apache/airflow#32721]
### What do you see as an issue?

The page [create-custom-decorator](https://github.com/apache/airflow/blob/main/docs/apache-airflow/howto/create-custom-decorator.rst) does not describe how or where to place get_provider_info.py

### Solving the problem

https://github.com/apache/airflow/blob/main/docs/apache-airflow/howto/custom-operator.rst is a better example, as it provides pointers for configuring PYTHONPATH and further link to [:doc:`/administration-and-deployment/modules_management`](https://github.com/apache/airflow/blob/main/docs/apache-airflow/howto/custom-operator.rst#id9)

Unfortunately, the same tips don't work for the decorators (at least it seems not to in the standalone version), or should they?

### Anything else

Thank you

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
https://airflow.apache.org/docs/apache-airflow-providers/index.html#how-to-create-your-own-provider
