### ISSUE TITLE
Dynamic Task Mapping - Wrong expected behavior during rerun/clear of mapped index

### ISSUE THREAD

**Issue by enrique-ayala** [apache/airflow#32757]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

version | 2.5.3                                                
executor | CeleryExecutor

When using Dynamic Task Mapping I noticed a behavior during a rerun/clearing of a particular mapped index.

In my DAG, I have task ``submit_job`` that is dynamically mapped using the expand method. Downstream from each ``submit_job`` task, I have a ``wait_and_get_report`` sensor that is also dynamically mapped using the expand method (See How to reproduce section with a sample dag) . 

During a rerun or clearing of a specific mapped index for example ``submit_job[0]``, I expected only the corresponding  downstream task ``wait_and_get_report[0]`` to be rerun. However, I observed that all downstream tasks  ``wait_and_get_report[0]`` and ``wait_and_get_report[1]`` were rerun as well: 
![image](https://github.com/apache/airflow/assets/10963531/da456407-40fe-4f0d-ab3c-891ff10dc671)

### What you think should happen instead

During a rerun or clearing of a specific mapped index, I expect the behavior to be more granular. Specifically:

When I rerun or clear a particular mapped index ``submit_job[0]`` , I expected that : 
- ``submit_job[0]``should be rerun (initiating a new API call) and only the corresponding downstream ``wait_and_get_report[0]`` should be rerun, waiting for the completion of the new API call and retrieving the report results for that specific index.

Currently, the rerun or clearing operation triggers all downstream tasks, regardless of the mapped index, which is causing additional processing and potentially unnecessary API calls.

### How to reproduce

This is a sample dag that reflects this use case : 

```
from airflow import DAG
from airflow.decorators import task
from airflow.utils.dates import days_ago
from airflow.sensors.base import BaseSensorOperator

default_args = {
    'owner': 'dummy_owner',
    'start_date': days_ago(1),
}


class WaitAndGetReport(BaseSensorOperator):
    """
    Wait for job_id to finish and retrieve report file
    """

    template_fields = ('job_id',)

    def __init__(
        self,
        *args,
        job_id: str,
        **kwargs
    ):
        super().__init__(**kwargs)
        self.job_id = job_id

    def poke(self, context: dict) -> bool:
        print(f"Check until JobStatus==true and immediate call GetReportAPI for: {self.job_id}")   
        return True


with DAG(
    'sample_dag_to_reproduce_issue',
    default_args=default_args,
    schedule_interval=None, 
    catchup=False,
) as dag:

    @task
    def prepare_report_request():
        # API json request body is generated here
        return ["request_1", "request_2"]

    @task
    def submit_job(job_request):
        # API call is executed here which returns a corresponding job_id . 
        print(f"Calling submitJobAPI ...")
        return f"a_returned_job_id_for_{job_request}_from_submitJobAPI"


    report_requests = prepare_report_request()
    job_ids = submit_job.expand(job_request=report_requests)
    get_reports = WaitAndGetReport.partial(task_id='wait_and_get_report',
                                          mode='reschedule', poke_interval=5).expand(job_id=job_ids)
```

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
In your dag, the mapped operator `get_reports` is a downstream of the mapped operator `submit_job`, which means that every mapped task created from `get_reports` is downstream of all the mapped tasks created from `submit_job`.
```
submit_job1 -------|        | -------- get_reports1
submit_job2 ------ |------> | -------- get_reports2
submit_job3 ------ |        | -------- get_reports3
```
If you want to create something like:
```
submit_job1 ----------> get_reports1
submit_job2 ----------> get_reports2
submit_job3 ----------> get_reports3
```
you can create a task group which contains the two tasks `submit_job` and `get_reports` without any mapping, then map the task group itself:
```python
@taskgroup
def my_taskgroup(job_request):
    return WaitAndGetReport(task_id='wait_and_get_report',
                                          mode='reschedule', poke_interval=5, job_id=submit_job(job_request=report_requests))
my_taskgroup.expand(job_request=report_requests)
```

**Comment by enrique-ayala** [comment]
Nice @hussein-awala  , thanks! 

On the same topic, I've received this NotImplementedError exception : 
```
operator expansion in an expanded task group is not yet supported
```
Is there any plan to support it ? that would be also a very handy feature.

**Comment by potiuk** [comment]
> Is there any plan to support it ? that would be also a very handy feature.

PRs are always welcome. Generally there are no "plans" other than some AIPs. If there is someone who wants to implement something like that - they just do it. It can be anyone -maye even you :)

**Comment by foldvari** [comment]
@hussein-awala This is the exact opposite of the behavior I'd expect.
For me expanding tasks means that it is task to task mapping so the dependency is between the mapped tasks.
task1[0] --> task2[0]
task1[1] --> task2[1]
task1[2] --> task2[2]

And when I expand a taskgroup that for me means that the dependency is between the whole group of mapped tasks.

task_group1  -->  task_group2
 +- task1[0]            +- task2[0]
 +- task1[1]            +- task2[1]
 +- task1[2]            +- task2[2]

It seems I am missing the concept of it. Can someone explain it please?  Or is it only to maintain backwards compatibility of the task mapping behavior?
