### ISSUE TITLE
Connection ID is not sanitized and you can self - javascript yourself

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#32770]
### Body

In Admin -> Connection the connection ID is not sanitized when you create it and not sanitized when it is displaye so you can put pieces of javascript in it `<script>alert(1)</script>` . This is not really a security issue, becaus you cannot do more with it than when you edit/inspect in the browser, but it would be nice to fix it and sanitize connection ID - likely ad the display time.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by AmanSal1** [comment]
@potiuk  Can I work on this ?

**Comment by potiuk** [comment]
It looks like it's something even deeper in FAB. When. you enter < or { in the connection_id, the Conneciton EDIT crashes with:

<img width="1015" alt="Screenshot 2023-08-28 at 11 39 32" src="https://github.com/apache/airflow/assets/595491/48a24c5f-93c2-4fc4-be96-ea516d6ef71a">

It needs a bit closer investigation
