### ISSUE TITLE
Docker image of xcom_sidecar is not configurable

### ISSUE THREAD

**Issue by raycarter** [apache/airflow#32805]
### Description

The iamge of xcom_sidecar is not cunfigurable (code: [xcom_sidecar.py#36](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/utils/xcom_sidecar.py#L36)). In our situation we can not access the "alpine" image from the docker image registry. Then the pod will not be started because the pulling of image failed.

Therefore it would be very nice that the image of xcom_sidecar is configurable so that we can pass an image hosted by our registry.

I see there was a merged PR about this feature #26766. But the changes was deleted in the commit a1f5a542. 

Could you please review it and add this feature again? Thanks!

### Use case/motivation

Usecase:

Use KubernetesPodOperator with `do_xcom_push=True` in an environment which can not access docker image registry.

### Related issues

PR #26766 deleted in a1f5a542

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Thanks for filing this request. I can understand for private hosted environment the access to public docker registry might be limited. Had been myself in the same situation.
@dstandish Do you know why this feature was removed? Had there been an intend to this?

**Comment by pegasas** [comment]
hi, @jens-scheffler-bosch , I am freshman in airflow community and willing to contribute, will you like to assign this task to me as me good first issue?

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/32858
