### ISSUE TITLE
Configuration of S3 based dags_folder

### ISSUE THREAD

**Issue by mashirali** [apache/airflow#32824]
### Apache Airflow version

2.6.3

### What happened

I have install apache-airflow-providers-amazon package before adding my s3 path in configuration as  `"AIRFLOW__CORE__DAGS_FOLDER=s3://bucket/dags/"` but no dag is being fetched till now.

### What you think should happen instead

The Dags should be shown

### How to reproduce

Here is the script:
```bash
docker run -it -p 8080:8080 --env AWS_DEFAULT_REGION=us-east-2 \
--env AWS_ACCESS_KEY_ID=**** \
--env AWS_SECRET_ACCESS_KEY=**** \
--env "_PIP_ADDITIONAL_REQUIREMENTS=lxml==4.6.3 apache-airflow[s3]==2.6.3 apache-airflow[amazon]==2.6.3 apache-airflow-providers-amazon==8.3.1 charset-normalizer==1.4.1 mlflow==2.5.0" \
--env AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS=origin,content-type,accept \
--env AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS=POST,GET,OPTIONS,DELETE \
--env AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS=* \
--env AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db \
--env AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth \
--env AIRFLOW__WEBSERVER__AUTHENTICATE=True \
--env AIRFLOW__WEBSERVER__AUTH_ALOGIN=admin:admin \
--env AIRFLOW__CORE__LOAD_EXAMPLES=False \
--env AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True \
--env AIRFLOW__CORE__DAGS_FOLDER=s3://airflow-bucket/dags/ apache/airflow:2.6.3-python3.8 standalone
```

### Operating System

ubuntu 22.04

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.3.1

### Deployment

Other Docker-based deployment

### Deployment details

I am making two deployments in parallel, One is by testing in my local machine using the above provided docker run command. The other one is ECS Deployment on which I am sending the environment variables.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mashirali** [comment]
In configuration this looks like, <html>
<body>


Section | Key | Value | Source
-- | -- | -- | --
core | dags_folder | s3://airflow-dags/dags/


</body>
</html>

**Comment by Lee-W** [comment]
Hello, could you please share where you found the documentation that mentions dags_folder supporting s3? I attempted to search through the code but was unable to locate it.

**Comment by mashirali** [comment]
Can you share the solution to this.
________________________________

**Comment by eladkal** [comment]
It seems that what you are after is [AIP-5 Remote DAG Fetcher](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher) which is not yet supported.

Currently dags must present on a file system that is accessible to the scheduler, webserver, and workers. So if this is not the case for you then you should use some service to sync the files to the relevant file system.
