### ISSUE TITLE
Page not updating automatically the events, ajax?

### ISSUE THREAD

**Issue by pauloventurab** [apache/airflow#32868]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello guys, after resets some pods (scheduler, trigger and worker), once I run some dag, I can't see it refreshing the tasks moving automatically, the logs and etc. I need always to refresh the page to see what is going on and it is not good.

Airflow Version 2.6.1 on GKE Kubernetes

### What you think should happen instead

Restart kubernetes pods

### How to reproduce

I dont know, I want to do know what is the step I need to fix it.

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

helm with some docker modifications just to install some requirements.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
hi @pauloventurab can you check if this is still happening on the latest versions? 2.6.3 is the latest version at the moment and 2.7.0 will be out soon too. For me refresh of logs works fine.
