### ISSUE TITLE
DatabricksSubmitRunOperator should accept a pipeline name for a pipeline_task

### ISSUE THREAD

**Issue by adam133** [apache/airflow#32866]
### Description

It would be nice if we could give the DatabricksSubmitRunOperator a pipeline name instead of a pipeline_id for cases when you do not already know the pipeline_id but do know the name. I'm not sure if there's an easy way to fetch a pipeline_id.

### Use case/motivation

Avoid hardcoding pipeline ID's, storing the ID's elsewhere, or fetching the pipeline list and filtering it manually if the pipeline name is known, but ID is not.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by adam133** [comment]
Should be pretty similar function and use to the find_job_id_by_name function [here](https://github.com/apache/airflow/blob/9e3104b5effc56f77833772d86e7201bcc50b8c9/airflow/providers/databricks/hooks/databricks.py#L193 ).

**Comment by hussein-awala** [comment]
@adam133 Sounds like a good feature, would you like to implement it and become a contributor on Airflow?

**Comment by adam133** [comment]
If I get time, yes - problem is lack of time 😄 

For now I've just hardcoded pipeline IDs to keep moving on my project.

**Comment by adam133** [comment]
Got a draft linked above, needs testing, tests, and documentation updates I think.

**Comment by adam133** [comment]
PR should be ready for review now if anyone minds taking a look. If I get a chance I'll try adding a more specific test case.
