### ISSUE TITLE
Wrong version in Dockerfile

### ISSUE THREAD

**Issue by gachdavit** [apache/airflow#32877]
### Apache Airflow version

2.6.3

### What happened

I want to use `2.6.3` stable version of `Airflow`. I cloned the project and checkout on the `tags/2.6.3`.

```bash
git checkout tags/2.6.3 -b  my_custom_branch
```
After checkout I check the `Dockerfile` and there is what I see below:

```bash
ARG AIRFLOW_VERSION="2.6.2"
```
Then I just download code as a `zip` [2.6.3 link](https://github.com/apache/airflow/releases/tag/2.6.3) and I see the same under `Dockerfile`.

Does `AIRFLOW_VERSION` have a wrong value ?

Thanks !

### How to reproduce

I need confirmation that, version is definitely wrong under `Dockerfile`.

### Operating System

Ubuntu

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
I think it depends on the latest released version. For 2.6.3, the latest released version is the previous one which is 2.6.2.

@potiuk @hussein-awala @pierrejeambrun can you confirm this hypothesis?

If that's indeed an issue, I'd like to fix it

**Comment by amoghrajesh** [comment]
@potiuk I completely missed that, didn't get you at all.
Can you explain a bit more

**Comment by potiuk** [comment]
* The version is manually updated in the docker file as part of the release process
* the process is here: https://github.com/apache/airflow/blob/v2-6-test/dev/README_RELEASE_AIRFLOW.md
* if you look there, updating the version is done after the TAG is set for the release
* it should be done before.

**Comment by gachdavit** [comment]
@potiuk 

When I am doing `git checkout tags/2.6.3` (I want `2.6.3 stable` version) and I will change the value in the `Dockerfile` (`2.6.2` -> `2.6.3`) manually, that must work as well right ?

**Comment by amoghrajesh** [comment]
@potiuk I can see that the step: `- Updating `Dockerfile` with the new version.` is last. We are not doing any steps after it.
Can you point me where this is done?
> if you look there, updating the version is done after the TAG is set for the release

**Comment by potiuk** [comment]
> When I am doing git checkout tags/2.6.3 (I want 2.6.3 stable version) and I will change the value in the Dockerfile (2.6.2 -> 2.6.3) manually, that must work as well right ?

Read the docs: https://airflow.apache.org/docs/docker-stack/build.html - it has all the options and explains how to choose airflow version to use by`--build-args`. There are examples you can follow. NOTE! you might not necessary need to use the Dockerfile. Dockerfile is there for "power users" who want to have optimized experience and follow the "customization" route rather than "extending" the reference image of ours. The docs I linked explain the difference, you can also watch my talk explaining it https://www.youtube.com/watch?v=wDr3Y7q2XoI 

> @potiuk I can see that the step: - Updating Dockerfile with the new version. is last

Yes. It is last. This is the issue to be fixed. It should be before tagging (which is before it).

**Comment by gachdavit** [comment]
@potiuk 

Thanks !
