### ISSUE TITLE
Airflow UI ignoring extra connection field during test connection

### ISSUE THREAD

**Issue by genehynson** [apache/airflow#32890]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

In Airflow 2.6.1 I can no longer use the `extra` field in any `http` based connection when testing the connection.

Inspecting the web request for testing the connection I see that the `extra` field is empty, even though I have data in there:

```json
{
  "connection_id": "",
  "conn_type": "http",
  "extra": "{}"
}
```

<img width="457" alt="image" src="https://github.com/apache/airflow/assets/6411855/d6bab951-5d03-4695-a397-8bf6989d93a7">

I saw [this issue](https://github.com/apache/airflow/issues/31330#issuecomment-1558315370) which seems related. It was closed because the opener worked around the issue by creating the connection in code instead of the Airflow UI.

I couldn't find any other issues mentioning this problem.

### What you think should happen instead

The `extra` field should be included in the test connection request.

### How to reproduce

Create an `http` connection in the Airflow UI using at least version 2.6.1. Put any value in the `extra` field and test the connection while inspecting the network request. Notice that the `extra` field value is not supplied in the request.

### Operating System

N/A

### Versions of Apache Airflow Providers

N/A

### Deployment

Astronomer

### Anything else

If I had to guess, I think it might be related to [this PR](https://github.com/apache/airflow/pull/28583) where a json linter was added to the extra field.

Saving the connection seems to work fine, just not testing it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
Reopening this as the fix was reverted in https://github.com/apache/airflow/pull/33032
