### ISSUE TITLE
question: Why a MySqlOperator only could run single sql command?

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#329]
How is if I want to run multiple SQL command in one task?

**Comment by mistercrunch** [comment]
I just merged a commit that enables passing a list of statements to the sql parameter of the operator. The hook already enabled this, but the operators would fail when attempting logging the list...
https://github.com/airbnb/airflow/commit/4b20b3dfed2935e25ac07789a0cf1572d84a4ad0

**Comment by griffinqiu** [comment]
What is the philosophy of one task with one sql query ; )))

**Comment by griffinqiu** [comment]
Thank you

**Comment by griffinqiu** [comment]
@mistercrunch Could we change to 

``` python
if type(self.sql) == list:
  log = "\nExecuting: ".join(self.sql)
else:
  log = str(self.sql)
logging.info('Executing: ' + log)
```

**Comment by griffinqiu** [comment]
@mistercrunch My major question is why can not run multiple SQL at the same time.
Such as my sql file have multiple SQL script slice by ;
