### ISSUE TITLE
DAG run marked as success even though it hasn't run yet

### ISSUE THREAD

**Issue by aamster** [apache/airflow#32937]
### Apache Airflow version

2.6.3

### What happened

DAG run marked as success even though it hasn't run yet

![Screenshot 2023-07-29 at 9 38 25 AM](https://github.com/apache/airflow/assets/5454341/9173b9a3-08a7-40c5-beed-eb5866dbe3ae)

### What you think should happen instead

The dag needs to run instead of immediately being marked as success. This is a very severe bug. 

### How to reproduce

Unfortunately I am not sure what the minimal conditions are to reproduce this, but I can consistently reproduce this with my script. 

I am submitting 40 dag runs in a script by calling /api/v1/dags/<dag_id>/dagRuns endpoint to submit a dag run.

Consistently only 1 out of 40 is immediately marked as success even though it never ran. 

### Operating System

rocky

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
What is the start date of your dag? is it smaller than the dag runs logical dates?

**Comment by aamster** [comment]
Looks like logical_date is passing datetime.datetime.utcnow() but start_date is datetime.datetime.now(). Will close if that's the issue

**Comment by hussein-awala** [comment]
`start_date` should be smaller than `logical_date`, otherwise the DagRun will be marked immediately as succeeded without run it.
I close the issue.

**Comment by aamster** [comment]
I will investigate this more on Monday. It still doesn't make sense why
only 1 dag run out of 40 submitted at the same time would immediately be
marked as succeeded if this is the issue since local and UTC time would
differ by several hours

**Comment by aamster** [comment]
@hussein-awala I checked and `datetime.datetime.now()` returns local time in UTC. The dag has `start_date` of `datetime.datetime.now()` and the `logical_date` is being passed as `datetime.datetime.utcnow()`. Therefore, the logical_date must be after the start_date. Please reopen this issue.

**Comment by hussein-awala** [comment]
> print(datetime.datetime.now(), datetime.datetime.utcnow())
2023-07-29 21:01:51.339089 2023-07-29 21:01:51.339093

In your case they have the same value, it could be related to your [default-timezone](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timezone.html#default-time-zone).

> It still doesn't make sense why only 1 dag run out of 40 submitted at the same time

If you use `datetime.now()` for both parameters, there is a small chance that the scheduler processes the DagRun too fast because it's not overloaded, in this case, the two values could be equals.

Using a variable date for dag `start_date` is a bad practice, and using `datetime.now()` as the value for that variable is worse. It would be better if you could use a fixed value, and if not, you can set it to `datetime.now() - timedelta(hours=1)` or `pendulum.yesterday()`. Could you test this before reopening the issue?

**Comment by hussein-awala** [comment]
From [Airflow FAQ](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date:~:text=We%20recommend%20against%20using%20dynamic%20values%20as%20start_date%2C%20especially%20datetime.now()%20as%20it%20can%20be%20quite%20confusing.%20The%20task%20is%20triggered%20once%20the%20period%20closes%2C%20and%20in%20theory%20an%20%40hourly%20DAG%20would%20never%20get%20to%20an%20hour%20after%20now%20as%20now()%20moves%20along.):
> We recommend against using dynamic values as start_date, especially datetime.now() as it can be quite confusing. The task is triggered once the period closes, and in theory an @hourly DAG would never get to an hour after now as now() moves along.

**Comment by aamster** [comment]
@hussein-awala could not reproduce with `pendulum.yesterday` though I cannot say I understand why that should fix this issue since the DAG is started well before the dag runs are submitted so start_date should be before logical_date
