### ISSUE TITLE
Official Airflow AWS ECS Executor

### ISSUE THREAD

**Issue by colelloa** [apache/airflow#32943]
### Description

Hi,

I recently stumbled upon https://github.com/aelzeiny/airflow-aws-executors - it is no longer maintained. I think this functionality could be a great way to expand functionality into cloud providers, and the linked repo is a great example of how well AWS Fargate/Batch/ECS integrate into the Airflow ecosystem.

I'd be happy to help integrate this if needed, although it is not my repo - I'm a long-time airflow user, but never contributed!

### Use case/motivation

I'd like to be able to use this set of Executors without needing to install from an unofficial unmaintained library or fork it and maintain it internally, to prevent the need for setting up a celery cluster or kubernetes cluster and give more flexibility to airflow users!

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
[AIP-51 Removing Executor Coupling from Core Airflow](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-51+Removing+Executor+Coupling+from+Core+Airflow) is almost completed.
I think after that we will need to have mailing list discussion about policy of how/what type of new executor will be accepted as Airflow providers and what will be left as 3rd party (Similar to the policy of how we accept providers https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers ) cc @o-nikolas @potiuk 

Regardless is will be possible to write your own custom executor and deploy it easily.

**Comment by potiuk** [comment]
I also think the AWS team prepares to bring the executor to the amazon provider.

**Comment by potiuk** [comment]
(and yes - it will require devlist discussion ).

**Comment by raphaelauv** [comment]
@colelloa -> https://apache-airflow.slack.com/archives/CCRR5EBA7/p1689029701359549

**Comment by eladkal** [comment]
I'm going to close this issue as for the moment there is no action item here.
@colelloa I suggest to follow @shubham22 feedback request in Slack

**Comment by o-nikolas** [comment]
@colelloa,

You'll be pleased to hear that we're working on it :) (you can see more details here https://github.com/aelzeiny/airflow-aws-executors/issues/24).

ECS executor is under construction as we speak. Keep an eye out!

**Comment by raphaelauv** [comment]
EcsExecutor will act like a KubernetesExecturor ( one new ephemeral airflow worker container for every task ) or CeleryExecutor ( shared running container for N airflow task ) , or a mix of both ( like the CeleryKubernetes ) ? 

will the EcsExecutor support/manage the triggerer for the deferable tasks ?

**Comment by o-nikolas** [comment]
> EcsExecutor will act like a KubernetesExecturor ( one new ephemeral airflow worker container for every task ) or CeleryExecutor ( shared running container for N airflow task ) , or a mix of both ( like the CeleryKubernetesExecutor ) ?

It will work much like the K8s executor, with each Airflow Task launched into it's own ECS Task (the overloading of the word Task is very unfortunate in this space :laughing: )  

> will the EcsExecutor support/manage the triggerer(s) for the deferable tasks ?

It is not really up to the executor to manager deferred tasks. That is the responsibility of the Triggerer.

**Comment by o-nikolas** [comment]
We will follow-up soon with an AWS Batch executor which will be closer to a Celery style executor with queuing and batching on the executor side.

**Comment by raphaelauv** [comment]
so we will need a AwsBatchEcsExecutor (like the CeleryKubernetesExecutor) :grin:

**Comment by o-nikolas** [comment]
> so we will need a AwsBatchEcsExecutor (like the CeleryKubernetesExecutor) 😁

I'll have something coming for that next year too :) To make using multiple executors at the same time natively supported in Airflow. We get asked for this periodically!
