### ISSUE TITLE
Error not detected in multi-statement vertica query

### ISSUE THREAD

**Issue by darkag** [apache/airflow#32993]
### Apache Airflow version

2.6.3

### What happened

Hello, 

There is a problem with multi-statement query and vertica, error will be detected only if it happens on the first statement of the sql.

for example if I run the following sql with default SQLExecuteQueryOperator options:
INSERT INTO MyTable (Key, Label) values (1, 'test 1');
INSERT INTO MyTable (Key, Label) values (1, 'test 2');
INSERT INTO MyTable (Key, Label) values (3, 'test 3');

the first insert will be commited, the nexts won't and no errors will be returned.
the same sql runed on mysql will return an error and no row will be inserted.

It seems to be linked to the way the vertica python client works (an issue has been opened on their git 4 years ago, [Duplicate key values error is not thrown as exception and is getting ignored](https://github.com/vertica/vertica-python/issues/255)) but since a workaround was provided I don't think it will be fixed in a near future. 

For the moment, to workaroud I use the split statement option with disabling auto-commit but I think it's dangerous to let this behaviour as is.

### How to reproduce

create a table MyTable with two columns Key and Lbl, declare Key as primary key.
Run the following query with SQLExecuteQueryOperator 
INSERT INTO MyTable (Key, Label) values (1, 'test 1');
INSERT INTO MyTable (Key, Label) values (1, 'test 2');
INSERT INTO MyTable (Key, Label) values (3, 'test 3');

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
Yes, it will affect other providers as the same base class/hook is used by others.

Looks like the `fetch_all_handler` gets used in the `get_records` method here https://github.com/apache/airflow/blob/main/airflow/providers/common/sql/hooks/sql.py#L255 in the base class DbApiHook.

So you can override this `get_records` method in Vertica hook and pass your custom handler there. You can define the custom handler in the same Vertica hook module. It just like normal method overriding. 

I have not used Vertica. But if you feel that is what is needed, please open a PR with that change and someone will be able to review your change.

**Comment by darkag** [comment]
It seems that operator run directly the hook's run function passing the fetch_all_handler as default, but it should work doing something like this for vertica hook:

```python
from airflow.providers.common.sql.hooks.sql import DbApiHook, fetch_all_handler

def vertica_fetch_all_handler(cursor) -> list[tuple] | None:
    to_return = fetch_all_handler(cursor)
    while cursor.nextset(): #loop on all statement result to get errors
        cursor.fetchall()
    return to_return
    

class VerticaHook(DbApiHook):
    """Interact with Vertica."""
    def run(
        self,
        sql: str | Iterable[str],
        autocommit: bool = False,
        parameters: Iterable | Mapping | None = None,
        handler: Callable | None = None,
        split_statements: bool = False,
        return_last: bool = True,
    ) -> Any | list[Any] | None:
        if(handler == fetch_all_handler):
            handler = vertica_fetch_all_handler
        return DbApiHook.run(self, sql, autocommit, parameters, split_statements, return_last)
```

I'll try to make test with this code tomorrow but I will not have time to make a PR for the moment.

**Comment by darkag** [comment]
While testing a possible fix I've found an other issue with the vertica client. Since the way I will fix the issue with operator may depend of a future fix for the above issue (the code provided earlier will work if you add the missing handler parameter in the DbApiHook.run call but I may not have to call fetchall for all the remaining result set)
