### ISSUE TITLE
Full screen mode for Logs, Graph, Code etc..

### ISSUE THREAD

**Issue by Adaverse** [apache/airflow#33012]
### Description

Currently, with the old UI, we can see logs, code, graph, gantt in major portion of the screen.
But with AIP-38, the replacement of the above UIs can be seen in a small portion of the screen. It would be great to have the option to toggle full-screen mode.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
> it is certainly possible to view everything in the manner you have described on the latest version of Airflow.

Yes, as of now, it's possible, but it would be removed in the coming future, ex - #32833 

>  Is this a feature request to be included as part of AIP-38?

It's a natural extension of AIP-38 and it can be added as a part of AIP-38.

Just for more clarity on the above, maybe we can have a button as marked in the screenshot, that makes the log go full screen and similarly for other tabs as well.

![image](https://github.com/apache/airflow/assets/35839624/af79bac8-7b70-4bdd-a283-ecbace8ecd2e)

**Comment by nathadfield** [comment]
@dstandish @utkarsharma2 Maybe one of the people involved in AIP-38 could comment on this better than I?

**Comment by NilsJPWerner** [comment]
I think a button to open logs in a full screen modal would be a great improvement. Currently I find myself constantly adjusting the log widths when I switch between focusing on the logs and focusing on the grid.

**Comment by Adaverse** [comment]
> I think a button to open logs in a full screen modal would be a great improvement. Currently I find myself constantly adjusting the log widths when I switch between focusing on the logs and focusing on the grid.

Same here! Will take this up once I get time. Until then if anyone wants to, please feel free to take a few of the tasks.

**Comment by morooshka** [comment]
Hi Team! Is there a way to see Graph / Logs like it was previously? Like this ([v2.6.3](https://pypi.python.org/pypi/apache-airflow/2.6.3))? I mean not at the right of grid
![image](https://github.com/apache/airflow/assets/72786791/70ecdf9d-a44e-45e3-9306-8a370a493896)

**Comment by bbovenzi** [comment]
We also made the filter bar collapsible: https://github.com/apache/airflow/pull/38296

Im going to improve the UX of it for 2.9.1 but yes, this is done.
