### ISSUE TITLE
Clearing task from List Task Instance page in UI does not also clear downstream tasks?

### ISSUE THREAD

**Issue by aamster** [apache/airflow#33014]
### Apache Airflow version

2.6.3

### What happened

Select tasks from List Task Instance page in UI and select clear
Only those tasks are cleared and downsteam tasks are not also cleared as they are in the DAG graph view

### What you think should happen instead

downstream tasks should also be cleared

### How to reproduce

Select tasks from List Task Instance page in UI for which there are downstream tasks and select clear

### Operating System

rocky

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
I think instead of automatically also clearing downstream tasks, maybe the modal from the grid/graph view should be displayed, giving the user the choice

<img width="1327" alt="image" src="https://github.com/apache/airflow/assets/25823361/4891681c-d0c9-4157-9e0e-39eb78834b21">

**Comment by pankajkoti** [comment]
@RNHTTR I removed the `area:core` label and put it `area:UI`. Please check if it sounds right.

**Comment by pankajkoti** [comment]
I think that would be the ideal way though. It should not silently clear all the downstream tasks unless explicitly asked for. 

I think we could discuss if it's a good idea to display the modal view from the List view.

cc: @bbovenzi @pierrejeambrun

**Comment by bbovenzi** [comment]
Let's at least update this confirmation text to say that it includes downstream tasks?

<img width="316" alt="Screenshot 2023-08-02 at 2 44 48 PM" src="https://github.com/apache/airflow/assets/4600967/ae181eb1-5d01-494f-8d4e-b13e4e448b2f">

**Comment by Adaverse** [comment]
> I think that would be the ideal way though. It should not silently clear all the downstream tasks unless explicitly asked for.
> 
> I think we could discuss if it's a good idea to display the modal view from the List view.

Yes, this would be ideal. Not sure if we can reuse the same components unless we migrate this above screen to React?

**Comment by bbovenzi** [comment]
Yes, replacing this in react is a lot for now. let's at least update the confirmation modal since that already exists on the FAB model.

**Comment by peloyeje** [comment]
Hey, I would like to try this one if that's ok
To make sure I get it right, expected behavior would be that downstream TIs are cleared + modal explicitely warns about it right?

**Comment by pierrejeambrun** [comment]
Just assigned you!
