### ISSUE TITLE
Efficient support for multiple daily DAGs to trigger one another via datasets with XCOM payload

### ISSUE THREAD

**Issue by scr-oath** [apache/airflow#33020]
### Description

Provide a mechanism to pass data (XCOM?) so that downstream DAGs could know more context about how/why/when/by-what they were triggerered.

### Use case/motivation

In order to avoid writing monolithic DAGs, it would seem useful to have separate DAGs focused on discrete Input and Output transforms, which would also allow them to be retried/rescheduled as needed. One could imagine daily batch-processing comprised of several DAGs and think of using the dataset mechanism as a way to trigger efficiently.  However, it seems that no information comes along with a dataset passed in each DAG's "schedule". If several days of daily tasks are (re-)scheduled, the outlet of a dataset would not be able to communicate to downstream DAGs what the "datestamp" was for them to process.

As of now the dataset is just a string and, when loosely coupling a producer/consumer via the Dataset, there is no way to communicate specific information about the producer's exact output. There also doesn't appear to be a way to mix-n-match scheduling based on a dataset as well as `@daily` e.g. so there's no way to connect a particular day's producer DAG with a consumer DAG.

If a task could query its lineage and specifically get data / XCOM information from the DAG/task/Dataset that triggered it, then it could take efficient actions based on the previous task's specific output location (i.e. its datestamp directory if that's the convention, but could be anything, really if a general way of passing/receiving data were provided.)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Is this not currently possible?

Outlet DAG:

```python
from pendulum import datetime

from airflow.decorators import (
    dag,
    task,
)

from airflow.datasets import Dataset


@dag(
    schedule=None,
    start_date=datetime(2023, 1, 1),
    catchup=False,
    default_args={
        "retries": 2,  # If a task fails, it will retry 2 times.
    },
    tags=["example"],
)  # If set, this tag is shown in the DAG view of the Airflow UI
def outlet():
    @task(outlets=[Dataset("outlet")])
    def write_xcom(ti=None):
        ti.xcom_push(key="outlet_xcom", value="xyz")

    write_xcom()


outlet()
```

Inlet DAG:

```python
import json
from pendulum import datetime

from airflow.decorators import (
    dag,
    task,
)

from airflow.datasets import Dataset


@dag(
    schedule=[Dataset("outlet")],
    start_date=datetime(2023, 1, 1),
    catchup=False,
    default_args={
        "retries": 2,  # If a task fails, it will retry 2 times.
    },
    tags=["example"],
)
def inlet():
    @task()
    def read_xcom(ti=None):
        xcoms = ti.xcom_pull(
            dag_id="outlet",
            task_ids="write_xcom",
            key="outlet_xcom",
            include_prior_dates=True,
        )
        print(f"xcoms: {xcoms}")

    read_xcom()


inlet()
```

```
[2023-08-02, 11:24:20 UTC] {logging_mixin.py:150} INFO - xcoms: xyz
```

**Comment by jens-scheffler-bosch** [comment]
Never tested myself but the code looks good. So if this is really the way of working then I still see a high demand that docs have this added as example and maybe the example dataset DAGs shipped include this in example code :-D

**Comment by scr-oath** [comment]
Well… this does seem like a reasonable approach, but then… it tightly couples the two dags.

There are some colleagues looking to version their dags by essentially adjusting the name of the file during deployment and using `Path(__file__).stem` as the dag_id.  They're aware of https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning but also not certain of its ETA.

Using the approach you suggested would not allow decoupling/loose-coupling of the producer and consumer dag through the dataset.

But it _DOES_ make me think that maybe the feature would be to carry the "triggering information" with dataset triggers… if the consumer dag (inlet in your case) could be told the name of the dag and/or dataset (if multiple) that triggered it, then it could ask for xcomm information by dag_id…

However, it makes me think "what if the producer ran multiple times before the downstream got its trigger" - not sure how often that would be the case - but… would the above solution allow for multiple separate triggers to carry their own xcom information related to their work?  Conceptually, you want to be able to get an event about each dataset write about what happened and I feel like using XCOM has the chance of race-conditions or skipping events - if you go read it - does it just always get the "last value"?
