### ISSUE TITLE
Allow DockerOperator to optionally pass DAG parameters as environment variables

### ISSUE THREAD

**Issue by theobjectivedad** [apache/airflow#33036]
### Description

This feature request proposes an update to ``airflow.providers.docker.operators.docker.DockerOperator`` where DAG parameters can optionally be passed into the container as environment variables. For example:

```python
task = DockerConfOperator(
  task_id="test_task",
  params_in_env=True,  # Defaults to False for compatibility
  ...
)
```

When enabled, DAG parameters will be passed into the container's environment. This would be a fairly simple update to ``execute`` so that it would pass the DAG context to ``_run_image`` which would pass the context to ``_run_image_with_mounts``. From here, ``context["params"]`` would simply be added to the container environment:

```python
self.container = self.cli.create_container(
  command=self.format_command(self.command),
  name=self.container_name,
  environment={
    **self._private_environment,
    **self.environment, 
    **context["params"]
  },
  ...
)
```

### Use case/motivation

**Scenario:**

DAG1 defines a DockerOperator task and provided a default environment variables, volume mounts, GPU devices, secrets, and other container-level settings for it to run in the desired environment. This configuration can be somewhat sophisticated depending on the environment.

Other DAGS leverage the TriggerDagRunOperator to invoke DAG1 and pass in ``conf`` parameters that will override environment variables in the container started by DAG1:

```python
my_task = TriggerDagRunOperator(
  task_id="inference_task",
  trigger_dag_id="DAG1",
  conf={
    "ENV_VAR1": "VAL1",
    "ENV_VAR2": "VAL2",
  },
)
```

Currently, it isn't straightforward to pass ``conf`` through dynamically to the container started by DAG1 since ``conf`` is part of the DAG context. An obvious solution would be to use templates however this would require that ``DAG1`` map each environment variable individually which could be too cumbersome for some applications and provide little value in the end (just consider how many environment-based configurations Airflow itself has).

With this update, ``conf`` would simply be passed into the container's environment when the feature is enabled and no additional mapping needed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Your proposal sounds reasonable and a good idea. Based on the standard Jinja-based templating I see no other (simple) option to pass a dict (dynamically) into the DockerOperator - at least I don't have a counter proposal immeditately.

Nevertheless I am not sure whether the property name is the best as well as it would be advised if _all_ `param`s should be passed into the ENV - and there could be also `params` being defined which are not of type string. So as simple as the approach smells there might be some side effects.

Before contributing this to the core - if you need that feature for your purposes - I'd propose to start on your side by implementing a first custom operator by inheriting from the `DockerOperator` and use it for a while. If you gained some experience (might be good to use it for a moment to see how "generic" it is, back-porting and contributing later. Or are you using exactly such kind of operator already and you think about back-porting?
(I note this because we do it the same - we use custom operators for a while and after gaining some experience of usage we think about what pieces are really common use and which ones are specific for our environment)

**Comment by theobjectivedad** [comment]
Good evening @jens-scheffler-bosch , I’ve been running a custom version of the DockerOperator for several weeks and would like to back-port.

To your point, I can imagine a scenario where folks may not want all dag params exposed as environment variables. Also, great feedback RE non-string values - I didn’t consider this.

I feel like adding another optional constructor parameter that contained a list of dag params that would be excluded from the container environment and wrapping the remaining dag params in a str() it would provide sufficient flexibility. 

To recap the design:

* pass_params_to_env is added to the DockerOperator constructor and when True would enable the feature. It will default to False to maintain compatibility. I’ll document that values will be converted to strings to make it clear for other DAG developers 
* Another optional parameter exclude_params_in_env will be an optional list of DAG parameter names that will not be passed to the container environment 

I was thinking about adding an include_params_in_env as well but I think when we are starting to list parameters it would just be better to map them in the environment template. 

Thank you again for your good feedback, let me know if this seems reasonable!

**Comment by jens-scheffler-bosch** [comment]
Mhm, okay on my way home today I thought about the parameter `render_template_as_native_obj=True` in DAGs. Do you know about this?

If you use this actually I assume the standard templating logic of Jinja could do all the same job via a `tojson` conversion, the following example did the same job like your proposal:

```
with DAG(
    dag_id="docker",
    schedule="0 0 * * *",
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    catchup=False,
    dagrun_timeout=datetime.timedelta(minutes=60),
    tags=["example", "example2"],
    params={
        "example_key": "example_value",
        "another_key": 1234,
    },
    render_template_as_native_obj=True,
) as dag:
    docker = DockerOperator(
        task_id="docker_test",
        image="alpine",
        command="env",
        environment="{{ params | tojson }}",
    )

    docker
```

**Comment by theobjectivedad** [comment]
I'm not familiar with render_template_as_native_obj, but it sounds like it is exactly what I'm trying to do. Let me update my DAGs and see how it works. I'll report back next week if I see any gaps. Giant thank you for the insight!

**Comment by jens-scheffler-bosch** [comment]
Example is here in the docs as well: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/operators.html#rendering-fields-as-native-python-objects

**Comment by theobjectivedad** [comment]
Good morning @jens-scheffler-bosch , the ``render_template_as_native_obj`` solution works perfectly. Thank you for your help!
