### ISSUE TITLE
Trigger DAG via POST REST-API invoke GET responce

### ISSUE THREAD

**Issue by dbatseka** [apache/airflow#33111]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version: [v2.6.2](https://pypi.python.org/pypi/apache-airflow/2.6.2)
Git Version: .release:d2f0d100dac4a95d664309d7b04a6a6110367446

We can't trigger any DAG since the [POST request](https://airflow.apache.org/docs/apache-airflow/2.6.2/stable-rest-api-ref.html#operation/post_dag_run) returns the same response as [GET request](https://airflow.apache.org/docs/apache-airflow/2.6.2/stable-rest-api-ref.html#operation/get_dag_runs):
```
{
"dag_runs": [......],
"total_entries": 202
}
```

Code with post request:

### What you think should happen instead

Instead, it should return the same structure as described in docs:
```
{
  "dag_run_id": "string",
  "dag_id": "string",
  "logical_date": "2019-08-24T14:15:22Z",
  "execution_date": "2019-08-24T14:15:22Z",
  "start_date": "2019-08-24T14:15:22Z",
  "end_date": "2019-08-24T14:15:22Z",
  "data_interval_start": "2019-08-24T14:15:22Z",
  "data_interval_end": "2019-08-24T14:15:22Z",
  "last_scheduling_decision": "2019-08-24T14:15:22Z",
  "run_type": "backfill",
  "state": "queued",
  "external_trigger": true,
  "conf": {},
  "note": "string"
}
```

### How to reproduce

```
data = {
    'my_data': {
        'id': '1',
        'firstName': 'John',
        'lastName': 'Smith'
    }
}

body = {
    "conf": {
        "data": data
    },
}
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}

req = requests.post(
    url=f"http://{url}/api/v1/dags/{dag_id}/dagRuns",
    data=json.dumps(body),
    auth=(aiflow_username, aiflow_password),
    headers=headers,
    verify=False
)
```

### Operating System

Ubuntu 20.04 LTS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
I'm not able to reproduce this; the `POST dags/{dag_id}/dagRuns` endpoint seems to be working fine, and the POST request returns the expected result:
```
{'conf': {},
 'dag_id': 'example_dag_basic',
 'dag_run_id': 'manual__2023-08-04T12:49:05.504282+00:00',
 'data_interval_end': '2023-08-04T00:00:00+00:00',
 'data_interval_start': '2023-08-03T00:00:00+00:00',
 'end_date': None,
 'execution_date': '2023-08-04T12:49:05.504282+00:00',
 'external_trigger': True,
 'last_scheduling_decision': None,
 'logical_date': '2023-08-04T12:49:05.504282+00:00',
 'note': None,
 'run_type': 'manual',
 'start_date': None,
 'state': 'queued'}
```

 Can you please provide a complete example that includes the DAG code? Also, you can wrap code in 3 back ticks (\``` before and \``` after your code sample) to properly format code.

**Comment by dbaceko** [comment]
Thank you, @RNHTTR 

Wrapped code and added airflow version info.
Unfortunately, there is no sense to add any DAG code since this POST request returns `{ "dag_runs": [......], "total_entries": N }` for any DAG in our environment
![image](https://github.com/apache/airflow/assets/43149842/a0e890e3-7910-47f9-96e7-b018a42c43f5)

**Comment by dbaceko** [comment]
Hi guys, 
Just wanted to inform you we resolved the issue by using `https` instead of `http` for post requests.
