### ISSUE TITLE
Empty log folders are not removed when clean up

### ISSUE THREAD

**Issue by ckljohn** [apache/airflow#33162]
### Apache Airflow version

main (development)

### What happened

Empty log folders use up all Inodes and they are not removed by [clean-logs.sh](https://github.com/apache/airflow/blob/main/scripts/docker/clean-logs.sh)

This is the diff after cleaning empty folders. (50GB disk used)

```
airflow@airflow-worker-2:/opt/airflow/logs$ df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/nvme2n1    3276800 1311542  1965258   41% /opt/airflow/logs
airflow@airflow-worker-2:/opt/airflow/logs$ find . -type d -empty -delete
airflow@airflow-worker-2:/opt/airflow/logs$ df -i
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
/dev/nvme2n1    3276800 158708  3118092    5% /opt/airflow/logs
```

### How to reproduce

Have lots of frequent DAGs.

### Operating System

Debian 11

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked as good first issue, but mayeb you would like to fix it yourself? it does not seem complex and I bet you already have a solution for that in your environment? Contributing it back seems like a good idea if you do
