### ISSUE TITLE
Dynamic TaskGroup Mapping - No logs from Grid view 

### ISSUE THREAD

**Issue by enrique-ayala** [apache/airflow#33179]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version 2.5.3 

When using a mapped Task Group , task logs are not shown  from Grid view .  For example  
![image](https://github.com/apache/airflow/assets/10963531/b1d53bc1-151c-455e-958b-dd44bb17009f)

See "How to reproduce" for dag code example. 

 

### What you think should happen instead

I was expecting to see logs represented similar as with dynamic task mapping from Grid view , where you can select a mapped index task   to see logs. 

### How to reproduce

```
from airflow.decorators import dag, task_group, task
from pendulum import datetime


@dag(
    start_date=datetime(2022, 12, 1),
    schedule=None,
    catchup=False,
)
def task_group_mapping_example():
    # creating a task group using the decorator with the dynamic input my_num
    @task_group(group_id="group1")
    def tg1(my_num):
        @task
        def print_num(num):
            return num

        @task
        def add_42(num):
            return num + 42

        print_num(my_num) >> add_42(my_num)

    # creating 6 mapped task group instances of the task group group1 (2.5 feature)
    tg1_object = tg1.expand(my_num=[19, 23, 42, 8, 7, 108])


task_group_mapping_example()
```

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is a duplicate. It's been fixed in 2.6 - you should upgrade (ideally to latest 2.6 or wait for 2.7 that should be released in the next few weeks: This is the PR in question https://github.com/apache/airflow/pull/28208
