### ISSUE TITLE
KubernetesPodOperator does not push XCOM

### ISSUE THREAD

**Issue by orenl91** [apache/airflow#33184]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Apache Airflow version
2.5.3 (on Google Composer)

What happened
Kubernetes pod operator failed to push xcom value.

After upgrading airflow from 2.3.4 to 2.5.3 (and apache-airflow-providers-cncf-kubernetes from 5.2.0 to 7.2.0) pushing of xcom values from kubernetes pod operator stopped working.

attaching the log and xcom screen
![image](https://github.com/apache/airflow/assets/7141865/63a035f9-3fe2-44bb-ac67-c8e87186a6ba)

![image](https://github.com/apache/airflow/assets/7141865/a45f2904-4816-468a-85d5-58c41467c5f7)

### What you think should happen instead

A new XCOM value should appear in XCOM screen

### How to reproduce

Using Google Cloud Composer 2.3.5 with Airflow 2.5.3

### Operating System

Google Cloud Composer Managed Airflow

### Versions of Apache Airflow Providers

From Google Documentation : https://cloud.google.com/composer/docs/concepts/versioning/composer-versions

apache-airflow==2.5.3+composer
apache-airflow-providers-apache-beam==5.1.1
apache-airflow-providers-cncf-kubernetes==7.2.0
apache-airflow-providers-common-sql==1.6.0
apache-airflow-providers-dbt-cloud==3.2.2
apache-airflow-providers-ftp==3.4.2
apache-airflow-providers-google==10.3.0
apache-airflow-providers-hashicorp==3.4.2
apache-airflow-providers-http==4.4.2
apache-airflow-providers-imap==3.2.2
apache-airflow-providers-mysql==5.1.1
apache-airflow-providers-postgres==5.5.2
apache-airflow-providers-sendgrid==3.2.1
apache-airflow-providers-sqlite==3.4.2
apache-airflow-providers-ssh==3.7.1

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
```
    KubernetesPodOperator(
        namespace="default",
        kubernetes_conn_id="kubernetes_default",
        image="alpine:3.16.2",
        cmds=["sh", "-c", "mkdir -p /airflow/xcom/;echo '[1,2,3,4]' > /airflow/xcom/return.json"],
        name="write-xcom",
        do_xcom_push=True,
        on_finish_action="delete_pod",
        task_id="write-xcom",
        get_logs=True,
    )
```

work with `apache-airflow-providers-cncf-kubernetes==7.4.1`

**Comment by orenl91** [comment]
Hi @raphaelauv thanks for replying.
my environment is using apache-airflow-providers-cncf-kubernetes==7.2.0
here is my code:
KubernetesPodOperator(
            task_id=pod_id,
            name=pod_id,
            image_pull_policy='Always',
            do_xcom_push=True,
            namespace=namespace,
            get_logs=True,  # Capture logs from the pod
            log_events_on_failure=True,  # Capture and log events in case of pod failure
            is_delete_operator_pod=True, # To clean up the pod after runs
            # config_file parameter - can be skipped if connection contains this setting 
            config_file="/home/airflow/composer_kube_config",
            # definition of connection to be used by the operator
            kubernetes_conn_id='kubernetes_default',   
            image=IMAGE
        )

**Comment by raphaelauv** [comment]
this is not a reproducible example with the latest provider version

**Comment by chanjaljayaram** [comment]
Maybe an issue here => [self._exec_pod_command(resp, "kill -s **SIGINT** 1")](https://github.com/apache/airflow/blob/a54c2424df51bf1acec420f4792a237dabcfa12b/airflow/providers/cncf/kubernetes/utils/pod_manager.py#L702).

Got it working after I changed SIGINT in the kill command to INT.

**Comment by potiuk** [comment]
Maybe you have some unsupported system you run Airflow on?
