### ISSUE TITLE
Task in DAG,after marking as success, immediately mark as failure.

### ISSUE THREAD

**Issue by qingwuxiamo** [apache/airflow#33201]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version 2.2.5
In the recent Airflow, tasks in DAGs often have this kind of problem - the tasks actually succeed in executing normally. However, strange things happen, the tasks are first marked as success but then immediately marked as failure, resulting in many tasks not being able to be scheduled normally and triggering alerts.
![image](https://github.com/apache/airflow/assets/67778528/1b5576fb-cdb3-408f-b110-7fd8270e5608)

### What you think should happen instead

I've been using it for two years and I haven't encountered this kind of problem.I don't know, I'm at a loss.

### How to reproduce

Often occurring, every day.

### Operating System

 Alibaba Cloud Elastic Compute Service

### Versions of Apache Airflow Providers

Airflow version 2.2.5

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you please add reproduce example?

**Comment by qingwuxiamo** [comment]
> Can you please add reproduce example?

Sorry, this is sporadic at the moment and cannot be reproduced completely. It may occur in any task. According to observation, the occurrence rate of this exception should be less than one percent per day.

**Comment by qingwuxiamo** [comment]
Then, occasional error situations can occur.
![image](https://github.com/apache/airflow/assets/67778528/098c834a-bfda-4319-a248-274e31f48569)

![image](https://github.com/apache/airflow/assets/67778528/e469ff95-aa8b-472d-9fde-ba6bc2cfe72c)

**Comment by potiuk** [comment]
I think that it could help if you could compare the log of successful output and unsuccessful one for the same task. And having it in a form that you can see the text of it (gists in github?) rather than log sceenshots would be helpful .

**Comment by potiuk** [comment]
You are missing on not having those 1000s fixes applied.

**Comment by qingwuxiamo** [comment]
It looks like I really need to upgrade then, thank you for your answer.
