### ISSUE TITLE
Max active deferred tasks

### ISSUE THREAD

**Issue by tim-x-y-z** [apache/airflow#33212]
### Description

It would be great to have a wait to limit the concurrency of deferred task. Currently using `max_active_task` doesn't limit the number of `deferred` tasks. 
As more operators adopt the `deferrable` approach, this would be a valuable feature.

### Use case/motivation

Limit the number of concurrent tasks when those are using `deferrable` operators.

### Related issues

potentially:
https://github.com/apache/airflow/discussions/21243#discussioncomment-2084928
https://github.com/apache/airflow/issues/15082
https://github.com/apache/airflow/issues/29416

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
As @raphaelauv proposed, you can use the conf `trigerrer.default_capacity` to limit the number of active trigger in a triggerrer, and the total number of active triggers is the number of trigerrer instances * `trigerrer.default_capacity`.

Once the task is deferred, it won't consume any more resources, waiting for its trigger to complete, so IMHO limiting the number of deferred tasks is pointless. However, what matters is the number of active triggers which, although light, could put some pressure on the triggerer service.

Could you explain your needs? Is it to reduce the pressure on the scheduler and the workers or to reduce it on an external system?

**Comment by tim-habitat** [comment]
Thanks for the replies! I agree with all you said.
However, as you may have sensed, in your question:
>  Could you explain your needs? Is it to reduce the pressure on the scheduler and the workers or to reduce it on an external system?

my need is to actually reduce the pressure on an external system. In particular, i am having concurrency limitations on an external endpoint. Hence i would like to limit the number of deferred task but ony within a specific dag. 
I wouldn't want to limit the triggerer capacity just for that outcome as multiple other dags don't have this constraint.

**Comment by raphaelauv** [comment]
then you could use an airflow pool https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/pools.html

**Comment by potiuk** [comment]
> then you could use an airflow pool https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/pools.html

The problme with that though is that deferred tasks do not count against pool limits . There is an issue for that https://github.com/apache/airflow/issues/29416 that was linked (but not explained why).

**Comment by potiuk** [comment]
I think actually - implementing #29416 is the **right** approach.

**Comment by potiuk** [comment]
And there is Green PR doing just that that I am going to advocate for in 2.7.0

**Comment by potiuk** [comment]
Merged for 2.7.0 - so once we have it out, you can use it @tim-habitat. I guess we can close that one then ?

**Comment by tim-habitat** [comment]
Amazing thank you ! 🙏 
Absolutely i'll close the issue
