### ISSUE TITLE
Dynamic task state goes from scheduled to failed on scheduler restart

### ISSUE THREAD

**Issue by tnyz** [apache/airflow#33221]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When airflow scheduler restarts, the dynamic mapped tasks goes from scheduled to failed directly without any run attempt and retry is not applied.

### What you think should happen instead

Dynamic mapped task should function like regular task and should continue to be scheduled upon scheduler restart

### How to reproduce

restarting scheduler when a dynamic task is running with task to be scheduled

### Operating System

linux

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please add reproduce example so we can look into it.
