### ISSUE TITLE
Scheduling simultaneous task try before previous try ended

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#33282]
### Apache Airflow version

2.6.3

### What happened

We experience an issue with Airflow scheduling another task try before the previous (first) task instance even ended. E.g. first task instance ended 2:41:46 (SUCCESSfully !) and Airflow started another task try at 2:41:06

### What you think should happen instead

No scheduling of another try before previous ended

### How to reproduce

Use PythonOperator inside TaskGroup with Airflow 2.6.3

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.4.0
apache-airflow-providers-cncf-kubernetes==7.4.0
apache-airflow-providers-common-sql==1.6.1
apache-airflow-providers-ftp==3.4.2
apache-airflow-providers-http==4.5.0
apache-airflow-providers-imap==3.2.2
apache-airflow-providers-postgres==5.6.0
apache-airflow-providers-slack==7.3.2
apache-airflow-providers-sqlite==3.4.3
```

### Deployment

Other Docker-based deployment

### Deployment details

- Own on-premise kubernetes cluster v1.24.6
- python 3.10.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please provide some evidences - excerpt of the log files, DAG examples  - something that provides minimally reproducible example of what you observe. Without it you are asking for a lot of time of others trying to guess and reproduce what you observe.

By providing those details you are increasing your chances that someone will actually have a look, spend time and attempt to diagnose it. Without those - the chances are slim.

**Comment by romanzdk** [comment]
Well it is pretty difficult to do so.. I can provide logs:

First task try:

```
... application logs ...
[2023-08-10, 02:41:49 UTC] {python.py:183} INFO - Done. Returned value was: None
[2023-08-10, 02:41:49 UTC] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=dag-name, task_id=task_group.task_6, execution_date=20230809T000000, start_date=20230810T024106, end_date=20230810T024149
```

second task try:

```
10-233-93-249.data--airflow.pod
*** Found local files:
***   * /var/lib/airflow/root/logs/dag_id=dag-name/run_id=scheduled__2023-08-09T00:00:00+00:00/task_id=task_group.task_6/attempt=2.log
[2023-08-10, 02:41:06 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag-name.task_group.task_6 scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-08-10, 02:41:06 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag-name.task_group.task_6 scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-08-10, 02:41:06 UTC] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-08-10, 02:41:06 UTC] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): task_group.task_6> on 2023-08-09 00:00:00+00:00
```

**Comment by potiuk** [comment]
> Well it is pretty difficult to do so.. I can provide logs:

It even more difficult to help without it. But keep trying - maybe it will be enough for someone to decide to spend their time on it and see if there is enough information they can help with

**Comment by potiuk** [comment]
If you describe more circumstances and try to detail more information DAGs etc, your chances are going up.

**Comment by romanzdk** [comment]
DAG default arguments:
```python
default_args = {
	'owner': 'data-team',
	'depends_on_past': False,
	'start_date': datetime.datetime(2023, 3, 31),
	'sla': datetime.timedelta(hours = 3, minutes = 30),
	'execution_timeout': datetime.timedelta(hours = 3),
	'email_on_failure': False,
	'email_on_retry': False,
	'retries': 3,
	'retry_delay': datetime.timedelta(minutes = 1),
	'retry_exponential_backoff': True,
	'max_retry_delay': datetime.timedelta(minutes = 10),
	'max_active_tis_per_dag': 8,
	'pool': EXECUTION_POOL,
}
```

Using regular PythonOperator with function that uses `paramiko` to SSH into EC2 and perform some operations there and that is it.

**Comment by jens-scheffler-bosch** [comment]
From the logs itself I can confirm in reading time stamps and parallel execution is not desired. But with this information it is not possible to discover any root cause. As I was also debugging deep in scheduler code I very much assume some side effect is causing this. Without understanding the root cause it is hard to think about how to fix such concurrency in a distributed system w/o a central lock (which is a design feature, not a flaw).

I have some more questions on this, this might help finding the root cause:
- How many schedulers do you run?
- How many workers do you run?
- Which setup, Redis+Celery? Which executors?
- Are you sure that no DB Backup especially no DB restore was made during the error cause?
- Were any components of Scheduler, Worker, Redis Queue, Database restarted in the timeframe of the error?
- Is it possible to re-produce this?
- Did it happen once or multiple times?
- Would it be possible to have logs of all workers and schedulers in the time period shared? Would be a longer search for errors but might be the only final evidence.
- What is your [Scheduler] orphaned_tasks_check_interval and scheduler_zombie_task_threshold configuration?
- How long are the affected tasks running (start/end)?
- Do you have configured any specific [celery_broker_transport_options] visibility_timeout options?

**Comment by romanzdk** [comment]
-     How many schedulers do you run? 3
-     How many workers do you run? 1
-     Which setup, Redis+Celery? Which executors? (SequentialExecutor)
-     Are you sure that no DB Backup especially no DB restore was made during the error cause? yes
-     Were any components of Scheduler, Worker, Redis Queue, Database restarted in the timeframe of the error? no
-     Is it possible to re-produce this? sometimes when I retry the dag instance it appears and sometimes no
-     Did it happen once or multiple times? every day since ~ start of the month
-     Would it be possible to have logs of all workers and schedulers in the time period shared? Would be a longer search for errors but might be the only final evidence. will try to get them
-     What is your [Scheduler] orphaned_tasks_check_interval and scheduler_zombie_task_threshold configuration? orphaned_tasks_check_interval = 300.0, scheduler_zombie_task_threshold = 300
-     How long are the affected tasks running (start/end)? approximately 20mins
-     Do you have configured any specific [celery_broker_transport_options] visibility_timeout options? no

**Comment by potiuk** [comment]
* `SequentialExecutor` - THIS IS YOUR PROBLEM.

Never, Ever, under ANY circumstances use Sequential executor for anything else that quick testing /  working with SQLite. 

Plesse DO NOT open issues that your tasks do not work with it for anything that even closely resembles production.

You have enough warnings about it in the documentation, logs, and even warning displayed prominently in the UI of airflow that you should not do it. You are shooting yourself in the foot by ignoring all that warnings.

AND you are completely wasting time of people who want  to help others here with their real issues. 

Please stop doing it and ignorring very clear warnigns you have.

**Comment by romanzdk** [comment]
Sorry, my bad. We have `LocalExecutor` with parallelism set to 10, not `SequentialExecutor`.
