### ISSUE TITLE
Add from_email parameter to EmailOperator

### ISSUE THREAD

**Issue by shakeelansari63** [apache/airflow#33287]
### Description

I am looking for adding from_email parameter to EmailOperator. Currently, the EmailOperator takes the sender email from Airflow Config. 
Which means the emails going from Airflow will always go from same email. 

But we need a way where The EmailOperator user can define the from_email so that sender email can be changed per DAGs. 

And lets make this parameter optional, meaning if user does not provide any email, it will still use the one defined in config.

### Use case/motivation

When developing different DAGs for different Business units which deliver reports to Business users, we need a way to define sender email. So that when business users respond to the email, it goes to right team. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by d2015196** [comment]
Such a nice feature request!

**Comment by potiuk** [comment]
I reopened it, but it needs to be rebased by the author and I think it has been waiting for @hussein-awala review technically - and @Limess -  the easiest way to continue is if you ask there if the author wants to continue and rebase / fix conflicts and if they are ok with it - even taking over the PR and leading it to completion.

**Comment by potiuk** [comment]
I reopened it, but it needs to be rebased by the author and I think it has been waiting for @hussein-awala review technically - and @Limess -  the easiest way to continue is if you ask there if the author wants to continue and rebase / fix conflicts and if they are ok with it - even taking over the PR and leading it to completion.

**Comment by shakeelansari63** [comment]
I am traveling this week. Will work on this soon as I get access to my pc.

**Comment by hussein-awala** [comment]
I will add it to my to-do list for this week 🤦‍♂️

**Comment by shakeelansari63** [comment]
Rebased and resolved conflicts in PR #33288

**Comment by shakeelansari63** [comment]
Closed the PR. Cleaning up the issue as well.
