### ISSUE TITLE
Sanitize filename of the MySQLHook bulk_load parameter

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#33283]
### Body

The `bulk_load` parameter of `MySQLHook` takes a filename parameter that can be passed ";" as well and rather than only bulk_load the file but execute arbitrary SQL commands.

This parameter should be sanitized in order to not allow this. This is not a security vulnerabilyt as this parameter should come from a DAG and there you can run arbitrary command anyway, however we  should fix it anyway.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by d2015196** [comment]
Can you give more details as to what sanitation should look like? Should it not accept SELECT statements? Or some special characters? That would help me if I pick this up.

**Comment by potiuk** [comment]
> Can you give more details as to what sanitation should look like? Should it not accept SELECT statements? Or some special characters? That would help me if I pick this up.

We want to avoid this:

```
fillename = " file; SELECT * FROM DUAL" 
```
