### ISSUE TITLE
Documentation outdated on dockerhub

### ISSUE THREAD

**Issue by alejandrofm** [apache/airflow#33319]
### What do you see as an issue?

On:
https://hub.docker.com/r/apache/airflow

It says in several places that the last version is 2.3.3 like here:
![image](https://github.com/apache/airflow/assets/19591174/640b0e73-dfcb-4118-ae5f-c0376ebb98a3)

### Solving the problem

Update the version and requirements to 2.6.3.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Thanks. I trimmed down the description in the way that we will not need to update it in the future :)
