### ISSUE TITLE
Statsd metrics description is incorrect

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#33377]
### What do you see as an issue?

<img width="963" alt="Screenshot 2023-08-14 at 9 55 11 AM" src="https://github.com/apache/airflow/assets/10162465/bb493eb2-1cfd-45bb-928a-a4e21e015251">
Here dagrun duration success and failure have description where success is stored in seconds while that of failure is shown as stored in milliseconds from the description.

But when checked in code part, where this two metrics are recorded, it is the same duration time that gets stored varying depending on the dag_id run state. 
<img width="963" alt="Screenshot 2023-08-14 at 10 00 28 AM" src="https://github.com/apache/airflow/assets/10162465/53d5aaa8-4c57-4357-b9c2-8d64164fad7c">

### Solving the problem

It looks the documentation description for that statsd metrics is misleading

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shubhamraj-git** [comment]
I am interested in this issue. Could you please assign me?

**Comment by amoghrajesh** [comment]
@Bowrna I am assigning this issue to @shubhamraj-git. This if for the contributors workshop.
