### ISSUE TITLE
SlackAPIPostOperator enhancement

### ISSUE THREAD

**Issue by kolfild26** [apache/airflow#33391]
### Description

I would like to suggest changes in `SlackAPIPostOperator`. 
SlackAPIPostOperator is supposed to send message to Slack. Now, there is no responce left after the execution finished.
Would be good to save its `ts` and `channel` to XCOM once it's finished successfully.
It looks to be quite easy because [here](https://github.com/apache/airflow/blob/main/airflow/providers/slack/operators/slack.py#L84) we actually have [chat.postMessage](https://api.slack.com/methods/chat.postMessage) responce from Slack which includes all needed info. Then we could push it to XCOM.
```
responce = self.hook.call(self.method, json=self.api_params)
ti = kwargs['context']['task_instance']
ti.xcom_push(key="ts", value=responce['ts'])
ti.xcom_push(key="channel", value=responce['channel'])
```
It will look like:
![изображение](https://github.com/apache/airflow/assets/12990695/5405b607-2b3d-40c7-87db-b5f18efda979)
or
![изображение](https://github.com/apache/airflow/assets/12990695/45c3c2c9-5a42-4a4f-98d3-451188086c03)

### Use case/motivation

Motivation is to have access to the timestamps of the sent messages in order to track them futher - change/delete. In Slack the only way to do it is to know its timestamp (& channel of course).
The case is quite specific and may not be usefull for others, so before open a PR, would like to know if this suggestion have chances to be accepted.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
The best thing you can do is to make the change and raise a PR.  Then there can be a discussion about its implementation.  My only comment might be to make the logging of this data to an XCOM an optional parameter.

**Comment by eladkal** [comment]
I think this request is very custom use case that should be handled as custom operator in your deployment.

As for specifics, Xcoms are designed for task communication the use case you are describing is not about that. You simply want tracking. I think what you are really after is to export the event of message sent to a system that handles event tracking/ lineage(?)

Thus I think this use case is better handled in your own deployment. Should more users reply and endurance this request we can revisit. For now, I'm closing this issue

**Comment by kolfild26** [comment]
>  Xcoms are designed for task communication

@eladkal 
Okay, but actually this was the case.
We are using Slack as a batch notification platform. Per the requiments one slack message is shared between several tasks which represent the same business logic unit. See the pic. attached.
![изображение](https://github.com/apache/airflow/assets/12990695/b1d31dcd-51f9-408f-b933-464cd47f6f7a)

Using different messages is a workaround, but the channel feed will be mixed with other messages.

p.s. yes, there are plenty other ways to meet the same, including external storages etc. but not going beyond Airflow functionality looked more useful for me.
All right, will implement this locally, thanks for your feedback anyway.

**Comment by Taragolis** [comment]
Unfortunetly store XComs might be expensive, so better do not create additional XComs without reason in common operators. However you always could create your own operator based on `SlackAPIOperator`, `SlackHook` or `SlackWebhookHook`

```python
from airflow.providers.slack.operators.slack import SlackAPIOperator


class CustomSlackAPIOperator(SlackAPIOperator):

    def construct_api_call_params(self) -> Any:
        return {
            "foo": "bar",
            "spam": "egg",
        }

    def execute(self, **kwargs):
        if not self.api_params:
            self.construct_api_call_params()
        result = self.hook.call(self.method, json=self.api_params)
        # some user-code below
```
