### ISSUE TITLE
Installing static assets for the admin?

### ISSUE THREAD

**Issue by marklit** [apache/airflow#334]
Is there a single download location or folder within a repository that includes the 3rd party static assets for the admin? [jQuery](https://github.com/airbnb/airflow/blob/6635a29b8d4bc0928a6046484cb13b98870d188e/airflow/www/templates/admin/base.html#L75) among various other libraries aren't included in the git repo (which is fair enough) and there doesn't seem to be any notes in the installation documentation.

**Comment by mistercrunch** [comment]
Everything should be included but we had a release (v1.4.0 it think?) that had issues. Please reopen if it's still an issue after upgrading.

**Comment by marklit** [comment]
I installed 1.4.0:

```bash
pip install -e 'git+https://github.com/mistercrunch/airflow.git@efd9e4c4f5dc413308fa958a8038240a38840f67#egg=airflow'
```

and restarted supervisor but it's still showing 404s for the following two assets when I load up the `/admin/` pages:

* /admin/static/vendor/jquery-2.1.1.min.js
* /admin/static/vendor/moment-2.8.4.min.js

(https://github.com/airbnb/airflow/blob/1.4.0/airflow/www/templates/admin/base.html#L75)[airflow/www/templates/admin/base.html] includes jQuery as a local static file located at `/admin/static/vendor/jquery-2.1.1.min.js`. There doesn't appear to be any vendor folder in the [airflow/www/static](https://github.com/airbnb/airflow/tree/1.4.0/airflow/www/static) folder nor does there appear to be a copy of jQuery anywhere in the [code base](https://github.com/airbnb/airflow/search?utf8=%E2%9C%93&q=jQuery).

**Comment by marklit** [comment]
@mistercrunch GitHub isn't offering me the option of re-opening the ticket. Could you do so please?

**Comment by marklit** [comment]
Sorry, there is no need to re-open. pip wasn't seeing the 1.4.1 release tag and nor was git for some reason. I downloaded the zip of 1.4.1 from github and installed that via pip to get 1.4.1. Release 1.4.1 works as expected in relation to this issue.

**Comment by mistercrunch** [comment]
Did `pip install airflow --upgrade` not upgrade for you? Should I be looking into this?

**Comment by marklit** [comment]
Yesterday the root problem I was getting when installing via the git repo was that I couldn't see the tags past 1.1.1. I had freshly cloned the repo from github but that was as far as it could see in terms of tags. I re-traced my steps this morning and I can see the 1.4.1 release and install that specific release via git. I'm not sure there is an issue here as I cannot re-produce any of the problems I was having.

As for my installation all my jobs ran nicely overnight and everything appears to be working well :)
