### ISSUE TITLE
BigQuery with impersonation_chain does not accept custom scopes

### ISSUE THREAD

**Issue by mai-nakagawa** [apache/airflow#33400]
### Apache Airflow version

main (development)

### What happened

I always face the following error when I try to run a BigQuery query that accesses [connected sheets](https://cloud.google.com/bigquery/docs/connected-sheets), when I use `impersonation_chain`.
```
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2203, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1571, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/opt/python3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/opt/python3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/opt/python3.8/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials.
```

I think it's because it always uses a default scope: `https://www.googleapis.com/auth/cloud-platform`. We can set scopes with Airflow connections ([code](https://github.com/apache/airflow/blob/0f73647bdab79ac6c30961222924f6166f75b55a/airflow/providers/google/common/hooks/base_google.py#L395-L404)). However, we cannot set scopes with `impersonation_chain`.

### What you think should happen instead

I would like the operators and hooks to accept custom scope - `https://www.googleapis.com/auth/drive` in this case.

### How to reproduce

1. Prepare a [connected sheet](https://cloud.google.com/bigquery/docs/connected-sheets).
2. Run a task with BigQueryInsertJobOperator (or the like) to run a BigQuery query against the connected sheet, using `impersonation_chain`.
3. You'll face the error:
    ```
    403 Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials.
    ```

### Operating System

Linux

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@mai-nakagawa Thanks for logging this.  I also know this is a problem so I'm keen to see if this can be addressed.  Are you aware of what the solution to this might be?

**Comment by mai-nakagawa** [comment]
@nathadfield Thanks for addressing the matter.

Airflow connection already have a functionality to set scope. So, the only `impersonation_chain` needs scope. My quick idea is to create a class for impersonation_chain to keep the service account email address and scope as follows. What do you think?
```
@dataclass
class ImpersonationChain:
    chain: ImpersonationServiceAccountWithScope | Sequence[ImpersonationServiceAccountWithScope]


@dataclass
class ImpersonationServiceAccountWithScope:
    email_address: str
    scope: str | None = None
```

**Comment by nathadfield** [comment]
@mai-nakagawa Ah, ok!  Well, I would suggest that you make a change and raise a PR then it will no doubt come up for discussion with the committers.  I will assign the issue to you and look forward to this improvement!

**Comment by mai-nakagawa** [comment]
@nathadfield Oh, ok. I'll try when I have time.

**Comment by nathadfield** [comment]
@mai-nakagawa Sorry, I didn't want to assume that you would implement this.  It just seemed like you were already working on it.  I can un-assign you if you'd prefer.

**Comment by mai-nakagawa** [comment]
@nathadfield Can you please un-assign me then? I might try to fix by myself when I have time, however, I can't guarantee. Sorry for confusion.

**Comment by nathadfield** [comment]
No problem.  I'll ask around to see if other people have some thoughts on this too.

**Comment by mai-nakagawa** [comment]
Possible workaround:

- Step1: Extend a BigQueryHook class and overwrite [`GoogleBaseHook#scopes`](https://github.com/apache/airflow/blob/0f73647bdab79ac6c30961222924f6166f75b55a/airflow/providers/google/common/hooks/base_google.py#L395-L404) method as follows:
    ```python
    class BigQueryHookWithScopes(BigQueryHook):
      def __init__(self, scopes: Sequence[str], *args, **kwargs):
          super().__init__(*args, **kwargs)
          self._scopes = scopes
  
      @property
      def scopes(self) -> Sequence[str]:
          return self._scopes
    ```
- Step2: Extend a BigQuery related Operators to use the above hook as follows:
    ```python
    class BigQueryInsertJobOperatorWithScope(BigQueryInsertJobOperator):
        def __init__(self, scopes, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.scopes = scopes
    
        def execute(self, context):
            self.hook = BigQueryHookWithScopes(
                scopes=self.scopes,
                gcp_conn_id=self.gcp_conn_id,
                use_legacy_sql=self.use_legacy_sql,
                delegate_to=self.delegate_to,
                location=self.location,
                impersonation_chain=self.impersonation_chain,
            )
            super().execute(context)
    ```

**Comment by aritra24** [comment]
I can try taking this up if it's available

**Comment by nathadfield** [comment]
@aritra24 I think that would be most welcomed.

**Comment by phanikumv** [comment]
Assigned to you @aritra24

**Comment by aritra24** [comment]
@nathadfield I've been a bit occupied with work and lost track of this, I can try working on this by early to mid next week I presume.

**Comment by nathadfield** [comment]
@aritra24 No problem, I've been there myself.

**Comment by aritra24** [comment]
@nathadfield this might need to be assigned to someone else, I tried it out for a few days now and unfortunately my lack of experience with gcp is really slowing down progress and it might be better handled by someone with better grasp on this.

**Comment by pierre-comalada** [comment]
Any updates on this issue ?

**Comment by buu-nguyen** [comment]
> Possible workaround:
> 
>     * Step1: Extend a BigQueryHook class and overwrite [`GoogleBaseHook#scopes`](https://github.com/apache/airflow/blob/0f73647bdab79ac6c30961222924f6166f75b55a/airflow/providers/google/common/hooks/base_google.py#L395-L404) method as follows:
>       ```python
>       class BigQueryHookWithScopes(BigQueryHook):
>         def __init__(self, scopes: Sequence[str], *args, **kwargs):
>             super().__init__(*args, **kwargs)
>             self._scopes = scopes
>       
>         @property
>         def scopes(self) -> Sequence[str]:
>             return self._scopes
>       ```
> 
>     * Step2: Extend a BigQuery related Operators to use the above hook as follows:
>       ```python
>       class BigQueryExecuteQueryOperatorWithScope(BigQueryExecuteQueryOperator):
>           def __init__(self, scopes, *args, **kwargs):
>               super().__init__(*args, **kwargs)
>               self.scopes = scopes
>       
>           def execute(self, context):
>               self.hook = BigQueryHookWithScopes(
>                   scopes=self.scopes,
>                   gcp_conn_id=self.gcp_conn_id,
>                   use_legacy_sql=self.use_legacy_sql,
>                   delegate_to=self.delegate_to,
>                   location=self.location,
>                   impersonation_chain=self.impersonation_chain,
>               )
>               super().execute(context)
>       ```

Hey, thanks for the workaround. I just noticed that GoogleBaseHook seems to already pick up scopes from connection's field(https://github.com/apache/airflow/blob/0f73647bdab79ac6c30961222924f6166f75b55a/airflow/providers/google/common/hooks/base_google.py#L402C44-L402C44).
Is there a specific reason to override it? Just curious about this approach.

**Comment by mai-nakagawa** [comment]
Yes, it picks up scopes from Airflow Connection's field. The problem is that we cannot set scopes with impersonation_chain, as written in the description field of this GitHub issue.
