### ISSUE TITLE
Trim down the PyPI readme

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#33505]
### Body

The PyPI README is far too long for the PyPI page.  Just basic summary is needed and links to documentation, changelog,GitHub page.

We have now dedicated Changelog page and there should be a "project-url" pointing to it (same as in Providers). 

Some images (AWS) are broken and they should not be there anyway.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajkoti** [comment]
I could try working on this if that sounds okay

**Comment by potiuk** [comment]
Feel free.

**Comment by uranusjr** [comment]
> Just basic summary is needed and links to documentation, changelog, GitHub page.

I don’t think we even need the links? They are already available in the sidebar on the left anyway.

**Comment by potiuk** [comment]
> don’t think we even need the links? They are already available in the sidebar on the left anyway.

Yep. This is what I meant :)
