### ISSUE TITLE
Airflow 2.7 is incompatible with SodaCore versions 3.0.24 and beyond

### ISSUE THREAD

**Issue by nathadfield** [apache/airflow#33577]
### Apache Airflow version

2.7.0

### What happened

When trying to install SodaCore on Airflow 2.7, the following error is received due to a conflict with `opentelemetry-api`.

```
ERROR: Cannot install apache-airflow==2.7.0 and soda-core==3.0.48 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow 2.7.0 depends on opentelemetry-api==1.15.0
    soda-core 3.0.48 depends on opentelemetry-api~=1.16.0
```

SodaCore has depended on `opentelemetry-api~=1.16.0` ever since v[3.0.24](https://github.com/sodadata/soda-core/releases/tag/v3.0.24).

### What you think should happen instead

Airflow needs to support versions of `opentelemetry-api` 1.16.x.

### How to reproduce

Simply running the following commands to install the two packages should reproduce the error.

```
$ python3 -m venv /tmp/soda                                                                                         
$ /tmp/soda/bin/pip install apache-airflow==2.7.0 soda-core-bigquery==3.0.48
```

### Operating System

n/a

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Fixed. We will have otel 1.15+ supported for 2.7.1. That was a bit tricky and required celery bump :)

**Comment by potiuk** [comment]
Thanks for raising it @nathadfield -> I completely forgot about this one when @ferruzzi added opentelmetry I left it as unsolved issue. Now we got it solved.

**Comment by nathadfield** [comment]
@potiuk Awesome!  I'll look forward to 2.7.1 then. :)

**Comment by potiuk** [comment]
It's gonna be sooner rather than later :)

**Comment by ferruzzi** [comment]
Thanks for sorting this out!     When I added OTel, I wasn't able to get pip to resolve any version other than that one very specific version so I had to pin it.  I just saw Jarek's other thread where he explained the fix.   That's great.
