### ISSUE TITLE
Airflow 2.7 Webserver unreacheable with new authentication manager

### ISSUE THREAD

**Issue by cesar-vermeulen** [apache/airflow#33586]
### Apache Airflow version

2.7.0

### What happened

When connecting to the Airflow UI, we get the following message:

```
> Python version: 3.11.4
> Airflow version: 2.7.0
> Node: redact
> -------------------------------------------------------------------------------
> Error! Please contact server admin.
```

If we investigate further and we look at the Kubernetes pod logs, we see that following error message is thrown:

>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/views.py", line 989, in index
>     return self.render_template(
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/views.py", line 694, in render_template
>     return super().render_template(
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/baseviews.py", line 339, in render_template
>     return render_template(
>            ^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
>     return _render(app, template, context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
>     rv = template.render(context)
>          ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
>     self.environment.handle_exception()
>   File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/templates/airflow/dags.html", line 44, in top-level template code
>     {% elif curr_ordering_direction == 'asc' and request.args.get('sorting_key') == attribute_name %}
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/templates/airflow/main.html", line 21, in top-level template code
>     {% from 'airflow/_messages.html' import show_message %}
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
>     {% import 'appbuilder/baselib.html' as baselib %}
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
>     {% block body %}
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 8, in block 'body'
>     {% block navbar %}
>   File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 10, in block 'navbar'
>     {% include 'appbuilder/navbar.html' %}
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/templates/appbuilder/navbar.html", line 53, in top-level template code
>     {% include 'appbuilder/navbar_right.html' %}
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/www/templates/appbuilder/navbar_right.html", line 71, in top-level template code
>     <span>{% for name in user_names %}{{ name[0].upper() }}{% endfor %}</span>
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
>     return getattr(obj, attribute)
>            ^^^^^^^^^^^^^^^^^^^^^^^
> jinja2.exceptions.UndefinedError: str object has no element 0
> 

### What you think should happen instead

Show the Airflow UI

### How to reproduce

The deployment is done using the official Airflow helm chart with Azure AD authentication on the webserver.

As soon as we did the upgrade to Airflow 2.7, the webserver became unreacheable when trying to access it with the error shown above.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==7.4.2
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-microsoft-azure==4.3.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Webserver config:
AUTH_TYPE = AUTH_OAUTH
AUTH_ROLE_ADMIN = 'Admin'
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Admin"

OAUTH_PROVIDERS = [
    {
    "name": "azure",
    "icon": "fa-microsoft",
    "token_key": "access_token",
    "remote_app": {
        "client_id": "${airflow_client_id}",
        "client_secret": "${airflow_client_secret}",
        "api_base_url": "https://login.microsoftonline.com/${airflow_tenant_id}/oauth2",
        "client_kwargs": {
            "scope": "User.read name preferred_username email profile",
            "resource": "${airflow_client_id}",
        },
        "request_token_url": None,
        "access_token_url": "https://login.microsoftonline.com/${airflow_tenant_id}/oauth2/token",
        "authorize_url": "https://login.microsoftonline.com/${airflow_tenant_id}/oauth2/authorize",
        },
    },
]

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by cesar-vermeulen** [comment]
These are not set; this is a screenshot of same user but in different (Airflow 2.6.2) environment:
![image](https://github.com/apache/airflow/assets/94971679/6705fcc0-784d-432b-a560-c025a2706cd4)
 
I checked our Azure AD and there the first and lastname where not set. I asked our system admins to set these, and retried, but did not work. The screenshot above is also from after these updates.

**Comment by rjtshrm** [comment]
The issue can be resolved it you manually update the first_name and the last_name in the airflow db ab_user. For me it worked. Although it is not a good way, it should be done automatically I guess after the upgrade. Let me know, if it is resolved in automatic way ;)

**Comment by vincbeck** [comment]
But this is something we definitely should handle. I'll create a PR to fix it. Thanks for the heads up!

**Comment by rjtshrm** [comment]
But why is it Mandatory in 2.7, earlier version works fine without first and last name

**Comment by vincbeck** [comment]
When implementing #32217 which caused the issue, I thought this use case (no first name and no last name) did not exist. I was wrong. #33617 fixes the bug

**Comment by vincbeck** [comment]
> But why is it Mandatory in 2.7, earlier version works fine without first and last name

It is still not mandatory, it is a bug

**Comment by potiuk** [comment]
Scheduled for 2.7.1.

**Comment by rjtshrm** [comment]
Thanks @vincbeck. There is another issue when using oauth auth, I get error on login but it was working fine on previous version of airflow

```
[2023-08-23T11:27:20.737+0000] {manager.py:1129} ERROR - OAUTH userinfo does not have username or email {}
[2023-08-23T11:27:20.738+0000] {app.py:1744} ERROR - Exception on /oauth-authorized/aws_cognito [GET]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/flask_appbuilder/security/views.py", line 693, in oauth_authorized
    return redirect(self.appbuilder.get_url_for_login)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirflowAppBuilder' object has no attribute 'get_url_for_login'
```

Do you have any idea about this behaviour?

**Comment by beatstream69** [comment]
Same issue as above, reverting to 2.6.3 =(

**Comment by rjtshrm** [comment]
After lot of time spent and debugging found that in earlier version we were using **FAB_SECURITY_MANAGER_CLASS** to override the custom auth. But here it is expecting it to SECURITY_MANAGER_CLASS. https://github.com/apache/airflow/blob/2ae1c10bfa59d1b2b5d8d453cd64d9858cb18c0b/airflow/www/extensions/init_appbuilder.py#L657 

As it can be seen that  if SECURITY_MANAGER_CLASS is not set then it uses default AirflowSecurityManager where the custom auth login for aws cognito was missing and hence was getting the error.

Although in the airflow 2.7.0 docs https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html, FAB_SECURITY_MANAGER_CLASS is mentioned.

Also, make sure SECURITY_MANAGER_CLASS to class type not a string as in FAB_SECURITY_MANAGER_CLASS.

@potiuk @vincbeck Can you confirm this behaviour or am i missing something

**Comment by vincbeck** [comment]
@rjtshrm. Yep, looks like another issue. I removed `get_url_for_login` because we no longer use it but I did not know it was used internally by FAB. Definitely some test missing here. I should have tested with oauth. Fix here: #33660

**Comment by vincbeck** [comment]
> @potiuk @vincbeck Can you confirm this behaviour or am i missing something

You are correct, thanks for the catch! It is definitely an error in the documentation which I also fixed as part of #33660. But this is a documentation glitch only, in the code it has been `SECURITY_MANAGER_CLASS` for a while

**Comment by rjtshrm** [comment]
Thanks @vincbeck , so ideally we should use SECURITY_MANAGER_CLASS instead of the FAB one.

**Comment by vincbeck** [comment]
Correct. `FAB_SECURITY_MANAGER_CLASS` does not exist
