### ISSUE TITLE
Impossible to use sftp provider on AWS MWAA 2.6.3

### ISSUE THREAD

**Issue by MJB127** [apache/airflow#33588]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I tried to use the sftp provider on MWAA versions 2.6.3 that is available with Python 3.10.
However, this provider depends on paramiko, which in turn depends on bcrypt library. 
The assorted libs are provided in a plugins.zip bundle as I'm using the private server option (this has outgoing access disabled for MWAA).
Now bcrypt doesn't provide a release for 3.10 and MWAA enforces the minor Python version. 
As such, installation of the requirements fails. SFTP provider can be used on workers, but its not available for the webserver (invisible in the provider list, can't set up a connection through the UI). 

### How to reproduce

1.  Prepare requirements.txt using the following constraints https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt and containing apache-airflow-providers-sftp==4.3.1.
2. Download the dependencies with pip download
3. Pack the dependencies into plugins.zip. Note it should contain the bcrypt wheel. For me pip installs version for Python 3.6 while running on Python 3.10. No version of bcrypt is available for Python 3.10
4. Prepare another requirements.txt, remove constraints and add (force to use the libs from the zip) 
--find-links /usr/local/airflow/plugins
--no-index
6. Upload plugins and requirements file to S3 
7. Create an MWAA instance using these two files
8. Once it's created look into Cloudwatch logs, there should be a message "No matching distribution found for bcrypt>=3.2"

### Operating System

Amazon Linux

### Versions of Apache Airflow Providers

 apache-airflow-providers-sftp==4.3.1
Airflow 2.6.3

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
this is an issue with MWAA , not airflow you should open the issue with their support.
