### ISSUE TITLE
Add a compatibility with Opensearch search for log management

### ISSUE THREAD

**Issue by djadeau** [apache/airflow#33619]
### Description

Dear Airflow team,

Today, it is possible to configure Airflow to read logs of the tasks from ElasticSearch.

Is it possible to add the support of Opensearch as source of the task logs ?

Thank you.

### Use case/motivation

Log sinks are often used in large companies. Concentrate logs in a log sinks is very practical for searches.

Opensearch and Elasticsearch have similar methods, so it should not create major change.

ElasticSearch has added some checks in the client library, so it is not possible anymore to Opensearch with the elasticsearch library.

Cloud providers such as OVHCloud or Scaleway, propose Opensearch as log manager as a service.

Opensearch is a full opensource solution contrary to Elasticsearch.

### Related issues

No

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@cjames23 is working on opensearch hook

**Comment by cjames23** [comment]
Sorry about the delay on this. If no one has made any of the Open Search capabilities I am almost complete with the hook and some cursory operators for creating indexes, documents and searching an index. I need to finish writing unit and system tests and documentation.

**Comment by cjames23** [comment]
@eladkal do you want to assign this to me with the two open PRs I have.

**Comment by cjames23** [comment]
OpenSearch provider was merged but does not have log integration yet for airflow task log integrations. Currently working on adding support for the AWS Managed version of OpenSearch and then I will begin working on the log integrations.

**Comment by erikvatt** [comment]
@cjames23 Have you started working on OpenSearch log integration?

**Comment by eladkal** [comment]
I think that https://github.com/apache/airflow/pull/34693 has most of the needed logic for AWS integration it just require adjustments after the OpenSearch provider was implemented. Once this is completed we can start work on log integration.
Not sure though if @cjames23 is working on it

**Comment by ftforce** [comment]
Any updates on this?
