### ISSUE TITLE
Long custom operator name overflows in graph view

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#33693]
### Apache Airflow version

main (development)

### What happened

1. There was support added to configure UI elements in graph view in https://github.com/apache/airflow/issues/31949
2. Long custom operator names overflow out of the box. Meanwhile long task id are truncated with ellipsis. I guess same could be done by removing width attribute that has "fit-content" and "noOfLines" should be added.

Originally wrapped before commit : 

![Screenshot 2023-08-24 at 18-05-06 gh32757 - Grid - Airflow](https://github.com/apache/airflow/assets/3972343/2118975d-8467-4039-879f-13a87d9bcd79)

main : 

![Screenshot 2023-08-24 at 18-17-31 gh32757 - Grid - Airflow](https://github.com/apache/airflow/assets/3972343/7d0b86e1-39c3-4fb4-928c-1ea54697128e)

### How to reproduce

Sample dag to reproduce the issue in UI

```python
from datetime import datetime
from airflow.decorators import dag, task
from airflow.models.baseoperator import BaseOperator
from airflow.operators.bash import BashOperator

class HelloOperator(BashOperator):
    custom_operator_name = "SampleLongNameOfOperator123456789"

@dag(dag_id="gh32757", start_date=datetime(2023, 1, 1), catchup=False)
def mydag():

    bash = BashOperator(task_id="t1", bash_command="echo hello")
    hello = HelloOperator(task_id="SampleLongTaskId1234567891234890", bash_command="echo test")
    bash2 = BashOperator(task_id="t3", bash_command="echo bye")

    bash >> hello >> bash2

mydag()
```

### Operating System

Ubuntu

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @bbovenzi

**Comment by ivan-afonichkin** [comment]
I would be happy to work on this one, could you please assign it to me?

**Comment by potiuk** [comment]
Assigned! I hope you will prove that CSS is, indeed, awesome :)
