### ISSUE TITLE
Feature Request : Pass Arguments to DAG via Backfill and Run Commands

### ISSUE THREAD

**Issue by r39132** [apache/airflow#337]
I am using the CLI "backfill" command as part of some automation at Agari. 

Essentially, we are at a point in our development cycle where we need to clear and refresh 30 days of data every day -- this is because we need to regenerate historical data using new model versions and we are rapidly iterating on model versions. It is not enough for us to only run for one day because we need data points that only occur at single points in time in the past to test our models. 

I'm leveraging `airflow backfill` for that purpose. However, since our DAG is designed for daily runs and being leverage by this automation, I'd like to skip (mark success) certain tasks. 

I'd like to pass parameters via the backfill command line directly to the DAG. The immediate use-case if to let the DAG know it is being run as a backfill, so that some of my tasks can run No-Ops.

**Comment by georgebdavis** [comment]
Just want to flag that this relates to some discussion re: triggered DAGs in https://github.com/airbnb/airflow/issues/289 (and now the roadmap!) - in many cases when triggering a DAG for an on-demand analysis, it would be handy to pass some metadata that was accessible to DAG tasks.  Viewed in this way, there are a lot of common semantics between backfill use cases and on-demand use cases.
