### ISSUE TITLE
Disable ReadtheDocs

### ISSUE THREAD

**Issue by wolff-sg** [apache/airflow#33704]
### What do you see as an issue?

The entire ReadtheDocs for Airflow is outdated--stopped at version 1.10, but still gets shown as "latest".

This means someone web searching specifying Airflow things [0] can easily get to ReadtheDocs and get stale Airflow information [1] that looks advertised as up to date ("latest").

Specifically for example, RTD [1] says latest CLI command for dag backfill task regex filtering is `--task_regex` when in fact the latest is `--task-regex` per [2].

[0] https://www.google.com/search?q=airflow+%22dags+trigger%22+regex
[1] https://airflow-apache.readthedocs.io/en/latest/cli-ref.html#dags
[2] https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#dags

### Solving the problem

Remove Airflow from ReadtheDocs.  The old pages are there for historic reasons, but at this point the history is apparently such that a sync to ReadtheDocs is not feasible.

(Some pages on ReadtheDocs do just point to Apache docs, which is fine, like https://airflow.readthedocs.io/en/stable/.  But the pages at https://airflow-apache.readthedocs.io/ do seem confusing and are easily found from web searches.  So either point all to Apache, or simply remove all.  Something like that.)

### Anything else

This was discussed in Airflow Slack #documentation channel thread at https://apache-airflow.slack.com/archives/CJ1LVREHX/p1692898453109329 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc: @kaxil @ashb - > who has access to read the docs for Airflow? Can we drop it somehow ?

**Comment by potiuk** [comment]
We might want to run lazy consensus but I think it's about the time we just drop it.

**Comment by kaxil** [comment]
Yup I will delete it

**Comment by kaxil** [comment]
Btw https://airflow-apache.readthedocs.io/ is not used by us; someone random on the internet might have created it. The official docs were at https://airflow.readthedocs.io/

**Comment by kaxil** [comment]
After some back and forth, the site (https://airflow-apache.readthedocs.io/ ) has been delisted

```
$ curl https://airflow-apache.readthedocs.io/robots.txt    
# Delisted project, removing from search indexing
# See: https://docs.readthedocs.io/en/stable/unofficial-projects.html
User-agent: *
Disallow: /
$
```

**Comment by potiuk** [comment]
cool!
