### ISSUE TITLE
Upgrade Azure File Share to v12

### ISSUE THREAD

**Issue by alexbegg** [apache/airflow#33850]
### Description

In November 2019 the Azure File Share python package was "renamed from `azure-storage-file` to `azure-storage-file-share` along with renamed client modules":
https://azure.github.io/azure-sdk/releases/2019-11/python.html

Yet it is 2023 and we still have `azure-storage-file>=2.1.0` as a dependency for `apache-airflow-providers-microsoft-azure`. I am opening this issue to propose removing this over three year old deprecated package.

I am aware of the challenges with earlier attempts to upgrade Azure Storage packages to v12 as discussed in https://github.com/apache/airflow/pull/8184. I hope those challenges are gone by now? Especially since `azure-storage-blob` already has been upgraded to v12 in this provider (https://github.com/apache/airflow/pull/12188).

Also,

I believe this is why `azure-storage-common>=2.1.0` is also still a dependency. Which is listed as deprecated on https://azure.github.io/azure-sdk/releases/deprecated/python.html:
- I have not fully investigated but I believe it is possible once we upgrade to `azure-storage-file-share` v12 this provider will no longer need `azure-storage-common` as a dependency as as it just contains the common code shared by the old 2.x versions of "blob", "file" and "queue". We already upgraded "blob" to v12, and we don't have "queue" support, so "file" is the last remaining.
- Also removing "azure-storage-common" will remove the warning:
    ```
    ... site-packages/azure/storage/common/_connection.py:82 SyntaxWarning: "is" with a literal. Did you mean "=="?
    ```
    (a fix was merged to "main" in 2020 however Microsoft no longer will release new versions of this package)

I _used_ to be an active Azure Storage user (up until last year), but I am now mainly an AWS user, so I would appreciate it if someone else will create a PR for this, but if nobody does I suppose I could look into it.

### Use case/motivation

Mainly to remove deprecated packages, and secondly to remove one SyntaxWarning

### Related issues

This is the related issue to upgrade `azure-storage-blob` to v12: https://github.com/apache/airflow/issues/11968

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @pankajastro

**Comment by pankajastro** [comment]
> cc @pankajastro

Thanks @alexbegg for raising it. 
@eladkal I have been working on upgrading it but there might be some breaking changes, I'll a PR soon for the same.
