### ISSUE TITLE
Log appropriate trigger cancel reasons

### ISSUE THREAD

**Issue by pankajkoti** [apache/airflow#33877]
### Description

Continuing the conversation from the topic covered in #31720, we successfully managed the cancellation resulting from trigger timeout within pull request #31757. Within the same pull request, a generic cancellation log was introduced. This log, however, also surfaces during instances where the trigger completes successfully. To address this matter, pull request #33874 is in progress, aiming to eliminate this generalized trigger log. This alteration is prompted by user feedback, revealing that the presence of the general log caused confusion by implying errors even in cases of successful triggers.

In accordance with the deliberations in issue #31720, it is necessary for us to implement a system that facilitates the communication of pertinent causes for diverse trigger cancellation scenarios. And we need to then incorporate logic designed to convey specific cancellation explanations and subsequently record corresponding detailed cancellation logs.

### Related issues

#31720 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Closed by #33874
