### ISSUE TITLE
Add verification if short options in breeze are repeated

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#33958]
### Body

When you have two option with the same short flag - in the same command, only one can be used - for example before https://github.com/apache/airflow/pull/33957 `static-checks -t` yielded `--image-tag` not `--static-checks`.

We should check if any of the commands of breeze has such flag duplicated. 

This should be done in the place where we calculate hash from the context dictionary in setup_commands.py:

```
def get_command_hash_export() -> str:
    import rich_click

    hashes = []
    with Context(main) as ctx:
        the_context_dict = ctx.to_info_dict()
```

This is used in `breeze setup regenerate-command-images` and the `the_context_dict` contains information about all commands and their flags, so we should be able to easily check if some flags are duplicated in all commands.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
CC: @amoghrajesh -> maybe another one for you :)

**Comment by amoghrajesh** [comment]
Self assigned this one. @potiuk 
Will take it up as soon as I have some bandwidth!
