### ISSUE TITLE
please disable pinwheel animation as it violates ada guidelines

### ISSUE THREAD

**Issue by mj-dd** [apache/airflow#34019]
### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
May I know please on which pages you mean exactly?

From a quick recall, I can't think of an animation that the user cannot pause. Would be nice if you could provide more details so that we can address this.

**Comment by mj-dd** [comment]
the pinwheel is on all pages. and it cannot be paused. anytime the mouse cursor incidentally crosses it endlessly animates.

**Comment by pankajkoti** [comment]
okay, trying to understand more here. The animation starts only upon hover (so that is the state of change) and when you move away, the animation stops. Besides there is no meaningful content that would be hidden if we don't hover over it.
So if someone does not want to see the animation they can just stop hovering over it, no? 

Or am I missing something more here wrt ADA? I am just reading more about ADA over the Internet as this is new to me, so trying to understand more :-)

**Comment by mj-dd** [comment]
you should avoid using unnecessary animation and this animation is unnecessary (and esp need not be continuous). is this a difficult change?
[
](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions)

**Comment by mj-dd** [comment]
i believe this is the change:[ forked example](https://github.com/apache/airflow/compare/main...mj-dd:airflow:sample-fork)

thanks!!!

**Comment by potiuk** [comment]
I think this should be also deferred to our designers and UI expersts. I personally find this animation has an estethical funciton only, and I think it's rather difficult to trigger accidentally (which really ADA guidelines are about). I believe the guidelines are mostly to protect people with vestibular disorder, but I think in this case this is something subtle and not something that you can trigger accidentally when trolling etc. But we must leave it to our UI experts.

Thaks for raising our attention to it and posting link to guidelines - I marked it as UI area.

BTW. Guidelines like that are just that - guidelines and we might choose to not follow them. 

For the future my suggestion @mj-dd - if you want to be succesful in your quest I recommend you to put more effort in politely asking for it and explaining what will be the harm made, who might suffer and how and point to relevant parts of guidelines and explain how this particular change might affect those users.

**Comment by pankajkoti** [comment]
I tried to remove the infinite animation but keep a spin for 1.5s and then it stops. Hope that is acceptable.

I personally like the spin, gives a nice play feel, but happy to hear opinions and if it absolutely non-compliant then yes, we need to remove it

**Comment by potiuk** [comment]
Yeah. Stopping after 1.5s is a good idea @pankajkoti :D

**Comment by mj-dd** [comment]
> I think this should be also deferred to our designers and UI expersts. I personally find this animation has an estethical funciton only, and I think it's rather difficult to trigger accidentally (which really ADA guidelines are about). I believe the guidelines are mostly to protect people with vestibular disorder, but I think in this case this is something subtle and not something that you can trigger accidentally when trolling etc. But we must leave it to our UI experts.
> 
> Thaks for raising our attention to it and posting link to guidelines - I marked it as UI area.
> 
> BTW. Guidelines like that are just that - guidelines and we might choose to not follow them.
> 
> For the future my suggestion @mj-dd - if you want to be succesful in your quest I recommend you to put more effort in politely asking for it and explaining what will be the harm made, who might suffer and how and point to relevant parts of guidelines and explain how this particular change might affect those users.

the ada recommendation seems to be no unnecessary animations. the purpose of the formalized ada guidelinis to spare the millions of individual affected persons from making their own separate arguments. i agree with allowing dedicated designers to make these decisions.

**Comment by pankajkoti** [comment]
yes thank you @mj-dd . It's good to learn about these guidelines :)

**Comment by potiuk** [comment]
>  guidelines to spare the millions of individual affected persons from making their own separate arguments

Sure. But if you do not explain where you are coming from and which guidelines you are talking about and which people are afffected, you might come as a rude person. Simply proactively epxlaining your reasoning in point goes a long way. And I would heartily recoommend you to do it if you want to be more successful with it .

**Comment by potiuk** [comment]
Like we just learned about it after you posted it eventually :). That was rather useful

**Comment by mj-dd** [comment]
yeah i should have included the link originally. thanks for your patience!
