### ISSUE TITLE
Split Celery integration tests in to "redis", "rabbitmq", "sqlalchemy"

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34032]
### Body

Our celery integration tests assume only "redis" as both broker and result backend, however, we should be able to relatively easily add a few more integration configurations there. 

That would - for example - make it possible to detect earlied that Celery 5.3.3 and 5.3.2 is broken when SQLalchemy result backend is used https://github.com/celery/celery/issues/8470 - resulting in https://github.com/apache/airflow/pull/34031  and then it would not even make it into our constraints and our "canary" builds could detect it.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
Please assign me :)

**Comment by shahar1** [comment]
@potiuk While implementing #39994, I wasn't exactly sure how to treat `sqlalchemy` in this case, as it is a Python package rather than a service - I'd be happy if you could elaborate.

**Comment by potiuk** [comment]
It was more "DB" (not sure where sqlalchemy was from) - I believe (but I might be wrong now) - Celery also supports DB as a broker. It as a long time ago so I might misremember and could be it was a sort of "mental shortcut"
