### ISSUE TITLE
UI Grid error when DAG has been removed

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#34058]
**Reproduce on main:**
- Run a DAG
- Rename the DAG
- Wait for dag file processor to remove the deleted DAG and add the new one. (Old Dag should not appear on the home page anymore)
- Go to the Browse DAGRUN page.
- Click on a DagRun of the deleted DAG, as if you want to see the 'details/grid' of that old dag run

More info and screenshots here:
https://github.com/notifications#discussioncomment-6898570

![image](https://github.com/apache/airflow/assets/14861206/7af81643-6278-4d90-a20f-6aa7b259ce59)

**Comment by SbtrktCtrl** [comment]
Legends! thank you.

**Comment by pierrejeambrun** [comment]
Did you run it with breeze ? Or ran the webserver in debug mode ?

We see that there is an error, you just don’t have the stack trace, meaning that the server is not in debug mode.

Having an error is not expected.

**Comment by potiuk** [comment]
Yes. As mentioned in the first line of what you should do "gather the relevant information (detailed log with errors...".

You need to look there. Exposing more information in the UI is a potential security issue. No application in produciton mode should EVER do that.

**Comment by Abhishek-kumar-samsung** [comment]
> Did you run it with breeze ? Or ran the webserver in debug mode ?
> 
> We see that there is an error, you just don’t have the stack trace, meaning that the server is not in debug mode.
> 
> Having an error is not expected.

I ran using breeze start-airflow, it won't occur there?

**Comment by Abhishek-kumar-samsung** [comment]
> Yes. As mentioned in the first line of what you should do "gather the relevant information (detailed log with errors...".
> 
> You need to look there. Exposing more information in the UI is a potential security issue. No application in produciton mode should EVER do that.

Oh okay.

**Comment by potiuk** [comment]
> I ran using breeze start-airflow, it won't occur there?

You can add `--dev-mode` flag when you run `start-airflow` - then instead of the "ooops" screen you will see the screen that @pierrejeambrun posted above - with more details and debugging capabilities

**Comment by Abhishek-kumar-samsung** [comment]
> > I ran using breeze start-airflow, it won't occur there?
> 
> You can add `--dev-mode` flag when you run `start-airflow` - then instead of the "ooops" screen you will see the screen that @pierrejeambrun posted above - with more details and debugging capabilities

Thankyou
Now i am able to reproduce.
