### ISSUE TITLE
Toggling TaskGroup toggles all TaskGroups with the same label on Graph/Grid

### ISSUE THREAD

**Issue by Usiel** [apache/airflow#34066]
### Apache Airflow version

main (development)

### What happened

When you have 2 TaskGroups with the same `group_id` (nested under different parents), toggling either of them on the UI (graph or grid) toggles both.

<img src="https://cdn-std.droplr.net/files/acc_1153680/9Z1Nvs" alt="image" width="50%">

### What you think should happen instead

Only the clicked TaskGroup should be toggled. They should be distinguishable since they have the parent's group_id as prefix.

### How to reproduce

```
from datetime import datetime

from airflow.models import DAG
from airflow.operators.empty import EmptyOperator
from airflow.utils.task_group import TaskGroup

with DAG(
    "my_dag",
    start_date=datetime(2023, 9, 4),
):
    with TaskGroup(group_id="a"):
        with TaskGroup(group_id="inner"):
            EmptyOperator(task_id="dummy")

    with TaskGroup(group_id="b"):
        with TaskGroup(group_id="inner"):
            EmptyOperator(task_id="dummy")
```

### Operating System

-

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
I just tested the DAG on the latest main branch and encountered the same issue. As you already send a PR, I'll assign this issue to you.
