### ISSUE TITLE
Delete record of dag run is not being logged in audit logs when clicking on delete button in list dag runs

### ISSUE THREAD

**Issue by Raul824** [apache/airflow#34069]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When doing a list dag runs and doing check box selection and in actions delete dags is performed in audit logs we get an event with "action_muldelete".

But if instead of using check box and actions we directly click on delete button provided there is no audit log for the deleted dag run.

### What you think should happen instead

There should be atleast and identifiable event for audit in both scenarios. For one it is present but for other there is no audit.

### How to reproduce

Go to List dag runs 
1. Select one dag run using check box and go to actions and delete and confirm. Check audit logs there will be an event of action_muldelete
2. Go to list dag run and click on delete button which is present beside check box and adjacent to edit record. Check audit logs there will be no event for this action.

### Operating System

Redhat 8

### Versions of Apache Airflow Providers

airflow 2.6.1 running on Docker with postgres 13 and pgbouncer.

### Deployment

Docker-Compose

### Deployment details

airflow 2.6.1 running on Docker with postgres 13 and pgbouncer.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I think we have the same problem in different views and different event types.

I will try to fix them all with a simple solution
