### ISSUE TITLE
Replace  --package-filter usage for `publish-docs` breeze command with short package names

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34085]
### Body

Same as https://github.com/apache/airflow/issues/33876 but for `publish-docs` command.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @amoghrajesh ?

**Comment by amoghrajesh** [comment]
Self assigning. Will take it up as soon as I have some bandwidth!
Thanks :)
