### ISSUE TITLE
Can Delete on Task Instances permission is required to clear task

### ISSUE THREAD

**Issue by Raul824** [apache/airflow#34092]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I was changing the roles to remove all delete access. But as soon as I remove permission "Can Delete on Task Instances" clear task takes to a blank page.

Shouldn't clear task access work without Delete access?

### What you think should happen instead

Can Delete Task Instance should not affect clear task access.

### How to reproduce

Copy the Op role and remove all Can Delete and assign that role to a user.
That user will not be able to clear task instance now.
add "Can Delete on Task Instances" permission to the role and user will now have access to clear task instances page.

### Operating System

Redhat 8

### Versions of Apache Airflow Providers

2.6.1 

### Deployment

Docker-Compose

### Deployment details

airflow 2.6.1 running on Docker with postgres 13 and pgbouncer.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I created #34123 to discuss this issue, because I am not sure if it's a bug or if there was some reason to use delete instead of edit for TI.
