### ISSUE TITLE
Downstream node is executing even though upstream node is in "Yet to run" status

### ISSUE THREAD

**Issue by vidyapanchalZS** [apache/airflow#34105]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello team, 

We are facing one issue on Airflow version 2.2.2 where downstream task ran successfully even though status of upstream node was "yet to run".

In this DAG, we had set trigger rule for downstream task is "all_done" and upstream task has no rule. When we faced this issue, we observed that status of upstream task run was "yet to run" but downstream task ran successfully. 
Further, we checked logs of worker , scheduler and webserver logs for this issue and observed that web server , scheduler and worker logs have all data related task which executed successfully on airflow but that was not reflected on the airflow UI.
At the time of issue , we observed high CPU utilization  for Web server. 

Could you please let us know how to resolve this issue in the future. 

### What you think should happen instead

The Status of task should be reflected on airflow UI. 

### How to reproduce

We faced this issue 2 times after that issue did not occur.

### Operating System

Amazon linux

### Versions of Apache Airflow Providers

Airflow version 2.2.2 

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Airflow 2.2.2 released almost two years ago, so that it quite a big chance that it already resolved in the current Airflow: https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#release-notes 

Could you also provide example of the DAG which might reproduce this behaviour, so someone could check it this issue present in current Airflow 2.7.x
