### ISSUE TITLE
Always show details panel when user navigates to Graph tab

### ISSUE THREAD

**Issue by Usiel** [apache/airflow#34132]
### Description

When a user navigates to `/grid?tab=graph` we should show the details panel with the graph tab selected, even when the user hid the details panel previously.

### Use case/motivation

People already complained asking me where the graph view went after the latest Airflow upgrade (2.7.0). I can understand that this may be confusing, especially when they navigate to the graph from a DAG run link.

![Screen Capture on 2023-09-06 at 11-52-09](https://github.com/apache/airflow/assets/1842905/db935269-20de-4f77-8899-3ca993bf464f)

It would be more user friendly if we could auto-open the details panel when a user navigates to the graph tab, so they immediately get what they expect.

Happy to create the PR for this, I believe it should be just a tiny change. However, I'm opening this feature request first, just to make sure I'm not conflicting with any other plans ([AIP-39?](https://github.com/apache/airflow/projects/9)).

### Related issues

https://github.com/apache/airflow/issues/29852

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I'd say - go for it. It's no brainer :).
