### ISSUE TITLE
Update docs to mark Pluggy interface as stable rather than experimental

### ISSUE THREAD

**Issue by TheCodyRich** [apache/airflow#34147]
### What do you see as an issue?

[Pluggy interface has been listed as experimental](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/cluster-policies.html#:~:text=By%20using%20a,experimental%20feature.) since Airflow 2.6.  Requesting it be listed as stable

### Solving the problem

Change the documentation to say it is now stable

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
Yep, I think it's time to mark it stable! Let's add a newsfragment while we are at it.

**Comment by DjVinnii** [comment]
Is this also relevant for the [Listeners](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/listeners.html) or is that a separate topic? As these are also using Pluggy.

**Comment by TheCodyRich** [comment]
I would assume they would be the same, but for now I've opened a PR just for the Cluster Policies
