### ISSUE TITLE
Description needed for default resource configurations

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#34141]
### What do you see as an issue?

Several of the [operator configuration options](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#operators) don't have descriptions which is confusing.

### Solving the problem

This can be solved by adding a description to each of these fields, [for example default_ram](https://github.com/apache/airflow/blob/2.7.0/airflow/config_templates/config.yml#L1290)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Curiously, [this stackoverflow post on default_ram, etc](https://stackoverflow.com/a/48223083/7004653) says these configurations aren’t used anywhere (although there are a few references to the Resources class -- [example](https://github.com/apache/airflow/blob/b9acffa81bf61dcf0c5553942c52629c7f75ebe2/airflow/models/baseoperator.py#L147))

**Comment by eladkal** [comment]
See related issue and comment https://github.com/apache/airflow/issues/16563#issuecomment-865045209

**Comment by Owen-CH-Leung** [comment]
I'll help to improve the docs. Please assign this to me
