### ISSUE TITLE
`log_query` of `AthenaOperator` dumps un readable query

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#34189]
### Body

Log:
![Screenshot 2023-09-07 at 22 18 41](https://github.com/apache/airflow/assets/45845474/09c918d6-a81e-4aa3-833b-2e750213d1a1)

Compare to render tab:
![Screenshot 2023-09-07 at 22 19 50](https://github.com/apache/airflow/assets/45845474/d8f47985-9954-4410-93f7-1d121a1d4ed6)

**Reproduce steps:**

set `file.sql` as:
```
CREATE EXTERNAL TABLE IF NOT EXISTS `outputs3`(
  `region` string,
  ....
)
```

set operator as:

```
AthenaOperator(
    task_id="my_task",
    query="file.sql",
    database="my_db",
    log_query=True,
    output_location="s3://...",
)
```
        
 **The needed fix:**
 Pretty print the query. It should appear exactly like it is in the `.sql` file.
 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by mingdaoy** [comment]
@eladkal Can I take ownership of this issue? I wanna learn and be curious

**Comment by eladkal** [comment]
Assigned to you @mingdaoy

**Comment by eladkal** [comment]
> use Athena within Airflow to verify the result.

You can setup aws connection with Athena table to test it
I think AWS offers free trail account if you don't have one? cc @shubham22

**Comment by eladkal** [comment]
By the way the `log_query` is useful also for other cases. So we can also add it in `BaseSQLOperator` then you can test it with almost any databasse using `SQLExecuteQueryOperator`. Since this is just parsing strings I think it's safe to say that if it works for `SQLExecuteQueryOperator` it will work also for Athena.
Then open PR for Athena and PR for common.sql
