### ISSUE TITLE
When updating to 1.11.0, webserver ingress create/upgrade fails.

### ISSUE THREAD

**Issue by j1wonpark** [apache/airflow#34196]
### Official Helm Chart version

main (development)

### Apache Airflow version

2.7.0

### Kubernetes Version

1.23

### Helm Chart configuration

Simply use the existing 1.10.0 without defining the fullname.

### What happened

The error below occurs.

Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "***.****.****" and path "/" is already defined in ingress ****/airflow-airflow-ingress:

### What you think should happen instead

The upgrade must succeed without any special regeneration of Ingress.

### How to reproduce

Simply use the existing 1.10.0 without defining the fullname

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
I wasn't able to reproduce this. Helm should be deleting the old ingress before creating the new one.

**Comment by phil-park** [comment]
@jedcunningham 
I used helm with options 'atomic' and 'wait' to make stable changes to my service. 


            name,
            f"{chart.repository}/{chart.chart}",
            "--create-namespace",
            "--namespace",
            namespace,
            "--values",
            values,
            "--wait",
            "--atomic",
            "--timeout",
            timeout,
            "--output",
            "json",

**Comment by jedcunningham** [comment]
Ah, that's part of the problem then. Wait isn't supported, though it might work if you toggle the useHelmHooks flags to off. A little more context in #15340 (but fair warning some of those comments aren't talking about the official chart).

**Comment by mg-aik** [comment]
I have the same problem as @phil-park:

Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "xxx.yyy.net" and path "/" is already defined in ingress popsicle/xxx-airflow-airflow-ingress

Any news around this?

**Comment by Vedrillan** [comment]
Same issue upgrading with terraform and the helm_release resource and following every instruction there https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform

Deleted the ingress, redeployed and the issue is fixed.

**Comment by a-narsudinov** [comment]
Have the same issue during upgrade from 1.10 to 1.13:
```
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "xxx.domain.tld" and path "/" is already defined in ingress airflow-xxx/airflow-xxx-airflow-ingress
```

This a bit disappointing that the issue is closed since it is a bit problematic to automatically update hundred all of ours clusters.
