### ISSUE TITLE
Do Broken DAGs affect the scheduling/execution of other, unrelated DAGs?

### ISSUE THREAD

**Issue by r39132** [apache/airflow#342]
We've been getting some import errors on some DAGs. Since the entire DAG bag is loaded in order to run any DAG, it would seem that problems with unrelated DAGs might keep my target DAG from executing? We are running the LocalExecutor.

We were stumped. After installing some dependencies to resolve the import errors, we noticed that our target DAG started working.

**Comment by mistercrunch** [comment]
It really shouldn't. We have 100+ DAGs at Airbnb and sometimes a DAG or two will go offline as people push bad code and it does not affect the other DAGs, as expected.

**Comment by r39132** [comment]
It was a shot in the dark to root cause issue #341 

It's curious how once we resolved the dependency, it started working, though there might be something else at play here. Do you folks test using the LocalExecutor or only the CeleryExecutor?

**Comment by mistercrunch** [comment]
I just realized I was running the tests against SequentialExecutor and a sqlite db. I just switched my `unitests.cfg` to use LocalExecutor and a mysql database, that should speed up the process and cover LocalExecutor, which is much more important than SequentialExecutor.
