### ISSUE TITLE
apache/airflow:latest-python3.8 docker image bug

### ISSUE THREAD

**Issue by gillesoldano** [apache/airflow#34203]
### Apache Airflow version

2.7.1

### What happened

Hi, 
this morning while rebuilding an image based on the apache/airflow:latest-python3.8 I failed to import a dag and was presented with the following error:
```
Broken DAG: [/opt/airflow/dags/quality_prediction_ct.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/gateway/config.py", line 79, in OpenAIConfig
    @root_validator(pre=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

Yesterday it worked just fine and no modification were done to the code. I then tried to downgrade the version to 2.7.1rc2 and got the same error, I then downgraded it to version 2.7.0 and it worked again.

### How to reproduce

I really don't know, I'm just running a dag in python using the task flow api.

### Operating System

Manjaro Linux

### Deployment

Docker-Compose

### Deployment details

Dockerfile:
```
FROM apache/airflow:latest-python3.8

RUN pip install pip --upgrade
RUN pip install mlflow xgboost scikit-learn matplotlib bentoml influxdb-client aiohttp

EXPOSE 8080
```

Docker compose:
```
services:
  airlow_server:
    container_name: airflow_server
    build:
      context: .
      dockerfile: dockerfile_airflow
    hostname: "airflow_server"
    network_mode: "host"
    volumes:
      - ./dags:/opt/airflow/dags
    command: airflow standalone
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
the current image has Pydantic 2 (as opposed to previous images) - this is your problem (and we are not going to downgrade in the reference image). Pydantic released Version 2 few months ago and we are at the transition period where most of the libraries have already upgraded, but you might still have some libraries that are lagging behind.

You have two options:

* Airflow 2.7.1 does not limit you to Pydantic 2 - reference image has Pydantic 2, but you can still build your custom image and downgrade to Pydantic 1  (see https://airflow.apache.org/docs/docker-stack/build.html#adding-new-pypi-packages-individually) on how you can downgrade/upgrade/install PyPI packages in your custom image

* You can upgrade your libraries or your code to use Pydantic 2 (this is the best future-looking change and I'd recommend it) 

Closing as invalid.
