### ISSUE TITLE
Add run_id to event logs API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#34211]
### Description

We currently only include `execution_date` in the event logs response, but dag runs can have a custom id. We should add `run_id` as an additional field to both event log endpoints to make sure a user can now which dag run and task instance produced the event.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vidhanvyrs** [comment]
hey @bbovenzi I am more than happy to contribute here and  I think i can help you with this, Can you assign this issue to me so i can get the approval to start working on it

**Comment by ephraimbuddy** [comment]
I have assigned it to you @Vidhanvyrs

**Comment by boraberke** [comment]
Seems like #37731 added `run_id`. 

@Taragolis maybe this issue can be closed?
