### ISSUE TITLE
Generate per-provider SBOM

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34236]
We should - similarly as for Apache Airflow generate SBOMS for all versions of all providers we have relased in Airflow 2. This will take quite some time and we need to - sometimes- generate  up to 90 of those, so it should be massively paralllelised in order to be put as part of release process similarly to other parallel actions we have (for example generating provider documentation)

The current idea is that we should use extend and parallelise the way how we currently use `breeze sbom generate-provider-requirements` command. Currently this command takes "--airflow-version" as parameter, to be able to generate "provider-only" sboms (basically by subtracting new dependencies from those that come from "bare" airflow" installation. However older provider versions used older airflow version when they have been released and we should use those airflow versions to generate the requirements.

We already have:

* `breeze release-management generate-providers-metadata` -> this one generates information about all versions of all providers (using constraints files) -> date of release and which airflow version was "current" when the provider was released
* ` breeze sbom generate-provider-requirements` -> it generates "provider-only" requirements - i.e. dependencies that are contributed by providers when installing them on top of specific airflow version
* `breeze sbom update-sbom-information` - uses airflow images to generate airflow SBOM information in "airflow-site".

One of the ways how we can "massively" generate SBOM from that information is:

* we build an image where we install all released "bare" airflow versions - each in its own venv
* extend `breeze sbom update-sbom-information` to run parallel generation of provider SBOM by using this "all airflow" image - for each provider version we would run a container and install the new provider in the right venv (corresponding to airflow version that was "latest" when the provider version in question has been released

**Comment by pierrejeambrun** [comment]
I'll take this one.

**Comment by pierrejeambrun** [comment]
I think after a few PRs we can safely say that we have a 'working'  first version. This will most certainly need some more tweaks, adjustments and improvements, but I'll close for now.
