### ISSUE TITLE
Standardise output of "airflow connections export" to those of "airflow variables export" and "airflow users export"

### ISSUE THREAD

**Issue by gbonazzoli** [apache/airflow#34232]
### Description

The three commands:

```
              airflow users export /opt/airflow/dags/users.json &&
              airflow variables export /opt/airflow/dags/variables.json &&
              airflow connections export /opt/airflow/dags/connections.json
```

give back:

```
7 users successfully exported to /opt/airflow/dags/users.json
36 variables successfully exported to /opt/airflow/dags/variables.json
Connections successfully exported to /opt/airflow/dags/connections.json.
```

### Use case/motivation

Standardise output of "airflow connections export" to those of "airflow variables export" and "airflow users export"

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked as "good first issue".

**Comment by AmirAflak** [comment]
would like to take this :)

**Comment by potiuk** [comment]
assigned

**Comment by Jayden-Chiu** [comment]
Ended up creating own PR for this issue because seems like development has not been started in the past two weeks
