### ISSUE TITLE
access control logs

### ISSUE THREAD

**Issue by Shlomixg** [apache/airflow#34265]
### Apache Airflow version

2.7.1

### What happened

After upgrading to 2.7.1 from 2.5.3 we encountered those logs in the scheduler logs:

```[2023-09-11T05:52:34.865+0000] {logging_mixin.py:151} INFO - [2023-09-11T05:52:34.865+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:<dag_name>' as access control is unset.```

Since we have multiple DAGs for the same DAG file (>40), and the DAG processor is running on a high period, we have a lot of redundant logs, which creates more unnecessary data to store.

Adding the setting `access_control={}` did not change the logs.

We don't want to manage the access control for each DAG, as we have a high-level approach, but we also don't want these logs.

### What you think should happen instead

Add some settings to allow avoid printing this info logs about sync permissions

### How to reproduce

Airflow Version - 2.7.1
Python - 3.11.5

Create a DAg without setting access_control and watch logs. e.g. `XXX/_data/scheduler/2023-09-11/dag_name.py.log`

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yeah. We shoudl change those logs about syncing to debug. For now a workaround is to use  https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/advanced-logging-configuration.html and set `airflow.www.security.AirflowSecurityManager` logger level to WARNING.

**Comment by csp33** [comment]
I'll do it!

**Comment by potiuk** [comment]
Feel free.
