### ISSUE TITLE
Automate links to configuration of providers

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34306]
### Body

Since more and more providers release their configuration, we should automate generation of the links to the configuration.

See https://github.com/apache/airflow/pull/34305

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Jyoticharan** [comment]
I am beginner in the field of open source and interested to work on this issue,please assign me the issue.

**Comment by hussein-awala** [comment]
@Jyoticharan sure, I assigned you.

**Comment by eladkal** [comment]
@Jyoticharan are you still working on this issue?

**Comment by poorvirohidekar** [comment]
@potiuk - I am interested in working on this. Can you please assign it to me?

Could you help me understand this issue description? 
I built the docs in my local for a provider and could find the configuration.rst file. Can you tell me how this relates to the generation of the links to the configuration?

**Comment by hussein-awala** [comment]
@poorvirohidekar assigned you.

**Comment by potiuk** [comment]
@poorvirohidekar - similarly to what has beein implemented for automatically retrieving operators/hooks and other references here https://github.com/apache/airflow/blob/main/docs/exts/operators_and_hooks_ref.py - this file adds sphinx directives that are called by sphinx when placed in the .rst files and the code can scan for configurations in provider.yaml files and generate the list from there - we need a new directive there.

**Comment by poorvirohidekar** [comment]
@potiuk - So from the provider.yaml file, I see that we generate https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/configurations-ref.html doc. When you say "automate links", do you mean the links that have been done as a part of this PR as an example - https://github.com/apache/airflow/pull/34305 ?

**Comment by poorvirohidekar** [comment]
@potiuk - From the file mentioned, I understand that class AuthConfigurations is rendering a template configurations.rst.jinja2 and when I look at the configurations.rst.jinja2 file (https://github.com/apache/airflow/blob/main/docs/exts/templates/configuration.rst.jinja2), there is a way in which a similar pattern of link seems to be getting generated? I am not sure if this AuthConfigurations is the relevant existing directive for this issue. 
If not, then can you help me understand how the links currently being generated or point me in the right direction?

**Comment by potiuk** [comment]
Ah. So it's alreeady done 🤦
