### ISSUE TITLE
WasbHook forces httpS for testing else it will be an azure url

### ISSUE THREAD

**Issue by KIC** [apache/airflow#34303]
### Apache Airflow version

2.7.1

### What happened

Can nott test WasbHook using azurite because of the following code segment:

airflow.providers.microsoft.azure.hooks.wasb.WasbHook.get_conn.account_url
```python
        account_url = (
            conn.host
            if conn.host and conn.host.startswith("https://")
            else f"https://{conn.login}.blob.core.windows.net/"
        )
```

### What you think should happen instead

which should allow non secured sites for testing like:

` if conn.host and re.search(r'^https?:\/\/.*"', conn.host)`

### How to reproduce

use a connection to a azurite container
`docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite     azurite-blob --blobHost 0.0.0.0 --blobPort 10000`

### Operating System

linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Fancy a PR @KIC?

**Comment by KIC** [comment]
Let me see if I can get a dev environment running quickly ...

**Comment by KIC** [comment]
ah looks like you have cahnged it already, sorry for the noise:
`        account_url = conn.host if conn.host else f"https://{conn.login}.blob.core.windows.net/"`
