### ISSUE TITLE
Only the default condition on Task Instance filters work

### ISSUE THREAD

**Issue by LiamOrmiston** [apache/airflow#34313]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

On version 2.7.0
When adding filters to the Browse -> Task Instances page, only the default condition on any filter works. This is either `Starts with` or `Equal to` depending on the filter.

For example:
When adding a `Task Id` filter, only the `Starts with` condition works. Picking `Ends with` will result in a search as if you never entered that filter at all. The filter will not appear under the search drop down and the results do not reflect that the filter was applied.

Adding `Starts with` and `Ends with` results in just `Starts with` being applied.

### What you think should happen instead

Each condition should work on any given filter.

### How to reproduce

1. Go to the Browse -> Task Instances page
2. Select the `Search` drop down
3. Pick any filter
4. Change the conditon to something other than the default choice
5. Add something to the condition field
6. Hit Search

### Operating System

CentOS Stream 8

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
I believe that this is the same issue reported in https://github.com/apache/airflow/issues/33895 which was fixed in https://github.com/apache/airflow/pull/33931, which was included in the 2.7.1 release.
