### ISSUE TITLE
Listeners for Datasets

### ISSUE THREAD

**Issue by DjVinnii** [apache/airflow#34327]
### Description

Add listeners for Datasets (events)

### Use case/motivation

As Airflow administrators, we would like to trigger some external processes based on all datasets being created/updated by our users. We came across the listeners for the dag runs and task instances (which are also useful), but are still missing listeners for datasets.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
This would be a cool feature, would you like to work on it?

**Comment by yermalov-here** [comment]
i'd like to try to implement it

**Comment by yermalov-here** [comment]
Apart from `dataset creation` and `dataset updates` would it also be helpful to introduce hooks for dataset `orphaning` and `unorphaning`?

**Comment by DjVinnii** [comment]
> Apart from `dataset creation` and `dataset updates` would it also be helpful to introduce hooks for dataset `orphaning` and `unorphaning`?

In our use-case we only have a purpose for the `dataset creation` and `dataset updates`. However, I could see that others also are interested in the `orphaning` and `unorphaning`. What's your take on it @hussein-awala?

**Comment by cmarteepants** [comment]
@DjVinnii, for docs/release notes purposes, high-level what is your use-case for this?

**Comment by DjVinnii** [comment]
@cmarteepants 

> Like what kind of external processes could someone trigger on dataset events?

We are going to use the dataset listeners in order to synchronize datasets across regional Airflow instances. Unfortunately there is no API endpoint yet to create/update Datasets so we still need to do some tricky workarounds.
