### ISSUE TITLE
DAG Filtering using TAGs - Result Returned is DAG's with Union of Tags

### ISSUE THREAD

**Issue by iamakashladdha** [apache/airflow#34370]
### Apache Airflow version

2.7.1

### What happened

Current Behavior In Airflow UI is when we filter the DAGs using TAGs, the Search results returned are of Union of Tags i.e. ORing of Tags, But when we have 100's of DAGs with overlapping tags, it becomes difficult to filter them out. 

For example - Here in a snap, if we filter for `consumer` and `datasets`, then we wanted only one DAG result to be returned i.e. DAG having both the Tags `consumer` and `datasets`, But all the DAGs having either consumer and/or dataset tags are returned.
 
![image](https://github.com/apache/airflow/assets/98732616/ceee51f9-3655-494a-a76d-46116bb9687b)

### What you think should happen instead

The intersection of Tags, i.e. ANDing of Tags can Happen i.e. return only those DAGs in the search result that meet all the Tags in the query. 

The best is to make it configurable and provide options for both Current Behaviors and the requested behavior so it does not break the existing flow.

### How to reproduce

- Assign two Tags tag1 and tag2 to one DAG
- Assign tag1 to 2nd DAG
- Assign tag3 to 3rd DAG

- Now when you filter by both the tags tag1 and tag2, the result returned will have a union of both the tags i.e. all 3 DAGs will be returned. 

### Operating System

Astro Runtime 9.1.0

### Deployment

Astronomer

### Deployment details

Astro Runtime 9.1.0, Airflow 2.7.1

### Anything else

Always

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
cc: @bbovenzi @pierrejeambrun hoping you have some thoughts on this ☝🏽

**Comment by bbovenzi** [comment]
We probably want a more advanced tags filter that can allow a user to specify OR and AND operations.

**Comment by hussein-awala** [comment]
duplicates: #10724

And there is already a WIP PR for this feature: #33490

I'll close it, feel free to comment on the PR or the other issue.
