### ISSUE TITLE
Missing log file when there's more than one attempt

### ISSUE THREAD

**Issue by r-magalhaes** [apache/airflow#34393]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello,

When there's more than one attempt in a task execution, I've noticed that the first attempt log file is missing from the worker that the webserver is trying to fetch the log from.

Airflow version v2.5.3.

### How to reproduce

If one of your tasks has 2 attempts for example, the first attempt log file seems to be missing from the worker.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Could you provide more details about your issue and your airflow deployment?
- Which executor are you using?
- Are you using remote logging?
- `the first attempt log file is missing from the worker` what do you get exactly?

Also, did you check if the issue was already fixed in a newer version? (for ex: #32561)

**Comment by r-magalhaes** [comment]
Hey @hussein-awala,

So we're using CeleryExecutor and we're not using Remote Logging.

In the first attempt logs we're getting this 
![image](https://github.com/apache/airflow/assets/118082123/9d5c2290-510f-4272-bea9-9d5a9c033d17)

I check inside the worker it tries to fetch the log from and the file is not there.

I think there's a plan to update Airflow's version but as for right now we need to guarantee a few things before the update.

**Comment by DevilShubert** [comment]
> Hey [@hussein-awala](https://github.com/hussein-awala),
> 
> So we're using CeleryExecutor and we're not using Remote Logging.
> 
> In the first attempt logs we're getting this ![image](https://github.com/apache/airflow/assets/118082123/9d5c2290-510f-4272-bea9-9d5a9c033d17)
> 
> I check inside the worker it tries to fetch the log from and the file is not there.
> 
> I think there's a plan to update Airflow's version but as for right now we need to guarantee a few things before the update.

Hi, I'm facing the same issue. Do you know which new version of Airflow has fixed this problem?
