### ISSUE TITLE
WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34419]
UPDATE: as clarified by the author it's about the `get_uri` method (this was missing in the original reprot).

### Discussed in https://github.com/apache/airflow/discussions/34308

<div type='discussions-op-text'>

<sup>Originally posted by **kuikeelc** September 12, 2023</sup>
### Apache Airflow version

2.7.1

### What happened

When you use a connection with a type that holds an underscore (_), Airflow gives the following warning:

WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.

I don't think it is so bad that underscores are used. Can the warning be removed again?

### How to reproduce

No warning 

### Operating System

Mac OS X

### Versions of Apache Airflow Providers

independent of providers

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

none

### Anything else

No

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by potiuk** [comment]
Marked as "good first issue" - hopefully somoene will pick it up.

**Comment by highpon** [comment]
would like to take this :)

**Comment by eladkal** [comment]
@highpon assigned

**Comment by potiuk** [comment]
Copying @uranusjr from #34308 which is the discusion that was converted  that issue (let's continue it here).

> RFC 3986 indeed does not allow underscore so the warning is legit. It works for urllib.parse but there’s no guarantee it works with other things, or will in the future. If anything I’d suggest start disallowing it entirely instead. Why is allowing the underscore important? Why can’t we switch to say google-cloud-platform instead?

> Thinking about this a bit more, maybe we should just start sliently coercing underscores to dashes instead. Allowing (say) both google-clould-platform and google_could_platform as connection types seems like an unnecessary source of possible bugs that benefits mostly nobody.

I think it's not only about coertion, but mostly about clarification what the `get_uri` method does. Coercion would be abreaking change and I think potential uses of the `get_uri`  should be looked at and decision made what to do with it. 

I believe the  `get_uri` method intention was not really defined. We can assume that URI implies RFC 3986, so we can also treat it as a bugfix -  and take the risk of breaking someone's workflow (but it requires SIGNIFICANT note in release notes).

But we have to be very clear about which `get_uri` we are taking and what is the relation with all `get_uri` methods.

Currently there is `get_uri` method in Connection:

```
    def get_uri(self) -> str:
        """Return connection in URI format."""
```

There is also a `get_uri` method in Common-sql DBAPIHook:

```
    def get_uri(self) -> str:
        """
        Extract the URI from the connection.

        :return: the extracted uri.
        """
        conn = self.get_connection(getattr(self, self.conn_name_attr))
        conn.schema = self.__schema or conn.schema
        return conn.get_uri()
```

There are also 15 other implementation in a number of hooks that are inheriting DBAPIHooks - with varying degrees of cusomization - but I believe most of the implementation return the RFC3986 compliant urls. 

A bit of the problem there is that semantically speaking - it's not clear "what kind" of the URI should be returned here. For example there is a different URI when you want to connect to a database with sqlalchemy, and different drivers for the same database might also have different schemes/parameters etc. So it is not entirely clear what kind of URL the `get_uri` method should return. Also some databases define their own schemes (odbc/jdbc has particularly interesting one as it might contain something that looks like there are two schemes but there is one:

```
jdbc:mysql://localhost:3306/sonoo
```

In this casee `jdbc:mysql` is the URI scheme (not jdbc as you might imagine - `:` is perfectly ok as part of the scheme as long as it is not followed by "//`.) .  It's still RFC3986 compliaant.

So IMHO - we should just review all those implementations, update the description and clarify something along the lines of :

**The method returns an RFC3986 compliant URI for the database that can be used by arbitrary chosen driver for the database as the URI that can be used by the driver to connect to the databse. It's not an URI that will work for `sqlalchemy` driver URI, just one of the native drivers.**

I think also we should review all the providers of ours and see if the change will impact the reult of the method and enumerate them in the release notes.

If we make a SIGNIFICANT note and mention that get_uri methods for listed provider connections will behaving differently, I think this is quite a good approach.

WDYT @uranusjr ?  I am happy to review if someone does all that and if others agree that this is a good direction to take.

**Comment by kuikeelc** [comment]
I think we are mixing things up here. The connection id can contain underscores. The current warning disallows underscores in the name. I strongly recommend the remove the warning where it concerns the connection id (not the url) and focus on more important things.

**Comment by potiuk** [comment]
> I think we are mixing things up here. The connection id can contain underscores. The current warning disallows underscores in the name. I strongly recommend the remove the warning where it concerns the connection id (not the url) and focus on more important things.

I think you are mixing things. While indeed originally the issue description was not clear (and I converted it into discussion), the author clarified that the warning is about `get_uri` method NOT the way how connections are defined. See this note at the top top of the isssue

> > UPDATE: as clarified by the author it's about the get_uri method (this was missing in the original reprot).

Where do you see the warnings referring to connection ids @kuikeelc ?

**Comment by kuikeelc** [comment]
The bug remains in v2.7.3.

If you run a task that uses a connection (pretty much any of them) this line will show up in the logs:

`[2023-11-07T09:03:56.571+0100] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.`

[The bug is because of this line of code](https://github.com/apache/airflow/blob/11bdfe4c12efa2f5d256cc49916a20beaa5487eb/airflow/models/connection.py#L234).

I will do source code change as a pull request as well.

**Comment by potiuk** [comment]
> I have prepared a change that removes the unnecessary warning. I can push it to a branch called 'issue/34419'. If you allow me write permissions.

You won't get write permissions unless you become committer. You need to fork airflow and create PR from your fork like everyone else contributing (see CONTRIBUTING.rst)/.  This is the standard development process fo all GitHub projects.

Also se ethe discussion about solving it in https://github.com/apache/airflow/pull/34446 - it's not the "warning" that is the problem but semantics of the method.

**Comment by SamoylovMD** [comment]
For those who have been struggling with this issue, here are the lines of code which helped me to get rid of the warning in my DAG code:

```
from airflow.models import Connection
Connection.logger().setLevel(logging.ERROR)
```
