### ISSUE TITLE
Consolidate the warning stacklevel in KubernetesPodTrigger

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#34424]
### Body

Use stacklevel 2 instead of the default 1:
https://github.com/apache/airflow/blob/1b122c15030e99cef9d4ff26d3781a7a9d6949bc/airflow/providers/cncf/kubernetes/triggers/pod.py#L103-L106

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by richsuca** [comment]
please assign to me

**Comment by hussein-awala** [comment]
@richsuca assigned you.

**Comment by anukrati1507** [comment]
please assign to me.

**Comment by amoghrajesh** [comment]
This issue was not actively worked on. Assigning to you @anukrati1507
