### ISSUE TITLE
Consolidate the waning stacklevel in K8S pod_manager

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#34423]
### Body

Use stacklevel 2 instead of the default 1:
https://github.com/apache/airflow/blob/b5057e0e1fc6b7a47e38037a97cac862706747f0/airflow/providers/cncf/kubernetes/utils/pod_manager.py#L361-L365

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by daxmahoney** [comment]
I would like to work on this issue

**Comment by potiuk** [comment]
Congrats on first merged PR 🎉
