### ISSUE TITLE
UI/UX Graph Display

### ISSUE THREAD

**Issue by cedric-ejara** [apache/airflow#34429]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

The graph is displayed in an unusual size in **version 2.7.0**
[Screenshot from 2023-09-16 23-38-05](https://github.com/apache/airflow/assets/131764205/cf02507f-7593-4cd5-9969-bddf6e45083e)
[Screenshot from 2023-09-16 23-41-38](https://github.com/apache/airflow/assets/131764205/476933d0-f50c-47ce-91c3-943c52312025)
[Screenshot from 2023-09-16 23-39-09](https://github.com/apache/airflow/assets/131764205/09b8198b-56a6-480e-9909-087b886976e6)

### What you think should happen instead

I expect that the graph be displayed well and all the extract spaces removed, according to the parent of the container.
Like this

[Screenshot from 2023-09-16 23-54-11](https://github.com/apache/airflow/assets/131764205/2fc7948a-b89d-4573-9606-450ff7a11418)

### How to reproduce

I created a dag use to generate tasks in my main dag and for every source group I create a table group > source_name > table_name group some sources have like 31 tables while others have less and other have more, and it created that display graph.

### Operating System

Ubuntu 22.10

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.3.3
apache-airflow-providers-common-sql==1.7.1
apache-airflow-providers-ftp==3.5.1
apache-airflow-providers-http==4.5.1
apache-airflow-providers-imap==3.3.1
apache-airflow-providers-slack==8.0.0
apache-airflow-providers-snowflake==5.0.0
apache-airflow-providers-sqlite==3.4.3

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
@cedric-ejara could you also provide example DAG for reproduce this issue. This not required to be real DAG, some simple combination of empty/python operators would be enough.

**Comment by NEONITIN3** [comment]
@cedric-ejara  hi. Airflow version 2.7
