### ISSUE TITLE
Respect node color in the new UI graph

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#34420]
### Body

In Airflow 2.7.0 we removed the old graph and replaced it by the new graph view. However, this new graph doesn't change the node color to the color provided in the operator, it only use this color as a shadow for the task name:
![image](https://github.com/apache/airflow/assets/21311487/15941073-b2a5-49e0-b76a-dd2947bf8752)

It would be better if we change the node color as we had before with the old graph

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by bbovenzi** [comment]
This is intentional. The color really indicates the operator. Would it help if the operator badge had a larger font or more padding to make it more noticeable?

**Comment by amoghrajesh** [comment]
This issue can be used the handle the case where we increase the font size and add some padding. It is pretty invisible otherwise, I like the idea!
