### ISSUE TITLE
Consolidate stacklevel in ssh operator warning

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#34421]
### Body

SSHOperator uses the default `stacklevel` (1) in its deprecation warning, it should be 2:
https://github.com/apache/airflow/blob/a59076eaeed03dd46e749ad58160193b4ef3660c/airflow/providers/ssh/operators/ssh.py#L139-L143

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by OHOUNN** [comment]
I would like to work on this issue please assign it to me

**Comment by hussein-awala** [comment]
@OHOUNN assigned you.

**Comment by shubhamraj-git** [comment]
Can you please assign this to me?
