### ISSUE TITLE
Consolidate stacklevel in ssh hooks warning

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow#34422]
### Body

SSHHook uses the default stacklevel (1) in its deprecation warning, it should be 2:
https://github.com/apache/airflow/blob/b11525702c72cb53034aa29ccd6d0e1161ac475c/airflow/providers/ssh/hooks/ssh.py#L433-L439
https://github.com/apache/airflow/blob/b11525702c72cb53034aa29ccd6d0e1161ac475c/airflow/providers/ssh/hooks/ssh.py#L369-L374
https://github.com/apache/airflow/blob/b11525702c72cb53034aa29ccd6d0e1161ac475c/airflow/providers/ssh/hooks/ssh.py#L232-L238

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by daxmahoney** [comment]
I would like to work on this issue please assign it to me

**Comment by hussein-awala** [comment]
@daxmahoney Assigned you.
