### ISSUE TITLE
Connection id "extra" error

### ISSUE THREAD

**Issue by Dobring** [apache/airflow#34456]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Dear Sir/Madam.
In airflow 2.7.0 version 
After editing connection in GUI,
Field extra recieves default value of {}, which is not equal to None. 

This causes extra={} argument being passed to connection uri. 
{} is encoded to %7B%7D, as you can see on screen attached.

The result of default value is attached
It leads to the following error message.

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) invalid dsn: invalid connection option "__extra__" 
(Background on this error at: https://sqlalche.me/e/14/f405)

![photo_5206597667222835967_y (1)](https://github.com/apache/airflow/assets/59996696/62f1227e-1f74-44cb-adf5-d42d52f62b64)

### What you think should happen instead

I expect that if I leave Extra field empty when creating a connection id, there shall no be extra information.

### How to reproduce

We simply create the connection by manually inputing all usual credentials.

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.5.1
apache-airflow-providers-postgres==5.6.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by slavanorm** [comment]
See PR with original changes

https://github.com/apache/airflow/pull/28583

**Comment by Taragolis** [comment]
@Dobring could you provide a bit more information. It's quite difficult to understand what is going wrong here.

1. Which version of  Amazon and Postgres provider are you use
2. Full traceback of error
3. Minimal step for reproduce, please provide it as text so someone who would check might replace by it owns values. ⚠️⚠️ You **don't need** to provide your actual credentials, just samples ⚠️⚠️

**Comment by Dobring** [comment]
Dear Taragolis, please find the full traceback of error I have received,
[dag_id=prod-test_run_id=manual__2023-09-18T20_23_39.862391+00_00_task_id=print_player_attempt=1.log](https://github.com/apache/airflow/files/12653303/dag_id.prod-test_run_id.manual__2023-09-18T20_23_39.862391%2B00_00_task_id.print_player_attempt.1.log)

**Comment by Taragolis** [comment]
Ok, now seems I got what a problem.
Last changes finally break PostgresHook.get_uri logic, to be honest it was broken for a long time, maybe even since it implemented.

The problem with bad assumption that Airflow Connection URI is the same as psycopg2 or even sqlalchemy URI. But it not the same, and was never the same due to the fact that Airflow PostgreSQL connection has extra attributes which is not supported by psycopg2/SQLAlcemy and current implementation takes Airflow URI and replaced schema. So it is need to be fixed in PostgreSQL provider and maybe others.

**Comment by slavanorm** [comment]
so, we could fix it in our case by manually going to connections GUI, deleting {} in extra field, and saving connection.
im pretty sure if you edit connection without removing default {}  value in extra field, it will ruin connection again.

**Comment by Taragolis** [comment]
> so, we could fix it in our case by manually going to connections GUI, deleting {} in extra field, and saving connection.

As temporary fix it might help

>ruin connection again.

The problem not in Airflow Connection itself. The problem in PostgresHook implementation because Airflow Connection != SQLAlchemy.
