### ISSUE TITLE
Graph view task name & status visibility 

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#34455]
### Description

I have had complaints from coworkers that it is harder to visibly see the status of airflow tasks in the new graph view. They miss the colored border from the old graph view that made it very clear what the status of a task was. They have also mentioned that names of the tasks feel a lot smaller and harder to read without zooming in.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Makes sense to me! Let's add the color to the border and increase the task name font size. Should be very easy for anyone to pick up.

**Comment by hainenber** [comment]
Hi there, I'd like to work on this. Pls help assign. Thanks!
