### ISSUE TITLE
UI Improvement - adjust the panels in grid view when maximize

### ISSUE THREAD

**Issue by hamedhsn** [apache/airflow#34477]
### Description

Since the grid view contains lots of information and specially if user wants to read the logs when the window maximized it is better for the right panel to expand instead of the left one which does not have much info other than the tasks. 
in my wide monitor when I maximize it looks like 

![Screenshot 2023-09-19 at 12 50 45](https://github.com/apache/airflow/assets/4147327/38e1bac4-1a79-42af-8208-9f179fb081b0)

so if the right panel maximized and not the left one my log would have been much more visible and I would not have go to graph view/ log to look at the logs

### Use case/motivation

so if the right panel maximized and not the left one my log would have been much more visible and I would not have go to graph view/ log to look at the logs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We made the width adjustable in 2.5.0. This shoudl solve your problem.
https://github.com/apache/airflow/pull/27273

**Comment by hamedhsn** [comment]
great! thanks
