### ISSUE TITLE
sqlalchemy error when running CLI command airflow tasks test -- 

### ISSUE THREAD

**Issue by rm-minus-r-star** [apache/airflow#34491]
### Apache Airflow version

2.7.1

### What happened

Same issue as [#34109](https://github.com/apache/airflow/issues/34109) with out-of-the-box 2.7.1.

Fix [#34120](https://github.com/apache/airflow/pull/34120) provided for 2.7.0 works, but has evidently not been included in 2.7.1

### What you think should happen instead

I would have expected bug fixes to be included in later versions

### How to reproduce

`airflow tasks test dag-name task-id`, as for [#34109 ](https://github.com/apache/airflow/issues/34109) under 2.7.1

### Operating System

(X)Ubuntu 20.04.6 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.7.1
apache-airflow-providers-ftp==3.5.1
apache-airflow-providers-http==4.5.1
apache-airflow-providers-imap==3.3.1
apache-airflow-providers-sqlite==3.4.3

### Deployment

Virtualenv installation

### Deployment details

installed into venv after `python3.10 -m venv venv`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/34120 is a part of [Airflow 2.7.2 milestone](https://github.com/apache/airflow/milestone/81?closed=1)
