### ISSUE TITLE
Add securityContexts in dagProcessor.logGroomerSidecar

### ISSUE THREAD

**Issue by aldwyn** [apache/airflow#34498]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

1.26.7

### What happened

When enabling `dagProcessor.logGroomerSidecar`, our OPA gatekeeper flags the `dag-processor-log-groomer` container with the appropriate non-root permissions. There is no way to set the `securityContexts` for this sidecar as it is not even enabled.

### What you think should happen instead

The `securityContexts` setting for the `dag-processor-log-groomer` container should be configurable.

### How to reproduce

In the Helm values, set `dagProcessor.logGroomerSidecar` to `true`.

### Anything else

This problem occurs when there are OPA policies in place pertaining to strict `securityContexts` settings.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MPParsley** [comment]
Hi @aldwyn, do you have an example values.yml file to set a securityContext?
