### ISSUE TITLE
Airflow logs not found giving error-The task might not have been executed or worker executing it might have finished abnormally (e.g. was evicted).

### ISSUE THREAD

**Issue by Shifa15** [apache/airflow#34504]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version is 2.5.3
When the DAGs are executing at scheduled time it is giving the following error in 1 or 2 attempts and then executing the task.
```
Log file is not found: 
*** The task might not have been executed or worker executing it might have finished abnormally (e.g. was evicted).
*** Please, refer to https://cloud.google.com/composer/docs/how-to/using/troubleshooting-dags#common_issues hints to learn what might be possible reasons for a missing log.
```

### What you think should happen instead

There might be following possible cause
- logs clean up required
- pod has stopped working
- worker is executing the task

### How to reproduce

Not sure

### Operating System

Windows

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Which executor are you using? Did you try to reproduce it with the latest version?
