### ISSUE TITLE
Airflow Google Provider BigQueryIntervalCheckOperator miss project_id

### ISSUE THREAD

**Issue by cceasy** [apache/airflow#34513]
### Apache Airflow version

main (development)

### What happened

When we use BigQueryIntervalCheckOperator to check the data in big query, we need to submit a bq job, but there is no way to define the bq job project id, it extract the project id from the gcp_conn_id hook. But we may NOT have permission to submit bq job to that project, so the job would fail.

### What you think should happen instead

we should enable pass the bq job project id so that the underlying bq job could success.

### How to reproduce

use the operator with a gcp connection that the correspond service account does not have permission to submit bq job to the connection project.

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.5.0

### Deployment

Google Cloud Composer

### Deployment details

 composer-2.4.1-airflow-2.5.3 

### Anything else

we need to be able to define the project id here https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py#L563
<img width="901" alt="image" src="https://github.com/apache/airflow/assets/6096155/d0e9cb0e-1a05-4ed1-a52e-65a76a69fc31">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Zhenye-Na** [comment]
Could you assign this issue to me as I am working on this actively.

Thanks!

**Comment by hussein-awala** [comment]
@Zhenye-Na assigned you.

**Comment by eladkal** [comment]
Fixed in: https://github.com/apache/airflow/pull/34573
