### ISSUE TITLE
Define constant variables for repo routes in databricks hook

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#34521]
### Apache Airflow version

main (development)

### What happened

Databricks hook utilizes some constant variables to define routes and the operations on them https://github.com/apache/airflow/blob/main/airflow/providers/databricks/hooks/databricks.py#L39-L70, but it does not do this for the repo routes at all https://github.com/apache/airflow/blob/main/airflow/providers/databricks/hooks/databricks.py#L521-L550

### What you think should happen instead

There should be constant variables for the routes that are used to call the repo endpoints

### How to reproduce

Look at code repository

### Operating System

Ventura 13.0

### Versions of Apache Airflow Providers

apache-airflow-providers-databricks==4.5.0

### Deployment

Docker-Compose

### Anything else

I am willing to submit a PR to this but I have some competing priorities right now

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
This improvement looks great and It seems there's already a PR for it.
