### ISSUE TITLE
Unable to retrieve logs for nested task group when parent is mapped

### ISSUE THREAD

**Issue by fritz-astronomer** [apache/airflow#34535]
### Apache Airflow version

2.7.1

### What happened

Unable to retrieve logs for task inside task group inside mapped task group.
Got `404 "TaskInstance not found"` in network requests

### How to reproduce

```
from datetime import datetime
from airflow import DAG
from airflow.decorators import task, task_group
from airflow.operators.bash import BashOperator
from airflow.utils.task_group import TaskGroup

with DAG("mapped_task_group_bug", schedule=None, start_date=datetime(1970, 1, 1)):
    @task
    def foo():
        return ["a", "b", "c"]


    @task_group
    def bar(x):
        with TaskGroup("baz"):
            # If child task group exists, logs 404
            #  "TaskInstance not found"
            # http://localhost:8080/api/v1/dags/mapped_task_group_bug/dagRuns/manual__2023-09-21T22:31:56.863704+00:00/taskInstances/bar.baz.bop/logs/2?full_content=false
            # if it is removed, logs appear
            BashOperator(task_id="bop", bash_command="echo hi $x", env={"x": x})


    bar.partial().expand(x=foo())
```

### Operating System

debian 11 / `astro dev start`

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by fritz-astronomer** [comment]
If this is known/expected behavior, I don't see mention of it here:
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#taskgroups
or here:
https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html#mapping-over-a-task-group

**Comment by hussein-awala** [comment]
I found that the log exists and available in the TaskInstance view, but the problem is in the GridView which should consider the TI as mapped TI and try to get the log for the selected index.

I tested #34587 and it fixed the issue on the dag your provided, and I tested with a more complex case (5 nested levels) and everything looks good, could you check it?
