### ISSUE TITLE
Datasets - trigger DAG run when any dataset is updated

### ISSUE THREAD

**Issue by westonplatter** [apache/airflow#34534]
### Description

On [this doc page](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html#multiple-datasets), Airflow explicitly says all datasets need to be updated before a DAG runs is triggered.
> When using datasets, in this first release (v2.4) waiting for all datasets in the list to be updated is the only option when multiple datasets are consumed by a DAG. **A later release may introduce more fine-grained options allowing for greater flexibility.**

I would like to see the `schedule` param logic configurable so that **all** or **any** dataset being updated triggers a DAG run.

### Use case/motivation

Configurable so that a DAG run is triggered when either **all** or **any** dataset is updated.

To keep the API consistent, code changes would keep `all` as the default functionality.

### Related issues

Tangential, but not directly related
- [Listeners for Datasets - #34327](https://github.com/apache/airflow/issues/34327)
- [Support External Dataset Updates - #29162](https://github.com/apache/airflow/issues/29162) 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Amar1404** [comment]
I think so We need it partial Aware Scheduling here. Let say we are dependent on 3 dataset.
Let say we update each dataset every hour. And we want one dataset should be partial dataset. Like lets say it was updated last if updated upto 6 hours ago then it is fine go ahead and trigger the dag. Otherwise some callback.

It will be a great feature

**Comment by yermalov-here** [comment]
(in case it helps) Directly related:
closed PR - https://github.com/apache/airflow/pull/28333
discussion - https://github.com/apache/airflow/discussions/28253

**Comment by dstandish** [comment]
@sunank200 and I are working on this right now actually

**Comment by harveymarshall** [comment]
@dstandish has there been on movement on this issue? I will be following closely.

**Comment by gabrielrmn** [comment]
any updates here?
looking forward for this improvement!

**Comment by dstandish** [comment]
Yes there's a number of PRs that have been merged for this but this is the one that show you the syntax https://github.com/apache/airflow/pull/37101

**Comment by jscheffl** [comment]
This feature is available since Airflow 2.9, see https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html#logical-operators-for-datasets
