### ISSUE TITLE
优化单个DAG大量任务在页面展示延迟高的问题

### ISSUE THREAD

**Issue by PromiseOne** [apache/airflow#34584]
### Description

希望能够优化单个DAG在前端页面展示的时候页面长时间无响应的问题。

### Use case/motivation

我有很多个任务需要放在同一个DAG中，因为同一个DAG中能够一目了然的展示任务与任务之间的关系。但是如果在不考虑使用子DAG的情况下，使用同一个DAG来展示超过500+的任务时页面的响应时间就开始逐渐令人无法接受，但是我的实际情况是需要展示上万+的任务，目前页面的响应速度无法达到一个让人满意的结果。

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I close this issue as invalid, could you please update it or create a new one in English?
