### ISSUE TITLE
helm chart doesn't support securityContext  for airflow-run-airflow-migration and dag-processor init container

### ISSUE THREAD

**Issue by rahulgoyal2987** [apache/airflow#34595]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.6.3

### Kubernetes Version

1.27

### Helm Chart configuration

helm chart doesn't support securityContext for airflow-run-airflow-migration and dag-processor init container

### How to reproduce

helm chart doesn't support securityContext  for airflow-run-airflow-migration and dag-processor init container. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
> As there was a parallel BugReport for security context in OpenShift in #34599 does this belong together?

It was closed as invalid
https://github.com/apache/airflow/issues/34599#issuecomment-1786955073

**Comment by MPParsley** [comment]
Indeed, it was about redis and statsd but the problem with airflow-run-airflow-migrations remains.
