### ISSUE TITLE
Extra Links not refresh by the "Auto-refresh"

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#34623]
### Apache Airflow version

2.7.1

### What happened

the buttons extra links are not refreshed by the "auto refresh" feature

that mean if you clear a task , and the second run is in running state , the buttons under Extra Links are still linking to the first run of the task

### How to reproduce

run a task with a Extra Links like the `GlueJobOperator` wait for the finish 

clear the task , wait for it to be running , click again on the Extra link it open a new tab on the first run and not the new run

### Operating System

ubuntu 22.04

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
If anyone wants to take this up. we need to add `tryNumber` to the query key [here](https://github.com/apache/airflow/blob/main/airflow/www/static/js/api/useExtraLinks.ts#L45)

**Comment by Rohxn16** [comment]
Hey maybe i can give it a try

**Comment by vchiapaikeo** [comment]
@Rohxn16 , are you still working on this? Happy to take a look at it if you are no longer!

**Comment by Rohxn16** [comment]
@vchiapaikeo feel feee to do please

**Comment by potiuk** [comment]
Assigned.
