### ISSUE TITLE
Keyboard shortcuts opens a modal window for DAG operations  

### ISSUE THREAD

**Issue by svncsvr** [apache/airflow#34685]
### Description

Current implementation of keyboard shortcuts to quickly interact with DAG and Tasks is quite cool. One issue with it though it could also be dangerous if shortcut was pressed accidentally since there is no modal window for user input. 

### Use case/motivation

It would be safer to ask for user approval before i.e clearing, marking DAG runs. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kurayami07734** [comment]
Please assign me to this issue
