### ISSUE TITLE
Drag and drop feature in airflow GUI  (no code ETL)

### ISSUE THREAD

**Issue by sivankumar86** [apache/airflow#34702]
### Description

drag and drop components for each operator,sensor to generate DAG and create a relationship by connecting from GUI.

No code ETL

### Use case/motivation

It would be great if there is a feature to develop workflow using GUI . Example,  drag and drop components for each operator,sensor to generate DAG and create a relationship by connecting from GUI.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
-> https://airflow.apache.org/docs/apache-airflow/stable/index.html#why-not-airflow

**Comment by nathadfield** [comment]
The closest you are going to get to this is the notebook-style interface that Astronomer are building called [Astro Cloud IDE](https://docs.astronomer.io/astro/cloud-ide).

**Comment by sivankumar86** [comment]
I am using below  extension in jupyter if anyone looking for the same.
https://elyra.readthedocs.io/en/latest/getting_started/installation.html
