### ISSUE TITLE
AUTH_REMOTE_USER is gone

### ISSUE THREAD

**Issue by ghost** [apache/airflow#34720]
### Apache Airflow version

2.7.1

### What happened

We upgraded from 2.6.3 to 2.7.1 and the webserver stopped working due to our config with error:

```
ImportError: cannot import name 'AUTH_REMOTE_USER' from 'airflow.www.fab_security.manager'
```

There's a commit called [Fix inheritance chain in security manager (https://github.com/apache/airflow/pull/33901)](https://github.com/apache/airflow/commit/d3ce44236895e9e1779ea39d7681b59a25af0509) which sounds suspicious around magic security imports.

### What you think should happen instead

This is [still documented](https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#other-methods) and it wasn't noted in the changelog as removed, so it shouldn't have broken our upgrade.

### How to reproduce

it's not there, so try to import it and... it's not there.

for now I just switched it to importing directly `from flask_appbuilder.const import AUTH_DB, AUTH_LDAP, AUTH_OAUTH, AUTH_OID, AUTH_REMOTE_USER`

### Operating System

all of them

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
The mentioned commit is not released yet.

For this issue, IMHO importing from `airflow.www.fab_security.manager` is not a good practice, and these example code was added in 2.7.0 by https://github.com/apache/airflow/pull/32759.

I will update the documentation.
