### ISSUE TITLE
Hiding Run Id and Logical date from trigger DAG UI

### ISSUE THREAD

**Issue by hterik** [apache/airflow#34726]
### Description

With the new more user friendly Trigger UI (`/dags/mydag/trigger`), one can direct more users to using Airflow UI directly.

However, the first two questions a user has to answer is **Logical date** and **Run ID**, which are very confusing and in most cases make no sense to override, even for administrators these values should be rare edge cases to override.

![image](https://github.com/apache/airflow/assets/89977373/201327a1-2a18-4cc3-8129-55057fa5e852)

**Is it possible to?**
* Make these inputs opt-in on a per DAG level?
* Global config to hide them from all DAGs?
* Hide under "advanced and optional" section?

Airflow version 2.7.1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Logical date defaults to now, but I believe that customizing it allows a user to "schedule" a manual run. And the custom run id can explain why.


@jens-scheffler-bosch What are your thoughts?
