### ISSUE TITLE
get_external_log_url not visible, partially hidden under the status bar

### ISSUE THREAD

**Issue by hterik** [apache/airflow#34753]
### Apache Airflow version

2.7.1

### What happened

Links defined using `get_external_log_url` in a logger set by config option `logging.logging_config_class` are some times not visible:
Regression after upgrade from 2.5.1 to 2.7.1:
![image](https://github.com/apache/airflow/assets/89977373/524bbd08-011d-4a66-b6cc-a0cff8115bea)

Only if you hover at the very top of it will the outline be seen and you can actually click it. Without hovering over it there is no way to know the button is there.

### How to reproduce

Open grid view, press log tab, scroll to bottom.

### Operating System

Ubuntu 22

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Closed by https://github.com/apache/airflow/pull/35668
