### ISSUE TITLE
Unable to search dags/tasks using filters results in "

### ISSUE THREAD

**Issue by ravi77o** [apache/airflow#34761]
### Apache Airflow version

2.7.0

### What happened

When I use search macros other than "Starts With" when browsing Tasks and DAGs, Airflow disregards them search. 

I noticed that the URL parameters contain `undefined`. For example, `_flt_undefined_dag_id`.

### What you think should happen instead

Airflow UI should filter the tasks/DAGs based off the search macros and also retain the search criteria on the results page.

### How to reproduce

**DAG Runs**
1. Click browse
2. Click DAG Runs
3. Click Search
4. Click Add Filter
5. Click State (for example)
6. Change the "Starts with" to "Contains"
7. In the third box, type in `whatever`
8. Click search

**Task Instances**
1. Click browse
2. Click Task Instances
3. Click Search
4. Click Add Filter
5. Click State (for example)
6. Change the "Starts with" to "Contains"
7. In the third box, type in `whatever`
8. Click search

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other 3rd-party Helm chart

### Anything else

This happens all the time.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bisk1** [comment]
Can't reproduce it on Airflow 2.7.1
![image](https://github.com/apache/airflow/assets/9072987/f01aed76-b1d4-4504-8821-af461f9beea9)

**Comment by ravi77o** [comment]
@Bisk1 thanks for checking -- I listed the incorrect version in my ticket, I experienced it on 2.7.0, not 2.7.1 like I originally had. Closing this out. Thanks again!
