### ISSUE TITLE
need to run airflow cli command "airflow dags details" for multiple DAG IDs

### ISSUE THREAD

**Issue by vidyapanchalZS** [apache/airflow#34765]
### Description

Hello Team,

Hope you are doing well!

We have one use case where we want to check last parsed time for the multiple DAGs. Currently we have one airflow cli command i.e "airflow dags details" which gives the output for only one DAG ID but we want same result of this cli command for multiple DAG IDs.

We would you like to request you to create similar or modify the same cli command for giving last parsed time for multiple tasks.

Thanks & Regards,
Vidya Panchal 

### Use case/motivation

cli command : airflow dags details ----> give as output for only one DAG ID/DAG name.

We want "airflow dags details" cli command also give result for multiple DAG IDs / DAG names. 

### Related issues

We have one business use case where we want to fetch last parsed time for multiple DAGs and perform our business operations accordingly. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by erdos2n** [comment]
I'm happy to pick this up if we want to move forward with this suggestion.

**Comment by eladkal** [comment]
Maybe better to add this as output for `airflow dags list` ?

**Comment by jens-scheffler-bosch** [comment]
I agree adding to `airflow dags list` as additional optional column makes a good sense. Feel free to contribute, probably a good small contribution, entry point could be `airflow/cli/commands/dag_command.py:dag_list_dags()` and adding a new CLI parameter

**Comment by vidyapanchalZS** [comment]
Thank you for acknowledging it. Can we also have similar implementation for REST API where we get DAGs parsing details for multiple DAGs in single API call?

**Comment by sidrahsayyad** [comment]
Team,

Any update on this task ? We need to get the last parsed time information of multiple DAGs at the same time. Right now this would mean running the CLI command multiple times with different DAG IDs. This enhancement will prevent the multiple command executions. Also, as Vidya mentioned, we need similar support in the REST API as well.

Regards,
Sidrah.

**Comment by jens-scheffler-bosch** [comment]
Hi @sidrahsayyad you are polling for status in an Open Source project. You know that people contribute to this sometimes as full time job but mostly in spare time or as side business? There is no SLA behind a feature request.

If you are under pressure then please arrange a support agreement with a commercial vendor to support you on this or feel free to contribute.

Airflow does not provide an SLA for having requested features being implemented.
