### ISSUE TITLE
Airflow Operator LambdaInvokeFunctionOperator should provide option to overwrite read_timeout settings

### ISSUE THREAD

**Issue by vishwaggupta** [apache/airflow#34781]
### Description

Currently LambdaInvokeFunctionOperator doesn't provide option to overwrite read_timeout settings which is defaulted to 60 seconds specially for managed services like AWS MWAA. LambdaInvokeFunctionOperator timeout if Lambda function execution time is more than 60 seconds. Customers have to change to other options like python operator with boto3 based execution.

### Use case/motivation

Providing option to overwrite read_timeout will enable customers to use LambdaInvokeFunctionOperator in cases when AWS lambda function execution time is more than 60 seconds, since it's not well documented in open source community project teams discover this based on DAG step failures. Solving this will save time/effort and create better experience for the project teams.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
@vishwaggupta Right now you could provide timeouts via connection, description was added in Amazon provider documentation, right now it [available in develop version of documentation](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-amazon/stable/operators/lambda.html#invoke-an-aws-lambda-function)

But this good point to add ability propagate botocore config from Operator to Hook, as well as other parameters

**Comment by vishwaggupta** [comment]
@Taragolis - Thank you for prompt response and acknowledging the issue. Based on your feedback we were able to resolve the issue by creating a new connection in Airflow UI of Managed Workflows for Apache Airflow (MWAA) with connection type as "Amazon Web Services" and in Extra field added {"config_kwargs": {"read_timeout": 900}}. We left "AWS Access Key ID" & "AWS Secret Access Key" as blank.
