### ISSUE TITLE
Support multi-select state filtering on grid view

### ISSUE THREAD

**Issue by Usiel** [apache/airflow#34795]
### Description

Replace the existing selects with multi-selects that allow you to filter multiple DAG run states and types at the same time, somewhat similar to my prototype:

![image](https://github.com/apache/airflow/assets/1842905/c4ec0793-1ccb-417d-989c-781997416f97)

### Use case/motivation

I'm not sure if it is just me, but sometimes I wish I was able to show multiple DAG run states, especially `running` and `failed`, at the same time. 
This would be especially helpful for busy DAGs on which I want to clear a few failed runs. Without the multi-select, if I switch from `failed` to `running` DAG runs, I need to orient myself again to find the run I just cleared (assuming there are lots of other running DAG runs). _With_ the multi-select, the DAG run I just cleared stays in the same spot and I can check the logs, while clearing some other failed runs.

I'm not sure we need a multi-select for DAG run types as well. I'd tend to say no, but maybe someone else has a use-case for that.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
Yup, it would be nice to have.

**Comment by vchiapaikeo** [comment]
Happy to give this a try!

**Comment by potiuk** [comment]
Pls

**Comment by Usiel** [comment]
> Happy to give this a try!

Sure, go ahead! I already previously started a prototype, maybe it helps: https://github.com/apache/airflow/compare/main...Usiel:airflow:usiel/add-multi-dag-state-filter

**Comment by vchiapaikeo** [comment]
Nice! I used a similar approach but kept the array serialized as a csv so that we wouldn't have to change all the method signatures in useFilters. Your styling was very helpful :-)
