### ISSUE TITLE
Airflow postgres connection field schema points to database name

### ISSUE THREAD

**Issue by dineshmarimu2** [apache/airflow#34799]
### Apache Airflow version

2.7.1

### What happened

Airflow's postgres connection configuration form has a field called  'schema'  which is misguiding as values mentioned here is used to refer to the database name instead of the schema name. It should be correctly named to 'database' or 'dbname'

### How to reproduce

create a connection on the web UI and choose connection type as postgres.
Have a dag connect to an postgres server with multiple databases
provide the database name in the 'schema' field of the connection form- this would work if nothing else is incorrect in the etl
now change the value in the schema field of the connection form to refer to a schema- this will fail unexpectedly as the schema name field actually points to the database name.

### Operating System

Windows and Linux

### Versions of Apache Airflow Providers

2.71

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> now change the value in the schema field of the connection form to refer to a schema- this will fail unexpectedly as the schema name field actually points to the database name.

https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html#postgresql-connection

**Comment by Taragolis** [comment]
@dinu-bilt Are you sure that we need to close this issue? At least we could rename field in the Connection UI.

**Comment by dinu-bilt** [comment]
Yes that'd  be ideal. Thanks

**Comment by Taragolis** [comment]
I've marked as "good first issue" it should be a simple change, just need to implements `get_ui_field_behaviour` on PostgresHook

Some examples in other Hooks

https://github.com/apache/airflow/blob/659d94f0ae89f47a7d4b95d6c19ab7f87bd3a60f/airflow/providers/arangodb/hooks/arangodb.py#L137-L154

https://github.com/apache/airflow/blob/284fa7000dd342967935aff39b1a6f83f9afb174/airflow/providers/amazon/aws/hooks/base_aws.py#L793-L819

**Comment by pubudu91** [comment]
@Taragolis Was playing around with Airflow a bit, so tried out the fix suggested above. Can you please see if this is ok? If so, will send in a PR. https://github.com/apache/airflow/commit/802e39147e05e783d89fa0db1799d04530a14c1c

The following is how it looks in the UI with my change. 
![Screenshot from 2023-10-06 18-15-43](https://github.com/apache/airflow/assets/6260009/bb0287ad-253e-41e1-a5fe-24e40eb657e5)

Also, I suppose we'll have to update the docs at https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-postgres/connections/postgres.rst as well right?

**Comment by GarimaUttam** [comment]
Sir @Taragolis  I want to start contributing as a newcomer. Plz suggest me how to start contributing. Should I ask you to assign them or should we start cloning and try to make PR's directly.

**Comment by Taragolis** [comment]
> I want to start contributing as a newcomer. Plz suggest me how to start contributing. Should I ask you to assign them or should we start cloning

We have a documentation how to start contribution to Airflow:
- [Contributor's Quick Start](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#contributors-quick-start)
- [Airflow Breeze](https://github.com/apache/airflow/blob/main/BREEZE.rst) 
- [CONTRIBUTING.rst](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst)

In general speaking you don't have to be assigned to the issue for start working on the issue, but it could be done if you feel that it required some time to implement new feature/bug fix for avoid situation that multiple contributors starts working on issue.

For particular this on @pubudu91 already create PR and add tag `closes: #34799` so better select another one.

In additional I want to say that if you know how to make Airflow better and you could propose the changes, then you don't have to create issue, you could create a PR and add description within.

**Comment by petr-larin** [comment]
Hi Folks! When exporting a postgres connection from Airflow to json using `airflow connections export`, the field name is still `schema` rather than `database`.
