### ISSUE TITLE
Feature Request : Support "force" as a flag to the Airflow Clear Command

### ISSUE THREAD

**Issue by r39132** [apache/airflow#348]
I'm building automation around the airflow CLI and would like to clear a DAG for a set of dates. I'd like to call it and just force without needing to programmatically sending `"yes"` to stdin. 

It would be nice to have an optional --force or `-c (coerce)` flag to just clear state. '-f' is already taken to mean `run only failed` tasks.

**Comment by r39132** [comment]
I recall seeing that this was implemented somewhere and I was about to close this but I can't find the pull request.

**Comment by mistercrunch** [comment]
`airflow clear --no_confirm`
