### ISSUE TITLE
EcsRunTaskOperator

### ISSUE THREAD

**Issue by rotemlevibigabid** [apache/airflow#34802]
### Apache Airflow version

2.7.1

### What happened

EcsRunTaskOperator on deferrable mode
ecs task Exit code: 0 but deferrable task never ends

### How to reproduce

use deferrable EcsRunTaskOperator and do  Exit code: 0 

### Operating System

mac

### Versions of Apache Airflow Providers

latest

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Could you also provide information about installed providers? Did you use try to use latest AWS Provider?

**Comment by shubham22** [comment]
@rotemlevibigabid - are you still running into this issue? If so, could you please add more information as Andrey requested? Also, please confirm that you run into this issue in deferrable mode only. cc: @syedahsn
