### ISSUE TITLE
Upgrade Helm chart dependency to bitnami/postgresql 13.x.x and PostgreSQL 16

### ISSUE THREAD

**Issue by dnskr** [apache/airflow#34817]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

1.27

### What happened

Airflow Helm chart 1.11.0 depends on [bitnami/postgresql:12.10.0](https://github.com/apache/airflow/blob/38e6607cc855f55666b817177103585f080d6173/chart/Chart.yaml#L37) subchart and deploys [PostgreSQL 11](https://github.com/apache/airflow/blob/38e6607cc855f55666b817177103585f080d6173/chart/values.yaml#L2232C14-L2232C14) by default.

Apart from good practice of keeping dependencies up to date, there is an end-of-life for `PostgreSQL 11` coming in November 9, 2023 as described in [PostgreSQL  Versioning Policy](https://www.postgresql.org/support/versioning/).

### What you think should happen instead

Next Airflow Helm chart release should use latest `bitnami/postgresql:13.x.x` and `PostgreSQL 16` by default.

### How to reproduce

Deploy Airflow Helm chart 1.11.0 with default configuration.

### Anything else

This issue is created to highlight the problem and discuss how it should be fixed with minimal impact on end users.

PostgreSQL was intentionally downgraded from `15` to `11` after `bitnami/postgresql` upgrade from `10.5.3` to `12.1.9`.
Related PRs:
 - https://github.com/apache/airflow/pull/29071
 - https://github.com/apache/airflow/pull/29207

The PR https://github.com/apache/airflow/pull/29207 also contains the discussion of future version upgrade.

Also related PRs with minor changes and fixes:
 - https://github.com/apache/airflow/pull/29210
 - https://github.com/apache/airflow/pull/29478
 - https://github.com/apache/airflow/pull/33747

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
>and PostgreSQL 16 by default.

This would unlikely happen, Airflow CI do not have regular runs on Postgres 16 yet (https://github.com/apache/airflow/pull/34543)

After EOL Postgres 11 I guess default would be Postgres 12, at least this happen for other components: default python is 3.8, default db backend the oldest one.

**Comment by dnskr** [comment]
Airflow Helm chart has been released recently, so taking it into considiration, there is a good chance that Airflow can support Postgres 16 officially before next Helm chart release.
I'm fine with upgrading PostgreSQL to the newest possible version, either it's 15, 14, 13 or even 12. However, I'm not sure that upgrading to PostgreSQL 12 is a pragmatic solution, because end-of-life for PostgreSQL 12 coming next year (November 14, 2024).

Main challenge with the upgrade is that there is no auto-upgrade options for major versions of PostgreSQL as far as I know, i.e. major version upgrade flow requires users to manage it manually with some database downtime. See https://www.postgresql.org/docs/current/pgupgrade.html for more details.

**Comment by eladkal** [comment]
We added Postgres 16 support to main branch https://github.com/apache/airflow/pull/34543

**Comment by dnskr** [comment]
Looks like there is no automated solution for the problem at the moment.
Related issue https://github.com/bitnami/charts/issues/14926

**Comment by potiuk** [comment]
We can continue upgrading it manually as we do now. And it's fine to upgrade to postgres 16 immediately. Postgres in our chart is not intended for production use and you **SHOULD** use external postgres. So we do not have to maintain any compatibility or upgrade path.
