### ISSUE TITLE
Add AthenaSqlHook based on PyAthena

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#34823]
### Body

The problem:

`AthenaOperator` store query result in S3 and push to xcom the query_id.
To read the result one must find the path in S3 of the query output (using query_id), download the output file, open it and then ask questions on it. This is very very very frusturating.

My query for example is `SELECT(1) FROM...`. I simply want to count records and compare it to something. I want the record number to be pushed to Xcom. This enables variety of options such as Branching, ShortCircuit and other

We probably can not (don't want) to just add `push_query_result` flag to `AthenaOperator` from what I see the API of the hook doesn't allow this easily.

We should see if we can overcome this somehow. (maybe a new hook with [`PyAthena`](https://pypi.org/project/PyAthena/)? by doing so Athena should be compatible with all our current SQL operators.)
This is a big blocker from utalizing Athena efficiently. 

The Task: (at least how I see it)
Create `AthenaSqlHook` which is based on `PyAthena`. Hook should inherit from `DbApiHook` 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by treyyi** [comment]
Hi @eladkal, 
I would like to take a look and work on this new `AthenaSqlHook` implementation.
Could you assign this task to me?

Thanks!

**Comment by flolas** [comment]
Hi @treyyi Are you working on this? I'm really interested in this hook. Happy to help if you need so

**Comment by shubham22** [comment]
@treyyi - please let us know if you're looking into this. If not Treyyi@, @flolas, would you have time to implement this?
