### ISSUE TITLE
Adding property files option in the Spark Submit command

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#34838]
### Description

spark-submit command has one of the options to pass the properties file as argument. Instead of loading multiple key, value via --conf option, this will help to load extra properties from the file path. While we have support for most of the arguments supported in spark-submit command in SparkSubmitOperator, this one `property-files` is missing. Could that be included?
```[root@airflow ~]# spark-submit --help
Usage: spark-submit [options] <app jar | python file | R file> [app arguments]
Usage: spark-submit --kill [submission ID] --master [spark://...]
Usage: spark-submit --status [submission ID] --master [spark://...]
Usage: spark-submit run-example [options] example-class [example args]

Options:

 --conf, -c PROP=VALUE       Arbitrary Spark configuration property.
  --properties-file FILE      Path to a file from which to load extra properties. If not
                              specified, this will look for conf/spark-defaults.conf.
```

### Use case/motivation

Add the property-files as one of the options to pass in the SparkSubmitOperator to load the extra config properties as file

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ghostp13409** [comment]
Hi @Bowrna,
I'm a first time contributor, and i feel like I could give this a try. Can I work on it?

**Comment by Bowrna** [comment]
sure @ghostp13409 , ping here if you need any help

**Comment by ghostp13409** [comment]
Hi @Bowrna ,
I've created the PR. kindly review it.
I've added property-files operator in the spark submit operator.
As I'm a newcomer to this industry I'm not sure if I need to do any other changes other than this. please let me know if there is a need to do any additional changes.
