### ISSUE TITLE
Dataset view shows nothing when DAGs inlet and outlet are the same

### ISSUE THREAD

**Issue by UTRI-JR7** [apache/airflow#34867]
### Apache Airflow version

2.7.1

### What happened

I have noticed that when I create a DAG which starts right after a dataset update and the same DAG updates the same dataset, Dataset view in webserver cant render

### What you think should happen instead

It could be possible that instead of that dag and dataset refers each other as in dag dependency view? 

### How to reproduce

Creating a DAG with a dataset which is an inlet and outlet

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Okay, having a circular reference in DAG triggers might be generating effects unforseen. Can you tell about the use case? Otherwise I rather believe that we might need to think about validation that circular references in dataset triggers are prevented (we do the same validation within DAG tasks). But before preventing for such to happen, I would like to understand "why".
Can you tell us your use case?

**Comment by UTRI-JR7** [comment]
Hi,

We simply have a DAG which sensor a storage, whenever a file which match a prefix arrives,  launch the nexts tasks.
It's like a kind of CDC in batch that nowadays runs once a day (we don't know when) but we would like to increase frecuencies.

The schedule behaviour works as follow:

We have a DAG "associated" with a Dataset that updates it,  and every time that this Dataset is updated, DAG is restarted 

The point is that the DAG  Dependicies View show something like this:

![image](https://github.com/apache/airflow/assets/77438029/aceef6f7-98d9-430f-96c9-b4108e846088)

But in Dataset view, there must be a render problem due to a loop in DAG-Dataset dependencies.

![image](https://github.com/apache/airflow/assets/77438029/378f99d0-a527-41a2-8dd3-85905b2e1921)

I don't know whether i am misusing airflow Datasets, or this behaviour can be considered as a bug in the react-flow code, that could be render as the DAG Dependencies view with a loop in the flow.

Thanks in advance!
