### ISSUE TITLE
Postgres conn type should normalize to postgresql (instead of the inverse)

### ISSUE THREAD

**Issue by dhuang** [apache/airflow#34876]
### Apache Airflow version

2.7.1

### What happened

Currently Airflow normalizes conn types of `postgresql` to `postgres`, which means calling`Connection.get_uri()` always gets a `postgres://...` string. If we want to use this outside of the `PostgresHook` (which inverts this back in its [get_uri()](https://github.com/apache/airflow/blob/main/airflow/providers/postgres/hooks/postgres.py#L186)), you'll run into issues using the long deprecated `postgres` dialect.

### What you think should happen instead

Seems like we should just invert the normalization? Happy to put a quick PR up if this is what we want.

### How to reproduce

Call `Connection.get_uri()` on a connection with `conn_type` as `postgresql`.

### Operating System

Debian 12

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Airflow Connection URL it is representation (serialisation) of Airflow Connection, not psycopg2 URL nor SQLAlchemy URL

> Call Connection.get_uri() on a connection with conn_type as postgresql.
 
This is a combination of bad assumption and wrong implementation: https://lists.apache.org/thread/8rhmz3qh30hvkondct4sfmgk4vd07mn5
