### ISSUE TITLE
Contents of DAG files are assumed to have not changed

### ISSUE THREAD

**Issue by indexKevinBoak** [apache/airflow#34917]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version 2.1.4

A python file containing a single DAG definition was somehow linked to multiple DAGs.

ie.
2 DAGs, "DAG-A" & "DAG-B" were pointing to "file.py", but file.py only contained "DAG-B"

The UI would should "DAG-A", and if you clicked "Code", it would take you to the code for "DAG-B". 

### What you think should happen instead

I don't think much more explanation is necessary.
Once "file.py" no longer contained DAG-A, DAG-A should no longer have been linked to that file.

If DAG-A had moved to a new file, then it should be linked there. If it had been removed entirely, then it should cease to exist as a DAG in the system.

### How to reproduce

1. Create a new file "my-dag-file.py" which contains a definition for DAG-A to run on some schedule
2. Sync Airflow with this DAG, and let the DAG  run.
3. Update "my-dag-file.py" to no longer contain "DAG-A", but instead replace it with a new job "DAG-B"
4. Sync DAGs again
5. You *should* see both DAG-A and DAG-B still... even though DAG-A no longer exists.
6. DAG-A will fail to run if you try to execute it.

### Operating System

linux/amd64

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> Version 2.1.4
> A python file containing a single DAG definition was somehow linked to multiple DAGs.

Could you provide simple examples which could be tested on modern Airflow version? Because I guess your case  (related to dynamic dags) might be fixed in 2.2 or 2.3, which are released for about 2 years ago.
