### ISSUE TITLE
TriggerDagRunOperator does not trigger dag on subsequent run even with reset_dag_run=True

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#34953]
### Discussed in https://github.com/apache/airflow/discussions/24548

<div type='discussions-op-text'>

<sup>Originally posted by **don1uppa** June 16, 2022</sup>
### Apache Airflow version

2.2.5

### What happened

I have a dag that starts another dag with a conf.   
I am attempting to start the initiating dag a second time with different configuration parameters.   I it to start the other dag with the new parameters.

## What you think should happen instead

It should use the new conf when starting the called dag

### How to reproduce

See code in squsequent message

### Operating System

windows and ubuntu

### Versions of Apache Airflow Providers

N/A

### Deployment

Docker-Compose

### Anything else

**Work around for now is to delete the previous "child" dag runs.**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

**Comment by abdurafeyf** [comment]
Assign it to me. maybe i can help

**Comment by boushphong** [comment]
@abdurafeyf Do you mind if I take over? :bow:
