### ISSUE TITLE
Token expiring with deferred SnowflakeOperator

### ISSUE THREAD

**Issue by jonathanleek** [apache/airflow#34968]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

In Airflow 2.7.1, it appears that the SnowflakeOperator is not renewing it's token when deferred, causing the task to fail to resume.

### What you think should happen instead

Token should renew, similar to how the AWSBaseHook does (https://github.com/astronomer/astronomer-providers/issues/1292)

### How to reproduce

Defer a Snowflake Sensor for an extended period of time.

### Operating System

linux

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jonathanleek** [comment]
`[2023-09-26T13:10:00.446+0000] {snowflake.py:219} INFO - Task deferred
[2023-09-26T13:10:00.453+0000] {taskinstance.py:1524} INFO - Pausing task as DEFERRED. dag_id=*****, task_id=*******, execution_date=20230925T080000, start_date=20230926T130958`

When it resumed 5 minutes later it failed
`[2023-09-26T13:15:29.054+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1608, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/astronomer/providers/snowflake/operators/snowflake.py", line 242, in execute_complete
    msg = f"sfquid: {event['query_id']}, {event['type']}: {event['message']}"
                     ~~~~~^^^^^^^^^^^^
KeyError: 'query_id'`

**Comment by Taragolis** [comment]
> /usr/local/lib/python3.11/site-packages/astronomer/providers/snowflake/operators/snowflake.py"

This provider is not a part of [Community Providers](https://airflow.apache.org/docs/#providers-packagesdocsapache-airflow-providersindexhtml)
