### ISSUE TITLE
Users Error

### ISSUE THREAD

**Issue by renato-rt** [apache/airflow#34970]
### Apache Airflow version

2.7.2

### What happened

When clicking on 'List Users' I am getting an error called:

But I don't have anyone connected, according to the error.

### What you think should happen instead

Show users

### How to reproduce

Click on menu Secutiry, after click on 'List Users'

### Operating System

WIndows 11

### Deployment

Official Apache Airflow Helm Chart

### Anything else

![image](https://github.com/apache/airflow/assets/73500709/c9b788ca-c18d-46c8-a211-75cd99e74bb8)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by renatogav** [comment]
Wow, that worked! You are amazing guys, thank you so much @Taragolis!

**Comment by renato-rt** [comment]
Wow, that worked! You are amazing guys, thank you so much @Taragolis!

**Comment by Rafnel** [comment]
Wanted to add another datapoint, we are on Airflow 2.6.3 and our users/roles page has been broken for a long time, same error as above. Downgrading to WTForms 3.0.1 fixed the issue. Thanks all!
