### ISSUE TITLE
SFTPToGCSOperator doesn't fail like `SFTPOperator` if the source file doesn't exist

### ISSUE THREAD

**Issue by ishiis** [apache/airflow#34989]
### Apache Airflow version

2.7.2

### What happened

When source_path contains a wildcard, SFTPToGCSOperator succeeds if the file does not exist in the specified path.

### What you think should happen instead

If the file does not exist, the operator should fail.

### How to reproduce

1. Include wildcards in source_path.
2. If the file does not exist in source_path, it will be reproduced.

```python
SFTPToGCSOperator(
    task_id=f"sftp_to_gcs_task",
    gcp_conn_id="gcp_conn_id",
    sftp_conn_id="sftp_conn_id",
    source_path="/var/path/to/*",    # wildcard within source_path
    destination_bucket="my_bucket",
    destination_path="path/to"
)
```

### Operating System

GCP Container

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.5.0

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
What behaviour then expected if required to move object (`move=True`)?
If task completed successfully and after that it restarted then with your suggestion the task failed, which might breaks someone pipeline.
