### ISSUE TITLE
the redis and hive port type issues

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#350]
We I start worker I got this imformation.

ERROR/MainProcess] consumer: Cannot connect to redis://ctu-cco-int.ubisoft.org:6379/12: Int or String expected.

I fould it is bcs socket.getaddrinfo request the int type of port fields int python2.7/site-packages/redis/connection.py

I found it is also have convert in **init** function, however it look like the <class 'future.types.newint.newint'> type could not been convert to int
logging.info(type(port))  # class 'future.types.newint.newint'
self.port = int(port)
logging.info(type(self.port))  # still class 'future.types.newint.newint'

Another question is also about the port of hive, after I config the hive2 connect,  I test it via the Hot Query. it is not work. 

it is bcs the port in socket.getaddrinfo function need a int type, but long type give. So I have to manual  convert it to int in python2.7/site-packages/thrift/transport/TSocket.py

I checked the define in model.py of airflow. the port is defined int. it is very strange

**Comment by mistercrunch** [comment]
Looks strange, maybe try:
`pip install redis --upgrade`

**Comment by griffinqiu** [comment]
I have tried. It look like some package conflict or missing

**Comment by mistercrunch** [comment]
Sorry, we cannot help with that. Try Googling your Redis issue, ask the Redis community, or defer to RabbitMQ...

**Comment by griffinqiu** [comment]
I have found the reason. It is bcs the Python 2.7 version issue.  I reinstall python to 2.7.10. it work.
