### ISSUE TITLE
SlackAPIFileOperator non-JSON Response 504

### ISSUE THREAD

**Issue by M-Waleed-Khan** [apache/airflow#35009]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi, I am using SlackAPIFileOperator to share a file to slack from airflow, The file is sent everytime but the airflow dag fails some times with larger files > 150 MB file size and sometimes it fails even with 10 MB file size
The exception says
ERROR - An error occurred while calling SlackAPIFileOperator : Received a response in a non-JSON format: <!DOCTYPE html>
<p>It seems like there’s a problem connecting to our servers, and we’re investigating the issue.</p>

I trimmed both the comments above because they are long, I will paste the actual whole error in comment.

### How to reproduce

use SlackAPIFileOperator to share a file heres the code
`slack_operator_file = SlackAPIFileOperator(
            task_id="fileshare_slack",
            token=token,
            channel=channel,
            initial_comment=initial_comment,
            filename=file_name,
            filetype=filetype
        )`

### Operating System

Mac and AWS MWAA both same

### Versions of Apache Airflow Providers

apache-airflow-providers-slack==4.2.0
apache-airflow-providers-http==2.0.3
apache-airflow-providers-amazon==2.4.0

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> I trimmed both the comments above because they are long, I will paste the actual whole error in comment.

Better provide full logs because `SlackAPIFileOperator : Received a response in a non-JSON format:` doesn't not make any sense without error message and response

> apache-airflow-providers-slack==4.2.0

Current version is 8.2.0 did you tried on the latest version?

**Comment by M-Waleed-Khan** [comment]
> > I trimmed both the comments above because they are long, I will paste the actual whole error in comment.
> 
> Better provide full logs because `SlackAPIFileOperator : Received a response in a non-JSON format:` doesn't not make any sense without error message and response
> 
> > apache-airflow-providers-slack==4.2.0
> 
> Current version is 8.2.0 did you tried on the latest version?

Hi Taragolis, thanks for reply here is the complete log

`[2023-10-17, 13:46:50 UTC] {{run_fileshare_shedular.py:26}} ERROR - An error occurred while calling SlackAPIFileOperator : Received a response in a non-JSON format: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Server Error | Slack</title><meta ... The server responded with: {'status': 504, 'headers': {'x-edge-backend': 'envoy-www', 'access-control-allow-credentials': 'true', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'cache-control': 'no-cache', 'content-length': '7295', 'content-type': 'text/html; charset=utf-8', 'x-slack-edge-shared-secret-outcome': 'no-match', 'date': 'Tue, 17 Oct 2023 13:46:50 GMT', 'server': 'envoy', 'via': 'envoy-edge-bom-mkrdfoic', 'connection': 'close'}, 'body': '<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="utf-8">\n\t<title>Server Error | Slack</title>\n\t<meta name="author" content="Slack">\n\t<style>\n\t\t/* General */\n\t\t@font-face {\n\t\t\tfont-family: \'Slack-Lato\';\n\t\t\tfont-style: normal;\n\t\t\tfont-weight: 400;\n\t\t\tsrc: local(\'☺\'), url(https://a.slack-edge.com/80588/fonts/lato-2-compressed/lato-regular.woff2) format(\'woff2\'), url(https://a.slack-edge.com/80588/fonts/lato-2/lato-regular.woff) format(\'woff\');\n\t\t}\n\t\t@font-face {\n\t\t\tfont-family: \'Slack-Lato\';\n\t\t\tfont-style: normal;\n\t\t\tfont-weight: 700;\n\t\t\tsrc: local(\'☺\'), url(https://a.slack-edge.com/80588/fonts/lato-2-compressed/lato-bold.woff2) format(\'woff2\'), url(https://a.slack-edge.com/80588/fonts/lato-2/lato-bold.woff) format(\'woff\');\n\t\t}\n\n\t\t* {\n\t\t\t-ms-box-sizing: border-box;\n\t\t\t-moz-box-sizing: border-box;\n\t\t\t-webkit-box-sizing: border-box;\n\t\t\tbox-sizing: border-box;\n\t\t}\n\t\thtml, body {\n\t\t\twidth: 100%;\n\t\t\toverflow-x: hidden;\n\t\t}\n\t\thtml.desktop {\n\t\t\tmargin-top: 30px;\n\t\t}\n\t\tbody {\n\t\t\tmargin: 0;\n\t\t\tfont-family: \'Slack-Lato\', sans-serif;\n\t\t\tfont-variant-ligatures: common-ligatures;\n\t\t\t-webkit-font-smoothing: antialiased;\n\t\t\t-moz-osx-font-smoothing: grayscale;\n\t\t\tcolor: #555459;\n\t\t\tfont-size: 1.125rem;\n\t\t\tline-height: 1.5rem;\n\t\t\tbackground: #f9f9f9;\n\t\t}\n\n\t\ta, a:link, a:visited {\n\t\t\tcolor: #3aa3e3;\n\t\t\ttext-decoration: none;\n\t\t}\n\n\t\th1 {\n\t\t\tfont-size: 2rem;\n\t\t\tline-height: 2.5rem;\n\t\t\tletter-spacing: -1px;\n\t\t\tfont-weight: 700;\n\t\t\tfont-family: \'Slack-Lato\', sans-serif;\n\t\t\tmargin: 0 0 1rem 0;\n\t\t}\n\t\t@media only screen and (max-width: 640px) {\n\t\t\th1 {\n\t\t\t\tfont-size: 1.75rem;\n\t\t\t\tline-height: 2rem;\n\t\t\t}\n\t\t}\n\n\t\tp {\n\t\t\tmargin: 0 0 1rem 0;\n\t\t}\n\n\t\t/* Page */\n\t\t#page {\n\t\t\twidth: 100%;\n\t\t\ttop: 0;\n\t\t\tleft: 0;\n\t\t\tbottom: 0;\n\t\t\tright: 0;\n\t\t}\n\t\t#page_contents {\n\t\t\tmargin: 0 auto;\n\t\t\tpadding: 8rem 2rem;\n\t\t}\n\t\t@media only screen and (max-height: 768px), screen and (max-width: 640px) {\n\t\t\t#page_contents {\n\t\t\t\tpadding: 6rem 2rem;\n\t\t\t}\n\t\t}\n\t\t@media only screen and (min-width: 1024px) {\n\t\t\t#page_contents {\n\t\t\t\twidth: 1024px;\n\t\t\t}\n\t\t}\n\t\t@media only screen and (max-width: 640px) {\n\t\t\t#page_contents {\n\t\t\t\twidth: 100%;\n\t\t\t\tpadding: 1rem 0.8rem;\n\t\t\t\tmargin-top: 70px;\n\t\t\t}\n\t\t}\n\n\t\t/* Top nav */\n\t\tnav.top.persistent, nav.top.with_color {\n\t\t\tbackground: #fff;\n\t\t\tbox-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);\n\t\t}\n\t\tnav.top {\n\t\t\tposition: fixed;\n\t\t\ttop: 0;\n\t\t\twidth: 100%;\n\t\t\theight: 70px;\n\t\t\tz-index: 99;\n\t\t}\n\t\thtml.desktop nav.top {\n\t\t\tpadding-top: 30px;\n\t\t\theight: 100px;\n\t\t}\n\t\tnav.top.persistent .logo, nav.top.with_color .logo {\n\t\t\tbackground-position: left bottom;\n\t\t}\n\t\tnav .logo {\n\t\t\tbackground-size: 120px 31px;\n\t\t\theight: 31px;\n\t\t\twidth: 120px;\n\t\t\tfloat: left;\n\t\t\tmargin: 20px 0 0 20px;\n\t\t\tbackground: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAfCAYAAAAslQkwAAAHLUlEQVR42u2afUxTVxiHKwIqouLUOY2zHXNb4rS3iIgofk2NMXM6s6ARysIWHcu+iCyiUakFEjVkm9M4N0w29s90c8t0LbZ0YsziqKBExYGKOKXUDzYpUlCnE7j7XXI68XpOObfUjSZ9kyeB+55e7+Xp+XjPUcUT8WXuqfH25v2gYkqpe0eC3f1E17xgNSZqrdk/gQqtxfCp7ogxStU7YjlYJWMM6O0xAKyiEA78G9PKWxLiS91tU0qbxQe4qxbWiv2kfIzNOBNS27WWbNGDYM0+HVtREKb6/+N3IMpYGACCnwIihSHAvwG5BySpcqYea14m5SHXIkmVo7MZXw0KDgTBGJZpguPtboOUR2+9RBOM6+uCggNAsDTnMgTnkB7soPZgi2FDUHAACJYWVNKcGxQc8ILZIS2opDkXUg0gp5Oy1jlBwQEpmD+CggNEcIK9ZRp6ZREWVJcw/DpYoE012hTMONk6QongGJthoWAx/Ky1GioF66btsYe2+vKg48EWsB+cI/JOgEKwEkT5QfAcsJvctw4cB7tAAsnHgXwZ7wJvMQHkgiPgAqgGJpAH1H4QrAX5FIwgXDX1mDveU+fyAtHnZl8W+/MIFmzGRY+usA3Hk8R9fTnFRoEC0AZEL/xFXizCB8GjgbWb+xeCdMr1Ui+SvgUdXu7ZBvaAobyCKe3qKe3awVJPGfQ9h1RaHbycS7DF8Cu9TjbM55AbAoqBqIDFCgVHg8uc93ZyCtaBKwqe+SKYoFBwf1DOaPfhgzLI7i71TXBLJqmDq2gCsW35ARF8gyrYakzjELye8QI3wW3K9WsgVIHgfuAUEHnhEDwGXPfhPk4wTIHgvYw2n8s3MvJ9E+yOVyF0xYZdFLkdgiU3Rspj3nXJ84Ilu22yNe8FDsHyHnMWTOySV4O3QQ3Jb1Y4B2cBkUE7+bxbkWDvI84N4PQybH/JKdjAyFtBX9lBgjgYkiuUzcEtW/4dAUo2D0Mv/e1huYZckqYINrTrirOzOOQOpLzAD16G8mVArUBwKGig5O+ADBAJPPESqOQQPJPR5iB4TjYt7OuSbwXZIIJDcBLjC1IJBqloMVsUQzHkLobodZhbN7DA4ipjennzZPnnk6qN4Vg4LRWKs9/z9FxPYAjPlOZjCYh/P/ZQ7kQVX/QBbobk+SC8h2VSIiXXAeZ6OeEp70ZwASUPkcz4inxmJOciax64w5iangYBFyVAZNACDoA3wCAfBK+l5PYCb/FmN4IvynL3wXA/1sGNlGu3wCTADkf064mOsSk24KxTp1yXcGj0Rk8e1+c61CkluH4ePxf+qUnDAzwIV5GwoNEkHAZXG83a62yEGpdZu7vFHMv70lPAPZZk2UvmgH4KBG+j5NJ7KPiuLHfabxsdbLyf2tVHp8Q5xia31Y1NFh9CnfyxlHdqUmch39E1h98vXIt9K6JT7kHd/EaTVlQCJJ8Rq5N4D69fUVBy2EE4p+CdlFxyDwSHUGr1o/+B4O2AHeiVe4g4qmDINNHy9Rr9ik7BZsFGxCmiyayFOO6IBCuBTVYe0djKKTibktvWwx58VZZrBaF+FFzGuJ7hTfARmkDPEA3RNbQ8xG/qFGzSVvoi2GXWrVL5FmFk6M4C1ZSXPcspeBEQKUI0gBWfdSP4R0p+I2BFGkhSIDgaXGKUdEvo868mJYcm0KnRzybzby1VMD4n5TGv7lQs16Rtd1lixnPIfBLEdbPSrqSshMM5BEcyVqTVQCf7dyLARxxlUgol/zdYDUJkz51Ocp6pZRrnTtZEcIuSu039W0lzKXrjUdrwzCO4uShxKBZXJ5XIbSoS1qr4wghEYAHTQZgsPwLUyV7UrWCjYwcQKdwHdlBAyrJmzo2OUHCe0e4y2AsKQS2jTT7nRsdrjFq4gToCiUZjSL0mdQGG5fQ6tZ4suTkEkxArYsOainQvYz7ObDLr1jAxCemk5/JEOGig/OFrifASxnz8jQLBI8Efft6qnOXpmQq5CyYp2KrMY7SpBlGAHdyCH2/ogaiQa2CUwsOGeZTyhsU9zsOGNI7TL/kwnqrwsKEPMDHaHQZhfhGMkucsht7WTlDrukzCdy5bnD92VYaDLxT8oa6ABB/Pg+fIRgsaNWA9p2DPF8fJ8dxXwXQfjwsHg3OMtl/7S7BDPs9C9EXRHBuh8k+MBmtACWiinAGfAWvBACAPK6iSkQhoMQTkUb4UF8BGcv8l4KSMwm7+A3sGsIN22YKojJRd/Rlf7ioKkZS2z4NTjPbJ/hdMcBXpklSPJ6KABowlw5Tfg8geR3qIvyKMPPMo8ty9I7DCPkHd6FDrM73VwU0m3TuqYPT+gOCtlE2OjiuaZB3Zh/7k0VJIaHMVCy+qgtH7o0GbOhDD9C9d5Lbh9yxP3mWJH4zyqNQjFz/fh+DVqmAESpA6+Rn9DKc6Jdn5rH7cI3nRGHLTFDOr6WDMiuaiuGhVMHpN/AN0GQvJQUqdZQAAAABJRU5ErkJggg==) left top no-repeat;\n\t\t}\n\n\t\t/* Card */\n\t\t.card {\n\t\t\tbackground-color: #fff;\n\t\t\tborder-radius: 0.25rem;\n\t\t\tbox-shadow: 0 1px 0 rgba(0, 0, 0, 0.25);\n\t\t\tpadding: 2rem 2rem 1rem;\n\t\t\tmargin: 0 auto 2rem;\n\t\t\tposition: relative;\n\t\t\tborder: 1px solid #e8e8e8;\n\t\t}\n\t\t@media only screen and (max-width: 640px) {\n\t\t\t.card {\n\t\t\t\tpadding: 1rem;\n\t\t\t}\n\t\t}\n\t\t.warning_icon {\n\t\t\tmargin: 0 4px;\n\t\t\ttransform: translateY(2px);\n\t\t}\n\t</style>\n</head>\n<body>\n\t<nav class="top persistent">\n\t\t<a href="https://status.slack.com/" class="logo" data-qa="logo"></a>\n\t</nav>\n\t<div id="page">\n\t\t<div id="page_contents">\n\t\t\t<h1>\n\t\t\t\t<svg width="30px" height="27px" viewBox="0 0 60 54" class="warning_icon"><path d="M51.6 54C56.9 54 60 51 60 47 60 45.4 59.6 43.8 58.6 42.1L36.9 4.8C35 1.6 32.5 0 30 0 27.5 0 25 1.6 23.1 4.8L1.4 42.1C0.4 43.8 0 45.4 0 47 0 51 3.1 54 8.4 54L51.6 54ZM51.6 49.5L8.4 49.5C6 49.5 4.7 48.3 4.7 46.6 4.7 45.9 4.9 45.1 5.3 44.2L27.1 7C27.9 5.5 28.9 4.8 30 4.8 31.1 4.8 32.1 5.5 32.9 7L54.7 44.2C55.2 45.1 55.4 45.9 55.4 46.6 55.4 48.3 54 49.5 51.6 49.5ZM30 33C31.7 33 33 31.6 33 30L33 18C33 16.3 31.7 15 30 15 28.4 15 27 16.3 27 18L27 30C27 31.6 28.4 33 30 33ZM30 45C32.1 45 33.8 43.3 33.8 41.2 33.8 39.2 32.1 37.5 30 37.5 27.9 37.5 26.3 39.2 26.3 41.2 26.3 43.3 27.9 45 30 45Z" fill="#D94827"/></svg>\n\t\t\t\tServer Error\n\t\t\t</h1>\n\t\t\t<div class="card">\n\t\t\t\t<p>It seems like there’s a problem connecting to our servers, and we’re investigating the issue.</p>\n\t\t\t\t<p>Please <a href="https://status.slack.com/" target="_blank" rel="noopener noreferrer">check our Status page for updates</a>.</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<script type="text/javascript">\n\t\tif (window.desktop) {\n\t\t\tdocument.documentElement.className = \'desktop\';\n\t\t}\n\n\t\tvar FIVE_MINS = 5 * 60 * 1000;\n\t\tvar TEN_MINS = 10 * 60 * 1000;\n\n\t\tfunction randomBetween(min, max) {\n\t\t\treturn Math.floor(Math.random() * (max - (min + 1))) + min;\n\t\t}\n\n\t\twindow.setTimeout(function () {\n\t\t\twindow.location.reload(true);\n\t\t}, randomBetween(FIVE_MINS, TEN_MINS));\n\t</script>\n</body>\n</html>\n'} `

**Comment by Taragolis** [comment]
According to the error some issues with the Slack API itself, see [504 Status code](https://developer.mozilla.org/en/docs/Web/HTTP/Status/504)

I would recommend to setup retries to that task, that might help in case of such errors.

And I just wondering, is it only failed with 50x status codes? Asked because there is similar issue might happen but the nature is different, see: https://github.com/slackapi/python-slack-sdk/issues/1165#issuecomment-1021995427

**Comment by M-Waleed-Khan** [comment]
> According to the error some issues with the Slack API itself, see [504 Status code](https://developer.mozilla.org/en/docs/Web/HTTP/Status/504)
> 
> I would recommend to setup retries to that task, that might help in case of such errors.
> 
> And I just wondering, is it only failed with 50x status codes? Asked because there is similar issue might happen but the nature is different, see: [slackapi/python-slack-sdk#1165 (comment)](https://github.com/slackapi/python-slack-sdk/issues/1165#issuecomment-1021995427)

Yes, the respone is same 504 everytime. I can implement retry in the code but on manual retries it fails 100% means everytime. The file is sent and received on slack, but the dag fails with this response

**Comment by M-Waleed-Khan** [comment]
> > According to the error some issues with the Slack API itself, see [504 Status code](https://developer.mozilla.org/en/docs/Web/HTTP/Status/504)
> > I would recommend to setup retries to that task, that might help in case of such errors.
> > And I just wondering, is it only failed with 50x status codes? Asked because there is similar issue might happen but the nature is different, see: [slackapi/python-slack-sdk#1165 (comment)](https://github.com/slackapi/python-slack-sdk/issues/1165#issuecomment-1021995427)
> 
> Yes, the respone is same 504 everytime. I can implement retry in the code but on manual retries it fails 100% means everytime. The file is sent and received on slack, but the dag fails with this response

yesterday my understanding was that it fails when the file size is around or over 150 MB as it was working 100% everytime with smaller file sizes < 130 MB and failing around 150 MB files, but then later in the evening it started failing for files even 10 MB files
