### ISSUE TITLE
tasks are marked fail even when the api call is in progress with no error logs

### ISSUE THREAD

**Issue by sktemkar** [apache/airflow#35056]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow tasks are marked failed even though the jobs are running in background through the API call(databricks job)
It checks the status every 30 seconds.
This is also happening for the external task sensor jobs.

The last line of the logs is just the api call and no failure messages logged.

### What you think should happen instead

the api call should either complete or fail and send the status back to airflow task.

### How to reproduce

Airflow2.6 version installed on Azure AKS 1.26.6
Call api (databricks job)

### Operating System

Azure Aks 1.26.6

### Versions of Apache Airflow Providers

2.6.1

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Helm chart deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
Can you attach the code and log snippet in the issue?
