### ISSUE TITLE
Rewrite tag_providers.sh in python

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#35057]
### Body

There is no additional value in keeping the bash scripts. We should rewrite this script in python

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by thakkardharmik** [comment]
@amoghrajesh Can i take a stab on this? Thanks!

**Comment by amoghrajesh** [comment]
Feel free. Assigning to you

**Comment by KesharwaniArpita** [comment]
Can I try to to Solve this issue?

**Comment by poorvirohidekar** [comment]
@amoghrajesh - I am interested in working on this. Can you please assign this to me?

**Comment by amoghrajesh** [comment]
@poorvirohidekar feel free
