### ISSUE TITLE
Task dependency upstream/downstream setting error

### ISSUE THREAD

**Issue by MemphisMeng** [apache/airflow#35062]
### What do you see as an issue?

I'm using Airflow 2.7.2 and following the [documentation](https://airflow.apache.org/docs/apache-airflow/2.7.2/core-concepts/dags.html#task-dependencies) to define the dependency relationship relationship between tasks. I tried the explicit way suggested by the doc but it failed.

```
first_task.set_downstream(second_task, third_task)
third_task.set_upstream(fourth_task)
```

### Solving the problem

It seems it doesn't work if we want to attach multiple tasks downstream to one in a one-line manner. So I suggest currently we should break it down. Or resolve it.

```
first_task.set_downstream(second_task)
first_task.set_downstream(third_task)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shubhamraj-git** [comment]
I am interested in this issue. Could you please assign me?
