### ISSUE TITLE
Grid UI Scrollbar / Cell Click Issue

### ISSUE THREAD

**Issue by jdu** [apache/airflow#35074]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

This is in 2.5.2, we're in the midst of upgrading to to 2.7 but haven't tested thoroughly if this happens there as we don't have the volume of historic runs. 

On the DAG main landing page, if you have a long DAG with multiple sub-groups, and a number of runs recorded, the UI in it's default listing of `25` previous runs, causes the scrollbar for the grid to overlay the right-most column, making it impossible to click on the cells for the right-most DAG run.

![image](https://github.com/apache/airflow/assets/120225/8d33d3a2-630c-4210-88b6-7a52be0e45df)

This is specifically in Firefox.

It's not world-ending, just a bit annoying at times.

### What you think should happen instead

The Grid area should have enough pad to the right of the rightmost column to clear the scrollbar area.

You can get around this by altering the number of runs down to 5 in the dropdown above the grid, this seems to fix the issue in order access the cells.

### How to reproduce

This seems to be the scenario it happens under:

- DAG with long list of tasks, including sub-groups, and moderately long labels
- Show 25 runs on the dag screen

![image](https://github.com/apache/airflow/assets/120225/118f3044-2e18-4678-9ee3-d249cb2c39c7)

### Operating System

Ubuntu 22.04 / macOS

### Versions of Apache Airflow Providers

N/A

### Deployment

Other

### Deployment details

Custom deployment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vchiapaikeo** [comment]
Hey @Adaverse , this is also really annoying for us over at Etsy as well. Please let me know if I can help at all on this!

**Comment by potiuk** [comment]
cc: @bbovenzi @pierrejeambrun for visibility

**Comment by pierrejeambrun** [comment]
I remember fixing exactly that https://github.com/apache/airflow/pull/25554 in `2.3.4`

But since then there has been a lot of updates/improvement to that grid view, maybe css was shuffled a bit and need some fixing again. Some rightly placed right-padding should do the trick.

**Comment by vchiapaikeo** [comment]
Ooo didn't realize this was fixed. Nice! I think it still is okay. Just started breeze on latest and it seems to be fine on both Chrome and Firefox. 🎉 

<img width="559" alt="image" src="https://github.com/apache/airflow/assets/9200263/09b339cf-59a0-4149-89dc-eca8df29db17">

**Comment by vchiapaikeo** [comment]
Ah I think the problem occurs specifically when horizontal scroll is activated - 

<img width="513" alt="image" src="https://github.com/apache/airflow/assets/9200263/7e00850b-6ab5-4d47-bfc5-7c237197c501">

<img width="539" alt="image" src="https://github.com/apache/airflow/assets/9200263/0ffe0d8c-d58b-428f-83aa-0af6150d8b1c">

This doesn't seem to happen in Chrome.

**Comment by vchiapaikeo** [comment]
A bit hacky but here's an attempt: https://github.com/apache/airflow/pull/35346
