### ISSUE TITLE
Cryptographic API Misuse Vulnerability:  Do not use unverified  JWT

### ISSUE THREAD

**Issue by gxx777** [apache/airflow#35126]

**Comment by ephraimbuddy** [comment]
This is not the correct way to report security issues. See https://airflow.apache.org/docs/apache-airflow/2.1.1/security/index.html#reporting-vulnerabilities

**Comment by gxx777** [comment]
> This is not the correct way to report security issues. See https://airflow.apache.org/docs/apache-airflow/2.1.1/security/index.html#reporting-vulnerabilities

Thanks a lot!
