### ISSUE TITLE
Cloud not read served logs

### ISSUE THREAD

**Issue by DevDan99** [apache/airflow#35125]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.0

### Kubernetes Version

Not use

### Helm Chart configuration

Default setting

### Docker Image customizations

No customization

### What happened

When running a DAG, the process throws an error within a few seconds.
Error message: Cloud-served logs not read: Request URL is missing an 'http://' or 'https://' protocol.
I'm not able to identify the problem so I think it's a bug, as a few days ago the Dag was running normally. 
I've already tried reinstalling the airflow image, installing old versions, but the error persists. 
The server that hosts airflow does not have any type of proxy or firewall blocking

Error image:
![image](https://github.com/apache/airflow/assets/104991023/5f8afa84-50ff-4981-bf6f-171dd463df7e)

### What you think should happen instead

The correct execution, which was carried out a few days ago, is after the DAG starts, it makes a request on a website, captures the information and uploads it to my data lake.

### How to reproduce

In my case, as soon as I run any DAG, which makes a request on a website, the error happens.

### Anything else

Graphic Image: 
![image](https://github.com/apache/airflow/assets/104991023/427b4fe3-5208-4d21-980e-f9039950909f)

My code:
```python
from airflow import DAG #lib da Dag no airflow
from datetime import datetime #lib para obter data e hora
from airflow.operators.python import PythonOperator #Lib para cria dag
from minio import Minio #lib para interagir com o Min IO
import pandas as pd #tratamento de dados
import requests #faz requisições HTML
import io # criar o arqui temporario na memoria
import json


def Capta_dolar (): #faz requisição HTTP e obtem o JSON
    url = "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoMoedaPeriodo(moeda=@moeda,dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)?@moeda='USD'&@dataInicial='01-01-2022'&@dataFinalCotacao='12-31-2090'&$top=10000&$format=json&$select=cotacaoCompra,cotacaoVenda,dataHoraCotacao,tipoBoletim"
    response = requests.get(url)
    dados= json.loads(response.content) #abrindo o arquivo que foi pego
    key_select= ['cotacaoCompra','cotacaoVenda','dataHoraCotacao','tipoBoletim'] #cria lista de chaves escolhidas e organizar os dados dos mesmos tipos
    filtro_dados= [{key: D_orig[key] for key in key_select} for D_orig in dados['value']] #para cada dicionario no Json, é criado um novo dicionario, contendo apenas as chaves filtradas
    df= pd.DataFrame(filtro_dados)
    return df

def Transforma_CSV(ti): # Transforma o JSON em CSV
    df= ti.xcom_pull(task_ids='Capta_dolar')
    csv= df.to_csv(index=False)
    return csv

def Upload_Minio(ti):
    csv = ti.xcom_pull(task_ids= 'Transforma_CSV') #pega dados da task aterior
    
    config = {
        "dest_bucket": "processed",
        "minio_endpoint": "10.2.0.28:9000",
        "minio_user": "AirFl",
        "minio_password": "dBCvoOhizLpyvFZFWXA7ceqIo4J7XJYRhyD9y"
    } #cria um dicionairo para salvar as informações de conexao
    
    minio_client = Minio(
        config["minio_endpoint"],
        access_key=config["minio_user"],
        secret_key=config["minio_password"],
        secure=False
    ) # faz a conexão com Minio
    
    bucket_name= 'dadospublicos'
    file_name= 'Cot_dolar.csv'
    csv_bytes= csv.encode('utf-8') #converte str em bytes

    minio_client.put_object(
        bucket_name,
        file_name,
        io.BytesIO(csv_bytes), #passa o Byte em um objeto BytesIO
        len(csv_bytes),
        content_type= 'text/csv'
    ) # realiza o Upload para o Bucket no MinIo

with DAG('Capta_Dolar',start_date= datetime(2023,9,27), schedule_interval='@daily', catchup= False) as dag:

    Capta_dolar= PythonOperator(
        task_id= 'Capta_dolar',
        python_callable= Capta_dolar 
    )

    Transforma_CSV= PythonOperator(
        task_id= 'Transforma_CSV',
        python_callable= Transforma_CSV
    )

    Upload_Minio= PythonOperator(
        task_id= 'Upload_Minio',
        python_callable= Upload_Minio

    )

    Capta_dolar >> Transforma_CSV >> Upload_Minio
```
    
I've already opened a discussion about the problem, but no one responds to me.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
This sounds more like a deployment issue in core, not related to helm-chart. I assume to judge this problem report more details are needed.

If a scheduled task runs into error w/o logs being served, two cases can be the root of the problem, typically related to the deployment if broken in general - best is to double check with one of the example DAGs. Can you please check:
1. Do you see errors in the console of the scheduler or worker indicating a general issue (like DB not accessible, out of memory etc.)?
2. Can you check your log back-end if really not logs are being created or if this is a display problem? If logs are existing in your (however deployed) storage back-end, they might reveal more details.
