### ISSUE TITLE
Support for general OIDC providers or making it clear in document

### ISSUE THREAD

**Issue by rqi14** [apache/airflow#35131]
### Description

I tried hard to configure airflow with authentik OIDC but airflow kept complaining about empty userinfo. There are very limited tutorials online. After reading some source code of authlib, flask-appbuilder and airflow, I found in [airflow/airflow/auth/managers/fab/security_manager/override.py](https://github.com/apache/airflow/blob/ef497bc3412273c3a45f43f40e69c9520c7cc74c/airflow/auth/managers/fab/security_manager/override.py) that only a selection of providers are supported (github twitter linkedin google azure openshift okta keycloak). If the provider name is not within this list, it will always return an empty userinfo at [line 1475](https://github.com/apache/airflow/blob/ef497bc3412273c3a45f43f40e69c9520c7cc74c/airflow/auth/managers/fab/security_manager/override.py#L1475C22-L1475C22). 

For others who try to integrate openid connect, I would recommend read the code in [airflow/airflow/auth/managers/fab/security_manager/override.py starting from line 1398](https://github.com/apache/airflow/blob/ef497bc3412273c3a45f43f40e69c9520c7cc74c/airflow/auth/managers/fab/security_manager/override.py#L1398)

### Use case/motivation

This behaviour should be documented. Otherwise, there should be a way to configure other OIDC providers like other projects that support OIDC in a general manner. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
> This behaviour should be documented. Otherwise, there should be a way to configure other OIDC providers like other projects that support OIDC in a general manner.

We base our authentication on what FAB provides so the documentation - if missing - should likely be added there. But if you feel like this is good, it would be nice to add it.


Ideally someone like you @rqi14  who have experience, need, who had done and tested it is the best to contribute such docs. We heavily rely on our users - especially those who have practical experience - to contribute the documentation (Airflow has 2600 contributors and many of those contributed some documentation like that.

If you wish to give back and contribute - that's cool, I can assign it to you, otherwise it will be open here waiting for somoene who could contribute it base on their experiences with OIDC providers.

**Comment by rqi14** [comment]
> > This behaviour should be documented. Otherwise, there should be a way to configure other OIDC providers like other projects that support OIDC in a general manner.
> 
> We base our authentication on what FAB provides so the documentation - if missing - should likely be added there. But if you feel like this is good, it would be nice to add it.
> 
> Ideally someone like you @rqi14 who have experience, need, who had done and tested it is the best to contribute such docs. We heavily rely on our users - especially those who have practical experience - to contribute the documentation (Airflow has 2600 contributors and many of those contributed some documentation like that.
> 
> If you wish to give back and contribute - that's cool, I can assign it to you, otherwise it will be open here waiting for somoene who could contribute it base on their experiences with OIDC providers.

Thanks for the prompt reply. I'm happy to update the document with the list of supported OIDC providers. Do you mind giving me a hint where the document is located so I can edit it?

**Comment by potiuk** [comment]
> Thanks for the prompt reply. I'm happy to update the document with the list of supported OIDC providers. Do you mind giving me a hint where the document is located so I can edit it?

It's super-easy. Find the right docuemntation in  https://airflow.apache.org/docs/ . In the right bottom of the page you will find a "Suggest a change on this page" with Github logo on it. Click it, and PR will be opened for you at the exact source page that is used to generate the documentation and you will be able to update the documentation even without leaving GitHub UI.
