### ISSUE TITLE
make a trigger_rule for one upstream failed but wait the whole upstream tasks to finish

### ISSUE THREAD

**Issue by salimmoulouel** [apache/airflow#35149]
### Description

currently the one_failed, launch the tasks just after one of the upstream tasks failed, it can be good to be able to force the task wait the whole upstream tasks finish to be launched

### Use case/motivation

move file to error after been used by multiple upstream tasks, currently it can move the file before the whole upstream tasks finish their job

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
> wait the whole upstream tasks finish to be launched

How is that different from `all_done` trigger rule?

**Comment by salimmoulouel** [comment]
Sorry i didn't describe well my problem bacause i was beginner when i wrote the issue
A >> D
B >> D
A and B are BranchOperator, when one of them send skip signal to D,  D is skipped without waiting all the previous task to finish even if it's "all_done" trigger rule, i hope i'm clear now

**Comment by eladkal** [comment]
This use case doesnt make sense to me.
I assume your real case is:
A >> [C, D]
B >> [ C, E]
Where A and B are branch operator.

When A say to follow to D (thus skip C) and B say follow to C (Thus skip E) you end up in a wierd case as its not so clear if C should be wxecuted or not. C upstream tasks (A and B) are both success either way.

Please explain the logic of how you decide if C should be execute or not. I think that this case should not happen to begin with.. having to branch operators pointing to the exact same task is very odd. If you must do so I would use EmptyOperato to decouple the two branches.

**Comment by salimmoulouel** [comment]
https://github.com/apache/airflow/issues/7858
i found an issue which look like mine.
@eladkal  thank you for time spent to understand my problem

**Comment by eladkal** [comment]
Great.
Closing then as no issue
