### ISSUE TITLE
dag_file_processor_timeout fails silently and prevents DAGs from processing correctly

### ISSUE THREAD

**Issue by teu** [apache/airflow#35157]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When dag_file_processor_timeout is exceeded on a dynamic DAG generator (our generates over 80 DAGs) some dags, despite the DAG model objects are being correctly create in code, won't get shown in airflow UI nor scheduled. 
There is no error to be found regarding this in the logs.

### What you think should happen instead

Should be an error in scheduler logs that a timeout had been reached.

### How to reproduce

Airflow version 2.3.3 
Create a dynamic dag that will create dags every 10 seconds with a wait exceeding [dag_file_processor_timeout]. Some dags will get scheduled, some won't.

### Operating System

Ubuntu 22

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@teu Are you able to see whether this is occurring on a more recent Airflow version and, if so, can you share the code and any configuration settings that will enable someone to easily reproduce the issue?

**Comment by boushphong** [comment]
Let me work on this!

**Comment by boushphong** [comment]
> What you think should happen instead
Should be an error in scheduler logs that a timeout had been reached.

I did a quick check. There is error logic logic on branch 2.3.3 and on the main branch. 
https://github.com/apache/airflow/blob/aa1f8d9531eb21bddaa481773e05a78106dc63fa/airflow/dag_processing/manager.py#L1078-L1083
