### ISSUE TITLE
clear_task_instances support all parameters

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#35170]
### Description

`clear_task_instances` function does not support all parameters same REST API endpoint does

### Use case/motivation

I need to clear task instances with “downstream” setting

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> clear_task_instances function does not support all parameters same REST API endpoint does

[airflow.models.taskinstance.clear_task_instances](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/taskinstance/index.html#airflow.models.taskinstance.clear_task_instances) uses for internal of Airflow, including [api/v1/dags/{dag_id}/clearTaskInstances](https://airflow.apache.org/api/v1/dags/{dag_id}/clearTaskInstances) REST API endpoint.

I don't think this function is intended to be used by DAG Authors and it just accidentally become a public

**Comment by eladkal** [comment]
> I don't think this function is intended to be used by DAG Authors and it just accidentally become a public

cc @ephraimbuddy is that right?

**Comment by ephraimbuddy** [comment]
> > I don't think this function is intended to be used by DAG Authors and it just accidentally become a public
> 
> cc @ephraimbuddy is that right?

Yes. The function is used internally. It's not meant to be used by DAG authors. Both UI, CLI, and REST API use it internally and the interface is not expected to match the REST API interface. This issue is not valid
