### ISSUE TITLE
Wild char support when setting a new role for a set of DAGs

### ISSUE THREAD

**Issue by svncsvr** [apache/airflow#35178]
### Description

Airflows Access Control system is quite advanced and it is already helping us a lot in organizing user and team accesses. 
i.e example using the following notation we are able to specify roles on DAG level

`can read on DAG:my_dag_id
`
However we are constantly adding new DAGs and don't want to keep editing the role for the newly added DAGs. Instead, since we already adapted a DAG naming conventions it would have been  so much easier if we could i.e use wildcard chars or regex when specifying the DAG name. ie

`can read on DAG:quality_*
`
We think this feature would be a great addition to already powerful access control implementation.    

### Use case/motivation

We are trying to access finer granularity when working with Access Control on individual DAG level

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is unlikely to happen as we are moving away from the current mode in favour of more flexible system https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-56+Extensible+user+management - where you will be able to write your own Auth Manager and manage your access rules in whatever way you want.

The way how FAB authentication is implemented, using wildcards would bear extremely huge performance hit and we decided against extending that model in favour of completely changing the approach and moving not only authentication but also authorization outside of Airflow and putting that in hands of the deployment managers to implement schemes that will match their organisation.

**Comment by potiuk** [comment]
cc: @vincbeck

**Comment by nathadfield** [comment]
Closing based on @potiuk's commnents.
