### ISSUE TITLE
Relax mandatory requirement for `start_date` when `schedule=None`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#35199]
### Body

Currently `start_date` is mandatory parameter.
For DAGs with `schedule=None` we can relax this requirement as no scheduling calculation needed so the `start_date` parameter isn't used.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by profwacko** [comment]
I'll take a look at this as well!

**Comment by yash-jain221** [comment]
I would like to try it as well!

**Comment by potiuk** [comment]
Fist with good PR wins then ? Srsly - talk to each other and decide who takes it :)

**Comment by yash-jain221** [comment]
Hey, This is my first contribution and I have been working with airflow for
a year.
I thought I could start with this issue as it is a good first issue and I
had faced the exact same problem while using it.
is it fine if I take this then?
