### ISSUE TITLE
Incorrect number of DAGs after update to 2.7.2

### ISSUE THREAD

**Issue by q121212** [apache/airflow#35228]
### Apache Airflow version

2.7.2

### What happened

I was update Airflow from 2.5.x to 2.7.2 in docker and on production rhel server, and in each airflows i have incorrect number of DAGs in the next categories (All, Active, Paused). Everywhere the number is greater than it should be and than it was before update.

### What you think should happen instead

The number of DAGs categorized as All, Active, and Paused should remain consistent before and after the upgrade.

### How to reproduce

1. Have a running instance of Apache Airflow version 2.5.x with a known number of DAGs categorized as All, Active, and Paused.
2. Upgrade the Apache Airflow instance to version 2.7.2 following the official upgrade instructions.
3. Navigate to the Airflow UI and check the number of DAGs listed under the categories All, Active, and Paused.

### Operating System

``` RHEL Server: $ cat /etc/os-release NAME="Red Hat Enterprise Linux" VERSION="8.8 (Ootpa)" ID="rhel" ID_LIKE="fedora" VERSION_ID="8.8" PLATFORM_ID="platform:el8" PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos" HOME_URL="https://www.redhat.com/" DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8" BUG_REPORT_URL="https://bugzilla.redhat.com/"  REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8" REDHAT_BUGZILLA_PRODUCT_VERSION=8.8 REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux" REDHAT_SUPPORT_PRODUCT_VERSION="8.8"   Docker container:  PRETTY\_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION\_ID="12" VERSION="12 (bookworm)" VERSION\_CODENAME=bookworm ID=debian HOME\_URL="[https://www.debian.org/](https://www.debian.org/)" SUPPORT\_URL="[https://www.debian.org/support](https://www.debian.org/support)" BUG\_REPORT\_URL="[https://bugs.debian.org/](https://bugs.debian.org/)" ```

### Deployment

Other

### Deployment details

My Airflow's deployed to Linux RHEL sever and another one in docker container 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/34944
- https://github.com/apache/airflow/issues/34955
