### ISSUE TITLE
Add `JiraNotifier`

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#35261]
### Body

Similar to the [notifiers we already have](https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/notifications.html) we want to add `JiraNotifier` to cut a Jira ticket.
This is very useful to be set with `on_failure_callback`.

You can view other PRs that added similar functionality: [ChimeNotifier](https://github.com/apache/airflow/pull/32222), [SmtpNotifier](https://github.com/apache/airflow/pull/31359)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pubudu91** [comment]
Hi @eladkal, I'd like to look into this.

**Comment by eladkal** [comment]
> Hi @eladkal, I'd like to look into this.

Assigned
