### ISSUE TITLE
Log Links Aren't Clickable in Grid Details Logs Tab

### ISSUE THREAD

**Issue by travis-cook-sfdc** [apache/airflow#35280]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Currently using Airflow 2.6.2 but didn't see any fixes in the changelog for this on the current version, but perhaps my search-fu was bad.

In the grid view, the log tab will not render URLs as links.

This is not the case in the `/log` page which can still be accessed via Grid Details -> More Details -> Logs.

### What you think should happen instead

URLs should be clickable links if they're present in the log pane

### How to reproduce

Run any operator that calls `logger.info("https://www.example.com")`

Notice that in the webserver, this line will not be rendered as clickable link the grid view

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

n/a

### Deployment

Other Docker-based deployment

### Anything else

This happens on all logs

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@travis-cook-sfdc Thanks for logging this.  I have confirmed this to also be the case on v2.7.2.

**Comment by bbovenzi** [comment]
Should be relatively straightforward to detect urls inside of `parseLogs()`.
We're already checking timestamps, log levels, etc.

**Comment by bbovenzi** [comment]
Yes so in the component above it we have a function that returns those parsedLogs. We'd change it from a string to a ReactElement so we can include `<Link>` components mixed in.

**Comment by amoghrajesh** [comment]
Still an issue, self assigning and taking it up

**Comment by amoghrajesh** [comment]
Reopening as it is being discussed here https://github.com/apache/airflow/pull/36829
