### ISSUE TITLE
DAG runs from TriggerDagRunOperator is missing Start Date

### ISSUE THREAD

**Issue by sudiptad2017** [apache/airflow#35281]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Version: 2.1.4
We are trying to trigger a DAG from another DAG in Airflow using the `TriggerDagRunOperator`. Below is the code snippet for the operator. 
```
trigger_dag = TriggerDagRunOperator(
            task_id=task_id,
            trigger_dag_id='{{(task_instance.xcom_pull("distribute_dag_trigger_requests",key="' + task_id + '"))["dag_id"]}}',
            conf='{{(task_instance.xcom_pull("distribute_dag_trigger_requests",key="' + task_id + '"))["conf"]}}'
        )
```
While the target DAG is triggering fine, we noticed that the Start Date attribute is not populated for the dag runs, also in the tree view UI the DAG status pop up shows "Started" and "Duration" as empty and overall status as "Not yet started" even though the DAG execution has been completed. Please see the attachments for reference. Is this the expected behavior or can we do something to get these rectified?

<img width="1728" alt="Screenshot 2023-10-30 at 8 06 04 AM" src="https://github.com/apache/airflow/assets/28659682/89101b63-8bc3-400e-aaac-f1be33135e8e">
<img width="1728" alt="Screenshot 2023-10-30 at 2 26 20 PM copy" src="https://github.com/apache/airflow/assets/28659682/2859a8d6-08af-4acc-aefd-406f01187ef1">

 

### How to reproduce

This issue should occur if the TriggerDagRunOperator is used with the syntax like in the issue description.

### Operating System

PRETTY_NAME="Debian GNU/Linux 10 (buster)" NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian

### Deployment

Other

### Deployment details

We use AWS EKS to run Airflow. The DAG files are deployed to EFS and the volume is then mounted to the EKS cluster.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
Hi @sudiptad2017! Could you try reproducing this issue on a newer version of Airflow? 2.1.4 was released 2 years ago and there has been a tremendous number of changes to the UI since. Most likely this issue won't be picked up unless you can provide details that the start date is unpopulated in the same manner on a more recent version of Airflow.

**Comment by sudiptad2017** [comment]
Hi @josh-fell! Thanks for your response. In that case I would have to find a workaround for now. We have an upgrade planned soon. I will raise another issue if this issue persists after the upgrade.
