### ISSUE TITLE
Feature Request : Are Hourly Hourly Runs in Supported in Airflow?

### ISSUE THREAD

**Issue by r39132** [apache/airflow#353]
We would like to use Airflow for hourly runs. This looks possible by setting `'schedule_interval': timedelta(hours=1),`

I recall trying this and noticed that one of the views (e.g. Tree View) did not support it.

**Comment by r39132** [comment]
Pinging @mistercrunch for his thoughts.

**Comment by mistercrunch** [comment]
Yeah it works, schedule_interval is a DAG param, as in:

```
dag = DAG(dag_id='foo', schedule_interval=timedelta(hours=1))
```

**Comment by r39132** [comment]
I currently need to get our pipeline to hourly. I just switched the DAG to hourly in test and am running into a few issues. For one, `ds` that is passed into my operators is `YYYY-MM-DD` but I need it as an ISO DateTime. How do I get it in 'YYYY-MM-DDTHH:MM:SS"? How do you guys support hourly if, when the dag is specified as having an hourly schedule interval, you don't pass the time in ds?
