### ISSUE TITLE
WORKER_AUTOSCALE should not allow max workers < min workers

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#35332]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

[This was reported for Airflow 2.5.3](https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1698124263201309), but I suspect the behavior is still the same as I don't see any related issues/PRs.

The [WORKER_CONCURRENCY configuration is rather counterintuitive](https://github.com/apache/airflow/pull/4609); the configuration is specified by `max workers, min workers`. This can lead users to specify a maximum number of workers that is less than the minimum number of workers. I'm not entirely sure what happens when this is specified, but I don't believe it behaves normally.

### What you think should happen instead

An exception should be raised if a user attempts to specify a maximum number of workers less than the minimum number of workers.

### How to reproduce

Set `AIRFLOW__CELERY__WORKER_AUTOSCALE=1, 3`, and I suspect only 1 node will ever exist.

https://airflow.apache.org/docs/apache-airflow-providers-celery/stable/configurations-ref.html#worker-autoscale

### Operating System

n/a

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@RNHTTR can you raise a PR for it?

**Comment by RNHTTR** [comment]
Sure -- might take me ~1 week or so

**Comment by Bowrna** [comment]
Could i pick up this issue if it's still pending @RNHTTR ?

**Comment by RNHTTR** [comment]
Go for it! Thanks!

**Comment by Bowrna** [comment]
@RNHTTR However we are going to configure the worker_autoscale, be it (max_concurrency, min_concurrency) or (min_concurrency, max_concurrency) or (single_concurrency_val), celery is taking care of that part in the below way.

https://github.com/celery/celery/blob/be61f8f311b3cdc08c7957cf5b9df9a808a25686/celery/bin/worker.py#L75-L99

class Autoscale(ParamType):
    """Autoscaling parameter."""


    name = "<min workers>, <max workers>"


    def convert(self, value, param, ctx):
        value = value.split(',')


        if len(value) > 2:
            self.fail("Expected two comma separated integers or one integer."
                      f"Got {len(value)} instead.")


        if len(value) == 1:
            try:
                value = (int(value[0]), 0)
            except ValueError:
                self.fail(f"Expected an integer. Got {value} instead.")


        try:
            return tuple(reversed(sorted(map(int, value))))
        except ValueError:
            self.fail("Expected two comma separated integers."
                      f"Got {value.join(',')} instead.")



The above sorted reversed tuple part takes care of sorting it and giving the config

For example, I have configured in airflow.cfg with param as worker_autoscale as 2, 16. But when starting the celery it is right set as min concurrency as 2 and max as 16

<img width="834" alt="Screenshot 2024-01-04 at 4 02 12 PM" src="https://github.com/apache/airflow/assets/10162465/21a1c6f9-bfee-4a8b-9d39-4b4f9c6d7573">
<img width="834" alt="Screenshot 2024-01-04 at 4 02 22 PM" src="https://github.com/apache/airflow/assets/10162465/5420ad0f-3b9c-4fd9-a0e3-1c9477db2f9e">

Do you think it is still valid to handle this issue? Please let me know

**Comment by Bowrna** [comment]
@RNHTTR @eladkal @Taragolis could you give me update about the above comment?

**Comment by RNHTTR** [comment]
Interesting... so this config works in either direction? For example `2,16` works exactly the same as `16,2`? If so, it might make sense to update the docs accordingly.

**Comment by Bowrna** [comment]
yes it works the same way for both config. yeah, let me update the docs

**Comment by Bowrna** [comment]
@RNHTTR shall we close this issue after I fix the documentation?
