### ISSUE TITLE
Would it be possible to add 'name' to the list of template fields for EmrServerlessStartJobOperator?

### ISSUE THREAD

**Issue by kostiantyn-lab** [apache/airflow#35341]
### Description

We have a use case where we would like to run a job runs in EMR Serverless where the job name should contain the start date.
For example: `name="[{{ ds }}] testing"`.

The solution presented in [31711](https://github.com/apache/airflow/issues/31711) does not work, because command
[self.name = name or self.config.pop("name", f"emr_serverless_job_airflow_{uuid4()}")](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/emr.py#L1229) 
removes the `name` parameter from the `config` when initializing the `EmrServerlessStartJobOperator` operator

### Related issues

https://github.com/apache/airflow/issues/31711

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @dacort

**Comment by sseung00921** [comment]
Hello! I would like to pick up this issue. @Taragolis

**Comment by sseung00921** [comment]
@Taragolis Thanks a lot for your kind comment and hint. All right! I will start.

**Comment by dacort** [comment]
Thanks for picking this up @sseung00921 !
