### ISSUE TITLE
Airflow Scheduler with Kubernetes Executor has errors in logs and stuck slots with no running tasks

### ISSUE THREAD

**Issue by crabio** [apache/airflow#35354]
### Apache Airflow version

2.7.2

### What happened

1. Airflow Scheduler has periodic errors:
```log
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 111, in run
    self.resource_version = self._run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 167, in _run
    for event in self._pod_events(kube_client=kube_client, query_kwargs=kwargs):
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 182, in stream
    raise client.rest.ApiException(
kubernetes.client.exceptions.ApiException: (410)
```

2. Scheduler at start has a lot of empty slots, what we see in it's metrics (airflow_executor_running_tasks, airflow_executor_open_slots). But after some time and these errors - it has no empty slots and no tasks are scheduled. All stuck in the queued state.

After some analyze it seems confusing that in [kubernetes provider v7.8.0](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/_modules/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.html) it has code to process it:
```
except ApiException as e:
            if e.status == 410:  # Resource version is too old
                if self.namespace == ALL_NAMESPACES:
                    pods = kube_client.list_pod_for_all_namespaces(watch=False)
                else:
                    pods = kube_client.list_namespaced_pod(namespace=self.namespace, watch=False)
                resource_version = pods.metadata.resource_version
                query_kwargs["resource_version"] = resource_version
                return self._pod_events(kube_client=kube_client, query_kwargs=query_kwargs)
            else:
                raise
```

But not clear, why we still have an error.
Also I saw that this error was a lot of times in other versions of Airflow.

### How to reproduce

1. Create docker of Airflow with these libraries:
```
apache-airflow == 2.7.2
dbt-core == 1.6.6
dbt-snowflake == 1.6.4
apache-airflow-providers-snowflake
apache-airflow[statsd]
facebook-business == 16.0.2
google-ads == 21.1.0
twitter-ads == 11.0.0
acryl-datahub-airflow-plugin
acryl-datahub[dbt]
checksumdir
filelock
openpyxl
cronsim
apache-airflow-providers-cncf-kubernetes==7.8.0
kubernetes
```

2. Configure it via Community Helm chart with Kubernetes Executor
3. Add more than 50 tasks in 2-3 DAGs

### Operating System

Docker based on apache/airflow:2.7.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

apache-airflow-providers-cncf-kubernetes==7.8.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by crabio** [comment]
Also we figured out that some time tasks failed without any reason and without retries.

```log
[[34m2023-11-02T03:13:05.686+0000[0m] {[34mtaskinstance.py:[0m1441} WARNING[0m - cannot record scheduled_duration for task AAA because previous state change time has not been saved[0m
[[34m2023-11-02T03:13:05.686+0000[0m] {[34mbase_executor.py:[0m144} INFO[0m - Adding to queue: ['airflow', 'tasks', 'run', 'AAA', 'AAA', 'scheduled__2023-11-02T02:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/dags/AAA.py'][0m
[[34m2023-11-02T03:13:05.686+0000[0m] {[34mscheduler_job_runner.py:[0m636} INFO[0m - Sending TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue default[0m
[[34m2023-11-02T03:13:05.691+0000[0m] {[34mkubernetes_executor.py:[0m312} INFO[0m - Add task TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1) with command ['airflow', 'tasks', 'run', 'AAA', 'AAA', 'scheduled__2023-11-02T02:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/dags/AAA.py'][0m
[[34m2023-11-02T03:13:05.839+0000[0m] {[34mkubernetes_executor_utils.py:[0m396} INFO[0m - Creating kubernetes pod for job is TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1), with pod name AAA-783qadx4, annotations: <omitted>[0m
[[34m2023-11-02T03:13:06.120+0000[0m] {[34mscheduler_job_runner.py:[0m686} INFO[0m - Received executor event with state queued for task instance TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1)[0m
[[34m2023-11-02T03:14:23.708+0000[0m] {[34mkubernetes_executor.py:[0m356} INFO[0m - Changing state of (TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1), <TaskInstanceState.FAILED: 'failed'>, 'AAA-783qadx4', '520667263') to failed[0m
[[34m2023-11-02T03:14:23.715+0000[0m] {[34mkubernetes_executor.py:[0m441} INFO[0m - Deleted pod: TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1) in namespace BBB[0m
[[34m2023-11-02T03:14:23.725+0000[0m] {[34mscheduler_job_runner.py:[0m686} INFO[0m - Received executor event with state failed for task instance TaskInstanceKey(dag_id='AAA', task_id='AAA', run_id='scheduled__2023-11-02T02:00:00+00:00', try_number=1, map_index=-1)[0m
[[34m2023-11-02T03:14:23.787+0000[0m] {[34mscheduler_job_runner.py:[0m723} INFO[0m - TaskInstance Finished: dag_id=AAA, task_id=AAA, run_id=scheduled__2023-11-02T02:00:00+00:00, map_index=-1, run_start_date=None, run_end_date=None, run_duration=None, state=queued, executor_state=failed, try_number=1, max_tries=0, job_id=None, pool=pool, queue=default, priority_weight=1, operator=CustomOperator, queued_dttm=2023-11-02 03:13:05.681227+00:00, queued_by_job_id=166781, pid=None[0m
```

But in next run this task succeed.

**Comment by jens-scheffler-bosch** [comment]
Your descriptions are a bit vague but I can say that the scheduler does not create empty slots in advance with KubernetesExecutor. For each task being executed, one POD is launched by the scheduler.
If the scheduler received an HTTP 410 error I feel something is broken in your K8s setup or POD template. Can you check for the PODs started if they fail or do they publish specific events in K8s?

**Comment by crabio** [comment]
In my case I see that Airflow Scheduler after some time not queuing tasks. But we have empty slots in pool and all components are running.

No pods are spawned. All tasks are failed or skipped without attempts.

After restart Airflow Scheduling pods - all working fine for some time.

We have this only on env with a 200+ DAGs.

**Comment by crabio** [comment]
Maybe it is same issue:

Some times tasks is running well after Scheduling restart. But random task can fail without any logs or attempts.
If I clear it state via UI - task processes correctly.

This thing started happening after switch from Celery to KubernetesExecutor

**Comment by jens-scheffler-bosch** [comment]
This rather sounds like troubleshooting.
I have never used KubernetesExecutor myself, so unfortunately I have not further experience and would assume that Scheduler might contain errors in the log. I assume you have checked the Scheduler logs?
Converting to a discussion for troubleshooting.
