### ISSUE TITLE
Official Airflow Helm Chart Adding EmptyDir Sizes and Basic Probes to all Containers to Values File

### ISSUE THREAD

**Issue by ahipp13** [apache/airflow#35353]
### Description

What I am requesting here is some changes to the Official Airflow Helm chart. What I am requesting is the addition in the values file to be able to edit the size limit on all the EmptyDirs that are expressed in the deployment files (i.e. like in the scheduler-deployment.yaml, etc.). Also I am requesting the ability to be able to add probes to ALL containers within the values file. 

### Use case/motivation

Since I am deploying to a Kubernetes cluster owned by a different team, they have certain requirements for deploying a pod. 2 of these requirements are:
1) All Empty Dirs need a size limit and 
2) all containers deployed need liveness and readiness probes

Currently what I have to do is manually add all this in, which is a pain when I want to upgrade to your latest helm chart. It would be awesome if a global liveness and readiness probes option could be added to the values file like the securityContext, or at least just options for probes in every container created. Same with the Empty Dirs. I may be the only use case for this so it might not be worth it, but putting it out there in case anybody else is in a similar situation!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Regarding 1)
Are you using custom `volume` and `volumeMount` definitions or which deployments are you referring to?

Regarding 2)
Liveness and readiness probes are added for most of the containers as I remember, at least for webserver, scheduler, worker and triggerer. Can you tell us, which POD/deployment a liveness+readiness probe is missing? Or are the ones generated today not sufficient for your K8s policies? I feel the gap is not too large.

Note in general: Airflow is an OpenSource project, you can kindly request here and maybe somebody as volunteer might be contributing this. If you have a concrete demand or gap, especially in helm it is also very common to contribute a PR to extend or fix a problem. If you are bothered by manual adjustments, then this might be good rather than waiting that somebody fixes it. What also is used sometimes is the tool "helmfile" on top of helm if you want to regularly patch or extend deployments if you miss anything.

**Comment by ahipp13** [comment]
@jens-scheffler-bosch  thank you for responding! For 1, if you take a look at the scheduler-deployment.yaml file: 
![image](https://github.com/apache/airflow/assets/118911990/fe01993d-979f-4817-8afb-6a96521a88d3)
If I leave this as it is, I cannot deploy because it does not have a size limit, so I have to add:
![image](https://github.com/apache/airflow/assets/118911990/519fa19f-0f18-4bac-9831-fa0a6e2965e5)

Also for 2, these are where I have to add probes:
pod-template-file.kubernetes-helm-yaml, liveness and readiness
git sync container definition in the _helpers.yaml file, liveness and readiness
create-user-job.yaml, liveness and readiness
migrate-database-job.yaml, liveness and readiness
scheduler-deployment.yaml, readiness
triggerer-deployment.yaml, readiness

I have never made a PR before, is there a document to describe the process? If I can get some time I can try and leave one. Also, I will look into helmfile as well. Thank you so much!

**Comment by jens-scheffler-bosch** [comment]
For contribution the process is well defined in https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst - take a look, it will not be hard. I also started like this.

Regarding (1):
I don't know the helm structure in detail but could it be possible to pass "EmptyDir" as storage back-end volume and mark it pseudo stateful with this? Then using this potentially is it possible to inject limits?

Regarding (2):
- A couple of PODs/deployments you mention like migration are only "one off" if you deploy. They finish after "job done". I would say it is hard adding a liveness there as it is not a classic service. Same like in "Create user" - this only creates the first Admin user on initial deployment. What do you patch-in locally? Just any kind of dummy?
- Scheduler and Triggerer as well do not define a real service. Readiness is made for services so you know when to route requests to it. This would also require a kind of "dummy".

In total your policies seem to be a kind of strict. Are you sure you can not relax them with your admins? I mean adding a set of dummies just to have a dummy readiness/liveness does not seem to be really a good idea.

**Comment by shohamy7** [comment]
Hi! @ahipp13 
I saw your issue, and took a look in the current helm chart (1.12.0-dev) and it looks that the first proposal of supporting extra configuration such as `sizeLimit` when using `emptyDir` is already implemented, so I guess it will be available in the next release.
Regard to your second proposal, I agree with @jscheffl that we should not add liveness and readiness probe "just to add" them. As @jscheffl said, it seems like those components don't have probes for a reason.
It feels odd to add "dummy" probes for no reason and can make the chart more complex with no actual benefit.

**Comment by ahipp13** [comment]
@shohamy7 That's great! I think we will be upgrading to that helm chart in February so that will be good.

As far as the probes, that does make sense to me. Now I wish I could convince the admins that own the cluster that, but unfortunately I cannot. So will probably just have to keep putting probes in! Am going to close this. Thanks all!
