### ISSUE TITLE
Numeric values in DAG details are incorrectly rendered as timestamps

### ISSUE THREAD

**Issue by Gollum999** [apache/airflow#35414]
### Apache Airflow version

2.7.2

### What happened

On the "Details" tab on a DAGs "Grid" page, all numeric DAG attributes are rendered as timestamps instead of numbers.  For example:

![image](https://github.com/apache/airflow/assets/7269927/9a99ccab-2d20-4a57-9fa8-63447e14444b)

I have noticed this behavior with the following fields, though there may be more:
* Max active runs
* Max active tasks
* Concurrency

### What you think should happen instead

Numeric fields should be rendered as numbers.

### How to reproduce

Go to any DAG's Grid page.  Don't select a DAG Run or Task Instance.  Click the Details tab if it is not already selected.

### Operating System

CentOS Stream 8

### Versions of Apache Airflow Providers

N/A

### Deployment

Other

### Deployment details

Standalone + self-hosted

### Anything else

I think the bug is [here](https://github.com/apache/airflow/blob/0a257afd031289062c76e7b77678337e88e10b93/airflow/www/static/js/dag/details/Dag.tsx#L133):
```
  // parse value for each key if date or not
  const parseStringData = (value: string) =>
    Number.isNaN(Date.parse(value)) ? value : <Time dateTime={value} />;
```
`Date.parse(1)` returns a number that is not NaN.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Can you tell us a bit more about your setup and browser? I did a regression on 2.7.2 by using `docker run -it -p 38080:8080  apache/airflow:2.7.2-python3.8 bash` and in there called `airflow db reset` and then `AIRFLOW__CORE__LOAD_EXAMPLES=True airflow standalone`, started DAG `example_python_operator` and took a look to the GRID view. In my (Firefox) the numbers are shown correct:
![image](https://github.com/apache/airflow/assets/95105677/cf2cb6fe-44ce-4d7d-8e8d-70054f411d27)

Also tested with Cromium browser.

I need to admit, that the tested DAG does not define specific values but uses the fallback defaults. Is your case with a specific configuration in `max active runs` or `max active tasks`?

**Comment by potiuk** [comment]
You have forgotten to provide details about the DB you use @Gollum999 - but my guess is that your DB is causing the problem you see. probably it's something that is not exactly what Airflow standard requirements are.

**Comment by potiuk** [comment]
Converting into discussion until this is clarified and mayb more details provided.
