### ISSUE TITLE
Visual bug - the default pod template is always rendered in K8s Pod Spec 

### ISSUE THREAD

**Issue by ampx-mg** [apache/airflow#35476]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I am using Airflow 2.7.1, official helm chart deployment on EKS 1.23, using KubernetesExecutor and git sync.

I am experimenting with multiple pod templates for my deployment and managed to change the template per task as described in https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#example-pod-templates. Everything works as expected, except the K8s Pod Spec never shows the pod template that was used to override the default one. The default template under
```
config:
  kubernetes_executor:
    pod_template_file: /opt/airflow/my_templates/default_template.yaml
```
gets rendered everytime regardless if it was used or not.

### What you think should happen instead

The pod template that was used to override the default one should get rendered.

### How to reproduce

Deploy airflow using the official helm chart and add 2 different pod templates as extra volumes to scheduler. Have one of them as the default one under
```
config:
  kubernetes_executor:
    pod_template_file:
```
used the other one as override https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#pod-template-file. Then check the logs of a task which you used the overriding template for. See k8s Pod Spec and the default one should be rendered instead of the correct one

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

```
apache-airflow                           2.7.1
apache-airflow-providers-amazon          8.6.0
apache-airflow-providers-celery          3.3.3
apache-airflow-providers-cncf-kubernetes 7.5.0
apache-airflow-providers-common-sql      1.7.1
apache-airflow-providers-daskexecutor    1.0.1
apache-airflow-providers-docker          3.7.4
apache-airflow-providers-elasticsearch   5.0.1
apache-airflow-providers-ftp             3.5.1
apache-airflow-providers-google          10.7.0
apache-airflow-providers-grpc            3.2.2
apache-airflow-providers-hashicorp       3.4.2
apache-airflow-providers-http            4.5.1
apache-airflow-providers-imap            3.3.1
apache-airflow-providers-microsoft-azure 6.3.0
apache-airflow-providers-mysql           5.3.0
apache-airflow-providers-odbc            4.0.0
apache-airflow-providers-openlineage     1.0.2
apache-airflow-providers-postgres        5.6.0
apache-airflow-providers-redis           3.3.1
apache-airflow-providers-sendgrid        3.2.2
apache-airflow-providers-sftp            4.6.0
apache-airflow-providers-slack           8.0.0
apache-airflow-providers-snowflake       5.0.0
apache-airflow-providers-sqlite          3.4.3
apache-airflow-providers-ssh             3.7.2

```

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Kubernetes 1.23

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I don't think this is a bug; I had a similar issue in the past. When you provide `config.kubernetes_executor.pod_template_file` to the chart, it will add it to the `config` configmap, then mount it to the different services:
https://github.com/apache/airflow/blob/dc74d3327e6aed105b7aa7f08a79ee6341543747/chart/templates/scheduler/scheduler-deployment.yaml#L226-L229

If your pod template doesn't have the same volume mount, it will think that the default template is used. So, the solution is to add the same block to your pod template. If you have a good solution to inject the provided pod template and add this block automatically by the chart, you can open a PR.

I will close the issue as not planned.
