### ISSUE TITLE
ECS Executor - Supporting Capacity Providers

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#35489]
### Description

From feedback [here](https://github.com/apache/airflow/pull/34381#issuecomment-1796224734):

The ECS Executor does not currently support Capacity Providers. It currently requires that users specify a [LaunchType](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-launchType), and if you're specifying a LaunchType then you cannot specify a Capacity Provider, they are mutually exclusive.

Using Capacity Providers can be essential for organizations that use EC2-hosted ECS Clusters. Capacity Providers are very cost efficient since you can use them to dynamically scale your EC2 instances based on demand.

### Related issues

#34381

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ferruzzi** [comment]
Taking a look at this one now.

**Comment by ferruzzi** [comment]
@o-nikolas @mshober First big decision.   According to the run_task API docs:

```If a capacityProviderStrategy is specified, the launchType parameter must be omitted. If no capacityProviderStrategy or launchType is specified, the defaultCapacityProviderStrategy for the cluster is used.```

Currently the executor defaults to a FARGATE launchtype is nothing is provided.  We are still "experimental" so we CAN change that without notice or deprecation.  Should we adjust and adopt the API's default?   I think it makes sense to follow their lead here, but it's a digression from our current behavior so I wanted to run it by you.

**Comment by o-nikolas** [comment]
> > we could do a describe to see if there is a default capacity provider strategy set and use that of course
> 
> I think I like that.
> 
> Proposal:
> 
> ```
> If both are provided, fail early with an exception
> If only one is provided, use it
> If none are provided:
>   - describe the cluster and see if there is a default CP to fall back on
>       - if yes, provide nothing to the API and let it default there
>       - if no, provide the FARGATE launch type.
> ```

Looks good to me!
