### ISSUE TITLE
Requests/limits in custom-values.yaml ignored

### ISSUE THREAD

**Issue by dabukster** [apache/airflow#35497]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

8.8.0

### Kubernetes Version

1.25.11

### What happened

I want to install Airflow on a kubernetes cluster. Background, the cluster is provided by our department, so I can't change anything about the settings.

When I run `helm install ... --values custom-values.yaml ...` I get for all components the same error message (cf. below), even though I tried to add `requests/limits` entries to the `resources` sections and `runAsNonRoot` in `securityContext` sections  in a `custom-values.yaml`.  But it seems these values are ignored.

**Question:** How can I provide these values or how can I adjust the configuration to get installation running?

```
admission webhook "validate.kyverno.svc-fail" denied the request:

policy Deployment/i8l-dev/airflow-cluster-web for resource violations: ** the same for scheduler, postgres. etc.**

limit-pod-resources:
  autogen-limit-pod-resources: 'validation error: CPU and memory resource requests
    and limits have an upper limit of 10800 RAM and 3586 millicores. rule autogen-limit-pod-resources
    failed at path /spec/template/spec/initContainers/0/resources/limits/'
require-run-as-nonroot:
  autogen-run-as-non-root: 'validation error: Running as root is not allowed. Either
    the field spec.securityContext.runAsNonRoot must be set to `true`, or the fields
    spec.containers[*].securityContext.runAsNonRoot, spec.initContainers[*].securityContext.runAsNonRoot,
    and spec.ephemeralContainers[*].securityContext.runAsNonRoot must be set to `true`.
    rule autogen-run-as-non-root[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/
    rule autogen-run-as-non-root[1] failed at path /spec/template/spec/initContainers/0/securityContext/runAsNonRoot/'

```

Comment: The same issue was also raised for the community helm chart, but got never addressed as well

### What you think should happen instead

The helm chart should be installed

### How to reproduce

Install on a kubernetes cluster with kyverno in place that enforces the restrictions returned by the error messages. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ylnsnv** [comment]
Can you please provide us with the `custom-values.yaml` you're using? Or at least, what you think is, the relevant part out of it?

**Comment by dabukster** [comment]
Hi,

I've attacht the yaml as txt. But I'd say nothing special.

[custom-values_yaml.txt](https://github.com/apache/airflow/files/13301880/custom-values_yaml.txt)
