### ISSUE TITLE
Document precedence of `full_pod_spec` on `KubernetesPodOperator`

### ISSUE THREAD

**Issue by ketozhang** [apache/airflow#35509]
### What do you see as an issue?

`full_pod_spec` (see [this answer](https://github.com/apache/airflow/discussions/35425#discussioncomment-7496939)) overrides `pod_template` but it itself is a template to be overriden by the other arguments later (e.g., `image`). This is not very clear from either its name or current documentation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ketozhang** [comment]
Related discussion 
https://github.com/apache/airflow/discussions/35425

**Comment by ketozhang** [comment]
From https://github.com/apache/airflow/discussions/35425

**Comment by amoghrajesh** [comment]
@ketozhang do you want to work on this?
