### ISSUE TITLE
Airflow use more swap of ubuntu

### ISSUE THREAD

**Issue by ThuanDoHung** [apache/airflow#35501]
### Apache Airflow version

2.7.3

### What happened

From Airflow 2.7.2, my server warning (High swap space usage (less than 50% free)). This my server use airflow 2.6.x before not warning.

My Server:
OS: Ubuntu 22.04.3 LTS
AIRFLOW: 2.7.2 (upgrade from 2.6.x)
RAM: 8GB (now more 3Gb Free)
SWAP: 4GB (Use more 1.9GB) (if use Ariflow 2.6.x, swap ~= 0GB)

### How to reproduce

From Airflow 2.6 i upgrade 2.7.2, after upgrade about 2-3 days, my server warning High swap space usage (less than 50% free). I try reboot server but 2-3 days warning again 

### Operating System

Ubuntu Server 22.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow[celery,cgroups,dask,statsd,virtualenv,redis]==2.7.3

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ThuanDoHung** [comment]
Status of server:
![image](https://github.com/apache/airflow/assets/95118800/03f20ea7-08e0-4801-bde7-21f527415e86)

And Zabbix Warning:
![image](https://github.com/apache/airflow/assets/95118800/e23b9b3e-b047-41fc-994a-4c6217b9d663)

**Comment by potiuk** [comment]
likely related to https://github.com/apache/airflow/discussions/32856
https://github.com/apache/airflow/discussions/24694

Can you pleae use https://github.com/bloomberg/memray and share/ dump the memory usage of your airflow after the memory used grows ? 

You will ifnd instructions on how to use memray there.

Without it, it is impossible to diagnose the issue - it's likely related to some configuration you have so without more details it is impossible to act on.
