### ISSUE TITLE
Create an `OpsgenieNotifier`

### ISSUE THREAD

**Issue by Eric-Mendes** [apache/airflow#35516]
### Description

Create a notifier for provider opsgenie. It should be the same as `OpsgenieCreateAlertOperator`.

### Use case/motivation

Given that now notifiers exist I believe the `OpsgenieCreateAlertOperator` is better off as a notifier.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
@Eric-Mendes I've assigned this to you, since you marked that you will want to submit a PR. If you don't wan't to work on this issue, just let me know.

**Comment by Eric-Mendes** [comment]
@Taragolis I have the PR ready, I'm just struggling to write tests and test it. Do you have any tips?

**Comment by Taragolis** [comment]
Me personal approach would be:
1. Copy test from one of the existed notifier
2. Make changes: e.g. some other mocks required, but I assume that mocks would be almost the same as in Operator: https://github.com/apache/airflow/blob/main/airflow/providers/opsgenie/operators/opsgenie.py

You could also have a look recommendation in recent PR: https://github.com/apache/airflow/pull/35397

**Comment by Eric-Mendes** [comment]
And how do I run it, @Taragolis? Sorry if it's a dumb question, I'm sort of new at this.
I've been trying to do `pytest test_opsgenie.py` and been getting
```bash
ImportError while loading conftest 'airflow/tests/conftest.py'.
tests/conftest.py:31: in <module>
    import time_machine
E   ModuleNotFoundError: No module named 'time_machine'
```

**Comment by utkarsharma2** [comment]
@Eric-Mendes We already have a provider for Apprise, and Apprise support sending notifications to Opsgenie --   https://github.com/caronc/apprise#productivity-based-notifications

**Comment by Taragolis** [comment]
@Eric-Mendes I think you don't have install `time-machine` into the [local virtual environment](https://github.com/apache/airflow/blob/main/LOCAL_VIRTUALENV.rst) 

You also could run tests inside of breeze shell

```console
❯ breeze shell

root@9e497aa0674f:/opt/airflow# pytest tests/providers/amazon/aws/operators/test_s3.py
```

There is also other options available listed in [TESTING.rst](https://github.com/apache/airflow/blob/main/TESTING.rst) but I assume configure local virtual env or breeze would be enough

**Comment by Eric-Mendes** [comment]
Tested it and opened the PR @Taragolis. Thanks for the guidance.

**Comment by Eric-Mendes** [comment]
@utkarsharma2 I didn't know about Apprise, but it seems nice. I'll probably end up using it, but since PagerDuty has its own notifier I still feel like this is a cohesive feature to have.
