### ISSUE TITLE
"Celery command failed", but "Marking task as SUCCESS"

### ISSUE THREAD

**Issue by EinavDanielDX** [apache/airflow#35610]
### Apache Airflow version

2.7.3

### What happened

I've executed a task, on flower and worker log I see this error:
```
airflow.exceptions.AirflowException: Celery command failed on host: my-worker.svc.cluster.local with celery_task_id 5f4b68d0-cb6d-405f-924b-17229833c5ae
```

Yet in airflow web UI the task marked as "finished successfully" with the following log:
```
2023-11-13T16:55:32.339+0000 | INFO | 3722 | taskinstance.py:1400 | Marking task as SUCCESS. dag_id=onboarding_DAG, task_id=TASK_X, execution_date=20231113T135707, start_date=20231113T165530, end_date=20231113T165532
2023-11-13T16:55:32.412+0000 | INFO | 3709 | local_task_job_runner.py:228 | Task exited with return code 0
```

The process actually DID its job, yet i cant figure why celery executor logged an error while the task actually runs just fine

### What you think should happen instead

Task run result in celery and web UI should be consistent.

### How to reproduce

.

### Operating System

Debian 11 (bullseye) container, running on EKS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.7.1
apache-airflow-providers-celery==3.3.4
apache-airflow-providers-cncf-kubernetes==7.6.0
apache-airflow-providers-common-sql==1.7.2
apache-airflow-providers-daskexecutor==1.0.1
apache-airflow-providers-docker==3.7.5
apache-airflow-providers-elasticsearch==5.0.2
apache-airflow-providers-ftp==3.5.2
apache-airflow-providers-google==10.9.0
apache-airflow-providers-grpc==3.2.2
apache-airflow-providers-hashicorp==3.4.3
apache-airflow-providers-http==4.5.2
apache-airflow-providers-imap==3.3.2
apache-airflow-providers-microsoft-azure==7.0.0
apache-airflow-providers-mysql==5.3.1
apache-airflow-providers-odbc==4.0.0
apache-airflow-providers-openlineage==1.1.0
apache-airflow-providers-postgres==5.6.1
apache-airflow-providers-redis==3.3.2
apache-airflow-providers-sendgrid==3.2.2
apache-airflow-providers-sftp==4.6.1
apache-airflow-providers-slack==8.1.0
apache-airflow-providers-snowflake==5.0.1
apache-airflow-providers-sqlite==3.4.3
apache-airflow-providers-ssh==3.7.3

### Deployment

Other 3rd-party Helm chart

### Anything else

On a regular basis, to most of the tasks in queue
![image](https://github.com/apache/airflow/assets/97506919/0d8a331f-b7bb-4c6b-84e1-1d31814168af)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you provide reproduce example for this behavior? 
cc @auvipy any idea what may cause this?

**Comment by EinavDanielDX** [comment]
I have update on the matter.
More background regarding the deployment:
We are using airflow with Celery Executor on Kubernetes, in addition, as we don't need the workers up and running all the time we are using Keda for scaling up and down the workers, which means workers are being killed regularly.
Our deployment is configured to allow graceful shutdown for 4 hours ( which is more than enough for any task we run to finish its processing).
We noticed that beside the misalignment between successful jobs and failed celery tasks we have other errors on random tasks, such as 
"Executor reports task instance finished (success) although the task says it's queued. (Info: None) Was the task killed externally?"
or
"Loading metadata failed: {'success': False, 'reason': AirflowException('Task received SIGTERM signal')}"

After further investigation set `AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION: "False"` 

Now our flower looks better
![image](https://github.com/apache/airflow/assets/97506919/7de68d7e-f754-45a1-a7ab-1ad833d4e463)

**Comment by potiuk** [comment]
That's an interesting lead. I will mark it for 2.8.1 and maybe we could guesss what could be the readon. Do you see any logs from the workers indicating that there might be an error when attempting to update database ?

**Comment by raphaelauv** [comment]
with airflow 2.9.1  since we activated the auto-scaling of workers with keda we see the same problem than @EinavDanielDX
