### ISSUE TITLE
Enhance the docs on zombie tasks to elaborate on how they are detected

### ISSUE THREAD

**Issue by pankajkoti** [apache/airflow#35698]
### What do you see as an issue?

The documentation for zombie tasks https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks is a bit abstract at the moment. There is a scope for enhancing the document by explaining how Airflow detects tasks as zombies

### Solving the problem

We can enhance the documentation by translating this query https://github.com/astronomer/airflow/blob/main/airflow/jobs/scheduler_job_runner.py#L1721 to a layman readable text in our documentation.

### Anything else

It might also help to add developer contribution steps to reproduce zombies locally.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
cc: @Lee-W @vatsrahul1001 @phanikumv

**Comment by potiuk** [comment]
God idea. :). Would love to read and review such document - so feel free to ping me when ready for review :)
