### ISSUE TITLE
Add EC2RebootInstanceOperator and EC2HibernateInstanceOperator  to Amazon Provider

### ISSUE THREAD

**Issue by odaneau-astro** [apache/airflow#35703]
### Description

The Amazon Airflow Provider lacks operators for "Reboot Instance" and "Hibernate Instance," two states available in the AWS UI. Achieving feature parity would provide a seamless experience, aligning Airflow with AWS capabilities.

I'd like to see the EC2RebootInstanceOperator and EC2HibernateInstanceOperator added to Amazon Provider.

### Use case/motivation

This enhancement ensures users can manage EC2 instances in Airflow the same way they do in the AWS UI.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add it as PR as well if you will - otherwise marked it as a good-first-issue for someone who would like to pick it up

**Comment by dashton90** [comment]
I'd be happy to take this one. Is it more sensible to add `hibernate` as a parameter to the `EC2StopInstanceOperator`, or create a separate `EC2HibernateInstanceOperator`?
