### ISSUE TITLE
Documentation Operator name diverges from real name

### ISSUE THREAD

**Issue by dsantiago** [apache/airflow#35705]
### What do you see as an issue?

As can be seen in https://github.com/apache/airflow/blob/ce16963e9d69849309aa0a7cf978ed85ab741439/airflow/providers/google/cloud/transfers/mssql_to_gcs.py#L44

The name `MsSqlToGoogleCloudStorageOperator` should be the same as the class `MSSQLToGCSOperator`	

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
I guess this example should be remove in favor of [operator documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/transfer/bigquery_to_mssql.html#howto-operator-bigquerytomssqloperator) which synchronised with System Tests

**Comment by hguercan** [comment]
Can it be assigned to me as my first task please?

**Comment by hguercan** [comment]
https://github.com/apache/airflow/pull/35715

**Comment by dsantiago** [comment]
> I guess this example should be remove in favor of [operator documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/transfer/bigquery_to_mssql.html#howto-operator-bigquerytomssqloperator) which synchronised with System Tests

Just to remember that the Operator mentioned is for the inverse, from MsSql -> BigQuery
