### ISSUE TITLE
Setting a task to run state doesn't do nothing

### ISSUE THREAD

**Issue by alejandrofm** [apache/airflow#35729]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

If I set the task to running here, it goes to the "running" state but does nothing
![image](https://github.com/apache/airflow/assets/19591174/20d1fefd-15a1-4020-8f50-c8561f608e53)

### What you think should happen instead

I think the option should be removed for **tasks**

### How to reproduce

Set a queued task to running state

### Operating System

Airflow 2.7.2 Python3.10 official image

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
I think this setting of state is an administrative "overright" of the original status and can be used in any kind of troubleshooting - but you need to know what you are doing. It is not intended to use it to (re-)launch tasks. It plainly sets the state,

In my job I used all of the other states and on this point I agree - I am not sure how useful it is to set a task to "running". If it is running it should have received this status, it the task is not running and is not started (it will not with this action) then it is never turned to any follow-up state,

I would leave the judgement to others with a bit more legacy on the UI but I assume it would really make sense to remove or print three warnings for the option.
