### ISSUE TITLE
Allow Google Hooks to use AnonymousCredentials 

### ISSUE THREAD

**Issue by jvaesteves** [apache/airflow#35755]
### Description

Currently, all Google operations demands valid credentials to connect with GCP, but when trying to mock Google services using emulators, we are giving the opportunity to redirect all requests to them via environment variables from the SDK, but we can't configure the hooks to not require any credentials in this circumstances.

### Use case/motivation

- Enable easy mocking and testing of Google Cloud Operators by enabling AnonymousCredentials to be used as the Connection option.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
@eladkal Could you please assign me?
