### ISSUE TITLE
Error invalid log folder's name because fault when generating run_id 

### ISSUE THREAD

**Issue by Volcano4bit6** [apache/airflow#35765]
### Apache Airflow version

2.7.3

### What happened

I can't trigger my DAG

### How to reproduce

When I triggered a DAG, I had the following fault:
`ERROR - Failed to execute task [Errno 22] Invalid argument: '/opt/airflow/logs/dag_id=hello_world/run_id=manual__2023-11-20T22:41:50.275085+00:00'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/logs/dag_id=hello_world/run_id=manual__2023-11-20T22:41:50.275085+00:00/task_id=hello_task'`

My OS is Ubuntu 20.04. The name `manual__2023-11-20T22:41:50.275085+00:00` is invalid because the folder's name must not have `:` character. How can I change the `run_id` generation method or can we update the generation method?

### Operating System

Ubuntu 20.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think you are running it on Windows Filesystem that's why it does not work for you . You should change your filesystem to be Linux-based, t won't work otherwise. 

Airflow expliclity only works with POSIX OS and POSIX filesystems. It is a requirement.

**Comment by potiuk** [comment]
In the future, if you ask a question of this kind you should open discussion, not issue.

**Comment by Volcano4bit6** [comment]
Thank you, it's work
