### ISSUE TITLE
dbt Cloud provider to support retry from point of failure

### ISSUE THREAD

**Issue by sdurry** [apache/airflow#35772]
### Description

dbt Cloud offers the possibility to [retry](https://docs.getdbt.com/docs/deploy/retry-jobs) job from point of failure. This feature can be triggered natively within dbt cloud, but there is also a new [endpoint](https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retry%20Failed%20Job) airflow users may want to trigger as part of their orchstration

### Use case/motivation

I image dbt Cloud customers using different patterns in airflow to handle retry today:

-  parse the dbt DAG in Airflow to get the benefit of re-running from the point of failure
- full manual retry by re-starting dbt Cloud Job Task

Supporting this new [endpoint](https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retry%20Failed%20Job) as its own operator will simplify implementing such logic.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
could I try to fix this issue @eladkal ?

**Comment by josh-fell** [comment]
All yours @Bowrna!

**Comment by b-per** [comment]
Hi @Bowrna , is it something you are still looking at?

**Comment by Bowrna** [comment]
hi @b-per let me give it a try this weekend. If I couldn't then I will unassign it from my name.

**Comment by Bowrna** [comment]
hi @b-per please take this issue.. I have bitten more than I can chew and struggling to finish it off.
