### ISSUE TITLE
Airflow DAG Not Starting as Expected on Scheduled Date

### ISSUE THREAD

**Issue by Sovenique** [apache/airflow#35793]
### Apache Airflow version

2.7.3

### What happened

I'm experiencing an issue with scheduling a new DAG in Airflow. I set the start date for the DAG to 2023-11-22 (I did this on 2023-11-21 and this was synced through Git to Airflow), but one day later, the DAG still hasn't started. I'm unsure if this is an expected behavior or if there's a misconfiguration on my part. How can I successfully launch a new DAG with the following parameters?

Settings:
```
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    'start_date': datetime(2023, 11, 22),
    "retries": 5,
    "retry_delay": timedelta(minutes=1),
}

dag = DAG(
    "test_dag",
    schedule_interval="00 00 * * *",
    default_args=default_args,
    description='Test DAG',
    tags=["test"],
)
```
In the Airflow UI, Next Run still shows 2023-11-22, 00:00:00, but Last Run is still empty.

DagModel Debug Information:
```
Attribute                               Value
--------------------------------------   --------------------------------------------
fileloc                                 /opt/airflow/dags/repo/dags/test_dag.py
has_import_errors                       False
has_task_concurrency_limits             False
is_active                               True
is_paused_at_creation                   True
is_subdag                               False
last_expired                            None
last_parsed_time                        2023-11-22 10:34:47.596203+00:00
next_dagrun                             2023-11-22 00:00:00+00:00
next_dagrun_create_after                2023-11-23 00:00:00+00:00
next_dagrun_data_interval               DataInterval(start=DateTime(2023, 11, 22, 0, 0, 0, tzinfo=Timezone('UTC')), end=DateTime(2023, 11, 23, 0, 0, 0, tzinfo=Timezone('UTC')))
parent_dag                              None
pickle_id                               None
processor_subdir                        /opt/airflow/dags/repo/
timetable_description                   At 00:00
timezone                                Timezone('UTC')
```

### What you think should happen instead

Is there something I'm missing in the configuration, or is there a delay expected in the first run of a new DAG? Any insights or suggestions on how to resolve this would be greatly appreciated.

### How to reproduce

Create a test DAG with the settings specified above.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
That is expected behaviour, Airflow will run after the end of the scheduling interval, in your case for logical date (execution date) `2023-11-22 00:00:00+00:00` it will start after `2023-11-22 00:00:00+00:00`

- [Scheduler](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/scheduler.html#scheduler)
- [DAG Runs](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html)
