### ISSUE TITLE
Add path to airflow.cfg in docker-compose.yml

### ISSUE THREAD

**Issue by svvema** [apache/airflow#35812]
### Description

Adding a commented line in compose file like `- ${AIRFLOW_PROJ_DIR:-.}/airflow.cfg:/opt/airflow/airflow.cfg ` would save new users tons of time when customizing the configuration file. Also the current default bind `- ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config` is misleading where file airflow.cfg should be stored in the container.
Another solution is to simply add similar information here https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html

### Use case/motivation

I was setting up email notifications and didn’t understand why SMTP server configuration from airflow.cfg didn’t work

### Related issues

https://github.com/puckel/docker-airflow/issues/338
https://forum.astronomer.io/t/airflow-up-and-running-but-airflow-cfg-file-not-found/1931

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
docker-compose sample is not a production level example. It just exists for simple purpose "Quick run and say 'Whoa! it actually works!'" however configuration for production might be complicated and required to have a knowledge in both Docker and Docker Compose.

However feel free to update/extend information which might help others to solve this one issue

**Comment by Taragolis** [comment]
> Also the current default bind - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config is misleading where file airflow.cfg should be stored in the container.

It might be stored in any place and configured by [AIRFLOW_CONFIG](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#envvar-AIRFLOW_CONFIG) environment variable, but by default it set to `${AIRFLOW_HOME}/airflow.cfg`

**Comment by potiuk** [comment]
Yes @svvema -> if you feel like improving the compose file you are absolutely welcome to. Would you like to contribute back in exchange for getting not only free software but also an example to start with so that you do not have to do it from the scratch?

Shall we assign it to you and will you submit a PR? Does not seem as a difficult task and you seem to know what you want?

Otherwise - we've marked it as good-first-issue and it will wait for someone to pick it up.t

**Comment by dominikhei** [comment]
@potiuk since this still hasn't been solved yet, I have a pull request at hand that would close the issue, is it okay if I create the pr?

**Comment by potiuk** [comment]
> @potiuk since this still hasn't been solved yet, I have a pull request at hand that would close the issue, is it okay if I create the pr?

There is absolutely no need to ask for permission to open a PR. You always can do it .
