### ISSUE TITLE
On the front-end page, the content is not displayed in the Executor Class field

### ISSUE THREAD

**Issue by LengYue12389** [apache/airflow#35847]
### Apache Airflow version

2.7.3

### What happened

Dear developer:
 I am a beneficiary of Airflow, I noticed a slight issue while using Airflow, as shown in the following image
![image](https://github.com/apache/airflow/assets/79817309/14b19f0a-d372-4410-b9d9-9c108d71951a)
The CeleryExecutor would have been displayed here, this issue will not occur in version 2.6

### What you think should happen instead

![image](https://github.com/apache/airflow/assets/79817309/a8bb9d56-1e6a-4541-98a6-308ec1ba09da)
Running on CentOS in version 2.6 can display normally
![image](https://github.com/apache/airflow/assets/79817309/7e633b82-4c7b-4676-9dba-057907c75339)

### How to reproduce

My operating environment is as follows:
operating system: Ubuntu Server 2204 LTS
Python version: 3.10.13
Airflow version: 2.7.3
Redis version: 6.0
PostgreSQL version: 14.1
Version of other components:
apache-airflow-providers-celery          3.4.1
apache-airflow-providers-common-sql      1.7.2
apache-airflow-providers-ftp             3.5.2
apache-airflow-providers-http            4.5.2
apache-airflow-providers-imap            3.3.2
apache-airflow-providers-sqlite          3.4.3

### Operating System

Ubuntu 22.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.4.1
apache-airflow-providers-common-sql==1.7.2
apache-airflow-providers-ftp==3.5.2
apache-airflow-providers-http==4.5.2
apache-airflow-providers-imap==3.3.2
apache-airflow-providers-sqlite==3.4.3

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to work on it

**Comment by thisistorr** [comment]
Hello, I'm Torr, a contributor eager to help resolve issue #35847.
After carefully reviewing the details, I am interested in making a contribution to address this specific issue.
If it's possible, could you please assign this issue to me?
Thank you.
