### ISSUE TITLE
New logs tab is broken for tasks with high retries

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#35889]
### Apache Airflow version

2.7.3

### What happened

One of our users had high number of retries around 600 and the operator was like a sensor that retries on failure till retry limit is reached. The new log page renders the log tab to the bottom making it unusable. In the old page there is still a display of buttons for all retry but scrolling is enabled. To fix this we had to change log from buttons to a drop down where attempt can be selected placing the dropdown before the element to select log level. This is an edge case but we thought to file anyway in case someone is facing this. We are happy to upstream to one of the selected below solutions : 

1. Using dropdown on high number of attempts like after 50 and falling back to buttons. But this is a UX change to use button in one case and dropdown in another that user needs to be educated.
2. Always using dropdown despite low number of attempts with default of latest attempt.

Attaching sample dag code that could lead to this scenario.

Sample scenario : 

![image](https://github.com/apache/airflow/assets/3972343/a46afe26-7b61-4e72-9f83-137b1cedae9c)

### How to reproduce

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.decorators import task
from airflow.models.param import Param
from airflow.operators.empty import EmptyOperator

from datetime import timedelta


with DAG(
    dag_id="retry_ui_issue",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    schedule_interval="@once",
) as dag:

    @task(retries=400, retry_delay=timedelta(seconds=1))
    def fail_always():
        raise Exception("fail")

    fail_always()
```

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We could add logic that if the try number is > 10 we make it a dropdown instead of a series of buttons.

**Comment by tirkarthi** [comment]
Thanks @bbovenzi , I will raise a PR for this since we have this fix internally.
