### ISSUE TITLE
run_as_user task report airflow.exceptions.DagRunNotFound: DagRun for tsy-succ-test with run_id or execution_date of '' not found

### ISSUE THREAD

**Issue by yogaliving** [apache/airflow#35906]
### Description

I am running airflow 2.7.3 in a single machine, airflow is installed in a python virtualenv, the airflow_home is /mnt/bmr/airflow.

```python
#!/usr/bin/python
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from datetime import datetime, timedelta
import subprocess

default_args = {
    'owner': 'test_owner',
    'depends_on_past': False,
    'start_date':datetime(2023,11,13),
    'retries': 0,
    'retry_delay': timedelta(minutes=1),

}
dag = DAG('tsy-succ-test', default_args=default_args, schedule_interval=timedelta(days=1))

t1 = BashOperator(
    task_id='t1',
    bash_command='hdfs dfs -ls /',
    run_as_user='hdfs',
    dag=dag)
```

I use this dag will failed,and log said:
```
airflow.exceptions.DagRunNotFound: DagRun for tsy-succ-test with run_id or execution_date of 'scheduled__2023-11-27T00:00:00+00:00' not found
```
but i can find `scheduled__2023-11-27T00:00:00+00:00` in the mysql
![image](https://github.com/apache/airflow/assets/55875703/5e5328db-1dc7-49bc-9dbb-c41ab076ff2b)

if i use this dag
```python
#!/usr/bin/python
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from datetime import datetime, timedelta
import subprocess

default_args = {
    'owner': 'test_owner',
    'depends_on_past': False,
    'start_date':datetime(2023,11,13),
    'retries': 0,
    'retry_delay': timedelta(minutes=1),

}
dag = DAG('tsy-succ-test', default_args=default_args, schedule_interval=timedelta(days=1))

t1 = BashOperator(
    task_id='t1',
    bash_command='hdfs dfs -ls /',
    dag=dag)`
```
it will succeed.
![image](https://github.com/apache/airflow/assets/55875703/6a847e3e-18e1-4d02-96a6-9a302fffbbfc)
I start airflow with root user

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
From the error report it is hard t judge what the root cause is. The only difference i notice from the changed DAG is that you remove the `run_as_user` attribute?

Please describe more details, how you setup looks like, if Airflow is installed in a venv, which executor? Is the user which should be impersonated is existing?

In general is it not recommended to run Airflow with a root user as privilige, this would impose security risks. Can not find documentation in general but I would prevent running as root if possible.
