### ISSUE TITLE
Adding Support for Yarn queue and other extras in SparkSubmit Operator and Hook

### ISSUE THREAD

**Issue by pateash** [apache/airflow#35911]
### Description

Spark-submit 
--queue thequeue option specifies the YARN queue to which the application should be submitted.

more  - https://spark.apache.org/docs/3.2.0/running-on-yarn.html

### Use case/motivation

The --queue option is particularly useful in a multi-tenant environment where different users or groups have allocated resources in specific YARN queues.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pateash** [comment]
Please assign this to me, this is a quick fix
I will try to complete this by this weekend.

**Comment by hussein-awala** [comment]
@pateash assigned you.

**Comment by pateash** [comment]
Currently it's possible to set this option inside Spark connection, but we should have the ability to override it if needed using operator arguments.
<img width="1123" alt="image" src="https://github.com/apache/airflow/assets/16856802/05db383b-1447-4a67-bc86-23cd4752e37d">

**Comment by eladkal** [comment]
> Currently it's possible to set this option inside Spark connection, but we should have the ability to override it if needed using operator arguments.

So do we have a task to complete here?

**Comment by eladkal** [comment]
We normally allow to override connection extra from the operator level. For example with Snowflake you can set different warehouse than the default one set in the connection.

**Comment by pateash** [comment]
Yes, it's done using args AFAIK,
Let me add an argument to override this.

**Comment by databius** [comment]
I think the update caused the new issue since SparkSubmitOperator accidentally overwrote the Base Operator's parameter.

https://github.com/apache/airflow/blob/main/airflow/providers/apache/spark/operators/spark_submit.py#L76
>     :param queue: The name of the YARN queue to which the application is submitted.
       (will overwrite any yarn queue defined in the connection's extra JSON)

https://github.com/apache/airflow/blob/main/airflow/models/baseoperator.py#L587
>     :param queue: which queue to target when running this job. Not
        all executors implement queue management, the CeleryExecutor
        does support targeting specific queues.

So if you are using CeleryKubernetesExecutor, you cannot decide the Operator run on KubernetesExecutor by setting the `queue` to [kubernetes_queue](https://airflow.apache.org/docs/apache-airflow-providers-celery/stable/configurations-ref.html#kubernetes-queue)

**Comment by djuarezg** [comment]
Since 4.6.0 where this was introduced, onwards, using SparkSubmitOperator is broken for us, as the queue can no longer be taken into account due to this change.
