### ISSUE TITLE
Add an on_skipped_callback

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#35936]
### Description

Add functionality to support an `on_skipped_callback` to execute a callable function when a task is skipped.

### Use case/motivation

Here are a couple potential use cases:

* [Recent StackOverflow question looking for the functionality](https://stackoverflow.com/questions/77565651/airflow-skipped-dag-run-mail-notification)
* [Support for an on_skipped_callback in a separate issue](https://github.com/apache/airflow/issues/30264#issuecomment-1505759049)

Partially fixed by: #36374

### Related issues

#30264 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment]
@RNHTTR I could take this up. Could you assign it to me?

**Comment by RNHTTR** [comment]
Done!
