### ISSUE TITLE
There's no way to pass params to dag.test()

### ISSUE THREAD

**Issue by getaaron** [apache/airflow#35930]
### Description

I'm writing a new dag which takes params and trying out calling `dag.test()` in my unit test. The basic dag could look like:

```python
emotions = ['elated', 'ennui']

@task
def some_task(emotion: str, date: str):
    url = f"http://example.com/do_something/{date}?emotion={emotion}"
    response = requests.post(url)
    if response.status_code != 200:
        raise AirflowException(f"Request failed with status {response.status_code}")

@dag(default_args=default_args,
     schedule=None,
     params={"emotion": Param(None, enum=emotions),
             "date": Param(None, type="string", format="date")})
def process_my_emotion():
    some_task('{{ params.emotion }}', '{{ params.date }}')
```

In my test, I want to call `dag.test()` with an `emotion` and `date` and assert the correct URL is formed. I tried this:

```python
@patch("requests.post")
@freeze_time("2024-01-01")
def test_process_my_emotion(mock_post, manual_dag):
    mock_post.return_value = Mock(status_code=200)
    manual_dag.test(execution_date=datetime(2024, 1, 1),
                    params={'emotion': 'ennui', 'date': '2024-01-01'})

    mock_post.assert_any_call(
        f"http://example.com/do_something/2024-01-01?emotion=ennui"
    )
```

This fails with:

> TypeError: test() got an unexpected keyword argument 'params'

Looking at

https://github.com/apache/airflow/blob/f6962a929b839215613d1b6f99f43511759c1e5b/airflow/models/dag.py#L2769-L2776

I don't see a way to pass params in.

If I'm correct, the feature I'm requesting is a way to pass params in. If I'm incorrect, I'm requesting an improvement to the docs.

### Use case/motivation

I would like to test dags that use params by calling `dag.test()`

### Related issues

I didn't find any.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by keithbentrup** [comment]
@getaaron Try `dag.test(run_conf={"paramA": "valueA", "paramB": "valueB"})`. The [test() docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/dag/index.html#airflow.models.dag.DAG.test) are vague, but it worked for me when I was looking for the solution.

**Comment by RNHTTR** [comment]
@getaaron apologies for the delayed response. It looks like @keithbentrup 's solution ought to work. With that said, Keith's point about [dag.test() docs](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/debug.html#testing-dags-with-dag-test) being is spot on -- updating these docs would be a great idea. Let me know if you'd like some help with that.
