### ISSUE TITLE
Wrong order of parameters in WebUI

### ISSUE THREAD

**Issue by glasen** [apache/airflow#35944]
### Apache Airflow version

2.7.3

### What happened

Please see the provided code and the screenshot:

`with (DAG(
        'sag_pipeline_4_ai',
        default_args=default_args,
        description='KI-Pipeline',
        schedule_interval=None,
        start_date=pendulum.today('UTC').add(),
        tags=['sag'],
        max_active_runs=1,
        params={
            "database": create_list_param(URIServer.get_all_databases(), "Select Database"),
            "collection": create_list_param(["messages", "files_content"], "Select Collection"),
            "server": create_list_param(['mia', 'akira', 'tori'], "Select Server"),
            "epochs_document_embedding": Param(10, type="integer", minimum=3, maximum=30,
                                               title="Epochs for document-embedding"),
            "force_cleaning": Param(False, type="boolean", title="Force cleaning"),
            "build_topic_model": Param(True, type="boolean", title="Build Topic-Model"),
            "rebuild_communication_graph": Param(False, type="boolean", title="Rebuild communication-graph"),
            "purge_persons_communication_graph": Param(True, type="boolean",
                                                       title="Purge persons from communication-graph"),
        }
) as dag):`

![Screenshot](https://github.com/apache/airflow/assets/1146471/a6d1dba9-0a60-4322-8c02-5978ebb82f92)

The ordering of the params in the UI is different from the ordering in the code.

### What you think should happen instead

According to your documentation, the ordering should be like the ordering in the code:

[Use Params to Provide a Trigger UI Form](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html#use-params-to-provide-a-trigger-ui-form)

> Form fields are rendered in the order of definition of params in the DAG.

### How to reproduce

Fresh pip-install of Airflow 2.3.7 on Ubuntu 22.04 with Python 3.10.

### Operating System

Ubuntu 22.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ardada2468** [comment]
Can I start working on this?

**Comment by potiuk** [comment]
sure

**Comment by huruifeng** [comment]
this also happens to me, I am using 2.8.0, the ordering  of the parameters in WebUI is totally different from the ordering in code?
Has this been solved or how can I order my parameters in the WebUI.

**Comment by glasen** [comment]
The problem still exists with version 2.8.1

**Comment by simond** [comment]
I can't seem to replicate this on 2.8.1 - are you able to provide a minimal working example? Your code example is unfinished.
