### ISSUE TITLE
Cannot download packages for 2.7.3

### ISSUE THREAD

**Issue by eugeny-stoyka** [apache/airflow#35953]
### What do you see as an issue?

Hello. Cannot download all packages by **Installing from PyPI** section in **README.md**

`pip install 'apache-airflow[all]==2.7.3' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.10.txt"
`

> ERROR: Cannot install apache-airflow[all]==2.7.3 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     apache-airflow[all] 2.7.3 depends on watchtower~=2.0.1; extra == "all"
>     The user requested (constraint) watchtower==3.0.1

`pip --version`
> pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I just changed **install** into **download**. Do i have any misconception of it?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
All is only a development dependency - you should not use it to download the released version. You need to individually specify all packages you want to install: 

https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html#bundle-extras

> These are extras that install one or more extras as a bundle. Note that these extras should only be used for “development” version of Airflow - i.e. when Airflow is installed from sources. Because of the way how bundle extras are constructed they might not work when airflow is installed from ‘PyPI`.

> If you want to install Airflow from PyPI with “all” extras (which should basically be never needed - you almost never need all extras from Airflow), you need to list explicitly all the non-bundle extras that you want to install.
