### ISSUE TITLE
Native templating modifies types even when no `{{}}` are present

### ISSUE THREAD

**Issue by theis188** [apache/airflow#35987]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Using Airflow 2.6.3, the `render_template_as_native_obj` option, templated fields can change type, even if there is no `{{}}` in the field.

If you specify a string in a templated field which can evaluate to an int, list or some other non-string, it will change type if `render_template_as_native_obj` is set to True.

For example, if you set a templated field equal to = `["my_package_version", "1.0"]`, after templating, this field gets converted to `["my_package_version", 1.0]` which may not be what you intended. 

I run into this when using KubernetesPodOperator. The `arguments` there must be a list of strings, so this behavior is unexpected. Sometimes, it is convenient to use `render_template_as_native_obj` for other purposes.

I've discovered that you can get the desired string by encapsulating, eg `"'1.0'"` turns into `"1.0"` after templating but this is strange and un-ergonomic for consumers of these operators.

### What you think should happen instead

It may be desired to pass a string through templating only if a `{{ }}` is detected within it.

For example, this logic could be added to string templating [here](https://github.com/apache/airflow/blob/4a9824de8e063ee78a18583de24cd59718adc7f7/airflow/template/templater.py#L172-L174)

### How to reproduce

Add a string representation of integer or some other native Python type, and its type will be converted under native templating, even without a `{{}}` in the string.

For example:

```
from airflow.models import DAG
from airflow.operators.python import PythonOperator
import datetime

op_args = ["abc", "1.0", "{{ var }}"]

# Task/dag definition
dag = DAG(dag_id="sample", render_template_as_native_obj=True, start_date=datetime.datetime(2021, 1, 1))
task = PythonOperator(task_id="python_task", python_callable=print, op_args=op_args, dag=dag)

# Do rendering
task.render_template_fields({"var": [1,2,3]})

task.op_args
# ['abc', 1.0, [1, 2, 3]]
# I probably wanted the native list obj without "1.0" being converted to 1.0
```

### Operating System

MacOS

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
No. This is the way how https://jinja.palletsprojects.com/en/3.0.x/nativetypes/ works (and this is what we are using). we are not going to change how it works. You might instead make a proposal and change to JINJA if you want to change how it works.

What you can do instead you can add PR to add another way of resolving templates - new parameter etc. But we are not going to modify the way how NativeEnvironment from Jinja works. That would be also backwards-incompatible, so we are not going to `change` how it works.

**Comment by potiuk** [comment]
You probably do not understand.

That parameter - when set - means "use https://jinja.palletsprojects.com/en/3.0.x/nativetypes/" . Always. No exceptions.

If you want to propose a different scheme - feel free. But this will be a different scheme.

**Comment by potiuk** [comment]
Yes. And yes, you are most welcome to contribute a NEW FEATURE to support it - the idea is that if you want something to happen to open-source, contributing it to a project that you are using, is the best way you can give back to everyone who contributed as well. If it's not neceessary for you, but you have a `wish` for it to happen, then it will become a `wish` until someone will pick an interest and make it happen. That how it works when you get a free software to use.
