### ISSUE TITLE
OAUTH users not getting the login again screen when the user password reset or token invoked on OAUTH PROVIDERS side

### ISSUE THREAD

**Issue by thanushcst** [apache/airflow#35980]
### Apache Airflow version

2.8.0b1

### What happened

Go to 'login'
Login with Oauth User
Reset the password on Oauth user manager
Superset keep allowing the user with existing login

### What you think should happen instead

Should be redirect to login page if the user action found on UI

### How to reproduce

Should be redirect to login page if the user action found on UI

### Operating System

Docker

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
@thanushcst does this issue still occur in 2.9.X?
