### ISSUE TITLE
Using xcom in non PythonOperators

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#360]
Hi Guys,

I'd like to use parameters passed from an earlier task (`PythonOperator`) in a `PostgresOperator`. Is it possible to somehow use the xcom_pull function inside a `PostgresOperator`?

i.e. 
Task A (Python) ------ returns a list [foo, bar] ------> Task B (Postgres)

Where task B uses the list [foo,bar] in a Jinja templated piece of SQL.

**Comment by mistercrunch** [comment]
Totally. In your template, you just have to do something similar to:

```
SELECT * FROM {{ ti.xcom_pull('table_name') }}
```

FYI `ti` is a shortcut to the current `task_instance` object

**Comment by jlowin** [comment]
didn't realize you could do that! :+1:

**Comment by martingrayson** [comment]
Awesome, I couldn't work out how to get at the task instance - didnt occur to me that you could actually reference it in the template. Brilliant work guys :smile_cat:

**Comment by mistercrunch** [comment]
Here's the documentation reference to everything accessible in the templates (and in the "context" passed to operators):
http://pythonhosted.org/airflow/code.html#macros
