### ISSUE TITLE
Airflow DAG manual runs conflict with scheduled runs

### ISSUE THREAD

**Issue by reinafengreinafeng** [apache/airflow#36098]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version 2.6.2

With a manual run in the past, the next schedule run will be skipped.
<img width="772" alt="image" src="https://github.com/apache/airflow/assets/100874512/ccdc4207-1ec1-4b60-8244-a6dbe3825463">
<img width="765" alt="image" src="https://github.com/apache/airflow/assets/100874512/c1f7af70-a21d-4f47-83dc-0034cf0a0044">

### What you think should happen instead

For the Airflow DAG(or scheduled runs), the logical date is  Data interval start. For manual runs, the logical date that you specified on the UI is Data interval end. The logical date is shown in the “Run ID” on the UI.

At 14:06:52, Airflow DAG treats the timestamp in the “Run ID” to be start date so it thought manual__2023-11-07T14:06:00+00:00 is for 14:06:00 ~ 14:08:00. So it generated a catch up run scheduled__2023-11-07T14:04:00+00:00 which is actually a duplicate run for 14:04:00 ~ 14:06:00

At 14:08:00, with the same reason, the Airflow DAG thought the run for14:06:00 ~ 14:08:00 has already be done by manual__2023-11-07T14:06:00+00:00 so it didn’t trigger scheduled__2023-11-07T14:06:00+00:00.

At 14:11:00, when we tried to trigger a manual run for 14:06:00 ~ 14:08:00 , we passed 14:08:00 as the logical date. But the airflow thought the logical date here was start date but the scheduled__2023-11-07T14:08:00+00:00 for 14:06:00 ~ 14:08:00 had already done. So it raised an error. 

### How to reproduce

The reproduce steps have been listed above.

### Operating System

idk

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
I'm not able to reproduce this. Can you provide an example DAG? Something that stands out is that the first manual run was triggered at 14:05:00 but it didn't start running until 14:06:49... Is there a lot of traffic in this Airflow environment?
