### ISSUE TITLE
Webserver returns 500 for POST requests to api/dag/*/dagrun from anonymous user 

### ISSUE THREAD

**Issue by eliskovets** [apache/airflow#36110]
### Apache Airflow version

2.7.3

### What happened

After upgrade to 2.7.3 I noticed that webserver returns 500 for POST requests with a `note` field. After some investigation it seems that None in [user_id](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L1524) converted to str causing it: 
```
[SQL: INSERT INTO dag_run_note (user_id, dag_run_id, content, created_at, updated_at) VALUES (%(user_id)s, %(dag_run_id)s, %(content)s, %(created_at)s, %(updated_at)s)]
[parameters: {'user_id': 'None', 'dag_run_id': 2944, 'content': 'test', 'created_at': datetime.datetime(2023, 12, 7, 17, 42, 15, 390085, tzinfo=Timezone('UTC')), 'updated_at': datetime.datetime(2023, 12, 7, 17, 42, 15, 390096, tzinfo=Timezone('UTC'))}]
rundag [07/Dec/2023:17:42:15 +0000] "POST /api/v1/dags/*/dagRuns HTTP/1.1" 500 1539 "-" "python-requests/2.31.0"
```
That's probably not an issue of Airflow itself, but SQLAlchemy 1.4. it's probably fixed in 2.0.

### What you think should happen instead

Dagrun should be successfully registered by airflow and note should be saved into `dag_run_note` table.

### How to reproduce
1. Disable Auth to allow unauthorized access to the API in `webserver_config.py`
```
AUTH_ROLE_PUBLIC = "Admin"
```
2. Try to schedule a run via `DAGRun` API
```python
import requests
dag_run_url="https://airflow/api/v1/dags/test/dagRuns"
r = requests.post(
    url=dag_run_url, json={"dag_run_id": "test_me", "note":"note", "conf": {}}
)
assert r.status_code == 500

print(r.text)

```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other Docker-based deployment

### Deployment details

Docker image: apache/airflow:2.7.3-python3.9
DB: Postgresql

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pateash** [comment]
I can take this up if needed.
@potiuk @eladkal

**Comment by eliskovets** [comment]
Hi @pateash , 
Sorry, forgot to tell you, that I also have `"AIRFLOW__API__AUTH_BACKENDS": "airflow.api.auth.backend.default"` set.

**Comment by pateash** [comment]
## **RCA** 

user_id is coming as 'None':,
The error message indicates that **user_id** is being passed as the string '**None**', which is invalid for an integer field in the database. This is happening because the user context is not properly set due to disabled authentication.

**Comment by pateash** [comment]
The issue here is ,

<img width="402" alt="image" src="https://github.com/apache/airflow/assets/16856802/3424fbde-2f80-4d14-9a74-cabf43df93c3">

user_id is a foreign key from **ab_user** table, 
so what should we add in here?
although we can insert add **null** here .

I might need your input @potiuk, @eladkal

**Comment by pateash** [comment]
looks like we should be able to insert null here,
moving forward by inserting null, we can revisit if there is any objection.

<img width="782" alt="image" src="https://github.com/apache/airflow/assets/16856802/7ec011e6-9345-4b53-9054-17d38df9bdc0">

**Comment by eliskovets** [comment]
@pateash i believe before 2.7 notes weren't a separate table, that's why it worked before.
