### ISSUE TITLE
Add operator to capture diagnostic tarball for Dataproc 

### ISSUE THREAD

**Issue by fnshemerirwe** [apache/airflow#36173]
### Description

Add operator to capture the diagnostic tarball for a Dataproc cluster managed by Airflow.

### Use case/motivation

The [diagnostic tarball](https://cloud.google.com/dataproc/docs/support/diagnose-cluster-command) captures and persists the state of the Dataproc cluster even after the cluster has been deleted. It would be nice to have an operator that captures the diagnostic tarball that can be used to troubleshoot issues affecting Dataproc clusters and jobs managed by Airflow.

### Related issues

NA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment]
Sounds cool. Feel free to submit a PR!
