### ISSUE TITLE
Add unit tests to retrieve fsspec  from providers including backwards compatibility

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#36187]
### Body

We currently miss fsspec retrieval for providers and #36186 fixed compatibility issue with it, so we should likely add unit tests covering it.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @bolkedebruin

**Comment by bolkedebruin** [comment]
We should indeed test, but should we not yank the older released providers? This seems over doing the backwards compat (and maintaining it!) While the feature , somewhat arguably, couldn't  be used. 

Well maybe not as they are existing providers, unlike common.io. Still it feels weird. If a change ends up in a provider before generally usable and still being worked on we should have a different mechanism IMHO.

**Comment by potiuk** [comment]
> Well maybe not as they are existing providers, unlike common.io. Still it feels weird. If a change ends up in a provider before generally usable and still being worked on we should have a different mechanism IMHO.

Absolutely agree. Any idea how to do it? what do you think will be a better approach here?

**Comment by potiuk** [comment]
> We should indeed test, but should we not yank the older released providers? This seems over doing the backwards compat (and maintaining it!) While the feature , somewhat arguably, couldn't be used.

This would not work.

Yanking is when there is an error, and we already have some of those providers as part of "golden" constraints in some versions of airflow, which means that when someone upgrades just airflow without providers, they will still remain with those versions. Yanking only prevents people from making specific version available for `pip` resolver  when it resolves new set of packages to install, but when you either specified the version explicitly (which we do with constraints) or when the package is already installed `yanking` has no effect.

So in scenario when someone installed `airflow[amazon]==2.7.3` and after that `airflow==2.8.0` they would end up with broken amazon provider.
