### ISSUE TITLE
Create CLI command `airflow providers auth-managers`

### ISSUE THREAD

**Issue by vincbeck** [apache/airflow#36193]
### Description

Providers can provide custom auth managers. It would be interesting that, in the same fashion as `airflow providers executors`, to have a CLI command `airflow providers auth-managers` which list all auth managers available in the environment.  

### Use case/motivation

Any provider can provide a custom auth manager, since the number of providers can become big, it would be interesting for the end user  to have a CLI command which list all auth managers provider by the providers installed in the environment.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
Can i pick this issue too? @potiuk @vincbeck

**Comment by potiuk** [comment]
Sure :)

**Comment by vincbeck** [comment]
Be my guest :)

**Comment by Bowrna** [comment]
@vincbeck The following command is used to get the current auth manager configured:
```airflow config get-value core auth_manager```. But the scope of this CLI command is to list out all the auth managers available unlike the one that's currently used right?

**Comment by Bowrna** [comment]
hi @potiuk @vincbeck i am trying to fix this issue and when hitting the cli command with options for `airflow providers` cmd line. It lists only the old set of commands and the new set of commands is not visible to me even when the code has the recent set of commands in it. i tried setting up the cmd line like mentioned in below docs. Am I missing something?
<img width="1439" alt="Screenshot 2023-12-26 at 1 15 35 PM" src="https://github.com/apache/airflow/assets/10162465/18ae4b35-4394-443b-9a29-474622031ea4">

https://airflow.apache.org/docs/apache-airflow/stable/howto/usage-cli.html#set-up-bash-zsh-completion

**Comment by Bowrna** [comment]
> hi @potiuk @vincbeck i am trying to fix this issue and when hitting the cli command with options for `airflow providers` cmd line. It lists only the old set of commands and the new set of commands is not visible to me even when the code has the recent set of commands in it. i tried setting up the cmd line like mentioned in below docs. Am I missing something? <img alt="Screenshot 2023-12-26 at 1 15 35 PM" width="1439" src="https://private-user-images.githubusercontent.com/10162465/292831927-18ae4b35-4394-443b-9a29-474622031ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzk2MTYsIm5iZiI6MTcwMzU3OTMxNiwicGF0aCI6Ii8xMDE2MjQ2NS8yOTI4MzE5MjctMThhZTRiMzUtNDM5NC00NDNiLTlhMjktNDc0NjIyMDMxZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNzI4ZWFjZGYwMTllYmRlMTM4MDFlMzFjY2EzZjE2ODYzOGE2YTc2MjI0MGViNWViZjg1OGYwODZlOTlkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBcCs1ivzuudlPl_s6x5IaJV0yl627T7HlkIni_Y52k">
> 
> https://airflow.apache.org/docs/apache-airflow/stable/howto/usage-cli.html#set-up-bash-zsh-completion

can be ignored. I checked without getting into airflow env. it works now
