### ISSUE TITLE
"Mark state as..." button options grayed out

### ISSUE THREAD

**Issue by internetcoffeephone** [apache/airflow#36219]
### Apache Airflow version

2.7.3

### What happened?

Since a few versions ago, the button to mark a task state as success is grayed out when the task is in a success state. Conversely, whenever a task is in a failed state, the mark button as failed is grayed out.
![Screenshot 2023-12-14 at 11 15 31](https://github.com/apache/airflow/assets/5096835/d263c7d6-8a3f-4e81-a310-dcb790365a73)

### What you think should happen instead?

This is inconvenient. These buttons bring up another dialog where you may select past/future/downstream/upstream tasks. These tasks may not match the state of the task you currently have selected. Frequently it is useful to be able to set all downstream tasks of an already succeeded task to success.
![Screenshot 2023-12-14 at 11 21 01](https://github.com/apache/airflow/assets/5096835/b2d87cde-a7a6-48a1-8b64-73d4b6830546)

The current workaround is to first set the task to the opposite of the desired state, then to mark it as the desired state with added past/future/downstream/upstream tasks. This is clunky.

The buttons should not be grayed out depending on the current task state.

### How to reproduce

Mark a task as success. Then try to do it again.

### Operating System

n/a

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Good call. This should be a one line change to just remove a `disabled` prop if you want to do it!
