### ISSUE TITLE
Helm Chart tatsd-mappings.yml still referencing old (Airflow 1.x) Pool metrics

### ISSUE THREAD

**Issue by frankgrimes97** [apache/airflow#36245]
### Official Helm Chart version

1.8.0

### Apache Airflow version

2.5.3

### Kubernetes Version

v1.23.7

### What happened

The `statsd-mappings.yml` is referencing old `airflow.pool.used_slots` which no longer exist since Airflow 2.0.0 release (ref: https://lists.apache.org/thread/ojn90zln7oc2d79jz6kpg6np1hr4t3cl).
It seems that as part of [[AIRFLOW-5662] Reduce DB queries used to emit pool usage metrics](https://github.com/apache/airflow/pull/6342) it was replaced with the following two metrics:
  - `airflow.pool.queued_slots`
  - `airflow.pool.running_slots`

N.B. this remains incorrect even on the latest version in `main`: https://github.com/apache/airflow/blob/1f6f34dba0dbc82778d25839cd78945736424692/chart/files/statsd-mappings.yml#L79C1-L82

### What you think should happen instead

`airflow.pool.queued_slots` and `airflow.pool.running_slots` should be exposed instead

### How to reproduce

N/A

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Maybe yoy would like to fix it @frankgrimes97 ? PRs are always most welcome. Otherwise it will wait for someone to pick it up
