### ISSUE TITLE
Update Airflow code to use pendulum 3

### ISSUE THREAD

**Issue by JhangShengLuo** [apache/airflow#36274]
### Apache Airflow version

2.8.0b1

### What happened?

Due to Pendulum's latest release (https://github.com/sdispater/pendulum/releases/tag/3.0.0)
might need to update settings.py  -> pendulum.tz.timezone("UTC") into pendulum.timezone("UTC")

### How to reproduce

when python package Pendulum==3.0.0

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

airflow==2.5.0

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Airflow do not compatible with pendulum 3 yet, and 2.8.0b1 has a limitation [pendulum>=2.0,<3.0](https://github.com/apache/airflow/blob/c28ba46e131c96fcd98043333dca28589cc782fe/setup.cfg#L131-L133)

**Comment by Taragolis** [comment]
For older versions of Airflow you should use constraints files, see:
- [[Reminder] How to reproducibly install Airflow](https://lists.apache.org/thread/b8q1t3pvtky7y7mb2kjt4r2bz5bvz8qy)
- [Installation of Airflow™: Installation from PyPI](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html)

**Comment by potiuk** [comment]
Also we have whole huge discussion on what we do with Pendulum. Updating one import is a tip of the iceberg here, this is not going to be solved by single PR or solving one issue. @JhangShengLuo you are welcome to take part in the devlist discussion to discuss future of Pendulum in Airflow here: https://lists.apache.org/thread/vpwxg8r93nrhnth3q63b8polt7xyvkwm  - this is where decisions about what we do with Pendulum 3 will be made.

Closing it, as this is really a devlist discussion thread.

**Comment by JhangShengLuo** [comment]
Great explanation and hard-working, thanks @Taragolis, @potiuk.
