### ISSUE TITLE
Leak in Celery Executor Running Tasks Slot Count

### ISSUE THREAD

**Issue by dirrao** [apache/airflow#36335]
Facing the same issue with airflow 2.6.2. Airflow ui shows no tasks are running but the Celery executor open slots are stuck to zero whereas running slots are stuck at 32 which results skip over queuing/running any more tasks.

AIRFLOW__CORE__PARALLELISM is 32 and the number of workers running is 2 with having AIRFLOW__CELERY__WORKER_CONCURRENCY value 8

I'm not really sure how to reproduce it, because it happens over a period of time, and that too sporadically.

The below image shows the number of tasks running for the celery executor.  It slowly goes up and when it reaches the limit, **sometimes** it doesn't come down until we restart the scheduler.
![image](https://github.com/apache/airflow/assets/19358003/9eada2ed-3124-4204-b94a-2e5bc5acd5d7)

The below image shows the number of open slots for the celery executor, which follows the same pattern as above because it's inversely proportional to the number of running tasks.
<img width="775" alt="image" src="https://github.com/apache/airflow/assets/19358003/58be1236-91ae-495b-97ed-67f6a1826d5c">

The below image shows the number of tasks running per pool in the airflow webserver UI. Here we can see that the number of running tasks are not in proportion with the celery executor slots and we have observed that after a point Airflow stops scheduling any task at all because it doesn't find any open slot of the executor.
![image](https://github.com/apache/airflow/assets/19358003/7191cfbd-ba8f-47bb-be64-782de4cea2a4)

To mitigate this issue, we are restarting the scheduler every hour. Please suggest if we can follow any better approach to overcome the same.

_Originally posted by @Cricktom in https://github.com/apache/airflow/issues/32928#issuecomment-1733324843_

**Comment by deepak4babu** [comment]
Is there any update on this? we are facing the same issue in our environment. Currently we are restarting our scheduler pod every hour to mitigate this.

**Comment by r0ck37** [comment]
we have the same issue.

**Comment by potiuk** [comment]
Airflow 2.10.3 is now out an it has fix #42932 that is likely to fix the problems you reported, please <author> upgrade, check if it fixed your problem and report back @dirrao @deepak4babu @r0ck37 ?
