### ISSUE TITLE
Kubernetes Executor -> is forbidden: exceeded quota

### ISSUE THREAD

**Issue by devscheffer** [apache/airflow#36348]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

I’m using the Kubernetes executor along with the Kubernetes pod operator. My DAG has many tasks running in parallel. 

However, when resources are not available for a task, I encounter an error. The error message indicates that the pod has exceeded its resource quota.
```
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"xxx\" is forbidden: exceeded quota: airflow-dags-resource-quota, requested: limits.cpu=550m, used: limits.cpu=3300m, limited: limits.cpu=3500m","reason":"Forbidden","details":{"name":"xxx","kind":"pods"},"code":403}
```

### What you think should happen instead?

I was under the impression that when using the Kubernetes executor, tasks would queue until sufficient resources become available, rather than failing. I’m wondering if I’ve overlooked some configuration settings. For most configurations, I’m using the default values provided by the Airflow Helm chart. Can anyone help me understand this?

### How to reproduce

use kubernetes and the airflow helmchart, set some resource quota for the namespace and try to execute a lot of tasks in parallel that would normally consume more resource than it is available

### Operating System

ubuntu

### Versions of Apache Airflow Providers

2.7.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by csp33** [comment]
hi @devscheffer , I believe this issue is related to your k8s cluster rather than to Airflow.
It seems that you have some quotas defined for the namespace you're trying to run the task in.
You can check it with `kubectl get quota -n <your namespace>`

https://kubernetes.io/docs/concepts/policy/resource-quotas/
