### ISSUE TITLE
AWS Provder Operators and Sensors Duplicate Code

### ISSUE THREAD

**Issue by dirrao** [apache/airflow#36386]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon 8.13.0

### Apache Airflow version

2.8.0

### Operating System

Cent OS 7

### Deployment

Other

### Deployment details

Docker based deployments

### What happened

I have seen duplicate code related to deferrable execute_complete in operators and sensors of aws provider. It would be nice to abstract this into aws base operator/sensor and inherit it across all the aws operators and sensors to avoid duplicate code.

### What you think should happen instead

 It would be nice to abstract this into aws base operator/sensor and inherit it across all the aws operators and sensors to avoid duplicate code.

### How to reproduce

N/A

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Is it some how related to the https://github.com/apache/airflow/issues/35278 ?

**Comment by dirrao** [comment]
> Is it some how related to the #35278 ?

Yes. Both of them meant for the same.

**Comment by Taragolis** [comment]
Ok, let's then close this one in favor or https://github.com/apache/airflow/issues/35278.
If required something more than described in  https://github.com/apache/airflow/issues/35278 then required to add more details and we could reopen this issue
