### ISSUE TITLE
The task is stuck in a queued state forever in case of pod launch errors

### ISSUE THREAD

**Issue by dirrao** [apache/airflow#36403]
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes: 7.11.0

### Apache Airflow version

2.8.0

### Operating System

Cent OS 7

### Deployment

Other

### Deployment details

Terraform based deployment

### What happened

When the K8 executor is unable to launch the worker pod due to permissions issues or an invalid namespace. The K8 executor keep trying to launch the worker pod and the errors remain persist. So, the task ends up in a queued state for so long/forever. 

### What you think should happen instead

We shouldn't retry the worker pods launch continuously in case of persistent/transient errors. Let the executor mark them as failed and let the scheduler honor the task retries with retry delay (5 mins) and then fail the task eventually if the error persists.  

### How to reproduce

We can try the following scenarios
a> Provide incorrect namespace in prod_override configuration
b> Role that doesn't have permissions to launch the pod in a specific namespace
c> namespace quota exhausted 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
feel free to attempt to handle it

**Comment by adihakimi** [comment]
We’re facing the same issue on v2.6.3.
We thought that ‘scheduler_task_queued_timeout’ might help but it doesn’t.

**Comment by dirrao** [comment]
> scheduler_task_queued_timeout

Existing options doesn't help here. I am going to raise an MR to fix this issue very soon.

**Comment by RNHTTR** [comment]
Hey @dirrao -- Wondering if you had a chance to open a PR for this?
