### ISSUE TITLE
Empty Details tab after upgrading to Airflow 2.8.0 (Dynamic Task Mapping)

### ISSUE THREAD

**Issue by csp33** [apache/airflow#36481]
### Apache Airflow version

2.8.0

### What happened?

After upgrading to Airflow 2.8.0, I've found out that the `Details` tab is empty for mapped tasks
<img width="1715" alt="image" src="https://github.com/apache/airflow/assets/28935464/38b4d53a-47d5-4c6c-bb82-60f317d62ae5">

### What you think should happen instead?

Details tab should appear, just like before

### How to reproduce

1. Run the following DAG
  ```python
    with DAG(
        dag_id="test_mapped_tasks_ui",
        schedule=None,
        catchup=False,
        max_active_runs=1,
        render_template_as_native_obj=True,
    ) as dag:
    
        @task
        def my_task(idx: int) -> None:
            print(f"Task {idx} done")
    
        my_task.expand(idx=list(range(1, 10)))

  ```
2. Open the `Details` tab of `my_task`

### Operating System

Airflow in Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Likely should be address before 2.8.1 (cc: @bbovenzi @pierrejeambrun).

@csp33 -> can you see any errors in console log (open inspect view in your browser) when you open the details tab? Could you please post it here?

**Comment by csp33** [comment]
> Likely should be address before 2.8.1 (cc: @bbovenzi @pierrejeambrun).
> 
> @csp33 -> can you see any errors in console log (open inspect view in your browser) when you open the details tab? Could you please post it here?

<img width="1720" alt="image" src="https://github.com/apache/airflow/assets/28935464/aa24cf53-284c-4894-a302-736861d36b95">

Just a deprecation warning
