### ISSUE TITLE
Missing AzureSynapseRunPipelineOperator in docs

### ISSUE THREAD

**Issue by KamilKandzia** [apache/airflow#36488]
### What do you see as an issue?

There are two operators in the synapse.py file (https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/operators/synapse.py), but on the page https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/operators/azure_synapse.html AzureSynapseRunPipelineOperator is not described (missing)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by killua1zoldyck** [comment]
Hi, I can work on this.
