### ISSUE TITLE
Airflow installation failed with pip command on Python 3.8

### ISSUE THREAD

**Issue by cd10anil** [apache/airflow#36520]
### Apache Airflow version

2.8.0

### What happened?

When tried to install AirFlow using pip command in python 3.8 environment, if failed with Error: invalid requirement. The details below in screenshot. 
![image](https://github.com/apache/airflow/assets/2949158/e0b6efea-d589-47f1-bb46-679dba8c14d7)

### What you think should happen instead?

The installation of airflow should succeeded.

### How to reproduce

1. Windows 11 machine, VS Code , create a empty folder, setup a project folder. on vs terminal, create environment for python, activate the environment. then try to install airflow with command given in github for pip installation 
"pip install 'apache-airflow==2.8.0' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.0/constraints-3.8.txt"
on which it throw below error.
ERROR: Invalid requirement: "'apache-airflow==2.8.0'"

### Operating System

Windows 11 Home Single language OS

### Versions of Apache Airflow Providers

apache-airflow==2.8.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is expected. Check prerequisites. Airflow on Windows can only be installed with WSEL2:

https://airflow.apache.org/docs/apache-airflow/stable/installation/prerequisites.html

```
Airflow™ currently can be run on POSIX-compliant Operating Systems. For development it is regularly tested on fairly modern Linux Distros and recent versions of MacOS. On Windows you can run it via WSL2 (Windows Subsystem for Linux 2) or via Linux Containers. The work to add Windows support is tracked via [#10388](https://github.com/apache/airflow/issues/10388) but it is not a high priority. You should only use Linux-based distros as “Production” execution environment as this is the only environment that is supported. The only distro that is used in our CI tests and that is used in the [Community managed DockerHub image](https://hub.docker.com/p/apache/airflow) is Debian Bullseye.
```
