### ISSUE TITLE
Pause DAG such that all tasks complete

### ISSUE THREAD

**Issue by rajrao** [apache/airflow#36539]
### Description

Currently when one pauses a DAG, it allows the currently executing task to complete and then leaves all downstream tasks to go to scheduled.
I feel like there should be the ability to "Complete DAG run and then Pause", so that the entire DAG run can complete.

### Use case/motivation

Often times we need to take down a certain service that a DAG is dependent on (eg: database server). Currently, we have the ability to pause the dag, which allows the executing task to complete and then puts all other downstream tasks in "scheduled" state and runs them once the Dag is unpaused.

When the DAG is long running, we ideally would like to allow the entire DAG to complete so that the result of the DAG can be made available for customers and then pause the DAG. This way, I could put all these dags into "Complete and then Pause" mode and wait for all the work against my services to complete. After that I could take them offline, or do whatever work on them and then unpause all of the DAGs.

Another use case is when we have to upgrade the Airflow. In such cases, again it would be nice to get all DAGs that are running to complete and then upgrade the Airflow.

In the absence of such functionality, we are looking at adding a shortcircuit operator to our DAGs that would then check if a variable is set and if it is, then it would return False and short-circuit then run. This seems like adding an additional bit of plumbing that might be best implemented directly as part of DAG UI via an option like "Complete all downstream tasks and then Pause"

For the Airflow upgrade use case, often times we have to take longer for the upgrade, as someone has to look at the DAG runs and as the complete, pause them and once they are all paused, then do the upgrade. And this needs someone to babysite Airflow. But, if there was a single option to allow ALL dags to "complete and then pause" this would be so much better.

see also https://stackoverflow.com/questions/77734881/allow-current-dagrun-to-complete-and-disable-all-subsequent-runs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Agree nice feature to have. Let's see if someone will take it on.

**Comment by vchiapaikeo** [comment]
Hey @rajrao - I've been talking to @eladkal about this and we both agree that this feature would be beneficial. One thing I wanted to suggest in the meantime (and possibly for the person who works on this) is to use the `end_date` field on the dag. When we had to do something similar during a side-by-side migration, we leveraged the `end_date` field to drain dags off of our old Airflow (and subsequently modified their `start_date`s for new Airflow). Most of our dags were daily but some were hourly so pegging at the right `end_date` can be tricky. 

With many dags, this can quickly get difficult to scale but codemod solutions like [fastmod](https://github.com/facebookincubator/fastmod) can help. If a solution allowed us to do this programmatically, that would be really nice.

**Comment by aritra24** [comment]
I was trying to look into this, what is the behaviour we're expecting?
1. Is it a parameter set in the configs that determines the behaviour on pause? (For example drain_current_tasks_on_pause) or is it something in the UI?
2. Also I was looking through the scheduler_job_runner and I guess the point where it makes this determination is [here](https://github.com/apache/airflow/blob/main/airflow/jobs/scheduler_job_runner.py#L373) so my question is, is there a scenario where there would be a TI which is in scheduled state, it's dag model is in paused state and it should not run or is the solution just to make the is paused check based on the param/ui field? 
@eladkal if you have any guidance you could provide me on above I can try making a commit.

**Comment by kmehkeri** [comment]
It feels to me that the cleanest approach would be to strictly separate two effects currently being under one switch:
- Pause (scheduler doesn't trigger new DAG runs) / unpause
- Put on hold (scheduled tasks aren't picked up by workers) / resume

Adding option to "pause the DAG in a different mode" has chance to cause confusion.

**Comment by aritra24** [comment]
Hey @potiuk /@eladkal just wanted to bring this onto your radar, would you have any suggestions on the direction of implementation on this?

**Comment by potiuk** [comment]
I do not have a clear vision on implementation details here, but intuitively, it seems that we should have a new state of dag (hold) which will be same as "paused" for scheduler but same as "active" for executor. Then scheduler could change it automatically put it to paused, when all tasks for that DAG are completed. 

But it should start from pretty careful inventory or where it is used and deciding if this is a doable thinkg

**Comment by aritra24** [comment]
That sounds reasonable, let me try it out and see how it goes. I'll update once I have something working on here.

**Comment by eladkal** [comment]
Closing as duplicated of https://github.com/apache/airflow/issues/22006 lets continue discussion there
