### ISSUE TITLE
Redis hook with ssl fails instantiate Redis client

### ISSUE THREAD

**Issue by shohamy7** [apache/airflow#36552]
### Apache Airflow Provider(s)

redis

### Versions of Apache Airflow Providers

apache-airflow-providers-redis==3.5.0 (latest)

### Apache Airflow version

2.8.0

### Operating System

Debian GNU/Linux

### Deployment

Official Apache Airflow Helm Chart

### What happened

When trying to use the `RedisHook` with SSL, the Redis client fails to instantiate due to misconfiguration of the `ssl_cert_file` which is not exist in the python redis library.
Instead it should be `ssl_certfile`, you can click [here](https://redis.io/docs/connect/clients/python/#:~:text=import%20redis-,r%20%3D%20redis.Redis(,),-r.set ) to see an examle in the redis docs.

When instantiating a `RedisHook` with SSL, the following error occurs:
<img width="681" alt="Screen Shot 2024-01-03 at 14 11 21" src="https://github.com/apache/airflow/assets/46799583/f5b065ae-fd92-4f97-b677-120327cf9a5a">

The task obviously fails after this exception.
Full logs here:
[dag_id=dummy_redis_run_id=manual__2024-01-03T09_14_02+00_00_task_id=dummy_redis_task_attempt=1.log](https://github.com/apache/airflow/files/13818807/dag_id.dummy_redis_run_id.manual__2024-01-03T09_14_02%2B00_00_task_id.dummy_redis_task_attempt.1.log)

### What you think should happen instead

The `RedisHook` instantiation should work with SSL.

### How to reproduce

To reproduce do the following:
1. Create the following connection:
<img width="961" alt="Screen Shot 2024-01-03 at 14 23 22" src="https://github.com/apache/airflow/assets/46799583/3b8a768f-5b9c-4ab1-bb6c-e7c7303c18b1">

You can copy the extra from here:
```
{
  "db": 0,
  "ssl": true,
  "ssl_cert_reqs": "required",
  "ssl_cert_file": "/tmp",
  "ssl_check_hostname": false
}
```

2. Run the following DAG:

```
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.redis.operators.redis_publish import RedisPublishOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2023, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'dummy_redis',
    default_args=default_args,
    schedule=None, 
) as dag:
    dummy_redis = RedisPublishOperator(
        task_id="dummy_redis_task",
        channel="dummy",
        message="hello",
        redis_conn_id="test_redis",
    )
```
3. Run the DAG and wait for it to fail.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shohamy7** [comment]
@jscheffl @potiuk 
Should we support both `ssl_cert_file` and `ssl_certfile` with deprecation warning for the `ssl_cert_file` extra?
This will fix the problem for already created connections in the old way.
Let me know what are you thinking :)

**Comment by potiuk** [comment]
Ideally both with deprecation.
