### ISSUE TITLE
Bold and increase font-size of graph task headers

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#36557]
### Description

I think bolding and increasing the fontsize of task headers would improve legibility. Here is a comparison: 

Before:
<img src="https://github.com/apache/airflow/assets/10968348/92a986f2-00a7-4d95-bdad-0279881ce60e" width="300">

After: 
<img src="https://github.com/apache/airflow/assets/10968348/30a73ae8-318a-419a-ab41-91638700e64e" width="350">

This was from just adding `font-weight: bold` and `font-size: 14px` to the header css, and increasing the height of the task by a few pixels.

Some other suggestions are to make the the border a bit wider and drop the task status from the contents since the border now makes it redundant. It could be replaced with duration or nothing at all.

<img src="https://github.com/apache/airflow/assets/10968348/761d137d-d546-4b67-a315-01f5717bb333" width="300">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Thanks for the proposal. Peronally I'd prefer to keep a consistent font size (meaning not too many different font sizes on the UI) but making bold text and other proposals looks good to me (but I am just one person - other opinions welcome).

I assigned you the issue, feel free to raise a PR.

**Comment by NilsJPWerner** [comment]
@bbovenzi do you have thoughts?

**Comment by aadeshmodak13** [comment]
We have to go to airflow/www/static/css/graph.css   Am I right??  I'm new to open source.

**Comment by bbovenzi** [comment]
We got rid of most of graph.css. It's all in https://github.com/apache/airflow/tree/main/airflow/www/static/js/dag/details/graph now.

We can definitely make the name bigger. One idea I was toying with was also to hide details and only show the status color and task name when you zoom out.

**Comment by NilsJPWerner** [comment]
That's a good idea! I was thinking that running tasks could dynamically display their current run time as well. You could also have some sort of progress indicator that compares current run time to average previous run times. That may be a bit involved though.

**Comment by bbovenzi** [comment]
Yes it would be fun to be able to display more useful info like that while also having a simpler view too.

Rough WIP:
<img width="731" alt="Screenshot 2024-01-25 at 4 34 21 PM" src="https://github.com/apache/airflow/assets/4600967/9d12678d-d5de-4928-adad-d807133dae5f">

<img width="468" alt="Screenshot 2024-01-25 at 4 34 27 PM" src="https://github.com/apache/airflow/assets/4600967/675b8378-d98a-41d0-9800-c1018da0fde4">
