### ISSUE TITLE
Google Dataflow Providers Raises an Exception when job has failed/cancelled

### ISSUE THREAD

**Issue by themitigater** [apache/airflow#36567]
### Apache Airflow Provider(s)

google

### Apache Airflow version

2.6.3

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Google Cloud Composer
composer-2.5.3-airflow-2.6.3

### What happened

```python
ERROR 2024-01-03T19:38:49.509065278Z Task failed with exception Traceback (most recent call last): File "/home/airflow/gcs/plugins/operators/dataflow_staging.py", line 885, in execute self.job = self.hook.start_flex_template( File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper return func(self, *args, **kwargs) File "/home/airflow/gcs/plugins/hooks/dataflow_staging.py", line 871, in start_flex_template jobs_controller.wait_for_done() File "/home/airflow/gcs/plugins/hooks/dataflow_staging.py", line 484, in wait_for_done while self._jobs and not all( File "/home/airflow/gcs/plugins/hooks/dataflow_staging.py", line 485, in <genexpr> self._check_dataflow_job_state(job) for job in self._jobs File "/home/airflow/gcs/plugins/hooks/dataflow_staging.py", line 475, in _check_dataflow_job_state raise Exception( Exception: Google Cloud Dataflow job dataflow-operator-some-pipeline-status-20240103-150500-3-c0b5a70c is in an unexpected terminal state: JOB_STATE_CANCELLED, expected terminal state: JOB_STATE_DONE
ERROR 2024-01-03T19:38:50.049752244Z Failed to execute job 903791 for task dataflow_operator-staging-av_agent_active_status (Google Cloud Dataflow job dataflow-operator-some-pipeline-status-20240103-150500-3-c0b5a70c is in an unexpected terminal state: JOB_STATE_CANCELLED, expected terminal state: JOB_STATE_DONE; 409959)
ERROR 2024-01-03T19:38:50.172097569Z Marking run <DagRun dataflow_dag-staging-av_agent_active_status @ 2024-01-03 15:05:00+00:00: scheduled__2024-01-03T15:05:00+00:00, state:running, queued_at: 2024-01-03 19:34:54.329527+00:00. externally triggered: False> failed
---------------------
This is the problematic behaviour
------------------------
ERROR 2024-01-03T19:38:56.091734160Z [2024-01-03 19:38:56,079] {dag.py:1354} ERROR - failed to invoke dag state update callback
```

### What you think should happen instead

This should log an error and execute the corresponding failure callbacks defined in the DAG file

### How to reproduce

1. Create any DAG and use `DataflowStartFlexTemplateOperator` with 
2. Cancel the Dataflow Job
3. Check the status on Airflow, the Job would be failed the above errors would appear in the logs

### Anything else

I have tried using the code for `hooks/dataflow.py` & `operators/dataflow.py`  in the main branch, 2.8.0 branch and the behaviour is the same. This was not the case a month ago (unsure if Google Cloud has updated the providers internally)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by themitigater** [comment]
This is my DAG File

```python
from airflow.models import DAG
from utils.helpers import analytical_pipeline_params, dataflow_request, dag_start_date
from operators.dataflow_staging import (
    DataflowStartFlexTemplateOperator,
)
from airflow.hooks.base_hook import BaseHook
from hooks.failure_hook import failure_hook

name = "some-"
env = "staging"

ENV_PREFIX = ""
if env != "prod":
    ENV_PREFIX = f"{env}-"


JOB_NAME_SUFFIX = (
    "{{macros.ds_format(data_interval_start,'%Y-%m-%dT%H:%M:%S%z','%Y%m%d-%H%M%S')}}"
)
JOB_NAME_SUFFIX += "-" + "{{task_instance.try_number}}"

params = analytical_pipeline_params(ENV_PREFIX, BaseHook, 30, 0, 0, env)
request_params = dataflow_request(ENV_PREFIX, name, JOB_NAME_SUFFIX)

body = request_params["body"]
default_args = {"start_date": dag_start_date(days=2)}

with DAG(
    f"dataflow_dag-{ENV_PREFIX}{name}",
    params=params,
    default_args=default_args,
    is_paused_upon_creation=True,
    tags=[env, "AssistedVideo", "VS", "Analytical", "Hourly"],
    schedule_interval="5,35 4-15 * * 1-5",
    on_failure_callback=failure_hook,
) as dag:
    parameters = {
        "clickhouseURL": "{{params.clickhouseURL}}",
        "minutes": "{{ params.minutes }}",
        "hours": "{{ params.hours }}",
        "days": "{{ params.days }}",
        "startTime": "{{ data_interval_start - macros.timedelta(minutes=5) if dag_run.run_type != 'manual' else params.startTime }}",
    }

    body["launchParameter"]["parameters"] = parameters

    start_template_job = DataflowStartFlexTemplateOperator(
        task_id=f"dataflow_operator-{ENV_PREFIX}{name}",
        project_id=request_params["project"],
        location=request_params["region"],
        body=body,
        wait_until_finished=True,
        dag=dag,
        do_xcom_push=False,
    )

if __name__ == "__main__":
    dag.test()

```

**Comment by themitigater** [comment]
On checking the code for hooks from [airflow 2.5.3](https://github.com/apache/airflow/blob/2.5.0/airflow/providers/google/cloud/hooks/dataflow.py#L388), it seems like it always used to raise, not sure if anything has changed in how Airflow handles it now. 

I am happy to help triage and fix this if someone can guide me on where to start.

**Comment by RNHTTR** [comment]
> On checking the code for hooks from [airflow 2.5.3](https://github.com/apache/airflow/blob/2.5.0/airflow/providers/google/cloud/hooks/dataflow.py#L388), it seems like it always used to raise, not sure if anything has changed in how Airflow handles it now.
> 
> I am happy to help triage and fix this if someone can guide me on where to start.

First step would be to reproduce. From there, it will be much easier to step through the code and identify the root cause of the issue.

**Comment by themitigater** [comment]
> > On checking the code for hooks from [airflow 2.5.3](https://github.com/apache/airflow/blob/2.5.0/airflow/providers/google/cloud/hooks/dataflow.py#L388), it seems like it always used to raise, not sure if anything has changed in how Airflow handles it now.
> > I am happy to help triage and fix this if someone can guide me on where to start.
> 
> First step would be to reproduce. From there, it will be much easier to step through the code and identify the root cause of the issue and implement a fix.

Can you tell me where to look first? I looked at `dag.py:1354` and `dagrun.py` as per the stacktrace, but haven't found anything concrete.

**Comment by themitigater** [comment]
I have made some progress here, it seems like something inside my custom hook is failing and the exception is being caught by the said lines `dag.py:1354`. This doesn't seem to be an issue with Airflow or Composer at the moment. I will close the ticket.
