### ISSUE TITLE
Align the run type icon in line with text in grid view

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#36574]
### Apache Airflow version

main (development)

### What happened?

The run type icon and the text next to it seem to have a small gap which makes them look as if they are out of alignment.
![example_pic](https://github.com/apache/airflow/assets/35884252/190b3f40-bad8-44a0-8eb1-dec6f3b9b1ea)

### What you think should happen instead?

We should be looking at aligning both of these together

### How to reproduce

1. Create a DAG
2. Run the DAG
3. From DAG Runs -> Grid View
4. Click on the grid pertaining to the DAG run and see the "Details" tab

### Operating System

MacOS

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
cc @bbovenzi @pierrejeambrun

**Comment by amoghrajesh** [comment]
@potiuk @eladkal do you think this is a valid issue?

Trying to understand what the process for some issue existing forever is here

**Comment by potiuk** [comment]
The process of dealing with issues is described in https://github.com/apache/airflow/blob/main/ISSUE_TRIAGE_PROCESS.rst 

I think there is no way two of us can be called for every issue to decide whether issues are valid or not and I do not think it is necessary - but if you think the issue triage process we have can be improved, I think starting with what we have is a good place.

**Comment by amoghrajesh** [comment]
Thanks for the tip @potiuk

I was trying to understand the process around trying to fix issues that have been part of the design for really long, the tag shouldve been in the below paragraph, my bad.

The tag was not for asking if the issue was valid but rather for the question below. My typo there, apologies

**Comment by amoghrajesh** [comment]
Nope it's ok. I understood it myself!

Apologies for the tag
