### ISSUE TITLE
SnowflakeSqlApiOperator does not support OAuth 

### ISSUE THREAD

**Issue by erdos2n** [apache/airflow#36621]
### Description

There are 2 methods for Authenticating to Snowflake: `OAUTH` and `KEYPAIR_JWT`

Currently the only supported auth method is `KEYPAIR_JWT`. It would be great to have OAUTH as an option, as well.

https://github.com/apache/airflow/blob/c47dcc59e5a0766d6b390bc8ceafc8ab6b762c88/airflow/providers/snowflake/hooks/snowflake_sql_api.py#L197 

### Use case/motivation

Add more flexibility to Snowflake Authentication

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ighoshsubho** [comment]
I would like to work on this issue, please assign it to me.

**Comment by aritra24** [comment]
Sure @ighoshsubho, assigning it to you
