### ISSUE TITLE
[Performance] Too many calls against timetable when clicking a task instance

### ISSUE THREAD

**Issue by mujiannan** [apache/airflow#36671]
### Description

Click any scheduled task instance for task_instance_info, `confirm` api spend long-time responding, even failing.  
### Reproduce
1. Click any scheduled task instance for task_instance_info  
2. A `confirm` GET request will be sent and processed along following chain:   
    `confirm -> set_state -> confirmed_infos = list(_iter_existing_dag_run_infos(dag, dag_run_ids, session=session)) -> dag.iter_dagrun_infos_between -> next_dagrun_info{{ ! again and again...}}`
If the DAG have an intensive schedule strategy, above calls against timetable will spend very long time, which is performance consuming.  
Especially, when you use a custom timetable, that'll be terrible(CPU, memory, and time).

### Reference
1. Request headers  
```
Request URL: <airflow-web-ingress>/confirm?dag_id=<dag_id>&dag_run_id=<dag_run_id>&past=false&future=false&upstream=false&downstream=false&state=success&task_id=<task_id>
Request Method: GET
```
2. Codes
airflow/www/views.py:  
```python
    def confirm(self):
        ...
        to_be_altered = set_state(
            tasks=tasks,
            run_id=dag_run_id,
            upstream=upstream,
            downstream=downstream,
            future=future,
            past=past,
            state=state,
            commit=False,
        )
        ...
```
airflow/api/common/mark_tasks.py:  
```python
def set_state(
    ...
    dag_run_ids = get_run_ids(dag, run_id, future, past, session=session)
    ...
def get_run_ids(...
    ...
    if not dag.timetable.can_be_scheduled:
    ...
    else:
        dates = [
            info.logical_date for info in dag.iter_dagrun_infos_between(start_date, end_date, align=False)
        ]
        run_ids = [dr.run_id for dr in DagRun.find(dag_id=dag.dag_id, execution_date=dates, session=session)]
    ...
```
airflow/models/dag.py:  
```python
    def iter_dagrun_infos_between(...
        ...
        # Generate naturally according to schedule.
        while info is not None:
            yield info
            try:
                info = self.timetable.next_dagrun_info(
                    last_automated_data_interval=info.data_interval,
                    restriction=restriction,
                )
            except Exception:
                self.log.exception(
                    "Failed to fetch run info after data interval %s for DAG %r",
                    info.data_interval if info else "<NONE>",
                    self.dag_id,
                )
                break
```

### Questions
1. Why a confirm `GET` request send to backend when I click a task_intance?  
2. Is it *necessary* / *reasonable* to call `set_state` to get task_instance_info?
3. Is it necessary to iterate all data_interval?  
4. Can we get task_instance_info from database directly?

### Potential solutions
1. Remove `confirm` call when clicking task_instance to get task_instance_info?  
2. Introduce a new `get_state` function?  
4. First query database for dag_run_info and task_instances, then call timetable.next_dag_info?

Too confused to create a PR😥.

### Use case/motivation

Reduce calls to timetable when confirm a task_instance_info.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
This smells like being related to #36119
