### ISSUE TITLE
Bulk Variable Updates to allow transactional rollbacks

### ISSUE THREAD

**Issue by NathanielRose** [apache/airflow#36694]
### Description

Currently we have to iterate through variables in a json file to be able to upload new values. We should have a native way to simply hand off the JSON file to set all variables and have Airflow manage the iteration so its able to rollback in case of a failure.

### Use case/motivation

Hoping to achieve transactional rollback.
- Modifying these methods here -https://github.com/apache/airflow/blob/9cb2052810a8a4b191e77d804fc79927f046c8bb/airflow/cli/commands/variable_command.py#L62 

- A new option to take in a json instead of each value pair

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment]
Is this not achieved with [this](https://github.com/apache/airflow/blob/9cb2052810a8a4b191e77d804fc79927f046c8bb/airflow/cli/commands/variable_command.py#L79)?

**Comment by aritra24** [comment]
Closing this since it already exists
