### ISSUE TITLE
Could access template system in PythonOperator

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#367]
In some cases. I had to use PythonOperator to replace MySQLOperator or HiveOperator.
We cannot use the template of SQL in PythonOperator. We have to use other logic to access template file and replace the variable.

Could we provide the templates and template_ext in Init task, and get the rendered content in python_callback?

**Comment by griffinqiu** [comment]
I tried use a plugin to fix it, however, it is not work for common. We could not override the class attribute in initialization.

``` python
import logging

from airflow.operators import PythonOperator
from airflow.utils import apply_defaults
from airflow.plugins_manager import AirflowPlugin

class PythonWithTemplatesOperator(PythonOperator):
    # template_fields = ('foo', 'bar')
    # template_ext = ('.sql')
    @apply_defaults
    def __init__(
            self,
            templates = dict(),
            template_ext = tuple(),
            *args, **kwargs):
        self.templates = templates
        for k in self.templates.keys():
            setattr(self, k, self.templates[k])
        self.__class__.template_fields = tuple(self.templates.keys())
        self.__class__.template_ext = template_ext
```

**Comment by mistercrunch** [comment]
Oh nice. Here's my take on it: https://github.com/airbnb/airflow/pull/369

**Comment by griffinqiu** [comment]
Thank you. Let's merge to release version and close it ; ))
