### ISSUE TITLE
Support writing custom DAG tags in metrics

### ISSUE THREAD

**Issue by cbuffett** [apache/airflow#36704]
### Description

With the ability to include tags for both Datadog and Telegraf metrics, it doesn't currently appear possible to include any custom tags defined on the DAG as part of those metrics. Telegraf for instance, supports including arbitrary key/value pairs as part of the metric name, but the set of tags that are included are limited, e.g., TaskInstance includes only `dag_id` and `task_id`

### Use case/motivation

We include several metadata tags in our DAGs that we'd like to use as filters within our TIG stack, for example things like environment or stakeholder. One idea would be to modify DAG tags to add support for a dictionary and then use those tags wherever metrics are emitted.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirrao** [comment]
@cbuffett 
Yes, this is a good idea.

**Comment by dirrao** [comment]
@cbuffett 
It is a big feature request and it requires a discussion. So, converting it to a discussion.
