### ISSUE TITLE
Apache Airflow "latest" image is still Python 3.8 in Airflow 2.8.0 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#36740]
### Body

Despite what is documented in [Changelog](https://airflow.apache.org/docs/docker-stack/changelog.html) and what we agreed in [the lazy consensus](https://lists.apache.org/thread/0oxnvct24xlqsj76z42w2ttw2d043oy3 ) , the default docker imagest (latest/latest-slim) are still pointing to Python 3.8.

The changelog should be corrected and that move should happen in Airflow 2.9

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Looks strange.. It looks like the code is there and fixed .... puzzled a bit... But I will find out.

**Comment by hussein-awala** [comment]
Good catch! but yeah, it's very strange. Based in the CI log, it should be ok:
```
Replacing latest images with links to the newly created images.
Creating apache/airflow:latest-python3.11 alias for apache/airflow:2.8.0-python3.11
Running command: <regctl image copy apache/airflow:2.8.0-python3.11 apache/airflow:latest-python3.11>
  
  Working directory /home/runner/actions-runner/_work/airflow/airflow
  
  
  regctl image copy --force-recursive --digest-tags apache/airflow:2.8.0-python3.11 apache/airflow:latest-python3.11
  
Creating apache/airflow:latest alias for apache/airflow:2.8.0
Running command: <regctl image copy apache/airflow:2.8.0 apache/airflow:latest>
  
  Working directory /home/runner/actions-runner/_work/airflow/airflow
  
  
  regctl image copy --force-recursive --digest-tags apache/airflow:2.8.0 apache/airflow:latest
```
I checked the sha256 of the images we released one month ago to ensure that it is not a new issue, but it looks like we had the same issue with the RC images.

**Comment by potiuk** [comment]
Ah... I know .. my mistake. If you look here - it only changese at which python version the "2.8.0" alias points to latest one. There is no `python` used in this if, so the only thing it change is when `latest` becomes aliased to`2.8.0`.

```
            if python == ALLOWED_PYTHON_MAJOR_MINOR_VERSIONS[-1]:
                # only tag latest "default" image when we build the latest allowed python version
                if slim_images:
                    alias_image(
                        f"{dockerhub_repo}:slim-{airflow_version}",
                        f"{dockerhub_repo}:slim-latest",
                    )
                else:
                    alias_image(
                        f"{dockerhub_repo}:{airflow_version}",
                        f"{dockerhub_repo}:latest",
                    )
```

But what **should** be changed is the line before that:

```
            if python == DEFAULT_PYTHON_MAJOR_MINOR_VERSION:
                alias_image(image_name, f"{dockerhub_repo}:{airflow_version}")
```

(and similar one in slim image) - > because THERE the "airflow:2.8.0-python3.8" gets the `airflow:2.8.0` alias - which what it was about.

I will announce it at devlist that we are delaying it and remove the log in dockerfile changelog.
