### ISSUE TITLE
CLEAR task instance Privilege changed?

### ISSUE THREAD

**Issue by Leo4ML** [apache/airflow#36783]
### Apache Airflow version

2.8.0

### What happened?

I created a user named data_user with base_adm and data_adm role privileges.
base_adm:
can read on Website, 
can read on DAG Runs, 
can read on Task Instances, 
can read on DAG Code, 
can read on Task Logs, 
can read on My Profile, 
can read on Audit Logs, 
can create on Task Instances, 
can edit on Task Instances,
can delete on Task Instances
data_adm:
can edit on DAG:WF_DATA_FLOW,
can read on DAG:WF_DATA_FLOW
It worked on Airflow 2.7.3, data_user can only manage DAG WF_DATA_FLOW and can't not access other DAG.I do not change anything, but it doesn't work on Airflow 2.8.0. On Airflow 2.8.0, I clear WF_DATA_FLOW's task, web go to blank.
<img width="2510" alt="image" src="https://github.com/apache/airflow/assets/32268546/8b302fbc-e42d-42b1-915e-53197e7f3d18">

I readed Airflow 2.8.0 release note and not find anything about privileges changed content.
So, I think it's a bug.

### How to reproduce

I don't know how to reproduce on Airflow 2.8.0.

### Operating System

CentoOS7.6

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Leo4ML** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by vatsrahul1001** [comment]
I am able to reproduce it, looks like an issue

**Comment by potiuk** [comment]
cc: @vincbeck

**Comment by vincbeck** [comment]
I cannot reproduce it (not fully at least). With the same configuration I can access to the DAG page (`/dags/<dag_id>/grid` and `/dags/<dag_id>/grid?tab=graph`). I can see the list of tasks. When I click on "Clear existing tasks", it does not work though, I dont have any blank page but the API fails, I am looking into it but I wanted to make sure this is the bug you are reporting and not something else. When does the blank page happen? After clicking on "Clear existing tasks"?

**Comment by vincbeck** [comment]
I fount out the issue regarding clearing tasks. In https://github.com/apache/airflow/pull/34317#discussion_r1355917769, we agreed to convert task instances to task instance + dag runs. So here, when clicking on "Clear existing tasks", the endpoint is protected wth `@auth.has_access_dag("PUT", DagAccessEntity.TASK_INSTANCE)` which means: does the user has permissions to edit task instances (actually, should not it be "delete"?). But now we are converting DagAccessEntity.TASK_INSTANCE to task instances + dag runs, we are checking whether the user has permissions to edit task instances and dag runs. In this case, the user does not have permission to edit dag runs, thus no task gets clearer.

What should we do here? I dont think we should modify the code, what we did in https://github.com/apache/airflow/pull/34317#discussion_r1355917769 is not backward compatible but this is a bug fix. I would encourage you to give permissions to edit dag runs to your user. Should I create a PR to check whether the user has permissions to `delete` task instances (instead of `put`) [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2364)?

**Comment by potiuk** [comment]
Yep. This is a bug fix. The permissions of the user/role should be updated  in your case @Leo4ML  as they were wrong in the first place.

**Comment by Leo4ML** [comment]
> I cannot reproduce it (not fully at least). With the same configuration I can access to the DAG page (`/dags/<dag_id>/grid` and `/dags/<dag_id>/grid?tab=graph`). I can see the list of tasks. When I click on "Clear existing tasks", it does not work though, I dont have any blank page but the API fails, I am looking into it but I wanted to make sure this is the bug you are reporting and not something else. When does the blank page happen? After clicking on "Clear existing tasks"?

Thank you for replaying！With the configuration I can access to the DAG pag and see the list of tasks.Like below

**Comment by Leo4ML** [comment]
> I fount out the issue regarding clearing tasks. In [#34317 (comment)](https://github.com/apache/airflow/pull/34317#discussion_r1355917769), we agreed to convert task instances to task instance + dag runs. So here, when clicking on "Clear existing tasks", the endpoint is protected wth `@auth.has_access_dag("PUT", DagAccessEntity.TASK_INSTANCE)` which means: does the user has permissions to edit task instances (actually, should not it be "delete"?). But now we are converting DagAccessEntity.TASK_INSTANCE to task instances + dag runs, we are checking whether the user has permissions to edit task instances and dag runs. In this case, the user does not have permission to edit dag runs, thus no task gets clearer.
> 
> What should we do here? I dont think we should modify the code, what we did in [#34317 (comment)](https://github.com/apache/airflow/pull/34317#discussion_r1355917769) is not backward compatible but this is a bug fix. I would encourage you to give permissions to edit dag runs to your user. Should I create a PR to check whether the user has permissions to `delete` task instances (instead of `put`) [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2364)?
After giving permissions to edit dag runs to my user，it works : )
The content should in 2.8.0 release note.

**Comment by Leo4ML** [comment]
> edit dag runs to my user，it works : )

Yes，give permissions to edit dag runs to my user，it works : )

**Comment by Leo4ML** [comment]
> Yep. This is a bug fix. The permissions of the user/role should be updated in your case @Leo4ML as they were wrong in the first place.

Yes，give permissions to edit dag runs to my user，it works : )

**Comment by vatsrahul1001** [comment]
marking this close @Leo4ML as this works after adding edit dag runs permission
