### ISSUE TITLE
Variables create API does not accept description

### ISSUE THREAD

**Issue by ryandutton** [apache/airflow#36811]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

Using the swagger REST API "Try It Out" feature accepts description as a field and once submitted will return the description, however, on viewing the variable in the UI I can see the description has not been set.

### What you think should happen instead?

The description should be added to the variable on creation.

### How to reproduce

Attempt to create a variable using the following endpoint `/api/v1/ui/#/Variable/post_variables` and it will return the variable description. Then go to the variables page in the UI, search for your new variable and you will see no description has been created.

### Operating System

Centos 8

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
I check on the main and this bug still persists
