### ISSUE TITLE
Webserver redirects to main page when user is not logged in

### ISSUE THREAD

**Issue by csp33** [apache/airflow#36832]
### Apache Airflow version

2.8.0

### What happened?

When opening the log of a specific Airflow DAG/log/whatever (like `<my airflow host>/log?execution_date=<date>&task_id=<task_id>&dag_id=<dag_id>&map_index=<map_index>`), the user is redirected to the login page if he's not logged in.
However, when the login is performed, the homepage of the webserver is shown, instead of the URL that was initially opened.

### How to reproduce

1. Enter into Airflow and copy the URL of a specific DAG (i.e `<my host>/dags/<my_dag>/grid`).
2. Log out
3. Paste the URL you copied -> you'll be redirected to the login page.
4. Login
5. See how you'll be redirected to the home page.

### Operating System

Docker image

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

I found out that this logic is implemented in https://github.com/apache/airflow/blob/13b0930bf45faece076ef1b0c4e6fd14f2b17e16/airflow/providers/fab/auth_manager/fab_auth_manager.py#L349
https://github.com/apache/airflow/blob/13b0930bf45faece076ef1b0c4e6fd14f2b17e16/airflow/providers/fab/auth_manager/fab_auth_manager.py#L354
However, we're calling this function using `next`
https://github.com/apache/airflow/blob/13b0930bf45faece076ef1b0c4e6fd14f2b17e16/airflow/www/auth.py#L119

Changing `next` to `next_url` should do the trick 😄 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by foldvari** [comment]
I still see the same issue in Airflow 2.8.4
But if I replace 'next_url' by 'next' in the URL then it starts working.

**Comment by vincbeck** [comment]
What version of provider are you using? I guess the fixes you are looking for are here: #37225 and #37904

**Comment by foldvari** [comment]
> What version of provider are you using? I guess the fixes you are looking for are here: #37225 and #37904

Thanks, it seems #37904 addresses the issue. Which version will have this fix?

**Comment by vincbeck** [comment]
#37904 is a provider change so it is not a matter of Airflow version, it is a matter for fab provider version. I cannot see from the PR which version of FAB provider it is in but if you use the last, it should fix your issue. https://pypi.org/project/apache-airflow-providers-fab/
