### ISSUE TITLE
Triggering DAG with parameters is mandatory when  show_trigger_form_if_no_params is enabled

### ISSUE THREAD

**Issue by csp33** [apache/airflow#36843]
### Apache Airflow version

2.8.0

### What happened?

When setting `show_trigger_form_if_no_params` to True, users can not trigger DAGs without configuration. The `Trigger DAG` button redirects to the `Trigger DAG` form instead of triggering the DAG with `dagrun_conf={}` (like before)

https://github.com/apache/airflow/assets/28935464/62083be1-1330-4f75-8e47-848c36f99abb

### What you think should happen instead?

The `Trigger DAG` button should trigger the DAG with `dagrun_conf={}` (like before).
The `Trigger DAG w/ config` button should keep its behavior.

### How to reproduce

1. Add a DAG without params to your DAGs folder (for example, example_bash_operator.py).
2. Start Airflow with the following environment variable value: `AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True`
3. Try to trigger the DAG without config (first option)

### Operating System

Airflow Docker Image

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Good catch. It seems this slipped through the tests when we tried to fix the XSS problem of the trigger with the referenced commit.
Also this bug is in 2.8.1. If nobody jumps on this, I could try to fix this in the next weeks.

**Comment by wilk85** [comment]
Hello, where i need to set show_trigger_form_if_no_params? 
and also i have no trigger with config in 2.7.3 enveironment varaible AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS as True is not helping

**Comment by jscheffl** [comment]
Hi,

You need to set it as described here: https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#show-trigger-form-if-no-params

Either in airflow.cfg, section webserver or via ENV before starting webserver.

Mit freundlichen Grüßen / Best regards

Jens Scheffler

Alliance: Enabler - Tech Lead (XC-AS/EAE-ADA-T)
Robert Bosch GmbH | Hessbruehlstraße 21 | 70565 Stuttgart-Vaihingen | GERMANY | www.bosch.com<http://www.bosch.com/>
Tel. +49 711 811-91508 | Mobil +49 160 90417410 | ***@***.******@***.***>

Sitz: Stuttgart, Registergericht: Amtsgericht Stuttgart, HRB 14000;
Aufsichtsratsvorsitzender: Prof. Dr. Stefan Asenkerschbaumer;
Geschäftsführung: Dr. Stefan Hartung, Dr. Christian Fischer, Dr. Markus Forschner,
Stefan Grosch, Dr. Markus Heyn, Dr. Tanja Rückert
​

**Comment by wilk85** [comment]
@jscheffl thank you, im using helm charts, and i was wondering which annotation would be right and where exactly to add that env variable, i was testing with env: envVars, extraEnvVars

**Comment by jscheffl** [comment]
> @jscheffl thank you, im using helm charts, and i was wondering which annotation would be right and where exactly to add that env variable, i was testing with env: envVars, extraEnvVars

Please take a look to https://airflow.apache.org/docs/helm-chart/stable/airflow-configuration.html
Probably (never tried myself) you need to set the following in your values.yaml:
```
config:
  webserver:
    show_trigger_form_if_no_params: 'True'
```
