### ISSUE TITLE
Copy button on a Dag run's config copies only one run config

### ISSUE THREAD

**Issue by anteverse** [apache/airflow#36848]
### Apache Airflow version

2.8.0

### What happened?

Hi, I believe I hit a case where the run config that's exported when we click "Copy" does not seem to be updated when we switch from one run to another in the UI.
The copied json of the run config is always the same.

### What you think should happen instead?

I believe the content of the copy should match the right run, and be updated as we switch runs.

Little bit of a clue: being on one run view, if I refresh the page, then I can copy the right json.

### How to reproduce

Have this DAG for instance:
```python
with DAG(
    dag_id="issue_copy_button",
    schedule=None,
    catchup=False,
    start_date=pendulum.today("UTC").add(days=-1),
    params={
        "list_of_strings": Param(
            [],
            type="array",
            title="List of strings",
            items={"type": "string"},
        ),
    },
) as dag:

    @task
    def my_task() -> None:
        print("Task done")

    my_task()
```

Now in the UI:
1. trigger a first run with: `["a", "b", "c"]` then a second run with `["d", "e", "f"]`.
2. open the last run. Press "Copy" on the run config. You get the json of the set of values for this run, hence `{"list_of_strings": ["d", "e", "f"]}`
3. now open the other run (on the left panel). Press "Copy" on the run config. You will still get the same json as before, hence `{"list_of_strings": ["d", "e", "f"]}` instead of `{"list_of_strings": ["a", "b", "c"]}` which matches the currently opened run.

Tested in 2.8.0 and 2.7.3.

Let me know you need more details or if there's anything I should do differently. I could not find a matching existing issue, but feel free to close if there's one.

Thank you!

<img width="1655" alt="Screenshot 2024-01-17 at 17 20 14" src="https://github.com/apache/airflow/assets/13581591/e43b4c80-e8b8-40ae-b5ed-58b3669028a6">

### Operating System

Airflow on Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
I guess it similar to https://github.com/apache/airflow/issues/34846 and might be even fixed by https://github.com/apache/airflow/pull/34904

**Comment by Taragolis** [comment]
Well nope, it still persists in current `main`

**Comment by anteverse** [comment]
Thanks a lot, looking forward to the next releases.
