### ISSUE TITLE
SECURITY_MANAGER_CLASS not being picked up in webserver_config.py

### ISSUE THREAD

**Issue by CharlieJ15420** [apache/airflow#36875]
### Apache Airflow version

2.8.0

### What happened?

I've just upgraded from 2.7.3 to 2.8.0 and have my own custom security manager. This custom security manager inherited from AirflowSecurityManager. Now I've upgraded to 2.8.0 I've altered my security manager to inherit from FabAirflowSecurityManagerOverride. Despite this, my custom security manager isn't being picked up. I've made no changes to webserver_config.py where I've specified the SECURITY_MANAGER_CLASS. It should pick up my custom sec manager via this line: https://github.com/apache/airflow/blob/2.8.0/airflow/auth/managers/fab/fab_auth_manager.py#L340 however when I try to login, not only do I get invalid login but the errors in the logs are coming from override.py (where the base FabAirflowSecurityManagerOverride lives) compared to my customsecuritymanager.py. I'm not sure if something else has changed that I need to alter or if there is a bug somewhere that isnt picking up my custom security manager class.

note: I'm also using the default fab auth manager

### What you think should happen instead?

My custom security manager should be picked up and used. I've verified it's not being picked up by putting in an incorrect name which in the past has produced an error.

### How to reproduce

Try to set your own SECURITY_MANAGER_CLASS in webserver_config.py and inherit from FabAirflowSecurityManagerOverride.

### Operating System

CentOS7

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
CC @vincbeck

**Comment by CharlieJ15420** [comment]
Even if I put the entire custom security manager class in webserver_config.py it still doesn't pick it up. I can see webserver_config.py is in the correct dir once deployed too.

**Comment by Taragolis** [comment]
Is it similar to:
- https://github.com/apache/airflow/issues/36342
- https://github.com/apache/airflow/pull/36343

???

**Comment by CharlieJ15420** [comment]
Not quite, as the webserver starts fine - it's just not picking up my custom security manager at all.

**Comment by potiuk** [comment]
Can you share your webserver_config.py ? Maybe you have a typo there of some sort ?

**Comment by vdozal** [comment]
Hi @CharlieJ15420, did you solve this issue? I'm having the same, I added log messages and don't see them, plus I get this message when trying to login:
**The request to sign in was denied.**

**Comment by WRinnovation** [comment]
While migrating from 2.4.0 to 2.10.0 I noticed that in the Webserver [documentation](https://airflow.apache.org/docs/apache-airflow/2.8.0/security/webserver.html) of 2.8.0 it used SECURITY_MANAGER_CLASS instead of the [previous version](https://airflow.apache.org/docs/apache-airflow/2.7.0/security/webserver.html) FAB_SECURITY_MANAGER_CLASS, in addition to using the new class FabAirflowSecurityManagerOverride.

Changing this is what fixed it for me, altough I did not find an official migration guide stating this
