### ISSUE TITLE
apache-airflow-providers-mongo does not disable SSL/TLS correctly

### ISSUE THREAD

**Issue by NoahStapp** [apache/airflow#36881]
### Apache Airflow Provider(s)

mongo

### Versions of Apache Airflow Providers

apache-airflow-providers-mongo version 3.4.0

### Apache Airflow version

2

### Operating System

macOS 14.2.1

### Deployment

Other

### What happened

The MongoHook URI generator does not disable SSL/TLS correctly. When the `ssl` option is set to `False`, it sets the PyMongo option `ssl_cert_reqs=CERT_NONE` or `tlsAllowInvalidCertificates=True`, depending on the available PyMongo version. `ssl_cert_reqs` and `tlsAllowInvalidCertificates` do not actually disable SSL/TLS inside PyMongo, causing the following error when combined with `srv=True`:

`Can not specify conflicting values for URI options ssl and tls.`

This is confusing, as I would expect setting `ssl=False` actually disables SSL rather than disabling cert verification. 

### How to reproduce

Set up a MongoDB connection using apache-airflow-providers-mongo with the following arguments: 

`{"login": "admin", "password": "test", "host": "mymongo", "schema": "admin", "extras": {"srv": True, "ssl": False}}`

This will result in the error described above.

### Anything else

This issue occurs whenever a user attempts to disable SSL while using an SRV connection string with apache-airflow-providers-mongo.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
@NoahStapp this might be related to https://github.com/apache/airflow/pull/37214. It has been fixed now

**Comment by eladkal** [comment]
Closing as fixed in https://github.com/apache/airflow/pull/37214 we can always reopen if someone reports otherwise
