### ISSUE TITLE
Support for configmaps (as env var & volume) in the template fields in the KubernetesPodOperator

### ISSUE THREAD

**Issue by vizeit** [apache/airflow#36888]
### Description

Currently configmaps are not supported in the template fields in the KubernetesPodOperator. It will be helpful to add this support to dynamically attach configmaps to a pod 

### Use case/motivation

Currently configmaps are not supported in the template fields in the KubernetesPodOperator. It will be helpful to add this support to dynamically attach configmaps to a pod 

**I have made the code changes locally and also added unittests. I have also run all the Kubernetes provider unit tests after the changes**

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Do KubernetesPodOperator's existing parameters [volumes](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/pod.py#L121) and [configmaps](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/pod.py#L175) not suffice?

**Comment by vizeit** [comment]
Also to add, I have been able to extend k8 operator to accommodate configmap as a volume with templated values, not as environment variables. I did that last year with pvcs before the pvcs were added to template fields. The reason I think it will help to add configmap template functionality rather in the k8 provider package is because decorator also uses k8 operator and I am not sure I can easily add template fields to k8 decorator without creating custom provider package for k8 that has extended k8 operator class. I hope these details will help you to understand better

**Comment by RNHTTR** [comment]
Sounds good. I assigned the Issue to you. Feel free to open a PR! The [Contributors Quickstart Guide](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst) might be helpful, and feel free to [reach out on slack](https://apache-airflow-slack.herokuapp.com/).

> The reason I think it will help to add configmap template functionality rather in the k8 provider package is because decorator also uses k8 operator and I am not sure I can easily add template fields to k8 decorator without creating custom provider package for k8 that has extended k8 operator class.

Wouldn't the template fields be added to the [KubernetesPodOperator in the Kubernetes provider package](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/pod.py#L213)?

**Comment by vizeit** [comment]
Yes, the change will only be in the KubernetesPodOperator class in the Kubernetes provider package. I meant to say in my comment that if I wanted to incorporate additional template fields in the k8 decorator myself in my project, I could not do it unless I first created custom k8 operator class with those additional template fields and then creating custom k8 decorator in a custom provider package. I hope this clarifies
