### ISSUE TITLE
Request for Inclusion of Horizontal Pod Autoscaling (HPA) Option in KubernetesPodOperator

### ISSUE THREAD

**Issue by codeprasan** [apache/airflow#36932]
### Description

In the current Airflow version, the KubernetesPodOperator allows users to specify computer resources, but these resources are distributed across nodes. Unfortunately, there is a shortage of available nodes, leading to resource constraints. It would be advantageous to introduce an option for Horizontal Pod Autoscaling (HPA) for this operator. Currently, Airflow, through the KubernetesPodOperator, generates a new pod dynamically for each execution. However, the implementation of HPA/Replicas is hindered by a missing feature or property in the existing operator. The addition of an HPA option would address this limitation and enhance the scalability of the operator.

### Use case/motivation

In our Airflow setup, we aim to trigger Spark jobs, but the absence of Horizontal Pod Autoscaling (HPA) functionality in the KubernetesPodOperator poses a challenge. The current operator lacks the capability to leverage HPA for dynamic scaling, hindering our ability to efficiently scale resources based on workload demands. This limitation impacts the scalability and performance optimization of Spark jobs within the Airflow environment. Introducing HPA support to the KubernetesPodOperator would be instrumental in addressing this issue and enhancing the overall scalability and flexibility of our Spark job execution.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
the KPO start a pod , that's all and will always

use the `KubernetesCreateResourceOperator` to start something like a `RayJob` or `SparkApplication`
