### ISSUE TITLE
Add CLI support for bulk pause and resume of DAGs

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#36956]
### Description

Allow Airflow CLI's `dag` subcommands , `pause` and `unpause`, to support multiple DAG IDs instead of only one.

### Use case/motivation

There are cases where we would like to pause or resume multiple DAGs at once. As a Cloud Composer user - I'd like to do both, for example, before and after [upgrading](https://cloud.google.com/composer/docs/composer-2/upgrade-environments#upgrade_your_environment) an environment, in correspondence. The current methods of doing it, at least in Cloud Composer, are manually via the UI (not scalable), via Airflow API using `dag_id_pattern` (not easily accessible, at least in CC), or one-by-one via the CLI - most straightforward to perform, but only supports one DAG id per run (considering the extra overhead for accessing the CC's GKE - it could take up to a minute to pause or unpause each DAG!).

### Possible Caveats
#32360 - as `dag_id_pattern` might be changed in Airflow's API - the method for passing multiple DAG ids should be considered.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by enchant3dmango** [comment]
@shahar1 @potiuk I think [this feature request](https://github.com/apache/airflow/issues/36994) could be developed along with the PR for this feature.

**Comment by potiuk** [comment]
> @shahar1 @potiuk I think [this feature request](https://github.com/apache/airflow/issues/36994) could be developed along with the PR for this feature.

Or separately. There is no particular reasons to bundle such things together, the smaller the scope of the PR, the higher chance someone will complete it and the faster it goes through review.
