### ISSUE TITLE
We use workers with Fargate, but there's a problem

### ISSUE THREAD

**Issue by 5pponent** [apache/airflow#36967]
### Description

When running tasks on Fargate, we need to make sure that capacity provisioning can be done on a per-task basis. Also, it would be nice to have multiple tasks running on one Fargate node, but only one task running on one node.

### Use case/motivation

It's time to go serverless.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
airflow desn't have the feature of kubernetes , airflow do not know and check the requirements of tasks
