### ISSUE TITLE
404:  https://github.com/apache/airflow/blob/main/dev/breeze/doc/dev/MANUALLY_GENERATING_IMAGE_CACHE_AND_CONSTRAINTS.md

### ISSUE THREAD

**Issue by lewijw** [apache/airflow#36987]
### What do you see as an issue?

The link entitled "Manually generating image cache and constraints" is broken:
https://github.com/apache/airflow/blob/main/dev/breeze/doc/09_release_management_tasks.rst#generating-constraints

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Thanks! Fix in https://github.com/apache/airflow/pull/36988
