### ISSUE TITLE
Configuration file issue, plugin folder key name not specified in configuration file.

### ISSUE THREAD

**Issue by vi3k6i5** [apache/airflow#37]
### System details:

Description:    Ubuntu 15.04
Linux my-pc 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
### Steps to reproduce:

I cloned the repo and tried the quick start steps : http://pythonhosted.org/airflow/start.html

got error at the following step:

$ airflow initdb
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 3, in <module>
    from airflow.bin.cli import get_parser
  File "/usr/local/lib/python2.7/dist-packages/airflow/**init**.py", line 10, in <module>
    from airflow.configuration import conf
  File "/usr/local/lib/python2.7/dist-packages/airflow/configuration.py", line 276, in <module>
    conf.read(AIRFLOW_CONFIG)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /home/viki/airflow/airflow.cfg
    [line 32]: '/home/viki/airflow/plugins\n'

The error seems to be because the configuration file is like this 

# Where your Airflow plugins are stored
/home/viki/airflow/plugins

i changed it to 

# Where your Airflow plugins are stored
plugins_folder = /home/viki/airflow/plugins

and it worked.

**Comment by mistercrunch** [comment]
good catch, v1.1.1 is coming to fix this

**Comment by mistercrunch** [comment]
`v1.1.1` is out here and addresses this bug:
https://pypi.python.org/pypi/airflow/1.1.1

I'll need to add a unit test to parse the default cfg ...
