### ISSUE TITLE
Feature request: run on an external scheduler

### ISSUE THREAD

**Issue by kimtore** [apache/airflow#370]
Hi,

I'm evaluating Airflow for MET Norway as a replacement for our current workflow pipeline. One of the requirements is that it must work with an external grid computing engine, Open Grid Engine or similar. The CeleryExecutor is not a viable option for us, because we would like to keep our current grid infrastructure.

I've been looking at how to implement this support by subclassing either the `BaseOperator` or the `BaseExecutor` classes. However, each of these options poses problems:
- Subclassing `BaseOperator` seems the easiest. By copying the code from `BashOperator`, and modifying it a bit so that it submits the job instead of running it locally, we are able to achieve this. However, we have to run it synchronously, and thus a network outage or scheduler crash will terminate the job.
- The idea of subclassing `BaseExecutor` is tempting, since the API is asynchronous, and the class can maintain its own account of ongoing jobs. But in this class, we have several problems. First, the command that is passed is similar to `airflow run dag_id task_id 2015-09-08T13:25:00 --local -sd DAGS_FOLDER/dag_id.py`. We cannot run this command directly on our grid without installing Airflow there, which we don't consider a good option. Second, we don't seem to be able to pass any variables to the Executor. This means that we cannot control our grid engine features, like CPU/memory requirements, parallelization, and the like.

Can you help us figure out how to implement these features, so that we can use `BaseExecutor`?

Regards,
@ambientsound

**Comment by mistercrunch** [comment]
It sounds like subclassing `BaseExecutor` would be the way to go.

About your statement:
"We cannot run this command directly on our grid without installing Airflow there"

The state of the task instance is managed by the `airflow run` at the moment, and this encapsulation does quite a few things, from parsing your pipelines metadata, running the code in the operator and updating its status to "running" and "success". In light of that, the Airflow task instance needs the Airflow code to run Airflow jobs. 

So your options are to either install Airflow on those boxes, or somehow bootstrap it. To bootstrap it, you could highjack the `airflow run` call on that box to run code that would download and install airflow and then fire up the actual `airflow run`.

We could move the command generation from the `TaskInstance` class to `BaseExecutor` if you'd like to be able to control that though.

**Comment by kimtore** [comment]
Thanks for your swift reply.

The `TaskInstance::run` function is very big indeed, and does a lot of separate steps in succession. Would it perhaps be beneficial if this function was split up into smaller parts?

Then, a subclass of `BaseExecutor` might have access to the `TaskInstance` instance instead of just the `airflow run ...` command line.

Consider the following pseudo-code.

```
execute_async():
    if taskinstance is ready to run:
        set taskinstance state to running
        if task operator is of type BashOperator:
            extract command line task.bash_command
            execute using the grid engine
        else:
            run task.execute()

sync():
    for each taskinstance:
        if task operator is of type BashOperator:
            check status in grid engine
        else:
            check status in local thread
        if task is done:
            update status
```

Might this be sufficient to solve the problem?

**Comment by mistercrunch** [comment]
I really prefer for the unit of work to take care of its own state, message queues can drop messages. At the moment it's somewhat of a relief to know that the executor can be consider mostly stateless (if the executor goes down, the state is mostly safe as the workers will maintain the state of the tasks regardless of the shape of the executor or the message queue). There's also a mechanism by which task instances emit a regular heartbeat so that we can identify zombie tasks, that's all part of the wrapping and there are strong assumptions there. Changing these assumptions mean changing some code, generating new bugs and having to develop new ways to resync the state when it gets unsync. 

So if you want to run airflow you need to have Airflow on the worker, there just are no clean ways around it.
