### ISSUE TITLE
Add "airflow users change-user-password" 

### ISSUE THREAD

**Issue by ecerulm** [apache/airflow#37009]
### Description

there is `airflow users create`  and `airflow users delete` , but there is no `airflow users change-password` or anything to reset the password of a user. 

If a user has forgot his password , the administrator needs a cli alternative to change its password

### Use case/motivation

If a user has forgot his password , the administrator needs a CLI alternative to change its password

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment]
That seems reasonable, I can take a look into adding it

**Comment by ecerulm** [comment]
By the way, for completeness the cli alternative to change the password **today** would be 

```

FLASK_APP=airflow.www.app flask fab reset-password
The username [admin]:   theusernameyouwanttochange
Password: xxxxx
Repeat for confirmation: xxxxx
INFO - Updated user Firstname Lastname
```

**Comment by potiuk** [comment]
Or you can use API or Web UI. But yes CLI command would be useful.

**Comment by ecerulm** [comment]
> Or you can use API or **Web UI**.
 
I was trying to do it via the **Web UI** but I could find a way to change the password of another user.

 I tried via  Security > List users > Edit record and I don't see any way to change the password. I see that I can change / reset my own password via the profile icon on the top right > Your Profile > Reset password  but I'm after reseting the password for another user (as an admin)

**Comment by potiuk** [comment]
Cick on the "show user" (a small looking glass icon) for a user as an admin and you will see `reset password` button.

**Comment by ecerulm** [comment]
>Click on the "show user" (a small looking glass icon) for a user as an admin and you will see reset password button.

Ok, found it, well definitely I didn't expect to find "reset password" under "Show user" instead of "Edit user"

**Comment by potiuk** [comment]
> > Click on the "show user" (a small looking glass icon) for a user as an admin and you will see reset password button.
> 
> Ok, found it, well definitely I didn't expect to find "reset password" under "Show user" instead of "Edit user"

Yep. Agree it's not intuitive.  And as usual in open-source project like this PRs to change it are most welcome of course, if you think it could be improved.

**Comment by ecerulm** [comment]
You also mention Airflow REST API as a way, I found https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/patch_user but it seems deprecated, is this the wrong one?

**Comment by potiuk** [comment]
It's the right one - it's deprecated only because it's moved with AuthManager implementatiobn (but we have not described it well enough and did not generate swagger/API documentation for the new endpoints- it's coming in https://github.com/apache/airflow/pull/36664
