### ISSUE TITLE
Dependency Issue with apache-airflow-providers-fab

### ISSUE THREAD

**Issue by aashishshrestha09** [apache/airflow#37020]
### Apache Airflow Provider(s)

fab

### Versions of Apache Airflow Providers

`apache-airflow-providers-fab==1.0.0`

### Apache Airflow version

2.8.1

### Operating System

macOS

### Deployment

Other Docker-based deployment

### What happened

While trying to use the `get_oauth_user_info` method in my custom security manager, I encountered a dependency issue. I was following the recommendation to inherit from `airflow.auth.managers.fab.security_manager.override.FabAirflowSecurityManagerOverride` for overriding the security manager. However, when I tried to install `apache-airflow-providers-fab`, I found that the package requires apache-airflow version 2.9.0 or higher, but as of now, Apache Airflow has not released a version 2.9.0.

### What you think should happen instead

I expected the apache-airflow-providers-fab package to have a dependency on a version of apache-airflow that is currently available.

### How to reproduce

To reproduce the issue, try to install apache-airflow-providers-fab with the latest available version of apache-airflow. The dependency conflict becomes apparent.

### Anything else

This issue is preventing me from using the `get_oauth_user_info` method in my custom security manager and the `apache-airflow-providers-fab` package. Any help or guidance would be appreciated.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@vincbeck correct me if I am wrong here.

Only for Airflow>=2.9.0 the fab provider can be used. While the provider is released the core code of Airflow 2.8 dont refrence it so you cant really use it.

See https://github.com/apache/airflow/pull/35926

Its important to understand that providers have seperated release cycle and the provider must be released **before** we release Airflow 2.9.0

**Comment by vincbeck** [comment]
> @vincbeck correct me if I am wrong here.
> 
> Only for Airflow>=2.9.0 the fab provider can be used. While the provider is released the core code of Airflow 2.8 dont refrence it so you cant really use it.
> 
> See #35926
> 
> Its important to understand that providers have seperated release cycle and the provider must be released **before** we release Airflow 2.9.0

100% correct

**Comment by babaMar** [comment]
From where can I import `Role` model in 2.8.1?

I'm upgrading from an older version and found:
`from airflow.www.security import Role`, which now gives me error

**Comment by vincbeck** [comment]
> from airflow.www.security import Role, User, which now gives me error.

What error do you get?

**Comment by babaMar** [comment]
it cannot be imported from there, as it's not there...
I fixed this with:
`from airflow.auth.managers.fab.models import Role, User`

**Comment by vincbeck** [comment]
> it cannot be imported from there, as it's not there... I fixed this with: `from airflow.auth.managers.fab.models import Role, User`

It seems we indeed break those imports ... Sorry for that. For Airflow 2.8.x version you should get them from `airflow.auth.managers.fab.models` and from Airflow 2.9, you should get them from `airflow.providers.fab.auth_manager.models`.

These models are not part of the Airflow public interface, I think that's the reason why we introduced some breaking changes.
