### ISSUE TITLE
Update airflow.io.path.ObjectStoragePath for upcoming universal_pathlib release

### ISSUE THREAD

**Issue by ap--** [apache/airflow#37067]
### Apache Airflow version

main (development)

### What happened?

I'm opening this issue to track a needed refactor of `airflow.io.path.ObjectStoragePath` to support the next release of `universal_pathlib` without having to have a special implementation for Python-3.12

### What you think should happen instead?

Tagging @bolkedebruin, @uranusjr, @potiuk 

It would be great if I could have some insight into the intended behaviour for the custom `UPath` subclass `airflow.io.path.ObjectStoragePath`

Looking at the current implementation it seems that these are the intended changes:

- (1) extracting a connection ID from the URI https://github.com/apache/airflow/blob/07fd3646fa765859a152731bf135ea944d0753d7/airflow/io/path.py#L148-L151
- (2) delegating fsspec filesystem creation to `airflow.io.store.ObjectStore` https://github.com/apache/airflow/blob/07fd3646fa765859a152731bf135ea944d0753d7/airflow/io/path.py#L49-L65
- (3) customization and extension of the `UPath` interface with several custom methods.

I am working on supporting (1) and (2) via custom methods that can be overwritten in UPath subclasses, and allow to have a single implementation for python versions prior to 3.12 and 3.12+, see: fsspec/universal_pathlib#172

Once that is integrated in UPath it should simplify the `ObjectStoragePath` implementation a lot. The custom accessor will be replaced by a factory method for creating fsspec filesystems, and the custom `__new__` implementation by a method for parsing additional storage_options.

Let me know if that sounds good, and what's the best way to collaborate on this issue and move forward.

Cheers,
Andreas 😃 

### How to reproduce

N/A

### Operating System

N/A

### Versions of Apache Airflow Providers

---

### Deployment

Other

### Deployment details

N/A

### Anything else?

N/A

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bolkedebruin** [comment]
Hey @ap-- , 

That just sounds awesome! Obviously any simplification while retaining flexibility sounds great. 

The generic need for a custom class on top of UPath is indeed to support Airflow-isms, like what you mentioned but also to be able to de/serialize a path into something that can be stored in a database. We are also a bit more "object store" oriented (semantically) than UPath I guess, so a little bit more strict in what we support how how things behave.

**Comment by ap--** [comment]
> The generic need for a custom class on top of UPath is indeed to support Airflow-isms, like what you mentioned but also to be able to de/serialize a path into something that can be stored in a database. We are also a bit more "object store" oriented (semantically) than UPath I guess, so a little bit more strict in what we support how how things behave.

Great 👍  Once I finish the implementation for fsspec/universal_pathlib#173 I'll open a PR here.

**Comment by potiuk** [comment]
Last blocker for https://github.com/apache/airflow/pull/36755

**Comment by ap--** [comment]
@bolkedebruin I released a new version of universal_pathlib yesterday, that vendors the required code to delay import of the required fsspec filesystems until they are actually used for IO.

PR #37524 should in theory pass all tests now, if `universal_pathlib>=0.2.2` is used as a dependency.
