### ISSUE TITLE
Config variable execute_tasks_new_python_interpreter not sufficiently documented

### ISSUE THREAD

**Issue by robinaly** [apache/airflow#37074]
### What do you see as an issue?

The documentation of [``execute_tasks_new_python_interpreter``](https://github.com/apache/airflow/blob/1197f2ff654e2fdafbb9d410a8d99cb6d6d3f8e6/airflow/config_templates/config.yml#L148 )  does not mention that the ``run_as_user`` option has to be also specified (e.g. via core.default_impersonation). 

That's at least the case when run using the [``StandardTaskRunner``](https://github.com/apache/airflow/blob/1197f2ff654e2fdafbb9d410a8d99cb6d6d3f8e6/airflow/task/task_runner/standard_task_runner.py#L47)

### Solving the problem

Specify that ``run_as_user`` needs to be set

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Have you considered raising a PR and contributing an improvement?
