### ISSUE TITLE
Add two new fields (gunicorn_logconfig & gunicorn_logconfig_dict) to airflow.cfg to allow users to configure Airflow Webserver logs

### ISSUE THREAD

**Issue by shayoo9814** [apache/airflow#37078]
### Description

Today, Airflow users lack the ability to configure Airflow Webserver logs. (Users can only configure [access logs](https://docs.gunicorn.org/en/stable/settings.html#accesslog), which is only a subset of Airflow Webserver logs). For instance, Airflow users are not able to convert Airflow Webserver logs into structured logs. 
In order to configure Airflow Webserver logs, Airflow users need to be able to configure Airflow Gunicorn logs. 
Today, Airflow parses airflow.cfg to specify various custom configurations when initializing Gunicorn in airflow/cli/cli_config.py (e.g. the --access-logformat flag is set [here](https://github.com/apache/airflow/blob/main/airflow/cli/cli_config.py#L740-L744)) and I don’t see an option to set neither the [--log-config](https://docs.gunicorn.org/en/stable/settings.html#logconfig) flag nor the [--logconfig_dict](https://docs.gunicorn.org/en/stable/settings.html#logconfig-dict) flag, at least one of which is necessary to configure gunicorn logging.
To provide maximum flexibility to users in terms of configuring Airflow Webserver logs, I request that Airflow maintainers add both `gunicorn_logconfig` and `gunicorn_logconfig_dict` parameters to Airflow.cfg, which will be parsed and passed in during Airflow's Gunicorn initialization.

### Use case/motivation

The motivation is to empower Airflow users to configure Airflow Webserver logs as they please. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can configure gunicorn settings by GUNICORN_CMD_ARGS variable

https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/logging-tasks.html#serving-logs-from-workers-and-triggerer

**Comment by shayoo9814** [comment]
I still believe there is value to be gained from the proposed change for the following reasons. 
1. Consistent interface for Airflow customizations
`airflow.cfg` is what users recognize as the established interface through which they can override/customize various configurations (e.g., `logging_config_class` and `celery_config_options`). Why not keep things consistent and allow Airflow users to customize Celery logging through `airflow.cfg`?
2. GUNICORN_CMD_ARGS is harder to manage than `airflow.cfg`
In our case, we have to add this ENV in our Dockerfile and custom startup scripts, which is more work compared to modifying `airflow.cfg`

**Comment by potiuk** [comment]
No. This is wrong assessment.

We already have few 100s of options in airflow config and we do not want to bloat it with even more stuff. Airflow config is actually one of the worst way to manage configuation, the best one in many deployments is setting configuration with environment variables, because it makes it far easier to manage changes in individual values and see them straight where you set them inthe Dockerfile.

Nope . Our approach is that we only add new configuration when we absolutely need it, and if there is no other - easy - way to configure it.
