### ISSUE TITLE
Allow Dag Processor Manager to log to stdout

### ISSUE THREAD

**Issue by plmnguyen** [apache/airflow#37122]
### Description

On Airflow 2.8.1, the DAG processor manager no longer logs out to stdout (whereas it did on 2.6.2).

### Use case/motivation

We currently have a configuration option for the DAG processor to log to stdout via `AIRFLOW__LOGGING__DAG_PROCESSOR_LOG_TARGET`. A similar configuration `AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_TARGET` could achieve that.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by stevenschaerer** [comment]
Happy to take a look.

**Comment by Owen-CH-Leung** [comment]
afaik, the DAG processor manager runs in a spawned process and by default output its log to a destinated file defined by `dag_processor_manager_log_location`. I think this behaviour also applies to `v2.6.2`

I suggest adding an extra variable in the config like `dag_processor_manager_log_stdout` , which if being set to `True` (default is `False`) , extend the log handler to also include logging to stdout. That way, the log from the spawned process can also be directed to the stdout of airflow scheduler like below : 

<img width="1399" alt="image" src="https://github.com/apache/airflow/assets/43698890/645fe926-ed81-4766-80c0-e0a3fa673155">


thoughts ?

**Comment by potiuk** [comment]
> thoughts ?

 This is a valid option if someone wants it, all it needs is someone to PR it.

**Comment by Owen-CH-Leung** [comment]
> > thoughts ?
> 
> This is a valid option if someone wants it, all it needs is someone to PR it.

Ok I'm on it

**Comment by jeff-cook** [comment]
I found the config doc for this https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dag-processor-log-target

And set 
```
          env:
            - name: AIRFLOW__LOGGING__DAG_PROCESSOR_LOG_TARGET
              value: stdout
```

However in `apache/airflow:3.0.2` it is not sending to stdout. 
I'm running the current helm chart version `1.18.0`
