### ISSUE TITLE
Airflow  2.7.2 constrain file use redshift-connector==2.7.2 that causes dependency issues with dbt-redshift package (any)

### ISSUE THREAD

**Issue by EsauOlivaLeaoHelix** [apache/airflow#37148]
### Apache Airflow Provider(s)

dbt-cloud

### Versions of Apache Airflow Providers

--constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt

redshift-connector==2.014
dbt-redshift==1.7.2
dbt-postgress==1.7.7

### Apache Airflow version

2.7.2

### Operating System

MACOS

### Deployment

Amazon (AWS) MWAA

### Deployment details

Mwaa 2.7.2 version

## Current Behavior
The constrain file from 2.7.2 is hard pined to redshift-connector==2.014.  and that connector is related to: [https://github.com/dbt-labs/dbt-redshift/pull/601#issuecomment-1718442908](url)

A concrete example of this is Airflow 2.7.2 which uses the following default constraints:
https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt

You'll note the version of redshift-connector is 2.0.914 but this package jumped from 2.0.913 directly to 2.0.915, so it is essentially uninstallable by default in Airflow

## Expected/Previous Behavior
pip install with constraint should still have a valid installation candidate

### How to reproduce

pip install dbt-redshift --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt 

## Relevant log output

`ERROR: Cannot install -r /usr/local/airflow/requirements/requirements.txt  because these package versions have conflicting dependencies.`

The conflict is caused by:
    dbt-redshift 1.7.2 depends on redshift-connector!=2.0.914, <=2.0.918 and >=2.0.913
    The user requested (constraint) redshift-connector==2.0.914

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
**Solution**: Please Install first airflow and it dependencies and after that install upgrade all third party packages
**Solution with explanation**: Please follow the recommendation [Installation from PyPI: Upgrading and installing dependencies (including providers)](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#upgrading-and-installing-dependencies-including-providers)
