### ISSUE TITLE
sentry add_tagging() can take unset "task" variable

### ISSUE THREAD

**Issue by LipuFei** [apache/airflow#37142]
### Apache Airflow version

2.8.1

### What happened?

Our sentry has captured this error in `sentry.py`:

![image](https://github.com/apache/airflow/assets/2630468/39039a53-8b84-4a4a-92fc-313bf0414507)

![image](https://github.com/apache/airflow/assets/2630468/e5c59310-03ac-4351-8bcc-cb7b431569ab)

Looks at the TaskInstance class, the `task` attribute has a comment saying it's not always set. I think this is the case where it's not set.

https://github.com/apache/airflow/blob/e1b032d05b6fba0766a7d81f8af6bc2e2cc3d0d6/airflow/models/taskinstance.py#L1312

### What you think should happen instead?

Sentry `add_tagging()` should not raise exceptions

### How to reproduce

I'm not sure, but this seems to happen if a worker node is forcefully shut down when it's in the middle of running a task.

### Operating System

Airflow 2.8.1 Python 3.11 Docker

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

On EKS.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jkramer-ginkgo** [comment]
This is resolved by https://github.com/apache/airflow/pull/37002
