### ISSUE TITLE
In correct '{{ ds }}' value is picked up when runing a custom schedule task 

### ISSUE THREAD

**Issue by kashyap-adithya** [apache/airflow#37169]
### Apache Airflow version

2.8.1

### What happened?

I have a task that runs on a custom schedule interval, for all the hour values other than 0 the '{{ ds }}' value is returning  '{{ next_ds }}' value. which is incorrect. 

### What you think should happen instead?

Irrespective of the h value the {{ ds }} value should be consistent 

### How to reproduce

Have a simple task that is expected to run every 3 hours and it should print {{ ds }} value, you will see that the task that is scheduled at h = 3 hours will start returning the {{ next_ds }} value in the place of {{ ds }}

### Operating System

Ubuntu 22.0 

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by adithyakashyapv** [comment]
I think there is issue at my end 
I will fix it at my end
