### ISSUE TITLE
SqlToSlackApiFileOperator - Empty files

### ISSUE THREAD

**Issue by patricio-gonzalez-ventures** [apache/airflow#37191]
### Apache Airflow Provider(s)

slack

### Apache Airflow version

latest

### Operating System

macos

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Astronomer

### What happened

I am using the class SqlToSlackApiFileOperator which does not allow me to avoid sending messages to slack with an empty file.

### What you think should happen instead

I would to add a new parameter to the class that will add the possibility to allow us to avoid sending empty files (len condition in https://github.com/apache/airflow/blob/main/airflow/providers/slack/transfers/sql_to_slack_webhook.py#L160).

### How to reproduce

It can be easily reproduced after configuring a query that will retrieve no data.

### Anything else

I can work in the PR (it'd be my first one), although I would need guidance if the approach is right.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Feel free to make a PR

> (len condition in https://github.com/apache/airflow/blob/main/airflow/providers/slack/transfers/sql_to_slack_webhook.py#L160).

Small nit, you cant send file through Slack Incoming Webhook, this only available into the Slack API (APP). So you need to make changes into the different module

https://github.com/apache/airflow/blob/dec2662190dd4480d0c631da733e19d2ec9a479d/airflow/providers/slack/transfers/sql_to_slack.py#L136
