### ISSUE TITLE
Webserver - Rendered JdbcOperator results in Internal server error (500)

### ISSUE THREAD

**Issue by jomar83** [apache/airflow#372]
In the webserver choosing a JdbcOperator then trying to display the rendered template results in an internal server error. That happens if the sql argument is a list and not a single sql string. The SqlLexer expects a string and calls decode on it... Of course that doesn't work on a list.

``` python
AttributeError: 'list' object has no attribute 'decode'
```

@mistercrunch we can fix it, the question is what the rendering result is supposed to be and if we should write a custom (Delegating or something like that) Lexer for this issue.

**Comment by mistercrunch** [comment]
This bug was affecting all templated items that would be a list or a dict, this should address it:
https://github.com/airbnb/airflow/pull/374

**Comment by jomar83** [comment]
Great, thanks!
