### ISSUE TITLE
S3 Hook provides unnecessary log message when using s3hook class instance method: download_file

### ISSUE THREAD

**Issue by Bartket** [apache/airflow#37204]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon = "8.7.1"

### Apache Airflow version

2.7.2

### Operating System

Ubuntu 22.04.3 LTS

### Deployment

Amazon (AWS) MWAA

### Deployment details

MWAA Local runner 2.7.2

### What happened

When using s3hook.download_file(), Airflow logs return the message:

"This function shadows the 'download_file' method of S3 API, but it is not the same. If you "
"want to use the original method from S3 API, please call "
"'S3Hook.get_conn().download_file()'"

### What you think should happen instead

It would be better to make it a docstring, to not spam this message inside the task instance logs when calling it from within the custom operator.

The change was introduced in this PR: https://github.com/apache/airflow/pull/26886

### How to reproduce

Call the s3hook.download_file() method inside the custom Airflow operator.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
@Taragolis , can you assign this to me? I'll raise a PR.
