### ISSUE TITLE
Airflow task logs is showing as "Marking task as SUCCESS" and downstreams tasks are scheduled, but its not updating the state in metadata(postgreSql Flexi server)

### ISSUE THREAD

**Issue by sktemkar16** [apache/airflow#37212]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.6.1

### What happened?

Airflow task logs is showing as "Marking task as SUCCESS" and downstream tasks are scheduled, but its not updating the state in metadata(postgreSql Flexi server)

Due to this, the task is in up for retry and not proceeding. This is happening intermittently.

### How to reproduce

It should show the correct logs that it failed to update the metadata db.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@sktemkar16 You have not provided enough information for us to investigate the problem you raised.  Can you provide more information and, ideally, a way of replicating it?
