### ISSUE TITLE
CUSTOM_SECURITY_MANAGER must extend FabAirflowSecurityManagerOverride not FAB's own security manager

### ISSUE THREAD

**Issue by c-thiel** [apache/airflow#37227]
### Apache Airflow version

2.8.1

### What happened?

This is related to https://github.com/apache/airflow/issues/36432 which is not fixed fully in 2.8.1

When using a custom security manager that does not inherit also from `airflow.www.security.AirflowSecurityManager`, the webserver fails with:

Exception: Your CUSTOM_SECURITY_MANAGER must extend FabAirflowSecurityManagerOverride,
                     not FAB's own security manager.

This is also described as an amendmend to the old issue:
https://github.com/apache/airflow/issues/36432#issuecomment-1921340775

### How to reproduce

Follow the [documentation](https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#example-using-team-based-authorization-with-github-oauth) and extend the FabAirflowSecurityManagerOverride class. 
See it fail.

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Duplicate of #https://github.com/apache/airflow/issues/36342 - will be fixed in upcoming 2.8.2
