### ISSUE TITLE
Momento Warning

### ISSUE THREAD

**Issue by Satoshi-Sh** [apache/airflow#37281]
### Apache Airflow version

2.8.1

### What happened?

When I sign in to the Airflow client. Moment gives a warning in the browser terminal.

`
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2024-02-09T03:36:42T+00:009, _f: undefined, _strict: undefined, _locale: [object Object]
`

![Screenshot from 2024-02-09 09-53-28](https://github.com/apache/airflow/assets/73622805/2123120b-4e5a-49ca-9574-c7412a5c6b01)

### What you think should happen instead?

No warning should be shown.

### How to reproduce

1. Run the webserver locally
2. Sign in and open the browser terminal, and you will see the warning.

### Operating System

Ubuntu 22.04.3 LTS

### Deployment

Docker-Compose

### Anything else?

If you have a contribution guide for the website, I would like to know where it is. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rafidka** [comment]
Not directly related to this, but Airflow should move off of `momentjs` altogether at some point. The project is long considered legacy and developers are encouraged not to use it by the authors of momentjs themselves:

https://momentjs.com/docs/#/-project-status/

**Comment by potiuk** [comment]
> Not directly related to this, but Airflow should move off of `momentjs` altogether at some point. The project is long considered legacy and developers are encouraged not to use it by the authors of momentjs themselves:
> 
> https://momentjs.com/docs/#/-project-status/

Could you plese open an issue for that @rafidka ?
