### ISSUE TITLE
Support configuring 'can_create' on DAG level permissions

### ISSUE THREAD

**Issue by shakhar** [apache/airflow#37329]
### Description

Currently DAG level permissions supports only the  `can_read`, `can_edit` and `can_delete` actions ([ref](https://github.com/apache/airflow/blob/main/airflow/security/permissions.py#L67)) without supporting `can_create`. Moreover, it supports only `RESOURCE_DAG` resource ([ref](https://github.com/apache/airflow/blob/main/airflow/providers/fab/auth_manager/security_manager/override.py#L198)) without supporting all prefixed DAG related resources, like `RESOURCE_DAG_RUN`.

I believe that if you will add the `RESOURCE_DAG_RUN` to the `DAG_RESOURCES` list (and all other prefixed DAG resources) and add the `can_create` to the  `DAG_ACTIONS` list, it will allow us to configure a DAG level permission to trigger a run (`can_create` on `RESOURCE_DAG_RUN` will let you do it) and will open door for other DAG level permissions that are not directly on the `RESOURCE_DAG` level.

### Use case/motivation

We want to be able to support DAG level permissions to trigger an new DAG run.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
Triaged; see also discussion in #37249.

**Comment by joaopamaral** [comment]
I've created this PR https://github.com/Automattic/hadoop-cluster/pull/1811 to extend the dag level permission to allow use Dag Run resources. @shakhar, I think it can solve your issue, right?

**Comment by shakhar** [comment]
@joaopamaral Yes, this will solve my issue, thanks 🙏🏽
