### ISSUE TITLE
mapping key "ports" already defined at line 23 - Regression introduced in 681d2ba 

### ISSUE THREAD

**Issue by Ahmad-RW** [apache/airflow#37353]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

1.27

### What happened

issue in `webserver-service.yaml` file line number 46, key `port` duplicated

### How to reproduce

just install the helm chart with default values will reproduce the issue 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
There is no need to open issue for those kind of changes - just opening PR is enough.

**Comment by Ahmad-RW** [comment]
https://github.com/apache/airflow/pull/37356
