### ISSUE TITLE
Filter datasets by dag_id in rest API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#37423]
### Description

We have a list datasets endpoint in the API. Right now we can only filter by searching uri string. It would be useful to be able to pass one or multiple `dag_id`s and only return datasets that include that `dag_id` in `consuming_dags` or `producing_tasks`

### Use case/motivation

Make it easy to see what datasets are connected to a dag.

Right now our webserver endpoint to get dataset dependencies returns all datasets+dags and then the UI needs to filter it down.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Some questions I have I'd like to get people's thoughts on:

1. Should it be a single dag_id or an array of multiple dag_ids?
2. Should we specify only consuming or only producing or both?
3. Maybe we need a separate, perhaps not in the public REST API, endpoint to return the entire dataset-dag graph based on either a dataset_uri or a dag_id?

**Comment by bbovenzi** [comment]
Actually this could just be in `datasets_summary` endpoint in the webserver.

**Comment by Satoshi-Sh** [comment]
I can take on this task.
