### ISSUE TITLE
Marking task state as Failed or Success without taskinstance edit role is resulting into partial empty screen

### ISSUE THREAD

**Issue by sreenusuuda** [apache/airflow#37451]
### Apache Airflow version

2.8.1

### What happened?

Marking task state as Failed or Success without task instance edit role is resulting into partial empty screen as shown below instead of Access Denied message. 

### What you think should happen instead?

We should show proper messaging saying user is lacking permission. 

### How to reproduce

1. Create new user and assign user with can edit dags, can read dag runs, can edit dag runs permissions.
2. Try to login with user and click on the specific Dag. 
3. Select task and try to mark it as Failed or Success. 

### Operating System

mac os

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RodrigoGanancia** [comment]
Hey, can I work on this issue?
