### ISSUE TITLE
Inlets not handled properly with @task functions

### ISSUE THREAD

**Issue by ninowalker** [apache/airflow#37463]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.0

### What happened?

A task with an outlet should convey it's outlets as inlets to a `@task` decorated function, when instantiated with `inlets=AUTO`. Instead, the string "auto" (the value of `airflow.lineage.AUTO`) is passed as the value, rather than the resolved outlets.

Consider a minimal test case:

```python
from airflow import DAG
from airflow.decorators import task
from airflow.lineage import AUTO
from datetime import datetime, timedelta

from airflow.operators.empty import EmptyOperator

DAG_ID = "test_lineage"

with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2021, 1, 1),
    dagrun_timeout=timedelta(minutes=5),
    catchup=False,
) as dag:
    f = "filename"
    op1 = EmptyOperator(
        task_id="leave1",
        outlets=[f],
    )

    @task
    def test_inlets(inlets):
        assert inlets == [f], f"{inlets} != {[f]}"
        return True

    op1 >> test_inlets(inlets=AUTO)
```

### What you think should happen instead?

`inlets` should resolve to the `outlets` of the upstream task, instead of being unresolved.

Instead:
```
AssertionError: ['auto'] != ['filename']'
```

### How to reproduce

1. Create the DAG, given the test code above.
2. Run the DAG.
3. Be sad :(

### Operating System

OSX

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.13.0
apache-airflow-providers-common-sql==1.9.0
apache-airflow-providers-discord==3.5.0
apache-airflow-providers-ftp @ file:///home/conda/feedstock_root/build_artifacts/apache-airflow-providers-ftp_1702441975571/work
apache-airflow-providers-google==10.12.0
apache-airflow-providers-http @ file:///home/conda/feedstock_root/build_artifacts/apache-airflow-providers-http_1706649884002/work
apache-airflow-providers-imap @ file:///home/conda/feedstock_root/build_artifacts/apache-airflow-providers-imap_1702443030927/work
apache-airflow-providers-papermill==3.6.0
apache-airflow-providers-postgres==5.9.0
apache-airflow-providers-sqlite==3.6.0
```

### Deployment

Other

### Deployment details

Running standalone.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ninowalker** [comment]
For additional context,  with the python debugger inside `execute_callable` of the PythonOperator (which wraps the function in question):

1. It's calling `self.python_callable(*self.op_args, **self.op_kwargs)`
2. `self.op_kwargs` are unresolved.
3. However, `self.inlets` does contain the correct values.
4. Thus, the problem is with the PythonOperator not supporting `inlets`.

Is this by design? Seems not.


```python
> /Users/rfc/miniforge3/envs/openwtf/lib/python3.11/site-packages/airflow/operators/python.py(216)execute_callable()
-> return self.python_callable(*self.op_args, **self.op_kwargs)
(Pdb) p self.op_kwargs
{'inlets': ['auto'], 'execution_date': '2024-02-15T22:14:46.598812+00:00'}
(Pdb) p self.inlets
['filename']
```

**Comment by Taragolis** [comment]
This works fine to me

```python
from airflow import DAG
from airflow.decorators import task
from airflow.lineage import AUTO
from datetime import datetime, timedelta

from airflow.operators.empty import EmptyOperator

DAG_ID = "test_lineage"

with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2021, 1, 1),
    dagrun_timeout=timedelta(minutes=5),
    catchup=False,
) as dag:
    f = "filename"
    op1 = EmptyOperator(
        task_id="leave1",
        outlets=[f],
    )

    @task(inlets=AUTO)
    def test_inlets(**kwargs):
        task_ = kwargs["task"]
        assert task_.inlets == [f], f"{task_.inlets} != {[f]}"
```

I'm surprised that someone use [Experimental Linage](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/lineage.html)
