### ISSUE TITLE
Core tests fail when run separately

### ISSUE THREAD

**Issue by drajguru** [apache/airflow#37466]
### Apache Airflow version

main (development)

### What happened?

test_sqlite_relative_path() in test_settings.py seemingly puts the session into a state that prevents subsequent test modules from passing. I think during this test the session is re-initialized and this interferes other test modules due to it being a global object.

### What you think should happen instead?

The test should mock out the session, engine... objects to avoid mutating the global state.

### How to reproduce

breeze testing tests --test-type Core

! _pytest.outcomes.Exit: Unable clear test DB, got error sqlalchemy.exc.OperationalE
[SQL: DELETE FROM job]
(Background on this error at: https://sqlalche.me/e/14/e3q8) !
============ 193 passed, 4 skipped, 5 warnings in 65.27s (0:01:05) =============

### Operating System

ubuntu 22.04

### Deployment

Virtualenv installation

### Deployment details

Using breeze

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Are you ABSOLUTELY sure you tested in on the latest main ? 

Becauase I believe I fixed this very problem few days ago here: https://github.com/apache/airflow/pull/37320 - where indeed original monkeypatching was not removed and all those things you are patching now were initialized as side effect.

But combining _AIRFLOW_SKIP_DB_TESTS and patching just Session and Engine which is a bit easier, does the trick in a much simpler way.

I just run `breeze testing tests --test-type Core` in main and it did not fail with the error you suggest, so likely you assessed it's wrong based on the version that was before.

Can you please re-verify if you still can reproduce the problem with latest main ? My feeling is that it is good now.

**Comment by potiuk** [comment]
BTW. You Absolutely should not open issue for such  things - just opening PR is more than enough, we hate beauraucracy (even the word is ugly) and in Airlfow, when you plan to open a PR, there is absolutely no need to open issue for it, it adds unnecessary overhead.

**Comment by drajguru** [comment]
Oh I see... I just retested on the latest main and the issue is indeed now fixed.
