### ISSUE TITLE
Alert / sound when a task or a dag completes

### ISSUE THREAD

**Issue by tim-x-y-z** [apache/airflow#37475]
### Description

it would be nice to have the web app play a sound notification when a task or a dag completes

### Use case/motivation

sometime we would start a dag manually and would like to know when it has successfully (or not) executed - currently just going back and checking the web page but it could be nice to have a sound notification if the app is open on the dag that is running

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by DarkFalc0n** [comment]
I would love to look into this issue.

**Comment by enchant3dmango** [comment]
Just in case you are not aware, you can use `on_success_callback` to send you an alert to Email, Slack, etc, when DAG (you can use it per task as well) is completed. Even so, this could be a good feature to develop in the future.

**Comment by bbovenzi** [comment]
Please use the existing callbacks.

I for one have too many tabs open and it would be extremely annoying when one of them starts making noise out of nowhere. Let alone if its a backfill or `catchup=true`
