### ISSUE TITLE
Inactive

### ISSUE THREAD

**Issue by sreenusuuda** [apache/airflow#37489]

**Comment by potiuk** [comment]
Can you please report it following https://github.com/apache/airflow/security/policy. Public issue is a bad idea in this case.

**Comment by potiuk** [comment]
FYI: @sreenusuuda  This one has been fixed in https://github.com/airflow-s/airflow-s/issues/119 in 2.8.2 . I'd suggest next time to report similar issue following the security policy so that we can also credit you appropriately.
