### ISSUE TITLE
inactive

### ISSUE THREAD

**Issue by sreenusuuda** [apache/airflow#37492]
Removed

**Comment by jscheffl** [comment]
I was reading multiple times and am missing the context of this error report. Can you give a bit more context to this?

Is this in the web UI? REST API? How do you access?

**Comment by sreenusuuda** [comment]
Its with REST API. 
<img width="1494" alt="Screenshot 2024-02-18 at 4 08 54 PM" src="https://github.com/apache/airflow/assets/99465779/8f4ee541-40fa-4ab2-8b00-68b83abc2631">
<img width="1488" alt="Screenshot 2024-02-18 at 4 08 14 PM" src="https://github.com/apache/airflow/assets/99465779/642a6fdd-1c37-422c-94b7-3f7137f05cf0">

**Comment by potiuk** [comment]
Can you please - as mentioned before report security related issues in a way that is explained in our security  policy and NOT as public issues? This is quite irresponsive behaviour and you have been already told that you should not do it. 

I am deleting this issue and ask you to do it as described in our Security policy (see security tab in GitHub).

**Comment by sreenusuuda** [comment]
@potiuk I apologize for not noticing your comment on the other issue earlier. This is my first time reporting an issue on a public repository. I will ensure to prioritize security considerations going forward.
