### ISSUE TITLE
Adding Task ids in DAG details API endpoint for Efficiency

### ISSUE THREAD

**Issue by msoni1369** [apache/airflow#37564]
### Description

The absence of task names in the DAG details API necessitates separate calls for task and DAG information, hindering process efficiency.

### Use case/motivation

Currently, task names are not included in the DAG details API endpoint. Tasks represent the execution component of a DAG also various API endpoints require task names. Therefore, to retrieve task names, one must query the "/dags/{dag_id}/tasks" endpoint. Additionally, to obtain basic DAG details, the "/dags/{dag_id}/details" endpoint is utilized. In my use case, automation of certain processes necessitates both DAG information and task names. Consequently, the need to utilize two separate API endpoints slows down the overall process, particularly considering the multitude of DAGs. It would be advantageous to consolidate this information into a single API call, considering that tasks are integral part of a DAG.

### Related issues

No relevant issue found

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
According to the documentation, the endpoint `details` should return a simplified representation of DAG, but IMHO it's a good idea to add an argument to include the tasks in this response, and keep it false by default.

**Comment by msoni1369** [comment]
@hussein-awala The current response of dag details API endpoint is as below. Instead of agrument for detailed details can we just add an element in response as shown below. 

"tasks": ["task1", "task2",...., "taskN"],

current response:

{
  "dag_id": "string",
  "root_dag_id": "string",
  "is_paused": true,
  "is_active": true,
  "is_subdag": true,
  "last_parsed_time": "2019-08-24T14:15:22Z",
  "last_pickled": "2019-08-24T14:15:22Z",
  "last_expired": "2019-08-24T14:15:22Z",
  "scheduler_lock": true,
  "pickle_id": "string",
  "default_view": "string",
  "fileloc": "string",
  "file_token": "string",
  "owners": [
    "string"
  ],
  "description": "string",
  "schedule_interval": {
    "__type": "string",
    "days": 0,
    "seconds": 0,
    "microseconds": 0
  },
  "timetable_description": "string",
  "tags": [
    {
      "name": "string"
    }
  ],
  "max_active_tasks": 0,
  "max_active_runs": 0,
  "has_task_concurrency_limits": true,
  "has_import_errors": true,
  "next_dagrun": "2019-08-24T14:15:22Z",
  "next_dagrun_data_interval_start": "2019-08-24T14:15:22Z",
  "next_dagrun_data_interval_end": "2019-08-24T14:15:22Z",
  "next_dagrun_create_after": "2019-08-24T14:15:22Z",
  "timezone": "string",
  "catchup": true,
  "orientation": "string",
  "concurrency": 0,
  "start_date": "2019-08-24T14:15:22Z",
  "dag_run_timeout": {
    "__type": "string",
    "days": 0,
    "seconds": 0,
    "microseconds": 0
  },
  "doc_md": "string",
  "params": {},
  "end_date": "2019-08-24T14:15:22Z",
  "is_paused_upon_creation": true,
  "last_parsed": "2019-08-24T14:15:22Z",
  "template_search_path": [
    "string"
  ],
  "render_template_as_native_obj": true
}
