### ISSUE TITLE
Bug in Extras in Add Connection , while writing few words are hidden due to margin and padding

### ISSUE THREAD

**Issue by Ram-tripath** [apache/airflow#37583]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

When adding Connection , while filling Extras field , few starting characters are hidden or not visible in UI.
For example if you fill : {"key":"Value"} then " {Ke" " starting few words will be not visible in UI.

### What you think should happen instead?

This error is basically due to some errors in margin and paddings of the text box where extras are filled.

### How to reproduce

Deploy and Run airflow version 2.7.3 and then try adding new connection and fill the Extras field.

### Operating System

Debian

### Versions of Apache Airflow Providers

2.7.3

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ram-tripath** [comment]
Hi @gitstart-airflow @potiuk , I need some help in understanding , I know the solution if i make changes in codemirror.css which is present in .../dist/cordemirror.css.
I need your assistance and help to fix it.

**Comment by potiuk** [comment]
Not sure why you are calling me - I have nothing to do with UI. please try to not call people directly if you are not sure if you should If you know solution. the open PR to it. All that is needed to do is explaine in CONTRIBUTING.rst and you should follow it We have 30-40 PRS merged a day at least there is no way some special  assistance (especailly when you are not asking concrete questions but asking for undisclosed and undefined amount of time from someone) can be given to every single person.

If you have concrete question or struggle - please ask concrete questions (use slack or github discussions) but when you ask for assistance, you ask for much more. See https://dontasktoask.com/

**Comment by pateash** [comment]
@Ram-tripath could you please share some screenshots of the issue you are facing?

**Comment by eladkal** [comment]
@Ram-tripath please share real example of the issue `" {Ke" "  `
i think the real issue you are trying to solve is not about hidden things but more about having Json linter similar to the idea in https://github.com/apache/airflow/issues/27157 ?

**Comment by shahar1** [comment]
@Ram-tripath would you still like to work on this issue?
It would be helpful if you could provide additional screenshots so it could be resolved.
