### ISSUE TITLE
DASK support removed but documentation article not updated

### ISSUE THREAD

**Issue by cameronthompson-payroc** [apache/airflow#37594]
### What do you see as an issue?

It is my understanding that DASK executor support has been withdrawn from future versions of airflow and is only receiving limited support, see this post https://github.com/apache/airflow/discussions/36976 

This documentation appears to be out of date https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/dask.html 

### Solving the problem

The documentation should be updated to make it clear as to the status of DASK, we were investigating it's usage for a while and it was not immediately clear that it had had support discontinued as  it is not listed on that page.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Already removed by #36269, so after next major version of Airflow this will be reflected into the documentation

**Comment by potiuk** [comment]
Also to clarify:

> It is my understanding that DASK executor support has been withdrawn from future versions of airflow and is only receiving limited support, see this post https://github.com/apache/airflow/discussions/36976

DASK executor has been removed from maintenance and as @Taragolis mentioned - we will stop mentoning it in the documentation, but it's already not been in airflow as of 2.7 minor release - it's been moving to provider. And it still can be used by installing provider. We have a stable API for executors and the old releases executor can be used by installing the provider.
