### ISSUE TITLE
AttributeError: 'SnowflakeHook' object has no attribute '_make_common_data_structure'

### ISSUE THREAD

**Issue by koziez** [apache/airflow#37591]
### Apache Airflow version

2.8.1

### What happened?

SnowflakeHook broken by update.

### What you think should happen instead?

SnowflakeHook should not raise an exception

### How to reproduce

Create DAG with SnowflakeOperator.

`snowflake_node = SnowflakeOperator(
    task_id=f"run_snowflake_{vendor}_{syncer}",
    snowflake_conn_id="snowflake_connection",
    sql=sql,
    dag=dag,
)`

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

whatever comes with apache/airflow:2.8.1

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

standard deployment

### Anything else?

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 391, in run
    result = self._make_common_data_structure(handler(cur))
AttributeError: 'SnowflakeHook' object has no attribute '_make_common_data_structure'

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> whatever comes with apache/airflow:2.8.1

Did you tried to update to the latest version of the provider?

**Comment by koziez** [comment]
@Taragolis I found the issue. I was using the wrong constraint file. Closed.
