### ISSUE TITLE
'None' execution date in a few DAG runs across several others

### ISSUE THREAD

**Issue by ariansacct** [apache/airflow#37592]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

A series of DAG runs were scheduled. Total number is around 30 (set using `start_date` and `end_date` params, one for each day of a month). On two of the runs, the value of `context['execution_date']` is `None`, failing the SQL task that uses it. The other runs are fine. All the runs use the same code and `provide_context = True` in all.

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'schedule_interval': '@daily',
    'provide_context': True,
    "retry_delay": duration(minutes=5),
    'retries': 5
}
```

### What you think should happen instead?

The date should not be null.

### How to reproduce

Not fully sure.

### Operating System

Ubuntu 20.04.6 LTS

### Deployment

Virtualenv installation

### Anything else?

It happened a few times. It does not happen with every single DAG source code.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Can you provide a replica of your DAG. That being said, `'schedule_interval': '@daily',` is a DAG level argument. It shouldn't be in the `default_args`. `default_args` are arguments you pass to all the tasks in your DAG

**Comment by ariansacct** [comment]
Could you mention what you mean by "replica" of the DAG? I'm happy to share the source code (with parts taken out).

**Comment by potiuk** [comment]
> I'm happy to share the source code (with parts taken out).

That's what replica means.
