### ISSUE TITLE
Hashicorp Vault: KvV2.create_or_update_secret() got an unexpected keyword argument 'secret_path'

### ISSUE THREAD

**Issue by Blizzke** [apache/airflow#37619]
### Apache Airflow Provider(s)

hashicorp

### Versions of Apache Airflow Providers

apache-airflow-providers-hashicorp==3.6.3

### Apache Airflow version

2.8.1

### Operating System

arch

### Deployment

Virtualenv installation

### Deployment details

[_VaultClient.create_or_update_secret()](https://github.com/apache/airflow/blob/main/airflow/providers/hashicorp/_internal_client/vault_client.py#L475) calls the underlying KV engine with a `secret_path` keyword parameter that should've been `path`:

```
File ".../.venv/lib/python3.11/site-packages/airflow/providers/hashicorp/_internal_client/vault_client.py", line 474, in create_or_update_secret
    response = self.client.secrets.kv.v2.create_or_update_secret(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: KvV2.create_or_update_secret() got an unexpected keyword argument 'secret_path'
```

### What happened

When using this functionality it fails given the above error message.

### What you think should happen instead

If the create_or_update_secret functionality is provided, it should work as intended.

### How to reproduce

Call `create_or_update_secret`, via the VaultHook for example.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tungbq** [comment]
Hi team, can I work on this issue?

**Comment by potiuk** [comment]
feel free
