### ISSUE TITLE
Trigger DAG w/config page appears no matter which option is selected

### ISSUE THREAD

**Issue by matterrr** [apache/airflow#37632]
### Apache Airflow version

2.8.1

### What happened?

When I trigger a DAG in the DAG view by pressing the play button, and I select `Trigger DAG`, Airflow navigates to the page where the user can specify Configuration JSON. Normally this page only appears when I select `Trigger DAG w/config`.

This adds an extra step when triggering any DAG - The vast majority of our DAGs have no runtime config.,

### What you think should happen instead?

The DAG should trigger instead of navigating to this page.

### How to reproduce

- Go to the DAG view of any example DAG
- Trigger the DAG by  pressing the play button and selecting `Trigger DAG`
- Observe that Airflow navigates to the `Trigger DAG: <dag ID>` page where you can specify Configuration JSON

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
Try looking at this configuration
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#show-trigger-form-if-no-params
You can change it to show params form only if exist,

**Comment by jscheffl** [comment]
I assume besides the configuration which is set (else no conf page would show-up) this also relates to the bug report #37063 which was fixed with #37379 which will be included in Airflow 2.8.2 ... which is in final release testing and probably will be released in a few days. Stay tuned.

Therefore closing as duplicate - if you thing it is a different problem, please leve a comment, logs and details, then we can re-open

**Comment by matterrr** [comment]
Just confirming that the bug linked above would indeed fix this issue.

**Comment by jscheffl** [comment]
> Just confirming that the bug linked above would indeed fix this issue.

Then you can be happy that Airflow 2.8.2 was just released today... so happy upgrading! :-D
