### ISSUE TITLE
do_xcom_push doesn't work

### ISSUE THREAD

**Issue by ashwintastic** [apache/airflow#37709]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.5

### What happened?

    cmd2 = 'echo 2'
    dbt_task = BashOperator(task_id='some_task_id',
                            bash_command=cmd2,
                            do_xcom_push=True)

Expectation: 2 should be push to xcom , but nothing is pushed in xcom

### How to reproduce

run a bash command in airflow , with the help of BashOperator with do_xcom_push= True . 

    cmd2 = 'echo 2'
    dbt_task = BashOperator(task_id='some_task_0',
                            bash_command=cmd2,
                            do_xcom_push=True)

### Operating System

windows 11

### Deployment

Docker-Compose

### Anything else?

NA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
I am unable to reproduce this with below dag which on execution pushes 2 to xcom from some_task_0 task. Can you please add a simple standalone dag without third party dependencies to reproduce this issue? Can you please check logs to see if the bash command was executed to show output in logs?

https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html#airflow.operators.bash.BashOperator

> If BaseOperator.do_xcom_push is True, the last line written to stdout will also be pushed to an XCom when the bash command completes

Sample log : 

```
[2024-02-26, 14:45:32 UTC] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26, 14:45:32 UTC] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo 2']
[2024-02-26, 14:45:32 UTC] {subprocess.py:86} INFO - Output:
[2024-02-26, 14:45:32 UTC] {subprocess.py:93} INFO - 2
[2024-02-26, 14:45:32 UTC] {subprocess.py:97} INFO - Command exited with return code 0
```

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.bash import BashOperator

from datetime import timedelta

with DAG(
    dag_id="gh_37709",
    start_date=datetime(2023, 10, 10),
    catchup=False,
    schedule_interval="@daily",
) as dag:

    cmd2 = "echo 2"

    dbt_task = BashOperator(task_id="some_task_0", bash_command=cmd2, do_xcom_push=True)

    dbt_task
```

**Comment by ashwintastic** [comment]
@tirkarthi    Please find my logs
<img width="512" alt="image" src="https://github.com/apache/airflow/assets/11703081/04f7d66c-21cd-4b32-bd5a-8588f7d96bd0">


But XCOM is empty

<img width="580" alt="image" src="https://github.com/apache/airflow/assets/11703081/d277bd82-8c95-4b8c-b846-f3b50790c5e3">
