### ISSUE TITLE
Lambda Operator doc has the wrong text

### ISSUE THREAD

**Issue by phal-nx** [apache/airflow#37781]
### What do you see as an issue?

https://airflow.apache.org/docs/apache-airflow-providers-amazon/3.1.1/operators/lambda.html

`To publish a message to an Amazon SNS Topic you can use [AwsLambdaInvokeFunctionOperator]`

This is a lambda, not a Amazon SNS topic operator

### Solving the problem

Change the wording on that sentence

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
The current version (8.18.0) of Amazon Provider documentation doesn't contain such a typo: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/lambda.html
