### ISSUE TITLE
Grid view tooltip text is truncated if date is too long

### ISSUE THREAD

**Issue by simond** [apache/airflow#37782]
### Apache Airflow version

2.8.2

### What happened?

When hovering over a dag run on the grid view the text will overflow the tooltip:
![image](https://github.com/apache/airflow/assets/421551/e004bb1d-483a-4462-aef0-ff2c1039530f)

### What you think should happen instead?

The tooltip box should be made a bit bigger to accommodate for long dates

### How to reproduce

- Load the example DAGs and set your timezone to something like UTC. 
- Run any of the example DAGs which have use data_interval_end as the run_ordering (eg. example_branch_datetime_operator)

### Operating System

osx 14.3.1 (23D60)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by simond** [comment]
Can i be assigned this issue?

**Comment by potiuk** [comment]
Feel free

**Comment by simond** [comment]
Fixed by pr #37805
