### ISSUE TITLE
Airflow UI marks task as failed but the task still running in kubernetes

### ISSUE THREAD

**Issue by rogerzs** [apache/airflow#37800]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.2

### What happened?

I'm using Airflow in Kubernetes, e i'm using KubernetesExecutor.

Sometimes, some tasks from dags are marked as failed in airflow ui, but tasks are still running in kubernetes,  are even completed successfully.

### What you think should happen instead?

I think a task not must be marked as failed if it execution not yet finished

### How to reproduce

I don't know how to reproduce, because the problem don't have a pattern.

### Operating System

Ubuntu 22.04

### Versions of Apache Airflow Providers

apache-airflow-providers-slack==7.3.0
apache-airflow[google,cncf.kubernetes,amazon,celery]==2.7.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

GKE - Version 1.27.9-gke.1092000

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Can you provide more information? Logs, etc. As is, there's not enough info to be able to reproduce or come up with a solution since the problem is not really clear.

**Comment by rogerzs** [comment]
@RNHTTR ok i'll try get the logs
