### ISSUE TITLE
Apply Airflow Reverse Proxy Through the Values.yaml

### ISSUE THREAD

**Issue by cjay2067** [apache/airflow#37825]
### Official Helm Chart version

1.12.0 (latest released)

### Apache Airflow version

2.8.1

### Kubernetes Version

v1.28.5-eks

### Helm Chart configuration

Follow the Airflow Helm installation guidelines

helm repo add apache-airflow https://airflow.apache.org
helm upgrade --install airflow apache-airflow/airflow --namespace airflow --create-namespace

### What happened

after the deployment of the Airflow application on Kubernetes, a manual ingress was created to allow external access to the application. However, I am unable to connect with Airflow UI. Is there a values.yaml file parameter that specifies how the reverse proxy should be implemented at the airflow application level? or how to apply it?
![MicrosoftTeams-image 22_31](https://github.com/apache/airflow/assets/110012375/194a1217-749d-4cb6-afae-7b6fe5ffbb74)

### How to reproduce

Raised a discussion for this and looking for some expert opinions from your team. 
Discussion: https://github.com/apache/airflow/discussions/37824

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Closing it - as discussion is created.
