### ISSUE TITLE
Use a better log context name than `pod_manager.py` for KubernetesPodOperator runtime

### ISSUE THREAD

**Issue by ketozhang** [apache/airflow#37843]
### Description

KPO's runtime stderr and stdout is printed to the logger `pod_manager.py` module. 

### Use case/motivation

The context "KubernetesPodOperator" would be more clear. 

Is there a reason the logs must strictly be the module file? 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yes. This is the default for all loggers in Python and this is the default (and it allows to debug things more easily if you look at the source code). If you wish to change it - in Airflow 2.8+ you have the possibility to change logger name to whatever name you want: https://github.com/apache/airflow/pull/34964
