### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte (after upgrade to 2.8.2)

### ISSUE THREAD

**Issue by AlekseiSaff** [apache/airflow#37871]
### Apache Airflow version

2.8.2

### What happened?

after upgrade to 2.8.2 some backfill DAGs fail to run with error

00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/nse/nse_data_validation.py']
[2024-03-04T10:41:51.731+0800] {base_executor.py:146} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'nse-data-validation', 'stream_filter_9_banknifty', 'backfill__2023-06-08T14:
00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/nse/nse_data_validation.py']
[2024-03-04T10:41:51.743+0800] {base_executor.py:146} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'nse-data-validation', 'stream_filter_9_banknifty', 'backfill__2023-06-09T14:
00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/nse/nse_data_validation.py']
[2024-03-04T10:41:56.063+0800] {backfill_job_runner.py:446} INFO - [backfill progress] | finished run 0 of 2 | tasks waiting: 104 | succeeded: 4 | running: 20 | failed: 0 | skipped: 0
 | deadlocked: 0 | not ready: 90
[2024-03-04T10:42:00.787+0800] {backfill_job_runner.py:446} INFO - [backfill progress] | finished run 0 of 2 | tasks waiting: 104 | succeeded: 24 | running: 0 | failed: 0 | skipped: 0
 | deadlocked: 0 | not ready: 0
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### What you think should happen instead?

DAG must be procesed in a normal way

### How to reproduce

Run DAG via backfill

### Operating System

CentOS 7.9

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by AlekseiSaff** [comment]
From what I realize can't see/get some xcom objects anymore .

Mar  4 10:58:14 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 346, in __call__
Mar  4 10:58:14 lt-hkg1-avm04 airflow: fn(*args, **kw)
Mar  4 10:58:14 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 3702, in _event_on_load
Mar  4 10:58:14 lt-hkg1-avm04 airflow: instrumenting_mapper._reconstructor(state.obj())
Mar  4 10:58:14 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/models/xcom.py", line 132, in init_on_load
Mar  4 10:58:14 lt-hkg1-avm04 airflow: self.value = self.orm_deserialize_value()
Mar  4 10:58:14 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/models/xcom.py", line 705, in orm_deserialize_value
Mar  4 10:58:14 lt-hkg1-avm04 airflow: return BaseXCom._deserialize_value(self, True)
Mar  4 10:58:14 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/models/xcom.py", line 689, in _deserialize_value
Mar  4 10:58:14 lt-hkg1-avm04 airflow: return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
Mar  4 10:58:14 lt-hkg1-avm04 airflow: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by AlekseiSaff** [comment]
that is what I'm seeing in value field of XCOM table (read via python)

enable_xcom_pickling = False - in settings


b'\x80\x04\x88.'
b'\x80\x04\x95\x06\x00\x00\x00\x00\x00\x00\x00J\xd1\xb14\x01.'
b'\x80\x04\x95*\x00\x00\x00\x00\x00\x00\x00\x8c&check_for_stream_iplf_9_banknifty_sync\x94.'
b'\x80\x04\x95;\x00\x00\x00\x00\x00\x00\x00}\x94\x8c\x08followed\x94]\x94\x8c&check_for_stream_iplf_9_banknifty_sync\x94as.'
b'\x80\x04\x88.'
b'\x80\x04\x95\x06\x00\x00\x00\x00\x00\x00\x00J\xd4\xb14\x01.'
b'\x80\x04\x95*\x00\x00\x00\x00\x00\x00\x00\x8c&check_for_stream_iplf_6_banknifty_sync\x94.'
b'\x80\x04\x95;\x00\x00\x00\x00\x00\x00\x00}\x94\x8c\x08followed\x94]\x94\x8c&check_for_stream_iplf_6_banknifty_sync\x94as.'

**Comment by AlekseiSaff** [comment]
I set enable_xcom_pickling to True and now it works

**Comment by AlekseiSaff** [comment]
sorry, I had it True on worker machine, but false on web-server

**Comment by AlekseiSaff** [comment]
It seems like we had different value for enable_xcom_pickling on webserver and workers.

**Comment by jscheffl** [comment]
So is the problem resolved and the last comment just re-opened?
