### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints2.8.1/constraints-3.8.txt

### ISSUE THREAD

**Issue by kassar-anass25** [apache/airflow#37878]
### Apache Airflow version

2.8.2

### What happened?

ERROR: Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints2.8.1/constraints-3.8.txt

### How to reproduce

          .

### Operating System

ubunto windows 10

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Instead of `https://raw.githubusercontent.com/apache/airflow/constraints2.8.1/constraints-3.8.txt` please use `https://raw.githubusercontent.com/apache/airflow/constraints`**-**`2.8.1/constraints-3.8.txt`

**Comment by kassar-anass25** [comment]
> Instead of `https://raw.githubusercontent.com/apache/airflow/constraints2.8.1/constraints-3.8.txt` please use `https://raw.githubusercontent.com/apache/airflow/constraints`**-**`2.8.1/constraints-3.8.txt`

thanks
