### ISSUE TITLE
FastAPI incompatible with Airflow due to Flask-AppBuilder's email-validator constraint

### ISSUE THREAD

**Issue by nickolasrm** [apache/airflow#37879]
### Apache Airflow version

2.8.2

### What happened?

it's not possible to use `fastapi` with `airflow` because airflow depends on `flask-appbuilder`. The `appbuilder` dependencies require `email-validator<2`, which is incompatible with `pydantic[email] `, thus making `fastapi` incompatible.

The new version of the `appbuilder` (^4.4) fixes this problem by relaxing `email-validator` constraint and doesn't seem to introduce any breaking changes to the airflow.

### How to reproduce

Try installing `pip install "fastapi[all]>=0.9" "apache-airflow==2.8.2"`

### Operating System

Ubuntu 22.04

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
don't you just need the airflow clients ?

https://pypi.org/project/apache-airflow-client/
