### ISSUE TITLE
In DAG Graph View, clicking Task on it's name doesn't select the task

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#37932]
### Apache Airflow version

2.8.2

### What happened?

In the DAG Graph view, attempting to select a task by clicking on it's name does nothing. In version 2.8.0 it was working as intended.

![2024-03-06 10-58-20](https://github.com/apache/airflow/assets/4175430/74001291-0fbd-410e-90ea-c37628a9c86d)

### What you think should happen instead?

In the DAG Graph view, click on a task's name should select the task.

### How to reproduce

1. Create Dummy DAG with Dummy operators.
2. Open the DAG Graph View
3. Click a specific task on it's name

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Deployment details

Docker Compose version v2.2.3

### Anything else?

This problem occurs every time.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### Related Pull Requests:
- https://github.com/apache/airflow/pull/38782

**Comment by jonhspyro** [comment]
Hey, can I work on this issue?

**Comment by poorvirohidekar** [comment]
@eladkal I'd like to try my hand at this one. Can you please assign it to me?

**Comment by jonhspyro** [comment]
Hi, I was looking through the code and I found this bit of code in the component TaskName in the file DagNode.tsx:

```
onClick={(e) => {
  e.stopPropagation();
  onToggleCollapse();
}}
```
          
          
that when I comment just solves the issue, can you tell me if this bit of code does any specific task?


Thank you for your help :))

**Comment by jonhspyro** [comment]
@eladkal Should is it worth creating a test for this fix, considering the scale of the issue?

**Comment by pedro-cf** [comment]
greetings @jonhspyro not sure if forgotten or just busy! seems workflow didn't pass

**Comment by jonhspyro** [comment]
> greetings @jonhspyro not sure if forgotten or just busy! seems workflow didn't pass

I've been busy with college, will fix this week! :)

**Comment by pedro-cf** [comment]
Greetings @jonhspyro , is there anything preventing a merge ?

**Comment by pedro-cf** [comment]
Greetings @jonhspyro any chance you could create a pull request with your fixes :) ?
