### ISSUE TITLE
task instance keeps running when call http url with httpx in PythonOperator

### ISSUE THREAD

**Issue by mayuanxiaonong** [apache/airflow#37939]
### Apache Airflow version

2.8.2

### What happened?

I have a PythonOperator in my dag , in the python_callable function calls a http url by using `httpx.get(url)` . when i trigger the dag , the task instance keeps running , and the log stops before httpx.get . and it doesn't raise timeout error .

i tried  httpx and requests, and got the same problem.

<img width="1080" alt="image" src="https://github.com/apache/airflow/assets/7379670/7ff53133-f948-40ad-b853-21b687c997c8">

this is my code:
```python
        url='https://pokeapi.co/api/v2/pokemon/151'

        ## 1. try with httpx
        # print('begin with httpx.Client')
        # client = httpx.Client(timeout=30)  # stuck here
        # print('client = ', client)
        # resp = client.get(url=url)
        # print('resp = ', resp, resp.is_success)

        ## 2. try with httpx.AsyncClient
        # print('begin with httpx.AsyncClient')
        # client = httpx.AsyncClient(timeout=30)  # stuck here
        # print('client = ', client)
        # resp = client.get(url=url)
        # resp = asyncio.run(resp)
        # print('resp = ', resp)

        ## 3. try with requests
        print('begig with requests')
        session = requests.session()
        print('session = ', session)
        resp = session.get(url=url, timeout=30)  # stuck here
        print('resp = ', resp, resp)

```

and log like this:

<img width="951" alt="image" src="https://github.com/apache/airflow/assets/7379670/a22840ff-88dd-4133-857c-077d250a33db">

### How to reproduce

the code i provided

### Operating System

macOS 13.4.1

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mayuanxiaonong** [comment]
The problem is here .  when call `requests.get(url)`, it will check if pass proxy , and  the function ` _get_proxy_settings ` stuck .   

BTW , i call this function in shell scripts, and it works well . 

![image](https://github.com/apache/airflow/assets/7379670/cbda3630-8e9b-4b82-9175-be1fb884e338)

**Comment by mayuanxiaonong** [comment]
skip proxy bypass check with the follow code:
```python
## try with httpx
with httpx.Client(trust_env=False, timeout=30) as client:
    resp = client.get(url=url)
    print('resp = ', resp, resp.is_success)

## or with requests
with requests.Session() as session:
    session.trust_env = False
    resp = session.get(url=url, timeout=30)
    print('resp = ', resp)
```

**Comment by Taragolis** [comment]
I guess you have a Segmentation Fault. Try to set environment variable `no_proxy` to `*`
