### ISSUE TITLE
In the DAG Graph view, all DAG runs disappear after selecting a Run State

### ISSUE THREAD

**Issue by rgelsi** [apache/airflow#37966]
### Apache Airflow version

2.8.2

### What happened?

In the DAG Graph view, all DAG runs disappear after selecting a Run State from the dropdown. After reloading the page, the DAG runs with the selected states reappear.

![airflow_dag_run_state_bug](https://github.com/apache/airflow/assets/16667311/198e136e-c7e8-45c2-984a-26c409acba6b)

In version 2.8.1 it was working as intended and it still works as expected in the Grid view.

### What you think should happen instead?

In the DAG Graph view, selecting a DAG run state should display all DAG runs with that state.

### How to reproduce

1. Create and start a Dummy DAG with Dummy operators.
2. Open the DAG Graph View
4. Select a DAG run state from the dropdown

### Operating System

Oracle Linux 8.9

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Kubernetes v1.26.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Does this only happen for `running` DAG runs and only in the graph now? Gantt, Details, etc are fine?

**Comment by rgelsi** [comment]
This happens with all types of DAG run states and, in addition to the Graph view, also in the Gantt view. Grid and Code view do not have this issue.

**Comment by potiuk** [comment]
Can you please open Console in your browser and copy paste the logs and error details printed there - it looks like a javascript error that might come from some of your specific DAG configuration / state/ historical data - and without having the stack trace it will be rather impossible to figure out the problem (and having stack traces/javascript output should be helpful - if there are some printed in the console)

**Comment by rgelsi** [comment]
The following error is displayed in the Browser Console:
```
response: "{\"error\": \"Can not provide filters when dag_run_id filter is selected.\"}"
responseText: "{\"error\": \"Can not provide filters when dag_run_id filter is selected.\"}"
responseURL: "https://airflow.mydomain.gknpm/object/grid_data?dag_id=test_dag_v1&num_runs=5&run_state=running&dag_run_id=manual__2024-03-08T13:03:38.006850%2B00:00"
status: 400
statusText: "BAD REQUEST"
```

This error message was added with version 2.8.2: https://github.com/apache/airflow/blob/2.8.2/airflow/www/views.py#L3585

When accessing a DAG via the graph or grid view, the parameter dag_run_id is added to the URL. This is not the case with the grid or code view. After manually removing the dag_run_id from the URL, the filter works as expected.

**Comment by bbovenzi** [comment]
That makes sense. If you have a dag run selected, we shouldn't let you filter out your selection.
So either setting a filter clears your selection or filters are disabled when a dag run is selected with a warning

**Comment by eladkal** [comment]
@bbovenzi do we have a task here?

**Comment by bbovenzi** [comment]
> @bbovenzi do we have a task here?

Yes, let's clear a user's selection if the Dag run is no longer on the page after filters change.

**Comment by bbovenzi** [comment]
Actually I think this is fixed by https://github.com/apache/airflow/pull/38941 But we should also add some better empty states here to prompt users to clear any filters.
