### ISSUE TITLE
The systemd package cannot be installed because this system does not have a merged /usr.

### ISSUE THREAD

**Issue by Pooort** [apache/airflow#37970]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.2

### What happened?

I'm using `apache/airflow:2.7.2-python3.9` docker image and trying to install firefox to use in my DAGs.

But there is an issue:
```
******************************************************************************
*
* The systemd package cannot be installed because this system does
* not have a merged /usr.
*
* Please install the usrmerge package to convert this system to merged-/usr.
*
* For more information please read https://wiki.debian.org/UsrMerge.
*
****************************************************************************** 
```

### How to reproduce

In the container:
`apt install systemd`

### Operating System

Debian

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Not related to the Airflow:

- https://stackoverflow.com/a/51985145
- https://forums.docker.com/t/how-to-run-systemd-inside-a-docker-container/137954/2
