### ISSUE TITLE
pendulum 3.0 raise bug on old versions of airflow

### ISSUE THREAD

**Issue by Niccolum** [apache/airflow#38038]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.4.3

### What happened?

Hello. I saw, that on old airflow version we have requirement https://github.com/apache/airflow/blob/v2-4-stable/setup.cfg#L116

So, if we use together pendulum>=3.0 and airflow 2.4.3, we catch a bug

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py", line 42, in <module>
    from airflow import settings
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py", line 49, in <module>
    TIMEZONE = pendulum.tz.timezone('UTC')
TypeError: 'module' object is not callable

because of 
https://stackoverflow.com/questions/77703615/pendulum-tz-timezoneutc-typeerror-module-object-is-not-callable/77705021#77705021

Can you add right constraint to this line?

### How to reproduce

just install airflow 2.4.3 with pendulum>=3.0

### Operating System

any

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Niccolum** [comment]
add a PR:
https://github.com/apache/airflow/pull/38039

**Comment by Taragolis** [comment]
We do not change old releases, as well as not released any new bugfix releases after the new feature/minor version released.
Please consider to use provided constraints for appropriate version of Airflow(see [Installation from PyPI](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files))  and/or add explicit `pendulum<3` into your `pip install` command
