### ISSUE TITLE
XCOM_sidecar_container not started results in long running DAG

### ISSUE THREAD

**Issue by ionescur2** [apache/airflow#38115]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.2

### What happened?

**Error**: Xcom_sidecar_container sometimes is not started which will result in a long running dag waiting for the container to start but it will never start again.

There is a small change in the following method: **_await_xcom_sidecar_container_start_** from **_/airflow/providers/cncf/kubernetes/utils/pod_manager.py_**.

Version 2.6.0 code:
```python
    def await_xcom_sidecar_container_start(self, pod: V1Pod) -> None:
        self.log.info("Checking if xcom sidecar container is started.")
        warned = False
        while True:
            if self.container_is_running(pod, PodDefaults.SIDECAR_CONTAINER_NAME):
                self.log.info("The xcom sidecar container is started.")
                break
            if not warned:
                self.log.warning("The xcom sidecar container is not yet started.")
                warned = True
            time.sleep(1)
```

Version 2.7.2 code:
```python
    def await_xcom_sidecar_container_start(self, pod: V1Pod) -> None:
        self.log.info("Checking if xcom sidecar container is started.")
        for attempt in itertools.count():
            if self.container_is_running(pod, PodDefaults.SIDECAR_CONTAINER_NAME):
                self.log.info("The xcom sidecar container is started.")
                break
            if not attempt:
                self.log.warning("The xcom sidecar container is not yet started.")
            time.sleep(1)
```

We believe that the old version code with the while true: inside is better suited because it checks if the container is started.

### What you think should happen instead?

```python
    def await_xcom_sidecar_container_start(self, pod: V1Pod) -> None:
        self.log.info("Checking if xcom sidecar container is started.")
        warned = False
        while True:
            if self.container_is_running(pod, PodDefaults.SIDECAR_CONTAINER_NAME):
                self.log.info("The xcom sidecar container is started.")
                break
            if not warned:
                self.log.warning("The xcom sidecar container is not yet started.")
                warned = True
            time.sleep(1)
```

We believe that this code will wait for the the container to start.

### How to reproduce

Sometimes the XCOM container is not started. Stop the container and see the reaction of the DAG. 

### Operating System

Linux

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ionescur2** [comment]
Last log: [2024-03-01 13:31:43,814] The xcom sidecar container is not yet started.

**Comment by hussein-awala** [comment]
Technically, there is no difference between the code of the two versions, where `tertools.count()` is an infinite generator for incremental numbers. IMHO we need to add a timeout for the waiting time, similar to what we do for the base container, and when we reach this timeout, we should fail the task instead of waiting forever.

**Comment by jhongy1994** [comment]
I created PR #40909 to fix this issue. Please check it!

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/42504
