### ISSUE TITLE
max_active_runs_per_dag is not respected

### ISSUE THREAD

**Issue by HenryLee19** [apache/airflow#38159]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.3

### What happened?

I changed  the "max_active_runs_per_dag" from the default of 16 to 2, in the Airflow config. Then manually triggered a DAG 10x via the UI and observed 10 instances of the DAG in the "running" state.

### What you think should happen instead?

I expected there to be 2 instances in the "running" state and 8 in the "queued" state. 

(Note, setting "max_active_runs" at the DAG level works. It is only the global "max_active_runs_per_dag" that appears to be not working.)

### How to reproduce

1. in airflow.cfg, change "max_active_runs_per_dag" from the default of 16 to 2
2. restart Airflow (Docker container, in my case)
3. trigger a DAG via the UI play button 10x
4. observe 10 instances of the DAG in the "running" state

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### Deployment details

Used the docker-compose found here: https://airflow.apache.org/docs/apache-airflow/2.8.3/docker-compose.yaml

### Anything else?

DAG definition:

```
from datetime import datetime
import time

from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'email': ['airflow@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
}


def _task1(**context):
    time.sleep(120)
    return


with DAG(
    dag_id='dag1',
    default_args=default_args,
    schedule=None,
    catchup=False
) as dag:

    task1 = PythonOperator(
        task_id='task1',
        python_callable=_task1
    )
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Thanks for reporting the bug. I very much doubt that in 2.8.3 this behavior is changed. It is a core feature in Scheduler to restrict runs if set by parameter.

My first guess is that the scheduler does not effectively have the right parameter being set. Can you please:
1. Copy the finally used airflow config here
2. Attach the final used compose file to the bug
3. Exec into the scheduler POD and execute the `env` command validating the the config is present. Maybe also post the output here.
