### ISSUE TITLE
Timezone information should be shown in Next Run details

### ISSUE THREAD

**Issue by pateash** [apache/airflow#38172]
### Description

We currently do not show the Timezone information in Next Run information,
although user can hover over and check this  in ToolTip, we can also show this upfront.
<img width="699" alt="image" src="https://github.com/apache/airflow/assets/16856802/024199cd-a98f-46d4-9453-cdaa3c75686b">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
I have never tried to fix something related to UI and I wish to try fixing this issue.
