### ISSUE TITLE
constraint "dag_run_dag_id_execution_date_key" not using run_id

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#38176]
### Apache Airflow version

2.8.3

### What happened?

I want run multiple dag_run with the same execution date but it fail with

```log
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key"
DETAIL:  Key (dag_id, execution_date)=(test_a, 2024-03-01 00:00:00+00) already exists.
```

### How to reproduce

```python

from airflow.operators.python import PythonOperator
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from pendulum import today
from airflow import DAG

dag = DAG(
    dag_id="test_a",
    schedule_interval=None,
    start_date=today("UTC").add(days=-1000)
)

with dag:
    def toto(arg_1):
        print(arg_1)

    task_2 = PythonOperator(
        task_id="task-two",
        python_callable=toto,
        op_kwargs={"arg_1": "1"})

dag = DAG(
    dag_id="test_b",
    schedule_interval=None,
    start_date=today("UTC").add(days=-1)
)

with dag:
    TriggerDagRunOperator.partial(
        task_id="aaa",
        trigger_dag_id="test_a",
        reset_dag_run=True,
        wait_for_completion=True,
        deferrable=True
    ).expand_kwargs(
        [{"execution_date": x, "trigger_run_id": y} for x, y in
         [("2024-03-01", "NAME_a"), ("2024-03-01", "NAME_b")]])
```

### Operating System

ubuntu 22.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Check https://github.com/apache/airflow/pull/38179#issuecomment-2000603769

**Comment by raphaelauv** [comment]
https://github.com/apache/airflow/pull/41818

**Comment by uranusjr** [comment]
Now you can run multiple runs with the same date (but different run IDs). Is this still relevant?

**Comment by raphaelauv** [comment]
if `Now you can run multiple runs with the same date (but different run IDs)` then yes I can close this issue

also @uranusjr can we run with a None/NULL execution date ? 

(I have dags where the a dag_run is not related to a date)
