### ISSUE TITLE
Adding max_consecutive_failed_dag_runs in UI for dag

### ISSUE THREAD

**Issue by pateash** [apache/airflow#38171]
### Description

related - #36935

We are adding the  ability to automatically turn off DAG after X number of consecutive failures.

There are 2 ways to configure this

in DAG() using max_consecutive_failed_dag_runs parameter this will override any config (as below)
Using core config inside airflow.cfg or variable AIRFLOW__CORE_MAX_CONSECUTIVE_FAILED_DAG_RUNS_PER_DAG
environment variable.

### Use case/motivation

We should also show this information into dag_id(besides dag_id) if this is being used,
although we are showing this in dag details for now.

 
<img width="838" alt="image" src="https://github.com/apache/airflow/assets/16856802/b1e098b1-a8ed-4bf6-831a-3d33b0fe4b08">

### Related issues

 #36935

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
This one required significant changes in Airflow. There any existed options for the change the behavior of the DAG/Task thought the UI. Only thought the configurations (explicit or cluster policies) or by the code.

So I guess it might comes thought AIP (Airflow Improvement Proposals) first, see: https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals

But lets see what the other say.

**Comment by ruettere** [comment]
Hi, this variable is really helpful. Is it intended to be GA in the near future?

**Comment by ashb** [comment]
@ruettere This was merged into 2.9. If that isn't available in 3.3 anymore please open a new issue.
