### ISSUE TITLE
Show task_failed_deps on for scheduled tasks in Task Instance Details panel

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#38189]
### Description

There is a cli command `task_failed_deps` that produces a human-readable explanation for what dependencies a task needs to meet to progress to queued. I think when you click on a task that is in `scheduled`, you should see a button that, if you press it, produces the output of that command.

### Use case/motivation

Users are sometimes confused as to why a task is still in scheduled. Not all users have cli access or scheduler logs easily available.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
This is in the legacy task page. We should add it to react and only show it when the task state is scheduled.

**Comment by eladkal** [comment]
Why do we need a button?
If we know why a task is delayed it should be explained on the task detail page

**Comment by bbovenzi** [comment]
I updated the title, no need for a button. Just check if the task instance is `scheduled` or not.
