### ISSUE TITLE
Getting dags from dagbag is failing

### ISSUE THREAD

**Issue by sktemkar** [apache/airflow#38235]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

After the upgrade of airflow version from 2.6.1 to 2.7.1 or 2.7.3, I am facing error in simple code of extracting dags list from dagbag. I tried to increase the setrecursionlimit to 10k, but its failing after trying for few hours.
```python
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.models import DagBag

def list_dags():
    print(f"Available DAGs:")
    dagbag = DagBag('/opt/airflow/dags', include_examples=False, safe_mode=True)
    for dag_id in dagbag.dag_ids:
        print(dag_id)

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2022, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'list_dags',
    default_args=default_args,
    description='A DAG to list all other DAGs in the dags folder',
    schedule_interval=None,  # Set your desired schedule interval or use None for manual triggering
)

list_dags_task = PythonOperator(
    task_id='list_dags_task',
    python_callable=list_dags,
    dag=dag,
)
```
ERROR
```
RecursionError: maximum recursion depth exceeded during compilation
[2024-03-15, 23:47:12 AEDT] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags
[2024-03-15, 23:47:30 AEDT] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/access.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/access.py", line 12, in <module>
    sys.setrecursionlimit(10000)
RecursionError: cannot set the recursion limit to 10000 at the recursion depth 10015: the limit is too low
```
### What you think should happen instead?

It should be able to read all the dags list and print the dag_id.

### How to reproduce
```python
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.models import DagBag

def list_dags():
    print(f"Available DAGs:")
    dagbag = DagBag('/opt/airflow/dags', include_examples=False, safe_mode=True)
    for dag_id in dagbag.dag_ids:
        print(dag_id)

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2022, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'list_dags',
    default_args=default_args,
    description='A DAG to list all other DAGs in the dags folder',
    schedule_interval=None,  # Set your desired schedule interval or use None for manual triggering
)

list_dags_task = PythonOperator(
    task_id='list_dags_task',
    python_callable=list_dags,
    dag=dag,
)
```
### Operating System

Azure Aks 1.26.9 ubuntu

### Versions of Apache Airflow Providers

2.7.1/2.7.3

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@sktemkar I took the code you provided (although I had to modify it slightly - different DagBag directory and using `from airflow.operators.python` instead - but I was unable to replicate your issue on Airflow v2.8.3.

Can you review on a newer Airflow version?  If it still occurring then I might suggest that the problem lies within the contents of your DagBag directory rather than an issue with Airflow itself.

**Comment by sktemkar** [comment]
> Hello @sktemkar were you able to find solution to it?

hi @toaryangupta Yes, the issue was with one dag with bad code. I corrected the dag and the dags appeared in UI. Also, try to increase the dag_file_processor_timeout for the dag to get parsed and appear in UI.
