### ISSUE TITLE
Triggering a inactive dag manually makes the dag active which leads to making the dag, and the subsequent run is also triggered at the next scheduled time

### ISSUE THREAD

**Issue by mittalsarthak** [apache/airflow#38242]
### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment]
@mittalsarthak I think we'd need some more details before anyone can look into this. Please share what exactly you're doing as well as some screenshots of what you see would help.

**Comment by aritra24** [comment]
Also it would in general be advised to follow the issue template as it helps with some of the preliminary analysis without needing back and forths.
