### ISSUE TITLE
Dag trigger confirmation popup for Production Environment

### ISSUE THREAD

**Issue by maycuatroi1** [apache/airflow#38284]
### Description

My team and I are currently working with Airflow, and we manage multiple environments: Development, Staging, and Production. Occasionally, we need to access the Production Airflow to read logs for data analysis. However, we've encountered an issue three times where a team member accidentally triggered a DAG in the Production environment.

I'm wondering if there is an existing solution to prevent this?

If not, I'd like to suggest a feature where if the environment is set to Production, Airflow would display a confirmation popup before triggering a DAG. This would ask the user to confirm if they indeed wish to proceed with the trigger.

### Use case/motivation

To prevent accidental triggering of DAGs in the Production environment by adding an additional layer of confirmation for user actions.

### What would you like to happen?
 I'd like Airflow to display a confirmation popup asking for user confirmation before allowing a DAG to be triggered in the Production environment.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
   - https://github.com/apache/airflow/pull/38299

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can definitely propose a PR with  feature like that.
