### ISSUE TITLE
"Task stuck in queued" should not count against retries

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#38304]
### Description

I think Airflow should have a configureable number of attempts for re-attempting to launch a task if it was killed for being stuck in queued for too long. Currently, such re-attempts consume task retries, but these are conceptually distinct from a task failing to run at all.

### Use case/motivation

On a certain task that happens to not be idempotent, an Airflow user sets retries to zero intentionally, as a human will need to examine if the task can be safely retried or if manual intervention is necessary. However, if the same task is killed for being stuck in queued, the task never started, so the lack of idempotency does not matter and the task should definitely be re-attempted. Airflow currently does not allow a user to express this set of preferences.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by AMK9978** [comment]
@potiuk As a new contributor to Airflow, I would like to work on this issue!

**Comment by AMK9978** [comment]
@potiuk 
Unfortunately, I have had difficulties running the project and its test although the code of this feature may not be complex. I may add an issue about my problem because I didn't find anything relevant to it. I unassigned myself.

**Comment by Bowrna** [comment]
Could i check this issue @potiuk ?

**Comment by potiuk** [comment]
Assigned you

**Comment by Bowrna** [comment]
@potiuk Currently if the task is struck in the queue for a longer time, we fail the task. To have a separate try_number for failed queue task, we may not know during the retry part, why the task failed. Like if it's due to fail on the run or fail due to struck in the queue.  How do you think we can handle this case? 

https://github.com/apache/airflow/blob/0af5d923d99591576b3758ab3c694d02dbe152bf/airflow/jobs/scheduler_job_runner.py#L1541-L1576

**Comment by Bowrna** [comment]
The retry logic handled here in taskinstance.py. It is failed and therefore checks if its eligible for retry, if yes its queued again.
But having another logic like FAILED_IN_QUEUE and TRY_NUMBER_FOR_QUEUE to handle the queue failed task makes sense to me for now. If you see other way, please let me know.
https://github.com/apache/airflow/blob/b6ff085679c283cd3ccc3edf20dd3e6b0eaec967/airflow/models/taskinstance.py#L2992-L3015

**Comment by potiuk** [comment]
The thing is that task_instance is not created yet because ... the task is in the queue. So what needs to happen is that the whole logic should happen in scheduler - becuase it's the scheduler (and to be precise - executor) that realizes that task is queued state. And it should be a different handling in executor, not in task instance -that's the whole complexity of the task.

**Comment by Bowrna** [comment]
> The thing is that task_instance is not created yet because ... the task is in the queue. So what needs to happen is that the whole logic should happen in scheduler - becuase it's the scheduler (and to be precise - executor) that realizes that task is queued state. And it should be a different handling in executor, not in task instance -that's the whole complexity of the task.

@potiuk task_instance would be created with state as queued right? i could understand this should be handled in executor part as how the _fail_tasks_stuck_in_queued is handled. But I can see that TI models are queried to find the queued tasks and that could mean that task_instance object is created. If I am missing to understand the point you have specified, please let me know.

https://github.com/apache/airflow/blob/0af5d923d99591576b3758ab3c694d02dbe152bf/airflow/jobs/scheduler_job_runner.py#L1541-L1576

**Comment by potiuk** [comment]
it's good understanding - it should likely be done somewhere there.

**Comment by Bowrna** [comment]
@collinmcnulty I know this is a long time, but can you share with me the executor type on which these task instances are running.

**Comment by collinmcnulty** [comment]
@Bowrna Mine were running on celery executor, but I think the solution ought to be agnostic to the executor used.

**Comment by Bowrna** [comment]
@collinmcnulty I have tagged you in this link https://github.com/apache/airflow/pull/39398#issuecomment-2227829264 and we can have further conversation on this part in that PR.

**Comment by eladkal** [comment]
I think this issue is solved by https://github.com/apache/airflow/pull/44158 ?

**Comment by collinmcnulty** [comment]
Yes, that’s correct. Closing.
