### ISSUE TITLE
Add legend for average task runtime graph

### ISSUE THREAD

**Issue by simond** [apache/airflow#38420]
### Description

When clicking on a task in the grid view, a newly-created chart that shows the duration of the tasks shows two reference lines. It is not clear what these reference lines mean and there should be a legend that describes what they are. Is one the average duration and the other the median duration? 

![image](https://github.com/apache/airflow/assets/421551/c76dff91-f125-4fc5-a181-ae6ff16fc40f)

I think it would make sense to have a legend either below or beside the graph to describe what the reference lines are.

### Use case/motivation

The motivation is to allow users to understand what the lines on the chart represent. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Yes I mentioned it also in https://github.com/apache/airflow/pull/38214#issuecomment-2002074774
cc @tirkarthi

**Comment by tirkarthi** [comment]
Yes, it was decided to keep mean and not average. The blue line is mean task run duration. The gray line is mean queued duration.
