### ISSUE TITLE
SparkKubernetes doesn't work with the "application_file" kwarg

### ISSUE THREAD

**Issue by eylonronen** [apache/airflow#38537]
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==8.0.0

### Apache Airflow version

2.8.2

### Operating System

-

### Deployment

Official Apache Airflow Helm Chart

### What happened

When using the "application_file" kwarg and passing a yaml file path the operator fails because it tries to open a file that is not found.
The issue is that because application_file is a template_field and "yaml" is a template_ext, Airflow reads the yaml file, renders the jinja template and sets the attribute to be the content of the file, which then in "manage_template_specs" method the operator tries to open (that's the 2nd time) and fails

### What you think should happen instead

passing a path to an application file using the application_file should work without failures

### How to reproduce

Use the SparkKubernetesOperator with the application_file kwarg without failures

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/issues/38017
- https://github.com/apache/airflow/pull/38035

So in the next release it should be fixed
