### ISSUE TITLE
Add `mssql` test integration 

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#38577]
### Body

After removal Microsoft SQL Server as DB Backend (https://lists.apache.org/thread/pgcgmhf6560k8jbsmz8nlyoxosvltph2) we lost an ability to run unit tests over MS SQL database. All unit tests which rely on mssql moved into the integration tests (see https://github.com/apache/airflow/pull/38530):
- `tests/providers/apache/hive/transfers/test_mssql_to_hive.py` -> [`tests/integration/providers/apache/hive/transfers/test_mssql_to_hive.py`](https://github.com/apache/airflow/blob/main/tests/integration/providers/apache/hive/transfers/test_mssql_to_hive.py)
- `tests/providers/google/cloud/transfers/test_bigquery_to_mssql.py` -> [`tests/integration/providers/google/cloud/transfers/test_bigquery_to_mssql.py`](https://github.com/apache/airflow/blob/main/tests/integration/providers/google/cloud/transfers/test_bigquery_to_mssql.py)
- `tests/providers/google/cloud/transfers/test_mssql_to_gcs.py` -> [`tests/integration/providers/google/cloud/transfers/test_mssql_to_gcs.py`](https://github.com/apache/airflow/blob/main/tests/integration/providers/google/cloud/transfers/test_mssql_to_gcs.py)

We should eventually add MS SQL as available option for integration tests, and make to possible to run integration tests with it

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
Please assign me :)
