### ISSUE TITLE
Add `drill` test integration

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#38578]
### Body

During https://github.com/apache/airflow/pull/38530 we found that for a long time (since initial commit to the provider TBH) configured to invalid DB Backend.  Unit test which moved into the integration tests:
- `tests/providers/apache/drill/operators/test_drill.py` -> [`tests/integration/providers/apache/drill/operators/test_drill.py`](https://github.com/apache/airflow/blob/main/tests/integration/providers/apache/drill/operators/test_drill.py)

We should eventually add Apache Drill as available option for integration tests, and make to possible to run integration tests with it

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
I'll `drill` it down, please assign me :)
