### ISSUE TITLE
Avoid to use sync (with blocking io) functions into the `WorkflowTrigger`

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#38672]
### Body

After last refactoring (https://github.com/apache/airflow/pull/36916) `airflow.triggers.external_task.WorkflowTrigger` start more actively use blocking IO - request to DB with non-async drivers.

Instead of direct call sync method, it should be wrapped in one of the common practice to run sync code into async loop:
- [`asyncio.to_thread`](https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread) Python 3.9+, for backward compatible with Python 3.8 it should use [`asyncio.loop.run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)
- [`asgiref.sync.sync_to_async`](https://docs.djangoproject.com/en/stable/topics/async/#asgiref.sync.sync_to_async)
- [`anyio`](https://anyio.readthedocs.io/en/stable/) ???

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by stevenschaerer** [comment]
take
