### ISSUE TITLE
Provide option to cancel job runs in DatabricksRunNowOperator

### ISSUE THREAD

**Issue by subham611** [apache/airflow#38695]
### Description

We are using apache airflow databricks operator to manage spark streaming jobs. When we submit a new streaming job after code update, DatabricksRunNowOperator simply queue new job. But what we need is a option to cancel existing run and submit a new job.
There should be an option to cancelExistingRun before submitting a new job run.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
Hi, thanks for submitting this issue. As you mentioned, you're willing to submit a PR, I'll assign this to you

**Comment by SubhamSinghal** [comment]
@Lee-W Please review this PR: https://github.com/apache/airflow/pull/38702
