### ISSUE TITLE
Performance Issues on Initial Page Load

### ISSUE THREAD

**Issue by vchiapaikeo** [apache/airflow#38776]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

We have started to notice more slowness on initial page load. On our deployment, it takes nearly 6s for the server to respond. 

<img width="1512" alt="image" src="https://github.com/apache/airflow/assets/9200263/0fc199ff-7594-40cb-99ba-6b679ef87aa4">

We started to do some analysis of the queries that are being run and we found 3 that take over 1400ms (and likely are being run serially).

1. Getting running dags -1.4s
1. Getting failed dags - 1.8s
1. Populating the dags and data in the html table itself (which defaults to 25 and we've set to 100 but we don't see much improvement when we lower it - only 500ms at most) - 1.6s

<img width="1346" alt="image" src="https://github.com/apache/airflow/assets/9200263/4c76f95d-5e6c-4492-82e8-8986bb3c9f9e">

All of these queries are attached in the following txt file with explain plans and explain analyzes:

[slow_queries_on_initial_load.txt](https://github.com/apache/airflow/files/14885813/slow_queries_on_initial_load.txt)

### What you think should happen instead?

We are wondering if there are any ways we could possibly improve the performance of initial page load. Some ideas that come to mind:

1. Caching with short ttls that are invalidated intelligently
2. Improved indexing strategies
3. Concurrent/async query execution
4. Your idea here!

### How to reproduce

Add ~2-4k dags to an Airflow deployment and reload the initial page

### Operating System

Debian 11

### Versions of Apache Airflow Providers

N/A

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

We deploy our cluster on GCP's GKE

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @ephraimbuddy @bbovenzi

**Comment by pankajkoti** [comment]
hi @vchiapaikeo , were you able to make progress on this?  Would like to learn if you added any additional indexes or so and would be more than happy to collaborate with you on this one.

**Comment by vchiapaikeo** [comment]
Hey @pankajkoti ! Yes, that would be wonderful! The only thing I can think of from looking at the queries and the explain plan is something around the dag table - since there already is an index on dag_run and the state col. Based on those explain plans, perhaps something on the dag table around dag_id, is_subdag, and is_active? I see two existing indices on dag right now:

```sql
CREATE INDEX idx_root_dag_id
   ON dag (root_dag_id ASC);

CREATE INDEX idx_next_dagrun_create_after
   ON dag (next_dagrun_create_after ASC);
```

The other thing I was thinking about (but have just been very slow to implement and try) is a ThreadPool for some of the queries in the /home route. The slow queries are [here](https://github.com/apache/airflow/blob/main/airflow/www/templates/airflow/dags.html#L148-L157) and are retrieved from [this call](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L739). These get loaded serially here --> https://github.com/apache/airflow/blob/main/airflow/www/views.py#L858-L859

My thought is that [these queries](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L847-L859) plus [this one](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L915-L921) can all get submitted to a threadpool for execution so that they run concurrently. Wanted to get the teams' thoughts on that and if you think it would work. The implementation shouldn't be too bad.

**Comment by tirkarthi** [comment]
Related work on making sql queries async. cc @hussein-awala 

https://github.com/apache/airflow/pull/36504

**Comment by vchiapaikeo** [comment]
@hussein-awala , a ThreadPoolExecutor implementation would be easier to get going intially but my guess is that the switch to async calls here makes more sense overall and would be cleaner. Let me know what ya think when you have a few mins!

**Comment by sunank200** [comment]
These queries(https://github.com/apache/airflow/blob/main/airflow/www/views.py#L855, https://github.com/apache/airflow/blob/main/airflow/www/views.py#L860, https://github.com/apache/airflow/blob/main/airflow/www/views.py#L866 and so on) run serially as mentioned by @vchiapaikeo. I tried running these locally with 4000 DAGs and it took 1.86 seconds to show the running DAGs. Running these key database queries concurrently in the index method using ThreadPoolExecutor improves the performance.

**Comment by vchiapaikeo** [comment]
Right, makes sense - it sounds like the best solution then may be to wait for @hussein-awala 's AIP on introducing async SQLAlchemy sessions into the codebase (seems like they will start with connections and variables first) and then calling these db functions asynchronously on the webserver. Wdyt?

**Comment by pankajkoti** [comment]
> @pankajkoti have you tried adding additional indexes as suggested in the thread? I tried it in my local setup using breeze but it doesn't seem to improve the performance drastically.

@sunank200 yes, I did try adding few indexes based on the SQL queries that get fired but I did not observe any improvement either

**Comment by sunank200** [comment]
> Right, makes sense - it sounds like the best solution then may be to wait for @hussein-awala 's AIP on introducing async SQLAlchemy sessions into the codebase (seems like they will start with connections and variables first) and then calling these db functions asynchronously on the webserver. Wdyt?

Sure. Waiting for @hussein-awala AIP.
