### ISSUE TITLE
Default credentials cause warnings on Google Chrome after logging in to Airflow's UI

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#38797]
### Official Helm Chart version

main (development)

### Apache Airflow version

dev

### Kubernetes Version

N/A

### What happened

In recent months, Google made some changes to Chrome, causing a data breach warning when logging in to Airflow's UI using the default credentials (username: `admin`, password: `admin`) — see attached.
<img width="801" alt="admin_admin" src="https://github.com/apache/airflow/assets/60007259/4d7bde53-cacb-4e24-8d9e-9f4b30927f8b">
It used to be even more annoying by being "sticky", i.e., that the only way to get rid of it without changing the credentials is to reenter Airflow's UI from another tab - but it seems that it is no longer so.
When logging in via another common browsers (e.g., Firefox), it doesn't happen

Unfortunately, I didn't find a way to cancel it via Chrome's settings.

### What you think should happen instead

I thought that it would be appropriate to bring it to the attention of the community as this warning is quite annoying for Chrome users (especially for contribution purposes), so as long as there is no good option to disable this warning from Chrome's settings -  I assume that the options are any of the following:
1. Change the default credentials into a less trivial combination to avoid these warnings for Chrome users (e.g., `admin:airflow,` `airflow:airflow,` etc.).
2. Keep the current behavior and add some documentation about it.
3. As there could be some heavy consequences due to the first option, it might be better to make the default credentials customizable, at least when running with `breeze` configuration.

### How to reproduce

Easiest with `breeze`:
1. Use the latest Chrome Version (as of writing these lines: 123.0.6312.106).
2. Run `breeze --start-airflow`
3. Log in to Airflow's UI with the default credentials (`admin`, `admin`).
4. Wait for the warning to pop up.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
I would rather address this issue to the Google, because it annoys everywhere, even if host is localhost, and there is no easy way to turn it of for specific dev endpoint. The idea of warning interesting but it lead to the situation, that users, especially devs, would rather turn it of completely

**Comment by shahar1** [comment]
> I would rather address this issue to the Google, because it annoys everywhere, even if host is localhost, and there is no easy way to turn it of for specific dev endpoint. The idea of warning interesting but it lead to the situation, that users, especially devs, would rather turn it of completely

Unfortunately, Chrome is not an open source, so I'm not sure what the address is in this case.
As we agree that this issue is annoying, wouldn't it be better for now to be able to override the default credentials on-demand when working on `breeze`?

**Comment by Taragolis** [comment]
> but unfortunately, Chrome is not an open source, so I'm not sure what the address is in this case.

AFAIK, Chrome bugs could be reported/tracked on Chromium bug tracker: https://issues.chromium.org/issues

There is also some close related bugs already opened: https://issues.chromium.org/issues?q=status:open%20data%20breach

**Comment by shahar1** [comment]
I'm closing this as a Wontfix. This is a very Chrome-specific issue that can be solved easily by using anonymous mode or by using another browser. Even in normal settings - it's less annoying than before.
