### ISSUE TITLE
Backfill reporting "skipped" tasks as "waiting"

### ISSUE THREAD

**Issue by jjfine** [apache/airflow#388]
Using 1.5.1, LocalExecutor, and the example_branch_operator.

Run `airflow backfill example_branch_operator -s2015-09-01 -e2015-09-02` and it will never finish.

You'll just get this log line repeating forever:
`INFO - [backfill progress] waiting: 12 | succeeded: 8 | kicked_off: 8 | failed: 0 | skipped: 0`

The UI properly shows these tasks were skipped.

**Comment by mistercrunch** [comment]
Do you have a zombie task instance that is flagged as running but not actually running? Clear it!
