### ISSUE TITLE
DAGs are able to see historical dataset events when created new / disabled - enabled / deleted - recreated.

### ISSUE THREAD

**Issue by tosheer** [apache/airflow#38826]
### Apache Airflow version

2.9.0b2

### What happened?

* If a new dataset triggreed DAG is created for an already existing dataset. (Dataset has already existing dataset events)
    * DAG catch up false.
        * DAG see all dataset events from very first event for dataset.
    * DAG catch up true.
        * DAG see all dataset events from very first event for dataset.
* If a dataset triggreed DAG is disabled and then enabled back. (In b/w disable and enable of the DAG dataset events)
    * DAG catch up false.
        * DAG see all dataset events received during the timeframe when DAG was disabled.
    * DAG catch up true.
        * DAG see all dataset events received during the timeframe when DAG was disabled.
* If a dataset triggreed DAG is deleted and then recreated back keeping dag_id same. (In b/w delete and recreate of the DAG dataset events)
    * DAG catch up false.
        * DAG see all dataset events received during the timeframe when DAG was not enabled.
    * DAG catch up true.
        * DAG see all dataset events received during the timeframe when DAG was deleted.

### What you think should happen instead?

* If a new dataset triggreed DAG is created for an already existing dataset. (Dataset has already existing dataset events)
    * DAG catch up false.
        * Expected behaviour: DAG should see all the dataset events from the time when DAG was enabled.
        * Actual Behaviour: DAG see all dataset events from very first event for dataset.
    * DAG catch up true.
        * Expected behaviour: DAG should see all the dataset events from the time when DAG was created.
        * Actual Behaviour: DAG see all dataset events from very first event for dataset.
* If a dataset triggreed DAG is disabled and then enabled back. (In b/w disable and enable of the DAG dataset events)
    * DAG catch up false.
        * Expected behaviour: DAG should see all the dataset events from the time when DAG was enabled back.
        * Actual Behaviour: DAG see all dataset events received during the timeframe when DAG was disabled.
    * DAG catch up true.
        * Expected behaviour: DAG see all dataset events received during the timeframe when DAG was disabled.
        * Actual Behaviour: DAG see all dataset events received during the timeframe when DAG was disabled.
* If a dataset triggreed DAG is deleted and then recreated back keeping dag_id same. (In b/w delete and recreate of the DAG dataset events)
    * DAG catch up false.
        * Expected behaviour: DAG should see all the dataset events from the time when DAG was enabled and not all the events received during the timeframe when DAG was deleted or recreated and not enabled.
        * Actual Behaviour: DAG see all dataset events received during the timeframe when DAG was not enabled.
    * DAG catch up true.
        * Expected behaviour: DAG should see all the dataset events from the time when DAG was recreated and not all the events received during the timeframe when DAG was deleted.
        * Actual Behaviour: DAG see all dataset events received during the timeframe when DAG was deleted.

### How to reproduce

* Create a new DAG which has dataset event producer. Enable both the producer.
* Run producer dag multiple times.
* Create a new consumer DAG which also get triggered from same dataset with catchup false.
* Enable the new DAG.
* You will see new DAG will run as soon as enabled and see very first event in the dataset.
* In the next run whenever that was scheduled DAG will get all the events other than the first event it has already consumed.

```from __future__ import annotations

import pendulum

from airflow.datasets import Dataset
from airflow.models.dag import DAG
from airflow.operators.bash import BashOperator

# [START dataset_def]
poc_dag1_dataset = Dataset("test-cluster/test-schema/test-table")
poc_dag2_dataset = Dataset("test-cluster/test-schema/test-table2")
poc_dataset_consumes_check = Dataset("test-cluster/test-schema/test-table-check")
poc_dataset_consumes_check2 = Dataset("test-cluster/test-schema/test-table-check2")


def _write2_post_execute(context, _):
    context["dataset_events"]["test-cluster/test-schema/test-table"].extra = {"x_tk": 1}


with DAG(
    dag_id="poc_dataset_produces_1",
    catchup=False,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    schedule="@daily",
    tags=["produces", "dataset-scheduled"],
) as dag1:
    # [START task_outlet]
    BashOperator(
        outlets=[poc_dag1_dataset], 
        task_id="producing_task_1", 
        bash_command="sleep 5",
        post_execute=_write2_post_execute,
    )
    # [END task_outlet]
```

After this add  
```
# [START dag_dep]
with DAG(
    dag_id="poc_dataset_consumes_1",
    catchup=False,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    schedule=[poc_dag1_dataset],
    tags=["consumes", "dataset-scheduled"],
) as dag3:
    # [END dag_dep]
    BashOperator(
        task_id="consuming_1",
        bash_command='echo "ti_key={{ triggering_dataset_events }}"',
    )
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### Deployment details

Plain vanilla airflow.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I agree with the `catchup=False` expectations. Not sure about the `True` ones. When doing timed scheduling (i.e. timetables), we use `start_date` to decide how far back to catch up, and I think we should use the same mechanism, not based on when a DAG is (re)created. You could argue this is not smart enough (and I would agree), but now is not the time to change this.

**Comment by uranusjr** [comment]
On the implementation front—the `catchup=True` case is not too difficult to implement, but `catchup=False` presents problems. When scheduling against time, we can simply create a DAG run in the future because we know when that’ll happen, and that future run also acts as the cutoff point in subsequent iterations for how long the scheduler should look back. With event-based scheduling, however, we don’t know when the next run will happen, and need another way to tell the scheduler when to stop looking into the past.

We could add a new field on `DagModel` for this (say a datetime field `last_unpause`). Alternatively… maybe we can cheat instead and create one run from the most recent past events? Once that one run exists, the scheduler would know not to look past it in later iterations. Are there other solutions? I would love some ideas.

**Comment by Lee-W** [comment]
`DagModel.ast_unpause` sounds like a reasonable choice. But I thought DDRQs are only added to active DAGs? If that's the case, why would the DAG with `catchup=False` looks for past events 🤔 Or maybe we need to check whether the DAG is pausing when creating DDRQ?

**Comment by uranusjr** [comment]
> DDRQs are only added to active DAGs

Are they? From what I can tell all DAGs are referenced. The code creating DDRQs uses `consuming_dags`, which is based on the through table `DagScheduleDatasetReference`, which does not exclude inactive DAGs.

Maybe the right fix is to only create entries in `DagScheduleDatasetReference` for active DagModel rows, or add additional logic in `consuming_dags` to only include active DAGs.

**Comment by tosheer** [comment]
@Lee-W I have checked event when DAGs are deleted/ disabled its entry from `dag_schedule_dataset_reference` is not deleted which lead to addition of entry in `dataset_dag_run_queue` when an event is received. On event consumer side no check is in place it just check and provide all the events from the last run.

For more details see https://github.com/apache/airflow/blob/main/airflow/jobs/scheduler_job_runner.py#L1260-L1274.

@uranusjr do you think its a reasonable fix for the consumption path
` dataset_event_filters.append(DatasetEvent.timestamp > DagScheduleDatasetReference.created_at)`

```
                dataset_event_filters = [
                    DagScheduleDatasetReference.dag_id == dag.dag_id,
                    DatasetEvent.timestamp <= exec_date,
                ]
                if previous_dag_run:
                    dataset_event_filters.append(DatasetEvent.timestamp > DagScheduleDatasetReference.execution_date)
                else:
                    dataset_event_filters.append(DatasetEvent.timestamp > DagScheduleDatasetReference.created_at)

                dataset_events = session.scalars(
                    select(DatasetEvent)
                    .join(
                        DagScheduleDatasetReference,
                        DatasetEvent.dataset_id == DagScheduleDatasetReference.dataset_id,
                    )
                    .where(*dataset_event_filters)
                ).all()
```

```

**Comment by uranusjr** [comment]
> * As soon an a DAG is deleted remove entry from dag_schedule_dataset_reference so that entries are not added in the dataset_dag_run_queue table for any of the dataset events.

I don’t think we need to do that. Instead, the query to `dag_schedule_dataset_reference` can check if a DAG has been paused or deleted (actually deactivated; if the row is actually _removed_ the database automatically propogates the deletion via foreign key). This way we only need to handle the comsuming side.

**Comment by uranusjr** [comment]
See #38891 for a possible solution.
