### ISSUE TITLE
White INFO log is hard to read

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#38844]
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

2.9.0

### What happened?

White INFO log is hard to read

![image](https://github.com/apache/airflow/assets/31843161/aff517de-6a21-4043-b1a3-cd13156c9682)

### What you think should happen instead?

use normal black font color

### How to reproduce

use airflow 2.9.0 with some KubernetesPodOperator outputting random INFO logs

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.19.0
apache-airflow-providers-celery==3.6.1
apache-airflow-providers-cncf-kubernetes==8.0.1
apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-fab==1.0.2
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-postgres==5.10.2
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-sqlite==3.7.1

### Deployment

Other Docker-based deployment

### Deployment details

celery executor, on-premise kubernetes 1.26.5, postgres 13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Does the logs returned from API have ansi code that causes this? 

cc: @jscheffl

**Comment by romanzdk** [comment]
> Does the logs returned from API have ansi code that causes this? 
yes. maybe we can have some logs background color switch? or some override mechanism for the logs color?

**Comment by jscheffl** [comment]
Actually after this change we ran into the same pitfall. A lot of logs are colored and if a dark mode terminal is used (e.g. github/VSCode) then nobody notices that explicit color is set to WHITE.
From perspective of usability you could blame Airflow but the log view just does not implement a dark mode. An application emitting logs should not assume your terminal is in dark mode. Would be the same if you set log output to black text color and then dark mode is not working.

Mainly depending on which application you use. For example we had https://pypi.org/project/colorlog/ and colors are defined like:
```
default_log_colors = {
    "DEBUG": "white",
    "INFO": "green",
    "WARNING": "yellow",
    "ERROR": "red",
    "CRITICAL": "bold_red",
}
```
In such cases WHITE need to be removed. If you remove the color then this log level does not apply any coloring and use standard system terminal colors.

**Comment by jscheffl** [comment]
There is a future improvement planned to support dark mode in Airflow wen UI, but this will take some time. Current log window colors are not configurable (background and font colors)

**Comment by romanzdk** [comment]
Alright. We are gonna try to solve this with changing color settings for our info logs (i.e. deleting the explicit color setting for it). Thanks!
