### ISSUE TITLE
Change the UI color for ExternalSensor tasks

### ISSUE THREAD

**Issue by Timelessprod** [apache/airflow#38845]
### Description

With the recent update of the graph display in DAGs, there's a visibility issue regarding external task sensors. Indeed those tasks have a `#19647e` tile color while the status & operator name are displayed in `--chakra-colors-gray-500` (aka `#718096`) on top of it, which makes the text unreadable. You can see a screenshot below:

<img width="239" alt="Current situation" src="https://github.com/apache/airflow/assets/69579602/8497faa7-9a61-4e59-a0ff-576844cfe67f">

I can submit a PR for it if needed but I'm unsure if there's a chart regarding which color to give to what type of operator etc. so please tell me. My idea would be to use same tint but lighter color like `#4db7db` which is more readable (see below) but not perfect for accessibility:

<img width="239" alt="Suggested new color" src="https://github.com/apache/airflow/assets/69579602/e2fa562b-668f-4756-9ef0-421d5da3280e">

### Use case/motivation

The current color makes monitoring and debugging very annoying as it's unreadable. It is also a big issue regarding accessibility as color-blind people may not be able to guess the status name by the status color. As an argument, it was red flagged by Chrome Lighthouse when I ran a test on the webpage.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by idantepper** [comment]
Hi, I would like to take this issue
