### ISSUE TITLE
401 UNAUTHORIZED when using AUTH_ROLE_PUBLIC = "Admin"

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#38900]
### Body

When using 

```
AUTH_ROLE_PUBLIC = 'Admin'
```

And not logged in...

Some webserver endpoints return 401 UNAUTHORIZED

E.g.

![image](https://github.com/apache/airflow/assets/15932138/930cff14-2a33-4d50-b921-fc4dac6a8027)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by phanikumv** [comment]
cc @Lee-W could you please look into it tomorrow

**Comment by Lee-W** [comment]
Sure 👍
