### ISSUE TITLE
Remove extra slash from update_job_permission api

### ISSUE THREAD

**Issue by SubhamSinghal** [apache/airflow#38919]
### Apache Airflow Provider(s)

databricks

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.2.0
apache-airflow-providers-common-sql==1.10.0
apache-airflow-providers-databricks==6.1.0
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.8.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-sqlite==3.7.0

### Apache Airflow version

2.8.1

### Operating System

ubuntu

### Deployment

Google Cloud Composer

### What happened

Update job permission failed due to extra slash 

### What you think should happen instead

Update job permission should have updated job permissions

### How to reproduce

Create a job config with access control list.

```
 access_control = [{
            "group_name": "abc",
            "permission_level": "CAN_MANAGE_RUN"
        }]
```
In the first run CreateJobOperator updates ACL properly. Now update ACL list and run CreateJobOperator again.

 ```
access_control = [{
            "group_name": "abc",
            "permission_level": "CAN_MANAGE_RUN"
        },
        {
            "group_name": "def",
            "permission_level": "CAN_MANAGE_RUN"
        }
]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/38918
@SubhamSinghal you can always open PR directly, no need to open issue first
