### ISSUE TITLE
Two buttons to reset password for an airflow user

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#38922]
### Apache Airflow version

2.9.0

### What happened?

There are two buttons under "Show User" section to reset password, one called "Reset password" and the other "Reset my password". Both seem to be redirecting to the same modal.

![image](https://github.com/apache/airflow/assets/35884252/511559b7-b032-4255-93a9-73d4edbe37c5)

One redirects to: http://localhost:28080/resetpassword/form?pk=1 and the other redirects to http://localhost:28080/resetpassword/form

### What you think should happen instead?

We should not have duplicates for this, and one button can be removed unless they both do different things.

### How to reproduce

1. Install latest airflow and run it with breeze: `breeze start-airflow --dev-mode`
2. Navigate to Security -> Show User (on any existing user)
3. Click on the buttons in the footer

### Operating System

NA

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
cc @bbovenzi @pierrejeambrun to check if this is expected.

**Comment by potiuk** [comment]
Related to https://github.com/apache/airflow/issues/37030 - yes it's like that and it definitely could be improved.

**Comment by aritra24** [comment]
I believe this should be fairly easy to do, just need to remove the extra action from [here](https://github.com/apache/airflow/blob/main/airflow/providers/fab/auth_manager/views/user.py#L81) similar to how edit was removed.

**Comment by amoghrajesh** [comment]
> Related to #37030 - yes it's like that and it definitely could be improved.

Yes it is related. The related issue will be a bigger enhancement.
