### ISSUE TITLE
You cannot see newer DAG runs if you open a link to a specific DAG run [UI Bug] [New as of 2.9.0?]

### ISSUE THREAD

**Issue by Rafnel** [apache/airflow#38939]
### Apache Airflow version

2.9.0

### What happened?

When I click on a specific DAG run in a DAG, then copy that URL and open it in a new tab, the linked DAG run now appears to be the most recent run of the DAG even if there are newer runs. In other words, the linked DAG run appears as the right-most DAG run on the grid.

### What you think should happen instead?

In previous Airflow versions, you could share the link to a specific DAG run and when opened, the linked run would be highlighted and the user could still see newer runs by scrolling the grid view to the right. I believe it is a bit confusing to link a DAG run and then not be able to see any newer runs from that link without going back to the main DAG page and opening the DAG from there.

If this is intended behavior, maybe we should include a button that resets the user's view so that they can see newer runs. I don't see a way to reset my view and find newer runs without completely leaving the page.

### How to reproduce

1. Open a DAG with multiple runs. Here's a DAG we own which runs once per day. 
![click a dag](https://github.com/apache/airflow/assets/18747511/d7b1fc10-c828-4ba8-a1e5-1426436b3d17)
2. Click on an older run. 
![Select an older run](https://github.com/apache/airflow/assets/18747511/a2a4e5fa-ca07-418b-a4d8-0f74a33114d1)
3. Copy the link to that run. Should be something like:  https://AIRFLOW_URL/dags/DAG_ID/grid?dag_run_id=scheduled__2024-03-27T06%3A30%3A00%2B00%3A00
4. Open it in a new tab. Observe that this run now appears to be the newest run and you can't scroll right or clear the selection or anything. The only way I found to see newer DAG runs is to open the DAG again via its base URL. 
![Can't scroll right](https://github.com/apache/airflow/assets/18747511/e6b1744a-f03e-4954-ac01-2ffd478dd251)

### Operating System

Ubuntu 20.04.6 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-fab==1.0.2
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-ssh==3.10.1

### Deployment

Virtualenv installation

### Deployment details

Self-hosting an Airflow instance on Ubuntu

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @bbovenzi

**Comment by bbovenzi** [comment]
Already working on a fix. PR should be up soon

**Comment by Rafnel** [comment]
Awesome, thank you all!
