### ISSUE TITLE
add blob size to LocalFilesystemToGCSOperator

### ISSUE THREAD

**Issue by JessieZdev** [apache/airflow#38958]
### Description

Hi team,

I hope LocalFilesystemToGCSOperator can add blob size in order to allow users to upload large files without timeout issue. the hook.upload has blob size arg.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
Hi @JessieZdev , please let me know if you're still interested in contributing to this feature. I can assign this to you. Thanks!

**Comment by jsjasonseba** [comment]
Hi, could I take this issue?
