### ISSUE TITLE
Control DAG Executor Assignment through RBAC

### ISSUE THREAD

**Issue by PVK222** [apache/airflow#38966]
### Description

Use RBAC to check DAG owner executors. This enhancement would ensure that only authorized users/processes can access an executor.

### Use case/motivation

Preventing unauthorized DAG to access an isolated executor / better DAG and ressource isolation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
DAGs already have access control feature

https://github.com/apache/airflow/blob/f2e2221bb15c50fb4e9ffefb4abf2bb0fbad70dd/airflow/models/dag.py#L429-L430

Please elaborate on your use case

**Comment by PVK222** [comment]
Can a limit a DAG to acces to a specifique executor only ?

**Comment by PVK222** [comment]
The use case is following.

Executor 1: dedicate to department A

Executor 2: Dedicate to Department B

Developpeur X can only access Exector 1.

**Comment by PVK222** [comment]
I closed the feature request. thank to Gemini, I thought the DAG could indicate an unspecified executor and that you could have many dedicated executors on Airflow.
![image](https://github.com/apache/airflow/assets/166828630/e161a7c2-756f-43a7-b8ed-69a61147e518)
