### ISSUE TITLE
Tasks are in queued state for a longer time and executor slots are exhausted often

### ISSUE THREAD

**Issue by paramjeet01** [apache/airflow#38968]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.3

### What happened?

The tasks are in queued state for longer time than expected. This was working fine in 2.3.3 perfectly.

### What you think should happen instead?

The tasks should be in running state instead being queued.

### How to reproduce

Spin up more than 150 dag run in parallel and the tasks gets queued while it can execute in airflow 2.8.3

### Operating System

Amazon Linux 2

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Without any logs, errors, metrics or details it is impossible to (1) understand your problem and (2) fix anything.

Can you please describe more details?

**Comment by paramjeet01** [comment]
Apologies, I'm relatively new to Airflow. We've checked the scheduler logs thoroughly, and everything seems to be functioning correctly without any errors. Additionally, the scheduler pods are operating within normal CPU and memory limits. Our database, RDS, doesn't indicate any breaches either. Currently, we're running a DAG with 150 parallel DAG runs. However, a significant portion of tasks are remaining in a queued state for an extended period. Specifically, about 140 tasks are queued, while only 39 are actively running. I've already reviewed the configurations for max_active_tasks_per_dag and max_active_runs_per_dag, and they appear to be properly set. We did not face this issue in 2.3.3

**Comment by ephraimbuddy** [comment]
> Apologies, I'm relatively new to Airflow. We've checked the scheduler logs thoroughly, and everything seems to be functioning correctly without any errors. Additionally, the scheduler pods are operating within normal CPU and memory limits. Our database, RDS, doesn't indicate any breaches either. Currently, we're running a DAG with 150 parallel DAG runs. However, a significant portion of tasks are remaining in a queued state for an extended period. Specifically, about 140 tasks are queued, while only 39 are actively running. I've already reviewed the configurations for max_active_tasks_per_dag and max_active_runs_per_dag, and they appear to be properly set. We did not face this issue in 2.3.3

Can you try increasing the `[scheduler]max_tis_per_query` to 512? In one performance debugging, we discovered this to work better when increased but it might depend on the environment

**Comment by paramjeet01** [comment]
I have updated the config map with `max_tis_per_query = 512` and redeployed the scheduler. Will monitor for some time and let you know , thanks for quick response.

**Comment by paramjeet01** [comment]
@ephraimbuddy , The above config has improved the performance in scheduling the tasks and the gantt view shows the tasks queue time is lesser than before. Also , please share performance tuning documentation that will be really nice of you.

**Comment by tirkarthi** [comment]
@paramjeet01 This might be helpful 

https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/scheduler.html#fine-tuning-your-scheduler-performance

**Comment by paramjeet01** [comment]
@ephraimbuddy , Also saw that the dags were in scheduled state , after restarting the scheduler everything works fine now.

**Comment by paramjeet01** [comment]
This is similar issue to #36998 , #36478

**Comment by changqian9** [comment]
We got the same issues for twice. Same observation, this happened when executor open slots < 0.
<img width="1737" alt="Screenshot 2024-04-14 at 14 21 36" src="https://github.com/apache/airflow/assets/10512672/cec289f7-d68d-49a2-80ef-24fb367de635">
cc @paramjeet01

**Comment by paramjeet01** [comment]
@jscheffl , Can you remove the pending response label.

**Comment by paramjeet01** [comment]
After observing for some time, we encountered instances where the executor open slots were approaching negative values, leading to tasks becoming stuck in the scheduled state. Restarting all the scheduler pods solved this issue.

![9EC59300-B161-4A66-9639-01CDA6ABAF71_1_201_a](https://github.com/apache/airflow/assets/36541629/a32ebe85-57b1-4cdf-83b5-e6ed155e4adb)
![9EC59300-B161-4A66-9639-01CDA6ABAF71_1_201_a](https://github.com/apache/airflow/assets/36541629/98fc59a9-771f-4ea5-b54f-352e83a8dc27)

**Comment by paramjeet01** [comment]
We have also observed that the pods are not cleaned up after completion of the task and all the pods are stuck in SUCCEEDED state.

**Comment by paramjeet01** [comment]
Sorry , the above comment is false positive. We are customizing our KPO and we missed to add `on_finish_action` so the pods stuck in SUCCEEDED state. After adding it , all the pods are removed properly.
We also able to mitigate the executor slots leak by adding a cronjob to restart our schedulers once in a while.

**Comment by dirrao** [comment]
This issue is related to watcher is not able to scale and process the events on time. This leads to so many completed pods over the time. 
related: #22612

**Comment by dirrao** [comment]
@paramjeet01 
You can mention airflow num_runs configuration parameter to restart the scheduler container based on your needs. 
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html

**Comment by dirrao** [comment]
This issue is related to watcher is not able to scale and process the events on time. This leads to so many completed pods over the time.
related: https://github.com/apache/airflow/issues/22612

**Comment by paramjeet01** [comment]
@dirrao ,  airflow num_runs configuration parameter purpose has been changed a while ago AFAIK and cannot be used for restarting the scheduler. We have also removed run_duration which was later used for restarting the scheduler.
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#num-runs 
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#remove-run-duration

**Comment by sunank200** [comment]
If I understood this correctly, the performance issues with tasks in the queued state were mitigated by adjusting max_tis_per_query, scaling scheduler replicas, and implementing periodic scheduler restarts.  @paramjeet01 tried periodic restarts of all scheduler pods to temporarily resolve the issue.

Related Issues: #36998, #22612

**Comment by potiuk** [comment]
Airflow 2.10.3 is now out an it has fix #42932 that is likely to fix the problems you reported, please <author> upgrade, check if it fixed your problem and report back @paramjeet01 ?
