### ISSUE TITLE
Mismatching dates in Run ID and Grid View

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#38977]
### Apache Airflow version

2.9.0

### What happened?

The fact that the date in the Run ID (I think `logical_date`?) and the date displayed in human readable form in the grid view are different is really confusing.

### What you think should happen instead?

The date reflected in the UI should match the date in the default Run ID

### How to reproduce

Run a DAG with the `@hourly` schedule.

### Operating System

n/a

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

<img width="943" alt="image" src="https://github.com/apache/airflow/assets/25823361/c1a1633f-cda4-42d1-9673-caea83d69ccc">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
This looks like a similar report to https://github.com/apache/airflow/issues/35946
