### ISSUE TITLE
How to execute arbitrary SQL in postgres?

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#39]
I'd like to execute a series of SQL statements on Redshift.

I'd planned to use the SqlSensor to do this but failed to read the part of the documentation about executing a statement until a criteria is met. I just need to execute regardless of the result set.

Is there a way of doing this without using the PythonOperator and opening my own postgres connection? It looks as if I want a MySqlOperator for postgres.

**Comment by martingrayson** [comment]
Sorry - I can see there's an option package for postgres (that I even installed) ;) Its just not in the documentation yet.

**Comment by mistercrunch** [comment]
You want to use the `PostgresOperator` documented here:
http://pythonhosted.org/airflow/code.html#airflow.operators.PostgresOperator

Being the scene the operator uses a hook, you can use the hook build other operators (data transfer, sensors, ...) or within PythonOperator, but `PostgresOperator` allows you to do what you described.
http://pythonhosted.org/airflow/code.html#airflow.hooks.PostgresHook

**Comment by martingrayson** [comment]
Thanks mistercrunch :+1: I'm really not sure how I missed that in the documentation !
