### ISSUE TITLE
No way of going back to the DAG page once entering task details

### ISSUE THREAD

**Issue by csp33** [apache/airflow#39023]
### Apache Airflow version

2.9.0

### What happened?

Once entering the Task Details view, there's no way to directly go back to the DAG page.
![image](https://github.com/apache/airflow/assets/28935464/3cee6e6e-e61e-4ca5-82b9-c81803342072)

In Airflow 2.8.4, we could still use the old navigation tabs (i.e `Grid`) to go back to the DAG page
![image](https://github.com/apache/airflow/assets/28935464/d25e3766-f17b-4407-97cf-ee3a0598edb2)

### What you think should happen instead?

There should be a button to go back to the DAG page

### How to reproduce

1. Enter the `More Details` page of a TaskInstance.
2. Try to go back to the DAG page

### Operating System

Airflow in Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ecodina** [comment]
I can confirm this also happens to us. In our case, we use a custom email template, using {{ ti.log_url }}, which redirects to this "new" page without a proper way to view the grid. Another thing I noticed is that at the top right it appears as "Schedule: False".

**Comment by bbovenzi** [comment]
Let's finally finish feature parity with this and the new UI then and redirect to the task page with the appropriate tab selected.

**Comment by AetherUnbound** [comment]
@bbovenzi It actually looks like there's more detail available via the "More Details" link than is present on the Details tab of the grid view. The "Rendered Templates" link is covered sufficiently I believe, but there are tons of other fields that are present there which aren't present on the Details tab. How would you like to proceed? I can get a PR up for the `ti.log_url` change, but it seems like those pages still have some merit and it might be best to add the header @csp33 points to in their screenshot and officially remove the other pages (`/log`, `/task`, and `/rendered-template`) in another issue.

**Comment by bbovenzi** [comment]
Yeah, for 2.9.1 let's add a Grid button in `task_instance.html`. It can be inside the already existing `<ul>` of all the other buttons. That would be a good first issue for anyone to take on.
