### ISSUE TITLE
Graph is empty after update to 2.9.0 on some DAGs

### ISSUE THREAD

**Issue by sicarul** [apache/airflow#39038]
### Apache Airflow version

2.9.0

### What happened?

Since upgrading from 2.8.3 to 2.9.0, some DAGs are now empty

### What you think should happen instead?

Graphs should show in the UI

### How to reproduce

Some times when i open the graph it shows for a fraction of a second and then disappears, and other times i see it completely empty; I'm not sure how to reproduce it, but when i open the dev console i see this, which mentions a shape and then names a model *that is not part of this dag*, which seems even weirder. The dag has a task group if that's relevant:

```
Error: org.eclipse.elk.graph.json.JsonImportException: Referenced shape does not exist: dbt_models.stg_mysql_single_user_organization
```

<img width="1913" alt="image" src="https://github.com/apache/airflow/assets/4952116/c1a7edc1-1735-4f35-9db4-c3208deeab3d">

In case it's relevant, this dag is generated from a single python file that generates dozens of dags from a yaml, not sure if they can somehow be.

An even weirder fact about all this, is that running the same DAG locally using docker-compose, i see the graph just fine, so it's only happening on the hosted version that has exactly the same DAGs and Docker (Maybe some old dag run in the database that had something wrong?)

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon[aiobotocore]==8.20.0
apache-airflow-providers-common-sql==1.12.0
apache-airflow-providers-http==4.10.1
apache-airflow-providers-snowflake==5.4.0
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-redis==3.6.1
apache-airflow-providers-celery==3.6.2

### Deployment

Other Docker-based deployment

### Deployment details

Running on Docker images on AWS ECS

### Anything else?

I am willing to submit a PR but i have no idea where/why this happens, and zero knowledge of Airflow's codebase, if someone can at least guide me as to where could i fix this issue

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sicarul** [comment]
If it helps to decipher this problem, i found another case:
<img width="1902" alt="image" src="https://github.com/apache/airflow/assets/4952116/895c1425-5b66-4ecc-9c08-bd7ab563840e">

And in this one, i was able to find old tasks with that name (That task does not exist any more) - However even after deleting the deprecated task instances using the UI, the same error persists in the console, my impression is it seems some "phantom records" are being picked up by the graph library?.

**Comment by eladkal** [comment]
cc @bbovenzi

**Comment by bbovenzi** [comment]
So this only happens to DAGs with Datasets? And it sounds like it happens when we retrieve datasets but either the dataset or task no longer exists so we're pointing to a nonexistent node. Sounds straightforward enough to add a check for that.

**Comment by sicarul** [comment]
@bbovenzi Yes, that seems to be the case. My guess is this didn't happen before because Airflow was not drawing datasets in the graph
