### ISSUE TITLE
Rendering map_index_template even if the task fails

### ISSUE THREAD

**Issue by tomrutter** [apache/airflow#39065]
### Description

The map_index_template field on a task is used to render a custom name for each individual sub task in a mapped task. It is generated by rendering the task context on the jinja template provided. It is possible to add to this context during the task run and therefore control the mapped index based on the results of the task. As a result, the rendering happens after a task run completes and this has the side effect that it will only render the mapped task for tasks that succeed.

This isn't always the case though, and it would be useful to see the custom map index both during task runs, and for tasks that have failed. I propose that we render the map index twice - once before and once after the task runs. This would mean that the mapped index appears during the task run, and also persists for tasks that have failed.

### Use case/motivation

It would be useful to be able to see the custom map index even for tasks that fail, when the context information to do so is available. This helps with tracking down which tasks have failed, as the mapped task index can be used to provide human readable information to distinguish the mapped tasks from one another.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
@tomrutter perhaps this [PR](https://github.com/apache/airflow/pull/38902) fixes it already. Could you check once it's the same issue you're reporting?

**Comment by pankajkoti** [comment]
cc: @RNHTTR @TJaniF @uranusjr for your opinion on this one ☝🏽

**Comment by raphaelauv** [comment]
related : https://github.com/apache/airflow/issues/39092

**Comment by RNHTTR** [comment]
Yes, #38902 will resolve the issue where named mapped instances don't render if the instance fails. 

I couldn't figure out how to get the mapped instances to render _during_ task execution, but I think it's worthy for there to be an issue open for that. @tomrutter would you be open to closing this one and opening a separate Issue for rendering named mapped instances during task execution?

**Comment by tomrutter** [comment]
Sure. Will do.
