### ISSUE TITLE
Tree View is not getting updated to show the status

### ISSUE THREAD

**Issue by puneethpotu** [apache/airflow#391]
I have two Dags first dag is dependent on the Time sensor and the second dag is set to run after the task from the first dag is complete. I see that the tree view is not updating with status after the job is success.

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 9, 12),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'schedule_interval': timedelta(1),
    'retry_interval': timedelta(minutes=15)

task_start_job = TimeSensor(
    target_time=time(12,10),
    task_id='Initiating_Job',
    dag=dag)
```

Please find above the default arguments and the time sensor task that i am using.

**Comment by puneethpotu** [comment]
Initially my start_date was set to `start_date: datetime.today()` after changing it to as shown above code in my previous comment, the tree got updated to show the status of the tasks. I did the same changes to the dependent job as well and it started to work. Leaving the issue open until someone comments to make sure, if the issue was caused due to `start_date: datetime.today()`

**Comment by mistercrunch** [comment]
`datetime.today()` is a `datetime.date` type, not a `datetime.datetime`, this may create some problems. The docs specify clearly that `start_date` receives a `datetime.datetime`, but I can see how using a date could be a common pitfall. I just added a warning message on start_date's type, it will make the next version
