### ISSUE TITLE
Compatiblity wiht xmlsec 1.3.14 for Amazon Provider

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#39103]
### Body

The xmlsec used by Amazon provider for authentication has compatiblity
issue with libxmlsec 1.2.* that is used by default in debian bookworm.

We should investigate if/howe we can upgrade our images to support it,
in the meantime we limitt python bindings to < 1.3.13.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @ferruzzi @vincbeck might be worth looking at

**Comment by ferruzzi** [comment]
@potiuk - I'm sorry, I got distracted by a shiny new thing and completely forgot about this after you tagged me

@jedcunningham - Thanks for fixing it.

**Comment by potiuk** [comment]
Fixed by #39103

**Comment by jedcunningham** [comment]
Just for posterity: I did nothing to fix it (I just removed the pin), but 1.3.14 no longer exhibits a problem.

**Comment by vitaliyf** [comment]
@jedcunningham that's because xmlsec project [uploaded binary wheels](https://pypi.org/project/xmlsec/1.3.14/#files) for 1.3.14 (see recent comments in https://github.com/xmlsec/python-xmlsec/issues/316) so perhaps the pin inside airflow should be removed now, since they are expected to do that going forward.

We are actually running into problems with 1.3.13 that .14 is meant to address, so airflow's pin is preventing that upgrade.

**Comment by potiuk** [comment]
> @jedcunningham that's because xmlsec project [uploaded binary wheels](https://pypi.org/project/xmlsec/1.3.14/#files) for 1.3.14 (see recent comments in [xmlsec/python-xmlsec#316](https://github.com/xmlsec/python-xmlsec/issues/316)) so perhaps the pin inside airflow should be removed now, since they are expected to do that going forward.
> 
> We are actually running into problems with 1.3.13 that .14 is meant to address, so airflow's pin is preventing that upgrade.

Yes. This is what we did.

**Comment by vitaliyf** [comment]
@potiuk ah yes, I think I got confused while looking through code in your fork instead of apache/airflow 🤦 

For posterity: pin removed in https://github.com/apache/airflow/pull/39534 and should be released in apache-airflow-providers-amazon version > 8.21.0
