### ISSUE TITLE
allow setting a default view for the run

### ISSUE THREAD

**Issue by kiaradlf** [apache/airflow#39125]
### Description

`dag_default_view` lets one specify a preferred default view for the dag from among its tab.
runs similarly have a number of tabs, and i find myself continuously switching to the log tab as soon as i can.

### Use case/motivation

i feel it would thus be nice if we similarly had a setting to allow specifying the default tab for runs.

### Related issues

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
We could create a task_instance_default_view or just make logs the default for all users. I've wanted to refactor how the tabs work anyway since it changes a lot depending on if a dag/dag run/task instance/mapped instance is selected.

**Comment by geraj1010** [comment]
I'm interested in taking this on, if it's still an active issue.

**Comment by bbovenzi** [comment]
We're changing the designs quite a bit for Airflow 3.0. [See them here](https://github.com/apache/airflow/issues/42371). We definitely want to make it easier to get to logs ASAP. Hopefully, we don't need another config here. We may even deprecate `default_dag_view` in all honesty
