### ISSUE TITLE
Add end date of task instance to tooltip

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#39150]
### Description

Currently, only start date and duration of a task instance are displayed in the tooltip. It will be useful to display the end date too since some of our users are wanted to know the end date and it takes some work to add start date and duration to come up at the date. We have a patch for this but wanted to discuss it before submission. Screenshot of the change as below : 

![image](https://github.com/apache/airflow/assets/3972343/37b92b1f-c67d-4da2-8cdc-4ce426315d1b)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
@bbovenzi, would be happy to know your thoughts on this. Thanks.

**Comment by bbovenzi** [comment]
Sure! I think that makes sense.
