### ISSUE TITLE
Issue with CLI/Airflow API

### ISSUE THREAD

**Issue by fakirAyoub** [apache/airflow#39197]
### What do you see as an issue?

In this [link](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html), the CLI for adding roles is either incomplete or outdated (for instance, it is not shown that resources should be prefixed with their types => `DAG:...`), etc...

There is no documentation on how to query the API in a deployed Airflow environment (Kubernetes or else)

### Solving the problem

Have a clearer and working examples for the Airflow CLI, and the API to interact with the Airflow components.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Indeed. Link should be added to https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/cli-ref.html where it has been moved - similarly to executors CLIs - can you please add a PR with the link ?

**Comment by potiuk** [comment]
(should be easy - by looking as other links are added after clicking "Suggest a change on this page".

**Comment by potiuk** [comment]
Added it quickly to make sure it will make it for 2.9.1
