### ISSUE TITLE
Airflow auto-refresh on UI

### ISSUE THREAD

**Issue by Elik09** [apache/airflow#39209]
### Description

The auto refresh feature on the airflow DAGS page in the  web UI does not work when a new, dynamically created, DAG has been added to the system.

### Use case/motivation

When there is a new DAG added to the system, the auto refresh slider that handles task status updates should also refresh the list of currently active/present DAGS.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
I believe this is a kind of known limitation or you could also say optimiztation. The auto refresh only refreshes the counters on status of DAGs which are active. Not only new DAGs are not refreshed, also other details of existing DAGs if DAG code is changed (e.g. schedule) stays static.
You could classify this as a shortcoming but the initial load is also more expensive on the DB to select the data together. In regards of performance I am not sure if a constant full refresh is a good idea.

Would you consider to contribute an extension to enable a full refresh as user option?
