### ISSUE TITLE
Edit connection fields dissapearing from web interface

### ISSUE THREAD

**Issue by suhren** [apache/airflow#39251]
### Apache Airflow version

2.9.0

### What happened?

We have recently upgraded from Airflow 2.4.0 to 2.9.0. The migration itself went fine, but we have noticed that the "Edit Connection" page in the Airflow web interface is not working properly when trying to edit existing connections. Specifically, when we try to edit some of our Spark connections, all available configuration fields quickly (less than a second) flash up on the page, but then dissapear. We are then left with only a small subset of fields we can edit. I have tried using incognito mode, as well as different browsers (Firefox, Chrome, Edge), but they all behave the same. I am attaching two images to show what I mean. The first image shows what we see for only a fraciton of a second when the page loads, then it quickly reverts to the fields seen in the second image.

![Picture1](https://github.com/apache/airflow/assets/29000670/59d2e243-a2a7-4b9f-bc32-e43a631ecc9f)
![Picture2](https://github.com/apache/airflow/assets/29000670/f47ad446-86c6-46e5-b6c2-e18393b0daba)

### How to reproduce

We set up a fresh installation of Airflow 2.9.0 and added some Spark configurations like the ones seen in the images attached. When starting the web server and navigating to the "edit connections" page, we get this behavior.

### Operating System

Red Hat Enterprise Linux Server 7.6 (Maipo)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by suhren** [comment]
Hi @RNHTTR. I am using apache-airflow-providers-apache-spark 4.7.2

**Comment by eladkal** [comment]
I think this was fixed in https://github.com/apache/airflow/pull/39229 ?
