### ISSUE TITLE
[Bug]: Papermill Provider installed via pip seems empty

### ISSUE THREAD

**Issue by deramos** [apache/airflow#39281]
### Apache Airflow Provider(s)

papermill

### Versions of Apache Airflow Providers

``` pip install apache-airflow-providers-papermill ``` installs successfully, but the installed package seems empty 

<img width="384" alt="image" src="https://github.com/apache/airflow/assets/3740968/04b81284-73d6-4cd2-be38-8384361fa92d">

Also, library import on pycharm doesn't have papermill under providers

<img width="738" alt="image" src="https://github.com/apache/airflow/assets/3740968/eab49e40-b043-4c93-a0d7-3fef21388ed3">
 

### Apache Airflow version

2.8.4

### Operating System

macOS Sonoma 14.0 (23A344)

### Deployment

Virtualenv installation

### Deployment details

Python 3.9 virtualenv
Pip 24.0

### How to reproduce

Run 
```pip install apache-airflow ``` on macOS 14.0 (23A344)

Then run 
``` pip install  apache-airflow-providers-papermill```

You'd probably get an empty package

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Airflow Community Providers are [namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) and installed under the `airflow/providers` namespace

**Comment by deramos** [comment]
@Taragolis the message I posted earlier shows that `papermill‘ doesn't exist in the airflow.providers namespace even after pip install. I think you may have missed it.
