### ISSUE TITLE
In provider docs, the environment variables in Configuration tab are shown incorrectly

### ISSUE THREAD

**Issue by kahlstrm** [apache/airflow#39311]
### What do you see as an issue?

https://airflow.apache.org/docs/apache-airflow-providers-jdbc/stable/configurations-ref.html
Here it suggests to use `AIRFLOW__PROVIDERS.JDBC__ALLOW_DRIVER_CLASS_IN_EXTRA` which is incorrect.

Instead it should be `AIRFLOW__PROVIDERS_JDBC__ALLOW_DRIVER_CLASS_IN_EXTRA` as per https://airflow.apache.org/docs/apache-airflow-providers-jdbc/stable/connections/jdbc.html and https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html

### Solving the problem

In `docs/exts/includes/sections-and-options.rst`, also pipe the value through `replace (".", "_")` when rendering the template.

This needs to be checked if there are any conflicts, i.e. if some packages behave differently.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kahlstrm** [comment]
Problem seems to have to do with providers using the `provider.yaml`'s `config` field, and having the key inside that be of format `xxx.yyy`
Only `jdbc` and [`common-io`](https://airflow.apache.org/docs/apache-airflow-providers-common-io/stable/configurations-ref.html) seem to be affected by this.

**Comment by kahlstrm** [comment]
At least according to https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html:

> Note that when the section name has a dot in it, you must replace it with an underscore when setting the env var. For example consider the pretend section providers.some_provider:

The replacement should be expected behavior.

**Comment by RNHTTR** [comment]
The dots are pretty unconventional and potentially confusing, so even though it's documented, it might be worthwhile to replace the dots when creating the config if it's not too difficult. I can't quite find out how the configuration references get built though...

**Comment by RNHTTR** [comment]
The dots are pretty unconventional and potentially confusing, so even though it's documented, it might be worthwhile to replace the dots when creating the config if it's not too difficult. I can't quite find out how the configuration references get built though...

@kahlstrm would you like to be assigned to this issue?
