### ISSUE TITLE
Release helm chart for Airflow 2.9.0

### ISSUE THREAD

**Issue by mdsakalu** [apache/airflow#39318]
### Official Helm Chart version

main (development)

### Apache Airflow version

2.9.0

### Kubernetes Version

1.28.7

### How to reproduce

Please make a helm chart release that has Airflow 2.9.0 as the default version. Looks like the change was already made in #38839, just needs a release created

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
The chart is complatible with Airflow 2.9.0 you can simply change the default value
