### ISSUE TITLE
Wrong schedule for hourly dag

### ISSUE THREAD

**Issue by GabrielGomiz** [apache/airflow#39435]
### Apache Airflow version

2.9.0

### What happened?

I have several dags that are configured to run hourly and are scheduled wrong (every 4 hours for example). Please see detail in the attached image. This dags were working perfectly on Airflow version 2.7.3. It started failing after the upgrade to 2.8.x. I've tested with 2.9.0 and finally today with 2.9.1 and I confirm the problem is still there.

![airflow](https://github.com/apache/airflow/assets/94997540/7a593e04-7ecb-4c9f-be99-8734798cadd8)

I'm running airflow on docker with official docker compose as base schema.

### What you think should happen instead?

Dag should be scheduled every hour

### How to reproduce

Create a dag with schedule="0 * * * *"

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.20.0
apache-airflow-providers-celery==3.6.2
apache-airflow-providers-cncf-kubernetes==8.1.1
apache-airflow-providers-common-io==1.3.1
apache-airflow-providers-common-sql==1.12.0
apache-airflow-providers-docker==3.10.0
apache-airflow-providers-elasticsearch==5.3.4
apache-airflow-providers-fab==1.0.4
apache-airflow-providers-ftp==3.8.0
apache-airflow-providers-google==10.17.0
apache-airflow-providers-grpc==3.4.1
apache-airflow-providers-hashicorp==3.6.4
apache-airflow-providers-http==4.10.1
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-microsoft-azure==10.0.0
apache-airflow-providers-mysql==5.5.4
apache-airflow-providers-odbc==4.5.0
apache-airflow-providers-openlineage==1.7.0
apache-airflow-providers-postgres==5.10.2
apache-airflow-providers-redis==3.6.1
apache-airflow-providers-sendgrid==3.4.0
apache-airflow-providers-sftp==4.9.1
apache-airflow-providers-slack==8.6.2
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-snowflake==5.4.0
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-ssh==3.10.1

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Can you please post the dag or a minimal example to reproduce this?

**Comment by GabrielGomiz** [comment]
```
#!/usr/bin/python3

from airflow import DAG
from datetime import datetime

from airflow.operators.bash import BashOperator
from airflow.hooks.base import BaseHook

default_args = {
    'owner': 'ggomiz',
    'depends_on_past': False,
    'start_date': datetime(2024,5,6),
    'email': ['sysadmin@cooperativaobrera.coop'],
    'email_on_failure': True,
    'email_on_retry': False
}

# hourly redis dag
dag_hourly = DAG(dag_id='redis_test', default_args=default_args, schedule='0 * * * *', catchup=False, tags=["dbservers", "backups", "redis"])

task_args = {
    'retries': 0,
    'trigger_rule': 'all_done'
}

# hourly backup task
task_daily = BashOperator(task_id="test_redis_master",
                          bash_command="cronjob.sh -q -u root /srv/redis/scripts/redisbackup.sh master",
                          dag=dag_hourly, queue = "galadriel", default_args=task_args)
```

This minimal DAG to make an hourly backup of our redis database is getting incorrect schedule.

![schedule](https://github.com/apache/airflow/assets/94997540/a398f6ce-1adf-46cc-a840-93ce58fc751b)

**Comment by GabrielGomiz** [comment]
As additional information, I've several other DAGs with hourly schedule definition, but also are incorrectly scheduled on a 4 hour interval, but they are not executing. Last run time is before the upgrade.

![next](https://github.com/apache/airflow/assets/94997540/590631db-a3ad-4a2e-88cf-93b0fd6b42e4)

![last](https://github.com/apache/airflow/assets/94997540/ebf5ccc5-4ad4-47d7-a4d1-ad226514b0db)

**Comment by tirkarthi** [comment]
I am unable to reproduce this locally on main branch with the given dag code. The dag is scheduled hourly for me. Since this is a common cron expression I am wondering if there is something else wrong specific to the installation.

**Comment by Taragolis** [comment]
@GabrielGomiz Could you provide also information about your timezones configurations: in OS and in Airflow Configuration?

**Comment by GabrielGomiz** [comment]
> @GabrielGomiz Could you provide also information about your timezones configurations: in OS and in Airflow Configuration?

Ok. We're in Argentina, so timezone is -3 ART as you can see in the timestamps above: "2024-05-06T12:00:00-03:00"

![tz](https://github.com/apache/airflow/assets/94997540/2168d0fb-5eca-4a17-af77-3e1af6084013)

Inside the docker containers TZ is -3 ART also:
```
[/opt/airflow] [docker] airflow > date
Mon May  6 18:52:14 -03 2024
```

**Comment by Taragolis** [comment]
I more interested in values which are setting up, not a result. Invalid configuration may lead to some errors, e.g. Airflow expected to work with IANA timezones, if OS misconfigured it also might return invalid values.

**Comment by Taragolis** [comment]
This might be similar to this one https://github.com/apache/airflow/discussions/37869#discussion-6312536 or it could be something new and different, without understand what is your setup it is hard to guess what is going wrong here, because I could also confirm the fact, that with default configurations it is works without any issues.

**Comment by GabrielGomiz** [comment]
Ok, I'll look into timezone configuration and report back asap. Thanks @Taragolis

**Comment by GabrielGomiz** [comment]
@Taragolis, setting TZ env var to "America/Buenos_Aires", as described in #37869 worked perfectly.

I've had already in docker compose file set the following env vars:
`AIRFLOW__CORE__DEFAULT_TIMEZONE: 'America/Buenos_Aires'`
`AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'America/Buenos_Aires'`
but didn't know that also must set TZ env var.

Weird thing is that on airflow version 2.7.3 worked ok without setting TZ env var.

Thanks for your help!
