### ISSUE TITLE
Task groups are not being represented in bold letters anymore

### ISSUE THREAD

**Issue by FelipeRamos-neuro** [apache/airflow#39439]
### Apache Airflow version

2.9.1

### What happened?

After updating from version 2.9.0 to 2.9.1, task groups are not appearing in bold letters anymore.

Before:
![Captura de tela de 2024-05-06 11-59-57](https://github.com/apache/airflow/assets/150050590/e2ce4ed8-25eb-4ed4-8dcb-cff058c0590f)

After:
![Captura de tela de 2024-05-06 10-35-45](https://github.com/apache/airflow/assets/150050590/c34ccaa9-2ae2-4443-bb99-c26afc39bed7)

### What you think should happen instead?

Since no change in UI behavior was communicated in the release notes, it should perform in a similar manner.

### How to reproduce

Create two virtual environments with Python 3.10, one with Apache Airflow 2.9.0 and the other with Apache Airflow 2.9.1. Then run one after the other on standalone mode and check the example dags for task group and task group decorator.

### Operating System

Ubuntu 22.04.4 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.21.0
apache-airflow-providers-celery==3.7.0
apache-airflow-providers-cncf-kubernetes==8.2.0
apache-airflow-providers-common-io==1.3.1
apache-airflow-providers-common-sql==1.13.0
apache-airflow-providers-fab==1.1.0
apache-airflow-providers-ftp==3.9.0
apache-airflow-providers-http==4.11.0
apache-airflow-providers-imap==3.6.0
apache-airflow-providers-mysql==5.6.0
apache-airflow-providers-postgres==5.11.0
apache-airflow-providers-redis==3.7.0
apache-airflow-providers-smtp==1.7.0
apache-airflow-providers-sqlite==3.8.0
papermill==2.6.0
scrapbook==0.5.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
cc: @bbovenzi I guess it is intended Grid View behaviour after https://github.com/apache/airflow/pull/38940

**Comment by bbovenzi** [comment]
Yes, I removed the bold text. We were using a lot of different font variations around the grid+graph view. Groups in the grid were bold but in the graph were not. Now it's consistent in the UI and in the code. There are still carets to show that it is a group.

Gonna close for now
