### ISSUE TITLE
webserver: Additional property base_url is not allowed

### ISSUE THREAD

**Issue by PaleNeutron** [apache/airflow#39455]
### Official Helm Chart version

1.13.1 (latest released)

### Apache Airflow version

2.8.3

### Kubernetes Version

v1.29.4

### Helm Chart configuration

webserver:
  enabled: true
  base_url: "http://foo.com/airflow"

### What happened

Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- webserver: Additional property base_url is not allowed

### What you think should happen instead

success

### How to reproduce

helm template --name-template=airflow -f airflow-values.yaml  apache-airflow/airflow

### Anything else

- Chart: Allow ``webserver.base_url`` to be templated (#16126) 

I think it should be fixed  but not.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PaleNeutron** [comment]
sorry, it should be

```
config:
  webserver:
    enabled: true
    base_url: "http://foo.com/airflow"
```

**Comment by elehcim** [comment]
I got confused too. Why not putting the `base_url` directly into the `webserver` section (not `config.webserver`)?
