### ISSUE TITLE
Best practice: Mock connections AttributeError: type object 'Connection' has no attribute 'get'

### ISSUE THREAD

**Issue by iamtodor** [apache/airflow#39475]
### What do you see as an issue?

Per paragraph https://airflow.apache.org/docs/apache-airflow/2.8.2/best-practices.html#mocking-variables-and-connections
The given example

```
conn = Connection(
    conn_type="gcpssh",
    login="cat",
    host="conn-host",
)
conn_uri = conn.get_uri()
with mock.patch.dict("os.environ", AIRFLOW_CONN_MY_CONN=conn_uri):
    assert "cat" == Connection.get("my_conn").login
```

raises an error:

```
def test_foo():
        conn = Connection(
            conn_type="gcpssh",
            login="cat",
            host="conn-host",
        )
        conn_uri = conn.get_uri()
        with mock.patch.dict("os.environ", AIRFLOW_CONN_MY_CONN=conn_uri):
>           assert "cat" == Connection.get("my_conn").login
E           AttributeError: type object 'Connection' has no attribute 'get'

path/to/test/file.py:12: AttributeError
```

### Solving the problem

Update the doc

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamtodor** [comment]
I assume this one https://airflow.apache.org/docs/apache-airflow/2.1.2/_api/airflow/hooks/base/index.html#airflow.hooks.base.BaseHook.get_connection should be used

**Comment by rawwar** [comment]
@iamtodor , I think, you can use `get_connection_from_secrets` method of `Connection` : https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/connection/index.html#airflow.models.connection.Connection.get_connection_from_secrets

**Comment by iamtodor** [comment]
@rawwar yup, this approach could also be used. I think yours is better, is that right?

**Comment by rawwar** [comment]
> @rawwar yup, this approach could also be used. I think yours is better, is that right?

Yeah, I think `get_connection_from_secrets ` is correct. But, You can raise a PR with `get_connection_from_secrets` and request a review.
