### ISSUE TITLE
Error when _upload_file_temp in DataprocSubmitPySparkJobOperator

### ISSUE THREAD

**Issue by RubenBBlazquez** [apache/airflow#39478]
### Apache Airflow version

2.9.1

### What happened?

in the method **_upload_file_temp** from **DataprocSubmitPySparkJobOperator** it calls the function **_generate_temp_filename** which do this return: `f"{time:%Y%m%d%H%M%S}_{str(uuid.uuid4())[:8]}_{ntpath.basename(filename)}"` and the first format is bad, it gives the following error: 
`TypeError: unsupported format string passed to module.__format__`

### What you think should happen instead?

it should be like this:
 `
        date = time.strftime("%Y%m%d%H%M%S")
        return f"{date}_{str(uuid.uuid4())[:8]}_{ntpath.basename(filename)}"
`

to get the date string 20240508114811

### How to reproduce

you only have to create an instance of **DataprocSubmitPySparkJobOperator** and call the method _upload_file_temp to reproduce the error

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

airflow-providers-google
from 10.7.0 to 10.17.0, in all this versions fail

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
[`DataprocSubmitPySparkJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.DataprocSubmitPySparkJobOperator) - deprecated long time ago (in Airflow 1.10.x  https://github.com/apache/airflow/pull/6371) in favor of [`DataprocSubmitJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.DataprocSubmitJobOperator)

**Comment by RubenBBlazquez** [comment]
> [`DataprocSubmitPySparkJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.DataprocSubmitPySparkJobOperator) - deprecated long time ago (in Airflow 1.10.x #6371) in favor of [`DataprocSubmitJobOperator`](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/dataproc/index.html#airflow.providers.google.cloud.operators.dataproc.DataprocSubmitJobOperator)
But even if it is deprecated, why in the version 10.7.0 has been modified and now dont work, if is deprecated,  should not be modified no?

**Comment by Taragolis** [comment]
> But even if it is deprecated, why in the version 10.7.0 has been modified and now dont work, if is deprecated, it should not be modified no?

That is a good question, in general it shouldn't unless some formatter/linter changes or something which already covered by the tests. But this one was made manually: https://github.com/apache/airflow/pull/33455
