### ISSUE TITLE
SageMakerTransformOperator does not deduplicate model name

### ISSUE THREAD

**Issue by mxuan0** [apache/airflow#39502]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

8.7.1

### Apache Airflow version

2.7.2

### Operating System

amazon linux AMI

### Deployment

Amazon (AWS) MWAA

### What happened

The SageMakerTransformOperator deduplicates job name before creating the job, but does not deduplicate the model name before creating the model. Upon retry, the operator would fail due to model already exist error.

### What you think should happen instead

The operator should apply the same behavior (fail or add timestamp) to both the job name and the model name.

### How to reproduce

create a DAG containing a SageMakerTransformOperator step. In the operator config, fix both ModelName and TransformJobName. In airflow UI, run the task until completion in airflow once, and the run the same task for the second time by "clear task".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mateuslatrova** [comment]
Hi! I would like to work on this issue after triage!
