### ISSUE TITLE
Task Instance Note accordion doesn't collapse

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#39529]
### Apache Airflow version

2.9.0

### What happened?

Pressing the chevron to collapse task instance notes has no effect

### What you think should happen instead?

Task instance notes should be collapsed

### How to reproduce

Run a task. Add a note. Click the collapse button.

### Operating System

n/a

### Deployment

Astronomer

### Anything else?

![image](https://github.com/apache/airflow/assets/25823361/4d148dab-99cc-401e-93e3-07d20734834f)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Is this consistently reproducible? I reproduced it once and then on page refresh it works fine. Not able to reproduce it again in adding new note in another task instance note. Dag run note also shares same code and seems to be working fine.
