### ISSUE TITLE
Airflow 与 任务 失联，任务状态没办法更新

### ISSUE THREAD

**Issue by johnnylei** [apache/airflow#39537]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

Airflow 运行 KubernetesPodOperator 类型任务的，ApiServer 异常了3m, 导致Airflow 和 任务失联，后续状态无法更新

### What you think should happen instead?

-

### How to reproduce

-

### Operating System

dockerd

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Airflow Community can only accept issues/bug reports which written in English.

Also make sure that this is a bug and not troubleshooting, if it is troubleshooting please consider to use [Discussions](https://github.com/apache/airflow/discussions) instead.

In addition you also might check [Apache Airflow Community Slack Workspace](https://s.apache.org/airflow-slack)
