### ISSUE TITLE
The Rendered Template button  has disappeared from the Task Detail.

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#39549]
### Apache Airflow version

2.9.1

### What happened?

The Rendered Template button  has disappeared from the Task Detail.
It has been there before 2.9.1 was released. Maybe wrong implementation of the new Grid button?

### What you think should happen instead?

The Rendered Template button should be avalilable in the Task Detail options (see the picture from 2.9.0.).
![image](https://github.com/apache/airflow/assets/162625270/590f22c3-e736-4c05-a365-c03e5e6b689a)

### How to reproduce

Just click on the task instance in the grid view to show task detail page.

### Operating System

Kubernetes on Unix platform

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
For anyone on 2.9.1 looking for the Rendered Template, you can still find it after clicking on "More Details"

**Comment by Pad71** [comment]
> For anyone on 2.9.1 looking for the Rendered Template, you can still find it after clicking on "More Details"

Yeah, I know, but it's a useful tool and I don't understand what the reason was for hiding it. I didn't find any request to do that.

**Comment by romsharon98** [comment]
Closing the issue as deprecated:

https://github.com/apache/airflow/issues/39527
