### ISSUE TITLE
UI bug with `DAG Docs` display in `DAG Run` Triggering page

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#39589]
### Apache Airflow version

2.9.1

### What happened?

When triggering a `DAG Run` of a `DAG` that includes `Parameters`, in the `DAG Run` "triggering page" the `DAG Docs` are expanded by default and clicking on the `DAG Docs` quickly closes and re-expands the `DAG  Docs`. See gif:

![2024-05-13 16-36-29](https://github.com/apache/airflow/assets/4175430/fda7e28b-35d9-41d2-8ed0-afbff7adcf59)

### What you think should happen instead?

When triggering a `DAG Run` of a `DAG` that includes `Parameters`, in the `DAG Run` "triggering page" the `DAG Docs` should be closed by default and only then should clicking on the `DAG Docs` expands the docs.

### How to reproduce

1. Trigger a `DAG Run` of a `DAG` that includes `Parameters`.
2. Confirm that the `DAG Docs` are already expanded
3. Click on the `DAG Docs` a single time to confirm that the `DAG Docs` will quickly close and re-expand.

### Operating System

Windows 11 WSL2

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Actually - this was made by me "by intent". I believe the community never "voted" on it but it was assuming:
- DAG docs give guidance for the user how to use the DAG. It might describe guidance when and how to trigger and a general overview about what it does.
- If a manual trigger is being made, the docs are mostly helpful  for first time users.

Before changing the behavior back and hiding the docs by default: Can you give a reason why you think this is a problem?
If so, can we maybe make a vote about who things displaying DAG docs is benefitial and who does not like to see it?
It might be also something that might be a configuration option if there is not a clear result.

I would see it also the way: If docs are bothering you, have you considered not adding them to the DAG? There is no requirement to add documentation. But if there is documentation and it is hidden by default, then users might miss it per default.

**Comment by jscheffl** [comment]
> @jscheffl In the scenario where it is intended to show the docs by default, there is still a bug. As seen on the GIF when I try to minimize the docs (the first time after opening the page) it quickly collapses and re-expands, forcing you to click it twice in order to minimize it.
> 

Okay, agree in this point - to fold the DAG docs you should only need to click once, seems the handler on the folding has a wrong state.
