### ISSUE TITLE
Making `mssql` provider to support  only `mssql+pymssql` dialect

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#39586]
### Description

Currently, we allow users to pass dialect via `sqlalchemy_scheme` extra field of the `mssql` connections.

https://github.com/apache/airflow/blob/3873b098130ff4b8c1b8a37ac596be7b560c62ca/airflow/providers/microsoft/mssql/hooks/mssql.py#L80

 I am proposing to remove this field as it is not possible to support multiple dialects without installing the relevant dialect driver. Also, the [documentation page](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/connections/mssql.html) does not even mention about `sqlalchemy_scheme` or the possibility of using other dialects.

### Use case/motivation

Supporting multiple dialects requires the installation of multiple drivers. Since we only install `pymssql`, this allows the usage of the `mssql+pymssql` dialect alone and not others.

I am also interested in updating the documentation to reflect this.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
@Taragolis , requesting your comments on this. 

I was working on updating `mssql` provider to use `sqlalchemy_url` property in `get_uri` and got the idea for this issue.

**Comment by eladkal** [comment]
It looks like a small code change? If so it's better to simply raise PR we can have the discussion on the PR itself

**Comment by shahar1** [comment]
@rawwar Would you still like to work on this issue?

**Comment by dabla** [comment]
An overview of all enhancements and fixes I did regarding hooks:

[40665](https://github.com/apache/airflow/pull/40665)
[40669](https://github.com/apache/airflow/pull/40669)
[40751](https://github.com/apache/airflow/pull/40751)
[40836](https://github.com/apache/airflow/pull/40836)

**Comment by shahar1** [comment]
Thanks @dabla , I'll assign this issue on you then.

**Comment by dabla** [comment]
> ### Description
> Currently, we allow users to pass dialect via `sqlalchemy_scheme` extra field of the `mssql` connections.
> 
> https://github.com/apache/airflow/blob/3873b098130ff4b8c1b8a37ac596be7b560c62ca/airflow/providers/microsoft/mssql/hooks/mssql.py#L80
> 
> I am proposing to remove this field as it is not possible to support multiple dialects without installing the relevant dialect driver. Also, the [documentation page](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/connections/mssql.html) does not even mention about `sqlalchemy_scheme` or the possibility of using other dialects.
> 
> ### Use case/motivation
> Supporting multiple dialects requires the installation of multiple drivers. Since we only install `pymssql`, this allows the usage of the `mssql+pymssql` dialect alone and not others.
> 
> I am also interested in updating the documentation to reflect this.
> 
> ### Related issues
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

I would not remove that property, we for example are actually using is as we have installed multiple drivers (pymssql/odbc/jdbc/...) to access multiple databases.  Indeed the 'sqlalchemy_scheme' schould be documeneted, especially in the case of the JdbcHook are there it is required to define it if you want to use the sqlalchemy engine.

**Comment by dabla** [comment]
As [PR40669](https://github.com/apache/airflow/pull/40669) has been closed I think this one can also be closed?
