### ISSUE TITLE
Dynamic task mapping - partial args are not check and only fail at trigger

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#39639]
### Apache Airflow version

2.9.1

### What happened?

```python
    PythonOperator(
        task_id="test_2",
        python_callable=a,
        pool="pool_1",
        pool_slots="a",
    )
```

airflow fail with 

![Screenshot from 2024-05-15 14-34-18](https://github.com/apache/airflow/assets/10202690/1c3f581b-1d8e-433f-8024-ae9bebdb9566)

but 

with

```python
    PythonOperator.partial(
        task_id="test",
        python_callable=a,
        pool="pool_1",
        pool_slots="a",
    ).expand(show_return_value_in_logs=[True])
```

airflow do not fail to parse the file and fail at trigger of the pipeline

### What you think should happen instead?

airflow should detect incorrect args of partial

### How to reproduce

```python
from airflow.operators.python import PythonOperator
from pendulum import today
from airflow import DAG

with DAG(
        dag_id="test_partial",
        schedule_interval=None,
        start_date=today("UTC").add(days=-1)):
    def a():
        return

    PythonOperator.partial(
        task_id="test",
        python_callable=a,
        pool="pool_1",
        pool_slots="a",
    ).expand(show_return_value_in_logs=[True])
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by karenbraganz** [comment]
I would like to be assigned this issue.

**Comment by RNHTTR** [comment]
Done!
