### ISSUE TITLE
Params Fail to Evaluate In Dag Body

### ISSUE THREAD

**Issue by oliver-helix** [apache/airflow#39651]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.2

### What happened?

When providing airflow params, the parameter is not available in the body of the airflow dag.

### What you think should happen instead?

The value should be available in the airflow dag

### How to reproduce

```python
from airflow import DAG
from airflow.models.param import Param
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator

with DAG("generate_password_dag", params={"test": Param("defeault", type="string")}) as dag:
    sql_operator = SQLExecuteQueryOperator(
        task_id="sql_operator",
        sql="sql/{{ params.test }}.sql",
        database="default",
    )
```

### Operating System

NA

### Versions of Apache Airflow Providers

NA

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

NA

### Anything else?

NA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by oliver-helix** [comment]
Thanks for your response @Taragolis! For my use-case, I'd like to determine the SQL file with a param provided in the UI

**Comment by josh-fell** [comment]
You can use [Jinja's `include` tag](https://jinja.palletsprojects.com/en/3.1.x/templates/#include) to render a file's contents.

For example, using this SQL file;
```sql
# dags/sql/default.sql
SELECT 'from a templated file';
```
and this task definition:
```py
from airflow.models.dag import DAG
from airflow.models.param import Param
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator

with DAG(
    "generate_password_dag",
    params={"test": Param("default", type="string")},
):
    sql_operator = SQLExecuteQueryOperator(
        task_id="sql_operator",
        sql="{% include 'sql/' ~ params.test ~ '.sql' %}",
        conn_id="postgres",
    )
```
In the above task definition, `~` is string concatenation in Jinja.

Task log:
<img width="941" alt="image" src="https://github.com/apache/airflow/assets/48934154/3ddf0c00-c10a-40fa-97f0-b2993bc26bc9">

**Comment by oliver-helix** [comment]
Thank you @josh-fell! This indeed works. Curious why `sql="{% include 'sql/' ~ params.test ~ '.sql' %}"` works when `sql="sql/{{ params.test }}.sql"` does not?

**Comment by Taragolis** [comment]
> works when sql="sql/{{ params.test }}.sql" does not?

It doesn't work by design, see: https://github.com/apache/airflow/issues/39651#issuecomment-2113385429

> Curious why sql="{% include 'sql/' ~ params.test ~ '.sql' %}" works 

It is just a Jinja statement which rendered
