### ISSUE TITLE
Output tasks doc in the UI

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#39676]
### Description

I would like to see the `doc_md` attribute of any Task in the Airflow UI. As of now it is visible only after I click "More details" which is not practical when I need to look for documentation of multiple tasks.

### Use case/motivation

We would like to start to utilize the documentation attribute for task as not everybody is familiar with what every task does and using doc_md we can point to more detailed docs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
cc @bbovenzi if not mistaken this is something we discussed previously that task docs should have more visability like the dag docs

**Comment by jscheffl** [comment]
I would believe if @bbovenzi , me or anybody else contributes into getting away the last legacy web pages into 2.10 then this would be going into the standard details view in GRID view.

**Comment by tirkarthi** [comment]
I have created https://github.com/apache/airflow/pull/39899 with screenshots for reference. It follows the approach similar to task instance notes and task dependency check table.
