### ISSUE TITLE
GenericTransfer - Warning: "Placeholder defined in Connection..."

### ISSUE THREAD

**Issue by romanzdk** [apache/airflow#39678]
### Apache Airflow version

2.9.1

### What happened?

We use GenericTransfer task to copy data from one DB to another. Task is successful but we get a warning in logs:
`[2024-05-17, 10:08:43 UTC] {sql.py:187} WARNING - Placeholder defined in Connection 'None' is not listed in 'DEFAULT_SQL_PLACEHOLDERS' and got ignored. Falling back to the default placeholder '%s'.`

I checked the Connections in the Admin and everything looks alright.

<img width="395" alt="Screenshot 2024-05-17 at 12 22 33" src="https://github.com/apache/airflow/assets/31843161/ba25629d-c7d1-4b0c-8dc7-9a22d88da93e">

### What you think should happen instead?

No warning log

### How to reproduce

create and run GenericTransfer task:

```python
copy_task = GenericTransfer(
	task_id = 'copy_task',
	dag = dag,
	source_conn_id = 'source-db',
	destination_conn_id = 'bi-database',
	sql = '''
		SELECT
			"date"
		FROM "TableName"
	''',
	destination_table = '"TableName"',
	preoperator = '''
		DELETE FROM "TableName"
		WHERE
			1 = 1
	'''
)
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.20.0
apache-airflow-providers-celery==3.6.2
apache-airflow-providers-cncf-kubernetes==8.1.1
apache-airflow-providers-common-io==1.3.1
apache-airflow-providers-common-sql==1.12.0
apache-airflow-providers-fab==1.0.4
apache-airflow-providers-ftp==3.8.0
apache-airflow-providers-http==4.10.1
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-postgres==5.10.2
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-sqlite==3.7.1

### Deployment

Other Docker-based deployment

### Deployment details

Airflow 2.9.1, on-premise Kubernetes cluster 1.26.5, python 3.10.12, Celery executor, Postgres 13.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
cc: @dabla https://github.com/apache/airflow/pull/38528/files#r1551219388

**Comment by dabla** [comment]
I'm on it, will write a test to reproduce but I suppose a None check is missing hence why the warning message.

**Comment by dabla** [comment]
I've created a [PR](https://github.com/apache/airflow/pull/39690) for this which fixes the issue.
