### ISSUE TITLE
data to long when using s3 to gcs

### ISSUE THREAD

**Issue by Lee2532** [apache/airflow#39708]
### Description

If a large amount of s3 data is moved using s3 to gcs, data too long for column error occurs when storing related values in the last xcom

### Use case/motivation

I think we can prevent this error by adding a logic that compresses the list to show only some of the data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
XCOM is not for data , it's for metadata ( xcom backend is just a work around , in all case Airlfow should not see your data )

Airflow is a scheduling tool not an ETL tool

Airlfow operators are most of them simple python helpers not data-transfert efficient tools
