### ISSUE TITLE
Metric for pool_scheduled

### ISSUE THREAD

**Issue by andreyolv** [apache/airflow#39757]
### Description

There are the following metrics: 
- airflow_pool_running_slots
- airflow_pool_open_slots
- airflow_pool_queued_slots

However there is no metric for scheduled slots and it would be very useful to know when there are problems or that the scheduler freezes and accumulates tasks.

### Use case/motivation

Improve monitoring of possible problems in the scheduler

### Related issues

I did not find it

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
@andreyolv , I think this will be available in the next release : https://github.com/apache/airflow/pull/38899
