### ISSUE TITLE
Document how to create a new Airflow API endpoint

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#39836]
### What do you see as an issue?

Currently, it's difficult to know how to create an Airflow API endpoint.

There are several steps, including adding the endpoint to the [openapi yaml](https://github.com/apache/airflow/blob/main/airflow/api_connexion/openapi/v1.yaml), creating the [endpoint](https://github.com/apache/airflow/tree/main/airflow/api_connexion/endpoints), and I think there's a pre-commit hook that if you don't run gets you all tangled up (I think it creates a minified js file with all of the endpoints for `www`?)

### Solving the problem

Write some docs!

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by andyjianzhou** [comment]
Hey! I'll be completing this!
