### ISSUE TITLE
Add docs. for development of integration tests

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#39838]
### What do you see as an issue?

[Current docs](https://github.com/shahar1/airflow/blob/78523fdbf1b80a7fbc7ec5e7b0b20f6934917898/contributing-docs/testing/integration_tests.rst) refer to the enablement and usage of integration tests, but there's a small gap in how to implement them. For example, creating an integration yaml file for docker-compose, allocating ports, updating breeze files, and more.

### Solving the problem

Adding some information about the development of integration tests to either `TESTING.rst` or Breeze docs.

### Anything else

I learnt that it could be helpful after creating #39831 :)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Improving contributor docs is highly appreciated.
@shahar1 assigned it to you

**Comment by potiuk** [comment]
> updating breeze files, and more.

Should be a bit simplified with https://github.com/apache/airflow/pull/39866
