### ISSUE TITLE
"Add Dag Run" /dagrun/add page issue

### ISSUE THREAD

**Issue by fliaj** [apache/airflow#39856]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.1

### What happened?

1. I created DAG runs with no notes at first. Therefore, when I want to add a DAG run with past logical date like below, I found that I cannot fill in the Dag Run Note field, which is a required field.

![Screenshot 2024-05-27 at 01 51 21](https://github.com/apache/airflow/assets/40557001/d38433e3-68aa-4f2b-9d4e-c021f87c9c00)

2. After I added random DAG Run Note to an existing DAG Runs, the `/dagrun/add` page throws error
![Screenshot 2024-05-27 at 01 51 39](https://github.com/apache/airflow/assets/40557001/49555344-80ba-4a62-b3ce-3edad685c68f)

No useful logs shown in the web server log group.

### What you think should happen instead?

1. Allow users to create DAG Runs without notes.
2. No error in the Add DAG Run page if the existing DAG Runs are with notes.

### How to reproduce

Please refer to the **What happened** section, thanks

### Operating System

MWAA

### Deployment

Amazon (AWS) MWAA

### Deployment details

I am not sure that this issue is specific to the service provider.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
As this UI is not maintained and FAB is to be deprecated - I never noticed the add button myself :-D - I propsoe to fix this problem by removing the UI. Adding a DAG run via this UI does not seem to be the proper way to interact with the system. It even allows you to add a new DAG Run with success which has never been run. Trigger UI via the "Play" button is the right option

**Comment by fliaj** [comment]
@jscheffl Thanks so much for the prompt response and action, one quick followup: 
 
What is your suggestion for my use case where I want to trigger one DAG run with past logical date? Is **CLI** the only way?

**Comment by jscheffl** [comment]
> What is your suggestion for my use case where I want to trigger one DAG run with past logical date? Is **CLI** the only way?

I'd suggest to use (1) the CLI, (2) the API or (3) the "Play" option in the web UI. Since a while the DAG run options are hidden if the DAG does not specify any parameters. If you want to force the UI to display the trigger details page - where also the logical date can be changed - you need to set the `AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS` (see https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#show-trigger-form-if-no-params).
