### ISSUE TITLE
Scheduler catchup setting is ignored

### ISSUE THREAD

**Issue by cedric-fauth** [apache/airflow#39867]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.2

### What happened?

I tried setting [`AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False`](https://airflow.apache.org/docs/apache-airflow/2.8.2/configurations-ref.html#catchup-by-default) which should prevent the scheduler from scheduling dag runs that were missed in the past. But wheh I unpause a DAG which never ran it is scheduled automatically for a run. 

### What you think should happen instead?

I thought this env var would override the existing config and not schedule a dag after unpausing it.

### How to reproduce

Create a DAG with a start_date in the past and a frequent schedule interval. When it's paused and never ran in the past and you unpause it a dag run is scheduled.

### Operating System

WSL (Ubuntu) and even on AWS ECS

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.18.0
apache-airflow-providers-celery==3.6.0
apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.0
apache-airflow-providers-docker==3.9.1
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.9.1
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-postgres==5.10.1
apache-airflow-providers-redis==3.6.0
apache-airflow-providers-sqlite==3.7.1
```

### Deployment

Virtualenv installation

### Deployment details

Also tested it using AWS Fargate with same problem. Env vars are set correctly:

```
{
"name": "AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT",
"value": "False"
},
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Does it trigger catchup for all data intervals or only the latest data intervals? If it's the latest one I guess this is expected since the first run after unpause is considered to be not part of past catchups. Related stackoverflow answer

Ref : https://stackoverflow.com/q/67160748

**Comment by cedric-fauth** [comment]
You're right only the latest run is scheduled. So there is no way to prevent this?

**Comment by jscheffl** [comment]
The "latest" schedule refers always to the "current" time period. I understand this as a common mis-understanding of schedules in Airflow and how they are named. Can you take a look here? https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html#data-interval
