### ISSUE TITLE
Duplicated shortcuts with same keys

### ISSUE THREAD

**Issue by Timelessprod** [apache/airflow#39895]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.2

### What happened?

When opening a DAG window, and running the shortcut `shift + /` to display Airflow's tasks shortcuts:
<img width="212" alt="Screenshot 2024-05-28 at 12 15 45" src="https://github.com/apache/airflow/assets/69579602/c1a36102-3d37-43bd-b6e6-f30ef17ea8c6">
the following pop up window appears:
<img width="952" alt="Screenshot 2024-05-28 at 12 12 04" src="https://github.com/apache/airflow/assets/69579602/e2f6c638-ea9d-4367-85b6-21333c48cc5c">

We can see that there are 3 pairs of shortcuts that share the same key combination `shiftKey + S/C/F` (should it be `shift` instead of `shiftKey` by the way ?). I thought it would be a matter of pressing the left or right shift key but in all cases, only the top 3 actions are being executed, the 3 following ones are not accessible.

### What you think should happen instead?

There should be distinct key combination for each shortcut action.

### How to reproduce

1. Run an Airflow instance
2. Open the web UI
3. Click on any DAG to open its page
4. Type `shift + /` to open shortcut documentation popup

### Operating System

MacOS Sonoma 14.4.1 (23E224)

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.2.0
apache-airflow-providers-common-sql==1.3.3
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.2.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-sqlite==3.3.1

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Can you clarify what you mean by "only the top 3 actions are being executed, the 3 following ones are not accessible."?

In an Airflow environment based on the main branch, I just selected a task instance, hit shift + s, and it prompted me to mark the task instance as success, for example:

> shiftKey + C | Clears the selected DAG run **or task instance** with all its existing tasks

**Comment by indraneel07** [comment]
The top 3 work at the DAG level, and the following 3 work at the task level.
To use the following 3, select a task in the UI and try using the shortcuts. You will be able to see the difference.
