### ISSUE TITLE
Allow check_fn of S3KeySensor to be used in more use cases

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#39898]
### Body

After https://github.com/apache/airflow/pull/22737 the `check_fn` is part of `S3KeySensor` and can be used as additional check layer:

https://github.com/apache/airflow/blob/2bc103698fad1b7c0bebed0d5cbdda0ec7ea83c3/airflow/providers/amazon/aws/sensors/s3.py#L139-L140

However if you will check the code you will see that it's tightly cuppled with the file size:
https://github.com/apache/airflow/blob/2bc103698fad1b7c0bebed0d5cbdda0ec7ea83c3/airflow/providers/amazon/aws/sensors/s3.py#L137

https://github.com/apache/airflow/blob/2bc103698fad1b7c0bebed0d5cbdda0ec7ea83c3/airflow/providers/amazon/aws/sensors/s3.py#L127

However this doesn't have to be only for Size/ContentLength. We should support any key possible by the return object of head_object:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/head_object.html

**The task:**
Make the Size/ContentLength parameterized (keep the default as is) but let the use decide how to construct the `files` list.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by ellisms** [comment]
I'll take this one.
