### ISSUE TITLE
Simple example of csv to Mysql

### ISSUE THREAD

**Issue by shamsulbuddy** [apache/airflow#399]
I can see that there are operators for S3 but I am looking for an example where I have to pull a CSV file from a remote location after sftp to that remote server and then unzip that sftped csv.zip file and then load that file on Mysql and on success send an Email.

Nothing to do with S3 or Hive , I just need a very basic example with above setup. Any pointers?

**Comment by mistercrunch** [comment]
You can write a python function that does all of this using hooks and then use `PythonOperator` to run it.

**Comment by r39132** [comment]
If you can encapsulate your logic in Python, you can simply use a PythonOperator. No need to master the array of different custom operators. Personally, I pretty much only use BashOperator and PythonOperator for everything. I leverage boto when I need to do anything AWS related.

For your case above, you can 
1. Use a BashOperator to execute the FTP
2. Use a BashOperator to unzip the downloaded file
3. Load the file into your MySQL library using the PythonOperator using your connector of choice
4. Send an email using the EmailOperator
