### ISSUE TITLE
mypy: Value of type "XComArg" is not indexable

### ISSUE THREAD

**Issue by hterik** [apache/airflow#39944]
### Apache Airflow version

2.9.1

### What happened?

1. Try to make a DAG following the example on https://airflow.apache.org/docs/apache-airflow/2.9.1/core-concepts/taskflow.html#taskflow
2. Run `mypy` in strict mode on this DAG (mypy version 1.10.0)
3. mypy fails with error 
    ```
    example.py:20 error: Value of type "XComArg" is not indexable  [index]
    example.py:21 error: Value of type "XComArg" is not indexable  [index]
   ```

### What you think should happen instead?

Mypy should allow usage of `XComArgs` using `multiple_outputs=True`

### How to reproduce

See above

### Operating System

Ubuntu 24.04

### Deployment

Other Docker-based deployment

### Anything else?

Possibly related to https://github.com/apache/airflow/issues/39514 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Can you try with mypy 1.9.0, which is what [Airflow uses and is defined in constraints](https://github.com/apache/airflow/blob/constraints-2.9.1/constraints-3.12.txt#L449)

**Comment by hterik** [comment]
Same error with mypy 1.9.0

**Comment by hterik** [comment]
I think this will be solved by https://github.com/apache/airflow/issues/38796

**Comment by potiuk** [comment]
Yeah. Duplicate.

**Comment by bergercookie** [comment]
Is this issue actually completed as indicated by its status? the two last comments suggest otherwise
I'm getting multiple mypy related issues with airflow 2.10.5 and it's confusing seeing that issues like these are marked as completed (even though they probably are not)

Could developers instead close these as duplicate instead (I think the github dropdown does allow for this.
