### ISSUE TITLE
Update the Search Ads 360 hook to Call the New Reporting API

### ISSUE THREAD

**Issue by Taishan314** [apache/airflow#39942]
### Description

The current Search Ads 360 API is being deprecated and replaced with the Search Ads Reporting API, details of which are found [here](https://developers.google.com/search-ads/reporting/migrate/overview).

I currently use the [GoogleSearchAds operators](https://github.com/apache/airflow/blob/main/airflow/providers/google/marketing_platform/operators/search_ads.py) which all call the GoogleSearchAdsHook, which in turn, establishes a connection to an api as seen [here](https://github.com/apache/airflow/blob/main/airflow/providers/google/marketing_platform/hooks/search_ads.py#L48).

I believe this is calling the api soon to be deprecated. _**The deprecation date supplied by google is the 30th June 2024.**_

### Use case/motivation

I'd like to see an update to this method to call the new api, perhaps make the old one optional for deprecation purposes.

The old api service name is: _doubleclicksearch.googleapis.com_
The new api service name is: _searchads360.googleapis.com_

I believe the change should be adding the string "**_searchads360_**" to the build() method inside the get_conn() method call.

Making that parameter configurable with the default as "**_doubleclicksearch_**" would be the ideal change for deprecation of the old api.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
cc @VladaZakharova

**Comment by Taishan314** [comment]
@molcay Thank you very much! Do you know if the version will be released before the 30th June?

**Comment by Taishan314** [comment]
FYI, I dived into the code for the replacement api and the change I suggested won't be enough for this update. 

Legacy API: https://googleapis.github.io/google-api-python-client/docs/dyn/doubleclicksearch_v2.html
Replacement API: https://googleapis.github.io/google-api-python-client/docs/dyn/searchads360_v0.html

**Comment by appley** [comment]
Hi! I am interested in working on this!
