### ISSUE TITLE
setup.py download URL

### ISSUE THREAD

**Issue by eerwitt** [apache/airflow#4]
While installing I noticed the `url` and `download_url` point to @mistercrunch's repo:

https://github.com/airbnb/airflow/blob/9a791999b871d5f19550cbf882fbd09037d99e52/setup.py#L69

> ```
>     url='https://github.com/mistercrunch/Airflow',
>     download_url=(
>         'https://github.com/mistercrunch/Airflow/tarball/' + version),
> ```

Is that the correct repository to install and update from?

**Comment by mistercrunch** [comment]
Good catch! This used to be on my personal repo until yesterday's announcement. I'll push a PR to fix this right now.

**Comment by mistercrunch** [comment]
Fixed in 1.0.1
https://pypi.python.org/pypi/airflow/1.0.1

**Comment by eerwitt** [comment]
Awesome and congrats!
