### ISSUE TITLE
Support `limit` and `offset` parameters for List task instances (batch) endpoint

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#40038]
### Description

As of now, `limit` and `offset` are not supported for [List task instances (batch)](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_mapped_task_instances) endpoint. Supporting them will help users fetch data in batches

### Use case/motivation

Limit and offset are available for List DAGs. Having this feature for listing task instances will help manage the amount of data retrieved

### Related issues

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
> @shahar1 , [Documentation](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch) does not mention about `page_offset` and `page_limit`.  But, I will try to use them and see if they work

I misread as DAG runs and not task instances, apologies :)
Maybe it can be implemented similarly though

**Comment by ShakaibKhan** [comment]
I can try adding this to the task instance batch endpoint. I think its just passing the `limit` and `offset` into the body and adding them to the task instance query. If no one else is addressing this I will assign it to myself.

**Comment by shahar1** [comment]
> I can try adding this to the task instance batch endpoint. I think its just passing the `limit` and `offset` into the body and adding them to the task instance query. If no one else is addressing this I will assign it to myself.

I assigned this task for you, thank you!

**Comment by ShakaibKhan** [comment]
Looks like [page_limit and page_offset](https://github.com/apache/airflow/blob/2eda7376f4c27df82f0cafba7699bcc46c3fcd05/airflow/api_connexion/schemas/task_instance_schema.py#L106) are already in the endpoint schema its just not used in the endpoint. I have added and tested the changes to the endpoint locally. I am working on adding some unit tests.

**Comment by yuxian0908** [comment]
Hi @ShakaibKhan, I’m planning to submit my first PR and was wondering if I could take on this issue? (If you’re not currently working on it, of course.)
