### ISSUE TITLE
Configuration option "max_templated_field_length" does not work on the rendered template content

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#40045]
### Apache Airflow version

2.9.1

### What happened?

The templated attribute contains a rather long SQL statement (20 000 B). It was displayed incorrectly both in the "Task Instance Detail" and in the "Rendered Template" section (the SQL statement was truncated). 

I set the max_templated_field_length configuration parameter to 32000. 

After that, the templated attribute was displayed fine in the "Task Instance Detail" section, but in the "Rendered Template" section it was still displayed incorrectly (see the pict)

Task Instance Detail section
![image](https://github.com/apache/airflow/assets/162625270/4e5f8951-d45d-446d-a791-04f1d4a73c27)

Rendered Template section
![image](https://github.com/apache/airflow/assets/162625270/12caeb51-7fac-4c16-80d2-33026c5ec8d4)

### What you think should happen instead?

Templated attribute for a given configuration should also appear correctly in the Rendered Template section.

I would also like to ask if the "Rendered Template" link could return to where it was before version 2.9.0. That is, as a subitem of the Details tab (at the same level as the links to Task Instance Details and List All Instances.

The Rendered template section is very frequently used (our Tasks contain mostly SQL) and the current settings since version 2.9.0 make it very difficult to use

### How to reproduce

Use long data (longer than max_templated_field_length settings) in the templated attribute and display it.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
I was unable to replicate this on `main`.  A few theories which might explain the issues here:

 - You will need to update the `max_templated_field_length` setting on your executors in order for it to take effect. Setting it on only the webserver won't change anything since the rendered fields are saved at execution time in the RTIF table.
 
 - Changing this setting will not un-truncate the rendered templates for tasks which already ran, since the templates are only rendered once (at execution time), so only tasks run _after_ the setting has been changed will reflect the larger value of `max_templated_field_length`. 
 
 Do either of these explain the issues you've been seeing?

**Comment by Pad71** [comment]
@SamWheating  Thank you very much, Sam, the problem was the the second point.  What confused me was that the "truncated" data in the Task Instance Details section displayed correctly immediately after changing the max_templated_field_length.

**Comment by Pad71** [comment]
not an error

**Comment by adinamarca** [comment]
> I was unable to replicate this on `main`. A few theories which might explain the issues here:
> 
> * You will need to update the `max_templated_field_length` setting on your executors in order for it to take effect. Setting it on only the webserver won't change anything since the rendered fields are saved at execution time in the RTIF table.
> * Changing this setting will not un-truncate the rendered templates for tasks which already ran, since the templates are only rendered once (at execution time), so only tasks run _after_ the setting has been changed will reflect the larger value of `max_templated_field_length`.
> 
> Do either of these explain the issues you've been seeing?

Does this affect only stored metadata in UI/Database but not task instance itself? I mean, it does not impact the actual execution of tasks or result in data loss within the task instances themselves? Thanks
