### ISSUE TITLE
download log - Try number 0 is invalid

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#40070]
### Apache Airflow version

2.9.1

### What happened?

I can see the logs if I click on the task

![Screenshot from 2024-06-05 17-41-13](https://github.com/apache/airflow/assets/10202690/fd7c59d5-9c42-4492-8613-2bd47d85ec22)

but If I click on download it show 

```log
{"message": [["default_host", "Error fetching the logs. Try number 0 is invalid."]], "metadata": {"end_of_log": true}}
```

and if I click on `see more`

it show nothing

### How to reproduce

it's a deferable KPO

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

keda autoscaling on the airflow workers

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Can you check if this is reproducible on main branch? There was segnificant change around `try_numver` which will be released in 2.10
