### ISSUE TITLE
Unable to Scroll Down to See All DAG Runs in Calendar View

### ISSUE THREAD

**Issue by hkc-8010** [apache/airflow#40083]
### Apache Airflow version

2.9.1

### If "Other Airflow 2 version" selected, which one?

2.9.1

### What happened?

I am unable to scroll down to see all the DAG runs in the calendar view of the Airflow UI. This seems to be an Airflow UI bug. The only workaround is to zoom out the web browser to see the whole calendar view on a single page.
![image (8)](https://github.com/apache/airflow/assets/95332229/3c820a09-cd85-43b9-897d-27ce382fc1ee)

### What you think should happen instead?

I should be able to scroll down to view all the DAG runs in the calendar view without having to zoom out the browser.

### How to reproduce

- To see this behaviour, you need to have a huge historical dag_runs history, for example, starting from 2015 up to 2024.
- Open the Airflow UI.
- Navigate to the calendar view.
- Try to scroll down to view all the DAG runs.

### Operating System

Darwin Hems-MBP.lan 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 arm64

### Deployment

Astronomer

### Deployment details

Using Helm for deployment on Kubernetes with no significant customizations to the UI components.

### Anything else?

This problem occurs every time I try to view the calendar with a large number of DAG runs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment]
discussed with @hkc-8010 in react calendar scroll is not available only. User had initiated a backfill till run_id 2015 and not able to scroll

**Comment by phanikumv** [comment]
cc @bbovenzi can we consider this for 2.10?
