### ISSUE TITLE
duplicate key value violates unique constraint serialized_dag_pkey for dynamic dag generation

### ISSUE THREAD

**Issue by jiananyim** [apache/airflow#40082]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.1

### What happened?

Hello,

We recently encountered the following error, and we can confirm that the DAG viewing_station_grid_data_analysis only appears once in our setup.
```
[2024-06-05T21:50:11.420+0000] {{logging_mixin.py:188}} INFO - [2024-06-05T21:50:11.419+0000] {{dagbag.py:647}} ERROR - Failed to write serialized DAG: /usr/local/airflow/dags/vjobs_dynamic_dag.py
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    self._assert_active()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(viewing_station_grid_data_analysis) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: ({'dag_id': 'db_snapshots_valarm_hourly', 'fileloc': '/usr/local/airflow/dags/dynamic_dags/vjobs_dynamic_dag_batch_7.py', 'fileloc_hash': 71059898310842332, 'data': '{"__version": 1, "dag": {"start_date": 1679702400.0, "_dag_id": "db_snapshots_valarm_hourly", "timetable": {"__type": "airflow.timetables.interval.Cr ... (104310 characters truncated) ... ': {\'cpu\': \'256m\', \'memory\': \'2Gi\'}}", "volumes": [], "volume_mounts": [], "cluster_context": "aws"}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2024, 6, 6, 1, 10, 11, 534883, tzinfo=Timezone('UTC')), 'dag_hash': '5be21fc04823d4a5ed5b3733d21cabcd', 'processor_subdir': '/usr/local/airflow/dags'}, {'dag_id': 'enterprise_metrics_command_ingestion', 'fileloc': '/usr/local/airflow/dags/dynamic_dags/vjobs_dynamic_dag_batch_7.py', 'fileloc_hash': 71059898310842332, 'data': '{"__version": 1, "dag": {"start_date": 1686096000.0, "_dag_id": "enterprise_metrics_command_ingestion", "timetable": {"__type": "airflow.timetables.i ... (57998 characters truncated) ... ': {\'cpu\': \'256m\', \'memory\': \'2Gi\'}}", "volumes": [], "volume_mounts": [], "cluster_context": "aws"}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2024, 6, 6, 1, 10, 11, 856045, tzinfo=Timezone('UTC')), 'dag_hash': '296356c08d551d90c140c848369cfa92', 'processor_subdir': '/usr/local/airflow/dags'}, {'dag_id': 'salesforce_snapshot_delta', 'fileloc': '/usr/local/airflow/dags/dynamic_dags/vjobs_dynamic_dag_batch_7.py', 'fileloc_hash': 71059898310842332, 'data': '{"__version": 1, "dag": {"start_date": 1693872000.0, "_dag_id": "salesforce_snapshot_delta", "timetable": {"__type": "airflow.timetables.interval.Cro ... (186206 characters truncated) ... "limit_memory": "16Gi", "limit_cpu": "2048m"}, "volumes": [], "volume_mounts": [], "cluster_context": "aws"}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None
```

We have 5 schedulers running. For DAG generation, we have a dynamically generated DAG file that can produce over a hundred DAGs with fixed names.

It appears that these 5 schedulers are writing to the database simultaneously, causing contention. Therefore, I would like to understand the locking mechanism in Airflow and the writing mechanism for dynamic DAGs.

1. How does Airflow handle DAGs generated from the same file during processing? Are they written to the database using a single connection, or are they written in separate batches?
2. Is there any locking mechanism between schedulers, or should the database be configured to allow only one writing point?
3. Do you have any other suggestions for handling such errors?

Thank you very much!

### What you think should happen instead?

Airflow should only process it without the duplicate key problem

### How to reproduce

dynamic dag generation with a large number of dags.

### Operating System

amazon mwaa

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Have you tried t separate the DAG parsing process out of the schedulers. If you run 5 scheduler instances it could be in deed multiple schedulers are parsing the same DAG files in paralllel.
See https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#standalone-dag-processor

This also reduces load from schedulers, so running one standalone DAG processor also might give an option to reduce the amount of parallel schedulers. We have not seen more schedlung throughput in our setup if more than 3 schedulers are running.

**Comment by jiananyim** [comment]
Hi @jscheffl ,
It seems like the solution only reduces the likelihood of issues occurring, rather than solving the problem entirely.
With the MWAA hosted by Amazon, we cannot set up only one Airflow scheduler. Does it means this problem happens as expected?

**Comment by potiuk** [comment]
Do you see this happening in the logs but your schedulers continue working ? Or do you see some other problems resulting from those log entries?

**Comment by jiananyim** [comment]
@potiuk  the schedulers will be blocked by these errors until they restart after a timeout. 
During this period, some jobs will fail immediately with an error indicating that they cannot create the log group.

**Comment by potiuk** [comment]
> @potiuk the schedulers will be blocked by these errors until they restart after a timeout.

Blocked in what sense? Are they crashing and your deployment does not start them up? Are they hanging? Could you explain the exact behaviour that you see please?

**Comment by jiananyim** [comment]
@potiuk 
We cannot determine the exact sequence of events, but we have observed the following:
1. The scheduler throws jobs and then hangs indefinitely until they are killed upon reaching the timeout period. Afterward, a new scheduler is initiated.
2. Some jobs fail to execute, and we see errors indicating that the log group does not exist. Upon inspection, we confirmed that the corresponding log groups were indeed not created.

**Comment by potiuk** [comment]
> The scheduler throws jobs and then hangs indefinitely until they are killed upon reaching the timeout period. Afterward, a new scheduler is initiated.

Timeout of what? How do you determine timeout. What timeout it is? How do you decide when timeout is reached?

**Comment by jiananyim** [comment]
We set the time out by  -- 
core.dag_file_processor_timeout | 150
core.dagbag_import_timeout | 150
And we found we cannot get new scheduler until 150s. (We changed it to 200 or 300, the waiting time also got changed)

And we set the standalone_dag_processor to true. But all dags disappeared only with this configuration change.

**Comment by potiuk** [comment]
I am not sure if I understand, but this means that parsing of your DAG hangs. Something in your DAGs is just blocking during parsing - for example reaching out to external URL, connecting to the database etc. You are the only person in the world that can track it down. I suggest thorough reading and applying https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code and following chapters and tracking down where parsing your DAG hangs - it's all your code that is in the DAG and there is no way airflow can interfere with it, so you have an investigation on your side to make.

**Comment by jiananyim** [comment]
We updated the version to 2.9.2, and this error has almost disappeared. We still don't know the root cause.

**Comment by greg-seesaw** [comment]
Funny enough, this error started happening to us after we upgraded MWAA from 2.8.1 to 2.9.2 on Wednesday.

I'm not sure what's happening exactly either, but putting some data points here:

1. We have a small MWAA environment (`mw1.small`): 2 schedulers, 1-10 workers, and only 6 DAGs, most of which are small.
2. We are using all the MWAA defaults, like `dag_file_processor_timeout = 50` and `standalone_dag_processor = False`. (I'm not sure if we can change the latter in MWAA.)
3. This tends to happen around the time a DAG is running
4. There have also been intermittent errors in the scheduler log, like: `[ [34m2024-07-17T20:05:36.564+0000 [0m] { [34mscheduler_job_runner.py: [0m1422} ERROR [0m - Couldn't find DAG SNOWFLAKE_MONITORING_DAG in DAG bag or database! [0m`. They don't necessarily line up with the DAG Processing errors.
5. We've reduced the amount of top-level Python code as much as we could, to minimize DAG import time.

@jiananyim Has this error appeared the last 2 days for you?

**Comment by millin** [comment]
@rafidka Hello! Could you please pay attention to this?
We also encountered this problem after the update MWAA to 2.9.2.
It looks like the last version's config changes may have caused this.

**Comment by rafidka** [comment]
@millin, if you have reasons to think this is a MWAA issue, then please reach out to us via the official channels and someone in the team will take a look.

**Comment by rafidka** [comment]
If the issue is related to 2.9.2, you can easily create an issue under https://github.com/aws/amazon-mwaa-docker-images/, since the code for the 2.9.2 version is now open source.

**Comment by millin** [comment]
I did a research.
This error is the result of multiple dag-processors simultaneously trying to insert a new `serialized dag` into the table.
After some time, one of the dag-processors manages to do this and the error goes away.

When processing dynamic DAGs (especially if there are several hundred of them in one dag-file) it just happens more often, because inserting new rows takes more time.

In the case of MWAA the error occurs very often because when starting a new image (e.g. for new worker) each time the `airflow db migrate` [command is called](https://github.com/aws/amazon-mwaa-docker-images/blob/2c0bad6b29f8f856fe4c4938a7b6d99ab626f1ec/images/airflow/2.9.2/python/mwaa/entrypoint.py#L114) from `entrypoint`, which in turn runs `reserialize_dags` and clears the whole `serialized_dag` table.

**Comment by rafidka** [comment]
We created this PR https://github.com/aws/amazon-mwaa-docker-images/pull/125 to fix the issue in Amazon MWAA. However, I believe a fix is also needed on Airflow side. If the database is already migrated, the `airflow db migrate` should be a no-op operation, as there isn't any gain (and certainly some harm) from reserializing already correctly serialized DAGs,
