### ISSUE TITLE
Env_vars from KubernetesPodOperator does not assume secret (deploy as env var) because secrets are loaded after env vars into the pods.

### ISSUE THREAD

**Issue by ana-carolina-januario** [apache/airflow#40092]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.6.0

### What happened?

We've tried to perform some bash commands where we need to use env_vars to build the command.
The main environment variable, so called COMMAND, has a placeholder to be replaced by some secret values, for instance:
(here having (), {}, or nothing surrounding the env_var, does not affect the result.)

COMMAND="echo 'This is my secret $(SECRET_AS_ENV_VAR)'"  

but when I run:
echo $COMMAND

The result does not replace the variable.

When I run:
echo $SECRET_AS_ENV_VAR
The value is printed correctly so, the variable is successfully loaded.

I've tried to 

I've analyzed the pods and noticed the order env_vars are presented, might be affecting this replacement.

I've notice that when the pod is being build, the secrets (as env vars) are being loaded after the env vars. This could be reviewed in order to load secrets prior to the load of env_vars.

Thanks,
Ana

### What you think should happen instead?

I believe the env var COMMAND should have the SECRET_AS_ENV_VAR replaced properly when starting the pod.

After looking at the code, I've noticed this function should load secrets at the same time (or even before) loading env vars.:
https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/7.3.0/_modules/airflow/providers/cncf/kubernetes/operators/pod.html#KubernetesPodOperator.build_pod_request_obj 

### How to reproduce

Using your KubernetesPodOperator example,
https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/1.2.0/_modules/airflow/providers/cncf/kubernetes/example_dags/example_kubernetes.html
 add a variable with a value that uses the secret deployed as env:
 
 init_environments = [k8s.V1EnvVar(name='key1', value='This string should show the value of SQL_CONN = $(SQL_CONN)'), k8s.V1EnvVar(name='key2', value='value2')]

For the args parameter:
args=['echo $key1']

With this echo, the value won't be replaced in the value of key1.
But if you run 'echo $SQL_CONN'  the value will be correctly printed.

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian

### Versions of Apache Airflow Providers

Version of the apache-airflow-providers-cncf-kubernetes is 6.1.0 

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ana-carolina-januario** [comment]
Hi,
Additionally, I've tried multiple workarounds:

1. export to other env var like:
    export COMMAND_1=$COMMAND
    without success.
2. export the secret to another env var(using the cmds parameter) and then export the command to another env_var as well:
cmds=['sh', '-c', 'export NEW_SECRET=$(SQL_CONN) ; export COMMAND_1=$(COMMAND)']
also without changes on the behaviour.

Thanks,
Ana.

**Comment by raphaelauv** [comment]
use kubernetes native secret ( since kubernetes env_vars are plain text )

```python

secret_toto = Secret(
    deploy_type='env',
    deploy_target='THE_SECRET',
    secret="toto",
    key="tata')

KubernetesPodOperator(
    task_id="task-toto",
    kubernetes_conn_id="kubernetes_default",
    image="aaaaa:0.1",
    secrets=[secret_toto],
)

```

**Comment by ana-carolina-januario** [comment]
I'm not sure if I understood the suggestion.
My problem is that, once the pod is launched, the order of the env_vars (secrets+env_vars) is not the ideal. - if they are independent fro each other, the order does not matter.

I would expect the secrets being loaded before the env_vars but once I run "describe" from kubectl for the pod, I figure that the secrets are loaded **after** the env_vars (that I build dynamically and hence it is not compatible to put them in a secret).
Once I launch the pod, I 'need' the secrets to be loaded before the env vars so I can perform all actions using env_vars that refer secrets' values.

Let me know if this does not make sense to you.

Thanks!

**Comment by ana-carolina-januario** [comment]
Actually, env_vars can be added using a for loop right after the load of the secrets, instead of being loaded at pod instance creation:

<img width="307" alt="image" src="https://github.com/apache/airflow/assets/59447613/118435c9-c9dd-4f50-aea7-b08c5f6f256e">

and making sure of removing the load of the env_vars from pod instantiation:
<img width="233" alt="image" src="https://github.com/apache/airflow/assets/59447613/c9d7119b-f475-4dad-b5d9-d1112157872a">

**Comment by ephraimbuddy** [comment]
Closing as won't fix

**Comment by potiuk** [comment]
Also we just merged https://github.com/apache/airflow/pull/40519 that addresses that by explicitly mentioning in appropriate places that env variables are bad way of passing secrets.

**Comment by ajanuariogalp** [comment]
Actually I am using k8s native secrets to pass credentials/secrets.
What I pass as env var is a command with the reference for a secret deployed as env_Var:
from airflow.kubernetes.secret import Secret
secret_value = Secret(
                        deploy_type=deploy_type,
                        deploy_target=secret_key,
                        secret=secret_name,
                        key=value
                    )
and my command is like:
COMMAND="some-tool $(SECRET_DEPLOYED_AS_ENV_VAR)"
where _some-tool_ needs the value passed through the env_var that contains the secret value.

I am not passing the value of the secret directly as an env var, I am passing through k8s secret, deploying as env_var.

Thanks!

**Comment by ana-carolina-januario** [comment]
Actually I am using k8s native secrets to pass credentials/secrets.
What I pass as env var is a command with the reference for a secret deployed as env_Var:
from airflow.kubernetes.secret import Secret
secret_value = Secret(
deploy_type=deploy_type,
deploy_target=secret_key,
secret=secret_name,
key=value
)
and my command is like:
COMMAND="some-tool $(SECRET_DEPLOYED_AS_ENV_VAR)"
where some-tool needs the value passed through the env_var that contains the secret value.

I am not passing the value of the secret directly as an env var, I am passing through k8s secret, deploying as env_var.

Thanks!

**Comment by potiuk** [comment]
> I am not passing the value of the secret directly as an env var, I am passing through k8s secret, deploying as env_var.


I stull do not understand. If you use native secret in K8S you should be able to mount it as ENV var directly - and value of that secret should be available for you - this is native k8s behaviour, and Airflow has nothing to do with it. 

I really have no idea in this case what is passed when and what problem you have - maybe I am stupid, but most likely You should explain in ore detail what your problem is.

Please try to explain it in the way that we can understand it if you need help.

I will re-open it and convert into discussion so that you can continue explaining it, but this is almost for sure not an airflow issue, so discussion is more appropriate.
