### ISSUE TITLE
schedule_interval not working as expected?

### ISSUE THREAD

**Issue by kevinmandich** [apache/airflow#401]
Hi there,

I created a DAG like such:

```
START_DATE = datetime.combine(date(2015,9,14), datetime.min.time())

default_args = {
  'owner': 'kmandich',
  'pool': 'ep_feedback_report',
  'depends_on_past':False,
  'start_date': START_DATE,
  'email': ['kmandich@agari.com'],
  'schedule_interval':timedelta(days=7),
  'email_on_failure': True,
  'email_on_retry': True
}

dag = DAG('feeback_report', default_args=default_args)
```

I was expecting this DAG to run once every 7 days, starting at 0:00 UTC on Sep. 14, 2015. However, it seems to be running every dat at 0:00 UTC. Am I not setting the `schedule_interval` field correctly? From what I can tell after checking the documentation, this is how this parameter should be defined. Please let me know, and thank you.

**Comment by mistercrunch** [comment]
`schedule_interval` is a DAG param now...

**Comment by mistercrunch** [comment]
I just added a warning to clarify this:
https://github.com/airbnb/airflow/commit/3e8bb2abf18c3a130c52288e25f5f7d114e407ad

**Comment by kevinmandich** [comment]
For sure, thanks!
