### ISSUE TITLE
Pandas dependency locked at pre-0.16?

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#402]
[migrating commit comment https://github.com/airbnb/airflow/commit/fb7366c6c837b50d614283861d54f2747e984617 for visibility]

Just curious, why the hard dependency on pre-0.16 pandas at https://github.com/airbnb/airflow/commit/fb7366c6c837b50d614283861d54f2747e984617#diff-2eeaed663bd0d25b7e608891384b7298R57? 0.16.2 is the current stable version and 0.17 is coming very soon -- currently in RC.

Pandas in particular is likely to be used in lots of user-defined Airflow tasks -- requiring users to use an old version of the library seems onerous given that it looks like Airflow itself only uses very basic pandas features.

**Comment by mistercrunch** [comment]
I've been bit with releases breaking their API (flask-login) recently.

It theory pre `1.0` release can break their API in second digit releases and post 1.0 in their first digit release, so I'm matching that.

So for now my approach is to allow for `>=` than what I run my unitests on, and `<` than where the API may change.

The alternative are:
- Fully pinning version numbers, missing out on bug fixes and security updates
- Using `>=` and hope for the best (and face the worst)
- ?

Airflow is special as it has a lot of dependencies by the nature of the project, so we will suffer from dependencies changing APIs. This is trying to prevent that.

BTW it's about time for pandas to go 1.0 ! Wow.

**Comment by mistercrunch** [comment]
I trust pandas to not break the API until 1.0 btw, I'll approve a PR that says `<1.0.0`

**Comment by jlowin** [comment]
Your approach makes a lot of sense. It's too bad virtualenv-type solutions fail here because the Airflow env would need to do all the executing. I'll submit a PR for the Pandas 1.0 lock.
