### ISSUE TITLE
Parameter invalid (cluster) in amazon-> operator -> EcsRunTaskOperator when using deferrable

### ISSUE THREAD

**Issue by frantoja** [apache/airflow#40207]
### Apache Airflow Provider(s)

amazon

### Apache Airflow version

2.8.1

### Operating System

AWS MWAA

### Deployment

Amazon (AWS) MWAA

### What happened

I have a custom class inheritance from EcsRunTaskOperator.
When I set deferrable = True, the Airflow task runs and changes to the deferred state successfully and also the ECS task runs successfully. However, when it returns (TaskDoneTrigger - task finished), the method execute_completes -> self._after_execution() -> self._check_success_task() -> response = self.client.describe_tasks(cluster=self.cluster, task=[self. arn]) shows an error:

botocore.exceptions.ParamValidationError: Parameter validation failed
Invalid type for parameter cluster, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

### What you think should happen instead

I believe (and tested) that the variable self.cluster (approximately line 696 in the file airflow/providers/amazon/aws/operators/ecs.py) "looses the value"

### How to reproduce

Set the parameter deferrable to true in EcsRunTaskOperator

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
Indeed, the operator `EcsRunTaskOperator` use some variables that might not have been set when executing `execute_complete`. Ideally `execute_complete` should only use information from the event, the executor/worker running `execute` and `execute_complete` might (and most likely) be different
