### ISSUE TITLE
adjust the task execution order

### ISSUE THREAD

**Issue by tongxin880120** [apache/airflow#40213]
### Body

![image](https://github.com/apache/airflow/assets/37608505/00556b36-7e1a-4247-b74f-d75df71299f4)

Hi, I would like to ask a problem. I want to adjust one task first to execute in a task grid. How I adjust it . thank you 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
> I acknowledge that I am a maintainer/committer of the Apache Airflow project.

You are not a mantainer of the project. Please don't use this option.
If you have a bug or feature request to submit use the right form
