### ISSUE TITLE
Google Cloud BigQuery Transfer Operator to Google Cloud Storage misleading documentation

### ISSUE THREAD

**Issue by joonvena** [apache/airflow#40217]
### What do you see as an issue?

https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/transfer/bigquery_to_gcs.html

Currently this documentation gives expression that this Operator would be used to import file from GCS to BigQuery.

### Solving the problem

Change all GCS > BigQuery sections to be BigQuery > GCS instead so its clear for what the operator is actually used.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to fix it. Though you do not need to open an issue to fix it with PR.
