### ISSUE TITLE
Support network tags in airflow.providers.google.cloud.operators.dataproc.DataprocCreateBatchOperator()

### ISSUE THREAD

**Issue by githubwua** [apache/airflow#40232]
### Description

When submitting a batch job to Dataproc, it is possible to specify network tags, as shown [here](https://cloud.google.com/sdk/gcloud/reference/dataproc/batches/submit)

But [airflow.providers.google.cloud.operators.dataproc.DataprocCreateBatchOperator()](https://github.com/apache/airflow/blob/d5a75446a62ba8804879177ce394c7456adaa4d3/airflow/providers/google/cloud/operators/dataproc.py#L2912) does not have an argument to accept network tags.  So it is impossible to specify network tags when submitting Dataproc batch jobs from Airflow.

This is a feature request to add support for network tags in DataprocCreateBatchOperator()

### Use case/motivation

When a network has firewall rules that allow/deny network traffic, we need to specify network tags to apply specific firewall rules to worker and master nodes.  Without network tags, nodes cannot communicate with each other.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kunaljubce** [comment]
I want to take a stab at this, can you please assign this to me?

**Comment by potiuk** [comment]
Assigned.

**Comment by githubwua** [comment]
Thanks for taking a stab at this.  By the way, can we also add support for tags for DataprocCreateClusterOperator as well?

**Comment by kunaljubce** [comment]
> Thanks for taking a stab at this. By the way, can we also add support for tags for DataprocCreateClusterOperator as well?

@githubwua Just to confirm, your ask here is to add the tags as mentioned [here](https://cloud.google.com/sdk/gcloud/reference/dataproc/batches/submit) right?

> --tags=[TAGS,…]
> Network tags for traffic control.

**Comment by kunaljubce** [comment]
One more thing @githubwua. Regarding the original requirement here to add `tags` to `DataprocCreateBatchOperator`, can you try to pass your network tags in the below syntax to the batch config and try once?

```
BATCH_CONFIG = {
    "environment_config": {
        "execution_config": {
            "subnetwork_uri": "<your-subnet>",
            "network_tags": "<your-network-tags>",
        }
    },
    "spark_batch": {
        "jar_file_uris": ["file:///usr/lib/spark/examples/jars/spark-examples.jar"],
        "main_class": "org.apache.spark.examples.SparkPi",
    },
}
```
and then pass this `BATCH_CONFIG` while instantiating the operator?

```
create_batch = DataprocCreateBatchOperator(
        task_id="create_batch",
        project_id=PROJECT_ID,
        region=REGION,
        batch=BATCH_CONFIG,
        batch_id=BATCH_ID,
    )
```

I dug deep into the [GCP docs](https://cloud.google.com/python/docs/reference/dataproc/latest/google.cloud.dataproc_v1.types.ExecutionConfig) for the `BatchControllerClient()` and found this out, better to try if this works before making a code change on airflow side.

**Comment by kunaljubce** [comment]
@githubwua FYI in case this fell under your radar :)

**Comment by githubwua** [comment]
Thank you for finding the right place to specify network tags. I didn't realize it is available deep inside the cluster config field.  I will try and see if I can update the documentation to point this out.
