### ISSUE TITLE
Incorrect run gets started

### ISSUE THREAD

**Issue by CarlKarlssonSchmidt** [apache/airflow#40274]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.6.3

### What happened?

We have seen that on DAG:s with depend_on_past=True & max_active_task=1 a run which is not the next in line starts and immediately hangs due to depend_on_task=True. Since we have max_active_task=1 this blocks the DAG from running completely until the incorrect run i cleared manually.

 
![Screenshot from 2024-06-14 07-53-01](https://github.com/apache/airflow/assets/4922502/ab0df2c5-0531-45eb-88cd-4a4007349104)
![Screenshot from 2024-06-17 11-13-40](https://github.com/apache/airflow/assets/4922502/1dc65354-0c0a-44fa-ba8d-35080cae4bf1)

### What you think should happen instead?

The next run in line should be started

### How to reproduce

This is intermittent. I'm running a re-running a DAG by clearing the state on all previous runs. Maybe 1 of 10 triggeres are on the wrong date.

### Operating System

MWAA

### Deployment

Amazon (AWS) MWAA

### Anything else?

For this DAG and a dag with a sensor to it, 1 out of 10 triggers/runs are incorrect.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment]
@CarlKarlssonSchmidt I am not able to reproduce this. can you share your DAG? Also have you also tested this with 2.9.2

**Comment by ephraimbuddy** [comment]
@CarlKarlssonSchmidt , you can also update to the latest version and let us know if it's still the case. Airflow 2.6 is far from the latest one
