### ISSUE TITLE
Handle  toctree contains reference to nonexisting document `_api/` errors better when building docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#40302]
### Body

When building documentation (`breeze build-docs`) and you press ctrl-c in-between, the autoapi docs might remain empty and they cause

```
toctree contains reference to nonexisting document '_api/*` errors better when building docs
```

Currently the way to fix it is to add `--clean-build` option when you build docs.

We should likely improve the build process to handle it a bit better. Either 

a) detect it happens and regenerate api docs
b) suggest the user to use `--clean-build` when it happens

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by poorvirohidekar** [comment]
@potiuk I would like to try this. Could you please assign this to me?

**Comment by amoghrajesh** [comment]
Feel free to work on this
