### ISSUE TITLE
OpenLineage defaults in airflow.cfg incorrect

### ISSUE THREAD

**Issue by merobi-hub** [apache/airflow#40306]
### Apache Airflow Provider(s)

openlineage

### Versions of Apache Airflow Providers

apache-airflow-providers-openlineage==1.5.0

### Apache Airflow version

2.9.2

### Operating System

MacOS Sonoma 14.5

### Deployment

Virtualenv installation

### What happened

Found in airflow.cfg:
```
[openlineage]
transport = '{"type": "http", "url": "http://localhost:5000/"}'
namespace = 'airflow-dev'
```

Expected:
```
[openlineage]
transport = {"type": "http", "url": "http://localhost:5000", "endpoint": "api/v1/lineage"}
namespace = airflow-dev
```

### What you think should happen instead

Lineage from Airflow is not being received by Marquez with the current defaults. When changed to the corrected values above, lineage is received. Perhaps there is a bug in the parser being used to get the variables from the environment, or there is an issue in the provider's [conf.py](https://github.com/apache/airflow/blob/main/airflow/providers/openlineage/conf.py)-?

### How to reproduce

Run `airflow standalone` command after confirming that the provider and its dependencies have been installed.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tatiana** [comment]
@mobuchowski would love your thoughts on this one

**Comment by potiuk** [comment]
I don't think this is about defaults. We need to know the history of what happened to the airflow.cfg you refer to @merobi-hub ? and where the values were taken from - but this is not about "defaults".

From what I see, default for this parameter is empty. And you have to manually set it. And example explaining it changed in https://github.com/apache/airflow/pull/37620 to include the endpoint.

When you run:

```
airflow config list --defaults
``` 

You get this:

```
# Pass OpenLineage Client transport configuration as JSON string. It should contain type of the
# transport and additional options (different for each transport type). For more details see:
# https://openlineage.io/docs/client/python/#built-in-transport-types
#
# Currently supported types are:
#
#   * HTTP
#   * Kafka
#   * Console
#   * File
#
# Example: transport = {"type": "http", "url": "http://localhost:5000", "endpoint": "api/v1/lineage"}
#
# Variable: AIRFLOW__OPENLINEAGE__TRANSPORT
#
# transport =
```

So the "endpoint" is mentioned in example, but defaults are empty. Previously indeed the example did not have endpoint and previous versions of openlineage provider accepted it this way.

So I presume (@merobi-hub?) that this is all about "What do we do if the users used previous version of the openlineage, configured it and now with the new version of openlineage it does not work" - so it's more of a migration issue ?

My suggestion would be - if really "endpoint" is needed - to add it automatically if missing and raise a warning that confiiguration should be updated. 

We did something similar with `auth_backends` parameter of `api` session - where in new version of it we expect "session" backend to be explicitly added, but in some old versions it was not needed, so we add it automatically if missing and raise a warning for the user to update their configuration.


```python
    def _upgrade_auth_backends(self):
        """
        Ensure a custom auth_backends setting contains session.

        This is required by the UI for ajax queries.
        """
        old_value = self.get("api", "auth_backends", fallback="")
        if old_value in ("airflow.api.auth.backend.default", ""):
            # handled by deprecated_values
            pass
        elif old_value.find("airflow.api.auth.backend.session") == -1:
            new_value = old_value + ",airflow.api.auth.backend.session"
            self._update_env_var(section="api", name="auth_backends", new_value=new_value)
            self.upgraded_values[("api", "auth_backends")] = old_value

            # if the old value is set via env var, we need to wipe it
            # otherwise, it'll "win" over our adjusted value
            old_env_var = self._env_var_name("api", "auth_backend")
            os.environ.pop(old_env_var, None)

            warnings.warn(
                "The auth_backends setting in [api] has had airflow.api.auth.backend.session added "
                "in the running config, which is needed by the UI. Please update your config before "
                "Apache Airflow 3.0.",
                FutureWarning,
                stacklevel=1,
            )
```

**Comment by merobi-hub** [comment]
@kacpermuda thanks for your comment. This was a case of user error unfortunately (or fortunately depending on how you look at it!), so I'm closing this.
