### ISSUE TITLE
After deleting a dag from the dags directory, it is still displayed in the UI

### ISSUE THREAD

**Issue by tatyana12345** [apache/airflow#40322]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.3

### What happened?

Dag has been removed from the airflow dags directory /opt/airflow/dags. Dag is not displayed when running the airflow dags list command. But it is still available in the Airflow UI, and it is also available in the Airflow postgres database.

### What you think should happen instead?

It is expected that dag will be automatically removed from the web interface after deleting dag from the dags directory.

### How to reproduce

Remove dag from the /opt/airflow/dags directory and it will still be available in the web interface even after a few days

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Deleting the Airflow dag file doesn't delete the db entries. You might want to try below command to delete the related entries. Please also check the below discussion that has different steps in deleting the dag completely.

https://github.com/apache/airflow/discussions/21864

```
airflow dags delete -h 
Usage: airflow dags delete [-h] [-v] [-y] dag_id

Delete all DB records related to the specified DAG

Positional Arguments:
  dag_id         The id of the dag

Options:
  -h, --help     show this help message and exit
  -v, --verbose  Make logging output more verbose
  -y, --yes      Do not prompt to confirm. Use with care!
```

**Comment by shahar1** [comment]
Please try @tirkarthi 's suggestion.
I'm converting the issue into a discussion, as it seems like an expected behavior.
