### ISSUE TITLE
Request to Reintroduce Tasks Duration Multi Line Graph

### ISSUE THREAD

**Issue by ahdeanlau** [apache/airflow#40337]
### Description

As an Analyst, I find the old Task Duration graph much more effective for observing outliers since it consolidates the duration of all tasks line graphs as a multi line graph.

### Use case/motivation

Currently, we can only view the duration of tasks individually, which makes it difficult to identify spikes in specific tasks, especially if the total DAG run duration appears normal (possibly due to other tasks finishing faster). Could we reintroduce the old Task Duration graph or combine it with the new one to improve the visibility of task duration outliers?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
cc @bbovenzi, do we have a similar thing somewhere?

**Comment by tirkarthi** [comment]
I tried an initial attempt at it and still doesn't pass with typescript compiler checks. The idea is to have task duration tab when no task or run_id is selected. Then go through the grid data to group all run durations (excluding queued duration) in the echarts required format and construct a stacked line chart similar to the legacy implementation. Still need to test with task groups but the initial work with screenshot and branch as below.

Branch : https://github.com/tirkarthi/airflow/tree/task-duration-all
Apache echarts example : https://echarts.apache.org/examples/en/editor.html?c=line-stack

![image](https://github.com/apache/airflow/assets/3972343/bcb28af1-85d5-4b3a-97cc-d8f9e711498b)
