### ISSUE TITLE
Add on_kill to SSHOperator

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#40343]
### Body

The SSHOperator does not have `on_kill` method which could deliberately close the ssh client. This means that the klient is close by TERM or even KILL signal when the task is closed and it might leave the connection to SSH still open for quite some time when the server might not realise that the client is closed. 

Closing the client gently should improve the speed with which the SSH server will close such stale connections in most cases.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vatsrahul1001** [comment]
@potiuk can I take this up?

**Comment by MRLab12** [comment]
I had started some work on this and did not noticed it was assigned. Happy to hand it off it someone else is already working on it.

**Comment by vatsrahul1001** [comment]
@MRLab12 go for it if you already have started in this

**Comment by MRLab12** [comment]
@vatsrahul1001 Thanks! 

@potiuk I opened that draft PR to get an idea of where this new `on_kill` method should be used or if the idea is to just let the user call it when they need it.
