### ISSUE TITLE
values.yaml `dags.gitSync.containerLifecycleHooks` Does not working

### ISSUE THREAD

**Issue by chanNamgung** [apache/airflow#40364]
### Official Helm Chart version

1.11.0

### Apache Airflow version

2.7.1

### Kubernetes Version

1.27

### Helm Chart configuration

`dags.gitSync.containerLifecycleHooks` Does not working.

I think it need to add  some commands at `git_sync_container` in `_helpers.yaml` 

### How to reproduce

1. set `dags.gitSync.containerLifecycleHooks`
2. check git-sync container does not have any hooks

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by getChan** [comment]
take
