### ISSUE TITLE
Quickstart Pre-reqs

### ISSUE THREAD

**Issue by lmalladi** [apache/airflow#404]
Had to install gcc, subversion on base Amazon linux AMI before I run pip install airflow. Also requires super user privs

**Comment by lmalladi** [comment]
also gcc++

**Comment by mistercrunch** [comment]
subversion?

**Comment by mistercrunch** [comment]
Do you know which lib needed GCC? `python-mysql`? Did you install subpackages?

Also if you want to install python packages in userspace you may want to check out `virtualenv`
