### ISSUE TITLE
admin canot see admin components

### ISSUE THREAD

**Issue by nevo11** [apache/airflow#40406]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.0

### What happened?

Hey, I have i client that usess the airflow deployment we created and allthough we gave is user admin role he cant see the option under admin **some** of the time. ther edosnet seame to be enething in the log to show the issus and the bug appear and disappear randomly. 
Has any one else encountered this issus? Thanks

P.S. sometimes the user see some of the option but not other, like only the plugin option.

### What you think should happen instead?

the user with the admin role shoud see the admin option consistently

### How to reproduce

i am not shore but this error seemes to occur only with granted admin user.

### Operating System

debain 12

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please upgrade to latest 2.9.* version. This is a known issue solved in 2.9.2. Generally speaking you should always upgrade to latest version of airlfow - even if you do not want to upgrade to latest, latest, latest in your minor line ONLY contains bugfixes (including security fixes), so not upgrading from version .0 when there is .1 and .2 makes very little sense.
