### ISSUE TITLE
ProcessingJobName is not preserved after execution returns from deferred state in SM proceesing job

### ISSUE THREAD

**Issue by joch0a** [apache/airflow#40432]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

We are using 8.23.0 version of airflow provider package and set deferrable to True when using SMProcessingJob. 

We set define the ProcessingJobName with something like "project-dag_name-date-uuid", where uuid is to deduplicate job name upon retry. However, when the execution gets back from deferred state, the original uuid is not preserved and there would be a new uuid so the operator cannot find a job with the new job name and it would fail.

There is a closed related issue (https://github.com/apache/airflow/issues/39503) but the fix only applies for Transform jobs.

### Apache Airflow version

2.8.1

### Operating System

Amazon Linux AMI

### Deployment

Amazon (AWS) MWAA

### How to reproduce

For a given SMProcessingJob 
1) Set "ProcessingJobName": f"{name}-{str(uuid4())[:8]}".
2) Set deferrable = True
3) The run the DAG.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
Fixed as part of #40706
