### ISSUE TITLE
ElasticsearchSQLHook fails with AttributeError: __enter__

### ISSUE THREAD

**Issue by Pooort** [apache/airflow#40430]
### Apache Airflow Provider(s)

elasticsearch

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.0
apache-airflow-providers-elasticsearch==5.4.1
apache-airflow-providers-fab==1.1.1
apache-airflow-providers-ftp==3.9.1
apache-airflow-providers-http==4.11.1
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.1

### Apache Airflow version

v2.9.2

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### What happened

[Documentation's usage example](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/5.4.1/hooks/elasticsearch_sql_hook.html) for ElasticsearchSQLHook:
```
    es = ElasticsearchSQLHook(elasticsearch_conn_id=CONN_ID)

    # Handle ES conn with context manager
    with es.get_conn() as es_conn:
        tables = es_conn.execute("SHOW TABLES")
        for table, *_ in tables:
            print(f"table: {table}")
    return True
```

fails with: `AttributeError: __enter__`

### How to reproduce

Implement [Documentation's usage example](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/5.4.1/hooks/elasticsearch_sql_hook.html).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Since tou mentioned you deploy with MWAA, are you interacting with elasticsearch or with opensearch?

**Comment by aritra24** [comment]
@Pooort a full stack trace and a ready to use dag for repro would help speed up a fix.

**Comment by potiuk** [comment]
Yes. Lack of stack trace makes it impossible to help you.
