### ISSUE TITLE
Allow setting log_driver when using DockerSwarmOperator

### ISSUE THREAD

**Issue by xjchew** [apache/airflow#40533]
### Description

Allow DockerSwarmOperator to be initialized with a `log_driver` argument which will be used by Docker SDK to create the service.

### Use case/motivation

I have a Docker Swarm with all the nodes set to `gelf` logging driver as default. However, DockerSwarmOperator requires the services' logging driver to be `json-file`.
Allowing the logging driver to be specified when initializing the DockerSwarmOperator will allow services to be created with `json-file` logging driver in order for logs to be retrieved and shown in the UI.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mr1holmes** [comment]
I would like to work on this.
Please assign it to me.

**Comment by geraj1010** [comment]
May I be assigned this issue @potiuk. This would be my first contribution.

**Comment by eladkal** [comment]
@geraj1010 assigned

**Comment by geraj1010** [comment]
Created PR https://github.com/apache/airflow/pull/41416
