### ISSUE TITLE
Airflow SFTPToS3Operator file exist check

### ISSUE THREAD

**Issue by gaurav7261** [apache/airflow#40576]
### Description

currently operator fail in case file not found on sftp,can we have one parameter for user to configure it like fail_on_file_not_exist ?

### Use case/motivation

this way, user will able to configure the parameter and operator will not fail in case of sftp file not exist

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gaurav7261** [comment]
@potiuk  is it fine ? can I  start work on this

**Comment by potiuk** [comment]
Sure. You do not need to ask for permission - just start - any meaningful discusion on it might happen when we see PR.

**Comment by Guaqamole** [comment]
I made fix to this issue. PR link: https://github.com/apache/airflow/pull/44320

**Comment by Guaqamole** [comment]
@potiuk could you review my PR for this issue? https://github.com/apache/airflow/pull/44320
