### ISSUE TITLE
Add support for `dag_stats` in REST API

### ISSUE THREAD

**Issue by reganbaum** [apache/airflow#40594]
### Description

1. Today, there is no REST API available to get the stats of a DAG (# success/failed/running/queued runs) via API. However, the UI uses an endpoint `dag_stats` to display this information. The goal is to have a REST API endpoint available that gets the DAG stats at `/api/v1/dag_stats`.
2. Moved over to https://github.com/apache/airflow/issues/40600

### Use case/motivation

I would like to programmatically (1) get the stats for all my DAGs and (2) programmatically stop a running workflow, which actually stops the execution (not just changes the state in the database).

### Related issues

https://github.com/apache/airflow/issues/40600

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
(1) - sure if someone implements it
(2) - impossible  until we change architecture (possibly might be doable in Airlfow 3 - I heartily invite you to subscribe to devlist discussions on that and take part in those discussions and advocate and possibly offer contributions to make it happen

**Comment by potiuk** [comment]
Marked it for (1) as "good first issue" and if someone would like to implement such endpoint. Also @reganbaum you are welcome to try it if you want to have it faster rather than wait for someone to pick it up and implement.

**Comment by reganbaum** [comment]
Thanks, Jarek. I moved the `dagrun_failed` issue (2) over to its own issue for easier tracking: https://github.com/apache/airflow/issues/40600

**Comment by dondaum** [comment]
Happy to take this over. Would be a good chance to get to know the Airflow REST API.

**Comment by potiuk** [comment]
Assigned you

**Comment by shubham22** [comment]
@dondaum - are you still working on this? Please let us know if there is anything we can help with. It would be best to have this shipped with v2.10 as the community's focus will be on Airflow 3 afterwards. cc: @ferruzzi

**Comment by dondaum** [comment]
Yeah I will finish it this week. Sorry I had some busy weeks.
