### ISSUE TITLE
MySQL table `dag_pickle` column `pickle` type `blob` not large enough for big DAGs

### ISSUE THREAD

**Issue by timeisapear** [apache/airflow#406]
Manually had to change column type from `blob` to `longblob` in MySQL `airflow.dag_pickle.pickle` to fit a large DAG when trying to execute a backfill using CeleryExecutor

**Comment by mistercrunch** [comment]
Did you just run an `ALTER` statement?

**Comment by timeisapear** [comment]
Yes. It seemed to do the trick.

**Comment by mtustin-handy** [comment]
FYI, you can now specify the core option `donot_pickle=True` to disable pickling, and instead pre-distribute your code.
