### ISSUE TITLE
No option for passing tags to EmrServerlessStartJobOperator

### ISSUE THREAD

**Issue by nivangio** [apache/airflow#40613]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.2.0

### Apache Airflow version

2.6.3

### Operating System

Mac/Ubuntu (doesn't matter really)

### Deployment

Official Apache Airflow Helm Chart

### What happened

EmrServerlessStartJobOperator does not provide the capability to pass tags, although it is supported by AWS.

### What you think should happen instead

EmrServerlessStartJobOperator should have the tags argument where you can pass tags in a dict in the  {"key": "value"} form

### How to reproduce

Does not apply, it is simply not there.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gyli** [comment]
`EmrServerlessStartJobOperator` accepts dict type argument `config`, and tags could be passed with it.

```
EmrServerlessStartJobOperator(..., config={"tags": {"key": "value"}})
```

**Comment by eladkal** [comment]
> `EmrServerlessStartJobOperator` accepts dict type argument `config`, and tags could be passed with it.
> 
> ```
> EmrServerlessStartJobOperator(..., config={"tags": {"key": "value"}})
> ```

Thanks for verifying.
closing this issue as resolved
