### ISSUE TITLE
Bad map_index in the log view of a mapped task

### ISSUE THREAD

**Issue by NBardelot** [apache/airflow#40655]
### Apache Airflow version

2.9.2

### What happened?

The URL built by the view has a "map_index" parameter value of -1, while the real value is 0+.

![screenshot](https://github.com/apache/airflow/assets/11333203/a937cb09-e273-4394-9fc7-4f3e454276a2)

The `redirect_to_external_log` function of `airflow/www/views.py` thus does not find the task instance and outputs an error in the Airflow UI: "Task [some task] does not exist".

Changing the map_index manually in the URL to the good value makes the link work properly.

### What you think should happen instead?

The URL computed by the view should be with the right map_index.

### How to reproduce

Have an external logging mechanism in place (we have ElasticSearch), and create mapped tasks. See that the log URL of those mapped tasks are wrong when those are instanciated.

### Operating System

Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by atomic77** [comment]
I was able to reproduce this locally for `example_dynamic_task_mapping` against v2.9.2; if no one else has spoken for this issue I would like to give it a try.

**Comment by potiuk** [comment]
Feel free.
