### ISSUE TITLE
Allow config a static ip for the pgbouncer clusterip service

### ISSUE THREAD

**Issue by fbertos** [apache/airflow#40676]
### Description

Would be interesting to be able of setting a specific internal IP address for the ClusterIP service of the pgbouncer through the Helm chart.

### Use case/motivation

Specify the IP of the pgbouncer related service through the values.yml

For instance:
.....
spec:
  type: ClusterIP
  **{{- if .Values.pgbouncer.service.ip }}
  clusterIP: {{- .Values.pgbouncer.service.ip }}
  {{- end }}**
  selector:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
  ports:
    - name: pgbouncer
      protocol: TCP
      port: {{ .Values.ports.pgbouncer }}
    - name: pgbouncer-metrics
      protocol: TCP
      port: {{ .Values.ports.pgbouncerScrape }}
.....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
feel free.

**Comment by alizademhdi** [comment]
Hello. I am interested in working on this issue. Can you assign this to me?

**Comment by fbertos** [comment]
No problem on my side but I am not sure I have enough privileges to assign this to you.
