### ISSUE TITLE
[2.9.1] "Task Tries"/Attempts UI is innaccessible

### ISSUE THREAD

**Issue by Rafnel** [apache/airflow#40673]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.1

### What happened?

My team upgraded from Airflow 2.6.3 to 2.9 a few months ago and one thing I can't find anymore is the "attempts" or "tries" UI. Previously, when you opened a DAG, there was a UI available (via the top of the page, see this old screenshot from 2.6.3: https://airflow.apache.org/docs/apache-airflow/2.6.3/ui.html#grid-view ) that allowed you to see the number of tries that each task took on each dagrun. It was a line graph, I believe. This was a helpful UI because some DAGs have tens of tasks and finding a task that took multiple attempts is opaque without clicking into each task individually.

I can't find this UI anymore, although I do believe I found a button to this UI which doesn't work anymore:
<img width="728" alt="Screenshot 2024-07-09 120317" src="https://github.com/apache/airflow/assets/18747511/2713d0ec-6866-4272-b46a-037f9ead990b">

This button links to /dags/DAG_NAME/tries, and when clicked, just takes you to /dags/DAG_NAME/grid, which indicates to me that the "tries" UI no longer exists.

After a bit of digging, I can't find a release notes that points to this UI being removed, although I might not be searching for the right keywords. Is this disappearance a bug? Or purposeful?

### What you think should happen instead?

When you hover over the "..." on a DAG in the Airflow homepage and click "Tries", it should take you to the "Tries" UI, which shows a graph of recent dagruns and how many attempts each task took on each dagrun.

### How to reproduce

1. Run Airflow 2.9.1 UI
2. Create example DAG
3. Hover over the horizontal "..." on the DAGs homepage
4. Click "Tries"
5. Observe that this takes you to the DAG grid UI, not the "/tries" UI.

### Operating System

Ubuntu 22.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-fab==1.0.2
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-ssh==3.10.1

### Deployment

Virtualenv installation

### Deployment details

Running Airflow Scheduler and UI "raw" on Ubuntu as systemd services.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Rafnel** [comment]
I think I found the change which removed this UI:

https://github.com/apache/airflow/pull/37988

`Task Tries -> Grid (this never made sense as a line chart, instead try_number is displayed in more places)`

I do agree that a line chart was unintuitive, but the actual info shown in this page was super helpful. For example, I have a DAG with ~30 TaskGroups, and each TaskGroup has ~10+ tasks. I have automatic retries configured on these tasks to help smooth over some application issues that we occasionally have. Sometimes, when debugging, I want to look at a specific DAG run and find which tasks took more than one attempt. It might just be 1 task out of hundreds which took more than 1 attempt. The old UI, although messy, allowed me to quickly find this one task so I could drill into its logs. Now, without this UI, is there a way to look at a DAG run and see which tasks took more than one attempt?

**Comment by tirkarthi** [comment]
Task instance try history has been added to gantt view as part of Airflow 2.10 . https://github.com/apache/airflow/pull/40304

**Comment by Rafnel** [comment]
Ah, perfect, I just looked at that issue and I believe adding the attempts to the gantt view will do exactly what I want. Thanks so much for pointing me to this issue.
