### ISSUE TITLE
TimeSensor change by default_timezone is not working

### ISSUE THREAD

**Issue by YiiTing** [apache/airflow#40679]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.0

### What happened?

When use the TimeSensor and set target_time in timezone, i expect it will stop after five minutes in current timezone, but it can't stop.

As settings below
instance: timedatectl set Asia/Taipei
airflow.cfg: default_timezone set Asia/Taipei

### What you think should happen instead?

Probably timezone.make_naive(timezone.utcnow(), self.dag.timezone).time() > self.target_time is not working

### How to reproduce

from airflow.decorators import dag
from airflow.sensors.time_sensor import TimeSensor
from airflow.timetables.trigger import CronTriggerTimetable
import datetime, pendulum, textwrap

@dag(
    dag_id="test_timesensor",
    schedule=CronTriggerTimetable("0 0 * * *", timezone="Asia/Taipei"),
    start_date=pendulum.datetime(2024, 1, 1),
    default_args={
        "owner": "test",
        "retries": 3,
        "retry_delay": datetime.timedelta(minutes=10),
        "do_xcom_push": False,
    },
    catchup=False
)
def generate_dag():

    delay_5m = TimeSensor(
        task_id="delay_5m",
        target_time=(pendulum.now("Asia/Taipei") + datetime.timedelta(minutes=5)).time(),
        poke_interval=datetime.timedelta(minutes=1),
        timeout=datetime.timedelta(minutes=30),
    )

generate_dag()

### Operating System

Ubuntu 22.04

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gyli** [comment]
Seems to be a bug indeed and I can reproduce the issue with same default timezone settings. I will see if I can make a fix.

As a temporary workaround, you can set tz in your dag start_date `start_date=pendulum.datetime(2024, 1, 1, tz='Asia/Taipei')`.

**Comment by YiiTing** [comment]
Thanks for your time.
I have tried it `start_date=pendulum.datetime(2024, 1, 1, tz='Asia/Taipei')`, and it succeeded.

But get another issue,
When set config **default_timezone** with 'Asia/Taipei', and can find DAG Details **timezone** in 'Asia/Taipei',
and DAG can't stop.

Do you have any ideas?
Thanks for your help.

**Comment by gyli** [comment]
I am not able to reproduce the DAG not stopping issue. If you see the pre task execution log, you will find log like `Checking if the time (05:20:27.524650) has come` and log time. It might provide more info whether the task is check the right time, and whether it did not stop even if the time passed.

**Comment by YiiTing** [comment]
Hello [gyli](https://github.com/gyli),

Here is code.
When don't set timezone in start_date, airflow.cfg set `default_timezone in 'Asia/Taipei'`, and can find timezone with 'Asia/Taipei' in DAG Details, but TimeSensor can't stop after two minutes.

```
from airflow.decorators import dag
from airflow.sensors.time_sensor import TimeSensor
from airflow.timetables.trigger import CronTriggerTimetable

import datetime, pendulum, textwrap


@dag(dag_id="example_dags",
     schedule=CronTriggerTimetable("0 0 * * *", timezone="Asia/Taipei"),
     start_date=pendulum.datetime(2024, 1, 1),
     default_args={
         'owner': "airflow",
         'retries': 3,
         'retry_delay': datetime.timedelta(minutes=10),
         'depends_on_past': False
     },
     catchup=False,
     tags=["example"])
def generate_dag():
    delay_2m = TimeSensor(
        task_id="delay_2m",
        target_time=(pendulum.now("Asia/Taipei") + datetime.timedelta(minutes=2)).time(),
        poke_interval=datetime.timedelta(minutes=1),
        timeout=datetime.timedelta(minutes=10))
    
    
generate_dag()
```

and here is ouput 
```
[2024-07-23, 09:51:44 CST] {local_task_job_runner.py:120}  Pre task execution logs
[2024-07-23, 09:51:44 CST] {time_sensor.py:48} INFO - Checking if the time (09:53:44.546664) has come
[2024-07-23, 09:52:44 CST] {time_sensor.py:48} INFO - Checking if the time (09:53:44.546664) has come
[2024-07-23, 09:53:44 CST] {time_sensor.py:48} INFO - Checking if the time (09:53:44.546664) has come
[2024-07-23, 09:54:45 CST] {time_sensor.py:48} INFO - Checking if the time (09:53:44.546664) has come
```

**Comment by gyli** [comment]
Timezone of start_date has higher priority than the default timezone of Airflow, when deciding the timezone of a DAG. As I posted above, `pendulum.datetime(2024, 1, 1)` comes with default tz UTC. To set start_date without timezone, you can use `datetime.datetime(2024, 1, 1)` with Python datetime module.

**Comment by YiiTing** [comment]
Hello [gyli](https://github.com/gyli),

I got it and it works.
Thanks for your help.
