### ISSUE TITLE
Configuration file not in effect

### ISSUE THREAD

**Issue by viitoare** [apache/airflow#40710]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.1

### What happened?

I am using the CeleryExecutor. When I set parallelism=300 only in airflow.cfg and do not add AIRFLOW__CORE__PARALLELISM in docker-compose.yaml, the value of self.parallelism printed in base_executor.py is 32. When I add AIRFLOW__CORE__PARALLELISM: 300 in docker-compose.yaml, the value of self.parallelism printed in base_executor.py is the configured 300.

### What you think should happen instead?

It should only take effect when I configure parallelism in airflow.cfg, rather than setting AIRFLOW_ CORE.PLALLELISM in Docker Compose.yaml for it to take effect

### How to reproduce

Only configure parallelism=300 in airflows.cfg, do not set AIRFLOW__CORE__PARALLELISM in docker-compose. yaml, and then print the value of self. parallelism in base_deecutor. py. You can see that the printed value is 32
![微信截图_20240710192422](https://github.com/apache/airflow/assets/130271253/5b396816-cc55-452b-8753-35f2908f34b4)
![微信截图_20240710192444](https://github.com/apache/airflow/assets/130271253/a3bab3cd-a4ab-4671-b94c-bad6a2a6d173)

### Operating System

Kylin Linux Advanced Server v10

### Versions of Apache Airflow Providers

2.9.1

### Deployment

Docker-Compose

### Deployment details

Celery Version 5.4.0
Docker Compose version v2.5.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
Could you please edit the content of "How to reproduce" section and translate it into English?

**Comment by viitoare** [comment]
> Could you please edit the content of "How to reproduce" section and translate it into English?

Sorry, it was my mistake and it has been corrected
