### ISSUE TITLE
Add a keytab field to the Spark connection (handle the base64 encoded text value as a credential).

### ISSUE THREAD

**Issue by seyoon-lim** [apache/airflow#40749]
### Description

Hello,

I would like to introduce and propose a feature I have personally implemented in the SparkSubmitHook for managing Spark connections.

This feature focuses on managing the Kerberos-related principal and keytab within the connection settings.

The basic idea is to store the keytab as a base64 encoded credential. When submitting a Spark job, the credential is decoded and saved as a file, and its path is specified during the submission.

![image](https://github.com/user-attachments/assets/1d242cd5-0484-4057-9159-4212862253ae)

### Use case/motivation

Setting up the keytab for each worker can be challenging, and managing the keytab each time it changes can be cumbersome. By storing this information within the connection, we can reduce the need to deploy the keytab every time.

I would appreciate your consideration of this proposal.

Thank you.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
If you already have the implementation it's best to simply open a PR so we can review the code and the suggestion

**Comment by seyoon-lim** [comment]
@eladkal 
Okay, I will make a PR soon.
Thank you!
