### ISSUE TITLE
xcom_pull doesn't show up in auto-generated docs

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#408]
This is minor, but I just noticed that `xcom_pull` doesn't show up in the docs (here is `xcom_push`, it should be right under it: http://airflow.readthedocs.org/en/latest/code.html#airflow.models.TaskInstance.xcom_push).

Could that be because the docstring is formatted (https://github.com/airbnb/airflow/blob/master/airflow/models.py#L1157)? If so, I can submit a version that isn't formatted.

**Comment by mistercrunch** [comment]
That would be my guess. Sphinx works in mysterious ways :)
