### ISSUE TITLE
Add links to example dags in use params section

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40811]
### Body

The https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html#use-params-to-provide-a-trigger-ui-form has 

> For examples also please take a look to two example DAGs provided: example_params_trigger_ui and example_params_ui_tutorial.

but there is no link to them. We should add link to these example dags.

Also, we should provide a paragraph that explain what makes a field required and how users can choose it.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by TreavVasu** [comment]
@eladkal should the required para include the info to set this to True only in a note?
![image](https://github.com/user-attachments/assets/87581514-4798-47e1-ab50-76122582ab34)

**Comment by amolsr** [comment]
The dags in the documentation - 

example_params_ui_tutorial - https://raw.githubusercontent.com/apache/airflow/main/airflow/example_dags/example_params_ui_tutorial.py

example_params_trigger_ui - https://raw.githubusercontent.com/apache/airflow/main/airflow/example_dags/example_params_trigger_ui.py

"Fields can be required or not. If the defined fields are typed they are getting required by default (else they would not pass JSON schema validation) - to make typed fields optional you must permit the optional "null" type."

I can do the changes please assign this to me. 

Thanks

**Comment by AChowdhury1211** [comment]
@amolsr If you are planning on opening a PR add a link to this line as well: 

> If you want to provide special formatting or links you need to use the Param attribute description_md. See tutorial DAG example_params_ui_tutorial for an example.

**Comment by AChowdhury1211** [comment]
I'm a bit confused if "example_params_ui_tutorial" is correct or not? <dag_name> instead seems more appropriate.
> To pre-populate values in the form when publishing a link to the trigger form you can call the trigger URL /dags/<dag_name>/trigger and add query parameter to the URL in the form name=value, for example /dags/example_params_ui_tutorial/trigger?required_field=some%20text.` To pre-define the run id of the DAG run, use the URL parameter run_id
