### ISSUE TITLE
Add a check in BigQueryInsertJobOperator to verify the Job state before marking it as success in Airflow

### ISSUE THREAD

**Issue by kandharvishnu** [apache/airflow#40839]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.12.0

### Apache Airflow version

2.7.3

### Operating System

debian

### Deployment

Astronomer

### What happened

When the [BigQueryInsertJobOperator](https://github.com/apache/airflow/blob/4298c433bc8b3136b8131ebe006dcf10c601e9c1/airflow/providers/google/cloud/operators/bigquery.py#L2654) submits a job to BigQuery, there are instances where the TaskInstance in Airflow is marked as success rarely before the Job actually completes in BigQuery.

When the `execute `method of a TaskInstance’s Operator completes without raising an exception, the TaskInstance is marked as `success`. Since these TaskInstances are being marked as `success`, it implies that the BigQueryInsertJobOperator’s `execute` method is completing without any exceptions. When [QueryJob.result](https://github.com/googleapis/python-bigquery/blob/49bfd124cc76a719acf9257610181612d1452e56/google/cloud/bigquery/job/query.py#L1463) returns something, allowing the `execute` method to finish.

### What you think should happen instead

Need to add an additional check [here](https://github.com/apache/airflow/blob/4298c433bc8b3136b8131ebe006dcf10c601e9c1/airflow/providers/google/cloud/operators/bigquery.py#L2866) to verify if the Job state is `DONE` in BigQuery, ensuring that Airflow only marks the TaskInstance as `success` when the job is indeed complete in BigQuery.

### How to reproduce

I haven't been able to replicate the issue. It happens infrequently.

### Anything else

There might be a bug in `google-cloud-bigquery==3.13.0` that causes the `QueryJob.result` method to return before the job is actually `DONE`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Worth noting that even though this is on an older version of the provider, there's no check in main to see whether the job completed in BigQuery. I _think_ this is probably a bug in `google-cloud-bigquery==3.13.0`, but it still might make sense to check whether the job is complete to avoid this situation completely.

**Comment by shahar1** [comment]
@kandharvishnu @pankajastro 

I'd like to have 3 requests:
1. Could you please decide on continuing the work in a single PR? I'd be happy if you guys could come to an agreement in good terms, it will make the reviewing work much easier :)
2. Could you please check if upgrading BigQuery's SDK solves the issue?*
3. Could you please raise an issue about it in [BigQuery's Python SDK repository](https://github.com/googleapis/python-bigquery)? (and if you're BigQuery users - it would be helpful to also raise a case about it via GCP's console)

\* @eladkal I agree with your [statement](https://github.com/apache/airflow/pull/44279#discussion_r1853912328) that we shouldn't work with permanent workarounds - however, would it suffice for now to implement one of the PRs while adding a link to this issue?

**Comment by pankajastro** [comment]
Hey @shahar1, Thank you for the review feedback I appreciate it. I have added my thoughts and also proposed some modified solutions which might help us in detecting future errors. Please do let me your thought. thank you! https://github.com/apache/airflow/pull/44279#discussion_r1862715519

**Comment by eladkal** [comment]
Closed by https://github.com/apache/airflow/pull/44279
