### ISSUE TITLE
Support DEBUG logging by component

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#40840]
### Description

Currently, users can only enable debug logging across all Airflow components. So, if you want to enable debug logging in the worker or triggerer, you have to also enable debug logging in the scheduler, which produces a ton of noise and writes a ton of data to disk.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jedcunningham** [comment]
I do this fairly regularly already with an env var override for the config. `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG airflow scheduler` for example. Is that not sufficient? I feel like getting more granular for the config is a slippery slope - not _that_ worker, just this one, or not _that_ KE task, just this one type thing.
