### ISSUE TITLE
SnowflakeSqlApiOperator's Snowflake Legacy Url Authentication Issue

### ISSUE THREAD

**Issue by shubham-arora-18** [apache/airflow#40885]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.5.1

### What happened?

I have been facing an issue with GCP airflow.

-   Version of composer: composer-2.3.3
-   Version of airflow: airflow-2.5.1
-   Version of apache-airflow-providers-snowflake package: 5.1.2

Issue is:

1. The normal SnowflakeOperator(`airflow.providers.snowflake.operators.snowflake.SnowflakeOperator`) internally uses correct url for snowflake authentication (`https://<orgname>-<account_name>.[snowflakecomputing.com](http://snowflakecomputing.com/`).
2. But SnowflakeSqlApiOperator (`airflow.providers.snowflake.operators.snowflake.SnowflakeSqlApiOperator`) uses legacy url for snowflake authentication(`https://<accountlocator>.<region>.<cloud>.[snowflakecomputing.com](http://snowflakecomputing.com/`).
3. The use of legacy url is discouraged and support for the same will end soon, we confirmed this from snowflake.
4. I looked at the change log between 5.1.2 version to the latest version(5.6.0) but no log suggests this has been taken care of.

Related Links:
Apache Airflow Snowflake package documentation: [Link](https://airflow.apache.org/docs/apache-airflow-providers-snowflake/5.1.2/_api/airflow/providers/snowflake/operators/snowflake/index.html#module-airflow.providers.snowflake.operators.snowflake)
Snowflake documentation for authentication: [Link](https://docs.snowflake.com/en/user-guide/organizations-connect)

### What you think should happen instead?

The SnowflakeSqlApiOperator should use the same url for snowflake authentication as the SnowflakeOperator.

### How to reproduce

Try running a query with SnowflakeSqlApiOperator on your snowflake instance.

### Operating System

mac

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
The Cloud Composer, AIrflow and snowflake versions seem outdated - have you tried upgrading to latest?

**Comment by shubham-arora-18** [comment]
> The Cloud Composer, AIrflow and snowflake versions seem outdated - have you tried upgrading each to the latest?

Updating composer is a taxing task. No point in upgrading the composer unless the issue has been resolved in the latest apache snowflake library. I don't see any such change in the changelog.

Please correct me if wrong.

**Comment by shubham-arora-18** [comment]
Yes, I just checked it and it is fixed. Closing the issue, thanks.
