### ISSUE TITLE
Cluster Activity Tab are missing after upgrade from 2.6.3 to 2.7.3 and even after upgrade to 2.8.4 

### ISSUE THREAD

**Issue by dannyeuu** [apache/airflow#40941]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.4

### What happened?

After upgrade from 2.6.3 to 2.7.3 and even after upgrade to 2.8.4 the feature Cluster Activity does not appear on resources page:
![Screenshot from 2024-07-22 16-12-35](https://github.com/user-attachments/assets/5e274e5d-75ef-4d64-9e75-a6eeac69ad61)

### How to reproduce

Install version 2.6.3 on Kubernetes and upgrade to 2.7.3

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.19.0
apache-airflow-providers-apache-hive==7.0.1
apache-airflow-providers-apache-spark==4.7.1
apache-airflow-providers-cncf-kubernetes==8.0.1
apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-elasticsearch==5.3.3
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-google==10.16.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-microsoft-azure==9.0.1
apache-airflow-providers-mongo==4.0.0
apache-airflow-providers-mysql==5.5.4
apache-airflow-providers-odbc==4.4.1
apache-airflow-providers-oracle==3.9.2
apache-airflow-providers-postgres==5.10.2
apache-airflow-providers-sftp==4.9.0
apache-airflow-providers-slack==8.6.1
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-ssh==3.10.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by brow1998** [comment]
Same hapened here!

**Comment by mlaurawanderley** [comment]
Here too... did anyone manage to solve it?

**Comment by eladkal** [comment]
I am not able to reproduce.
Can someone suggest a way to reproduce this issue?
