### ISSUE TITLE
Add an FTP hook

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#41]
Do you have plans to support FTP hooks?

I've noticed there's an FTP connection type in the front-end, but I've not found a component to utilise the connection. Is this a case of me extending BaseHook to wrap some functionality to pull and push files via FTP or is there something existing that I've missed?

**Comment by mistercrunch** [comment]
I think the frontend ftp reference is an artifact of early development, thinking that a FtpHook would appear early on. But it turns that with HDFS and S3 around we don't have use cases for FTP internally at this point.

This means that if you need FTP support you'll have to write a hook or wait for the community to come up with one. It should be very easy to derive BaseHook and implement just the methods that you need. I'm assuming you also need some sort of data transfer operator to send to FTP or load from FTP. You'd have to build those operators as well.

Note that you can always use a `PythonOperator` to do anything you'd do in a python function.

I'll happily review FTP related PRs if you want to contribute to our portfolio of hooks and operators!

**Comment by martingrayson** [comment]
Brilliant, thanks! I may well implement a hook if I get time. I will probably hack my process to use shell commands to implement something quickly and come back to the correct way when I get time.

**Comment by shamsulbuddy** [comment]
@martingrayson  , Have you got any success with FTP hooks . I have some similar problem https://github.com/airbnb/airflow/issues/399

**Comment by martingrayson** [comment]
I wrote a really basic hook but there are no unit tests and I never got around to actually using it in anger.

**Comment by sc250072** [comment]
## Fixed 3 Latest Copilot Comments

### Comment 1 (test_bearer.py:110): Missing blank line between methods
✅ **Fixed:** Added blank line between test_validate_missing_jws_private_key() and test_validate_invalid_logmech() for PEP 8 compliance.

### Comment 2 (test_teradata.py:289): Missing validation assertion  
✅ **Fixed:** Added `assert mock_validate_file.called` to verify validate_config() is called during Bearer setup.

### Comment 3 (teradata.rst:259): Misleading wording on required fields
✅ **Fixed:** Updated documentation to clarify that Bearer oidc_clientid and jws_cert are optional while jws_private_key is required.
