### ISSUE TITLE
DAG-level authorization via Keycloak using DAGs prefix

### ISSUE THREAD

**Issue by vegaskyo** [apache/airflow#41038]
### Description

While the integration for general authentication works seamlessly, I've noticed that Airflow currently does not support authorization at the DAGs level via Keycloak.

### Use case/motivation

In many production environments, different teams or users need to access to specifics DAGs while being restricted from others. Implementing DAGs level authorization would greatly enhance security and manageability in such scenarios. Leveraging DAGs prefixes, such as "testers_*", to assign permissions to user groups would provide a flexible and efficient solution. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
this is being disussed in https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-79+Replace+Flask+App+Builder - AIP that is targetted for Airlfow 3  and is part of the mutli-team approach for Airflow 3  https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-67+Multi-team+deployment+of+Airflow+components. 

We are looking for volunteer who would like to take on the task and implement KeyCloak Auth Manger with similar functionality, so if you would like to help and contribute generic KeyCloak Auth Manager - feel free.

Closing as duplicate.
