### ISSUE TITLE
Wrong MRO in operators without `__init__`

### ISSUE THREAD

**Issue by grihabor** [apache/airflow#41085]
### Apache Airflow version

2.9.3

### What happened?

Wrong MRO leads to an exception when subclassing `BaseSQLOperator` and `BranchSQLOperator`, see below

### How to reproduce

```python
from airflow.providers.common.sql.operators import sql

class Mixin(sql.BaseSQLOperator):
    pass

class Branch(Mixin, sql.BranchSQLOperator):
    pass

Branch(task_id='test', conn_id='abc', follow_task_ids_if_true='x', follow_task_ids_if_false='y')
```
Output:
```
AirflowException: Invalid arguments were passed to Branch (task_id: test). Invalid arguments were:
**kwargs: {'follow_task_ids_if_true': 'x', 'follow_task_ids_if_false': 'y'}
```

### Operating System

Ubuntu 22.04

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
Thanks for filing this issue. I just verified this can be reproduced in the latest  main (a7b0dc25c0201e3e69726aa6033102128d8d9046)
