### ISSUE TITLE
Celery produces incorrect external logs while task is running: 'Task Instance State' FAILED: Task is in the 'running' state.

### ISSUE THREAD

**Issue by internetcoffeephone** [apache/airflow#41123]
### Apache Airflow Provider(s)

celery

### Versions of Apache Airflow Providers

celery[sqs]==5.4.0

### Apache Airflow version

2.9.2

### Operating System

NAME="Amazon Linux" VERSION="2" ID="amzn"

### Deployment

Other Docker-based deployment

### Deployment details

Four separate Airflow containers deployed on AWS ECS Fargate, split into a webserver, scheduler, triggerer and celery worker. These each start with their respective `airflow webserver`, `airflow scheduler` etc. commands. These are linked together with an Elastic EFS volume to share a repo with DAGs and other code. The EFS volume is never near throughput capacity, which seems to be causing [similar errors](https://stackoverflow.com/q/56878366) for others.

### What happened

Prior to deploying on AWS ECS Fargate, we ran Airflow on EC2. Since the migration however, worker logs are inconsistently appearing in the Airflow web console.

When starting, a task will correctly show the following log:
`*** No logs found on s3 for ti=<TaskInstance: test_dag.check_basics scheduled__2024-07-28T00:00:00+00:00 [queued]>
`
The task will continue to execute correctly and the log will start populating correctly. However, not long after (5-120 seconds), either on auto or manual page refresh, a different message appears:

```
{AWS IP}
*** Found logs in s3:
***   * s3://company_name-datalake-airflow-logs-prod/airflow-main/dag_id=test_dag/run_id=scheduled__2024-07-28T00:00:00+00:00/task_id=test_dag.check_basics/attempt=1.log
[2024-07-30, 12:54:47 CEST] {{local_task_job_runner.py:120}} ▼ Pre task execution logs
[2024-07-30, 12:54:47 CEST] {{taskinstance.py:2067}} INFO - Dependencies not met for <TaskInstance: test_dag.check_basics scheduled__2024-07-29T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-07-30, 12:54:47 CEST] {{taskinstance.py:2067}} INFO - Dependencies not met for <TaskInstance: test_dag.check_basics scheduled__2024-07-29T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-07-30, 12:54:47 CEST] {{local_task_job_runner.py:163}} INFO - Task is not able to be run
```

Sometimes line 3 and 4 (the lines with FAILED) are repeated once.
In the background, the task is correctly running however.

Once the task completes, the log is written to S3 again in one of the following 3 forms:

1. The extra error log vanishes entirely and is replaced by the correct log
2. The extra error log is prepended to the correct log
3. The extra error log is appended to the correct log
4. The extra error log is prepended to a log that starts with: `[2024-07-30, 10:02:07 CEST] {{taskinstance.py:1207}} INFO - Marking task as SUCCESS...`, but the first part of the correct log is missing

In all of these 4 cases the task has completed successfully.

### What you think should happen instead

The logs should be retrieved correctly from the Airflow worker to the Airflow webserver, even while the task is still running. There shouldn't be logs in S3 which say `'Task Instance State' FAILED: Task is in the 'running' state.` The final S3 log should not contain these lines at all.

### How to reproduce

Given the complexity of this setup, this is unfortunately not trivial to reproduce. You would need to deploy 4 containers to AWS ECS Fargate, link them together with an Elastic shared EFS volume, set up an SQS queue and postgresql database backend.

I'm at my wit's end here, and would like some help into making this reproducible, because the above instructions are obviously insufficient.

### Anything else

I have looked into many similar issues, and none seem to be this exact issue.
In https://github.com/apache/airflow/pull/31829, the error message is identical but that pertains to long-running tasks. This is not the case here. The tasks here are not long-running and the error appears within seconds/minutes.
Our `task_acks_late=True` and timeout settings are sufficiently high.
```
(airflow_env) airflow@xxxxxxx:/usr/local/airflow airflow config list | grep timeout
...
visibility_timeout = 21600
```

I have tried setting AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION to False.

The database and SQS connection strings are all correct, as are the secret webserver/worker keys. I can see connections and messages between them. What I suspect is happening here is that Celery tries to pick up a task for the second time, fails, then writes a log to S3. Because a log is found in S3 by the Airflow webserver, it then never even checks the Airflow worker for logs.

The problem occurs on every single DAG in our environment.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by EvertonSA** [comment]
it seems to me task_acks_late=True invalidates whatever you have on visibility_timeout

**Comment by internetcoffeephone** [comment]
@EvertonSA You are right, I included these for completeness.

I found another clue: the second (erroneous) execution of the task always happens ~30 seconds later, never off by more than 1 second.
E.g.
```
[2024-08-13, 03:55:37 CEST] {{taskinstance.py:2077}} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.check_basics scheduled__2024-08-12T00:00:00+00:00 [queued]>
...
[2024-08-13, 03:56:06 CEST] {{taskinstance.py:2067}} INFO - Dependencies not met for <TaskInstance: test_dag.check_basics scheduled__2024-08-12T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
```

This gives us a clue as to which config settings may be relevant here, but the only relevant one I was able to find was: `min_serialized_dag_update_interval = 30`

I lack understanding of the interaction between Airflow/Celery to know where exactly I need to look - either Airflow is 
scheduling or picking up tasks that it shouldn't, or Celery is not correctly communicating running task state. Any pointers on where in the Airflow code this process happens would be appreciated.

**Comment by internetcoffeephone** [comment]
I solved the problem.

The issue was that AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__VISIBILITY_TIMEOUT was set to a higher value than the actual [visibility timeout](https://registry.terraform.io/providers/hashicorp/aws/5.54.1/docs/resources/sqs_queue#visibility_timeout_seconds) set in the AWS SQS server.

Making those values equal completely resolved the issue.
