### ISSUE TITLE
Unable to fetch logs from amazon s3

### ISSUE THREAD

**Issue by KanaSukita** [apache/airflow#41171]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.2

### What happened?

I have configured the airflow.cfg file and make sure the the Celery worker logs are stored in both the worker instance and the Amazon S3.

The logs in S3 are stored in s3://${BUCKET_NAME}/airflow_logs/dag_id=xxxx/run_id=scheduled__2024-07-30T03:20:00+00:00/task_id=xxxx/，and logs saved in the worker instance with path ${AIRFLOW_HOME}/logs/dag_id=xxxx/run_id=scheduled__2024-07-30T03:20:00+00:00/task_id=xxxx/

When I check the Airflow UI for task retrieval, it cannot retrieve the logs from S3, but it can retrieve the logs from the worker instance. Logs are as below:

```
ip-10-121-129-159.eu-west-1.compute.internal
*** No logs found on s3 for ti=<TaskInstance: logstash_alice_etl.convert_euw1 scheduled__2024-07-30T03:20:00+00:00 [success]>
*** Found logs served from host http://ip-10-121-129-159.eu-west-1.compute.internal:8793/log/dag_id=xxxx/run_id=scheduled__2024-07-30T03:20:00+00:00/task_id=xxxx/attempt=4.log
[2024-08-01, 07:29:55 UTC] {local_task_job_runner.py:120} ▶ Pre task execution logs
[2024-08-01, 07:30:03 UTC] {subprocess.py:63} INFO - Tmp dir root location: /tmp
...
```

### What you think should happen instead?

The logs should be found in S3 instead of the worker instance

### How to reproduce

configure the [logging] parts in airflow.cfg with the below modifications:

base_log_folder = /opt/apache/airflow/logs
remote_logging = True
remote_log_conn_id = aws_airflow_euw1                  # Just an IAM connection to S3 in eu-west-1
remote_base_log_folder = s3://${BUCKET_NAME}/airflow_logs

### Operating System

Amazon Linux 2023

### Versions of Apache Airflow Providers

airflow 2.9.2

### Deployment

Virtualenv installation

### Deployment details

Deploy in Amazon Linux 2023 with default python environment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by burito111** [comment]
Hi, I can confirm similar issue with the same version 2.9.2 and MWAA on AWS. I get following information when going into task logs.

*** Unable to read remote logs from Cloudwatch (log_group: airflow-airflow-Task, log_stream: dag_id=pineapple/run_id=manual__2024-08-02T19_16_42.903450+00_00/task_id=training_model_C/attempt=1.log)
*** An error occurred (ResourceNotFoundException) when calling the GetLogEvents operation: The specified log stream does not exist.

*** Could not read served logs: Request URL is missing an 'http://'/ or 'https://'/ protocol.

**Comment by eladkal** [comment]
cc @vincbeck @o-nikolas you might want to look into this one

**Comment by vincbeck** [comment]
I tested it using the same configuration with breeze (against main and against Airflow 2.9.2) and it works properly. @KanaSukita, @burito111, did it stop working when you upgraded Airflow? Amazon provider package? What triggered the logs to stop working?

**Comment by shubham22** [comment]
@burito111 MWAA does not support S3 for logs, so this is expected behavior.

**Comment by eladkal** [comment]
Closing as not Airflow issue.

If further assistance required on this please contact MWAA support.
