### ISSUE TITLE
Allow uploading a new model version to Google Cloud Vertex AI Model Registry using the `UploadModelOperator`

### ISSUE THREAD

**Issue by GLaDAP** [apache/airflow#41194]
### Description

Using Vertex AI, it is possible to upload a model as a new version of an existing model. This is possible by passing the `parent_model` to the `UploadModelRequest`. However, the `ModelServiceHook.upload_model` (under `airflow.providers.google.cloud.hooks.vertex_ai.model_service.py`) does not allow a user to pass the `parent_model`.

Currently, when a new model is uploaded, a new model is created instead of creating a new version on an already existing model.

### Use case/motivation

Adding this feature enables users to use the[ model versioning](https://cloud.google.com/vertex-ai/docs/model-registry/versioning) functionality in Vertex AI.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
cc: @VladaZakharova , @e-galan

**Comment by jx2lee** [comment]
Can i take this? 👀

**Comment by VladaZakharova** [comment]
> Can i take this? 👀 If possible, please assign this issue to me. (it will be done until day after tomorrow)

sure, thank you :)
