### ISSUE TITLE
Support for SLAs on Dataset driven DAGs

### ISSUE THREAD

**Issue by samuhepp** [apache/airflow#41195]
### Description

It looks like SLA miss callbacks are only really supported on scheduled DAGs which is problematic moving to Datasets.

### Use case/motivation

It would still be useful to alert on tasks that are taking longer than expected

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
Duplicate of #38099 - this feature request should be implemented a part of a greater [Airflow purposal](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-57+Refactor+SLA+Feature).
