### ISSUE TITLE
TriggerDagRunOperator doesn't allow empty failed_states

### ISSUE THREAD

**Issue by zhijie-dv01** [apache/airflow#41229]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

In some cases, our company need to mark TriggerDagRunOperator as Success even if the triggered DAG failed. 
But TriggerDagRunOperator doesn't allow that. When I set failed_states to be an empty list, the following code will always add "failed" to failed_states
https://github.com/apache/airflow/blob/e3525cf4aa13dccc8c8b04603eef9f9692818a3b/airflow/operators/trigger_dagrun.py#L153

### What you think should happen instead?

It should be like this:
```
        if failed_states or failed_states == []:
            self.failed_states = [DagRunState(s) for s in failed_states]
        else:
            self.failed_states = [DagRunState.FAILED]
```

### How to reproduce

Try the setting as follows, and let the triggered dag failed.
```
TriggerDagRunOperator(
            task_id='abc',
            trigger_dag_id=dag_id,
            execution_date='{{execution_date}}',
            wait_for_completion=True,
            poke_interval=60 * 30,  # 30 mins
            allowed_states=[State.SUCCESS, State.FAILED],
            failed_states=[],
            deferrable=True,
        )
```

### Operating System

linux

### Versions of Apache Airflow Providers

airflow 2.7.3/ Cloud composer 2.8.1

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
Why you would like to pass it empty list?
Passing `None` will solve your problem.

**Comment by zhijie-dv01** [comment]
> Why you would like to pass it empty list? Passing `None` will solve your problem.

@romsharon98  In the if else condition, passing None will still go to "else" and then add DagRunState.FAILED to failed_states

**Comment by phi-friday** [comment]
Until this issue is resolved,
You might want to try using `post_execute` or `on_execute_callback` or `on_failure_callback`.
Maybe that will help.

**Comment by zhijie-dv01** [comment]
@romsharon98 @hussein-awala  I’m unsure about the collaboration process here. I indicated my willingness to submit a PR and proposed a solution, yet my idea was used to raise a PR by someone else. Could future opportunities be left for new contributors like myself?

**Comment by potiuk** [comment]
> @romsharon98 @hussein-awala I’m unsure about the collaboration process here. I indicated my willingness to submit a PR and proposed a solution, yet my idea was used to raise a PR by someone else. Could future opportunities be left for new contributors like myself?

Happens. You need to allow for some room of uncertainty and overlap. Sometimes two people will work on the same things. Sometimes people will say they work on something - but they don't. This is life happening. You can try to prevent this from happening and put a guard on every step or you allow for imperfectness and occasional mishups.

Accept the imperfectness. Done is better than perfect. There are plenty of things to work, and there is also a saying that copying is the best flatter you can have - also actually when your idea is done by someone else is  THE BEST THING EVER. You sparked the idea, someone else did it. Your idea got implemented and you spent 0 time on it, and can come with few more ideas in this time. The overall community effect of it is hugely positive,
