### ISSUE TITLE
Moto 5.0.12 breaks amazon provider's RDS tests

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#41243]
### Body

The **just released** moto `5.0.12` breaks tests for AWS RDS 

https://github.com/apache/airflow/actions/runs/10230423335/job/28305276935#step:7:919

The way to reproduce it:

* Enter breeze `breeze` (you get latest constraints dependencies there)
* Run the test `pytest tests/providers/amazon/aws/sensors/test_rds.py::TestRdsExportTaskExistenceSensor::test_export_task_poke_false`
* It succeeds
* Upgrade moto to latest version `pip install --upgrade moto`:

```
Installing collected packages: moto
  Attempting uninstall: moto
    Found existing installation: moto 5.0.11
    Uninstalling moto-5.0.11:
      Successfully uninstalled moto-5.0.11
Successfully installed moto-5.0.12
```
* run the same test again

Fails with 

```
  raise error_class(parsed_response, operation_name)
E           botocore.errorfactory.ExportTaskNotFoundFault: An error occurred (ExportTaskNotFound) when calling the DescribeExportTasks operation: Cannot cancel export task because a task with the identifier my-db-instance-snap-export is not exist.
```

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vikramaditya91** [comment]
The reason for the failure is
https://github.com/getmoto/moto/pull/7861

specifically the 
```patch
+            "ExportTaskNotFound",
-            "ExportTaskNotFoundFault",
 ```
 
 in the `ExportTaskNotFoundError`
