### ISSUE TITLE
wrong display of multiline messages in the log after filtering by message level

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#41265]
### Apache Airflow version

2.9.3

### What happened?

Problem displaying an error in the tab Logs in the task detail.

If the error text in the log is on multiple lines, it is displayed correctly in the basic view without filtering (see the picture)
![image](https://github.com/user-attachments/assets/d9827e7e-7dbe-4d88-98af-f82598cf8c58)

But if I use filter by message level (e.g. error, see the pict) , then only the first line of the same error message is displayed. The information on the other lines for this error message is not visible (see the picture)
![image](https://github.com/user-attachments/assets/00813f80-8744-41dd-b7d0-28c6c738f4c5)

### What you think should happen instead?

A multi-line message should be displayed in its entirety even after applying the message level filter

### How to reproduce

Display a multi-line message (typically an error message) in the task log and then apply a filter to the ERROR level

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Pad71** [comment]
the same problem with displaying multiline message is also when filtering to other levels (e.g. INFO etc.)

**Comment by Lee-W** [comment]
Thanks for reporting this. I just verified this happens in the latest main ([45658a8963761ce8a565b481156c847e493fce67](https://github.com/apache/airflow/tree/45658a8963761ce8a565b481156c847e493fce67))

**Comment by Lee-W** [comment]
cc @bbovenzi

**Comment by bbovenzi** [comment]
Talking with Ash about his TaskSDK work. Logs will be sent to the UI in json format so we won't need all of this regex string processing to try to add features to logs. But this is important enough to fix for 2.10.x or 2.11

**Comment by jason810496** [comment]
Hi @Lee-W, I could try resolve this issue, could you assign to me, thanks !

**Comment by Lee-W** [comment]
> Hi @Lee-W, I could try resolve this issue, could you assign to me, thanks !

Definitely, just assigned it to you 🙂

**Comment by Lee-W** [comment]
Sure. Thanks for reminding me 🙂  Next time, you can mention `close: #pr-number` in your pr, and it'll automatically close the issue
