### ISSUE TITLE
Scheduled DAGs with cron expression

### ISSUE THREAD

**Issue by galmeida-hedgepoint** [apache/airflow#41270]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.2

### What happened?

DAGs scheduled with cron expression that contains specifc day of week defined are not running at the scheduled time.

DAGs scheduled with the cron expression examples below don't work:
`0 17 * * 1`
`0 17 * * 1-2`
`0 17 * * 1-6`
`0 17 * * mon`
`0 17 * * MON`

DAGs scheduled with the cron expression example below work fine:
`0 17 * * *`

### How to reproduce

Create a DAG with `schedule` or `schedule_interval` with specifc day of week defined in cron expression, example: `schedule="0 17 * * 1"`

### Operating System

Amazon Linux / Amazon MWAA

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.24.0
apache-airflow-providers-slack==8.7.1
apache-airflow-providers-pagerduty==3.7.1

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Can you please add a sample dag to reproduce this locally? By don't work do you mean the dag is triggered on incorrect dates or not triggered at all?

I tried a dag with schedule as `0 17 * * 1-2` and it renders the planned dates as expected in calendar with next dagrun also being calculated correctly.

Sample dag

```python
from datetime import datetime, timedelta

from airflow import DAG
from airflow.decorators import task

with DAG(
    dag_id="error_color",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    schedule_interval="0 17 * * 1-2",
) as dag:

    @task
    def empty():
        pass


    empty()
```

![image](https://github.com/user-attachments/assets/7eb846be-ffe8-4fa2-9ea0-8f7ed813ec85)

**Comment by galmeida-hedgepoint** [comment]
The dag is **not**  triggered at all

**Comment by tirkarthi** [comment]
This could be an issue due to start_date being dynamic. It's strongly recommended to use a static start_date.

https://forum.astronomer.io/t/airflow-start-date-concepts/393
https://stackoverflow.com/questions/41134524/why-is-it-recommended-against-using-a-dynamic-start-date-in-airflow
https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date

**Comment by galmeida-hedgepoint** [comment]
I have just tested and now it is working perfectly! Thank you

![image](https://github.com/user-attachments/assets/751f54ee-4006-4f66-8fe1-563467ec4fc9)
