### ISSUE TITLE
taskflow does not understand * (argument unpack operator): ValueError: The key 'how' in args is a part of kwargs and therefore reserved.

### ISSUE THREAD

**Issue by jabbera** [apache/airflow#41286]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.2

### What happened?

Executing the attached repro in airflow results in a runtime error 

ValueError: The key 'how' in args is a part of kwargs and therefore reserved.

### What you think should happen instead?

This dag should execute properly

### How to reproduce

```
from airflow.decorators import dag, task
@dag(
    schedule=None,
    catchup=False,
    tags=["example"],
)
def demo_bug():
    @task()
    def input1() -> str:
        return "A"
    
    @task()
    def input2() -> str:
        return "B"
    
    @task()
    def bug(*str, how="cow"):
        pass

    bug(input1, input2, how="now")

demo_bug()
```

### Operating System

Ubuntu 22.04.4 LTS

### Versions of Apache Airflow Providers

None relevant

### Deployment

Virtualenv installation

### Deployment details

Nothing of note

### Anything else?

All the time

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by atomic77** [comment]
I've got this reproduced locally against `main` and would like to give it a try.

**Comment by jabbera** [comment]
> I've got this reproduced locally against `main` and would like to give it a try.

I gave it a try. Never committed to airflow before so it's a shot in the dark.

**Comment by atomic77** [comment]
> I gave it a try. Never committed to airflow before so it's a shot in the dark.

Oh no worries - I was looking around for something to fix and saw the `Yes I am willing to submit a PR!` box unchecked so thought you were just reporting the issue.
