### ISSUE TITLE
Airflow REST GET API call for TaskInstances returns unordered items, making paged retrieval impossible

### ISSUE THREAD

**Issue by DFINITYManu** [apache/airflow#41283]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.1, but nothing in the release notes thereafter indicates this issue has been fixed.

### What happened?

When using paged retrieval:

```
https://airflow/api/v1/dags/DAG/dagRuns/rc--2024-08-02_01-30/taskInstances?limit=100&offset=0
https://airflow/api/v1/dags/DAG/dagRuns/rc--2024-08-02_01-30/taskInstances?limit=100&offset=100
https://airflow/api/v1/dags/DAG/dagRuns/rc--2024-08-02_01-30/taskInstances?limit=100&offset=200
```

the task instance results are unordered, ensuring with near certainty that all subsequent paged retrievals (with offset > 0) return some tasks already returned before, and fail to return tasks that should have been in the page.  Thus, concatenating the tasks yields the correct *number* of tasks, but some are repeated and some are missing.

Full retrieval as per

```
https://airflow/api/v1/dags/DAG/dagRuns/rc--2024-08-02_01-30/taskInstances?limit=300
```

returns each task instance only once, and returns all task instances exhaustively.

### What you think should happen instead?

Task instances from API call should either be returned in some specific order, or there should be a query string parameter allowing us users to specify a designated order (such as task instance creation / appearance date).

### How to reproduce

Just issue a taskInstances GET call with a small limit, then with an offset equivalent to the small limit.  Tasks that were on the first batch are likely to appear on the second batch too.

### Operating System

Ubuntu 22.04 container

### Versions of Apache Airflow Providers

Not relevant.

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

We use a very vanilla Kubernetes.

### Anything else?

Always.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

I cannot, but I can recommend the following: all REST endpoints that list items in a paged manner must return items in a stable sort order, or at least allow the end user to specify a stable sort order criteria and document that unordered items are returned by default.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by omkar-foss** [comment]
I'm looking into this, will raise a PR in a while.

**Comment by omkar-foss** [comment]
@DFINITYManu I've raised #41307 which should be able to resolve your above mentioned issue. Hoping it'll be useful.

As a sidenote - while looking into this, I came across some other GET endpoints where `order_by` query param can be added, I'll raise separate issues and PRs for those incrementally.
