### ISSUE TITLE
SparkSubmitHook requires yarn binary

### ISSUE THREAD

**Issue by EugeneMSOff** [apache/airflow#41324]
### Apache Airflow Provider(s)

apache-spark

### Versions of Apache Airflow Providers

4.9.0

### Apache Airflow version

2.9.3

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### What happened

I try to use spark submit with --master yarn --deploy-mode cluster parameters.
And I wanna to kill application on cluster when I terminate SparkSubmitOperator.

SparkSubmitHook has a on_kill() method, which run `yarn application -kill`  command:
https://github.com/apache/airflow/blob/45658a8963761ce8a565b481156c847e493fce67/airflow/providers/apache/spark/hooks/spark_submit.py#L709
But it's not worked, because of no such binary in the PATH (`yarn`).
My Airflow instance run on host, without hadoop installation.

In the hook docstring only `spark-submit`  mentioned as required, no word about `yarn`
https://github.com/apache/airflow/blob/45658a8963761ce8a565b481156c847e493fce67/airflow/providers/apache/spark/hooks/spark_submit.py#L42

### What you think should happen instead

As an option, change the state of application with rest api
https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html

### How to reproduce

Use Spark connection type with deploy mode `cluster` and host 'yarn' fields.
Run  SparkSubmitOperator and mark state as "failed".

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunank200** [comment]
@EugeneMSOff Is the YARN binary available in the PATH of your Airflow instance? It seems that the YARN binary may not be available in your current environment, which could be the reason you're unable to kill Spark applications on the YARN cluster using the `on_kill()` method. Would you like to attempt installing the YARN binary in your Docker setup and try again?

If you wish, you can create a PR to clarify that when YARN is used as the cluster manager (i.e., when --master yarn is specified), the YARN binary must be available in the PATH of the Airflow instance. This is necessary for operations such as killing YARN applications via the `on_kill()` method in `SparkSubmitHook`.

Alternatively, we could consider adding a new feature, using the YARN ResourceManager REST API to manage the application state (e.g., killing), if the YARN binary is unavailable.

**Comment by EugeneMSOff** [comment]
@sunank200 first of all, thanks for your attention.

As I said, such binary is not in PATH of my Airflow instance.
`yarn` tool is provided by `hadoop` installation.
If I just copy it to Airflow instance, it won't be enough
