### ISSUE TITLE
Missing dependency `methodtools` when using `microsoft-mssql==3.8.0` with `airflow==2.7.3`

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#41330]
### Apache Airflow version

main (development)

### What happened?

[apache-airflow-providers-microsoft-mssql ](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/3.8.0/index.html#requirements) documentation mentions that it  3.8.0 supports airflow>2.7.0.  But, it causes the following import error.

```
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 26, in <module>
    from methodtools import lru_cache
ModuleNotFoundError: No module named 'methodtools'
```

### What you think should happen instead?

`methodtools` is not part of the requirements in Airflow 2.7.3.  Documentation should be updated for apache-airflow-providers-microsoft-mssql to show the compatible Airflow version.

### How to reproduce

Use apache-airflow-providers-microsoft-mssql==3.8.0 along with airflow==2.7.3. Then, try to import  `from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook`

### Operating System

ubuntu-22.04

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Indeed
