### ISSUE TITLE
Add a CoalesceOperator to Airflow Providers

### ISSUE THREAD

**Issue by ghost** [apache/airflow#41339]
### Description

Coalesce is one of the industry-leaders in Snowflake transformations and orchestration efforts. Currently, there is not a provider available to run Coalesce workflows via Airflow. This issue proposes a new provider (Coalesce) with a `CoalesceOperator` that allows for a Coalesce workflows to be triggered.

### Use case/motivation

With a CoalesceOperator, Airflow users can orchestrate their Coalesce workflows in a DAG. This is what Airflow is built for; orchestrating disparate components of a data ecosystem, all while maintaining a single pane of glass into execution details.

Coalesce is used in a somewhat similar way to dbt, which is wildly popular among Airflow users. This operator is just the first component of a larger provider offering (hooks, sensors, etc.).

### Related issues

NA, there are no related issues associated with this.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please follow the procedure of accepting new provider
https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers

**Comment by jroach-astronomer** [comment]
@eladkal, thanks for the documentation. I went ahead and read through it, but I was still unclear on next-steps. Do I go ahead and start a thread with the `devlist`? Is there another way to begin the discussion? Should I develop the PR before or after the discuss? Thanks for the help!

**Comment by eladkal** [comment]
First step is to start a discussion in the mailing list with your proposal. If this is not clear from the guide then please feel free to improve it

**Comment by potiuk** [comment]
Also search archives https://lists.apache.org/list.html?dev@airflow.apache.org with "new provider" discussions - and you will see how such discussions looked in the past. This is a very good way to understand whether you want to get the new provider at all in the first place, and what are the chances that your proposal will be accepted.
