### ISSUE TITLE
[OpenAI Provider] Support Batch API in OpenAI Hook 

### ISSUE THREAD

**Issue by josix** [apache/airflow#41336]
### Description

For generating a large number of responses from OpenAI's LLM, we can leverage the [Batch API](https://platform.openai.com/docs/guides/batch/overview) to send asynchronous groups of requests and wait for their completion when rapid response is not required. This approach can also help reduce costs in use cases such as prompt evaluations and applying prompts to each entity in large datasets. Supporting this functionality would be particularly useful for workflows in Airflow, which is commonly used for batch processing of different datasets. It would be great if the OpenAI provider could support the Batch API.

### Use case/motivation

To support Batch API, the OpenAI Hook would need to include the following behaviors:

1. Support for OpenAI().files.create, which is already implemented.
1. Support for OpenAI().batches.create to submit a job for OpenAI to make predictions on the file.
1. Support other behaviors that batches have such as retrieve and cancel. 

I think that would be nice if we have a new deferrable operator to submit the batch prediction and retrieve the results once finished, that would be helpful.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
Sounds like a good idea. As you checked the you're willing to submit a PR box, I'll assign this one to you.
