### ISSUE TITLE
Graph view crashes when a DAG is empty

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#41332]
### Apache Airflow version

main (development)

### What happened?

When an empty DAG is created without any tasks, the DAG can be parsed and triggered in the UI, but the UI crashes when you click on _Graph_. The entire screen (except the top bar) disappears.

```
Uncaught TypeError: u.nodes.children[0] is undefined
    gQ http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    wa http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    Ms http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    wl http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    vu http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    mu http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    gu http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    iu http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    ru http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    _ http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
    O http://localhost:28080/static/dist/grid.abc695e791ed71742eea.js:2
grid.abc695e791ed71742eea.js:2:2750893
```

### What you think should happen instead?

The UI should load correctly. The graph should be empty (no blocks), but other controls should still load.

### How to reproduce

1. Load this DAG into Airflow

    ```python
    from airflow.decorators import dag

    @dag(schedule=None)
    def empty():
        pass

    empty()

2. Trigger a run from the Home page.

3. Click into the DAG detail view
4. Clikc on _Graph_


### Operating System

n/a

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josix** [comment]
I made [this change](https://github.com/josix/airflow/commit/7a6b04dc0f0a96b56812323eb299c2bbbdd93354) to let the page no become blank, but is it okay to display empty dag like this?


![image](https://github.com/user-attachments/assets/f03e4b98-9b60-46d9-8ac3-f1cd55a36aa4)

**Comment by romsharon98** [comment]
> I made [this change](https://github.com/josix/airflow/commit/7a6b04dc0f0a96b56812323eb299c2bbbdd93354) to let the page not become blank, but is it okay to display empty dag like this?
> 
> ![image](https://private-user-images.githubusercontent.com/18432820/356245257-f03e4b98-9b60-46d9-8ac3-f1cd55a36aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzAyMzAsIm5iZiI6MTcyMzEyOTkzMCwicGF0aCI6Ii8xODQzMjgyMC8zNTYyNDUyNTctZjAzZTRiOTgtOWI2MC00NmQ5LThhYzMtZjFjZDU1YTM2YWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MWE3ZTk0NGY2ZGIxMjUxMTA1ODQxYjcwMDY5NzQ3MmFmNDg2YjdhNzg5NGI2ZjQ2NzNlZWRlOTU0MzI1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIq26CDUjKEHRfNyC7BC9wK2bpOTPMYWet-UJkY_O7g)

Yes, I think this is how it should look.

**Comment by uranusjr** [comment]
Agreed, I think an empty page is good enough. An empty DAG is a user error anyway, and it’s probably good enough we don’t crash.
