### ISSUE TITLE
[Providers] Airbyte new deployment version changed API endpoints

### ISSUE THREAD

**Issue by baugarcia** [apache/airflow#41365]
### Apache Airflow Provider(s)

airbyte

### Versions of Apache Airflow Providers

apache-airflow-providers-airbyte==3.5.1

### Apache Airflow version

2.8.1

### Operating System

MWAA/AL

### Deployment

Amazon (AWS) MWAA

### Deployment details

Standard MWAA deployment. Nothing really specific or particular

### What happened

After updating to one of the latest Airbyte versions (and using acbtl installation method, as they have as standard on their documentation) the Airbyte provider from Airflow cannot connect to the api server. The reason is that the endpoints have changed, according to Airbyte's documentation:

https://github.com/airbytehq/airbyte/issues/43423

https://reference.airbyte.com/reference/standalone-server-deprecation-and-migration-to-airbyte-server

### What you think should happen instead

Provider should be updated so that it points to the correct endpoint of the new api for Airbyte server

### How to reproduce

Deploy MWAA. Perform a fresh install of Airbyte using current documentation and standards for OSS installation (abctl).
Use Airflow's Airbyte provider to do anything in the Airbyte server and you will get a connection refused error, as it is pointing to the wrong endpoint.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
@josix I think you might be interested in this one 🙂

**Comment by josix** [comment]
Yeah, let me check it

**Comment by marcosmarxm** [comment]
https://github.com/apache/airflow/pull/41122 implement the new Auth API method.

**Comment by Lee-W** [comment]
Thanks for letting us know! Let me reassign it to you
