### ISSUE TITLE
Microsoft-Azure - ms graph hook - Tenant ID fetched from wrong extra_dejson key.

### ISSUE THREAD

**Issue by w0ut0** [apache/airflow#41399]
### Apache Airflow Provider(s)

microsoft-azure

### Versions of Apache Airflow Providers

```
apache-airflow==2.9.1
apache-airflow-providers-microsoft-azure==10.1.1
```

### Apache Airflow version

2.9.1

### Operating System

Ubuntu 22.04.4 LTS

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

The general [Azure connection](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/azure.html) has parameter `tenantId`.

However, the [MS Graph operators](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/operators/msgraph.html) look for the key `tenant_id` ([code](https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/hooks/msgraph.py#L193)).

### What happened

```
{msgraph.py:214} INFO - Tenant id: None
(....)
ERROR - tenant_id should be an Azure Active Directory tenant's id (also called its 'directory id')
```

### What you think should happen instead

The tenant_id should be read from `extra_dejson.tenantId` instead of `extra_dejson.tenant_id`. We can keep both to maintain backwards compatibility. 

### How to reproduce

- Create a Microsoft Azure connection with client_id, client_secret and tenant id.
- Try to use the Microsoft Graph API Operator 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/41331
