### ISSUE TITLE
Error when you pass string arguments with white spaces on kubernetes pod operator

### ISSUE THREAD

**Issue by abmramirez** [apache/airflow#41419]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.2

### What happened?

When you pass arguments with white spaces on a kubernetes pod operator, a carriage return is added after each whitespace on the rendered template and the operator reads each line as distinct params. We tested this on 2.9.2 and previous versions. The same happens with apache-airflow-providers-cncf-kubernetes 8.3.1 and previous version.
For example: 

if the argument is: {"data": "value with spaces"}

The rendered template prints this:

'--data',
'{"data": "value '
'with '
'spaces"}'

But it should be like this:
'--data',
'{"data": "value with spaces"}'

### What you think should happen instead?

The rendered template should not add a return carriage after white spaces

### How to reproduce

Passing arguments with a whitespace on a kubernetes pod operator

### Operating System

Ubuntu 22.04 container

### Versions of Apache Airflow Providers

apache-airflow==2.9.2
apache-airflow-providers-cncf-kubernetes 8.3.1

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

airflow install on linux box.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunank200** [comment]
@abmramirez you might want to ensure that the arguments are properly escaped or quoted. Does the following work for you?
```
task = KubernetesPodOperator(
    task_id='example_task',
    namespace='default',
    image='your-image',
    cmds=["/bin/bash", "-c"],
    arguments=['--data', '{"data": "value with spaces"}'],
    name='example-pod',
    in_cluster=True,
    is_delete_operator_pod=True,
    get_logs=True,
)
```

**Comment by abmramirez** [comment]
> @abmramirez you might want to ensure that the arguments are properly escaped or quoted. Does the following work for you?
> 
> ```
> task = KubernetesPodOperator(
>     task_id='example_task',
>     namespace='default',
>     image='your-image',
>     cmds=["/bin/bash", "-c"],
>     arguments=['--data', '{"data": "value with spaces"}'],
>     name='example-pod',
>     in_cluster=True,
>     is_delete_operator_pod=True,
>     get_logs=True,
> )
> ```
Hi,

That is how we are sending the parameters and the error still occurs.
