### ISSUE TITLE
Use `set` instead of `list` for dag's tags

### ISSUE THREAD

**Issue by Avihais12344** [apache/airflow#41420]
### Description

Instead of using `list` for holding the tags of a specific dag (as we can see at the [docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/dag/index.html#airflow.models.dag.DAG)), I suggest using `set` instead, specifically [`MutableSet` for the type hinting](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSet), and [python `set`](https://docs.python.org/3/tutorial/datastructures.html#sets) as the default implementation.

### Use case/motivation

I would want to add multiple tags (even the same ones) faster, without worrying about duplicates, and reduce the memory usage because of it. Also, it's good to check if a certain tag already exists.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunank200** [comment]
@Avihais12344 Thanks for raising the issue. I had follow-up questions:
- Will this change to `set` break any existing DAGs or workflows expecting a list? I think it would. Wouldn't this be breaking change? 
- Are there any edge cases or performance regressions to consider with this change?
- How would we ensure the use of `set` is consistent across the codebase, particularly in how tags are stored/retrieved?

**Comment by Avihais12344** [comment]
Hello @sunank200, thanks for responding.

It would break existing code expecting tags as list, that's why I wanted to discuss it here.
The interface is different from list, but other than that, it would not be too much than different, we can think of it as a unique list. So I think there would not be edge case, as we alreay take the unique items from the tags list.

We can ensure the use of `set` accross the codebase by using typing and linters that would enforce the right types.

**Comment by Avihais12344** [comment]
Created a PR for this [here](https://github.com/apache/airflow/pull/41695).
