### ISSUE TITLE
ModuleNotFoundError: No module named 'methodtools' due to breaking changes made in a new release 3.8.0 of apache-airflow-providers-microsoft-mssql library

### ISSUE THREAD

**Issue by thelastmessiha** [apache/airflow#41446]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

After upgrading from apache-airflow-providers-microsoft-mssql = "==3.7.2" to apache-airflow-providers-microsoft-mssql = "==3.8.0" while also upgrading from composer-2.8.7-airflow-2.7.3 to composer-2.8.8-airflow-2.7.3, I saw a DAG import error, and had to specify and install methodtools = "==0.4.7" to get past the error. I was expecting this dependent package get installed automatically. Google Support says the mssql.py script is the one requesting the dependency but after checking the readme for the apache-ariflow-providers-microsoft-mssql, it is not listed as a needed package [2][3]. For a fix on this you would have to reach out to the package administrator team, as this dependency is not listed and therefore airflow did not have any instruction to download it. 

[1] File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/mssql_to_gcs.py", line 27, in from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 26, in from methodtools import lru_cache ModuleNotFoundError: No module named 'methodtools'
[2] 
``apache-airflow``                       ``>=2.7.0``
``apache-airflow-providers-common-sql``  ``>=1.14.1``
``pymssql``                              ``>=2.3.0``
[3] https://pypi.org/project/apache-airflow-providers-microsoft-mssql/

### What you think should happen instead?

I think methodtools should be included in the dependent packages of the apache-airflow-providers-microsoft-mssql provider

### How to reproduce

update apache-airflow-providers-microsoft-mssql library to 3.8.0

### Operating System

Ubuntu 20.04.6 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.27.0
apache-airflow-providers-apache-beam @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_apache_beam-5.7.1-py3-none-any.whl
apache-airflow-providers-celery @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_celery-3.6.0-py3-none-any.whl
apache-airflow-providers-cncf-kubernetes @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_cncf_kubernetes-8.3.3-py3-none-any.whl
apache-airflow-providers-common-compat==1.1.0
apache-airflow-providers-common-sql @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_common_sql-1.14.2-py3-none-any.whl
apache-airflow-providers-dbt-cloud @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_dbt_cloud-3.9.0-py3-none-any.whl
apache-airflow-providers-ftp @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_ftp-3.10.0-py3-none-any.whl
apache-airflow-providers-google @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_google-10.21.0-py3-none-any.whl
apache-airflow-providers-hashicorp @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_hashicorp-3.7.1-py3-none-any.whl
apache-airflow-providers-http @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_http-4.12.0-py3-none-any.whl
apache-airflow-providers-imap @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_imap-3.6.1-py3-none-any.whl
apache-airflow-providers-microsoft-mssql==3.8.0
apache-airflow-providers-mysql @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_mysql-5.6.2-py3-none-any.whl
apache-airflow-providers-postgres @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_postgres-5.11.2-py3-none-any.whl
apache-airflow-providers-sendgrid @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_sendgrid-3.5.1-py3-none-any.whl
apache-airflow-providers-sqlite @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_sqlite-3.8.1-py3-none-any.whl
apache-airflow-providers-ssh @ file:///usr/local/lib/airflow-pypi-dependencies-2.7.3/python3.11/apache_airflow_providers_ssh-3.11.2-py3-none-any.whl
apache-airflow-providers-tableau==4.5.2

### Deployment

Google Cloud Composer

### Deployment details

composer-2.8.8-airflow-2.7.3

### Anything else?

This problem occurs every time the parser tries to import a DAG that uses the provider. I had to install `methodtools = "==0.4.7"` manually/explicitly to get past the issue.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Already addressed in #41392
