### ISSUE TITLE
Is it possible to avoid a running dag run that would be affected if the dag file is changed? 

### ISSUE THREAD

**Issue by shawn-ann** [apache/airflow#41452]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.2.3

### What happened?

For running dag runs, any changes to the dag file should affect it.

### What you think should happen instead?

For running dag runs, any changes to the dag file should not affect it.

### How to reproduce

create a dag file with a dag id of "dag-001" containing a task A and B. A will take 30 minutes to execute, I run the dag file(first run), and while it's running I update the file and add a new task after B, and then run it again(second run).
My expectation is that the first run should only run tasks A and B, but it will also run C, even though I didn't add C at startup.

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please do not open issues for discussions - especially if you already opened one

**Comment by potiuk** [comment]
Patiently wait until someone will respond there (and for sure few hours for respeons is not patient - taking into account this forum where volunteers are helping others in their free time)

**Comment by shawn-ann** [comment]
Thanks
