### ISSUE TITLE
Email on failure stuck indefinitely (not timing out)

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#41490]
### Apache Airflow version

2.9.3

### What happened?

I’ve run into an issue where the email on failure feature causes a task to be indefinitly stuck without ever timing out. This problem was caused by firewall restrictions preventing outgoing traffic but shouldnt the emailing process timeout after 30s by default?

### What you think should happen instead?

The email process should timeout.

### How to reproduce

Block outgoing traffic via firewall restrictions.

### Operating System

Ubuntu

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunank200** [comment]
@pedro-cf Thank you for submitting the issue. Have you verified the smtp_timeout value in your airflow.cfg or environment variables? Also, please check if other settings like smtp_retry_limit and smtp_ssl are configured, as they might be affecting the behavior. Additionally, could you provide the logs from a task that got stuck due to this issue for further analysis?

**Comment by pedro-cf** [comment]
> @pedro-cf Thank you for submitting the issue. Have you verified the smtp_timeout value in your airflow.cfg or environment variables? Also, please check if other settings like smtp_retry_limit and smtp_ssl are configured, as they might be affecting the behavior. Additionally, could you provide the logs from a task that got stuck due to this issue for further analysis?

@sunank200 

- smtp_timeout: default
- smtp_retry_limit: default
- smtp_ssl: configured

Currently on vacation so don't have access to logs. Will provide asap.

**Comment by pedro-cf** [comment]
Sorry I am unable to provide the logs @sunank200

**Comment by potiuk** [comment]
So we close this one until someone can reproduce the error.
