### ISSUE TITLE
Make `dag_ids` parameter optional for `dagStats` REST API

### ISSUE THREAD

**Issue by reganbaum** [apache/airflow#41495]
### Description

Today, the `dagStats` REST API [requires a list of `dag_ids` as input](https://github.com/dondaum/airflow/blob/619d98932a023c80c24ca97e28d2fe3f9f11ba77/airflow/api_connexion/openapi/v1.yaml#L2164-L2177).

Can we make this parameter optional, so that if no `dag_ids` are provided, it will return all the stats of all the dags? This is the current behavior of the `dag_stats` endpoint, so it'd be good to have parity with the REST API so that the UI could use this same REST API in the future.

### Use case/motivation

Clients should be able to make a REST API call to get all the dag stats without requiring specific dag ids. 

### Related issues

https://github.com/apache/airflow/pull/41017 (see specific discussion in the PR here: https://github.com/apache/airflow/pull/41017#discussion_r1698824381)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dondaum** [comment]
I would be happy to help with this one again.

**Comment by Yusin0903** [comment]
Hi, Can I try this issue?

**Comment by potiuk** [comment]
Feel free to collaborate on that one @dondaum @Yusin0903

**Comment by dondaum** [comment]
@Yusin0903 I've already contributed to a similar feature request. So from my side you can take care of this and I can help you if you need help. What do you think?

**Comment by Yusin0903** [comment]
@dondaum ok, thank you!

**Comment by Yusin0903** [comment]
@dondaum Hi, because I am busy recently. I think I can not do it so well. Can u continue executing it?

**Comment by dondaum** [comment]
> @dondaum Hi, because I am busy recently. I think I can not do it so well. Can u continue executing it?

Sure. I will take this one over.

**Comment by michaeljs-c** [comment]
Hi @dondaum I'm looking to make my first contribution. Could I take part in this one?

**Comment by dondaum** [comment]
> Hi @dondaum I'm looking to make my first contribution. Could I take part in this one?

Sure. I think it is hard to split it up. So from my side you can take care of this and I can help you if you need help. What do you think?

**Comment by dondaum** [comment]
@potiuk can you please assign @michaeljs-c
