### ISSUE TITLE
XCom Display for INT value shows error in web UI

### ISSUE THREAD

**Issue by jscheffl** [apache/airflow#41514]
### Apache Airflow version

2.10.0rc1

### What happened?

When one task returns an integer value, the "new" XCom display shows an error JSON instead of the value like:

![image](https://github.com/user-attachments/assets/14341605-406f-432f-9d58-55ca8588d5af)

Noteworthy>: JSON or string or empty value works.

### What you think should happen instead?

The real INT value should be displayed

### How to reproduce

Run the DAG example_dynamic_task_mapping and check the XCom result of "add_one" task

### Operating System

not relevant

### Versions of Apache Airflow Providers

not relevant

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

not relevant

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
okay, same problem for bool and float.

**Comment by tirkarthi** [comment]
Faced similar issue : https://github.com/apache/airflow/pull/39918#issuecomment-2248601544
