### ISSUE TITLE
wait_for_downstream doesn't seem to work as expected

### ISSUE THREAD

**Issue by kakoni** [apache/airflow#41526]
### Apache Airflow version

2.10.0

### What happened?

Running this test code on 16. August. It does catchup.
```
from airflow.decorators import dag
from airflow.operators.bash import BashOperator

from datetime import datetime, timedelta

default_args = {
    'depends_on_past': True,
    'wait_for_downstream': True,
}

@dag(
    start_date=datetime(2024, 8, 10),
    default_args=default_args,
    schedule_interval='0 6 * * *'
)
def test2():
    t1 = BashOperator(task_id='t1', bash_command="sleep 10")
    t2 = BashOperator(task_id='t2', bash_command="sleep 10")
    t3 = BashOperator(task_id='t3', bash_command="sleep 10")
    t4 = BashOperator(task_id='t4', bash_command="sleep 10")
    t5 = BashOperator(task_id='t5', bash_command="sleep 10")

    t1 >> t2 >> t3 >> t4 >> t5

test2()
```

It proceeds to running tasks on the next day before the earlier day is finished.

<img width="297" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/a29e702e-a74d-44c8-b6ec-9221342cb7aa">

### What you think should happen instead?

I'm assuming that it should run all the tasks for Aug 13, before proceeding to any task on Aug 14

### How to reproduce

Run the provided dag code.

### Operating System

Docker

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
The behavior is as expected.
It start a new DagRun because the default max_active_runs is 16.
But it does not start the first task until the first and second task don't finish successfully in the DagRun before.

**Comment by kakoni** [comment]
@romsharon98 Thank you, I guess I misunderstood how wait_for_downstream flag works. So the corrective action would be to set max_active_runs to 1 for this dag I guess.

**Comment by romsharon98** [comment]
> @romsharon98 Thank you, I guess I misunderstood how wait_for_downstream flag works. So the corrective action would be to set max_active_runs to 1 for this dag I guess. 

Exactly
