### ISSUE TITLE
Access control error after upgrading from version 2.9.3 to 2.10.0

### ISSUE THREAD

**Issue by FelipeRamos-neuro** [apache/airflow#41540]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.0

### What happened?

After upgrading my Airflow deployment to the latest version, I noticed many DAG Import Errors mentioning access control

### What you think should happen instead?

I have always created my dags with similar permissions such as these: `{"EXAMPLE":["can_read","can_edit"]}`, on access_control. Unless the documentation hasn't been updated yet, it should still work as intended.

### How to reproduce

Deployment with Airflow 2.10.0 with Python 3.10 and with a dag created with similar access_control: `{"EXAMPLE":["can_read","can_edit"]}`

### Operating System

Amazon Linux 2

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.27.0
apache-airflow-providers-cncf-kubernetes==8.3.4
apache-airflow-providers-common-compat==1.1.0
apache-airflow-providers-common-io==1.4.0
apache-airflow-providers-common-sql==1.15.0
apache-airflow-providers-fab==1.2.2
apache-airflow-providers-ftp==3.10.1
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-mysql==5.6.3
apache-airflow-providers-postgres==5.11.3
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.2
```

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by FelipeRamos-neuro** [comment]
Some prints I forgot to add to the issue

![Captura de tela de 2024-08-16 12-41-16](https://github.com/user-attachments/assets/450b864b-d9c1-4fff-be3b-74f818d91d66)
![Captura de tela de 2024-08-16 12-41-33](https://github.com/user-attachments/assets/1bdff012-892c-4265-bb02-cc93de98077f)

**Comment by joaopamaral** [comment]
Hey @FelipeRamos-neuro, I was able to reproduce the error. I'll open the PR to fix it.

**Comment by joaopamaral** [comment]
Hey @FelipeRamos-neuro, can you confirm if this error vanishes if you navigate to a different link and back to dags? E.g try to go to dataset and navigate back to the dags? 
I can see the error only when I drop the db and start airflow from scratch, but when I navigate the error disappears. Do you have this same behavior?

**Comment by joaopamaral** [comment]
FYI, the error is that we are changing the access_control format (to include the resource name) in airflow 2.10, but old FAB version doesn't know how to handle it. I'll include in the PR to send the new format only if the FAB version can deal the new format.

https://github.com/apache/airflow/blob/8c2f56375a4560361c5f96d54c92c46674473387/airflow/models/dag.py#L937-L948
