### ISSUE TITLE
Add Backfill Button to DAGs Overview and Individual DAG Pages in the Webserver UI

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#41542]
### Description

This feature request proposes the addition of a "Backfill" button to the Apache Airflow webserver UI, both on the DAGs overview page and within individual DAG pages. This button would allow users to easily initiate backfill operations directly from the web interface without needing to use the command line interface (CLI).

![637656DC-1783-42AD-9E75-C7C84A72D4D9](https://github.com/user-attachments/assets/611f47ea-43f9-4264-98a9-8d5f17806089)

### Use case/motivation

Currently, Airflow users must use the CLI to perform backfills, which can be cumbersome and time-consuming, especially for users who are more comfortable with a graphical interface. By adding a "Backfill" button to the webserver UI, users would gain the ability to:

- Select a date range directly within the UI for backfilling.
- Initiate backfills with a single click, improving usability and reducing the need to switch between the UI and CLI.
- Monitor the status of the backfill operation within the same interface they use for all other DAG interactions.

This feature would significantly streamline the backfill process, making Airflow more user-friendly for those who prefer using the web UI over the CLI. It would also reduce the risk of errors associated with manual CLI commands, such as incorrect date inputs or DAG IDs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is far more than addinga "button". This is planned for Airflow 3 and the whole Airlfow Improvement Proposal about how to implement it https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-78+Scheduler-managed+backfill
