### ISSUE TITLE
callback without __name__ are not allowed when taskinstance executing

### ISSUE THREAD

**Issue by obarisk** [apache/airflow#41563]
### Apache Airflow version

2.10.0

### What happened?

_run_finished_callback now logs

```
callback.__name__
```

however, BaseNotifier without .__name__ attribute either.

It can be a bug "BaseNotifer" allowed in the callbacks of a dag

Or it just missing of documentation or incorrect documentation of [callback](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html)

### What you think should happen instead?

if we allow Notifer as callback,
then we must make function/Notfier callback execute correctly. i.e., modify the log of `callback.__name__`.

if we believe callbacks must with ".__name__" attributes, documents required.

### How to reproduce

the example dag will fail with airflow=2.10.0

```python
import datetime
import pendulum

from airflow import DAG
from airflow.operators.empty import EmptyOperator
from airflow.providers.discord.notifications.discord import DiscordNotifier
from airflow.providers.slack.notifications.slack_webhook import send_slack_webhook_notification


def task_failure_alert(context):
    print(f"Task has failed, task_instance_key_str: {context['task_instance_key_str']}")

def dag_success_alert(context):
    print(f"DAG has succeeded, run_id: {context['run_id']}")

with DAG(
    dag_id="example_callback",
    schedule=None,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    dagrun_timeout=datetime.timedelta(minutes=60),
    catchup=False,
    on_success_callback=[
      send_slack_webhook_notification(slack_webhook_conn_id="slack_default", text=" {{ dag.dag_id }}"),
      DiscordNotifier(discord_conn_id="discord_default", text= {{ dag.dag_id }}"),
    ],
    on_failure_callback=task_failure_alert,
    tags=["example"],
):
    task1 = EmptyOperator(task_id="task1")
    task2 = EmptyOperator(task_id="task2")
    task3 = EmptyOperator(task_id="task3", on_success_callback=[dag_success_alert])
    task1 >> task2 >> task3
```

### Operating System

Debian GNU/Linux 12

### Versions of Apache Airflow Providers

apache-airflow-providers-discord         | 3.7.1
apache-airflow-providers-slack           | 8.8.0

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
It looks like `__name__` is not present on instance of a class and in this case a notifier instance is used in the callback. The change was added in #38892.

Docs : `https://docs.python.org/3.10/library/stdtypes.html#definition.__name__`

> definition.__name__[¶](https://docs.python.org/3.10/library/stdtypes.html#definition.__name__)
> The name of the class, function, method, descriptor, or generator instance.

https://stackoverflow.com/questions/14514838/why-do-python-instances-have-no-name-attribute

cc: @romsharon98

**Comment by obarisk** [comment]
try to fix it.

https://github.com/apache/airflow/pull/41591
