### ISSUE TITLE
Support for workload identity authentication from the Databricks provider

### ISSUE THREAD

**Issue by basvandriel** [apache/airflow#41586]
### Description

Currently, only managed identity is supported for connecting from Airflow to Databricks using the `use_azure_managed_identity` parameter. However, I have a use case where an Airflow instance is running on an AKS cluster. That's why this would be a great improvement in authentication without using any secrets.

### Related issues

#39521 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@basvandriel Are you planning to implement this yourself?

**Comment by basvandriel** [comment]
Yes, I am working on this as we speak :)

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nathan Hadfield ***@***.***>
Verzonden: Wednesday, August 21, 2024 12:03:25 PM
Aan: apache/airflow ***@***.***>
CC: Bas van Driel ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [apache/airflow] Support for workload identity authentication from the Databricks provider (Issue #41586)


@basvandriel<https://github.com/basvandriel> Are you planning to implement this yourself?

**Comment by pmooij** [comment]
Nice @basvandriel, I would like to use this as well 👍
