### ISSUE TITLE
Logout link in no roles and permissions error page is broken

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#41580]
### Apache Airflow version

main (development)

### What happened?

logout endpoint was made a POST endpoint in https://github.com/apache/airflow/pull/40145 . With this change the /logout link in error page when there are no roles and permissions is still a GET request causing the request to be invalid. 

https://github.com/apache/airflow/blob/75fb7acbaca09a040067f0a5a37637ff44eb9e14/airflow/www/templates/airflow/no_roles_permissions.html#L32-L34

### How to reproduce

1. Initialize a new database.
2. Create an admin user.
3. Login as the user without roles and permission to get to the error page.
4. Click on logout link.

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
cc: @shahar1 -> small follow-up to #40145

**Comment by rohitnandi12** [comment]
Hi @potiuk @shahar1 ,

This issue seems straightforward and I am confident to solve this. This is also going to be my first step towards Open Source contribution. I request you to please assign this issue to me. 

Regards,
Rohit Nandi

**Comment by shahar1** [comment]
> Hi @potiuk @shahar1 ,
> 
> This issue seems straightforward and I am confident to solve this. This is also going to be my first step towards Open Source contribution. I request you to please assign this issue to me.
> 
> Regards, Rohit Nandi

Welcome abroad! :)
I assigned you, I'd be happy to review your PR when you're done.

**Comment by gagan-bhullar-tech** [comment]
@shahar1 Fixed this issue in my PR. Can you please assign this issue to me.
