### ISSUE TITLE
Running Breeze static checks (all files) on local machine results in failures

### ISSUE THREAD

**Issue by omkar-foss** [apache/airflow#41604]
### Apache Airflow version

main (development)

### What happened?

Running `breeze static-checks --all-files` on local machine results in failures. Reported by user Tim Perry on Airflow Slack.

**Failure output reported by user:**
```
Run flynt string format converter for Python.......................................Failed
- hook id: flynt
- files were modified by this hook
Running flynt v.1.0.1
Using config file at /Users/tim/code/qualapps/apache/apache-airflow/pyproject.toml
<unknown>:79: SyntaxWarning: invalid escape sequence '\s'
<unknown>:79: SyntaxWarning: invalid escape sequence '\s'
<unknown>:79: SyntaxWarning: invalid escape sequence '\s'
Run 'ruff format' for extremely fast Python formatting.............................Failed
- hook id: ruff-format
- files were modified by this hook
1 file reformatted, 4622 files left unchanged
4623 files left unchanged
un mypy for providers.............................................................Failed
- hook id: mypy-providers
- exit code: 2
Using 'uv' to install Airflow
Using airflow version from current sources
Leaving default pydantic v2
Using 'uv' to install Airflow
airflow/providers/fab/auth_manager/cli_commands/user_command.py:215: error:
f-string expression part cannot include a backslash [syntax]
      print(f"Created the following users:\n\t{'\\n\\t'.join(users_c...
          ^
Found 1 error in 1 file (errors prevented further checking)
Error 2 returned
If you see strange stacktraces above, and can't reproduce it, please run this command and try again:
breeze ci-image build --python 3.8
You can also run `breeze down --cleanup-mypy-cache` to clean up the cache used.
Using 'uv' to install Airflow
Using airflow version from current sources
Leaving default pydantic v2
Using 'uv' to install Airflow
```

### What you think should happen instead?

The static checks should complete without failures when no code changes have been made by user on local machine.

### How to reproduce

**Steps to reproduce this issue:**
1. Pull Airflow `main` repo.
2. Setup Breeze on local machine.
3. Run static checks with Breeze using command: `breeze static-checks --all-files`

### Operating System

macOS Sonoma 14.5 with Docker 4.32.0

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by omkar-foss** [comment]
I ran `breeze static-checks --all-files` on my local machine, and I too am seeing this error:
```
airflow/providers/fab/auth_manager/cli_commands/user_command.py:215: error:
f-string expression part cannot include a backslash [syntax]
      print(f"Created the following users:\n\t{'\\n\\t'.join(users_c...
```

Although I did not get this other error - `<unknown>:79: SyntaxWarning: invalid escape sequence '\s'`. This one actually is a (syntax) warning, so it's weird to see that it's causing a failure.

I'll look into this further and raise a PR accordingly.

**Comment by uranusjr** [comment]
I think this can be closed?

**Comment by omkar-foss** [comment]
Yes, just checking on one other failure (from a syntax warning) and a confirmation from the user who reported this issue (if it's fixed for them), after which I'll close this issue.

**Comment by potiuk** [comment]
Let's close it now - if the user has still problem we can always re-open. Closing things fast with the notion that they can be always re-opened is the best way to deal with issue overload.

**Comment by omkar-foss** [comment]
Sure, sounds good.
