### ISSUE TITLE
end_from_trigger leaves deferred tasks without an end_date and increasing duration

### ISSUE THREAD

**Issue by adrianrego** [apache/airflow#41613]
### Apache Airflow version

2.10.0rc1

### What happened?

Using new `end_from_trigger` option leaves successful tasks without an end_date.  This doesn't impact downstream operations, but the "duration" for the task in the UI is now considered as from the start of the DagRun to "now" and updates with each reload.  This minimizes the utility of the the Gannt Chart and Task Duration views.

### What you think should happen instead?

Tasks that are ended from a Trigger should be updated with a proper end_date in order to properly assess task duration (including deferred time).

### How to reproduce

Defer a task with `end_from_trigger = True`.  After task is completed check task duration in Tree View or Gantt Chart.  Duration updates everytime UI is reloaded and is considered from the the time of the DagRun until now.

### Operating System

All

### Versions of Apache Airflow Providers

Latest release versions.

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

K8S with KubernetesExecutor

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc @sunank200

**Comment by tirkarthi** [comment]
state attribute of task_instance is directly set in BaseTaskEndEvent. A possible fix would be to call task_instance.set_state which will set the state and update end_date and duration attributes. I can raise a fix for this.

**Comment by tirkarthi** [comment]
@adrianrego  Please review #41754 . I guess you can also inherit `BaseTaskEndEvent` to override `handle_submit` to call set_state as per PR and use it as base class for custom TaskSuccessEvent, TaskFailedEvent etc. though I haven't tested it in case you need the fix before next release of 2.10.1 .

**Comment by adrianrego** [comment]
@tirkarthi Thanks for the quick PR.  I'm in no position to officially review, but the changes look straight-forward and covered by a test-case.  I can wait for this to make it into the next release cycle.

**Comment by Lee-W** [comment]
> @tirkarthi Thanks for the quick PR. I'm in no position to officially review, but the changes look straight-forward and covered by a test-case. I can wait for this to make it into the next release cycle.

Even if you don't have commitership, you can still encouraged to review a PR 🙂  I'll also try to take a look these days
