### ISSUE TITLE
can't scroll task tries

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#41660]
### Apache Airflow version

2.10.0

### What happened?

I can't scroll task tries when there is more than 10 retries

![image](https://github.com/user-attachments/assets/3f350cbc-e41e-43e0-8874-fa62e3d8c68e)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
I am unable to reproduce this on v2-10-test and 2.10.0 . cc: @bbovenzi

**Comment by bbovenzi** [comment]
@raphaelauv what browser are you using?

**Comment by raphaelauv** [comment]
google chrome Version 128.0.6613.84 (Official Build) (64-bit)

**Comment by tirkarthi** [comment]
Just to add I was trying it on Firefox 129.0.1 in Ubuntu.

**Comment by raphaelauv** [comment]
maybe it's related to https://github.com/apache/airflow/issues/41742

since for a dag_run I can see 13 runs and scrool and for another I can't scrool and see the first 3 tries
![Screenshot from 2024-08-26 19-08-21](https://github.com/user-attachments/assets/50112107-40fd-40e9-9437-b3cb685f732a)
![Screenshot from 2024-08-26 19-08-13](https://github.com/user-attachments/assets/9c3babce-a716-4e6b-87d7-64eee72b8827)

**Comment by bbovenzi** [comment]
I wonder if we should flip the order too. The last try is more important than the first, no?

**Comment by raphaelauv** [comment]
bug no more present on `2.10.2`
