### ISSUE TITLE
Add helpful debug statements to Google Cloud Dataproc hook

### ISSUE THREAD

**Issue by fnshemerirwe** [apache/airflow#41789]
### Apache Airflow Provider(s)

google

### Apache Airflow version

airflow-2.9.1

### Operating System

NA

### Deployment

Google Cloud Composer

### What happened

The various hooks in the Google Cloud Dataproc hook do not have debug statements that would make it easier for developers to identify and resolve issues related to passing incorrect field values to the APIs. 

One specific example is the [create_batch](https://github.com/apache/airflow/blob/ded67d04c666aa8dc92d0c752e7d0fb5f856da1d/airflow/providers/google/cloud/hooks/dataproc.py#L965), method. By including a debug statement that prints the batch object, developers can quickly verify the object's contents and identify any discrepancies between the fields and the Dataproc API. 

### How to reproduce

Submit any DAG using [Google Cloud Batch Operator](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/cloud_batch.html#submit-a-job) 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
If you want - feel free to contribute - otherwise it will have to wait for someone to pick it up- marked as good first issue.

**Comment by gaurav-bakale** [comment]
> If you want - feel free to contribute - otherwise it will have to wait for someone to pick it up- marked as good first issue.

I would like to pick it up. Can you please tell me whom to contact if I need some help while adding statements.

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/43265
