### ISSUE TITLE
Typo in OTEL trace attribute

### ISSUE THREAD

**Issue by swythan** [apache/airflow#41836]
### Apache Airflow version

2.10.0

### What happened?

The OTEL spans created for tasks have an attribute called `ququed_by_job_id` which I believe should be `queued_by_job_id`.

### How to reproduce

Enable OTEL tracing and run a DAG. 

### Operating System

Ubuntu 22.04.4 LTS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by howardyoo** [comment]
I believe your observation is right! Definitely looks like a typo.

**Comment by swythan** [comment]
Thanks, all.
