### ISSUE TITLE
Connecting to a remote airflow instance via cli

### ISSUE THREAD

**Issue by deepaksinghkhetwal** [apache/airflow#41849]
### What do you see as an issue?

Hello, I am trying to connect to an airflow running remotely in EC2 via airflow cli from local. I am following the below documentation for the setup. I cannot find a way to authenticate to the remote airflow instance. Is it possible to do it?

https://airflow.apache.org/docs/apache-airflow/2.0.2/usage-cli.html#set-up-connection-to-a-remote-airflow-instance

### Solving the problem

If it is possible to authenticate to a remote airflow the steps can be documented

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
The remote connect option to use the CLI with the REST API has been removed. The link of documentation you shared is from a very old 2.0.2 Airflow-version.
The current version of the SW does not carry this at the moment. But we are planning to re-introduce this in Airflow 3 again for better remote management under the umbrealla of AIP-81 (see https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-81+Enhanced+Security+in+CLI+via+Integration+of+API?src=contextnavpagetreemode) - if you are wanting to contribute we would be happy.
