### ISSUE TITLE
AirFlow 2.9.3 hatch build missing www/static/dist inside the output wheel

### ISSUE THREAD

**Issue by gaoweisgp** [apache/airflow#41866]
### Apache Airflow version

2.9.3

### What happened?

Per[ INSTALL file](https://github.com/apache/airflow/blob/v2-9-stable/INSTALL#L219), the `hatch build` result for v2-9-stable (2.9.3) does not contains "airflow/www/static/dist" subdirectory. On the other hand, the provided 2.9.3 wheel has it. This caused the installed airflow UI to have lots of 404 errors for files like
```
http://127.0.0.1:8081/control/static/dist/bootstrap-datetimepicker.min.css
``` 

### How to reproduce

1. hatch build -t sdist
2. tar -tf filename.tar.gz | grep 'www/static/dist'

### Operating System

Red Hat Enterprise Linux release 8.8 (Ootpa)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Correct. You need to use -t custom target to build assets as described in https://github.com/apache/airflow/blob/v2-9-stable/INSTALL#L342
