### ISSUE TITLE
After user admin recreation: AttributeError: 'NoneType' object has no attribute 'is_active': unable to connect

### ISSUE THREAD

**Issue by good92** [apache/airflow#41901]
### Apache Airflow version

2.9.3

### What happened?

After deletion and recreation of the user admin to change its password, Airflow is no more accessible and fails with:

│   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/fab_auth_manager.py", line 183, in is_logged_in                                                                    │
│     return not self.get_user().is_anonymous                                                                                                                                                                     
│   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 316, in __get__                                                                                                              
│     obj = instance._get_current_object()                                                                                                                                                                        
│   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 520, in _get_current_object                                                                                                  
│     return get_name(local())  # type: ignore                                                                                                                                                                    
│   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>                                                                                                          
│     current_user = LocalProxy(lambda: _get_user())                                                                                                                                                             
│   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user                                                                                                        
│     current_app.login_manager._load_user()                                                                                                                                                                     
│   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/login_manager.py", line 364, in _load_user                                                                                               
│     user = self._user_callback(user_id)                                                                                                                                                                         
│   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1553, in load_user                                                             │
│     if user.is_active:                                                                                                                                                                                           AttributeError: 'NoneType' object has no attribute 'is_active' 

### What you think should happen instead?

Airflow should be accessible and present the login form or a use full error to fix the user configuration - session reset,
after admin user recreation.

### How to reproduce

airflow users delete -u admin
airflow users create --username admin --password admin --role Admin --firstname admin --lastname admin --email admin@admin.com

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.25.0
apache-airflow-providers-celery==3.7.2
apache-airflow-providers-cncf-kubernetes==8.3.3
apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.2
apache-airflow-providers-docker==3.12.2
apache-airflow-providers-elasticsearch==5.4.1
apache-airflow-providers-fab==1.2.2
apache-airflow-providers-ftp==3.10.0
apache-airflow-providers-google==10.21.0
apache-airflow-providers-grpc==3.5.2
apache-airflow-providers-hashicorp==3.7.1
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-microsoft-azure==10.2.0
apache-airflow-providers-mysql==5.6.2
apache-airflow-providers-odbc==4.6.2
apache-airflow-providers-openlineage==1.9.1
apache-airflow-providers-postgres==5.11.2
apache-airflow-providers-redis==3.7.1
apache-airflow-providers-sendgrid==3.5.1
apache-airflow-providers-sftp==4.10.2
apache-airflow-providers-slack==8.7.1
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-snowflake==5.6.0
apache-airflow-providers-sqlite==3.8.1
apache-airflow-providers-ssh==3.11.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

  image:
    repository: apache/airflow
    tag: slim-2.9.3-python3.11

with argocd configuration and K8sexecutor

### Anything else?

unable to connect and reset the configuration

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by good92** [comment]
workaround:
airflow db reset
airflow users create --username admin --password admin --role Admin --firstname admin --lastname admin --email [admin@admin.com](mailto:admin@admin.com)

Notes:
webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:62660 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:62715 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:63882 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:63946 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64582 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64674 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:64940 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65014 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65117 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65199 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65385 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65441 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65874 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:65950 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66003 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66087 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66686 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66779 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66918 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:66964 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:67735 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:67791 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68043 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68097 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68532 SyntaxWarning: invalid escape sequence '\d'                                                     │
│ webserver /home/airflow/.local/lib/python3.12/site-packages/azure/synapse/artifacts/models/_models_py3.py:68588 SyntaxWarning: invalid escape sequence '\d'

**Comment by jscheffl** [comment]
I assume the "right" way to reset a user (admin or normal) password is:
```
root@fb30c3a3f4ce:/opt/airflow# airflow users reset-password --help
Usage: airflow users reset-password [-h] [-e EMAIL] [-p PASSWORD] [--use-random-password] [-u USERNAME] [-v]

Reset a user's password

Options:
  -h, --help            show this help message and exit
  -e, --email EMAIL     Email of the user
  -p, --password PASSWORD
                        Password of the user, required to create a user without --use-random-password
  --use-random-password
                        Do not prompt for password. Use random string instead. Required to create a user without --password
  -u, --username USERNAME
                        Username of the user
  -v, --verbose         Make logging output more verbose

examples:
To reset an user with username equals to "admin", run:

    $ airflow users reset-password \
          --username admin
```

**Comment by jscheffl** [comment]
Note: I tested the steps below "How to Reproduce" and can not see a problem in Airflow 2.10.0 and latest main (both). As you reported the problem with 2.9.3... can you test on 2.10 if you really can re-produce?
