### ISSUE TITLE
When generating "status of testing" issue, we should mark all commit authors not only PR authors

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#41969]
### Body

Currently when we gnerate "status of tesitng" we add PR authors to it - but sometimes (when commit is cherry-picked or when it has multiple authors) - the original author for the commit might not be marked in the issue.

We should improve our tooling to retrieve authorship information from the commit, not only from the PR.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @amoghrajesh

**Comment by potiuk** [comment]
See https://github.com/apache/airflow/issues/41956#issuecomment-2325592569 for example.

**Comment by amoghrajesh** [comment]
Thanks! I will try and take a look at it

**Comment by potiuk** [comment]
Also - one other - related thing I notices - for such backported PRs, we also do not mention linked issues - because they are linked to the original PRs, so likely we need to do a bit more complex calculation of those:

a) get all the authors from the commit
a) if the commit message contains (cherry-picked from .....) -> find the original PR (by looking at the (#number) in the original commit message.
b) get the linked issue information from the original PR
