### ISSUE TITLE
XCOM value json viz - CamelCase keys

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#42029]
### Apache Airflow version

2.10.0

### What happened?

when I vizualize the XCOM in airflow UI , the keys are formatted in CamelCase

![image](https://github.com/user-attachments/assets/f87a91ef-e7e8-44de-a69e-72168b8ec737)

### How to reproduce

```python
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.dates import days_ago

with DAG(dag_id="test",
         start_date=days_ago(1),
         schedule=None):
    def toto():
        rst = []
        results_list = ["a", "b", "c", "d"]
        for index, item in enumerate(results_list):
            tmp = {
                "aaaaaaaa_bbbbbb": index,
                "cccccccc_dddddd": item
            }
            rst.append(tmp)

        return rst

    PythonOperator(
        task_id="a",
        python_callable=toto,
        do_xcom_push=True,
    )

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Uuups, great catch... and this is serious. I tried to trace it down and it seems to be rooted in the automatically generated API client bindngs in JavaScript which use `CamelCasedPropertiesDeep` from the JSON response...

@bbovenzi do you know how the generated API can be influenced NOT to camelCase all objects received from public API?
