### ISSUE TITLE
metric name in otel metric logger will get truncated if they exceed limit of 63 characters

### ISSUE THREAD

**Issue by howardyoo** [apache/airflow#42038]
### Apache Airflow version

2.10.0

### What happened?

# Symptom
When running a DAG in Airflow with OTEL metrics enabled, you may receive warning messages that may look like this:
```
[2024-09-05, 11:01:22 CDT] {logging_mixin.py:190} WARNING - /opt/airflow/airflow/metrics/otel_logger.py:361 UserWarning: Metric name `airflow.dag.example_complex.update_tag_template_field.queued_duration` exceeds OpenTelemetry's name length limit of 63 characters and will be truncated to `airflow.dag.example_complex.update_tag_template_field.queued_du`.
```

# Reason
The reason being that metric name in OTEL standard will be limited to 63 characters, and thus, when the metric name exceeding that size is being generated, it will get truncated, as the message implies.

# Solution
When instrumenting these metrics, there is no need to make the metric name conforming to the statsd expression (which puts combination of attributes into the name, due to how the statsd data format is designed), but we could rather change the metric to:

- having **metric name** as : airflow.dag.queued_duration
- having **attribute** dag_id: example_complex
- having **attribute** task_id: update_tag_template_field

This will ensure the metric name to be well kept within the limit, while providing better context by separating dag_id with task_id.

### What you think should happen instead?

The current behavior is not correct because the metric name is getting truncated, and if there are longer names, it will lose the full information of what it was about.

### How to reproduce

Prepare and run DAG file with long dag id and task id, and see the task logs and identify WARNING message generated by otel_logger.py

### Operating System

Linux (amd64)

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ferruzzi** [comment]
Yes, this is well known and something we discussed when I was implementing the OTel metrics.  That is why some metrics are emitted twice; once with the "old" long StatsD name and again with a shorter name and tags for OTel.  In the case of your example, the shorter version is being emitted as `task.queued_duration` [here](https://github.com/apache/airflow/blob/main/airflow/models/taskinstance.py#L2829)

**Comment by ferruzzi** [comment]
The Airflow 3 dev team is discussing if we are going to drop StatsD entirely, which would remove the need for this.

Another alternative I have proposed int he past is that each metrics logger (StatsD, OTel, Datadog, etc) would need a "build name" method which accepts a short name and tags and returns the name to be emitted in the format that works for that logger; so otel's version would return the short name, statsd would return name with the tags concatenated onto it, etc.

**Comment by howardyoo** [comment]
Ah, I understand. I don't think StatsD is going to be dropped entirely in Airflow 3, though. Perhaps, in case of Otel metrics, if the metric name is longer than 63 characters, maybe we should just not send it, because that won't be meaningful. (ex. send the metrics twice, but if the metric name is longer than 63 char, just send the short name only).

However, I like your proposal of 'build name' method being applied across all of the metric loggers such that it would affect how the name should be generated for different types of metric loggers.

**Comment by ferruzzi** [comment]
I've also replied in the related conversation over [here](https://github.com/apache/airflow/issues/40800#issuecomment-2332254233) with some more background and details.

**Comment by howardyoo** [comment]
closing this issue, as related to the issue #40800. Would like the discussion to continue on there.
