### ISSUE TITLE
Wrong display of XCOM for boolean False value

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#42096]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.1

### What happened?

There was a bug in version 2.10 when displaying xcom values in the UI. It should have been fixed - see https://github.com/apache/airflow/pull/41516.

However, the problem persists for boolean False values (see images below).
For True - xcom displays correct value
![image](https://github.com/user-attachments/assets/862e1c6a-3247-4e83-be27-2210f2e48218)

For False - xcom displays wrong value
![image](https://github.com/user-attachments/assets/af83951e-92ee-48ac-94b7-3dab090544d3)

Test Dag Code:

```
from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator

# DAG Definition
with DAG(
    dag_id="TEST_XCOM_BOOLEANS",
    schedule = None,
    start_date = datetime(2024, 9, 8),
) as dag:

    def return_true():
        return True	

    true_task = PythonOperator(
        task_id = 'true_task',
        python_callable = return_true,
        trigger_rule = 'none_failed',
    )

    def return_false():
        return False	
	
    false_task = PythonOperator(
        task_id = 'false_task',
        python_callable = return_false,
        trigger_rule = 'none_failed',
    )	
```

### What you think should happen instead?

For False value it should display "False" and not "Value is NULL"

### How to reproduce

Run Dag (see the code below)

Test Dag Code:

```
from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator

# DAG Definition
with DAG(
    dag_id="TEST_XCOM_BOOLEANS",
    schedule = None,
    start_date = datetime(2024, 9, 8),
) as dag:

    def return_true():
        return True	

    true_task = PythonOperator(
        task_id = 'true_task',
        python_callable = return_true,
        trigger_rule = 'none_failed',
    )

    def return_false():
        return False	
	
    false_task = PythonOperator(
        task_id = 'false_task',
        python_callable = return_false,
        trigger_rule = 'none_failed',
    )	
```

### Operating System

Kubernetes on Unix platform

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment]
fix was merge, @Pad71 can you close the issue ?

**Comment by Pad71** [comment]
@raphaelauv DOne :)
