### ISSUE TITLE
UI: Dag trigger form not submitting parameters on keyboard submit

### ISSUE THREAD

**Issue by hskev** [apache/airflow#42157]
### Apache Airflow version

2.10.0

### What happened?

- Triggered DAG using "Trigger DAG"
- Submitted "Dag Conf Parameters" form using the enter key, instead of the "Trigger" button
- DAG ran with the default parameters as defined in the DAG itself.

When doing the same process, but clicking the "Trigger" button, the parameters are passed through as expected.

### What you think should happen instead?

The values entered in the "Dag Conf Parameters" input fields should be passed to the DAG run.

### How to reproduce

1. Trigger a DAG run with parameters
2. In the "DAG conf Parameters" section, enter valid inputs
3. Trigger the DAG by using the enter key whilst your cursor is in one of the input fields
4. The DAG run config shows the default values as they were defined in the DAG itself.

(This is experienced using the latest version of Firefox on the latest stable MacOS)

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.27.0
apache-airflow-providers-celery==3.7.3
apache-airflow-providers-cncf-kubernetes==8.3.4
apache-airflow-providers-common-compat==1.1.0
apache-airflow-providers-common-io==1.4.0
apache-airflow-providers-common-sql==1.15.0
apache-airflow-providers-docker==3.12.3
apache-airflow-providers-elasticsearch==5.4.2
apache-airflow-providers-fab==1.2.2
apache-airflow-providers-ftp==3.10.1
apache-airflow-providers-google==10.21.1
apache-airflow-providers-grpc==3.5.2
apache-airflow-providers-hashicorp==3.7.1
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-microsoft-azure==10.3.0
apache-airflow-providers-mysql==5.6.3
apache-airflow-providers-odbc==4.6.3
apache-airflow-providers-openlineage==1.10.0
apache-airflow-providers-postgres==5.11.3
apache-airflow-providers-redis==3.7.1
apache-airflow-providers-sendgrid==3.5.1
apache-airflow-providers-sftp==4.10.3
apache-airflow-providers-slack==8.8.0
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-snowflake==5.6.1
apache-airflow-providers-sqlite==3.8.2
apache-airflow-providers-ssh==3.12.0```

### Deployment

Docker-Compose

### Deployment details

Python 3.12 base image

`INSTALL_MYSQL_CLIENT_TYPE=mysql`

However, was able to reproduce with a base docker-compose image.

### Anything else?

Happens every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
In-deed this is a (small) bug. Form fields are only updating the dict in javascript when leaving the field, but if you press enter then the form is submitted w/o updating.

Would you like to supply a fix?

**Comment by dannyl1u** [comment]
Hi! I'd like to raise a PR for this as my first contribution, can this be assigned to me?

**Comment by jscheffl** [comment]
> Hi @jscheffl I'd like to raise a PR for this as my first contribution, can this be assigned to me?

Yes, cool! Looking forward for a PR! Thanks.

**Comment by dannyl1u** [comment]
Hi @jscheffl ! Submitted https://github.com/apache/airflow/pull/42487 for the fix

**Comment by hskev** [comment]
@dannyl1u Appreciated!
