### ISSUE TITLE
AIP-84 List DAGs endpoint new features (1/2)

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42159]
### Description
Related to: https://github.com/apache/airflow/issues/42370

Create a list DAGs endpoint in fastAPI. Make sure that is feature-complete with the dags list homepage in the legacy UI.

Features:
- include last dag run
- sort by dag_display_name ✅ , next run datetime ✅ , last run datetime ✅, last run state ✅,
- filter by tags ✅, owners ✅, last run state ✅ , is paused ✅ 
- search by dag_display_name ✅ ,

### Use case/motivation

Our current REST API dags list endpoint is not sufficient. It doesn't include any run history and sorting only works for a few fields
The legacy UI uses a custom FAB view which also needs to be replaced.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Splitted in two with https://github.com/apache/airflow/issues/42467.
