### ISSUE TITLE
replace mysql-python with a python3 compatible mysql driver (e.g pymysql)

### ISSUE THREAD

**Issue by LilithWittmann** [apache/airflow#422]
The mysql-python package is currently not python3 compatible. So maybe someone should replace it with a python 3 compatible mysql driver. (e.g. pymysql - https://pypi.python.org/pypi/PyMySQL). It's also compatible with sqlalchemy: http://docs.sqlalchemy.org/en/rel_0_9/dialects/mysql.html#module-sqlalchemy.dialects.mysql.pymysql

**Comment by LilithWittmann** [comment]
Maybe mysql-python is still needed for celery. But celery should also work with sqlalchemy and sqlalchemy works with pymysql… (http://celery.readthedocs.org/en/latest/getting-started/brokers/sqlalchemy.html)

**Comment by jlowin** [comment]
I think [optional] celery requirements shouldn't block airflow at all, especially since celery is itself optional for airflow. See also #423

**Comment by jlowin** [comment]
Believe this is closed in #424/#442
