### ISSUE TITLE
Hardcoded Opentelemetry SERVICE_NAME

### ISSUE THREAD

**Issue by nicolasge** [apache/airflow#42210]
### Apache Airflow version

2.10.1

### What happened?

When enabled the OTEL in Airflow, the OTEL_SERVICE_NAME is hardcoded to "Airflow".  Based on https://opentelemetry.io/docs/languages/sdk-configuration/general/ users should be able to overwrite this to any value via environment variable OTEL_SERVICE_NAME.

Image code path: /home/airflow/.local/lib/python3.12/site-packages/airflow/metrics/otel_logger.py
Bug line:  resource = Resource(attributes={SERVICE_NAME: "Airflow"})

### What you think should happen instead?

If user specified OTEL_SERVICE_NAME via environment, airflow use should this value instead of hardcoded value which is "Airflow"

### How to reproduce

During the installation, inject an extra environment OTEL_SERVICE_NAME and set the value to a value not equal to Airflow

### Operating System

Debian 12

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
Apparently `otel` configuration already have  `service_name` configuration, I duplicate it to the metrics section and apply it on the service name.

Let me know what you think on the [PR](https://github.com/apache/airflow/pull/42242)

**Comment by nicolasge** [comment]
It looks good to me.  Thanks @romsharon98
