### ISSUE TITLE
Facing lots of issues while following Contribution-quick start guidelines for M1. 

### ISSUE THREAD

**Issue by nikhilkarve** [apache/airflow#42238]
### What do you see as an issue?

1. While running breeze ci-image build
ERROR: failed to solve: process "/bin/bash -o pipefail -o errexit -o nounset -o nolog -c bash /scripts/docker/install_os_dependencies.sh dev" did not complete successfully: exit code: 100
Error when building image! Image build: 3.8:linux/arm64
2. After running breeze setup autocomplete
Users/nkarve/Desktop/Personal/airflow/airflow/dev/breeze/autocomplete/breeze-complete-zsh.sh:34: command not found: compdef

Also had a few errors earlier with docker versions. 

### Solving the problem

It feels overwhelming and difficult for a new person to get started. Can we please have a dedicated macOs dev env installation guide? Or at least a youtube video from someone who have done it before. 

Much needed. Thanks!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gopidesupavan** [comment]
It looks like you have problem in bash or zshrc file, try add these to those files.

autoload -Uz compinit
compinit
