### ISSUE TITLE
remove scheduler_lock column

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#42258]
### Body

This field exists on the dag table.  Pretty sure it's not used.

<img width="708" alt="image" src="https://github.com/user-attachments/assets/a7be4f35-2bbe-4704-bdde-7d66bef78823">

cc @phanikumv @cmarteepants 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by prabhusneha** [comment]
Can I pick up this change?

**Comment by dstandish** [comment]
sure
