### ISSUE TITLE
Add REST API for configuring DAG bundle backends

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42294]
### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by jedcunningham** [comment]
These are not being configured in the db any longer, removing the need for this endpoint.

**Comment by wzhpor** [comment]
Hi!

I'm starting with airflow and trying to see provisioning methods that are available. Do I understand correctly that bundles will only be configurable via file and restatr of airflow will be required to add new git repo/bundle?
