### ISSUE TITLE
Add cli for configuring DAG bundle backends

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42293]
### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Prab-27** [comment]
@jedcunningham , I'd like to work on this issue.

**Comment by jedcunningham** [comment]
Hi @Prab-27, sorry, we've gone a different direction and these are being configured in configuration instead (#44924). However, there is some other cli/api work if you are open to it. I'll tag you in those issues later today.

**Comment by Prab-27** [comment]
Thanks @jedcunningham. I'd like to work on that type of issue. If there are any, tag me.

**Comment by jedcunningham** [comment]
@Prab-27, there are a number of issues in the [project for AIP-66](https://github.com/orgs/apache/projects/406), if you'd like to pick up one of them.
