### ISSUE TITLE
Changed behaviour on macros template due to Pendulum v3

### ISSUE THREAD

**Issue by fritzwijaya** [apache/airflow#42302]
### Apache Airflow version

2.10.1

### What happened?

Due to changed default behaviour on Pendulum v3.x.x, the default print behaviour for template is getting affected. Its breaking dags that rely on template that using Pendulum type like `data_interval_start` and `data_interval_end`.

The current work around is to using Airflow Jinja filter `ts`.

### How to reproduce

In Pendulum 2:
```
>>> import pendulum
>>> str(pendulum.now())
'2024-01-29T16:00:38.678167-06:00'
```

In Pendulum 3:
```
>>> import pendulum
>>> str(pendulum.now())
'2024-01-29 16:00:23.305698-06:00'
>>> 
```

### Operating System

Docker/Debian

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
This has been [discussed](https://github.com/apache/airflow/discussions/37037) before.  I'd suggest using [.isoformat(sep='T')](https://docs.python.org/3/library/datetime.html#datetime.date.isoformat) if you require back compat.
