### ISSUE TITLE
 New "airflow assets" CLI subcommand

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#42317]
### Description

[User Presentation Considerations](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=311627076#AIP75NewAssetCentricSyntax-UserPresentationConsiderations)

* [x] `airflow assets list` https://github.com/apache/airflow/pull/44387
* [x] `airflow assets detail` https://github.com/apache/airflow/pull/44445
* [x] `airflow assets --alias` to list asset aliases https://github.com/apache/airflow/pull/44595
* [x] `airflow assets detail --alias` to view an asset alias https://github.com/apache/airflow/pull/44595
* [x] `airflow assets materialize` https://github.com/apache/airflow/pull/44558
    * something like `airflow dags trigger`
    * steps
        1. get an asset
        2. find the tasks reference this asset as an outlet
            1. raise an error if there's not
            2. raise an error if there're more than one (as of now)
        3. trigger that DAG

### Use case/motivation

[Rationale](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=311626828#AIP73ExpandedDataAwareness-Rationale)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
First CLI subcommand `list` #44387
