### ISSUE TITLE
Calculate and track DAG version

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42333]
### Body

We need to calculate the DAG version based on the serialized DAG, and start tracking it on the task instance try level.

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by phanikumv** [comment]
facing some issues on the DAG hash, working on it

**Comment by ephraimbuddy** [comment]
PR: https://github.com/apache/airflow/pull/42517
PR: https://github.com/apache/airflow/pull/42547

**Comment by ephraimbuddy** [comment]
PR: https://github.com/apache/airflow/pull/42690
