### ISSUE TITLE
Refactor serialized_dag and dag_code to keep version history

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42334]
### Body

Add the version from #42333 to the PK for ser dag and DAG code.

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by ephraimbuddy** [comment]
PR: https://github.com/apache/airflow/pull/43821

**Comment by phanikumv** [comment]
Closing as the PR is merged
