### ISSUE TITLE
Investigate better DAG version detection?

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42337]
### Body

Do this part of the AIP:

> We will explore having a more comprehensive version detection method (e.g. if the code inside of a PythonOperators python_callable changes, or in functions that that callable calls)

Simply detecting when the `python_callable` that is passed changes (somehow), might be enough and a good line.

### Committer

- [x] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by kunaljubce** [comment]
@jedcunningham If I understand the ask correctly, as of today, the DAG UI still shows the older version of the `python_callable` code and we need a way to identify/log when the code change happens and show the updated code on the UI. Am I correct?

**Comment by phanikumv** [comment]
[PR](https://github.com/apache/airflow/pull/44180) has been merged. Closing this issue.
