### ISSUE TITLE
Remove execution_date and logical_date from arguments where function/API is used to look up a DAG run

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#42338]
### Body

Since we’re dropping the unique constraint, those arguments no longer can look up a unique DAG run. Those functions should already take a `run_id`, which should be used instead going forward.

The use of execution/logical date in those functions should have already been deprecated. If not, a deprecation warning should be added to the 2.x branch to be released in 2.11.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by sunank200** [comment]
Created a draft PR [https://github.com/apache/airflow/pull/42404](https://github.com/apache/airflow/pull/42404). Currently fixing the tests.

**Comment by sunank200** [comment]
Currently fixing the tests and making CI green.

**Comment by sunank200** [comment]
I have removed the `execution_date` completely. We have 202 files changed as part of this PR [#42404](https://github.com/apache/airflow/pull/42404) @uranusjr can you take a look, please for early review? I have renamed the execution date in the `TaskInstance` model and other classes. I am now working on fixing tests.

**Comment by sunank200** [comment]
I have fixed most of the tests. I am currently fixing the test for Core, WWW, API and CLI.

**Comment by phanikumv** [comment]
This is being addressed in https://github.com/apache/airflow/pull/42404
