### ISSUE TITLE
Remove execution_date from API, CLI, web UI return values

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#42339]
### Body

It should return the same value under `logical_date`. This field/attribute should already be present; if not, it should be added to the 2.x branch and released in 2.11.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by sunank200** [comment]
Most of the changes required for this is already part of this PR [https://github.com/apache/airflow/pull/42404](https://github.com/apache/airflow/pull/42404)

**Comment by phanikumv** [comment]
This is being addressed in https://github.com/apache/airflow/pull/42404
