### ISSUE TITLE
Remove all references on “execution date” as a name

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#42340]
### Body

This includes documentation, web UI labels, CLI strings, etc. In most cases they should just be renamed to _logical date_. We can investigate replacing them with another value (`run_id`?) in a case-by-case basis later.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by sunank200** [comment]
This can be closed as [#42404](https://github.com/apache/airflow/pull/42404) and [#43902](https://github.com/apache/airflow/pull/43902) was merged to main.

**Comment by uranusjr** [comment]
We still have some in the API. I’m not sure we need to work on those; will check with AIP-84 folks.

**Comment by sunank200** [comment]
Should I keep it open in that case?
