### ISSUE TITLE
AIP-84 Add external dependencies to a dag's graph_data

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#42367]
from @bbovenzi:
> In 2.10, we cobbled together a UI to show dataset conditions and upstream and downstream dataset dependencies. We should update this to include a boolean param show_external_dependencies to show connected datasets, dataset conditions, triggers and sensors.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by bbovenzi** [comment]
We can rename graph_data to dag `structure`, with edges and nodes. The nested list of nodes should have the topological sort, which we may move to happen during DAG serialization. With a sorted list of nodes, specifying which are tasks and which aren't, we can reuse the endpoint to help render the grid and gantt views.

**Comment by bbovenzi** [comment]
Actually, the sort should be based off of the `webserver.grid_view_sorting_order` config.

**Comment by bbovenzi** [comment]
Sample of the most minimal return we need. (using the same types as we would need with dag/asset dependencies)

```
{
  nodes: [
    {
      id: 'task_1',
      label: 'string', // task_display_name, asset_uri, etc
      type: 'task' | 'asset' | 'sensor' | 'trigger' // either the Ui can filter for only tasks, or we do
      children: [] // only for task groups
    }
  ],
  edges: [{
    source_id: 'task_1',
    target_id: 'task_2'
  }]
}
```

**Comment by bbovenzi** [comment]
Updated types I am using on the frontend mockups:

```
export type Edge = {
  is_setup_teardown?: boolean;
  label?: string;
  source_id: string;
  target_id: string;
};

export type Node = {
  children?: Array<Node>;
  id: string;
  is_mapped?: boolean;
  label: string;
  tooltip?: string;
  type:
    | "asset_alias"
    | "asset_condition"
    | "asset"
    | "dag"
    | "join"
    | "sensor"
    | "setup_task"
    | "takedown_task"
    | "task"
    | "trigger";
};

export type GraphData = {
  arrange: "BT" | "LR" | "RL" | "TB";
  edges: Array<Edge>;
  nodes: Array<Node>;
};
```

**Comment by pierrejeambrun** [comment]
Having fields optional in the payload, i.e `?:` makes it a little bit more complicated to handle and I think it might be easier to always return all fields, defaulting to `None` in case they are not filled, and the front knows what to read based on the `type`  value.
