### ISSUE TITLE
AIP-84 Migrate public endpoints from api_connexion to the new Rest API

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#42370]
### Body

https://github.com/apache/airflow/issues/42366 is taking care of migrating private endpoints.

This issue focuses on migrating all the public ones. Ideally they shouldn't change too much and be feature rich compare to airflow 2.x.

An exemple PR can be found here https://github.com/apache/airflow/pull/42196

####  Backfill (6 endpoints) @dstandish 
- `list_backfills` https://github.com/apache/airflow/pull/43496 @dstandish 
- `get_backfill` https://github.com/apache/airflow/pull/43496 @dstandish 
- `pause_backfill` https://github.com/apache/airflow/pull/43496 @dstandish 
- `unpause_backfill` https://github.com/apache/airflow/pull/43496 @dstandish 
- `cancel_backfill` https://github.com/apache/airflow/pull/43496 @dstandish 
- `create_backfill` https://github.com/apache/airflow/pull/43496 @dstandish 

#### Config (2 endpoints) @rawwar 
- https://github.com/apache/airflow/issues/42745 @jason810496 

#### Connection @bugraoz93  (6 endpoints)
- `api_connexion/endpoints/connection_endpoint.py` `delete_connection` https://github.com/apache/airflow/issues/42559 @bugraoz93 
- `api_connexion/endpoints/connection_endpoint.py` `get_connection` https://github.com/apache/airflow/issues/42590 @rawwar  
- `api_connexion/endpoints/connection_endpoint.py` `get_connections`  https://github.com/apache/airflow/issues/42591 @bugraoz93 
- `api_connexion/endpoints/connection_endpoint.py` `patch_connection` https://github.com/apache/airflow/issues/42592 @bugraoz93 
- `api_connexion/endpoints/connection_endpoint.py` `post_connection` https://github.com/apache/airflow/issues/42593 @bugraoz93 
- `api_connexion/endpoints/connection_endpoint.py` `test_connection` https://github.com/apache/airflow/issues/42594 @bugraoz93 

####  DAG (5 endpoints)
- `api_connexion/endpoints/dag_endpoint.py` `get_dag_details`  https://github.com/apache/airflow/issues/42453 @omkar-foss
- `api_connexion/endpoints/dag_endpoint.py` `patch_dag` https://github.com/apache/airflow/issues/42468 @pierrejeambrun 
- `api_connexion/endpoints/dag_endpoint.py` `patch_dags` https://github.com/apache/airflow/issues/42544 @pierrejeambrun 
- `api_connexion/endpoints/dag_endpoint.py` `get_dag` https://github.com/apache/airflow/issues/42652 @omkar-foss 
- `api_connexion/endpoints/dag_endpoint.py` `delete_dag` https://github.com/apache/airflow/issues/42650 @omkar-foss

#### Dag Parsing (1 endpoint)
- https://github.com/apache/airflow/pull/44416/ @prabhusneha 

#### Dag Runs @rawwar (9 endpoints)
- All dag run endpoints`api_connexion/endpoints/dag_run_endpoint.py` https://github.com/apache/airflow/issues/42701 @rawwar 

#### Dag Source (1 endpoint) 
- https://github.com/apache/airflow/issues/42876 @omkar-foss 

#### Dag Stats (1 endpoint)
- https://github.com/apache/airflow/issues/42877 @omkar-foss 

#### Dag Warnings (1 endpoint) @rawwar 
- https://github.com/apache/airflow/issues/42748 @rawwar 

#### Dataset / Assets (10 endpoints) @amoghrajesh
- `get_assets` https://github.com/apache/airflow/pull/43783 @amoghrajesh
- `get_asset` https://github.com/apache/airflow/pull/43825 @amoghrajesh 
- `get_upstream_asset_events` https://github.com/apache/airflow/pull/43874 @amoghrajesh
- `get_asset_events` https://github.com/apache/airflow/pull/43881 @vatsrahul1001
- `create_asset_event` https://github.com/apache/airflow/pull/43984 @vatsrahul1001 
- `get_asset_queued_events` https://github.com/apache/airflow/pull/44139 @vatsrahul1001 
- `delete_asset_queued_events` https://github.com/apache/airflow/pull/44138 @vatsrahul1001 
- `get_dag_asset_queued_events` https://github.com/apache/airflow/pull/44124 @amoghrajesh
- `delete_dag_asset_queued_events` https://github.com/apache/airflow/pull/44129 @amoghrajesh
- `delete_dag_asset_queued_event` https://github.com/apache/airflow/pull/44130 @amoghrajesh
- `get_dag_asset_queued_event` https://github.com/apache/airflow/pull/44128 @amoghrajesh

#### Event Logs (2 endpoints)

- https://github.com/apache/airflow/issues/43326 @jason810496 
- https://github.com/apache/airflow/issues/43327 @jason810496 

#### Extra Link (1 endpoint)
- https://github.com/apache/airflow/pull/44277 @prabhusneha

#### Monitor (2 endpoints) 
- https://github.com/apache/airflow/issues/42937 @bbovenzi
- https://github.com/apache/airflow/issues/42879 @omkar-foss 

#### Import Error (2 endpoints) @jason810496
- https://github.com/apache/airflow/issues/43594 @jason810496
https://github.com/apache/airflow/issues/43595 @jason810496

#### Log (1 endpoint)
- https://github.com/apache/airflow/pull/44238 @utkarsharma2 

#### Plugin (1 endpoint)
- https://github.com/apache/airflow/pull/43125 @pierrejeambrun 

#### Pool (5 endpoints) @pierrejeambrun
- https://github.com/apache/airflow/pull/43165 @pierrejeambrun 
- https://github.com/apache/airflow/pull/43221 @pierrejeambrun
- https://github.com/apache/airflow/pull/43223 @pierrejeambrun
- https://github.com/apache/airflow/pull/43266 @pierrejeambrun
- https://github.com/apache/airflow/pull/43317 @pierrejeambrun

#### Provider (1 endpoint)
 - https://github.com/apache/airflow/pull/43159 @pierrejeambrun

#### Task (2 endpoints) @omkar-foss 
- https://github.com/apache/airflow/issues/42874 @omkar-foss 
- https://github.com/apache/airflow/issues/42875 @omkar-foss 

#### Task Instance (15 endpoints) @pierrejeambrun
- https://github.com/apache/airflow/pull/43485 @pierrejeambrun 
- https://github.com/apache/airflow/pull/43548 @pierrejeambrun 
- https://github.com/apache/airflow/pull/43642 @pierrejeambrun 
- https://github.com/apache/airflow/issues/43748 @pierrejeambrun 
- https://github.com/apache/airflow/issues/43749 @pierrejeambrun
- https://github.com/apache/airflow/issues/43750 @pierrejeambrun
- https://github.com/apache/airflow/issues/43756 @pierrejeambrun
- https://github.com/apache/airflow/issues/43751 @omkar-foss 
- https://github.com/apache/airflow/issues/43753 @omkar-foss 
- https://github.com/apache/airflow/issues/43754 @omkar-foss 
- https://github.com/apache/airflow/issues/43752 @omkar-foss
-  https://github.com/apache/airflow/pull/43675 @kandharvishnu 
- https://github.com/apache/airflow/pull/44206 @kandharvishnu
- https://github.com/apache/airflow/pull/44301 @kandharvishnu  
- https://github.com/apache/airflow/pull/44303 @kandharvishnu

#### Variables (5 endpoints)
- https://github.com/apache/airflow/pull/42798 @pierrejeambrun 
- https://github.com/apache/airflow/pull/42834 @pierrejeambrun 
- https://github.com/apache/airflow/pull/42929 @pierrejeambrun 
- https://github.com/apache/airflow/pull/42948 @pierrejeambrun 
- https://github.com/apache/airflow/pull/43083 @pierrejeambrun 

#### XCom (2 endpoints)
- https://github.com/apache/airflow/issues/42978 @michaeljs-c 
- https://github.com/apache/airflow/issues/42980 @michaeljs-c 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by omkar-foss** [comment]
Trimming down `views.py` is very tempting 😄

May I pick this up? If yes, please assign this issue to me. Thanks!

**Comment by pierrejeambrun** [comment]
Hello @omkar-foss,

`views.py` are mostly 'rendered' front end that will get replaced by the new UI react or `private/UI` REST route, most of them are with the `/object/` prefix, such as `def grid_data`. If you want to work on those UI dedicated endpoints you can that would be part of https://github.com/apache/airflow/issues/42366.

This issue focuses on the public endpoints, those are located under the `api_connexion` folder.

In anycase, just mention the endpoint you are migrating so people do not do the same ones, and I will update the description to track that :).

**Comment by omkar-foss** [comment]
Hi @pierrejeambrun, thank you for explaining it to me, much appreciate it.

I'll start migrating the public endpoints, beginning with migration of the DAG Details API (`get_dag_details`) in `api_connexion/endpoints/dag_endpoint.py`.

Since this is a meta issue (missed that previously!), I'll create the issue/PR corresponding to the endpoint(s) that I'll be working on and link to this issue (like usual).

P.S: `views.py` will have to wait :)

**Comment by bugraoz93** [comment]
Thanks for creating the ticket @pierrejeambrun! Let me take connection endpoints

**Comment by pierrejeambrun** [comment]
Great, thanks @bugraoz93

**Comment by bugraoz93** [comment]
Thanks for assigning! Let me save you from regular updates :) I create for all the endpoints in connections.

**Comment by pierrejeambrun** [comment]
Great, thanks @bugraoz93. I just updated the meta issue with those new additions. Let me know if you plan to work on all of them so I can assign you, or just some of them so I can label them with `good first issue` and let other contributor grab them :)

**Comment by bugraoz93** [comment]
I am planning to work on all of them @pierrejeambrun. if you can assign them to me, that would be great! Thanks :)

**Comment by omkar-foss** [comment]
Hey folks! After https://github.com/apache/airflow/pull/42631 (open for review), I can pick up these two next in order:

1. `get_dag` - https://github.com/apache/airflow/issues/42652
2. `delete_dag` - https://github.com/apache/airflow/issues/42650

With these 2 done, I suppose we should have the `dags.py` migration complete. When you find some time, please update this meta and assign these to me, thank you! 😃

**Comment by bbovenzi** [comment]
@omkar-foss Assigned. Thanks for picking these issues up!

**Comment by rawwar** [comment]
I am working on the following 
1. get_connection - #42674 
2. get_connections - #42677

**Comment by omkar-foss** [comment]
Hey folks, just a heads-up on Pydantic aliases - try not to use `AliasGenerator` as it breaks Airflow lowest direct dependency resolution tests with a `TypeError` because lower versions of Pydantic wouldn't be having [this patch](https://github.com/pydantic/pydantic/pull/8806). The TypeError looks like `alias_generator ... must return str, not ...` (for more info see [this issue](https://github.com/pydantic/pydantic/issues/8768)).

Can use either `AliasChoices` or `AliasPath` as those work fine. I faced this issue in https://github.com/apache/airflow/pull/42631 and spent a while on it, so just thought should let you all know!

**Comment by potiuk** [comment]
> Hey folks, just a heads-up on Pydantic aliases - try not to use AliasGenerator as it breaks Airflow lowest direct 

We can also update the minimum version of Pydantic to the version that is fixed. This is the feature of the "lowest direct" tests that they detect such minimum requirements are not met. So maybe you can figure out which is the minimum version and we set it @omkar-foss ?

**Comment by omkar-foss** [comment]
>This is the feature of the "lowest direct" tests that they detect such minimum requirements are not met.

It's a very cool feature! Helping to find issues we normally wouldn't find during regular unit or integration tests.

>We can also update the minimum version of Pydantic to the version that is fixed.
>So maybe you can figure out which is the minimum version and we set it

That would be great, the minimum Pydantic version that is fixed is v2.6.4, [this commit](https://github.com/pydantic/pydantic/commit/6214a4bc472bfc4cd72232ab5d407dc640dc64aa#diff-648afe3d986261d8f2015b2b131b0e4a448d4dc6946cfde1a7a836876cee255eR9) for quick reference.

**Comment by potiuk** [comment]
> That would be great, the minimum Pydantic version that is fixed is v2.6.4, [this commit](https://github.com/pydantic/pydantic/commit/6214a4bc472bfc4cd72232ab5d407dc640dc64aa#diff-648afe3d986261d8f2015b2b131b0e4a448d4dc6946cfde1a7a836876cee255eR9) for quick reference.

Added min version for Pydantic in https://github.com/apache/airflow/pull/42694

**Comment by pierrejeambrun** [comment]
@rawwar 

> I am working on the following

> get_connection - https://github.com/apache/airflow/pull/42674
> get_connections - AIP-84 Migrate the public endpoint Get Connections to FastAPI  #42677`

Thanks for your contribution and help on AIP-84, as mentioned above, I think @bugraoz93 is already working on connections endpoints, or is planning to do so. Feel free to grab any other endpoints that looks cool to you, under `api_connexions/endpoints`. Besides `dag_endpoint` and `connection_endpoint` eveything is up for a grab.

**Comment by pierrejeambrun** [comment]
Assigning myself to variables

**Comment by omkar-foss** [comment]
I've created new issues for sections Dag Source (1 endpoint), Dag Stats (1 endpoint), Task (2 endpoints) and Version (1 endpoint). List as below:

1. https://github.com/apache/airflow/issues/42876
2. https://github.com/apache/airflow/issues/42877
3. https://github.com/apache/airflow/issues/42874
4. https://github.com/apache/airflow/issues/42875
5. https://github.com/apache/airflow/issues/42879

Please assign these to me, I'll pick these up one by one in the next few days, right after https://github.com/apache/airflow/issues/42650. Cheers.

**Comment by pierrejeambrun** [comment]
@omkar-foss assigned and meta issue updated, thanks :)

**Comment by michaeljs-c** [comment]
Hi @pierrejeambrun I've added issues for XCom, please assign to me 🙂 thanks

**Comment by jason810496** [comment]
Hi @pierrejeambrun, I can take on the migrations for **Event Logs**:
1. Get Event Log
2. Get Event Logs

However, none of the current issue form templates fit a task issue (the `Task and Meta` template tags the issue with `kind:meta` instead of `kind:feature`).
Could you please create the issue and assign it to me? Thanks!

**Comment by jason810496** [comment]
Hi @pierrejeambrun, the changes look good to me, but I have another question:

When should I utilize a parameter class (the classes declared in `common/parameters.py` with `to_orm` and `depends` methods) instead of adding query parameters directly (like `dag_runs_limit: int = 10` in this case)?

For example, in the Event Log endpoints, the query should leverage `paginated_select`, but the `paginated_select` function depends on a parameter class rather than query parameters. In this case, should I declare all filter classes in `common/parameters.py`, or would it be better to add a `FilterParam` with `dynamic_depends`, similar to `SortParam`, that could be used across all endpoints?

**Comment by jason810496** [comment]
Hi @pierrejeambrun, I can handle the migrations for **Import Error**

1. `get_import_error`
2. `get_import_errors`

I’m still encountering the issue where I can’t create the correct issue type.
Could you please create it and assign it to me? Thanks!

**Comment by rawwar** [comment]
I've unassigned myself for the config endpoint issue. If no one takes it, I'll pick it up once I finish DagRun and DagWarning endpoints. 
Issue: https://github.com/apache/airflow/issues/42745 <- If anyone wants to take this, please let me know and I can assign it to you.

**Comment by kandharvishnuu** [comment]
@pierrejeambrun I am working on `get taskinstance try` endpoint

**Comment by omkar-foss** [comment]
Hi @pierrejeambrun, could you please assign these TI-related endpoints to me in above issue description:

**GET:**
- https://github.com/apache/airflow/issues/43748
- https://github.com/apache/airflow/issues/43749
- https://github.com/apache/airflow/issues/43750
- https://github.com/apache/airflow/issues/43756

**POST:**
- https://github.com/apache/airflow/issues/43751

**PUT:**
- https://github.com/apache/airflow/issues/43753
- https://github.com/apache/airflow/issues/43754
- https://github.com/apache/airflow/issues/43755
- https://github.com/apache/airflow/issues/43752

**Comment by pierrejeambrun** [comment]
You're assigned, issue updated, let me know if that shounds good for you :).

**Comment by omkar-foss** [comment]
> You're assigned, issue updated, let me know if that shounds good for you :).

Yes sure, that works. Thank you :)

**Comment by bbovenzi** [comment]
@prabhusneha I see you're assigned to Logs. What is the status of getting the logs for a task instance? That would be a useful one to get in the UI soon!

**Comment by utkarsharma2** [comment]
> @prabhusneha I see you're assigned to Logs. What is the status of getting the logs for a task instance? That would be a useful one to get in the UI soon!

Hey, @bbovenzi I'm taking care of `task instance logs` endpoint, I'm mostly done with it, but there are a couple of test cases that require setting users in fastapi which requires a little more work. I'll keep you posted.

**Comment by phanikumv** [comment]
Thanks @utkarsharma2  (updated the description accordingly).
