### ISSUE TITLE
Add heartbeat metric for DAG processor

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#42380]
### Description

The scheduler emits a `scheduler_heartbeat`, which makes it easy to determine if the scheduler is up and running. We should add an equivalent for the DAG processor.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shalberd** [comment]
thank you, @jedcunningham @rawwar @potiuk nice catch in 2.10.3, though it did not make it into release notes, it seems. https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-10-3-2024-11-04
Can you confirm this change is in release 2.10.3?
