### ISSUE TITLE
Add SageMakerProcessingSensor

### ISSUE THREAD

**Issue by anneadb** [apache/airflow#42411]
### Description

Hi,
we would like to switch our Sagemaker pipelines to Airflow pipelines.
There are already many useful operators and sensors - however, the sensor for processing jobs is missing. Could this be added?

All current sensors are listed here: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/sensors/sagemaker/index.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
How is that different than `SageMakerPipelineSensor`?

**Comment by vVv-AA** [comment]
@Lee-W Have raised PR for this. Please review when you can.
https://github.com/apache/airflow/pull/43144

**Comment by anneadb** [comment]
Thank you so much for implementing this!
How does the release process usually work, will this be included in the next minor automatically?

**Comment by vincbeck** [comment]
Yes, in the next providers release
