### ISSUE TITLE
Redact secrets from external secrets provider

### ISSUE THREAD

**Issue by stuart23** [apache/airflow#42420]
### Apache Airflow version

2.10.1

### What happened?

When using a third party secrets backend (e.g. AWS Secrets Manager), secret values are not redacted from task logs and appear as plaintext in the logs.

### What you think should happen instead?

When writing task logs, the worker should list all the secret values from the backend and add that to the list of things to redact.

### How to reproduce

Connect a secrets backend e.g. [AWS Secrets Manager](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/secrets_manager/index.html#module-airflow.providers.amazon.aws.secrets.secrets_manager)
Print a value from the backend - the plaintext will appear in the task logs

### Operating System

N/A

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by wseaton** [comment]
Not just secret values, it is also important that bootstrap variables for secrets manager configuration like `AIRFLOW__SECRETS__BACKEND_KWARGS` can be masked in task logs, since they are visible to the workers.

**Comment by potiuk** [comment]
Could. you please clarify and show examples of what values you are talking about ? Airflow does not mask "ALL" values retrieved from secret backends only those that are considered "sensitive" - see https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/mask-sensitive-values.html. In many cases Secrets backend are used to keep non-sensitive configuration and those non-sensitive values are not masked.

So examples and explanation why things should be masked and aren't ?
