### ISSUE TITLE
Implicit exception in `GCSToLocalFilesystemOperator` when reading non-existing files

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#42439]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

10.15.0

### Apache Airflow version

2.6.3

### Operating System

Debian

### Deployment

Google Cloud Composer

### What happened

When using `GCSToLocalFilesystemOperator` on a non-existing object, the resulted exception is regarding a `NoneType` object with no `size` attribute - which is True, but it would be better to raise an exception that the file simply does not exist.

### How to reproduce

Use the `GCSToLocalFilesystemOperator` with a non-existing `OBJECT_NAME`
```python
    gcs_to_fs = GCSToLocalFilesystemOperator(
        task_id="gcs_to_fs",
        bucket=BUCKET,  # <- exists
        object_name=OBJECT_NAME, # <- does not exist
    )
```
You'll get an exception similar to this:

```
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/gcs_to_local.py", line 118, in execute
    file_size = hook.get_size(bucket_name=self.bucket, object_name=self.object_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 968, in get_size
    blob_size = blob.size
                ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'size'
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jsjasonseba** [comment]
Hi @shahar1, I’d like to take this issue. I plan to create a custom exception inheriting from AirflowException and raise it. Any suggestions?

**Comment by shahar1** [comment]
> Hi @shahar1, I’d like to take this issue. I plan to create a custom exception inheriting from AirflowException and raise it. Any suggestions?

Thanks for your willing to contribute!
I just assigned you this issue.
I'd avoid for now creating a customized exception class, as no other classes in this provider do so.
Please ping me in the PR when you're ready :)
