### ISSUE TITLE
Inconsistent log formatting in (TaskDetail) Logs and (See more) Log tabs

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#42440]
### Apache Airflow version

2.10.1

### If "Other Airflow 2 version" selected, which one?

2.10.2

### What happened?

In the Logs tab, the colors for warnings and errors are used in the log text (see the pict)
![image](https://github.com/user-attachments/assets/c9c78c0b-b2cb-4835-a256-575669fded60)

But if you display the log using See more, the text will be displayed without colour formatting (see the pict of the very same log)
![image](https://github.com/user-attachments/assets/f0e328c7-40a4-49fa-b077-e65a88698ea7)

### What you think should happen instead?

The log text should be displayed equally (with colored formating) in both places

### How to reproduce

View the task log with warnings and/or errors in the task detail, and then view it using the View More feature.

### Operating System

Kubernetes on Unix platform

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
This was intentional since legacy log page doesn't process logs line by line like log tab. The processing is done on client side. The legacy logs page is planned to be removed so there won't be much development to add this feature.

https://github.com/apache/airflow/pull/39006#issuecomment-2067480912

**Comment by Pad71** [comment]
@tirkarthi  Ok, thanks for the information. Closing this issue.

**Comment by Pad71** [comment]
create or replace view v_sla_definitions as
select
   DEF.ID as SLA_ID
 , DEF.NAME
 , DEF.DESCR
 , DEF.SLA_TYPE_ID
 , CONA.NAME as CONTEXT_AREA
 , CON.NAME  as CONTEXT
 , TARG.NAME as TARGET
 , TARG.SLA_TARGET_TYPE_ID as TARGET_TYPE
 , DEF.SLA_PERIOD_ID
 , DEF.SLA_START_TYPE_ID
 , DEF.SLA_START_TYPE_CUST_PAR
 , DEF.SLA_END_TYPE_ID
 , DEF.SLA_END_TYPE_CUST_PAR
 , DEF.MAX_DURATION
 , DEF.SLA_DURATION_UNIT_ID
from SLA_DEFINITION DEF
join SLA_CONTEXT CON on DEF.SLA_CONTEXT_ID = CON.ID
join SLA_CONTEXT_AREA CONA on CON.SLA_CONTEXT_AREA_ID = CONA.ID
join SLA_TARGET TARG on DEF.SLA_TARGET_ID = TARG.ID
order by DEF.ID;
