### ISSUE TITLE
WasbHook needs a copy_object method in Airflow

### ISSUE THREAD

**Issue by kunaljubce** [apache/airflow#42497]
### Description

Currently we have a `copy_object` method for S3Hook. It would be beneficial to have a similar method for WasbHook to be able to copy blob objects seamlessly in Azure. 

### Use case/motivation

To be able to seamlessly copy blob objects from one Blob container to another within the same Azure storage account. We can also add the native support to copy objects across different storage accounts with an optional parameter. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kunaljubce** [comment]
I am working on this, please assign this to me if the feature looks like a reasonable value add.

**Comment by kunaljubce** [comment]
The cross-storage account functionality has an added layer of complexity since, unlike in AWS, Azure implements a 3 tiered folder structure. 

AWS: Account (Auth) --> S3 Bucket --> Prefix --> Keys
Azure: Account (Auth) --> Storage Account (Auth) --> Containers --> Blob Prefix --> Blob objects

In Azure, due to the need to have authentication setup at a storage account level, it becomes imperative to create different instances of WasbHook for different storage accounts, which is not the case in AWS with the S3Hook. My plan is to handle this with an optional parameter, wherein users can mention the destination storage account details/hook for the dest storage account and the file copy would happen accordingly. 

Please let me know your thoughts!

**Comment by Lee-W** [comment]
roughly read though it. looks like a good idea. I just assigned it to you. Thanks

**Comment by kunaljubce** [comment]
@Lee-W The PR is up for review now.
