### ISSUE TITLE
Snowflake connection UI does not hide private_key_content in the Extra field and in the Private key (Text) field

### ISSUE THREAD

**Issue by TJaniF** [apache/airflow#42496]
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

apache-airflow-providers-snowflake==5.7.1

### Apache Airflow version

2.10.2

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Astronomer

### What happened

Noticed that the private_key_content as well as the Private key (Text) field are not masked upon editing a connection

![image](https://github.com/user-attachments/assets/0c5fad9e-8b14-4f9e-a9fa-587e14fd608e)

(also the Private key (Text) field displays error and warning icons for valid keys, probably trying to display JSON)

### What you think should happen instead

I think it should be masked in the text field and use `RATHER_LONG_SENSITIVE_FIELD_PLACEHOLDER` in the Extra field
Also it should not display warning icons for a valid key.

### How to reproduce

1. Create a Snowflake connection in the Airflow UI
2. paste a value in the Private Key (Text) field
3. Save the connection
4. Edit the connection
5. See the key

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
@potiuk , wondering if it's possible to hide private_key_content in the Extra field?  The only way I see it is by making extra field sensitive.

**Comment by potiuk** [comment]
> @potiuk , wondering if it's possible to hide private_key_content in the Extra field? The only way I see it is by making extra field sensitive.

Yes. Your PR implemented what's needed. Will be released in the next snowflake provider.
