### ISSUE TITLE
Kubernetes Pod Operator Init container logging

### ISSUE THREAD

**Issue by johnhoran** [apache/airflow#42498]
### Description

When writing a pod using an init container, I notice that you don't get any logs from the init container.  I tried adding the name of the init container to the container_logs option in KubernetesPodOperator, but it complains that the container couldn't be found.  
I also noticed that the airflow would say the pod was pending while the init container process was running.  

### Use case/motivation

- When init containers are running the task should be consider running.
- Logs from init containers should be shown 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Thanks for the proposal - I think is is a valid feature! If you implement it, you might make this configurable, maybe not everybody wants logs, maybe some only on error?
