### ISSUE TITLE
use charts libary that allows commercial use instead of highcharts.js

### ISSUE THREAD

**Issue by LilithWittmann** [apache/airflow#425]
I know highcharts.js is really cool but doesn't allow commercial use in the cost-free version. The highcharts.js [license faq](http://shop.highsoft.com/faq/non-commercial) says:

> IF I AM USING THE SOFTWARE ON A COMMERCIAL COMPANY'S INTRANET, DOES IT REQUIRE A LICENSE
> Yes. The Developers License allows you to install and use the software on commercial company's intranet.

So every company that wants to use airflow has to pay 390$ for a highchart developer license?
Maybe it would be an option to replace highcharts with chart.js or d3.js?

**Comment by neovintage** [comment]
I would recommend http://metricsgraphicsjs.org/ for this. The mozilla license is a bit more favorable.

**Comment by mistercrunch** [comment]
It looks like Highchart's definition of "non-commercial" isn't what I though it was. I'm not even sure it's in line with the creative commons specs. We also might be able to get a blessing from them, though it might just be easier to rip it out. 

I've used this lib before: http://nvd3.org/

**Comment by LilithWittmann** [comment]
Ok I will try to replace highcharts with one of these libraries (and maybe refactor the javascript part a bit ;-) )

**Comment by mistercrunch** [comment]
Oh wow! that is ambitious. Sorry about my javascript :)

**Comment by LilithWittmann** [comment]
Ok, I (re)implemented some of the chart types:
- line
- bar (grouped, stacked)
- column (grouped, stacked)
- stacked area (stacked, stream, expanded)

but I have no idea how to implement the others (esp. heatmap and parallel coordinates) with nvd3 /o\
You can find my branch here: https://github.com/LilithWittmann/airflow/tree/new_chart_libary

**Comment by mistercrunch** [comment]
Nice!

Parallel coordinate is one of those d3 examples, the license looks ok there. For heatmap we can probably just remove the feature.

Now there's a few views in the application itself (landing times and duration charts). The Gantt chart might be a git more tricky but it isn't too hard to reproduce while hacking a line chart. I'm hoping I can get to this sometime next week.

**Comment by mistercrunch** [comment]
I pulled the branch and opened a dozen of charts on my end and only a few actually worked. I'll have to dig in and do some work to make this work.

**Comment by bolkedebruin** [comment]
d3 implementation is underway also as requirement to do apache releases.
