### ISSUE TITLE
[Airbyte] Airflow Airbyte provider 4.0 not allowing disabled auth and does not work with auth

### ISSUE THREAD

**Issue by baugarcia** [apache/airflow#42520]
### Apache Airflow Provider(s)

airbyte

### Versions of Apache Airflow Providers

apache-airflow-providers-airbyte | 4.0.0

### Apache Airflow version

2.8.1

### Operating System

AWS MWAA

### Deployment

Amazon (AWS) MWAA

### Deployment details

Nothing really relevant. Standard AWS MWAA installation. 

### What happened

There are two issues with the version 4.0.0 of the airbyte provider:

1 - In the airbyte provider, there is no use case for disabling authentication as an OSS instalation. You are being forced to enable authentication and pass the client_id and client_secret

2 - It does not seem to get the authentication token. Even after enabling auth and creating the user application and using the client_id and client_secret, it just gets a 404 error. None of the documented endpoints, either in airbyte or the airflow provider code/guidelines seem to work. We have also tried multiple iterations of endpoints, such as /api, /api/v1. /api/public/v1/.... in both the host and/or the Token URL (also tested with v1/applications/token):

```
[2024-09-26, 15:41:37 UTC] {{taskinstance.py:2698}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 157, in submit_sync_connection
    res = self.airbyte_api.jobs.create_job(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airbyte_api/jobs.py", line 100, in create_job
    raise e
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airbyte_api/jobs.py", line 95, in create_job
    req = self.sdk_configuration.get_hooks().before_request(BeforeRequestContext(hook_ctx), req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airbyte_api/_hooks/sdkhooks.py", line 41, in before_request
    out = hook.before_request(hook_ctx, request)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airbyte_api/_hooks/clientcredentials.py", line 59, in before_request
    sess = self.do_token_request(credentials, self.get_scopes(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airbyte_api/_hooks/clientcredentials.py", line 122, in do_token_request
    raise Exception(
Exception: Unexpected status code 404 from token endpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 83, in execute
    job_object = hook.submit_sync_connection(connection_id=self.connection_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 165, in submit_sync_connection
    raise AirflowException(e)
airflow.exceptions.AirflowException: Unexpected status code 404 from token endpoint
``` 

### What you think should happen instead

1 - There should be a use case for an OSS instalation with disabled authentication. No token needed to connect.
2 - Not have a 404 error. Or document clearly what you should input in the fields, if we are doing something wrong.

### How to reproduce

1 - Newest install of OSS Airbyte with authentication disabled. You don't have the /applications endpoint, so you cannot get a token and therefore use the provider
2 -  Install newest OSS Airbyte, use airflow's airbyte 4.0.0 provider, try to connect and submit a job using the client_id and client_secret, as well as the Token-URL and host fields.

### Anything else

Every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by querbesd** [comment]
Hello, 
I have exactly the same issue (OSS instalation and version 4.0.0 of the airbyte provide).

**Comment by ShelRoman** [comment]
Hello @baugarcia 
Could you please share how did you resolve this issue?

**Comment by amardatar** [comment]
If you use the "Token URL" `api/v1/applications/token` then I think that will deal with the 404 at least, but instead I get a 401. I've created an issue https://github.com/airbytehq/airbyte-api-python-sdk/issues/112 to track, since the core problem seems to be from the airbyte-api SDK, rather than from the provider.

Alternatively, the airbyte-api SDK _does_ seem to work with username/password auth, so possibly the change could still be made here in the provider, with the option to auth using username/password for OSS users?

**Comment by amardatar** [comment]
For anyone looking for a workaround - this is a little involved, but I've got it working by making the following changes:

The connection in Airflow has the details:
Host: `<your airbyte domain>/api/public/v1`
Token URL: `v1/applications/token`
Client ID: `<your client ID>`
Client Secret: `<your client secret>`

And the clientcredentials.py file needs to be updated [here](https://github.com/airbytehq/airbyte-api-python-sdk/blob/048c847914113b75a246ce122fe1cce4f48fee64/src/airbyte_api/_hooks/clientcredentials.py#L119) from `data=payload` to `data=json.dumps(payload)` (you'll also need to `import json` at the top of the file). Up to you how you do this - I created a copy of the file in my repo, and then use that to replace the normally installed file in my Dockerfile, i.e. something like `COPY clientcredentials.py /home/airflow/.local/lib/python3.12/site-packages/airbyte_api/_hooks/clientcredentials.py`.

Obviously - wouldn't recommend this unless you know what you're doing, fairly high chance of something breaking at some point.

**Comment by NahidOulmi** [comment]
For those who are encountering this issue, a quickfix I did was to use the `apache-airflow-providers-airbyte` package version  3.0.0 instead of version >=4.0.0. With this version authentication is not necessary.

**Comment by CrisNavasM** [comment]
You may also add this as well at the top of your DAGs

```python
import airbyte_api._hooks.clientcredentials as _cc
_cc.ClientCredentialsHook.get_credentials = lambda self, source: None
```

So you can keep an up to date version of the Airflow operators
