### ISSUE TITLE
AIP-84 Migrate the public endpoint Get Connection to FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#42590]
### Description

Migrate the 'GET' connection to Fast API.

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
I would like to work on this issue.

**Comment by pierrejeambrun** [comment]
@rawwar Thanks for your PR. I think @bugraoz93 is taking care of other `Connection` related endpoints. You are more than welcome to continue helping with AIP-84, there are plenty of other endpoints to migrate, you can find them under `api_connexion/endpoints` for instance `DagRun`, `Pool` etc...

Let me know if you want to work on any of them so I can assign you :)

**Comment by rawwar** [comment]
I apologize for not looking through history and picking up this issue on a whim.  @bugraoz93 , I've initiated PRs to get a connection and list connection. I am closing the list of connections PR as that's just a draft. 

@pierrejeambrun , thanks so much!

**Comment by bugraoz93** [comment]
Thanks @pierrejeambrun! (No problem :) :pray:) 

Thanks for jumping in @rawwar! We need all the help we can get. No problem at all, there is a huge backlog we should cover anyway :)
