### ISSUE TITLE
AIP-84 Migrate /object/grid_data from views to FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#42595]
### Description

Migrate `views` `/object/grid_data` to Fast API.

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42366

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
I mentioned in the main epic how we want to refactor this endpoint. I think we can have `graph_data` handle all of the task order and structure as I mentioned in #42367. Then we can simplify `grid_data` to only include dag run history. Each dag run includes an array of all its task instances. 

Also, it would be nice to calculate summaries of mapped tasks and task groups (determine the overall state, give a breakdown of counts of children states, determine earliest queued, earliest start_date and latest end_date). 

By separting runs from the task structure we can add pagination and filtering to the`dag_runs_with_task_summaries` endpoint, then we can do stuff like only refresh on active dag runs.

**Comment by bugraoz93** [comment]
@bbovenzi I am not sure if I grasp all the parts. I will work on this and create a PR soon. Let's discuss in the PR to make this work how you imagined

**Comment by bbovenzi** [comment]
That's alright. This is a complicated endpoint. Something like:

```
[{
  version_number?: number
  data_enterval_end?: string | null;
  data_interval_start?: string | null;
  end_date?: string | null;
  run_id: string;
  run_type: string;
  queued_at?: string | null;
  start_date?: string | null;
  state: string;
  task_instances?: TaskInstanceSummary[];
}]
```


Where the `TaskInstanceSummary` can be either a single task instance, or summarizing multiple tasks as a Task Group or Mapped Task. For a summary, we need:

```
  end_date: string | null; // latest end date
  overall_state: string | null // Check `priority` in `airflow/www/utils.py`
  start_date: string | null; // earliest start date
  queued_at: string | null // earliest queued at date
  task_count: number; // total number of children tasks inside this group or mapped task
  states: // dict of states and the number of tasks with each state
  task_id: string;
  try_number: number;
 ```

**Comment by bugraoz93** [comment]
Thanks for the details! It's clear now.
