### ISSUE TITLE
GCSToGCSOperator is not able to copy files with wildcard to destination bucket in airflow 2.7.3 version

### ISSUE THREAD

**Issue by shyamshaw** [apache/airflow#42615]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.12.0

### Apache Airflow version

2.7.3

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### How to reproduce

`from datetime import timedelta, datetime
from airflow import DAG
from airflow.providers.google.cloud.transfers.gcs_to_gcs import GCSToGCSOperator
 
CONN_ID = 'bfddxvenu1-dev-sa1'
SOURCE_BUCKET =  'bfdaf-dags-bfddxvenu1-test-sm'
DESTINATION_BUCKET =  'bfdaf-dags-bfddxvenu1-test-sm'
 
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2022, 1, 1),
    'email': ['shyam.shaw@gmail.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}
 
dag = DAG(
    'move_gcs_files',
    default_args=default_args,
    description='A simple DAG to move files from one GCS bucket to another',
    schedule_interval=None,
)
 
move_files = GCSToGCSOperator(
    task_id='move_files',
    source_bucket=SOURCE_BUCKET,
    source_object='load/incremental/ca/*.csv',
    destination_bucket=DESTINATION_BUCKET,
    destination_object='processing/incremental/ca/',
    move_object=True,
    dag=dag,
    gcp_conn_id=CONN_ID
)
 
move_files`

Airflow task is marking as SUCCESS however files are not getting copied to destination bucket. This works fine with airflow 2.4.3 version and apache-airflow-providers-google==8.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
`apache-airflow-providers-google==10.12.0` is almost a year old. After connecting with @kandharvishnu, I believe this issue has been resolved in `apache-airflow-providers-google>=10.18.0` -- Is that correct?

**Comment by shyamshaw** [comment]
@RNHTTR 

Yes, it seems issue has been resolved in `apache-airflow-providers-google>=10.18.0` 
I could not find any bug or behaviour changes related to this issue as it was working in previous version of `apache-airflow-providers-google`

**Comment by RNHTTR** [comment]
Got it. Since this is already fixed, I'm going to close this out.
