### ISSUE TITLE
MsSQLHook and pymssql Adaptive Server connection failed

### ISSUE THREAD

**Issue by ghost** [apache/airflow#42642]
### Apache Airflow version

2.10.2

### What happened?

Connecting to mssql server caused an adaptive server issue and database could not be accessed.

> pymssql.exceptions.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed

### What you think should happen instead?

Connection hook should be successful if the Airflow connection variable is readable and filled in correctly.

Logs below:

> [2024-10-02, 02:05:48 UTC] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1884, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed \n')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/etl/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/etl/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/etl/anaconda3/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/etl/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/etl/airflow/dags/platypus_etl/mssqltopostgresoperator.py", line 59, in execute
    with closing(source.get_conn()) as conn:
  File "/home/etl/anaconda3/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 98, in get_conn
    conn = pymssql.connect(
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed

### How to reproduce

apache-airflow-providers-microsoft-mssql-3.9.1
pymssql-2.3.1
apache-airflow-providers-common-sql-1.17.1

Use MsSQL hook to connect to database using a MSSQL connection from the Airflow connection menu.

### Operating System

CentOS 7

### Versions of Apache Airflow Providers

apache-airflow-providers-microsoft-mssql-3.9.1
pymssql-2.3.1
apache-airflow-providers-common-sql-1.17.1

### Deployment

Virtualenv installation

### Anything else?

Problem occurs using apache-airflow-providers-microsoft-mssql-3.9.1 and pymssql-2.3.1 and apache-airflow-providers-common-sql-1.17.1

Reverting back to  apache-airflow-providers-microsoft-mssql-3.4.2, pymssql-2.2.4  and apache-airflow-providers-common-sql-1.7.2 fixed my issue.

See similar issue here: https://github.com/pymssql/pymssql/issues/913

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gordthompson** [comment]
@anthony-joyce - As in https://github.com/pymssql/pymssql/issues/913 , are you using an environment variable similar to this?

```bash
export AIRFLOW_CONN_MSSQL_DEFAULT='mssql+pymssql://usr:pwd@server.example.com/dbname'
```

**Comment by anthony-joyce** [comment]
@gordthompson Hi Gord. Thanks for the reply. I am not, currently. I was using the connection variable from the Airflow environment (Airflow menu --> Connections). Unless that connection is getting rendered incorrectly before being passed to mssql.....

Should I be using an environment variable similar to what you have posted?

Thanks!

**Comment by gordthompson** [comment]
I have zero experience with Airflow so I don't know the best approach to use in your case. I was really asking if you were using a connection URL of that form. If you were, then I would suggest trying

```
mssql+pymssql://usr:pwd@server.example.com/dbname?tds_version=7.0
```

to see if that helps. Can you add the extra `tds_version` connection parameter using your method?

**Comment by anthony-joyce** [comment]
Added {tds_version: 7.0} to the connection but still receiving errors. I definitely thank you for the help but I as well am trying to figure out my issue with very little understanding how Airflow renders those connection options. 

Hopefully others will chime in as the is getting triaged. Thanks again @gordthompson.
