### ISSUE TITLE
In MsSqlHook, SQLAlchemy engine scheme is overriden by the change in #40669

### ISSUE THREAD

**Issue by emredjan** [apache/airflow#42664]
### Apache Airflow Provider(s)

common-sql

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.16.0
apache-airflow-providers-microsoft-mssql==3.9.0
apache-airflow-providers-odbc==4.7.0

### Apache Airflow version

2.10.2

### Operating System

RHEL 8.10

### Deployment

Virtualenv installation

### What happened

We're using mssql+pyodbc connections in airflow to connect to our MS SQL Server. We're creating a hook using `MsSqlHook` and using `.get_sqlalchemy_engine()` to get an sql alchemy engine object to pass along our database tasks.
Prior to apache-airflow-providers-common-sql 1.15.0, this was working as expected (last known working version is 1.14.1, please see below for a working example)
With a change introduced in 1.15.0 (https://github.com/apache/airflow/pull/40669), `.get_sqlalchemy_engine()` passes the `creator` argument with the value `self.get_conn` to the `.create_engine()` function, which overrides the engine creation with the default connection scheme, which uses `pymssql`, even though we specifically define the scheme as `pyodbc` in the connection, and in the hook.

Resulting engine object becomes a weird combination of two, with a `mssql+pyodbc` scheme in the connection uri, but tries to connect to using the `pymssql` dialect internally, which results in fatal errors:

![image](https://github.com/user-attachments/assets/bd25e5d4-c8d0-4e12-8177-e1467dd9f57c)

As if it's trying to make a `pymssql` connection, but with a `pyodbc` URL.

### What you think should happen instead

The connection should work, as it does prior to the change.

![image](https://github.com/user-attachments/assets/dbc176e6-2817-42cc-95a7-767161059e3c)

If we comment out / delete the line `engine_kwargs["creator"] = self.get_conn` in `‎airflow/providers/common/sql/hooks/sql.py` (https://github.com/apache/airflow/commit/f6c7388cfa70874d84f312a5859a4f510fef0084#diff-6e1b2f961cb951d05d66d2d814ef5f6d8f8bf8f43c40fb5d40e27a031fed8dd7R246), connections works as expected.

### How to reproduce

This is the connection that's used (values changed for privacy)

Basically use any MSSQL connection with a `mssql+pyodbc` scheme

```
{
    "conn_type": "mssql",
    "host": "<redacted>",
    "login": "user",
    "password": "pass",
    "schema": "master",
    "port": 1433,
    "extra": {
        "driver": "ODBC Driver 18 for SQL Server",
        "encrypt": "yes",
        "sqlalchemy_scheme": "mssql+pyodbc"
    }
}
```

Try to connect through a hook and sqlalchemy engine:

```python
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
hook = MsSqlHook(mssql_conn_id='conn1')  # conn1: the id for above connection
#hook = MsSqlHook(mssql_conn_id='conn1', sqlalchemy_scheme='mssql+pyodbc') # optional, same result
engine = hook.get_sqlalchemy_engine()
engine.connect()
```

This fails on > 1.15.0
Works on <= 1.14.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dabla** [comment]
Weird, because we are also using MSSQL with ODBC and are using the get_sqlalchemy_engine() method as well and having the same connection config as you posted without issues.

**Comment by emredjan** [comment]
> Weird, because we are also using MSSQL with ODBC and are using the get_sqlalchemy_engine() method as well and having the same connection config as you posted without issues.

Are you using `"sqlalchemy_scheme": "mssql+pyodbc"` in the connection or the hook? Or you just use the ODBC Driver with the default SQLAlchemy scheme (`mssql+pymssql`)

**Comment by dabla** [comment]
This error is weird, but now I understand why, what you are doing is wrong, and in the past this wouldn't have caused any issues, but now it is.

Don't do this as you show above:

```
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
hook = MsSqlHook(mssql_conn_id='conn1')  # conn1: the id for above connection
#hook = MsSqlHook(mssql_conn_id='conn1', sqlalchemy_scheme='mssql+pyodbc') # optional, same result
engine = hook.get_sqlalchemy_engine()
engine.connect()
```

But do this, as this will work:

```
hook = DbAphiHook.get_hook(conn_id='conn1')
engine = hook.get_sqlalchemy_engine()
engine.connect()
```

I will explain why your example fails now.  As you stated, you use MSSQL through ODBC connection (and thus ODBC driver), but in your example you use the MsSqlHook instead of OdbcHook, so here you try to us an ODBC connection with a PyMSSQL based hook (e.g. MsSqlHook), which of course won't work.  It could have worked in the past but then you were lucky, now it won't as the get_sqlalchemy_engine method is now a generic method in DbApiHook which isn't overridden anymore in MsSqlHook.

**Important:**: It is always a good practice not to instantiate the specialized hook yourself, it's better to use the DbAphiHook.get_hook classmethod, as this will return you the specialized hook depending on the connection type of the connection id you passed.

So please try my suggestion and let me know.

**Comment by dabla** [comment]
> > Weird, because we are also using MSSQL with ODBC and are using the get_sqlalchemy_engine() method as well and having the same connection config as you posted without issues.
> 
> Are you using `"sqlalchemy_scheme": "mssql+pyodbc"` in the connection or the hook? Or you just use the ODBC Driver with the default SQLAlchemy scheme (`mssql+pymssql`)

Yes, I also defined the "sqlalchemy_scheme": "mssql+pyodbc" in the extra of the connection as you showed above, the configuration of you connection is correct, but the instantiation of the hook isn't.  Please check my answer above.

**Comment by emredjan** [comment]
Tried this:

```python
from airflow.providers.common.sql.hooks.sql import DbApiHook
hook = DbApiHook.get_hook(conn_id='conn1')
engine = hook.get_sqlalchemy_engine()
engine.connect()
```

It results in the same error as above: `AttributeError: 'pymssql._pymssql.Connection' object has no attribute 'add_output_converter'`

While I understand `DbApiHook.get_hook()` is the proper way to instantiate a database hook, it just creates a `MsSqlHook` with the same parameters as above. In practice, nothing changes on the engine creation side with `.get_sqlalchemy_engine()`.

As I don't use any other databases, I'm not entirely sure about the passing the connection to the engine with the `creator` argument (`engine_kwargs["creator"] = self.get_conn`), but that causes any connection parameters to be ignored. As the passed connection with the `get_conn` just returns the default MS SQL connection with pymssql as it creates a basic connection, any other scheme or other parameters in the connection are bypassed. See the `get_conn` definition:

```python
def get_conn(self):
    """Return a connection object."""
    db = self.get_connection(self.get_conn_id())
    return self.connector.connect(host=db.host, port=db.port, username=db.login, schema=db.schema)
```

From SQLAlchemy docs:

![image](https://github.com/user-attachments/assets/4ed645e6-a196-4750-b749-fb2e001174c4)

The resulting engine is a weird object with a pyodbc driver and dialect, but with a pymssql connection underlying.

**Comment by dabla** [comment]
> Tried this:
> 
> ```python
> from airflow.providers.common.sql.hooks.sql import DbApiHook
> hook = DbApiHook.get_hook(conn_id='conn1')
> engine = hook.get_sqlalchemy_engine()
> engine.connect()
> ```
> 
> It results in the same error as above: `AttributeError: 'pymssql._pymssql.Connection' object has no attribute 'add_output_converter'` (This is an error from SQLAlchemy, when it internally tries to pass a pymssql connection object into a pyodbc dialect based connection script)
> 
> While I understand `DbApiHook.get_hook()` is the proper way to instantiate a database hook, it just creates a `MsSqlHook` with the same parameters as above. In practice, nothing changes on the engine creation side with `.get_sqlalchemy_engine()`.
> 
> As I don't use any other databases, I'm not entirely sure about the benefits of passing the connection to the engine with the `creator` argument (`engine_kwargs["creator"] = self.get_conn`), but that causes any connection parameters to be ignored. As the passed connection with the `get_conn` just returns the default MS SQL connection with pymssql, it creates a basic connection, and any other scheme or other parameters in the connection are bypassed. See the `get_conn` definition:
> 
> ```python
> def get_conn(self):
>     """Return a connection object."""
>     db = self.get_connection(self.get_conn_id())
>     return self.connector.connect(host=db.host, port=db.port, username=db.login, schema=db.schema)
> ```
> 
> From SQLAlchemy `create_engine()` docs:
> 
> ![image](https://private-user-images.githubusercontent.com/389091/373229841-4ed645e6-a196-4750-b749-fb2e001174c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTU2ODEsIm5iZiI6MTcyNzk1NTM4MSwicGF0aCI6Ii8zODkwOTEvMzczMjI5ODQxLTRlZDY0NWU2LWExOTYtNDc1MC1iNzQ5LWZiMmUwMDExNzRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMTM2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjNkYWQzY2Y1MDU5Y2Q3ZmM4Y2RmNDJmZGEwNzYwZWFjZWRlZjJmNTk2YmJiODdjNTIxYjcxNDA4MmFlMGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q3T-7d7bt_E3P_nZ8br3dM9_dkRuajVGxkj1G6d8pTQ)
> 
> The resulting engine is a weird object with a pyodbc driver and dialect, but with a pymssql connection underlying.

Ok now I'm confused...  Are you trying to access MSSQL through ODBC or PyMSQL?  Because in your initial post you stated ODBC, but now you're referring to PyMSSQL?

**Comment by dabla** [comment]
This config is also contradiction:

```
{
    **"conn_type": "mssql",**
    "host": "<redacted>",
    "login": "user",
    "password": "pass",
    "schema": "master",
    "port": 1433,
    "extra": {
        "driver": "ODBC Driver 18 for SQL Server",
        "encrypt": "yes",
        **"sqlalchemy_scheme": "mssql+pyodbc"**
    }
}
```

Connection type is mssql (so pymssql), but in your extras you specify you want to use the ODBC driver and "mssql+pyodbc" sqlalchemy_scheme while the connection type is mssql which is actually pymssql, not ODBC.

**Comment by emredjan** [comment]
I'm trying to access MSSQL through Microsoft ODBC driver, using the `mssql+pyodbc` sqlalchemy driver / dialect. I'm aware that MSSQL connection uses pymssql  driver / dialect underneath, but you were always able to override that for getting  sqlalchemy engine objects with the `sqlchemy_scheme` argument, which is the exact reason that this argument exists as far as I'm aware.

It should be possible to change the driver in the MSSQL connection objects

**Comment by dabla** [comment]
> I'm trying to access MSSQL through Microsoft ODBC driver, using the `mssql+pyodbc` sqlalchemy driver / dialect. I'm aware that MSSQL connection uses pymssql driver / dialect underneath, but you were always able to override that for getting sqlalchemy engine objects with the `sqlchemy_scheme` argument, which is the exact reason that this argument exists as far as I'm aware.
> 
> It should be possible to change the driver in the MSSQL connections without changing the connection type to ODBC. See MSSQL provider docs:
> 
> https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/_api/airflow/providers/microsoft/mssql/hooks/mssql/index.html

As far as I know, you should always use ODBC as connection type when using ODBC connections, not using a native connection type and then still override it as ODBC.  @potiuk what do you think? Or I'm seeing/understood this wrongly?

**Comment by dabla** [comment]
> Think about this:
> 
> I modified the connection to remove the "contradiction":
> 
> ```json
> {
>     "conn_type": "mssql",
>     "host": "<redacted>",
>     "login": "user",
>     "password": "pass",
>     "schema": "master",
>     "port": 1433,
>     "extra": {
>         "driver": "ODBC Driver 18 for SQL Server",
>         "encrypt": "yes"
>     }
> }
> ```
> 
> Creating an MSSQL hook, overriding the sqlalchemy_scheme in the hook instantiation instead, which is an allowed option according to the documentation:
> 
> ![image](https://private-user-images.githubusercontent.com/389091/373244343-aaeb66f5-3ad7-47b9-b4f8-be16bc082346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTc5MjQsIm5iZiI6MTcyNzk1NzYyNCwicGF0aCI6Ii8zODkwOTEvMzczMjQ0MzQzLWFhZWI2NmY1LTNhZDctNDdiOS1iNGY4LWJlMTZiYzA4MjM0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMjEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWM0YmZkZTk1MWYyNDc4MTI0NjRhMGZiNjIzYzAwYzhiNWZiMDVjODE5NzEyODFmMjdjZjNmZThkMjQyMGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DvVpcGaz0JOod36MDY11AiZixGz5tjjOlcRaUYJ-aZE)
> 
> ```python
> from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
> hook = MsSqlHook(mssql_conn_id='conn1', sqlalchemy_scheme='mssql+pyodbc')
> engine = hook.get_sqlalchemy_engine()
> 
> engine.connect()
> ```
> 
> ^ This is not working as well, which means this change is a breaking one.
> 
> Using pymssql as an internal connection is fine, but it should respect the choice of `sqlalchemy_scheme` argument in the hook, in `get_sqlalchemy_engine` and `get_sqlalchemy_connection` methods. Changing the connection type to ODBC should not be needed in my opinion as the abstraction is done by sqlalchemy anyway, which allows different connection dialects with MSSQL (`mssql+pyodbc`, `mssql+pymssql`, etc.).
> 
> If this is the way MSSQL connections in Airflow will move forward, and will not allow any other driver to be used than `pymssql`, then this was never communicated as such in the changelogs and documentations, and there needs to be more changes (like removing `sqlalchemy_scheme` override option in mssql provider), and would be better communicated as a breaking change for these use cases.

It should actually be like this:

```
{
    "conn_type": "odbc",
    "host": "<redacted>",
    "login": "user",
    "password": "pass",
    "schema": "master",
    "port": 1433,
    "extra": {
        "driver": "ODBC Driver 18 for SQL Server",
        "encrypt": "yes",
        "sqlalchemy_scheme": "mssql+pyodbc"
    }
}
```

This is what we are using and works.

**Comment by dabla** [comment]
I've digged a bit deeper regarding following line of code:

` engine_kwargs["creator"] = self.get_conn`

This was to support JDBC connections with sqlalchemy, I could remove it from the DbApiHook and override it in the JdbcHook, then you would still be able to use it as you intended to.

**Comment by dabla** [comment]
[PR ](https://github.com/apache/airflow/pull/42705)succeeded, so it could be merged.
