### ISSUE TITLE
AIP-68 | Migrate plugin menu_items to FastAPI and new UI

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42706]
- Rename `appbuilder_menu_items` to `menu_items`
- Add a `GET /plugins` endpoint to FastAPI that looks up the menu items and sends them as an array to the UI
- Have the UI consume the `GET /plugins` endpoint and render the menu items links just like how the DocsButton component works: https://github.com/apache/airflow/blob/main/airflow/ui/src/layouts/Nav/DocsButton.tsx

**Comment by Brijeshthummar02** [comment]
@bbovenzi i can fix this, assign me the task.

**Comment by bbovenzi** [comment]
@Brijeshthummar02 assigned! Let me know if you need help with any part here.

**Comment by Brijeshthummar02** [comment]
Guide me for 2nd and 3rd point,can you clarify in brief with the path.

**Comment by bbovenzi** [comment]
1. just rename the plugin menu_items property
2. create a new GET `/plugins` endpoint in the new FastAPI that will return a list of all plugin menu_items. You can the PRs tagged here to see how to build endpoints for FastAPI: https://github.com/apache/airflow/issues/42370
3. Once there is an endpoint in FastAPI, we autogenerate all the types and queries. Then you call the function, something like `usePluginServiceGetPlugins()`, inside the Nav component to render the MenuItems. Probably reusing the code from the DocsButton component.

**Comment by Brijeshthummar02** [comment]
can you provide the path of file for the first point.

**Comment by bbovenzi** [comment]
Actually we have the menu items provided in #43125.
