### ISSUE TITLE
DAG priority parsing request is not inserted correctly on Postgres

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#42704]
### Apache Airflow version

2.10.2

### What happened?

https://github.com/apache/airflow/blob/9ec21405c0abe23f6de2e0acd704faa6631fbe76/airflow/assets/manager.py#L256-L276

We use a faster SQL on Postgres to insert DagPriorityParsingRequest rows. From what I can see though the logic seems wrong? The `slow` version inserts one DPPR for each fileloc, but the Postgres version only inserts _one_ row (at most, it can insert none on conflict, but that’s besides the point).

```pycon
>>> file_locs = ["a", "b", "c"]  # Mock data.
>>> {"fileloc": fileloc for fileloc in file_locs})
{'fileloc': 'c'}
```

This can’t be right… but there’s no bug reports on this from what I can tell.

### What you think should happen instead?

The line should probably be

```python
session.execute(stmt, ({"fileloc": fileloc} for fileloc in file_locs))
```

instead.

### How to reproduce

I was just reading the code. Didn’t actually have any behavioural observations.

### Operating System

Any

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
The PRs have been merged. Closing this issue
