### ISSUE TITLE
AIP-38 | DAGs List | Search by dag_display_name_pattern

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42714]
The public get dags endpoints in FastAPI now supports `dag_display_name_pattern`. We should use that to search DAGs in the UI and activate the disabled search bar that is already there.

We can leave "Advanced Search" disabled for now.

See top of page for the search bar:
![Image](https://github.com/user-attachments/assets/368ff14d-20b3-46c8-a4ec-053edf40b429)

**Comment by luyangliuable** [comment]
Can I get assigned this issue? I got started already thanks

**Comment by luyangliuable** [comment]
Hi I was just wondering is this issue ready to be closed or is there anything more that needs to be fixed :)

**Comment by bbovenzi** [comment]
Closed via #42896
