### ISSUE TITLE
AIP-84 | Public list tags endpoint

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42713]
In the public API, we should have a get `/dag/tags` endpoint that return a list of all tags across all DAGs. We can then use this in the UI to filter the dags list by tag #42712

Views.py code to migrate: https://github.com/apache/airflow//blob/main/airflow/www/views.py#L1035

**Comment by jason810496** [comment]
Hi, I'm interested in working on this issue. Could you please assign this ticket to me? Thanks !

**Comment by bbovenzi** [comment]
@jason810496 all yours!

**Comment by rawwar** [comment]
@bbovenzi, Can we also add support for the offset, limit?

**Comment by bbovenzi** [comment]
Yes. And then we should have a `tag_name_pattern` search param too.
