### ISSUE TITLE
AIP-38 | DAGs List |  Filter by last_dag_run_state

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42715]
We now have `last_dag_run_state` in FastAPI's get dags endpoint. Let's use that in the UI. And enable the disabled buttons that are already in the UI:

![Image](https://github.com/user-attachments/assets/f52498a5-4392-4f55-95d3-beeeff3f9e2b)

**Comment by tirkarthi** [comment]
I am working on a patch for this. Please assign this to me.
