### ISSUE TITLE
AIP-84 | Add last run details to dags list

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42730]
Add the latest dag run to the returned dag in the public get `/dags` endpoint in fastapi.

`dag.latest_dagrun` should be a serialized DagRun or None

**Comment by ArshiaZr** [comment]
Can you please assign it to me?

**Comment by bbovenzi** [comment]
Thanks @ArshiaZr  Instead of listing a few separate columns of the dag run. We should probably just return `dag.last_dagrun` as a dict of the DagRun model.

**Comment by bbovenzi** [comment]
@ArshiaZr this is the issue to add `last_dagrun` to the fast api dags list. So please feel free to work on it!

**Comment by pierrejeambrun** [comment]
Hello @ArshiaZr,

Are you still working on it? Do you need help to get started?

**Comment by pierrejeambrun** [comment]
Closing. We are now using the private endpoint for `recent_dag_runs` which has more information.

**Comment by tirkarthi** [comment]
The PR was stale and closed. It's probably good to reopen this issue and have the latest dagrun as part of the dag response which is more efficient and useful in pages like dag detail instead of fetching last 14 dagruns and getting the last item.
