### ISSUE TITLE
AIP-38 Add skeleton loading state to table component

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42734]
Add loading state to table and card views of our list component.

**Comment by tirkarthi** [comment]
See also https://github.com/TanStack/table/discussions/2386

**Comment by bbovenzi** [comment]
> See also [TanStack/table#2386](https://github.com/TanStack/table/discussions/2386)

Thanks. The approach in my PR isn't too different except that we add extra options to the `column.meta` object. Then we only have to write the Skeleton components once.

**Comment by bbovenzi** [comment]
Closed in #42711
