### ISSUE TITLE
AIP-84 Migrate DagWarning public endpoint to FastAPI

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#42748]
### Description

Migrate List dag warnings endpoint

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
While I was working on this issue,  I noticed, legacy API 's list dag warning endpoint's Responses schema shows "import_errors" . I think, this should have been DagWarnings.

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_warnings


@pierrejeambrun , do you think this is a bug?

**Comment by pierrejeambrun** [comment]
Yes this is a mistake in the legacy API. The actual response has `dag_warnings`:

![Screenshot 2024-10-09 at 15 57 15](https://github.com/user-attachments/assets/577685ed-97fc-4d87-a120-4aeb3393da93)

PR here:
https://github.com/apache/airflow/pull/42858
