### ISSUE TITLE
Include Unit Test for Legacy UI and API Selective Checks in Breeze

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#42774]
### Description

Follow-up work of #42758.

### Related issues

#42758

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gopidesupavan** [comment]
@bugraoz93 can i assign it to you ? :)

**Comment by bugraoz93** [comment]
That would be great, @gopidesupavan! Thanks! :)
