### ISSUE TITLE
How to schedule tasks with different start_date in one dag?

### ISSUE THREAD

**Issue by pkexcellent** [apache/airflow#428]
Hi, I want to schedule some tasks with different start_date in one dag, like this:

``` python
dag = DAG(dag_id = 'myjob', default_args=default_args)
#in default_args, 'start_date' is datetime(2015, 9, 1)
t1 = BashOperator(
     task_id = 't1',
     bash_command = "date",
     dag = dag) 

t2 = BashOperator(
     task_id = 't2',
     bash_command = "date",
     start_date = datetime(2015, 9, 1, 0, 30),
     dag = dag) 

t1.set_downstream(t2)
```

now my system date is 2015-09-19, 
I use `airflow scheduler -d myjob` 
 t1 can run success, but t2 cannot be scheduled, why? 
Thanks a lot!

**Comment by mistercrunch** [comment]
`start_date` really means "first run". Each run (aka `execution_date`) need to line up perfectly for dependencies to be met. 

If you want to delay t2 by 30 minutes the airflow way, you'd use a TimeSensor (as say `t3`) and have t2 depend on t3. All these tasks would have the same `start_date`.

Make sense? Where do you think I should change the docs to clarify this?

**Comment by pkexcellent** [comment]
Thanks, that's really help! 
And the `start_date` is really a confused concept for new users,  "start date" and "start time" is really different.
Maybe some more description for the parameter `start_date` at `class BaseOperator(object)` in models.py is better:

``` python
:param start_date: start date for the task, the scheduler will start from this point in time. 
All the tasks in one dag should have the same start 'time'
:type start_date: datetime
```

**Comment by mistercrunch** [comment]
This should make it very clear:
https://github.com/airbnb/airflow/commit/00f3f69b61bca55ad69e0a17e15713a708355f33
