### ISSUE TITLE
Add a clock widget with timezone support in new UI

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#42817]
### Description

The clock widget in the navigation bar was useful to change time from UTC to other timezones like local timezone in the old UI. The change was also reflected in all other datetime related components. It will be helpful to have the widget in the new UI like the side bar below dark theme toggle button. I opened this issue since I didn't see it in the designs. Please feel free to close this if it's tracked in other issue.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
cc: @bbovenzi @pierrejeambrun

**Comment by bbovenzi** [comment]
Yes, let's put that and the light/dark mode in a User Profile settings modal.

**Comment by bbovenzi** [comment]
We will also have to copy over the `useTimezone` hook and provider from the previous UI and the `<Time />` component. But both should use `dayjs` instead of `moment`
