### ISSUE TITLE
AIP-38 Move Light/Dark Mode Toggle to User Settings

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42823]
Swap the light/dakr mode toggle button with a User Settings button with an `import { FiUser } from "react-icons/fi";` icon. Clicking on it can open up a menu with toggling dark/light mode as an option.

**Comment by AryanK1511** [comment]
Hello @bbovenzi ! R u able to assign this issue to me as I would really like to work on this

**Comment by bbovenzi** [comment]
@AryanK1511 all yours!

**Comment by AryanK1511** [comment]
@bbovenzi Hello! I was working on this issue and have managed to implement the icon. However, I am not sure about the exact UI that you want for the menu. How do you want me to go forward with this?

**Comment by AryanK1511** [comment]
@bbovenzi This is what I have right now. I know it is not pretty but I wanted to ask you what you want me to do with this or was the point of this issue just to add the icon and not to work on the menu?


https://github.com/user-attachments/assets/70444692-7350-404a-b0d8-fc35fe69d93d

**Comment by bbovenzi** [comment]
Oh I had a similar issue when adding the [docs button](https://github.com/apache/airflow/blob/main/airflow/ui/src/layouts/Nav/DocsButton.tsx)

Let's pass just the same props as a NavButton instead of `as={}` and make sure to specify the menu placement

**Comment by AryanK1511** [comment]
Hello @bbovenzi! I have fixed this in #42964. Take a look and lemme know if it is good.
