### ISSUE TITLE
AIP-38 | New Dashboard homepage

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42825]
Create a new homepage dashboard to give an overview of what is happening on the airflow deployment. Essentially, migrate and expand upon Cluster Activity

- Add a new Dashboard page
- Show cluster health stats
- #42700
- https://github.com/apache/airflow/issues/43328
- Show DAG import errors
- Quick links to DAGs with failed runs or running runs
- Add an event timeline to help with date range selection

**Comment by raphaelauv** [comment]
in `Show cluster health stats`

it would be very nice to also show the number of components ( scheduler(s) , celery-worker(s) , triggerer(s) , dag-processor(s) )

**Comment by bbovenzi** [comment]
Closing in favor of larger tracking issue: https://github.com/apache/airflow/issues/43712
