### ISSUE TITLE
AIP-84 Add UI batch recent_dag_runs endpoint

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#42933]
In the new Dags list view we show a chart of recent dag runs:

![Image](https://github.com/user-attachments/assets/2374ce73-7cb9-48ac-b3a6-637dbc049434)

We should add a new endpoint `ui/dags/recent_dag_runs` to return an array of recent dag run arrays like so:
```
[{ dag_id: 'string', dag_runs: []}]
```

It should accept the same filters and pagination as the public get dags endpoint so that we can match them together.

This replaces the viewspy `/last_dagruns`.

**Comment by jason810496** [comment]
Hi, I've just finished #42713. Could you please assign this ticket to me? Thanks!
