### ISSUE TITLE
AIP-84 Migrate XCom get entry public endpoint to FastAPI

### ISSUE THREAD

**Issue by michaeljs-c** [apache/airflow#42978]
### Description

Migrate the XCom get entry public endpoint from connexion to FastAPI

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Hello @michaeljs-c,

Any progress on this issue ? Don't hesitate if you need help to get started.

**Comment by michaeljs-c** [comment]
Hi @pierrejeambrun, thanks I'm almost finished with it, just working through CI
