### ISSUE TITLE
add display_name to rendered fields for Vertex AI training operators

### ISSUE THREAD

**Issue by WSHoekstra** [apache/airflow#43027]
### Description

I would like the 'display_name' arg be added to the list of rendered_fields for the Vertex AI CreateHyperparameterTuningJobOperator and CreateCustomContainerTrainingJobOperator operators.

### Use case/motivation

I would like to be able to dynamically build the display_name of my custom Vertex AI (hyperparameter tuning) training jobs. At the moment, I have to create a custom operator that adds the display_name to the list of rendered fields to achieve this. I'd rather just use the base operators directly.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to work on it - assigned you
