### ISSUE TITLE
Extra long value in `op_args` and `op_kwargs` in OpenLineage event

### ISSUE THREAD

**Issue by rahul-madaan** [apache/airflow#43031]
### Apache Airflow Provider(s)

openlineage

### Versions of Apache Airflow Providers

"openlineageAdapterVersion": "1.6.0",
"version": "2.9.0"

### Apache Airflow version

2.9.0

### Operating System

mac

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

deployment details are not present

### What happened

I am getting extra long value in op_args and op_kwargs
inside run.facets.unknownSourceAttribute.unknownItems[]

### What you think should happen instead

there should be a flag which can be set to true incase we require op_args and op_kwargs value in the OL event.
default value of the flag should be false and only enabled when required.

The information in the op_kwargs and op_args is sensitive in some cases - getting emailIDs of people in the org.

### How to reproduce

There must be some way to get data into op_args and op_kwargs. I am not really sure on how to reproduce the issue.
The data in these keys is huge.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kacpermuda** [comment]
Hey, have you been able to see if the `include_full_task_info` [config](https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/configurations-ref.html#include-full-task-info) introduced in provider 1.10 can help you out? It should limit the number of fields included in the event.
