### ISSUE TITLE
AIP-38 | Add more sort options to Dags List

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43043]
In our fastapi endpoint, we only sort the 

Right now, we only sort by `dag_id`. Let's swap that for display_name. Also, let's add `"next_dagrun", "last_run_state", "last_run_start_date"` as other sort options.

Since not all of these fields are currently columns in the dags list response, we probably need to always our `sort-by-select` instead of only when its a card list.

**Comment by shubhamraj-git** [comment]
Could you assign this to me.
