### ISSUE TITLE
Inconsistent display of timezone

### ISSUE THREAD

**Issue by hydeboy** [apache/airflow#43149]
### Apache Airflow version

2.10.2

### What happened?

<img width="1028" alt="20241018160503" src="https://github.com/user-attachments/assets/915f3495-daa4-441d-bd64-4f61d6acc910">

### What you think should happen instead?

The Timezone displayed in the details area on the webpage should be consistent with the<meta>dag_timezone in the<head>of the HTML source

### How to reproduce

Set the default_timezone in the airflows. cfg file to Asia/Shanghai, start airflow, open the homepage, and click on example_branch_operator

### Operating System

Ubuntu 22.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
See also https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timezone.html#default-time-zone

This is the internal time zone for the scheduling and processing of jobs. The UI display is separate of this and in your case it seems you have selected UTC in the browser top-right. So I see this is rather a feature (DAG is configured to run in Timezone A and your Browser is in Timezone B).
