### ISSUE TITLE
DAG-level permissions for `/dags/{dag_id}/clearTaskInstances` is incorrect

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#43140]
### What do you see as an issue?

The documentation on [DAG level permissions](https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/access-control.html#dag-level-permissions) states that the permissions `DAGs.can_edit`, `DAG Runs.can_read`, `Task Instances.can_edit` are required for the endpoint `/dags/{dag_id}/clearTaskInstances`.

### Solving the problem

The permissions for the endpoint `/dags/{dag_id}/clearTaskInstances` are `DAGs.can_edit`, `DAG Runs.can_edit`, `Task Instances.can_edit`. The method is also "PUT" not "POST".

In Airflow 2.8.0, the [clear endpoint](https://github.com/apache/airflow/blob/2.9.3/airflow/api_connexion/endpoints/task_instance_endpoint.py#L444) updated (see [PR](https://github.com/apache/airflow/pull/34317)) to use the requires_access_dag function which leverages [is_authorized_dag](https://github.com/apache/airflow/blob/providers-fab/1.2.2/airflow/providers/fab/auth_manager/fab_auth_manager.py#L203). More importantly, the SAME resource method is used to check against each resource entity. The clear method passes the "PUT" resource method which [translates](https://github.com/apache/airflow/blob/2.9.3/airflow/auth/managers/utils/fab.py#L34-L40) to "ACTION_CAN_EDIT".
 
The logic translates to requiring the following permissions.
(permissions.ACTION_CAN_EDIT, permissions.RESOURCE_DAG)
(permissions.ACTION_CAN_EDIT, permissions.RESOURCE_DAG_RUN)
(permissions.ACTION_CAN_EDIT, permissions.RESOURCE_TASK_INSTANCE)

### Anything else

I did not check the other DAG level permissions. I recommend verifying each entry.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yes. Would be great if someone takes it and reviews all the permissions and correct if there any problems. If you don't want to contribute it @wolfier, I marked it as a good first issue. It's not a high priority though as we are completely rewriting it for Airflow 3 and I believe the fastapi implementation there will have a consistenty between the docs and permissions pretty much guaranteed (@pierrejeambrun ?). 

Other than that, yes, this is not consistent with docs and unless someone would like to take it on, unlikely to be addressed in 2.*, we will leave it as "good first issue" to review and fix all inconsistencies.

**Comment by pierrejeambrun** [comment]
Documentation and code method will be automatically in sync. I will not be possible to have the documentation stating "PUT", and the code implementing a "POST".

Permissions are for now just custom airflow code and FastAPI does not know how to handle that. If permissions need to be exposed in the swagger spec, we can write some code to automatically fill that in but this is not supported out of the box. That can actually be a nice improvement.

**Comment by potiuk** [comment]
> Permissions are for now just custom airflow code and FastAPI automatic documentation does not know how to handle that. If permissions need to be exposed in the swagger spec, we can write some code to automatically fill that in, but this is not supported out of the box. That can actually be a nice improvement.

Let's capture it as an issue then :) ?

**Comment by pierrejeambrun** [comment]
Issue created here https://github.com/apache/airflow/issues/43430

**Comment by SuccessMoses** [comment]
@pierrejeambrun I want to work on #43430 as my first issue

**Comment by SuccessMoses** [comment]
what is the path to the source file for the documentation? I am not yet familiar with the code base

**Comment by potiuk** [comment]
> what is the path to the source file for the documentation? I am not yet familiar with the code base

Click "suggest a change on this page" on the Page you want to edit and PR will be opened for you automatically in the right file.
