### ISSUE TITLE
AIP-84 | UI endpoint for config

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43166]
In the told UI, we passed a lot of variables via global variables in FAB templates. We should replace those with a `ui/config` endpoint, to exposed specifically what the UI needs to render such as:

Settings:
`state_color_mapping`

Config:
`audit_view_excluded_events`
`audit_view_included_events`
`warn_deployment_exposure`
`page_size`
`default_wrap`
`auto_refresh_interval`
`default_ui_timezone`
`hide_paused_dags_by_default`
`require_confirmation_dag_change`
`enable_swagger_ui`
`instance_name`
`instance_name_has_markup`
`show_trigger_form_if_no_params`
`test_connection`
`navbar_*` we may need to update this to support light/dark modes. but let's send it all for now
`IS_K8S` which collates a few values together:
  ```
  conf.get("core", "EXECUTOR") in {
      executor_constants.KUBERNETES_EXECUTOR,
      executor_constants.CELERY_KUBERNETES_EXECUTOR,
      executor_constants.LOCAL_KUBERNETES_EXECUTOR,
  }
  ```

Other config: 
`standalone_dag_processor` [This should be checked in the API, not the UI](https://github.com/apache/airflow/issues/44253)

We do need to migrate the config to the public rest api too in https://github.com/apache/airflow/issues/42745 but that can be toggled off. This UI endpoint always needs to return in order for the UI to render correctly.

**Comment by tirkarthi** [comment]
Adding a note to also update pagination to be of the same webserver page_size value in airflow.cfg which is hard-coded as 50 now.

https://github.com/apache/airflow/blob/899dcbfcb2b0ca2a8eb50cfb807bf96c336a3552/airflow/ui/src/components/DataTable/useTableUrlState.ts#L25-L31

**Comment by bbovenzi** [comment]
Actually we can generate `IS_K8S` via

```
IS_K8S_OR_K8SCELERY_EXECUTOR = conf.get("core", "EXECUTOR") in {
    executor_constants.KUBERNETES_EXECUTOR,
    executor_constants.CELERY_KUBERNETES_EXECUTOR,
    executor_constants.LOCAL_KUBERNETES_EXECUTOR,
}


I think we should deprecate `state_colors` and make that only user-configurable

**Comment by vatsrahul1001** [comment]
@pierrejeambrun @bbovenzi 

1. Does the format below look okay to you for the `UI/config `endpoint?
  
  ````
  {
    "settings": [
      {
        "state_colors": {
          "deferred": "mediumpurple",
          "failed": "red",
          "queued": "gray",
          "removed": "lightgrey",
          "restarting": "violet",
          "running": "lime",
          "scheduled": "tan",
          "skipped": "hotpink",
          "success": "green",
          "up_for_reschedule": "turquoise",
          "up_for_retry": "gold",
          "upstream_failed": "orange"
        }
      },
      {
        "is_k8s": false
      }
    ],
    "config": {
      "page_size": "value1",
      "auto_refresh_interval": "value2",
      "default_ui_timezone": "value1",
      "standalone_dag_processor": "value2",
      "hide_paused_dags_by_default": "value1",
      "auto_refresh_interval": "value2",
      "navbar_color": "value1",
      "instance_name": "value2",
      "webserver_config": {}
      
    }
  }
  ```
2. What should we display when `expose_config` is set to false? Should we return a 403, or is it acceptable to show the values in this case?

**Comment by pierrejeambrun** [comment]
Those config are just for the UI to display properly. (For auth and maybe even non auth users).

Only very basic and display/UI specific things should be returned by this endpoint. We cannot return the entire configuration. just the attributes mentionned by Brent. (Those are safe to return).

**Comment by vatsrahul1001** [comment]
@pierrejeambrun here @bbovenzi mentioned returning entire conf. webserver dict after checking which values we need to support. 
> probably the entire conf.webserver dict, which we should double check which values we still want to support.

We can do settings and config
**settings**
```
state_colors
IS_K8S_OR_K8SCELERY_EXECUTOR
```

**config**
```
page_size
auto_refresh_interval
default_ui_timezone
standalone_dag_processor
hide_paused_dags_by_default
navbar_color
instance_name
```

**Comment by vatsrahul1001** [comment]
Below is the updated response. cc: @pierrejeambrun @bbovenzi 
```

{
  "settings": [
    {
      "state_color": {
        "deferred": "mediumpurple",
        "failed": "red",
        "queued": "gray",
        "removed": "lightgrey",
        "restarting": "violet",
        "running": "lime",
        "scheduled": "tan",
        "skipped": "hotpink",
        "success": "green",
        "up_for_reschedule": "turquoise",
        "up_for_retry": "gold",
        "upstream_failed": "orange"
      }
    },
    {
      "is_k8s": false
    }
  ],
  "configs": {
    "navbar_color": "#fff",
    "page_size": 100,
    "auto_refresh_interval": 3,
    "default_ui_timezone": "UTC",
    "hide_paused_dags_by_default": false,
    "instance_name": "Airflow"
  }
}
```

**Comment by pierrejeambrun** [comment]
> @pierrejeambrun here @bbovenzi mentioned returning entire conf. webserver dict after checking which values we need to support.

I understand. That's true that most of the webserver could be usefull to the UI, i'm not sure if `everything` is safe to be exposed and should be exposed. Sticking to a 'on need' basis might be a safer approach at first.

I have no strong opinion on that.

The last payload mentioned looks like something we can use. I'll let Brent confirm if this is enough for the front-end to start with.

**Comment by bbovenzi** [comment]
I just updated the main description changing some of the desired config values.

Also, let's make it all one flat dict and remove the distinction between `settings` and `config`
