### ISSUE TITLE
Document local virtualenv setup with workspaces

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#43200]
With #42505 and few follow-up issuse we've worked out how to use uv workspaces, to have the source tree split between airflow and providers. This means that it is possible to have airflow and providers development working fot both breeze and local virtual environment using `uv workspaces`

While with Breeze it works out-of-the-box, the local virtualenv setup and IDE setup for IntelliJ, VS Code requires some adjustments. Our documentation still describes how it works for the "pre-providers-split" and our contributors (both new and those who already contributed) are a bit confused what to do and how to set-it up - because there is not even a mentioning of uv and workspaces in the contributing documentation.

While a number of people who use the workspaces already had worked out their patterns, this is not explained and knowledge about it is not shared with other contributors, especially that `uv workspace` is a relatively new feature and by far not something we can assume that people know about.

We need to update https://github.com/apache/airflow/blob/main/contributing-docs/03_contributors_quick_start.rst https://github.com/apache/airflow/blob/main/contributing-docs/07_local_virtualenv.rst and related IDE guides in those chapters to explain it better.

**Comment by ashb** [comment]
`uv sync` "should" I think be the command we want to use, but it's not working right now and gives an error about unresolveable deps https://apache-airflow.slack.com/archives/C06K9Q5G2UA/p1729109616153099

```
  × No solution found when resolving dependencies for split (python_full_version == '3.9.*'):
  ╰─▶ Because only the following versions of snowflake-snowpark-python{python_full_version < '3.12'} are available:
          snowflake-snowpark-python{python_full_version < '3.12'}<=1.17.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.18.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.19.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.20.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.21.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.21.1
          snowflake-snowpark-python{python_full_version < '3.12'}==1.22.0
          snowflake-snowpark-python{python_full_version < '3.12'}==1.22.1
          snowflake-snowpark-python{python_full_version < '3.12'}==1.23.0
      and all of:
          snowflake-snowpark-python>=1.17.0,<=1.21.1
          snowflake-snowpark-python>=1.22.1
...
```

(Error trimmed)

**Comment by kunaljubce** [comment]
@potiuk Although this is not technically my first Airflow issue, can I take this up? Seems like a good way to get my hands dirty with the local installation stuff, and I have been meaning to get a good knowledge on that since I faced some challenges with my previous PR when trying to test it locally.

**Comment by potiuk** [comment]
> @potiuk Although this is not technically my first Airflow issue, can I take this up? Seems like a good way to get my hands dirty with the local installation stuff, and I have been meaning to get a good knowledge on that since I faced some challenges with my previous PR when trying to test it locally.

Ah... I have **just** proposed a PR to address it - and only now I see you commented on it (asynchronous checking). Maybe a good idea is to go through my PR @kunaljubce and follow it, check if things are clear and unambiguous, propose improvements etc :)
