### ISSUE TITLE
When the task is in the up_for_retry or rescheduler state, logs cannot be obtained

### ISSUE THREAD

**Issue by stursdsafdaf** [apache/airflow#43209]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.3

### What happened?

When the task is in the up_for_retry or rescheduler state, logs cannot be obtained.
As shown in the figure, only the hostname is displayed
<img width="1811" alt="iShot_2024-10-21_16 33 44" src="https://github.com/user-attachments/assets/035b0081-09b9-4b89-b20f-ef8b00cb441a">

### What you think should happen instead?

Tasks in the up_for_retry and rescheduler states have been executed but failed and are in the retry phase. Logs should be displayed normally.

### How to reproduce

I deployed 3 nodes and did not enable remote logging.
This happens if the task is running on a non-web node and is in the up_for_retry or rescheduler state.

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.7.3
apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.2
apache-airflow-providers-fab==1.2.2
apache-airflow-providers-ftp==3.10.0
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-mysql==5.6.3
apache-airflow-providers-redis==3.7.1
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.1

### Deployment

Virtualenv installation

### Deployment details

I use Python virtual environment deployment, the configuration is as attached
[airflow_new.txt](https://github.com/user-attachments/files/17457993/airflow_new.txt)

### Anything else?

code file :lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py
This code will result in only getting the log of the node where the web is located when remote logging is not used, so only the host name will be output
<img width="1471" alt="iShot_2024-10-21_16 51 24" src="https://github.com/user-attachments/assets/8f27a221-9394-4cab-bc10-753620c5feea">

So, it should be changed to this
<img width="1475" alt="iShot_2024-10-21_16 53 15" src="https://github.com/user-attachments/assets/feb61027-4a20-41f8-b87b-7eb0b264aa4b">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Looks playsible. WDYT @dstandish ?

**Comment by AllardQuek** [comment]
Hi @stursdsafdaf, I am also facing a similar issue on v2.7.3. May I check if your proposed solution worked for you? 

I noticed there is a previously merged PR (https://github.com/apache/airflow/pull/39496) that seems to perform a similar fix. although the changes do not seem to be included in the latest version. As I'm still new to Airflow, could anyone confirm if that fix would solve this issue too?

**Comment by dstandish** [comment]
I think I added a related fix here https://github.com/apache/airflow/pull/41272 which has milestone of 2.10.0.

Did you try 2.10?

**Comment by dstandish** [comment]
Yeah the reports here are from 2.9.3 and 2.7.3 so I assume that this is resolved by https://github.com/apache/airflow/pull/41272 in  2.10.0 so I will close this.

**Comment by AllardQuek** [comment]
> I think I added a related fix here #41272 which has milestone of 2.10.0.
> 
> Did you try 2.10?

We are working with v2.7.3 in production. To implement the fix in an earlier version, which changes do we require from https://github.com/apache/airflow/pull/41272/files? The changes do not seem to mention the up for retry state. Thank you!

**Comment by potiuk** [comment]
> We are working with v2.7.3 in production. To implement the fix in an earlier version, which changes do we require from https://github.com/apache/airflow/pull/41272/files? The changes do not seem to mention the up for retry state. Thank you!

You need to upgrade. We do not have a process to individually guide and explain how to take parts of the code and apply it to your version if you do not want to upgrade. If you want there are a number of 3rd-party commercial companies to assist you with it (and get paid for it), but if you want to rely on volunteer's effort here, the only way to apply fixes is to upgrade.

**Comment by AllardQuek** [comment]
> You need to upgrade. We do not have a process to individually guide and explain how to take parts of the code and apply it to your version if you do not want to upgrade. If you want there are a number of 3rd-party commercial companies to assist you with it (and get paid for it), but if you want to rely on volunteer's effort here, the only way to apply fixes is to upgrade.

Got it, thanks!
