### ISSUE TITLE
RabbitMQOperator task stuck on queued when using CeleryExecutor as core executor 

### ISSUE THREAD

**Issue by abdalhalimalzohbi** [apache/airflow#43203]
### Apache Airflow Provider(s)

redis

### Versions of Apache Airflow Providers

airflow-provider-rabbitmq 0.6.1

### Apache Airflow version

2.10.2

### Operating System

airflow bitnami image

### Deployment

Official Apache Airflow Helm Chart

### What happened

When using CeleryExecutor as the core executor for Airflow and utilizing the RabbitMQOperator task from rabbitmq_provider.operators.rabbitmq, the task remains stuck in the queued state and is not recognized by Celery workers. The issue arises when attempting to use RabbitMQOperator to publish messages to an external RabbitMQ queue, which is not related to the Airflow instance.

The root cause of the conflict is that the RabbitMQOperator takes a queue field as a parameter, and this value is mistakenly treated as the name of the queue that the Celery workers will use to execute the task. This creates confusion, as the queue parameter is intended to represent the destination queue for message publishing, not the execution queue for Celery tasks.

### How to reproduce

NA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
`airflow-provider-rabbitmq` is not official Airflow provider. There is no `RabbitMQOperator` in the Apache-Airflow project.
Unless you can explain what is the bug in Airflow code base I suggest to submit this report to the maintainers of `airflow-provider-rabbitmq`
