### ISSUE TITLE
WTForms 3.2.0 broke Airflow main

### ISSUE THREAD

**Issue by jscheffl** [apache/airflow#43228]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.x as well ass main/3.0

### What happened?

Update of WTForms 3.2.0 removed some deprecations and broke the current use of the forms in Airflow.

PR: https://github.com/pallets-eco/wtforms/pull/859
Release: https://github.com/pallets-eco/wtforms/releases/tag/3.2.0
Broken run: https://github.com/apache/airflow/actions/runs/11441304988/job/31829670288

### What you think should happen instead?

WTForms feature release should not break Airflow.

### How to reproduce

n/a

### Operating System

all

### Versions of Apache Airflow Providers

unrelevant

### Deployment

Other

### Deployment details

Github :-D

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Aaah, I see following other threads the problem should be fixed in 3.2.1...

**Comment by jscheffl** [comment]
...and the fix 3.2.1 also has a regression as in https://github.com/pallets-eco/wtforms/issues/863 - re open this...

**Comment by potiuk** [comment]
This is fixed already via #43309
