### ISSUE TITLE
Parameters for dbapihook

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#433]
A few `DbApiHook` methods accept a `parameters` argument (https://github.com/airbnb/airflow/blob/master/airflow/hooks/dbapi_hook.py#L80). I assume that's to supply bind parameters to SQL, but it doesn't seem to actually be used for anything. @mistercrunch would you accept a PR to use it, or is there a different use case?

**Comment by mistercrunch** [comment]
Yeah I'm not 100% sure on what the intent was, @smarden1 ?

I don't think that the base class needs this, but it's ok to add extra params (with sensible defaults) to individual hooks' methods.

**Comment by smarden1** [comment]
ah. @jlowin - you are correct, those  parameters were supposed to be passed back through to the execute fn on the cursor, but it appears that they aren't doing that -- that would be the expected behavior imho.

nice catch!
