### ISSUE TITLE
AIP-84 Migrate the public endpoint Get Event Logs to FastAPI

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43326]
Migrate the public endpoint `get_event_logs` to FastAPI

Part of https://github.com/apache/airflow/issues/42370

**Comment by bbovenzi** [comment]
cc: @jason810496

**Comment by Bowrna** [comment]
@bbovenzi could i try fixing this issue if its not taken?

**Comment by jason810496** [comment]
Hi @Bowrna, I’m already working on this issue.
