### ISSUE TITLE
Out of the box gunicorn_config.py doesn't allow cipher suite configuration.

### ISSUE THREAD

**Issue by 3BK** [apache/airflow#43332]
### Apache Airflow version

2.10.2

### What happened?

sslyze localhost:8080
```
Cipher suites {'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA', 'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384', 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA'} are supported, but should be rejected.
```

### What you think should happen instead?

The **webserver()** function in **airflow/cli/commands/webserver_command.py** should either allow the cipher suite to be tailored (or pass an sslyze audit out of the box.

### How to reproduce

1. start the web server
2. scan the web server with sslyze.

### Operating System

"Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-common-compat==1.2.1
apache-airflow-providers-common-io==1.4.2
apache-airflow-providers-fab==1.4.1
apache-airflow-providers-http==4.13.1

### Deployment

Virtualenv installation

### Deployment details

nstr

### Anything else?

Occurs every time.

PR available upon request.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 3BK** [comment]
At present, the config is hard coded.

**Comment by 3BK** [comment]
Here is a potential fix to the webserver() function.        if cipher_suite:
            run_args += ["--ciphers", cipher_suite]

**Comment by 3BK** [comment]
The alternative would be to hard code the cipher suites so they pass an OWASP scan.
https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html

**Comment by potiuk** [comment]
This is how you can set arguments
