### ISSUE TITLE
Add dag into the website UI

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#434]
Hi someone there,

I'am new to this project,I want add new dag to the website UI like this :
![image](https://cloud.githubusercontent.com/assets/8220811/9982215/ca420df2-6006-11e5-85df-d69e84b30fc2.png)
I read the document ,and didn't find the way ,anyone can help me ?

**Comment by kapil-malik** [comment]
Define a new dag in a python file, for example [tutorial](pythonhosted.org/airflow/tutorial.html) and paste it in the dags_folder (by default ~/airflow/dags ). When a task in DAG runs for next time (via scheduler), it will show up in the UI.
