### ISSUE TITLE
Incorrect Rendering of Error for DBT Output in Airflow Logs

### ISSUE THREAD

**Issue by GabrielEisenbergOlympus** [apache/airflow#43465]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.1

### What happened?

A dbt run concluded successfully and the logs rendered as if there was an error:
![image](https://github.com/user-attachments/assets/6312db21-848c-4b2c-bbf7-f9213d4e0cec)

This likely happened because of the word "ERROR" in the logs.

### What you think should happen instead?

The log should not be rendered as if there was no error

### How to reproduce

Run this code on an airflow instance (in my case I used astro to reproduce the error seen in MWAA):

```python
from airflow.decorators import dag, task
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

# Define the basic parameters of the DAG, like schedule and start_date
@dag(
    start_date=datetime(2024, 1, 1),
    schedule="@daily",
    catchup=False,
)
def error_render():
    @task(task_id="render_error")
    def log_error():
        logger.info("Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1")

    log_error()

error_render()
```

I obtained the following output:

![image](https://github.com/user-attachments/assets/58b4f68e-f428-481e-ac5f-3b7ac0110366)

### Operating System

Amazon Linux 2023

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
seems like coloring is taken from the ERROR specified in the message, nice good first issue for someone to take a look at.

**Comment by mithindev** [comment]
Hi @potiuk, I’d like to work on it.

**Comment by mithindev** [comment]
## Error Reproduction

I successfully reproduced the error:

![Error Screenshot](https://github.com/user-attachments/assets/30338020-c669-4a28-9650-ddeb164fd402)

I am currently working on a solution.

**Comment by mithindev** [comment]
Hello @nathadfield,

I wanted to get a bit more context regarding the expected outcome for this task. Based on my current investigation, it appears that the coloring is applied by matching specific keywords like “error,” “warn,” or “exception.” However, this approach seems limited, as it doesn’t account for other relevant keywords, such as “Failed,” which might also warrant a red color.

Could you clarify if the goal is to apply color based on log states rather than just matching specific words? Should I proceed with an approach that aligns coloring with log states or levels instead?

**Comment by GabrielEisenbergOlympus** [comment]
Hi @jscheffl, perhaps there could be a little more nuance as to how errors etc are highlighted. This could get rather complex, but I'll suggest it anyway.

You could generate error highlighting based on the underlying technologies being used in a task. In that way, you could have custom highlighting that gets defined at a task level. 

In this case, dbt outputs the outcome in a consistent manner as shown above. So perhaps the highlighting for the task could be tuned based on custom regex. In this case, the output line could be ignored in highlighting. Is this overkill for something simple? Probably. 

Do with this what you will 😆

**Comment by jscheffl** [comment]
> Hi @jscheffl, perhaps there could be a little more nuance as to how errors etc are highlighted. This could get rather complex, but I'll suggest it anyway.

Yes, this is what I feared. Also I was not a big fan of the feature first-place.

So what I wanted to say is: It will be complex. And as logs are rendered on the client side and can also be a couple of megabytes which are re-loaded time-over time it need to be implemented in a way not crashing browser by overload. And it need to be a bit more clever than the current mechanism.

Note that the UI is in complete rework, it is planned to re-implement it fully with Airflow 3. So an improvement will most likely only be relevant for Airflow 2.10/2.11 line.

Looking forward for your proposal!
