### ISSUE TITLE
how can I merge the branches in the situation using BranchPythonOperator?

### ISSUE THREAD

**Issue by pkexcellent** [apache/airflow#436]
Sorry to bother you, but I met a problem when I use `BranchPythonOperator`. The workflow is like this. It choose `one_way` and skip `skip_this_way`,  and `job_done` 's `trigger_rule = 'one_success'`. I hope `job_done` run after `run_this_way` is done, but actually `job_done` is also set to skipped? Why and How can I run it properly? Should `BranchPythonOperator` be used in this case?
<img width="515" alt="e" src="https://cloud.githubusercontent.com/assets/6879137/9987016/a08c3720-6075-11e5-8b51-e8eeebe075fa.png">
#167 can not solve my problem well. because I have no parameter like `env`. How should I solve this using Airflow?

**Comment by pkexcellent** [comment]
The image seems like not shown in webpage. This is my workflow:
```-------------```/ ```skip_this_way```\
```make_choice`````` ------------------``` ```job_done```
```-------------```  \ ```run_this_way```/
```make_choice``` is a BashPythonOperator. It choose ```run_this_way``` and skip ```skip_this_way```, then ```job_done``` 's ```trigger_rule = 'one_success'```. I hope ```job_done``` run after ```run_this_way``` is done, but actually ```job_done``` is also set to skipped? Why and How can I run it properly?

**Comment by pkexcellent** [comment]
I found the solution! thanks #167

**Comment by mistercrunch** [comment]
Thanks for reporting this bug. https://github.com/airbnb/airflow/pull/449 should address it.

**Comment by r39132** [comment]
:+1:

**Comment by mistercrunch** [comment]
From my understanding this is fixed, closing.

**Comment by r39132** [comment]
@mistercrunch @pkexcellent https://github.com/airbnb/airflow/issues/680 You may want to reopen this bug.
