### ISSUE TITLE
Add Custom Title to the Header in UI

### ISSUE THREAD

**Issue by vanmik** [apache/airflow#43605]
### Description

Add custom title in the UI header, next to Airflow logo

### Use case/motivation

Usually Airflow is deployed as several independent instances: one for test purpose, one for stage, one for production etc. As a result when using UI it's hard to tell which version is actually used. How about adding some label to the header next to airflow logo?

It could be configurable with UI ENV parameters like:
`VITE_HEADER_TAG=dev/prod/local/anything`
`VITE_HEADER_TAG_COLOR=red`

And here is example how it might look:
![airflow-env](https://github.com/user-attachments/assets/d9c49c32-630a-4915-9e1a-1edfca4aef7f)

If this will be greenlighted i'm willing to write the code

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Is it the same like INSTANCE_NAME we have in Airflow 2 to be carried-over to Airflow 3?
In-deed this should be planned. Adding this to the UI project.

https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#instance-name

**Comment by eladkal** [comment]
Following what @jscheffl see the docs:
https://airflow.apache.org/docs/apache-airflow/stable/howto/customize-ui.html#id2

![Screenshot 2024-11-03 at 9 17 59](https://github.com/user-attachments/assets/a3d8165a-eb3c-4562-a972-1a01ae4c698f)


I think we can close this issue as solved

**Comment by potiuk** [comment]
Indeed.

**Comment by bbovenzi** [comment]
Yes, this is already a task to pass the config to the new UI: https://github.com/apache/airflow/issues/43166
