### ISSUE TITLE
AIP-81 Implement Missing API Endpoints for Jobs will be used from CLI Commands

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#43657]
### Description

To enhance the API functionality, this umbrella ticket organizes the development of missing endpoints for `Jobs`. Implementing these endpoints will enable users to manage resources more effectively through the API, improving usability and reducing the need for multiple workarounds.
The main aim of the workload will help to make CLI secure via using these endpoints.

- List Jobs with Filter (like State, job_type, hostname, is_alive) -> https://github.com/apache/airflow/issues/43660 @jason810496 
- List Jobs -> https://github.com/apache/airflow/issues/43661 @josix 

### Use case/motivation

[AIP-81](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-81+Enhanced+Security+in+CLI+via+Integration+of+API)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jason810496** [comment]
Hi @bugraoz93, I can take on this API. Could you please assign the issue to me? Thanks!

**Comment by bugraoz93** [comment]
Hi @jason810496 , this issue is consisted on two parts/endpoints. One of them is already assigned. I can assign you the other one, which is listing jobs with filters if you want to work on it

**Comment by potiuk** [comment]
I assigned both of you :)
