### ISSUE TITLE
AIP-81 Implement List Jobs with Filter Endpoint in FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#43660]
### Description

Create an endpoint in FastAPI that lists `Jobs` with the ability to filter by specific criteria like `state`, `job_type`, `hostname`, and `is_alive` status. This will allow users to efficiently query and monitor jobs based on their current status and other attributes.

### Use case/motivation

See related issue.

### Related issues

#43657

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bugraoz93** [comment]
@jason810496 , this is the one I mentioned in the umbrella issue

**Comment by jason810496** [comment]
I see, I left the comment on the wrong issue while navigating between this one and #43657. 😅
I meant to take on this one. Thanks!

**Comment by bugraoz93** [comment]
Assigned, thanks! :)
