### ISSUE TITLE
AIP-81 Implement List Jobs Endpoint in FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#43661]
### Description

Develop an endpoint in FastAPI that provides a list of all jobs, allowing users to view jobs.

### Use case/motivation

See related issue.

### Related issues

#43657

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josix** [comment]
Hi @bugraoz93, I can help resolve this issue, thanks!

**Comment by bugraoz93** [comment]
Thanks for assigning @rawwar! For sure, @josix  go ahead, any help would be great!

**Comment by bugraoz93** [comment]
Closing this in favour of discussion here #43859
