### ISSUE TITLE
AIP-38 | Show version

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43710]
Use the auto-generated get version query. In order to display the Airflow version and Git Version.

Although, we have a few options of where to render this:

- In the footer like the legacy UI
- In the User menu of the NavBar. Airflow version is a direct link to the release docs. While git version can exist in a TBD full Settings page

**Comment by dauinh** [comment]
Hi @bbovenzi! Can I take up this issue?

**Comment by bbovenzi** [comment]
All yours! Look for the `version` endpoint  in the the publci fastapi
