### ISSUE TITLE
AIP-38 | List Import Errors

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43711]
![Image](https://github.com/user-attachments/assets/49f4cc5c-1d24-421b-8055-1bb03ac3b7c2)

Use the auto-generated list import errors query in the new UI.

Add a button to the Dashboard page saying how many import errors there are (don't show the button if there are 0).
Clicking the button should open a large modal listing all import errors. For a long list, the user should be able to scroll inside the modal.

**Comment by enisnazif** [comment]
I can take a look at this

**Comment by shubhamraj-git** [comment]
Hey could you please assign this to me.

1. Dashboard contains only health for now, will add the stats.
2. Inside the stats, we will have different buttons, one will be "Import errors"
3. Existing API : http://localhost:29091/docs#/Import%20Error/get_import_errors
4. We will show list as DAG display name and accordion to view the import errors.
5. I was thinking about modal size to 5, scrollable to 10 and pagination effect.
6. Future work:  Will support any search / sort filter on the modal.

**Comment by bbovenzi** [comment]
Assigned and those 6 steps make sense to me!

**Comment by atul-astronomer** [comment]
@shubhamraj-git Do we plan to have sort enabled also on DAG import error modal? Currently I am seeing only search enabled
@bbovenzi

**Comment by shubhamraj-git** [comment]
Yes, As per initial talks with @bbovenzi , We can add the sort options and search options using API calls, currently (Only search) it is done on client side.
