### ISSUE TITLE
AIP-84 Set Task Instances State

### ISSUE THREAD

**Issue by omkar-foss** [apache/airflow#43752]
### Description

Currently the Set Task Instances State public endpoint is at `api_connexion/endpoints/task_instance_endpoint.py` under `post_set_task_instances_state`. We need to migrate it to the `api_fastapi/views/public/task_instances.py` under a `set_task_instances_state` or similar.

Features and functionality of the endpoint will remain unchanged. Please note that this is a `PUT` endpoint, contrary to the name of the old API function starting with the word `post`.

### Use case/motivation

AIP-84 cWiki Link: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API

### Related issues

Related to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by omkar-foss** [comment]
I'm working on this one, will raise a PR within today.

**Comment by pierrejeambrun** [comment]
Completed in https://github.com/apache/airflow/pull/44223
