### ISSUE TITLE
AIP-84 Patch Mapped Task Instance

### ISSUE THREAD

**Issue by omkar-foss** [apache/airflow#43754]
### Description

Currently the Patch Mapped Task Instance public endpoint is at `api_connexion/endpoints/task_instance_endpoint.py` under `patch_mapped_task_instance`. We need to migrate it to the `api_fastapi/views/public/task_instances.py` under a `patch_mapped_task_instance` or similar.

### Use case/motivation

AIP-84 cWiki Link: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API

### Related issues

Related to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by omkar-foss** [comment]
I suppose this is covered [here](https://github.com/apache/airflow/pull/44223/files#diff-975b8fd26f7ca1fec635278e2a788ed2e1ac10aba6e8e37a94931b6136cc2b68R493-R496) in PR  https://github.com/apache/airflow/pull/44223.

**Comment by pierrejeambrun** [comment]
Completed in https://github.com/apache/airflow/pull/44223
