### ISSUE TITLE
AIP-84 Set Task Instance Note

### ISSUE THREAD

**Issue by omkar-foss** [apache/airflow#43755]
### Description

Currently the Set Task Instance Note public endpoint is at `api_connexion/endpoints/task_instance_endpoint.py` under `set_task_instance_note`. We need to migrate it to the `api_fastapi/views/public/task_instances.py` under a `set_task_instance_note` or similar.

Features and functionality of the endpoint will remain unchanged.

### Use case/motivation

AIP-84 cWiki Link: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API

### Related issues

Related to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Closing. This endpoint will not be migrated, in the same way as we are doing for the `DagRun`, the update of the task instance note should be part of the `PATCH` task instance. (improved/broader PATCH instance).

Closing.
