### ISSUE TITLE
Lineage between tasks are missing (Airflow -> OpenLineage -> Marquez)

### ISSUE THREAD

**Issue by thinkORo** [apache/airflow#43776]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.3

### What happened?

I use Marquez to visualize dependencies. In Airflow I have installed apache-airflow-providers-openlineage and configured the OpenLineage transport:

```
AIRFLOW__OPENLINEAGE__TRANSPORT: '{“type”: “http”, “url”: “http://YOUR_IP:5000”, “endpoint”: “api/v1/lineage”}'
AIRFLOW__OPENLINEAGE__NAMESPACE: 'airflow'
AIRFLOW__OPENLINEAGE__INCLUDE_FULL_TASK_INFO: 'true'
```

Events and jobs are transferred as expected, but without the corresponding lineage. This means that I only see the tasks in Marquez, but not the DAG with the tasks.

### What you think should happen instead?

In Marquez the DAG shoud be shown incl. all tasks.

### How to reproduce

1. pip-install the required package: apache-airflow-providers-openlineage
2. configure openlinage transport like so: AIRFLOW__OPENLINEAGE__TRANSPORT: '{“type”: “http”, “url”: “http://YOUR_IP:5000”, “endpoint”: “api/v1/lineage”}'
3. execute any Airflow DAG

### Operating System

Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-openlineage==1.13.0

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by thinkORo** [comment]
After updating to Airflow 2.10.3 everything is running as expected.

**Comment by mats1701** [comment]
Using Airflow 2.10.4 and apache-airflow-providers-openlineage==2.0.0 I still get this exact behaviour. Tried downgrading the provider package to 1.13.0 but no luck.
I have set the exact same environment variables.
