### ISSUE TITLE
Incorrect FutureWarning possibly caused by a missing PR in 2.10.3

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#43794]
### Apache Airflow version

2.10.3

### What happened?

In Airflow 2.10.3 `configuration.py` file, we have

https://github.com/apache/airflow/blob/c99887ec11ce3e1a43f2794fcf36d27555140f00/airflow/configuration.py#L857-L859

The `self.sensitive_config_values` returns both `('database', 'sql_alchemy_conn')` and `('core', 'sql_alchemy_conn')` because in 2.10.3 the [deprecated_options](https://github.com/apache/airflow/blob/c99887ec11ce3e1a43f2794fcf36d27555140f00/airflow/configuration.py#L328) variable is not empty. I think it's supposed to be removed. See https://github.com/apache/airflow/pull/42126.

Hence the `self.get()` raises a warning:

```
airflow/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
```

Which confuses our users.

### What you think should happen instead?

The warning should not be raised.

### How to reproduce

1. `pip` Install Airflow 2.10.3
2. Run cli `$ airflow version`

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amoghrajesh** [comment]
@dirrao was this targetted for 2.10.3?

**Comment by potiuk** [comment]
Yeah - we noticed it as well during the Man's Hackathon :) .  It's something we should definitely target in 2.10.4
