### ISSUE TITLE
Metrics dagrun.duration.success/failed.<dag_id> are missing in statsd exporter for airflow deployed on Kubernetes cluster

### ISSUE THREAD

**Issue by costa-danilo** [apache/airflow#43833]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

v2.10.2

### What happened?

We deployed Airflow in a Kubernetes cluster through Helm Chart (https://github.com/apache/airflow/tree/main/chart) with statds enabled, the configuration for statsd is the default one.

The issue involves being able to see most metrics except for dagrun.duration.success.<dag_id> and dagrun.duration.failed.<dag_id>

### What you think should happen instead?

The metrics dagrun.duration.success.<dag_id> and dagrun.duration.failed.<dag_id> should be visible in the exporter

### How to reproduce

1.     Deploy Airflow on Kubernetes with the official helm chart
2.     Set up Statsd exporter for metric collection
2.     Schedule sample dag runs to generate metrics
3.     dagrun.duration.success.<dag_id> and dagrun.duration.failed.<dag_id> metrics will be not be available on the statds /metrics path

### Operating System

Oracle Linux 9

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

In this issue https://github.com/apache/airflow/issues/18630 you suggest to deploy a custom Airflow image in order to enable TCPStatsClient but I am unable to do that, is there any way to do such thing through helm chart values?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rwhitley45** [comment]
I'm having the same issue with my airflow instance in K8s. Metric counts are way low:
```
# HELP statsd_exporter_metrics_total The total number of metrics.
# TYPE statsd_exporter_metrics_total gauge
statsd_exporter_metrics_total{type="counter"} 4
statsd_exporter_metrics_total{type="gauge"} 17
statsd_exporter_metrics_total{type="summary"} 11
```

**Comment by LSparkzwz** [comment]
Up

**Comment by RyanWang0811** [comment]
I find the helm chart statsd have mapping config setting
https://github.com/apache/airflow/blob/main/chart/values.yaml#L2088

the `dagrun.duration.success.<dag_id>` and `dagrun.duration.failed.<dag_id>` have been transfer.
https://github.com/apache/airflow/blob/main/chart/files/statsd-mappings.yml#L61-L69

**Comment by mamaicode** [comment]
> I find the helm chart statsd have mapping config setting https://github.com/apache/airflow/blob/main/chart/values.yaml#L2088
> 
> the `dagrun.duration.success.<dag_id>` and `dagrun.duration.failed.<dag_id>` have been transfer. https://github.com/apache/airflow/blob/main/chart/files/statsd-mappings.yml#L61-L69

Thank you so much for sharing this! Took me a while to figure it out:)
