### ISSUE TITLE
Add support of max log length for OTEL task log event

### ISSUE THREAD

**Issue by howardyoo** [apache/airflow#43868]
### Apache Airflow version

2.10.3

### What happened?

When the OTEL_TASK_LOG_EVENT is enabled, scheduler job performs extraction of the task log as span event which would get added to the task span (https://github.com/apache/airflow/blob/cf3f9c7640a5f00af0a5117b146f32994daa6fe7/airflow/jobs/scheduler_job_runner.py#L805). However, there is a risk of log entry being extremely large, that it would easily produce message that may not fit into the span event. Also, there is a potential risk of halting scheduler from running as scheduler would be busy processing it.

### What you think should happen instead?

OTEL_TASK_LOG_EVENT should support MAX length of the log entry, such that it should have a safe default value of the max length (e.g. 64k characters), which will effectively trim the task log once that max limit is reached, preventing any operational risk of scheduler if the log message is too large to be practical.

### How to reproduce

Generate a huge log (hundreds of megabytes?) and observe scheduler to hang (or causing delay) processing the log as span event.

### Operating System

Linux (amd64)

### Versions of Apache Airflow Providers

N/A

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
+1

**Comment by dstandish** [comment]
If you are talking about uploading task execution logs from the scheduler loop, this seems like still very much not a good idea.  Even if just a snippet of logs, you don't want to be retrieving connections, reading from s3, etc.  It's not the place to do that.

**Comment by potiuk** [comment]
> If you are talking about uploading task execution logs from the scheduler loop, this seems like still very much not a good idea. Even if just a snippet of logs, you don't want to be retrieving connections, reading from s3, etc. It's not the place to do that.

Who is taling about doing it from scheduler loop?

**Comment by dstandish** [comment]
that's where the code in question is right now and that's the context for this is it not?

**Comment by dstandish** [comment]
look in the top of this issue @potiuk 
<img width="698" alt="image" src="https://github.com/user-attachments/assets/eef7fc4b-0da4-429a-87ee-133981879c31">

**Comment by dstandish** [comment]
so it sounds like this issue is just about reducing the size of the log message in the area where it's currently added.

but it cannot be added ther.

**Comment by potiuk** [comment]
> that's where the code in question is right now and that's the context for this is it not?

Oh, I have not seen that - this should be definitely done from task/worker..

**Comment by dstandish** [comment]
😌

**Comment by ashb** [comment]
No, remove this feature entirely. Logs do not belong in Otel traces/spans. Use OTel logging and associate it with a span if that's what you want to do, but this code cannot exist in the scheduler.
