### ISSUE TITLE
AIP-81 Implement POST/Insert Multiple Pools in FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#43896]
### Description

Develop an endpoint in FastAPI that enables POST one or multiple `Pools` from a list. This feature should allow users to import their connections from a set of connections in a single request.

### Use case/motivation

[AIP-81](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-81+Enhanced+Security+in+CLI+via+Integration+of+API)

### Related issues

https://github.com/apache/airflow/issues/42560

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jason810496** [comment]
@bugraoz93 The issue I will take also, Thanks !
