### ISSUE TITLE
Add ability to disable SSL in Snowflake provider

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#43963]
### Description

Currently snowflake provider uses `requests` library in non-deferrable mode and `aiohttp` library in deferrable mode to make requests to snowflake URL.  It does not have the config to disable SSL

### Use case/motivation

Ability to disable ssl verification can help when connecting to Snowflake hosted via AWS private link. Often, in deferrable mode it causes following failure `certificate verify failed: Hostname mismatch, certificate is not valid`. While this works in non-deferrable mode. 

### Related issues

NA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
It's a bit problematic, I woudl very much prefer to have an easy way to configure private certificates for it. I think accessing Snowflake without SSL is REALLY bad idea - especially that almost by definition it is "somwhere else" (Yeah I understand it can be in a private network, but it is not really super secure either in this case). I'd only limit no-SSL connections to internal communication on the same node or proxy -> webapp where their network is truly internal and not accessible by any "human" in the company (which I hardly imagine possible when you communicate with Snowflake). 

It might sound excessive but it had already costed Snowflake a lot of reputation damage when their MFA was not enforced earlier this year: https://www.informationweek.com/cyber-resilience/snowflake-s-lack-of-mfa-control-leaves-companies-vulnerable-experts-say - and we can safely assume that "disabling security" should not be easy.

Maybe - if you attempt to do it, you should make sure there is big FAT warning generated when any such non-secured connection is attempted - like "THIS IS NOT SECURE, MAKE SURE THAT YOU ARE NOT CONNECTING TO PRODUCTION INSTANCE" or smth.

**Comment by eladkal** [comment]
This is not unique to Snowflake... other providers connection can have similar request.

My prespective is: No insecure features unless the provider owner is asking for it and involved in the provider maintenance. Specificly but not limited to security concerns/questions/feedback.
