### ISSUE TITLE
Broken link to docker provider example dags

### ISSUE THREAD

**Issue by juhi24** [apache/airflow#44012]
### What do you see as an issue?

There is a broken link in the [index of providers-docker](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-docker/index.rst?plain=1#L52):
```Example DAGs <https://github.com/apache/airflow/tree/providers-docker/|version|/providers/tests/system/docker>```

### Solving the problem

If the example DAGs still exist. The link should point to their location.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by amirmor1** [comment]
https://github.com/amirmor1/airflow/pull/2
