### ISSUE TITLE
Add pre-commit to validate provider __init__ is matching the template

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44024]
### Body

To avoid issues like: https://github.com/apache/airflow/pull/44017

Some info about templating of `__init__`
https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#optional-apply-template-updates

The pre commit should fail if someone modify the init to a pattern that doesn't match the template

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
FYI. There is a nice way to create an issue by maintainer - create a note in a project and convert it to the issue - this way you can bypass the meta task template :)

**Comment by potiuk** [comment]
This will not be needed after #44511 is implemented.
