### ISSUE TITLE
Trigger provider openlineage tests after assets change

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#44026]
When running selective checks, we should automatically trigger open-lineage provider tests (in main) in any PR that changes assets, as openlineage tests heavily rely on assets and are often broken after asset changes. Example https://github.com/apache/airflow/pull/44025 fixing broken test:

![Image](https://github.com/user-attachments/assets/76c8b38f-917b-48f8-af7e-e5ee375a2700)

**Comment by potiuk** [comment]
cc: @vatsrahul1001 @uranusjr => we might fix it to happen automatically (this test was broken by #41325) but kind request - until when you add new fields to assets etc, plese add "full tests needed" to the PR :)

**Comment by gopidesupavan** [comment]
Yeah running openlineage tests would be good :)

**Comment by vatsrahul1001** [comment]
@potiuk I will look into this

**Comment by potiuk** [comment]
assigned you @vatsrahul1001 !

**Comment by vatsrahul1001** [comment]
@potiuk, I was checking how selective checks work, and your [comment](https://github.com/apache/airflow/issues/43498#issuecomment-2446157132) helped me understand it better. Should we create a new` FileGroupForCi.ASSET_FILES` for all asset files and use it to trigger the open-lineage provider tests?

**Comment by potiuk** [comment]
Yes. That's likely best idea
