### ISSUE TITLE
Color Alternative - Color Blind / Deutan

### ISSUE THREAD

**Issue by supernoi** [apache/airflow#44038]
### Description

Is there an alternative color scheme for people with color blindness?  

### Use case/motivation

I have some difficulty interpreting certain information that is color-based.
It doesn't prevent me from using the application, but sometimes I find it more challenging to interpret the information.

![image](https://github.com/user-attachments/assets/1af58299-d217-4b9f-8741-6826ca884580)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
You can change the colors:
https://airflow.apache.org/docs/apache-airflow/stable/howto/customize-ui.html#customizing-state-colours
Note that dark mode is available in Airflow. 2.10 (experimental) and we have a color blind track for Airflow 3:
https://github.com/apache/airflow/issues/43054

**Comment by eladkal** [comment]
Closing as we can focus the relevant needs in #43054
