### ISSUE TITLE
Resolve mypy errors on appflow

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44111]
### Body

Following https://github.com/apache/airflow/pull/42954#discussion_r1817993084 and https://github.com/apache/airflow/pull/43436 we need to fix the issue with `mypy-boto3-appflow` and remove the type ignores.

The task:
1. Bump to `mypy-boto3-appflo>=1.35.39`
2. Apply the needed fixes to appflow code to make mypy happy without using `# type: ignore[arg-type]`

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by jx2lee** [comment]
@eladkal  Can i take this issue? assign to me, please 🚀
