### ISSUE TITLE
Helm chart airflow webserver not starting

### ISSUE THREAD

**Issue by PecTheFabricator** [apache/airflow#44159]
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

2.10.3

### Kubernetes Version

K3s

### Helm Chart configuration

I have set only my external database

### Docker Image customizations

None

### What happened

I am trying to setup the Airflow via Helm chart, all the pods is going on, except the web server. I have tried running with the default helm chart values and making some changes, but both seems to give me the same thing. After some time, the pods restart, and keep in this loop. I can't find too much information in the logs. Below is the screenshots with he logs I have access to
**Webserver Pod Log**
![image](https://github.com/user-attachments/assets/6d0b3554-c9bf-4289-818b-452a9c4f6cc9)

**Webserver Pod Describe section**
![image](https://github.com/user-attachments/assets/f051d814-c77d-4442-8da0-947c973e7c45)

### How to reproduce

1. Run the following code, without any changes in the values.yaml 
helm upgrade --install airflow apache-airflow/airflow --namespace airflow-test --create-namespace 

2. Make changes to the database and set an external database

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
Signal 15 is sometimes triggered due to insufficient resources, such as low memory. 
Can you check this?

**Comment by PecTheFabricator** [comment]
> Signal 15 is sometimes triggered due to insufficient resources, such as low memory. Can you check this?

I have tried even without setting the resources limits. The resource limits was commented. Also, the cluster memory usage is always under 50%. I will try to scale up and get back

**Comment by PecTheFabricator** [comment]
> Signal 15 is sometimes triggered due to insufficient resources, such as low memory. Can you check this?

As asked, I have increased the memory requests and limit as follow 


  resources:
    limits:
      cpu: 4
      memory: 10Gi
    requests:
      cpu: 2
      memory: 4Gi

however the error continues. What I have noticed is that the container is restarting right after the connection is denied (see 2nd screenshot in the post)

**Comment by romsharon98** [comment]
Maybe it takes more than the startupProbe and because of this it getting restart?
Try to increase `webserver.startupProbe` values

**Comment by PecTheFabricator** [comment]
> Maybe it takes more than the startupProbe and because of this it getting restart? Try to increase `webserver.startupProbe` values

Hey, thanks for the help, it worked. I just needed to increase the values in the webserver.startuProbe and it started the webserver. 
Thanks Again
