### ISSUE TITLE
Airflow s3 xcom backend - Show the xcom values in airflow UI than the s3 path for the xcom

### ISSUE THREAD

**Issue by bparamjeet** [apache/airflow#44212]
### Description

Currently while using s3 xcom backend , the result is stored in s3 path as expected but while viewing the xcom from airflow UI , the value shown is the s3 path but it would be great if we have the actual xcom value in the place.

### Use case/motivation

Usecase : It will be helpful for developers to view the xcom

### Related issues

-

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Not sure which implementation you use - but xcom backend has `orm_deserialize_value` method https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/xcom/index.html#airflow.models.xcom.BaseXCom.orm_deserialize_value that is used to produce the representation of the xcom shown in webserver. You should likely override it in the way that it shows values for small varlues (if you can make quick decision based on your knowledge about Xcom) - or just indication that the value is too big if it is - (this makes very little sense and it will crash your webserver if you display very long xcom value in the webserver).

**Comment by potiuk** [comment]
Converting to discussion.
