### ISSUE TITLE
Stats of a dynamic mapped tasks disappear after an automatic retry of a failed task

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#44245]
### Apache Airflow version

2.10.2

### What happened?

When a task gets expanded [dynamically](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html), any retried failed task makes its other stats disappear.

### How to reproduce

```python
import random
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator # add ".providers.standard" in 3

def random_fail_task(task_id):
    if random.random() < 0.5: 
        raise Exception(f"Task {task_id} failed")
    print(f"Task {task_id} succeeded")


def all_success(task_id):
    print(f"Task {task_id} succeeded")

with DAG(
    dag_id='dynamic_task_expansion',
    start_date=datetime(2023, 1, 1),
    schedule=None,
    catchup=False,
) as dag:

    tasks = PythonOperator.partial(
        task_id='task',
        retries=3, ## Change to 0 for the second coherence check
        retry_delay=timedelta(seconds=10),
        python_callable=random_fail_task, # <- Change to all_success for first coherence checks
    ).expand(op_args=[[i] for i in range(100)])
```

**Coherence checks**

1. When replacing `random_fail_task` with `random_all_success_task `, we get the exact number of tasks, all succesful (100):
![image](https://github.com/user-attachments/assets/304f9019-1339-452d-8b16-f750cccb92e2)

2. When we apply `retries=0` with `random_fail_task` the total number of tasks (succesful+failed) is once again 100:
![image](https://github.com/user-attachments/assets/2d7f47e5-7431-45bb-9b28-f0f914bd366c)

**Reproduction**
1. When running the `random_fail_task` task with `retries>=0` - some of the mapped tasks fail and are up for retry:
![image](https://github.com/user-attachments/assets/59c9d316-9004-42e2-9d78-5d7b44fa7ffe)

2. Immediately when failed tasks are triggered for re-run, some of the other tasks disappear from the UI:
![image](https://github.com/user-attachments/assets/13228a2b-a9e9-4ade-86c2-d868d24bac46)

3. And finally we're left with less tasks than what we started:
![image](https://github.com/user-attachments/assets/e136c3f2-9788-46c0-b223-58a9bda8e168)

When looking the the "Mapped Tasks" tab, all of the tasks still are still there.
---

### Operating System

Linux

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
First idea: look at the network inspector and see if the issue is in the API response or just in the presentation of the data

**Comment by shahar1** [comment]
> First idea: look at the network inspector and see if the issue is in the API response or just in the presentation of the data

Thanks for the tip! It seems like the issue is in the API response.
