### ISSUE TITLE
Check standalone_dag_processor config in get_airflow_health()

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#44253]
Right now the UI has to check the scheduler config for `standalone_dag_processor` in order to determin if the dag_processor health  check should be rendered.

It would be better if we checked for `standalone_dag_processor` in the backend and simply not return a `dag_processor` object as part of the `public/health` endpoint if False

**Comment by vatsrahul1001** [comment]
@bbovenzi would like to work on this. Can I assign it to myself?
