### ISSUE TITLE
Add Endpoint to set TI Rendered Fields

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#44359]
Create Endpoint to get TI Rendered fields on the worker and save it to DB

https://github.com/apache/airflow/blob/acf106b5a174aa8a0b27542c34e355a3ac0ef39e/airflow/models/taskinstance.py#L2915-L2916

**Comment by SuccessMoses** [comment]
Hi @amoghrajesh, are you working on this?

**Comment by amoghrajesh** [comment]
Hello! @SuccessMoses 
Yes, I am working on this one

**Comment by amoghrajesh** [comment]
The fix for this issue will cover the execution api side changes,  which expects a `dict[str, str]` to store into the RTIF table. `dict[str, str]` denotes the field: <rendered value>
