### ISSUE TITLE
Compatibility for AIP-74

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#44375]
### Body

We renamed dataset to asset for AIP-74, but it’s supposed to be completely backward compatible (DAGs on 2.x should work unchanged). We did the bulk of the work already, but missed some small ones (e.g. in the execute context). We should fix those.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Lee-W** [comment]
At least, `DatasetAll` and `DatasetAny` will need to be backported as well
