### ISSUE TITLE
Add ability to list "active" backfills both across cluster and per-dag (UI-only API -- not public)

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#44396]
### Body

child of parent issue https://github.com/apache/airflow/issues/43970

UI needs the ability to fetch the active backfill for a dag, and the list of all active backfills across the cluster. 

Add this _only_ in the UI part of the core API, so that it is not considered "public" and therefore we can change it as desired without having to wait until airflow 4.0

i.e. here:
<img width="241" alt="image" src="https://github.com/user-attachments/assets/3e06f066-0571-4027-9a8f-eddf0383fba6">

cc @jedcunningham @bbovenzi @phanikumv @pierrejeambrun 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vatsrahul1001** [comment]
cc: @prabhusneha assigning this to you.

**Comment by prabhusneha** [comment]
> cc: @prabhusneha assigning this to you.

Sure, will take this up.

**Comment by phanikumv** [comment]
Weird that @prabhusneha  is getting unassigned automatically, and that is showing up as @vatsrahul1001 unassigned it, seems to be a problem in GitHub. However it seems to be sorted now

**Comment by prabhusneha** [comment]
PR: https://github.com/apache/airflow/pull/44624

**Comment by prabhusneha** [comment]
Addressing the PR comments. 
Working on the test that are failing.
