### ISSUE TITLE
Is it possible one dag have multiple-instance with different input params

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#444]

**Comment by mistercrunch** [comment]
I'm not sure if I understand the question but you can have a function that returns different DAG instances from different parameters.

**Comment by griffinqiu** [comment]
For example:
I have a DAG that is for calculate some game standard KPIs. The data sources of the Games schema are same. But the database connection is different.
I want to start multiple Dag Instances, the DAG instances use the same Dag and different Environment variable(such as the DB connections) as start Dag params.

**Comment by mistercrunch** [comment]
Yeah, for instance you an write a function that instantiate and return a DAG object, to which you pass a different dictionary of `default_args` for instance.

Here's a heavily simplified example:

```
def make_dag(dag_id, default_args):
    dag = DAG(dag_id=dag_id, default_args=default_args)
    # create your tasks and associate them
    return dag
foo = make_dag('foo', {'mysql_conn_id': 'foo'})
bar = make_dag('foo', {'mysql_conn_id': 'bar'})
```

**Comment by griffinqiu** [comment]
I got it. Let's me try. Thank you!
