### ISSUE TITLE
Asset related REST API endpoints rework

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#44412]
### Description

We used to have `/api/v1/datasets/{uri}` in airflow 2.x and changed into `/api/v1/assets/{uri}` for airflow 3.0, but this could raise the issue as assets now have a new attribute `name.`

After discussion with @uranusjr , it should be changed into `/api/v1/assets/{name}` instead. As `Asset("s3://...")` generates an asset with name and URI set to `s3://...`, it should still make sense.

But there would be two more things to consider.

1. Whether we want to filter assets by URI 
2. Whehter we want to list the assets that are not active

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
> @jedcunningham @ephraimbuddy would like to know whether we're still returning a DAG that is deleted after DAG versioning. If not, we'll probably also not return non-active assets in the API

I think you mean a DAG whose file is deleted. If so, all we do is mark the dag as inactive, just as before. It didn't change. The only change is that the serdag for such dag won't be deleted, but previously, it would have been deleted.

**Comment by Lee-W** [comment]
> so

will we still be able to get it through REST API?

**Comment by Lee-W** [comment]
@uranusjr If my memory serves correct, we're waiting for the UI folks for this?

**Comment by uranusjr** [comment]
We already merged #44801 to solve the URI part. I’m not sure what we should do for the activeness part since we don’t have a real use case yet.

**Comment by Lee-W** [comment]
> We already merged #44801 to solve the URI part. I’m not sure what we should do for the activeness part since we don’t have a real use case yet.

ah yes, forget about that one. then I'll close this one till we have a concrete idea on what needs to be done
