### ISSUE TITLE
Migrate `TI.trigger_timeout` to `UtcDateTime`

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#44421]
Since we are working on Airflow 3, let's use this time to resolve this comment

https://github.com/apache/airflow/blob/6f0d731350674bedc320f213d55694c2df43017c/airflow/models/taskinstance.py#L1774-L1778

**Comment by rawwar** [comment]
I'm working on converting dag_run.conf from BYTEA to JSON. I think, this will be a good next issue for me. I'll pick this if no one picks by the time I finish https://github.com/apache/airflow/pull/44333

**Comment by rawwar** [comment]
@vatsrahul1001 will be working on this one.
