### ISSUE TITLE
AIP-81 Implement GET Airflow Version in REST API (FastAPI)

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#44534]
### Description

Implement an endpoint `GET` that returns the Apache Airflow version that is installed and running.
i.e. 2.10.3

### Use case/motivation

[AIP-81](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-81+Enhanced+Security+in+CLI+via+Integration+of+API)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ajay-Satish-01** [comment]
I can work on this. Please assign it to me. Thanks

**Comment by Ajay-Satish-01** [comment]
@bugraoz93  I would like to know if my thought process is right.

1. `airflow/api_fastapi/core_api/routes/public/version.py` This path already has the function of returning the version number of airflow.
2. The swagger UI for the route public/version returns  `{ "version": "3.0.0.dev0",  "git_version": null }`

So, should I remove the git_version and return version?

On the AIP-81 site, it is mentioned that
Missing: Get Airflow version
Additional Note: This API will only return the Airflow version in the running environment. The CLI version will be locally displayed.

**Comment by Ajay-Satish-01** [comment]
Sure. Thanks
