### ISSUE TITLE
 Airflow 2 to 3 auto migration rules - airflow config (~44080)

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#44555]
### Description

Parent issue: #41641

### Removal
* `smtp`
    * `smtp_user` (from #41539)
    * `smtp_password` (from #41539)
* `webserver`
    * `allow_raw_html_descriptions` (from #40029)
    * `session_lifetime_days` (from #41550) → use `session_lifetime_minutes`
    * `force_log_out_after` (from #41550) → use `session_lifetime_minutes`
* `scheduler`
    * `dependency_detector` (from #41609)
* `operators`
    * `ALLOW_ILLEGAL_ARGUMENTS` (from #41761)
* `metrics`
    * `metrics_use_pattern_match` (from #41975)
    * `timer_unit_consistency` (from #43975)
* `celery`
    * `stalled_task_timeout` (from #42060)
* `core`
    * `check_slas` (from #42285)
    * `strict_dataset_uri_validation` (from #43915)
* `logging`
    * `enable_task_context_logger` (from #43183)
* `traces`
    * `otel_task_log_event` (from #43943)

### Rename
* `scheduler`
    * `processor_poll_interval` →  `cheduler_idle_sleep_time` (from #41096)
* `metrics`
    * `statsd_allow_list` → `metrics_allow_list` (from #42088)
    * `statsd_block_list` → `metrics_block_list` (from #42088)
* cross section
    * `scheduler.statsd_on` → `metrics.statsd_on` (from #42088)
    * `scheduler.statsd_host` → `metrics.statsd_host` (from #42088)
    * `scheduler.statsd_port` → `metrics.statsd_port` (from #42088)
    * `scheduler.statsd_prefix` → `metrics.statsd_prefix` (from #42088)
    * `scheduler.statsd_allow_list` → `metrics.statsd_allow_list` (from #42088)
    * `scheduler.stat_name_handler` → `metrics.stat_name_handler` (from #42088)
    * `scheduler.statsd_datadog_enabled` → `metrics.statsd_datadog_enabled` (from #42088)
    * `scheduler.statsd_datadog_tags` → `metrics.statsd_datadog_tags` (from #42088)
    * `scheduler.statsd_datadog_metrics_tags` → `metrics.statsd_datadog_metrics_tags` (from #42088)
    * `scheduler.statsd_custom_client_path` → 
    * `core.sql_alchemy_conn` → `database.sql_alchemy_conn` (from #42126)
    * `core.sql_engine_encoding` → `database.sql_engine_encoding` (from #42126)
    * `core.sql_engine_collation_for_ids` → `database.sql_engine_collation_for_ids` (from #42126)
    * `core.sql_alchemy_pool_enabled` → `database.sql_alchemy_pool_enabled` (from #42126)
    * `core.sql_alchemy_pool_size` → `database.sql_alchemy_pool_size` (from #42126)
    * `core.sql_alchemy_max_overflow` → `database.sql_alchemy_max_overflow` (from #42126)
    * `core.sql_alchemy_pool_recycle` → `database.sql_alchemy_pool_recycle` (from #42126)
    * `core.sql_alchemy_pool_pre_ping` → `database.sql_alchemy_pool_pre_ping` (from #42126)
    * `core.sql_alchemy_schema` → `database.sql_alchemy_schema` (from #42126)
    * `core.sql_alchemy_connect_args` → `database.sql_alchemy_connect_args` (from #42126)
    * `core.load_default_connections` → `database.load_default_connections` (from #42126)
    *  `core.max_db_retries` → `database.max_db_retries` (from #42126)
    * `core.worker_precheck` → `celery.worker_precheck` (from #42129)
    * `scheduler.max_threads` → `scheduler.parsing_processes` (from #42129)
    * `celery.default_queue` → `operators.default_queue` (from #42129)
    * `admin.hide_sensitive_variable_fields` → `core.hide_sensitive_var_conn_fields` (from #42129)
    * `admin.sensitive_variable_fields` → `core.sensitive_var_conn_names` (from #42129)
    * `core.non_pooled_task_slot_count` → `core.default_pool_task_slot_count` (from #42129)
    * `core.dag_concurrency` → `core.max_active_tasks_per_dag` (from #42129)
    * `api.access_control_allow_origin` → `api.access_control_allow_origins` (from #42129)
    * `api.auth_backend` → `api.auth_backends` (from #42129)
    * `scheduler.deactivate_stale_dags_interval` → `scheduler.parsing_cleanup_interval` (from #42129)
    * `kubernetes_executor.worker_pods_pending_timeout_check_interval` → `scheduler.task_queued_timeout_check_interval` (from #42129)
    * `webserver.update_fab_perms` → `fab.update_fab_perms` (from #42129)
    * `webserver.auth_rate_limited` → `fab.auth_rate_limited` (from #42129)
    * `webserver.auth_rate_limit` → `fab.auth_rate_limit` (from #42129)
* `policy` → `task_policy` (from #41550) 
* `kubernetes` → `kubernetes_executor` (from #42129)

### Related issues

https://github.com/apache/airflow/issues/41641

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunank200** [comment]
Created the PR for `airflow config lint` : https://github.com/apache/airflow/pull/44908
