### ISSUE TITLE
AIP-84 Rework Asset API URLs to solve conflicting routes

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#44609]
The way that the Asset API was implemented (flask) and then migrated over to FastAPI contains conflicting routes:
- GET `assets/events`
- GET /assets/queuedEvents/{uri:path}
- GET `/assets/{uri:path}`
- Maybe more

**First approach** to solve this would most probably be to swap the use of `uri` as an identifier for the backend to instead use the `id` (autoincremented int) therefore resolving the possible conflicts.

**Another Approach 1**: de-nest endpoints. `GET queuedEvents/{uri:path}`, `GET `/events`

**Another Approach 2**: forbid certain keywords for asset uri creation, i.e `events`, `queuedEvents`, etc.. that are internally used by airflow.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Prab-27** [comment]
Hello @pierrejeambrun,I am a newbie and I'd like to work on this issue

**Comment by pierrejeambrun** [comment]
Hell @Prab-27,

You are assigned :) Feel free to work on that. Files for the `Asset` API are located in `airflow/api_fastapi/core_api/routes/public/assets.py`

**Comment by Prab-27** [comment]
@pierrejeambrun , There is one PR merged #44801 that changed uri: str to id: int.

Would you please tell me if I still need to de-nest the endpoints, or if this has already been resolved

**Comment by pierrejeambrun** [comment]
Thanks @Prab-27, indeed this is solved by https://github.com/apache/airflow/pull/44801. 

Closing.

Adopted solution was:
> First approach to solve this would most probably be to swap the use of uri as an identifier for the backend to instead use the id (autoincremented int) therefore resolving the possible conflicts.

**Comment by Prab-27** [comment]
@pierrejeambrun , Do `get_asset_events `and  `create_asset_event` have same path ? and do they conflict ?

**Comment by pierrejeambrun** [comment]
> @pierrejeambrun , Could you please check if `get_asset_events` and ` create_asset_event` have the same path `/assets/events`, and if they conflict?

The method is not the same ‘GET’ vs ‘POST’. That shouldn’t be a problem.
