### ISSUE TITLE
AIP-38 | Task Details Page

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#44669]
Similar to the Dag, Dag Run and Task Instance Details pages. We need a Task Details pages that lists details of a task and can summarize its Task Instances.

- Have the [Task Card](https://github.com/apache/airflow/pull/44604) in the Dag Details page link to this new Task Detail page
- Create a Task Instances list that uses the public rest API but filtered by Task_id. [Backend issue]([44670](https://github.com/apache/airflow/issues/44670))
- Add an overview page with the same TrendCountButton as the Dag Details overview page to filter the list of task instances.

**Comment by tirkarthi** [comment]
Tasks can also have docs as `doc_md` attribute which can be added similar to `Dag Docs` button to show the docs as modal in task details page.
