### ISSUE TITLE
AIP-84 Filter task instances list by task id and display name

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#44670]
Add two new filters to list task instances at `/public/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances`:

`task_id` to only return Tis with that task_id
`task_display_name_pattern` to allow a user to pass a string to search for a TI by `task_display_name` or `task_id`

**Comment by jason810496** [comment]
Hi @bbovenzi I can work on this issue, could you assign to me ? Thanks !

**Comment by bbovenzi** [comment]
@jason810496 go for it!

**Comment by tirkarthi** [comment]
There is list task instances batch to pass task_id, dag_id and other parameters as POST call.

https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch
