### ISSUE TITLE
airflow backfill fails when specifying a PythonOperator task instance and sending DAG pickle to worker

### ISSUE THREAD

**Issue by timeisapear** [apache/airflow#447]
`airflow backfill -t opc -s 2012-01-02 -e 2012-01-02 -i one_day` fails with error:

```
[2015-09-22 11:01:04,101] {models.py:902} INFO - Executing <Task(PythonOperator): opc01> on 2012-01-02 00:00:00
[2015-09-22 11:01:04,101] {models.py:959} ERROR - 'PythonOperator' object has no attribute 'params'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 904, in run
    context = self.get_template_context()
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1001, in get_template_context
    if 'tables' in task.params:
AttributeError: 'PythonOperator' object has no attribute 'params'
[2015-09-22 11:01:04,110] {models.py:995} ERROR - 'PythonOperator' object has no attribute 'params'
```

but `airflow backfill -t opc -s 2012-01-02 -e 2012-01-02 -i -x one_day` succeeds.

Offending library code:

``` python
tables = None
 if 'tables' in task.params:
     tables = task.params['tables']
```

Why is task.params sometimes set but not in this case?

**Comment by mistercrunch** [comment]
What's the type of `params['tables']`? Is it picklable?

**Comment by timeisapear** [comment]
Heh, not sure. I was hoping you could give insight since the code throwing the error is from Airflow's library, specifically https://github.com/airbnb/airflow/blob/master/airflow/models.py#L1015

**Comment by mistercrunch** [comment]
Looks like the problem is that the pickle is incomplete, it should have a `params` attribute but doesn't. There are no codepaths that I know that can cause a task to not have a `params` attribute

**Comment by timeisapear** [comment]
I have an open issue #406 that our DAG is a bit large so it has to be stored in MySQL as a longblob. Could the pickling be failing silently due to its size?

FWIW, running a backfill on the whole DAG (without specifying a task filter) does succeed, and that probably pickles the DAG since CeleryExecutor is specified.

**Comment by mistercrunch** [comment]
Does this happen consistently? It seems very odd to me. 

At Airbnb we have many DAGs that can't be pickled because they use macros that aren't picklable, so we tend to use `backfill --local` which forces a local executor, does that work for you as a fallback?

Otherwise to debug it you'd have to fire up an ipython shell, pickle the DAG by hand, unpickle it and compare the two objects, try to understand why the one that comes back has missing params. That's pretty involved...

**Comment by mtustin-handy** [comment]
I've had a similar problem, that pickles are too big. My response was to add a config option to disable pickling (it previously existed as a flag). Accordingly, if not running locally, all celery workers must have the same code available to them.
