### ISSUE TITLE
Installing sqoop provider generates error with airflow cmd

### ISSUE THREAD

**Issue by b3c0bb** [apache/airflow#44703]
### Apache Airflow version

2.10.3

### What happened?

Testing new installation of Airflow 2.10.3. If I install **apache-airflow-providers-apache-sqoop** invocations of airflow command produce the error:
 
> $ airflow info
> Traceback (most recent call last):
>   File "/usr/local/bin/airflow", line 8, in <module>
>     sys.exit(main())
>   File "/airflow/git/airflow/__main__.py", line 62, in main
>     args.func(args)
>   File "/airflow/git/airflow/cli/cli_config.py", line 49, in command
>     return func(*args, **kwargs)
>   File "/airflow/git/airflow/utils/cli.py", line 387, in _wrapper
>     f(*args, **kwargs)
>   File "/airflow/git/airflow/utils/providers_configuration_loader.py", line 54, in wrapped_function
>     ProvidersManager().initialize_providers_configuration()
>   File "/airflow/git/airflow/providers_manager.py", line 384, in wrapped_function
>     func(*args, **kwargs)
>   File "/airflow/git/airflow/providers_manager.py", line 580, in initialize_providers_configuration
>     self._initialize_providers_configuration()
>   File "/airflow/git/airflow/providers_manager.py", line 593, in _initialize_providers_configuration
>     self.initialize_providers_list()
>   File "/airflow/git/airflow/providers_manager.py", line 384, in wrapped_function
>     func(*args, **kwargs)
>   File "/airflow/git/airflow/providers_manager.py", line 495, in initialize_providers_list
>     self._discover_all_providers_from_packages()
>   File "/airflow/git/airflow/providers_manager.py", line 628, in _discover_all_providers_from_packages
>     provider_info = entry_point.load()()
>   File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 211, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'airflow.providers.apache.sqoop'

### What you think should happen instead?

I assume this error should not appear. No issues with a few other providers.

### How to reproduce

I'm installing from git branch 2.10.3 using command:
`pip install -e . -c https://raw.githubusercontent.com/apache/airflow/constraints-2.10.3/constraints-3.9.txt`

### Operating System

Rocky Linux release 8.10 (Green Obsidian)

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-sqoop==4.2.1

I also tried earlier versions

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gopidesupavan** [comment]
Sqoop provider was terminated from apache-airflow. https://airflow.apache.org/docs/apache-airflow-providers-apache-sqoop/4.2.1/changelog.html.

**Comment by b3c0bb** [comment]
Ok, thanks. I thought the provider could still be used despite being deprecated, but I guess that is not the case.

**Comment by potiuk** [comment]
Hard to say - old providers, yes can be used. but you are somehow mixing installing old airflow in editable way from a url with installing released provider. Those two have nothing to do with each other. Generally providers are never released from version branches, they are always released from main branch and editable installation just uses providers that were available in sources at the moment airflow was released. So yes - released provided are supported, but you are trying to use sources where they have already been removed and install them from there. That is not going to work

**Comment by b3c0bb** [comment]
Makes sense, thanks for the info @potiuk
