### ISSUE TITLE
providers-odbc in airflow:2.10.2 error UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91.

### ISSUE THREAD

**Issue by RamesChan** [apache/airflow#44902]
### Apache Airflow Provider(s)

odbc

### Versions of Apache Airflow Providers

apache-airflow-providers-odbc==4.7.0

### Apache Airflow version

2.7.1 and 2.10.2

### Operating System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Deployment

Docker-Compose

### Deployment details

I build arirflow from image tag 2.7.1 and 2.10.2. both image use the same Dockerfile just change the image tag. this Dockerfile will install IBM Netezza Datawarehouse ODBC Driver and copy unixODBC configulation files.

**Dockerfile**
```
FROM apache/airflow:2.10.2  #<---change tag.

USER root
RUN apt-get update
RUN apt install -y \
    nano \
    procps \
    unixodbc \
    build-essential \
    unzip
RUN rm -rf /var/lib/apt/lists/*

# ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
ENV LD_LIBRARY_PATH /usr/local/nz/lib64

COPY ./odbc/* /opt/nz_odbc

WORKDIR /opt/nz_odbc
RUN tar -xvzf nps-linuxclient-v11.2.1.10.tar.gz

WORKDIR /opt/nz_odbc/linux64
RUN ./unpack

COPY ./odbc/config/odbc.ini /etc/odbc.ini
COPY ./odbc/config/odbc.ini /usr/local/etc/odbc.ini
COPY ./odbc/config/odbcinst.ini /etc/odbcinst.ini
COPY ./odbc/config/odbcinst.ini /usr/local/etc/odbcinst.ini

USER airflow

RUN pip install apache-airflow apache-airflow-providers-odbc

WORKDIR /opt/
```

### What happened

After that I run compose up and then set connection name "nz_odbc" like this image below.
![image](https://github.com/user-attachments/assets/df3efb2a-20d8-4205-8e82-0ff4b542fb31)

and then use this python script to run DAG create table in Netezza.
```
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
from airflow.providers.odbc.hooks.odbc import OdbcHook

default_args = {
    'owner': 'MyDAG',
    'depends_on_past': False,
    'start_date': datetime(2024, 12, 13),
    'retries': 0,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    dag_id="create_table",
    default_args=default_args,
    schedule_interval="@daily"
)

def get_data_from_system_i():
    
    odbc_hook = OdbcHook(odbc_conn_id='nz_odbc')
    
    connection = odbc_hook.get_conn()

    # Set encoding (optional, depends on your driver/database)
    connection.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
    connection.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
    connection.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-8')
    connection.setencoding(encoding='utf-8')

    cursor = connection.cursor()
    
    cursor.execute("""
        CREATE TABLE EMPLOYEE (
            id int,
            name VARCHAR(50),
            department VARCHAR(50)
        )
    """)
    
    connection.commit() 
    
    cursor.close()
    connection.close()

create_table = PythonOperator(
    task_id='get_customer_data',
    python_callable=get_data_from_system_i,
    dag=dag
)

create_table
```

then it have error when I use airflow version 2.10.2 but success in version 2.7.1.

the error of airflow:2.10.2
![image](https://github.com/user-attachments/assets/3154431a-c38d-4ec7-9232-6b82b3942f2b)

### What you think should happen instead

It's Should success like airflow:2.7.1

### How to reproduce

1. install netezzaODBC driver
2. test configulation is collect by **isql**
3. run airflow dag

### Anything else

- when I try to write python script by use pyodbc and then run script in container by command "python3 main.py" in airflow2.10.2 show same error that happen in airflow log. but airflow 2.7.1 success.
- I try to install everything in ubuntu20.04 (maybe same version of airflow:2.7.1) and 22.04 (maybe same version of airflow:2.10.2) and then run the pyodbc script. it's show the same error like above.
- that mean I think ubuntu version is not nessesary. maybe airflow 2.7.1 have some configulation or installation different from others.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Hard to say - looks like it might be a combination of some of your locale and how json gets translated - and likely some changes uncovered bad configuration of your machine. I know @dabla has been improving and changing it over the last couple of months and there were changes recently in retrieving the extras.

As a quick workaroun - can yoy please downgrade your ODBC provider following https://airflow.apache.org/docs/docker-stack/build.html#example-of-setting-own-airflow-provider-packages to the version that was installed in 2.7.1 (I think from https://github.com/apache/airflow/blob/main/generated/provider_metadata.json it looks like it was 4.0.0 where in 2.10.2 it was 4.7.1  - there was quite many changes between those versions.

You can also see the changelog https://airflow.apache.org/docs/apache-airflow-providers-odbc/stable/changelog.html and see that there were many changes between. 

Ideally - maybe that something you can help us with - you could pin-point in which version of the ODBC provider it has changed. The fastest way is "bisecting" -  if it works with 4.0.0 -> you could try in the "half" between 4.0.0 and 4.7.1 and then see if it is still working (if it does - the change was introduce later, if not - it was before). Rinse and repeat until you find the exact version that causes your problem.

That could enormously help in diagnosing the root cause of the problem.

**Comment by potiuk** [comment]
So if you could make such an exercise @RamesChan and bisect which odbc provider introduces the prblem - that woudl be fantastic - maybe we will also find it will **not** work with the old ODBC provider, but that would lead to maybe other conclusions.

**Comment by dabla** [comment]
Seems like an encoding issue, but looking at your connection details I don't see anything special, unless of course there would be a special character in the password.

**Comment by dabla** [comment]
Those where the changes I made, still can't figure out how this would have impacted the encoding issue:

```
    @property
    def connection(self):
        """The Connection object with ID ``odbc_conn_id``."""
        if not self._connection:
            self._connection = self.get_connection(self.get_conn_id())
        return self._connection

    @property
    def connection_extra_lower(self) -> dict:
        """
        ``connection.extra_dejson`` but where keys are converted to lower case.

        This is used internally for case-insensitive access of odbc params.
        """
        return {k.lower(): v for k, v in self.connection.extra_dejson.items()}

    @property
    def odbc_connection_string(self):
        """
        ODBC connection string.

        We build connection string instead of using ``pyodbc.connect`` params
        because, for example, there is no param representing
        ``ApplicationIntent=ReadOnly``.  Any key-value pairs provided in
        ``Connection.extra`` will be added to the connection string.
        """
        if not self._conn_str:
            conn_str = ""
            if self.driver:
                conn_str += f"DRIVER={{{self.driver}}};"
            if self.dsn:
                conn_str += f"DSN={self.dsn};"
            if self.connection.host:
                conn_str += f"SERVER={self.connection.host};"
            database = self.database or self.connection.schema
            if database:
                conn_str += f"DATABASE={database};"
            if self.connection.login:
                conn_str += f"UID={self.connection.login};"
            if self.connection.password:
                conn_str += f"PWD={self.connection.password};"
            if self.connection.port:
                conn_str += f"PORT={self.connection.port};"

            extra_exclude = {"driver", "dsn", "connect_kwargs", "sqlalchemy_scheme", "placeholder"}
            extra_params = {
                k: v for k, v in **self.connection.extra_dejson.items()** if k.lower() not in extra_exclude
            }
            for k, v in extra_params.items():
                conn_str += f"{k}={v};"

            self._conn_str = conn_str
        return self._conn_str
```

**Comment by RamesChan** [comment]
Hello, everyone! I have some great news to share. I’ve managed to resolve the issue and identified its root cause.

The problem was related to the version of pyodbc used:

In `airflow:2.7.1`, the version of `pyodbc` is `4.0.39`.
However, in `airflow:2.10.2`, the version of `pyodbc` is `5.1.0`.
To resolve the issue, I downgraded the Python version in `airflow:2.10.2` from `3.12.x` to `3.10.12`, allowing me to install `pyodbc version 4.0.39` on `airflow:2.10.2`. After making this change, everything works perfectly! I was able to run the script and successfully connect to Netezza.

However, I have yet to verify exactly until which version of `pyodbc` my `Netezza` can support. Additionally, I haven’t checked which version of `airflow-provider-odbc` I need to use if I want to work with newer versions of `Airflow`.

I’d like to extend my gratitude to both of you @dabla @potiuk  for helping troubleshoot and identify the cause of this problem. Thank you so much!

**Comment by dabla** [comment]
> Hello, everyone! I have some great news to share. I’ve managed to resolve the issue and identified its root cause.
> 
> The problem was related to the version of pyodbc used:
> 
> In `airflow:2.7.1`, the version of `pyodbc` is `4.0.39`. However, in `airflow:2.10.2`, the version of `pyodbc` is `5.1.0`. To resolve the issue, I downgraded the Python version in `airflow:2.10.2` from `3.12.x` to `3.10.12`, allowing me to install `pyodbc version 4.0.39` on `airflow:2.10.2`. After making this change, everything works perfectly! I was able to run the script and successfully connect to Netezza.
> 
> However, I have yet to verify exactly until which version of `pyodbc` my `Netezza` can support. Additionally, I haven’t checked which version of `airflow-provider-odbc` I need to use if I want to work with newer versions of `Airflow`.
> 
> I’d like to extend my gratitude to both of you @dabla @potiuk for helping troubleshoot and identify the cause of this problem. Thank you so much!

You’re welcome, glad you found the issue and you found a workaround. We also experienced weird issues with odbc drivers in the past, not always easy to pin-point.
