### ISSUE TITLE
Inter-dag deps

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#45]
I'm trying to use the ExternalTaskSensor to execute a data processing dag upon the completion of another dag that builds some lookup tables.

My child dag's demo code is below:

```
random_dep = ExternalTaskSensor(
    external_dag_id='driver',
    external_task_id='templated',
    owner='crm',
    task_id='random_dep'
    )

run_this = PythonOperator(
    task_id='print_the_context',
    provide_context=True,
    python_callable=print_context,
    dag=dag)
run_this.set_upstream(random_dep)

task = PythonOperator(
    task_id='sleep_for_1',
    python_callable=my_sleeping_function,
    op_kwargs={'random_base': 1},
    dag=dag)

task.set_upstream(run_this)
```

Have a correctly used the ExternalTaskSensor? Ive noticed this dag isnt rendered on the "Graph View" of the frontend.

**Comment by mistercrunch** [comment]
You forgot the `dag=dag` in the `ExternalTaskSensor` call. 

`dag=dag` does the same as dag.add_task(random_dep) AND it does some magic to make sure that the dag's `default_args` and `params` get applied at the task level.

**Comment by martingrayson** [comment]
Thanks for the pointer - I've changed the code and it now renders in the webserver as expected and looks fine in the logs.

One thing though is that the sensor doesnt seem to be functioning as I'd expect. I've executed the parent task (dag=templated) using a backfill over a date range. I've then tried to backfill the child tag over the same range. I would expect the dag to run as the dependency is satisfied.

This doesnt seem to work and the dag blocks, pocking the sensor. I've had a look at ```sensors.py``` and even looked at the ```task_instance``` table in the sqllite db, and all looks fine to me...

**Comment by mistercrunch** [comment]
Can you tell me if this would fix it for you?:
https://github.com/airbnb/airflow/pull/49

**Comment by martingrayson** [comment]
I've just added comment to #49

**Comment by martingrayson** [comment]
Works for me now - closing :+1:
