### ISSUE TITLE
Allow Dynamic Tasks to be Searchable Using `map_index_template`

### ISSUE THREAD

**Issue by jayceslesar** [apache/airflow#45100]
### Description

It looks like this data is already stored in the [database](https://github.com/apache/airflow/blob/main/airflow/models/taskinstance.py#L1709) and it would be helpful if these were what is rendered/searched upon in the browse -> task instances UI given they are provided.  Happy to hack on this -- if someone can point me in the direction of where this is set up in the UI in the code that would be extremely helpful!

The existing data for dynamic task mapping in the browse -> task instances UI only allows one to search on the index value, which seems correct but provides little to no value especially in the case a user has specified a template to use instead of the default integer.

### Use case/motivation

I think this is valuable because I am never going to search for index 0 on a dynamic task, and am much more likely to use the "id" of the task which I would consider to be the values of the `map_index_template` variable that I am setting. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Given that FAB views and Airflow 2 UI will not receive active development this should be done in the new UI for Airflow 3 once browse pages are up with filter support.

**Comment by jscheffl** [comment]
Agree... until I realized that it is only 1 line of change needed...
