### ISSUE TITLE
Providing SMTP user and password from airflow.cfg or environment variables

### ISSUE THREAD

**Issue by BalaMuralibi** [apache/airflow#45114]
### Apache Airflow version

2.10.4

### What happened?

Currently airflow smtp email.py utils is not taking  ```user, password``` values from airflow.cfg/env variables, rather it gets ```user, password``` values from smtp connection https://github.com/apache/airflow/blob/main/airflow/utils/email.py#L245-L246

```
AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
AIRFLOW__SMTP__SMTP_HOST: host
AIRFLOW__SMTP__SMTP_STARTTLS: true
AIRFLOW__SMTP__SMTP_SSL: False
AIRFLOW__SMTP__SMTP_USER: "user@domain"
AIRFLOW__SMTP__SMTP_PASSWORD: 'pwd'
AIRFLOW__SMTP__SMTP_PORT: 25
AIRFLOW__SMTP__SMTP_MAIL_FROM: from@email.com 
```

### What you think should happen instead?

In production its not realistic to manually supply smtp user password in connection, thus it would be ideal to consider to get ```user and password ``` from airflow.cfg in case they are supplied ```AIRFLOW__SMTP__SMTP_USER: "user@domain"  AIRFLOW__SMTP__SMTP_PASSWORD: 'pwd' ```.

### How to reproduce

na

### Operating System

na

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

Please suggest if there is a work around to provide smtp password securely.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can provide them as connection variables: https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#storing-connections-in-environment-variables

**Comment by potiuk** [comment]
For the future - please use discussions if you have a question or doubt of that sort. Issues are for reporting problems that are airflow problems and when you want to do something and do not know how, open discussion.

**Comment by BalaMuralibi** [comment]
Thanks for your reply. I had tried with connection variable  ```AIRFLOW_CONN_SMTP_DEFAULT: smtp://$(smtpuser):$(smtppwd)@host25?disable_ssl=true ``` prior posting here. It didn't help.

**Comment by potiuk** [comment]
I have no idea if it's a good format or not or whether there are some typos or lack of variables. But you should  make sure to create your env variable using the tool we provided (just scroll down). URLs need a number of escaping - especially if your password contains special characters (this is how URL works) and the tooling we create. In the document I linked above there are both - tools that allow you to generate proper URL as well as an explanation how you can use JSON stored in an env variable to avoid escaping. I recommend you to read and follow those.
