### ISSUE TITLE
start_date not respected?

### ISSUE THREAD

**Issue by praveev** [apache/airflow#456]
I've created  a DAG as shown:

`dag = DAG('XYZ', default_args=default_args, start_date=datetime(2015, 9, 23, 23, 00), schedule_interval=timedelta(minutes=2))`

But the DAG always starts at `2015-06-01`. However subsequent executions rightly happen 2 mins later.

On a separate note, the UI shows this `2015-06-01 09:32:00` as Run time. Even if I change the Run time here, it doesn't save.

Also, can you please approve google group access? if you prefer i ask such questions in the group

**Comment by praveev** [comment]
It looks like if i use a different `dag_id` it works. Is there a cache? 
I might have used the default `2015-06-01` for `dag_id = 'XYZ'` early on but then I cancelled and changed the date to 2015-09-23. Now it doesn't respect the start date for the same  dag_id. Once i changed `dag_id='abc'`, it worked fine

**Comment by mistercrunch** [comment]
start_date is only used when "seeding" task (running for the first time), from that point on it adds the schedule_interval to the latest task instance.

From memory, the scheduler reloads the pipeline definition when it detects that the file has changed or every 10 runs.

**Comment by praveev** [comment]
Sure. But shouldn't the scheduler pick up the new start_date on restart for the same dag_id?

**Comment by mistercrunch** [comment]
Maybe it should skip ahead to the new start_date but that is not the current behavior. It's documented in both BaseOperator and The Scheduler.

**Comment by praveev** [comment]
I vote for skip ahead b/c I can't use the same dag_id anymore. will close issue for now. this can be a feature enhancement.

**Comment by mistercrunch** [comment]
Wait. You can clear the state (from the UI or CLI) and it will restart at start_date. You can also "mark success" on the run right before the one you want as your new start_date and the scheduler will pick it up from there.

**Comment by praveev** [comment]
oh ok. `airflow clear dag_id` from CLI works for me. In the UI, that dag is marked as success already.

**Comment by praveev** [comment]
Thanks CLI `airflow clear` solved it. unclear on the UI trick as that DAG is marked success already.

**Comment by mistercrunch** [comment]
You could click each children and clear with include downstream, you could clear that task with include downstream and quickly mark success right after, before the scheduler has time to retrigger the task...

**Comment by mistercrunch** [comment]
Click on one of the little square and click the Clear button from the
contextual menu. You can check all of "upstream/downstream/future/past"
prior to click clear to clear all

**Comment by praveev** [comment]
thanks

**Comment by sayap** [comment]
We found that if we want to have a new start_date, we need to do `airflow clear` first, followed by restarting the scheduler. The scheduler is not aware of the new start_date simply from loading the modified DAG file. Is this expected?
