### ISSUE TITLE
Trigger rule suspect behavior

### ISSUE THREAD

**Issue by ghost** [apache/airflow#458]
Scenario:
![screen shot 2015-09-24 at 14 11 39](https://cloud.githubusercontent.com/assets/6168354/10073015/1712beda-62c6-11e5-81c1-b1e7052f0aba.png)

Please see the picture for overview.

One job is failing out of several that are upstream from a job (the bottleneck job in the picture) that have the trigger rule set to all done. This job gets status upstream_failed _BEFORE_ being set to success (based on the trigger rule). This results in the downstream jobs also getting set to upstream_failed status and are never run, even after the trigger rule job gets status success.

So in points:
1. The failed job fails.
2. The trigger job gets status upstream_failed.
3. The downstream jobs (to the trigger job) also gets upstream_failed.
4. Now the trigger_job changes status to success.
5. The downstream jobs does NOT run.

The way we would have guessed this would work is that the trigger job should run before the downstream jobs in this situation.

We use this dag:

default_args = {
    'owner': 'cron',
    'wait_for_downstream': False,
    'depends_on_past': False,
    'start_date': datetime.datetime(2015, 9, 22, 0, 0),
}

dag = DAG('jobs', default_args=default_args, schedule_interval=timedelta(days=1))

**Comment by mistercrunch** [comment]
Got it, that is the expected behavior, the `upstream_failed` tasks need to be cleared in order to be re-evaluated. Luckily it easy to do this from the CLI and not too hard from the UI.

`upstream_failed` as all other task instance states in Airflow is not a logical state, it is persistent. Marking tasks `upstream_failed` allows for the scheduler to move on an not accumulate more dependencies to check at each run. It's important to keep the scheduler's worker close to O(n) in relation to the number of tasks.

There could be more logic in this area (recursing through downstream tasks on "mark success", and clearing the state), but it may be more tricky than it first seems (trigger_rules, other dependencies, ...)

**Comment by mistercrunch** [comment]
Nice looking DAG btw!

**Comment by ghost** [comment]
Yeah its very good looking! The user interface and easy python configuration was one of the reasons we wanted to try out airflow at my company. :)

The reason we have set up the jobs like in the graph is because we want all the extraction jobs to run first in parallell and then once they are all done, we start with the transform and export jobs (those are the jobs after the gatekeeper job).

We would like to configure airflow so that even if one of the extraction job fails, we would like the downstream jobs to still run. Because in our environment, its acceptable if it fails and we still will use data from previous successful daily extractions in the downstream jobs. We dont want to manually set the job to success since its being run in the early morning when we are sleeping. :)

Do you have any suggestions how we could accomplish this? We also tried using a ExternalTaskSensor that looks at the gatekeeper job and allowed it to be in status failure, but we still get the upstream_failed status on all the downstream tasks.

**Comment by ghost** [comment]
Hi,

We got all this to work by using an ExternalTaskSensor in the correct way. :) So for other people who wants to be able to continue running the graph even on failure or upstream_failed statuses, Im posting what we did below.

Here is our daily graph of jobs, where the extraction jobs are the upper part of the picture. These extraction jobs are sometimes going to fail, and when they do, we still want all the downstream jobs to run.

![external_task_sensor](https://cloud.githubusercontent.com/assets/6168354/10159275/982c8bf2-6697-11e5-87c0-68025a1fab01.png)

So what we did is we have a TimeSensor in the beginning of the first graph that will kick off the extraction jobs at a specific time every day. We also have a job that all the extraction jobs are leading to, called ExtractionsComplete (orange job in the pic since its in upstream_failed status). This job doesnt really do anything but we could put some testing code here to make sure we got what we expected, or whatever. 

In the second graph, we start with a ExternalTaskSensor job, checking the status of the ExtractionsComplete job. We allow the ExtractionsComplete job to be in success, failure or upstream_failed statuses.

This way, the ExternalTaskSensor will always meet its success criteria, and its downstream jobs can run.

Here is the relevant code as well:

default_args = {
    'owner': 'cron',
    'wait_for_downstream': False,
    'depends_on_past': False,
    'start_date': datetime.datetime(2015, 9, 22, 0, 0)
}

dag = DAG('jobs', default_args=default_args, schedule_interval=timedelta(days=1))

TimeSensor = TimeSensor(target_time=datetime.time(8, 00), task_id="TimeSensor", dag=dag)

ExtractionsComplete = BashOperator(task_id="ExtractionsComplete", bash_command=Scripts.AfterExtractions, dag=dag)

ExtractionsDone = ExternalTaskSensor(dag=dag, external_dag_id="jobs", task_id="ExtractionsDone", external_task_id="ExtractionsComplete", allowed_states=["success", "failed", "upstream_failed"], retry_delay=timedelta(minutes=1))

We do not have any parent to the ExtractionsDone job which is why the rest of the flow becomes a separate graph.

Hopefully this helps someone with a simular usecase as ours. :)
