### ISSUE TITLE
Pipeline specific table creation

### ISSUE THREAD

**Issue by praveev** [apache/airflow#465]
I see that new tables needed by airflow are created during `airflow initdb`. 
I also need another table for my pipeline. I would like this new table to also be created during `airflow initdb`. I know I can manually create it but this feature would be nice for deployment purposes.

How can I do this with airflow?

**Comment by mistercrunch** [comment]
Airflow manages only its own metadata in initdb. Table creation for your pipes should be handled in your pipeline file, inside operators (for example a MySqlOperator running a CREATE TABLE statement), and these tables should probably live in a different database/schema then the Airflow metadata database.

**Comment by praveev** [comment]
I am already using MySqlOperator to make changes to that table. But for creation I thought it would be cleaner if it was done along with the rest of the db setup. Also this is usually a one time thing and we really don't need a task at the beginning to find or create for this every time the DAG runs.

**Comment by mistercrunch** [comment]
These are 2 very different things, the line in the sand has to be pretty clear. On one side Airflow ships with a metadata database. On the the other you use Airflow to build data pipelines and you can decide whether you include DDL or not as part of your pipelines or not.

**Comment by praveev** [comment]
I am using the table to store metadata as well. Here's my use case - I only want one dag to be running for a specific dataset at any given point in time. So I am using a table to store its status - running, processed or failed. I have a sensor that checks with the table to decide whether or not to run the rest of the DAG for that dataset. 

Here's how the sensor works:

```
if (new data in HDFS)
    if (table status for that data is processed or failed)
        set status for that data to running
        proceed further to the next task
    else sleep and try again
```

The table is only used to store metadata for the pipeline.

**Comment by mistercrunch** [comment]
That's kind of what the `Variables` were created for:
http://pythonhosted.org/airflow/concepts.html#variables

But you know typically people don't alter the schema of an application. It would be a good thing to keep your metadata separated from the Airflow metadata database.

**Comment by cheddar** [comment]
Hrm, I don't think @praveev 's explanation is really getting at what we are actually doing.

We have some directories on hdfs like

```
/prefix_dir/table_name/2015-09-01/version_string_001/files_of_data
/prefix_dir/table_name/2015-09-01/version_string_002/files_of_data
/prefix_dir/table_name/2015-09-01/version_string_003/files_of_data
/prefix_dir/table_name/2015-09-02/version_string_001/files_of_data
/prefix_dir/table_name/2015-09-02/version_string_002/files_of_data
```

The idea here is that the newest `version_string` is the newest copy of the data for that given time period.  We are writing a sensor that watches the HDFS paths and checks what the newest version is and if it has been processed.  If the last processed version is older than the currently available version on HDFS, then we kick off the job using XCom to tell the rest of the DAG to process the relevant day of data.

So, this table stores the processed time ranges with their version.  And I'm hoping to eventually add a new thing to the airflow UI to enable viewing what time periods have been processed based on this as well as update the state flag for things like reprocessing.

Logically, the data is equivalent to what airflow likely maintains about what DAGs have been run and how they ran and stuff like that.  So, I think it does make sense alongside the other airflow tables and doing a one-off creation of it whenever we run `initdb` would be nice.  I was imagining something where essentially our extension for the sensor could also have a method that is picked up when `initdb` is called.  I don't think it makes sense for us to have yet another database up and running just to store this extra metadata about how and when jobs should be scheduled.

That said, we could totally make the sensor intelligent enough to check for the table and create it if it doesn't exist.  We were just thinking that it might be nice to have the ability to add extra stuff to the `initdb` hook.  If you are against that, then maybe once we get this running and working well, we can talk about whether our changes could be useful to be included inside airflow in general and then maybe integrate it with `initdb`.

**Comment by jlowin** [comment]
I think this is a good use case for XComs, which if you think about it are basically lightweight ways to write arbitrary data to a key-value store maintained inside the airflow db.

For example, have your task push an XCom every time it processes your data, and at the start of each processing run, check that XCom to see what that latest processed stamp was.

Pseudocode (not tested):

``` python
# use in PythonOperator
def task_func(ti, **context):
    # get last processed date from XCom (basically equivalent to querying database table)
    last_processed = ti.xcom_pull(key='last_processed_version', include_prior_dates=True)
    if not last_processed:
        last_processed = '2015-01-01'
    # get version strings
    version_strings = parse_hdfs_paths()
    # check if any versions are newer than last processed date
    needs_processing = [version for version in version_strings if version > last_processed]
    # if there are newer versions, update the XCom with the new date
    if needs_processing:
        ti.xcom_push(key='last_processed_version', value=max(needs_processing))
   # automatic XCom push for use downstream
    return needs_processing 
```

I use something along these lines to check whether a database needs to be updated.

**Comment by cheddar** [comment]
Is there an easy way to access the XCom values from a UI plugin in airflow?  Also, will it be easy to add indexes to the table such that when we write the UI as well, we can make sure the queries it is doing are acceptable?

**Comment by mistercrunch** [comment]
You can access the XComs straight through the models in your plugin.
`from airflow.models import XCom`

You can add indexes as an Alembic migration

**Comment by cheddar** [comment]
So, if I structure my XComs as something like `table-20150901-version -> current_status`, is it possible to then query and say "What versions of 2015-09-01 on table X were processed and when?"

Also, is it possible to ask "What is the current status of all days between 2015-07-01 and 2015-10-01 including the most recently processed version string for each?"

My understanding of XComs is that it is a simple key-value, so I had been assuming that such questions are not recommended...
