### ISSUE TITLE
Unable to interpolate env_vars in airflow.cfg

### ISSUE THREAD

**Issue by neovintage** [apache/airflow#470]
I'm almost positive that pull request #467 has resulted in non working interpolated config vars in the airflow.cfg file. I'm not sure what the intent was of that pull request, so I've been unable to submit a patch. 

The output of the error looks like this:

```
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '$DATABASE_URL'
```

example of what doesn't work:

```
[core]
sql_alchemy_url = $DATABASE_URL
```

**Comment by jlowin** [comment]
@neovintage something weird is definitely happening here -- I will fix it.

**Comment by jlowin** [comment]
@neovintage I got a similar error as you under Python 2 (when I wrote my comment) but since then I can't replicate it under Py2 or Py3. Are you sure you have a `$DATABASE_URL` env var set (which would be the other reason you'd see that error)? For example if you set `sql_alchemy_conn = $PATH` (or some env var you know exists) do you see it properly expanded in the error message?

**Comment by neovintage** [comment]
@jlowin It's set and I've also tried changing it to something else. When I rollback to commit ba35124d75a3ad23266c324d729e80d5267e161f and then print the output (e.g. conf.get('core', 'SQL_ALCHEMY_URL')), I end up with the correct uri. At current head, when I print the conf var I end up with '$DATABASE_URL'. I've tried blowing away my virtualenv and starting from scratch. Is there any toher output that would be useful?

**Comment by jlowin** [comment]
@neovintage ok, I was pretty sure you knew what you were doing but it never hurts to ask :). I suspect this is a weird corner case with the Py3 compatible basestring that for some reason I can never replicate (it popped up in one other issue). Could you please help me with one thing -- if you look at line 35, could you print the type of the env_var that is getting kicked out? If I'm right it'll be something like `newstr`:

``` python
def expand_env_var(env_var):
    if not isinstance(env_var, basestring):
        print(type(env_var))
        return env_var
    ...
```

Regardless, I will rework the trap a different way. Really sorry for the trouble!
