### ISSUE TITLE
Add the S3KeySensor into the dag

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#474]
I am new to the airflow, anyone can tell me how to add the S3KeySensor into the DAG ? For example : The Bucket name is "bucket_A",while the key is "production/2015/09/20",I want to check if this key exists in the aws s3.

**Comment by thomastanmin93** [comment]
How can I set the conn_id for the S3KeySensor, I set the S3KeySensor like this :
task_source_logs_files_check = S3KeySensor(
    task_id='check_source_logs_file_exists',
    bucket_key='s3://AAAAA/******',
    bucket_name='AAAAA',
    wildcard_match=True,
    dag=dag)

And run the scheduler,But I get the wrong message:
![image](https://cloud.githubusercontent.com/assets/8220811/10188402/a2b5a432-6791-11e5-9605-d644895307be.png)

**Comment by mistercrunch** [comment]
The docs are missing a parameter `s3_conn_id` which defaults to `s3_default` (I'm adding it to the docs as soon as I have a minute), you need to create this connection through the Connection menu in the UI, or using environment variables.

**Comment by thomastanmin93** [comment]
@mistercrunch  So can you give me an example about the s3_conn_id,I don't know how to config it.BTW,need I set the system environment variables for the aws access key ? Can airflow read AWS credentials or  check first for environment variables and then fall back to ~/.aws/credentials if the env variables don't exist ?

**Comment by pedrorjbr** [comment]
@Thomasmisfit  Did u solved the issue? I am facing the same problem.

**Comment by thomastanmin93** [comment]
@pedrorjbr https://github.com/airbnb/airflow/issues/123
It may help for you~~

**Comment by r39132** [comment]
So, I use boto and AWS CLI on the same server where airflow runs. Assuming boto runs on this same box, airflow will default to using boto under the hood. If you use boto, then you may have a `~/.aws/credentials` file. That will work. Just remove an config from the `extra` field on the connection edit page.

Here's an example of a using an s3 key sensor : 
https://gist.github.com/r39132/b22671d0293cd7740b38
