### ISSUE TITLE
The query stuck for hive2 

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#48]
I used a simple query for a hive2 connection. It have been sucked. I cannot get the result ;(

2015-06-19 10:20:56,647 - tornado.access - INFO - 200 GET /admin/queryview/ (10.196.11.238) 19.21ms
2015-06-19 10:21:02,962 - root - INFO - Using connection to: localhost
2015-06-19 10:21:02,965 - root - INFO - Using connection to: localhost

**Comment by mistercrunch** [comment]
Is your hiveserver2 service working properly? Can you telnet into that localhost port? Can you use pyhive directly against it?

**Comment by griffinqiu** [comment]
I found the reason, it because the authMechanism is NOSASL. My ENV is PLAIN.
The issue is strange, there is no error log, no timeout.

**Comment by griffinqiu** [comment]
Could we have the authMechanism configure in connections setting?

**Comment by mistercrunch** [comment]
Yes, I'm adding it and refactoring HiveServer2Hook a bit in the process, expect a PR today

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/71
