### ISSUE TITLE
Landing times page receives task data in way which renders unicode objects as u'code'

### ISSUE THREAD

**Issue by mtustin-handy** [apache/airflow#483]
This line

```
new Chartkick.LineChart(document.getElementById("chart-0"), [task_data_here])
```

Receives the task_data_here encoded not as real json, but in such a way that unicode object are represented with their `u` prefix. Example:

```
new Chartkick.LineChart(document.getElementById("chart-0"), [{'data': [], 'name': u'csv_export_db_table'}, {'data': [], 'name': u'export_db_table'},], {"library": {"yAxis": {"title": {"text": "hours after 00:00"}}}, "height": "700px"});
```

This is a problem because it (appears to) causes the exception `Uncaught SyntaxError: Unexpected string`

**Comment by nonlyli** [comment]
Update: This bug is not able to reproduce on v1.6.0

I got the same issue on v1.5.2

Pages:
http://domain:8080/admin/airflow/landing_times (Landing Times)
http://domain:8080/admin/airflow/duration (Task Duration)
