### ISSUE TITLE
Problem with AIRFLOW_HOME environment variable

### ISSUE THREAD

**Issue by puckel** [apache/airflow#484]
Hi,

A user opened an issue on my docker-airflow repo https://github.com/puckel/docker-airflow/issues/6

I've checked from my side the docker part and to fix the issue with log visualization I had to replace {AIRFLOW_HOME}/logs with the complete path /usr/local/airflow/logs in airflow.cfg

Then I check deeper :

```
airflow@1d5b38926fc9:~$ getent passwd |grep airflow
airflow:x:1000:1000::/usr/local/airflow:/bin/bash
airflow@1d5b38926fc9:~$ env |grep HOME
HOME=/usr/local/airflow
AIRFLOW_HOME=/usr/local/airflow
```

When I start the worker I've a new directory created :

```
airflow@222b6bb890c7:~$ pwd
/usr/local/airflow

airflow@1d5b38926fc9:~$ ls
airflow.cfg  entrypoint.sh  unittests.cfg  {AIRFLOW_HOME}

airflow@1d5b38926fc9:~$ ls \{AIRFLOW_HOME\}/
logs  unittests.cfg

airflow@1d5b38926fc9:~$ ls \{AIRFLOW_HOME\}/logs/
example_bash_operator    example_http_operator    example_xcom
example_branch_operator  example_python_operator  tutorial
```

I ran airflow worker with strace :

```
 587   stat("{AIRFLOW_HOME}/logs/example_xcom/push", 0x7ffdd21d3b40) = -1 ENOENT (No such file or directory)
587   stat("{AIRFLOW_HOME}/logs/example_xcom", 0x7ffdd21d38a0) = -1 ENOENT (No such file or directory)
587   stat("{AIRFLOW_HOME}/logs", 0x7ffdd21d3600) = -1 ENOENT (No such file or directory)
587   stat("{AIRFLOW_HOME}", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
587   stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
587   open("/usr/local/airflow/{AIRFLOW_HOME}/logs/example_xcom/push/2015-01-22T00:00:00", O_WRONLY|O_CREAT|O_APPEND, 0666) = 34
```

My airflow.cfg is the same as https://github.com/puckel/docker-airflow/blob/master/config/airflow.cfg

I've checked also the env part of configuration.py :

```
>>> import os
>>> import sys
>>> print os.environ['AIRFLOW_HOME']
/usr/local/airflow
```

**Comment by neovintage** [comment]
@puckel I'm wondering if the way I did it might fix it for you:  https://github.com/heroku/heroku-airflow/blob/master/airflow.cfg

I did have to pin airflow to a commit past the 1.5.1 release to get this to work.
