### ISSUE TITLE
Bug : Airflow test picks up new AWS API keys, but Airflow schedulers do not!

### ISSUE THREAD

**Issue by r39132** [apache/airflow#492]
How do we invalidate STS tokens when we change AWS API Access Keys that Airflow is using? It seems that `airflow test` works, but `airflow run` or anything running via the schedulers fail!

Specifically, `airflow test ep_demo purge_DLQ 2015-10-07` works but `airflow run ep_demo purge_DLQ 2015-10-07` fails!

We have changed our AWS creds on the airflow webserver, where we also run local executors and schedulers. Unfortunately, the new creds are not being picked up. We can run boto code outside of airflow and it runs correctly, picking up AWS creds from the ENV vars. However, in airflow, there seems to be a `token`. I think this token is cached and is referring to an invalid API token -- we retired the old API Key. How do I invalidate the token that airflow is using? @mistercrunch 

`[2015-10-07 16:34:47,325] {connection.py:1205} ERROR - 403 Forbidden
[2015-10-07 16:34:47,325] {connection.py:1206} ERROR - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message><Detail/></Error><RequestId>3016929b-9c59-56ca-9e92-dc14d7be036f</RequestId></ErrorResponse>
[2015-10-07 16:34:47,327] {models.py:962} ERROR - 'NoneType' object has no attribute 'count'`

**Comment by r39132** [comment]
Also, `airflow test ep_demo purge_DLQ 2015-10-07` works but `airflow run ep_demo purge_DLQ 2015-10-07` fails!

**Comment by artwr** [comment]
That's odd, in theory, the code at https://github.com/airbnb/airflow/blob/master/airflow/hooks/S3_hook.py#L140-L152 should get a new token each time. I am afraid I might be out of my depth on those internals.

The S3 hook is due for a redesign especially using boto3. If anybody wants to volunteer... :smile:

**Comment by r39132** [comment]
We don't use any AWS airflow hooks - we only use the Python and Bash operator types. Via boto, we call out AWS. Instead, we just use boto2. We don't have any problem running `airflow test`, but this is not working via the local executors at all. We have built a python script named `reload_data.py` that reload a range of days. The script calls into airflow tasks via the CLI using `airflow test`. Right now, we are exclusively using this script. Our airflow server is completely blocked since it uses executors. Any help you can provide would be helpful.

**Comment by r39132** [comment]
Also, I don't think I need to mention this, but I am able to make calls via boto in a python shell or regular boto program as well. So, it's just a problem with the local executors. I've restarted them.. etc... so I'm really wondering if there is some token caching or something being done.

**Comment by r39132** [comment]
Ok.. found the issue. A `./aws/credentials` file with a different set of creds. I figured that ENV vars always won.
