### ISSUE TITLE
Please consider using pip freeze to generate requirements.txt

### ISSUE THREAD

**Issue by jbrownlucid** [apache/airflow#508]
This is the recommended method in [pip's documentation](http://pip.readthedocs.org/en/stable/user_guide/#requirements-files). Is there a reason why we are leaving the exact versions of packages installed to be determined at the time of installation? Using floating versions of dependencies is a wonderful way to make life exciting for operators and sysadmins. If there isn't anything blocking it I'd like to humbly suggest that we follow the best practice here. I'm open to doing this myself and verifying it on a clean install if there's interest.

**Comment by mistercrunch** [comment]
`requirements.txt` doesn't do much for projects on Pypi. The dependencies for Airflow (and all projects on Pypi) are defined using setuptools, typically in a `setup.py` 
https://github.com/airbnb/airflow/blob/master/setup.py#L50

Quite a bit of thoughts went into dependencies specifications for Airflow. Fully freezing versions (as opposed to allowing ranges as it is currently) has downsides as we might miss out on security updates and bugfixes, also you might have to download multiple versions of each library to satisfy each project (you can end up with 6 versions of pandas/numpy on your system which isn't great). On the other hand there could be bugs in the community that others can't recreate which isn't great. 

I'm giving the current method a spin and if I get bit I might fully freeze.

**Comment by jbrownlucid** [comment]
Thanks for the explanation. So far Airflow is working out great for us, I just get nervous about these things sometimes.
