### ISSUE TITLE
Running custom Python scripts

### ISSUE THREAD

**Issue by jochem** [apache/airflow#520]
Hi,

I was wondering what's the preferred way of running your own Python scripts when using the PythonOperator. I'm currently defining my own methods in a DAG file, but it makes them quite long and it's not super pretty. Therefore, I am now considering to create a 'scripts' directory in the Airflow home directory so I can do 'from scripts import foo'. Does that make sense?

Also, when running Airflow from Docker with your custom scripts, some of those depend on other libraries that are not available in the container and you would basically need to rebuild the container every time a new requirement pops up. Are there any ideas to work around that?

**Comment by jlowin** [comment]
You should be able to import scripts or libraries from anywhere on `PATH` just as with any python library; Airflow adds `$AIRFLOW_HOME` to `PATH` (I believe) so a scripts folder there would work. An alternative would be to build a library with its own DAG folder and point (or symlink) the airflow DAG folder at that one.

I believe the only way to avoid rebuilding a Docker container is to use a Docker volume for shared state.

**Comment by mistercrunch** [comment]
Installing a python packages (`python setup.py install`, `pip install foo`) add it to your site-packages, which is part of your python path, meaning when you `import foo` it will find it. You can also use the PYTHONPATH environment variable to include arbitrary folders. Another method is to use sys.path, as in:

```
import sys
sys.path.append('/mnt/foo')
```

Note that for a folder to be considered a package it needs a `__init__.py` file in it.

Airflow adds your DAGS_FOLDER to your python path. So provided that you sprinkle `__init__.py` files around your pipelines, you can always do absolute imports from a pipeline to the other.

**Comment by martingrayson** [comment]
I've implemented some alerting and common functions I use in my dags. I've packaged them and reference them like @mistercrunch describes using `PYTHONPATH`, works a treat for me!

**Comment by jochem** [comment]
@jlowin It looks like Airflow does not add AIRFLOW_HOME to the path, which explains why I also can't get my airflow_login module imported.

@mistercrunch Are there specific reasons for not adding AIRFLOW_HOME to the path? If i add `sys.path.append(conf.get('core', 'airflow_home'))` to the root `__init__.py` that seems to work fine (and more convenient than prefixing every command with PYTHONPATH=...etc).

**Comment by mistercrunch** [comment]
Adding your package's root to the PYTHONPATH is a bad idea. Most packages have common module names like utils, models, app or settings. If you have multiple applications adding their root to the PYTHONPATH there's no namespacing and good luck understanding what `import settings` is actually doing. 

What you want is your app to be namespaced in the PYTHONPATH so that you can `from airflow import settings`

**Comment by mistercrunch** [comment]
Note that messing with `sys.path` is somewhat hacky or magical and it can interfere with users assumptions. Taking a certain codepath that modifies `sys.path` may result in different behavior in your imports, which can be tricky to debug.
