### ISSUE TITLE
Feature Proposal: Pull connection config from database before grabbing from environment variable

### ISSUE THREAD

**Issue by turtlemonvh** [apache/airflow#524]
In most other programs I have used, the normal order of preference for configuration variables is:

```
config file < environment variable < command line flag < run time value
```

The database values are set at run time, so I would expect them to override environment variable settings.  However, [hooks check the environment before checking the database](https://github.com/airbnb/airflow/blob/1.5.1/airflow/hooks/base_hook.py#L43).

As soon as I noticed this, I changed all my hooks to inherit from a common subclass to fix this behavior (see below), but I think that maybe this should be changed in the core of airflow.

```
class FixedPrecedenceBaseHook(BaseHook):
    @classmethod
    def get_connection(cls, conn_id):
        conn = None
        try:
            conn = random.choice(cls.get_connections(conn_id))
        except AirflowException:
            environment_uri = os.environ.get(CONN_ENV_PREFIX + conn_id.upper())
            if environment_uri:
                conn = Connection(uri=environment_uri)

        if not conn:
            raise AirflowException(
                "The conn_id `{0}` isn't defined".format(conn_id))

        if conn.host:
            logging.info("Using connection to: " + conn.host)
        return conn
```

If you agree this should be changed, I can submit a PR with the fix.

Also, while we're at it, if you are open to allowing the user to define connections in the configuration file (I could [add a section for `connections`](https://github.com/airbnb/airflow/blob/1.5.1/airflow/configuration.py)), that would be a nice way to allow the user to consistently define settings multiple ways.

Let me know what you think.

**Comment by mistercrunch** [comment]
Database values aren't set at runtime (depending on what you mean by that), they're persistent. So it seems like the more ephemeral envvars should have precedence as a way to override them. 

About the configuration file, I'm thinking about eventually moving away from the `.cfg` format and into the `settings.py` file as it's more dynamic and the native lib for cfg parsing is pretty horrible. You could actually today use a `airflow_local_settings.py` in your PYTHONPATH to define connections as a bit of code that uses the Connection model to save connection metadata in the database.

**Comment by turtlemonvh** [comment]
Thanks for getting back @mistercrunch.

The scenario that I'm driving at for database values vs environment variables is this:
- user sets an environment variable for a connection `AIRFLOW_CONN_ELASTICSEARCH` (to serve as a default location)
- user wants to update that connection to point to the new location for elasticsearch without restarting airflow
- they go to the web ui and add a connection `elasticsearch`
- but airflow keeps using the environment variable

Yeah, connection objects are persisted in the database - what I meant was that they can be _changed_ at runtime (bad choice of words on my part).

An example of a tool that takes this approach to configuration is elasticsearch.  You can modify settings via a REST api and those are persisted (technically, they are optionally persisted) between restarts of the application.

About the configuration file, I guess that makes sense.  I saw [that hook](https://github.com/airbnb/airflow/blob/1.5.1/airflow/settings.py#L69) today when looking at the code and wasn't sure what the recommended use of that is.  Using it to inject more content into the settings django-style makes sense.  Thanks for the tip.

About the switch from cfg: I can tell you that a lot of tools out there are moving to yaml, toml, or even json since they are more friendly to edit in other languages than python files.  At my company we just moved a few internal services off of python files for that reason (and also the need to play with the python path to get those formats to work).  I agree that cfg files are not super awesome.

**Comment by bolkedebruin** [comment]
@turtlemonvh If you still want this adjustment please create a Jira issue for it.
