### ISSUE TITLE
[Solved]Backfill Jobs don't support task execution time as task start time.

### ISSUE THREAD

**Issue by Yongyiw** [apache/airflow#526]
I have periodical data hook tasks using task execution time as argument. But when I launch backfill jobs, the task start time was set to the start time of backfill jobs.

![airflow_backfill](https://cloud.githubusercontent.com/assets/3275577/10590565/5722e096-767f-11e5-996f-9d060492c537.png)

Notice that all tasks use the same start time which leads to hooks fetching the data sets of same time period. I wonder why we use `bf_start_date` to set task instances' `start_time`? Any insight or consideration about this?

And by setting the `task_start_date` to `ti.execution_date`, I solved my problem,

```
class BackfillJobs:
...
    def _execute()
       executor.queue_task_instance(
                        ti,
                        mark_success=self.mark_success,
                        task_start_date=self.bf_start_date, # change to ti.execution_date
                        pickle_id=pickle_id,
                        ignore_dependencies=self.ignore_dependencies)
```

So I think maybe we can add one extra argument for `queue_task_instance()` like `use_task_execution_date` to control the which start_time to be applied to backfill task instances.

Any input will be appreciated. Thanks!

**Comment by mistercrunch** [comment]
the -s of the `airflow run` command is used internally to bypass the depends_on_past criteria on the start_date of the backfill. Meaning if your task has a `start_date` that on `2015-01-01`, but your backfill start_date is `2015-02-01`, it will disregard `depends_on_paste=True` for `2015-02-01`. It has no other effect. The `execution_date` param is the one that is matters and is the 3rd arg after `airflow run`.

**Comment by Yongyiw** [comment]
Oh! That makes sense to me. Thank you so much @mistercrunch

I believe I should use task `execution_time` instead of task `start_time` as the reference of time in my operator. And I will try to get the `execution_time` of `TaskInstance` in my operator.

**Comment by Yongyiw** [comment]
Just realize `execute()` function of operator takes `context` as an argument. I can get `execution_date` from it. Very very handy.

Great work! Thanks a lot!
