### ISSUE TITLE
How to modify the default_login file to add the user authenticate Fuction

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#534]
Hi anyone there,

I just copy/paste airflow.default_login in a airflow_login.py and set webserver.authenticate as true in my airflow.cfg. What else I should do in the file airflow_login.py ?
 I have read the flask-login doc :https://flask-login.readthedocs.org/en/latest/ ,but didn't find what I should modify in the airflow_login.py file .Need I create the login.html file for the website display ?

**Comment by bolkedebruin** [comment]
@mistercrunch maybe it is time for PR-#501?
