### ISSUE TITLE
Expose SQLAlchemy engine through method in Hooks

### ISSUE THREAD

**Issue by jackgolding** [apache/airflow#541]
Currently DBApiHook.get_conn() returns a DBAPI2 object. If there was a method which returned a SQLAlchemy engine, we could use pandas.to_sql() with this engine derived from a hook.

Does anyone else know of any benefits or a way to generate the engine from a DBAPI2 object instead?

**Comment by mistercrunch** [comment]
I've been thinking about how it'd be nice to have a `SqlAlchemyHook` to write cross db code through their expression language.

But it should be easy to write a `DbApiHook.get_sqla_engine()`. The prefix for the URI (the "mysql" in `mysql://root@localhost`) should probably be a class level param of the derivatives of `DbApiHook`. Then it's just a matter of putting together the URI from the connection object.

**Comment by jackgolding** [comment]
You couldn't get the password through the connection object could you though?

**Comment by mistercrunch** [comment]
The connection object knows how to decrypt password.
https://github.com/airbnb/airflow/blob/master/airflow/models.py#L386
