### ISSUE TITLE
Parameters ignored in dbapi_hook

### ISSUE THREAD

**Issue by jackgolding** [apache/airflow#542]
Lines 46 to 54 in gbapi_hook.py notice the function parameters is not used passed through to psql.read_sql() - quick fix is to change df = psql.read_sql(sql, con=conn) to df = psql.read_sql(sql, con=conn,params=parameters)

   def get_pandas_df(self, sql, parameters=None):
        '''
        Executes the sql and returns a pandas dataframe
        '''
        import pandas.io.sql as psql
        conn = self.get_conn()
        df = psql.read_sql(sql, con=conn)
        conn.close()
        return df

**Comment by jlowin** [comment]
@jackgolding believe that was fixed in #445 (see https://github.com/airbnb/airflow/blob/master/airflow/hooks/dbapi_hook.py#l44) -- you may need to update your airflow to see the change!
