### ISSUE TITLE
Can't mark tasks as successful if start_date > execution_date

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#544]
This line (https://github.com/airbnb/airflow/blame/master/airflow/www/app.py#L1012) from #448 raises an error if a task's `execution_date` falls before the dag's `start_date`. However, `start_date` can change for many reasons (including simply updating the DAG script with a new `start_date`). In that case, it becomes impossible to mark tasks as successful if they were generated by a previous "version" of a DAG (meaning a DAG with the same `dag_id` but a different and future `start_date`).

**Comment by bolkedebruin** [comment]
@jlowin if this is still an issue can you create a Jira for it?
