### ISSUE TITLE
Task instance progress

### ISSUE THREAD

**Issue by pierre-borckmans** [apache/airflow#549]
I'm currently investigating Airflow functionnalities.
So far, I'm impressed by its flexibility and features.

Something that I'm missing is the ability to monitor the progress of a given task.
I guess it would be possible to expose an API for the tasks to publish their progress (percentage or current step vs total steps, ...).

Would it make sense to add this functionnality in the Airflow paradigm?

I'm willing to help if I can get indications where this would fit.

Thanks

**Comment by mistercrunch** [comment]
It'd be nice to get more visibility on progress outside of the log. In some cases a job is unaware of which percentage it is at, but is aware of state or progress. For instance a task may know it has moved 20000 rows so far, without knowing how many more there are coming. 

Maybe there could be a field in the task_instance table for progress and could be used differently by different operators as a short string. Data transfer operators could post how many rows they've moved so far. Hive jobs could post which statement/phase/percentage they're at, ... 

The API is easy to implement (add a `BaseOperator.set_progress()`), the hard part is to adapt the operators to periodically adjust their progress in a meaningful way.
