### ISSUE TITLE
Most recent task information on DAGs page

### ISSUE THREAD

**Issue by toryhaavik** [apache/airflow#562]
The status bubbles are nice to provide an overall summary of each DAG, but what I'd like to see is information about the most recent task run (or currently running) for each DAG.  I can imagine it could be another column in the DAGs table that contains information like:
- task name
- execution date/time
- duration
- running/success/failure

There isn't a lot of room, so the implementation would need to be done well to convey enough information to be useful.

I'm planning on hacking on this soon, I just wanted to open this issue to see if others are interested/have thought about this as well.

**Comment by mistercrunch** [comment]
Querying the task_instance table for latest run information would definitely need to be done in an async fashion as it may take a moment to load and we don't want to hold up loading the main parts of the page  while waiting for this info.

**Comment by jlowin** [comment]
I believe this was added in #975.
