### ISSUE TITLE
hive ldap with auth=noSasl bug

### ISSUE THREAD

**Issue by zstan** [apache/airflow#567]
i have a little troube with CDH 5 cluster:
with 

```
<property>
  <name>hive.server2.authentication</name>
  <value>LDAP</value>
</property>
```

this change useful for properly working:

``` diff
diff --git a/airflow/hooks/hive_hooks.py b/airflow/hooks/hive_hooks.py
index 794c78a..ca15a64 100644
--- a/airflow/hooks/hive_hooks.py
+++ b/airflow/hooks/hive_hooks.py
@@ -86,7 +86,7 @@ class HiveCliHook(BaseHook):
                         jdbc_url = (
                             "jdbc:hive2://"
                             "{0}:{1}/{2}"
-                            ";auth=noSasl"
+                            #";auth=noSasl"
                         ).format(conn.host, conn.port, conn.schema)

                     cmd_extra += ['-u', jdbc_url]
```

i.e. NO sasl parameter need in this case, can u fix it?

**Comment by dominikbenz** [comment]
Instead of removing the "auth=noSasl" part from hive_hooks.py, it may be better to make the auth mechanism configurable from outside (e.g. we're using mapr with auth=maprsasl, and did this via a quick local fix). What would be the best place for such a configuration? I suppose the connection config? If the direction is clear, I'd be happy to contribute.

**Comment by zstan** [comment]
of course, it`s right way, appending it into Extras or whole auth config will be ok/

**Comment by bolkedebruin** [comment]
It might actually be better to parse hive-site.xml instead and to pick it up from there. Or are there case  where this config is not available? Or maybe even better make this configurable so you can do both.

**Comment by mistercrunch** [comment]
The connection's extra attributes is the way to go

**Comment by alvin1** [comment]
What I did for this type of issue was created a customized hook and operator. Get the authentication setting from the connection and check it in customized hook.

**Comment by zstan** [comment]
> > It might actually be better to parse hive-site.xml instead and to pick it up from there.
1. It`s look like implicit behavior (not good idea)
2. you need to find hive.conf and it is not so easy ... 99% it is default /etc/hive but in 1% you need to parse hive config files. Configure it into **Connections** sounds like ok.;

Oh i found that it is already realised here :

``` python
class HiveServer2Hook(BaseHook): 
...
        auth_mechanism = db.extra_dejson.get('authMechanism', 'NOSASL')
```

all you need just copy paste it there. Thanks !
