### ISSUE TITLE
[TESTS] py3.4 tests on travis often do not complete since LocalExecutor is used 

### ISSUE THREAD

**Issue by bolkedebruin** [apache/airflow#575]
Quite often the task doesn't finish and the last log snippet is repeated. I'm not sure what the cause is of this as it occasionally does finish.

INFO  [root] [backfill progress] waiting: 6 | succeeded: 0 | kicked_off: 4 | failed: 0 | wont_run: 0 
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 4 running task instances
DEBUG [root] 0 in queue
DEBUG [root] 28 open slots
INFO  [root] [backfill progress] waiting: 5 | succeeded: 1 | kicked_off: 4 | failed: 0 | wont_run: 0 
INFO  [root] Adding to queue: airflow run example_bash_operator run_after_loop 2015-01-01T00:00:00   --local     -sd DAGS_FOLDER/example_dags/example_bash_operator.py -s 2015-01-01T00:00:00 
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 3 running task instances
DEBUG [root] 1 in queue
DEBUG [root] 29 open slots
INFO  [root] [backfill progress] waiting: 2 | succeeded: 4 | kicked_off: 5 | failed: 0 | wont_run: 0 
INFO  [root] LocalWorker running airflow run example_bash_operator run_after_loop 2015-01-01T00:00:00   --local     -sd DAGS_FOLDER/example_dags/example_bash_operator.py -s 2015-01-01T00:00:00 
Logging into: /home/travis/airflow/logs/example_bash_operator/run_after_loop/2015-01-01T00:00:00
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 2 running task instances
DEBUG [root] 0 in queue
DEBUG [root] 30 open slots
INFO  [root] [backfill progress] waiting: 2 | succeeded: 4 | kicked_off: 5 | failed: 0 | wont_run: 0 
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 2 running task instances
DEBUG [root] 0 in queue
DEBUG [root] 30 open slots
INFO  [root] [backfill progress] waiting: 2 | succeeded: 4 | kicked_off: 5 | failed: 0 | wont_run: 0 
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 2 running task instances
DEBUG [root] 0 in queue
DEBUG [root] 30 open slots
INFO  [root] [backfill progress] waiting: 1 | succeeded: 5 | kicked_off: 6 | failed: 0 | wont_run: 0 
DEBUG [root] [heart] Boom.
DEBUG [root] Calling the <class 'airflow.executors.local_executor.LocalExecutor'> sync method
DEBUG [root] 1 running task instances
DEBUG [root] 0 in queue

**Comment by mistercrunch** [comment]
I know! I had the intuition that it might be from a race condition between the different builds (assuming that the 4 sub-build use the same mysql db). 

Do you know for a fact whether it's the case or if each sub-build gets its own db?

**Comment by bolkedebruin** [comment]
No, I am not absolutely sure certainly not with the docker instances they now use. I would be very surprised if it is shared though. Besides, it only happens with the python 3.4 builds not with the python 2.7 and I think that is suspicious.

I'll see if I can track something down, but in this area of Airflow I don't know my way around as easy. And, firstly, I will see if I can fix the caching because something is still off there.

**Comment by bolkedebruin** [comment]
It does definitely look like a race condition. I purged the caches and all builds finished, next build failed partially again. It also happens with py27 btw. If you restart the failed job it works. Im not sure where/why it happens. I will open an issue with the travis guys, see if they can help.
- I've fixed the caching now build times actually decrease ;-).

**Comment by bolkedebruin** [comment]
Small update: the python environments (3.4 - 2.7) share the same cache. So instead of 4 there are just 2. Don't know if this can be the cause as tox separates environments. It might point to the issue that mysql might be shared (although I still doubt this)

**Comment by bolkedebruin** [comment]
ps ax in travis environment gives:

USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  23812  1768 ?        Ss   11:07   0:00 /sbin/init
root         27  0.0  0.0  50040  2928 ?        Ss   11:07   0:00 /usr/sbin/sshd
root         33  0.0  0.0  19116   912 ?        Ss   11:07   0:00 cron
mysql        63  0.1  0.3 889320 109564 ?       Ssl  11:07   0:00 /usr/sbin/mysq
postgres    128  0.2  0.0 135464 15024 ?        S    11:07   0:00 /usr/lib/postg
postgres    181  0.0  0.0 135464  2036 ?        Ss   11:07   0:00 postgres: writ
postgres    182  0.0  0.0 135464  1544 ?        Ss   11:07   0:00 postgres: wal 
postgres    183  0.0  0.0 136284  2908 ?        Ss   11:07   0:00 postgres: auto
postgres    184  0.0  0.0  96264  1632 ?        Ss   11:07   0:00 postgres: stat
root        230  0.0  0.0  73432  3644 ?        Ss   11:07   0:00 sshd: travis [
travis      234  0.0  0.0  73432  1788 ?        R    11:07   0:00 sshd: travis@p
travis     1020  0.4  0.0  17164  6488 pts/1    Ss+  11:07   0:00 bash --login /
openldap   6078  0.0  0.1 238256 48132 ?        Ssl  11:08   0:00 /usr/sbin/slap
travis     6636  0.4  0.0  91504 12832 pts/1    S+   11:08   0:00 /home/travis/v
travis     6709  0.0  0.0  20760  1628 pts/1    S+   11:09   0:00 bash /home/tra
travis     6717  0.0  0.1 163372 51836 ?        Ssl  11:09   0:00 slapd -h ldap:
travis     6719  0.0  0.0  18160  1256 pts/1    R+   11:09   0:00 ps aux

mysql is definitely not shared.

**Comment by mistercrunch** [comment]
I changed a setting in travis to reduce parallelism to see if it helped, but I've still seen errors after that. I may just go back to a SequentialExecutor in master and see if it fixes it. We can fix this race condition or issue with LocalExecutor in a branch. 

Maybe cgroups kill extra processes? I'll try a SequentialExecutor with parallelism.

**Comment by bolkedebruin** [comment]
Might work, but as you get a dedicated 2 cpus and 4GB per build I'm not expecting that the groups are the issue. It might solve the issue for now.

**Comment by bolkedebruin** [comment]
Ah now I understand what you meant by parallel. I thought you mentioned the build parallelism.

**Comment by bolkedebruin** [comment]
Just as a reminder (if it still does not work): travis gives you 2 vCPUs, so real parallelism is limited to 2.
