### ISSUE TITLE
Want more powerful data reprocess feature

### ISSUE THREAD

**Issue by xqandpan** [apache/airflow#576]
Hi there,
I'm using airflow to process daily data. Recently I had a new data process requirement like below:
When I process data of date 2015-10-30, I need process the data of 3 days, 30 days, 15 days ago.
I use bash operator to help me do these things:
airflow clear my_dag -t ^my_task$ -c -s 2015-10-27 -e 2015-10-27
...
airflow run my_dag my_task -i -f 2015-10-27
...
But I had to manage the task execute dependence. And I had some tasks need to skip to repress, so I can't clear all. And I lose the parallel execution.
It's great if airflow can provide a easy way to reprocess any day's data, manage the dependence automatic, allow skip some specific tasks and don't lose the parallel execution.
Or is these some other solution for my requirement?

**Comment by mistercrunch** [comment]
I've never used the BashOperator to run an airflow command but I guess that's fair game. Typically we think of `clear` and `backfill` commands as manually triggered. Also note that `airflow backfill` will parallelize.

One good news is that in an upcoming branch the scheduler will actually fill in holes. So if you go back and clear sections of a DAG for previous date it will actually pick up the slack.

**Comment by alvin1** [comment]
Is it possible that to skip some task not running when processing data? I had some task only need to execute the last time, but the other tasks need to execute day by day when reprocessing data. Currently, I only can set the tasks need to skip 'Mark success' manually.

**Comment by mistercrunch** [comment]
For now you can run `airflow backfill` commands with `mark_success` prior to running your actual backfills.

There's a feature request for a `only_run_latest` flag for BaseOperator that would bake this dependency logic in you DAG and eventually in the scheduler and backfill.
