### ISSUE TITLE
Task Instances Continuing to Be Scheduled Outside of Backfill Window

### ISSUE THREAD

**Issue by Vandiver247** [apache/airflow#582]
I am currently trying to play around some more with the backfill command. However, I have run into an issue.  I created a DAG with a start date of 3 June 2016 and an End Date of 31 August 2020.  This DAG has a schedule interval of 1 hour.  Upon uploading this DAG, obviously, nothing get's scheduled since it has not reached the start date yet. Now I I run the following backfill command:

```
airflow backfill <dag_name> -s 2015-10-28 -e 2015-10-29
```

The idea is that I want to test this DAG by backfilling on some old dates, however, I still don't actually want the DAG to start running regularly until June.  Therefore, once it reaches the end date of the backfill, it should stop and continue to wait for it's actual start date.

The backfill process does correctly schedule and execute the hourly runs for the backfill window.  The problem is that after this backfill process completes, the scheduler then proceeds to continue scheduling tasks.  The scheduler continues to schedule tasks until it hits the current date and time, as though the DAG's actual start date has been changed.

I have noticed this same problem occur if I go into the UI and manually select a job instance from the DAG view and run it.  Rather than just running that one instance, it will run it, and then proceed to continue scheduling instances until it catches up to the current date.

So this leads to two questions:
1. Is this the intended functionality?
2. How can I achieve what I described above?

(I am using the CeleryExecutor.)

**Comment by mistercrunch** [comment]
It's a documented functionality that's not very intuitive. `start_date` is only used to seed the task, once task is seeded by the scheduler or say a backfill command, the scheduler just moved on.

It'd be fair game to alter the scheduler to not kick tasks off that haven't reached their start date.

**Comment by mistercrunch** [comment]
Should be fixed in 1.6 as DAG runs are only created from start_date onwards
