### ISSUE TITLE
[TESTS] Creating tests for multiple configs

### ISSUE THREAD

**Issue by bolkedebruin** [apache/airflow#589]
@mistercrunch @artwr 

I have been trying to implement tests for different authentication backends, like ldap or kerberos. This requires the possibility to change the config per test. To implement this I made the flask app be created from a factory and this works now after the adjustment of mistercrunch. I also removed the "hack" from "default_login.py" by using a different object than the User object for flask as there is no relationship required between the database representation of a User and the authentication backend. Unfortunately, I am struggling with the configuration and I can use some advice or help how to approach this.

What are the issues:
- The config is loaded in many locations and most importantly in the init of airflow itself. This makes "reloading" seemingly hard and I never got it to work reliably: travis tests failing, local tests working
- login_required is nullified if web authentication is not active. I do not get it re-activated when I put this is in the create_app and config file re-applied (ie. the module for the authentication is loaded)
- Tests did actually work when I run them separately, but not if combined with the other tests so it has definitely to with initialization and loading

I'm unsure what to do. I have been tinkering with rewriting how the config works by making it a class with class methods. Furthermore by separating the database functions out of utils to its own module to make sure the config is not needed before initialization. Still the initialization in airflow's init comes in making it very hard to factor it out. This path is pretty invasive and I am looking for alternatives before I continue down on this path.

See for work in progress my rewire_conf branch.

Thanks in advance.

**Comment by bolkedebruin** [comment]
Ok I have been digging a bit further. The main issue seems to be that the configuration is imported in the local scope of each module (ie. from configuration import conf) and thus configuration items cannot be changed after the import. A better way is to do an "import configuration".

I'll see if I can get example working and then work my way through it.

See also: http://stackoverflow.com/questions/6268278/modifying-global-variables-in-python-unittest-framework

**Comment by mistercrunch** [comment]
Well you cannot assign a new object in place of `airflow.configuration.conf` since the different module will be referencing the old object `id`, but you can alter the content of the object. I just tested that `conf.read('altered_airflow.cfg')` does adapt when the next `conf.get` is called. 

Then the only thing is to make sure that no conf.get calls are cached at the module level, we need to make sure that `conf.get` is only called in routines, not in module scope.

**Comment by bolkedebruin** [comment]
I got that. Although now I am able to have the config updated by refactoring the config calls to use the module instead. However now I am in trouble getting the decorator to use the newly configured backend. See also my branch conf_multiple.

**Comment by bolkedebruin** [comment]
Mmm. Just found out that my check if it worked or not was not checking for the right thing. There goes a couple of days out the window... :-) I might be closer than I thought.

**Comment by bolkedebruin** [comment]
Done
