### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#592]
![image](https://cloud.githubusercontent.com/assets/8220811/10932387/3c4996a0-830b-11e5-9865-413d2b7366ad.png)

When I run the dag ,I get this error ,it seems that My sqlite3 table is so large  that I cannot store task data into table ,but I think it's enough for this dag,anyone know this issue ?
![image](https://cloud.githubusercontent.com/assets/8220811/10932394/45c61f78-830b-11e5-9e2c-abe20fe18edf.png)

**Comment by mistercrunch** [comment]
I've seen the disk i/o error msg when using a LocalExecutor against a Sqlite database. Sqlite doesn't support concurrency so it fails when multiple processes try access the one db file.
