### ISSUE TITLE
Please fix the charts example provided in your documentation

### ISSUE THREAD

**Issue by r39132** [apache/airflow#598]
On http://pythonhosted.org/airflow/profiling.html, the screenshot shows a SQL statement of `select series x,y, from table`". Can you provide the actual query? 
I assume it is the query below, but even that did not work for me. I am running version 1.5.1.
`SELECT dag_id, execution_date, count(*) as ccount
from task_instance
group by dag_id, execution_date`

**Comment by mistercrunch** [comment]
The chart form screenshot is of the "create" form with its default values. It would make sense to show the form related to the chart above though.

The screenshots are dated, we need new ones. I'll wait until the next version. There are quite a few UI changes in the scheduler related PR that I'm about to land.

**Comment by r39132** [comment]
Cool. We were able to figure it out so I will add some screen shots here to help others with the following example. The first screen shot below is a chart of email message counts by organization (e.g. our client organizations) and day. Each organization (e.g. 1, 6, 7) is represented by a different series, the X-axis is day, and the y-axis is the number of email that org received. 

<img width="782" alt="screenshot 2015-11-05 08 13 26" src="https://cloud.githubusercontent.com/assets/581734/10974097/4bf6381c-8395-11e5-9a2b-5f2afaa53d6e.png">

The second screen shot represents the form underlying the chart.

<img width="802" alt="screenshot 2015-11-05 08 13 37" src="https://cloud.githubusercontent.com/assets/581734/10974099/4d25a876-8395-11e5-93bc-4c9f7f35f450.png">
