### ISSUE TITLE
Why the dag state in the ui website will disappear ?

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#605]
I met a issue. I write  a dag using PythonOperator && TimeSensor && S3KeySensor . I add it into the dag by "airflow scheduler -d ********\* -sd **/**_/_***/test.py" . It run very well at first , but I find it turns to be the following : 
![2 pic](https://cloud.githubusercontent.com/assets/8220811/11013165/cfd9dbd6-853c-11e5-9bd9-8f986fc71b75.jpg)

**Comment by thomastanmin93** [comment]
I set up the airflow in the ubuntu ,add the scheduler and then quit from the terminal . it happened to be this .Are there any ways to add the dag into scheduler permanently ?

**Comment by mistercrunch** [comment]
Did you hit the refresh button on the right side of the red rectangle in your screenshot?

If the link is not clickable it means the scheduler knows about the DAG but the web server hasn't found it yet.

**Comment by thomastanmin93** [comment]
Yes, I click the refresh button,but it still be not useful .  Any solution for this ?

**Comment by thomastanmin93** [comment]
Any way that I can use to add the dag into scheduler and show in the web permanently ? I need it to run every day .

**Comment by mistercrunch** [comment]
Leave the scheduler running, maybe restart the web server? Make sure they both point to the same `dags_folder`.

**Comment by thomastanmin93** [comment]
OK. I run the scheduler in the remote ubuntu server . it seems this issue happened when I quit the remote ubuntu from terminal .
