### ISSUE TITLE
removing dag from UI

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#609]
Is it possible to remove a DAG from UI?

I already remove the dag from dags folder,  but it still showing in the UI.

**Comment by mistercrunch** [comment]
For now the cleanup happens when re-starting the web server.

Short term solution could be to remove from the DagBag on the refresh event for that DAG, which forces people to click that refresh button on the main DAGs view, but I can't think of logical other ways as changing the DagBag's content has to take part in the scope of a web request.

Long term solution is to have a stateless web server serving serialized DAGs (pickles) from the DB

**Comment by mistercrunch** [comment]
Actually the challenge is that each worker on the webserver has its own DagBag, and that hitting a cleanup endpoint only cleans up one of the workers.

**Comment by pedrorjbr** [comment]
Thanks! I find a similiar post with the answer.

**Comment by bolkedebruin** [comment]
@mistercrunch you could also serve the dags from hbase or hdfs (or s3, nfs for that matter) which would remove the issue of separate DagBags right?

Or if syncing is required you could use inotify to monitor and send a sync command over rabbitmq to make sure the workers refresh (again I didn't look at the current code)

**Comment by mistercrunch** [comment]
Well the DagBag is an in memory representation of all the DAGs in the dags_folder. Reprocessing all the DAGs in the folder can't be done as part of a web request, it's just too long. Re-evaluating an individual DAG from a file as part of the web request is not ideal. 

Serializing the DAG to a database or caching engine (memcache or whatever k/v store or the airflow metadata db) has some issues that could be ironed out (serializing a jinja template, non-serializable object put in people's DAG's params or default_args) but may be the best bet. There are still questions as to how who drives the serialization (most likely the scheduler, but what if you don't have a scheduler running?) and how is versioning / cleanup managed... Fun stuff.

**Comment by mistercrunch** [comment]
Also note that the process of refreshing a DAG in the UI puts a timestamp in the db that is essentially expiring the DAG with a specific timestamp. The DagBag has mechanics to check that timestamp and refresh from source files if its in memory representation is older than the expiration timestamp.
