### ISSUE TITLE
Airflow operator to execute a task on AWS ECS

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#616]
Are you planning to create an operator to start task on AWS ECS?

As far as I know, the start task is a asynchronous operation. So the operator need to simulate a synchronous operation.

**Comment by mistercrunch** [comment]
We're not planning on it but I'm sure it would be useful to many in the community. The Airflow team only develops the operators that Airbnb needs. 

You indeed would need to make it seem synchronous if you want other tasks to depend on its execution. If it's hard or impossible to do, you could have a ECS trigger operator that does not execute synchronously and have some other sensor down the chain that waits for an outcome of this ECS job. You'd simply have to make it clear in the operator's documentation that this is just a trigger.

**Comment by pedrorjbr** [comment]
Thanks! I am curious. 
In Airbnb how do you execute long running jobs? Are you using hadoop/spark?
Do you have any kind of microservices architecture?

**Comment by mistercrunch** [comment]
We do execute long running jobs, actually most of our jobs are long running. We do use Hadoop/Hive/Spark/Presto/Druid and more!

I'm not sure what microservice exactly means, but I believe most of our services can't be qualified as being "micro".
