### ISSUE TITLE
Duration column in 'Task Instances' view is blank for fast tasks

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#625]
It appears that tasks that take less than one second end up with a blank value for the 'duration' column.

I'm running 1.5.2.

![image](https://cloud.githubusercontent.com/assets/167569/11135326/e2b6b268-8958-11e5-8a24-84c7b586623e.png)

**Comment by criccomini** [comment]
Running on OSX with Python 2.7

**Comment by mistercrunch** [comment]
Should be fixed in >=1.6.0 . Reopen this issue if you find that is still the case after upgrading.

**Comment by criccomini** [comment]
Confirmed. 1.6.0 upgrade fixed it.
