### ISSUE TITLE
Hourly Schedules Not Working

### ISSUE THREAD

**Issue by r39132** [apache/airflow#626]
I'd like to reference https://github.com/airbnb/airflow/issues/353  

Since I cannot re-open that ticket, I'd like to follow up here. I tried to move my DAG to hourly, a critical requirement for our business and an important milestone for the GA of a new product. Unfortunately, when I changed the schedule interval to 3600, I noticed that the `ds` parameters were not resolving beyond the day.

**Comment by mistercrunch** [comment]
{{ execution_date }} is a python datetime.datetime object, you can format it however you want. {{ execution_date.isoformat() }} or more intricate formating using the `strftime` method

**Comment by mistercrunch** [comment]
Oh and since 1.6.0 you can set `schedule_interval='@hourly'`

**Comment by r39132** [comment]
nice!

**Comment by r39132** [comment]
The upgrade to 1.6.0 and hourly is not actually working. Airflow is not honoring my DAG specified.
