### ISSUE TITLE
Refresh Database list in Data Profiling

### ISSUE THREAD

**Issue by KarthikR511** [apache/airflow#631]
How do i list my DB connections in Data profiling ---> AdHoc Query page. I only see Sqlite_default and I could able to connect to Local MySQL and dump logs into it when i run airflow scheduler -p. But I want to see MySQL DB connection in Data Profiling page to query few tables?

Thanks
Karthik

**Comment by mistercrunch** [comment]
Did you fill in the form in `Admin->Connections->Create`?

**Comment by KarthikR511** [comment]
Yes I did, do i need to restart the webserver?

**Comment by mistercrunch** [comment]
Does running `pip install airflow[mysql]` help?

The only operators and hooks that are available are the ones you have the required libs installed for.

**Comment by KarthikR511** [comment]
Thanks, it got resolved after restarting the web-server.
