### ISSUE TITLE
Task doesn't start Immediately after the dependency is met

### ISSUE THREAD

**Issue by puneethpotu** [apache/airflow#633]
Hi can someone help me with the below problem or explain what might be happening

I have a dag In which the first task is time sensor looking for 8:00 UTC and the second task which is dependent on the first time sensor task. It looks like the Time sensor succeeded at 8:00 when the time has reached, but my second task didn't start until 9:00. I have the code attached below

```
default_args = {
    'owner': 'dwh',
    'depends_on_past': True,
    'wait_for_downstream': True,
    'start_date': datetime(2015, 11, 12),
    'email': [''],
    'email_on_failure': True,
    'email_on_retry': True,
    'retries': 0,
    'schedule_interval': timedelta(1),
    'retry_interval': timedelta(minutes=15),
    'queue': 'dwh',
    # 'pool': 'backfill',
    # 'priority_weight': 10,
    # 'end_date': datetime(2016, 1, 1),
}

dag = DAG(job_name, default_args=default_args)

task_start_job = TimeSensor(
    target_time=time(8,01),
    task_id='Initiating_start_time',
    dag=dag)


task1_script="test.sh"
task1_clicks_s = NWBashScriptOperator(
    bash_script=task1_script,
    script_args=[],
    task_id='clicks_s',
    dag=dag)

task1_clicks_s.set_upstream(task_start_job)
```

**Comment by mistercrunch** [comment]
What is your scheduler's `scheduler_heartbeat_sec` set to? Are you sure the scheduler was running at the time the upstream task ended. Was there other dependencies?

**Comment by puneethpotu** [comment]
Thanks for the response. The heartbeat setting is set to `scheduler_heartbeat_sec = 5`. I think this is related to a different issue. On the celery worker the number of tasks to be executed is to 32. So though scheduler is kicking of the jobs worker was not firing them. We changed that setting to 64 and now the jobs ran fine!! Please let me know if we need to modify any other settings related to worker!

Thanks

**Comment by mistercrunch** [comment]
You may want to set up a pool with a number of slots that matches the one on all of your celery workers combined, when it goes over, task instances will show up as status "queued" in the UI.

Then you have to make sure that all tasks reference that default pool. One way to do that at the cluster level is to use the "policy" function in your local settings to enforce that pool even when it's not defined by the author of the pipeline.
