### ISSUE TITLE
Bug: Hourly start dates are not honored when a Daily DAG is converted to an Hourly DAG

### ISSUE THREAD

**Issue by r39132** [apache/airflow#638]
Hi Folks!
Hourly start dates are not being honored - I am running 1.6.0, installed from git.

I had a DAG that was daily on 1.5.1 and I recently moved to 1.6.0 and also to hourly, using the the new `@hourly` syntax as shown below. Here is my DAG definition: 

```
now = datetime.now()
START_DATE = now.replace(hour=now.time().hour-1, minute=0, second=0, microsecond=0)

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'pool': 'ep_data_pipeline',
    'start_date': START_DATE,
    'email': [import_ep_pipeline_alert_email_dl],
    'email_on_failure': import_airflow_enable_notifications,
    'email_on_retry': import_airflow_enable_notifications,
    'retries': 0,
    'retry_delay': timedelta(seconds=60),
    'priority_weight': import_airflow_priority_weight
}
dag = DAG('ep_demo', schedule_interval='@hourly', default_args=default_args)
```

A few phenomena are occurring. 
The start date for my DAG is `2015-11-14 20:00:00` as shown in the image below. 
<img width="555" alt="screenshot 2015-11-15 12 26 38" src="https://cloud.githubusercontent.com/assets/581734/11170807/2aabc544-8b94-11e5-9cf2-626b9f7e19af.png">

In tree view, you can see that there are runs being scheduled before that start date -- you will notice a clear visual division between all green runs and failed runs!

<img width="1080" alt="screenshot 2015-11-15 12 25 33" src="https://cloud.githubusercontent.com/assets/581734/11170803/0667d6aa-8b94-11e5-9917-834df2fd277f.png">

If I try to mark runs before the start date as success, I get `Exception: Wait. start_date needs to be before end_date` exception. 
<img width="1113" alt="screenshot 2015-11-15 12 31 16" src="https://cloud.githubusercontent.com/assets/581734/11170824/c9e2f060-8b94-11e5-968e-7eb54211e3db.png">

If I expand the tree view to look how far back the runs are being scheduled, I see it is being scheduled as far back as `2015-11-08 00:00:00`, which is when it was set at some point before I switched from daily to hourly. 2 images follow, the first is the expanded view of the DAG as hourly, the second is the expanded view as daily on another cloned airflow host. Both have runs starting at `2015-11-08 00:00:00`. By cloned airflow host, I just mean a fresh install of 1.6.0 on a new server but with a cloned airflow DB!

Hourly Runs start at `2015-11-08 00:00:00`
<img width="1086" alt="screenshot 2015-11-15 12 34 48" src="https://cloud.githubusercontent.com/assets/581734/11170854/9a554702-8b95-11e5-9807-318827ea2135.png">

Daily Runs start at `2015-11-08 00:00:00`
<img width="973" alt="screenshot 2015-11-15 12 39 09" src="https://cloud.githubusercontent.com/assets/581734/11170860/e9d682f0-8b95-11e5-96d1-5b0a8482d0e9.png">

I would like the start date to be honored. I don't know how to delete a DAG -- there still isn't a feature to do that -- if I could delete the DAG, I could try to reimport it as hourly to clean out any cruft in the DB. When I converted to hourly, the system started needlessly scheduling work, most of which failed.

**Comment by r39132** [comment]
@artwr @bolkedebruin : ^

**Comment by bolkedebruin** [comment]
@r39132 check issue #582 it seems similar. @mistercrunch mentioned there it should be fixed in 1.6 but maybe that needs to be 1.6.1.

**Comment by mistercrunch** [comment]
We had to make a call on where the first DAG run would be generated when migrating a DAG from 1.5 to 1.6. I didn't want to go all the way to the `min(start_date)` of the DAG for many reasons. So for DAGs with task instance history and no DAG run (thus migrating), we decided to go 5 runs back from the latest recorded task_instance, assuming that the scheduler would re-evaluate the past 5 runs, complete them and keep moving.

The transition created a few problems in a few of our 130+ DAGs at Airbnb, but it was simply a matter of altering the state of a few DAG runs and adapting to the new way of doing things, notably increasing the `concurrency` setting on some large DAGs.

Note that `start_date` is a task level param, and DagRun is a DAG level state. There are some race conditions there. There has always been some race conditions: say if you start a new DAG where task A depends on B and B's start_date is after A's, things would never have run in 1.5.

But yes, there are a few things to iron out here.

**Comment by r39132** [comment]
@mistercrunch In my case, what is the expected if I have daily runs for the past 3 months? When I move to hourly, will it fill in the missing hours?

**Comment by r39132** [comment]
I'm keeping this issue open as it may impact other people. I worked around it by: 
1. Changing my dag_id to `my_dag_v2` from `my_dag_v1`
2. Restarting the webserver and scheduler

The result was that it started a new DAG with no-history. The old DAG disappeared from the UI. The system honored the start-time of my new hourly DAG.

**Comment by bolkedebruin** [comment]
@r39132 can you create a Jira for this and link it to the AIRFLOW-20?
