### ISSUE TITLE
Recover execution date in DAG

### ISSUE THREAD

**Issue by sergiohgz** [apache/airflow#657]
Hi everyone,

I'm trying to take the execution time of a task. This is the code I made for:

``` python
interval = timedelta(days=1)
execution_dt = datetime.strptime('{{execution_date}}', "%Y-%m-%d %H:%M:%S %z") - interval

so = SampleOperator(
    task_id='With_exec_datetime',
    message="Executing dag with datetime %s" % execution_dt.isoformat(),
    dag=dag
)
```

The problem comes when executing, airflow said:

> time data '{{execution_date}}' does not match format '%Y-%m-%d %H:%M:%S'

I tried with other variables as  '{{ds}}' variable and them formats ('%Y-%m-%d') and the responses were similar.

Which is the correct way to take execution date as datetime? In which format it is recovered? I followed this python doc for this: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

Too much thanks

**Comment by jlowin** [comment]
Only certain fields are templated, indicated by the class attributes of each operator. If you add a class attribute to your Operator it should work:

``` python
class SampleOperator(BaseOperator):
    template_fields = ('bash_command',)
    def __init__(...):
        ...
```

Alternatively, use a PythonOperator and pass `provide_context=True`, then use the PythonOperator to print the `ds` object from the context.

**Comment by sergiohgz** [comment]
Well, with my SampleOperator I can take that macros with this:

``` python
so = SampleOperator(
    task_id='With_exec_datetime',
    message="Executing dag with datetime {{execution_date}}", 
    dag=dag
)
```

And it works fine, but I have a `timedelta(days=1)`, so execution date shows a day before I want. Then I will use other Operators like SimpleHttpOperator to send dates as parameters, and I need the real execution date.

In example, if I program a dag to work every day (`timedelta(days=1)`) and it is scheduled to start day 18/11/2015 at 12:00, it first execution will be 19/11/2015 with `{{execution_date}}` equal to 18/11/2015, but we need `{{execution_date}} + timedelta(days=1)` (that is 19/11/2015).

This is because we need to deal with executions after server failures. This way we can make all requests we need and won't lost data.

Thank you

**Comment by mistercrunch** [comment]
`execution_date` is a `datetime.datetime` object, and timedelta is passed as under the macro namespace (module) and accessible this way `{{ macros.timedelta }}`

This mean you can do things like `{{ (execution_date + macros.timedelta(1)).isoformat()[:10] }}`.

**Comment by sergiohgz** [comment]
Thank you @mistercrunch, finally my solution is `{{ (execution_date + dag.schedule_interval) }}`. The other side is that now I need to make more operations over these dates. I though that taking more variables with templates is a temporal solution until I understand more Jinja.

Too much thanks

**Comment by sergiohgz** [comment]
This way doesn't work because data field from SimpleHttpOperator is not templated. I make a PR with this. Other way is enabling access direct from code.

`{{ macros.timedelta }}` becomes good for calculating days, but if we work with months we use `dateutil.relativedelta.relativedelta(months=X)` and I don't believe that it is supported in macros. I'm trying to add but don't know how you made it with timedelta (you haven't got a method definition for it).

Too much thanks

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/667
