### ISSUE TITLE
task duration and landing times charts only display data for the last 30 days by default

### ISSUE THREAD

**Issue by ghost** [apache/airflow#660]
the default value for days is 30 when clicking the "task duration" link, and if a dag has been running for more than 30 days the graph won't be complete. took us awhile to figure out why we couldn't see anything when we clicked on "task duration". we now modify the "days" parameter manually, but it was not obvious what was happening at first.

**Comment by nicktgr15** [comment]
Just installed airflow and I thought that the task duration was broken until I came across this github issue. Thanks emmeljay.

**Comment by bolkedebruin** [comment]
@emmeljay please create a jira issue for this if you are still interested to have this adjusted.
