### ISSUE TITLE
Can't run multiple instances of externally triggered DAG simultaneously

### ISSUE THREAD

**Issue by yakneens** [apache/airflow#664]
I schedule 10 runs of an externally triggered DAG, each with a different payload to process, but the scheduler does not schedule tasks from runs 2-10 until the corresponding task in run 1 has finished.

I see how this makes sense for scheduled DAGs but it would be great if this could be optional for externally triggered DAGs.

**Comment by mistercrunch** [comment]
Do you have `depends_on_past` set to True? Is the `concurrency` setting of your DAG is maxed out?

**Comment by yakneens** [comment]
These are my DAG settings:

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime.datetime(2020,01,01),
    'email': ['airflow@airflow.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG("freebayes-regenotype", default_args=default_args,schedule_interval=None)
```

Concurrency is at default 16. Looks like the docs define this setting as:

"concurrency (int) – the number of task instances allowed to run concurrently"

What does that mean precisely? If I have a DAG with 100 tasks in it then 16 at a time will get scheduled? If I have 100 DAGs with 1 task each, then 16 DAG runs will get scheduled? I will play around with this setting, of course, to see the effect. 

Is there no restriction on simultaneous scheduling of multiple runs of the same DAG then? I am certain that I saw a blurb in the documentation somewhere that a task instance for a task would only get scheduled when it's predecessor run has completed.

**Comment by artwr** [comment]
Sergei,
There is a new [max_active_runs](http://pythonhosted.org/airflow/code.html#airflow.models.DAG) DAG parameter that restricts the maximum number of dag_runs that can be run. It can be changed when creating a DAG. 

Basically, number of dags currently running <= max_active_runs <= concurrency (maximum number of tasks from the same dag running at the same time across dag_runs).

I hope this helps.

Best,
Arthur

**Comment by yakneens** [comment]
Thanks, that resolved my issue.
