### ISSUE TITLE
Dags with relativedelta(months) stopped working [Bug]

### ISSUE THREAD

**Issue by sergiohgz** [apache/airflow#666]
Our dags programmed to work every month with dateutil.relativedelta library don't work with latests version of Airflow. We tried version 1.5.1 and it works perfect.

**Comment by mistercrunch** [comment]
Was that in 1.6.1 or 1.6.2? I feel like I fixed a bug there but it may not have made it out yet.

I'd recommend using the cron-like syntax in 1.6.*, we might deprecate relativedelta in the future.

**Comment by sergiohgz** [comment]
The same problem with actual code. Sorry.

If using cron-like syntax with one month, accesing to field schedule_interval with macro field what will return? I don't know any library that work with months except relativedelta. :smile:

**Comment by mistercrunch** [comment]
you can use `dag.following_schedule(execution_date)`, behind the scene it's using the `croniter` lib

**Comment by sergiohgz** [comment]
Thank you so much @mistercrunch.
Think in not deprecate relativedelta for intervals, it is a good choice to make code more readable.
