### ISSUE TITLE
Running on celery dag doesn't execute due to wrong path

### ISSUE THREAD

**Issue by bolkedebruin** [apache/airflow#669]
We have configured `dags_folder=/usr/share/airflow/dags`, this is outside AIRFLOW_HOME. DAGs in this folder cannot be executed due to the command line reading (from models.py) `-sd DAGS_FOLDER/usr/share/airflow/dags/my.py` which gets expanded in `cli.py` to `/usr/share/airflow/dags/usr/share/airflow/dags/my.py` which obviously doesn't exist. 

I'm unsure why this happens and if this is expected behaviour and we are misconfiguring.

```
if not pickle_id and self.task.dag and self.task.dag.full_filepath:
            cmd += "-sd DAGS_FOLDER/{self.task.dag.filepath} "
```

**Comment by bolkedebruin** [comment]
Digging in a bit further, it seems that it is assumed that dags_folder is a relative path to AIRFLOW_HOME. I think a check on weather dags_folder is an absolute path will solve the issue. Or it should be documented.

**Comment by mistercrunch** [comment]
Yes, it wouldn't have to be that way but I think it is the case. I can't remember whether there is a good reason for it or not.
