### ISSUE TITLE
auth parameter change for beeline (based on the newest commit 2015-11-20)

### ISSUE THREAD

**Issue by syvineckruyk** [apache/airflow#677]
oddly enough in my environment ... I am passing user, schema, and extra parameters to beeline.

{"use_beeline": true, "auth":"plain", "hive_cli_params": "-i /home/airflow/hiveconf.hql"}

The connection string is actually causing the trailing params/arguments to fail.
(-bash: -n: command not found)

enclosing the connection string in quotes has resolved the issue for me.

Would adding:
jdbc_url = '"{jdbc_url}"'.format(jdbc_url=jdbc_url) 
following:

jdbc_url = jdbc_url.format(**locals())

be acceptable to you ? It could also be done in a single statement ... but would look a bit odd.

**Comment by bolkedebruin** [comment]
@syvineckruyk would single quotes be enough? then it probably could be done higher up

**Comment by syvineckruyk** [comment]
@bolkedebruin may actually have been a mistake on my end ... need to do a few more tests and will confirm ... thanks for the help though.
