### ISSUE TITLE
Skipped state isn't propagated downstream, resulting in DAG runs stuck in running state

### ISSUE THREAD

**Issue by r39132** [apache/airflow#680]
I'm running 1.6.0

Referring to https://github.com/airbnb/airflow/issues/436, which was recently closed. I believe that should be reopened and linked to this issue. 

I am seeing 2 sorts of broken behaviour around branching and joining. This bug captures the right side of the decision, and #685 captures the left side of the decision.

I am seeing the following behavior : 

The DAG runs are complete in the picture below, except for the one that failed. I'm interested in the ones which should be skipped, but still show empty blank squares. There are 3 of them. These should all be skipped. 

<img width="549" alt="screenshot 2015-11-22 18 18 06" src="https://cloud.githubusercontent.com/assets/581734/11328761/6da0b77c-9145-11e5-8bd4-eeac81b8881a.png">

The last task in the DAG is `send_email_notification_flow_successful`, which completed. The branch operator took the branch that skips model building and immediately called `aggregate_data_spark_job`. When it did this, it skipped `build_sender_models_spark_job` and its direct downstream dependents.  

Here's the DAG view : 
<img width="900" alt="screenshot 2015-11-22 18 08 13" src="https://cloud.githubusercontent.com/assets/581734/11328686/07d6f0a6-9144-11e5-8c31-d68c266e1735.png">

Unfortunately, the state is not being recorded as skipped for those descendants (e.g. `build_cdd_...`, `build_dom_rep...`, etc...) and those are shown as permanently unrun, leaving the DAGRUN in a "running state" forever!

I am including the task definition of the `aggregate_data_spark_job` below, where I use the `trigger_rule='one_success'` :

```
aggregate_data_spark_job = BashOperator(
    task_id='aggregate_data_spark_job',
    execution_timeout=timedelta(hours=3),
    trigger_rule='one_success',
    priority_weight=5,
    pool='ep_data_pipeline_spark_tasks_only',
    bash_command=optional_aggregation_templated_command,
    params={'ENV': ENV,
            'import_spark_cluster_ip': import_spark_cluster_ip,
            'granularity_secs': import_airflow_granularity_secs,
            'compute_end_dt' : compute_end_dt},
    dag=dag)
aggregate_data_spark_job.set_upstream(check_for_successful_model_building_branch_condition)
aggregate_data_spark_job.set_upstream(check_for_time_to_build_model_branch_condition)
```

**Comment by mistercrunch** [comment]
Can you test that it is still the case on `1.6.2`? I reviewed the related 1.6.2 code and I can't think of any reason why these task instances wouldn't get skipped.

**Comment by r39132** [comment]
I didn't see a tag for 1.6.2, but I pulled head from master. I confirmed the same broken behavior. There is additionally another problem as well, which I am tracking in a separate bug : https://github.com/airbnb/airflow/issues/685

**Comment by r39132** [comment]
After disabling depends_on_past (i.e. setting it to False), this worked for me. 

Some documentation has been added at https://github.com/airbnb/airflow/commit/a3dacf6684f8bab053fa6f1fbcf16aedf26d4e6a

<img width="1052" alt="screenshot 2015-11-23 17 16 02" src="https://cloud.githubusercontent.com/assets/581734/11354997/f49e3ae0-9205-11e5-9d88-ce883773b70e.png">

**Comment by r39132** [comment]
The issue is that "depends_on_past:True" does not currently work well with branch operators.

**Comment by r39132** [comment]
This will be tracked in https://github.com/airbnb/airflow/issues/1155 so closing this!
