### ISSUE TITLE
BUG : depends on past=True is not honored!

### ISSUE THREAD

**Issue by r39132** [apache/airflow#683]
I have a brand new DAG that is hourly running on 1.6.0.

Airflow is not honoring the `'depends_on_past': True,` as shown in the tree 

```
default_args = {
    'owner': '<hidden>',
    'depends_on_past': True,
    'pool': 'ep_data_pipeline',
    'start_date': START_DATE,
    'email': [import_ep_pipeline_alert_email_dl],
    'email_on_failure': import_airflow_enable_notifications,
    'email_on_retry': import_airflow_enable_notifications,
    'retries': 0,
    'retry_delay': timedelta(seconds=60),
    'priority_weight': import_airflow_priority_weight
}
dag = DAG('ep_telemetry_v2', schedule_interval='@hourly', default_args=default_args)
```

It is not being honored. I'll add a screen shot soon. I had already cleared the UI before considering filing a bug.

**Comment by mistercrunch** [comment]
Are you using `airflow backfill` or some other entry point than the scheduler?

**Comment by r39132** [comment]
I'm just running with a scheduler, webserver, and local executors. This is being observed in the UI and this is only triggered by schedulers running hourly. Last night, 6/12 runs failed due to a transient issue.. and the run failures were random. So, the 1am and 2am runs failed, then the 3am run succeeded, and the 4am run failed, etc... This morning I awoke to seem some failed and some succeeded. I quickly fixed the source of the transient failure and reran. I don't have a tree UI screen capture to share unfortunately. 

I can share the task details for one such task : 

<img width="797" alt="screenshot 2015-11-23 13 18 39" src="https://cloud.githubusercontent.com/assets/581734/11350111/c8cbe53c-91e4-11e5-9815-c773bbc409cb.png">

**Comment by r39132** [comment]
BTW, I noticed this happening on a plain-old BashOperator. In the DAG below, the `generate_new_parquet_spark_job` was failing and the next run would ignore that the previous hour's `generate_new_parquet_spark_job` had failed and go ahead and schedule the current hour's `generate_new_parquet_spark_job` to run. Unlike other issues that I filed today, this does not involve any branching. 

<img width="814" alt="screenshot 2015-11-23 17 15 21" src="https://cloud.githubusercontent.com/assets/581734/11355148/9ce9fa6c-9207-11e5-820d-e7c5c1f79d8d.png">

**Comment by mistercrunch** [comment]
Is it possible that you've been going back and forth with `depends_on_past` True/False and maybe it got triggered at some point where `depends_on_past == False`?

**Comment by mistercrunch** [comment]
is START_DATE dynamic? because depends_on_past is disregarded for the start_date of a task (so that it can get started...).
