### ISSUE TITLE
Slack doc typo?

### ISSUE THREAD

**Issue by max-sixty** [apache/airflow#684]
http://airflow.readthedocs.org/en/latest/code.html#airflow.operators.SlackAPIOperator.execute

> SlackAPIOperator calls will not fail even if the call is not unsuccessful. It should not prevent a DAG from completing in success

Is the double (triple?) negative a typo? If Slack is down, does this raise or continue?

Thanks!

**Comment by syvineckruyk** [comment]
@MaximilianR The docs need to be updated ... ill submit a PR. A dag will fail if Slack is down ... (Slack went down for us today .. I am guessing you experienced the same)

**Comment by mistercrunch** [comment]
Somewhat unrelated but I had issue with their python client and submitted a PR to their repo that they merged but haven't release on Pypi yet...
PR here:
https://github.com/slackhq/python-slackclient/pull/48

I thought everyone would have had the same issue we had, didn't you?

**Comment by syvineckruyk** [comment]
@mistercrunch we have not encountered this issue. I will try to replicate though.

**Comment by mistercrunch** [comment]
Which version of Airflow and the Slack client are you running?

**Comment by syvineckruyk** [comment]
Gone through all versions of Airflow and currently using slackclient (0.16)

**Comment by mistercrunch** [comment]
Interesting, I'm not sure why we hit an error and you don't... You may want to try their trunk (branch master) and make sure it doesn't break your stuff. I'm pushing on them to release another version.

**Comment by rawdigits** [comment]
Just to clarify: Right now python-slackclient don't try to catch http failures so the exception should just bubble up. Is this not working properly for you somewhere?

**Comment by bolkedebruin** [comment]
if issue persists please create Jira.
