### ISSUE TITLE
Fetch log for a task

### ISSUE THREAD

**Issue by zeroware** [apache/airflow#691]
Is it possible to get the path for a given task log file inside an operator ?

I would like to create a report from several tasks by using the log files. 

EDIT : I can see that the `EmailOperator` can take a list of file attachment. Would be nice to be able to give it the log files.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/blob/master/airflow/models.py#L585

**Comment by zeroware** [comment]
Thanks a lot. 
Can I use a macro to specify the log filepath as attachment in EmailOperator ? 
Something like `{{ ti.log_filepath }}`

**Comment by mistercrunch** [comment]
Yup, it should work.
