### ISSUE TITLE
Cannot load executor plugins

### ISSUE THREAD

**Issue by syvineckruyk** [apache/airflow#692]
Operators work fine... I even tried the dummy plugin script included in the docs.

Python 2.7.10 (default, Sep 23 2015, 19:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from airflow.operators import PluginOperator
> > > from airflow.operators import PluginExecutor
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name PluginExecutor

**Comment by artwr** [comment]
Should it be `from airflow.executors import PluginExecutor` ?

**Comment by syvineckruyk** [comment]
Arthur ... good catch .. i made a mistake for this example .. however the issue remains.
Python 2.7.10 (default, Sep 23 2015, 19:22:00) 

[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from airflow.operators import PluginOperator
> > > from airflow.executors import PluginExecutor
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name PluginExecutor

**Comment by artwr** [comment]
@syvineckruyk is this still an issue? If not, can we close it?

**Comment by syvineckruyk** [comment]
@artwr Arthur i recently upgraded to 1.6.2.3 ... will try this again today and let you know. Thanks

**Comment by bolkedebruin** [comment]
Please create jira if issue persists.
