### ISSUE TITLE
Refresh screenshots in DOCS

### ISSUE THREAD

**Issue by batjko** [apache/airflow#695]
Hi,

I think it's rather useless in this state. People can't even figure out what is shown because every frame is very busy with lots of information.

Consider splitting this and just inserting several static images instead, so people can take time looking at each.

Alternatively, make it much much slower perhaps?

Many thanks.

**Comment by bolkedebruin** [comment]
@batjko best way to get it updated is to supply a new one!

**Comment by batjko** [comment]
I am not a user and have no knowledge of what this project actually is about.
I only passed by through a random link, trying to see what this repo does, and the first thing I noticed was the giant confusing gif making it hard for me to see what the author is trying to show me.

So I thought I'd leave some feedback.

**Comment by bolkedebruin** [comment]
@batjko :+1: Then thanks for the feedback

**Comment by mistercrunch** [comment]
We need to refresh the screenshots altogether, the UI has changed quite a bit since we first took them. The gif on the readme was an attempt to be nimble on real estate.

You can find static ones in the docs. http://pythonhosted.org/airflow/ui.html
