### ISSUE TITLE
How do you log print statements?

### ISSUE THREAD

**Issue by kevinmandich** [apache/airflow#70]
I'm running a few scripts via PythonOperator and was wondering how I can log print statements within these scripts. Any information would be appreciated. Thank you,

Kevin

**Comment by r39132** [comment]
Access to a logger would be ideal. We would like to log to the same files that are read by the webapp. We are running the local executor

**Comment by mistercrunch** [comment]
`import logging` and use it (`logging.info(msg)`), it will make it to the log file. Print statements probably come out on the worker's stdout. I may be able to to wire the prints to be captured and wired in the logging module. I'll take a look when I have a moment, but for now use logging.

**Comment by artwr** [comment]
```
import logging
logging.info("the message you want {}".format(variable_to_display))
```

has been working for us.

**Comment by r39132** [comment]
Thx

**Comment by kevinmandich** [comment]
Thanks all!
