### ISSUE TITLE
Variables.get tries to json-deserialize the default value

### ISSUE THREAD

**Issue by sv3ndk** [apache/airflow#701]
I have noted that if we  we try to 
- `get` a Variable with an ID that is not present in DB 
- and we specify a default value
- and we specify that the variable should be deserialized as json

Then the current logic is (correctly) falling back to the default value, but then tries to parse it as a JSON string (and should not, IMHO). 

This is directly visible in the code , if we call it with `Variable.get("thisIDDoesNotExist", default_var=42, deserialize_json=True)`:

```
    @classmethod
    @provide_session
    def get(cls, key, default_var=None, deserialize_json=False, session=None):
        obj = session.query(cls).filter(cls.key == key).first()
        if obj is None:
            if default_var is not None:
                v = default_var
            else:
                raise ValueError('Variable {} does not exist'.format(key))
        else:
            v = obj.val
        if deserialize_json and v:
            v = json.loads(v)
        return v
```

This is easy enough to fix, my question is: should we?

I believe we should, since the current behaviour implies that default values for json variable would need to be json-encoded, which is not very handy. 

[The documentation for Variables](http://pythonhosted.org/airflow/concepts.html#variables) currently does not mention the presence of `default_var`, so I assume fixing this should not break existing DAGs.

Are you OK that I submit a PR to fix this?

**Comment by svendx4f** [comment]
@mistercrunch, @artwr , could you please tell us your opinion on that one? We have a small fix w

**Comment by mistercrunch** [comment]
The PR you described is welcomed!
