### ISSUE TITLE
I am not able to schedule the job running every second

### ISSUE THREAD

**Issue by kimi0421** [apache/airflow#706]
For the test purpose, I wrote following code to test my schedule job: 

```
from airflow.models import DAG
from airflow.operators import BashOperator
from datetime import datetime, timedelta

args = {
    'owner': 'airflow',
    'start_date': datetime(2015, 12, 1),
}

dag = DAG(dag_id='cat_test',
          default_args=args,
          schedule_interval=timedelta(seconds=1))

cmd = 'echo hello > /home/hello.txt'

t1 = BashOperator(task_id='cat_hello',
                  bash_command=cmd,
                  dag=dag)
```

And I can see in the UI, it is 
![image](https://cloud.githubusercontent.com/assets/3711468/11509008/9efdf17e-9896-11e5-9d0d-0f7b2fff99f9.png)

But the problem is, it never runs automatically every second. I have to launch DAG manually.

**Comment by mistercrunch** [comment]
It makes no sense to use a batch workflow engine to run every second. Airflow is not meant for realtime and arguably not even for close-to-realtime. 

I'd suggest never going under 5 minutes. Hourly / daily is the zone of comfort. 5 minutes is probably overhead heavy.

**Comment by kimi0421** [comment]
@mistercrunch Actually, I will never do that in the production, I am just trying to test it will run automatically, and see the result for the testing purpose. But the problem, it never runs. I am not sure where did I do wrong.
