### ISSUE TITLE
airflow on windows

### ISSUE THREAD

**Issue by afarbos** [apache/airflow#709]
When I execute `airflow webserver` in a windows shell, I obtain this error message:

```
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\users\afarbos\desktop\airflow\env\scripts\gunicorn.exe\__main__.py", line 5, in <module>
  File "c:\users\afarbos\desktop\airflow\env\lib\site-packages\gunicorn\app\wsgiapp.py", line 10, in <module>
    from gunicorn.app.base import Application
  File "c:\users\afarbos\desktop\airflow\env\lib\site-packages\gunicorn\app\base.py", line 12, in <module>
    from gunicorn import util
  File "c:\users\afarbos\desktop\airflow\env\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ImportError: No module named fcntl
```

It seems that fcntl does not work on windows (http://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows). Is that normal ? does airflow support windows ?

**Comment by artwr** [comment]
@hevy-CC4477,
Unfortunately, our shift to gunicorn as the application server made airflow incompatible with windows : 
http://stackoverflow.com/questions/11087682/does-gunicorn-run-on-windows

I do not think we plan on supporting windows at this point, and since we do not have machines that run windows would have a hard time testing against it.

**Comment by afarbos** [comment]
Does that only impact the web server? Or other functionality are also impacted?

**Comment by mistercrunch** [comment]
NT4 support is on the roadmap, we'll then attack Windows Server 2000 and work our way up.

**Comment by mistercrunch** [comment]
just kidding

**Comment by artwr** [comment]
It would impact the web server, as well as the way we serve/visualize the logs currently. The main issue is that the webserver is baked into the tool, but I do not think that the worker and scheduler are affected by this. Then again, I have not tested it, so I cannot vouch for compatibility.

**Comment by pascalknapen** [comment]
I tried to get just an airflow worker to run on windows and hit a lot of issues (log naming incompatible with the file system, relying on shebangs, ... ). I ended up creating a winrm operator. I hope this helps ...

**Comment by afarbos** [comment]
Yes, you answer to my question thanks.
