### ISSUE TITLE
how to handle crashes

### ISSUE THREAD

**Issue by afarbos** [apache/airflow#710]
I want to know how to handle cases where everything goes wrong, I am not too much worry for the workers, queue or db. I already know how their up time  or how they handle crashes.

But, I am still not sure to understand how works airflow. I assume that you a server or a process that know when to add stuff in the queue to respect the dag. Am I right ? if yes, how can I handle a crashes ? (can I duplicate this server/process on a other container ?).

**Comment by bolkedebruin** [comment]
Please use the mailinglist for these kind of questions.
