### ISSUE TITLE
Broken tree view Base Date picker 

### ISSUE THREAD

**Issue by kerzhner** [apache/airflow#711]
With version 1.6.1, we are seeing the following:
1. Go to Tree View for any DAG.
2. Change Base Date to be in the future to observe future runs that have not started yet.
3. Click Apply, then click Go.
3. Observe that the Tree base date remains unchanged.

We sometimes use Airflow UI to mark an entire, future DAG run as successful. Right now, this use case is broken.

Anyone else seeing this behavior?

**Comment by garthcn** [comment]
+1

**Comment by EvanWillms** [comment]
+1

**Comment by bolkedebruin** [comment]
@kerzhner is this still an issue with the latest releases? Can you then please create a Jira for it?
