### ISSUE TITLE
DAG is not running as expected 

### ISSUE THREAD

**Issue by kimi0421** [apache/airflow#713]
Sorry, since I can't reopen the issue, I post the problem here. I would like schedule a job running every hour, but the problem it never runs. 

```
from airflow.models import DAG
from airflow.operators import BashOperator
from datetime import datetime, timedelta

args = {
    'owner': 'airflow',
    'start_date': datetime.now() - timedelta(minutes=5),
}

dag = DAG(dag_id='cat_test',
          default_args=args,
          schedule_interval='0 * * * *')

cmd = 'echo hello > /home/kimi/hello.txt'

t1 = BashOperator(task_id='cat_hello',
                  bash_command=cmd,
                  dag=dag)
```

Code is above, did I do something wrong? After load the dag, what should I do? The dag is never triggered. I was expecting it would run like normal cron job.

**Comment by kimi0421** [comment]
And the problem is when I run: 

```
airflow scheduler
```

I will schedule all the job from 2015-10-01, but right now is 2015-12-02, did I do something wrong? Where to set the configurations. After I load the DAG, should I run the following command?

```
airflow trigger_dag [dag_id]
```

**Comment by mistercrunch** [comment]
http://pythonhosted.org/airflow/faq.html

"Is your start_date set properly? The Airflow scheduler triggers the task soon after the start_date + scheduler_interval is passed."

You need your start date to before now-schedule_interval
