### ISSUE TITLE
Should we skip a task if its trigger rule is `all_success` and any of its upstream tasks are skipped?

### ISSUE THREAD

**Issue by lamdrew** [apache/airflow#718]
Running Airflow 1.6.1. I have a task that has two parents:
1. A task that can be marked skipped by a `PythonBranchOperator`
2. Another task that is always triggered

The task's `trigger_rule` is `all_success`. When one of the upstream tasks is skipped, this task is never triggered and is left in limbo. I would expect this task to be marked as skipped. 

Maybe in `are_dependencies_met`, the logic should look something like:

``` python
- if skipped >= len(task._upstream_list):
+ if skipped >= len(task._upstream_list) or (task.trigger_rule == TR.ALL_SUCCESS and skipped > 0):
```

**Comment by mistercrunch** [comment]
That sounds absolutely right, there may be more limbo cases like this one in the dependency engine. We do not use a lot of branching at Airbnb so this hasn't come up yet on our side.

Please send a PR!

**Comment by lamdrew** [comment]
Along the same vein as the original post, here's another limbo case.

I have a task with two parents. The task's `trigger_rule` is `all_success`. One of the parents succeeded but the other parent was marked as `upstream_failed`. This task is never scheduled.

``` python
- elif failed + upstream_failed >= len(task._upstream_list):
+ elif (failed + upstream_failed >= len(task._upstream_list) or
+   (task.trigger_rule == TR.ALL_SUCCESS and upstream_failed > 0)):
```
