### ISSUE TITLE
Can we see DAG as a function ?

### ISSUE THREAD

**Issue by afarbos** [apache/airflow#719]
After looking at some other issue and the code also, dags seems to be super static.

For example, if I have a dag that can process one image. If I want to process ten image on the same way, I will need to create ten dags, right? If yes, could we not see dags as a function and in this case we could execute the same dag with the file name of the image as dag parameter.

**Comment by EvanWillms** [comment]
After some trial and error, it appears DAG objects are only collected into the DagBag if they're referenced as a module local variable.  Since dag configuration is pure python code, it is quite possible (if not entirely straightforward) to programmatically build variant DAGs.

```
create_dags = ['first_dag', 'second_dag']
for dag_name in create_dags:
    new_dag = DAG(
        dag_name,
        start_date=start_date,
        schedule_interval=schedule_interval,
        default_args=default_args
    )
    locals()[dag_name] = new_dag
    del new_dag
```
