### ISSUE TITLE
Documentation guidelines

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#72]
We'd like to use comments within our dags to generate job specific documentation.

This will enable us to version control, maintain and easily produce maintainable and understandable DAGs without the overheads of writing separate documents.

This seems fairly straight forward using docstring conventions. However, I'd like to provide useful comments that explain the logic within each task within a DAG. Is there a way to use sphinx (or something similar) to generate documentation? It would be brilliant if we could produce html/pdf/any format documentation that detailed each task and its dependencies/inputs etc..

**Comment by mistercrunch** [comment]
There's a special undocumented feature to squeeze documentation at a task level. All you need to do is

```
foo = SomeOperator(...)
foo.doc = "This task does nothing"
```

This will render in the "Task Details" page in the header section.

There's also `task.doc_yaml` and `task.doc_json` that will actually render using nice language aware color coding. I could easily add `task.doc_markup` and/or `task.doc_rst`.

We could add more hook, say at the DAG level too and render it somewhere (as a header in the Graph view?). Though for now if you put a docstring on your DAG module you'll see it in the "Code" view.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/74

**Comment by martingrayson** [comment]
This looks brilliant! Is there also a way of using the ``.doc` attribute in something like sphynx or at least some way of getting such comments out of the airflow ecosystem for use in a doc library for developers?

**Comment by mistercrunch** [comment]
Not sure, the sphinx automagic works out of class doctrings, not object content. 

But it would be easy to put something together in the DAG object that would gather the `doc_md` string from the DAG object and all the tasks in the DAG and put together some a raw html page.

**Comment by mistercrunch** [comment]
I'm closing this for now, but it shouldn't be hard to create a `DAG.generate_html_docs()` method at this point. I won't be writing it myself since we use the Airflow UI to display the eventual docs.
