### ISSUE TITLE
Keep connections on default in resetdb

### ISSUE THREAD

**Issue by jackgolding** [apache/airflow#720]
resetdb seems to be an easy way to fix problems and muck around when you aren't too worried about previous run results. The problem is that resetdb deletes the connection table. I think there should be a flag to keep the connection table, curious as to what others think.

**Comment by mistercrunch** [comment]
I'm extremely afraid of things that make it easy to nuke everything. Muscle memory and context shift don't play well together. Someone developing a plugin nuked production a few months back with a resetdb. I prefer not spending time restoring backups and playing catchup.

Write yourself a script, name it `jack_nukes_airflow_dev.py`, hardcode the connection string in there and don't share it with anyone :)

**Comment by jackgolding** [comment]
No worries, just thought it might be useful to add a "keep connections" parameter in `airflow resetdb`

Running `delete from log; delete from job; delete from dag; delete from dag_pickle; delete from task_instance; delete from job;` seems to have stuffed up all my charts, so its probably not a good to do that :+1:
