### ISSUE TITLE
Add configuration option in airflow.cfg for Flask APPLICATION_ROOT

### ISSUE THREAD

**Issue by boxysean** [apache/airflow#726]
For various reasons, I might not have the flexibility to use a domain or subdomain root, e.g., `airflow.myorg.com`) as the entry point to Airflow. Instead I may have to use something like `myorg.com/airflow/`.

Fortunately Flask has the `APPLICATION_ROOT` configuration option which could help me enable this access mode for the Airflow webserver easily, [explained here](http://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes).

I believe this feature is added in two steps:
1. Add configuration option logic to flow from airflow.cfg to instantiation of Flask.
2. Go through existing template files and convert to using `url_for` (e.g. [here](https://github.com/airbnb/airflow/blob/f8046512172f37ffde72fa99d787fc0e609f70ab/airflow/contrib/plugins/metastore_browser/templates/metastore_browser/base.html#L17)).
3. (hidden step) Encourage other contributors to use `url_for` going forward.

Thanks for this project!

**Comment by mistercrunch** [comment]
I would bless a PR doing all this :)

**Comment by marcelmfs** [comment]
Here is what I did to achieve this without messing with flask code (too much):

1) replaced every instance of '/admin' to '/relative/uri'
2) proxy_pass '/relative/uri/' to 'http://localhost:8080/relative/uri/;'
3) extracted all static files to be served by a different webserver and served with caching directives (/usr/lib/python2.7/site-packages/airflow-egg(?.*)/airflow/templates/www/static/ really messy shit here)

**Comment by bolkedebruin** [comment]
@boxysean is this still an issue for you? If so can you please create a Jira for it?

**Comment by marcelmfs** [comment]
As for 1.7.0 stands, yes it's still missing the feature to be able to configure `APPLICATION_ROOT`.

**Comment by boxysean** [comment]
Added issue to JIRA, [AIRFLOW-82](https://issues.apache.org/jira/browse/AIRFLOW-82)
