### ISSUE TITLE
Question about scheduler

### ISSUE THREAD

**Issue by kimi0421** [apache/airflow#734]
Maybe I didn't understand airflow so well, and it's a dummy question. 

If I would like to run the dag which has schedule_interval every day, like cron job, do I need keep 

```
airflow scheduler 
```

running all the time? If so, in production, how can I make it running in the backend or in a daemon mode. If 
    airflow scheduler

running all the time will it have any performance issues?

**Comment by bolkedebruin** [comment]
Yes you will need to run it constantly as the scheduler triggers the running of jobs. You can compare it to cron but it is just a bit more sophisticated. It is pretty light weight so the scheduler itself should not end up in performance issues quickly. 

To run it as a daemon you need to wrap it in a init.d script or use a systemd unit. For systemd unit have a look in the scripts/systemd directory.
