### ISSUE TITLE
What is the warning about schedule_interval?

### ISSUE THREAD

**Issue by Tjorriemorrie** [apache/airflow#741]
I receive this warning:

> WARNING:root:schedule_interval is used for <Task(BashOperator): import_retire_activebase>, though it has been deprecated as a task parameter, you need to specify it as a DAG parameter instead

I have my `schedule_interval` on my args_default parameters that I pass onto the Dag(). It was previously on the tasks, but I would prefer to have it on the DAG. The warning seems to say otherwise? (or I'm unsure why I get a warning when I'm doing it correctly?) Can you please clear this up, it's confusing.

**Comment by mistercrunch** [comment]
schedule_interval is now a DAG object argument, not a task object argument.

default_args or the DAG is a dictionary of defaults for task level arguments

```
DAG("mydagid", schedule_interval='@daily', default_args=d)
```

where the dict `d` does NOT contain schedule_interval

We used to allow for tasks on different schedule_interval in the same DAG, but that was confusing so now we enforce it as a DAG level param.

**Comment by Tjorriemorrie** [comment]
Thanks!

**Comment by cwong99** [comment]
I am on version 1.6.1.
I am seeing lots of warning but the schedule_interval is not specified at the task level for a BashOperator.
WARNING:root:schedule_interval is used for <Task(BashOperator): print_date>, though it has been deprecated as a task parameter, you need to specify it as a DAG parameter instead

And this is the operator:
t1 = BashOperator(
    task_id='print_date',
    queue='dev',
    bash_command='hostname',
    dag=dag)

**Comment by cwong99** [comment]
Nevermind, I got it now. Schedule_interval was in the default_args.  I have to move it to the dag.
