### ISSUE TITLE
Show connections defined in environment variables in GUI

### ISSUE THREAD

**Issue by sergiohgz** [apache/airflow#754]
Hello @mistercrunch,

I saw that connections defined in environment variables are not showing in Admin>Connections because that table is taken from database. I think a beauty enhancement based in drawing also connections defined in environment variables and, because we cannot modify system env, make them unchangeable.

It would be reasonable :smile: 

Thank you

**Comment by mistercrunch** [comment]
We don't use that feature at Airbnb so we probably won't work on it. But from a design perspective you could have a read only table above the current crud section. We'll be happy to review a PR doing this.

**Comment by neovintage** [comment]
We typically recommend using config var (env variables) when working with anything connection related on Heroku. That's how we connect to other dbs when using Airflow. I'd love to see this too.
