### ISSUE TITLE
Issues with scheduler (using celery) after upgrade to 1.6.1

### ISSUE THREAD

**Issue by smueller1245** [apache/airflow#757]
Hi,

First, many thanks for developing and open sourcing Airflow. We have been using it for the past few months and it has greatly improved our workflow process.

After upgrading to 1.6.1, we've had a few troubles with the scheduler.
1. Pools that existed prior to the upgrade will not run jobs anymore. We created new pools with different names and assigned our dags to them.
2. Sometimes, though a DAG run will start (can see this in the UI and in the scheduler logs), the tasks for that DAG run will not be queued.
3. Sometimes there is a long delay between the time when a task gets queued and when it gets worked on, even if there are available slot in the pool.

I was doing some research and noticed that here (https://groups.google.com/forum/#!topic/airbnb_airflow/Bf-7YASKD2U) and in #698 it was recommended to run the scheduler for 5 runs at a time before restarting it. This seems to have helped some.

For the third issue, I noticed a 20 minute delay between seeing this in the scheduler logs:
2015-12-10 17:27:38,852 - root - INFO - Adding to queue: airflow run Airflow-Scheduler-Monitor heartbeat 2015-12-10T16:31:00   --local     -sd DAGS_FOLDER/scheduler-monitor.py  

And seeing this in the worker log:
Logging into: /r9/airflow/logs/Airflow-Scheduler-Monitor/heartbeat/2015-12-10T16:31:00

Is there a good way to look at whats happening between these two log messages, either with more logging or connecting to look at the celery queues?

Thanks,
Stephen

**Comment by thibault-ketterer** [comment]
Well I just saw here

https://medium.com/handy-tech/airflow-tips-tricks-and-pitfalls-9ba53fba14eb#.x3wfdr7ei
> Even though subdags are triggered as part of a larger dag, if their schedule is set to None or ‘@once’, the subdag operator will succeed without doing anything.

maybe this is my issue, I'll check this again, anyway It's a strange behavior.

**Comment by matthewdavidhauser** [comment]
Hi Stephen,

I was just wondering if these problems were resolved? Also, do you know if this problem is specific to using celery?

Thanks,

Matt

**Comment by NeilHanlon** [comment]
@matthewdavidhauser I'm wondering if this could be a celery issue with sqlacademy as a broker... do you think changing to RabbitMQ or Redis might be a good thing to try?

**Comment by matthewdavidhauser** [comment]
@NeilHanlon don't have much insight on that one- I've just been using the local executor and hadn't seen any issues so far

**Comment by smueller1245** [comment]
Hi Neil and Matt, thank you for the replies. Neil, good to hear from you :)

We have been using celery with mysql/sqlalchemy as the broker. I will give RabbitMQ a try.

Thanks!

**Comment by smueller1245** [comment]
In case anyone is seeing similar issues: I found that you can run the "airflow flower" command and go to http://<hostname>:8383 to use the flower UI to monitor celery.

**Comment by r39132** [comment]
FYI, we (Agari) use the local executor instead of the celery executor. We moved from 1.5.1 to 1.6.1+ (HEAD master) and did not notice any issues with scheduling and our pool. We did not need to recreate any pools, so this sounds like a celery specify problem. It would be good if you changed the title of this issue to reflect that. We run airflow in both staging and prod, so we did the upgrade (via `git pull`, `python setup.py install`, and `airflow upgradedb`) to both without any issues.

**Comment by bolkedebruin** [comment]
Is this still an issue? Otherwise is seems more an issue for the mailinglist. Closing for now here otherwise create Jira.

**Comment by NeilHanlon** [comment]
@bolkedebruin I believe we put in a PR to fix the issues, and we also switched over to rabbitmq as a broker which seemed to help as well.

**Comment by reconditesea** [comment]
@NeilHanlon Wondering which airflow version has your fix for this issue? We're also bitten by it recently using airflow 1.6.2 + celery. Thanks!

**Comment by bolkedebruin** [comment]
@reconditesea 1.7.1*, most likely out next week will contain a lot of scheduler fixes including this one.
- given no new blockers

**Comment by NeilHanlon** [comment]
@reconditesea https://github.com/apache/incubator-airflow/pull/1135 I believe is the PR

**Comment by reconditesea** [comment]
Thank you @bolkedebruin, @NeilHanlon !
