### ISSUE TITLE
How to set user password before login the website

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#759]
I use the password_auth.py to control user login ,but I need set the user password before logining,so anyone can tell me where I can set it and how ? Thanks~~

![image](https://cloud.githubusercontent.com/assets/8220811/11767533/dcb4244e-a1eb-11e5-8ffa-af9d0a01beed.png)

**Comment by Yongyiw** [comment]
I didn't try `password_auth.py` before, but if LDAP authentication is within your consideration, you can  set it up by following steps:

1) Set up a LDAP server:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-a-basic-ldap-server-on-an-ubuntu-12-04-vps

2) Select `ldap_auth.py` as your authentication backend.
3) Add LDAP configs in `airflow.cfg`:

```
bind_user = cn=admin,dc=vagrant,dc=com
bind_password = ????
uri = ldap://127.0.0.1:389
user_filter = objectClass=posixAccount
user_name_attr = cn
basedn = dc=vagrant,dc=com
```

But I am also curious about how to use password_auth.py as backend. Appreciated if anyone could help :D

**Comment by bolkedebruin** [comment]
@neovintage I think this one is for you ;-)

**Comment by neovintage** [comment]
@bolkedebruin looks like it. 

@Thomasmisfit are you working with a fresh installation of airflow?

**Comment by thomastanmin93** [comment]
@neovintage ,  yes,I upgrade it to the 1.6.1

**Comment by neovintage** [comment]
You'll need to log into the box where airflow is installed and open up a new python repl. Then import the airflow libs and then create a new PasswordUser. Once you've created that first user, you can then create other users via the web interface.

Here's an example:

```
$ cd ~/airflow
$ python
Python 2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import airflow
>>> from airflow import models, settings
>>> from airflow.contrib.auth.backends.password_auth import PasswordUser
>>> user = PasswordUser(models.User())
>>> user.username = 'new_user_name'
>>> user.email = 'new_user_email@example.com'
>>> user.password = 'set_the_password'
>>> session = settings.Session()
>>> session.add(user)
>>> session.commit()
>>> session.close()
>>> exit()
```

I'll write these instructions in the documentation. I originally thought of creating a new user with a password in the migrations but I didn't want to have the risk of developers installing airflow and not deleting that default account.

**Comment by dpalomin** [comment]
Hmmm, I tried the user creation instructions noted above and in the documentation, but I get an error about missing a table at the "session.commit()" call.  

  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: u'INSERT INTO user (username, email, password) VALUES (?, ?, ?)'] [parameters: ('myuser', 'my_user@example.com', '$2b$1XXXXXXXDIoT8/.aWaXXXFkv3XXXXXXX6pbKyTIzge')]

**Comment by bolkedebruin** [comment]
table is now called 'users'. Did you upgrade properly? Please open Jira if required.
