### ISSUE TITLE
Can a dag run depend on past? 

### ISSUE THREAD

**Issue by wil5for** [apache/airflow#768]
I would like to have entire dag runs depend on previous dag runs. 

Use case 1: I have turned off a dag and when I turn it back on I would like to prioritize earlier runs completing over later runs starting. In my dag below its important that when runs are backed up we finish `aggregate_db_message_job` as soon as possible

<img width="855" alt="screen shot 2015-12-15 at 6 47 04 pm" src="https://cloud.githubusercontent.com/assets/5509123/11830694/47e938f0-a35c-11e5-9e3d-6eedfeabed12.png">

Use case 2: Some tasks in a dag depend on previous instances _of a different task_. In this Dag I want `clear_spark_logs` after the `send_email_notification_flow_successful` of the previous run

<img width="681" alt="screen shot 2015-12-15 at 6 48 51 pm" src="https://cloud.githubusercontent.com/assets/5509123/11830732/970c0af2-a35c-11e5-8e5f-2c17dc2217e2.png">

As I understand Airflow, setting depends_on_past to True for a Dag just sets the depends_on_past parameter for each task in that dag. Using priority weights also doesn't seem to solve the problem since the task pool might be large enough to start tasks in the next day.

What's the proper way to solve this with airflow?

**Comment by r39132** [comment]
+1

**Comment by mistercrunch** [comment]
You can do that by adding a root task all the way downstream, and adding a `ExternalTaskSensor` referencing it as a dependency for all leaf nodes (most upstream) for the previous run.

You could also reduce the `max_active_runs` of your DAG to limit the parallelism all the way to 1.

**Comment by r39132** [comment]
Can you provide an example for our DAG in the Graph view above? As mentioned, essentially, for use-case 2, we want `clear spark logs` for a DAG run to wait until the previous run's `send_email_notification_flow_successful` completes successfully.

**Comment by mistercrunch** [comment]
Look at how ExternalTaskSensor has an `execution_delta` param. You can just have one task directly upstream of `clear spark logs` that targets  the same dag_id, and `send_email_notification_flow_successful` for `execution_delta=dag.schedule_interval`
http://pythonhosted.org/airflow/code.html#airflow.operators.ExternalTaskSensor

**Comment by r39132** [comment]
Cool. Didn't think about using it within the same DAG. Thx. Will try that out. I am running hourly, so I could set the execution delta to `hours=1`. Is the execution delta a minimum requirement or a maximum requirement? In other words, does at least 1 hour difference need to occur for the trigger to fire? Or does the trigger fire up until a max difference of 1 hour occurs?

**Comment by wil5for** [comment]
The external task sensor with an external_dag_id of the same dag worked well. Thanks for pointing out that operator!

Example:

```
wait_for_task_in_previous_hour = ExternalTaskSensor(
    task_id='wait_for_task_in_previous_hour',
    external_dag_id='my_dag_id',
    external_task_id='task_to_wait_for_id',
    allowed_states=['success'],
    execution_delta=timedelta(hours=1),
    dag=dag)
```
