### ISSUE TITLE
Issue using the Datepicker of a Treeview from DAG List

### ISSUE THREAD

**Issue by kivismik** [apache/airflow#769]
Steps to reproduce:
1. Go to Airflow main UI
2. Select the Treeview Icon next to a DAG
3. Change the "Number of runs" to another value and click Go
4. A HTTP 500 error is displayed because the parameter "root" has the value of "None" instead of being empty.

**Comment by artwr** [comment]
May I ask which version of airflow you are using? I think this has been fixed in master.

**Comment by kivismik** [comment]
Works on the updated version of Airflow
