### ISSUE TITLE
How to modify BashOperator task's environment dinamically

### ISSUE THREAD

**Issue by WesleyBatista** [apache/airflow#775]
Hello guys!

Here we use a bunch of python scripts to do our ETLs. Scripts that takes parameters like _date_ini_ and _date_end_ from the environment.

In Airflow we have the _execution_date_, that represents the date which the task instance is running for (our date_ini).

The _execution_date_ is only available on the task's context, which makes sense. But, some way I need to get that value, make some magic and put a _date_end_ in the environment, so I can continue with the `os.getenv()` and don't need to modify my python scripts.

Do you guys have some tip to achieve this?

I already tried to set the `pre_execute` in my task passing a method which modifies the _context_, but no success :disappointed:.

``` python
def set_env_var(context):
    return context.update({"my_env_var": "MY_env_var_value"})

bash_command_str = "python -c \"import os; print os.getenv('my_env_var');\""
bashTask = BashOperator(dag = dag, task_id = "asas", bash_command = bash_command_str)
bashTask.pre_execute = set_env_var
```

I don't know exactly if is it, but I just guess whether the sort of these lines were changed... Maybe the pre_execute would work.

https://github.com/airbnb/airflow/blob/master/airflow/models.py#L983-L984

Thanks in advance!

**Comment by mistercrunch** [comment]
Check out the `env` parameter in BashOperator
http://pythonhosted.org/airflow/_modules/bash_operator.html#BashOperator

I just added a PR (https://github.com/airbnb/airflow/pull/776/files) to make this parameter templated, meaning the values of the dict can receive jinja as in `env = {'execution_date': "{{ execution_date.isoformat() }}"}` and will get replaced at runtime.

Here's the list of what you can use:
http://pythonhosted.org/airflow/code.html#macros

**Comment by WesleyBatista** [comment]
I tried the `env` parameter, but today I can't update the values at runtime.

If I understood, after the PR be merged I will be able to do:

``` python
from airflow.operators import BashOperator

customEnv = {
'date_ini': "{{ execution_date.isoformat() }}", 
'date_end': "{{ execution_date + dag.schedule_interval }}"
}
env = dict(os.environ, **customEnv)
task = BashOperator(
            ...
            env=env
        )

# on the etl scripts
import os 
...
date_ini = os.getenv('date_ini')
date_end = os.getenv('date_end')
...
```

**Comment by mistercrunch** [comment]
Exactly, I just merged the PR
