### ISSUE TITLE
Task instance got assigned to wrong queue

### ISSUE THREAD

**Issue by garthcn** [apache/airflow#778]
I'm on Airflow 1.6.1

I have two machines: one running one scheduler and one worker (call it worker A); the other running just one worker (call it worker B). 

Worker A is started without queue argument: `airflow worker`
Worker B is started with queue argument: `airflow worker -q special`

Then I have one DAG which is made of 3 operators. 2 of the operators (OpA and OpB) have `queue=special` config and the other (OpC) doesn't. 

I expect OpC to be inserted into the default queue and gets picked up by Worker A; OpA and OpB to be inserted into `special` queue and get picked up by Worker B. 

In Scheduler log, it shows that OpA and OpB are indeed assigned to `speical` queue; OpC gets assigned to default queue, but in Airflow DB, everything is in `special` queue.
For example:
in the scheduler log, I can see:

```
[celery] queuing ('DAG_NAME', 'OpC', datetime.datetime(2015, 10, 25, 8, 30)) through celery, queue=default
```

However, in the Airflow database, in `task_instance` table, OpC has queue values of `special` (instead of `default`). And instead of being picked up by Worker A (which should only be listening on `default` queue), it's being picked up by Worker B (which should only be listening on `special` queue). 

For machine running Worker A, `airflow.cfg` has `default_queue = default`
For machine running worker B, `airflow.cfg` has  `default_queue = special`. However I assume the CLI argument (`airflow worker -q <queue_name>`) is what's being used by worker. 

Did I make some mistakes in the config or in my understanding about Airflow? 

Thanks so much!

BTW, it looks like the Airflow doc is inconsistent regarding using queue with CeleryExecutor.
This page (http://airflow.readthedocs.org/en/latest/concepts.html?highlight=queue#queues) says that CeleryExecutor supports special queue.
This page (http://airflow.readthedocs.org/en/latest/code.html?highlight=queue#baseoperator) says the opposite: 

```
queue (str) – which queue to target when running this job. Not all executors implement queue management, the CeleryExecutor does support targeting specific queues.
```

**Comment by adambom** [comment]
:+1:

**Comment by bolkedebruin** [comment]
@garthcn Would you mind creating a Jira issue for this? Thanks!
