### ISSUE TITLE
LDAP role for viewer access (should not be able to execute the DAGS only viewer permission)

### ISSUE THREAD

**Issue by Deepakparashar14** [apache/airflow#7799]
**Description**

**Use case / motivation**

**Related Issues**

details description here : https://issues.apache.org/jira/browse/AIRFLOW-7095#
Hi ,

I have been trying to  setup a LDAP authentication in my company and have manged to done that successfully .
And using the superuser and data profiler filter and also i have created the viewer filter in the ldap_auth.py file and that filter too working but the users who belongs to this group can execute the DAGS i want to restrict them just only to view the status of dags and logs and they should not be able to execute them .
Can you please suggest me where and which file i can make the changes for the same to implement it .

**Comment by jedcunningham** [comment]
@Deepakparashar14, if you haven't already, you should move to the RBAC UI if you are on Airflow 1 (or upgrade to Airflow 2) as it has better granularity for restricting access.

**Comment by jedcunningham** [comment]
Airflow 1 has reached end of life.
