### ISSUE TITLE
Colorblind friendly UI

### ISSUE THREAD

**Issue by mapsam** [apache/airflow#7843]
Hello! Thanks for all your work on Airflow :) 

### Description

Reds (failed) & greens (success) colors are not colorblind friendly. 

### Use case / motivation

As a deuteranope, when I view recently run dags, it's not clear which runs succeeded and which failed. To me, this is probably one of the most important features of the Airflow UI. 

![Screen Shot 2020-03-23 at 10 18 59 AM](https://user-images.githubusercontent.com/1943001/77344000-c6696180-6cef-11ea-9330-8c97c8f285c4.png)

*You could convince me everything succeeded or failed in this screenshot.*

### Suggestions

Totally understand that red/green are important for our common expectations of failure/success, so I'll just propose some other reds/greens that work for me, with the caveat that there are many more types of colorblindness than my own so it's worth getting a diverse set of opinions here. Something other than default `red` and `green` web colors will be tremendously helpful though!

**`red` / `DarkSeaGreen`** - simple change, works well with the yellow "running" value

![Screen Shot 2020-03-23 at 10 21 58 AM](https://user-images.githubusercontent.com/1943001/77344398-56a7a680-6cf0-11ea-829c-b871a2be5935.png)

**[clrs.cc](http://clrs.cc/)** failed = `#FF4136`, success = `#2ECC40`, running = `#01FF70` - this comes with the bonus of being [A11Y compliant](http://clrs.cc/a11y/).

![Screen Shot 2020-03-23 at 10 31 45 AM](https://user-images.githubusercontent.com/1943001/77345204-87d4a680-6cf1-11ea-9ab3-c8533f0ead77.png)

Happy to create more combinations, if helpful. Cheers!

**Comment by ericfischer** [comment]
Of these two, I would strongly prefer

![77344398-56a7a680-6cf0-11ea-829c-b871a2be5935](https://user-images.githubusercontent.com/1951835/77346206-1eee2e00-6cf3-11ea-8b8f-811a92be9ea9.png)

because I can tell the green and yellow apart reliably in this one and cannot in in the second.

I think my own preference would be for this very bright yellow and darker red, and a green that is as light and saturated as possible with a hue toward the blue end of the greens:

![77344398-56a7a680-6cf0-11ea-829c-b871a2be5935 mod](https://user-images.githubusercontent.com/1951835/77347952-ddab4d80-6cf5-11ea-8cab-3bb4ccdc9542.png)

@mapsam Do these colors work for you?

**Comment by mapsam** [comment]
Thanks @ericfischer! I can't really tell the difference between your green and yellow, but the red/green is extremely contrasting, which is great.

Maybe "running" shouldn't be yellow, and should be a blue or grey to just be completely different.

**running = `CornflowerBlue`**

![Screen Shot 2020-03-23 at 11 28 50 AM](https://user-images.githubusercontent.com/1943001/77350437-c4a49b80-6cf9-11ea-8a01-1b6b9fdeb0b9.png)

**running = `palegreen`** - just curious if these two types of green are contrasting enough, and separate enough from the red for you.

![Screen Shot 2020-03-23 at 11 29 15 AM](https://user-images.githubusercontent.com/1943001/77350502-d5551180-6cf9-11ea-9f43-7545d666c8ad.png)

**Comment by ericfischer** [comment]
@mapsam Either of these two last images works for me. The `CornflowerBlue` is easier to distinguish than the `palegreen`.

**Comment by RosterIn** [comment]
There was an attempt on this some time ago
https://github.com/apache/airflow/pull/2654

**Comment by csurett** [comment]
Couldn't the colors be made into a user preference using Javascript and a cookie?

**Comment by preston-m-price** [comment]
I also have a difficult time with the reds/greens when looking at past DAG runs. Another approach I've seen used successfully is to use different shapes for different values in the legend. If it's possible to move away from the box shape, different results could be expressed through different iconography as well as color.

**Comment by kaxil** [comment]
Added it to 1.10.11 milestone, we will include this in Airflow 1.10.11

However, I would like to know what would best work for you all

Options:
1) Default to colorblind friendly UI
2) Make the colors configurable

Can you please let me know in comments, please?

**Comment by mapsam** [comment]
@kaxil 👋 awesome! 

> Default to colorblind friendly UI

This would be ideal - if even the reds/greens were made slightly different.

> Make the colors configurable

The above is ideal, but this also sounds really helpful! Especially since not all colors work for everyone.

**Comment by optimuspaul** [comment]
I would prefer to just have the colors configurable. But also agree with @preston-m-price, shape differences would add a lot of value for me. Even making the size larger on the boxes would increase my ability to reason with the colors.

**Comment by csurett** [comment]
I'd prefer configurable so that current users aren't confused.

**Comment by giselamorrone** [comment]
@kaxil we had the same issues, and none in our team is colorblind. For us the problem is more with failed and skipped (red and pink, they are really similar), they are hard to detect fast!
Would be great if we could configure that ourselves!

**Comment by kaxil** [comment]
Looks like "Configurable" would be what all would like 👍

**Comment by preston-m-price** [comment]
I would vote for default colorblind friendly. I regularly get screenshots captured in issues and presentations that I can't read.

**Comment by ashb** [comment]
@preston-m-price Can you recommend some colours that work for you please?

Not _promising_ we'll change it, but we can look at it.

(And or different shapes too.)

**Comment by preston-m-price** [comment]
Sure, I just recently made some changes to our fork that make things easier for me to see. I took a SWAG and found some colors that worked for me in my situation. 

Using tree.css as an example:
```
rect.failed {
    fill: firebrick;
}
rect.queued {
    fill: darkgray;
}
rect.up_for_retry {
    fill: yellow;
}
rect.skipped {
    fill: darkorchid;
}
```
I still have a hard time with :firebrick and :green when they're in the circles at the top of the tree view, but in the grid below I can see them much better.
![image](https://user-images.githubusercontent.com/5125809/81233929-f8d7d100-8fb4-11ea-8cc7-9a1d09ab0ca8.png)

**Comment by Acehaidrey** [comment]
is there any work or plans to make the colorblind ui configurable? We've had requests at pinterest too about it, and wanted to see what others here have been doing to help this

**Comment by kaxil** [comment]
Looking at that one today

**Comment by kaxil** [comment]
I will raise a PR today and we will release it as a part of 1.10.11

**Comment by Acehaidrey** [comment]
Thank you much @kaxil

**Comment by kaxil** [comment]
I have created a PR : https://github.com/apache/airflow/pull/9520 to implement this changing Task States colors. 

PS: I am not good with UI but with the current change, it should work fine. Can you all give it a shot and post your feedback, please.

We will soon release 1.10.11 and I would like to include this change :)

**Comment by vmatt** [comment]
hey @mapsam @preston-m-price I've just come up with an [userscript](https://medium.com/namilink/making-apache-airflow-more-accessible-31667b55c55d), that replaces color status with symbols!
