### ISSUE TITLE
Kubernetes Executor wastefully creates pods for DummyOperator tasks

### ISSUE THREAD

**Issue by jpuffer** [apache/airflow#7871]
**Description**

Kubernetes Executor currently spins up a whole worker pod to execute a dummy task.  We know Airflow's DummyOperator doesn't actually _do_ work - it's there to help to organize /group tasks and very useful for that purpose. 

**Use case / motivation**

For complex DAGs, skipping the worker creation process for dummy tasks could significantly improve execution time and resource use in the cluster.  Could the executor work more like the local executor when dealing with the dummy tasks? (that way, they could be essentially instant and not interfere with the actual worker pool)

**Comment by mik-laj** [comment]
Interesting idea. I think you can just mark these tasks automatically in a success state. This made this change work for all executors.

**Comment by mik-laj** [comment]
Done :-D

**Comment by jpuffer** [comment]
🌟⚡️🎉
