### ISSUE TITLE
API endpoint to fetch DAG instance expected start time

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7876]
**Description**

From: https://issues.apache.org/jira/projects/AIRFLOW/issues/AIRFLOW-621?filter=allopenissues&orderby=affectedVersion+ASC%2C+priority+DESC%2C+updated+DESC

"I'm looking for a mechanism to fetch a scheduled DAG instance's expected start time, in Oozie world it is populated as nominal time.

For my specific use case, I have a DAG that is scheduled to run every 15 mins and one of the task needs to use the DAG instance start time to query database and fetch all the rows that have been inserted/updated in last 15 mins. I need a mechanism to fetch the expected start time of the DAG instance and pass it to the task since the task actual start time might be after the expected start time."

**Use case / motivation**

a mechanism to fetch a scheduled DAG instance's expected start time

**Related Issues**

**Comment by mik-laj** [comment]
@dimberman There is no need to do the REST API here, but a class method is enough

**Comment by ashb** [comment]
@mik-laj This was not Dan's request originally -- he's starting to migrate issues over from Jira.
