### ISSUE TITLE
Url parser in connection uses path as schema for HTTPs connections

### ISSUE THREAD

**Issue by thiagorsqr** [apache/airflow#7881]
**Apache Airflow version**: 1.10.6 

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- **Kernel** (e.g. `uname -a`): 
```
Linux airflow 5.0.0-1035-azure #37-Ubuntu SMP Wed Mar 18 11:21:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**: 
- **Others**:
**What happened**: 

When configuring HTTPs connection strings Airflow stills connects using http.

HTTPS is only configurable using scheme as path under HTTP operator and connections strings

User line 194 in connections shouldn't quoted_schema receive the scheme configuration from uri_parts.scheme instead of the path. Currently is using the scheme as the path from uri_parts. If that's the case https connection strings would need to be configured like 
http://localhost:8080/https for it to work.

```
https://github.com/apache/airflow/blob/a6fd74e706e0da24da1dfcceba14600c929a36cf/airflow/models/connection.py#L194
```

**What you expected to happen**: Be able to configure https connections strings 

**How to reproduce it**: Try to configure a https connection string and see how Airflow connections parse it.

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Hello,
Once I started working on it, but I did not find time to complete this change. If you want, you can rely on my change.
https://github.com/apache/airflow/pull/5239
Best regards,

**Comment by eladkal** [comment]
Duplicate https://github.com/apache/airflow/issues/10913
