### ISSUE TITLE
KubernetesPodOperator had an event of type Pending

### ISSUE THREAD

**Issue by sbahir** [apache/airflow#7883]
Hello,

**Apache Airflow version**: 1.10.9

**Kubernetes version** 
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

**Environment:**
OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS

I am currently running this tests for Airflow on Kubernetes [blog test ](https://kubernetes.io/blog/2018/06/28/airflow-on-kubernetes-part-1-a-different-kind-of-operator/) 

it's running well for dummyOperator : 
`start = DummyOperator(task_id='run_this_first', dag=dag)`

But the Pod doesn't start for 
`passing = KubernetesPodOperator(namespace='default',
                          image="Python:3.6",
                          cmds=["Python","-c"],
                          arguments=["print('hello world')"],
                          labels={"foo": "bar"},
                          name="passing-test",
                          task_id="passing-task",
                          get_logs=True,
                          dag=dag
                          )`

The pod is stuck in a pending state 
`{"asctime": "2020-03-25 21:51:40,693", "filename": "logging_mixin.py", "lineno": 112, "levelname": "INFO", "message": "[2020-03-25 21:51:40,693] {{pod_launcher.py:142}} INFO - Event: passing-test-492349fd had an event of type Pending", "dag_id": "kubernetes_smoke_test", "task_id": "passing-task", "execution_date": "2020_03_25T21_13_15_733983", "try_number": "3"}
{"asctime": "2020-03-25 21:51:41,747", "filename": "logging_mixin.py", "lineno": 112, "levelname": "INFO", "message": "[2020-03-25 21:51:41,746] {{pod_launcher.py:142}} INFO - Event: passing-test-492349fd had an event of type Pending", "dag_id": "kubernetes_smoke_test", "task_id": "passing-task", "execution_date": "2020_03_25T21_13_15_733983", "try_number": "3"}
{"asctime": "2020-03-25 21:51:41,825", "filename": "taskinstance.py", "lineno": 1128, "levelname": "ERROR", "message": "Pod Launching failed: Pod took too long to start", "dag_id": "kubernetes_smoke_test", "task_id": "passing-task", "execution_date": "2020_03_25T21_13_15_733983", "try_number": "3"}
{"asctime": "2020-03-25 21:51:41,830", "filename": "taskinstance.py", "lineno": 1185, "levelname": "INFO", "message": "Marking task as FAILED.dag_id=kubernetes_smoke_test, task_id=passing-task, execution_date=20200325T211315, start_date=20200325T214940, end_date=20200325T215141", "dag_id": "kubernetes_smoke_test", "task_id": "passing-task", "execution_date": "2020_03_25T21_13_15_733983", "try_number": "3"}
{"asctime": "2020-03-25 21:51:43,450", "filename": "logging_mixin.py", "lineno": 112, "levelname": "INFO", "message": "[2020-03-25 21:51:43,449] {{local_task_job.py:103}} INFO - Task exited with return code 1", "dag_id": "kubernetes_smoke_test", "task_id": "passing-task", "execution_date": "2020_03_25T21_13_15_733983", "try_number": "3"}`

The machine I am running it on have a proxy to the internet, so my guess is that it can't pull the image `python:3.6` maybe but the logs are not clear. 
How can I debug more efficiently to understand what is the problem ?

Thank you

Saad

**Comment by yiannissakk** [comment]
Hello Saad,

I am having exactly the same problem. I think we got our example from the same place too.

Did you end up solving this?

Thanks
Yiannis
