### ISSUE TITLE
Custom Facebook Ads Operator

### ISSUE THREAD

**Issue by randr97** [apache/airflow#7887]
**Description**
This is feature request to have custom operators to pull insights from Facebook Ads Platform

- This enables facebook ads as a platform to be integrated into airflow by enabling operators
- The initial request would provide Ad Insights from facebook

**Use case / motivation**
- The operator is QA - verified by strong test case policy of the community
- Continuous support by the open source development community
- Pulling FB Ad insights can then be then used for data viz. and biz. decisions

**Comment by ashb** [comment]
You marked this as "WIP" -- are you working on it?

**Comment by mik-laj** [comment]
@ashb Yes. I support this contributor.

**Comment by randr97** [comment]
> You marked this as "WIP" -- are you working on it?

Yep, on it!

**Comment by randr97** [comment]
Next Steps -

- [ ] FB reports to S3 Bucket (AWS integration)
- [ ] Audience onboarding to FB
- [ ]  Creative Bulk Upload

**Comment by kaxil** [comment]
> @mik-laj Any thoughts?
> Next Steps -
> 
> * [ ]  FB reports to S3 Bucket (AWS integration) (Operator)
> * [ ]  Audience onboarding to FB (Hook) (Operator)
> * [ ]   Creative Bulk Upload (Hook) (Operator)

Let's create new issues for other hooks

**Comment by mik-laj** [comment]
@randr97 I'm not a Facebook expert, but these operators look useful.
