### ISSUE TITLE
Having SSHOperator?

### ISSUE THREAD

**Issue by KeenS** [apache/airflow#789]
I'd like to kick scripts at remote boxes via ssh. I know I can use `ssh` command via BashOperator. However current (master) airflow have the SSHHook. I think it is better that using existing eco system.

If it is acceptable, I'll submit [code](https://github.com/KeenS/airflow/blob/ssh_operator/airflow/contrib/operators/ssh_operator.py)  (WIP).

**Comment by bolkedebruin** [comment]
I like it but I would like to see some tests added and maybe a rename to SSHExecuteOperator?

**Comment by KeenS** [comment]
@bolkedebruin OK. I'm planning to write tests too. Then where should I put them? It seems there are no test directories for contrib packages.

Re renaming:  I see. I'll change the name.
