### ISSUE TITLE
Airflow Kubernetes Pod Operator Debugger

### ISSUE THREAD

**Issue by Javier162380** [apache/airflow#7904]
**Description**

Airflow and Kubernetes integration are great. Although one of the hardest part comes when we need to debug.

I found some time problematic when I create or change some configuration in a  dag using the KubernetesPodOperator to know if the task is going to render all their attributes as I want. For instance, some times on my job I found inconsistencies in the way arguments or entry points are parsing, or Kubernetes resources are created or referenced.

Moreover having a tool for generating k8s pod templates from Airflow dag, can be also really convenient for recover historical data if you are using an incremental approach for some dags or trigger some tasks with as slightly different configuration for one-time demand. In this way, we can interact directly with the Kubernetes API without needing to change airflow dags configuration, so Airflow will give us more speed and flexibility

**Use case / motivation**

For this solution, I will like to have a feature in Airflow that given a dag or path containing multiple dags Airflow can generate one or multiple k8s pod templates in a path or giving an output in a terminal for debugging, and maybe in a most ambitious way for deploying into prod using a Kubernetes command.
 Something similar to the helm installs --debug dry-run command (https://helm.sh/docs/chart_template_guide/debugging/). 

This feature could be added directly to the CLI so it can be easily used for end-users. In the same way

I have created a library implementing this new functionality
https://github.com/Javier162380/AirflowKuberentesDebugger

**Comment by dimberman** [comment]
Hi @Javier162380, Once we release 2.0 one of the big things we're going to work on is overhauling the UI. We're discussing creating a "render" attribute for pods created by the KubernetesPodOperator. I'm going to add @ryanahamilton to this discussion

**Comment by ashb** [comment]
This is done now.
