### ISSUE TITLE
Allow jinja templates to be used in task params

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7910]
**Description**

At present when defining an Operator it isn't possible to reference template variables such as ds in the params block.

Enabling this makes it easier to reuse Operators with very similar configurations. An example of this might be a BashOperator which runs a large (possibly external) script that only has a couple of configuration changes used between different runs.

**Use case / motivation**
For example, you might have something like this:

```python
op = BashOperator(
	task_id = "task",
	bash_command = "do-something.sh {{params.path}}",
        params = {"path": "/path/to/thing/{{ds}}/thing.csv"},
        dag = dag
)
```
In this case, the bash_command will be expanded to:
```
  do-something.sh /path/to/thing/{{ds}}/things.csv
```
But should be expanded to:
```
  do-something.sh /path/to/thing/2017-06-14/things.csv
```

**Related Issues**

**Comment by a-jumani** [comment]
If you don't mind, I'd like to take stab at it. Have been using Airflow for the past few months, would love to contribute.

**Comment by dmateusp** [comment]
hi folks! I was looking for this feature and I'm seeing both this issue and 2 PRs closed, but it does not seem resolved?

**Comment by elephantmetropolis** [comment]
Hey @dimberman, I am very late to the party but the 2 PRs has been closed and the issue is marked as resolved.
Is there a reason why jinja template cannot be used within `params` ? Or is it just waiting for someone to do it ?
