### ISSUE TITLE
Add data retention policy to Airflow

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7911]
**Description**

Airflow's DB currently holds the entire history of all executions for all time. This is problematic as the DB grows. The UI starts to get slower, and the DB's disk usage grows. There is no bound to how large the DB will grow.

It would be useful to add a feature in Airflow to do two things:

    Delete old data from the DB
    Mark some lower watermark, past which DAG executions are ignored

For example, (2) would allow you to tell the scheduler "ignore all data prior to a year ago". And (1) would allow Airflow to delete all data prior to January 1, 2015.

**Use case / motivation**

**Related Issues**

Copied from https://issues.apache.org/jira/browse/AIRFLOW-108

**Comment by joshowen** [comment]
I'm particularly interested in having a low watermark to speed up the webserver's queries, but we'd want to persist all of the dagrun metadata for occasional offline reporting.

**Comment by joshowen** [comment]
One other thought on this: it would be very useful if the low watermark was configurable in the UI (eg, show me the last 30d/365d /all DAGRuns)

**Comment by mik-laj** [comment]
Some users use this to maintain high performance for a long time.
https://github.com/teamclairvoyant/airflow-maintenance-dags

**Comment by hsnprsd** [comment]
@mik-laj I think it would be good to add the features in the github repo you mentioned to airflow itself.

**Comment by potiuk** [comment]
I think maintenance DAGs is more of a "trick". It would be better if we have "proper data retention" built in Airflow rather than DAGs you can schedule. This is at least my opinion, maybe something we want to discuss as possible feature for 2.1

**Comment by mik-laj** [comment]
@potiuk  @hsnprsd Here is mailing lists discussion: https://lists.apache.org/thread.html/f622e719d5f7e804bf75c05697f405264caae1d3a72aa1bd991b78e9%40%3Cdev.airflow.apache.org%3E
Can you add your comment there?

**Comment by potiuk** [comment]
> @potiuk @hsnprsd Here is mailing lists discussion: https://lists.apache.org/thread.html/f622e719d5f7e804bf75c05697f405264caae1d3a72aa1bd991b78e9%40%3Cdev.airflow.apache.org%3E
> Can you add your comment there?

The discussion is from March/April 2019. I do not see any value in reviving it there.  I will leave it to whoever is interestedin movin it forward - possibly @dimberman who opened the issue (or anyone who would like to lead it to carry it on).

**Comment by mik-laj** [comment]
Giving full administrator privileges is an extreme case, but giving read-only one or two DAGs is something that makes sense to support.  I looked at the code quickly and I don't find it difficult to add support for this case.

I think if we improve this one SQL query and use get_user_roles instead of our own SQL query it should work.

**Comment by dimberman** [comment]
@potiuk this is something I auto-ported from JIRA. I can leave it to @ashb @vikramkoka if we want to address it but my guess is this might be lower priority vs. other features. That said if anyone in the community wants to take this on I'd be glad to help them do it!

**Comment by potiuk** [comment]
Sure. No strong feelings about it, and - as everything in the community - it will get done if there is someone leading it :)

**Comment by JavierLopezT** [comment]
If I get some guidance on how/where to start I could try to do it

**Comment by potiuk** [comment]
> If I get some guidance on how/where to start I could try to do it

I think good start is to take a look at the - quite popular - maintenance dags here: https://github.com/teamclairvoyant/airflow-maintenance-dags  - this is a set of 3rd-party maintenance DAGs that people are using for some kind of maintenance (`db-cleanup`). We do not know how "correct it is" and how well it copes with the new Airflow versions, but It can give an idea on how users deal with it.

I think that might be a good idea to start from that and work out an approach (other than DAGs) implementing something like that in airlfow  as periodic Job  - especially that long term plans will be to not allow tasks to talk to the DB directly, the DAG-approach would not work in this case.

I think personally this should start with at least discussion in the devlist or (maybe even better) a new AIP (Airflow Improvement Proposal - https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals ) as result of this discussion.

I think there are many ways it can be done, but it needs some proposal and quite extensive discussion (on performance consequence, where should such cleanup be running, whether it should be a separate process or should it run within scheduler, how to deal with multiple-schedulers if we choose scheduler-embedded solution, etc. etc. It's actually quite an extensive one

**Comment by koconder** [comment]
@potiuk should we close this as resolved, as the DB cleanup is now part of the main release?

**Comment by potiuk** [comment]
Sure. Let's close it.
