### ISSUE TITLE
Support more general and customizable trigger rule options

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7934]
**Description**

Currently, the trigger rule options in Airflow are very limited. For example, it is difficult to let a task trigger when the upstream either failed or succeeded (but not upstream_failed). 

We should support more general and more customizable trigger rule options.

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-389

**Comment by roachlord** [comment]
We have a use case for more flexible trigger_rules - 

We have task (C) with two upstream processes (A & B)
A (required) -> C
B (optional) -> C    (apologies for the poor diagram)
one of the upstream processes (B) is optional and allowed to fail. The other task (A) *must* succeed for C to run successfully. We can set task C's trigger_rule to `all_done` or `one_success` but this lessens the strict criteria of task C that A must succeed.

We believe we can achieve this behavior by adding an additional DummyOperators into the dag but this seems unsatisfactory. For example -
 A (required) -> C
 B (optional) -> D -> C 
Where D is a DummyOperator with trigger rule = `all_done` and task C has trigger_rule `all_success`
