### ISSUE TITLE
Webserver does not detach from console when using -D

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7941]
**Apache Airflow version**: 1.7.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

Since the rework of a rolling webserver restart the "airflow webserver -D" does not detach from the console anymore

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-486

**Comment by zhongjiajie** [comment]
@dimberman Hi, I found out we have so many duplicate issue, such as this one and https://github.com/apache/airflow/issues/7942

**Comment by turbaszek** [comment]
And do we want to migrate all issues? This one is really old (1.7)... also I'm not sure if we agreed on process of the migration.

**Comment by zhongjiajie** [comment]
Did daniel mean start in ariflow-1.7 and don't fix until now?

**Comment by dimberman** [comment]
@turbaszek I'm starting from the top but trying to filter out tickets that I know to be no longer relevant. It's harder with the older tickets but some of these problems appear to be still happening.
