### ISSUE TITLE
SLA notification does not work for manually triggered DAGs 

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7959]
**Apache Airflow version**: None

Ticket was created 07/Oct/16 21:40

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

No SLA notifcation emails are sent for manually triggered DAGs.

The code for DAG.following_schedule does not seem to handle the case of scheduler_interval=None ...

   def following_schedule(self, dttm):
        if isinstance(self._schedule_interval, six.string_types):
            cron = croniter(self._schedule_interval, dttm)
            return cron.get_next(datetime)
        elif isinstance(self._schedule_interval, timedelta):
            return dttm + self._schedule_interval

When the DAG has schedule_interval=None, the following exception is raised ...

File "<...>/lib/python2.7/site-packages/airflow/jobs.py", line 284, in manage_slas
     while dttm < datetime.now():
TypeError: can't compare datetime.datetime to NoneType

**What you expected to happen**:

**How to reproduce it**:

For example, if you have ...

dag = DAG(
    'my_dag',
    start_date=datetime(2015, 1, 1),
    schedule_interval=None,
    default_args=args)

t = PythonOperator(
        task_id='t2',
        python_callable=<callable>,
        sla=timedelta(seconds=60),
        dag=dag)

There is no email sent if the task takes more than the SLA time.

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-557

**Comment by mz347247** [comment]
Is this issue solved?

**Comment by suyogchadawar** [comment]
is this issue resolved?

**Comment by potiuk** [comment]
> is this issue resolved?

What do you think by looking at the history ? Any other person answering this question has the same data that you have. So what's your take on it ? Do you have a reason to believe it is not solved? Can you please open a new issue if you have a reproducible case ?
