### ISSUE TITLE
Should be able to prevent tasks from overlapping across multiple DAG Runs

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7960]
**Apache Airflow version**: 1.7.1.2

Ticket was created 11/Jul/16 16:06

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

Currently, there is an issue of tasks overlapping between DAG runs
This can cause tasks to compete for resources as well as duplicating or overwriting what the other task is doing.

**What you expected to happen**:

As a the Airflow administrator,
If a task from a previous DAG Run is still running when the next scheduled run triggers the same task, there should be a way prevent the tasks from overlapping.

**How to reproduce it**:

1) Create a DAG with a short scheduled interval
2) Create a task in that DAG to run longer than the interval
Result: Both tasks end up running that the same time.

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-323

**Comment by nicku33** [comment]
I thought the parameter 'max_active_runs' accomplished this but it does not. I would also like this feature.

**Comment by rtjarvis** [comment]
I need this two - max_active_runs doesn't work. Any progress?

**Comment by ilCatania** [comment]
This can be achieved with `task_concurrency`:

https://airflow.apache.org/docs/apache-airflow/stable/faq.html

> task_concurrency: This parameter controls the number of concurrent running task instances across dag_runs per task.
