### ISSUE TITLE
Airflow's Hive integration doesn't scale up to tables with more than 32,767 partitions (and this is really easy to fix)

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7963]
**Apache Airflow version**: None

Ticket was created 27/Oct/16 03:30

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

The Hive metastore API has a rather confusing method signature for listPartitions. The last method parameter specifies the maximum number of partitions to return, and its type is a Java short. So Airflow passes the maximum Java short value (32,767) and notes the limitation in its API docs:

https://github.com/apache/incubator-airflow/blob/92064398c4c982a310925da376745a1713bf96e2/airflow/hooks/hive_hooks.py#L497-L499

 However, if you pass the magic number -1 as the "limit", then the metastore API will return all partitions. I found this documented here:

https://issues.cloudera.org/browse/IMPALA-749

I've also tried this myself on a Hive table with 80,000+ partitions.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-601

**Comment by eladkal** [comment]
For who will pick it up note the HiveHook is now located in [providers](https://github.com/apache/airflow/blob/master/airflow/providers/apache/hive/hooks/hive.py#L622:L624)

**Comment by zhongjiajie** [comment]
Good catch
