### ISSUE TITLE
 Add dag_run to the task_instance table or create new taskuuid column and use this to uniquely identify a task

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7967]
**Apache Airflow version**: None

Ticket was created 21/Nov/16 18:35

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

We are planning to run around 40,000 tasks a day using airflow and some of them are critical to give quick feedback to developers. 

Currently having execution date to uniquely identify tasks does not work for us since we mainly trigger dags (instead of running them on schedule) we collide with 1 sec granularity on several occasions.  Having a task uuid or associating dag_run to task_instance  table and using this for scheduling and updating status will help us here.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-642

**Comment by mik-laj** [comment]
It is possible to increase the gradation. You need to set "replace_microseconds" to "false" (boolean as string) in request body or use experimental API:
More:
https://airflow.readthedocs.io/en/latest/rest-api-ref.html#post--api-experimental-dags--DAG_ID--dag_runs
https://airflow.readthedocs.io/en/latest/stable-rest-api-ref.html#operation/post_dag_run
