### ISSUE TITLE
Automatic Refresh on DAG Graph View

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7970]
Ticket was created 30/Nov/16 11:51

**Description**

It would be nice not to have to press a button to refresh the graph view all the time. There's no reason not to have the option to have this refresh itself regularly so you can have it on a screen in the background and know that it's reasonably up to date when you glance across at it.

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-659

**Comment by JeffryMAC** [comment]
This is so so so so so so so much needed.

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/11534
