### ISSUE TITLE
PrestoHook - Add session properties

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7974]
Ticket was created 24/Dec/16 03:06

**Description**

In presto, there are some session properties (https://prestodb.io/docs/current/sql/set-session.html) that can be used in order to make queries more efficient. The idea would be to add session properties in the "Extra Fields" param in Presto Connection.

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-714

**Comment by dimberman** [comment]
-

**Comment by michaelguanzon** [comment]
Hi, any updates on this? Has this been implemented?
