### ISSUE TITLE
When creating a DagRun from the interface Run Id should be mandatory

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7982]
**Apache Airflow version**: None

Ticket was created 25/Jan/17 16:36

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

If the user forgets to set the Run Id, he'll be welcomed (in the scheduler) with the following exception:

  File "projects/incubator-airflow/airflow/models.py", line 4085, in is_backfill
    if "backfill" in self.run_id:
TypeError: argument of type 'NoneType' is not iterable

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-805

**Comment by fuyi** [comment]
I think the issue is labeled wrong. it is an issue for **Scheduler**
