### ISSUE TITLE
Bash_operator dont read multiline output

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7984]
**Apache Airflow version**: None given

Ticket was created 26/Jan/17 23:20

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

following piece of code is the root cause of it.  

line = ''
                for line in iter(sp.stdout.readline, b''):
                    line = line.decode(self.output_encoding).strip()
                    logging.info(line)

I plan to fix it using string buffer instead of just 1 line string variable here.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-833

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/7983
