### ISSUE TITLE
Remove deprecated features prior to releasing Airflow 2.0

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7987]
Ticket was created 02/May/16 13:00

**Description**

A number of features have been marked for deprecation in Airflow 2.0. They need to be deleted prior to release. 

Usually the error message or comments will mention Airflow 2.0 with either a #TODO or #FIXME.

Tracking list (not necessarily complete!):
JIRA:
AIRFLOW-31
AIRFLOW-200

GitHub:
https://github.com/airbnb/airflow/pull/1137/files#diff-1c2404a3a60f829127232842250ff406R233
https://github.com/airbnb/airflow/pull/1219
https://github.com/airbnb/airflow/pull/1285

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-32

**Comment by vikramkoka** [comment]
@dimberman Is there anything left to do here?
