### ISSUE TITLE
Having a REST layer for all command line interface of Airflow

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7997]
Ticket was created 21/Feb/17 08:06

**Description**

We are planning to use Airflow and was thinking if can have a REST interface for all the command line interface. This will be a cool feature to have. If you all wish then I can take up that task.

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-890

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/issues/10552
