### ISSUE TITLE
How Do I Execute Conditional Branching?

### ISSUE THREAD

**Issue by r39132** [apache/airflow#80]
Let's say that I have 2 paths with a branching point.

```
a --> b1 --> c --> e --> f --> g
a --> b2 --> d
```

So, starting at "a", based on some condition, I either follow `b1 --> c --> e --> f --> g` or `b2-->d`. In my specific case, if there is data generated from stage "a", I expect to go through full processing of the data `c --> e --> f --> g`. If I don't have data, then I expect to execute "d", which simply emails that there is no new data to process today!

If the entire flow were executed in a single subprocess within a single python interpreter, I could set a global boolean (tsk tsk, I know) that all operators check in order to decide whether to "do something" or not. Essentially, I would be placing the conditional logic in all operators downstream of "b". I am using the LocalExecutor right now, but don't expect that this assumption will hold.

So, I would need to store the global in a database and have all downstream operators check that boolean. Basically, I would rather just have a "branch operator" instead, so that I don't need to do this! In my flow, "b' is the branch operator, with "b1" and "b2" as branches.

In the absence of a conditional operator, I am considering the following:
If there is no data, "c" will raise an error so that it is marked red and the downstream operators would not be executed. On the other branch, "d" would pass, sending an email that there is no new data. 

If there is new data, then the opposite could happen.

My approach above will achieve what I need by showing one branch as having one "red" or "failed" task (i.e. at "c" or "d") and everything downstream as not being executed. That seems to meet my need

**Comment by mistercrunch** [comment]
I see the case for a branch operator, though we tend to wire things down different path by using an attribute of the data, and an empty batch typically never happens except if there is a problem.

An easy implementation would be to essentially derive the `PythonOperator` into a `BranchPythonOperator`, and have the assumption that the `python_callable` returns the name of the branch to take, namely the task_id of the direct downstream task to follow. Then this operator would set a failed status on all the directly downstream task_ids not returned.

**Comment by mistercrunch** [comment]
I wrote a quick sketch of what it may look like in this branch https://github.com/airbnb/airflow/compare/branch_python_operator?expand=1 but haven't tested it, let me know what you think.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/96

**Comment by r39132** [comment]
Folks, when are you planning your next release. I would like to use this in our staging environment and that is currently deployed using "pip"

**Comment by mistercrunch** [comment]
`v1.2.0` is out!
https://pypi.python.org/pypi/airflow

I pushed the new version of the docs to http://pythonhosted.org/airflow/ also
