### ISSUE TITLE
Show whether spark job is "running" or "waiting"

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#8000]
Ticket was created 07/Feb/17 21:52

**Description**

As of now, Airflow shows that a task is "running" in Airflow when it could be listed as "WAITING" in the Spark UI (and can be listed as "WAITING" for hours when the Airflow UI might indicate it is running if I forget to check the Spark UI). 

Would be awesome once ticket 802 for spark integration is complete to add this enhancement of more granular detail about the task. 

Note (Daniel 3/29/20): We should add an "external" field to task state to store task-specific data like spark cluster state

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-849

**Comment by mik-laj** [comment]
I think it should be a completely new element - an "external" state. This task is constantly executing and consumes worker resources, so "running" state is correct.  We can add a new column, which can be controlled by the task. The external state will not be used by the scheduler and will be able to have any label set by the task. WDYT?

**Comment by eladkal** [comment]
The flow of submitting job to a remote server is very common.
In my workflows I do: `SubmitJobRemoteOperator` -> `RemoteSensor` (reschedule mode).
This way Airflow workers are not occupied longer than it should.
