### ISSUE TITLE
Use annotated tags for releases?

### ISSUE THREAD

**Issue by aostapenko** [apache/airflow#8005]
Tag creation is inconsistent. Most of tags are lightweight. From man git-tag:

>        Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a
>        "lightweight" tag is simply a name for an object (usually a commit object).
> 
>        Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will
>        ignore lightweight tags by default.

$ git for-each-ref refs/tags
9da7687a794d93bc09b095224640899933337e5e tag	refs/tags/0.1
2a642ef8148af0c5619f2d61864a0d732aa84362 tag	refs/tags/0.11
62dae1be0acf7f2b37fa9d6d18b49bc48317f3a4 tag	refs/tags/0.2
24f6e90a88953dbfbbedac26457cdb285c1f9f78 tag	refs/tags/0.2.1
9e98d661ed0bfb50c66af74c74f33927dbde87a8 tag	refs/tags/0.2.2
b0c94f2d02918d7497c995c98ea7ddd30ef10212 tag	refs/tags/0.2.3
ea652ed8bde179d467e79e5ce212036cbe7bb152 tag	refs/tags/0.3
4429312af3317c29c29efca7ca12abd706175c56 tag	refs/tags/0.3.1
a3cc629f004c15e1e2764990afa67ba2ce538b47 tag	refs/tags/0.3.2
e7edeec1eebc2b8fee582e37758db566af011df1 tag	refs/tags/0.4
6acca13f1aa8f56cef327e0aceb1f1bb8c9537a4 tag	refs/tags/0.4.1
76f06bf2d3e01d17c0d87d30ad595ca56652c5ab tag	refs/tags/0.4.2
727f30a7dd7a21a3fa6e9827ff33d47c333ffeb4 tag	refs/tags/0.4.3
0955faa839bff61fec67199b22fd5dfe19d31cfc tag	refs/tags/0.4.5
acd13362e9d44cb78b04f8e03c5eb2e09afb82ea tag	refs/tags/0.4.6
6d3e3d3e02ef48249f03cd99f07d7c167ec1af6b tag	refs/tags/0.5.0
cfb2117f882be3f120db82012a79c52d5ed974f7 tag	refs/tags/1.0.0
19278e4a12426818e0de4725bd17669810905748 tag	refs/tags/1.0.1
1011d9bbfaa25bdd048a82cbdbd4908429953adb tag	refs/tags/1.1.0
c1ebb276618161c47dbe237f01ffc2fdc8f8bf05 tag	refs/tags/1.1.1
26e0d449737e8671000f671d820a9537f23f345a commit	refs/tags/1.10.0
f1083cbada337731ed0b7e27b09eee7a26c8189a commit	refs/tags/1.10.0rc1
fc00875ed00555e5da5661324479e8703787bbd5 commit	refs/tags/1.10.0rc2
862ad8b9c2eb9af206d369bc661b6a2decc22148 commit	refs/tags/1.10.0rc3
26e0d449737e8671000f671d820a9537f23f345a commit	refs/tags/1.10.0rc4
adc2245a3bc094a7b27e01ca1c81447bb2743848 tag	refs/tags/1.10.1
fa9088699696d89a7d00f3cdadc9b1360978a86c commit	refs/tags/1.10.1b1
c870fa9e362f8129d5bca82f2332793a72f97141 tag	refs/tags/1.10.1rc1
c929ae555746ed8552fde3c0aae6ccc49022dbdb tag	refs/tags/1.10.1rc2
6d33636f3e83865258a68256daa33b56369d83a6 tag	refs/tags/1.10.2
68d59caf3350b35acf70149d3863b1b28171c96b commit	refs/tags/1.10.2b1
2be7b1b3ebdb39b11646fa0e8bdc837e4e71bfc0 commit	refs/tags/1.10.2b2
fa50cf764c6c25c603480b82277f7981fb524a83 commit	refs/tags/1.10.2rc1
d72778386f63db33e5587df6268c266d45b7a980 commit	refs/tags/1.10.2rc2
cb8b2a1dc64c3ea6ba445893c65c6c953dfb476a commit	refs/tags/1.10.2rc3
16d93c9e45e14179c7822fed248743f0c3fd935c commit	refs/tags/1.10.3
895d355f4f3cec10c7657d5f445e558bcf58b329 commit	refs/tags/1.10.3b1
47a744f8a5b62ac61495465c1b93611d507c790f commit	refs/tags/1.10.3b2
4c1a21834d32f61d3daee5a44c891fe62dee8c5f tag	refs/tags/1.10.3post1
4c1a21834d32f61d3daee5a44c891fe62dee8c5f tag	refs/tags/1.10.3post2
224c8bd09916825fea7bd18a33f004d86cea0d0a commit	refs/tags/1.10.3rc1
16d93c9e45e14179c7822fed248743f0c3fd935c commit	refs/tags/1.10.3rc2
a18283911750017a01d538bcdd48283b6a265bfb commit	refs/tags/1.10.4
037bdb209d01e65bb009219134036959f936d998 commit	refs/tags/1.10.4b1
7e803d1c01b73afa9e1acf0e90a1e0b9907df491 commit	refs/tags/1.10.4b2
a749316d191bc39424cde36c53ecbc519fbf794e commit	refs/tags/1.10.4rc1
19bb7f7e83d9a8a01e1766b3b0ad99eda8ef2287 commit	refs/tags/1.10.4rc2
fd437d6b090d33d649676523b9a0be2f77e5edc1 commit	refs/tags/1.10.4rc3
e424f1792ac4abe2a83cdeeccfbc79e19a809c96 commit	refs/tags/1.10.4rc4
a18283911750017a01d538bcdd48283b6a265bfb commit	refs/tags/1.10.4rc5
704e48dee368d193f742e064f42461205ef587e2 commit	refs/tags/1.10.5
704e48dee368d193f742e064f42461205ef587e2 commit	refs/tags/1.10.5rc1
73bf718358c01cc41e5f23b914a8824a2665a28c commit	refs/tags/1.10.6
94971510d2b4474098a4e1246c6e5d805fe0eb5e commit	refs/tags/1.10.6rc1
73bf718358c01cc41e5f23b914a8824a2665a28c commit	refs/tags/1.10.6rc2
c8597cbf143b970ad3c7b0d62e3b44d1dfdc8afe commit	refs/tags/1.10.7
01e245cf10e79f2353c20249398735b9ee79f79c commit	refs/tags/1.10.7rc1
123a6d67428efdc784c8dad6b375d778ea579a85 commit	refs/tags/1.10.7rc2
c8597cbf143b970ad3c7b0d62e3b44d1dfdc8afe commit	refs/tags/1.10.7rc3
b0d62f28343fed6a989558f0c26dc1ae83fcbdc0 commit	refs/tags/1.10.8
b0d62f28343fed6a989558f0c26dc1ae83fcbdc0 commit	refs/tags/1.10.8rc1
4b25cb9d08565502172cb847c79d81559775d504 commit	refs/tags/1.10.9
4b25cb9d08565502172cb847c79d81559775d504 commit	refs/tags/1.10.9rc1
ba1c2fa1cbf335936dc3a3a5c67acbb6f71316b4 tag	refs/tags/1.2.0
3c9f782ca4f63068fab25eed71e4a1a545072797 tag	refs/tags/1.3.0
305465d13c44960cb4d1c11ebf3f83425769ca1f tag	refs/tags/1.4.0
db26311f98a8e36a35c28cd92daf370cc49ca7d1 tag	refs/tags/1.4.1
065617a58a578ad48509c28b45efc51d6b4de193 tag	refs/tags/1.5.0
70a9f4f800608424985aef952aac4ad504edd444 tag	refs/tags/1.5.1
ce25e4a7381d30affda893fadbbe7c91bbadb0d1 tag	refs/tags/1.5.2
c267b0ec61d6a35935f3184190ecd96f51067ba9 tag	refs/tags/1.6.0
642861f0744de3044cae8587c8c57a1591bf2983 tag	refs/tags/1.6.1
161e473ee4f703d3a73ff3925ee1af67921522c1 commit	refs/tags/1.6.2
35cb43992161893b7b34c3b7177662ef47d3cfc5 commit	refs/tags/1.6.2-docs
f71ea7023143185830a7cdc36c3b2010441aaa25 commit	refs/tags/1.7.0
ffc070100a6608c83a13ab0d025cfcae72c6cff8 commit	refs/tags/1.7.0rc1
1d0d8681ddf89fabd5f3521d0846a758e47962b3 commit	refs/tags/1.7.1
16cf31d90cba68a86358fc9d5d112a738e2592e5 commit	refs/tags/1.7.1.1
408b7e6c51bec78c31e506e84ea219e8deb7531a commit	refs/tags/1.7.1.2
209bf9c7b3f36dcb169cd402e626aef7c522986e commit	refs/tags/1.7.1.3
209bf9c7b3f36dcb169cd402e626aef7c522986e commit	refs/tags/1.7.1.3-docs
6581858703211bad60793f4b278871edb842fd46 commit	refs/tags/1.7.1rc1
d6a348f9d985e347ceec6e40f6e9e20d17bfd3a5 tag	refs/tags/1.8.0
a37e675ad73a0e161ac811794e3a522917b5fd74 tag	refs/tags/1.8.0+apache.incubating
37262bc7dfa5bd0cd9bd7adf5492f2e0a4beec9e commit	refs/tags/1.8.0-docs
0d8509e7ec9894c62664df81b4f76fa37727d84d commit	refs/tags/1.8.1
32a26d84b679a54add43092d0bdb77350dcbaeaf commit	refs/tags/1.8.2
c6a09c47e6402a05d2477e6431c6d717e2b5a3ba commit	refs/tags/1.8.2rc1
302520828cdce65a4efa65d495bb0b5d05b35069 commit	refs/tags/1.8.2rc2
0be35d6280cd3e2a64b02989de4a3d99e24f0989 commit	refs/tags/1.8.2rc3
32a26d84b679a54add43092d0bdb77350dcbaeaf commit	refs/tags/1.8.2rc4
d760d63e1a141a43a4a43daee9abd54cf11c894b commit	refs/tags/1.9.0
97666b5669042078d4958e6e350306cc0f9ebe7d commit	refs/tags/1.9.0alpha0
afcdd097d765c8e88b4858436bb01585bc04ba7f commit	refs/tags/1.9.0alpha1
b50017036e8b85a3e7e09ac247f3e7b08b5c023f commit	refs/tags/1.9.0rc1
f87d8aca93cf2c6df21bea7b13b6703d91f09865 commit	refs/tags/1.9.0rc2
6ccd54113a3b219220a9affb4298d19507de9de1 commit	refs/tags/1.9.0rc3
a02291b175fb0a441bd841e5dae94369061abb69 commit	refs/tags/1.9.0rc4
2205f498b7a9f7775a70c41ee7ad8052cf346894 commit	refs/tags/1.9.0rc5
575b78fd5551a9d79c2c63fd450c936f0281686e commit	refs/tags/1.9.0rc6
8457b0036939c75c967d4750a55e4513f98546a1 commit	refs/tags/1.9.0rc7
d760d63e1a141a43a4a43daee9abd54cf11c894b commit	refs/tags/1.9.0rc8
6581858703211bad60793f4b278871edb842fd46 commit	refs/tags/airbnb_1.7.1rc1
8d72975734e66d6efa775cec62dd0aea87575c0d commit	refs/tags/airbnb_1.7.1rc10
39ab764a9a8a37fd29be39fa53cbc3a3642a7e41 commit	refs/tags/airbnb_1.7.1rc11
15637b0ed9a60cf27ad7a5990ad88b7389db9341 commit	refs/tags/airbnb_1.7.1rc13
061dfc6cc4ee84632ee0d272e2e8da32a69f7e79 commit	refs/tags/airbnb_1.7.1rc14
173b193132411c54a9d249f5e51251088bd5c02a commit	refs/tags/airbnb_1.7.1rc2
f1ff65c8cde913fd9bfa8b21f83c7300b8b0effd commit	refs/tags/airbnb_1.7.1rc3
173b193132411c54a9d249f5e51251088bd5c02a commit	refs/tags/airbnb_1.7.1rc4
563be1324d982f6033e7d087f41e070805aefa21 commit	refs/tags/airbnb_1.7.1rc6
f4e9fd68e0cb32bf65af6c719ebd97ae93fd841a commit	refs/tags/airbnb_1.7.1rc7
51ee7d36c407875aeaddad5ba3fb56e3fc3acc58 commit	refs/tags/airbnb_1.7.1rc8
546e54cef3565e72816d44876db5556a1f89c54a commit	refs/tags/airbnb_prod.1.6.1.0
190ee9398dedbecf056bf0b80d3b2aa4cb211cd3 commit	refs/tags/airbnb_prod.1.6.1.1
3be5e81154728a7fa2ca5c7072e3ba8b9750d9f1 commit	refs/tags/airbnb_prod.1.6.1.2
0f69d352e0d99707416ce072834feaecc5821eb7 commit	refs/tags/airbnb_prod.1.6.1.3
a0e41d32e1e428d35e63e4a5e2f245348a07fcc5 commit	refs/tags/airbnb_prod.1.6.1.4
715b98509c4155137c50eb6e8396dbe6873c6c8a commit	refs/tags/airbnb_prod.1.6.1.5
e19bc21ff19d9804f4d5be5ad96390fce802080c commit	refs/tags/airbnb_prod.1.6.1.6
101c957821de3d7e9e114150be57f25c95af463e commit	refs/tags/airbnb_prod.1.6.1.7
072f4e8d2754f500132189621f6f0d766ae1ef84 commit	refs/tags/airbnb_prod.1.6.1.8
85ff87ee12feb3a4e7525c4d9975d830e657866f commit	refs/tags/airbnb_prod.1.6.2.1
ea16895a0cfc8071fab3e5c3232b060169342dda commit	refs/tags/airbnb_prod.1.6.2.10
d233e41dadb8b2d043aef4be7ca043e3677c70a9 commit	refs/tags/airbnb_prod.1.6.2.2
bd0966069473276a34cb6443981ed4bdaf0a37bd commit	refs/tags/airbnb_prod.1.6.2.3
2c150966f2c96997be4aac851f460088168b249b commit	refs/tags/airbnb_prod.1.6.2.4
0f5ff784d08538430c8dbd2348d815dcf8e50b72 commit	refs/tags/airbnb_prod.1.6.2.5
95fa58fbd395652fcb71fb7500b85f828ffbfa09 commit	refs/tags/airbnb_prod.1.6.2.6
f74e6900e06e8b490112efb938abb822f04f71ab commit	refs/tags/airbnb_prod.1.6.2.7
7866d5d32dde6afcc958d6bc70a4fbd495982ede commit	refs/tags/airbnb_prod.1.6.2.8
ffc070100a6608c83a13ab0d025cfcae72c6cff8 commit	refs/tags/airbnb_prod.1.6.2.9

**Comment by turbaszek** [comment]
@potiuk or @kaxil do you think we can do something about it?

**Comment by ashb** [comment]
What exactly is the issue/ask? Most tags in most projects are lightweight. Are you saying we should use annotated tags?

**Comment by potiuk** [comment]
Agree with @ashb 

I was in a project where all commits and all tags were signed and during release, the signatures were verified with public keys of all the developers. But this was a project that had requirements coming from payment certifications and it had really high security requirements (thus bureaucracy). I personally designed a procedure where the OS for the terminal was prepared in a secure room which was electromagnetically isolated and it was built on a laptop that had never been connected to internet. The public keys of all developers were stored on a USB kept in a safe.  True story! Not so long ago.

But let's get back to the ground. This is an open-source project that has plenty of eyes looking at it every day. There is no reason to use annotated tags for it.

If you want to introduce annotations and signing - you really have to go all the way and secure every single step of the process. As long as you have no way to verify whether the tag has been signed by the right people, it does not give you much.

**Comment by potiuk** [comment]
Won't fix.

**Comment by ashb** [comment]
Also signing our commits is only half the battle - it does nothing for the few hundred projects we depend upon

**Comment by kaxil** [comment]
In any case, we upload signed releases at https://dist.apache.org/repos/dist/release/airflow/ and KEYS of Release Managers are available at https://dist.apache.org/repos/dist/release/airflow/KEYS

**Comment by potiuk** [comment]
Why ?  What would be the scenario you want to handle?

**Comment by aostapenko** [comment]
The purpose of reporting this issue is a promotion of best git practices enabling an ability to use git functionality that ignores lightweight tags. Like using git push --follow-tags for mirroring particular branch with all tags pointing to revisions available from this branch.

**Comment by cwedgwood** [comment]
one nice property of annotated tags is "git describe" works, i use this in makefiles and also for container tags

**Comment by ashb** [comment]
@aostapenko Show me something other than git's own docs that claims annotated tags are best practice and we can revaluate it. Git's docs are primarilry written by git+linux kernel developers.

What does `git push --follow-tags` give that `git push --tags` doesn't?

@cwedgwood `git describe --tags` works with non-annotated tags.

**Comment by aostapenko** [comment]
Who created tag and when is rather a helpful info. We don't discuss why commits have an author, date and commit message. Why should this be different for tags? Creating release tag using particular commit is an accountable decision. And additional info may help to better understand occurrences of tag recreation.

**Comment by potiuk** [comment]
I think we can discuss this as one of the possibilities to use when we discuss how we approach 2.0 versioning and release. WDYT @ashb ?

**Comment by ashb** [comment]
> Who created tag and when is rather a helpful info

Sure, can be. It ultimately doesn't change much of our process to use annotated tags, even if all the info in an annotated tag is falsifiable. I can very easily push an annotated tag that makes it look like we released Airflow 1.10.11 in 1971 :)

**Comment by potiuk** [comment]
Following up the discussion I just started in https://lists.apache.org/thread.html/r04e1675677dbf85e124955661d6173c6e09933c2bfe2ce8af8ef2e56%40%3Cdev.airflow.apache.org%3E - I think one of the possibilities we might have for optimising our image building and DockerHub publishing of images, my proposal is to create daily snapshot tags using cron jobs in Github Actions. Then I think it would make sense to make the distinction:

1) Daily snapshot tags created automatically would be lightweight tags (we need them if we want to have nightly builds on DockerHub - they cannot be triggered on schedule, they can only be triggered  via Tag or Branch push. 

2) Release tags created manually by the release manager would be annotated tags.

I think that might make perfect sense and could be an easy way to separate one from the others. 

@ashb @kaxil @dimberman you were all involved in release/management and  DockerHub build discussions -> what do you think?

**Comment by ashb** [comment]
As I posted on the mailing list, it's possible to make a POST request to a special url on docker hub to build all or a specific tag -- coupled with a cron'd CI action/job we can get 1 without git tags.

**Comment by potiuk** [comment]
Now - we will make a nightly tag with #8549  - so the "release" tags in the future can be annotated I think - still to make a distinction. I don't think there's any harm in it. I'ts jus t a matter of adding a flag in our release scripts.
