### ISSUE TITLE
Custom SSL CA CERTIFICATE by Configuration for Kubernetes Executor

### ISSUE THREAD

**Issue by nirousseau** [apache/airflow#8019]
**Description**

Add more configuration settings for the _Kubernetes Executor_ in order to support `ssl_ca_cert` (parameter for **kubernetes-client / python** : customize the certificate file to verify the peer).

As an example :

_airflow.yaml_
`[kubernetes]`
`ssl_ca_cert = `

**Use case / motivation**

We are prototyping Airflow in a Kubernetes Cluster that is issuing a custom CA Certificate. Since we are not able to add our certificate to the TrustChain, airflow can't communicate with the API Server.

When no `ca_cert` is specified, **kubernetes-client** will use **certifi** as its TrustChain. 

See : https://github.com/kubernetes-client/python/blob/master/kubernetes/client/rest.py#L66

All queries will use urllib3, using **certifi**'s ca.

**Related Issues**

N/A

**Comment by nirousseau** [comment]
I would be very happy to contribute to the project, to my mind, this issue can be resolved by adding my configuration line around this : [executors/kubernetes_executor.py#L70](https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L70).

something of the form :

self.ssl_ca_cert = conf.get(self.kubernetes_section, 'ssl_ca_cert')

But I don't see the entrypoint for notifying the underlying kubernetes client to use the new `ssl_ca_cert` var 😢

**Comment by nirousseau** [comment]
bump 👍

**Comment by nirousseau** [comment]
bump 👍

**Comment by nirousseau** [comment]
bump²

**Comment by eladkal** [comment]
cc @jedcunningham WDYT?
