### ISSUE TITLE
Clearbit integration

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow#8026]
**Description**

Add integration to [clearbit](https://clearbit.com/docs#api-reference) using thier [python package
](https://github.com/clearbit/clearbit-python)

**Use case / motivation**

We want to build ETL that takes data from clearbit and put it in GCS so an operator for this will be very useful.

**Related Issues**

None

**Comment by turbaszek** [comment]
@alexInhert would you be interested in doing this integration? I'm happy to help :)
