### ISSUE TITLE
BigQueryCursor not using Location when fetching results.

### ISSUE THREAD

**Issue by romainjln** [apache/airflow#8031]
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: Might not be relevant (UNIX)

- **Cloud provider or hardware configuration**: GCP but able to reproduce that locally too
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
We are trying to use Airflow BigQueryHook to get some records from our warehouse (via method get_records inherited from the class DbApiHook) in a custom sensor class. The dataset that has the table we are querying is located in `europe-west2`

The BigQuery job is properly sent/received to/by our BigQuery server and according to the WebUI of BigQuery, the query is successful. 

In the log of the Airflow task, we can see that the task switches from:
(checking the status of the job)
```
INFO - URL being requested: GET https://bigquery.googleapis.com/bigquery/v2/projects/{our_project}/jobs/{job_id}?location=europe-west2&alt=json
```
to:
(trying to get the results of the query)
```
INFO - URL being requested: GET https://bigquery.googleapis.com/bigquery/v2/projects/{our_project}/queries/{job_id}?alt=json
```
But this http request returns a 404 error: Job not found. 

**What you expected to happen**:
We expect the job to be found and the result of our query to be returned.

**Possible explanation**
By inspecting the logs, we can see that in the second GET http request the location parameter is not used. 
We think that this could be explained by the fact that the function `next()` of the class `BigQueryCursor` calls the method `getQueryResults` without passing the parameter `location`. 

**How to reproduce it**:
By creating a table in a dataset located in `europe-west2` (I guess any region would exhibit this behaviour as long as the dataset is not located in a multi-region like EU or US) and running the following function in a PythonOperator for example:
```
def check_bug(conn_id):
    hook = BigQueryHook(conn_id, use_legacy_sql=False) # same result when using parameter location='europe-west2'
    records = hook.get_records('''SELECT 1 FROM {newly_created_table}''')
```

**Comment by mik-laj** [comment]
In Q2, we're planning major upgrades for BigQuery operators. Your opinion is very important and we will definitely take it into account during our work.

**Comment by mik-laj** [comment]
We corrected this error and release it in a backport package.
https://github.com/apache/airflow#backport-packages
If you still have any problems, please let me know.
