### ISSUE TITLE
Security: Variable level ownership/permission

### ISSUE THREAD

**Issue by selvathiruarul** [apache/airflow#8032]
**Description**

Feature to provide variable level permission to users/roles. so that in an organization, different users can manage their own variables.

**Use case / motivation**

Provide user/role level permission to each variable, so that a user don't have to reach out to others to change their own variables or won't have permission to change other variables by mistake.

**Comment by ashb** [comment]
This is a nice feature, but how would this interact with DAGs trying to access variables?

And also for DAGs accessing variables: it would be best effort and not an actual protection as DAGs run with full database access, so could by-pass any code-level protection on Variable. (This would be true if/until we move workers from not having direct database access.)

**Comment by eladkal** [comment]
This is part of the multi tenancy https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-1%3A+Improve+Airflow+Security
I'm closing as issues related to that should be discussed in the AIP.
