### ISSUE TITLE
Security: make user in mysql

### ISSUE THREAD

**Issue by 8432konia** [apache/airflow#8035]
**Description**
[reference](https://airflow.apache.org/docs/stable/security.html#web-authentication)

I wanna make first user , so I ran  this code.
```
$ cd ~/airflow
$ python
Python 2.7.9 (default, Feb 10 2015, 03:28:08)
Type "help", "copyright", "credits" or "license" for more information.
>>> import airflow
>>> from airflow import models, settings
>>> from airflow.contrib.auth.backends.password_auth import PasswordUser
>>> user = PasswordUser(models.User())
>>> user.username = 'new_user_name'
>>> user.email = 'new_user_email@example.com'
>>> user.password = 'set_the_password'
>>> session = settings.Session()
>>> session.add(user)
>>> session.commit()
>>> session.close()
>>> exit()
```

Maybe this code is only sqlite ... How using mysql ?

**Comment by zhongjiajie** [comment]
Try to use `airflow users create` in command line to create new user? @konia-s

**Comment by zhongjiajie** [comment]
@konia-s Check if you change configure in https://github.com/apache/airflow/blob/6f4e3b6a05dd4e6944fefa7f6fdada64b5c6e025/airflow/config_templates/default_airflow.cfg#L380

**Comment by konia-s** [comment]
thx !!!
I can make user ><
