### ISSUE TITLE
SalesforceHook not compatible with simple_salesforce 1.0.0

### ISSUE THREAD

**Issue by shawon-crosen** [apache/airflow#8036]
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.17.0

**Environment**: production

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **Kernel** (e.g. `uname -a`): Linux 0 4.14.138+ #1 SMP Tue Sep 3 02:58:08 PDT 2019 x86_64 GNU/Linux
- **Install tools**: pip
- **Others**: helm
**What happened**:

When running out salesforce dag, which uses a custom hook that wraps the base hook, the base hook gives us the following error:

**What you expected to happen**:

I expected the base SalesforceHook() class to properly sign in and pull data. It seems that this issue started occurring with the latest release of simple_salesforce, version 1.0.0.

Based on the simple_salesforce code, it looks like the sign_in method in the SalesforceHook class in airflow/contrib/salesforce/hooks/salesforce_hook.py is still calling a deprecated keyword argument of `sandbox`. 

Here is a link to the commit for simple_salesforce 1.0.0 12 days ago: https://github.com/simple-salesforce/simple-salesforce/commit/1ebee0085b27ab5f9181a5e691fb8dc9fdc90163

**How to reproduce it**:

Try to use the SalesforceHook in a dag that installed apache-airflow 1.10.9 via pip. I am using the stable/airflow helm chart with the puckel/docker-airflow docker image.

This happens every time the SalesforceHook class tries to sign in with the Salesforce credentials

**Comment by eladkal** [comment]
was fixed in master https://github.com/apache/airflow/pull/7857

**Comment by ShawonC** [comment]
Do you know if/when that fix will be pushed to the pypi package repository? Or is that fix only for the master version that will become 2.0.0?

**Comment by eladkal** [comment]
I can prepare a PR for 1.10 branch but it will be a breaking change.
Maybe better approach is to pin simple-salesforce on the 1.10 branch.

I'll wait for comments from the community which approach is preferred.

**Comment by potiuk** [comment]
I think pinning is a better solution. Is there any reason (for now) to move to 1.0 that anyone is aware of?

**Comment by mik-laj** [comment]
I think the best solution is to pin old versions and release new operators in the backport package. https://cwiki.apache.org/confluence/display/AIRFLOW/Backported+providers+packages+for+Airflow+1.10.*+series

@eladkal To release a package with operators, operators must be tested (preferably using system tests) and there must be a person who will be the maintainer. Are you interested?

**Comment by ShawonC** [comment]
From my end I was mostly just curious if an update for the pypi stable package would be released. 

Right now I have the version for simple-salesforce pinned to <1.0.0 for my own airflow deployment and it's working fine.

**Comment by potiuk** [comment]
> I think the best solution is to pin old versions and release new operators in the backport package. https://cwiki.apache.org/confluence/display/AIRFLOW/Backported+providers+packages+for+Airflow+1.10.*+series

True. This is already what will happen automatically with the current backport mechanism. You are right @mik-laj -> we can easily rely on that mechanism. This means that when you install `apache-airflow-backport-salesforce` package, you will be able to use the new "providers" salesforce operators but not the old ones

**Comment by eladkal** [comment]
@ShawonC I did the same in my docker.

@mik-laj I'll take a look yet I'm not sure there is needed
The [change log](https://github.com/simple-salesforce/simple-salesforce/blob/master/CHANGES#L1) for the new version is very small and it doesn't look there is something super important in the new version. I think the bump of version was only due to the breaking change of the `sandbox` parameter and the drop support of older python versions. Yet looks like their change log is incomplete as it doesn't even mention the breaking change of the `sandbox` parameter.

I would recommend to wait and see if there demand for such backport before investing the time.

@potiuk you already pinned it before my PR so maybe just cherry pick https://github.com/apache/airflow/pull/7775 for 1.10?

**Comment by potiuk** [comment]
Actually - we do not need to do anything to make backport packages work. That's the beauty of it ...

And  ....  it's already cherry-picked: https://github.com/apache/airflow/commit/3264302816a2dc59fc3a0a1912a9d23b923e4348

**Comment by mik-laj** [comment]
@eladkal We do not do these packages just to give you the option to use these operators earlier. There is also a second reason. We want to improve the quality of these integrations and facilitate their testing in an automatic way.

**Comment by eladkal** [comment]
Issue is fixed in [salesforce provider](https://pypi.org/project/apache-airflow-backport-providers-salesforce/)>=  2020.6.24
