### ISSUE TITLE
[AIP-31] Resolve XComArg in template_fields

### ISSUE THREAD

**Issue by casassg** [apache/airflow#8053]
**Description**

As a DAG Author, I want to set a templated_field as XComArg and for it to get resolved into the XCom object at execution time.

_Proposed implementation_
- Add a new check in `BaseOperator.render_template` that checks if the content is `XComArg` and applies the `get` method to replace the content. [Code location.](https://github.com/apache/airflow/blob/2869d3dae03f7d7bd5bea66c25ae0e0c97771281/airflow/models/baseoperator.py#L801)

**Use case / motivation**

- Set explicit XCom values in `templated_fields` instead of using string templates.

**Related Issues**

Blocked by: #8052

**Comment by turbaszek** [comment]
FYI @jonathanshir
