### ISSUE TITLE
Support DAGS folder being in different location on scheduler and worker.

### ISSUE THREAD

**Issue by rabsr** [apache/airflow#8061]
**Description**

Dags folder in celery workers can be kept at different location as kept in Airflow scheduler node. Airflow task run can use dag full file path based on airflow home configuration on their node given dag file relative path to dags folder.

**Use case / motivation**

Currently scheduler uses absolute path for dags file to schedule task in task run command (`-sd` arg). This command makes hard to keep dags folder at different locations in celery workers which may be running in different environment. So using Airflow with celery with cross environment setup is difficult. 
This feature will help to keep dags folder at any location at worker nodes and tasks command can be configured for dag file path using home configuration.

**Comment by turbaszek** [comment]
@rabsr would setting `AIRFLOW__CORE__DAGS_FOLDER` solve the issue?

**Comment by mik-laj** [comment]
@turbaszek This will not help because an absolute path is added to the queue. Someone once tried to fix it but it doesn't work now.
https://github.com/apache/airflow/blob/master/airflow/models/taskinstance.py#L273-L279

**Comment by ashb** [comment]
I think this got broken when the "SimpleDagBag" concept was introduced.

**Comment by pogson** [comment]
I just encountered this. Strange thing is that a regular scheduled dag is sent to the celery worker with the full path... but if you click run and ignore all the celery worker get `DAGS_FOLDER/dagname.py`. I'm on 1.10.5 right now.

**Comment by aragaorenan** [comment]
Hello everyone, any update about this issue?

**Comment by mik-laj** [comment]
@aragaorenan  I did not see any active contributions related to it. This is also not a big problem if you are using containers/Docker or other [mount namespace](https://en.wikipedia.org/wiki/Linux_namespaces#Mount_(mnt)) isolation, so I wouldn't expect this problem to be fixed quickly.

**Comment by JCoder01** [comment]
At first pass I can see 2 paths to fixing this.
1) change what gets passed in to `TI.generate_command` [here](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L1103) to replace the local dags_folder with `DAGS_FOLDER` or add a property `dag_model` such as `generic_file_path` and pass that in rather than `fileloc`, either way do a `.replace(settings.DAGS_FOLDER, 'DAGS_FOLDER'), 'DAGS_FOLDER')` somewhere
or
2) move it further upstream and do something with `fileloc` in the db to strip out the path of the dags_folder before saving to the table.
@ashb and @kaxil thoughts?

**Comment by ashb** [comment]
@JCoder01 probably 2 is a "better" solution, yeah.

**Comment by JCoder01** [comment]
@ashb that's what I was thinking too, why does the "better" solution always seem to be the more complicated one... One possible hiccup, if dag serialization isn't enabled, isn't this still an issue? Maybe both 1 and 2 need to be done?

**Comment by ashb** [comment]
on 2.0 DAG serialization cannot be turned off anymore, so that's not a problem

**Comment by JCoder01** [comment]
Ok, after I wrote that I was just looking through the code to see if that mattered and was about to edit my comment.

**Comment by JCoder01** [comment]
Closed MR, This doesn't seem to be too big of a problem and I was able to handle it by monkey patching TaskInstance.generate_command in my airflow_local_settings.py

**Comment by rabsr** [comment]
@JCoder01 Will you be able to share the patch for this feature? I would like to try it in our setup.

**Comment by JCoder01** [comment]
Hi @rabsr here you go, let me know if you have any questions.
```
from airflow.settings import DAGS_FOLDER
from airflow.models.taskinstance import TaskInstance
from typing import Optional, List
from datetime import datetime

old_generate_command = TaskInstance.generate_command
def new_generate_command(
        dag_id: str,  # pylint: disable=too-many-arguments
        task_id: str,
        execution_date: datetime,
        mark_success: bool = False,
        ignore_all_deps: bool = False,
        ignore_depends_on_past: bool = False,
        ignore_task_deps: bool = False,
        ignore_ti_state: bool = False,
        local: bool = False,
        pickle_id: Optional[int] = None,
        file_path: Optional[str] = None,
        raw: bool = False,
        job_id: Optional[str] = None,
        pool: Optional[str] = None,
        cfg_path: Optional[str] = None,
) -> List[str]:
    dags_folder = f'{DAGS_FOLDER}/' if not DAGS_FOLDER.endswith('/') else DAGS_FOLDER
    file_path = file_path.replace(dags_folder, 'DAGS_FOLDER/')
    return old_generate_command(dag_id,
                               task_id,
                               execution_date,
                               mark_success,
                               ignore_all_deps,
                               ignore_depends_on_past,
                               ignore_task_deps,
                               ignore_ti_state,
                               local,
                               pickle_id,
                               file_path,
                               raw,
                               job_id,
                               pool,
                               cfg_path)

TaskInstance.generate_command = new_generate_command
```

**Comment by jhtimmins** [comment]
@ashb can this be closed, since there's a workaround?

**Comment by ashb** [comment]
No, we should fix this properly in Airflow.

**Comment by baryluk** [comment]
Hi.

Re #16860 

I think these change should be better documented in changelog, as well in the Kubernetes Pod template documentation ( https://airflow.apache.org/docs/apache-airflow/2.2.2/executor/kubernetes.html#example-pod-templates ).

It causes now dag failures, if the variable `AIRFLOW__CORE__DAGS_FOLDER` is not set on worker pods. It was not the case when running Airflow 2.1.4, but started failing in 2.2.x.

**Comment by ashb** [comment]
@baryluk that setting has a default value, so you shouldn't _have_ to set it. (AIRFLOW_HOME/dags is the default, i.e. `~/airflow/dags`)

What behaviuor are you seeing?

**Comment by potiuk** [comment]
> It causes now dag failures, if the variable `AIRFLOW__CORE__DAGS_FOLDER` is not set on worker pods. It was not the case when running Airflow 2.1.4, but started failing in 2.2.x.

I think the problem was that the AIRFLOW__CORE__DAGS_FOLDER variable but not in workers and it is not how it is supposed to be. It worked "accidentally" this way but it was never intended:

See https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html

> Use the same configuration across all the Airflow components. While each component does not require all, some configurations need to be same otherwise they would not work as expected. A good example for that is secret_key which should be same on the Webserver and Worker to allow Webserver to fetch logs from Worker.

**Comment by potiuk** [comment]
@baryluk  I think we added this comment in 2.2.0 to clarify similar problems pople had, but this was always "intented" even if not as clearly documented - so what you did in this case, you discovered a misconfiguration of your deployment simply.

**Comment by baryluk** [comment]
In our airflow instance, we do set `AIRFLOW__CORE__DAGS_FOLDER` on the scheduler (via chart), to non standard location `/opt/airflow/dags/primary` afaik. But not on k8s pod templates. Scheduler is not forwarding its own `AIRFLOW__CORE__DAGS_FOLDER` setting to the pod template, if it is not set there.

**Comment by potiuk** [comment]
> In our airflow instance, we do set `AIRFLOW__CORE__DAGS_FOLDER` on the scheduler (via chart), to non standard location `/opt/airflow/dags/primary` afaik. But not on k8s pod templates. Scheduler is not forwarding its own `AIRFLOW__CORE__DAGS_FOLDER` setting to the pod template, if it is not set there.

Ah yeah - the comment in config also applies to the pod template.
 
> And again, if this is misconfiguration, why there is no mention of this in the https://airflow.apache.org/docs/apache-airflow/2.2.2/executor/kubernetes.html#example-pod-templates ?. It basically provides a bad example.

The example is good as an example when you do not override it. But agree it's a good  idea to add a note there along the lines of "following the https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html" note make sure that you set all variables in your pod template when you modify them.

Would you like to make PR with that ? I think you are the best person to know how to phrase it so that people like you who do not have same assumptions as we can find it when needed.

**Comment by baryluk** [comment]
@potiuk Ok. I will add a note there, and send PR.

**Comment by intc-hharshtk** [comment]
I got this problem resolved by providing the absolute path of dag and plugin location in airflow.cfg file.
