### ISSUE TITLE
Execution_date before start_date can be run

### ISSUE THREAD

**Issue by Sergey942** [apache/airflow#8063]
After I choose Rendered of a task and choose a date(such as '2005-01-01', before the start_date) to apply, I click "Graph View" of this DAG. I found the base date went to '2005-01-01'. Then if I run a task in this web, it will success.

**Comment by eladkal** [comment]
@Sergey942  can you please specify the exact reproduce steps?

**Comment by Sergey942** [comment]
1. I designed my DAG: 'start_date':datetime(2020,1,1,0,0).Then run all tasks once.
2. View Rendered Template of one task, and choose instance date to '2019-01-01 xx:xx:xx'.
3.Click 'Graph View' of this DAG, the base date will change to '2019-01-01 xx:xx:xx'.
4.Choose any task of this DAG, and click run , it will success.

**Comment by eladkal** [comment]
I think this is expected - to my understanding Run button execute task arbitrary (it works only with Celery/K8s executors).

**Comment by uranusjr** [comment]
Correct, `start_date` only affects DAG scheduling; if you say you want the DAG to do a manual run, it will oblige.

**Comment by eladkal** [comment]
> Correct, `start_date` only affects DAG scheduling; if you say you want the DAG to do a manual run, it will oblige.

He is referring to the Run button of a task not the trigger dag run button:
![Screen Shot 2021-06-20 at 11 28 48](https://user-images.githubusercontent.com/45845474/122667304-d0ac3100-d1ba-11eb-8ca9-d464e805fff9.png)

**Comment by uranusjr** [comment]
Oops, sorry, I misread. The idea is the same though, those manual UI triggers are not a part of scheduling.

**Comment by eladkal** [comment]
yeah.
I'm closing this issue as this is the expected behavior.
