### ISSUE TITLE
Allow Custom Task Runner via plugins

### ISSUE THREAD

**Issue by rabsr** [apache/airflow#8067]
**Description**
Airflow provides a plugin manager to integrate external features. However, there is no configuration available to have custom task runner as part of plugins.

**Use case / motivation**
 Enabling custom task runner integration with Airflow will help users in configuring runners as per environment requirement and dependencies.

**Comment by mik-laj** [comment]
It looks trivial. Do you want to work on it? I think this should not be configured by plugins, but the configuration option. Similar to the executor.
Please look at https://github.com/apache/airflow/pull/7563

How would you like to use it? Do you have any special task runner already implemented?  I wonder if it would be a better idea to contribute it to the community.

**Comment by rabsr** [comment]
It's not any new task runner. I just want to override some functionality at of base task runner as our environment have some restrictions. #8062 

@mik-laj Thanks for quick support. When can we expect it to get released?

**Comment by mik-laj** [comment]
I don't see the reason why it couldn't be part of Airflow 1.10, but I don't deal with older releases. I am only working on Airflow 2.0.

As for the Airflow 2.0 release date.
> Currently, stable versions of Apache Airflow are released in 1.10.* series. We are working on the future, major version of Airflow from the 2.0.* series. It is going to be released in 2020. However, the exact time of release depends on many factors and is yet unknown. 

We also have an open discussion in the community: 
https://lists.apache.org/thread.html/r0abba3669962f101d787ad793611ba436d35c8e022aa565705778b7d%40%3Cdev.airflow.apache.org%3E
