### ISSUE TITLE
Execute SubDAG tasks as part of parent DAG

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#8078]
**Description**

Currently, the SubDagOperator launches a completely different DAG and then monitors it as a separate entity. This has lead to all sorts of edge case (e.g. when workers have different executors than the scheduler).

This Issue suggests that we instead merge all tasks from the subdag into the original DAG with an extra "original_dag" label. this means at the UI level we can still condense all subdag tasks into a single task, but a single scheduler will still perform all task launching.

**Use case / motivation**

We want SubDag tasks to act exactly the same as non-subdag tasks

**Related Issues**

**Comment by dimberman** [comment]
@xinbinhuang

**Comment by xinbinhuang** [comment]
+1

**Comment by dimberman** [comment]
I think it's totally reasonable to say that SubDag separation should be more of a UI feature than an execution feature, so I think if we can identify which tasks are "subdag" tasks, we can condense them in the UI.

**Comment by dimberman** [comment]
@kaxil does this mess with DAG serialization? Would this subdag task adding happen at DAG parsing time?

**Comment by xinbinhuang** [comment]
Yeah, totally agree. I don't think the added complexity with nested dags gives more errors than values.

I actually have a more simplistic thought. Instead of returning a DAG from the dag factory, we can just ask the `dag factory` to return a list of tasks. While the `SubDagOperator` (this become more like a `SubTasksOperator` in this case) can be just used to add an annotation to that group of tasks that will be later used to render the DAG graph in the UI.

**Comment by kaxil** [comment]
> Yeah, totally agree. I don't think the added complexity with nested dags gives more values than errors.
> 
> I actually have a more simplistic thought. Instead of returning a DAG from the `dag factory`, we can just ask the `dag factory` to return a list of tasks. While the `SubDagOperator` (this become more like a `SubTasksOperator` in this case) can be just used to add an annotation to that group of tasks that will be later used to render the DAG graph in the UI.

I like the idea.

>@kaxil does this mess with DAG serialization? Would this subdag task adding happen at DAG parsing time?

No that should work fine

**Comment by xinbinhuang** [comment]
@kaxil @dimberman  Do we need an AIP for this? This seems to change the whole behavior of the `SubDagOperator` or even renaming/removing it.

**Comment by kaxil** [comment]
> @kaxil @dimberman Do we need an AIP for this? This seems to change the whole behavior of the `SubDagOperator` or even renaming/removing it.

Yes, please. This definitely needs voting and some design discussion. Can you please create an AIP and start a discussion thread once you have that AIP doc ready.

**Comment by xinbinhuang** [comment]
> > @kaxil @dimberman Do we need an AIP for this? This seems to change the whole behavior of the `SubDagOperator` or even renaming/removing it.
> 
> Yes, please. This definitely needs voting and some design discussion. Can you please create an AIP and start a discussion thread once you have that AIP doc ready.

Sounds good. I will draft an AIP within this week and open a thread for discussion.

**Comment by xinbinhuang** [comment]
@kaxil  I think I need permission to create an AIP at Confluence. Can you give me permission? My email is `bin.huangxb@gmail.com`

**Comment by dimberman** [comment]
@xinbinhuang SGTM! I'm gonna play around with a Draft PR just to see what I can jerry-rig, but it will be more based around "what CAN we do" than "what WILL we do"

**Comment by kaxil** [comment]
> @kaxil I think I need permission to create an AIP at Confluence. Can you give me permission?

Done

**Comment by xinbinhuang** [comment]
@kaxil @turbaszek @dimberman I found this PR https://github.com/apache/airflow/pull/5498 when I was working on the AIP draft.  It fixed the `SubDagOperator` by using the scheduler instead of backfill, so SubDags will use the same executor as the parent dag. I guess this solves the biggest problem of `SubDagOperator`. 

It seemed to me that the problem has been fixed? Should I proceed to finish the AIP draft?

**Comment by xinbinhuang** [comment]
I think I will proceed with finishing the AIP and then let the community decide. I think it makes more sense to treat `subdag` as in `subgraph to graph` rather than a vertex as right now.

**Comment by kaxil** [comment]
> > It seems to me that the problem has been fixed? I wonder if it is still useful for the suggested change and proceed to finish the AIP draft?
> 
> I think I will proceed with finishing the AIP and then let the community decide. I think it makes more sense to treat `subdag` as in `subgraph to graph` rather than a vertex as right now.

Yes, please do 👍

**Comment by ashb** [comment]
Closing in favour of https://github.com/apache/airflow/pull/10153
