### ISSUE TITLE
Verification of LDAP authentication 

### ISSUE THREAD

**Issue by planenutz** [apache/airflow#809]
Is there anyway to manually verify that LDAP is configured properly in Airflow? All I get is the (nearly) useless message at startup about airflow_login failing to import.

**Comment by NeilHanlon** [comment]
What does your configuration look like?

**Comment by bolkedebruin** [comment]
@planenutz what version of airflow are you using and how did you configure ldap? The error should be logged in the latest version (ie. it is not swallowed any more).

**Comment by planenutz** [comment]
Read in the docs somewhere that LDAP does not work in 1.5.1, which is what we have running. Upgrade is in progress. Probably should close this issue until the upgrade is complete.

**Comment by planenutz** [comment]
Upgraded to 1.6.1. still fails. 

Traceback (most recent call last):
  File "bin/airflow", line 17, in <module>
    args.func(args)
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/bin/cli.py", line 323, in webserver
    app = cached_app(configuration)
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/www/app.py", line 119, in cached_app
    app = create_app(config)
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/www/app.py", line 28, in create_app
    airflow.load_login()
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/**init**.py", line 49, in load_login
    raise AirflowException("Failed to import authentication backend")
airflow.utils.AirflowException: Failed to import authentication backend

But the module is in the path

[pads122.sj2.ups.vclk.net]vccorp@pads122:airflow: >!find
find ./ -name "ldap*"
./lib/python2.7/site-packages/airflow/contrib/auth/backends/ldap_auth.pyc
./lib/python2.7/site-packages/airflow/contrib/auth/backends/ldap_auth.py

Configuration. (we use anonymous querying and no cert for internal queries)

[webserver]
...
authenticate = True
auth_backend = airflow.contrib.auth.backends.ldap_auth
...
[ldap]
uri = ldaps://fs1.sj2.vclk.net:636
basedn = "ou=People,dc=vclk,dc=net"

**Comment by bolkedebruin** [comment]
Are the ldap pre-requisites installed? (I'll have a look later at providing more useful error messages).

**Comment by planenutz** [comment]
was missing ldap3, installed that and now gunicorn is complaining. :-(

**Comment by planenutz** [comment]
LDAP working... closing the ticket.
