### ISSUE TITLE
Introduce Pydocstyle

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8091]
**Description**

Introduce doc style checker in pre-commit

**Use case / motivation**

We could introduce style checker for documentation we have in the code (https://pypi.org/project/pydocstyle/ for example) in pre-commit. That would help us to write a consistent documentation.

**Comment by mik-laj** [comment]
@kaxil @potiuk What else are we planning to do with this ticket?

**Comment by kaxil** [comment]
This can be closed, I will create a new ticket on the following steps
