### ISSUE TITLE
Docs: Broken link to KubernetesPodOperator

### ISSUE THREAD

**Issue by louisguitton** [apache/airflow#8093]
**Apache Airflow version**: 1.10.9 (latest on docs site)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

Go to https://airflow.apache.org/docs/stable/kubernetes.html, click on `KubernetePodOperator`, it sends you to the Executor instead.

**What you expected to happen**:

I expect to arrive on the KubernetesPodOperator page.
Looking at the code, the link points to a page that is now gone.
- rst code with link to old page https://github.com/apache/airflow/blame/1c5e105db7e740540e6b2453b3bfb016925c1e07/docs/kubernetes.rst#L31
- old page is present on readthedocs https://airflow.readthedocs.io/en/latest/howto/operator/index.html
- old page is not present on the new docs https://airflow.apache.org/docs/stable/howto/operator/index.html

**How to reproduce it**:

Go to https://airflow.apache.org/docs/stable/kubernetes.html, click on `KubernetePodOperator`, it sends you to the Executor instead.

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Hi. Could you create PR yourself? You can do this from Github Web UI.
![image](https://user-images.githubusercontent.com/12058428/78363049-66aa6a80-75bb-11ea-90f4-3eb6ca8235d0.png)
https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository
Thnks!

**Comment by louisguitton** [comment]
Sorry if wasn't clear: 
- the link is correct ✅ 
- the destination page is correct ✅ , it's here https://github.com/apache/airflow/blob/master/docs/howto/operator/kubernetes.rst
- when you inspect the HTML, the link is wrong ❌ as you can see here 
![image](https://user-images.githubusercontent.com/7823843/78372392-847ecc00-75c9-11ea-9e09-d0b66548e150.png)
- the fact that it shows up fine on read the docs proves it's rather an issue with the new website

At this moment, it's not clear to me how I could fix this with a PR in the UI on the `.rst` file 😂 

Let me know if in the end the issue is more to open on apache/airflow-site.

**Comment by mik-laj** [comment]
I got it. The problem is only in the 1.10 series. In Airflow 2.0 this problem is gone.
Here is latest doc: https://airflow.readthedocs.io/en/latest/kubernetes.html

**Comment by kaxil** [comment]
Has been cherry-picked to 1.10.10rc2
