### ISSUE TITLE
Set variable from stdin

### ISSUE THREAD

**Issue by briansorahan** [apache/airflow#8105]
**Description**

Would like to be able to do this:
```
cat FILE | airflow variables -s KEY -
```

**Use case / motivation**

Less error-prone than reading the file into a variable and interpolating the variable into a shell command.

**Related Issues**

I searched the github issues for "stdin" and "input" but didn't find anything that looked like it matched.

**Comment by mik-laj** [comment]
This should work.
```bash
airflow variables -s KEY "<(cat FILE)"
```
or
```bash
cat FILE | xargs -I {} airflow variables -s KEY "{}"
```

**Comment by jedcunningham** [comment]
@briansorahan, you can now use variables directly from the filesystem with a [local filesystem secrets backend](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/secrets-backend/local-filesystem-secrets-backend.html). Would that be an acceptable alternative (or what @mik-laj proposed)?

**Comment by briansorahan** [comment]
@jedcunningham I think I ended up doing what @mik-laj suggested
