### ISSUE TITLE
bug: "duration" does not take into account tasks that span multiple days

### ISSUE THREAD

**Issue by neuromusic** [apache/airflow#811]
On the Gantt view, "duration" does not take into account tasks that span multiple days

![screenshot from 2015-12-30 15 52 10](https://cloud.githubusercontent.com/assets/1245615/12059321/e935510a-af0d-11e5-94c0-73c5e6b8040a.png)

**Comment by mistercrunch** [comment]
Fixed in master:
https://github.com/airbnb/airflow/commit/b63b42429ffea52ec9c9a0ead7dbc258ea4c2900#diff-a32a363fa616685db3bfefba947535b2R1141

This will make the next (overdue) release.

**Comment by neuromusic** [comment]
Sweet. Thanks!

Justin

On Sat, Jan 2, 2016 at 10:18 PM, Maxime Beauchemin <notifications@github.com
