### ISSUE TITLE
Authentication in API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8111]
**Description**

We should prepare an authentication mechanism that allows easy extension and adding a new authentication method.

More information about REST API:
https://github.com/apache/airflow/issues/8107

**Use case / motivation**

The purpose of authentication is to achieve a certain level of confidence that the entity is in fact the one it claims to be. Extending authentication methods allows the security requirements of various organizations to be met.

PR does not need to implement any common authentication mechanism. All they have to do is accept the user ID in the request and log in.

**Related Issues**

N/A

**Comment by mik-laj** [comment]
I think we can add a simple decorator that will call functions before handling requests. This function will be responsible for checking the credentials and setting the user attribute in the flask context. FAB and flask_login work in the same way, so we will be able to create a special authorization mechanism that will delegate the operation to FAB Security, as well as add new or specific for a particular organization, e.g. Kerberos, Custom Identity Proxy/Portal (like Astronomer).

A simple code example that authenticates a user with an HTTP header may look like this.

```
from flask import request, g

REMOTE_USER_HEADER = 'REMOTE_USER'

username = request.headers.get(REMOTE_USER_HEADER)
if not username:
    raise AuthenticationProblem(
        403, "Forbidden", f"Header {REMOTE_USER_HEADER} is missing in
the request"
    )

if not request.authorization:
    user = current_app.appbuilder.sm.auth_user_remote_user(username)
    if user is None:
        raise AuthenticationProblem(
            403, "Forbidden", f"Not authorized"
        )
    log.info("User authorized: %s", user)
    g.user = user
```

**Comment by jhtimmins** [comment]
@mik-laj I'm interested in taking over this task. Is the API at a stage where this would be helpful?

**Comment by mik-laj** [comment]
@jhtimmins I wanted to start working on the core today or Wednesday. However, if you have time, you can start working.

**Comment by jhtimmins** [comment]
@mik-laj Cool. Do you mean the core of authentication or the core of the API?

**Comment by mik-laj** [comment]
@jhtimmins Authorization core, i.e. one authorization mechanism (e.g. via HTTP headers) and the ability to choose others using the configuration options.

**Comment by jhtimmins** [comment]
Gotcha, thanks. Is this issue the best place to discuss the design? Thinking I can design interface and 1-2 implementations.

**Comment by mik-laj** [comment]
Yes. We can discuss it here. If we want to have more opinions, we can ask on the mailing list later.  For non-key design discussions, Github is a good place.  If you prefer, you can also create a draft PR.

**Comment by jhtimmins** [comment]
@mik-laj I'm a bit confused about the need to have a customizable auth scheme, where the user can pick a common implementation or add their own. Connexion seems to support a small number of predefined schemes https://connexion.readthedocs.io/en/latest/security.html.

Two questions then:
1. Do you envision users modifying the .airflow.yml file to specify their preferred scheme?
2. How do you picture allowing a custom scheme to fit within Connexion's limitations?

Thanks

**Comment by mik-laj** [comment]
You do not have to specify it in the API specification, because it is a configurable value. OpenAPI does not support this case.

**Comment by jhtimmins** [comment]
Could you explain what you mean by "OpenAPI does not support this case"? Do you mean that OpenAPI doesn't support configurable authentication schemes?

**Comment by mik-laj** [comment]
@jhtimmins OpenAPI is very limiting in the authorization configuration description You cannot describe several authorization mechanisms and selection rules in one specification file. We cannot express all the intentions that users have, so I think we may not include authorization in the API specification at all.  Many users will not use authorization at all, and instead configure the auth proxy to do so (e. g. https://developer.okta.com/blog/2018/08/28/nginx-auth-requesthttps://developer.okta.com/blog/2018/08/28/nginx-auth-request, https://cloud.google.com/iap)

**Comment by jhtimmins** [comment]
@mik-laj Ah I understand. That clarifies it a lot. Thank you.

**Comment by jhtimmins** [comment]
@mik-laj  Ok, I have a rough decision, if you could let me know your thoughts. Ultimately, only `settings.py` needs to be visible to the user if they're using a pre-existing auth function. If they want to add a custom function, they can create a new file and reference it from `settings.py`.

## End result
- `login_required` decorator.

```python
@app.route('/')
@decorators.login_required
def hello_world():
    return 'Hello, World!'
```

## Auth.py
- Defines various authentication functions.

```python
from flask import request

def basic_auth():
    return request.authorization.username == "james" and request.authorization.password == "pw"
```

## Settings.py
- Allows a user to specify the preferred auth function.
- _Currently_ also includes the code that imports the function strings. In reality, this would be a separate step/file.

```python
import auth

authentication_module = "auth"
authentication_function = "basic_auth"

authenticator = getattr(auth, authentication_function)
```

## Decorators.py
- Defines `login_required` decorator that applies auth function to API view function

```python
from flask import g, request, Response
from settings import authenticator


def login_required(wrapped):
    def wrapper(*args, **kwargs):
        if authenticator():
            return wrapped(*args, **kwargs)
        
        return Response("Forbidden", 403)

    return wrapper
```

Thanks so much!

**Comment by jhtimmins** [comment]
@mik-laj I'm working on a scratchpad git repo in my personal account. https://github.com/jhtimmins/scratch-airflow-auth

Thus far, my focus has been the interface from the airflow user standpoint.

This design allows configuration at either the app level or the individual route. If configured at the app level, individual routes can be marked as as requiring user auth with either `@auth.login_required` or `@auth.login_required()` decorators.

- "App level" means they define an auth scheme in settings.py or environment variables. (edited) 
- "Path level" lets them set an auth scheme for a specific path by passing the auth validation method path to the decorator.
`@auth.login_required("auth.schemes.token_auth")`

Order of precendence: `Path level > env vars > settings.py`

I'm pleased with this interface for now, but I'd like to avoid the need for decorators at all. So I will circle back later on to see about setting up auth as middleware (similar to Django's design).

But my next step is nailing down how auth integrates with the existing user permission structure, so middleware will have to wait for now.

Do you have any thoughts or concerns?

**Comment by ad-m** [comment]
@mik-laj , have you considered introducing a "token exchange" flow (similiar to RFC8693) instead of adding a new middleware? Then you can effectively support many forms of authentication, where each subsequent form has completely different requirements. I notice that when the scheduler communicates with the REST API, one internal form of authentication will be required. Users expect at least one external form of authentication. In the case of using "token exchange", basic communication would be carried out using own Airflow instance access tokens only.

See also family of operation in AWS IAM `AssumeRole*`: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html

**Comment by mik-laj** [comment]
@ad-m  I do not want to introduce any requirements on the client API. If you want, you can use OAuth2, but you can also implement Kerberos-based or other fashionable protocol.

**Comment by jhtimmins** [comment]
@mik-laj have you had a chance to look at what I added in https://github.com/jhtimmins/scratch-airflow-auth/blob/master/auth/__init__.py? Really that code is about defining the interface for interacting with the authentication system. Two questions:
1. What do you think of the interface?
2. Should I implement any additional pieces of the auth system for this specific issue?

**Comment by mik-laj** [comment]
@jhtimmins Hi. I started cleaning up the authentication code for the experimental API and I like the concept that is implemented there. Auth backend selection is done with option`auth_backend` in `api` section. 
Each backend must have 2 defined methods:
 - `init_app(app: Flask)` - function invoked when creating a flash application, which allows you to add a new view.
 - `requires_authentication(fn: Callable)` -  decorator that allows you to implement arbitrary code before and after or instead of a view function

and can define one attribute:

 - `CLIENT_AUTH: : Optional[Union[Tuple[str, str], AuthBase]]` - attribute used by CLI in remote mode. Irrelevant in our case.

We currently have several backends implemented:
https://github.com/apache/airflow/tree/master/airflow/api/auth/backend
I am also working on one
https://github.com/apache/airflow/pull/9848/files

What do you think to use this code in the new API as well?

**Comment by jhtimmins** [comment]
Hi @mik-laj, if what we have is working, then it probably makes the most sense to do as you say and continue with the current architecture.

Do you think there is value in allowing different auth rules on a view-by-view basis? If so, parts of my design support this. 

It seems like Airflow would benefit from having a few prebuilt backends with common authentication schemes (Bearer Token, JWT, basic auth, etc.) What do you think about me implementing a few of those?

**Comment by mik-laj** [comment]
> Do you think there is value in allowing different auth rules on a view-by-view basis? If so, parts of my design support this.

Do you mean authorizations/permission control?  We have a separate issue about it: https://github.com/apache/airflow/issues/8112
I haven't thought about this topic in detail yet. This week, I'd like to do that. I will probably want to do everything as Ash suggested. 

> It seems like Airflow would benefit from having a few prebuilt backends with common authentication schemes (Bearer Token, JWT, basic auth, etc.) What do you think about me implementing a few of those?

It is beyond the scope of the current work. Personally, I will try to ensure integrations with CAS (e.g. [KeyCloak](https://www.keycloak.org/)) that will allow us to authenticate using various methods in a much more secure way e.g. it provides 2FA.  If we prepare [documentation](https://github.com/apache/airflow/issues/8123), each organization will be able to easily prepare an authentication backend in accordance with the requirements of its organization.  If you are willing to implement the implementation, I will be happy to help with the review.

**Comment by jhtimmins** [comment]
@mik-laj That makes sense. When you say "If you are willing to implement the implementation", are you referring to KeyCloak?

**Comment by mik-laj** [comment]
@jhtimmins I updated the comment to make it clearer. If you want to implement other authorization protocols, I will be happy to help with the review.

**Comment by jhtimmins** [comment]
@mik-laj Thanks for the update and offering to review. Since it seems like most of the focus thus far has been on using an auth proxy, I will work on simple auth mechanisms for users that don't have an auth proxy.

If this issue is just for an overall design, but not any of the actual implementations, is there anything else to do to satisfy the requirements of #8111? Since we're going with the existing auth model from the experimental API, it's not clear to me what there is that needs work for this.

**Comment by mik-laj** [comment]
@jhtimmins  The following authentication backends for the experimental API are available:
- airflow.api.auth.backend.default
- airflow.api.auth.backend.deny_all
- airflow.api.auth.backend.kerberos_auth
- airflow.providers.google.common.auth_backend.google_openid.requires_authentication

Following this, you can implement a new backend. 

If we want to have the credentials for a new API then we have to the new decorator for authorization for each API view.
This decorator should be based on `airflow.www.api.experimental.endpoints.requires_authentication` decorator, but should return error messages compatible with the new API.

It will look similar to the following
```python
def requires_authentication(function: T):
    """Decorator for functions that require authentication"""
    @wraps(function)
    def decorated(*args, **kwargs):
        response = current_app.api_auth.requires_authentication(function)(*args, **kwargs)
        if response.status_code == 403:
        	raise Unauthenticated("Unauthenticated")

    return cast(T, decorated)
```

**Comment by jhtimmins** [comment]
Great, thanks for that context @mik-laj.

**Comment by houqp** [comment]
@mik-laj @jhtimmins shouldn't we mark this issue as completed? what's left to be done here?

**Comment by mik-laj** [comment]
@houqp  I did not close the ticket because the topic of other authorization methods was discussed here, but I have already asked our colleague to create a separate ticket. On a separate ticket, we can discuss what else we want to do.
