### ISSUE TITLE
Improvement: CRUD Framework for API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8116]
**Description**

We need to build views that share common behavior. It would be nice if the code was not repeated. We need views that will only perform CRUD operations (Create, Update, List, Update, [GET])

More information about REST API:
https://github.com/apache/airflow/issues/8107

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by kaxil** [comment]
Hi @mik-laj is this issue still valid?

**Comment by mik-laj** [comment]
@kaxil It is nice-to-have. We can reduce duplicate code if we want, but since we had many different Independent contributors with different skill levels, we couldn't start with that.

**Comment by kaxil** [comment]
Cool, just wanted to check all the blockers for 2.0

**Comment by kaxil** [comment]
This has been done right @mik-laj .. Closing it -- Feel free to open if you think anything else needs to be done
