### ISSUE TITLE
HATEOS for API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8117]
**Description**

Links should be added to the objects to make it easier to use. I recommend https://flask-marshmallow.readthedocs.io/en/latest/

More information about REST API:
https://github.com/apache/airflow/issues/8107

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by auvipy** [comment]
https://flask-rest-jsonapi.readthedocs.io/en/latest/ could helpto add json-api 1.0/1.1 based HATEOS REST API

**Comment by kaxil** [comment]
With us generating clients, is this that useful anymore ?

**Comment by jscheffl** [comment]
This item seems to be stale for a while and nobody pushed demand. Closing therefore.
