### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8118]
**Description**

We should create endpoints that allow us to perform operations in Airflow

We need the following read-only endpoints - Database:

- [API Endpoints - Read-only - Connection ](https://github.com/apache/airflow/issues/8127)
- [API Endpoints - Read-only - DAG Model ](https://github.com/apache/airflow/issues/8128)
- [API Endpoints - Read-only - DAG Runs ](https://github.com/apache/airflow/issues/8129)
- [API Endpoints - Read-only - Import errors ](https://github.com/apache/airflow/issues/8130)
- [API Endpoints - Read-only - Pools ](https://github.com/apache/airflow/issues/8131)
- [API Endpoints - Read-only - Task Instance ](https://github.com/apache/airflow/issues/8132)
- [API Endpoints - Read-only - Variable ](https://github.com/apache/airflow/issues/8133)
- [API Endpoints - Read-only - XCOM ](https://github.com/apache/airflow/issues/8134)

We need to implement other endpoints: 

- [API Endpoint - Logs ](https://github.com/apache/airflow/issues/8135)
- [API Endpoint - Config ](https://github.com/apache/airflow/issues/8136)
- [API Endpoint - Dag source ](https://github.com/apache/airflow/issues/8137)
- [API Endpoint - Dags structure/Task ](https://github.com/apache/airflow/issues/8138)
- [API Endpoint - Links ](https://github.com/apache/airflow/issues/8140)
- [API Endpoint - Health - Spec and impelementataion](https://github.com/apache/airflow/issues/8144)

More information about the REST API is available:
[AIP-32 - Airflow REST API - High-level info](https://github.com/apache/airflow/issues/8107)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by prakshalj0512** [comment]
@mik-laj Hey, would it be possible to add an endpoint for getting the airflow version as well? Thanks.

**Comment by mik-laj** [comment]
We have /version endpoint: https://airflow.readthedocs.io/en/latest/stable-rest-api-ref.html#operation/get_version

**Comment by prakshalj0512** [comment]
Great. I was just looking at the list we have in this issue. Thanks for sharing that link...really helpful!
