### ISSUE TITLE
prevent using SQLite db with LocalExecutor, CeleryExecutor

### ISSUE THREAD

**Issue by neuromusic** [apache/airflow#812]
In hindsight, it was perhaps silly of me to try to run the LocalExecutor with a sqlite database, but it seemed to work.

until it didn't.

after many hours I started getting zombie process errors. setting up Postgres seemed to fix them, so I can only assume that they were due to concurrency issues w/ sqlite and the LocalExecutor.

expected behavior: 

```
$ airflow scheduler
airflow: error: cannot use sqlite with the LocalExecutor 
```

**Comment by mistercrunch** [comment]
Right, it should just fail early.
