### ISSUE TITLE
Migration guide from the experimental API to the REST API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8121]
**Description**

We should prepare a guide that will facilitate the migration from the experimental API to the API for Airflow 2.0.

More information about the docs for REST API is available:
[Docs for REST API](https://github.com/apache/airflow/issues/8143)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by ephraimbuddy** [comment]
I'm interested in this issue.

**Comment by mik-laj** [comment]
@ephraimbuddy  I assigned you to this ticket.
