### ISSUE TITLE
Guide about authorization and permission

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8122]
**Description**

We should prepare a guide that will describe how to manage permissions for the API. If there is a guide for Web UI, we can extend it. If it does not exist, then we must write from scratch.

More information about the docs for REST API is available:
[Docs for REST API](https://github.com/apache/airflow/issues/8143)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by pujaji** [comment]
I would love to take up this task! I am planning to about neatly document various authorization types like API keys, Basic Auth, HMAC (Hash-based message authorization code), OAuth 2.0.

**Comment by pujaji** [comment]
@mik-laj please let me know your toughts! if I am in the right direction, suggest any additions or improvizations

**Comment by mik-laj** [comment]
Hello

This document should describe the existing solution, so it should be created after or during implementation. We don't want to implement all authorization methods, but I hope that new methods will be added based on community requests.

Best regards,

**Comment by pujaji** [comment]
Got it Totally!                                                                                 
Thanks

**Comment by mik-laj** [comment]
According to recent discussions, we want to use the same permissions as Web UI, so we don't need it.
Here is docs: https://airflow.readthedocs.io/en/latest/security/access-control.html
