### ISSUE TITLE
Guide about  API authentication (including custom)

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8123]
**Description**

We should write a guide that describes how to add new ones or use the current authentication method.

More information about the docs for REST API is available:
[Docs for REST API](https://github.com/apache/airflow/issues/8143)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by OmairK** [comment]
If the REST API is built on Flask App builder we can take a look at [FAB Security](https://flask-appbuilder.readthedocs.io/en/latest/security.html), it would cover most of the authentication as well as the custom authentications too, what do you think ?

**Comment by mik-laj** [comment]
Here is the PR that is used to discuss implementation: https://github.com/apache/airflow/issues/8111
I have nothing against FAB Security if it can be combined with connexion.
