### ISSUE TITLE
API Endpoints - Read-only - Connection

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8127]
**Description**

Hello 

We need to create several endpoints that perform read-only operations on **Connection** . We need the following endpoints:

- GET /connections
- GET /connections/{connection_id}

For now, we focus only on read-only operations, but others will also be implemented as the next step.

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

Lots of love,

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by mik-laj** [comment]
@ephraimbuddy Are you working on this change? Can you comment on this ticket so that I can assign you?
https://github.com/apache/airflow/pull/9095

**Comment by ephraimbuddy** [comment]
Yes. I am working on it
