### ISSUE TITLE
API Endpoints - Read-only - DAG

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8128]
**Description**

Hello 

We need to create several endpoints that perform basic read-only operations on **DAG Model** . We need the following endpoints:

- GET /dags
- GET /dags/{dag_id}

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

Love,

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by bertosantamaria** [comment]
Hi @mik-laj and team. I'm very interested in working on this issue.  This is something that is vital for the Airflow installation we run on my team.   Is the next step to introduce a PR and work with the committers/community on any feedback/changes requested?

Also, I'm noticing there is not creation of DAGs mentioned here.  For the installation my team runs this functionality is also key.  Can creation of DAGs be added to the scope of this issue?

**Comment by mik-laj** [comment]
Hello @mik-laj 
We are currently discussing the specification in the PR. 
https://github.com/apache/airflow/pull/8721
Because of the fact that the specification has not been merged, we cannot start the implementation.  If you want the work to start then I invite you to review the specifications and when everything looks good, I am asking you to accept the PR.

Creating a DAG is not part of the specification, because there is no universal way to do this. There are different ways to create a DAG depending on the deployment model. Some users create DAG using files on S3, others using GCS, others using Docker images, others using git sync, etc.  For now, we want to focus on the common and universal feature that exists in Airflow and provide the API for it. Here is a document that describes the goals and non-goals of the project.
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-32%3A+Airflow+REST+API

**Comment by bertosantamaria** [comment]
Hi @mik-laj,
Congrats on getting https://github.com/apache/airflow/pull/8721 merged. Now that it has cleared I’d love to start helping with this issue. Can I proceed by following the spec or is there a different course to follow. 

Thanks.

**Comment by mik-laj** [comment]
Hey, I found a PR who is already starting to implement this ticket. Do you want to take it over?
https://github.com/apache/airflow/pull/9045

Would you not be interested in this ticket?
https://github.com/apache/airflow/issues/8140

**Comment by bertosantamaria** [comment]
@mik-laj Just confirming you are suggesting picking up where you left off on https://github.com/apache/airflow/pull/9045?  I'd be happy to work on that.  thanks

**Comment by mik-laj** [comment]
@bertosantamaria  I think that a better idea would be to take care of another ticket that has no assigned person. You can track the current tickets on the board. 
https://github.com/apache/airflow/projects/1
Column: "TODO - Priority tasks -  Non-assigned"

**Comment by bertosantamaria** [comment]
@mik-laj to be honest the change I'd like to implement is this one #9109. It seems this issue (8128) has been rescoped to implement read-only endpoints. Are there any objections to taking on #9109 instead?

**Comment by bertosantamaria** [comment]
Ah, I see.  Ok, sounds great.  thanks!

**Comment by mik-laj** [comment]
@bertosantamaria How do you do? Do you need any help? A lot is going on in the project. If you need some inspiration then you can look at merged or unmerged PRs.
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aclosed
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aopen
I hope this will help you.

**Comment by bertosantamaria** [comment]
thanks @mik-laj.  I'll take those PRs as inspiration and have something to show for this in the next d few days.  regards.
