### ISSUE TITLE
API Endpoints - Read-only - DAG Runs

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8129]
Hello 

We need to create several endpoints that perform basic read-only operations on **DAG Runs** . We need the following endpoints:

- GET /dags/{dag_id}/dagRuns
- GET /dags/{dag_id}/dagRuns/{dag_run_id}

For now, we focus only on read-only operations, but others will also be implemented as the next step.

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by dlamblin** [comment]
I see the update in PATCH, but I don't see a POST for create… is there a reason for this not be included? Or am I missing another way to create a dag run.

**Comment by mik-laj** [comment]
I should be included. I updated the ticket.

**Comment by davinchia** [comment]
+1. we currently use the experimental api to start dag runs, and have to jump through lots of hoops to get the status of a current dag run. allowing someone to do this easily will be awesome

**Comment by rtstock** [comment]
+1 would also love to see historical output (eg results of admin/airflow/tree?root=&dag_id=) in json as well

**Comment by mik-laj** [comment]
@davinchia or @rtstock Hi. We have already started to implement. Do you still want to work on this ticket? For now, we focus only on read-only operations, but others will also be implemented as the next step.

Here is dag_run_endpoint.py file. You should start working here.
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/dag_run_endpoint.py

You can be inspired by this change: https://github.com/apache/airflow/pull/9045

**Comment by ephraimbuddy** [comment]
Hi @mik-laj , I will like to work on this
