### ISSUE TITLE
API Endpoints - Read-only - Import errors

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8130]
**Description**
Hello 

We need to create several endpoints that perform basic read-only operations on **Import error** . We need the following endpoints:

- GET /importErrors
- GET /importErrors/{import_error_id}

For now, we focus only on read-only operations, but others will also be implemented as the next step.

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by OmairK** [comment]
Hi @mik-laj I would like to work on this.

**Comment by mik-laj** [comment]
@OmairK I assigned you to the ticket. I look forward to your contributions.
