### ISSUE TITLE
API Endpoints - Read-only - Pools

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8131]
**Description**
Hello 

We need to create several endpoints that perform basic read-only operations on **Pools** . We need the following endpoints:

- GET /pools
- GET /pools/{pool_name}

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by mik-laj** [comment]
@OmairK Are you working on this change? Can you comment on this ticket so that I can assign you?
https://github.com/apache/airflow/pull/9097

**Comment by OmairK** [comment]
Yes I am working on it can you please assign it to me, thanks.
