### ISSUE TITLE
API Endpoints - Read-only - Task Instance

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8132]
**Description**
Hello 

We need to create several endpoints that perform basic read-only operations on **Task instance** . We need the following endpoints:

- GET /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances
- GET /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}

For now, we focus only on read-only operations, but others will also be implemented as the next step.

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by GMarkfjard** [comment]
@mik-laj I'd love to get my hands dirty with this!

**Comment by mik-laj** [comment]
@GMarkfjard  Fantastic. I look forward to your contribution with a warm heart. 🐈

**Comment by mik-laj** [comment]
@GMarkfjard How do you do? Do you need any help? A lot is going on in the project. If you need some inspiration then you can look at merged or unmerged PRs.
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aclosed
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aopen
I hope this will help you.

**Comment by mik-laj** [comment]
@@GMarkfjard  Do you need any information? Is something blocking you?  If you don't have time, maybe you would like another contributor to take care of this ticket? This is the last read-only endpoint that I do not know the status of.

**Comment by GMarkfjard** [comment]
@mik-laj Sorry, been AWOL for a few days. I should just have a few tests left and then I'm done. ETA Monday

**Comment by mik-laj** [comment]
@GMarkfjard Do you need help? This month I would like to finish all read-only operations. We only have a week of time left.  Do you have any problems? We managed to solve many problems while working on other end points, so if we get to know your change better, we will be able to help you. Creating a draft of your change would be helpful to us.

**Comment by pcandoalmeida** [comment]
Hi everyone 👋🏼 is this issue still open for work? I can see the `Hacktoberfest` label has been added and would love to help if no one is working on this at the moment?

**Comment by OmairK** [comment]
> Hi everyone 👋🏼 is this issue still open? I can see the `Hacktoberfest` label has been added and would love to help if no one is working on this at the moment?

@pcandoalmeida there is already a draft PR in review for this issue #9597.

**Comment by pcandoalmeida** [comment]
How did I miss that! Thanks @OmairK!
