### ISSUE TITLE
API Endpoints - Read-only - Variable

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8133]
**Description**

Hello 

We need to create several endpoints that perform basic read-only operations on **Variable** . We need the following endpoints:

- GET /variables
- GET /variables/{variable_key}

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**
N/A

**Related Issues**
N/A

**Comment by mik-laj** [comment]
@houqp Do you want to work on it?
We are ready. You can start working from this file
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/variable_endpoint.py

For now, we focus only on read-only operations, but others will also be implemented as the next step.

**Comment by houqp** [comment]
@mik-laj yes, I can take a stab at it this week. do you mind if I implement write endpoints as well or do you prefer me to only fill out the read endpoints?

**Comment by mik-laj** [comment]
A single PR can close multiple tickets. I divided the variable endpoints because I want to involve many new people in these tasks. When the ticket is small it is easier to finish it.
Here is a ticket about CRUD operation for Variable: 
https://github.com/apache/airflow/issues/9115
Does this sound good to you?

**Comment by houqp** [comment]
@mik-laj looks good to me!
