### ISSUE TITLE
API Endpoint - Logs

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8135]
**Description**
Hello,

We need to prepare an endpoint that will read the logs for the task. Logs are already available in Web UI, so abstractions should be created and used in both places. The code responsible for reading the log in the Web UI is in the file [`airflow/www/views.py`](https://github.com/apache/airflow/blob/master/airflow/www/views.py) (method `get_logs_with_metadata`)
The token is metadata data serialized to JSON and encoded with base64. This prevents user from building clients based on a specific metadata structure. We cannot guarantee their permanent structure because it use external plugins.

- GET /dags/{dag_id}/taskInstances/{task_id}/{execution_date}/logs/{task_try_number}

More details about API Endpoints: 
https://github.com/apache/airflow/issues/8118

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by mik-laj** [comment]
@kaxil Do you want to help with this ticket?

**Comment by mik-laj** [comment]
@kaxil   Hi. We have already started to implement. Do you still want to work on this ticket?

Here is log_endpoint.py file. You should start working here.
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/log_endpoint.py

**Comment by kaxil** [comment]
Yeah sorry I won't be able to work on it for at least a month or two, so please feel free to reassign

**Comment by ephraimbuddy** [comment]
Hi @mik-laj, can I start working on this?

**Comment by mik-laj** [comment]
@ephraimbuddy Fantastic. I've assigned you to this ticket.

**Comment by mik-laj** [comment]
@ephraimbuddy  Do you need any help? Endpoints that enable data reading are a priority for me.

**Comment by ephraimbuddy** [comment]
Oh, I thought I had been working on this via the eventlogs endpoint. I didn't know this is a different endpoint. Thanks, I will start working on it right away

**Comment by mik-laj** [comment]
@ephraimbuddy EventLog is a log of operations performed in Web UI.
Logs are related to Task Instance. More info: https://airflow.readthedocs.io/en/latest/howto/write-logs.html?highlight=logging
This is one of the most interesting endpoints
