### ISSUE TITLE
API Endpoint - Config

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8136]
**Description**

Hello,

We need an endpoint that allows us to **read** the current Airflow configuration.

- GET /config

More details about API Endpoints:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by vbmade2000** [comment]
This looks good first one.

**Comment by mik-laj** [comment]
We haven't started implementation yet. We're working on a specification, but next week everything will start.  Are you already on our Slack? We have #sig-api channel. To join, please use this link: https://apache-airflow-slack.herokuapp.com/

**Comment by vbmade2000** [comment]
> We haven't started implementation yet. We're working on a specification, but next week everything will start. Are you already on our Slack? We have #sig-api channel. To join, please use this link: https://apache-airflow-slack.herokuapp.com/

Sure. Just joined channel.

**Comment by vbmade2000** [comment]
Will it fall under /api/v1 only or it is a common one between all the api versions ?

**Comment by mik-laj** [comment]
Hi. We have already started to implement.  Here is config_endpoint.py file. You should start working here.  
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/config_endpoint.py

**Comment by mik-laj** [comment]
@vbmade2000  How do you do? Do you need any help? A lot is going on in the project. If you feel the inspiration then you can look at merged or unmerged PRs.
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aclosed
https://github.com/apache/airflow/pulls?q=is%3Apr+label%3Aarea%3AAPI+is%3Aopen
I hope this will help you.

**Comment by mik-laj** [comment]
@vbmade2000 Do you need help? I will gladly help you if you create your PR.

**Comment by zikun** [comment]
I would like to pick it up if there is no update

**Comment by mik-laj** [comment]
@zikun I assigned you to this ticket?

**Comment by vbmade2000** [comment]
> @vbmade2000 Do you need help? I will gladly help you if you create your PR.

Hey Thanks. Apology. I was extreely busy and couldn't check Github. I finished actual code in couple of days with some UTs but documentation (and may be something else ) is remaining. Thanks @zikun you picked up this.
