### ISSUE TITLE
API Endpoint - Dag source

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8137]
**Description**

Hello, 

We need an endpoint that allows you to read the DAG File source code. 
When ``store_dag_code`` = True, then the code should be read from the database.
When ``store_dag_code`` = False, then the code should be read from the file.

- `GET /dagSources/{file_token}`

More details about API Endpoints:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by TobKed** [comment]
Looks interesting. I will try to do this :)

**Comment by mik-laj** [comment]
@TobKed Hi. We have already started to implement. Do you still want to work on this ticket? 

Here is config_endpoint.py file. You should start working here.  https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/config_endpoint.py

**Comment by TobKed** [comment]
@mik-laj yes, I will start working on this

**Comment by mik-laj** [comment]
@TobKed Do you need any help? If you need help, feel free to write or call.

**Comment by TobKed** [comment]
thanks @mik-laj , indeed I need some help , I will contact you on slack.
