### ISSUE TITLE
API Endpoint - Dags details/Task

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8138]
**Description**

We need to have endpoints that allow us to read information about workflow - DAG, Task. Endpoints should properly support serialization.

- GET /dags/{dag_id}/details
- GET /dags/{dag_id}/tasks
- GET /dags/{dag_id}/tasks/{task_id}

More details about API Endpoints:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by vbmade2000** [comment]
@mik-laj I want to take take this task.

**Comment by mik-laj** [comment]
@vbmade2000 This task looks simple but requires integration with DAG Serialization and many test cases. What do you think about [API Endpoint - Config](https://github.com/apache/airflow/issues/8136)?

**Comment by zikun** [comment]
Hi @mik-laj This looks more challenging than other endpoints. Can I take this one?

**Comment by mik-laj** [comment]
Hello. 
Today during the morning standup I was able to get Tomek involved in this task. Unfortunately, he didn't write a comment under the ticket, I haven't assigned him to the task yet. Today he worked hard all day to make these endpoints. Sorry for the confusion. 
Best regards
Kamill

**Comment by mik-laj** [comment]
We currently have a lot of changes that are underway. I invite you to review them. Any review is very helpful.
https://github.com/apache/airflow/pulls?q=is%3Apr+is%3Aopen+label%3Aarea%3AAPI

**Comment by zikun** [comment]
No worries.
Thanks. I'll take a look. Meanwhile I'd like to wait for some of the blocked tickets to get my hands dirty
