### ISSUE TITLE
API Endpoint - XCOM/Variables lookup

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8142]
**Description**

We need endpoints that allow you to retrieve an element based on the object key - `lookup`.

- GET /variables/lookup

More details about API Endpoints:
https://github.com/apache/airflow/issues/8118

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by ctivanovich** [comment]
Hello, this portion would essentially be exposing access to the XComs/Variables data in the database via API client request, either to an external, authenticated application, or via the CLI? I have taken a look at the API-32 page, and I gather that there will also be an API server, meaning someone should be able to send a request along with a credential to get this information in e.g. JSON?

**Comment by mik-laj** [comment]
Yes. We want to enable the integration of various systems with Airflow.

**Comment by mik-laj** [comment]
We removed these endpoints.  Now they are part of ticket https://github.com/apache/airflow/issues/8134 and 
https://github.com/apache/airflow/issues/8133
