### ISSUE TITLE
Docs for REST API

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8143]
**Description**

We should prepare documentation for the REST API:

- [Guide about API authentication (including custom)](https://github.com/apache/airflow/issues/8123)
- [Guide about authorization and permission](https://github.com/apache/airflow/issues/8122)
- [Migration guide from the experimental API to the REST API](https://github.com/apache/airflow/issues/8121)
- [Guide "How to use REST API"](https://github.com/apache/airflow/issues/8120)
- [REST API Reference](https://github.com/apache/airflow/issues/8119)

More information about the REST API is available:
[AIP-32 - Airflow REST API - High-level info](https://github.com/apache/airflow/issues/8107)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by Quadrisheriff** [comment]
Hi, I am a technical writer. Can I help on this?
