### ISSUE TITLE
trigger_rule=one_failed doesn't lead to proper skipped statuses

### ISSUE THREAD

**Issue by mistercrunch** [apache/airflow#815]

**Comment by abridgett** [comment]
I'm more than happy to help diagnose and fix this if possible (probably not capable of something too complex though).  Anything in particular I could look at (logs messages, could send the DAG through if that helps).

**Comment by abridgett** [comment]
If I mark the task which is set "trigger_rule=one_failed" as success, the DAG is marked as success.   If my understanding is correct, we need a bit more logic in airflow/models.py:are_dependendencies_met (when flag_upstream_failed is True) to set the status to SKIPPED or FAILED for the other cases, not just when trigger_rule is TR.ALL_SUCCESS.
