### ISSUE TITLE
Add section about process of updating Airflow

### ISSUE THREAD

**Issue by vastep** [apache/airflow#8158]
**Description**

Hello Community.
Official docs does not contain any info about update procedure.
There are two pages about changes but they are not such useful as expected:
https://airflow.apache.org/docs/stable/changelog.html
https://github.com/apache/airflow/blob/master/UPDATING.md

**Use case / motivation**
It would be good to have a recommendation/description for process,
especially for MINOR and PATCH versions, e.g.
- make dump for all, restore and search for bugs OR
- just do `pip install --upgrade` and then `airflow upgradedb` OR
- install new version from scratch and deploy DAGs freshly OR
- any suggestions?

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/issues/10089

**Comment by eladkal** [comment]
Docs "Upgrading Airflow to a newer version" available in:
https://airflow.apache.org/docs/apache-airflow/stable/installation/upgrading.html?highlight=upgrade#upgrading-airflow-to-a-newer-version
