### ISSUE TITLE
Google `Credentials` object has not attribute `with_subject`

### ISSUE THREAD

**Issue by iamshwin** [apache/airflow#8163]
**Apache Airflow version**:
master

**What happened**:
When`delegate_to` is supplied and no `key_path` or `keyfile_dict` is supplied (i.e. `google.auth.default()` is called) the `Credentials` object has no attribute `with_subject`.

This is called in `get_credentials_and_project_id` in https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/utils/credentials_provider.py

`AttributeError: 'Credentials' object has no attribute 'with_subject'`

**What you expected to happen**:
Correct authentication, or raise an Exception that you shouldn't be supplying a `delegate_to` when you haven't supplied a `key_path` or `keyfile_dict`.

**How to reproduce it**:
Supply a `delegate_to` argument in the Operator, but do not supply a `key_path` or `keyfile_dict`.

**Comment by mik-laj** [comment]
I'm afraid this problem may be a little more complex. 
``google.auth.default()`` supports 4 methods of authentication methods in following order:
*  the credentials from the GOOGLE_APPLICATION_CREDENTIALS environment  variable.
*  the credentials from the Cloud SDK
*  Google App Engine App Identity credentials,
* the credentials and project ID from the GCE Metadata Service

Some methods support delegate_to correctly, and others do not support this.  Can you tell me how you are authorized to limit the scope of the problem?

**Comment by iamshwin** [comment]
We are running Airflow on Cloud Composer (GCP's managed service). It looks like it is using the credentials from the Cloud SDK.

**Comment by iamshwin** [comment]
Ok, so that does that mean that any time someone specifies a `delegate_to` in any Operator in Cloud Composer, the authentication will fail? Should we raise an explicit exception when people try and do that? It would make for a much better user experience.

**Comment by mik-laj** [comment]
Yes. We should do it. Can you deal with this? I think that if someone passes the delegate_to parameter and the current credentials object does not have the with_subject attribute, an exception should be raised: "The current authentication method does not support account impersonate". 
The corresponding code is here:
https://github.com/apache/airflow/blob/beef6c2/airflow/providers/google/cloud/utils/credentials_provider.py#L243-L244
Tests: https://github.com/apache/airflow/blob/8a02402/tests/providers/google/common/hooks/test_base_google.py#L337

Contributor guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
Development environment: https://github.com/apache/airflow/blob/master/BREEZE.rst

The community is waiting for your contribution 🐈

**Comment by iamshwin** [comment]
Yes, I'll open a PR.

**Comment by mik-laj** [comment]
I'm glad. Thanks in advance. 😻 I am waiting.
