### ISSUE TITLE
Extend elastic DAG with a binary tree, grid, star

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8187]
**Description**

We have ["elastic DAG"](https://github.com/apache/airflow/blob/master/scripts/perf/dags/elastic_dag.py#L77) which we use in various performance tests. It allows you to generate any DAG using environment variables.
An example test that uses such a DAG looks like this
```python
        with mock.patch.dict("os.environ", {
            "PERF_DAGS_COUNT": str(dag_count),
            "PERF_TASKS_COUNT": str(task_count),
            "PERF_START_AGO": start_ago,
            "PERF_SCHEDULE_INTERVAL": schedule_interval,
            "PERF_SHAPE": shape,
        }), conf_vars({
            ('scheduler', 'use_job_schedule'): 'True',
        }):
            dagbag = DagBag(dag_folder=ELASTIC_DAG_FILE, include_examples=False)
            with assert_queries_count(expected_query_count):
                processor = DagFileProcessor([], mock.MagicMock())
                processor._process_dags(dagbag.dags.values())
```
Source: 
https://github.com/apache/airflow/blob/6bd2e59/tests/jobs/test_scheduler_job.py#L1175

This DAG File allows you to generate DAGs that contain all the tasks connected in a linear manner or have no connections.

It would be useful to add more complex DAGs, especially binary trees or/and grids or/and stars. This will allow us to test more complex cases more easily.

![](https://study.com/cimages/multimages/16/0e0646ba-30e5-40d9-b45c-a138f038f05b_full_complete_perfect.png)

**Use case / motivation**

N/A

**Related Issues**

N/A

**Comment by alexandrecaze** [comment]
I am interested in taking this issue @mik-laj

**Comment by alexandrecaze** [comment]
@mik-laj What do you mean by grids and stars shaped DAGs ?

**Comment by mik-laj** [comment]
DAGs that look like the picture
![Screenshot 2020-04-13 at 20 15 01](https://user-images.githubusercontent.com/12058428/79146961-7ac44800-7dc3-11ea-8622-6c28f58a0bd2.png)

**Comment by alexandrecaze** [comment]
Would we imagine a second layer for the star ?

![Capture d’écran 2020-04-13 à 20 21 59](https://user-images.githubusercontent.com/11877365/79147602-777d8c00-7dc4-11ea-9749-cecc1485fe55.png)

**Comment by mik-laj** [comment]
All children of task 1. This is needed to check if the tasks will be performed at the second iteration of the loop.   Grid is needed to perform a stress test and at the same time not get lost in all dependencies.  Binary tree will allow us to check cases more real to real situations.
