### ISSUE TITLE
exists other portable database more simple?

### ISSUE THREAD

**Issue by ByteCompiler** [apache/airflow#8188]
cassandra is more hard settup.

i am looking for one database portable(java,multi os) than i can run in only one click like mysql and than has one workbench for edit import and export datas
Please delete these comment blocks before submitting the issue.

**Comment by mik-laj** [comment]
This does not look like a description of the problem or as a feature request Github Issue is not for asking questions.

Please read this guide
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
