### ISSUE TITLE
Guide for Apache Hive operators 

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8191]
**Description**

Hello,

A guide that describes how to use Apache Druid software operators would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guides for Apache operators:
Apache Cassandra: https://github.com/apache/airflow/issues/8189
Apache Druid: https://github.com/apache/airflow/issues/8199
Apache Hive: https://github.com/apache/airflow/issues/8191
Apache Livy: https://github.com/apache/airflow/issues/8192
Apache Pig: https://github.com/apache/airflow/issues/8193
Apache Pinot: https://github.com/apache/airflow/issues/8194
Apache Spark: https://github.com/apache/airflow/issues/8195
Apache Sqoop: https://github.com/apache/airflow/issues/8196
Hadoop Distributed File System (HDFS): https://github.com/apache/airflow/issues/8197
WebHDFS: https://github.com/apache/airflow/issues/8198

**Comment by iadi7ya** [comment]
Hi @mik-laj, I would like to work on this issue. It would be great if you could assign this to me?

**Comment by potiuk** [comment]
assigned :)
