### ISSUE TITLE
Guide for Apache Pinot operators 

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8194]
**Description**

Hello,

A guide that describes how to use Apache Pinot software operators would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guides for Apache operators:
Apache Cassandra: https://github.com/apache/airflow/issues/8189
Apache Druid: https://github.com/apache/airflow/issues/8199
Apache Hive: https://github.com/apache/airflow/issues/8191
Apache Livy: https://github.com/apache/airflow/issues/8192
Apache Pig: https://github.com/apache/airflow/issues/8193
Apache Pinot: https://github.com/apache/airflow/issues/8194
Apache Spark: https://github.com/apache/airflow/issues/8195
Apache Sqoop: https://github.com/apache/airflow/issues/8196
Hadoop Distributed File System (HDFS): https://github.com/apache/airflow/issues/8197
WebHDFS: https://github.com/apache/airflow/issues/8198

**Comment by sharon2719** [comment]
Hello kindly assign me this project.

**Comment by eladkal** [comment]
> Add Guide for Apache Pinot #18930

Yes but still we can explain how to use with with PythonOperators using example dags. Some of the work was already done on https://github.com/apache/airflow/pull/18930 so you can reuse what is needed.

**Comment by Melodie97** [comment]
> > Add Guide for Apache Pinot #18930
> 
> Yes but still we can explain how to use with with PythonOperators using example dags. Some of the work was already done on #18930 so you can reuse what is needed.

Hi @eladkal , the example  dags done on that pull request seem to have some errors, the arguments doesn't match that of the classes created in pinot.py
