### ISSUE TITLE
Guide for WebHDFS operators 

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8198]
**Description**

Hello,

A guide that describes how to use WebHDFS software operators would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guides for Apache operators:
Apache Cassandra: https://github.com/apache/airflow/issues/8189
Apache Druid: https://github.com/apache/airflow/issues/8199
Apache Hive: https://github.com/apache/airflow/issues/8191
Apache Livy: https://github.com/apache/airflow/issues/8192
Apache Pig: https://github.com/apache/airflow/issues/8193
Apache Pinot: https://github.com/apache/airflow/issues/8194
Apache Spark: https://github.com/apache/airflow/issues/8195
Apache Sqoop: https://github.com/apache/airflow/issues/8196
Hadoop Distributed File System (HDFS): https://github.com/apache/airflow/issues/8197
WebHDFS: https://github.com/apache/airflow/issues/8198

**Comment by Melodie97** [comment]
I would like to work on this issue

**Comment by potiuk** [comment]
Feel free :)

**Comment by Melodie97** [comment]
Hi @potiuk , It seems there is already an operators guide for Apache Hadoop HDFS Operators in the docs
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-apache-hdfs/latest/operators.html

**Comment by potiuk** [comment]
> Hi @potiuk , It seems there is already an operators guide for Apache Hadoop HDFS Operators in the docs http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-apache-hdfs/latest/operators.html

Yeah. But `WebHDFS` are a different set of operators/hooks.?

**Comment by Melodie97** [comment]
ok

**Comment by eladkal** [comment]
Solved in https://github.com/apache/airflow/pull/21393
