### ISSUE TITLE
Create guide for BigQuery operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8200]
**Description**

Hello,

A guide that describes how to use BigQuery service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Best regards,
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

**Comment by alexandraabbas** [comment]
@mik-laj Please, assign the ticket to me, thanks!

**Comment by alexandraabbas** [comment]
@mik-laj This PR can be linked to this issue: https://github.com/apache/airflow/pull/8276.
