### ISSUE TITLE
Create guide for Dataproc operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8203]
**Description**

Hello,

A guide that describes how to use Dataproc service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Best regards,

Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

**Comment by joppevos** [comment]
Happy to pick this up. Worked with the service a bit before.

**Comment by mik-laj** [comment]
@joppevos  I assigned you to this task.

**Comment by eladkal** [comment]
solved in https://github.com/apache/airflow/pull/9037
