### ISSUE TITLE
Create guide for Datastore operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8204]
**Description**

Hello,

A guide that describes how to use Datastore service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

**Comment by psyduck1203** [comment]
hey im interested in this issue solving but im a first timer !!

**Comment by mik-laj** [comment]
@psyduck1203 I don't know if this ticket has already been resolved. Recently, we have made a big contribution to this integration.

@turbaszek Is there any missing documentation?

**Comment by turbaszek** [comment]
We miss docs for get/delete operation operators. But I'm not even sure if we need those operators tbh
