### ISSUE TITLE
Create guide for Cloud Key Management Service (KMS) operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8205]
**Description**

Hello,

A guide that describes how to use Datastore service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Best regards,

Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

**Comment by tanjinP** [comment]
I can take this on - this is a service I've worked heavily in.

**Comment by mik-laj** [comment]
Hi. I've assigned you to this ticket.

**Comment by tanjinP** [comment]
> **Description**
> 
> Hello,
> 
> A guide that describes how to use Datastore service operators would be useful.
> 
> We have an example DAG for this service, so the guide should not be a big challenge.
> 
> If anyone is interested in this task, I am willing to provide all the necessary tips and information.
> 
> Other guides are available:
> https://airflow.readthedocs.io/en/latest/howto/operator/index.html
> 
> All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory.
> 
> Best regards,
> 
> Kamil
> 
> **Use case / motivation**
> 
> N/A
> 
> **Related Issues**
> 
> Missing guide for GCP: #8209

Hey @mik-laj - just have a few concerns with this issue:
1. The description says `Datastore` - I'm assuming this is a copy/paste error as the Datastore guide issue is here #8204 
1. Where are the Cloud KMS operators? I could only find the [Hook](https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/hooks/kms.py). Do Hooks have a different way of creating guides? If not, where would they be located? I couldn't find any particular examples of this scenario.

**Comment by mik-laj** [comment]
I checked again and we actually don't have operators. 
A list of operators and hooks is available.:
https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#id15
