### ISSUE TITLE
Create guide for Kubernetes Engine operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8206]
**Description**

Hello,

A guide that describes how to use Kubernetes Engine service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Best regards,

Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

**Comment by rcjsuen** [comment]
> A guide that describes how to use Kubernetes Engine service operators would be useful.

@mik-laj What is a "Kubernetes Engine service operator"?

**Comment by mik-laj** [comment]
We have two types of operators for GCP:
* Service operators: perform operations on Google services.
* Transfer operators: copies data from/to Google services.

List of operators, hooks and guides for GCP: https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#gcp-google-cloud-platform

Google Kubernetes Engine (GKE) provides a managed environment for deploying, managing, and scaling your containerized applications using Google infrastructure.
More informaation: https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview

List of all GKE operators: https://airflow.readthedocs.io/en/latest/_api/airflow/providers/google/cloud/operators/kubernetes_engine/index.html#module-airflow.providers.google.cloud.operators.kubernetes_engine

**Comment by tanjinP** [comment]
I can take this on - this is a service I've worked heavily in.

**Comment by mik-laj** [comment]
Hi. I've assigned you to this ticket.

**Comment by tanjinP** [comment]
@mik-laj should this issue be closed?
