### ISSUE TITLE
Missing guides for GCP operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8209]
**Description**

Hello, 

Some GCP services do not have guides. It would be nice if we created the missing guides. 

We have an example DAGs for GCP services, so the guide should not be a big challenge.

If anyone is interested in this, I am willing to provide all the necessary tips and information.

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Other guides are [available](https://airflow.readthedocs.io/en/latest/howto/operator/index.html)

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

New users want to learn how to use an operator should have documentation. The most important thing in this guide is to include an example of the use of operators.

**Related Issues**

BigQuery: https://github.com/apache/airflow/issues/8200
Cloud Data Loss Prevention (DLP): https://github.com/apache/airflow/issues/8201
Dataflow: https://github.com/apache/airflow/issues/8202
Dataproc: https://github.com/apache/airflow/issues/8203
Datastore: https://github.com/apache/airflow/issues/8204
Cloud Key Management Service (KMS): https://github.com/apache/airflow/issues/8205
Kubernetes Engine: https://github.com/apache/airflow/issues/8206
Machine Learning Engine: https://github.com/apache/airflow/issues/8207
Cloud Tasks: https://github.com/apache/airflow/issues/8208

**Comment by matheusbsilva** [comment]
I would like to help on this issue, but I have some questions first.
- Can you send me an example of a guide? The link you provided is [broken](https://airflow.readthedocs.io/en/latest/howto/operator/index.htm)
- Which GCP guides are missing? I see you linked related issues and some of them are solved I would link to know which operators don't have a guide yet.

**Comment by mik-laj** [comment]
Correct link:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html
Here is a full list of Google services, along with information on whether operators and a tutorial are available.
https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#google
