### ISSUE TITLE
UI time zone not used in Gantt charts tooltips

### ISSUE THREAD

**Issue by olchas** [apache/airflow#8210]
**Apache Airflow version**: v2.0.0.dev0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): -

**Environment**: Docker 

- **Cloud provider or hardware configuration**: -
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): 
Linux 6dac905dd519 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux
- **Install tools**: Airflow Breeze (image: apache/airflow:master-python3.6-ci)
- **Others**: -
**What happened**:

Gantt charts seem to always use UTC for displaying task start/end dates, but use local time for time axis, regardless of the time zone set in UI (see screens below: my local time zone is CEST).
<img width="815" alt="Zrzut ekranu 2020-04-8 o 09 18 50" src="https://user-images.githubusercontent.com/34898234/78764706-3c73f680-7987-11ea-925b-e394ac329298.png">
<img width="840" alt="Zrzut ekranu 2020-04-8 o 09 17 17" src="https://user-images.githubusercontent.com/34898234/78764752-4eee3000-7987-11ea-957b-338376d1bf41.png">
<img width="925" alt="Zrzut ekranu 2020-04-8 o 10 58 09" src="https://user-images.githubusercontent.com/34898234/78765233-01be8e00-7988-11ea-8215-9179102cb390.png">

**What you expected to happen**:

Time zone of the time axis and task start/end dates should be the same - probably the time zone specified in the UI should be used.

**How to reproduce it**:

Simply go to Gantt chart of any Dag Run and try changing the time zone in the UI to see that neither the time axis nor task start/end dates reflect the change.

You can also change the local time on your workstation and refresh the page with Gantt chart to see that time axis changed to reflect the new time zone.

**Anything else we need to know**: -

**Comment by mik-laj** [comment]
@ashb Can you look at it

**Comment by ashb** [comment]
Yup, valid bug, missed the tooltips on that in my timezone revamp. I will try and make them use the same tooltip code as graph and tree view (which now share the same JS)
