### ISSUE TITLE
Add Option for BashOperator to Set State to SKIPPED

### ISSUE THREAD

**Issue by xyu** [apache/airflow#8245]
Allow BashOperator Tasks to Skip instead of Fail

With the BashOperator sometimes I want to signal that the task should soft fail / return in a skipped state for itself and downstream tasks without having to hard fail it. I think it would be a good idea to add an option on the operator so that when the exit code matches what is given instead of failing task we raise a skip exception.

**Related Issues**

I've created #8244 as an example / idea of what I think could be done to implement this feature.

**Comment by ashb** [comment]
Closed by https://github.com/apache/airflow/pull/13421 but exit code will be changed in https://github.com/apache/airflow/pull/14963
