### ISSUE TITLE
Docs: LatestOnlyOperator documentation is misleading

### ISSUE THREAD

**Issue by ynouri** [apache/airflow#8246]
I'm relatively new to Airflow and I started experimenting with LatestOnlyOperator for the needs of my team.

The operator itself seems to work fine but [the documentation ](https://airflow.apache.org/docs/stable/concepts.html#latest-run-only)was slightly confusing.
* The code example is not in line with the DAG tree view screenshot
* "downstream" and "upstream" concepts seem to be mistakenly swapped in the explanation (even though they are very clearly defined [a few paragraphs above](https://airflow.apache.org/docs/stable/concepts.html#relations-between-tasks))

**Comment by boittega** [comment]
The documentation has being updated fixing the confusions, the code in the documentation is also out of date, the new dag has the downstream and upstream fixed.
The PR updating the documentation:
https://github.com/apache/airflow/pull/5970
https://github.com/apache/airflow/pull/7729

I've updated the image that was showing the structure upside down.
https://github.com/apache/airflow/pull/8268
