### ISSUE TITLE
DagCode is never updated

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#8249]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:
docker-compose, LocalExecutor

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
After making a change to my DAG, the values in the DagCode table are never updated, and the Code view always displays the code from the first time it was loaded. I do see my changes in the webserver in all other views (tree view, graph view, etc).

**What you expected to happen**:
I expect to see the currently used code in the Code view at any point in time.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
Hmm are you sure about this ?

**Comment by kaxil** [comment]
Basically there might be a lag of 120 seconds because it is hard-coded. I will change it to make it configurable but can you double-check and see that the code is updated after 120 seconds.

**Comment by BasPH** [comment]
Will double check

**Comment by BasPH** [comment]
Checked one more time, but no luck. Can you reproduce this?

My starting situation: I have my DAG, code is shown in the Code view, everything is consistent in the UI.
1. Make change to the DAG
2. Hit refresh in UI -> all is updated, also the serialized dag
3. Waited 5 minutes, but no updated code in DagCode table yet

**Comment by kaxil** [comment]
Just want to confirm before I try to reproduce, which UI did you use? Flask-admin or FAB?

**Comment by BasPH** [comment]
RBAC

**Comment by kaxil** [comment]
Thanks, I will try to reproduce

**Comment by BasPH** [comment]
@kaxil here's the docker-compose file + DAG I used for this: https://github.com/BasPH/airflow-tests

- Bring up with `docker-compose up`
- login with user `airflow`, pass `airflow`
- make change to hello_world.py (it's mounted in the scheduler container)
- wait

**Comment by kaxil** [comment]
Yes, I can reproduce this. Will fix it today

**Comment by kaxil** [comment]
Actually it seems to be working for me now. Not sure what happened previously. 

I also had added the code for this:

For 1.10.10 tag:

https://github.com/apache/airflow/blob/96697180d79bfc90f6964a8e99f9dd441789177c/tests/models/test_dagcode.py#L142-L176

**Comment by kaxil** [comment]
I added a few more import lines and they seem to appear

**Comment by BasPH** [comment]
That's odd, could you describe your setup? I just tested again with Airflow 1.10.10, just starting webserver & scheduler from command line, no Docker, but still no Dag Code refresh, while the other views did update.

**Comment by kaxil** [comment]
> That's odd, could you describe your setup? I just tested again with Airflow 1.10.10, just starting webserver & scheduler from command line, no Docker, but still no Dag Code refresh, while the other views did update.

Let's do a screen share

**Comment by kaxil** [comment]
Sent you a zoom link on Airflow Slack.

My Setup is MacOS, installed Airflow in a VirtualEnv

**Comment by kaxil** [comment]
The DagCode uses a Modification Time, we can change that to actually checking the "diff" if need be

Can you also check on the Master, please? Want to know if it is the same for you on the Master

**Comment by BasPH** [comment]
Closed by https://github.com/apache/airflow/pull/8266
