### ISSUE TITLE
Implement Azure key vault secrets backend

### ISSUE THREAD

**Issue by BasPH** [apache/airflow#8258]
**Description**

A secrets backend for Azure Key Vault

**Use case / motivation**

In addition to AWS Secrets Manager & SSM, HashiCorp Vault, and GCP Secrets Manager, we could implement a secrets backend for Azure Key Vault.

**Related Issues**

No

**Comment by rammady** [comment]
Can we fetch secrete from azure key vault in Airflow using python code ?

**Comment by BasPH** [comment]
At the moment there is no secrets backend to do so, that's what this issue is for.

**Comment by rammady** [comment]
Thanks BasPH

**Comment by rammady** [comment]
Is there any work around for that? Please suggest .

**Comment by mik-laj** [comment]
@rammady Writing your own backend is quite easy. You only need to implement two methods. Please look at Google Secret Manager as an example
https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/secrets/secrets_manager.py
If you have experience with Azure then it should not be difficult to write it. Each workaround seems more difficult to implement than pure solution.

**Comment by rammady** [comment]
Thanks @mik-laj .

**Comment by mik-laj** [comment]
Would you like to try to do it?

**Comment by rammady** [comment]
yeah @mik-laj

**Comment by kaxil** [comment]
Yeah go ahead, I was planning to do it but if you want to here is the info I had collected:

Creating client: https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python#authenticate-and-create-a-client

Getting secret:
```python
retrieved_secret = client.get_secret(secretName)
```

**Comment by elwinarens** [comment]
```
from typing import Optional
import re

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from cached_property import cached_property

from airflow.secrets import BaseSecretsBackend
from airflow.utils.log.logging_mixin import LoggingMixin


class AzureKeyVaultBackend(BaseSecretsBackend, LoggingMixin):
    """
    Retrieves Airflow Connections or Variables from Azure Key Vault's secrets.

    Configurable via ``airflow.cfg`` like so:

    .. code-block:: ini

        [secrets]
        backend = orchestrator.providers.microsoft.azure.secrets.azure_key_vault.KeyVaultBackend
        backend_kwargs = {"vault_url": "<azure_key_vault_uri>"}

    For example, if secrets prefix is ``airflow-connections-smtp-default``, this would be accessible
    if you provide ``{"connections_prefix": "airflow-connections"}`` and request conn_id ``smtp-default``.
    And if variables prefix is ``airflow-variables-hello``, this would be accessible
    if you provide ``{"variables_prefix": "airflow-variables"}`` and request variable key ``hello``.

    :param vault_url: The URL of an Azure Key Vault to use.
    :type vault_url: str
    :param connections_prefix: Specifies the prefix of the secret to read to get Connections.
    :type connections_prefix: str
    :param variables_prefix: Specifies the prefix of the secret to read to get Variables.
    :type variables_prefix: str
    :param sep: separator used to concatenate secret_prefix and secret_id. Default: "-"
    :type sep: str
    """

    def __init__(
        self,
        vault_url: str = None,
        connections_prefix: str = 'airflow-connections',
        variables_prefix: str = 'airflow-variables',
        sep: str = "-",
        **kwargs
    ):
        super().__init__(**kwargs)
        self.connections_prefix = connections_prefix.rstrip(sep)
        self.variables_prefix = variables_prefix.rstrip(sep)
        self.vault_url = vault_url
        self.sep = sep
        self.kwargs = kwargs

    @cached_property
    def client(self):
        """
        Create a Azure Key Vault client
        """
        credential = DefaultAzureCredential()
        client = SecretClient(
            vault_url=self.vault_url,
            credential=credential,
            **self.kwargs
        )
        return client

    def get_conn_uri(self, conn_id: str) -> Optional[str]:
        """
        Get an Airflow Connection URI from an Azure Key Vault secret.

        :param conn_id: connection id
        :type conn_id: str
        """
        return self._get_secret(self.connections_prefix, conn_id)

    def get_variable(self, key: str) -> Optional[str]:
        """
        Get an Airflow Variable from an Azure Key Vault secret.

        :param key: Variable Key
        :return: Variable Value
        """
        return self._get_secret(self.variables_prefix, key)

    @staticmethod
    def build_path(path_prefix: str, secret_id: str, sep: str = "-") -> str:
        """
        Given a path_prefix and secret_id, build a valid secret bane for the Key Vault Backend.
        Also replaces all non alphanumeric characters in the path with dashes,
        so ``connection_default`` becomes ``connection-default``.

        :param path_prefix: Prefix of the path to get secret
        :type path_prefix: str
        :param secret_id: Secret id
        :type secret_id: str
        :param sep: separator used to concatenate path_prefix and secret_id. Default: "-"
        :type sep: str
        """
        path = "{}{}{}".format(path_prefix, sep, secret_id)
        return re.sub('[^0-9a-zA-Z-]', sep, path)

    def _get_secret(self, path_prefix: str, secret_id: str) -> Optional[str]:
        secret_name = self.build_path(path_prefix, secret_id, self.sep)
        try:
            secret = self.client.get_secret(secret_name)
            return secret.value
        except Exception as ex:
            self.log.debug(
                "An error occurred when calling the "
                "get_secret operation: "
                "Secret %s not found: %s", (secret_name, ex)
            )
            return None
```

**Comment by mik-laj** [comment]
@rammady Do you need any help?

@elwinarens I know you work on it too. Would you like to share something? Collaborative work is more effective and beneficial.

**Comment by elwinarens** [comment]
@mik-laj Need to check on the OSS policy before sharing, hence i deleted it. Let me get back to you asap.

**Comment by potiuk** [comment]
It woudl be great to create a Hook together with the backend -> similarly as I did with HashiCorp Vault https://github.com/apache/airflow/pull/8974

BTW. I thought that Azure's Vault is simply HashiCopr Vault Managed By Microsoft? Or am I completely wrong?

**Comment by rammady** [comment]
@mik-laj I didn't do much on this .I'll share once there is something meaningful .

**Comment by alexbegg** [comment]
@rammady @elwinarens today I have been writing my own secret backend for Azure Key Vault if you want me to help with contributing this too.

I am using kwargs for the Service Principle's client id, client secret, and tenant id. I am also documenting it just as much as the other backends. I am doing some final QA-ing before I am PR ready.

I also added a kwarg called `word_sep` in which you can specify the word separator of the conn_id or variable key because Key Vault does not accept underscores for secret names. It defaults to "_" because that is the recommended separator for conn_ids. This is in addition to the `sep` kwarg that separates the prefix and the conn_id, and it defaults to "-" just like with GCP Secrets Manager.

**Comment by alexbegg** [comment]
One question I have is what is a suggested location to store a custom secret backends file in relation to the airflow home dir? The only other time I used a path in the config was for a logging config path but this actually feels more like a plugin than an config. On that thought... is there any plans to allow for adding secret backends as part of a plugin?

**Comment by mik-laj** [comment]
We do not plan to support plugins for secret backends. Custom secret backends can be distributed using regular python packages. If you do not want to create a package, you can add code to the sys.path variable using PYTHONPATH or take advantage of the fact that some directories are automatically added by Airflow e.g. plugin  directory (https://github.com/apache/airflow/issues/8647#issuecomment-623208206)

plugins should only be used to make changes to Web UI. Any other use carries its problems e.g. higher memory consumption by Airflow

**Comment by alexbegg** [comment]
@mik-laj thank you for the clarification. Seeing operators, hooks, and sensors in airflow plugins documentation caused me to think it was the preferred method. It is good to know about the increased memory consumption. These notes should get added to the documentation.

**Comment by mik-laj** [comment]
@alexbegg I agree. Here is a ticket that discusses defects in the documentation about loading modules.
https://github.com/apache/airflow/issues/8715

**Comment by alexbegg** [comment]
@mik-laj Thank you, that will be very useful to have documented!
