### ISSUE TITLE
Add Jira/Github Issue to "CONTIRUBTE.rst"

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8271]
**What you expected to happen**:

I would be happy if Jira and Github were added to the "How to communicate" section of the CONTRIBUTING.rst file. They should present Jira's previous and current role, and describe the Github Issue and the differences between the two services.
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#how-to-communicate

We need this description to answer questions similar to the following:
https://lists.apache.org/thread.html/rd52ec6081dd612e51e77f119ce94984cf8cbe8629da497496b7cde80%40%3Cdev.airflow.apache.org%3E

Best regards,

**Comment by potiuk** [comment]
Why not adding it @mik-laj  ? Adding docs is easy :D

**Comment by mik-laj** [comment]
I didn't have time to deal with it at the moment. On the other hand, I didn't want to miss it.

**Comment by mik-laj** [comment]
@mschickensoup Can you look ai it?

**Comment by eladkal** [comment]
If needed I can address this in the following days

**Comment by mschickensoup** [comment]
@mik-laj I can also have a look at it, so @eladkal can have less work :-)
