### ISSUE TITLE
Missing unit tests for some modules in providers package

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8278]
**Description**

We have a rule that every file in the `providers` directory should have tests. This is true in many cases, but there are minor exceptions.
https://github.com/apache/airflow/blob/master/tests/test_project_structure.py#L29-L50

- [x] `tests/providers/amazon/aws/hooks/test_athena.py`
- [x] `tests/providers/apache/cassandra/sensors/test_record.py`
- [x] `tests/providers/apache/cassandra/sensors/test_table.py`
- [x] `tests/providers/apache/hdfs/sensors/test_web_hdfs.py`
- [x] `tests/providers/apache/hive/operators/test_vertica_to_hive.py`
- [x] `tests/providers/apache/pig/operators/test_pig.py`
- [x] `tests/providers/apache/spark/hooks/test_spark_jdbc_script.py`
- [x] `tests/providers/cncf/kubernetes/operators/test_kubernetes_pod.py`
- [x] `tests/providers/google/cloud/operators/test_datastore.py`
- [x] `tests/providers/google/cloud/operators/test_sql_to_gcs.py`
- [x] `tests/providers/google/cloud/sensors/test_bigquery.py`
- [x] `tests/providers/google/cloud/utils/test_field_sanitizer.py`
- [x] `tests/providers/google/cloud/utils/test_field_validator.py`
- [x] `tests/providers/google/cloud/utils/test_mlengine_operator_utils.py`
- [x] `tests/providers/google/cloud/utils/test_mlengine_prediction_summary.py`
- [x] `tests/providers/jenkins/hooks/test_jenkins.py`
- [x] `tests/providers/microsoft/azure/sensors/test_azure_cosmos.py`
- [x] `tests/providers/microsoft/mssql/hooks/test_mssql.py`
- [x] `tests/providers/oracle/operators/test_oracle.py`
- [x] `tests/providers/qubole/hooks/test_qubole.py`
- [x] `tests/providers/samba/hooks/test_samba.py`
- [x] `tests/providers/sqlite/operators/test_sqlite.py`
- [x] `tests/providers/yandex/hooks/test_yandex.py`

I would be happy if someone would complete the missing tests.

If you decide to finish this ticket you don't have to do all the work yourself. One PR can only deal with a single file and it's ok.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

Raising test coverage facilitates refactoring and prevents regression.

For the contributor, this is an opportunity to learn more about the structure of the project and to learn better good practices in writing tests in Python. 

**Related Issues**

N/A

**Comment by samuelkhtu** [comment]
If no one is working on the test_mssql.py, I can take work it.

tests/providers/microsoft/mssql/hooks/test_mssql.py

**Comment by subkanthi** [comment]
Added tests for Yandex hook
- tests/providers/yandex/hooks/test_yandex.py

https://github.com/apache/airflow/pull/9665/files

**Comment by subkanthi** [comment]
Added unit test for jenkins hook
https://github.com/apache/airflow/pull/9767

**Comment by rootcss** [comment]
I've picked Cassandra table and record sensors hook.
```
 tests/providers/apache/cassandra/sensors/test_record.py
 tests/providers/apache/cassandra/sensors/test_table.py
```

**Comment by rootcss** [comment]
Picked  `tests/providers/apache/hdfs/sensors/test_web_hdfs.py`

**Comment by mik-laj** [comment]
@rootcss Wouldn't you be willing to give some love for this ticket?
https://github.com/apache/airflow/issues/8189

**Comment by rootcss** [comment]
> @rootcss Wouldn't you be willing to give some love for this ticket?
> #8189

@mik-laj Here's some more ❤️ for Cassandra - https://github.com/apache/airflow/pull/9877

**Comment by ari-hacks** [comment]
I'd like to tackle ` tests/providers/microsoft/azure/sensors/test_azure_cosmos.py`

**Comment by rootcss** [comment]
I'm picking the following tests:
- [ ] tests/providers/google/cloud/utils/test_field_sanitizer.py
- [ ] tests/providers/google/cloud/utils/test_field_validator.py
- [ ] tests/providers/google/cloud/operators/test_datastore.py
- [ ] tests/providers/microsoft/mssql/hooks/test_mssql.py
- [ ] tests/providers/samba/hooks/test_samba.py
cc: @mik-laj

**Comment by rootcss** [comment]
@mik-laj `MsSqlHook` in airflow/providers/microsoft/mssql/hooks/mssql.py is deprecated. Do we still need to add tests for it?

**Comment by mik-laj** [comment]
@rootcss If someone is willing, they can add tests, but it is not necessary. I will be happy without tests for this module.

**Comment by mik-laj** [comment]
@rootcss As far as I know, Tomek is working on tests for Datastore. 

@turbaszek Can you confirm that?

**Comment by mik-laj** [comment]
I found PR: https://github.com/PolideaInternal/airflow/pull/946

**Comment by rootcss** [comment]
> @rootcss As far as I know, Tomek is working on tests for Datastore.
> 
> @turbaszek Can you confirm that?

Sure. I've removed it from my list.

**Comment by rootcss** [comment]
@mik-laj I think, rest of the tests have been picked already. We're close to close this issue :)

**Comment by rootcss** [comment]
I've picked  `tests/providers/google/cloud/utils/test_mlengine_prediction_summary.py`

**Comment by mik-laj** [comment]
The ticket has been completed :-D

Thanks to everyone who participated in this task.
More info: https://github.com/apache/airflow/pull/10799

**Comment by potiuk** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by rootcss** [comment]
👍
