### ISSUE TITLE
Missing crossreferences between hooks and guides

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8282]
Hello,

We have a [guide for many connection types](https://airflow.readthedocs.io/en/latest/howto/connection/index.html#connection-types) and many hooks for these connections.

The following fragment should appear in the hook documentation:
```rst
    .. seealso::
        For more information on how to set-up connection for this hook, take a look at:
        :ref:`howto/connection:XXX`
```

If the class has subclasses, the note should only be in the base class.

Similar information should be found in the connection documentation.
```rst
    .. seealso::
        For more information on how to use the connection with the hook, take a look at:
        :class:`airflow`
```

The purpose of this change is to facilitate access to related parts of the documentation.

Best regards,
Kamil

**Comment by alexandrecaze** [comment]
Hi @mik-laj I am down to work on this issue.

**Comment by mik-laj** [comment]
@alexandraabbas Do you need any help?

**Comment by satishbellapu** [comment]
@mik-laj Is this still open for pick-up ?

**Comment by mik-laj** [comment]
@satishbellapu This task has not been completed. I assigned you to this ticket. I look forward to your contribution.

**Comment by satishbellapu** [comment]
@mik-laj  can you be more clear on the requirement or some sample connector which has the ref as per your guideline should help me to close the PR at the earliest.

**Comment by mik-laj** [comment]
Currently, operators have a reference between the documentation and the class.
<img width="856" alt="Screenshot 2020-06-28 at 09 43 36" src="https://user-images.githubusercontent.com/12058428/85941636-4ec95500-b924-11ea-8408-8b89aa499e0c.png">
<img width="782" alt="Screenshot 2020-06-28 at 09 43 46" src="https://user-images.githubusercontent.com/12058428/85941642-512baf00-b924-11ea-9b12-ea64b0c77eee.png">
https://airflow.readthedocs.io/en/latest/howto/operator/gcp/compute.html
https://airflow.readthedocs.io/en/latest/_api/airflow/providers/google/cloud/operators/compute/index.html#airflow.providers.google.cloud.operators.compute.ComputeEngineStartInstanceOperator

Based on this, I came up with the idea that a reference between the hook and the connection type would be useful.

In the case of Google, means that you must add a reference to the connection configuration in class A.
Here is docstring for GoogleBaseHook
https://airflow.readthedocs.io/en/latest/_api/airflow/providers/google/common/hooks/base_google/index.html#airflow.providers.google.common.hooks.base_google.GoogleBaseHook
Here are docs for Google connection:
https://airflow.readthedocs.io/en/latest/howto/connection/gcp.html
However, we have more classes that have no references. A list of all connections is available. Here is the complete list of connections that have documentation.
https://airflow.readthedocs.io/en/latest/howto/connection/index.html#connection-types

If there are many hooks that use a given type of connection, only the base class should have a note i.e. GoogleBaseHook should have a reference, CloudFirestoreHook should not have a reference.

**Comment by satishbellapu** [comment]
Thanks for the explanation @mik-laj will get back if i have questions.

**Comment by eladkal** [comment]
Closing as many already fixed.
I'll try to generate list for the missing ones and open a dedicated issue for them as not all providers have howto guide for connections.
