### ISSUE TITLE
Bump supported mysqlclient to <1.5

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#8292]
**Description**

version 1.4.X introduced in Jan 2019 

we should support it if we can.

**Use case / motivation**

pin of <1.4 was done in https://github.com/apache/airflow/pull/4558 due to lack of Python 2 compatibility. Since Master doesn't support Python 2 anymore there is no need for that restriction

**Related Issues**

Moved from https://issues.apache.org/jira/browse/AIRFLOW-4810

I tried to fix it in https://github.com/apache/airflow/pull/5430 but didn't get help with the tests so if any one wants to pick it up be my guest.

**Comment by potiuk** [comment]
I will take a look later this week. I have plans to review al the requirements and remove some conflicting ones.

**Comment by stackapack** [comment]
I'm currently looking into this.

**Comment by RosterIn** [comment]
@potiuk are you working on this or it's open for anyone to pick?

**Comment by potiuk** [comment]
Free to pick. I have forgotten about this one completely

**Comment by uranusjr** [comment]
I’ll probably find some time to create a new PR this week. The last one seems to have got pretty close but unfortunately went stale.

**Comment by RosterIn** [comment]
mysqlclient has version 2.0.3 out:
https://pypi.org/project/mysqlclient/#history
