### ISSUE TITLE
Architecture diagram on Documentation is broken

### ISSUE THREAD

**Issue by rkhaled0** [apache/airflow#8293]
**Apache Airflow version**: N/A
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: Mac OS Catalina
- **OS** (e.g. from /etc/os-release): macOS Catalina version 10.15.4
- **Others**: Safari v13.1

**What happened**:

Architecture diagram on the following page is broken (rendering KO) :

https://airflow.apache.org/docs/stable/executor/celery.html#architecture

**What you expected to happen**: a beautiful diagram ^^

**Comment by mik-laj** [comment]
@kaxil Do you have graphviz installed?

> The following additional application must be installed to use the project:
> 
> * python3.6 or newer
> * pip
> * graphviz

https://github.com/apache/airflow-site/blob/master/CONTRIBUTE.md#how-to-release-new-documentation

**Comment by kaxil** [comment]
Thanks for raising the issue, will fix it today @r3da-hash .

@mik-laj Hmm I installed it but looks like `pip3` vs `pip`. Anyways, will fix it today.

**Comment by kaxil** [comment]
PR: https://github.com/apache/airflow-site/pull/265

**Comment by kaxil** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/8811558/79251806-950c2d80-7e78-11ea-8999-76cfd4bf80b6.png)
