### ISSUE TITLE
Customizable configurable footer in admin web interface

### ISSUE THREAD

**Issue by MShekow** [apache/airflow#8297]
**Description**

The footer area of the HTML template of the admin web interface should be customizable. The server admin should be able to add arbitrary HTML code. This could be achieved by the ability to provide the HTML code in the `airflow.cfg`, or by overwriting a .html template file (which is non-existent or empty by default) in a defined location.

**Use case / motivation**

Websites *must* have a link to a privacy page, by EU laws. Typically, the link to those kinds of pages is placed in the footer of the page. A customizable footer would enable this use case.

**Related Issues**
None

**Comment by potiuk** [comment]
@MShekow Could you please provide a link to the regulations? I believe they apply only to public websites and Airflow's web interface is not a public website - it is an internal application. 

Providing link with justification would be great if you think otherwise. For now I am closing this issue as invalid, but I am happy to reconsider and re-open if you provide the links that will show us that indeed there is a need for such privacy statement.

**Comment by MShekow** [comment]
I don't have a link at hand, but you're right in your assumption that the regulations only apply to public websites. However, the admin interface may well be publicly accessible, but authentication-protected. Public access facilitates access to external collaborators who are not part of the company network. Working with IT departments to get VPN set up is a pure nightmare... I'd rather hack Airflow templates for the rest of my life (which would also be much faster).

The ability to modify the footer could also be useful in other cases, e.g. if you want to place other kinds of information into the footer.

**Comment by potiuk** [comment]
I would not recommend anyone open up the admin interface of Airflow to the public. And authentication is a must. While I agree editable footer might be a good idea, I would leave that to the UI revamp that is planned to happen soon. We are going to rewrite the UI from the scratch most likely and I guess we can do it with technology that is better suited for templatization and customization. For now, I would not spend any cycles on making it happen..
