### ISSUE TITLE
No way to create a Dataflow job with Private IP configuration

### ISSUE THREAD

**Issue by sgringwe** [apache/airflow#8300]
**Description**

It does not appear that Airflow supports https://cloud.google.com/dataflow/docs/guides/specifying-networks#public_ip_parameter in it's GCP Dataflow operators.

Looking at the documentation and at  https://github.com/apache/airflow/blob/16d93c9e45e14179c7822fed248743f0c3fd935c/airflow/contrib/hooks/gcp_dataflow_hook.py#L275 it seems that Airflow does not support passing in a private IP configuration for Dataflow jobs. In Terraform, they use IpConfiguration as seen at https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_dataflow_job.go#L183. Ideally, Airflow could use the same parameter.

Unfortunately, there does not seem to be any documentation for this parameter that is being used https://cloud.google.com/dataflow/docs/reference/rest/v1b3/RuntimeEnvironment. Potentially this is a bug only in their docs?

**Use case / motivation**

I want to use https://cloud.google.com/dataflow/docs/guides/specifying-networks#public_ip_parameter feature so my VMs do not have public IPs

**Related Issues**

I don't believe so

**Comment by mik-laj** [comment]
Hi. 
It looks like a real bug. In the near future, I will try to address this problem.

Thanks for the report.

**Comment by mik-laj** [comment]
> Unfortunately, there does not seem to be any documentation for this parameter that is being used https://cloud.google.com/dataflow/docs/reference/rest/v1b3/RuntimeEnvironment. Potentially this is a bug only in their docs?

Truth. Documentation is not updated. This object accepts the following parameters.

- `additionalExperiments`
- `additionalUserLabels`
- `bypassTempDirValidation`
- `ipConfiguration`
- `kmsKeyName`
- `machineType`
- `maxWorkers`
- `network`
- `numWorkers`
- `serviceAccountEmail`
- `subnetwork`
- `tempLocation`
- `workerRegion`
- `workerZone`
- `zone`

You can configure private IP via ``ipConfiguration`` parameter.


> **`ipConfiguration`**
> 
> Configuration for VM IPs.
> 
> Type: string
> 
> The following values are accepted.
> 
> | Value                                       |  Description                                                          |
> |-----------------------------|-----------------------------------------------|
> |`WORKER_IP_UNSPECIFIED` | The configuration is unknown, or unspecified. |
> |`WORKER_IP_PUBLIC`           | Workers should have public IP addresses.        |
> |`WORKER_IP_PRIVATE`          | Workers should have private IP addresses.      |
>
