### ISSUE TITLE
Ability to see subdags tasks within parent dag

### ISSUE THREAD

**Issue by KevinKobi** [apache/airflow#8306]
**Description**
Ability to see subdags task within parent dag.
The idea is to add button or something similar that will convert all subdags to regular view like subdag doesn't exist.

**Use case / motivation**

It's possible to see the tasks within subdag by zoom in  but it's not possible to see all the tasks from parent + all subdags in one place. This can become handy.

**Related Issues**

**Comment by stephenonethree** [comment]
This would be nice as long as we could toggle it!

**Comment by kaxil** [comment]
Use TaskGroups feature -- https://airflow.apache.org/docs/apache-airflow/stable/concepts.html#taskgroup
