### ISSUE TITLE
Task Duration Missing from the Graph View Tool-tip for Running Tasks

### ISSUE THREAD

**Issue by shane-graham** [apache/airflow#8311]
**Apache Airflow version**: 1.10.10

**Environment**:

- **Cloud provider or hardware configuration**:  AWS EC2 m5.2xlarge
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- **Kernel** (e.g. `uname -a`): Linux 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Python 3.7.7/Pip in a virtual environment
- **Others**:  **RBAC UI**, on a standalone server with the LocalExecutor running a PostgreSQL repository

**What happened**:  The Graph View tool-tip does not display the duration of running tasks while the Tree View does.  In addition, the Graph View shows "Invalid Date" for the "Ended:" field while the Tree View displays the current datetime.

**What you expected to happen**:  The Graph View should show the same date and duration information as the Tree View for running tasks.

**How to reproduce it**:  While a DAG is executing, examine the tool-tips in both the Tree View and Graph View pages.

![image](https://user-images.githubusercontent.com/46032116/79288560-12de3200-7e95-11ea-8bc9-88de94f07e74.png)

**Comment by zachliu** [comment]
upgraded to `1.10.10` two weeks ago, just noticed this issue :sweat_smile:

**Comment by fuyi** [comment]
I start working on this bug, have already reproduced the issue and start fixing it. will submit a PR soon

**Comment by XD-DENG** [comment]
Thanks @fuyi for taking up this

**Comment by fuyi** [comment]
PR is available at: https://github.com/apache/airflow/pull/8675

**Comment by ipeluffo** [comment]
I noticed this issue also in (some) tasks on finished DAGs. Has anyone else noticed this?

**Comment by eladkal** [comment]
fixed in #8675
