### ISSUE TITLE
Sending email requires to systematicaly log on the smtp server

### ISSUE THREAD

**Issue by agrouaze** [apache/airflow#834]
In the utils.py send_MIME_email() method, first the "smtp_user" and "smtp_password" are mandatory and are retrieved as strings thus they cannot contains None. Therefore the line:
s.login(SMTP_USER, SMTP_PASSWORD)
is systematicaly executed while in some case one just want to send a email without having to connect to the smtp server.
So in my opinion it is an issue. Correct if it is wrong.

**Comment by mistercrunch** [comment]
In python empty string evals as False, and empty strings are set as conf defaults.

`s.login` happens in an if block `if SMTP_USER and SMTP_PASSWORD`, so that line shouldn't execute if either are left empty.

**Comment by agrouaze** [comment]
Thank for the explanation. Then the ticket can be closed.
