### ISSUE TITLE
Creating a chart using snowflake connection throws no hooks found error.

### ISSUE THREAD

**Issue by sakcruise** [apache/airflow#8379]
After adding snowflake connections in Admin -> Connections UI. Trying to create a chart using DataProfiling -> Charts using the snowflake connection, throws the below error

 **SQL execution failed. Details: Unknown hook type snowflake**

**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): MAC Mojave
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:

Error: SQL execution failed. Details: Unknown hook type snowflake!

**What you expected to happen**:

It should list the data from the table.

**How to reproduce it**:
Add snowflake connections in admin section and use that to create a chart. just a data table type.
should give you this error.
![Screenshot 2020-04-15 at 14 09 13](https://user-images.githubusercontent.com/28932255/79341009-03a5c580-7f23-11ea-8011-6346430b04f5.png)

**Anything else we need to know**:

I know the exact reason, its because in connections.py (airflow.models.connections) https://github.com/apache/airflow/blob/master/airflow/models/connection.py
CONN_TYPE_TO_HOOK does not have the definition for 'snowflake'. And it should work after adding the below line. But i dont want to change that file. Its good to be fixed.

` "snowflake": ("airflow.contrib.hooks.snowflake_hook", "snowflake_conn_id")`

**Comment by dephusluke** [comment]
@sakcruise if you know the fix why not just fixing it?

**Comment by simond** [comment]
Should this issue be closed? It looks like the fix has been made [here](https://github.com/apache/airflow/blob/master/airflow/models/connection.py#L85)

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/9843
