### ISSUE TITLE
filter_by_owner showing all dags rather than only owner

### ISSUE THREAD

**Issue by Ecako** [apache/airflow#838]
I have authentication set up and working through ldap, however regardless of owner I am able to see all DAGs in the web ui even though i have set filter to true
# Set to true to turn on authentication : http://pythonhosted.org/airflow/installation.html#web-authentication

authenticate = True
auth_backend = airflow.contrib.auth.backends.ldap_auth
# Filter the list of dags by owner name (requires authentication to be enabled)

filter_by_owner = True

**Comment by bolkedebruin** [comment]
This is a know issue and is on the roadmap. Please create a Jira issue for this. Thanks.
