### ISSUE TITLE
Support 'capacityProviderStrategy' option for ECSOperator

### ISSUE THREAD

**Issue by chang12** [apache/airflow#8381]
**Description**

[AWS launches Fargate Spot](https://aws.amazon.com/about-aws/whats-new/2019/12/aws-launches-fargate-spot-save-up-to-70-for-fault-tolerant-applications/) on December, 2019. It can be configured in [run_task on boto3 with 'capacityProviderStrategy' option](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task). It would be nice if we could set this option for ECSOperator.

**Use case / motivation**

Tasks with Fargate Spot are cheaper than tasks without Fargate Spot.

**Related Issues**

None found.

**Comment by hammad13060** [comment]
@eladkal I'd like to work on this. How can I assign this issue to myself.

**Comment by mik-laj** [comment]
@hammad13060  I assigned you to this ticket.

**Comment by eladkal** [comment]
@hammad13060 unassigning you from this issue as you didn't complete the PR

This issue is now open for anyone who wants to work on it.

**Comment by codenamestif** [comment]
i would like to take this one

**Comment by potiuk** [comment]
Feel free @codenamestif !
