### ISSUE TITLE
add HostPID and HostIPC support to KubernetesPodOperator

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#8402]
**Description**

HostPID - Controls whether the pod containers can share the host process ID namespace. Note that when paired with ptrace this can be used to escalate privileges outside of the container (ptrace is forbidden by default).

HostIPC - Controls whether the pod containers can share the host IPC namespace.

**Use case / motivation**
I'd like to be able to start KubernetesPodOperator with HostPID / HostIPC privileges
expose security functionality to the operator.

**Related Issues**

**Comment by kaxil** [comment]
From Airflow 1.10.14 we expose the entire Kubernetes Pod object API, so this should allow you to add HostPID and HostIPC
