### ISSUE TITLE
Increase max password length in Airflow Connections

### ISSUE THREAD

**Issue by pablosjv** [apache/airflow#8417]
**Description**

Increase max password length stored in Airflow Connections from the 500 characters to 5000 characters. 

**Use case / motivation**

The current password length in the Airflow Connections is 500 characters. This is enough for most of the use cases. However, we should be able to store longer passwords in the databases. 

Right now, I am increasing the size of the password by modifying the column in PostgreSQL. But as a user, I would want that this is the default configuration for the database so I don't need to do any custom tweaking to store the connections in Airflow.

The "extra" field length is 5000 characters and potentially, I could store the passwords there. However, this is not the most secure approach as that field is not encrypted.

**Related Issues**

None.

**Comment by kaxil** [comment]
We have already increased the limit to 5000 in Airflow 1.10.7

https://github.com/apache/airflow/pull/6241

**Comment by pablosjv** [comment]
Thanks! I was working with 1.10.4 version.

However, I couldn't find that issue in the [changelog for 1.10.7](https://airflow.apache.org/docs/stable/changelog.html#airflow-1-10-7-2019-12-24). Is the changelog updated? Or Am I not looking at the correct place?

**Comment by kaxil** [comment]
> Thanks! I was working with 1.10.4 version.
> 
> However, I couldn't find that issue in the [changelog for 1.10.7](https://airflow.apache.org/docs/stable/changelog.html#airflow-1-10-7-2019-12-24). Is the changelog updated? Or Am I not looking at the correct place?

It is not nicely worded by it is at https://airflow.apache.org/docs/stable/changelog.html#id9

![image](https://user-images.githubusercontent.com/8811558/79586709-65079900-80c9-11ea-8750-4b61307f53d2.png)

>[AIRFLOW-6185] SQLAlchemy Connection model schema not aligned with Alembic schema (#6754)

**Comment by potiuk** [comment]
Indeed :). If you are looking for Password length change, you'd not find it :)
