### ISSUE TITLE
Update docker operator network documentation

### ISSUE THREAD

**Issue by pablosjv** [apache/airflow#8418]
**Description**

The current parameter for selecting the network in the DockerOperator is `network_mode`. There is not a clear explanation of the scope of this field in the docs.

**Use case / motivation**

I was trying to develop a dag that needed access to a predefined docker network in the Host. I found in the documentation the `network_mode` parameter for the docker operator. The description of the parameter is the following:

```
network_mode (str) – Network mode for the container.
```

By this description, I supposed that the available parameters for the network_mode were just the default drivers (bridge, host, overlay). However, when testing it, I found out that you can indeed specify a user-defined network for the DockerOperator. 

I think that the current documentation is not clear enough about this functionality (or maybe the parameter name is not very descriptive). It would be very useful to have more detailed docs in this section of the documentation.

Thanks in advance! 

**Related Issues**

None.

**Comment by potiuk** [comment]
How about you add it yourself ? @pablosjv. Just create a PR!

**Comment by dedunumax** [comment]
I added the link on docker documentation. network_method is used to define Docker network drivers as I understood. Correct me if I am wrong @pablosjv. Thank you.

**Comment by mbarkhau** [comment]
I've looked through the code of the DockerOperator and from what I can tell, the `network_mode` parameter is passed through to the `network_mode` parameter of [`APIClient.create_host_config`](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config) method:

From the source code at `docker/api/container.py`(https://github.com/docker/docker-py/blob/master/docker/api/container.py#L443):
```
    def create_host_config(self, *args, **kwargs):
            """
            ...

            network_mode (str): One of:
                - ``bridge`` Create a new network stack for the container on
                  the bridge network.
                - ``none`` No networking for this container.
                - ``container:<name|id>`` Reuse another container's network
                  stack.
                - ``host`` Use the host network stack.
                  This mode is incompatible with ``port_bindings``.
```

**Comment by eracle** [comment]
On the dockerpy documentation is not mentioned: the `network_mode` parameter can also be the name of the network.

**Comment by Bowrna** [comment]
Shall I try to fix this documentation? This is quite new for me, but I think I can do it.
