### ISSUE TITLE
How to run downstream tasks automatically when rerun the upstream task?

### ISSUE THREAD

**Issue by adadle** [apache/airflow#842]
A -> B

task B depends on task A.
when we rerun A, how to run the downstream tasks?

**Comment by mistercrunch** [comment]
clear A with the "including downstream" option, then either let the scheduler pick up the tasks. You can do it from the UI or CLI.

**Comment by CooperLuan** [comment]
What if C depend A using ExternalTaskSensor in another dag?
Can CLI deal with this situation?
