### ISSUE TITLE
DockerSwarmOperator always pulls docker image

### ISSUE THREAD

**Issue by CodingJonas** [apache/airflow#8420]
**Airflow Version**: 1.10.10

I noticed that the `DockerSwarmOperator` always pulls the required docker image on the machine the worker, which executes the task, is running.

Is there a reason to do this? Since the docker swarm runs distributed, a different node could run the service, which has to pull the docker image, too. This behaviour makes to my knowledge only sense for the `DockerOperator`.

The `DockerSwarmOperator` uses the [execute function](https://github.com/apache/airflow/blob/79d3f33c1b65c9c7e7b1a75e25d38cab9aa4517f/airflow/providers/docker/operators/docker.py#L281) of the `DockerOperator` which always pulls the image. 

Would it make sense to redefine the execute function of the `DockerSwarmOperator` to remove this behaviour? If so I'm happy to make a pull request for it :)

**Comment by potiuk** [comment]
Why invalid? Looks like it's quite valid point :). Did you change your mind ?

**Comment by CodingJonas** [comment]
The invalid tag was set automatically, and I didn't find a way to change it. I must have done something wrong when I created the issue.

**Comment by potiuk** [comment]
Feel free to make a PR :). The issue Llooks very VALID :)
