### ISSUE TITLE
defaults_args can't take into method of class instance 

### ISSUE THREAD

**Issue by xiaohan2013** [apache/airflow#8425]
**Apache Airflow version**:  1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: amazon ec2
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):Linux version 4.14.165-103.209.amzn1.x86_64
- **Install tools**:pip3
- **Others**:

**What happened**: pickle _thread.RLock objects

**What you expected to happen**: 

**How to reproduce it**:   
1. 
default_args = {
    'owner': 'xxx',
    'depends_on_past': False,
    'start_date': datetime(2020, 4, 6),
    'email': ['xxx@xxx.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
    'retry_delay': timedelta(minutes=5),
    'on_failure_callback': notifier.failure_callback
}
2.  notifier = Notifier(subscribers=[Notifier.MSG], phone_receivers="111111111111",
                    email_receivers="xxxxx@xxxxx.com")

3. dag = DAG('xxxxxxx',
          default_args=default_args,
          schedule_interval='01 20 * * *')
4. UI throw exception， pickle _thread.RLock objects ，however in the logfile throwing TypeError: cannot serialize '_io.TextIOWrapper' object

**Anything else we need to know**:

**Comment by kaxil** [comment]
This is not to do with default_args but to do with Logger object, what operator are you using ?

**Comment by brstorrie** [comment]
Ended up being a problem with Marquez-airflow instrumentation, this can be closed.
