### ISSUE TITLE
Support slackclient v2 with 2.0

### ISSUE THREAD

**Issue by michaelosthege** [apache/airflow#8433]
**Description**
Slack migrated their Python client to v2. In v1 they ended support for Python 2.7 with its EOL.

Airflow 2.0 will also end support for Python 2.7, so there's no need for the outdated dependency to stick around.

**Use case / motivation**
The [Python Slack SDK documentation](https://slack.dev/python-slackclient/) for v1 of the SDK is nowhere to be found, taking all the fun out of using it.

Furthermore, [Slack does not add new features to the v1 SDK](https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x#minimum-python-versions).

**Related Issues / PR**
PR https://github.com/apache/airflow/pull/5519 already implemented the change for the Slack operators, but was not merged because Python 2 was still supported at the time.

The corresponding [AIRFLOW-4543](https://issues.apache.org/jira/browse/AIRFLOW-4543) ticket is closed and cannot be reopened.

**Comment by eladkal** [comment]
Resolved in https://github.com/apache/airflow/pull/5519 and released in [slack provider ](https://pypi.org/project/apache-airflow-backport-providers-slack/)>= 2020.6.24
