### ISSUE TITLE
Clean up the test_variable_commnand.py file.

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8439]
Hello,

There is some mess in this file. All commands are tested in one method, which makes it difficult to develop these commands.
https://raw.githubusercontent.com/apache/airflow/17fc9c541ea4aecbd5ae566a11f6601b4038b197/tests/cli/commands/test_variable_command.py
I would be happy if each command was tested in a separate method and if there were no side effects between tests.

Additional points can be obtained if you add an assertion that will check the content of the file during export and import.

Best regards,
Kamil

**Comment by Kopurlso** [comment]
Hey @mik-laj I'm a bit of a beginner, but I'd love to try my hand at this issue, if I'm understanding the ask correctly, you want to refactor out each variable_command method into its own testing method for easier testing.

**Comment by mik-laj** [comment]
Yes.  I want to divide one large test method into several smaller ones.

**Comment by mik-laj** [comment]
@Kopurlso How do you do? Have you encountered any difficulties?

**Comment by voltaiq-austin-chou** [comment]
I had some trouble setting up my environment initially but now have tests running and am slowly working through the tests to make sure I understand what's going on. I hope to have a PR up by Thursday latest but hopefully earlier. Thanks for checking in!

**Comment by mik-laj** [comment]
@voltaiq-austin-chou  Do you use Breeze? Can you tell a little more about your problems? We try to make it easy for everyone to join the project. Your feedback would be very helpful for us.

**Comment by voltaiq-austin-chou** [comment]
@mik-laj yea I used Breeze, but I spent a while trying to integrate it into PyCharm since that's the IDE I'm used to. I guess I'm not sure how to properly set the Docker environment in PyCharm and so spent a while trying to download dependencies there but it was unsuccessful so I'm just running the tests via command line as shown in the Breeze intro video with pytest which works.

**Comment by mik-laj** [comment]
@voltaiq-austin-chou I also use the console. In the IDE, I only run some tests when I'm sure they don't contain any dependencies - are real unit tests. A lot of operator tests can be run this way but I run the core in the breeze console

**Comment by voltaiq-austin-chou** [comment]
Hey @mik-laj I made a PR but please feel free to add any feedback if you have any. Also not sure how to add reviewers to a PR...normally I can request them but I'm not sure why I can't

**Comment by potiuk** [comment]
Only committers can add reviewers
