### ISSUE TITLE
mark as success does not apply to children in a subdag

### ISSUE THREAD

**Issue by syvineckruyk** [apache/airflow#844]
@mistercrunch I use subdags a lot. The clear command applies to a subdag and it's contained tasks. However mark as succes only applies to the subdag operator task but does not change the status of the children.

Does it make sense to you to modify the behavior of mark as success to be more like clear ?

**Comment by mistercrunch** [comment]
I know that for clear we sometimes want either behavior, depending if you want to throw away the succeeded steps within the subdag or not. We used the CRUD "Task Instance" view when we just need to delete and not clear. 

For mark success I'm not sure why it's useful to mark the success within the sub dag. Do you have it set as `depends_on_past` within?

**Comment by syvineckruyk** [comment]
@mistercrunch sorry for the delay ... yes that's the issue ... it's the depend on past on the tasks within a subdag. There are some edge cases when I rerun a task instance in the past where I have marked the previous instances as success manually .. the task will not run. In fact it get's caught in a queued state and never gets picked up. Though other tasks progress through the queue just fine.
