### ISSUE TITLE
Command descriptions too long

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8447]
Hello,

The description of some of the commands on the list are too long. This makes them difficult to read.
<img width="726" alt="Screenshot 2020-04-18 at 23 02 43" src="https://user-images.githubusercontent.com/12058428/79671178-bd719000-81c8-11ea-97b5-fc4b4aae0abf.png">

I think that some text should be moved to descriptions of individual commands e.g. `airflow days backfill --help``.
We currently do not have descriptions for individual commands. After executing the `` --help '' command, we only have a list of arguments.
<img width="720" alt="Screenshot 2020-04-18 at 23 04 40" src="https://user-images.githubusercontent.com/12058428/79671219-248f4480-81c9-11ea-8b6c-030495e3be86.png">

After making changes it may look like the screen below.
<img width="720" alt="Screenshot 2020-04-18 at 23 08 11" src="https://user-images.githubusercontent.com/12058428/79671262-8059cd80-81c9-11ea-8539-dee59122c511.png">

<img width="729" alt="Screenshot 2020-04-18 at 23 10 58" src="https://user-images.githubusercontent.com/12058428/79671338-e5152800-81c9-11ea-9f3a-1f28628d6af5.png">

Descriptions can be set by the parameters `description` or` epilogue`.
https://github.com/apache/airflow/blob/8517cb189872aebdd70e9d5d584478cd7fb65d0f/airflow/cli/cli_parser.py#L1280-L1282

```diff
    sub_proc = subparsers.add_parser(
-        sub.name, help=sub.help
+        sub.name, help=sub.help, description="DESCRIPTION", epilog="EPILOG"
    )
```

I would be happy if all the commands had a description. It may duplicate the description from the list.

**Comment by potiuk** [comment]
Agree. I have now similar approach for Breeze's commands :)

**Comment by tedmiston** [comment]
I am working on an initial PR for this one.

**Comment by mik-laj** [comment]
@tedmiston  Do you need any help? This ticket already has 4 hearts, which means that people have loved these change suggestions and will be very happy when it is finished.

**Comment by mik-laj** [comment]
Due to inactivity over 30 days, I am unassigning you from this ticket. Another person can start working on it if they are interested. If you would like to continue working on it, please create a PR and I will assign you to this ticket again.
