### ISSUE TITLE
How to prevent back fill?

### ISSUE THREAD

**Issue by Tjorriemorrie** [apache/airflow#845]
Currently the `start_date` on the dag args does a back fill for all the tasks. In my situation this is extremely undesired behaviour; I'm making changes to a DAG and adding a task. I cannot seem to remove that param as it seems to be a required parameter. I already have `depends_on_past` turned off but that's irrelevant. Is there another way to prevent unnecessary back fills?

**Comment by mistercrunch** [comment]
the start_date is a task level parameter. default_args is only a collection of defaults for the tasks within the DAG, you can override any of those by passing it into the operator's constructor.

Also note that only the active DAG runs should get processed and that if you were to want that backfill behavior you may have to re-activate DAG runs
