### ISSUE TITLE
Spark version 3 does not work

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#8453]
If anyone runs into this in the future I've found out where the issue is in the spark_submit_hook.py.
Line 419 in spark submit hook

match_exit_code = re.search(r'\s*Exit code: (\d+)', line)
in spark 3.0 the line that prints the exit code is actually lower case E on "Exit code:" so this re.search will never find that value. To fix this you can simply switch the line to this
match_exit_code = re.search(r'\s*Exit code: (\d+)', line, re.IGNORECASE)
Which should also be backwards compatible.

**Comment by stijndehaes** [comment]
I fixed that in this pr: https://github.com/apache/airflow/pull/8730

**Comment by dephusluke** [comment]
@stijndehaes it seems that there are issues with your PR. You are changing 1480 files and over 500 commits.

**Comment by stijndehaes** [comment]
@dephusluke I rebased when github had problems. Rebasing again looks to have fixed it.
