### ISSUE TITLE
Add ability to sort dag list in the UI by Dag, Owner, Last Run

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#8459]
**Description**
Currently the dag list is sorted by the DAG name 

It should be possible to sort the dag list in the UI by: Dag, Owner, Last Run and allow ASC /DESC ordering.

This functionality already exist in the UI for example in: Security -> List Users.
You can sort the table by any column.

Moved from Jira https://issues.apache.org/jira/browse/AIRFLOW-6745

**Comment by scrdest** [comment]
I've started looking into this as my first issue - mind assigning it to me?

**Comment by potiuk** [comment]
Done!

**Comment by rewe52** [comment]
Hi! Do you have any progress in this task?

**Comment by uranusjr** [comment]
There’s an unfinished PR (#11652) but it’s been long enough I’d assume it’s been abandoned. Would you be interested in picking up the effort and finish the patch?

**Comment by rewe52** [comment]
I'm just a user of Airflow, not good developer and this feature may be useful for my team, it means that i can't finished this patch

**Comment by potiuk** [comment]
Let's hope someone will pick it up then.

**Comment by scrdest** [comment]
@uranusjr I'm the author of #11652; my dev environment for Airflow got corrupted over multiple rebases + some virtualenv nonsense somehow. 

I'd need to recreate a clean env for this and cherrypick the relevant changes, but I've been absolutely swamped with other engagements. If I find some time, I'll open a new PR for this.

**Comment by pierrejeambrun** [comment]
Hello guys,

Thank you @eladkal for pointing me to this issue. I would be glad to help on this one :)

Best,

**Comment by eladkal** [comment]
Since @scrdest doesnt have the time to finish i assiged to you

**Comment by potiuk** [comment]
@TryHarder01 - following your nickname. can you please open a new  issue describing it instead. It would be sillty to have the same issue solved in few different releases, and we prefer granularity, so opening an issue which is related to this one is the way to go.
