### ISSUE TITLE
Add ability to run some tasks on LocalExecutor but rest on Celery/DaskExecutor

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#8460]
is there a way to set executor per task? ie I want all tasks (except task named abc) to use celeryexecutor/daskexecutor but I want task named abc to use local executor (due to firewall only opened from master)

https://github.com/apache/airflow/pull/6725 has some relevant code, hoping it can be merged!

**Comment by potiuk** [comment]
I once added a PR for multiple executors based on queue - would you find it useful ?https://github.com/PolideaInternal/airflow/commit/6590f665d4d9aa2629052c1af2e6f4c36a9a4dd3

**Comment by tooptoop4** [comment]
can u pls merge to apache airflow repo?

**Comment by potiuk** [comment]
Well. I could resurrect it yeah. But only after I finish some of the most urgent things with CI/Kubernetes/prod image - but If you would like to pick it up till then - feel free @tooptoop4  :)

**Comment by joshowen** [comment]
Hi @potiuk I do think this is worth resurrecting.  Having a path to migrate between executors is helpful with a larger deployments, especially now that the Kube executor is a thing.  I assume I could build a custom executor to handle the executor instance routing, but making it easily configurable by dag/task is definitely preferable.

**Comment by potiuk** [comment]
We have CeleryK8SExecutor now and I think it is better to have this specialized executor rather than generic one.
