### ISSUE TITLE
DbApiHook: add chunksize to get_pandas_df parameters

### ISSUE THREAD

**Issue by wittfabian** [apache/airflow#8468]
**Description**

The method "get_pandas_df" should be extended by the parameter "chunksize".

**Use case / motivation**

For the case that very large amounts of data are read, the "chunksize" is a good way to reduce the size of individual queries.

**Links**

https://github.com/apache/airflow/blob/f4faed6eea70e34da60edcb555fffc9099d3214a/airflow/hooks/dbapi_hook.py#L123

https://github.com/pandas-dev/pandas/blob/0.25.x/pandas/io/sql.py#L344

**Comment by imorales-mosaico** [comment]
There are a problem with the chunksize, because the get_pandas_df close the connection in the first call of the iterator[DataFrame] returned

**Comment by carmoreno1** [comment]
> There are a problem with the chunksize, because the get_pandas_df close the connection in the first call of the iterator[DataFrame] returned

Hi @imorales-mosaico is there a workaround about `chunksize` using Airflow?

**Comment by potiuk** [comment]
Please @imorales-mosaico  - open a new Feature/Bug request with a bit better description, rather than commenting on a closed ticket (you can add Relates to: #8464 in the description).

**Comment by potiuk** [comment]
(Or Ideally submit a PR fixing the problem immediately - if there is a problem).
