### ISSUE TITLE
Deleting a DAG breaks webapp UI

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#847]
I'm using PyPI 1.6.2 release.

If you delete a DAG from the dags folder, the UI continues to show it. Clicking on the refresh icon doesn't make it go away. Clicking on the code link (lightning bolt) causes a 500 error. This is a rough user experience.

Bouncing the full `airflow webserver` process seems to fix the problem. Would be nice if the webserver automatically removed DAGs.

**Comment by criccomini** [comment]
Relates to https://github.com/airbnb/airflow/pull/848

**Comment by r39132** [comment]
When we deploy new DAGs, we restart both the airflow scheduler and webserver in order to reload the DAG bags in those processes. We use local executor at Agari. Our deployment automation (Capistrano) script takes care of both DAG deployment and the restart post-DAG deployment.

**Comment by bolkedebruin** [comment]
@criccomini can you create a jira for this? Imho the webserver should just refresh its own dagbag (i have working code for that)
