### ISSUE TITLE
Fix migrations 1.10.10 for MS SQL Server

### ISSUE THREAD

**Issue by ghost** [apache/airflow#8470]
**Apache Airflow version**: 1.10.10

**Environment**: 

- **Cloud provider or hardware configuration**: MS SQL Server

**What happened**:

Migrations break on uncaught ProgrammingError:
https://github.com/apache/airflow/blob/1.10.10/airflow/migrations/versions/852ae6c715af_add_rendered_task_instance_fields_table.py#L48-L49

This was fixed for another migration using this hack in:
https://github.com/apache/airflow/blob/1.10.10/airflow/migrations/versions/d38e04c12aa2_add_serialized_dag_table.py#L44-L45

**What you expected to happen**:
The ProgrammingError is caught in the same way as in https://github.com/apache/airflow/blob/1.10.10/airflow/migrations/versions/d38e04c12aa2_add_serialized_dag_table.py#L44-L45

**How to reproduce it**:
Run migrations on a fresh MSSQL Server Database

**Related JIRA ticket of previous bug report**:
https://issues.apache.org/jira/browse/AIRFLOW-6366

**Comment by elwinarens** [comment]
Already fixed in the master branch. Closing
