### ISSUE TITLE
Add InitContainers for KubernetesExecutor

### ISSUE THREAD

**Issue by jonathonbattista** [apache/airflow#8479]
**Description**

Allow the KubernetesExecutor to spawn an Init or Sidecar Container in the Worker Pod before running the DAG.

**Use case / motivation**

Since the KubernetesExectuor overrides the container command, we need to be able to run some logic to config the Worker Pod's environment before running the DAG.  i.e. Pull environment-specific files.

Currently, we are doing this at the DAG-level which is not ideal and we don't want to do this when building the Docker image and manage environment-specific Docker images.

**Comment by jonathonbattista** [comment]
Any update on this?

It would be super useful to be able to run custom logic before the worker pod runs!

**Comment by jedcunningham** [comment]
@jonathonbattista, this is now possible with [pod_template_file](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#pod-template-file).
