### ISSUE TITLE
Allow configuration of args vs command to support container entrypoint in kubernetes executor

### ISSUE THREAD

**Issue by dmayle** [apache/airflow#8495]
**Description**
Please add an option to the kubernetes config to support using a container entrypoint.  Right now, the kubernetes executor runs the worker and sets the command option on the pod.  This overrides the container's entrypoint, which prevents scripts from properly setting up the airflow environment.

**Use case / motivation**
Some airflow containers (notable puckel/docker-airflow) use an entrypoint to properly setup the airflow environment.  This allows things like constructing the SQL Alchemy connection string from database parameters.

**Related Issues**
Not in Airflow (there's a similar issue in Spark)

**Other**
The most likely place to fix this is in worker_configuration.make_pod, checking a value from kube_executor_config.  If 'use_entrypoint' is set, then the airflow command would be passed to the 'args' parameter, and the command would be left empty.

**Comment by matthieu-foucault** [comment]
@dmayle Ran into that issue as well when trying to run airflow on an OpenShift cluster (which requires some setup when starting a pod). 
Our workaround was to rename the airflow executable in the docker image and add a shell script in the PATH that does whatever setup is needed before calling airflow

**Comment by humbledude** [comment]
https://github.com/apache/airflow/blob/72d5a58fd734cf4a02e351210b7db5ae2fae7e4e/airflow/executors/kubernetes_executor.py#L470

this could be "args"...

**Comment by mik-laj** [comment]
@dmayle @matthieu-foucault @humbledude Would you like to contribute this change to the project? This looks like a much needed change so I'd love to help with the review.

CC: @dimberman

**Comment by dszakallas** [comment]
I need this feature as well. As an alternative to what @humbledude proposed we could assume that the docker image has a command (docker entrypoint) that 'behaves like airflow' and only specify the airflow command's args in the arg field so that when the flag enabling this feature is set we send sth like:
```
"command": [],
"args": ["run", "my-dag", "my-task", ...]
```

**Comment by cris-b** [comment]
This was fixed in master under  #12766

**Comment by dimberman** [comment]
This is fixed in master and should be released as a part of either 2.0.1 or 2.0.2
