### ISSUE TITLE
New boolean property in dag to prevent multi concurrent execution dates

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#8520]
I want to be able to prevent the same Dagid running for multi exec dates at same time. For example DagA runs every hour I don't want the 3pm run to schedule tasks if the 2pm run is still running.

I know max active dag runs is similar but it affects all dags, I want to be able to specify per dagid.

Pools only operate at task level but I want to operate at dag level, in first come first serve basis, so I don't wan't to timeout the 2pm run after 60mins.

**Comment by ashb** [comment]
Sorry for missing this issue when you first created. This has been possible for a long time with `DAG.max_active_runs`:

```python
dag = DAG(dag_id="my_dag", max_active_runs=1)
```
