### ISSUE TITLE
Json Parse Error in Tree View

### ISSUE THREAD

**Issue by qzheng1989** [apache/airflow#8523]
**Apache Airflow version**: 1.10.10

**What happened**:
When DAG is triggered with custom configuration that contains escape characters in a json variable value, tree view will fail to load due to json parse error at https://github.com/apache/airflow/blob/master/airflow/www/templates/airflow/tree.html#L139

**What you expected to happen**:
Tree view should load

**How to reproduce it**:
Create any simple dag and trigger with api call or on UI and provide following as configuration.
```
{
     "abc": "this is simple message\n"
}
```

The new logic in tree view will turn above json into string, then trying to parse it out.
<img width="392" alt="Screen Shot 2020-04-22 at 6 44 11 PM" src="https://user-images.githubusercontent.com/1458754/80041001-4b02f780-84c9-11ea-97ff-44e78a4b774e.png">

**Anything else we need to know**:
Introduce in https://github.com/apache/airflow/pull/7492

**Comment by kaxil** [comment]
cc @houqp

**Comment by houqp** [comment]
Thanks @kaxil for the tag, I will look into this. It should escape all json strings.

**Comment by houqp** [comment]
turns out escape sequence itself is not escaped, @qzheng1989 feel free to test out my fix in #8551.

**Comment by kaxil** [comment]
Thanks @houqp . @qzheng1989 Fix will be available in Airflow 1.10.11
