### ISSUE TITLE
'Last Run' column empty for Viewer role in RBAC UI

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#8526]
In 1.10.9 with RBAC UI, and a user who has the Viewer role, the 'Last Run' column on main dags page is empty. It is present for user with Admin role though.

Seems can_last_dagruns "can last dagruns on Airflow" permission is only Admin, should it be on Op, User, Viewer ?

**Comment by thesuperzapper** [comment]
I have made PR #9133 to fix this
