### ISSUE TITLE
Relative paths get wrong expansion

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#8527]
I generate some dags from json config file. It's a common use case arround. When I load this config file I have to write the whole path (seen in many blog posts and SO answers). If I try a relative path the expansion is made in relation to another path

If in my `/opt/airflow/dags/mydags_reppo/mydag_file.py` I was to use:
```python
config_path = os.path.abspath('config.json')
with open(config_path,'r') as file:
  config = file.read()
```
Airflow will throw the following error:
```
No such file or directory '/opt/airflow/config.json'
```
Well, of course not. The file is not there. I could trick it using something like
```python
base_dags_path = os.getenv('AIRFLOW__CORE__DAGS_FOLDER', conf.get('core','dags_folder'))
config_path = f'{base_dags_path}/mydags_repo/config.json'
# read file from config_path
```
But maybe there's an easier way, or maybe the way airflow expands the path can be changed

**Comment by ashb** [comment]
Yeah, this is not something we are likely to change -- generally you shouldn't expect any python file to be run from a specific directoyr, and the suggestion Kamil gave is the way to account for that in a resilient manner.

**Comment by dinigo** [comment]
thanks @mik-laj ! great solution. Sorry for generating overload with this sort of thing
