### ISSUE TITLE
"TypeError: can't pickle _thread.RLock objects" on usage of BigQueryOperator

### ISSUE THREAD

**Issue by ImadYIdrissi** [apache/airflow#8541]
**Apache Airflow version**:1.10.2

**Kubernetes version**: 1.14.10-gke.27

**Environment**: GC Composer

- **Cloud provider or hardware configuration**: GCP

**What happened**:  The "clear" option crashes the UI.

**error messages**: TypeError: can't pickle _thread.RLock objects

**What you expected to happen**: I expect airflow to clear the task and its dependencies, then re-run the task. 

**What do you think went wrong?**: When I try to include a `BigQueryOperator` from `airflow.contrib.operators.bigquery_operator` in my DAG, the error occurs.

**How to reproduce it**: I am not sure how to reproduce this error in any other environment. Please find the video explaining the bug in the following link : [Video explanation of the bug](https://youtu.be/jIHLCmQcXTs)

**How often does this problem occur?**  Every time I try to add the `BigQueryOperator` to this particular DAG.

**Probably similar Issues** : 
 - [AIRFLOW-351](https://issues.apache.org/jira/browse/AIRFLOW-351)
 - [AIRFLOW-4496](https://issues.apache.org/jira/browse/AIRFLOW-4496?jql=project%20%3D%20AIRFLOW%20AND%20text%20~%20%22TypeError%3A%20can%27t%20pickle%20_thread.RLock%20objects%22)
<details><summary>UI Crash Logs</summary> Ooops.

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: 788ee3e5c207
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python3.6/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/python3.6/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/python3.6/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/python3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/python3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/python3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/python3.6/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/opt/python3.6/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/opt/python3.6/lib/python3.6/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/airflow/airflow/www/utils.py", line 281, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/airflow/airflow/www/utils.py", line 328, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/airflow/airflow/www/views.py", line 1166, in clear
    include_upstream=upstream)
  File "/usr/local/lib/airflow/airflow/models.py", line 4166, in sub_dag
    dag = copy.deepcopy(self)
  File "/opt/python3.6/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/airflow/airflow/models.py", line 4151, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/airflow/airflow/models.py", line 2874, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/opt/python3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/python3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/python3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/python3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/opt/python3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/python3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python3.6/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects</details>

**Comment by ImadYIdrissi** [comment]
Yeah, it turns out I forgot to upload the SQL SCRIPT that the `BigQueryOperator` uses... I believe there should be a clear `FileNotFound` exception instead of a UI crash.

**Comment by mik-laj** [comment]
Does this problem still occur in Airflow in the master branch? We have introduced a lot of changes and improvements in GCP operators and I think that this problem may have already been solved.

**Comment by ImadYIdrissi** [comment]
@mik-laj Isn't the master branch at the version 1.10.10? If so, probably the bugs have been solved. But since Composer is still at V 1.10.3, then possibly these issues will again occur. I am seriously thinking of deploying my own VM or Cluster and use airflow on it. Although a managed service sounds good in theory, the overhead spent on trying to fix already fixed problems is still getting higher.

**Comment by juzov-mag** [comment]
1.10.9 still has this issue, or so I believe. What version solves this issue?

**Comment by dgies** [comment]
Confirmed this is still an issue in the latest Composer release, `composer-1.12.0-airflow-1.10.10`
Any attempt to clear tasks using downstream fails if the DAG uses GCP Dataproc operators.
Can also reproduce through the CLI using `gcloud composer environments run $COMPOSER --location $LOCATION clear -- $DAG -t $TASK --downstream`

An ugly workaround is to clear the entire DAG Run by omitting `-t $TASK --downstream`

**Comment by mik-laj** [comment]
Does this problem also occur when the operator from airflow.providers is used?  The operators from airflow.contrib have known issues, so it is recommended to migrate to airflow.providers ..

**Comment by dgies** [comment]
> Does this problem also occur when the operator from airflow.providers is used? The operators from airflow.contrib have known issues, so it is recommended to migrate to airflow.providers ..

I'd already tried using ` airflow.providers.google.cloud.operators.dataproc` and it failed the same because in later releases the old `airflow.contrib.operators.dataproc_operator` now imports airflow.providers and  subclasses/decorates them with a deprecation warning.

**Comment by MatteoMart1994** [comment]
Is there any update on this issue? Still experiencing with composer-1.10.4-airflow-1.10.6 version

**Comment by stephenonethree** [comment]
I also started experiencing this issue on `composer-1.16.3-airflow-1.10.15` as well as `composer-1.16.1-airflow-1.10.15`. In my case I'm not technically using BigQueryOperator but I added a custom operator which loads to BigQuery (Relevant import `from google.cloud import bigquery`). Until I added that operator to my latest DAG I didn't have problems clearing tasks, then once I added it I started getting the error message.

I'm going to dig into this a bit more next week and will let you know if I find more relevant details, but for now just wanted to note that I think the issue may be ongoing.

I found this PR via https://issues.apache.org/jira/browse/AIRFLOW-351 and then https://github.com/apache/airflow/issues/7929

**Comment by stephenonethree** [comment]
Incidentally in my case I had accidentally passed a parameter to one of my custom operators that was almost certainly not pickleable (I passed another operator to that operator, instead of a string). Then, I fixed that issue and went back to passing a string. The bad code is nowhere to be seen at this point but I still have the issue. Is there any sort of parameter history that might still be lurking in the database or something that could be causing this problem? Just a shot in the dark.

**Comment by stephenonethree** [comment]
Incidentally, I tried deleting the entire dag using the deletion button from the main DAG page list, which as expected based on the description of that button removed the dag and then caused it to show up again when I refreshed in a second (because I had intentionally not deleted the .py). However, after testing I continued to get the same error when trying to clear statuses downstream/recursive. I guess this might rule out some possible causes.

**Comment by stephenonethree** [comment]
Ok, I think I might have actually found the cause. Unlike other people who have reported this error message, in my case I traced the error to a very specific configuration: I had a single SubDag with direct upstream dependencies on 2 other SubDags. Attempting to clear the status of that SubDag (the downstream one) caused this error. I was able to stop this error by reworking the dependencies so that no SubDag directly depended on more than 1 other SubDag.

It looks like, in my case, this had nothing to do with directly passing a non-pickleable parameter to a Dag or Task.

Sorry for all the spam, but I hope this latest update helps anybody who wants to look into this (or finds this while Googling).

**Comment by zachliu** [comment]
in my case, on `composer 1.13.0 airflow 1.10.12`, this error occurs when i use a for-loop:
```python
downstream_task_1 = SomeOperator()
downstream_task_2 = SomeOperator()
for i in range(x):
    task = SomeOperator(
        task_id=f"task_{i}"
    )
    task >> downstream_task_1 >> downstream_task_2
```
strangely, i had to
```python
downstream_task_1 = SomeOperator()
downstream_task_2 = SomeOperator()
for i in range(x):
    task = SomeOperator(
        task_id=f"task_{i}"
    )
    task >> downstream_task_1
downstream_task_1 >> downstream_task_2
```
otherwise downstream_task_2 will give me the nuke

**Comment by eladkal** [comment]
does this issue happen on latest airflow version?
