### ISSUE TITLE
Production Docker Image - quick start

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8542]
**Description**

Hello

We miss the quick start guide that will allow you to quickly launch Airflow from the official image.
For now, we only have a guide that describes how to install Airflow using Pip.
https://airflow.readthedocs.io/en/latest/installation.html

In a perfect world, I'd see the following pages:
* **Installation** - general information and general information and comparison of PIP and Docker. Notes on Conda are also possible.
  * **Quickstart for Pip**  - similar page to the current page, but without the "Extra packages" tables and a reference to another page instead.
  * **Quickstart for Docker** - The most important thing is that there are commands that will allow you to run a simple DAG (I success criteria) and log in to the webserver (II success criteria).
  * **Extra packages**  - Tables with extra packages.

However, I will be happy even if someone describes and prepares commands that will allow you to run the Docker image and meet 2 success criteria.

Best regards,
Kamil Breguła

CC: @potiuk 

Should also be connected with #8578

**Comment by potiuk** [comment]
Yep. this is planned. I am gathering feedback from users in https://apache-airflow.slack.com/archives/CQAMHKWSJ and hopefully we will get useful feedback and PRs from those discussions. Feel free to join :). I really want to get users to tell us how they are going to use it. If you want you can contribute too.

> * **Extra packages**  - Tables with extra packages.
I think we already have this? Don't wee

**Comment by mik-laj** [comment]
@potiuk I think that now it should be a separate subpage. We have a guide for PIP, which contains these tables, but if Docker will use it, you can move these tables to a separate subpage.
