### ISSUE TITLE
Is 1.10.10 version still saving the variable to the table? or is it only available as environment variable?

### ISSUE THREAD

**Issue by atejano** [apache/airflow#8543]
**Do not use issues for support requests or general help queries**

Please ask on one of our mailing lists, or in our Slack channel. See the "Ask a question" section of http://airflow.apache.org/community/

Issues which are not bug reports or feature requests (i.e. "how do I get X working", or "How do I best do X?") will likely be closed without a response.

**Comment by potiuk** [comment]
> **Do not use issues for support requests or general help queries**
> 
> Please ask on one of our mailing lists, or in our Slack channel. See the "Ask a question" section of http://airflow.apache.org/community/
> 
> Issues which are not bug reports or feature requests (i.e. "how do I get X working", or "How do I best do X?") will likely be closed without a response.

Please read the content of the issue.
