### ISSUE TITLE
Not able to trigger the DAG using api in 1.10.10

### ISSUE THREAD

**Issue by mnishesh** [apache/airflow#8547]
Actual : even though the response status is 200 we are not able to trigger the DAG using POST API.
same code is working fine in 1.10.9
expected :- API should be able to trigger the DAGS.

code snippet 
import unittest
import requests
import time
import xmlrunner

class FunctionalTest(unittest.TestCase):
     def test_import_dags(self):
    
        headers = {
            'Cache-Control': 'no-cache',
            'Content-Type': 'application/json'}

        resp1 = requests.get('ocp_url/api/experimental/dags/Functional_Test_New/paused/false',verify=False)
        print(resp1.text) 
        
        resp = requests.post('ocp_ur/api/experimental/dags/Functional_Test_New/dag_runs',verify = False,headers=headers,json='')
        
        print(resp.status_code)
        print(resp.text)    
        time.sleep(60)
        file = open("C:/Work/airflow/dags-master/DAGBAG/results/relative_testfileNew.txt", "r")
        str1 = file.readline()
        file.close()
        
        self.assertIn('testNew\n',str1,'Expected Value not matched with Real Value')
        #print(str1)
runner = xmlrunner.XMLTestRunner(output='test-reports')
unittest.main(testRunner=runner)

console 
Running tests...
----------------------------------------------------------------------
C:\Users\AD78762\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{"response":"ok"}

C:\Users\AD78762\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
200
[{"dag_id":"Functional_Test_New","dag_run_url":"/admin/airflow/graph?dag_id=Functional_Test_New&execution_date=2020-04-22+00%3A00%3A00%2B00%3A00","execution_date":"2020-04-22T00:00:00+00:00","id":1,"run_id":"scheduled__2020-04-22T00:00:00+00:00","start_date":"2020-04-23T17:35:50.034826+00:00","state":"success"},{"dag_id":"Functional_Test_New","dag_run_url":"/admin/airflow/graph?dag_id=Functional_Test_New&execution_date=2020-04-23+00%3A00%3A00%2B00%3A00","execution_date":"2020-04-23T00:00:00+00:00","id":4,"run_id":"scheduled__2020-04-23T00:00:00+00:00","start_date":"2020-04-24T00:00:05.641065+00:00","state":"failed"},{"dag_id":"Functional_Test_New","dag_run_url":"/admin/airflow/graph?dag_id=Functional_Test_New&execution_date=2020-04-23+19%3A38%3A19.698230%2B00%3A00","execution_date":"2020-04-23T19:38:19.698230+00:00","id":2,"run_id":"manual__2020-04-23T19:38:19.698230+00:00","start_date":"2020-04-23T19:38:19.711872+00:00","state":"success"},{"dag_id":"Functional_Test_New","dag_run_url":"/admin/airflow/graph?dag_id=Functional_Test_New&execution_date=2020-04-23+21%3A00%3A44.794903%2B00%3A00","execution_date":"2020-04-23T21:00:44.794903+00:00","id":3,"run_id":"manual__2020-04-23T21:00:44.794903+00:00","start_date":"2020-04-23T21:00:44.806646+00:00","state":"failed"}]

.
----------------------------------------------------------------------
Ran 1 test in 73.578s

OK

Generating XML reports...

**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by ashb** [comment]
The experimental API is now replace in 2.0 with a fully specified OpenAPI-based API https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html
