### ISSUE TITLE
[Umbrella] Add Docker compose example

### ISSUE THREAD

**Issue by yordis** [apache/airflow#8548]
Would be amazing to add some example on how to set up Airflow with the new image using Docker Compose.

Example:
- https://github.com/bitnami/bitnami-docker-airflow

Updated by @potiuk :  moved the example to #8605 together with other examples from Slack.

**Comment by resdevd** [comment]
I’ve created a repo with Docker Compose boilerplate with official Airflow Docker images.

https://github.com/resdevd/docker-compose-airflow

**Comment by potiuk** [comment]
I think w would like all this to be eventually part of the Airflow repo. Ther is no point in having separate repos if this all can be added to the official airflow one. It should be all community managed. Can you @resdevd make a PR to the main Airflow repo. I am happy to comment on that.

**Comment by resdevd** [comment]
@potiuk Ofcourse, I've created that repo mainly for my personal preference and usecase. 
Feel free to use the above docker-compose code and modify if necessary. 
Alternatively I can happily contribute the code to main Airflow repo next week and let community direct the docker-compose boilerplate.

**Comment by potiuk** [comment]
That would be great if you contribute. I will take a look at  a few of the sources we have and try to split the changes needed into github issues and will welcome some contributions there :)

**Comment by potiuk** [comment]
Comment - treat this as an "Umbrella task' - I split it into two separate issues for now #8605  and 8606 as those two will likely be implemented separately.

**Comment by ryw** [comment]
Moved milestone to to 2.1 since this doesn't block release of 2.0.

**Comment by kaxil** [comment]
This has been done, closing it out
