### ISSUE TITLE
Support YAML input for CloudBuildCreateOperator

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8567]
**Description**

Hello,

We have an operator that allows us to run build in the Cloud Build service.
https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/google/cloud/operators/cloud_build.py
Unfortunately, this operator did not allow easy use with YAML files. It is a common format for this service
https://cloud.google.com/cloud-build/docs/build-config#yaml
I think we should add the possibility to pass the path to the file from which the definition will be loaded.
We have a similar feature in SparkKubernetesOperator.
https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py
https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/cncf/kubernetes/example_dags/example_spark_kubernetes_operator_spark_pi.yaml
https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/cncf/kubernetes/example_dags/example_spark_kubernetes_operator.py#L63-L70

If anyone wants to do this task, please remember to update system tests and documentation.

If you haven't used the GCP yet, after creating the account you will [get $300](https://cloud.google.com/free).
If you already have an account, you can use [Free Tier](https://cloud.google.com/free). This gives you 120 Build-minutes per day for free.

The implementation of this task will allow a better understanding of GCP services, as well as learn methods of testing that is required by the community. If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Best regards,
Kamil

**Comment by joppevos** [comment]
@mik-laj Happy to pick up this task. Do you mean adding an extra argument to be able to pass the filepath or adjusting the current `body` variable to also accept a filepath instead of only dict builds?

**Comment by mik-laj** [comment]
@joppevos Use the current argument again if possible.

**Comment by mik-laj** [comment]
@joppevos  How are you? Do you have any more questions?

**Comment by joppevos** [comment]
@mik-laj thanks for asking. I got stuck at the system-test and I forgot/was afraid to ask :)
How do I write a system test with a local YAML. Were should I place this or what is the best practice for it. 
I tested the implementation of accepting a build yaml config like this now. :
`dct = '''
steps:
- name: 'ubuntu'
  args: ['echo', 'hello airflow!']
'''
with open('/tmp/example.yaml', 'w+') as f:
    f.write(dct)

CloudBuildCreateOperator(task_id='examplebuild',
                         body='/tmp/example.yaml',
                         dag=dag)`

 I understand it is probably not how it should be tested, would appreciate if you can point me in the right direction

**Comment by mik-laj** [comment]
@joppevos Your file should be located next to the file with an example DAG, so it will be this directory. https://github.com/apache/airflow/tree/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/google/cloud/example_dags
After that you can refer to the file in the DAG file.

We already have a similar case with the Spark Kubernetes operator.
https://github.com/apache/airflow/tree/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/cncf/kubernetes/example_dags
