### ISSUE TITLE
Rewrite Google Cloud Build integration to use the native library.

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8568]
Hello,

We have an operator that allows us to run build in the Cloud Build service.
https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/google/cloud/operators/cloud_build.py
Unfortunately, this operator uses the old library, which is based on the discovery API.
https://github.com/googleapis/google-api-python-client
We should migrate to the new native library.
https://googleapis.dev/python/cloudbuild/latest/gapic/v1/api.html

If you haven't used the GCP yet, after creating the account you will [get $300](https://cloud.google.com/free).
If you already have an account, you can use [Free Tier](https://cloud.google.com/free). This gives you 120 Build-minutes per day for free.

The implementation of this task will allow a better understanding of GCP services, as well as learn methods of testing that is required by the community. If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Best regards,
Kamil

**Comment by ryanyuan** [comment]
@mik-laj I just created a PR for this. :)

**Comment by eladkal** [comment]
hey @ryanyuan do you wish to complete the PR?

**Comment by ryanyuan** [comment]
Hey @eladkal, I do. I pinged the reviewers lots of times but no one reviewed it. Hence it’s closed.

**Comment by eladkal** [comment]
> Hey @eladkal, I do. I pinged the reviewers lots of times but no one reviewed it. Hence it’s closed.

Sorry for that. I'll help with the review :)
You can either reopen the closed PR and rebase it or open a new PR.

**Comment by potiuk** [comment]
Yeah. Sorry for that.  I missed that one too - happy to review @ryanyuan . It happens sometimes that we miss a  PR or two in a flood of them :D.

**Comment by ryanyuan** [comment]
Hi @eladkal , @potiuk . Yeah all good! I understand there have been so many PRs coming in last 2 years.

I'll reopen my PR and check my code again. I may need to take a week or 2 to compare my code with the latest api code and doc to see if there are anything I need to update.

**Comment by potiuk** [comment]
🙏

**Comment by eladkal** [comment]
Thank you @ryanyuan 🙏
