### ISSUE TITLE
Docs: cron preset table is not rendering properly

### ISSUE THREAD

**Issue by seancron** [apache/airflow#857]
As seen at http://airflow.readthedocs.org/en/latest/scheduler.html#dag-runs the cron presets table is not rendering correctly.

At a glance, the `scheduler.rst` file seems to be fine, and renders correctly on Github. Might be as simple as adding an extra newline preceding the table, but have not setup a dev environment to test this.

**Comment by mistercrunch** [comment]
I've been having issues getting readthedocs to build Airflow lately. The main docs version is here:
http://pythonhosted.org/airflow/scheduler.html 

I haven't had time to dig in. Would love if anyone could figure out how to get readthedocs to build this package properly without attempting to install `requirements.txt`
