### ISSUE TITLE
Release the first set of backport packages

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8582]
**Description**

As discussed in https://lists.apache.org/thread.html/r9a4781b60a2a6a2ed3ea11ecfe3b610f2e515fefdfdfbd30c75215e0%40%3Cdev.airflow.apache.org%3E 

We decided to released backport packages without the hard requirement on system tests. 

**Use case / motivation**

Preparing system tests for all packages is a burden (even though we already have 66% of them - all google packages) done. This will only pay-off once we automate the execution of the system tests a described in  [AIP-4](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+Automation+of+System+Tests+for+external+systems). For now the general conclusion is that we should release all the packages as CALVER releases relying on the fact that they are unit tested. Since this is an optional feature for Airflow 1.10.* series, users will be able to test those new packages and report any problems. Before Airflow 2.0 is released.

**Related Issues**

There were related issues to prepare each package separately with system tests but they are closed now: https://github.com/apache/airflow/issues?q=label%3Aarea%3Abackport-packages+is%3Aclosed

**Comment by kaxil** [comment]
After our discussion:

- Our Release Guide: https://cwiki.apache.org/confluence/display/AIRFLOW/Releasing+Airflow - This has details (or links to other docs) on how to create your GPG KEYS and upload them to https://dist.apache.org/repos/dist/release/airflow/KEYS. And has the details of the actual release process. Feel free to create a separate section (or a Subpage) for releasing the Backport package.
- Our normal RC Voting rules apply
- Versioning: CALVER (YYYY-MM-DD) 
- Release backport packages for all the providers for the first one. After that they can be released individually
- Docs: The Readme inside each Provider backport package will contain details about the list of new Operators/Hooks/Secrets etc
- ReadtheDocs: Create a new page that shows all the Backport Packages that were released with Changelogs (We should not add this page on airflow.apache.org doc site, so may be add a RTD env var to ignore - ???)
- Have 'backport' in the name (e.g apache-airflow-provider-google-backport) of the final release candidate and the package to future-proof us if we ever separate the provides folder to separate repos
- Create separate folder for each provider 'downloads.apache.org/airflow/backport-providers/$provider/$ver/$x.whl'
- To get files in to downloads.apache.org we do it via SVN, and we should obviously upload it to dev/ first (which is what your release guide says to do)
- We will have a single Git Tag for each Backport Release (e.g backport-provider-2020-04-27) can have multiple providers released under it but a Single Git Tag

**Comment by ashb** [comment]
Done!
