### ISSUE TITLE
Rename extra module `apache-airflow[gcp]` to `apache-airflow[google]`

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#8583]
In the official docs as in the development we use the command`pip install apache-airflow[gcp]`to install `google` hocks and operators.

Now in the `master` (2.0) this extra installs tools for:
- Google Cloud
- Google Suite
- Google Ads
- Google Marketing cloud

Can we replace `gcp` extra for `google` name in the documentation and the packaging setup in airflow v2.0?

**Comment by potiuk** [comment]
Yep. I think it's the right time to do it :)

**Comment by ashwinshankar77** [comment]
@turbaszek I will take a stab at this one
