### ISSUE TITLE
Add Airtable Hook

### ISSUE THREAD

**Issue by hagope** [apache/airflow#8589]
**Description**

[Airtable](https://airtable.com/) is powerful and intuitive service that allows users to build complex data structures and layers in tons of other features in the form of "blocks."

**Use case / motivation**

Its important for Airflow to connect to apps in which business users are inputting data in a structured manner. I've previously implemented the [Google Sheets hook](https://github.com/apache/airflow/pull/5845) which we are putting to good use at Coursera and hopefully elsewhere. I believe Airtable could be used similarly for loading/reading "bases" (tables).  Implementation seems pretty straightforward, with clean [api](https://airtable.com/api)

One potential use case I'd like to explore is using Airtable as an entry point for DAG creation, it has a very good UI/UX and could potentially provide a "no-code" solution to getting DAGs up and running with Airflow.

-->

**Related Issues**

[[AIRFLOW-5158] Add Google Sheets hook](https://github.com/apache/airflow/pull/5845)

**Comment by turbaszek** [comment]
Hi @hagope thanks for the issue! Would you like to work on it?

**Comment by samrogers226** [comment]
I would be happy to take this - I've actually already built a bit of custom code to integrate our stack with Airtable and could benefit from this. 

@turbaszek feel free to list me as the assignee.

**Comment by turbaszek** [comment]
@samrogers226 awesome! Ping me if you need any reviews :)

**Comment by eladkal** [comment]
@samrogers226 are you still working on this issue?

**Comment by josh-fell** [comment]
@turbaszek  @eladkal I'd love to hack away at this.

**Comment by eladkal** [comment]
Airtable has python sdk which seems maintained: https://github.com/gtalarico/pyairtable
so for anyone who wants to pick it up it should be easier to integrate with the Python SDK.
You can check previous PRs of adding new provider for reference like: https://github.com/apache/airflow/pull/17068 to

**Comment by eladkal** [comment]
Due to time passed and the fact that no one expressed interest in this provider I'm closing this request.
Providers can be added as 3rd party (it doesn't have to be in Airflow repo) https://airflow.apache.org/ecosystem/#third-party-airflow-plugins-and-providers
If anyone thinks there is a reason to add this provider to Airflow and is willing to maintain it please open a thread on the mailing list first.
