### ISSUE TITLE
Airflow DAGs On/Off toggle button not working properly with RBAC=True mode

### ISSUE THREAD

**Issue by ytiam** [apache/airflow#8599]
I am using an AWS ec2 instance and installed apache-airflow there. Following steps, I am doing in that instance,
 1) After initiating airflow with 'airflow initdb', I created a user with **Admin** role using 'airflow create_user' option and  in airflow.cfg changed rbac = True. 
2) Again ran 'airflow initdb' and 'airflow webserver'. It initiated the webserver.
3) In another tab,  run 'airflow scheduler'
4) Then using port-forwarding to port forward the 8080 port from the ec2 instance to my local machine
5) In my local browser, I am just opening localhost:8080/
6) On Airflow login page, putting credentials of the Admin user, I logged in into Airflow
7) After toggling ON a dag from UI, when I am refreshing the page or clicking on some other option, the DAG toggling button is automatically turning OFF. and hence I am not able to run any DAG

![image](https://user-images.githubusercontent.com/13828878/80454358-8bd69280-8947-11ea-9fbf-e63b20e09d9b.png)

The button I am talking about is on the left side of the DAG name.

Please help anyone

**Comment by pradige** [comment]
I'm on the same with u 
maybe y can see response
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF token is missing.</p>

i'm trying to figure it out but nothing to do right now

**Comment by ytiam** [comment]
No Clue I am getting, whats the issue exactly happening behind

**Comment by ytiam** [comment]
The following issue looks similar to ours:
https://issues.apache.org/jira/browse/AIRFLOW-2866

**Comment by Adam-Leyshon** [comment]
This is caused by the latest release of Flask-AppBuilder 2.3.3 which updated jQuery to 3.5
Downgrading to FAB 2.3.2 solved it for us.

**Comment by ytiam** [comment]
Voila...:D Downgrading to FAB 2.3.2, worked. Thanks a lot @Adam-Leyshon

**Comment by pradige** [comment]
@Adam-Leyshon 
thank you . it also work for me ^^

**Comment by ryw** [comment]
@ryanahamilton want to look at this?
