### ISSUE TITLE
[SQL Server]'JSON_VALID' is not a recognized built-in function name

### ISSUE THREAD

**Issue by martinskeem** [apache/airflow#8611]
**Apache Airflow version**:1.10.10
**What happened**: Not able to run upgradedb

It seems that there's a regression of this bug, specifically pertaining to SQL Server, which does not support "JSON_VALID": https://issues.apache.org/jira/browse/AIRFLOW-6366

Resulting in this error during "airflow upgradedb":

Apr 28 14:58:40 devaf1-dk1.sys.dom airflow[43060]: sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'JSON_VALID' is not a recognized bu...QLExecDirectW)")
Apr 28 14:58:40 devaf1-dk1.sys.dom airflow[43060]: [SQL: SELECT JSON_VALID(1)]

**Comment by 2dor** [comment]
Any updates on this?

**Comment by martinskeem** [comment]
I believe this will be resolved (again) in 1.10.11: https://github.com/apache/airflow/pull/8385
