### ISSUE TITLE
Production Docker Image AIRFLOW_INSTALL_VERSION does not overwrite AIRFLOW_VERSION environment variable

### ISSUE THREAD

**Issue by ldacey** [apache/airflow#8612]
**Apache Airflow version**: 1.10.10

**What happened**:
When I look at environment variables within my Airflow containers, I see `AIRFLOW_VERSION="2.0.0.dev0"`

**What you expected to happen**:
Since I built the image with `AIRFLOW_INSTALL_VERSION="==1.10.10" `, I would expect any reference to the Airflow version to reflect 1.10.10 and not 2.0.0.

**How to reproduce it**:
Build an image with a specific AIRFLOW_INSTALL_VERSION and then exec into it and printenv or inspect the container and you will see `AIRFLOW_VERSION="2.0.0.dev0"`. It does not appear like this env var impacts anything and it is hard coded to 2.0.0.dev0 at the moment. Most likely, this variable should be replaced with the AIRFLOW_INSTALL_VERSION instead.

```
docker build . \
--build-arg AIRFLOW_INSTALL_SOURCES="apache-airflow" \
--build-arg AIRFLOW_INSTALL_VERSION="==1.10.10" 
```

/label area:production-image

**Comment by potiuk** [comment]
I finally looked at it - there is not an easy way to do it automatically. I just updated breeze to automatically set, and updated the documentation and examples to clarify that whenever you run AIRFLOW_VERSION, you should also specify AIRFOW_VERSION build arg. PR #12875
