### ISSUE TITLE
Profile worker hostname to celery executor for command fail

### ISSUE THREAD

**Issue by YingboWang** [apache/airflow#8619]
**Description**
Add hostname to the celery command failed exception information. Pass it to executor event_buffer as info field. So we know which host is having issue from scheduler log and will be able to handle these executor events more efficiently.

**Use case / motivation**
When there is an inconsistency between executor event return state and DB state. It is hard to debug the root cause and for celery executor we need to query logs from all workers. The reason is that at this time DB hostname was not updated and we don't know which worker have picked up the task and caused the failure. If we have the hostname with the executor event, we will be able to identify the host and debug root cause on that host. It could reduce time and operations to find out problematic host.

**Related Issues**

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/8624
