### ISSUE TITLE
Transfer operators and division into providers

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8620]
Hello,

Somewhere we need to include a summary of the [AIP-31](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths)
I don't have an idea yet, but I'm saving my note.

> The transfer operator should be included in the package according to the destination :
> Example: ``HTTPToMySQL`` should be in ``airflow.providers.mysql``
> However, if one of the side is a large cloud provider or a large foundation, e.g. Google, Apache, CNCF, then you should put it in the provider's package.
> Example: ``GCSToMySQL`` should be in ``airflow.providers.googlle``
> If there is a large cloud provider on both sides then it should be placed according to the destination.
> Example: `GCSToS3` should be in airflow.providers.amazon
> 

Best regards,
Kamil

**Comment by potiuk** [comment]
I will add some doc changes alongside  releasing first batch of backport packages.

**Comment by mik-laj** [comment]
@potiuk Fantastic!  Let me know if you start work. I will be happy to help with reviews.

**Comment by mik-laj** [comment]
Done: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#naming-conventions-for-provider-packages
