### ISSUE TITLE
Triggering a DAG for a future run(s) stops the intermediate scheduled run(s)

### ISSUE THREAD

**Issue by aishusan** [apache/airflow#8628]
- Airflow Version: 1.10.9 (We tried it across other versions too, but we see the same behavior!)
- Python Version: 3.6.0
- DAG schedule: Every 1 hour once. 
- OS: Mac OS 
- Kernel: Darwin Kernel Version 18.7.0
- Environment:Local/GCP
- Kubernetes: Not applicable. We run the plain vanilla version of Airflow using pip installation. 

**Issue:**

**At 11.00AM** 

We triggered a DAG in UI to be scheduled for 2.05 PM (Below are the details)

**At 02.30 PM** 

The job that was scheduled for 2.05 PM ran successfully but we didn't see the 12.00 PM, 1.00 PM and 2.00 PM job's DAG Runs which was supposed to run as per the schedule. 
After the 2.05 PM job ran successfully, the rest of the jobs in the schedule seem to run as expected. Say the ones that were supposed to run at 3.00 PM, 4.00 PM, etc. 

**Details:** 
State: running
Dag Id: <dag_id>
Execution Date : 2020-04-21 14:05:00
Run Id : scheduled__2020-04-21T14:05:00+00:00

**Expectation:**

We expected the intermediate DAG Runs at 12.00 PM, 1.00 PM and 2.00 PM to run as expected but we don't see them running. 

We posted this the slack channel - https://apache-airflow.slack.com/archives/CCR6P6JRL/p1588075771175300

**Comment by eladkal** [comment]
can you please check if it still happens in master?
You are using an old airflow version and also a recent fix of https://github.com/apache/airflow/issues/13434 sounds very similar
