### ISSUE TITLE
DockerOperator cannot pull image when docker client uses json-file log driver

### ISSUE THREAD

**Issue by acroos** [apache/airflow#8629]
**Apache Airflow version**: 1.10.10

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Python version**: 3.7.7

**What happened**:

When pulling a new image using the DockerOperator, the pull fails because [the pull method](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.image.ImageApiMixin.pull) on docker-py's `APIClient` will return a generator of dicts when `decode=True`.  The docker operator expects that generator to return strings [as seen here](https://github.com/apache/airflow/blob/master/airflow/providers/docker/operators/docker.py#L274).  The result is the following error:

```
[2020-04-29 11:14:59,010] {taskinstance.py:1145} ERROR - 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 269, in execute
    output = json.loads(l.decode('utf-8').strip())
AttributeError: 'dict' object has no attribute 'decode'
```

**What you expected to happen**:

The DockerOperator should be able to pull images regardless of log driver.  It should handle both 'bytes' and 'dict' return types from the pull method.

**How to reproduce it**:

1. Set up your docker client to use the `json-file` log driver [instructions here](https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver)
2. Create a DAG with a single DockerOperator and set `force_pull=True`
3. Run the DAG

**Comment by acroos** [comment]
Sorry!  It appears https://github.com/apache/airflow/pull/8287 will fix this issue

**Comment by timrourke** [comment]
@acroos FYI, I tried changing `/etc/docker/daemon.json` to use `journald` to no avail; I think this issue exists regardless of what logging driver selected.

Were you able to bypass this issue by changing anything else while we wait for https://github.com/apache/airflow/pull/8287 to make it into a stable release?

**Comment by acroos** [comment]
@timrourke to be honest, I didn't try many other options.  It seems to me like this will be an issue regardless of log driver indeed, according to docker-py docs, a dict is the expected return type.  It doesn't mention anything about different drivers.

**Comment by timrourke** [comment]
@acroos Thanks! FYI looks like this got merged: https://github.com/apache/airflow/pull/8287

**Comment by languitar** [comment]
Does anyone know when this will end up in a stable release?

**Comment by mik-laj** [comment]
@languitar We plan to release it in Airflow 2.0. However, you will be able to use it in Airflow 1.10 using backport packages. The releasing process of these packages is ongoing. I hope it will take us up to two weeks.
https://github.com/apache/airflow#using-hooks-and-operators-from-master-in-airflow-110

**Comment by eladkal** [comment]
This should have been fixed by https://github.com/apache/airflow/pull/8287 if someone still experience the bug in Airflow > 2 please comment
