### ISSUE TITLE
Airflow 1.10.10 scheduler bug 

### ISSUE THREAD

**Issue by flin-aa** [apache/airflow#8632]
**Apache Airflow 1.10.10**:

**Linux version 3.10.107-1-(gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) **:

**start scheduler a few minutes ,airflow celery do not received task , also can say scheduler do not send task to broker while scheduler still running in backend, the scheduler will  turn to be red after scheduled task number reach to the 16.**:

 
![image](https://user-images.githubusercontent.com/6638184/80606053-68563980-8a66-11ea-8a3a-11151841c1b4.png)

i have three server, a(server) ,b(worker) ,c(worker) 
 
redis server: redis-cli 5.0.8
redis client: redis-cli 3.2.12
mysql  Ver 14.14 Distrib 5.6.44, for Linux (x86_64) using  EditLine wrapper
Python-3.7.0

**Comment by zhongjiajie** [comment]
Could you show some log about the scheduler? @flin-aa

**Comment by zhongjiajie** [comment]
Close this issue cause no more detail.
