### ISSUE TITLE
Scheduler not receiving heartbeats

### ISSUE THREAD

**Issue by darwinyip** [apache/airflow#8638]
**Apache Airflow version**: 1.10.9

**Environment**:

- **Cloud provider or hardware configuration**: AWS - webserver, flower, scheduler, worker running in separate ECS services
- **OS** (e.g. from /etc/os-release): python:3.6-slim
- **Others**: Running distributed with Celery
`apache-airflow[aws,celery,crypto,gcp,mysql,postgres,redis,sentry,slack,ssh]==1.10.9`

**What happened**:

Seeing occasional scheduler issues after upgrading from 1.10.3 to 1.10.9

```
The scheduler does not appear to be running. Last heartbeat was received X hour ago.
The DAGs list may not update, and new tasks will not be scheduled.
```

**What you expected to happen**:

Scheduler keep receiving heartbeats

**How to reproduce it**:

It seems to occur when the scheduler's memory usage is very high, such as +75%. When that happens, memory flatlines.

**Anything else we need to know**:

Happens intermittently.

**Comment by ashb** [comment]
We believe this is fixed with Airflow 2.0.0 now (at least for Celery executor) so I'm going to close out this issue.

If it is still a problem after upgrading to 2.0 let us know and we can re-open this.
