### ISSUE TITLE
Data Transformations subDAGs to allow dependecies between inputs and outputs of Nodes

### ISSUE THREAD

**Issue by cvarelaruiz** [apache/airflow#864]
While Airflow shows dependencies between the task nodes of a DAG it would be very useful to be able to create specific type of subDAGs where the nodes perform Data operations (or transformations).

Similar to XComs but optimized for bulk data, each one of those data operation nodes could have multiple inputs (like pandas dataframes) on which they perform operations and are shared to nodes downstream via outputs, and therefore the dependencies would be tracked and assessed against those inputs/outputs rather than completion of tasks.

**Comment by bolkedebruin** [comment]
+1
