### ISSUE TITLE
BigQuery: integer range partitioning support for BQ tables

### ISSUE THREAD

**Issue by exploy** [apache/airflow#8645]
**Description**

Support for  integer range partitioning for BigQuery tables

**Use case / motivation**

There is already support for time partitioning while creating BQ tables and Google offers more options than only time partitioning. 
We found integer range partitioning working best for our case so we customized few classes to gain this functionality. 

More details: https://cloud.google.com/bigquery/docs/partitioned-tables

Will contribute the change but it is not yet ready

**Related Issues**

A quick search revealed no similar issues.

**Comment by exploy** [comment]
Related PR https://github.com/apache/airflow/pull/8653

**Comment by mik-laj** [comment]
@exploy Could you please check if this feature is still missing? We have made major changes to this integration and many of the missing features are now available.

**Comment by totogo** [comment]
@mik-laj I was looking for this feature too, it's not there yet

**Comment by mik-laj** [comment]
I was able to create tables with integer range partitioning.
```
    create_table = BigQueryCreateEmptyTableOperator(
        task_id="create_table",
        dataset_id="test_dataset",
        table_id="test_airflow_table",
        table_resource={
            "rangePartitioning": {
                "field": "my_int_field",
                "range": {
                    "start": 1,
                    "end": 10000,
                    "interval": 100
                }
            },
            "id": "new-range-partition-table",
            "schema": {
                "fields": [
                    {
                        "name": "my_int_field",
                        "type": "INTEGER",
                        "mode": "NULLABLE"
                    }
                ]
            }
        }
    )
````
![Screenshot 2020-12-18 at 14 28 03](https://user-images.githubusercontent.com/12058428/102619916-7c59c300-413d-11eb-8f21-7fae8ea20b2f.png)
![Screenshot 2020-12-18 at 14 28 18](https://user-images.githubusercontent.com/12058428/102619923-7d8af000-413d-11eb-9434-afcb097b17b4.png)
