### ISSUE TITLE
Custom connection for backported Yandex.Cloud provider

### ISSUE THREAD

**Issue by peter-volkov** [apache/airflow#8650]
There is a Yandex.Cloud provider in master branch.
However, I want it completely backported to Airflow 1.* to distribute among the clients.
The problem is this provider requires a custom connection type, which is not backported at the moment.
https://github.com/apache/airflow/blob/master/airflow/models/connection.py#L170

It is hardly can be packaged as a wheel, because it involves editing common Airflow files
```airflow/www/views.py```
```airflow/www/forms.py```
```airflow/models/connection.py```

I can make a PR to 1-10-test/1-10-stable branch if there is no other way to pack the custom connection to the separated wheel package

**Comment by peter-volkov** [comment]
Related discussion in Slack
https://app.slack.com/client/TCQ18L22Z/CUKA3KQ81/thread/CUKA3KQ81-1588259396.032300

**Comment by eladkal** [comment]
solved in https://github.com/apache/airflow/pull/8791
