### ISSUE TITLE
Custom Operator Documentation Typo

### ISSUE THREAD

**Issue by JonnyWaffles** [apache/airflow#8654]
Hi friends,

There is a typo in the documentation regarding customer operators [here](https://airflow.apache.org/docs/stable/howto/custom-operator.html#creating-a-custom-operator). `name` should be `self.name` and the task id template should probably be changed to `{{ task_instance.task_id  }}`

```python
class HelloOperator(BaseOperator):

    template_fields = ['name']

    @apply_defaults
    def __init__(
            self,
            name: str,
            *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.name = name

    def execute(self, context):
        message = "Hello from {}".format(self.name)
        print(message)
        return message
```
and then {{ task_id }} should become

```hello_task = HelloOperator(task_id='task_id_1', dag=dag, name='{{ task_instance.task_id  }}')```

Cheers

EDIT: Not sure how to change the label to kind:docs

**Comment by potiuk** [comment]
Changed the label. Maybe you would like to make A PR fixing it @JonnyWaffles? Airflow is a community project and anyone can contributed. Seems you know exactly how to fix the docs. An you can make Fork/PR/change the docs purely using Github interface.

**Comment by JonnyWaffles** [comment]
Hi friends the pull request is here https://github.com/apache/airflow/pull/8678
