### ISSUE TITLE
airflow clear cli very slow

### ISSUE THREAD

**Issue by yee379** [apache/airflow#8658]
**Apache Airflow version**:
1.10.10

**Environment**:
postgres backend

**What happened**:
i often have dag run tasks that fail. more often or not, rerunning the task will work - even with retries, its often better in my environment to wait a long-ish while before clearing the task and downstream tasks. hence i basically run `airflow clear` on the command line for tasks that have failed, say every day or so. however, i notice its very slow - often taking a minute or more per individual task to clear. they are executed like this.

    airflow clear --downstream -t my_task  my_dag -s 2020-04-26T09:13:41.080853+00 -e 2020-04-26T09:13:41.080853+00 -c

the `-s` and `-e` args are derived from a database query of the airflow database itself.

**What you expected to happen**:
i would expect the `airflow clear` to return quickly - seconds rather than minutes. it works fine (quickly) if i clear the task and downstream from the gui (much slower if recursive). perhaps having an option to take in the run_id would help with the backend database query? eg

    airflow clear --downstream -t my_task  my_dag --run_id pos44_00012

would be appropriate?

**Comment by eladkal** [comment]
It may have been fixed by https://github.com/apache/airflow/pull/14048
can you please check with Airflow 2.0.0 / Master?
