### ISSUE TITLE
Postgres to GCS operator - use named cursor

### ISSUE THREAD

**Issue by maroshmka** [apache/airflow#8664]
**Description**

Hey guys, 

postgres_to_gcs operator is putting all data (based on select statement) into memory.
ref [here](https://github.com/apache/airflow/blob/b185b364dfa5c6601da55ddad98f8be7f6a44b68/airflow/providers/google/cloud/operators/postgres_to_gcs.py#L75) 

**Use case / motivation**

We are uploading bigger data to gcs. In our case, it is mostly, because of doing backups of the table. But its not tied to this one use-case, of course, anytime your select returns bigger amount of data, the operator puts it in to the memory.

To make this more specific, lets say table we are selecting have 10gb, which means that the process where it is running (no matter the executor), needs to have ~11gb available.

We are using Airflow 1.10.3, I checked the master version and this operator its a bit refactored, but the issue is still there.

We have solved it with using server side cursor, from psycopg you can do that with specifying name for the cursor - https://www.psycopg.org/docs/usage.html#server-side-cursors
We have overriden few methods that pulls the data.

I can create a PR, but want to know first what you think about it. Let me know how to proceed. In case this is reasonable thing to do, please decide if:
1. We want to keep both options - named/default cursor, e.g. specified by operator argument
2. We want to allow to specify itersize, default is on 2k rows

In our case, we decreased mem usage of selecting 18gb table to ~150mb 🙂 

thank you!

**Comment by lihan** [comment]
@maroshmka I also have a reference implementation, and hit by the same problem. Loading all data into memory is not the way to go.

`class CustomPostgresToGoogleCloudStorageOperator(PostgresToGoogleCloudStorageOperator):

    @apply_defaults
    def __init__(self,
                 itersize=20000,      # batch size
                 *args,
                 **kwargs):
        super(CustomPostgresToGoogleCloudStorageOperator, self).__init__(*args, **kwargs)
        self.itersize = itersize

    def query(self):
        """
        Queries Postgres and returns a cursor to the results.
        """
        hook = PostgresHook(postgres_conn_id=self.postgres_conn_id)
        conn = hook.get_conn()
        random_str = ''.join(random.choice(string.ascii_lowercase) for i in range(4))
        cursor = conn.cursor(name='airflow_cursor_{}'.format(random_str))
        cursor.itersize = self.itersize
        cursor.execute(self.sql, self.parameters)
        return cursor`
