### ISSUE TITLE
K8S Pods labels have task_id and dag_id which then gets warned

### ISSUE THREAD

**Issue by lihan** [apache/airflow#8666]
So here it seems it warns if Pod label contains **dag_id** or **task_id**
https://github.com/apache/airflow/blob/b185b364dfa5c6601da55ddad98f8be7f6a44b68/airflow/executors/kubernetes_executor.py#L642

But then in Pod generator, it adds these two?
https://github.com/apache/airflow/blob/b185b364dfa5c6601da55ddad98f8be7f6a44b68/airflow/kubernetes/pod_generator.py#L422

**Comment by lihan** [comment]
This message get printed to console every time a Pod is scheduled.

**Comment by mik-laj** [comment]
@lihan The problem is that you have your DAG_ID or Task ID contains illegal characters. In that case, a safe path is started which is very slow. See: https://github.com/apache/airflow/blob/b185b364dfa5c6601da55ddad98f8be7f6a44b68/airflow/executors/kubernetes_executor.py#L559
