### ISSUE TITLE
A more generic on_failure, on_retry methods

### ISSUE THREAD

**Issue by jeffolsi** [apache/airflow#8686]
**Description**

Airflow offers to setup:

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 1),
    'email': ['airflow@example.com'],
    'email_on_failure': True,
    'email_on_retry': True,
}
```

In this case email_on_failure, email_on_retry will use the list email to notify on failure/retry.
It's 3 lines that solve the issue of getting notified when there is a problem. 

**Use case / motivation**

issue starts when one doesn't wish to be notified by email. One can and should be able to be notified by Slack, Telegram or any other integration that Airflow has with chat apps.
Airflow should provide the infrastructure for this and any chat integration can choose if they add it or not when PR is submitted for that integration.

So possible solution can be:

for email:
```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 1),
    'method_notify':'email',
    'list_notify': ['airflow@example.com'],
    'notify_on_failure': True,
    'notify_on_retry': True,
}
```

for Slack:

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 1),
    'method_notify':'slack',
    'list_notify': ['chanle_name'],
    'notify_on_failure': True,
    'notify_on_retry': True,
}
```

**More info**

I'm aware that I can write `on_failure_callback` and `on_retry_callback`. This is what I do now but I think this can be improved. Also I feel that those methods are more for "Do something about the failure" rather than notify that it happened.

**Comment by RosterIn** [comment]
This is really good suggestion!
This can really solve many issues for organizations that work with more than one communication application.

**Comment by ashb** [comment]
Closing in favour of #12611 which is more general purpose.
