### ISSUE TITLE
Skip task itself instead of all downstream tasks

### ISSUE THREAD

**Issue by yuqian90** [apache/airflow#8696]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: any
- **OS** (e.g. from /etc/os-release): any
- **Kernel** (e.g. `uname -a`): any
- **Install tools**: any
- **Others**: any

**What happened**:

- When a sensor is set to `soft_fail=True`, it becomes skipped when it fails. However, it also calls `BaseSensorOperator._do_skip_downstream_tasks()` and skips all of its downstream tasks unconditionally, including those with `trigger_rule` `none_failed`, `one_success` etc.
- `ShortCircuitOperator` is similar. When it is skipped, it skips all its downstream tasks unconditionally.

**What you expected to happen**:
- When a soft_fail sensor fails, it should skip itself. Downstream tasks with `trigger_rule` `all_success` (i.e. the default) should be skipped because of `TriggerRuleDep`. Tasks that are `none_failed` or `one_success` etc should not be skipped unconditionally by the soft_fail sensor.
- Same applies for `ShortCircuitOperator`

**How to reproduce it**:
Any DAG with `soft_fail` or `ShortCircuitOperator` and downstream tasks having `trigger_rule` `none_failed`, `one_success` will have this problem.

**Anything else we need to know**:

An old issue addressed this in general and made it possible for operators to skip themselves and not its downstream. The same principle should be applied to `soft_fail` and `ShortCircuitOperator`:
https://github.com/apache/airflow/pull/1292

The fix should to this issue is rather simple, just raise `AirflowSkipException` and not skip downstream tasks. Leave it to the TriggerRuleDep to do the skip based on the trigger_rule of tasks.

**Comment by RosterIn** [comment]
seems related to https://github.com/apache/airflow/issues/7858

**Comment by yuqian90** [comment]
It looks like the same issue has been reported before as well: https://issues.apache.org/jira/browse/AIRFLOW-6163

**Comment by gdevanla** [comment]
@yuqian90 I believe you are pointing to this line of code which should not be performing this task here.  

https://github.com/apache/airflow/blob/7506c73f1721151e9c50ef8bdb70d2136a16190b/airflow/sensors/base_sensor_operator.py#L121

As I understand it, when the jobs are not skipped here, the current set up in TriggerRuleDep._evaluate_trigger_rule() takes care of skipping the tasks for appropriate conditions.

https://github.com/apache/airflow/blob/7506c73f1721151e9c50ef8bdb70d2136a16190b/airflow/ti_deps/deps/trigger_rule_dep.py#L128

Any thoughts on this change along these lines?

**Comment by j-y-matsubara** [comment]
@gdevanla 
Sorry for cutting in, and I agree with your idea.
I was having trouble with this, so I am trying to fix it. 
Are you planning to fix it?

**Comment by gdevanla** [comment]
Nope, you can go ahead and work on it. I hit the same issue with in our internal project and was looking through the code to understand what was happening. Then I came across this bug submission.

**Comment by j-y-matsubara** [comment]
Thank you, your comments.
If my fix seems slow, and you want to fix it hurry, you should feel free to correct me.

**Comment by ccage-simp** [comment]
Thank you for reporting this @yuqian90, and to @j-y-matsubara for submitting PR for fix. Issue has been troubling me since upgrade to 1.10.

**Comment by j-y-matsubara** [comment]
@ccage-simp 
This PR has not been merged yet. 
What issues did you encounter?

**Comment by ccage-simp** [comment]
Same as the defect. I mean to say that I'm looking forward to this fix being released.

I use soft_fail True at times and want skipped tasks not to automatically skip all downstream tasks. I believe that trigger_rule ALL_DONE and others should allow for upstream of skipped.

**Comment by j-y-matsubara** [comment]
Thank you for your reply, @ccage-simp 
I'm sorry, I made a wrong interpretation about your comment.

Best Regard,

**Comment by j-y-matsubara** [comment]
@yuqian90 
I am sorry to bother you, but Is it possible to close this issue?
The PR have been merged, but it didn't seem to link well with this issue.

**Comment by yuqian90** [comment]
Great thank you so much @j-y-matsubara
