### ISSUE TITLE
Tutorial documentation: "date"?

### ISSUE THREAD

**Issue by gtoonstra** [apache/airflow#87]
Just following the tutorial to see what airflow is about. It was easy to follow up till the "testing" paragraph on the tutorial page. Suddenly a "date" parameter is required.

Until there, I assumed you could run a batch job on anything and just request it to be run. Here, airflow implicitly requires that you run any DAG for a date or date ranges and that this parameter is required. I'm not sure if this parameter is passed into every task, or whether airflow simply needs this for another purpose.

It would be good to explain what this strange date parameter is for, what impact it has on tasks or whether this is internal use.

**Comment by mistercrunch** [comment]
Airflow assumes that you are running batch jobs on a schedule. As you see this is deeply rooted in the platform.

I can see how people would be interested use a workflow engine outside of a schedule, say based on when chunks of data show up, or when some other systems tells it to. It's not impossible to do so. The key would be to disregard the scheduler (by not firing it up, or setting the tasks as `adhoc=True`), and to think of `execution_date` as some sort of run_id.

Some elements from the UI won't make sense, but Airflow will still do its thing as a workflow engine.

**Comment by gtoonstra** [comment]
Thanks for the explanation.

Please evaluate if the docs should have some comment added to explain the use of the start_date, I can imagine others may have similar problems figuring out where it appeared from.

So what I understood:
- "airflow test" allows you to run a single task from a dag. It will actually execute the task locally, but it does not leave logs or update the database that the test was run. I don't know what purpose start_date serves here.
- "airflow run" is used to run a single task through the scheduler (does start_date here mean "run for a particular date?".  I just see the current date in the logs ) 
- "airflow backfill" is used to populate the schedule with records to run tasks from a dag in the correct order, respecting the dependencies. Here the start_date and end_date mean the date range for which to schedule the dag with an indicated interval.

The use of the 'date' parameter without a time part also implies that the dag's are intended to be complex batch jobs that run once per day. Is this correct?
- If a task failed and it is rerun ( "airflow run"?  ) and it succeeds along with the rest of the dag, then in the end airflow reports "all green" for the task on a particular day. You can rerun tasks, but they will just be rerun in the same 'day' context, so it does not make sense.
- corner case: If you have a dag that failed and work up to 1am to resolve it, how does the task show up?  As the "start_date" with which it ran, or just using the current date of the machine?  Is airflow clever enough to consider it part of the previous day's run ( in the logs, etc? ). Does it make sense to try to resolve issues after midnight with airflow?
- When writing airflow operators and tasks, should one use the 'start_date'/'end_date' as input parameter for the work or can any task just use the current machine date / time?  This is a very important decision, because it makes results reproducible (or not). 

I noticed that if you use 'backfill' to create jobs to run, it will also create historic records for that. So if you specify start_date from 2015-01-01, it will create records for every date up to now and run them in the scheduler.

**Comment by mistercrunch** [comment]
Notes and answers:
- `start_date` is mostly used by the scheduler (`airflow scheduler`) to know where to start running from for each task. If you commit a new task to your DAG, the scheduler will attempt to run that task starting on that date. Also for tasks that are `depends_on_past==True`, we don't care about that flag for the `start_date`
- Much like `airflow test`, `airflow run` allows you to trigger a single "task instance" with a set of options documented in the CLI doc and displayable by running `airflow run -h`. It cares about dependencies, and records its success/failure in the DB

The assumption is that your DAG has a start_date and a schedule_interval. If you have a schedule_interval of `timedelta(hours=1)`, the scheduler will schedule your DAG to run every hour. The state is recorded for each task instance, which is a task for a specific schedule. The "_date" params receive a `datetime.datetime` in the API and a parsable datetime string in the CLI. You can use `2015-01-01`, or `2015-01-01T00:00` or `2015-01-01T01:00` in the CLI, anything that the dateutils lib will parse, that matches your schedule.

**Comment by gtoonstra** [comment]
Created a pull request with a proposal on making this clearer.  Most of my confusion was related by not picking up the difference between "execution_date" and "start_date". Now it all makes sense.
