### ISSUE TITLE
Support for set in XCom serialization

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#8703]
**Description**

Add support for `set` in Xcom serialization method. This requires support for `set` in nested structures. 

**Use case / motivation**
Once we switched to JSON as main serialization format the following error appeared:
```
TypeError: Object of type 'set' is not JSON serializable
```

**Related Issues**

Discussion started in https://github.com/apache/airflow/pull/8607#discussion_r419327697

**Comment by turbaszek** [comment]
As I said in https://github.com/apache/airflow/pull/8607#discussion_r419327697

> I was thinking about that and I am against it. JSON has no set structure and users should be aware of this. Additionally, if we want to support set in general then we have to support all possible nested structures (dicts + sets, list of sets, etc)

But I am happy to discuss. @kaxil @ashb @potiuk @mik-laj

**Comment by kaxil** [comment]
We do it anyway for Serialized DAGs so we can just reuse the following code that takes care of set and other nested data structures:

https://github.com/apache/airflow/blob/caa60b1141ac02cdde1c33464be9adca114c2ed5/airflow/serialization/serialized_objects.py#L164-L209

**Comment by kaxil** [comment]
I am surprised though that we didn't get any issues regarding it yet (or maybe we just haven't looked) :D

**Comment by turbaszek** [comment]
> We do it anyway for Serialized DAGs

And if I am not mistaken we make an assumption that we will never reach max concurrency error? 

> I am surprised though that we didn't get any issues regarding it yet (or maybe we just haven't looked) :D

Me too but I'm getting used to the fact that a lot of operators are never used by majority...

**Comment by ashb** [comment]
XCom used to be pickle by default (and still is on 1.10?), that'll be why it has gone un-noticed for so long.

**Comment by turbaszek** [comment]
> XCom used to be pickle by default (and still is on 1.10?), that'll be why it has gone un-noticed for so long.

Imho the main reason were side effects in tests. Otherwise, we will spot it at once.

**Comment by turbaszek** [comment]
@kaxil @ashb @mik-laj @potiuk @zhongjiajie what's your opinion? Should we silently make `set` JSON-serializable or not?

**Comment by zhongjiajie** [comment]
> @kaxil @ashb @mik-laj @potiuk @zhongjiajie what's your opinion? Should we silently make `set` JSON-serializable or not?

I think we should use JSON ser, and we going to use json as default serializable (as less in code base `TODO` mark said that)

**Comment by kaxil** [comment]
Yes I think we should make it Serializable

**Comment by vikramkoka** [comment]
@turbaszek @kaxil Unclear on if this should have a milestone?

**Comment by kaxil** [comment]
The PR (https://github.com/apache/airflow/pull/9847) linked to this issue has milestone so we should be fine

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/16786 should fix this

**Comment by kaxil** [comment]
Let's use Custom XCom backend if needed -- this isn't critical

**Comment by eladkal** [comment]
@kaxil https://github.com/apache/airflow/pull/16395 was on hold for a fix here.
Should we also close the linked issue https://github.com/apache/airflow/issues/16386 ?
