### ISSUE TITLE
At what point a TaskInstance is persisted in db?

### ISSUE THREAD

**Issue by rpaidar** [apache/airflow#871]
I am new to Python and have been trying to understand how airflow works.  I can not see where a taskinstance is persisted in the database.  Could someone point me to the code where this is done?
Thanks.

**Comment by mistercrunch** [comment]
We use an ORM called SqlAlchemy.`TaskInstance.run`
https://github.com/airbnb/airflow/blob/0c29db14eb4fda8180bf8943384fac7ba1308078/airflow/models.py#L909
Is where the the most common flow occurs (set to running, success, failed). In this context `self` is an orm TaskInstance object.

Other methods and flows alter state (clearing, marking succes, ...)
