### ISSUE TITLE
Container level securityContext support for kubernetes

### ISSUE THREAD

**Issue by bhavaniravi** [apache/airflow#8714]
**Description**

KubernetesExecutor/KubernetesPodOperator supports `securityContext` for pods but I am working on a case where I want to set a `privileged` mode for base container.

**Use case / motivation**

Mounting s3 to worker pods using s3fuse needs to run the base container in privileged mode

**Related Issues**

None

**Comment by dimberman** [comment]
@bhavaniravi I'm going to close this as I believe this is handled by creating a `pod_template_file`, but please re-open if you feel this is not the case
