### ISSUE TITLE
Documentation about loading packages in Python / Airflow

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8715]
**Description**

A guide is missing to answer the following questions.

- [x] How does Python load packages? 
   - sys.path and [a intelligent algorithm](https://stackoverflow.com/questions/897792/where-is-pythons-sys-path-initialized-from/38403654#38403654) for determining the content of this variable
- [x] How does Airflow modify this behavior? 
   - 3 new directories - https://github.com/apache/airflow/issues/8647
- [x] When and how you can affect the module loading mechanism? 
   - PYTHONPATH
   - Pip packages
- [x] How to create python package with operators/plugins? 
   - Short guide
    - link to [Python Packaging User Guide](https://packaging.python.org/tutorials/packaging-projects/)
- [x] How to use PYTHONPATH? 
   - A generic example and an example with Docker.
- [x] How do you check the contents of the sys.path variable? 
   - `airflow info` command
- [x] How to set configuration option with import e.g. `hostname_callback`, `api_client`? 

Best regards,
Kamil

**Comment by potiuk** [comment]
Absolutely needed ! Fully agree.

**Comment by mik-laj** [comment]
It's related to:
https://github.com/apache/airflow/issues/9498
https://github.com/apache/airflow/issues/9507
So I added this to the Airflow 2.0 milestone

**Comment by mik-laj** [comment]
@rootcss Could you please leave a comment so I can assign you to this ticket?

**Comment by rootcss** [comment]
@mik-laj yes, can you assign this issue to me?

**Comment by mik-laj** [comment]
@rootcss I assigned you to this ticket.

**Comment by rootcss** [comment]
@mik-laj where do you think we should put this doc? a new file in the root of docs or somewhere else?

**Comment by mik-laj** [comment]
New file in the root directory - `docs/`

**Comment by potiuk** [comment]
I think we can close that Kamil ?
