### ISSUE TITLE
DagRuns page renders the state column with artifacts

### ISSUE THREAD

**Issue by voroninman** [apache/airflow#8717]
**Apache Airflow version**: 1.10.10

**Environment**:

Docker image [python:3.7-slim](https://github.com/docker-library/python/blob/b818e9441c088295165edf79a791503f1fe7f6f7/3.7/buster/slim/Dockerfile).

**How to reproduce it**:

Navigate to `/admin/dagrun/`.

<img width="960" alt="Screenshot 2020-05-05 at 15 05 26" src="https://user-images.githubusercontent.com/399059/81069421-2273f800-8ee2-11ea-8346-3e74d289607b.png">

**Other**:

The web server returns HTML that consists of:

```html
<a
	data-csrf=""
	data-pk="1150737"
	data-role="x-editable"
	data-source="[{&#34;text&#34;: &#34;&#34;, &#34;value&#34;: &#34;__None&#34;}, {&#34;text&#34;: &#34;success&#34;, &#34;value&#34;: &#34;success&#34;}, {&#34;text&#34;: &#34;running&#34;, &#34;value&#34;: &#34;running&#34;}, {&#34;text&#34;: &#34;failed&#34;, &#34;value&#34;: &#34;failed&#34;}]"
	data-type="select2"
	data-url="./ajax/update/"
	data-value="<span class="label" style="background-color:green;">success</span>" 
	href="#" 
	id="state" 
	name="state"
>
	<span class="label" style="background-color:green;">success</span>
</a>
```

Flask-Admin version is 1.5.4.
After a brief investigation, the problem seems to be related to using HTML as a value for an editable widget.

**Comment by davido912** [comment]
I am facing the same problem. did you manage to solve this?

**Comment by voroninman** [comment]
> I am facing the same problem. did you manage to solve this?

No. I haven't tried really as it's mostly esthetics.

**Comment by davido912** [comment]
> > I am facing the same problem. did you manage to solve this?
> 
> No. I haven't tried really as it's mostly esthetics.

I believe you can also not set the state on that page. Try changing the state there to running/failed you'll see it doesn't update. However, setting the state from other sections does work.

**Comment by voroninman** [comment]
> > > I am facing the same problem. did you manage to solve this?
> > 
> > 
> > No. I haven't tried really as it's mostly esthetics.
> 
> I believe you can also not set the state on that page. Try changing the state there to running/failed you'll see it doesn't update. However, setting the state from other sections does work.

True. I do change the state from other sections.

**Comment by spencerogawa** [comment]
I'm having the same issue as well. The state seems clickable.

Openshift
Python 3.7.6 (Compiled from source)
REL 7
Airflow 1.10.10

![Capture](https://user-images.githubusercontent.com/11817131/82121030-27457100-9758-11ea-8f8d-8cb0653eecbd.png)

**Comment by ashb** [comment]
This appears to a bug in our (soon to be remove) old UI. The easy fix for now is to switch to the RBAC UI by enabling it in your config files. We are only doing bug fixes against the old UI now (so this should get fixed) but you won't get any new features, such as the ability to show datetimes in your local TZ if you stick on this UI.

**Comment by kaxil** [comment]
Fixed in https://github.com/apache/airflow/commit/dbe308c7ea31043d86ac1b563c5590fe6c40bcb5
