### ISSUE TITLE
Can't clear all upstream tasks when DAG Serialization is enabled

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#8720]
**Apache Airflow version**: 1.10.10

**To Reproduce**
Steps to reproduce the behavior with Astronomer Image:
1. Enable DAG Serialization (Put `AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True`
Once the Webserver boots up, run any DAG
1. Once the DAG completes execution, click on the task that has few upstream tasks in Graph View
1. One the **Task Instance Modal**, select **Upstream** -> click on **Clear**. You will see a list of tasks but that would not have all the upstream tasks.

**Screenshots**
![Apr-22-2020 15-56-14](https://user-images.githubusercontent.com/8811558/79997805-d96b7f00-84b1-11ea-8328-9d24c4a77ad6.gif)

**Comment by ashb** [comment]
I think I have a fix for this

**Comment by kaxil** [comment]
Fixed in 1.10.11
