### ISSUE TITLE
Uploading List of Files to Google Cloud Storage

### ISSUE THREAD

**Issue by timhealz** [apache/airflow#8724]
**Description**

In the [current implementation](https://airflow.apache.org/docs/stable/_api/airflow/contrib/operators/file_to_gcs/index.html) of `FileToGoogleCloudStorageOperator`, a single file is inputted to be uploaded to Google Cloud Storage bucket.

I'd like to implement functionality to allow input of a list of files, directory path or perhaps even a wildcard string (`/path/to/*.csv` for example).

**Related Issues**

Not that I can tell from searching, but there is this [stackoverflow question](https://stackoverflow.com/questions/58945050/uploading-local-directory-to-gcs-using-airflow) that @kaxil answered.

**Comment by mik-laj** [comment]
Very useful. I think it can easily be done if you use [glob.glob](https://docs.python.org/3/library/glob.html#glob.glob)

**Comment by timhealz** [comment]
Agreed @mik-laj , I can work on the PR if this issue can be assigned to me.

**Comment by kaxil** [comment]
> Agreed @mik-laj , I can work on the PR if this issue can be assigned to me.

Done
