### ISSUE TITLE
Purpose of warning when packaged dag contains an __init__.py?

### ISSUE THREAD

**Issue by mattdornfeld** [apache/airflow#8727]
I see [here](https://github.com/apache/airflow/blob/c717d12f47c604082afc106b7a4a1f71d91f73e2/airflow/models/dagbag.py#L252) a warning is logged when a packaged dag contains an __init__.py. I'm currently using __init__.py files in my packaged dags to execute code when the dags are imported. Is there a reason a warning is logged when this happens?

**Comment by mik-laj** [comment]
Github issue is not for asking questions. For this purpose, there is a mailing list or Slack.
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#how-to-communicate
