### ISSUE TITLE
Feature Request : Support a Callback for SLA Miss Reporting

### ISSUE THREAD

**Issue by r39132** [apache/airflow#873]
Currently, my company uses VictorOps to dispatch alerts to the on-call engineer(s). VictorOps is like PagerDuty. Airflow supports email notifications for various event types : `email on error`, `email on retry`, `email on SLA miss`, etc... Unfortunately, there is only one place in a DAG to specify an Email DL for such notifications. It is possible to have Airflow support a separate DL for each cause of email notification, but this is will quickly add more configuration than is necessary. At my company, we don't want to page someone because of a task failure or a task retry, since failures are typically transient and resolved on retries. If our DAGs do not meet SLAs, then we need to page the on-call. In order to do this, we would like a python callback that we can leverage to call the VictorOps API and possibly also the Slack API (to post the issue to a Slack channel).

Here's an example DAG that specifies `email_on_failure` and `email_on_retry` as well as specifies an SLA for a task in the DAG

```
default_args = {
    'owner': 'sanand',
    'depends_on_past': False,
    'pool': 'ep_data_pipeline',
    'start_date': START_DATE,
    'email': [import_ep_pipeline_alert_email_dl],
    'email_on_failure': import_airflow_enable_notifications,
    'email_on_retry': import_airflow_enable_notifications,
    'retries': 1,
    'retry_delay': timedelta(seconds=120),
    'priority_weight': import_airflow_priority_weight
}
dag = DAG(DAG_NAME, schedule_interval='@hourly', default_args=default_args)

send_email_notification_flow_successful = PythonOperator(
    task_id='send_email_notification_flow_successful',
    execution_timeout=timedelta(minutes=15),
    pool='ep_data_pipeline_metrics_gathering',
    provide_context=True,
    sla=timedelta(hours=2),
    python_callable=send_email_notification_flow_successful,
    dag=dag)
send_email_notification_flow_successful.set_upstream(aggregate_db_message_job)

```

**Comment by r39132** [comment]
I'm proposing the following PR : https://github.com/airbnb/airflow/pull/869

**Comment by xcoderzach** [comment]
+1 this would be extremely useful.

**Comment by r39132** [comment]
@mistercrunch : ^

**Comment by r39132** [comment]
This was just merged into Master. Closing.

**Comment by r39132** [comment]
I'm providing an example of how we use this callback at Agari. We have an hourly DAG that scores some data. It needs to complete within 2 hours (i.e. within our configured SLA for run completion), otherwise, we need to page the on-call engineer and post a message in our ops slack channel as part of our slack ops initiative.

In the example below, we specify a callback called `sla_alert_func`. That function, defined in another file, executes a VictorOps API call to page our on-call and then posts some info in our ops slack channel,

```
default_args = {
    'owner': 'sanand',
    'depends_on_past': False,
    'pool': 'ep_data_pipeline',
    'start_date': START_DATE,
    'email': [import_ep_pipeline_alert_email_dl],
    'email_on_failure': import_airflow_enable_notifications,
    'email_on_retry': import_airflow_enable_notifications,
    'retries': 1,
    'retry_delay': timedelta(seconds=120),
    'priority_weight': import_airflow_priority_weight
}
dag = DAG(DAG_NAME, schedule_interval='@hourly', default_args=default_args, sla_miss_callback=sla_alert_func)

# FUNCTIONS
def sla_alert_func(dag, task_list, blocking_task_list, slas, blocking_tis):
    logger.info('Executing SLA miss callback')

    message_type = 'info'
    if ENV == 'EP_PROD':
        message_type = 'critical'

    # Execute VictorOps alerting
    message_name = "{env} - {dag_name} SLA Miss for task `{task_list}`".format(**{
        'dag_name': dag.dag_id,
        'task_list': task_list,
        'env': ENV,
    })

    userdata ={"message_type": message_type,
               "state_message": message_name,
               "monitoring_tool": "airflow",
               "entity_id":"airflow/telemetry/SLA_miss"}
    requests.post('https://alert.victorops.com/integrations/generic/0000000/alert/{}/ep'.format(victorops_key), data=json.dumps(userdata))

    # Execute Slack alerting
    report_issues_on_slack_util(message_name)
```
