### ISSUE TITLE
Logging module (custom) no longer working 

### ISSUE THREAD

**Issue by davido912** [apache/airflow#8731]
Hey, 
Since having updated Airflow to the latest version 1.10.10, it appears that using the logging module to generate custom logging into Airflow logs no longer works. 
Was there something changed with the configuration file that no longer allows this or is there a workaround? Again, this has been working for the last year, and since updating stopped to work.

Would appreciate help.
Thanks!

**Comment by rahulj51** [comment]
This looks like it's related to #8484

**Comment by kamikaze** [comment]
same here since 1.10.9 (probably 1.10.8, but we skipped it)

**Comment by eladkal** [comment]
Since this issue is reported over an old version of Airflow kindly asking to recheck with Airflow 2.1.0
If something isn't working as expected please provide full reproduce steps
