### ISSUE TITLE
BUG: Unable to view or browse dags in web UI after migrated airflow 1.9.0 to 1.10.10

### ISSUE THREAD

**Issue by mmuru** [apache/airflow#8752]
**Apache Airflow version**: airflow 1.10.10 

**Environment**:

- **OS** (e.g. from /etc/os-release): Mac 

**What happened**:
`
Ooops! throws exception
File "/Users/muru/opensrc/py36/airflow_110/venv368/lib/python3.6/site-packages/airflow/www/templates/airflow/dags.html", line 84, in block "body"
    <a href="{{ url_for('airflow.'+ dag.get_default_view(), dag_id=dag.dag_id) }}" title="{{ dag.description[0:80] + '...' if dag.description|length > 80 else dag.description }}">
TypeError: object of type 'NoneType' has no len()
`

**What you expected to happen**:
Should able to load page without errors or exceptions.

The description column in dag table can be null. But in the dags.html, should check dag.decription is not null before perform length filter. 

**How to reproduce it**:
migrate airflow 1.9.0 to 1.10.10
Perform airflow upgradedb 
start airflow webserver 
launch and open http://localhost:8080/

**Anything else we need to know**:
Line 84 in airflow/www/templates/airflow/dags.html file, replace the condition
`if dag.description|length > 80 
change to
if dag.description and dag.description|length > 80`

As a workaround, perform the following db update and open http://localhost:8080/
`update dag
set description=' '
where description is null;`

**Comment by mik-laj** [comment]
Here is related PR: https://github.com/apache/airflow/pull/7593/files
@zhongjiajie Can you look at it?

**Comment by zhongjiajie** [comment]
Thanks @mik-laj to notice that, but is odd that https://github.com/apache/airflow/pull/7593 not release in 1.10.10, and the reporter solution is also my PR's solution. And @kaxil milestone PR in 1.10.11, I think it will be fix after 1.10.11 release, cc: @mmuru

**Comment by zhongjiajie** [comment]
BTW, I will check which PR cause this error

**Comment by zhongjiajie** [comment]
@mmuru  I find out the original pr is https://github.com/apache/airflow/pull/7457, and I think it should not cause error because dag.description default value is `''`(empty string),
https://github.com/apache/airflow/blob/42e9a2912b2736dd166ab711a3b0993913669612/airflow/models/dag.py#L218
unless you define `description=None` in DAG files. if so maybe you should just remove the description define.

And, BTW, we have https://github.com/apache/airflow/pull/7593 to fix that will release in 1.10.11, will use `description=None` as default value, and fix your situation

**Comment by zhongjiajie** [comment]
Please mention me if you have further problem, I am sick recently and only check github twice a day, sorry about that.

**Comment by mmuru** [comment]
@zhongjiajie: I reviewed PR #7457, It checks only dag.description length limit but dag.description can be null. In my case, as I mentioned the 1.9.0 dags didn't have description. The description column was introduced in 1.10 and the default is null. I reviewed PR #7953 and it will fix this issue.

**Comment by kaxil** [comment]
Yes that PR will be cherry-picked in 1.10.11 and should fix the issue.

**Comment by zhongjiajie** [comment]
@mmuru In this case I prefer to close this issue, would reopen it if you still have further information.

**Comment by shawnngtq** [comment]
I face the same issue. Commenting here for record

**Comment by kaxil** [comment]
Cherry-picked to v1-10-test: d0de41c
