### ISSUE TITLE
Airflow suddenly died in all the instances

### ISSUE THREAD

**Issue by messitrip** [apache/airflow#8753]
Sorry for there's no log in this issue.
Before restarting airflow webserver, I found the log the webserver couldn't find some processes.
And It died suddenly.
Airflow version is 1.10.3 and It's run on ubuntu 18.04 EC2 instance.

I try to remember that
the log is like that
```
with open('proc/1802/stat') as f:
```
then 

got error that looks like
 **_NoSuchProcess: No process found with pid 1802_**

**Comment by ashb** [comment]
There is nothing we can do to debug this with so little information, sorry.
