### ISSUE TITLE
dags.html returns template error if the DAG is missing.

### ISSUE THREAD

**Issue by RyanSiu1995** [apache/airflow#8755]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
Debian with pip install airflow

**What happened**:
I have some missing DAGs from the source code and it has the record in the database. 
When I upgrade to v1.10.10, those DAGs don't have the description field, which is None by default, so the change on this PR, #7457, will return an error about applying `len` function to None type.

**What you expected to happen**:
It should not have any error during the rendering.

**How to reproduce it**:
Remove a registered DAG from the source code. And the error will pop up

**Anything else we need to know**:
Nope

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/8752

**Comment by zhongjiajie** [comment]
@RyanSiu1995 Hi, you said

> those DAGs don't have the description field, which is None by default

But I find out the default value of description is `''`(empty string), see https://github.com/apache/airflow/issues/8752#issuecomment-625006878, which version before you upgrade to 1.10.10?

**Comment by RyanSiu1995** [comment]
@zhongjiajie I was using 1.10.3.

**Comment by zhongjiajie** [comment]
@RyanSiu1995 Hi, in https://github.com/apache/airflow/issues/8752 we could know that the issue fix in master branch and will release in 1.10.11, and https://github.com/apache/airflow/issues/8752#issue-613713226 also give the solution before 1.10.11 release, hope could you
