### ISSUE TITLE
Implement kubernetes auth for vault backend

### ISSUE THREAD

**Issue by jogueber** [apache/airflow#8762]
**Description**
Currently the vault backend does not support kubernetes auth meaning if a JWT token is mounted inside the kubernetes pod it is not specify this directly to login using this token.

I propose to extend the `VaultBackend` to include an authentification using this token. 
Essentially this is already provided by the [vault client](https://hvac.readthedocs.io/en/stable/usage/auth_methods/kubernetes.html).
This would include reading the JWT token from the path and calling the login method (as described in the documentation).

**Comment by mik-laj** [comment]
@jojo19893 Can you look at this PR? https://github.com/apache/airflow/pull/8640

**Comment by jojo19893** [comment]
yes it is sorry didn't see it my bad
