### ISSUE TITLE
Add custom Salesforce connection type

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#8766]
**Description**

Airflow has SalesforceHook but it doesn't have a defined connection.

In order to create a Connection one must expose it's secret token as text :

https://stackoverflow.com/questions/53510980/salesforce-connection-using-apache-airflow-ui

Also it's not very intuitive that the Conn Type should remain blank.

It would be easier and also user friendly if there will be salesforce connection in the UI which has a security_token field that is encrypted.

moved from https://issues.apache.org/jira/browse/AIRFLOW-6429

**Comment by feluelle** [comment]
> Also it's not very intuitive that the Conn Type should remain blank.

That's true. At least there should be a `howto` docs guide on how to set up the connection properly.

**Comment by kaxil** [comment]
That can be a good first-issue to add docs :) what to create that issue @feluelle ?

> > Also it's not very intuitive that the Conn Type should remain blank.
> 
> That's true. At least there should be a `howto` docs guide on how to set up the connection properly.

**Comment by feluelle** [comment]
Sure.

**Comment by gtossou** [comment]
I would like to work on this issue

**Comment by eladkal** [comment]
@gtossou are you still working on this?

**Comment by gtossou** [comment]
> @gtossou are you still working on this?
@eladkal i'm still working on it. just figuring out the testing part before publishing a PR

**Comment by potiuk** [comment]
@gtossou  -> Just FYI, We just merged the first of the series of "auto-discovery" of Provider's capabilities, And we have defined a way how Providers can expose such connections to the Airflow Core (just in time for 2.0). 

The most important (connection type discovery) is here https://github.com/apache/airflow/commit/2037303eef93fd36ab13746b045d1c1fee6aa143


But few more are coming (see in progress items here: https://github.com/apache/airflow/projects/5) 

I will soon also add a description on the  "Discovering provider capabilities"  (Connection Types, Connection Forms, Extra Links for now). Just wanted to you to be aware that this are is still going through some latest refinements before 2.0 release.

**Comment by eladkal** [comment]
@gtossou are you still working on this issue?

**Comment by cmarteepants** [comment]
@kaxil If nobody is taking this, would love to take this on!

**Comment by kaxil** [comment]
Assigned this to you @cmarteepants  :) thanks

**Comment by eladkal** [comment]
@cmarteepants are you still working on this?
If you need some references you can check:
https://github.com/apache/airflow/pull/14724
https://github.com/apache/airflow/pull/15159

**Comment by cmarteepants** [comment]
I am! Sorry. Will hurry up. Client Engagement has been bleeding me dry 😃

**Comment by eladkal** [comment]
hi @cmarteepants rechecking you are still working on this issue?

**Comment by cmarteepants** [comment]
Hi, thanks for checking. Please feel free to reassign. I should have let you know sooner, sorry if this causes any problems

**Comment by josh-fell** [comment]
@eladkal I'm happy to take this on if still available.

**Comment by potiuk** [comment]
assigned
