### ISSUE TITLE
modal task box is unselectable

### ISSUE THREAD

**Issue by abridgett** [apache/airflow#877]
hotfix d233e41dadb8b2d043aef4be7ca043e3677c70a9 breaks the modal window for me (both on chrome and firefox).  When I select a task instance, the modal window pops up, but the whole screen is faded to grey and clicking anywhere just makes the modal dialog disappear.  i.e. I can't actually click on any button

**Comment by thibault-ketterer** [comment]
got a small fix here (comments) https://github.com/airbnb/airflow/commit/d233e41dadb8b2d043aef4be7ca043e3677c70a9
it works for me

**Comment by mistercrunch** [comment]
Would be nice if someone can come up with a fix and test it on multiple browser. I'm on PTO...

**Comment by mistercrunch** [comment]
Can you confirm that this fixes your issue?
https://github.com/airbnb/airflow/pull/1144
