### ISSUE TITLE
Airflow Tutorial page inconsistencies

### ISSUE THREAD

**Issue by akshayi1** [apache/airflow#88]
I noticed some inconsistencies in your Tutorial page where you walk us through the DAG. For instance, in the code block, you have:

```
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 1),
    'email': ['airflow@airflow.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_interval': timedelta(minutes=5),
    # 'queue': 'bash_queue',
    # 'pool': 'backfill',
    # 'priority_weight': 10,
    # 'schedule_interval': timedelta(1),
    # 'end_date': datetime(2016, 1, 1),
}
```

But when you break it down, it becomes:

```
args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 1, 1),
    'email': ['airflow@airflow.com',],
    'email_on_failure': True,
    'email_on_retry': True,
}
```

And again,

```
t1 = BashOperator(
    task_id='print_date',
    bash_command='date',
    dag=dag)

t2 = BashOperator(
    task_id='sleep',
    bash_command='sleep 5',
    dag=dag)
```

which becomes:

```
t1 = BashOperator(
    task_id='print_date',
    bash_command='date',
    dag=dag)

t2 = BashOperator(
    task_id='sleep',
    email_on_failure=False,
    bash_command='sleep 5',
    dag=dag)
```

I am less concerned with the fact that you changed the code to illustrate the arguments and parameters and more concerned that you say: "Here is an example of a basic pipeline definition. Do not worry if this looks complicated, a line by line explanation follows below." leading us to believe that it will be a true reproduction, which it is not. Please fix the code in the tutorial so that it is clearer. Thanks!

**Comment by artwr** [comment]
I have made some changes to the tutorial so that it follows the code presented at the top.
I hope it clears some things up.
https://github.com/airbnb/airflow/pull/89
