### ISSUE TITLE
Using systemd to stop scheduler in LocalExecutor mode only kills master process

### ISSUE THREAD

**Issue by ybendana** [apache/airflow#880]
After I issue a `systemctl stop airflow-scheduler` I still see 32 child processes left around which I then have to kill using `pkill airflow`. This looks related to #852 and perhaps the same fix of storing the scheduler.pid of the master process will work.

**Comment by bolkedebruin** [comment]
@mistercrunch I can broaden the pr

**Comment by bolkedebruin** [comment]
This should be fixed in master
