### ISSUE TITLE
Add ability for all operators to interact with storages of AWS/GCP/AZURE

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#8804]
**Description**

Currently every operator is doing `XToY`. so if someone wrote `MySQLToGCS` it doesn't help someone who needs `MySQLToS3`.

**Use case / motivation**

It would be great if when PR is raised people will need only to handle the `X` part and provide a list of the `Y` part. Something like people need to write `XtoDataframe` or `XtoFile` and there is build in integration in Airflow that can handle the `FileToS3` `FileToGCS` etc... 

So when user is PR `MySQLToFile` Airflow will utilise this and auto create `MySQLToGCS` and `MySQLToS3`.

The idea is to build infrastructure layer once that will be automated for all.

**Comment by dinigo** [comment]
You are suggesting to implement kind of what we have with [GenericTransfer](https://github.com/apache/airflow/blob/master/airflow/operators/generic_transfer.py). I've thought of this too. We would need to have a common API for getting and sending files. Preferably a `flile-like-object` so transfers are done with a stream and they don't take storage.

I would rather have an `XtoYOperator` where I can configure the Hooks for each, source and destination, such as:
```
gcs_to_s3 = GenericFileTransfer(
  source_hook=GCSHook('gcs-conn-id'),
  dest_hook=S3Hook('s3-conn-id'),
  source_file='gs://my-gcs-bucket/my-file.csv',
  dest_file='my-s3-bucket/my-file.csv'
)

**Comment by turbaszek** [comment]
This issue may provide some alternative https://github.com/apache/airflow/issues/8059

**Comment by ashb** [comment]
See https://issues.apache.org/jira/browse/AIRFLOW-2651 for the previous discussion of this.

There was a pr #3526 but the interface/code wasn't quite right.

**Comment by dinigo** [comment]
@turbaszek I see how this is related, and I face this question frequently. But I think #8059 depends on having a common FS interface like   #3526 sugests. 

Right now we have (I might miss some) the following file providers: S3, GCS, Azure, SFTP/SSH, FTP, Samba. If we want to allow all operations between them it means  it's `N^2 - N` operators. It's 36 operators. And will be more as other cloud providers are added (Alibaba, DO, ...). I'll give a look at the PR @ashb , thanks.

**Comment by jrderuiter** [comment]
Would be interesting to implement this using fsspec (https://filesystem-spec.readthedocs.io/en/latest/). A single fsspec hook would provide an interface to all filesystems supported by fsspec, which includes Azure Blob/GDL2, S3 and GCS. You also get others like FTP and SFTP for free too (https://filesystem-spec.readthedocs.io/en/latest/api.html#implementations).

**Comment by RNHTTR** [comment]
Given there are already so many transfer operators (e.g. [AWS transfers](https://github.com/apache/airflow/tree/main/airflow/providers/amazon/aws/transfers)), I think implementing something like this would be more trouble than it's worth.
