### ISSUE TITLE
Broken : JS Code in Head Master is Broken

### ISSUE THREAD

**Issue by r39132** [apache/airflow#881]
Refer to image.......
<img width="825" alt="screenshot 2016-01-15 18 32 30" src="https://cloud.githubusercontent.com/assets/581734/12369989/737e59b0-bbb6-11e5-9262-9797b34c71ad.png">

The top of my git log is shown below: 

```
commit 692014d8c2691351751c3921b99a92f99acca3f9
Merge: 459ec4c 3846abc
Author: Maxime Beauchemin <maximebeauchemin@gmail.com>
Date:   Fri Jan 15 10:12:11 2016 -0800

    Merge pull request #879 from thibault-ketterer/readme_update

    Readme update

commit 3846abcb038e3743f9004b05dd9f359b329c4723
Author: thibault ketterer <thekit@gmail.com>
Date:   Fri Jan 15 17:11:04 2016 +0100

    [readme] rename link
```

**Comment by r39132** [comment]
Hmn.. it looks like the issue is related to minified JS files not being found.. 
<img width="658" alt="screenshot 2016-01-19 12 20 46" src="https://cloud.githubusercontent.com/assets/581734/12430904/31fc567e-bea7-11e5-9489-9c2b91cd508d.png">

**Comment by mistercrunch** [comment]
What's your `flask-admin` version? Share the output of `pip freeze | grep -i flask`

**Comment by r39132** [comment]
deploy@workflow-00:~$ pip freeze | grep -i flask
Flask==0.10.1
Flask-Admin==1.4.0
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-WTF==0.12

**Comment by mistercrunch** [comment]
That `admin/admin` thing look bad. Plugins messing up your blueprints? If you have plugins can you try turning them off temporarily?

**Comment by r39132** [comment]
I don't use plugins.. don't actually know what they are.

Also, the `admin/admin` paths are the same on our current production machine, which work fine. Our production machine is running on post `1.6.1` code and has the following as its latest git log entry:

```
commit 715b98509c4155137c50eb6e8396dbe6873c6c8a
Merge: deb891c 7e7cc4e
Author: Maxime Beauchemin <maximebeauchemin@gmail.com>
Date:   Thu Dec 17 21:18:44 2015 -0800

    Merge pull request #782 from airbnb/close_conn

    [core] Closing db connection during execution
```

**Comment by r39132** [comment]
It looks like some of the JS is available, but some are missing.

On the main DAG overview page for example, I see the following as either available or missing:
**Available**
- `/admin/admin/vendor/select2/select2.min.js`
- `/admin/admin/bootstrap/bootstrap3/js/bootstrap.min.js`
- `/static/jqClock.min.js`
- `/admin/admin/vendor/bootstrap-daterangepicker/daterangepicker.js?v=1.3.22`
- `/admin/admin/admin/js/form.js?v=1.0.0`
- `/static/d3.v3.min.js`

**Missing (404)**
- `/admin/admin/vendor/jquery-2.1.1.min.js`
- `/admin/admin/vendor/moment-2.8.4.min.js`

**Comment by marcelmfs** [comment]
This might also be related https://github.com/airbnb/airflow/issues/726

**Comment by syvineckruyk** [comment]
@r39132 did you ever find a solution to this ... just upgraded to the airbnb_prod branch and now facing the same issue.

![image](https://cloud.githubusercontent.com/assets/335167/13327217/d2e0df16-db9d-11e5-83ee-1a133609457f.png)

**Comment by mistercrunch** [comment]
Do a clean install of `flask_admin`,

```
pip unsintall flask_admin
pip install flask_admin==1.4.0
```

**Comment by syvineckruyk** [comment]
no dice

**Comment by syvineckruyk** [comment]
@mistercrunch @r39132 
Just did a clean install of airbnb_prod.1.6.2.3 and got the same issue.

FYI I was running airbnb_prod.1.6.1.3 before.

**Comment by mistercrunch** [comment]
What's your flask_admin version?
`pip freeze | grep -i admin`

**Comment by mistercrunch** [comment]
you may need a `sudo pip uninstall flask_admin`

**Comment by syvineckruyk** [comment]
(airflow) [airflow@usw2dbdpag01 ~]$ pip freeze | grep -i admin
Flask-Admin==1.4.0
(airflow) [airflow@usw2dbdpag01 ~]$

**Comment by mistercrunch** [comment]
Are you in a virtualenv? If so nuke it and make a new one maybe.

**Comment by syvineckruyk** [comment]
did that ... multiple times ... also tried master same issue ... reverting to 1.6.1.3 fixes it ... ill keep working on it in the morning. is jquery installed by flask-admin ?

**Comment by mistercrunch** [comment]
Yeah flask-admin ships with jquery and we piggyback on it

**Comment by mistercrunch** [comment]
maybe grep your whole box for `jquery-2.1.1.min.js` to see where that is coming from

**Comment by syvineckruyk** [comment]
@mistercrunch found the problem ... isolating the root cause ... need to install on a new environment to make sure that it's not caused by artifacts on my system .. but i doubt it since it's isolated in a virtualenv. Details to follow shortly .. got to get to work.

**Comment by syvineckruyk** [comment]
@mistercrunch got it ... post mortem and PR coming today .. I really need to leave for work now :)

**Comment by syvineckruyk** [comment]
@mistercrunch got a few issues to deal with ... so not sure if I'll get around to submitting a proper fix today. It looks like the cleanup step in setup.py is not working and a file which was removed from the repo at some point (airflow/www/templates/admin/base.html) is remaining in the build directory which is not being deleted and then being installed even though it's no longer in the repo. 

A clean repo, clearing the build artifacts,  or removing that file from the installation solves the issue. Maybe you could have a step at the beginning of setup.py that deletes existing build artifacts.

```
(airflow) [airflow@usw2dbdpag02 airflow]$ git status
# On branch gd_prod_1.6.2.3
nothing to commit (working directory clean)
(airflow) [airflow@usw2dbdpag02 airflow]$ ls -lha airflow/www/templates/admin/
total 12K
drwxr-xr-x. 2 airflow airflow 4.0K Feb 25 23:33 .
drwxr-xr-x. 4 airflow airflow 4.0K Feb 25 23:33 ..
-rw-r--r--. 1 airflow airflow 2.5K Feb 25 23:33 master.html
(airflow) [airflow@usw2dbdpag02 airflow]$ ls -lha build/lib/airflow/www/templates/admin/
total 16K
drwxr-xr-x. 2 airflow airflow 4.0K Feb 25 23:33 .
drwxr-xr-x. 4 airflow airflow 4.0K Feb 25 23:04 ..
-rw-r--r--. 1 airflow airflow 3.8K Feb 25 23:04 base.html
-rw-r--r--. 1 airflow airflow 2.5K Feb 25 23:33 master.html

```

I've noticed the build artifacts not getting deleted on both my servers and my mac.

**Comment by syvineckruyk** [comment]
making sure you clean on install also does the trick.
python setup.py clean extra_clean install

**Comment by syvineckruyk** [comment]
@r39132 I believe this will also solve the issue for you
