### ISSUE TITLE
Add ability to filter dag list by clicking on specific tag

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#8821]
**Description**

tags was added in https://github.com/apache/airflow/pull/6489
it would be great if by clicking a tag it will show all the tags associated to this tag.
Similar to how filter tags search bar works just without the need to type.

**Comment by mik-laj** [comment]
Hi. It makes sense. Would you like to work on this change?

**Comment by Sangarshanan** [comment]
I could pick this up if this is not taken yet?

**Comment by mik-laj** [comment]
@Sangarshanan I assigned you to this ticket. I look forward to your contributions. 🐈
