### ISSUE TITLE
Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.     Please install the service specific packages prefixed by `azure` needed for your application.

### ISSUE THREAD

**Issue by Nick-0723** [apache/airflow#8838]
**Apache Airflow version**: 1.10.10

**What happened**: when use pip install all dependencies `pip-3.6 install apache-airflow[all]`
```txt
Collecting azure-storage>=0.34.0; extra == "all" (from apache-airflow[all])
  Using cached https://files.pythonhosted.org/packages/5d/cd/cac628adf6cb0086a24c20d76609445f1bf841483d56ec9f5645bbaa9ab7/azure-storage-0.37.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-build-bqgrrvz0/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
```
**What you expected to happen**: successful install

**Comment by potiuk** [comment]
Yep.  Noticed that last night: #8833

**Comment by potiuk** [comment]
Not much we can do for 1.10.10 but if you follow the recommended installation method, airflow should still install cleanly https://github.com/apache/airflow/blob/master/README.md#installing-from-pypi

**Comment by francois-travais** [comment]
It's a shame the documentation is not inline with the README : https://airflow.apache.org/docs/stable/installation.html

**Comment by potiuk** [comment]
@francois-travais - what exactly do you think should be there? I am happy to update what is missing so that we can release in 1.10. Any suggestions please :) ?

**Comment by francois-travais** [comment]
Yes it's about the `--constraints`.
I think this section https://github.com/apache/airflow/blob/master/README.md#installing-from-pypi should be in the documentation and not just in the README.

**Comment by potiuk** [comment]
Indeed @francois-travais. Added issue for that with 1.10.11 as the milestone target. https://github.com/apache/airflow/issues/8860

**Comment by potiuk** [comment]
This is being handled in #12188
