### ISSUE TITLE
"Dag Runs" UI page shows broken State after enabled DAGs serialization

### ISSUE THREAD

**Issue by mshalak-nix** [apache/airflow#8839]
**Apache Airflow version**: 1.10.10

**Kubernetes version**: 1.15.11

- **Cloud provider**: Google Cloud

**What happened**:

After switching DAGs serialization on, "State" column in UI shows HTML code for all DAGs on the "Dag Runs" page. "Task Instances" page works fine.
![image](https://user-images.githubusercontent.com/57914365/81667874-85b6da80-944c-11ea-9704-49cc6c553f48.png)

**What you expected to happen**:

"State" column should not show HTML code.

**How to reproduce it**:
Switch serialization on using env var AIRFLOW__CORE__STORE_SERIALIZED_DAGS=true. Then open the "Dag Runs" page.

**Comment by davido912** [comment]
Experiencing the same problem here. However, I am not sure if this has to do with seralization because on my end it is set to False.

**Comment by enriqueayala** [comment]
Having same issue for versions 1.10.10/ 1.10.9  and store_serialized_dags=False/True  . 

No solution found yet..

**Comment by enriqueayala** [comment]
From slack response: https://apache-airflow.slack.com/archives/CCR6P6JRL/p1590309858271500 

> Easy fix: use the RBAC UI ;)

> We'll fix it in 1.10.11

**Comment by eladkal** [comment]
Duplicated of https://github.com/apache/airflow/issues/8717
Fixed in https://github.com/apache/airflow/pull/9612
