### ISSUE TITLE
Date Time Parsing Issue in Frontend when running DAGs

### ISSUE THREAD

**Issue by MJFND** [apache/airflow#8842]
**Apache Airflow version**: 1.10.10

**What happened**: Seeing issue when running DAGs with any execution dates from the UI 
<img width="1082" alt="" src="https://user-images.githubusercontent.com/12442542/81700178-c3822600-9481-11ea-92c5-3c32c7211988.png">

**What you expected to happen**: Should Parse the date correctly

**What do you think went wrong**: It is not able to parse the time in the datetime. Looks a Frontend bug as command line did not have that issue.

**How to reproduce it**: Go the the UI and try to rerun a DAG with any execution dates.

**Comment by kglazunov** [comment]
I've got the same issue with Version : 1.10.10

**Comment by realradical** [comment]
same issue, had no problem with 1.10.9
