### ISSUE TITLE
[SQSSensor] max_messages template field issue

### ISSUE THREAD

**Issue by fgrotkowski** [apache/airflow#8844]
Hello,
I have the following code snippet:

```
calculate_available_databricks_slots = PythonOperator(
    dag = dag,
    task_id = 'calculate_available_databricks_slots',
    python_callable = _calculate_available_databricks_slots,
    provide_context = True
)
retrieve_sqs_messages = SQSSensor(
    dag = dag,
    task_id = 'retrieve_sqs_messages',
    sqs_queue = SQS_QUEUE_URL,
    aws_conn_id = None,
    max_messages = '{{ task_instance.xcom_pull(task_ids = "calculate_available_databricks_slots") }}',
    wait_time_seconds = 1,
    provide_context = True
)
```
When I run it I got the following error connected with max_messages param:
`Invalid type for parameter MaxNumberOfMessages, value: 3, type: <class 'str'>, valid types: <class 'int'>`
max_messages is templated field, but it's impossible to use it since I can't cast it do int.
Could you please help?

**Comment by kaxil** [comment]
Unfortunately, any templated_field can only be a str or an Iterable of string or recurse class that has template_field that is string. It can't be **int**
