### ISSUE TITLE
DuplicateTaskIdFound missing from exceptions.py in pypi package of Apr 9, 2020

### ISSUE THREAD

**Issue by ebrard** [apache/airflow#8859]
**Apache Airflow version**:

1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

NA

**Environment**:

NA

**What happened**:

`airflow initdb`

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 42, in <module>
    from airflow.models import DAG
  File "/usr/local/lib/python3.6/site-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 39, in <module>
    from airflow.exceptions import AirflowException, DuplicateTaskIdFound
ImportError: cannot import name 'DuplicateTaskIdFound'

**What you expected to happen**:

`DuplicateTaskIdFound` is not part of the file exceptions.py that ships with [pypi](https://files.pythonhosted.org/packages/b1/61/a40271d4cec58e52749b6bc8c703b11b0e6d4e4ab5bbcbaf177a6a1ee096/apache-airflow-1.10.10.tar.gz) for apache-airflow==1.10.10

**How to reproduce it**:

Install apache-airflow from pypi, run initdb for example

**Comment by kaxil** [comment]
I can't reproduce this error. `DuplicateTaskIdFound` is not a part of 1.10.10

**Comment by kaxil** [comment]
here is the code from 1.10.10 for the file that is show in the stacktrace.

https://github.com/apache/airflow/blob/96697180d79bfc90f6964a8e99f9dd441789177c/airflow/models/baseoperator.py#L39-L57
