### ISSUE TITLE
Add PyPI installation to airflow official docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8860]
**Description**

The information about constraints and installing from PyPi should be added to the docs before releasing 1.10.11

https://github.com/apache/airflow/blob/master/README.md#installing-from-pypi

**Use case / motivation**

People use official website/docs for installation and as discussed in https://github.com/apache/airflow/issues/8838#issuecomment-628021587 sometimes it's the only source, so having the mechanism of stable installation should be described there as well.

**Related Issues**

#8838

**Comment by kaxil** [comment]
Can this be closed? I think this is already covered by https://github.com/apache/airflow/pull/9889 and https://github.com/apache/airflow/pull/8513

WDYT @potiuk ?

**Comment by potiuk** [comment]
Yep
