### ISSUE TITLE
HttpHook.run method doesn't convert dict in 'data' parameter to json object

### ISSUE THREAD

**Issue by uncletoxa** [apache/airflow#8861]
**Apache Airflow version**: 1.10.10

**Environment**:

- **Others**:
requests==2.22.0    
requests-oauthlib==1.3.0 

**What happened**:

Execution of HttpHook leads to error (on the API serverside):
```
{"Error":"Could not read JSON: Unrecognized token 'format': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.apache.catalina.connector.CoyoteInputStream@50edfaf7; line: 1, column: 8]; nested exception is org.codehaus.jackson.JsonParseException: Unrecognized token 'format': was expecting 'null', 'true', 'false' or NaN\n at [Source: org.apache.catalina.connector.CoyoteInputStream@50edfaf7; line: 1, column: 8]"}
``` 
The reason was providing `dict` instead of `JSON formatted str` in `data` parameter of `http_hook.run()`.

**What you expected to happen**:

Airflow uses [request.Requests](https://github.com/psf/requests/blob/aeda65bbe57ac5edbcc2d80db85d010befb7d419/requests/models.py#L198) api which explicitly states 
```
:param data: the body to attach to the request. If a dictionary or
        list of tuples ``[(key, value)]`` is provided, form-encoding will
        take place.
```
Although currently that's not working for my case, the only way to send a payload is to provide json object.

**Anything else we need to know**:
Easy fix would be changing [docstring](https://github.com/apache/airflow/blob/96697180d79bfc90f6964a8e99f9dd441789177c/airflow/hooks/http_hook.py#L93) of HttpHook.run. Mb state that both dict and json object are acceptable.

**Comment by mik-laj** [comment]
Interesting. Do you want to work on it?  Can I assign you to this ticket?

Here is contributor guide:  https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

**Comment by saurabh7248** [comment]
Hey @mik-laj, can I try my hand at fixing this?

**Comment by mik-laj** [comment]
@saurabh7248 I assigned you to this ticket.

**Comment by ashb** [comment]
I don't think anything needs doing, the hook already supports extra arguments https://github.com/apache/airflow/blob/96697180d79bfc90f6964a8e99f9dd441789177c/airflow/hooks/http_hook.py#L100-L101

The request docs you linked to:

> :param data: the body to attach to the request. If a dictionary or
>        list of tuples ``[(key, value)]`` is provided, form-encoding will
>        take place.

Passing data is doing what is says -- _form_ encoding, as if this was a `<form>`  submitted by a browser.

If you want to submit json as the body, do `hook.run(json={'a': [1,2,3]})'

**Comment by ToxaZ** [comment]
@ashb but the functionatliy of HttpHook.run is still broken. I don't insist on fixing it, just fyi.
