### ISSUE TITLE
Additional extras

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8866]
**Description**

It would be great to be able to pass "ADDITIONAL_EXTRAS" build arg and add extras to the "base" extras of Production Docker image.

**Use case / motivation**

If someone wants to add just one extra, they might want to specify only that one extra to add rather than copy the whole list

**Related Issues**

It's been discussed in https://github.com/apache/airflow/issues/8605#issuecomment-628520489

**Comment by wittfabian** [comment]
Which name is better? 
"ADDITIONAL_EXTRAS" or "AIRLOW_ADDITIONAL_EXTRAS"

**Comment by potiuk** [comment]
I used to use AIRFLOW everywher, but ... AIRFLOW is the whole context so we know those are AIRFLOW extras :)
