### ISSUE TITLE
Documentation building is slow

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8874]
Hello, 

Building documentation takes over 10 minutes when only a small change has been made. I think it is worth analyzing whether this process cannot be speed-uo.
My propositions:

- incremental rebuilds:  Currently, building is always started from scratch, but Sphinx supports building only changed files
   https://github.com/apache/airflow/blob/master/docs/build#L51
   https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-E
- multiprocessing buidl: Sphinx support distributing the build over N processes in parallel, to make building on multiprocessor machines more effective. This may require changes(or monkey-patch) to external plugins.
   https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-E

Best regards,
Kamil

**Comment by ashb** [comment]
https://github.com/readthedocs/sphinx-autoapi/issues/191 if/when it comes would help too

**Comment by mik-laj** [comment]
We divided the documentation into smaller packages. Now building documentation for apache-airflow takes less than 2 minutes and for apache-airflow-providers-telegram even less than 20 seconds.
Closed by: https://github.com/apache/airflow/issues/11423
