### ISSUE TITLE
Displaying field templates and constructor parameters in scripts/list-integration.py

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#8893]
Hello,

We have script that allows us to display class names.
https://github.com/apache/airflow/blob/master/scripts/list-integrations.py
It would be nice if it were possible to display template fields and constructor parameters.  This should be available when you run this script with an additional option. The output should be available as CSV or JSON or JSONL. Constructor parameters from BaseOperator or BaseSensor should be ignored.
This tool is needed to review all operators to eliminate missing template fields in existing operators.

Related PR:
https://github.com/apache/airflow/pull/8870
https://github.com/apache/airflow/pull/8840
https://github.com/apache/airflow/pull/7198
https://github.com/apache/airflow/pull/7127
https://github.com/apache/airflow/pull/6656
https://github.com/apache/airflow/pull/5718
https://github.com/apache/airflow/pull/5490
https://github.com/apache/airflow/pull/5248
https://github.com/apache/airflow/pull/5097
https://github.com/apache/airflow/pull/4920
https://github.com/apache/airflow/pull/4691
https://github.com/apache/airflow/pull/3305
https://github.com/apache/airflow/pull/2981
https://github.com/apache/airflow/pull/2549
https://github.com/apache/airflow/pull/2480
https://github.com/apache/airflow/pull/2235
https://github.com/apache/airflow/pull/1808
https://github.com/apache/airflow/pull/996
and more

**Comment by maverick12345678** [comment]
Hey , I would like to work on it .

**Comment by mik-laj** [comment]
@maverick12345678 Assigned.  It really will be very helpful for me.

**Comment by maverick12345678** [comment]
I would like to have some insight on what exactly is having in this code ? @mik-laj

**Comment by mik-laj** [comment]
This file? What exactly code?
https://github.com/apache/airflow/blob/master/scripts/list-integrations.py

I want to have the following output  or equivalent:
```
airflow.providers.google.cloud.operators.datacatalog.CloudDataCatalogCreateEntryOperator;location,entry_group,entry_id,entry,project_id,retry,timeout,metadata,gcp_conn_id;,location,entry_group,entry_id,entry,project_id,retry,timeout,metadata,gcp_conn_id
```
First column - full qualified class name
Second column - template fields (comma separated)
Third column - constructor parameters - excluding BaseOperator (comma separated)

**Comment by maverick12345678** [comment]
> This file? What exactly code?
> https://github.com/apache/airflow/blob/master/scripts/list-integrations.py
> 
> I want to have the following output or equivalent:
> 
> ```
> airflow.providers.google.cloud.operators.datacatalog.CloudDataCatalogCreateEntryOperator;location,entry_group,entry_id,entry,project_id,retry,timeout,metadata,gcp_conn_id;,location,entry_group,entry_id,entry,project_id,retry,timeout,metadata,gcp_conn_id
> ```
> 
> First column - full qualified class name
> Second column - template fields (comma separated)
> Third column - constructor parameters - excluding BaseOperator (comma separated)
> 
> This will facilitate my further analysis of these operators, but for now we have to collect the data.

Okay ! Thanks for the heads up !

**Comment by mik-laj** [comment]
@maverick12345678 Do you need any help?

Users report related errors to us all the time.  Here a new ticket from yesterday.
https://github.com/apache/airflow/issues/9146

**Comment by maverick12345678** [comment]
I will convey the message. I am looking into the matter. Sorry for the delay

**Comment by edithturn** [comment]
@eladkal let me take this one.
