### ISSUE TITLE
Question about timeouts and background threads with PythonOperator

### ISSUE THREAD

**Issue by adambom** [apache/airflow#890]
Suppose I have the following PythonOperator within a DAG:

``` python
from threading import Thread
from time import sleep
from time import timedelta


def sleepy(bucket, **kwargs):
    t = Thread(target=sleep, args=(3600,))
    t.start()
    t.join()

op = PythonOperator(
    task_id='sleepy',
    python_callable=sleepy,
    execution_timout=timedelta(seconds=30), )
```

What is the expected/actual behavior of the python operator in this situation? The sleepy callable will take one hour to run, but the execution timeout is set to 30 seconds. Will the operator time out? What if there is an uncaught exception on the background thread?

**Comment by adambom** [comment]
For context, we have this exact problem with one of our production tasks. We have a `PythonOperator` with a 4 hour timeout that spins up several background threads to do a bunch of work. Rarely, the task will just hang forever without triggering a timeout. It could either be an uncaught exception happening on one of the background threads, or the task is just taking really long and never finishing for some reason.

I'm trying to understand the guarantees that airflow's scheduler is able to provide regarding multithreading with `PythonOperators`.

**Comment by mistercrunch** [comment]
I think that's more of a Python question than an Airflow question and that's beyond me to be honest. Maybe reading the code of the timeout context manager might help:
https://github.com/airbnb/airflow/blob/master/airflow/utils.py#L607

**Comment by t1m0thy** [comment]
I think in both cases of threads and child processes you will need to explicitly handle both:
a) exceptions raised in the remove thread/process
b) terminating (or somehow handling) the child thread/process when a timeout occurs in the parent, presumably with code passed to on_failure_callback.

For more depth, check out this discussion on SO about handling exceptions raised in threads.
http://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python

**Comment by adambom** [comment]
Thanks for pointing me in the right direction. I'll certainly look into your suggestions. Let's leave this issue open and I'll update it with what, if anything, I find.

**Comment by bolkedebruin** [comment]
@adambom please create a Jira issue to track further if you want to update
