### ISSUE TITLE
The test_celery_executor test fails transiently in CI

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8908]
**Apache Airflow version**:

Master - 2.0.0dev

**Environment**:

GitHub CI jobs.

**What happened**:

The Celery Executor test is transiently failing. I think this started to appear recently (so likely it is one of the optimizations implemented recently) 

You can see an example of such failure here but there are many more similar ones)

https://github.com/apache/airflow/runs/687537257?check_suite_focus=true#step:6:387

I think there were recently some optimizations done in this area and I believe it might be the root cause of this problem. Can you please help to solve that problem? I do not want to put that problem to Quarantine, as it looks like an awfully "real" problem.

```
/usr/local/lib/python3.7/site-packages/celery/result.py:333: in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
/usr/local/lib/python3.7/site-packages/celery/result.py:326: in throw
    self.on_ready.throw(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/vine/promises.py:244: in throw
    reraise(type(exc), exc, tb)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tp = <class 'Exception'>
value = Exception('<class \'sqlalchemy.exc.IntegrityError\'>((\'(psycopg2.errors.UniqueViolation) duplicate key value violates..."pg_type_typname_nsp_index"\\nDETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.\\n\',))')
tb = None

    def reraise(tp, value, tb=None):
        """Reraise exception."""
        if value.__traceback__ is not tb:
            raise value.with_traceback(tb)
>       raise value
E       Exception: <class 'sqlalchemy.exc.IntegrityError'>(('(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"\nDETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.\n',))
```

**What you expected to happen**:

The test succeeds consistently.

**How to reproduce it**:

Happens practically with every build on CI recently - randomly at one of several jobs that run the test. Some of the jobs succeed (with different backends), some of them fail. This happens often but it's not fully repeatable.

**Additional info**

Discussion in devlist: https://lists.apache.org/thread.html/r2b531ef5c4a31746843127fc313c939296f3957eceafe4c1753b0f6d%40%3Cdev.airflow.apache.org%3E

**Comment by mik-laj** [comment]
@auvipy  Can you look at it?

**Comment by auvipy** [comment]
seems to be an integrity error in sqla "pg_type_typname_nsp_index"\nDETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.\n',) 

if you can try celery and kombu from github master? it might be an issue of airflow code itself

**Comment by potiuk** [comment]
The problem is that it is transient - sometimes it works, sometimes it does not.

I also think it's an issue in the Airflow Code - likely connected to the optimizations recently made by@mik-laj  or @ashb . 

* I looked at the history of requirements.txt and celery version did not change since 20th of March
celery==4.4.2

* The error started to appear only few days ago. I believe it is likely caused by 

commit fc862a3edd010e65b9b3fe586855fe81807ee4e8
Author: Kamil Breguła <mik-laj@users.noreply.github.com>
Date:   Thu May 14 06:01:13 2020 +0200

    Do not create a separate process for one task in CeleryExecutor (#8855)

or maybe this:

commit fe4219112a63d6debf84bcfd644e1681854db85c
Author: Ash Berlin-Taylor <ash_github@firemirror.com>
Date:   Thu May 14 16:49:12 2020 +0100

    Don't use ProcessorAgent to test ProcessorManager (#8871)
    
    Some of our tests (when I was looking at another change) were using the
    ProcessorAgent to run and test the behaviour of our ProcessorManager in
    certain cases. Having that extra process in the middle is not critical
    for the tests, and makes it harder to debug the problem when if
    something breaks.
    
    To make this possible I have made a small refactor to the loop of
    DagFileProcessorManager (to give us a method we can call in tests that
    doesn't do `os.setsid`).

or this: 

commit 82de6f74aee199d916d113a65a40821ec8ca0c43
Author: Ash Berlin-Taylor <ash_github@firemirror.com>
Date:   Fri May 15 22:17:55 2020 +0100

    Spend less time waiting for DagFileProcessor processes to complete (#8814)
    
    In debugging another test I noticed that the scheduler was spending a
    long time waiting for a "simple" dag to be parsed. But upon closer
    inspection the parsing process itself was done in a few milliseconds,
    but we just weren't harvesting the results in a timely fashion.
    
    This change uses the `sentinel` attribute of multiprocessing.Connection
    (added in Python 3.3) to be able to wait for all the processes, so that
    as soon as one has finished we get woken up and can immediately harvest
    and pass on the parsed dags.
    
    This makes test_scheduler_job.py about twice as quick, and also reduces
    the time the scheduler spends between tasks .
    
    In real work loads, or where there are lots of dags this likely won't
    equate to much such a huge speed up, but for our (synthetic) elastic
    performance test dag.
    
    These were the timings for the dag to run all the tasks in a single dag
    run to completion., with PERF_SCHEDULE_INTERVAL='1d' PERF_DAGS_COUNT=1
    
    I also have
    
    PERF_SHAPE=linear PERF_TASKS_COUNT=12:
    
    **Before**: 45.4166s
    
    **After**: 16.9499s
    
    PERF_SHAPE=linear PERF_TASKS_COUNT=24:
    
    **Before**: 82.6426s
    
    **After**: 34.0672s
    
    PERF_SHAPE=binary_tree PERF_TASKS_COUNT=24:
    
    **Before**: 20.3802s
    
    **After**: 9.1400s
    
    PERF_SHAPE=grid PERF_TASKS_COUNT=24:
    
    **Before**: 27.4735s
    
    **After**: 11.5607s
    
    If you have many more dag **files**, this likely won't be your bottleneck.

**Comment by ashb** [comment]
82de6f7 is unlikely to be it, unless it exposed a timing vector to the problem by making tasks schedule quicker. Could be.

**Comment by ashb** [comment]
Current hypotheis:

https://github.com/celery/celery/blob/eef03a3d299a2e4c1a69926be56ca521f0d16779/celery/backends/database/session.py#L52-L60  (which just calls out to SQLA to do the work)

is not handling this race case where two processes check, find the table missing, and then both try to create it.

**Comment by ashb** [comment]
Trying this:

```
    @classmethod
    def setUpClass(cls):
        from celery.backends.database.session import SessionManager
        backend_uri = conf.get('celery', 'result_backend')
        __import__('pdb').set_trace()
        SessionManager().session_factory(backend_uri)
```

**Comment by ashb** [comment]
@auvipy Ah, that session factory wants the `db+` prefix stripped off already, what is the "right" way in celery to get hold of the configured backend?

**Comment by ashb** [comment]
I mean the _best_ fix here would be if SQLA emited these as `CREATE TABLE IF NOT EXISTS x`, rather than checking which tables exist and then emiting `CREAT TABLE x`.

**Comment by potiuk** [comment]
Thanks @ashb  -> great that you fixed it  :)
