### ISSUE TITLE
Passing in parameters for externally triggered dags

### ISSUE THREAD

**Issue by jasminetsai** [apache/airflow#891]
Are there any near-term plans to allow that?

**Comment by mistercrunch** [comment]
Not on the Airbnb side as far as I can tell.

**Comment by r39132** [comment]
Hi @jasminetsai!
I had a similar request to pass parameters via `airflow run/test/backfill` commands. It would be great if you could tackle this problem -- I'd be happy to review a PR.

**Comment by r39132** [comment]
@jasminetsai This is now supported in the CLI itself thanks to @mistercrunch

This is also documented on https://www.linkedin.com/pulse/airflow-lesson-1-triggerdagrunoperator-siddharth-anand

**Comment by jasminetsai** [comment]
Thanks for the heads up!

On Sun, Feb 21, 2016 at 8:31 PM, Sid Anand notifications@github.com wrote:

> Closed #891 https://github.com/airbnb/airflow/issues/891.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airbnb/airflow/issues/891#event-558975913.

## 

Jasmine Y. Tsai
+1 415 812 2219
