### ISSUE TITLE
Impala Hook

### ISSUE THREAD

**Issue by blcksrx** [apache/airflow#8916]
**Description**

Impala Hook

**Use case / motivation**

**Related Issues**

**Comment by bdsoha** [comment]
Any updates on this?

**Comment by potiuk** [comment]
@bdsoha feel free to take it on and implement it.

 Generally things here are not implemented unless someone volunteers to implement it. So if you are really interested, implementing it and contributing back is the fastest way to get it implemented (you can also try to find someone who would do that).

This is how things work in Open-source.

**Comment by bdsoha** [comment]
> @bdsoha feel free to take it on and implement it.
> 
> Generally things here are not implemented unless someone volunteers to implement it. So if you are really interested, implementing it and contributing back is the fastest way to get it implemented (you can also try to find someone who would do that).
> 
> This is how things work in Open-source.

I was asking because of @blcksrx existing PR.
