### ISSUE TITLE
Add some "sensitive file" to include in "dock-only CI pytestless builds

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8921]
**Description**

Currently we skip tests when no .py files change. But this does not take into account much rarer situations when Dockerfile.ci, setup.cfg and few other files change. 

We should add those files to the detection of whether to run the builds or not.

**Use case / motivation**

Sometimes we need to fix Dockerfile.ci for example and it woudl be great to see if the tests are still fine.

**Comment by ashb** [comment]
@potiuk Are you actively working on this right now? If not I'd like to try it so I get to know the new CI a bit better.

**Comment by ashb** [comment]
Taking silence as consent - PR incoming :)

**Comment by potiuk** [comment]
Feel free :)
