### ISSUE TITLE
Jenkins connection edit is not working on Web Server

### ISSUE THREAD

**Issue by ptamorri** [apache/airflow#8930]
Hi to all,
i'm using Airflow version 1.10.10 (the actual latest) and get error page everytime i try to modify a Jenkins connection.
If i delete it and recreate it, it works.

I'm using Kubernetes azure service.

Adding trace too, i think it will be an easy fix :)

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 69, in inner
>     return self._run_view(f, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 368, in _run_view
>     return fn(self, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/flask_admin/model/base.py", line 2154, in edit_view
>     self.on_form_prefill(form, id)
>   File "/usr/local/lib/python3.8/site-packages/airflow/www/views.py", line 3203, in on_form_prefill
>     value = d.get(field, '')
> AttributeError: 'bool' object has no attribute 'get'

Problem occurs everytime i click on "edit" button of a Jenkins connection in Web server UI.

Thanks

**Comment by ashb** [comment]
Fixed with latest provider modules.
