### ISSUE TITLE
Graph to see DAG run duration metric

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#8931]
**Description**

airflow has many graph showing insights on task level (task duration, task tries, landing times, gantt)
yet there are no graphs that show metrics on graph level

I have a simple question that I want to see in a graph. Did the overall time the dag runs has increased  or not? it can be simple graph just calculating the dag start time and stop time and putting all durations on one graph.

something like:
![chart](https://user-images.githubusercontent.com/63792998/82488142-198d4400-9ae8-11ea-93d8-703675c37b28.png)

would be extra cool if it will allow to play with the duration units (seconds, minutes, hours, days)

**Comment by JeffryMAC** [comment]
is anyone know a good way to get this data from the backend db? is anyone monitoring such thing in their own internal system?

**Comment by mik-laj** [comment]
I think it's best if you use Data Studio and you connect directly to the database.
Here is a guide for PostgresSQL:
https://support.google.com/datastudio/answer/7288010?hl=en
Here is a guide for MySQL:
https://support.google.com/datastudio/answer/7088031?hl=en

**Comment by JeffryMAC** [comment]
thx @mik-laj  is there any documentation on how to add more graphs to the UI?

**Comment by mik-laj** [comment]
@JeffryMAC I haven't seen it, but we use [FAB](https://flask-appbuilder.readthedocs.io/en/latest/) to build views and [nvd3](https://pypi.org/project/python-nvd3/) as a graph library

**Comment by JeffryMAC** [comment]
Played around some and I couldn't find easy way to set this up.
I really think that airflow needs to support this natively.
Have a graph that shows run time (duration) of the whole dag end to end with trend so we can detect which dag runs take long time and should be investigated.

**Comment by turbaszek** [comment]
@JeffryMAC I somehow agree that having nice stats in Airflow itself would be a nice feature. I did some work around that in #11631

**Comment by JeffryMAC** [comment]
@turbaszek that looks very cool and it's very useful I'm sure.
But this issue is around data that already available in Airflow database it just need a proper presentation in the UI.

I really feel that Airflow can improve in the graphs it shows in the UI and allow users to better understand what is going on.
Graphs can make it really easy to spot problems.

**Comment by bbovenzi** [comment]
I'm working on some updates to tree view that will address this.

**Comment by bbovenzi** [comment]
This is now in the Grid view.
