### ISSUE TITLE
change from zdesk to zenpy in ZendeskHook

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#8937]
**Description**
[zdesk ](https://github.com/fprimex/zdesk) hasn't been updated in two years.
there is a better maintained package [zenpy](https://github.com/facetoe/zenpy)

The [ZendeskHook](https://github.com/apache/airflow/blob/master/airflow/providers/zendesk/hooks/zendesk.py#L21)  needs to be refactored to work with the new package.

**Comment by bhaveshpatel640** [comment]
@eladkal @potiuk  I will give it a shot, Thanks!

**Comment by xrmx** [comment]
Looking at the zenpy code it looks like that every endpoint is wrapped in a class, see https://github.com/facetoe/zenpy/blob/master/zenpy/__init__.py#L97. Can't see a sane way to map the plain path to a class to keep backwards compatibility. Said that we can leverage the `BaseApi` class in https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py to get ratelimit handling for free. Do you have any thoughts?

**Comment by RosterIn** [comment]
@xrmx Since the old package isn't maintained and can't have new functionality I think this change is required even if breaking change. Also Airflow soon change major version which is great because it will be able to introduce breaking changes.
I think better to hear from the project owners @potiuk @kaxil @mik-laj

**Comment by kaxil** [comment]
Yes I agree, let's use zenpy since zdesk seems to be abandoned.

**Comment by eladkal** [comment]
@xrmx do you want to work on this task?

**Comment by xrmx** [comment]
@eladkal nope

**Comment by thelderop** [comment]
I'll give this a shot!

**Comment by mik-laj** [comment]
I assigned you to this ticket.

**Comment by pierrejeambrun** [comment]
Hi,

I can work on this one :)

**Comment by uranusjr** [comment]
Go ahead

**Comment by eladkal** [comment]
@pierrejeambrun are you still working on this issue?

**Comment by pierrejeambrun** [comment]
Hello @eladkal 

I didn't start yet, I wanted to close this one first https://github.com/apache/airflow/pull/20386 but it's taking a little longer than expected. I think it's ready now and I can start working on this one :)
