### ISSUE TITLE
next_execution_date is not a pendulum instance

### ISSUE THREAD

**Issue by danly** [apache/airflow#8939]
**Apache Airflow version**: 1.10.2

**What happened**:
[According to the docs](https://airflow.apache.org/docs/stable/macros-ref.html) `next_execution_date` is a pendulum instance:

> the next execution date (pendulum.Pendulum)

However, when trying to call `start_of` method of `next_execution_date` it is a `datetime.datetime` instance.

Code:
```python
def execute(**kwargs):
  next_execution_date = kwargs.get('next_execution_date')
  stop = next_execution_date.start_of('day')
  #...
```

Error Log:
```
Subtask my_task stop = next_execution_date.start_of('day')
Subtask my_task AttributeError: 'datetime.datetime' object has no attribute 'start_of'
```

**How to reproduce it**:
Try calling pendulum methods from `next_execution_date`

**Stop-gap**:
As a temporary fix, I am creating a pendulum instance from the `datetime.datetime` object.

```
def execute(**kwargs):
  next_execution_date = kwargs.get('next_execution_date')
  stop = pendulum.instance(next_execution_date).start_of('day')
  #...
```

**Comment by rootcss** [comment]
@danly I think, you're looking at the docs of the latest stable version. For v1.10.2 you can refer the docs here: https://airflow.apache.org/docs/1.10.2/code.html#macros - which mentions `{{ next_execution_date }}` an instance of `datetime.datetime`

**Comment by rootcss** [comment]
@mik-laj This can be closed.

**Comment by danly** [comment]
Thanks @rootcss I didn't realize I was looking at the wrong docs.
