### ISSUE TITLE
Move aws-cli out of the CI image

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8947]
**Description**

The awsli binary can be used from the docker image  https://hub.docker.com/r/amazon/aws-cli  and script written to hide pulling and mounting authorisation volumes to it.

**Use case / motivation**

When you run aws-cli command inside of the ci image in Breeze, aws-cli docker image is pulled automatically and is used to run awscli commands/

**Related Issues**

Umbrella issue #8785

**Comment by potiuk** [comment]
Closed  by #9129

**Comment by feluelle** [comment]
@potiuk closed this manually because it was not closed automatically.
