### ISSUE TITLE
logging output seems a little too verbose?

### ISSUE THREAD

**Issue by sayap** [apache/airflow#895]
We noticed that after commit 225e1ecb, the following log lines start to appear repeatedly from scheduler:

```
[2016-01-20 17:43:09,182] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
[2016-01-20 17:43:09,231] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
```

The reason seems to be that the INFO log level is applied to the root logger, instead of just doing `logging.getLogger('airflow').setLevel(LOGGING_LEVEL)`.

Perhaps all logging code shall be changed to be calling `LOG = logging.getLogger(__name__)` first, so that we can modify airflow log level independently?

**Comment by mistercrunch** [comment]
I also noticed that the logs got more verbose recently. I'm still somewhat challenged when trying to figure out proper logging best practices in Python. Allowing external modules to import Airflow and set logging level for it specifically is important. It seems like to do this we need to associate all airflow logging to `logging.getLogger('airflow')` ?

**Comment by sayap** [comment]
The documentation recommends `logging.getLogger(__name__)`:

> The logger name hierarchy is analogous to the Python package hierarchy, and identical to it if you organise your loggers on a per-module basis using the recommended construction `logging.getLogger(__name__)`. That’s because in a module, `__name__` is the module’s name in the Python package namespace.

https://docs.python.org/2/library/logging.html

If there is no objection, we will create a PR :grin:

**Comment by mistercrunch** [comment]
It seems reasonable, someone contributed a LoggingMixin class that we use in many places and it must follow the module namespace approach `+ '.' + classname`. It seems like it fits the model described with an extra level of detail. There must be a fair amount of orphan logging calls though. I'm happy reviewing PRs that move the needle in the right direction. 

https://github.com/airbnb/airflow/blob/5afe1d16f0b9930309fab2c912a33e2c3b16c250/airflow/utils.py#L765

**Comment by bolkedebruin** [comment]
@sayap Any Pr yet :)? Can you create a jira for it if you find the time?
