### ISSUE TITLE
Run task with ignoring all options doesn't work

### ISSUE THREAD

**Issue by jhettler** [apache/airflow#8951]
**Apache Airflow version**: 1.10.10

**Environment**: Docker official image 

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

If you check all options and press run, nothing happens, only pending in network. I can see only Adding to queue in logs nothing more.

[2020-05-21 13:30:32,078] {{base_executor.py:58}} INFO - Adding to queue: ['airflow', 'run', '01_DBT', 'EVERYONE.seduo_b2b_statistics_current', '2020-05-19T23:35:00+00:00', '-A', '-i', '--force', '--local', '--pool', 'default_pool', '-sd', 'DAGS_FOLDER/01_DBT.py']

![image](https://user-images.githubusercontent.com/6342027/82563690-cd89e000-9b77-11ea-939f-d93c1ed0cad8.png)

Clear works fine. It is related to RBAC mode, when we have it without RBAC it works fine.

**What you expected to happen**:

Run should start the task.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by doowhtron** [comment]
I have got the same issue.  And I found the webserver was blocked in file celery_executor.py line213

            send_pool = Pool(processes=num_processes)

**Comment by eladkal** [comment]
Is it still an issue in latest airflow version?
