### ISSUE TITLE
use separate pod_mutation_hook for Kubernetes Executor pod

### ISSUE THREAD

**Issue by fuyi** [apache/airflow#8965]
**Description**

According to the [Kubernetes Executor doc](https://airflow.apache.org/docs/stable/kubernetes.html),  pod_mutation_hook is used to mutate pod object before sending to the Kubernetes client for scheduling. 

We deploy Airflow in K8S environment and use both Kubernetes Executor and KubernetesPodOperator. We need to set almost completely different set of fields for Executor pod and KubernetesPodOperator pod. 

Since `pod_mutation_hook` is applied to all Pod creation requests, we have to check which type of pod in the function then add a different set of K8S fields.

Pseudo code:

```python

def pod_mutation_hook:
   if pod.type == 'kubernetes executor workers pod':
        pod.annotations['pod-type'] = 'kubernetes-executor-worker-pod'
   if pod.type == 'PodOperator pod': 
        pod.annotations['pod-type'] = 'pod-operator-pod'
```

The issues:

* It is not clear what fields are applied to what Pod type
* This is not good practice for separate of concerns.

**Use case / motivation**

I propose we keep `pod_mutation_hook` for mutating PodOperator pod and use a separate hook like `executor_pod_mutation_hook` to mutate Kuberenetes Executor pod.

**Comment by fuyi** [comment]
Yes, this works, I am currently using this approach to distinguish POd types. 

But would it be better to use a separate hook for separate types of Pod to separate the concern?

**Comment by dimberman** [comment]
@fuyi it's worth noting that there is a label injected by all KubernetesExecutor pods. Something like `is_kubernetes_executor_pod: true`. You can filter by this. I think creating a seperate hook might create some confusion. I'm going to close this for now, though if you want to propose it to the mailing list would be interested in discussing further with the larger community.
