### ISSUE TITLE
2.0.0-dev - Webserver front page missing dag_id for dag runs and task instances

### ISSUE THREAD

**Issue by dimitrijepetrovic** [apache/airflow#8966]
When trying to view task_isntance list or dag_run (by clicking on circles on the front page)
dag_id field is passed as undefined

dags.html (line 430) - value of "d" is undefined
`
          .on('click', function(d, i) {
            if (d.count > 0)
              window.location = "{{ url_for('DagRunModelView.list') }}?_flt_3_dag_id=" + d.dag_id + "&_flt_3_state=" + d.state;
          })
`

**Comment by kaxil** [comment]
Fixed by https://github.com/apache/airflow/commit/836f717d316d6b20bc2f2bc07d781dd332618471
