### ISSUE TITLE
New users through UI after setting up admin through REPL

### ISSUE THREAD

**Issue by sergiohgz** [apache/airflow#897]
Hello everyone,

We are now in make secure our Airflow instance and advice that with password method, every new user must be made though Python REPL. A good enhancement would be that using password method, after setting the first user, it could act as the administrator of the system and can provide new users through UI. Other posibility would be that after setting first user, every user created from UI is provided by other user and can set password and every field in that.

Think about that and we could make a good collaboration with this enhancement.

Thank you so much

**Comment by r39132** [comment]
+1 on the first approach. We need to have 2 types of users:
- Admin
- non-admin
