### ISSUE TITLE
Use type hints to indicate multiple return values when using @task

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#8996]
**Description**

Use type hints to indicate multiple return values of `@task` decorated function to improve dereferencing. 

Using type hints to enhance code behaviour is for example done in:
https://databricks.com/blog/2020/05/20/new-pandas-udfs-and-python-type-hints-in-the-upcoming-release-of-apache-spark-3-0.html

**Use case / motivation**

Currently: 
```python
@task(multiple_outputs=True)
def my_function():
    return 1, 2, 3
```
expected:
```
@task
def my_function() -> Tuple[int, int, int]:
    return 1, 2, 3
```

**Related Issues**
https://github.com/apache/airflow/pull/8962/files#r429341828
https://github.com/apache/airflow/pull/8962/files#r428948073

**Comment by AndersonReyes** [comment]
@turbaszek is this in todo? I want to give it a shot

**Comment by AndersonReyes** [comment]
after some googling looks like this can be achieved like this 

```
....
    if python_callable:
        sig = signature(python_callable).return_annotation
        if get_origin(sig) in (dict, tuple):
            multiple_outputs = True
....
```

**Comment by vikramkoka** [comment]
@kaxil , @turbaszek  Should this be in beta1 from the perspective of feature complete?

**Comment by turbaszek** [comment]
> @kaxil , @turbaszek Should this be in beta1 from the perspective of feature complete?

@vikramkoka I would say this adds only a syntax sugar not a "real feature"

**Comment by potiuk** [comment]
Hey @turbaszek -> is ti somethig we want to add fo 2.0.0rc1 ? Or should we postpone to 2.1 ? If so - can you change the milestone please?
