### ISSUE TITLE
Tutorial documentation with bash_command correction

### ISSUE THREAD

**Issue by mans2singh** [apache/airflow#8999]
**Description:**

Correction in tutorial documentation regarding bash_command

**Issue:**

- The bash_command with shell file is as follows:

> ``bash_command='templated_command.sh'``, where the file location is relative to

But perhaps should be:

> ``bash_command='templated_command.sh '``, where the file location is relative to

**Comment by turbaszek** [comment]
Not sure what the issue is, @mans2singh can you explain?

**Comment by eladkal** [comment]
I assume @mans2singh is referring to the issue related to Jinja where you need to[ add space](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/bash.html#jinja-template-not-found) at the end of the script. This is mentioned at the Jinja section of the doc.

The problem refers to is doc:
https://github.com/apache/airflow/blob/master/docs/apache-airflow/tutorial.rst#templating-with-jinja

I'll fix it soon
