### ISSUE TITLE
Is it possible to create a recyclable Dag without schedule

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#900]
I made a data transfer from csv files to hive tables.
There are over hundred tables. I create hundred task to complicating move data from csv to hive table. I also via the Pool to balance the server performance.

I want to get the latest data ASAP. So I may need a loop schedule. The 2nd round will be run after 1st round. The 3rd round will be run after 2nd. However, airflow look like does not support this function. I have to created shorter schedule(like 30 minutes). There are two issue with this solution:
1. It hard to control the time. Sometimes 30 minutes is not enough, sometimes 30 minutes is waste.
2. It easy to accumulation dags. For example, the Dag crashed in weekend. I fixed it in the next week. But I will get 2 days \* 24 \* 2 Dag runs.

I also tried use ShortCircuitOperator to skip some tasks by execution_date. But the skip is slow because I have many tasks in the Dag.

Is there a Best Practices for the scene?

Thank you,
Griffin

**Comment by r39132** [comment]
It doesn't sound like Airflow is the right solution for a few reasons. For one, you don't want to execute on a fixed schedule. You essentially want to be notified when new data arrives -- when it does, you want to execute a transformation to hive.

If you were using AWS, I'd recommend that you drop your csv files to S3. You can set S3 up to publish new object notifications via SNS/SQS. You can then write a SQS consumer to read the SQS notifications, pull the csv objects out of S3, transform it, and then insert it into Hive. 

This is a continuous process.. and does not rely on a schedule. It's okay to have some ad-hoc DAGs and tasks in airflow that are not tied to a schedule, but often they will be triggered by some other job that is running on a schedule.

**Comment by r39132** [comment]
FYI, you can create a DAG that is not scheduled : `schedule_interval=None` 

You can then use an Sensor to detect new data - e.g. S3 Sensor to detect new data S3 and have it trigger your DAG to run!

**Comment by griffinqiu** [comment]
hmmm, if the DAG scheduled is none. The Sensor which in the DAG will run ?

**Comment by griffinqiu** [comment]
I got it, you mean use the External Triggers

**Comment by jasminetsai** [comment]
Do you have any sample patterns//code for this by chance?

**Comment by mistercrunch** [comment]
```
dag = DAG('foo', schedule_interval=None)
```

**Comment by jasminetsai** [comment]
Sorry I meant triggering another dag from within one DAG- what is the
recommended way to do that? Bash operator with the cli or is there another
interface?

On Tuesday, February 2, 2016, Maxime Beauchemin notifications@github.com
wrote:

> dag = DAG('foo', schedule_interval=None)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airbnb/airflow/issues/900#issuecomment-178657127.

## 

Jasmine Y. Tsai
+1 415 812 2219

**Comment by mistercrunch** [comment]
http://pythonhosted.org/airflow/code.html#airflow.operators.TriggerDagRunOperator

**Comment by griffinqiu** [comment]
Thanks
