### ISSUE TITLE
"COPY ${AIRFLOW_SOURCES_FROM} ${AIRFLOW_SOURCES_TO}" failed on local build

### ISSUE THREAD

**Issue by wittfabian** [apache/airflow#9003]
**Apache Airflow version**: 1.10.10

**Environment**:

- **OS**: Windows 10 / Docker Desktop

**What happened**:
According to the documentation it should be possible to build the image with the following command:

```
docker build . \
  --build-arg PYTHON_BASE_IMAGE="python:3.7-slim-buster" \
  --build-arg PYTHON_MAJOR_MINOR_VERSION=3.7 \
  --build-arg AIRFLOW_INSTALL_SOURCES="apache-airflow" \
  --build-arg AIRFLOW_INSTALL_VERSION="==1.10.10" \
  --build-arg CONSTRAINT_REQUIREMENTS="https://raw.githubusercontent.com/apache/airflow/1.10.10/requirements/requirements-python3.7.txt" \
  --build-arg ENTRYPOINT_FILE="https://raw.githubusercontent.com/apache/airflow/1.10.10/entrypoint.sh" \
  --build-arg AIRFLOW_SOURCES_FROM="entrypoint.sh" \
  --build-arg AIRFLOW_SOURCES_TO="/entrypoint"
```
(https://github.com/apache/airflow/blob/v1-10-stable/IMAGES.rst#production-images)

**_Docker build failed with:_**

```
Step 32/90 : COPY ${AIRFLOW_SOURCES_FROM} ${AIRFLOW_SOURCES_TO}
COPY failed: stat /var/lib/docker/tmp/docker-builder025357303/entrypoint.sh: no such file or directory
```

Before step 32 the required file "entrypoint.sh" is not provided/added.

**What you expected to happen**:
Successful build.

**How to reproduce it**:
Run the build command.

**Comment by potiuk** [comment]
Yes. It's possible to build it from the sources. Apparently you only copied Dockerfile but not the entrypoint.sh which is needed as well. It's even written in the instructions [IMAGES.rst](https://github.com/apache/airflow/blob/master/IMAGES.rst) :

> This builds production image in version 3.6 with default extras from the local sources

You can build the image without entrypoint.sh present locally - but then it will need to be downloaded from the selected TAG in github. T

**Comment by potiuk** [comment]
You could also use 

```
  --build-arg AIRFLOW_SOURCES_FROM="Dockerfile" \
  --build-arg AIRFLOW_SOURCES_TO="/dockerfile"
```

if you really want a standalone Dockerfile build. Feel free to make PR to update that in the documentation - I am happy to review it.

**Comment by wittfabian** [comment]
Oh, then I misunderstood.
I thought with `--build-arg ENTRYPOINT_FILE="https://raw.githubusercontent.com/apache/airflow/1.10.10/entrypoint.sh"` that would be possible.

**Comment by wittfabian** [comment]
We need additional Airflow extras and Python dependencies for our production environment. The only possibility is to take over the github repo and build it in our own source control. Or is there a better solution?

**Comment by potiuk** [comment]
Will be there soon #8604 #8866 .. But if you want to make PR - feel free :)
