### ISSUE TITLE
Hive Operator mapred_job_name_template missing from config template

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#9005]
**Apache Airflow version**:
2.0.0.dev , 1.10.*

**What happened**:

Apache Hive Operator has `mapred_job_name_template` config param which is not included in any configuration description. It uses single curly braces {} for some hive-specific values (hostname, dag_id, task_id, execution_date) and this prevents putting the config variable into .cfg file because then Airflow will treat those names as environment variables to read from.

**What you expected to happen**:

HIveOperator should be updated to change this format to (for example) JINJA template, which would make it possible to put it in config and have some default values defined (with {{}} ) similarly to other parameters, 

**How to reproduce it**:

Try to add default value to configuration yaml and run tests.  Tests will fail (either because hostname not defined or because the values will be wrong).

**Comment by eladkal** [comment]
@potiuk I think today this issue is a won't fix? why would we want a provider specific settings in `.cfg`?

**Comment by potiuk** [comment]
I am not sure if it is won't fix. I do not even know when/why this parameter have been added - but, well it is there in the .cfg file,  and I created that issue simply because I stumbled upon it. I think yeah - it should be deprecated and move toi the Hive Operator at the very least.

There are likely some historical reasons why "hive" section is there, but I agree, it shoudl be better to remove it and deprecate whole section. I left it as good-first-issue and maybe someone using Hive could fix it.

**Comment by eladkal** [comment]
I think the reason is just legacy.

Hive was/is deep integrated into core... Hive is the only one that even has [specific macros](https://github.com/apache/airflow/blob/main/airflow/macros/hive.py)  (which we didn't yet extracted to the Hive provider :/ )

**Comment by potiuk** [comment]
Ah yeah. Maybe we need "Decouple Hive from Airflow Core". And we can specifically make the MJOR release of apache.hive provider with breaking changes if we need those.

**Comment by eladkal** [comment]
Closing as stale issue
