### ISSUE TITLE
Use Terraform for System Testing

### ISSUE THREAD

**Issue by feluelle** [apache/airflow#9009]
**Description**

As @ashb @potiuk and me already shortly discussed in a slack thread..

We could use terraform for testing Airflow integrations with real services from providers.
Key benefits:
* Write declarative configuration files
* Plan and predict changes
* Create reproducible infrastructure

I didn't think about the implementation details (pytest + terraform) yet, but I think it would make it a lot easier using terraform instead of having to write a lot of system helper classes in python.

**EDIT:**

Some interesting resources: 
* https://www.fugue.co/blog/blog-post-creating-an-automated-cloud-infrastructure-testing-tool-with-terraform-and-pytest

**Comment by potiuk** [comment]
Absolutley!

**Comment by szha** [comment]
HashiCorp recently added a clause to their [term of evaluation](https://www.hashicorp.com/terms-of-evaluation) that forbids the usage of their enterprise software in China. While this may or may not affect this proposal, it does pose potential legal risk to contributors in China.

**Comment by turbaszek** [comment]
> I think it would make it a lot easier using terraform instead of having to write a lot of system helper classes in python.

In my opinion it depends... Is creating a single GCS bucket worth adding terraform? However, I fully support the idea for usting terraform to setup complex environment.

**Comment by potiuk** [comment]
Fully Agree with Tomek. Especially with some setup/teardown that is quick and can be repeated for each test every time, using terraform makes no sense. But when you have longer setup that is more complex and takes quite some time, this might be definitely worthwhile.

The usual scenario for that will be 

a) create  the environment -> terraform script

b) iterate on the tests 
alternating with
c) potentially changing target state of the environment - updating and re-running the terraform script applying the changes.

d) tear-down the environment (using terraform script to delete the environment).

**Comment by feluelle** [comment]
So what I have in mind is that the `def setUpClass` automatically `terraform init`s the infra located in `tests/providers/*/infrastructure` for a file named as the example dag file and should end with `.tf` **if exists**

What we could also do would be only running the terraform init for`tests/providers/*/infrastructure` once for all example dags when the providers system flag is used `--system amazon`.

> Is creating a single GCS bucket worth adding terraform?

@turbaszek in my opinion we should do it consistenly for all example_dags. Do you think it would be slow? Or what is your concern?
Under the hood terraform is also using the cli's we use to create resources for aws and google, right? So why not do it safely and more manageable using terraform? I think the biggest plus is that the infra automatically gets destroyed so we do not accidently let something exists longer as the test needs it.

**Comment by feluelle** [comment]
I have a question: When I am adding terraform to airflow and I want it through docker like it was done [here](https://github.com/apache/airflow/commit/a39e9a352050f96dedadc39ab3d985065971c98c) what volumes should I mount? I need to mount the .aws, .azure, etc. folder but also the folders containing the .tf files. How should I do it? Mount the whole airflow dir?

WDYT? @potiuk @turbaszek :)

**Comment by potiuk** [comment]
Yeah. Airflow sources are best. But for that, you will need to create a HOST_AIRFLOW_SOURCES variable (similarly as I do with HOST_HOME) as an environment variable and mount it as `/opt/airlfow`.

**Comment by potiuk** [comment]
And BTW. IT would be great to also add this mapping -v ${HOST_ARIFLOW_SOURCES}:/opt/airflow also to the other commands. We might wan to upload stuff to gcloud/aws as well.

**Comment by feluelle** [comment]
Terraform was introduced during #8877 

For further integration i.e. automatisation of system tests we can also use terraform but that should be a separate issue.
