### ISSUE TITLE
Update to Pendulum 2.1.0

### ISSUE THREAD

**Issue by thesuperzapper** [apache/airflow#9015]
**Description**

Currently, we use pendulum `1.4.4`, this is an old version, we should consider moving to `2.1.0`.

If we do this we should make it very public as it will break some jobs if users don't update names like `Interval` to `Duration`.

For pendulum changelog, [see here](https://pendulum.eustace.io/blog/category/releases/).

**Comment by mik-laj** [comment]
@thesuperzapper I think it's a good idea. Do you want to take care of it?

**Comment by waleedsamy** [comment]
+1

**Comment by nehiljain** [comment]
+1
