### ISSUE TITLE
DataProcPySparkOperator gives wrong arguments to GoogleCloudStorageHook upload() method in v1.10.10

### ISSUE THREAD

**Issue by alexandraabbas** [apache/airflow#9027]
**Apache Airflow version**: 1.10.10

- **Cloud provider or hardware configuration**: Local
- **OS** (e.g. from /etc/os-release): MacOS High Sierra 10.13.6
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 17.7.0
- **Install tools**: pip, conda
- **Others**: -

**What happened**:

Cannot upload local pyspark file when using DataProcPySparkOperator. 

```python
weekday = DataProcPySparkOperator(
        task_id='weekday_analytics',
        main='/pyspark/weekday/avg_speed.py',
        cluster_name='ephemeral-spark-cluster-{{ ds_nodash }}',
        dataproc_pyspark_jars=
        'gs://spark-lib/bigquery/spark-bigquery-latest.jar',
)
```

I'm getting the following error when DataProcPySparkOperator.main="local file path".

```python
TypeError: upload() got an unexpected keyword argument 'bucket_name'
```

I think DataProcPySparkOperator._upload_file_temp() uses wrong argument names when trying to run GoogleCloudStorageHook.upload() method. GoogleCloudStorageHook.upload() expects `bucket` and `object` however DataProcPySparkOperator._upload_file_temp() tries to use the names `bucket_name` and `object_name`.

**What you expected to happen**:

I expected the DataProcPySparkOperator to upload my local python file to GCS.

**How to reproduce it**:

Use main="local file path" with DataProcPySparkOperator.

**Anything else we need to know**:

It happened every time I tried to run DataProcPySparkOperator with a main="local file path".

**Comment by alexandraabbas** [comment]
I'm happy to fix this issue. I thought I raise a bug first.

**Comment by mik-laj** [comment]
@alexandraabbas  I assigned you to this ticket. When you finish your work, write to me or @turbaaszek to review the change.

**Comment by alexandraabbas** [comment]
@mik-laj I see in the contributors' guide that all PR-s should target master. On master `airflow.contrib.operators.dataproc_operator.DataProcPySparkOperator` is derived from `airflow.providers.google.cloud.operators.dataproc.DataprocSubmitPySparkJobOperator` so the issue is solved on master. However the issue is still there on v1-10-stable. Can I raise a PR to target v1-10-test?

**Comment by alexandraabbas** [comment]
Backport packages are going to be released very soon which will solve this issue.
