### ISSUE TITLE
Cant add DAG run manually from WebUI

### ISSUE THREAD

**Issue by fuyi** [apache/airflow#9028]
**Apache Airflow version**:

1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

When trying to create a DAG run record from WebUI  Browse -> DAG Runs, it fails with the error message "Not a valid datetime value" for the field "Execution Date". See screenshot attached.

![bug_dag_run](https://user-images.githubusercontent.com/295515/82943817-7aaa9100-9f9a-11ea-973a-a667d8b2f11f.png)

**What you expected to happen**:

A DAG run record is created successfully.

**How to reproduce it**:

See the screenshot above.

**Comment by ofaakye** [comment]
Any updates on this issue. I am having the same issue?

**Comment by fuyi** [comment]
@ofaakye I just verified that this issue happens only on v1.10.10, not on the master branch. I am working on a patch to fix this.

**Comment by fuyi** [comment]
@ofaakye This issue is fixed on v1.10.11. You can just update to that version.
