### ISSUE TITLE
entrypoint cannot enter bash shell

### ISSUE THREAD

**Issue by 22quinn** [apache/airflow#9033]
**Apache Airflow version**: 1.10.10 / master

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
Production Docker image

**What happened**:

`docker run --rm -it apache/airflow:1.10.10 bash`

Output:

airflow command error: argument subcommand: invalid choice: 'bash' (choose from 'backfill', 'list_dag_runs', 'list_tasks', 'clear', 'pause', 'unpause', 'trigger_dag', 'delete_dag', 'show_dag', 'pool', 'variables', 'kerberos', 'render', 'run', 'initdb', 'list_dags', 'dag_state', 'task_failed_deps', 'task_state', 'serve_logs', 'test', 'webserver', 'resetdb', 'upgradedb', 'checkdb', 'shell', 'scheduler', 'worker', 'flower', 'version', 'connections', 'create_user', 'delete_user', 'list_users', 'sync_perm', 'next_execution', 'rotate_fernet_key'), see help above.

**What you expected to happen**:

Enter bash shell
`airflow@0477774b3772:/opt/airflow$`

**How to reproduce it**:
`docker run --rm -it apache/airflow:1.10.10 bash`

**Anything else we need to know**:

**Comment by zikun** [comment]
Before I make a PR to fix it, can someone confirm this is the expected behaviour?

**Comment by potiuk** [comment]
For 1.10.10 it was like that but it's been fixed in master and will be cherry-picked for 1.10.11
