### ISSUE TITLE
Correctly describe the dst parameter in LocalFilesystemToGCS operator

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#9040]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The description of the `dst` parameter of the LocalFilesystemToGCSOperator is not correct. 
https://github.com/apache/airflow/blob/738667082d32d3ef93ec2cd6c3735ff3691ba1cc/airflow/providers/google/cloud/operators/local_to_gcs.py#L35-L36

**What you expected to happen**:

I expected it to be described as the object name. The `dst` parameter was simply passed to the `object_name` parameter of the `upload` method of the `GCSHook`. This means that the `dst` parameter is the object name to use to store the uploaded object and not a path as described. 
https://github.com/apache/airflow/blob/738667082d32d3ef93ec2cd6c3735ff3691ba1cc/airflow/providers/google/cloud/operators/local_to_gcs.py#L90-L96
Here is the description of the `object_name` parameter in the upload method of `GCSHook`:  `The object name to set when uploading the file.`
https://github.com/apache/airflow/blob/738667082d32d3ef93ec2cd6c3735ff3691ba1cc/airflow/providers/google/cloud/hooks/gcs.py#L300-L323

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
It's a bit ambiguous indeed and it would be great to make it consistent. Objects in GCS are often referred to as files - even if they are really objects - but in all kinds of UI  interfaces the objects with "/" are interpreted as folders/paths (but they are really not paths -  just object names). There is no real concept of "folder" in GCS.
