### ISSUE TITLE
[AIP-31] Update Airflow tutorial to use functional DAGs

### ISSUE THREAD

**Issue by casassg** [apache/airflow#9041]
**Description**

Change Airflow tutorial (or create new tutorial) using the new functional layer.

**Use case / motivation**

Help users onboard Airflow by reducing the complexity of the tutorial by adopting the new functional DAG definition layer.

**Related Issues**

Blocked by #8057

**Comment by kaxil** [comment]
@casassg @turbaszek Can one you create a Github issue for the "dag" decorator -- looks like that is the only other pieces missing for Airflow 2.0 with regards to Functional DAGs apart from other tickets mentioned in https://github.com/apache/airflow/labels/AIP-31

**Comment by mik-laj** [comment]
I think the guide should present a functional imperative and functional approach. These are two different approaches and have different use cases. This is not a 1 to 1 alternative.

**Comment by casassg** [comment]
This specific issue is about the main tutorial. I think that one benefits from having a unique style (I prefer functional as its easier). We should add a guide for both styles though

**Comment by ashb** [comment]
Vikram has volunteered to tackle this
