### ISSUE TITLE
ERROR - Can't compile non template nodes when I am using Papermill Operator

### ISSUE THREAD

**Issue by wgonzalez25** [apache/airflow#9048]
Hi:

I have an issue related to Papermil Operator when I am trying to DAG RUN in AWS (Ubuntu 18-04)

Attached, you can find the log file associated to this issue where appears the message: ERROR - Can't compile non template nodes

Additionally, I am sending my DAG File if you can find some issue too.

```python
import os
from datetime import timedelta
from datetime import datetime
from airflow.models import DAG
from airflow.operators.papermill_operator import PapermillOperator
from airflow.utils.dates import days_ago


default_args = {
    'owner': 'Walter',
    'start_date': days_ago(1),
}

with DAG(
    dag_id='COVID_TEST',
    default_args=default_args,
    schedule_interval='@daily',
    dagrun_timeout=timedelta(minutes=10)
) as dag:
    # [START howto_operator_papermill]
    run_this = PapermillOperator(
        task_id="COVID_example_notebook",
        input_nb="/home/ubuntu/COVID/COVID_TEST.ipynb",
        output_nb="/home/ubuntu/COVID/out-{{ execution_date }}.ipynb",
        parameters={"msgs": "Ran from Airflow at {{ execution_date }}!"}
    )
    # [END howto_operator_papermill]
```

[COVID_TEST_COVID_example_notebook_2020-05-27T00_00_00+00_00_8.log](https://github.com/apache/airflow/files/4694681/COVID_TEST_COVID_example_notebook_2020-05-27T00_00_00%2B00_00_8.log)

**Comment by eladkal** [comment]
Can you please check if the issue still appear using the Papermill provider & Airflow 2?
https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
