### ISSUE TITLE
Connection support for repeated extra fields

### ISSUE THREAD

**Issue by frnidito** [apache/airflow#9060]
**Description**

The `Connection` object should be able to support repeated keys in the extra fields.

**Use case / motivation**

Some connections strings, for instance the one used by MongoDB, support the repetition of keys such as in setting the rules for the precedence in choosing data-centres:

`mongodb://mongos1.example.com,mongos2.example.com/?readPreference=secondary&readPreferenceTags=dc:ny,rack:r1&readPreferenceTags=dc:ny&readPreferenceTags=`

At the moment, there is no way to set this in the Connection neither though the UI nor using the CLI.
```
>>> from airflow.models.connection import Connection
>>> c = Connection(uri='my-conn-type://my-login:my-password@my-host:5432/my-schema?param1=val1&param2=val2')
>>> c.extra
'{"param1": "val1", "param2": "val2"}'
>>> c.set_extra('{"param1": "val1", "param1": "val2"}')  # <- here
>>> c.get_uri()
'my-conn-type://my-login:my-password@my-host:5432/my-schema?param1=val2'
```

Adding support to this, maybe with an array form in the JSON would be ideal, i.e., being able to write something like:
```
>>> c.set_extra('{"param1": ["val1", "val2"]}')
>>> c.get_uri()
'my-conn-type://my-login:my-password@my-host:5432/my-schema?param1=val1&param1=val2'
```

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/blob/ffbbbfc1a7c2266a19293e0c06b80d46e394fe57/airflow/models/connection.py#L211
If we want arrays to be created via the URL, we need to improve the parsing of the query string. Currently, you can only define a string there.

**Comment by dstandish** [comment]
@frnidito we now can serialize full json to the conn URI (see https://github.com/apache/airflow/pull/15100)

is it ok to close this issue?
