### ISSUE TITLE
LDAPS forces ssl.CERT_REQUIRED preventing the use of self-signed certificates

### ISSUE THREAD

**Issue by NBardelot** [apache/airflow#9063]
In `contrib/auth/backends/ldap_auth.py` in the stable version of Airflow maintained under the branch `v1-10-stable`:

```
    tls_configuration = Tls(validate=ssl.CERT_REQUIRED,
                            ca_certs_file=cacert)
```

the behaviour of `validate` should be made configurable so that one can opt for `ssl.CERT_OPTIONAL` as per [the documentation of `ldap3`](https://ldap3.readthedocs.io/en/latest/ssltls.html).

I propose to add a new configuration under `ldap` named `cert_validation` with three valid string values corresponding to the same name as the SSL library:

  * **`CERT_NONE`**: use `ssl.CERT_NONE` (certificates are ignored)
  * **`CERT_OPTIONAL`**: use `ssl.CERT_OPTIONAL` (certificate not required, but validated if provided)
  * **`CERT_REQUIRED`** _by default to match the current behaviour_: use `ssl.CERT_REQUIRED` (certificate required and validated)

If the configuration is omitted it default to `CERT_REQUIRED`. If it is anything else than those three strings, the configuration should throw an error.

**Comment by potiuk** [comment]
Closing for the same reason as #9065
