### ISSUE TITLE
Build and publish API clients automatically

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#9080]
**Description**

The OpenAPI allows to generate automatically clients for various languages. There are however some unresolved problems with some of the constructs in the Open API - for example oneOf with single schema produces uncompilable code  despite being correct specification. Another example is "key" generic name of parameter, which in Java code might cause compilation problems in some cases as "key" variable name is used internally in generated methods.

We would like to make sure that our OpenAPI specification produces compilable and usable clients when auto-client generation is used.  This can be easily setup as a CI step.

**Use case / motivation**

We want our customers to have very easy path in using the API. Being able to use pre-generated client API in their favorite language can save many days of work for integration.

CI building the API clients + API clients published as artifacts are great way to achieve that consistently.

**Related Issues**
#7549

**Comment by mik-laj** [comment]
We have POCs: https://github.com/mik-laj/airflow-api-clients
If anyone wants, they can base on it or start from scratch.
An example of a successful client generation is Kubernetes: https://github.com/kubernetes-client
We can get inspired by their work.

**Comment by mik-laj** [comment]
@houqp  Can you reply here? I can't assign you to a ticket without it.

**Comment by houqp** [comment]
@mik-laj sure, i will take this ticket.

**Comment by mik-laj** [comment]
I have prepared a spreadsheet in which we can collect requirements about what the client must have in order to be released.
https://docs.google.com/spreadsheets/d/11VaVxdZyYcVHtPwL0JL_qKJ4YzIyvefGcoUleBofn28/edit#gid=0

**Comment by potiuk** [comment]
Love it. @houqp - happy to help with reviews and bouncing-off any problems you might have.

**Comment by mik-laj** [comment]
I add the "kind:meta" label because we won't be able to close it with one or two tickets.

**Comment by houqp** [comment]
@mik-laj are we still tracking the client progress with the spreadsheet you linked? I left couple comments there, but hasn't seen it updated. we can also create separate ticket for each language to track the status.

**Comment by mik-laj** [comment]
@houqp  Thanks for pinging me I updated the spreadsheet and added new requirements about authorization. These are optional in most cases. I would prefer to have one spreadsheet so that adding a new requirement is updated for all clients.

**Comment by mik-laj** [comment]
@houqp I have given you editor permission on this sheet, so you can make changes to it.

**Comment by mik-laj** [comment]
We should add info about client library to docs:
https://airflow.readthedocs.io/en/latest/stable-rest-api-ref.html

**Comment by zachliu** [comment]
as i mentioned in the slack/forum, i've been working on my own [airflow-python-sdk](https://pypi.org/project/airflow-python-sdk/).
i noticed the differences between the `/api/v1/openapi.json` embedded in the swagger UI and this [specs](https://raw.githubusercontent.com/PolideaInternal/airflow/75b0ad0fb606cc41f9af43cb6373aed25a8fc39c/openapi.yaml).
is there a reason for such differences? there are lots of "unimplemented" endpoints in the [specs](https://raw.githubusercontent.com/PolideaInternal/airflow/75b0ad0fb606cc41f9af43cb6373aed25a8fc39c/openapi.yaml) and i've been adding them one by one

**Comment by mik-laj** [comment]
Here is the latest version of the specification.
**Development version (master)**
https://github.com/apache/airflow/blob/master/airflow/api_connexion/openapi/v1.yaml
**2.0.0 (latest released)**
https://github.com/apache/airflow/blob/2.0.0/airflow/api_connexion/openapi/v1.yaml

**Comment by zachliu** [comment]
i've been using the wrong spec :facepalm:

**Comment by mik-laj** [comment]
The specification for each version is also available in the documentation.
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html
![Screenshot 2021-02-03 at 00 50 21](https://user-images.githubusercontent.com/12058428/106677855-cf86b880-65b9-11eb-8017-b46d94d06b58.png)

**Comment by zachliu** [comment]
@mik-laj thanks, in a few days i shall release my `v1.0.0` sdk :muscle:

**Comment by potiuk** [comment]
We alredy have clients published (some). Whic is good enough.
