### ISSUE TITLE
Marking the dag task to success/failed in web UI, task's end date is None.

### ISSUE THREAD

**Issue by santhoshhpe** [apache/airflow#9090]
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
docker
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- **Kernel** (e.g. `uname -a`):
Linux 15d4b3070038 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 GNU/Linux
- **Install tools**:
BCRYPT, BOTO3, 
- **Others**:
<img width="375" alt="Capture" src="https://user-images.githubusercontent.com/62881503/83400877-4531f780-a421-11ea-8c00-37e85e80770e.PNG">

**What happened**:
The end date attribute of the task is None

**What you expected to happen**:
The end date attribute must capture the date and time of marking the task as success or failed.

Not sure
**How to reproduce it**:

**Anything else we need to know**:

**Comment by dimberman** [comment]
Hi @santhoshhpe is this issue in 2.0 as well?

**Comment by santhoshhpe** [comment]
Hi @dimberman, I haven't got a chance to check in Airflow version 2.0, this was initially observed in airflow verison 1.10.10.

**Comment by dimberman** [comment]
@santhoshhpe are you sure we should even have an end date here? The task technically never ended... cc: @kaxil

**Comment by santhoshhpe** [comment]
I guess this use to happen if the task state is set externally to success or failure.

**Comment by jedcunningham** [comment]
This is no longer an issue in 2.0. Start and end date are both populated both on task instance details and in "Browse -> Task Instances". This can be closed.

**Comment by santhoshhpe** [comment]
Thanks all for looking into this.
