### ISSUE TITLE
Enable configuration for GIT_SYNC_DEPTH in Kubernetes Executor

### ISSUE THREAD

**Issue by mgorsk1** [apache/airflow#9093]
**Apache Airflow version**:
1.10.7

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Git sync init container in worker failed to pull the code:

I0601 12:04:55.354457       1 main.go:269]  "level"=0 "msg"="starting up"  "args"=["git-sync"]
I0601 12:04:55.886749       1 main.go:495]  "level"=0 "msg"="cloned repo"  "origin"="https://gitlab.wbaa.pl.ing.net/data-assets/ingestion-dags.git"
E0601 12:04:55.888925       1 main.go:294]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 128: \"fatal: ambiguous argument '0.1.7': unknown revision or path not in the working tree.\\nUse '--' to separate paths from revisions, like this:\\n'git \u003ccommand\u003e [\u003crevision\u003e...] -- [\u003cfile\u003e...]'\\n0.1.7\\n\"" 

**What you expected to happen**:

The latest tag on synced repo was 0.1.8 but we wanted to checkout 0.1.7 in our deployment. I expected git sync to pull 0.1.7 tag. When configuring GIT_SYNC_REV to 0.1.8 workers doesn't fail.

According to git-sync documentation (https://github.com/kubernetes/git-sync) the issue might be with hardcoded GIT_SYNC_DEPTH variable in worker definition (set to 1 instead of 0)

**How to reproduce it**:

Configure git sync with GIT_SYNC_REV variable and try to checkout older than latest tag.

**Anything else we need to know**:

We have used pod_mutation_hook to override this hardcoded value and it resolved the issue but I believe it should be a configuration option.

**Comment by eladkal** [comment]
fixed by https://github.com/apache/airflow/pull/9094
