### ISSUE TITLE
moving sql operators into sql.py

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#9099]
with the addition of BranchSqlOperator https://github.com/apache/airflow/pull/8942 and as pointed during the review I'd like to suggest the following :
```
airflow/operators/sql_branch_operator.py
airflow/operators/check_operator.py
```
will be merged to `airflow/operators/sql.py `
The operators will be renamed as:
CheckOperator                   ->~~SqlCheckOperator~~ SQLCheckOperator
ValueCheckOperator         ->~~SqlValueCheckOperator~~ SQLValueCheckOperator
IntervalCheckOperator      -> ~~SqlIntervalCheckOperator~~ SQLIntervalCheckOperator
ThresholdCheckOperator ->~~SqlThresholdCheckOperator~~ SQLThresholdCheckOperator
BranchSqlOperator             -> the same.
The motivation is that Airflow currently have two separated files in core related to generic SQL.
My suggestion is similar to how PythonOperator(s) are organized in `python.py` (PythonOperator, BranchPythonOperator, ...)

@samuelkhtu you mentioned on slack that you want to take it.
If not I'll add PR for it

**Comment by mik-laj** [comment]
We should use uppercase for acronyms 

> Note: When using acronyms in CapWords, capitalize all the letters of the acronym. Thus HTTPServerError is better than HttpServerError.

https://www.python.org/dev/peps/pep-0008/

**Comment by eladkal** [comment]
@mik-laj NP. edited

**Comment by samuelkhtu** [comment]
@eladkal Thanks. Can you assign this to me? I can work on this.

**Comment by mik-laj** [comment]
Please start working. I'll do it when I'm on the PC.

**Comment by samuelkhtu** [comment]
Should we change the class name from BranchSqlOperator to SQLBranchOperator or use the Python organization? (BranchSQLOperator?)

**Comment by eladkal** [comment]
> Should we change the class name from BranchSqlOperator to SQLBranchOperator or use the Python organization? (BranchSQLOperator?)

It won't be consistent with how it's done  in `python.py `:
**Branch**PythonOperator
PythonOperator
PythonVirtualenvOperator

In my opinion the goal here is to make the SQL be consistent with Airflow current convention.
After this step is done you can raise the question of `BranchXOperator` or `XBranchOperator` to discussion as this effect operators from different modules so it's not just SQL local module issue.

**Comment by samuelkhtu** [comment]
Thanks. Sounds good. The PR is done. I will send it out for review later this afternoon.

**Comment by samuelkhtu** [comment]
Hi @eladkal @mik-laj , the PR is ready for review. Thanks.
[https://github.com/apache/airflow/pull/9124](url)
