### ISSUE TITLE
Rename all Transfer operators in Providers to XTYOperator convention

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#9101]
**Description**

**Use case / motivation**

We agreed during [the voting](https://lists.apache.org/thread.html/r341898c92de08c8365cd730bb4a3c37ef0c9a0ecea3f18a273cb6ee6%40%3Cdev.airflow.apache.org%3E) that all the transfer operators should be named XToYOperator
We should rename all the operators to follow the convention and enforce it in the checks.

**Comment by JeffryMAC** [comment]
what is XToYHook ?

**Comment by potiuk** [comment]
See the link in the description. @JeffryMAC

**Comment by turbaszek** [comment]
@potiuk do we have any XToY**Hook**?

**Comment by JeffryMAC** [comment]
hooks are on specific service (single) so how can how does something on X and Y?
Unless it's XtoX but even then it's called operator not hook

**Comment by potiuk** [comment]
It's only about Transfer operators

**Comment by potiuk** [comment]
yes we have at least a few

**Comment by potiuk** [comment]
I thought we had some but not really. Clarified.

**Comment by turbaszek** [comment]
I think it's already done @potiuk ?

**Comment by potiuk** [comment]
Indeed!
