### ISSUE TITLE
Add ability to filter DAG list by clicking on dag owner

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#9102]
**Description**

Similar to https://github.com/apache/airflow/issues/8821

**Use case / motivation**

DAG list is organised by dag id so if someone want to see his dags he must search for it in the bar. it can good if by clicking on owner in owner column it will show only this person dags

@Sangarshanan what do you think?

**Comment by Sangarshanan** [comment]
Nice! I have gotten rather used to just doing ctrl+F :stuck_out_tongue:  can pick this up too

**Comment by JeffryMAC** [comment]
@Sangarshanan  yeah but ctrl + f doesn't help when you have many dags so they are on different pages.

**Comment by JeffryMAC** [comment]
@Sangarshanan do you work on this?

**Comment by Sangarshanan** [comment]
oh no I completely lost track of this issue, already have the code will find it and try to raise a PR soon

**Comment by eladkal** [comment]
@Sangarshanan I assigned the issue to you
