### ISSUE TITLE
API Endpoint - CRUD - Connection

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9108]
Hello 

We need to create several endpoints that perform basic CRUD operations on **Connection** . We need the following endpoints:

- POST /connections
- DELETE /connections/{connection_id}
- PATCH /connections/{connection_id}

IT depends on https://github.com/apache/airflow/issues/8127

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by ephraimbuddy** [comment]
Hi @mik-laj , Can I start working on this?

**Comment by mik-laj** [comment]
@ephraimbuddy. Fantastic. I'm assigned you to this ticket.
