### ISSUE TITLE
API Endpoint - CRUD - DAG

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9109]
Hello 

We need to create several endpoints that perform basic CRUD operations on **DAG**. We need the following endpoints:

- PATCH /dags/{dag_id}

It depends on https://github.com/apache/airflow/issues/8128

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by mik-laj** [comment]
@bertosantamaria Can you reply to this?  This allows me to assign you to this ticket.

**Comment by bertosantamaria** [comment]
Yes hi and thank you.

**Comment by takunnithan** [comment]
@mik-laj  Hi, Is this assigned to @bertosantamaria ? If not, I would like to work on this

**Comment by mik-laj** [comment]
This ticket is blocked because it depends on read-only endpoints. - https://github.com/apache/airflow/issues/8128  These two tickets have a common scheme.
You can check available tickets in the Github project in the TODO column.
https://github.com/apache/airflow/projects/1

**Comment by takunnithan** [comment]
@mik-laj Thanks!

**Comment by OmairK** [comment]
@mik-laj can you assign me this task please?

**Comment by mik-laj** [comment]
@OmairK I assigned you to this ticket.
