### ISSUE TITLE
API Endpoint - CRUD - Dag Runs

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9110]
Hello 

We need to create several endpoints that perform basic CRUD operations on **DAG Run**. We need the following endpoints:

DELETE /dags/{dag_id}/dagRuns/{dag_run_id}
PATCH /dags/{dag_id}/dagRuns/{dag_run_id}
POST /dags/{dag_id}/dagRuns/{dag_run_id}

It depends on https://github.com/apache/airflow/issues/8129

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by ephraimbuddy** [comment]
Hi @mik-laj , I will like to work on this

**Comment by mik-laj** [comment]
@ephraimbuddy Hi. I assigned you to another task. When you finish, I'll assign you to the next tasks.

**Comment by OmairK** [comment]
Hi @mik-laj can I work on this issue ?

**Comment by mik-laj** [comment]
@OmairK I assigned you to this ticket. 🐈
