### ISSUE TITLE
API Endpoint - CRUD - XCOM

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9111]
Hello 

We need to create several endpoints that perform basic CRUD operations on **XCOM Entries*. We need the following endpoints:

POST /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries
DELETE /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}
PATCH /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}

It depends on https://github.com/apache/airflow/issues/8134

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by ephraimbuddy** [comment]
Hi, @mik-laj , I know the log_endpoint is not merged yet but should I start working on this?

**Comment by mik-laj** [comment]
Yes. You can work on other tickets if you are blocked.
