### ISSUE TITLE
API Endpoint - Batch

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9112]
Hello 

We need to create several endpoints that perform batch operations on **XCOM Entries*. We need the following endpoints:

- ``POST /dags/~/dagRuns/list``
- ``POST /dags/~/dagRuns/~/taskInstances/list``

It depends on https://github.com/apache/airflow/issues/8132, https://github.com/apache/airflow/issues/8129

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by takunnithan** [comment]
@mik-laj I would like to work on this. Can I take this as my first issue ?

**Comment by mik-laj** [comment]
``POST /dags/~/dagRuns/~/taskInstances/list`` is still blocked, but you can start working on ``POST /dags/~/dagRuns/list``. I assigned you to this ticket.

**Comment by takunnithan** [comment]
@mik-laj Thanks!
