### ISSUE TITLE
API Endpoint - CRUD - Pool

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9114]
Hello 

We need to create several endpoints that perform basic CRUD operations on **Pools**. We need the following endpoints:

POST /pools
DELETE /pools/{pool_name}
PATCH /pools/{pool_name}

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by OmairK** [comment]
Hi @mik-laj can you assign me this issue please.

**Comment by mik-laj** [comment]
Hi @OmairK I assigned you to this task.
