### ISSUE TITLE
API Endpoint - CRUD - Variable

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9115]
Hello 

We need to create several endpoints that perform basic CRUD operations on **Variable**. We need the following endpoints:

POST /variables
DELETE /variables/{variable_key}
PATCH /variables/{variable_key}

Detailed information is available in the issue:
https://github.com/apache/airflow/issues/8118

LOVE,

**Comment by mik-laj** [comment]
@houqp Can you write a comment here? This will allow me to assign you to this ticket.

**Comment by houqp** [comment]
I will take this one as well :)
