### ISSUE TITLE
Apache beam issue extracting job from monitoring page

### ISSUE THREAD

**Issue by pegerto** [apache/airflow#9117]
**Apache Airflow version**: 1.10.10 and 1.10.9 has been verified

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
no Kube

**Environment**:

- **Others**: docker environment with java 1.8

**What happened**:

The existing function to extract a job id from the monitoring page is no longer compatible with new beam 2.20:

https://github.com/apache/airflow/blob/96697180d79bfc90f6964a8e99f9dd441789177c/airflow/contrib/hooks/gcp_dataflow_hook.py#L142-L148

The monitoring page includes the zone as part of the URL causing the regex to extract always the `zone` instead of the `job_id`

A new regex compatible with the new and old monitoring url needs to be added to the operator:

https://github.com/apache/beam/blob/v2.20.0/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/MonitoringUtil.java#L192-L195

As per the been new configuration region is extracted instead of the job id

**Comment by mik-laj** [comment]
Duplicated: https://github.com/apache/airflow/issues?q=is%3Aissue+is%3Aopen+Dataflow
