### ISSUE TITLE
Support Flink operator

### ISSUE THREAD

**Issue by SteNicholas** [apache/airflow#9134]
**Description**

Airflow currently supports Spark operators for kicking off a spark-submit job.  In real-time computing or online machine learning scenarios, Flink operator could be designed to submit flink job in streaming workflow.

**Use case / motivation**

Airflow coud supports definition of `FlinkSubmitOperator` for DAG composed of multiple Flink jobs. `FlinkSubmitOperator` is designed to introduce the operator that kicks off a flink-submit task, and provides corresponding to JDBC and SQL operators.

**Related Issues**

N/A

**Comment by zhongjiajie** [comment]
Sound good! looking forward your contribute. BTW, Airflow open to all new and useful operators.

**Comment by subkanthi** [comment]
If this is not being worked on, I can take it on, please let me know. @zhongjiajie

**Comment by mik-laj** [comment]
@subkanthi I assigned you to this ticket. 🐈

**Comment by SteNicholas** [comment]
@subkanthi I thought that you currently couldn't complete this issue. Because the streaming semantic couldn't support, how do you work on this issue?

**Comment by mik-laj** [comment]
@SteNicholas I think we can add two operators. One that starts streaming operations on a remote cluster, return ID to XCOM and the other that stops these operations. However, I have no experience with Flink. Do you think this is possible?

**Comment by zhongjiajie** [comment]
I think it depend on what we could add streaming to airflow, if it will task many times, maybe support parts of flink function on flink operator is acceptable.

**Comment by subkanthi** [comment]
I thought this was very similar to the SparkSubmit operator where it expects spark-submit to be in the path and takes the jar file as a parameter.

**Comment by zhongjiajie** [comment]
> was

But that parts of flink function, nor full of it. maybe you could see https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-35+Add+Signal+Based+Scheduling+To+Airflow for more detail.

**Comment by subkanthi** [comment]
@mik-laj , @zhongjiajie is it OK if i just work on the simple flinksubmit operator first, maybe we can have another issue for the streaming part?

**Comment by SteNicholas** [comment]
@subkanthi How does the operator teminate? The flink submit for streaming application doesn't teminate.

**Comment by subkanthi** [comment]
Is it not the same as spark-submit kill command, we use the flink cancel command.
./bin/flink cancel <jobID>
Are we all referring to starting and cancelling jobs using the CLI?
https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/cli.html

**Comment by SteNicholas** [comment]
Do you mean that the implemenation of FlinkOperator is based on `flink run` command? But If you want to kill Flink Job, you must persist with the job id. Therefore, how do you control with this presistence?

**Comment by sreenath-kamath** [comment]
Why not use the flink REST API's to submit the job and store the job_id in the xcom variable and exit the process, https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html. Incase the user wants to poll for the status of the job in the dag a `Sensor` can also be written which takes the job id as an argument and ensures that the job is still running. wdyt ?

**Comment by SteNicholas** [comment]
@sreenath-kamath Submitting Flink job always uses Flink command, and using the flink REST API's to submit the job isn't friendly to Airflow's users.

**Comment by mdianjun** [comment]
@subkanthi Hello，is there any progress on this issue?

**Comment by ChethanUK** [comment]
Working on this, will send PR soon

**Comment by punit-zeta** [comment]
Hi, @ChethanUK any update on this issue?

**Comment by LuigiCerone** [comment]
Hello, any update on this?

**Comment by xinbinhuang** [comment]
fixed in #28512
