### ISSUE TITLE
depends_on_past issue on 1.6.1

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#914]
![2016-01-26_091826](https://cloud.githubusercontent.com/assets/179343/12569871/d5ca419c-c40d-11e5-85b2-2a5054fb17ec.png)

The task will be stuck when the next of the past have been skipped. I understand the mean of depends_on_past and wait_for_downstream. But the skipped should be the logically be expected. The future task should be run instead of stop.

**Comment by griffinqiu** [comment]
Sorry, I found it is bcs the wait_for_downstream be set to True

**Comment by mistercrunch** [comment]
You probably shouldn't use depends_on_past no a branching scheme. Should a skipped be considered ok or generate another skipped status? People may want either behavior.

**Comment by nonlyli** [comment]
@mistercrunch
I think "skip" or "sucess" status means able to start another task in the new Dag.
Other status "running", "failed", "up_to_retry" means need wait the same task in prev Dag.

**Comment by mistercrunch** [comment]
But why depends_on_past of something that can be skipped? Wontfix. Will review your PR though if you guys think this is important.

**Comment by griffinqiu** [comment]
@mistercrunch I think this is useful. 

You could image a scenario. I need deal some data timely (Such as 30 minutes). I can get the results of the latest after DAG run one round. So I need control this DAG as singleton(add depends_on_past). For some fault the DAG may behind schedule. I just need run once after the fault is fixed in fact. I may add some logic to skip the behind schedule tasks of the DAG. So the skip is my logic for schedule as @nonlyli mentioned "I think "skip" or "sucess" status means able to start another task in the new Dag."

#1033

**Comment by griffinqiu** [comment]
![20160226173639](https://cloud.githubusercontent.com/assets/179343/13348637/8dbf4914-dcaf-11e5-8266-bf468cda6563.jpg)

**Comment by griffinqiu** [comment]
Right now, I just can set the max_active_runs to 1 for solve this scenario. T_T

**Comment by griffinqiu** [comment]
#1155

**Comment by r39132** [comment]
@griffinqiu We will support this behavior. I just fixed an issue related to depends_on_past=True and Skipped states, but I'm not sure it will fix wait_for_downstream. Can you pull master after https://github.com/airbnb/airflow/pull/1169 is merged and ping me on gitter with whether this is fixed or needs an extra change?

**Comment by r39132** [comment]
This is now fixed in the PR above and tracked in the issue : https://github.com/airbnb/airflow/issues/1155
