### ISSUE TITLE
Enhance `SqlToSlackOperator` to support attachments

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#9145]
**Use case / motivation**
following to https://github.com/apache/airflow/pull/9023
Current implementation of SnowflakeToSlackOperator adds the data frame result to the slack message. That way it's not suitable for large data. Even 50 rows is too much. In some cases it's better to send the message with attachment as csv file.

**Comment by kishvanchee** [comment]
Is this taken? Can I work on this?

I feel the `SlackAPIFileOperator` https://github.com/apache/airflow/blob/fe59f2622337616fe1902bb6d7e1bce6f002ffa8/airflow/providers/slack/operators/slack.py#L159 might be used here?

**Comment by JeffryMAC** [comment]
@kishvanchee it's not taken you can work on this.
storing in tmp is what many transfer operators do
examples:
https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/transfers/gcs_to_sftp.py#L164
https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/transfers/sql_to_gcs.py#L184

**Comment by kishvanchee** [comment]
Should I be using `SlackHook` only for file uploads while at the moment the operator is using `SlackWebhookHook` ?

Docstring for SlackWebhookHook says
> :param attachments: The attachments to send on Slack. Should be a list of
        dictionaries representing Slack attachments.
    :type attachments: list

This is confusing to me since I can attach list of dictionaries, but not file objects.

While for SlackHook I can find a suitable call method which actually does the file upload.
https://github.com/apache/airflow/blob/d404cb06dd52d391a9ef26ef700b61f04a771cd5/airflow/providers/slack/hooks/slack.py#L85 

[This stackoverflow answer](https://stackoverflow.com/a/36287627/5675288) says that I can't use a webhook, but must use an api for file upload. The WebClient is what is actually being used in the `SlackAPIFileOperator` too. https://github.com/apache/airflow/blob/fe59f2622337616fe1902bb6d7e1bce6f002ffa8/airflow/providers/slack/operators/slack.py#L159

**Comment by JeffryMAC** [comment]
worth asking @simond as the author of the original PR and @feluelle @turbaszek who approved it.

**Comment by simond** [comment]
Oof, I can't really remember the reason I used the `SlackWebHook` over `SlackHook` unfortunately. I think it was because it is simpler to use for basic messages. Now that you want to add an attachment too then yea, you may have to move to the SlackHook instead unfortunately!

**Comment by kishvanchee** [comment]
Ah okie. Does it make more sense to use `SlackHook` now just for the attachment part? Or should I try refactoring the current implementation with `SlackHook` itself? Not sure about design choices/patterns here.

I would appreciate any help @turbaszek @feluelle

**Comment by turbaszek** [comment]
> Does it make more sense to use `SlackHook` now just for the attachment part? Or should I try refactoring the current implementation with `SlackHook` itself?

I think it would be best to reuse what we already have 👍

**Comment by fatmumuhomer** [comment]
@turbaszek I can work on this one for the workshop.

**Comment by feluelle** [comment]
I thought @kishvanchee liked to work on that one?

I think using SlackHook for the file upload makes sense and the use the SlackWebHook for the rest.

**Comment by kishvanchee** [comment]
@feluelle I am, I didn't get this assigned to me though. Although now I am confused whether I should be working on this...

**Comment by fatmumuhomer** [comment]
@kishvanchee feel free to take it and work on it if you would like. I was using this as a practice issue in the contributor workshop that @turbaszek was teaching. I'm happy to grab a different issue.

**Comment by feluelle** [comment]
Thanks @fatmumuhomer :)

**Comment by JeffryMAC** [comment]
@kishvanchee did you had time to work on it?

**Comment by eladkal** [comment]
@kishvanchee  due to passed time I'm unassigning you.
This issue is available for anyone who wants to pick it

**Comment by kevgeo** [comment]
Hi @Taragolis, are you still working on adding an enhancement. Could I take up this issue?

**Comment by Taragolis** [comment]
Hi @kevgeo I have a hectic weeks, so feel free to take this issue, you could grab some [my previous changes](https://github.com/apache/airflow/pull/24660/files) if you find some useful parts.

I have a plan to make changes in Slack hooks first however I really do not know when I have a time for that.

**Comment by kevgeo** [comment]
Thanks @Taragolis, I will look into your previous PR too.
