### ISSUE TITLE
Retries are causing constraint violation (Airflow 1.10.10)

### ISSUE THREAD

**Issue by dimon222** [apache/airflow#9148]
**Apache Airflow version**:
1.10.10

**Database version**:
MariaDB 10.2.22

**What happened**:
When task fails, next task retry raises this exception immediately:
```
INSERT INTO rendered_task_instance_fields (dag_id, task_id, execution_date, rendered_fields) VALUES (%s, %s, %s, %s)
('test_dag', 'test_task', datetime.datetime(2020, 6, 4, 22, 20, 21, 139775), '')
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'test_dag-test_task-2020-' for key 'PRIMARY')
```
For some reason the value for execution date is calculated exactly same as previous retry. I might assume its not supposed to happen.

**What you expected to happen**:
Task retries correctly.

**How to reproduce it**:
Crash task that has retries > 0, wait for retry.
Alternatively, crash task, then clear this task's state in dag view to cause manual retry.

**Anything else we need to know**:
It happens always on retry. Not happening on 1.10.9 (very recent regression)
I'm able to retry correctly by removing related task records in MariaDB in rendered_task_instance_fields table.

**Comment by potiuk** [comment]
@kaxil @ashb @anitakar -> this one seems to be serialization related and seems to be fairly important to fix for 1.10.11

**Comment by ashb** [comment]
@dimon222 Disabling `store_serialized_dags` in your config should also work around this problem.

**Comment by kaxil** [comment]
Yes, will fix it for 1.10.11

**Comment by kaxil** [comment]
@dimon222 Can you try setting `max_num_rendered_ti_fields_per_task` to 1 and see it that helps for now ?

**Comment by chrismclennon** [comment]
I'm experiencing the same issue. @kaxil I set `max_num_rendered_ti_fields_per_task=1` and am still seeing the issue.

**Comment by kaxil** [comment]
I will fix this for 1.10.11 soon and will try to post a workaround too in 1-2 days

**Comment by kaxil** [comment]
Looks like this issues only occurs when using MySQL backend

**Comment by kaxil** [comment]
Current workarounds for MySQL Users:

1) Disable DAG Serialization
2) Run the following query on your Metadata DB:
	```sql
	alter table rendered_task_instance_fields modify execution_date timestamp(6) not null;
	```
