### ISSUE TITLE
Add migration to increase length of ab_view_menu.name column

### ISSUE THREAD

**Issue by ashb** [apache/airflow#9155]
See https://github.com/dpgaspar/Flask-AppBuilder/pull/1368

Daniel @ FAB has recommended we add a migration in Airflow to handle this subtle schema change in FAB.

We can do that, but we don't currently have a migration that creates/ensures the FAB tables exist (we have been relying on FAB creating them for us) -- so perhaps we should "import" the current definition of all of FABS tables with an set of `CREATE TABLE IF NOT EXIST` statements.

**Comment by lordozb** [comment]
@ashb FAB has fixed and merged it in their master. 
https://github.com/dpgaspar/Flask-AppBuilder/commit/6e77920a4dab5c62e8c37df8c343f136e75eff50

**Comment by kaxil** [comment]
@ashb Do we still want to address this in 1.10.13?

**Comment by ashb** [comment]
Yeah, let's
