### ISSUE TITLE
Why 302 redirect to /admin? 

### ISSUE THREAD

**Issue by marcelmfs** [apache/airflow#916]
Hi, can I ask why airflow redirects from `/` to `/admin` if EVERY navigation is anchored at `/admin/something`?

I am asking this because I'm in the process of integrating airflow into our current stack and it's annoying for proxying purposes to have that, not to mention the `/admin/admin/admin/css/bootstrap/admin.css` request that is made from the `/admin/index.html`. 

Is it possible to remove the first redirect to `/admin` and leave airflow responding solely on `/`?

Thank you!

Edit: probably related to https://github.com/airbnb/airflow/issues/726

**Comment by r39132** [comment]
I agree that it doesn't make sense why all functionality is on admin, except that it probably evolved that way. In terms of proxying, we put an apache reverse proxy in front and a single rewrite rule. We need to specify `https://myapacheserver/admin` in order to get to the airflow server, but there isn't any issue with the other paths.

**Comment by mistercrunch** [comment]
Well Airflow is built on top of flask-admin and leverages its templates and views. I'm unclear on where the /admin/admin/admin stuff is coming from, but it shouldn't occur. 

It may be sound to port the UI to `Flask App Builder` or even Django (much more of an undertaking) to get authentication and granular permissions / role management. I can't justify spending the time at this point though. 

If anyone can spare an intern, that's a pretty scoped out project with little need for guidance.

**Comment by r39132** [comment]
Hmn.

@djeps
I am seeing something interesting on recent versions of Airflow which happens to be related to missing js. I first thought it was related to proxying, but when I went behind the proxy, I noticed the same problem at the server itself. I have an open issue for it at #881 

I wonder if you are seeing this issue as well.

**Comment by marcelmfs** [comment]
The only missing `js` I'm seeing is `//admin/admin/admin/js/form-1.0.0.js` on "task duration, landing times and gantt" views. The problem with having another proxy just to have airflow properly proxied under it's own URI is that with our dockerized environment it makes little sense to have yet another container, but to fix the redirect to have airflow on it's own base url endpoint.

**Comment by mistercrunch** [comment]
I think you're having issues with colliding versions of `flask-admin`. You can try `pip uninstall flask-admin`, and/or `sudo pip uninstall flask-admin` before reinstalling the pinned version from setup.py (`pip install flask-admin==1.4.0`)

If you use a virtualenv you can start from a fresh, clean one.

**Comment by marcelmfs** [comment]
@mistercrunch I don't think that's the issue as in my case, the airflow docker container is always built from a clean minimal centos7 image following all pinned versions from `requirements.txt` file.

**Comment by mistercrunch** [comment]
actually the `requirements.txt` doesn't have much things pinned, I should really remove it from there.

The proper way to install is using the bracket notation as in `pip install airflow[hive]` and specify the subpackages you need.
