### ISSUE TITLE
Moving of the transfer operators to new packages

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9161]
Following the discussion
https://lists.apache.org/thread.html/rbf69247f8d4702a1b3770ab4891d90daed1ef12f385f2040f3ebe92d%40%3Cdev.airflow.apache.org%3E
and voting
https://lists.apache.org/thread.html/r3514ef575b437b9eb368111b1e4b03ad7455e63d64c359c22fd6ea9a%40%3Cdev.airflow.apache.org%3E

We move transfer operators to the new package - airflow.providers.*.transfer. 

As a result, we will have the following provider packages structure.

`airflow.providers.*.example_dags`
`airflow.providers.*.hooks`
`airflow.providers.*.operators`
`airflow.providers.*.secrets`
`airflow.providers.*.sensors`
`airflow.providers.*.transfer`
`airflow.providers.*.utils`

**Comment by 2796gaurav** [comment]
Great @mik-laj Looks like you will need a helping hand for this. Maybe I can help. I have contributed to couple of OSS but not airflow. although I have worked on it. Can you provide a simple task that I can work on in this?

**Comment by mik-laj** [comment]
@2796gaurav Thank you very much for your willingness to help, but my team would like to complete the change themselves, because it is needed to release backport packages. We want to release these packages as soon as possible because many users would like to start using them. We have already moved many operators in the past, so we have the tool and experience that speeds up this task.

What do you think about this ticket?  
https://github.com/apache/airflow/issues/8171
There is open PR here, but the user has not been active for a long time. If you write a comment under the ticket, I can assign you to this ticket.

**Comment by 2796gaurav** [comment]
Yes sure would love to do that!
