### ISSUE TITLE
DAG run fails when task instance is still running

### ISSUE THREAD

**Issue by fuyi** [apache/airflow#9166]
**Apache Airflow version**:

1.10.10

**What happened**:

DAG run fails when task instance is still running. see screenshot below

![Screenshot 2020-06-01 at 21 50 43](https://user-images.githubusercontent.com/295515/83963257-d7fce700-a8a4-11ea-940f-c87465bf7bd5.png)

**What you expected to happen**:

DAG run is in status running, not failed while a tasks instance is still running

**How to reproduce it**:

**Anything else we need to know**:

**Comment by tooptoop4** [comment]
https://github.com/apache/airflow/pull/8082 might help

**Comment by zorseti** [comment]
May be you have set dagrun_timeout in your dag?

**Comment by fuyi** [comment]
Thanks @zorseti, Yes, we have set dagrun_timout. However, would it make more sense to terminate running task when dag run fails? 🤔

**Comment by zorseti** [comment]
> Thanks @zorseti, Yes, we have set dagrun_timout. However, would it make more sense to terminate running task when dag run fails? 🤔
Maybe, but we don’t use the dagrun_timout parameter when we actually use it. We generally set the execution_timeout parameter for each task, which can make both task and dagrun mark failure during timeout.

**Comment by fuyi** [comment]
Hello @zorseti , Are you suggesting me to set `execution_timeout` for each individual task to control when to fail the DAG? This works.

However, I have a use case: 

`I don't care how much time each task runs, but I need to fail the DAG run and underneath task instances after X hours`

which I think `dagrun_timeout` is more appropriate here.

**Comment by fuyi** [comment]
Since DAG run failed due to `dagrun_timeout` reached. this is not a bug. close for now
