### ISSUE TITLE
Include plugin information in the version page

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#9185]
**Description**

Please include plug-in information (see below) in the Airflow "About -> Version" information page in the web interface.

**Use case / motivation**

Plug-ins have a lot of leeway in Airflow, adding not only operators, sensors, hooks, and executors, but can also provide menu items and other, less visible extensions to the Airflow server. However, you currently can't get an overview of what plug-ins were loaded, or where they came from (some information is logged at DEBUG level but is incomplete).

This makes verifying plug-in operation needlessly complicated. 

Plug-ins are loaded from two locations:

- `.py` files in the directory named by `core.plugins_folder`
- entry points in any setuptools-installed Python project

Per plug-in, ideally the 'versions' page (or a similar page dedicated to plugins) would list:

- plugin name
- source (plugins folder or entry point)
- for plugins folder plugins
   - path relative to the plugins folder
- for entry point plugins
   - the project name and version from the `EntryPoint.dist` object (using `str(entry_point.dist)` should suffice)
   - the entrypoint name, module and attributes information (`str(entry_point)` provides this, already formatted).
   - **NOT** the file location, that'd be a security issue. The entrypoint information is enough to locate the plugin when someone has access to the machine and the Python installation that runs Airflow.
- Optionally: information on the specific extension points provided by the plug-in.

**Comment by mik-laj** [comment]
I added `airflow plugns` command recently. It would be good if the scope of information was similar in these two places.
https://github.com/apache/airflow/pull/9001

Would you like to start working on this ticket? Should I assign you to this?

**Comment by mjpieters** [comment]
> Would you like to start working on this ticket? Should I assign you to this?

Yes and no. :-) I'll have to find time, something I'm short on right now. I'll have a look at how your `airflow plugins` command is implemented, soon.

**Comment by mik-laj** [comment]
I added the "good first issue" label, which will make it easier for other contributors to find this ticket.

**Comment by rootcss** [comment]
@mik-laj I've picked this one as discussed. can you please assign it to me?

**Comment by mik-laj** [comment]
@rootcss I assigned you to this ticket. 

Did you know you can work on more than one ticket if you have time? We do not check if someone has more than one assigned ticket.

**Comment by rootcss** [comment]
> @rootcss I assigned you to this ticket.
> 
> Did you know you can work on more than one ticket if you have time? We do not check if someone has more than one assigned ticket.

Sure. Got it.
