### ISSUE TITLE
Try out (again) BUILDKIT for Docker builds with GitHub registry as cache

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#9192]
**Description**

BUILDKIT provides much better interface/experience for building images (especially segmented images) - we could switch to use it finally (providing that we can easily use cache from registry - most likely GitHub registry rather than DockerHub which should only be used for release purposes. 

**Use case / motivation**

We can have faster/smaller builds for development and release purpose if we switch to Buildkit.

https://docs.docker.com/develop/develop-images/build_enhancements/

**Comment by mik-laj** [comment]
@potiuk Is it done?

**Comment by potiuk** [comment]
Yep. Good catch
