### ISSUE TITLE
Add ability to use key files for Hooks development

### ISSUE THREAD

**Issue by sann05** [apache/airflow#9205]
As I an Airflow developer I want to have the ability to use key files for an API authorization for Hooks development.

Some APIs use key files (including binary files) for authorization.  

How it would look like:

0. _A user is on the "Add Connection" page._
1. Clicks on the "Browse" button opposite to the "Key file" field.
2. Chooses the needed key file.
3. The key file is saved under $AIRFLOW_HOME/key_files/<random_generated_name> (I am not sure if it's necessary, but it will make harder to understand what key file for what exact connection, while it's mapped in the database)

Use case:

0. _Developing a Hook._
1. Get connection by id with BaseHook.get_connection(connection_id) function.
2. Get the absolute path to the key_file with Connection.key_file attribute, so the user can use it in the API authorization.

**Comment by mik-laj** [comment]
@sann05 Have you looked at how this problem was solved in SSHHook?

**Comment by sann05** [comment]
Thank @mik-laj for your answer.

> @sann05 Have you looked at how this problem was solved in SSHHook?

No, but have looked right now. If I am not mistaken there are few options including: 
 - pass a key as a string (which is now always an option) 
 - pass a path to the file

But the main question is: how should I handle the presence of the key_file on the airflow workers?

**Comment by mik-laj** [comment]
Airflow allows you to store extra credentials data in the extra field in a database or secret backend.  Some connections also allow you to point to a local file, but then the system administrator should ensure that the file exists. You can do it in many ways, e.g. NFS, Git-sync, GCS-sync, shared volume, copy this file in the docker image.

The easiest way is to put this file in the Connection table or secret backend. Why is this not an option?

**Comment by sann05** [comment]
@mik-laj my main point was to give the ability to Airflow Administrators/Developers to create connections without interacting with System Administrators or rebuild and redeploying images to the whole cluster.

About secret backends:
I didn't know about secret backends. I'll take a look at this option.

About connection table:
What do you mean by saying "put this file in the Connection table"?
If you mean the usual DB table, that contains information about connections  I have 2 questions:
 1. How can you put my key file there?
 2. How can I retrieve it from it?

**Comment by mik-laj** [comment]
1. In the same way as for SSH. You must put this file in the extra field. If it is a binary file then you can use base64 so that this file can be saved in a JSON file.
2. In the same way as for SSHHook. `BaseHook.get_connections(conn_id="AAA").extra_dejson['private_key']`

**Comment by sann05** [comment]
@mik-laj thank you for your answers. For now, we have the next options:

1.  Store file as a string in the password field (to be masked) or as an extra field in a new connection
2.  Get it from either sync or mount features
3.  Get the as a string from a secret backend

The way I thought about the feature is to store the file **as a file** in DB. But that way we would get unnecessary struggles with checking that file exists on workers.
