### ISSUE TITLE
FILTER_BY_ONWER does not work for multi-owner dags 

### ISSUE THREAD

**Issue by 51yu** [apache/airflow#9213]
**Apache Airflow version**:
1.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
owner field of dags `owner1, owner2, owner3`
owner1 can not see the dag 

https://github.com/apache/airflow/blob/v1-10-stable/airflow/www/views.py#L2271

**Comment by dephusluke** [comment]
probably @kaxil can

**Comment by kaxil** [comment]
That commit is 4 years old :D so something else might have reverted back that behaviour. 

I will mark it for 1.10.12

**Comment by 51yu** [comment]
@kaxil Thanks for helping. I create another relevant issue
https://github.com/apache/airflow/issues/9711

**Comment by kaxil** [comment]
We have deprecated the old UI and from Airflow 2.0.0 the new RBAC UI will be the default UI. Hence all the changes to old UI have been freezer. Please use the RBAC UI -- https://airflow.apache.org/blog/airflow-1.10.12/#use-airflow-rbac-ui
