### ISSUE TITLE
UI/TZ issue: incorectly mapping DAGs 

### ISSUE THREAD

**Issue by ebacal** [apache/airflow#9221]
**Apache Airflow version**:
1.10.9 and 1.10.10

**Environment:**:

- MySQL 5.7, TZ=PST
- airflow.cfg tested with time_zone=system, Los_Angeles/America, utc

**What happened**:

1. From a schedule view by clicking on DAG with Execution date 18:00 PST it maps me to 18:00 UTC DAG instance
2. In Browse TASK INSTANCE view, sorted by state failed displays correct tasks but when I choose to clear them it clears  task with UTC  execution dates

**How to reproduce it**:

In UI click under "Schedule" on gray schedule time button for any DAG 
Take first DAG and check its "Execution date" 

<img width="1757" alt="Screen Shot 2020-06-10 at 4 12 46 PM" src="https://user-images.githubusercontent.com/43861342/84327924-7606e080-ab35-11ea-9bd7-365ac8faff45.png">

click on it 

<img width="1749" alt="Screen Shot 2020-06-10 at 4 14 59 PM" src="https://user-images.githubusercontent.com/43861342/84327999-a8184280-ab35-11ea-9386-410865dfcdba.png">

open log and compare time stamps inside the log with "Execution date"

<img width="1235" alt="Screen Shot 2020-06-10 at 4 16 56 PM" src="https://user-images.githubusercontent.com/43861342/84328115-ee6da180-ab35-11ea-9808-3a1b2a370ebb.png">

**Bonus: miscalculating execution time in UI when in TZ aware**:

**1.10.10**

UI TZ=UTC - Correct Execution time stamp

<img width="1756" alt="Screen Shot 2020-06-10 at 4 28 43 PM" src="https://user-images.githubusercontent.com/43861342/84328893-1a8a2200-ab38-11ea-874a-344ba8710ed5.png">

UI TZ=PST - Incorrect Execution time stamp

<img width="1764" alt="Screen Shot 2020-06-10 at 4 25 16 PM" src="https://user-images.githubusercontent.com/43861342/84328634-5ec8f280-ab37-11ea-874b-0d085f7e88fc.png">

**Comment by ashb** [comment]
What frequency is your dag? Hourly? (This is not part of the problem, but would help in reproducing the issue)

**Comment by ebacal** [comment]
The one above is 5 min.  I have tried 1/5/30 min intervals, as well.

**Comment by ebacal** [comment]
Issue is fixed in 1.10.11 release
