### ISSUE TITLE
请问离线安装airflow 1.10   如何操作，有相关文档么？

### ISSUE THREAD

**Issue by michal5210** [apache/airflow#9225]
大家好，请问airflow 的离线安装相关资料哪里可以获得，在下浏览了一遍1.10安装，都是在线的，用不了啊

**Comment by potiuk** [comment]
Please use slack to ask your questions and preferably use English (See https://airflow.apache.org /community section for details)

**Comment by michal5210** [comment]
> Please use slack to ask your questions and preferably use English (See https://airflow.apache.org /community section for details)

sorry,I'm just looking for an offline installation file about v1.10-stable
