### ISSUE TITLE
dags state refresh

### ISSUE THREAD

**Issue by zstan** [apache/airflow#923]
hello, thank you for airflow ones more.
look i have some kind of trouble with 1.6.2 ver (1.5.2 the same) if i add new dag i couldn`t see some state information, logs and so on from web interface before webserver restart, after restart all ok.
pic1,2 _before_ webserver restart pic3 _after_
i use 
_executor = CeleryExecutor_
and process looks like :
`ps aux | grep airflow
zstan    14040  0.0  0.8 264304 73116 pts/2    S    Jan27   0:17 /usr/bin/python /usr/local/bin/airflow serve_logs

zstan    14428  8.2  1.0 285332 82212 pts/2    S    Jan27 119:53 /usr/bin/python /usr/local/bin/airflow scheduler

postgres 21747  3.0  0.1 249640  8796 ?        Ss   12:50   0:30 postgres: airflow airflow ::1(47056) idle in transaction       

root     22469  0.0  0.0  66152  2424 pts/2    S+   13:01   0:00 sudo airflow webserver -p 80 -hn [::]

root     22470  0.2  0.9 275016 78224 pts/2    S+   13:01   0:00 /usr/bin/python /usr/local/bin/airflow webserver -p 80 -hn [::]

postgres 22476  0.0  0.0 249008  6984 ?        Ss   13:01   0:00 postgres: airflow airflow ::1(47065) idle                           

root     22477  0.0  0.1  54656 13904 pts/2    S+   13:01   0:00 gunicorn: master [airflow.www.app:cached_app()]      

root     22482  0.1  0.9 275824 78156 pts/2    S+   13:01   0:00 gunicorn: worker [airflow.www.app:cached_app()]    

root     22483  0.2  0.9 275952 78528 pts/2    S+   13:01   0:00 gunicorn: worker [airflow.www.app:cached_app()]  
root     22484  0.2  0.9 276756 79412 pts/2    S+   13:01   0:00 gunicorn: worker [airflow.www.app:cached_app()]     

root     22487  0.2  0.9 276288 78420 pts/2    S+   13:01   0:00 gunicorn: worker [airflow.www.app:cached_app()]     

postgres 22494  0.0  0.0 249008  6980 ?        Ss   13:01   0:00 postgres: airflow airflow ::1(47066) idle  
postgres 22495  0.0  0.0 249604  7424 ?        Ss   13:01   0:00 postgres: airflow airflow ::1(47067) idle  
postgres 22496  0.0  0.0 249008  6988 ?        Ss   13:01   0:00 postgres: airflow airflow ::1(47068) idle  
postgres 22497  0.0  0.0 249604  7448 ?        Ss   13:01   0:00 postgres: airflow airflow ::1(47069) idle  
zstan    22610  0.0  0.0  11744   940 pts/4    S+   13:07   0:00 grep --color=auto airflow
`

![airflow1](https://cloud.githubusercontent.com/assets/1107510/12641255/9a43a542-c5bf-11e5-8c9f-60e491138256.png)
![airflow2](https://cloud.githubusercontent.com/assets/1107510/12641256/9a448f34-c5bf-11e5-958b-9b73850192bc.png)
![airflow3](https://cloud.githubusercontent.com/assets/1107510/12641257/9a4acbba-c5bf-11e5-9952-9e225fd651ae.png)

is this a bug ? thanks !

**Comment by mistercrunch** [comment]
Did you hit the refresh button to the right there?

**Comment by zstan** [comment]
pic2 is created after hitting, "dag is now fresh like a ...." header ! May be i forgot to run some component? webserver, scheduler, worker is it ok for refreshing ?

**Comment by zstan** [comment]
my problem was - that untill dag still working the state remain non active (like shows in pics), after all jobs are done it became active. Sorry and thank you ! Issue - couldn`t be fixed, it`s seems all ok.
