### ISSUE TITLE
SLA notifications for long running tasks, regardless of the schedule and task predecessors

### ISSUE THREAD

**Issue by OleksandrBerchenko** [apache/airflow#9233]
**Description**

Current SLA implementation has two serious limitations:

1. It doesn't work for manually triggered DAGs.
2. It can calculate duration starting only from the DAG scheduled time, not from the actual task start time.

**Use case / motivation**

The following simple use case is not covered:

I want an email notification when a particular task runs for too long (like more than 30 minutes).

**Related Issues**

See also https://github.com/apache/airflow/issues/7959.

**Comment by eladkal** [comment]
Should be a part of https://github.com/apache/airflow/issues/18031
