### ISSUE TITLE
docker module in the requirements but not installed

### ISSUE THREAD

**Issue by dinigo** [apache/airflow#9234]
**Apache Airflow version**: 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: docker image

**What happened**:
`DockerOperator` does not work beacuase depends on `docker` module 

How shoud we indicate in the Dockerfile that this should be installed? I suppose that a new "extra" called  `docker` has to be created, so that we can install it with `pip install apache-airflow[docker]`.

**What you expected to happen**:

`docker` module being installed at some point in the Dockerfile

**How to reproduce it**:

Invoke a `DockerOperator` based task and it will produce the following error
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 238, in process_file
    loader.exec_module(m)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/c4m_dag.py", line 1, in <module>
    from airflow.providers.docker.operators.docker import DockerOperator
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 25, in <module>
    from docker import APIClient, tls
ModuleNotFoundError: No module named 'docker'
```
 
**Anything else we need to know**:
I see it is listed in the "requirements.txt" file. But as this file is used as a constrain then it's not installed.  From the [pip](https://pip.pypa.io/en/stable/user_guide/#constraints-files) documentation we can see
> Constraints files are requirements files that only control which version of a requirement is installed, not whether it is installed or not.

**Comment by potiuk** [comment]
You will find answer in the IMAGES.rst file. You can build your own version of the image and specify
AIRFLOW_EXTRAS if you build the image. in the master version of the image you can keep the default extras and specify ADDITIONAL_AIRFLOW_EXTRAS as well
