### ISSUE TITLE
Allow a Google API credentials object to be provided for GoogleBaseHook

### ISSUE THREAD

**Issue by dgorelik** [apache/airflow#9236]
**Description**

Allow a a Google API credentials object to be provided for GoogleBaseHook. I think this would be as  simple as updating the initializer to set `self._cached_credentials` to a passed-in arg here:
https://github.com/apache/airflow/blob/daed75260903119f8f5dc8ee493778c50b1a6a8f/airflow/providers/google/common/hooks/base_google.py#L156

**Use case / motivation**

This should allow a service accounnt running Airflow to [impersonate another service account](https://google-auth.readthedocs.io/en/latest/reference/google.auth.impersonated_credentials.html), without needing to deal with exported service account keys as the connection ID paradigm seems to require.

Does this change make sense given the Airflow architecture?

**Comment by dgorelik** [comment]
Note: if this idea makes sense, I am happy to send a PR to implement it.

**Comment by mik-laj** [comment]
I wonder why we can't improve the current implementation of impersonated service? For now, you can interpersonal to another account using delegate_to parameter. This parameter is available in hook and operators, so its use is very easy.

**Comment by dgorelik** [comment]
> I wonder why we can't improve the current implementation of impersonated service? For now, you can interpersonal to another account using delegate_to parameter. This parameter is available in hook and operators, so its use is very easy.

When used with the Google Auth library, `delegate_to` is used for "Domain-wide delegation allows a service account to access user data on behalf of any user in a Google Apps domain without consent from the user." (https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#domain-wide-delegation)
That is, it's not for delegating on behalf of a GCP service account.

**Comment by mik-laj** [comment]
@dgorelik It is related? https://github.com/apache/airflow/issues/8803

@jaketf What do you think about it? Will it be useful to your users?

**Comment by dgorelik** [comment]
@mik-laj I think this is actually a duplicate of https://github.com/apache/airflow/issues/8803

**Comment by mik-laj** [comment]
I started an internal discussion about support for this feature. However, this is a duplicate, so I close this ticket.
