### ISSUE TITLE
Encrypted variables

### ISSUE THREAD

**Issue by caseybrown89** [apache/airflow#924]
It would be great if it was possible to encrypt variables similar to how connections can be encrypted.  My use case is that I'm using the PostgresOperator to execute a COPY command into Amazon Redshift.  The COPY command requires that I pass in two keys, aws_access_key_id and aws_secret_access_key.  I would prefer that I didn't have to store aws_secret_access_key in plain text in the variables section.

**Comment by r39132** [comment]
+1 This is something we need as well. We have all sorts of 3rd party API integrations that require some sort of key management solution (VictorOps/PagerDuty, Loggly/SumoLogic/LogEntries/DataDog/, Slack, etc...). For people that use AWS, there can be some integration with KMS (Key Management System/Store?) or some other option. This is a good feature request.

The argument could be made that all 3rd party integrations be developed via hooks that use connections and leveraged via operators (if I understand the relationship between those concepts correctly), but it's better to offer the encrypted variable route as well as that makes it easier for people using the general-purpose PythonOperator to make API calls out to 3rd parties.

**Comment by criccomini** [comment]
This seems interesting. I'm sure we will have some encrypted-variable use cases, but the encryption use case that I have is slightly different. If we run code inside a Docker (https://github.com/airbnb/airflow/pull/882) container, which needs some certs to access things, we have no easy way of getting them there. The difference here is that 1) We already have a secret store already (https://github.com/hashicorp/vault) and 2) I am interested in files, not strings.

**Comment by mistercrunch** [comment]
also encrypting the extra field in connections

**Comment by r39132** [comment]
I can take a crack at it.

**Comment by r39132** [comment]
@mistercrunch  What is the `extra` field for? Is it a notes section?

**Comment by mistercrunch** [comment]
The `extra` field is used for json blobs for anything connection related that doesn't really fit into the classic host/login/psw classic pattern. Say a specific API might have a key or some account id. The HiveOperator supports a beeline=True extra param, ... You can grep for extra under hooks and see how it's been used so far.

**Comment by caseybrown89** [comment]
One example where it should be encrypted -  the S3Hook pulls the aws access
key and aws secret key from the extra field.

**Comment by r39132** [comment]
Okie.. I have something working for the "extra" parameter.. One question.. on the connection list page, I'd like to display one new control for "is extra field encrypted".. but can't figure out where to add that config.

**Comment by r39132** [comment]
@mistercrunch I have this working for the "extra" field with one exception. Refer to the screen shot below. For "sid_test", I encrypt the extra field. For the other connections, how is the "disabled" rendedered for "is_encrypted"?

<img width="888" alt="screenshot 2016-01-29 16 53 04" src="https://cloud.githubusercontent.com/assets/581734/12692195/cbb1545a-c6a8-11e5-9a09-8779d4f77818.png">

**Comment by r39132** [comment]
I have set the default to False in the model.py file. 

```
is_encrypted = Column(Boolean, unique=False, default=False)
is_extra_encrypted = Column(Boolean, unique=False, default=False)
```

And I've disabled the widget in views.py

```
    form_widget_args = {
        'is_encrypted': {'disabled': True},
        'is_extra_encrypted': {'disabled': True},
    }
```

**Comment by r39132** [comment]
Also, it looks like the first column has disappeared.. the one with the edit and trash icons :-).. looks like master head is broken?

**Comment by r39132** [comment]
@mistercrunch I'm having trouble figuring out where your connection_list page gets the 'minus' css images specified for the false values of is_encrypted. I'm trying to fill the is_extra_encrypted with those same 'minus' images. The "checkmark" image is showing up fine, as you can see in the image I shared above, but not the minus images.

**Comment by r39132** [comment]
To encrypt the `extra` field, I have a fix : 
https://github.com/airbnb/airflow/pull/934

**Comment by r39132** [comment]
https://github.com/airbnb/airflow/pull/947 Here is the PR for encrypting variables in the DB.

@mistercrunch ^

**Comment by r39132** [comment]
@caseybrown89 This takes care of encrypting stuff in the DB .. though I imagine you still want some authorization functionality to only allow admins to see variables values.. and not everyone.

**Comment by r39132** [comment]
We can close this @mistercrunch
