### ISSUE TITLE
Docker Image Compatibility with Openshift/Kubernetes

### ISSUE THREAD

**Issue by flymg** [apache/airflow#9248]
**Description**

The new production ready Docker images are not compatible out of the box for Openshift Deployment, as some Openshift key concepts where violated.

Example:
apache/airflow:1.10.10-python3.7

**Use case / motivation**

Reference: https://docs.openshift.com/container-platform/3.7/creating_images/guidelines.html
- Image must be runnable with arbitrary userid
- Image must be runnable without associated entry in /etc/passwd

A Key Problem is the installation of python requirements as uid 50000 (airflow).

**Workaround**

```Dockerfile
FROM apache/airflow:1.10.10-python3.7

ARG PYTHON_MAJOR_MINOR_VERSION="3.7"
ENV PYTHON_MAJOR_MINOR_VERSION=${PYTHON_MAJOR_MINOR_VERSION}

# Modifications to the make image compatible with Openshifts Support Arbitrary User IDs
# https://docs.openshift.com/container-platform/3.7/creating_images/guidelines.html
USER root
# directories to be modified
RUN chgrp -R 0 /home/airflow && chmod -R g=u /home/airflow
RUN chgrp -R 0 ${AIRFLOW_HOME} && chmod -R g=u ${AIRFLOW_HOME}

# additionally, airflow users python site-packages must be available to arbitrary user as well
# Reference: https://stackoverflow.com/a/7901603
RUN echo "/home/airflow/.local/lib/python${PYTHON_MAJOR_MINOR_VERSION}/site-packages" > /usr/local/lib/python${PYTHON_MAJOR_MINOR_VERSION}/site-packages/airflow.pth

RUN chmod g=u /etc/passwd
...
```

Also a Shell Script must be used after startup to add a username, if none is found
```sh
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi
```

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/issues/8706 It is related?

**Comment by flymg** [comment]
@mik-laj 

> #8706 It is related?

Yes, but #8706 is not enough.
pip installation must be changed as well.

**Comment by potiuk** [comment]
Yep. We will need to change both. Thanks, @flymg for posting the link to the guidelines - will be helpful. We target to make those changes in 1.10.11 release.

**Comment by altunbaratli** [comment]
Hello @flymg,
Thank you very much for your workaround, this helped me to figure out the issue that I was surviving for a while.
As I am new to docker stuff, I am not fully sure how to run your additional shell script after startup. Rn, I am having error "'getpwuid(): uid not found: 1001380000'" . P.S I am not able to add additional commands in the docker run .. . I have to handle this script inside of dockerfile. Thanks.

**Comment by flymg** [comment]
@altunbaratli have a look at the puckel Docker image for airflow, which uses a shellscript as entrypoint
Place the script above inside
