### ISSUE TITLE
Please update Qubole hook to include Jupyter Notebooks

### ISSUE THREAD

**Issue by Blackrobe** [apache/airflow#9252]
**Description**

`qds-sdk` already supports JupyterNotebookCommand (https://github.com/qubole/qds-sdk-py/blob/master/qds_sdk/commands.py#L1351) since version 1.15.0 (change notes here https://github.com/qubole/qds-sdk-py/releases/tag/V1.15.0)

and Airflow through `requirements.txt` already includes `qds-sdk` version 1.16.0 https://github.com/apache/airflow/blob/master/requirements/requirements-python3.7.txt#L309

but this hook https://github.com/apache/airflow/blob/master/airflow/providers/qubole/hooks/qubole.py#L26-L29 (also L39-L50) has not been updated yet. 

I suggest we add following the pattern on https://github.com/qubole/qds-sdk-py/blob/master/bin/qds.py#L39

I already planned a fix https://github.com/apache/airflow/commit/785992d1dec6f7f837f1ffbb604535240e22d2bc
but I have never do/opened any PR to Airflow before in my life and I was overwhelmed by the requirements before opening a PR :roll_eyes: (but I understand what the requirements are for) could someone kindly guide me

**Use case / motivation**

I want Airflow's Qubole operator to be able to interact with Qubole Jupyter Notebooks. It's already in the Qubole SDK.

**Comment by mik-laj** [comment]
> but I have never do/opened any PR to Airflow before in my life and I was overwhelmed by the requirements before opening a PR 🙄 (but I understand what the requirements are for) could someone kindly guide me

There are two most important things.
1. You need to create a Pull Request. https://opensource.com/article/19/7/create-pull-request-github
2. CI should be green (except quarantine tests)
3. You are fully responsible for your change.  If your change has not gained the attention of any member of the community, then you must fix it.
> Ping @ #development slack, comment @people. Be annoying. Be considerate.

We also have a contributor guide:
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
