### ISSUE TITLE
Read-only file system and error installing airflow

### ISSUE THREAD

**Issue by manuelarod** [apache/airflow#9265]
I am trying to install airflow on my computer using the "requirements-python3.5.txt" file. However, I'm getting a read-only file system and when trying to install airflow I get the following error. I tried running this command: sudo chown -R vagrant /home/vagrant/.cache but it didn't work either. I have no idea how to solve this and what else to do to be able to install airflow. 
<img width="843" alt="Screen Shot 2020-06-12 at 6 09 17 PM" src="https://user-images.githubusercontent.com/56454556/84553025-5eb42880-acd8-11ea-8d67-f056075c9221.png">

**Comment by potiuk** [comment]
Please read the message displayed when you create issues. Do not use GitHub issues for questions and your system troubles. Go to https://airflow.apache.org/community/. and you will find "ask a question" chapter where you can join slack and ask questions like that there.
