### ISSUE TITLE
deleting airflow dag run will delete also the related task instances

### ISSUE THREAD

**Issue by AndresNamm** [apache/airflow#9271]
For example: I have a dag that has successful runs from 2018-2020. I change a couple of ETL steps in my dag and would like to rerun the dag for this period. It would be intuitive to just delete the existing dag runs in this period so the dag runs and the tasks in them would be scheduled again. However, based on my current tests when I delete the dag runs, the scheduler will schedule the dags again however as the tasks still exist and are successful, airflow will mark the 2018-2020 dag runs as successful without rerunning the tasks.

**Comment by kk17** [comment]
any plan for developing the feature?

**Comment by eladkal** [comment]
Wouldn't you just need to clear the relevant runs? Then it will execute them with the updated steps.
