### ISSUE TITLE
Decrypt secrets from SystemsManagerParameterStoreBackend

### ISSUE THREAD

**Issue by feluelle** [apache/airflow#9275]
**Description**

Currently you cannot retrieve secrets from _AWS System Manager - Parameter Store_ which are encrypted i.e. stored as `SecureString`, because we explictly set it to not use decryption: https://github.com/apache/airflow/blob/cbebed2b4d0bd1e0984c331c0270e83bf8df8540/airflow/providers/amazon/aws/secrets/systems_manager.py#L106

**Use case / motivation**

One may want to secure their parameters / secrets through encryption and so uses `SecureString` to achieve this. To support this we need to enable decryption.

**Comment by kaxil** [comment]
Related PR: https://github.com/apache/airflow/pull/9214
