### ISSUE TITLE
Unable to store xcom because of MySQL BLOB type limitation

### ISSUE THREAD

**Issue by yene** [apache/airflow#9299]
**Apache Airflow version**:
Airflow 1.10.10, 2020-04-09

**Environment**:
- MySQL: 5.7.30

**What happened**:
Storing a message bigger than 65,535 bytes resulted in a mysql error.
```
(_mysql_exceptions.DataError) (1406, "Data too long for column 'value' at row 1")
```

**What you expected to happen**:

No error, since this amount of data is still the range of acceptable payload sizes.

**How to reproduce it**:

**Anything else we need to know**:
sqlalchemy `sa.PickleType()` uses BLOB on MySQL which limits xcom.value to 65,535 bytes. 

`sa.PickleType()` uses BYTEA in Postgres which is has a much higher max size.

**Comment by superina5** [comment]
experienced the same isseu, upvote +1

**Comment by vikramkoka** [comment]
Just as a note, the maximum xcom value to be stored is defined as being 49344 bytes. 
In the code, this is defined as MAX_XCOM_SIZE = 49344

**Comment by potiuk** [comment]
I agree with @vikramkoka -> XCOM is not supposed to store big amounts of data and MAX_XCOM_SIZE is the maximum you can expect. Rather than increasing the limits I'd turn that into an issue to verify that the MAX_XCOM_SIZE is consistently applied everywhere. The limitation is not due to limit on the field size it is because of the frequency of accessing and model of accessing the XCOM table by Airflow - allowing for much bigger xcom fields might open up scenarios where different components start throttling each other and the whole system might become unusable. This is a dangerous path to go through.

**Comment by yene** [comment]
In my opinion MySQL type should not limit users, maybe VARBINARY would fit?

**Comment by eladkal** [comment]
I'm closing this as won't fix.
You can set alternative xcom backend if needed.

**Comment by vietvudanh** [comment]
I do not use xcom for data exchange but still get this error. It is because the key `return_value` of my BashOperator's output is too big; over 65,535 bytes.
This is kind of annoying, is there config where airflow can just truncate the output to the max value, before inserting into database?

**Comment by potiuk** [comment]
It's the problem with your Bash script. By default Bash operator will store LAST LINE of your output to XCom: see the documentation http://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html#module-airflow.operators.bash 

If your Bash prints 65k last line then yes, this is the problem you will get at.

**Comment by vietvudanh** [comment]
> It's the problem with your Bash script. By default Bash operator will store LAST LINE of your output to XCom: see the documentation http://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html#module-airflow.operators.bash
> 
> If your Bash prints 65k last line then yes, this is the problem you will get at.

I have read the source code for [1.10](http://airflow.apache.org/docs/apache-airflow/1.10.12/_modules/airflow/operators/bash_operator.html#BashOperator.execute) and [latest](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/operators/bash.html#BashOperator.execute)

it looks like the `return last line` is only correct for version `1`, not `2` (I am using `v2.1.1`)

**Comment by potiuk** [comment]
```
result = self.subprocess_hook.run_command(
```

```
        self.log.info('Output:')
            line = ''
            for raw_line in iter(self.sub_process.stdout.readline, b''):
                line = raw_line.decode(output_encoding).rstrip()
                self.log.info("%s", line)

            self.sub_process.wait()

            self.log.info('Command exited with return code %s', self.sub_process.returncode)

        return SubprocessResult(exit_code=self.sub_process.returncode, output=line)
```

**Comment by vietvudanh** [comment]
> SubProcessHook

Thank you, after looking into SubProcessHook I have realized the problem, it was indeed my script.

**Comment by seunggabi** [comment]
### My solution.

```sql

alter table xcom
             modify value MEDIUMBLOB null;

```
