### ISSUE TITLE
depends_on_past at DAG level

### ISSUE THREAD

**Issue by rijuk** [apache/airflow#93]
I have a DAG which looks like the following:
t1 -> t2

When I run a backfill for this DAG (say for day1 and day2) , I want to make sure that the DAG for day2 gets executed only after the DAG for day1 is complete. From the name, "depends_on_past" looked like the right thing to use. However, it works at the task level. In other words, t1 for day2 starts executing after t1 for day1 is complete before t2 for day1 is completed.

Is there a way to force a similar "depends_on_past" at the DAG level?

**Comment by artwr** [comment]
@rijuk, What you are looking for is the parameter `wait_for_downstream`. A run for a task instance will then only happen if previous runs of the downstream tasks are complete.

**Comment by mistercrunch** [comment]
"A run for a task instance will then only happen if previous runs of the **directly** downstream tasks of that task are **succesful**."

If you want to force the completion of the entire DAG, you'll need to put a trigger (say you could land a dummy trigger file in HDFS or S3) at the very end of all the tasks in your DAG, and use a sensor at the very beginning of your DAG (waiting for that that trigger file to show up in HDFS or S3).

**Comment by rijuk** [comment]
Thanks.
