### ISSUE TITLE
Create DatafusionPipelineStateSensor

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#9300]
**Description**

Create a sensor that will wait for Cloud Datafusion pipeline to be in expected state.

**Use case / motivation**

_Originally posted by @jaketf in https://github.com/apache/airflow/pull/8954#discussion_r438261904_

**Related Issues**

#8673

**Comment by turbaszek** [comment]
@mik-laj what is the reason to close this issue? Was this sensors implemented?

**Comment by mik-laj** [comment]
it felt like it was finished.  I saw the related PR that is closed.

**Comment by turbaszek** [comment]
The PR fixed the operator that works in a synchronous manner. This ticket is about creating a sensors and allowing async mode in `DatafusionCreatePipelineOperator` similar to #10673

**Comment by eladkal** [comment]
functionality added in https://github.com/apache/airflow/pull/17787
