### ISSUE TITLE
Airflow Slots parameter in Airflow 2.0

### ISSUE THREAD

**Issue by afsalabdup** [apache/airflow#9301]
Team, I am using slots parameter along with 'pool' in bash operator. My task is dependent on a resource/pool named "abc" and it needs at least 1 available slot to run. So the code will look like below.

run_this_xyz = BashOperator(
        task_id='task_1',
        bash_command=' /path/abc.sh  ',
        pool='abc',
        slots=1,
        dag=dag
)

When I am running the dags, I see below warning. Seems like 'slots' parameter won't be available in Airflow 2.0 version. May I know how to specify slots in Airflow 2.0 version ?

[2020-06-15 01:17:46,175] {bash_operator.py:128} INFO - **kwargs: {'slots': 1}
 Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:

**Comment by mik-laj** [comment]
This parameter in Airflow 1.10 and 2.0 is named `pool_slots`.

> pool_slots (int) – the number of pool slots this task should use (>= 1) Values less than 1 are not allowed.

<img width="880" alt="Screenshot 2020-06-15 at 12 17 31" src="https://user-images.githubusercontent.com/12058428/84646325-37d93a80-af02-11ea-8dcd-76c9227df7ba.png">

**Comment by afsalabdup** [comment]
Thanks @mik-laj
