### ISSUE TITLE
Implement per-provider CI test scheme

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#9318]
**Description**

Now when we have a clean split between providers, we can improve our CI testing patterns to only run those tests that are relevant to the change.

The logic proposed:

* If any of the "core" files change -> run all tests

* If only the  "provider" files change -> run only the tests for that provider and for all providers that depends on it.
* If only some "provider" files change -> we might only try to build documentation for that provider
* If only some "provider" files change -> we might only build and tests those provider packages

**Use case / motivation**

That will speed up CI tests and free slots for more parallel builds

**Comment by RNHTTR** [comment]
@potiuk isn't this complete?

**Comment by potiuk** [comment]
oh yeah. Done (even more than that because we are also building and testing all "cross-dependent" providers.
