### ISSUE TITLE
Head Master seems to have a bug on the connection list page

### ISSUE THREAD

**Issue by r39132** [apache/airflow#932]
There is no way to edit the connections? The "pencil" and "trash" icons are missing from each row.

<img width="1440" alt="screenshot 2016-01-29 17 31 16" src="https://cloud.githubusercontent.com/assets/581734/12692610/407552aa-c6ae-11e5-84d1-fe19c54cf669.png">

**Comment by mistercrunch** [comment]
Can't reproduce... I feel like someone reported a similar issue recently and might have found a solution. Re-installing flask-admin to >=1.4.0 (from memory)?

**Comment by r39132** [comment]
This is resolved. It seems that as root (on Mac), I had flask-admin at 1.2.0. Whenever I did `pip freeze | grep -i flask-admin`, even when sudo'd, I only saw 1.4.0.

Anyway, I uninstalled 1.2.0 and installed 1.4.0 and it works.

**Comment by mistercrunch** [comment]
FYI @askeys
