### ISSUE TITLE
How to create a role that can browse DAGs but not pause/unpause them?

### ISSUE THREAD

**Issue by KayleMaster** [apache/airflow#9324]
Hi,

I've tried the Viewer role and while it doesn't have the "can_paused" permission, it can still pause/unpause DAGs which is problematic for us.  
Is there something I'm missing?

**Comment by KayleMaster** [comment]
Care to elaborate why this issue is closed? I can't find any help on the slack channel

**Comment by potiuk** [comment]
Heloy yes. The general issues and questions are not handled via the Github issue. It is actually stated when you try to open such issue. Apologise if it was not clear. I closed a bunch of such issues to clean them up. We do encourage you to seek help at slack or devlist - and be persistent. This project is run mostly by volunteers and often users can help each other. Addiitonally I do recommend to join the Airlfow Summit that just started https://airflowsummit.org/
