### ISSUE TITLE
unable to install papermill provider

### ISSUE THREAD

**Issue by yash64** [apache/airflow#9328]
I am trying to install papermill provider for airflow but i get an error. I am running airflow on Ubuntu 18.04. Below are the details

```
yaswanth@DESKTOP-TUTMG4J:~$ airflow version
1.10.10
yaswanth@DESKTOP-TUTMG4J:~$ python3 --version
Python 3.6.9
```
```
yaswanth@DESKTOP-TUTMG4J:~$ pip3 install apache-airflow-backport-providers-papermill
Collecting apache-airflow-backport-providers-papermill
  Could not find a version that satisfies the requirement apache-airflow-backport-providers-papermill (from versions: )
No matching distribution found for apache-airflow-backport-providers-papermill
```
Just to check if any other providers with same requirements are also failing and I tried amazon provider
```
yaswanth@DESKTOP-TUTMG4J:~$ pip3 install apache-airflow-backport-providers-amazon
```
and this installed successfully but papermill is failing. Can someone please help on this.

**Comment by potiuk** [comment]
Papermill provider has been removed from distributions. I will explain the reasons for all the removals in final documentation (I am planning to make a new RC today or tomorrow latest). 

Current implementation of Papermill provider does not provide any advantage over the 1.10.* version except being tightly integrated with 2.0 way of lineage implementation which is backwards-incompatible with version 1.10. I hope we will have AIP-31 in place (Functional DAGs) that will enable to implement lineage in much more future-proof way, and then we might remove the current Papermill lineage approach and make the backport package for it released separately.

**Comment by yash64** [comment]
@potiuk Thanks for your reply. Does that mean PapermillOperator will not be available in future versions also? In case if it is not available, can you please help on other options available to schedule Jupyter notebooks using Airflow.

**Comment by mik-laj** [comment]
@yash64  This operator will still be available in Airflow 2.0 and 1.10. It will not be part of the backport packages.

**Comment by yash64** [comment]
@mik-laj Then how can I install papermill in Airflow 1.10? `pip3 install apache-airflow-backport-providers-papermill` was the suggested way but this is not working. Any other way?

**Comment by mik-laj** [comment]
You don't to install. It is available out-of-box: https://airflow.readthedocs.io/en/1.10.10/_api/airflow/operators/papermill_operator/index.html

**Comment by yash64** [comment]
Thanks @mik-laj
