### ISSUE TITLE
List of downstream tasks for a task

### ISSUE THREAD

**Issue by afsalabdup** [apache/airflow#9343]
It would be great if we have a airflow command which list all downstream tasks for a task. For example, there are 4 tasks in a dag - dummy1 > dummy2 > dummy3 > dummy4. I need list of all downstream tasks of dummy2, output should be dummy3 and dummy4. I believe currently there is no airflow command to list downstream tasks for a task.

**Comment by kaxil** [comment]
Can you let us know the use-case for it?

There is a show_dag command: https://airflow.readthedocs.io/en/stable/cli-ref.html#show_dag
to view the shape of the DAG.

And if you want to get downstream_tasks for tests, you can directly use the following code:

```
dag.task_dict[task_id].downstream_task_ids
```

**Comment by afsalabdup** [comment]
Consider DAG which contains 4 tasks - Dummy1 > Dummy2 > Dummy3 > Dummy4 
If I want to put a future instance task 'Dummy2' ON HOLD, we can mark that task to success through CLI by providing future execution id, but the issue is when I mark that task to success, downstream tasks (Dummy3 and Dummy4) will start running immediately because downstream will check if its upstream Dummy2 is success or not. I want to put all downstream tasks ON HOLD, means I need to mark all downstream tasks to success, so that Dummy2's downstreams won't trigger by itself. If we can include downstream tasks while marking Dummy2 to success, then we do not have to run 'mark success' commands individually for all downstream tasks.

**Comment by eladkal** [comment]
The feature request here is put task on hold which you opened a separated issue for https://github.com/apache/airflow/issues/9298

The rest is questions how to achieve this functionality without having the feature which are more suitable for https://stackoverflow.com/
