### ISSUE TITLE
QuboleHook unable to build command with list tags

### ISSUE THREAD

**Issue by egibbm** [apache/airflow#9347]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Google Cloud
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- **Kernel** (e.g. `uname -a`): Linux int-vidio-stats-airflow-bionic 5.0.0-1034-gcp #35-Ubuntu SMP Tue Mar 17 03:56:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: pip
- **Others**:

**What happened**:

Recently, we upgraded airflow version from v1.10.5 to v1.10.10 due to airflow instance that upgraded to ubuntu bionic. Existing dag configuration having tags as list causes  an issue at some jobs that use Qubole.
Error log:

```
Traceback (most recent call last):
  File "/home/jenkins/virtualenv/airflow/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/jenkins/virtualenv/airflow/lib/python3.6/site-packages/airflow/contrib/operators/qubole_operator.py", line 207, in execute
    return self.get_hook().execute(context)
  File "/home/jenkins/virtualenv/airflow/lib/python3.6/site-packages/airflow/contrib/hooks/qubole_hook.py", line 131, in execute
    args = self.cls.parse(self.create_cmd_args(context))
  File "/home/jenkins/virtualenv/airflow/lib/python3.6/site-packages/airflow/contrib/hooks/qubole_hook.py", line 248, in create_cmd_args
    self._add_tags(tags, value)
  File "/home/jenkins/virtualenv/airflow/lib/python3.6/site-packages/airflow/contrib/hooks/qubole_hook.py", line 267, in _add_tags
    tags.extend(value)
AttributeError: 'set' object has no attribute 'extend'
```

**What you expected to happen**:

the tags should be included as a comma separated arguments to the build command.

**How to reproduce it**:
using sample dag having list tags
```
    t2 = QuboleOperator(
        task_id='hive_gcs_location',
        command_type="hivecmd",
        script_location="s3n://public-qubole/qbol-library/scripts/show_table.hql",
        notify=True,
        tags=['tag1', 'tag2'],
        trigger_rule="all_done"
    )
```
and do an airflow run.

**Comment by mik-laj** [comment]
@chattarajoy @anmol-dhingra @randuhmm Can you take a look at this ticket? Would you like to help solve it?

**Comment by chattarajoy** [comment]
@mik-laj this was fixed with https://github.com/apache/airflow/pull/9349

**Comment by mik-laj** [comment]
@chattarajoy Awesome! 

This is one more topic. We are trying to improve our documentation, and I see a guides that explains how to use these operators is missing. Here are guides for other operators: https://airflow.readthedocs.io/en/latest/howto/operator/index.html
Wouldn't you like to write a guide for this operator?

**Comment by mik-laj** [comment]
This provider also has poor typing coverage.
https://github.com/apache/airflow/issues/9708#issuecomment-687518888

**Comment by chattarajoy** [comment]
sure @mik-laj create issues for both the points mentioned will look into it. Could you pls change the assignee for the to me?

**Comment by mik-laj** [comment]
@chattarajoy I assigned you to these tickets.
