### ISSUE TITLE
Consider renaming master branch to something less offensive

### ISSUE THREAD

**Issue by ad-m** [apache/airflow#9351]
As a long-time lover of project collaborators, I would like to propose...

Master is not a good term for the main branch, I'd say its high time to consider renaming this to something like main or edge.

According Apache CoC: 

> Whether we are participating as professionals or volunteers, we value professionalism in all interactions, and take responsibility for our own speech. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behaviour are not acceptable.

Edit: I don't know how to update labels as feature request.

**Comment by turbaszek** [comment]
@ad-m I agree with this proposal. Personally I would opt for `develop` or `main`.

**Comment by turbaszek** [comment]
@ashb @aijamalnk @leahecole @potiuk @kaxil @mik-laj

**Comment by feluelle** [comment]
`develop` 👍

**Comment by ashb** [comment]
`main` seems to be GitHubs new default

**Comment by turbaszek** [comment]
> `main` seems to be GitHubs new default

That's true, however, I would say that in our case the `develop` sounds like a better approach as we have "version-branches".

**Comment by potiuk** [comment]
devel or develop gets my vote as well

**Comment by leahecole** [comment]
develop or main seem great to me, and if develop makes more sense with Airflow, seems like a great idea to me :)

**Comment by turbaszek** [comment]
@ashb @potiuk who can make the change?

**Comment by mik-laj** [comment]
@turbaszek This can be more problematic than we expected. See: https://apache-airflow.slack.com/archives/CCPRP7943/p1592582878155700

**Comment by turbaszek** [comment]
Oh I have missed it, thanks @mik-laj ! Btw. having github issues now, shouldn't we encourage discussion here instead of slack (especially if ticket exists) ?

**Comment by potiuk** [comment]
Indeed we have a super-easy way to build documentation - simply run './breeze build-documentation' and all should happen automatically. I would love to hear what problems you experience with it.

**Comment by ad-m** [comment]
@turbaszek , yes, according to Apache CoC:

> Be open. We invite anyone to participate in our community. **We preferably use public methods of communication for project-related messages, unless discussing something sensitive.** This applies to messages for help or project-related support, too; not only is a public support request much more likely to result in an answer to a question, it also makes sure that any inadvertent mistakes made by people answering will be more easily detected and corrected.

(own bold - pogrubienie własne)

**Comment by kaxil** [comment]
We need to be extra cautious and think this through and maybe first try any automation we think of on a dummy repo.

**Comment by potiuk** [comment]
Agree. While I am all for changing - I think we can wreak havoc by haste changes here. 

An Idea: Why don't we continue working on 2.0 in master and once we start 2.1 work we can create "development" branch and rather than switching to master immediately we will simply ask everyone to move their PR to "development" for their PRs if they want to get it merged. This way we can do it gradually and naturally.

**Comment by ashb** [comment]
Oh ace - If you delete a branch after merging it, GitHub no longer closes PRs that were based on that branch. This helps with renaming 'master', but also helps generally with PRs that are branches of branches. https://github.blog/changelog/2020-05-19-pull-request-retargeting/

**Comment by turbaszek** [comment]
https://github.com/github/renaming

**Comment by potiuk** [comment]
Yep. GitHub suggest to wait a bit as they are working on support to
seamlessly change the branch name.

I think considering the impact it might have on our opened PRs I think it
is a wise thing to wait until this support is ready (even though I'd love
to change it now).

J.

wt., 21 lip 2020, 10:28 użytkownik Tomek Urbaszek <notifications@github.com>
napisał:

**Comment by ashb** [comment]
Yes to this! And I'm starting to work on it now. I'm going to close this issue for #12982 which has a concrete plan.
