### ISSUE TITLE
Extend Default Sensitive Variable Fields

### ISSUE THREAD

**Issue by Marloxo** [apache/airflow#9372]
**Description**

Sensitive variable fields list [here](https://github.com/apache/airflow/blob/master/airflow/www/utils.py#L42) could be extended to be more flexible to include more options.

**Use case / motivation**

It would be better and more extendable if we can use:
- `token` instead of `access_token`
- `key` instead of `api_key` and `apikey `

```PYTHON
DEFAULT_SENSITIVE_VARIABLE_FIELDS = (
    'password',
    'secret',
    'passwd',
    'authorization',
    'api_key',
    'apikey',
    'access_token',
)
```
that would give users more freedom in naming their variables
in my case we have some variables named:
ex:
- `TRELLO_KEY`
- `TRELLO_TOKEN`

**Comment by mik-laj** [comment]
It will not be difficult to add support for additional labels from the configuration. Would you like to contribute?
Before you contribute, you should read
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

**Comment by Marloxo** [comment]
yeah sure, I will send a PR in awhile 👍

**Comment by Marloxo** [comment]
Closing this issue since it's already fixed with this PR https://github.com/apache/airflow/pull/9397
