### ISSUE TITLE
path to file as sql parameter in PostgresOperator not working anymore

### ISSUE THREAD

**Issue by uncletoxa** [apache/airflow#9373]
**Apache Airflow version**: 1.10.10

**What happened**:

```python
maintenance_operator = PostgresOperator(
        task_id='get_tables_size',
        postgres_conn_id='pentaho',
        sql='./dags/maintenance/queries/get_tables_size.sql')
```
brings an error
`jinja2.exceptions.TemplateNotFound: ./dags/maintenance/queries/get_tables_size.sql`

**What you expected to happen**:

PostgresOperator not parsing path to file. Instead tries to evaluate path string as sql query string.
The only way to make it work now:

```python
maintenance_operator = PostgresOperator(
        task_id='get_tables_size',
        postgres_conn_id='pentaho',
        sql=open(
            './dags/pentaho_maintenance/queries/get_tables_size.sql')
            .read())
```

**Anything else we need to know**:

Properly worked on airflow 1.10.2

**Comment by kaxil** [comment]
can you try with the following:

```
maintenance_operator = PostgresOperator(
        task_id='get_tables_size',
        postgres_conn_id='pentaho',
        sql='maintenance/queries/get_tables_size.sql')
```

**Comment by ToxaZ** [comment]
Tried, doesn't work.
Even absolute path gives an error:

```jinja2.exceptions.TemplateNotFound: /home/toxaz/work//pentaho_maintenance/queries/get_tables_size.sql```

**Comment by eladkal** [comment]
I'm unable to reproduce.

```
with DAG(
    dag_id="testing_postgres",
    default_args=default_args,
    schedule_interval=None
) as dag:

    t3 = PostgresOperator(
        task_id='get_tables_size',
        postgres_conn_id='postgres_new',
        sql='maintenance/queries/my.sql'
    )
```

![Screen Shot 2021-02-25 at 23 05 05](https://user-images.githubusercontent.com/45845474/109216999-ecc83480-77bd-11eb-84a4-0a0cc6fe5413.png)

**Comment by ToxaZ** [comment]
@eladkal which version you have tested? I'm still getting an error on 1.10.10, 1.10.12, 1.10.14

**Comment by eladkal** [comment]
1.10.14

Where is your dag file located?
Could it be that the sql file path isn't relative to the dag file? (if so did you define `template_searchpath` ?)
