### ISSUE TITLE
Move task handlers to airflow.providers package

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9386]
Hello,

We have the airflow.providers package, which should contain items specific to specific sevices/software. We should move the handlers to this package. I don't have an idea for the specific structure of the package yet, so I'm open to suggestions.

We have the following files left to move.

- [ ] airflow/utils/log/wasb_task_handler.py
- [ ] airflow/utils/log/cloudwatch_task_handler.py
- [ ] airflow/utils/log/gcs_task_handler.py
- [ ] airflow/utils/log/es_task_handler.py
- [ ] airflow/utils/log/stackdriver_task_handler.py
- [ ] airflow/utils/log/s3_task_handler.py

Each move should be moved out in a backward-compatible manner. We should add a note in UPDATING.md also.

Cheers

**Comment by ephraimbuddy** [comment]
Hi, can I work on these while I await your reviews on the other PRs? It seems easy, thanks.

**Comment by mik-laj** [comment]
Yes. Go ahead and work.
