### ISSUE TITLE
Use enum for task_states/dag_states

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9387]
Hello,

We use Python 3+, so we should consider using an enumerated type for objects that are buckets for contents  This will give us better type hints.
https://github.com/apache/airflow/blob/master/airflow/utils/state.py

Best regards,
Kamil Breguła

**Comment by mik-laj** [comment]
CC: @turbaszek

**Comment by muyajil** [comment]
Hi,
I'd like to help out with this issue.

**Comment by turbaszek** [comment]
@muyajil should I assign you?

**Comment by mik-laj** [comment]
@muyajil I assigned you to this ticket. I look forward to your contributions 😻

@turbaszek I think we can assign people without confirmation. The assignment of people is important because it is visible on the ticket list. This makes finding free tickets easier.

**Comment by chutcheson** [comment]
Is this still an open issue?

**Comment by muyajil** [comment]
@chutcheson Yes it is, unfortunately I never got the chance to really get started

**Comment by andrewgodwin** [comment]
I'll take this up, if someone wants to assign me.

**Comment by andrewgodwin** [comment]
I would like to ask, though - do we just want the type hinting here (in which case we can just declare a nice Literal type for the state tuples), or take on the problems that changing a tuple to an enum will cause? There's a few places in Airflow, and presumably in some third-party code, that presume they can do operations on `State.task_states` as if it were a sliceable/iterable.

**Comment by uranusjr** [comment]
I briefly read related source, and it seems to me the main advantage would be to make sure the right values are passed the right value to SQLAlchemy, so `Literal` feels like a better solution.

**Comment by andrewgodwin** [comment]
Yeah, after having done some exploratory coding here, it's basically going to require a big separate Literal type that probably duplicates a lot of the values. I'll draw it up, but we can see if it's worth it in the PR discussion.
