### ISSUE TITLE
SSL Issue on K8S with SlackWebhookOperator

### ISSUE THREAD

**Issue by benbenbang** [apache/airflow#9407]
Recently our team is testing all the dags to check everything will work fine on airflow on k8s. However, one of the issues we didn't have before is that the SSL issue happens in the POD. The only solution for us to fix it is to turn on `verify=True` for all the HTTP related hook. But except SlackWebhookOperator, it was hardcoded with proxy and cannot take any extra option.

https://airflow.apache.org/docs/stable/_modules/airflow/contrib/hooks/slack_webhook_hook.html

If there's no PR for this, I would like to open a PR to do a quick enhancement on this operator. Advice and any other comments are all welcome. Thanks in advance.

**Comment by mik-laj** [comment]
Hello, 

Any contribution is greatly appreciated.

If you do not feel confident in OSS, then I invite you to read the guide.
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

Cheers

**Comment by benbenbang** [comment]
Thanks, PR created :) 

https://github.com/apache/airflow/pull/9409
