### ISSUE TITLE
Support airflowignore for plugins

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9413]
Hello,

Airflow has a mechanism to ignore files before they are automatically loaded by Airflow using a .airflowignore file.
A .airflowignore file specifies the directories or files in DAG_FOLDER that Airflow should intentionally ignore.

> For example, you can prepare a .airflowignore file with contents
> ```
> project_a
> tenant_[\d]
> ```
> Then files like project_a_dag_1.py, TESTING_project_a.py, tenant_1.py, project_a/dag_1.py, and tenant_1/dag_1.py in your DAG_FOLDER would be ignored (If a directory’s name matches any of the patterns, this directory and all its subfolders would not be scanned by Airflow at all. This improves efficiency of DAG finding).

More information: https://airflow.readthedocs.io/en/latest/concepts.html?highlight=airflowignore

It would be helpful to make a similar feature available to plugins. This improves the efficiency of plugins finding. 

If anyone is interested in this, I am willing to provide all the necessary tips and information.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Cheers

**Comment by j-y-matsubara** [comment]
@mik-laj 
I am interested in this task. Would you mind if I do it?

I plan to add code of "Ignore"  to  : 
https://github.com/apache/airflow/blob/c703ce20c836e9f797203ed233fe6e3d51d8cbd4/airflow/plugins_manager.py#L159-L162

**Comment by mik-laj** [comment]
@j-y-matsubara  This seems like a good place. I assigned you to this ticket. :-)

**Comment by j-y-matsubara** [comment]
I'm sorry.  I had failed to link to pull reqest.
This issue have already fixed.

**Comment by turbaszek** [comment]
Closed in #9531
