### ISSUE TITLE
Environment variables reference

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9414]
Hello,

I think it's worth creating a list of environment variables used by Airflow. This will allow you to refer to it from other places in the documentation.  We should use [envvar directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html?highlight=envvar#directive-envvar) in this docs.

This list can be added to the file:  [docs/cli-ref.rst](https://github.com/apache/airflow/blob/master/docs/cli-ref.rst) ([preview](https://airflow.readthedocs.io/en/latest/cli-ref.html))

We have the following environment variables
```
.. envvar:: AIRFLOW__{SECTION}__{KEY}
.. envvar:: AIRFLOW__{SECTION}__{KEY}_CMD
.. envvar:: AIRFLOW_CONFIG
.. envvar:: AIRFLOW_CONN_{CONN_ID}
.. envvar:: AIRFLOW_HOME
.. envvar:: AIRFLOW_VAR_{KEY}
```

We can be inspired by the following links
https://docs.docker.com/compose/reference/envvars/
https://raw.githubusercontent.com/python/cpython/7864f11cdf12807555d62c7a132c191eb41ecc02/Doc/using/cmdline.rst
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

If anyone is interested in this, I am willing to provide all the necessary tips and information.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

**Comment by jkrajpal** [comment]
@mik-laj please assign this to me.

**Comment by turbaszek** [comment]
@jkrajpal I assigned you 🚀 @mik-laj I suppose we would like to use the config.yml to generate the envvar reference?

**Comment by mik-laj** [comment]
@turbaszek  Why would I do that? I would like to have a list of only 6 options. In case of ``AIRFLOW__{SECTION}__{KEY}``. I would like a description that is related to the configuration options and a link to the documentation with all configuration options.

**Comment by mik-laj** [comment]
@ghost Do you have any problem? Do you have any questions? I will be very happy to help you if I can

**Comment by mik-laj** [comment]
The user who wanted to do this task deleted the account, so this ticket is now free.

**Comment by faihegberg** [comment]
@mik-laj I’d like to grab this one if that’s ok 🙂 I just finished reading through the contribution guideline/documentation and this will be my first issue. Please let me know if you have any additional info that you think will be helpful.

**Comment by mik-laj** [comment]
@faihegberg You are already assigned to this ticket. When you create a PR it will be easier for us to discuss the details.

**Comment by gflores1023** [comment]
Hi, came across this issue. There's now a broken link on [dag-run](https://airflow.readthedocs.io/en/latest/dag-run.html?highlight=catchup#backfill) - the link that points to: https://airflow.readthedocs.io/en/latest/cli-ref.html#backfill

"The **[backfill command](https://airflow.readthedocs.io/en/latest/cli-ref.html#backfill)** will re-run all the instances of the dag_id for all the intervals within the start date and end date."

I noticed faihegberg added a redirect but it doesn't appear to be working?

**Comment by mik-laj** [comment]
@gflores1023 If you want to propose a design change then you don't have a ticket. It is enough to create a PR.
