### ISSUE TITLE
[AIP-31] Update DAG examples to use Functional DAG style

### ISSUE THREAD

**Issue by casassg** [apache/airflow#9415]
**Description**

- Update Airflow documentation to use functional style DAGs instead. 
- Update Airflow tutorials documentation
- Update information about XCom and `.output` attribute

**Use case / motivation**

As discussed in https://github.com/apache/airflow/pull/8962#discussion_r442706891 we believe that functional DAG definition may be easier to onboard and easier to abstract underlying Airflow mechanisms.

**Related Issues**

Created from #8962

**Comment by turbaszek** [comment]
+ should we update the information about XComs and the `.output` attribute?

**Comment by josh-fell** [comment]
@turbaszek @eladkal Is this enhancement still needed?  Since I'm working on #10285, might be worthwhile to tackle together as they seem implicitly related.  Happy to contribute here as well.

**Comment by eladkal** [comment]
@josh-fell assigned to you

**Comment by josh-fell** [comment]
FYI - I have a number of PRs opened to handle #10285 which updated 86 files. I will wait on reviews and merges of those before moving to this issue to minimize merge collisions and such + make the changes more manageable. I haven't forgotten about this 😄

**Comment by josh-fell** [comment]
FYI - Just waiting on 1 PR to get merged for core example DAG updates then I'll be good to go taking this on shortly thereafter.

**Comment by josh-fell** [comment]
Last PR merged. I'll start working on this now. Thanks for your patience @eladkal

**Comment by josh-fell** [comment]
In other PRs there was discussion of removing `PythonOperator` use in the example DAGs but I'm wondering what everyone's thoughts are on handling imported functions that are called in the DAG. Should we keep the `PythonOperator` use in these cases or show a syntax-sugar version like `op = task(imported_function)(func_args)`?

For example, in the core [example_kubernetes_executor](https://github.com/apache/airflow/blob/3ddb389882128fe76941c8995a68629d8f2b324f/airflow/example_dags/example_kubernetes_executor.py) DAG:
```python
from airflow.example_dags.libs.helper import print_stuff
...
start_task = PythonOperator(task_id="start_task", python_callable=print_stuff)
```
Obviously we could always remove the reference to this function and add it directly to the DAG but there definitely use cases where folks are importing centralized, business-logic functions into DAGs but don't want to add Airflow-specific language to the functions themselves (i.e. decorating the function with `@task`).

@ephraimbuddy Curious on your opinion here too.

**Comment by ephraimbuddy** [comment]
What do you think about this? I feel it's good: 

```python
from airflow.example_dags.libs.helper import print_stuff

@task
def start_task():
    print_stuff()
```

**Comment by josh-fell** [comment]
> What do you think about this? I feel it's good:
> 
> ```python
> from airflow.example_dags.libs.helper import print_stuff
> 
> @task
> def start_task():
>     print_stuff()
> ```

Well, I completely missed the obvious answer; it's been a long day. Love it.
