### ISSUE TITLE
YAML file format in LocalFilesystemBackend

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9417]
Hello,

I would be happy if LocalFilesystemBackend would support YAML files. This file format is easier for human editing than JSON files, so it would be easier for developers to use.

Tasks to do

- [ ] 1. Define the file format (based on the current JSON format)
- [ ] 2. Add support for YAML files
- [ ] 3. Add tests
- [ ] 4. Upddate docs

Steps 2 and 3 can be swapped if [TDD](https://en.wikipedia.org/wiki/Test-driven_development) methodology will be used. It will be easy here, so it will be an good exercise.

If anyone is interested in this, I am willing to provide all the necessary tips and information.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Cheers

**Comment by VinayGb665** [comment]
I would like to pick this up

**Comment by mik-laj** [comment]
@VinayGb665 I assigned you to this ticket.  I look forward to your contributions. 🐈

**Comment by mik-laj** [comment]
@ VinayGb665 Yes. It may be based on this, but if you have your idea then you can present it in your change.
