### ISSUE TITLE
Add note about secret backend in security.rst

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9420]
Hello,

A small note would be useful. Now we only have information about Fernet on this page.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards,
Kamil

CC: @kaxil

**Comment by mik-laj** [comment]
@kaxil Are you planning to continue working on the ticket or can another person start working on it? This is a "good-first-issue", so I'd be happy if new contributors could work on it.

**Comment by kaxil** [comment]
Un-assigned myself, will let the new contributors work on this one

**Comment by mik-laj** [comment]
Done via: https://github.com/apache/airflow/pull/10352
