### ISSUE TITLE
Airflow support for S3 compatible storages

### ISSUE THREAD

**Issue by vaddisrinivas** [apache/airflow#9474]
Hi,

Curious to know about the support for S3 compatible storages like DELL ECS, MINIO ETC

Thanks

**Comment by dimon222** [comment]
Yes, it works as long as you specify endpoint url. However, it seems to be broken to serving logs in UI for some users on latest release 1.10.10 (works fine in 1.10.9)

**Comment by vaddisrinivas** [comment]
It doesnt work for me even as I continue to provide HOST in the connection and also other relevant parameters.
If there is any alternative for the same, please help with that.

Thanks.

**Comment by dispensable** [comment]
We are currently using Minio as our airflow cluster logging backend. It works perfect. But setting the connection is a little bit tricky U should not set host in the host form field otherwise set host in the `Extra` fields with `{"host": "http://YOUR_S3_URL:PORT"}`, just leave the `host`/`port`/`schema` form fields blank.

**Comment by vaddisrinivas** [comment]
hi @dispensable , will try this and update the ticket asap!

**Comment by vaddisrinivas** [comment]
hi @dispensable / all, 

How do I pass the access_key_id and other parameters to connect to that? can someone please help on that?

**Comment by dimon222** [comment]
> hi @dispensable / all,
> 
> How do I pass the access_key_id and other parameters to connect to that? can someone please help on that?

Username/Password fields in respective connection

**Comment by vaddisrinivas** [comment]
hi @dispensable/@dimon222, thanks for your help.

I have SUCCESSFULLY enabled pushing airflow logs to s3 compatible bucket by following what was mentioned above,
in brief : 

- created a new connection with -> {"host": "http://myhost:myport",   "aws_access_key_id" :"myaccesskey/username"
        ,"aws_secret_access_key": "myreallybigsecretkey"} 

- then I went ahead, modified the configuration by adding 
  AIRFLOW__CORE__REMOTE_LOGGING: True,
  AIRFLOW__CORE__REMOTE_LOG_CONN_ID: connectionthatwassetearlier,
  AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://bucketname/pathorfolderonBucket",

- restarted Airflow!

**Comment by Asgoret** [comment]
Everywhere is HTTP, but what about HTTPS? airflow doesn't support HTTPS S3 endpoints? I've got a very odd error (`An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records`) when use HTTPS-based endpoint. In dev with HTTP, all works perfectly.
cc @dimon222
