### ISSUE TITLE
Unwanted backfill when using empty database even with catchup set to false

### ISSUE THREAD

**Issue by CodingJonas** [apache/airflow#9485]
**Apache Airflow version**:v1.10

**Environment**: Deployed inside a Docker container

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.4
- **Install tools**: pipenv

**What happened**:
I have a DAG with start date of 1/1/2018 and schedule to run through a cron expression (e.g. every 2 hours). This is the first time I start Airflow with a new database. No DAG has ever run before. As soon as I unpause my DAG, the scheduler will start running one DAG. I set `catchup=False` to stop this behaviour from happening, yet it still schedules exactly one DAG for backfill.
If there was a previous DAG run this behaviour does not happen.

I found a [reference to this issue](https://stackoverflow.com/questions/52177418/how-to-stop-dag-from-backfilling-catchup-by-default-false-and-catchup-false-doe#comment92792366_52922501) already from 2018, which describes a very similar problem, but I couldn't find an open issue to this.

**What you expected to happen**:
If I set `catchup=False`, I expect no backfill to happen.

**How to reproduce it**:
These are the DAG settings I use:
```python
dag_params = dict(
    dag_id='test',
    schedule_interval='0 */2 * * *',
    start_date=datetime(2018, 1, 1),
    max_active_runs=1,
    catchup=False,
)
```

**Comment**:
I read somewhere that setting a future `start_date` could help, I tried it with `datetime(3018, 1, 1)`, which got rid of the unwanted backfill, but no DAGs got executed. More interestingly it started a DAG and instantly set it to 'success´ without running a single task. But I think this is unrelated to this issue.

**Comment by gflores1023** [comment]
There was recently a bugfix involving catchup=False. Not sure if related, but you can try using the latest Airflow version 1.10.11 to see if the issue persists. 

https://github.com/apache/airflow/pull/8776

**Comment by eladkal** [comment]
You mention 2 issues:
1. Why a single run is created when you use catchup=False.
2. Why this single run is marked as success without running anything.

For the **1st** question:
This is by design.
Kaxil explained it in the first paragraph of his answer to the stackoverflow question you mentioned in your question.

For the **2nd** question:
I'm unable to reproduce such behavior. Please provide a reproduce example.
