### ISSUE TITLE
Unable to retrieve logs after Out Of Memory Error

### ISSUE THREAD

**Issue by WesleyBatista** [apache/airflow#9490]
**Apache Airflow version**: 1.10.10

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux 9 (stretch)`
- **Kernel** (e.g. `uname -a`): `Linux <redacted> 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

**What happened**:

A task got executed and failed, but the execution logs are inaccessible from the UI.

![image](https://user-images.githubusercontent.com/755254/85449070-9f912480-b597-11ea-9f6e-9ebf2ede720a.png)

```
$ cat /var/log/airflow/<dag_id>/<task_id>/2020-06-15T01\:23\:00+00\:00/1.log
... <application logs here. no raised exceptions>
[2020-06-22 20:15:35,141] {logging_mixin.py:112} INFO - [2020-06-22 20:15:35,091] {local_task_job.py:103} INFO - Task exited with return code -9
```

**What you expected to happen**:

Execution logs should be available on the UI.

**How to reproduce it**:

In our case it was an [OOM error](https://stackoverflow.com/a/18529453), but maybe any unhandled error can be used to reproduce a crash, or perhaps even issuing a `kill -9` on the process running the task could reproduce the issue.

**Anything else we need to know**:

1. I found this issue that helped me to understand the error: https://issues.apache.org/jira/browse/AIRFLOW-4922 

2. Our current setup:
    - **machine1** running `airflow-webserver`, `airflow-scheduler`, `airflow-worker`
    - **machine2**  running `airflow-worker`
    
    The task is set to be executed on **machine2**
3. These are the task instances currently on the airflow metadata database:
    ![bug-no-logs-airflow](https://user-images.githubusercontent.com/755254/85451797-876ed480-b59a-11ea-8feb-d38204a4135b.png)
    
    We can see in the image that the one which took the most duration time and eventually got killed by OOM is also the one without a `hostname` set.

**Comment by samgans** [comment]
I've stumbled upon the same issue. Can someone who has such information to tell more about why the UI actually can't retrieve the hostname from the task instance?

**Comment by WesleyBatista** [comment]
another characteristic of this bug: the logs are available while the task is running, but disappear when the task fail.

still present on v2.0.2, which now outputs the error name instead of the code:

```
[2021-09-02 11:18:06,592] {local_task_job.py:146} INFO - Task exited with return code Negsignal.SIGKILL
```

**Comment by eladkal** [comment]
Does it still happen on latest airflow version?

**Comment by AmeyKu1Karni** [comment]
I am using Airflow Version 3.0.0. When I click on logs in the Airflow UI (running on localhost:8080) for a task, the page loads into "Aw snap, not enough memory" error in Chrome.
