### ISSUE TITLE
Remove adding Operators via plugins in 2.0

### ISSUE THREAD

**Issue by ashb** [apache/airflow#9498]
In Airflow 2.0 we should remove the ability to add operators and hooks via plugins. 

I think we should deprecate adding Operators and Hooks via the Airflow plugin mechanism.

I think plugins should be reserved for any mechanism that a plain-ol python module import won't work for (which is basically anything that needs to tie deeply in to the Webserver or Scheduler process).

To that end I think we should deprecate adding operators via plugins:

```python
    from airflow.operators.my_plugin import MyOperator
```

can become

```python
    from my_plugin import MyOperator
```

with no impact on functionality.

For this not to be a hard/sudden breaking change we should issue a deprecation warning for this in 1.10.12 - https://github.com/apache/airflow/issues/9500

Discussed here:

https://lists.apache.org/thread.html/a1453d6a6f113709386b61c68c3f5cd61b258fe78f07811169500fe3%40%3Cdev.airflow.apache.org%3E

**Comment by mik-laj** [comment]
First of all, we should prepare documentation that describes how loading operators works to increase awareness of the problem. Many people use plugins because they know no other alternative.
https://github.com/apache/airflow/issues/8715

**Comment by ashb** [comment]
Good call. We can adopt something from https://www.astronomer.io/guides/airflow-importing-custom-hooks-operators/

**Comment by kaxil** [comment]
Docs have been added about Import Mechanism: https://github.com/apache/airflow/pull/10303

https://airflow.readthedocs.io/en/latest/modules_management.html
