### ISSUE TITLE
Using templates in PythonOperator

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#95]
Sorry for a trivial question, I've been trawling thru the code but cant seem to get templating to work within PythonOperators.

I've been using the templating features of the PostgresOperator to read an external sql file and template some of the logic. I'd like to do similar using a PythonOperator, specifically:
- Call a python function supplying a dict (via a PythonOperator)
- The python function should load a template and render it using the supplied dict as variables.

Is this possible? I've been fiddling trying to supply a `template_fields` value to my function hoping it will magically work.

**Comment by mistercrunch** [comment]
Check out the `provide_context` flag in the PythonOperator documentation.
http://pythonhosted.org/airflow/code.html#airflow.operators.PythonOperator

The idea is that when your flip that to `True`, I pass the whole context to the call as kwargs. The context is basically everything defined here:
http://pythonhosted.org/airflow/code.html#macros

```
def foo(my_param, ds, task, *args, **kwargs):
    print(my_param) # that's your param, you can have as many as you want
    print(ds) # this comes from the context
    print task.task_id # task is a reference to the task object, coming from the context
    print(kwargs.keys()) # shows all the keys in the context not explicitly defined in the function header
```

I think @artwr has a PythonScriptOperator that would receive text or a `.py` file as an input, but it's not in the repo. I prefer the `PythonOperator` approach, I think it makes the code more dynamic and cleaner.

**Comment by martingrayson** [comment]
What I'm actually trying to do is template SQL and do some interaction with a db within a PythonOperator - I'm not actually reading/templating `.py` files.

I'm trying to pass the `.sql` template to my PythonOperator and use the rendered version within my operators function (calling out to a postgres hook infact). Is that possible?

**Comment by mistercrunch** [comment]
Oh interesting. You may be able to call the task's render_template method from your `python_callable`.
https://github.com/airbnb/airflow/blob/master/airflow/models.py#L1156

```
def foo(*args, **kwargs):
    task = kwargs['task']
    sql  "TEST: {{ ds }}"
    logging.info(task.render_template(sql, kwargs))
```

**Comment by martingrayson** [comment]
Awesome! Thank you, I'll test this in the morning :+1:

**Comment by martingrayson** [comment]
I've got it working using your example, but it feels dirty how I'm setting the `template_ext` value.

Could this be done better?

```
def check_function(ds, **kwargs):
    task = kwargs['task']
    task.__class__.template_ext = ('.sql',)
    rendered_sql = task.render_template(kwargs['sql_template'], kwargs)

    redshift_hook = PostgresHook(postgres_conn_id=kwargs['redshift_connection_id'])
    rec_set = redshift_hook.get_records(rendered_sql)
    # Do some stuff with the record set here.
    logging.info(rec_set)

check_task = PythonOperator(
    task_id='check_task',
    python_callable=check_function,
    provide_context=True,
    params=schema_mapping,
    op_kwargs={'sql_template': 'my_templated_sql.sql',
               'redshift_connection_id': 'redshift_analytics'},
    dag=dag)
```

Incase you cant tell, Python isn't my most comfortable language...

**Comment by mistercrunch** [comment]
I'm surprised this actually works. You could alter your function to expect sql (templated) as a `str` instead of the sql file location. This would avoid you relying on jinja/airflow internal magic to resolve the file's content. So a good old `open()` there making sure you use a relative path to `__file__` allows you to get rid of the `task.__class__.template_ext` affectation.

Now I'd be careful in your function header of defining `ds` or anything else out of the airflow context because it will strip it out of `kwargs` as kwargs is the placeholder for all non-defined keyword args. Then `ds` doesn't make it through in the `render_template` call. So I'd remove `ds` from the header and get it out of `kwargs` (like `task`). `sql_template` though isn't part of the airflow context, so that one you can have in the header.
