### ISSUE TITLE
Add EMR Operators and AWS Lambda Operators

### ISSUE THREAD

**Issue by r39132** [apache/airflow#950]
This is more a note-to-self than anything, but we have started using Airflow DAGs to spin up EMR, execute steps, and then spin down the EMR cluster. We currently do this via the existing BashOperator and AWS CLI. We are looking into making this a specific operator to make it more reusable for the community.

We are also starting to look at Lambda, so we are considering building operators for both!

**Comment by r39132** [comment]
Closing for now until I have a more concise definition of the work.

**Comment by lucasc896** [comment]
👍  This would definitely be of interest to us too

**Comment by tomerf8** [comment]
+1
