### ISSUE TITLE
Docker operator command

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#9518]
Hi, when I am using command as a one element list it generated unhandled, strange error. Docs don't say, that list can not consist only one element.  I've strugled two days until I resolve it. Can it be fixed?

**Comment by nullhack** [comment]
Hi @gardner-dev Thank you for opening this report. Can you give some details? 
Like, What is the strange error you mentioned? How have you solved It? Can you provide a simple example of DAG which can reproduce the issue? Which version of airflow are you using?

**Comment by gardner-dev** [comment]
Sure @nullhack! In the documentation regarding docker operaort we can read
```
command (str or list) – Command to be run in the container. (templated)
```
When I run docker operator with command such as:
`command=["python owid_API.py -date {{ ds }}"]`
it generates error

> docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"python owid_API.py -date 2020-03-14\": executable file not found in $PATH": unknown")

The clear problem is that list is one-element list. But it should be specified in docs that list doesn't work for one command

**Comment by mik-laj** [comment]
You should use 
```
command="python owid_API.py -date {{ ds }}"
```
or
```
command=["python", "owid_API.py", "-date", "{{ ds }}"]
```
I don't know what we could do to prevent a similar problem in the future.

A similar problem will occur in CLI if you provide an invalid value.
```
docker run -ti --rm openjdk:8-jre-slim 'bash -c "echo 1"'
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash -c \\\"echo 1\\\"\": executable file not found in $PATH": unknown.
```
We may require this argument to be a list, but it is a breaking change. And this breaks one special feature of this operator.
You can put an array into XCOM and as an argument.
For xcom = `["bash", "-c", "echo 123"]`
and 
```
command="{{ task_instance.xcom_pull("create_dataset_task", key="dataset_id") }}"
```
it will run `bash -c 'echo 123'`. Please note that the number of array elements can be dynamic.

**Comment by mik-laj** [comment]
> Docs don't say, that list can not consist only one element

It can be only one element, but it should be an executable file.
```
command=["./my-awesome-script.sh"]
```

**Comment by gardner-dev** [comment]
Thank you @mik-laj , issue could be closed then
