### ISSUE TITLE
remove duplicate parameters from `sql_to_gcs.py`

### ISSUE THREAD

**Issue by Marloxo** [apache/airflow#9526]
**Apache Airflow version**:
1.10.10

**Environment**:
Docker

**What happened**:

it's just small nitpick, we have this redundant line which assign the `parameters` twice in `sql_to_gcs` 

https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/transfers/sql_to_gcs.py#L115:L118

```python
        self.parameters = parameters
        self.gcp_conn_id = gcp_conn_id
        self.delegate_to = delegate_to
        self.parameters = parameters
```

**Comment by kaxil** [comment]
Fixed by https://github.com/apache/airflow/pull/9527
