### ISSUE TITLE
Official Airflow Helm Chart DAG sync support

### ISSUE THREAD

**Issue by jacobhjkim** [apache/airflow#9528]
**Description**

Use [git-sync](https://github.com/kubernetes/git-sync) to update Airflow DAGs when using the official [Airflow Helm Chart](https://github.com/apache/airflow/tree/master/chart).

**Use case / motivation**

Currently, if you use the official [Airflow Helm Chart](https://github.com/apache/airflow/tree/master/chart) the only way to update DAGs is to build a new Airflow image. Building a new Airflow Image and deploying every time when there is a change in DAG seems like overkill. So I propose updating DAGs by using [git-sync](https://github.com/kubernetes/git-sync)
>git-sync is a simple command that pulls a git repository into a local directory. It is a perfect "sidecar" container in Kubernetes - it can periodically pull files down from a repository so that an application can consume them.

**Comment by jacobhjkim** [comment]
Seems like https://github.com/apache/airflow/pull/9371 is already working on it.

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/9371
