### ISSUE TITLE
Can't log out of Airflow

### ISSUE THREAD

**Issue by criccomini** [apache/airflow#953]
Airflow has no 'logout' button (that I can see). When using a secure backend (e.g. LDAP), there's no way to log out (other than manually deleting the session cookie from the browser). It would be nice to add a logout button.

**Comment by mistercrunch** [comment]
There's an endpoint though, so it should be trivial to add a button.

**Comment by criccomini** [comment]
Working on this here:

https://github.com/airbnb/airflow/pull/987

**Comment by criccomini** [comment]
Closing. PR was committed.
