### ISSUE TITLE
raise AirflowException("SSH operator error: {0}".format(str(e)))

### ISSUE THREAD

**Issue by miamiajin** [apache/airflow#9539]
[airflow ssh operator error.log](https://github.com/apache/airflow/files/4838542/airflow.ssh.operator.error.log)

**Apache Airflow version**: 1.10.3

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: python3.5

**What happened**:

The airflow DAG run smoothly for the first 2 weeks. Then the error occured. There is no more error information in the log except for "raise AirflowException("SSH operator error: {0}".format(str(e)))". The DAG ran successfully after rerunning it. In this DAG, 5 SSHOperator run parallel. I checked the ram and cpu usage. All looks fine. The whole log file is attached above.

**What you expected to happen**:

Don't fail anymore.

**How to reproduce it**:

No idea how to reprodice it. It fails randomly.

**Comment by potiuk** [comment]
Github issues are not ment for troubleshooting (see the templates we have) instead, please discuss your problem on slack/#troubleshooting  channel. You will get all the information how to get there in "Ask a question"  section of  https://airflow.apache.org/community/
