### ISSUE TITLE
Option for DAG to be instantiated in 'off' mode.

### ISSUE THREAD

**Issue by nicktrav** [apache/airflow#954]
Often when testing a new DAG, it is preferable to be able to deploy the new DAG as disabled or 'off' initially. After checking that the settings / templates look good, the DAG can then be enabled.

The option to make this a global default (i.e. for all DAGs), as well as for selected DAGs would be convenient.

cc: @r39132

**Comment by r39132** [comment]
Here you go : https://github.com/airbnb/airflow/pull/956
