### ISSUE TITLE
GoogleCampaignManagerInsertReportOperator Fails when using Templated Reports

### ISSUE THREAD

**Issue by efolgar** [apache/airflow#9541]
The GoogleCampaignManagerInsertReportOperator fails with the following 400 error when attempting to insert a report rendered from a file template:

> HttpError 400 when requesting https://www.googleapis.com/dfareporting/v3.3/userprofiles/*******/reports?alt=json returned "Report type needs to be set."

Appears the issue is that Jinja templates will always render as a String but the operator is expecting a Dictionary (representing the JSON object).

Here's a sample call:
```
GoogleCampaignManagerInsertReportOperator(
        task_id="create_report",
        gcp_conn_id=self.config.get("gcp_connection_id"),
        profile_id=self.config.get("cm_profile_id"),
        report="./resources/reports/cm_report.json",
        params=report_params,
        dag=self.dag)
```

Relevant Code:
https://github.com/apache/airflow/blob/096f5c5cba963b364ee75f6686d128cd4d34d66e/airflow/providers/google/marketing_platform/operators/campaign_manager.py#L287

**Comment by mik-laj** [comment]
A similar problem has already been resolved in airflow.providers.google.cloud.operators.cloud_build.CloudBuildCreateBuildOperator operator.
Here is code for fix:
https://github.com/apache/airflow/blob/c420dbd6e13e17867eb4ccc4271b37966310ac0f/airflow/providers/google/cloud/operators/cloud_build.py#L202-L210

**Comment by turbaszek** [comment]
@mik-laj I was thinking about this over weekend. Shouldn't we add this logic to Airflow core? I would say that we should support at least .json and .yaml WDYT? @kaxil @feluelle
