### ISSUE TITLE
Add support for snowflake on the sql_sensor

### ISSUE THREAD

**Issue by KumarManoj-S** [apache/airflow#9548]
**Description**

Enable the support for Snowflake on the SqlSensor.

**Use case**

Currently, the `SqlSensor` supports only the following connection types,

- google_cloud_platform
- jdbc
- mssql
- mysql
- oracle
- postgres
- presto
- sqlite
- vertica

At the moment, it doesn't have support for Snowflake. This ticket is to add support for Snowflake on the `SqlSensor`.

**Comment by KumarManoj-S** [comment]
Hi, I would like to pick up this issue if it is a good feature to come in.

**Comment by mik-laj** [comment]
@KumarManoj-S I assigned you. to this ticket. This change seems sensible. We should not have lists of approved classes in the code, but we should rely on interfaces.

**Comment by eladkal** [comment]
@KumarManoj-S  note that if this works for SqlSensor there is no reason it won't work for SqlOperators
https://github.com/apache/airflow/blob/1d36b0303b8632fce6de78ca4e782ae26ee06fea/airflow/sensors/sql_sensor.py#L72
https://github.com/apache/airflow/blob/0b9bf4a285a074bbde270839a90fb53c257340be/airflow/operators/sql.py#L26
 (not sure why two different lists are needed as lists are the same and there shouldn't be a reason why sensor would work on specific db but the operators won't or vice versa)
Might worth checking that if you can address both

**Comment by KumarManoj-S** [comment]
@eladkal Sure. That's a good point. I will check if I can address both of them.
