### ISSUE TITLE
Missing operator - CloudVisionReferenceImageCreateOperator

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9558]
Hello,

We miss the operator for method delete_reference_image to hook CloudVisionHook. All other methods probably have matching operators.
This is important to me because the hook method refers to this operator in docstring.
https://github.com/apache/airflow/blob/1d36b0303b8632fce6de78ca4e782ae26ee06fea/airflow/providers/google/cloud/hooks/vision.py#L428

Best regards,
Kamil

**Comment by subkanthi** [comment]
Looks like already implemented. @mik-laj 

`@GoogleBaseHook.fallback_to_default_project_id
    def delete_reference_image(
        self,
        location: str,
        product_id: str,
        reference_image_id: str,
        project_id: str,
        retry: Optional[Retry] = None,
        timeout: Optional[float] = None,
        metadata: Optional[Sequence[Tuple[str, str]]] = None,
    ) -> Dict:`

**Comment by mik-laj** [comment]
@subkanthi  we have method in hook, but we don't have an operator that allows us to easily use this method in DAG.

**Comment by manesioz** [comment]
I'd like to take a stab at it if no one else is working on it.

**Comment by potiuk** [comment]
Go for it @manesioz !
