### ISSUE TITLE
Documentation does not tell what "dry run" does

### ISSUE THREAD

**Issue by michaelosthege** [apache/airflow#9561]
**Description**

The https://airflow.apache.org/docs/stable/cli-ref.html?highlight=backfill#backfill documentation page explains the `--dry-run` command as
> Perform a dry run

Unfortunately that doesn't help if one does not know what is mean by "dry run".

**Use case / motivation**
I'm trying to run trigger a backfill such that the terminal detaches after triggering the command.
Does "dry-run" help with that?

**Comment by kaxil** [comment]
You could run the backfill command and suffix it with `&`  (ampersand) to run it in background
