### ISSUE TITLE
Attach roles to AD groups - Azure OAuth

### ISSUE THREAD

**Issue by sk2991** [apache/airflow#9583]
We have implemented RBAC using Azure OAuth, Is there any way to attach a role to AD group - so that users part of that AD groups/Tenant can get default access to the attached role 

**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.15.10

**Environment**: 

- **Cloud provider or hardware configuration**: Azure (AKS)
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux
- **Kernel** (e.g. `uname -a`): 4.15.0-1089-azure
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

attach a role to AD group (or) Azure tenant

**How to reproduce it**:

Helm install stable/airflow
Implement RBAC using Azure OAuth

**Comment by elwinarens** [comment]
@sk2991  Would you mind sharing your Azure OAuth implementation?

**Comment by rafaelpierre** [comment]
@sk2991 +1

> @sk2991 Would you mind sharing your Azure OAuth implementation?

**Comment by mik-laj** [comment]
Is this helpful for you?  I don't use Azure OAuth, so I'm not sure this change applies here.
https://github.com/dpgaspar/Flask-AppBuilder/pull/1410

**Comment by sk2991** [comment]
@elwinarens @rafaelpierre  - I have used this [link](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/oauth/config.py) to configure Azure OAuth. 
Other useful links:
https://github.com/apache/airflow/pull/3015
https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth

**Comment by sk2991** [comment]
@mik-laj  It does help to some extent. Is there anyway to extend this? Instead of declaring "AUTH_USER_REGISTRATION_ROLE_JMESPATH = "contains(['alice@example.com', 'celine@example.com'], email) && 'Admin' || 'Public'"" this manually in config file - can we assign it dynamically?

**Comment by hussainsaify** [comment]
@sk2991 were you able to solve this using a more cleaner method than shared above?

**Comment by sk2991** [comment]
@hussainsaify I was not able to find any other way.
