### ISSUE TITLE
Bug: @daily schedule with depends_on_past and non-midnight start date will never run

### ISSUE THREAD

**Issue by jlowin** [apache/airflow#959]
Probably a rare case, but one I found myself in because I didn't realize that `@daily` implies midnight, not `date time.timedelta(days=1)`!

If a `@daily` DAG has a `start_date` that isn't midnight, the first `DagRun` will run at the specified time, but the second run will run at midnight. Then any tasks that `depend_on_past` will fail since they will look for the prior midnight run, not the actual `start_date`.

Possible solutions:
- if a DAG doesn't start at midnight, transform cron presets to time delta equivalents (this would protect against the general case of not intending midnight runs ever)
- have `DAG.previous_schedule` return `max(previous_schedule, self.start_date)` (this would protect against just the case I'm describing

**Comment by mistercrunch** [comment]
`@daily`, the other `@` shortcuts and the cron notation subscribe to the standard of having a clear schedule, and `execution_date` that line up. I'd rather phase out the support for time interval support than allowing for it on the cron notation side.

The better way to delay tasks is with data dependencies (sensors!) or a TimeDeltaSensor in the absence of it. 

Changing the schedule, especially while having `depends_on_past=True` will lead to all sorts of confusing clogging. The key is to move the start_date to something on your schedule.

An eventual `DAG.validate` method could check that start_dates fall onto an existing schedule, or something rounded when using timedeltas.
