### ISSUE TITLE
Add unittests for GCSTaskHandler

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#9600]
**Description**

The `GCSTaskHandler` from `airflow.utils.log.gcs_task_handler` does not have a unit test. 

**Use case / motivation**

The test is necessary so that we can be able to move the `GCSTaskHandler` to its providers package(`google`)

**Related Issues**
#9386

**Comment by OmairK** [comment]
Hey @ephraimbuddy are you working on it or is this issue up for taking?

**Comment by ephraimbuddy** [comment]
You can work on it, I'm not currently working on it.

**Comment by OmairK** [comment]
Great, can you assign me this task please. Thanks :smile:
