### ISSUE TITLE
Add unit test for WasbTaskHandler

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#9603]
Description

The WasbTaskHandler from airflow.utils.log.wasb_task_handler does not have a unit test.

Use case / motivation

The test is necessary so that we can be able to move the WasbTaskHandler to its providers package(microsoft)

Related Issues
#9386

**Comment by ephraimbuddy** [comment]
Hi @mik-laj , I want to work on this?

**Comment by mik-laj** [comment]
Every contribution is valuable. You don't have to add tests if you want to move this class.  You can add this file to the exclusion list.

**Comment by ephraimbuddy** [comment]
Oh. Thanks. I never knew.

**Comment by ephraimbuddy** [comment]
Moving it now. Never thought of it:)
