### ISSUE TITLE
TimeSensor triggers immediately when used over midnight (UTC)

### ISSUE THREAD

**Issue by freget** [apache/airflow#9609]
**Apache Airflow version**: 1.10.10 (issue exists in current master as well)

**Environment**: does not seem relevant

**What happened**:

The TimeSensor does trigger if the current time is later than the defined trigger time. Looking at the [source code](https://github.com/apache/airflow/blob/master/airflow/sensors/time_sensor.py), the trigger rule is defined as
```
return timezone.utcnow().time() > self.target_time
```
This leads to problems when the DAG runs over midnight UTC. For example, suppose the following DAG:

```
with DAG('foo', 
    default_args={'start_date': datetime(2020, 7, 1, tzinfo=pendulum.timezone("Europe/Berlin"))}, 
    schedule_interval="0 0 * * *") as dag:

    # in summer, Europe/Berlin is two hours after UTC, hence: 
    time_04h00_local = TimeSensor(task_id="time_01h30", target_time=time(hour=2, minute=00))
```

This DAG will be triggered at 22:00 UTC. Then, according to the trigger rule:
```
22:00 UTC > 2:00 UTC
```
Hence, the TimeSensor will be triggered immediately. 

**What you expected to happen**:

The TimeSensor should trigger at the following day if `target_time < next_execution_date.time()`

**Possible workarounds**:

One can always use the TimeDeltaSensor to archive similar effects. This does result in code that is not as readable, though.

**Comment by zikun** [comment]
I would say this is a feature request rather than a bug. The TimeSensor behaves as expected.

I would like to propose a new sensor `DateTimeSensor`.

So in case above, it will be something like
`time_04h00_local = DateTimeSensor(task_id="time_01h30", target_time=pendulum.parse('{{ next_execution_date }}').add(days=1).replace(hour=2, minute=0)`

WDYT?

**Comment by freget** [comment]
I would also be fine with a new sensor. I still believe that this problem should be at least documented, as it is everything but obvious if the DAG is initialized timezone aware.

**Comment by zikun** [comment]
I just realize your case is a little different. You must have set `default_timezone` in the Airflow config. I think we should fix it in `TimeSensor` itself. I'll make a quick PR
