### ISSUE TITLE
Git-sync retry for worker pods 

### ISSUE THREAD

**Issue by bhavaniravi** [apache/airflow#9625]
**Description**

Airflow when using KubernetesExecutor and `git-mode` need to have a `GIT_SYNC_MAX_SYNC_FAILURES` option. 

**Use case / motivation**

When running a task with `git-mode` and KubernetesExecutor with self-hosted bitbucket or GitLab,  the pod fails because it couldn't connect to the Code hosting service thereby marking the task failed. 

While we can set `GIT_SYNC_MAX_SYNC_FAILURES` as suggested by [Kubernetes git-sync repo](https://github.com/kubernetes/git-sync), there is no option to set this in airflow workers via config.

**Comment by bhavaniravi** [comment]
On approval as a valid feature, I would love to work on this :)

**Comment by eladkal** [comment]
@jedcunningham WDYT?

**Comment by jedcunningham** [comment]
I assume this is for the helm chart. This can already be set via `dags.gitSync.maxFailures`.

@bhavaniravi, if this isn't what you meant, we can reopen this. Thanks!
