### ISSUE TITLE
"Try Number" is off by 1 in the Gantt view

### ISSUE THREAD

**Issue by jpuffer** [apache/airflow#9633]
**Apache Airflow version**: 1.10.10

**Environment**:

- **Cloud provider or hardware configuration**: Astronomer

**What happened**:
In the Gantt view, all tasks start at "Try number: 2" and increment from there.

**What you expected to happen**:
I expect the first try to be called try number 1.

**How to reproduce it**:
Look at gantt view for any DAG run

**Anything else we need to know**:

JIRA says this was solved as of v..10.7, but I'm finding that's not the case:
https://issues.apache.org/jira/browse/AIRFLOW-2143

**Comment by kaxil** [comment]
Thanks Jake, we will check this and comment back on my findings.
