### ISSUE TITLE
Cannot update XCOMs via RBAC UI

### ISSUE THREAD

**Issue by freedom1989** [apache/airflow#9634]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: 

I cannot update the XCOMs via the RBAC UI. It always show me "Not a valid datetime value."
I even tried `2020-06-30 16:56:02+00:00` and `2020-06-30 16:56:02` as the input.

**What you expected to happen**:

**How to reproduce it**:

![image](https://user-images.githubusercontent.com/3204415/86428573-a817f680-bd1f-11ea-913e-4ee011cf6671.png)

**Anything else we need to know**:

**Comment by potiuk** [comment]
XCom editing is removed completely in 1.10.11 https://github.com/apache/airflow/commit/b8f2cd329e9d97a319dc6eb26992e1f19a467551 - so this issue is not valid any more.
