### ISSUE TITLE
Airflow Logging Sensitive Information

### ISSUE THREAD

**Issue by davido912** [apache/airflow#9638]
The Snowflake hook (and more accurately the dbapihook) logs sensitive information that is retrieved from the Airflow connections metadata. This happens by both the logger and the logging that comes with the cursor itself that fires the SQL commands. 
This part of the code I believe is the offender: (dbapi_hook.py/ run function)
```         with closing(conn.cursor()) as cur:
                for s in sql:
                    if sys.version_info[0] < 3:
                        s = s.encode('utf-8')
                    if parameters is not None:
                        self.log.info("{} with parameters {}".format(s, parameters))
                        cur.execute(s, parameters)
                    else:
                        self.log.info(s)
                        cur.execute(s)
```

I posted this issue on the official Slack channel and I was told to bring this issue up here. Would be great if we could mask this kind of information from being printed to the logs.

**Comment by kaxil** [comment]
What kind of sensitive information were you seeing in logs?

The one you pointed out seems to only log `parameters`

**Comment by davido912** [comment]
I'll give an example of my use case, I'm using the Snowflake hook (which is based on the dbapihook). The hook itself prints to the logs the SQL queries it sends. Snowflake has a SQL query that requires feeding AWS credentials. These are ingested into the SQL string by pulling them from the Airflow metadatabase connections and fired via the Snowflake Hook. However, this hook prints to the Airflow logs the credentials. 

Posting this on the Slack channel was answered with this:
![image](https://user-images.githubusercontent.com/48397009/86536583-2378d400-bee9-11ea-922f-fec7bf227fa4.png)


I am not quite sure what's the bug, however, I am still wondering whether a way exists to mask this kind of sensitive information.

**Comment by kaxil** [comment]
> I'll give an example of my use case, I'm using the Snowflake hook (which is based on the dbapihook). The hook itself prints to the logs the SQL queries it sends. Snowflake has a SQL query that requires feeding AWS credentials. These are ingested into the SQL string by pulling them from the Airflow metadatabase connections and fired via the Snowflake Hook. However, this hook prints to the Airflow logs the credentials.
> 
> Posting this on the Slack channel was answered with this:
> 
> ```
> David Ohayon Jul 3rd at 12:04 PM
> hey hey,
> Is there any workaround to masking sensitive information from being printed to the logs while using hooks? (e.g. Snowflake Hook that is based on the dbapihook)
> 
> 
> 
> 
> 4 replies
> 
> Kamil Breguła🐈  2 days ago
> It's an bug. This should not happen. You can create a ticket so that we can make changes to the code so that this data is not printed in the log
> 
> David Ohayon  2 days ago
> In the sense that these operators shouldn’t log credentials retrieved from the Airflow connections, correct? So this behaviour is to not be expected and isn’t something I need to tweak on my side but should be patched?
> 
> Kamil Breguła🐈  2 days ago
> We sshould patch it in Airflow.
> 
> David Ohayon  2 days ago
> Okay, will open a ticket on github
> ```
> 
> I am not quite sure what's the bug, however, I am still wondering whether a way exists to mask this kind of sensitive information.

You will have to setup a custom logger and mask those information as there is no easy way of knowing what is a secret and what is now when using a SQL statement.

**Comment by kaxil** [comment]
The thing I can do for now is increasing the log level for that specific log line to DEBUG so that the logline won't get to the file until you increase the logging level to DEBUG . WDYT ?

**Comment by davido912** [comment]
Hey @kaxil , thank you for the reply!
It actually sounds like a better solution instead of having the loggers print anything fed to them by default. In a sense, we print the SQL commands sometimes to the logs so we can debug. So having the log level of that line as debug might make more sense :)

**Comment by vikramkoka** [comment]
@kaxil can this issue be closed?

**Comment by kaxil** [comment]
> @kaxil can this issue be closed?

Unfortunately not, we haven't solved the issue

**Comment by JavierLopezT** [comment]
Has this been solved with https://github.com/apache/airflow/pull/15599?
