### ISSUE TITLE
Task failed because of Command exited with return code -9 due to RAM

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#9655]
As far as I understand, the apparition of return code -9 when a task fails, is because the error is unknown. However, I have faced two situations when it was because of a lack of RAM (in my docker image):
-MongoToS3Operator. I solved it modifying the operator and allowing to write on disk
-Retrieving a dataframe with the dbapi hook, due to the size of the dataframe

I have no clue if it is possible to identify when a problem has been because lacking of RAM, but if it is possible, maybe it would be nice to have a new code that specifies it

**Comment by madison-ookla** [comment]
From what we have seen, a -9 code indicates that it is an OOM issue. We have not seen a -9 occur in any other circumstances. It seems like for python, a -9 indicates a memory issue ([relevant stackoverflow link](https://stackoverflow.com/questions/18529452/what-does-a-python-process-return-code-9-mean))

**Comment by eladkal** [comment]
@JavierLopezT is this issue diffrenat than https://github.com/apache/airflow/issues/14270 which was already resolved?

**Comment by JavierLopezT** [comment]
> @JavierLopezT is this issue diffrenat than #14270 which was already resolved?

No. Sorry, I didn't realize I had already opened this one.
