### ISSUE TITLE
Replace flask_oauthlib with Authlib

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#9662]
**Description**

flask_oauthlib has been deprecated in favour of Authlib. It would be good if airflow starts using Authlib

**Use case / motivation**

FlaskAppBuilder is now using Authlib. 
Since FlaskAppBuilder is deeply integrated into Airflow, it will be good to also have this Authlib. Flask-oauthlib documentation recommends Authlib

**Related Issues**

**Comment by scoiatael** [comment]
Flask OAuthlib has not been updated since May, 2018 (https://pypi.org/project/Flask-OAuthlib/) and depends on OAuthlib < 3.0.0 (also from May, 2018).

**Comment by ephraimbuddy** [comment]
We want to start using Authlib. Can you help @scoiatael?

**Comment by scoiatael** [comment]
@ephraimbuddy I'll see if I can manage to get some time allocated for that, but I'm not very optimistic about that.
