### ISSUE TITLE
Order BROKEN DAG messages in the UI

### ISSUE THREAD

**Issue by JeffryMAC** [apache/airflow#9669]
**Apache Airflow version**: 1.10.7

**What happened**:

When you have more than 1 Broken dag error in the UI every time you refresh the screen the order of the error changes. it's so annoying.

**What you expected to happen**:

have some strict order of the messages. Whatever order you want but make it consistant.

**How to reproduce it**:
add a 2-3 dags with errors so broken dag error appears. refresh the screen few times you will see the order of messages changes randomly.

**Comment by anubhav562** [comment]
Hey @JeffryMAC, I was able to reproduce this issue. I would like to work on this issue and would love to contribute to the source code. Any idea on how do we get ourselves assigned to the issue?

**Comment by potiuk** [comment]
Assigned you :)

**Comment by danielenricocahall** [comment]
@anubhav562 did you happen to start working on this yet? I see how to fix it but I didn't want to submit a PR if you plan to!

**Comment by anubhav562** [comment]
Hi, Danny (@danielenricocahall)! Yeah, sure you can go ahead with it!
