### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by machbio** [apache/airflow#968]
Python3 Support pending for Airflow -  https://caniusepython3.com/project/airflow
- croniter (which is blocking airflow) - (supports python3 - https://travis-ci.org/kiorky/croniter)
- dill (which is blocking airflow) - (https://github.com/uqfoundation/dill/blob/master/setup.py#L175)
- thrift (which is blocking airflow) - (supports python3 - https://thriftpy.readthedocs.org/en/latest/#features)

As mentioned above from caniusepython3 website, all the following have support - can we be specific on why Airflow is not supported for python3 yet ?

**Comment by mistercrunch** [comment]
We actually run the tests against both `2.7` and `3.4` systematically. We have folks using 3.4 in production. I just need to figure out what I need to change in my `setup.py` I assume...

**Comment by jlowin** [comment]
I'm going to close this -- I'm not sure why Airflow doesn't show up as Py3 but it most certainly is!
