### ISSUE TITLE
Transfer to upload files from SFTP to Azure Blob Storage

### ISSUE THREAD

**Issue by wolvery** [apache/airflow#9683]
**Description**

Transfer to scan files from sftp source path and upload them to Azure Blob Storage

**Use case / motivation**

* Scan a source path and upload files using a wildcard or the complete source path of a file at SFTP and upload these files to a Azure Blob Storage.

**PR Created**
 Process to upload sftp files to blob storage #9677

**Comment by wolvery** [comment]
Hi @eladkal I believe I have finished a solution to this issue at #14254

**Comment by eladkal** [comment]
hi @wolvery are you still working on the PR? there are comments that needs to be addresed

**Comment by wolvery** [comment]
> hi @wolvery are you still working on the PR? there are comments that needs to be addressed

Hi @eladkal, yes, I am still working on it. I am going to answer them today. Sorry for the late answer
