### ISSUE TITLE
run --local return status 0 even if command fails

### ISSUE THREAD

**Issue by kretes** [apache/airflow#969]
When airflow is not on bash path we get following situation

```
/home/ubuntu/.conda/envs/airflow/bin/airflow run -l NDCG hive_partition_ndcg_0 2016-02-06T12:00:00
[2016-02-08 15:55:25,118] {__init__.py:36} INFO - Using executor CeleryExecutor
Logging into: /home/ubuntu/airflow/logs/NDCG/hive_partition_ndcg_0/2016-02-06T12:00:00
bash: airflow: command not found
$ echo "$?"
0

```

obviuosly it should fail if airflow command is not found.

additionaly it claims it is using celery although it is running the process locally (airflow 1.6.2)

**Comment by r39132** [comment]
Hi @kretes, 
`[2016-02-08 15:55:25,118] {__init__.py:36} INFO - Using executor CeleryExecutor` is misleading. It's just printing out what the default executor is based on configuration when overrides (e.g. '-l') are not provided. In this case, the LocalExecutor will be used. The output should be changed. Would you like to submit a PR for it and I can merge it?

**Comment by r39132** [comment]
In terms of handling the return differently, feel free to submit a PR. There is one place where this is done:

<img width="571" alt="screenshot 2016-02-16 00 00 51" src="https://cloud.githubusercontent.com/assets/581734/13063474/68dc32a0-d440-11e5-93cd-3c8494d6269a.png">

This looks correct, but it seems that cli.py is not bubbling this return code up! Instead, you are getting the return code of cli.py. 

In general, I'd say adding airflow to the path is the solution, but I agree this is something that could trip people up during setup. Hence, submit a PR and we will look at it.

**Comment by bolkedebruin** [comment]
@r39132 @kretes can you guys create a Jira for this?
