### ISSUE TITLE
Schedule Interval Last Thursday of every month

### ISSUE THREAD

**Issue by hlokired** [apache/airflow#9703]
Hi Team, 

We have a requirement that we need to schedule a Airflow Job on last Thursday of every month.
So basically we might have 4 or 5 Thursdays depends on the month.

how can it be changed dynamically. i.e.: its 4th or 5th Thursday.

We tried implementing with the below, but it didn't work 
We have scheduled it for schedule_interval= "45 01 * * 4L".

We have raised to google support after multiple options and support team asked to raise the issue with Airflow team.

Could you please help us with the requirement.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/9096
