### ISSUE TITLE
airflow 1.10 filter logs based on DAG owner

### ISSUE THREAD

**Issue by 51yu** [apache/airflow#9711]
**Apache Airflow version**:
1.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
not k8s issue

**Environment**:
linux

**What happened**:
when FILTER_BY_OWNER enabled, logs view should also filtered based on dag owner
otherwise, dag_link in log list could redirect to any dag without constraint of dag owner
https://github.com/apache/airflow/blob/v1-10-stable/airflow/www/views.py#L2980

**What you expected to happen**:
user has subset view of logs owned by user (specified in owner field in DAG defninition) 

**How to reproduce it**:
1. enable filter by owner and create two dags with different owner 
2. when user login, in navigation bar click browse -> logs, in version 1.10. user could view any logs
and further click dag link to visit any dag

**Comment by kaxil** [comment]
We have deprecated the old UI and from Airflow 2.0.0 the new RBAC UI will be the default UI. Hence all the changes to old UI have been freezer. Please use the RBAC UI -- https://airflow.apache.org/blog/airflow-1.10.12/#use-airflow-rbac-ui
