### ISSUE TITLE
store_serialized_dags causes a pile up of open connections to the database backend with ~3000 DagRuns

### ISSUE THREAD

**Issue by amr-noureldin** [apache/airflow#9718]
**Apache Airflow version**: 1.10.10

**Environment**:
PostgreSQL ~~9.4~~ 10

- **OS** (e.g. from /etc/os-release): Fedora 28
- **Kernel** (e.g. `uname -a`): Linux  3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

**What happened**: Upon enabling `store_serialized_dags`, we noticed that connections pile up on the database end that are never closed. Out of 2500 open db connections, 2495 had running queries: 

```
DELETE FROM rendered_task_instance_fields WHERE rendered_task_instance_fields.dag_id = ‘my_dag_id’ AND rendered_task_instance_fields.task_id = ‘my_task_id’ AND (rendered_task_instance_fields.dag_id, rendered_task_ins
tance_fields.task_id, rendered_task_instance_fields.execution_date) NOT IN (SELECT rendered_task_instance_fields.dag_id, rendered_task_instance_fields.task_id, rendered_task_instance_fields.execution_date FROM rendered_task_instance_fields
  WHERE rendered_task_instance_fields.dag_id = 'my_dag_id' AND rendered_task_instance_fields.task_id = 'my_task_id' ORDER BY rendered_task_instance_fields.execution_date DESC
   LIMIT 30
```

Upon disabling `store_serialized_dags`, we no longer saw such a pile up of db connections.

Irrelevant, but wouldn't hurt to mention: we are using pgbouncer as a connection pool between Airflow and PostgreSQL ~~9.4~~ 10. Pgbouncer is configured for transactional connections.

**What you expected to happen**: I did not expect such queries to take that long to execute, and block the db backend from further requests.

**How to reproduce it**:
- Enable store_serialized_dags
- Trigger a particularr DAG, with 3000 DagRuns

**Comment by kaxil** [comment]
A workaround would be to set `max_num_rendered_ti_fields_per_task` to 0 (https://airflow.readthedocs.io/en/stable/configurations-ref.html#max-num-rendered-ti-fields-per-task)

**Comment by kaxil** [comment]
Can you also test it with Postgres >= 9.6 on a test instance and let us know if you still see the issue

**Comment by amr-noureldin** [comment]
Sorry for the typo, this issue was encountered when running on Potgres 10

**Comment by ashb** [comment]
Can you give us an example dag that shows this problem too please?

**Comment by ashb** [comment]
Could you also please run `EXPLAIN ANALYZE` on that delete query in your DB?

**Comment by kaxil** [comment]
This should be fixed by https://github.com/apache/airflow/pull/9993
