### ISSUE TITLE
Task instance null, execution date skipped

### ISSUE THREAD

**Issue by AyWa** [apache/airflow#9731]
**Apache Airflow version**: `1.10.9`
**DB**:  `Postgre11.6` (aws rds)

**Environment**:

- **Cloud provider or hardware configuration**: `AWS BEANSTALK - DOCKER` in a `Local` executor

**What happened**:

In the UI, everything looks to be correctly run:

<img width="645" alt="Screen Shot 2020-07-09 at 1 04 12 PM" src="https://user-images.githubusercontent.com/13608477/86998728-f3347c80-c1eb-11ea-962b-d4c09c9cacac.png">

However, we figure out that one execution date was missing (in our application). So I tried to find the reason why, and in the tree view, they was no circle for this date.
So I ran `SELECT * FROM dag_run where execution_date='2020-05-25T00:00:00+00:00'` and there was no row too.

After that I check the pool task, and by filter by date (filter by status not equal to success was showing nothing), I found:

<img width="1641" alt="Screen Shot 2020-07-09 at 1 04 01 PM" src="https://user-images.githubusercontent.com/13608477/86998972-7ce44a00-c1ec-11ea-9725-21433b181018.png">

So somehow, airflow UI is a bit misleading, because there was a task that failed to be run. But there was no easy way to figure out, without knowing the date or going to the database and running `SELECT * from task_instance where state is Null where  execution_date='2020-05-26T00:00:00+00:00';`

![Screen Shot 2020-07-09 at 1 24 37 PM](https://user-images.githubusercontent.com/13608477/86999465-9e920100-c1ed-11ea-9dca-0f770acdb4cb.png)

**What you expected to happen**:

* I would expect to have an error or at least an indicator that a task instance are in null state or that a dag run was missing
* I would expect to be able to filter `List Task Instance` by `NULL` or `None` status. However it was showing no result (if I was filtering by not equal to success it was empty too)
* ideally I would expect to not have Null state, but If it is in the UI, I think it is acceptable

**How to reproduce it**:

Sadly I do not know how to reproduce, but I think by putting the data in the database we can at least "reproduce" the issue in the UI:

- a dag run need to be empty `SELECT * FROM dag_run where execution_date='2020-05-25T00:00:00+00:00'`-> should give no row
- task instance for this execution date should have an `Null` state like the screenshot shared. 

Because we run in Elastic beanstalk, sometimes, container might be stop / recreated etc, so maybe it is related to that.

**Comment by eladkal** [comment]
I don't think we can use this reproduce steps. If you are deliberately putting wrong data in the database you can't be surprised that the UI shows that wrong data.
many changes were made since 1.0.9 is the issue still happening on Airflow 2?

**Comment by AyWa** [comment]
> The question is how the wrong/missing records were created to begin with.

Only airflow is writing to the `DB` -> I only made query when investigating the issue of why there was missing execution date.

However, I do not seems to be able to reproduce often. We didnt migrated to airflow 2 yet.
i will close this issue
