### ISSUE TITLE
DockerOperator does not support wait timeout for container

### ISSUE THREAD

**Issue by sahil-b-shah** [apache/airflow#9732]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: 

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux Ubuntu SMP 2018 x86_64 GNU/Linux
- **Install tools**: Python 3.6.11
- **Others**:
Docker version 18.03.0-ce
docker==4.2.0

**What happened**:
Modified the `DockerOperator` to accept a `timeout` parameter that gets passed on to the `cli.wait` command (i.e. `result = self.cli.wait(self.container["Id"], timeout=self.timeout)` ). 

The timeout does not work correctly. The container goes till full execution even if it's past the timeout window.

**What you expected to happen**:

The following commands work correctly when directly using the same docker python api on my local computer, which is Docker version 19.03.5. 

```
from docker import APIClient
cli = APIClient()
container = cli.create_container("alpine", "sleep 45")
cli.start(container["Id"])
cli.wait(container["Id"], timeout=5)
# urllib3.exceptions.ReadTimeoutError after 5 seconds
```

**How to reproduce it**:

Pass a `timeout` value in the call to `cli.wait` in L 260 of airflow/providers/docker/operators/docker.py

**Anything else we need to know**:

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/22502
