### ISSUE TITLE
Initial support for Mixpanel ETL applications 

### ISSUE THREAD

**Issue by shaneikennedy** [apache/airflow#9738]
**Description**

Initial support  for Mixpanel ETL applications -> Connections, Hooks, Operators (Mixpanel -> Storage service)

**Use case / motivation**

Use case: Moving Mixpanel event data to a data warehouse for BI reporting.

Motivation: With how popular Mixpanel is as an analytics service I'm surprised there isn't already support for them. I'm currently working on an implementation of a Hook and an Operator but figure they could be of use to the community as well. If there's interest I'd be happy to contribute upstream 👍 

**Related Issues**

Could not find any related issues.

**Comment by eladkal** [comment]
@shaneikennedy  You are more than welcome to contribute. Can I assign this task to you?

**Comment by shaneikennedy** [comment]
@eladkal sorry, I've moved companies since opening the issue and don't think I have the time 😞

**Comment by ulinares** [comment]
Hi everyone, 
Currently I'm working on this, I'd be happy to contribute.

**Comment by potiuk** [comment]
Assigned you @ulinares !

**Comment by omer-ginosar** [comment]
@ulinares Can you share your progress with it? When do you think it'll be avail?

**Comment by eladkal** [comment]
Policy for adding new provider is explained at https://github.com/apache/airflow/blob/main/PROVIDERS.rst

I'm going to close this issue as the process of adding a provider require investment and commitment from the requester thus it's unlikely that someone will just pick up this request and implement it so no reason to keep this issue open.
