### ISSUE TITLE
Statuses column on DAGs homepage should only represent active or most recent DAG runs

### ISSUE THREAD

**Issue by jtschoonhoven** [apache/airflow#974]
**Problem**
Currently the status column shows the sum of successes/failures for all history. This makes it very difficult to tell at a glance whether the most recent DAG run completed successfully. I often have to enter tree view and zoom out to learn if a given DAG run failed. My intuition is that most Airflow users do not care about failed tasks from the not recent past and the default behavior should be to hide these.

**Proposal**
The statuses column should only represent the statuses of tasks in all _currently active_ DAG runs. If no DAG is currently active, it should represent the _most recent_ DAG run. This way the user can quickly scan the DAGs homepage to find whether the most recent DAG run completed successfully.

I intend to have a PR out for this soon. Posting here first for feedback.

**Comment by jtschoonhoven** [comment]
The query that currently backs statuses column is equivalent to:

```
SELECT ti.dag_id, ti.state, COUNT(ti.task_id)
FROM task_instance ti
GROUP BY 1, 2;
```

In my proposal this becomes:

```
SELECT ti.dag_id, ti.state, COUNT(task_id)
FROM task_instance ti
LEFT JOIN (
    SELECT dag_id, execution_date FROM dag_run WHERE dag_run.state = 'running'
) active ON ti.dag_id = active.dag_id AND ti.execution_date = active.execution_date
LEFT JOIN (
    SELECT dag_id, MAX(execution_date) AS execution_date FROM dag_run GROUP BY dag_id
) recent ON ti.dag_id = recent.dag_id AND ti.execution_date = recent.execution_date
WHERE active.dag_id IS NOT NULL
OR recent.dag_id IS NOT NULL
GROUP BY 1, 2;
```

**Comment by mistercrunch** [comment]
Sounds very logical. Let me take a look at the PR.

**Comment by bruce-lyft** [comment]
:100:  for this.  Thank you @jtschoonhoven  and @mistercrunch  for this change!
