### ISSUE TITLE
Replace azure-datalake-store by azure-mgmt-datalake-store

### ISSUE THREAD

**Issue by feluelle** [apache/airflow#9743]
**Description**

This should be a change which not effects the usage of the related provider modules i.e. **refactoring**.

Microsoft actively develops python packages for Azure in https://github.com/Azure/azure-sdk-for-python 
> This repository is for active development of the Azure SDK for Python

Those packages can be recognized by prefix `azure-mgmt-`.

**Comment by xuky76** [comment]
Hi @feluelle,

I have taken a look into this and I am not sure if I understand. It doesn't seem like the functionality from azure-datalake-store is in azure-mgmt-datalake-store. Perhaps it's [azure-storage-file-datalake](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-datalake)?

I honestly don't know for sure as I'm new. Some clarification would be great

Cheers!

**Comment by potiuk** [comment]
I think we can close that one @feluelle ?  I am not sure we are going to do anything about it?
