### ISSUE TITLE
Replace azure-kusto-data by azure-mgmt-kusto

### ISSUE THREAD

**Issue by feluelle** [apache/airflow#9744]
**Description**

This should be a change which not effects the usage of the related provider modules i.e. **refactoring**.

Microsoft actively develops python packages for Azure in https://github.com/Azure/azure-sdk-for-python 
> This repository is for active development of the Azure SDK for Python

Those packages can be recognized by prefix `azure-mgmt-`.

**Comment by spektom** [comment]
Hi @feluelle 

I don't think this library provides a way to query Kusto data, it's just a (autogenerated) tool for managing Kusto clusters using ARM templates.

**Comment by feluelle** [comment]
> I don't think this library provides a way to query Kusto data

Thanks @spektom I see. You are correct. And the `adx` hook we already have is querying data. So I am gonna close this ticket.
