### ISSUE TITLE
Replace azure-storage and azure-storage-blob by azure-mgmt-storage

### ISSUE THREAD

**Issue by feluelle** [apache/airflow#9745]
**Description**

This should be a change which not effects the usage of the related provider modules i.e. **refactoring**.

Microsoft actively develops python packages for Azure in https://github.com/Azure/azure-sdk-for-python 
> This repository is for active development of the Azure SDK for Python

Those packages can be recognized by prefix `azure-mgmt-`.

**Comment by kaxil** [comment]
I think those are 2 different libraries that serve different purposes: https://www.gcptutorials.com/post/azure-sdk-management-vs-client-libraries

https://github.com/Azure/azure-sdk-for-python#packages-available


https://pypi.org/project/azure-storage-blob/  (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob) vs https://pypi.org/project/azure-mgmt-storage/

**Comment by feluelle** [comment]
Yes @kaxil I think you're right. If the libraries are substantial different we can close the PR.
