### ISSUE TITLE
Missing refresh_all method in airflow/www/views.py

### ISSUE THREAD

**Issue by prakshalj0512** [apache/airflow#9749]
**Apache Airflow version**: 1.10.x
**What happened**:

The refresh_all method was deleted as part of this PR: https://github.com/apache/airflow/commit/66b2a47d9e6dbef551e31d41d23ee4fc2eae3636#diff-948e87b4f8f644b3ad8c7950958df033

Lines 1719-1728 in `airflow/www/views.py`
```
@expose('/refresh_all', methods=['POST'])
@has_access
@action_logging
 def refresh_all(self):
      dagbag.collect_dags(only_if_updated=False)
       # sync permissions for all dags
       for dag_id, dag in dagbag.dags.items():
            appbuilder.sm.sync_perm_for_dag(dag_id, dag.access_control)
        flash("All DAGs are now up to date")
        return redirect(url_for('Airflow.index'))
```
Also, in `airflow/www/test_views.py`, add the following code (reference Lines 650-653 from the PR):
```
def test_refresh_all(self):
        resp = self.client.post("/refresh_all",
                                follow_redirects=True)
        self.check_content_in_response('', resp, resp_code=200)
```
Kindly add the method. Thanks!

**Comment by turbaszek** [comment]
Summoning @kaxil as our serialization expert, https://github.com/apache/airflow/pull/5743

**Comment by kaxil** [comment]
> Summoning @kaxil as our serialization expert, #5743

Thanks Tomek, yeah we had a chat with @prakshalj0512 on Slack about this. I will look into why I removed this method and if I can't find any good reason, we will add it back for 1.10.12

**Comment by kaxil** [comment]
We have decided against backporting this as calling `/refresh_all` would only refresh DAGs for a single gunicorn worker and might cause inconsistent state on Ctr+R (Browser refresh)
