### ISSUE TITLE
Connect to Compute Engine instance by name

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9752]
Hello,

It would be very helpful to have an operator that allows you to execute the SSH command on another virtual machine without the need to manage RSA keys and without the need to configure IP addresses. 

* The server should be specified by instance name and zone.
* The key should be provided using the following methods (user selection):
   - [OSLogin](https://cloud.google.com/compute/docs/instances/managing-instance-access#gcloud_1)
   - [Project/instance metadata](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys)
   - None 
-  We should support tunnel the ssh connection through [the Cloud Identity-Aware Proxy](https://cloud.google.com/iap/docs/using-tcp-forwarding). Thanks to this, we will be able access to VM instances that do not have public IP addresses or do not permit direct access over the internet.
- We should support Connect to instances using their internal IP addresses rather than their external IP addresses. Thanks to this, we will be able to connect from one instance to another on the same VPC network, over a VPN connection, or between two peered VPC networks.

In brief. This should work similarly to the [gcloud compute ssh](https://cloud.google.com/sdk/gcloud/reference/compute/ssh
) command.

**Comment by ad-m** [comment]
As reference implementation source code of `gcloud compute ssh` is available at https://github.com/twistedpair/google-cloud-sdk/blob/35260d66269f5bb1db88c5f1f96365b813c29ce7/google-cloud-sdk/lib/googlecloudsdk/compute/subcommands/ssh.py .
