### ISSUE TITLE
pip install apache-airflow[all]==1.10.0 error

### ISSUE THREAD

**Issue by zhbdesign** [apache/airflow#9763]
[root@hadoop-master2 airflow]# pip install -i https://pypi.douban.com/simple/ apache-airflow[all]==1.10.0
Looking in indexes: https://pypi.douban.com/simple/
Collecting apache-airflow[all]==1.10.0
  Using cached https://pypi.doubanio.com/packages/da/2a/6e9efcd40193850e2f636c7306eede2ff5607aa9f81ff9f7a151d9b13ff8/apache-airflow-1.10.0.tar.gz (4.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-itml1imn/apache-airflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-itml1imn/apache-airflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bu73rbu0
         cwd: /tmp/pip-install-itml1imn/apache-airflow/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-itml1imn/apache-airflow/setup.py", line 124
        async = [
              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kaxil** [comment]
What Python version are you using?

**Comment by zhbdesign** [comment]
> What Python version are you using?

python3.7.5,I can execute without a version number. Can I use Python 3.7.5 for version 1.10

**Comment by zhbdesign** [comment]
> What Python version are you using?
How to solve the following errors?

Using legacy setup.py install for multi-key-dict, since package 'wheel' is not installed.
Using legacy setup.py install for python-http-client, since package 'wheel' is not installed.
ERROR: astroid 2.4.2 has requirement lazy-object-proxy==1.4.*, but you'll have lazy-object-proxy 1.5.0 which is incompatible.
ERROR: snowflake-connector-python 2.2.8 has requirement azure-storage-blob<13.0.0,>=12.0.0; python_version >= "3.5.2", but you'll have azure-storage-blob 2.1.0 which is incompatible.
ERROR: snowflake-connector-python 2.2.8 has requirement boto3<1.14,>=1.4.4, but you'll have boto3 1.14.20 which is incompatible.
ERROR: snowflake-connector-python 2.2.8 has requirement idna<2.10, but you'll have idna 2.10 which is incompatible.
ERROR: snowflake-connector-python 2.2.8 has requirement requests<2.24.0, but you'll have requests 2.24.0 which is incompatible.
Installing collected packages: google-cloud-texttospeech, parameterized, sphinx-jinja, isodate, msrest, msrestazure, azure-mgmt-resource, google-cloud-spanner, google-cloud-secret-manager, cassandra-driver, presto-python-client, sphinxcontrib-dotnetdomain, unidecode, astroid, sphinxcontrib-golangdomain, sphinx-autoapi, hvac, sasl, thrift-sasl, pyhive, JPype1, pymongo, sentinels, mongomock, pydruid, pymssql, azure-mgmt-containerinstance, cgroupspy, pysmbclient, hmsclient, uritemplate, google-api-python-client, pytest-cov, google-cloud-container, filelock, distlib, virtualenv, freezegun, future-fstrings, pinotdb, atlasclient, docopt, fastavro, requests-kerberos, hdfs, flaky, psycopg2-binary, google-cloud-bigquery, pydata-google-auth, pandas-gbq, identify, nodeenv, cfgv, pre-commit, jaydebeapi, sentry-sdk, pytest-forked, apipkg, execnet, pytest-xdist, google-cloud-vision, multi-key-dict, python-jenkins, cx-Oracle, PyOpenSSL, requests-mock, websocket-client, slackclient, pycryptodomex, asn1crypto, oscrypto, snowflake-connector-python, google-cloud-translate, kubernetes, snowflake-sqlalchemy, elasticsearch, python-http-client, sendgrid, datadog, mysqlclient, sshtunnel, elasticsearch-dsl, google-cloud-language, blinker, yamllint, sphinx-copybutton, apache-airflow
    Running setup.py install for cassandra-driver ... done
    Running setup.py install for sphinxcontrib-dotnetdomain ... done
  WARNING: The script unidecode is installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for sasl ... error
    ERROR: Command errored out with exit status 1:
     command: /bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ymxn2sfp/sasl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ymxn2sfp/sasl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-p_lrphvv/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/sasl
         cwd: /tmp/pip-install-ymxn2sfp/sasl/
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/sasl
    copying sasl/__init__.py -> build/lib.linux-x86_64-3.7/sasl
    running egg_info
    writing sasl.egg-info/PKG-INFO
    writing dependency_links to sasl.egg-info/dependency_links.txt
    writing requirements to sasl.egg-info/requires.txt
    writing top-level names to sasl.egg-info/top_level.txt
    reading manifest file 'sasl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'sasl.egg-info/SOURCES.txt'
    copying sasl/saslwrapper.cpp -> build/lib.linux-x86_64-3.7/sasl
    copying sasl/saslwrapper.h -> build/lib.linux-x86_64-3.7/sasl
    copying sasl/saslwrapper.pyx -> build/lib.linux-x86_64-3.7/sasl
    running build_ext
    building 'sasl.saslwrapper' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/sasl
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isasl -I/usr/local/include/python3.7m -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-3.7/sasl/saslwrapper.o
    In file included from sasl/saslwrapper.cpp:254:0:
    sasl/saslwrapper.h:22:23: 致命错误：sasl/sasl.h：没有那个文件或目录
     #include <sasl/sasl.h>
                           ^
    编译中断。
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ymxn2sfp/sasl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ymxn2sfp/sasl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-p_lrphvv/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/sasl Check the logs for full command output.

**Comment by mik-laj** [comment]
This version does not support Python 3.7. This version supports: "2.7", "3.5". In Airflow 1.10.4, we added support for Python 3.6. Can you check these versions?

**Comment by potiuk** [comment]
Also, if you are trying to install Airflow for the first time. I definitely recommend to install the latest released version 1.10.11.

**Comment by mik-laj** [comment]
I think we can do nothing to solve this ticket, so I close this ticket. We have a simple workaround - upgrade to the new version of Airflow
