### ISSUE TITLE
Params dictionary passed to multiple tasks are overridden

### ISSUE THREAD

**Issue by nicktrav** [apache/airflow#977]
When creating tasks that use the same `default_args` dictionary in which template params are stored, the params dictionary is inadvertently modified.

To reproduce, use the following Dag definition:

``` python
from datetime import datetime

from airflow import DAG
from airflow.operators import BashOperator


args = {
    'owner': 'test',
    'params': {
        'param1': 1,
        'param2': 2,
    }
}

dag = DAG(
    'test-dag',
    start_date=datetime(2016, 1, 1),
    schedule_interval="@once",
    default_args=args,
)

a = BashOperator(
    task_id='task-a',
    bash_command="echo 'param1: {{ params.param1 }}'",
    dag=dag,
    default_args=args,
)

b = BashOperator(
    task_id='task-b',
    bash_command="echo 'param2: {{ params.param2 }}'",
    dag=dag,
    default_args=args,
)

a.set_downstream(b)
```

Running `task-b` returns nothing for `param2` (we expect `2`):

``` bash
$ airflow test test-dag task-b 2015-01-01
016-02-08 21:28:55,611] {bash_operator.py:62} INFO - Running command: echo 'param2: '
[2016-02-08 21:28:55,615] {bash_operator.py:70} INFO - Output:
[2016-02-08 21:28:55,617] {bash_operator.py:74} INFO - param2:
[2016-02-08 21:28:55,617] {bash_operator.py:77} INFO - Command exited with return code 0
```

When modifying `task-a` to use a _copy_ of the dictionary, i.e.

``` python
a = BashOperator(
    task_id='task-a',
    bash_command="echo 'param1: {{ params.param1 }}'",
    dag=dag,
    default_args=args.copy(),
)
```

then re-running `task-b` returns the parameter values, as expected:

``` bash
$ airflow test test-dag task-b 2015-01-01
[2016-02-08 21:30:33,379] {bash_operator.py:62} INFO - Running command: echo 'param2: 2'
[2016-02-08 21:30:33,383] {bash_operator.py:70} INFO - Output:
[2016-02-08 21:30:33,385] {bash_operator.py:74} INFO - param2: 2
[2016-02-08 21:30:33,385] {bash_operator.py:77} INFO - Command exited with return code 0
```

I think there's something going on where the parameters that are passed into the tasks are accessed and modified in place.

Maybe the task should make a copy of this `default_args` dictionary first?

**Comment by mistercrunch** [comment]
The pattern we've been repeating at Airbnb is to pass the dag when creating the task, this allows for this magic decorator to do wonderful things:
https://github.com/airbnb/airflow/blob/master/airflow/utils.py#L421

I'd encourage you to take this approach since it's thoroughly tested, but I'm going to attempt to fix this bug now.

**Comment by nicktrav** [comment]
Is that different to what I pasted? Can you paste an example of how this would look with regard to my example above?

**Comment by mistercrunch** [comment]
I meant always pass `dag=dag` to all task constructors, and `default_args=args` only to the DAG constructor

**Comment by mistercrunch** [comment]
I understand it may not be super clear, but the the `defaults_args` or the DAG make to the task via the dag=dag in the decorator I pointed to. I'm pretty sure the fix for the bug you found lives in that decorator too...

**Comment by nicktrav** [comment]
This version still doesn't work:

``` python
dag = DAG(
    'test-dag',
    start_date=datetime(2016, 1, 1),
    schedule_interval="@once",
    default_args=args,
)

a = BashOperator(
    task_id='task-a',
    bash_command="echo 'param1: {{ params.param1 }}'",
    dag=dag,
)

b = BashOperator(
    task_id='task-b',
    bash_command="echo 'param2: {{ params.param2 }}'",
    dag=dag,
)
```

**Comment by mistercrunch** [comment]
This patch did it for me:
https://github.com/airbnb/airflow/pull/978

**Comment by nicktrav** [comment]
@mistercrunch - I tested your changes locally and it looks good. Thanks!
