### ISSUE TITLE
Helm chart webserver pod does not start when setting the webserver base url

### ISSUE THREAD

**Issue by vsimon** [apache/airflow#9777]
**Apache Airflow version**:
1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.15.11

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Utilize a proxy in front of the airflow webserver service which proxies the `/airflow` prefix to the service.

In the values.yaml file, configure the [webserver base url environment variable](https://airflow.apache.org/docs/stable/configurations-ref.html#base-url) through the `env:` field.  For example, like `"AIRFLOW__WEBSERVER__BASE_URL: domain.com/airflow/"`.  Install the helm chart. The webserver pod crashloops.

**What you expected to happen**:

The helm chart tailors the correct endpoint to access in it's probes.

**What do you think went wrong?**

When the webserver picks the baseurl value up, in my example the health endpoint is located at `airflow/health` but the pod healthcheck is trying to access the `/health` endpoint resulting in a 404 error and resulting in the pod being periodically restarted for failing it's healthchecks.

**How to reproduce it**:

**Anything else we need to know**:

**Comment by kaxil** [comment]
Solution/work-around in https://github.com/apache/airflow/pull/9778#issuecomment-927357065

Please let me know if this is still an issue and we can reopen it
