### ISSUE TITLE
You need Python 3.5 or later to use mypy when installing version 1.10.11

### ISSUE THREAD

**Issue by zhbdesign** [apache/airflow#9789]
You need Python 3.5 or later to use mypy when installing version 1.10.11. How to solve this problem?

**Comment by potiuk** [comment]
It'sexpected. Why do you want to use mypy in 2.7 in Airflow? 

 MyPy is purely a development dependency and it's not installed with Airflow when you install it without [devel] extra. Python 2.7 is already past the end of life and many tools like MyPy will not work with it any more. In fact MyPy is clear about it in their documentation https://github.com/python/mypy/blob/v0.3.1/README.md#requirements 

> You need Python 3.2 or later to run mypy

Airflow 1.10 supports Python 2.7, 3.5, 3.6. 3.7 (see https://github.com/apache/airflow/blob/master/README.md#requirements) so Python 3.5 + requirement is expected.
