### ISSUE TITLE
Cannot trigger multiple DAG runs per second

### ISSUE THREAD

**Issue by FelixReuthlingerBMW** [apache/airflow#9790]
I am not sure whether to put this as a bug or feature request (depends on how you see this).
As this might be completely independent from versions, os, k8s, ... I will not add this detail here.

Short: When trying to trigger a DAG via the REST API interface more than once per second the Airflow returns a HTTP 500 error code. 

Long: When using Airflow REST API I can send any amount of POST calls, but when sending more calls per second returning an HTTP 500 might be very misleading. If it is expected to not send more requests as 1 per second, it should return an HTTP 400 and have a good error message. If it is intended to be able to send more than 1 POST call per second, I would expect this to be a bug and hopefully be fixed. AFAIK Airflow inside its implementation uses a timestamp with precision of seconds to create a DAG run. But this might not be fitting to having received multiple requests in the same second, since then the uniqueness requirement might be failing.

**Comment by mik-laj** [comment]
You need to set "replace_microseconds" parameter to "False" in body. Unfortunately, this feaature is not documented, but we are working on a new API that will not have this problem.

**Comment by FelixReuthlingerBMW** [comment]
Thanks for the lighting-speed reaction ;)
Will try this out.

**Comment by FelixReuthlingerBMW** [comment]
Probably this is not available with our version 1.10.10, could you please check?
Using this additional parameter in the body caused permanently getting code 500.

**Comment by FelixReuthlingerBMW** [comment]
I sent a body like this:
{"conf":{...},"run_id":"2020-07-13T01:35:26_14e6b65e-d1c8-4452-bf21-2029e181354d","replace_microseconds":false}
Or should it be boolean inside a string?

**Comment by mik-laj** [comment]
Can you try this command?
```
 curl -v \
 -X POST  \
 -H "Content-Type: application/json" \
 'http://localhost:28080/api/experimental/dags/example_bash_operator/dag_runs' \
--data '{"replace_microseconds":"false"}'
```

**Comment by FelixReuthlingerBMW** [comment]
Ok, this works perfect, thx a lot !! ;)

**Comment by mik-laj** [comment]
@FelixReuthlingerBMW Can I ask for a review?
https://github.com/apache/airflow/pull/9793
