### ISSUE TITLE
Add Notification in UI that DAG with Interval Change will not be Scheduled

### ISSUE THREAD

**Issue by jimmycfa** [apache/airflow#9795]
**Description**

I ran into this Pitfall today from https://cwiki.apache.org/confluence/display/AIRFLOW/Common+Pitfalls : "When needing to change your start_date and schedule interval, change the name of the dag" I originally had a daily DAG: '03 * * *' I kept the name but changed to weekly '0 3 * * Sun' and the new schedule did not run.

**Use case / motivation**

I think it would be good to have a feature that flagged the DAG in the UI so you know that the new interval doesn't match the old and that the new DAG schedule won't run. As it stands today unless you find these Pitfalls in the linked doc it is hard to tell why your DAG isn't running.

**Related Issues**
None that I could find.

**Comment by eladkal** [comment]
The confluence pitfall page is no longer available thus it can no longer confuse users with outdated information.
Any relevant information from the pitfalls doc was integrated into Airflow documentation in https://github.com/apache/airflow/pull/15183

**Comment by eladkal** [comment]
The confluence pitfall page is no longer available thus it can no longer confuse users with outdated information.
Any relevant information from the pitfalls doc was integrated into Airflow documentation in https://github.com/apache/airflow/pull/15183
