### ISSUE TITLE
copy without wild cards does not replace source file name

### ISSUE THREAD

**Issue by sisuo3039** [apache/airflow#9803]
Detail issue:
https://stackoverflow.com/questions/62843727/airflow-gcstogcsoperator-destination-object-file-path-not-working

I think the root may be here:
https://github.com/apache/airflow/blob/efe1bdd29b0a02c37f011c1c5783ef295962260d/airflow/providers/google/cloud/transfers/gcs_to_gcs.py#L265
if copy 'abc/' to 'bcd/'
it lists all subfolder file from 'abc/' like 'abc/d.csv','abc/e.csv' but destination still 'bcd/'?
should it replace ('abc/','bcd/,1) as destination object?

**Comment by rm3195** [comment]
One more note here: setting wildcard in `source_objects` gives following log message: `Delimiter ignored because wildcard is in prefix`. So if you want delimiter to work correctly, you need to specify wildcard in source, but if you specify it then delimiter is ignored...

**Comment by potiuk** [comment]
@rm3195 -> maybe you would like to fix this one ? Seems like  a nice contribution.

**Comment by rm3195** [comment]
> @rm3195 -> maybe you would like to fix this one ? Seems like a nice contribution.

Unfortunately my python skills are not that good :(

**Comment by sisuo3039** [comment]
@potiuk 
Let me see if we can help to fix both issues

**Comment by YingyingPeng22** [comment]
https://github.com/apache/airflow/pull/13800

**Comment by uranusjr** [comment]
It seems like the issue mentioned in the original issue description is already fixed in #13919. Should this be closed?
