### ISSUE TITLE
The scheduler does not appear to be running

### ISSUE THREAD

**Issue by zhbdesign** [apache/airflow#9807]
The scheduler does not appear to be running. Last heartbeat was received 9 seconds ago

The DAGs list may not update, and new tasks will not be scheduled

[2020-07-13 15:45:28,005] {scheduler_ job.py:1349 } INFO - Starting the scheduler

[2020-07-13 15:45:28,005] {scheduler_ job.py:1357 } INFO - Running execute loop for -1 seconds

[2020-07-13 15:45:28,006] {scheduler_ job.py:1358 } INFO - Processing each file at most -1 times

[2020-07-13 15:45:28,006] {scheduler_ job.py:1361 } INFO - Searching for files in /opt/airflow/dags

[2020-07-13 15:45:28,007] {scheduler_ job.py:1363 } INFO - There are 0 files in /opt/airflow/dags

[2020-07-13 15:45:28,007] {scheduler_ job.py:1420 } INFO - Resetting orphaned tasks for active dag runs

[2020-07-13 15:45:28,023] {dag_ processing.py:562 } INFO - Launched DagFileProcessorManager with pid: 169618

[2020-07-13 15:45:28,030] { settings.py:55 } INFO - Configured default timezone <Timezone [UTC]>

[2020-07-13 15:52:03,799] {scheduler_ job.py:958 } INFO - 33 tasks up for execution:

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Homework_ Submit_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Member_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Mode_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Pattern_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Poll_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Poll_ Options_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Poll_ Submit_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Questionnaire_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Questionnaire_ Stat_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Resource_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Role_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Satisfaction_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ StatNew_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Stat_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Structure_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Summary_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Topic_ Special_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.m2ctask_ Homework_ SubmitActivity_ Topic_ Video_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.MySql_ 2_ ClickHouse_ Activity_ Activity_ Discuss_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

<TaskInstance: user_ MySql_ 2_ ClickHouse_ increment_ srt_ Activity.MySql_ 2_ ClickHouse_ Activity_ Activity_ Homework_ score_ inc 2020-07-13 09:52:02.590680+00:00 [scheduled]>

**Comment by potiuk** [comment]
As explained in the README and templates - Please use slack to ask for help in troubleshooting, not the github issues. See "Ask a question" chapter in https://airflow.apache.org/community/
