### ISSUE TITLE
Add tests for OpenAPI specification

### ISSUE THREAD

**Issue by ad-m** [apache/airflow#9808]
**Description**

I notice that we have API specifications that require manual maintenance over time. In order to minimize the risk that it will become outdated, I propose to use its elements during integration tests ( https://github.com/apache/airflow/tree/master/tests/api_connexion/endpoints ).

From my own experience I know that simple verification whether the scheme (selected by hard-coded name) contained in the specification contains all the fields placed in the sample answers allows to avoid many oversights. More attention may be required if the relevant schema will be searched based on the path rather than based on the schema name. Then, however, it should not be difficult to check if the status code of the answer is provided by the specifications also.

It requires attention to ensure that this type of test verifies both that the required fields are included in the response and that the response does not contain any fields not included in the specification.

The implementation of basic tests of this type of tests should not be complex, as the current tests contain a response structure in memory, so you should find the appropriate scheme and validate this response, just as HTTP response status code is now verified: 

https://github.com/apache/airflow/blob/5eb2808/tests/api_connexion/endpoints/test_task_endpoint.py#L131-L133

Example implementation in JavaScript:

https://github.com/hyperonecom/h1-cli/blob/5895f7414d3ebf8ceed912ef5443ebc01dd9eb69/lib/tests.js#L55-L65
https://github.com/hyperonecom/h1-cli/blob/5895f7414d3ebf8ceed912ef5443ebc01dd9eb69/lib/tests.js#L188-L191

OpenAPI uses the JSONSchema standard for the schema definition, for which there are numerous validators even for old-fashion Python ( https://json-schema.org/implementations.html).

**Use case / motivation**

Reduce maintenance burden of OpenAPI specification

**Related Issues**

#8107

**Comment by ad-m** [comment]
@mik-laj, could you add label "area:API" and "good first issue"?

**Comment by mik-laj** [comment]
We use [connexion](https://connexion.readthedocs.io/en/latest/request.html#request-validation) to handle this case.  Do you want to add something more?

**Comment by ad-m** [comment]
I was not aware that connection are able to validate responses:
https://github.com/apache/airflow/blob/53c0f2d987bf3dbfb59da283287f4aa7b72524ab/airflow/www/extensions/init_views.py#L105
