### ISSUE TITLE
add impersonation authentication (proxy-user authentication)

### ISSUE THREAD

**Issue by Tagar** [apache/airflow#982]
It would be great to have impersonation authentication added in.

So, for example, like it is implemented in Hue:
1. Hue runs under a service account "hue" (in kerberized clusters it will be hue/FQDN@realm);
2. Users authentication in Hue using e.g. LDAP authentication;
3. Other services (e.g. trust user "hue" to authentication on behalf of other users - e.g. that were authenticated into Airflow using LDAP or some other mechanism).

E.g. for spark it's just one parameter --proxy-user that is added to spark-submit.

http://www.cloudera.com/documentation/enterprise/5-4-x/topics/sg_spark_auth.html

**Comment by r39132** [comment]
Agree. This is a good feature to add. Adding the E/HW labels.

**Comment by dgies** [comment]
This is pretty much a requirement for me to be able to run a multi-tennant Airflow server.  User's jobs need to run under their own credentials in order to be able to write to their HDFS resources.  Without this the account running the executor needs to own the data for every user's jobs.

**Comment by bolkedebruin** [comment]
I think I already implemented this for the HiveHook (ie. for the kerberos side of things).

There is however a big difference between running jobs as a separate user (ie. airflow changes its uid to another user) and doing the above. To do it properly you need something like privilege separation and authentication for the dags (ie signing them and then verifying them against a key that is known and authorized).

Of course you could just add (like I did in the HiveHook) the option to use a proxy user, but lets say I would have a very tough discussion with my security people if I would like to use this feature.

**Comment by Tagar** [comment]
For us, service accounts are considered more secure.
E.g. let's comapre with airflow and ... sshd
- sshd:
  
  runs under root (real user id), and after user authenicates, uid locks down to an actual (effective user), so sshd child processes are running for that actual user. 
- Airflow:
  
  You have a service (airflow) that runs under one user ("airflow" is "real user id") and has ability to impersonate to other actual users after they are authenitcated by the service ("effective userid").

Given this example, I think it'll be easier to explain to the security people that this is actually more secure? I guess sshd might be a good reference point here.

``` shell
$ pstree -up | grep ssh
        |-sshd(2262)-+-sshd(2859)---sshd(2861,rdautkha)---ksh(2862)
        |            |-sshd(4967)---sshd(4973,rdautkha)---ksh(4974)-+-grep(5990)

$ ps -ef | egrep "2262|2859"
root      2262     1  0  2015 ?        00:00:11 /usr/sbin/sshd
root      2859  2262  0 Jan26 ?        00:00:00 sshd: rdautkha [priv]
rdautkha  2861  2859  0 Jan26 ?        00:00:00 sshd: rdautkha@pts/1

```

In our organization service accounts and authentication of end users by middle tier services/applications is considered a more secure practice. Thank you.

**Comment by bolkedebruin** [comment]
Exactly. Like I wrote the ideal way to go is privilege separation and have airflow set the effective uid. And yes ssh was what I had in mind. This is not trivial to implement though.
