### ISSUE TITLE
Import connections/variables from a file

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9855]
Hello,

We have a new local file system secret backend that allows us to load connections and variables from files. We support 3 file formats: YAML, JSON, ENV.
https://airflow.readthedocs.io/en/latest/howto/use-alternative-secrets-backend.html#local-filesystem-secrets-backend
https://github.com/apache/airflow/blob/master/airflow/secrets/local_filesystem.py
I think we can use the same code to create new commands for the CLI that allow us o import connections or variables. 

Best regards,
Kamil

**Comment by utkarsharma2** [comment]
Hey mik-laj,

What should happen to existing connections? should we override them?/let them be untouched?/ask for user input?

**Comment by mik-laj** [comment]
>Hey mik-laj,
> 
> What should happen to existing connections? should we override them?/let them be untouched?/ask for user input?

@utkarsharma2 By default, the operation should be canceled, but with an additional option it should be possible to change this behavior ``--overwrite-existing``.

**Comment by utkarsharma2** [comment]
Hey @mik-laj,

There is already a feature to import variables - `airflow variables import file`, however, this command only accepts the JSON file. Should we augment, existing command?

**Comment by mik-laj** [comment]
I thought about the extra option for a longer time and I don't think this will cover all cases.

I thiink, we need `merge-dispossition` It should specifies the action that occurs if the variables/connection already exists. 
We should support the following values are supported:
`OVERWRITE`: If the table variable/connection exists, we should overwrites the data.
`IGNORE`: If the table variable/connection exists, we should skip this connection/variable.
`RESTRICT`: If the variable/connection already exists, an exception is raised.

The default value should be RESTRICT. Each command invocation should be atomic and only occurs if all changes is able to complete successfully (one transaction).

**Comment by mik-laj** [comment]
We should handle reading values from a standard input. `airflow connection import -` should read value from stdin instead file.

**Comment by caioalmeida97** [comment]
@mik-laj is there any updates on this feature? I tried to run `airflow connections import $JSON_FILE` but it didn't work :(

**Comment by mik-laj** [comment]
Here is PR:https://github.com/apache/airflow/pull/9907 Feel free to continue it

**Comment by chutcheson** [comment]
I'm looking for a good first issue to work on.

Is this a correct account of the feature request?

> When using the airflow command line interface tool, I want to be able to import connections to databases or other services using a file that specifies the details associated with the connection.

Is there anything else that I should understand with respect to the request?

**Comment by uranusjr** [comment]
That sounds correct to me.

**Comment by mik-laj** [comment]
@chutcheson  Yes. We just want to import connections from a file.

**Comment by natanweinberger** [comment]
I started a first crack at this issue a few days ago, apologies for not posting sooner. I'll open a PR for it shortly. @chutcheson, would be great to get your feedback since you're interested in this issue as well!
