### ISSUE TITLE
Export connection/variable to file

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9856]
Hello,

We have a ticket about importing connections and variable
https://github.com/apache/airflow/issues/9855

- `airflow connections export`
- `airflow variables export`

To facilitate the management, it would also be useful to create this file using the CLI. We should support 3 file formats.

Best regards,
Kamil Breguła

**Comment by rootcss** [comment]
@mik-laj I'd like to work on this. Can you assign this to me?

**Comment by mik-laj** [comment]
@rootcss I assigned you to this ticket

**Comment by rootcss** [comment]
@mik-laj Just to be clear about the scope of this issue, describing it here:
We should have a CLI command: `airflow connection export --format=<format> --output-file=/path/to/your/file/name.json`
It should export it in the following formats: `json`, `yaml` and `env`.

The exported connections should be the list of all saved connections in the airflow metadatabase.

Let me know what do you think about this.

**Comment by mik-laj** [comment]
@rootcss  SGTM. It is worth writing documentation for this, which will describe this command. I am thinking of an extra section on this page
https://airflow.readthedocs.io/en/latest/howto/connection/index.html

**Comment by rootcss** [comment]
Sure. :+1:

**Comment by kaxil** [comment]
Can this be closed @mik-laj ? 

i am closing it for now -- let me know if you feel that we need to do more here
