### ISSUE TITLE
check-integrations  pre commit test failing when it shouldn't

### ISSUE THREAD

**Issue by scrambldchannel** [apache/airflow#9866]
**Apache Airflow version**: 2.0.0.dev0 (ie master branch)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**:

- **Cloud provider or hardware configuration**: Local
- **OS** (e.g. from /etc/os-release): Ununtu 20
- **Kernel** (e.g. `uname -a`): 5.4.0-40-generic #44-Ubuntu SMP x86_64 GNU/Linux
- **Install tools**: git
- **Others**:

**What happened**:

When triggered by a file change, the check-integrations pre-commit test failed with:

```
- hook id: check-integrations
- exit code: 1

./scripts/ci/pre_commit/pre_commit_check_integrations.sh: line 26: AVAILABLE_INTEGRATIONS: unbound variable
```

**What you expected to happen**:

It should pass or fail in a way related to the file change. The variable should be defined and this has nothing to do with the changes that trigger the file.

A change was made that removed the processing of `_script_init.sh` in `pre_commit_check_integrations.sh`

**How to reproduce it**:

Change one of the triggering files as per `.pre-commit-config.yaml` and run `pre-commit run check-integrations`

**Anything else we need to know**:

I came across this while working on https://github.com/apache/airflow/pull/9858

I've created a change in a branch that seems to fix it but not entirely sure it's correct. I can pull into a simple PR if desired. 

https://github.com/scrambldchannel/airflow/tree/integration_pre_commit

**Comment by kaxil** [comment]
Fixed in https://github.com/apache/airflow/pull/9869
