### ISSUE TITLE
Editing DAGs through ui

### ISSUE THREAD

**Issue by apoorvanand** [apache/airflow#9871]
Currenlty users can only view the code of DAG in ui but if it support the editing also it would be great feature to consider .

**Comment by eladkal** [comment]
I'm not sure if this is a good idea
Wouldn't you want to code review DAGs before deploying it?
Also I'm not even sure if this is doable as with DAG [siralization](https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html#dag-serialization) the webserver doesn't have access to the DAG folder.

@vikramkoka @kaxil WDYT?

**Comment by kaxil** [comment]
There is this nice plugin you can use: https://github.com/andreax79/airflow-code-editor

PS: I have not tested it but seems popular

But yeah I don't think we will integrate it in core as like Elad mentioned we use DAG Serialization and with the assumption that the Webserver might not have access to the Dag files.

The plugin I linked can work for you if it has access to Dag files

**Comment by potiuk** [comment]
Yeah. Editing code in Airflow UI is baaaaad idea. 

However if you integrate Airflow with DAGs via `git-sync` and if your code is in GitHub - you can get what you want - nice, web-driven DAG code editing but also all the benefits of code reviews, access control etc. etc. I highly recommend this kind of worklfow. 

Shall we close this one?
