### ISSUE TITLE
Statsd metrics

### ISSUE THREAD

**Issue by asselism** [apache/airflow#9928]
**Apache Airflow version:** 1.10.11

**Environment:**

    OS (e.g. from /etc/os-release): Red Hat
    Python: 3.6

Hi, I was using statsd metrics reporting and I noticed that the "DAG bag size" metric seems to only give the number of active DAGs, not the total number of DAGs. Also the "total parse time" gives a number that is much higher (about 5 times higher) than the number given when I run "airflow list_dags -r". I was wondering what is the reason behind this discrepancy and how can I get the total number of DAGs from statsd metrics. Thank you!

**Comment by ashb** [comment]
This should be fixed up in 2.0 -- we massively re-worked the dag parsing and metrics it emits.

Could you try there and let us know if it's still a problem?
