### ISSUE TITLE
Extra links for Google Cloud operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9941]
Hello,

Airflow has support for [extra links](https://airflow.readthedocs.io/en/latest/howto/define_extra_link.html), but it is wide-supported common. Only [4 operators](https://github.com/apache/airflow/blob/master/airflow/serialization/serialized_objects.py#L45-L48) support it.

I think we should focus on the most popular services first.

- [x] Cloud Storage https://github.com/apache/airflow/pull/23865
- [x] BigQuery https://github.com/apache/airflow/pull/23165
- [x] Dataflow https://github.com/apache/airflow/pull/21639
- [x] Dataproc https://github.com/apache/airflow/pull/10343

In the next step, we can add operators for the remaining services.

- [ ] AutoML https://github.com/apache/airflow/pull/25466
- [x] BigQuery Data Transfer Service https://github.com/apache/airflow/pull/22280
- [x] Bigtable https://github.com/apache/airflow/pull/23164
- [ ] Cloud Build
- [ ] Compute Engine https://github.com/apache/airflow/pull/25608
- [ ] Cloud Data Loss Prevention (DLP)
- [ ] DataFusion
- [ ] Datacatalog
- [x] Datastore https://github.com/apache/airflow/pull/23110
- [ ] Deployment Manager
- [ ] Cloud Functions
- [ ] Cloud Firestore
- [ ] Cloud Key Management Service (KMS)
- [ ] Cloud Life Sciences
- [x] Kubernetes Engine https://github.com/apache/airflow/pull/24786
- [ ] Machine Learning Engine https://github.com/apache/airflow/pull/26836
- [ ] Cloud Memorystore
- [ ] Natural Language
- [ ] Cloud Pub/Sub
- [ ] Cloud Secret Manager
- [ ] Cloud Spanner
- [ ] Cloud Speech-to-Text
- [ ] Cloud SQL
- [ ] Cloud Stackdriver
- [ ] Storage Transfer Service
- [ ] Cloud Tasks
- [ ] Cloud Text-to-Speech
- [ ] Cloud Translation
- [ ] Cloud Video Intelligence
- [ ] Cloud Vision

If you decide to finish this ticket you don't have to do all the work yourself. One PR can only deal with a single file/provider and it's ok.

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

If you haven't used the GCP yet, after creating the account you will [get $300](https://cloud.google.com/free). The implementation of this task will allow a better understanding of GCP services. If anyone is interested in this task, I am willing to provide all the necessary tips and information.

If anyone is interested in this task, I am happy to provide all the necessary tips and information. 

Best regards,
Kamil

**Comment by mik-laj** [comment]
@dossett Would you like to help with this ticket?

**Comment by dossett** [comment]
@mik-laj Once we upgrade past 1.10.3 I will definitely try to contribute to this.  Hopefully soon!

**Comment by thaohtp** [comment]
@mik-laj Hi, I'm thinking to give a try on Cloud Storage, I'm new to this project. I'd love to get your clear idea on how do we get bucket name and object name for GCS link. 

Looking at previous examples, mostly we generate urls from xcom, however I'm thinking to take it from operator parameter `bucket_name/objects`. Getting xcom makes sure the task executed, which means we can be sure GCS bucket/object existed. However, I feel it's still fine by getting from operator parameter. What do you think?

**Comment by edithturn** [comment]
@mik-laj I have some experience with Google Cloud, I would really happy to work on this issue. Could you please provide me with the tips and information to start it? I will appreciate it.

**Comment by Dark-Knight11** [comment]
Hi, I would like to add operators for Compute Engine service. Can you please guide me on it?

**Comment by lwyszomi** [comment]
We already working to update all existing google operator, I think we sent several PR related to this issue. @wojsamjan please include this issue in the PR's with the links to the google operators.

**Comment by eladkal** [comment]
@lwyszomi Do you need this issue for tracking? it seems like you are doing it independently and no one else in the community chime in this effort so I wonder if we should keep this issue open?
If you would like community assistance I suggest maybe add some description/instructions so new contributors can help?

**Comment by lwyszomi** [comment]
@eladkal I forgot that this issue exists, I will check with my list and I will update this one. Maybe is not needed any more

**Comment by lwyszomi** [comment]
@eladkal I don't have permissions to update this issue, but I added link to all PR that was sent to the community.

**Comment by eladkal** [comment]
OK since this list doesn't really help you I'm closing this issue.
If you will need community help please comment and we will revisit what is the best way to handle it (single vs multiple issues)
