### ISSUE TITLE
Incorrect signature of operators

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#9942]
Hello,

Currently, the signatures of most operators look similar to the following.
```python
    @apply_defaults
    def __init__(
        self, sql: str, conn_id: Optional[str] = None, *args, **kwargs
    ) -> None:
        super().__init__(*args, **kwargs)
        self.conn_id = conn_id
        self.sql = sql
```
There are two problems here.
1. The ``apply_default`` decorator forces all arguments to be passed as keyword arguments, but this information is not marked in the signature. As of Python 3 it is possible to mark arguments as [keyword-only argument](https://www.python.org/dev/peps/pep-3102/).
2. The `*args` is passed to the BaseOperator class, but this class does not accept positional arguments.

The new operator signature may look like folllow
```python
    @apply_defaults
    def __init__(
        self, *, sql: str, conn_id: Optional[str] = None, **kwargs
    ) -> None:
        super().__init__(**kwargs)
        self.conn_id = conn_id
        self.sql = sql
```

This change will allow the detection of improper operator initialization by static code analysis tools. This will also improve the operator's documentation as the method signature is available in the Python API Reference.

This change is backward-compatible because the positional arguments were not accepted before, but this was not enforced by the Python interpreter, but by an ddecorator.

We can use Bowler to do it. 

Best regards,
Kamil

**Comment by LeonY1** [comment]
Is it okay if I take up this issue? Is there any CLA that I have to sign in order to contribute?

**Comment by mik-laj** [comment]
@LeonY1  CLA is not required.

**Comment by mik-laj** [comment]
@LeonY1  I assigned you to this ticket.

**Comment by LeonY1** [comment]
Should I also work on adding the positional marker back in?

**Comment by mik-laj** [comment]
@LeonY1  You can start. You are already assigned to this ticket so I cannot assign you again.
