### ISSUE TITLE
Allow logging configuration at the DAG level

### ISSUE THREAD

**Issue by fatmumuhomer** [apache/airflow#9955]
**Description**

Enable logging configurations at the DAG level to add more flexibility for logging when testing and troubleshooting

**Use case / motivation**

Airflow should provide a way for a DAG or set of DAGs to use a logging configuration specific to it/them. If desired a DAG could use the system logging level, but when necessary a DAG could use a specific logging config to override those settings. Once a DAG is running in an environment with no issues it is unlikely you would want debug logging enabled as it adds a lot of noise and takes up space. However, as new DAGs are promoted it might be helpful to enable debug logging ONLY on those DAGs while testing occurs.

**Related Issues**

Not that I know of.

**Comment by mik-laj** [comment]
Currently, it is possible to overwrite the configuration at the DAG File level. 
All you need to do is add a similar code. to the following.
```
import logging;
logging.getLogger('awesome-sdk').setLevel(logging.FATAL)
```
