### ISSUE TITLE
S3ToRedshiftTransfer and RedshiftToS3Transfer with role-based access control

### ISSUE THREAD

**Issue by selvamshan** [apache/airflow#9971]
Hi In S3ToRedshiftTransfer and RedshiftToS3Transfer  option for using role-based access control

**To specify role-based access control, provide the credentials-args string in the following format.
'aws_iam_role=arn:aws:iam::<aws-account-id>:role/<role-name>'**

```
copy sales
from 'emr://j-SAMPLE2B500FC/myoutput/json/' 
iam_role 'arn:aws:iam::0123456789012:role/MyRedshiftRole'
JSON 's3://mybucket/jsonpaths.txt';
```
Thanks and Regards
Selvaraj

**Comment by john-jac** [comment]
Hi Folks...I'd like to take this one if I may and if it is still applicable

**Comment by potiuk** [comment]
Feel free John!
