### ISSUE TITLE
Add time enabled as macro

### ISSUE THREAD

**Issue by tambulkar** [apache/airflow#9974]
**Description**
Add a macro that includes the time the dag was enabled (unpaused)
**Use case / motivation**
I need a task to take action based on how recently a dag was enabled without having to alter the dag everytime I enable it.

**Related Issues**

**Comment by jhtimmins** [comment]
Can you expand on what you're proposing? Can you not accomplish what you need with a custom macro? https://airflow.apache.org/docs/stable/tutorial.html?highlight=user_defined_macros

**Comment by tambulkar** [comment]
I just want to add a column to the DAG model that tracks the time a dag was paused/unpaused. I don't think user defined macros provide this functionality

**Comment by eladkal** [comment]
@tambulkar Can you elaborate on the use case where this functionality needed in a production DAG?

**Comment by turbaszek** [comment]
I think this is something that can be one of result of this discussion:
https://lists.apache.org/thread.html/r14e23de7b71f61e3e81b11eb84da2612938982c46c9824e884d8ba50%40%3Cdev.airflow.apache.org%3E

We could log this event similarly to what was proposed in this thread.
