### ISSUE TITLE
Celery Executor gets stuck running Noops on Completed Jobs

### ISSUE THREAD

**Issue by jpavlick** [apache/airflow#999]
Hey all,
I've recently started using airflow, and I'm trying to get it running in a production environment on AWS. We are using Celery Executor with a Redis backend. One thing I've noticed is that Airflow doesn't seem to allocate tasks in the most efficient way possible. For example, I have 16 workers running, but airflow only has 5 tasks in any kind of run/running state:

<img width="203" alt="screen shot 2016-02-12 at 4 55 03 pm" src="https://cloud.githubusercontent.com/assets/687426/13021482/7b04212a-d1a9-11e5-99e4-f8ef62f38c15.png">

I looked into Celery Flower and it looks like Celery is doing noops on _completed_ jobs. I'm not sure how it gets into this state, but it seems to keep all of the celery workers allocated so that new tasks can't get assigned. Here's an example from the logs:

```
[2016-02-12 21:52:15,049] {models.py:974} INFO - Executing <Task(PythonOperator): LOAD_monthlyVisitNbr > on 2016-02-11 00:00:00
[2016-02-12 21:52:15,073] {base_hook.py:53} INFO - Using connection to: 10.00.000.000
[2016-02-12 21:52:15,228] {base_hook.py:53} INFO - Using connection to: 10.00.000.000
[2016-02-12 21:52:22,314] {oracle_hook.py:84} INFO - Done loading. Loaded a total of 406 rows
[2016-02-12 21:52:22,352] {python_operator.py:66} INFO - Done. Returned value was: None
[2016-02-12 21:52:32,392] {models.py:124} INFO - Filling up the DagBag from /home/airflow/airflow/dags/omniture_reports.py
[2016-02-12 21:52:32,392] {models.py:197} INFO - Importing /home/airflow/airflow/dags/omniture_reports.py
[2016-02-12 21:52:32,584] {models.py:284} INFO - Loaded DAG <DAG: omniture_reports>`
```

I would expect the log to end with the `INFO - Done. Returned value was: None` line, rather than continue to load up the DagBag. (For reference, there are about 25 more instances of this after the log line I'm showing above.) Is there a way to prevent this from happening? Is this something in our config that we have done wrong? Appreciate the help

**Comment by bolkedebruin** [comment]
This will _most likely_ be fixed in 1.7.1. Please create Jira issue if this persists. @jlowin

**Comment by johnnason** [comment]
I'm seeing what I think could be a side effect of this issue, and I'd like a little more info on what was changed in behavior for 1.7.1.
In my case, we use a XCOM and I noticed it was (in my opinion) being erroneously cleared. Getting to the root of how it was cleared, I see the task was re-run in a similar "no-op" state as this issue alludes to, with me seeing the `INFO` messages after the true successful scheduled task run for `Filling up the DagBag` and then another message for `Previously Succeeded`. This caused the XCOM to clear even though the task was not truly run. I think that in and of itself is a bug, but in terms of the no-op run taking place do you have an Issue you could point me to so I can see the code changes and determine if it may be what we've seen as well? Thanks!

**Comment by jlowin** [comment]
@johnnason you're right, that is a bug. I just created an issue https://issues.apache.org/jira/browse/AIRFLOW-131

**Comment by johnnason** [comment]
Thanks @jlowin!
